### ISSUE TITLE
Build settings always reset

### ISSUE THREAD

**Issue by kockok** [CocoaPods/CocoaPods#10008]
* [v ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

no warnings/errors

## What happened instead?
```
[!] The `Tests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-/Pods--.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `App[Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-app/Pods-app.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```
## CocoaPods Environment
```
cocoapods (1.9.3)
cocoapods-core (1.9.3)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.4.0, 1.3.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.5.0, 1.4.1)
cocoapods-try (1.2.0, 1.1.0)
```
I've tried this solution from SO:
```
1.Target - > building settings- >ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES, Value type is Boolean, click on the other, change the value to $(inherited)
2.perform - pod update
3.Done
```

However, every time I run `pod install`, the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` field will reset.

**Comment by dnkoutso** [comment]
Are you sure you are editing your own user project and also save the value? Please upload a sample app demonstrating the issue.

**Comment by kockok** [comment]
The warnings were gone after I restarted the computer the other day.
I think that it could be solved by restarting the terminal.
