### ISSUE TITLE
v1.10.0.beta.2 error: custom shell script '[CP] Copy dSYMs' when precompiling framework is enabled.

### ISSUE THREAD

**Issue by lzzhang75** [CocoaPods/CocoaPods#10003]
# Report

## What did you do?
* Install v1.10.0.beta.2
* Add "Pre-compiling" depdency "pod 'CocoaLumberjack/Swift',             '~> 3.6', :binary => true" 
* Run `pod install`

## What did you expect to happen?
I expecte the xcode project can compile after the pod install

## What happened instead?
```
Error: Command PhaseScriptExecution failed with nonzero exit code.

Run custom shell script '[CP] Copy dSYMs'

rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/....../Library/Developer/Xcode/DerivedData/......../Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CocoaLumberjack.build/DerivedSources/CocoaLumberjack.framework.framework.dSYM" "/Users/....../Library/Developer/Xcode/DerivedData/....../Build/Products/Debug-iphonesimulator/CocoaLumberjack"
building file list ... rsync: link_stat "/Users/....../Library/Developer/Xcode/DerivedData/....../Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/CocoaLumberjack.build/DerivedSources/CocoaLumberjack.framework.dSYM" failed: No such file or directory (2)
```

### Stack

```
   CocoaPods : 1.10.0.beta.2
        Ruby : ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.6 (11E708)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/....../.rvm/rubies/ruby-2.4.6/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/....../.rvm/gems/ruby-2.4.6/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-binary      : 0.4.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
plugin 'cocoapods-binary'

platform :ios, '11.0'
use_frameworks!

AFNETWORKING_VERSION ||= '~> 3.1'

target 'UICollectionView' do
  pod 'AFNetworking/NSURLSession',         AFNETWORKING_VERSION, :binary => true
  pod 'AFNetworking/Reachability',         AFNETWORKING_VERSION, :binary => true
  pod 'AFNetworking/Serialization',        AFNETWORKING_VERSION, :binary => true
  pod 'CocoaLumberjack/Swift',             '~> 3.6', :binary => true
  pod 'Alamofire', '~> 5.2', :binary => true
end
```

## Project that demonstrates the issue
unrelated

## Additional Mote
v1.10.x added a build script "CocoaLumberjack-copy-dsyms.sh" when Precompiling is enabled. This script causes build error, as mentioned in the previous sections.

This new script wasn't in v1.9.3 when Precomiling was enabled using v1.9.3

**Comment by dnkoutso** [comment]
```
 :binary => true"
```

is not an official cocoapods dsl. This seems as a bug in the plugin you are using

**Comment by lzzhang75** [comment]
@dnkoutso  this is the Pre-compiling dependencies, here is the CocoaPods guides: https://guides.cocoapods.org/plugins/pre-compiling-dependencies.htm,

**Comment by dnkoutso** [comment]
@lzzhang75 good point. i will move to cocoapods-binary repo.

**Comment by dnkoutso** [comment]
@lzzhang75 https://github.com/leavez/cocoapods-binary is not an official cocoapods plugin as I thought it was. I recommend you file the issue there for fixing as the plugin doesn't seem to work with 1.10.0.beta.1.

Going to close as a fix is not in CocoaPods library but rather in the plugin.

**Comment by eugeneshih** [comment]
Having cocoapods support this feature as an official plugin would be really great.

**Comment by kingnight** [comment]
> Having cocoapods support this feature as an official plugin would be really great.

Very good Sugggestion！
