### ISSUE TITLE
🐛 : Unable to install pods using custom build configurations

### ISSUE THREAD

**Issue by luskin** [CocoaPods/CocoaPods#10015]
## What did you do?
1. Created 2 new build configurations and renamed the default `Debug` and `Release` configurations, configurations looks like this:

<img width="748" alt="Screen Shot 2020-08-27 at 2 54 17 PM" src="https://user-images.githubusercontent.com/5702322/91498761-323e9000-e875-11ea-8925-9892bc56f3a3.png">

2. Created two new schemes, `Staging` and `Production`

3. Added new build configurations, as currently understood from [the documentation here](https://guides.cocoapods.org/syntax/podfile.html#project), to the podfile like so:

```ruby
platform :ios, '10.0'

project 'Project',
  'Staging.Debug' => :debug,
  'Staging.Release' => :release,
  'Production.Debug' => :debug,
  'Production.Release' => :release

target 'Project' do
  ...
```

4. Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Receive an error that cocoapods is unable to find the configuration whitelisted? This error is very confusing and the only thing I can find on it a small issue regarding providing more information on the error, see here: https://github.com/CocoaPods/CocoaPods/issues/5113

`[!] Unknown configuration whitelisted: debug. CocoaPods found production.debug, production.release, staging.debug, and staging.release, did you mean one of these?`

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.6 (11E708)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'Project',
  'Staging.Debug' => :debug,
  'Staging.Release' => :release,
  'Production.Debug' => :debug,
  'Production.Release' => :release

target 'Project' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # STRIPE
  pod 'Stripe', '~> 19.0.1'
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  # PERMISSIONS
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  target 'ProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

**Comment by dnkoutso** [comment]
can you please upload a quick sample app demonstrating the issue?

**Comment by luskin** [comment]
@dnkoutso sure thing, I was able to reproduce very easily. 

1) Used `react-native init` to just simply create a blank project
2) `cd ios && pod install` <-- Works fine
3) Create custom build configurations `Staging.Debug`, `Staging.Release`, `Production.Debug`, `Production.Release`
4) Add custom build configurations to pod file (see issue above)
5) run `pod install` <-- broken

Here is my repro project:

https://github.com/luskin/cocoapods-broken-custom-configurations

**Comment by dnkoutso** [comment]
@luskin awesome thanks!

**Comment by dnkoutso** [comment]
@luskin is there a step that does not include React-native?

**Comment by dnkoutso** [comment]
I also have zero experience or setup with React Native.

**Comment by luskin** [comment]
This specific issue though has nothing to do with react-native, the ios folder of the project is essentially just an ios project. I used react-native because it's a 1 line command to create a new iOS project with Podfile and all that. If it would help I can simply copy out the ios folder for you into its own repo.

**Comment by dnkoutso** [comment]
It might help but I will also try to repro. The simpler the project the better.

**Comment by luskin** [comment]
it's extremely simple to run the project as is if you don't mind. all you have to do is run `yarn install` in the root directory, then `cd ios && pod install`.

**Comment by dnkoutso** [comment]
@luskin thanks again. apologies for my naiveness and almost laziness!

**Comment by luskin** [comment]
@dnkoutso i'm working on it now actually and I could be onto something, it seems as though if I keep the standard `Debug` and `Release` build config names around, and then just copy them into NEW `Staging` and `Production`... etc configurations, that `pod install` succeeds as expected. I'll keep digging but it seems as though the problem occurs when there it can't find what I expect it's looking for, which is a default `Debug` and `Release` configuration name.

**Comment by dnkoutso** [comment]
I think CocoaPods makes a lot of assumptions that debug/releases configurations exist.

**Comment by Jinxiaoming** [comment]
@luskin https://github.com/facebook/react-native/pull/29074

**Comment by Goldziher** [comment]
im also experiencing exactly the same issue as the OP

**Comment by Jinxiaoming** [comment]
You can define

```

**Comment by dnkoutso** [comment]
This seems like a Flipper issue then?

**Comment by Jinxiaoming** [comment]
This is a React Native issue, which used to integrate Flipper but not support pods configurations configurable til now.

So we can manually update the Podfile by rewriting the `use_flipper!` method to make it configurable for custom configurations

**Comment by dnkoutso** [comment]
Seems like OK to close for now as the issue is not in CocoaPods.

**Comment by Benzer1406** [comment]
Just to leave a clear solution here. Thankfully the solution is already merged, to RN 0.63.3, so you can either:
* comment `use_flipper!` in the Podfile
* add your configurations to the line like this: `use_flipper!(configurations: ['DebugConfig', 'ReleaseConfig'])`

**Comment by matinzd** [comment]
This seems flipper issue. 

```use_flipper!({ 'Flipper' => '0.98.0' }, configurations: ['Release-prod','Release-dev','Debug-prod', 'Debug-dev'])
```

**Comment by dcangulo** [comment]
Any solution for 0.69.3? `use_flipper!` has been removed in this version.

https://react-native-community.github.io/upgrade-helper/?from=0.69.1&to=0.69.3

**Comment by ko-devHong** [comment]
> 

I was in the middle of a react-native migration.  66.0 -> 0.70.0 

it work.

```
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :flipper_configuration => FlipperConfiguration.enabled(['DevDebug','ProdDebug','DevRelease', 'ProdRelease']),
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
```

**Comment by iaroslav-ternovyi** [comment]
> I was in the middle of a react-native migration. 66.0 -> 0.70.0
> 
> it work.
> 
> ```
>   use_react_native!(
>     :path => config[:reactNativePath],
>     :hermes_enabled => true,
>     :flipper_configuration => FlipperConfiguration.enabled(['DevDebug','ProdDebug','DevRelease', 'ProdRelease']),
>     :app_path => "#{Pod::Config.instance.installation_root}/.."
>   )
> ```

Thx mate!

**Comment by puniker** [comment]
In case it can help anyone, I was getting this error while setting up the environments and doing `pod install`.
To fix it, delete this line `:flipper_configuration => flipper_config` from Podfile because use_flipper is already being used.
