### ISSUE TITLE
file patterns: The `vendored_frameworks` pattern did not match any file.

### ISSUE THREAD

**Issue by VetriThiyagu** [CocoaPods/CocoaPods#10014]
## What did you do?
Hi,
Am creating a framework using CocoaPods, by importing some of the static libraries and classes. It was working fine till I add one 3rd party static framework. I copied that static framework into my local directory and added below lines in .podspec

s.static_framework = true
s.vendored_frameworks = '(PATH_TO_3RD PARTY STATIC FRAMEWORK)'

then I ran pod spec lint Project.podspec --verbose, It threw ERROR | file patterns: The vendored_frameworks pattern did not match any file. I have been stuck in this issue for last 2 days. Please help me to solve this.

## What did you expect to happen?

** BUILD SUCCEEDED **

## What happened instead?

file patterns: The vendored_frameworks pattern did not match any file

## Project that demonstrates the issue

Am creating a framework using CocoaPods, by importing some of the static libraries and classes. It was working fine till I add one 3rd party static framework. I copied that static framework into my local directory and added below lines in .podspec

s.static_framework = true
s.vendored_frameworks = '(PATH_TO_3RD PARTY STATIC FRAMEWORK)'

then I ran pod spec lint Project.podspec --verbose, It threw ERROR | file patterns: The vendored_frameworks pattern did not match any file. I have been stuck in this issue for last 2 days. Please help me to solve this.

**Comment by VetriThiyagu** [comment]
Hi,
Am creating a framework using CocoaPods, by importing some of the static libraries and classes. It was working fine till I add one 3rd party static framework. I copied that static framework into my local directory and added below lines in .podspec 

s.static_framework = true
s.vendored_frameworks = '(PATH_TO_3RD PARTY STATIC FRAMEWORK)'

then I ran pod spec lint Project.podspec --verbose, It threw ERROR | file patterns: The `vendored_frameworks` pattern did not match any file. I have been stuck in this issue for last 2 days. Please help me to solve this.

**Comment by dnkoutso** [comment]
when you run `pod spec ling` cocoapods will clone the sources and the tag you specify in `s.source`. Its possible your framework is not present at this tag.

At this time I do not see a cocoapods bug yet so I am going to preemptively close. I will re-open if we find out its a cocoapods bug.

**Comment by VetriThiyagu** [comment]
Hi @dnkoutso ,
Thank you very much for the reply, As am new to the CocoaPods, Can you please explain me the necessary steps to include 3rd party static framework which is compiled using Carthage in my Cocoapod framework ?
What I am doing in my project:
I am creating a framework which includes c++ static library, objective-C and Swift classes, none of these are 3rd party, I needed to include one more 3rd party static framework which is compiled using Carthage, It was throwing an error. So could you please help me to get through?
