### ISSUE TITLE
[CP] Embed Pods Frameworks - Not added to Framework Target - Runtime Error: dyld: Library not loaded

### ISSUE THREAD

**Issue by bboyle18** [CocoaPods/CocoaPods#10010]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I have a `Framework` target that I build to produce a framework file that is consumed by other apps. This framework also uses a small number of third party frameworks, like AFNetworking.
After introducing Swift into the framework code base, I've recently switched from distributing as a static framework to a Dynamic Framework by specifying `use_frameworks!` in my Podfile.

Since doing this, `[CP] Embed Pods Framworks` is not added as a script in my Framework target's build phases.
This prevents my third party framework dependencies from being added to my Dynamic Framework, thereby causing a runtime error (`dyld: Library not loaded`) when integrating my framework into an app.

- Is there a specific reason why framework targets to not get `[CP] Embed Pods Framworks` build phase step added to them by Cocoapods? I can see in the code where Cocoapods [explicitly excludes library targets](https://github.com/CocoaPods/CocoaPods/blob/6835eff45279bfaea557677491acc6aa4dd4897f/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_integrator.rb#L34-L38). I'd love to understand why.
- Is there any way that I can ensure that my third party dependency frameworks get embedded in my Dynamic Framework and not having to declare them as dependencies externally?

Thanks for any suggestions or advice! 😄 

## What did you do?

I switched to using Dynamic frameworks with Cocoapods.

## What did you expect to happen?
I expected that the script `[CP] Embed Pods Frameworks` would have been added to my Build Phases for my framework target, in order to copy my third party framework dependencies into my own `.framework`.

## What happened instead?
when I build my framework and then integrate it with another app I get the following error:
```
dyld: Library not loaded: @rpath/AFNetworking.framework/AFNetworking
  Referenced from: /Users/brianboyle/Library/Developer/CoreSimulator/Devices/2FA16AB1-5D39-474F-99FF-01D2C4FD93BC/data/Containers/Bundle/Application/24CB3BBE-2C7F-4016-BC49-A133F8E64D65/ExSee.app/Frameworks/MyFramework.framework/MyFramework
  Reason: image not found
```
The root cause of this is that my third party dependency frameworks are not copied into my `MyFramework.framework`.

## CocoaPods Environment
Using cocoapods `1.10.0.beta.2` (have also tried this on the latest stable version 1.9.3)
```
source 'https://cdn.cocoapods.org/'
platform :ios, 12
use_frameworks!

target 'MyFramework' do
    pod 'AFNetworking'
end
```

**Comment by dnkoutso** [comment]
I think CocoaPods always meant to copy frameworks to app targets therefore this is why this is not happening. I think its historical reasons and could be a breaking change if we decided to change it so. This is a very quick glimpse and thoughts on this though so I might be a bit wrong.

**Comment by bboyle18** [comment]
Thanks for clearifying @dnkoutso 👍 
I'm curious what process others use for including third party frameworks in their Dynamic Framework. Would love to hear other people's approaches to working around this.
Thanks!

**Comment by dnkoutso** [comment]
You can perhaps copy them manually? is this for SDK development? Do you also get a warning that talks about "library development" and so forth?

**Comment by Rusty6113** [comment]
- **_[]()_**

**Comment by bboyle18** [comment]
Yep, its for SDK development @dnkoutso 
Could definitely copy them manually, but want to automate this and not deviate too much with custom scripts from the standard cocoapods way of doing things.
I understand that this approach or Dynamic Framework + third party frameworks is not support out of of the box by Cocoapods. Just really curious as to how others doing SDK development handle this, since I doubt I'm the only one 😄

**Comment by dnkoutso** [comment]
Yeah its a good question.............................. I dont think we offer great 1st party support for SDK development. I assume folks use custom script phases to copy over the frameworks if they are dynamically included.

I _think_ Apple does not allow umbrella frameworks to ship so I think for SDK development you have to use static linking which CocoaPods now supports.

**Comment by bboyle18** [comment]
Yep, I've gone down the route of statically linking third party libs. It's works ok, but the Copy Resources build phase script fails for macCatalyst builds because Assets are stored in a different resources directory. 
Still need to figure out how to exclude this script running for macCatalyst. 

Thanks for the info @dnkoutso, it's hep confirm that I'm not configuring cocoapods incorrectly👍🏻.
I'm going to close the issue, but would still welcome other thoughts or peoples experiences of sdk development with cocoapods.

**Comment by dnkoutso** [comment]
@bboyle18 

> but the Copy Resources build phase script fails for macCatalyst builds because Assets are stored in a different resources directory.
Still need to figure out how to exclude this script running for macCatalyst.

If this is something we can fix for CocoaPods perhaps its worthwhile?

**Comment by bboyle18** [comment]
@dnkoutso Sure! I'm on vacation at the moment, so will post specific details in a few days.
