### ISSUE TITLE
Unable to add dependency in development pod via Carthage 

### ISSUE THREAD

**Issue by GOKUXGOD** [CocoaPods/CocoaPods#10011]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I have a codebase which is distributed via pod
Suppose a Network Pod, as of now its podSpec has Alamofire as a dependency,

Now I want to integrate Alamofire via Carthage in my Network pod
so I have removed Alamofire pod by removing Alamofire from Network Pod's podspec
and run pod install

Next I have added Cartfile and its content are just plain:
github "Alamofire/Alamofire" ~> 5.2

I have run Carthage update --platform iOS
Carthage successfully produced framework in Build/iOS folder

Now trying to add Alamofire via Carthage followed all steps:

https://github.com/Carthage/Carthage#adding-frameworks-to-an-application

I have added frameworks search path:
$(SRCROOT)/Carthage/Build/iOS

But when I import Alamofire in my Dev pod it triggers error :
No such module 'Alamofire'

Please help or suggest that what I am doing is right or this is completely useless

As this is just a beginning for a particular task in which I have to give both CocoaPods and Carthage support to all my dev pods

**Comment by dnkoutso** [comment]
CocoaPods does not support working with Carthage as a first class party support. You have to do the integration manually.
