### ISSUE TITLE
cocopods static library header file name conflicts

### ISSUE THREAD

**Issue by jiqimaogou** [CocoaPods/CocoaPods#10019]
## What did you do?

I have two dependencies in my target:

```
pod `a_framework` # framework
pod `b_sourcecode` # static library
```

both two library have a header file named `error.h`
and in `b_sourcecode` have a code `#include "error.h"`.

when it compile `b_sourcecode`, the `a_framework`'s `error.h` was found. so it errors.

## What did you expect to happen?

find `b_sourcecode`'s error.h.

## What happened instead?

find `a_framework`'s error.h.

## CocoaPods Environment

1.7.5

## what have I tried

```
pod `b_sourcecode`, :modular_headers => true
```

it does not works.

**Comment by dnkoutso** [comment]
i do not think you can do much here but fix the sources to use framework imports rather than quote imports. Its possible the header search paths of the first framework to be above the static library one (depending on naming) and its the one that is found first.
