### ISSUE TITLE
Incomplete Pod source folder when using :git and :branch

### ISSUE THREAD

**Issue by rpitting** [CocoaPods/CocoaPods#10032]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I am trying to use the branch of a fork for the EarlGrey Pod with fixes for iOS 14.

My Podfile looks like this

```ruby
platform :ios, '10.0'

target 'EGTest' do
  use_frameworks!

  pod 'EarlGrey', :git => 'https://github.com/AdevintaSpain/EarlGrey.git', :branch => 'ios-14-compatibility'
end
```

## What did you expect to happen?

The Pod is successfully installed, using the latest commit of the branch

## What happened instead?

However, after `pod install` the contents of Pods/EarlGrey only contain the README and LICENSE file, just as if it's the initial commit.

I also tried in on a different machine, same outcome.

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.7 (11E801a)
         Git : git version 2.18.0
Ruby lib dir : /Users/rpittinger/.rbenv/versions/2.6.3/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ e533cea5b3210f81564d4de4a28a671374348cc0

               exaring-amazon-fling-sdk - git - git@git.exaring.net:ios/amazon-fling-sdk.git @ 3c7beb7998a7cf2785400d6793c7087935862b82

               exaring-amazon-login-sdk - git - git@git.exaring.net:ios/amazon-login-sdk.git @ 64930d8943ff8e064149cbd94f5e241dc6c46c4e

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/rpittinger/.rbenv/versions/2.6.3/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'EGTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EGTest
  pod 'EarlGrey', :git => 'https://github.com/AdevintaSpain/EarlGrey.git', :branch => 'ios-14-compatibility'

end
```

**Comment by dnkoutso** [comment]
Hmmm... this seems like an interesting case. Just because you specify a branch it does not mean the podspec on that branch points to the sources.

From what I saw in that branch EarlyGray podspec still points to a pre compiled .zip file and a vendored framework only.

https://github.com/AdevintaSpain/EarlGrey/blob/ios-14-compatibility/EarlGrey.podspec.json#L19 and https://github.com/AdevintaSpain/EarlGrey/blob/ios-14-compatibility/EarlGrey.podspec.json#L37

It seems to me the bug here is that CocoaPods should be correctly linking the vendored framework which it appears it does not...
