### ISSUE TITLE
'pod trunk push' failed.

### ISSUE THREAD

**Issue by LuokuangLBS** [CocoaPods/CocoaPods#10038]
When I push my podspec file to trunk ( pod trunk push LKMapSDK_Base.podspec --verbose), I get error like this 'Source code for your Pod was not accessible to CocoaPods Trunk. Is it a private repo or behind a username/password on http?'.
Anyone can help me?

podspec file like this:
Pod::Spec.new do |s|
  s.name             = 'LKMapSDK_Base'
  s.version          = '2.5.0'
  s.summary          = '箩筐地图iOS SDK（CocoaPods箩筐地图官方库），基础功能包'

  s.description      = <<-DESC
箩筐地图iOS SDK（CocoaPods箩筐地图官方库），基础功能包。提供基础功能。
                       DESC

  s.homepage         = 'https://lbs.luokuang.com'
  s.license          = { :type => 'Copyright', :text => 'Copyright © 2020 LuoKuang. All Rights Reserved.' }
  s.author           = { 'LuokuangLBS' => 'haofp@luokung.com' }
  s.source           = { "http": "https://lkbj.cn-bj.ufileos.com/lbs/static/zip/LKMapSDK_Base_2.5.0.zip" }
  s.source_files = 'LKMapSDK_Base.framework/**/*.{h}'
  s.ios.deployment_target = '9.0'
  s.requires_arc = true
  s.frameworks = 'UIKit', 'CoreLocation'
  s.public_header_files = 'LKMapSDK_Base.framework/Headers/*.h'
  s.vendored_frameworks = 'LKMapSDK_Base.framework'
  s.libraries = 'c++'
end

**Comment by dnkoutso** [comment]
For private repos please use `pod repo push` instead of `pod trunk push` which is reserved for public CocoaPods.

**Comment by LuokuangLBS** [comment]
Thank u. The reason is 'https://lkbj.cn-bj.ufileos.com' can not be visited in some case.
