### ISSUE TITLE
Code Coverage when using :generate_multiple_pod_projects is not working

### ISSUE THREAD

**Issue by ricardorauber** [CocoaPods/CocoaPods#10034]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run the tests in a project with local pods and using the :generate_multiple_pod_projects flag.

## What did you expect to happen?

All tests run and the coverage is gathered.

## What happened instead?

The tests run fine, but the coverage is not right.

### Stack

```
   CocoaPods : 1.10.0.beta.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.7 (11E801a)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-binary      : 0.4.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
install! 'cocoapods', :generate_multiple_pod_projects => true
platform :ios, '12.4'
inhibit_all_warnings!
use_frameworks!

def internal_pods
  pod 'Core',         :path => 'Modules/Core',         :testspecs => ['Tests'], :inhibit_warnings => false
  pod 'DesignSystem', :path => 'Modules/DesignSystem', :testspecs => ['Tests'], :inhibit_warnings => false
end

def external_pods
  #pod 'Alamofire',    '5.2.2'
  #pod 'RealmSwift',   '5.3.2', :modular_headers => true
  pod 'SwifterSwift', '5.2.0'
  pod 'SwiftLint',    '0.40.1'
end

def test_pods
  pod 'Nimble',            '8.1.2'
  pod 'OHHTTPStubs/Swift', '9.0.0'
  pod 'Quick',             '3.0.0'
end

target 'App' do
  internal_pods
  external_pods
end

target 'Tests' do
  internal_pods
  test_pods
end

target 'UI Tests' do
  test_pods
end
```

## Project that demonstrates the issue

[Template-iOS.zip](https://github.com/CocoaPods/CocoaPods/files/5177277/Template-iOS.zip)

**Comment by dnkoutso** [comment]
is code coverage enabled int he podspecs?

**Comment by ricardorauber** [comment]
Hi @dnkoutso, this is the podspec of the development pod:

```ruby
Pod::Spec.new do |s|
  
  # Info
  module_name = 'Core'
  s.name      = module_name
  s.version   = '0.1.0'
  s.summary   = module_name + ' module'
  s.homepage  = "http://www.poatek.com"
  s.license   = 'BSD'
  s.author    = 'Poatek'
  s.source    = {
    :git => 'https://poatek@dev.azure.com/poatek/MobileTeam/_git/' + module_name + ".git",
    :tag => s.version.to_s
  }
  
  # Project Setup
  s.ios.deployment_target = '12.4'
  s.swift_versions        = ['5.1', '5.2']
  s.pod_target_xcconfig   = { 'ENABLE_TESTABILITY' => 'YES' }
  s.static_framework      = true
  
  # Sources
  s.source_files = 'Source/**/*'
  
  # External Dependencies
  #s.dependency  'Burritos'
  
  # Tests
  s.test_spec 'Tests' do |test_spec|
    test_spec.requires_app_host = true
    test_spec.source_files      = 'Tests/**/*.{swift}'
    
    # Test Dependencies
    test_spec.dependency 'Nimble'
    test_spec.dependency 'Quick'
  end
  
end
```

and here are some images of the scheme that I am using to run the tests:

![Screen Shot 2020-09-08 at 09 16 08](https://user-images.githubusercontent.com/983661/92475655-224b7800-f1b4-11ea-85cc-214d441e6c0d.png)
![Screen Shot 2020-09-08 at 09 16 48](https://user-images.githubusercontent.com/983661/92475669-27a8c280-f1b4-11ea-80d0-0fc04c79fba0.png)
![Screen Shot 2020-09-08 at 09 16 57](https://user-images.githubusercontent.com/983661/92475678-2bd4e000-f1b4-11ea-9231-3c3ef9c20b67.png)

**Comment by ricardorauber** [comment]
I have many tests already and they are all running:

![Screen Shot 2020-09-08 at 09 22 35](https://user-images.githubusercontent.com/983661/92476249-072d3800-f1b5-11ea-8f28-bd4de3a35329.png)

But for some reason, the coverage is only showing 1 line of 1 file that is a property:

![Screen Shot 2020-09-08 at 09 23 01](https://user-images.githubusercontent.com/983661/92476339-2deb6e80-f1b5-11ea-956c-6868da77b5a0.png)

**Comment by dnkoutso** [comment]
@ricardorauber have you enabled:
```ruby
    test_spec.scheme = {
      :code_coverage => true, :environment_variables => {'FOO' => 'BAR' }
    }
```

for each test specs of yours?

**Comment by ricardorauber** [comment]
Hey @dnkoutso I did add the `:code_coverage => true` now but still it doesn't work. It looks really weird that it is only showing the init of 1 of the files from the local pod.

```ruby
Pod::Spec.new do |s|
  
  # Info
  module_name = 'Core'
  s.name      = module_name
  s.version   = '0.1.0'
  s.summary   = module_name + ' module'
  s.homepage  = "http://www.poatek.com"
  s.license   = 'BSD'
  s.author    = 'Poatek'
  s.source    = {
    :git => 'https://poatek@dev.azure.com/poatek/MobileTeam/_git/' + module_name + ".git",
    :tag => s.version.to_s
  }
  
  # Project Setup
  s.ios.deployment_target = '12.4'
  s.swift_versions        = ['5.1', '5.2']
  s.pod_target_xcconfig   = { 'ENABLE_TESTABILITY' => 'YES' }
  s.static_framework      = true
  
  # Sources
  s.source_files = 'Source/**/*'
  
  # External Dependencies
  #s.dependency  'Burritos'
  
  # Tests
  s.test_spec 'Tests' do |test_spec|
    test_spec.requires_app_host = true
    test_spec.source_files      = 'Tests/**/*.{swift}'
    test_spec.scheme            = { :code_coverage => true }
    
    # Test Dependencies
    test_spec.dependency 'Nimble'
    test_spec.dependency 'Quick'
  end
  
end
```

**Comment by dnkoutso** [comment]
I used your template with Xcode 11.2.1 (I haven't updated to latest 11.x)

<img width="1512" alt="Screen Shot 2020-09-11 at 1 47 02 PM" src="https://user-images.githubusercontent.com/310370/92961761-70bb7980-f435-11ea-97fb-50d19f0c9622.png">

Doesn't this look correct? i.e it seems to me coverage is generated correctly.

Perhaps an Xcode issue?
