### ISSUE TITLE
Can Cocoapods support SPM?

### ISSUE THREAD

**Issue by CveniEs** [CocoaPods/CocoaPods#10049]
In my project, A library use cocoapods, and B library use swift package manager, Can A library depend on the B library?
what can I do in A.podspec or do other things can make it goes well...

**Comment by dnkoutso** [comment]
No you cannot do this nor are there plans to support it at this time. Best thing to do is ask A library author to provide SPM support for their module.

**Comment by mfazekas** [comment]
FWIW I'm using a post_install script to add SPM reps to cocoa pods targets:

```ruby
def add_spm_to_target(project, target_name, url, requirement, product_name)
  project.targets.each do |target|
    if target.name == target_name
      pkg = project.new(Xcodeproj::Project::Object::XCRemoteSwiftPackageReference)
      pkg.repositoryURL = url
      pkg.requirement = requirement
      ref = project.new(Xcodeproj::Project::Object::XCSwiftPackageProductDependency)
      ref.package = pkg
      ref.product_name = product_name
      target.package_product_dependencies << ref
      project.root_object.package_references << pkg
    end
  end

  project.save
end


post_install do |installer|
    spm_spec = {
      url: "https://github.com/maplibre/maplibre-gl-native-distribution",
      requirement: {
        kind: "upToNextMajorVersion",
        minimumVersion: "5.11.0"
      },
      product_name: "Mapbox"
    }
    add_spm_to_target(
      installer.pods_project,
      "react-native-mapbox-gl",
      rpm_spec[:url],
      rpm_spec[:requirement],
      rpm_spec[:product_name]
    )
end
```

**Comment by iPile** [comment]
@mfazekas Hi, I found this script of yours and wanted to ask when are you executing it? I have encountered the same problem I believe you have with SPM and Cocoapods

**Comment by mfazekas** [comment]
> @mfazekas Hi, I found this script of yours and wanted to ask when are you executing it? I have encountered the same problem I believe you have with SPM and Cocoapods

@iPile I'm executing from the [`post_install`](https://guides.cocoapods.org/syntax/podfile.html#post_install) hook in cocoa pods.

**Comment by iPile** [comment]
@mfazekas are you specifying anything in the .podspec file? `pod repo push` still doesn't seem to find the swift package and returns `No such module`

**Comment by mfazekas** [comment]
@iPile we do have a [podspec](https://github.com/react-native-mapbox-gl/maps/blob/master/react-native-mapbox-gl.podspec), you can check it out. The structure is like this:
Like this:

foo.podspec
```ruby
def $foo._add_spm_to_target(project, target_name, url, requirement, product_name)
...
end

def $foo.post_install(installer)
  self._add_spm_to_target(installer.pods_project, "foo", spm_url, spm_requirement, spm_product_name)
end
```

Users Podfile:
```
post_install do |installer|
  $foo.post_install(installer)
end
```

Not sure about `pod repo push` cocoa pods will not see your spm deps for sure. You can use `--skip-import-validation` with repo push, but you probably should not declare your spm dept in podsspec `dependenty`.

**Comment by soumyamahunt** [comment]
@mfazekas I am getting [`No such module`](https://github.com/CocoaPods/CocoaPods/issues/11214) error as well. Also, I tried manually adding a swift package to `Alamofire` pod target and the result was same. Is there anything else I am missing? My Xcode version: `13.3.1 (13E500a)`.

**Comment by orta** [comment]
FWIW, this to me is a really good space for someone to write a comprehensive cocoapods plugin

**Comment by soumyamahunt** [comment]
> FWIW, this to me is a really good space for someone to write a comprehensive cocoapods plugin

@orta I was planning on that, but so far I haven't been able to manually add swift package to a pod target. I am always getting [`No such module`](https://github.com/CocoaPods/CocoaPods/issues/11214)  error.

**Comment by osrufung** [comment]
Hi! me too @soumyamahunt @mfazekas 

We tried, but probably because the template for those projects is not updated that package reference cannot be used. In fact, if you try later to include the Swift Package into that generated project, it gets stuck during the package fetching. Any idea?

**Comment by mfazekas** [comment]
@osrufung , @soumyamahunt I'm not expert in swift packages and their Xcode implementation. If you can solve the issue manually, then it's possible to compare the Xcode project files to see what dependencies/settings have not been added by the scripts.
