### ISSUE TITLE
Whether different subspecs are supported and applied to different targets

### ISSUE THREAD

**Issue by developeryh** [CocoaPods/CocoaPods#10042]
Whether different subspecs are supported and applied to different targets？

**Comment by dnkoutso** [comment]
I do not quite understand the question. I believe you can specify different subspecs for different targets yes.

Going to close as an incomplete issue report and we can continue discussion here.

**Comment by developeryh** [comment]
such as on a project has two target ,  targetA and targetB ,now in the Podfile 

target 'A' do
pod 'xxxxx/Core', '3.0.0'
end
target 'B' do
pod 'xxxxx/Supspec', '3.0.0'
end

it can't be work!
