### ISSUE TITLE
Command in plugin is not recognized

### ISSUE THREAD

**Issue by lianghanzhen** [CocoaPods/CocoaPods#10043]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. `sudo gem install cocoapods`
2. `sudo gem install cocoapods-generate`
3. `pod gen --platforms=ios --gen-directory=*** shared.podspec`

## What did you expect to happen?

A workspace should be generated.

## What happened instead?

Executing of 'pod gen --platforms=ios --gen-directory=*** shared.podspec' failed with code 1 and message:
[!] Unknown command: `gen`
Did you mean: env?

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache         Manipulate the CocoaPods cache
    + deintegrate   Deintegrate CocoaPods from your project
    + env           Display pod environment
    + init          Generate a Podfile for the current directory
    + install       Install project dependencies according to versions from a
                    Podfile.lock
    + ipc           Inter-process communication
    + lib           Develop pods
    + list          List pods
    + outdated      Show outdated project dependencies
    + plugins       Show available CocoaPods plugins
    + repo          Manage spec-repositories
    + search        Search for pods
    + setup         Setup the CocoaPods environment
    + spec          Manage pod specs
    + trunk         Interact with the CocoaPods API (e.g. publishing new specs)
    + try           Try a Pod!
    + update        Update outdated project dependencies and create new Podfile.lock

Options:

    --silent        Show nothing
    --version       Show the version of the tool
    --verbose       Show more debugging information
    --no-ansi       Show output without ANSI codes
    --help          Show help banner of specified command

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G6020)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.17.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c8bca35f64e897980bb4ea990a145dba26a87204
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Can you try updating to CocoaPods 1.9.3 or CocoaPods 1.10.beta?

**Comment by lianghanzhen** [comment]
1.9.3 works for me. Thanks.

**Comment by raorpiano** [comment]
I am using macbook with apple m1 chip, I tried installing cocoapods-generate, it says it installed but when I run pod gen, i get this error
[!] Unknown command: `gen`

**Comment by pauminku** [comment]
> I am using macbook with apple m1 chip, I tried installing cocoapods-generate, it says it installed but when I run pod gen, i get this error
> [!] Unknown command: `gen`

Same here, did you find any solution?

**Comment by RoqueCampos** [comment]
I vas having the same error on a Mac M1, and the following steps worked for me:

[https://github.com/CocoaPods/CocoaPods/issues/10712#issuecomment-866502317](url)

**Comment by pauminku** [comment]
@RoqueCampos, the link is not working. Thanks.

**Comment by xoif** [comment]
Why is this closed if pod gen is still not working (natively) on apple silicon with ruby 3.x and cocoapods 1.11.3

**Comment by AleksaaDj** [comment]
Any updates?
