### ISSUE TITLE
Cocoapods 1.10 beta 2 is not creating te file resources.sh

### ISSUE THREAD

**Issue by fabios9702** [CocoaPods/CocoaPods#10048]
I've added the AppClip target to the main app, but when I upload on App Store connect there is an error saying: 
"**ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.**"
so I've noticed that on the build phases of the App Clip was missing the script ** [CP] Copy Pods Resources**, I've added the script with the path of the App Clip Target: **""${PODS_ROOT}/Target Support Files/Pods-AppClip/Pods-AppClip-resources.sh"**; but the problem is that the file **Pods-AppClip-resources.sh** is not there, I've tried a lot of time to execute pod install and I've also tried to do pod deintegrate and then pod install, but the problem is still there. Do you have a solution that can work? Otherwise I can't upload the App on App Store Connect

podfile:
target 'AppClip' do
 use_frameworks! :linkage => :static
    pod 'Alamofire', '~> 4.8'
    pod 'SwiftyJSON'
    pod 'SDWebImage'
    pod 'Groot'
    pod 'SwiftEntryKit'
    pod 'Braintree/Apple-Pay'
end

**Comment by dnkoutso** [comment]
What version of xcodeproj gem are you using? can you `gem update xcodeproj` and try again?

**Comment by fabios9702** [comment]
I've updated and I'm using the version 1.18.0 _(if I do gem list I'm getting: xcodeproj (1.18.0, 1.17.1, 1.14.0))_. 
After the update the situation is the same, **the file Pods-AppClip-resources.sh is not there**, and also the script **[CP] Copy Pods Resources**, it's not in Xcode build phases.

**Comment by dnkoutso** [comment]
Can you please attach a small sample app?

**Comment by fabios9702** [comment]
I've created this empty project adding the AppClip target here is the link: https://github.com/fabios9702/TestAppClip
**Note** that this is not the project where I've the problem _(cause it's a private repository and I can't upload here)_, but I've created this project from scratch, added the app clip target, installed the pods and also here the **resources.sh is not there**  and also the script **[CP] Copy Pods Resources**, it's not in Xcode build phases.

**Comment by fabios9702** [comment]
any news?

**Comment by dnkoutso** [comment]
@fabios9702 from the initial issue report Podfile none of the Pods you have any resources? This is why this phase is not added.

The error you received from Apple does not seem to be related to resources?

**Comment by dnkoutso** [comment]
CocoaPods will not add this phase if there are no resources phase.

**Comment by fabios9702** [comment]
> @fabios9702 from the initial issue report Podfile none of the Pods you have any resources? This is why this phase is not added.
> 
> The error you received from Apple does not seem to be related to resources?

Yes it’s related to the resources cause the first time I’ve upload without compiling the bit code and then the App Clip crashes because was not founding the Alamofire library.
So how can I fix the issue?

**Comment by dnkoutso** [comment]
> not founding the Alamofire library

But this doesn't have to do anything with resources. You are statically linking your dependencies so there is no need to copy the dynamic framework either.

I do not know actually how to fix the issue, I suspect it _might_ be something we need to fix in CocoaPods for app clip support but I am fairly confident it doesnt have to do with resources.

**Comment by dnkoutso** [comment]
Does the Apple error message tell you *which* dynamic library it cant find?

**Comment by dnkoutso** [comment]
<img width="1792" alt="Screen_Shot_2020-09-11_at_1_35_31_PM" src="https://user-images.githubusercontent.com/310370/92960694-b0816180-f433-11ea-98a0-2a7ee26acb69.png">

proof that resources work. Adding 'GoogleMaps' pod which brings in resources seems to be adding the script phase.

The issue is different and has to do with a dynamic library being referenced by your executable either by your own specific project or a bug in CocoaPods with respect to app clips.

**Comment by pavlof01** [comment]
same problem

**Comment by fabios9702** [comment]
> same problem

I’ve solved not using anymore cocoa pods on app clip, I’m using Carthage + SPM

**Comment by dnkoutso** [comment]
sounds good thanks!
