### ISSUE TITLE
App Clips Multiple Pods Version

### ISSUE THREAD

**Issue by KrockodilL** [CocoaPods/CocoaPods#10047]
- [x]  I've read and understood the CONTRIBUTING guidelines and have done my best effort to follow.

## What did you do?
We're trying to integrate AppClips to our existing app. Main target of our app contains base version of our private pod, while appclips should contain another version - more compressed to fit Apple's 10mb size restriction 

## What did you expect to happen?

Multiple versions of a single pod in two different targets. 

## What happened instead?

After ```pod install``` I got:
[!] There are multiple dependencies with different sources for `MyPod` in `Podfile`:

- MyPod (from `https://gitlab.mycompany.com`, branch `develop`)
- MyPod (from `https://gitlab.mycompany.com`, branch `appClips`)
### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 11.7 (11E801a)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/o.sinev/.rvm/rubies/ruby-2.6.5/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 3e2fc0a2a690b503bd4424f6d3420a0de55a8e48

               mycompany-cocoapods-cocoapods - git - https://gitlab.mycompany.com/cocoapods/cocoapods.git @ 0e603426d925f813fae85425c7a58e63c547387e

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/o.sinev/.rvm/gems/ruby-2.6.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '11.0'

use_frameworks!

target 'MyTarget' do
 pod 'MyPod', :git => 'https://gitlab.mycompany.com, :branch => 'develop'
end

target 'MyTargetAppClips' do
 pod 'MyPod', :git => 'https://gitlab.mycompany.com, :branch => 'appClips'
end
```

**Comment by dnkoutso** [comment]
This is not related as much to app clips. Specifying a single pod across different sources is not supported at this time.

**Comment by dnkoutso** [comment]
Going to close as there are no plans right now to support pods coming in from multiple different sources.
