### ISSUE TITLE
Can't use my own pod

### ISSUE THREAD

**Issue by krotoff** [CocoaPods/CocoaPods#10057]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I made [my own pod](https://github.com/krotoff/KrotoffSwiftExtensions) and tried to use it. 

## What did you expect to happen?

Clearly working library of my methods and classes (not brilliant solutions, but it's in infinite progress :))

## What happened instead?

All my tries to use it in my projects was finished with failure: I can install pod, I can import it, but my projects don't see any classes/methods/properties. I made [a question on StackOverflow](https://stackoverflow.com/questions/63850195/my-cocoapods-framework-methods-are-not-available-by-import-in-another-app). And as you can see, other people can use my pod. So the problem is in my environment. But I can't find it. Please, help!

## CocoaPods Environment

Was reproduced on 1.10.1 beta as well.
### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.7 (11E801a)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TestProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestProject
  pod 'KrotoffSwiftExtensions'

end
```

## Project that demonstrates the issue

https://drive.google.com/file/d/15ynsB0YLdjKUfBDrYlEJqvNy__tXmKby/view?usp=sharing

Best regards,
Andrew.

**Comment by krotoff** [comment]
Oh, one clarification: all other pods work correctly, so the problem is in my pod and only on my Mac.

**Comment by dnkoutso** [comment]
I was able to successfully import and use a protocol from your pod.

<img width="1512" alt="Screen_Shot_2020-09-14_at_1_17_37_PM" src="https://user-images.githubusercontent.com/310370/93123400-a195eb80-f68d-11ea-907c-724a8e7a7774.png">

I recommend continuing to wait on StackOverflow as currently it seems cocoapods does the configuration and wiring properly.
