### ISSUE TITLE
Are there any method specifying framework linkage for `pod lib lint`?

### ISSUE THREAD

**Issue by EmingK** [CocoaPods/CocoaPods#10060]
For `Podfile` we have `use_frameworks! :linkage => :static`, specifying all framework pod targets using static linkage.

Does `pod lib lint` have something equivalent?

There are some pods not working correctly when using modular headers with `--use-libraries` option.

**Comment by dnkoutso** [comment]
Yes it is `--use-static-frameworks` in 1.9.x i think.

closing and we can continue the discussion here if something is missing or a bug i will re-open.

**Comment by EmingK** [comment]
> Yes it is `--use-static-frameworks` in 1.9.x i think.
> 
> closing and we can continue the discussion here if something is missing or a bug i will re-open.

Thanks for your reply!

I have checked that he option `--use-static-frameworks` is available since 1.10.x.

**Comment by dnkoutso** [comment]
@EmingK thank you and you are right https://github.com/CocoaPods/CocoaPods/pull/9632!

We just shipped 1.10.0.rc.1 today.
