### ISSUE TITLE
The Swift pod `react-native-blurhash` depends upon `React-Core`, which does not define modules...

### ISSUE THREAD

**Issue by mrousavy** [CocoaPods/CocoaPods#10068]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I've followed the suggested solution in https://github.com/facebook/react-native/issues/29633 and changed my module's Podspec to depend on `React-Core` instead of `React` since `React` is just an umbrella pod.

## What did you expect to happen?

I expected it to work normally and be future proof once the `React` umbrella pod gets removed

## What happened instead?

I get the error:

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `react-native-blurhash` depends upon `React-Core`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

## Workaround

After changing the Podspec, I've read that you need to enable modular headers for Swift projects to work statically linked. I've tried:

1. Setting `d.pod_target_xcconfig = { "DEFINES_MODULE" => "YES" }` in my podspec -> That didn't change anything, still same error
2. Setting `use_modular_headers!` in my app's Podfile -> That gave me this build error for glog instead: https://github.com/facebook/react-native/issues/26217

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ a7f1ce526bfbf3d34cdec4f462e03c06cda2201e

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Springsale' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # React Native Admob Native Ads
  pod 'Google-Mobile-Ads-SDK'

  target 'SpringsaleTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  # Note that if you have use_frameworks! enabled, Flipper will not work and you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

## Project that demonstrates the issue

This native module: https://github.com/mrousavy/react-native-blurhash installed in a react native 0.63.2 app and using Xcode 12.

**Comment by dnkoutso** [comment]
Please provide a sample app demonstrating the issue _without_ ReactNative.

**Comment by hengkx** [comment]
https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

same problem.

**Comment by mrousavy** [comment]
Yeah, looks like this happens because the pod I depend on (`React-Core`) does not specify `"DEFINES_MODULE" => "YES"` in it's `s.pod_target_xcconfig`. Is that required for Objective-C pods to be used in Swift projects?

**Comment by dnkoutso** [comment]
I think so yes.
