### ISSUE TITLE
Framework Not Found error in Xcode 12

### ISSUE THREAD

**Issue by hishak** [CocoaPods/CocoaPods#10073]
Cocoapods release:  1.9.3 and then 1.10
(same error with either release)

# Report

## What did you do?

Took working Xcode workspace and built/run with Xcode 12 for the first time.

## What did you expect to happen?

No errors.

## What happened instead?

**ld: framework not found Pods_CopticFind
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

### Stack

```
   CocoaPods : 1.10.0.rc.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ f699c2391bb95454a158c86988689268b5a78877

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'CopticFind' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OneSignal', '>= 2.11.2', '< 3.0'

end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OneSignal', '>= 2.11.2', '< 3.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

## What else did you try?
1.  Changed podfile platform command to match iOS Xcode Deployment Target:  12
(still same error)
2.  pod deintegrate
pod update
(still same error)
3.  Deleted podfile and podfile.lock and installed cocoapods from scratch followed by
pod init
pod repo update
pod install
(still same error)
4.  commented out 'use_frameworks!'
(still same error)
5.  Change Framework Search path to 'recursive'.
(still same error)

**Comment by dnkoutso** [comment]
Please upload a sample app demonstrating the issue.

**Comment by hishak** [comment]
Just trying to load this sdk into an Xcode 12 workspace.  My code is not in Github, and have no small sample app.
https://github.com/OneSignal/OneSignal-iOS-SDK

**Comment by dnkoutso** [comment]
I just tried it on a sample app and I was successfully able to build.

I am sorry without a sample app that shows the issue we can't be much of help.

Your best bet is to run `pod deintegrate` and `pod install` again.

**Comment by dnkoutso** [comment]
<img width="1792" alt="Screen_Shot_2020-09-20_at_12_25_16_PM" src="https://user-images.githubusercontent.com/310370/93720199-65a2d080-fb3c-11ea-9f40-e2314bb85729.png">

**Comment by hishak** [comment]
Yikes, ok, I have figured out how to tell Xcode to push my project to Github.
So, now you have the (sample) app.
https://github.com/hishak/CopticChurchLocatorSwift5

**Comment by dnkoutso** [comment]
Can you please update the sample app to include cocoapods and the issue at hand? I cant seem to compile it due to non-cocoapods issues.

**Comment by hishak** [comment]
Oh, when I told Xcode to push to Github, was there something I was supposed to select regarding Cocoapods?

**Comment by hishak** [comment]
Issue is that what worked before Xcode 12 does not work with Xcode 12.  No changes made other than upgrading to Xcode 12.
![Screen Shot 2020-09-20 at 16 39 59](https://user-images.githubusercontent.com/10100514/93721763-1bcbe180-fb60-11ea-9270-2728d2f74c86.png)

**Comment by hishak** [comment]
Framework exists.
![Screen Shot 2020-09-20 at 16 42 42](https://user-images.githubusercontent.com/10100514/93721816-7c5b1e80-fb60-11ea-96ea-9daa2baaaedf.png)
![Screen Shot 2020-09-20 at 16 45 14](https://user-images.githubusercontent.com/10100514/93721846-b6c4bb80-fb60-11ea-954b-e5a8382b002e.png)

**Comment by hishak** [comment]
Just checking, when you got the OneSignal SDK to build successfully above, was that with Xcode 12?
(works for me on 11.7 but not on 12).  Issue building is only with 12.

**Comment by dnkoutso** [comment]
yes that was with Xcode 12.

**Comment by hishak** [comment]
ok, again, is there something I need to do in Xcode to include cocoapods in the push to Github?

**Comment by dnkoutso** [comment]
yes, please add a `Podfile` run `pod install` to generate the workspace and build. Ensure that the build fails in the way the original issue said because when I tried it I got some Swift files missing error.

**Comment by hishak** [comment]
Yes, I did that before doing the push to Github.  It is from the workspace, not the project.  I only open the workspace in Xcode for years now.  Attached is the podfile, which you can also see above.  I had to add .txt so it can be loaded here.
[Podfile.txt](https://github.com/CocoaPods/CocoaPods/files/5252803/Podfile.txt)

**Comment by dnkoutso** [comment]
There is no Podfile here https://github.com/hishak/CopticChurchLocatorSwift5

**Comment by hishak** [comment]
I don't know why it adds a url when i drag the file here from Finder on mac.  Can you copy **Podfile** from above?

**Comment by dnkoutso** [comment]
I did actually and I saw this error:

```
error: Build input file cannot be found: '/Users/dimitris/Development/ios/CopticChurchLocatorSwift5/OneSignalNotificationServiceExtension/NotificationService.swift' (in target 'OneSignalNotificationServiceExtension' from project 'CopticFind')
```

This does not seem the same issue that you reported.

**Comment by hishak** [comment]
Hmm, everything with 'OneSignal' is in the cocoapod framework.

**Comment by hishak** [comment]
I still get same error no matter what I change or do.  Anyway somehow your build is missing the following?
![Screen Shot 2020-09-20 at 18 37 54](https://user-images.githubusercontent.com/10100514/93723890-9e5c9d00-fb70-11ea-99df-a9a82933e87d.png)

**Comment by dnkoutso** [comment]
I figured the other issue and then figured out your original issue.

You are building for arm64 which is Apple Silicon which the Pods-CopticFind does not support.

Add `arm64` to your EXCLUDED_ARCHS and it worked.

<img width="1512" alt="Screen_Shot_2020-09-20_at_3_44_21_PM" src="https://user-images.githubusercontent.com/310370/93723990-313d0d80-fb58-11ea-869b-560546d55060.png">


Going to close for now. There are other open issues about VALID_ARCHS and EXLCULDED_ARCHS.
