### ISSUE TITLE
`pod repo`, `pod env` and possibly other commands are failing during CDN/repository outage

### ISSUE THREAD

**Issue by username0x0a** [CocoaPods/CocoaPods#10082]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
aerial:~ misacek% pod repo add-cdn trunk https://cdn.cocoapods.org

Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org`
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/CocoaPods-version.yml Response: 500 
<html>
<head>
<title>Fastly error: unknown domain cdn.cocoapods.org</title>
</head>
<body>
<p>Fastly error: unknown domain: cdn.cocoapods.org. Please check that this domain has been added to a service.</p>
<p>Details: cache-hhn4034-HHN</p></body></html>
[zsh] ✘ Returned code 1
                             
aerial:~ misacek% pod repo list

[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/CocoaPods-version.yml Response: 500 
<html>
<head>
<title>Fastly error: unknown domain cdn.cocoapods.org</title>
</head>
<body>
<p>Fastly error: unknown domain: cdn.cocoapods.org. Please check that this domain has been added to a service.</p>
<p>Details: cache-fra19168-FRA</p></body></html>
[zsh] ✘ Returned code 1
```

As you can see, `pod repo add-cdn` command has failed, but instead of dropping the failing repository, `pod` adds it as a stub record.

When using `pod repo list` or some other commands after, these fail as well – instead of simply listing stub or no repository in this moment, the command rather fails due to outage as well.

Until `pod repo remove trunk` is performed, no `pod repo` command works as expected.

## What did you expect to happen?

Always having repositories list in a consistent, working state, with commands being more failure-proof.

## What happened instead?

`pod repo list` and potentially other `pod repo` commands failing. Even `pod env` from the Environment step requirement below fails.

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.0 (12A7208)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : skypicker-apple-libraries-podspecs - git - git@gitlab.skypicker.com:mobile/apple-libraries-podspecs.git @ c61d525065ff3a18cee3c732f00444e2fb92a200

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

**Comment by dnkoutso** [comment]
Please see https://github.com/CocoaPods/CocoaPods/issues/10078 which is also pinned on this repo.

Closing as duplicate.

**Comment by username0x0a** [comment]
@dnkoutso That's not an issue about CDN, but about the failure of `pod repo` commands not directly related to repository update. Users can't use `pod repo` to list & remove the failing repository, that's the basic thing that should be fixed before the next outage comes.

**Comment by dnkoutso** [comment]
@username0x0a I apologize for the fast trigger.

**Comment by dnkoutso** [comment]
You are absolutely

**Comment by username0x0a** [comment]
Thx for quick reopening. 👍
