### ISSUE TITLE
'"Project 'Pods'" - Enable Recommended Warning' for Xcode 12 GM

### ISSUE THREAD

**Issue by avm0418** [CocoaPods/CocoaPods#10083]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` for a project using Xcode 12.0

## What did you expect to happen?

A Pods project be completed without any warnings or errors

## What happened instead?

A Pods project was created with the warning: 
"Project 'Pods" - Enable Recommended Warning
This will enable the following recommended compiler warning:
* Quoted includes in Framework Header

### Stack

```
   CocoaPods : 1.10.0.rc.1
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /usr/local/Cellar/ruby/2.7.1_2/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ f59bc61c1253562c6794e0eaa37d922ffe2c4107

               xxx-inc - git - git@github.com:xxx
[CocoapodsDemo.zip](https://github.com/CocoaPods/CocoaPods/files/5264737/CocoapodsDemo.zip)
-inc/Specs.git @ 7f7d2a61235b09bc0c159008f8e90a8d18ea3f22

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/lib/ruby/gems/2.7.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '13.4'
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false, :warn_for_multiple_pod_sources => false, :warn_for_unused_master_specs_repo => false

target 'CocoapodsDemo' do
  workspace 'CocoapodsDemo.xcworkspace'
  project 'CocoapodsDemo/CocoapodsDemo.xcodeproj'

  pod 'SQLCipher', :inhibit_warnings => true
  pod 'GRDB.swift/SQLCipher', :inhibit_warnings => true  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
    target.build_configurations.each do |config|
       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
    end
  end
end
```

**Comment by avm0418** [comment]
[CocoapodsDemo.zip](https://github.com/CocoaPods/CocoaPods/files/5264747/CocoapodsDemo.zip)

**Comment by tealshift** [comment]
Not to criticize CocoaPods too harshly, but these warnings seem to appear in every new Xcode and are _very_ slow to get fixed.

**Comment by SmartHbdev** [comment]
I was exactly seaching for this ! Can we use a post_install hook to fix this ?
It's a real pain to see it back on every pod update

**Comment by amorde** [comment]
Thanks for the report! Xcodeproj will need to be updated to include the new warnings by default.

This has historically been difficult for us to keep up with. There's a [script](https://github.com/CocoaPods/Xcodeproj/blob/master/spec/fixtures/CommonBuildSettings/rebuild_from_xcode) that attempts to parse templates within Xcode to pull out the relevant information we did, but its not perfect and still requires manual intervention. If you're interesting in contributing, PRs welcome!

**Comment by paulb777** [comment]
I believe this one is a bit more tricky than just updating Xcodeproj. CocoaPods will also need to change its umbrella header generation to comply with the new default `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` value.

**Comment by avm0418** [comment]
I don't mind submitting a PR if I'm told exactly how to approach the fix. @paulb777 comment makes me a little wary that I am the best person to fix this issue though.

**Comment by amorde** [comment]
Yes I forgot about this specific warning, it will take some extra work.

We'll need to update this section of code to support angle-style imports

https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/header.rb#L57

**Comment by dnkoutso** [comment]
Related https://github.com/CocoaPods/Xcodeproj/pull/767

**Comment by dnkoutso** [comment]
Isnt this now fixed with the updated build settings in CocoaPods/Xcodeproj#767?

Should we close @amorde?
