### ISSUE TITLE
iOS Build fails in ionic 5 , Xcode 12 ,Pods 1.9.3

### ISSUE THREAD

**Issue by itsmerockingagain** [CocoaPods/CocoaPods#10094]
XCODE 12,
PODS 1.9.3
IONIC 5

 I am trying to create iOS build using below command:

ionic cordova build ios --prod --release --source-map

Source code is getting compiled successfully but gives error when it tries to create build for simulator.

Output in console:

ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/XXXXX-ceksaryiiycgttbnlrfwfgdmpmyf/Build/Products/Release-iphonesimulator/GoogleToolboxForMac'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/XXXXX-ceksaryiiycgttbnlrfwfgdmpmyf/Build/Products/Release-iphonesimulator/Protobuf'
ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/XXXXX-ceksaryiiycgttbnlrfwfgdmpmyf/Build/Products/Release-iphonesimulator/nanopb'

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseAnalytics' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseInstanceID' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseCore' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FirebaseMessaging' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Protobuf' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'GoogleToolboxForMac' from project 'Pods')
** BUILD FAILED **

The following build commands failed:
        Ld /Users/user/Library/Developer/Xcode/DerivedData/XXXXX-ceksaryiiycgttbnlrfwfgdmpmyf/Build/Intermediates.noindex/XXXXX.build/Release-iphonesimulator/XXXXX.build/Objects-normal/arm64/Binary/XXXXX normal arm64
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
cordova build ios --release exited with exit code 65.

Please help on this.

Thanks

**Comment by dnkoutso** [comment]
Sorry. This issue discusses about using ionic and cordova. Those are projects that use CocoaPods.

Please provide a sample app _without_ Cordova or Ionic for us to be able to diagnose.

I will preemptively close this issue but I will re-open if you show that this is a CocoaPods issue.

From a quick look you might need to add EXCLUDED_ARCHS instead of VALID_ARCHS and see relevant issues here.

**Comment by itsmerockingagain** [comment]
Could you please check if pod 1.9.3 has support for arm64 architecture?

**Comment by KCknows** [comment]
Can whoever you are leave me alone. Jesus, do you know what you are doing?  Do you realize the you erase my memory every time there is a code or build that fails??  Please stop letting just anybody in here!

**Comment by KCknows** [comment]
It's not a iphone. It's a android A71

Sent from my Bell Samsung device over Canada’s largest network.

________________________________

**Comment by KCknows** [comment]
Android 10

Sent from my Bell Samsung device over Canada’s largest network.

________________________________
