### ISSUE TITLE
Problem consuming a pod that makes use of a xcframework (Simulator build not working)

### ISSUE THREAD

**Issue by a4z** [CocoaPods/CocoaPods#10090]
cocoapod 1.3.9
XCode 12 and 11.5

# Consuming a pod that self consumes a xcframework

## Problem Details

I have a pod (framework) that self uses a xcframework 
This framework builds fine, but when I try to consume it from an App, I can not build for the simulator.
It can build for a target device.

So far I identified the following problem, when I build the App, the TheXCFrameworkConsumer is build via the pod and at the end, the liker command has the following seach flags for finding the TheXCFrameworkConsumer framework

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios11.0-simulator -dynamiclib -isysroot
....
-F/Users/where/ever/TheXCFrameworkConsumer/
-F/Users/where/ever/TheXCFrameworkConsumer/TheXCFrameworkConsumer.xcframework/ios-arm64 
-F/Users/where/ever/TheXCFrameworkConsumer/TheXCFrameworkConsumer.xcframework/ios-x86_64-simulator
....
-framework EcpSdkNative
....
```

The build works of course for arm64, because TheXCFrameworkConsumer is found in `/Users/where/ever/TheXCFrameworkConsumer/TheXCFrameworkConsumer.xcframework/ios-arm64`

but when I build for the simulator, it also looks into this directory first, and then I get the message

ld: warning: ignoring file /Users/where/ever/TheXCFrameworkConsumer/.xcframework/ios-arm64/TheXCFrameworkConsumer.framework/TheXCFrameworkConsumer, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64

and stop, linker errors.

### What would work

When I remove the `-F/Users/where/ever/TheXCFrameworkConsumer/TheXCFrameworkConsumer.xcframework/ios-arm64` part from the command line, then linking works

so obviously cocoapod is not continue searching the next framework search dir when a framework is found for the wrong architecture.

Do I miss some flags, or is this a cocoapod issue ?

**Comment by dnkoutso** [comment]
We cant tell if its a cocoapods issue from the report. Please upload a sample app and also provide the version of CocoaPods you are using. 1.10.0.rc.1 provides quite a few fixes.

**Comment by a4z** [comment]
cocoapod 1.3.9, XCode 12 and XCode 11.5

A sample project is not easy challenge for me since I consume just pods, but I will see what I can do.

Until I have something that makes tracing the problem more easy and reproducible for others,
Is it possible that this is all related? 
https://github.com/shogo4405/HaishinKit.swift/issues/753
https://github.com/CocoaPods/CocoaPods/issues/9525

**Comment by dnkoutso** [comment]
There is no 1.3.9 version of CocoaPods gem. Do you mean 1.9.3? Try 1.10.0.rc.1?

**Comment by a4z** [comment]
Oh, I am sorry!  you are of course right.
```
bundle exec pod --version
1.9.3
```
(now with copy and paste)

ok, I will test the rc of 1.10.0 , thanks for the tip!

**Comment by itsmerockingagain** [comment]
i am also facing same issue on Xcode 12, Pod 1.9.3 , seems like pods are not supporting arm64 architecture for iOS 14 simulators.

created issue #10094

**Comment by a4z** [comment]
I updated to `gem 'cocoapods', ">= 1.10.0.rc.1"` , re build and re installed everything with Xcode 12.0.1,
 and now I can build the application
It seems something changed in the generation of the xcconfig files, and this is a good change.
So I will close this ticket, if I encounter some other issue I will re-open or file a new one

**Comment by banane** [comment]
I'm having an issue where I can't archive- I get a "building for iOS, but linking in dylib file is for simulator" - Plaid's xcframework included in the pod, LinkKit. Simulator works fine (in our test targets). But building our main target is the issue.
