### ISSUE TITLE
RuntimeError - [Xcodeproj] Unknown object version.

### ISSUE THREAD

**Issue by LemonSpike** [CocoaPods/CocoaPods#10099]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

### Command

```
/usr/local/bin/pod update Firebase/Crashlytics Firebase/Analytics
```

### Report

* What did you do?
pod update for two pods

* What did you expect to happen?
Update pods

* What happened instead?
Got an error message and failed update.

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 8cc64318f1f173e19caa133637927fc3da01b6b7

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://cdn.cocoapods.org/'

abstract_target 'pods' do
	pod 'MBProgressHUD'
	pod 'UbiquityStoreManager'
	pod 'libPhoneNumber-iOS'
	pod 'ActionSheetPicker-3.0'
	pod 'Reachability'
	pod 'AFNetworking', '2.6.3'
	pod 'TTTAttributedLabel'
  pod 'Flurry-iOS-SDK/FlurrySDK'

	pod 'Firebase/Analytics'
	pod 'Firebase/Crashlytics'

	target 'MyHealthGuide' do
	end

	target 'TestMyHealthGuide' do
	end
end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1177:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1171:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

[!] [!] Xcodeproj doesn't know about the following attributes {"alwaysOutOfDate"=>"1"} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

**Comment by LemonSpike** [comment]
There's a Cocoapods bug in the latest Xcode 12, where you can set an option for the Run Script Build Phase to `Based on Dependency Analysis`. Reverting that to the default selected state worked for pod install although this should probably be fixed. 😄

**Comment by dnkoutso** [comment]
The crash can be fixed by `gem update xcodeproj` as the new xcodeproj gem knows about the new Xcode 12 project structure.

As fas this is concerned:

```
[!] [!] Xcodeproj doesn't know about the following attributes {"alwaysOutOfDate"=>"1"} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

Its filed here https://github.com/CocoaPods/Xcodeproj/issues/785 and its a warning.

Going to close for now as i believe this is already fixed and the other issue is filed.

**Comment by PoisonSoftwareStudio** [comment]
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'AppLovinSDK', '10.3.3'
end
target 'Unity-iPhone' do
end
```
output
```
[!] [!] Xcodeproj doesn't know about the following attributes {"alwaysOutOfDate"=>"1"} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new

[!] [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```
I've tried most things I've seen and it doesn't work.
`gem update xcodeproj ` 
output: 
```
Updating installed gems
Nothing to update
```

**Comment by jianchaoxu** [comment]
Analyzing dependencies
Traceback (most recent call last):
	20: from /Users/hehe/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	19: from /Users/hehe/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	18: from /Users/hehe/.rvm/gems/ruby-2.7.0/bin/pod:25:in `<main>'
	17: from /Users/hehe/.rvm/gems/ruby-2.7.0/bin/pod:25:in `load'
	16: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
	15: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
	14: from /Users/hehe/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	13: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
	12: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
	11: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
	10: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
	 9: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
	 8: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
	 7: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
	 6: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1184:in `inspect_targets_to_integrate'
	 5: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
	 4: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1189:in `block in inspect_targets_to_integrate'
	 3: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1189:in `each'
	 2: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1190:in `block (2 levels) in inspect_targets_to_integrate'
	 1: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:113:in `open'
/Users/hehe/.rvm/gems/ruby-2.7.0/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:228:in `initialize_from_file': [Xcodeproj] Unknown object version (56). (RuntimeError)
	11: from /Users/hehe/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	10: from /Users/hehe/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	 9: from /Users/hehe/.rvm/gems/ruby-2.7.0/bin/pod:25:in `<main>'
	 8: from /Users/hehe/.rvm/gems/ruby-2.7.0/bin/pod:25:in `load'
	 7: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
	 6: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
	 5: from /Users/hehe/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	 4: from /Users/hehe/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	 3: from /Users/hehe/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	 2: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:66:in `report_error'
	 1: from /Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface/error_report.rb:34:in `report'
/Users/hehe/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface/error_report.rb:34:in `force_encoding': can't modify frozen String: "[Xcodeproj] Unknown object version (56)." (FrozenError)
