### ISSUE TITLE
The alias file under Pods/Headers/Private generated by `pod install` cannot be recognized and will be recognized as a relative path, causing compilation errors

### ISSUE THREAD

**Issue by suwu150** [CocoaPods/CocoaPods#10102]
## What did you do?

The alias file under Pods/Headers/Private generated by podinstall cannot be recognized and will be recognized as a relative path, causing compilation errors

## What did you expect to happen?
Able to recognize alias files

## What happened instead?

headers can be embodied, not substitutes, or can be recognized as normal files

## CocoaPods Environment
```
pod --version
1.5.3
xcode 11.3
```

**Comment by dnkoutso** [comment]
This is a very old version of CocoaPods. I also do not entirely understand the issue at hand here. Please provide a sample app and clear steps to reproduce the issue or how it can be an enhancement.
