### ISSUE TITLE
How to package or process glog into a static library for import instead of using it through pod

### ISSUE THREAD

**Issue by suwu150** [CocoaPods/CocoaPods#10101]
How to package or process glog into a static library for import instead of using it through pod,When I used the pod to generate the header, after translating the code through windows, the substitute in the header was not recognized, and the file content became a relative path

**Comment by dnkoutso** [comment]
Sorry this is not a sufficient error report. Please provide sample app or ask in StackOverflow under `cocoapods` tag.
