### ISSUE TITLE
Multiple commands produce error with XCFramework 

### ISSUE THREAD

**Issue by TheCodeTalker** [CocoaPods/CocoaPods#10106]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Hello we started to use xcframework recently in our project . I am having an issue with Cocoapods where we have library `IVTNetworking` is generated with xcframework and trying to integrate with pod as dependency to other library after pod install while build we see and error like 

``` 
Multiple commands produce /Users/chitaranjans/Library/Developer/Xcode/DerivedData/VTNetworkEngine-divuxvvhxfzuclfkagrswscrlgpm/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/IVTNetworking  :
1) That command depends on command in Target 'IVTNetworking_Debug' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'IVTNetworking_Release' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
 ```
<img width="1063" alt="Screenshot 2020-09-30 at 10 17 31 PM" src="https://user-images.githubusercontent.com/3683673/94715201-c1563080-036a-11eb-84b2-211ea457ad7d.png">

## What did you expect to happen?
As you build it should copy respective xcframework like (debug and release ) xcframework

## What happened instead?
As you seen in above screenshot getting same error  

### Stack

```
   CocoaPods : 1.10.0.beta.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.3.1 (11C505)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ fb84a8148a93b4ea7997d40e7bb3107e7451ba94

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project

target 'VTNetworkEngine' do
  platform :ios, '10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VTNetworkEngine
  pod 'Alamofire', '~>4.8.2'
  pod 'AlamofireImage', '~> 3.5'
  pod 'IVTNetworking_Debug', :configuration => ['Debug'], :path => 'SupportingFramework/IVTNetworking/Debug/IVTNetworking_Debug.podspec'
  pod 'IVTNetworking_Release', :configuration => ['Release'], :path => 'SupportingFramework/IVTNetworking/Release/IVTNetworking_Release.podspec'
  pod 'TrustKit'
end

target 'VTNetworkEngine_tvOS' do
  platform :tvos, '10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Alamofire', '~>4.8.2'
  pod 'AlamofireImage', '~> 3.5'
  pod 'IVTNetworking_tvOS_Debug', :configuration => ['Debug'], :path => 'SupportingFramework/IVTNetworking_tvOS/Debug/IVTNetworking_tvOS_Debug.podspec'
#   pod 'IVTNetworking_tvOS_Release', :configuration => ['Release'], :path => 'SupportingFramework/IVTNetworking_tvOS/Release/IVTNetworking_tvOS_Release.podspec'
  pod 'TrustKit'

end
```

## Project that demonstrates the issue
If have IVTNetworking_Debug and IVTNetworking_Release different XCFramework with debug and release variant . You should get this error

**Comment by TheCodeTalker** [comment]
@dnkoutso need your help

**Comment by dnkoutso** [comment]
Can you upload a quick sample app?

**Comment by TheCodeTalker** [comment]
[Multiple commands produce error Demo.zip](https://github.com/CocoaPods/CocoaPods/files/5313594/Multiple.commands.produce.error.Demo.zip)

**Comment by dnkoutso** [comment]
@TheCodeTalker From the CocoaPods perspective you have 2 different pods that produce the same xcframework. Xcode New Build System is much stricter and does not allow that.

Xcode (and therefore the way CocoaPods) does not have a way to differentiate between a "DEBUG" and "RELEASE" target so when you say in your `Podfile`:

```ruby
target 'Demo_XcFrameworks_Integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo_XcFrameworks_Integration

  pod 'SampleLibrary_Debug', :configuration => ['Debug'], :path => 'SupportingFramework/SampleLibrary/Debug/SampleLibrary_Debug.podspec'
  pod 'SampleLibrary_Release', :configuration => ['Release'], :path => 'SupportingFramework/SampleLibrary/Release/SampleLibrary_Release.podspec'

end
```

CocoaPods will add those two dependencies in Xcode correctly and like this:
<img width="1512" alt="Screen_Shot_2020-10-02_at_10_02_01_AM" src="https://user-images.githubusercontent.com/310370/94949784-5a359a80-0496-11eb-842f-b2eef50c3619.png">

Can you do the same with pure Xcode? I do not think so. You have to choose one _or_ the other dependency to link since they produce the same XCFramework.

You can accomplish the above by perhaps an ENV variable in your `Podfile`.

```ruby
if ENV['RELEASE'] 
  pod 'MyReleasePod'
else
  pod 'MyDebugPod'
end
```

I do not think there is something we can do here to prevent this?

**Comment by dnkoutso** [comment]
All I am saying is that the fact that CocoaPods has `:configurations` support we are still hitting a wall with Xcode which does not clearly distinguish between the two.

**Comment by dnkoutso** [comment]
Unless maybe we can debounce this by checking $CONFIGURATION in our install-xcframeworks.sh scripts? cc @amorde ?

**Comment by dnkoutso** [comment]
Hmmm this seems to also be related to the OUTPUT paths for our custom script phase...perhaps we can append a CONFIGURATION folder to that and that would fix it.

Removing output file lists and input file lists makes your build works but remember I think the RELEASE one will stomp the DEBUG one because you are adding both pods.

**Comment by dnkoutso** [comment]
@TheCodeTalker want to take a stab at it?

**Comment by amorde** [comment]
Isn't configuration already included? I see `Debug-iphoneos` in the path

**Comment by dnkoutso** [comment]
from the output xcfilelist I see:

SampleLibrary_Debug-xcframeworks-output-files.xcfilelist
```
${PODS_XCFRAMEWORKS_BUILD_DIR}/SampleLibrary
```

SampleLibrary_Release-xcframeworks-output-files.xcfilelist
```
${PODS_XCFRAMEWORKS_BUILD_DIR}/SampleLibrary
```

Should we place those inside `${PODS_XCFRAMEWORKS_BUILD_DIR}/$CONFIGURATION/SampleLibrary`?

**Comment by TheCodeTalker** [comment]
> @TheCodeTalker want to take a stab at it?

I am newbee here. still let me know how can I help?

**Comment by dnkoutso** [comment]
or alternatively we can use the pod targets name to place it into that folder?

**Comment by goudsmit** [comment]
Am I correct in assuming this is also what's likely causing my issues with using the cocoapods-binary plugin?

**Comment by FaultyJuggler** [comment]
Running into this as well with other libraries and cocoapods-binary where "multiple commands"
I've noticed my version of my project that runs fine does not have all of the -copy-dsyms.sh and dsym-outputfiles.xcfilelist files even with binary on.

**Comment by zdnk** [comment]
Same here.

**Comment by Neil20170223** [comment]
Same here.

**Comment by KevinGong2013** [comment]
`pod: v1.9.3` worked on this case.

**Comment by jronceroscb** [comment]
Is there any workaround for this as of now?

**Comment by marciogranzotto** [comment]
@dnkoutso I see this is tagged with `workaround available` but I can't find any workaround

**Comment by Jichao** [comment]
workaround:
```
pod _1.9.1_ setup
pod _1.9.1_ install
```

**Comment by dnkoutso** [comment]
@amorde I investigated this again. If we place one level deeper all frameworks keyed by target name within `XCFrameworkIntermediates` we can fix this and support this project.

<img width="1040" alt="Screen_Shot_2021-07-29_at_11_00_57_PM" src="https://user-images.githubusercontent.com/310370/127558115-fa5ad26f-36d9-47fd-8c1b-b71871fa4a11.png">

I managed to successfully compile the sample project given here with some changes.

What do you think?

**Comment by dnkoutso** [comment]
This would require updating the shell scripts, output paths as well as the framework search paths.

**Comment by dnkoutso** [comment]
PR https://github.com/CocoaPods/CocoaPods/pull/10826

**Comment by Lianghuajian** [comment]
> I am seeing this same issue when trying to use vendored XCFrameworks in subspecs.
> 
> The podspec is structured like so with the parent XCFramework depending on both subspecs:
> 
> ```
> Pod::Spec.new do |s|
>     s.name             = "Parent"
>     s.version          = "1.0.0"
>     s.source           = { :git => "file:///local/repo" }
>     s.platform         = :ios
>     s.requires_arc     = true
>     
>     s.ios.vendored_frameworks = 'path/to/parent.xcframework'
>     s.preserve_paths = 'path/to/parent.xcframework'
> 
>     s.subspec 'core' do |ss|
>       ss.vendored_frameworks = 'path/to/core.xcframework'
>       ss.preserve_paths = 'path/to/core.xcframework'
>     end
> 
>     s.subspec 'dependsOnCore' do |ss|
>       ss.dependency 'Parent/core'
>       ss.vendored_frameworks = 'path/to/dependsOnCore.xcframework'
>       ss.preserve_paths = 'path/to/dependsOnCore.xcframework'
>     end
>   end
> ```
> 
> ### I get the duplicate error when my Podfile is like this
> ```
> platform :ios, '9.0'
> 
> target 'MyApp' do
>   #use_frameworks!
> 
>   # Pods for MyApp
> 
>   pod 'Parent', :path => '../path/to/local/repo'
> end
> 
> target 'ExtensionTarget' do
>   #use_frameworks!
> 
>   # Pods for ExtensionTarget
>   pod 'Parent/dependsOnCore', :path => '../path/to/local/repo'
> end
> ```
> 
> If I have both targets just use Parent it works fine, but I want to be able to have my extension target only use the subspecs.
> 
> Do I need to have separate Podspecs instead of subspecs to support this case?

Find a solution just add 
```
 install! 'cocoapods',
         disable_input_output_paths: true
```
to your Podfile

**Comment by priore** [comment]
> 
> Find a solution just add
> 
> ```
>  install! 'cocoapods',
>          disable_input_output_paths: true
> ```
> 
> to your Podfile

@Lianghuajian, unfortunately this doesn't fix during the archive process, but only during build or run process :(
