### ISSUE TITLE
Use Swift package manager CocoaPods is dead!

### ISSUE THREAD

**Issue by RealTechyGod** [CocoaPods/CocoaPods#10126]
Use Swift package manager CocoaPods is dead!

_Originally posted by @RealTechyGod in https://github.com/CocoaPods/CocoaPods/issues/10125#issuecomment-704375978_

**Comment by dnkoutso** [comment]
yay!

**Comment by dnkoutso** [comment]
But in all honesty, thanks for the issue! CocoaPods is a community driven dependency manager. We enjoy additional options for the iOS ecosystem for handling dependencies. Use whatever works best for you!
