### ISSUE TITLE
setting precompiled static library when not using "use_frameworks!" in podfile

### ISSUE THREAD

**Issue by moshekrush** [CocoaPods/CocoaPods#10124]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm trying to configure a pod that will be distributed both as a static library, dynamic framework and static framework.
My pod has a dependency in precompiled binary (which I can build as static/dynamic according to my choice)
1. In order to distribute as a dynamic framework: I created a subspec which uses the `vendored_framework` flag and points to the prebuild framework which I compiled as dynamic
2. In order to distribute as a static framework: I created a subspec which uses the `vendored_framework` flag and points to the prebuild framework which I compiled as static
3. In order to distribute as static library I added a subspec which has a `vendored_library` flag which points to the binary file which I created as static (and other flags such as `xcconfig`)
So far so good 👍 

However, I was wondering how can I define which precompiled binary will be fetched when a someone comment out `use_frameworks!` and suppose to get my pod as a static lib

## What did you expect to happen?

Get a precompiled static lib 

## What happened instead?

I got the public_headers correctly and the default subspec, In my case a precompiled dynamic framework

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G73)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 904425e38ac02c4720f81e34d2a5535dd6f5074b

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

Thanks

**Comment by dnkoutso** [comment]
did you try cocoapods 1.10?
