### ISSUE TITLE
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

### ISSUE THREAD

**Issue by ShuchiSingla** [CocoaPods/CocoaPods#10123]
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.
After the failure, "pod repo update" was executed and failed. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.
pod install output:
Analyzing dependencies
[7m――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――[0m
### Command
```
/usr/local/bin/pod install
```
### Report
* What did you do?
* What did you expect to happen?
* What happened instead?
### Stack
```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0.1 (9A1004)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2bb3f9489f13e1e8a254e6ff3dcdcf46f69101e5
```
### Plugins
```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```
### Podfile
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
target 'UnityFramework' do
  pod 'Firebase/Analytics', '6.32.2'
  pod 'Firebase/Core', '6.32.2'
  pod 'Firebase/Messaging', '6.32.2'
end
```
### Error
```
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:290:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:287:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:287:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:299:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:296:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:261:in `new_from_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:202:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:851:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:850:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:850:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:845:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
[7m――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――[0m
[31m[!] Oh no, an error occurred.[0m
[33mSearch for existing GitHub issues similar to yours:[0m
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Xcodeproj+doesn%27t+know+about+the+following+attributes+%7B%22inputFileListPaths%22%3D%3E%5B%5D%2C+%22outputFileListPaths%22%3D%3E%5B%5D%7D+for+the+%27PBXShellScriptBuildPhase%27+isa.%0AIf+this+attribute+was+generated+by+Xcode+please+file+an+issue%3A+https%3A%2F%2Fgithub.com%2FCocoaPods%2FXcodeproj%2Fissues%2Fnew&type=Issues
[33mIf none exists, create a ticket, with the template displayed above, on:[0m
https://github.com/CocoaPods/CocoaPods/issues/new
[33mBe sure to first read the contributing guide for details on how to properly submit a ticket:[0m
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
Don't forget to anonymize any private data!
Looking for related issues on cocoapods/cocoapods...
    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:
    export LANG=en_US.UTF-8
    [0m
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:72:in `get_api_results'
	from /Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:26:in `search'
	from /Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:59:in `search_exception'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
pod repo update output:
Updating spec repo `master`
[31m[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down[0m
    [33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
    Consider adding the following to ~/.profile:
    export LANG=en_US.UTF-8
    [0m

**Comment by igor-makarov** [comment]
Your `xcodeproj` version seems extremely old. You can update it with `gem update xcodeproj`.

**Comment by dnkoutso** [comment]
Yeap. for now this issue can be closed.
