### ISSUE TITLE
Lint not exiting with nonzero code

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/CocoaPods#10128]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod lib lint` on my library, which contains a compiler warning

## What did you expect to happen?

CocoaPods validation prints out that it failed due to a warning, and then returns nonzero

## What happened instead?

CocoaPods validation prints out that it failed due to a warning, and then returns zero, leaving no indication to my script calling it that it failed

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 96efe4836b724d747a0a1e4c92876f4083a852aa

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/dfrankel/.gem/ruby/2.6.0/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-keys         : 2.2.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.4.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

## Project that demonstrates the issue

The [UnrarKit project's v2.10 branch](https://github.com/abbeycode/UnrarKit/tree/v2.10) demonstrates this issue. All you need to do is clone and run `Scripts/cocoapods-validate.sh`.

Or, if you look at the logs of my latest attempted release build on Travis, you can see that the `lint` phase returned nonzero (the script is run with `set -e` so that failure would terminate the whole script) [in spite of warnings and a message reading that it did not pass validation](https://travis-ci.org/github/abbeycode/UnrarKit/jobs/733421448#L7068). I'm fairly certain this used to fail the build when it would happen, and I'd prefer it if it did. Shouldn't all Pods be free of warnings?

If this is intended behavior, then this message is misleading:

> [!] UnrarKit did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
7069

If warnings aren't intended to fail the `lint` command, then why would you need to explicitly allow them?

**Comment by igor-makarov** [comment]
It looks like you're piping the result of `pod lib lint` through another command. I believe this causes the shell to ignore the exit code of the first command.

Try using one more shell flag:  
```bash
set -o pipefail
```
