### ISSUE TITLE
Trying to run flutter App on ios simulator give me this Error

### ISSUE THREAD

**Issue by AhmedKhattab95** [CocoaPods/CocoaPods#10127]
Trying to run flutter App on ios simulator give me this Error
Pod File:
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      # Here are some configurations automatically generated by flutter

      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
         'PERMISSION_EVENTS=0',

        ## dart: PermissionGroup.reminders
        'PERMISSION_REMINDERS=0',

        ## dart: PermissionGroup.contacts
        'PERMISSION_CONTACTS=0',

        ## dart: PermissionGroup.camera
        #'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        # 'PERMISSION_MICROPHONE=0',

        ## dart: PermissionGroup.speech
         'PERMISSION_SPEECH_RECOGNIZER=0',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=0',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=0',

        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=0',

        ## dart: PermissionGroup.mediaLibrary
         'PERMISSION_MEDIA_LIBRARY=0',

        ## dart: PermissionGroup.sensors
         'PERMISSION_SENSORS=0'
      ]

    end
  end
end

pod 'Firebase/MLVisionFaceModel'

debuging

Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A background_fetch
      A connectivity
      A connectivity_for_web
      A connectivity_macos
      A devicelocale
      A esys_flutter_share
      A firebase_crashlytics
      A firebase_messaging
      A firebase_ml_vision
      A flutter_app_badger
      A flutter_background_geolocation
      A flutter_image_compress
      A flutter_local_notifications
      A flutter_plugin_android_lifecycle
      A image_picker
      A local_auth
      A location
      A location_web
      A multi_image_picker
      A package_info
      A path_provider
      A path_provider_linux
      A path_provider_macos
      A path_provider_windows
      A permission_handler
      A shared_preferences
      A shared_preferences_linux
      A shared_preferences_macos
      A shared_preferences_web
      A shared_preferences_windows
      A sqflite
      A url_launcher
      A url_launcher_linux
      A url_launcher_macos
      A url_launcher_web
      A url_launcher_windows
      - Firebase
      - Flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `background_fetch` from `.symlinks/plugins/background_fetch/ios`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `connectivity_for_web` from `.symlinks/plugins/connectivity_for_web/ios`
    -> Fetching podspec for `connectivity_macos` from `.symlinks/plugins/connectivity_macos/ios`
    -> Fetching podspec for `devicelocale` from `.symlinks/plugins/devicelocale/ios`
    -> Fetching podspec for `esys_flutter_share` from `.symlinks/plugins/esys_flutter_share/ios`
    -> Fetching podspec for `firebase_crashlytics` from `.symlinks/plugins/firebase_crashlytics/ios`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

    ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    ### Command

    ```
    /usr/local/bin/pod install --verbose
    ```

    ### Report

    * What did you do?

    * What did you expect to happen?

    * What happened instead?

    ### Stack

    ```
       CocoaPods : 1.10.0.rc.1
            Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
        RubyGems : 3.0.3
            Host : Mac OS X 10.15.4 (19E287)
           Xcode : 12.0.1 (12A7300)
             Git : git version 2.20.1
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
    Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 01b47946a91b1f108c441259479b5e4082e99daa

                   trunk - CDN - https://cdn.cocoapods.org/
    ```

    ### Plugins

    ```
    cocoapods-deintegrate : 1.0.4
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.0
    cocoapods-stats       : 1.1.0
    cocoapods-trunk       : 1.4.1
    cocoapods-try         : 1.1.0
    ```

    ### Podfile

    ```ruby
    # Uncomment this line to define a global platform for your project
    platform :ios, '9.0'

    # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
    ENV['COCOAPODS_DISABLE_STATS'] = 'true'

    project 'Runner', {
      'Debug' => :debug,
      'Profile' => :release,
      'Release' => :release,
    }

    def parse_KV_file(file, separator='=')
      file_abs_path = File.expand_path(file)
      if !File.exists? file_abs_path
        return [];
      end
      generated_key_values = {}
      skip_line_start_symbols = ["#", "/"]
      File.foreach(file_abs_path) do |line|
        next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
        plugin = line.split(pattern=separator)
        if plugin.length == 2
          podname = plugin[0].strip()
          path = plugin[1].strip()
          podpath = File.expand_path("#{path}", file_abs_path)
          generated_key_values[podname] = podpath
        else
          puts "Invalid plugin specification: #{line}"
        end
      end
      generated_key_values
    end

    target 'Runner' do
      use_modular_headers!
      use_frameworks!

      # Flutter Pod

      copied_flutter_dir = File.join(__dir__, 'Flutter')
      copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
      copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
      unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
        # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
        # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
        # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

        generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
        unless File.exist?(generated_xcode_build_settings_path)
          raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
        end
        generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
        cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

        unless File.exist?(copied_framework_path)
          FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
        end
        unless File.exist?(copied_podspec_path)
          FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
        end
      end

      # Keep pod path relative so it can be checked into Podfile.lock.
      pod 'Flutter', :path => 'Flutter'

      # Plugin Pods

      # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
      # referring to absolute paths on developers' machines.
      system('rm -rf .symlinks')
      system('mkdir -p .symlinks/plugins')
      plugin_pods = parse_KV_file('../.flutter-plugins')
      plugin_pods.each do |name, path|
        symlink = File.join('.symlinks', 'plugins', name)
        File.symlink(path, symlink)
        pod name, :path => File.join(symlink, 'ios')
      end
    end

    # Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
    install! 'cocoapods', :disable_input_output_paths => true

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
          config.build_settings['ENABLE_BITCODE'] = 'NO'
          # Here are some configurations automatically generated by flutter

          # You can remove unused permissions here
          # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/develop/permission_handler/ios/Classes/PermissionHandlerEnums.h
          # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
            '$(inherited)',

            ## dart: PermissionGroup.calendar
             'PERMISSION_EVENTS=0',

            ## dart: PermissionGroup.reminders
            'PERMISSION_REMINDERS=0',

            ## dart: PermissionGroup.contacts
            'PERMISSION_CONTACTS=0',

            ## dart: PermissionGroup.camera
            #'PERMISSION_CAMERA=0',

            ## dart: PermissionGroup.microphone
            # 'PERMISSION_MICROPHONE=0',

            ## dart: PermissionGroup.speech
             'PERMISSION_SPEECH_RECOGNIZER=0',

            ## dart: PermissionGroup.photos
            # 'PERMISSION_PHOTOS=0',

            ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
            # 'PERMISSION_LOCATION=0',

            ## dart: PermissionGroup.notification
            # 'PERMISSION_NOTIFICATIONS=0',

            ## dart: PermissionGroup.mediaLibrary
             'PERMISSION_MEDIA_LIBRARY=0',

            ## dart: PermissionGroup.sensors
             'PERMISSION_SENSORS=0'
          ]

        end
      end
    end

    pod 'Firebase/MLVisionFaceModel'
    ```

    ### Error

    ```
    ArgumentError - Malformed version number string p.0
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/version.rb:47:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/vendor/version.rb:199:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/vendor/version.rb:199:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/vendor/version.rb:192:in `create'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/platform.rb:54:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/specification.rb:517:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/specification.rb:517:in `block in available_platforms'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/specification.rb:517:in `map'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/specification.rb:517:in `available_platforms'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0.rc.1/lib/cocoapods-core/specification.rb:402:in `dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/validator.rb:44:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/external_sources/abstract_external_source.rb:201:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/external_sources/abstract_external_source.rb:201:in `validator_for_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/external_sources/abstract_external_source.rb:186:in `validate_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/external_sources/abstract_external_source.rb:178:in `store_podspec'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:989:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:968:in `block (2 levels) in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:967:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:967:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:966:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/installer.rb:160:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.rc.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'
    ```

    ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

    [!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+p.0&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
     - Error running pod install Error launching application on iPhone 11.
       https://github.com/CocoaPods/CocoaPods/issues/9981 [closed] [1 comment]
       16 Aug 2020

     - error when running pod install
       https://github.com/CocoaPods/CocoaPods/issues/9195 [closed] [4 comments]
       04 Oct 2019

     - 0.38.1: Linker errors due to incompatible semver versions
       https://github.com/CocoaPods/CocoaPods/issues/3887 [closed] [10 comments]
       25 Jul 2015

Error output from CocoaPods:
↳
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/ashraf/Desktop/Work/App.Connect/smile_me_in in PATH, mode 040757

Error running pod install
Error launching application on iPhone 11 Pro Max.

**Comment by dnkoutso** [comment]
This looks like an issue parsing a version number. Please upload a sample app _without_ Flutter that demonstrates the issue.

**Comment by AhmedKhattab95** [comment]
it's happening with this app couldn't create solution to demonstrate issue 
and here's what appears when run pod install sometimes


[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] FirebaseMLVisionFaceModel has been deprecated in favor of MLKitFaceDetection

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

**Comment by dnkoutso** [comment]
I continue to believe this is related to Flutter integration that uses CocoaPods.

We get many issues around Flutter and we ask people to create and show sample apps that _do not_ include Flutter so we can diagnose easier.

Without a non-Flutter sample app that shows the issue we cannot help as it takes a lot of time and knowledge of Flutter.

**Comment by AhmedKhattab95** [comment]
It's a private project and can't share it if you can join with me with a VPN could share it with you

**Comment by AhmedKhattab95** [comment]
I found that i need to update all firebase plugins with latest and also use firebase_core with latest version
also added 3 files with ios from this comment on another issue [https://github.com/flutter/flutter/issues/17899](17899)
https://github.com/flutter/flutter/issues/17899#issuecomment-392134517
can follow these links:
https://firebase.flutter.dev/docs/migration/
like https://stackoverflow.com/a/63492262/6309432
https://stackoverflow.com/questions/56055142/cocoapods-could-not-find-compatible-versions-for-pod-firebase-coreonly

and here's new pubspec.yaml file
```
version: 3.8.8+107

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  devicelocale: ^0.2.1
  shared_preferences: ^0.5.6+1
  http: ^0.12.2
  #camera: ^0.4.0+1
  path_provider: ^1.6.0
  image_picker: 0.6.7
  uuid: ^2.0.0
  flutter_calendar_carousel: ^1.4.11
  url_launcher: ^5.4.5
  local_auth: ^0.6.1
  #onesignal: ^1.1.0
  connectivity: ^0.4.8+6
  flutter_picker: ^1.1.0
  location: ^3.0.2
  flutter_local_notifications: ^0.8.4
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  dotted_border: ^1.0.2
  intl: ^0.16.0
  cupertino_icons: ^0.1.2
  package_info: ^0.4.3
  flutter_image_compress: ^0.6.3
  exif: ^1.0.1
  firebase_ml_vision: ^0.9.7
  collection: ^1.14.11
  responsive_grid: ^1.2.1+1
  flutter_background_geolocation: ^1.9.0
  flutter_fluid_slider: ^1.0.2
  esys_flutter_share: ^1.0.2
  photo_view: ^0.6.0
  mask_text_input_formatter: ^1.0.5
  auto_size_text: ^2.1.0
  crypto: ^2.1.3
  firebase_crashlytics: ^0.2.1+1
  cached_network_image: ^2.2.0+1
  flutter_linkify: ^3.1.3
  qr_flutter: ^3.1.0
  material_design_icons_flutter: ^4.0.5345
  permission_handler: ^5.0.0+hotfix.8
  flutter_app_badger: ^1.1.2
  awesome_dialog: ^1.1.3
  flutter_cache_manager: ^1.4.2
  flutter_slidable: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/langs/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
```

**Comment by dnkoutso** [comment]
So is this fixed?

**Comment by AhmedKhattab95** [comment]
yes
