### ISSUE TITLE
Static XCFramework include paths

### ISSUE THREAD

**Issue by iKleMiX** [CocoaPods/CocoaPods#10136]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I've added simple xcframework with static libs inside.

## What did you expect to happen?

I expect it to work like the xcframework would be dropped in Xcode:
```
#import <TestLib/TestLib.h>
```

## What happened instead?

Cocoapods copies headers to a different location and sets `HEADER_SEARCH_PATHS` to `"${PODS_XCFRAMEWORKS_BUILD_DIR}/TestLib/Headers"`. Which forces you to use `#import <TestLib.h>`, which breaks all includes in the umbrella header, and some header name collision might happen as well.

### Stack

```
   CocoaPods : 1.10.0.rc.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.26.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 1.0.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestXCPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  platform :osx, '10.15'

  # Pods for TestXCPod
  pod 'TestLib', :path => 'build'
end
```

## Project that demonstrates the issue

Ping me if you need this test project, but it is really simple.

**Comment by amorde** [comment]
Thanks for the report. We do have an example project that tests this particular setup but it might not be catching this issue.

cc @Westacular I know you were looking at static libs within xcframeworks recently in https://github.com/CocoaPods/CocoaPods/pull/10072, have you seen this issue?

@iKleMiX do you have a proposed solution to this? Is there something we could be doing differently to resolve this?

**Comment by amorde** [comment]
Actually this _might_ be already fixed based on this convo https://github.com/CocoaPods/CocoaPods/pull/10072/files#r492205090 we weren't setting `HEADER_SEARCH_PATHS` correctly

**Comment by iKleMiX** [comment]
Test repository - https://github.com/iKleMiX/TestXCPod
Open workspace
Build - BuildLib
Run `pod install`
Build TestXCPod, it might work somehow by Xcode magic, because it finds header locally, but won't work for externally built xcframeworks.

In DerivedData we can see following structure: `XCFrameworkIntermediates/TestLib/Headers/TestLib_macOS.h`
And pods are adding header search path to `XCFrameworkIntermediates/TestLib/Headers/` 
@amorde I propose to add another directory with XCFramework name in Headers, so the path to the headers looks like - `XCFrameworkIntermediates/TestLib/Headers/TestLib/TestLib_macOS.h` then it should work fine.

Final note: this is not fixed in https://github.com/CocoaPods/CocoaPods/pull/10072/files#r492205090 I checked out code changes and all imports were `#import "Coconut.h"` instead of `#import <CoconutLib/Coconut.h>`

**Comment by dnkoutso** [comment]
thanks for great report, will take a look for 1.11.0.

**Comment by dnkoutso** [comment]
@iKleMiX yes the provided sample builds successfully for me. 

Do you have a sample with a remote pod that demonstrates the issue?

**Comment by dnkoutso** [comment]
ping @iKleMiX

**Comment by iKleMiX** [comment]
Will try to update repro with a remote pod in next few days.

**Comment by iKleMiX** [comment]
I updated this repository - https://github.com/iKleMiX/TestXCPod
Used latest CocoaPods 1.11.0.beta.2

Here's the structure of the XCFramework:
<img width="269" alt="Screen Shot 2021-08-18 at 11 59 16 AM" src="https://user-images.githubusercontent.com/25431687/129869773-fea554d4-cc61-43f0-b6d1-1868b2000584.png">

It is called `TestLib` and has a header named `TestLib_macOS.h`. As with any framework, I expect it to be included as `#import <TestLib/TestLib_macOS.h>` but the header is not found.

In the generated xcconfig there's search path defined as:
```
HEADER_SEARCH_PATHS = $(inherited) "${PODS_XCFRAMEWORKS_BUILD_DIR}/SomePrivatePod/Headers"
```

Intermediate directory structure looks like this:
<img width="302" alt="Screen Shot 2021-08-18 at 12 03 05 PM" src="https://user-images.githubusercontent.com/25431687/129870406-362ff5c8-e8c0-4cec-8f48-c680807f9b6b.png">

So importing header like this: `#import "TestLib_macOS.h"` works, but is totally wrong, since umbrella headers won't work, and imagine 2 frameworks with the same header names.

**Comment by dnkoutso** [comment]
Thanks for the sample! will investigate for 1.11.0

**Comment by dnkoutso** [comment]
It seems we do not have a good way to support modular headers fro static frameworks, I will need to see what Xcode does generally by default.

**Comment by dnkoutso** [comment]
@iKleMiX I was unable to also `import <TestLib/TestLib_macOS.h>` with a non-cocoapods vanilla Xcode app by integrating the same xcframework you supplied in your repo.

This seems it cannot be supported because there is no module created. I was able to `import "TestLib_macOS.h"`.

CocoaPods in this case seems to match the vanilla Xcode functionality.

**Comment by dnkoutso** [comment]
It seems Xcode output the header inside `include` folder.

Probably automatically scanned by Xcode as part of finding `""` headers.

<img width="1032" alt="Screen Shot 2021-08-18 at 1 16 26 PM" src="https://user-images.githubusercontent.com/310370/129881394-b9f42b61-01be-4107-bd86-809ce2dc3e4b.png">

**Comment by iKleMiX** [comment]
You are right! I didn't test properly same xcframework with a built-in method.

When creating framework with `xcodebuild -create-xcframework` you must not pass `-headers headers/LibName`, omit last directory and it will be added to the framework structure itself, thus resulting in a working xcframework through Xcode drag'n'drop and CocoaPods 👍

**Comment by dnkoutso** [comment]
awesome!
