### ISSUE TITLE
Documentation for Pod::Project broken

### ISSUE THREAD

**Issue by rpitting** [CocoaPods/CocoaPods#10143]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

The documentation for Pod::Project (https://rubydoc.info/gems/cocoapods/Pod/Project) seems to be down.

I tried to access it via https://rubydoc.info/gems/cocoapods/Pod/Installer.

## What did you expect to happen?

The documentation for Pod::Project is shown.

## What happened instead?

`Error 503 Service Unavailable`

## CocoaPods Environment

N/A

## Project that demonstrates the issue

N/A

**Comment by igor-makarov** [comment]
It appears that this is an issue in https://rubydoc.info that happens in all other pages on the site, including ones not related to CocoaPods.  

Please contact the admins of RubyDoc to report the issue to them.
