### ISSUE TITLE
IPA size is bigger when using development pod

### ISSUE THREAD

**Issue by annomusa** [CocoaPods/CocoaPods#10142]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Comparing usual modular project using `Xcode Framework` and `Development Pod`

Xcode Framework
1. Create Sample project
2. Create an Xcode framework module named `ModuleSample`
3. Add 1600 swift files into `ModuleSample`
4. Generate IPA -> Size 12.8 MB

Development Pod
1. Create Sample project
2. Create Podspec for `ModuleSample` with source_files include 1600 swift files
3. Generate IPA -> Size 13.5 MB

## What did you expect to happen?
Generated IPA using `Development Pod` have the same size with `Xcode project`

## What happened instead?
IPA using `Development Pod` have bigger size compare to `Xcode framework`
`Development Pod` -> 13.5 MB
`Xcode framework` -> 12.8 MB

`ModuleSample` module  using Xcode framework
![image](https://user-images.githubusercontent.com/6714815/95707408-aac1aa80-0c83-11eb-9c0c-968d5814f55d.png)

`ModuleSample` module using Development pod
![image](https://user-images.githubusercontent.com/6714815/95707455-c88f0f80-0c83-11eb-9a04-0691fada9e1f.png)

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.3
        Host : macOS 11.0 (20A5384c)
       Xcode : 12.0 (12A7209)
         Git : git version 2.20.1
Ruby lib dir : /Users/aunorafiq/.rvm/rubies/ruby-2.6.5/lib
Repositories : artsy - git - https://github.com/artsy/Specs.git @ d70f6d5de16e32f4d001a6b9753ba65d250aa866

               bukalapak - git - https://github.com/bukalapak/BukalapakiOSSpecs.git @ 7f4b11a57d9f628c983f78d089d1f2e19b54da93

               bukalapak-bukalapakiosspecs - git - git@git.gitlab.cloud.bukalapak.io:bukalapak/bukalapakiosspecs.git @ 799cfbb61d0c778314db19c0a078bcee101b3599

               master - git - https://github.com/CocoaPods/Specs.git @ 34ab5308af863d3ee8ebf50110afdf1962213d65

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/aunorafiq/.rvm/gems/ruby-2.6.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '10.0'
use_frameworks!

workspace 'PodSample'

target 'PodSample' do
  project 'PodSample.xcodeproj'

  pod 'AFNetworking', '3.2.1'
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'MBProgressHUD'
  pod 'Masonry'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'CocoaLumberjack'
  pod 'Realm'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'ModuleSample', :path => '../ModuleSample'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        if defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
          config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = "YES"
        end

        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      elsif config.name == 'Release'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
      end

      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
```

## Project that demonstrates the issue
https://github.com/annomusa/Pod-or-Project

**Comment by annomusa** [comment]
I've tried to adjust the build settings for development pod same as with the xcode framework, but it seems doesn't work
https://www.diffchecker.com/h8B1B09i

**Comment by ihsanhusnul** [comment]
I've tried been investigating by comparing the IPA use this [tools](https://github.com/bl-core-vitals/appdiff).
now the increasing size `narrowed` to Alamofire, Kingfisher, and SnapKit.
but I still don't know yet this can be happens.
https://docs.google.com/spreadsheets/d/1S_1DzUG3h_BKjv2CioCkzSi1KaWImBYB7FQOtF8YqWQ/edit?usp=sharing
