### ISSUE TITLE
Executing POD Update cannot find the private library I just committed

### ISSUE THREAD

**Issue by melo30** [CocoaPods/CocoaPods#10169]
After a successful pod Trunk prompt, why can't I search for the latest version and wait a while for it to appear

**Comment by melo30** [comment]
cocoapods version is 1.9.1 
system version is 10.15.6

**Comment by melo30** [comment]
It takes about 10-30 minutes for the new version to appear

**Comment by dnkoutso** [comment]
That is because of CDN which needs sometime to propagate the changes through. If you want to avoid this issue please switch to the `git` based version of the master specs repo.
