### ISSUE TITLE
Library not loaded with static linkage

### ISSUE THREAD

**Issue by ianbytchek** [CocoaPods/CocoaPods#10168]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I use a few static Swift frameworks (not libraries), both via Carthage and inside the project. So I decided to do the same with CocoaPods and installed [mrackwitz/Version](https://github.com/mrackwitz/Version) with `use_frameworks! :linkage => :static`.

For some reason it doesn't appear to be statically linked and the app fails with `dyld: Library not loaded: @rpath/Version.framework/Versions/A/Version`.

I can also see that link phase does `-framework Version` just like it does for other static frameworks. I've also seen there might be some issue with that in 1.10.0, but 1.9.3 suffers from the same problem. Once I switch to `:linkage => :dynamic` everything runs smoothly.

Am I missing something obvious and `use_frameworks! :linkage => :static` produces something different, not static frameworks, or is is supposed to work as expected? Can this be caused by other dependencies?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.1 (12A7403)
         Git : git version 2.28.0
Ruby lib dir : /Users/ianbytchek/.rbenv/versions/2.7.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 1bb527b6c7bf87e74d36446a3a3fa022172bd527

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/ianbytchek/.rbenv/versions/2.7.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
project '../App.xcodeproj'
workspace '../App.xcworkspace'
platform :osx, '10.12'

target 'App' do
  use_frameworks! :linkage => :static
  pod 'AppCenter/Analytics'
  pod 'AppCenter/Crashes'
  pod 'Version'
end
```

**Comment by dnkoutso** [comment]
Need a sample app here that we can reproduce the issue with. Please provide step-by-step instructions on how to reproduce the issue.

**Comment by ianbytchek** [comment]
@dnkoutso Apologies for the laggy reply. I tried to separate this into a stand alone project and everything worked as expected. The original project returned back to normal as well. Can't say if this was a random glitch or something somewhere was updated, gonna keep an eye on this. Thanks for looking into this! 🙏
