### ISSUE TITLE
Code Coverage for the Unit Test Targets are incorrect with a configuration different than debug

### ISSUE THREAD

**Issue by sachinvas** [CocoaPods/CocoaPods#10166]
Before you start, are you using the latest CocoaPods release?
Yes

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
1. We have a Staging configuration which is basically a duplicate of Debug Configuration (setup exists for around 3 years)
2. We have many inhouse repositories as dependency resolved using the dynamic frameworks
3. Until Xcode 11.3.1, we were able to see the coverage of all these dynamic frameworks
4. Updated to Xcode 11.7 and now Xcode 12.1.

## What did you expect to happen?
1. Code Coverage should work for all these dynamic frameworks.
2. Retain the configuration.
3. Upon changing the configuration from debug to staging it works fine.

## What happened instead?
1. On Xcode 11.7 through Xcode 12.1 we are getting only a few files covered under the dynamic frameworks.
2. Upon changing the configuration from Staging to Debug it works fine.

## CocoaPods Environment
1. CocoaPods version 1.10

## Project that demonstrates the issue
1. Unable to share the project due to privacy policies.

**Comment by dnkoutso** [comment]
I'd love to see a sample app here demonstrating the issue.

**Comment by sachinvas** [comment]
[WrongCodeCoverage.zip](https://github.com/CocoaPods/CocoaPods/files/5433043/WrongCodeCoverage.zip)
@dnkoutso Thank you for your response. PFA for the sample project which depicts the problem.
Current Configuration is set to Staging
Updating the settings to Debug will resolve the issue.

**Comment by sachinvas** [comment]
@dnkoutso I have provided the sample output, please let me know.
