### ISSUE TITLE
Pods-<target>-resources.sh contains incorrect assets path

### ISSUE THREAD

**Issue by fedetrim** [CocoaPods/CocoaPods#10170]
🌈
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Tried to build a project with a dev pod containing `.xcassets` file, using statically-linked frameworks.

## What did you expect to happen?

Expected the project to build successfully.

## What happened instead?

Got an error during the `[CP] Copy Pods Resources` build phase:
```
error: Resource "/Users/federicotrimboli/Library/Developer/Xcode/DerivedData/AssetsBug-daxuxarxrtwbxadonvosjaawkieq/Build/Products/Debug-iphonesimulator/DevPod/DevPod.framework/Images.car" not found. Run 'pod install' to update the copy resources script.
```

The original `.xcassets` file included in the dev pod is indeed called `Images.xcassets`, but when navigating to the path shown in the error, I can see that the compiled `.car` file is actually called `Assets.car`. Looks like Xcode assigns `Assets.car` to every compiled `xcassets` regardless of the original name. However, the `Pods-<target>-resources.sh` script tries to access the file using the original name `Images` instead of `Assets`.

Additionally, if there were more than one `xcassets`, all of them would be merged+compiled into a single `Assets.car`, so the naming makes sense. In this case, the script should contain a single line but instead it's generating one line per `xcassets` file.

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.0.1 (12A7300)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/federicotrimboli/.rvm/rubies/ruby-2.6.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ af326a1bd1b3bbe0188e494fc00d6355e455e836

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/federicotrimboli/.rvm/gems/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
unless defined?(Bundler)
  puts "\nPlease re-run using:".red
  puts "  bundle exec pod #{ARGV.join(' ')}\n"
  exit(1)
end

install! 'cocoapods'
platform :ios, '12.0'
use_frameworks! :linkage => :static

target 'AssetsBug' do
  pod 'DevPod', :path => 'DevPod'
end
```

## Project that demonstrates the issue

I'm attaching a sample Xcode project that demonstrates the issue: [AssetsBug.zip](https://github.com/CocoaPods/CocoaPods/files/5438117/AssetsBug.zip)

**Comment by benzsuankularb** [comment]
I also run into this issue.

**Comment by CoderWQYao** [comment]
I also run into this issue.

**Comment by feixue299** [comment]
I also run into this issue.

**Comment by fedetrim** [comment]
I believe this issue might have been introduced here: #9441

**Comment by feixue299** [comment]
In my case, 
```
use_frameworks :linkage => :static
```
 was added to the podFile happen error, Then I added 
```
spec. Static_framework = true
```
 and changed it to 
```
use_frameworks
```
 in podFile，it works!
