### ISSUE TITLE
It keeps asking me to add 'if #available' version check` while it's already there

### ISSUE THREAD

**Issue by kennic** [CocoaPods/CocoaPods#10177]
Why does it keep asking me to add `'if #available' version check` while it's already there?

<img width="1355" alt="Screen_Shot_2020-10-29_at_11_36_03_AM" src="https://user-images.githubusercontent.com/5372071/97526215-3e60de00-19db-11eb-9514-67da9df90c0f.png">

<img width="869" alt="Screen_Shot_2020-10-29_at_11_36_49_AM" src="https://user-images.githubusercontent.com/5372071/97526231-4882dc80-19db-11eb-8885-bc3a2aa80d7c.png">

**Comment by igor-makarov** [comment]
@kennic it looks like your availability directives don't include tvOS, which is the one the compiler is complaining about.

**Comment by kennic** [comment]
> @kennic it looks like your availability directives don't include tvOS, which is the one the compiler is complaining about.

Ah you are right. I move it to `#if os(iOS)` block and now it works. Thank you!
