### ISSUE TITLE
Install latest pre-release pod version available

### ISSUE THREAD

**Issue by sadanro100** [CocoaPods/CocoaPods#10176]
Cocoapods: 1.9.3
Xcode: 12.0

I've been trying to automate our release for both development (TestFlight) and production (App Store) environments using Fastlane.

That involves making sure our app is built using the latest API client which is an OpenAPI-codegen-generated pod, according to the environment being built.

In order to distinguish the environment during the pod install, I'm using an env var as such:

`env PODFILE_TYPE=production pod install`

The issue is, I don't know how to make CocoaPods install the latest pre-release version when building development. (I don't want to specify a version, just get the latest)

```
case ENV['PODFILE_TYPE']

when 'production'
  # This installs the latest production version available
  pod 'leadmanagerclient' 
when 'development'
  # How do I get it to install the latest development version available?
  pod 'leadmanagerclient' 

else
  puts 'Specify PODFILE_TYPE'
  exit 1
end
```

**Comment by igor-makarov** [comment]
It seems like you're intending to use different versions of the same pod, check out [Podfile](https://guides.cocoapods.org/syntax/podfile.html#pod) - especially the part titled 'Using the files from a local path'.

**Comment by sadanro100** [comment]
@igor-makarov 

I am able to install pre-release versions by specifying the exact version like:

pod 'leadmanagerclient', '1.0.108-beta.13'

The thing is, I don't want to specify a version, I need to get the latest beta version. Any ideas?

**Comment by sadanro100** [comment]
@igor-makarov 

I am able to install pre-release versions by specifying the exact version like:

`pod 'leadmanagerclient', '1.0.108-beta.13'`

The thing is, I don't want to specify a version, I need to get the latest beta version. Any ideas?

**Comment by sadanro100** [comment]
I see what you mean now, but what I am trying to avoid is to write code to check what the latest beta version available is.

If I have to write that code I might as well just pass the latest beta version available as a parameter, but since I always need the latest version, if CocoaPods could install the latest beta just like it installs the latest production version, that would be cleaner and easier to implement.

**Comment by igor-makarov** [comment]
From what I know, that isn't supported by design.

**Comment by berjayasompo** [comment]
> Cocoapods: 1.9.3
> 
> Xcode: 12.0
> 
> 
> 
> I've been trying to automate our release for both development (TestFlight) and production (App Store) environments using Fastlane.
> 
> 
> 
> That involves making sure our app is built using the latest API client which is an OpenAPI-codegen-generated pod, according to the environment being built.
> 
> 
> 
> In order to distinguish the environment during the pod install, I'm using an env var as such:
> 
> 
> 
> `env PODFILE_TYPE=production pod install`
> 
> 
> 
> The issue is, I don't know how to make CocoaPods install the latest pre-release version when building development. (I don't want to specify a version, just get the latest)
> 
> 
> 
> ```
> 
> case ENV['PODFILE_TYPE']
> 
> 
> 
> when 'production'
> 
>   # This installs the latest production version available
> 
>   pod 'leadmanagerclient' 
> 
> when 'development'
> 
>   # How do I get it to install the latest development version available?
> 
>   pod 'leadmanagerclient' 
> 
> 
> 
> else
> 
>   puts 'Specify PODFILE_TYPE'
> 
>   exit 1
> 
> end
> 
> ```
> 
> 
> 
>

**Comment by dnkoutso** [comment]
Does something like `~> 1.0.108-beta` work?

**Comment by hsiraaH** [comment]
@dnkoutso Yes your suggestion works, in fact other version comparison symbols like >, >=, and their < counterparts work fine. The only thing seems to be that we need to add the ‘-beta’ flag to our dependancy version.
