### ISSUE TITLE
Can't set Swift version to 5.3 for all pods with CocoaPods 1.8.4

### ISSUE THREAD

**Issue by HoustonDuane** [CocoaPods/CocoaPods#10172]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm using Xcode 12.0.1. 
I have set the swift version to 5.3 in `pre-install` and `post-install` hooks like this:
```
pre_install do |installer|
  installer.pod_targets.each do |pod_target|
    pod_target_xcconfig['SWIFT_VERSION'] = '5.3'
  end
end

post_install do |installer|
  installer.target_installation_results.pod_target_installation_results.each do |name, result|
    installer.generated_projects.each do |project|
      project.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.3'
      end
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '5.3'
        end
      end
    end
  end
end
```
Then I run `pod install`.

## What did you expect to happen?

I expect the xcode project/workspace tell me somewhere that we are actually using Swift 5.3.

## What happened instead?

Both the .xcodeproj file and the generated .xcworkspace file has shown this:
![image](https://user-images.githubusercontent.com/39131270/96954656-69a08480-1526-11eb-9799-94adc1e1e199.png)
The above applies for every target in my project. I don't see a `Swift 5.3` option in the list.

If I run the app onto my iPhone, in the build log I can see `export SWIFT_VERSION\=5.0` in one of the build phase log when I enabled the `Show environment variables in build log` option.

I'm not sure if this is a CocoaPods issue or an Xcode one, someone please enlighten me. Much thanks!

**Comment by dnkoutso** [comment]
Please provide a sample app that demonstrates the issue including Xcode version and CocoaPods version.

Its possible the Xcode UI does not say "5.3" but it does have "5.3" inside the .xcodeproj.
