### ISSUE TITLE
Not installing correctly for App Extension target

### ISSUE THREAD

**Issue by imReker** [CocoaPods/CocoaPods#10188]
* [*] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
1. Create a default xcode project.
2. Create an App Clip target, a Photo Extension target and a Widget Extension target.
3. `pod init`.
4. Add `hello` pod to every target.
5. `pod install`.

## What did you expect to happen?

CocoaPods create `[CP] Embed Pods Frameworks` Build Phase to every target.

## What happened instead?

CocoaPods only creates `[CP] Embed Pods Frameworks` Build Phase to App and AppClip target.
And this makes Extension targets failed to run correctly.

If I manully create a `[CP] Embed Pods Frameworks` in Extension target(copy the content from App target), everything works.

![issue](https://user-images.githubusercontent.com/4949937/98083379-36121280-1eb5-11eb-8596-3341b2f7fdbd.png)

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.1 (12A7403)
         Git : git version 2.28.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppClip' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppClip
  
  pod 'hello'
end

target 'photoExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for photoExtension
  pod 'hello'
end

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'hello'
end

target 'widgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for widgetExtension
  pod 'hello'
end
```

**Comment by igor-makarov** [comment]
@imReker I am using app extensions with frameworks, and frameworks aren't supposed to be embedded into the extensions, only into the containing app.

Embedding them into both would cause unnecessary duplication and increase bundle size.

From the looks of it, your CocoaPods setup looks fine.  
Are you overriding the `LD_RUNPATH_SEARCH_PATHS` in your extension targets? That seems like a good place to start.

**Comment by imReker** [comment]
@igor-makarov Oh, my fault, sorry for wasting your time, thanks.

**Comment by igor-makarov** [comment]
@imReker it's no trouble!
