### ISSUE TITLE
Custom Framework : dyld: Symbol not found: _$s11CryptoSwift7PaddingO5pkcs7yA2CmFWC

### ISSUE THREAD

**Issue by deepesh259nitk** [CocoaPods/CocoaPods#10185]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I am using a custom framework created using 3 different cocoapods. I am using this custom framework in a client app by dropping the xc framework created. As soon as the client app launches it crashes with below crash logs. I have seen this issue reported many other places on apple and stackoverflow but i could not find a proper answer which worked for me. Now i have uploaded both the client app and the framework repo to github so that anyone trying to help me can actually see the set up and code. Please can any one suggest a proper solution to this issue.

pod version : 1.9.3

Framework : https://github.com/deepesh259nitk/PaymentsKit

Client App : https://github.com/deepesh259nitk/PaymentClient

## What did you expect to happen?

No crash when the client app launches. 

## What happened instead?

Crash seen when app launches

see crash logs 
`dyld: Symbol not found: $s11CryptoSwift7PaddingO5pkcs7yA2CmFWC Referenced from: /Users/deepesh.vasthimal/Library/Developer/Xcode/DerivedData/PaymentClient-bnsircrdeaciebedmqaliyxezdqe/Build/Products/Debug-iphonesimulator/PaymentsKit.framework/PaymentsKit Expected in: /Users/deepesh.vasthimal/Library/Developer/CoreSimulator/Devices/A0876375-98D5-4215-A139-68F29E787388/data/Containers/Bundle/Application/D954732B-EDDC-478E-85C4-C5C9B14FDDEE/PaymentClient.app/Frameworks/CryptoSwift.framework/CryptoSwift in /Users/deepesh.vasthimal/Library/Developer/Xcode/DerivedData/PaymentClient-bnsircrdeaciebedmqaliyxezdqe/Build/Products/Debug-iphonesimulator/PaymentsKit.framework/PaymentsKit dyld: launch, loading dependent libraries DYLDSHAREDCACHEDIR=/Users/deepesh.vasthimal/Library/Developer/CoreSimulator/Caches/dyld/19H2/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A372 DYLDROOTPATH=/Users/deepesh.vasthimal/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLDLIBRARYPATH=/Users/deepesh.vasthimal/Library/Developer/Xcode/DerivedData/PaymentClient-bnsircrdeaciebedmqaliyxezdqe/Build/Products/Debug-iphonesimulator:/Users/deepesh.vasthimal/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLDINSERTLIBRARIES=/Users/deepesh.vasthimal/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Users/de
`
### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ ddd5672892a4cbaacf1c8703ad2578e4f44e05ed

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaymentsKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PaymentsKit
  pod 'JOSESwift', '2.2.1', :inhibit_warnings => true
  pod 'GMEllipticCurveCrypto', '1.3', :inhibit_warnings => true
  pod 'CryptoSwift', '~> 1.3.1', :inhibit_warnings => true
  
  target 'PaymentsKitTests' do
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

Framework : https://github.com/deepesh259nitk/PaymentsKit

Client App : https://github.com/deepesh259nitk/PaymentClient

The Client App crashes as it launches when using the XCFramework from the Framework repo above.

**Comment by deepesh259nitk** [comment]
I am using a custom framework created using 3 different cocoapods. I am using this custom framework in a client app by dropping the xc framework created. As soon as the client app launches it crashes with below crash logs. I have seen this issue reported many other places on apple and stackoverflow but i could not find a proper answer which worked for me. Now i have uploaded both the client app and the framework repo to github so that anyone trying to help me can actually see the set up and code. Please can any one suggest a proper solution to this issue.

Framework : https://github.com/deepesh259nitk/PaymentsKit

Client App : https://github.com/deepesh259nitk/PaymentClient

Crash Logs on app launch

dyld: Symbol not found: $s11CryptoSwift7PaddingO5pkcs7yA2CmFWC Referenced from: /Users/deepesh.vasthimal/Library/Developer/Xcode/DerivedData/PaymentClient-bnsircrdeaciebedmqaliyxezdqe/Build/Products/Debug-iphonesimulator/PaymentsKit.framework/PaymentsKit Expected in: /Users/deepesh.vasthimal/Library/Developer/CoreSimulator/Devices/A0876375-98D5-4215-A139-68F29E787388/data/Containers/Bundle/Application/D954732B-EDDC-478E-85C4-C5C9B14FDDEE/PaymentClient.app/Frameworks/CryptoSwift.framework/CryptoSwift in /Users/deepesh.vasthimal/Library/Developer/Xcode/DerivedData/PaymentClient-bnsircrdeaciebedmqaliyxezdqe/Build/Products/Debug-iphonesimulator/PaymentsKit.framework/PaymentsKit dyld: launch, loading dependent libraries DYLDSHAREDCACHEDIR=/Users/deepesh.vasthimal/Library/Developer/CoreSimulator/Caches/dyld/19H2/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A372 DYLDROOTPATH=/Users/deepesh.vasthimal/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLDLIBRARYPATH=/Users/deepesh.vasthimal/Library/Developer/Xcode/DerivedData/PaymentClient-bnsircrdeaciebedmqaliyxezdqe/Build/Products/Debug-iphonesimulator:/Users/deepesh.vasthimal/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLDINSERTLIBRARIES=/Users/deepesh.vasthimal/Downloads/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Users/de

Things which I have tried.

- I tried removing the CryptoSwift completely to see if the error happens due to this pod, but the crash then comes to JOSESwift which is another pod.
- I have realised the crash happens as it cannot find specific symbols both in CryptoSwift and JOSESwift. And also when i use specific methods of these libraries.
 for example if i use the AES method of CryptoSwift if you see my repo for framework, by adding the below code the crash happens, Just including the pod does not crash but usage of it produces the crash.

_$s11CryptoSwift7PaddingO5pkcs7yA2CmFWC

guard let aesObject = try? AES(key: [UInt8](Data()),
               blockMode: CBC(iv: Array(Data())),
               padding: .pkcs7) else {   return "" }

- I am also adding the pods in the client app so that it does not get added twice if you see Client App repo you will see all the 3 pods are added.

**Comment by dnkoutso** [comment]
Can you please try 1.10 release?

**Comment by deepesh-vasthimal-cko** [comment]
> 1.10

@dnkoutso thanks, i just updated my cocoa-pods to 1.10 and still see the same crash. Anything else i can try ? Do you want to check my repo and see if any settings needs change for this crash to go away ?

**Comment by dnkoutso** [comment]
A sample app always helps, I might not have the time to take a look but others may.

**Comment by deepesh-vasthimal-cko** [comment]
This issue is fixed , please refer the solution here : https://github.com/CocoaPods/CocoaPods/issues/9775, Thanks for your support. 

Solution is to add below in the pod file of the client app. 

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
end
end
end

**Comment by nick3389** [comment]
@deepesh-vasthimal-cko I confirm it works for me too. My case is that I embedded a .xcframework in a third party, which framework has pod dependencies and I had the same crash. My Cocoapods version is 1.10.0. Will there be any fix in a future release?

**Comment by KPatel91** [comment]
@deepesh-vasthimal-cko thank you so much

**Comment by provBarryTolnas** [comment]
The suggested fix is really a workaround. It has the side-effect of building all pods in the project in ["library evolution mode" ](https://docs.swift.org/swift-book/ReferenceManual/Attributes.html#ID620) which means all [enums in the pods are nonfrozen](https://docs.swift.org/swift-book/ReferenceManual/Statements.html#ID602). This triggers compiler warnings about needing to add `@unknown default:` to every switch over one of these nonfrozen enums from every pod. In many cases these are non-sensical since they are not in libraries that are dynamically linked and therefore new unknown cases can't be added without recompiling the parent project anyway. So they aren't protecting us from anything. In these case we _want_ the compiler to give an error for missing case.

**Comment by Prathap-iOS** [comment]
I am getting this error and app is crashing in Simulator on launch in Xcode 15.

dyld[1382]: Symbol not found: _$s12MessagingAPI10ObservableP11addObserver_05eagerE08onRemove_AA16ObservationTokenCqd___ABQzSgy10Foundation4UUIDVcSgyqd__Sg_AmItctRld__ClFTq
  Referenced from: <E5F303BC-37EE-3D86-B963-0F0E67D66268> /Users/nowfloats/Library/Developer/CoreSimulator/Devices/D2153E36-7A57-47AF-8B22-FA452E65CA9F/data/Containers/Bundle/Application/86CB2DD9-343B-4E60-AC6A-EC58B3C563E9/Boost.app/Frameworks/ChatSDK.framework/ChatSDK
  Expected in:     <B9B4AA06-0F82-3BE2-831F-07DBAA33B595> /Users/nowfloats/Library/Developer/CoreSimulator/Devices/D2153E36-7A57-47AF-8B22-FA452E65CA9F/data/Containers/Bundle/Application/86CB2DD9-343B-4E60-AC6A-EC58B3C563E9/Boost.app/Frameworks/MessagingAPI.framework/MessagingAPI

How can I fix this issue?

**Comment by janwandter** [comment]
> I am getting this error and app is crashing in Simulator on launch in Xcode 15.
> 
> dyld[1382]: Symbol not found: _$s12MessagingAPI10ObservableP11addObserver_05eagerE08onRemove_AA16ObservationTokenCqd___ABQzSgy10Foundation4UUIDVcSgyqd__Sg_AmItctRld__ClFTq Referenced from: /Users/nowfloats/Library/Developer/CoreSimulator/Devices/D2153E36-7A57-47AF-8B22-FA452E65CA9F/data/Containers/Bundle/Application/86CB2DD9-343B-4E60-AC6A-EC58B3C563E9/Boost.app/Frameworks/ChatSDK.framework/ChatSDK Expected in: /Users/nowfloats/Library/Developer/CoreSimulator/Devices/D2153E36-7A57-47AF-8B22-FA452E65CA9F/data/Containers/Bundle/Application/86CB2DD9-343B-4E60-AC6A-EC58B3C563E9/Boost.app/Frameworks/MessagingAPI.framework/MessagingAPI
> 
> How can I fix this issue?

I'm having the same problem with the same libraries. Did you find a solution?

**Comment by KosFM** [comment]
> This issue is fixed , please refer the solution here ( last comment ): #9775, Thanks for your support.
> 
> Solution is to add below in the pod file of the client app and do a pod deintegrate and pod install and the crash goes away.
> 
> ```
> post_install do |installer|
> installer.pods_project.targets.each do |target|
> target.build_configurations.each do |config|
> config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
> end
> end
> end
> ```

Thanks to this configuration, many crash-related issues can be resolved. However, I was unable to fix my issue using just these `post_install` configurations. After extensive research and several trial-and-error attempts, I discovered that the problem might also be linked to `IPHONEOS_DEPLOYMENT_TARGET` updates in the target configurations during the `post_install` phase.

If you're updating the `IPHONEOS_DEPLOYMENT_TARGET` in your Podfile, try downgrading it to a lower version. This adjustment helped resolve the issue in conjunction with the `BUILD_LIBRARY_FOR_DISTRIBUTION` flag. Although I couldn't fully understand the interaction between this flag and the dynamic linker, reverting the deployment target version successfully resolved my issue.

**Comment by nicolastinkl** [comment]
> config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

It's work for me .
before settings with :config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'  ,will be crash .

after code:
`
post_install do |installer|
  installer.pods_project.targets.each do |target|
    
    target.build_configurations.each do |config|
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
    
    flutter_additional_ios_build_settings(target)
  end
end
`

It's running sucessfully
