### ISSUE TITLE
Xcode 12 warning update to recommended settings

### ISSUE THREAD

**Issue by tahirmt** [CocoaPods/CocoaPods#10189]
running CocoaPods 1.10 with Xcode 12. I am getting the following warning for all targets "Target '<target-name>' overrides the Architectures setting. This will remove the setting and allow Xcode to automatically select Architectures available based on hardware available for the active platform and deployment target"

**Comment by dnkoutso** [comment]
Did you update Xcodeproj? `gem update xcodeproj`.

Alternatively please include a sample app demonstrating the issue.

**Comment by tahirmt** [comment]
I'm not using `xcodeproj` gem. I'll create a sample app and report back.

**Comment by dnkoutso** [comment]
CocoaPods uses the xcodeproj gem. If you are using CocoaPods then its using this gem and its version is not locked except the major part.

Xcodeproj manages the default build settings for the Pods.xcodeproj CocoaPods generates.

**Comment by tahirmt** [comment]
Looks like I have 1.19 installed already.

**Comment by tahirmt** [comment]
@dnkoutso when trying to create a sample project I found my issue. There was an old override in the pod file. Thanks for the help.

**Comment by dnkoutso** [comment]
awesome!

**Comment by Cy-4AH** [comment]
CocoaPods 1.10.1 Xcode 12.3 Xcodeproj 1.19.0 yet again "Pods project: Update to recommended settings"

**Comment by simonschellaert** [comment]
I'm running into the same issue (Xcode 12.4 - cocoapods 1.10.1 - xcodeproj 1.19.0).

As a temporary workaround, you can add the following to your `Podfile`:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'ARCHS'
    end
  end
end
```

This will remove the _Architectures_ setting from all of the pods in your project, which allows them to simply inherit the project/workspace _Architectures_. This was inspired by [this blog post](https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/).

**Comment by EvgenyKarkan** [comment]
This issue should be re-open.

**Comment by gmogames** [comment]
Xcode 12.5.1 (12E507), cocapods 1.10.2 I'm still getting:
![image](https://user-images.githubusercontent.com/1765046/130281555-8c5ad1d4-8a6c-4158-94c4-1c07c60d9272.png)

can we re-open this @dnkoutso ?
