### ISSUE TITLE
Archive failed - Argument list too long - disable_input_output_paths info

### ISSUE THREAD

**Issue by jordimele** [CocoaPods/CocoaPods#10200]
## What did you do?

Do archive project.

## What did you expect to happen?

Archive finish sucessfully

## What happened instead?

Archive failed.
`Verify final result code for completed build operation
Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below.`
`unable to spawn process (Argument list too long)`

## CocoaPods Environment

   CocoaPods : 1.8.4
              Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.7.3
               Host : Mac OS X 10.15.7 (19H2)
            Xcode : 11.1 (11A1027)
                  Git : git version 2.21.0 (Apple Git-122)
    Ruby lib dir : /usr/local/Cellar/ruby/2.4.2_1/lib

## Project that demonstrates the issue

The project is private and cannot be shared.

The problem could be solved using the disable_input_output_paths key in the podfile:
`install! 'cocoapods', :disable_input_output_paths => true`

With this, the input/output files path is left blank and the file can be done correctly.
The question is to know what the input/output files path is for, which is generated every time we perform a pod install or a pod update, but we configure the **disable_input_output_paths** key in the podfile, which in that case, the input/output files path is not filled.

Could you tell us about the use of the input / output files path?

What risks, advantages, disadvantages, performance, ... exist using the disable_input_output_paths key, which does not generate input / output files?

Thank you.

Sample project that NOT use disable_input_output_paths:
Build Phases -> Embed Pods Frameworks -> Input Files y Output Files:
<img width="1723" alt="old" src="https://user-images.githubusercontent.com/11957195/98643677-a5fa2000-232f-11eb-8714-e18f897304b7.png">

Sample project that USE disable_input_output_paths:
Build Phases -> Embed Pods Frameworks -> Input Files y Output Files:
<img width="1835" alt="new" src="https://user-images.githubusercontent.com/11957195/98643706-ae525b00-232f-11eb-8199-6646437bb6fd.png">

**Comment by jordimele** [comment]
Someone from the Cocoapods team could let us know about the use of the input / output files path?

What risks, advantages, disadvantages, performance, ... exist using the disable_input_output_paths key, which does not generate input / output files?

Is there any documentation?

Thank you.

**Comment by dnkoutso** [comment]
Input/output paths help the cocoapods script phases run faster. There's been an issue for a while with Xcode 11 though that has been fixed in Xcode 12.

You may safely disable the usage of these paths. Things should continue working but incremental builds might be slower due to the fact that Xcode will always invoke the CocoaPods scripts.

For now I am going to close as I do not see an action item here for CocoaPods.
