### ISSUE TITLE
Can CocoaPods download prebuilt framework?

### ISSUE THREAD

**Issue by ScottPierce** [CocoaPods/CocoaPods#10208]
My team has several teams who own features in a single repository. We're struggling to find a sane way to version and release features to be used in the main application. Does CocoaPods have a way to download and hook up a prebuilt library or framework?

**Comment by dnkoutso** [comment]
Yes, this is being used in many places and constantly. Just include a `.zip` file and upload it somewhere with `s.vendored_frameworks` or `s.vendored_libraries`.

**Comment by ScottPierce** [comment]
> Yes, this is being used in many places and constantly. Just include a `.zip` file and upload it somewhere with `s.vendored_frameworks` or `s.vendored_libraries`.

Where can I find documentation on this? What do you mean upload it somewhere? Just to any host? Can these frameworks be private and protected so they aren't publicly accessibile?

**Comment by igor-makarov** [comment]
[Zip source](https://guides.cocoapods.org/syntax/podspec.html#source) - use basic auth for password protection or aby other  scheme.

[Vendored frameworks](https://guides.cocoapods.org/syntax/podspec.html#vendored_frameworks) - to declare what to link.

**Comment by dnkoutso** [comment]
You can host it privately yes and anywhere as long as it is accessible from the network that is trying to reach the host.
