### ISSUE TITLE
Unable to find a specification for `UrbanAirship-iOS-SDK (~> 10.0.3)`

### ISSUE THREAD

**Issue by ChetanaJavali** [CocoaPods/CocoaPods#10201]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

Trying to set up the mobile application for ios ( versions using currently : node : v12.16.1 , npm : 6.13.4 , IOS version : 10.15.7)

Steps followed: 
1) In the root folder - sudo gem install cocoapods
2) npm install
3) cd ios
4) pod install 

Getting the below error :

**[!] Unable to find a specification for `UrbanAirship-iOS-SDK (~> 10.0.3)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.**

Tried solutions:
1) updating the pod
2) reinstalling all the dependencies again
3) setting up project multiple times
4) uninstalling and installing back again.
5) Tried different UrbanAirship versions, getting the same error 

However, no luck !! Can anyone please help with the issue what i am facing.

**Comment by dnkoutso** [comment]
As the error message suggests make sure the master cocoapods specs repo is setup (or CDN) and is fully updated.

It worked for me.
```
Analyzing dependencies
Downloading dependencies
Installing UrbanAirship-iOS-SDK (10.0.4)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```
