### ISSUE TITLE
Cpp compiled failed when remove use_frameworks!

### ISSUE THREAD

**Issue by YiYiZheng** [CocoaPods/CocoaPods#10211]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
1. I remove 'use_frameworks!' from podfile
2. pod install
3. Run project

## What did you expect to happen?
Project compile successfully

## What happened instead?
Compile cpp(*.mm) failed

clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)

## CocoaPods Environment
1.10.0

## Project that demonstrates the issue
No

But here is the clang crash log
https://github.com/YiYiZheng/Repo/blob/main/clang.crash

**Comment by dnkoutso** [comment]
Without a sample app that clearly demonstrates the issue we cannot diagnose this.
