### ISSUE TITLE
How to create multiple targets podspec like in SPM

### ISSUE THREAD

**Issue by malcommac** [CocoaPods/CocoaPods#10212]
Hi guys,

My library is composed by two modules:
- The library core in Swift
- A module in C which includes CHTMLSAXParser

This is the structure

<img width="933" alt="Screenshot 2020-11-16 at 18 09 43" src="https://user-images.githubusercontent.com/235645/99285365-b3377300-2837-11eb-96c1-8726dc097e05.png">

Now in order to compile it in SPM I need to create two targets:

```swift
import PackageDescription

let package = Package(
    name: "MyLib",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "MyLib",
            targets: ["MyLib"]),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "CHTMLSAXParser",
            dependencies: []),
        .target(
            name: "MyLib",
            dependencies: ["CHTMLSAXParser"])
    ]
)
```

This is pretty straightforward (and required because I can't mix both ObjC and Swift in the same module): in MyLib a source swift file call `import CHTMLSAXParser` and everything works fine.
However I don't know what's the correct way to replicate the same behaviour with CocoaPods podspec file.
Any idea?

**Comment by igor-makarov** [comment]
In CocoaPods, you can either create two separate pods for your targets (with separate `.podspec`s), or just mix the ObjC and Swift sources together, as CocoaPods doesn't have that limitation you mentioned.

**Comment by malcommac** [comment]
The best solution maybe to include the same sources in a single package but one file `import CHTMLSAXParser` and I don't know how to suppress this in case of cocoapods and keep it in case of SPM.  

The alternative seems better but can I reference another local podspec from inside the main library podspec?

**Comment by igor-makarov** [comment]
Maybe try `#if canImport(CHTMLSAXParser)`?

More info:  
https://www.hackingwithswift.com/example-code/language/how-to-check-whether-a-module-is-available-using-canimport

**Comment by dnkoutso** [comment]
You can, but not by `:path` as `:path` is not available in podspecs. If you are not planning on publishing your main podspec then just type `s.dependency 'MyLocalPod'` and then ensure do add in your `Podfile` `pod 'MyLocalPod', :path => '../path/to/MyLocalPod.podspec'`

**Comment by malcommac** [comment]
I'll publish the pod. By the way @igor-makarov suggestions worked like a charm.
Just to recap: the limit with mixed Swift-ObjC code does not apply to CocoaPods packages so I'll integrate all inside the same module.

My podspec, just for reference, is this:

```ruby
Pod::Spec.new do |s|
  s.name         = "MyLib"
  ...
  s.source_files  = "Sources/**/*"
  s.ios.public_header_files =  'Sources/**/*.h'
  s.xcconfig  = {
     'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2',
     'OTHER_LDFLAGS' => '-lxml2'
}
  s.frameworks  = "Foundation"
  s.swift_versions = ['5.0', '5.1', '5.3']
end
```

When imported from CocoaPods I'll not need of `import CHTMLSAXParser` (the second module) so I can bypass it using `#if canImport(CHTMLSAXParser)?`: 

```swift
#if canImport(CHTMLSAXParser)?
  import CHTMLSAXParser
#endif
```

Thank you guys 👍
