### ISSUE TITLE
ionic cordova build ios  - The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation

### ISSUE THREAD

**Issue by prabhashibuddhima** [CocoaPods/CocoaPods#10214]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

npm install
ionic cordova platform add ios@5.1.1
cordova plugin add cordova-plugin-wkwebview-engine
sudo gem install cocoapods
pod repo update
ionic cordova prepare ios
ionic cordova build ios

## What did you expect to happen?
.Build should be successful

## What happened instead?
Build failed with error  : The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation

**Comment by dnkoutso** [comment]
Please provide a sample app _without_ Cordova. I recommend filing an issue with Cordova.

**Comment by prabhashibuddhima** [comment]
I have solved the issue by running the below commands to my project directory:

`npm install `
`sudo gem install cocoapods`
`pod repo update`
`ionic cordova platform add ios@5.1.0`
`ionic cordova prepare ios`
`cordova build ios`

**Comment by DuaneQ** [comment]
@prabhashibuddhima is this an ionic project?  I'm having the same issue.

**Comment by prabhashibuddhima** [comment]
> @prabhashibuddhima is this an ionic project? I'm having the same issue.

Hi,

@DuaneQ yes. it's an ionic project
