### ISSUE TITLE
CocoaPods not parsing simctl output, results in error

### ISSUE THREAD

**Issue by rowungiles** [CocoaPods/CocoaPods#10213]
When I try a `pod lib lint` I'm receiving an error:
`    - ERROR | [iOS] unknown: Encountered an unknown error (784: unexpected token at '2020-11-17 12:11:19.652 simctl[48241:1246091] apply_selection_policy_once: prefer use of removable GPUs (via com.apple.CoreSimulator.simctl:GPUSelectionPolicy->preferRemovable)`

I have an eGPU attached to my machine which causes additional logs to come back. 
For example:

`xcrun simctl list`will return:
```
xcrun simctl list
2020-11-17 12:19:37.295 simctl[53441:1264174] apply_selection_policy_once: prefer use of removable GPUs (via com.apple.CoreSimulator.simctl:GPUSelectionPolicy->preferRemovable)
== Device Types ==
```

I think that the cause might be `lib/cocoapods/simctl.rb` (and I suppose others where parsing occurs) failing to parse this output correctly.

I'm using CocoaPods 1.10.0 on macOS 11.0.1.

**Comment by dnkoutso** [comment]
What version of Xcode? Did you also `gem update fourflusher`?

**Comment by rowungiles** [comment]
I see no updates running update on fourflusher, it's on fourflusher (2.3.1).

I'm using Xcode Version 12.2 (12B45b).

**Comment by dnkoutso** [comment]
This might be an issue with Xcode 12.2 probably, will need to handle the output of `xcrun simctl list`.

**Comment by dnkoutso** [comment]
@rowungiles could use some help here perhaps. This probably can move to `fourflusher` repo.

**Comment by owalerys** [comment]
I reported the same issue with Flutter: https://github.com/flutter/flutter/issues/72733

That specific line that you're seeing `apply_selection_policy_once` is coming back in `stderr` so some tools assume that to be a fatal error, though it appears to only be a warning.

**Comment by rowungiles** [comment]
@dnkoutso did you want me to raise an issue in the `fourflusher` issues?

**Comment by Alex009** [comment]
same problem too...
cocoapods 1.10.0
macos 11.1
xcode 12.3

**Comment by dnkoutso** [comment]
Fixed with https://github.com/CocoaPods/fourflusher/pull/27

**Comment by rowungiles** [comment]
Thanks so much for committing a fix for this @dnkoutso 🥇
