### ISSUE TITLE
Cocoapods 1.10.0 caused issues with assets folder

### ISSUE THREAD

**Issue by ahmedgomaa27** [CocoaPods/CocoaPods#10215]
ℹ After updating Cocoapods to 1.10.0, I tried to run the project on Xcode 12.1, any image from my assets returns nil **in Runtime** only, when i downgrade Cocoapods to version 1.9.1 it works fine!

Using CocoaPods: 1.10.0

Using Xcode 12.1

# Report

## What did you do?
- update cocoapods to 1.10.0 
- Run `pod update` in terminal
any ideas?

**Comment by dnkoutso** [comment]
This is not a sufficient issue report. Please upload sample app demonstrating issue and reproducible steps.

**Comment by ahmedgomaa27** [comment]
@dnkoutso  please check updates

**Comment by dnkoutso** [comment]
Still need a sample app here. It takes a long of time to reproduce such reports without a sample app.

**Comment by ahmedgomaa27** [comment]
@dnkoutso provide me with UDID and email so I'll create IPA and send it for you

**Comment by GengJian** [comment]
I encountered the same problem. Trigger conditions only need set resources path like this:

s.resources = [
    'XDCommonModule/Assets/*.xcassets',
] 

while in cocoapods1.9.3+xcode11 ✅ cocoapods1.9.3+xcode12 ✅ cocoapods1.10.0+xcode12 ❌
maybe wrong with ".car"

**Comment by waterfly** [comment]
I have the same problem. 
It doesn't  work when in CocoaPods 1.10.0 + Xcode 12.2 , but it's fine in CocoaPods 1.9.3 + Xcode 12.2.

In CocoaPods 1.10.0 + Xcode 12.2
Build Phase:
When there are multiple .xcasset files in the Pod library, it prompts that the xx.car file is not found.
For example:
The pod lib have Color.xcassets, Member.xcassets, The Xcode  prompts that can't find Color.car and Member.car

**Comment by gonghonglou** [comment]
I have the same problem with CocoaPods 1.10.0 + Xcode 12.2

I have executed pod install and success, but build error:
```
Resource "/Users/xxx/Library/Developer/Xcode/DerivedData/App-ayaltzewtboqekeslwlmxhqpomtw/Build/Products/Debug-iphonesimulator/xxPod/xxPod.framework/xxPod.car" not found. Run 'pod install' to update the copy resources script.
```
