### ISSUE TITLE
pod install  [!] Oh no, an error occurred.

### ISSUE THREAD

**Issue by silencHuaTian** [CocoaPods/CocoaPods#10226]
Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=incompatible+library+version+-+%2FUsers%2Flizhiquan%2F.rvm%2Frubies%2Fruby-2.6.3%2Flib%2Fruby%2Fgems%2F2.6.0%2Fgems%2Fffi-1.13.1%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by zjl801** [comment]
same there

**Comment by yajuncao** [comment]
same there,somebody can  resolve this question？
