### ISSUE TITLE
Wrong download cache path

### ISSUE THREAD

**Issue by SolaWing** [CocoaPods/CocoaPods#10228]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

the following function in downloader/cache.rb, for a 1.0.1 version spec, will return 1.0.podspec.json, make the newer version use the wrong cache.
```
      def path_for_spec(request, slug_opts = {})
        path = root + 'Specs' + request.slug(**slug_opts)
        path.sub_ext('.podspec.json')
      end
```

**Comment by dnkoutso** [comment]
Can you make a PR with a test?

**Comment by SolaWing** [comment]
https://github.com/CocoaPods/CocoaPods/pull/10231 already make a PR. @dnkoutso

**Comment by dnkoutso** [comment]
thanks, left some minor comments and questions
