### ISSUE TITLE
Invalid `Podfile` file: [!] Unable to locate the executable `node`

### ISSUE THREAD

**Issue by a007** [CocoaPods/CocoaPods#10227]
Hey i am getting pod install error

Error :

```
[!] Invalid `Podfile` file: [!] Unable to locate the executable `node`.
 #  target 'appname' do
 >    config = use_native_modules!
```

My pod file :

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'appname' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
  pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
  pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
  pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'appnameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper! 
  post_install do |installer|
    flipper_post_install(installer)

  end
end

target 'appname-tvOS' do
  # Pods for appname-tvOS

  target 'appname-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

react-native info :
```

System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 474.87 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.5.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 19, 21, 22, 23, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-Q | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: ^4.13.1 => 4.13.1 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

**pod --version**        
1.5.2

**sudo gem list cocoapods**

> cocoapods-core (1.8.4)
> cocoapods-deintegrate (1.0.4)
> cocoapods-downloader (1.3.0)
> cocoapods-plugins (1.0.0)
> cocoapods-search (1.0.0)
> cocoapods-stats (1.1.0)
> cocoapods-trunk (1.4.1)
> cocoapods-try (1.1.0)

The situation does not change when I create a new project.
I will be waiting for your help on how to proceed. Thank you

**Comment by dnkoutso** [comment]
This seems to be an issue with ReactNative integration, please file an issue there.

Also this seems a rather old version of CocoaPods, please upgrade to 1.10.0.

**Comment by olalerephillip** [comment]
someone please help i'm also getting the above error when i run pod install. i have latest version of cocoapod

**Comment by suusofttruongnv** [comment]
Have you solved this problem yet?

Let me know how to fix the error if you solved it !

Thanks!!

**Comment by Walachian** [comment]
I solved this problem with:

brew remove cocoapods && sudo gem install cocoapods

I have initially installed cocoapods by using homebrew, which got me pods version 1.5.2. I've tried to update it in numerous ways but it didn't work. 

Then I've tried tot install cocoapods from ruby gems with the above command (sudo gem install cocoapods) and even if the installation was successful and it showed that I have just installed cocoapods 1.10.1 the command line calls for pods were still pointing to the homebrew version -> so when I was typing pods --version the terminal was printing 1.5.2. 

After running (brew remove cocoapods) the command line calls automatically pointed to the gems version of cocoapods, so now when I type: pod --version -> the terminal prints 1.10.1 and pod install works fine.

Hope this helps somebody

**Comment by FinnGu** [comment]
> I solved this problem with:
> 
> brew remove cocoapods && sudo gem install cocoapods
> 
> I have initially installed cocoapods by using homebrew, which got me pods version 1.5.2. I've tried to update it in numerous ways but it didn't work.
> 
> Then I've tried tot install cocoapods from ruby gems with the above command (sudo gem install cocoapods) and even if the installation was successful and it showed that I have just installed cocoapods 1.10.1 the command line calls for pods were still pointing to the homebrew version -> so when I was typing pods --version the terminal was printing 1.5.2.
> 
> After running (brew remove cocoapods) the command line calls automatically pointed to the gems version of cocoapods, so now when I type: pod --version -> the terminal prints 1.10.1 and pod install works fine.
> 
> Hope this helps somebody

I had the same issue and was able to resolve it by upgrading cocoapods to `>=1.10.0`.

You can use homebrew, though. Just make extra sure, that you are not installing the cask, but the real formula `brew install cocoapods` (without the `--cask` option) for a more recent version.

**Comment by syedamirali14** [comment]
it is happening in my M1 , above solutions didn't work for me

**Comment by msaadh909** [comment]
same thing happening with me
`
✔ Processing template
✖ Installing CocoaPods dependencies (this may take a few minutes)
✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./test1/ios && pod install".
CocoaPods documentation: https://cocoapods.org/
`

I am also on M1 machine

**Comment by OneQuy** [comment]
> This seems to be an issue with ReactNative integration, please file an issue there.
> 
> Also this seems a rather old version of CocoaPods, please upgrade to 1.10.0.

This really works for me!!!! Thank you so muchhh

**Comment by umer-viabletree** [comment]
> > I solved this problem with:
> > brew remove cocoapods && sudo gem install cocoapods
> > I have initially installed cocoapods by using homebrew, which got me pods version 1.5.2. I've tried to update it in numerous ways but it didn't work.
> > Then I've tried tot install cocoapods from ruby gems with the above command (sudo gem install cocoapods) and even if the installation was successful and it showed that I have just installed cocoapods 1.10.1 the command line calls for pods were still pointing to the homebrew version -> so when I was typing pods --version the terminal was printing 1.5.2.
> > After running (brew remove cocoapods) the command line calls automatically pointed to the gems version of cocoapods, so now when I type: pod --version -> the terminal prints 1.10.1 and pod install works fine.
> > Hope this helps somebody
> 
> I had the same issue and was able to resolve it by upgrading cocoapods to `>=1.10.0`.
> 
> You can use homebrew, though. Just make extra sure, that you are not installing the cask, but the real formula `brew install cocoapods` (without the `--cask` option) for a more recent version.
work bro. Thanks

**Comment by umer-viabletree** [comment]
brew install cocoapods.  works in my case.
