### ISSUE TITLE
Cannot set required version 11.0.0 for a macOS CocoaPod that requires Big Sur

### ISSUE THREAD

**Issue by kyle-n** [CocoaPods/CocoaPods#10225]
* [X] 🌈 I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Created a new CocoaPod, [OnPasteboardChange](https://github.com/kyle-n/OnPasteboardChange)
- Used SwiftUI features in my CocoaPod that require macOS Big Sur
- In `TestPod.podspec`, set `  spec.platforms = { :ios => '14.0', :osx => '11.0.0' }`
- I ran `pod trunk push --allow-warnings`
- I also tried to publish the CocoaPod with `:osx => '10.16.0'` and this was rejected as well

## What did you expect to happen?

- I am able to publish a CocoaPod that requires Big Sur as a minimum version, whether by writing `11.0.0` or `10.16.0`, so users do not install the pod on a project targeting Catalina 10.15.x and then see build errors over unrecognized SwiftUI features

## What happened instead?

On `pod trunk push`, I received the response:

```
    - NOTE  | [OSX] xcodebuild:  warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.16.0, but the range of supported deployment target versions is 10.6 to 10.15.99. (in target 'App' from project 'App')
```

This happened while attempting to publish the macOS version minimum as 10.16.0 and 11.0.0.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.0.1 (20B28)
       Xcode : 12.2 (12B5044c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

https://github.com/kyle-n/OnPasteboardChange

**Comment by dnkoutso** [comment]
I believe the warning is for the generated app cocoapods creates to validate your pod. Is this warning causing an issue?

**Comment by dnkoutso** [comment]
I see you are also in a rather old version of cocoapods, can you try 1.10.0?

**Comment by kyle-n** [comment]
@dnkoutso I upgraded CocoaPods to 1.10.0 and was able to publish the CocoaPod with `spec.platforms = { :ios => '14.0', :osx => '11.0.0' }`. Having an old version of CocoaPods seems to have been the issue. Thank you for noticing that!
