### ISSUE TITLE
Got error while trying pod install

### ISSUE THREAD

**Issue by jonahbrandwagt** [CocoaPods/CocoaPods#10220]
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
pod install

* What did you expect to happen?
Installing my pod's

* What happened instead?
Error. This is on my MacBook Pro with the new M1 processor, maybe it has something to do with that.

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.1.4
        Host : macOS 11.0.1 (20B29)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KikiKickzLab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KikiKickzLab
  pod 'SwiftyJSON'

end
```

### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle - /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
This looks like an issue with `ffi` installation in your environment. There are many other issues related to this to look around for information.

At this time, CocoaPods is only a consumer of the `ffi` gem so there isn't much we can do to fix the specific issue you are getting. What we are trying to do is remove the dependency from `ffi` in a future release.

**Comment by jonahbrandwagt** [comment]
Ok, so until CocoaPods removes the fyi dependency I can't use it?

**Comment by dnkoutso** [comment]
Or fix the `ffi` gem installation in your environment.

**Comment by jonahbrandwagt** [comment]
Fixed it by running the following command: `arch -x86_64 pod install`

**Comment by mast** [comment]
Seeing the same on Mac mini with M1. I guess M1 arch is not supported?

**Comment by NSDavidObject** [comment]
+1

**Comment by handofthecode** [comment]
sudo arch -x86_64 gem install ffi

Then

arch -x86_64 pod install

**Comment by fmxfmx** [comment]
try this
https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1

**Comment by onur-eren** [comment]
Apple released a solution [https://support.apple.com/en-us/HT211861](https://support.apple.com/en-us/HT211861) until the softwares are compatible.

**Comment by kangyeting** [comment]
1.打开终端显示简介 
2.勾选以Rosetta方式打开
3. 运行 sudo gem install cocoapods （之前安装过就略过
4. 运行 sudo gem install ffi
5.最后pod install
6.source 'https://github.com/CocoaPods/Specs.git' 有的网络不好需要先移除掉

 this is true : https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1

**Comment by Kaspik** [comment]
We can definitely update title of this issue as compatibility with M1 chip. Same issues here happening on completely fresh and new MacBook Air with M1.

**Comment by Riton2013** [comment]
Guys, do you have any ideas to fix this problem,  I am using MacBook air with M1 chip.
I can't use "pod search" or "pod update" command so far.

**Comment by Kaspik** [comment]
As suggested you need to duplicate terminal, run terminal through rosetta (aka x86) and use it there until CocoaPods add compatibility for ARM.

**Comment by Riton2013** [comment]
It seem little different with what I met. I can use "pod install", but not "pod search". I already make terminal run with rosetta, I don't know what happen.

**Comment by rmnkbofficial** [comment]
> sudo arch -x86_64 gem install ffi
> 
> Then
> 
> arch -x86_64 pod install

This worked for me

**Comment by cnknv** [comment]
Here is the solution:
1- Go to your applications > utilities folder. 
2- Right click and click "Get Info" 
3- Check "Open Using Rosetta" option
4- Start your terminal app
5- `sudo gem install cocoapods`
6- `sudo gem install ffi`
7- `pod install`

worked on my end

**Comment by dnkoutso** [comment]
This seems an issue with installing `ffi` gem on M1. At this time cocoapods depends on `ffi` gem but we are hoping to remove it in a future version which is the only thing that would circumvent this issue.

In the meantime please seek out alternatives on how to successfully install `ffi` gem within M1 environment.

**Comment by OKNoah** [comment]
I see people saying they can do this without Rosetta, but I can't reproduce that. It's very annoying.

**Comment by OKNoah** [comment]
> sudo arch -x86_64 gem install ffi
> 
> Then
> 
> arch -x86_64 pod install

Can you clarify... does this mean you have to exclude arm64 and basically do everything after with x86_64?

**Comment by dcx86** [comment]
> Here is the solution:
> 1- Go to your applications > utilities folder.
> 2- Right click and click "Get Info" on your terminal app
> 3- Check "Open Using Rosetta" option
> 4- Start your terminal app
> 5- `sudo gem install cocoapods`
> 6- `sudo gem install ffi`
> 7- `pod install`
> 
> worked on my end

This is the right approach! I had to do some extra steps:
1- Uninstall cocoapods and ffi to begin with
2- Restart terminal after checking the option "Open Using Rosetta"

**Comment by lemanno** [comment]
> > sudo arch -x86_64 gem install ffi
> > Then
> > arch -x86_64 pod install
> 
> This worked for me

Mac Mini M1 - worked too

**Comment by AyazAI** [comment]
It worked on Mac m1

**Comment by OKNoah** [comment]
All, it feels like I've gotten 100 emails about this fix/workaround of using `arch -x86_64` (or using a Terminal in Rosetta mode). It's been posted a few times here already, and likewise on half a dozen other issues on the subject. It's probably futile to say this, but just keep I mind people are following these issues to wait for other developments.

**Comment by RosalieWessels** [comment]
Had the same issue, got it fixed after opening Terminal using Rosetta and after @handofthecode's answer.

**Comment by mhborujerdi** [comment]
Hello, You should install the latest version of CommandLineTools for Xcode to fix this issue.

**Comment by krzyzanowskim** [comment]
@mhborujerdi saying it fixes itself with Xcode 12.4 CommandLineTools, or 12.5 beta3?

**Comment by Mahdibn** [comment]
this worked for me
first:
"sudo arch -x86_64 gem install ffi"
then:
"arch -x86_64 pod install"

**Comment by hamidmustafa** [comment]
To @all 

**A perfect solution is here.** 


 I fixed the ffi issue by uninstalling my faulty Ruby version and CocoaPods, then I used the -x86_64 arch to reinstall ffi and CocoaPods.
 
These are the steps I did to get back to a working state (and to apply the M1 workarounds for ffi):
Uninstall Ruby with: brew uninstall ruby --force
Uninstall CocoaPods. At first, try to list all CocoaPods versions / components with gem list --local | grep cocoapods. Then uninstall them one by one, in my case:
sudo gem uninstall cocoapods
sudo gem uninstall cocoapods-core
sudo gem uninstall cocoapods-downloader
etc.
As a next step I was able to reinstall ffi and then CocoaPods with:
sudo arch -x86_64 gem install ffi
sudo arch -x86_64 gem install cocoapods
 
Once done, I could run the pod install as expected. Note that I had the Terminal open all the time in standard mode - no Rosetta required. 
 
 
Source: https://stackoverflow.com/questions/66644365/cocoapods-on-m1-apple-silicon-fails-with-ffi-wrong-architecture

**Comment by AbhilashRaipally** [comment]
> To @ALL
> 
> **A perfect solution is here.**
> 
> I fixed the ffi issue by uninstalling my faulty Ruby version and CocoaPods, then I used the -x86_64 arch to reinstall ffi and CocoaPods.
> 
> These are the steps I did to get back to a working state (and to apply the M1 workarounds for ffi):
> Uninstall Ruby with: brew uninstall ruby --force
> Uninstall CocoaPods. At first, try to list all CocoaPods versions / components with gem list --local | grep cocoapods. Then uninstall them one by one, in my case:
> sudo gem uninstall cocoapods
> sudo gem uninstall cocoapods-core
> sudo gem uninstall cocoapods-downloader
> etc.
> As a next step I was able to reinstall ffi and then CocoaPods with:
> sudo arch -x86_64 gem install ffi
> sudo arch -x86_64 gem install cocoapods
> 
> Once done, I could run the pod install as expected. Note that I had the Terminal open all the time in standard mode - no Rosetta required.
> 
> Source: https://stackoverflow.com/questions/66644365/cocoapods-on-m1-apple-silicon-fails-with-ffi-wrong-architecture

This seems to be positive. But did you reinstall ruby? Which version. Can you share that command as well

**Comment by KaneCheshire** [comment]
I've just installed Cocoapods on a brand new M1 Mac and `pod trunk push` gives me this same error. It's December now, and over a year since Apple Silicone has been around. Could something not have been built into Cocoapods by now to at least help people fix it without having to dig around in long issue threads? Or even, just a small note on the install page? There's absolutely nothing about it here: https://guides.cocoapods.org/using/getting-started.html

**Comment by johndpope** [comment]
@KaneCheshire - wouldn't a simple 
` arch -x86_64 pod trunk push`
fix this?

**Comment by endronk** [comment]
> try this https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1

> If you can use Homebrew to manage cocoapods.
> 
> ### Uninstall the local cocoapods gem
> sudo gem uninstall cocoapods
> 
> ### Reinstall cocoapods via Homebrew
> brew install cocoapods

Awesome. This works for me without the need to use `arch` command, just use a plain `pod install`.

**Comment by gitrthanki1** [comment]
sudo arch -x86_64 gem install ffi

Then

arch -x86_64 pod install

unable to resolve using above command. I'm getting **arch: posix_spawnp: gem: Bad CPU type in executable**

**Comment by gitrthanki1** [comment]
> Fixed it by running the following command: `arch -x86_64 pod install`
this command gives 'arch: posix_spawnp: pod: Bad CPU type in executable' on my macOS

**Comment by soheilaGhayour** [comment]
> sudo arch -x86_64 gem install ffi
> 
> Then
> 
> arch -x86_64 pod install
> 
> unable to resolve using above command. I'm getting **arch: posix_spawnp: gem: Bad CPU type in executable**

same here

**Comment by osamamohammed98** [comment]
> sudo arch -x86_64 gem install ffi
> 
> Then
> 
> arch -x86_64 pod install

this work for me

**Comment by jaweria-siddiqui-cygnis** [comment]
> arch -x86_64 pod install

work for me. Thank You

**Comment by iSimar** [comment]
> Here is the solution: 1- Go to your applications > utilities folder. 2- Right click and click "Get Info" on your terminal app 3- Check "Open Using Rosetta" option 4- Start your terminal app 5- `sudo gem install cocoapods` 6- `sudo gem install ffi` 7- `pod install`
> 
> worked on my end

This worked on M1 pro

**Comment by bobokhon7** [comment]
> sudo arch -x86_64 gem install ffi
> 
> Then
> 
> arch -x86_64 pod install

Thanks a lot
You saved my life
I spent f***ng 8 hours for this

**Comment by digitaltim-de** [comment]
same error and cant fix it m1pro

**Comment by glennposadas** [comment]
Read up, 2022, M1 with Rbenv.

My current Rbenv setup (v3.1.2) works fine in most of the project, but here comes a strange project, cocoapods was acting up only on this project.


1. After uninstalling all the cocoapods remnants,
2. Set both local and global of your Rbenv to `system`.
```
rbenv local system
```

and

```
rbenv global system
```

3. Then proceed to your usual M1 pod install, like so:
```
arch -x86_64 pod install
```

voila!

**Comment by martmalo** [comment]
With Mac M1(2020) I can verify that this [stackoverflow](https://stackoverflow.com/a/65334677/19844222) fixed the issue.

**Comment by umairalirehan** [comment]
run this command in ios folder
arch -arm64 brew install cocoapods

**Comment by okerivy** [comment]
**Flutter** 

```
sudo gem uninstall ffi && sudo gem install ffi -- --enable-libffi-alloc
pod install
```

**Comment by shevakuilin** [comment]
> Here is the solution: 1- Go to your applications > utilities folder. 2- Right click and click "Get Info" on your terminal app 3- Check "Open Using Rosetta" option 4- Start your terminal app 5- `sudo gem install cocoapods` 6- `sudo gem install ffi` 7- `pod install`
> 
> worked on my end

This worked for me, thx!😘

**Comment by anuragfexle** [comment]
> arch -x86_64 pod install

this works

**Comment by Greed1997** [comment]
this not works fucking retards

**Comment by mostafabrazi** [comment]
This worked for me
https://stackoverflow.com/a/66556339/6192834

**Comment by KunjKanani** [comment]
I deleted my `podfile.lock` and ran `pod install`.

It's work for me. I am using Flutter.
