### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by AndreasKr** [CocoaPods/CocoaPods#10223]
I followed the installation guide on 
https://guides.cocoapods.org/using/getting-started
updated .bash_profile 
opened new shell

andreas$ echo $PATH
/Users/andreas/.gem/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
andreas$ gem install cocoapods --user-install

Expectation was that installation runs without errors.

But I received the following error:

        Successfully installed httpclient-2.8.3
        A new major version is available for Algolia! Please now use the https://rubygems.org/gems/algolia gem to get the latest 
        features.
        Successfully installed algoliasearch-1.27.5
        Building native extensions. This could take a while...
        ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.
        current directory: /Users/andreas/.gem/ruby/2.6.0/gems/ffi-1.13.1/ext/ffi_c
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I 
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20201119-1791-16cis7f.rb 
    extconf.rb 
        checking for ffi.h... *** extconf.rb failed ***
        Could not create Makefile due to some reason, probably lack of necessary

Looking in in the directory, ffi.h is missing...

**Comment by dnkoutso** [comment]
Please see related `ffi` gem.

Please install `gem install ffi` and try again.

At this time this does not appear a bug or issue with the cocoapods library itself.
