### ISSUE TITLE
Type has different definitions in multiple modules (Xcode 12 specific)

### ISSUE THREAD

**Issue by till0xff** [CocoaPods/CocoaPods#10235]
# Report

## What did you do?

I have a large xcode project with many private pods (> 50). The project contains a lot of legacy code in ObjC that also uses these pods (bridging header required). In xcode 12 project build fails with error:
```
'<Type>' has different definitions in different modules; first difference is definition in module '<ModuleName>.Swift' found...
```

I removed `MODULEMAP_FILE` parameter for targets in `Pods.xcodeproj` and the project was successfully built. Unfortunately, CocoaPods does not allow to disable `modulemap` generation. I made #10207 that adds this feature. To disable `modulemap` generation, just specify `spec.module_map = false` in the `podspec` file.

## What did you expect to happen?

Build successful

## What happened instead?

Build failed

## Project that demonstrates the issue

This is a very simplified project example that reproduces the problem.

https://github.com/till0xff/cocoapods-skip-modulemap-example

Look at [these lines](https://github.com/till0xff/cocoapods-skip-modulemap-example/blob/master/Gemfile#L3-L4)

**Comment by dnkoutso** [comment]
@till0xff if a podspec says `false` for a module map does that break consumers of that pod?

**Comment by till0xff** [comment]
@dnkoutso  No, if the pod has no obj-c code. Otherwise, this code will not be available, because the required headers will not be included in the modulemap that is automatically generated by the Swift compiler.

**Comment by dnkoutso** [comment]
@till0xff just to understand this 100% you have multiple legacy objc pods that cocoapods generates a module map for you that your app code includes and causes this issue?

**Comment by till0xff** [comment]
@dnkoutso My local pods do not contain Obj-C code (pure swift). But the main project that uses these pods contains some legacy Obj-C code.
