### ISSUE TITLE
xcode12cocopods errer

### ISSUE THREAD

**Issue by MayDayzll** [CocoaPods/CocoaPods#10233]
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Dictionary+missing+%27%3B%27+after+key-value+pair+for+%22D0B1743F23B0B21900E4A9A4%22%2C+found+%22%22%0A+++++%23++-------------------------------------------%0A+++++%23++%09rootObject+%3D+9A5CE6C81EAE362E00B0A687+%2F%2A+Project+object+%2A%2F%3B%0A+++++%23++%7D%0A11426%3E++%0A++++++++%5E%0A+++++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by faheemfactor** [comment]
i got same issue on apple silicon. any fix?
