### ISSUE TITLE
Add support for xcodeprojects and bundle targets

### ISSUE THREAD

**Issue by diederich** [CocoaPods/CocoaPods#1024]
I haven't found an issue where to this fits in, so I'm creating a new one. Somewhat related issues seem to be #743 and #1011.

As discussed on UIKonf with @alloy, I had the idea that instead of specifying all kinds of build settings in the pod spec files, it would be nice to directly use the (static lib as well as resource) targets from the xcodeproject of a library.

To test if this would somehow work (and as I have no ruby-fu), @tonklon jumped in and did all the prototyping. The result is this branch: https://github.com/diederich/CocoaPods/tree/feature/xcproject-based-pods

There's only one addition to the spec files: 'xcodeproj':
```
Pod::Spec.new do |s|
  s.name         = 'Foo'
  s.version      = '1.0.0'                                                                  
  s.summary      = 'A library that retrieves the current price of your favorite ice cream.'
  s.author       = { 'Tobias Klonk' => 'tobias.klonk@tklonk.net' }                          
  s.source       = { :svn => 'svn+ssh://svn@code.tonklon.com/tonklon/foo' }
  s.xcodeproj    = { project: "foo.xcodeproj", library_target: "foo", resource_target: "bar" }                                    
  s.dependency     'JSONKit', '~> 1.4'
end                             
```

As you can see, the feature branch has come to age, but if this is still useful, please feel free to grab what looks good.

**Comment by Sajjon** [comment]
Hi all! What is the status of this? I have an Xcode project with a lot of build settings, header search paths, compiler flags, macros, architecture (armv7, 64 bit etc) and scripts etc. It is not clear how to "translate" those settings in the xcodeproj file to the podspec file, or if it is even possible? 

So basically I would like to to what @diederich proposed in the top of this issue. Is it possible? :S

**Comment by Sajjon** [comment]
Does [this SO reply](http://stackoverflow.com/a/23118954/1311272) relate to this issue? Is that a way of achieving what I want? :)

**Comment by alloy** [comment]
@Sajjon That is probably the best solution. There are a plethora of problems when using Xcode projects directly, the simplest being that projects won’t build if the configuration names don’t line-up with those in the app project.

**Comment by Sajjon** [comment]
So that means that we are left with only the option of using a static library instead of a dynamic framework?

So @diederich idea was not embraced/included at all in the end?

**Comment by Sajjon** [comment]
@alloy but can I "convert" all my settings in my .xcodeproj file to the podspec? Is there a mapping for every setting in the .xcodeproj file to the podspec file?

**Comment by orta** [comment]
There's probably not a direct mapping for _every_ setting, but you can [include them](https://guides.cocoapods.org/syntax/podspec.html#compiler_flags). Given that we've not had to make any changes outside of module changes to the Podspec syntax in a long time, it's a pretty safe bet that you are covered with the DSL.

If you're providing source, then CocoaPods end-users get to choose whether to have a framework or a static library.

**Comment by segiddins** [comment]
I think we can close this as _wontfix_? @CocoaPods/core

**Comment by neonichu** [comment]
:+1:

**Comment by orta** [comment]
If a well-tested PR comes in with great support for this appears we can definitely re-consider, but from the core team's perspective there are too many downsides, and edge cases to doing this kind of thing ourselves.
