### ISSUE TITLE
pod install fails with ld: library not found for -lz and clang error

### ISSUE THREAD

**Issue by piotrros** [CocoaPods/CocoaPods#10244]
# Report

I'm unable to update RealmSwift framework via cocoa pods. Going any higher than 5.2.0 or just removing the version (so it'll update straight to the latest version) leads to the error described below. This is happening on fresh, hello world SwiftUI project (the same issue is on my real UIKit project so it's not related to SwiftUI). 

I'm using cocoa pods 1.10.0 (latest), I even tried reinstalling it. Any other pod install without any issue. I've also update ruby and openssl to the latest version. I tried rebooting my mac and calling the same method on a different network and result it the same. Removing Podfile.lock and Pods directory don't help either.

## What did you do?

`pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

I've got an error:

```
pod install
Analyzing dependencies
Downloading dependencies
Installing Realm (10.1.4)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

Downloading dependency: sync 10.1.3 from https://static.realm.io/downloads/sync/realm-sync-xcframework-10.1.3.tar.xz
ld: library not found for -lz
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)


[!] Automatically assigning platform `iOS` with version `13.2` on target `swiftuitest` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H2)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - file system
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftuitest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftuitest
  pod 'RealmSwift'

end
```

## Project that demonstrates the issue

[swiftuitest.zip](https://github.com/CocoaPods/CocoaPods/files/5603395/swiftuitest.zip)

**Comment by dnkoutso** [comment]
I will try it myself but so far this looks like an environment issue and not a cocoapods issue. i successfully installed RealmSwift earlier but I might do it again just to verify.

**Comment by piotrros** [comment]
If it doesn't work for fresh project what can I do? Every other pod installs just fine.

**Comment by dnkoutso** [comment]
Something in your environment and the custom prepare command shell script Realm invokes doesn't work. I recommend filing an issue with them and see if they can help you diagnose.

I can successfully install Realm pod in a sample app of mine so at this time this does not seem like a CocoaPods issue.

Happy to re-open it if you can show it is indeed a cocoapods issue with a sample app or additional debugging information.
