### ISSUE TITLE
Code builds successfully a corrupted archive, not showing in organizer, as soon as cocoapods installs react-native-mapbox-gl from Podfile

### ISSUE THREAD

**Issue by byvalentino** [CocoaPods/CocoaPods#10247]
https://stackoverflow.com/questions/64933102/xcode-builds-successfully-a-corrupted-archive-not-showing-in-organizer-as-soon

**Comment by dnkoutso** [comment]
The stackoverflow discussion seems to be leading to a solution. Closing for now.

**Comment by dnkoutso** [comment]
This isnt a valid issue report to begin with.

**Comment by byvalentino** [comment]
I apologize for cutting corners when reporting. The information at the link it's very close to your template, if not exactly the same. However, the manual solution is kind of screaming help from you guys. How can we turn this manual process into an automatic linking by cocoapods?
