### ISSUE TITLE
Unable to install vendored xcframework with 1.10

### ISSUE THREAD

**Issue by dylancom** [CocoaPods/CocoaPods#10257]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I upgraded cocoapods from 1.9.3 to 1.10.0 and ran pod install.

## What did you expect to happen?

That my pods would install normally.

## What happened instead?

`[!] Unable to install vendored xcframework taglib for Pod private-pod, because it contains both static and dynamic frameworks.`

If I downgrade to 1.9.3, the error disappears and everything works fine.

**Comment by jamilAion** [comment]
Any update for it?

**Comment by eebean2** [comment]
Any update, this is still an issue in 1.11.3

**Comment by xuelongqy** [comment]
> Any update, this is still an issue in 1.11.3

I use cocoapods installed by brew and it works
