### ISSUE TITLE
'pod install' with Error

### ISSUE THREAD

**Issue by 673837850** [CocoaPods/CocoaPods#10261]
I used M1 Mac mini.
cocopods installed and when use 'pod install', an error was encountered.
'
https://github.com/CocoaPods/CocoaPods/search?q=dlsym%280x7fbe1d22c9d0%2C+Init_ffi_c%29%3A+symbol+not+found+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.13.1%2Flib%2Fffi_c.bundle&type=Issues
'

**Comment by dnkoutso** [comment]
Please search other issues around workarounds and environment setup regarding the `ffi` gem.
