### ISSUE TITLE
Nexus private repository not able to mirror cdn.cocoapods.org

### ISSUE THREAD

**Issue by lefkatis** [CocoaPods/CocoaPods#10276]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
I have setup a proxy cocoapod repository to proxy cdn.cocoapods.org.
I have replaced "source" in my Podfile to point to my nexus repository like this
`source 'https://[DOMAIN]:8443/repository/ios-cdn-cocoapods/'`
I run pod install to retrieve pods from a private Nexus repository

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Install all pod dependencies correctly and cache everything on my private Nexus repository.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
I get this error:
RuntimeError - Unable to create a source with URL https://[DOMAIN]:8443/repository/ios-cdn-cocoapods/
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:58:in `create_source_with_url'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:19:in `find_or_create_source_with_url'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-art-1.0.4/lib/cocoapods_plugin.rb:101:in `sources'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:985:in `block in resolve_dependencies'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/lefkatis/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/lefkatis/.rbenv/versions/2.7.0/bin/pod:23:in `load'
/Users/lefkatis/.rbenv/versions/2.7.0/bin/pod:23:in `<main>'

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/lefkatis/.rbenv/versions/2.7.0/lib
Repositories : hellenicbank-repository-ios-cdn-cocoapods - file system
               hellenicbank-repository-ios-cdn-cocoapods-1 - file system
               hellenicbank-repository-ios-cdn-cocoapods-2 - file system
               hellenicbank-repository-ios-cdn-cocoapods-3 - file system
               hellenicbank-repository-ios-cdn-cocoapods-4 - file system
               hellenicbank-repository-ios-cdn-cocoapods-5 - file system
               hellenicbank-repository-ios-cdn-cocoapods-6 - file system
```

### Installation Source

```
Executable Path: /Users/lefkatis/.rbenv/versions/2.7.0/bin/pod
```

### Plugins

```
cocoapods-art         : 1.0.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
I have created a new xcode project and the same thing happened.

**Comment by igor-makarov** [comment]
This seems like an issue with either the Nexus mirror or your local HTTP access config. Here are some things to try:  
* `rm -rf ~/.cocoapods/repos/hellenicbank-repository-*` to clean out the local copies that seem broken.
* Look at [this guide](https://help.sonatype.com/repomanager3/formats/cocoapods-repositories) for setting up NXRM with CocoaPods.
* Contact Sonatype for technical support. While CocoaPods has been cooperative with commercial package management services, it's ultimately their proprietary implementation.

I seem to recall some folks that worked on some NXRM adaptation, @igorudovika ? @jlstephens89 ?

**Comment by lefkatis** [comment]
Hello

Thanks for reaching out.
I have tried what you said. 
I also followed that guide before posting here and I have also contacted Sonatype. After exchanging numerous emails they ended up referring me here :)

**Comment by lefkatis** [comment]
I solved it by uninstalling plugin "cocoapods-art".

**Comment by igorudovika** [comment]
Hello,
Sorry for late response. Yep, we also faced with compatibility problem between "cocoapods-art" plugin and with "CDN approach" to fetch any dependencies.
