### ISSUE TITLE
Question: Any reason why Info.plist for dependencies cannot be generated?

### ISSUE THREAD

**Issue by sanyesz123** [CocoaPods/CocoaPods#10272]
# Report

## What did you do?

I have a simple **Podfile** for my project, and I would like to link the dependencies dynamically to my project, so I added `use_frameworks!` to the **Podfile**. If I run a `pod install` from terminal, the **Info.plist** files for the dependencies are generated under the **Target Support Files/dependency**. If I run a `pod install`, on the same machine with the **same** configuration, using **Jenkins**, the **Info.plist** files for the dependencies are not generated. 

## What did you expect to happen?

I expected that the `pod install` will generate all the necessary **Info.plist** files under the mentioned directory, as I run the `pod install` from terminal.

## What happened instead?

The **Info.plist** files are not generated, even if I run a `pod install --verbose` the lines with `- Generating Info.plist file at` message are missing. Modulemap, xcconfig, dummy, prefix, umbrella files are generated.

Any ideas?

**Comment by sanyesz123** [comment]
Okay... if `INFOPLIST_FILE` environment variable is set, the **Info.plist** files are not generated. So the solution is simple,  I needed just to remove the environment variable. But why ? :)

**Comment by dnkoutso** [comment]
If CocoaPods sees this is already set it avoids making one as it will be unused.

**Comment by sanyesz123** [comment]
I did not find this in the documentation, and I think it should be part of it. It's a very hidden information. The ticket can be closed from my side.
