### ISSUE TITLE
Different Linkage per Configuration possible?

### ISSUE THREAD

**Issue by winkelsdorf** [CocoaPods/CocoaPods#10289]
Hello,

I'm wondering if there's a way to link differently depending on the build configuration.

Currently SwiftUI Previews do not work for static libraries or frameworks, so they require dynamic frameworks while improved launch performance and fonts used from framework resources require static linking (as framework or library).

So I'm in a situation where I'd prefer linking dynamically during development (in debug configurations) and statically for releases.

Tried everything I'm aware of (from multiple targets to deduplication settings). Sooner or later these attempts fail, as the same pods are referenced.

The only way I see is having two completely separate projects and/or workspaces. Opinions or ideas? Am I missing out something?

Cheers
Frederik

**Comment by dnkoutso** [comment]
I do not think this is supported out of the box. You might need an ENV variable in your `Podfile` to drive that under the `use_frameworks!` DSL and each time you switch to run `pod install`...

**Comment by winkelsdorf** [comment]
@dnkoutso Yes, that's another way. Honestly I wanted to avoid that due to overhead in my workflow (we do a check-in of the Pods, comparing them on the Pipeline with freshly generated pod install - that would require always switching to static before all PRs).

What made me thought this might work, was this Issue (and it's merged PR): https://github.com/CocoaPods/CocoaPods/issues/9099

The example you gave was:
```ruby
  pod 'AFNetworking', '~> 1.0'

  target 'MyApp' do
    use_frameworks!
  end

  target 'MyApp2' do
    use_frameworks! :linkage => :dynamic
  end

  target 'MyApp3' do
    use_frameworks! :linkage => :static
  end
```

From my understanding that would have meant that AFNetworking is linked into all targets, two times dynamically and one time statically. Multiple targets would be fine - so looked exactly like what I wanted to do 😅

**Comment by winkelsdorf** [comment]
@dnkoutso Verified the above example to be working with remote Pods (here Alamofire).

As soon as I start using a private Pod, I get:
```shell
Analyzing dependencies
Downloading dependencies
Installing CustomPod (1.0.0)
[!] The 'Pods-SwiftUIPreviews' target has transitive dependencies that include statically linked binaries: (CustomPod-static)
```

So PR https://github.com/CocoaPods/CocoaPods/pull/9119 closes this for everything but private pods. Any Idea where to have a look how to fix that?
