### ISSUE TITLE
Build issue with Xcode 12.3 - file not found #include "ruby/config.h"

### ISSUE THREAD

**Issue by oransel** [CocoaPods/CocoaPods#10286]
Trying to install without using sudo with the following command.

`gem install --user-install cocoapods`

I saw a lot of errors and comments reported with Ruby on macOS with the same issue. Error generated is:

`package configuration for libffi is not found
"xcrun clang -o conftest -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/lib   -arch x86_64   -lruby.2.6   "
In file included from conftest.c:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
#include "ruby/config.h"
         ^~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: note: did not find header 'config.h' in framework 'ruby' (loaded from '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks')
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */`

I found that the build command used is:

`xcrun clang -o conftest \
    -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19 \
    -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward \
    -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 \
    -I. \
    -D_XOPEN_SOURCE \
    -D_DARWIN_C_SOURCE \
    -D_DARWIN_UNLIMITED_SELECT \
    -D_REENTRANT    \
    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS conftest.c  \
    -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib \
    -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/lib   \
    -arch x86_64 \
    -lruby.2.6`

But, it needs to be

`xcrun clang -o conftest \
    -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20 \
    -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward \
    -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 \
    -I. \
    -D_XOPEN_SOURCE \
    -D_DARWIN_C_SOURCE \
    -D_DARWIN_UNLIMITED_SELECT \
    -D_REENTRANT    \
    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS conftest.c  \
    -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib \
    -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib   \
    -arch x86_64 \
    -lruby.2.6`

Notice the following changes:

Instead of universal-darwin19, it is universal-darwin20
Instead of MacOSX10.15.Internal.sdk, it is MacOSX.sdk

**Comment by oransel** [comment]
Seems to be an issue with macOS 10.15 and Xcode 12. 
Combination of macOS 10.15 and Xcode 11 works fine.

**Comment by wangjiajiajohn** [comment]
> Seems to be an issue with macOS 10.15 and Xcode 12.
> Combination of macOS 10.15 and Xcode 11 works fine.

I just update rurby version to 2.7.2, resolve the problem

**Comment by faraz-ahmad** [comment]
@wangjiajiajohn -  How did you update the ruby? Can you please provide me the steps. I am stuck in this issue from 2 days. Thank you.

**Comment by oransel** [comment]
> > Seems to be an issue with macOS 10.15 and Xcode 12.
> > Combination of macOS 10.15 and Xcode 11 works fine.
> 
> I just update rurby version to 2.7.2, resolve the problem

I didn't want to use brew or ports, so I had to downgrade Xcode to make it work.

**Comment by tsuyoi** [comment]
> > > Seems to be an issue with macOS 10.15 and Xcode 12.
> > > Combination of macOS 10.15 and Xcode 11 works fine.
> > 
> > 
> > I just update rurby version to 2.7.2, resolve the problem
> 
> I didn't want to use brew or ports, so I had to downgrade Xcode to make it work.

Can confirm Command Line Tools 11.5 works on Catalina (10.15). 

For those unfamiliar with changing/downgrading Command Line Tools:
- Download Command Line Tools 11.5 from [Apple Developer Downloads](https://developer.apple.com/download/more/?=xcode)
- `sudo rm -rf /Library/Developer/CommandLineTools`
- Install Command Line Tools from .dmg/.pkg
- `sudo xcode-select --switch /Library/Developer/CommandLineTools`
- `[sudo] gem install [--user-install] cocoapods`
- `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`

**Comment by dnkoutso** [comment]
This issue does not appear related to CocoaPod per se though right? It seems an environment issue?

**Comment by oransel** [comment]
> This issue does not appear related to CocoaPod per se though right? It seems an environment issue?

I am concluding from my experience that it is not CocoaPods issue.

**Comment by acecilia** [comment]
I just updated to Xcode 12.3 and I am hitting this issue. This solved it for me:

```
cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0
cp universal-darwin20 universal-darwin19
```

**Comment by robertschmid23** [comment]
> I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> 
> `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19`

I just did a clean install of Catalina and the path above did not exist.  The path I found it under is;

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0

The second part - 

ln -s universal-darwin20 universal-darwin19

worked for me once I found the right directory.

**Comment by lulzimfazlija** [comment]
I am having same problem with catalina 10.15.7, ruby 2.6.3p62!

Error:
did not find header 'config.h' in framework 'ruby' (loaded from '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks')
1 error generated.

**Comment by faraz-ahmad** [comment]
Just update ruby to 2.7 and it will get resolved.

**Comment by zhangmazi** [comment]
> Just update ruby to 2.7 and it will get resolved.

how to upgrade ruby to 2.7...i had try too hard

**Comment by faraz-ahmad** [comment]
https://rayhightower.com/blog/2013/05/16/upgrading-ruby-with-rvm/

Here is the instructions to update Ruby

**Comment by zhangmazi** [comment]
> https://rayhightower.com/blog/2013/05/16/upgrading-ruby-with-rvm/
> 
> Here is the instructions to update Ruby

but it is not for ruby-2.7 by rvm... because it tips "no binary rubies available 2.7.2"

**Comment by aboutmydreams** [comment]
I find someone meet same problem
https://ernestojeh.com/fix-jekyll-on-macos-big-sur

**Comment by aboutmydreams** [comment]
I solve it by:
"rvm use ruby-3.0"

https://www.jianshu.com/p/9c9f8d4867eb
> > https://rayhightower.com/blog/2013/05/16/upgrading-ruby-with-rvm/
> > Here is the instructions to update Ruby
> 
> but it is not for ruby-2.7 by rvm... because it tips "no binary rubies available 2.7.2"

**Comment by jinthislife** [comment]
> Can confirm Command Line Tools 11.5 works on Catalina (10.15).
> 
> For those unfamiliar with changing/downgrading Command Line Tools:
> 
> * Download Command Line Tools 11.5 from [Apple Developer Downloads](https://developer.apple.com/download/more/?=xcode)
> * `sudo rm -rf /Library/Developer/CommandLineTools`
> * Install Command Line Tools from .dmg/.pkg
> * `sudo xcode-select --switch /Library/Developer/CommandLineTools`
> * `[sudo] gem install [--user-install] cocoapods`
> * `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`




I ran into this issue while installing fastlane today.
I'm using MacOS 10.15.7.
Downgrading to Command Line Tools for Xcode 11.5 resolved my issue.

> * Download Command Line Tools 11.5 from [Apple Developer Downloads](https://developer.apple.com/download/more/?=xcode)
> * `sudo rm -rf /Library/Developer/CommandLineTools`
> * Install Command Line Tools from .dmg/.pkg
> * `sudo xcode-select --switch /Library/Developer/CommandLineTools`

and trying to installing fastlane works perfect. Thanks!

**Comment by NBroomfield** [comment]
Anyone else with this issue, this is what worked for me:

1) curl -sSL https://get.rvm.io | bash -s stable
2) **close and reopen terminal**
3) rvm install ruby@latest
4) rvm use ruby-3.0.0 --default

**Comment by qozia3** [comment]
> Anyone else with this issue, this is what worked for me:
> 
> 1. curl -sSL https://get.rvm.io | bash -s stable
> 2. **close and reopen terminal**
> 3. rvm install ruby@latest
> 4. rvm use ruby-3.0.0 --default

Thank you!!
this worked for me

**Comment by stefanlasiewski** [comment]
> Just update ruby to 2.7 and it will get resolved.

This doesn't work for folks who use the Mac's default version of Ruby.  It's a bad idea to replace Mac's system utilities-- instead, users would be better off installing Ruby from Homebrew or another source.

**Comment by acecilia** [comment]
Solutions depending on your setup:
* If you use the system ruby: https://github.com/CocoaPods/CocoaPods/issues/10286#issuecomment-750403566
* If you use rbenv or other ruby manager that is not the system ruby: https://github.com/CocoaPods/CocoaPods/issues/10286#issuecomment-752692835

**Comment by zhangferry** [comment]
> Anyone else with this issue, this is what worked for me:
> 
> 1. curl -sSL https://get.rvm.io | bash -s stable
> 2. **close and reopen terminal**
> 3. rvm install ruby@latest
> 4. rvm use ruby-3.0.0 --default

ruby-2.7.2 will also work. So maybe ruby-2.6.0 cause the problem.

**Comment by FFGuerrero** [comment]
> Can confirm Command Line Tools 11.5 works on Catalina (10.15).
> 
> For those unfamiliar with changing/downgrading Command Line Tools:
> 
> * Download Command Line Tools 11.5 from [Apple Developer Downloads](https://developer.apple.com/download/more/?=xcode)
> * `sudo rm -rf /Library/Developer/CommandLineTools`
> * Install Command Line Tools from .dmg/.pkg
> * `sudo xcode-select --switch /Library/Developer/CommandLineTools`
> * `[sudo] gem install [--user-install] cocoapods`
> * `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer`

Thank you!! This worked for me

**Comment by QiuDaniel** [comment]
> I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> 
> `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19`
 
Thanks!!!! This worked for me

**Comment by hiddenfloret** [comment]
> I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> 
> `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19 `

Even with sudo I get the following 'ln: universal-darwin19: Permission denied'.

**Comment by hiddenfloret** [comment]
Fixed it by running this instead at path: `sudo ln -sf universal-darwin20 universal-darwin19`

**Comment by hiddenfloret** [comment]
> > I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> > `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19 `
> 
> Even with sudo I get the following 'ln: universal-darwin19: Permission denied'. How can I fix this?

Fixed it by running with sudo and the -f option instead at path: sudo ln -sf universal-darwin20 universal-darwin19

**Comment by TheKeyKim** [comment]
> > Seems to be an issue with macOS 10.15 and Xcode 12.
> > Combination of macOS 10.15 and Xcode 11 works fine.
> 
> I just update rurby version to 2.7.2, resolve the problem

Oh,.. you save me.. very thks.......!!!!!!

**Comment by AlonsoAGlobant** [comment]
> > > I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> > > `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19 `
> > 
> > 
> > Even with sudo I get the following 'ln: universal-darwin19: Permission denied'. How can I fix this?
> 
> Fixed it by running with sudo and the -f option instead at path: sudo ln -sf universal-darwin20 universal-darwin19

This solved the issue for me.

**Comment by mrmillmill** [comment]
> Trying to install without using sudo with the following command.
> 
> `gem install --user-install cocoapods`
> 
> I saw a lot of errors and comments reported with Ruby on macOS with the same issue. Error generated is:
> 
> `package configuration for libffi is not found "xcrun clang -o conftest -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS conftest.c -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/lib -arch x86_64 -lruby.2.6 " In file included from conftest.c:1: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby.h:33: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found #include "ruby/config.h" ^~~~~~~~~~~~~~~ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:24:10: note: did not find header 'config.h' in framework 'ruby' (loaded from '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks') 1 error generated. checked program was: /* begin */ 1: #include "ruby.h" 2: 3: int main(int argc, char **argv) 4: { 5: return 0; 6: } /* end */`
> 
> I found that the build command used is:
> 
> `xcrun clang -o conftest \ -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19 \ -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward \ -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 \ -I. \ -D_XOPEN_SOURCE \ -D_DARWIN_C_SOURCE \ -D_DARWIN_UNLIMITED_SELECT \ -D_REENTRANT \ -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS conftest.c \ -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib \ -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/lib \ -arch x86_64 \ -lruby.2.6`
> 
> But, it needs to be
> 
> `xcrun clang -o conftest \ -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20 \ -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward \ -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 \ -I. \ -D_XOPEN_SOURCE \ -D_DARWIN_C_SOURCE \ -D_DARWIN_UNLIMITED_SELECT \ -D_REENTRANT \ -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS conftest.c \ -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib \ -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib \ -arch x86_64 \ -lruby.2.6`
> 
> Notice the following changes:
> 
> Instead of universal-darwin19, it is universal-darwin20
> Instead of MacOSX10.15.Internal.sdk, it is MacOSX.sdk

Hey Oransel, running gem install --user-install cocoapods like you suggested worked for me! I am on Mac Big Sur 11.2.1, Xcode 12.4

**Comment by xuzhaocheng** [comment]
> I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> 
> `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19 `

Thanks!!! This works for me!!

**Comment by sampart** [comment]
Here are some slightly more detailed instructions that worked for me with `rbenv`:

1. Install rbenv
2. Install a newer Ruby (I went for 2.7.3): `rbenv install 2.7.3`
3. Switch to that one globally: `rbenv global 2.7.3` (don't worry about doing it globally, you can always switch back to `system` later, or can use `rbenv local` later for individual folders)
4. Install rails `sudo gem install rails`
5. Rebuild rbenv's shims: `rbenv rehash`
6. `rails new ...` should now work.

If you still have trouble on point (6), try running the shim version directly - `rvm shims` will tell you where it is.

Hope this helps.

**Comment by iskalinov13** [comment]
> > Anyone else with this issue, this is what worked for me:
> > 
> > 1. curl -sSL https://get.rvm.io | bash -s stable
> > 2. **close and reopen terminal**
> > 3. rvm install ruby@latest
> > 4. rvm use ruby-3.0.0 --default
> 
> ruby-2.7.2 will also work. So maybe ruby-2.6.0 cause the problem.

Thanks 😍 This works for me !!! ❤️

**Comment by gaoliang-dl** [comment]
I find this by Xcode.
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
sudo gem install -n /usr/local/bin cocoapode

**Comment by yujianyuanhaha** [comment]
> I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> 
> `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19 `

this work for me, thanks

**Comment by ethanneff** [comment]
> Anyone else with this issue, this is what worked for me:
> 
> 1. curl -sSL https://get.rvm.io | bash -s stable
> 2. **close and reopen terminal**
> 3. rvm install ruby@latest
> 4. rvm use ruby-3.0.0 --default

thank you!

**Comment by Spiderpowa** [comment]
Update if you're using Xcode 13.1

```
cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin21 universal-darwin20
```

**Comment by grahamlyons** [comment]
I had a similar issue (but installing `json`) with missing `config.h`. I'm using stock system Ruby and didn't want to deviate into `brew` installed dependencies. I found the `config.h` file in a different folder so I copied it into the path that was expected and the install worked.

`sudo cp /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/Headers/ruby/config.h /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/`

**Comment by JinleeJeong** [comment]
> Anyone else with this issue, this is what worked for me:
> 
> 1. curl -sSL https://get.rvm.io | bash -s stable
> 2. **close and reopen terminal**
> 3. rvm install ruby@latest
> 4. rvm use ruby-3.0.0 --default

You save my time :) Thank you so much!

**Comment by authosoro** [comment]
> > Trying to install without using sudo with the following command.
> > `gem install --user-install cocoapods`
> 
> Hey Oransel, running gem install --user-install cocoapods like you suggested worked for me! I am on Mac Big Sur 11.2.1, Xcode 12.4, ruby 2.6.3p62,

This worked for me, same OS, Xcode & ruby version

**Comment by zbqlalala** [comment]
> I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> 
> `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19 `

cool! works for me. set this and reopen the terminal. thx!

**Comment by kazuiains** [comment]
> I just updated to Xcode 12.3 and I am hitting this issue. Seems like Xcode 12.3 broke the system ruby installation. This solved it for me:
> 
> `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin20 universal-darwin19 `

THANKS!! you saved me. I've been looking all day for ways to fix it.

**Comment by lwouis** [comment]
I fixed the issue with a variation of https://github.com/CocoaPods/CocoaPods/issues/10286#issuecomment-972475697:

```
cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && ln -s universal-darwin21 universal-darwin22
```

**Comment by eugeniobaglieri** [comment]
This is the variation of https://github.com/CocoaPods/CocoaPods/issues/10286#issuecomment-972475697 for MacOS Ventura

`cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && sudo ln -s universal-darwin21 universal-darwin22`

**Comment by beezital** [comment]
Running Xcode 14.2 on Monterey (12.6.2) I had to create a "downgrade" link

`cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 && sudo ln -s universal-darwin22 universal-darwin21`

**Comment by grigorye** [comment]
Just in case, it looks like it's possible to use stock Ruby, without messing up with symlinks, provided that macOS command line tools package is installed on the host. The thing is that command line tools package bundles SDKs for most recent versions of macOS, and most notably, the one matching the host. Then it's just a matter of overriding SDKROOT in the environment, to point all the low-level tools like clang to the custom root matching the correct version of SDK.

One can install command line tools with something like `xcode-select --install`.

As an example, in the context of the original report, it's worth trying something like this:

```
macos_major_vers=$(sw_vers -productVersion | sed 's/^\([^.]*\)\..*$/\1/') # e.g. 12
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX"$macos_major_vers".sdk

env SDKROOT="$SDKROOT" gem install --user-install cocoapods
```

**Comment by kosbar** [comment]
Update from ruby 2.6.10p210 (2022-04-12 revision 67958) to ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-darwin22] helps me)
