### ISSUE TITLE
Error on M1 Mac

### ISSUE THREAD

**Issue by designexe** [CocoaPods/CocoaPods#10287]
* [ x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.0.1 (20B29)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories :
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '13.0'

target 'Flash Chat iOS13' do
  use_frameworks!

  # Pods for Flash Chat iOS13
  pod 'TextFieldEffects'
end
```

### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle - /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:414:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

Roesta2
rch -x86_64 sudo gem install cocoapods -n /usr/local/bin
sudo gem install ffi     

platform :ios, '13.0'

target 'Flash Chat iOS13' do
  use_frameworks!

  # Pods for Flash Chat iOS13
  pod 'TextFieldEffects'
end

**Comment by Jfmetcalf5** [comment]
I have the same thing happening to me.. please help

**Comment by brucedaniel** [comment]
I'm seeing the same thing, blocking Firebase install

**Comment by designexe** [comment]
This works for me 👍 
1. Duplicate the Terminal application in the Utilities folder.
2. Right click on the app and choose Get Info.
3. Rename the other version of the app as you like.
4. Check the option "open with Rosetta".
5. Install Cocoapods with the command "sudo gem install cocoapods"
6. Type the command line "sudo gem install ffi" to fix the ffi bundle problem. Now you can do a "pod install" without problem.

**Comment by keanconsolacion** [comment]
This seems to be the exact solution.
Also, don't forget to relaunch the terminal completely by quitting it. 

> This works for me 👍
> 
> 1. Duplicate the Terminal application in the Utilities folder.
> 2. Right click on the app and choose Get Info.
> 3. Rename the other version of the app as you like.
> 4. Check the option "open with Rosetta".
> 5. Install Cocoapods with the command "sudo gem install cocoapods"
> 6. Type the command line "sudo gem install ffi" to fix the ffi bundle problem. Now you can do a "pod install" without problem.

**Comment by dnkoutso** [comment]
Trying to consolidate issues regarding this https://github.com/CocoaPods/CocoaPods/issues/9907

Closing as dup. There are 10s if not 100s of reports around ffi gem with various solutions.

**Comment by mehransahandi** [comment]
> This worked for me:
> [#10220 (comment)](https://github.com/CocoaPods/CocoaPods/issues/10220#issuecomment-730963835)



> This worked for me:
> [#10220 (comment)](https://github.com/CocoaPods/CocoaPods/issues/10220#issuecomment-730963835)

**Comment by hjKangIB** [comment]
if you use m1 apple chipset macbook
you might should use this instead of above comment
`sudo arch -x86_64 gem install ffi`
`arch -x86_64 pod install`

> This works for me 👍
> 
> 1. Duplicate the Terminal application in the Utilities folder.
> 2. Right click on the app and choose Get Info.
> 3. Rename the other version of the app as you like.
> 4. Check the option "open with Rosetta".
> 5. Install Cocoapods with the command "sudo gem install cocoapods"
> 6. Type the command line "sudo gem install ffi" to fix the ffi bundle problem. Now you can do a "pod install" without problem.

**Comment by codler** [comment]
After `sudo gem install cocoapods` Im getting this error when running `pod install`
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': 
dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle, 0x0009): 
could not use '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle' because it is not a compatible arch - 
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle (LoadError)

**Comment by samirmaikap** [comment]
if you're running on M1 Mac, and your terminal is set to Rosetta, run this command `sudo arch -arm64 gem pristine ffi`

**Comment by lawrencejews** [comment]
followed all m1 guidelines but now am getting Yoga error

**Comment by lawrencejews** [comment]
<img width="1440" alt="Screen Shot 2021-12-17 at 2 55 08 PM" src="https://user-images.githubusercontent.com/69748354/146522395-b1277f12-ce5f-408e-91f7-ffc217498390.png">

**Comment by Fareed-Ahmad7** [comment]
this worked for me https://github.com/CocoaPods/CocoaPods/issues/10220#issuecomment-730963835

**Comment by dineybomfim** [comment]
> In my case, If you use m1 apple chipset macbook like me you might should use this instead of above comment
> 
> `sudo arch -x86_64 gem install ffi` `arch -x86_64 pod install`
> 
> > This works for me 👍
> > 
> > 1. Duplicate the Terminal application in the Utilities folder.
> > 2. Right click on the app and choose Get Info.
> > 3. Rename the other version of the app as you like.
> > 4. Check the option "open with Rosetta".
> > 5. Install Cocoapods with the command "sudo gem install cocoapods"
> > 6. Type the command line "sudo gem install ffi" to fix the ffi bundle problem. Now you can do a "pod install" without problem.

This right here, ladies and gentleman, is the real deal!!!!

`sudo arch -x86_64 gem install ffi` is the ultimate TRICK!!!! After days and days!!! Finally I found this answer above! Thanks God!

**Comment by dmryan711** [comment]
> if you're running on M1 Mac, and your terminal is set to Rosetta, run this command `sudo arch -arm64 gem pristine ffi` and `pod install`

This worked for me, thank you

**Comment by bukunmialuko** [comment]
1. Cd into ios folder
2. run in terminal(Ios folder as root): arch -x86_64 pod install

**Comment by rubywai** [comment]
> This works for me 👍
> 
> 1. Duplicate the Terminal application in the Utilities folder.
> 2. Right click on the app and choose Get Info.
> 3. Rename the other version of the app as you like.
> 4. Check the option "open with Rosetta".
> 5. Install Cocoapods with the command "sudo gem install cocoapods"
> 6. Type the command line "sudo gem install ffi" to fix the ffi bundle problem. Now you can do a "pod install" without problem.

Very helpful

**Comment by okerivy** [comment]
**Flutter** 

```
sudo gem uninstall ffi && sudo gem install ffi -- --enable-libffi-alloc
pod install
```

**Comment by paulocoutinhox** [comment]
I get the same error on every commands posted here:

```
sudo gem uninstall ffi && sudo gem install ffi -- --enable-libffi-alloc
Gem 'ffi' is not installed
Building native extensions with: '--enable-libffi-alloc'
This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20230105-45488-65bn05.rb extconf.rb --enable-libffi-alloc
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:546:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:543:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:672:in `try_ldflags'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1832:in `pkg_config'
	from extconf.rb:9:in `system_libffi_usable?'
	from extconf.rb:42:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-21/2.6.0/ffi-1.15.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-21/2.6.0/ffi-1.15.5/gem_make.out
```

**Comment by spsaucier** [comment]
`npx pod install` worked where Rosetta did not.

**Comment by pwhsueh** [comment]
> In my case, If you use m1 apple chipset macbook like me you might should use this instead of above comment
> 
> `sudo arch -x86_64 gem install ffi` `arch -x86_64 pod install`
> 
> > This works for me 👍
> > 
> > 1. Duplicate the Terminal application in the Utilities folder.
> > 2. Right click on the app and choose Get Info.
> > 3. Rename the other version of the app as you like.
> > 4. Check the option "open with Rosetta".
> > 5. Install Cocoapods with the command "sudo gem install cocoapods"
> > 6. Type the command line "sudo gem install ffi" to fix the ffi bundle problem. Now you can do a "pod install" without problem.

it works for me, thanks a lot

**Comment by fermellone** [comment]
> This works for me 👍
> 
> 1. Duplicate the Terminal application in the Utilities folder.
> 2. Right click on the app and choose Get Info.
> 3. Rename the other version of the app as you like.
> 4. Check the option "open with Rosetta".
> 5. Install Cocoapods with the command "sudo gem install cocoapods"
> 6. Type the command line "sudo gem install ffi" to fix the ffi bundle problem. Now you can do a "pod install" without problem.

For those who are trying to run the app with vscode, you only need to execute "arch -x86_64 sudo gem install ffi" with the vscode terminal.

**Comment by liuyongjiesail** [comment]
M1 Mac use "arch -arm64 pod install" in Jenkins Pipeline.

**Comment by RiffatIslam** [comment]
> This works for me 👍
> 
> 1. Duplicate the Terminal application in the Utilities folder.
> 2. Right click on the app and choose Get Info.
> 3. Rename the other version of the app as you like.
> 4. Check the option "open with Rosetta".
> 5. Install Cocoapods with the command "sudo gem install cocoapods"
> 6. Type the command line "sudo gem install ffi" to fix the ffi bundle problem. Now you can do a "pod install" without problem.

Thanks, Worked for me
