### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by artemumanets** [CocoaPods/CocoaPods#10298]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
While generating archiving build, the following error occurs. Running the app on the simulator or device, everything works fine. Previously there were no error with Xcode 11 and iOS 13.*.

## What did you do?

Archiving app in XCode 12.0 or 12.3 gives the following error:
```
mkdir -p /Users/artemumanets/Library/Developer/Xcode/DerivedData/App-fuhwlkmrhjyszfaeoepbbjmjjzzi/Build/Intermediates.noindex/ArchiveIntermediates/App Staging/BuildProductsPath/Release (Staging)-iphoneos/App Staging.app/Frameworks
Symlinked...
Command PhaseScriptExecution failed with a nonzero exit code
```

## What did you expect to happen?
While archiving, it is supposed to work with out errors.

## What happened instead?
An error is occurring while building the app, from Xcode or fastlane.

## CocoaPods Environment
```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ f523a889245860ba8c441a3373f73073b550a22a
```

**Comment by dnkoutso** [comment]
Please upload a sample app demonstrating the issue with minimal cocoapods reproducible steps.

**Comment by artemumanets** [comment]
It is a huge project that belongs to a company where I work. If I create a smaller demo, probably everything will work as expected.

If you are not able to help me without a project and if possible, can you guide me to understand if the last line (before command exit) "Symlinked..." is executed or not, or it is the one that is breaking the script.
If that is not the case, what is next cocoapods internal script or step is executed after the Symlinking?

**Comment by dnkoutso** [comment]
@artemumanets its coming from this https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/embed_frameworks_script.rb#L85

**Comment by artemumanets** [comment]
@dnkoutso thank you, I will check if it helps me.

**Comment by dnkoutso** [comment]
If you do figure it out and you believe its a bug in cocoapods that can handle something better lets make a PR!

**Comment by artemumanets** [comment]
Ok, I'm still researching, couldn't figure it out yet.

**Comment by artemumanets** [comment]
The following line is failing in the script that you have shared:
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/embed_frameworks_script.rb#L86
```source="$(readlink "${source}")"```

Do you now what can cause this?

**Comment by artemumanets** [comment]
I wasn't able to find the reason for this error to occur. 
I've tried to comment the line of code in my Pods-AppName-framework.sh that was causing the app to crash, and the build has succeeded, I've tested the app and everything looks ok.

I'm not sure where is the root of the problem, but this has at least temporarily solved the issue.
So for now I added the following Build Phase Script, just before [CP] Embed Pods Frameworks

**Comment by dnkoutso** [comment]
@artemumanets it looks like you have a symlink somewhere in the framework and cocoapods is meant to take care of that but it doesnt.

**Comment by thomaswinkler** [comment]
@artemumanets, ran into the same issue and needed to fix the readlink implementation in the script. Please note, there is a readlink() wrapper function that causes the error.

```bash
6 old_read_link=`which readlink`
7 readlink () {
8    path=`$old_read_link "$1"`;
9 ...
```
For some paths it is required to wrap $1 in quotes. For me it did contain spaces.

**Comment by rogerluan** [comment]
@artemumanets 's solution worked well for me. I'm seeing this issue when precompiling pods using https://github.com/leavez/cocoapods-binary - and looks like there're more folks facing this same issue when precompiling using other tools as you can see above ☝️ 

May be an issue the precompile tools, but for the time being idk how to fix them other than using this dirty workaround. I have no idea why deleting the `source="$(readlink "${source}")"` works 😬 but it does - I tested building, archiving, exporting and uploading to the App Store and validating against Apple's servers, and launching and playing around with the app in TestFlight. So, so far this solution's 💯

**Comment by thomaswinkler** [comment]
@rogerluan, I also found it to be a problem of cocoapods-binary. This problem is actually coming from the readlink() wrapper implementation cocoapods-binary is adding. This cocoapods-binary readlink() implementation does not correctly escape the path. My project name did contain spaces resulting in failing readlink calls. I did fix it using the updated version of @artemumanets script. Probably better than just removing it as it would miss some of the symlinks in your package.

```bash
SRC_STR='    path=`$old_read_link $1`;'
DST_STR='    path=`$old_read_link "$1"`;'

sed -i -e "s/${SRC_STR}/${DST_STR}/g" "${PODS_ROOT}/Target Support Files/Pods-AppName/Pods-AppName-frameworks.sh"
echo "Done fixing Pods-AppName-frameworks.sh"
```

**Comment by rogerluan** [comment]
@thomaswinkler that is amazing! Yes, this is a lot better, and also comforts me knowing the root cause of the issue 🤗 
I have tested your solution and it works great!

Also, worth noting that there has already been a fix to cocopods-binary, opened in Dec 2019 and merged in Sep 2020 (😢 ), but still unreleased 😭 https://github.com/leavez/cocoapods-binary/pull/107

As cocoapods-binary-cache was built on top of cocoapods-binary, it faced it same issue. I just opened a PR to fix it there too: https://github.com/grab/cocoapods-binary-cache/pull/67

**Comment by hkodes** [comment]
Easy way to Fix this:

1.Go to Menu System Preferences -> Security & Privacy.
2.Choose the Privacy Tab.
3.Select Full Disk Access item in left list.
4.Select Xcode in right list.

**Comment by firattamur** [comment]
@hkodes thanks a lot, your solution worked for me.

**Comment by domeOo** [comment]
@hkodes still working thank you <3

**Comment by gitgobrr** [comment]
For me this small adjustment helped:
Go to ${PODS_ROOT}"/Target Support Files/Pods-AppName/Pods-AppName-frameworks.sh"
Line 42 in my file: 
```
  if [ -L "${source}" ]; then
    echo "Symlinked..."
    source="$(readlink -f "${source}")" # add "-f" option to the readlink command
  fi
```

**Comment by Ahsanwarsi** [comment]
I encountered the same issue. Here's what worked for me;
I added the following in the Podfile post_install section:

```
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
      end
    end
```

Then, I ran the `pod deintegrate` command followed by `pod install`.
