### ISSUE TITLE
Resource file in cocoapod is set to a wrong target

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [CocoaPods/CocoaPods#10296]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I asked this [question](https://stackoverflow.com/q/65324092/1077789) on StackOverflow about 5 days ago but didn't receive any response so I'm re-posting it here.

I have a public CocoaPod called [CountrySelectorView](https://cocoapods.org/pods/CountrySelectorView). It's basically a small library that allows users to select countries from a list. This list of countries is included as a json file in the pod.

I released the first version (v0.1.0) a few months ago and it worked well without an issue. Today I added some new changes to the codebase and released a new version (v0.1.2).

When I install this new version now, the _countries.json_ file is assigned a weird target.

![hk5OT](https://user-images.githubusercontent.com/2551877/102744980-19f10480-4381-11eb-980b-3a186b5263f2.png)

And this affects only that json file. All other files are set to the proper target.

![fXV9c](https://user-images.githubusercontent.com/2551877/102745008-29704d80-4381-11eb-8f63-ab2641814448.png)

This is my `podspec` file. The only thing I changed here was the version string before publishing the new version. No changes were done to the _countries.json_ file either apart from some minor content changes.

```ruby
Pod::Spec.new do |s|
  s.name             = 'CountrySelectorView'
  s.version          = '0.1.2'
  s.summary          = 'CountrySelectorView lets users pick a country from a list.'

  s.description      = <<-DESC
                        CountrySelectorView lets users pick a country. You can show it either as a list where you can search or a picker view.
                       DESC

  s.homepage         = 'https://github.com/Isuru-Nanayakkara/CountrySelectorView'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Isuru-Nanayakkara' => '<my_email>' }
  s.source           = { :git => 'https://github.com/Isuru-Nanayakkara/CountrySelectorView.git', :tag => s.version.to_s }

  s.ios.deployment_target = '11.0'

  s.source_files = 'CountrySelectorView/Classes/**/*'
  
  s.resource_bundles = {
      'CountrySelectorView' => ['CountrySelectorView/Assets/countries.json']
  }

  s.frameworks = 'UIKit'
  s.swift_version = '5.0'
end
```

Strange thing is when I install the old version (v0.1.0) now, this problem arises in that version as well! Prior to today, it worked fine.

Any idea what may have caused this?

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.0.1 (20B50)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ cc89cb22a07cfac4f9134d8ee462c618b74c1f6a

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

[Demo project](https://www.dropbox.com/s/zpnx61w2kzxldv1/countrydemo.zip?dl=0)

**Comment by dnkoutso** [comment]
<img width="1512" alt="Screen_Shot_2020-12-28_at_1_52_44_PM" src="https://user-images.githubusercontent.com/310370/103242599-02cb8d00-4914-11eb-9536-164b4c23251b.png">

not sure...this one looks like its working correctly.

Can you try to get some reproducible steps perhaps? Maybe you had a bad glob in `s.source_files` that catches that JSON file?
