### ISSUE TITLE
can not clone this resource

### ISSUE THREAD

**Issue by ztkgithub** [CocoaPods/CocoaPods#10304]
Hello,Recently, this resource has been downloading slowly, but it finally failed. I tried many times，think you
！
<img width="575" alt="截屏2020-12-25 下午6 59 23" src="https://user-images.githubusercontent.com/4881647/103133088-6b7ff300-46e3-11eb-863e-506f68575def.png">
<img width="574" alt="截屏2020-12-25 下午6 59 54" src="https://user-images.githubusercontent.com/4881647/103133090-6de24d00-46e3-11eb-9865-998e0a0dd982.png">

**Comment by dnkoutso** [comment]
This seems like. a network issue with cloning the master source repo. Remove it from the top of your podfile perhaps and use the CDN?
