### ISSUE TITLE
Error Occurred when installing Google AdMobs

### ISSUE THREAD

**Issue by Daniel-Sama** [CocoaPods/CocoaPods#10306]
Hi,

I'm trying to install Google Admobs into my Xcode project using CocoaPods, but a error came up.

Please tell me how to fix this

Thanks

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install --repo-update

## What did you expect to happen?

Install the pod dependencies correctly without any errors

## What happened instead?

This error came up: [!] Oh no, an error occurred.

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.0.1 (20B29)
       Xcode : 12.2 (12B45b)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hode The Line' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hode The Line
  pod 'Google-Mobile-Ads-SDK'

  target 'Hode The LineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hode The LineUITests' do
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Please paste the error. This report is incomplete.
