### ISSUE TITLE
Ability to use `install! 'cocoapods', skip_pods_project_generation: true` outside of Podfile.

### ISSUE THREAD

**Issue by swiftyfinch** [CocoaPods/CocoaPods#10305]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Hello! I'm not sure that I do it correctly here, but I want to ask the question (**It's not an issue**).

I work on a huge project and we commit our `Podfile.lock` in a git repo. So, we often have conflicts in that file on that line:
`PODFILE CHECKSUM: *some checksum*`

Then we solve conflict and run the command `pod install`, which takes a lot of time for us. Especially, the part of `Generating Pods project`. About `3-4 minutes`. We will try to manage that ourselves for now.

I noticed that for solving the conflict in `PODFILE CHECKSUM: *some checksum*` line I don't want to use `Generating Pods project` step. Also, I found the ability to switch off that step via Podfile. `install! 'cocoapods', skip_pods_project_generation: true`.
But this command changes Podfile.lock checksum too.

**I wonder if there have any chance to use `skip_pods_project_generation` without affecting `Podfile.lock`. For example, something like that: `pod install --skip_pods_project_generation`. Or any other solution.**

**Comment by dnkoutso** [comment]
Do you check in your Pods directory? If not then you can use this https://github.com/segiddins/cocoapods-amicable.

At this time updating the Podfile.lock checksum is probably something that cocoapods should do and does intentionally as the contents of the file may change as. is your case with the conflicts you have to deal with.

**Comment by swiftyfinch** [comment]
Thanks a lot! It looks like a good workaround. I will try it and come back soon.

**Comment by swiftyfinch** [comment]
@dnkoutso OK, let's close this. Thanks for your suggestion! 🎉
