### ISSUE TITLE
Pod spec validation error when validating a xcframework

### ISSUE THREAD

**Issue by Swapnil1794** [CocoaPods/CocoaPods#10310]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
created podspec file to distribute xcframework

## What did you expect to happen?
podspec file must validate successfully

## What happened instead?

Error occurred while validating podspec file -- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

## CocoaPods Environment
Cocoapods version - 1.10.0
Xcode : 12.2

## Project that demonstrates the issue

Podspec file :
Pod::Spec.new do |s|

s.platform = :ios
s.ios.deployment_target = '11.1'
s.swift_version = "5.0"
s.name = "PMCareFramework"
s.summary = "PMCareFramework for customer."
s.requires_arc = true

s.version = "1.0.46"
s.license = { :type => "MIT", :file => "LICENSE" }

s.author = { "Swapnil G" => "swapnil.gavali@vivant.me" }

s.homepage = "https://git.allizhealth.com/Repository/Detail/1d8e78d6-d115-4b96-9fb4-c5a8e3667dc3"

s.source = { :git => "https://git.allizhealth.com/PMCareFramework.git",
:tag => "#{s.version}" }

s.ios.framework  = "UIKit"
s.framework  = "WebKit"
s.ios.framework  = "HealthKit"

s.dependency 'SQLite.swift','~> 0.12.2'
s.dependency 'Alamofire', '~> 5.2.2'
s.dependency 'Charts', '~> 3.5.0'
s.dependency 'CryptoSwift', '~> 1.3.1'
s.dependency 'NVActivityIndicatorView', '~> 5.0.0'
s.dependency 'SwiftSoup', '~> 2.3.2'
s.dependency 'SwiftyJSON', '~> 5.0.0'
s.dependency 'DropDown', '~> 2.3.13'
s.dependency 'HGCircularSlider', '~> 2.2.0'
s.dependency 'RealmSwift', '~> 5.3.3'
s.dependency 'SDWebImage', '~> 5.9.0'

s.vendored_frameworks = "PMCareFramework.xcframework"

end

**Comment by dnkoutso** [comment]
This is not a sufficient issue report. Please fill in all details and provide a reproducible sample.

Try running command with `--verbose` to see the error message.

Going to preemptively close as we get a lot of issues and its hard to manage all of them. 

I will re-open if you attach a sample and more complete information.

**Comment by SSAkash273** [comment]
-> TestPod (0.0.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [iOS] xcodebuild:  warning: [CP] RemotevalSDK.xcframework: Unable to find matching slice in 'ios-arm64' for the current build architectures (arm64 x86_64) and platform (-iphonesimulator).
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    
    I got this error when I add s.vendored_frameworks in the pod spec
