### ISSUE TITLE
Attempts to reorder groups in `post_install` are always over-written

### ISSUE THREAD

**Issue by OliverPearmain-Triller** [CocoaPods/CocoaPods#10318]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Create pod named "XampleLib"
$ `pod lib create XampleLib`

Respond with iOS, Swift, Yes, None, No

- Edit the generated `PodFile` as below (adding `generate_multiple_pod_projects` and `post_install`):
```
use_frameworks!

platform :ios, '9.0'

install! 'cocoapods',
  :generate_multiple_pod_projects => true

target 'XampleLib_Example' do
  pod 'XampleLib', :path => '../'

  target 'XampleLib_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    code_group = project.main_group.groups.find { |group| group.to_s == 'XampleLib' }
    next if code_group.nil?
    
    puts "Working on project #{project.path}"
    puts "Groups BEFORE:"
    project.main_group.children.each { |child| puts "  #{child}" }

    puts "Reordering groups"
    
    project.main_group.children.delete(code_group)
    project.main_group.children.insert(0, code_group)

    project.save # Not sure if this is required or not

    puts "Groups AFTER:"
    project.main_group.children.each { |child| puts "  #{child}" }
  end
end

```

- Erase the generated Pods and re-run `pod install`
$ `rm -rf Pods && pod install`

- Note the output from the `post_install` is as follows (which confirms the reordering as expected):
```
Analyzing dependencies
Downloading dependencies
Installing XampleLib (0.1.0)
Generating Pods project
Working on project /Users/okp/Code/XampleLib/Example/Pods/XampleLib.xcodeproj
Groups BEFORE:
  Products
  Frameworks
  XampleLib
Reordering groups
Groups AFTER:
  XampleLib
  Products
  Frameworks
Integrating client project
```

## What did you expect to happen?

I'd like for the "main" group `XampleLib` to appear at the very top. I expected the changes I'd made to the groups order in `post_install` to have been persisted and things to look like this in Xcode...
![Screenshot 2020-12-30 at 11 40 02](https://user-images.githubusercontent.com/70571840/103349093-d8a0d900-4a93-11eb-8d9d-bea780d869d2.png)

## What happened instead?

The changes to the groups order is NOT peristed and instead things like look this...
![Screenshot 2020-12-30 at 11 40 20](https://user-images.githubusercontent.com/70571840/103349164-0dad2b80-4a94-11eb-90d6-da6b09a267cd.png)

I suspect that after the `post_install` step when cocoapods itself saves the projects it does a full pass of all groups and re-sorts them. Hopefully however this is just something I am doing wrong.

## Project that demonstrates the issue

I don't think its necessary to create an example project since its faster and cleaner to just `pod lib create` as per the steps I have provided. 

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 11.7 (11E801a)
         Git : git version 2.28.0
Ruby lib dir : /Users/okp/.rbenv/versions/2.7.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ fbc970693ed5b76fd5f22cf57c50194c66b1335b

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/okp/.rbenv/versions/2.7.1/bin/pod
```

### Plugins

```
cocoapods-binary       : 0.4.4
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.3.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.5.0
cocoapods-try          : 1.2.0
```

### Podfile

```ruby
use_frameworks!

platform :ios, '9.0'

install! 'cocoapods',
  :generate_multiple_pod_projects => true

target 'XampleLib_Example' do
  pod 'XampleLib', :path => '../'

  target 'XampleLib_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    code_group = project.main_group.groups.find { |group| group.to_s == 'XampleLib' }
    next if code_group.nil?
    
    puts "Working on project #{project.path}"
    puts "Groups BEFORE:"
    project.main_group.children.each { |child| puts "  #{child}" }

    puts "Reordering groups"
    
    project.main_group.children.delete(code_group)
    project.main_group.children.insert(0, code_group)

    puts "Groups AFTER reordering:"
    project.main_group.children.each { |child| puts "  #{child}" }

    project.save
	
    puts "Groups AFTER save:"
    project.main_group.children.each { |child| puts "  #{child}" }
  end
end
```

**Comment by OliverPearmain-Triller** [comment]
I think my suspicions are correct. At the point the project is saved `project.sort(...)` is called...
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb#L81

I have now found a workaround which is to monkey-patch/swizzle the `sort` method of the `project` (in `post_install`) so that when called it does nothing.  Confirmed working :-)

```
    # Monkey-patch the projects `sort` method so the group reordering isn't undone when the project is saved
    def project.sort(arg) "Monkey-patched sort!" end
```

So my `post_install` now looks like this...
```
post_install do |installer|
  installer.generated_projects.each do |project|
    code_group = project.main_group.groups.find { |group| group.to_s == 'XampleLib' }
    next if code_group.nil?
    
    puts "Working on project #{project.path}"
    puts "Groups BEFORE:"
    project.main_group.children.each { |child| puts "  #{child}" }

    puts "Reordering groups"
    
    project.main_group.children.delete(code_group)
    project.main_group.children.insert(0, code_group)
	
    # Monkey-patch the projects `sort` method so the group reordering isn't undone when the project is saved
    def project.sort(arg) "Monkey-patched sort!" end
  end
end
```

**Comment by dnkoutso** [comment]
I believe there is a post_integrate hook you can use too.

Its generally not advisable to call 

```ruby
    project.save # Not sure if this is required or not
```

Because cocoapods will also call save again afterwards.

**Comment by OliverPearmain-Triller** [comment]
Thanks for the reply.  The `post_intgrate` hooks works perfectly (provided I called `project.save`) without the need for monkey-patching/swizzling. 👍 👍 👍 

PS: there doesn't seem to be any documenation on the `post_integrate` hook under the [Hooks documentation](https://guides.cocoapods.org/syntax/podfile.html#group_hooks), which is why I never discovered it by myself.  Perhaps this could be addressed?

Thanks again.

**Comment by OliverPearmain-Triller** [comment]
To be fair though, it looks like its only just been released!!

https://blog.cocoapods.org/CocoaPods-1.10.0-beta/

**Comment by dnkoutso** [comment]
@OliverPearmain-Triller good point I was looking to update those earlier, will do as part of this.
