### ISSUE TITLE
can't get podspec validation [iOS] xcodebuild: Returned an unsuccessful exit code.

### ISSUE THREAD

**Issue by iChirag** [CocoaPods/CocoaPods#10322]
Details:
Xcode 12.2
Error:
 ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

podspec:
https://github.com/softnoesis-com/ShakeBug/blob/master/ShakeBug.podspec

```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/var/folders/nf/dy0jjxbn64b3b693v4v3zk6r0000gn/T/CocoaPods-Lint-20201231-12444-1te9kdy-ShakeBug/Pods/ShakeBug/ShakeBug.framework/ShakeBug' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Ld /Users/ichirag/Library/Developer/Xcode/DerivedData/App-gkjznaptcvsieubqxdjbbriqooaj/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/arm64/Binary/App normal arm64
    (1 failure)
   Testing with `xcodebuild`. 
 -> ShakeBug (1.0.13)
    - WARN  | [iOS] license: Unable to find a license file
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

[!] The spec did not pass validation, due to 1 error.
```

I tested this pod with the local directory, it works fine. I also achieved IPA as well with a local document directory pod. 
 
Please help me.

**Comment by gajjartejas** [comment]
Same issue here.

**Comment by dnkoutso** [comment]
```
    	Ld /Users/ichirag/Library/Developer/Xcode/DerivedData/App-gkjznaptcvsieubqxdjbbriqooaj/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/arm64/Binary/App normal arm64
```

Seems like the artifact being built is not producing this architecture.

I think there are other issue reports around here you have to update your `pod_target_xcconfig` to disable an architecture.

Search for "building for iOS Simulator, but linking in dylib built for iOS" in the issues.

**Comment by iChirag** [comment]
hello @dnkoutso 
Thanks for the message.

Earlier when I was exported framework then I was facing an issue arm64 issue when I was combining both the simulator and iPhone framework.

After lots of investigation, I founded a solution to my script

`xcodebuild -target "${PROJECT_NAME}" BITCODE_GENERATION_MODE=bitcode OTHER_CFLAGS="-fembed-bitcode" -configuration ${CONFIGURATION} -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR="${BUILD_DIR}" BUILD_ROOT="${BUILD_ROOT}" EXCLUDED_ARCHS="arm64" clean build`

So I added
`EXCLUDED_ARCHS="arm64"` and it starts working for both simulator and iPhone.

I tested this framework with a local directory pod and it was fine for both the simulator and iPhone.

but now only` pod spec lint .` giving this error.

how to get a solution for this? So far I did the same procedure more than 10 times and it was always working fine without any changes to my script. This issue only started after Xcode 12 come.

**Comment by dnkoutso** [comment]
You can change such settings via `s.pod_target_xcconfig`. search for EXCLUDED_ARCHS in the issues here you will see examples.

**Comment by iChirag** [comment]
hello @dnkoutso 

As per your instruction, I had added the following line in .podspec file
`s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }`

but I am still getting same error

```
** BUILD FAILED **
    
    
    The following build commands failed:
    	Ld /Users/ichirag/Library/Developer/Xcode/DerivedData/App-bxtzzkkqvahdbobofjassjnqnxck/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/arm64/Binary/App normal arm64
    (1 failure)
   Testing with `xcodebuild`. 
 -> ShakeBug (1.0.13)
    - WARN  | [iOS] license: Unable to find a license file
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

[!] The spec did not pass validation, due to 1 error.

```

**Comment by iChirag** [comment]
Never mind @dnkoutso 

I just added a single line, I have to add 2 lines in .podspec file and it succeeded.
```
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

Thanks a lot!

**Comment by dnkoutso** [comment]
yeap thats it.

**Comment by pranayprajapati** [comment]
- WARN  | [iOS] swift: The validator used Swift `4.0` by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_versions` attribute in your podspec. Note that usage of a `.swift-version` file is now deprecated.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | [iOS] xcodebuild:  note: Planning
    - NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
    - ERROR | xcodebuild:  MyFramework/MyFramework/ViewControllers/FirstVC/FirstViewController.swift:9:8: error: no such module 'SocketIO'

**Comment by jaykumarvcx** [comment]
Hi Guys,

I am also facing the same 
 - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'Starscream' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'Starscream' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'Socket.IO-Client-Swift' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'GoogleWebRTC' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'EnxRTCiOS' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'Socket.IO-Client-Swift' from project 'Pods')

Whare I have added 

s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }

But still no luck, suggestion, please

**Comment by jaykumarvcx** [comment]
Hi Paulb

I have done the same and I got an error as

ld: framework not found **EnxFaceAIiOS**
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    Copy /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.swiftmodule/x86_64-apple-ios-simulator.abi.json /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.abi.json (in target 'App' from project 'App')
        cd /var/folders/mv/vjq48h6s349c4scqf3_9r89r0000gn/T/CocoaPods-Lint-20221011-11533-xng8ma-EnxFaceAIiOS
        builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks -rename /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.abi.json /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.swiftmodule/x86_64-apple-ios-simulator.abi.json
    
    Copy /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.swiftmodule/x86_64-apple-ios-simulator.swiftdoc /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.swiftdoc (in target 'App' from project 'App')
        cd /var/folders/mv/vjq48h6s349c4scqf3_9r89r0000gn/T/CocoaPods-Lint-20221011-11533-xng8ma-EnxFaceAIiOS
        builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks -rename /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.swiftdoc /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.swiftmodule/x86_64-apple-ios-simulator.swiftdoc
    
    Copy /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.swiftmodule/x86_64-apple-ios-simulator.swiftmodule /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.swiftmodule (in target 'App' from project 'App')
        cd /var/folders/mv/vjq48h6s349c4scqf3_9r89r0000gn/T/CocoaPods-Lint-20221011-11533-xng8ma-EnxFaceAIiOS
        builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks -rename /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.swiftmodule /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
    
    Copy /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.swiftmodule/Project/x86_64-apple-ios-simulator.swiftsourceinfo /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.swiftsourceinfo (in target 'App' from project 'App')
        cd /var/folders/mv/vjq48h6s349c4scqf3_9r89r0000gn/T/CocoaPods-Lint-20221011-11533-xng8ma-EnxFaceAIiOS
        builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks -rename /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.swiftsourceinfo /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.swiftmodule/Project/x86_64-apple-ios-simulator.swiftsourceinfo
    
    /var/folders/mv/vjq48h6s349c4scqf3_9r89r0000gn/T/CocoaPods-Lint-20221011-11533-xng8ma-EnxFaceAIiOS/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'EnxRTCiOS' from project 'Pods')
    /var/folders/mv/vjq48h6s349c4scqf3_9r89r0000gn/T/CocoaPods-Lint-20221011-11533-xng8ma-EnxFaceAIiOS/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'GoogleWebRTC' from project 'Pods')
    /var/folders/mv/vjq48h6s349c4scqf3_9r89r0000gn/T/CocoaPods-Lint-20221011-11533-xng8ma-EnxFaceAIiOS/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'Socket.IO-Client-Swift' from project 'Pods')
    ** BUILD FAILED **
    
    
    The following build commands failed:
    	Ld /Users/jaykumar/Library/Developer/Xcode/DerivedData/App-faiicaykyxzscrhaalxomjiunjdz/Build/Products/Release-iphonesimulator/App.app/App normal (in target 'App' from project 'App')
    (1 failure)
   Testing with `xcodebuild`. 
 -> EnxFaceAIiOS (1.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'Starscream' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'Starscream' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Metadata extraction skipped. No AppIntents.framework dependency found. (in target 'Socket.IO-Client-Swift' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'EnxRTCiOS' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'GoogleWebRTC' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.0.99. (in target 'Socket.IO-Client-Swift' from project 'Pods')

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.



This is my framework, which I am going to release on cocoa pod **EnxFaceAIiOS**
But after creating the framework, once I add it manually to my project, it is working.

The only issue I am unable to publish on Cocoa Pod.

**Comment by iZooto-App-Push** [comment]
https://github.com/CocoaPods/CocoaPods/issues/11741#issue-1559259877

**Comment by zhangyy2017** [comment]
@jaykumarvcx  I also had the same problem, but I added the following and it compiled

**Comment by zhangyy2017** [comment]
@jaykumarvcx  I also had the same problem, but I added the following and it compiled

s.pod_target_xcconfig = {
    'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'x86_64 armv7 arm64',
    'VALID_ARCHS' => 'x86_64 armv7 arm64',
  }
  s.user_target_xcconfig = {
      'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'x86_64 armv7 arm64',
      'VALID_ARCHS' => 'x86_64 armv7 arm64',
  }
