### ISSUE TITLE
PrivatePods files didn't show as expect In Xcode 12.3 Project Navigator

### ISSUE THREAD

**Issue by shi1234ww** [CocoaPods/CocoaPods#10321]
Hi ~ 
   My pod --version is 1.10.0, Xcode  version is 12.3 .
 I've made a private pods using cocoapods, It show well In Finder like this :
<img width="813" alt="Screen Shot 2020-12-31 at 18 03 36" src="https://user-images.githubusercontent.com/15307512/103405568-87c3da00-4b92-11eb-8883-0a582c56bdbf.png">

But In Xcode navigator  , It show like this 

<img width="262" alt="Screen Shot 2020-12-31 at 17 58 20" src="https://user-images.githubusercontent.com/15307512/103405584-94483280-4b92-11eb-8cd9-7c1e8260d828.png">
It seems that the pod files didn't be categoried with folders,   like what AFNetworking does,
<img width="263" alt="Screen Shot 2020-12-31 at 18 05 37" src="https://user-images.githubusercontent.com/15307512/103405670-ce193900-4b92-11eb-922f-989144821d1d.png">

My *.podspec file is like this : 
s.source_files = 'Module_A/Classes/**/*'

  s.subspec 'Business' do |ss1|
    ss1.source_files = 'Module_A/Classes/Business/*.{h,m}'
  end

  s.subspec 'Target_CT' do |ss2|
    ss2.source_files = 'Module_A/Classes/Target_CT/*.{h,m}'
    ss2.dependency 'Module_A/Business'
  end

  s.subspec 'Category_CT' do |ss3|
    ss3.source_files = 'Module_A/Classes/Category_CT/*.{h,m}'
  end
  

Is there any solution to make my private pod file show well Like Afnnetworking?  which files will be settled In folder?Thanks

**Comment by dnkoutso** [comment]
CocoaPods will flatten this if there are no sub-folders. Once you add a subfolder it should create the groups as you expect.

There is also `preserve_pod_file_structure` I think installation option to use.

Going to close for now as this works as intended.

**Comment by shi1234ww** [comment]
It works , Thank you very much !
