### ISSUE TITLE
Pods/Target Support Files/Pods-VideoClip/Pods-VideoClip-frameworks.sh: line 43: source: unbound variable

### ISSUE THREAD

**Issue by corners-summer** [CocoaPods/CocoaPods#10330]
I made such a mistake in the running times：
Pods/Target Support Files/Pods-VideoClip/Pods-VideoClip-frameworks.sh: line 43: source: unbound variable
CocoaPods 1.10.0

**Comment by dnkoutso** [comment]
This is not a valid issue report.
