### ISSUE TITLE
Pod with dependency resulting in warnings saying that classes are implemented in two places

### ISSUE THREAD

**Issue by DamascenoRafael** [CocoaPods/CocoaPods#10343]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I am trying to distribute a framework using the `.xcframework` format (since the goal is to keep the framework's source closed).

It has a dependency on `pod 'GoogleMLKit / FaceDetection'` (specified on the `.podspec` file).

I create a SampleApp with a `Podfile` containing the my framework as a dependency.

The current project organization is:

```
📂 MyFramework
 ┣ 📜 MyFramework.xcodeproj
 ┣ 📜 MyFramework.xcworkspace
 ┣ 📜 Podfile
 ┣ 📜 MyFramework.podspec
 ┣ 📂 Sources
 ┃  ┗ ...
 ┗ 📂 SampleApp
    ┣ 📜 SampleApp.xcodeproj
    ┣ 📜 SampleApp.xcworkspace
    ┣ 📜 Podfile
    ┗ ...
```

I generated the `MyFramework.xcframework` using the following commands:

```bash
# iOS slice
xcodebuild archive \
    -workspace MyFramework.xcworkspace \
    -scheme MyFramework \
    -configuration Release \
    -sdk iphoneos \
    -arch arm64 \
    -archivePath './build/temp/MyFramework.framework-iphoneos.xcarchive' \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
    SKIP_INSTALL=NO

# Simulator slice
xcodebuild archive \
    -workspace MyFramework.xcworkspace \
    -scheme MyFramework \
    -configuration Release \
    -sdk iphonesimulator \
    -arch x86_64 \
    -archivePath './build/temp/MyFramework.framework-iphonesimulator.xcarchive' \
    BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
    SKIP_INSTALL=NO

# Create the XCFramework
xcodebuild -create-xcframework \
    -framework './build/temp/MyFramework.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/MyFramework.framework' \
    -framework './build/temp/MyFramework.framework-iphoneos.xcarchive/Products/Library/Frameworks/MyFramework.framework' \
    -output './build/MyFramework.xcframework'
```

I made a `MyFramework.zip` containing `MyFramework.xcframework` avaiable at `http://localhost:8080/MyFramework.zip`.

Then I ran `pod install` on the `SampleApp` folder, openned `SampleApp.xcworkspace` and tried to build and run using Xcode.

*I copied the relevants files below at [relevant files section](#relevant-files).*

## What did you expect to happen?

I expected the SampleApp to run without warnings.

## What happened instead?

The SampleApp emitted several warnings saying that classes from Google are implemented in two places. Examples below:

```
objc[27285]: Class PodsDummy_GoogleUtilitiesComponents is implemented in both /private/var/containers/Bundle/Application/FDA4FC83-BD07-45B6-8F52-3E0E17A60EF5/SampleApp.app/Frameworks/MyFramework.framework/MyFramework (0x1052d93a8) and /private/var/containers/Bundle/Application/FDA4FC83-BD07-45B6-8F52-3E0E17A60EF5/SampleApp.app/SampleApp (0x103dcf480). One of the two will be used. Which one is undefined.
objc[27285]: Class GULCCComponent is implemented in both /private/var/containers/Bundle/Application/FDA4FC83-BD07-45B6-8F52-3E0E17A60EF5/SampleApp.app/Frameworks/MyFramework.framework/MyFramework (0x1052d93d0) and /private/var/containers/Bundle/Application/FDA4FC83-BD07-45B6-8F52-3E0E17A60EF5/SampleApp.app/SampleApp (0x103dcf4a8). One of the two will be used. Which one is undefined.
objc[27285]: Class MLKLoggerProcessInfo is implemented in both /private/var/containers/Bundle/Application/FDA4FC83-BD07-45B6-8F52-3E0E17A60EF5/SampleApp.app/Frameworks/MyFramework.framework/MyFramework (0x1052d9538) and /private/var/containers/Bundle/Application/FDA4FC83-BD07-45B6-8F52-3E0E17A60EF5/SampleApp.app/SampleApp (0x103dcf610). One of the two will be used. Which one is undefined.
...
```

By searching on the internet I found out ([from this link](https://github.com/CocoaPods/CocoaPods/issues/9586)) that I could work around this issue with a post_install script that removes the conflicting libraries from the linking path of the SampleApp. But I don't know if that has some side effects. Also it would be interesting if I didn't have to add a post_install script to the SampleApp `Podfile` and the solution involved only the framework.

```ruby
# SampleApp/Podfile

static_libraries = ["GoogleUtilitiesComponents", "MLKitCommon", "MLKitFaceDetection", "MLKitVision"]

post_install do |installer|
  puts "Running post_install script"
  puts "Fix static_libraries"
  installer.aggregate_targets.each do |aggregate_target|
    puts aggregate_target
    aggregate_target.xcconfigs.each do |config_name, config_file|
      config_file.frameworks.subtract(static_libraries)
      xcconfig_path = aggregate_target.xcconfig_path(config_name)
      config_file.save_as(xcconfig_path)
    end
  end
end
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H15)
       Xcode : 12.3 (12C33)
         Git : git version 2.28.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

<a name="relevant-files"></a>
## Relevant files

The MyFramework `Podfile`:
```ruby
platform :ios, '10.0'

target 'MyFramework' do
  use_frameworks!

  project './MyFramework.xcodeproj'
  pod 'GoogleMLKit/FaceDetection'

end
```

The relevant parts of `MyFramework.podspec`:
```ruby
Pod::Spec.new do |spec|

  # ...

  spec.platform     = :ios, "10.0"

  spec.source       = { :http => "http://localhost:8080/MyFramework.zip" }
  spec.vendored_frameworks = 'MyFramework.xcframework'

  spec.dependency "GoogleMLKit/FaceDetection", "~> 1.0"

end
```

The original `SampleApp/Podfile`:
```ruby
platform :ios, '10.0'

target 'SampleApp' do
  use_frameworks!

  # Pods for SampleApp
  pod 'MyFramework', :podspec => '../MyFramework.podspec'

end
```

**Comment by DamascenoRafael** [comment]
Update: I was able to solve the problem without using the post_install script.
Since the framework makes use of some static dependencies a solution would be to change the framework to be static as well.

The main changes I didn't know exactly how to make were:
- Change the "Math-O Type" property in "Build Settings" to "Static Library";
- Run "xcodebuild build" instead of "xcodebuild archive".

**Comment by trimech-hsan** [comment]
Hello DamascenoRafael.
 I have the same issue with my custom xcframework 
But your solution, not worked for me.
I have a question  about this "Run "xcodebuild build" instead of "xcodebuild archive".
"how you can create xcframework without  archive?
Thanks
