### ISSUE TITLE
Cocoa pods installation error

### ISSUE THREAD

**Issue by Zaitam** [CocoaPods/CocoaPods#10340]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

 🌈
## What did you do?
npx pod-install/npm run install:macos/pod install
## What did you expect to happen?
Cocoapods installation is successful
## What happened instead?

`
Auto-linking React Native module for target `spotter-macOS`: RNCAsyncStorage
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native-macos/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native-macos/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost-for-react-native` from `../node_modules/react-native-macos/third-party-podspecs/boost-for-react-native.podspec`
Fetching podspec for `glog` from `../node_modules/react-native-macos/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.62.16)
Installing FBReactNativeSpec (0.62.16)
Installing KeyHolder (4.0.0)
Installing Magnet (3.2.0)
Installing RCT-Folly (2018.10.22.00)
Installing RCTRequired (0.62.16)
Installing RCTTypeSafety (0.62.16)
Installing RNCAsyncStorage (1.13.2)
Installing React (0.62.16)
Installing React-Core (0.62.16)
Installing React-CoreModules (0.62.16)
Installing React-RCTActionSheet (0.62.16)
Installing React-RCTAnimation (0.62.16)
Installing React-RCTBlob (0.62.16)
Installing React-RCTImage (0.62.16)
Installing React-RCTLinking (0.62.16)
Installing React-RCTNetwork (0.62.16)
Installing React-RCTSettings (0.62.16)
Installing React-RCTText (0.62.16)
Installing React-RCTVibration (0.62.16)
Installing React-cxxreact (0.62.16)
Installing React-jsi (0.62.16)
Installing React-jsiexecutor (0.62.16)
Installing React-jsinspector (0.62.16)
Installing ReactCommon (0.62.16)
Installing Sauce (2.1.0)
Installing ShellOut (2.0.0)
Installing Yoga (1.14.0)
Installing boost-for-react-native (1.63.0)
Installing glog (0.3.5)
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h

/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif

/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif

/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-apple-darwin-gcc... /Library/Developer/CommandLineTools/usr/bin/cc -arch armv7 -isysroot 
checking whether the C compiler works... no
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos'
/Users/MatiasGotz/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-d86cb/missing: Unknown `--is-lightweight' option
Try `/Users/MatiasGotz/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-d86cb/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/MatiasGotz/Library/Caches/CocoaPods/Pods/External/glog/2263bd123499e5b93b5efe24871be317-d86cb':
configure: error: C compiler cannot create executables
See `config.log' for more details

## CocoaPods Environment
```
   CocoaPods : 1.10.1
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.7 (19H114)
       Xcode :  ()
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/MatiasGotz/.rvm/rubies/ruby-2.7.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/

**Comment by dnkoutso** [comment]
This is an invalid issue report and also it seems like an environment issue.
