### ISSUE TITLE
Update .xcconfig file for pod from podspec

### ISSUE THREAD

**Issue by ManaliSingh27** [CocoaPods/CocoaPods#10342]
Sorry if this is the wrong place to post this.
I need add #include a file in .xcconfig generated for pods. Is there some way to specify this in podspec file?

**Comment by dnkoutso** [comment]
Not in podspec, you can only do it in `post_install` hook inside `Podfile`.

**Comment by ManaliSingh27** [comment]
Is it possible to share a sample code (to be added in podfile) to include a file. I want the developed cocoapod classes  to access the included file.

**Comment by dnkoutso** [comment]
You can just use standard Ruby on `post_install` inside your `Podfile` to `File.open` the xcconfig file and then edit it to add a line.

For now going to close as no further action seems to be needed for CocoaPods.
