### ISSUE TITLE
Get this error when run the command "pod setup" on Mac M1

### ISSUE THREAD

**Issue by master950** [CocoaPods/CocoaPods#10357]
hignton@higntondeMac-mini ~ % pod setup
Traceback (most recent call last):
	16: from /usr/local/bin/pod:23:in `<main>'
	15: from /usr/local/bin/pod:23:in `load'
	14: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:36:in `<top (required)>'
	13: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	12: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	11: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods.rb:9:in `<top (required)>'
	10: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 9: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 8: from /Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	 7: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 6: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 5: from /Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/xml_mini.rb:5:in `<top (required)>'
	 4: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 3: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/bigdecimal-2.0.2/lib/bigdecimal.rb:1:in `<top (required)>'
	 1: from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require': dlsym(0x7fbd8d594df0, Init_bigdecimal): symbol not found - /Library/Ruby/Gems/2.6.0/gems/bigdecimal-2.0.2/lib/bigdecimal.bundle (LoadError)

**Comment by dnkoutso** [comment]
This is not a sufficient issue report. Also please use this https://github.com/CocoaPods/CocoaPods/issues/9907 as an issue around M1.
