### ISSUE TITLE
preserve_paths not being respected

### ISSUE THREAD

**Issue by rohan-elear** [CocoaPods/CocoaPods#10358]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I am wrapping a C static library around a wrapper written in Swift.
I have a script to download the libraries .a in various arch and compile a .xcframework to be sourced by the wrapper.
I have added the path of the CSDK in the preserve_paths but I do not see it getting copied out. Hence the Podspec file is not able to run the script to download items and create the xcframework.

`pod lib lint`

NOTE: The project build fine with command line xcodebuild or GUI. I am also able to distribute this using xcframework but not able to make it run using pod.
``` ruby
s.preserve_paths = ['myCSDK/**/*']
s.script_phase = { :name => 'Fetch_CSDK_binaries',
    :script => '$SRCROOT/myCSDK/fetch-libs.sh',
    :execution_position => :before_compile }
```

```
.
├── myCSDK
│   ├── fetch-libs.sh
│   └── include
│       ├── libA
│       └── libB
├── mySDK
│   ├── Callback
│   ├── Data\ Models
│   ├── Extensions
│   └── Logger
└── mySDK.xcodeproj
```

## What did you expect to happen?

mySDK did pass validation

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
`/var/folders/6b/2_vqps3d00558xlzm36b1wn00000gn/T/CocoaPods-Lint-20210115-2224-1hb3k5r-mySDK/Pods/myCSDK/fetch-libs.sh: No such file or directory
    Command PhaseScriptExecution failed with a nonzero exit code`

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H114)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.10.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mySDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for mySDK

  target 'mySDKTests' do
    # Pods for testing
  end

end
```

**Comment by dnkoutso** [comment]
i think you want to use `$PODS_TARGET_SRCROOT` instead.

$SRCROOT is set by Xcode and its not the same location as your pod is installed by CocoaPods.

**Comment by rohan-elear** [comment]
Thanks for the advice, I had tried it ran the script. Now on to solving the next issue with this.

**Comment by dnkoutso** [comment]
Going to close for now and re-open if you find any issues!
