### ISSUE TITLE
Header file can not be found when archiving for Catalyst

### ISSUE THREAD

**Issue by yulin-liang** [CocoaPods/CocoaPods#10354]
**Archiving** a project for **Mac Catalyst** that includes the gRPC-Core pod fails because header files in its sub-framework `openssl_grpc.framework` can not be found. While **building for Catalyst** or **archiving for iOS device** are successful. 

- When **building** the project, ` openssl_grpc.framework` creates a new symlink called Header which points to `Versions/Current/Headers`
  <img width="1706" alt="Screen Shot 2021-01-14 at 2 55 21 PM" src="https://user-images.githubusercontent.com/64815511/104663949-ebfe9780-5682-11eb-9ad7-22688f37c81b.png">
 
  ![image](https://user-images.githubusercontent.com/64815511/104664392-f79e8e00-5683-11eb-9539-81a9899a2aca.png)
 
- But **archiving** doesn't create the symbolic link.
  ![image](https://user-images.githubusercontent.com/64815511/104664257-a1314f80-5683-11eb-9813-5e540de83c78.png)
 
  ![image](https://user-images.githubusercontent.com/64815511/104664478-32a0c180-5684-11eb-88db-efaf67dbdef7.png)

Here's the [BoringSSL-GRPC.podspec](https://github.com/grpc/grpc/blob/master/src/objective-c/BoringSSL-GRPC.podspec), I don't if it is related to the `header_mappings_dir` or `header_dir` attributes, do you have any idea?

## Reproduce

Here's an smaller repro case at https://github.com/paulb777/CatalystArchiveGRPC

git clone git@github.com:paulb777/CatalystArchiveGRPC.git
cd CatalystArchiveGRPC
open CatalystArchiveGRPC.xcworkspace
Choose MyMac scheme
Product -> Archive

## What did you expect to happen?

Archive fails.

## What happened instead?

Successful archive

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
    RubyGems : 3.0.8
        Host : macOS 11.1 (20C69)
       Xcode : 11.6 (11E708)
         Git : git version 2.30.0.284.gd98b1dd5eaa7-goog
Ruby lib dir : /Users/yulinliang/.rvm/rubies/ruby-2.6.5/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ d5725915e8e3c2c1bf31228f817373543a9cee3e

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/yulinliang/.rvm/gems/ruby-2.6.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatalystArchiveGRPC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatalystArchiveGRPC
  pod "BoringSSL-GRPC", "0.0.14"
  pod "gRPC-Core", "1.34.0"

end
```

## Project that demonstrates the issue

https://github.com/paulb777/CatalystArchiveGRPC

more info can be found: https://github.com/grpc/grpc/issues/20500

**Comment by dnkoutso** [comment]
did try cocoapods 1.10.1?

**Comment by yulin-liang** [comment]
It still doesn't work.

**Comment by tgoyne** [comment]
https://github.com/CocoaPods/CocoaPods/pull/10224 should fix this.
