### ISSUE TITLE
"pod update" don't work on Mac-mini M1

### ISSUE THREAD

**Issue by BobbyStefansson** [CocoaPods/CocoaPods#10353]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

I got a crash depending on ffi
LoadError - dlsym(0x7ff386da3b70, Init_ffi_c): symbol not found - /Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Access' do

  use_frameworks!

  pod 'Alamofire', '~> 5.3'
  pod 'CocoaLumberjack/Swift', '3.7'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

  target 'AccessTests' do

    inherit! :search_paths

    pod 'OHHTTPStubs', '~> 9.0.0'
    pod 'OHHTTPStubs/Swift'

  end

end

```

**Comment by dnkoutso** [comment]
dup of https://github.com/CocoaPods/CocoaPods/issues/10315#issuecomment-756349884 tons of other similar issues here regarding `ffi`.

**Comment by BobbyStefansson** [comment]
Yes, sorry, I noticed - except that none of the described solutions worked... What can be done? Wait until 'ffi' gets updated 
![image](https://user-images.githubusercontent.com/77467732/104661700-60f4c000-56c9-11eb-919f-d60a1dc9765d.png)

**Comment by dnkoutso** [comment]
I am not sure for M1 as I do not have one but check this still open issue https://github.com/CocoaPods/CocoaPods/issues/9907
