### ISSUE TITLE
 CocoaPods requires your terminal to be using UTF-8 encoding.     Consider adding the following to ~/.profile:      export LANG=en_US.UTF-8

### ISSUE THREAD

**Issue by anujrathore131** [CocoaPods/CocoaPods#10361]
i have added   export LANG=en_US.UTF-8 still facing same errors what to do?

**Comment by OKNoah** [comment]
> i have added export LANG=en_US.UTF-8 still facing same errors what to do?

You probably need to add it to `~/.zshrc` if anything.

**Comment by dnkoutso** [comment]
Also ensure you re-start your terminal when you run this command.

It is best to ask this question in StackOverflow as no further action will be taken for CocoaPods.
