### ISSUE TITLE
Only one vendored_frameworks containing multiple xcframework is correctly integrated into project

### ISSUE THREAD

**Issue by qchenqizhi** [CocoaPods/CocoaPods#10378]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Only one vendored_frameworks containing multiple `xcframework` is correctly integrated into the project

## What did you do?

pod install

## What did you expect to happen?
Install all pod dependencies correctly. build success

## What happened instead?
pod install success
build with error:
```
No such module 'expat'
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.3 (12C33)
         Git : git version 2.15.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.0'

target 'Demo' do
  platform :ios, '11.0'
  use_frameworks!
  pod 'mobile-ffmpeg-full', '~> 4.4'
end
```

## Project that demonstrates the issue
It can be easily reproduced:
Add `mobile-ffmpeg-full` to the Podfile, and then import multiple frameworks provided by `mobile-ffmpeg-full` in project
![image](https://user-images.githubusercontent.com/973316/105673208-b0848880-5f20-11eb-9d07-f80eb8d6f663.png)

Maybe related: https://github.com/tanersener/mobile-ffmpeg/issues/663

**Comment by dnkoutso** [comment]
Please provide a sample app demonstrating the issue.

**Comment by dnkoutso** [comment]
oh nevermind you have some clear and easy instructions to do so.

**Comment by dnkoutso** [comment]
yeap confirmed. I think I got a fix as well.

**Comment by dnkoutso** [comment]
Posted a fix https://github.com/CocoaPods/CocoaPods/pull/10884
