### ISSUE TITLE
ERROR | [OSX] unknown: Encountered an unknown error (Unsupported file type: ) during validation.

### ISSUE THREAD

**Issue by praveenkumar8699** [CocoaPods/CocoaPods#10380]
* [ Yes] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod spec lint`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Validate the podspec file

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. ERROR | [iOS] unknown: Encountered an unknown error (Unsupported file type: ) during validation.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H15)
       Xcode : 12.3 (12C33)
         Git : git version 2.29.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.10.0/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

ERROR | [iOS] unknown: Encountered an unknown error (Unsupported file type: ) during validation.
![Screenshot 2021-01-25 at 8 17 36 PM](https://user-images.githubusercontent.com/16165392/105721260-5f898a00-5f4a-11eb-8cf8-89e6926139e9.png)

**Comment by dnkoutso** [comment]
This is not a sufficient issue report but my take is that the source you have provided is not supported in `s.source`
