### ISSUE TITLE
How can I specify in the podfile to automatically enable the UITests target

### ISSUE THREAD

**Issue by SergeyVerigin** [CocoaPods/CocoaPods#10384]
if IS_UITESTING_ENABLED
          target.build_configurations.each do |config|
    if target.name == "iOSAutoTests-UI-Tests"
          config.build_settings['TEST_TARGET_NAME'] = "APP"
    end
    end
    end
    end

I automatically create a target with tests in xcode, but it is disabled by default, as I can specify via the podfile to automatically enable the target

**Comment by SergeyVerigin** [comment]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/51368366/106005868-b49ddb00-60c5-11eb-98ee-9d5876721d80.png">

**Comment by dnkoutso** [comment]
Start from here https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb#L153

going to close as this does not appear a bug or enhancement for cocoapods.
