### ISSUE TITLE
Plist::Emit.save_plist(acknow, acknowPath, { :indent => "" }) wrong number of arguments (given 2, expected 0..1)

### ISSUE THREAD

**Issue by DidiFly** [CocoaPods/CocoaPods#10397]
cocoapods version 1.10.1

terminal:
[!] An error occurred while processing the post-install hook of the Podfile.

wrong number of arguments (given 2, expected 0..1)

/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/CFPropertyList-3.0.3/lib/cfpropertylist/rbCFPropertyList.rb:440:in `to_plist'
/Users/d7test/Desktop/Git/xxxx_Gitlab_Branch_hotfix(1d562561)_release/xxxx-ios/plist/plist/generator.rb:60:in `block in save_plist'
/Users/d7test/Desktop/Git/xxxx_Gitlab_Branch_hotfix(1d562561)_release/xxxx-ios/plist/plist/generator.rb:59:in `open'
/Users/d7test/Desktop/Git/xxxx_Gitlab_Branch_hotfix(1d562561)_release/xxxx-ios/plist/plist/generator.rb:59:in `save_plist'
/Users/d7test/Desktop/Git/xxxx_Gitlab_Branch_hotfix(1d562561)_release/xxxx-ios/Podfile:91:in `block (2 levels) in from_ruby'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/d7test/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'

Podfile:
require 'fileutils'
FileUtils.cp_r('Pods/Target Support Files/Pods-sbi_nbapp/Pods-sbi_nbapp-acknowledgements.plist', 'sbi_nbapp/Settings.bundle/Acknowledgements.plist', :remove_destination => true)

require './plist/plist'
acknowPath = File.join(File.dirname(__FILE__), "xxxx/Settings.bundle/Acknowledgements.plist")
acknow = Plist.parse_xml(acknowPath)
customPath = File.join(File.dirname(__FILE__), "xxxx/Settings.bundle/Licenses.plist")
custom = Plist.parse_xml(customPath)
for item in custom["PreferenceSpecifiers"]
    acknow["PreferenceSpecifiers"].push(item)
end
Plist::Emit.save_plist(acknow, acknowPath, { :indent => "" })  
end

Comment out “Plist::Emit.save_plist(acknow, acknowPath, { :indent => "" })  ”
There will be no problems
Can anyone help me solve this problem?

When set to platform: ios, '12.0' there will be problems

**Comment by dnkoutso** [comment]
This seems like an issue in your custom post install hook in the Podfile.

Its very hard to diagnose this issue report. Please file one filling in the issue template. Going to preemptively close.
