### ISSUE TITLE
`ruby-macho` dependency fails to read some dylibs

### ISSUE THREAD

**Issue by PeqNP** [CocoaPods/CocoaPods#10390]
One of our 3rd party xcframeworks can not be read by the version of `ruby-macho` (~1.4) that cocoapods depends on. When I `puts` the error that `MachO` provided it returned the following error:

```
Unrecognized Mach-O load command: 0x80000034
```

The effect is that the 3rd party xcframework does not get its respective `install_framework` line added in the targets `Pods-mytarget-frameworks.sh` file. This causes the app to crash as it can't load the library on app launch.

It produces the same error on cocoapods v1.8 and v1.10.1. I was able to determine a working version of the lib by copying the code from `def dynamic_library?` into a `test.rb` script, updating the version of `ruby-macho` to the latest (which is 2.5), and then running `test.rb`.

Bundler does not provide a way to override this dependency. Therefore, my options are to either fork cocoapods, and possibly other dependencies that require this version, and update the respective `Gemfile` (no thanks) or pray that some kind soul can at least help me determine which project's `Gemfile` needs to be updated. I've looked at the cocoapods's `Gemfile` and several other dependencies and could not find the declaration.

**Comment by dnkoutso** [comment]
Thanks for the report! Cocoapods gemspec shows:
```ruby
s.add_runtime_dependency 'ruby-macho',    '~> 1.4'
```

Is there any version until 2.0 that fixes the issue or is it fixed only in 2.x and above?

**Comment by PeqNP** [comment]
I have no idea how I missed that. I am so sorry. I'll see if I can find it and update it. Thank you so much!

**Comment by dnkoutso** [comment]
@PeqNP looks like there is no other version above 1.4 fo ruby-macho. it goes straight to 2.0.

The only thing to do here is for us to update cocoapods to work with 2.x version or if you fork and change the gemspec.

**Comment by PeqNP** [comment]
@dnkoutso thank you so much. I was able to fix the problem with the following procedure.

- Fork `cocoapods`
- Checkout the `1.10.1` tag
- Make the modification to switch `ruby-macho` to 2.5
- Created a new tag `1.10.1nb` ("nb" stands for "Nordstrom Best". Long story)
- Updated `Gemfile` and added line: `gem "cocoapods", :git => "https://github.com/PeqNP/CocoaPods", :tag => "1.10.1nb"`
- `pod install`

I now see the `install_framework` line in the respective bash script. Yay!

I would love to see this fix in a future version of cocoapods so that I don't have to maintain a fork. I did a cursory glance in the project and found that only a single file is referencing `MachO`, `xcode/linkage_analyzer.rb`. It seems like a low risk change? Of course it's rarely that easy. Hard to tell what the consequences may be if you bump up to a major version.

I hope this helps someone else. I'm happy to make the change. I don't know if a contribution is necessary as it's such a simple change. I'm happy to submit a PR. Let me know.

**Comment by dnkoutso** [comment]
Yes lets change it! can make it `> 1.0, < 3.0` perhaps if both 1.x and 2.x works.

**Comment by guzuqing** [comment]
I encountered a similar problem where a dynamic library cannot be installed into an IPA file. I believe that when CocoaPods is checking if a binary file is a dynamic library, it uses MachO.open(binary).dylib?. When an error is thrown, the entire installation process should fail instead of simply assuming that the library is non-dynamic.


sourcecode  in linkage_analyzer.rb
require 'macho'

module Pod
  module Xcode
    class LinkageAnalyzer
      # @param  [Pathname] binary
      #         The file to be checked for being a dynamic Mach-O binary.
      #
      # @return [Boolean] Whether `binary` can be dynamically linked.
      #
      def self.dynamic_binary?(binary)
        @cached_dynamic_binary_results ||= {}
        return @cached_dynamic_binary_results[binary] unless @cached_dynamic_binary_results[binary].nil?
        return false unless binary.file?

        @cached_dynamic_binary_results[binary] = MachO.open(binary).dylib?
      rescue MachO::MachOError
        @cached_dynamic_binary_results[binary] = false
      end
    end
  end
end


 rescue MachO::MachOError should raise an error !!!!

**Comment by guzuqing** [comment]
Unrecognized Mach-O load command: 0x80000034

This error typically occurs in Mach-O files compiled with older toolchains or compilers because these files may contain load commands that the current version of the toolchain cannot recognize. When the iOS SDK continues to upgrade, this problem can become a long-term and persistent issue.
