### ISSUE TITLE
Error installing pod for google ad mob sdk on M1 MacBook Pro

### ISSUE THREAD

**Issue by ExtraExaByte** [CocoaPods/CocoaPods#10400]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ I ran 'pod init' 
added the google admob sdk extension
Saved the pod file and ran:
pod 'install'

## What did you expect to happen?

have google admob pod install

## What happened instead?

I was told that an error occurred with this link 
https://github.com/CocoaPods/CocoaPods/search?q=dlsym%280x7f9e63fd82e0%2C+Init_ffi_c%29%3A+symbol+not+found+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.0.1 (20B29)
       Xcode : 12.4 (12D4e)
         Git : git version 2.23.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 'MyAppUI'
	pod 'Google-Mobile-Ads-SDK'


  target 'MyAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppUIUITests' do
    # Pods for testing
  end

end
```

**Comment by dnkoutso** [comment]
This does not appear a valid issue report. Please fill in all necessary information.

**Comment by dnkoutso** [comment]
Please include a stack trace and if possible a sample app.
