### ISSUE TITLE
Don't have /bin in your PATH, gem executables will not run.

### ISSUE THREAD

**Issue by CodeKing09** [CocoaPods/CocoaPods#10404]
# Report

## What did you do?

User-Install CocoaPods, `gem install cocoapods --user-install`

## What did you expect to happen?

Install CocoaPods for my user.

## What happened instead?

`WARNING:  You don't have /Users/yolo/.gem/ruby/2.6.0/bin in your PATH,
	  gem executables will not run.
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted @ apply2files - /Users/yolo/.gem/ruby/2.6.0/gems/ffi-1.14.2/CHANGELOG.md`

**Comment by dnkoutso** [comment]
This does not seem an issue with coocapods but rather with your Ruby environment.
