### ISSUE TITLE
Can't run rspec to validate specs

### ISSUE THREAD

**Issue by prohoney** [CocoaPods/CocoaPods#10417]
Hi there,

I’ve tried to start a contribution a few times, I’m still stuck at the roots.
Here’s roughly what I’ve done:

- Cloned cocoapods repo 
- Ran `bundle install`
- FWIW when I run`bundle config` it's all empty. 

- Then from the root directory I just run `rspec spec/functional/command_spec.rb` and that fails. Like all attempts to run rspec fail for me on the project. 
I tried a bunch of solutions on SO, cloned again, went through multiple rspec tutorials. I can successfully run `rspec somefile.rb` and it works outside the repo, but I can’t figure out how to run the specs of the cocoapods repo. I get the following error: 
> /Library/Ruby/Gems/2.6.0/gems/rspec-core-3.10.0/lib/rspec/core/formatters.rb:212:in `require’: cannot load such file -- rspec/core/formatters/progress_formatter (LoadError)

Do I need to modify the Gemfile ? Or something?

**Comment by prohoney** [comment]
I figured the solution: 

See https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#pull-requests and
https://guides.cocoapods.org/contributing/contribute-to-cocoapods.html

```
bundle exec bacon spec/functional/command_spec.rb
```
Or just do `bundle exec rake spec`

**Comment by dnkoutso** [comment]
Yes CocoaPods uses bacon to run its tests.

Will close for now.
