### ISSUE TITLE
How do I upgrade my firebase?

### ISSUE THREAD

**Issue by martianma** [CocoaPods/CocoaPods#10421]
The following pod updates are available:
- Bugly 2.5.5 -> 2.5.5 (latest version 2.5.71)
- Firebase 6.34.0 -> (unused) (latest version 7.6.0)
- FirebaseAnalytics 6.9.0 -> 6.9.0 (latest version 7.6.0)
- FirebaseCore 6.10.4 -> 6.10.4 (latest version 7.6.0)
- FirebaseCoreDiagnostics 1.7.0 -> 1.7.0 (latest version 7.6.0)
- FirebaseInstallations 1.7.0 -> 1.7.0 (latest version 7.6.0)
- FirebaseInstanceID 4.8.0 -> 4.8.0 (latest version 7.6.0)
- FirebaseMessaging 4.7.1 -> 4.7.1 (latest version 7.6.0)
- GoogleAppMeasurement 6.9.0 -> 6.9.0 (latest version 7.6.0)
- GoogleDataTransport 7.5.1 -> 7.5.1 (latest version 8.2.0)
- GoogleUtilities 6.7.2 -> (unused) (latest version 7.2.2)
- nanopb 1.30906.0 -> 1.30906.0 (latest version 2.30907.0)
- Protobuf 3.14.0 -> 3.14.0 (latest version 4.0.0-rc1)

pod update Firebase/Core 
not work

**Comment by martianma** [comment]
cocoapods-1.10.1

**Comment by paulb777** [comment]
The Podfile.lock should show what is restricting the update.

**Comment by martianma** [comment]
- Firebase/Analytics (6.34.0):
    - Firebase/Core
  - Firebase/Core (6.34.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 6.9.0)
  - Firebase/CoreOnly (6.34.0):
    - FirebaseCore (= 6.10.4)
  - Firebase/Messaging (6.34.0):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 4.7.1)
  - FirebaseAnalytics (6.9.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.7)
    - GoogleAppMeasurement (= 6.9.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - FirebaseCore (6.10.4):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - FirebaseInstallations (1.7.0):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - PromisesObjC (~> 1.2)
  - FirebaseInstanceID (4.8.0):
    - FirebaseCore (~> 6.10)
    - FirebaseInstallations (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
  - FirebaseMessaging (4.7.1):
    - FirebaseCore (~> 6.10)
    - FirebaseInstanceID (~> 4.7)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Reachability (~> 6.7)
    - GoogleUtilities/UserDefaults (~> 6.7)
    - Protobuf (>= 3.9.2, ~> 3.9)
  - GoogleAppMeasurement (6.9.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/MethodSwizzler (~> 6.7)
    - GoogleUtilities/Network (~> 6.7)
    - "GoogleUtilities/NSData+zlib (~> 6.7)"
    - nanopb (~> 1.30906.0)
  - GoogleDataTransport (7.5.1):
    - nanopb (~> 1.30906.0)

This file is very complicated, I don't think it should be changed directly like this, right?

**Comment by martianma** [comment]
What is the best way to do this?

**Comment by paulb777** [comment]
Map the versions requested in the Podfile to the requirements to the dependencies shown in the Podfile.lock.  

This isn't a CocoaPods issue and really should be brought up as a stackoverflow question.
