### ISSUE TITLE
Embed Pods Framework input/output files are redundant (and cause issues sometimes)

### ISSUE THREAD

**Issue by Air-Craft** [CocoaPods/CocoaPods#10422]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

On our CI, Fastlane is generating an error: 

```
build error: unable to spawn process '/bin/sh' (Argument list too long)
```

...for the **Embed Pods Frameworks** script.

Upon investigation, I see that the reason is likely that my project now has about 100 framework dependencies which are listed in the **Input Files** section, and then again for **Output Files**.  

But when I peak inside CP's script, it doesn't reference these input/output files (via `SCRIPT_INPUT_FILE_[N]` etc) but hard codes them into the script, meaning these values in xcode's Build Phase are redundant.

## What did you expect to happen?

I'd expect the Input Files and Output Files section to be empty as they are hardcoded into the script.

## What happened instead?

They are listed there redundantly

## CocoaPods Environment

```
CocoaPods : 1.10.0
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G73)
       Xcode : 12.2 (12B45b)
         Git : git version 2.30.0
Ruby lib dir : /Users/HKS/.rvm/rubies/ruby-2.6.5/lib
Repositories : NutrinoPodSpecs - git - git@github.com:Comocomo/NutrinoPodSpecs.git @ f4826a625708c518ae4cee7297cbfc878be73241

               trunk - CDN - https://cdn.cocoapods.org/
```

## Other

Sorry I can't share the project.  I'm wondering whether in the meantime there is something I can add to my Podfile to remove these redundant fields in the Build Phase?

Thx!

**Comment by Air-Craft** [comment]
Answer to that last question:

```
post_integrate do  |installer|
    project =  installer.aggregate_targets[0].user_project
    target = project.targets.find { |t| t.name.include? 'MyTarget'}
    phase = target.build_phases.find { |p| p.display_name == '[CP] Embed Pods Frameworks' }
    phase.input_paths = []
    phase.output_paths = []
    project.save
end
```

**Comment by HelloCore** [comment]
> Answer to that last question:
> 
> ```
> post_integrate do  |installer|
>     project =  installer.aggregate_targets[0].user_project
>     target = project.targets.find { |t| t.name.include? 'MyTarget'}
>     phase = target.build_phases.find { |p| p.display_name == '[CP] Embed Pods Frameworks' }
>     phase.input_paths = []
>     phase.output_paths = []
>     project.save
> end
> ```

I also found this problem. 
After digging to cocoapods source code, I found that if you change project format to `Xcode 9.3-compatible` or higher, and run pod install again, it would use **Input File Lists** instead of **Input Files**.

**Comment by dnkoutso** [comment]
Input File lists vs Input Files shouldnt make a difference. Its an optimization and simplicity and reduces the amount of entries to avoid `ARG_MAX`.

i do not understand the issue. Cocoapods does not need to use `SCRIPT_INPUT_FILE_[N]` etc. The input paths are known and the output paths are also known.

You can also use `:disable_input_output_paths` installation option.

**Comment by dnkoutso** [comment]
Or use xcfilelists with Xcode 9.3 and above.
