### ISSUE TITLE
Pod installation issue failure on Apple M1 MacBook Pro

### ISSUE THREAD

**Issue by Ravvoshift** [CocoaPods/CocoaPods#10428]
THIS IS EXACTLY WHAT IS BEING DISPLAYED WHEN I TRIED TO INTEGRATE COCOAPODS IN AN OS APPLICATION ON XCODE. WHELP!!

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlsym%280x7fa737697980%2C+Init_ffi_c%29%3A+symbol+not+found+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

[!] Automatically assigning platform `iOS` with version `14.0` on target `Logmate Logistics` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by dnkoutso** [comment]
This issue report is not actionable. We also track M1 support here https://github.com/CocoaPods/CocoaPods/issues/9907.
