### ISSUE TITLE
Help am new problem with pod install

### ISSUE THREAD

**Issue by Tami-TA** [CocoaPods/CocoaPods#10449]
Have this problem
[!] CocoaPods could not find compatible versions for pod "Firebase/core":

In Podfile:

Firebase/core

None of your spec sources contain a spec satisfying the dependency: `Firebase/core`.

You have either:

* out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.

* mistyped the name or version.

* not added the source repo that hosts the Podspec to your Podfile.

[!] Automatically assigning platform `iOS` with version `14.3` on target `Spacechat` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by paulb777** [comment]
BTW, `Firebase/Core` is no longer recommended usage. Instead, directly specify the needed Firebase libraries. See https://firebase.google.com/docs/ios/setup#available-pods
