### ISSUE TITLE
Error running project in flutter

### ISSUE THREAD

**Issue by rubenteste** [CocoaPods/CocoaPods#10456]
Hi,
I'm trying to run flutter in mac. If i create project with "flutter create new_proj" it works 100%.
But when i start develop the project and run it in the emulator it give me erros:

[!] Oh no, an error occurred.

    Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=dlsym%280x7fb74c923f00%2C+Init_ffi_c%29%3A+symbol+not+found+-+%2FLibrary
    %2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues

    If none exists, create a ticket, with the template displayed above, on:
    https://github.com/CocoaPods/CocoaPods/issues/new

    Be sure to first read the contributing guide for details on how to properly submit a ticket:
    https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

    Don't forget to anonymize any private data!

    Looking for related issues on cocoapods/cocoapods...
    Found no similar issues. To create a new issue, please visit:
    https://github.com/cocoapods/cocoapods/issues/new

Error running pod install
Error launching application on iPhone 12 Pro Max.

**Comment by dnkoutso** [comment]
Please file an issue with Flutter repo.
