### ISSUE TITLE
pod trunk push a library that has dependency on SPM package

### ISSUE THREAD

**Issue by liuxuan30** [CocoaPods/CocoaPods#10463]
Hi there,

I have searched for a while and couldn't get a clear answer, does pod / podspec support adding a dependency that is a Swift package manager source?

e.g. our framework has been long on pod, and recently, we have adopted apple-algorithm into the framework, which is a SPM package: https://github.com/apple/swift-algorithms

in our podspec, I'm not sure if I could add package as a depedency and what's the format:
e.g. I'm looking for something like
```
spec.dependency.source 'https://github.com/apple/swift-algorithms'
s.dependency 'swift-algorithms'
```

**Comment by dnkoutso** [comment]
Not at this time. But you can create and publish your own podspec of this repo into an internal cocoapods repo of yours.

**Comment by dnkoutso** [comment]
going to close at this time.

**Comment by dnkoutso** [comment]
We can continue discussion here and happy to re-open if we get into a more thorough proposal.

**Comment by liuxuan30** [comment]
thanks. I would hope pod could support importing SPM depencenies, as nowadays, it seems popular to use SPM.

**Comment by yuriisamoienko** [comment]
+1 we desperately need this feature
