### ISSUE TITLE
Error 'The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.'

### ISSUE THREAD

**Issue by safield** [CocoaPods/CocoaPods#10487]
I am running the archive process of my flutter app in xcode.

The build is failing with 'The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.'.

To attempt to resolve the issue I have run the following commands in order...

```
sudo gem install cocoa-pods
pod deintegrate
pod clean
pod setup
pod install
pod update
```

After all this, the archive process fails with the same error.

**Comment by dnkoutso** [comment]
Please upload a sample app _without_ Flutter that demonstrates the issue and with clear instructions. i can re-open this once you do so.
