### ISSUE TITLE
UUID Issues with CocoaPods on macOS Big Sur for Flutter on Android Studio.

### ISSUE THREAD

**Issue by MuhammadMalik22** [CocoaPods/CocoaPods#10482]
Hey everyone! So I was having some issues with the CocoaPods for Flutter on Android Studio. Im currently working on the Big Sur OS. The issue I was having is. 
`Error output from CocoaPods:
↳

    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID. `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and the unknown UUID is being discarded.`

Does anyone know what this mean and what I should do for this. Thanks so much.

**Comment by daniilshumkoidt** [comment]
@MuhammadMalik22 this is most likely not related to CocoaPods but Flutter itself. Try removing your `ios` folder from your Flutter project and run `flutter create .` which is going to regenerate the iOS project with the correct configuration.

**Comment by daniil-shumko** [comment]
@MuhammadMalik22 this is most likely not related to CocoaPods but Flutter itself. Try removing your `ios` folder from your Flutter project and run `flutter create .` which is going to regenerate the iOS project with the correct configuration.

**Comment by dnkoutso** [comment]
Yes please file an issue with Flutter. If you believe this is related to cocoapods then please remove flutter and upload a sample app demonstrating the issue _without_ Flutter in this repo.

**Comment by MuhammadMalik22** [comment]
I ran `flutter create` in terminal and the response that I got was `zsh: command not found: flutter`. What should I do now?

**Comment by daniil-shumko** [comment]
@MuhammadMalik22 it looks like you don't have Flutter installed on your machine. Please follow the official guide on how to properly install Flutter. And any issue related to Flutter should be opened on the Flutter's repo.
