### ISSUE TITLE
'pod install' takes forever

### ISSUE THREAD

**Issue by squm** [CocoaPods/CocoaPods#10494]
## What did you do?

`pod install`

## What happened

it took 4 hours, 41 minutes, 10 seconds to complete

```
Analyzing dependencies
  CDN: trunk Relative path: Specs/0/3/5/Firebase/1.0.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
<...>
  CDN: trunk Relative path: Specs/0/3/5/Firebase/7.7.0/Firebase.podspec.json exists! Returning local because checking is only perfomed in repo update
```

I've noticed it iterates over each version from 0 to latest, during that time `ruby` hits 100% CPU load for its single thread

**Comment by dnkoutso** [comment]
not sure what the issue here is and the information supplied here is very thin. Please open a new issue with more information and debugging the network performance to help us diagnose.
