### ISSUE TITLE
I have a framework with two versions debug and release

### ISSUE THREAD

**Issue by BrunoDLL** [CocoaPods/CocoaPods#10499]
I have a framework with two versions debug and release, how do I add a differentiation between these two versions?

my podspec:
  s.dependency 'MyFramework'

podspec of my MyFramwork:
  s.vendored_frameworks = 'MyFramwork.framework'

podfile example:
  pod 'MyLibrary',: path => '../'
  pod 'MyFramwork',: path => '../MyFramwork'

now my framework are two files:
MyFramwork_release
MyFramwork_debug

thanks for the help

**Comment by dnkoutso** [comment]
You have to nam them differently.

See this issue https://github.com/CocoaPods/CocoaPods/issues/101062 which also has a fix for 1.11.0.
