### ISSUE TITLE
pod install: Stuck at "Generating deterministic UUIDs"

### ISSUE THREAD

**Issue by mrousavy** [CocoaPods/CocoaPods#10506]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I ran `pod install`

I have also tried to clean _everything_:

```sh
rm -rf node_modules
rm -rf yarn.lock
rm -rf package-lock.json

rm -rf ~/Library/Caches/CocoaPods
rm -rf ios/Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*

cd ios
pod deintegrate
pod setup
yarn
pod install
```

## What did you expect to happen?

I expect it to install pods and generate the project successfully.

## What happened instead?

Instead, it gets stuck at:

```
Integrating target `OpenSSL-Universal`
    Adding Build Phase '[CP] Copy XCFrameworks' to project.
  - Generating deterministic UUIDs
```

(That's the `Generating Pods project` step)

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.2 (20D80)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

[VisionCamera example](https://github.com/cuvent/react-native-vision-camera/tree/main/example) (podspec [here](https://github.com/cuvent/react-native-vision-camera/blob/main/VisionCamera.podspec), library pbxproj [here](https://github.com/cuvent/react-native-vision-camera/blob/main/ios/VisionCamera.xcodeproj/project.pbxproj) and example app's pbxproj [here](https://github.com/cuvent/react-native-vision-camera/blob/main/example/ios/VisionCameraExample.xcodeproj/project.pbxproj))

**Comment by mrousavy** [comment]
☹️

**Comment by mrousavy** [comment]
@alloy do you have an idea what might be wrong here?

**Comment by therealkh** [comment]
have the same problem after updating to macOS 11.3 Apple Silicon M1

**Comment by vishalnarkhede** [comment]
Same here!!

**Comment by pktippa** [comment]
@mrousavy did you found any workaround, as @therealkh said, after updating to macOS 11.3 on Apple Silicon M1, I started to face the same issue. Please suggest.

**Comment by andreialecu** [comment]
Bunch of us hitting this issue with a recent Flipper update here: https://github.com/facebook/flipper/issues/2248

**Comment by pktippa** [comment]
@smenke if you are running a react-native project, check this https://github.com/facebook/flipper/issues/2248#issuecomment-830060572 this worked for me on my macOS 11.3

**Comment by smenke** [comment]
> @smenke if you are running a react-native project, check this [facebook/flipper#2248 (comment)](https://github.com/facebook/flipper/issues/2248#issuecomment-830060572) this worked for me on my macOS 11.3

I am running a react-native project & that fixed this issue! Thank you so much! On to fixing the other issue that cropped up after macOS to 11.3.

**Comment by whenmoon** [comment]
Same here, Apple M1, disaster.

**Comment by pktippa** [comment]
@whenmoon not necessarily M1 issue, my colleague faced same issue with macOS Catalina 10.5.7 on Intel Mac too. Looks like it is Flipper issue.

**Comment by yxibng** [comment]
same issue, Apple M1, help me

![image](https://user-images.githubusercontent.com/45938609/123056298-589f6e80-d439-11eb-8323-e3fd5f9f742f.png)
![image](https://user-images.githubusercontent.com/45938609/123056361-6c4ad500-d439-11eb-9120-4ca57cce14c5.png)
![image](https://user-images.githubusercontent.com/45938609/123056504-8edcee00-d439-11eb-8927-44fc8d7e9a3f.png)

**Comment by dnkoutso** [comment]
Closing as a Facebook Flipper issue.
