### ISSUE TITLE
Rsync resources in Pods-resouces.sh is too slow

### ISSUE THREAD

**Issue by onato** [CocoaPods/CocoaPods#1050]
I have decreased the time it takes to run Pods-resouces.sh on my project from **26 seconds** to **6 seconds**.

I have a lot of resources so the bottleneck is the rsync commands that copy the resources. 

This can be sped up by issuing just one rsync command ( **rsync --files-from** ). I have modified my Pods-resouces.sh script as follows

```
RESOURCES_TO_COPY=${PODS_ROOT}/resources-to-copy.txt
install_resource()
{
…
    *)
      echo "${PODS_ROOT}/$1" >> "$RESOURCES_TO_COPY"
      #rsync -av --exclude '*/.svn/*' "${PODS_ROOT}/$1" "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
      ;;
…
install_resource 'blah1/blah.png'
install_resource 'blah2.png'
…
rsync -avr --no-relative --exclude '*/.svn/*' --files-from="$RESOURCES_TO_COPY" / "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
rm "$RESOURCES_TO_COPY"
```

Can you please implement something like this to speed up the build time?

**Comment by cyborch** [comment]
I replaced the script entirely with a makefile which ensures that only the files which were updated gets copied. That improved my build times from ~20s to ~4s.

**Comment by zzzworm** [comment]
> I replaced the script entirely with a makefile which ensures that only the files which were updated gets copied. That improved my build times from ~20s to ~4s.
Can you give a example to explain how to write the makefile?
