### ISSUE TITLE
getting error while running pod install

### ISSUE THREAD

**Issue by vbokhonov** [CocoaPods/CocoaPods#10513]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I was trying to run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

An error occurred.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.2 (20D80)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'WWDC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WWDC
  pod 'Firebase/Database'

end
```

## Project that demonstrates the issue

An error details could be found in attached file.

[err.zip](https://github.com/CocoaPods/CocoaPods/files/6127776/err.zip)

Thank you in advance for your help.

**Comment by dnkoutso** [comment]
looks like `ffi` gem installation issue. Please see similar issue reports on how to successfully install `ffi` gem.
