### ISSUE TITLE
running pod install does not generate Podifile.lock and displays the message: Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.  [!] The Podfile does not contain any dependencies.

### ISSUE THREAD

**Issue by sassneto** [CocoaPods/CocoaPods#10511]
Mac-mini-de-BOSS:ios boss$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.14.6 18G7016 darwin-x64,
    locale pt-BR)
    • Flutter version 2.0.1 at /Applications/flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/boss/Library/Android/sdk/
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/boss/Library/Android/sdk/
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ! Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82

My Podfile:
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end

Podfile.lock:
PODFILE CHECKSUM: 5ada3782c16649731dd16e7a93753acb0d5d4856

COCOAPODS: 1.10.1

My pub spec:
name: flutter_app01
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_signin_button: ^0.2.6 #1.1.0
  google_sign_in: ^4.1.1 #4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

**Comment by dnkoutso** [comment]
Please paste this issue to Flutter.

**Comment by sassneto** [comment]
I'm new here, I didn't understand.
