### ISSUE TITLE
CocoaPods finding old ruby, this makes the build fail when pod install on M1 Mac

### ISSUE THREAD

**Issue by SJang1** [CocoaPods/CocoaPods#10512]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
It is connected with https://github.com/ffi/ffi/issues/870

If you run into this problem, great way fix for now is using rvm and use higher version of ruby(ex: 3.0.0).
 
## What did you do?
1. Install ruby via homebrew `brew install ruby` (This installed ruby 3.0.0p0)
2. add new ruby installed by homebrew using `echo 'export PATH="/opt/homebrew/opt/ruby/bin:$PATH"' >> ~/.zshrc`
3. Run `pod install`

2-1. Also tried with this flags, it also happened. (Nothing changed)
```
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/ruby/lib/pkgconfig"
```

## What did you expect to happen?
Ruby installed with homebrew will be used.

## What happened instead?
It still used `ruby 2.6.3p62` that is installed in `/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib`
Not used `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]` is used. (Which I installed with homebrew, and if I run `ruby -v` also `ruby 3.0.0p0` comes out. only cocoapod using old ruby version.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue
Also not on the project. (when just run `pod env` out of project)

I was also trying https://github.com/bitgapp/eqMac
because of this issue, `pod install` fails.

**Comment by rastapasta** [comment]
``/usr/local/bin/pod`` was most likely put in place by your old ruby's gem - make sure to reinstall CocoaPods with homebrew's gem and add your new ruby's gems' binary folder to your path: ``/opt/homebrew/lib/ruby/gems/3.0.0/bin``

**Comment by rastapasta** [comment]
To validate this assumption,  check the shebang at your referenced executable path:
```sh
$ head -n 1 /usr/local/bin/pod
```
It'll most likely return ```#!/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby``` in which case upper assumption validates and this issue being able to be marked as resolved.

**Comment by garrettApproachableGeek** [comment]
For future readers I was in this exact place. The solution was to remove `pod` from `/usr/local/bin/pod` and then the `pod` version from `brew install cocoapods` was able to be picked up

**Comment by nsourov** [comment]
> For future readers I was in this exact place. The solution was to remove `pod` from `/usr/local/bin/pod` and then the `pod` version from `brew install cocoapods` was able to be picked up

This worked perfectly! Thanks @garrettApproachableGeek

**Comment by indiealexh** [comment]
> brew install cocoapods

Actual godsend thanks you! @garrettApproachableGeek
