### ISSUE TITLE
Cocoapod missing required architecture x86_64 & i386

### ISSUE THREAD

**Issue by MohammadJahirul** [CocoaPods/CocoaPods#10527]
<img width="1534" alt="Screen Shot 2021-03-18 at 12 01 05 PM" src="https://user-images.githubusercontent.com/17243074/111580519-d96b2080-87e1-11eb-8885-79bc88c70f61.png">

ℹ It tells me one of my frameworks missing required architecture.  ℹ I have attached the screenshot, I am stuck for 2 to 3 days. Dou you have its solution.

**Comment by dnkoutso** [comment]
sorry this is not a sufficient issue report. Please file a new issue by filling in the template and provide a sample app demonstrating the issue.
