### ISSUE TITLE
Unable to find matching .xcframework slice in framework for the current build architectures (x86_64 i386)

### ISSUE THREAD

**Issue by MediametrieDev** [CocoaPods/CocoaPods#10523]
* [ x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod spec lint

## What did you expect to happen?

That the spec pass the validation before pushing to cocoapod

## What happened instead?

The spec did not pass validation due to 1 error

    - NOTE  | [iOS] xcodebuild:  warning: [CP] Unable to find matching .xcframework slice in 'MyFramework/MyFramework.xcframework MyFramework framework ios-arm64 ios-arm64_x86_64-maccatalyst ios-arm64_x86_64-simulator' for the current build architectures (x86_64 i386).
    - NOTE  | xcodebuild:  ld: warning: directory not found for option '-F/Users/adminlocal/Library/Developer/Xcode/DerivedData/App-bddjaxvbceslpcclpxeaetqeonai/Build/Products/Release-iphonesimulator/XCFrameworkIntermediates/MyFramework'
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 285be86e90757b00be85941f821a701a913cebf4

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```
Pod::Spec.new do |s|
  s.name             = 'StreamingTagSwift'
  s.version          = '6.0.0-tvOS'
  s.summary          = 'eStat iOS swift SDK'
  s.description      = 'Repository for eStat iOS swift framework.'
  s.homepage         = 'https://github.com/MediametrieDev/StreamingTagSwift'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Mediametrie' => 'support-mesure@mediametrie.fr' }
  s.source           = { :git => 'https://github.com/MediametrieDev/StreamingTagSwift.git', :tag => s.version, :branch => "master"  }
  s.vendored_frameworks = 'StreamingTagSwift.xcframework'
  s.ios.deployment_target = '10.2'
  s.tvos.deployment_target = '9.0'
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
end

```

## Project that demonstrates the issue

https://cocoapods.org/pods/StreamingTagSwift

I successfully push my framework on cocoapod, 20 days ago, with the version 6.0.0
I forget to add s.tvos.deployment_target in mypodspec, but the tvos framework is already in the xcframework
So I try to edit the podspec, increment the version, push to git, tag, push the tag (same as version) : the only modification I did is the podspec, I did not touch the xcframework
When I try to pod spec lint, it always fail with this line : 

Unable to find matching .xcframework slice in 'MyFramework/MyFramework.xcframework MyFramework framework ios-arm64 ios-arm64_x86_64-maccatalyst ios-arm64_x86_64-simulator' for the current build architectures (x86_64 i386).

**Comment by gpwdata** [comment]
Looks like I'm having exactly the same issue but with private pod. Only workaround that I found is downgrading cocoapods to 1.9.0 or 1.9.1.

**Comment by snowinszu** [comment]
same issue, any update?

**Comment by dnkoutso** [comment]
this seems to be passing for me locally with master branch of CocoaPods (what would b 1.11.0).

command: `bundle exec pod lib lint StreamingTagSwift.podspec --verbose --no-clean`

output:

```
    ** BUILD SUCCEEDED ** [6.120 sec]
    
   Testing with `xcodebuild`. 
 -> StreamingTagSwift (7.1.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | xcodebuild:  note: Planning
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | [tvOS] xcodebuild:  ld: warning: dylib (/Users/dimitris/Library/Developer/Xcode/DerivedData/App-akywwigviuruunaucqaimyfbaaak/Build/Products/Release-appletvsimulator/XCFrameworkIntermediates/StreamingTagSwift/StreamingTagSwift.framework/StreamingTagSwift) was built for newer tvOS Simulator version (14.5) than being linked (10.2)
    - NOTE  | [tvOS] xcodebuild:  ld: warning: dylib (/Users/dimitris/Library/Developer/Xcode/DerivedData/App-akywwigviuruunaucqaimyfbaaak/Build/Products/Release-appletvsimulator/XCFrameworkIntermediates/StreamingTagSwift/StreamingTagSwift.framework/StreamingTagSwift) was built for newer tvOS Simulator version (14.5) than being linked (14.0)

Pods workspace available at `/var/folders/g7/83vp4gbx2q58k1wd02f17b4r0000gn/T/CocoaPods-Lint-20210806-49640-1charun-StreamingTagSwift/App.xcworkspace` for inspection.

StreamingTagSwift passed validation.
```

**Comment by dnkoutso** [comment]
can you please try the master branch and verify it works for you vs 1.10.2? its possible this bug is fixed now.

**Comment by Marqueurs** [comment]
I edited many thing since march, but finally I solved this problem when I add thoses lines into my podspec file

  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }


Here's my entire podfile for my project version 7.1.0  : https://github.com/MediametrieDev/StreamingTagSwift/blob/master/StreamingTagSwift.podspec

**Comment by dnkoutso** [comment]
OK going to close for now then.
