### ISSUE TITLE
Issue in pod install with cocopod 1.10.1

### ISSUE THREAD

**Issue by shwetha-mugeraya24** [CocoaPods/CocoaPods#10529]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

e.g. Run `pod install` with 1.10.1, previously I had 1.9.3 cocopod version

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

 dsym files are being removed from project file

## Project that demonstrates the issue

 I updated my local cocopod version to 1.10.1 and Run `pod install` with 1.10.1, previously I had 1.9.3 cocopod version. 
dsym files are being removed from project file. Is this expected behaviour ? is it ok to delete link to Dsym from project file from name = "[CP] Copy Pods Resources" and  name = "[CP] Embed Pods Frameworks";?

**Comment by dnkoutso** [comment]
That phase was moved to the libraries themselves as it was being an issue with Xcode's new build system causing duplicate output files.
