### ISSUE TITLE
This feature is available, via private specs repos, as we've mentioned multiple times in the thread.

### ISSUE THREAD

**Issue by konacurrents** [CocoaPods/CocoaPods#10526]
This feature is available, via private specs repos, as we've mentioned multiple times in the thread.

_Originally posted by @orta in https://github.com/CocoaPods/CocoaPods/issues/3276#issuecomment-257140162_

This thread confuses "end users" - those using Podfile, and "pod developers" - those using pod specs.  

So how can "pod developers" reference other pods that are privately built? 
I don't see where: "This feature is available, via private specs repos, as we've mentioned multiple times in the thread."

@segiddins sums up the private pod referencing other private pods "precisely the reason private specs repos exist"

thanks.

**Comment by dnkoutso** [comment]
This is not supported and that thread is very old. You cannot specify `path` for podspecs as they are published externally. there are no plans to support this feature anytime soon.
