### ISSUE TITLE
xxx.h file not found, version is 1.10.0

### ISSUE THREAD

**Issue by yownyang** [CocoaPods/CocoaPods#10520]
Information：
1. I use local pod and remote pod。
2. Local pod in Podfile is local path, like "path=>../../xxx"。Remote pod in Podfile is url, like "git => http://xxx.git"。
3. Import local pod to remote pod。
4. "pod install" succeed on 1.10.0 version。
5. When I build project, raise error：xxx.h file not found。

Question:
1. Why the same code and config is good on 1.5.3 version?
2. How can I use local pod in remote pod?

**Comment by dnkoutso** [comment]
This is not a complete issue report. Please re-file with a sample app demonstrating the issue and clear instructions.
