### ISSUE TITLE
How to solve the error 'The bundle at XX.framework' contains disallowed file 'Frameworks'

### ISSUE THREAD

**Issue by magic3584** [CocoaPods/CocoaPods#10538]
## What did you do?

Build a dynamic framework

## What happened instead?
It show errors when upload to App Store
**"Invalid Bundle. The bundle at 'Demo.app/Frameworks/MyFramework.framework' contains disallowed nested bundle." 
"Invalid Bundle. The bundle at 'Demo.app/Frameworks/MyFramework.framework' contains disallowed file 'Frameworks'."** 

### Stack

```
   CocoaPods : 1.10.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
               master - git - https://github.com/CocoaPods/Specs.git @ 51ea42a677550c61ce72f6b5699e8c294a0d6e3a

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.4
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.5.0
cocoapods-try          : 1.2.0
cocoapods-yunduo-bulid : 1.0.0
```
## Project that demonstrates the issue

Here is the question on StackOverflow:https://stackoverflow.com/questions/66745136/how-to-solve-the-error-the-bundle-at-xx-framework-contains-disallowed-file-fr

**Comment by dnkoutso** [comment]
Please provide a sample app for us to diagnose.

**Comment by magic3584** [comment]
Solved.
