### ISSUE TITLE
Wrong Pods_${TARGET_NAME}.framework when it contains acute accent

### ISSUE THREAD

**Issue by brennobemoura** [CocoaPods/CocoaPods#10533]
* [ x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Create a Xcode target like "Óbvio App"
Run `pod install`

## What did you expect to happen?

That Cocoapods imports correctly the Pods_Óbvio_App.framework

## What happened instead?

It has generated the Pods_Óbvio_App.framework, but imported Pods__bvio_App.framework

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]
    RubyGems : 3.2.15
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.4 (12D4e)
         Git : git version 2.31.0
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.0.0_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

Not provided yet.

**Comment by dnkoutso** [comment]
Yes I have seen this before, PR would be nice with a test! Does Xcode vanilla support those characters?
