### ISSUE TITLE
M1 pod 执行报错

### ISSUE THREAD

**Issue by houshixian** [CocoaPods/CocoaPods#10550]
M1 MacBookPro  cocoaPods  pod search xxx 时出错，麻烦有遇到的大神帮忙解决下 🙏🙏🙏

<img width="1434" alt="截屏2021-03-30 下午6 14 43" src="https://user-images.githubusercontent.com/18547388/112973391-da0d9a80-9183-11eb-9aa6-2d019a4b8e4a.png">

**Comment by ccdwyer** [comment]
https://github.com/CocoaPods/CocoaPods/issues/10408 It's related to this issue.

**Comment by DeraDream** [comment]
兄die解决没，我也遇到了
