### ISSUE TITLE
When I ran pod install in the repository it gives me errors

### ISSUE THREAD

**Issue by jessicapeng** [CocoaPods/CocoaPods#10559]
When I ran pod install in the repository it gives me errors

This is the error it gives me: 

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[!] Oh no, an error occurred.
Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+missing+compatible+arch+in+%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle+-+%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues
If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new
Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
Don't forget to anonymize any private data!
Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
[!] Automatically assigning platform `iOS` with version `14.0` on target `spotio` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
jessicapeng@Jessicas-MBP spotio-iOS-App %

**Comment by dnkoutso** [comment]
This is not a valid issue report.
