### ISSUE TITLE
When i run pod install in react-native project, getting below error on macOS Big Sur

### ISSUE THREAD

**Issue by KishoreKumar-Techment** [CocoaPods/CocoaPods#10557]
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.2.15
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.1 (12A7403)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MEIS' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
#  pod 'Firebase/Messaging'
#  pod 'Firebase/Analytics'
#  pod 'Firebase/Core', '~> 7.6.0'


  pod 'react-native-video', :path => '../node_modules/react-native-video'

  target 'MEISTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'MEIS-tvOS' do
  # Pods for MEIS-tvOS

  target 'MEIS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

### Error

```
LoadError - dlopen(/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi_c.bundle, 0x0009): missing compatible arch in /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi_c.bundle - /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi_c.bundle
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `load'
/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+missing+compatible+arch+in+%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle+-+%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

[!] NPM package '@react-native-firebase/database' depends on '@react-native-firebase/app' v11.2.0 but found v10.8.1, this might cause build issues or runtime crashes.

[!] NPM package '@react-native-firebase/database' depends on '@react-native-firebase/app' v11.2.0 but found v10.8.1, this might cause build issues or runtime crashes.

**Comment by kirill-design** [comment]
> 
> 
> Analyzing dependencies
> 
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> 
> Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
> 
> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> 
> 
> 
> ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> 
> 
> ### Command
> 
> 
> 
> ```
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/bin/pod install
> 
> ```
> 
> 
> 
> ### Report
> 
> 
> 
> * What did you do?
> 
> 
> 
> * What did you expect to happen?
> 
> 
> 
> * What happened instead?
> 
> 
> 
> 
> 
> ### Stack
> 
> 
> 
> ```
> 
>    CocoaPods : 1.10.1
> 
>         Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
> 
>     RubyGems : 3.2.15
> 
>         Host : macOS 11.2.3 (20D91)
> 
>        Xcode : 12.1 (12A7403)
> 
>          Git : git version 2.24.3 (Apple Git-128)
> 
> Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
> 
> Repositories : 
> 
> ```
> 
> 
> 
> ### Plugins
> 
> 
> 
> ```
> 
> cocoapods-clean       : 0.0.1
> 
> cocoapods-deintegrate : 1.0.4
> 
> cocoapods-plugins     : 1.0.0
> 
> cocoapods-search      : 1.0.0
> 
> cocoapods-trunk       : 1.5.0
> 
> cocoapods-try         : 1.2.0
> 
> ```
> 
> 
> 
> ### Podfile
> 
> 
> 
> ```ruby
> 
> require_relative '../node_modules/react-native/scripts/react_native_pods'
> 
> require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
> 
> 
> 
> platform :ios, '10.0'
> 
> 
> 
> target 'MEIS' do
> 
>   config = use_native_modules!
> 
> 
> 
>   use_react_native!(:path => config["reactNativePath"])
> 
> #  pod 'Firebase/Messaging'
> 
> #  pod 'Firebase/Analytics'
> 
> #  pod 'Firebase/Core', '~> 7.6.0'
> 
> 
> 
> 
> 
>   pod 'react-native-video', :path => '../node_modules/react-native-video'
> 
> 
> 
>   target 'MEISTests' do
> 
>     inherit! :complete
> 
>     # Pods for testing
> 
>   end
> 
> 
> 
>   # Enables Flipper.
> 
>   #
> 
>   # Note that if you have use_frameworks! enabled, Flipper will not work and
> 
>   # you should disable these next few lines.
> 
>   # use_flipper!
> 
>   # post_install do |installer|
> 
>   #   flipper_post_install(installer)
> 
>   # end
> 
> end
> 
> 
> 
> target 'MEIS-tvOS' do
> 
>   # Pods for MEIS-tvOS
> 
> 
> 
>   target 'MEIS-tvOSTests' do
> 
>     inherit! :search_paths
> 
>     # Pods for testing
> 
>   end
> 
> end
> 
> ```
> 
> 
> 
> ### Error
> 
> 
> 
> ```
> 
> LoadError - dlopen(/opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi_c.bundle, 0x0009): missing compatible arch in /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi_c.bundle - /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi_c.bundle
> 
> /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
> 
> /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
> 
> /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
> 
> /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
> 
> /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
> 
> /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
> 
> /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
> 
> /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:85:in `require'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
> 
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `load'
> 
> /opt/homebrew/Cellar/cocoapods/1.10.1/libexec/bin/pod:23:in `<main>'
> 
> ```
> 
> 
> 
> ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> 
> 
> [!] Oh no, an error occurred.
> 
> 
> 
> Search for existing GitHub issues similar to yours:
> 
> https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+missing+compatible+arch+in+%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle+-+%2Fopt%2Fhomebrew%2FCellar%2Fcocoapods%2F1.10.1%2Flibexec%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues
> 
> 
> 
> If none exists, create a ticket, with the template displayed above, on:
> 
> https://github.com/CocoaPods/CocoaPods/issues/new
> 
> 
> 
> Be sure to first read the contributing guide for details on how to properly submit a ticket:
> 
> https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
> 
> 
> 
> Don't forget to anonymize any private data!
> 
> 
> 
> Looking for related issues on cocoapods/cocoapods...
> 
> Searching for inspections failed: undefined method `map' for nil:NilClass
> 
> 
> 
> [!] NPM package '@react-native-firebase/database' depends on '@react-native-firebase/app' v11.2.0 but found v10.8.1, this might cause build issues or runtime crashes.
> 
> 
> 
> [!] NPM package '@react-native-firebase/database' depends on '@react-native-firebase/app' v11.2.0 but found v10.8.1, this might cause build issues or runtime crashes.
> 
>

**Comment by lewis-smith** [comment]
Possibly to do with the way I installed pods, but I see this error if I run `pod update` on my M1 Mac natively. If I run it in Rosetta it works fine.

**Comment by jwstanly** [comment]
Think it's an Apple silicon issue. Ran this and got things working: 

```
arch -x86_64 pod deintegrate
arch -x86_64 pod install
arch -x86_64 pod update
```

Going forward I'm aliasing `pod="arch -x86_64 /usr/local/bin/pod"` to avoid arm vs x86 issues when dealing with CocoaPods

**Comment by dnkoutso** [comment]
see blog post https://betterprogramming.pub/ruby-on-apple-silicon-m1-macs-fb159849b2f5

This is a widely known `ffi` gem installation issue.
