### ISSUE TITLE
[BUG] CocoaPods flutter firebase plugin failed to compile [firebase_messaging]

### ISSUE THREAD

**Issue by maheshkumar2150** [CocoaPods/CocoaPods#10558]
I created two same projects in windows and macos.
Add the flutter plugins in both of them.

It is compiled successfully in windows.
But cocoapods throwing error

Please fix the bug.
I created an issue already and waiting for it without any reply.
Please it affects my production time.
What is the solution for it?

I have created the issue in Flutterfire also.
Please have a look at it. and please fix it.
https://github.com/FirebaseExtended/flutterfire/issues/5657

**Comment by dnkoutso** [comment]
This is not a valid issue report. please use the issue template and attach a sample app demonstrating the issue.
