### ISSUE TITLE
The 'Pods-ProjectName' target has libraries with conflicting names: libname.a

### ISSUE THREAD

**Issue by vitalybatrakov** [CocoaPods/CocoaPods#10567]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

I got the error: The 'Pods-ProjectName' target has libraries with conflicting names: libname.a

I have 2 pods in my project, that have the same .a library inside, but when i install pods i have this error. 

Stacktrace:
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:67:in `verify_no_duplicate_names'
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:58:in `block (2 levels) in verify_no_duplicate_framework_and_library_names'
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:48:in `each_key'
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:48:in `block in verify_no_duplicate_framework_and_library_names'
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:47:in `each'
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:47:in `verify_no_duplicate_framework_and_library_names'
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:590:in `validate_targets'
...vendor/bundle/ruby/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:158:in `install!'

Can you fix this problem, please?

## CocoaPods Environment

   CocoaPods : 1.9.3
        Ruby : ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 12.1 (12A7403)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/user/.rvm/rubies/ruby-2.6.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 51345fe374af77c374e20fd5df89d2d6e65a29cf

**Comment by dnkoutso** [comment]
You would need to rename one of the two libraries. Its a bad configuration to do that anyway.

Use a post instal hook or contact the author to update the vendored artifact.
