### ISSUE TITLE
Cannot find `Firebase` module when doing `pod lib lint` for my private static lib.

### ISSUE THREAD

**Issue by Bawenang** [CocoaPods/CocoaPods#10561]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod lib lint [LIBNAME].podspec

## What did you expect to happen?

The linting is successful

## What happened instead?

The linting failed with these errors:
`    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.`
`    - ERROR | xcodebuild:  /Users/bawenang/zLogger/zLogger/zLogger/Classes/LogFileSenderAdapter.swift:10:8: error: no such module 'Firebase'`

## CocoaPods Environment

```
---------------------------------------------
Error loading the plugin `slather-2.4.7`.

Gem::ConflictError - Unable to activate slather-2.4.7, because activesupport-5.2.4.5 conflicts with activesupport (>= 4.0.2, < 5)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------
```

## Project that demonstrates the issue

https://drive.google.com/file/d/1uuvAl3tBTW8rrI9JjEVJa7heUtbV9hQw/view?usp=sharing

**Comment by paulb777** [comment]
The Firebase pod is an umbrella pod and typically should not be used as a podspec dependency.  Use the specifically needed Firebase pod instead and use `import FirebaseStorage` instead of `import Firebase`.

**Comment by Bawenang** [comment]
@paulb777 You are right. After I changed it to FirebaseCore, it works now. Thanks.
