### ISSUE TITLE
copy-dsyms scripts include full paths

### ISSUE THREAD

**Issue by davehakim** [CocoaPods/CocoaPods#10565]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) 🌈.

# Report

Generated copy-dsyms.sh scripts call `install_dsym` on full paths to bundled dsyms. This makes the scripts unsuitable to be committed in a multi user project. It appears the paths could just as easily start with `${PODS_ROOT}`

## What did you do?

Cloned https://github.com/zendesk/ios_sdk_demo_apps/
Ran `pod install` in the SupportSDKSamples directory
Observed the generated copy-dsyms scripts had full paths to dsyms in them 

<img width="1468" alt="Screen Shot 2021-04-07 at 1 49 00 PM" src="https://user-images.githubusercontent.com/3911478/113911509-10f93700-97a8-11eb-8ef2-4f4d83405a5b.png">

## What did you expect to happen?

I'd expect paths to start with `${PODS_ROOT}` so that the scripts could be committed to a repo and work when checked out by other developers / CI

<img width="1596" alt="Screen Shot 2021-04-07 at 5 45 43 PM" src="https://user-images.githubusercontent.com/3911478/113940402-63981a80-97cb-11eb-85ce-edb9f17f401e.png">

## What happened instead?

Because the full paths were committed to the repo the dsyms for these XCFrameworks did not make it into our archive build which was made by CI

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/hakimd0-v/.rvm/rubies/ruby-2.6.0/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ c2874842003cc474c391079104045c2c6ad394a4
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/hakimd/.rvm/gems/ruby-2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
cocoapods-wholemodule : 0.0.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git' 

platform :ios, '10.0'

target 'CocoaPodSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodSample
  pod 'ZendeskSupportSDK'
end
```

## Project that demonstrates the issue

Running pod install in this SupportSDKSamples project and then examining the generated copy-dsyms scripts will demonstrate the issue https://github.com/zendesk/ios_sdk_demo_apps/tree/master/SupportSDKSamples

**Comment by dnkoutso** [comment]
This seems like a valid enhancement and fix to be honest. We should change that.

**Comment by dnkoutso** [comment]
@davehakim want to take a stab at it and open a PR?

**Comment by dnkoutso** [comment]
seems like PR is up for this https://github.com/CocoaPods/CocoaPods/pull/10583

**Comment by knox** [comment]
Oh, i didn't knew this issue existed when I created that PR. It fixes the problem described here.

**Comment by dnkoutso** [comment]
awesome thank for confirming @knox !
