### ISSUE TITLE
How to move '~/.cocoapods' to another directory 

### ISSUE THREAD

**Issue by phoenixsky** [CocoaPods/CocoaPods#10571]
Something like  XXX_HOME  
> PATH : export GEM_HOME=$HOME/Ruby/gem

**Comment by orta** [comment]
I don't think we have a flag for that

**Comment by drewdavis418** [comment]
In case anyone comes across this issue while searching around, this [seems to be supported](https://github.com/CocoaPods/CocoaPods/blob/e83d3264d4960d53dcb0cc921b0468f768dd3ed4/lib/cocoapods/config.rb#L137) via the `CP_HOME_DIR` environment variable. There is even [a test case](https://github.com/CocoaPods/CocoaPods/blob/ed1f011062a52ad136aadef80e0fc7d598766d27/spec/unit/config_spec.rb#L33) for this, so it is _probably_ safe to assume that this is supported.

```bash
export CP_HOME_DIR="$HOME/.local/share/cocoapods"
```
