### ISSUE TITLE
Pods are missing in Targets Xcode iOS

### ISSUE THREAD

**Issue by raf-wtag** [CocoaPods/CocoaPods#10574]
I don't know if this is the right place to describe my problem.

I'm using MapBox Search SDK for iOS. After installing cocoapods using -
```
brew cleanup -d -v
brew install cocoapods
pod setup
```
to install cocoapods.

Then I open my Xcode project in terminal and run - `pod init`

After that added this to my Podfile -
```
target 'MapBox' do
   use_frameworks!
  pod 'MapboxSearchUI', ">= 1.0.0-beta.3", "< 2.0"
end
```
and run `pod install` so it gives me - 
```
Analyzing dependencies
Downloading dependencies
Using MapboxCommon (9.0.2)
Using MapboxMobileEvents (0.10.8)
Using MapboxSearch (1.0.0-beta.4)
Using MapboxSearchUI (1.0.0-beta.4)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
```
In my project directory in Pods folder I got 4 folder for 4 libraries -

![Screenshot 2021-04-12 at 11 41 33 AM](https://user-images.githubusercontent.com/79823087/114351840-f995c180-9b8c-11eb-93e9-57a4bdd9f3ed.png)

But in my Xcode I'm only getting 1 library in Targets -

![Screenshot 2021-04-12 at 11 41 08 AM](https://user-images.githubusercontent.com/79823087/114352055-3661b880-9b8d-11eb-9072-2f572820d904.png)

When I'm trying to build / run this project I'm getting -
`Framework not found MapboxCommon.xcframework`
and Build Failed.

I'm running `1.5.2` pod version.

So, Is this a cocoapod issue? Or it is causing because of some issues in MapBox?

**Comment by paulb777** [comment]
Update CocoaPods. A much more recent version of CocoaPods is needed to support `xcframeworks`.
