### ISSUE TITLE
Add import to module_map or umbrella header

### ISSUE THREAD

**Issue by swiftyfinch** [CocoaPods/CocoaPods#10588]
Hello everyone!

I wonder If there exists any way to change the content of `PodName-umbrella.h`?
Or somehow to pass my own through podspec DSL.

I need to add import to umbrella header or ideally change all content to this:
```swift
// PodName-umbrella.h
@import MyAnotherPod;
```

Also, I can use a custom `module_map`.
But I couldn't figure out how to use the correct path to the header file from my pod.
```swift
framework module PodName {
    header "MyAnotherPod.h" // ⛔️ Header 'MyAnotherPod.h' not found
}
```

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by swiftyfinch** [comment]
OK, @orta. And thanks for the suggestion!
By the way, I posted my solution on [StackOverflow](https://stackoverflow.com/a/67157396/6197314)
