### ISSUE TITLE
[Feature request] pod primary destination and fallback

### ISSUE THREAD

**Issue by simonmcl** [CocoaPods/CocoaPods#10582]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I am building an iOS app, the core of which we are also open sourcing as a cocoapod. I use 

```
pod '{name}', :path => '~/Documents/projects/{name}'
```

when i'm developing the main application, so that I can make changes to the library more easily, as practically every new feature for the app, needs new code in the pod. When I'm done, I cut a new version of the pod, wait for it to sync, update the main apps podfile, then push to my CI. A lot of this is very manual and needs to be done for every release. Would it be possible to add something like (i'm not a ruby dev, treat it as pseudo code):

```
pod '{name}', {
  :primary => { :path => '~/Documents/projects/{name}' },
  :fallback => { :git => 'https://gitlab.com/....', :tag => '0.0.1' }
}
```

So that when pod installing, it will first try to find a local copy, if none found, use the remote version. This would let me work locally and not have to update the file for every release for my CI

**Comment by gereons** [comment]
I had a similar problem a while ago and solved it via environment variables/dot-files. See https://stackoverflow.com/questions/60799084/share-common-code-between-2-ios-apps-swift-package-manager-cocoapods-monorepo/60804182#60804182

**Comment by simonmcl** [comment]
@gereons thats a huge help, didn't know something like that was possible, thanks. Something like that answer should be added as a code sample on the cocoapods website

**Comment by dnkoutso** [comment]
ENV variables was the first thing that came to me as well upon reading your feature request. I am going to close for now. There are quite a few samples scattered around using ENV variables. The `Podfile` is just Ruby so you can write any Ruby code you wish to customize stuff.
