### ISSUE TITLE
CDN errors. URL couldn’t be downloaded

### ISSUE THREAD

**Issue by raven** [CocoaPods/CocoaPods#10580]
We're seeing CDN failures:

```

Analyzing dependencies
[!] CDN: trunk Repo update failed - 4 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/a/a/6/Kingfisher/3.2.2/Kingfisher.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/6/Kingfisher/3.2.2/Kingfisher.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/a/a/6/Kingfisher/4.6.1/Kingfisher.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/6/Kingfisher/4.6.1/Kingfisher.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/a/a/6/Kingfisher/5.5.0/Kingfisher.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/6/Kingfisher/5.5.0/Kingfisher.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/a/a/6/Kingfisher/6.1.0/Kingfisher.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/6/Kingfisher/6.1.0/Kingfisher.podspec.json
🚨 Error: The command exited with status 1

```

Another repo:
```
[!] CDN: cocoapods- Repo update failed - 2 error(s):
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/a/9/SwiftProtobuf/1.15.0/SwiftProtobuf.podspec.json Response: 302
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/a/9/SwiftProtobuf/1.3.0/SwiftProtobuf.podspec.json Response: 302
```

## Temporary Workarounds
If you're landing on this issue looking for how to unblock yourself / teams, here are some options:

### Workaround: Use git repo (the old pre-CDN method)
Your milage may vary with this method. It worked for our teams and a few others in this thread. Note: cloning the git repo can take a **significant** amount of time (~10mins)

In your Podfile replace:
`source 'https://cdn.cocoapods.org/'`
with:
`source 'https://github.com/CocoaPods/Specs.git'`

If working locally, you may need to remove your old refs to the cdn repo:
`pod repo remove trunk`
`pod install --repo-update`

### Workaround: Use patched Cocoapods that includes a fix for `302`s

From @stigi below:

> We've unblocked ourselves by temporarily using the latest HEAD versions of cocoapods & cocoapods-core that contains the fix for the 302 redirect issue ([CocoaPods/Core#683](https://github.com/CocoaPods/Core/pull/683)).
> 
> I'm crossposting from [CocoaPods/Core#683 (comment)](https://github.com/CocoaPods/Core/pull/683#issuecomment-818563401):
> 
> For everybody who needs to unblock themself (or their CI respectively): We're temporarily using the latest master commits of `cocoapods`, `cocoapods-core` and `xcodeproj` which include #679 and circumvent the issue:
> 
> Here's a snippet from our Gemfile:
> 
> ```
> ## Workaround
> ## hard coding current `master` versions of cocoapods gems to circumvent 302
> ## redirect issue with the pods repo until https://github.com/CocoaPods/Core/pull/683
> ## finds its way into stable
> #gem "cocoapods", "~> 1.10.1"
> gem "xcodeproj", github: 'cocoapods/xcodeproj', ref: '907c817'
> gem "cocoapods-core", github: 'cocoapods/core', ref: '5687c51'
> gem "cocoapods", github: 'cocoapods/cocoapods', ref: '123f2d0'
> ```

## Outstanding question:
Will whatever caused the `302`s be reverted?

**Comment by Alex009** [comment]
we have same problem at CI and local

**Comment by kovalandrew** [comment]
Same issue, reinstall cocoapod, turn on/off vpn doesn't help

**Comment by yyjim** [comment]
Same issue

**Comment by LisonFan** [comment]
jsdelivr Strike?

**Comment by diaozheng999** [comment]
I'm facing similar issue on 1.10.1:

```
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
[!] CDN: trunk Repo update failed - 4 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/2.4.1.1/Firebase.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/0/3/5/Firebase/2.4.1.1/Firebase.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.18.0/Firebase.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/0/3/5/Firebase/6.18.0/Firebase.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.19.0/Firebase.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/0/3/5/Firebase/6.19.0/Firebase.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.33.0/Firebase.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/0/3/5/Firebase/6.33.0/Firebase.podspec.json
```

**Comment by geowarsong** [comment]
Same for us, for all Repo's, we have an issue with Firebase and Amplitude

**Comment by srafiqa** [comment]
Same issue

**Comment by raven** [comment]
The fallback of using the git spec repo is working for us:

https://github.com/CocoaPods/CocoaPods/issues/10528#issuecomment-801754823

**Comment by Hao-Cognativ** [comment]
Same issue here and I tried the fallback of using the git spec repo, it stuck at cloning like forever...

**Comment by dreampiggy** [comment]
Seems CDN Server is down ?
```
[!] CDN: trunk Repo update failed - 10 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.24.0/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.25.0/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.26.0/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.27.1/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.31.1/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.2.0/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.4.0-M1/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.5.0/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.6.0/Firebase.podspec.json Response: 302
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.7.0/Firebase.podspec.json Response: 302
```

**Comment by geowarsong** [comment]
@Hao-Cognativ you can download the repo manually and it to `USER_PATH/.cocoapods/repos` this will help.
Fallback helped me, I was forced to remove repos and re-download them again, then with bundler again, `bundle exec pod install` 

Workaround provided by @raven 's above

**Comment by Hao-Cognativ** [comment]
> @Hao-Cognativ you can download the repo manually and it to `USER_PATH/.cocoapods/repos` this will help.
> Fallback helped me, I was forced to remove cocoapods repos and re-download them again, then with bundler again, `bundle exec pod install`
> 
> The workaround provided by @raven 's above

Thanks dude, will give it a go

**Comment by Hao-Cognativ** [comment]
> @Hao-Cognativ you can download the repo manually and it to `USER_PATH/.cocoapods/repos` this will help.
> Fallback helped me, I was forced to remove cocoapods repos and re-download them again, then with bundler again, `bundle exec pod install`
> 
> The workaround provided by @raven 's above

Fallback helps too, I just have to be patient to wait for more than 10 mins for cloning.
LOL, thanks again dude

**Comment by ChristopherDrum** [comment]
Outage here too. Same CDN problem.
I get a long string of `Ignoring ffi-1.12.2 because its extensions are not built. Try: gem pristine ffi --version 1.12.2` warnings concurrent with this problem. False errors? (`ffi 1.15.0` is found and seems to be used without issue)

**Comment by chml** [comment]
Why cocoapods not handling the 302 redirection?

**Comment by biancadragomir** [comment]
We are also facing this issue on Bitrise
`[!] CDN: trunk Repo update failed - 4 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/b/9/AppAuth/0.6.0/AppAuth.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/b/b/9/AppAuth/0.6.0/AppAuth.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/b/9/AppAuth/0.9.0/AppAuth.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/b/b/9/AppAuth/0.9.0/AppAuth.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/b/9/AppAuth/0.95.0/AppAuth.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/b/b/9/AppAuth/0.95.0/AppAuth.podspec.json
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/b/9/AppAuth/1.3.1/AppAuth.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/b/b/9/AppAuth/1.3.1/AppAuth.podspec.json
Command failed, error: exit status 1`

**Comment by VanTigranyan** [comment]
> Seems CDN Server is down ?
> 
> ```
> [!] CDN: trunk Repo update failed - 10 error(s):
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.24.0/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.25.0/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.26.0/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.27.1/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.31.1/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.2.0/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.4.0-M1/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.5.0/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.6.0/Firebase.podspec.json Response: 302
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/7.7.0/Firebase.podspec.json Response: 302
> ```

Seeing exactly the same issue. Problem comes from Firebase pod that does 302 redirection.

**Comment by cmfsotelo** [comment]
> Why cocoapods not handling the 302 redirection?

Maybe this addresses part of your concern
https://github.com/CocoaPods/Core/pull/683

We are suffering from this issue as well 😢

**Comment by chml** [comment]
> > Why cocoapods not handling the 302 redirection?
> 
> Maybe this addresses part of your concern
> [CocoaPods/Core#683](https://github.com/CocoaPods/Core/pull/683)
> 
> We are suffering from this issue as well 😢

Yes, currently may use bundler for a workaround:
```
gem "cocoapods-core", path: "~/github/core/" ## the cocoapods-core master clone
```

**Comment by Hao-Cognativ** [comment]
> We are also facing this issue on Bitrise
> 
> ```
> [!] CDN: trunk Repo update failed - 4 error(s):
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/b/9/AppAuth/0.6.0/AppAuth.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/b/b/9/AppAuth/0.6.0/AppAuth.podspec.json
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/b/9/AppAuth/0.9.0/AppAuth.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/b/b/9/AppAuth/0.9.0/AppAuth.podspec.json
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/b/9/AppAuth/0.95.0/AppAuth.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/b/b/9/AppAuth/0.95.0/AppAuth.podspec.json
> CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/b/9/AppAuth/1.3.1/AppAuth.podspec.json Response: 302 Found. Redirecting to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/b/b/9/AppAuth/1.3.1/AppAuth.podspec.json
> Command failed, error: exit status 1
> ```

We use Bitrise as mobile CI/CD and we had the same issue, check the workaround provided by @raven 's above, that solved my issue

**Comment by koust** [comment]
same issue

**Comment by hakota** [comment]
It's just a temporary workaround.
Try the following

https://github.com/CocoaPods/CocoaPods/issues/10528#issuecomment-818528590

**Comment by jesperjohansson** [comment]
Temporary workaround

Put
```
source 'https://github.com/CocoaPods/Specs.git'
```
in top of your Podfile and then try `pod install` again

**Comment by snowsiechau** [comment]
> Temporary workaround
> 
> Put
> 
> ```
> source 'https://github.com/CocoaPods/Specs.git'
> ```
> 
> in top of your Podfile and then try `pod install` again

not working for me

**Comment by xiao333ma** [comment]
> Temporary workaround
> 
> Put
> 
> ```
> source 'https://github.com/CocoaPods/Specs.git'
> ```
> 
> in top of your Podfile and then try `pod install` again

remove `source 'https://cdn.cocoapods.org/' ` if need

it's work for me

**Comment by MeGaPk** [comment]
same from estonia

**Comment by sdaniel55** [comment]
@snowsiechau try removing the CDN, you can list them with `pod repo list` and remove with `pod repo remove trunk`. Then `pod install` should work afterwards

**Comment by kcsaba-sonrisa** [comment]
same from Hungary, all CI pipline failed :( The Temporary workaround is working(mentioned by @xiao333ma) The `pod repo remove trunk` it wasn't enough!

**Comment by snowsiechau** [comment]
> @snowsiechau try removing the CDN, you can list them with `pod repo list` and remove with `pod repo remove trunk`. Then `pod install` should work afterwards (and the `Podfile`'s `source` update as well of course)
it worked, many thanks

**Comment by stigi** [comment]
We've unblocked ourselves by temporarily using the latest HEAD versions of cocoapods & cocoapods-core that contains he fix (https://github.com/CocoaPods/Core/pull/683).

I'm crossposting from https://github.com/CocoaPods/Core/pull/683#issuecomment-818563401

For everybody who needs to unblock themself (or their CI respectively): We're temporarily using the latest master commits of `cocoapods`, `cocoapods-core` and `xcodeproj` which include #679 and circumvent the issue:

Here's a snippet from our Gemfile:

```
## Workaround
## hard coding current `master` versions of cocoapods gems to circumvent 302
## redirect issue with the pods repo until https://github.com/CocoaPods/Core/pull/683
## finds it's way into stable
#gem "cocoapods", "~> 1.10.1"
gem "xcodeproj", github: 'cocoapods/xcodeproj', ref: '907c817'
gem "cocoapods-core", github: 'cocoapods/core', ref: '5687c51'
gem "cocoapods", github: 'cocoapods/cocoapods', ref: '123f2d0'
```

**Comment by janghunlee** [comment]
we have same problem at CI

**Comment by markrufino-cp** [comment]
> Temporary workaround
> 
> Put
> 
> ```
> source 'https://github.com/CocoaPods/Specs.git'
> ```
> 
> in top of your Podfile and then try `pod install` again

This worked for me on Bitrise.

**Comment by tapwork** [comment]
@stigi saved my day!

**Comment by ChristopherDrum** [comment]
@stigi It's slow but it works. Appreciate the assist 👍

**Comment by lawdt** [comment]
same problem

**Comment by mateszlanka** [comment]
@stigi 's solution also works properly on Azure Devops

**Comment by markangelohernandez** [comment]
I have tried again to run our `Bitrise` dev workflow `cocoapod` step and is no longer failing, no more CDN errors. Same thing with my local machine.

**Comment by jesperjohansson** [comment]
CDN seems to work again

**Comment by mceIdo** [comment]
Any chance this is happening again now? Anyone else experiencing it currently?

**Comment by craastad** [comment]
Is there any chance this is happening now again? We're finding a lot of errors in our system in this flavor.

**Comment by dnkoutso** [comment]
we have merged a fix for 302 in 1.10.2 which will ship this week hopefully. the same fix also is for 1.11.0 next release.

**Comment by haofanning** [comment]
same issue on 1.11.2 , it still happen

**Comment by kevinkooyizen** [comment]
Still happening. Please reopen this

**Comment by VladyslavKozlovskyi** [comment]
I also faced it 30 mins ago

**Comment by paulb777** [comment]
See https://github.com/CocoaPods/CocoaPods/issues/11355
