### ISSUE TITLE
Error Firebase dependencies

### ISSUE THREAD

**Issue by yjlock** [CocoaPods/CocoaPods#10590]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

i run`pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

yohanjoseph-lockel@MacBook-Air-de-Yohan name-app % pod install
Analyzing dependencies
Downloading dependencies
Installing Firebase (3.17.0)
Installing FirebaseAnalytics (3.9.0)
Installing FirebaseAuth (3.1.1)
Installing FirebaseCore (3.6.0)
Installing FirebaseDatabase (3.1.2)
Installing FirebaseInstanceID (1.0.10)
Installing FirebaseStorage (1.1.0)
Installing GTMSessionFetcher (1.5.0)
Installing Google (3.1.0)
Installing GoogleSignIn (4.4.0)
Installing GoogleToolboxForMac (2.3.1)
Generating Pods project
Integrating client project

### Error

```
NoMethodError - undefined method `files' for <PBXFileReference path=`Pods` UUID=`7B818E38262AE1C700382D36`>:Xcodeproj::Project::Object::PBXFileReference
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:165:in `create_xcconfig_ref'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:45:in `set_target_xcconfig'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:21:in `block (2 levels) in integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:20:in `block in integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:19:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:439:in `block in integrate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:438:in `integrate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator.rb:146:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator.rb:146:in `integrate_user_targets'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/user_project_integrator.rb:73:in `integrate!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:840:in `block in integrate_user_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:836:in `integrate_user_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:180:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```
――― TEMPLATE END 

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60files%27+for+%3CPBXFileReference+path%3D%60Pods%60+UUID%3D%607B818E38262AE1C700382D36%60%3E%3AXcodeproj%3A%3AProject%3A%3AObject%3A%3APBXFileReference&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

![Capture d’écran 2021-04-17 à 18 43 37](https://user-images.githubusercontent.com/47239700/115120252-dadc6400-9fac-11eb-8f8b-f512f2da0982.png)

**Comment by rani-maker** [comment]
same problem

**Comment by paulb777** [comment]
I'm not sure about the CocoaPods issue here, but Firebase 3.x is five years old and I strongly recommend upgrading to Firebase 7.x which is well tested with CocoaPods.

**Comment by rani-maker** [comment]
> I'm not sure about the CocoaPods issue here, but Firebase 3.x is five years old and I strongly recommend upgrading to Firebase 7.x which is well tested with CocoaPods.

Please how to upgrade ?

**Comment by yjlock** [comment]
Hello guys thank you for the quick return, I solved my incident by recreating the project. I dont know exactly what it is going on, but it works again !
