### ISSUE TITLE
Published Succesfullly but not able to install by pod install command.

### ISSUE THREAD

**Issue by Suraj007** [CocoaPods/CocoaPods#10611]
🎉  Congrats

 🚀  PokktSDK (1.0.0) successfully published
 📅  April 26th, 21:44
 🌎  https://cocoapods.org/pods/PokktSDK
 👍  Tell your friends!

Could you please help me , what is the issue.

**Comment by paulb777** [comment]
Please fill out the issue template including the Podfile being used.

**Comment by Suraj007** [comment]
Hi Paul, 

Below is my pod file content:

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokktPodTesting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PokktSDK'
  # Pods for PokktPodTesting

end

**Comment by Suraj007** [comment]
Hi Paul,

I have successfully published my podspec file and got the below message.

🎉 Congrats

🚀 PokktSDK (1.0.0) successfully published
📅 April 26th, 21:44
🌎 https://cocoapods.org/pods/PokktSDK
👍 Tell your friends!

And below is my podfile content:

target 'PokktPodTesting' do
  pod 'PokktSDK'
end

When I am trying to install using the above podfile getting the below error:

Analyzing dependencies
[!] Unable to find a specification for `PokktSDK`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by paulb777** [comment]
I don't reproduce. Did you follow the suggestions in the error message?

Anyway , this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
