### ISSUE TITLE
No such module 'Segment'

### ISSUE THREAD

**Issue by Innocuousjoe** [CocoaPods/CocoaPods#10625]
* [X ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Added `pod 'Analytics', '~> 4.1'`

## What did you expect to happen?

I expected to be able to `import Segment` in AppDelegate.swift

## What happened instead?

`No such module "Segment"`

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.3 (20E232)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs @ 42e46d134de9a58331563c84d72a6e48e3f5852f

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs'
platform :ios, '12.0'
workspace 'Pace'

target 'Pace' do
  pod "SwiftPhoenixClient", '~> 1.0'
  pod 'MessageKit'
  pod 'TwilioVideo', '~> 3.7'
  pod 'SwiftyJSON'
  pod 'DropDown'
  pod 'SideMenu'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'OpenGraph'
  pod 'Analytics', '~> 4.1'

end
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
