### ISSUE TITLE
pod repo push xxx --allow-warnings  with ' refusing to merge unrelated histories ' error occured

### ISSUE THREAD

**Issue by Goallying** [CocoaPods/CocoaPods#10621]
Updating the `xxx' repo

[!] /usr/bin/git -C /Users/xxx/.cocoapods/repos/xxx pull

hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: refusing to merge unrelated histories

**Comment by dnkoutso** [comment]
this issue is not following our issue template and provides very little context. please file a new issue properly filling in the template and specify clear steps.
