### ISSUE TITLE
Exception: Error running pod install

### ISSUE THREAD

**Issue by jojoberrah** [CocoaPods/CocoaPods#10622]
Search for existing GitHub issues similar to yours:
    https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2
    FGems%2F2.6.0%2Fgems%2Fffi-1.15.0%2Flib%2Fffi_c.bundle%2C+9%29%3A+no+suitabl
    e+image+found.++Did+find%3A%0A%09%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Ff
    fi-1.15.0%2Flib%2Fffi_c.bundle%3A+mach-o%2C+but+wrong+architecture%0A%09%2FL
    ibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.0%2Flib%2Fffi_c.bundle%3A+mac
    h-o%2C+but+wrong+architecture+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fff
    i-1.15.0%2Flib%2Fffi_c.bundle&type=Issues

Looking for related issues on cocoapods/cocoapods...

Error output from CocoaPods:
↳
    Searching for inspections failed: undefined method `map' for nil:NilClass

Exception: Error running pod install

**Comment by 1479HuangDa** [comment]
I have same the problem

**Comment by chaochaox1990** [comment]
add one

**Comment by javioli-devbase** [comment]
same here...

**Comment by dnkoutso** [comment]
Please file a new issue report following the template and provide more information and a sample app for us to be able to diagnose.
