### ISSUE TITLE
 /usr/local/Cellar/cocoapods/1.9.3/libexec/gems/cocoapods-core-1.9.3/lib/cocoapods-core/cdn_source.rb:342: warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by samchidi2005** [CocoaPods/CocoaPods#10628]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by samchidi2005** [comment]
CocoaPods : 1.9.3
Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin18]
RubyGems : 3.1.2
Host : Mac OS X 10.14.6 (18G8022)
Xcode : 11.2.1 (11B500)
Git : git version 2.23.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.1_2/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ f87702f564e9614ffef81c70479446dd90f828c3

**Comment by dnkoutso** [comment]
Issue template is not valid for us to diagnose.
