### ISSUE TITLE
Cocoa pod builds well, but importing claims no source is found. Basically everything related to c++ source: std::list, std::string

### ISSUE THREAD

**Issue by MikaelKorpinen** [CocoaPods/CocoaPods#10620]
<!--
ℹ Please fill out this template when filing an issue.
All lines beginning with an ℹ symbol instruct you with
what info we expect.  

Before you start, are you using the latest CocoaPods release?
Yes I have updated cocoapods.

# Report

## What did you do?
I made an xcode project that uses some c++ files. Everything works fine tests pass, but when I import the cocoa pod xcode claims the cocoapod files are not found. (#import <list>, #import >string> ). These happen only inside the cocoa pod space

I have tried multiple things.
pod deintegrate, pod install, pod update. I have tried editing pod spec according to stack instructions. I have tried editin pod file use frameworks.

## What did you expect to happen?
imported cocoa pod works like it works in the source project for the cocoa pod.

ℹ Please replace these two lines with what you expected to happen.  
I expected the pod to be able to link the libraries it refers to

## What happened instead?
Cannot find libraries/files #import <list>, #import >string>

ℹ Please replace these two lines with of what happened instead.  
Pod is missing connection to libraries that are supported by XCode

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.1 (20C69)
       Xcode : 12.3 (12C33)
         Git : git version 2.23.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApprienObjectiveCExampleApp iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!
 #   pod 'cocos2d'
    pod 'ApprienObjectiveC', :path => '~/workspace/github/ApprienObjectiveC/'

end
```

Link to repo that has the problem.
https://github.com/phzfi/ApprienObjectiveCExampleGame

**Comment by dnkoutso** [comment]
This is not a valid issue report, please file in a new issue with the template and provide a sample app explaining the issue with more detail.
