### ISSUE TITLE
Terminal report < [!] No `Podfile' found in the project directory.> while <pod install>

### ISSUE THREAD

**Issue by baronboar576** [CocoaPods/CocoaPods#10629]
My Project path previously are '跟着项目学iOS应用开发：基于Swift 4/Happy Chat Duplicate/', When I initialize the project with 
'pod init', add in the Podfile with some libararies and runs 'pod install', Cocoapods just report and Error like the Title'[!] No `Podfile' found in the project directory.'. I guess the reason is the use of ":" in project path, so I just replace this character with a dash(-), rerun the 'pod install', the Error is disappear.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by baronboar576** [comment]
Thanks, Learned it.
