### ISSUE TITLE
Pod spec lint fails for a xcframework binary http source

### ISSUE THREAD

**Issue by stasel** [CocoaPods/CocoaPods#10638]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod spec lint --verbose`

## What did you expect to happen?

The linter should complete successfully 

## What happened instead?
Xcodebuild fails on the linker stage

```
    ld: warning: directory not found for option '-F/Users/stasel/Library/Developer/Xcode/DerivedData/App-hevpsmbejliybnbekfecimzvbmfh/Build/Products/Release-iphonesimulator/XCFrameworkIntermediates/WebRTC'
    ld: framework not found WebRTC
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    ** BUILD FAILED **
```

Full verbose log can be found here: https://pastebin.com/1ySwFVmy

## Podspec
```ruby
Pod::Spec.new do |spec|

  spec.name         = "WebRTC-lib"
  spec.version      = "90.0.0"
  spec.summary      = "Unofficial distribution of WebRTC framework binaries for iOS. "
  spec.description  = <<-DESC
  This pod contains unofficial distribution of WebRTC framework binaries for iOS.
  All binaries in this repository are compiled from the official WebRTC source code without any modifications to the sources code or to the output binaries.
  DESC

  spec.homepage     = "https://github.com/stasel/WebRTC"
  spec.license      = { :type => 'BSD' }
  spec.author       = "Stasel"
  spec.platform     = :ios, "10.0"

  spec.source       = { :http => "https://github.com/stasel/WebRTC/releases/download/90.0.0/WebRTC-M90.xcframework.zip" }
  spec.vendored_frameworks = "WebRTC.xcframework"
end

```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.3.1 (20E241)
       Xcode : 12.5 (12E262)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

https://github.com/stasel/WebRTC

**Comment by snowinszu** [comment]
Same issue, hope fix soon

**Comment by swrdfish** [comment]
Is there any work around for this?

**Comment by swrdfish** [comment]
@meyer-solutions I faced and same problem as you mentioned, as it turn out the structure of my zip was wrong. I had a wrapping folder at the root of the zip, which is wrong. The contents of the zip should directly contain the framework folders.

```bash
#MyPod.zip (incorrect)
MyPod/
   - MyPod.xcframework
   - LICENSE
   - MyPod.podspec
   
#MyPod.zip (correct)   
   - MyPod.xcframework
   - LICENSE
   - MyPod.podspec
```
But the linker stage issue still remains.
Hope that helps.

**Comment by ahl0107** [comment]
Same issue,occurs in version 1.10.0 or higher

**Comment by dnkoutso** [comment]
Will have to diagnose, perhaps a cocoapods-downloader issue rather than cocoapods.

**Comment by snowinszu** [comment]
Any update?

> Will have to diagnose, perhaps a cocoapods-downloader issue rather than cocoapods.

**Comment by dnkoutso** [comment]
nope, feel free to assist to diagnose this!

**Comment by dnkoutso** [comment]
Will attempt to fix this for 1.11.0.

**Comment by dnkoutso** [comment]
I can reproduce. Will be digging further.

**Comment by stasel** [comment]
Awesome, thanks for checking it out @dnkoutso

**Comment by dnkoutso** [comment]
@stasel from a quick look it seems the structure of the xcframework might not be correct. It seems you are not using `create-xcframework`.

However, SPM does seem to work so something somehow correctly works by supplying "ios", "simulator" and "macos" inside the xcframework.

**Comment by stasel** [comment]
Yeah, because `create-xcframework` does not support bundling multiple arch binaries (like arm macos and x64 macos), I manually create the `xcframework` with `lipo`. 
In the plist I specify the correct paths and it works with SPM or manual embed.

**Comment by dnkoutso** [comment]
@stasel I see...from a quick glance this would be much harder to add support. We would have to parse the plist and figure the supplied archs instead.

**Comment by dnkoutso** [comment]
we would have to update cocoapods to parse the info.plist instead of the folders to enumerate the available archs.

**Comment by stasel** [comment]
Hm... If I rename the folder to match the standard `xcframework` will it work without any fix?

**Comment by dnkoutso** [comment]
@stasel I think so.

For example cocoapods CI has AppCenter xcframework being tested.

The script phase is
```
install_xcframework "${PODS_ROOT}/AppCenter/AppCenter-SDK-Apple/AppCenterCrashes.xcframework" "AppCenter/Crashes" "framework" "ios-arm64_arm64e_armv7_armv7s" "ios-arm64_x86_64-maccatalyst" "ios-arm64_i386_x86_64-simulator"
```

and the .xcframework contents:

<img width="1032" alt="Screen Shot 2021-08-13 at 12 27 49 AM" src="https://user-images.githubusercontent.com/310370/129272364-61b76c39-5e47-4d52-8730-1704011ae322.png">

**Comment by dnkoutso** [comment]
Its basically a list of supported architectures and then cocoapods chooses the correct slice at build time.

**Comment by dnkoutso** [comment]
Looking at entry in AppCenter.plist

```
		<dict>
			<key>LibraryIdentifier</key>
			<string>ios-arm64_i386_x86_64-simulator</string>
			<key>LibraryPath</key>
			<string>AppCenter.framework</string>
			<key>SupportedArchitectures</key>
			<array>
				<string>arm64</string>
				<string>i386</string>
				<string>x86_64</string>
			</array>
			<key>SupportedPlatform</key>
			<string>ios</string>
			<key>SupportedPlatformVariant</key>
			<string>simulator</string>
		</dict>
```

Seems like its SupportedPlatform + "-" + SupportedArchitectures.join('_') + "-" + SupportedPlatformVariant

which produces `ios-arm64_i386_x86_64-simulator`

**Comment by stasel** [comment]
Thanks for that, I'll try implementing this on my side and try again

**Comment by dnkoutso** [comment]
thank you! I _think_ if you get it working we might close this issue as we are generally moving more towards what Apple create-xcframework script produces.

We have some aspiration to update the xcframework integration and remove the script entirely and instead just let Xcode do its thing but that might be a 1.12.0 version feature.

**Comment by dnkoutso** [comment]
Hey @stasel ! any update to share? curious if it all worked out for you.

**Comment by stasel** [comment]
Hey @dnkoutso 
Yesterday I renamed the folders inside the xcframework to a similar format like AppCenter's framework and it worked!
I wonder where did they got that `ios-arm64_i386_x86_64-simulator` format because the standard `-create-xcframework` command does not support multiple architectures.

I'm waiting for the next release in two weeks so I can push it to cocoapods trunk and test it again

**Comment by dnkoutso** [comment]
> because the standard -create-xcframework command does not support multiple architectures.

interesting, i thought thats what it does by default.

> I'm waiting for the next release in two weeks so I can push it to cocoapods trunk and test it again

do you mean cocoapods release? yes I hope to have it by end of August.

**Comment by stasel** [comment]
> interesting, i thought thats what it does by default.
Yeah, there is this annoying issue that is [discussed on Apple forums](https://developer.apple.com/forums/thread/666335) and the only workaround is to use `lipo` to create my own xcframework - so annoying.

> do you mean cocoapods release? yes I hope to have it by end of August.
Oh sorry, I meant the next WebRTC release. It looks like `pod lint` passing in the current release as well so I don't have to wait for the next cocoapods release

**Comment by dnkoutso** [comment]
I wonder if we should close now or keep open. The only work i can see to make your case work is to parse the info plist file in the shell script

**Comment by dnkoutso** [comment]
Or an alternarive is to move away from the script and use “copy artifacts” phase from xcode

**Comment by dnkoutso** [comment]
@stasel for now I am going to close but we can re-open later if we see this happening again. I havent seen many other issue reports similar to this one yet.

**Comment by stasel** [comment]
Sounds good. Thanks for your help on how to fixed it.
I'll let you know if something comes up

**Comment by dnkoutso** [comment]
awesome! thanks again for the patience!
