### ISSUE TITLE
Jenkins in alpha branch doesn't respect podfile and  podfile.lock 

### ISSUE THREAD

**Issue by vsricci** [CocoaPods/CocoaPods#10632]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
## What did you do?
I have differents repos to create features.
Some repo for monolito, other for libs that the monolito uses, other to specify in podspec the version of libs and the repo link.
When I try to generate alpha version, in Jenkins has the podfile equals ~> 3.4, but in repo that I specify the versions, if exists an version equal 3.5.0. The jenkins doesn't respect the podfile.lock and do download to 3.5.0. 
How would I  organize the number versions, for fix this problem?

## What did you expect to happen?
some fix to organize number of version when jenkins try to do download of dependencies in alpha.

## What happened instead?
Jenkins didn't respect version in podfile and podfile.lock and do download others version higher specified in pods.

## CocoaPods Environment
example : pod 'lib', '~> 3.4'

## Project that demonstrates the issue
company project, I can't.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by vsricci** [comment]
@orta thanks for help, I did this in stack.
