### ISSUE TITLE
Help to implement BOM generator

### ISSUE THREAD

**Issue by jgongo** [CocoaPods/CocoaPods#10643]
Sorry to post this here, but I haven't found any other place more suitable for this type of request.

I'm the maintainer of https://github.com/CycloneDX/cyclonedx-cocoapods. This project creates a CycloneDX bill-of-material document including all the project dependencies which can later be used by other tools to audit software, warn about vulnerabilities, etc. I have implemented the first version using the CocoaPods gem as a dependency, and inspecting its source code. It would be great if somebody with knowledge about the inners of CocoaPods could validate the work and lend me a hand with a pair of doubts I have:

* How can I use the CocoaPods configuration infrastructure so I don't have to hard wire the CocoaPods directory in `::Pod::Source::Manager.new('~/.cocoapods/repos')`
* I build the BOM using information extracted from `Podfile` and `Podfile.lock`. Is there any way to programatically check that `Podfile.lock` is in sync with `Podfile`?

**Comment by macblazer** [comment]
> How can I use the CocoaPods configuration infrastructure so I don't have to hard wire the CocoaPods directory in ::Pod::Source::Manager.new('~/.cocoapods/repos')

The command `pod repo list` shows the information about the locally configured repositories.  Each repo has a URL to a repository on the internet, as well as the local path to the repository, along with it's type.

**Comment by dnkoutso** [comment]
> How can I use the CocoaPods configuration infrastructure so I don't have to hard wire the CocoaPods directory in ::Pod::Source::Manager.new('~/.cocoapods/repos')

Use `Config.instance.repos_dir`

> I build the BOM using information extracted from Podfile and Podfile.lock. Is there any way to programatically check that Podfile.lock is in sync with Podfile?

CocoaPods adds a script phase when `pod install` run to verify Podfile and podfile.lock as in sync:

```ruby

        # Adds a shell script build phase responsible for checking if the Pods
        # locked in the Pods/Manifest.lock file are in sync with the Pods defined
        # in the Podfile.lock.
        #
        # @note   The build phase is appended to the front because to fail
        #         fast.
        #
        # @return [void]
        #
        def add_check_manifest_lock_script_phase
          phase_name = CHECK_MANIFEST_PHASE_NAME
          native_targets.each do |native_target|
            phase = TargetIntegrator.create_or_update_shell_script_build_phase(native_target, BUILD_PHASE_PREFIX + phase_name)
            native_target.build_phases.unshift(phase).uniq! unless native_target.build_phases.first == phase
            phase.shell_script = <<-SH.strip_heredoc
              diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
              if [ $? != 0 ] ; then
                  # print error to STDERR
                  echo "error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation." >&2
                  exit 1
              fi
              # This output is used by Xcode 'outputs' to avoid re-running this script phase.
              echo "SUCCESS" > "${SCRIPT_OUTPUT_FILE_0}"
            SH
          end
        end
```

you can sort of do the same logic yourself to verify that.

Going to close as I do not see a bug or enhancement.

**Comment by jgongo** [comment]
Thanks a lot for the info, @dnkoutso !!
