### ISSUE TITLE
Unable to validate podspec file patterns and license file when pushing trunk for osx

### ISSUE THREAD

**Issue by oscarvillagrana** [CocoaPods/CocoaPods#10658]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk push` with osx

## What did you expect to happen?

Push a library of the most simplest format. Tried all the combination(individually of course) of file patterns possible(also changed the folder names and the folder structure to try all possibilities) including:

```
  s.source_files = 'macOS_UI/Classes/**/*'
  s.source_files  = 'macOS_UI/Classes/*.{h,m,xib}'
  s.source_files  = 'macOS_UI/Classes/ViewController.{h,m,xib}'
  s.source_files  = 'macOS_UI/Classes/ViewController.h','macOS_UI/Classes/ViewController.m','macOS_UI/Classes/ViewController.xib'
  s.source_files  = "Classes", "Classes/*.{h,m,xib}"
  s.source_files  = 'Classes/*.{h,m,xib}'
  s.source_files  = 'Classes/ViewController.{h,m,xib}'
  s.source_files  = 'Classes/ViewController.*'
```
Also tried re installing gem and cocoapods. But no file pattern worked. Also tried different GitHub projects and didn't work. I tried using the CocoaPodsExampleLibrary (https://github.com/CocoaPods/CocoaPodsExampleLibrary) and did not work either.

## What happened instead?

Build was successful but validation failed:

[!] Found podspec `macOS_UI.podspec`
Updating spec repo `trunk`
Validating podspec
 -> macOS_UI (1.0.0)
    - ERROR | [OSX] file patterns: The `source_files` pattern did not match any file.
    - WARN  | [OSX] license: Unable to find a license file
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: 
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | [OSX] xcodebuild:  note: Planning build
    - NOTE  | [OSX] xcodebuild:  note: Analyzing workspace
    - NOTE  | [OSX] xcodebuild:  note: Constructing build description

[!] The spec did not pass validation, due to 1 error and 1 warning.

[!] Unable to read the license file `LICENSE` for the spec `macOS_UI (1.0.0)`

[!] Unable to read the license file `LICENSE` for the spec `macOS_UI (1.0.0)`

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.2.17
        Host : macOS 11.3.1 (20E241)
       Xcode : 12.5 (12E262)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

https://github.com/oscarvillagrana/macos_ui

**Comment by oscarvillagrana** [comment]
Please help. Though it is my first time using cocoapods I did spend days reviewing all documentation and all tutorials possible.

**Comment by paulb777** [comment]
Looks like the 1.0.0 tag doesn't include most of the recent commits. CocoaPods uses the tag to find the sources.

**Comment by oscarvillagrana** [comment]
I see, that explains it. Thank you!
