### ISSUE TITLE
dyld: Library not loaded: @rpath .... 

### ISSUE THREAD

**Issue by chefnobody** [CocoaPods/CocoaPods#10654]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

A simple dependency graph using CocoaPods and explicit **Frameworks and Libraries** in Xcode does not result in expected behavior.

## What did I do?

* Created blank `DemoApp` iOS application.
* Created new Framework Target + Unit Test Target named `First`. Do not embed in `DemoApp`.
* Created new Framework Target + Unit Test Target named `Second`. Again, do not embed in `DemoApp`.
* Add `First` Framework to **Frameworks, Libraries, and Embedded Content** under `DemoApp` Target.
* Add `Second` Framework to **Frameworks, Libraries, and Embedded Content** under `First` Target.
* Run `pod init`
* In Podfile add `SwiftDate` as dependency to `Second`.
* Run `pod install`
* Build and run `DemoApp`.

The application fails to load because of a linker error:
```
dyld: Library not loaded: @rpath/SwiftDate.framework/SwiftDate
  Referenced from: /Users/aconnoll/Library/Developer/Xcode/DerivedData/DemoApp-gggzczarguwiqcefubcpaufrxnpn/Build/Products/Debug-iphonesimulator/Second.framework/Second
  Reason: image not found
```
## What did you expect to happen?

I expected that my application would build and run successfully and that `SwiftDate` would be available and visible to the linker for linking to the `DemoApp` target through its dependence upon `First.framework`, through `First`'s dependence upon `Second.framework`.

Dependency graph:
![graph](https://user-images.githubusercontent.com/303658/118307947-39a7d700-b4a0-11eb-8c44-20b13272990e.png)

## What happened instead?

Linker failed to link `SwiftDate`.

## What have I tried?

The only solution I could sort out was adding `SwiftDate` explicitly to the `DemoApp` target, via the PodFile.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin19]
    RubyGems : 3.0.9
        Host : Mac OS X 10.15.7 (19H524)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/aconnoll/.rvm/rubies/ruby-2.6.0/lib
Repositories : 
               master - git - https://github.com/CocoaPods/Specs.git @ f01c0b43b9cd6fb8ac2ddce06c84c6bd428119c5

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/aconnoll/.rvm/gems/ruby-2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

use_frameworks!

target 'DemoApp' do
end

target 'First' do
  target 'FirstTests' do
    inherit! :search_paths
  end  
end

target 'Second' do
  pod 'SwiftDate', '6.3.1'

  target 'SecondTests' do
    inherit! :search_paths
  end  
end
```

## Project that demonstrates the issue

https://github.com/chefnobody/DemoApp

**Comment by dnkoutso** [comment]
You cannot do that without statically linking frameworks.

Right now you have them all as dynamic frameworks. Even if you specify the "Second" framework as embedded in your app this wont work unless you actually embed `SwiftDate` too, but in your Podfile you do not specify that.

To accomplish this use static linking:

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

use_frameworks!

target 'DemoApp' do
end

target 'First' do
  target 'FirstTests' do
    inherit! :search_paths
  end  
end

target 'Second' do
  use_frameworks!(:linkage => :static)  # Add this line here.
  pod 'SwiftDate', '6.3.1'

  target 'SecondTests' do
    inherit! :search_paths
  end  
end
```

Then in Xcode switch the `Second` target `Mach-O Type` to "Static Library".

It worked for me.

**Comment by chefnobody** [comment]
@dnkoutso Thanks for the clarification. Doing as you described has resolved the dyld issue.
