### ISSUE TITLE
Can't run pod install

### ISSUE THREAD

**Issue by andrew-jolley** [CocoaPods/CocoaPods#10666]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Error of 'Searching for inspections failed: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)'

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin20]
    RubyGems : 3.2.15
        Host : macOS 11.3.1 (20E241)
       Xcode :  ()
         Git : git version 2.30.1
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.0.1/lib
Repositories : 
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.10.1_1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

It was adding Google Firebase to a pod

**Comment by dnkoutso** [comment]
Try not using the CDN but instead use git based repo to search for pods.
