### ISSUE TITLE
The podspec configuration file can support dependent links

### ISSUE THREAD

**Issue by KBvsMJ** [CocoaPods/CocoaPods#10662]
[Something like this](https://stackoverflow.com/questions/16905112/cocoapods-dependency-in-pod-spec-not-working)
![image](https://user-images.githubusercontent.com/8489350/118799427-4c237580-b8d1-11eb-89fb-5eab882600ab.png)

**Comment by orta** [comment]
Afraid not. It's not the responsibility of Podspecs to declare _where_ to find the dependency, only what the dependency is.

**Comment by KBvsMJ** [comment]
@orta Are there any good suggestions to solve the problem of relying on the third library?

**Comment by orta** [comment]
Use your own private specs repo or define it in a Podfile
