### ISSUE TITLE
Can't install pod

### ISSUE THREAD

**Issue by andrew-jolley** [CocoaPods/CocoaPods#10665]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

Error of 'Searching for inspections failed: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)'

## Project that demonstrates the issue

It was adding Google Firebase to a pod

**Comment by paulb777** [comment]
Please use issue template.
