### ISSUE TITLE
Issue with setting up iOS pod installation

### ISSUE THREAD

**Issue by kaicoleridge** [CocoaPods/CocoaPods#10669]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

I ran 'pod install' 

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

To install all pod dependencies. 

## What happened instead?

An error was thrown. 
<img width="1440" alt="Screenshot 2021-05-23 at 14 30 46" src="https://user-images.githubusercontent.com/51129378/119262756-4df08000-bbd4-11eb-9385-438cad40d277.png">

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by BellEraDev** [comment]
I have the same problem. How to fix it?

**Comment by javioli-devbase** [comment]
I get the solution with:

```
# Install ffi
sudo arch -x86_64 gem install ffi

# Re-install dependencies
arch -x86_64 pod install
```

**Comment by kaicoleridge** [comment]
Thank, that did the trick!
