### ISSUE TITLE
Syntax for pod_target_xcconfig

### ISSUE THREAD

**Issue by ivanvorobei** [CocoaPods/CocoaPods#10663]
Sorry, I not have problem. I want simple ask about correct way.

I have [podspec](https://github.com/ivanvorobei/SPPermissions/blob/main/SPPermissions.podspec) file and using `pod_target_xcconfig`. 

Now I added only one flag:

```
"SWIFT_ACTIVE_COMPILATION_CONDITIONS"  => "SPPERMISSIONS_CAMERA"
```

How I can add more flags? I mean syntax.

Maybe:

```
"SWIFT_ACTIVE_COMPILATION_CONDITIONS"  => "SPPERMISSIONS_CAMERA, SECOND_FLAG"
"SWIFT_ACTIVE_COMPILATION_CONDITIONS"  => "SPPERMISSIONS_CAMERA", "SECOND_FLAG"
"SWIFT_ACTIVE_COMPILATION_CONDITIONS"  => "SPPERMISSIONS_CAMERA" + "SECOND_FLAG"
```

**Comment by orta** [comment]
https://guides.cocoapods.org/syntax/podspec.html#pod_target_xcconfig
