### ISSUE TITLE
Base configuration warning even though custom xcconfig is set up correctly

### ISSUE THREAD

**Issue by mvandervelden** [CocoaPods/CocoaPods#10687]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- I have a project with a single workspace & Podfile, containing a main app project and a number of frameworks, organized in separate projects in the same workspace, and located in subfolders of the repository. The main app and the frameworks both have Cocoapods dependencies.
- I added custom xcconfig files on target level for an internal framework that uses Cocoapods, for each build config
- In the xcconfig file, I include the reference to the pod config file like this: `#include "../../../Pods/Target Support Files/Pods-SomeTarget/Pods-SomeTarget.debug.xcconfig"`. The `../../../` is needed here because the framework config lives under the `Components/SomeTarget/Configs`.
- I checked in the project file, and saw that the Cocoapods xcconfig file was 
- ran `pod install`

## What did you expect to happen?

Install all pods without any warnings, like before, because the reference to the `Pods-SomeTarget.debug.xcconfig` file is properly made in the xcconfig file.

## What happened instead?

Receiving warnings for each target and build configuration that has a custom xcconfig set:
> [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `SomeTarget` to `Target Support Files/Pods-SomeTarget/Pods-SomeTarget.debug.xcconfig` or include the `Target Support Files/Pods-SomeTarget/Pods-SomeTarget.debug.xcconfig` in your build configuration (`Components/SomeTarget/Configs/SomeTarget.debug.xcconfig`).

EDIT: If this is expected behavior, I'd also be happy with a guide on how to inhibit this warning message, as it's not relevant for this case.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : macOS 11.2.3 (20D91)
       Xcode : 12.5 (12E262)
         Git : git version 2.28.0
Ruby lib dir : /Users/Maarten/.rbenv/versions/2.7.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/Maarten/.rbenv/versions/2.7.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-check       : 1.1.0
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

workspace 'SomeWorkspace'

target 'SomeTarget' do
    project 'Components/SomeTarget/SomeTarget'

    pod 'Alamofire'
end

target 'SomeApp' do
    pod 'Sourcery'

    someapp_pods
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = "YES"
    end
end
```

**Comment by dnkoutso** [comment]
Does the project build? if it does then we just need to update the warning to ensure it catches this case. I think it uses regex to do so.

**Comment by dnkoutso** [comment]
relevant code to change/fix and write a test for https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb#L110-L126

**Comment by mvandervelden** [comment]
> Does the project build? if it does then we just need to update the warning to ensure it catches this case. I think it uses regex to do so.

Yes, the project does build

**Comment by dnkoutso** [comment]
@mvandervelden do you have a quick sample app by any chance? It helps speed up things a lot for me.

**Comment by mvandervelden** [comment]
@dnkoutso Thanks for investigating. I created a sample app for this, that reproduces the issue: https://github.com/mvandervelden/CocoaPodsXCConfigIssue

**Comment by dnkoutso** [comment]
awesome! thanks a lot will take a look next week most likely. Will mark this for 1.11.0 release as a fix.

**Comment by dnkoutso** [comment]
@mvandervelden this seems to be a different issue. 

Your `target.debug.xcconfig` has:
```
#include "../../Pods/Target Support Files/Pods-CocoaPodsXCConfigIssueFramework/Pods-CocoaPodsXCConfigIssueFramework.release.xcconfig"
#include "target.common.xcconfig"

SWIFT_OPTIMIZATION_LEVEL = -Onone
```

Shouldnt this be:

```
#include "../../Pods/Target Support Files/Pods-CocoaPodsXCConfigIssueFramework/Pods-CocoaPodsXCConfigIssueFramework.*debug*.xcconfig"
#include "target.common.xcconfig"

SWIFT_OPTIMIZATION_LEVEL = -Onone
```

Upon switching those the regex matches correctly already and no cocoapods changes needed.

**Comment by dnkoutso** [comment]
And the same is true for `target.release.xcconfig`. It should be:

```
#include "../../Pods/Target Support Files/Pods-CocoaPodsXCConfigIssueFramework/Pods-CocoaPodsXCConfigIssueFramework.release.xcconfig"
#include "target.common.xcconfig"
```

**Comment by dnkoutso** [comment]
ping @mvandervelden if possible to verify my comment above.

**Comment by mvandervelden** [comment]
Hi! 
🙈 I'm not at my keyboard for the next 12 days (typing this from phone), so I cannot verify this for you, but it seems like I made a stupid mistake copy-pasting and updating config files, which is definitely not beyond me to do.

And even worse I probably did the same thing twice for both my production issue and the sample project.

If you couldn't reproduce the warnings after fixing the paths, then I have all reason to believe that this was in fact the issue.

Feel free to close, sorry for the loss of your time. Thanks for the help! I will verify once I get back to my machine.

**Comment by dnkoutso** [comment]
Awesome! Thanks @mvandervelden and no worries! Please paste here if you see something I missed.

Yes the project built and no warning was printed when I made this change.

**Comment by mvandervelden** [comment]
I was able to verify that this was indeed the issue, fixed it on my side. Thanks again!
