### ISSUE TITLE
Cocoapods pod lib lint error "No Framework found"

### ISSUE THREAD

**Issue by dsp90** [CocoaPods/CocoaPods#10681]
# Report

I am using the latest Cocoapods version 1.10.1. But whatever was working before with version 1.9.3 is not working now as I am facing the errors in ```pod lib lint```. Whenever I run it gives errors. Xcode version is 12.5 and command lines version is 12.5.
I have built an xcframework using xcodebuild without any problems. Then I have pushed the xcframework with the Podspec file in a public repository.

## What did you do?

Run pod lib lint

## What did you expect to happen?
pod lint success

## What actually happened?

  The following build commands failed:
    	Ld /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/App-hejpghwoagyzopaxjbjqnyhmajlk/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/Binary/App normal x86_64
    	Ld /Users/xxxxxxx/Library/Developer/Xcode/DerivedData/App-hejpghwoagyzopaxjbjqnyhmajlk/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/Binary/App normal i386
    (2 failures)

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5 (12E262)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0

### PodSpec file

Pod::Spec.new do |spec|
  spec.name         = 'WeatherChannel'
  spec.version      = '0.0.1'
  spec.license      = { :type => "MIT", :file => "MIT License" }
  spec.description  = <<-DESC
  A small demo library for something very simple as weather.
  						DESC
  spec.homepage     = 'https://github.com/dsp90/WeatherChannelSDK'
  spec.authors      = { 'dsp90' => 'pawardushyant22@gmail.com' }
  spec.summary      = 'This is some library'
  spec.platform 	= :ios, "9.0"
  spec.source       = { :git => 'https://github.com/dsp90/WeatherChannelSDK.git', :tag => '0.0.1' }
  spec.vendored_frameworks = 'xcframework/WeatherChannel.xcframework'
  spec.swift_version    = '5.0'
end

## Project that demonstrates the issue

https://github.com/dsp90/WeatherChannelSDK.git

**Comment by dnkoutso** [comment]
For me this worked:

`pod lib lint --verbose`

```
    ** BUILD SUCCEEDED ** [8.187 sec]
    
   Testing with `xcodebuild`. 
 -> WeatherChannel (0.0.2)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

Pods workspace available at `/var/folders/g7/83vp4gbx2q58k1wd02f17b4r0000gn/T/CocoaPods-Lint-20210702-21954-t0rzj9-WeatherChannel/App.xcworkspace` for inspection.

WeatherChannel passed validation.
```

Xcode version 12.1
CocoaPods version 1.10.1.

**Comment by dsp90** [comment]
> For me this worked:
> 
> `pod lib lint --verbose`
> 
> ```
>     ** BUILD SUCCEEDED ** [8.187 sec]
>     
>    Testing with `xcodebuild`. 
>  -> WeatherChannel (0.0.2)
>     - NOTE  | xcodebuild:  note: Using new build system
>     - NOTE  | xcodebuild:  note: Building targets in parallel
>     - NOTE  | xcodebuild:  note: Using codesigning identity override: -
>     - NOTE  | [iOS] xcodebuild:  note: Planning build
>     - NOTE  | [iOS] xcodebuild:  note: Constructing build description
>     - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
> 
> Pods workspace available at `/var/folders/g7/83vp4gbx2q58k1wd02f17b4r0000gn/T/CocoaPods-Lint-20210702-21954-t0rzj9-WeatherChannel/App.xcworkspace` for inspection.
> 
> WeatherChannel passed validation.
> ```
> 
> Xcode version 12.1
> CocoaPods version 1.10.1.

Yes, it did worked the next morning.
