### ISSUE TITLE
CocoaPods 1.10 OneSignal MacAir M1 Issue

### ISSUE THREAD

**Issue by contactatfp** [CocoaPods/CocoaPods#10684]
# Report

## What did you do?

Successfully installed cocoapods-1.10.1

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install --repo-update
```

### Report

* What did you do?
*   update Podfile

* What did you expect to happen?
   The pods are installed in accordance with Podfile.lock
* What happened instead?
error

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.1 (20D74)
       Xcode : 12.5 (12E262)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Academy Alerts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Academy Alerts
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneSignalNotificationServiceExtension
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

end
```

### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.1/lib/ffi_c.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.1/lib/ffi_c.bundle - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.1/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.1/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.1/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.14.0/lib/ethon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by Bharanitharan06** [comment]
Am also facing the same issue, any suggestion for it.

**Comment by 98oktay** [comment]
Installing like this solved my problem.

`arch -x86_64 pod install --repo-update`

**Comment by antgel** [comment]
@98oktay Isn't that a plaster? Do you know what the root cause is?

**Comment by contactatfp** [comment]
Unfortunately, arch -x86_64 pod install --repo-update, didn't work either. thank you though.

**Comment by diaaserag** [comment]
Am also facing the same issue
in macbook pro m1
what should i do

**Comment by diaaserag** [comment]
https://armen-mkrtchian.medium.com/run-cocoapods-on-apple-silicon-and-macos-big-sur-developer-transition-kit-b62acffc1387

this link will help you god willing 
i solve the same problem

**Comment by javi10823** [comment]
same issue here

**Comment by peerobo** [comment]
What I did for temporary fix: (no need to select open with rosetta)
- open terminal
- delete cocoapods + ffi:
 `sudo gem uninstall cocoapods`
  `sudo gem uninstall ffi`
- install cocoapods again with arch command:
`arch -x86_64 sudo gem install cocoapods`
- do pod update/install with arch command:
`arch -x86_64 pod install`

**Comment by contactatfp** [comment]
> What I did for temporary fix: (no need to select open with rosetta)
> 
> * open terminal
> * delete cocoapods + ffi:
>   `sudo gem uninstall cocoapods`
>   `sudo gem uninstall ffi`
> * install cocoapods again with arch command:
>   `arch -x86_64 sudo gem install cocoapods`
> * do pod update/install with arch command:
>   `arch -x86_64 pod install`

This worked. Thank you.

**Comment by antgel** [comment]
@contactatfp Why close the issue? I don't think the above workaround is a proper fix.

**Comment by PeqNP** [comment]
I don't remember having to do this with a previous version of cocoapods. One of the dependencies (probably ffi) is not built for the new M1s.

I don't prefer pre-pending every command with `arch`. My work-around is to create an alias to `pod` in my `.zshrc`:
```
alias pod="arch -x86_64 pod"
```

**Comment by ThePredators** [comment]
> I don't remember having to do this with a previous version of cocoapods. One of the dependencies (probably ffi) is not built for the new M1s.
> 
> I don't prefer prepending every command with `arch`. My work-around is to create an alias to `pod` in my `.zshrc`:
> 
> ```
> alias pod="arch -x86_64 pod"
> ```

Bro i think we re meant to be friends !! I did the exact same stuff !!

**Comment by mostasim** [comment]
> Installing like this solved my problem.
> 
> `arch -x86_64 pod install --repo-update`

Thank you. It's work for me.
