### ISSUE TITLE
CocoaPods Install Failure with AgoraRTCEngine_IOS, ArgoraRTM and 'Firebase Analytics, Database and UI'

### ISSUE THREAD

**Issue by mjmuhamm** [CocoaPods/CocoaPods#10680]
* [y ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

updated Podfile and pod install 

## What happened instead?
Failed to install four pods, rather independent or together. Two work when iterating individually but others do not

## CocoaPods Environment
Error: missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.1/lib/ffi_c.bundle - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.1/lib/ffi_c.bundle

ℹ Please replace these two lines with the output of `pod env`.
There is no output.

## Project that demonstrates the issue
A blank project will reproduce this issue on my current system which is Macbook Air 2020 M1 Version 11.2.3 (BigSur)
![New Note](https://user-images.githubusercontent.com/53790225/119887642-6200ee00-bf02-11eb-9ba9-a39825976016.jpeg)
![New Note](https://user-images.githubusercontent.com/53790225/119887651-64634800-bf02-11eb-9904-6caedfd578de.jpeg)

**Comment by dnkoutso** [comment]
This looks like the `ffi` gem installation issue, please see this blog post https://betterprogramming.pub/ruby-on-apple-silicon-m1-macs-fb159849b2f5
