### ISSUE TITLE
"pod trunk register" verification link leads to 404

### ISSUE THREAD

**Issue by terry-citrix** [CocoaPods/CocoaPods#10697]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?
1. I ran `pod trunk register terry.replaced@citrix.com 'Terry Duchastel' --description='mac mini'`
1. I got a verification link.
1. I clicked on the verification link (in either chrome or safari -- I tried both).

Note: I tried this twice. I got the email pretty fast.
* https://trunk.cocoapods.org/sessions/verify/b77d89a8
* https://trunk.cocoapods.org/sessions/verify/d5b50f6e

## What did you expect to happen?
I expected that clicking on the verification link would inform me that my registration was successful.

## What happened instead?
I instead got a 404 response and the web page returned states: "Hello there, looks like you're lost. Technically its a 404, but we're not too fussed."

Regardless of whether the session was validated/created or not (and to be honest I can't tell if it was successful but I'm going to assume that it wasn't), it should not return a 404 error message.  It seems confusing to users -- to me anyways.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5 (12E262)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : (i removed our private repository links)

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

n/a

## Notes

When I do `pod trunk me` it now shows the following:

```
terry@Terrys-Mac-mini MdxFrameworkLoader % pod trunk me
  - Name:     Terry Duchastel
  - Email:    terry.replaced@citrix.com
  - Since:    June 6th, 20:49
  - Pods:     None
  - Sessions:
    - June 6th, 20:49 - October 12th, 21:53. IP: (_removed_) Description: mac mini
    - June 6th, 22:07 - October 12th, 22:18. IP: (_removed_) Description: mac mini
```

**Comment by harold-citrix** [comment]
Please help.  I have the same issue.

**Comment by dnkoutso** [comment]
@orta if you have any time, any possible reasons for this?

**Comment by orta** [comment]
This is usually when you have some sort of link checker checking the link ahead of time, so you're the 2nd person to hit it. The 404 means it's been checked and validated, and your CLI session should be fine.

**Comment by terry-citrix** [comment]
I checked and you're correct -- my CLI session was good.  I guess we can close this issue.
