### ISSUE TITLE
cocopods not install in bigsur

### ISSUE THREAD

**Issue by pradip-thummar-sttl** [CocoaPods/CocoaPods#10709]
[!] Oh no, an error occurred.  Search for existing GitHub issues similar to yours: https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+missing+compatible+arch+in+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues  If none exists, create a ticket, with the template displayed above, on: https://github.com/CocoaPods/CocoaPods/issues/new  Be sure to first read the contributing guide for details on how to properly submit a ticket: https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md  Don't forget to anonymize any private data!  Looking for related issues on cocoapods/cocoapods...  - When i run pod install in react-native project, getting below error on macOS Big Sur    https://github.com/CocoaPods/CocoaPods/issues/10557 [open] [1 comment]    03 Apr 2021   - Unable to install Braintree in pod file    https://github.com/CocoaPods/CocoaPods/issues/10614 [closed] [1 comment]    6 weeks ago   - pod install error    https://github.com/CocoaPods/CocoaPods/issues/10311 [closed] [8 comments]    4 days ago  and 7 more at: https://github.com/cocoapods/cocoapods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%2C%200x0009%29%3A%20missing%20compatible%20arch%20in%20%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle%20-%20%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.14.2%2Flib%2Fffi_c.bundle&type=Issues&utf8=✓  [!] `<PBXNativeTarget name=`OpenSchool` UUID=`13B07F861A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `12A74E48120E78F28B37EADF` for attribute: `build_phases`. This can be the result of a merge and the unknown UUID is being discarded.

**Comment by dnkoutso** [comment]
Not a valid issue report.
