### ISSUE TITLE
POD INIT ERROR

### ISSUE THREAD

**Issue by Anildemirci** [CocoaPods/CocoaPods#10728]
Anl-MacBook-Air:MyApp2 anil$ pod init

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]
    RubyGems : 3.2.15
        Host : macOS 11.4 (20F71)
       Xcode : 13.0 (13A5154h)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /usr/local/Cellar/ruby/3.0.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/usr/local/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'
/usr/local/lib/ruby/gems/3.0.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:112:in `open'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/init.rb:41:in `validate!'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Unknown+object+version.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - [Xcodeproj] Unknown object version.  Help Please
   https://github.com/CocoaPods/CocoaPods/issues/10604 [open] [6 comments]
   3 days ago

 - Xcode-beta 13.0 can't init project
   https://github.com/CocoaPods/CocoaPods/issues/10713 [open] [9 comments]
   4 hours ago

 - RuntimeError - [Xcodeproj] Unknown object version.
   https://github.com/CocoaPods/CocoaPods/issues/10259 [closed] [7 comments]
   21 Apr 2021

and 60 more at:
https://github.com/cocoapods/cocoapods/search?q=%5BXcodeproj%5D%20Unknown%20object%20version.&type=Issues&utf8=✓
Anl-MacBook-Air:MyApp2 anil$

**Comment by moniqueyj** [comment]
I have same problem ... 
tried
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

xcode-select: note: install 

pod init

anyone have a solution?

**Comment by BlankConan** [comment]
me too~

**Comment by Anildemirci** [comment]
When I open my file with xcode12.5 beta, the problem is solved. then while developing the project, open the file with xcode13 and run without any problem.

**Comment by BlankConan** [comment]
这个应该可以解决
https://github.com/CocoaPods/CocoaPods/issues/10746#issue-934728326

**Comment by dnkoutso** [comment]
This is an issue with Xcode 13 and the Xcodeproj gem which will be fixed soon. Closing as duplicate.

**Comment by dnkoutso** [comment]
`gem update xcodeproj` will fix this issue once Xcodeproj gem is updated to support Xcode 13.

**Comment by hassanyasin28** [comment]
- sudo gem install cocoapods
- pod init

**Comment by Emekaony** [comment]
> 

this worked for me too.
