### ISSUE TITLE
Module 'audioplayers' not found

### ISSUE THREAD

**Issue by kothanzaw** [CocoaPods/CocoaPods#10738]
I am just trying to write a small app to play audio from flutter project. Which is working on android .. but when i try for iphone It show me the error .. Module 'audioplayers' not found in xcode .. i tried others audioplayer, others libraries too.. but same issue.. xcode just telling me that module not found error .. others library are working well like share_perference .. , can some body help me ? I am going to mad ..

dependencies:
  audioplayers: ^0.19.0

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by paulb777** [comment]
There is not enough info here to investigate a CocoaPods issue. Please report to a flutter channel or provide a reproducible example without flutter.

**Comment by kenaitian** [comment]
Same issue as explained above and still no fix after exhausting my options
