### ISSUE TITLE
"pod install" saves modifies Podfile.lock because of different CocoaPods version

### ISSUE THREAD

**Issue by sryze** [CocoaPods/CocoaPods#10747]
When different team members use different versions of CocoaPods, the build will fail due to version mismatch in Podfile.lock. They must run `pod install` before building the project if another team member committed his version of Podfile.lock to VCS.

Example:

```
-COCOAPODS: 1.10.0
+COCOAPODS: 1.10.1
```

May I ask what is the point of having `COCOAPODS: x.y.z` field in the lock file? Isn't a lock file supposed to stay unchanged?

**Comment by orta** [comment]
Ensuring you have a consistent version of CocoaPods across your team is a pretty important thing - having the version in the lockfile (and using bundler) helps to insure that.

**Comment by dnkoutso** [comment]
Yes this is by design.
