### ISSUE TITLE
RuntimeError - [Xcodeproj] Unknown object version.

### ISSUE THREAD

**Issue by BlankConan** [CocoaPods/CocoaPods#10746]
出现这个问题的，我目前的解决方案：

![image](https://user-images.githubusercontent.com/38722095/124115338-427c5880-daa0-11eb-86c2-80e464611519.png)
查看 `Project Format`，降到最近使用的版本

如果还不行，执行下面命令进行尝试：
` sudo gem update xcodeproj`

**Comment by dnkoutso** [comment]
Closing as dup of https://github.com/CocoaPods/CocoaPods/issues/10713

**Comment by MrZhou1990** [comment]
It's doesn't work
