### ISSUE TITLE
subspec doesn't recognize  ../

### ISSUE THREAD

**Issue by LRH-iOS** [CocoaPods/CocoaPods#10740]
s.subspec 'TTT' do |ss|
        ss.source_files = '../TTT/Classes/*.{h,m,mm,c,cc}'
    end

A directory path other than the current directory is not recognized

**Comment by paulb777** [comment]
This is probably intentional since a podspec needs to be at the root of a repository to publish.

**Comment by dnkoutso** [comment]
@paulb777 is right. This is correct for root specs and subspecs.
