### ISSUE TITLE
run pod lib lint have one error

### ISSUE THREAD

**Issue by shichuanyang** [CocoaPods/CocoaPods#10758]
I created a framework that relies on another XCFramework. Now that Xcode has compiled successfully, I will get an error when I execute the command "pod lib lint AdvanceSDK.podspec --allow-warnings --skip-import-validation --use-libraries --verbose --no-clean --sources='https://github.com/CocoaPods/Specs.git'"

i have one error:xxxxxx.m  file not found: KSAdSDK/KSAdSDK.h

but My code has compiled successfully and runs successfully without any problems

Below is the contents of my podspec file

Pod::Spec.new do |s|
    s.name             = 'TESTSDK'
    
    s.version          = '3.2.4.7'
    s.ios.deployment_target = '9.0'
    s.platform     = :ios, "9.0"
    s.requires_arc = true
    
    s.license          = { :type => 'MIT', :file => 'LICENSE' }
    s.summary          = 'bayescom iOS SDK'
    s.description      = <<-DESC
    xxxx
    
    s.homepage         = 'http://www.xxxx.com/'
    
    s.author           = { 'bayescom' => 'http://www.xxxx.com/' }
    s.source           = { :git => 'https://github.com/xxxx/xxx.git', :tag => s.version.to_s }
    
    s.user_target_xcconfig = {'OTHER_LDFLAGS' => ['-ObjC']}
    
    valid_archs = ['i386', 'armv7', 'x86_64', 'arm64']
    # bitcode
    s.pod_target_xcconfig = { 'ENABLE_BITCODE' => 'NO', 'VALID_ARCHS' => valid_archs.join(' '), 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
    s.user_target_xcconfig = { 'ENABLE_BITCODE' => 'NO', 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
    
    s.default_subspec = 'Core'
    
    s.requires_arc = true
    s.static_framework = true
    
    s.subspec 'Core' do |core|
        core.source_files = 'TESTSDK/Core/**/*.{h,m}'
        core.frameworks = 'UIKit', 'Foundation', 'AdSupport'
    end
    
    s.subspec 'Adspot' do |adspot|
        adspot.dependency 'TEST/Core'
        adspot.source_files = 'TESTSDK/Adspot/**/*.{h,m}'
    end
    s.subspec 'KS' do |ks|
        ks.dependency 'TEST/Core'
        ks.dependency 'TEST/Adspot'
        ks.dependency 'KSAdSDK'
        ks.source_files =  'TESTSDK/Adapter/ks/**/*.{h,m}'
        ks.frameworks = 'Foundation', 'UIKit', 'MobileCoreServices', 'CoreGraphics', 'Security', 'SystemConfiguration','CoreTelephony', 'AdSupport', 'CoreData', 'StoreKit', 'AVFoundation', 'MediaPlayer', 'CoreMedia','WebKit', 'Accelerate', 'CoreLocation', 'AVKit','MessageUI','QuickLook', 'AddressBook'
        ks.libraries =  'z','resolv.9', 'sqlite3','c++','c++abi'
#        ks.ios.deployment_target    = '9.0'

    end
    
    
    s.xcconfig = {
        'VALID_ARCHS' =>  valid_archs.join(' '),
    }
    
end

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
