### ISSUE TITLE
Wrong framework selected if folder contains both Framework and XCFramework

### ISSUE THREAD

**Issue by grabbou** [CocoaPods/CocoaPods#10759]
Hey,

We are working on a [migration from a fat framework to XCFramework in Hermes](https://github.com/facebook/hermes/pull/543).

After migrating, we have noticed that the CI and certain contributors are getting the following error during the build time:

> ld: warning: ignoring file /Users/grabbou/Repositories/hermes/destroot/Library/Frameworks/iphoneos/hermes.framework/hermes, missing required architecture x86_64 in file /Users/grabbou/Repositories/hermes/destroot/Library/Frameworks/iphoneos/hermes.framework/hermes (3 slices)

The reason turned out being an extraneous `hermes.framework` file located under `/Users/grabbou/Repositories/hermes/destroot/Library/Frameworks/iphoneos/` that was a leftover from the previous build. You can clearly see this on a CircleCI failure, when the cache was not invalidated.

After removing `hermes.framework`, everything started working and `/Users/grabbou/Repositories/hermes/destroot/Library/Frameworks/iphoneos/hermes.xcframework` was used instead.

What is interesting, is that our `podspec` explicitly points to a correct file and any additional files within a folder should not be an issue:

>   spec.ios.vendored_frameworks = "destroot/Library/Frameworks/iphoneos/hermes.xcframework"

Tested on CocoaPods 1.10. 

Is this an expected Apple behaviour or an unwanted one?

**Comment by dnkoutso** [comment]
this does not seem a cocoapods issue at first glance. It seems a left over artifact from a previous build was causing issues.

**Comment by dnkoutso** [comment]
there isnt much cocoapods can do, you should clean derived data and re-run a build with the xcframework.
