### ISSUE TITLE
How to hook pod install error?

### ISSUE THREAD

**Issue by CLuRoad** [CocoaPods/CocoaPods#10757]
I want to print some tips after `pod install` executed failed. First of all, how to hook `pod install` failed?

Thanks!

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
