### ISSUE TITLE
Installing Kingfisher | pod install problem

### ISSUE THREAD

**Issue by zkllbc** [CocoaPods/CocoaPods#10779]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I try to install kingfisher with pod install command

## What did you expect to happen?

I expect to work 100%

## What happened instead?

Error occurred after running
![Screen Shot 2021-07-13 at 11 50 24 PM](https://user-images.githubusercontent.com/57118051/125714454-6baaa9e8-531c-41e9-9232-9d7d07d5a785.png)

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

I tried installing it with rosseta terminal, also follow all instruction with the same problem I encounter, but still nothing change.
![Screen Shot 2021-07-13 at 11 50 24 PM](https://user-images.githubusercontent.com/57118051/125714567-67788521-dd18-44ae-a769-64efe4e2d33c.png)

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
I am sorry but this is not a sufficient error report. please re-open a new issue, include a stacktrace and a sample app.
