### ISSUE TITLE
MacOS11.4 CocoaPods is not installed or is not configured properly.

### ISSUE THREAD

**Issue by jtojto5521** [CocoaPods/CocoaPods#10771]
MacOS11.4 CocoaPods is not installed or is not configured properly.
I tried the following for this, but this situation does not go away. Is there any way?

sudo gem  install cocoapods
pod set up

sudo gem install -n /usr/local/bin cocoapods
pod set up

**Comment by dnkoutso** [comment]
this is not a complete issue report. please use the issue template and provide reproducible steps or a sample app.
