### ISSUE TITLE
Is it possible to insert a script phase _before_ Copying Headers?

### ISSUE THREAD

**Issue by jeffwatkins** [CocoaPods/CocoaPods#10770]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
In our new module we generate some headers & source files. The headers should be copied into the resulting library. I'd like to ensure the script phase appears before the copy headers phase. The best I seem to be able to do is add a script phase with `:execution_position => :before_compile`.

## What did you do?
I created a new CocoaPod that uses a custom code generator to emit some *.h & *.m files which will be included in the final library. This code generator is integrated using a script phase definition with `:execution_position => :before_compile`.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5 (12E262)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
use_frameworks! :linkage => :static

platform :ios, '13.0'

target 'WFUIToolkitExample' do
  pod 'WFUIToolkit', :path => '../../common/WFUIToolkit/WFUIToolkit.podspec'

  target 'WFUIToolkitExampleTests' do
    inherit! :search_paths

    
  end
end
```

**Comment by dnkoutso** [comment]
This should be an easy enhancement! Not supported currently but the execution position dsl is easily extended.

**Comment by jeffwatkins** [comment]
If you give me a hint, I'd be happy to at least take a stab at it.

**Comment by dnkoutso** [comment]
I believe you need 2 PRs.

one in core to add to the DSL here https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L1050, perhaps add `before_copy_headers` and `after_copy_headers` and any specs (tests) required.

Then you'd need to update this logic https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/user_project_integrator/target_integrator.rb#L327-L350 which only right considers the before_compile case. You'd need to extend it slightly for the headers phase and properly set the script phase order. specs (tests) should be easy to add here as they already exist in `target_integrator_spec.rb` and are easy to cargo cult from to add support for what you want.

**Comment by dnkoutso** [comment]
Core PR https://github.com/CocoaPods/Core/pull/686

**Comment by dnkoutso** [comment]
and main cocoapods pr https://github.com/CocoaPods/CocoaPods/pull/10788

**Comment by dnkoutso** [comment]
support was added.

**Comment by jeffwatkins** [comment]
My goodness. Thanks so much. I hadn't even had a chance to noodle on this.
