### ISSUE TITLE
Problem with Pod install

### ISSUE THREAD

**Issue by zkllbc** [CocoaPods/CocoaPods#10778]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod init and pod install trying to install king fisher to my Xcode file

## What did you expect to happen?

To install it without a problem

## What happened instead?

error occur after hitting pod install

## CocoaPods Environment

pod env pod init
![Screen Shot 2021-07-13 at 11 50 24 PM](https://user-images.githubusercontent.com/57118051/125576489-a73c043c-e965-418b-a394-f9f9235f2609.png)

**Comment by dnkoutso** [comment]
this is not a sufficient error report. please ask in stackoverflow as this appears an environment issue.
