### ISSUE TITLE
CocoaPods how to create multiple projects in one workspace  with podspec file？

### ISSUE THREAD

**Issue by wulongwang** [CocoaPods/CocoaPods#10786]
for example 

platform :ios, '9.0'

workspace 'TestWorkSpace'
xcodeproj 'Project1/Project1.xcodeproj'
xcodeproj 'Project2/Project2.xcodeproj'

target 'Project1' do
    xcodeproj 'Project1/Project1.xcodeproj'
   #Pods for Project1
    pod 'SwiftyJSON', '~> 4.0'
end

target 'Project2' do
    xcodeproj 'Project2/Project2.xcodeproj'
   #Pods for Project2
    pod 'SwiftyJSON', '~> 4.0'
end

auto create multiple projects with podspec file

**Comment by dnkoutso** [comment]
I am not sure if this is a feature request or bug report. Please use the issue template and provide sufficient information to us so we can work it out.
