### ISSUE TITLE
`pod install` overwrites Project build settings "EXLUDED_ARCHS"

### ISSUE THREAD

**Issue by jsamr** [CocoaPods/CocoaPods#10798]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expect to happen?

After a successful operation (status 0), the project (not target) build settings should not be affected.

## What happened instead?

After a successful operation (status 0), project build settings for each type (debug, release) had its `EXCLUDED_ARCHS` overwritten.

Before pod install (excluded architecture set to `arm64`):

<img width="872" alt="Screenshot 2021-07-21 at 14 29 18" src="https://user-images.githubusercontent.com/3646758/126534330-8da47ba1-068a-43ab-bde4-50ad261b6c42.png">

After pod install (excluded architecture empty)::

<img width="875" alt="Screenshot 2021-07-21 at 14 31 23" src="https://user-images.githubusercontent.com/3646758/126534346-b62d6f8a-bb10-418b-b273-8d51dbabb95d.png">

Here is a git diff of my pbxproj showing changes introduced by `pod install`:

```diff
diff --git a/ios/TabacInfoService.xcodeproj/project.pbxproj b/ios/TabacInfoService.xcodeproj/project.pbxproj
index 498167f..7ed8dfd 100644
--- a/ios/TabacInfoService.xcodeproj/project.pbxproj
+++ b/ios/TabacInfoService.xcodeproj/project.pbxproj
@@ -1166,7 +1166,7 @@
 				COPY_PHASE_STRIP = NO;
 				ENABLE_STRICT_OBJC_MSGSEND = YES;
 				ENABLE_TESTABILITY = YES;
-				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;
+				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "";
 				GCC_C_LANGUAGE_STANDARD = gnu99;
 				GCC_DYNAMIC_NO_PIC = NO;
 				GCC_NO_COMMON_BLOCKS = YES;
@@ -1229,7 +1229,7 @@
 				COPY_PHASE_STRIP = YES;
 				ENABLE_NS_ASSERTIONS = NO;
 				ENABLE_STRICT_OBJC_MSGSEND = YES;
-				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;
+				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = "";
 				GCC_C_LANGUAGE_STANDARD = gnu99;
 				GCC_NO_COMMON_BLOCKS = YES;
 				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.2 (20D80)
       Xcode : 12.5 (12E262)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

I'd love to share a reproduction but it's closed sourced. It's a React Native 0.64.1 project, Podfile below:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'
target 'TabacInfoService' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  target 'TabacInfoServiceTests' do
    inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
    # Fix for mac m1, see https://stackoverflow.com/a/63955114
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  # https://documentation.onesignal.com/docs/using-onesignals-xcframework-for-mac-catalyst
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  pod 'Permission-Calendars', :path => '../node_modules/react-native-permissions/ios/Calendars.podspec'
end

# https://documentation.onesignal.com/docs/using-onesignals-xcframework-for-mac-catalyst
target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
end
```

**Comment by dnkoutso** [comment]
You are probably consuming a pod that changes `user_target_xcconfig`.

**Comment by dnkoutso** [comment]
I do not think there is much we can do here, you would need to contact the author if what I think it happening here is true.

**Comment by jsamr** [comment]
@dnkoutso Thank you for your prompt reply! Is there any way to override that behavior in my Podfile? I've tried to write the setting via `post_install` (`generated_projects`); but it didn't work. Obviously, my understanding of Cacaopods logic is limited.

**Comment by dnkoutso** [comment]
you may use a `post_integrate` hook but must call `save` in the xcodeproj you edit. You can also maybe in a `pre_install` hook edit or access the pod that does this to your project and remove that setting. It seems though that if you do this will your project compile then? The author must have intended to this in order to get their pod to work.

**Comment by jsamr** [comment]
@dnkoutso Thank you so much for those leads! Yes it would compile; if I `git checkout` the `pbxproj`  and get arm64 architecture excluded, everything works smoothly :ok_hand: ; Although I understand this is a provisory workaround and ultimately all the deps of this project should support arm64 arch.

**Comment by jsamr** [comment]
I've tried with `post_integrate` like so

```ruby
post_integrate do |installer|
  installer.generated_projects.each do |project|
    project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    project.save()
  end
end
```
But I am witnessing the same behavior. Am I missing out something? Perhaps the "project" I'm using is not the xcodeproj you are referring.

**Comment by jsamr** [comment]
Got it!

```ruby
post_integrate do |installer|
  project_path = "./TabacInfoService.xcodeproj"
  project = Xcodeproj::Project.open(project_path)
  project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  project.save()
end
```
Once again, thank you for your invaluable time.

**Comment by dnkoutso** [comment]
Awesome!

**Comment by kestarumper** [comment]
Coming from a `react-native` (version `0.69`) background.

I've had a similar problem, but for me, it was
```diff
- "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;
+ "EXCLUDED_ARCHS[sdk=iphonesimulator*]" = i386;
```

To my surprise, when I set a **target config** instead of _project config_ the `pod install` stopped overwriting it.
This lets the build pass.
