### ISSUE TITLE
You may have encountered a bug in the Ruby interpreter or extension libraries. GoogleMaps SDK

### ISSUE THREAD

**Issue by heeshala** [CocoaPods/CocoaPods#10797]
I tried to install GoogleMaps SDK with the following podfile

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'GoogleMaps'

end
```
But pod install/update is aborted with the error of ```You may have encountered a bug in the Ruby interpreter or extension libraries```. I am developing a flutter project for ios

**Comment by paulb777** [comment]
Please fill out the issue template
