### ISSUE TITLE
 Dependency error when generate_multiple_pod_projects=YES

### ISSUE THREAD

**Issue by magic3584** [CocoaPods/CocoaPods#10818]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

generate_multiple_pod_projects: true

## What did you expect to happen?

 Install all pod dependencies correctly.
Or how can I exclude some dependency.

## What happened instead?

<img width="1293" alt="WX20210729-172323@2x" src="https://user-images.githubusercontent.com/6275110/127467556-4a214bd7-dc65-42ea-964f-3a8b94dadd79.png">

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories :
               master - git - https://github.com/CocoaPods/Specs.git @ bfb989664f9df6f1bd62fdbf5ffbb627a6fd32c1

               trunk - CDN - https://cdn.cocoapods.org/

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.4
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.5.0
cocoapods-try          : 1.2.0
```

**Comment by dnkoutso** [comment]
this might be expected and was a warning when multiple pods project feature was launched. Read this https://blog.cocoapods.org/CocoaPods-1.7.0-beta/

<img width="790" alt="Screen Shot 2021-07-29 at 3 29 37 PM" src="https://user-images.githubusercontent.com/310370/127491954-e7799b98-83e3-493f-b152-00fd1db606e6.png">

Having said that, please upload a sample app showing the issue so we can verify.

It is recommended to reach to the pod author and update public headers to use `<>` vs `""` so it can work across projects.

**Comment by magic3584** [comment]
Sorry, I have uploaded a demo here [https://github.com/magic3584/PodMultiProjectsDemo](https://github.com/magic3584/PodMultiProjectsDemo)

> It is recommended to reach to the pod author and update public headers to use <> vs "" so it can work across projects.

If I have tens of dependency,  what I can do is fork and change `""` to `<>` in every dependency?

Or is there any way to disable dependency explicitly? [issue9274](https://github.com/CocoaPods/CocoaPods/issues/9274#issue-509539911) is referring this but it is not fixed  seemly.

**Comment by dnkoutso** [comment]
You can write perhaps a `post_install` hook to update the header files of all the dependencies you want.

You can also not use multiple pods projects and use a single project instead as it is the default. Yes we have #9274 open still.

**Comment by magic3584** [comment]
> You can write perhaps a post_install hook to update the header files of all the dependencies you want.

How can I do this? By setting the **Header Search Path** or other? Could U please make a little demo?

**Comment by dnkoutso** [comment]
You could potentially open the file and edit it in place using standard Ruby.

```ruby
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["HEADER_SEARCH_PATHS"] = "..."
    end
  end
```

etc.

You have access to _everything_ cocoapods uses, including `pod_target.rb` which represents a single pod target and also your own project and the Pods project.

I am not clear on the fix you have to apply but I do believe you will be able to change anything you'd like to accomplish your patch.

For now going to close this as I do not expect any action from this issue.
