### ISSUE TITLE
Runtime error when building with XCFramework containing a dynamic framework as vendored_frameworks 

### ISSUE THREAD

**Issue by dreddmannEG** [CocoaPods/CocoaPods#10811]
* [ x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Created a new ios app in xcode
2. install/init pod to use a vendored_frameworks that is an XCFramework containing a dynamic framework
3. build/run in xcode

## What did you expect to happen?

The application to run with no errors

## What happened instead?

xcode had a runtime error:

```
dyld: Library not loaded: @rpath/Evergage.framework/Evergage
Reason: image not found
```

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.7 (19H1217)
       Xcode :  ()
         Git : git version 2.30.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'MyTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!

  # Pods for CocoaTest
  pod 'Evergage', :path => '../evergage-sdk-ios-1.3.2'
  
end
```

Project that demonstrates the issue

The project can be found in [this repo](https://github.com/dreddmannEG/vendoredFrameworksIsue) in the "MyTestApp" folder. The only difference between this and our working podspec is using the dynamic vendored_frameworks does not work and using the static one does. The path to the static framework is commented out in the podspec file below the dynamic vendored_frameworks definition.

I found a similar issue [here](https://github.com/CocoaPods/CocoaPods/issues/10634) where the workaround was to remove arm64e architectures, but we would like to keep spport for arm64e and still get this to work

**Comment by dnkoutso** [comment]
is this runtime issue showing on M1? I do not not have an M1 machine to be able to repro.

**Comment by hashtag-smashtag** [comment]
We don't have M1 machines either.  Repro-ing on non-M1 machines 👍

**Comment by dnkoutso** [comment]
<img width="506" alt="Screen Shot 2021-07-31 at 12 09 11 AM" src="https://user-images.githubusercontent.com/310370/127711788-e92a63c4-6d7e-405b-a606-322643d47802.png">

<img width="1792" alt="Screen_Shot_2021-07-31_at_12_09_15_AM" src="https://user-images.githubusercontent.com/310370/127711798-8a49bd86-8dc4-4e9e-8c08-e35c33f6c7b9.png">

Using CocoaPods master and Xcode 13.0 this seems to be working fine for me. Including the dynamic version as well.

**Comment by dnkoutso** [comment]
OK I think this is already fixed on master branch (1.11.0).

I was able to repro the crash on 1.10.2.

Not sure exactly which change has done it though to point you at. Please try master branch using Bundler.

**Comment by dnkoutso** [comment]
@hashtag-smashtag @dreddmannEG please confirm issue is fixed with 1.11.0 (master branch). Once you do I will close the issue.

**Comment by hashtag-smashtag** [comment]
@dnkoutso I followed this [Unreleased Features ](https://guides.cocoapods.org/using/unreleased-features) guide, git branch `master`, used the `spod` alias.  It still reports version `1.10.2` but I suspect that's because versions aren't bumped until release?

Anyhow, indeed, it appears the dynamic XCFramework was brought into the app, and the app no longer crashes at runtime! 
 Looking forward to the next release, so we can update our podspec to optionally support our vendored XCFramework in dynamic flavor.  👍

**Comment by dnkoutso** [comment]
> @dnkoutso I followed this Unreleased Features guide, git branch master, used the spod alias. It still reports version 1.10.2 but I suspect that's because versions aren't bumped until release?

yes master still has 1.10.2 as its version, its not bumped as part of the release process. As long as the SHA is the one you want you are good!

Will ship 1.11.0 in August maybe 2-3 weeks from now.

**Comment by dnkoutso** [comment]
I meant a beta of 1.11.0 so most definitely one in August.
