### ISSUE TITLE
path_provider-2.0.2 / Flutter Build Issue IOS

### ISSUE THREAD

**Issue by lyntree** [CocoaPods/CocoaPods#10821]
Hi,

Can you please read up on this issue posted with Flutter and Work together please as I have now other developers contacting me with the same issue, whatever happened with the last build of Flutter or Cocoapods has broken my build tool and I cannot build anything for IOS as it always throws an issue with Flutter H, but after looking at this, I don't think the issue is with system links or the flutter h, but more to do with the building tools such as CocoaPods.

https://github.com/flutter/flutter/issues/86997

**path_provider-2.0.2**

I've already been onto Flutter about this issue, and between Flutter and Cocoa Pods, I do believe the issue is with Cocoapods, as it will not pass this file, add to that when I make changes to the pods within Xcode (it doesn't want to save anything) so I've raised that directly as a bug with Apple as I have an M1 

**Pods Version:** Pods 1.10.2

**Comment by orta** [comment]
I think we're going to need some kind of repro to look at otherwise this looks pretty un-actionable from CocoaPods' side from a quick look though the linked issue

**Comment by dnkoutso** [comment]
@orta is right. We cannot determine or clearly say this is a cocoapods issue. You have to provide a sample app _without_ Flutter that clearly shows the issue or a similar one for us to diagnose.

Will keep this issue open for a few days until a sample app without Flutter is uploaded, otherwise it will be closed.

**Comment by lyntree** [comment]
Hi Both,

Thanks for replying, at the moment there's about 5 of us trying to work out the bug but we do suspect its something to do with the Pod, we will update you as soon as we find something x

**Comment by lyntree** [comment]
Just an update, It's up to you guys if you want to close this or not but I have discovered an issue with that package to do with cocoa pods, I've raised that with the Flutter Team and waiting to hear back.

**Comment by dnkoutso** [comment]
Thanks!
