### ISSUE TITLE
pod framework does not generate dsym file?

### ISSUE THREAD

**Issue by buptwsg** [CocoaPods/CocoaPods#10829]
# Report

## What did you do?

Use pod framework command to build SDWebImage.podspec into a xcframework.

## What did you expect to happen?
1. dsym file is generated.
2. the universal framework contains architecture armv7.

## What happened instead?

1. no dsym file is generated.
2. the universal framework contains arm64, i386, x86_64.

### Stack

```
   CocoaPods : 1.10.2
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.7 (19H1323)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /usr/local/Cellar/ruby/2.7.2/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 5bfad26960b880f7f09fc559211e15dd74f5ed04

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

## Project that demonstrates the issue

https://github.com/SDWebImage/SDWebImage

Download the source, and run `pod framework SDWebImage.podspec`

**Comment by dnkoutso** [comment]
`pod framework` is not an official cocoapods command. please file an issue to the corresponding github repo.
