### ISSUE TITLE
Errno::EACCES - Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by tcwijekoon** [CocoaPods/CocoaPods#10837]
I am working on react native project
when run pod install i got this error
   Errno::EACCES - Permission denied @ dir_s_mkdir - projectpath/ios/Pods/CocoaAsyncSocket/7.6.5-065fd

and at the end of template

[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
This is not a sufficient issue report. Please use the issue template and also provide a sample app or steps to reproduce the issue.

From a quick glance this seems like a permission issue so try `chmod` the projectpath/ios.

**Comment by tcwijekoon** [comment]
In my projectpath there was a folder name with a space, so I moved full project to a new path without space. not it works.
seems  in reactnative build not accept space for path. 
issue solved.

Thank you

**Comment by dnkoutso** [comment]
awesome thanks for reporting back! might help others!
