### ISSUE TITLE
Collision with Fastlane due to 

### ISSUE THREAD

**Issue by rodrigoelp** [CocoaPods/CocoaPods#10836]
# Report

Though this might not be directly associated with Cocoapods, it is quite common for CI environments to use cocoapods and fastlane under a similar configuration.
As fastlane continues to progress with their evolution, solving the AppStore Connect API they have updated addressable to a higher version to the one contained in CocoaPods, causing a clash.

This issue to to address and update this dependency for CocoaPods.

## What did you do?

Configured my Gemfile as stated below:

```ruby
source "https://rubygems.org"

gem "cocoapods", "~> 1.10.2"
gem "fastlane", "~> 2.190.0"
```

## Steps to reproduce
- Run `bundle install`

## What did you expect to happen?

- Both fastlane and cocoapods are installed.

## What happened instead?
```
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem "addressable":
  In snapshot (Gemfile.lock):
    addressable (= 2.7.0)

  In Gemfile:
    cocoapods (~> 1.10.2) was resolved to 1.10.2, which depends on
      addressable (~> 2.6)

    fastlane (~> 2.190.0) was resolved to 2.190.0, which depends on
      addressable (< 3.0.0, >= 2.8)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

### Stack

```
   CocoaPods : 1.10.2
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
    RubyGems : 3.2.8
        Host : macOS 11.5 (20G71)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.28.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/rod/dev/product/gems/ruby/2.7.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

**Comment by rodrigoelp** [comment]
Never mind, found the problem might have been my Gemfile.lock stating the incorrect dependency.

**Comment by dnkoutso** [comment]
Also taken care of for 1.11.0 see this previous issue https://github.com/CocoaPods/CocoaPods/issues/10802
