### ISSUE TITLE
Pod Install Generates Different Checksum for Each Team Member

### ISSUE THREAD

**Issue by stherold** [CocoaPods/CocoaPods#10839]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

We integrate a framework which is only locally stored in the project folder (details below). Me and my team members have run pod install. All from the same commit on the same branch. So same preconditions.

## What did you expect to happen?

We want a Podfile.lock has the same checksums for each team member but we don't know what we can do.

## What happened instead?

Everybody of us gets different checksums for the only SDK we integrate which is a local SDK in our apps project folder. In this local Podspec they specify 
```
s.source = { path => 'TICKeosLibraryIoki.embeddedframework' }
```
This leads to the case that the absolute path to the local podspec is added to `Pods/Local Podspecs/EOSMobileShop.podspec.json`:
```
  "source": {
    "<HOME>/<path_to_project>/dependencies/TICKeosTicketManager/EOSMobileShop.podspec": "TICKeosLibraryIoki.embeddedframework"
  },
```
The checksum in Podfile.lock is generated from this JSON. Since each of us has our project in a different location on our Mac, the checksum is different for each team member.

My question now, why can't this be a path relative to the project folder? 🤔

### Stack

```
   CocoaPods : 1.10.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.5.1 (20G80)
       Xcode : 12.5 (12E262)
         Git : git version 2.32.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 1b0d9ad853333bbebe2d028d0e91fe01a14f322e

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: <HOME>/.gem/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'OurApp' do 
pod 'EOSMobileShop', :path => './dependencies/TICKeosTicketManager/EOSMobileShop.podspec', :binary => true
end
```

## Project that demonstrates the issue

Sorry I don't have this.

**Comment by dnkoutso** [comment]
This seems expected? When you consume a pod via `:path` its `source` is not used so you should remove the `HOME` from s.source in order to force the checksum to be the same always.

we use countless of local pods without an issue.

**Comment by stherold** [comment]
I cannot remove the `<HOME>` from the JSON file since it is auto-generated by cocoapods. In the podspec which I have control ober there are all relative paths.

**Comment by stherold** [comment]
Then I get an error that it is required ;-)
```
[!] The `EOSMobileShop` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `source`.
```

**Comment by dnkoutso** [comment]
ah that is something we can improve on if a pod gets consumed via `:path` from Podfile.

Can you try something like:
```ruby
s.source       = { git: 'Not Published', tag: "1.0.0" }
```

?

**Comment by stherold** [comment]
Man you saved my life :D It build sfor me still need to check with all our team mmebers that a `pod install` doesn't produce any change. And yes that could be improved by CocoaPods to not require `s.source { ... }`

Many thanks 👍

**Comment by dnkoutso** [comment]
it does but we can improve not to output this message if this pod is consumed via `:path`.

**Comment by dnkoutso** [comment]
no problemo!

**Comment by stherold** [comment]
I just wonder how Cocoapods is then finding the `TICKeosLibraryIoki.embeddedframework` when it is not specified anymore in the podspec. In the Podfile I just link to the folder containing the podspec but how does CP know that the source is this embeddedframework ?

**Comment by dnkoutso** [comment]
Is this a vendored framework? You need to specify it in vendored_frameworks
or source_files.

**Comment by stherold** [comment]
Ah on the second look they do exactly that 👍

**Comment by dnkoutso** [comment]
@stherold seems like things are OK now, going to close. We can re-open if needed.
