### ISSUE TITLE
引入头文件 代码补全 不起作用

### ISSUE THREAD

**Issue by yushuyi** [CocoaPods/CocoaPods#10844]
Xcode 12.5
cocoapods 1.10.2

目前我通过 CocoaPods 以静态库的形式 引入了一些第三方库，但是在调用的工程 import时 没有代码补全， 网上尝试了很多办法，包括 User Header Search Paths 也不行。 有遇到过类似的问题吗？

![image](https://user-images.githubusercontent.com/1632740/128492107-6b1fd5dd-47f1-43f7-a6ca-11dcea3b08f3.png)
![image](https://user-images.githubusercontent.com/1632740/128492142-2f90acb5-175d-43bf-8d33-0b952e065607.png)
![image](https://user-images.githubusercontent.com/1632740/128492165-e35f058c-9305-4c25-9353-f435a7edbf59.png)

**Comment by dnkoutso** [comment]
I am sorry I cannot understand the language. Please file a new issue following the issue template and in English so I can assist.

**Comment by yushuyi** [comment]
please
