### ISSUE TITLE
The static library introduced by CocoaPods cannot code completion header files

### ISSUE THREAD

**Issue by yushuyi** [CocoaPods/CocoaPods#10852]
Xcode 12.5
cocoapods 1.10.2

At present, I have introduced some third-party libraries in the form of static libraries through CocoaPods, but there is no code completion when the project is called. I tried many methods online, including "User Header Search Paths". Have you encountered a similar problem?

![image](https://user-images.githubusercontent.com/1632740/128492107-6b1fd5dd-47f1-43f7-a6ca-11dcea3b08f3.png)
![image](https://user-images.githubusercontent.com/1632740/128492142-2f90acb5-175d-43bf-8d33-0b952e065607.png)
![image](https://user-images.githubusercontent.com/1632740/128492165-e35f058c-9305-4c25-9353-f435a7edbf59.png)

**Comment by dnkoutso** [comment]
Can you try `import <Masonry...>` instead?

**Comment by yushuyi** [comment]
@dnkoutso It doesn't work either

**Comment by dnkoutso** [comment]
<img width="1512" alt="Screen Shot 2021-08-11 at 10 40 18 AM" src="https://user-images.githubusercontent.com/310370/128989450-d6e7d4dd-a95f-4644-a3ac-1ea0630453d9.png">

works fine for me. Not sure what the issue but does not appear to be cocoapods related for now.

**Comment by dnkoutso** [comment]
Going to preemptively close and we can re-open if needed.

**Comment by yushuyi** [comment]
@dnkoutso Can you send me the demo to see

**Comment by dnkoutso** [comment]
Its a standard new application from Xcode and added a Podfile from the issue report.

**Comment by prideyao** [comment]
Hi, I got a similar problem on Xcode 12.5, the pod name can be completed correctly:
![image](https://user-images.githubusercontent.com/87849426/132694907-9d30bd9a-989b-4da8-bad7-91b1ab6cade2.png)

but it couldn't find the header files under the pod
![image](https://user-images.githubusercontent.com/87849426/132695169-8d9dd446-e4ef-4dd5-a413-de554211e7f4.png)

only when the file undler the /Header is not a symlink can it be recognized (by the way, on Xcode 12.3 symlinks could be found in this way)
![image](https://user-images.githubusercontent.com/87849426/132696064-3d7655a1-3caa-4ecd-a367-32a6d0802b5c.png)

One more strange phenomenon, when I delete the right  angle bracket '>' and press Esc, the completion works again
![image](https://user-images.githubusercontent.com/87849426/132696673-ddb6146b-1819-4013-8147-891c7f3bbfce.png)

Is this a bug of Xcode 12.5? or is this a known problem?
couldn't found much info on google, appreciate for any tips

**Comment by prideyao** [comment]
@dnkoutso
