### ISSUE TITLE
Got error while pod installation.

### ISSUE THREAD

**Issue by Nishant395** [CocoaPods/CocoaPods#10862]
Command :-
pod install

Error:-
You have encountered a bug in the Ruby interpreter or extension libraries. 
Bugs reports are welcome.

How can I solve this issue?

**Comment by dnkoutso** [comment]
This seems like a ruby environment issue. Please ask in stackoverflow instead. We are unable to diagnose with given information.

**Comment by Nishant395** [comment]
Hie!
I was trying to install some pods like 'FacebookCore' , 'netfox' , 'Kingfisher'.
Then I got that error.
