### ISSUE TITLE
Precompiled XCFrameworks fail to integrate when using non-standard Xcode configuration names

### ISSUE THREAD

**Issue by pietbrauer** [CocoaPods/CocoaPods#10869]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

My Xcode project has multiple configurations, which I separate by prefixing the default configurations, e.g. eDebug, kDebug, pDebug. In this project I have to integrate a static xcframework (amongst others "regular" pods) via CocoaPods.

## What did you expect to happen?

My Frameworks are integrated, I get no warning and can build the app.

## What happened instead?

CocoaPods gives me the warning `[CP] Unable to find matching .xcframework slice in '<Project Path>/Pods/SAPFiori/SAPFiori.xcframework SAPFiori framework ios-arm64 ios-x86_64-simulator ios-x86_64-maccatalyst' for the current build architectures (arm64 x86_64).` for every precompiled xcframework I try to integrate.

Next to the warning I also can't import any of the Pods.

I think that the issue lies in the shell scripts copying the xcframeworks as this gives the following error: `SAPSample/Pods/Target Support Files/Pods-SAPSample/Pods-SAPSample-frameworks.sh: line 42: source: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code` the variable `source` is never set using the prefixed `Debug` configuration.

When integrating _without_ a prefixed configuration it is set to `/Users/pietbrauer/Library/Developer/Xcode/DerivedData/SAPSample-fqkfnwlaucblpxcmlwdiejucfoft/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/SAPCommon/SAPCommon.framework`

### Stack

```
   CocoaPods : 1.10.2
        Ruby : ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
    RubyGems : 3.2.22
        Host : macOS 11.5.1 (20G80)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.32.0
Ruby lib dir : /usr/local/Cellar/ruby/3.0.2/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ a8cae227e699e4b25ca5fc9e9462340510885696

               sap - git - https://github.com/SAP-samples/cloud-sdk-ios-specs @ db3432abe40acbe912da96bf8a4dc98e175d1011

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/pietbrauer/.gem/bin/pod
```

### Plugins

```
claide-plugins             : 0.9.2
cocoapods-art              : 1.0.4
cocoapods-catalyst-support : 0.1.2
cocoapods-clean            : 0.0.1
cocoapods-deintegrate      : 1.0.4
cocoapods-dependencies     : 1.0.0.beta.1
cocoapods-plugins          : 1.0.0
cocoapods-rome             : 1.0.1
cocoapods-search           : 1.0.1
cocoapods-stats            : 1.1.0
cocoapods-trunk            : 1.5.0
cocoapods-try              : 1.2.0
cocoapods_debug            : 0.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/SAP-samples/cloud-sdk-ios-specs'
platform :ios, '14.1'

target 'Sample' do
  use_frameworks!

  pod 'SAPOData'
  pod 'SAPFiori'
  pod 'SAPFioriFlows'
  pod 'SwiftGen'
  pod 'SwiftLint'
end
```

## Project that demonstrates the issue

Project: https://github.com/pietbrauer/cocoapods-xcframeworks-integration-issue
Diff: https://github.com/pietbrauer/cocoapods-xcframeworks-integration-issue/compare/prefix-config

**Comment by dnkoutso** [comment]
CocoaPods does not know that `eDebug` is the default debug configuration.

This podfile change worked for me on your `prefix-config` branch.

```ruby
# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/SAP-samples/cloud-sdk-ios-specs'
platform :ios, '14.0'

project 'SAPSample.xcodeproj', 'eDebug' => :debug


target 'SAPSample' do
  use_frameworks!

  pod 'SAPCommon'
end
```

See more here https://guides.cocoapods.org/syntax/podfile.html#project

Going to preemptively close we can re-open if needed.
