### ISSUE TITLE
forcereact failed. Command failed: pod update. No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by terlim-sfdc** [CocoaPods/CocoaPods#10875]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by terlim-sfdc** [comment]
ℹ Please replace these two lines with what you did.
e.g. Run pod install. or pod update

What did you expect to happen?
ℹ Please replace these two lines with what you expected to happen.
e.g. Install all pod dependencies correctly.

What happened instead?
ℹ Please replace these two lines with of what happened instead.

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=uninitialized+constant+Pod%3A%3ABuildType&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
/Users/terence.lim
forcereact failed

Command failed: pod update
terence.lim@terence-ltmnvvw ~ % pod update
[!] No `Podfile' found in the project directory.
terence.lim@terence-ltmnvvw ~ % pod install
[!] No `Podfile' found in the project directory.
terence.lim@terence-ltmnvvw ~ % 


CocoaPods Environment
ℹ Please replace these two lines with the output of pod env.

### Stack

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.5.1 (20G80)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.32.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

terence.lim@terence-ltmnvvw ~ % 

Project that demonstrates the issue
ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by terlim-sfdc** [comment]
Hi @dnkoutso - i noticed you closed this case, but I didn't see any comments. I'm stuck and not sure what to do. 
I tried running pod install and it keeps giving me No Podfile found in the project directory. How do I fix that?
Do you think you can help?

**Comment by paulb777** [comment]
@terlim-sfdc Please see the error message and make sure you have a `Podfile`. If you're still stuck, issues here should adhere to the template with a repro case.
