### ISSUE TITLE
Can a pod be undeprecated?

### ISSUE THREAD

**Issue by chriskilding** [CocoaPods/CocoaPods#10874]
I see two ways to deprecate a pod:

```
spec.deprecated = true
```

```
spec.deprecated_in_favor_of = "<pod-id>"
```

Question 1: Does the deprecation apply at the pod level (i.e. it implicitly deprecates all previous published versions too), or does it only apply to the pod version with the `spec.deprecated` marker?

Question 2: Can you undeprecate a pod in the future? Is it enough to simply remove the `spec.deprecated`or `spec.deprecated_in_favor_of` line from the Podspec, and publish a new version? Or do you have to set `spec.deprecated = false` in the Podspec?

**Comment by dnkoutso** [comment]
I am not sure. i think so? If you publish a new version with those entries removed then I think cocoapods will not output any warning.

cc @orta maybe for trunk related info, if any?

**Comment by orta** [comment]
I'm pretty sure it works by deprecating a _version_ and so removing that syntax will mean the new version is undeprecated.

**Comment by dnkoutso** [comment]
yeap I thought the same.

Going to close since I see no action needed here. Will re-open if needed.
