### ISSUE TITLE
Problem when install xcframework

### ISSUE THREAD

**Issue by paulo-coutinho** [CocoaPods/CocoaPods#10878]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

When i install my xcframework using cocoapods sometimes it generate the SH file correctly and sometimes it generate without the correct lines. 

I have on one machine the correct file and in other the wrong file:

![image](https://user-images.githubusercontent.com/395096/130133055-b6c8805c-9225-4349-9ff9-fc74d742f248.png)

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

pod install
or
pod update

## What did you expect to happen?

Our xcframework installed correctly

## What happened instead?

When i execute my app i get:

```
dyld: Library not loaded: @loader_path/Frameworks/ezored.framework/ezored
  Referenced from: /private/var/containers/Bundle/Application/323A8B7B-4F1D-43C1-BDEF-47CC9DF2DA64/Sample.app/Sample
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 12.5 (12E262)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 19e59c966b4b56cc5f66c911ae4029d6862342b6

               findawayworld - git - https://github.com/FindawayWorld/FindawayPods.git @ 0119d85c029ae56572e21ded5e042c8ff68f96a8

               trunk - CDN - https://cdn.cocoapods.org/
               ubook-editora - git - git@github.com:ubook-editora/pods-repository.git @ 2b43d29a1fd0705e19e873d76ed67906ad6becbe

```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.10.1_1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

https://github.com/ezored/ezored/tree/version-3/projects/ios/Sample

**Comment by dnkoutso** [comment]
@paulo-coutinho the screenshot on the right looks like the latest 1.11.0 beta. I can tell from the `paths=` line...

it seems you are using a different version across two different machines. Its possible 1.11.0 has fixed things related to installing this xcframework.

**Comment by dnkoutso** [comment]
I highly recommend using bundler to manage versions of gems across machines.

**Comment by dnkoutso** [comment]
The left side screenshot looks like an older version of cocoapods.

It tried with 1.11.0.beta.2 on your sample project and it installed the xcframework correctly.

For now going to close and recommend to use 1.11.0.beta.

**Comment by paulo-coutinho** [comment]
Hi,

I have installed from gem/bundler and now it is working with beta version.

Do you know when it will be released?

Thanks.
