### ISSUE TITLE
Errno::ENOENT - No such file or directory @ rb_sysopen 

### ISSUE THREAD

**Issue by himanshuagnihotri801** [CocoaPods/CocoaPods#10880]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Pods not installed throwing error: Errno::ENOENT - No such file or directory @ rb_sysopen - https://webservices.flickfusion.net/sdk/spin/2FEDC124-DAC5-2731-328B-190817E04655/FFSpinSDK-4.0.4.podspec

## CocoaPods Environment

pods version 1.10.1 on my machine

## Project that demonstrates the issue

while installing the below pod we are getting above error -
pod 'FFSpinSDK', :podspec => 'https://webservices.flickfusion.net/sdk/spin/2FEDC124-DAC5-2731-328B-190817E04655/FFSpinSDK-4.0.4.podspec'

**Comment by himanshuagnihotri801** [comment]
<img width="1182" alt="Screenshot 2021-08-20 at 12 25 30 PM" src="https://user-images.githubusercontent.com/89242716/130193371-d3812867-7a9e-496e-a872-419be3cb654d.png">

**Comment by dnkoutso** [comment]
this seems you cant access https://webservices.flickfusion.net/sdk/spin/2FEDC124-DAC5-2731-328B-190817E04655/FFSpinSDK-4.0.4.podspec. 

I tried it in a sample app and it works for me:

```
he Gemfile's dependencies are satisfied
Analyzing dependencies
Fetching podspec for `FFSpinSDK` from `https://webservices.flickfusion.net/sdk/spin/2FEDC124-DAC5-2731-328B-190817E04655/FFSpinSDK-4.0.4.podspec`
Downloading dependencies
Installing FFSpinSDK (4.0.4)
Installing SFHFKeychainUtils (1.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
```

Make sure you have internet access to access this file. before using `:podspec`.

Going to preemptively close we can re-open if we find a bug or enhancement.

**Comment by dnkoutso** [comment]
Try `pod cache clean --all` as well and `rm -rf ~/.cocoapods/repos` although I dont think either are related.

**Comment by himanshuagnihotri801** [comment]
Internet is running fine still we are getting error. Also we have access to the url . Still facing this issue on my machine. Do not know how can I fix it. Let us know if you can help me out here.

**Comment by dnkoutso** [comment]
try using different ruby version? perhaps 2.x? If so I can re-open this issue for Ruby 3.0?

Look into cocoapods sources and put out `puts` statements. Perhaps there an actual bug we should fix.

**Comment by himanshuagnihotri801** [comment]
I am using ruby 3.0. `ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]` .

**Comment by dnkoutso** [comment]
Yes try using 2.x?
