### ISSUE TITLE
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275: [BUG] Bus Error at 0x00000001025ac000

### ISSUE THREAD

**Issue by larsbentz** [CocoaPods/CocoaPods#10883]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
  
Ran `pod install`

## What did you expect to happen?

Install all pod dependencies correctly defined in pod file with this content:

target 'MyApp' do
  use_frameworks!

  project 'MyApp.xcodeproj'
  platform :ios, '9.0'

  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal'

  target 'MyAppTests' do
    inherit! :search_paths
  end

  target 'MyAppUITests' do
    inherit! :search_paths
  end
end

## What happened instead?

Got this error:

Analyzing dependencies
Pre-downloading: `Moscapsule` from `https://github.com/flightonary/Moscapsule.git`
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275: [BUG] Bus Error at 0x00000001050c0000
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]

### Stack

```
   CocoaPods : 1.10.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.5.2 (20G95)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0

## Project that demonstrates the issue

Standard iOS MyApp with no modified code yet, only modified pod file and run pod install. 
[ruby_crash.zip](https://github.com/CocoaPods/CocoaPods/files/7022649/ruby_crash.zip)

**Comment by dnkoutso** [comment]
Hi there, thanks for filing the issue. We have seen quite a few reports related to `ffi` gem installation which seem to be more related to the environment of gems rather than with cocoapods specifically.

Please ask in StackOverflow for assistance or search for similar closed issues in this repo.

If you have an M1 please see https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1

**Comment by larsbentz** [comment]
Hi - thanks for quick response and sorry for not having found this on StackOverflow. I searched the net but maybe my search criteria wasn't good enough.

Thanks.
