### ISSUE TITLE
README content not updating after push

### ISSUE THREAD

**Issue by bradhowes** [CocoaPods/CocoaPods#10896]
* [ X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod trunk push BRHJoyStickView.podspec` with new version (3.2.0).
Everything was OK (no warnings or errors).

## What did you expect to happen?

Entry for BRHJoyStickView on https://cocoapods.org/pods/BRHJoyStickView shows updated README content.
Also see https://github.com/CocoaPods/cocoapods-metadata-service/issues/22

## What happened instead?

Old content is still visible. However, version is correctly reported as 3.2.0

### Stack

```
   CocoaPods : 1.10.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.5.2 (20G95)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

Not applicable

**Comment by dnkoutso** [comment]
Hey @bradhowes , thanks for reporting this issue. It seems you already indicated the duplicate issue https://github.com/CocoaPods/cocoapods-metadata-service/issues/22 so its good to bump again the urgency to fix this.

However, given this is already filed I am going to close this one to keep things organized as we get quite a few issues filed daily.

Happy to re-open if you feel strongly this is different than https://github.com/CocoaPods/cocoapods-metadata-service/issues/22
