### ISSUE TITLE
M1 error running pod install

### ISSUE THREAD

**Issue by Shamnawagamuwa** [CocoaPods/CocoaPods#10907]
Report

What did you do?
Installing react-native (not via expo) but got an error in installing CocoaPods dependencies and tells to manually run pod install

What did you expect to happen?
Successfull react native project template

What happened instead?
Got an error

Pod File
<img width="676" alt="Screenshot 2564-08-30 at 7 24 07 PM" src="https://user-images.githubusercontent.com/65786304/131350567-e32d4956-05ac-4286-871b-1667e14860e5.png">

Error
<img width="896" alt="Screenshot 2564-08-30 at 7 22 51 PM" src="https://user-images.githubusercontent.com/65786304/131350431-81ca2f2e-d3c9-4ae5-8104-e50a6e46bd81.png">
<img width="1124" alt="Screenshot 2564-08-30 at 7 23 17 PM" src="https://user-images.githubusercontent.com/65786304/131350450-ed46a791-0f23-4fb6-a2ce-448ad348385a.png">
<img width="1440" alt="Screenshot 2564-08-30 at 7 23 44 PM" src="https://user-images.githubusercontent.com/65786304/131350463-7d9faf7b-86fe-4d91-92be-89e996095ffc.png">

**Comment by dnkoutso** [comment]
Please see https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1 and search here for other closed issues for potential solutions.
