### ISSUE TITLE
Can substitute repo imported by dependency in pod file?

### ISSUE THREAD

**Issue by xiedeacc** [CocoaPods/CocoaPods#10905]
I import project a(https://github.com/ex/a) in podfile, a import b(https://xxx.com/ex/b),  can I substitute b's repo to another url in Podfile?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
