### ISSUE TITLE
pod install does nothing

### ISSUE THREAD

**Issue by GrueseGehenRaus** [CocoaPods/CocoaPods#10910]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I've installed cocoa pods via my terminal and as I ran 'pod install' in my Xcode projects directory.
## What did you expect to happen?

Frameworks to be installed
e.g. Install all pod dependencies correctly.

## What happened instead?

Well It didn't really do anything I think
## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.10.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.5.2 (20G95)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'i67 Messenger' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
 
end
```

**Comment by GrueseGehenRaus** [comment]
I've run pod install --verbose" and after around 5 minutes  "-> Pod installation complete! There are 3 dependencies from the Podfile and 18 total pods installed." was printed. Did it fix the problem?

**Comment by dnkoutso** [comment]
this looks correct. Open the workspace to start developing.

For now I am going to close as I see no bug or enhancement here.
