### ISSUE TITLE
pod install Searching for inspections failed: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by X-Morris** [CocoaPods/CocoaPods#10926]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
This is not a complete issue report.

**Comment by X-Morris** [comment]
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2Fopt%2Fhomebrew%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Fffi-1.15.4.pre1%2Flib%2Fffi_c.bundle%2C+9%29%3A+no+suitable+image+found.++Did+find%3A%0A%09%2Fopt%2Fhomebrew%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Fffi-1.15.4.pre1%2Flib%2Fffi_c.bundle%3A+mach-o%2C+but+wrong+architecture%0A%09%2Fopt%2Fhomebrew%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Fffi-1.15.4.pre1%2Flib%2Fffi_c.bundle%3A+mach-o%2C+but+wrong+architecture+-+%2Fopt%2Fhomebrew%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Fffi-1.15.4.pre1%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by furkannkilicc** [comment]
Hi did you solve that ı got same error ?
