### ISSUE TITLE
Pod install fails after updating to 1.11.0

### ISSUE THREAD

**Issue by umang-simform** [CocoaPods/CocoaPods#10922]
* [*] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
`pod install`  was working fine till yesterday and then I updated cocoapods version and now I am not able to install pods successfully. I tried downgrading the version and it worked fine.
## What did you do?
Run `pod install --repo-update`

## What did you expect to happen?
 Install all pod dependencies correctly.

## What happened instead?

> 
> [!] The following Swift pods cannot yet be integrated as static libraries:
> 
> The Swift pod `Giphy` depends upon `libwebp`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

> pod env
> 
> ### Stack
> 
> ```
>    CocoaPods : 1.11.0
>         Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
>     RubyGems : 3.0.3
>         Host : macOS 11.5.2 (20G95)
>        Xcode : 12.5.1 (12E507)
>          Git : git version 2.33.0
> Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
> Repositories : trunk - CDN - https://cdn.cocoapods.org/
> ```
> 
> ### Installation Source
> 
> ```
> Executable Path: /usr/local/bin/pod
> ```
> 
> ### Plugins
> 
> ```
> cocoapods-deintegrate : 1.0.4
> cocoapods-plugins     : 1.0.0
> cocoapods-search      : 1.0.0
> cocoapods-trunk       : 1.5.0
> cocoapods-try         : 1.2.0
> ```
>

**Comment by dnkoutso** [comment]
This is fixed by https://github.com/CocoaPods/CocoaPods/pull/10914 and will be released in 1.11.1 next week.

**Comment by dnkoutso** [comment]
For now keep using 1.10.2 or add the dependency to your podfile and specify `:modular_headers => true`.

**Comment by dnkoutso** [comment]
If you are using Bundler you may also point it to the latest `1-11-stable` branch to get the fix from "today"

**Comment by umang-simform** [comment]
Also, I can not put `use_modular_headers!` globally in your Podfile as it breaks build process as it is react native project.

**Comment by dnkoutso** [comment]
@umang-simform you can do it on a per pod basis.

```ruby
pod 'MyPod', :modular_headers => true
```

**Comment by dnkoutso** [comment]
> [!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod Giphy depends upon libwebp, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set use_modular_headers! globally in your Podfile, *or specify :modular_headers => true for particular dependencies.*

**Comment by umang-simform** [comment]
Yup, Trying the same, Not sure why I missed your previous comments but I am now trying this : 
`pod 'MyPod', :modular_headers => true
`

**Comment by dnkoutso** [comment]
OK, let me know. Although this is a workaround for now. Sorry for closing issue too quickly but it has already been fixed.

**Comment by umang-simform** [comment]
@dnkoutso  It is totally fine , Thank you so much for your amazingly fast response
