### ISSUE TITLE
Pods are not installed when adding a podspec from a private GitHub repo

### ISSUE THREAD

**Issue by javierdemartin** [CocoaPods/CocoaPods#10921]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I am in the process of setting up a CI/CD pipeline and one of our dependencies is behind a private GitHub repo. That podspec is being added outside of `Podfile` via the `pod repo add XXX` command, which correctly adds data to `~/.cocoapods./repos/` but when running the `pod install` command in my project directory nothing is installed even though the install command outputs no error and the installation has completed.

* Am I missing something that might install these private pods in another directory that is not the project's?
* Is this the correct approach to install pod dependency that is on a private repo?

## What did you do?

The purpose of this setup is to be run on a CI/CD machine on GitHub Actions with no previous Git configuration. Repository cloning is done via OAuth tokens (GitHub's Personal Access Tokens). For simplicity I am replicating these commands local on my laptop instead of the CI/CD machine as I get the same results. I have two dependencies `PrivateRepoSpec` & `PrivateRepoSpecDev`.

1. Current `Podfile` contents

```
platform :ios, '14.0'

target 'MyApp' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    pod 'PrivateRepoSpec', :path => '~/.cocoapods/repos/PrivateRepoSpec/'
    pod 'DatadogSDK'
end

target 'MyApp Dev' do
    use_frameworks!

    pod 'PrivateRepoSpec Dev', :path => '~/.cocoapods/repos/PrivateRepoSpecDev/'
    pod 'DatadogSDK'
end
```

2. Add private podspec repo as a dependency

```
pod repo add PrivateRepoSpec https://${CICD_GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/ORG/privaterepo-specs.git
          
pod repo add  PrivateRepoSpecDev https://${CICD_GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/ORG/privaterepo-specs.git
```

After this `ls ~/.cocoapods/repos/` shows that both dependencies have correctly been added to `~/.cocoapods/repos/`

```
PrivateRepoSpec    PrivateRepoSpecDev cocoapods trunk
```

3. Install Pods

```
> pod install --verbose

Analyzing dependencies
Downloading dependencies
Installing DatadogSDK (1.6.0)
Installing PrivateRepoSpec (4.0.0)
Installing PrivateRepoSpecDev (4.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 5 dependencies from the Podfile and 6 total pods installed.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
```

## What did you expect to happen?

Private pod dependencies to be installed on the Xcode's `Pods/` directory and project to compile.

## What happened instead?

Missing pods in `Pods/` folder after `pod install` even though `pod install` command's output says otherwise. I would expect here two folders with my private dependencies: `PrivateRepoSpec`& `PrivateRepoSpecDev`.

```
> ls Pods/

Headers              Local Podspecs       Pods.xcodeproj      
DatadogSDK      Manifest.lock        Target Support Files
```

This causes Xcode's project to not compile as these dependencies are missing.

## CocoaPods Environment

<details>
 <summary>pod install</summary>

### Stack

```
   CocoaPods : 1.11.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.5.2 (20G95)
       Xcode : 13.0 (13A5212g)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 707e98d43b58aa970f6da6a5b71990a8993ddcb4

               PrivateRepoSpec - git - https://${CICD_GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/ORG/privaterepo-specs.git @ 84215569d4008f7dd38a386cf409db833d7483a8

               PrivateRepoSpecDev - git - https://${CICD_GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/ORG/privaterepo-specs.git @ 84215569d4008f7dd38a386cf409db833d7483a8

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '14.0'

target 'MyApp' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!

    # Remove this comment on PR!
    pod 'PrivateRepoSpec', :path => '~/.cocoapods/repos/PrivateRepoSpec/'
    pod 'DatadogSDK'
end

target 'MyApp Dev' do
    use_frameworks!

    pod 'PrivateRepoSpec Dev', :path => '~/.cocoapods/repos/PrivateRepoSpecDev/'
    pod 'iCarousel'
    pod 'Charts'
    pod 'DatadogSDK'
end
```

</details>

**Comment by dnkoutso** [comment]
hmmm not sure whats going on there but this is a second report.

Can you try `pod cache clean --all` and then `rm -rf Pods/` in your project and then `pod install`?

**Comment by javierdemartin** [comment]
Unfortunately the result is the same, `ls Pods/` still doesn't have the pods as it would with any other public Pod given an url.

Is specifying the `.podspec` file on the `Podfile` as done above a correct approach like so?

```
...
pod 'PrivateRepoSpec', :path => '~/.cocoapods/repos/PrivateRepoSpec/'
```

Other than that I am at a loss on what could be wrong here?

Thanks!

**Comment by dnkoutso** [comment]
should be good, I think cocoapods scans the folder and uses the first result.

**Comment by javierdemartin** [comment]
I'm going to close this as I can't reproduce the exact issue with another sample sample project but I've found an alternative to this issue that fixed our own case. **We were using HTTPS & Personal Access Tokens to clone all private repos using a dummy account with only read permissions, we've now changed to use SSH with a private/public key pair.**.

In case someone is facing this same issue this is an alternative fix they can try when using this from GitHub Actions. Add a private key to your project secrets and also add associate the public key to the dummy account with only read permissions.

```
# Skip input checking on remote host's SSH fingerprint
echo "StrictHostKeyChecking no" >> ~/.ssh/config
# Use SSH instead of HTTPS for cloning
git config --global url."git@github.com:".insteadOf "https://github.com/"
ssh-agent -a /tmp/ssh_agent.sock > /dev/null
echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/cicd_key_temp
chmod 400 ~/.ssh/cicd_key_temp
ssh-add ~/.ssh/cicd_key_temp
pod cache clean --all
pod repo add-cdn trunk 'https://cdn.cocoapods.org'
pod install
git config --global --unset url."git@github.com:".insteadOf "https://github.com/"
# From now on your Pods/ folder should have your private pods installed inside
```
