### ISSUE TITLE
when I update to 1.11.0 , I get an error.....

### ISSUE THREAD

**Issue by scotale** [CocoaPods/CocoaPods#10943]
xcode : 12.4  cocoapods:1.11.0   FacebookCoreKit:11.2.0  
What  can I do to solve this error?
Error:  Lexical or Preprocessor Issue Group,  'FBSDKCoreKitImport.h' file not found
![Uploading Screenshot 2021-09-12 at 1.56.05 PM.png…]()

**Comment by dnkoutso** [comment]
Sorry this is not a valid issue report. Please ask in StackOverflow.
