### ISSUE TITLE
Multi-project workspace does not seem to link dependencies correctly

### ISSUE THREAD

**Issue by jbehrens94** [CocoaPods/CocoaPods#10959]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I have a workspace that contains two xcodeproj's, one that's got some iOS targets and a Modules.xcodeproj that contains frameworks. I defined `workspace` correctly and used `project` declarations in the right places. I ran `pod install`, which succeeded without errors or warnings.

## What did you expect to happen?
I expect a target within Modules.xcodeproj to be linked correctly with the dependencies. 

## What happened instead?
I'm seeing crashes that a dependency of my dependency is not linked correctly. E.g. `dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire Referenced from: {project_dir}/Build/Products/Debug-iphonesimulator/{name}.framework/{name}
  Reason: image not found`

### {Project name}

```
   CocoaPods : 1.10.2
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]
    RubyGems : 3.1.2
        Host : macOS 11.5.2 (20G95)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.33.0
Ruby lib dir : /Users/johannbehrens/.rbenv/versions/2.7.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/johannbehrens/.rbenv/versions/2.7.1/bin/pod
```

### Plugins

```
cocoapods-acknowledgements : 1.3.0
cocoapods-deintegrate      : 1.0.4
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.1.0
cocoapods-trunk            : 1.5.0
cocoapods-try              : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

# Define the workspace
workspace '{project}.xcworkspace'

def firebase
  pod 'Firebase/Analytics', '7.11.0'
  pod 'Firebase/Crashlytics', '7.11.0'
  pod 'Firebase/RemoteConfig', '7.11.0'
end

def keychain
  pod 'KeychainSwift', '19.0.0' # This is the latest version, has iOS 8 in Podspec. Warning can't be solved yet.
end

def reachability
  pod 'AppleReachability', '5.0.0' # This is the latest version, has iOS 8 in Podspec. Warning can't be solved yet.
end

target '{project}' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Set correct project
  project '{project}.xcodeproj'

  # Pods for {project}
  firebase
  keychain
  reachability

  pod 'LTHPasscodeViewController', '3.9.4' # This is the latest version, has iOS 8 in Podspec. Warning can't be solved yet.
  pod 'KRLCollectionViewGridLayout', '1.0.0' # This is the latest version, has iOS 8 in Podspec. Warning can't be solved yet.

  target '{project}Tests' do
    inherit! :search_paths
    
    pod "Sourcery", "1.5.0"
  end

end

target '{project}ShareExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Set correct project
  project '{project}.xcodeproj'

  # Pods for {project}ShareExtension
  firebase
  keychain
  reachability
end

target '{project}WidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Set correct project
  project '{project}.xcodeproj'

  # Pods for {project}WidgetExtension
  firebase
  keychain
  reachability
end

target '{project}FilesExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Set correct project
  project '{project}.xcodeproj'

  # Pods for {project}WidgetExtension
  keychain
end

target '{project}FilesUIExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Set correct project
  project '{project}.xcodeproj'

  # Pods for {project}WidgetExtension
  keychain
end

target '{framework1}' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Set correct project
  project 'Modules/Modules.xcodeproj'

  pod 'Moya/RxSwift', '15.0.0'
  pod 'Sourcery', '1.5.0'
end

target '{framework1}Tests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Set correct project
  project 'Modules/Modules.xcodeproj'

  pod 'Quick', '4.0.0'
  pod 'Nimble', '9.2.1'
  pod 'RxBlocking', '6.2.0'
  pod 'RxTest', '6.2.0'
end
```

## Project that demonstrates the issue
I have found that adding the framework its dependencies to the app target fixes the dyld runtime errors, I'm not sure if this is something that is due to Cocoapods overriding some Xcode settings, or that Xcode is just configured incorrectly.

**Comment by dnkoutso** [comment]
We will need a sample app here to fully be able to diagnose, can you upload one demonstrating the issue?

**Comment by darekxan** [comment]
I'm not entirely sure that my issue is exactly the same, but looks quite similar. 
Workspace consists of `App` and `Library`.

Here's the dependency tree:
```
App
|-- Library
      |-- RxSwift
```

Running on simulator produces the same output:
```
dyld: Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: /Users/dariusz/Library/Developer/Xcode/DerivedData/ModuleTest-eolqznwgrvezilcmmugweipucuyq/Build/Products/Debug-iphonesimulator/Library.framework/Library
  Reason: image not found
```

Contents of `@rpath` fragment:
```
➜  / ls /Users/dariusz/Library/Developer/Xcode/DerivedData/ModuleTest-eolqznwgrvezilcmmugweipucuyq/Build/Products/Debug-iphonesimulator

App.app                    App.swiftmodule            Library.framework          Pods_App.framework         Pods_Lib_Library.framework RxSwift
```

As you can see there is an `RxSwift` directory. It containts `RxSwift.framework` folder. If I move it up a step (so it's where the other frameworks) - the sample app launches properly.


## Cocoapods Environment
### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [arm64-darwin20]
    RubyGems : 3.2.15
        Host : macOS 11.6 (20G165)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.23.0
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.0.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 66879d80e47883f85f27dd089fb16e82774ef080

               netlify- - CDN - https://cocoapods-cdn.netlify.app/
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '13.0'
use_frameworks!
workspace 'ModuleTest'

target 'App' do
  project 'App/App.xcodeproj'
end
target 'AppTests' do
  project 'App/App.xcodeproj'
  inherit! :search_paths
end
abstract_target 'Lib' do
  project 'Library/Library.xcodeproj'
  pod 'RxSwift'
  
  target 'Library' do
  end
    
  target 'LibraryTests' do
    inherit! :search_paths
  end
end
```

## Sample project
https://github.com/darekxan/cocoapods_10959/

**Comment by dnkoutso** [comment]
Awesome thanks for sample app!

**Comment by dnkoutso** [comment]
@darekxan in order for cocoapods to embed the RxSwift framework into your app you need to add an App->Library dependency in your Xcode project.

I did this and your app ran successfully. CocoaPods cannot embed frameworks into another framework (Library in this case), they all get embedded in the app. CocoaPods wont do this unless it can derive that Library is actually _used_ by the App.

So drag Library.xcodeproj into App.xcodeproj and go to Build Settings and add a dependency from the App to the Library.

I also believe this is the same fix for the original authors fix.

**Comment by darekxan** [comment]
Thank You for the insight. Can you zip/push your working project please? I dragged Library.xcodeproj, added a dependency in Build Phase -> Dependencies, but still cannot manage it to work.

**Comment by darekxan** [comment]
ok now I got it -> `pod install` was needed! Thank You :)

**Comment by dnkoutso** [comment]
yeap, re integration!

**Comment by Jon889** [comment]
> [@darekxan](https://github.com/darekxan) in order for cocoapods to embed the RxSwift framework into your app you need to add an App->Library dependency in your Xcode project.
> 
> I did this and your app ran successfully. CocoaPods cannot embed frameworks into another framework (Library in this case), they all get embedded in the app. CocoaPods wont do this unless it can derive that Library is actually _used_ by the App.
> 
> So drag Library.xcodeproj into App.xcodeproj and go to Build Settings and add a dependency from the App to the Library.
> 
> I also believe this is the same fix for the original authors fix.

Isn't the whole point of workspaces that Xcode projects don't need to be nested? I think the better solution is for CocoaPods to look at `Link Binary with Libraries`/`Frameworks, Libraries and Embedded Content` instead of `Target Dependencies` which can't have cross project dependencies.

It feels like quite a common setup to have a workspace with two non nested projects and dependencies between them, yet it seems this isn't supported by CocoaPods?

**Comment by Jon889** [comment]
> [@darekxan](https://github.com/darekxan) in order for cocoapods to embed the RxSwift framework into your app you need to add an App->Library dependency in your Xcode project.
> 
> I did this and your app ran successfully. CocoaPods cannot embed frameworks into another framework (Library in this case), they all get embedded in the app. CocoaPods wont do this unless it can derive that Library is actually _used_ by the App.
> 
> So drag Library.xcodeproj into App.xcodeproj and go to Build Settings and add a dependency from the App to the Library.
> 
> I also believe this is the same fix for the original authors fix.

@dnkoutso 
Isn't the whole point of workspaces that Xcode projects don't need to be nested? I think the better solution is for CocoaPods to look at `Link Binary with Libraries`/`Frameworks, Libraries and Embedded Content` instead of `Target Dependencies` which can't have cross project dependencies.

It feels like quite a common setup to have a workspace with two non nested projects and dependencies between them, yet it seems this isn't supported by CocoaPods?

**Comment by Jon889** [comment]
> [@darekxan](https://github.com/darekxan) in order for cocoapods to embed the RxSwift framework into your app you need to add an App->Library dependency in your Xcode project.
> 
> I did this and your app ran successfully. CocoaPods cannot embed frameworks into another framework (Library in this case), they all get embedded in the app. CocoaPods wont do this unless it can derive that Library is actually _used_ by the App.
> 
> So drag Library.xcodeproj into App.xcodeproj and go to Build Settings and add a dependency from the App to the Library.
> 
> I also believe this is the same fix for the original authors fix.

Also this solution means RxSwift is accessible in the app target, ie you can `import RxSwift` in the app. Really it should only copy RxSwift into the app bundle, not link to it, unless the Podfile specifies RxSwift is a dependency of the app too.
