### ISSUE TITLE
'GCDWebServerPrivate.h' file not found

### ISSUE THREAD

**Issue by tienit150198** [CocoaPods/CocoaPods#10958]
I'm using a couple of libs and everything works fine.
Then I want to use this lib and add it to cocoapods, I use pod install successfully.
But when I go to the project to build, an error occurs

Error image:
<img width="1105" alt="Screenshot 2021-09-20 at 18 33 13" src="https://user-images.githubusercontent.com/52131412/133995776-35636820-1d41-456e-a27c-f424f086d8e0.png">

**And here is my pod file**
<img width="686" alt="Screenshot 2021-09-20 at 18 36 03" src="https://user-images.githubusercontent.com/52131412/133995927-327a78e3-64e2-4248-88bd-d3226913cab8.png">

Has anyone had this problem, and is there a way to fix it.
**I use xcode 12.4, swift 5.3**

**Comment by dnkoutso** [comment]
Hey there, thanks for the issue report. Unfortunately this is not a full issue report and seems like a better fit to ask in StackOverflow.

If you believe its a cocoapods gem issue please file a new issue filling in our issue template and provide a sample app and steps to reproduce.
