### ISSUE TITLE
payload bind method not working  . please help me

### ISSUE THREAD

**Issue by ramojiroy** [CocoaPods/CocoaPods#10957]
Error: Malformed version number string 2.6.0
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Using Xcode 10.1: Requires CocoaPods 1.6.0 or above.

Issue with Nanaimo not loading:
Please run `[sudo] gem uninstall nanaimo` and remove all but the latest version.

Issues with `pod search`? Try deleting your cache `rm -rf ~/Library/Caches/CocoaPods`first.
-->

* [ ] I've read and understood the [*CONTRIBUTING* g

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by ramojiroy** [comment]
Error: Malformed version number string 2.6.0
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
 please help me

**Comment by dnkoutso** [comment]
sorry this is not a valid issue report. Please ask in StackOverflow for assistance.
