### ISSUE TITLE
sudo gem install cocoapods Erro cannot load such file -- socket

### ISSUE THREAD

**Issue by williamkung** [CocoaPods/CocoaPods#10966]
sudo gem install cocoapods Erro

ERROR:  Loading command: install (LoadError)
	cannot load such file -- socket
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

system macos  11.6（20G165)
xcode 13.0 (13A223)

**Comment by dnkoutso** [comment]
This is not a valid issue report.
