### ISSUE TITLE
It doesn't work :(

### ISSUE THREAD

**Issue by JakeLEESEUNGJU** [CocoaPods/CocoaPods#10964]
It doesn't work :(

jake@SEUNGJUui-MacBookPro ios % arch -x86_64 pod install --repo-update

Updating local specs repositories
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '8.5.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '8.5.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '8.5.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "Firebase/Firestore":
  In snapshot (Podfile.lock):
    Firebase/Firestore (= 8.3.0)

  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 1.0.7, which depends on
      Firebase/Firestore (= 8.5.0)

You have either:
 * changed the constraints of dependency `Firebase/Firestore` inside your development pod `cloud_firestore`.
   You should run `pod update Firebase/Firestore` to apply changes you've made.

then, i  run 'pod update Firebase/Firestore' then same error occurred again .

_Originally posted by @JakeLEESEUNGJU in https://github.com/CocoaPods/CocoaPods/issues/10923#issuecomment-921576954_

**Comment by dnkoutso** [comment]
I am sorry this is not a valid issue report. Please fill in the issue template and provide a sample app or ask in StackOverflow.
