### ISSUE TITLE
[!] Couldn't determine repo type for URL

### ISSUE THREAD

**Issue by skyming** [CocoaPods/CocoaPods#10971]
➜  WNNDemo git:(dev1.0.0) pod install
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
[!] Couldn't determine repo type for URL: `http://igit.yycorp.com/specs.git`: (<unknown>): mapping values are not allowed in this context at line 13 column 19
➜  WNNDemo git:(dev1.0.0) pod install
Analyzing dependencies
[!] Couldn't determine repo type for URL: `http://igit.yycorp.com/specs.git`: (<unknown>): mapping values are not allowed in this context at line 13 column 19

**Comment by skyming** [comment]
pod repo add  specs  http://igit.yycorp.com/specs.git

**Comment by wnstkdyu** [comment]
@skyming 
Can you explain how you solve this issue? 🙏
