### ISSUE TITLE
Unknown object version

### ISSUE THREAD

**Issue by yasminOliver** [CocoaPods/CocoaPods#10973]
My pod version = pod --version 1.5.2 and my cocopods version is gem list cocoapods  
*** LOCAL GEMS ***
cocoapods (1.11.2)
cocoapods-core (1.11.2)
cocoapods-deintegrate (1.0.5)
cocoapods-downloader (1.5.1)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.1)
cocoapods-trunk (1.6.0)
cocoapods-try (1.2.0)

I did the cocoapods update but it doesn't show up on the system and it doesn't allow pod install either. I already installed it with the gem and homebrew but it didn't solve

**Comment by dnkoutso** [comment]
`gem update xcodeproj`

This is a very old version of cocoapods you are using and xcodeproj gem.

**Comment by dnkoutso** [comment]
Also `gem update cocoapods` generally.

**Comment by yasminOliver** [comment]
I've already done the update but the system doesn't recognize it.

**Comment by dnkoutso** [comment]
Can you run `gem which xcodeproj` and paste the output here?

**Comment by yasminOliver** [comment]
I did the update and this message appeared: 

Updating installed gems
Nothing to update

**Comment by dnkoutso** [comment]
My other comment was to run `gem which` not `gem update` does that output anything?

**Comment by yasminOliver** [comment]
gem which xcodeproj:
 /usr/local/lib/ruby/gems/3.0.0/gems/xcodeproj-1.21.0/lib/xcodeproj.rb

gem which cocoapods:
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods.rb

**Comment by dnkoutso** [comment]
hmm thats weird.

it seems you said in original report `pod --version 1.5.2` how come this is such an old version and not printing 1.11.2?

**Comment by yasminOliver** [comment]
That's exactly the problem, I can't use cocoapods and also I can't use the latest version instead of this 1.5

**Comment by dnkoutso** [comment]
that seems like an environment issue. Try using https://bundler.io/ with a `Gemfile` to create a gem sandbox to run things with.
