### ISSUE TITLE
A about making static framework

### ISSUE THREAD

**Issue by a51095** [CocoaPods/CocoaPods#10992]
### !!! help !!!
- After verification, it is successfully pushed to `cocoapods.org`；
- Use `pod install` to download to the project；
- But I can't find the module of this static library；
- I must manually `add` this static library in the `link binary with libraries` tab to find the corresponding module;
- The following screenshot is the relevant content in my `xxsdk.podspec` file；
- There are only`. Framework` files and no`. Swift` files in the `lib` folder;
- What configuration items do I lack? How can I solve this problem？

```
  ...
  spec.static_framework = true
  spec.ios.vendored_frameworks  = 'lib/HandyScannerSDK.framework'
  spec.source_files  = "lib/HandyScannerSDK.framework/**/*"
  spec.public_header_files = 'lib/HandyScannerSDK.framework/Headers/HandyScannerSDK-Swift.h'
  ...
```

**Comment by dnkoutso** [comment]
Hey there, thanks for the report. Unfortunately this is not sufficient for us to diagnose a bug. Please ask in StackOverflow under cocoapods tag to receive assistance.
