### ISSUE TITLE
Intermittent build error: rm: <root>/Pods/resources-to-copy.txt: No such file or directory

### ISSUE THREAD

**Issue by mjbeauregard** [CocoaPods/CocoaPods#1099]
This problem started when I added a second test target to my project. The first one was for unit tests that should run quickly and is defined like this in my Podfile:

```
target :UnitTests do
    pod 'Kiwi'
end
```

This has been working for weeks. I can run tests in Xcode using cmd-U which correctly builds the UnitTests target and runs them.

Then I decided to add another test target for functional/acceptance tests that drive the application. Since these are going to be slower tests, I want to keep them separate from the lower level, faster specs. So I added the following target in the Podfile:

```
target :FunctionalTests, :exclusive => true do
    pod 'Kiwi'
    pod 'Shelley'
    pod 'PublicAutomation'
end
```

Now when I hit cmd-U to run the tests, more than half of the time I get the following error:

```
rm: <root>/Pods/resources-to-copy.txt: No such file or directory
```

Through experimentation I believe I have isolated the problem down to the Pods/Pods-<target>-resources.sh scripts. My project now has three such files:

```
Pods/Pods-resources.sh
Pods/Pods-FunctionalTests-resources.sh
Pods/Pods-UnitTests-resources.sh
```

All three of these scripts are identical and are manipulating the same file named in this variable:

```
RESOURCES_TO_COPY=${PODS_ROOT}/resources-to-copy.txt
```

It occurred to me that maybe Xcode is running the test builds in parallel causing these scripts to fight over that single file which would explain the intermittent failures. I say intermittent, but it basically fails about 80% of the time for me.

A simple solution to the problem was to edit each of the scripts giving the RESOURCES_TO_COPY variable a unique filename for each script. Obviously this is local hack, but does indicate the nature of the problem and a potential fix.

I'd be happy to send a pull request with the fix, but to be honest after a quick look I don't know how I might determine the target name within the script generator. Thoughts?

**Comment by alexszilagyi** [comment]
I'm not sure if anyone else is facing this issue but I'm getting this error with: `1.2.1` version. Any1?
