### ISSUE TITLE
Windows Ruby: "Response: SSL peer certificate or SSH remote key was not OK"

### ISSUE THREAD

**Issue by edsumpena** [CocoaPods/CocoaPods#11012]
I'm pretty new to CocoaPods and am trying to get it to work on a Windows 10 PC. 

## What did you do?

pod install --verbose

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Resolving dependencies of `Podfile`
  CDN: cocoapods-cdn URL couldn't be downloaded: https://cocoapods-cdn.netlify.app/CocoaPods-version.yml Response: SSL
  peer certificate or SSH remote key was not OK, retries: 4
  CDN: cocoapods-cdn URL couldn't be downloaded: https://cocoapods-cdn.netlify.app/CocoaPods-version.yml Response: SSL
  peer certificate or SSH remote key was not OK, retries: 3
  CDN: cocoapods-cdn URL couldn't be downloaded: https://cocoapods-cdn.netlify.app/CocoaPods-version.yml Response:
  Timeout was reached, retries: 2
  CDN: cocoapods-cdn URL couldn't be downloaded: https://cocoapods-cdn.netlify.app/CocoaPods-version.yml Response: SSL
  peer certificate or SSH remote key was not OK, retries: 1
[!] CDN: cocoapods-cdn URL couldn't be downloaded: https://cocoapods-cdn.netlify.app/CocoaPods-version.yml Response: SSL peer certificate or SSH remote key was not OK

## CocoaPods Environment

I can't even run pod env. I keep getting:
CDN: cocoapods-cdn URL couldn't be downloaded: https://cocoapods-cdn.netlify.app/CocoaPods-version.yml Response: SSL
  peer certificate or SSH remote key was not OK, retries: 4
  CDN: cocoapods-cdn URL couldn't be downloaded: https://cocoapods-cdn.netlify.app/CocoaPods-version.yml Response: SSL
  peer certificate or SSH remote key was not OK, retries: 3
  CDN: cocoapods-cdn URL couldn't be downloaded: https://cocoapods-cdn.netlify.app/CocoaPods-version.yml Response: SSL
  peer certificate or SSH remote key was not OK, retries: 2

## Project that demonstrates the issue

https://github.com/edsumpena/cocopods_windows_test/tree/master/ios

**Comment by dnkoutso** [comment]
This seems like a network issue trying to reach CDN? Can you use the git based master specs repo?

**Comment by edsumpena** [comment]
@dnkoutso Sorry, I'm am pretty new to Podfile. Do I do this by adding `source 'https://github.com/CocoaPods/Specs' ` at the top of my Podfile?

**Comment by edsumpena** [comment]
I have tried on different networks and VPNs and they all show the same message. Do you have any suggestions on how I can resolve this on my end?

**Comment by leni8ec** [comment]
I have the same issue, And I can't find a solution.

https://github.com/CocoaPods/CocoaPods/issues/9955#issuecomment-1363570667

**Comment by rolfen** [comment]
How was issue closed as "completed"?

Most likely this is related to downloading the fix for https://github.com/CocoaPods/CocoaPods/issues/9955 which was also closed as "completed" without any comment. 

My conclusion that cocoapods are not supported under Windows. This should have been declared in the documentation.

**Comment by zararashigal** [comment]
Same issue, developer is lazy.
