### ISSUE TITLE
source ssh path is ok, https error

### ISSUE THREAD

**Issue by hapiii** [CocoaPods/CocoaPods#11035]
# Report
CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
  because checking is only performed in repo update
[!] Couldn't determine repo type for URL: 
 (<unknown>): mapping values are not allowed in this context at line

## What did you do?

when source with ssh ,and then pod install  it is ok
source  'git@git.xxxx.spec-repo.git' 

but when i used https
source 'http://xxx.spec-repo.git',

 pod install

error with 

CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
  because checking is only performed in repo update
[!] Couldn't determine repo type for URL: 
 (<unknown>): mapping values are not allowed in this context at line

## What did you expect to happen?
I want used https, and pod install isOK

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
    RubyGems : 3.2.30
        Host : macOS 11.5.2 (20G95)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /Users/admin/.rvm/rubies/ruby-3.0.0/lib
Repositories : aliyun-aliyun-specs - git - https://github.com/aliyun/aliyun-specs.git @ cb258199ea1327f6799cd667958cffda5cf3c00a
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

**Comment by chickdan** [comment]
I'm running into this issue as well. I believe #10985 is the fix but it's been sitting in PR for >30 days.

**Comment by jarbogast-salesforce** [comment]
Just here to say that this issue is also affecting me as well.

**Comment by jarbogast-salesforce** [comment]
I have a feeling the issue is due to the changes made here, but haven't had time to debug further.

https://github.com/CocoaPods/CocoaPods/compare/1.10.2...1.11.2#diff-24c199b6be42ab53d15822d302797ddd75232a0d731e2e21ebea5e249c60426d

**Comment by jarbogast-salesforce** [comment]
My workaround for now is to 

`bundle exec pod repo add repoName https://blah.host.com/Cocoapod-Specs.git`

and then

`bundle exec pod install`

works like a charm

**Comment by hapiii** [comment]
I solved the problem by



pod repo remove trunk
pod repo add repoName 'http://xxx.mySpec-repo.git'


I hope it helps you～

**Comment by dhrushit-RIT** [comment]
Is having to add a repo separately a normal behavior? should it not work out of the box like it did for ssh, just by using source command?

By running repo add command, I noticed that the complete repository is cloned at the `/User/<username>/.cocoapods/repos/` folder.
