### ISSUE TITLE
how to push a xcframework include modulemap to trunk

### ISSUE THREAD

**Issue by Blackvsion** [CocoaPods/CocoaPods#11049]
# Report

## What did you do?

I am developing a swift framework include C file, so, I create a `module.modulemap` and add path to `Module Map File` and `Import Paths`,  it works well when coding. Then I build it to `xcframework` by command `carthage build --no-skip-current --platform all --configuration Release --use-xcframeworks` and try to push it to trunk by `pod trunk push --allow-warnings --use-libraries`.

## What did you expect to happen?

push success

## What happened instead?
```
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
```

### Stack
```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.5.2 (20G95)
       Xcode : 13.0 (13A233)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```
### Installation Source
```
Executable Path: /usr/local/bin/pod
```
### Plugins
```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

You can download my xcframework.zip by [My xcframework](https://app.heimouyun.com/sdk/ios/BVCommon-0.1.1.zip)

some things in my project
```
└── BVCommon
    ├── BVCommon.h
    └── C
        ├── Wifi
        │   ├── getgateway.c
        │   ├── getgateway.h
        │   └── route.h
        └── module.modulemap
```
module.modulemap:
```
module BVCommon {
    header "Wifi/getgateway.h"
    header "Wifi/route.h"
    export *
}
```

And, there is my podspec:
```
  Pod::Spec.new do |s|
  s.name             = 'BVCommon'
  s.version          = '0.1.1'
  s.summary          = 'Blackvision'
  s.description      = 'BVCommon'
  s.homepage         = 'http://www.blackvision.net'
  s.license          = { :type => 'MIT' }
  s.author           = { 'Blackvision' => 'http://www.blackvision.net' }
  s.source           = { :http => "https://app.heimouyun.com/sdk/ios/#{s.name}-#{s.version}.zip", :type => "zip" }
  
  s.swift_versions = '5.0'

  s.ios.deployment_target = '11.0'

  s.vendored_frameworks = 'lib/*.xcframework'

  s.compiler_flags = '-ObjC -all_load'

  s.framework = 'CommonCrypto'

  s.dependency 'MQTTClient', '0.15.3'
  s.dependency 'CocoaAsyncSocket', '7.6.5'
  s.dependency 'Alamofire', '5.4.4'
  s.dependency 'SwiftyJSON', '5.0.1'
  s.dependency 'GZIP', '1.3.0'
end
```

**Comment by dnkoutso** [comment]
It seems you are using `carthage` to build the framework and not cocoapods. TO use a modulemap you have to place it inside the xcframework itself and it will be used by Xcode by default.

I am going to preemptively close as I do not see any action we can take here. Happy to re-open this issue if we find a bug or enhancement in CocoaPods.
