### ISSUE TITLE
CocoaPods installed but not working.

### ISSUE THREAD

**Issue by sohelansaridhule** [CocoaPods/CocoaPods#11043]
I installed Flutter SDK successfully on **Mac monterey version**, but when I run `flutter doctor` command, get the result for Cocoapods like below - 

>  CocoaPods installed but not working.
>         You appear to have CocoaPods installed but it is not working.
>         This can happen if the version of Ruby that CocoaPods was installed with
>         is different from the one being used to invoke it.
>         This can usually be fixed by re-installing CocoaPods.
>       To re-install see
>       https://guides.cocoapods.org/using/getting-started.html#installation for
>       instructions.

I installed cocoapods using  `sudo gem install cocoapods ` then the result remained the same.
Then I uninstalled and reinstalled using `brew install cocoapods ` then also the result remained the same.

Ignoring that cocoapods error, when I hit the command `pod install` I get this result - 

> Updating local specs repositories
> Analyzing dependencies
> [!] No podspec found for `contacts_service` in `.symlinks/plugins/contacts_service/ios`

**Comment by dnkoutso** [comment]
This seems like a flutter issue. Please file an issue with flutter github repo. Try using cocoapods on a no flutter project to see if its working.
