### ISSUE TITLE
 ERROR | [iOS] file patterns: The `vendored_frameworks` pattern did not match any file.

### ISSUE THREAD

**Issue by khushiMishti** [CocoaPods/CocoaPods#11045]
<!--
ℹ I added spec.ios.vendored_frameworks = "photoFramework.xcframework".
but its giving me error 'vendored_framework' pattern did not match.

**Comment by khushiMishti** [comment]
Hy dnkousto, 
Why are you closing my question? If you can help me, then respond otherwise don't be close my thread.

**Comment by dnkoutso** [comment]
@khushiMishti the original issue you filed did not follow the issue template that this repo specifies. It provided little to no information for us to diagnose anything besides the error. There was no podspec information attached or a sample app reproducing and showing an issue in CocoaPods.

We get a lot of issues filed daily most of which do not follow our template (or just the default template). We do not have the time to triage issues that are incomplete and without any information that is actionable to us.

Please file a new issue providing all the information needed or ask in StackOverflow under `cocoapods` tag.
