### ISSUE TITLE
no such module error throw when run in command line but in xcode, it is success

### ISSUE THREAD

**Issue by nguyenhuutinh** [CocoaPods/CocoaPods#11053]
Hello,
with pod 1.11.2
I face this issue when run the command line `flutter run` to run ios app in `simulator iphone 13`
```
[CP] Unable to find matching .xcframework slice in 'ios-i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64).

error: no such module 

```
but from Xcode, it is success.

Do you know the reason of my error?

Thanks

**Comment by dnkoutso** [comment]
Hi there, this is not a sufficient issue report for us to assist. Please file in a new issue filling in the template and provide a sample app showing the issue along with the environment you are running into.
