### ISSUE TITLE
Is it safe to use Podfile.lock files with different versions of Cocoapods?

### ISSUE THREAD

**Issue by Luca-spopo** [CocoaPods/CocoaPods#11059]
Would cocoapods properly throw an error if it cannot confidently read a podfile.lock created by a newer/older version of cocoapods? (As opposed to installing the wrong dependencies)

**Comment by dnkoutso** [comment]
It posts a warning but the Podfile.lock contents havent been updated recently.

I think its safe to depend on it for the time being. Going to close as at this time there is no action for us to take here.

**Comment by dnkoutso** [comment]
Happy to continue discussion btw and re-open if we find an enhancement!

**Comment by Luca-spopo** [comment]
@dnkoutso Thanks for the answer, I just need to know, that in case there are updates to the lock file contents (or historically, in past updates to lockfile contents), is the format backward compatible, and if not does CocoaPods throw an error?

**Comment by dnkoutso** [comment]
I do not think there is any mechanism that ensures backwards compatibility for the lockfile contents but historically it hasnt changed to cause issues.

We internally rely on parsing it in quite a few places.

**Comment by Luca-spopo** [comment]
Thanks!

**Comment by Luca-spopo** [comment]
@dnkoutso From what I see, a warning is only issued if the lock file was made using a newer version. No warning is issued if the lock file was made using an older version, this leads me to believe that it is backward compatible for the major version.

In case the lock file is older by a major version, looks like the pods are recreated.
