### ISSUE TITLE
Loading through pods is giving compilation error

### ISSUE THREAD

**Issue by rishavjn** [CocoaPods/CocoaPods#11054]
I have a git project which have folder structure like as shown below.

Root Folder 

   Folder A

     a.swift

     b.swift

   Folder B

     a.swift

     c.swift

   Folder C

     a.swift

     d.swift

And so on.

I want create cocoapod for this but by generic way it is giving me error. 

The error is: Two files with same name under different paths are there. So can’t compile them.

a.swift file is common in different folders. While loading this project from podspec file and compiling the example project it gives error.
How to create podspec file for this structure?

What should I do?

**Comment by dnkoutso** [comment]
Hi there, please ask this question in StackOverflow under `cocoapods` tag for assistance.
