### ISSUE TITLE
post-install hook: undefined method `root_object' for nil:NilClass

### ISSUE THREAD

**Issue by lucifer001** [CocoaPods/CocoaPods#11064]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What happened instead?

[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `root_object' for nil:NilClass

/Users/pix1o/Desktop/ASIA_APP/JGNPlan/Podfile:183:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:196:in `post_install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:945:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:933:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:932:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:331:in `block (2 levels) in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:330:in `block in create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:301:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:180:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:167:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.2.2
        Host : macOS 11.6 (20G165)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ dcb8f7a7208e6fb2ac86915b69c5e0aaa6438872

               master - git - https://gitlab.pengpengla.com/pengpengios/podspec.git @ c9421c8f192b3dd5461059ccc0b5d00c599f4379

               pengpengios - git - https://gitlab.pengpengla.com/pengpengios/podspec.git @ 4e6ade615f3fbaadc77c12948d8b99cdfef1efe8

               pengpengla-ioscore-podspec - git - https://gitlab.pengpengla.com/ioscore/podspec.git @ 5964a515b3a2db81bc34bd090432f4e4771093cc

               trunk - CDN - https://cdn.cocoapods.org/
               upworldcjw - git - https://github.com/upworldcjw/podsecRepo.git @ c0e54e0010e97aed2460fd95c69210144fa03460

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '10.0'
inhibit_all_warnings!
source 'https://github.com/upworldcjw/podsecRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

install! 'cocoapods',
      :generate_multiple_pod_projects => true,
      :incremental_installation => true

target:Test do

pod 'WCDB', '1.0.7.5', :inhibit_warnings => true

pod 'CocoaAsyncSocket', '7.6.5', :inhibit_warnings => true

pod 'IAPHelper', '1.1', :inhibit_warnings => true

pod 'YYCache', '1.0.4', :inhibit_warnings => true, :project_name => 'YY'

pod 'YYCategories', '1.0.4', :inhibit_warnings => true, :project_name => 'YY'

pod 'Masonry', '1.1.0', :inhibit_warnings => true
pod 'SnapKit', '5.0.1'

pod 'WZLSerializeKit', '1.2.2'

pod 'MJRefresh', '3.7.2', :inhibit_warnings => true, :project_name => 'MJ'

pod 'KSPhotoBrowser', '0.3.1'

pod 'MBProgressHUD', '~> 1.1.0', :inhibit_warnings => true

pod 'IQKeyboardManager', '6.5.6', :inhibit_warnings => true

pod 'TZImagePickerController', '3.6.6', :inhibit_warnings => true

pod 'DZNEmptyDataSet', '1.8.1', :inhibit_warnings => true

# pod 'XHLaunchAd', :inhibit_warnings => true

pod 'YYText', '1.0.7', :project_name => 'YY'

pod 'WZLBadge', '1.2.6'

pod 'JXCategoryView', '1.5.9'

pod 'Bugly', '2.5.90'

pod 'Adjust', '4.29.6', :inhibit_warnings => true

pod 'FBSDKCoreKit', '11.0.0', :project_name => 'FaceBook'
pod 'FBSDKLoginKit', '11.0.0', :project_name => 'FaceBook'

pod 'CocoaLumberjack', '3.7.2', :inhibit_warnings => true

pod 'YYModel', '1.0.4',
  :inhibit_warnings => true,
  :project_name => 'YY'

pod 'SSZipArchive', '2.4.2'

pod 'LookinServer', '1.0.4', :configurations => ['Debug']
# pod 'WoodPeckeriOS', :configurations => ['Debug']

pod 'lottie-ios', '~> 2.5.3', :inhibit_warnings => true

pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
pod 'Firebase/Performance'

pod 'JJException', '0.2.11'

pod 'YYImage', '1.0.4', :project_name => 'YY'
pod 'YYImage/WebP', :project_name => 'YY'

pod 'CocoaSecurity', '1.2.4'

pod 'VungleSDK-iOS', '6.10.3'

pod 'MJExtension', '3.3.0', :project_name => 'MJ'

pod 'GoogleSignIn', '6.0.2'

pod 'HNCountryLanguage',:project_name => 'HNFrameWork'

pod 'HNCategory',:project_name => 'HNFrameWork'
end

post_install do |installer|
  
    installer.pods_project.root_object.attributes['LastSwiftUpdateCheck'] = 9999
    installer.pods_project.root_object.attributes['LastUpgradeCheck'] = 9999
    shared_data_dir = Xcodeproj::XCScheme.user_data_dir(installer.pods_project.path)
    Dir["#{shared_data_dir}/*.xcscheme"].each do |scheme_path|
      scheme = Xcodeproj::XCScheme.new scheme_path
      scheme.doc.root.attributes['LastUpgradeVersion'] = 9999
      scheme.save!
    end
      
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end
        end
        project.build_configurations.each do |bc|
            bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end
    
end
```

**Comment by dnkoutso** [comment]
This is your own internal issue within the `Podfile`. Post install hooks are not part of CocoaPods, they are only offered as hooks. Please inspect Podfile line 196 to find the issue.
