### ISSUE TITLE
Cuckoo executable (cuckoo_generator) gives BAD CPU type in executable error

### ISSUE THREAD

**Issue by michalmlu** [CocoaPods/CocoaPods#11067]
The newest version of Cuckoo (1.5.2) when integrated with Xcode project with CocoaPods downloads an executable that is not runnable on an intel machine.

I downloaded both 1.5.1 & 1.5.2 versions of Cuckoo with the command line from Podspec

curl -Lo cuckoo_generator https://github.com/Brightify/Cuckoo/releases/download/1.5.1/cuckoo_generator
curl -Lo cuckoo_generator https://github.com/Brightify/Cuckoo/releases/download/1.5.2/cuckoo_generator

after adding exec permissions with chmod

1.5.1 version of Cuckoo gives this output
```
Available commands:

   generate   Generates mock files
   help       Display general or command-specific help
   version    Prints the version of this generator.
```

while the other fails like so

```
-bash: ./cuckoo_generator: Bad CPU type in executable
```

I suspect that it was build against the Apple Silicon

**Comment by dnkoutso** [comment]
Please file an issue with the cuckoo repo instead. CocoaPods does not integrate with this tool nor do we maintain it.

**Comment by michalmlu** [comment]
Sorry I mistook the windows. I thought that I was doing just that

**Comment by dnkoutso** [comment]
ha np!
