### ISSUE TITLE
"pod update" fails on MacBook Pro m1 max, zsh

### ISSUE THREAD

**Issue by erik-utr** [CocoaPods/CocoaPods#11078]
* [ x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run pod update

## What did you expect to happen?

update (note: pod install works fine)

## What happened instead?

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27arm64%27%2C+need+%27x86_64%27%29%29%2C+%27%2Fusr%2Flib%2Fffi_c.bundle%27+%28no+such+file%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.4%2Flib%2Fffi_c.bundle&type=Issues

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.2.30
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '14.7'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'utrplay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for utrplay
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'JTAppleCalendar'
  pod 'iCarousel', '~> 1.8'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'libPhoneNumber-iOS'
  pod 'GooglePlaces'
  pod 'SwiftCharts', '~> 0.6.5'
  pod 'SwiftGen', '~> 6.0'
  pod 'WePay', '~> 7.0.0'
  pod 'Stripe'
  pod 'Iterable-iOS-SDK'
  pod 'Introspect'
  pod 'Firebase/DynamicLinks'

  pod 'Analytics'
  pod 'PhoneNumberKit'

  post_install do |pi|
      pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.7'
        end
      end
  end
end
```

**Comment by erik-utr** [comment]
sudo arch -x86_64 gem install ffi

This fixed the problem

**Comment by jpike88** [comment]
```gem install --user-install ffi -- --enable-libffi-alloc```

This worked for me
