### ISSUE TITLE
Cocoapods-patch 1.0.1 won't apply patches

### ISSUE THREAD

**Issue by martin-dzuro** [CocoaPods/CocoaPods#11070]
# Report

## What did you do?

`pod install` 

## What did you expect to happen?

It was expected to install all the dependencies and apply a patch before creating the workspace

## What happened instead?

No patch (via Cocoapods-patch) was applied. Seems like Pod::HooksManager.register('cocoapods-patch', :pre_integrate) was never called.

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.4 (20F71)
       Xcode : 13.0 (13A233)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-patch       : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
plugin 'cocoapods-patch'

target 'podTest' do
  use_frameworks!

  pod 'TestFairy'
end
```

## Project that demonstrates the issue

The issue was described in detail here: https://github.com/DoubleSymmetry/cocoapods-patch/issues/17 
As this seems to be an issue with Pod Hooks, I'm also posting it here

https://github.com/martin-dzuro/CocapodsPatchIssueExample

**Comment by amorde** [comment]
Hello! It's not clear to me what we need to do here. We don't control the implementation of plugins, but if there's a compatibility issue that was caused by a change to CocoaPods we can investigate that with more information.

Going to close for now as there's nothing for us to do without more information
