### ISSUE TITLE
Can't install pod because of mismatched version of Firebase/core only

### ISSUE THREAD

**Issue by NandhakumarThiyagarajah** [CocoaPods/CocoaPods#11095]
[

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.
<img width="1440" alt="Screenshot 2021-12-10 at 9 45 26 PM" src="https://user-images.githubusercontent.com/95929751/145606090-0ae6deb2-44d2-4e30-823a-10ff5da3312c.png">
<img width="1440" alt="Screenshot 2021-12-10 at 9 45 21 PM" src="https://user-images.githubusercontent.com/95929751/145606140-aaae8886-2d27-4528-9838-7ecb98f85ab9.png">

**Comment by paulb777** [comment]
Following the suggestions in the error message might work like `pod install --repo-update`

Otherwise this is a usability issue and should be followed up with react-native or on stackoverflow.
