### ISSUE TITLE
Cloudflare wants me to answer a Captcha in Terminal

### ISSUE THREAD

**Issue by etoiledemer** [CocoaPods/CocoaPods#11091]
# Report

## What did you do?
` pod repo update`

## What did you expect to happen?

an update

## What happened instead?

It flooded my terminal with HTML from a Cloudflare request for a CAPTCHA. Please remove this annoying Captcha check 

```
pod repo update
[...]

  $ /usr/local/bin/git -C /Users/macos/.cocoapods/repos/master reset --hard origin/master
  Updating files: 100% (150876/150876), done.
  HEAD is now at 29da6e893be0 [Add] Queen 1.6.0-official-lite
Updating spec repo `trunk`

[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/deprecated_podspecs.txt Response: 403 <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>

<title>Attention Required! | Cloudflare</title>

<meta name="captcha-bypass" id="captcha-bypass" />

[...]
```
## CocoaPods Environment

not relevant

**Comment by dnkoutso** [comment]
cc @igor-makarov is this an issue on CDN?

**Comment by igor-makarov** [comment]
@dnkoutso seems so, but I don't believe we can do anything about it. 

@etoiledemer you could try opening the URL  https://cdn.cocoapods.org/deprecated_podspecs.txt in a browser and answering the CAPTCHA - maybe this will help?

**Comment by etoiledemer** [comment]
@igor-makarov captcha can't be disabled on CF ?

**Comment by dnkoutso** [comment]
we are uncertain why you see the captcha though. I am able to successfully see the list of podspecs in the URL @igor-makarov pasted above without need for captcha.

**Comment by etoiledemer** [comment]
I connect through a Tor Exit

**Comment by igor-makarov** [comment]
I believe the CAPTCHA is triggered by CloudFlare's DDoS protection features. However, we cannot turn these features off as they serve a purpose.
