### ISSUE TITLE
targets - duplicate interface definition

### ISSUE THREAD

**Issue by larromba** [CocoaPods/CocoaPods#1109]
Hey there,

Firstly - now I'm used to the pod way - I got to say a massive thanks - you've made my coding life much easier; if I could buy you all a tasty beer I would!

My problem:
- I've created 2 pods for api communication. I've been asked to keep them identical, but change one into a 'testing' implementation that can be developed without actually calling the api (e.g. it simply sends back fake JSON data for api calls that don't yet exist).
- The problem is that when I add a new file to the test api that extends an api base class, when I run my xcode project, it moans about there being 'duplicated headers'. I assume because my pod project contains 2 pod folders of identical headers (plus any new headers added to the test api pod). I hope this makes sense!

How I've done it:
- I created 2 local cocoapods that contain the same header files / classes, lets call these: A and A_TEST.
- In my Xcode project, I create 2 targets, a and a_test.
- In my Podfile, I then do the following:

target :a do
    pod 'A', :path => "pathTo/A"
end

target :a_test do
    pod 'A_TEST', :path => "pathTo/A_TEST"
end

(note: I'm expecting to exclude any references or header searches to A in the a_test target and vice versa)
(note: I've also tried ":exclusive => true do" on both)
- I run: sudo pod install
- In the pod xcode project, the correct headers have been added to the correct static libraries.
- I successfully build both targets (a and a_test) in my xcode project.
- I add a new file into the test api pod that extends an api base class.
- I update all pods in my xcode project
- I import the new api file into my app
- I build both targets again but now receive a 'duplicate interface definition for [base class] class' error

I 'think' the problem is that, something is not excluding the relevant headers on building each target. 

I've ensured my xcode project is using $(inherited) in the right places. I've also ensured both my project and the pod project have the correct User-Defined variables, e.g. ${PODS_BUILD_HEADERS_SEARCH_PATHS}.

I've tried removing the suspected header imports from the relevant .xcconfig files to no avail.

Any and all help will be appreciated!

**Comment by LouisRosner** [comment]
THanks for your answer
