### ISSUE TITLE
pod trunk register no longer working

### ISSUE THREAD

**Issue by kstenerud** [CocoaPods/CocoaPods#11090]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk register (my-email) "(my-name)"

## What did you expect to happen?

I expected the received email link to go somewhere useful

## What happened instead?

The link in the confirmation email went to a 404 error page: https://trunk.cocoapods.org/sessions/verify/fe1d15af

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]
    RubyGems : 3.1.2
        Host : macOS 11.6 (20G165)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.23.0
Ruby lib dir : /Users/karl/.rbenv/versions/2.7.1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/karl/.rbenv/versions/2.7.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```
## Project that demonstrates the issue

This is a problem in the infrastructure itself.

**Comment by orta** [comment]
This is very likely to be a link checker validating your session early
