### ISSUE TITLE
Blank PODS_ROOT causing Build Errors

### ISSUE THREAD

**Issue by stationkeeping** [CocoaPods/CocoaPods#1110]
I'm unable to build a project that uses CocoaPods. I get the following errors:

> diff: /../Podfile.lock: No such file or directory
> diff: /Manifest.lock: No such file or directory
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

`$ pod install` seems to work fine and adds a `Pods` Project to my Workspace. I've tried `$ pod update` but this doesn't help.

It seems that `PODS_ROOT` is not being set. Where is it defined?

Podfile:

```
workspace 'Example.xcworkspace'
xcodeproj 'Example/Example.xcodeproj' 
platform :ios, '6.0'

pod 'TestFlightSDK', '~> 1.3.0-beta.5'
pod 'TestFlightLogger', '~> 0.0.2'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'Reachability', '~> 3.1.0'
pod 'SBJson', '~> 3.2'
pod 'MKMapViewZoom', '~> 1.0.0'
```

**Comment by db42** [comment]
If you modified pods setting for different target, you'd need two steps to force a re-integration:

1. Remove the pods library from the 'Link Binary with Libraries' of the target
2. Set Configuration to 'None' for the project. Select project (not the target), then tap on 'Info'. More details http://stackoverflow.com/questions/16795280/using-cocoapods-with-multiple-projects
