### ISSUE TITLE
I can't find my pod when I search on cocoapods.org

### ISSUE THREAD

**Issue by shichuanyang** [CocoaPods/CocoaPods#11109]
# Report

## What did you do?

I uploaded my pod 'EasyAdsSDK' , and run 'pod search EasyAdsSDK' can find it, but I can't find EasyAdsSDK when I search on cocoapods.org

## What did you expect to happen?

Find EasyAdsSDK when I search on cocoapods.org

## What happened instead?

can't Find EasyAdsSDK  when I search on cocoapods.org

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.1.4
        Host : macOS 11.6 (20G165)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 99009ee6baa09fb011c9126dd63cefedb7704074

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

in Podfile add 
pod 'EasyAdsSDK'
  pod 'EasyAdsSDK/CSJ'
  pod 'EasyAdsSDK/GDT'
  pod 'EasyAdsSDK/KS'
  pod 'EasyAdsSDK/BD'

can find soure of my pod

**Comment by shichuanyang** [comment]
I'm thinking that's just a CDN build delay, but it's been a week

**Comment by vilanovi** [comment]
In my case, I've published a pod (new) and it is not listed in the website, but neither in pod search (and I can't install it via pod install). I've opened also an issue: https://github.com/CocoaPods/CocoaPods/issues/11119

**Comment by jeanhbr** [comment]
Same here for our pod CSCardTransition. We cannot find it on the CocoaPod website, yet it has been more than a week since we published it.

**Comment by dnkoutso** [comment]
Those do get indexed but eventually, I am not sure how frequently but those appear now.
