### ISSUE TITLE
Fail to Install 'cordova-plugin-facebook4'

### ISSUE THREAD

**Issue by edrafael** [CocoaPods/CocoaPods#11103]
# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Install all pod dependencies correctly.

## What happened instead?

ℹ Fail to install

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

Traceback (most recent call last):
        4: from /usr/local/bin/pod:23:in `<main>'
        3: from /usr/local/bin/pod:23:in `load'
        2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/bin/pod:55:in `<top (required)>'
        1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

## Project that demonstrates the issue
![image (11)](https://user-images.githubusercontent.com/95452320/146049720-fe6d634f-94cc-4d1b-b1bd-11ac2b1d295d.png)
![image (10)](https://user-images.githubusercontent.com/95452320/146049730-a9296a57-3422-4cf1-aee4-105c48a13719.png)
![image (9)](https://user-images.githubusercontent.com/95452320/146049735-d2732e29-f3f9-4672-85ad-22298cfa7607.png)

**Comment by dnkoutso** [comment]
error message states the issue. Please do not run coocapods as root or pass `--allow-root` with latest version of cocoapods 1.11.1.
