### ISSUE TITLE
Could not build the application for the simulator. Error launching application on iPhone 13.

### ISSUE THREAD

**Issue by susantodev** [CocoaPods/CocoaPods#11117]
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           20.5s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:B41ECBB1-E3F3-41DA-A3FD-73BCA0AA072E, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:2EC07032-3AC1-4CB2-B269-6B8E5D1927B0, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:B40E3A8E-F490-4219-86C3-C0C6CA848DFD, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:EB6C090F-46E4-4E63-8A75-D7CDF1FBDED1, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:3EA6742A-6030-40FC-AA69-A0E270A3D87E, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:628C9585-CB23-4689-9AA7-2B56CD91E33E, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:90E0D3B1-DC53-4D36-84CC-4B551CDCFF62, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:F14E0696-E1DA-4890-8009-FBF0B8CE0B2A, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:A885AE5B-DC6D-438F-A509-D62B4CF40FA4, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:6D7C5649-6868-45E4-947E-B404D7615219, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:905ED5A2-32DD-4344-996B-43AE782D461B, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:BEB8E0B6-135C-4E12-A35A-4AE760B7C8B5, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:56CA6EFA-4C6A-4DE6-A91E-D7F6C4EFCC20, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:1244F25A-2072-4EBC-9B9B-D9106E3752C0, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:E7AEC39B-5666-4257-B57E-9FC829C14F88, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:7B29CE28-152A-4502-A624-8CE9A83A5B17, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:90311FAB-82B5-44FD-B118-C96CE0704607, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:BF42D075-4152-4F8B-BE48-F49E46DDEC43, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:D56C5B6E-AA4C-4FFC-A43C-6DCC43A47B5D, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:C637D4B5-371B-4B81-95A3-D6816426EE0E, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:CAEE83CD-6883-4BAA-83D1-A66EF6EEE148, OS:15.0, name:iPod touch (7th generation) }
    { platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008103-001E39D62ED1001E }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/susanto/StudioProjects/Fabries-Lagbe-Apps--main/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'connectivity_plus' not found
    @import connectivity_plus;
     ~~~~~~~^~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Objects-normal/arm64/Binary/libPods-Runner.a'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Objects-normal/arm64/Pods-Runner.LinkFileList'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Objects-normal/x86_64/Binary/libPods-Runner.a'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Objects-normal/x86_64/Pods-Runner.LinkFileList'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Pods-Runner-all-non-framework-target-headers.hmap'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Pods-Runner-all-target-headers.hmap'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Pods-Runner-generated-files.hmap'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Pods-Runner-own-target-headers.hmap'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Pods-Runner-project-headers.hmap'

    note: Removed stale file '/Users/susanto/Library/Developer/Xcode/DerivedData/Runner-gnqjlrbjdpfdstgjpolazfxxpzad/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-Runner.build/Pods-Runner.hmap'

    warning: Stale file '/Users/susanto/StudioProjects/Fabries-Lagbe-Apps--main/build/ios/Debug-iphonesimulator/libPods-Runner.a' is located outside of the allowed root paths.


Could not build the application for the simulator.
Error launching application on iPhone 13.

**Comment by paulb777** [comment]
Sorry. This is not a CocoaPods issue.
