### ISSUE TITLE
Physical Cocoa pods

### ISSUE THREAD

**Issue by dingtianran** [CocoaPods/CocoaPods#11111]
# Wish all you guys have a nice & happy holiday! 🍫

![IMG_6819](https://user-images.githubusercontent.com/720392/146836089-f25409ea-f9ca-482c-be87-363e17fb93cd.jpg)

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Taking a picture of Cocoapods

## What did you expect to happen?

Happy holiday

## What happened instead?

Happy holiday x2

## CocoaPods Environment

Reality

## Project that demonstrates the issue

Have fun guys!

**Comment by dnkoutso** [comment]
amazing!!! thank you so much !! :D
