### ISSUE TITLE
Publishing pod via trunk successfully --> Pod not available

### ISSUE THREAD

**Issue by vilanovi** [CocoaPods/CocoaPods#11119]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Submitted a new Pod via trunk successfully: `pod trunk push MagicBell.podspec`. Original repo at https://github.com/magicbell-io/magicbell-ios.

The command ended successfully, with the beautiful emojis and the link to our new pod in cocoapods:
https://cocoapods.org/pods/MagicBell.

The spec has been pushed to the master branch of CocoaPods/Specs:
https://github.com/CocoaPods/Specs/blob/master/Specs/8/1/0/MagicBell/1.0.0-alpha.1/MagicBell.podspec.json

The pod info can be fetched via `pod trunk info MagicBell`

```
MagicBell
    - Versions:
      - 1.0.0-alpha.1 (2021-12-23 15:39:36 UTC)
    - Owners:
      - Joan Martin <joan@mobilejazz.com>
      - Josue Montano <josue@magicbell.io>
```

## What did you expect to happen?

The library to be available in both:
- Website search: https://cocoapods.org > search for "MagicBell"
- Website link: https://cocoapods.org/pods/MagicBell
- Searchable via "pod search MagicBell"
- Installable via `pod "MagicBell"` in a Podfile
 
## What happened instead?

- You can't find it when searching on the website
- The link to the cocoapods page redirects to the public webstie of MagicBell instead to the custom page of Cocoapods

And most important: 

- It is not searchable via pod search
- It cannot be installed as the podspec is not found (even after cleaning cache, doing a `pod repo update`, trying from multiple computers in multiple locations)

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.6 (20G165)
       Xcode : 13.1 (13A1030d)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

Any project that uses `pod "MagicBell"`, or any attempt to search for it.

**Comment by vilanovi** [comment]
I've published a new version and again, it is not available:

- Cocoapods link redirects to the website of MagicBell
- MagicBell pod is not listed in Cocoapods website
- `pod search MagicBell` cannot find it
- `pod 'MagicBell'` in a podfile fails
- `pod trunk info MagicBell` shows the info of the pod successfully

![image](https://user-images.githubusercontent.com/1830894/147647629-56fdff56-47e7-478e-91f8-412b0275de80.png)

![image](https://user-images.githubusercontent.com/1830894/147647765-a22da9b8-1697-40a3-83b9-e45e84ac68aa.png)

**Comment by vilanovi** [comment]
Ok, I think I know what happens. As the pod is being deployed as a pre-release (1.0.0-alpha.X), I think Cocoapods is not publishing it publicly: not in the website (can't be found), and not in pod search. It is neither accessible via pod install doing `pod "MagicBell"`. 

However, now I see it is accessible via pod install if I do:

- `pod 'MagicBell', '1.0.0-alpha.2'` (specifying the exact version) 
- `pod 'MagicBell', '>=0'` (specifying any version greater than 0)

Therefore, I assume this is the behavior of Cocoapods, and MagicBell will be published and available as soon we publish a non-alpha (not a pre-release) version. 

I would have loved to find this behavior documented somewhere.

**Comment by GRyabkin** [comment]
@vilanovi excuse me could you tell me how to check that framework you have built for cocoapods is pre-release or not? Is it possible using cocoapods linting or some command line tool?

**Comment by dagronf** [comment]
I'm finding the same situation with a couple of libraries that I had on Cocoapods for well over a year.  Both DSFSparkline and my QRCode package have the same issue. 

* If I search for 'sparklines' on the website, the package (DSFSparkline) doesn't appear in the results
* If I search for 'sparklines' on the command line, the package appears.

```
-> DSFSparkline (5.1.1)
   Simple Sparkline View for macOS, iOS and tvOS
   pod 'DSFSparkline', '~> 5.1.1'
   - Homepage: https://github.com/dagronf
   - Source:   .git
   - Versions: 5.1.1, 5.1.0, 5.0.1 [master repo]
   - Subspecs:
     - DSFSparkline/Core (5.1.1)
```

This package first appeared on Cocoapods around Dec 2019, so I'm guessing it's not a CDN issue.

Same this has occurred with my QRCode package (DSF_QRCode).  Can be found via search on the command line but not via the website

```
-> DSF_QRCode (17.0.0)
   A simple drop-in macOS/iOS/tvOS/watchOS QR Code generator view for Swift, Objective-C and SwiftUI.
   pod 'DSF_QRCode', '~> 17.0.0'
   - Homepage: https://github.com/dagronf/QRCode
   - Source:   https://github.com/dagronf/QRCode.git
   - Versions: 17.0.0, 16.1.1, 16.1.0, 16.0.1, 16.0.0 [master repo]
```

Given that there are thousands of packages available via the website, I must be doing something wrong.
