### ISSUE TITLE
NoMethodError - undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by Sungen** [CocoaPods/CocoaPods#11132]
### Command

```
/usr/local/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin21]
    RubyGems : 3.2.22
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /usr/local/Cellar/ruby/3.0.2_1/lib
Repositories : mPaaS_iOS_specs - git - https://code.aliyun.com/mpaas-public/podspecs.git @ 930a2056ebefdda697fc7517223351ff8f0737c0

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-mPaaS       : 0.9.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# mPaaS Pods Begin
plugin "cocoapods-mPaaS"
source "https://code.aliyun.com/mpaas-public/podspecs.git"
mPaaS_baseline '10.1.68'  # 请将 x.x.x 替换成真实基线版本
mPaaS_version_code 39   # This line is maintained by MPaaS plugin automatically. Please don't modify.
# mPaaS Pods End
# ---------------------------------------------------------------------

use_frameworks!
platform :ios, '9.0'
inhibit_all_warnings!

def xmf_special_pods
  
end

def xmf_pods
  
end

def third_pods
  pod 'SDWebImage'
  pod 'Masonry'
end

def mpaas_pods
  remove_pod "mPaaS_SDWebImage"
  remove_pod "mPaaS_Masonry"
  
#  mPaaS_pod "mPaaS_Push" #消息推送
  mPaaS_pod "mPaaS_RPC" #移动网关
  mPaaS_pod "mPaaS_Sync" #移动同步
#  mPaaS_pod "mPaaS_Config" #开关配置
#  mPaaS_pod "mPaaS_Hotpatch" #热修复
#  mPaaS_pod "mPaaS_Upgrade" #升级发布
  mPaaS_pod "mPaaS_Share" #社交分享
#  mPaaS_pod "mPaaS_DataCenter" #统一存储
  mPaaS_pod "mPaaS_ScanCode" #扫码
#  mPaaS_pod "mPaaS_Multimedia" #多媒体
  mPaaS_pod "mPaaS_MobileFramework" #移动框架
  mPaaS_pod "mPaaS_CDP" #智能投放
  
#  mPaaS_pod "mPaaS_TinyApp" #小程序发布
#  mPaaS_pod "mPaaS_Nebula" #离线包和H5
end

def target_pods
  mpaas_pods
  third_pods
  xmf_pods
end

def push_pods
  
end

abstract_target 'common' do
  target_pods

  target 'XIBPB' do
   
  end
  
  target 'XIBPB_T' do
    mPaaS_pod 'mPaaS_DevHelper'
#    mPaaS_pod 'mPaaS_NebulaDevHelper'
  end
end

abstract_target 'push' do
  push_pods
  
  target 'Push' do
  
  end

  target 'Push_T' do
  
  end
end

#移除最低8.0支持的警告提示
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
```

### Error

```
NoMethodError - undefined method `+' for nil:NilClass
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:306:in `block (3 levels) in <module:CocoapodsmPaaSHooks>'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:298:in `foreach'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:298:in `block (2 levels) in <module:CocoapodsmPaaSHooks>'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:158:in `each'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:158:in `block in <module:CocoapodsmPaaSHooks>'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:122:in `block (3 levels) in run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:115:in `each'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/hooks_manager.rb:114:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:649:in `run_plugins_post_install_hooks'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:614:in `perform_post_install_actions'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:170:in `install!'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%2B%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NoMethodError - undefined method `real_path`
   https://github.com/CocoaPods/CocoaPods/issues/8082 [open] [14 comments]
   20 May 2021

 - post-install hook: undefined method `root_object' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/11064 [closed] [1 comment]
   6 weeks ago

 - NoMethodError - undefined method `each' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9239 [closed] [11 comments]
   2 weeks ago

and 278 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60%2B%27%20for%20nil&type=Issues&utf8=✓

**Comment by Sungen** [comment]
uncommend 
#  mPaaS_pod "mPaaS_TinyApp" #小程序发布
#  mPaaS_pod "mPaaS_Nebula" #离线包和H5
error changed
[!] Invalid `Podfile` file: undefined method `each' for nil:NilClass.

 #  from /Users/xib/Documents/Projects/XIB_MBS/xibpb-ios/Podfile:95
 #  -------------------------------------------
 #    
 >    mPaaS_pod "mPaaS_TinyApp" #小程序发布
 #    mPaaS_pod "mPaaS_Nebula" #离线包和H5
 #  -------------------------------------------

/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:50:in `initialize'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:327:in `new'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/podfile.rb:293:in `from_file'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/config.rb:205:in `podfile'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:46:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
This looks like an issue with your own hook:
```
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:306:in `block (3 levels) in <module:CocoapodsmPaaSHooks>'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:298:in `foreach'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:298:in `block (2 levels) in <module:CocoapodsmPaaSHooks>'
/usr/local/lib/ruby/gems/3.0.0/gems/cocoapods-mPaaS-0.9.5/lib/cocoapods-mPaaS/cocoapods_hook.rb:158:in `each'
```
