### ISSUE TITLE
pod install does not create Info.plist

### ISSUE THREAD

**Issue by linhVmodev** [CocoaPods/CocoaPods#11146]
* [ *] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

create new Xcode project and add pod 'Alamofire' or any other pod

## What did you expect to happen?

Can run normally

## What happened instead?

Info.plist not existed in Target Support Files/Alamofire

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.5.2 (20G95)
       Xcode : 12.5.1 (12E507)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test
  pod 'Alamofire'

end
```

## Project that demonstrates the issue
[https://github.com/linhVmodev/test](url)

**Comment by linhVmodev** [comment]
Some time work, some time doesn't. Closed.

**Comment by shuixuan1225** [comment]
post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                  config.build_settings['GENERATE_INFOPLIST_FILE'] = 'YES'
               end
          end
   end
end
