### ISSUE TITLE
CocoaPods Install Error

### ISSUE THREAD

**Issue by iOSamit** [CocoaPods/CocoaPods#11140]
Not able to install CocoaPods

Xcode  - 13.2.1
macOs BigSur - 11.6.2

Error 
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.

**Comment by DreamPWJ** [comment]
me too   why?

**Comment by osamaazmat** [comment]
This is a permission issue. You should be using a seperate ruby manager for cocoapods. 

I solved it by doing the following steps:

1) Install a third party Ruby Manager (I Installed rbenv)
2) Install Ruby version LESS than 3.1.0 (3.1.0 has issues in cocoapods, I installed 2.7.5)
3) Setup rbenv as global and change ruby path to the one from rbenv
4) Install Cocoapods again

Detailed Explanation here:

https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma/54873916#54873916

**Comment by Nightsquid7** [comment]
> 

@osamaazmat This worked for me.

Same issue as above, 

Xcode - 13.2.1
macOs BigSur - 11.6.2

actually I followed the [link above] (https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma/54873916#54873916) before
using chruby, which did not work. 

using rbenv seems to have fixed the issue, much thanks 🙇

**Comment by huangjihua** [comment]
me too,
cocoapods-1.11.3 

``` bash
pod install 
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /Users/hank/.nvm/versions/node in PATH, mode 040777
[!] No Xcode project found, please specify one
```

**Comment by huangjihua** [comment]
me too,
cocoapods-1.11.3 

``` bash
pod install 
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /Users/hank/.nvm/versions/node in PATH, mode 040777
[!] No Xcode project found, please specify one
```
