### ISSUE TITLE
🌈 The `[CP] Embed Pods Frameworks` run script phase is not getting added to the target

### ISSUE THREAD

**Issue by alejandrofr85** [CocoaPods/CocoaPods#11151]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I created a new framework Project in Xcode. Then used this Podfile:

```
target 'TestiOSApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => './shared'
end
```

After opening the workspace there is no `[CP] Embed Pods Frameworks` run script phase for the `TestiOSApp` target. The `shared` pod has a vendored framework, and that framework is not getting copied into the `Framework` directory of the app.

## What did you expect to happen?

The `[CP] Embed Pods Frameworks` phase should be added to the target, which should allow the vendored framework to get copied into the app.

## What happened instead?

The `[CP] Embed Pods Frameworks` phase was not added the target.

## CocoaPods Environment

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : macOS 11.6 (20G165)
       Xcode : 13.2 (13C90)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /Users/alejandro/.rvm/rubies/ruby-2.7.0/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 801285a2de3962e0fd0ff9719e64f40ef56cc834
```

## Project that demonstrates the issue

[Copy-frameworks-phase-not-being-added-issue.zip](https://github.com/CocoaPods/CocoaPods/files/7851127/Copy-frameworks-phase-not-being-added-issue.zip)

**Comment by xuzhongping** [comment]
@alejandrofr85  Hi，the shared.framework you provided is a static library and shouldn't need to be integrated into the '[CP] Embed Pods Frameworks', that's what a dynamic embed framewok needs.

**Comment by alejandrofr85** [comment]
🤦 That makes a lot of sense. Thanks for your help with this.
