### ISSUE TITLE
How to define a path in podspec file from neighbor's folder for propertys?

### ISSUE THREAD

**Issue by jocoders** [CocoaPods/CocoaPods#11154]
I have an app with the next structure:
```
root
  |- ios
      |- Pods
      |   |- ChartFramework
      |- Podfile
  |- node_modules
      |- react-native-library
          |- react-native-library.podspec
```
I need to define the path for public_header_files/vendored_frameworks propertys in react-native-library.podspec from root/ios/Pods/ChartFramework

1.Put relative path:
```
react-native-library.podspec
Pod::Spec.new do |s|
    s.name           = name
    s.version        = version
    s.description    = description
    s.summary        = summary
    s.homepage       = homepage
    s.license        = license
    s.authors        = authors
    s.source = { :http => "file://#{zipfile}"}
    s.platform     = :ios, "9.0"
    s.public_header_files = "../../ios/Pods/ChartFramework/ChartFramework.frameworks/Headers/*"
    s.vendored_frameworks = "../../ios/Pods/ChartFramework/ChartFramework.framework"
    s.dependency "React"
end
```
In this case after build in Xcode get the error:

```
'ChartFramework/ChartFramework.h' file not found
```

2.Put relative paths like an object:
```
react-native-library.podspec
Pod::Spec.new do |s|
    s.name           = name
    s.version        = version
    s.description    = description
    s.summary        = summary
    s.homepage       = homepage
    s.license        = license
    s.authors        = authors
    s.source = { :http => "file://#{zipfile}"}
    s.platform     = :ios, "9.0"
    s.public_header_files = { :path => "../../ios/Pods/ChartFramework/ChartFramework.frameworks/Headers/*" }
    s.vendored_frameworks = { :path => "../../ios/Pods/ChartFramework/ChartFramework.framework" }
    s.dependency "React"
end
```
But in this case get the error after pod install:
<img width="930" alt="Screenshot 2022-01-12 at 11 43 12" src="https://user-images.githubusercontent.com/41040813/149295129-6f2ef815-14c5-4f13-a731-2f5e001d35d7.png">

Please can you help me how to write the correct path for ChartFramework from root/node_modules/react-native-library/react-native-library.podspec?

**Comment by xuzhongping** [comment]
@jocoders Hi,for file matching in podspec, parent directories are not allowed, you can find instructions in this document:
https://guides.cocoapods.org/syntax/podspec.html#group_file_patterns

**Comment by jocoders** [comment]
> That is correct. Parent directories are not allowed to be referenced.

But how to do it? If framework installs in root/ios/Pods folder, but it need to use in another directory root/node_modules/react-native-charts-library/ios ? Which way can I use to connect it?

**Comment by xuzhongping** [comment]
@jocoders In general, you should move the podspec file to the same level or parent directory of the framework
