### ISSUE TITLE
Error while adding TikTokOpenSDK iOS SDK

### ISSUE THREAD

**Issue by jigpanchal** [CocoaPods/CocoaPods#11165]
!
![Screen Shot 2022-01-18 at 5 54 54 PM](https://user-images.githubusercontent.com/91688690/150048924-79fde19c-27e6-4653-86ba-547484e42afe.png)

**Comment by paulb777** [comment]
See #9907, https://betterprogramming.pub/ruby-on-apple-silicon-m1-macs-fb159849b2f5, and other issues in this repo related to the ffi issue and CocoaPods on M1 Macs.

**Comment by jigpanchal** [comment]
Was able to resolve it with

Execute below to install the required ffi :
sudo arch -x86_64 gem install ffi

Instead of pod install use :
arch -x86_64 pod install
