### ISSUE TITLE
ERROR:  Error installing cocoapods: zeitwerk requires Ruby version >= 2.5

### ISSUE THREAD

**Issue by CanfieldMobileDev** [CocoaPods/CocoaPods#11176]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

sudo gem install cocoapods

## What did you expect to happen?

CocoaPods will get installed

## What happened instead?

Received error:

ERROR:  Error installing cocoapods:
	zeitwerk requires Ruby version >= 2.5.

## CocoaPods Environment

Running `$ ruby -v` returns `ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]`

Running `$ gem env` returns:

RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.12
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Users/ilya/.rvm/gems/ruby-2.2.1
  - USER INSTALLATION DIRECTORY: /Users/ilya/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: /Users/ilya/.rvm/rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/ilya/.rvm/gems/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: /Users/ilya/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/ilya/.rvm/gems/ruby-2.2.1
     - /Users/ilya/.rvm/gems/ruby-2.2.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/ilya/.rvm/gems/ruby-2.2.1/bin
     - /Users/ilya/.rvm/gems/ruby-2.2.1@global/bin
     - /Users/ilya/.rvm/rubies/ruby-2.2.1/bin
     - /Users/ilya/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /usr/local/git/bin
     - /Users/ilya/Projects/Evaluations/Swiftshield

Running `rvm install ruby-head` returns:

Checking requirements for osx.
Installing requirements for osx.
Updating system............Failed to update Homebrew, follow instructions at

    https://docs.brew.sh/Common-Issues

and make sure `brew update` works before continuing.
.
Error running 'requirements_osx_brew_update_system ruby-head',
please read /_myhomedir_/.rvm/log/1643674860_ruby-head/update_system.log
Requirements installation failed with status: 1.

At this point I stopped, as it's too deep for my knowledge of macOS. Please advise.

## Project that demonstrates the issue

N/A

**Comment by dnkoutso** [comment]
Seems like an environment issue of a gem that requires ruby >= 2.5.
