### ISSUE TITLE
pod issue

### ISSUE THREAD

**Issue by prasannavenkatesh-colan** [CocoaPods/CocoaPods#11181]

**Comment by prasannavenkatesh-colan** [comment]
pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.start_with?('RNFB')
        def pod.build_type;
          Pod::Target::BuildType.static_library
        end
      end
    end
  end
  
 
leads:

[!] An error occurred while processing the pre-install hook of the Podfile.

uninitialized constant Pod::Target::BuildType
Did you mean?  Pod::BuildType

**Comment by paulb777** [comment]
Please fill out the issue template
