### ISSUE TITLE
CocoaPods minimum required version 1.9.0 or greater not installed.

### ISSUE THREAD

**Issue by abddi** [CocoaPods/CocoaPods#11190]
My App is working fine on Android but when try to run it on iOS unfortunately it shows me this error:

```
Launching lib/main.dart on iPhone 13 in debug mode...
lib/main.dart:1
Warning: CocoaPods minimum required version 1.9.0 or greater not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
Error launching application on iPhone 13.
Exited (sigterm)
```
I'm using all new packages versions in my pubspec.yaml file, Also I have installed Cocoapods and tried a lot of solutions like uninstall and re-install with brew and pods but I don't know how this suppose to be upgrading or downgrading to version 1.9.0, I have tried to install/upgrade it as the Cocoapods official web has written in my Terminal through sudo gem install cocoapods but it fails every time I do it please help! :'(

**Comment by xuzhongping** [comment]
@abddi Hi,Please fill out template when filing an issue,to better understand your environmental information.
Looks like a version requirement issue, you should reinstall cocoapods using:
```
gem uninstall cocoapods

# The latest version
gem install cocoapods -v 1.11.2
```

**Comment by abddi** [comment]
I have installed cocoapods through brew install cocoapods,
Now I'm trying to 

> @abddi Hi,Please fill out template when filing an issue,to better understand your environmental information. Looks like a version requirement issue, you should reinstall cocoapods using:
> 
> ```
> gem uninstall cocoapods
> 
> # The latest version
> gem install cocoapods -v 1.11.2
> ```
I've tried it before the only way that I've got to install cocoapods 1.5.2 is from brew install cocoapods but I can't update it to the required version!

Here is what it does returns: 

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.

**Comment by xuzhongping** [comment]
@abddi Sorry, I was wrong about the uninstall process, since you are using homebrew, you should use homebrew to uninstall old cocoapods:
````
brew uninstall cocoapods
````
It looks like your computer is M1 silicon? If yes, I suggest you don't use the system preset ruby (universal version), see the answer here: [https://stackoverflow.com/questions/64901180/how-to-running-cocoapods-on-apple-silicon-m1](https://stackoverflow.com/questions/64901180/how-to-running-cocoapods-on-apple-silicon-m1)

**Comment by abddi** [comment]
> brew uninstall cocoapods

abdallah@MacBook-Pro ~ % brew uninstall cocoapods
Error: Cask 'cocoapods' is not installed.

**Comment by abddi** [comment]
Here is my GEM PATH:

abdallah@MacBook-Pro ~ % gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.6
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [universal.x86_64-darwin20]
  - INSTALLATION DIRECTORY: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/abdallah/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin
  - SPEC CACHE DIRECTORY: /Users/abdallah/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
     - ruby
     - universal-darwin-20
  - GEM PATHS:
     - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
     - /Users/abdallah/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - :concurrent_downloads => 8
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/abdallah/.rbenv/bin
     - /Users/abdallah/.rbenv/shims
     - /Users/abdallah/.rbenv/bin
     - /Users/abdallah/.rbenv/shims
     - /Library/Frameworks/Python.framework/Versions/3.10/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /Users/abdallah/Desktop/development/sdk/flutter/bin
     - /Users/abdallah/.rvm/bin
     - /Users/abdallah/.rbenv/bin
     - /Users/abdallah/Desktop/development/sdk/flutter/bin
     - /Users/abdallah/.rvm/bin
     - /Users/abdallah/.rbenv/bin
abdallah@MacBook-Pro ~ % rvm gemdir
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0

**Comment by abddi** [comment]
I have just solved it by:

1. Uninstall Hebrew completely from Mac.
2. Install rvm.
3. Install latest ruby version from rvm ----> rvm install ruby v3.1.2
4. Install cocoapods ----> sudo gem install cocoapods

**Comment by papajoejo** [comment]
I have tried everything but still issue hasn't bee solved.

**Comment by glennmichaelmejias** [comment]
this works to me
`brew uninstall cocoapods`
`sudo gem install -n /usr/local/bin cocoapods`
