### ISSUE TITLE
"pod install" for binary frameworks works correctly only with ruby 2.6.8

### ISSUE THREAD

**Issue by mkondakov83** [CocoaPods/CocoaPods#11211]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

"pod install" for binary frameworks works properly only with ruby 2.6.8
Any higher or lower version of ruby causes issues: some frameworks are not presented in application bundle; application crashes in runtime with error: Library not loaded: @rpath/TestFramework.framework/TestFramework

Please check attached test project.

Issue description:
We deliver some of our frameworks to our clients as fat binaries. This frameworks are built by script with all dependencies.
Finally we deliver all our frameworks as binaries and all dependencies as binaries.

Client installs our frameworks and all dependencies as binaries from git repo.

This approach was working good until Xcode 13.x
If we build our frameworks with Xcode 13.x we have unexpected issue during "pod install" phase on client's side

All dependency frameworks, installed to original "TestProject" with Podfile (in our case it's Reachability.framework) are installed correctly
But all our own frameworks added to original project "TestProject" (in our case it's TestProject.framework) are not added to app bundle during "pod install"

We have spent a lot of time to discover the reason why it happens and accidentally we have found that "pod install" works fine if active ruby version is set to 2.6.8

## What did you do?

Steps to reproduce:
1. unzip test project
2. cd TestApp
3. pod install
4. sh ./build.sh
5. cd ../ClientTestApp

At this moment check ruby version with "ruby -v" command. If ruby version is other than 2.6.8 (tested with 2.6.3, 2.7.4, 3.1.0) next command will generate incorrect ClientTestApp/Pods/Target Support Files/Pods-ClientTestApp/Pods-ClientTestApp-frameworks.sh script with missed TestFramework

6. pod install
7 open ClientTestApp.xcworkspace and run project

## What did you expect to happen?

Project ClientTestApps runs without issues

## What happened instead?

Project ClientTestApps crashes at runtime with error Library not loaded: @rpath/TestFramework.framework/TestFramework

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin21]
    RubyGems : 3.2.32
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.0 (13A233)
         Git : git version 2.30.1 (Apple Git-130)
Ruby lib dir : /Users/maksym.kondakov/.rubies/ruby-2.7.4/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 5c4c892a88cfed7a7c0a7ef8d2e101d7d4e53bdb

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/maksym.kondakov/.gem/ruby/2.7.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
	installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
end

target 'ClientTestApp' do
  use_frameworks!
  pod 'TestFramework', :path => "../TestApp/build/universal"
end
```

## Project that demonstrates the issue

[RubyIssue.zip](https://github.com/CocoaPods/CocoaPods/files/8098106/RubyIssue.zip)

**Comment by sethfri** [comment]
The error you've included, `Library not loaded: @rpath/TestFramework.framework/TestFramework`, actually seems reminiscent of [this bug fix](https://github.com/CocoaPods/CocoaPods/commit/58cc35dd2134f936079c52af9d7870971c8f763d), not a Ruby version issue. Have you tried pointing your CocoaPods version to the `master` branch and seeing if that resolves your issue? I don't think this has been in an official CocoaPods release yet

**Comment by mkondakov83** [comment]
> The error you've included, `Library not loaded: @rpath/TestFramework.framework/TestFramework`, actually seems reminiscent of [this bug fix](https://github.com/CocoaPods/CocoaPods/commit/58cc35dd2134f936079c52af9d7870971c8f763d), not a Ruby version issue. Have you tried pointing your CocoaPods version to the `master` branch and seeing if that resolves your issue? I don't think this has been in an official CocoaPods release yet

Thanks a lot @sethfri, I have built CocoaPods from master branch and my issue is gone.

Now I can't reproduce this issue even with older version of cocoapods, I tried to reinstall cocoapods, switch ruby versions, clean caches. Maybe you can help me? I want to understand what happens and why it works now even with older configuration.

**Comment by sethfri** [comment]
I'm not sure exactly what caches you're clearing when you say `clean caches`, but a possibility is that unless you're fully deleting the `Pods` directory, CocoaPods may be doing some caching that prevents the target support file in question from being regenerated.

You could try running `pod install --clean-install` on an older version of CocoaPods to see if that's able to reintroduce your issue.

**Comment by dnkoutso** [comment]
This is fixed with https://github.com/CocoaPods/CocoaPods/pull/11217. The original fix was merged to master (1.12) but now we are cherry-picking it down to for 1.11.3.

**Comment by dnkoutso** [comment]
The 1.12 original PR can be found here https://github.com/CocoaPods/CocoaPods/pull/11158

**Comment by mkondakov83** [comment]
@dnkoutso thanks a lot! Maybe you know when 1.11.3 is planned to be released?

**Comment by dnkoutso** [comment]
@mkondakov83 I can do it in the next few days .

**Comment by mkondakov83** [comment]
Hi @dnkoutso, do you still plan to release 1.11.3 ?

**Comment by dnkoutso** [comment]
Heh, tried to do it last night but had some build issues, will resume today.
