### ISSUE TITLE
Is there a script or method to build the IOS project exported by unity into the private library of cocoapods?

### ISSUE THREAD

**Issue by chaosVoid** [CocoaPods/CocoaPods#11218]
I think the Unity and iOS hybrid project needs a script that can build the ios project exported by unity as a CocoaPods private library.
Manually embedding Unity into an iOS project is too easy to miss and very inefficient.

**Comment by dnkoutso** [comment]
At this time no. You would have to build it yourself or seek potential solutions.

This does not appear an enhancement or bug so I am going to close it.
