### ISSUE TITLE
pod install issue - You may have encountered a bug in the Ruby interpreter or extension libraries.

### ISSUE THREAD

**Issue by nurujjamanpollob** [CocoaPods/CocoaPods#11222]
## What I have done?

'cd directory, to where my project is.

Then, I have Run `pod install` it failed, so after that, I have run `pod update` both are failed with a similar message, here is the summary of this error message:

<pre><code>You may have encountered a bug in the Ruby interpreter or extension libraries</code></pre>

## The Error Message is:

I have tried to paste the whole error Log here, but because of body length limit, I can't paste it here, so please visit this link to see this Stacktrace: https://pastebin.com/9VuLTSvd

## Device Information

`M1 Pro CPU with Latest Version of macOS Monterey 12.2.1`

## CocoaPods Environment

Trying `pod env` gives me the similar long error message

## Log Files

For your help diagonstic this issue, here is the backup of all log file zip format, you can download from here: <a href="https://drive.google.com/file/d/1YFW1phmxkpeMlrZnRRDKBVs70gY-SP49/view?usp=sharing">https://drive.google.com/file/d/1YFW1phmxkpeMlrZnRRDKBVs70gY-SP49/view?usp=sharing</a>

**Comment by jonchoi** [comment]
Same here +1

**Comment by nurujjamanpollob** [comment]
> Same here +1

Did you found any workaround. I already get stuck 🥺

**Comment by amorde** [comment]
There's likely an issue with the installation of the `ffi` gem on your machine. You can try running `gem pristine ffi` to re-install it. I don't think there's much other assistance we can provide here

**Comment by endrits079** [comment]
On Mac with M1 chip this worked for me:
sudo arch -x86_64 gem install ffi

Then

arch -x86_64 pod install

comment by SlonGL on https://developer.apple.com/forums/thread/652822

**Comment by nurujjamanpollob** [comment]
Thanks, @endrits079

It's worked fine. Does anyone know when native support for the Apple CPU Platform is come?

**Comment by amorde** [comment]
I use CocoaPods on Apple Silicon every day at work - it works today, and it shouldn't be necessary to force Rosetta.

Re-installing the latest version of the `ffi` gem (without the `arch x86_64`) should work

**Comment by timothysantos** [comment]
I tried the installing the `ffi` with `arch x86_64` and it still didn't work

so I re-installed using `sudo gem pristine ffi` (I had to add sudo bec it says I don't have permission without it)

and bec I encountered this error, `xcrun: error: unable to lookup item 'Path' in SDK 'iphoneos' glog pod`
I did this: `XCode->Preferences->Locations->Command Line Tools and select the xcode` (recommended [here](https://stackoverflow.com/a/66047817/1730753)) —it works now

I'm not sure if my issue was related to this though

**Comment by kakaemma** [comment]
sudo arch -x86_64 gem install ffi
cd ios/App
arch -x86_64 pod repo update
arch -x86_64 pod install
