### ISSUE TITLE
How can i make subdependency available from library

### ISSUE THREAD

**Issue by ozcanzaferayan** [CocoaPods/CocoaPods#11237]
Im currently developing a library for the app. And my library has another dependency like FBAds. Dependency chain is like below: FBAds -> Library -> App

Problem is, App side would like to use FBAds from my Library directly. But when we try to import FBAds from App, it shows an error like "No such module".

How can i make it available FBAds to App.

My case is illustrated like below:

![Untitled-2022-03-08-1339](https://user-images.githubusercontent.com/1326963/157226889-c7a11fce-3eb9-473c-835d-04bfcbf03cf6.png)

**Comment by dnkoutso** [comment]
Going to close as I do not see an action item here for CocoaPods such as a bug or enhancement.
