### ISSUE TITLE
Illformed requirement $IOS_FIREBASE_POD_VERSION

### ISSUE THREAD

**Issue by albermejo** [CocoaPods/CocoaPods#11249]
[capacitor] 
[capacitor] ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[capacitor] 
[capacitor] ### Command
[capacitor] 
[capacitor] ```
[capacitor] /usr/local/bin/pod install
[capacitor] ```
[capacitor] 
[capacitor] ### Report
[capacitor] 
[capacitor] * What did you do? "capacitor sync ios" generate a new version of ios
[capacitor] 
[capacitor] * What did you expect to happen? generate a new version of ios
[capacitor] 
[capacitor] * What happened instead? error
[capacitor] 
[capacitor] 
[capacitor] ### Stack
[capacitor] 
[capacitor] ```
[capacitor]    CocoaPods : 1.11.2
[capacitor]         Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
[capacitor]     RubyGems : 3.0.3.1
[capacitor]         Host : macOS 12.2.1 (21D62)
[capacitor]        Xcode : 13.2.1 (13C100)
[capacitor]          Git : git version 2.32.0 (Apple Git-132)
[capacitor] Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
[capacitor] Repositories : trunk - CDN - https://cdn.cocoapods.org/
[capacitor] ```
[capacitor] 
[capacitor] ### Plugins
[capacitor] 
[capacitor] ```
[capacitor] cocoapods-deintegrate : 1.0.5
[capacitor] cocoapods-plugins     : 1.0.0
[capacitor] cocoapods-search      : 1.0.1
[capacitor] cocoapods-trunk       : 1.6.0
[capacitor] cocoapods-try         : 1.2.0
[capacitor] ```
[capacitor] 
[capacitor] ### Podfile
[capacitor] 
[capacitor] ```ruby
[capacitor] platform :ios, '11.0'
[capacitor] use_frameworks!
[capacitor] 
[capacitor] # workaround to avoid Xcode caching of Pods that requires
[capacitor] # Product -> Clean Build Folder after new Cordova plugins installed
[capacitor] # Requires CocoaPods 1.6 or newer
[capacitor] install! 'cocoapods', :disable_input_output_paths => true
[capacitor] 
[capacitor] def capacitor_pods
[capacitor]   # Automatic Capacitor Pod dependencies, do not delete
[capacitor]   pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
[capacitor]   pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
[capacitor]   pod 'CapacitorCommunityFirebaseAnalytics', :path => '../../node_modules/@capacitor-community/firebase-analytics'
[capacitor]   pod 'CordovaPluginsStatic', :path => '../capacitor-cordova-ios-plugins'
[capacitor]   # Do not delete
[capacitor] end
[capacitor] 
[capacitor] target 'App' do
[capacitor]   capacitor_pods
[capacitor]   # Add your Pods here
[capacitor] end
[capacitor] ```
[capacitor] 
[capacitor] ### Error
[capacitor] 
[capacitor] ```
[capacitor] ArgumentError - Illformed requirement `"$IOS_FIREBASE_POD_VERSION"`
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/requirement.rb:63:in `parse'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/requirement.rb:88:in `map!'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/requirement.rb:88:in `initialize'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/requirement.rb:34:in `new'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/requirement.rb:34:in `create'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/dependency.rb:101:in `initialize'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/consumer.rb:233:in `new'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/consumer.rb:233:in `block in dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/consumer.rb:232:in `each'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/consumer.rb:232:in `map'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification/consumer.rb:232:in `dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:403:in `block in dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:402:in `map'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/specification.rb:402:in `dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/validator.rb:44:in `initialize'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:201:in `new'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:201:in `validator_for_podspec'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:186:in `validate_podspec'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:178:in `store_podspec'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/path_source.rb:17:in `block in fetch'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:993:in `fetch_external_source'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:972:in `block (2 levels) in fetch_external_sources'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:971:in `each'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:971:in `block in fetch_external_sources'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:970:in `fetch_external_sources'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
[capacitor] /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
[capacitor] /usr/local/bin/pod:23:in `load'
[capacitor] /usr/local/bin/pod:23:in `<main>'
[capacitor] ```
[capacitor] 
[capacitor] ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
This is not a valid issue report.
