### ISSUE TITLE
pod repo update Found multiple specifications

### ISSUE THREAD

**Issue by FranZhou** [CocoaPods/CocoaPods#11259]
I am trying to add the following dependency to my Podspec
```
s.dependency 'XXX'
```

`XXX` is my private pod, and it's name conflict to cocoapods public repos.
in `Poodle` I can use this code to resolve conflict,
```
pod 'XXX', :git => 'XXX private git address'
```

but when I want to push my Podspec to remote, something error happens
```
pod repo push remotePrivatePodRepos PodspecName.podspec
```
`
[!] Found multiple specifications for XXX (1.12.5):- /Users/xxx/.cocoapods/repos/cocoapods/Specs/a/7/6/XXX/1.12.5/XXX.podspec.json- /Users/xxx/.cocoapods/repos/trunk/Specs/a/7/6/XXX/1.12.5/XXX.podspec.json
`
how to resolve it?

**Comment by FranZhou** [comment]
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/12538162/158924842-72dfa861-97e9-4f34-8b3b-fac5ed7951cc.png">
it doesn't work. when I run `pod repo push`, the trunk appear again

**Comment by laurentg-nvizzio** [comment]
> you have both trunk and git based master specs repo. Please delete the master one `rm -rf ~/.cocoapods/repos/cocoapods`

How does this happen?
We have never changed anything to our Cocoapods setup, yet ended up with those two repos as well.

What is the mechanism which causes this?
