### ISSUE TITLE
Swift  Bridge push error.

### ISSUE THREAD

**Issue by Corotata** [CocoaPods/CocoaPods#11257]
I create Swift pod, it work well in workspace, when I  push it to my private cocoa pods,it error:

```
pod repo push MySpecs LHSystemMessageModule.podspec --verbose --allow-warnings --use-libraries --use-modular-headers 
```

-> LHSystemMessageModule (1.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | xcodebuild:  note: Build preparation complete
    - NOTE  | [iOS] xcodebuild:  note: Planning
    - NOTE  | [iOS] xcodebuild:  note: Building targets in parallel
    - NOTE  | [iOS] xcodebuild:  CoreStore/Sources/CoreStoreBridge.m:29:9: fatal error: 'CoreStore/CoreStore-Swift.h' file not found

[!] The `LHSystemMessageModule.podspec` specification does not validate.

**Comment by dnkoutso** [comment]
This is not sufficient information for us to diagnose. This looks like a misconfigured podspec perhaps. Please upload a podspec and a sample app demonstrating the issue and I will re-open.
