### ISSUE TITLE
Getting error while pod install

### ISSUE THREAD

**Issue by RNdevAvinash** [CocoaPods/CocoaPods#11268]
[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In Podfile:
    RNFBAnalytics (from `../node_modules/@react-native-firebase/analytics`) was resolved to 14.7.0, which depends on
      Firebase/Analytics (= 8.14.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Analytics (= 8.14.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

firebase  versions 

    "@react-native-firebase/analytics": "^14.7.0",
    "@react-native-firebase/app": "^14.7.0",
    "@react-native-firebase/crashlytics": "^14.7.0",
    "@react-native-firebase/messaging": "^14.7.0",

**Comment by paulb777** [comment]
Try `pod repo update`. This is not a CocoaPods issue.
