### ISSUE TITLE
Frameworks with conflicting names: webrtc.xcframework

### ISSUE THREAD

**Issue by marcoberetta96** [CocoaPods/CocoaPods#11278]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
When trying to run `pod install` when using both `JitsiMeetSDK` and `WebRTC-SDK` the following error is triggered.
I need both the pods in my project and I can't find a way to get out of this issue.

## What happened?
`[!] The 'Pods-Runner' target has frameworks with conflicting names: webrtc.xcframework.`

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.0.1 (21A559)
       Xcode : 13.2.1 (13C100)
         Git : git version 2.34.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '12.0'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  use_frameworks!
  pod 'JitsiMeetSDK', '~> 5.0.0'
  pod 'WebRTC-SDK', '~> 97.4692.02'
end

install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
        'PERMISSION_MICROPHONE=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_NOTIFICATIONS=1',
        'PERMISSION_MEDIA_LIBRARY=1',
      ]
    end
  end
end

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignalXCFramework', '>= 3.4.3', '< 4.0'
end
```

**Comment by marcoberetta96** [comment]
Here the two podspecs:
- https://github.com/CocoaPods/Specs/blob/master/Specs/c/0/0/JitsiMeetSDK/5.0.2/JitsiMeetSDK.podspec.json
- https://github.com/CocoaPods/Specs/blob/master/Specs/2/c/6/GoogleWebRTC/1.1.31999/GoogleWebRTC.podspec.json

They both have `WebRTC.framework` in the `vendored_frameworks`.
How can I solve this issue?

**Comment by dnkoutso** [comment]
You cannot at this time. You have to write a pre install hook perhaps or ask the authors to remove it. It seems an issue with JitsiMeetSDK most likely if Google is the original author.

**Comment by dnkoutso** [comment]
Sorry I do not have one handy or know from the top of my head. I know there might have been other issues to search around for doing this.

You'd have to tinker through `pod_target` and what `installer` gives you in the `pre_install` hook etc.

**Comment by dnkoutso** [comment]
Going to close as for right now there is no actionable thing to do. I recommend reaching to the author and tell them to use a dependency instead of vending that framework for you, given that Google already vends it.

**Comment by esraaabdelmonem1994** [comment]
@marcoberetta96 I have the same issue, so are you found any answer? I'm using jitsimeetsdk and iosrtc and both of them have webrtc.xcframework

**Comment by marcoberetta96** [comment]
not solved

**Comment by leonardogbr** [comment]
I'm having the same problem with `jitsi_meet_flutter_sdk` and `sip_ua`. Any updates?

**Comment by Ozaoujal** [comment]
I have this problem too

**Comment by jimmy-sqe** [comment]
Me too

**Comment by incubo4u** [comment]
and me too 🥲
