### ISSUE TITLE
can't install pods

### ISSUE THREAD

**Issue by doofygoof** [CocoaPods/CocoaPods#11281]
<img width="1512" alt="Screenshot 2022-04-01 at 08 49 03" src="https://user-images.githubusercontent.com/102763459/161210508-dc352c7f-bfc4-4b28-aed0-97389489f53a.png">
<img width="1512" alt="Screenshot 2022-04-01 at 08 49 07" src="https://user-images.githubusercontent.com/102763459/161210539-9827c0d0-c80c-4526-91e2-97732c43a49f.png">

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by jesuasir007** [comment]
yes ,same error to me

**Comment by dnkoutso** [comment]
this is not a valid issue report.
