### ISSUE TITLE
Pod keeps manual link

### ISSUE THREAD

**Issue by philippbb** [CocoaPods/CocoaPods#11298]
Hi,

I accidentally did a manual link of a react native  pod after I changed the podfile to the new autolink system. 

Now i removed the manual link in the podfile and pod install works fine, but whenever  I do yarn run ios I still get the message that the pod is manual linked.

I tried unlink, clean cache, removed podfolder, removed node module and redo pod install but the message persists.

Any advice? Thank u for an answer.

**Comment by dnkoutso** [comment]
Sorry this is not a complete issue report. Please file an issue with ReactNative instead.
