### ISSUE TITLE
"Duplicate interface definition for class " in CocoaPods

### ISSUE THREAD

**Issue by Osama-Fawzi** [CocoaPods/CocoaPods#11295]
I am trying to install two similar pods (nous_sonic is the original while nous_sonicV2 is a fork with some modifications, podspec has been updated accordingly).

I set two different independent targets in a new test project, and installed pods as follow:

Podfile:

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def nousSonic
   pod 'nous_sonic', :path => '../NousSonicLibrary'
  
end

def nousSonicV2
  pod 'nous_sonicV2', :path => '../NousSonicLibraryV2.0'
  
end

target 'TestTargets' do
  use_frameworks!
  nousSonic
end

target 'TestTargets2' do
  use_frameworks!
  nousSonicV2
end
PodLock:

PODS:
  - nous_sonic (1.12.2):
    - NSLogger (~> 1.9.0)
    - ReactiveObjC (~> 3.1.0)
  - nous_sonicV2 (1.12.3):
    - NSLogger (~> 1.9.0)
    - ReactiveObjC (~> 3.1.0)
  - NSLogger (1.9.7):
    - NSLogger/ObjC (= 1.9.7)
  - NSLogger/ObjC (1.9.7)
  - ReactiveObjC (3.1.1)

DEPENDENCIES:
  - nous_sonic (from `../NousSonicLibrary`)
  - nous_sonicV2 (from `../NousSonicLibraryV2.0`)

SPEC REPOS:
  trunk:
    - NSLogger
    - ReactiveObjC

EXTERNAL SOURCES:
  nous_sonic:
    :path: "../NousSonicLibrary"
  nous_sonicV2:
    :path: "../NousSonicLibraryV2.0"

SPEC CHECKSUMS:
  nous_sonic: 8e09553055fa6b45875c58d7318688177c49b0aa
  nous_sonicV2: 8c90af2ccc2d144ccfaf204176260ae820dfa4f4
  NSLogger: cf3013a4fba189f631f07e6c3d5b8ce2b209654b
  ReactiveObjC: 011caa393aa0383245f2dcf9bf02e86b80b36040

PODFILE CHECKSUM: 985faad41adb0b50318eb007ab7666ee8eef5570

COCOAPODS: 1.10.1
here are the outcomes:

1- try to build 'TestTargets', build successfully.

2- try to build 'TestTargets2', build failed with error 'Duplicate interface definition for class ...' and shows duplications from both pods.

3- remove 'nous_sonic' from 'TestTargets', and rebuild 'TestTargets2' -> build successfully as expected with new modifications.

Note, the project is new there is nothing implemented not even an imports!

Why there is conflicts specially for 'nous_sonicV2'?

or, if you can provide a script to force exclude 'nous_sonic' in preprocessing for 'TestTargets2', would be an alternative workaround.

**Comment by TRIMER** [comment]
Hello. I have similar issue. How did you solve it?

**Comment by TRIMER** [comment]
@Osama-Fawzi Hello. I have similar issue. How did you solve it?
