### ISSUE TITLE
Lack of ability to Add Run Script Build Phase for integrated projects

### ISSUE THREAD

**Issue by dismory** [CocoaPods/CocoaPods#1129]
My company have a self-build framework for collecting crashes. Beside embedding the framework, it is also necessary to add a **Run Script Build Phase** for uploading dYSM files to our servers after each build. AFAK, CocoaPods is not able to manipulate integrated projects currently.

**Comment by siuying** [comment]
I almost get it working with ``prepare_command`` and xcodeproj. Unfortunately prepare_command is performed before the Pods project is created, I cannot add the build phase to Pods project.
