### ISSUE TITLE
How to set BUILD_ACTIVE_ARCHITECTURE_ONLY of a pod in Podfile

### ISSUE THREAD

**Issue by mdddj** [CocoaPods/CocoaPods#11304]
Hello, the above error will appear every time I pack, and then I have to set Yes, may I ask if there is a way to set this property at one time, instead of having to change it every time
![790o1ipdzg](https://user-images.githubusercontent.com/29020213/163341341-ef474157-3552-4703-9cae-9326a56abf74.png)

![CqpC5XMVgf](https://user-images.githubusercontent.com/29020213/163341412-78e97fd5-0edb-4008-a8e9-760f52c3b28e.png)

<img width="785" alt="image" src="https://user-images.githubusercontent.com/29020213/163341668-25c5b38f-45b8-4948-b8ad-f2fa2cd5d816.png">

I set it like this but it doesn't work, how can I set that property to yes

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
