### ISSUE TITLE
Pod outdated on Mac Studio M1 Max

### ISSUE THREAD

**Issue by ArtfulDodger40** [CocoaPods/CocoaPods#11339]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run pod outdated (pod update didn't work either)
## What did you expect to happen?

Tell me what updates would happen

## What happened instead?

Got an error
## CocoaPods Environment

objc[10938]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1f0c61eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb84f8). One of the two will be used. Which one is undefined.
objc[10938]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1f0c61f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb8548). One of the two will be used. Which one is undefined.
objc[10938]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1f0c61f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb8598). One of the two will be used. Which one is undefined.
objc[10938]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1f0c61fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb85e8). One of the two will be used. Which one is undefined.
objc[10938]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1f0c61ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb8638). One of the two will be used. Which one is undefined.
objc[10938]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1f0c62040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103eb8688). One of the two will be used. Which one is undefined.
andrewkeays@Mac-Studio ~ %

**Comment by dnkoutso** [comment]
I am not sure this is related to `pod outdated` tbh. This looks like a system issue? Do other commands like pod install etc work?

**Comment by ArtfulDodger40** [comment]
Tried pod update. Haven’t tried pod install yet, terminal is choking on a git push! This is a new computer - Mac Studio with M1 Max, and Rosetta 2, so I wondered if the issue was something to do with that. Didn’t have this on my Mack Pro (which this computer was set up from. Having Github problems as well, but that was happening pre this new system,.

Regards

Andrew Keays
Ph: 0419 556 969
***@***.***

**Comment by dnkoutso** [comment]
Going to close for now and we can re-open if we think this is a cocoapods issue and not system env issue.

**Comment by ArtfulDodger40** [comment]
Yes, pod install worked. Pod outdated still does not. I guess its a moot point now...

Regards

Andrew Keays
Ph: 0419 556 969
***@***.***
