### ISSUE TITLE
Remove podspec dependency and add it via Podfile.

### ISSUE THREAD

**Issue by JV17** [CocoaPods/CocoaPods#11340]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Have another pod inside our podspec as a dependency.

Run `pod install`
Build & Run `.xcworkspace`

## What did you expect to happen?

We would like to be able to remove dependencies inside podspec file and consume them via Podfile, instead of podspec.

- Install all pod dependencies correctly.
- Build & Run the project successfully.

## What happened instead?

`No such module {ModuleName/Pod Dependency Name}`

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin20]
    RubyGems : 3.1.2
        Host : macOS 12.3.1 (21E258)
       Xcode : 13.3 (13E113)
         Git : git version 2.32.0 (Apple Git-132)
Ruby lib dir : /Users/user/.rvm/rubies/ruby-2.7.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ df542639bd284f992f3de81cff2db3100bddbeba

               Internal repos....

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/user/.rvm/gems/ruby-2.7.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-pod-linkage : 0.0.1
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
slather               : 2.7.1
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by JV17** [comment]
@orta I agree, I did opened a thread [here](https://stackoverflow.com/questions/72019809/removing-pod-dependency-from-podspec-and-add-it-from-elsewhere), but haven't received any response. If anyone of you could comment on this thread, I will really appreciate it. Thank you!
