### ISSUE TITLE
Mac M1 - Pod fails if opened from project RESOLVED

### ISSUE THREAD

**Issue by SportApps** [CocoaPods/CocoaPods#11369]
@orta, apparently, my version of git is installed in `/Users/forcebru/bin/git`, not in `/usr/local/bin`, where `brew`ed files seem to go, so it just updated the `brew`ed version of git (for whatever reason I had two).

_Originally posted by @ForceBru in https://github.com/CocoaPods/CocoaPods/issues/8661#issuecomment-478361816_

Hi guys!

I can not make the pod command to work if I open it out of the IDE Terminal in the project.

```
timknogel@Tims-MacBook-Pro multiculturalapp % pod
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)
        from /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:140:in `verify_minimum_git_version!'
        from /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:49:in `run'
        from /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
        from /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
        from /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'
```

Where do I have pod installed?
```
timknogel@Tims-MacBook-Pro multiculturalapp % which pod
/opt/homebrew/bin/pod

```

Where do I have GIT installed (Home-brew)?
```
timknogel@Tims-MacBook-Pro multiculturalapp % which git
/usr/local/bin/git
```
My Git version:
```
timknogel@Tims-MacBook-Pro multiculturalapp % git version
git version 2.36.0
```

Can somebody help please?

**Comment by SportApps** [comment]
I have the impression now that it is project related - when I install cocoa pods in a newly created project - everything works fine.... Any ideas why that could be?
I need this old project because it's an important App.

**Comment by SportApps** [comment]
Can anybody help?

**Comment by orta** [comment]
As you  @'d me in the OP, I'd recommend you look at the code mention in the error: 

> /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:128:in `git_version': Failed to extract git version from `git --version` ("") (RuntimeError)

And then make a PR to CocoaPods which fixes your case, as I mentioned to the person who first encountered this bug in 2019. CocoaPods runs on volunteers spare time, and for a lot of us that is very sparse nowadays

**Comment by SportApps** [comment]
Ok! I got it resolved. It actually had nothing to do with Git I think. I just created a new project from scratch, configured it again and copied in the old LIB folder... Then it worked. So it must have been somehow project related.
