### ISSUE TITLE
[pod_install] removes flutter module paths

### ISSUE THREAD

**Issue by grisvladko** [CocoaPods/CocoaPods#11378]
Hello,
i have addressed an issue to flutter team in order to understand a certain behavior:
when i install cocoapods using: sudo gem install cocoapods : 
i run pod install on my project which includes a flutter module in it, and i get this : 

![WhatsApp Image 2022-05-19 at 12 03 23 PM](https://user-images.githubusercontent.com/59421266/169763025-e43731b6-05a7-43bd-b84a-808ff66a4440.jpeg)

meaning that pod install command removes the paths to my flutter module.

But ! and it is very interesting : when i remove pods and install them via brew install cocoapods everything works fine! the pod install command on my iOS project does not remove tha path to flutter module and it works.

**Comment by dnkoutso** [comment]
We do not accept Flutter related issues. Please only file an issue without flutter demonstrating an issue with cocoapods instead.
