### ISSUE TITLE
How to add private source for the spec dependency in podspec

### ISSUE THREAD

**Issue by LongXiangGuo** [CocoaPods/CocoaPods#11374]
I'am want to add a private pod in the podSpec, It looks like this below.

```
// my_custom.podspec file
  s.dependency 'OneKit', :source => "https://github.com/volcengine/volcengine-specs.git"

[!] Failed to load 'volcano_apm_plugin' podspec: 
[!] Invalid `volcano_apm_plugin.podspec` file: [!] Unsupported version requirements. [{:source=>"https://github.com/volcengine/volcengine-specs.git"}] is not valid..
```

However, the syntax is not supported, I just move it from the host project `Profile` (`Pod 'OneKit', :source => "https://github.com/volcengine/volcengine-specs.git"`).  I have reviewed the relevant [cocoapods documents](https://guides.cocoapods.org/syntax/podspec.html) Does any one known cocoaPods have any other syntax to support it?

**Comment by LongXiangGuo** [comment]
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20] 
Pod version 1.11.2

**Comment by paulb777** [comment]
Use the `--sources` option to `pod` commands. Details with `--help`

**Comment by LongXiangGuo** [comment]
Thanks @paulb777, I have add the sources to  the host target Podfile fixed it.
