### ISSUE TITLE
pod install issue

### ISSUE THREAD

**Issue by fs810321** [CocoaPods/CocoaPods#11388]
<img width="1440" alt="Screenshot 2022-05-29 at 4 53 14 PM" src="https://user-images.githubusercontent.com/106473259/170865531-83a0ae2f-38d1-4718-a7f6-3097c7e7058f.png">
<img width="1440" alt="Screenshot 2022-05-29 at 4 53 28 PM" src="https://user-images.githubusercontent.com/106473259/170865537-178846e9-fc18-435a-b85b-d286672d682d.png">
<img width="1440" alt="Screenshot 2022-05-29 at 4 53 32 PM" src="https://user-images.githubusercontent.com/106473259/170865541-222b8413-94cb-4a65-ae12-cbe031bf55af.png">

**Comment by dnkoutso** [comment]
Please see other `ffi` gem related installation issues.
