### ISSUE TITLE
Error with flutter_stripe: ^3.0.2 for ios 

### ISSUE THREAD

**Issue by NavneetTechlene** [CocoaPods/CocoaPods#11394]
!] CocoaPods could not find compatible versions for pod "Stripe":
  In Podfile:
    stripe_ios (from `.symlinks/plugins/stripe_ios/ios`) was resolved to 0.0.1, which depends on
      Stripe (~> 22.3.0)

None of your spec sources contain a spec satisfying the dependency: `Stripe (~> 22.3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
 

 [My Code](https://github.com/NavneetTechlene/stripeExample`)(`https://github.com/NavneetTechlene/stripeExample`)

 1.) using
Xcode Version 13.3.1 (13E500a)
flutter_stripe: ^3.0.2
Flutter 3.0.1• channel stable • https://github.com/flutter/flutter.git

2.) Build for Android 
3.) arch -x86_64 pod install  with flutter_stripe: ^3.0.2 above error and with # flutter_stripe: ^3.0.2  in pubspec.yaml i can make ios ipa

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
