### ISSUE TITLE
CocoaPods could not find compatible versions for pod "YandexMapsMobile":

### ISSUE THREAD

**Issue by Abdullajon711** [CocoaPods/CocoaPods#11409]
After run pod install  this error showed
                 
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "YandexMapsMobile":
  In Podfile:
    yandex_mapkit (from `.symlinks/plugins/yandex_mapkit/ios`) was resolved to 0.0.1, which depends on
      YandexMapsMobile (= 4.1.0-full)

None of your spec sources contain a spec satisfying the dependency: `YandexMapsMobile (= 4.1.0-full)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by NigmetovTimur** [comment]
+
