### ISSUE TITLE
Pod init failed on M1 Mac macOS Ventura 13.0 beta1

### ISSUE THREAD

**Issue by haoboxuxu** [CocoaPods/CocoaPods#11406]
### Command

```
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
    RubyGems : 3.3.11
        Host : macOS 13.0 (22A5266r)
       Xcode : 14.0 (14A5228q)
         Git : git version 2.32.1 (Apple Git-133)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.1.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version (56).
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:228:in `initialize_from_file'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:113:in `open'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/init.rb:41:in `validate!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'
```

**Comment by l-kovachev** [comment]
I guess this will be fixed shortly, but as a workaround I have created the project with Xcode 13.2.1 (13C100), then 'pod init'.
Added some dependencies to the Podfile then 'pod install'.
Finally opened the .xcworkspace with Xcode 14.0 beta (14A5228q).

Maybe creating the project with some of the latest stable versions of Xcode will work too.

**Comment by horidream** [comment]
Edit `./YourProject.xcodeproj/project.pbxproj` file and change the `objectVersion` value to `55` will work as a workaround
```
// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 55;
	objects = {
...
```

**Comment by timsonner** [comment]
@horidream 's method worked for me, initialized without a hitch. EZ.

**Comment by rmbrown410** [comment]
Restarting my machine worked for me. Tried a lot of things before doing a clean restart and nothing worked. Just re-installed via homebrew and restarted.

**Comment by Homayuun** [comment]
> Edit `./YourProject.xcodeproj/project.pbxproj` file and change the `objectVersion` value to `55` will work as a workaround
> 
> ```
> // !$*UTF8*$!
> {
> 	archiveVersion = 1;
> 	classes = {
> 	};
> 	objectVersion = 55;
> 	objects = {
> ...
> ```

Dude I've went through awful lot of ways from modifying zshrc to brew install cocoapods and ruby and so on... 
YOU'RE A GENIUS !!! THANK YOU THANK YOU THANK YOU!!!
**FOR ANYONE WHO'S Reading**
 just as @horidream says:
 - go to your xcodeproj
 **- right click/ show package contents/ project.pbxproj**
 - change object version from 56 to 55

**Comment by dnkoutso** [comment]
Please also use ‘gem update xcodeproj’
