### ISSUE TITLE
missing gem when use cocoapods plugin 

### ISSUE THREAD

**Issue by ARIEnergy** [CocoaPods/CocoaPods#11413]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I use cocoapods plugin - cocoapods-merge-pod in my project and then when I run the command line as below, it always showed the error 

missing the gem even though I had installed the gems in my project successfully 
ℹ Please replace these two lines with what you did.  
bundle exec pod install 

## What did you expect to happen?
I truly hope it installed successfully in my project

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?
It showed missing gems , but in act I had installed  it 

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

The latest cocoapods  I used in my project 

## Project that demonstrates the issue

when use cocoapods plugin in my podfile , it cannot be successful.

**Comment by ARIEnergy** [comment]
@segiddins  Any tips to fix the issue???

**Comment by orta** [comment]
You probably want to make sure its in your Gemfile if you are using `bundle exec`

**Comment by ARIEnergy** [comment]
I Used it , I am sure, but it failed

发件人：Orta Therox ***@***.***>
发送日期：2022-06-20 17:49:09
收件人：CocoaPods/CocoaPods ***@***.***>
抄送人：ARIEnergy ***@***.***>,Author ***@***.***>
主题：Re: [CocoaPods/CocoaPods] missing gem when use cocoapods plugin (Issue #11413)

You probably want to make sure its in your Gemfile if you are using bundle exec
