### ISSUE TITLE
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FBCxxFollyDynamicConvert":

### ISSUE THREAD

**Issue by mmalvicini** [CocoaPods/CocoaPods#11443]
# Report
Create new App react-native on Mac with M1

## What did you do?
npx react-native init MyApp

ℹ Please replace these two lines with what you did.  
error Error: Failed to update CocoaPods repositories for iOS project.

## What did you expect to happen?
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FBCxxFollyDynamicConvert":

**Comment by dnkoutso** [comment]
Unfortunately this is not a complete issue report and we are unable to assist. Please provide more information and a reproducible sample.
