### ISSUE TITLE
curl: (35) error:02FFF036:system library:func(4095):Connection reset by peer

### ISSUE THREAD

**Issue by WeiXiangL** [CocoaPods/CocoaPods#11468]
[!] Error installing UMAPM
[!] /usr/bin/curl -f -L -o /var/folders/hn/_jsk1gk96yd3g_m5z8kc22lm0000gn/T/d20220718-24757-17a6yrh/file.zip https://umplus-sdk-download.oss-cn-shanghai.aliyuncs.com/iOS/UMAPM/UMAPM_1.7.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) error:02FFF036:system library:func(4095):Connection reset by peer

**Comment by orta** [comment]
This looks like an issue downloading via curl, and not a CocoaPods issue - I'd recommend looking into that
