### ISSUE TITLE
Pod install bug in M1 Pro 0x000000010239c000

### ISSUE THREAD

**Issue by AndreyITicha** [CocoaPods/CocoaPods#11476]
Hi, guys!

I have a problem when i making `pod install`.
I'm programming on MacBook Pro 2021 with M1 Pro.
I have a program on SwiftUI and I want to add a FireBase. 
The best way is CocoaPods. First I do this command: `sudo gem install cocoapods`, after it I open my Xcode folder and made this command: `pod init` and then I do that command: `pod install`. And here I have a trouble. 
At first line I have a this bug: `/Library/Ruby/Gems/2\.6\.0/gems/ffi-1\.15\.5/lib/ffi/library.rb:275: [BUG] Bus Error at 0x000000010239c000 ruby 2\.6\.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]`.
I tried to open terminal with Rossetta and after this to install ffi, but it only got worse... So I open terminal without Rossetta, uninstall ffi and reinstall CocoaPods 😅
Here the Podfile:
`# Uncomment the next line to define a global platform for your project`
`# platform :ios, '9.0'`
`target 'SwiftTasks' do`
  `# Comment the next line if you don't want to use dynamic frameworks`
  `use_frameworks!`

  `# Pods for SwiftTasks`
	`pod 'FirebaseFirestore'`
`end`

Log when I do `pod install` will be in [.docx file](https://github.com/CocoaPods/CocoaPods/files/9166685/Bug.log.docx)

OS: MacOS Monterey

If someone know how to fix, please help 🙏🙏🙏

**Comment by dnkoutso** [comment]
Please see other ffi gem installation issues.
