### ISSUE TITLE
Pod install CDN: trunk URL couldn't be downloaded

### ISSUE THREAD

**Issue by Adithyan2295** [CocoaPods/CocoaPods#11478]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?
The following error was shown - 
[!] CDN: trunk Repo update failed - 56 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.2.0/Firebase.podspec.json Response: Timeout was reached

## CocoaPods Environment
![Screenshot 2022-07-22 at 5 15 33 PM](https://user-images.githubusercontent.com/94591962/180432738-ed019c74-8b5e-4b00-bd50-f4df4817f258.png)

**Comment by dnkoutso** [comment]
Seems like a network timeout issue. You may also switch to use git based master specs repo.

**Comment by Adithyan2295** [comment]
> Seems like a network timeout issue. You may also switch to use git based master specs repo.

Is there any other permanent solution for this?
