### ISSUE TITLE
Pod only install after second time

### ISSUE THREAD

**Issue by paulocoutinhox** [CocoaPods/CocoaPods#11509]
Hi,

My pod only install after second time.

In the first time, the directory is empty.

I made a project to show this:
https://github.com/paulocoutinhox/google-cast-bug

Thanks.

**Comment by paulocoutinhox** [comment]
The full log is here:
https://github.com/paulocoutinhox/google-cast-bug/runs/7962291542?check_suite_focus=true

The is "First attempt" and "Second attempt" showing the difference between the two "pod install" calls.

**Comment by xuzhongping** [comment]
Hi, using the git option to install the pod, I thought the repository should contain all the files needed and not point to another source; but it did work on the second install, and I'll track down what caused the problem.

**Comment by paulocoutinhox** [comment]
I solve it:
https://github.com/ubook-editora/ub-google-cast-sdk-no-bluetooth/blob/main/ub-google-cast-sdk-no-bluetooth.podspec

And:
https://github.com/paulocoutinhox/google-cast-bug/blob/main/Podfile
