### ISSUE TITLE
Error occurred when executing pod init

### ISSUE THREAD

**Issue by mhmtkrgz** [CocoaPods/CocoaPods#11536]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod init`

## What did you expect to happen?

Create podfile.

## What happened instead?

```
RuntimeError - [Xcodeproj] Unknown object version (56).
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:228:in `initialize_from_file'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/xcodeproj-1.21.0/lib/xcodeproj/project.rb:113:in `open'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command/init.rb:41:in `validate!'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/claide-1.1.0/lib/claide/command.rb:333:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod:25:in `<main>'
```

## CocoaPods Environment

```
   CocoaPods : 1.11.3
        Ruby : ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
    RubyGems : 3.3.11
        Host : macOS 12.5.1 (21G83)
       Xcode : 14.0 (14A309)
         Git : git version 2.37.0 (Apple Git-136)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.1.2_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.11.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

**Comment by thanhnam1042** [comment]
brew uninstall cocoapods and reinstall cocoapods with sudo gem install cocoapods

**Comment by saqib-saud** [comment]
> Xcode : 14.0 (14A309)

This issue exists in new projects created using Xcode 14.0

**Comment by SergejLogis** [comment]
> "brew uninstall cocoapods" and reinstall cocoapods with "sudo gem install cocoapods"

This fixed it for me! Thanks 🙇‍♂️

**Comment by saqib-saud** [comment]
<img width="264" alt="Screen Shot 2022-09-15 at 10 27 28 am" src="https://user-images.githubusercontent.com/400207/190285758-c9a4b9f5-9cc4-4882-aff1-d90a651da491.png">

reinstalling cocoapods did not fix the issue but downgrading project format did fix this issue.

**Comment by ttaashutoshtt** [comment]
> <img alt="Screen Shot 2022-09-15 at 10 27 28 am" width="264" src="https://user-images.githubusercontent.com/400207/190285758-c9a4b9f5-9cc4-4882-aff1-d90a651da491.png">
> 
> reinstalling cocoapods did not fix the issue but downgrading project format did fix this issue.

Thank you so much, this fixed the issue for me.

**Comment by toufique-imam** [comment]
```
gem update xcodeproj
sudo gem update xcodeproj
brew uninstall cocoapods
sudo gem install cocoapods
```
using these commands together solved my issue

**Comment by tungdangplus** [comment]
> 

This fixed for me. Even the project I created by Xcode 14

**Comment by tungdangplus** [comment]
> 

This fixed for project created from Xcode 14

**Comment by tungdangplus** [comment]
Thank to thanhnam1042: "brew uninstall cocoapods" and reinstall cocoapods with "sudo gem install cocoapods"
This fixed for my project created by Xcode 14

**Comment by yaozhang-this** [comment]
After `brew uninstall cocoapods` I am getting a different error
```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
```
This seems to be using the system gems shipped with macOS that is using x86 architecture

The pod command should use the gem compatible with ARM architecture.

**Comment by mhasan341** [comment]
> "brew uninstall cocoapods" and reinstall cocoapods with "sudo gem install cocoapods"

Solved! 🥳 Thanks much!

**Comment by samplegitrithub** [comment]
1. sudo arch -x86_64 gem install ffi
2. arch -x86_64 pod install
this two can solve your issue

**Comment by SBarpit** [comment]
> ```
> gem update xcodeproj
> sudo gem update xcodeproj
> brew uninstall cocoapods
> sudo gem install cocoapods
> ```
> 
> using these commands together solved my issue

I'm using Xcode 14.0, and this is working for me. Thanks @toufique-imam

**Comment by phongle6893** [comment]
> <img alt="Screen Shot 2022-09-15 at 10 27 28 am" width="264" src="https://user-images.githubusercontent.com/400207/190285758-c9a4b9f5-9cc4-4882-aff1-d90a651da491.png">
> 
> reinstalling cocoapods did not fix the issue but downgrading project format did fix this issue.

Thank you, It work for me 👍

**Comment by patratacus** [comment]
Below works for me (based on all the other answers) after I did brew install and pod init doesn't work on Xcode 14 project I have.

```
sudo brew uninstall cocoapods
sudo gem install cocoapods
sudo gem update xcodeproj
```
Setting Project Format to Xcode 13.0-compatible also works, but I'd rather have it working with Xcode 14

**Comment by sourav-singh-rawat** [comment]
> "brew uninstall cocoapods" and reinstall cocoapods with "sudo gem install cocoapods"
This worked for me thanks!

**Comment by jubran** [comment]
> > <img alt="Screen Shot 2022-09-15 at 10 27 28 am" width="264" src="https://user-images.githubusercontent.com/400207/190285758-c9a4b9f5-9cc4-4882-aff1-d90a651da491.png">
> > reinstalling cocoapods did not fix the issue but downgrading project format did fix this issue.
> 
> Thank you, It works for me 👍


working with me 
thank u

**Comment by heistings** [comment]
> 

Thanks very much, it works for me.
