### ISSUE TITLE
Error when using pod spec lint on a machine with attached, active eGPU

### ISSUE THREAD

**Issue by vincentneo** [CocoaPods/CocoaPods#11530]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod spec lint`

## What did you expect to happen?
Successfully linting with result

## What happened instead?

Issue as mentioned in #10213, but with latest CocoaPods, etc

### Observation:
```
    - ERROR | [iOS] unknown: Encountered an unknown error (767: unexpected token at '2022-09-07 01:03:20.100 simctl[18424:463653] apply_selection_policy_once: prefer use of removable GPUs (via com.apple.CoreSimulator.simctl:GPUSelectionPolicy->preferRemovable)
') during validation.
```

```
xcrun simctl list
2022-09-07 01:09:30.733 simctl[18468:467561] apply_selection_policy_once: prefer use of removable GPUs (via com.apple.CoreSimulator.simctl:GPUSelectionPolicy->preferRemovable)
== Device Types ==
```
Observed to be basically consistent with #10213.

`fourflusher` version is still 2.3.1 when installed via `gem install fourflusher`, after seeing above issue. Did not resolve. Assume that this gem isn't required? Or is there a need to somehow install the master branch version of `fourflusher`?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.4 (21F79)
       Xcode : 13.4.1 (13F100)
         Git : git version 2.32.1 (Apple Git-133)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

**Comment by vincentneo** [comment]
Happens with `pod trunk push x.podspec` too.

**Comment by vincentneo** [comment]
Seems like this configuration fixes it: 

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.5.1 (21G83)
       Xcode : 14.1 (14B47)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

Therefore, I am closing this.

**Comment by vanshg** [comment]
I was getting a similar error (but mine was saying _avoid_ Removable not _prefer_ Removable

` apply_selection_policy_once: avoid use of removable GPUs (via com.apple.CoreSimulator.simctl:GPUSelectionPolicy->avoidRemovable)`

This seems to stem from a bug (?) in `xcrun` itself. Running the command in my IDE's built-in terminal is what caused the error.

What fixed it for me was to use the native macOS Terminal application
