### ISSUE TITLE
Lock files in Pods folder

### ISSUE THREAD

**Issue by AliSoftware** [CocoaPods/CocoaPods#1154]
Wouldn't it be possible to **lock every file in the Pods folder** (using `SetFile -a L [thefile]`) to **prevent accidental editing of sources of the libraries imported by CocoaPods** ?

Some coworkers are sometimes tempted to modify the source code of a pod (for example if they found a bug in it) directly in the Pods.xcodeproj project, instead of editing the source of the original pod (create a branch on the pod repository, file a pull request, etc). This happens most of the time unintentionally, simply because they didn't realize this source code was one of a pod's (navigating in Xcode using Cmd-clics may lead you far without realizing where you land…)

Locking all files in the Pods/ directory would prevent such mistakes, by making Xcode warn you before you try and edit a source file you should'nt.

---

> Note: One problem with that is that the "Locked" flag (that you can set/get using SetFIle/GetFileInfo) is attached to the HFS+ filesystem if I'm not mistaken, but if I commit the Pods/ folder on my repo (because my coworkers and my Jenkins-CI should not be forced to install cocoapods on their own machine and run `pod update` themselves after each `git pull`) I'm not sure such Locked flag will stick. If that's not the case, any alternative solution is welcome to overcome this issue and avoid those mistakes.

**Comment by segiddins** [comment]
I say we should just close this. The user can edit things under `Pods` at their own peril.

**Comment by nickmshelley** [comment]
@segiddins What a great programming philosophy! :)

**Comment by segiddins** [comment]
@nickmshelley don't know if you're being sarcastic or not, but I don't think it's worth spending time on this sort of thing .

**Comment by nickmshelley** [comment]
@segiddins I was being sarcastic, but I completely agree that a solution seems too complicated and risky for the size of the problem. I just thought the way you said it could be slightly humorous if taken out of context. I wasn't trying to be offensive or trolling or anything. Sorry if it was inappropriate.

**Comment by nickmshelley** [comment]
In case any more anecdotal information is helpful to anyone, all of my coworkers and I have run into this same situation at some point. Eventually we experience enough pain that we are more careful, but when new people come on they usually run into it as well. It's mainly (only) a problem with pods that we have authored, so the code seems like it's just part of the app. Maybe that's not a common use case.

**Comment by AliSoftware** [comment]
@nickmshelley we are in the same situation (often happen on private pods we have authored so that it seems like our code, but once used to it we stop making the mistake, and only newcomers are generally concerned) but our pre-commit hook I quoted above solved the problem.
This pre-commit hook is now part of our git template — installed using `git config init.template_dir` — so it's already setup after a fresh `git clone` or `git init` for everyone.

HTH

**Comment by kylef** [comment]
This would be achievable a different way, by removing the writable permission flag on every file, i-e, turning the files into read-only.

```bash
$ chmod 444 Pods/
```

**Comment by ObjSal** [comment]
Here is a script that will make only source projects inside the Pods directory read only:

    pushd Pods
        for f in * ; do    
            if [ "$f" == "Headers" ] || [ "$f" == "Local Podspecs" ] || [ "$f" == "Pods.xcodeproj" ] || [ "$f" == "Target Support Files" ] || [ "$f" == "Manifest.lock" ]; then
                #Skip non source projects
                continue
            fi
            chmod -R -w "$f"
        done
    popd

**Comment by AliSoftware** [comment]
@kyle what about suggesting users to use Yelp's [cocoapods-readonly](https://github.com/Yelp/cocoapods-readonly) CP plugin, that seems to exactly fit those needs and solve the problem?

I haven't tested that CP plugin yet, but if someone could test it and tell if it fits, then we could close the issue for good.

**Comment by getaaron** [comment]
If the Yelp plugin works as expected it should become the default CocoaPods behavior. It's safer and encourages good practices. CC @mglidden

**Comment by mglidden** [comment]
The plugin locks all pods that aren't being installed locally. We've been using it for several months now and haven't run into any issues with it. However, as mentioned earlier in this thread, it won't help if you commit the Pods directory.

I'm happy to submit a pull request if you think it should be the default behavior.

**Comment by AliSoftware** [comment]
Whatever solution we choose (plugin, custom solution, etc), there is no proper solution for people (like me) that commit the Pods directory, so the fact that we recommend the plugin for that won't change a thing, we wouldn't be able to offer more than this plugin has to offer.

So I say go for it, let's suggest this plugin, at least it will provide a solution for people not committing their Pods folder.

**Comment by orta** [comment]
I'd like to see it in core personally :+1:

**Comment by getaaron** [comment]
Can we both lock the pods (like in @mglidden's plugin) and discard inappropriate changes with @AliSoftware's pre-commit hook?

To address @AliSoftware's concern that `chflags` does not stick with git pushs, we could also add a `post-merge` hook to set the flags appropriately.

**Comment by segiddins** [comment]
CocoaPods can't and shouldn't do anything git-specific, but plugins to do that stuff would be great!

**Comment by orta** [comment]
This is in cocoapods core now.

**Comment by kraftydevil** [comment]
This breaks my workflow after updating from 0.33.0 to 0.38.0.

Is it possible to disable this feature in 0.38.0? Preferably on a per-pod basis?

If disabling is not available in the current version, then here's why the feature is giving me trouble:

I often work on my own private library pod on the project(s) using that pod. This way I can test it out before having to 'pod update'.

If everything looks good, I have a script to copy the changes from my project to to the directory where my library pod resides on my machine.

I've found this to be much easier than writing guess-code in my library, pushing changes, calling pod update on the client project and THEN finally getting to see if my changes worked.

The feature is meant to protect me against something that I'm very much aware of. I can see how it makes sense for pods that I didn't write and have no intention of modifying.

It's just easier to them directly. Xcode does give me the option to Unlock the file but it's too much to hit 'Unlock' for every file I want to change.
