### ISSUE TITLE
Xcode 14 resource_bundle with xcasset can not get the image in bundle

### ISSUE THREAD

**Issue by LiMaoAtCD** [CocoaPods/CocoaPods#11561]
after I upgrade Xcode to version 14.0.1, use command 'pod install', I cannot get the image by using  UIImage.init(named: name, in: imageBundle, compatibleWith: nil)  in the imageBundle.
<img width="575" alt="image" src="https://user-images.githubusercontent.com/4811145/192211586-f191db21-1a05-4ad5-82d9-7e1a963323f0.png">

 I found my private pod CMBasicView.bundle in the product file.it seems like 
everything is OK.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/4811145/192210950-b7faeb98-a078-4ddd-9dd4-6438ab6d9dce.png">
before I type 'pod install' by Xcode14. it is fine
<img width="561" alt="image" src="https://user-images.githubusercontent.com/4811145/192210759-47dc6d71-4066-406c-bf7f-3cd8c1c6d861.png">
but after I re-type 'pod install'
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/4811145/192212965-6f2bfe43-6679-4a44-afd1-49291f716003.png">
the image is nil, I open the product file but there is no different in the bundle file 
<img width="255" alt="image" src="https://user-images.githubusercontent.com/4811145/192213187-13cc1f76-342e-4105-a4aa-b8a51b955223.png">
so confused!

**Comment by JosephPoplar** [comment]
https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1273990056

**Comment by JosephPoplar** [comment]
I face the same problem, when I use Xcode 14 and set "CODE_SIGN_ALLOWED" to "NO", you can try this workaround instead.
https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1273990056

**Comment by Ralven** [comment]
this is still occurring in 14.1, has anyone found another solution to this.

**Comment by RafaelFMR** [comment]
Bumping this incase anyone has found a solution, still not seeing one other than just using Resources.

**Comment by parachutemind** [comment]
Same here. 
We had to go back to using `resources` instead of `resource_bundles` in the podspec to work around it.

**Comment by q651082931** [comment]
installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            #设置CODE_SIGN_IDENTITY为空
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings.delete('PRODUCT_BUNDLE_IDENTIFIER')
         end
    end
  end

podfile wriite this,can solve this question。
