### ISSUE TITLE
undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by devwistkey** [CocoaPods/CocoaPods#11572]
# Report
Searching for inspections failed: undefined method `map' for nil:NilClass

## What did you do?
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
Searching for inspections failed: undefined method `map' for nil:NilClass

My Podfile -> https://github.com/devwistkey/zilpay-mobile/blob/s19/ios/Podfile

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by JessieSunShine** [comment]
你这个问题怎么解决的啊
