### ISSUE TITLE
build_settings.rb:446: warning: deprecated Object#=~ is called on Array; it always returns nil

### ISSUE THREAD

**Issue by AppleTidusDev** [CocoaPods/CocoaPods#11626]
`pod install` after log

`Analyzing dependencies
Downloading dependencies
Generating Pods project
/Users/tzx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446: warning: deprecated Object#=~ is called on Array; it always returns nil
/Users/tzx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446: warning: deprecated Object#=~ is called on Array; it always returns nil
/Users/tzx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446: warning: deprecated Object#=~ is called on Array; it always returns nil
/Users/tzx/.rvm/gems/ruby-2.7.0/gems/cocoapods-1.11.3/lib/cocoapods/target/build_settings.rb:446: warning: deprecated Object#=~ is called on Array; it always returns nil
Integrating client project`

master

how can i do fix this  warning?

**Comment by ikesyo** [comment]
This is now broken on Ruby 3.2.0: https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

> ### Removed methods
> The following deprecated methods are removed.
> 
> - …
> - `Kernel#=~` [[Feature #15231](https://bugs.ruby-lang.org/issues/15231)]
> - …
