### ISSUE TITLE
How to support multiplatform in one target?

### ISSUE THREAD

**Issue by liuduoios** [CocoaPods/CocoaPods#11642]
We can develop multiplatform app (for example: iOS and macOS) in one target using Xcode 14.
But in Podfile, it seems must specify only one platform. How to configure it to let it can support multi platforms simultaneously? 
Maybe like this: `platform :osx, '13.0', :ios, '16.0'`

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by Giuliopime** [comment]
Either I don't understand how xcode targets work, or using cocoapods on a multiplatform project is not possible rn. Is that the case?
