### ISSUE TITLE
Pod claim requests stay unattended for months

### ISSUE THREAD

**Issue by nalexn** [CocoaPods/CocoaPods#11678]
# Report

## What did you do?

I submitted several pod claim requests in a span of a few months through your [form](https://trunk.cocoapods.org/claims/new).

After wasting a month waiting, started reaching out to people having relations with CocoaPods directly on Twitter.  Most people kindly responded, but no one has any clue who should be contacted for this type of request.

## What did you expect to happen?

I expect the pod claim request to be reviewed once in a while.

## What happened instead?

2 months passed, and the users of my library [complain](https://github.com/nalexn/ViewInspector/issues/211) about library updates not being published on cocoapods.

## Project that demonstrates the issue

https://github.com/nalexn/ViewInspector

**Comment by orta** [comment]
I just don't have much time for CocoaPods anymore, and other folks don't look at the support queue. I try to throw some time once a quarter to do them, but it's not perfect because I'm busy and it's been years since I've done iOS.

**Comment by orta** [comment]
I got though most of the queue today, thanks for the reminder
