### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by easyhaipi** [CocoaPods/CocoaPods#11712]
NoMethodError - undefined method `=~' for ["-fno-c++-static-destructors", "-fno-unwind-tables", "-fno-asynchronous-unwind-tables"]:Array

https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%3D~%27+for+%5B%22-fno-c%2B%2B-static-destructors%22%2C+%22-fno-unwind-tables%22%2C+%22-fno-asynchronous-unwind-tables%22%5D%3AArray&type=Issues

**Comment by easyhaipi** [comment]
ruby-3.2.0-preview1 版本太高的愿意

**Comment by easyhaipi** [comment]
ruby-3.0.0即可

**Comment by Hitomilras** [comment]
Same issue
