### ISSUE TITLE
Is there a difference between the two ways shown below for adding vendored_frameworks to your PodSpec?

### ISSUE THREAD

**Issue by mfaani** [CocoaPods/CocoaPods#11726]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

When adding an xcframework to your PodSpec, should you do:

```ruby
spec.source = { :git => 'your repo here', :tag => "#{spec.version}" }
vendored_frameworks = "StarWarsKit.xcframework"
```
Then in Podfile just do:

```ruby
pod 'StarWarsKit', '1.0'
use_frameworks!
```

--------------------------------
OR do:

```ruby
s.default_subspecs = 'Source'

s.subspec 'Framework' do |sp|
   sp.ios.vendored_frameworks = 'StarWarsKit.xcframework'
end
s.subspec 'Source' do |sp|
  sp.source_files = 'StarWarsKit/**/*.{swift,storyboard,xib}'
  sp.resources = 'StarWarsKit/**/*.{png,xcassets,gif,strings}'
end
```
Then in Podfile just do:

```ruby
pod 'StarWarsKit/Framework', '1.0'
use_frameworks!
```

To the project that installs the pod, are they the same?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
