### ISSUE TITLE
`spec.source = :http` only gets downloaded after second run `pod install`

### ISSUE THREAD

**Issue by ruijfcanas** [CocoaPods/CocoaPods#11748]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm doing a `pod install` of a Pod of mine whose repository is on Bitbucket. Everything related with authentication has been handled.

## What did you expect to happen?

The pod should be downloaded from the given URL in the .podspec at once since it's everything working as expected locally.

## What happened instead?

The pod doesn't get to download what he is supposed to (I've checked on the project and in cache files - ~/Library/Caches/Cocoapods/Pods/External/MyPod - and I have empty folders) but the logs say the pod was installed with success. I re-run the `pod install` command, and it proceeds to install my Pod (like he never did in the first `pod install`) and proceeds to download it as well.

It looks like at the first `pod install`, it is not possible to read the .podspec file in the repository or there's some kind of conflict between the pre-downloading (done when fetching external sources) and the URL on `spec.source`

This is only happening when I'm using `spec.source` with an URL while trying to download a file of type .tgz or .zip. 

## CocoaPods Environment

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin20]
    RubyGems : 3.0.9
        Host : macOS 12.6.2 (21G320)
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /.rvm/rubies/ruby-2.6.0/lib
```

## Podspec
```ruby
Pod::Spec.new do |spec|
  spec.name = 'MyPod'
  spec.version = "MyVersion"
  spec.homepage = '...'
  spec.authors = '...'
  spec.license = "..."
  spec.summary = '...'
  spec.static_framework = true
  spec.vendored_frameworks = "myFramework.xcframework"
  spec.libraries = "c++"
  spec.module_name = "#{spec.name}_umbrella"
  spec.ios.deployment_target = '...'
  spec.source = { 
:http => "https://.../rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/raw/myFramework.tar.gz?at=#{spec.version}",
 :type => 'tgz'
}
end
```

## Podfile
```ruby
use_frameworks!

pod 'shared', :git => 'https://.../myBitbucketRepo.git', :tag => 'x.y.z'
...
```

**Comment by ShaneQi** [comment]
I've encountered the same issue (along with another related issue), I did a little bit of digging and created another issue to cover both issues: https://github.com/CocoaPods/CocoaPods/issues/11867

I suggest closing this issue because my issue has better description of the root cause and has a demo project.

**Comment by ruijfcanas** [comment]
I ended up not providing much more info since I just abandoned the idea of following this approach but I'd still like to see this fixed in the future. Thanks for opening your issue. I'll close this one.
