### ISSUE TITLE
pod install/update failed, "cannot handle socket"

### ISSUE THREAD

**Issue by swoderheart** [CocoaPods/CocoaPods#11769]
Hello, I encountered a problem：
and I have tried to reinstall cocoapod with version 1.11.2 and 1.11.3
the problem still exists.

cocoapods (1.11.2) / (1.11.3)
cocoapods-core (1.11.2) / (1.11.3)
cocoapods-deintegrate (1.0.5)
cocoapods-downloader (1.6.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.1)
cocoapods-trunk (1.6.0)
cocoapods-try (1.2.0)

I also tried clean cache by :
pod cache clean --all   
or
rm -rf ~/Library/Caches/CocoaPods

And the problem still exists. 
--------------------------------------------------------
`Fetching external sources
-> Pre-downloading: `AFNetworking` from `https://git.woa.com/XXXXSpecs/AFNetworking.git`, tag `3.2.1`
  > Copying AFNetworking from `/Users/hoho/Library/Caches/CocoaPods/Pods/External/AFNetworking/220efda2ca6a01ddf1a630d4f75915e1` to `Pods/AFNetworking`
-> Fetching podspec for `Flutter` from `Flutter`
-> Pre-downloading: `TAImage` from `http://git.woa.com/engineering/TAImage.git`, commit `3b02ffe`
 > Git download
 > Git download
     $ /usr/bin/git clone http://git.woa.com/engineering/TAImage.git /var/folders/j4/ck4kvxv93s10srzcr0n3hxpr0000gn/T/d20230215-11004-1h7127x --template=
     Cloning into '/var/folders/j4/ck4kvxv93s10srzcr0n3hxpr0000gn/T/d20230215-11004-1h7127x'...
   $ /usr/bin/git -C /var/folders/j4/ck4kvxv93s10srzcr0n3hxpr0000gn/T/d20230215-11004-1h7127x checkout --quiet 3b02ffe

**[!] Error installing TAImage
[!] Failed to download 'TAImage': cannot handle socket**

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:120:in `rescue in block in pre_download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:115:in `block in pre_download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/abstract_external_source.rb:113:in `pre_download'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:993:in `fetch_external_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:972:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:971:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:971:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:970:in `fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'`

**Comment by orta** [comment]
This is likely a local setup issue with however you communicate to `http://git.woa.com/engineering`
