### ISSUE TITLE
https://cocoapods.org is down

### ISSUE THREAD

**Issue by jensenbox** [CocoaPods/CocoaPods#11789]
I am not sure where else to report this.

![image](https://user-images.githubusercontent.com/189265/221462655-e338a2e2-a01e-4593-8f59-c62d9461b238.png)

**Comment by akjha96** [comment]
I am seeing the same error. And flutter doctor command is failing due to this. 
[!] HTTP Host Availability
    ✗ HTTP host "https://cocoapods.org/" is not reachable. Reason: Failed to
      connect to host in 10 seconds

**Comment by orta** [comment]
Thanks heroku had changed an env var for us, and I've corrected it
