### ISSUE TITLE
All commands are invalid

### ISSUE THREAD

**Issue by Kejiasir** [CocoaPods/CocoaPods#11792]
# Report

## What did you do?

Run `pod install`，`pod --help`，`pod --version`， all commands....

## What did you expect to happen?
Right job

## What happened instead?

Ignoring ffi-1.15.5 because its extensions are not built. Try: gem pristine ffi --version 1.15.5
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies': undefined method `request' for nil:NilClass (NoMethodError)

    [@failed_dep.dependency, @activated.request.dependency]
                                       ^^^^^^^^
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/exceptions.rb:61:in `conflicting_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/exceptions.rb:55:in `initialize'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver.rb:193:in `exception'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver.rb:193:in `raise'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver.rb:193:in `rescue in resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver.rb:191:in `resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/request_set.rb:411:in `resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/request_set.rb:423:in `resolve_current'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:228:in `finish_resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:285:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:283:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:283:in `activate_bin_path'
	from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317:in `raise_error_unless_state': Unable to satisfy the following requirements: (Gem::Resolver::Molinillo::VersionConflict)

- `minitest (>= 5.1)` required by `activesupport-6.1.7.2`
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
	from <internal:kernel>:90:in `tap'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/resolver.rb:190:in `resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/request_set.rb:411:in `resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/request_set.rb:423:in `resolve_current'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:228:in `finish_resolve'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:285:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:283:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:283:in `activate_bin_path'
	from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'

## CocoaPods Environment

The above error occurred when I was running all the commands. I do not know the reason. Ask for help

**Comment by dnkoutso** [comment]
Seek support for ffi installation issues.
