### ISSUE TITLE
Command `pod install` failed. └─ Cause: pod exited with non-zero code: 1

### ISSUE THREAD

**Issue by showtan001** [CocoaPods/CocoaPods#11793]
# Report

## What did you do
Run `pod install`

##  happened

`Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 1
/Users/daihuangfeng/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems.rb:263:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
	from /Users/daihuangfeng/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems.rb:282:in `activate_bin_path'
	from /Users/daihuangfeng/.rvm/gems/ruby-2.7.6/bin/pod:25:in `<main>'
	from /Users/daihuangfeng/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `eval'
	from /Users/daihuangfeng/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `<main>'`

**Comment by orta** [comment]
This is an issue in your local ruby environment, I'd recommend re-installing your dependencies etc
