### ISSUE TITLE
subdomain cdn2.cocoapods.org vulnerable to subdomain hijacking attack

### ISSUE THREAD

**Issue by jossef** [CocoaPods/CocoaPods#11798]
I want to report subdomain [cdn2.cocoapods.org](https://cdn2.cocoapods.org) is vulnerable to subdomain hijacking attacks via GitHub Pages.

It seems that the subdomain was used years ago and abandoned, but the DNS records still point to GitHub Pages hosting service, and this is how attackers hijacked it to host a fishy casino website (shoutout to @guynachshon from my team on discovering this):

![Group 2661 (1)](https://user-images.githubusercontent.com/1287098/222135339-129eb056-583a-437d-a78a-c79b858034ab.png)

While we are investigating this, the subdomain got freed on GitHub Pages (probably due to an update/mistake of the attackers)

![Group 2665](https://user-images.githubusercontent.com/1287098/222137504-934a24e3-d287-4232-a6d4-ef49fa2cf33b.png)

We jumped on the opportunity and created a [simple repository](https://github.com/jossef/cocoapods-subdomain-hijacking-demo) to hold this subdomain and prevent another takeover by those casino attackers. 

This works as long as the subdomain is unoccupied by another GitHub Pages project and is super simple to set up - settings, enable GitHub Pages, type the subdomain "cdn2.cocoapods.org":

![Group 2666](https://user-images.githubusercontent.com/1287098/222135040-29a931cc-6094-4200-b677-badd559e382e.png)

For now, it shows the simple readme of my repo. If you are going to delete the cdn2.cocoapods.org DNS record that would resolve this. Otherwise let me know if you want me to release the domain from my repo on GitHub Pages so you could grab it

![Group 2664](https://user-images.githubusercontent.com/1287098/222139792-7472da9b-3216-47c5-8609-589b8dd41adc.png)

**Comment by orta** [comment]
Thanks for the really well done writeup - I've just dropped `cdn2.` from our DNS records and that should be updating everywhere now!

**Comment by orta** [comment]
OK, this looks to be correctly NOOPing now - thanks!
