### ISSUE TITLE
[CP] Embed Pods Frameworks is removed and not add again.

### ISSUE THREAD

**Issue by felipeflorencio** [CocoaPods/CocoaPods#11800]
# Report

It happens with random people that the "[CP] Embed Pods Frameworks" is being deliberated removed from the project.pbproj and it's not being added again.

This issue is not reproducible for a specific user that has this issue.

The project has the "[CP] Embed Pods Frameworks" in the project.pbprojec, he runs "pod install" If you look into the diff, the only thing that happens is this phase is removed.

The project doesn't work, when you try to build you get a dylb error, for apparent reasons as it was removed.

## What did you do?

Clear cache, both Xcode and pod, also update pod, for one user update cocoapods installation worked well, to the other one no.

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
The "[CP] Embed Pods Frameworks" is removed from the project.pbproject and you get and dylb crashs

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
Last one or older doesn't matter
All M1 machines

What do I expect to get here?

As it's user-specific, I want to know if someone knows in the cocoapods source code where is the code that removes the "[CP] Embed Pods Frameworks" and add it again.

Why?

As I can't reproduce my goal is to read the source code to find out if somewhere there I can get a clue, talk to this user and see if he changes something will make it work, and if yes I can come here and provide a solution.

Appreciate any guidance.

**Comment by CrazyFanFan** [comment]
Have you tried `pod deintegrate` and then run `pod install` again? 
Note that `pod deintegrate` will remove the local Pods directory and roll back the changes made by Cocoapods to the MainProject.

**Comment by felipeflorencio** [comment]
Yep, all the basic stuff like deintegrate, even manually delete the xcframework, clean cocoapods cache, and more.

In the end I just dropped how I was doing to go with another solution, the number of issues that I have with cocoapods when building .framework is getting quite high
