### ISSUE TITLE
cocopods  from file in git repo 

### ISSUE THREAD

**Issue by aplha98** [CocoaPods/CocoaPods#11825]
please help, 
I have git repo contains files like this this 
main/kmm/podspec

my profile
 pod 'benoShared', :git => 'git@bitbucket.org:xteam/kmm-pod.git', :branch => 'main'
 
 I want cocopod to install the pod from main/kmm/podspec in my git repo

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
