### ISSUE TITLE
Error while installing cocoa pods

### ISSUE THREAD

**Issue by Ebisrf** [CocoaPods/CocoaPods#11849]
Despite all proposed solutions I can't install cocoa pods on my MacBook air operating Ventura 13.2.1

Last login: Sun Apr  9 17:14:24 on ttys000
michaelheger@Michaels-MacBook-Air ~ % sudo gem install cocoapods
Password:
Fetching addressable-2.8.4.gem
ERROR:  Error installing cocoapods:
	The last version of activesupport (>= 5.0, < 8) to support your Ruby & RubyGems was 6.1.7.3. Try installing it with `gem install activesupport -v 6.1.7.3` and then running the current command again
	activesupport requires Ruby version >= 2.7.0. The current ruby version is 2.6.10.210.
michaelheger@Michaels-MacBook-Air ~ % gem install activesupport -v 6.1.7.3
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
michaelheger@Michaels-MacBook-Air ~ % 

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by hackv01d** [comment]
I had exactly the same problem, so I tried to install it using homebrew:
$ brew install cocoapods
The problem is gone

**Comment by Ebisrf** [comment]
Thanks a lot, it work for me, too!Great solution, simple and effective!Am 02.05.2023 um 20:56 schrieb Ivan Semenov ***@***.***>:﻿
I had exactly the same problem, so I tried to install it using homebrew:
$ brew install cocoapods
The problem is gone

**Comment by summer-wu** [comment]
I encountered exactly same error, I am using MacOS Ventura 13.3, the system ruby version is `ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]`
![image](https://github.com/CocoaPods/CocoaPods/assets/2476434/6f75dc40-4775-4754-81e1-6026f1f8cf57)

There are many ways to fix it, e.g. using ruby v2.7 or using brew.
But for simplicity, I just run these two commands:
```
sudo gem install activesupport -v 6.1.7.4
sudo gem install cocoapods --verbose --debug
```

**Comment by hamzakocinkag** [comment]
**MacOS Sonoma 14.0**

![image](https://github.com/CocoaPods/CocoaPods/assets/52803358/25f98678-d97b-4bef-b3af-5d13234a8165)


`sudo gem install activesupport -v 6.1.7.6`
`sudo gem install cocoapods`

**Comment by mzm008** [comment]
yes。 I also got this problem

**Comment by viktornord** [comment]
+1, please get it fixed

**Comment by saiprasad-coditas** [comment]
+1 I also have the same problem

**Comment by paulb777** [comment]
activesupport dependency issues should be addressed with CocoaPods 1.14.x

**Comment by markhu** [comment]
Workaround that worked for me under macOS Sonoma 14.1 was to install an older version of the pod command:

`sudo gem install cocoapods -v "1.13.0"`

**Comment by jojo7590** [comment]
Thanks
