### ISSUE TITLE
pod trunk push fails validation warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]

### ISSUE THREAD

**Issue by zorgiepoo** [CocoaPods/CocoaPods#11846]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I ran `pod trunk push` to push [a new pod](https://github.com/sparkle-project/Sparkle/blob/2.x/Sparkle.podspec)

## What did you expect to happen?

To push the pod without any validation issues.

## What happened instead?

I hit validation issues

```
    - NOTE  | xcodebuild:  note: Using codesigning identity override: 
    - NOTE  | [OSX] xcodebuild:  note: Building targets in dependency order
    - WARN  | xcodebuild:  /var/folders/3l/bj6h32n11wlg8zj8585gwy2c0000gn/T/CocoaPods-Lint-20230407-76308-37tpae-Sparkle/App/main.m:3:9: warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]

[!] The spec did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it).
```

### Stack

```
   CocoaPods : 1.12.0
        Ruby : ruby 3.2.0 (2022-12-25 revision a528908271) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.3 (22E252)
       Xcode : 14.3 (14E222b)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

[Project is here](https://github.com/sparkle-project/Sparkle).

--

On a closer inspection with `pod lib lint` I think cocoapods is autogenerating some code with `int main() {}` -- Xcode suggests inserting `void` in the parameter list.

**Comment by paulb777** [comment]
I believe this is an issue introduced with Xcode 14.3
