### ISSUE TITLE
flutter dependencies   sqflite: ^2.2.6 error

### ISSUE THREAD

**Issue by lhpllpp** [CocoaPods/CocoaPods#11842]
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /opt/homebrew/opt in PATH, mode 040777
    objc[72603]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f0f1ab90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ae42c8). One of the two will be used. Which one is undefined.
    objc[72603]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f0f1abe0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103ae4318). One of the two will be used. Which one is undefined.
    Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by orta** [comment]
This doesn't really seem like an actionable issue, I'd recommend looking into flutter specific sources for info

**Comment by lhpllpp** [comment]
你好，您的邮件已收到，谢谢。
