### ISSUE TITLE
Please release 1.12.1

### ISSUE THREAD

**Issue by tim-eucalyptus** [CocoaPods/CocoaPods#11843]
This one is blocking our Flutter development/deployment right now: https://github.com/CocoaPods/CocoaPods/pull/11828

It looks like a lot of other people agree.

Thanks!

**Comment by andreasreuter** [comment]
You can give it a try to change your Pods-APPNAME-frameworks.sh file:
```
if [ -L "${source}" ]; then
  echo "Symlinked..."
  source="$(readlink "${source}")"
fi
```

with:
```
if [ -L "${source}" ]; then
  echo "Symlinked..."
  source="$(readlink -f "${source}")"
fi
```

**Comment by orta** [comment]
Given the message at the end of https://github.com/CocoaPods/CocoaPods/pull/11828#issuecomment-1496357883 I'm closing this as a dupe
