### ISSUE TITLE
Searching for inspections failed: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by JakeTorres** [CocoaPods/CocoaPods#11844]
"Searching for inspections failed: undefined method `map' for nil:NilClass"
Above question  when i  pod install --verbose, with "Kingfisher". find an error  review log that in Kingfisher.podspec.json.
path:repos->trunc->a->a->6->kingfisher-7.6.2->Kingfisher.podsec.json. podsec.json styele wrong, update all is ok.

**Comment by paulb777** [comment]
Please use issue template.
