### ISSUE TITLE
Upgrade from xCode 14.2 to 14.3 PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by bitfactory-michel-lubbers** [CocoaPods/CocoaPods#11856]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `xcode -> build -> archive`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. That the app is build

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. The build failed with error.
`PhaseScriptExecution failed with a nonzero exit code`

## CocoaPods Environment

ℹ Please replace line 44 with code `source="$(readlink "${source}")"`.
e.g. into this `source="$(readlink -f "${source}")"`
file: Pods-App-frameworks.sh

## Project that demonstrates the issue

ℹ It is a private project.

## Mention
https://developer.apple.com/forums/thread/725230?answerId=746897022#746897022

## Is also mention with apple feedback:
ℹ Thank you for filing the feedback report. After reviewing the issue you reported, we've determined it should be investigated and resolved by CocoaPods - the third-party software you are using. Please contact them for assistance.

**Comment by mehmetbaykar** [comment]
Any update on this?

**Comment by o15a3d4l11s2** [comment]
It is already merged: https://github.com/CocoaPods/CocoaPods/pull/11828
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/11808

**Comment by jonesnc** [comment]
Any word on when this change will be pushed to rubygems?

**Comment by litinskii** [comment]
+1

**Comment by paulcarpenter** [comment]
+1

**Comment by Imtayaz** [comment]
still struggling
