### ISSUE TITLE
am try install firebase in my react native project

### ISSUE THREAD

**Issue by sushmitha1994** [CocoaPods/CocoaPods#11860]
If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
<img width="1440" alt="Screenshot 2023-04-12 at 12 13 41 PM" src="https://user-images.githubusercontent.com/103494943/231373449-323f9805-112a-47e4-8ac9-0a4c677ef82d.png">
<img width="1440" alt="Screenshot 2023-04-12 at 12 14 03 PM" src="https://user-images.githubusercontent.com/103494943/231373515-08dd34c0-a665-4a33-95b4-09aeadd18dd3.png">

**Comment by paulb777** [comment]
Please follow issue template or follow up in react native forum.
