### ISSUE TITLE
The pod library code color is the same as the system

### ISSUE THREAD

**Issue by MuRanJiangXia** [CocoaPods/CocoaPods#11872]
The pod library code color is the same as the system

xcode 14.3

**Comment by orta** [comment]
Not really sure what you mean?

**Comment by MuRanJiangXia** [comment]
The class name and method of the pod third-party library are the same as the API color of the system.
Previously, Pod's third-party library class names, methods, and custom method colors were the same

**Comment by orta** [comment]
That sounds like an Xcode feature, you might want to revert to an older build of Xcode maybe.
