### ISSUE TITLE
Pod spec lint throws The requested URL returned error: 404

### ISSUE THREAD

**Issue by jaykumarvcx** [CocoaPods/CocoaPods#11896]
EnablexWebRTC (1.0.2)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/curl -f -L -o /var/folders/mv/vjq48h6s349c4scqf3_9r89r0000gn/T/d20230509-2903-ewmdri/file.zip https://www.enablex.io/httpdocs/developer/wp-content/uploads/EnablexWebRTC_1.0.2.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
) during validation.

[!] The spec did not pass validation, due to 1 error.

Where i am using Mac M1 Chip
Cococpad Version - 1.12.1
Xcode Version - 14.3

**Comment by joshuarendora1** [comment]
Hi Good Day before we begin can i ask a little favor to Subscribe these
Youtube chanel?
Please click Link Below. 👇👇

https://youtube.com/shorts/va3bZK4wiKU?feature=share


YOU'RE SUBSCRIPTION IS REALLY A BIG HELP TO THE CHARITY WE CHOSEN TO
RECEIVED 75% OF THE SALLARY WE MAKE IN THE FUTURE.

WE ARE EXPECTING THAT YOU ARE ALSO IN LINE AND 1 OF THOSE PEOPLE ALSO WHO
SUPPORT WHAT WE MAKE AND PLAN IN THE FUTURE IN HELPING OTHERS ♥️♥️♥️

THANK YOU SO MUCH ♥️

**Comment by jaykumarvcx** [comment]
Any help on same please.

**Comment by jaykumarvcx** [comment]
> This URL 404s for me also

Why you closed this issue, As of now no solution for the same.

**Comment by paulb777** [comment]
The missing URL isn't a CocoaPods issue. It's a problem with the `EnablexWebRTC` pod and their support channels should be contacted.
