### ISSUE TITLE
pod spec lint Error !!!

### ISSUE THREAD

**Issue by Kejiasir** [CocoaPods/CocoaPods#11900]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

### I am creating a private library. When I edited the `.podspec` file for `pod spec lint`, I keep encountering errors. I have tried countless times to modify the path of `subspec` -> `source_files`, but still report errors. Please help me!

![20230511190010](https://github.com/CocoaPods/CocoaPods/assets/14361443/6dd9fbbb-9506-4502-a01b-1699c2ca35c8)

**Comment by paulb777** [comment]
Please fill out the issue template with a reproducible example.
