### ISSUE TITLE
Error installing BarrierFreeSDK

### ISSUE THREAD

**Issue by averroecp** [CocoaPods/CocoaPods#11905]
[!] Error installing BarrierFreeSDK
[!] /usr/bin/curl -f -L -o /var/folders/yc/qdg7tb5s24v9x_4fgx76m3rr0000gn/T/d20230512-19126-a5je4m/file.zip https://nexus3.mapxus.com/repository/barrier-free-ios/1.8.0/barrier-free-sdk-ios.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3'

**Comment by paulb777** [comment]
Either a transient network error or an issue with BarrierFreeSDK
