### ISSUE TITLE
Issue with sharing pods with multiple targets

### ISSUE THREAD

**Issue by nrajput05** [CocoaPods/CocoaPods#11901]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I want to keep Braintree/ApplePay pod in a child target which should have some common pods as well. Here is how the pod file looks like
```
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

use_frameworks!

def common_pods
  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'Braintree'
  pod 'Braintree/Venmo'
  pod 'SwiftLint'
  pod 'JTAppleCalendar'
  pod 'MaterialComponents/TextControls+FilledTextFields'
end
  
target 'testAllDeps' do
  common_pods
  pod 'Braintree/ApplePay'

end

target 'testCommonDeps' do
  common_pods

end
```

## What did you expect to happen?

testCommonDeps compiles successfully but testAllDeps fails with these errors:
Multiple commands produce '/Users/xxxx/Library/Developer/Xcode/DerivedData/testFlurry-dswkraujlkgxwmdvcldydpsuplzu/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Braintree/PayPalDataCollector/PPRiskMagnes.framework'

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin21]
    RubyGems : 3.4.10
        Host : macOS 12.6.1 (21G217)
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0

```

**Comment by paulb777** [comment]
This is not a CocoaPods issue. It is not possible to link a static framework into both the app and dynamic frameworks.  See the explanation at https://github.com/firebase/firebase-ios-sdk/blob/master/docs/firebase_in_libraries.md

**Comment by nrajput05** [comment]
But I am just trying to have different pods for two app targets. Isn't that possible? Where did I mention the static framework?

**Comment by paulb777** [comment]
Reopening since it's dynamic:
```
file ./Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Braintree/PayPalDataCollector/PPRiskMagnes.framework/PPRiskMagnes
./Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Braintree/PayPalDataCollector/PPRiskMagnes.framework/PPRiskMagnes: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [arm64:Mach-O 64-bit dynamically linked shared library arm64]
./Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Braintree/PayPalDataCollector/PPRiskMagnes.framework/PPRiskMagnes (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
./Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Braintree/PayPalDataCollector/PPRiskMagnes.framework/PPRiskMagnes (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by nrajput05** [comment]
@paulb777 Any update on this issue please? Is there any other way you would like to suggest to have pods separately for separate targets? I can live with the workaround for now but managing two codebases one with ApplePayPod and other without is a pain.

**Comment by orta** [comment]
@nrajput05 you're welcome to look into it and send pull requests if you have a pressing time constraint. CocoaPods is an open source run by volunteers in their spare time.

**Comment by nrajput05** [comment]
> @nrajput05 you're welcome to look into it and send pull requests if you have a pressing time constraint. CocoaPods is an open source run by volunteers in their spare time.

Can you point me in some direction of what is causing this issue in terms of the internal working of Cocoapods?
