### ISSUE TITLE
No update for a long time on pod claim

### ISSUE THREAD

**Issue by darahak-datadome** [CocoaPods/CocoaPods#11918]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Hello 👋 

My team submitted a couple of pod claims from this [page](https://trunk.cocoapods.org/claims/new) for a [project](https://github.com/CocoaPods/Specs/tree/master/Specs/1/3/3/DataDomeAFNetworking) that we are maintaining.

This was done back in February 2023, but we have not heard back from anyone.

The problem is that the pod is owned by a former employee who left last year and we are not able to publish updates for it.

## What did you expect to happen?

I would expect pod claims to be reviewed with a reasonable delay.
I understand that maintainers are probably busy elsewhere, but it is impacting our business so I'm giving this a try to move the process forward.

## What happened instead?

We did not get any feedback on our pod claim that was done more than 3 months ago.

## Project that demonstrates the issue

https://github.com/CocoaPods/Specs/tree/master/Specs/1/3/3/DataDomeAFNetworking

**Comment by imaginaris** [comment]
Same here except we are waiting for two weeks now. I don't know if that's normal.
@darahak-datadome Did you get some kind of confirmation email after submitting the claim?

**Comment by darahak-datadome** [comment]
@imaginaris I don't recall getting anything. I saw [this other issue](https://github.com/CocoaPods/CocoaPods/issues/11678), that's why I opened a new one for my case.

**Comment by orta** [comment]
Hey folks, I usually only look at them every 6 months or so nowadays, I just don't really have the time for that OSS admin work on a regular basis

I've just gone through the backlog, and I expect both of you should have some sort of email from me 👍🏻

**Comment by imaginaris** [comment]
Thanks @orta. I know you are super busy.  I got you email 👍

I think it would be nice to get some kind of automated confirmation email after submitting the claim (just like with `pod trunk register`). I got into thinking that maybe there was some internal server error or I made a typo in email address.
