### ISSUE TITLE
Issue uploading a pod

### ISSUE THREAD

**Issue by iliescu-Andrei** [CocoaPods/CocoaPods#11911]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk push

## What did you expect to happen?

Upload a new pod

## What happened instead?

I received the uploaded successfully, but after more than a week, i am still redirected to the github page and the pod is not findable in with pod search

### Stack

```
   CocoaPods : 1.11.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.6.3 (21G419)
       Xcode : 14.2 (14C18)
         Git : git version 2.15.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

The project is ZeroBounceSDK_India. (https://cocoapods.org/pods/ZeroBounceSDK_India)

**Comment by nickohold** [comment]
+1 - We have the same issue. 
Our deploy was faulty due to this error, even after upgrading cocoapods to latest version.
Fix ASAP please!

**Comment by Yurish-IL** [comment]
+1 - I also experience same issue when running -

**Comment by roi-eshel-ironsrc** [comment]
Same here :/ 
Two deploys are now stuck
We are now in mid deployment and that would soon affect our users.
Please fix as soon as possible!

**Comment by orta** [comment]
I took a stab at trying to fix https://github.com/CocoaPods/CocoaPods/issues/11621 this morning by putting trunk infront of a CDN, which certainly reduced the pressure on the API, but seems to have a side effect of stopping uploads - just disabled it! Sorry folks

**Comment by iliescu-Andrei** [comment]
@orta
Hi, this issue is not solved for me, the cocoapods link redirects to the github page since I first uploaded it more than a week ago. I can install it now but the `pod search` does not return anything and the redirect to github page is still happening.
