### ISSUE TITLE
It seems CocoaPods does not support multi platforms in one target.

### ISSUE THREAD

**Issue by liuduoios** [CocoaPods/CocoaPods#11943]
I want to build an app in one target for iOS and macOS，can CocoaPods do this? How to do that?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
