### ISSUE TITLE
CordovaPluginsResources.framework - Pods issues

### ISSUE THREAD

**Issue by RenzoPH** [CocoaPods/CocoaPods#11957]
We encountering this issue in our build. Even we try to update our pods or cocoaPods but the issue still persist. Whose anyone are having a solution for this issues

ios/App/build/Debug-iphoneos/CordovaPluginsResources/CordovaPluginsResources.framework/scannerOverlay.nib" not found. Run 'pod install' to update the copy resources script.

<img width="161" alt="image" src="https://github.com/CocoaPods/CocoaPods/assets/132117813/2847896f-08e0-4422-9681-62abbf54905e">

**Comment by dnkoutso** [comment]
This is not an actionable issue report.

**Comment by dnkoutso** [comment]
Please fill in issue template, include an example and more information.
