### ISSUE TITLE
When I made a 'pod trunk push' error

### ISSUE THREAD

**Issue by chensunwang** [CocoaPods/CocoaPods#11951]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk push HYCivicCenter.podspec --use-libraries --allow-warnings --sources='https://code.aliyun.com/mpaas-public/podspecs.git,https://github.com/CocoaPods/Specs.git'

## What did you expect to happen?

successfully published!

## What happened instead?

[!] Unknown option: `--sources=https://code.aliyun.com/mpaas-public/podspecs.git,https://github.com/CocoaPods/Specs.git`
Did you mean: --use-modular-headers?

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin22]
    RubyGems : 3.1.4
        Host : macOS 13.4 (22F66)
       Xcode : 14.3.1 (14E300c)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /Users/chensunwang/.rvm/rubies/ruby-2.7.2/lib
Repositories : aliyun-mpaas-public-podspecs - git - https://code.aliyun.com/mpaas-public/podspecs.git @ 78b071daf4c819f743bb0bd299e4b3680430c2d6

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 09e365d08ae25b65612a149a2281f7541b9500c7

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/chensunwang/.rvm/gems/ruby-2.7.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrel
![WX20230615-202338@2x](https://github.com/CocoaPods/CocoaPods/assets/24197561/80e6b1c6-fc76-4a17-ac38-a4b80323d464)
ated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by paulb777** [comment]
`--sources` is not an available option for `pod trunk push`. 

Since `trunk` is specifying that the main CocoaPods source of truth is requested - not an alternative source.

**Comment by chensunwang** [comment]
So how do I publish with 'pod trunk push'? thank you
