### ISSUE TITLE
Xcode 14.2. How to correctly change dynamic pod library to static?

### ISSUE THREAD

**Issue by timoninas** [CocoaPods/CocoaPods#11960]
The third party library began to support only the static cocoapods library. Before that, it was connected as dynamic

After changing the dynamic library to a static one, such an error began to appear

I'm using Xcode 14.2

Please help me figure this out:

`Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56 `

```
ld: warning: Could not find or use auto-linked library 'swiftCompatibility56'
ld: warning: Could not find or use auto-linked framework '<Name>'
ld: warning: Could not find or use auto-linked framework '<Name>'
ld: warning: Could not find or use auto-linked framework '<Name>'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftCompatibility56", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_<someName> in <ThirdPartyLibrary>.a(File.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$<ThirdPartyLibrary> in <ThirdPartyLibrary>.a(File.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$<ThirdPartyLibrary> in <ThirdPartyLibrary>.a(File.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$<ThirdPartyLibrary> in <ThirdPartyLibrary>.a(File.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$<ThirdPartyLibrary> in <ThirdPartyLibrary>.a(File.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$<ThirdPartyLibrary> in <ThirdPartyLibrary>.a(File.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$<ThirdPartyLibrary> in <ThirdPartyLibrary>.a(File.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility56_$_<ThirdPartyLibrary>, __swift_FORCE_LOAD_$_swiftCompatibility56_$_<ThirdPartyLibrary> , __swift_FORCE_LOAD_$_swiftCompatibility56_$_<ThirdPartyLibrary> )
ld: symbol(s) not found for architecture arm64

```

P.S. My podfile doesn't contain line `use_frameworks!`

P.S.S. I also did add empty file at project. It doesn't help me :(

**Comment by omarzl** [comment]
I don't think this is related to Cocoapods at all, the error is that it is not being able to link with the corresponding `libswiftCompatibilityConcurrency.a`
You should validate the linker flags passed during the linking phase.
An option is that you force the linker to search the library this way:
`-L$(DEVELOPER_DIR)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(PLATFORM_NAME)` in `Other Linker Flags`option.

Example:
<img width="1173" alt="Captura de pantalla 2023-06-27 a la(s) 17 32 35" src="https://github.com/CocoaPods/CocoaPods/assets/6267487/6e56e61c-ef25-44a1-adfa-8f559f2b4cff">

**Comment by timoninas** [comment]
@omarzl 

I've added this option to Build settings, clear all project, but still have the same error

<img width="882" alt="Screenshot 2023-06-28 at 11 28 11" src="https://github.com/CocoaPods/CocoaPods/assets/46595497/2543c97c-3464-43cd-9e97-77a5a224e82f">


:(
<img width="350" alt="Screenshot 2023-06-28 at 11 29 27" src="https://github.com/CocoaPods/CocoaPods/assets/46595497/4652d6c0-01e5-450e-8b4d-ce1a109cde98">

**Comment by mikehouse** [comment]
I see that Xcode 14.2 has 5.7.2 swift version, may be the error swiftCompatibility56 says that the library was built with swift 5.6 version that is not compatible with Xcode 14.2

**Comment by omarzl** [comment]
Oh I see that Xcode 14.2 doesn't have the static lib `libswiftCompatibility56.a` while Xcode 14.3 has it.
You should be able to solve your issue by upgrading to 14.3 without any additional linker flags.

**Comment by timoninas** [comment]
@mikehouse @omarzl thank you a lot, it was misinformation from vendor
They now support Xcode 14.3 as the minimum version

**Comment by tattivitorino** [comment]
hi there.. facing the same problem here.. is there a way to fix this without updating XCode?

this is happening after I added facebook_app_events package into my flutter project which is new project without any other packages.. (i'm testing in a clean project)

that's the error..

```
[   +4 ms] Failed to build iOS app
[        ] Error (Xcode): Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56
           
[   +1 ms] Could not build the application for the simulator.
[        ] Error launching application on iPhone 13 Pro Max.
[   +1 ms] "flutter run" took 48,508ms.
[   +3 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:752:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1350:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

that's my flutter environment:
```
[✓] Flutter (Channel stable, 3.16.0, on macOS 13.2.1 22D68 darwin-arm64, locale en-BR)
    • Flutter version 3.16.0 on channel stable at /Users/tattivitorino/fvm/versions/3.16.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (5 months ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64

```

**Comment by hoangphuc1103** [comment]
Hi everyone, my MacOs is Monterey 14.7.5 and I can't update XCode version to 14.3 :((
Are there any solutions?

**Comment by saadzarif** [comment]
@hoangphuc1103 did you find anything?
Did anybody find any solution?

**Comment by hoangphuc1103** [comment]
> @hoangphuc1103 did you find anything? Did anybody find any solution?

Hi saadzarif, I'm still stuck with this issue, it seems that now I can't build flutter app on old MacOS

**Comment by haithngn** [comment]
Ensure the libswiftCompatibility56.a file exists from your Xcode bundle
```
fd swiftCompatibility56 /Applications/Xcode.app
```

result should be
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/libswiftCompatibility56.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCompatibility56.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/watchos/libswiftCompatibility56.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCompatibility56.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/appletvsimulator/libswiftCompatibility56.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/watchsimulator/libswiftCompatibility56.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/appletvos/libswiftCompatibility56.a
```

**Comment by arys** [comment]
I solved this by fixing my TOOLCHAIN_DIR variable:		
TOOLCHAIN_DIR = "$(DEVELOPER_DIR)/Toolchains/XcodeDefault.xctoolchain";
it was empty and my swift path was just /usr/lib/swift, and of course that path doesn't have swiftCompatibility56 files.

**Comment by thodorisNtorlis** [comment]
> I solved this by fixing my TOOLCHAIN_DIR variable: TOOLCHAIN_DIR = "$(DEVELOPER_DIR)/Toolchains/XcodeDefault.xctoolchain"; it was empty and my swift path was just /usr/lib/swift, and of course that path doesn't have swiftCompatibility56 files.

How can i update OOLCHAIN_DIR variable in xcode. I am new in ios development.

**Comment by arys** [comment]
@thodorisNtorlis I just opened my project in code editor and searched for TOOLCHAIN_DIR

**Comment by phucprime** [comment]
Download the newer version of Toolchain for Xcode; it worked for me like a charm!

https://www.swift.org/install/macos/

**Comment by thodorisNtorlis** [comment]
> Download the newer version of Toolchain for Xcode; it worked for me like a charm!
> 
> https://www.swift.org/install/macos/

I have updated the toolchain and i get the same error.

**Comment by alisabry22** [comment]
@tattivitorino  have you solved this issue with facebook_app_events me also facing the same issue.

**Comment by hugorivera** [comment]
> @tattivitorino have you solved this issue with facebook_app_events me also facing the same issue.

i have the same issue with facebook_app_events, i fix it just updating xcode to 15.4

**Comment by manali-sahu** [comment]
> > @hoangphuc1103 did you find anything? Did anybody find any solution?
> 
> Hi saadzarif, I'm still stuck with this issue, it seems that now I can't build flutter app on old MacOS

did you find anything?.. i am also stuck.

**Comment by kimo** [comment]
> • Engine revision 74d16627b9
>     • Dart version 3.2.0
>     • DevTools version 2.28.2
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14C18
>     • CocoaPods version 1.11.3
> 
> darwin-arm64   • macOS 13.2.1 22D68 darwin-arm64

This worked for me on monterey 12.7.6 with Mac Pro 2016, as I am unable to upgrade the Xcode anymore.

**Comment by phucprime** [comment]
> > Download the newer version of Toolchain for Xcode; it worked for me like a charm!
> > https://www.swift.org/install/macos/
> 
> I have updated the toolchain and i get the same error.

Do not forget to pick the latest version of Toolchain after you've been updated.

<img width="720" alt="Screen Shot 2024-09-13 at 08 45 25" src="https://github.com/user-attachments/assets/f9284dff-7bfd-4ff2-9d2e-4089b63689fe">

**Comment by JiaoLiu** [comment]
> toolchain

I switched to the latest toolchain but get this error when try to debug on device。

<img width="260" alt="image" src="https://github.com/user-attachments/assets/3adb9f43-5015-46bf-bc18-4b7253ea2a46">

**Comment by einsitang** [comment]
same issue
