### ISSUE TITLE
How to use pod in aggregate target's build phase?

### ISSUE THREAD

**Issue by NikKovIos** [CocoaPods/CocoaPods#11972]
I have target 'Main' and aggregate target 'Script'. `Main` target contains all files and installed pods. 'Script' target contains only one build phase:

![image](https://github.com/CocoaPods/CocoaPods/assets/16647690/b72a9364-2886-4e76-88a9-063a71051539)

When I build target, it don't find pods. I tried to install in Podfile like

```
target 'Script' do
    pod 'Periphery', '= 2.14.1'
end
```
but it return error that aggregate target is not target and can't find it: `Unable to find a target named "Script" in project`

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by NikKovIos** [comment]
Opened here https://stackoverflow.com/questions/76590014/how-to-use-pod-in-aggregate-targets-build-phase
