### ISSUE TITLE
Build Failed , even after i downloaded everything still getting this error can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by webdSUNIL** [CocoaPods/CocoaPods#11989]
sunilpatra@sunils-MacBook-Pro rideapp % pod --version
Traceback (most recent call last):
        4: from /Users/sunilpatra/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `<main>'
        3: from /Users/sunilpatra/.rvm/gems/ruby-2.7.6/bin/ruby_executable_hooks:22:in `eval'
        2: from /Users/sunilpatra/.rvm/gems/ruby-2.7.6/bin/pod:25:in `<main>'
        1: from /Users/sunilpatra/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems.rb:282:in `activate_bin_path'
/Users/sunilpatra/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0/rubygems.rb:263:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)

when i do run in ios 
a - run on Android

info Opening the app on iOS...
info Found Xcode project "holycabs.xcodeproj"
info No booted devices or simulators found. Launching first available simulator...
info Launching iPhone SE (3rd generation) (iOS 16.4)
info Building (using "xcodebuild -project holycabs.xcodeproj -configuration Debug -scheme holycabs -destination id=A1011889-D492-4935-91A6-A1EB3E0CDF28")
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project holycabs.xcodeproj -configuration Debug -scheme holycabs -destination id=A1011889-D492-4935-91A6-A1EB3E0CDF28

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

Computing target dependency graph and provisioning inputs

Create build description
Build description signature: 560b024a3f892e109bd24c0fa9460803
Build description path: /Users/sunilpatra/Library/Developer/Xcode/DerivedData/holycabs-bvmmxwqdmkfuavejenuvxiajpeev/Build/Intermediates.noindex/XCBuildData/560b024a3f892e109bd24c0fa9460803.xcbuilddata

note: Building targets in dependency order
/Users/sunilpatra/Documents/GitHub/rideapp/ios/Pods/Target Support Files/Pods-holycabs/Pods-holycabs.debug.xcconfig:1:1: error: unable to open configuration settings file
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-holycabs/Pods-holycabs-frameworks-Debug-output-files.xcfilelist' (in target 'holycabs' from project 'holycabs')
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-holycabs/Pods-holycabs-resources-Debug-output-files.xcfilelist' (in target 'holycabs' from project 'holycabs')
error: Unable to load contents of file list: '/Target Support Files/Pods-holycabs/Pods-holycabs-frameworks-Debug-input-files.xcfilelist' (in target 'holycabs' from project 'holycabs')
error: Unable to load contents of file list: '/Target Support Files/Pods-holycabs/Pods-holycabs-frameworks-Debug-output-files.xcfilelist' (in target 'holycabs' from project 'holycabs')
warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'holycabs' from project 'holycabs')
warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'holycabs' from project 'holycabs')
error: Unable to load contents of file list: '/Target Support Files/Pods-holycabs/Pods-holycabs-resources-Debug-input-files.xcfilelist' (in target 'holycabs' from project 'holycabs')
error: Unable to load contents of file list: '/Target Support Files/Pods-holycabs/Pods-holycabs-resources-Debug-output-files.xcfilelist' (in target 'holycabs' from project 'holycabs')
warning: Run script build phase '[CP] Copy Pods Resources' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'holycabs' from project 'holycabs')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'holycabs' from project 'holycabs')

2023-07-09 14:47:01.244 xcodebuild[3634:35780] DVTCoreDeviceEnabledState: DVTCoreDeviceEnabledState_Disabled set via user default (DVTEnableCoreDevice=disabled)
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:A1011889-D492-4935-91A6-A1EB3E0CDF28, OS:16.4, name:iPhone SE (3rd generation) }
{ platform:iOS Simulator, id:A1011889-D492-4935-91A6-A1EB3E0CDF28, OS:16.4, name:iPhone SE (3rd generation) }
** BUILD FAILED **

info Run CLI with --verbose flag for more details.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
