### ISSUE TITLE
Xcode 15: Support Privacy Manifests?

### ISSUE THREAD

**Issue by phirk** [CocoaPods/CocoaPods#11990]
As of Xcode 15, Apple supports adding [Privacy Manifests](https://developer.apple.com/documentation/bundleresources/describing_data_use_in_privacy_manifests) to SDKs. We develop an SDK that consists of several components (frameworks) for which we would like to add a Privacy Manifest. That works fine for our local builds, but we distribute our SDK via CocoaPods, which generates a single framework with the sources of all our components. This single framework currently does not have a Privacy Manifest.

Would it be possible to support Privacy Manifests in CocoaPods?

(Merge all `PrivacyInfo.xcprivacy` files of components?)

**Comment by orta** [comment]
Lots of discussion here: https://github.com/CocoaPods/CocoaPods/issues/10325 - doesn't seem like there's been too much velocity on the issue, so I'd recommend appending anything new to that issue

**Comment by xygkevin** [comment]
Need to explicitly indicate NSPrivacyTracking=false via PrivacyInfoxc.privacy file

**Comment by ymoyao** [comment]
@phirk try cocoapods-privacy, https://github.com/ymoyao/cocoapods-privacy, if help to you , please star ~
