### ISSUE TITLE
Use of Library cocoapods-art with cocoapods 1.12.1 : Doesn't work without having a repo in ./cocoapods/repos

### ISSUE THREAD

**Issue by killianTrm** [CocoaPods/CocoaPods#11994]
We use the cocoapods-art library to reference Jfrog artifactory repository for pod install

Now since cocoapods 1.11 update to 1.12
We must have repository in .cocoapods/repos

In Podfile we specify the use of the following plugin
plugin 'cocoapods-art', :sources => [
‘REPO_JFROG’
]
We don't understand because we only use in Podfile ./cocoapods/repos-art/REPO_JFROG

Cocoapods-art: v1.1.0 (only change in my project it's cocoapods's version)
https://rubygems.org/gems/cocoapods-art/versions/1.1.0 

Can we conclude that using cocoapods-art is no longer necessary to point to a JFrog artifactory repository ?
Not work, if I want to add repo JFrog with command "pod repo add REPO_JFROG $urlRepoJfrog" 
Try to do a git clone and it's impossible on a JFrog's repository

**So "cocoapods-art" it's always necessary :**
gem install cocoapods-art
create a .netrc with credential
pod repo-art add REPO_JFROG $URLRepoJfrog

**But we must to clone the folder ./cocoapods/repos-art/ in ./cocoapods/repos/** 
And it's work

Why we must to do that with this version cocoapods ?

**Comment by orta** [comment]
This seems to be an issue for the repo of cocoapods-art, and not CocoaPods
