### ISSUE TITLE
pod install error in M1 macbook.

### ISSUE THREAD

**Issue by paavan-ansorbit** [CocoaPods/CocoaPods#12007]
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=cannot+load+such+file+--+ffi_c&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Cant install pods when generating new React native project
   https://github.com/CocoaPods/CocoaPods/issues/11641 [open] [18 comments]
   27 May 2023

 - pod install --repo-update with LoadError - cannot load such file -- ffi_c
   https://github.com/CocoaPods/CocoaPods/issues/10370 [closed] [3 comments]
   31 May 2021

 - pod install error in M1 macbook.
   https://github.com/CocoaPods/CocoaPods/issues/11042 [closed] [1 comment]
   05 Nov 2021

**Comment by orta** [comment]
This is just the template.
