### ISSUE TITLE
Unable to install the pod 'AWSAPIGateway', '~> 2.4.7' 

### ISSUE THREAD

**Issue by keerthikaitmit** [CocoaPods/CocoaPods#12017]
<img width="1512" alt="Screenshot 2023-07-31 at 8 51 34 AM" src="https://github.com/CocoaPods/CocoaPods/assets/6038007/a4fd31a9-234b-476d-8f05-04eb25f74f08">
<img width="1512" alt="Screenshot 2023-07-31 at 8 51 22 AM" src="https://github.com/CocoaPods/CocoaPods/assets/6038007/8958e543-eaf3-4562-973e-a94ea9613f47">
<img width="1512" alt="Screenshot 2023-07-31 at 8 51 14 AM" src="https://github.com/CocoaPods/CocoaPods/assets/6038007/c7b44e8d-120e-478b-869c-56443353841c">

Facing some issue kindly help me on this

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
