### ISSUE TITLE
Xcode 15 beta 8 any pod command crashes with error: Unknown object version (60).

### ISSUE THREAD

**Issue by JasurSalimov** [CocoaPods/CocoaPods#12043]
## What did you do?

ℹ Run pod install - it crashed on terminal.

## What did you expect to happen?

ℹ  Install all pod dependencies correctly.

## What happened instead?

ℹ  RuntimeError - [Xcodeproj] Unknown object version (60)
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:228:in `initialize_from_file'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:113:in `open'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1194:in `block (2 levels) in inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1193:in `each'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1193:in `block in inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:1188:in `inspect_targets_to_integrate'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer/analyzer.rb:107:in `analyze'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:422:in `analyze'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/installer.rb:162:in `install!'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.12.1/libexec/gems/cocoapods-1.12.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `load'
/usr/local/Cellar/cocoapods/1.12.1/libexec/bin/pod:25:in `<main>'
## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.5.1 (22G90)
       Xcode : 15.0 (15A5229m)
         Git : git version 2.38.1
Ruby lib dir : /usr/local/Cellar/ruby/3.2.2_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.12.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectName' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'JXBanner'
  pod 'JXPageControl'
  pod 'Wormholy', :configurations => ['Debug']
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SVProgressHUD'
  pod 'SwiftyStoreKit'
  
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end
```

**Comment by JasurSalimov** [comment]
I tried everything, pod deintegrate, install again, pod update, gem udpate xcodeproj and etc. Nothing helped. Temporary workaround is to change the objectVersion in xcodeproj file project.pbxproj to version which is less then  60 can be 54, or 56.

**Comment by tomcondon** [comment]
I have been using Xcode 15 b8 and CocoaPod 1.12.1 with the Podfile fix below and I have not seen any issues.

installer.pods_project.targets.each do |target|  
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings["DEVELOPMENT_TEAM"] = "XXXXXXXXX"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      # needed for Xcode 15, needs to be commented out for Xcode 14.3.1 (DT_TOOLCHAIN_DIR name has changed)
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

**Comment by JasurSalimov** [comment]
Do not know what exactly was the problem after reinstalling the xcode, it was fixed. so I am closing the issue myself.

**Comment by chrislconover** [comment]
I have this same error, but only in one of my projects, after installing Xcode 15 final, from Beta 8.

**Comment by chrislconover** [comment]
Can someone re-open this? this is an active bug, the same as all the others for objectVersion. 

Solution:
- Push a new tag of Cocoapods, for gem / homebrew to pull down, master should work fine.

Work around:
 - use old file format in Xcode 15

Context:
 - Xcode project using the latest "objectVersion" (Select project, then File inspector)
 - Cocoapods relies on the sub project Xcodeproj, which tracks its last known version in constants.rb.
 - Cocoapods on master, currently points to Xcodeproj 1.2.2 which knows the latest objectVersion (60), but the last tagged cocaopods version (1.12.1) precedes this, and so pulls the stale version of Xcoderproj (see Gem.lock).
 - Per the OP, cocoapods compares the observed Xcode object version (60) against the stale value of 56, and fails per above.
 
References:

Need a new tag: 
  - https://github.com/CocoaPods/CocoaPods/tags

Prior art: 
 - https://github.com/CocoaPods/Xcodeproj/pull/884
 
Current dependency will work
  - https://github.com/CocoaPods/CocoaPods/blob/master/Gemfile.lock
 
For objectVersion in constants.rb:
 - https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb
