### ISSUE TITLE
pod lib lint error

### ISSUE THREAD

**Issue by Goallying** [CocoaPods/CocoaPods#12041]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run 'pod lib lint'

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
No error .

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
pod lib lint error.

 The following build commands failed:
    	Ld /glgl/admin/Library/Developer/Xcode/DerivedData/App-crixbtqxoxixxwgphptvwbrwsxfq/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Hydra_iOS.build/Objects-normal/arm64/Binary/Hydra_iOS normal arm64 (in target 'xxx' from project 'Pods')

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]
    RubyGems : 3.2.16
        Host : macOS 13.2.1 (22D68)
       Xcode : 14.3.1 (14E300c)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ e6f0a6ce9dc0e8a9d9b6f0d6409513701d8ba128

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
