### ISSUE TITLE
Issue loading images on the latest Xcode 15 (all betas + release candidate ) on tests

### ISSUE THREAD

**Issue by StefiGx** [CocoaPods/CocoaPods#12051]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

## The issue

I am having an issue when running unit tests on the latest Xcode Release candidate. When running pod install all the development repos get installed properly but  the images (in module's.xcassets) are not being loaded when running tests. When trying to load an image the bundle is retrieved correctly and the assets.car file is there, but the image fails to load either way. 

In the .podspec file I have:` s.resource_bundles = { /path of resources/ }.` This issues seems to be affecting only tests.
I am using the latest release for the [cocoa pods 1.12.1](https://github.com/CocoaPods/CocoaPods/releases/tag/1.12.1) I also tried the [Xcode 15 fix commit](https://github.com/CocoaPods/CocoaPods/pull/12009) of the library but the issue is persistent. 

You can clearly see this issue in the attached example project. Here I am using as an example an external pod from 'ProcessOut'. In the Asstes+Generated file in the library if you set to public:

- enum Asset
- enum Images + the static values inside
- struct ImageAsset + typealias Image + var image: Image {

And afterwards run the tests they will crash as the image cannot be load. We're experiencing the issue of images not loading on running unit tests with all the pods that are not static and or don't have s.resources set. 

[TestingImages.zip](https://github.com/CocoaPods/CocoaPods/files/12648353/TestingImages.zip)

**Comment by JohnEstropia** [comment]
Seeing this issue as well. The podspec which declares an `xcdatamodeld` resource within the `test_spec` seem to not be working now, and `pod lib lint` (etc) fails as a result.

**Comment by angelstoone** [comment]
It seems that issue #11184 was related therefore we fixed it by changing the name of the resource bundle exposed by the development pods (that was "colliding" with the development pods' name)

**Comment by Buju77** [comment]
> It seems that issue #11184 was related therefore we fixed it by changing the name of the resource bundle exposed by the development pods (that was "colliding" with the development pods' name). Given that it is solved how about closing the issue @StefiGx 😄 🎉 ?

@angelstoone can you please point me to the commit/branch/PR where this was fixed as you mentioned? I would like to see the changes to the fix 🙏
