### ISSUE TITLE
Multiple Project pod shell run failed 

### ISSUE THREAD

**Issue by lyb5834** [CocoaPods/CocoaPods#12073]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
```
create a multiple project then pod install
if package exist bundle or set use_frameworks! 
Xcode-Product-Run
```
## Podfile content
```
 platform :ios, '11.0'

workspace 'MultipleProjectDemo.xcworkspace'

#use_frameworks!
#use_modular_headers!

def commonPods
  
  pod 'GKNavigationBarSwift'
end

# project one
target 'MultipleSubProjectOne' do
  project 'subProjects/MultipleSubProjectOne/MultipleSubProjectOne.xcodeproj'
  commonPods
end

# project two
target 'MultipleSubProjectTwo' do
  project 'subProjects/MultipleSubProjectTwo/MultipleSubProjectTwo.xcodeproj'
  commonPods
end
```

## What did you expect to happen?
`Run success`

## What happened instead?
```
/Users/mac/Documents/iOSTest/MultipleProjectDemo/subProjects/MultipleSubProjectOne/../../Pods/GKNavigationBarSwift/Sources/GKNavigationBarSwift.bundle
building file list ... done
GKNavigationBarSwift.bundle/btn_back_black@2x.png
GKNavigationBarSwift.bundle/btn_back_black@3x.png
GKNavigationBarSwift.bundle/btn_back_white@2x.png
GKNavigationBarSwift.bundle/btn_back_white@3x.png
GKNavigationBarSwift.bundle/nav_line.png
GKNavigationBarSwift.bundle/nav_line@2x.png
GKNavigationBarSwift.bundle/nav_line@3x.png
rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.btn_back_black@2x.png.U8VS0E" failed: Operation not permitted (1)
rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.btn_back_black@3x.png.IY4E76" failed: Operation not permitted (1)
rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.btn_back_white@2x.png.CLf1Ue" failed: Operation not permitted (1)
rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.btn_back_white@3x.png.vGTU7i" failed: Operation not permitted (1)
rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.nav_line.png.eHNMUF" failed: Operation not permitted (1)
rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.nav_line@2x.png.OrfHlY" failed: Operation not permitted (1)
rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.nav_line@3x.png.EY5P9W" failed: Operation not permitted (1)

sent 5739 bytes  received 174 bytes  11826.00 bytes/sec
total size is 5173  speedup is 0.87
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/d9889869-120b-11ee-b796-7a03568b17ac/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
realpath: illegal option -- m
usage: realpath [-q] [path ...]
:107: error: Unexpected failure
```

## CocoaPods Environment

```
   CocoaPods : 1.13.0
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.5.2 (22G91)
       Xcode : 15.0 (15A240d)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /usr/local/Cellar/ruby/3.2.2_1/lib
Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ 4f06e297b7759974f184c718c2a7b9f760706f32

               artsy - git - https://github.com/Artsy/Specs.git @ c416b392ce39204d47ad48f34c02cfb94dc98982

               master - git - https://github.com/CocoaPods/Specs.git @ 76c02a9ce2003e3e584f9d5f82c43d60786dfed3

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.13.0/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue
[MultipleProjectDemo.zip](https://lyb5834.github.io/files/MultipleProjectDemo.zip)

**Comment by dnkoutso** [comment]
Seems like a permission issue `rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.nav_line@3x.png.EY5P9W" failed: Operation not permitted (1)
`

**Comment by lyb5834** [comment]
> Seems like a permission issue `rsync: mkstemp "/Users/mac/Library/Developer/Xcode/DerivedData/MultipleProjectDemo-bvjrlqhcsuitwjedlxeevsttmdsg/Build/Products/Debug-iphoneos/MultipleSubProjectOne.app/GKNavigationBarSwift.bundle/.nav_line@3x.png.EY5P9W" failed: Operation not permitted (1) `

any solutions?

**Comment by dnkoutso** [comment]
Not sure give permission to that folder.

**Comment by dnkoutso** [comment]
Going to close as it does not seem a cocoapods library issue.

**Comment by ryancornia** [comment]
FWIW: I have the same issue with XCode 15 on a project that was working correctly previous in XCode 14. I still haven't found a solution, but don't believe it is a permissions issue. I have updated to the latest cocoapods. The commands work fine from the command line, and the directory/sub-directory permissions are correct. Adding my experience here in case others run into this and find a solution to share.

**Comment by ryancornia** [comment]
Solved this on my project. In Build Settings, make sure ENABLE_USER_SCRIPT_SANDBOXING is set to NO.

**Comment by meilbn** [comment]
> Solved this on my project. In Build Settings, make sure ENABLE_USER_SCRIPT_SANDBOXING is set to NO.

Thanks, you saved my day! It's worked for me.

**Comment by lyb5834** [comment]
> Solved this on my project. In Build Settings, make sure ENABLE_USER_SCRIPT_SANDBOXING is set to NO.

perfect!  @dnkoutso Hi, i think the issue is solved and I suggest it's worth a PR to fix it

**Comment by nilesh14panamx** [comment]
> Solved this on my project. In Build Settings, make sure ENABLE_USER_SCRIPT_SANDBOXING is set to NO.

Not working for me.

**Comment by unitedapps20** [comment]
> Solved this on my project. In Build Settings, make sure ENABLE_USER_SCRIPT_SANDBOXING is set to NO.

also not working for me 
my app is build succeed ,they can run good but  give me the issue  if I can  archive

**Comment by kartikthakur2022** [comment]
+1

**Comment by davpirelli** [comment]
> > Solved this on my project. In Build Settings, make sure ENABLE_USER_SCRIPT_SANDBOXING is set to NO.
> 
> also not working for me my app is build succeed ,they can run good but give me the issue if I can archive

Same here. Ok for archiving, building, running on physical device / simulator but not when archiving

**Comment by dhermanns** [comment]
Same here :(

**Comment by edudnyk** [comment]
For me it helped to set `ENABLE_USER_SCRIPT_SANDBOXING = NO` in the app target build settings.

**Comment by archmagees** [comment]
> Solved this on my project. In Build Settings, make sure ENABLE_USER_SCRIPT_SANDBOXING is set to NO.

You really saved my life~~~ Thanks a lot!!!

**Comment by DomenicaPomeriggio** [comment]
> Solved this on my project. In Build Settings, make sure ENABLE_USER_SCRIPT_SANDBOXING is set to NO.

Thanks a lot!!!

**Comment by ehsan6sha** [comment]
This is not the bst solution as there are some cases that sandboxing needs to be YES like using crashlytics. Any other solution?
