### ISSUE TITLE
source code for your pod was not accessible to cocoapods trunk. is it a private repo or behind a username/password on http?

### ISSUE THREAD

**Issue by nadeemworkspacelulu** [CocoaPods/CocoaPods#12074]
Getting this error on pod trunk push  --allow-warnings

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
