### ISSUE TITLE
Please fix Twilio project ownership issues

### ISSUE THREAD

**Issue by futurealecks** [CocoaPods/CocoaPods#12085]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Twilio devs using CocoaPods can no longer update their projects due to CocoaPods incorrectly removed the ownership of this project from Twilio.

**_This is a plea for two organizations (Twilio and Cocoapods) to figure this out._**

https://www.twilio.com/docs/video/changelog-twilio-video-ios-latest#560-march-28-2023
https://github.com/twilio/twilio-video-ios/issues/260

**Comment by orta** [comment]
Sure  - I couldn't find any requests from them asking to fix this, but I've added ios-sdks@twilio.com to that pod
