### ISSUE TITLE
Unknown type name 'namespace' in umbrella-header.h that include cpp headers

### ISSUE THREAD

**Issue by Alexufo** [CocoaPods/CocoaPods#12105]
I am trying to compile a swift project with my pod. My pod contains binary libs and c++ wrapper for them.
I have successfully created the pod for the default objc project and everything works fine.

Then I try to integrate my pod into the default swift project in the same way and I get

![image](https://github.com/CocoaPods/CocoaPods/assets/1562329/c02cd3e1-1120-4404-8611-1932813077d7)

I remove "import myModule" from swift (the project starts compiling without errors) and put bridge-header.h. After that I can access my pod, but I don't want to use bridge-header.h Is it possible?

**Comment by ospfranco** [comment]
Did you find a solution for this?

**Comment by Alexufo** [comment]
> Did you find a solution for this?

No. A bit hacky. I change parent project. 

```This config set bridge-header in parent project.
 s.xcconfig = { "SWIFT_OBJC_BRIDGING_HEADER" => "${PODS_CONFIGURATION_BUILD_DIR}/Name/Name.framework/Headers/Name-Bridging-Header.h"}

 ```
 Bridge header will be avalable in xcode after first build.

**Comment by ospfranco** [comment]
I found the issue. Whenever you have a Swift source together with C++ sources, XCode will try to compile the headers as C headers and not C++ independently of what you tell it. Don't know if this is an issue with CocoaPods or XCode itself, but here is the workaround I found:

```ruby
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name           = "matrix"
  s.version        = package["version"]
  s.summary        = package["description"]
  s.homepage       = package["homepage"]
  s.license        = package["license"]
  s.authors        = package["author"]
  s.platforms      = { :ios => "13.0" }

  s.pod_target_xcconfig = {
    "DEFINES_MODULE" => "YES",
    "SWIFT_COMPILATION_MODE" => "wholemodule",
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++17",
    "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/cpp/\"/** " # This will link the headers at compile time, flag passed directly to the compiler
  }

  s.source_files = "ios/**/*.{mm,swift}", "cpp/**/*.{cpp,c}" # Do not include the headers in the sources, then XCode won't try to compile them

  s.preserve_paths = [
    "cpp/**/*.h",
    "ios/**/*.h"
  ]
  
  s.dependency "React"
  s.dependency "React-Core"
  s.dependency "React-callinvoker"
end
```

By not including the headers in `source_files` XCode does not try to compile them, but by adding them to the HEADER_SEARCH_PATHS they are still found on the linking step of the compilation.

One side effect is that the headers will not appear on the project explorer view on XCode but 🤷

**Comment by Alexufo** [comment]
Thanks. My working pod is

```ruby
Pod::Spec.new do |s|
  s.name             = 'Id'
  s.version          = '0.1.0'
  s.summary          = 'Swift pod'
  s.homepage         = 'https://'

  s.source           = { :path => './' }
  
  s.ios.deployment_target = '11.0'
  s.frameworks = 'UIKit', 'Foundation','AVFoundation' , 'CoreVideo', 'CoreGraphics', 'CoreMedia'
  
  s.ios.resources = 'Core/data'
  s.ios.vendored_frameworks = 'Core/lib/*.xcframework'
  
  s.xcconfig = {
    'SWIFT_OBJC_BRIDGING_HEADER' => '$(PODS_ROOT)/../S/S-Bridging-Header.h',
    'HEADER_SEARCH_PATHS' =>
    '$(PODS_ROOT)/../Core/wrap/objcs/include ' +
    '$(PODS_ROOT)/../Core/wrap/objcs/include_impl ' +
    '$(PODS_ROOT)/../Core/wrap/objci/include ' +
    '$(PODS_ROOT)/../Core/wrap/objci/include_impl ' +
    '$(PODS_ROOT)/../Core/include'
  }

  s.pod_target_xcconfig = {  
    "DEFINES_MODULE" => "YES",
    'ENABLE_BITCODE' => "NO",
    'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386'
  }
  
  s.subspec 'Core' do |h|
    h.source_files =  "Core/wrap/**/*.{mm,h}", "Core/include/**/*.{mm,h}"
    h.header_mappings_dir = './'
  end
  
  s.subspec 'S' do |w|
    w.source_files =  "S/**/*.{mm,h}"
  end
  
end

```
`preserve_paths` doesn't work for me. If I ignore the *.h, they won't be copied to the build folder. If I move xcconfig to pod_target_xcconfig, I get the problem I wrote about earlier

**Comment by Alexufo** [comment]
@ospfranco  It works as you describe.Thank you. 

To convert the integration from `*-Bridging-Header.h` to ios framework ( use_framework! in PodFile )

I had to do 3 things:

1. Add to podspec only those headers that are specified in `*-Bridging-Header.h.`

*-Bridging-Header.h:
```
#import "Instance.h"
#import "Controller.h"
```

Podspec:
``` 
  s.source_files = 'Core/**/*.{mm}', 'Core/sources/Controller.h', 'Core/sources/Instance.h', 
  s.public_header_files = 'Core/sources/*.h'
```

2. Enable `'DEFINES_MODULE' => 'YES'`. In this case `module_map` is generated, which is a full analog of `*-Bridging-Header.h` 
( `import yourPodLib` in swift file allows you to see the interface of your pod)
```
  s.pod_target_xcconfig = {  
    'DEFINES_MODULE' => 'YES',
  } 
```        
3. When compiling, there is an error of missing cpp headers. The path to the necessary headers is specified by a 

```
  s.pod_target_xcconfig = {  
      'HEADER_SEARCH_PATHS' => [
      '$(PODS_TARGET_SRCROOT)/private_cpp',
    ],
  } 
```
And all works.

**Comment by ospfranco** [comment]
No, no idea, just found a configuration that works.

**Comment by Alexufo** [comment]
ok. I did it

'include/cppheaders' - folder with cpp headers

```ruby
Pod::Spec.new do |s|
  s.name             = 'test'
  s.version          = '0.0.1'
  s.summary          = 'lib'
  s.homepage         = ''
  s.source           = { :git => 'http://localhost:3000/giteagitea/test.git', :tag => s.version.to_s }
  s.swift_versions   = ['5.0'] 
  s.ios.deployment_target = '13.0'

# copy folder inside framework
 s.ios.resources = ['include/*']

  s.xcconfig= {  
     'HEADER_SEARCH_PATHS' => [
       "'${PODS_CONFIGURATION_BUILD_DIR}/#{s.name}/#{s.name}.framework/cppheaders'",
     ]
  }

  s.pod_target_xcconfig = {  
     'HEADER_SEARCH_PATHS' => [
       '$(PODS_TARGET_SRCROOT)/include/cpp_headers',
     ], 
  }
  ```
