### ISSUE TITLE
Just enterd pod install but they show me this error

### ISSUE THREAD

**Issue by Haris259** [CocoaPods/CocoaPods#12108]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.
<img width="1254" alt="Screenshot 2023-10-25 at 12 33 17 PM" src="https://github.com/CocoaPods/CocoaPods/assets/61193489/49f63d0f-e315-45cf-a06f-2dd9f3ed5c5a">

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by orta** [comment]
I'd recommend reading the error message, and acting on that - this screenshot doesn't even include the message.
