### ISSUE TITLE
Invalid path to .podspec.json

### ISSUE THREAD

**Issue by aserrr** [CocoaPods/CocoaPods#12128]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Missing podspec

## CocoaPods Environment

[myTrackerSDK](https://cocoapods.org/pods/myTrackerSDK)
Link to podspec looks like:
/CocoaPods/Specs/blob/master/Specs/["a",%20"8",%20"3",%20"myTrackerSDK",%20<Pod::Version%20version=3.1.0>]/myTrackerSDK.podspec.json

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
