### ISSUE TITLE
How to `debug` the custom `iOS Project Podfile` that auto generated by cocoapods `in IDE such as Vscode`

### ISSUE THREAD

**Issue by LongXiangGuo** [CocoaPods/CocoaPods#12129]
### This feature is VS Code specific

- [X] VS Code specific

### Use case

In most cases, we need to modify the Podfile to implement different logic for iOS project, so if we could add some configurations to the  IDE(Such as vscode) debug the Podfile directly, it will be more effective for coding.

```
    {
      "type": "ruby_lsp",
      "request": "launch",
      "name": "Podifle Debug",
      "program": "cd path/to/ios/project && pod install --verbose",
    },
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
