### ISSUE TITLE
Not received email for `pod trunk register`.

### ISSUE THREAD

**Issue by kober32** [CocoaPods/CocoaPods#12130]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod trunk register jan@kobersky.eu 'Jan Kobersky'`

## What did you expect to happen?

Receive an email with a login link.

## What happened instead?

No email was received (tried several times).

The following response was retrieved with `--verbose switch`

```
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.3, cipher: TLS_AES_128_GCM_SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.14.2\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 68\r\n\r\n"
<- "{\"email\":\"jan@kobersky.eu\",\"name\":\"Jan Kobersky\",\"description\":null}"
-> "HTTP/1.1 201 Created\r\n"
-> "Server: Cowboy\r\n"
-> "Date: Tue, 31 Oct 2023 11:20:56 GMT\r\n"
-> "Report-To: {\"group\":\"heroku-nel\",\"max_age\":3600,\"endpoints\":[{\"url\":\"https://nel.heroku.com/reports?ts=1698751256&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=QHpNuN47z4AzIDynuk3XGBz8Jp08LOyH2xo4EikZp0o%3D\"}]}\r\n"
-> "Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1698751256&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=QHpNuN47z4AzIDynuk3XGBz8Jp08LOyH2xo4EikZp0o%3D\r\n"
-> "Nel: {\"report_to\":\"heroku-nel\",\"max_age\":3600,\"success_fraction\":0.005,\"failure_fraction\":0.05,\"response_headers\":[\"Via\"]}\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Content-Length: 192\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 192 bytes...
-> "{\"created_at\":\"2023-10-31 11:20:56 UTC\",\"valid_until\":\"2024-03-07 11:20:56 UTC\",\"verified\":false,\"created_from_ip\":\"78.80.25.113\",\"description\":null,\"token\":\"7becabe4ed104bdf808XXXXXXXXX\"}"
read 192 bytes
Conn keep-alive
```

### Stack

```
   CocoaPods : 1.14.2
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 14.1 (23B74)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.14.2/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

--------

Is my custom domain on some kind of a blacklist? I received emails from cocoapods 2 months ago without any problems. I'm the only maintainer of the library - is there any process how to transfer the ownership to my other mail?

Thanks

**Comment by orta** [comment]
Yep, something was up with your mailserver back in october, we have about 20 of:

> unable to get mx info: failed to get IPs from PTR record: lookup <nil>: unrecognized address

I've removed the blocks on our side, should be fine now

**Comment by joaquinsfy** [comment]
i' m having the same issue, not receiving email from no-reply@cocoapods.org

 pod trunk register joaquinc@sfy.com --verbose
 any address from our domain .sfy.com doesn't work, I removed all the spam filters.
 with an address of gmail, works fine, but I can't add owner because I can't authenticate.
 
 maybe our domain sfy.com it's in your blacklist?
 
 Thanks
