### ISSUE TITLE
firebase_core & firebase_messaging not compitable with cocoapods

### ISSUE THREAD

**Issue by enjat26** [CocoaPods/CocoaPods#12134]
Please help me, now I used firebase_core: ^2.20.0 & firebase_messaging: ^14.7.2 with platform :ios, 12.0, if package firebase_core &firebase_messaging remove form pubspec.yaml it work no problem

I was trying 
- sudo arch -x86_64 gem install ffi
- arch -x86_64 pod repo update
- arch -x86_64 pod install
but now not working, usually working for me.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
