### ISSUE TITLE
Not received email for pod trunk register.

### ISSUE THREAD

**Issue by atom-sdk** [CocoaPods/CocoaPods#12141]
* [Yes ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk register developer@atomapi.com 'Atom By Secure.com'  --description='Pure Dev Macbook' --verbose`

## What did you expect to happen?

Receive an email with a login link.

## What happened instead?

No email was received (tried several times).

The following response was retrieved with --verbose

`opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.3, cipher: TLS_AES_128_GCM_SHA256
<- "POST /api/v1/sessions HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.12.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 94\r\n\r\n"
<- "{\"email\":\"developer@atomapi.com\",\"name\":\"Atom By Secure.com\",\"description\":\"Pure Dev Macbook\"}"
-> "HTTP/1.1 201 Created\r\n"
-> "Server: Cowboy\r\n"
-> "Date: Mon, 06 Nov 2023 09:25:24 GMT\r\n"
-> "Report-To: {\"group\":\"heroku-nel\",\"max_age\":3600,\"endpoints\":[{\"url\":\"https://nel.heroku.com/reports?ts=1699262724&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=qFyYSA1l0AA8xXEcAhej2z06eSi55l11%2FFFAjSAiK2E%3D\"}]}\r\n"
-> "Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1699262724&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=qFyYSA1l0AA8xXEcAhej2z06eSi55l11%2FFFAjSAiK2E%3D\r\n"
-> "Nel: {\"report_to\":\"heroku-nel\",\"max_age\":3600,\"success_fraction\":0.005,\"failure_fraction\":0.05,\"response_headers\":[\"Via\"]}\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Content-Length: 208\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 208 bytes...
-> "{\"created_at\":\"2023-11-06 09:25:24 UTC\",\"valid_until\":\"2024-03-13 09:25:24 UTC\",\"verified\":false,\"created_from_ip\":\"110.93.230.236\",\"description\":\"Pure Dev Macbook\",\"token\":\"e3603f01557a51ddf710883a5cbbd080\"}"
read 208 bytes
Conn keep-alive`

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [arm64-darwin21]
    RubyGems : 3.1.6
        Host : macOS 14.0 (23A344)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /Users/muneebsiddique/.rbenv/versions/2.7.3/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ fef71c8d5918173827b82459d240448a231bba8c

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/muneebsiddique/.rbenv/versions/2.7.3/bin/pod
```

### Plugins

```
cocoapods-acknowledgements : 1.3.0
cocoapods-deintegrate      : 1.0.5
cocoapods-keys             : 2.2.1
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.1
cocoapods-trunk            : 1.6.0
cocoapods-try              : 1.2.0
slather                    : 2.7.2
```

## Project that demonstrates the issue

We have been using this command for the last two years without any problem. The domain atomapi.com is not on the blacklist https://multirbl.valli.org/lookup/atomapi.com.html 

This is urgent, we need your support.

**Comment by orta** [comment]
Deleted the bounce request on this email address again 👍🏻
