### ISSUE TITLE
Can not receive CocoaPods verification email

### ISSUE THREAD

**Issue by ccyanfa** [CocoaPods/CocoaPods#12144]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

 Run `pod trunk register zhaowl@bokecc.com`

## What did you expect to happen?

Receive a verification email.

## What happened instead?

Can not receive any verification email.

## CocoaPods Environment

CocoaPods : 1.10.1
Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [×86_64-darwin19]
RubyGems : 3.0.4
Host: Mac OS X 10.15.7 (19H2026)
Xcode : 12.4 (12D4e)
Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/mac/.rvm/rubies/ruby-2.6.3/lib
Repositories: trunk - CDN - https://cdn.cocoapods.org/
t--t/rots.uns:shuo..o/t/Cocoes/soce.dr e 68206760
tuna - git - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git Q 6a0828eb7be10871446862ee33923988fd733bde

**Comment by iOSliu** [comment]
@segiddins @dnkoutso I really need your help with the above problem.

**Comment by orta** [comment]
Deleted the bounce request on this email 👍🏻
