### ISSUE TITLE
pod lib lint error

### ISSUE THREAD

**Issue by chunxige** [CocoaPods/CocoaPods#12168]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
`pod lib lint --allow-warnings --verbose`

 
ℹ what happened instead.  
`The following build commands failed:
    	Ld /Users/gechunxi/Library/Developer/Xcode/DerivedData/App-guehtnvupvnlgnddzdiedncrpowu/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/pop.build/Objects-normal/x86_64/Binary/pop normal x86_64 (in target 'pop' from project 'Pods') `

## CocoaPods Environment
`/usr/local/bin/pod ,  version:  1.14.3` 

## Project that demonstrates the issue
[MyLib.zip](https://github.com/CocoaPods/CocoaPods/files/13486279/MyLib.zip)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
