### ISSUE TITLE
Help with Undefined symbols on Xcode

### ISSUE THREAD

**Issue by konguele** [CocoaPods/CocoaPods#12164]
Good Morning,

I created my game in Gdevelop and when I use Cordova and CocoaPods, I get the following error on Xcode. It has the necessary frameworks (at least it has downloaded them correctly) and I see that they are arm64. Could you help me?

Gdevelop version: 5.2.176
Cordova Version: 12.0.0 (Cordova-lib@12.0.1)
Cocoapods version: 1.14.3

Thank you very much!

ld: Undefined symbols:
  _GULIsLoggableLevel, referenced from:
      -[APMMonitor isLoggableLevel:] in GoogleAppMeasurement[arm64][66](APMMonitor.o)
  _GULLogBasic, referenced from:
      -[APMASLLogger logMessage:logTag:messageCode:withLogLevel:] in GoogleAppMeasurement[arm64][11](APMASLLogger.o)
  _GULLogError, referenced from:
      -[APMPersistentDictionary initWithFileName:] in GoogleAppMeasurement[arm64][223](APMPersistentDictionary.o)
      _APMWriteDictionaryToURL in GoogleAppMeasurement[arm64][223](APMPersistentDictionary.o)
      -[APMUserDefaults synchronize] in GoogleAppMeasurement[arm64][274](APMUserDefaults.o)
  _GULLogInfo, referenced from:
      ___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement[arm64][291](UIViewController+APMScreenClassName.o)
  _GULLogWarning, referenced from:
      +[APMMeasurement sharedInstance] in GoogleAppMeasurement[arm64][61](APMMeasurement.o)
      -[APMPersistentDictionary objectForKey:] in GoogleAppMeasurement[arm64][223](APMPersistentDictionary.o)
      -[APMPersistentDictionary setObject:forKey:] in GoogleAppMeasurement[arm64][223](APMPersistentDictionary.o)
      -[APMUserDefaults objectForKey:] in GoogleAppMeasurement[arm64][274](APMUserDefaults.o)
      -[APMUserDefaults setObject:forKey:] in GoogleAppMeasurement[arm64][274](APMUserDefaults.o)
      -[APMUserDefaults synchronize] in GoogleAppMeasurement[arm64][274](APMUserDefaults.o)
      ___44+[UIViewController(APMScreenClassName) load]_block_invoke in GoogleAppMeasurement[arm64][291](UIViewController+APMScreenClassName.o)
      ...

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by ash737** [comment]
I have same issue, any update here?
