### ISSUE TITLE
Static and Dynamic Libraries not works together

### ISSUE THREAD

**Issue by shuftipro** [CocoaPods/CocoaPods#12172]
I'm currently working on a React Native project that involves the use of multiple Pods. However, I'm encountering an issue when attempting to run the project in Xcode.

The problem lies in the fact that some of my pods are linked statically, such as "glog," while others are linked dynamically, like "Shuftipro." I've attempted various approaches to use both types of linking, but I haven't found a viable solution yet.

In the provided Podfile below, I've configured the linkage to be static, causing all pods to be linked statically. However, my intention is to link "Socket.IO" dynamically because setting it to link dynamically individually allows it to work, while the static linkage causes issues with other pods.

If i use linkage = 'dynamic' my project working fine but with this my static dependencies not work so i want to use static at root level and link dynamic few libraries.

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
linkage = 'static'
if linkage != nil
 Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
 use_frameworks! :linkage => linkage.to_sym
end

# use_frameworks!
# linkage = 'dynamic'
# Pod::UI.puts "Here is USE_FRAMEWORKS #{linkage}ally linked Frameworks".red
# if linkage != nil
# Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
# use_frameworks! :linkage => linkage.to_sym
# end


target 'testshufti' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
#   :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'testshuftiTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.aggregate_targets.each do |target|
          target.xcconfigs.each do |variant, xcconfig|
          xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
          end
      end
    
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
              xcconfig_path = config.base_configuration_reference.real_path
              IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
          end
    
          if ['Socket.IO-Client-Swift', 'Starscream'].include? target.name
              config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          end
        end
      end
    end
  end
```
 
 XCode RunTime Error
 
<img width="1102" alt="Screenshot 2023-12-06 at 10 36 24 AM" src="https://github.com/CocoaPods/CocoaPods/assets/34159299/0d295df9-f51b-42bf-89eb-2c214c04bb91">

**Comment by shuftipro** [comment]
@dnkoutso Need your help to fix this metter.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by shuftipro** [comment]
@orta I already posted on StackOverFlow but no progress.
Can you please help to fix this matter.
My simple problem is in my react native project in iOS i want to use both static and dynamic linkage.
https://stackoverflow.com/questions/77604466/static-and-dynamic-pods-not-work-simultaneously-in-podfile-react-native

**Comment by Pradip-Shelake** [comment]
I have got same issue , my existing app is statically linked , I want to integrate hid origo sdk which require dynamic linkage . Have you resolved issue ? If yes please reply it really means to me.

**Comment by AyushBharadwaj** [comment]
Hey! 👋 I’m encountering the same issue.

I'm manually adding .xcframework files to my React Native TurboModule package. However, when I try to integrate this package into a sample app and run pod install, I get the following error:

"Generating Pods project
[!] Unable to install vendored xcframework `ffmpegkit` for Pod `truvideo-react-turbo-video-sdk`, because it contains both static and dynamic frameworks."
All the .xcframework files I'm using (including ffmpegkit) contain only dynamically linked shared libraries across all architectures. I've verified this using the file command.

Here’s a list of the frameworks included:

ffmpegkit.xcframework
libavutil.xcframework
libswresample.xcframework 
libavutil.xcframework 
libavformat.xcframework
libavfilter.xcframework 
libavdevice.xcframework

**Comment by Pradip-Shelake** [comment]
I have resolved this issue by manually adding sdk .xcframework to xcode .
Add . xcframework in build phases under copy bundle resources. And then you can use.
