### ISSUE TITLE
Something went wrong running `pod install` in the `ios` directory.

### ISSUE THREAD

**Issue by oza-27** [CocoaPods/CocoaPods#12199]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I am trying to run my react native application in ios by writing command 'npx expo run:ios' it says that couldn't install pods. 
i am not be able to install boost.
ℹ Please replace these two lines with what you did.  
e.g. Run `cd ios`
`pod install`

## What did you expect to happen?
Install all dependencies

ℹ Please replace these two lines with what you expected to happen.  
e.g.  It will install all packages using `pod install`

## What happened instead?
Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Oh no, an error occurred.

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. ### Stack

```
   CocoaPods : 1.14.3
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]
    RubyGems : 3.5.3
        Host : macOS 14.1.2 (23B92)
       Xcode : 15.1 (15C65)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /Users/revords/.rbenv/versions/3.2.2/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/revords/.rbenv/versions/3.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```
## Project that demonstrates the issue
Expo] Enabling modular headers for pod ExpoModulesCore
Auto-linking React Native modules for target `myapp`: BVLinearGradient, RNCAsyncStorage, RNCPicker, RNGestureHandler, RNPermissions, RNScreens, react-native-geolocation, react-native-geolocation-service, react-native-image-picker, react-native-maps, react-native-safe-area-context, react-native-simple-toast, react-native-splash-screen, and react-native-video
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Pre-downloading: `Google-Maps-iOS-Utils` from `https://github.com/Simon-TechForm/google-maps-ios-utils.git`, commit `35d05d1eeb65682c1b271f4f3760d814fd946aa1`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using the release tarball from Maven Central
Downloading dependencies
Installing BVLinearGradient (2.8.3)
Installing DoubleConversion (1.1.6)
Installing EXApplication (5.3.1)
Installing EXConstants (14.4.2)
Installing EXFileSystem (15.4.4)
Installing EXFont (11.4.0)
Installing EXLocation (16.1.0)
Installing Expo (49.0.13)
Installing ExpoKeepAwake (12.3.0)
Installing ExpoLinearGradient (12.3.0)
Installing ExpoModulesCore (1.5.11)
Installing FBLazyVector (0.72.6)
Installing FBReactNativeSpec (0.72.6)
Installing Google-Maps-iOS-Utils (4.1.0)
Installing GoogleMaps (7.4.0)
Installing RCT-Folly (2021.07.22.00)
Installing RCTRequired (0.72.6)
Installing RCTTypeSafety (0.72.6)
Installing RNCAsyncStorage (1.18.2)
Installing RNCPicker (2.4.10)
Installing RNGestureHandler (2.12.1)
Installing RNPermissions (3.10.1)
Installing RNScreens (3.22.1)
Installing React (0.72.6)
Installing React-Codegen (0.72.6)
Installing React-Core (0.72.6)
Installing React-CoreModules (0.72.6)
Installing React-NativeModulesApple (0.72.6)
Installing React-RCTActionSheet (0.72.6)
Installing React-RCTAnimation (0.72.6)
Installing React-RCTAppDelegate (0.72.6)
Installing React-RCTBlob (0.72.6)
Installing React-RCTImage (0.72.6)
Installing React-RCTLinking (0.72.6)
Installing React-RCTNetwork (0.72.6)
Installing React-RCTSettings (0.72.6)
Installing React-RCTText (0.72.6)
Installing React-RCTVibration (0.72.6)
Installing React-callinvoker (0.72.6)
Installing React-cxxreact (0.72.6)
Installing React-debug (0.72.6)
Installing React-hermes (0.72.6)
Installing React-jsi (0.72.6)
Installing React-jsiexecutor (0.72.6)
Installing React-jsinspector (0.72.6)
Installing React-logger (0.72.6)
Installing React-perflogger (0.72.6)
Installing React-rncore (0.72.6)
Installing React-runtimeexecutor (0.72.6)
Installing React-runtimescheduler (0.72.6)
Installing React-utils (0.72.6)
Installing ReactCommon (0.72.6)
Installing SocketRocket (0.6.1)
Installing Toast (4.0.0)
Installing Yoga (1.14.0)
Installing boost (1.76.0)

[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff

**Comment by paulb777** [comment]
The error looks related to boost or React Native and not CocoaPods.

**Comment by oza-27** [comment]
Yes. So, is there any solution??
