### ISSUE TITLE
Apple m1 install cocoapods issue help me

### ISSUE THREAD

**Issue by kheto5** [CocoaPods/CocoaPods#12239]
<img width="569" alt="Ekran Resmi 2024-01-31 20 27 07" src="https://github.com/CocoaPods/CocoaPods/assets/158314569/72b9fce9-568e-4a99-bf5f-eae5977177c7">

ı try "sudo gem install cocoa pods" and ı saw that issue, help me pls.

**Comment by osmnnyldzz** [comment]
You can use `brew install cocoapods `

**Comment by kheto5** [comment]
zsh: command not found: brew

ı try but ı saw that issue

**Comment by kheto5** [comment]
> You can use `brew install cocoapods `

zsh: command not found: brew

ı try but ı saw that issue

**Comment by monfresh** [comment]
Please, [never use sudo to install gems](https://www.moncefbelyamani.com/why-you-should-never-use-sudo-to-install-ruby-gems/), and [don't use the system Ruby](https://www.moncefbelyamani.com/why-you-shouldn-t-use-the-system-ruby-to-install-gems-on-a-mac/) (the Ruby version that came preinstalled on your Mac). Instead, I recommend using a Ruby version manager to install a separate version of Ruby, which will let you install cocoapods with `gem install cocoapods`.

Here's a [step-by-step guide for setting up a proper Ruby environment on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).

**Comment by kheto5** [comment]
> Please, [never use sudo to install gems](https://www.moncefbelyamani.com/why-you-should-never-use-sudo-to-install-ruby-gems/), and [don't use the system Ruby](https://www.moncefbelyamani.com/why-you-shouldn-t-use-the-system-ruby-to-install-gems-on-a-mac/) (the Ruby version that came preinstalled on your Mac). Instead, I recommend using a Ruby version manager to install a separate version of Ruby, which will let you install cocoapods with `gem install cocoapods`.
> 
> Here's a [step-by-step guide for setting up a proper Ruby environment on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).

I try guide but ı saw that issue. :( 

![Uploading Screenshot 2024-02-01 at 14.26.21.png…]()

**Comment by mustafa-boorenie** [comment]
Reinstalling won't work because the issue seems to be with the latest 'stable' version of Cocoapods, a temporary solution I found running:

`pod _1.14.3_ install`


Please ensure you have up-to-date ruby and react-native installed too.

Hope this helps!
