### ISSUE TITLE
Error in installing pod with cocoapods 1.15.1 - hermes.xcframework

### ISSUE THREAD

**Issue by srk-mnnit** [CocoaPods/CocoaPods#12266]
# Report

## What did you do?

ℹ brew install cocoapods.  
then `pod install`

## What did you expect to happen?

ℹ Should install pods correctly.

## What happened instead?

ℹ Getting error
```
[!] The 'Pods-App' target has transitive dependencies that include statically linked binaries: (/Users/.../Pods/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework)
```

## CocoaPods Environment

ℹ cocoapods - 1.15.1
hermes-engine (0.72.10)

## Project that demonstrates the issue

ℹ Install latest version of cocoapods and then run pod install

**Comment by paulb777** [comment]
Fixed in 1.15.2
