### ISSUE TITLE
CocoaPods on a fresh install of Catalina. /usr/local/Cellar/openssl@3/3.2.1: 6,867 files, 32.6MB, built in 430 minutes 10 seconds

### ISSUE THREAD

**Issue by ChrisSQL** [CocoaPods/CocoaPods#12296]
Installing CocoaPods on a fresh install of Catalina.

Still going after about 12 hours.

`brew install cocoapods
Warning: Treating cocoapods as a formula. For the cask, use homebrew/cask/cocoapods
Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Fetching dependencies for cocoapods: libyaml, ca-certificates, openssl@3, m4, autoconf, pkg-config, libssh2, cmake, libgit2, mpdecimal, readline, sqlite, xz, python@3.12, z3, lz4, zstd, ninja, pcre2, swig, llvm, rust and ruby
==> Fetching libyaml
==> Downloading https://ghcr.io/v2/homebrew/core/libyaml/manifests/0.2.5
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libyaml/blobs/sha256:56d3549b34
######################################################################### 100.0%
==> Fetching ca-certificates
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2023-
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/blobs/sha256:5c
######################################################################### 100.0%
==> Fetching openssl@3
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://www.openssl.org/source/openssl-3.2.1.tar.gz
######################################################################### 100.0%
==> Fetching m4
==> Downloading https://ghcr.io/v2/homebrew/core/m4/manifests/1.4.19
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:e0fec6a49fd80cc
######################################################################### 100.0%
==> Fetching autoconf
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.gz
######################################################################### 100.0%
==> Fetching pkg-config
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/blobs/sha256:80f141e
######################################################################### 100.0%
==> Fetching libssh2
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://libssh2.org/download/libssh2-1.11.0.tar.gz
######################################################################### 100.0%
==> Fetching cmake
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://github.com/Kitware/CMake/releases/download/v3.28.3/cmake
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
==> Fetching libgit2
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://github.com/libgit2/libgit2/archive/refs/tags/v1.7.2.tar.
==> Downloading from https://codeload.github.com/libgit2/libgit2/tar.gz/refs/tag
                     -=O=-         #     #     #     #                         
==> Fetching mpdecimal
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4
######################################################################### 100.0%
==> Fetching readline
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.2-patches/readline82
######################################################################### 100.0%
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.2.tar.gz
######################################################################### 100.0%
==> Fetching sqlite
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://www.sqlite.org/2024/sqlite-autoconf-3450100.tar.gz
######################################################################### 100.0%
==> Fetching xz
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://downloads.sourceforge.net/project/lzmautils/xz-5.4.5.tar
==> Downloading from https://kumisystems.dl.sourceforge.net/project/lzmautils/xz
######################################################################### 100.0%
==> Fetching python@3.12
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/6d2fb
######################################################################### 100.0%
==> Downloading https://files.pythonhosted.org/packages/c4/e6/c1ac50fe3eebb38a15
######################################################################### 100.0%
==> Downloading https://files.pythonhosted.org/packages/94/59/6638090c25e9bc4ce0
######################################################################### 100.0%
==> Downloading https://files.pythonhosted.org/packages/fc/c9/b146ca195403e0182a
######################################################################### 100.0%
==> Downloading https://files.pythonhosted.org/packages/b0/b4/bc2baae3970c282fae
######################################################################### 100.0%
==> Downloading https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tgz
######################################################################### 100.0%
==> Fetching z3
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.12.5.tar.g
==> Downloading from https://codeload.github.com/Z3Prover/z3/tar.gz/refs/tags/z3
            -#O=- #    #     #                                                 
==> Fetching lz4
==> Downloading https://ghcr.io/v2/homebrew/core/lz4/manifests/1.9.4
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/lz4/blobs/sha256:ddb59c42498843
######################################################################### 100.0%
==> Fetching zstd
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://github.com/facebook/zstd/archive/refs/tags/v1.5.5.tar.gz
==> Downloading from https://codeload.github.com/facebook/zstd/tar.gz/refs/tags/
######################################################################### 100.0%
==> Fetching ninja
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://github.com/ninja-build/ninja/commit/67834978a6abdfb790da
######################################################################### 100.0%
==> Downloading https://github.com/ninja-build/ninja/archive/refs/tags/v1.11.1.t
==> Downloading from https://codeload.github.com/ninja-build/ninja/tar.gz/refs/t
######################################################################### 100.0%
==> Fetching pcre2
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
==> Fetching swig
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://downloads.sourceforge.net/project/swig/swig/swig-4.2.1/s
==> Downloading from https://deac-fra.dl.sourceforge.net/project/swig/swig/swig-
######################################################################### 100.0%
==> Fetching llvm
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/23704
######################################################################### 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-1
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
==> Fetching rust
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://github.com/rust-lang/cargo/archive/refs/tags/0.77.0.tar.
==> Downloading from https://codeload.github.com/rust-lang/cargo/tar.gz/refs/tag
######################################################################### 100.0%
==> Downloading https://static.rust-lang.org/dist/2023-12-28/cargo-1.75.0-x86_64
######################################################################### 100.0%
==> Downloading https://static.rust-lang.org/dist/rustc-1.76.0-src.tar.gz
######################################################################### 100.0%
==> Fetching ruby
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://rubygems.org/rubygems/rubygems-3.5.4.tgz
######################################################################### 100.0%
==> Downloading https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz
######################################################################### 100.0%
==> Fetching cocoapods
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/44735d7
######################################################################### 100.0%
==> Downloading https://github.com/CocoaPods/CocoaPods/archive/refs/tags/1.15.2.
==> Downloading from https://codeload.github.com/CocoaPods/CocoaPods/tar.gz/refs
                           -=O=-               #     #    #    #               
==> Installing dependencies for cocoapods: pkg-config, libyaml, ca-certificates, openssl@3, m4, autoconf, libssh2, cmake, libgit2, mpdecimal, readline, sqlite, xz, python@3.12, z3, lz4, zstd, ninja, pcre2, swig, llvm, rust and ruby
==> Installing cocoapods dependency: pkg-config
==> Downloading https://ghcr.io/v2/homebrew/core/pkg-config/manifests/0.29.2_3
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/ac691fc7ab8ecffba32a837e7197101d271474a3a84cfddcc30c9fd6763ab3c6--pkg-config-0.29.2_3.bottle_manifest.json
==> Pouring pkg-config--0.29.2_3.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.2_3: 11 files, 623.9KB
==> Installing cocoapods dependency: libyaml
==> Downloading https://ghcr.io/v2/homebrew/core/libyaml/manifests/0.2.5
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/5f6b0af1730aa1bc02f8021c90ed7ffe988eeba95eec83e6c828f77332ba6406--libyaml-0.2.5.bottle_manifest.json
==> Pouring libyaml--0.2.5.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libyaml/0.2.5: 10 files, 323.7KB
==> Installing cocoapods dependency: ca-certificates
==> Downloading https://ghcr.io/v2/homebrew/core/ca-certificates/manifests/2023-
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/13aa86e429e05d02a76005d1881eaf625091a5ac4dc7d7674c706d12ba48796a--ca-certificates-2023-12-12.bottle_manifest.json
==> Pouring ca-certificates--2023-12-12.all.bottle.tar.gz
==> Regenerating CA certificate bundle from keychain, this may take a while...
🍺  /usr/local/Cellar/ca-certificates/2023-12-12: 3 files, 226.7KB
==> Installing cocoapods dependency: openssl@3
==> perl ./Configure --prefix=/usr/local/Cellar/openssl@3/3.2.1 --openssldir=/us
==> make
==> make install MANDIR=/usr/local/Cellar/openssl@3/3.2.1/share/man MANSUFFIX=ss
==> make test
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#############                                               ###############                                             ################                                            ##################                                          ####################                                        ######################                                      ########################                                    ##########################                                  ############################                                ##############################                              ################################                            ##################################                          ####################################                        #######################################                     #########################################                   ############################################                ######################################################################### 100.0%🍺  /usr/local/Cellar/openssl@3/3.2.1: 6,867 files, 32.6MB, built in 430 minutes 10 seconds
==> Installing cocoapods dependency: m4
==> Downloading https://ghcr.io/v2/homebrew/core/m4/manifests/1.4.19
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/5b2a7f715487b7377e409e8ca58569040cd89f33859f691210c58d94410fd33b--m4-1.4.19.bottle_manifest.json
==> Pouring m4--1.4.19.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/m4/1.4.19: 13 files, 724.4KB
==> Installing cocoapods dependency: autoconf
==> ./configure --with-lispdir=/usr/local/Cellar/autoconf/2.72/share/emacs/site-
==> make install
🍺  /usr/local/Cellar/autoconf/2.72: 71 files, 3.6MB, built in 5 seconds
==> Installing cocoapods dependency: libssh2
==> ./configure --disable-silent-rules --disable-examples-build --with-openssl -
==> make install
🍺  /usr/local/Cellar/libssh2/1.11.0_1: 197 files, 1.1MB, built in 29 seconds
==> Installing cocoapods dependency: cmake
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.28.3 --no-system-libs --paral
==> make
==> make install
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
🍺  /usr/local/Cellar/cmake/3.28.3: 3,329 files, 61MB, built in 16 minutes 4 seconds
==> Installing cocoapods dependency: libgit2
==> cmake -S . -B build -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DBUILD_TEST
==> cmake --build build
==> cmake --install build
==> cmake -S . -B build-static -DBUILD_SHARED_LIBS=OFF -DBUILD_EXAMPLES=OFF -DBU
==> cmake --build build-static
🍺  /usr/local/Cellar/libgit2/1.7.2: 104 files, 4.4MB, built in 1 minute 14 seconds
==> Installing cocoapods dependency: mpdecimal
==> ./configure
==> make
==> make install
🍺  /usr/local/Cellar/mpdecimal/4.0.0: 21 files, 628.7KB, built in 15 seconds
==> Installing cocoapods dependency: readline
==> Patching
==> Applying readline82-001
patching file nls.c
patching file patchlevel
==> Applying readline82-002
patching file display.c
patching file patchlevel
==> Applying readline82-003
patching file colors.c
patching file patchlevel
==> Applying readline82-004
patching file input.c
patching file patchlevel
==> Applying readline82-005
patching file callback.c
patching file patchlevel
==> Applying readline82-006
patching file input.c
Hunk #1 succeeded at 805 (offset -7 lines).
Hunk #2 succeeded at 816 (offset -7 lines).
Hunk #3 succeeded at 895 (offset -7 lines).
Hunk #4 succeeded at 938 (offset -7 lines).
patching file patchlevel
==> Applying readline82-007
patching file display.c
Hunk #1 succeeded at 3391 (offset -3 lines).
patching file patchlevel
==> ./configure --with-curses
==> make install SHLIB_LIBS=-lcurses
🍺  /usr/local/Cellar/readline/8.2.7: 50 files, 1.7MB, built in 26 seconds
==> Installing cocoapods dependency: sqlite
==> ./configure --enable-dynamic-extensions --enable-readline --disable-editline
==> make install
🍺  /usr/local/Cellar/sqlite/3.45.1: 11 files, 4.7MB, built in 1 minute 19 seconds
==> Installing cocoapods dependency: xz
==> ./configure --disable-silent-rules --disable-nls
==> make check
==> make install
🍺  /usr/local/Cellar/xz/5.4.5: 163 files, 2.6MB, built in 50 seconds
==> Installing cocoapods dependency: python@3.12
==> Patching
==> Applying 3.11-sysconfig.diff
patching file Lib/sysconfig.py
Hunk #1 succeeded at 96 (offset 1 line).
Hunk #2 succeeded at 300 (offset 5 lines).
==> ./configure --enable-ipv6 --datarootdir=/usr/local/Cellar/python@3.12/3.12.2
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python@3.12/3.12.2_1
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python@3.12/3.12
==> /usr/local/Cellar/python@3.12/3.12.2_1/bin/python3.12 -m venv /private/tmp/p
==> /private/tmp/pythonA3.12-20240226-38755-jluf5d/Python-3.12.2/whl_build/bin/p
==> /private/tmp/pythonA3.12-20240226-38755-jluf5d/Python-3.12.2/whl_build/bin/p
==> /private/tmp/pythonA3.12-20240226-38755-jluf5d/Python-3.12.2/whl_build/bin/p
==> /private/tmp/pythonA3.12-20240226-38755-jluf5d/Python-3.12.2/whl_build/bin/p
==> /private/tmp/pythonA3.12-20240226-38755-jluf5d/Python-3.12.2/whl_build/bin/p
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################### 100.0%
==> /usr/local/Cellar/python@3.12/3.12.2_1/bin/python3.12 -Im ensurepip
==> /usr/local/Cellar/python@3.12/3.12.2_1/bin/python3.12 -Im pip install -v --n
🍺  /usr/local/Cellar/python@3.12/3.12.2_1: 8,184 files, 185.5MB, built in 27 minutes 30 seconds
==> Installing cocoapods dependency: z3
==> cmake -S . -B build -DZ3_LINK_TIME_OPTIMIZATION=ON -DZ3_INCLUDE_GIT_DESCRIBE
==> cmake --build build
==> cmake --install build
==> make -C contrib/qprofdiff
🍺  /usr/local/Cellar/z3/4.12.5: 119 files, 32.6MB, built in 12 minutes 21 seconds
==> Installing cocoapods dependency: lz4
==> Downloading https://ghcr.io/v2/homebrew/core/lz4/manifests/1.9.4
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/379e59b981667f9585b33a2ff318769d8edca3ce6fd2e9a67ed291ae3e0cc872--lz4-1.9.4.bottle_manifest.json
==> Pouring lz4--1.9.4.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/lz4/1.9.4: 22 files, 680.3KB
==> Installing cocoapods dependency: zstd
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################## 100.0%
==> cmake -S build/cmake -B builddir -DZSTD_PROGRAMS_LINK_SHARED=ON -DZSTD_BUILD_CONTRIB=ON -DCMAKE_INSTALL_RPA
==> cmake --build builddir
==> cmake --install builddir
🍺  /usr/local/Cellar/zstd/1.5.5: 31 files, 2.5MB, built in 35 seconds
==> Installing cocoapods dependency: ninja
==> Patching
==> Applying 67834978a6abdfb790dac165b8b1f1c93648e624.patch
patching file src/browse.cc
==> python3 configure.py --bootstrap --with-python=python3
🍺  /usr/local/Cellar/ninja/1.11.1: 10 files, 454.7KB, built in 42 seconds
==> Installing cocoapods dependency: pcre2
==> ./configure --enable-pcre2-16 --enable-pcre2-32 --enable-pcre2grep-libz --enable-pcre2grep-libbz2 --enable-
==> make
==> make install
🍺  /usr/local/Cellar/pcre2/10.42: 230 files, 6.4MB, built in 44 seconds
==> Installing cocoapods dependency: swig
==> ./configure
==> make
==> make install
🍺  /usr/local/Cellar/swig/4.2.1: 829 files, 5.8MB, built in 47 seconds
==> Installing cocoapods dependency: llvm
==> Patching
==> Applying 17.x-arm64-opt.patch
patching file llvm/include/llvm/CodeGen/TargetInstrInfo.h
patching file llvm/lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.cpp
patching file llvm/lib/CodeGen/LiveDebugValues/VarLocBasedImpl.cpp
patching file llvm/lib/Target/AArch64/AArch64InstrInfo.cpp
patching file llvm/lib/Target/AArch64/AArch64InstrInfo.h
patching file llvm/test/CodeGen/AArch64/machine-cp-sub-reg.mir
==> cmake -G Ninja .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;mlir;polly -DLLVM_ENABLE_RUNTIMES
==> cmake --build .
`

**Comment by firofame** [comment]
this is insane.  I have been stuck for some time now.

```
==> cmake -G Ninja .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;ml
==> cmake --build .
```

**Comment by Troloroma** [comment]
> this is insane. I have been stuck for some time now.
> 
> ```
> ==> cmake -G Ninja .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;ml
> ==> cmake --build .
> ```

Does anyone succeed installation after "cmake -G Ninja..."?

**Comment by thefiscina** [comment]
i have the same here... 
==> Installing dependencies for cocoapods: llvm, rust and ruby
==> Installing cocoapods dependency: llvm
==> cmake -G Ninja .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;mlir;polly;lldb -DLLVM_ENABLE_RUNTIMES=compiler-rt;libcxx;libcxxabi;libunwind;openmp -DLLVM_POLLY_LINK_INTO_TOOLS=ON -DLLVM_BUILD
==> cmake --build .

**Comment by Troloroma** [comment]
> i have the same here... ==> Installing dependencies for cocoapods: llvm, rust and ruby ==> Installing cocoapods dependency: llvm ==> cmake -G Ninja .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;mlir;polly;lldb -DLLVM_ENABLE_RUNTIMES=compiler-rt;libcxx;libcxxabi;libunwind;openmp -DLLVM_POLLY_LINK_INTO_TOOLS=ON -DLLVM_BUILD ==> cmake --build .

i waited about 5 hours...

**Comment by Hysbak** [comment]
Same issue here. Was still going after 12+ hours so I canceled the terminal and trying again now... Lets see.

**Comment by monfresh** [comment]
This is one of the reasons I don't recommend installing cocoapods with Homebrew. Instead, I highly recommend installing a newer version of Ruby using a **version manager** (such as chruby, rbenv, asdf), and once you have Ruby installed, you can easily and quickly install cocoapods with `gem install cocoapods`. Note that you should never use `sudo` to install gems.

Here's a [step by step guide for properly installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).
