### ISSUE TITLE
in flutter

### ISSUE THREAD

**Issue by jamalshah690** [CocoaPods/CocoaPods#12319]
pod install               
Analyzing dependencies
cloud_firestore: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '10.22.0' defined in 'firebase_core'
Downloading dependencies
Installing AppAuth (1.7.3)
Installing BoringSSL-GRPC (0.0.32)

[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/1d/vcm__3hs06v80sxhzj7jc7zm0000gn/T/d20240321-5191-xe67gg --template=

Cloning into '/var/folders/1d/vcm__3hs06v80sxhzj7jc7zm0000gn/T/d20240321-5191-xe67gg'...
error: RPC failed; curl 18 Transferred a partial file
error: 1976 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by paulb777** [comment]
Missing CocoaPods issue template. May be an intermittent network issue. Please retry.
