### ISSUE TITLE
Xcode15.3  pod lib lint , xcodebuild: Returned an unsuccessful exit code.

### ISSUE THREAD

**Issue by evan802399** [CocoaPods/CocoaPods#12318]
** BUILD FAILED **
    
    The following build commands failed:
    	SwiftCompile normal x86_64 Compiling\ AnyExtensions.swift,\ BuiltInBasicType.swift,\ BuiltInBridgeType.swift,**********

Testing with `xcodebuild`. 
 -> SwiftNetworking (0.1.4)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - WARN  | url: There was a problem validating the URL https://github.com/********/SwiftNetworking.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [iOS] xcodebuild:  note: Target dependency graph (7 targets)
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.4.99. (in target 'Moya' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.4.99. (in target 'Alamofire-Alamofire' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 12.0 to 17.4.99. (in target 'HandyJSON' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0, but the range of supported deployment target versions is 12.0 to 17.4.99. (in target 'Alamofire' from project 'Pods')

Pods workspace available at `/var/folders/2h/_x9vhlf529b12_tbfzxn6qwm0000gn/T/CocoaPods-Lint-20240321-6520-1q02vaf-SwiftNetworking/App.xcworkspace` for inspection.

[!] SwiftNetworking did not pass validation, due to 1 error and 2 warnings.

Please help me

**Comment by paulb777** [comment]
This looks like an issue with the SwiftNetworking library, not with CocoaPods itself. Pleas report to the library provider.
