### ISSUE TITLE
pod lib lint error

### ISSUE THREAD

**Issue by shijian123** [CocoaPods/CocoaPods#12332]
The following build commands failed:
    	Ld /Users/xxx/Library/Developer/Xcode/DerivedData/App-bbdiuvavmfbqeyafsistcpmwcfaz/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/lottie-ios.build/Objects-normal/x86_64/Binary/Lottie normal x86_64 (in target 'lottie-ios' from project 'Pods')

**Comment by paulb777** [comment]
Please file an issue to the Lottie project.
