### ISSUE TITLE
'pod trunk push MyPod.podspec' taking very long time (more than an hour)

### ISSUE THREAD

**Issue by km-steve-ham** [CocoaPods/CocoaPods#12372]
3 days ago when I 'pod trunk push' it got release within couple minutes.

Now when I 'pod trunk push' it is taking more than an hour to release. Below logs show when I add --verbose (There are so many redirects):
CDN: trunk Redirecting from
  https://cdn.cocoapods.org/Specs/f/a/5/RollbarSwift/2.0.0-beta7/RollbarSwift.podspec.json
  to
  https://cdn.jsdelivr.net/cocoa/Specs/f/a/5/RollbarSwift/2.0.0-beta7/RollbarSwift.podspec.json
  CDN: trunk Redirecting from
  https://cdn.cocoapods.org/Specs/f/a/5/RollbarSwift/2.0.0-beta8/RollbarSwift.podspec.json
  to
  https://cdn.jsdelivr.net/cocoa/Specs/f/a/5/RollbarSwift/2.0.0-beta8/RollbarSwift.podspec.json
  CDN: trunk Redirecting from
  https://cdn.cocoapods.org/Specs/f/a/5/RollbarSwift/2.0.0-beta9/RollbarSwift.podspec.json
  to
  https://cdn.jsdelivr.net/cocoa/Specs/f/a/5/RollbarSwift/2.0.0-beta9/RollbarSwift.podspec.json
  CDN: trunk Redirecting from
  https://cdn.cocoapods.org/Specs/f/a/5/RollbarSwift/2.0.3/RollbarSwift.podspec.json
  to
  https://cdn.jsdelivr.net/cocoa/Specs/f/a/5/RollbarSwift/2.0.3/RollbarSwift.podspec.json
  CDN: trunk Redirecting from
  https://cdn.cocoapods.org/Specs/f/a/5/RollbarSwift/2.1.0/RollbarSwift.podspec.json

**Comment by ykhandelwal913** [comment]
We are also facing the same issue.

**Comment by ykhandelwal913** [comment]
@km-steve-ham did it resolve for you???

**Comment by steve-ham** [comment]
Yea it did get resolved, I cannot pin point exact reason but one day it's gone. I think all I did was to reinstall CocoaPods, in my past memory but that still didn't improve speed. I don't remember doing any hackish things changing settings and such. Now deployment speed is fast, just how it use to be before.
