### ISSUE TITLE
执行pod install 或pod update报错

### ISSUE THREAD

**Issue by ShemarKing** [CocoaPods/CocoaPods#12396]
![screenshots](https://github.com/CocoaPods/CocoaPods/assets/13427485/6d8972f4-603b-4c29-a3f5-c77b21479ed2)

**Comment by HyungonKim-Adscale** [comment]
I think you put invisible Unicode in the podfile. The square letter is usually Unicode. 
Delete the pod file and type them again. Don't copy and paste.

**Comment by paulb777** [comment]
See the issue template for the scope of what should be reported here and what information should be provided.
