### ISSUE TITLE
 **Error Output from CocoaPods:**

### ISSUE THREAD

**Issue by Mumtaz12** [CocoaPods/CocoaPods#12431]
### Report

**Error Output from CocoaPods:**
RuntimeError: attempted adding second root element to document
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.8/lib/rexml/document.rb:197:in `add'
/Library/Ruby/Gems/2.6.0/gems/rexml-3.2.8/lib/rexml/element.rb:1931:in `add'
...

**Comment by paulb777** [comment]
Please follow issue submission instructions.
