### ISSUE TITLE
I have an issue with "Pod install" - MacBook Air 2024

### ISSUE THREAD

**Issue by ahmedhammouda-ogtech** [CocoaPods/CocoaPods#12443]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
    RubyGems : 3.0.3.1
        Host : macOS 14.3 (23D2057)
       Xcode : 15.4 (15F31d)
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MirageCityCompound' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MirageCityCompound
pod 'SwiftOTP'
pod 'Alamofire', '~> 5.2'
pod 'SideMenu', '~> 6.0'
pod 'Kingfisher', '~> 5.0'
pod 'SwiftKeychainWrapper'
pod 'LanguageManager-iOS'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
#pod 'Firebase/Crashlytics'
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/ogtech/.cocoapods/repos/trunk/Specs/a/a/6/Kingfisher/5.8.2/Kingfisher.podspec.json'.

767: unexpected token at '{
  "name": "Kingfisher",
  "version": "5.8.2",
  "summary": "A lightweight and pure Swift implemented library for downloading and cacheing image from the web.",
  "description": "Kingfisher is a powerful and pure Swift implemented library for downloading and cacheing image from the web. It provides you a chance to use pure Swift alternation in your next app.\n\n* Everything in Kingfisher goes asynchronously, not only downloading, but also caching. That means you can never worry about blocking your UI thread.\n* Multiple-layer cache. Downloaded image will be cached in both memory and disk. So there is no need to download it again and this could boost your app dramatically.\n* Cache management. You can set the max duration or size the cache could take. And the cache will also be cleaned automatically to prevent taking too much resource.\n* Modern framework. Kingfisher uses `NSURLSession` and the latest technology of GCD, which makes it a strong and swift framework. It also provides you easy APIs to use.\n* Cancellable processing task. You can cancel the downloading or retriving image process if it is not needed anymore.\n* Independent components. You can use the downloader or caching system separately. Or even create your own cache based on Kingfisher's code.\n* Options to decompress the image in background before render it, which could improve the UI performance.\n* A category over `UIImageView` for setting image from an url directly.",
  "homepage": "https://github.com/onevcat/Kingfisher",
  "screenshots": "https://raw.githubusercontent.com/onevcat/Kingfisher/master/images/logo.png",
  "license": {
    "type": "MIT",
    "file": "LICENSE"
  },
  "authors": {
    "onevcat": "onevcat@gmail.com"
  },
  "social_media_url": "https://twitter.com/onevcat",
  "swift_versions": [
    "4.0",
    "4.2",
    "5.0"
  ],
  "platforms": {
    "ios": "10.0",
    "tvos": "10.0",
    "osx": "10.12",
    "watchos": "3'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification.rb:759:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/specification.rb:733:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/source.rb:188:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:348:in `block in delegating_block'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:422:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Failed+to+parse+JSON+at+file%3A+%27%2FUsers%2Fogtech%2F.cocoapods%2Frepos%2Ftrunk%2FSpecs%2Fa%2Fa%2F6%2FKingfisher%2F5.8.2%2FKingfisher.podspec.json%27.%0A%0A767%3A+unexpected+token+at+%27%7B%0A++%22name%22%3A+%22Kingfisher%22%2C%0A++%22version%22%3A+%225.8.2%22%2C%0A++%22summary%22%3A+%22A+lightweight+and+pure+Swift+implemented+library+for+downloading+and+cacheing+image+from+the+web.%22%2C%0A++%22description%22%3A+%22Kingfisher+is+a+powerful+and+pure+Swift+implemented+library+for+downloading+and+cacheing+image+from+the+web.+It+provides+you+a+chance+to+use+pure+Swift+alternation+in+your+next+app.%5Cn%5Cn%2A+Everything+in+Kingfisher+goes+asynchronously%2C+not+only+downloading%2C+but+also+caching.+That+means+you+can+never+worry+about+blocking+your+UI+thread.%5Cn%2A+Multiple-layer+cache.+Downloaded+image+will+be+cached+in+both+memory+and+disk.+So+there+is+no+need+to+download+it+again+and+this+could+boost+your+app+dramatically.%5Cn%2A+Cache+management.+You+can+set+the+max+duration+or+size+the+cache+could+take.+And+the+cache+will+also+be+cleaned+automatically+to+prevent+taking+too+much+resource.%5Cn%2A+Modern+framework.+Kingfisher+uses+%60NSURLSession%60+and+the+latest+technology+of+GCD%2C+which+makes+it+a+strong+and+swift+framework.+It+also+provides+you+easy+APIs+to+use.%5Cn%2A+Cancellable+processing+task.+You+can+cancel+the+downloading+or+retriving+image+process+if+it+is+not+needed+anymore.%5Cn%2A+Independent+components.+You+can+use+the+downloader+or+caching+system+separately.+Or+even+create+your+own+cache+based+on+Kingfisher%27s+code.%5Cn%2A+Options+to+decompress+the+image+in+background+before+render+it%2C+which+could+improve+the+UI+performance.%5Cn%2A+A+category+over+%60UIImageView%60+for+setting+image+from+an+url+directly.%22%2C%0A++%22homepage%22%3A+%22https%3A%2F%2Fgithub.com%2Fonevcat%2FKingfisher%22%2C%0A++%22screenshots%22%3A+%22https%3A%2F%2Fraw.githubusercontent.com%2Fonevcat%2FKingfisher%2Fmaster%2Fimages%2Flogo.png%22%2C%0A++%22license%22%3A+%7B%0A++++%22type%22%3A+%22MIT%22%2C%0A++++%22file%22%3A+%22LICENSE%22%0A++%7D%2C%0A++%22authors%22%3A+%7B%0A++++%22onevcat%22%3A+%22onevcat%40gmail.com%22%0A++%7D%2C%0A++%22social_media_url%22%3A+%22https%3A%2F%2Ftwitter.com%2Fonevcat%22%2C%0A++%22swift_versions%22%3A+%5B%0A++++%224.0%22%2C%0A++++%224.2%22%2C%0A++++%225.0%22%0A++%5D%2C%0A++%22platforms%22%3A+%7B%0A++++%22ios%22%3A+%2210.0%22%2C%0A++++%22tvos%22%3A+%2210.0%22%2C%0A++++%22osx%22%3A+%2210.12%22%2C%0A++++%22watchos%22%3A+%223%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

[!] Automatically assigning platform `iOS` with version `12.0` on target `MirageCityCompound` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**Comment by nagamekes03** [comment]
I am facing same issue and same error, already try to use version 13.0 and still no luck

**Comment by ahmedhammouda-ogtech** [comment]
> I am facing same issue and same error, already try to use version 13.0 and still no luck

I installed Homebrew and installed ruby by it, then install cocoapods by brew also.
the problem solved for me now.

https://mac.install.guide/homebrew/3
https://mac.install.guide/ruby/13
https://formulae.brew.sh/formula/cocoapods

**Comment by nagamekes03** [comment]
@ahmedhammouda-ogtech I managed to solve my problem by upgrading ruby to 3.3.3 using rbenv then set it as global ruby.
