### ISSUE TITLE
Properly handle dependencies in Pod targets to other Pods targets

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1244]
This involves:

- [ ] Include the build settings of the dependencies in the ones of the Pod targets.
- [x] Add file references to the system libraries as it is done with the frameworks.
- [x] Set up linked frameworks and libraries in Pod targets (this is not required but it is useful for illustrative purposes).

**Comment by segiddins** [comment]
@mrackwitz @neonichu is this something that's still needed?

**Comment by segiddins** [comment]
Closing as I believe this all has been addressed.
