### ISSUE TITLE
LoadError - cannot load such file -- ffi_c

### ISSUE THREAD

**Issue by MOAIS-GSThecar** [CocoaPods/CocoaPods#12440]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Install all pod dependencies correctly.

## What happened instead?
[!] Oh no, an error occurred while Analyzing dependencies

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin23]
    RubyGems : 3.0.3.1
        Host : macOS 14.2.1 (23C71)
       Xcode : 15.3 (15E204a)
         Git : git version 2.34.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0

```

### Podfile

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

# ignore all warnings from all pods
inhibit_all_warnings!

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
	if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end

target 'myapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myapp

	pod 'AcknowList'
	pod 'Alamofire'
	pod 'DropDown'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'FBSDKShareKit'
	pod 'FBSDKGamingServicesKit'
   	pod 'FBAudienceNetwork'
        pod 'Firebase'
	pod 'FirebaseAuth'
	pod 'FirebaseDynamicLinks'
	pod 'FirebaseFirestore'
	pod 'FirebaseFirestoreSwift'
	pod 'FirebaseStorage'
	pod 'FirebaseCrashlytics'
	pod 'FirebasePerformance'
	pod 'FirebaseRemoteConfig'
	pod 'FirebaseAnalytics'
	pod 'FirebaseFunctions'
	pod 'FirebaseMessaging'
	pod 'FSCalendar'
	pod 'GoogleSignIn'
	pod 'KakaoSDKShare'
	pod 'Kingfisher'
	pod 'lottie-ios'
	pod 'MarqueeLabel'
	pod 'PhoneNumberKit'
	pod 'RxDataSources'
	pod 'RxSwift'
    	pod 'RxCocoa'
	pod 'RxGesture'
	pod 'SnapKit'
	pod 'SwiftLint'
	pod 'SwiftGen'
	pod 'Then'
	pod 'RealmSwift', '10.50.0'
	pod 'VisualEffectView'
	pod 'OneSignal'
	pod 'Mixpanel-swift'
	pod 'NTrackerSDKExt'

  target 'myappTests' do
    inherit! :search_paths
    # Pods for testing

	pod "Quick"
	pod "Nimble"
	pod 'RxBlocking'
 	pod 'RxTest'
  end

   target 'OneSignalNotificationServiceExtension' do
	inherit! :search_paths
	pod 'OneSignal'
   end


end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

### Error

```
LoadError - cannot load such file -- ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.17.0-arm64-darwin/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.17.0-arm64-darwin/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.1/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:142:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:140:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:140:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:146:in `block in update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:144:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:144:in `update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:240:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:239:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by niladri-raychaudhuri** [comment]
Same here, I am using Flutter to run iOS App.

**Comment by robinsjovoll** [comment]
on Mac M3 I solved with
`brew install cocoapods`

**Comment by monfresh** [comment]
If you see references to `/System/Library/Frameworks/Ruby.framework/Versions/2.6` or `/Library/Ruby/Gems/2.6.0/gems/` in any error message, and if you run `which ruby` and it returns `/usr/bin/ruby`, that means you're using the system Ruby, which is the version of Ruby that came preinstalled by Apple on your Mac. 

**You should never use the system Ruby!**

Instead, you need to install a newer and separate version of Ruby using a version manager such as chruby/ruby-install, asdf, rbenv. You can also install Ruby and/or cocoapods with Homebrew but I don't recommend that.

Here's a [step by step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).

And here are articles that explain why you shouldn't use the system Ruby:

[Why You Shouldn't Use the System Ruby to Install Gems on a Mac](https://www.moncefbelyamani.com/why-you-shouldn-t-use-the-system-ruby-to-install-gems-on-a-mac/)

[Don't Use System Ruby](https://dontusesystemruby.com/#/)

And here's [a guide that explains all the possible ways you can install Ruby gems on a Mac](https://www.moncefbelyamani.com/the-definitive-guide-to-installing-ruby-gems-on-a-mac/), and why I recommend using a version manager.

Over the past 12 years, I've helped hundreds of thousands of people set up Ruby properly on their Mac, so I've seen all kinds of issues. The most reliable way to fix them and to avoid messing up your Mac and/or your development setup is to make sure to install Ruby properly using a version manager.

**Comment by jwainwright87** [comment]
> on Mac M3 I solved with `brew install cocoapods`

Worked for me! Had to `sudo gem uninstall cocoapods` first

**Comment by Zabi-Ullah** [comment]
i have m1 i am install xcode and setup environment of react native. i am create a new project but i am facing this issue 'RCTAppDelegate.h' file not found this error about not new project this error from old and new project i don't understand please guide me..

**Comment by nirmal0707** [comment]
> > on Mac M3 I solved with `brew install cocoapods`
> 
> Worked for me! Had to `sudo gem uninstall cocoapods` first

This worked in M3 🎉

If you installed CocoaPods using the command `sudo gem install cocoapods`, uninstall it with `sudo gem uninstall cocoapods`.

Then, install CocoaPods using Homebrew with the command `brew install cocoapods`.

Disclaimer: If you installed CocoaPods with Homebrew without first uninstalling it via the gem command, it may not work properly. In this case, you should use `brew uninstall cocoapods` and then run `brew install cocoapods`.

**Comment by owlnewworlds** [comment]
> on Mac M3 I solved with `brew install cocoapods`

YOU. ARE. A. SAVIOR. Thank you <3

**Comment by tikgithub** [comment]
one after you install cocoapods by  brew install cocoapods , if not work then try brew link --overwrite cocoapods
after than do the
cd ios
pod install

**Comment by Bintong** [comment]
1. sudo gem uninstall cocoapods first 
2. brew install cocoapods
3. brew link --overwrite cocoapods

**Comment by yingyugang** [comment]
> 1. sudo gem uninstall cocoapods first
> 2. brew install cocoapods
> 3. brew link --overwrite cocoapods

I solved my problem by this.

**Comment by soyjuanmacias** [comment]
> > 1. sudo gem uninstall cocoapods first
> > 2. brew install cocoapods
> > 3. brew link --overwrite cocoapods
> 
> I solved my problem by this.

It's works for me. 

Thanks

Macbook PRO M2

**Comment by Maheshoo7** [comment]
> 1. sudo gem uninstall cocoapods first
> 2. brew install cocoapods
> 3. brew link --overwrite cocoapods

After doing this i had to run `bundle install` and then `pod install`

**Comment by ahmeedev** [comment]
> > on Mac M3 I solved with `brew install cocoapods`
> 
> Worked for me! Had to `sudo gem uninstall cocoapods` first

Horaay, It works ! 🎊🎉

**Comment by 18923767582** [comment]
M4 also solved by
1. sudo gem uninstall cocoapods
2. brew install cocoapods
3. brew link cocoapods

**Comment by FrasapDev** [comment]
Mac book pro i9 2019 solved 

1. sudo gem uninstall cocoapods
2. brew install cocoapods
3. brew link cocoapods

**Comment by 94Sip** [comment]
> 1. sudo gem uninstall cocoapods first
> 2. brew install cocoapods
> 3. brew link --overwrite cocoapods

upgrade M2 mac to Sequoia and xcode 16.1 - this worked for me as well, for a flutter project

**Comment by kakaru1331** [comment]
> on Mac M3 I solved with `brew install cocoapods`

he is a real savior!

**Comment by JeremyHuang37** [comment]
```shell
bundle exec pod install
bundle update
```
for me is good

**Comment by tclxtianxiang-yu** [comment]
> 1. sudo gem uninstall cocoapods first
> 2. brew install cocoapods
> 3. brew link --overwrite cocoapods

for me is good.
mac m1max

**Comment by glumes** [comment]
> bundle exec pod install
> bundle update
> for me is good

this work for me

**Comment by ARSSHEIKH** [comment]
I had same error, My issue solved with this command
`sudo gem uninstall ffi && sudo gem install ffi -- --enable-libffi-alloc`

**Comment by saidjohn** [comment]
> 1. sudo gem uninstall cocoapods first
> 2. brew install cocoapods
> 3. brew link --overwrite cocoapods

It works! Thank you!

**Comment by nico-harison** [comment]
> I had same error, My issue solved with this command `sudo gem uninstall ffi && sudo gem install ffi -- --enable-libffi-alloc`

thanks it solved it

**Comment by Rakhilpr96** [comment]
In my case I resolved it by `sudo gem uninstall ffi && sudo gem install ffi --platform=ruby`
