### ISSUE TITLE
Potential Code Injection possibility

### ISSUE THREAD

**Issue by raf-wtag** [CocoaPods/CocoaPods#12448]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Recently A report by E.V.A Information Security reveals that Apple's popular dependency manager, CocoaPods, has been plagued with three critical vulnerabilities for several years -
https://www.darkreading.com/cloud-security/apple-cocoapods-bugs-expose-apps-code-injection?&web_view=true

## Expectation

Is there any fix coming from you?

**Comment by orta** [comment]
You can read the CocoaPods blog post about it from last year, https://blog.cocoapods.org/CocoaPods-Trunk-RCEs-2023/
