### ISSUE TITLE
Error installing pod on M2 Mac

### ISSUE THREAD

**Issue by cohnjonner** [CocoaPods/CocoaPods#12457]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod Install 

## What did you expect to happen?

run pod file correctly 

## What happened instead?

command failed out with error
"wrong argument type String (expected Regexp)"

## CocoaPods Environment

```
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
    RubyGems : 3.0.3.1
        Host : macOS 14.5 (23F79)
       Xcode :  ()
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
platform :ios, '13.0'

target 'Flash Chat iOS13' do
    use_frameworks!

  # Pods for Flash Chat iOS13

  pod 'CLTypingLabel'

end

## Project that demonstrates the issue
trying to integrate this into an app for a class that I'm taking 
this is the pod I can't install 
[CLTypingLabel](https://github.com/cl7/CLTypingLabel)

**Comment by cohnjonner** [comment]
I'm quite new so I realize it's possible I did something very obvious.

**Comment by naramirezj** [comment]
Hello! I am trying to run `pod install` on a M1 Mac and I am getting the same error. 
I believe it is related to the ruby version (2.6.1) and its REXML parser. However, I am unable to install ruby 3.0. I do not know if this is a known error occurring in M1 and M2 Macs.
### Stack:
```
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
    RubyGems : 3.0.3.1
        Host : macOS 14.5 (23F79)
       Xcode : 15.4 
         Git : git version 2.43.0
  Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
  trunk - CDN - https://cdn.cocoapods.org/
```
### Error: 
```
wrong argument type String (expected Regexp)
```

**Comment by cohnjonner** [comment]
naramirezj - just reinstalled ruby and configured my git that seemed to do it. Hope this helps you do the same.

**Comment by monfresh** [comment]
@naramirezj Hi Natalia. You are correct that the issue is due to using the system Ruby (the version of Ruby that comes preinstalled by Apple). If you're still having trouble installing a newer version of Ruby, here's a [step by step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).

And here's my article that explains in more detail why you're getting the [wrong argument type String (expected Regexp)](https://www.rubyonmac.dev/cocoapods-rexml-parse-exception) error.

I hope this helps!
