### ISSUE TITLE
Searching for inspections failed: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by Aciofani** [CocoaPods/CocoaPods#12451]
# Report

I tried to install pods with 'pod install' and i have this error:

<img width="543" alt="Screenshot 2024-07-10 alle 01 28 18" src="https://github.com/CocoaPods/CocoaPods/assets/57839445/0c43ddfe-fb7f-4ba3-8820-25e5536deaeb">

I'm unable to do pod install and ru my app.

I already tryed to run 'arch -x86_64 pod install' and i already tried all the things on internet that i've found on this specific error, but nothing worked for me.

I also installed a version manager for ruby. Now i'm using the latest stable version (3.3.4):
<img width="437" alt="Screenshot 2024-07-10 alle 01 31 41" src="https://github.com/CocoaPods/CocoaPods/assets/57839445/89860263-814d-4620-ad0b-867adbffcf8d">

But i see in the 'pod env' that the system version is mentioned...

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
    RubyGems : 3.0.3.1
        Host : macOS 14.5 (23F79)
       Xcode : 15.4 (15F31d)
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more infomation: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        
        ## dart: PermissionGroup.notification
        'PERMISSION_NOTIFICATIONS=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_CAMERA=1'
      ]
    end
  end
end
```

Hope that someone has the solution.
Thanks

**Comment by monfresh** [comment]
There are a few problems that are causing the issue you're seeing:

1) You're on an Apple Silicon Mac and you're running commands that start with `arch -x86_64`. You can't mix and match architectures. If you're running on the native `arm64` architecture, you can't install some things with `arm64` and then install some other things with the Intel `x86_64` architecture or with Rosetta, and you can't run some commands with `arm64` and others with `arch -x86_64`. This can cause all kinds of issues.

2) You're using the system Ruby. I see you've tried installing a newer Ruby version, which is great because [you should never use the system Ruby](https://www.moncefbelyamani.com/why-you-shouldn-t-use-the-system-ruby-to-install-gems-on-a-mac/). However, you didn't properly set up your development environment to use this newer version of Ruby.

To set up a proper Ruby development environment on an Apple Silicon Mac, follow my [step by step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).

**Comment by Aciofani** [comment]
I solved it by installing the latest version of Ruby using rbenv, ensuring that the `pod env` command outputs the correct version. Everything was done without replacing the system's Ruby. I'm using a MacBook with an M2 Pro.

Thanks anyway for the support.

**Comment by nauticlab** [comment]
Aciofani I have the same problem too, with macbook M3 pro. After updating Ruby did you do other operations?

**Comment by monfresh** [comment]
@nauticlab How did you update Ruby? Have you tried following my [guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/)?
