### ISSUE TITLE
Remove environment header

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1246]
Currently CocoaPods adds the file references to the xcconfigs in the main group of the client projects. It also adds the file references of the library targets in the Products group. This approach would benefit from further organization and is not flexible as it doesn't allow to add further file references without the risk of creating a mess.

I propose to:

- [x] create a `Pods` group in the main group of the user project
- [x] store the xcconfigs
- [ ] store the file references to the libraries
- [ ] store the file references to the resource bundles generated by CocoaPods
- [ ] ~~store the environment headers generated by CocoaPods~~

This group would be under the total control of CocoaPods and users should be warned that they risk to loose changes if they edit it. The group would also facilitate the de-integration feature in case a target is removed from the Podfile.

**Comment by segiddins** [comment]
Environment header has been removed as of 0.38, I believe!
