### ISSUE TITLE
How ignore podspec dependency version?

### ISSUE THREAD

**Issue by scott925** [CocoaPods/CocoaPods#12476]
in Podfile, we have two pods use

pod 'A', '1.3.0'
pod 'B', '1.2.1'

but in B's podspec have the fllow :
s.dependency 'A', '~> 1.2.1'

**Directly causing dependency conflicts.**

There are many similar situations in our project.

Are there any better ways to resolve this issue besides modifying the dependencies of the sub-libraries? We don't want to modify them one by one.

**Comment by paulb777** [comment]
This is fundamental to what CocoaPods does as a package manager. It enables the owner of pod B to release their library and promise that it will work with any 1.2.x version, but not anything beyond 1.3.0. - So no.
