### ISSUE TITLE
pod install

### ISSUE THREAD

**Issue by Mahendrasaini7734** [CocoaPods/CocoaPods#12478]
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Developer+workspace+file+reference+type+is+not+yet+supported+%28Runner.xcodeproj%29&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
arjun@192 ios % 

Error running pod install
Error launching application on iPhone 15 Pro Max.

esako solve karo mere pod install h fir bhi

**Comment by paulb777** [comment]
No CocoaPods issues described here. Please follow template guidance.
