### ISSUE TITLE
Add `prepare_command` to Specification DSL

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1247]
Give the recent introduction of the `resources_bundle` the usage case for the specification hooks are exhausting. It has been agreed to drop the `post_install` hook and to replace the `pre_install` hook with the `prepare_command` attribute.

The `prepare_command` would take a bash script (a string) and this script would be executed before the Pods project is built to allow the script to generate and modify the files which would be picked by the other attributes.

The script could simply execute a more complex script stored in the repository of the Pod.

**Comment by kenoy** [comment]
Hi, I'm new to CocoaPods,  can you please confirm whether post_install hook is still working in PodFile?  I am a bit confused as the documentation is still on the website https://guides.cocoapods.org/syntax/podfile.html#post_install suggesting its valid but reading this thread suggests it has been dropped.  I have tried to do some logging within the hook and using version 0.37.2 and it appears it wasn't going through the post_install, so just wanted confirmation.  Thanks!

**Comment by orta** [comment]
It still exists @kenoy
