### ISSUE TITLE
 _swift_FORCE_LOAD$_swiftCompatibility56 When Building Flutter iOS App with CocoaPods

### ISSUE THREAD

**Issue by polo8619** [CocoaPods/CocoaPods#12486]
I am encountering an error when trying to build my Flutter iOS app for the simulator using CocoaPods. The build fails with the following error message:

Error (Xcode): Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56
Could not build the application for the simulator.
Despite following the recommended steps to resolve this issue, the error persists.

Environment
Flutter Version: 3.22.2
Xcode Version: 14.2.0
CocoaPods Version: 1.15.2
iOS Deployment Target: 15.0
Swift Version: 5.0

Dependencies in pubspec.yaml:

dependencies:
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  another_flutter_splash_screen: ^1.2.0
  google_nav_bar: ^5.0.6
  provider: ^6.1.2
  flutter_splash_screen: ^3.0.0
  sign_in_button: ^3.2.0
  cloud_firestore: ^5.0.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  http: ^1.2.1
  device_preview: ^1.2.0
  firebase_messaging: ^15.0.2
  location: ^7.0.0
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.7.0

Podfile:

platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['OTHER_LDFLAGS'] = ['$(inherited)']
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end

What did you do?
I ran pod install followed by flutter run.

What did you expect to happen?
I expected the project to build successfully without errors.

What happened instead?
The build failed with the error Undefined symbol: __swift_FORCE_LOAD_$_swiftCompatibility56.

CocoaPods Environment

### Stack

CocoaPods : 1.11.2
Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin20]
RubyGems : 3.0.3
Host : macOS 12.3.1 (21E258)
Xcode : 14.2 (14C18)
Git : git version 2.32.1 (Apple Git-133)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
cocoapods - git - https://github.com/CocoaPods/Specs.git @ 78d6b1d02da3c071bb1b09ffbb8e07be7ed4e5e3

Installation Source
Executable Path: /usr/local/bin/pod

Plugins
cocoapods-deintegrate : 1.0.5
cocoapods-plugins : 1.0.0
cocoapods-search : 1.0.1
cocoapods-trunk : 1.6.0
cocoapods-try : 1.2.0

**Comment by paulb777** [comment]
Likely a newer Xcode version is needed. Please take any follow up questions to a Flutter support channel
