### ISSUE TITLE
Expose only required headers

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1249]
Currently CP exposes all the headers of all the targets in the xcconfings. This causes issues and should be fixed.

This is not possible at the moment because the `:exclusive` option of the Podfile DSL is used to integrate test targets and thus relies on the exposition of the headers of the parent target.

Depends on https://github.com/CocoaPods/CocoaPods/issues/840

**Comment by segiddins** [comment]
There will be an option for 'headers-only` inheritance that is replacing 'exclusive'
