### ISSUE TITLE
Provide support for integrating static libraries

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1250]
The analyzer could inspect the integrated target to detect if it is a static library and the installer could adjust the link settings accordingly.

See https://github.com/CocoaPods/CocoaPods/issues/117.

**Comment by yanzhiwei147** [comment]
+1 for this feature.
But i found elapse long time, it can will provide In the near future?

**Comment by segiddins** [comment]
Pretty sure we can close this, as the officially supported way of having pod dependencies of a lib is to make that lib a pod itself?

**Comment by neonichu** [comment]
:+1:
