### ISSUE TITLE
Vulnerabilities in CocoaPods Open the Door to Supply Chain Attacks Against Thousands of iOS and MacOS Applications

### ISSUE THREAD

**Issue by tanaakk-tientranv** [CocoaPods/CocoaPods#12524]
Hi @orta cc: CocoaPods Team

This post may address the same issue mentioned by your friend Raf-wtag above. However, I would appreciate it if you could review it for me. E.V.A has published a new article dated July 1, 2024, which you can find [here](https://www.evasec.io/blog/eva-discovered-supply-chain-vulnerabities-in-cocoapods), while your blog post is from last year. Could you kindly check if your blog post from last year has fully resolved the new issue discussed in E.V.A's article?

As a user rather than an author, I am concerned about whether I would be affected by this issue.

Thank you very much for your assistance.

_Originally posted by @tanaakk-tientranv in https://github.com/CocoaPods/CocoaPods/issues/12448#issuecomment-2268221006_

**Comment by orta** [comment]
Yep, it took E.V.A till July to do the same writeup

**Comment by nguyenvanhungjp** [comment]
Hi @orta  cc: CocoaPods Team
I have follow up questions.
Do pods that were uploaded to Cocoapods before 10/2023 contain malicious code?
Can current built apps get those pods from Cocoapods?
I would appreciate it if you would answer my question soon.
