### ISSUE TITLE
CDN with stale data

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#12520]
We (I) accidentally triggered an issue which caused the CDN to require a new successful GitHub Actions build - this doesn't seem to have been an easy thing to get up and running and we've started talking to GitHub support team about trying to unblock ourselves. 

Unsure how long it will take, but you're welcome to subscribe to this issue to keep notified.

**Comment by igor-makarov** [comment]
So it looks like Github Support have unblocked the issue and the periodic deploy is back on track! Closing this.
