### ISSUE TITLE
LoadError - cannot load such file -- ffi_c

### ISSUE THREAD

**Issue by mfathy70** [CocoaPods/CocoaPods#12538]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by sultansharma** [comment]
Check your ruby version with ruby-v ,
Check its latest of not, some time we have multiple ruby,
Set path
Reinstall ffi with sudo gem install ffi , May this will resolve your issue

**Comment by youngho-roundu** [comment]
thanks sultansharma. 

It work on me. [sudo gem install ffi ]
