### ISSUE TITLE
undefined method `basename' for an instance of String

### ISSUE THREAD

**Issue by luxinxuan** [CocoaPods/CocoaPods#12599]
cocopod install show error
undefined method `basename' for an instance of String

ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin23]
cocopod -v
1.15.2

**Comment by luxinxuan** [comment]
cocopod install show error：
[!] Error installing ImageClick
[!] Failed to download 'ImageClick': undefined method `basename' for an instance of String

**Comment by liyongping-pixocial** [comment]
rvm install 2.7 --disable-binary

**Comment by luxinxuan** [comment]
> cocopod install show error undefined method `basename' for an instance of String
> 
> ruby -v ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin23] cocopod -v 1.15.2

**Comment by luxinxuan** [comment]
> rvm install 2.7 --disable-binary rvm use 2.7.2 --default
> 
> ensure ruby version use 2.7.2, cocoapod version use 1.15.2

no work
