### ISSUE TITLE
PBXFileSystemSynchronizedRootGroup causing pod init to fail with CocoaPods 1.15.2a

### ISSUE THREAD

**Issue by RoyAlfi** [CocoaPods/CocoaPods#12627]
Hello,

I'm encountering an issue when trying to initialize CocoaPods in my project with pod init. The command fails with the following error message related to the PBXFileSystemSynchronizedRootGroup object in the Xcode project file.

Steps to Reproduce:
Set up a new Xcode project using Xcode version 16.0.
Run pod init to initialize the Podfile.
Expected Behavior:
The pod init command should create a Podfile for the project without any errors.

Actual Behavior:
The command fails with the following error message:

csharp
Copy code
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "path"=>"Sablet", "sourceTree"=>"<group>"}`
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
Environment:
CocoaPods Version: 1.15.2
CocoaPods Plugins:
cocoapods-deintegrate : 1.0.5
cocoapods-plugins : 1.0.0
cocoapods-search : 1.0.1
cocoapods-trunk : 1.6.0
cocoapods-try : 1.2.0
Xcode Version: 16.0 (16A242d)
macOS Version: macOS 15.0.1 (24A348)
Ruby Version: 2.6.10p210
RubyGems Version: 3.0.3.1
Git Version: git version 2.39.5 (Apple Git-154)
Stack Trace:
vbnet
Copy code
   CocoaPods : 1.15.2
        Ruby : ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin24]
    RubyGems : 3.0.3.1
        Host : macOS 15.0.1 (24A348)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/

Error:
RuntimeError - `PBXGroup` attempted to initialize an object with unknown ISA `PBXFileSystemSynchronizedRootGroup` from attributes: `{"isa"=>"PBXFileSystemSynchronizedRootGroup", "path"=>"Sablet", "sourceTree"=>"<group>"}`
Additional Information:
This issue seems to be related to changes introduced in newer versions of Xcode, specifically with the PBXFileSystemSynchronizedRootGroup object. After some research, it appears that the xcodeproj gem used by CocoaPods may not recognize this new object type.

I've attempted the following troubleshooting steps without success:

Updated CocoaPods to the latest version (1.15.2).
Updated the xcodeproj gem to the latest version.
Regenerated the .xcodeproj file by deleting and reopening the project in Xcode.
Verified that I have the correct versions of Ruby, RubyGems, and Xcode installed.
Would you please advise on how to resolve this issue, or if it is a bug, how it can be fixed in future updates?

Thank you for your assistance!

**Comment by eomonteiro** [comment]
Also update the below version objectVersion = 77; to objectVersion = 56;

Right Click on YOUR_PROJECT_NAME.xcodeproj Show Package Contents then open project.pbxproj
Replace every PBXFileSystemSynchronizedRootGroup with PBXGroup

**Comment by Gustavo0033** [comment]
Hello, I Tried this solution but my project still with some problem, after i replace every PBXFileSystemSynchronizedRootGroup with PBXGroup and reopen the project, my files desappeared.

<img width="294" alt="Captura de Tela 2024-10-11 às 15 03 11" src="https://github.com/user-attachments/assets/12d00777-b7f6-4edb-8f8c-e5a689ac11a1">

**Comment by eomonteiro** [comment]
Change only the word "PBXFileSystemSynchronizedRootGroup" to "PBXGroup"

**Comment by Gustavo0033** [comment]
I did it, but is not working.

I had three parts in this code with PBXFileSystemSynchronizedRootGroup and i changed to PBXGroup

<img width="625" alt="Captura de Tela 2024-10-11 às 16 45 42" src="https://github.com/user-attachments/assets/b691fab6-fbd7-45d2-8c4b-3c601a21ab94">

**Comment by eomonteiro** [comment]
try #12625

**Comment by LuisMoraEL** [comment]
I tried this, but is not working and I only changed "PBXFileSystemSynchronizedRootGroup" to "PBXGroup"
### Command

```
/Users/sedeam/.rbenv/versions/3.3.5/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-darwin24]
    RubyGems : 3.5.16
        Host : macOS 15.0.1 (24A348)
       Xcode : 16.0 (16A242d)
         Git : git version 2.39.5 (Apple Git-154)
Ruby lib dir : /Users/sedeam/.rbenv/versions/3.3.5/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppRKESP32' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppRKESP32
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'GoogleSignIn'

end
```

### Error

```
ArgumentError - [Xcodeproj] Unable to find compatibility version string for object version `77`.
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcodeproj-1.25.1/lib/xcodeproj/project.rb:85:in `initialize'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/project.rb:48:in `initialize'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb:82:in `new'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb:82:in `create_project'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/pods_project_generator/project_generator.rb:73:in `generate!'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:16:in `generate!'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:320:in `block in create_and_save_projects'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:315:in `create_and_save_projects'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:307:in `generate_pods_project'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:183:in `integrate'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:170:in `install!'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/sedeam/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/Users/sedeam/.rbenv/versions/3.3.5/bin/pod:25:in `load'
/Users/sedeam/.rbenv/versions/3.3.5/bin/pod:25:in `<main>'
