### ISSUE TITLE
pod lib lint is broken

### ISSUE THREAD

**Issue by kstenerud** [CocoaPods/CocoaPods#12664]
* [x ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint` on a fresh, very basic framework project.

## What did you expect to happen?

Successful linting

## What happened instead?

It fails with various errors, such as:

* `//privateTarget Support Files/MyFramework/MyFramework-umbrella.h:13:9: error: double-quoted include "MyFramework.h" in framework header, expected angle-bracketed instead`
* `Sandbox: rsync.samba(44452) deny(1) file-write-create /Users/karl.stenerud/Library/Developer/Xcode/DerivedData/App-gnevzkrtpocjzeduklkdbvflsxod/Build/Products/Release-iphonesimulator/App.app/Frameworks/MyFramework.framework/_CodeSignature (in target 'App' from project 'App')`

### Stack

```
   CocoaPods : 1.15.2
        Ruby : ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [arm64-darwin22]
    RubyGems : 3.2.33
        Host : macOS 14.7 (23H124)
       Xcode : 15.4 (15F31d)
         Git : git version 2.39.3 (Apple Git-146)
Ruby lib dir : /Users/karl.stenerud/.rbenv/versions/3.0.6/lib
Repositories : ariadnext-idcheckio-axt-podspecs - git - https://git-externe.rennes.ariadnext.com/idcheckio/axt-podspecs.git @ 2ebd182962d6b2812d1a82909d413b80b6b56867

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 0ad68fd861cfd5cc53d5e5061cf7f6faedfd637f

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/karl.stenerud/.rbenv/versions/3.0.6/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

https://github.com/kstenerud/cocoapods-framework-issue

**Comment by Saimoness** [comment]
We’re encountering the same problem with double-quoted include "pb.h" in framework header, expected angle-bracketed instead warnings when using:

```ruby
gem 'cocoapods', '~> 1.15'
```

I’ve attached a screenshot for reference. Despite troubleshooting and attempted modifying CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER, we haven’t been able to resolve this. 
Any insights would be greatly appreciated. Thank you!

<img width="1204" alt="Screenshot 2024-10-28 at 19 21 45" src="https://github.com/user-attachments/assets/d366a906-473e-4a12-8c4a-a26494163c75">

**Comment by m6vrm** [comment]
Pin xcodeproj to earlier version in `Gemfile`: `gem 'xcodeproj', '1.25.1'`
Xcodeproj was broken in 1.26.0: https://github.com/CocoaPods/Xcodeproj/issues/990

Also, you can remove `Gemfile.lock` from `.gitignore` to avoid errors with updated dependencies in future.

**Comment by Saimoness** [comment]
> Pin xcodeproj to earlier version in Gemfile: `gem 'xcodeproj', '1.25.1'` It was broken in 1.26.0: [CocoaPods/Xcodeproj#990](https://github.com/CocoaPods/Xcodeproj/issues/990)
> 
> Also, you can remove Gemfile.lock from .gitignore to avoid errors with updated dependencies in future.

Thanks, @m6vrm for pointing out the bug in 1.26.0. Pinning the xcodeproj gem to version 1.25.1 indeed resolves the issue. This should be the accepted answer.

**Comment by xiushaomin** [comment]
when will resolve this issue?

**Comment by BestiOSDev** [comment]
> when will resolve this issue?

use cocoapods 1.16.0

**Comment by kstenerud** [comment]
1.16.0 fixes the headers issue, but the sandbox issue remains.

**Repro case**: https://github.com/kstenerud/cocoapods-framework-issue

### Steps to reproduce:

```
pod lib lint
```

#### Output

```
$ pod lib lint

 -> MyFramework (1.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Building targets in dependency order
    - NOTE  | [iOS] xcodebuild:  note: Target dependency graph (3 targets)
    - NOTE  | [iOS] xcodebuild:  note: Signing static framework with --generate-pre-encrypt-hashes (in target 'Pods-App' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  error: Sandbox: rsync.samba(85833) deny(1) file-write-create /Users/karl.stenerud/Library/Developer/Xcode/DerivedData/App-eigfkkgvdgrbqzfdfjlovpbjzurq/Build/Products/Release-iphonesimulator/App.app/Frameworks/MyFramework.framework/_CodeSignature (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  error: Sandbox: rsync.samba(85834) deny(1) file-write-create /Users/karl.stenerud/Library/Developer/Xcode/DerivedData/App-eigfkkgvdgrbqzfdfjlovpbjzurq/Build/Products/Release-iphonesimulator/App.app/Frameworks/MyFramework.framework/.Info.plist.Pwo7uI (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  error: Sandbox: rsync.samba(85834) deny(1) file-write-create /Users/karl.stenerud/Library/Developer/Xcode/DerivedData/App-eigfkkgvdgrbqzfdfjlovpbjzurq/Build/Products/Release-iphonesimulator/App.app/Frameworks/MyFramework.framework/.MyFramework.6bX75E (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/289ffcb4-455d-11ef-953d-e2437461156c/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]

[!] MyFramework did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
```

### Discussion

This error occurs because the `App.xcworkspace` created by cocoapods to validate the podfile has `ENABLE_USER_SCRIPT_SANDBOXING` set to `YES`:

<img width="944" alt="Screenshot 2024-10-29 at 09 23 09" src="https://github.com/user-attachments/assets/63bcc219-e7ff-4213-a8c4-5c4b751298f3">

**Comment by hackiftekhar** [comment]
I'm also facing exactly same issue

**Comment by avelino-rodrigues** [comment]
Same issue here with ENABLE_USER_SCRIPT_SANDBOXING...

Adding this in podspec seems to workaround the issue
```
s.xcconfig = {
        'ENABLE_USER_SCRIPT_SANDBOXING' => 'NO',
    }
```

**Comment by hackiftekhar** [comment]
Thanks @avelino-rodrigues This worked for me as a workaround.

**Comment by amorde** [comment]
@kstenerud thank you for the report and the example project with the easy repro. I've put up a [PR](https://github.com/CocoaPods/CocoaPods/pull/12669) and will get out a patch release as soon as I can.

**Comment by khoogheem** [comment]
did this go to home-brew not seeing this version available
