### ISSUE TITLE
Error While Running "pod --version"  Plz help !!!!

### ISSUE THREAD

**Issue by KISHANsingh0001** [CocoaPods/CocoaPods#12688]
<img width="795" alt="Screenshot 2024-11-08 at 2 36 56 PM" src="https://github.com/user-attachments/assets/cd6b4bf4-c639-4274-9319-d41677fd2fc1">

**Comment by amorde** [comment]
The command is working fine, the warnings are related to your rubygems environment but you can see the last line in the output is `1.15.2` which is the version of cocoapods you have installed.
