### ISSUE TITLE
"pod install" converts *.xcodeproj/project.pbxproj to XML format which prevents merging branches

### ISSUE THREAD

**Issue by oleganza** [CocoaPods/CocoaPods#1275]
I have two branches that have diverged pbxproj files (iOS6 maintenance branch and iOS7 branch with some files added/reordered/removed). Normally, I have no problem applying fixes in iOS6 branch to iOS7 — git is capable of merging pbxproj files.

Now I need to add CocoaPods support to my project, and keep the ability to merge changes in iOS6 branch to iOS7 branch. I don't care if iOS6 branch has CocoaPods or not.
1. If I install pods on iOS6 branch, then I wouldn't be able to merge these changes to iOS7 branch because project file would be completely different (and reapplying all iOS7 changes by hand is very cumbersome at this point).
2. If I install pods on iOS7 branch, then I equally wouldn't be able to merge iOS6 to iOS7 for the same reason. (Only now XML file will be on iOS7 side.)

If "pod install" was just adding the stuff it needs and keeping old "plist" pbxproj format, I'd be able to merge my branches without a problem.

My question: is there a possibility to disable XML conversion and keep basic operation working? Or maybe converting to XML on demand in a temp file? Or supporting plist parsing along with XML in ruby scripts? 

Thanks.

**Comment by michaelochs** [comment]
I ran into the same problem, however, the current Xcode betas do NOT update the project file back to the old format. This could become a big issue, soon!

**Comment by kylef** [comment]
@michaelochs CocoaPods 0.36 no longer does this.

**Comment by itsthejb** [comment]
Had never experience this problem before, but it's creeping in with Xcode 7.2.1 and a new project that was probably created in 7.1+

**Comment by RobertSheaO** [comment]
This is still an issue, and a rather annoying one. Is there an update on how to prevent this from happening? I really hate having to open every *.xcodeproj and forcing Xcode to save it in ASCII format, vs. XML.

**Comment by VanMen** [comment]
A work around that take to solve this issue is like below:
1. take a backup of android & ios directory
2. delete android & ios directory
3. in project folder execute "react-native eject" which will create android & ios directory.
4. just in case you have some custom setting you can take it from the backup in step 1.
