### ISSUE TITLE
A spec should not be able to use `dependencies=` and pass validation.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#1369]
[This spec PR](https://github.com/CocoaPods/Specs/pull/4082) introduced a spec that uses `Specification#dependencies=` yet was able to [pass validation](https://travis-ci.org/CocoaPods/Specs/builds/11371977#L163) on Travis.

This in turn caused http://cocoapods.org to go down.

**Comment by segiddins** [comment]
I'm going to close this as a won't-fix edge case -- the exception will always happen, and that will prevent the invalid DSL usage from ever getting to the linter.
