### ISSUE TITLE
Xcode 5 and iOS 7 Linker Error

### ISSUE THREAD

**Issue by azamsharp** [CocoaPods/CocoaPods#1400]
When the app builds it gives the following error message: 

ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It used to work just fine! I am now targeting iOS 7 and Cocoapods is running into errors.

**Comment by dariodepasquale** [comment]
Very good Mal3k: your solution worked for me.

**Comment by pikaboo** [comment]
this solution: 
```
post_install do | installer |
    installer.project.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
end
```

does not work for me

everytime i update the pods, i have to manually change the active architecture to NO
is it possible to make it automatic somehow
