### ISSUE TITLE
When Error Ocurrs on `pod install`, no Cleaning of `.git` folders is done in `Pods` 

### ISSUE THREAD

**Issue by fabb** [CocoaPods/CocoaPods#1408]
When `pod install` aborts due to an error, the cleaning of `.git` and `.svn` directories is not done. Even when doing a second successful `pod install` afterwards, the `.git` folders from previously, before the error happened, correctly fetched pods are not cleaned.

The resulting problem is that the client project's git thinks, that this pod is a submodule, and does not display the contents of this pod's folder in the diff. As I want to commit the downloaded pods to my git repo, the files of this pod are missing for others / CI that checks out the git repo.

I think that cleaning should be done no matter if an error happens or not.

**Comment by kylef** [comment]
I can no longer reproduce this issue, appears to be fixed.
