### ISSUE TITLE
Link Pods Headers to Test Target

### ISSUE THREAD

**Issue by fabb** [CocoaPods/CocoaPods#1411]
I use some libraries from my main target in my test target too. This leads to a major problem:
1. If I use a plain Podfile, the headers of this libs cannot be found from the test target
2. If I follow http://stackoverflow.com/a/17885961/354018 and add `link_with ['MainTarget', 'MainTargetTests']` to my Podfile, the test target compiles fine, starts running, but crashes due to the following problem. I namely use the `Mantle` pod. the app crashes even before the tests start, but in the main target's `applicationDidBecomeActive:` method. There, a Mantle class is trying to be created which crashes in an assertion where `isSubclassOfClass:` fails, even when the tested client class _is_ a subclass of the expected Mantle model class. The only way I can explain this strange error (that does not happen when running the app regularly), is that both the main target and the test target link the library dependency, and when the test target loads the main target via bundle loader, the Mantle classes from the test target overrule the ones from the main target. The failing `isSubclassOfClass:` method compares a main target's class (which is a subclass of the main target's Mantle library model class) with the Mantle library model class - but I guess at this point the test target's Mantle library model class is taken.

... it's hard to explain, when I have some time I can try to create a minimal demonstrating project.

_Workaround:_ The only thing that helped, was _not_ to use `link_with ['MainTarget', 'MainTargetTests']` and add this path to the Header Search Paths of the test target: `"$(PROJECT_DIR)/[..]/Pods/BuildHeaders"` (recursively).

**Comment by daniel-reckoder** [comment]
Hi! Do you know if this is the way to solve it still? Or is there any other solution more elegant than use a no needed pod?

**Comment by karlbecker** [comment]
@daniel-reckoder :
The solution I had came from @kylef earlier in the thread:
```
target :"MyAppName Tests", :exclusive => true do
	# this pod is not used by MyAppName Tests, but we need something here to ensure we properly link cocoapods to the MyAppName Tests target
	# this dummy pod is not part of kylef's solution, but since we don't have anything unique to our test target, I added it here to ensure something unique was present
    pod 'OCMockito'
end
```

**Comment by daniel-reckoder** [comment]
@karlbecker:
That's my current solution as well. I was wondering about a new one where we don't have to use a pod that we don't need. Thanks, anyway!

**Comment by AresDev** [comment]
Any updates about this? Thanks!

**Comment by fulldecent** [comment]
Can anybody document the CORRECT way to do this?

Documentation at https://guides.cocoapods.org/syntax/podfile.html#podfile only says "An example of a more complex Podfile can be:" and posts something that doesn't apply to me.

Then later, "Defining a test target which can access SSZipArchive via Pods" describes a solution.

But when implemented, that produces the error:

> Invalid `Podfile` file: undefined method `inherit!'

Of course in this issue, and https://github.com/CocoaPods/CocoaPods/issues/1411, there is discussion of other people that are doing it the wrong way, apparently.

I thought setting up a Test target would be simple, but I find this is woefully wrong.

**Comment by fulldecent** [comment]
FYI, for anyone else who came here looking to set up a Podfile for an application target AND a test target, the following works for me using cocoapods 0.39. It produces lots of stupid error message which I ignore and seemingly have no consequence. Note: this is for a Swift project which also has (some) Swift pods.

````
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Echo' do
	pod 'Alamofire'
	pod 'AFNetworking'
	pod 'Google/Analytics'
	pod 'Google/AppInvite'
	pod 'Appirater'
	pod 'FDTake'
	pod 'MBProgressHUD'
	pod 'NSData+Base64'
	pod 'TDBadgedCell'
	pod 'FDWaveformView'
	pod 'SwiftyJSON'
end

target 'EchoTests' do
	pod 'Alamofire'
	pod 'AFNetworking'
	pod 'Google/Analytics'
	pod 'Google/AppInvite'
	pod 'Appirater'
	pod 'FDTake'
	pod 'MBProgressHUD'
	pod 'NSData+Base64'
	pod 'TDBadgedCell'
	pod 'FDWaveformView'
	pod 'SwiftyJSON'
end
````

**Comment by neirar** [comment]
@fulldecent, you can do something like this so you don't have to repeat the pods.

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def all_pods
    pod 'Alamofire'
    pod 'AFNetworking'
    pod 'Google/Analytics'
    pod 'Google/AppInvite'
    pod 'Appirater'
    pod 'FDTake'
    pod 'MBProgressHUD'
    pod 'NSData+Base64'
    pod 'TDBadgedCell'
    pod 'FDWaveformView'
    pod 'SwiftyJSON'
end

target 'Echo' do
    all_pods
end

target 'EchoTests' do
    all_pods
end
```

**_However, this didn't work for me_**. I had to remove the test target altogether from the Podfile and set the header search paths of the test target using a config file:

```
PODS_ROOT = ${SRCROOT}/../Pods
HEADER_SEARCH_PATHS = "${PODS_ROOT}/leveldb-library/" "${PODS_ROOT}/leveldb-library/include" $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/AFNetworking" "${PODS_ROOT}/Headers/Public/CorePlot" "${PODS_ROOT}/Headers/Public/Crashlytics" "${PODS_ROOT}/Headers/Public/DateTools" "${PODS_ROOT}/Headers/Public/Fabric" "${PODS_ROOT}/Headers/Public/IBActionSheet" "${PODS_ROOT}/Headers/Public/KiipSDK" "${PODS_ROOT}/Headers/Public/Mixpanel" "${PODS_ROOT}/Headers/Public/Objective-LevelDB" "${PODS_ROOT}/Headers/Public/SOCKit" "${PODS_ROOT}/Headers/Public/SSPullToRefresh" "${PODS_ROOT}/Headers/Public/UrbanAirship-iOS-SDK" "${PODS_ROOT}/Headers/Public/ViewDeck" "${PODS_ROOT}/Headers/Public/leveldb-library" "${PODS_ROOT}/Headers/Public/libzmq" "${PODS_ROOT}/Headers/Public/youtube-ios-player-helper"
```

You also have to make sure you are not linking against the pod library and that there aren't any pod build phases in your test target. As I understand it, the pods are already included in your app target. You don't need to include them again in your test target. But your test target needs to know where your header files are.

**Comment by orta** [comment]
Here are four of our Artsy Podfiles: [Eigen](https://github.com/artsy/eigen/blob/master/Podfile), [Energy](https://github.com/artsy/energy/blob/master/Podfile), [Eidolon](https://github.com/artsy/eidolon/blob/master/Podfile) and [Emergence](https://github.com/artsy/emergence/blob/master/Podfile). All are still on 0.39 syntax. All work fine with extensive test suites. The guides are currently working from the 1.0.0b which has a more explicit syntax for this stuff.

Can people please not bring old threads back to life, this  discussion probably should have been on StackOverflow.

**Comment by zjulili** [comment]
After thousands of builds and modifications of Podfile and project settings. Finally it work for me. 

Just remember to set MyProjectTest : Build Settings -> Objective-C Bridging Header to Empty while MyProject: Build Settings -> Objective-C Bridging Header point to the bridging header file.

My PodFile as below:
`
source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'9.0'
use_frameworks!

target 'MyProject' do
	all pods required by MyProject here

	target 'MyProjectTest' do
		inherit! :search_paths
	end
end
`

pod: 1.1.1
Xcode :8.1
