### ISSUE TITLE
- WARN  | [iOS] Unable to find a license file

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#1415]
this is not working as described in documentation here http://docs.cocoapods.org/specification.html#license
`s.license      = 'MIT'`

`pod spec lint` show warning that: [iOS] Unable to find a license file

**Comment by scfhao** [comment]
I have created a license file named "LICENSE" in my source, but when i run "pod spec lint",it also report "- WARN  | [iOS] license: Unable to find a license file". I try to clean "/Users/<username>/Library/Caches/CocoaPods/", It also not work.

**Comment by segiddins** [comment]
@scfhao please don't comment on two year old issues, it makes it hard to keep track of things. Make sure you're specifying the path correctly in your podspec, as documented in https://guides.cocoapods.org/syntax/podspec.html#license, and ask on a more appropriate forum such as StackOverflow for usage questions. Thanks!

**Comment by rivera-ernesto** [comment]
I think it makes more sense to comment on similar issues instead of opening duplicates. Otherwise just lock all closes issues that you dim "too old" to comment on.

**Comment by PoojaChirp** [comment]
Hi All,

I'm experiencing the same error. I followed the rules suggested in the article-https://guides.cocoapods.org/syntax/podspec.html#license, but I've no luck. The error is seen when I pod lint the spec - 

Unable to read the license file `/<path>/LICENSE.md` for the spec `spec name(11.12.0.0)`

Can someone please suggest a solution.

Thanks!

**Comment by amorde** [comment]
@PoojaChirp This issue is quite old - if you are experiencing a bug could you submit another issue with steps to reproduce?

**Comment by jbarros35** [comment]
I still reproduce it I'm pretty sure. Installed this today and still running and copied exactly the same code on documentation.
That's happen today.

**Comment by iliaskarim** [comment]
This issue is apparently still current 5 years after it was opened. To workaround it add the `--allow-warnings` flag.

**Comment by mayoralito** [comment]
2019 and the same thing keeps happening...

**Comment by amorde** [comment]
[This comment](https://github.com/CocoaPods/CocoaPods/issues/1415#issuecomment-29394860) still stands - we would prefer the actual license be specified, whether via the `:text` option or the `:file` option.

Comments mentioning the current year and that something is still occurring do not help. If you would like the behavior changed, please explain your reasoning and address the previous comments on why CocoaPods prefers an actual license. If there is a bug, please submit a new issue with a sample project that reproduces the bug. Thanks!
