### ISSUE TITLE
undefined method 's.ios.prepare_command' (using Cocoapods v0.25)

### ISSUE THREAD

**Issue by zakdances** [CocoaPods/CocoaPods#1424]
I'm using Cocoapods 0.25. Trying to lint a podspec with a platform-specific `prepare_command` generates this error. However, running `s.prepare_command` does not generate an error. Is a platform specific `prepare_command` not allowed? If not, how can I run a script just for iOS or OSX?

**Comment by SandeepAggarwal** [comment]
@fabiopelosin  I want to open a ticket here to include feature having prepare_command different for iOS and MacOSX . 
I wanted to have 2 different build scripts in prepare_command depending upon the platform for whihc there is no option to do so unless the above mentioned feature is added.
I have also posted a question on Stack-Overflow for this issue http://stackoverflow.com/questions/34576430/cocoapod-spec-dynamically-identify-platform
Please consider this request.

**Comment by segiddins** [comment]
@SandeepAggarwal thanks for the feature request, but it's highly unlikely we'll ever implement such a feature.

**Comment by SandeepAggarwal** [comment]
@segiddins Thanks for the feedback. Can you please suggest a work around then for this issue?

**Comment by segiddins** [comment]
Build both binaries in your prepare command?

**Comment by SandeepAggarwal** [comment]
Yes, I am building both binaries, since there is a support for commands like spec.ios.deployment_target,
spec.osx.deployment_target , s.osx.xcconfig and so on..

**Comment by SandeepAggarwal** [comment]
@segiddins @fabiopelosin  Any more inputs from your side for this issue?
