### ISSUE TITLE
Copy Pods Resources phase fails for pods with resource bundle in static library targets

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/CocoaPods#1439]
Let me give you a concrete example of what this means. (CocoaPods 0.25.0)
1. Create a new project (iOS → Framework & Library → Cocoa Touch Static Library) that you name _MyLibrary_
2. Do `pod install` with the following Podfile:
   
   ``` ruby
   platform :ios, '6.1'
   
   pod 'HockeySDK', '3.5.0rc2'
   ```
3. Do Product → Archive

It will fail with the following errors:

```
PhaseScriptExecution "Copy Pods Resources" /Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/IntermediateBuildFilesPath/MyLibrary.build/Release-iphoneos/MyLibrary.build/Script-4DD37CF050C74B59B7B12846.sh
    cd /Users/0xced/Projects/Experiments/MyLibrary
    /bin/sh -c /Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/IntermediateBuildFilesPath/MyLibrary.build/Release-iphoneos/MyLibrary.build/Script-4DD37CF050C74B59B7B12846.sh

/Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/BuildProductsPath/Release-iphoneos/HockeySDKResources.bundle
sending incremental file list
HockeySDKResources.bundle/
file has vanished: "/Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/BuildProductsPath/Release-iphoneos/HockeySDKResources.bundle/IconGradient.png"
file has vanished: "/Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/BuildProductsPath/Release-iphoneos/HockeySDKResources.bundle/IconGradient@2x.png"
file has vanished: "/Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/BuildProductsPath/Release-iphoneos/HockeySDKResources.bundle/authorize_denied.png"
file has vanished: "/Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/BuildProductsPath/Release-iphoneos/HockeySDKResources.bundle/authorize_denied@2x.png"
[...]
HockeySDKResources.bundle/ro.lproj/
file has vanished: "/Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/BuildProductsPath/Release-iphoneos/HockeySDKResources.bundle/ro.lproj/HockeySDK.strings"
HockeySDKResources.bundle/ru.lproj/
file has vanished: "/Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/BuildProductsPath/Release-iphoneos/HockeySDKResources.bundle/ru.lproj/HockeySDK.strings"
HockeySDKResources.bundle/zh-Hans.lproj/
file has vanished: "/Users/0xced/Library/Developer/Xcode/DerivedData/MyLibrary-bmutqcnlbqlgmkbhsvqyalhrtqsg/Build/Intermediates/ArchiveIntermediates/MyLibrary/BuildProductsPath/Release-iphoneos/HockeySDKResources.bundle/zh-Hans.lproj/HockeySDK.strings"

sent 1473 bytes  received 699 bytes  4344.00 bytes/sec
total size is 167225  speedup is 76.99
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1122) [sender=3.0.9]
Command /bin/sh failed with exit code 24
```

I believe this is a consequence of #1329 which added the `--copy-links` to rsync and changed `TARGET_BUILD_DIR` to `BUILT_PRODUCTS_DIR`.

Here is how the structure of the DerivedData directory looks like:
![MyLibrary structure](https://f.cloud.github.com/assets/51363/1262003/59249c4c-2c38-11e3-9144-4909b8922610.png)

As you can see, `HockeySDKResources.bundle` inside `BuildProductsPath/Release-iphoneos` is an empty directory (actually contains empty localization folder) instead of a symlink.

@blakewatters, any idea of what is going wrong here?

Final thought: Copy resources v2 (#743) was an awesome improvement over the previous implementation but why keep this `Pods-resources.sh` script that is causing more pain than it should? Why not create a _Product_ per resource bundle target and add it to the _Copy Bundle Resources_ phase instead of running this _Copy Pods Resources_ script?
![Products > MapBox.bundle](https://f.cloud.github.com/assets/51363/73257/973d028e-6038-11e2-9014-23bb47d763a0.png)

**Comment by didge** [comment]
@0xced, thanks for your final note, I just added HockeyApp to my project and I never would have figured this out!

**Comment by BluMist** [comment]
@didge, what did you end up doing? I don't quite understand the manual moving part.

**Comment by didge** [comment]
@BluMist, a build phase script called Copy Pods Resources was automatically added to my library target after executing ```pod install```.  Using Xcode, I opened my project workspace and created a new build phase script in my app target identical to the one in the library target.  I then deleted the one in the library target.

**Comment by dnkoutso** [comment]
Hit this problem as well. I understand the notion that static libraries should be converted to Pods but this is not realistic for some projects. We have static libraries as targets defined in our Podfile.

I think CocoaPods should not add the script for static library targets.

This is a very simple change to fix (one would have to re-integrate the targets). There might still need to be some work to fixup existing projects that have this script added to their targets.

Perhaps by adding an `remove_copy_resources_script_phase` method.

Here's the diff:

```ruby
diff --git a/lib/cocoapods/installer/user_project_integrator/target_integrator.rb b/lib/cocoapods/installer/user_project_integrator/target_integrator.rb
index 8b3c0ab..2987865 100644
--- a/lib/cocoapods/installer/user_project_integrator/target_integrator.rb
+++ b/lib/cocoapods/installer/user_project_integrator/target_integrator.rb
@@ -207,6 +207,7 @@ module Pod
         def add_copy_resources_script_phase
           phase_name = 'Copy Pods Resources'
           native_targets_to_integrate.each do |native_target|
+            next if native_target.symbol_type == :static_library
             phase = create_or_update_build_phase(native_target, phase_name)
             script_path = target.copy_resources_script_relative_path
             phase.shell_script = %("#{script_path}"\n)
```

/cc @segiddins @orta

**Comment by segiddins** [comment]
@dnkoutso it won't work due to other linker settings, and it's simply not a configuration that we want to support. In the meantime, you're free to hack around this in your post install hook
