### ISSUE TITLE
Duplicate code in generated prefix header file for Pods with subspecs

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaPods/CocoaPods#1449]
The current [prefix_header](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/prefix_header.rb) generator adds the [`prefix_header_contents`](http://docs.cocoapods.org/specification.html#prefix_header_contents) or [`prefix_header_file`](http://docs.cocoapods.org/specification.html#prefix_header_file) multiple times:
- Once for the Pod spec.
- [Additional](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/prefix_header.rb#L56) times for each subspec.

For instance the following Podspec:

``` ruby
Pod::Spec.new do |s|
    s.name          = "NBUCore"
    # ...
    s. prefix_header_contents = '#import "NBUCorePrivate.h"'

    s.subspec 'UI' do |su|
        su.source_files = 'Source/UI/*.{h,m}'
    end

    s.subspec 'Helpers' do |sh|
        sh.source_files = 'Source/Helpers/*.{h,m}'
    end

    s.subspec 'Additions' do |sa|
        sa.source_files = 'Source/Additions/*.{h,m}'
    end

    s.subspec 'Dashboard' do |sd|
        sd.source_files = 'Source/Dashboard/*.{h,m}'
        sd.resources    = 'Source/Dashboard/*.{xib}'
    end
end
```

Results in the following prefix file:

``` obj-c
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#endif

#import "Pods-environment.h"
#import "NBUCorePrivate.h"

#import "NBUCorePrivate.h"

#import "NBUCorePrivate.h"

#import "NBUCorePrivate.h"

#import "NBUCorePrivate.h"

```

**Comment by lemonkey** [comment]
Confirmed this is happening in 0.35.0.

**Comment by sstadelman** [comment]
confirmed also in 0.35.0
