### ISSUE TITLE
Cocoapods 0.26.1 build fails for device

### ISSUE THREAD

**Issue by johnryan** [CocoaPods/CocoaPods#1450]
After upgrading to 0.26.1 my project build fails when building for device with lots of arm64 errors and "Could not build module" errors. Builds fine in the simulator.

**Comment by k06a** [comment]
Just set `CLANG_ENABLE_MODULES = NO` and got error in this file:
```
#import <Foundation/Foundation.h>

...

typedef BOOL            jboolean;
        ^^ 
        J2ObjC_common.h:68:9: Unknown type name 'BOOL'
```
