### ISSUE TITLE
The Analyzer should store inspected build setting per build configuration name

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1466]
Currently the analyzer, while computing the build setting which should be inherited from the user target, resolves and stores a single value for all the build configurations. This approach is not robust as build setting might differ.

Related: #1462

**Comment by segiddins** [comment]
@mrackwitz is there any point in keeping this issue open? I think the target inspector is plenty robust after your latest refactor.

**Comment by mrackwitz** [comment]
My latest changes around the analyzer / target inspector didn't really improved anything around that.
But it seems that Xcodeproj's methods to resolve common build settings became just more robust. If any build setting has multiple values, then it will raise an exception.
I don't think we can or want to do anything about that as it would mean a drastic increase of complexity if we would take different platforms or architectures per build configuration into account.
