### ISSUE TITLE
pod install failing when using :git => x and the podfile version changing on master

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#1470]
So, I have this in my podfile

```
pod 'ORKeyboardReactingApplication', :git => 'https://github.com/orta/ORSimulatorKeyboardAccessor.git'
```

making a podfile of this a week ago (with some cropping )

```
PODS:
  - ORKeyboardReactingApplication (0.5)

DEPENDENCIES:
  - ORKeyboardReactingApplication (from `https://github.com/orta/ORSimulatorKeyboardAccessor.git`)

EXTERNAL SOURCES:
  ORKeyboardReactingApplication:
    :git: https://github.com/orta/ORSimulatorKeyboardAccessor.git

SPEC CHECKSUMS:
  ORKeyboardReactingApplication: 6588f82a81d45e86f33793d1f2a32a187f0e9a66

COCOAPODS: 0.25.0
```

Then I come along and do and update: https://github.com/orta/ORSimulatorKeyboardAccessor/commit/aea1dcae43efaac94b950808fa34ebb6cf461f50 bumping the version to `0.5.1`

This means the head of that custom repo doesn't match the version expected in the Podfile.lock anymore. My expectation ( and the [guide](http://guides.cocoapods.org/using/the-podfile.html) hints at this ) is that for this lib `:git` will always use head/master, but it's ignoring that and failing with this error:

```
[!] Required version (ORKeyboardReactingApplication (from `https://github.com/orta/ORSimulatorKeyboardAccessor.git`)) not found for `ORKeyboardReactingApplication`.
Available versions: 0.5.1
```

This is an expectations thing, but I would have thought it would have done one of two things: 
- Use the SHA from the last pod install ( this isn't currently in the podfile.lock though) 
- Use use master every time ( this is kinda what I was expecting, you do a pod install, and it will grab the latest because I want it always from head )

/cc @dstnbrkr

**Comment by Ismaran** [comment]
Run this code on Terminal, this works!!
sudo xcode-select --switch /Applications/Xcode.app

**Comment by User2004** [comment]
install pod follow following link steps for best result

https://webappcodes.com/integarte-cocoapods-in-xcode-project-objective-c-or-swift
