### ISSUE TITLE
CocoaPods tests rely on being online

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#1477]
Reference [tweet](https://twitter.com/GFontenot/status/389772304550756353) " _Honestly, the main issue I’ve run into with contributing is the dev setup. Tests have odd dependencies, require net access_ "

**Comment by segiddins** [comment]
I think now it's only the integration specs. We could definitely fix that in a super hack way (by injecting a 'hack' ruby file to override sources so we can use submodules or a tarball), but I'm not sure if thats worth it. Thoughts, @mrackwitz ?

**Comment by mrackwitz** [comment]
Would be nice to have, but it's for me still not top priority. Also I think it's good that we test the actual download code paths.

**Comment by segiddins** [comment]
:+1:

**Comment by cbowns** [comment]
:-1: I've worked on a slow connection on a couple projects which have tests like this, and it's maddening. Please reconsider this, especially if it's just one or two tests which require network access. Having an `--offline` flag, or making it easy to skip them, or something.

Not all developers have always-on, super-fast, unmetered wifi connections. Please consider ways to make the project easy and accessible for them.

**Comment by segiddins** [comment]
It's only the integration specs that have a net dependency, and they're specifically testing things that use the network. The unit and functional specs should all work offline. We'd welcome a PR making the integration specs work offline, but it's just not worth the effort for us at the moment.
