### ISSUE TITLE
pod setup -> [!] The `master` repo is not a git repo

### ISSUE THREAD

**Issue by mailworks** [CocoaPods/CocoaPods#1501]

**Comment by JRG-Developer** [comment]
For the Google users that wind up here...

It's also possible you need to set the active Xcode (especially, if you're install/uninstall Xcode betas).

In this case, the command you most likely need is this:

   sudo xcode-select -switch /Applications/Xcode.app/

Of course, change the path to your Xcode app if its not in this location.

**Comment by Bersaelor** [comment]
@JRG-Developer same issue happening with cocoapods 1.1.0.rc.2 and Xcode8 when trying to 'pod _1.1.0.rc.2_ trunk push'.
