### ISSUE TITLE
Getting .xcassets compilation to work for development pods?

### ISSUE THREAD

**Issue by epologee** [CocoaPods/CocoaPods#1549]
The [newly added compilation of a pod's xcassets](https://github.com/CocoaPods/CocoaPods/pull/1427) uses the following shell script to find and compile any *.xcassets folder relative to the current (presumably the project's) directory:

	if [ `find . -name '*.xcassets' | wc -l` -ne 0 ]
	then
	  DEVICE=`if [ "${TARGETED_DEVICE_FAMILY}" -eq 1 ]; then echo "iphone"; else echo "ipad"; fi`
	  find "${PWD}" -name "*.xcassets" -print0 | xargs -0 actool --output-format human-readable-text --notices --warnings --platform "${PLATFORM_NAME}" --minimum-deployment-target "${IPHONEOS_DEPLOYMENT_TARGET}" --target-device "${DEVICE}" --compress-pngs --compile "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.${WRAPPER_EXTENSION}"
	fi

When using development pods however, it's unlikely that they're in a subfolder of the project directory, rather you'll have them somewhere higher up your folder structure. There are two references to the current folder, one `find .` and one `find "${PWD}"`.

Shouldn't this script accomodate for the case of development pods, somehow referencing the specs and subspecs of a project's dependencies?

**Comment by tchagnon** [comment]
This appears to be fixed in master after 9cd9ce4152c4e7f89aee122a4b5879ccc5c02e82

We had a post_install that twiddled Pods-resources.sh as a workaround for this.  Since 0.36.0, there is no longer a find command for these resources, but the path is still broken until 9cd9ce4152c4e7f89aee122a4b5879ccc5c02e82.
