### ISSUE TITLE
Library not found for -lPods

### ISSUE THREAD

**Issue by cellularmitosis** [CocoaPods/CocoaPods#155]
Hey guys,

I'm getting the error "Library not found for -lPods".

This is after following the instructions in the README at https://github.com/CocoaPods/CocoaPods/blob/master/README.md

Additionally, I found https://github.com/CocoaPods/CocoaPods/wiki/Creating-a-project-that-uses-CocoaPods and followed step 4 in the FAQ (which specifically addresses this issue), but I still get the same error.

Versions:
Xcode: 4.2
OS X: 10.6.8

**Comment by denisysdata** [comment]
Same problem on cocoapods 0.35.0, in my case, after pod update the file project.pbxproj have lost all VALID_ARCHS and set ONLY_ACTIVE_ARCH to YES.

**Comment by Jeswang** [comment]
@PlayDevelop Thanks, delete the old libPods.a works for me.

**Comment by CrabDude** [comment]
@Jeswang @PlayDevelop YES! Remove `libPods.a` from "Link Binary With Libraries" in "Build Phases" fixed the issue for me which appeared to crop up almost inexplicably.

**Comment by russmatney** [comment]
Burned a few hours on this today, tried #allthethings that were listed here (lots of removing pods and `pod install`ing. even tried a fresh project from scratch but kept hitting the same missing libPods.a issue. The first symptom that led me to this was trying to `import Alamofire` in a swift file, but xcode could never find that module.

Solution that finally just worked for me was upgrading to the Beta: `gem install cocoapods --pre` and then `pod install`, which seems to move away completely from the libPods.a file to an actual Pods.framework. Restarted the workspace, and all is happy again.

For future ref: current Beta at the time of writing is: `0.36.0.beta.2`

**Comment by nightwolf-chen** [comment]
I had same problem. My problem was about "Build Active Architectrure Only" , I set that option to "NO" to solve the problem. Hope this could help anyone with the same problem.

**Comment by ruseel** [comment]
http://stackoverflow.com/a/23085107/262425

**Comment by cjayst** [comment]
@PlayDevelop fixed and worked for me, thanks.
