### ISSUE TITLE
Install error: "rake" from rake conflicts with /usr/bin/rake

### ISSUE THREAD

**Issue by zivelli** [CocoaPods/CocoaPods#1564]
Install Cocoapods on a fresh install of 10.9 & XCODE 5 produces the following error

```
rake's executable "rake" conflicts with /usr/bin/rake
Overwrite the executable? [yN]
```

I followed the direction here [set properly in the shell environment ](https://github.com/CocoaPods/CocoaPods/issues/639#issuecomment-11483748) but I still get the error.

**Comment by seansio1995** [comment]
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/rake
I still receive this error after simply typing "y"
