### ISSUE TITLE
CocoaPods should infer the SDK of the Pods project

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1576]

**Comment by Speakus** [comment]
is the any way to create "if" construction in the Podfile to divide logic for different SDKs ?

**Comment by segiddins** [comment]
Could someone (@kylef) jog my memory as to what this issue is about?

**Comment by kylef** [comment]
@segiddins I think it's regarding the `platform :ios, '10.8'` part of the Podfile is already define in the project. It would be possible to introspect this instead of having to define it in the Podfile perhaps?

**Comment by segiddins** [comment]
We already introspect the platform when integrating, I'm fairly certain.

**Comment by kylef** [comment]
@segiddins so why do we need to define it in our Podfiles?

**Comment by segiddins** [comment]
Pretty sure you only actually _need_ it when you sue `--no-integrate`

**Comment by segiddins** [comment]
Closing, since we can't seem to remember what the issue was even about.
