### ISSUE TITLE
Opt out of inhibit_all_warnings for specific pods

### ISSUE THREAD

**Issue by hfossli** [CocoaPods/CocoaPods#1587]
Hi

It would be great if the :inhibit_warnings => false was respected on specific pods when used. Then warnings for internal libraries could then still be visible in xcode.

Example:

    inhibit_all_warnings!

    pod 'ReactiveCocoa', '~> 1.9.6'
    pod 'CargoBay', :git => 'https://github.com/mattt/CargoBay.git'

    pod 'IVYViewTransitioner', :path => '../transitioner-ios', :inhibit_warnings => false

**Comment by segiddins** [comment]
I'm going to close this out, as it's been open for a year and a half without being addressed -- I'd welcome a PR implementing this, but I don't think it needs to remain opening any longer.

**Comment by hfossli** [comment]
> We're having the same issue at Yammer - local pods depend on pods with warnings (even AFN 1.x throws some), so we have this nasty post_install block.

@supermarin Can I see your nasty post_install? :)

I'm trying to solve this:
http://stackoverflow.com/questions/31644959/how-can-i-silence-warnings-from-all-pods-except-local-pods

**Comment by supermarin** [comment]
@hfossli unfortunately I don't work there anymore :)

**Comment by hfossli** [comment]
@supermarin can you @-mention someone who does? I really would like to know if it possible.. There's a bounty of 150 on the stackoverflow question, but no traction...

**Comment by xilin** [comment]
@hfossli Hi, after so many years, is there a new solution for your problem?

**Comment by xilin** [comment]
@guillaumealgis It seems that #6401 cannot help in this case, right?

**Comment by hfossli** [comment]
I'm not sure if there's an update to this issue.

**Comment by grigorye** [comment]
There's a cocoapods plugin, https://github.com/leavez/cocoapods-developing-folder that adds [`inhibit_warnings_with_condition`](https://github.com/leavez/cocoapods-developing-folder#-inhibit-warnings-for-specific-pods) for this.

Beware that when `inhibit_warnings_with_condition` is used, it makes `inhibit_all_warnings!` and `:inhibit_warnings` ineffective.

**Comment by xilin** [comment]
@grigorye I've tried this plugin, but it didn't help. If we are developing pod A, and it depends on pod B, Xcode will still complain about warnings generated in pod B if we use them in pod A.
