### ISSUE TITLE
Add headers quirk mode option

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1626]
Source files should always import headers from other Pods properly name-spacing them:

```
#import <ObjectiveSugar/ObjectiveSugar.h>
```

This is important for avoiding collisions and to clarify what library is providing the header and for other reasons.

If we can rely on this assumption we can just include the root of the headers search paths in the xcconfigs.

**Comment by segiddins** [comment]
Think it's time to do this, so things are consistent between static libs and frameworks, @mrackwitz ?

**Comment by mrackwitz** [comment]
Yes, let's begin to phase '-iquote' headers out, including integrated user projects. :+1:

**Comment by segiddins** [comment]
:fireworks:
