### ISSUE TITLE
Aggressive Pod project warning settings break pods

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaPods/CocoaPods#1629]
On top of modules being on by default breaking some builds (#1575), now also some warnings are set to "treat as error" breaking some extra ones.

Namely:
- `CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR` (Xcode default `YES`)
- `GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR` (Xcode default `NO`)
- `CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR` (Xcode default `YES`)

As I said before, I'm all in for extra warnings and enforcing better usage but breaking Pods can be frustrating for App developers that are not involved in the development of the libraries they use and that just stopped working once updating CocoaPods.

**Comment by RishabhTayal** [comment]
Is there a solution for this issue. Can we re-open it? I am still facing the same issue.
