### ISSUE TITLE
User options of overriding pod spec?

### ISSUE THREAD

**Issue by zorn** [CocoaPods/CocoaPods#165]
So my project is now using the JSONKit pod via the RestKit pod. The [spec for this JSONKit pod](https://github.com/CocoaPods/Specs/blob/master/JSONKit/1.4/JSONKit.podspec) links against the tagged 1.4 version which is a year old and sadly generates warnings about some extra parentheses. This errors have been fixed in master and it builds clean.

As a CocoaPods user what are my options at this point? Is there anyway to override the spec to use the master branch instead of the tag? Is there anyway I could fork JSONKit on GitHub point CocoaPods to my own copy of the JSONKit pod spec?

**Comment by revolter** [comment]
That's why you don't post links only answers :(

@fatuhoku, [This][1] is the correct link, if it is of any help after 2 years 😆 

  [1]: https://github.com/CocoaPods/CocoaPods/blob/ece1c9fdf6958fc93f9ea9c9fa7221e4b5dfef45/examples/SSCatalog/Podfile#L8-L13
