### ISSUE TITLE
vendored_library not working - library not starting with "lib"

### ISSUE THREAD

**Issue by 20minutos** [CocoaPods/CocoaPods#1656]
I'm trying to create a private pod with external code, this include a library that not starting with "lib"

I've seen https://github.com/CocoaPods/CocoaPods/issues/1398 but if i add xcconfig with LIBRARY_SEARCH_PATHS to the podspec, i get a "Undefined symbols for architecture i386" error

```
s.source_files = 'xiti/*.h'
s.preserve_paths = 'xiti/ATLibiOS.a','xiti/ATInternet.sqlite'

s.resources = 'xiti/ATInternet.sqlite'

s.xcconfig = { 'LIBRARY_SEARCH_PATHS' => '"$(PODS_ROOT)/xiti"' }

s.frameworks = 'SystemConfiguration', 'CoreLocation'
s.libraries = 'sqlite3', 'ATLibiOS'
```

**Comment by noark9** [comment]
Still not work on cocoapods 1.6.1, linker cannot find static libraries with out lib prefixed.
