### ISSUE TITLE
Copy resources v3

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaPods/CocoaPods#1690]
There were lots of improvements thanks to v2 discussion (#743) and `resource_bundle` solves most scenarios but I feel that it could be even better.

Specifically:

1. Process files in subdirectories.  
Most of the time localization `*.lproj` (#846) directories are needed and Nibs (#14), or more commonly String files (#1653) don't get processed.  
As I think 99% percent of the cases the directory will be a `*.lproj` one, it would be easy to add an extra case to the resources algorithm to analyze the folder's contents.  
Other folders could just be copied as of now to preserve the structure (#807), or even a podspec flag could be used if needed.

2. Combines `resource_bundle` contents among subspecs.  
For instance right now:
```ruby
    #...
    s.resource_bundle = { 'MyLibBundle' => ['Resources/Common.strings}'] }
    
    s.subspec 'Nibs' do |sub|
        #...
        sub.resource_bundle = { 'MyLibBundle' => 'Resources/Nibs/*.{xib}' }
    end
    
    s.subspec 'OptionalBigFilesMostProjectsWontNeed' do |sub|
       #...
        sub.resource_bundle = { 'MyLibBundle' => 'Resources/SomeBigFiles/*' }
    end
```
Will create the bundle with only `Common.strings` on it while it should create the bundle with the contents of all the active subspecs as well to give the same flexibility subspecs have with source files.  
Off course multiple bundles could be created, but that would be plain ugly.

3. Generate a bundle Info.plist  
Retrieve bundles with `+[NSBundle bundleWithIdentifier:]`?
Store bundle version.

Other usages you wish that the current implementation lacks?

**Comment by segiddins** [comment]
Pretty sure this is no longer necessary with Frameworks?

**Comment by timbodeit** [comment]
@segiddins Frameworks currently pose very similar (though not necessarily the same) issues. For instance a storyboard in a .lproj folder will not be compiled. See #2597

**Comment by efirestone** [comment]
I believe this is resolved with https://github.com/CocoaPods/CocoaPods/pull/4635 and https://github.com/CocoaPods/Xcodeproj/issues/259. You can test it in 1.0.0.beta.1

**Comment by a2** [comment]
I'm having trouble with this as well when my `.lproj` directories contain `.stringsdict` files.

**Comment by segiddins** [comment]
@a2 are you running the CocoaPods beta?

**Comment by a2** [comment]
@segiddins Yeah I was. I had to revert to 0.39 for it to work.

The duplicated UUIDs is a problem is 0.39 too, but just thought I'd point it out here.
![messages image 3708387216](https://cloud.githubusercontent.com/assets/241156/12530383/3e2242d0-c1de-11e5-8372-4f537c37c9eb.png)

Weird directory structure. Doesn't copy the `.stringsdict` into the `.bundle`. Only the generated `Info.plist` is there.
<img width="335" alt="screen shot 2016-01-22 at 8 34 23 pm" src="https://cloud.githubusercontent.com/assets/241156/12530384/3e788d66-c1de-11e5-982b-a24b978a866e.png">

**Comment by efirestone** [comment]
The weird directory structure was a result of https://github.com/CocoaPods/CocoaPods/issues/4762 (really sorry), but should be fixed in 1.0.0.beta.3.

Using beta 3, if you now declare your resources glob as `Resources/**/*` rather than `Resources/*` it should properly handle localized strings files and other bundles by merging them in the Xcode navigator.

**Comment by neonichu** [comment]
I think we can close it, since 1.0 changes the resource handling significantly and we should start with fresh tickets if there are issues with that.

**Comment by Blahartinger** [comment]
I have a need to specify additional assets as a subspec...has a new ticket been created? feature implemented? I think the answer is no...but...was there any resolution to being able to do something like rivera-ernesto mentions in the first post:

2. Combines resource_bundle contents among subspecs.
