### ISSUE TITLE
Error: "You have to install development tools first."

### ISSUE THREAD

**Issue by jamonholmgren** [CocoaPods/CocoaPods#1727]
I know this is a common problem, so I've searched all the issues but haven't found a solution to it. Hoping someone can point me in the right direction.

When I run `gem install cocoapods`, I get this:

```
 ~/ gem install cocoapods
Building native extensions.  This could take a while...
ERROR:  Error installing cocoapods:
    ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby -rubygems /usr/local/lib/ruby/gems/2.1.0/gems/rake-10.1.1/bin/rake RUBYARCHDIR=/Users/jh/.gem/ruby/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/xcodeproj-0.14.1 RUBYLIBDIR=/Users/jh/.gem/ruby/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/xcodeproj-0.14.1
/usr/local/bin/ruby extconf.rb
checking for -std=c99 option to compiler... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/usr/local/bin/ruby
/usr/local/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:571:in `block in try_compile'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:524:in `with_werror'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:571:in `try_compile'
    from extconf.rb:24:in `block in <main>'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:321:in `open'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
    from /usr/local/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
    from extconf.rb:23:in `<main>'
rake aborted!
Command failed with status (1): [/usr/local/bin/ruby extconf.rb...]
/Users/jh/.gem/ruby/2.1.0/gems/xcodeproj-0.14.1/ext/xcodeproj/Rakefile:37:in `block in <top (required)>'
Tasks: TOP => default => ext
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/jh/.gem/ruby/2.1.0/gems/xcodeproj-0.14.1 for inspection.
Results logged to /Users/jh/.gem/ruby/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/xcodeproj-0.14.1/gem_make.out
 ~/
```

I've already run `xcode-select --install`. Any ideas?

**Comment by qileilove** [comment]
yeah! the same error!   with @vixentael help， I fix errors.

**Comment by gMarx** [comment]
I just had this same issue, and it seems Xcode had updated in the background and I haven't opened it to accept the new terms. Once I opened it & accepted the terms, I could successfully run `gem install [gem_name]`

**Comment by josescasanova** [comment]
I had the same issue earlier today. I had updated my xcode and had not agreed to the terms yet. Running `sudo xcodebuild -license` and agreeing got my bundle working again.

**Comment by masak2009** [comment]
Who is looking directly for "You have to install development tools first" and you did all steps (command line tools, xcode licence accept etc.). Try this:

I have to update rvm itself and force reinstall ruby:

[http://www.fakingfantastic.com/2010/11/26/fixing-the-you-have-to-install-development-tools-first-error-with-nokogiri/](url)
For example:

```
rvm update head
rvm --force install 1.9.3
```

**Comment by zakahmad** [comment]
@josescasanova this worked for me

**Comment by preetb123** [comment]
thanks @masak2009 it worked with minor change:
```
rvm update head
rvm --force install 2.3.3

```

**Comment by Antoinebr** [comment]
Thanks @gmale it worked for me :)

**Comment by haseeb-ahmad** [comment]
> For future googlers, rehashing rbenv solved this issue for me.
> `rbenv rehash`

Thanks! It works for me.

**Comment by vinaymavi-tftus** [comment]
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` 

for more details check this link - https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error

**Comment by lhamadopagode** [comment]
> `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
> 
> for more details check this link - https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error

Thanks! It solved for me

**Comment by calliday** [comment]
I updated ruby and reinstalled cocoapods, solved my issue

**Comment by oldo** [comment]
I was getting this error as well and resolved by installing with [homebrew](https://formulae.brew.sh/formula/cocoapods) instead.

**Comment by technohowl** [comment]
> `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
> 
> for more details check this link - https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error

This fixed my issue.

**Comment by cdbrouk** [comment]
> `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
> 
> for more details check this link - https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error

I solve my issue. Thanks!! 👍

**Comment by valn1** [comment]
i spent almost 3 days of work trying to fix this, but finally got it to work, here is all that you need to do

install brew -

     ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 

when brew is installed, its git repository comes outdated, so you have to update it so you can install the latest version of the softwares you`ll need-

     git -C $(brew --repo homebrew/core) checkout master

overwrite the old brew link and, instead of installing by gem, use brew to install cocoapods-

    brew link --overwrite cocoapods 
    brew install cocoapods

this way you`ll have installed the latest version of cocoapods and you can verify it by using pod -v 


i guess there is a way of doing this by using gem, but you'd need to fix Apple's broken by default products, and that's a lot of work
hope i helped

**Comment by personalnadir** [comment]
I had this issue. Installing ruby through RVM fixed it for me (this upgraded me from 2.6 to 3.0). Instructions [here](https://rvm.io/rvm/install).

Note: the ruby alias does not update until you reload the environment.

**Comment by satvikpendem** [comment]
For those on M1 / Apple Silicon machines, I think the development tools don't work yet or aren't native, so installing via homebrew worked for me.

```
brew install cocoapods
```

**Comment by mattias0h** [comment]
I had a similar problem when running bundle install and I finally managed to solve the problem with `xcodebuild -runFirstLaunch`.

**Comment by HamGuy** [comment]
> For those on M1 / Apple Silicon machines, I think the development tools don't work yet or aren't native, so installing via homebrew worked for me.
> 
> ```
> brew install cocoapods
> ```

It works for me, many thanks!

**Comment by JohnKe0719** [comment]
> i spent almost 3 days of work trying to fix this, but finally got it to work, here is all that you need to do
> 
> install brew -
> 
> ```
>  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
> ```
> 
> when brew is installed, its git repository comes outdated, so you have to update it so you can install the latest version of the softwares you`ll need-
> 
> ```
>  git -C $(brew --repo homebrew/core) checkout master
> ```
> 
> instead of installing by gem, use brew to install cocoapods, then overwrite the link in case it shows the error (Error: The `brew link` step did not complete successfully)
> 
> ```
> brew install cocoapods
> brew link --overwrite cocoapods        (just in case the brew link doesnt work at first)
> ```
> 
> this way you`ll have installed the latest version of cocoapods and you can verify it by using pod -v
> 
> i guess there is a way of doing this by using gem, but you'd need to fix Apple's broken by default products, and that's a lot of work hope i helped

It works for me, many thanks!
