### ISSUE TITLE
PODS_ROOT not getting set

### ISSUE THREAD

**Issue by pswenson** [CocoaPods/CocoaPods#1730]
When I build my app for development, I have no troubles.  However when I try to build an archive/ipa from Xcode or using the schenzen gem I get this error:

`diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

Looking at the generated script I can see that the problem is ${PODS_ROOT} is not set to anything...

Any idea why this would happen and how to correct it?

BTW, I'm on cocoapods 0.29.0, iOS7

**Comment by bharveyimmediate** [comment]
I had this problem too, it turns out I was using an older version of the cocoapods ruby gem, which I presumed would have been updated automatically when I upgraded to the latest copy of xcode.

Upgrading the cocoapods ruby gem to version 1.7.5 resolved the problem for me.

**Comment by silverhammermba** [comment]
I also had this problem, in my case it was when building a target that did not use any pods, but which linked with frameworks that _did_ use pods. I just had to create an empty target block for it in my Podfile, which adds the missing configurations under the project.

**Comment by WNemencha** [comment]
@mattconnolly Thanks, you saved one developer's day :)

**Comment by gowda57** [comment]
Go to build settings
Click on plus icon at the top to add a user defined setting for missing variables
<img width="1109" alt="Screenshot 2022-01-19 at 12 49 56 PM" src="https://user-images.githubusercontent.com/29328230/150082897-442a5874-87a8-4c19-9cb7-81931b616e0b.png">
.
