### ISSUE TITLE
 While executing gem ... (TypeError)

### ISSUE THREAD

**Issue by fuxiaohui** [CocoaPods/CocoaPods#1742]
use:$ sudo gem install cocoa pods

see:
ERROR:  While executing gem ... (TypeError)
    instance of Date needs to have method `marshal_load'

**Comment by cloay** [comment]
I have this issue too
sudo gem install -n /usr/local/bin cocoapods  on osx 10.11.4 
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String

Somebody help, thanks!

**Comment by segiddins** [comment]
@cloay that was a bug in RubyGems 2.6.2 that just got fixed

**Comment by cloay** [comment]
@segiddins Tks!
