### ISSUE TITLE
Unnecessary import of <Cocoa/Cocoa.h>

### ISSUE THREAD

**Issue by ryanwmarsh** [CocoaPods/CocoaPods#1746]
The default `#import <Cocoa/Cocoa.h>` in `...-prefix.pch` is unnecessary for projects that are OSX command line apps. I recommend removing this and possibly the explicit `#import <UIKit/UIKit.h>` for iOS projects as pod authors likely import the headers they need without this. 

I explicitly should not import Cocoa.h in my app because of some very specific things I'm doing to the library path before linking.  While you might say, "Just remove the import," to that I reply "every time I run `pod install` the `...-prefix.pch` is overwritten by CocoaPods and that's just not very nice". 

See: https://github.com/CocoaPods/CocoaPods/blob/a497bb16d2363679fbe8530268098b62c6dcd02d/lib/cocoapods/generator/prefix_header.rb#L49

**Comment by segiddins** [comment]
Thoughts on this, team?

**Comment by neonichu** [comment]
IIRC, this import is actually replaced by Foundation in my watchOS PR - however I already saw breakage because of it. Better break now than post 1.0?

**Comment by segiddins** [comment]
:+1:. Tbh, I'd like to get rid of the implicit Foundation import as well...

**Comment by neonichu** [comment]
Then let's just :fire: the PCH entirely?

**Comment by segiddins** [comment]
Can't entirely, since podspecs can specify custom PCH contents

**Comment by neonichu** [comment]
At least limit its creation to those cases?

**Comment by orta** [comment]
less is more :+1:

**Comment by kylef** [comment]
Removing this import from created pch files could result in a breaking change for pods that didn't import these headers and depend on them.

I'd suggest we first remove this generated PCH file from linting a pod to prevent people submitting pods that will break when this change happens. Then later remove it from the generated project when a user integrates with Xcode.

**Comment by neonichu** [comment]
@kylef sounds like a good course of action - IMO, we should also think about deprecating `prefix_header_contents` before 1.0, since we already state that its use is not recommended.

**Comment by segiddins** [comment]
Pretty sure we've agreed this is impossible to do?

**Comment by neonichu** [comment]
As much as I wish we could get rid of it, it's probably a lost cause at this point.
