### ISSUE TITLE
better error message for 'platform of the target is not compatible...

### ISSUE THREAD

**Issue by ConfusedVorlon** [CocoaPods/CocoaPods#1763]
this is the error message I got on pod install.

[!] The platform of the target `Pods` (OS X 10.6) is not compatible with `CocoaHTTPServer (2.3)` which has a minimum requirement of iOS 5.0 - OS X 10.7.

this was confusing for me as my main project was set to 10.7

it turns out, I needed to specify the target in my podfile like this:
platform :osx, '10.7'

the error message could have helped me with something like - 

'the default target for OSX is 10.6, you can change this by using the following line in your podfile
platform :osx, '10.7'

**Comment by segiddins** [comment]
We've since improved this.
