### ISSUE TITLE
Allow :local in podfile

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#178]
Currently it is possible to specify a local dependency in a `podspec` file. It would be nice to support this feature in the `podfile` as well.

Example:

``` ruby
dependency 'MyAwesomeLib', :local, '~/path/to/MyAwesomeLib'
```

**Comment by orkenstein** [comment]
Sorry, can not understand, how to use custom `:podspec`! I need custom spec for `ReactiveCocoa` from this repo https://github.com/mhuusko5/Podspecs. How should I set up my `podfile`?

**Comment by orta** [comment]
![screen shot 2015-10-26 at 08 39 17](https://cloud.githubusercontent.com/assets/49038/10724506/0ff00ce2-7bbd-11e5-913e-5ca56c2d4a34.png)

These are all in CocoaPods/Specs - you don't need to do anything special to access them.

**Comment by orkenstein** [comment]
Thanks @orta!
But in case I need it in distant future, how to use custom `:podspec` stored at GitHub?

**Comment by orta** [comment]
You consult the guide on it: https://guides.cocoapods.org/syntax/podfile.html#pod :+1:

**Comment by orkenstein** [comment]
@orte, mkay, good 'ole rtfm.
Thanks!

**Comment by lemonkey** [comment]
@pjenkins-cc :+1: thanks for taking the time to outline the issues that you ran into and how you solved them.

**Comment by lemonkey** [comment]
@pjenkins-cc Looks like after following in your footsteps, I'm unable to setup something like the following:

    MainApp
    ----Pod1
    --------Pod2

Pod2 is a local dev pod for Pod1, and Pod1 is a local dev pod for MainApp.

MainApp's Podfile has an entry like this assigned to its main target:

`pod 'Pod1', :path => './pod1_framework'`

Pod1's .podspec has a dependency on Pod2 like this:

`s.dependency 'Pod2'`

while Pod1's Podfile has the following as the first line:

`pod "Pod2", :path => "./pod2_framework"`

Pod2's Pod2.podspec is in a folder "pod2_framework" in the Pod1 subfolder, which is itself a subfolder under MainApp.

When I try to do a `pod install` within the MainApp folder, the error I get is:

    Fetching external sources
    -> Fetching podspec for `Pod1` from `./pod1_framework`
    
    Resolving dependencies of `Podfile`
    [!] Unable to find a specification for `Pod2` depended upon by `Pod1`

**Comment by lemonkey** [comment]
When I modify the Main Podfile to have the path to the Pod2 Podfile:

`pod 'Pod2', :path => './pod1_framework/pod2_framework'`

`pod install` is successful (but with warnings -- see below) and the workspace appears to be correct. However, what ends up happening is that there is an additional Pods target in the Pods project, along side the Pods-Main and Pods-MainTests targets that you would expect. There are also Pod1 and Pod2 framework targets, as expected.

This extra Pods target causes the `pod install` to generate a warning:

    [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Main` to `Pods/Target Support Files/Pods-Main/Pods-Main.debug.xcconfig` or include the `Pods/Target Support Files/Pods-Main/Pods-Main.debug.xcconfig` in your build configuration.

**Comment by lemonkey** [comment]
I created a separate issue for my problem: https://github.com/CocoaPods/CocoaPods/issues/4570
