### ISSUE TITLE
Header files are not being found by the xcode

### ISSUE THREAD

**Issue by aparray** [CocoaPods/CocoaPods#1805]
I get the following warnings when i do pod install:

[!] [CorePlot (1.4.0)] The pre install hook of the specification DSL has been deprecated, use the `resource_bundles` or the `prepare_command` attributes.

[!] The target `PCTNursing [Debug]` overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Pods.xcconfig'.
    - Use the`$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The target `PCTNursing [Debug - Release]` overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Pods.xcconfig'.
    - Use the`$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The target `PCTNursing [Debug - Release - Release-Production]` overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Pods.xcconfig'.
    - Use the`$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The target `PCTNursing [Debug - Release - Release-Production - Release-Sandbox]` overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Pods.xcconfig'.
    - Use the`$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The target `PCTNursing [Debug - Release - Release-Production - Release-Sandbox - Release-Staging]` overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Pods.xcconfig'.
    - Use the`$(inherited)` flag, or
    - Remove the build settings from the target.

I tried using the inherited flag in header search paths but nothing happened?

**Comment by confile** [comment]
@aparray Where do you put the ``$(inherited)``in your podspec. Could you please post an example?
