### ISSUE TITLE
The prepare_command executed although :file reference is used.

### ISSUE THREAD

**Issue by besi** [CocoaPods/CocoaPods#1820]
I have a Podfile with the following contents:

````ruby
   pod 'myspecialpod', :path => '/Users/me/myspecialpod/'
````

Now in the guides for [prepare_command](http://guides.cocoapods.org/syntax/podspec.html#prepare_command) it says:

> If the pod is installed with the :path option this command will not be executed.

Now although i am using the `:path` option for my Pod the prepare_command script is executed. I create a file two folders up, which should end up in the Project directory of the given project using the Pod:

From my Podspec:

````ruby
  s.prepare_command = <<-CMD
  echo " 
  Some Stuff
  In a file
  " > ../../FileThatINeed.txt
  CMD
````

Now either the docs or the behaviour seems to be wrong. I am using cocoapods 0.29.0

**Comment by kylef** [comment]
Since no one has confirmed it still exists, I'm going to close. If someone later finds this issue please open a new issue.
