### ISSUE TITLE
Pod install result in initialize an object with an unknown UUID

### ISSUE THREAD

**Issue by wilferrel** [CocoaPods/CocoaPods#1822]
after cleaning out with : 
$ sudo rm -fr ~/.cocoapods/repos/master
$ pod setup

I performed a pod install but received: 
<PBXGroup path=`AppName` UUID=`B46F89A9180AFAA500654ABA`>`attempted to initialize an object with an unknown UUID.`B43B984D18119835003B101E`for attribute:`children`. This can be the result of a merge and the unknown UUID is being discarded.

**Comment by andreyslyusar** [comment]
I give a try to v0.36-beta2:
1. install sudo gem install cocoapods --pre
```bash
Fetching: cocoapods-core-0.36.0.beta.2.gem (100%)
Successfully installed cocoapods-core-0.36.0.beta.2
Fetching: claide-0.8.0.gem (100%)
Successfully installed claide-0.8.0
Fetching: xcodeproj-0.21.2.gem (100%)
Successfully installed xcodeproj-0.21.2
Fetching: cocoapods-plugins-0.4.0.gem (100%)
Successfully installed cocoapods-plugins-0.4.0
Fetching: cocoapods-trunk-0.5.0.gem (100%)
Successfully installed cocoapods-trunk-0.5.0
Fetching: molinillo-0.2.0.gem (100%)
Successfully installed molinillo-0.2.0
Fetching: cocoapods-0.36.0.beta.2.gem (100%)
Successfully installed cocoapods-0.36.0.beta.2
Parsing documentation for cocoapods-core-0.36.0.beta.2
Installing ri documentation for cocoapods-core-0.36.0.beta.2
Parsing documentation for claide-0.8.0
Installing ri documentation for claide-0.8.0
Parsing documentation for xcodeproj-0.21.2
Installing ri documentation for xcodeproj-0.21.2
Parsing documentation for cocoapods-plugins-0.4.0
Installing ri documentation for cocoapods-plugins-0.4.0
Parsing documentation for cocoapods-trunk-0.5.0
Installing ri documentation for cocoapods-trunk-0.5.0
Parsing documentation for molinillo-0.2.0
Installing ri documentation for molinillo-0.2.0
Parsing documentation for cocoapods-0.36.0.beta.2
Installing ri documentation for cocoapods-0.36.0.beta.2
7 gems installed
```

2. pod setup
```bash
Setting up CocoaPods master repo
Already up-to-date.
Setup completed
```
3. pod install 
```bash
[!] `<PBXBuildFile UUID=`18A958F56A8D643BCCF77FF9`>` attempted to initialize an object with an unknown UUID. `7BC88909A3F34A6B992B28CA` for attribute: `file_ref`. This can be the result of a merge and  the unknown UUID is being discarded.
```
There is no conflict or changes in master of cocoaPods in .cocoapods/repos/

4. Now every time "pod install". 
```bash
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Analyzing dependencies
Downloading dependencies
Using LoremIpsum (1.0.0)
Generating Pods project
Integrating client project
```
But pods seems to work correctly

**Comment by tolentinokas** [comment]
This fixed the issue for me: http://stackoverflow.com/a/22878202/1635363

**Comment by andreyslyusar** [comment]
In my case I clean cocoaPods Git master repo, refetch all from scratch. This solve terminal error.

**Comment by rvi** [comment]
I just deleted `Pods.framework`, and perform a `pod install` and the warnings disappear.

**Comment by litt1e-p** [comment]
@tolentinokas works for me,thx

**Comment by timbroder** [comment]
@rvi thanks much, that fixed it for me

**Comment by UncleEle** [comment]
@rvi works  for me,thx

**Comment by voidstarfire** [comment]
Where is Pods.framework ?

**Comment by shannoga** [comment]
@rvi , thanks

**Comment by 948080952** [comment]
@rvi Where is Pods.framework ?

**Comment by timbroder** [comment]
@voidstarfire @948080952 

In project navigator:
Pods > Products > Pods_[AppName].framework

**Comment by manishios** [comment]
I was facing the same issue. http://stackoverflow.com/a/31025426/4082792 fixed it.

**Comment by grifas** [comment]
Just do:
- pod deintegrate PROJECT.XCODEPROJ
- pod install

**Comment by ooopscc** [comment]
In some cases, this means you add some file (create the proj referene), then manually remove some file not within Xcode, but not remove the xcode proj reference.
Just use @rvi 's solution, you may just need to delete that reference.

**Comment by rob-keepsafe** [comment]
Another helpful trick without removing / re-adding folders (because sometimes they are virtual folders):

1. Select the folder that's giving you issues
2. Show the utilities pane on the right
3. Change the `Location` dropdown from its current value to some new value and then back to its original value
4. Clean your project
5. Run `pod install` again and the errors should be gone

Utilities pane:

<img width="371" alt="screen shot 2018-08-01 at 11 12 56 am" src="https://user-images.githubusercontent.com/30269720/43530661-1f209db8-957c-11e8-8ea6-338cdb6a57e1.png">

**Comment by tbanj** [comment]
> * pod deintegrate PROJECT.XCODEPROJ
> * pod install

This works for me thanks so much

**Comment by tobitech** [comment]
Can anyone help? I'm getting this error only on Bitrise but works fine on my local machine

**Comment by minhnguyen0712** [comment]
> Can anyone help? I'm getting this error only on Bitrise but works fine on my local machine

Maybe it was some misconflict and configuration, running @grifas's solution helps. With Bitrise, I think you need to re-configure the step to install.

> Just do:
> 
> * pod deintegrate PROJECT.XCODEPROJ
> * pod install
