### ISSUE TITLE
Remove a pod causes Linker Error

### ISSUE THREAD

**Issue by wolffan** [CocoaPods/CocoaPods#1823]
Removing Lookback pod caused this:

ld: framework not found LookBack
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Not sure if I'm doing something wrong or there is something wrong with the pod.

**Comment by jlubeck** [comment]
This just happened to me as well with cocoapods 1.1.1.
I had to manually remove the linker flags from my target.
I just removed the line from the Pod file and did pod install. Nothing more, nothing less.

**Comment by Rnorback** [comment]
This is happening to me wiht cocoapods 1.2.0 and I'm not finding any way out.

ld: framework not found LookBack
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ElyDantas** [comment]
To make sure what pod is giving you trouble you need to: 

1. Right click the message` "Linker command failed with exit code 1"` 
2. Choose the option `"Reveal in Log"` ,
3. A mensage in the right window will appear showing the framework causing you trouble
4. Delete `-framework` and `FrameworkName` in `"Other Linker Flags"` from your project target's `"Build Settings"`

<img width="1272" alt="copia de captura de tela 2017-07-27 as 23 37 22" src="https://user-images.githubusercontent.com/12100371/28700657-847dcc76-7327-11e7-95d0-7fb6f659bbe5.png">

<img width="1280" alt="copia de captura de tela 2017-07-27 as 23 39 29" src="https://user-images.githubusercontent.com/12100371/28700852-a66dba7a-7328-11e7-8d86-f996ae0fceba.png">

<img width="1280" alt="build success" src="https://user-images.githubusercontent.com/12100371/28700961-447377d2-7329-11e7-9146-bc8cf7385fa1.png">

**Comment by alper** [comment]
Just got bit by this after removing PaymillSDK. Cocoapods does not seem to update the "Other Linker Flags" setting?

**Comment by amberkatyal** [comment]
> @newmanw you have to remove the linkers.
> This means that in "Other Linker Flags" in you target "Build Settings", will have a list of linkers related to your pods.
> 
> Search for the pods that you want to delete and for each one you have to delete 2 things. First the linker with the pod name, and after, the "-framework" linker just below it.
> So 2 linkers for each pod.
> 
> That fixed things for me

i would consider not doing this operation by cocoapods is there fault only.  I tried all the answers everywhere on stackoverflow. This only solved my case.. :)
Thanks!!
