### ISSUE TITLE
Supspec with vendored_frameworks does not work as expected

### ISSUE THREAD

**Issue by angerman** [CocoaPods/CocoaPods#1824]
I think cocoapods with subspecs that reference pods with `vendored_frameworks` do not work, or better: work incorrectly.  Basically the subspec won't benefit from the `vendored_frameworks` of the spec it depends on, while the target using the pod with the subspec get the benefit.  To simplify: Project A, Target T has a dependency on Pod P with Supspec S. While P/S depends on Pod P2, which has a vendored_frameworks setting.

Now: P/S's xcconfig won't get `FRAMEWORK_SEARCH_PATHS` and `OTHER_LDFLAGS`, `-framework` setting, while T's `.xcconfig` will.

But: As P/S depends on P2, and likely has `#include <F/F.h>`, it will fail to lint (and compile). And T could have `#include <F/F.h>`, even though it's not directly dependent on the `vendored_framework` F.

Sample code: https://github.com/angerman/BrokenCocoaPods and here's the pods repo https://github.com/angerman/pods

**Comment by evanattwitter** [comment]
0.37 and this is still a problem. I managed to work around it by manually adding ss.xcconfig to the subspec

**Comment by segiddins** [comment]
Can anyone check if this is resolved by https://github.com/CocoaPods/CocoaPods/pull/3832?

**Comment by segiddins** [comment]
Closing due to lack of response, and the fact that the example project originally shared is no longer accessible.

**Comment by mhuusko5** [comment]
A little late, sorry.
Anyway, for your piece of mind, can confirm this is fixed for me.

**Comment by bakemecookies** [comment]
Possibly seeing some lingering things w/ this in 0.39 and hoping this is the right place for this discussion.

`FRAMEWORK_SEARCH_PATHS` gets propagated all the way up to application level and also for the application's primary Pods target, but not for any of the intermediate dependency targets (i.e., it's filled for the `Pods` target, but not for the generated `Pods-Dependency` target).

`HEADER_SEARCH_PATHS` seems to be properly filled all the way, so if `Dependency` includes something like `#import <F/F.h>` it's all fine, but `@import F;` isn't.

**Comment by steve6** [comment]
Hi guys,
Any update on this problem? I have the same problem with Google IMA framework inside a podspec.

Thanks
Steve

**Comment by mbalex99** [comment]
@steve did you figure out a solution?

**Comment by mamnun** [comment]
Same here with Google IMA
