### ISSUE TITLE
CocoaPods 0.29.0 does not inherit/know 'source_files' from parent spec.

### ISSUE THREAD

**Issue by dsuppiger** [CocoaPods/CocoaPods#1835]
Importing a header file pertaining to the parent spec within the source file of a child spec  results in a 'file not found' error when I push/lint the .podspec.

Adding the 'missing' file to the parent as well as to the child spec's source_files results in a successful push/lint but duplicate entries in the pod's build phases.

The same .podspec works flawlessly in CocoaPods 0.28.0.

**Comment by Ashton-W** [comment]
The documentation on **guides.cocoapods.org** is still wrong or just confusing on this matter.

**Comment by segiddins** [comment]
@Ashton-W A PR improving the docs would be very welcome!

**Comment by Ashton-W** [comment]
I'm not even sure I know how subspecs work to write that PR myself :(
