### ISSUE TITLE
Failing to run pod install: "mapping values are not allowed in this context"

### ISSUE THREAD

**Issue by codinglabs** [CocoaPods/CocoaPods#1853]
I just updated cocoapods to 0.29 (also tested with 0.28) from a super old version (can't remember which one) and now I run into the following error message when I execute 'pod install'.
### Stack

```
   CocoaPods : 0.28.0
        Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
    RubyGems : 2.0.3
        Host : Mac OS X 10.9.2 (13C64)
       Xcode : 5.0.2 (5A3005)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9a61a13fc6b5d3b9ecde5ea5b6c1da3a63d1c1d2
```
### Podfile

``` ruby
platform :ios, '7.0'
pod 'MarqueeLabel', '~> 1.2'
pod 'AFNetworking', '~> 2.0'
pod 'FormatterKit', '~> 1.4'
```
### Error

```
Psych::SyntaxError - (/Users/psteinacher/.cocoapods/repos/master/CocoaPods-version.yml): mapping values are not allowed in this context at line 3 column 4
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:299:in `block in load_file'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:299:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:299:in `load_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/lib/cocoapods/sources_manager.rb:248:in `version_information'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/lib/cocoapods/sources_manager.rb:209:in `repo_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/lib/cocoapods/sources_manager.rb:268:in `master_repo_functional?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/lib/cocoapods/command.rb:40:in `parse'
/Library/Ruby/Gems/2.0.0/gems/claide-0.4.0/lib/claide/command.rb:179:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/lib/cocoapods/command.rb:39:in `parse'
/Library/Ruby/Gems/2.0.0/gems/claide-0.4.0/lib/claide/command.rb:211:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.28.0/bin/pod:24:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by zlc000190** [comment]
i   run    
pod  install
then error comes

 CocoaPods : 0.34.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 ()
       Xcode : 6.1 (6A1052d)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 78dec2644e47aa272fb8c5ddf27a2e23e99c0a50

### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.1
```

### Podfile

```ruby
platform:ios,
pod 'MJRefresh',
pod 'MBProgressHUD',
pod 'FPPopover',
pod 'BWStatusBarOverlay',
pod 'Zbar',
pod 'ASIHTTPRequest',
pod 'SDWebImage',

## Error

```
SyntaxError - /Users/soufunlc/Desktop/newzxb/homezxb/Podfile:2: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
pod 'MJRefresh',
     ^
/Users/soufunlc/Desktop/newzxb/homezxb/Podfile:2: syntax error, unexpected ',', expecting end-of-input
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:247:in `eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:247:in `block in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:244:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:244:in `from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:220:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/config.rb:176:in `podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command.rb:101:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

i try linglong's method ,but doesn't work.

**Comment by developeryh** [comment]
@zlc000190 the same question with you,do you solve it ? if you did,i demand you emil me developer_yh@163,
