### ISSUE TITLE
pod install does not pull down latest commit from master

### ISSUE THREAD

**Issue by rex-remind101** [CocoaPods/CocoaPods#1866]
I'm pointed at `master` for a repo's podspec `:branch => 'master'`, this repo is used by a project of mine. I made some changes to `master` and pushed them upstream, but when I did a `pod install` the changes were not reflected in the project that's using the repo. I had to manually delete the cocoapods cache and then `pod install` for the changes to show.

**Comment by hemangshah** [comment]
Why don't I have the latest code which is in my release?

Github: https://github.com/hemangshah/printer
CocoaPods: https://cocoapods.org/pods/printer-logger

**Comment by reitzig** [comment]
@kylef `pod update` won't pull the new commit either.

**Comment by albertbori** [comment]
You can force it to update by changing the target `:commit:` value in your Podfile.lock:

![screen shot 2018-03-23 at 10 25 29 am](https://user-images.githubusercontent.com/1742709/37841165-9f48ae36-2e84-11e8-8587-66ead2209352.png)

**Comment by reitzig** [comment]
@albertbori Sure, but that's missing the point. I don't expect to do something manually if you point to a branch. I expect the dependency to be at the same state as the sources I get when cloning the repo, checking out that branch, and building.

**Comment by KimiChiu** [comment]
Here's how I did:
1. remove `pod 'library'` from Podfile
2. run `pod install`
3. add `pod 'library'` back
4. run `pod install` again
