### ISSUE TITLE
Duplicate Paths in FRAMEWORK_SEARCH_PATHS when a pod has multi vendored_frameworks

### ISSUE THREAD

**Issue by kejinlu** [CocoaPods/CocoaPods#1882]
I believe that it should remove  duplicate paths

**Comment by lemonkey** [comment]
Also confirmed if you're writing a podspec and have:

s.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '"$(PLATFORM_DIR)/Developer/Library/Frameworks"' }

The resulting Pods-xxx-debug.xcconfig has:

FRAMEWORK_SEARCH_PATHS = "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(PLATFORM_DIR)/Developer/Library/Frameworks"

**Comment by segiddins** [comment]
I don't think we can safely _always_ remove duplicate paths, as ordering matters.
