### ISSUE TITLE
Setting preprocessor macros from Podfile 

### ISSUE THREAD

**Issue by yuriy-tolstoguzov** [CocoaPods/CocoaPods#1884]
I want to implement switcher for logging internal stuff via preprocessor macros. As I found out there's no way to setup macros in an application, because Pods static library is compiling before application. The only way to set them is to put them into setting of Pods-MyLibrary target.
Except the fact that it's not convenient way to change setting of Pods targets for user, the one more problem: user can recreate workspace and Pods project file and their macros will be reseted. 
It will be great to have the way to add preprocessor macros in pods target via Podfile.
Thanks!

**Comment by malhal** [comment]
I took a look at the post_install guide above but struggling to apply that technique to appending a preprocessor macro. Anyone done it?

**Comment by orta** [comment]
You may be able to get there via build settings, [here is an example](https://github.com/artsy/eigen/blob/01b1c5a811d58d1ae2cedcac563a2c1c6da50225/Podfile#L134) of using that.

**Comment by malhal** [comment]
Thanks but that doesn't show what keys to use for the pre-processor macros and build vs release is going to add another complication. However it did give me the idea to just append to the pch:

```
post_install do |installer|
    File.open('Pods/Target Support Files/MHData/MHData-prefix.pch', 'a') { |f| f.puts("#define MHDATA_PREFIX_TO_ADD ZZ\n") }
end
```
