### ISSUE TITLE
resource_bundle and xcassets

### ISSUE THREAD

**Issue by bilby91** [CocoaPods/CocoaPods#1892]
So, im bundling some images with a library we are building. 

In my podspec i have s.resource_bundle { 'MyKit' => 'MyKit/Resources/Images.xcassets' }

How should i access my images inside MyKit ?  I managed to access them writing the full-path, this is horrible because it doesn't support multiple resolution handling. 

Is it possible to have different resource_bundle in subspecs?

**Comment by fatuhoku** [comment]
+1 the linked issue doesn't really seem to answer this issue. @bilby91 did you get it working in the end?

**Comment by crsantos** [comment]
Any ideas?

**Comment by peterdeweese** [comment]
+1. This still seems to be an issue.

**Comment by cuddergambino** [comment]
So I've run into this problem as well, and now coming back with a solution.
I just tried adding `.xcassets` to the `resource_bundle`, and it seems to be functional now. I have a few images (each with sizes 1x,2x,3x) in the `.xcassets` and they successfully load.


##### MyKit.podspec
```ruby
s.ios.resource_bundle = { 'MyKit' => 'Resources/**/*.xcassets' }
```

##### MyKitImageRetriever.swift
```swift
let podBundle = NSBundle(forClass: MyKitImageRetriever.self)
if let url = podBundle.URLForResource("MyKit", withExtension: "bundle"){
    let mykitBundle = NSBundle(URL: url)
    let retrievedImage = UIImage(named: "imagename", inBundle:mykitBundle, compatibleWithTraitCollection: nil)
    // now you have the image
}
```

**Comment by thexande** [comment]
`UIImage`convenience `init` for swift 4:

```swift
 extension UIImage {
    convenience init?(podAssetName: String) {
        let podBundle = Bundle(for: ConfettiView.self)
       
        /// A given class within your Pod framework
        guard let url = podBundle.url(forResource: "CryptoContribute",
                                      withExtension: "bundle") else {
            return nil
                                        
        }

        self.init(named: podAssetName,
                  in: Bundle(url: url),
                  compatibleWith: nil)
    }
 }
```
