### ISSUE TITLE
Move `pod install` command line flags to the Podfile DSL

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#1983]
The `--no-integrate` and (likely) the `--no-clean` make more sense at the Podfile level.

**Comment by chipsnyder** [comment]
This seems to have been lumped in to larger change sets and then lost. What is the current status of moving the `--no-integrate` flag to the Podfile?

**Comment by segiddins** [comment]
@chipsnyder as the issue is still open, and there have been no recent comments or linked pull requests, there has been no implementation progress on this feature.

**Comment by segiddins** [comment]
This is in as of the 1.0 betas.
