### ISSUE TITLE
header not found

### ISSUE THREAD

**Issue by scutdavy** [CocoaPods/CocoaPods#199]
I have add `dependency 'DDPageControl'` to Podfile and install,

but code tell me it could could not find     "DDPageControl.h",

any idea about this?

**Comment by NickolasHu** [comment]
In my situation, symbol links does not generate. I have pod 'xxx' , 'xxx' in Podfile and 'FRAME_WORK_SEARCH_PATH' in my spec. Why the Pods/Header/xxx symbol links does not generated, how these file generated?
