### ISSUE TITLE
Move more commands out of `CocoaPods`

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#2001]
I was thinking it might be nice to move some functionality into plugins, this will allow us to make more plugin releases independently of CocoaPods.

Things like `pod lib` could probably sit in it's own plugin. If we plan to do this, we need to decide on the rules for weather things go into a plugin or get bundled into this repository.

/cc @irrationalfab any thought?

**Comment by segiddins** [comment]
Closing as we don't need an issue tracking this -- we'll factor out things into plugins as we go along.
