### ISSUE TITLE
Semantic Versioning: metadata unsupported

### ISSUE THREAD

**Issue by darkFunction** [CocoaPods/CocoaPods#2017]
The Cocoapods guide states that we should use Semantic Versioning ( http://semver.org/ ) as the schema for our version numbers. However this is not fully implemented and I am unable to include metadata (in my particular case, the branch name).

I used a direct sample from the schema specification to test this.

**The schema rules state:**
*Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata SHOULD be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.*

**However Cocoapods reports:**
`ArgumentError - Malformed version number string 1.0.0-beta+exp.sha.5114f85`

**Comment by segiddins** [comment]
Closing, since this isn't really worth fixing -- changing the version class would break too much existing stuff.

**Comment by darkFunction** [comment]
If there are no plans to fix this, the documentation should be updated to state that Semantic Versioning is unsupported.
