### ISSUE TITLE
Podfile with iOS and OSX Support

### ISSUE THREAD

**Issue by levigroker** [CocoaPods/CocoaPods#2043]
I'm trying to setup CocoaPods with a legacy project which has both iOS and a OSX targets.

If, at the top of my Podfile, I specify:

```
platform :osx, '10.9'
```

and, as an example, specify a pod like CorePlot:

```
pod 'CorePlot'
```

Then, after a `pod update`, I see Mac specific sources in my Pods directory:

```
Pods/CorePlot/framework/MacOnly
```

which is okay, except that if I were to specify `:ios` as the `platform` then I see:

```
Pods/CorePlot/framework/iPhoneOnly
```

and I _do not_ see the `MacOnly` directory.

CorePlot's podspec specifies these directories based on the platform, which is why they are showing up differently based on the platform I select. However, I would like to be able to have my Podfile work for my iOS and OSX targets.

I continued and thought perhaps I could specify the platform based on the target in my project, and omit the top level platform declaration:

```
target "OSX" do
  platform :osx, '10.9'
end

target "iOS" do
  platform :ios, '7.0'
end
```

However, once I again do a `pod update` now I get a version compatibility error:

> [!] The platform of the target `Pods` (OS X ) is not compatible with `CorePlot (1.5.1)` which has a minimum requirement of iOS 3.1.3 - OS X 10.5."

Which would seem to indicate that CocoaPods is not recognizing the version information in my target block.

And, if I add a platform to the top level, in addition to the target specific platform, I then get only the code for whichever platform the top level platform indicated.

Am I forced to have two separate projects? One for iOS and one for Mac OS X, or is there a way to do this?

Many thanks,

Levi

```
   CocoaPods : 0.31.1
        Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
    RubyGems : 2.0.3
        Host : Mac OS X 10.9.2 (13C64)
       Xcode : 5.1.1 (5B1008)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib Repositories : master - https://github.com/CocoaPods/Specs.git @ bf6ff4b23c2e8b9e5fe5840eddfc3bad122eb932
```

**Comment by rchatham** [comment]
Running into a similar problem. My podfile looks like below. 

```
workspace 'bnb.me.xcworkspace'

target 'bnb.me.ios' do

  project 'bnb.me.ios.xcodeproj'
  platform :ios, '9.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bnb.me.ios
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'CoordinatorType'

  target 'bnb.me.iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'bnb.me.mac' do

  project 'bnb.me.mac.xcodeproj'
  platform :osx, '10.10'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bnb.me.mac
  pod 'CoordinatorType'

  target 'bnb.me.macTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

I also maintain this cocoapod. The .podspec looks like below.

```
Pod::Spec.new do |s|

  s.name         = "CoordinatorType"
  s.version      = "0.0.1"
  s.summary      = "CoordinatorType protocol for making implementing the Coordinator pattern painless."
  s.description  = <<-DESC
  CoordinatorType protocol with basic Coordinator requirements implemented and default functionality implemented via protocol extensions.
                   DESC
  s.homepage     = "https://github.com/rchatham/CoordinatorType.git"
  s.license      = "MIT"
  s.author             = { "Reid Chatham" => "reid.chatham@gmail.com" }

  s.ios.deployment_target = "8.0"
  s.osx.deployment_target = "10.10"

  s.source       = { :git => "https://github.com/rchatham/CoordinatorType.git", :tag => "#{s.version}" }

  s.ios.source_files   = 'CoordinatorType-iOS/*.swift'
  s.osx.source_files   = 'CoordinatorType-macOS/*.swift'

end
```

**Comment by Akateason** [comment]
new another target for mac only. 
then write you 'Podfile' like this
```

def commonPods
      pod 'a'
      # ...
end

target 'testDemo' do
  use_frameworks!
  platform:'ios','8.0'
  commonPods  
  pod 'b'
  pod 'c'
  # ...
end


target 'testDemoMac' do
  use_frameworks!
  platform:'osx','10.15'
  commonPods
  pod 'd'
  pod 'e'
  # ...
end

```
