### ISSUE TITLE
Prevent CocoaPods from creating project file conflicts

### ISSUE THREAD

**Issue by brennanMKE** [CocoaPods/CocoaPods#2047]
I just found that the project file was in conflict which prevented a Pull Request from being able to do a clean merge. This project file is approaching 1MB already and once it was conflicted the size was doubled by Git and FileMerge had trouble with loading it.

Once it did load I found that the conflicts were due to changes like shown below. Is CocoaPods causing the order of references to change or is Xcode? How can conflicts be prevented?

![conflicts](https://cloud.githubusercontent.com/assets/277419/2709422/286df2c6-c4b6-11e3-8f6f-fc923cd50685.png)

**Comment by kylef** [comment]
This would be fixed by https://github.com/CocoaPods/Xcodeproj/issues/175.
