### ISSUE TITLE
Validator/Linter should name offending subspec

### ISSUE THREAD

**Issue by tonyarnold** [CocoaPods/CocoaPods#2052]
Currently, I get the following output if `source_files` doesn't match any files:

```
- ERROR | [Rebel/RBLCGColorAdditions, Rebel/RBObjectSizzlingAdditions, Rebel/RBLViewController, and more...] The `source_files` pattern did not match any file.
```

It would be helpful to know _which_ sub spec isn't finding any files.

**Comment by segiddins** [comment]
This seems to be intentional (https://github.com/CocoaPods/CocoaPods/blob/seg-error-report-command/lib/cocoapods/validator.rb#L95). @orta, which do you prefer?

**Comment by segiddins** [comment]
I'm closing this as behaves as intended. It already lists three subspecs, which should be enough to get started investigating things.
