### ISSUE TITLE
Pods was rejected as an implicit dependency for 'libPods.a' because its architectures '' didn't contain all required architectures 'i386'

### ISSUE THREAD

**Issue by xialin** [CocoaPods/CocoaPods#2053]
Problem occurred after I updated CocoaPods to latest release last night...

Tried to set Architectures to standard (armv7, armv7s, arm64), set Build Active Architecture Only (Debug) to Yes.

It gave me the following warning/error:
Pods was rejected as an implicit dependency for 'libPods.a' because its architectures '' didn't contain all required architectures 'i386'
Library not found for -lPods

**Comment by Hackmodford** [comment]
@kvasavi That did the trick for me too :)

**Comment by bingeh** [comment]
It doesn't work, the question still remains.

**Comment by lcmaizld** [comment]
Thanks!!! it is worked

**Comment by KrLx1994roller** [comment]
mmiroslav answer is the correct one!

In my case, the project 'Build Active Architectures' was set to 'No'. Correct. But the pods' setting was set to 'Yes'. Changed to 'No' and warking very well! :+1:

**Comment by krvc** [comment]
I am using Xcode 6.1.1. By setting the "Build Active Architectures Only" to No, in main project and Pods subproject helped me to fix the above warning.

**Comment by XQ0820** [comment]
I am using Xcode 6.4
Set Build Active Architectures Only to No in Pods subproject also. help me to fix the problem

**Comment by ashfurrow** [comment]
I had this issue when I inadvertently deleted the "Debug" configuration from the Xcode project. Undoing that using git fixed the problem.

**Comment by dwdyer** [comment]
I get this problem every time I do a "pod install" (Cocoapods 0.39, Xcode 7 and 7.1).

I get around it by changing the Architectures setting of each pod to $(ARCHS_STANDARD) (by default it gets set to only 32-bit architectures). Shouldn't this issue still be open as I shouldn't need to manually edit files generated by Cocoapods?

**Comment by khanhankkhan** [comment]
why does pods never work in general?

**Comment by engmsaleh** [comment]
I have Xcode 7.1  and none of the above worked for me

**Comment by dinuvld** [comment]
Indeed, none of them worked for me on Xcode 7.1

**Comment by colorlength** [comment]
thanks!It work for me to~@xialin

**Comment by jkunzelman** [comment]
This seems like an ongoing problem that a number of people have been reporting. I'm experiencing the same and combination of all of the above techniques seems to fix it for a while, but as soon as I install another pod or run pod install everything gets reset and you have to go thru all the trouble shooting steps again. I've tried the prerelease betas and nothing seems to resolve the overall problem. I've followed all the steps in the trouble shooting FAQ. Very frustrating... Sorry to rant but i needed an outlet before I drive myself insane.

**Comment by toshiakiokano** [comment]
Worked for me. Thanks! @xialin

**Comment by Ged2323** [comment]
Yeah I had the GoogleMobileAds.framework already in my project. I deleted that then set the Build Active Architecture to 'Yes' then built it then you can se tit back to No and it will still build.

**Comment by HancleLee** [comment]
none of them work for me!!!Xcode7.3 cocopods1.0.0

**Comment by bikisDesign** [comment]
None of the above worked for me either. Has anyone found a different fix to this issue? Xcode 7.3 cocopods 1.0.0

**Comment by Scarafone** [comment]
None of the above has worked for me either. I will be trying to uninstall and reinstall, but all these issues first started happening to me when I first updated Cocoapods. Also it seems to build just fine if I am building directly to a physical device or building for simulator iPhone 5s and up. Only iphone 4s and 5 on simulator give me this issue.

**Comment by alvincrisuy** [comment]
Same here, nothing worked for me. I tried all the steps already. In my case, it is working on iPhone 4s others are not working.

**Comment by JoneRen** [comment]
none worked for me too, cocoapod v1.0.1, xcode 7.3, not working on iphone5c, worked on iphone6 and above.

**Comment by JoneRen** [comment]
ld: warning: ld: warning: ld: warning: ld: warning: ld: warning: ld: warning: ignoring file /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libAFNetworking.a, file was built for archive which is not the architecture being linked (armv7): /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libAFNetworking.aignoring file /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libDXPopover.a, file was built for archive which is not the architecture being linked (armv7): /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libDXPopover.aignoring file /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libFLEX.a, file was built for archive which is not the architecture being linked (armv7): /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libFLEX.aignoring file /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libBlocksKit.a, file was built for archive which is not the architecture being linked (armv7): /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libBlocksKit.aignoring file /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libAPParallaxHeader.a, file was built for archive which is not the architecture being linked (armv7): /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libAPParallaxHeader.aignoring file /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libFontAwesome+iOS.a, file was built for archive which is not the architecture being linked (armv7): /Users/renfei/Library/Developer/Xcode/DerivedData/littlewitch-fcnqufajtyuhhjfsxnlkudjwumjd/Build/Products/Debug-iphoneos/libFontAwesome+iOS.a

**Comment by alvincrisuy** [comment]
I solved it by deleting the derived data of my project in /Users/account/Library/Developer/Xcode/DerivedData

Hope this help.

**Comment by JoneRen** [comment]
@alvincrisuy  thanks for you quick reply, delete the derived data ,and set the "Build Active Architecture Only " to "YES" worked for me. 👍

**Comment by mhalttu** [comment]
I spent a couple of hours fighting with this, going through all the Google hits I could find. My build worked for the device, but not for the simulator. Here are the steps that finally solved the issue for me:

`
rm -rf ~/Library/Developer/Xcode/DerivedData/
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
`

And finally going to the Pods project and setting "Build Active Architectures Only" to "No" also for Debug.

**Comment by jakedunc** [comment]
Xcode 7.3.1 and cocoapods 1.0.1 I have this issue over and over again. I have tried all of the above solutions with no help. What else can I do!?

I am getting a bunch of "ld: warning: directory not found for option" and a "ld: library not found..."

**Comment by akouzeli** [comment]
Thanks a lot @alvincrisuy! 
After trying everything related to this issue that I found in Google, I can say your solution was the only one that did the job.

**Comment by mlchai** [comment]
For me a combination of things seemed to help.

- set platform to 8.0 in Podfile
- set "Build Active Architectures Only" to "YES" for BOTH the app and the Pod project files. Setting it to "NO" actually made it not build.
- run the commands (mostly deleting the DerivedData folder) in @mhalttu comment

**Comment by Zooeee** [comment]
Using cocoa pod 0.39.0, and 7.3.1, and none of the above solutions help.

**Comment by guidmattos** [comment]
You saved my life! Thanks!

**Comment by bhautikappv** [comment]
Hi all,

My project was developed in xcode 6.4 and trying to run it in xcode 8.0 but i got following error.

![screeen](https://cloud.githubusercontent.com/assets/24278294/21157937/47c42db0-c149-11e6-868b-a81eb5083825.png)

please suggest a way to successfully build project.

**Comment by benasher44** [comment]
Hi @bhautikappv! Thanks for letting us know! This issue is quite old, so we'd appreciate if you could file a new issue and fill out the issue template. If you could do that, we'd be happy to help. Have a great day!

**Comment by rtauziac** [comment]
I changed the default configuration names from Debug and Release to Dev and Prod before pod install. Don't do this because it breaks everything.
Actually I had to set the new names  to the pods and target configuration by hand to solve that, but this is tedious.

**Comment by luminkhant** [comment]
it work for me too.
Thanks @xialin

**Comment by JustCallMeDanTheMan** [comment]
I recently hit this issue after incorporating Firebase into a project, before completely configuring it i.e. it still had the default and latest target iOS version. Evidently, when properly configuring it later, sufficiently lowering the iOS target version to something sensible for my needs triggered this warning in Xcode for me. I guess earlier versions of iOS need to support older architectures (e.g. not just arm64), and so adding the need for arm7 later in the life of the project might trigger it... Wild guess, of course.

I'm sure for many, including me, it is my first encounter with Pods, with an entirely "I will do what they tell me to" approach, so a lot of people who have this issue (and find this page through high ranking on Google searches for the warning message contents) may be as utterly clueless as I am. Hence I have joined to post and leave a trail, with my scenario to aid future Google searches, for future fellow clueless folks to follow.

That's a lot of f words, though not as many as I uttered earlier in response to the issue.


Anyway, I followed mhalttu's comments verbatim (https://github.com/CocoaPods/CocoaPods/issues/2053#issuecomment-227248074) and this fixed the issue for me. Thanks mhalttu!

**Comment by kiraninfogird** [comment]
**_Deleted pods folder and Podfile.lock and did a pod install and repeated the above setting..._**

It's working now...!
Thanks...

**Comment by Abhishek-NickelFox** [comment]
@kiraninfogird : Thanks Alot !!!! :)

**Comment by mtpromano** [comment]
I had the same issue recently after **migrating to Xcode 10.1**.

Building with Debug config was working just fine, however archiving with Release config was generating this warning. 
And then archiving would fail, because in the main project all the **module imports** referring to Pods were failing.

Checking the **Build Settings** for the **Project** I realised that **iOS Deployment Target** was showing a different value for my Release config.
iOS 10.0, while my **Podfile** was set to `platform :ios, '11.0'`.

[![enter image description here][1]][1]



  [1]: https://i.stack.imgur.com/15zyL.png

**Comment by Yogesh-stackgeeks** [comment]
> I spent a couple of hours fighting with this, going through all the Google hits I could find. My build worked for the device, but not for the simulator. Here are the steps that finally solved the issue for me:
> 
> ```
> rm -rf ~/Library/Developer/Xcode/DerivedData/
> rm -rf "${HOME}/Library/Caches/CocoaPods"
> rm -rf "`pwd`/Pods/"
> pod update
> ```
> 
> And finally going to the Pods project and setting "Build Active Architectures Only" to "No" also for Debug.

I love you man, I have spent hours before find your solution which finally worked

**Comment by seneka13** [comment]
> I spent a couple of hours fighting with this, going through all the Google hits I could find. My build worked for the device, but not for the simulator. Here are the steps that finally solved the issue for me:
> 
> ```
> rm -rf ~/Library/Developer/Xcode/DerivedData/
> rm -rf "${HOME}/Library/Caches/CocoaPods"
> rm -rf "`pwd`/Pods/"
> pod update
> ```
> 
> And finally going to the Pods project and setting "Build Active Architectures Only" to "No" also for Debug.

Thank you man, I spent 2 days in searching problem decision
