### ISSUE TITLE
Language: "acknowledgement" vs. "acknowledgment"

### ISSUE THREAD

**Issue by notjosh** [CocoaPods/CocoaPods#2061]
CocoaPods seems to be preferring US English (i.e. "-ize") in the docs/code that I've seen. For the sake of consistency, "acknowledgment" should be used over "acknowledgement".

Some background:
 - https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Spelling
 - http://grammarist.com/spelling/acknowledgment-acknowledgement/

I'm happy to make a pass through and correct it myself, but just checking in first to see if it's a worthwhile concern. Thoughts?

**Comment by segiddins** [comment]
Closing.
