### ISSUE TITLE
Add ability to deprecate a pod (or specific versions) in favour of system functionality

### ISSUE THREAD

**Issue by stig** [CocoaPods/CocoaPods#2062]
I want to be able to deprecate some versions of SBJson in favour of _either_ later versions of itself (if you want chunked streaming / chunked delivery) _or_ NSJSONSerialisation - if you just want plain parsing.

**Comment by zlrs** [comment]
Do we have a solution for this problem now?

**Comment by visumickey** [comment]
Curious to see if there are any updates here. Is it possible to deprecate users who use older version of a library to move to the latest version of the library?
