### ISSUE TITLE
Agressive xcassets compilation policy can lead to duplicated resources

### ISSUE THREAD

**Issue by nikolaykasyanov** [CocoaPods/CocoaPods#2087]
I have the following configuration:
* Main project uses CococaPods
* Library project submodule located in $MAIN_PROJECT_DIR/Library/SomeLibrary
* I'm referencing library in main project's Podfile

Library contains *.xcassets and I prefer to use resource bundle for it. Here's the fragment of Library.podspec:
```
s.resource_bundle = {'LibraryResources' => ['Library/*.lproj', 'Library/Assets.xcassets']}
```

Everything compiles to LibraryResources.bundle, which then copied to application bundle as intended.

But because of this [part](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/copy_resources_script.rb#L138) of "Copy Pods Resources" script, `Library/Assets.xcassets` compiled again and results are copied to application bundle.

In the end I have duplicated images in Application.app and in Application.app/LibraryResources.bundle.

I found nasty workaround, changed "Copy Pods Resources" build phase script like this:

```bash
WRAPPER_EXTENSION=""
"${SRCROOT}/Pods/Pods-resources.sh"
```

What's the point in compiling every *.xcassets in project tree? User project should have them added to targets anyway, podspecs can reference them through `resources` or `resource_bundle`. Also, unnecessary work, because almost all *.xcassets would compile twice.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
