### ISSUE TITLE
Multiple projects integrated into a single .xcworkspace breaks/confuses Xcode

### ISSUE THREAD

**Issue by erichoracek** [CocoaPods/CocoaPods#2093]
Currently if you have multiple projects that are integrated into a single `.xcworkspace` with different dependencies it can cause issues building targets in either one of the projects.

An example of this configuration would be a Pod that has a `Tests` folder and an `Example` folder that each contain a `.xcodeproj`, each of which are both integrated into a root-level `.xcworkspace`. When a `$ pod install` is performed in each (creating two references to a `Pods.xcodeproj` in the root-level `.xcworkspace`), Xcode appears to randomly choose from the two available `Pods.xcodeproj`s, causing nondeterministic build failures.

A solution for this would be naming both of the `Pods.xcodeproj` in a unique way when there's already one present in the `.xcworkspace` that it's integrated into (e.g. `Pods-Tests.xcodeproj` and `Pods-Example.xcodeproj`).

**Comment by arjun-kava** [comment]
Add line at top of the file after platform,
```
project '<Project>.xcodeproj'
```
