### ISSUE TITLE
Download the Pods in parallel

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#2100]
Using something like https://github.com/beraboris/eldritch could be an option.

**Comment by orta** [comment]
Given that a lot of people have been forced to update git, perhaps the `--git-dir` thing could be a nice, covers the 90% use case?

**Comment by segiddins** [comment]
I'll look into it when I do the caching. 

-Samuel E. Giddins

On Feb 23, 2015, at 9:14 AM, Orta <notifications@github.com> wrote:

Given that a lot of people have been forced to update git, perhaps the --git-dir thing could be a nice, covers the 90% use case?

**Comment by neonichu** [comment]
`--git-dir` is already a thing in the version that ships with Xcode 6.1.1, which is 1.9.3

**Comment by segiddins** [comment]
I took a stab at https://github.com/CocoaPods/CocoaPods/tree/seg-concurrent.

**Comment by segiddins** [comment]
@kylef think we can close this now we have a download cache?
