### ISSUE TITLE
Custom configurations in primary project and incorrect Enable Foundation Assertions in Pods project

### ISSUE THREAD

**Issue by amayers** [CocoaPods/CocoaPods#2114]
I have been using some custom configurations in my projects, so on my main project I have: `Debug`, `Debug Staging`, `Release`, `Release Staging`. When I run a `pod install` and it generates the Pods project it faithfully recreates these configurations 👍. However I've noticed that the Pods project uses different values for the `Enable Foundation Assertions` build setting. In my main project both `Debug` and `Debug Staging` both have `Enable Foundation Assertions` set to YES, however the Pod project only sets `Debug` to YES, I would assume it would copy the main project's build settings for each configuration, unless there was a specific setting on a pod to override some setting.

**Comment by rsaunders100** [comment]
@alloy - Hey, we have the same issue.  - We want assertions in debug and not prod.

Are you saying we should do this?

```
target 'MyApp' do
  pod 'Reachability' :debug
  pod 'CocoaLumberjack' :debug
end
```
