### ISSUE TITLE
Additional environmental variables for prepare_command

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#2115]
When running full build scripts within prepare_command we need a way to expose the paths to C dependencies to configure scripts. A `$PODS_ROOT` environmental variable (or similar) would be useful so we can find the path to installed dependencies.

It looks like it might be easy to add: https://github.com/CocoaPods/CocoaPods/blob/453a7dae5fd2a46b04f3e97d8bd9d02559816850/lib/cocoapods/installer/pod_source_installer.rb#L139

For example, if I am making a podspec for a C library w/ a standard configure script that looks for OpenSSL, I need a way to point it to the location.

``` ruby
s.prepare_command = <<-CMD
./configure --openssl-headers="$PODS_ROOT/OpenSSL/Include" --prefix="$PODS_ROOT/SomeLibrary/"
CMD
```

**Comment by chrisballinger** [comment]
@segiddins Any movement on this?

**Comment by segiddins** [comment]
@chrisballinger not really -- it's actually incompatible with how the cache handles prepare command pods. Since there haven't been that many requests for this (rather substantial) feature, it's been relatively low priority for us.

**Comment by chrisballinger** [comment]
Ah okay, that sucks. Is there any wiggle room within the current design, or does it need a complete overhaul? I'd be willing to contribute towards this because it keeps popping up on C library Pods that I've been porting native podspecs from autotools hell.

For example: https://github.com/chrisballinger/libidn-podspec/issues/1

I need to run a configure script but it fails since it's invoked from the wrong directory, but if I could `cd` into `$PODS_ROOT` it would solve that issue.

**Comment by neonichu** [comment]
@chrisballinger we discussed this a bit internally and came to the conclusion that `prepare_command` isn't really viable for building things, because it is run once, prior to caching. So environmental information like platform, deployment target, architecture, etc. aren't even available at that point in time.

As @segiddins mentioned earlier, these really custom builds should happen as "External Build System" targets inside Xcode itself instead. The idea would be to add a new DSL attribute for that and CP would then generate such a target wrapping a script. This should make all the required information available via Xcode's build environment variables.

Would you be interested in working on that? If yes, I could help you out a bit in regards to navigating the CP codebase and getting this integrated.

**Comment by virtru-bjost** [comment]
Whats the status on this? I am really in need of `${POD_PLATFORM}` for the prepare_command so it can run the appropriate compile script.

**Comment by segiddins** [comment]
@virtru-bjost no progress has been made

**Comment by fragno** [comment]
really looking forward to this feature

**Comment by Snorlock** [comment]
I would love to know from where the pod install was called as an environment variable!
Like something project dir or similar.
Does it exist anything like this now?

**Comment by dnkoutso** [comment]
I think this would be an awesome idea to implement. Ability for podspecs to define external build system phases that have access to all xcode envt variables.

**Comment by guykogus** [comment]
Also wishing we had some environment variables right now...

**Comment by dnkoutso** [comment]
I think I am going to implement this.

**Comment by DanToml** [comment]
@dnkoutso could you write up a comment with the env vars you want to start exporting first? - Would be really nice to not leak details about other dependencies into this I think?

**Comment by dnkoutso** [comment]
@DanToml I am thinking of something like:

```ruby
spec.script_phase = { :name => 'Something', :script => 'echo "Hello World"' }
```

You wont be getting envt variables from other pods, you will only get the same one Xcode exposes when building, so things like $(PRODUCT_NAME), $(TARGET_NAME) etc.

What do you think?

**Comment by DanToml** [comment]
@dnkoutso iiinteresting, that sounds like it could work reasonably well? - I'm a little worried about how much DSL we've added lately tho (especially with us still not having future swift planned out)

**Comment by dnkoutso** [comment]
yeah same re: DSL but I think those are fairly safe/easy to add. The most challenging part actually is the ordering of the script phases. For example, there could be a reason you want a script phase to run after compile sources or before, or after copy headers or before, etc.

I think the more powerful we make cocoapods the more customization will exist :)

**Comment by DanToml** [comment]
Aye, it's just a difficult balance between power/customization and maintainability/understandibilty, especially for things that are super niche. (Not necessarily saying no to this, just being mindful of it.)

**Comment by Coeur** [comment]
@dnkoutso so maybe:

    spec.after_compile_script = ...
    spec.before_copy_headers_script = ...
    spec.after_copy_headers_script = ...

**Comment by dnkoutso** [comment]
@Coeur this will make the DSL a bit noisier...we might need to start small here let me think about it a bit more

**Comment by Coeur** [comment]
And what about:

    spec.scripts.after_compile = ...
    spec.scripts.before_copy_headers = ...
    spec.scripts.after_copy_headers = ...
    spec.scripts.after_install = ...

Then there is only one key "scripts".

**Comment by dnkoutso** [comment]
@Coeur I did not implement the Podspec DSL but I did implement the Podfile DSL:

https://github.com/CocoaPods/Core/pull/389
https://github.com/CocoaPods/CocoaPods/pull/6820

I still haven't solved 100% the DSL for adding before or after sources etc. 

You will be able to do:

```ruby
target 'SampleApp' do
  pod 'Alamofire'
  script_phase :name => 'HelloWorldScript2', :script => 'puts "Hello World"', :shell_path => '/usr/bin/ruby'
end
```

**Comment by dnkoutso** [comment]
Will continue work perhaps to enable Podspec DSL to allow script phases for podspecs.

In the meantime Podfile DSL will ship with 1.4.0.beta.1.

**Comment by bstpierr** [comment]
@dnkoutso This is great!

We would greatly appreciate the ability to add a script phase to the podspec as well. Our libraries require a developer key to be present to function correctly, as well as certain aps-environment & entitlement settings and we would like to add a simple linter check that provides a good human-readable warning when building if the settings are incorrect.

Being able to define this script in the podspec would simplify the Podfile setup our developers need to get started.

**Comment by dnkoutso** [comment]
@bstpierr will try to get this for 1.4.0. I want the same feature :)

**Comment by dnkoutso** [comment]
Here's the PR that adds the DSL to the core for allowing podspecs to specify script phases.

https://github.com/CocoaPods/Core/pull/413

**Comment by dnkoutso** [comment]
And the CocoaPods PR to add the script phases

https://github.com/CocoaPods/CocoaPods/pull/7092

**Comment by dnkoutso** [comment]
DSL has been merged. CocoaPods PR should hopefully land tomorrow.

There will be one follow up change in the DSL to allow specifying an execution placement for the script (i.e `:before_compile` etc.)

**Comment by vongohren** [comment]
Does these PRs allow for to specify posistion of the scriptpahse? Or is it append only?

**Comment by dnkoutso** [comment]
Not yet but the plan is to support this in 1.4.0.

**Comment by dnkoutso** [comment]
Merged the CP pr. This is without positioning yet but will be adding this next.

**Comment by vongohren** [comment]
I have made a issue on our bord to check it out!

**Comment by dnkoutso** [comment]
@vongohren seems like there was one more bug. Fixed here https://github.com/CocoaPods/CocoaPods/pull/7104

If you tried `script_phases` it probably didn't work at all unless you had test specs in your podspec.

Fixed in the PR above.
