### ISSUE TITLE
duplicate symbol _OBJC_METACLASS_$_PodsDummy_Pods

### ISSUE THREAD

**Issue by tonglesu** [CocoaPods/CocoaPods#2125]
I make a xx.a（use cocoaPods） server it to others,they want to use it in a project which used cocoaPods too,get this error:

duplicate symbol _OBJC_METACLASS_$_PodsDummy_Pods in:
    xx.a(Pods-dummy.o)
    other.a(Pods-dummy.o)
duplicate symbol _OBJC_CLASS_$_PodsDummy_Pods in:
    xx.a(Pods-dummy.o)
   other.a(Pods-dummy.o)

How can I resolve it? Can I delete the Pods-dummy.o from xx.a?

**Comment by WedgeSparda** [comment]
Same problem here. Deleted the files showed on the log error but the problem persists.

**Comment by ManiaChamp** [comment]
What is the solution of it ?
