### ISSUE TITLE
pod lib lint doesn’t check frameworks

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/CocoaPods#2134]
The `pod lib lint` command only compiles static libraries but doesn’t try to link them to an application executable. So if you forget to specify a framework in the podspec, the linker error that will ensue will not be caught by the linter but only once you use the pod in an actual project.

**Comment by segiddins** [comment]
This is even more relevant now that CocoaPods supports building frameworks :)

**Comment by tapi** [comment]
`--use-frameworks` was mentioned in the [blog post](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) but seems to be missing in 0.36.1. Is there a branch that has this flag we could use during migration to frameworks?

**Comment by kylef** [comment]
@tapi Since that post, we've reversed pod linting to use frameworks by default, and introduced it's counterpart `--use-libraries` to disable this.

**Comment by tapi** [comment]
👍🏻 Good to know, thanks.
