### ISSUE TITLE
Pod-resources.sh location

### ISSUE THREAD

**Issue by ldtkhanh2306** [CocoaPods/CocoaPods#2137]
The latest version I have of cocoapods (0.32.1) has the "Copy Pods Resources" of the target project generated as following:
"${SRCROOT}/Pods/Pods-resources.sh"

, which should be better changed to:
"${PODS_ROOT}/Pods-resources.sh"

**Comment by segiddins** [comment]
Closing this since the logic is properly encapsulated as-is.
