### ISSUE TITLE
Build Error after installing pods.

### ISSUE THREAD

**Issue by PrashantSharma15** [CocoaPods/CocoaPods#2163]
Hello, 

I am building a framework referring to this tutorial :
http://www.raywenderlich.com/65964/create-a-framework-for-ios

Thus i have to targets for my project: 

When i run "pod init" to "My Project Dir"  the podfile is created as : 

```
platform :ios, '7.0'

target 'MYFramework' do
end

target 'MYFrameworkTests' do
end

target 'Framework' do
end
```

I add `pod "AFNetworking", "~> 2.0" to 'MYFramework'`

and then run pod install : where i get error : `[!] Unable to find a target named 'Framework'`

strange !

after this i remove target 'Framework' do from pod file and then again hit pod install, where the pod is installed and i get the project workspace created. 

After that i try build my project i get the following error : 

```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-MyFramework
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-MyFramework is not an object file (not allowed in a library)
```

Before installing pods everything was cool. But not after.
Can you help.

Thanks in advance. 

Prashant.

**Comment by lexicalunit** [comment]
I am still having this issue and deintegrate didn't help at all. In fact I rm -rfed my entire project, manually created a new project, re-added all my source files, re-ran pod install, and still I get the error.

xcode version: 6.1.1


# Build Log

```
Resolving target dependencies
Pods-MyLib was rejected as an implicit dependency for 'libPods-MyLib.a' because it doesn't contain platform 'iphonesimulator' in its SUPPORTED_PLATFORMS 'macosx'
Libtool /Users/lexicalunit/Library/Developer/Xcode/DerivedData/MyLib-daqzvftypdrvlxglytqlijqueelr/Build/Products/Debug-iphonesimulator/libMyLib.a normal x86_64
    cd /Users/lexicalunit/projects/ios-client-sdk/MyLib
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/lexicalunit/Library/Developer/Xcode/DerivedData/MyLib-daqzvftypdrvlxglytqlijqueelr/Build/Products/Debug-iphonesimulator -filelist /Users/lexicalunit/Library/Developer/Xcode/DerivedData/MyLib-daqzvftypdrvlxglytqlijqueelr/Build/Intermediates/MyLib.build/Debug-iphonesimulator/MyLib.build/Objects-normal/x86_64/MyLib.LinkFileList -ObjC -lPods-MyLib -o /Users/lexicalunit/Library/Developer/Xcode/DerivedData/MyLib-daqzvftypdrvlxglytqlijqueelr/Build/Products/Debug-iphonesimulator/libMyLib.a

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified the following flags are invalid: -ObjC 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-MyLib
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-MyLib is not an object file (not allowed in a library)
```

**Comment by kylef** [comment]
> because it doesn't contain platform 'iphonesimulator' in its SUPPORTED_PLATFORMS 'macosx'

@lexicalunit This sounds like you've set the wrong platform in your Podfile. It's not related to this issue.

**Comment by lexicalunit** [comment]
I assure you I haven't done that. The `SUPPORTED_PLATFORMS` contains `iphonesimulator iphoneos macosx` and the Podfile contains `platform :ios, '6.0'` and `platform :osx, '10.9'`.

And the error output I am seeing is exactly the same as seen in this issue, so...

**Comment by ph1lb4** [comment]
i know it is a long time, however was there any solution to your questions @lexicalunit ?
