### ISSUE TITLE
Project New Scheme ld: library not found for -lPods

### ISSUE THREAD

**Issue by simalone** [CocoaPods/CocoaPods#2171]
I need to add a new project configuration in project setting at info tab , but when I do duplicate a release configuration, for example name is "Release2". Then edit my project scheme, set project archive build configuration to "Release2" instead of "release".  Then do archive to get error: library not found for -lPods.  
![1](https://cloud.githubusercontent.com/assets/700749/3053997/3ca70e3a-e1b2-11e3-9612-5a8eb60f4ba4.png)
![2](https://cloud.githubusercontent.com/assets/700749/3053998/3cac39fa-e1b2-11e3-9c21-9290c07cff65.png)
![3](https://cloud.githubusercontent.com/assets/700749/3053999/3cacbe48-e1b2-11e3-83a0-e13bf4ce3a29.png)

**Comment by ajaysharma05** [comment]
library not found for -lPods-AFNetworking

I am also facing the same error like this do you have any solution.

**Comment by AliSoftware** [comment]
@ajaysharma05 did you at least try the solution given above (plus run `pod install` again afterwards)?

**Comment by AngleZhou** [comment]
I met the same error and is struggling on the solution. Run pod install again will always stuck at 
Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git`
And the size is always 56k in ~/.cocoapods no matter one hour or two later.

**Comment by AliSoftware** [comment]
@AngleZhou how is "pod install is always stock at creating shallow clone of spec repo" related to this issue? Sorry I don't follow here.

**Comment by AngleZhou** [comment]
Well, it does not related directly, but is a related problem-solving step. And it worked now, with the help of System>Preference>Activity Monitor>Network, a git-remote-https showing the downloading process. 
Your solution works great!! Thanks!!
