### ISSUE TITLE
[JSON Format] Fix Pod::Command::Spec to handle JSON appropriately

### ISSUE THREAD

**Issue by AliSoftware** [CocoaPods/CocoaPods#2173]
This includes:
* Updating/Adapting the `Spec::XX::description` of each subcommand that mention `NAME.podspec` but not `NAME.podspec.json`
* Adapting `Spec::XX::arguments` likewise
* Fix `Spec::XX::initialize` that don't handle `.podspec.json` extensions and not only `.podspec`. This includes at least [L166](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/spec.rb#L166), [L200](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/spec.rb#L200), [L242](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/spec.rb#L242)
* Fix spec template at [line 463](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/spec.rb#L463)

**Comment by segiddins** [comment]
I'm pretty sure we've since fixed this?

**Comment by AliSoftware** [comment]
Maybe needs a double-check but yeah that was probably handled properly since then.

**Comment by segiddins** [comment]
99% sure this is done.
