### ISSUE TITLE
`pod init` Podfile search should be consistent with `pod install` 

### ISSUE THREAD

**Issue by marcelofabri** [CocoaPods/CocoaPods#2181]
Let's assume I have this folder structure:

`~/project/otherStuff`

`~project` contains an already setup project with CocoaPods (i.e. it also have a `Podfile`). If I create another project inside `otherStuff` and run `pod init`, CP says that I already have a `Podfile`:

```
$ pod init
 [in <redacted>/project]
 [!] Existing Podfile found in directory
```

However, if I manually create a `Podfile` and run `pod install` the dependencies are installed just fine.

This issue is to suggest that the same behavior is applied on both commands. I see two options here:
- Make `pod install` to fail on this case because a project inside another one's folder structure will not be allowed.
- Make `pod init` smarter and only search parent folders is a `.xcodeproj` isn't found on the current folder.

IMO the second way should be the expected behavior. 

I don't know Ruby very well, but I can try to create a PR once we set what is the expected behavior.

**Comment by rogerfsg** [comment]
What we can do to force to rerun the pod init?
