### ISSUE TITLE
prepare_command not executed when using :path...but sometimes it is

### ISSUE THREAD

**Issue by wilmarvh** [CocoaPods/CocoaPods#2187]
The docs state the following

> If the pod is installed with the :path option this command will not be executed.

My development pod is added to my main project as a submodule and the main project contains a line in the Podfile: `pod 'MyPod', :path => 'MyPod'`. I have a prerequisite that my resource bundle be built before the actual `pod install` so that it can be linked in via `s.resource_bundles`.

I have seen the following behaviour, which confuses me:
- When I run `pod install` on my local machine, the `prepare_command` is exectuted, and all is well. This behaviour however is not in line with the docs (but it is what I want).
- When I build the project on Bamboo, the `prepare_command` is not executed, and my ipa file ends up incorrect, as the resource bundle is never linked. This behaviour appears to be in line with the docs.
- If I change the Podfile to read: `pod 'MyPod', :git => 'git@github.com:wilmarvh/MyPod.git', :branch => 'develop'`, and I build via Bamboo, the `prepare_command` is executed and my ipa file is complete. This behaviour appears to be in line with the docs as well. However it is not possible to develop like this, as this requires me to always tinker with the consuming project's Podfile depending on where I want to build.

To be clear, I am building the main/consuming project in each instance.

_My issue is this_
I require the resource bundle to be built ALWAYS, regardless of how the pod is specified. Previously this worked great with the pre-install hook. Is there someway I can force the `prepare_command` to always execute? Is there another way to achieve what previously worked great on 0.32 and earlier?

Thanks

<3 Cocoapods

**Comment by haemi** [comment]
I do have the same request; I need some script running after `pod install`, but I do not want to move that responsibility to the client... what do you mean by

```
I recommend to encapsulate the prepare command in a dedicated file and invoke
that from the podspec. In this way adding a build phase is trivial with the local option
and doesn't lead to surprises.
```

how can I invoke a dedicated file from the podspec?

**Comment by kunalbalani** [comment]
I would +1 for this feature

**Comment by leavesster** [comment]
It seems the `prepare_command` executed when I use :path now. 
But it only executed at the first time I run `pod install`, if the podspec not change any more, the next time I run `pod install` the `prepare_command` won't executed. That why I search and find this issue. If any one explain this, please tell me, Thank you. I guess for this behavior is cocoapods track the podspec. But I did not find any document explain this.

After read this issue and [documentsp about prepare_command](https://guides.cocoapods.org/syntax/podspec.html#prepare_command). 
I not sure it is a bug or now cocoapods enable `prepare_command` with `:path` in 1.3.1(my pod version).

**Comment by cooler333** [comment]
I'm using prepare_command to add R.generated.swift file to development(local) pod for using R.swift in it. 
  
```ruby
Pod::Spec.new do |s|

    # ...

    generated_file_path = "Settings/Sources/R.generated.swift"
    s.prepare_command = 
    <<-CMD
        touch #{generated_file_path}
    CMD

    # ...

end
```

Is it bug or feature what prepare_command executed when I use :path?

same command but in pre_install looks weird:

```ruby
pre_install do |installer|
    installer.pod_targets.flat_map do |pod_target|
        if pod_target.pod_target_srcroot.include? 'LocalPods'
            pod_target_srcroot = pod_target.pod_target_srcroot
            pod_target_path = pod_target_srcroot.sub('${PODS_ROOT}/..', '.')
            pod_target_sources_path = pod_target_path + '/' + pod_target.name + '/Sources'
            generated_file_path = pod_target_sources_path + '/R.generated.swift'
            File.new(generated_file_path, 'w')
        end
    end
end
```
