### ISSUE TITLE
Unable to `pod trunk push`: "The podspec does not validate."

### ISSUE THREAD

**Issue by pkamb** [CocoaPods/CocoaPods#2193]
Attempting to use the new Trunk service.

> Claiming an existing library: If you want to claim a library that someone has already claimed, then you can use our Claims form to say that you are the maintainer / owner of a collection of libraries. Any issues regarding ownership of libraries will be arbitrated by the CocoaPods dev team. [(link)](http://guides.cocoapods.org/making/getting-setup-with-trunk.html)

I have claimed the Apptentive pod, although I cannot seem to find any confirmation email of this.

I'm now following this guide:
http://guides.cocoapods.org/making/getting-setup-with-trunk.html

I registered with `pod trunk register`, then clicked the link in the email. 

Then, `$ pod trunk push apptentive-ios.podspec --verbose`

> Installing apptentive-ios (1.5.0)
> GitHub download
> Creating cache git repo (/Users/user/Library/Caches/CocoaPods/GitHub/23bd039bd23e96f3fb3ce08ce468fd7c5a502d6e)
> Cloning to Pods folder
> 
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.

`[!] The podspec does not validate.`

This is the same podspec I have been using for many releases via Pull Request, so I don't think it's actually invalid? The error log should be modified if so.

> This means that you do not have to change any existing podspecs. [(link)](http://blog.cocoapods.org/CocoaPods-Trunk/)

Seems to suggest I don't need to modify the podspec.

Am I not registered as the owner of the pod? What other issue could be causing this?

**Comment by LiuPN** [comment]
localhost:PNTitleScroll lpn$ pod trunk push

[!] Found podspec `PNTitleScroll.podspec`
Updating spec repo `master`

CocoaPods 1.0.0.beta.6 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Validating podspec
[!] The podspec does not validate.

**Comment by LiuPN** [comment]
localhost:PNTitleScroll lpn$ pod spec lint PNTitleScroll.podspec

[!] Unable to load a specification for the plugin `/Users/lpn/.rvm/gems/ruby-2.2.1/gems/cocoapods-deintegrate-1.0.0.beta.1`
[!] The spec did not pass validation, due to 1 error.

**Comment by orta** [comment]
This is a different problem, however, it can probably be fixed by removing `cocoapods-deintegrate-1.0.0.beta.1` using - `gem uninstall cocoapods-deintegrate-1.0.0.beta.1`
