### ISSUE TITLE
`pod spec lint` not validating `-Wno-*` compiler flags

### ISSUE THREAD

**Issue by mxcl** [CocoaPods/CocoaPods#2210]
Referring to [this Twitter conversation](https://twitter.com/mxcl/status/472442039955509248) and this screenshot:

![screen shot 2014-05-30 at 1 18 40 pm](https://cloud.githubusercontent.com/assets/58962/3135300/26322114-e831-11e3-91f2-ed2087098846.png)

In this case not preventing the warning would result in ~400 warnings for the end user. My choices were using the warning or putting every method in YOLOKit into a separate category, which was doable, but would make adding new methods in the future tedious, and something I wanted to avoid. The warning in this case was irrelevant for the library itself, and I only wanted the warning to apply when compiling YOLOKit itself, not outside of it.

In the end I worked around it with a [clang pragma](https://github.com/mxcl/YOLOKit/blob/master/YOLO.ph) which I then include from every `.m`.

IMO as long as the warning flags don't propagate to the main project, CocoaPods could make this acceptable but maybe continue to refuse `-w`.

The specific flag here is `-Wno-incomplete-implementation` and I applied it as I have a single category (YOLO) for the library, but I split all the implementations across many files in order to make every method its own module. Clang would then warn in every file that the implementations were not complete, but they were, just not in the compilation unit.

**Comment by NSExceptional** [comment]
That's an interesting conclusion to come to. Shouldn't it be up to the author, whose warnings flags will end up being used to compile their source anyway?
