### ISSUE TITLE
Add inihibit_warnings to Podspec dependencies like in Podfile

### ISSUE THREAD

**Issue by kevindudley** [CocoaPods/CocoaPods#2231]
Can this be added? In a private Pod I'd like to remove warnings for 3rd party pods (because there's nothing I can do about them)....this was previously possible using the post_install hook...but of course it has gone ....e.g.

```
spec.post_install do |installer|
    installer.project.targets.each do |target|
      if !target.name.start_with?('Pods-FLO')
        target.build_configurations.each do |config|
          puts config
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        end
      end
    end
  end
```

**Comment by jpmcglone** [comment]
The overrides don't seem to work for me. I get warnings, and it basically undoes the inhibit_warnings :/

**Comment by xilin** [comment]
@jpmcglone So do I. The override cannot work now.
