### ISSUE TITLE
Development Pods should include *.podspec and README.*

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#2260]
I've been spending time with people creating a new Pod. 

When asked where people think they would find the Podspec for the a project to be after a `pod lib create` there is an expectation that it would be inside the `Development Pods` section in Xcode. 

After reflecting on that for a while I think it makes sense to have all development pods show their Podspecs as that's something that its an integral to editing the library itself. I'm also of the opinion that if we can find a READMEs or CHANGLOGs we should add those too, those are an important part of making a change to a library and we should do what we can to not make it necessary to leave Xcode to do those changes.

**Comment by neonichu** [comment]
A "Podspec Metadata" group is part of `pod lib create` for a while now, so let's close this.
