### ISSUE TITLE
Current resource bundle target setup doesn't play well with image assets containing universal images

### ISSUE THREAD

**Issue by nikolaykasyanov** [CocoaPods/CocoaPods#2292]
I have an asset catalog with universal image set (I'm using different images for iPhone and iPad) included in pod resource bundle like this:

```ruby
s.resource_bundle = {'LibName' => ['LibName/Media.xcassets']}
```

And here's the problem: build setting "Targeted Device Family" of LibName resource bundle target is set to `iPhone`, so I got no iPad images in resulting `LibName.bundle`.

I think that target device family should be inferred from the application target device family or user should be able to specify target device family in podfile so podspecs could inherit this setting.

**Comment by onekiloparsec** [comment]
Hi. Not sure what's the status of this, but the problem still exists.I am using 0.36.0 right now, and I have libraries with resources bundles containing not images but xibs. Once the Pods project is integrated into the client project, the "Target Device Family" setting of the Pods root project is blank (i.e. not iPhone, not iPad, and not iPhone/iPad). Upon building, resources get created for iPhone only. Selecting "iPhone/iPad" in the build setting of the Pods project fixes the problem, at least manually. But it has to be done every time we update the pods of the project. A thing that occurs many times when you are using the pods your are currently developing for an app. If I could provide help, I would be happy to do so.

**Comment by levigroker** [comment]
This is also happening for me with a storyboard. I'm using Xcode 6.3.1 targeting iOS 7.0 and up. My pod has a storyboard in it which recently does not show up for the iPad (but did previous to 6.3 and 8.3).

**Comment by levigroker** [comment]
Well, a workaround is to manually specify the desired Targeted Device Families in the `post_install` hook:

	post_install do |installer_representation|
	  # Directly set the Targeted Device Family
	  # See https://github.com/CocoaPods/CocoaPods/issues/2292
	  installer_representation.project.build_configurations.each do |config|
		config.build_settings['TARGETED_DEVICE_FAMILY'] = '1,2'
	  end
	end

See Apple's [XcodeBuildSettingRef](https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html) for specifics about `TARGETED_DEVICE_FAMILY`.

Essentially:
> 1: iPhone/iPod touch.
> 2: iPad.

It would be preferable for CocoaPods to inherit the targeted device family of the hosting Project's Targets, if possible.

Levi

**Comment by knox** [comment]
Based on levi's idea i am using the following `post_install` hook

    post_install do |installer|
      installer.project.targets.each do |target|
        next unless target.product_type == 'com.apple.product-type.bundle'
        target.build_configurations.each do |config|
          #config.build_settings['TARGETED_DEVICE_FAMILY'] = '1,2' # iPhone, iPad
          config.build_settings['TARGETED_DEVICE_FAMILY'] = '2'
        end
      end
    end

**Comment by brion** [comment]
Note that the above fails on 0.38 beta -- must use installer.pods_project instead of installer.project.

This works for me, but is a bit verbose:

```
post_install do |installer|
  if installer.respond_to?(:project)
    project = installer.project
  else
    project = installer.pods_project
  end
  project.targets.each do |target|
    if target.product_reference.name == 'OGVKitResources.bundle' then
      target.build_configurations.each do |config|
        config.build_settings['TARGETED_DEVICE_FAMILY'] = '1,2' # iPhone, iPad
      end
    end
  end
end
```

**Comment by Grubas7** [comment]
@brion Thanks a lot! You changes helps if somebody wants backward compatibility.

**Comment by levigroker** [comment]
@brion Thanks for the update. Seems to work well with Cocoapods 0.38.2. Cheers.

For the record, my updated post_install hook looks like this:

	post_install do |installer_representation|

	  # Grab the `project` object from the installer (cocoapods < 0.38 use `project`, cocoapods >= 0.38 use pods_project)
	  # See https://github.com/CocoaPods/CocoaPods/issues/2292
	  if installer_representation.respond_to?(:project)
		project = installer_representation.project
	  else
		project = installer_representation.pods_project
	  end

	  # Directly set the Targeted Device Family
	  # See https://github.com/CocoaPods/CocoaPods/issues/2292
	  project.build_configurations.each do |config|
		config.build_settings['TARGETED_DEVICE_FAMILY'] = '1,2'
	  end

	end

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by brion** [comment]
This appears to be resolved for me in the use_frameworks era.
