### ISSUE TITLE
"Build Active Architecture Only" setting not propagated for all configurations

### ISSUE THREAD

**Issue by rsanchezsaez** [CocoaPods/CocoaPods#2304]
I have an Xcode project with 4 configurations: _Debug_, _Debug-Special_, _Release_ and _Ad-Hoc_.

In my project _Debug_, _Debug-Special_ set `Build Active Architecture Only` to `Yes`and the rest to `No`.

However, when these 4 configurations are recreated on the _Pods_ project only _Debug_ is set to `No. _Debug-Special_ should be set to NO as well, but CocoaPods it's missing it.

I tried deleting `Pods.xcodeproj` and regenerating it with `pod install` to no avail.

**Comment by Dimon70007** [comment]
I have found another alternative for project with many configurations - using [postinstall hook in Podfile ](https://gist.github.com/Dimon70007/ecf9eaf8d0d0ae380512d94cf800c492)
No more needed specifying every configuration in Podfile after adding, all you need is only name your new debug configurations like `<anything>.Debug`
