### ISSUE TITLE
Command to convert JSON podspec to Ruby format

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#2313]
I noticed there's currently no command to revert a .podspec.json to a regular .podspec. I had a need for this command today when including a custom podspec in a forked repo.

**Comment by lvyile** [comment]
$ pod ipc spec --help

Very useful to me, thx :+1:

**Comment by orkenstein** [comment]
So how to use after all `podspec.json` with forked repo?

**Comment by wade0317** [comment]
I want convert json fomat to podspec file too. Is there any solutions ?

**Comment by bangnguyensea** [comment]
Oh, it's old issue, may I need to manually edit the podspec file :(

**Comment by karosLi** [comment]
I totally need this function...

**Comment by thongk** [comment]
I need podspec.json to podspec too...

**Comment by ProMonkeyZ** [comment]
> I want convert json fomat to podspec file too. Is there any solutions ?

i also want to convert json fomat to podspec , did you solve that ？

**Comment by thongk** [comment]
> > I want convert json fomat to podspec file too. Is there any solutions ?
> 
> i also want to convert json fomat to podspec , did you solve that ？

Finally I found we dont need .podspec anyway,when use .podspec, just instead with .podspec.json

**Comment by joquerod** [comment]
We use JFROG artifactory, which is an enterprise tool to host all our artifacts: gems, pods.
Thet don't support json podspecs, only ruby podspecs, and converting each spec is time consuming. Is there any plan to write this tool?

**Comment by dnkoutso** [comment]
@joquerod no current plans and the issue is closed. A PR would be welcome.

**Comment by wangpeiyan** [comment]
i need convert .json to podspec too!!!!

**Comment by KCknows** [comment]
Jasoncoray.vq@gmail.com

**Comment by kambala-decapitator** [comment]
wow, nobody has managed to hack a script for that up until now?

in the contemporary AI world the following prompt has worked well for me:

> Cocoapods can produce JSON out of a podspec. I need the other way around: I have a JSON file and want to get podspec file from it. Could you do it? Here's the JSON:
