### ISSUE TITLE
Podspec :submodules flag is ignored when pod is included with :git option

### ISSUE THREAD

**Issue by bengotow** [CocoaPods/CocoaPods#2317]
Hi there,

I'm working on a cocoapod that uses the :submodules flag. Here's the `source` declaration in the podspec:
```
  s.source       = { :git => "https://github.com/inboxapp/inbox-ios.git", :tag => s.version, :submodules => true }
```

When the published pod is included in a `Podfile`, everything works fine. The submodules are checked out and the pod compiles as expected.

```
target "Test" do
	pod "InboxSDK"
end
```

However, when people use the `:git` option in their podfile to reference our repository directly, submodules are not loaded and the pod does not compile. (Up until very recently, this was the only way to use our pod, since it is still under development.)

```
target "Test" do
	pod "InboxSDK", :git => 'https://github.com/inboxapp/inbox-ios.git'
end
```

This ticket (https://github.com/CocoaPods/CocoaPods/issues/2233) indicates that you can add the `:submodules => true` option to the Podfile to fix this problem. I understand that these options are entirely replacing the `source` declared in the podspec, removing any attributes that are not overridden. 

It would be helpful if this behavior was documented, since it's not obvious that overriding the `source.git` attribute of the Podspec will blow away the other attributes including `source.submodules`. I think it would also be better to copy the `source` hash from the Podspec and override only the values that are declared in the podfile. (So for example, if I fork inbox-ios, and my fork doesn't use submodules, I'd have to manually set :submodules => false in my podspec or it would inherit the default behavior from the podspec.)

**Comment by segiddins** [comment]
I think inheritance is a bad idea. @kylef let's close this?

**Comment by kylef** [comment]
:+1:
