### ISSUE TITLE
Linking is broken for static library (since Xcode6 beta4)

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#2319]
I know it's beta but something has changed since beta3.

I have project with static library and it build successfully. But then I link produced library to my tests (but it's not test only issue) and Xcode complain about missing references from dependency.

![screen shot 2014-07-21 at 23 31 11](https://cloud.githubusercontent.com/assets/758033/3650670/5c3a7c46-111e-11e4-99c3-58697bfdc286.png)

my setup is

MyLibrary <- link with libPods-MyLibrary.a
MyLibraryTests <- link with libMyLibrary.a

When I open the very same project with Xcode 5.1.1 everything is fine. I'm not sure if this is solely Xcode issue or it can be fixed with Cococapods, this is why I put this my obser

**Comment by madhaviw** [comment]
I set OTHER_LIBTOOLFLAGS to $(OTHER_LDFLAGS). pod install works fine. However xcodebuild fails to compile and gives a libtool error . I am on Xcode 7 . The error is as below:

Libtool /Users/madhaviw/Library/Developer/Xcode/DerivedData/MyApp-anrbtontsrplqhbqkaakszopovqr/Build/Intermediates/Pods.build/Release-iphoneos/Pods-PreparePods-A.build/Objects-normal/arm64/libPods-PreparePods-A.a normal arm64
	Libtool /Users/madhaviw/Library/Developer/Xcode/DerivedData/MyApp-anrbtontsrplqhbqkaakszopovqr/Build/Intermediates/Pods.build/Release-iphoneos/Pods-PreparePods-A.build/Objects-normal/armv7/libPods-PreparePods-A.a normal armv7
(2 failures)

This is the xcodebuild command on which it fails 
xcodebuild -workspace MyApp.xcworkspace -scheme Pods-PreparePods ONLY_ACTIVE_ARCH=NO -configuration Release -sdk iphoneos

Can you please help?

**Comment by madhaviw** [comment]
Nvm .. fixed the issue

**Comment by ostapkuzyk** [comment]
@madhaviw how did you managed to fix it? Have the similar one

**Comment by madhaviw** [comment]
Yes, I updated xctool to its latest version and it resolved.

**Comment by ostapkuzyk** [comment]
@madhaviw thx. just fixed it
