### ISSUE TITLE
Allow prepare_command when Pod installed with :path

### ISSUE THREAD

**Issue by jhersh** [CocoaPods/CocoaPods#2325]
The [prepare_command documentation](http://guides.cocoapods.org/syntax/podspec.html#prepare_command) includes this note:

> If the pod is installed with the :path option this command will not be executed.

I'd like to propose that this restriction be removed. I have an internal development pod, installed with `:path`, that includes an asset catalog. When the pod is installed, I would like to run a bash script (in this case, the excellent [objc-codegenutils](https://github.com/square/objc-codegenutils)) to generate an asset catalog class.

In the meantime, I'm working around this with a `post_install` script in the `Podfile`.

**Comment by segiddins** [comment]
I'm going to close this, since I kinda prefer the current behavior.

**Comment by antoinelamy** [comment]
@segiddins please reopen this issue, there are many use cases where this could be super helpful. It doesn't make any sense to duplicate the pod setup logic in the Podfile. Making this behaviour opt-in via an argument could make sense.
