### ISSUE TITLE
pod lib create: why am I forced to enter class prefix?

### ISSUE THREAD

**Issue by ivanzoid** [CocoaPods/CocoaPods#2339]
If my pod consists only from category(-es) for existing classes, I have no class prefix.

**Comment by anas10** [comment]
@orta as @ndmeiri says Xcode 6 no longer asks for a class prefix. 
Any update on that? 
Do we need to open a new issue ?

Thanks

**Comment by orta** [comment]
yeah, it's happening probably, think for ObjC it still makes sense for a library to have a prefix, will probably say that you can leave it blank for no prefix

**Comment by malhal** [comment]
When using 'pod lib create' the class prefix is referring to the example project rather than the lib, so just enter 'My' to get passed that question. Then you end up with MyAppDelegate and MyViewController which is perfect for a simple example project.
