### ISSUE TITLE
Homepage is not reachable in case of private pods?

### ISSUE THREAD

**Issue by kidsid49** [CocoaPods/CocoaPods#2351]
While testing the syntax of podfile by using this commands. 

```
$ pod --no-clean lib lint
```

It didn't passed the validation.
Gives the error like this-

```
-> sample-ios-pod (0.1.0)
- WARN  | The URL (https://github.com/MY_COMPANY_NAME/sample-ios-pod) is not reachable.

Pods project available at `/private/tmp/CocoaPods/Lint/Pods/Pods.xcodeproj` for inspection. 
[!] sample-eye-ios-pod did not pass validation.
```

The above github url is one of my private repository.
Anybody know how to resolve that issue?

in-fact i went through http://guides.cocoapods.org/making/private-cocoapods.html
But didn't get anything :-(

**Comment by SRAO011** [comment]
pod lib lint --private
 
 Lint skips checks that apply only to public specs
