### ISSUE TITLE
Feature request: git-subtree interoperability

### ISSUE THREAD

**Issue by kamitchell** [CocoaPods/CocoaPods#2357]
Possibly related to #2120. Bear with me, as I'm actually using CocoaPods to tinker with a project for the first time.

Various workflows and business requirements require *all* of the source code to be in the project repo, even if that source code came from a third party. Sometimes, the next step after ``git clone`` (or some other VCS checkout command) must be building the project.

Consider:

* Not all the developers may have internet access all the time. Keeping correct versions of third party sources with certain branches is a big win here.
* Customer requires a complete, buildable product to be pushed regularly to their repository.

git-subtree is pretty elegant in the sense that developers can patch things that are causing problems, write a good message describing the changes, and get on with the rest of development. The changes to the third-party code are strongly coupled to the development of the main product.

Those commits can then be extracted into a fork of the third-party repo and offered back to their original projects. The people doing the extraction don't necessarily have to be the ones making the patches. For us, it was a big win over git submodules, which caused a lot of confusion.

But what git-subtree lacks in the default fork is a good way of specifying the metadata that shows where trees come from, and it certainly doesn't cover the dependency angle. I think this is where a fusion of using subtrees and using CocoaPods would be a big win for me.

Let me say what I think would make it work, presuming maybe an option in the ``Podspec`` that says to use subtrees.

1. When CocoaPods discovers that it needs to add a non existing pod, I assume it resolves to a git repo URL and a ref spec (usually a tag) for the version. Instead of its normal method of getting the repo data, in subtree mode, it would issue something like ``git subtree add --squash --prefix=Pods/<podname> <repo> <refspec>``, and then continue with its normal processing.
2. Similarly, when discovering an update was needed, CocoaPods could issue a ``git subtree pull --squash --prefix=Pods/<podname> <repo> <refspec>``.
3. Might be nice to have a utility command to push local patches to a desired repo. Maybe something like ``pod subtree push <pod> <repo> <branch>`` would do a ``git subtree push --prefix=Pods/<podname> <repo> <branch>``. Mostly a convenience.

The ``--squash`` reduces the incoming code from the remote repo to one commit; leaving it off will result in all the history of the pod being in the current project. Could that be a per-pod option? It's something we do for some projects and leave off for others. And sometimes we do it for the initial add, but track the changes when we do a pull.

I know this is a pie-in-the-sky thing, and I wish I had the time or the Ruby skills to code something for you. But it'd remove probably the biggest barrier to using CocoaPods in the development situations I find myself.

If somebody skilled can point the way, perhaps I can tinker with it.

**Comment by aednichols** [comment]
This would be a fantastic enhancement. My current project uses a number of private pods that we're always iterating upon; this introduces some friction because we're effectively using a dependency manager for version control (i.e. constantly bumping version numbers to keep everything in sync).

**Comment by segiddins** [comment]
I think, unfortunately, that we're going to have to close this issue. We'd welcome a well-tested PR implementing this feature, but given how long the issue has been open for, I don't see it being productive to keep it open without any progress being made.
