### ISSUE TITLE
Unable to run command 'StripStoryboard Storyboard.storyboardc' - this target might include its own product.

### ISSUE THREAD

**Issue by JosephDuffy** [CocoaPods/CocoaPods#2372]
Hi everyone

I'm trying to add a Swift Framework to a Swift project using CocoaPods and getting an error whenever I try and build (in fact, as soon as I open Xcode with the newly created workspace):

`Unable to run command 'StripStoryboard Storyboard.storyboardc' - this target might include its own product.`

The contents of my Podfile is:

``` ruby
pod 'AuthenticationManager', :git => 'https://github.com/YetiiNet/AuthenticationManager.git'
```

and I'm running `pod install`

I am unable to clean the project (`Clean Failed`) and the error is showing on the `Pods-AuthenticationManager` target.

Xcode version: 6-Beta5 (latest as of post)
Pods version: 0.33.1
OS X Version: 10.9.4

**Comment by idokleinman** [comment]
I am getting this error in an Obj-C project
can't find any references to that nowhere else

**Comment by aspyct** [comment]
I'm getting the same error in an Obj-C project, with a storyboard that was previously completely fine. I changed the storyboard, but I can't find exactly what makes it fail now.

Will keep you posted. In the meantime, I'd love to hear any thoughts about this.

**Comment by aspyct** [comment]
Ok, found it.

Turns out I mistakenly included the storyboard in the `s.source_files`. Xcode was trying to compile it and it failed. Excluded it, and problem solved :)
