### ISSUE TITLE
Merge back cocoapods-core

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#2378]
The cocoapods-core was extracted because the native extension of Xcodeproj rendered difficult the usage of CocoaPods in servers (which usually are not running OS X).

#### Advantages:

- 1 single repository for strictly related code (no more sister pull request among the two repositories)
- Patches are easier to develop in isolation

#### Disadvantages

- History loss
- Work to be done

--

This discussion was extracted from https://github.com/CocoaPods/CocoaPods/pull/2373#issuecomment-51755151

**Comment by segiddins** [comment]
I think we can close this out -- I personally don't mind having two separate repos, and the rate of change on Core is low enough that I'm happy to keep it under higher scrutiny.
