### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#2379]
- [x] Create a `NOMENCLATURE.md` file on the root of the repo to document CocoaPods’ nomenclature.
- [ ] Changes references in the codebase from `aggregate_target` to `umbrella_target`
## 
#### Living NOMENCLATURE.md draft
- `Pod target`: the target of a single Pod.
- `Umbrella target`: the target generated to aide the integration of the Pod targets with the user targets.
- `User target`:  the target being integrated
- `Existing Xcode Project`: a subproject used directly to build a spec.
- `Native target`: the `PBXNativeTarget` Xcode / Xcodeproj build artifact, which could be an application, a framework, or a static library, or any other target type supported by Xcode.

**Comment by robcontreras** [comment]
@fabiopelosin  @kylef wanted to help out a little and would like your feedback on this to know if that's more or less the direction i should keep [nomneclature.md](https://github.com/robcontreras/CocoaPods/blob/feature/2379-add-glossary-of-terms/NOMENCLATURE.md)

**Comment by orta** [comment]
It's a good start: remember "Xcode" and "CocoaPods"

**Comment by robcontreras** [comment]
Here's a link to the [PR](https://github.com/CocoaPods/CocoaPods/pull/6559)
