### ISSUE TITLE
Inflect localisations used in user’s project and remove pod localisations that aren’t needed.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#2381]
Is this in any way doable? The reason is that this the one concrete example I know of for which the Podfile `pre_install` hook is needed (and it would be great if we can kill that hook at some point).

I.e. if a pod brings in Antartican, chances are that the user’s app doesn’t actually support that locale, but because of the pod the App Store will now list the app as supporting Antartican.

**Comment by netbe** [comment]
I have just found out about this key in Info.plist CFBundleAllowMixedLocalizations

    CFBundleAllowMixedLocalizations (Boolean - iOS, OS X) specifies whether the bundle supports the
    retrieval of localized strings from frameworks. This key is used primarily by Foundation tools that link to
    other system frameworks and want to retrieve localized resources from those frameworks.

Cocoapods could use this key to not process pod's resources localized not supported by the application.

**Comment by dtorres** [comment]
I have implemented this as a post_install plugin. Only works with localized resources directly in the Pod Resources. Needs a bit more work to work with bundles. 

I'll update this comment with the repo.

**Comment by dtorres** [comment]
Project with working plugin: https://github.com/dtorres/cocoapods-prune-localizations
Usage:
```plugin 'cocoapods-prune-localizations', {:localizations => ["en.lproj", "es.lproj"]}```

**Comment by dtorres** [comment]
I have just published the plugin.
The plugin now supports bare lproj's in a Pod resources as well as traversing .bundle's.

I feel the implementation is a bit fragile because it makes a lot of assumptions on how Cocoapods works today.

The ways to do this safer I can think of are:
- Enable a pre_install hook for plugins
- Integrate this directly into Cocoapods.

I'm willing to do the work for any option, let me know what you think.

**Comment by orta** [comment]
There is, as of 0.38, a pre-install hook for plugins.

**Comment by dtorres** [comment]
Great, I will update the plugin to use pre_install in 0.38 and later.

**Comment by segiddins** [comment]
@dtorres I think for us to consider making it a default plugin, it would need to be tested.

**Comment by dtorres** [comment]
@segiddins And I wouldn't have it other way. I do apologize for not updating the plugin as promised but moving to another continent is quite a project. And again, yes! I will add tests when I update it.

**Comment by segiddins** [comment]
No worries! Once it's tested, ping us here and we'll look into making it a default plugin! :rocket:
