### ISSUE TITLE
ArgumentError - invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by jollychang** [CocoaPods/CocoaPods#2385]
I got the issue too, I have search github issues and  set LC_ALL to "en_US.UTF-8" and podfile is utf-8 encoding.

```
[jollychang@WilliamMBP Frodo-iOS]$ head -n 10 ~/.bashrc
set -o emacs
export LANG=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_ALL=en_US.UTF-8
PAGER='less -X -M'
```

```
[jollychang@WilliamMBP Frodo-iOS]$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

```
[jollychang@WilliamMBP Frodo-iOS]$ pod install
Analyzing dependencies
Pre-downloading: `MQTTKit` from `https://github.com/jmesnil/MQTTKit.git`, commit `5ee5cf3819`
Downloading dependencies
Installing AFNetworking (1.3.3)
Installing ActionSheetPicker (0.0.2)
Installing AmonsulIOS (1.5.2)
Installing DOUFoundation (0.2.1)
Installing DOURegisterKit (1.2.1)
Installing DOUSNSSharing (2.3.6)
Installing DOUUserManager (1.0.1)
Installing DoubanObjCClient (1.3.1)
Installing DoubanObjCFileManager (1.0.6)
Installing FXBlurView (1.6.2)
Installing JSQSystemSoundPlayer (1.5.2)
Installing MQTTKit (0.1.0)
Installing PSTCollectionView (1.2.1)
Installing SDWebImage (3.5.2)
Installing SORelativeDateTransformer (1.1.10)
Installing SVProgressHUD (1.0)
Installing UIImage+BlurredFrame (0.0.4)
Installing Weibo (2.4.2)
Installing YAUIKit (1.1.6)

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```

   CocoaPods : 0.33.1
        Ruby : ruby 1.9.3p374 (2013-01-15 revision 38858) [x86_64-darwin12.2.0]
    RubyGems : 2.2.1
        Host : Mac OS X 10.9.4 (13E28)
       Xcode : 5.0 (5A1412)
Ruby lib dir : /usr/local/Cellar/ruby/1.9.3-p374/lib
Repositories : douban - http://code.dapps.douban.com/CocoaPodsSpecs.git @ c228aba175cc1acb127bf395a9a143597a5f41b5
               master - http://code.dapps.douban.com/mirror/Specs.git @ f3853e624817e37f30108cd91de947d0e87fe7b1

``````

### Podfile

```ruby
platform :ios, '7.0'

pod 'AmonsulIOS',                '~> 1.5.1'
pod 'DOUUserManager',            '~> 1.0.0'
pod 'DoubanObjCClient',          '~> 1.3.1'
pod 'DoubanObjCFileManager',     '~> 1.0.0'
pod 'YAUIKit',                   '~> 1.1.6'
pod 'SVProgressHUD',             '~> 1.0'
pod 'SDWebImage',                '3.5.2'
pod 'FXBlurView',                '~> 1.6.1'
pod 'SORelativeDateTransformer', '~> 1.1.10'
pod 'PSTCollectionView',         '~> 1.2.0'
pod 'DOUSNSSharing',             '~> 2.3.6'
pod 'DOURegisterKit',            '~> 1.2.1'
pod 'ActionSheetPicker',         '~> 0.0.2'
pod 'Weibo',                     '~> 2.4.2'
pod 'UIImage+BlurredFrame'
pod 'JSQSystemSoundPlayer'
pod 'MQTTKit', :git => 'https://github.com/jmesnil/MQTTKit.git', :commit => '5ee5cf3819'
``````
### Error

```
ArgumentError - invalid byte sequence in US-ASCII
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:106:in `fnmatch'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:106:in `block (3 levels) in relative_glob'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:105:in `each'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:105:in `any?'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:105:in `block (2 levels) in relative_glob'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:104:in `select'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:104:in `block in relative_glob'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:97:in `map'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:97:in `relative_glob'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/path_list.rb:70:in `glob'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/sandbox/file_accessor.rb:154:in `readme'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:280:in `map'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:280:in `used_files'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:255:in `clean_paths'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:157:in `clean_installation'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer/pod_source_installer.rb:82:in `clean!'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:287:in `block in clean_pod_sources'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:286:in `each'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:286:in `clean_pod_sources'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:109:in `block in download_dependencies'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/user_interface.rb:52:in `section'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:105:in `download_dependencies'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/installer.rb:90:in `install!'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:40:in `run_install_with_update'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/command/project.rb:70:in `run'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/claide-0.6.1/lib/claide/command.rb:281:in `run'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/lib/cocoapods/command.rb:48:in `run'
/usr/local/Cellar/ruby/1.9.3-p374/lib/ruby/gems/1.9.1/gems/cocoapods-0.33.1/bin/pod:33:in `<top (required)>'
/usr/local/Cellar/ruby/1.9.3-p374/bin/pod:23:in `load'
/usr/local/Cellar/ruby/1.9.3-p374/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing github issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+US-ASCII&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Don't forget to anonymize any private data!

```
```

**Comment by balasubramanian1612s** [comment]
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `cloud_firestore_web` from `.symlinks/plugins/cloud_firestore_web/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_auth_web` from `.symlinks/plugins/firebase_auth_web/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_core_web` from `.symlinks/plugins/firebase_core_web/ios`
    -> Fetching podspec for `firebase_storage` from `.symlinks/plugins/firebase_storage/ios`
    -> Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
    -> Fetching podspec for `flutter_plugin_android_lifecycle` from `.symlinks/plugins/flutter_plugin_android_lifecycle/ios`
    -> Fetching podspec for `flutter_razorpay_sdk` from `.symlinks/plugins/flutter_razorpay_sdk/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
        
-> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `google_sign_in_web` from `.symlinks/plugins/google_sign_in_web/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    
-> Fetching podspec for `razorpay_flutter` from `.symlinks/plugins/razorpay_flutter/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "razorpay_flutter":
      In Podfile:
        razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)
    Specs satisfying the `razorpay_flutter (from `.symlinks/plugins/razorpay_flutter/ios`)` dependency were found, but they required a higher minimum deployment target.
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'

/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'

**Comment by balasubramanian1612s** [comment]
I am getting this error, could anyone please help me, i tried updating pod, cleaning flutter, removing pod files..

**Comment by gsnsg** [comment]
Hi, I am also facing the same error when installing the pods and my ruby version is <b>2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]</b>
