### ISSUE TITLE
pod from a git repository with a branch is not working 

### ISSUE THREAD

**Issue by rvi** [CocoaPods/CocoaPods#2386]
I forked [CBZSplashView](https://github.com/rvirin/CBZSplashView) and I'd like to use it in my own project.

To be sure that the problem doesn't come from me, I create a Xcode project from scratch.

My project Podfile  contains one  line :

`pod 'CBZSplashView', :git=> 'git@github.com:rvirin/CBZSplashView.git',  :branch => 'remy'`

When I run `pod install` or `pod update`I've got the original version of the pod. Not my fork.

What I'm doing wrong ? 

The `:git` command [overrides the source of the podspec.](https://github.com/CocoaPods/CocoaPods/issues/2317#issuecomment-51718011)

I tried to modify the podspec to indicate that the sources files are now on my repository, but didn't work too.

``` bash
pod --version
0.33.1
```

**Comment by eneko** [comment]
Having a very similar issue, pulling from a private Github repo, I have specified the branch but the code comes from "master" only.

Using cocoapods 0.36
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'HDK', :git => 'git@github.com:xxxx/xxxx.git', :branch => 'develop'
```

**Comment by segiddins** [comment]
@eneko please open a new issue, with verbose output and steps to reproduce.

**Comment by bennettl** [comment]
Any fixes on this?

**Comment by orta** [comment]
There is a CocoaPods download cache you can try clear, `pod cache clean`

**Comment by aryaxt** [comment]
any update on this? having the same issue?

**Comment by dimohamdy** [comment]
@aryaxt  use  `pod cache clean` then `pod install`

**Comment by dimohamdy** [comment]
@orta  not work

**Comment by DanToml** [comment]
@aryaxt Please file a new issue with steps to reproduce.

**Comment by dimohamdy** [comment]
@fabiopelosin why you close issue a lot suffer from this issue ,and i think it's critical issue because most of swift repos now try to support swift3 branch

**Comment by spiewok** [comment]
@fabiopelosin I confirm: It's NOT working! This is critical! (Swift 3)

**Comment by DanToml** [comment]
@dimohamdy @spiewok Please file a new issue with verbose output and a reproduction case.
