### ISSUE TITLE
Remove the environment header

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#2390]
Context: https://github.com/CocoaPods/CocoaPods/pull/1791

**Comment by gregcotten** [comment]
Help! What if my app needs to check the version number of a pod?

**Comment by segiddins** [comment]
Pods should be responsible for making that information available on their own.

**Comment by gregcotten** [comment]
So you would prefer a bunch of hodgepodge boilerplate code in everyone's pods rather than a streamlined, unified Major/Minor/Patch definition for each Pod?

**Comment by neonichu** [comment]
If you use frameworks integration, the version numbers are available via the standard Foundation exports, see <http://stackoverflow.com/questions/24538215/get-version-number-of-ios-universal-framework-in-client> — this enables you to not make your code depend on integration via CP.
