### ISSUE TITLE
Resource Bundle not accessbile

### ISSUE THREAD

**Issue by Aranir** [CocoaPods/CocoaPods#2408]
I am unsure why this started happening, it may be connected to the installation of the new Xcode 6 beta 6 as It started the same day I installed it.

Suddently my App with uses a private pod hasn't access to any resources anymore.

Before I was loading me resources with the podspec:

```
s.resources = ["MyFramework/Resources/**/*.{xib, png, jpeg, jpg}"]
```

As it stopped working I assumed it might have something to do with the fact that I didn't use the recomended way of using resources so I tried to accomplish the same with the following:

```
s.resource_bundles = {'Resources' => ['MyFramework/Resources/**/*.{xib, png, jpeg, jpg}']}
```

They appear to be copied as I can find them under:

`Pods\Development Pods\MyFramework\Resources`

But when I try to load them:

```
UIImage *testImage = [UIImage imageNamed:@"testImage.jpeg"];
```

the `testImage` is always nil.

I also tried to find out if there was somehow a bundle accessible so I would need to load an image from a created bundle but:

```
NSArray *bundles = [[NSBundle mainBundle] pathsForResourcesOfType:@"bundle" inDirectory:nil];
```

Revealed that no bundle was created through Cocoapods.

Is this connected to Xcode 6 (I also tried to build with Xcode 5 but got the same result) or is something incorrect with my syntax or the way I have setup my podspec?

**Comment by ExoticObjects** [comment]
This is a real issue, why no replies?

After putting the following in my podspec:

	s.resource_bundles = {
		'Resources' => ['Resources/*.png'] 
	}

like @flaviamissi and @kylef, no bundles are made. 

It doesn't get much simpler than that. The podspec works in all other ways, the *.png files are in the top level `Resources` directory - what could be wrong? Seems like a bug...

I'm using Cocoapods 0.32.1 (I can't use the latest until [this bug](https://github.com/CocoaPods/CocoaPods/issues/2559) is fixed...) Has this been solved in a later version? If this is somehow my mistake, I'd love to know that as well!

**Comment by plusmancn** [comment]
The obvious solution that wasn’t listed anywhere is using the Cocoapods generated bundle (which the folder actually doesn’t exist) as a NSBundle:
have a try.
http://blog.flaviocaetano.com/post/cocoapods-and-resource_bundles/

it worked for me!!

**Comment by wendaovswendao** [comment]
bundle please load ，cocoapod don't load resourcebundle when app start 
code: if(!bundle.isLoad) { [bundle load]}

**Comment by tilowestermann** [comment]
Same issue here.

My podspec has `s.ios.resource_bundle = { 'APNPermissionRequest' => 'Pod/Assets/**/*.png' }` and images are copied to the Pods target (Pods -> APNPermissionRequest -> Resources). However, I can't load them.

**Comment by Broich** [comment]
Here's the exact same issue. Any progress on that?

**Comment by neonichu** [comment]
There's no example reproducing the perceived problem here, so it's hard to say what it even is. Could you provide one, @Broich?

**Comment by Broich** [comment]
@neonichu Thanks for your help and sorry for my late reply. I uploaded a sample project [here](https://www.dropbox.com/s/4lmm4ipnh6uwmqz/Charleene.zip?dl=0). 

The pod includes a storyboard as a resource. I can see it's added to the Resources directory but whenever I want to instantiate a VC from that storyboard I get ```*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named``` (...)

**Comment by orta** [comment]
```
        Charleene *charleene = [[UIStoryboard storyboardWithName:@"Charleene" bundle:nil] instantiateInitialViewController];
        charleene.containingViewController = viewControllerToPresent;
        charleene.transitionMode = mode;
```

You're looking for your library in the main bundle, you want to look within the bundle for your library. It would look something like:

``` 
        NSBundle *bundle = [NSBundle bundleForClass:Charleen.class];
        Charleene *charleene = [[UIStoryboard storyboardWithName:@"Charleene" bundle:bundle] instantiateInitialViewController];

```

**Comment by Broich** [comment]
Thanks @orta - Now got it to work.

**Comment by Broich** [comment]
[Here's](https://www.dropbox.com/s/4lmm4ipnh6uwmqz/Charleene.zip?dl=0) an updated version where the Bundle is created from the class name. I had it temporarily working but for some weird reason I get crashes whenever I try to reference a storyboard from within the Bundle that is created with ```pod install```

**Comment by domingguss** [comment]
@Broich  I just found out that *spec.resource_bundle* doesn't quite pick up the resource as good as *spec.resource_bundles* (notice plural notation).

I also found out that *s.resources* also worked more reliable than *s.resource*

**Comment by carusd** [comment]
I stuck in same thing for 2 days.I check my copy pod resources script.I check my bundle.I check my podspec. Everything is fine. I'm just about to give in. 

Then something hit my mind and I go check my xib files. Turns out it was because the deployment target is higher than my project's requirement deployment target. Making the same deployment target solved the problem.

**Comment by haifengkao** [comment]
I am tired of solving resources issue of CocoaPods, so I made [PodAsset](https://github.com/haifengkao/PodAsset) to deal with the problem once and for all.

**Comment by andreacipriani** [comment]
Thank you to your suggestions I was able to load nibs from the bundle of my Pod. 
But when my Sample-app calls my Pod to show a table view and dequeue a cell previously registered with an identifier and a valid nib, I get the "'Could not load NIB in bundle error" for the TableViewCell's nib. The error logs the Bundle of my Sample-app and not the one of my Pod. 

What am I missing?

**Comment by haifengkao** [comment]
It depends on the setting for your pod. If it is loaded as a framework, you have to use `[NSBundle bundleForClass:[some class which is defined in your pod]]`.  If it is loaded as a bundle, you can use `[NSBundle mainBundle]` or `[NSBundle bundleForClass:[some class in your sample app]`. 
I am tired of this shit, so I made [PodAsset](https://github.com/haifengkao/PodAsset)

**Comment by VenuKotha** [comment]
I updated my CP from 0.39.0 to 1.0.0. i am getting  the below error
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle:
in my podspec i written
s.resources = "Resources/**/*.{png,xib,json,plist,ttf,xcassets,sqlite}".
it is working fine in 0.39.0
What i observed is after pod install the resources are adding to workspace but not included in .app file.
I struggled a lot from last three days. Any one has the solution please share

**Comment by haifengkao** [comment]
@VenuKotha In my podspec, I use resource bundles
```ruby
  s.resource_bundles = {
     'MyPod' => ['MyPod/Assets/*.*']
  }
```

**Comment by VenuKotha** [comment]
Thank you very much for your response. I am using default bundle, so i can not use this. I got the issue and resolved. The issue is in my code base the value of minimum deployment target is 7.0 for my target settings. So i changed to 8.0 then it is working fine.

**Comment by haifengkao** [comment]
@VenuKotha resource bundle works for all targets, including 7.0

**Comment by VenuKotha** [comment]
ok, but i have to change my source files wherever read from bundle if I use this attribute.  So i change to 8.0

**Comment by VenuKotha** [comment]
Hi, I got one more issue. Please help me to resolve the issue if already got it.
My project is in objective c and my private pods are written in objective-C. Now i am writing a new private pod in Swift to go in mix and Match approach. When i give pod install i am getting below error
"[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it."
But i changed all my pod files for private pods using the same. still getting same error.  I am providing my pod file for one of private pod here.
podfile:-

source 'https://github.com/xxxx/ios-specs.git'
source 'https://github.com/cocoaPods/Specs.git'
  platform :ios, ‘8.0’
 use_frameworks!

target 'XXXXFoundationFramework' do
podspec :path => 'XXXFoundationFramework.podspec'
end


podspec:-

Pod::Spec.new do |s|

  s.name         = "xxxFoundationFramework"
  s.version      = "6.0.0"
  s.summary      = "This is master version"
  s.description  = <<-DESC
                   DESC

  s.homepage     = "http://EXAMPLE/xxxFoundationFramework"
  # s.screenshots  = "www.example.com/screenshots_1.gif", "www.example.com/screenshots_2.gif"
  s.license      = "MIT (example)"
  # s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "" => "" }
  # Or just: s.author    = ""
  # s.authors            = { "" => "" }
  # s.social_media_url   = "http://twitter.com/"
   s.platform     = :ios, "8.0"

  #  When using multiple platforms
  # s.ios.deployment_target = "5.0"
  # s.osx.deployment_target = "10.7"
  # s.watchos.deployment_target = "2.0"
  # s.tvos.deployment_target = "9.0"
  s.source       = { :git => "https://github.com/xxxxxx/xxxxxFoundationFramework.git" }
  s.source_files  = "xxxxxFoundationFramework", "xxxxFoundationFramework/**/*.{h,m}"
  s.exclude_files = "xxxxxFoundationFramework/Exclude"

  # s.public_header_files = "Classes/**/*.h"
s.prefix_header_contents = '#import "xxxxxHomeViewController.h"','#import "Constants.h"'

    # s.resource  = "icon.png"
   s.resources = "Resources/**/*.{png,xib,json,plist,ttf,xcassets,sqlite}"
  # s.resources = "xxxxxxxFoundationFramework/Resources/*.png","xxxxxxxFoundationFramework/Resources/**/*.xib","xxxxxxxFoundationFramework/Resources/**/*.json","xxxxxxxFoundationFramework/Resources/**/*.plist","xxxxxxxFoundationFramework/Resources/**/*.ttf","xxxxxxxeFoundationFramework/Resources/**/*.xcassets","xxxxxxxFoundationFramework/Resources/**/*.sqlite"
  # s.framework  = "SomeFramework"
  # s.frameworks = "SomeFramework", "AnotherFramework"

  # s.library   = "iconv"
  # s.libraries = "iconv", "xml2"
    s.vendored_library    = 'xxxxxxxFoundationFramework/LibUniversal/libmCommLib.a'
    s.library = 'xml2'
    s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }


  # ――― Project Settings ――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  If your library depends on compiler flags you can set them in the xcconfig hash
  #  where they will only apply to your library. If you depend on other Podspecs
  #  you can include multiple dependencies to ensure it works.

    s.requires_arc = true

  # s.xcconfig = { "HEADER_SEARCH_PATHS" => "$(SDKROOT)/usr/include/libxml2" }
  # s.dependency "JSONKit", "~> 1.4"
  # s.dependency "Google/CloudMessaging"
    s.dependency "xxxxxxxDomainModel", "~>6.0.0"
   # s.dependency "xxxxxxxNetworkManager", "~>6.0.0"
    s.dependency "xxxxxxxNetworkManagerSwift", "~> 1.0.0"
    s.dependency "xxxxxxxxxxxUtil", "~>6.0.0"
    s.dependency "xxxxxxxValidationManager", "~>6.0.0"
    s.dependency "Realm", "~>0.102.1"
    s.dependency "Typhoon", "~>3.5.1"
    s.dependency "couchbase-lite-ios","~> 1.2.1"
end

Thank you in advance

**Comment by benasher44** [comment]
Hi @VenuKotha! This issue is quite old. Would you mind filing a new one and filling out the issue template? Thanks!

**Comment by avadhutredekar** [comment]
Found a pod, https://github.com/haifengkao/PodAsset
Added it as dependency in pod spec and it solved the issue for me.

s.dependency 'PodAsset'

**Comment by AkashBelekar2428** [comment]
How to add Font File .ttf in podspce?

**Comment by glennposadas** [comment]
I got mine working by using `s.resources` instead of bundles.

```
s.resources        = ["SCMediaPicker/**/*.{storyboard,lproj}"]
```
