### ISSUE TITLE
GCC_PREPROCESSOR_DEFINITIONS values order affecting compilation on OS X

### ISSUE THREAD

**Issue by sync** [CocoaPods/CocoaPods#2423]
A way to reproduce this is by checking out for example the latest version of AFNetworking and setting up the Tests project (pod install inside the 'Tests' folder) and running a debug build of the OSX test target.

`xcodebuild -workspace AFNetworking.xcworkspace -scheme 'OS X Tests' -sdk 'macosx' -configuration Release clean test | xcpretty -c` ==> work in Release

`xcodebuild -workspace AFNetworking.xcworkspace -scheme 'OS X Tests' -sdk 'macosx' -configuration Debug clean test | xcpretty -c` ==> doesn't work in Debug

removing COCOAPODS=1 from all .xcconfig GCC_PREPROCESSOR_DEFINITION fixes it.

Also this isn't a 10.10 issue I am currently using 10.9 and Xcode 5.1.1.

Can anyone else either confirm / or let me know what am I doing wrong ?

**Comment by kylef** [comment]
Used the steps to reproduce and this works fine for me now:

```bash
$ git clone https://github.com/AFNetworking/AFNetworking
Cloning into 'AFNetworking'...
remote: Counting objects: 11326, done.
remote: Compressing objects: 100% (403/403), done.
remote: Total 11326 (delta 555), reused 688 (delta 431)
Receiving objects: 100% (11326/11326), 5.22 MiB | 3.00 MiB/s, done.
Resolving deltas: 100% (6678/6678), done.
Checking connectivity... done.
$ cd AFNetworking/Tests/
$ pod install --no-repo-update
Analyzing dependencies
Fetching podspec for `AFNetworking` from `../`
Downloading dependencies
Installing AFNetworking (2.5.1)
Installing Expecta (0.2.4)
Installing OCMock (2.1.1)
Generating Pods project
Integrating client project
$ cd ..
$ open AFNetworking.xcworkspace
$ xcodebuild -workspace AFNetworking.xcworkspace -scheme 'OS X Tests' -sdk 'macosx' -configuration Release clean test | xcpretty -c | grep Executed
	 Executed 71 tests, with 0 failures (0 unexpected) in 7.212 (7.236) seconds
$ xcodebuild -workspace AFNetworking.xcworkspace -scheme 'OS X Tests' -sdk 'macosx' -configuration Debug clean test | xcpretty -c | grep Executed
	 Executed 71 tests, with 0 failures (0 unexpected) in 7.387 (7.411) second
```
