### ISSUE TITLE
Rsync resources in Pods-resouces.sh is still too slow (when using asset catalogs)

### ISSUE THREAD

**Issue by jpmhouston** [CocoaPods/CocoaPods#2439]
Followup to https://github.com/CocoaPods/CocoaPods/issues/1050. That one fixes the rsync part of the script, I've found the xcasset part of the script is hobbled also when your project uses asset catalogs.

What seems to be happening is when actool is run to copy asset catalogs into the target, it re-runs on project assets as well as Pod assets.

I think my pull request fixes it correctly (but note that I don't really know what I'm doing): https://github.com/CocoaPods/CocoaPods/pull/2426

**Comment by alexbird** [comment]
Can anyone explain what will happen when we have framework support? 
Will we upgrade one day and find this step has gone and our builds are much faster, or does it mean a change in how we work with CocoaPods?
This step is now the longest single part of our build process, and it would be excellent to remove that speed bump from our TDD cycle.

**Comment by orta** [comment]
Likely a bit of both, the builds are much faster as the assets are embedded inside the frameworks. ( To my knowledge. ) The trade off is that if you're using `NSBundle mainBundle` in your code to access them then you'll need to change that to reflect the framework that those assets are in now.

**Comment by adamkaplan** [comment]
Seeing as CocoaPods is almost explicitly not designed to handle _surprise_ external changes to files within the Pods directory, it's a reasonable expectation that the copy script would not be aggressively healing. I know it's a far fetched request at this point, but it seems like CP could just check for a nonce of some kind and skip this whole rsync business on Debug builds. i.e. set or clear some lock on pod operations.

The frameworks change exists now, but unfortunately it will be quite some time before that is the standard in practice...

**Comment by werner77** [comment]
See my solution on stackoverflow: http://stackoverflow.com/a/40512275/480467
