### ISSUE TITLE
Framework pods with static library + test target causes dilemma (Fun with Abstract Targets)

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#2452]
[Parse-iOS](https://github.com/CocoaPods/Specs/blob/master/Specs/Parse-iOS/1.3.0/Parse-iOS.podspec.json) is a framework-pod.

Let's say I have two targets:

 - `MyProjLogic` static library target
 - `MyProjLogicTests` test bundle target. It depends on `MyProjLogic` and links against it.

Both of these need Parse support.

I like to express my pod dependencies as groups of 'traits' to apply onto my targets. So I've written my Podfile like so:

```ruby
# Podfile
...
target :ParseSupport do
  link_with 'MyProjLogic'
  pod 'Parse-iOS'
end
```

I was expecting this to work. But, actually when compiling the test target it was complaining that `<Parse/Parse.h>` could not be found.

I try linking the `ParseSupport` pod-library with `MyProjLogicTests` as well, as to make the headers available:

```ruby
...
  link_with 'MyProjLogic', 'MyProjLogicTests' 
...
```

This causes `Duplicate Symbol...` errors for Parse objects.

What I learned:

 - if I link a framework-pod to a static library, its headers (e.g. `<Parse/Parse.h>`)  are not available to test bundle targets that link to that static library
 - if I link the framework-pod to both the static library and the test bundle, then I get linker errors

I cannot think of any solutions other than to to manually set the Header Search Paths manually to point to the framework living under the Pods directory. ~~This will probably get overwritten by Cocoapods every time I run `pod install` and so this is an undesirable solution.~~

**UPDATE**: My solution at the moment is to [link Parse explicitly, including all of its dependencies](https://parse.com/apps/quickstart#parse_data/mobile/ios/native/existing) to any target that needs to work with Parse.

This is quite painful because it needs to be done for every target. You might have guessed from the example above, that I also have a couple of targets called `MyProjApp` and `MyProjTasterApp` that links against the `MyProjLogic` static library. For these cases, I get linker errors. I have to manually configure these targets to link against Parse as well.

What should I do?

**Comment by segiddins** [comment]
I'm fairly confident this has been fixed, feel free to comment if it hasn't.
