### ISSUE TITLE
Can't add owner do pod RevMob

### ISSUE THREAD

**Issue by marcelamiach** [CocoaPods/CocoaPods#2453]
Hello, 

I need to add a owner to RevMob pod and can't do it. I always receive the message "[!] You are not allowed to add owners to this pod.".

And I am the owner. How can I do that?

Thanks

**Comment by mro** [comment]
very confusing. What's `$ pod trunk add-owner` good for then?

**Comment by orta** [comment]
Adding someone else to a pod you already own.

**Comment by mro** [comment]
Confused now.

But it doesn't work, right?

At least that's what @marcelamiach  https://github.com/CocoaPods/CocoaPods/issues/2453#issue-42627971 told and @segiddins https://github.com/CocoaPods/CocoaPods/issues/2453#issuecomment-55412387 confirmed.

**Comment by segiddins** [comment]
No, @mro, this error is about not being authorized to add an owner.

**Comment by mro** [comment]
ic, @segiddins , but if me, the person that created the pod (supposedly the owner then), cannot add an owner - who possibly could then? That's byzantine to me.

**Comment by segiddins** [comment]
It means you don't have the correct Trunk account registered locally, most likely.
