### ISSUE TITLE
Cannot install cocoapods gem on Mac OS X 10.8.5 (Ruby 1.8.7) due to activesupport

### ISSUE THREAD

**Issue by dantull** [CocoaPods/CocoaPods#2458]
What I did:
sudo gem install -V cocoapods

The error I got:
ERROR:  Error installing cocoapods: activesupport requires Ruby version >= 1.9.3.

I read and searched the site and it seems like the intention is that 10.8.5 is still supposed to be supported. If not, I guess I can move to Mavericks, but wanted to report and confirm first.

Thanks.

**Comment by NiteshKumar-webonise** [comment]
Hi I am trying to install cocoa Pods but i am facing following issue. Can anyone help me out here 
sudo gem install -V  cocoapods
HEAD https://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
HEAD https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz
200 OK
GET https://rubygems.org/latest_specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz
200 OK
HEAD https://rubygems.org/specs.4.8.gz
302 Moved Temporarily
HEAD https://rubygems.global.ssl.fastly.net/specs.4.8.gz
200 OK
GET https://rubygems.org/specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/specs.4.8.gz
200 OK
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: cocoapods-trunk requires nap (~> 1.0)

**Comment by 1-61803** [comment]
ERROR:  Error installing cocoapods:
    	i18n requires Ruby version >= 1.9.3.

    tests-Mac:~ test$ ruby -v
    ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    tests-Mac:~ test$ 
    tests-Mac:~ test$ gem -v
    2.5.0
    tests-Mac:~ test$ 

I'm enjoying `cocoapods` installation in OS X 10.8.5, Xcode 5.1.1. Any ideas?
