### ISSUE TITLE
Problem with Headers folder when using SVN

### ISSUE THREAD

**Issue by vytis** [CocoaPods/CocoaPods#247]
My project uses SVN and I have added Pods directory to the repository. The problem is that every time i run `pod install` I suspect that Headers folder is recreated and SVN stops tracking changes in that folder. This probably happens because all .svn directories have disappeared from it. 

When looking at `svn status` I can see that Headers folder is marked with `~` sign ([more info](http://stackoverflow.com/questions/853405/what-does-the-subversion-status-symbol-mean)). This is very annoying, because the only way to fix this is to commit the deletion of Headers and then commit again with the updated version

**Comment by dairuiquan** [comment]
I have this problem too. Could you solve this? Please tell me . Thank you!
