### ISSUE TITLE
cocoapods can't find a pod version in master when an older version is available on the private repo, using the new sources option

### ISSUE THREAD

**Issue by fcy** [CocoaPods/CocoaPods#2478]
I'm converting my Podfile to the use the `source` option since this is a breaking change in 0.34.0 and I just found out a problem with the priorities and how cocoapods searches for pods. Looks like cocoapods assumes all versions of a pod are available on the first repo it finds the pod and that is not always the case.

For example, in my private repo I've a podspec for Tapstream version 2.7.2 because that version never made into the master repo. So if I search for Tapstream this is what I get:

```
$ pod search Tapstream


-> Tapstream (2.8.2)
   Tapstream marketing analytics.
   pod 'Tapstream', '~> 2.8.2'
   - Homepage: https://tapstream.com/
   - Source:   https://github.com/tapstream/tapstream-sdk.git
   - Versions: 2.8.2, 2.8.1, 2.7.4, 2.7.3, 2.7, 2.6.3, 2.6, 2.5.1, 2.5, 2.3 [master repo] - 2.7.2 [private repo]
```

In my Podfile I've this as the source options:

```
source 'private'
source 'master`
# ...
```

When I try to `pod install` using CocoaPods 0.34.0.rc2 I get this error:

```
$ pod install
Preparing
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Tapstream (= 2.8.2)` required by `Podfile`
```

This used to work fine before 0.34.0.rc2.

**Comment by MaximillionMai** [comment]
I am hitting this issue as well.  The public one was not releasing a version to fix its security issue, so I made a podspec release like "1.2.3-beta" in my private one.  This used to work perfectly in earlier versions of Cocoapods.  Now I am not able to pick up the public one. 
Most developers might have a tighter release deadline than the public open source code.  Waiting for the public version release might not be an option at times.
