### ISSUE TITLE
Xcode's syntax highlighting and code completion stops working

### ISSUE THREAD

**Issue by kommen** [CocoaPods/CocoaPods#25]
Under some circumstances Xcodes syntax highlighting and code completion stops working in files where header files from pod libraries are included.

I suspect this is has something to do with cocoapods `USER_HEADER_SEARCH_PATHS` in the `Pods.xcconfig` file, making Xcode search for the headers in the `BUILT_PRODUCTS_DIR`.
When building the initial index, the header files are not there yet, because the Pods target hasn't been built.

A workaround which made both syntax highlight and code completion work for me was to ensure that the Pods target is built (e.g building it as a dependency for another target or adding a separate Pods scheme) and the find the workspaces folder in Xcodes `Derived Data` folder and delete the _only_ `Index` folder there, to force Xcode to rebuild the index.

**Comment by itsthejb** [comment]
Have been having constant problems with this issue on my current project. It fits the symptoms here (pod headers imported in `.pch`). I tried various workarounds with no long-term luck. What *did* work was to abandon setting a prefix header in the test bundle build settings and instead manually importing the prefix header in each test file. Not elegant,  but *does* work.

Would be nice to have a "proper" solution, though...
