### ISSUE TITLE
CocoaPods 0.34.1 leaves pbxproject file in XML plist format

### ISSUE THREAD

**Issue by zygoat** [CocoaPods/CocoaPods#2530]
After upgrading from 0.33.1 to 0.34.1 today, I see a regression wherein `pod install` converts and leaves my project.pbxproj file sitting in XML property list format (rather than its original and Xcode-default ASCII property list format). This creates a huge, undiffable file in my working copy, _even if nothing has changed_.

According to [this wiki entry](https://github.com/CocoaPods/CocoaPods/wiki/Generate-ASCII-format-xcodeproj), the problem was first identified some time ago and resolved in CocoaPods 0.24.0.

In the mean time, I can clean up by making a bogus or trivial change to project settings in order to instigate Xcode into re-writing the project file; following a no-change `pod install` this will effectively revert it back from XML to ASCII, cleaning my working copy. However, this act should be unnecessary.

**Comment by erikjalevik** [comment]
I've just installed xcproj to get around this issue, but unfortunately this still doesn't result in a usable diff. Sure, the project file remains in ASCII format but all the IDs have changed and things have moved around to such an extent that the diff, although being between two ASCII files, shows differences on practically every line of the file.

**Comment by kylef** [comment]
@erikjalevik We're fully aware of this, the xcproj is mostly to keep your application project file consistent. The Pods.xcproj indeed changes the UUID's, there are a couple of open issues to prevent this:

- [Deterministic UUIDs](https://github.com/CocoaPods/Xcodeproj/issues/175)
- [Edit Pods projects in place](https://github.com/CocoaPods/CocoaPods/issues/1118)

There is even an open-pull request for this: https://github.com/CocoaPods/Xcodeproj/pull/185

**Comment by fabb** [comment]
Is xcproj still needed nowadays or are there better ways now?

**Comment by fabb** [comment]
@kylef I noticed when using `use_frameworks!` and doing a `pod install`, even when `xcproj` is installed, the project file will still be written in xml. Are there any workarounds for that? Both the Pods and my client project file are affected.

**Comment by Mitko-Kerezov** [comment]
I've got the following case:
Xcode 7.2, CocoaPods 0.39.0 - `$ pod install` leaves the `.pbxproject` in **ASCII plist format**
Xcode 7.2, CocoaPods 1.0.0-beta7 - `$ pod install` leaves the `.pbxproject` in **ASCII plist format**

Xcode 7.3, CocoaPods 0.39.0 - `$ pod install` leaves the `.pbxproject` in _**XML plist format**_
Xcode 7.3, CocoaPods 1.0.0-beta7 - `$ pod install` leaves the `.pbxproject` in **ASCII plist format**

Installing `xcproj` and adding it to path doesn't seem to fix the Xcode 7.3, CocoaPods 0.39.0 issue. As the `1.0.0-beta7` behaves correctly I'm guessing a patch will be issued for 0.39.0?

Tested both with and without `use_frameworks!`

**Comment by Mitko-Kerezov** [comment]
@kylef any thoughts on this?

**Comment by orta** [comment]
@Mitko-Kerezov please don't comment three hours after your last comment with "why haven't you responded to me" comments like this, it's not polite. People will get around to things that they work on in their spare time, when they do.

**Comment by Mitko-Kerezov** [comment]
@orta The comment was not meant to push anyone rather than to raise awareness. This issue is closed after all - not everyone checks up on closed issues
I don't mean to offend anyone

**Comment by segiddins** [comment]
No, we won't be patching pre-1.0 since Xcode 7.3 support is a feature and 1.0 final is very close.

**Comment by ryanzzff** [comment]
I can convert the format by running `xcproj touch` in Terminal.
so adding `system 'xcproj touch'` at the end of the Podfile seems work for me
