### ISSUE TITLE
Access Pods-environment.h

### ISSUE THREAD

**Issue by rivera-ernesto** [CocoaPods/CocoaPods#2536]
While never _officially_ supported, I use to `#import "../Pods-environment.h"` on many of my libraries to optionally use installed Pods while not really requiring them. For instance use CocoaLumberjack to log if already installed by the client app, but do not require it.

0.34.1 moves files around and I can't figure out how to reach Pods-environment.h.

Moreover I think this header file should be made readily accessible as it is very useful. Maybe `<Pods/Pods-environment.h>`?

**Comment by mxcl** [comment]
I guess there is no way to detect subspecs that don’t have headers then? I'll just hardcode a path to the Environment header until it next breaks.

**Comment by natestedman** [comment]
Based on these `Podfile` lines:

```ruby
pod 'AFNetworkActivityLogger', '~> 2.0', :configurations => ['Debug']
pod 'HockeySDK', '~> 3.6', :configurations => ['Ad-Hoc']
```

I have this code generated in my `Pods-environment.h`:

```c
// Debug build configuration
#ifdef DEBUG

  // AFNetworkActivityLogger
  #define COCOAPODS_POD_AVAILABLE_AFNetworkActivityLogger
  #define COCOAPODS_VERSION_MAJOR_AFNetworkActivityLogger 2
  #define COCOAPODS_VERSION_MINOR_AFNetworkActivityLogger 0
  #define COCOAPODS_VERSION_PATCH_AFNetworkActivityLogger 4

#endif
// Ad-Hoc build configuration
#ifdef AD_HOC

  // HockeySDK
  #define COCOAPODS_POD_AVAILABLE_HockeySDK
  #define COCOAPODS_VERSION_MAJOR_HockeySDK 3
  #define COCOAPODS_VERSION_MINOR_HockeySDK 6
  #define COCOAPODS_VERSION_PATCH_HockeySDK 4

#endif
```

I can guard like this...

```obj-c
#ifdef DEBUG
#import <AFNetworkActivityLogger/AFNetworkActivityLogger.h>
#endif
```

However, this leaks details into the application source that don't need to be there - the preprocessor macro should be based on library availability, not the current build configuration - I already declared that in `Podfile`. What I'd really want is something like:

```obj-c
#ifdef COCOAPODS_POD_AVAILABLE_AFNetworkActivityLogger
#import <AFNetworkActivityLogger/AFNetworkActivityLogger.h>
#endif
```

The headers are always *there*, so `__has_include` won't work. Perhaps the `Headers` directory could have `Debug`, `Release`, etc. subdirectories, and those could be specified in the build settings for each configuration?

**Comment by Whirlwind** [comment]
I agree with @natestedman ^_^
