### ISSUE TITLE
Duplicate headers in dependency

### ISSUE THREAD

**Issue by buscarini** [CocoaPods/CocoaPods#2540]
I have a pod which depends on Realm. The pod works on iOS and OS X, so I have an example with two targets, one for each platform. This is basically the structure:

	Example, ExampleMac -> MyPod -> Realm

And this would be my podfile:

	workspace 'Example.xcworkspace'
	xcodeproj 'Example/Example.xcodeproj'
	
	target :ExampleMac, :exclusive => true do
		xcodeproj 'ExampleMac/ExampleMac.xcodeproj'
		platform :osx, '10.8'
		pod 'MyPod', :path => '../'
		
		inhibit_all_warnings!  
	end
	
	target :Example, :exclusive => true do
		xcodeproj 'Example/Example.xcodeproj'
		platform :ios, '7.0'
		pod 'MyPod', :path => '../'
		
		inhibit_all_warnings!
	end
	
	target :ExampleTests, :exclusive => true do
		xcodeproj 'Example/Example.xcodeproj'
		platform :ios, '7.0'
		pod 'Specta', '~> 0.2'
		pod 'Expecta', '~> 0.3'
		pod 'OCMock', '~> 3'
		pod 'OHHTTPStubs'

		inhibit_all_warnings!
	end
	
This was working ok, except for the tests. I tried to fixed them and now the examples are not working either. The problem is that pod-Example-Realm is including both the ios and the osx headers, so I get duplicate definitions. Do you have any idea how to fix this?

Any comments would be much appreciated

Thanks

**Comment by segiddins** [comment]
Since this has had the `s4` label on it for almost a year, I'm presuming it's fixed?
