### ISSUE TITLE
SystemStackError - stack level too deep

### ISSUE THREAD

**Issue by mikeMTOL** [CocoaPods/CocoaPods#2552]
Michaels-MacBook-Pro:trunk Michael$ pod update
Update all pods
Analyzing dependencies
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
### Report
- What did you do?
  updated to cocoapods 0.34.1
- What did you expect to happen?
  to update pods
- What happened instead?
  bleeeech
### Stack

```
   CocoaPods : 0.34.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.0 (6A313)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 173a3d447f5bf59d0ef1a5dff39e5327cb3c98ef
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
platform :ios, '7.0'
pod 'DLAlertView', '~> 1.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'Mantle', '~> 1.4'
pod 'SVPullToRefresh', :git => 'https://github.com/mikeMTOL/SVPullToRefresh'
pod 'MSDynamicsDrawerViewController', :git => 'https://github.com/monospacecollective/MSDynamicsDrawerViewController', :commit => 'a38e327'
pod 'KeepLayout', :git => 'https://github.com/iMartinKiss/KeepLayout', :commit => '9641ab993c8261ce7b10ae3c42f8c173c853ef7c'
pod 'AFNetworking', '~> 2.2.3'
pod 'SDWebImage', '~> 3.6'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.3'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'Facebook-iOS-SDK', '~> 3.12'
pod 'Facebook-iOS-SDK', :inhibit_warnings => true
pod 'NGAParallaxMotion', '~> 1.0'
pod 'UIActionSheet-Blocks', '~> 1.0'
pod 'Reachability', '~> 3.1'
pod 'NSDate+Calendar', '~> 0.0'
pod 'FMDB', '~> 2.3'
# pod 'mopub-ios-sdk', '~> 2.3'
pod 'Google-Mobile-Ads-SDK', '~> 6.12'
pod 'RMYouTubeExtractor'
```
### Error

```
SystemStackError - stack level too deep
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.19.2/lib/xcodeproj/project/object_attributes.rb:139
```

**Comment by derjohng** [comment]
I met this issue today, and spend my whole day. I finally find the cause reason.
In my case, I add "Target Dependencies" in Build Phases of "WatchKit extension",
and cause "SystemStackError - stack level too deep".

Remove the "Target Dependencies" that is WatchKit app and main app, 
that will remove the "loop" issue.

**Comment by PelleRavn** [comment]
Had the same issue, and like @derjohng said, it's the Target Dependencies that makes the issue. 
I just have to re-add them afterwards, to make my app work again.

**Comment by neonichu** [comment]
can one of you provide a project that exhibits the issue?

**Comment by PelleRavn** [comment]
I can provide you with a project. But I really only comes down to make a new project (fx with a single view application), add fx a watch kit app target (and watch kit extension target), and then go under the watch kit extension > "Build Phases" and add the app target as Taget Dependency. This will result in this error, that is mentioned.
But let me know, if you want a sample project with this issue.

**Comment by FreudGit** [comment]
Hi, also have the stacklevel too deep error.

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'


def shared_pods
	pod 'Parse', '~> 1.2'
	pod 'Fabric'
	pod 'Crashlytics'


end

target '1001 v0.5' do
        shared_pods
        pod 'Google/Analytics', '~> 1.0.0'
	pod 'ParseUI'
	pod 'ParseFacebookUtilsV4', '~> 1.3'
	pod 'FMDB', '~> 2.2'
	pod 'NGAParallaxMotion', '~> 1.0'
	pod 'EDStarRating', '~> 1.1'
	pod 'skpsmtpmessage', '~> 0.0'
	pod 'CZPhotoPickerController', '~> 1.2'
	pod 'AFNetworking', '~> 2.3'
	pod 'SVProgressHUD', '~> 1.1'
end

target 'Widget1001' do
	shared_pods
end         

any idea?
