### ISSUE TITLE
Local (non-git) private repository not working on 0.34.X

### ISSUE THREAD

**Issue by sabadow** [CocoaPods/CocoaPods#2558]
I have a private repository on my local machine (it's a enterprise SVN repo) defined on ~/.cocoapods/repos.

````
pod repo list

arcadia-repo
- Type: local copy
- Path: /Users/cperez/.cocoapods/repos/arcadia-repo

master
- Type: git (origin)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/cperez/.cocoapods/repos/master
````
It works correctly on all versions including 0.33.1, but not in 0.34.1.

When I try to make a `pod install` this error appears:

````
pod install
Analyzing dependencies
fatal: No remote configured to list refs from.
[!] The `arcadia-repo` repo is not a git repo.
````

Thats right, the repo isn't a git repo. It's a new requirement for local repositories?
Thanks in advance.

**Comment by kylef** [comment]
https://github.com/CocoaPods/CocoaPods/pull/2973 does just that @neonichu.

**Comment by clarkda** [comment]
@kylef i'm still having the same issue with `pod install` from non-git repositories -- can we reopen this issue?

i'll do a PR in just a few

**Comment by kylef** [comment]
@clarkda Do you know if this has been resolved?
