### ISSUE TITLE
-fobjc-arc flag passed to tools which don't understand it

### ISSUE THREAD

**Issue by amolloy** [CocoaPods/CocoaPods#2559]
CocoaPods appears to add the -fobjc-arc flag to all compiled sources when requires_arc is true (which is the default now in 0.34), regardless of whether the tool that compiles that source file understands the flag or not. In particular, yacc (bison) will fail, and there are probably others.

Steps: 
- Add a pod which includes a yacc source file and has requires_arc set to true to your podfile.
- Run pod install
- Build in Xcode

Expected results:
- CocoaPods only applies the -fobjc-arc flag to Objective-C source files (*.m, *.mm) and the project builds without error.

Actual results:
- CocoaPods applies the -fobjc-arc flag to every compiled source file, regardless of file type. This does not cause issues for files compiled using clang, regardless of the actual language, but fails with files compiled with some other tools including yacc/bison.

**Comment by iosdev-republicofapps** [comment]
Bump ...

Any idea when this might be fixed?  :-)  It's causing builds to fail for a number of important specs that use things like yacc, etc and the C libraries.

**Comment by k0nserv** [comment]
Is `-fobjc-arc` still passed? #2769 makes it so that `-fobjc-no-arc` is passed and the project default becomes `CLANG_ENABLE_OBJC_ARC`.

**Comment by neonichu** [comment]
@k0nserv I tried <https://github.com/Bertrand/handlebars-objc> from the linked issues and it lints for me (after fixing an unrelated issue with `public_headers` in the spec).

**Comment by Legoless** [comment]
CocoaPods never sets `CLANG_ENABLE_OBJC_ARC` to `NO`, only appends compiler flags (at least from what I've tried). So if you have source files that are non-arc (one example is the repository @neonichu mentioned), Pods will be unable to build without modifying build settings manually in Xcode and setting that property + removing all compiler flags for non-ObjC files.

**Comment by orta** [comment]
Checked, this is still valid, to repo:

```sh
  git clone git@github.com:uranusjr/macdown.git
  cd macdown
  git submodule init
  git submodule update
  pod install
```
