### ISSUE TITLE
Generate binary version of pod

### ISSUE THREAD

**Issue by olegam** [CocoaPods/CocoaPods#2568]
At my company we have a number of private pods we manage through a private spec repo. We would also like to distribute our pods in binary form. The binary pods (containing a static lib and header files) should have the same names, but the podspecs should be hosted through a different spec repo. Using the new `source` keyword it should be possible to specify in the Podfile if the source based or the binary based version of our pods should be used.

When I compile an app using one of my normal pods there is a static lib created for each pod. I have tried copying one of those libs (called `libPods-MyPod.a`) along with the header files into its own folder and created a podspec for it. In the podspec I used the `vendored_library` property to make the app link against the binary pod. The problem with this approach is I get a linker error for duplicate symbols:

```
duplicate symbol _OBJC_METACLASS_$_PodsDummy_Pods_MyPod in:
    TestApp/build/Products/Debug-iphoneos/libPods-SHPFoundation.a(Pods-SHPFoundation-dummy.o)
    MyPod/libMyPod.a(Pods-MyPod-dummy.o)
```

If I instead create an Xcode project to generate the static library from my pod by manually selecting source files it works fine. But then I have to duplicate all the settings specified in the podspec file in the new Xcode project and I don't want to create and maintain such a project file for each of our pods.

Does anyone know how to properly create a static lib from a cocoapod?

Ultimately I want our CI server to automatically create binary pods whenever a pod is updated. Has anyone else tried something similar to this?

**Comment by cesar-oyarzun-m** [comment]
hey I'm using cocoapods packager and I want to have the same podspec to deliver source code and binary, but it doesn't work. It only works if I don't use subspecs. I'm following this page http://markspanbroek.github.io/2016/04/14/binary-cocoapods.html
