### ISSUE TITLE
Multiple application targets and set config files overridden by pod install

### ISSUE THREAD

**Issue by maurim86** [CocoaPods/CocoaPods#2575]
Hi, my application uses multiple targets and I have a separate xcconfig files for each. I used to specify configs per target as shown in the image below:

![pre-podinstall](https://cloud.githubusercontent.com/assets/3275630/4488143/1f55fd7c-4a09-11e4-9379-3f72673e90f4.png)

Since the pod install always forces Target 1 config to be Pods.debug I have to manually change the config file back to Target 1.

![post-podinstall](https://cloud.githubusercontent.com/assets/3275630/4488145/2a44e3f6-4a09-11e4-8651-49e41b75a04e.png)

Is there a way to prevent pod install from changing the targets config file. Or is there a better way to add per target configurations?

Cocoapods version: 0.34.1

Using following Podfile:
platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

pod 'ReactiveCocoa', '~> 2.3', :inhibit_warnings => true

Thanks, Mauri

**Comment by x5forever** [comment]
@maurim86 
I have the same issue. Have you found any way to solve it? Thanks for your help.

**Comment by maurim86** [comment]
@x5forever 
I'm not working with iOS anymore so I can't confirm this but didn't that get improved in the update as stated above?

Are you running newest cocoapods version? There has been breaking changes from 0.9 to 1.0 so check their migration guide :)

Hope you get It fixed!

**Comment by manishvpatel** [comment]
Hi all and @maurim86 

Its very simple to solve this issue. Just add #include "Pods/Target Support Files/Pods-TargetName/Pods-TargetName.debug.xcconfig" in your each custom config file. Make sure to change target name and environment.

Thanks.
