### ISSUE TITLE
Updating spec repositories is happening during `Analyzing dependencies`

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#2589]
This makes it seem like `Analyzing dependencies` is taking forever. When I did `--verbose` to see what was taking so long I found out it wasn't even analysing dependencies yet but updating spec repo's.

```bash
$ pod install --verbose
Analyzing dependencies

Updating spec repositories
  $ /usr/local/bin/git rev-parse  >/dev/null 2>&1
Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
```

We should say we're syncing spec repos and do that before printing `Analyzing dependencies`.

**Comment by deksden** [comment]
Totally agree with this issue: slow hotel wifi makes "analyzing" a pain! Informing that repo sync is in progress can make user skip this step.

Defenitely UI should be different than current.

**Comment by segiddins** [comment]
The issue is that updating the specs repos is _definitely_ part of the analysis step.

**Comment by orta** [comment]
I think it's reasonable to have it in it's own UI section as "Updating local Specs repo" before this?
