### ISSUE TITLE
Storyboard in Resource Bundle

### ISSUE THREAD

**Issue by shortstuffsushi** [CocoaPods/CocoaPods#2597]
Hi guys,

I've searched all through here and SO today, and I'm struggling to find a solution to my issue. I'm trying to include a library I've made into a project. The library includes localized strings and localized storyboards, so I've added a `resource_bundle` into it's podspec, which has a `**/*.{lproj,png}` specification. The strings are coming through fine, as expected (it pulls in the whole lproj folder). However, the storyboards are *not* working, and I believe it's because they aren't compiled. Instead of being .storyboardc files, the lproj's just contain .storyboards. Am I doing this the right way? Is there something I'm missing? Is this supported?

Thanks. Here's your :rainbow: btw.

**Comment by timbodeit** [comment]
I've made a small fix for this issue, that during project creation will transform `.lproj` structures into variant groups.
It is currently work in progress. The fix still needs some refactoring, documentation and tests, before this is ready for a pull request. I'll file one soon, but it might take a week or two before I find the time.

If someone needs this fix in the meantime, have a look at the [2597-variantgroups-localized-resources](https://github.com/timbodeit/CocoaPods/tree/2597-variantgroups-localized-resources) branch of my Cocoapods fork.

Help on providing test coverage for this would be very welcome.

**Comment by andyyardley** [comment]
I've done some research today using timbodelt's branch and it appears that for localised storyboards the target device needs to be included in the ibtool command line such as ' --target-device ipad --target-device iphone' as I was in a rush to resolve this I temporarily hacked it into my XXXX-resources.sh file and it correctly compiled and copied the storyboard to the app.

Maybe somebody else would like to verify this and create a proper fix?

**Comment by timbodeit** [comment]
@andyyardley Are you using static libraries or frameworks?
It sounds to me as if you are static libraries.

My fix was only intended for the use with frameworks where Xcode handles the compilation of the storyboard in the "Copy Bundle Resources" phase (so to say, itdoes the ibtool call for us).
AFAIK, my changes shouldn't make any difference to copying of the resources in a static library (as the `XXX-resourses.sh` script works based on the file system structure, not based on the xcode project structure).

I have only only briefly read over it, but your issue might be related to #1690

**Comment by andyyardley** [comment]
@timbodeit I'm using static libraries. TBH I didn't properly read the title of your pull request, nevertheless your works seems to create a much cleaner file structure which then works correctly with the 'hack' I mentioned above.

**Comment by timbodeit** [comment]
@andyyardley You couldn't have misread it at the time of your first comment, as the pull request didn't exist yet at that point.
To be fair, I was the one to incorrectly make the assumption that this issue was related to frameworks (as that is what I was using).

@shortstuffsushi Which one of the two were you using when you created this issue?

**Comment by shortstuffsushi** [comment]
@timbodeit at this point, I'm not sure. It's been ~ a year, and I'm not working on that project anymore, and don't remember what my exact issues were at that point, and haven't tried again with the more recent versions of Cocoapods (still using it, just not w/ storyboards really). However, frameworks are a newer feature of Cocoapods, right? In the past, it just always compiled to static libs, right? If so, then that's probably what I was doing at the time.

**Comment by timbodeit** [comment]
@andyyardley When I made those changes, I only intended the fix to be for frameworks. But as I found out today, it might also work for static libraries when using resource bundles.

To confirm: You weren't using resource bundles, but rather specifying a `resources` attribute in your spec, right?
Have you tried using resource bundles instead?

**Comment by efirestone** [comment]
I added some additional improvements here which definitely help with resources and resource bundles: https://github.com/CocoaPods/CocoaPods/pull/4635
