### ISSUE TITLE
"Check Pods Manifest.lock" fails in 0.34.2 (PODS_ROOT)

### ISSUE THREAD

**Issue by mattrubin** [CocoaPods/CocoaPods#2627]
After updating to `0.34.2`, the "Check Pods Manifest.lock" fails with the following error:

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

Enabling the "Show environment variables in build log" option for this build script reveals a difference. When using `0.34.1`, I see `export PODS_ROOT=/Users/matt/MyProject/Pods` in the build log, but the `PODS_ROOT` variable is clearly absent when using `0.34.2`.

I know that `PODS_ROOT` is deprecated as of `0.34`, but if it's no longer available then the CocoaPods-generated build script should be fixed to work without it.

**Comment by ogezue** [comment]
link_with 'Target A', 'Target B', 'Target C'  

was the magic line for me. Just add every target from your project.

**Comment by djibouti33** [comment]
I'm running cocoa pods 0.35.0, Xcode 6.1.1, and just like @ogezue said, adding link_with 'Target x' to my podfile and running `pod install` did the trick.

**Comment by SatyanarayanaKV** [comment]
hi im using CocoaPods 0.39.0.beta.4 is available. getting the above error

can any one help me please

**Comment by salvoc** [comment]
Make sure you have all of your target included in the Podfile somehow. 
I had this problem and was because since last update I had moved pod dependencies to the test target only and with the *exclusive* clause. This caused the Pods.debug.config and the Pods.release.config not to be generated.

**Comment by jurijstur** [comment]
You could use this tool:
https://github.com/kylef/cocoapods-deintegrate

and then

pod install

**Comment by BellAppLab** [comment]
I have come across this issue on 0.39.0 when using the `link_with` directive. Switching to adding pods to each target separately fixed it:

    target 'Target' do
        pod 'MyPod'
    end
    
    target 'OtherTarget' do
        pod 'MyPod'
    end

**Comment by sameid** [comment]
That cocoapods-deintegrate tool worked for me. Thanks jurijstur!
