### ISSUE TITLE
Optional frameworks needed

### ISSUE THREAD

**Issue by angelolloqui** [CocoaPods/CocoaPods#263]
I have an app that is using ShareKit with the Twitter Sharer. CocoaPods is adding the Twitter framework to the OTHER_LDFLAGS as follows:
`OTHER_LDFLAGS = -ObjC -all_load -framework Twitter`

The problem appears when I am trying to release the app, with iOS 4.2 deployment target.

When run in iOS 4.x  the Twitter framework can not be loaded, and therefore the app closes during the starting process. To fix it, we need to mark frameworks as optional, but I don't know how to do this with the OTHER_LDFLAGS (is it possible? I couldn't find anything similar googling).

And the corresponding Device Log:

```
Hardware Model:      iPhone2,1
Code Type:       ARM (Native)
Parent Process:  launchd [1]

Date/Time:       2012-05-22 10:53:01.805 +0200
OS Version:      iPhone OS 4.3.3 (8J2)
Report Version:  104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x00000001, 0xe7ffdefe
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/Twitter.framework/Twitter
  Referenced from: /var/mobile/Applications/BB918653-EE0F-4CE1-A52A-9F95CD8A6DA5/XXXX.app/XXXX
  Reason: image not found
  Dyld Version: 191.3
```

Any idea how to fix this in CocoaPods installation? 

For now I am going to delete the Twitter framework from the Pods.xcconfig file and include it manually (as optional), which I hope will work, but we should find a workaround for this because it will be present every time that a new framework appears.

Note: The app runs when starting from XCode, only crashes when installing the released ipa. It may make sense to you, but it does not to me :(

**Comment by onmyway133** [comment]
@alloy I see that in target Build Settings, there are `-framework UIKit` and `-weak_framework UIKit`, why is that?
