### ISSUE TITLE
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`

### ISSUE THREAD

**Issue by kyleYang** [CocoaPods/CocoaPods#2641]
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/user_interface/error_report.rb:13:in `report': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command.rb:61:in`report_error'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:300:in `handle_exception'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:274:in`rescue in run'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:264:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command.rb:48:in`run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/bin/pod:33:in `<top (required)>'
    from /usr/bin/pod:23:in`load'
    from /usr/bin/pod:23:in `<main>'

this error was showed when I use pod install update.
This project was downloaded from a svn.
ruby version is  ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
gem version is 2.4.2
cocoapods version is 0.34.2
Xcode 6.01. ,Mac OS version is 10.9.5

**Comment by danielmartinprieto** [comment]
I had the same issue and Kylef's answer solved my problem as well.

**Comment by peiweichen** [comment]
@kylef Thank you!

**Comment by qalandarov** [comment]
@kylef Thank you!

**Comment by jkbreunig** [comment]
I have a similar issue and @kylef solution didn't fix the issue.

Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.beta.1`

**Comment by segiddins** [comment]
@jkbreunig what CocoaPods version are you running?

**Comment by mattinove** [comment]
I have the same @jkbreunig  issue and @kylef solution didn't fix my problem too.
The CocoaPods version is **0.39.0** 
@segiddins can you help me please?

**Comment by Asteroidhaha** [comment]
"Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0`",how to solve this problem?

**Comment by dabvid** [comment]
+1

**Comment by trongtan** [comment]
Just remove gem cocopods-deploy.

**Comment by wangqianjun** [comment]
+1

**Comment by gknows** [comment]
+1

**Comment by kenial** [comment]
I just did:
`[sudo] gem uninstall cocoapods-deintegrate`
then,
`[sudo] gem install cocoapods`
It updated cocoapods up to 1.0.1 and now I got peace of mind.

**Comment by kenial** [comment]
And here is my result of `gem list' relevant to cocoapods:
> cocoapods (1.0.1, 0.39.0, 0.38.2, 0.37.2, 0.36.4)
> cocoapods-core (1.0.1, 0.39.0, 0.38.2, 0.37.2, 0.36.4)
> cocoapods-deintegrate (1.0.1)
> cocoapods-downloader (1.1.1, 1.0.0.beta.3, 0.9.3, 0.9.1, 0.9.0)
> cocoapods-plugins (1.0.0, 1.0.0.beta.1, 0.4.2)
> cocoapods-search (1.0.0, 1.0.0.beta.2, 0.1.0)
> cocoapods-stats (1.0.0, 1.0.0.beta.4, 0.6.2, 0.6.1, 0.5.3)
> cocoapods-trunk (1.0.0, 0.6.4, 0.6.1, 0.6.0)
> cocoapods-try (1.1.0, 1.0.0.beta.3, 0.5.1, 0.4.5, 0.4.3)

**Comment by seajean** [comment]
+1
