### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by kyleYang** [CocoaPods/CocoaPods#2642]
@alloy , I use command

```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```

configured terminal properly for UTF-8. but the error not be resolved.

```
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/user_interface/error_report.rb:13:in `report': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command.rb:61:in `report_error'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:300:in `handle_exception'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:274:in `rescue in run'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:264:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command.rb:48:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/bin/pod:33:in `<top (required)>'
    from /usr/bin/pod:23:in `load'
    from /usr/bin/pod:23:in `<main>'
```

and use $ env 

```
rvm_bin_path=/Users/apple/.rvm/bin
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/_q/qcdcvp1n21qdhxwwk0nnp2q40000gn/T/
Apple_PubSub_Socket_Render=/tmp/launch-ERuRft/Render
TERM_PROGRAM_VERSION=326
OLDPWD=/Users/apple
TERM_SESSION_ID=90AF7295-44CD-476E-A75F-5C6C1EF22FD5
LC_ALL=en_US.UTF-8
USER=apple
_system_type=Darwin
rvm_path=/Users/apple/.rvm
SSH_AUTH_SOCK=/tmp/launch-NAoKRw/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:25:52
rvm_prefix=/Users/apple
PATH=/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Users/apple/.rvm/bin
__CHECKFIX1436934=1
PWD=/Users/apple/SVNALL/yujiahui/yunifang/codes/iOS/trunk/eShop
LANG=en_US.UTF-8
_system_arch=x86_64
_system_version=10.9
rvm_version=1.25.33 (stable)
SHLVL=1
HOME=/Users/apple
LOGNAME=apple
LC_CTYPE=UTF-8
DISPLAY=/tmp/launch-hDnOeS/org.macosforge.xquartz:0
_system_name=OSX
_=/usr/bin/env
```

It's seem that the terminal has been changed!
Thank you!

**Comment by 401885064** [comment]
how to edit " '  "???   i  am  try  any  times!

**Comment by babydance** [comment]
you can try to open it by vi,and then check " ‘ ’ " carefully,you will find it was not " ' ".

**Comment by 401885064** [comment]
babydance   is   right!!   thank you！
![qq 20150116170650](https://cloud.githubusercontent.com/assets/1718122/5773824/03ed6b28-9da2-11e4-99d6-c7a385c9f384.jpg)

**Comment by maciekish** [comment]
Could this be related to our η characters turning into &#951; after a pod install? It started happening fairly recently.

**Comment by bartlomiejzdybowicz** [comment]
I have proper ' chars and still keep getting this error.

**Comment by PythonHe** [comment]
Just fixed this problem, I think we should edit podfile in the Xcode instead of TextEdit next time.

**Comment by ljchu** [comment]
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:

export LANG=en_US.UTF-8

-----
You need to set the encoding of your terminal to UTF-8.I think so.

**Comment by yoiang** [comment]
I'm getting this error when I do a `pod lib lint` on a project I forked and it isn't clear what file it's having the issue with or what's causing the issue exactly (podspec, license, readme...). I'd be great to have clearer error message if possible.

**Comment by gruhls508** [comment]
^ upvote for @PythonHe's comment. I had this issue because I had run `touch Podfile` followed by `open Podfile` in Terminal. Defaulted to opening Podfile in TextEdit, which provided the wrong encoding even though I had confirmed my chars used and syntax were correct (all I had in the podfile was `platform :ios, '8.2'`)

I deleted that podfile (and the /Pods directory that had been created in Xcode,) ran `touch Podfile` again and opened the Podfile this time with Xcode. I entered the same text I had had in my previous non-functional podfile, saved the file and was able to run `pod install` successfully.

**Comment by Morkrom** [comment]
I have the exact same issue but creating a new podfile and opening it only in xcode is not addressing the issue.

**Comment by lemonkey** [comment]
`file -I <filename>` is handy

**Comment by ZHANGMRXIN** [comment]
check ur podspec file, and double quotation marks shouls like this " ", not like this “ ”, or other samples.

**Comment by rubetek** [comment]
I changed my script call to

sh 'LANG=en_US.UTF-8 fastlane beta'

instead of just sh 'fastlane beta'

and it worked.

**Comment by wzbozon** [comment]
Jenkins/Pipeline doesn't use LANG from bash_profile for some reason.

I changed my script call to

sh 'LANG=en_US.UTF-8 fastlane beta'

instead of just sh 'fastlane beta'

and it worked.

**Comment by songhongkang** [comment]
![企业微信截图_95aa7c78-cd99-4c65-9107-6d8928bbf36b](https://user-images.githubusercontent.com/13045795/71965009-cc47be80-3239-11ea-8a1b-b190d153d915.png)
pod lin lint 出现了的，podspec没有中文符号，怎么解决的。。

**Comment by liangbohang** [comment]
Please check if there is any Chinese characters in your project path. It works for me and costs my half of day!

**Comment by Horse888** [comment]
> Please check if there is any Chinese characters in your project path. It works for me and costs my half of day!

Thank your very much, I spend two days on this issue. You are right, the problem is project path has Chinese characters.
