### ISSUE TITLE
Can't archive project

### ISSUE THREAD

**Issue by mgrebenets** [CocoaPods/CocoaPods#265]
Hi

Xcode 4.3
Mac OS X Lion
Trying to build Universal app.
I am opening workspace file generated by 'pod install'.
Building, testing on device and simulator works just fine.
However I run into problems when trying to archive I get this error message:

> ld: library not found for -lPods

I googled for similar problem and found this stackoverflow post http://stackoverflow.com/questions/9863836/library-not-found-for-lpods, but adding ":deployment_target => '5.0'" doesn't help. Generated Pods project file still has '4.1' deployment target and I still get same link error.
I tried messing around with Pods project file, setting deployment target to '5.0' manually, setting code signing, and other things with no results.

I wonder if I miss something here. Should archiving be done via command line if Pods are used or any other specifics?

Would appreciate any help, thanks.

Here's the Pod file:

> # Pods
> 
> platform :ios, :deployment_target => '5.0'
> # Facebook
> 
> dependency 'Facebook-iOS-SDK'
> # Other
> 
> dependency 'CocoaLumberjack'
> dependency 'SVProgressHUD'
> dependency 'CocoaAsyncSocket'
> dependency 'EGOTableViewPullRefresh'
> dependency 'Appirater'

**Comment by leonardocorrea1000** [comment]
In my case, the problem was in Podfile. I was setting pod Library for each target. But what to set in project level.

![screen shot 2016-05-09 at 11 23 52](https://cloud.githubusercontent.com/assets/12837871/15116167/96182b8c-15d8-11e6-998b-6a42c1fe1b06.png)
