### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by ramis2k** [CocoaPods/CocoaPods#2651]
![image](https://cloud.githubusercontent.com/assets/9155357/4603627/39090220-5173-11e4-94ab-3a4ddd756ee7.png)
### Report
- What did you do?
  Run pod install on a new empty project.
- What did you expect to happen?
  Install the latest pod versions.
- What happened instead?
  Got an error.

Steps followed:
I'm getting the error on my main project, but to make sure that it wasn't a problem with my project I did this:
- Create new, empty, xcode project somewhere.
- Create a Podfile there with only 3 lines (to make things really simple):
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '6.0'
  pod 'Appirater'
- Run pod install
  And I get this error:

> /Projects Mac/Pod Test > pod install
> Analyzing dependencies
> usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>]
>                      [-q|--quiet] [<repository> [<refs>...]]
> usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>]
>                      [-q|--quiet] [<repository> [<refs>...]]
> Creating shallow clone of spec repo `master-2` from `https://github.com/CocoaPods/Specs.git`
> usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>]
>                      [-q|--quiet] [<repository> [<refs>...]]
> usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>]
>                      [-q|--quiet] [<repository> [<refs>...]]
> usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>]
>                      [-q|--quiet] [<repository> [<refs>...]]
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
> fatal: Not a git repository (or any of the parent directories): .git
### Stack

```
   CocoaPods : 0.34.2
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.4 (13E28)
       Xcode : 6.0.1 (6A317)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9ed005f4d6d55b18deb2da378ed8fcb1b6f89786
               master-1 - https://github.com/CocoaPods/Specs.git @ e8033192aff958475ce11a88175f1960993a1b2f
               master-2 - https://github.com/CocoaPods/Specs.git @ e8033192aff958475ce11a88175f1960993a1b2f
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.0
cocoapods-try     : 0.4.1
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'
pod 'Appirater'
```
### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:172:in `block (2 levels) in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:172:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:172:in `block in update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:171:in `update_repositories_if_needed'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer/analyzer.rb:48:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.2/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

```

**Comment by manoj-eprosoft** [comment]
System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin14/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1 (6A1052d)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 66ecb44224d109e4e750ef314ef6f436d04e9991
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'ShowTracker' do:pod 'AFNetworking','2.5.4'

end
```

### Error

```
SyntaxError - /Users/epromacmini/Desktop/ShowTracker/Podfile:4: syntax error, unexpected tSTRING_BEG, expecting keyword_end
target 'ShowTracker' do:pod 'AFNetworking','2.5.4'
                             ^
/Users/epromacmini/Desktop/ShowTracker/Podfile:4: syntax error, unexpected ',', expecting keyword_end
target 'ShowTracker' do:pod 'AFNetworking','2.5.4'
                                           ^
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/podfile.rb:254:in `eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/podfile.rb:254:in `block in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/podfile.rb:251:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/podfile.rb:251:in `from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.37.1/lib/cocoapods-core/podfile.rb:227:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/config.rb:197:in `podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:109:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

It appears to have originated from your Podfile at line 4.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%2FUsers%2Fepromacmini%2FDesktop%2FShowTracker%2FPodfile%3A4%3A+syntax+error%2C+unexpected+tSTRING_BEG%2C+expecting+keyword_end%0Atarget+%27ShowTracker%27+do%3Apod+%27AFNetworking%27%2C%272.5.4%27%0A+++++++++++++++++++++++++++++%5E%0A%2FUsers%2Fepromacmini%2FDesktop%2FShowTracker%2FPodfile%3A4%3A+syntax+error%2C+unexpected+%27%2C%27%2C+expecting+keyword_end%0Atarget+%27ShowTracker%27+do%3Apod+%27AFNetworking%27%2C%272.5.4%27%0A+++++++++++++++++++++++++++++++++++++++++++%5E&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Can i know whats is the issue here?
I had followed the process given here "http://www.raywenderlich.com/64546/introduction-to-cocoapods-2"
