### ISSUE TITLE
Workspace doesn't build after pod update until re-open

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/CocoaPods#2665]
After updating to 0.34.2 whenever we run `pod update` the project doesn't compile anymore until the workspace was closed and opened again.
### Result

Warnings from Xcode:

```
The file "Pods.release.xcconfig" couldn’t be opened because its path couldn't be resolved.  It may be missing.
The file "Pods.debug.xcconfig" couldn’t be opened because its path couldn't be resolved.  It may be missing.
```

Resulting in these errors during build:

```
Diff: /../Podfile.lock: No such file or directory
Diff: /Manifest.lock: No such file or directory
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
### Notes
- `pod update` correctly added both xcconfig files to the `Pods` group and they can even be opened in Xcode.
- `pod update` succeeds without warnings or errors.
### Environment
- CocoaPods 0.34.2
- Xcode 6.1 GM 2
- Mac OS X 10.9.5
### Steps to reproduce:
1. Open the workspace
2. Run `pod update` in the workspace's path in Terminal
3. Build workspace
4. **Build fails**
5. Close workspace & open again
6. Build workspace
7. **Build succeeds**

**Comment by githupchenqiang** [comment]
how to deal it ，l am so hard

**Comment by scott-lydon** [comment]
@josipbernat where can I put PODS_ROOT=${SRCROOT}/Pods in the build settings?  Under what category?
