### ISSUE TITLE
Using pods in static library targets is broken in 0.34.x and Xcode 6.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#2666]
This ticket supersedes #2319.

With Xcode 6:
- When building app targets, the `OTHER_LDFLAGS` flag is used to link and passed to `ld`.
- When building a static library, the `OTHER_LIBTOOLFLAGS` flag is used to link and passed to `libtool`.

Thus, Xcode 6 no longer links in the pods dependencies into the user's static library target.

The simple fix is:
- Add `OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)` to the `Pods.CONFIGURATION.xcconfig` files.
- Override `OTHER_LIBTOOLFLAGS` to be blank on the Pods target in the Pods.xcodeproj, just like we already do with `OTHER_LDFLAGS`.

**Comment by itsthejb** [comment]
I appear to be seeing this issue in 0.36.0.beta.2. In my case, static library target, pods that require sqlite, libz, and libxml2:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified the following flags are invalid: -ObjC -ObjC
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lsqlite3
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lsqlite3 is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lxml2
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lxml2 is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lz
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lz is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lsqlite3
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lsqlite3 is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lxml2
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lxml2 is not an object file (not allowed in a library)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lz
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lz is not an object file (not allowed in a library)
```

**Comment by duhanebel** [comment]
I think this introduces another issue with IB designable. Libtool doesn't seem to like the "-ObjC" flag that is passed on LD_FLAGS and fails compilation when compiling for IBDesignables a View that links against a static library. The error is: 

`[...]/usr/bin/libtool: unknown option character `W' in: -Wl,-pie`

Removing "-ObjC" from OTHER_LIBTOOLFLAGS seem to fix the problem for IBDesignable builds.

**Comment by lemonkey** [comment]
Seeing the same issue when trying to build for IB designable for XIBs in a static library that uses Cocoapods.
