### ISSUE TITLE
CocoaPods on Yosemite needs UTF-8 encoding 

### ISSUE THREAD

**Issue by domingguss** [CocoaPods/CocoaPods#2668]
Came here because I (almost) got this error when i tried to do **pod install**:

```
NoMethodError - undefined method `repo' for nil:NilClass
```

I checked out a project, but now on Yosemite and could not do a 'pod install' anymore..

What I tried:
- uninstall xcodeproj
- uninstall cocoapods
- reinstall homebrew
- reinstall ruby
- reinstall xcodeproj
- reinstall cocoapods

But I stil got this error.
Then, after 4 hours of debugging and trying, I got this warning after I did **pod --version**

```
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
```

FIX: So I added the following to my ~/.bash_profile__ :

```
export LC_ALL="en_US.UTF-8"
```

P.S: This warning _only_ comes up when doing 
**pod --version**  
So, **please** include this UTF-8 warning when doing a **_pod install_** too ;)

**Comment by jonnyijapan** [comment]
I get this warning with both `pod versoin` and `pod install` and it does NOT go away, even adding the suggested `export LANG=en_US.UTF-8` to ~/.profile and/or ~/.bash_profile and restarting Terminal.
