### ISSUE TITLE
Pods not found within pch .. why?

### ISSUE THREAD

**Issue by wdcurry** [CocoaPods/CocoaPods#2671]
Perhaps i am missing something very basic, but with an apparently successful first usage of pods, i managed to get my app rolling without manual folders installation.... great!

But dropping the exact same import lines into Prefix.pch _fails_ to find the pods in question. 

Only until i (after much digging) decided to update "User Header Search Paths" with "Pods" recursive, and "Always Search User Paths" to Yes ... was i able to work with the pch.

Of course i assumed that I had somehow messed up the pods install, the podfile, the phases of the moon etc given how many use pods. Lost too much time chasing this one, and posted here to help others, or to discover my booboo...

Thoughts?

**Comment by manuqiao** [comment]
Cool inspiring @codepushr ! That solves my problem. The reason is that we got more than 1 targets in our project. The Podfile we wrote was not linked to others. I manually wrote another block of `target :'Target' do` , silly but effective. Additionally, `link_with` will be a much pretty way.

**Comment by Changzw** [comment]
@manuqiao  would you tell me the detail, how to solve it

**Comment by Changzw** [comment]
I find the issue again, Xcode 9

**Comment by manuqiao** [comment]
@Changzw It has been a long time. I think it was 1 pod to multi targets problem, was it? If yes, try this:
`abstract_target :'ProjectName' do`
`Pod "AFNetworking"`
`target 'target1'`
`target 'target2'`
`target 'target3'`

**Comment by Changzw** [comment]
I did it in this way ……
