### ISSUE TITLE
Specify development pods outside of the Podfile

### ISSUE THREAD

**Issue by irace** [CocoaPods/CocoaPods#2672]
Say there's an internal pod that we depend on in our organization, and I'm going to be working on it for an extended period of time. I'd clone the pod's repo and modify my Podfile to point to this local clone, run `pod install`, and I'd have a development pod that I can work on in conjunction with our app itself.

The problem here is that it's a pain to _not_ commit these Podfile changes over a long enough period of time, especially when I may be making other changes to the Podfile that I _do_ want to commit, or will be pulling down changes made from my teammates that may result in merge conflicts.

What are your thoughts on adding something like a **Podfile.dev** – a separate file that can be added to `.gitignore` and will be favored over Podfile when both are present? This would allow one to configure their development pods separately while still keeping the Podfile in sync with the rest of their teammates?

**Comment by brianpartridge** [comment]
Wasn't sure whether to put this here or in #1010. 

It looks like the change in #3540 could be leveraged by a plugin to implement this by overwriting the parsed podfile's pods with local paths.  It may need a `post_resolve_dependencies` step to prevent collisions between the explicit and implicit dependencies. Thoughts?

**Comment by shepting** [comment]
I would love to see this happen.

**Comment by neonichu** [comment]
@shepting feel free to submit a pull request

**Comment by msfeldstein** [comment]
Would it make sense to allow users to specify an optional path, which if it exists is used, and if it doesn't exist falls back to the remote pod source?

ie `pod 'AFNetworking', :path => '../AFNetworking'` would use the local directory if the user has AFNetworking checked out next to the current project and if not, is fetched from AFNetworkings github repo?

This is a really tough problem for projects with more than 1 person.

**Comment by segiddins** [comment]
@msfeldstein you can already emulate that yourself using ruby code in your podfile

**Comment by msfeldstein** [comment]
Something like this?

```
def localpod(name, properties)
  if !Dir.exists?(properties[:path])
    properties.delete(:path)
  end
  pod name, properties
end

localpod 'GPUImage', :path => "../GPUImage"
```

**Comment by fatuhoku** [comment]
+1

I want to model the layers of 'onion architecture' as my own Pods. However, I want them ALL to be development pods, as I do not need to share work with a team.

In a `Podfile` for `MyKit`:
```
  pod 'MyFoundation', :path => '../MyFoundation'
```

In `MyKit.podspec`

```
  s.dependency 'MyFoundation'
```

The error on `pod install`:

```
Updating local specs repositories
Analyzing dependencies
[!] There are multiple dependencies with different sources for `MyFoundation` in `Podfile`:

- MyFoundation (from `../MyFoundation`)
- MyFoundation
```

Really counter-intuitive and frankly wrong. The only place I could specify the source was in the `Podfile` and yet it causes a clash.

**Comment by Whirlwind** [comment]
Anybody can tell me how to solve the `multiple dependencies with different sources`? same with @fatuhoku

**Comment by segiddins** [comment]
So I spent some time thinking about this, and the issue I'm still facing is how to properly handle not clobbering the lockfile when the dev overrides are being used...

**Comment by Whirlwind** [comment]
I think when I want to use a dev pod, the pod's version is meaningless, so the dev show override all version in some podspecs and the podfile.lock.

**Comment by segiddins** [comment]
Exactly. That's not easy to implement, I'm not even sure how we can do it.

**Comment by Whirlwind** [comment]
⊙▂⊙

**Comment by Whirlwind** [comment]
After check the `analyzer.rb`, I think if the dependency have a external source, we can ignore the version requirements. The external source seem that only have one ( in the Podfile)

**Comment by Whirlwind** [comment]
@segiddins 
I try to modify the CP code  in analyzer.rb L440 (https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer.rb#L440).
change to 
```
          select { |_root_name, dependencies| dependencies.map(&:external_source).select {|source| !source.nil? }.count > 1 }
```
It seem to work.

**Comment by kam800** [comment]
@Whirlwind could you please make a pull request with this change? :)

**Comment by Whirlwind** [comment]
@kam800  The code just works without test it.

I hope the owner can check this idea and make a better way to fix this issue.

**Comment by irace** [comment]
Found another need for this. I’d like to use a development pod locally, but in source control I want my Podfile to be pointing to the remote version of the library, such that my CI system isn’t impacted by the fact that I’m using a development pod locally.

**Comment by segiddins** [comment]
@irace PRs welcome ;)
It's highly unlikely at this point anyone on the core team will add this feature, as none of us have needed it (just not committing changes has been sufficient) and there are far more pressing issues.

**Comment by neonichu** [comment]
I think we can close this, PRs are still welcome, though.
