### ISSUE TITLE
Separate public spec validation options

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#2682]
We don't need to validate certain attributes of specifications if they are private.

I think we can provide a `--private` option to the linter for private specs.

The following rules could be disabled:

- source
- homepage
- screenshot_urls
- docset_url
- documentation_url

**Comment by Ashton-W** [comment]
Just wanted to add (related issues have been closed and link to this issue). A new `private` attribute in the `podspec` would be easier when working with both public and private specs.

Rubygems has `allowed_push_host` which serves a similar purpose:
```ruby
Gem::Specification.new 'my_gem', '1.0' do |s|
  # ...
  s.metadata['allowed_push_host'] = 'https://gems.my-company.example'
end
```
