### ISSUE TITLE
Friendly UI for lint private pods with dependencies from a private repository

### ISSUE THREAD

**Issue by pablocarrillo** [CocoaPods/CocoaPods#2685]
The Cocoapods Team is making a fantastic work and the tool is really amazing. So I start using cocoapods more in deep and found surprisingly hard to check a podspec before submission for my own libraries.

IMO the repos should be included on the podspec file. Makes sense you state there how to resolve dependencies and not in the CLI. 
Also would be nice to accept in the CLI the repo names instead of the http address, it is really a hack to write something like:
```
pod spec lint --sources=https://bitbucket.org/boringlonguser/boringlongSpec/Specs,https://github.com/CocoaPods/Specs.git
```

When could be
```
pod spec lint --sources=MyPodSpecRepo,master
```

or even better
```
pod spec lint
```

And have a line like this in the spec file:
```
s.repo_source='https://bitbucket.org/boringlonguser/boringlongSpec/Specs'
s.repo_source='https://github.com/CocoaPods/Specs.git'
```

Finally when generate the podspec you can include the one for master by default.

Thanks again for your amazing job.

**Comment by wangweijia** [comment]
why  `pod repo push` uses all sources,but `pod repo lint` not
