### ISSUE TITLE
Linker "duplicate symbol" error  (0.34.4)

### ISSUE THREAD

**Issue by mattrubin** [CocoaPods/CocoaPods#2705]
As of 0.34.4, building our project results in many "duplicate symbol" errors from the linker. The problem is that we include the same AFNetworking pod in both our main app target and in a custom static library target included in our app. The pod file looks something like this:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

pod 'AFNetworking', '1.3.2'
(...other pods...)

target 'Library', :exclusive => true do
    pod 'AFNetworking', '1.3.2'
end
```

This issue did not exist in 0.34.2.

**Comment by SandyChapman** [comment]
If you need to prevent linking an additional library (to prevent duplicate symbols), you can use a post_install hook like this:

    post_install do |installer_representation|
        targets = ['Targer0', 'Target1', Target2']
        targets.each do |target|
            Dir["./Pods/Target\ Support\ Files/Pods-#{target}/*.xcconfig"].select { |f|
                text = File.read(f)
                new_contents = text.gsub(/-l"Pods-#{target}-PodToNotLink"/, "")
                File.open(f, "w") {|file| file.puts new_contents }
            }
        end
    end

It'd be great to have an addition to the pod command however that just stops the library link argument from being added to the xcconfig in the first place.

I.e.

    target 'MyTarget' do
        pod 'PodToNotLink', '~> 1.0.0', :unlinked
    end

**Comment by segiddins** [comment]
@SandyChapman I'm going to be working on a new Podfile DSL that will indeed make exposing only headers works.

**Comment by SandyChapman** [comment]
@segiddins Looking forward to it :)
