### ISSUE TITLE
inhibit_all_warnings! passes "-a" flag to Flex, thus breaking the build process

### ISSUE THREAD

**Issue by Zi0P4tch0** [CocoaPods/CocoaPods#2716]
Cocoapods appears to add the "-a" flag to **\*.lm** (Flex) sources when **inhibit_all_warnings!** is defined.

This breaks the build process

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/flex: Unrecognized option `a'

I haven't tested it, but It might sensible to have a look at **\*.ym** (Bison) sources as well.

**System specs:**

- OSX 10.10 Yosemite
- Ruby 2.1.3 (through RVM)
- Cocoapods 0.34.4
- Xcode 6.1

**To reproduce:**

Create an empty iOS project.
Use this podfile (installs my pod which contains **\*.lm**,**\*.ym** files in a subspec)

    source 'https://github.com/CocoaPods/Specs.git'

    inhibit_all_warnings!

    pod 'iHOCON' 

Try to build the project now. You should get a red dot.

**Comment by segiddins** [comment]
I'm pretty sure we fixed this in a recent release?

**Comment by segiddins** [comment]
Closing due to lack of response.
