### ISSUE TITLE
The file “Pods-acknowledgements.plist” couldn’t be opened because there is no such file.

### ISSUE THREAD

**Issue by boboRAY** [CocoaPods/CocoaPods#2717]
Hi : 
I just clean install my Mac to OS X 10.10 and using cocoa pods 0.34.4 and  Xcode 6.1
I clone my project from Github, which i used to run successfully

but after pod install and build i got this error message on Xcode
~/Projects/gomore-ios/Pods/AcknowledgementsBundle/Pods-acknowledgements.plist:0: error: reading data: The file “Pods-acknowledgements.plist” couldn’t be opened because there is no such file.

**Comment by bcyng** [comment]
add the following in your Podfile around the dependencies
add target "Kickflip" do
...
end

then relink your acknowledgements file in Xcode. you'll have to search for it as its moved.
