### ISSUE TITLE
Should pods be binary or source?

### ISSUE THREAD

**Issue by dodikk** [CocoaPods/CocoaPods#2731]
Created a new thread since it has been considered as off topic in #2729

**Comment by orta** [comment]
Alright, I'm closing this, since this was discussed other platforms have come that fit the mental model you're talking about for cocoa dependencies. Also, someone could build this as a cocoapods plugin so it works for everyone with a few days worth of side-project time.

**Comment by koxon** [comment]
Being new to IOS builds, I have to say I was very surprise of the compilation time. 
Changing compilers parameters sounds irrelevant as the hardware is tightly controlled. 

On the other hand, speeding up CI systems, auto builds and local tests is certainly a big plus. 
Like other dependency systems, shipping binaries should be the default behavior.
