### ISSUE TITLE
Build fails if libPods.a is removed from "Link Binary with Libraries" on static library target

### ISSUE THREAD

**Issue by themackworth** [CocoaPods/CocoaPods#2747]
This is related to #2704 but I decided to open a new issue since I think #2704 might be slightly different.  Feel free to delete this if you think they are too similar.

*Versions:*

Xcode 6.1
Cocoapods 0.34.4

Sample: https://github.com/themackworth/Cocoapods2704

*Steps to reproduce:*

Clone Repo
Open ProjectB.xcworkspace
Build Project

*Error:*

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified the following flags are invalid: -ObjC -ObjC 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-ProjectA
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-ProjectA is not an object file (not allowed in a library)

*Use Case:*

We build a series of static library projects.  We have one static library that contains the core to our SDK. We then have 6 other static library plugins that can be used in conjunction with the core. Because we want to be able to allow people to use different combinations, we remove libPods.a from link with binary build phase on the plugins so that it doesn't compile the core in.

Our workflow is usually to use `pod install` to generate the workspace, and then `pod update --no-integrate` to update pods when we need to.  Is this what we should be doing?

*Cause:*

It seems that the addition of `OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)` when libPods.a isn't in the "link binary with Libraries" phase, causes the build to fail.  

```
OTHER_LDFLAGS = -ObjC -l"Pods-ProjectA" -framework "AVFoundation" -framework "CoreMedia" -framework "MediaPlayer"
OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)
```

Removing `OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)` fixes the problem, but obviously that is needed if someone is building an app w/ xcode 6.

It would be nice if there was the do_not_integrate attribute discussed in #840 so that we could pick and choose what pods get added to OTHER_LIBTOOLFLAGS.

**Comment by themackworth** [comment]
@alloy Is this change as simple as just removing https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb#L53 and the corresponding tests and adding a release note item?

**Comment by neonichu** [comment]
@themackworth Everything that needs to be changed should be contained in this commit: a8645c6f3a3fe124e186678065e84a3821275ac1

**Comment by themackworth** [comment]
@neonichu I will try and put a pull request together this weekend to get the ball rolling.

It looks like most of https://github.com/CocoaPods/cocoapods-integration-specs/commit/53ea4d612b91c0e3be195a0e75b32bdefb2574d2 needs to be reverted also.

**Comment by quentinfasquel** [comment]
This seem closed but I can't figure what's the fix.. thank you?

**Comment by neonichu** [comment]
@quentinfasquel nope, this is still an open issue.

**Comment by a83988029** [comment]
then why it is not a problem of version of 0.34.1

**Comment by neonichu** [comment]
@a83988029 The version of libtool that ships with Xcode 6 is different, which lead to changes in CP.

**Comment by a83988029** [comment]
@neonichu fine,i'll see if this https://github.com/matehat/Objective-LevelDB/commit/d8733b4cddd765d22716cc67def13101e3c10ebb works

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/issues/3677.

**Comment by VenuKotha** [comment]
i am receiving below error if i create a static lib using cocoa pod with Reachability dependency
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-MZNetworkManager


error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-MZNetworkManager is not an object file (not allowed in a library)


As above discussions i did not get OTHER_LIBTOOLFLAGS in .xcconfig.
Please help to me to resolve this error and it is very urgent for me.
Thank you very much for your help
