### ISSUE TITLE
Integrating xcconfig files into a user's project that has no base configurations yet can fail.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#2752]
When using `link_with` to link into a second target and that target does not have a base configuration yet, [this](https://github.com/CocoaPods/CocoaPods/blob/e1022c5de3a9953ef32d4cabe00dfd366c7c21c4/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb#L90) code will raise a warning.

I have a local fix for this, just need to look at the tests first and if I’m overlooking anything else.

---

This can be seen in this code+branch: https://bitbucket.org/alloy020/gba4ios/branch/issue%2F7. Remove e.g. the `Pods.debug.xcconfig` from the GBA4iOS-Simulator target:

![screen shot 2014-10-29 at 14 17 18](https://cloud.githubusercontent.com/assets/2320/4826219/fdd0493a-5f6d-11e4-85bb-042cd29e9824.png)

And run `pod install`:

```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `GBA4iOS-Simulator` to `Pods/Target Support Files/Pods/Pods.debug.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.debug.xcconfig` in your build configuration.
```

**Comment by shalomfriss** [comment]
worked for me, I have a lot of configurations, I set all of them to none, ran pod install, warnings are gone
