### ISSUE TITLE
Not a clean project

### ISSUE THREAD

**Issue by adamrushy** [CocoaPods/CocoaPods#2753]
I am running a private pod. Spec has been created and I am running this command;

pod repo push WHCore WHCore.podspec --verbose

However right at the last minute spits this out;

*\* BUILD SUCCEEDED **

 -> WHCore (0.0.1)

[!] The repo `WHCore` is not clean

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/repo/push.rb:109:in `check_repo_status'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command/repo/push.rb:43:in`run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in`run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in`load'
/usr/bin/pod:23:in `<main>'

**Comment by dismory** [comment]
```ruby
clean = Dir.chdir(repo_dir) { `git status --porcelain  2>&1` } == ''
```
The validation here is not reliable if the user prefixes the `pod` command with [`proxychains`](https://github.com/rofl0r/proxychains-ng) command since it outputs extract log like `[proxychains] DLL init` stdout

**Comment by meigesir** [comment]
@dismory I have encountered this problem，thanks

**Comment by walker-ll** [comment]
i have deleted the repo and add repo, it's resolved!

**Comment by matheusvdesousa** [comment]
Had the same problem here. Thanks for the help :)

**Comment by yihuds** [comment]
> Doh! It’s complaining about the spec-repo to which you are trying to push the spec. My bad.
> 
> So if you change to `~/.cocoapods/repos/WHCore` and run `git status` there, it should probably show the real issue.

great, thanks.

**Comment by lakshmi-pri** [comment]
I have this problem too.

built successfully.

But it throws error.
[!] The repo `PodSpec` at `..` is not clean.
What I do? 

Please help me :(

**Comment by pranav21keshav** [comment]
Thank you so much @adamrushy and @alloy 
I faced this issue and because of your question and and answer it got resolved. 
Thank you
