### ISSUE TITLE
libtool: unknown option character `X' in: -Xlinker

### ISSUE THREAD

**Issue by tychop** [CocoaPods/CocoaPods#2764]
Any news on this build error? Last I read was that swift pods were not yet possible.
I see some cocoapods written in swift, so it must be possible to use swift in a pod now.

So what can I do to get over the Xlinker problem...?

(Using 0.34.4)

**Comment by skywinder** [comment]
@alloy Any updates? It seems, that pre-release version (` gem install cocoapods --pre`) should support swift. But I'm still get this error.
