### ISSUE TITLE
Podspec value for spec.libraries should not be added to OTHER_LIBTOOLFLAGS

### ISSUE THREAD

**Issue by kanstantsin** [CocoaPods/CocoaPods#2765]
I've encountered an issue while building static library target which depends on a pod with dynamic library dependencies. That's needed for running tests on the library.
In this case cocoapods add these dynamic libraries flags to my static library's OTHER_LD_FLAGS which is copied to OTHER_LIBTOOLFLAGS, which produces errors like this:
```error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lsqlite3```
while build.

This happens because dynamic libraries should only be linked to the app, and should not be linked to static library.
So, values, specified in spec.libraries should go to OTHER_LD_FLAGS but not to OTHER_LIBTOOLFLAGS.

[Here](https://github.com/kanstantsin/LibTestCocoapodsFailure/tree/master/Libtool) is the sample project to demonstrate the issue.
Replacing
```pod 'AFNetworking'```
with
```pod 'AFNetworking', :podspec => '.'```
and running ```pod install``` or ```pod update``` reproduces that.

**Comment by BamX** [comment]
Will this issue be solved?

**Comment by segiddins** [comment]
This was fixed by https://github.com/CocoaPods/CocoaPods/pull/3677.
