### ISSUE TITLE
SystemStackError - stack level too deep

### ISSUE THREAD

**Issue by ButtFly** [CocoaPods/CocoaPods#2770]
Analyzing dependencies
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 0.35.0.rc1
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.10 (14A389)
       Xcode : 6.1 (6A1052d)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /usr/local/Cellar/ruby/2.1.2_3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 39ac06d5fa610a08167342b866ab2f11c7a41703
```
### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.2
```
### Podfile

``` ruby
# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "Honor" do

pod 'AFNetworking'
pod 'pop'
pod 'XMLDictionary'
pod 'ZipArchive'
pod 'SVPullToRefresh'
pod 'RMMapper'
pod 'MGSwipeTableCell'
pod 'PureLayout'
end

target "HonorTests" do

end
```
### Error

```
SystemStackError - stack level too deep
/usr/local/lib/ruby/gems/2.1.0/gems/xcodeproj-0.20.1/lib/xcodeproj/project/object_attributes.rb:139
```

**Comment by derjohng** [comment]
I met the same issue today. 
Some article mentioned remove the targets of extensions(widget) will fixed this. 
It really works after I remove targets.
However, I need the targets.... >"<

I waste the whole day to find the solution, and still no luck....
