### ISSUE TITLE
Pod with tag incorrectly resolves to branch

### ISSUE THREAD

**Issue by jhersh** [CocoaPods/CocoaPods#2775]
I have this line in my `Podfile`:

``` ruby
pod 'ARAnalytics/GoogleAnalytics', :git => 'https://github.com/orta/ARAnalytics', :tag => '2.9.0'
```

In both `0.34.4` and `0.35.0.rc1`, this tag is incorrectly resolved to be a branch and the install fails, even though it seems to realize that I am referencing a tag:

``` bash
[0] % pod install
Analyzing dependencies
Pre-downloading: `ARAnalytics` from `https://github.com/orta/ARAnalytics`, tag `2.9.0`
[!] /usr/bin/git clone https://github.com/orta/ARAnalytics /Users/jhersh/Dev2/mudrammer/src/Pods/ARAnalytics --single-branch --depth 1 --branch 2.9.0

Cloning into '/Users/jhersh/Dev2/mudrammer/src/Pods/ARAnalytics'...

warning: Could not find remote branch 2.9.0 to clone.

fatal: Remote branch 2.9.0 not found in upstream origin

Unexpected end of command stream
```

**Comment by keith** [comment]
I ran across this today when someone accidentally pushed a branch with the same name as a tag to the repo, unfortunately the branch pointed to entirely different sources than the tag. I think it might be worth making sure we're only checking out tags in this case. In theory if force pushing tags also was restricted, this would be an attack vector for swapping out the sources of a pod without the consumer knowing (assuming the changes were intentionally subtle).

**Comment by segiddins** [comment]
> I ran across this today when someone accidentally pushed a branch with the same name as a tag to the repo, unfortunately the branch pointed to entirely different sources than the tag.

I don't think there's anything we can do, since git doesn't have any other way to specify a tag to clone

**Comment by keith** [comment]
Here's one option for that, although I agree it's definitely not ideal that you would lose shallow clones https://github.com/CocoaPods/cocoapods-downloader/pull/72

**Comment by Buzz-Lightyear** [comment]
@jhersh Have you since had issues with using tags in Podspecs?

**Comment by tigerAndBull** [comment]
This bug still exists.
