### ISSUE TITLE
:inhibit_warnings => true doesn't work on subspecs

### ISSUE THREAD

**Issue by benzguo** [CocoaPods/CocoaPods#2777]
Reproducible on a new project (v0.34.4):
https://github.com/benzguo/cocoapods-inhibitwarnings-subspec

Warnings are still emitted using this line:
```
pod 'FormatterKit/TimeIntervalFormatter', '~> 1.5.0', :inhibit_warnings => true
```

No warnings with this line:
```
pod 'FormatterKit', '~> 1.5.0', :inhibit_warnings => true
```

**Comment by adc-amatosov** [comment]
Issue still exists in version 0.35.0

**Comment by benzguo** [comment]
:bow: @segiddins
