### ISSUE TITLE
Pods xcconfig misses ${inherited} for HEADER_SEARCH_PATHS and OTHER_LDFLAGS

### ISSUE THREAD

**Issue by fabb** [CocoaPods/CocoaPods#2781]
I have a custom `xcconfig` for each build config. The pods `xcconfig` are applied at a lower level, i.e. overwrite the configs of the build config `xcconfig`. So if cocoapods misses `${inherited}` for one of the settings, it ignores the settings in the build config's `xcconfig`.
This is the case for `HEADER_SEARCH_PATHS` and `OTHER_LDFLAGS`. They should contain `${inherited}`.

**Comment by erikjalevik** [comment]
Just ran into this too. OTHER_C_FLAGS uses $(inherited), why not OTHER_LDFLAGS too?

**Comment by segiddins** [comment]
I believe we've fixed this as of the latest 0.39 betas.
