### ISSUE TITLE
Can't use live rendering with custom views in generated Pods project

### ISSUE THREAD

**Issue by qLag** [CocoaPods/CocoaPods#2792]
I have some custom views flagged IB_DESIGNABLE in the Pods project, but XCode can't use them for live rendering. Should I do something special ?

**Comment by qLag** [comment]
Using Cocoapods 0.36 beta 1, I have this warning when i try to use live rendering : 

warning: IB Designables: Ignoring user defined runtime attribute for key path "myBackgroundColor" on instance of "UIView". Hit an exception when attempting to set its value: [<UIView 0x7fdd41c19980> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key myBackgroundColor.

"myBackgroundColor" is a IBInspectable UIColor property declared in the "MyTextField" class (that inherits UIControl). MyTextField is declared as "IB_DESIGNABLE"  and it's part of a CocoaTouch Framework that i use in my App as a dependency with cocoapods. 

Should i do something special ?

**Comment by ZevEisenberg** [comment]
Is the UiView in IB set up as an instance of MyTextField?

**Comment by qLag** [comment]
Yes :/ 

See my example project with a simple Cocoa Touch Framework called "MyFramework". It contains a simple "MyTextField" class that is designable and has one inspectable property (for the background color of the inner textfield of MyTextField). 

My simple application called "MyApp" (here in Swift but I get the same problem when MyApp is in ObjC), use cocoapods to retrieve "MyFramework" into MyApp workspace. Okay good. But when i want to use Live rendering on MyTextField (you can se Main.storyboard, i dragged a UIView with "MyTextField" as a custom class), i get alternatively a warning  " Ignoring user defined runtime attribute for key path "myBackgroundColor" on instance of "UIView". Hit an exception ....." or an error : "IB Designables: Failed to update auto layout status: Failed to load designables from path (null)" ...

See my example here : https://github.com/qLag/ctfwithpods 

Thx.

**Comment by sashagood** [comment]
Have the same issue.

**Comment by neonichu** [comment]
You need to specify `use_frameworks!` in your Podfile to actually use frameworks. Otherwise, the integration via static libraries is used.

**Comment by qLag** [comment]
Ok Thank you. I did not see this option because is searched doc in wrong places (on cocoapods blog, issues about v0.36, podfile guide syntax page...). It works great now, thanks again

**Comment by qLag** [comment]
Last message in order to thank you. 
With your help combined to this post : http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

i've been able to transform my project as a Cocoa Touch Framework. By using Cocoapods v0.36 Beta 1, my custom components in my CTFramework are now visible in Interface Builder with LiveRendering. Thanks again for your support :+1:

**Comment by Fl0p** [comment]
Any other solution ? except ```use_frameworks``` ?
I can't use it because of other error
```The 'Pods-App' target has transitive dependencies that include static binaries: %a list of pods with static libs%```

Can we add some changes in project structure and settings to show IB path to a fake module ??

**Comment by BigSauce** [comment]
@neonichu, where exactly should `use_frameworks` be specified in the podfile?

**Comment by neonichu** [comment]
See http://guides.cocoapods.org/syntax/podfile.html#use_frameworks_bang

**Comment by joshuatbrown** [comment]
@BigSauce I'm not seeing the answer to your question in @neonichu's response - so... [This SO answer](http://stackoverflow.com/a/28907253/2030) says the `use_frameworks!` line should go right after the `platform` line.

**Comment by kylef** [comment]
@joshuatbrown It doesn't matter where it goes, as long as it's either in the target you want to integrate as a framework or in the root of the Podfile.
