### ISSUE TITLE
There was a problem validating the URL

### ISSUE THREAD

**Issue by nyssance** [CocoaPods/CocoaPods#2795]
`pod spec lint`

always 'There was a problem validating the URL'

no matter which URL,  ever
s.homepage     = 'https://cocoapods.org'
or
s.homepage     = 'https://github.com'

**Comment by evanspa** [comment]
For what it's worth, I JUST started getting this same 'There was a problem validating the URL' error when linking my podspec.  I have verified that my pod spec's homepage URL is fine.  Here's a snippet of the output of running "pod spec lint --verbose"

```
** BUILD SUCCEEDED **

 -> PEDev-Console (1.0.0)
    - WARN  | There was a problem validating the URL https://github.com/evanspa/PEDev-Console.
    - NOTE  | [iOS] [xcodebuild]  KissXML/KissXML/DDXMLDocument.m:94:47: warning: implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]

Analyzed 1 podspec.

[!] The spec did not pass validation.

/Users/nbkjmov/.gem/ruby/2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/command/spec.rb:112:in `run'
/Users/nbkjmov/.gem/ruby/2.2.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/nbkjmov/.gem/ruby/2.2.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/nbkjmov/.gem/ruby/2.2.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/nbkjmov/.gem/ruby/2.2.0/bin/pod:23:in `load'
/Users/nbkjmov/.gem/ruby/2.2.0/bin/pod:23:in `<main>'
```

**Comment by OliverDimitrov** [comment]
I can also confirm this issue. Although the site is working as it should, the pod spec lint just won't pass.

**Comment by hemangshah** [comment]
+1

**Comment by nabbestemmia** [comment]
"Happy" to see that I'm not the only one to have this problem

**Comment by mll** [comment]
+1

**Comment by mll** [comment]
This helps: https://stackoverflow.com/questions/38993527/cocoapods-failed-to-connect-to-github-to-update-the-cocoapods-specs-specs-repo
