### ISSUE TITLE
There is no way to put NDEBUG=1 in release.xcconfig

### ISSUE THREAD

**Issue by haifengkao** [CocoaPods/CocoaPods#2810]
I tried to add `NDEBUG=1` to disable `assert` in the release config.
However, I noticed that it's only possible to disable assert in both release and debug configs by using 

```
s.xcconfig = {"GCC_PREPROCESSOR_DEFINITIONS"=> '$(inherited) NDEBUG=1' }
```

How do I add the definition to the release config only?
.

**Comment by segiddins** [comment]
That's not something that CocoaPods really needs to support. You can do that on your own by checking

```objc
#ifndef DEBUG
#define NDEBUG 1
#endif
```

**Comment by haifengkao** [comment]
It doesn't solve my problem because I cannot change third-party pods.  
CocoaPods needs to support different configs for release and debug build.
Does that make sense to you?
