### ISSUE TITLE
[Discussion] Improve error reporting 🌈

### ISSUE THREAD

**Issue by AliSoftware** [CocoaPods/CocoaPods#2812]
By reading CP GitHub issues, I see that a lot of people:

* **Don't read the [CONTRIBUTING](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) guide** before posting (attempt to fix by 3a61c4a265d97c41bff17a2c3aeea878f228041b but still lost in a too long output)
* **Don't search for an existing issue** before creating a new one (probably because the suggested search is not agnostic enough to pointers, pod names, etc
* **Don't use the markdown template properly** when pasting it into github (missing to copy the triple-backticks for example, making it unformatted and difficult to read, or copying everything instead of only what is between the markers, etc)

Especially, **I believe [the exception output is too long](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/user_interface/error_report.rb) and thus shadows the important messages that the user should read**. Having the whole, long markdown template output makes important messages (like "please read the CONTRIBUTING guide" or "search for existing issues") hidden to the user.

This discussion is to see what can be done to improve the matter. /cc @CocoaPods/core

**Comment by segiddins** [comment]
Closing this due to lack of an actionable conclusion, and a desire (on my part) to keep the error report as-is, since it's incredibly useful for fixing bugs.
