### ISSUE TITLE
Source files that are used in multiple subspecs can end-up being compiled twice.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#2813]
```Podfile
pod "ARAnalytics/GoogleAnalytics"
pod "ARAnalytics/DSL"
```

Will add `ARAnalyticalProvider.m` and `ARAnalytics.m` to the compile phase twice:

![screen shot 2014-11-12 at 10 13 48](https://cloud.githubusercontent.com/assets/2320/5007740/397e1fce-6a55-11e4-9400-0fafd903d5ab.png)

Whereas they _are_ excluded from the `DSL` group, which it would be in if the `GoogleAnalytics` subspec is removed from the Podfile:

![screen shot 2014-11-12 at 10 14 45](https://cloud.githubusercontent.com/assets/2320/5007750/577c1436-6a55-11e4-8a98-995bd983d108.png)

**Comment by segiddins** [comment]
Pretty sure this was fixed recently?

**Comment by orta** [comment]
Yeah, I took a stab at it, then I think someone else, maybe you, did it.

**Comment by segiddins** [comment]
Yup :) Closing.
