### ISSUE TITLE
CocoaPods adds incorrect Other Linker Flags

### ISSUE THREAD

**Issue by macdonjo** [CocoaPods/CocoaPods#2833]
I placed `$(inherited)` in Other Linker Flags in the Build Settings of my app. Now, it's causing an error, but adding a Test framework.

The error and solution are explained in detail here: http://stackoverflow.com/questions/20340763/xcode-5-0-2-dyld-library-not-loaded-rpath-xctest-framework-versions-a-xctest

How can I modify the Other Linker Flags added by CocoaPods to ensure the XCTests does not get added?

**Comment by michaelknoch** [comment]
did you find a solution for this? i'm facing the same issue right now. @macdonjo
