### ISSUE TITLE
what's the mean of link_with in Podfile?

### ISSUE THREAD

**Issue by zixun** [CocoaPods/CocoaPods#2842]
AFNetworking's Podfile shows that:

``` objective-c
source 'https://github.com/CocoaPods/Specs'

xcodeproj 'AFNetworking Tests'
workspace '../AFNetworking'
inhibit_all_warnings!

def import_pods
  pod 'OCMock', '~> 2.1.1'
  pod 'Expecta', '~> 0.2.1'
  pod 'AFNetworking', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end
```

what's the meaning of link_with? and link_with always write in the first line:

``` objective-c
link_with ['Proj', 'ProjTests']

platform :ios, 6.0

pod 'Reachability', '3.1.1'
pod 'SVProgressHUD', '0.9'
pod 'FMDB', '2.1'
```

that's the different?

**Comment by adil-hussain-84** [comment]
@segiddins The documentation says:

> TODO: This method can be deleted once people have migrated to this 1.0 DSL.

What does that mean?!

**Comment by orta** [comment]
It means that we're deleting the `link_to` in a version after 1.0 is released. http://blog.cocoapods.org/CocoaPods-1.0/

**Comment by adil-hussain-84** [comment]
Okay. Thanks.

**Comment by wodow** [comment]
Archive.org has it at https://web.archive.org/web/20151230070422/http://guides.cocoapods.org/syntax/podfile.html#link_with

**Comment by ooopscc** [comment]
@wodow Thanks. I have read this document but still have no idea that where to put it, that simple example should show more context and its rules.
