### ISSUE TITLE
Debug and Release vendor library in one podspec

### ISSUE THREAD

**Issue by oemera** [CocoaPods/CocoaPods#2847]
We want to use CocoaPods to manage a private vendor library we need to use. This vendor ships 2 libraries in every release. One of them is for production use (release or app store environment) and the other is for debugging purposes. Lets say they are called 'lib123.a' and 'lib123debug.a'

I tried different approaches but couldn't find a solution which fits our needs. We need to include the release library in the Release configuration and the debug library in the Debug configuration. I know that you can import different pods for different configurations like this:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

target 'TestApp' do
  pod 'sdk-ios-debug', :git => 'git@github.com:whatever/sdk-ios.git', :tag => '2.6.9', :configurations => ['Debug']
  pod 'sdk-ios', :git => 'git@github.com:whatever/sdk-ios.git', :tag => '2.6.9', :configurations => ['Release', 'AppStore']
end
```

The SDK has two podspecs with different names:

```
Pod::Spec.new do |s|
  s.name                    = 'sdk-ios'
  s.version                 = '2.6.9'
  s.license                 = 'Commercial'
  s.summary                 = '..'
  s.description             = '..'
  s.source                  = { :git => 'git@github.com:whatever/sdk-ios.git', :tag => '2.6.9' }
  s.platform                = :ios, '7.0'
  s.source_files            = "*.h"
  s.ios.vendored_library    = 'lib123.a'
  s.ios.framework           = 'SystemConfiguration', 'ExternalAccessory', 'Security'
  s.ios.libraries           = 'z', 'iconv', 'bz2', 'c++'
end
```

```
Pod::Spec.new do |s|
  s.name                    = 'sdk-ios-debug'
  s.version                 = '2.6.9'
  s.license                 = 'Commercial'
  s.summary                 = '..'
  s.description             = '..'
  s.source                  = { :git => 'git@github.com:whatever/sdk-ios.git', :tag => '2.6.9' }
  s.platform                = :ios, '7.0'
  s.source_files            = "*.h"
  s.ios.vendored_library    = 'lib123debug.a'
  s.ios.framework           = 'SystemConfiguration', 'ExternalAccessory', 'Security'
  s.ios.libraries           = 'z', 'iconv', 'bz2', 'c++'
end
```

But this approach doesn't work quite well because I need to <code>#import \<sdk-ios-debug/SdkiOS.h\></code> or <code>#import \<sdk-ios/SdkiOS.h\></code>.

What could I do to get it right? My next idea would be to have one podspec for this vendor library and remove libraries for the given stages in the <code>pod_install</code> hook. For example:

```
Pod::Spec.new do |s|
  s.name                    = 'sdk-ios'
  s.version                 = '2.6.9'
  s.license                 = 'Commercial'
  s.summary                 = '..'
  s.description             = '..'
  s.source                  = { :git => 'git@github.com:whatever/sdk-ios.git', :tag => '2.6.9' }
  s.platform                = :ios, '7.0'
  s.source_files            = "*.h"
  s.ios.vendored_library    = 'lib123.a', 'lib123debug.a'
  s.ios.framework           = 'SystemConfiguration', 'ExternalAccessory', 'Security'
  s.ios.libraries           = 'z', 'iconv', 'bz2', 'c++'
end
```

**Comment by Speakus** [comment]
just suggestion:
Create two frameworks (debug + release) instead of two libraries + use vendored_frameworks + use two separate podspec (as you do now) - it allow to use one #import <sdk-ios/SdkiOS.h>

**Comment by segiddins** [comment]
Closing this as a wontfix, since I see no way of doing this that wouldn't involve an inordinate amount of complexity.

**Comment by revolter** [comment]
I noticed that CocoaPods modified the `Pods-Target-frameworks.sh` to include:

```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_framework "${PODS_ROOT}/PrivatePodName/Frameworks/PrivatePodName.framework"
fi
if [[ "$CONFIGURATION" == "Staging" ]]; then
  install_framework "${PODS_ROOT}/PrivatePodName/Frameworks/PrivatePodName.framework"
fi
if [[ "$CONFIGURATION" == "Release" ]]; then
  install_framework "${PODS_ROOT}/PrivatePodName/Frameworks/PrivatePodName.framework"
fi
```

where it installs the same `.framework`. But it looks like it could also install a different `.framework` depending on the main app's configuration somehow, but I can't find a way to create the `.podspec` in order to achieve this.

**Comment by CodeLife2012** [comment]
Any update?

**Comment by heltonrosa** [comment]
Hello @Speakus! If you still hear us, could you please explain with more details how did you build both .podspec files? How did you referenced both frameworks on vendored_frameworks, what differences do they have to have,  please?

**Comment by revolter** [comment]
I personally ended up creating 2 podspecs, one with the suffix `Debug`, which vendored `"#{MAIN_POD_NAME}/Frameworks/Debug/#{MAIN_POD_NAME}.framework"`, where `MAIN_POD_NAME` is the name of the pod, without the suffix.
