### ISSUE TITLE
Use OS X sandboxing revisited.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#2848]
This ticket supersedes #939 and limits its scope.

Now that the master spec-repo only contains JSON specs, there is already no way to have any Ruby code injection, so the only things we need to worry about are commands that are performed during installation.
- [ ] Change how all external commands are called from a single string to an array of command and arguments so that no intermediate shell is used anymore.
- [ ] Pass commands through `sandbox-exec` and define rule-sets like the following:
  - [ ] Only allow downloaders to access the network.
  - [ ] Only allow downloaders to use certain commands (e.g. `git`).
  - [ ] Only allow downloaders to write to the destination directory, e.g. `Pods/AFNetworking`.
  - [ ] Only allow `prepare_command` to read from (so it cannot send user data) and write to the Pod directory, e.g. `Pods/AFNetworking`.

**Comment by orta** [comment]
Yes

**Comment by neonichu** [comment]
@segiddins It could just create a temporary directory inside the Pods directory instead, couldn't it?

**Comment by segiddins** [comment]
@neonichu the build script it uses (which is not specific to CocoaPods) uses `/tmp`, but it should be fine to allow access to `/tmp`

**Comment by neonichu** [comment]
There's stuff to be screwed up in /tmp, so App Store apps which are sandboxed don't have access to it, either. I'd say we should stick to that and rather set TMPDIR to an appropriate directory only to be used by CP or even that Pod.

**Comment by alloy** [comment]
>  I'd say we should stick to that and rather set TMPDIR to an appropriate directory only to be used by CP or even that Pod.

@neonichu Yes, I was thinking exactly that too :+1:

**Comment by orta** [comment]
IMO, not 1.0.0 material, this shouldn't block the release

**Comment by segiddins** [comment]
@alloy did you ever make any progress on this?
