### ISSUE TITLE
pod install fail when remove a pod from podfile

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#2855]
I remove a pod from my Podfile. But the pod is a dependency of other pod.
So I hope that Cocoapods still install the pod, just no dependency by my project.
But I found it seem not work:

```
Finding Podfile changes
  R HTTPDNS
  R SecurityGuardSDK
  R TBMstore
...
[!] Unable to satisfy the following requirements:

- `TBMstore` required by `MtopSDK (1.2.0-build-17)`
```

I think the command should be `pod install`, not `pod update`, right?

**Comment by kylef** [comment]
I'm going to close this issue since it's been awaiting input for over 5 months. Please re-open it when @segiddins's question has been answered.
