### ISSUE TITLE
podfile.local no longer works in 0.35 🌈

### ISSUE THREAD

**Issue by mjhenkes** [CocoaPods/CocoaPods#2860]
With 0.35 you can no longer use the podfile.local trick to enable local development of pods since with the new dependency resolver you get the message:

```
[!] There are multiple dependencies with different sources for `AFNetworking` in `Podfile`:

- AFNetworking (from `https://github.com/AFNetworking/AFNetworking.git`, branch `master`)
- AFNetworking (~> 2.5)"
```

I guess this may or may not be a bug, but I like being able to pull in dependencies from the pod spec and be able to override them and point them to local branches without having to duplicate all the dependancies again in my local podfile.

I've provided a sample of this setup at the following repo:
https://github.com/mjhenkes/CocoaPodsLocalDev

**Comment by revolter** [comment]
@segiddins, But why doesn't this work:

	pod 'FolioReaderKit', :git => 'https://github.com/revolter/FolioReaderKit.git', :commit => '90ce3882', :configurations => ['Release']
	pod 'FolioReaderKit', :path => '~/Development/GitHub/revolter/FolioReaderKit', :configurations => ['Debug']

?

**Comment by benasher44** [comment]
@revolter CocoaPods generates a target in the Pods project for FolioReaderKit. As far as I know, you can't add files to a single target in Xcode that are meant to only be built in release vs debug. If Xcode doesn't support it, it's going be very difficult to support inside of CocoaPods.

**Comment by revolter** [comment]
@benasher44, Great explanation, thanks! Though you can exclude files from a configuration, as described [here][1], but it's not very reliable.

  [1]: https://github.com/Flipboard/FLEX#excluding-flex-from-release-app-store-builds

**Comment by benasher44** [comment]
@revolter if you can find cases where it's unreliable, we'd definitely appreciate a GitHub issue! In this particular case, this use of the feature is unsupported. It wasn't designed to be used to install one version of a pod in debug and another in release.

**Comment by revolter** [comment]
I said that Xcode's configuration based file exclusion is not reliable, not Cocoapods.

**Comment by benasher44** [comment]
Ah! Gotcha.
