### ISSUE TITLE
"Found multiple specifications"

### ISSUE THREAD

**Issue by kevinrenskers** [CocoaPods/CocoaPods#2861]
For some reason I now have 2 spec repos: /Users/kevin/.cocoapods/repos/master/Specs and /Users/kevin/.cocoapods/repos/master-1/Specs/. Whenever I `pod install` or push a new version to our private spec repo I get the error "Found multiple specifications", like this:

```
[!] Found multiple specifications for `AFNetworking (2.5.0)`:
- /Users/kevin/.cocoapods/repos/master/Specs/AFNetworking/2.5.0/AFNetworking.podspec.json
- /Users/kevin/.cocoapods/repos/master-1/Specs/AFNetworking/2.5.0/AFNetworking.podspec.json

[!] Found multiple specifications for `ObjectiveSugar (1.1.0)`:
- /Users/kevin/.cocoapods/repos/master/Specs/ObjectiveSugar/1.1.0/ObjectiveSugar.podspec.json
- /Users/kevin/.cocoapods/repos/master-1/Specs/ObjectiveSugar/1.1.0/ObjectiveSugar.podspec.json
```

(But a whole lot more then that, basically an error for every version of every pod used in the current project.)

This is the second time I have this problem. The last time I simply completely removed my .cocoapods folder and ran `pod setup`, but now I have this problem again. I'm using cocoapods 0.35.0.rc2. I think it happens when the shallow checkout is created.

**Comment by li-qing** [comment]
it helps, thanks a lot kevin !

**Comment by ZhouYiKoo** [comment]
I also encountered this problem, how to solve it?

**Comment by cristian-milea** [comment]
how was this solved?

**Comment by nick3389** [comment]
@kevinrenskers 
Same for me:

`- /Users/user/.cocoapods/repos/cocoapods/Specs/d/d/6/ReachabilitySwift/5.0.0/ReachabilitySwift.podspec.json
- /Users/user/.cocoapods/repos/trunk/Specs/d/d/6/ReachabilitySwift/5.0.0/ReachabilitySwift.podspec.json`

**Comment by FrancescoPaiola** [comment]
how to solve this problem?

**Comment by Amzd** [comment]
I think the newer issues are related to the switch to the CDN in 1.8.0
http://blog.cocoapods.org/CocoaPods-1.8.0-beta/

So the warning with `master` vs `trunk` like this: 
```
[!] Found multiple specifications for `[...]`:
- /.cocoapods/repos/master/Specs/[...].podspec.json
- /.cocoapods/repos/trunk/Specs/[...].podspec.json
```
---
Fixed by running:

```
pod repo remove master
```
And changing in your Podfile:
```diff
- source 'https://github.com/CocoaPods/Specs.git'
+ source 'https://cdn.cocoapods.org/'
```

**Comment by dshikulin-mwb** [comment]
In my case it was 
`pod repo remove cocoapods`
