### ISSUE TITLE
[Frameworks] Wrong specified location of integrated Pods Product Reference causes linker warning

### ISSUE THREAD

**Issue by flovilmart** [CocoaPods/CocoaPods#2877]
Upon archiving the linker throws those warnings. It's not annoying but I try to keep as much as possible warning free repositories and build procedures.

ld: warning: directory not found for option '-F/Users/florent/src/FreshMint/FreshMint/Pods/build/Debug-iphoneos/Pods-FreshMint'
ld: warning: directory not found for option '-F/Users/florent/src/FreshMint/FreshMint/Pods/build/Debug-iphoneos'

**Comment by mrackwitz** [comment]
:+1:

**Comment by parkej60** [comment]
Sorry if I missed this in the conversation above, but what is the solution??

**Comment by neonichu** [comment]
@parkej60 this problem should've been solved during the development of 0.36 - if you're seeing this with 0.37.2 please open a new issue with steps to reproduce, thanks!
