### ISSUE TITLE
Command to generate a throw-away Xcode project from a podspec

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#2885]
Consider the following stories:

> - As a library consumer, I would like to be able to integrate a library as a Xcode project, so that I can integrate in any way that Xcode offers and I see fit.
> - As a library author, I want CocoaPods to be able to produce a throw-away Xcode project based on my podspec, so that library consumers can integrate that without using CocoaPods and I don’t have to spend time maintaining a feature I don’t use.

So we need a pod plugin that does something like `pod xcode-ify Bananas.podspec` which produces a Xcode project that has 1 target, which is a framework version of the Bananas library.

The author can then decide whether or not to check the throw-away Xcode project into the repository or leave it up to the library consumer to produce it. The former would probably be the most user-friendly choice.

**Comment by segiddins** [comment]
@neonichu with target de-duplication, isn't this basically `pod install --no-integrate`, without it working for multiple platforms?

**Comment by neonichu** [comment]
Yep, but the issue remains that this isn't really stand alone if there are dependencies and there's no good way to solve this.

**Comment by segiddins** [comment]
Check in the `Pods` directory?

**Comment by neonichu** [comment]
:see_no_evil:

**Comment by maximkhatskevich** [comment]
See for solution https://github.com/CocoaPods/Xcodeproj/issues/590
