### ISSUE TITLE
base configuration not set when using link_with and target

### ISSUE THREAD

**Issue by ConfusedVorlon** [CocoaPods/CocoaPods#2907]
using a blank xcode project with two targets
1. PodTest 
2. PodTestTests

the following podfile does not set the configuration correctly for PodTestTests

```
#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '6.0'

link_with ['PodTest', 'PodTestTests']

pod 'CocoaLumberjack', '~> 1.9'

target 'PodTestTests' do
    pod 'MAZeroingWeakRef', '~> 1.0'
end
```

(all configurations are set to Pods.debug or Pods.release)

removing the link_with line, and removing the existing configurations from the project, then re-running pod install results in the configurations being set correctly.
 (configuration for PodTestTests is Pods-PodTestTests.debug/release)

It may be that I'm using link_with incorrectly here, but if that is the case, then the documentation definitely needs a little more info on correct usage.

http://guides.cocoapods.org/syntax/podfile.html#link_with

full project available here
https://dl.dropboxusercontent.com/u/4262242/PodTest.zip

I'm using cocoapods 0.35.0

**Comment by mrigankgupta** [comment]
I am facing the same problem. you might need to do Podfile like 

#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '6.0'

target 'PodTest'
    pod 'MAZeroingWeakRef', '~> 1.0'
   pod 'CocoaLumberjack', '~> 1.9'
end
target 'PodTestTests' do
    pod 'MAZeroingWeakRef', '~> 1.0'
end

**Comment by shams-ahmed** [comment]
@kylef is @mrigankgupta approach correct? i see the default template generate this when running ```pod init```

in terms of @ConfusedVorlon issue would this solve the issue, as they are only trying to add one pod just for there test target...

**Comment by vijayasreepanch** [comment]
Please help me with "Separate Pods For Different Targets"

This is my PodFile

source 'http://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MyApp' do
pod 'MMDrawerController'
end

target 'MyAppTests' do
pod 'SkyLab'
end

The issue is that for the test target (MyAppTests) both the pods get added. I am unable to add pods exclusively to test target alone. Thanks!
