### ISSUE TITLE
Pod setup error.

### ISSUE THREAD

**Issue by geoffharcourt** [CocoaPods/CocoaPods#2908]
I am trying to install a Cocoapods fresh on my OSX Yosemite machine. I'm using Ruby 2.1.5 and zsh. Here are my order of steps:

1. Make sure there's no residual Cocoapods config on my machine with `rm -rf ~/.cocoapods`
2. Uninstall all Cocoapods-related gems (downloader, trunk, try, plugins, etc)
3. Install Cocoapods 0.35.0 and run `pod setup`
```shell
[ ~ ] ✔ gem install cocoapods
Fetching: cocoapods-trunk-0.4.1.gem (100%)
Successfully installed cocoapods-trunk-0.4.1
Fetching: cocoapods-try-0.4.2.gem (100%)
Successfully installed cocoapods-try-0.4.2
Fetching: cocoapods-plugins-0.3.2.gem (100%)
Successfully installed cocoapods-plugins-0.3.2
Fetching: cocoapods-downloader-0.8.0.gem (100%)
Successfully installed cocoapods-downloader-0.8.0
Fetching: cocoapods-core-0.35.0.gem (100%)
Successfully installed cocoapods-core-0.35.0
Fetching: cocoapods-0.35.0.gem (100%)
Successfully installed cocoapods-0.35.0
6 gems installed
[ ~ ] ✔ pod setup
Setting up CocoaPods master repo
[!] There was an error reading '/Users/geoff/.cocoapods/repos/master/CocoaPods-version.yml'.
Please consult http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/ for more information.
```

My YAML file referenced in the error looks like this:
```yaml
---
min: 0.32.1
last: 0.35.0
```

I can get all of this to work if I uninstall everything and then install and lock my version of Cocoapods to 0.32.1 (and I can use Cocoapods in my project), but if I update to 0.35.0, I can neither successfully run `pod setup` nor execute `pod install` on my project with 0.35.0.

**Comment by clemensg** [comment]
This problem is still not fixed! :disappointed:

**Comment by TomStoermer** [comment]
Same here. Reverting psych fixed it. (copy&paste)

**Comment by clemensg** [comment]
No idea what change is causing the problem between 2.0.0 and 2.0.8. Any ideas? @alloy ?

Otherwise we'll have to `git bisect`.

**Comment by brendanmartens** [comment]
I just ran into this issue as well. I was able to get past it by doing:
rm -fr ~/.cocoapods
gem cleanup
gem install psych -v 2.0.0
gem uninstall psych -v 2.0.10
pod setup

I executed those commands in that order, in retrospect I would have tried uninstalling then cleaning...
I don't know of the gem cleanup was necessary.

**Comment by hidekuro** [comment]
@brendanmartens works fine for me. :+1:

**Comment by wyattblake** [comment]
finally, @brendanmartens me too.  Thanks!

**Comment by cromanelli** [comment]
In my case i had 2 psych versions :
 psych-2.0.6
 psych-2.0.11

uninstalled both and then reinstalled  psych-2.0.11

this fixed the problem

**Comment by Raiden996** [comment]
Same here. Reverting psych fixed it.

**Comment by kashif** [comment]
Latest psych-2.0.13 fixes the issue :clap:

**Comment by cbillante-gpsw** [comment]
2.0.5 worked for me.  Thanks for the solution.

**Comment by Japspre** [comment]
@dmi3j solution worked for me, thanks

**Comment by timguoqk** [comment]
psych-2.0.0 works for me.

**Comment by susemi99** [comment]
Thanks @csknns

**Comment by Nru** [comment]
Please reopen the issue. I have this problem too and version of gem psych is 2.0.13:

*** LOCAL GEMS ***

activesupport (4.2.1)
awesome_print (1.6.1)
bigdecimal (1.2.4)
builder (3.2.2)
bundler (1.6.2)
bundler-unload (1.0.2)
calabash-common (0.0.1)
calabash-cucumber (0.12.3)
CFPropertyList (2.3.1)
claide (0.8.1)
clamp (0.6.4)
cocoapods (0.36.3)
cocoapods-core (0.36.3)
cocoapods-downloader (0.9.0)
cocoapods-plugins (0.4.2)
cocoapods-trunk (0.6.0)
cocoapods-try (0.4.3)
colored (1.2)
cucumber (1.3.19)
diff-lcs (1.2.5)
edn (1.0.6)
escape (0.0.4)
executable-hooks (1.3.2)
fuzzy_match (2.0.4)
gem-wrappers (1.2.4)
geocoder (1.2.8)
gherkin (2.12.2)
httpclient (2.6.0.1)
i18n (0.7.0)
io-console (0.4.2)
json (1.8.2, 1.8.1)
json_pure (1.8.1)
mime-types (1.25.1)
mini_portile (0.6.2)
minitest (5.5.1, 4.7.5)
molinillo (0.2.3)
multi_json (1.11.0)
multi_test (0.1.2)
nap (0.8.0)
netrc (0.7.8)
nokogiri (1.6.6.2)
open4 (1.3.4)
psych (2.0.13)
rack (1.6.0)
rack-protection (1.5.3)
rake (10.1.0)
rdoc (4.1.0)
rest-client (1.6.8)
retriable (1.4.1, 1.3.3.1)
rubygems-bundler (1.4.4)
rubyzip (1.1.6)
run_loop (1.2.9)
rvm (1.11.3.9)
sim_launcher (0.4.13)
sinatra (1.4.6)
slather (1.6.0)
slowhandcuke (0.0.3)
test-unit (2.1.2.0)
thor (0.19.1)
thread_safe (0.3.5)
tilt (2.0.1)
tzinfo (1.2.2)
xamarin-test-cloud (0.9.35)
xcodeproj (0.23.1)

**Comment by neonichu** [comment]
Doesn't make sense to reopen if there is nothing actionable we can do about it. If you have found this to be an actual issue in CocoaPods, please share.

**Comment by SixArm** [comment]
Similar issue, with a twist: Cocoapods 0.36.3 works fine, and has for weeks. I just upgraded to Cocoapods 0.36.4 and now getting these errors:

    ✗ pod update
    Update all pods
    [!] ERROR: Parsing unable to continue due to parsing error:
   contained in the file located at /Users/joel/git/BoxbeeStorage/Frisbee/Podfile.lock

    ✗ rm -rf ~/.cocoapods
    ✗ pod install
    Analyzing dependencies
    Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git`
    [!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
    You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

**Comment by esetnik** [comment]
I disagree with @kashif. `psych-2.0.13` does not work for me. The only thing that works is reverting back to `psych-2.0.8` that is bundled with `ruby-2.2.1`.

```
$ gem list
*** LOCAL GEMS ***
psych (2.0.8)

$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

$ pod update
Update all pods
Analyzing dependencies
...
Generating Pods project
Integrating client project

$ gem update psych
Updating installed gems
Updating psych
Fetching: psych-2.0.13.gem (100%)
Building native extensions.  This could take a while...
Successfully installed psych-2.0.13
Parsing documentation for psych-2.0.13
Installing ri documentation for psych-2.0.13
Installing darkfish documentation for psych-2.0.13
Done installing documentation for psych after 2 seconds
Parsing documentation for psych-2.0.13
Done installing documentation for psych after 1 seconds
Gems updated: psych

$ pod update
Update all pods
[!] ERROR: Parsing unable to continue due to parsing error:

$ gem uninstall psych
Successfully uninstalled psych-2.0.13

$ pod update
Update all pods
Analyzing dependencies
...
Generating Pods project
Integrating client project
```

**Comment by kashif** [comment]
dear @esetnik yes it seems the error you get now is not the original error of this issue... any idea what the missing line is?

**Comment by esetnik** [comment]
The psych problem seems to cause both:

```
$ pod update
Update all pods
[!] ERROR: Parsing unable to continue due to parsing error:
```
and
```
$ pod setup
Setting up CocoaPods master repo
[!] There was an error reading '/Users/geoff/.cocoapods/repos/master/CocoaPods-version.yml'.
Please consult http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/ for more information.
```

The latter was the original reported issue. I'm just sharing that this issue is larger than just a broken `pod setup` it's also about `pod update` as well. It looks like @SixArm also reports the same.

**Comment by kashif** [comment]
@esetnik can you also kindly try with cocopods beta? `0.37.0.beta.1`?

**Comment by esetnik** [comment]
Not working on the beta unfortunately.

```
$ gem install cocoapods --pre
Fetching: xcodeproj-0.24.0.gem (100%)
Successfully installed xcodeproj-0.24.0
Fetching: cocoapods-core-0.37.0.beta.1.gem (100%)
Successfully installed cocoapods-core-0.37.0.beta.1
Fetching: cocoapods-0.37.0.beta.1.gem (100%)
Successfully installed cocoapods-0.37.0.beta.1
Parsing documentation for xcodeproj-0.24.0
Installing ri documentation for xcodeproj-0.24.0
Parsing documentation for cocoapods-core-0.37.0.beta.1
Installing ri documentation for cocoapods-core-0.37.0.beta.1
Parsing documentation for cocoapods-0.37.0.beta.1
Installing ri documentation for cocoapods-0.37.0.beta.1
Done installing documentation for xcodeproj, cocoapods-core, cocoapods after 7 seconds
3 gems installed

$ pod update
Update all pods
[!] ERROR: Parsing unable to continue due to parsing error:

$ gem uninstall psych
Successfully uninstalled psych-2.0.13

$ pod update
Update all pods
Analyzing dependencies
...
```

**Comment by softroots** [comment]
That was a headache - Thanks @csknns

**Comment by tallesborges** [comment]
rvm use 2.2.1 fix for me.

**Comment by giacgbj** [comment]
Cocoapods 0.37.1
Psych 2.0.13

```
$  pod setup
Setting up CocoaPods master repo
[!] There was an error reading '/Users/jhack/.cocoapods/repos/master/CocoaPods-version.yml'.
Please consult http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/ for more information.
```

**Comment by cbowns** [comment]
A big :+1:, I just hit this error as well. I think another `gem` I installed today (via `rbenv`) brought in `psych`.

**Comment by segiddins** [comment]
Also reported at https://github.com/bbatsov/rubocop/issues/1510 -- someone said it might be a RubyGems bug?

**Comment by sammoore** [comment]
Could this occur to someone who uses `rbenv` without proper maintenance / rehashing? Or is it a general problem that will occur with updating gems in general? I just had the same problem; pod broke after `gem update`.

**Comment by geoffharcourt** [comment]
This issue happened to me even after rehashing.

**Comment by hemanshuliya** [comment]
There was an error reading '/Users/sotsys0156/.cocoapods/repos/master/CocoaPods-version.yml

Solved by using following command: 

sudo rm -fr ~/.cocoapods/repos/master/CocoaPods-version.yml

**Comment by cmavromoustakos** [comment]
gem cleanup did it for me. 

The instructions that were given on the website given by CL were not valid.

The instructions that did not work for me were: http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/

**Comment by iosappdeveloper** [comment]
`gem cleanup` worked for me too.

<b>Background</b>: Initially I had `gem list` gave me `psych (2.0.15, 2.0.5, 2.0.0)` . After reading about comments, I performed `gem uninstall psych` which left me with `gem list` of  `psych (2.0.15, 2.0.5, 2.0.0)` .. Then I did `gem cleanup` and follow up `pod install` worked immediately.

**Comment by hachidorii** [comment]
Seems to me that removing the psych gem fixes this completely. I wonder what continues to cause this to be an issue.

**Comment by wolffan** [comment]
Doing 

- gem cleanup
-pod install worked

worked as well

**Comment by longbowww** [comment]
also ran into this today, but neither fixes worked for me 

ended up checking out a pre-update version from my git

**Comment by vinibaggio** [comment]
Reverting psych (from 2.0.15 to 2.0.8) fixed this for me as well.

**Comment by mikumaycry** [comment]
I reinstalled ruby, cocoapods...but only Reverting psych to 2.0.0 works

**Comment by SpikeyCoder** [comment]
Thank you for posting the psych version fix! Major help and fixed this for me as well.

**Comment by zirinisp** [comment]
`sudo gem cleanup
`
did the trick for me
