### ISSUE TITLE
[Frameworks] Extend linter for module_name

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/CocoaPods#2912]
For frameworks support we should extend the linter a bit:

- [x] Lint that `module_name` is a valid C99 identifier
- [ ] If an explicit `module_name` is specified, build both a static library and a framework

see also the discussion in CocoaPods/Core#205

**Comment by segiddins** [comment]
We should just build a framework for everything anyways now.

**Comment by neonichu** [comment]
@segiddins For the case where a `module_name` is specified, I agree. Otherwise, that'll be contradictory to frameworks being opt-in. We don't even know, yet, how to properly build things like OpenSSL as a framework.

**Comment by segiddins** [comment]
@neonichu ping?

**Comment by neonichu** [comment]
👍 

I wonder if it is actually necessary to build for both. Let's lint as `--use-frameworks` automatically if any framework specific option (module name, module map) is used?

**Comment by segiddins** [comment]
Sure, although haven't a lot of pods not been working as frameworks?

**Comment by neonichu** [comment]
Some aren't, mostly some vendored things and Pods using libs without module maps or C libraries. 

But I'd go with the assumption that if the author explicitly includes framework specific attributes, the Pod should work as a framework - otherwise those attributes wouldn't serve a purpose in that spec.
