### ISSUE TITLE
Change naming of resource bundle targets to "Pods-*" 

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/CocoaPods#2933]
Currently, the resource bundle targets CP generates are simply named after the bundle name, which can easily collide with user created targets in the same workspace. See CocoaPods/pod-template#81 for some discussion on how `xcodebuild` breaks if there are two schemes with the same name. Schemes are automatically named after the target name by default.

**Comment by segiddins** [comment]
@neonichu has this been fixed by any chance with reduplication?

**Comment by neonichu** [comment]
Nope, because this was about clashes with user created targets.

**Comment by segiddins** [comment]
This seems to be fixed given we use `resources_bundle_target_label` to generate the name for the bundles?
