### ISSUE TITLE
Git Dependency in Podspec

### ISSUE THREAD

**Issue by shortstuffsushi** [CocoaPods/CocoaPods#2937]
Hi all,

I'm trying to get a better understanding of #922, and the reason Cocoapods works this way, as I'm having the same issue right now. I have a podspec for a project that (I was hoping to have) point at a dependency from git, so `s.dependency 'SomeDependency', :git => ...`. #2485  seems to be looking for exactly the same issue, and was also pointed at #922, but this doesn't seem entirely related to having :git dependencies in specs. Maybe it is, it got pretty long and a bit off topic, so I thought I'd try to ask this as a more specific question.

Is it by design that specifying different sources doesn't work for Podspecs? If so, would you consider changing that behavior? It seems like a pretty common need, and there doesn't seem to be any way to work around it if you have that need.

An example use case I have is as follows:

We have three internal repositories, A, B, and C. C is the actual application, which has B as a dependency, B is a framework that utilizes the A framework (so A requires B, B requires C). During development, we want to be able to use a branch of A, which we were hoping to accomplish via subspecs in the B Podspec like this

```
  s.default_subspec = 'Core'

  s.subspec 'Core' do |ss|
    ss.dependency 'A'
  end

  s.subspec 'Dev' do |ss|
    ss.dependency 'A', :git => ..., :branch => ...
  end
```

Is there some way to do this that I'm not seeing? Is this not considered a valid use case? 

Thanks :rainbow:

**Comment by mpurland** [comment]
This is confusing as well. A podspec should be able to define what dependency, version, or method such as git or local path.

**Comment by groue** [comment]
Hello,

What if I am the maintainer of two libraries: Parent and Child, where Child depends on Parent, and I want to let Podfile specify a branch of Child that depends on a branch of Parent?

The use case is the following: as Swift 4 is coming, there is a `Swift4` branch of the GRDB.swift pod that users can install with `pod 'GRDB.swift', branch: 'Swift4'` in their podfile. Now I want to let users install the `Swift4` branch of another pod, `RxGRDB`, which that depends on GRDB. Can I update the podspec of RxGRDB to tell it depends on the Swift4 branch of GRDB?

**Comment by orta** [comment]
You would need to tell someone that they should set all the custom branches in their Podfile, e.g.

```ruby
pod 'RxGRDB', branch: 'Swift4'
pod 'GRDB.swift', branch: 'Swift4'
pod 'RxSwift', branch: 'Swift4'
```

That wouldn't pass `trunk push` though until the dependants have a Swift 4 version in trunk though

**Comment by groue** [comment]
All right, @orta. Thanks for the tip!
