### ISSUE TITLE
Unable to add private pod dependency to another private pod

### ISSUE THREAD

**Issue by harishkashyap** [CocoaPods/CocoaPods#2941]
Why is it so difficult to specify a private pod dependency to another private pod. I get the error: [!] Unable to find a specification for `...-sdk` depended upon by `...-ui-sdk`. If I specify sources with --sources: 
pod spec lint a-ui-sdk.podspec --sources='https://..@bitbucket.org/.../podsrepo.git, https://github.com/CocoaPods/Specs.git' --allow-warnings it throws this error:[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
I have added this repo to my sources.

**Comment by kevinrenskers** [comment]
I have the same problem, not with the linter but with `pod update` and `pod install`.

I have a private pod (A) with an example project that uses this podspec. Now I want this podspec to use another private pod (B). In the example project I run `pod install` and get this error: 

`[!] Unable to find a specification for B depended upon by A`

Private pod B is pushed to the private pod repo, it is there in `.cocoapods/repos/myprivaterepo`.

How can I solve this?

**Comment by segiddins** [comment]
@kevinrenskers use the `source` directive in your Podfile.

**Comment by kevinrenskers** [comment]
Ah, in the Podfile. Thanks, it worked.

**Comment by kidsid49** [comment]
@segiddins I also start facing this issue after updating to v0.37. Earlier it used to work fine. But after updating to v0.37 I am unable to run pod update or pod install for a private pod which is having dependency on another private pod.

Terminal shows this message on running pod update.

 [!] Unable to find a specification for `Pod B (~> 0.1.0)` depended upon by `Pod A`

**Comment by segiddins** [comment]
@kidsid49 see my earlier answer: specify all your `source`s in your Podfile

**Comment by kidsid49** [comment]
@segiddins Means apart from mentioning in .podsepc file of private pod (as dependency)  I have to specify all dependency sources in private pod podfile?

**Comment by JoshKimmelman** [comment]
@kidsid49 I was having the same problem.  Whichever podfile is pulling in Pod A needs to have the source URL for Pod B.  This way, cocoapods will know where to look.  Even though your pod is local, in order to be a dependency it needs to be online.

**Comment by gbattiston** [comment]
I'm having the same problem. I specified the source on the podfile.
But the problem keeps coming back. It's on pod lib lint

 -> MLMessages (0.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to add a source with url `git@github.com:mercadolibre/mobile-ios_specs.git` named `mercadolibre-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.) during validation.

These are the repos
gbattiston$ pod repo list

master
- Type: git (master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/gbattiston/.cocoapods/repos/master

mercadolibre
- Type: git (master)
- URL:  git@github.com:mercadolibre/mobile-ios_specs.git
- Path: /Users/gbattiston/.cocoapods/repos/mercadolibre

2 repos
