### ISSUE TITLE
Automatically detect conflicts between framework names

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/CocoaPods#2943]
See #2916 for discussion on how this can occur.

If a Pod with included frameworks still defines `source_files`, e.g. the GoogleMaps SDK, the fix build in #2918 will not work. As it leads to errors which are not immediately obvious, CP should throw an error during `pod install` if there is a conflict between `vendored_frameworks`, `frameworks` and the module names chosen for all Pods to be integrated.

**Comment by Reflejo** [comment]
Is it even possible to create a configuration that supports building a framework with a modulemap and also links statically the vendored_framework?. I'm trying to build it manually in order to see what is involved in the process.

**Comment by uros-gardasevic** [comment]
🌈 Hi, i didn't want to create a new ticket, because my problem might be related to this. I have the situation where two Pods includes the same library via vendored_framework field in their Podspec. While trying to generate workspace that relays on those two pods, CP fires "target has frameworks with conflicting names: <###>.framework" error. To me this sounds like legit use case, please correct me if i'm wrong or point me to further reading.

**Comment by luliu** [comment]
> 🌈 Hi, i didn't want to create a new ticket, because my problem might be related to this. I have the situation where two Pods includes the same library via **vendored_framework** field in their Podspec. While trying to generate workspace that relays on those two pods, CP fires "_target has frameworks with conflicting names: <###>.framework_" error. To me this sounds like legit use case, please correct me if i'm wrong or point me to further reading.

I second this.  Any word on this?

**Comment by uros-gardasevic** [comment]
Glad to see i am not the only one finding this a bit odd. Unfortunately i haven't heard from the guys, which might have something to do with the fact i didnt open a new ticket, and this one seems to be well buried. We did overcome this by commenting out problematic line in CP source, and it behaves as we expected, meaning everything is resolved and there aren't duplicated framework files added to the build artefact. I certainly not recommend this and am still in favour of finding more reasonable approach, but until then...

**Comment by amorde** [comment]
The problem with that is what if they are different frameworks that just happen to have the same name? which one would be linked into the file app? I don't realistically see support for that being added any time soon but would be open to PRs that improve this

**Comment by uros-gardasevic** [comment]
Hi @amorde , i see your point. I understand that more of the concern was what if there were two different frameworks with the same name. I was quite blinded with my case (the same framework), that i haven't given any thoughts to this situation. The reason for us ending up creating two Pods pulling in the same framework is that Canon SDK, which we relay on, is embedding two separated functionalities, namely camera control and RAW conversion which we dont want to keep in the same place (for common sense reasons). Thanks for your input.
