### ISSUE TITLE
Update will always download git pod, regardless of changes. 

### ISSUE THREAD

**Issue by markst** [CocoaPods/CocoaPods#2949]
If I have a pod specified as:
`pod 'RestKit', :git => 'git@github.com:Papercloud/RestKit.git', branch: 'master'`

`pod update` will always pre-download, regardless of whether there have been changes on the master, even if I specify a particular commit.

Can cocoapods be more intelligent & identify whether the commit id has changed & only download if necessary?

**Comment by krzyzanowskim** [comment]
I have somehow related issue, but `pod update` don't fetch fresh version and keep using the old one.
Sequence is:
1. pod install
2. update git repo
3. pod update (changes not fetched)

`pod 'ObjectivePGP', :git => 'https://github.com/krzyzanowskim/ObjectivePGP.git', :branch => :master`

Fetching external sources
-> Pre-downloading: `ObjectivePGP` from `https://github.com/krzyzanowskim/ObjectivePGP.git`, commit `c4652b63f5c9ac998c785590f09e697bb89a2ac8`

while there is newer commit available.

$ pod --version
0.35.0

**Comment by kylef** [comment]
@krzyzanowskim That sounds like a bug introduced in 0.35, could you file a separate issue for this?

**Comment by krzyzanowskim** [comment]
#2997

**Comment by kylef** [comment]
@krzyzanowskim thank you

**Comment by segiddins** [comment]
We can use `git ls-remote URL #{options[:branch] || 'HEAD'}` to figure out whether the SHA has actually changed

**Comment by segiddins** [comment]
I'm going to close this as not worth changing. A path implementing this would be much appreciated, but the difficulty of getting this right probably isn't worth the slight UX improvement.

**Comment by markst** [comment]
this is supposedly resolved with https://github.com/CocoaPods/CocoaPods/pull/3236
But this is still a major issue for me. Admittedly my internet isn't the greatest, but my pods take forever to update when there is no actual change on the git repo.

**Comment by segiddins** [comment]
@markst as I said, I'd love to see a patch implementing this behavior, but unless it's contributed by a member of the community, I just don't think it's worth the core team's time.

**Comment by danielgalasko** [comment]
Pity this was closed, would love to submit a PR if I could get pointed in the right direction. We use SHAs for our internal pods and it 'pre-downloads' them everytime we run pod update.

**Comment by segiddins** [comment]
@danielgalasko we'd still love to see a PR for this! As I posted above, using `git ls-remote` and comparing that SHA with what's in the lockfile would be a reasonable way to go
