### ISSUE TITLE
Target-'Pods' overrides the Architecures setting

### ISSUE THREAD

**Issue by lilin87788** [CocoaPods/CocoaPods#2951]
when i install my project with cocoapods have a warning like this ：

![image](https://cloud.githubusercontent.com/assets/1483811/5468405/4c0f84c8-8609-11e4-8850-5bb39d2a3af6.png)

**Comment by segiddins** [comment]
I've never seen this, so I'm going to close the issue. I'd be happy to re-open it if someone shared a project that reproduces it.
