### ISSUE TITLE
creating a shallow clone crash git repo server 

### ISSUE THREAD

**Issue by ninjitaru** [CocoaPods/CocoaPods#2960]
Hi,

We notice that the use of `--depth 1` will crash our internal git server
Is it possible to have option to manually remove `--depth 1` using pod spec?

I tried query our repo's git Content-Type, which appear to be smart  `Content-Type: application/x-git-upload-pack-advertisement`

**Comment by segiddins** [comment]
I believe this is addressed by https://github.com/CocoaPods/cocoapods-downloader/pull/36. If not, please comment with steps to reproduce so we can come up with another workaround.
