### ISSUE TITLE
[Frameworks] Let lint fail for Swift pods supporting deployment targets below iOS 8.0

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#2963]
If a podspecs includes Swift files, let the linter fail if the spec specifies a deployment targets on iOS below 8.0.

**Comment by neonichu** [comment]
Opinions on how to formulate this? Simply make this an error in case of a Swift pod?

```
 -> QueryKit (0.9.0)
    - ERROR | [QueryKit/Swift, QueryKit/Attribute/Swift, QueryKit/Attribute/Bridge, and more...]  ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
```

**Comment by kylef** [comment]
@neonichu Probably less fragile to do our own checks, Apple could change the message and break our logic.

**Comment by neonichu** [comment]
Makes sense - I'll take a stab at it tomorrow.
