### ISSUE TITLE
Linking Against an Today Widget?

### ISSUE THREAD

**Issue by bassrock** [CocoaPods/CocoaPods#2980]
I am using this to try and link pods to an application extension. I am getting the following warnings:

```
Linking against dylib not safe for use in application extensions:
```

Is this normal? From what I read apple will reject my application because of this. I am using the new framework integration on master to link my pods if that helps.

**Comment by segiddins** [comment]
@neonichu want to make a PR for this.

**Comment by bassrock** [comment]
Is this automatic? if so it does not currently work for WatchKit Extension targets.

**Comment by segiddins** [comment]
@bassrock what version of cocoapods are you using?

**Comment by bassrock** [comment]
@segiddins 0.36.0.beta.2

**Comment by segiddins** [comment]
In that case, please open a new issue detailing what's going wrong.

**Comment by bassrock** [comment]
ok
