### ISSUE TITLE
`pod trunk push` fails although `pod lib lint` is successful.

### ISSUE THREAD

**Issue by inamiy** [CocoaPods/CocoaPods#2981]
Minor issue here.

When `spec.requires_arc = true` is removed from podspec,
`pod lib lint` will be successful but `pod trunk push` will fail with only following error message attached:

> [!] The Pod Specification did not pass validation.

I found this when I was trunk-pushing SwiftState 1.1.1.

**Comment by nalexn** [comment]
I got trapped with this second time already, so for the reference:

Whenever local `lint` is successful, but `trunk push` fails at linting stage, make sure to purge the cached remote version:

`pod cache clean <your lib>`
