### ISSUE TITLE
OTHER_SWIFT_FLAGS is incorrect

### ISSUE THREAD

**Issue by favoyang** [CocoaPods/CocoaPods#2983]
In .xcconfig file, generated OTHER_SWIFT_FLAGS is

    OTHER_SWIFT_FLAGS = "-D COCOAPODS"

But should be

    OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS" 

Pod - 0.36.0.beta.1
Tested with SwiftColors.

**Comment by fluidsonic** [comment]
Afaik it should be `-DCOCOAPODS` without space.

**Comment by favoyang** [comment]
Yes, that should work as well.

    OTHER_SWIFT_FLAGS = $(inherited) "-DCOCOAPODS"

**Comment by danthorpe** [comment]
Hi! Can we re-open this ticket? The referenced commit doesn't fully address the issue as `$(inherited)` isn't generated in the output.

I've never actually contributed to CocoaPods before (shame on me) - but I had a go at fixing it in this branch: https://github.com/danthorpe/CocoaPods/commit/becbac0dcfd1c064344a81688f54c6d2c04d4bb1

**Comment by segiddins** [comment]
@danthorpe A PR with that change would be :ok_hand:

**Comment by markltownsend** [comment]
Going back to the original comment, the OTHER_SWIFT_FLAGS should be 

OTHER_SWIFT_FLAGS = $(inherited) '-DCOCOAPODS', not 
OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"

**Comment by allaire** [comment]
@markltownsend Both work no? I agree that if there's a space it falls on two line, but it still work
