### ISSUE TITLE
"[!] Unable to find target" when running "pod install"

### ISSUE THREAD

**Issue by caseyscarborough** [CocoaPods/CocoaPods#2987]
No matter what I've tried, every time I run "pod install", I receive the error `[!] Unable to find target`.

I've installed cocoapods following the instructions on [cocoapods.org](http://cocoapods.org/), and run `pod setup`, then `pod init`, and `pod install`.

Here is my `Podfile`:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.1'
pod 'MWFeedParser/NSString+HTML'
```

![screenshot 2014-12-28 16 24 08](https://cloud.githubusercontent.com/assets/3237612/5565023/fa16b170-8ead-11e4-9003-c5a298c4c978.png)

I've also quit Xcode, restarted the machine, etc. from other fixes I've found around the web, but there doesn't seem to be many people with this issue. Any idea what I'm missing here?

**Comment by azzouzze** [comment]
hi,

I have the same problem. 
Can you give more details on how you fixed the issue on your side?

thank you

**Comment by ranjitha-velolabs** [comment]
hi
I too have the same problem. 
Can you give more details on how you fixed the issue on your side?

**Comment by lalitpratap** [comment]
source 'https://github.com/CocoaPods/Specs.git'
target ‘check your target name spell correct’ do
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end
//#targetname should spell correctly
