### ISSUE TITLE
0.36.0.1.beta Blows up Basic Clean Installed App

### ISSUE THREAD

**Issue by jancel** [CocoaPods/CocoaPods#2996]
Please let me know what other info you need. Created a blank app, default options selected Universal for the iOS build options.  This is for a swift compiled app, I have not added anything to the project, would just really like to use cocoapods.  Added a Podfile

```
echo "platform :ios, '6.0'" > Podfile
```

```
echo "pod 'FontAwesomeKit', '~> 2.1.0'" >> Podfile
```

Attempting to build produces
```
Ld /Users/jancel/Library/Developer/Xcode/DerivedData/PictureThis-ftbwskpkrthngndvorpsdqtdiasq/Build/Products/Debug-iphonesimulator/PictureThis.app/PictureThis normal x86_64
    cd /Users/jancel/rokkit/PictureThis
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/jancel/Library/Developer/Xcode/DerivedData/PictureThis-ftbwskpkrthngndvorpsdqtdiasq/Build/Products/Debug-iphonesimulator -F/Users/jancel/Library/Developer/Xcode/DerivedData/PictureThis-ftbwskpkrthngndvorpsdqtdiasq/Build/Products/Debug-iphonesimulator -filelist /Users/jancel/Library/Developer/Xcode/DerivedData/PictureThis-ftbwskpkrthngndvorpsdqtdiasq/Build/Intermediates/PictureThis.build/Debug-iphonesimulator/PictureThis.build/Objects-normal/x86_64/PictureThis.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lPods-FontAwesomeKit -framework CoreText -framework UIKit -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/jancel/Library/Developer/Xcode/DerivedData/PictureThis-ftbwskpkrthngndvorpsdqtdiasq/Build/Intermediates/PictureThis.build/Debug-iphonesimulator/PictureThis.build/Objects-normal/x86_64/PictureThis.swiftmodule -mios-simulator-version-min=8.1 -lPods -Xlinker -dependency_info -Xlinker /Users/jancel/Library/Developer/Xcode/DerivedData/PictureThis-ftbwskpkrthngndvorpsdqtdiasq/Build/Intermediates/PictureThis.build/Debug-iphonesimulator/PictureThis.build/Objects-normal/x86_64/PictureThis_dependency_info.dat -o /Users/jancel/Library/Developer/Xcode/DerivedData/PictureThis-ftbwskpkrthngndvorpsdqtdiasq/Build/Products/Debug-iphonesimulator/PictureThis.app/PictureThis

ld: library not found for -lPods-FontAwesomeKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jancel** [comment]
Related to documentation. Is there a place where we should try to help improve the documentation?  I don't see any references to the confusion I had. 

Really, it's not abundantly clear from either "Installation" or "Getting Started" guide to close the current workspace and use the new pods workspace and this led to some issues with building/running the project. 

I'm back up and running.

**Comment by kylef** [comment]
Interesting, this second time someone has reported this issue in the past week and missed using the workspace (https://github.com/CocoaPods/CocoaPods/issues/2988#issuecomment-68230982). It's clear this is missed for people new to CocoaPods and I'm sure we can do better.

@jancel We would certainly love and welcome any contributions, the repository for the guides can be found at https://github.com/CocoaPods/guides.cocoapods.org/. You will notice there is a pull request button on the bottom of every page in the guides to make it easier.

![screen shot 2015-01-03 at 00 17 54](https://cloud.githubusercontent.com/assets/44164/5600913/0f20a196-92de-11e4-85dd-a23e0ea596f5.png)

---

`pod install` does mention this, do you think there is any wording we can change here to make it clearer?

![screen shot 2014-12-29 at 04 49 56](https://cloud.githubusercontent.com/assets/44164/5566223/27e399c0-8f16-11e4-9c0f-194ab03f6962.png)

The source code for this message can be found at https://github.com/CocoaPods/CocoaPods/blob/f9df489/lib/cocoapods/installer/user_project_integrator.rb#L97.

**Comment by kylef** [comment]
Maybe this message should be yellow and not green (@orta).

**Comment by jancel** [comment]
I did see the "pod install" but I didn't really understand what it meant.  Maybe something like "Please close down the editor and reopen from 'testa.xcworkspace'"  I read that, but not understanding what it was I was supposed to do, was my issue.  Again, I'm 24 hours into my iPhone dev experience.  I'm seasoned with Ruby & other cool stuff you guys use though.

**Comment by segiddins** [comment]
Maybe the message should also say 'instead of project.xcodeproj'?

**Comment by orta** [comment]
What's missing is the "close the other editor" bit, which could still have the original xcproject open. I presume this message only happens the first time you integrate?

Perhaps: `[!] Please close any current Xcode sessions and use 'testa.xcworkspace' for this project from now on.` ?

**Comment by cipriancaba** [comment]
Why not automatically open the new xcworkspace?

**Comment by kylef** [comment]
@cipriancaba I think there are a few cases where you may not want it automatically opened such as these:

- Automation of `pod install` in CI servers (travis ci etc)
- Running xcodebuild from command line and not the UI
- You don't use Xcode (App Code?)

**Comment by neonichu** [comment]
You also might still have the old Xcode window open, so the confusion would probably be even worse.

Ideally, the "Check Pods Manifest.lock" build phase could detect when building from the project, not the workspace and complain. There doesn't seem to be a way to do that, though, the environment is identical except for DerivedData directories.
