### ISSUE TITLE
"pod update" don't fetch fresh git repos

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#2997]
`pod update` don't fetch fresh version of git repository and keep using the old one.
Sequence is:
1. pod install
2. update git repo
3. pod update (changes not fetched)

pod 'ObjectivePGP', :git => 'https://github.com/krzyzanowskim/ObjectivePGP.git', :branch => :master

Fetching external sources
-> Pre-downloading: ObjectivePGP from https://github.com/krzyzanowskim/ObjectivePGP.git, commit c4652b63f5c9ac998c785590f09e697bb89a2ac8

while there is newer commit available.

Deleting Podfile.lock fix it and fresh data is fetched.

$ pod --version
0.35.0

**Comment by kylef** [comment]
Sounds like this was introduced via https://github.com/CocoaPods/CocoaPods/issues/1058 (/cc @segiddins).

**Comment by segiddins** [comment]
I believe I already put a fix in for this. I think it made it into 0.36.beta.1?

**Comment by kylef** [comment]
So it is, missed this one.

https://github.com/CocoaPods/CocoaPods/commit/d574946507e6a3d2e876c122430b711f49e833a7
