### ISSUE TITLE
Links to RubyGems semantic versioning pages are dead links and need to be replaced

### ISSUE THREAD

**Issue by iosdev-republicofapps** [CocoaPods/CocoaPods#3000]
Hi,

I'm about to try making my first CocoaPod (yay! :-) ) and I had some trouble with your documentation at http://guides.cocoapods.org/making/making-a-cocoapod.html .  In the *CocoaPods Versioning Specifics* you have two now dead links:

* [RubyGems Versioning Policies](http://docs.rubygems.org/read/chapter/7)
* [RubyGems version specifiers](http://docs.rubygems.org/read/chapter/16)

Both of these are dead and lead to nowhere.

Instead, I suggest you replace them with my best guess:

* [RubyGems Versioning Policies becomes http://guides.rubygems.org/patterns/#semantic-versioning](http://guides.rubygems.org/patterns/#semantic-versioning)
* [RubyGems version specifiers becomes http://guides.rubygems.org/patterns/#declaring-dependencies](http://guides.rubygems.org/patterns/#declaring-dependencies)

It was frustrating as a newbie to see these documentation links lead to dead (non-existent pages) so I wanted to help out but pointing this out and suggesting new pages.

Sorry if this is the wrong place to file documentation bugs.  Is there a better place?

Thanks

**Comment by segiddins** [comment]
We'd be thrilled to see a PR on https://github.com/CocoaPods/guides.cocoapods.org!

**Comment by iosdev-republicofapps** [comment]
My pleasure ... will do!  :-)

**Comment by iosdev-republicofapps** [comment]
Done: see https://github.com/CocoaPods/guides.cocoapods.org/pull/51

**Comment by iosdev-republicofapps** [comment]
I just created https://github.com/CocoaPods/CocoaPods/issues/3001 and I'd like to update that documentation as well: unclear how to add classes to my pod's Xcode project.

Any ideas?  :-)

Thanks!

**Comment by iosdev-republicofapps** [comment]
Also found one more out of date link and fixed it and updated the PR.

**Comment by orta** [comment]
Merged that PR, closing this issue, thanks @iosdev-republicofapps
