### ISSUE TITLE
Won't running pod setup with sudo create some root-owned stuff in my user-dir?

### ISSUE THREAD

**Issue by grav** [CocoaPods/CocoaPods#3002]
```
$ pod setup

"Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo."
```

This seems like a bad suggestion to me. Won't it create a ~/.cocoapods that is owned by root?

In my case, I just launched Xcode and agreed to the ULA, and then re-ran pod setup.

**Comment by kylef** [comment]
Any `pod` command will actually prevent you from running them as root and provide an error.

This isn't a message from the `pod` command directly, it looks like it's a message printed by another command we are running, such as `git`.

**Comment by neonichu** [comment]
Yah, that's probably `git`. Maybe we could add a check similar to homebrew to make this less confusing: <https://github.com/Homebrew/homebrew/blob/15806d6687ef5a9d233449acb49c8741d5d75a50/Library/Homebrew/cmd/doctor.rb#L1145-L1151>?

**Comment by kylef** [comment]
@neonichu Totally agree, changing the scope of this issue to implement that functionality.
