### ISSUE TITLE
pod lib create should support other targets besides iOS

### ISSUE THREAD

**Issue by iosdev-republicofapps** [CocoaPods/CocoaPods#3005]
Hi,

I like `pod lib create`, thanks for including it.  However, I'd like it to ask me a few more questions and create the project according to the answers:

* Do you want to include Mac OS X targets, iOS targets or both?
* Do you want to create Library, Framework or regular target?
* What are the minimum OS versions for iOS and OS X?

When creating a Mac OS X static library target I found it easier to just create the spodspec myself rather than try to massage the created template project into something that would work.

I'd be happy to help with this if somebody can give me some pointers as to where to start?

Thanks!

**Comment by orta** [comment]
Nope sorry, we're covering only the simplest use-cases in `pod lib create`. You're free to fork https://github.com/cocoapods/pod-template/ and add that yourself, it's very easy to use your own template ( see https://github.com/CocoaPods/pod-template/pull/86 ) but I wouldn't merge those changes back into our version. See the README in the repo for reasoning.

**Comment by gregcotten** [comment]
@orta Why not then cover the "simplest" use-case for both platforms? something like `pod lib create --platform osx`

**Comment by orta** [comment]
We've been debating doing something like that with the frameworks re-write, but I'd do a quick look to see how many pods actually support OS X before that to see if it's worth adding the extra overhead for most pods.

**Comment by iosdev-republicofapps** [comment]
Thanks @orta .

A lot of the big pods that I use support OS X:
AFNetworking
Specta
Expecta
OCMock

UI-specific and integration testing might not support OS X but a lot of other Objective-C libraries do.

I'm happy to help if needed?  :-)

**Comment by dbainbridge** [comment]
Is there a recommended template to use for building OS X pod and steps for it?

**Comment by orta** [comment]
I don't think anyone has created an OS X template for `pod lib create` alas

**Comment by frankrei** [comment]
I'm a bit stunned that OS X support seems to be such a low priority!?

**Comment by orta** [comment]
You're welcome to add it @frankrei :+1: - it's just not a priority for me

**Comment by bbugh** [comment]
Has there been any development on this in the last two years? I have no idea what I'm doing with Mac development or XCode, and I want to make an OSX-only cocoapod.

**Comment by orta** [comment]
No

**Comment by gregcotten** [comment]
#iOSMasterRace

**Comment by grosch** [comment]
Would be really nice to have this!

**Comment by amorde** [comment]
@grosch You are welcome to create a template yourself and submit a PR to https://github.com/cocoapods/pod-template/ - this is how new features are added!
