### ISSUE TITLE
0.36.0.beta.1 breaks archiving project as Mac App Archive

### ISSUE THREAD

**Issue by phranck** [CocoaPods/CocoaPods#3007]
#### Summary
After installation of 0.36.0.1.beta I noticed being unable to archive a Mac App project as a Mac application. Xcode just offers me "Generic Xcode Archive".

#### Steps to Reproduce
* create an empty "Cocoa Application" project
* do nothing but archiving of the product. As you can see, Xcode offers a valid *Mac App Archive*:

![valid Archive Type](https://cloud.githubusercontent.com/assets/871198/5613855/a84ddc40-94ea-11e4-8f52-f42c0bf9b7e5.png)

* close this project and create a Podfile within the project folder using this example (you can choose any pod):

```
platform :osx, "10.9"
xcodeproj "Test"

pod 'CCNStatusItemView'
```
* now fire `pod install`
* open the workspace
* archive again

#### Expected Results
The same valid *Mac App Archive* as shown above.

#### Actual Results
I can just archive as *Generic Xcode Archive*:

![genericxcodearchive](https://cloud.githubusercontent.com/assets/871198/5613871/e732c8d0-94ea-11e4-8518-344df3f127ac.png)

**Comment by clemensg** [comment]
Same here

**Comment by macguru** [comment]
Same here. He problem seems to be that the "Skip Install" flag is not set in the Pods project. As a temporary workaround you can just set it manually:
![screen shot 2015-01-27 at 00 36 30](https://cloud.githubusercontent.com/assets/191054/5910630/8fbcd8f6-a5bc-11e4-8446-6f6f812a9cdb.png)
