### ISSUE TITLE
`pod lib create SomeName` insists on Class Prefix

### ISSUE THREAD

**Issue by getaaron** [CocoaPods/CocoaPods#3013]
I have pod 0.36.0.beta.1 installed. Running `pod lib create SomeName` insists on a class prefix:

```
What is your class prefix?
 >

You need to provide an answer.
```

However, [class prefixes are no longer required in Swift](https://twitter.com/clattner_llvm/status/474730716941385729):

> Namespacing is implicit in swift, all classes (etc) are implicitly scoped by the module (Xcode target) they are in. no class prefixes needed

Requiring a class prefix fixes the Swift->Obj-C bridging issue, but for apps written purely in Swift, it seems like a shame to totally ignore the namespacing feature.

**Comment by segiddins** [comment]
Moved to https://github.com/CocoaPods/pod-template/issues/88.
