### ISSUE TITLE
Should linting flag unfilled name/email address?

### ISSUE THREAD

**Issue by squarefrog** [CocoaPods/CocoaPods#3014]
Just spotted PR https://github.com/CocoaPods/Specs/pull/12890 in Specs.

I presume the following is a placeholder declared somewhere

    "authors": {
      "YOUR NAME HERE": "YOUR EMAIL HERE"
    },

I cant find that placeholder declared anywhere and locally testing just pulls my information from Git. I suspect this may occur when no Git credentials are declared. Is it worth adding a lint test for this in Trunk?

**Comment by segiddins** [comment]
This would belong in the linter in CocoaPods/Core.

**Comment by squarefrog** [comment]
Moved to https://github.com/CocoaPods/Core/issues/214
