### ISSUE TITLE
Xcode 6 Cocoa Touch Framework - image not found error

### ISSUE THREAD

**Issue by shwetsolanki** [CocoaPods/CocoaPods#3015]
Hey, I am created the podspec file for the Cocoa Touch Framework. I have used "vendored_frameworks". Now when I try to install the podspec in my project, the Framework is added correctly. But when run the app, I get the following error.

**dyld: Library not loaded: @rpath/Some.framework/Some
Referenced from: /private/var/mobile/Containers/Bundle/Application/45B49F35-31E2-49F6-8102-26FF43F0BB2E/AppLifecycle.app/AppLifecycle
Reason: image not found**

I am sure this happening just because the framework is not added as Embedded Binaries and in the Project Target Settings. Could you tell me a way so that this is included in the podspec itself. And moreover, when I manually try to add the Some.framework to Embedded Binaries, its not listed.

Ref: https://github.com/CocoaPods/Specs/issues/12882

**Comment by neonichu** [comment]
Indeed, `vendored_frameworks` are currently not embedded - see also #1993 for the corresponding OS X issue.
