### ISSUE TITLE
Adding non-swift dependency to a Swift cocoapod doesn't include the non-swift dependency in the umbrella header

### ISSUE THREAD

**Issue by pt-arvind** [CocoaPods/CocoaPods#3019]
Adding non-swift dependency to a Swift cocoapod doesn't include the non-swift dependency in the umbrella header.

For example, if I create a new cocoapod library (pod lib create NewLib) and this NewLib has a dependency that looks like this:

  s.dependency 'KeychainItemWrapper', '~> 1.2'

That KeychainItemWrapper is not accessible anywhere in the cocoapod until I go to the umbrella header (for example: Pods-NewLib-NewLib/Pods-NewLib-NewLib-umbrella.h) and add the dependency in there manually. Have to do this every time I pod install.

**Comment by segiddins** [comment]
@pt-arvind you still need to import the dependency inside your pod's source files.

**Comment by pt-arvind** [comment]
@segiddins To my knowledge, you cannot import Obj-C code directly into a swift file. That's what the umbrella header is supposed to be for: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Given that these umbrella headers get re-created every time I do a 'pod install' wouldn't you say it's a bug that I would have to modify the Pod's umbrella header every time I do this?

**Comment by neonichu** [comment]
You can do it just fine, as long as you have a clang module, such as when using frameworks:

```swift
import KeychainItemWrapper

let foo = KeychainItemWrapper()
```

**Comment by pt-arvind** [comment]
oops! thanks a lot!
