### ISSUE TITLE
undefined symbols for architecture

### ISSUE THREAD

**Issue by romin991** [CocoaPods/CocoaPods#3020]
I have workspace that contains multiple projects inside.

and this is my podfile content : 

platform :ios, '7.1'
workspace 'instinctworkspace.xcworkspace'
xcodeproj 'islchat/islchat.xcodeproj'

inhibit_all_warnings!

target 'islchat' do
xcodeproj 'islchat/islchat.xcodeproj'
pod 'FMDB'
pod 'AFNetworking', '~> 2.5'

target 'instinct', :exclusive => true do
    platform :ios, '7.0'
    xcodeproj 'istlogin/instinct.xcodeproj'
    pod 'FMDB'
    pod 'AFNetworking', '~> 2.5'
end
end

xcodeproj 'tdllogin/TDLLogin.xcodeproj'
inhibit_all_warnings!
target 'TDLLogin' do
xcodeproj 'tdllogin/TDLLogin.xcodeproj'
pod 'FMDB'
pod 'AFNetworking', '~> 2.5'

target 'instinct', :exclusive => true do
    platform :ios, '7.0'
    xcodeproj 'istlogin/instinct.xcodeproj'
   
end
end

---------

but after pod install, i can't build it..  this is the error message : 
Undefined symbols for architecture armv7s:
  "_OBJC_CLASS_$_AFJSONRequestSerializer", referenced from:
      objc-class-ref in libTDLLogin.a(TDLLogin.o)
  "_OBJC_CLASS_$_FMDatabase", referenced from:
      objc-class-ref in libTDLLogin.a(mySingleton.o)
      objc-class-ref in libislchat.a(sqliteHelper.o)
  "_OBJC_CLASS_$_AFHTTPRequestOperationManager", referenced from:
      objc-class-ref in TDZAppDelegate.o
      objc-class-ref in libTDLLogin.a(TDLLogin.o)
ld: symbol(s) not found for architecture armv7s

(before this, the error is undefined symbols for arm64.. and i delete arm64 from the architecture)

please help .. thx :D

**Comment by mverderese** [comment]
2 questions. Is there any error output after running pod install? Are you able to successfully run islchat or does it have the same errors?

**Comment by romin991** [comment]
@mverderese i'm able to run the islchat and tdllogin static lib... 
there is no error output after running pod install... only warning... here's the output : 
---------
Analyzing dependencies

CocoaPods 0.36.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Using AFNetworking (2.5.0)
Using FMDB (2.4)
Generating Pods project
Integrating client projects

[!] The `islchat [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `../Pods/Target Support Files/Pods-islchat/Pods-islchat.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `islchat [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `../Pods/Target Support Files/Pods-islchat/Pods-islchat.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `TDLLogin [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `../Pods/Target Support Files/Pods-TDLLogin/Pods-TDLLogin.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `TDLLogin [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `../Pods/Target Support Files/Pods-TDLLogin/Pods-TDLLogin.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `instinct [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `../Pods/Target Support Files/Pods-instinct/Pods-instinct.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `instinct [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `../Pods/Target Support Files/Pods-instinct/Pods-instinct.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
--------------


thx for replying!

**Comment by mverderese** [comment]
Ah I think I've had this problem before. Try changing this configuration:
![screen shot 2015-01-08 at 12 40 24 am](https://cloud.githubusercontent.com/assets/3136176/5658389/08c22b04-96cf-11e4-9d83-056c389a7810.png)

To this:
![screen shot 2015-01-08 at 12 41 22 am](https://cloud.githubusercontent.com/assets/3136176/5658393/1d7f798e-96cf-11e4-9f91-3c0b206d09b2.png)

for each one of your build configurations and then running pod install again.

**Comment by romin991** [comment]
@mverderese  ahh... still the same error :(((

**Comment by neonichu** [comment]
Please follow the instructions from the warnings and correct your `OTHER_LDFLAGS`
