### ISSUE TITLE
set GCC_INPUT_FILETYPE in podspec has no effect

### ISSUE THREAD

**Issue by TinyQ** [CocoaPods/CocoaPods#3021]
I put this line in my podspec:
`s.xcconfig =  { 'GCC_INPUT_FILETYPE' => 'sourcecode.cpp.objcpp'}`

and then import this pod from another project. After running "pod install --no-repo-update", the pod is imported and under Pods folder the xcconfig files have this line:
`GCC_INPUT_FILETYPE = sourcecode.cpp.objcpp`

But when I open the project.pbxproj, it contains no 'GCC_INPUT_FILETYPE' and the build failed.

I'm using pod 0.35.0 and XCode 6.1.1

Does anyone know how to fix this?

Thanks!

**Comment by neonichu** [comment]
You should simply name your ObjC++ source code files as .mm, then there is no need to change the global definition of GCC_INPUT_FILETYPE.

**Comment by TinyQ** [comment]
But this solution requires user of my library to change their source code file extension while GCC_INPUT_FILETYPE option requires fewer changes.

**Comment by neonichu** [comment]
It can lead to very hard to debug issues for your users, though, because C++ is  not a strict superset of C.
