### ISSUE TITLE
undefined method `licence=', while it check against "license"

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#3022]
$ pod lib lint

!] Invalid `CryptoSwift.podspec` file: undefined method `licence=' for #<Pod::Specification name="CryptoSwift">. Updating CocoaPods might fix the issue.

problem is that it check for "license" key, not "licence" key

**Comment by neonichu** [comment]
Unsure I follow, the attribute is called `license`, <http://guides.cocoapods.org/syntax/podspec.html#license> and you are using `licence` in your spec.

**Comment by krzyzanowskim** [comment]
oh damn, you are right, I just assume that it complain about missing required key "licence", not the unknown licence.

**Comment by krzyzanowskim** [comment]
So now I'm complaining about warning message ;)

**Comment by neonichu** [comment]
It is also against our desire to use British English, don't let @orta find out :P :uk:

**Comment by kylef** [comment]
@neonichu We need to change license to licence :gb:

**Comment by krzyzanowskim** [comment]
+23

**Comment by orta** [comment]
probably better to do an alias to support both at this point

**Comment by krzyzanowskim** [comment]
Change it to licence, and if maintainer wont update accordingly, remove podspec from repository. You can do it.

;)

**Comment by segiddins** [comment]
As such an alias would only work in the ruby DSL, I'm in favor of keeping the 1 correct way of specifying the license.

**Comment by orta** [comment]
Think this is reasonable ( given that we have a derivative JSON format that would only support one ) closing.

Shame.
