### ISSUE TITLE
Could not build Objective-C module 'mySDK'

### ISSUE THREAD

**Issue by leviyehonatan** [CocoaPods/CocoaPods#3023]
i am trying to createa a framawork using two other frameworks Alamofire, SwiftyJSON

i got this error

my podfile looks like this:
platform :ios, '8.0'

inhibit_all_warnings!
pod 'SwiftyJSON', :git => "https://github.com/orta/SwiftyJSON", :branch => "podspec"
pod 'Alamofire', :git => "https://github.com/mrackwitz/Alamofire.git", :branch => "podspec"

and anyhow, am i going the right direction? my aim is to be able to distribute my framework without exposing the code for it? is it possible?

--Yehonatan

**Comment by neonichu** [comment]
In principal, this can work. See CocoaPods/swift#17 for discussion of when the error you are receiving can occur.
