### ISSUE TITLE
error for pod install AWS.SKD

### ISSUE THREAD

**Issue by luyishisan** [CocoaPods/CocoaPods#3026]
luyitekiMac:wardtester1.2.2 luyi$ pod install
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p598 (2014-11-13 revision 48408) [x86_64-darwin14.0.0]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /Users/luyi/.rvm/rubies/ruby-2.0.0-p598/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 56feac4fbb5d02bf5f49543e66ba199bb588c3c9
```

### Plugins

```
cocoapods-plugins : 0.3.2
cocoapods-trunk   : 0.4.1
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
source ‘https://github.com/CocoaPods/Specs.git'

pod ‘AWSiOSSDKv2’
pod ‘AWSCongitoSync’
```

### Error

```
SyntaxError - /Users/luyi/Desktop/wardtester1.2.2/Podfile:1: unknown regexp options - gthb
/Users/luyi/Desktop/wardtester1.2.2/Podfile:1: syntax error, unexpected tSTRING_BEG, expecting end-of-input
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:247:in `eval'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:247:in `block in from_ruby'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:244:in `new'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:244:in `from_ruby'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-core-0.35.0/lib/cocoapods-core/podfile.rb:220:in `from_file'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-0.35.0/lib/cocoapods/config.rb:176:in `podfile'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:108:in `verify_podfile_exists!'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-0.35.0/lib/cocoapods/command/project.rb:100:in `run'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/luyi/.rvm/gems/ruby-2.0.0-p598@global/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/luyi/.rvm/rubies/ruby-2.0.0-p598/bin/pod:23:in `load'
/Users/luyi/.rvm/rubies/ruby-2.0.0-p598/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

It appears to have originated from your Podfile at line 1.

Search for existing github issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%2FUsers%2Fluyi%2FDesktop%2Fwardtester1.2.2%2FPodfile%3A1%3A+unknown+regexp+options+-+gthb%0A%2FUsers%2Fluyi%2FDesktop%2Fwardtester1.2.2%2FPodfile%3A1%3A+syntax+error%2C+unexpected+tSTRING_BEG%2C+expecting+end-of-input&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

i hv been try many times , but still cannot install the pod      QUQ

**Comment by segiddins** [comment]
Your Podfile is using fancy quotes. It should work if you change it to:

```ruby
source 'https://github.com/CocoaPods/Specs.git'

pod 'AWSiOSSDKv2'
pod 'AWSCongitoSync'
```
