### ISSUE TITLE
pod install objc and swift

### ISSUE THREAD

**Issue by aaronz8** [CocoaPods/CocoaPods#3028]
I'm trying to install JSQMessagesViewController as well as Alamofire, and I get some errors. Here are the combinations I've tried:

JSQMessagesViewController (Objc)
-> Works

JSQMessagesViewController
Alamofire (Swift)
-> "JSQMessages.h file not found" in bridging header

JSQMessagesViewController
AFNetworking (Objc)
-> Works

JSQMessagesViewController
SwiftyJSON (Swift)
-> "JSQMessages.h file not found" in bridging header

Is there something in the setup process for a swift package I'm missing, or is this something that's expected (if so, what can I do to get around it)? Thanks!

**Comment by segiddins** [comment]
Can you please share your bridging header?

**Comment by aaronz8** [comment]
#import "JSQMessages.h"
    #import "JSQMessageData.h"

**Comment by segiddins** [comment]
Since the inclusion of Swift pods makes CocoaPods use frameworks, you must use:

```objc
#import < JSQMessagesViewController /JSQMessages.h>
#import < JSQMessagesViewController /JSQMessageData.h>

# or, alternatively

@import JSQMessagesViewController;
```

**Comment by aaronz8** [comment]
Interestingly, the first method gets rid of the error in the bridging header but I think it doesn't actually connect the package - I get lots of "Use of unresolved identifier 'JSQMessage' in my code. However, `@import JSQMessagesViewController'` works perfectly.

Thanks for the quick response!

**Comment by neonichu** [comment]
BTW, it is not necessary to use the bridging header with frameworks, you are able to directory import into Swift.

**Comment by thehellsoul** [comment]
Sorry to but i tried hours to search but cannot find a solution for this.
This is my bridging header file:

//@import RestKit;
//@import reverseGeoCoder;
//@import UIColor+HexString;
//#import <FXBlurViewFXBlurView.h>
//#import "NSString+MD5.h"
//#import "NSDate+TimeAgo.h"
//#import <ASIHTTPRequest/ASIFormDataRequest.h>
//#import "ASIHTTPRequest.h"
//#import "ASIHTTPRequestDelegate.h"
//#import "UIImage+ImageCompress.h"
@import RKValueTransformers;
@import SSKeychain;
@import MBProgressHUD;
#import "HMDiallingCode.h"
@import APAddressBook;
@import Canvas;
@import ILTranslucentView;
@import LLARingSpinnerView;
@import ICGTransitionAnimation;
@import PKImagePicker;
@import SIOSocket;
@import ISO8601DateFormatter;
@import JBChartView;
#import "BBAES.h"
#import "GM_AES128_CTR.h"
@import MHPrettyDate;
@import STTweetLabel;
@import SIAlertView;
@import SAMGradientView;
@import MZTimerLabel;
@import SevenSwitch;
@import FMMoveTableView;
@import EAMTextView;
@import Reachability;

and this is my Podfile:

pod 'RestKit'
pod 'MBProgressHUD'
pod 'SSKeychain'
pod 'APAddressBook'
pod 'APAddressBook/Swift'
pod 'IOS-Offline-GeoCoder'
pod 'Canvas'
pod 'ILTranslucentView'
pod 'LLARingSpinnerView'
pod 'UIColor-HexString'
pod 'FXBlurView'
pod 'ICGTransitionAnimation'
pod 'PKImagePicker'
pod 'MD5Digest'
pod 'SIOSocket'
pod 'NSDate+TimeAgo'
pod 'ISO8601DateFormatter'
pod 'ASIHTTPRequest'
pod 'UIImage+ImageCompress'
pod 'JBChartView'
pod 'MHPrettyDate'
pod 'STTweetLabel'
pod 'SIAlertView'
pod 'SAMGradientView'
pod 'MZTimerLabel'
pod 'SevenSwitch'
pod 'FMMoveTableView'
pod 'EAMTextView'
pod 'CryptoSwift'

I can't / (don't know how to) import the Pods with comment mark. Am i missing somethings? Thanks in advanced.

**Comment by RajendrasinhParmar** [comment]
Hello, 

I'm facing same issue. Can any one please help me.
