### ISSUE TITLE
Present a message when taking an existing non-swift project and migrating to frameworks

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#3029]
Lets say you add a new pod that has to be a framework. 

You don't specifically know that it has swift inside and it's going to convert your project to use frameworks, and suddenly things that are not the Pod you've been working on breaks. Offering the option before the migration (especially given that right now very few libraries will be developer tested. )

It will also force your application to be 8.0+, unless you've read the documentation / guides then you wouldn't know any of these constraints at the moment and it could be _very_ likely that this is not something you want to do.

Presenting a message on the first `pod install` that `"Including Moya will convert your dependencies to frameworks, this will require you to set 8.0 to the target SDK and its possible that your other pods have not been tested with frameworks yet. Are you sure? [Yn]`

**Comment by neonichu** [comment]
I don't think it is a good idea to have `pod install` be interactive, as it can hang e.g. hang your CI, it seems more suited as a warning. Another possibility would be requiring an explicit `use_frameworks!` and fail if you are using a Pod written in Swift.

In any case, the 8.0 dependency will come transitively with the selected Pod anyway and shouldn't need a secondary check.

**Comment by orta** [comment]
:+1:
