### ISSUE TITLE
Link static library only in debug mode (cocoapods 0.33.1)

### ISSUE THREAD

**Issue by YuyeQingshan** [CocoaPods/CocoaPods#3033]
I add some pods(FLEX, Tweaks, etc) to my project, And I want link them to my target only in debug mode.

I add this config to my Podfile

``` podfile
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        if target.name == 'Pods-FLEX'
            target.build_configurations.each do |config|
                if config.name == 'Release'
                    config.build_settings['EXCLUDED_SOURCE_FILE_NAMES'] = 'FLEX*'
                end
            end
        end
    end
end
```
It works well, the FLEX source file won't be compiled.But the target 'Pods-FLEX' in Pods project still be generated and linked to my targets.

Is there some way to avoid linking Debug libraries to Targets in cocoapods?

**Comment by neonichu** [comment]
You should upgrade to CP 0.34 and use configuration specific Pods as described in <http://blog.cocoapods.org/CocoaPods-0.34/>.
