### ISSUE TITLE
Migration for local podspecs from DSL to JSON

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/CocoaPods#3038]
The recently added JSON pretty-printed specs pose an issue with existing Pods directories, as two specs can exist for the same Pod. CP prefers the non-JSON variant leading to confusing results. All non-JSON specs in the "Local Podspecs" directory should be converted automatically to avoid this.

**Comment by segiddins** [comment]
My migration broke things, and I don't have time to fix it right now so I reverted.
