### ISSUE TITLE
0.36.0.beta.1 Creating a swift pod with an example project through pod lib create results in a non working pod project

### ISSUE THREAD

**Issue by jeroenleenarts** [CocoaPods/CocoaPods#3039]
When creating a pod lib with ```pod lib create ...``` the resulting project is not working "out of the box" when working with swift code in the pod and the example project.

The module name of the Pod matches the Example project's module name and thus the Pod itself will not be resolved. For an example of this, please see this repository:
https://github.com/jeroenleenarts/swift-pod-trial

Tnx to @ashfurrow for helping debug this: http://artsy.github.io/blog/2015/01/04/cocoapods-and-frameworks/#comment-1794251987

**Comment by orta** [comment]
Yeah, this is a known issue, no-one's got around to it yet. You're welcome to contribute: https://github.com/CocoaPods/pod-template/issues/88
