### ISSUE TITLE
Adding Files to Development Pods Through Xcode UI Doesn't Automatically Select the Source Files Folder

### ISSUE THREAD

**Issue by paulrehkugler** [CocoaPods/CocoaPods#3040]
Children of the "Development Pods" group in the project file, should set their group path to the `"source_files"` key in the corresponding Podspec, so that each individual file inside the group doesn't have to have a relative path that includes the path listed in `"source_files"`.

This would make adding files to development pods simpler, because the destination path of the file would already be populated in the Xcode UI, instead of the user needing to choose the appropriate relative path  to be detected by CocoaPods (which is already known to CocoaPods in the `"source_files"` key).

Maybe there are some edge cases here for complex directory structures, however this could be solved by making subgroups for each folder within the Development Pod group.

**Comment by orta** [comment]
This is fixed in `0.36` beta I believe, can you test it?

**Comment by segiddins** [comment]
This should've been implemented in https://github.com/CocoaPods/CocoaPods/commit/44e3dab48d83a4672d9fd074e52ac30c2b904df6.

**Comment by paulrehkugler** [comment]
Looks like it was. :+1:
