### ISSUE TITLE
XCode 6.1.1 - Use of Empty Enum

### ISSUE THREAD

**Issue by tobinharris** [CocoaPods/CocoaPods#3042]
I'm getting this error after updating to XCode 6.1.1.

`Could not build module UIKit` and `Use of empty enum`

I'm on CoocaPods 0.35.0. 

Any ideas how to fix?

![image](https://cloud.githubusercontent.com/assets/25578/5773812/cccb4b58-9d5e-11e4-9815-db682b4efa3a.png)

**Comment by segiddins** [comment]
@tobinharris this seems like an issue with `BBBadgeBarButtonItem` rather than CocoaPods itself. Additionally, we'd need [more information](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#bug-reports) to be able to debug if it is indeed an issue with CocoaPods itself.

**Comment by tobinharris** [comment]
Thanks @segiddins. This error is showing up on 2 pods since installing 6.1.1. I've rolled back to XCode 6.1 and the problem has gone away.

I'll fish out the extra information you need.
