### ISSUE TITLE
Changing the `podspec` path for an installed Pod makes Cocoapods look for it in a local path

### ISSUE THREAD

**Issue by ShayDavidson** [CocoaPods/CocoaPods#3043]
I had a Pod installed through a custom `podspec` like this:

``` ruby
pod 'MyPod', :podspec => 'https://gist.githubusercontent.com/podspec_1_defined_in_gist.podspec'
```

I had to change the path of the `podspec` to a different one:

``` ruby
pod 'MyPod', :podspec => 'https://gist.githubusercontent.com/podspec_2_defined_in_gist.podspec'
```

And once I ran `pod install` I got this message:

```
[!] No podspec found for `MyPod` in /Users/my_username/<path_to_my_project>/Pods/MyPod/MyPod.podspec.json
```

I managed to solve this by commenting out the `MyPod` pod from my `Podfie`, running `pod install`, uncomment the pod, and then run `pod install` again. Nevertheless, this looks like a bug.

**Comment by segiddins** [comment]
@kylef did you investigate this?

**Comment by orta** [comment]
I bet this would get caught now in 0.39 because of the podfile SHA checker too

**Comment by segiddins** [comment]
@orta that's not in 0.39, and it won't help if a `pod install` doesn't fix things.
