### ISSUE TITLE
Release scheme error: ld: library not found for -lPods-Afnetworking

### ISSUE THREAD

**Issue by dannyskim** [CocoaPods/CocoaPods#3045]
when doing a pod install, i get the following warnings:

<pre><code>[!] The `sherman [DebugProd]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debugprod.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `sherman [DebugTest]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debugtest.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `sherman [ReleaseProd]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.releaseprod.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `sherman [ReleaseTest]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.releasetest.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
</code></pre>

After changing those values that cocoapods CLI told me to, I still get the following build error when trying to archive any of the 4 schemes that I'm using for debug and release:

<pre><code>
Ld /Users/daniel.kim/Library/Developer/Xcode/DerivedData/project-dmzuaarzxovfpwglmdnamvbivecp/Build/Intermediates/ArchiveIntermediates/project-release-prod/IntermediateBuildFilesPath/project.build/ReleaseProd-iphoneos/project.build/Objects-normal/arm64/project normal arm64
    cd /Users/daniel.kim/Projects/7-11/project-ios-2-0
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -L/Users/daniel.kim/Library/Developer/Xcode/DerivedData/project-dmzuaarzxovfpwglmdnamvbivecp/Build/Intermediates/ArchiveIntermediates/project-release-prod/BuildProductsPath/ReleaseProd-iphoneos -L/Users/daniel.kim/Projects/7-11/project-ios-2-0/Pods/FlurrySDK/Flurry -F/Users/daniel.kim/Library/Developer/Xcode/DerivedData/project-dmzuaarzxovfpwglmdnamvbivecp/Build/Intermediates/ArchiveIntermediates/project-release-prod/BuildProductsPath/ReleaseProd-iphoneos -filelist /Users/daniel.kim/Library/Developer/Xcode/DerivedData/project-dmzuaarzxovfpwglmdnamvbivecp/Build/Intermediates/ArchiveIntermediates/project-release-prod/IntermediateBuildFilesPath/project.build/ReleaseProd-iphoneos/project.build/Objects-normal/arm64/project.LinkFileList -dead_strip -ObjC -lFlurry_5.4.0 -lPods-AFNetworking -lPods-AFOAuth2Client -lPods-AsyncImageView -lPods-Bugsnag -lPods-FXPageControl -lPods-FlurrySDK -lPods-ISO8601DateFormatter -lPods-MBProgressHUD -lPods-MMDrawerController -lPods-Mantle -lPods-RSBarcodes -lc++ -lz -framework AVFoundation -framework CoreGraphics -framework CoreImage -framework Foundation -framework MediaPlayer -framework MobileCoreServices -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -weak_framework AdSupport -weak_framework StoreKit -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -force_load -Xlinker /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a -Xlinker -add_ast_path -Xlinker /Users/daniel.kim/Library/Developer/Xcode/DerivedData/project-dmzuaarzxovfpwglmdnamvbivecp/Build/Intermediates/ArchiveIntermediates/project-release-prod/IntermediateBuildFilesPath/project.build/ReleaseProd-iphoneos/project.build/Objects-normal/arm64/project.swiftmodule -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=7.0 -lPods -Xlinker -dependency_info -Xlinker /Users/daniel.kim/Library/Developer/Xcode/DerivedData/project-dmzuaarzxovfpwglmdnamvbivecp/Build/Intermediates/ArchiveIntermediates/project-release-prod/IntermediateBuildFilesPath/project.build/ReleaseProd-iphoneos/project.build/Objects-normal/arm64/project_dependency_info.dat -o /Users/daniel.kim/Library/Developer/Xcode/DerivedData/project-dmzuaarzxovfpwglmdnamvbivecp/Build/Intermediates/ArchiveIntermediates/project-release-prod/IntermediateBuildFilesPath/project.build/ReleaseProd-iphoneos/project.build/Objects-normal/arm64/project

ld: library not found for -lPods-AFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code></pre>

Tried searching through tickets but couldn't find any answers.

**Comment by segiddins** [comment]
Well, did you follow the instructions in the warning?

**Comment by dannyskim** [comment]
Yes, I've updated my post to use the proper markdown format so my comments in my original post are more pronounced.

**Comment by segiddins** [comment]
Could you share your Podfile?

**Comment by dannyskim** [comment]
<pre><code
platform :ios, '7.0'
xcodeproj "project.xcodeproj" , { 'DebugProd' => :debug, 'DebugTest' => :debug, 'ReleaseProd' => :release, 'ReleaseTest' => :release }

workspace './project'
pod 'Bugsnag', :git => "https://github.com/bugsnag/bugsnag-cocoa.git"
pod 'FlurrySDK', '~> 5.3'
pod 'AFNetworking', '~> 1.3.3'
pod 'AFOAuth2Client', '~> 0.1.2'
pod 'ISO8601DateFormatter', '~> 0.7'
pod 'Mantle', '~> 1.3.1'
pod 'MMDrawerController', '~> 0.5.7'
pod 'RSBarcodes', '~> 0.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'AsyncImageView', '~> 1.5.1'
pod 'FXPageControl', '~> 1.4'
</code></pre>

**Comment by segiddins** [comment]
Have you tried cleaning before building?

**Comment by dannyskim** [comment]
Yep, i've tried cleaning, clearing out derived data, changing project settings to workspace relative, cleared out xcode cache in all relevant OSX system folders

**Comment by dannyskim** [comment]
As a note, the first scheme doesn't fail when building, with is my debug-prod scheme.  It archives and works successfully.  There is some mention on the troubleshooting cocoapods page about only the first target being specific automatically by cocoapods and that <code>link_with</code> needs to be used to specify other targets, but all I have is 4 schemes and one target, not 4 targets... 

What do i need to do to specify and direct cocoapods to those builds?

**Comment by samidaik00** [comment]
Hi, I believe I am having the same issue suddenly.. Not sure how it just happened.. Did you get around that ? 
Thanks

**Comment by fealonelei** [comment]
me too 
ld: library not found for -lPods-XcodeEditor
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dannyskim** [comment]
Yes, I did manage to fix it. 

If you go into your schemes

![screen-shot-2015-01-22-at-9 11 58-pm](https://cloud.githubusercontent.com/assets/2079623/5869239/94c86dae-a27b-11e4-9556-3a7df8108275.png)

Click on the schemes where it's blurred out, click on <code>Edit Scheme... -> Expand Archive -> Archive -> Build Confugiration</code>, select the one that matches your Scheme.

That fixed it for me at least.

**Comment by fealonelei** [comment]
It can not help me

2015-01-23 11:15 GMT+08:00 Daniel Kim <notifications@github.com>:

**Comment by githhhh** [comment]
这里可以帮助你
http://blog.kingiol.com/blog/2013/12/03/fix-cocoapods-warning-on-ios7-64bit/

**Comment by kylef** [comment]
I'm closing this due to the original issue was solved by the original poster.

For those of you having similar issues, I'd suggest taking them to StackOverflow or an appropriate forum for questions like these.
