### ISSUE TITLE
syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('

### ISSUE THREAD

**Issue by zlc000190** [CocoaPods/CocoaPods#3049]
### Stack

```
   CocoaPods : 0.34.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.1 (6A1052d)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 78dec2644e47aa272fb8c5ddf27a2e23e99c0a50
```

### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.1
```

### Podfile

```ruby
platform:ios,
pod 'MJRefresh',
pod 'MBProgressHUD',
pod 'FPPopover',
pod 'BWStatusBarOverlay',
pod 'Zbar',
pod 'ASIHTTPRequest',
pod 'SDWebImage',



## Error

```
SyntaxError - /Users/soufunlc/Desktop/newzxb/homezxb/Podfile:2: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
pod 'MJRefresh',
     ^
/Users/soufunlc/Desktop/newzxb/homezxb/Podfile:2: syntax error, unexpected ',', expecting end-of-input
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:247:in `eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:247:in `block in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:51:in `instance_eval'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:51:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:244:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:244:in `from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.34.1/lib/cocoapods-core/podfile.rb:220:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/config.rb:176:in `podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command.rb:101:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.34.1/bin/pod:33:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Those commas don't belong in your Podfile.

**Comment by zlc000190** [comment]
just commas error?     but i can't find what's wrong commas. it seems all is right.

**Comment by orta** [comment]
you don't need the comma at all, [Example](https://github.com/artsy/eidolon/blob/master/Podfile)

**Comment by zlc000190** [comment]
Thanks  a  lot.   @segiddins    @orta   

i  remove  all commas.  It  does  work for me.
