### ISSUE TITLE
New version of ReactiveCocoa leads a lot of my pods to crash

### ISSUE THREAD

**Issue by marcelosalloum** [CocoaPods/CocoaPods#3053]
Hey guys,

since this morning (January 20th 2015) It looks like there is a new version of ReactiveCocoa, so when I run pod install, I get 2 new libs being installed:
**Installing LlamaKit (0.1.1)
Installing ReactiveCocoa 3.0.0-alpha.1 (was 2.4.2)**
, then when I try to build my project, I get the following message:
**error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker**

They would not be installed a couple days ago and it seems the ReactiveCocoa has been updated to version 3. The problem is that a lot of my pods reference ReactiveCocoa without specifying a version and the new ReactiveCocoa contains swift code within, which is not supported by cocoapods so far.

This is making my Pod project to crash and I don't know how to force a specific version (2.4.2, for instance), since it is part of a lot of my libs.

Any ideas?

Thanks,

**Comment by neonichu** [comment]
Lock the dependency using an explicit version in your podspec: <http://guides.cocoapods.org/syntax/podspec.html#dependency>

You can also add ReactiveCocoa as an explicit dependency with version constraints in your Podfile and lock it that way.

**Comment by marcelosalloum** [comment]
Thank you man,

I fixed (avoided) the error by adding **pod 'ReactiveCocoa', '2.4.2'** to my Podfile
