### ISSUE TITLE
RuntimeError - [Xcodeproj] Consistency issue: build setting `IPHONEOS_DEPLOYMENT_TARGET` has multiple values

### ISSUE THREAD

**Issue by irace** [CocoaPods/CocoaPods#3055]
Is there any way to debug the following error message any further? Without any information as to what target it is seeing the inconsistency for/where it is getting these values from, it's impossible for me to debug,

```
RuntimeError - [Xcodeproj] Consistency issue: build setting `IPHONEOS_DEPLOYMENT_TARGET` has multiple values: `{"Release"=>"8.0", "Debug"=>"8.0", "Profile"=>"7.1", "App Store"=>"7.1", "In House"=>"7.1"}`
```

My project and app targets have deployment targets of 7.1. My share extension target has a deployment target of 8.0.

My Podfile looks more or less as follows (`platform :iOS, '8.0'` is required under `target :share_extension`, or else I get an error about being unable to install `PodThatOnlyWorksOn8`):

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

target :app do
    link_with 'App'

    pod 'FooBarBaz'
end

target :share_extension do
  platform :ios, '8.0'

  link_with 'ShareExtension'

  pod 'PodThatOnlyWorksOn8'
end
```

When I created a brand new Xcode project and set it up similarly, it worked just fine. This error occurs when trying to `pod install` on my existing, much more complicated project.

**Comment by neonichu** [comment]
That error is thrown here: <https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/project/object/native_target.rb#L79>

Did you try running `pod install --verbose` to see if that gives you a hint on which target it operates on when that error occurs?

**Comment by irace** [comment]
Yeah, the error does in fact occur while trying to install the first share extension target:

```
- Installing target `Pods-share_extension-LibraryName` iOS 8.0
```

However, this still doesn't really help me track down the issue since I've verified that the share extension target is configured to use the 8.0 deployment target in all cases.

**Comment by neonichu** [comment]
I think I can reproduce the issue now: it happens if the Pods project and a Pod target have different deployment target and there are more than the standard "Debug" and "Release" build configurations.

**Comment by irace** [comment]
> and there are more than the standard "Debug" and "Release" build configurations.

This would explain why it isn’t reproducible in my sample project.

**Comment by irace** [comment]
Also my colleague @brianmichel was able to tweak the CocoaPods source in order to get it to work:

> so in native_target.rb:54, if you just return target_settings and don’t try to merge the values.

@neonichu @kylef Any ideas for a workaround that doesn't involve modifying CocoaPods source?

**Comment by brianmichel** [comment]
> This would explain why it isn’t reproducible in my sample project.

Yup, was just about to chime in on this if I patch the xcodeproj library to not attempt to merge the project and target settings, but instead just return the target settings. Things seem to integrate correctly. 

Basically changing, 
```ruby
def resolved_build_setting(key)
  target_settings = build_configuration_list.get_setting(key)
  project_settings = project.build_configuration_list.get_setting(key)

  target_settings.merge(project_settings) do |_key, target_val, proj_val|
    target_val || proj_val
  end
end
```
to 
```ruby
def resolved_build_setting(key)
  target_settings = build_configuration_list.get_setting(key)
  
  target_settings
end
```

Granted, I don't know what problems this would introduce, it just lets the installation complete ¯\\_(ツ)_/¯

**Comment by neonichu** [comment]
Can't think of a workaround, as any `post_install` trickery would come too late in the process. 

The root cause seems to be that the Pod targets are only created with the default build configurations whereas the Pods project is created with all available configurations from the user project therefore creating the mismatch.

**Comment by kylef** [comment]
Workaround could be running CocoaPods with the `--no-integrate`. Then manually integrating (or integrate with the patched CocoaPods before).

**Comment by irace** [comment]
Thanks @kylef. I'm sure it's hard to say, but does this seem like the type of thing that could/would be fixed in the semi-short term?

**Comment by segiddins** [comment]
@neonichu why would that cause the issue?

**Comment by neonichu** [comment]
@segiddins merging project and target settings will end up with some configurations having the deployment target of the project and some that of the target => multiple values

**Comment by neonichu** [comment]
Turns out this is actually an issue with Xcodeproj: CocoaPods/Xcodeproj#228
