### ISSUE TITLE
unknown option character 'X' in: -Xlinker

### ISSUE THREAD

**Issue by ArtSabintsev** [CocoaPods/CocoaPods#3056]
Hi guys,

I'm trying to push the latest version of [Siren](http://github.com/ArtSabintsev/Siren) (0.2.0) to CocoaPods.

I get the following error when running `pod trunk push`:

```
[!] Found podspec `Siren.podspec`
Validating podspec
 -> Siren (0.2.0)
    - ERROR | [xcodebuild]  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

[!] The podspec does not validate.
```

Is the problem on your end, or is it PEBKC? :)

If the problem is PEBKAC, could I get some guidance? 

Thanks!

cc @getaaron

**Comment by neonichu** [comment]
Sounds to me as if you're not using the beta version to push.

**Comment by ArtSabintsev** [comment]
Yup, apparently i had an older pre-release installed. A simple 'gem update' did the trick!

Thanks, @neonichu!

**Comment by matthewpalmer** [comment]
Was having this problem. I had to do `sudo gem uninstall cocoapods` and choose to uninstall all versions (apparently I had 5 different versions installed) and then `sudo gem install cocoapods --pre` to get up to date. Hopefully this note helps someone in the future :)

**Comment by ArtSabintsev** [comment]
@matthewpalmer Thanks for posting your resolution technique. For me, if you can believe it or not, I simply had re-`source` my `bash_profile` file as I had made a breaking change an hour earlier.

**Comment by ArtSabintsev** [comment]
the gem-update I mentioned I did after the fact, and it didn't do much.
