### ISSUE TITLE
The resource bundle target does not honor xcconfig value from Podspec

### ISSUE THREAD

**Issue by Thomvis** [CocoaPods/CocoaPods#3057]
🌈

In an attempt to suppress warnings (that I do not care about) from a resource bundle target, I added the following line to my podspec (see below for full podspec):

`ss.xcconfig = { 'MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS' => 'YES' }`

I can see that the library target did pick up the value. Under 'User-Defined' build settings I find the expected entries:

```
MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS = YES
PODS_HIGHSTREET_MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS = YES
```

The **resource bundle target** however has **no user defined build settings**.

I believe this is a bug and can imagine resource targets are handled differently. If you agree, I'd be happy to try to make a PR.

---

Redacted Podspec:
```ruby
Pod::Spec.new do |s|
  s.name     = 'Highstreet'
  s.platform = :ios, '7.0'
  s.version  = 'REDACTED'
  s.license  = 'REDACTED'
  s.summary  = 'REDACTED'
  s.homepage = 'REDACTED'
  
  s.authors  = 'REDACTED'
  s.source   = { :git => 'REDACTED', :tag => 'v' + s.version.to_s }
  s.requires_arc = true

  s.ios.deployment_target = '7.0'
  s.frameworks = 'CoreData','StoreKit'
  s.libraries = 'sqlite3'

  s.default_subspec = 'Core'

  s.subspec 'Core' do |ss|
    ss.source_files = 'Highstreet/Classes/**/*.{h,m}'
    ss.resource_bundle = {
      'Highstreet' => [
        'Highstreet/Resources/Core Data/Highstreet.xcdatamodeld', 
        'REDACTED'
      ]
    }

    ss.xcconfig = { 'MOMC_NO_INVERSE_RELATIONSHIP_WARNINGS' => 'YES' }
  end
end
```

**Comment by segiddins** [comment]
@Thomvis yeah, a PR for this would be ace

**Comment by segiddins** [comment]
This should no longer be the case, looking at the source on master.
