### ISSUE TITLE
"pod lib lint" with a pod on a custom repository 

### ISSUE THREAD

**Issue by qLag** [CocoaPods/CocoaPods#3058]
Hi,
I have a custom repository that was added with "pod repo add REPO_NAME SOURCE_URL" command.

When i use "pod install" on my project that have a pod as a dependency  on my own repository, i t works perfectly. 

But when i want to check my project with "pod lib lint", it says that the pod on my repository was not found. What should i do please ?

Thx.

**Comment by segiddins** [comment]
Use the `--sources` option.

**Comment by orta** [comment]
Could we make finding out about sources easier?

**Comment by segiddins** [comment]
It's there in the help text and on the guides.

**Comment by qLag** [comment]
<code>--sources=https://github.com/artsy/Specs   
The sources from which to pull
                                               dependant pods (defaults to
                                               https://github.com/CocoaPods/Specs.git).</code>

Ok sorry, yet I had actually looked at the help for this command, but I did not think it was mandatory to specify the sources since it is not for the command 'pod install'.

thx again
