### ISSUE TITLE
[Analyzer] `def sources` ignores local repositories

### ISSUE THREAD

**Issue by clarkda** [CocoaPods/CocoaPods#3061]
> [Podfile] Change the default spec repository to the master
> - https://github.com/CocoaPods/CocoaPods/commit/0994612ebb65ad1aa221f384235e4702560df7d2

You can't specify a local source for a `podspec` since it has no `url`, and that makes sense. And previously local sources would just get picked up when a spec did not specify which to use -- defaulting to all sources. 

But now we explicitly use the master spec repository instead of what exists locally. So if I have a private spec repo setup with another vcs or I manage one by hand (barf), I'm unable to install any dependencies since they wont get picked up in the analyze phase.

Is this the intended behavior? Should we not default to local sources if they exist and fall back on the master spec repo otherwise?

/cc: @kylef

**Comment by segiddins** [comment]
You can use a file URL

**Comment by clarkda** [comment]
@segiddins I think we would have to add the file URL to the repo then? 

It looks like it will try `source_with_url(url)` or try to add it manually as a git repository.

**Comment by clarkda** [comment]
That could provide some useful output for `pod repo`  Something like..?

```
$ pod repo

master
- Type: git (origin)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/dusty/.cocoapods/repos/master

master-local
- Type: local copy
- URL:  file:///Users/dusty/.cocoapods/repos/master-local/
- Path: /Users/dusty/.cocoapods/repos/master-local
```

**Comment by clarkda** [comment]
Hm, I updated core locally and was able to make it work, but it's an issue when sharing projects across a team -- especially if the repositories are added to the standard `$HOME/.cocoapods` 

What about allowing the name of a local repository for the source or url?

**Comment by kylef** [comment]
@clarkda name would make sense, but it's no longer a "local" repository if it's shared? What mechanism are you using to share it across systems?

**Comment by clarkda** [comment]
@kylef the cocoapods-repo-svn and cocoapods-repo-hg plugins -- I also know at least one team that uses scripts to sync spec repos from non-git repositories on individual developer machines.

It's unfortunate that a lot of places still exist where they aren't able to use git for one reason or another :disappointed:

**Comment by clarkda** [comment]
@kylef If you all think that finding source by name or url would be a good change -- I'd be more than happy to throw something together and submit a PR

**Comment by kylef** [comment]
I'm going to close this, it should use a full path to the pod repository on disk, or a remote URI.

Plugins such as `cocoapods-repo-svn` and `cocoapods-repo-hg` should patch the source manager or update the API to cleanly add support. Allowing these plugins to handle SVN and HG URIs respectively.

**Comment by kylef** [comment]
#3190

**Comment by amorde** [comment]
@kylef @segiddins I don't know if this has changed since you suggested it, but specifying a local `file://` url leads to pod trying to "checkout" that repository, even if it is not a git repository or if it is already checked out

Podfile:
```
source 'file:///Users/MY_USER/.cocoapods/repos/private'
...
```

```
$ pod install                                                         
Analyzing dependencies
Cloning spec repo `users-my_user-.cocoapods-repos-private` from `file:///Users/MY_USER/.cocoapods/repos/private`
```

Surely this is undesired behavior. Is there a reason we cannot have a local repo without it being a git repository? `pod spec which` and `pod search` will work just fine but as soon as you try to install things get weird.

An ideal scenario would be to be able to do something like this:
```
source 'private'
```
And have the installer look at ~/.cocoapods/repos/private

As of now, the `cocoapods-repo-svn` plugin does not fully work because of this.
