### ISSUE TITLE
Swift assertions broken in frameworks created by 0.36.0.Beta.1

### ISSUE THREAD

**Issue by chrisco314** [CocoaPods/CocoaPods#3062]
#### Description:

Swift assertions are disabled in frameworks created by cocoapods 0.36.0.beta.1

#### Steps to reproduce:

(it would be so much easier to be able to attach this)

Assume the following directory structure:

	 file structure:
		/Assert.podspec (this file)
		/AssertMac
		/AssertMacClient/Podfile
	   	/AssertClientMacDirectBaseline

#### 1 Create baseline framework project

	/AssertMac

1.1 Open Xcode, create a new Framework project for OS X, select Swift as the default language.
1.2 Add a new Swift source file to the framework with the following code:

	import Foundation

	public class Fubar {
	  public init() {}
	  public func test() {
	    println("testing assertion...")
	    assert(false)
	    println("assertion not called")
	  }
	}

#### 2 Create baseline client project:
2.1 Open Xcode, create a new objective-c based Cocoa Touch Mac application, in the same parent directory as the library in step 1.

	   	/AssertClientMacDirectBaseline

		/AssertMac

2.2 Create a new file, main.swift, and paste the following code (don't know if starting as an obj-c project is significant, but is what I did)

	import Assert

	println("hello")

	let fubar = Fubar()
	fubar.test()

	println("goodbye")

2.3 Using finder or terminal, make a copy of this project for the cocoapods test

	/AssertMacClient/

2.4 Manually add the Assert framework above to the linker phase in project settings
2.5 Build and test (this worked for me, though I did delete Cocoa Touch references)
	* note that the assertion correctly fires in the Fubar class of Assert.framework

#### Cocoapods 

3. Create Assert.podspec at the root level, as a peer to the above project files

	/Assert.podspec (this file)
	
	/AssertMac
	/AssertClientMacDirectBaseline

podspec:

	Pod::Spec.new do |s|
	  s.name         = "Assert"
	  s.module_name  = 'Assert'
	  s.version      = "0.1.0"
	  s.summary      = "Assert"
	  s.description  = <<-DESC
	                   A longer description of Assert in Markdown format.

	                   * Think: Why did you write this? What is the focus? What does it do?
	                   * CocoaPods will be using this to generate tags, and improve search results.
	                   * Try to keep it short, snappy and to the point.
	                   * Finally, don't worry about the indent, CocoaPods strips it!
	                   DESC
	  s.license      = { :type => 'None', :text => '' }
	  s.homepage     = "http://www.google.org"
	  s.author       = { "foo bar" => "foo@bar.com" }

	  s.requires_arc = true

	  s.subspec 'mac' do |ss|
	    ss.platform     = :osx
	    ss.public_header_files = "AssertMac/**/*.h"
	    ss.source_files = 'AssertMac/**/*.{h,m,swift}'
	  end

	  s.subspec 'ios' do |ss|
	      ss.platform     = :ios
	      ss.public_header_files = "Assert/**/*.h"
	      ss.source_files = 'Assert/**/*.{h,m,swift}'
	  end

	end

4 Using the copy of the client project from step 2, add the following podfile, and run pod install

		/AssertMacClient/Podfile

		/Assert.podspec (this file)
		/AssertMac
	   	/AssertClientMacDirectBaseline

	#   AssertMacClient/Podfile

	platform :osx, :deployment_target => "10.10"

	pod 'Assert/mac', :path => '..'

4.1 Open the workspace, build and run, note that it skips by the assertion that worked in the basecase.

#### Expected result:

Assertions should be enabled by default in debug builds

#### Version:

0.36.0.Beta.1

**Comment by chrisco314** [comment]
Found the problem, the *Swift* Compiler Code Generation setting was not set properly:

![screen shot 2015-01-21 at 7 23 58 pm](https://cloud.githubusercontent.com/assets/7182365/5850057/15143cba-a1a3-11e4-8a88-92b0174b5cda.png)

I tested with and without and this fixed it for me.  This probably also explains why the execution pointer was jumping around so much in debugging.

Also note that the Deployment section looks like it has some errors as well.
![screen shot 2015-01-21 at 7 25 26 pm](https://cloud.githubusercontent.com/assets/7182365/5850082/791b7ea8-a1a3-11e4-8da4-eed362b5e16b.png)

**Comment by orta** [comment]
Great spotting :star:  :+1:

**Comment by chrisco314** [comment]
As of 0.36.0.Beta.2, the optimization problem is fixed but the Deployment -. "Strip Debug Symbols During Copy" is still reversed.

**Comment by segiddins** [comment]
@mrackwitz do we need to update the defaults in Xcodeproj?

**Comment by mrackwitz** [comment]
@segiddins: Yes, seems to be a historic mistake, which has slipped in.
But the [`SWIFT_OPTIMIZATION_LEVEL`](https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb#L168) should be configured correctly, independent from the used Xcode version.

**Comment by kylef** [comment]
This has been fixed by https://github.com/CocoaPods/Xcodeproj/commit/96b30982a5642eb37dce2241c6e54df8d6960dad.

**Comment by chrisco314** [comment]
Can someone recheck this on Xcode 6.1?  On Xcode 6.3, I am seeing this:

![screen shot 2015-02-20 at 2 36 55 pm](https://cloud.githubusercontent.com/assets/7182365/6310661/f261c75a-b90d-11e4-9e2b-f6b66f67f393.png)

It is odd to me that the the defaults would be to optimize Swift debug builds.  I'm not sure if that is an oversight or intentional on Apple's part, but on face value, it does not make sense and surely would take longer.  Explicitly setting it in cocoapods would avoid conclusively resolve this though.

**Comment by chrisco314** [comment]
(please re-open)

**Comment by chrisco314** [comment]
@orta @mrackwitz 

Can one of you re-open this?  It seems both quite important, and hopefully simple to fix.  Here is a post from a thread on devforums (https://devforums.apple.com/message/1109551#1109551), regarding this problem:

>Please do check your settings.  It may well be a CocoaPods bug as they've historically had some incorrect project-level settings that have caused trouble.  Our own templates configure project-wide build settings to ensure that debug builds are unoptimized in both Swift and C-family languages.  Individual targets initially inherit these project-wide settings without alteration.  There are no system-wide default build settings per se, just a default value that is inferred when a setting is omitted from the project file altogether (and that's one default value regardless of the build configuration, which is why new projects start out with an override to ensure that debug builds are not optimized.)

I do believe that the Swift Compiler section is new.

**Comment by neonichu** [comment]
Can confirm this, even though Xcodeproj has a default for `SWIFT_OPTIMIZATION_LEVEL` it doesn't appear to trickle down into the Pods project.

**Comment by mrackwitz** [comment]
@kylef: That doesn't solve it yet. The parameter must be added to the call when generating the PodTargets.

**Comment by kylef** [comment]
@mrackwitz Agreed, I didn't manually close this one. GitHub did when I merged the PR.
