### ISSUE TITLE
Sources of private pods developed against dependencies with specific tags means that is no way for that pod to pass `pod lib lint`

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#3068]
This issue is a philosophical problem arising from two properties about the way Cocopods works:

 - the only way to specify specific tagged dependency versions are in `Podfiles`. In my case this is `pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord', :tag => 'v2.3.0-beta.3'
`
 - these versions cannot be expressed in a private pod.

Thus, if I intend to use `pod lib create` to create a library in which I could factor out all my lovely MagicalRecord code that uses methods found only in `v2.3.0-beta.3`, there is no way for that new pod to pass `pod lib lint`. This is because `pod lib lint` will install the latest stable version, which is `v2.2`. FAR too old for my code.

I arrive at a situation where I'm stuck, and **cannot** factor out my code to the new library with real assurance I've expressed the dependencies correctly.

I could ignore the fact that `pod lib lint` doesn't succeed, for instance. However, this depends heavily on whichever `Podfile` uses this Pod to constrain MagicalRecord's version to `v2.3.0-beta.3` for me.

**Comment by segiddins** [comment]
Your pod spec dependency on `MagicalRecord` could read  `spec.dependency 'MagicalRecord', '>= 2.3.0-beta3', '< 4.0.0'`, for example.

**Comment by fatuhoku** [comment]
@segiddins oh, does that syntax work for tag names? `v2.3.0-beta3` is a tag, not a version number!

**Comment by segiddins** [comment]
No. It seems like what you really want is for @tonyarnold to release a beta version of MagicalRecord.

**Comment by fatuhoku** [comment]
@segiddins Hmmmmmm. I can see why Cocoapods mightn't want to support something like this. It would totally defeat the point of dependency management. We'll just have to pressure @tonyarnold to work doubly as hard to get that version out then. lol.

**Comment by tonyarnold** [comment]
@tonyarnold am tired. @tonyarnold am try to release new version soon! :trollface:
