### ISSUE TITLE
'podspec' directive in Podfile has trouble detecting dependencies that are local private pods

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#3070]
Note: 'private' below simply means it's a pod intended to be consumed internally by my own code, which lives locally on my dev machine.

I have a private library pod called `MakeEatSeeKit`. I also have a private pod that contains all of the tests for this library, called `MakeEatSeeKitTests`. So clearly I need to make `MakeEatSeeKitTests`'s podspec declare `MakeEatSeeKit` as a dependency (so that it can exercise its classes in a test!):

```ruby
# MakeEatSeeKitTests.podspec
Pod::Spec.new do |s|
  s.name = 'MakeEatSeeKitTests'
  # ... blah blah blah
  s.dependency 'MakeEatSeeKit'
end
```

**This approach is outlined in www.supermar.in/modular-objective-c/.**

Now — I want to be able to open up Xcode / AppCode and just run the tests for the library. So, I create a new `.xcodeproj`, add the relevant library sources into the project, and write a `Podfile` to supply the dependencies: dependencies listed in `MakeEatSeeKitTests.podspec`, to be exact.

```ruby
# Podfile

# ...

target 'MakeEatSeeKitTestTarget' do
  podspec :path => 'MakeEatSeeKitTests.podspec'
end
```

... where, let's just say `MakeEatSeeKitTestTarget` is a target that lets me run tests. Now the directory structure looks like this:
![screen shot 2015-01-23 at 18 05 31](https://cloud.githubusercontent.com/assets/430233/5879864/e7575d82-a32a-11e4-9e77-13c811d23466.png)

As far as I can tell from http://guides.cocoapods.org/syntax/podfile.html#podspec, I'm using this command correctly: `"It is intended to be used by the project of a library."`.  When I `pod install` I expected everything to just work. But I get an error:

### First error

```
[!] Unable to find a specification for `MakeEatSeeKit`
```

i.e. it **failed to find my local pod** after reading through the list of dependencies in the `podspec`.  So I thought, okay I probably just need to let Cocoapods know where to find it and give it a path. The only way you can do this is to constrain where the dependency can be satisfied in the `Podfile`. So I went ahead to do that...

```ruby
# Podfile (revised!)

# ... as before...

target 'MakeEatSeeKitTestTarget' do
  pod 'MakeEatSeeKit', :path => '.'
  podspec :path => 'MakeEatSeeKitTests.podspec'
end
```

I try `pod install` again.

### Second error

```
[!] There are multiple dependencies with different sources for `MakeEatSeeKit` in `Podfile`:

- MakeEatSeeKit (from `.`)
- MakeEatSeeKit
```

... and I'm out of options.

How can I make Cocoapods see `MakeEatSeeKit` as a local dependency?

**Comment by fatuhoku** [comment]
Actually. One moment. I've just tried something else and it might have worked...

**Comment by fatuhoku** [comment]
Okay. I can confirm this is an issue for me and would welcome your ideas.

**Comment by neonichu** [comment]
For your case, you do need the `podspec` attribute at all, so just using: 

```
target 'MakeEatSeeKitTestTarget' do
  pod 'MakeEatSeeKit', :path => '.'
end
```

will work.

**Comment by fatuhoku** [comment]
Ach, I guess... I had a reason for avoiding that — I think IDEs pick up file updates better or something.  Thanks anyway.
