### ISSUE TITLE
inhibit_all_warnings not working? Cocoapods 0.35.0

### ISSUE THREAD

**Issue by ronak2121** [CocoaPods/CocoaPods#3073]
For some reason, I'm not seeing inhibit_all_warnings working from one of our pods. I tried inhibiting the warnings for just that Pod, but that also had no effect.

Is there some configuration we have to do to enable this?

**Comment by segiddins** [comment]
Could you please be more specific with the issues you're seeing?

**Comment by ronak2121** [comment]
Here's my podfile:

platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

pod 'AFNetworking', '2.5.0'
pod 'AFNetworkActivityLogger', '2.0.3'
pod 'CocoaLumberjack', '1.9.1'
pod 'Typhoon', '2.2.1'
pod 'InternalProjectPod'

for some reason, I'm still seeing compiler warnings show up from the "InternalProjectPod." The "InternalProjectPod" is a library that we develop in house. I'm not seeing any compiler warnings from AFNetworking or Typhoon.

**Comment by ronak2121** [comment]
That's why I ask whether there's some configuration we need to do in the pod spec files to inhibit warnings.

**Comment by kylef** [comment]
@ronak2121 What kind of warning are you seeing? Are they from a particular source type?

**Comment by ronak2121** [comment]
They are a mixture of #warnings we have added to the code on our own, combined with compiler warnings about "NewLine Missing at the end of file". All files are in Objective-C.

**Comment by ronak2121** [comment]
We were also getting a ton of warnings related to custom compiler settings we had set up in our project. I've removed all of those custom settings and I'm trying to see if that makes any difference...

**Comment by ronak2121** [comment]
So after reverting a bunch of my custom project settings, running "pod install/update" results in no more warnings. However, I still don't see GCC_WARN_INHIBIT_ALL_WARNINGS being set to YES. This is regardless of whether I set:

inhibit_all_warnings!

xcodeproj 'Audible.xcodeproj'

or 

pod 'InternalProjectPod', :head, :inhibit_warnings => true

**Comment by phatmann** [comment]
I still don't see GCC_WARN_INHIBIT_ALL_WARNINGS being set to YES or NO with version 0.37. I looked through the CocoaPods code and there is actually no support for `inhibit_all_warnings!`. According to the changelog it was removed in build 0.13.0. The [CocoaPods guide](https://guides.cocoapods.org/syntax/podfile.html#inhibit_all_warnings_bang) incorrectly states this property is still supported.

**Comment by segiddins** [comment]
@phatmann `inhibit_all_warnings!` is supported, via calls to `inhibit_warnigns_for_pod`, iirc.

**Comment by phatmann** [comment]
I searched the whole code base for `inhibit_all_warnings!` and found no references to it. Can you point me to the appropriate code?

**Comment by amorde** [comment]
@phatmann The commands in the podfile are part of CocoaPods/Core, a separate project. The relevant section of code can be found [here](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/podfile/dsl.rb#L430-L432)

**Comment by numerics** [comment]
The command is NOT working... even with with the latest version CocoaPods 0.38.0. The top of my pod file:
platform :ios, '7.1'
inhibit_all_warnings!
xcodeproj 'SuperStarRewards.xcodeproj'
....   

I've rearranged lines and various other test... inhibit warnings is always turned off...

**Comment by segiddins** [comment]
@numerics could you please open a new issue with a project attached that demonstrates the issue? Thanks!
