### ISSUE TITLE
Swift 'header' file not updating

### ISSUE THREAD

**Issue by matthewpalmer** [CocoaPods/CocoaPods#3074]
Hi,

I'm having a bit of an issue updating one of my packages. I've made the changes in the 'Development Pods' section in Xcode, but when I go to my demo and testing app, the changes aren't showing up there and I get compiler errors.

Now, if I Command-Click on the class name in a method call, e.g. `Locksmith.saveData(...)`, it loads an up-to-date version of the code I was changing. But if I Command-Click on it in the `import Locksmith` line, it has the old method parameters.

The specific change I made was reordering the methods' parameters to allow for default values.

I've run `pod update`, `pod install`, `rm -rf Pods`, `pod spec lint`, etc., but nothing seems to be fixing it.

I've also published version 1.1.0 of this package, and now I'm working on 1.1.1, if that makes a difference.

Thanks very much for your help.

Edit: Also possibly relevant is that the changes were made in an extension to the original class, e.g.

```swift
extension Locksmith {
    class func saveData(data: [String : String], inService service: String, forUserAccount userAccount: String) -> NSError?
    class func loadDataInService(service: String, forUserAccount userAccount: String) -> (NSDictionary?, NSError?)
    class func deleteDataInService(service: String, forUserAccount userAccount: String) -> NSError?
    class func updateData(data: [String : String], inService service: String, forUserAccount userAccount: String) -> NSError?
    class func clearKeychain() -> NSError?
}
```

has not been updated if I command-click on `import Locksmith`, but is updated if I command-click on `Locksmith.saveData`

**Comment by segiddins** [comment]
It's possible that Xcode isn't invalidating the module cache. Can you try cleaning/deleting derived data?

**Comment by matthewpalmer** [comment]
Thanks for getting back to me so quickly :)

I was clearing derived data from within Xcode, but I this time I nuked everything from the command line and that fixed it. Thanks so much for your help!

For anyone (i.e. me) in the future,

`~/Library/Developer/Xcode/DerivedData` and then `rm -rf DerivedData/`=
