### ISSUE TITLE
cocoapod-keys on 0.36.0.beta.1

### ISSUE THREAD

**Issue by RuiAAPeres** [CocoaPods/CocoaPods#3076]
I am trying to use the `cocoapods-keys` plugin like this:

```
source 'https://github.com/CocoaPods/Specs.git'

plugin 'cocoapods-keys', {
  :project => "Stores Locator",
  :keys => [
    "ParseClientKey",
    "ParseApplicationID"
  ]
}

platform :ios, '8.0'
````

But I am getting:

```
[!] Invalid `Podfile` file: undefined method `deep_stringify_keys' for #<Hash:0x007fd23284f308>. Updating CocoaPods might fix the issue.

 #  from /Users/ruiperes/Desktop/StoresLocator/Podfile:3
 #  -------------------------------------------
 #  
 >  plugin 'cocoapods-keys', {
 #    :project => "Stores Locator",
 #  -------------------------------------------
```
Is there anything I am missing?

**Comment by RuiAAPeres** [comment]
Doing `sudo gem install activesupport ` solved the issue. It seems cocoapods is using  and old version (` s.add_runtime_dependency 'activesupport', '>= 3.2.15'`) Thanks to @davidcunha.

**Comment by neonichu** [comment]
This used to be due to Ruby 1.8.7 compatibility, see #2307 - maybe we can revisit it since we are now only supporting Ruby >= 2.0

**Comment by crarau** [comment]
I have run `sudo gem install activesupport` but I still have the same issue.

`sudo gem install activesupport`
`Successfully installed activesupport-4.2.0`
`Parsing documentation for activesupport-4.2.0`
`unable to convert "\x84" from ASCII-8BIT to UTF-8 for lib/active_support/values/unicode_tables.dat, skipping`
`1 gem installed`

`bundle exec pod install`
`[!] Invalid `Podfile` file: undefined method `deep_stringify_keys' for {:localizations=>["en.lproj"]}:Hash.` `Updating CocoaPods might fix the issue.`

Thanks for you help.

**Comment by abbeycode** [comment]
I'm getting this also, but only after I added CocoaPods Keys

**Comment by x2on** [comment]
`gem install activesupport` helped here.
