### ISSUE TITLE
have cocoapods detect a nib/xib outside of a bundle

### ISSUE THREAD

**Issue by dwery** [CocoaPods/CocoaPods#3077]
... in order to avoid code signing issues, see #790 .

**Comment by segiddins** [comment]
Might be appropriate for the Validator? Otherwise, this is a moot issue with Frameworks.

**Comment by neonichu** [comment]
So we would reject installation of Pods with NIBs in `resources` if the user doesn't use frameworks? That would also break lint, though, because there is no way to specify that a Pod can only be used as a framework.

**Comment by segiddins** [comment]
@neonichu I think the idea was to enforce that it was in a `resource_bundle`?

**Comment by neonichu** [comment]
Yah, but that also would only apply if not using frameworks. IMO, we should close this, in the end it is really an Xcode issue, anyway.

**Comment by segiddins** [comment]
:+1:
