### ISSUE TITLE
xcode open *.xcworkspace too slow, when Pods.xcodeproj contains more than 100 targets

### ISSUE THREAD

**Issue by wsvn53** [CocoaPods/CocoaPods#3079]
My project imported more than 100 third-party libraries. It created 100 targets in Pods.xcodeproj after `pod install`, so when I use xcode to open my xcworkspace, It is too slow, after more than 2 minutes before to write code or build target.

Most of my project's dependency are binary library, do not need a target for build, just need linker flag. Can you detect this situtation and do not create targets.

**Comment by neonichu** [comment]
This is already the case since 0.36 beta 1 if your Pods truly define no `source_files`, see #2918

**Comment by wsvn53** [comment]
Good work, thanks!!
