### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET is set to iOS 5.0 instead of what is specified in Podfile

### ISSUE THREAD

**Issue by ronak2121** [CocoaPods/CocoaPods#3084]
Hi,

We are specifying:

`platform :ios, '7.0'`

on top of our Podfile, but for some reason, the generated xcconfig files have:

`IPHONEOS_DEPLOYMENT_TARGET = 5.0`

included inside of them.

Why is this the case?

We are using Cocoapods 0.35.0.

**Comment by segiddins** [comment]
Can you please share your entire Podfile?

**Comment by ronak2121** [comment]
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

xcodeproj 'TestProject', 'App Store Distribution' => :release, 'Debug' => :debug

pod 'AFNetworking', '2.5.0'
pod 'AFNetworkActivityLogger', '2.0.3'
pod 'CocoaLumberjack', '1.9.1'
pod 'Typhoon', '2.3.4'
pod 'DTFoundation/DTHTMLParser', '~> 1.7'
pod 'HTKDynamicResizingCell'
pod 'Facebook-iOS-SDK', '~> 3.16.0'
pod 'CWStatusBarNotification', '~> 2.1.1'
pod 'THContactPicker', '0.0.4'
pod 'KVOController'

target :UnitTests do
    pod 'OCMockito', :head
    pod 'OCMock', :head
    pod 'TRVSMonitor', '0.0.3'
end

**Comment by ronak2121** [comment]
This is the same Podfile we're using which causes the issues with inhibit_all_warnings that I describe in: https://github.com/CocoaPods/CocoaPods/issues/3073

**Comment by segiddins** [comment]
In that case, it would be much appreciated if you could share the actual project, or another project that exhibits the same issues.

**Comment by ronak2121** [comment]
On a related note; I'm also not seeing the ONLY_ACTIVE_ARCH setting being enabled. I'll attach a test project shortly.

**Comment by ronak2121** [comment]
Found the problem had to do with the podspec of one of the pods we depend on. Closing.
