### ISSUE TITLE
Question : Dependency and pre-compiled librairies

### ISSUE THREAD

**Issue by WoodySlum** [CocoaPods/CocoaPods#3086]
Hi all,

You did a great work with Cocoapods and I'm glad to use it every day.
This message is not an issue, but more a question.

We develop an internal library at my company ; this library uses several dependencies.
As we don't want to publish the source code, for several reason I wouldn't mention we have created a private repository for cocoapods, and distribute the static library already compiled (.framework) through cocoapods.

In this case, I cannot manage dependencies  because code is pre-compiled in a static library, right ?
Is there any other way do distribute pre-compiled librairies without dependencies ?

Thanks all for reading

**Comment by orta** [comment]
Hey Woody, this gets asked pretty regularly, please use the github search.

The quick answer is https://github.com/CocoaPods/cocoapods-packager - the longer one is in issue history.
