### ISSUE TITLE
0.36.0.beta.2: Cannot figure out how to use groups in development pod

### ISSUE THREAD

**Issue by bunchjesse** [CocoaPods/CocoaPods#3087]
It was mentioned in the changelog for B1 that groups will be created to match the layout on the filesystem. I created a development pod and added source files in the classes folder then ran `pod install` but none of the subfolder's source files made it into the project.

Is there some trick that I don't know to get this to work?

![screen shot 2015-01-29 at 9 49 44 am](https://cloud.githubusercontent.com/assets/788291/5962907/39453aae-a79c-11e4-9454-addaf96f2be1.png)
![screen shot 2015-01-29 at 9 50 00 am](https://cloud.githubusercontent.com/assets/788291/5962908/396fd548-a79c-11e4-9e9d-ec65dee6fffe.png)

**Comment by segiddins** [comment]
What's your Podspec?

**Comment by bunchjesse** [comment]
Just the default that `pod lib create <name>` gave me:

```
#
# Be sure to run `pod lib lint TestKit.podspec' to ensure this is a
# valid spec and remove all comments before submitting the spec.
#
# Any lines starting with a # are optional, but encouraged
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = "TestKit"
  s.version          = "0.1.0"
  s.summary          = "A short description of TestKit."
  s.description      = <<-DESC
                       An optional longer description of TestKit

                       * Markdown format.
                       * Don't worry about the indent, we strip it!
                       DESC
  s.homepage         = "https://github.com/<GITHUB_USERNAME>/TestKit"
  # s.screenshots     = "www.example.com/screenshots_1", "www.example.com/screenshots_2"
  s.license          = 'MIT'
  s.author           = { "Jesse Bunch" => "jesse@getbunch.com" }
  s.source           = { :git => "https://github.com/<GITHUB_USERNAME>/TestKit.git", :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.platform     = :ios, '7.0'
  s.requires_arc = true

  s.source_files = 'Pod/Classes'
  s.resource_bundles = {
    'TestKit' => ['Pod/Assets/*.png']
  }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  # s.dependency 'AFNetworking', '~> 2.3'
end
```

**Comment by segiddins** [comment]
iirc, the `Pod/Classes` isn't recursive, but maybe it should be?

\c @kylef

**Comment by orta** [comment]
feels more like the intention is "using this as the root folder, recurse inside" to me

**Comment by kylef** [comment]
I agree, it should certainly recurse. Not recursing is certainly a bug.

**Comment by segiddins** [comment]
I actually don't think there's a way we can make it recurse automatically, looking at `FileAccessor#paths_for_attribute`

**Comment by kylef** [comment]
@bunchjesse If it wasn't clear from our discussion, you will need to change `s.source_files = 'Pod/Classes'`to something like `s.source_files = 'Pod/**/*.{h,m,swift}'` to include your source files.

**Comment by orta** [comment]
We can change the defaults (`pod lib create`/`pod spec create`) to be something more like the above as a step in the right direction?

**Comment by bunchjesse** [comment]
Thanks everyone. Making the source_files specification recursive did the trick!

`s.source_files = 'Pod/Classes/**/*{h,m}'`

@orta Is there any harm in making it recursive by default? It seems that if Cocoapods now supports folders as groups in a development pod, it should be recursive by default.

**Comment by segiddins** [comment]
It should be recursive by default. Let's change it to `Pod/Classes/**/*`
