### ISSUE TITLE
0.36.0.beta.2: Resource bundles in frameworks

### ISSUE THREAD

**Issue by romaonthego** [CocoaPods/CocoaPods#3088]
Hi,

I can't seem to make resource bundles working when I have `use_frameworks!` in my Podfile.

This line `[UIImage imageNamed:@"MyProject.bundle/SomeImage"]` returns `nil` when I have `use_frameworks!` enabled and it works without it. Am I doing something wrong or maybe it's a known issue?

Here's the contents of my podspec:

```
s.resource_bundle = { 'Project' => 'Project/Resources/*' }
s.preserve_paths = 'Project/Resources'
```

Thank you!

**Comment by segiddins** [comment]
The resource will be in the framework's bundle, I believe.

\c @neonichu

**Comment by neonichu** [comment]
Yep, you should do something like 

```
NSString *bundlePath = [[NSBundle bundleForClass:someClassFromYourPod.class] pathForResource:@"MyProject" ofType:@"bundle"];
NSBundle *projectBundle = [NSBundle bundleWithPath:bundlePath];
UIImage *image = [UIImage imageWithContentsOfFile:[bundle pathForResource:@"SomeImage" ofType:@"png"
```

to access resources, so that it works for both frameworks and non-frameworks. Using `bundleForClass:` is key here.

**Comment by romaonthego** [comment]
@neonichu @segiddins `imageWithContentsOfFile` doesn't cache images which is very inconvenient and requires modification to existing projects to support CocoaPods. Are there any plans to fix that in the future? This will break many pods when `use_frameworks!` is enabled.

**Comment by neonichu** [comment]
@romaonthego There isn't anything we can do about it, this is just how dynamic frameworks work, because they are a separate bundle.

There's [this radar](http://openradar.appspot.com/10250430) for `imageNamed:inBundle:` and also the possibility to pass a relative path to `imageNamed:`, though.

**Comment by romaonthego** [comment]
@neonichu got it, thank you!

**Comment by neonichu** [comment]
BTW, iOS 8.0 actually added this <https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/index.html#//apple_ref/occ/clm/UIImage/imageNamed:inBundle:compatibleWithTraitCollection:>

**Comment by romaonthego** [comment]
@neonichu great, that solves the problem. Thanks again!
