### ISSUE TITLE
怎么做 ？ pod install 添加framework 而不是 library

### ISSUE THREAD

**Issue by wodetian** [CocoaPods/CocoaPods#3090]
I can ask questions here?      😢   😢    😢   😢   😢    😢    😢    😢     😢

#3089

**Comment by segiddins** [comment]
You can ask questions, however the linked issue contained no questions, and didn't conform to our contributing guidelines for new issues.

**Comment by wodetian** [comment]
I don't know what meaning, my this question? But I really met ah. Excuse me, how to do can deal with it? Now my project can not run, for this reason, you can give me a link, let me go to see the related introduction, about this problem!

I'm in China. So, can not access the Google ~ ha ha ha Don't ask me why, I also don't know why fucking fuck the Chinese government? Beg you...

**Comment by orta** [comment]
QueryKit = Swift,
CocoaPods 0.36 uses Frameworks if you're using swift: http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by wodetian** [comment]
感激不尽～^_^

**Comment by wodetian** [comment]
@orta  Hello, I don't know what is the reason? What did I do wrong? 

![0db040b2-7785-496c-9696-38804a65439b](https://cloud.githubusercontent.com/assets/6121524/5991199/2c1df3fa-aa19-11e4-8a9f-16a8b694ed45.png)
