### ISSUE TITLE
pod install fails with local dependencies

### ISSUE THREAD

**Issue by qLag** [CocoaPods/CocoaPods#3096]
Since the Beta 2 , 'pod install' and 'pod update' fail because it doesn't find my local pods specified in a local repository.

I have my own repo that was added with "pod repo add <...>" command. One of the pod of this repo is defined as a dependency of another local pod. 

In my Podfile : 

<code>platform :ios, '6.0'</code>
<code>use_frameworks!</code>
<code>inhibit_all_warnings!</code>
<code></code>
<code>pod 'MFCore', :path => '../../../mfcore'</code>
<code>pod 'MFUI', :path => '../../../mfui'</code>

MFCore have some dependencies such as "MyJsonLibrary" (for the example, defined in MFCore.podspec) :
<code>  s.dependency 'MyJsonLibrary', '>= 1.6'</code>

MyJsonLibrary is on my own git repository that i've added with ths command : 
<code>pod repo add mypodspecs mygit@git.ptx.fr.something:mypodspecs.git</code>

in ~/.cocoapods/ folder, i have 
- repos/master (the master repository of Cocoapods)
- repos/mypodspecs (my own repo)

That sounds good and i can find  my pod "MyJsonLibrary" in  '~/.cocoapods/repos/mypodspecs' folder.

But...

When i run "pod install" I get this message : 
<code>[!] Unable to satisfy the following requirements:</code>
<code></code>
<code>- `MyJsonLibrary (>= 1.6)` required by `MFCore (1.1.6)`</code>

I don't know what i need to do to make it workin. I've seen this issue : https://github.com/CocoaPods/CocoaPods/issues/2946 but i don't know what thinking...

It was working with Beta 1 an older versions of Cocoapods.

Thx.

**Comment by neonichu** [comment]
Your Podfile needs a `source` directive to pull in your spec repo, see <http://guides.cocoapods.org/syntax/podfile.html#source>. This should have been the case since 0.35.

**Comment by qLag** [comment]
Okay i will do it. But, for information, i did not need with it 0.36.0 beta 1.
