### ISSUE TITLE
[0.36.0.beta.2]Dependency Analysis Error

### ISSUE THREAD

**Issue by Julyyq** [CocoaPods/CocoaPods#3098]
See screenshot:
![error](https://cloud.githubusercontent.com/assets/2620575/6004901/4b6305ec-ab41-11e4-930b-e170c769c777.png)

**Comment by Julyyq** [comment]
Someday when I open my Swift workspace, this error occurs all the time, I can't clean even do anything. I'm falling apart.

**Comment by orta** [comment]
Can you provide Podfiles, or an example project? 

This is a really small amount of information to work form. You're a developer, offer us a bug report we can work with.

**Comment by Julyyq** [comment]
@orta My cocoapods version: `0.36.0.beta.2`, that other filepath is my another pure objective-c code project.
I stash my local changes, back to previous working-well commit, then stash apply and run `pod install`, solved this issue.

**Comment by kylef** [comment]
I'm going to close this as there isn't really anything we can do with such little information.

Please attach detailed steps to reproduce, or an example project exhibiting this issue and we can re-open and investigate.
