### ISSUE TITLE
[Swift] 0.36.0.beta.2 does not link vendored frameworks to Pod targets

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/CocoaPods#3105]
Our app depends on a custom Pod `CoolAppPart` which in turn depends on Pod [`LayerKit`](https://github.com/layerhq/releases-ios) which provides a vendored framework.

Pod `CoolAppPart` cannot find any symbols of Pod `LayerKit` because its vendored framework is not linked against the Pod *target* of `CoolAppPart`.

Example project: https://github.com/fluidsonic/CocoaPodsLayerDemo

Output:
```
CocoaPodsLayerDemo/CoolAppPart/CoolAppPart.swift:1:8: error: no such module 'LayerKit'
```

Podfile:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'CoolAppPart', :path => 'CoolAppPart'
```

Podspec of Pod `CoolAppPart`:
```ruby
Pod::Spec.new do |s|
	s.name         = 'CoolAppPart'
	s.platform     = :ios, '8.0'
	s.source_files = '**/*.swift'

	s.dependency 'LayerKit'
end
```

**Comment by neonichu** [comment]
Yep, that is a known issue with frameworks and vendored artifacts, see CocoaPods/CocoaPods#2926
