### ISSUE TITLE
`--allow-warnings` flag doesn't work with `pod repo push` 

### ISSUE THREAD

**Issue by PadraigK** [CocoaPods/CocoaPods#3108]
I'm trying to push a podspec to my private cocoa pods repo. I need to use the git SSH URL, so I can't satisfy this warning:

```
- WARN  | [source] Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
```

`pod lib lint --allow-warnings` works great, telling me that it passed validation, but the same flag on the `pod repo push privaterepo Private.podspec --allow-warnings` is ignored, so the command always aborts.

**Comment by PadraigK** [comment]
Today this seems to be working, but it wasn't happening last night: https://pbs.twimg.com/media/B8-ZJ24IMAAjQ8j.jpg:large

What changed: 
- I manually created the first version in my private repo. I previously had just an empty /Specs folder, but I made a full /Specs/podname/version/my.podspec and pushed it manually. 
- I tried the current 0.36 beta, but it didn't work
- I uninstalled and reinstalled 0.35

Perhaps my install have become corrupted somehow, or perhaps there was another error being caused by the repo not having any specs in it yet.  My initial problem is solved, so close this if you like, but I'm happy to help track down the original issue if you're interested.

**Comment by segiddins** [comment]
@PadraigK are you sure you had actually pushed the tag up to the source? I'm making that failure message more verbose right now.

**Comment by PadraigK** [comment]
Ah, Yep. That is almost certainly what happened. A clearer error message will help. Perhaps the way to approach it would be for lint to detect and fail on it so that once it's happy, we know that the push should work.

**Comment by segiddins** [comment]
@PadraigK that's what `pod spec lint` is for :)

**Comment by PadraigK** [comment]
Oh, I was doing `pod lib lint`. My bad.
