### ISSUE TITLE
inhibit_indirect_pods_warnings! option

### ISSUE THREAD

**Issue by buscarini** [CocoaPods/CocoaPods#3109]
It would be nice to be able to allow warnings from direct pod dependencies, but inhibit those coming from the dependencies of those pods. I have some pods that I developed myself, so I want warnings from those, but I don't want warnings from the dependencies of those pods. Not sure if this is clear enough, so:

App -> Pod A -> Pod B

I want warnings from App and Pod A, but not from Pod B

**Comment by segiddins** [comment]
I'd say this is the territory where we shouldn't be cluttering the DSL, and instead should be encouraging use of the post install hook.

**Comment by neonichu** [comment]
I agree - this can be done as a plugin if really desired.

As a workaround, one can also add the dependencies directly to the Podfile and inhibit warnings on those.

**Comment by hfossli** [comment]
http://stackoverflow.com/questions/31644959/how-can-i-silence-warnings-from-all-pods-except-local-pods
