### ISSUE TITLE
Copy Pods Resources failed! ${BUILT_PRODUCTS_DIR}! rsync error: some files could not be transferred

### ISSUE THREAD

**Issue by yirenjun** [CocoaPods/CocoaPods#3110]
![image](https://cloud.githubusercontent.com/assets/273997/6038811/7652bfee-ac9b-11e4-966f-bd0a2260b89c.png)

The '#{resource}' in the script must enclosed in double quotes!!!

If you using a Development-Pods who creating a bundle,
![image](https://cloud.githubusercontent.com/assets/273997/6038945/be6af976-ac9c-11e4-984f-a04b70c04e5d.png)

The script will like this:
![image](https://cloud.githubusercontent.com/assets/273997/6038948/c169238c-ac9c-11e4-9922-784e3361a610.png)

Then ....
install_resource's params $1 will be a raw string contains raw string "${BUILT_PRODUCTS_DIR}", will not be replaced by the environment variable!!!

![image](https://cloud.githubusercontent.com/assets/273997/6039058/db54bf08-ac9d-11e4-861c-6a0ed3c49884.png)

**Comment by neonichu** [comment]
This is a known issue in 0.36 beta 2, see #3082.
