### ISSUE TITLE
Missing Errors in Pod Repo Push

### ISSUE THREAD

**Issue by szweier** [CocoaPods/CocoaPods#3111]
I'm attempting to do a pod push to a private repo from one computer which is failing and provided two error logs.  When I do the same from another computer it produces close to 20 error logs.  Now the errors are clear and easily fixed (classes exist in the folder structure which don't exist in the Xcodeproject so they fail during validation).  That is fine, the problem is that the person using the computer with only two errors doesn't get to see the full scope of what the problem is.  We are about to try simply fixing the two issues seen and see what it says on the next push but my question is.  Are there any additional settings I may have set on one computer over the other that could cause it to fail sooner.  When I did a diff on the two outputs I noticed that my computer attempts to compile many more files than the other computer does which would explain the missing errors. 

We have the same version (0.35.0) and I just uninstalled and reinstalled cocoa pods fresh on the computer where this issue occurs.  The reinstall has not helped.  Any thoughts on where this problem is coming from?

**Comment by neonichu** [comment]
I am assuming those were build errors? We rely on `xcodebuild` for that, factors that could cause a difference:

- Xcode versions
- the global "Continue building after errors" setting

**Comment by szweier** [comment]
Well, it looks like the continue building after errors setting wasn't checked on that computer.  I didn't verify 100% yet that the issue is fixed by that but it sure seems like thats the right answer.  Thank you for the quick reply.
