### ISSUE TITLE
deployment_target not accepted in JSON podspec

### ISSUE THREAD

**Issue by futuretap** [CocoaPods/CocoaPods#3113]
I specified

	"platforms": {
		"ios": "8.0"
	},
	"deployment_target": "7.0",

in my podspec.json file. Now `pod lib lint` complains with

    - WARN  | [iOS] Unrecognized `deployment_target` key

When I switch to a ruby-style podspec the parameter is accepted correctly. I'm using Cocoapods 0.35.0.

**Comment by segiddins** [comment]
You just need

```json
"platforms": {
    "ios": "7.0"
},
```

**Comment by futuretap** [comment]
So what is the documented deployment_target parameter then all about? And how can I specify the minimum build SDK?

**Comment by segiddins** [comment]
that's what the `7.0` in the `platforms` dictionary is specifying

**Comment by futuretap** [comment]
So the [documentation](http://guides.cocoapods.org/syntax/podspec.html#deployment_target) is wrong?

**Comment by kylef** [comment]
@futuretap The documentation is using the terminology and examples for Ruby podspecs.

```ruby
spec.ios.deployment_target = '8.0'
```

Is equivalent to this in the JSON pod specs:

```javascript
"platforms": {
    "ios": "8.0"
},
```

There is an open issue regarding this: https://github.com/CocoaPods/guides.cocoapods.org/issues/48

**Comment by futuretap** [comment]
I see. I reverted to a ruby podspec and wrote this:

	s.platform              = :ios, '8.0'
	s.ios.deployment_target = '7.0'

Is this then illegal syntax and what does it actually specify? lint didn't complain about it.

**Comment by segiddins** [comment]
You're just overwriting the deployment target.
