### ISSUE TITLE
Cocoapods prompting to report a bug when .xcodeproj is in a merge conflict

### ISSUE THREAD

**Issue by sebastiangrail** [CocoaPods/CocoaPods#3115]
When the `.xcodeproj` file is in a merge conflict, running `pod update` or `pod install` results in cocoapods failing and showing the error reporting markdown template.

A better error message would be something like: "path/to/project.xcodeproj" is in a merge conflict. Resolve the conflict before running pod install/update"

**Comment by segiddins** [comment]
Please open this on the Xcodeproj repo!

**Comment by sebastiangrail** [comment]
Sorry about that. Opened https://github.com/CocoaPods/Xcodeproj/issues/238 instead.
