### ISSUE TITLE
Pod spec lint takes too long

### ISSUE THREAD

**Issue by VilemKurz** [CocoaPods/CocoaPods#3116]
Our library, [ShareKit](https://github.com/ShareKit/ShareKit/blob/master/ShareKit.podspec) has many subspecs and a lot of dependencies. Pod spec lint takes too long, like 30 minutes plus, regardless of the speed of internet connection. Now it started to even [timeout Travis CI](https://travis-ci.org/ShareKit/ShareKit/builds/49718119). Please, optimize the lint command.

**Comment by orta** [comment]
+1 ARAnalytics also takes hours to lint / push

This is the issue about the fix: https://github.com/CocoaPods/CocoaPods/issues/2863 - so I'm closing this as a dupe.
