### ISSUE TITLE
Mysterious update

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#3122]
I have noticed mysterious update of one of pods in my project. 

`pod 'libPhoneNumber-iOS', '~> 0.6'`

$ pod update
`Installing libPhoneNumber-iOS 0.8.1 (was 0.7.6)`

I would rather expect not updaring to this version. 

$ pod --version
0.34.4

**Comment by neonichu** [comment]
This works as expected, the `~>` operator will update the last component of the version you specify. So if you wanted to lock it to the 0.6 series of versions, you'd need to say `~> 0.6.0`.

**Comment by orta** [comment]
http://robots.thoughtbot.com/rubys-pessimistic-operator

**Comment by krzyzanowskim** [comment]
thanks it's so pessimistic
