### ISSUE TITLE
Pods-frameworks.sh file not generated

### ISSUE THREAD

**Issue by S2V** [CocoaPods/CocoaPods#3123]
File not generated on .../Target Support Files/Pods-ProductName/Pods-ProductName-frameworks.sh. 
/Users/viktorsiruk/Desktop/ProductName2-0/Pods/Target Support Files/Pods-ProductName/Pods-ProductName-frameworks.sh: No such file or directory. Pod v3.5 / X6.1.1/OS 8.1

**Comment by segiddins** [comment]
Please provide enough information for someone to be able to reproduce the issue.

**Comment by kylef** [comment]
You seem to mentioned your running CocoaPods 0.35 (if that's what you mean by v3.5). The frameworks shell script is from CocoaPods 0.36 so it seems you have played around with 0.36 and then downgraded leaving references to the frameworks script in your project.

I'd suggest deintegrating when removing framework support and downgrading CocoaPods versions: https://github.com/kylef/cocoapods-deintegrate
