### ISSUE TITLE
[0.36.0.beta.2] '-Xanalyzer -analyzer-disable-checker -Xanalyzer deadcode' and flex/bison source compilation

### ISSUE THREAD

**Issue by foscomputerservices** [CocoaPods/CocoaPods#3127]
I have a swift project that depends on another pod that is all Objective-C, but also includes flex/bison sources.  The flags '-w -Xanalyzer -analyzer-disable-checker -Xanalyzer deadcode' are being passed to the flex & bison tools, which results in an error:

```
Yacc FOSFoundation/Pod/Classes/Private/FOSAdapterBinding.ym
    cd /Users/david/Repository/Customers/SteveMaher/btpios/Pods
    export PATH="/Applications/Xcode-Beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-Beta.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/yacc -w -Xanalyzer -analyzer-disable-checker -Xanalyzer deadcode -d -b /Users/david/Library/Developer/Xcode/DerivedData/BTP-cemgdgxfacaeohgsahmmkkijrtaj/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-BTP-FOSFoundation.build/DerivedSources/y /Users/david/Repository/Customers/SteveMaher/btpios/Pods/FOSFoundation/Pod/Classes/Private/FOSAdapterBinding.ym

/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- w
Try `/Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison --help' for more information.
Command /Applications/Xcode-Beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/yacc failed with exit code 1
```

These options come from various locations in the generated Pods/Pods.xcodeproj/project.pbxproj file:

```
		<dict>
			<key>fileRef</key>
			<string>C2E347DFDCCECB5CB48ABE4B</string>
			<key>isa</key>
			<string>PBXBuildFile</string>
			<key>settings</key>
			<dict>
				<key>COMPILER_FLAGS</key>
				<string>-w -Xanalyzer -analyzer-disable-checker -Xanalyzer deadcode</string>
			</dict>
		</dict>
```

If I remove options from the generated Pods/Pods.xcodeproj/project.pbxproj file, all compiles as expected.

Is there any way to not have the options apply to flex/bison files?

**Comment by Legoless** [comment]
This is a big issue, as it even breaks CI builds (unless you are commiting Pods to the repository). It would be nice to have the ability to add specific xcconfig settings to specific Pod - not entire Pods.xcconfig file, as this reflects throughout entire project in certain cases. For example, if you set CLANG_ENABLE_OBJC_ARC to NO, because .lm and .ly files do not support it (lex does not work with -fno-objc-arc flag), but then entire project will use this flag, if set with .xcconfig parameter in podspec file.

**Comment by segiddins** [comment]
This should be fixed looking at the code on master.
