### ISSUE TITLE
Unable to use dylib from Swift in pod

### ISSUE THREAD

**Issue by darrarski** [CocoaPods/CocoaPods#3130]
In one of my Swift project I am using functions defined in CommonCrypto dylib. Everything is working like expected when I am building the project directly from Xcode. It contains bridging header that imports CommonCrypto:

    #import <CommonCrypto/CommonCrypto.h>

and then I am able to call CommonCrypto function:

    CC_MD5(data.bytes, CC_LONG(data.length), resultBytes)

However, I am not able to integrate and use this project as a pod from another project. Xcode can't build pod target, because it can't see functions defined in CommonCrypto. I my podspec I have added:

    s.libraries = "commonCrypto"

But still, when building the pod target I am getting errors about undefined CC_MD5. I guess it's because the bridging header is missing in pod target, so CommonCrypto can't be imported into Swift context. I tried to fix that by defining:

    s.xcconfig = {
      'SWIFT_OBJC_BRIDGING_HEADER' => 'MyLib_Bridging_Header.h'
    }

in podspec, but then it tells me that bridging header can't be used in framework. I have also tried to define a public header in podspec:

    s.public_header_files = 'MyLib_Header.h'

but it didn't worked either, compilation was failing with error "non-modular header inside framework module".

I wonder if the problems are connected with some Cocoapods limitation, or it just my lack of knowledge about proper configuration.

**Comment by neonichu** [comment]
You can only use code in a Swift framework that comes as a module. Unfortunately, none of the dylibs that come with Apple's SDKs have modules defined for them, so you need to create one on your own. See also this thread CocoaPods/swift#8.

**Comment by darrarski** [comment]
@neonichu I really appreciate your help. I wasn't aware of `module.modulemap`. I manage to add this file to my pod, and now I can `import CommonCrypto` from swift file in my pod, but eventually I ended with another compilation error from pod's target:

    library not found for -lcommonCrypto

Perhaps you could provide some informations about configuring pod that defines module mapping. I will be very glad for any hints.

**Comment by neonichu** [comment]
@darrarski looks like the dylib cannot be found, you might have to configure search paths - I am unfamiliar with were it resides in the SDK.
