### ISSUE TITLE
Swift libraries code-signed & copied multiple times

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/CocoaPods#3131]
The `Embed Pods Frameworks` build phase copies Swift libraries separately for each framework pod.
This way most of the Swift libraries are code-signed and copied multiple times which costs a lot of time when building the project. Even when just running the app without a single change all frameworks are copied again which is slow and totally annoying.

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/pull/3166.

**Comment by AnthonyMDev** [comment]
Was this actually resolved? I've opened #3455, and it seems to be the same issue to me.

**Comment by fluidsonic** [comment]
No, this issue is not solved. cc @segiddins 

We still have to wait **2-3 minutes per build** just for the `Embed Pods Frameworks` script phase to complete. It unconditionally signs & copies all frameworks and Swift libraries even when they didn't change at all. It also signs & copies Swift libraries multiple times.

**I'd still prefer that CocoaPods lets Xcode take care of the signing & copying whenever possible.**

I know CocoaPods supports different dependencies per build configuration. Beside the fact that I don't think that that feature is good idea (people should use separate targets instead) we don't use that feature. And for sure the majority of CocoaPods users also doesn't use it. Builds should not be slowed down for the majority of users just because some users want different dependencies per build configuration. It should be possible to let Xcode handle all the signing & copying in the majority of cases.

Check out [our trimmed down log of the `Embed Pods Frameworks` script](https://gist.github.com/fluidsonic/90f381aef7ae9dff7b39):
- 2½ minutes
- 329x codesign (47x frameworks, 282x Swift libs)
- 329x rsync (47x frameworks w/ -av, 282x Swift libs w/ -auv)

**Comment by neonichu** [comment]
Relying solely on Xcode to copy the Swift libraries is not possible, as it will fail to do so in certain cases, see <http://samdmarshall.com/blog/swift_and_objc.html>

**Comment by fluidsonic** [comment]
Regarding the `libSwift*` issue:

Yes, I know about that issue. They key here is "in certain cases". Again the script phase tries to work around a problem which many users don't even have. We don't have it and yet we waste plenty time for an unnecessary script.
And the time adds up - our release cycle slowed down the last months a lot. Highest cost was unstable Xcode/Swift tooling but CocoaPods also added a lot cost recently due to scripts running on eeeevery single build. Even if I just hit "run" again without touching *anything*.

So instead of waiting for Apple to fix the issue we can think of solutions for this and reduce the build time for the majority of users:

1. The script presented in the article is one way to solve this (at least partially).
2. CocoaPods could add an own Swift file which references required frameworks to the app target(s) which causes Xcode to embed necessary Swift libraries.
3. Pods could indicate all Swift libraries they depend on through another setting in their `.podspec`.
4. CocoaPods could probably also derive necessary Swift libraries from the `frameworks` and `weak_frameworks` settings already available.
5. I could just indicate in the `Podfile` that I'm not affected by this issue (or took care of it by myself) and want to skip the `Embed Pods Frameworks` script phase entirely on my own responsibility.

Regarding `#1` and `#2` - sure, the app will be a little larger due to unnecessary Swift libraries being copied. But having a shorter build time surely makes up for that. Also CocoaPods could *still* use the slower method which is more precise for archive builds.

I'd prefer `#4` if it's possible to do or else `#5`. Solution `#5` is the least obtrusive since it allows developers to opt-in if they know what they are doing.

In any case as soon as CocoaPods does not create a `Embed Pods Frameworks` phase it must configure Xcode to embed the Pods frameworks on its own like you'd have to do it when not using CocoaPods at all. I'm just not sure whether Xcode is fine with having all Pod frameworks as targets of a single project or whether a single project is needed per Pod framework.

**Comment by neonichu** [comment]
Using a more native integration strategy might actually be at least a nice option to have, I started a WIP plugin which does this: <https://github.com/neonichu/cocoapods-native-integration>

Unfortunately, it cannot work properly at the moment, because the `PBXCopyResourceBuildPhase` cannot deal with the scoping via subdirectories we do, so any work on this is blocked by #3550
