### ISSUE TITLE
Xcode 6.3/0.36.0.beta.2 - "No such module" (facebook pop)

### ISSUE THREAD

**Issue by jrowlingson** [CocoaPods/CocoaPods#3132]
Possibly related: https://github.com/CocoaPods/CocoaPods/issues/3128

Xcode 6.3 (6D520o)
0.36.0.beta.2

Create new iOS project from template Single View App.

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'pop', '~> 1.0'
```

Then run ```pod install```, add import pop, and build via xcode and notice "No such module 'pop'"

Now replace with Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'PageMenu'
pod 'pop', '~> 1.0'
```

Then run ```pod install```, add import pop, correct for PageMenu Swift 1.2 compliance (as!), build via xcode, and notice successful build.

**Comment by segiddins** [comment]
If you want to import an ObjC pod as a module in Swift (as opposed to doing so in a bridging header), you must use `use_frameworks!` (which is implicitly done for you when you include a Swift pod).

**Comment by jrowlingson** [comment]
Thanks, this is working now:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'pop', '~> 1.0'
```

http://guides.cocoapods.org/syntax/podfile.html#use_frameworks_bang

**Comment by AgtLucas** [comment]
Odd thing, the only way that "Pop" works for me was adding `pod 'Alamofire'` in the Podfile...

**Comment by neonichu** [comment]
This is because adding a Swift Pod will make your target automatically use frameworks.

**Comment by AgtLucas** [comment]
@neonichu Good to know, thanks!

**Comment by Heisenbean** [comment]
@segiddins ,sorry to bother you,if my project supports iOS 7,and i add ```use_frameworks!``` in the Podfile.Will Apple reject my app?

**Comment by segiddins** [comment]
@Heisenbean you won't be able to submit to the App Store.
