### ISSUE TITLE
SSH with two-factor authentication 

### ISSUE THREAD

**Issue by cepages** [CocoaPods/CocoaPods#3135]
Hi 

I'm using the two fact authentication in git hub, I'm using 10.10.2  and Cocoa Pods 0.35.0

I have a private pod, which I've updated and created a new version and now I'd like to lint the podSpec file. The main problem is I can't use ssh in the source. 
```
  s.source = {
    :git => 'git@github.com:company/repo.git',
    :tag => '0.3.0'
  }
```

The problem is when we try to pass the validation we get a ruby error:

```
** BUILD SUCCEEDED **

    - WARN  | [source] Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.

[!] The spec did not pass validation.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/spec.rb:112:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>
```

It's working with https but I have to use a token and set up git credential helper. It's not a bad solution but I'd like to use ssh.

I've checked this with two different projects with the same problem.

**Comment by orta** [comment]
You can append `--allow-warnings` to your command to get around this. Not sure if this is fixed in `0.36` so keeping open

**Comment by cepages** [comment]
Thanks it's working both the lint and push:

```pod spec lint file.podspec --verbose --allow-warnings```

```pod repo push myRepo file.podspec --allow-warnings```

**Comment by chadmoone** [comment]
I don't think `--allow-warnings` is a good answer to this.  SSH is a much simpler implementation for private repositories when 2FA is enabled.  Just ignoring all warnings encourages other (more serious) issues to be ignored.

**Comment by ssoper** [comment]
Concur. I don't think use of https vs. ssh for the repo url should rise to the level of generating a warning. If folks are trying to access these behind firewalls the problem domain is on them.

**Comment by cepages** [comment]
Thanks @segiddins but the big problem is not the lint, the big problem is push the repo :)

@chadmoone I totally agree this shouldn't show a warning even it shouldn't stops the push
