### ISSUE TITLE
Single quote in project's name causes 'pod init' to write a bad Podfile

### ISSUE THREAD

**Issue by ar7hur** [CocoaPods/CocoaPods#3136]
1. Name a project `Alex's List` (note the single quote)
2. `pod init`

You get:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Alex's List' do

end

target 'Alex's ListTests' do

end
```

Which is not valid Ruby. Need to escape the single quote in this case.

**Comment by macteuts** [comment]
`target ‘Alex\’s List’ do` should work. It did for me.
