### ISSUE TITLE
`pod outdated` fails to indicate outdated pods unless preceded by `pod install`

### ISSUE THREAD

**Issue by zygoat** [CocoaPods/CocoaPods#3137]
Unless `pod install` is invoked immediately beforehand, `pod outdated` fails to give an accurate indication of out-of-date pods:

```
retinafey:Kashoo ben$ pod outdated
No updates are available.

retinafey:Kashoo ben$ pod install
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Using 1PasswordExtension (1.1)
Using AFNetworking (2.5.0)
Using Appirater (2.0.4)
Using Applause-SDK-PreProd (2.1.4)
Using CorePlot (1.5.1)
Using FBSnapshotTestCase (1.5)
Using FMDB (2.5)
Using FlurrySDK (5.4.0)
Using GRMustache (7.3.0)
Using HockeySDK (3.6.2)
Using JRSwizzle (1.0)
Using OHHTTPStubs (3.1.10)
Using SWTableViewCell (0.3.7)
Using TestFlightSDK (3.0.2)
Using zipzap (8.0.1)
Generating Pods project
Integrating client project

retinafey:Kashoo ben$ pod outdated
Analyzing dependencies
The following updates are available:
- AFNetworking 2.5.0 -> 2.5.1 (latest version 2.5.1)
- FlurrySDK 5.4.0 -> 6.0.0 (latest version 6.0.0)
- zipzap 8.0.1 -> 8.0.3 (latest version 8.0.3)
```

Note that in this example the project had already had `pod install` run several days ago, and the indicated "Using…" versions were already installed and built (i.e., invoking `pod install` here was not otherwise necessary).

This is misleading behaviour. One would reasonably expect `pod outdated` to consult the remote podspec repo in order to produce its results.

Furthermore, the apparent requirement of running a preceding `pod install` is not documented in the user guide.

**Comment by neonichu** [comment]
Actually, what is required is running `pod repo update`, which `pod install` implicitly does. I believe it is by design that `pod outdated` does not update the user's spec repos - @segiddins?

**Comment by segiddins** [comment]
Yeah, I think `outdated` not updating the specs repo is intentional (we don't want to trigger a large `git pull` unless absolutely necessary).

**Comment by neonichu** [comment]
We should update `--help` and the guides, though - the inclusion of `--no-repo-update` as option indeed heavily suggests that a manual update is not necessary.

**Comment by zygoat** [comment]
But under what circumstances would it be preferable to run a version comparison against an out-of-date repo?

Further, if the local repo is already up to date, won't the pull be negligible? (Conversely, the more out of date it is, the more likely that the version comparison will produce noteworthy results of the sort one is seeking by running the command.)

**Comment by zygoat** [comment]
To put it another way, if I am running `pod outdated`, it's precisely because I have reason to believe my local environment is out of date. Wholly implicit is my desire to compare it against the current remote repo. Thus, it would not occur to me that an additional step would first be required in order for my effort to actually work properly. (Worse, failing to do this gives no indication of my mistake, and leads me to conclude that everything is up to date.)

**Comment by segiddins** [comment]
@zygoat I'm starting to agree

**Comment by neonichu** [comment]
I also agree after thinking a bit about it.

In addition to that, the version history of the outdated command does not suggest it was ever deliberate that it doesn't `pod repo update` automatically, but it seems more like an unintended consequence of some other change.

**Comment by segiddins** [comment]
I'll change this today, just want to beef up the `outdated` test coverage
