### ISSUE TITLE
Running pod install after installing development pod ignores development pod

### ISSUE THREAD

**Issue by mtitolo** [CocoaPods/CocoaPods#3141]
Switching from a public pod to a development pod is ignored if you `pod install` multiple times.

Repro steps:
- Change 1 pod to `:path`
- `pod install`
- `pod install` again. It will download instead of using the local files.

**Comment by segiddins** [comment]
@mtitolo can you share the diff of your Lockfile?

**Comment by mtitolo** [comment]
@segiddins the lock file and Manifest.lock correctly shows `:path` as set in the Podfile.

When I run with `--verbose` This shows up:
```
Creating possibility state for MyLib (from `../../mylib`) (1 remaining)
  Attempting to activate MyLib (0.0.3)
  Activated Requests at MyLib (0.0.3)
[...]
Comparing resolved specification to the sandbox manifest
  M MyLib
```

When not running locally, we specify the `:git` and `:tag` of the pod. I haven't bumped the version in the spec yet. Not sure if this changes things.

**Comment by segiddins** [comment]
So the it's detecting that something has changed... could you possibly provide me with the entire verbose output?

**Comment by segiddins** [comment]
The issue is likely that the checkout source is never being removed when installing via `:path`.
