### ISSUE TITLE
[0.36.0.beta.2] Won't update to latest pod in podspec

### ISSUE THREAD

**Issue by atomkirk** [CocoaPods/CocoaPods#3148]
I have no idea if I've done something wrong or what, but I'll just state the facts:
I installed and tried `0.36.0.beta.2` and tried to install 
```ruby
pod 'MYSForms', path: 'libs/MYSForms'
```
which is at version 0.1.0 per the podspec file. But I kept getting `Using MYSForms (0.0.4)` when I did a `pod install` or `pod update`, or even after deleting my `Podfile.lock` file and doing a `pod install`.

So then I `gem uninstall cococapods && gem install cocoapods` to install `0.35.0`, then I delete the lock file and I get `Installing MYSForms 0.1.0 (was 0.0.4)`

So the same steps 1) delete lock file 2) run `pod install` would not update the pod, but after downgrading from `0.36.0.beta.2` to `0.35.0` it worked.

**Comment by atomkirk** [comment]
Also, when building in Xcode, no matter what I tried, after installing with `0.36.0.beta.2`, I got this:
```
/Users/adamkirk/me/projects/two-stories/ios/Pods/${BUILT_PRODUCTS_DIR}/MYSForms.bundle
building file list ... rsync: link_stat "/Users/adamkirk/me/projects/two-stories/ios/Pods/${BUILT_PRODUCTS_DIR}/MYSForms.bundle" failed: No such file or directory (2)
```

After I downgraded to `0.35.0`, it built fine.

**Comment by segiddins** [comment]
The second issue has been fixed.

Can you provide the verbose output of running `pod install` with the latest beta, and also the contents of your `Pods/Local Podspecs` directory? Thanks!

**Comment by atomkirk** [comment]
The second issue has been fixed in beta3?

**Comment by segiddins** [comment]
A fix for it is in `master` (https://github.com/CocoaPods/CocoaPods/pull/3085).

**Comment by segiddins** [comment]
Your issue is probably fixed by https://github.com/CocoaPods/CocoaPods/pull/3147. Feel free to re-open if that's not the case.
