### ISSUE TITLE
Adding platforms after initial pod install can lead to missing files

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/CocoaPods#3150]
I'm using the pod "ContentfulDeliveryAPI" as an example here, it has a different set of header files for OS X and iOS.

Start with a Podfile with just an OS X target:

```ruby
platform :osx, '10.10'

target 'osx' do
pod 'ContentfulDeliveryAPI'
end
```

Running `pod install --no-integrate` will only keep the OS X specific headers in the Pods directory.

If one adds an iOS target afterwards:

```ruby
target 'ios' do
platform :ios, '8.0'
pod 'ContentfulDeliveryAPI'
end
```

Running `pod install --no-integrate` again will not add any headers as there has been no change in versions and the checkout is deemed to be accurate.

I think we need to keep the union of files for all platforms around, not just the one requested during a certain `pod install`.

**Comment by segiddins** [comment]
@neonichu I'd lean towards storing platform requirements in the lockfile, and just re-installing the pod from the cache when the platforms change.

**Comment by neonichu** [comment]
@segiddins that seems like a good solution :+1:
