### ISSUE TITLE
No integrate option unnecessarily requires a global platform setting

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/CocoaPods#3151]
Using this Podfile:

```ruby
target 'osx' do
platform :osx, '10.10'
pod 'ContentfulDeliveryAPI'
end
```

Running `pod install --no-integrate` fails:

```
Analyzing dependencies
[!] It is necessary to specify the platform in the Podfile if not integrating.
```

This seems unnecessary, as the target has defined a platform.

**Comment by segiddins** [comment]
Known bug. It should probably only check the target definitions which have pods.

**Comment by andreydanil** [comment]
I got same problem and it was fixed after running pod setup and then pod install.

**Comment by sguillope** [comment]
@segiddins 
> It should probably only check the target definitions which have pods.

What do you think should be done with [`Analyzer:258`](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer.rb#L258)? Ok to skip?
