### ISSUE TITLE
Multiple C sources

### ISSUE THREAD

**Issue by CodeReaper** [CocoaPods/CocoaPods#3152]
🌈

I am trying to make a pod which has multiple sources of c code, but I don't see how to handle multiple sources when some of the sources isn't meant to compile on their own.

There is a main c project which compiles fine and the other sources I have are c code files which is meant to be placed in the source directory of the main project.

I have tried defining the other sources as dependencies as separate pods (which doesn't built on its own) and as subspecs (but the subspec source was ignored). Downloading all the sources and stashing them in a repo, doesn't seem all that pod-like.

For a specific example, these files https://github.com/zhanjunxiong/luapb/tree/master/src are meant to be among the files from http://www.lua.org/ftp/lua-5.1.5.tar.gz

Does cocoapods support a way of doing this, is this something that cocoapods should potentially support in a future version or is my use case too weird?

**Comment by segiddins** [comment]
Basically, you'll need to define podspecs for each of the sources, or otherwise create some sort of aggregate source.

**Comment by CodeReaper** [comment]
Separate podspecs would mean they cannot build on their own and doesn't the source from each podspec go in its own directory? The C sources I am talking about here must all go into one directory in order to be built.

**Comment by neonichu** [comment]
But <https://github.com/zhanjunxiong/luapb/blob/master/Makefile> builds with an installed version of Lua, that should also be possible when encapsulating it into a podspec. A podspec for Lua itself already exists, so you should depend on that.
