### ISSUE TITLE
ld: library not found for -lPods

### ISSUE THREAD

**Issue by Lukaz32** [CocoaPods/CocoaPods#3157]
My project won't compile due to the error: "ld: library not found for -lPods"
I began after I've updated to the prerelease version of Cocoapods .0.36
What might be going on? 
![screen shot 2015-02-18 at 2 44 55 pm](https://cloud.githubusercontent.com/assets/544727/6251836/619f0ae8-b77d-11e4-8853-17839d8c8f6d.png)

**Comment by orta** [comment]
Looks like we have an unescaped space somewhere.

**Comment by Lukaz32** [comment]
How can I fix it?

**Comment by orta** [comment]
This looks to be due to some custom framework search paths in your target.

**Comment by kylef** [comment]
Can you attach your Podfile to this issue @Lukaz32, there is very little information in your ticket to figure out the problem here.

**Comment by sunforhappy** [comment]
I have encountered similar problem yesterday, and solve it by roll back to v0.35. My project can compile and run in develop mode, and can not compile when it is archived.
the podfile is like this:
platform :ios, '7.0'
pod "AFNetworking", "~>2.0"
pod 'SSKeychain', '~> 1.2.2'
pod 'JSQSystemSoundPlayer'
pod 'UIView+Positioning'
pod 'UIImage-Resize' 
pod 'UICountingLabel'
pod 'AVOSCloud' #this library is the one which lead to compile error
pod 'NSDate+TimeAgo', '~> 1.0.3'
pod 'PureLayout'
pod 'iOS-Hierarchy-Viewer'
pod 'QueryKit'
pod 'DateTools'

**Comment by kylef** [comment]
@sunforhappy that issue sounds completely unrelated and you should file a separate issue.

Since the original issue has been awaiting feedback for over a month I'm going to close. Please re-open when the requested information was added.
