### ISSUE TITLE
Using a pod (which produce framework) in another pod

### ISSUE THREAD

**Issue by muccy** [CocoaPods/CocoaPods#3161]
Hi,
recently Google has updated its pod `Google-Mobile-Ads-SDK`, which now produce a framework. I have a public podspec called `MUKAdMobViewController` which has a dependency to it, and I would like to support new major version.
I paste you podspec:
```
Pod::Spec.new do |s|
  s.name      = 'MUKAdMobViewController'
  s.platform  = :ios, '6.0'
  s.version   = '1.2.4'
  s.summary   = 'View controller which manages an AdMob banner, geolocation and interstitial presentation.'

  s.source = {
    :git => 'https://github.com/muccy/MUKAdMobViewController.git',
    :tag => s.version.to_s
  }
  
  s.requires_arc    = true
  s.source_files    = 'MUKAdMobViewController/*.{h,m}'
  s.compiler_flags  = '-Wdocumentation'
  s.frameworks      = 'CoreLocation'
  
  s.dependency 'Google-Mobile-Ads-SDK', '~> 6.6'
end
```

I bumped up dependency version (`s.dependency 'Google-Mobile-Ads-SDK', '~> 7.0'`) and problems started. I have an example app created to develop `MUKAdMobViewController`.
![schermata 2015-02-19 alle 15 45 22](https://cloud.githubusercontent.com/assets/18466/6268587/53b65054-b84e-11e4-86ff-78ccb95f6ac9.png)

On top you can see two files of my pod: they are actually built by `Pods-MUKAdMobViewController` target, as you know. And that is why header files can not be found. There is no reference to `GoogleMobileAds.framework` there.
![schermata 2015-02-19 alle 15 48 06](https://cloud.githubusercontent.com/assets/18466/6268650/b9e02238-b84e-11e4-89f0-0e4e71cf9106.png)

Before they adopted framework there was no problem. 
Before to post an issue I tried circumvent the problem by setting manually linker flags like `HEADER_SEARCH_PATHS` or `-framework` in `OTHER_LDFLAGS`, but with no success.

How can I do? Thanks.

**Comment by neonichu** [comment]
If I understand #2722 correctly, it should not be needed anymore to define `public_header_files` for `vendored_frameworks`. However, for the Google-Mobile-Ads-SDK spec, the headers do not get symlinked automatically. @alloy any ideas?

**Comment by muccy** [comment]
I forgot to mention I'm using CocoaPods version 0.35.0.
I would like to highlight once more that `<GoogleMobileAds/GoogleMobileAds.h>` is found correctly inside the application (e.g. `MUKAdMobViewControllerExample` project) but not inside pod target (`Pods-MUKAdMobViewController`).
Thanks :)

**Comment by neonichu** [comment]
Right, this happens because the application target will have Frameworks Search Paths set correctly, but not the Pod target.

**Comment by alloy** [comment]
@neonichu In fact it never symlinks the headers by default. Clients (RM/CocoaDocs) could ask for them to be included with `public_headers(true)`. Ideally the frameworks search paths would be set appropriately, as you suggested, but a simple fix would be to _do_ make #2722 symlink the headers by default (30ebfc4ccefafdd4a2549e92798f0e622e62071c).

**Comment by Whirlwind** [comment]
```
Ideally the frameworks search paths would be set appropriately
```
I think it is good way. And is there anybody to fix it? Or simple fix it without change the Admob's spec?

**Comment by Whirlwind** [comment]
@alloy, anybody will fix it by adding the framework search paths? I am waiting...

**Comment by AliSoftware** [comment]
> I am waiting...

@Whirlwind Why don't you help the team out by making a PR? CocoaPods is a free and comunnity-basec tool so every contribution is welcome and will help :wink:

**Comment by Whirlwind** [comment]
@AliSoftware I hope I can make a PR, But I am new to ruby...

**Comment by AliSoftware** [comment]
I was new to ruby too until my first CocoaPods PR and I learned ruby by doing small PRs for CocoaPods myself :wink:

Small issues like this one are actually a good way to start learning Ruby, and the team is pretty helpful if you have any questions. See also [this interesting testimony from Hugo on CocoaPods' blog](http://blog.cocoapods.org/starting-open-source/) :smiley:

**Comment by vincentisambart** [comment]
Investigating things a bit, it seems that changing `file_accessor.public_headers ` to `file_accessor.public_headers(true)` at [file_references_installer.rb:126](https://github.com/CocoaPods/CocoaPods/blob/2e117f9f9df31b5a0f1bac372b2a67a7739eb71e/lib/cocoapods/installer/file_references_installer.rb#L126) mostly does the trick.

However, if you just use `public_headers(true)`, to include the file you would do `#include <PodName/MyHeader.h>`, not `#include <FrameworkName/MyHeader.h>`.
Which one do you think is best, `PodName/MyHeader.h` or `FrameworkName/MyHeader.h`?

**Comment by vincentisambart** [comment]
Oops, trying a bit more I realized that it has to be FrameworkName/MyHeader.h or else the includes inside the framework won't work.

**Comment by vhariable** [comment]
I tested this out as I was having this exact issue also. It partially works, but in this example of GoogleMobileAds, the framework headers include sub-directories containing headers that do not get symlinked (Loading, Mediation, and Search). The Loading sub-directory also contains sub-directories also.

**Comment by vhariable** [comment]
This fixes the issue. Tested in both a static framework using a podfile, and also a project using the previous static framework.

```
def self.vendored_frameworks_headers(framework)
    headers_dir = vendored_frameworks_headers_dir(framework)
    Pathname.glob(headers_dir + "**/" + GLOB_PATTERNS[:public_header_files])
end
```

**Comment by neonichu** [comment]
@vhariable cool, would you mind crafting a PR for that? That would be awesome!

**Comment by vhariable** [comment]
Would be glad to, didn't want to step on anyone's toes.

**Comment by ajayempty** [comment]
Hi,
i am trying to import pod file in my pod but i don't know how to i import that pod files.
![screen shot 2019-02-27 at 11 26 15 am](https://user-images.githubusercontent.com/46438229/53469256-37096480-3a83-11e9-9fc7-5b80ad25a583.png)
