### ISSUE TITLE
pathname.rb:422:in `open': No such file or directory - ~/.cocoapods/repos (Errno::ENOENT)

### ISSUE THREAD

**Issue by jdmuys** [CocoaPods/CocoaPods#3162]
I get that error message, whether I run `pod install` or `pod update`.
This is on a new install of Mac OS X Yosemite, Xcode 6.3 and cocoa pod, where I then git-cloned an existing project.
I have cocoa pod version 0.35.0

The directory ~/.cocoapods/ doesn't exist at all on my machine.

My podfile mentions restkit. I found two past issues with similar 'file not found' problems, which I read very carefully, but which left me clueless on how to fix my problem.

I was suggested to remove the Podfile.lock file, but that didn't help at all.

Here is the podfile:
#---------------------------------------------------------------
platform :ios, '7.1'

pod 'RestKit', '~> 0.20.2'

pod 'RestKit/Testing', '~> 0.20.2'
pod 'RestKit/Search', '~> 0.20.2'

pod 'CHCSVParser', '~> 2.0.7'
pod 'TPKeyboardAvoiding', '~> 1.0'
pod "PPSSignatureView"

**Comment by kylef** [comment]
This was fixed by https://github.com/CocoaPods/CocoaPods/commit/0994612ebb65ad1aa221f384235e4702560df7d2 and is in CocoaPods 0.36.0.beta.2.

Please search existing issues / try the latest version before filing issues.

As a workaround you can run the following:

```bash
$ pod setup
```
