### ISSUE TITLE
`pod install` Creates Schemes for Pods

### ISSUE THREAD

**Issue by fabb** [CocoaPods/CocoaPods#3165]
Unused Schemes clutter up the Schemes list, and the Pod Schemes are not really necessary. `pod install` recreates them every time, which should be avoided.

**Comment by segiddins** [comment]
Those schemes are necessary to build the pods?

**Comment by fabb** [comment]
No they are not. I always delete them and the build works fine.

**Comment by segiddins** [comment]
The schemes that are created should be hidden.

**Comment by fabb** [comment]
I use AppCode. Not sure if it supports hidden schemes.

**Comment by segiddins** [comment]
Ah well that sounds like an AppCode issue then!

**Comment by fabb** [comment]
I still do not understand why cocoapods needs to create these schemes. I think its unnecessary.

**Comment by segiddins** [comment]
Feel free to make a PR changing the behaviour, but as it's not really harmful, it's not a high priority.

**Comment by orta** [comment]
This is interesting. I dug back in the history a bit to get a sense of why the schemes exist at all.  Looks like they were added in  [0.26](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#0261) as a way to specifically compile a single pod.

IMO that's a feature no-one needs. I'd be :+1: on removing the per-pod schemes.

**Comment by segiddins** [comment]
I'm worried that scheme auto-creation will recreate all of those schemes, and they will no longer be hidden, so this requires some exploration.

**Comment by segiddins** [comment]
Closing. if appcode has that same visibility toggle is really irrelevant to the correct management of the targets in the pods projects, either cocoapods will make them or xcode will because if you want to build anything that isn't an explicit dependency you need a scheme.

**Comment by fabb** [comment]
Please reopen. The setting whether a scheme should be shown (`isShown`) is stored in `xcschememanagement.plist` in `xcuserdata`. So the setting is per-user which is impractical for version controlled projects - which will have `xcuserdata` in `.gitignore`.

I'd strongly suggest to just not create these schemes as they are not needed for anything.

**Comment by J-Rojas** [comment]
I'm having the same problem on AppCode. If these schemes are superfluous, please reopen and consider a fix.

**Comment by asalom** [comment]
I'd like this to be fixed as well or at least to have them all hidden by default or with some configuration. If you hide them, once you run pod install they show up again.

**Comment by fabb** [comment]
As these schemes are not needed, I'd rather suggest not creating them in the first place.

**Comment by neonichu** [comment]
These schemes are a necessary building block for things like CocoaPods/pod-template#106

My suggestion would be a plugin that removes schemes you don't want automatically via a `post_install` hook.

**Comment by fluidsonic** [comment]
We also have the issue **in Xcode** where after each `pod update` 100+ schemes are recreated automatically.

Looks like schemes for normal Pods are hidden while for development Pods they are not.
The scheme dropdown list in Xcode is so long that we have to scroll it all the time we want to switch our app target.

Note that `Autocreate Schemes` in Xcode is turned off.

**Please provide an option to prevent scheme creation.** Even if just by honoring Xcode's `Autocreate Schemes` option.
Also `pod update` became a lot slower in the recent months and by preventing scheme auto-creation we can easily save some time here.

**Comment by neonichu** [comment]
An option sounds acceptable

**Comment by fluidsonic** [comment]
Since this issue is closed should I create a new one with the suggestion to add such an option?

**Comment by danielpetroianu** [comment]
Hi, I've encountered similar behaviour.
I'm using 0.37.2 and when I'm executing `pod install` / `pod update` it creates schemas for all the **development** pods (and the annoying thing is that it always selects the first created one).
The schemes are *visible* and *shared*.

From what I can see, it happens only when I specify the development pods inside a `target`.
```
target "AppTarget" do
   pod "devPod", :path => "devPod"
end
```
I've downgraded to 0.35.0, and I don't see this happening.

Any thoughts?

**Comment by neonichu** [comment]
As stated before, this is deliberate. We'd be happy to accept a PR which adds a configuration option to turn it off, though.

**Comment by Buju77** [comment]
I'm also having this issue since we upgraded to 0.37.2. After each `pod update` it will recreate schemes for all pods it has. and the development pods are marked as **visible** and **shared** and it selects one of them as active one (even though we have selected our app scheme before)

this was not an issue before in 0.33.1. So this was introduced as some kind of "new" in the version between 0.35 (as @danielpetroianu mentioned) and 0.37.

**Comment by neonichu** [comment]
See #3824 for more discussion on this and the fix we're going to do.

**Comment by jaredsinclair** [comment]
I tried reading through #3824 and I can't tell what the resolution is. Is there a final word yet?

**Comment by eneko** [comment]
Any updates on this? As of February 2016, with CocoaPods 0.39.0, running `pod install` / `pod update` still creates Schemes (which is fine to me), but makes them visible ('Show' is checked) and also shared ('Shared' is checked). Furthermore, it makes the first one selected, as some folks have indicated before.

**Comment by keven-pogrzeba** [comment]
I would also like pod update not to create these schemes. any updates on this?

**Comment by segiddins** [comment]
See https://github.com/CocoaPods/CocoaPods/pull/5254

**Comment by revolter** [comment]
You use this by adding this to your `Podfile`:

    install! 'cocoapods',
        :share_schemes_for_development_pods => false
