### ISSUE TITLE
Pods library in Makefile

### ISSUE THREAD

**Issue by pmuvva** [CocoaPods/CocoaPods#3169]
Hi,

I want to compile lPods along with current Xcode project by using Makefile.  Below command I am using:
xcodebuild -project $(XCODE_PROJNAME) -arch arm64 -target $(XCODE_TARGET_NAME) -configuration $(XCODE_CONFIGURATION) -sdk iphoneos$(SDK_VER) build RUN_CLANG_STATIC_ANALYZER=YES

How to include PODS libraries in Makefile.

I am able to build by using Xcode 6 but not succeed in command line MAKEFILE.

My Podfile:
source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'iOSClient'
platform :ios, '8.0'
inhibit_all_warnings!
link_with 'iOSClient','CWSUnitTest','CWSAutoTest','CWSIntegrationTest'
pod "Brightcove-Player-SDK"

It is not able to find the lPods and libBCOVPlayerSDK.a .

Please help me to fix this.

**Comment by pmuvva** [comment]
shall I keep workspace name instead of xcodeproj?

**Comment by segiddins** [comment]
Yes, you'll need to build from the workspace, just like when building from inside Xcode.
