### ISSUE TITLE
Missing headers in Framework bundle in signed app preventing install on iOS Device

### ISSUE THREAD

**Issue by thebluepotato** [CocoaPods/CocoaPods#3170]
Hi! :rainbow:
I've recently begun using Cocoapods to handle my project's dependencies (Alamofire, SwiftyJSON and Ono). I'm using cocoapods 0.36b2 because my project and two of the dependencies are written in Swift.

Building and running works without any errors on the **Simulator**. However, when building and running for an **iOS device**, the build is successful but the running fails because "A signed resource has been added, modified, or deleted". After carefully analyzing the logs, I saw that the device refused the app because there was a codesigning issue with the **Frameworks** (and not with nib's as in [#790][1]). Although `codesign -vvvv myApp.app`didn't show any errors, `codesign -vvvv myApp.app/Frameworks/*`outputted following errors :

    $ codesign -vvvv myApp.app/Frameworks/*
    Frameworks/Alamofire.framework: a sealed resource is missing or invalid
    file missing: /Users/xxxx/Library/Developer/Xcode/DerivedData/myApp-xxx/Build/Products/Debug-iphoneos/myApp.app/Frameworks/Alamofire.framework/Headers/Pods-AO3-Alamofire-umbrella.h
    file missing: /Users/xxxx/Library/Developer/Xcode/DerivedData/myApp-xxx/Build/Products/Debug-iphoneos/myApp.app/Frameworks/Alamofire.framework/Headers/Alamofire-Swift.h
After pinpointing the issue I found that each Framework was missing a Headers directory which was referenced in the app's CodeSignature and in each Framework's CodeSignature too. After copying said directories from `Build/Products/Debug-iphoneos/Pods-myApp` where each Framework bundle is located (and contains the Headers directory), I could run the app on the device as usual.

I couldn't find these headers in the Simulator build but it ran, as said before, without any issues. Are these headers required for functionality?

I've also tried building and running a clean and new project with the same podfile and it outputted exactly the same error. I did the same after reinstalling Cocoapods, still the same.

So my question is : is Cocoapods failing to copy said Headers after having them signed or is the signing process referencing files it shouldn't? So here's my "bug report", hoping it's not just a misunderstanding on my side. As of course archive's also require signing, it might be related with issue [#3156][2] but I don't have enough info on that one.

**EDIT**: Now (after reinstalling cocoapods) it's actually worse because now copying the headers satisfies codesign for the frameworks but breaks codesign for the app. When it was still working I had copied the headers in each framework and commented each line in the app's CodeResources referencing these headers and it worked. Now they're not referenced in the app's CodeResources anymore and commenting the lines in each Frameworks CodeResources breaks the signing of the app because that's modifying a signed file...

  [1]: https://github.com/CocoaPods/CocoaPods/issues/790
  [2]: https://github.com/CocoaPods/CocoaPods/issues/3156

**Comment by thebluepotato** [comment]
So sorry guys, it turned out to be some very deep set conflicting signing identities which caused these issues. I've redone the xcodeproj and it's now working flawlessly. Thank you for Cocoapods and the amazing work you're doing with it!

**Comment by kylef** [comment]
Awesome, I'm glad you managed to fix the issue. Thanks for updating this issue. :balloon:
