### ISSUE TITLE
Cache non-local Pods

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#3172]
About a year ago, we killed the git cache in CocoaPods for the sake of simplicity, but it's made `pod install` (and the other commands that use it) much slower in certain circumstance.

We ought to create a new cache (like the one in Bundler) that lives inside CocoaPods itself (rather than the downloader), and will cache released pod versions, as well as git commits/tags.

**Comment by radex** [comment]
:+1:

**Comment by yanzhiwei147** [comment]
yep! This feature very important, like Maven can cache the reop for download,it can reuse package without re-download.
so how long can be release this feature?

**Comment by orta** [comment]
This has an active PR: https://github.com/CocoaPods/CocoaPods/pull/3236
