### ISSUE TITLE
Support parallel source downloading

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#3173]
Download multiple sources at once simultaneously ala [peru](https://github.com/buildinspace/peru).

![](https://github.com/buildinspace/peru/raw/master/docs/peru.gif)
Love their UX too.

Likely correlated: https://github.com/CocoaPods/CocoaPods/issues/3172
Warning, things like `Dir.chdir` will need to be taking into account

**Comment by segiddins** [comment]
This is a duplicate of an old issue I worked on last April.

**Comment by kylef** [comment]
#2100
