### ISSUE TITLE
Adding and referencing images in Swift Embedded Framework

### ISSUE THREAD

**Issue by dbettermann** [CocoaPods/CocoaPods#3174]
Hello,

I recently added some images to my Swift Embedded Framework (`s.source_files = 'Folder/*.swift', 'Folder/Artwork/*'`). I didn't get any errors in the pod after building it.

When I included the pod in a different project I got an exception. More specifically, I get an EXEC_BAD_INSTRUCTION on my main thread. I confirmed that it was the images by changing `UIImageView(image: UIImage(named: "name")!)` to `UIImageView()`.

Any thoughts? I am happy to provide more information.

**Comment by orta** [comment]
You cannot use `imageNamed` with Frameworks as the image sits in a different bundle to your application. 

Looks like a real error, because you're forcing an unwrapping of an object that doesn't exist. You would need to use `bundleForClass:` to then find the framework and get the image from that bundle.

**Comment by dbettermann** [comment]
Thank you for the quick response, @orta

I attempted to implement your solution, but I'm unable to get the image.

    let testBundle = NSBundle(forClass: self.dynamicType)
    println(testBundle) // prints the loaded bundle
    
    let testImage = UIImage(named: "lock", inBundle: testBundle, compatibleWithTraitCollection: nil)
    println(testImage) // prints nil

    let testImage4 = testBundle.pathForResource("lock", ofType: "png")
    println(testImage4) // prints nil

Sorry if it's something simple. I also tried `<PodClass>.self` for the class and was also unsuccessful.

**Comment by kylef** [comment]
@dbettermann You need to put your resources in the resources section of you podpsec and not the source files part. See http://guides.cocoapods.org/syntax/podspec.html#resources.

```ruby
s.source_files = 'Folder/*.swift', 'Folder/Artwork/*'
```

**Comment by dbettermann** [comment]
@kylef Awesome. That was it. I forgot about the resources section. Thank you!
