### ISSUE TITLE
Location of compiled binary files location

### ISSUE THREAD

**Issue by pmuvva** [CocoaPods/CocoaPods#3175]
Hi,

I compiled my project in command line:
```
xcodebuild -workspace iOSClient.xcworkspace -scheme "iOSClient" -configuration $(XCODE_CONFIGURATION) -arch arm64 -sdk iphoneos$(SDK_VER) build RUN_CLANG_STATIC_ANALYZER=YES
```
After the compilation then all the binaries are going to below path:
```
~/Library/Developer/Xcode/DerivedData/iOSClient-aurazgodruawefdvrdxvvznfigkd/Build/Products/Debug-iphoneos
```
This path is always fixed to get the libPods-Brightcove-Player-SDK.a and libPods.a .

I want to change output binary file location to "./Build" from Current working directory. How to set this path?

**Comment by kylef** [comment]
Hey,

Currently this isn't possible. However there is an open pull request over at https://github.com/CocoaPods/CocoaPods/pull/2880 which would make this possible.
