### ISSUE TITLE
Support fonts directly in a podspec

### ISSUE THREAD

**Issue by hborders** [CocoaPods/CocoaPods#3176]
[The code necessary to add custom fonts to my pod is scary.](http://stackoverflow.com/questions/12919513/how-do-i-add-a-custom-font-to-a-cocoapod) I wish there was a `fonts` property like `resources` that automatically modified the Info.plist accordingly.

**Comment by kylef** [comment]
The way that's done in that link wouldn't even work. I'd take a look at https://github.com/CocoaPods-Fonts/OpenSans which is a little more elegant and doesn't require such craziness.

**Comment by hborders** [comment]
That looks very similar to [the workaround I was going to use](http://stackoverflow.com/a/15521113/9636). However, if I was creating a framework manually, isn't it possible to specify custom fonts in the framework's Info.plist so that I wouldn't need to do the CoreText steps? If not, can the fonts be added to the main app's Info.plist?

**Comment by neonichu** [comment]
There's no way to do this in the framework's Info.plist, unfortunately. I don't think we should mess with the app's Info.plist, either - it'll lead to madness like the code from the original issue comment.

**Comment by orta** [comment]
https://github.com/artsy/Artsy-OSSUIFontsIMO, I don't think it's terrible to ask someone to add the keys to their plist.
