### ISSUE TITLE
RSS feed is not update

### ISSUE THREAD

**Issue by ersentekin** [CocoaPods/CocoaPods#3179]
Hey, I was using http://feeds.cocoapods.org/new-pods.rss url to fetch new pods.
But it looks like it's not an update rss feed right now. I saw it's not matching to @CocoaPodsFeed on Twitter. 

Something wrong with it?

**Comment by kylef** [comment]
Thanks for reporting this @ersentekin, I've filed an issue on the repository for the feeds API itself (https://github.com/CocoaPods/feeds.cocoapods.org/issues/269). Not sure what happened to it, but looks like it's been broken for a while.
