### ISSUE TITLE
Dependency not resolved for local podspec

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#3180]
Podfile:

    pod 'ObjectivePGP', :path => '~/Devel/objectivepgp-master'

from my ObjectivePGP.podspec

    s.dependency 'OpenSSL-Universal'
  
    [!] Unable to satisfy the following requirements:
        - `OpenSSL-Universal` required by `ObjectivePGP (0.3.2)`

So I added it manually

    pod 'OpenSSL-Universal'

but then

    $ pod install
    Analyzing dependencies
    Fetching podspec for `ObjectivePGP` from `~/Devel/objectivepgp-master`
    [!] Unable to satisfy the following requirements:

    - `OpenSSL-Universal` required by `Podfile`
    - `OpenSSL-Universal` required by `ObjectivePGP (0.3.2)`

I found that I have to specify version number for dependency, to make it work

    pod 'OpenSSL-Universal', '1.0.1.l'

this is as expected? why dependency is not installed automatically ?

$ pod --version
0.36.0.beta.2

**Comment by kylef** [comment]
That is as expected, it's because there is only pre-releases of the OpenSSL-Universal pod, `1.0.1.l, 1.0.1.k, 1.0.1.j-2, 1.0.1.j, 1.0.1.i, 1.0.1.h, 1.0.1.g, 1.0.1.f` as per [semantic versioning](http://semver.org).  #1489 

If you depended on it including pre-releases it would work, as follows:

```ruby
spec.dependency 'OpenSSL-Universal', '~> 1.0.1.l'
```

**Comment by krzyzanowskim** [comment]
I wonder how to change it then. If I change it to `1.0.1l` I'll break semantic versioning, however will it resolve right then ?

**Comment by kylef** [comment]
`1.0.1l` would still be a pre-release.

**Comment by krzyzanowskim** [comment]
is there a good solution for this problem, `101.l` maybe?

**Comment by segiddins** [comment]
`>= 1.0.1a, < 1.0.2`?

**Comment by kylef** [comment]
I'd suggest maybe going down the path that the OpenSSL pod uses. Which is to encode the character as a decimal.

1.0.1a becomes 1.0.1.1, 1.0.2b becomes 1.0.1.2 etc.
