### ISSUE TITLE
beta 2 uses in resource shell single quotes

### ISSUE THREAD

**Issue by Igor-Palaguta** [CocoaPods/CocoaPods#3182]
Hello,

I switched to 0.36.0.beta.2

And now resource script fails during processing resource with env variable inside

in beta.1 double quotes were used, and file name was properly interpolated
install_resource "${BUILT_PRODUCTS_DIR}/Appirater.bundle"

but in beta.2 signal quotes are used
install_resource '${BUILT_PRODUCTS_DIR}/Appirater.bundle'

**Comment by orta** [comment]
This is fixed in master, for now you can edit the `'` to `"` and it will compile, we should be getting a new build out very soon.

**Comment by Igor-Palaguta** [comment]
Thank you for so fast response, waiting for beta.3)
