### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by pmuvva** [CocoaPods/CocoaPods#3186]
Hi,

I used below command line to compile the workspace:
xcodebuild -workspace demoApp.xcworkspace -scheme "demoAppCWS" -arch i386 -configuration $(XCODE_CONFIGURATION) -sdk iphonesimulator$(SDK_VER) build RUN_CLANG_STATIC_ANALYZER=YES

I got the the error: 
fatal error: file '/Users/pmuvva/gitrepo/iOS/demoApp/Pods/Target Support Files/Pods/Pods-environment.h' has been modified since the precompiled header
'/Users/pmuvva/Library/Developer/Xcode/DerivedData/demoApp-aysavilfyulpfuhhvzbiqwwoyzzd/Build/Intermediates/PrecompiledHeaders/Pods-Brightcove-Player-SDK-prefix-cuaepauopatfpfdniaqufyufqtzi/Pods-Brightcove-Player-SDK-prefix.pch.pch'
was built
note: please rebuild precompiled header
'/Users/pmuvva/Library/Developer/Xcode/DerivedData/demoApp-aysavilfyulpfuhhvzbiqwwoyzzd/Build/Intermediates/PrecompiledHeaders/Pods-Brightcove-Player-SDK-prefix-cuaepauopatfpfdniaqufyufqtzi/Pods-Brightcove-Player-SDK-prefix.pch.pch'
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

** BUILD FAILED **

If I replace the architecture from i386 to X86_64 then it doesn't show the error.
I am using Xcode 6.1.1

I referred #2394 still I am not able to resolve......

Any info regarding this issue...

**Comment by neonichu** [comment]
It's an unfortunate Xcode issue - there's <https://github.com/alloy/AxeMode> until Apple fixes it or you can delete DerivedData / clean your project if you hit it. In any case, feel free to file a radar to get this fixed eventually. :satellite:
