### ISSUE TITLE
Proper Sources plugin API

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#3190]
We should make the SourcesManager more extensible for CocoaPods plugins.

**Comment by clarkda** [comment]
! Thanks @kylef

What did you have in mind @segiddins?

**Comment by segiddins** [comment]
No idea yet! As you're likely going to be the first consumer, it would be helpful to know what sort of API you'd need.

**Comment by amorde** [comment]
Any news on this? I am currently writing a plugin to support declaring private repositories as described in #3061 because there is still no way to have a private repository that is not using git. Overriding the behavior of SourcesManager is clunky and could easily break

**Comment by segiddins** [comment]
@amorde we're still waiting for someone to propose a concrete API and/or PR an implementation, if you'd like to help :)

**Comment by amorde** [comment]
Would love to! I'm new to Ruby so I'm not the best person to do it, but I'll see what I can do.

**Comment by clarkda** [comment]
Sorry guys! I've been covered up, but I'm working an issue that will likely reveal some pain points, let me fix this, get in a pr and I'll have more to say.

:cake: :cake:

**Comment by amorde** [comment]
An option could be to allow plugins to register themselves as source providers, so that the sources manager will ask all source providers for their sources. 

For example:
    
    Pod::HooksManager::register('cocoapods-repo-svn',:source_providers) do |context|
         # logic to return list of Pod::Source objects
    end
    
    # in the Podfile
    plugin 'cocoapods-repo-svn', {
         :sources => [
              'http://svn.myrepo.com',
          ]
     }

    # somewhere in SourcesManager
    source_providers.each do |provider|
       provider_sources = run_source_provider_hooks
       provider_sources.each do |source|
           sources << source # <-- Pod::Source object
       end
    end

Super rough psuedo code but hopefully you get the idea. Does that sound like a good way to go about it? I'm not an experienced contributor to Cocoapods so I might me thinking of it in the wrong way

**Comment by segiddins** [comment]
I suppose that approach could work -- it would basically allow the plugin to act as a factory for `Pod::Source`s

**Comment by orta** [comment]
Yeah, this seems like a good idea to me :+1:

**Comment by amorde** [comment]
The way I am doing it now is sending a subclass of Pod::Source, which also allows for more flexibility. I'm curious if @clarkda has other ideas

**Comment by clarkda** [comment]
I really love the idea of the plugin being able to `explicitly` provide access to the `source` objects .. as opposed to me only being able to pull spec repos from unsupported providers to the correct place .. and then try to keep up with changes to the core api.

:+1: @amorde 

And wow have things changed in the past few months!

**Comment by segiddins** [comment]
We've done this :)
