### ISSUE TITLE
Build failed with Pods.xcproject generated by 0.36.rc1

### ISSUE THREAD

**Issue by TonnyXu** [CocoaPods/CocoaPods#3191]
## Project setting

- Normal app
- Extension

## Problem

- Build failed on Pods, which reports `UIApplication` is not available in extension

### Detail in `Podfile`

```
# ...
pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v3.4.0'
# ...
```

### Detail of the build error

```
/xxx/Pods/Adjust/Adjust/AIActivityHandler.m:143:26: error: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
    if (![[UIApplication sharedApplication]
                         ^
In module 'UIKit' imported from /xxx/Pods/Target Support Files/Pods-Adjust/Pods-Adjust-prefix.pch:2:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:228:1: note: 'sharedApplication' has been explicitly marked unavailable here
+ (UIApplication *)sharedApplication NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.");
^
/xxx/Pods/Adjust/Adjust/AIActivityHandler.m:151:21: error: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
    [[UIApplication sharedApplication] openURL:deepLinkUrl];
                    ^
In module 'UIKit' imported from /xxx/Pods/Target Support Files/Pods-Adjust/Pods-Adjust-prefix.pch:2:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:228:1: note: 'sharedApplication' has been explicitly marked unavailable here
+ (UIApplication *)sharedApplication NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.");
^
/xxx/Pods/Adjust/Adjust/AIActivityHandler.m:151:40: error: 'openURL:' is unavailable: not available on iOS (App Extension)
    [[UIApplication sharedApplication] openURL:deepLinkUrl];
                                       ^
In module 'UIKit' imported from /xxx/Pods/Target Support Files/Pods-Adjust/Pods-Adjust-prefix.pch:2:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:238:1: note: 'openURL:' has been explicitly marked unavailable here
- (BOOL)openURL:(NSURL*)url NS_EXTENSION_UNAVAILABLE_IOS("");
^
3 errors generated.

```

## Workaround

- Fallback to 0.35, everything will be fine.

**Comment by neonichu** [comment]
To clarify: are you linking the "Adjust" Pod to your extension target? If yes, this is an intentional change, because its usage is apparently unsafe. See #3048

**Comment by TonnyXu** [comment]
No, I’m not. That’s why 0.35 works fine.

**Comment by neonichu** [comment]
Hm, I am unable to reproduce this, only pod targets used by an extension user target get the APPLICATION_EXTENSION_API_ONLY = YES for me. Can you share a more complete Podfile?

**Comment by TonnyXu** [comment]
Here is the almost complete Podfile, I've striped out all the private pods.

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.1'

# ignore all warnings from all pods
inhibit_all_warnings!

link_with 'app'

# development
pod 'Reveal-iOS-SDK', '~> 1.5.0' , :configurations => ['Debug']

# production
pod 'CocoaLumberjack', '~> 1.9.2'
pod 'UI7Kit', :head
pod 'GRMustache', '~> 6.8'
pod 'MBProgressHUD', '~> 0.8'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'Facebook-iOS-SDK', '~> 3.13'
pod 'JSONKit-NoWarning', '~> 1.1'
pod 'Evernote-SDK-iOS', '~> 1.3'
pod 'PocketAPI', '~> 1.0'
pod 'ASIHTTPRequest', '~> 1.8'
pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v3.4.0'

link_with 'app', 'appWidget'
pod 'TMCache', '~> 1.2.3'

post_install do |installer|
    installer.project.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
end

```

**Comment by neonichu** [comment]
Actually, this Podfile does link all Pods against both targets, because the second `link_with` directive will simply override the first one. You should use `target` blocks to segment the Pods so that only the desired ones are link against the app extension target.

**Comment by hashier** [comment]
I'm experience a similar problem with the difference between 0.35 and 0.36 even though I'm using `:target` in my Podfile.

```
target :TCWidget do
    pod 'AFNetworking', '~> 1.3'
...
end
```

and this worked fine with 0.35 and now with 0.36.3 and 0.36.4 I get the before mentioned problem:

> 'sharedApplication' is unavailable: not available on iOS (App Extension)

After upgrading from 0.35 to 0.36 and running `pod install` I saw this on the console:

> Installing AFNetworking 1.3.4 (was 1.3.4)

and the Podfile.lock has this diff:

```
-  AFNetworking: 80c4e0652b08eb34e25b9c0ff3c82556fe5967b4
+  AFNetworking: cf8e418e16f0c9c7e5c3150d019a3c679d015018
```

**Comment by segiddins** [comment]
@hashier the re-installation is to be expected (specs had trailing newlines added a few weeks back). And as the compiler error says, you're not allowed to reference `-[UIApplication sharedApplication]` in any code that's targeting an extension.

**Comment by hashier** [comment]
@segiddins but I didn't change any code, I just upgraded cocoa pods and it doesn't build anymore.

**Comment by segiddins** [comment]
@hashier I understand that, and the new behavior is both correct and expected.

**Comment by hashier** [comment]
@segiddins Could you please explain what exactly changed? I can see that the error is defines in UIApplication.h

> + (UIApplication *)sharedApplication NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.");

but I don't understand what in cocoa pods changed that I can't build the same code with 0.36 but I could with 0.35.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#enhancements-3

**Comment by hashier** [comment]
Yes I found this as well while looking at #3048 and I understand that the problem that before it was possible to link to APIs that shouldn't be used in Extensions but what I didn't understand how it was possible before without error at all since the NS_EXTENSION_UNAVAILABLE_IOS is defined in the UIApplication.h header so this didn't change BUT I found it now.

For everyone finding this thread some time later the information that I was missing (and wasn't obvious to me) in the CHANGELOG from 0.36 the following changed. The Pod Widget Targets Build Settings has changed the property `APPLICATION_EXTENSION_API_ONLY` to YES

**Comment by RuiAAPeres** [comment]
@segiddins I am also interested in a workaround for this. cc @hashier

**Comment by hashier** [comment]
@RuiAAPeres I always do what I already pondered upon in my last post.
After every `pod install` I select the pod-afnetworking target and change the `APPLICATION_EXTENSION_API_ONLY` back to `NO`. It's a bit annoying but right now the only way how to work around it without upgrading to `AFNetworking 2`.

**Comment by RuiAAPeres** [comment]
@hashier yeah I am going with that as well.

**Comment by gitizenme** [comment]
:+1: for the workaround until this is fixed.

**Comment by FreudGit** [comment]
Hi, thanks for the workaround.  Any plan to solve this?

**Comment by neonichu** [comment]
I don't see anything that can be solved here. It's highly fragile to set `APPLICATION_EXTENSION_API_ONLY` to `NO` as things will break if you actually call any of those APIs.

**Comment by hashier** [comment]
Would it be possible to have a flag in the Podfile to be able to set APPLICATION_EXTENSION_API_ONLY
For specified pods?

**Comment by neonichu** [comment]
I don't think that makes sense, you can change it in a post-install hook already: https://guides.cocoapods.org/syntax/podfile.html#post_install

**Comment by ArtSabintsev** [comment]
@neonichu can you give a code sample on how to set the `APPLICATION_EXTENSION_API_ONLY` to `NO` in a post-install hook?

Working through this issue as we speak.

**Comment by ArtSabintsev** [comment]
Would it be:

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end

**Comment by ArtSabintsev** [comment]
Yup, that works!

**Comment by hashier** [comment]
And how would it look like only for AFNetworking?
I don't want to turn it off for other pods. As mentioned before it's not a good think todo in the first place.

**Comment by neonichu** [comment]
you can check `target.name`

**Comment by ArtSabintsev** [comment]
@hashier here's some sample code that worked for me:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    case target.name
    when 'AFNetworking', 'FastImageCache', 'SVProgressHUD'
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end
```

**Comment by hashier** [comment]
Works like a charm @ArtSabintsev 

For everyone who needs to find out the `target.name`s, use that snipped:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
```

**Comment by ArtSabintsev** [comment]
Great to hear!
