### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by pmuvva** [CocoaPods/CocoaPods#3192]
Hi,

I included  pod "Brightcove-Player-SDK" in iOsclient.xcodeproj. After building then I got three ".a" files(libPods-Brightcove-Player-SDK.a,libPods.a and libLivePass3.a) and Pods-Brightcove-Player-SDK.build (directory).

If I want to integrate  libLivePass3.a with another project, In that scenario Shall I include rest of three (Pods-Brightcove-Player-SDK.build,libPods-Brightcove-Player-SDK.a,libPods.a)?

In the new project I included only libLivePass3.a and created "Podfile" which has pod "Brightcove-Player-SDK", but I am getting below error:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BCOVCatalogService", referenced from:
      objc-class-ref in BCOvPlayer.o
  "_OBJC_CLASS_$_BCOVPlayerSDKManager", referenced from:
      objc-class-ref in BCOvPlayer.o
  "_kBCOVPlaybackSessionErrorDomain", referenced from:
      -[BCOvMoviePlayerStreamerProxy playbackController:playbackSession:didReceiveLifecycleEvent:] in libLivePass3.a(BCOvMoviePlayerStreamerProxy.o)
  "_kBCOVPlaybackSessionLifecycleEventEnd", referenced from:
      -[BCOvMoviePlayerStreamerProxy playbackController:playbackSession:didReceiveLifecycleEvent:] in libLivePass3.a(BCOvMoviePlayerStreamerProxy.o)
  "_kBCOVPlaybackSessionLifecycleEventFail", referenced from:
      -[BCOvMoviePlayerStreamerProxy playbackController:playbackSession:didReceiveLifecycleEvent:] in 

Please guide me how to package static library?

**Comment by kylef** [comment]
@pmuvva If you are looking to package a pod up for distribution, please take a look and use the [cocoapods packager](https://github.com/CocoaPods/cocoapods-packager#cocoapods-packager) plugin.

**Comment by pmuvva** [comment]
Thanks for your reply. 
I am new to the Cocoa Pods. I am not getting how to use Pod Package?
I have two options, 1. compile the code in command line and add the pod package 
(xcodebuild -workspace iOSClient.xcworkspace -scheme "iOSClient" -configuration $(XCODE_CONFIGURATION) -arch arm64 -sdk iphoneos$(SDK_VER) build RUN_CLANG_STATIC_ANALYZER=YES )
2. After getting binaries then I can make Package 

Please guide me how to do in both the options.

**Comment by neonichu** [comment]
You need to create a Pod for your library, following <http://guides.cocoapods.org/making/making-a-cocoapod.html>. Once that is done, packaging is done via `pod package your.podspec`.
