### ISSUE TITLE
Lint to prevent dynamic libraries and frameworks from passing with iOS 7

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#3193]
Ref #1993 

We shouldn't allow a pod to have dynamic libraries or frameworks and target iOS less than 8

**Comment by krzyzanowskim** [comment]
why is it so ? shouldn't deployment target set to 7.1 be enough ? I found that it's not allowed now for podspecs.

"Simply put, if you write a Swift app today and submit it to the App Store this Fall when iOS 8 and OS X Yosemite are released, you can trust that your app will work well into the future. In fact, you can target back to OS X Mavericks or iOS 7 with that same app." via https://developer.apple.com/swift/blog/

**Comment by neonichu** [comment]
See Xcode's output when using dynamic libs:

> ld: warning: embedded dylibs/frameworks only run on iOS 8 or later.

**Comment by krzyzanowskim** [comment]
But it's ok when installed manually using subproject. I have a framework with target to 7.1, and project with target to 8.1, and everything looks good.

**Comment by krzyzanowskim** [comment]
check the project https://dl.dropboxusercontent.com/u/224308/testtest.zip

**Comment by neonichu** [comment]
It shows the same warning. You will not be able to submit like this to the App Store.

**Comment by krzyzanowskim** [comment]
oh crap, this warning is really hidden. Now I don't know what should I thing about statement about Compatibility ;-( https://developer.apple.com/swift/blog/?id=2

**Comment by neonichu** [comment]
Yah, that's why we made it explicit :) The compatibility statement still applies if you directly include the Swift files in the project.

**Comment by CalQL8ed-K-OS** [comment]
i think i can take this issue on, `lib/cocoapods/command/spec/lint.rb` seems like the file to change, ¿sound right?

**Comment by segiddins** [comment]
@CalQL8ed-K-OS I believe @neonichu has already started the work in https://github.com/CocoaPods/CocoaPods/issues/3207

**Comment by CalQL8ed-K-OS** [comment]
got it, ¿was there a way for me to tell?
¿any easy issues you'd suggest me tackling?

*- Xavi*

**Comment by neonichu** [comment]
@CalQL8ed-K-OS often, there should be a linked PR if someone is already doing it.

**Comment by CalQL8ed-K-OS** [comment]
okay, it's a little bit difficult to grok that in a quick scan of the issue, ¿maybe we should use the _Assignee_ feature?
