### ISSUE TITLE
0.36 RC1 is too restrictive about transitively included static libs

### ISSUE THREAD

**Issue by ashfurrow** [CocoaPods/CocoaPods#3194]
Using Swift pods requires `use_frameworks!`, which is fine. But doing that means including pods that have dependencies that include static libs (ARAnalytics is a good example) breaks everything:

```
[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/ash/bin/eidolon/Pods/HockeySDK/Vendor/CrashReporter.framework and /Users/ash/bin/eidolon/Pods/Mixpanel/Mixpanel/libMPCategoryHelpers.a)
```

The error message could be more clear that this is broke and not just a warning. 

I'll include an example shortly.

**Comment by ashfurrow** [comment]
On [this branch](https://github.com/artsy/eidolon/tree/pods-failure) of Eidolon, I'm getting the failure:

```
[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/ash/bin/eidolon/Pods/HockeySDK/Vendor/CrashReporter.framework and /Users/ash/bin/eidolon/Pods/Mixpanel/Mixpanel/libMPCategoryHelpers.a)
```

**Comment by neonichu** [comment]
Original issue: #2926

I think we should change the check to only reject static binaries which are linked directly to the user target, because the original reasoning applies there. The other issue of reexporting symbols (see #3106) is even relevant for direct dependencies, so the check is insufficient in that case anyway.

**Comment by cipriancaba** [comment]
We have the same problem with pods that include static libs and failing to install with the message above

**Comment by ashfurrow** [comment]
@neonichu Can you elaborate on the original reasoning? I'm still not clear why this error was added between Beta 2 and RC 1 – what purpose does it serve?

**Comment by neonichu** [comment]
@ashfurrow So if a vendoring Pod contains no source files, the vendored library/framework gets linked directly to the user target. If that Pod is used as a dependency by some other Pod, you'll get unresolved symbols at link time of that Pod's framework target. As we know up front that this cannot work, the error message was supposed to make it clearer (guess that failed :)). This case worked with classic CP, because a static library is never linked.

The original issue predates even Beta 1, I think, it was added now because we got around implementing this.

**Comment by ashfurrow** [comment]
I see, so this doesn't really have anything to do with CocoaPods' adoption of frameworks at all, then? 

In any case, I'm happy to help troubleshoot or test new fixes on Eidolon. Just let me know! :snowman:

**Comment by neonichu** [comment]
@ashfurrow oh yes, it does - this case was never a problem pre-frameworks, because the static library never gets linked - all the symbol resolution happens when the user target is linked.

**Comment by neonichu** [comment]
@ashfurrow BTW, if you can think of a message that makes clearer what actually happens, that would be :ok_hand:

**Comment by cipriancaba** [comment]
We use Cocoapods for splitting our app into different modules.. However, one of this modules uses a static library libSomething.a 
We used cocoapods with Swift and linked the library in the podspec with s.libraries = 'Something' which would add the symbols to the target.. I am not sure this error should happen in this case.. 

```
s.vendored_libraries = 'lib/libSomething.a'
s.libraries = 'Something'
```

**Comment by neonichu** [comment]
@cipriancaba does that Pod include source files as well?  Is it a dependency of another Pod?

**Comment by Fl0p** [comment]
:+1: 
Same for me
```target has transitive dependencies that include static binaries```
This may happen even with .framework pod
for example:
```target has transitive dependencies that include static binaries: (/Work/xcode_projects/MyTube/Pods/AdColony/AdColony.framework)```
But AdColony.framework has a same spec like any other framework pod in project

why this pod with error ?

**Comment by segiddins** [comment]
@Fl0p `AdColony.framework` probably doesn't contain a dynamic library but is rather a 'fake' framework

**Comment by Fl0p** [comment]
@segiddins 

in spec :
```
{
  "name": "AdColony",
  "version": "2.5.0",
...
  "source": {
    "git": "https://github.com/AdColony/AdColony-iOS-SDK.git",
    "tag": "v2.5.0"
  },
  "public_header_files": "AdColony.framework/**/*.h",
  "vendored_frameworks": "AdColony.framework",
  "preserve_paths": "AdColony.framework",
 ...
```

And here https://github.com/AdColony/AdColony-iOS-SDK
It looks like any other framework in my project for example HockeySDK
and HockeySDK works perfect for me.

but same HockeySDK not works for @ashfurrow

**Comment by segiddins** [comment]
Again @Fl0p, whether it says `framework` or not has _no_ bearing on whether it's a dynamic or static binary.

**Comment by Fl0p** [comment]
@segiddins 

Hmm.. but why same Pods/HockeySDK/Vendor/CrashReporter.framework works for me fine and don't works for @ashfurrow at the same time ?

@ashfurrow which version of HockeySDK are you using ?

for me   - HockeySDK (3.6.2)
SPEC CHECKSUMS:
  HockeySDK: bfd1f5ac75938b07499c4ac12932244b72a2e70b

**Comment by Fl0p** [comment]
After some experiments:

Pod1 with dependency to Pod2 which contain a 'fake' framework static lib 
plus podfile use_frameworks! 
Throw this error.

But at the same time i can include Pod2 directly into the podfile without Pod1

So dependency manager fail with dependencies

**Comment by cipriancaba** [comment]
@neonichu The pod includes source files (swift mostly, but also some Objective C).. The pod is a standalone module we use in our main app as dependency.. The source files contain swift, objective C.. It also contains a resource bundle..

It used to work ok, because of the **Other linker flags** that was added by cocoapods to the pod target in the main app: 
```
-l"Something"
```

**Comment by jshier** [comment]
This change also breaks the integration of the Fabric pod, since it uses fake frameworks as well.

**Comment by neonichu** [comment]
@cipriancaba Thanks, this should also work fine once we change the logic for this check.

**Comment by segiddins** [comment]
I think we could actually change this to just check if it's transitively required by more than one pod target, instead of just one. How does that sound, @neonichu ?

**Comment by pietbrauer** [comment]
Did someone try this issue with releasing a pod instead of installing one? Because installing one works like a charm for us, but releasing a pod with a `fake framework` dependency throws the error mentioned by @ashfurrow: `[!] The 'Pods' target has transitive dependencies that include static binaries: (/private/var/folders/vl/3mvpqpp92nd1fvt8rwbmhk2jfcflft/T/CocoaPods/Lint/Pods/INFOnlineLibrary/INFOnlineLibrary.framework)`

**Comment by neonichu** [comment]
You can lint with `--allow-libraries` as a workaround. But the error shouldn't happen, indeed.

**Comment by shawnbuso** [comment]
I'm still seeing this issue with 0.36.4 - is this expected or should it be resolved as of that version?

**Comment by mfclarke** [comment]
@shawnbuso seeing it here too, but --use-libraries resolves the issue for us

**Comment by ohwutup** [comment]
seeing this with 0.37.1

**Comment by SlaunchaMan** [comment]
Using 0.37.2, I get this trying to add the `Google/Analytics` pod:

```
[!] The 'Pods-MyTarget’ target has transitive dependencies that include static binaries: (/path/to/myapp/Pods/Google/Libraries/libGGLAnalytics.a, /path/to/myapp/Pods/Google/Libraries/libGGLCore.a, /path/to/myapp/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a, /path/to/myapp/Pods/GoogleNetworkingUtilities/Libraries/libGTMSessionFetcher_full.a, /path/to/myapp/Pods/GoogleNetworkingUtilities/Libraries/libGTMSessionFetcher_core.a, /path/to/myapp/Pods/GoogleSymbolUtilities/Libraries/libGSDK_Overload.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_iPhone.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_core.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_UIFont+LineHeight.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_SystemVersion.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_StringEncoding.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_RoundedRectPath.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_Regex.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_NSStringXML.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_NSStringHTML.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_NSScannerJSON.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_NSDictionary+URLArguments.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_KVO.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_GTMURLBuilder.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_DebugUtils.a, /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTM_AddressBook.a, and /path/to/myapp/Pods/GoogleUtilities/Libraries/libGTMStackTrace.a)
```

**Comment by ammoqq** [comment]
same issue here as SlaunchaMan

**Comment by spacedsweden** [comment]
Same issue here with pos that has depencies on vendored_frameworks

**Comment by AnthonyMDev** [comment]
So in the end, there is no way to make a static library, like crash lyrics, work when it is a dependency for multiple targets. This error isn't showing up because I'm configuring something wrong, right? It's just not doable

**Comment by shepting** [comment]
@AnthonyMDev This would suggest you are right: https://github.com/CocoaPods/CocoaPods/issues/3841

**Comment by goktugyil** [comment]
Still getting this:

/usr/bin/pod install

Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using ARAnalytics (3.6.2)
Installing Alamofire (1.2.3)
Using Crashlytics (3.0.11)
Using FLEX (2.0.3)
Using Fabric (1.2.8)
Using FlurrySDK (6.6.0)
Using GoogleAnalytics (3.12.0)
Using Mixpanel (2.8.2)
Using SVWebViewController (1.0)
Using SZTextView (1.2.1)
[!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/gok2/Documents/Arcane/Pods/FlurrySDK/Flurry/libFlurry_6.6.0.a and /Users/gok2/Documents/Arcane/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a)

**Comment by Legoless** [comment]
I'm still getting this error, as of now with ARAnalytics and Google Analytics.

**Comment by miguelcma** [comment]
Me too :\ version `0.39.0.beta.4` here

**Comment by medjessy** [comment]
+1

**Comment by aspyct** [comment]
Hey there,

We were having the same kind of issues here with a podspec having Google Analytics as dependency, and were actually unable to `pod lib lint` because of a dependency to Google Analytics. And therefore we were unable to push our custom pod.

It seems that adding the flag `--use-libraries` to the `pod lib lint` or `pod spec lint` and finally `pod repo push` allows cocoapod to validate correctly.

**Comment by olivierlesnicki** [comment]
+1

**Comment by orta** [comment]
I'm locking this as its looking like we're getting +1s without people reading the issue. In simple, if a library is not dynamic and you're trying to use it with frameworks you can use it, but you cannot use it as a dependency of something else via CocoaPods.

https://github.com/CocoaPods/CocoaPods/issues/3841#issuecomment-123803940
