### ISSUE TITLE
pod tries to checkout version branch instead of branch configured in Podfile

### ISSUE THREAD

**Issue by champo** [CocoaPods/CocoaPods#3196]
:rainbow:
I have several internal libraries configured to use the latest version from a branch:

```
pod 'ios-commons/UIColor+Hex', :git => 'ssh://.../ios-commons/', :branch => 'development'
```

Until 0.36.0.beta.2 this worked as expected: it simply brought the copy from that branch. However after updating to 0.36.0.rc1 it tries to checkout a '0.1.0-dev' branch. The version configured in ios-commons.podspec is 0.1.0-dev.
Relevant output from `pod install --verbose` (redacted repo url):
```
-> Installing ios-commons 0.1.0-dev (was 0.1.0-dev)
 > Git download
 > Git download
     $ /usr/bin/git clone ssh://.../ios-commons /Users/juanpablocivile/Documents/umewin/ios/Pods/ios-commons --single-branch --depth 1 --branch 0.1.0-dev
```

Tried to reproduce this in a clean checkout of the project and it didn't happen. Seems to only happen when the repo had a previous `pod install` using beta 2. Running `pod update` seems to fix the checkout.

**Comment by segiddins** [comment]
Can you please share steps to reproduce the issue?

**Comment by segiddins** [comment]
If this is indeed only an update issue coming from a beta, I'm not too worried. Feel free to reopen if you can point us in the direction of reproduction steps.
