### ISSUE TITLE
0.36.0.rc.1 - Incorrect Deprecated Error

### ISSUE THREAD

**Issue by JRG-Developer** [CocoaPods/CocoaPods#3197]
Using CocoaPods version `0.36.0.rc.1` (latest available via `gem install cocoapods --pre` at this time), on `pod spec lint` I incorrectly get this warning:

    BetterBaseControllers (1.0.2)
        - ERROR | a spec cannot be deprecated in favor of itself

However, the pod is not deprecated in favor of itself. The pod spec looks like this:

    Pod::Spec.new do |s|
      s.platform     = :ios
      s.ios.deployment_target = "7.0"
      s.name         = "BetterBaseControllers"
      s.version      = "1.0.2"
      s.summary      = "This library is deprecated. Use BetterBaseClasses instead."
      s.deprecated_in_favor_of = 'BetterBaseClasses'
      s.homepage     = "https://github.com/JRG-Developer/BetterBaseControllers"
      s.license      = { :type => "MIT", :file => "LICENSE" }
      s.author       = { "Joshua Greene" => "jrg.developer@gmail.com" }
      s.source   	   = { :git => "https://github.com/JRG-Developer/BetterBaseControllers.git", :tag => "#{s.version}"}
      s.framework    = "UIKit"
      s.requires_arc = true
      s.source_files = "BetterBaseControllers/*.{h,m}"
    end

This pod spec lints correctly using CocoaPods version 0.35.0.

**Comment by segiddins** [comment]
@JRG-Developer you're totally right, I just pushed a fix
