### ISSUE TITLE
Possibility to specify code signing identity

### ISSUE THREAD

**Issue by akashivskyy** [CocoaPods/CocoaPods#3198]
As a developer I should be able to specify (e.g. in `Podfile`) which identity should be used to code sign the framework dependencies.

As of today, CocoaPods sets the code signing identity to `iOS Developer`, which prevents CI builds from archiving and distributing the projects (as only distribution certificate is available).

The problem lies in [xcodeproj/lib/constants.rb:158](https://github.com/CocoaPods/Xcodeproj/blob/5db3688d756038531d861bb19f32eaecc2ed52e0/lib/xcodeproj/constants.rb#L192), where `CODE_SIGN_IDENTITY` is hardcoded to `iPhone Developer`.

This is related to #3156.

**Comment by segiddins** [comment]
You can already kinda do this via a post install hook, but I'm still not convinced it's necessary

**Comment by neonichu** [comment]
@segiddins Yah, shouldn't the actual signing be done by the frameworks script?

**Comment by piemonte** [comment]
@akashivskyy +1

**Comment by segiddins** [comment]
Yeah, the signing is done by the embed frameworks script, so this is unnecessary. But maybe we should forcibly disable signing on all CocoaPods targets from within Xcode?

**Comment by neonichu** [comment]
@segiddins I don't think that will work, IIRC Xcode errors when building a framework for iOS with code signing disabled

**Comment by segiddins** [comment]
Ah darn. In that case, I don't think there's anything for us to do.

**Comment by neonichu** [comment]
I agree, for people hitting special cases where they need this, a post-install hook should be totally fine.

**Comment by piemonte** [comment]
thanks for considering.

it's true, it is a special case for the folks that need it. although having to add a post install hook would require you to fork that repository and modify it. which was what I hoped to avoid.

**Comment by akashivskyy** [comment]
@piemonte You can add a post-install hook in your `Podfile`. Here's my current solution:

``rb
post_install do |installer|

  puts 'Setting appropriate code signing identities'
  installer.pods_project.targets.each { |target|
    {
      'iPhone Developer' => ['Development'],
      'iPhone Distribution' => ['Release', 'Staging', 'Production'],
    }.each { |value, configs|
      target.set_build_setting('CODE_SIGN_IDENTITY[sdk=iphoneos*]', value, configs)
	}
  }

end


class Xcodeproj::Project::Object::PBXNativeTarget

  def set_build_setting setting, value, config = nil
    unless config.nil?
      if config.kind_of?(Xcodeproj::Project::Object::XCBuildConfiguration)
        config.build_settings[setting] = value
      elsif config.kind_of?(String)
        build_configurations
          .select { |config_obj| config_obj.name == config }
          .each { |config| set_build_setting(setting, value, config) }
      elsif config.kind_of?(Array)
        config.each { |config| set_build_setting(setting, value, config) }
      else
        raise 'Unsupported configuration type: ' + config.class.inspect
      end
    else
      set_build_setting(setting, value, build_configurations)
    end
  end

end
```

**Comment by piemonte** [comment]
ah, i see now. @akashivskyy you're awesome. thanks for the help everyone. ✌️

**Comment by rkeniger** [comment]
@akashivskyy Thanks so much for this. I've been tearing my hair out trying to get Jenkins to build a Swift project with Frameworks. Your solution is the only one that actually worked.

**Comment by benjaminhorner** [comment]
I have tried all the above and more but I still get errors…

   PhaseScriptExecution Embed\ Pods\ Frameworks /Users/benjaminhorner/Library/Developer/Xcode/DerivedData/Qanda-gvgfupphoqlhunadtbdlptoavvpr/Build/Intermediates/Qanda.build/Debug-iphoneos/Qanda.build/Script-2D6395156474D5B46ABEF1EB.sh
    cd "/Users/benjaminhorner/Web projects/Qanda"
    /bin/sh -c /Users/benjaminhorner/Library/Developer/Xcode/DerivedData/Qanda-gvgfupphoqlhunadtbdlptoavvpr/Build/Intermediates/Qanda.build/Debug-iphoneos/Qanda.build/Script-2D6395156474D5B46ABEF1EB.sh

mkdir -p /Users/benjaminhorner/Library/Developer/Xcode/DerivedData/Qanda-gvgfupphoqlhunadtbdlptoavvpr/Build/Products/Debug-iphoneos/Qanda.app/Frameworks
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/benjaminhorner/Library/Developer/Xcode/DerivedData/Qanda-gvgfupphoqlhunadtbdlptoavvpr/Build/Products/Debug-iphoneos/AMScrollingNavbar.framework" "/Users/benjaminhorner/Library/Developer/Xcode/DerivedData/Qanda-gvgfupphoqlhunadtbdlptoavvpr/Build/Products/Debug-iphoneos/Qanda.app/Frameworks"
building file list ... done
AMScrollingNavbar.framework/
AMScrollingNavbar.framework/AMScrollingNavbar
AMScrollingNavbar.framework/Info.plist
AMScrollingNavbar.framework/_CodeSignature/CodeResources

sent 238029 bytes  received 92 bytes  476242.00 bytes/sec
total size is 237628  speedup is 1.00
Code Signing /Users/benjaminhorner/Library/Developer/Xcode/DerivedData/Qanda-gvgfupphoqlhunadtbdlptoavvpr/Build/Products/Debug-iphoneos/Qanda.app/Frameworks/AMScrollingNavbar.framework with Identity iPhone Distribution: Qanda (VHAFZMKSW2)
/usr/bin/codesign --force --sign 8B814641243DA5795251023A9709F86475CA6372 --preserve-metadata=identifier,entitlements "/Users/benjaminhorner/Library/Developer/Xcode/DerivedData/Qanda-gvgfupphoqlhunadtbdlptoavvpr/Build/Products/Debug-iphoneos/Qanda.app/Frameworks/AMScrollingNavbar.framework"
8B814641243DA5795251023A9709F86475CA6372: no identity found
Command /bin/sh failed with exit code 1

**Comment by fcy** [comment]
I've this problem and read through all the different solutions I found. There is one thing that I don't understand, based on the conversation here disabling code signing for Frameworks shouldn't work.

> But maybe we should forcibly disable signing on all CocoaPods targets from within Xcode?
...
>I don't think that will work, IIRC Xcode errors when building a framework for iOS with code signing disabled

If that is the case why the following post install hook fixes the problem? Am I missing something?

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
```

**Comment by neonichu** [comment]
Could be that Xcode's build step got more lenient in the meantime and accepts building frameworks for the device without code-signing.

**Comment by ikonst** [comment]
For one, IB Designables could not be loaded from unsigned frameworks.
