### ISSUE TITLE
0.36 RC1 and use_frameworks! renaming issue

### ISSUE THREAD

**Issue by Fl0p** [CocoaPods/CocoaPods#3199]
after using ``` use_frameworks! ``` all pods renamed

```
#import <Parse-iOS-SDK/Parse.h>
#import <Google-API-Client/GTLService.h>
```

stop working and required to rename

```
#import <Parse/Parse.h>
#import <Google_API_Client/GTLService.h>
```

**Comment by neonichu** [comment]
This is not a bug, it is a required change, because module names can only be C99 identifiers.
