### ISSUE TITLE
Unable to specify --sources option when doing "pod repo push MY_PRIVATE_REPO"

### ISSUE THREAD

**Issue by matteonovelli** [CocoaPods/CocoaPods#3204]
I have a private spec which depends on another private spec. When I try to push it into my own private repo it occurs this error: 

```
[!] Unable to find a specification for `MY_SPEC_2 (= 0.1.0)` depended upon by `MY_SPEC_1`
```

If I validate the pod spec using the --sources option everything works fine... but --sources option is not available to use with "pod repo push" command

**Comment by segiddins** [comment]
`pod repo push` uses all of the sources available locally.

**Comment by segiddins** [comment]
What command are you using to push? Can you verify that `MY_SPEC_2` is available in a cloned specs repository? You really haven't given us enough info to go on to reproduce the issue :/

**Comment by matteonovelli** [comment]
I have discovered that the problem was with the prefix_header_file attribute on my podspec file and I solved it.
Thanks!
