### ISSUE TITLE
Support for dependencies hosted in private podspecs

### ISSUE THREAD

**Issue by stkhapugin** [CocoaPods/CocoaPods#3205]
I want to create a private pod that depends on other private pods. Is there an equivalent of `source` directive for podspecs? Or maybe a workaround that allows listing private podspecs as dependencies? 

Some context: 

We're trying to modularise our app with cocoapods. Due to privacy reasons we have to use private podspecs repo. All is set up fine and in Podfile I can write:

```ruby 

source 'our-private-podspec'
pod 'MyPrivatePod', :head

```

but I can't find any equivalent of `source` for dependencies in [podspec syntax reference](http://guides.cocoapods.org/syntax/podspec.html#dependency).

**Comment by orta** [comment]
You would have a private Podspec repo hosting your specs ( Example [Specs](https://github.com/artsy/Specs), Example [Podfile](https://github.com/artsy/eigen/blob/master/Podfile#L1) ). There is no need to define where a Podspec's dependency can be found as that's the job of the Podfile, just that it exists.

**Comment by stkhapugin** [comment]
Thanks for a blazing fast reply. This works exactly like you described.
