### ISSUE TITLE
Linker error  with 0.36.0.rc.1

### ISSUE THREAD

**Issue by mglidden** [CocoaPods/CocoaPods#3208]
In 0.35.0, everything works as expected. In 0.36.0.rc.1, we get duplicate linker symbols:
```
duplicate symbol _OBJC_CLASS_$_FBURLConnection in:
    /Users/mglidden/Library/Developer/Xcode/DerivedData/Yelp-erlxilvsctgklcdbkxeutlxkvidj/Build/Products/Debug-iphonesimulator/libPods-Yelp-Facebook-iOS-SDK.a(FBURLConnection.o)
    /Users/mglidden/Library/Developer/Xcode/DerivedData/Yelp-erlxilvsctgklcdbkxeutlxkvidj/Build/Products/Debug-iphonesimulator/libPods-YelpTests-Facebook-iOS-SDK.a(FBURLConnection.o)
```

The relevant part of our podfile looks like this:
```
target :Yelp, :exclusive => true do
  install_common_pods()
end

target :YelpTests, :exclusive => true do
  install_common_pods()
  install_testing_pods()
end

target :YelpOCUnitTests, :exclusive => true do
  install_testing_pods()
end
```

Yelp is the main app, YelpOCUnitTests is a bundle (that depends on Yelp) with our test cases, and YelpTests it's own application that compiles the files from both Yelp and YelpOCUnitTests. 

There are > 2000 linker errors – one for every symbol in our libraries. They only appear when compiling YelpTests (Yelp and YelpOCUnitTests work as expected). YelpTests doesn't have any dependencies on Yelp, but, for some reason, Yelp's libraries are getting linked in.

When I look at the YelpTests linker command from 0.35.0, only Pods-YelpTests-* libraries are getting linked. In 0.36.0.rc.1, there are also a bunch of Pods-Yelp-* libraries. 

I compared Pods.xcodeproj between 0.35 and 0.36, but nothing stood out – everything appears to have the same dependencies before & after.

Let me know if there's anything else I should investigate. If it would help, I can try to make a small test project later this week.

**Comment by segiddins** [comment]
@neonichu haven't we seen this before?

**Comment by neonichu** [comment]
@segiddins I am not aware.

@mglidden Could you take a look at the XCConfigs in *Pods/Target Support Files*? Those should be the culprits for linking in the additional libraries.

**Comment by mglidden** [comment]
I figured it out – YPDebug (which imports Pods-Yelp.debug.xcconfig) was set as the fallback config file: 
![screenshot 2015-03-03 09 49 55](https://cloud.githubusercontent.com/assets/1319930/6468558/b56a3b4a-c18a-11e4-85ef-d233e6bc2e1c.png)

Since 0.36 now has $(inherited) in OTHER_LDFLAGS, this caused YelpTests to try and link the Yelp libraries.

Thanks for the help!
