### ISSUE TITLE
Removing the last pod dependency from a target breaks the target build configuration

### ISSUE THREAD

**Issue by akitchen** [CocoaPods/CocoaPods#3209]
Given I have been using CocoaPods successfully on my project

```
target 'MyApp' do
  pod 'AFNetworking'
end

#####

$ pod install
```

When I remove the last pod dependency from my app target

```
target 'MyApp' do
#  pod 'AFNetworking'
end

#####

$ pod install
```

Then my project fails to build due to a broken generated project configuration

* I have to manually remove the reference to the xcconfigs
* I have to delete the Check Pods Manifest and Copy Pods Resources build phases, and remove libPods-myApp from the linker phase manually.

In this scenario, I would expect CocoaPods to clean up the project enough so that one doesn't need to intervene manually before the application target can be built again.

**Comment by neonichu** [comment]
In the meantime, check out <https://github.com/kylef/cocoapods-deintegrate>

**Comment by kylef** [comment]
As @neonichu, for now use the [cocoapods-deintegrate](https://github.com/kylef/cocoapods-deintegrate) plugin. I'm going to close this issue since it's already tracked by #2471.
