### ISSUE TITLE
Load xcconfig file inpodspec rather than key-value pairs. 

### ISSUE THREAD

**Issue by brianpartridge** [CocoaPods/CocoaPods#3211]
I have several libraries that I'm trying to package up with podspecs, each of which references an xcconfig file in a git submodule, which contains common build settings, warnings, etc.  As I create specs for these libraries, I'd like a simple way to pull in the shared settings from the xcconfig, rather than converting the contents to a hash and putting it in the spec.xcconfig property. Is there a good way to do this?

I'd be fine with specifying the values in each podspec if there were differences, but given that the values are the same, it seems wrong to reproduce it everywhere and have to update it in each location when a value is added or updated. Am I missing something obvious? I like that you can specify a pch file, it would be great to do the same with an xcconfig.

**Comment by segiddins** [comment]
You can read in the config using ruby, since the Podspec is just a ruby DSL.

**Comment by neonichu** [comment]
If the config just exists for the specification's sake, you could also make it a shared ruby file.

**Comment by brianpartridge** [comment]
@segiddens I was looking into doing this yesterday, but it wasn't clear to me where that file would exit at 'pod install' time. Does :submodules seems to cause it to be cloned but I didn't see where it landed. 

@neonichu the file exists for use in other projects as an xcconfig. I considered making a gem that parses the file and could then be used in the podspec, but then each podspec would need to 'require' the gem.

**Comment by neonichu** [comment]
@brianpartridge By default, files which aren't used by any file pattern are deleted, you probably need to use `preserve_paths` (<http://guides.cocoapods.org/syntax/podspec.html#preserve_paths>).

**Comment by brianpartridge** [comment]
@neonichu Perfect! `preserve_paths` let's me keep the file around and then I can easily load it into my podspec's `xcconfig` field.  Thanks so much for the help.

**Comment by brianpartridge** [comment]
If anyone else is interested, this is what I did:

    xcconfig_path = "Frameworks/XCConfig/strict.xcconfig"
    s.preserve_path = xcconfig_path
    s.xcconfig = File.open(File.join(Dir.pwd, "Pods", s.name, xcconfig_path)) { |file| Hash[file.each_line.map { |line| line.split("=", 2) }] }
