### ISSUE TITLE
Dependency not resolved for head

### ISSUE THREAD

**Issue by muratgurel** [CocoaPods/CocoaPods#3212]
Cocoapods Version: 0.35.0 (but it also happens in the pre-release version)

Podfile:

```
pod 'CocoaLumberjack', :head
```

I get this error:

```
[!] Unable to satisfy the following requirements:
- `CocoaLumberjack (HEAD)` required by `Podfile`
```

This is because the latest version of CocoaLumberjack is pre-release and cocoapods wants me to explicitly state the pre-release version. However, I would like to be able to get the head of the pod.

Is this the expected behaviour? Is there another way to get the head of a pod?

**Comment by segiddins** [comment]
Probably a bug, I'll investigate. Thanks for the report!
