### ISSUE TITLE
Linker alerts when using frameworks

### ISSUE THREAD

**Issue by nachocual** [CocoaPods/CocoaPods#3213]
Using the following Podfile on a new project:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
use_frameworks!

pod 'Sparkle'
```

After running `pod install`, I get the following alert in Xcode twice (one for the Pods project and one for my new project):

>ld: warning Directory not found for option '-F/Users/ignacio.bergmann/Library/Developer/Xcode/DerivedData/Test-cqhdjvmvsuddwebdlcwyxsdpwona/Build/Products/Debug/Pods'

This is with Cocoapods 0.36.0.rc.1.

It seems to happen when you enable the usage of frameworks and all your dependencies are packaged in that way, so this folder never gets created, probably because no new ad hoc frameworks are built. If I add `AFNetworking` as a dependency for example (which requires a framework for it to be built by Cocoapods) the warning goes away. This might be wrong as I only have a basic understanding of how Cocoapods works.

**Comment by mrackwitz** [comment]
You're right, I can confirm this issue. We'll have to fix that. Thank you for reporting. :+1:
