### ISSUE TITLE
0.36.0.rc.1 Using nibs with "use_frameworks!" in pods

### ISSUE THREAD

**Issue by sergdort** [CocoaPods/CocoaPods#3214]
Don't know is it an issue, but to be able to use nibs from pod that I have added to my project with swift I had to add this resource manually like this http://stackoverflow.com/a/18072167 , may be this should  be automatically? Or I have to specify another bundle in the pod that I made?

**Comment by neonichu** [comment]
Resources for frameworks are bundled inside the framework, so using `bundleForClass:` instead of `mainBundle` is required to load them, see #3088
