### ISSUE TITLE
pod trunk register sends no mail

### ISSUE THREAD

**Issue by K4stor** [CocoaPods/CocoaPods#3216]
Hi 

I want to register with pod trunk register.
My mail Adress is manuel.binna@9elements.com

Can you help me somehow
Thanks

**Comment by kylef** [comment]
This isn't an issue in trunk but a problem with your mail provider. Your SMTP server responds with a 550 indicating your account has been disabled.

![screen shot 2015-03-03 at 14 46 19](https://cloud.githubusercontent.com/assets/44164/6464715/14eac804-c1b4-11e4-89ed-8bf300e99197.png)

Causing the emails to bounce each time:

![screen shot 2015-03-03 at 14 47 36](https://cloud.githubusercontent.com/assets/44164/6464740/46f9db6e-c1b4-11e4-9548-5800cffebf42.png)

**Comment by K4stor** [comment]
Well the email address was disabled at 18, Feb. But it is reenabled and I can send mails to it. I tried it with different accounts.
Is it possible that your server somehow rememberers this address as black-listed ?

**Comment by kylef** [comment]
As discussed on email, I've cleared the bounce please try again.
