### ISSUE TITLE
rsync fails - no such file.... when using xcodebuild command and swift frameworks

### ISSUE THREAD

**Issue by nick-fueled** [CocoaPods/CocoaPods#3220]
Have a project with Alamofire swift framework added via Cocoapods (using 0.36 RC1)

When creating an archive using the xcodebuild command, get the following error

Error we get is:
**building file list ... rsync: link_stat "/Users/N/Documents/ProjectX/build/Pods/Alamofire.framework" failed: No such file or directory (2)**

The xcodebuild command that I use is:
**xcodebuild -workspace ProjectX.xcworkspace  -scheme ProjectX-Snapshot archive -archivePath /Users/N/Documents/ProjectX/build/Moodelizer-Snapshot.xcarchive CONFIGURATION_BUILD_DIR=/Users/N/Documents/ProjectX/build CODE_SIGN_IDENTITY="Company Name Here" -destination generic/platform=iOS**

Note - seems to work when archiving through xcode itself.  We use the xcodebuild command with our CI server.

Looks like the framework files are there, but just not in the Pods subdirectory but rather in /Users/N/Documents/ProjectX/build/.

Using 6.1.1 Xcode command line tools.

We've never than this problem with 0.35 and objective-C pods.

Thanks Cocoapods Team!

**Comment by segiddins** [comment]
This is probably related to setting a custom  `CONFIGURATION_BUILD_DIR`

**Comment by neonichu** [comment]
Yep, this is a duplicated of #3063, open issue is tracked by #3095

**Comment by macu** [comment]
Seeing the same rsync output/failure in Jenkins CI for Alamofire.framework, running Xcode integration plugin 1.4.8, CocoaPods 0.36.4. Building through Xcode itself is fine. Does #3095 actually track this issue?

**Comment by macu** [comment]
I noticed that Alamofire.framework does not exist at "/Users/N/Documents/ProjectX/build/Pods/Alamofire.framework" but it does exist at "/Users/N/Documents/ProjectX/build/Alamofire.framework" along with other *.framework files.

For me the solution was to modify the script referenced in the "Embed Pods Frameworks" step, which in my workspace is located at "${SRCROOT}/../Pods/Target Support Files/Pods/Pods-frameworks.sh"

I removed the "/Pods" part from the source path in the `install_framework` function:

	install_framework()
	{
	  # Remove the /Pods/ part...
	  # local source="${BUILT_PRODUCTS_DIR}/Pods/$1"
	  local source="${BUILT_PRODUCTS_DIR}/$1"
	  local destination="${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}"
