### ISSUE TITLE
Multiple subspecs headers installed in the same public headers directory.

### ISSUE THREAD

**Issue by brianpartridge** [CocoaPods/CocoaPods#3221]
I have a spec like this:
```
Pod::Spec.new do |s|
  s.name         = "Cube"
  
  s.default_subspec = "Core"
  
  s.subspec "Core" do |ss|
    ss.source_files = "CubeCore"
    ss.private_header_files = "CubeCore/*_Internal.h", "CubeCore/*_Private.h"
    ss.prefix_header_file = "Other/CubeCore-Prefix.pch"
  end
  
  s.subspec "TestingHelpers" do |ss|
    ss.dependency "Cube/Core"
    ss.framework = "XCTest"
    ss.source_files = "Frameworks/CubeCoreTesting/CubeCoreTesting"
    ss.prefix_header_file = "Frameworks/CubeCoreTesting/Other/CubeCoreTesting-Prefix.pch"
  end

end
```

When I run `pod install` all the public headers are installed in `Pods/Headers/Public/CubeCore`, when I'd really like the Core subspec's headers in `CubeCore` and the TestingHelpers subspec's header in `CubeCoreTesting`.  I've looked at `header_dir` and `header_mappings_dir`, but it doesn't seem to do what I want.  Is there a way that I can configure this?  

My end goal is to be able to use the following lines in the consuming project:
```
    #import <CubeCore/CubeCore.h>
    #import <CubeCoreTesting/CubeCoreTesting.h>
```

**Comment by neonichu** [comment]
This won't be possible, especially not considering frameworks.

**Comment by brianpartridge** [comment]
Can you elaborate on that? None of these are actual frameworks (just an unfortunate folder name), or are you referring to adding Framework support?

It seems like I can accomplish it by breaking out the TestingHelpers subspec into it's own podspec, but I was hoping to avoid that.

**Comment by neonichu** [comment]
Sorry, I meant when integrating with `use_frameworks!` - one specification will correspond to one framework in that case. The only option I see for this is indeed breaking it up into two Pod specifications.

**Comment by segiddins** [comment]
@brianpartridge to accomplish what you want, you'd need to use separate podspecs.

**Comment by brianpartridge** [comment]
Will do, thanks for the help.
