### ISSUE TITLE
🌈 Question to be possible to automate `pod trunk push` with CI service like travisCI

### ISSUE THREAD

**Issue by yoheimuta** [CocoaPods/CocoaPods#3224]
🌈 (I read [CONTRIBUTING.md](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md))

I want to automate release flow of pod using travisCI, because [only a manual operation to be left of my ios release workflow](https://github.com/yoheimuta/mtburn-ios-sdk-demoapp#only-manual-operation-to-be-required) is `pod trunk push`.

The command of `pod trunk register` requires to verify e-mail and inadvertently has the sessoin in CI working machine (in not my own machine). The former disturbs automation and the latter compromises security.

I googled to solve this issue, and found same questions not to be solved on [stackoverflow](http://stackoverflow.com/questions/26382002/publishing-to-cocoapods-from-travis). And I couldn't find any same issues on this repository.

So I'm asking you to have a solution to automation with CI, and if it doesn't exist, I hope to add a solution to issues(task lists) of future version-up.

Thank you for developing nice services.

**Comment by segiddins** [comment]
We could probably allow override the trunk email and token via environment variables?

**Comment by orta** [comment]
I think that seems totally reasonable :+1:

**Comment by yoheimuta** [comment]
Thank you for quick response !

I can confirm to fetch token throught `pod trunk me --verbose`.
I'm going to try this soon.

**Comment by yoheimuta** [comment]
> I'm going to try this soon.

I tried and confirmed it. 

- Replaced some info with `***` manually.

```
$ bundle exec pod trunk me
[!] You need to register a session first.
...
$ COCOAPODS_TRUNK_TOKEN=*** bundle exec pod trunk me
...
  - Name:     ***
  - Email:    ***
  - Since:    September 11th, 2014 11:27
  - Pods:
    - ***
  - Sessions:
    - March 4th, 15:30           -     July 16th, 18:50. IP: 118.238.203.205 Description: Mac-158()
```

**Comment by marcosgriselli** [comment]
@loicgriffie I just tackled this issue on a [blog post](https://mar.codes/2018-12-10/Set-up-library-releases-from-CI). 

You'll need to generate an access token for trunk and set it as a secret variable on Bitrise under the `COCOAPODS_TRUNK_TOKEN` key. Here's a post by @kylef on how to generate the access token: https://fuller.li/posts/automated-cocoapods-releases-with-ci/
