### ISSUE TITLE
Allow override iOS 8+ framework requirement for trunk

### ISSUE THREAD

**Issue by jeffh** [CocoaPods/CocoaPods#3225]
From: https://github.com/Quick/Nimble/pull/102

Pushing a swift project that has a minimum deployment version of iOS less than 8 fails.

```
$ pod trunk push Nimble.podspec
 -> Nimble (0.3.1)
    - ERROR | [iOS] Swift support uses dynamic frameworks and is therefore only supported on iOS > 8.
    - NOTE  |  ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
```

While Xcode produces this warning, it is perfectly fine running dynamic frameworks on older simulators. I'm fine with an opt-in flag since using iOS frameworks for production code less than iOS 8 results in a rejection. The primary value is to run swift testing-only frameworks on older deployment targets.

**Comment by neonichu** [comment]
I am wondering if we should handle this special case via PRs against the Specs repo? Once we have a flag, there is no way to ensure that people aren't pushing their non-testing Pods to trunk as well with iOS 7 deployment targets. Another possibility would be allowing this for Pods which require the XCTest framework automatically.

**Comment by kylef** [comment]
We could potentially have a rule where this iOS 8 check in this case isn't used when validating a pod that has `framework = 'XCTest'`.

**Comment by orta** [comment]
^ This is a nice touch @kylef

**Comment by carloscrono** [comment]
This worked for me:

` s.platform     = :ios, "9.0"`

Added this on podspec file
