### ISSUE TITLE
with !use_frameworks missed Resources.bundle from pods

### ISSUE THREAD

**Issue by Fl0p** [CocoaPods/CocoaPods#3226]
By default PodResources.bundle copied to  ``` maiBundle.app/ ```
when project switched to  ``` use_frameworks! ``` resources copied into
 ``` mainBundle.app/Frameworks/new_pod_name/ ```

A lot of existing pods looks for theirs resources in main bundle for example 
https://github.com/kevinlawler/NSDate-TimeAgo/blob/master/NSDate%2BTimeAgo.m#L9-12

So ``` My.app/NSDateTimeAgo.bundle/ ``` became
``` My.app/Frameworks/NSDate_TimeAgo.framework/NSDateTimeAgo.bundle/ ```

Kinda solution: just add symlink to a new resource bundle

**Comment by neonichu** [comment]
Those Pods will need to be updated to use `bundleForClass:` instead of `mainBundle`, so that they work as both framework and static library.

**Comment by Fl0p** [comment]
@neonichu agreed
Any hot fix for smooth migration (symlink) ?
