### ISSUE TITLE
`pod outdated` can not work if some latest pods need higher version of iOS.

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3228]
I run `pod outdated` to find some outdated pod, and try to update them.
But I got a error:
```
➜ pod outdated
Analyzing dependencies
[!] The platform of the target `Pods` (iOS 6.0) is not compatible with `FLEX (2.0.1)` which has a minimum requirement of iOS 7.0.
➜ 
```
My requirement of iOS is 6.0, and I am using the FLEX(1.1.1).
I want to find the highest version to fit my app, rather than the latest version. And now, It also prevent to list other outdated pods. :(

**Comment by segiddins** [comment]
Yeah, that checking in the resolver needs to not happen when running `outdated`. I'd really appreciate a PR helping to fix this!

**Comment by segiddins** [comment]
Fwiw, the platform checking should probably be moved out to the analyzer, and imho should constitute a warning instead of an error.

**Comment by segiddins** [comment]
This behavior has since been changed, and if you want to override, you'll need to manually specify a higher platform for your target in the Podfile.
