### ISSUE TITLE
`pod search` can show the min system version

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3229]
```
➜  pod search FLEX
-> FLEX (2.0.1)
   A set of in-app debugging and exploration tools for iOS
   pod 'FLEX', '~> 2.0.1'
   - Homepage: https://github.com/Flipboard/FLEX
   - Source:   .....
   - Versions:  2.0.1, 2.0.0, 1.1.1, 1.1.0, 1.0.1, 1.0.0 [master]
```
My app is lowest system version is 6.0, but the `2.0.1`, `2.0.0` is `>=7.0` and the `1.1.1` is `>=6.0`.
So I will use the `1.1.1`. And I must search every podspec to find it.

 I hope the require system version can be shown.

**Comment by segiddins** [comment]
That would need to be shown for every version, which I think is impractical.

**Comment by orta** [comment]
This could be added to the `--full` command,

```
   - Versions: (>=7) 2.0.1, 2.0.0  (>=6) 1.1.1, 1.1.0, 1.0.1, 1.0.0 [master]
```

This it could get complex & ugly though.

**Comment by segiddins** [comment]
It _could_ be added, but keep in mind there are both iOS and OS X to think about, and those requirements may not change monotonically. I think you'd be best off just looking at the raw specs if you need to see _every_ aspect of them.

**Comment by orta** [comment]
Yeah, I'm going with @segiddins here. Closing. Thanks for the idea @Whirlwind
