### ISSUE TITLE
cannot use s.library = 'libz'

### ISSUE THREAD

**Issue by masterkain** [CocoaPods/CocoaPods#3232]
I'm trying to link against `libz.dylib`.

Podfile:

`s.library = 'libz'`

During linting:

```
   - ERROR | [iOS] [libraries] Libraries should omit the `lib` prefix  (`libz`)
```

`libz.dylib` will trigger another error.

**Comment by kylef** [comment]
As the error message stated, remove the `lib` prefix.

```ruby
spec.library = 'z'
```

**Comment by erduoniba** [comment]
@kylef 
is work for me, thanks
