### ISSUE TITLE
[Feature/PR Proposal] Strip unused localized assets.

### ISSUE THREAD

**Issue by dtorres** [CocoaPods/CocoaPods#3235]
There are a lot of pods (UI mostly, but there are others) that provide localizations of their bundled images and texts. It can take a significant size of the final app to include localized resources that won't end up being used. 

I would like to contribute this feature to remove those assets as part of the pods installation.

I don't know if this is significant enough to be included in the core project or doing a plugin on my own would be more fitting. 

 Appreciated any thoughts or opinions you might have on this.

**Comment by segiddins** [comment]
We have an open issue already describing this (https://github.com/CocoaPods/CocoaPods/issues/2381), and any contributions towards its implementation would be much appreciated!
