### ISSUE TITLE
What is the usage of other linker flag?

### ISSUE THREAD

**Issue by onmyway133** [CocoaPods/CocoaPods#3239]
I see that Pods project assembles all sub Pod projects into `libPods-MyApp.a`, and this binary is linked in `Link Binary With Library`.

What is the usage of declaring other linker flag in Pods.xcconfig?

`
OTHER_LDFLAGS = -ObjC -l"Pods-MyApp-AFNetworking" -l"Pods-MyApp-KVOController"
`

**Comment by segiddins** [comment]
It causes the actual pods to be linked into your application.
