### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sindhus** [CocoaPods/CocoaPods#3242]
Hi!

I ran a `gem install cocoapods --user-install` but looks like gem can't find it.
How do I start fixing this? 
Thanks!

➜  Induction git:(master) gem which cocoapods
ERROR:  Can't find ruby library file or shared library cocoapods
➜  Induction git:(master) pod install
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'cocoapods' (>= 0) among 97 total gem(s) (Gem::LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
        from /Users/sindhus/.gem/ruby/2.0.0/bin//pod:22:in `<main>'

**Comment by kylef** [comment]
When you use `--user-install`, RubyGems will install any gems into the gem user dir. You will need to add it's path to your `PATH`.

See the [RubyGems FAQ](http://guides.rubygems.org/faqs/#user-install) for more information.
