### ISSUE TITLE
Only one gem is being installed

### ISSUE THREAD

**Issue by dankiiing** [CocoaPods/CocoaPods#3243]
Hi,

I have added my account unto the sudoers file and was able to initiate the install of cocoapods but only one gem was installed. Here is the result of the install 

I ran > 
      sudo gem install cocoapods
Result >
     Successfully installed cocoapods-0.35.0
     Parsing documentation for cocoapods-0.35.0
     1 gem installed.

That's it.

previously the error was I didn't have .gem in my PATH of which I later added. I'm confused how do I fix this issue

**Comment by kylef** [comment]
You haven't mentioned and error or what issue your having?

**Comment by dankiiing** [comment]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:422:in `open': No such file or directory - /Users/username/.cocoapods/repos (Errno::ENOENT)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:422:in `foreach'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:422:in `children'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:63:in `all'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:130:in `repo_information'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface/error_report.rb:34:in `report'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:58:in `report_error'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:300:in `handle_exception'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:274:in `rescue in run'
    from /Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:264:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
    from /usr/bin/pod:23:in `load'
    from /usr/bin/pod:23:in `<main>'

**Comment by kylef** [comment]
This was fixed by and is in CocoaPods 0.36.

Please search existing issues / try the latest version before filing issues. There are at least three other tickets for this issue: #3162 #3126 #3223 and it's fixed by https://github.com/CocoaPods/CocoaPods/commit/0994612ebb65ad1aa221f384235e4702560df7d2.

As a workaround for CocoaPods 0.35, you can run the following:

```bash
$ pod setup
```

**Comment by dankiiing** [comment]
sorry about that, thank you, the problem is solved now
