### ISSUE TITLE
Swift unit tests broken after the migration to cocoapods 0.36.RC.1

### ISSUE THREAD

**Issue by craigzour** [CocoaPods/CocoaPods#3244]
Hi,

I just started to use the latest version of the library. My unit test target was perfectly working before and now that I have set it up with the 0.36, some of my unit tests are not passing anymore and some others are generating crashes.

For example: "fatal error: NSArray element failed to match the Swift Array Element type" or "fatal error: unexpectedly found nil while unwrapping an Optional value"

Is there something to know around that about the migration between the version 0.33 and the "latest" 0.36 ?

Thank you for your help !

**Comment by craigzour** [comment]
The issue is still present with the latest version 0.36.0. Do you guys have an idea about what is going on ?

**Comment by neonichu** [comment]
Really hard to say without any further info. Can you share a failing test? Did you actually opt-in to using frameworks or are you still using bridging headers?

**Comment by craigzour** [comment]
Well I can but I do not think it is gonna help because this is pretty basic stuff.

For instance: a simple comparison between two objects with a XCTEquals.

This is why I did not provide examples. I was just wondering if there was something obvious that I did not know about the migration process between the two versions.

Reminder: This is perfectly working with the 0.33.0.

**Comment by craigzour** [comment]
Hi,

I have been able to locate one specific issue that seems to be the root cause of a lot of my unit tests. The isKindOfClass or isMemberOfClass methods are not correctly working anymore when used from Swift unit tests.

Is it a clue for you ?

Everything is working with the previous 0.33.0.

**Comment by segiddins** [comment]
@craigzour that will happen when you link your pods to both the app target and the test target.

**Comment by craigzour** [comment]
@segiddins Oh ok. So what can I do If I want to include pods for the test target ? The compilation is failing if I am not including them.

**Comment by craigzour** [comment]
When I remove Pods inclusion from Test target I am not able to compile and run the tests. I get an error about one of my libraries which is not found.

What is the "official" solution about that ?

**Comment by craigzour** [comment]
I found one way of fixing my issue but it is really ugly.

target "Project" do
pod 'EDSemver', '0.3.0'
end

target "Project-Test" do
pod 'Useless-Pod' //pod that I am not gonna use at all.
end

Is it the only possible way of being able to move on for me ?

**Comment by craigzour** [comment]
Hi,

I definitely did not find any other solution than the one I described you yesterday. I cannot believe that this is the only existing solution. Do you know what could I do avoid importing a library that I will not use ?

**Comment by kylef** [comment]
Something like the above workaround would be required for now. There is a much larger long-term plan to introduce a keyword to integrate the headers of a target into the test targets:

```ruby
target 'MacApp'
  pod 'AFNetworking'

  target 'MacAppTests' do
     use_headers_of_parent
  end
end
```

Refactoring the Podfile (#840) along with (#1249). I'm going to close this issue as this behaviour is already known and planned to change with #840. For now I'd suggest such workarounds.

**Comment by craigzour** [comment]
Perfect ! Thank you !
