### ISSUE TITLE
Undefined symbols for architecture arm64 for a Cocoapod I own

### ISSUE THREAD

**Issue by ArtSabintsev** [CocoaPods/CocoaPods#3245]
Hey guys,

I'm trying to integrate `IDmeSDK`, a pod I own, into a Swift project of mine. I'm getting the following error when I build against the simulator and the device:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IDmeSDK", referenced from:
      __TMaCSo7IDmeSDK in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

However, when I do a manual *drag-n-drop* integration, I don't have any issues. 

**Here's the relevant info:**
- Cocoapods: 0.36b2
- Xcode: 6.2 GM
- Deployment Target: iOS 8.0
- Active/Valid Architectures: armv7, armv7s, arm64
- Other linker flags:
![screen shot 2015-03-10 at 11 42 31 am](https://cloud.githubusercontent.com/assets/854860/6578454/940934a2-c71a-11e4-89e3-0eb3218cd11d.png)

**Podfile**
```ruby
platform :ios, '8.0'
use_frameworks!

xcodeproj 'ID.me.xcodeproj'
pod 'IDmeSDK'
pod 'PrintlnMagic'
pod 'Siren'
pod 'UIColor-ColorWithHexAndAlpha'
```

Any and all help would be greatly appreciated!

EDIT: Added full Podfile, as first couple lines were missing.

**Comment by orta** [comment]
For context:
https://github.com/CocoaPods/Specs/blob/master/Specs/IDmeSDK/1.0.4/IDmeSDK.podspec.json

Does the embedded framework have a slice for 64bit? You can confirm with [lipo](http://stackoverflow.com/questions/18992840/how-to-check-if-a-static-library-is-built-for-64-bit)

**Comment by ArtSabintsev** [comment]
Hey @orta 

Running 
```sh
xcrun -sdk iphoneos lipo -info IDmeSDK.framework/IDmeSDK 
``` 
yields
```sh
Architectures in the fat file: IDmeSDK.framework/IDmeSDK are: i386 x86_64 armv7 arm64 
```

**Comment by ArtSabintsev** [comment]
Keep in mind, the library builds/runs properly if I add it in manually. I'm only seeing this issue when I add it via Cocoapods.

**Comment by pzearfoss** [comment]
When you ran lipo on that framework, is that one that's in the project you're dealing with?

**Comment by ArtSabintsev** [comment]
Yup!

**Comment by pzearfoss** [comment]
I haven't done much with frameworks specifically.  Just for sanity have you created a project with just your framework to see if that's the issue, or does yours rely on those others?

**Comment by ArtSabintsev** [comment]
This was a brand new project, but I'll do it again, for the sake of my own sanity. Thanks for the help! Will keep you posted.

**Comment by kylef** [comment]
@ArtSabintsev Would you be able to show us your Podfile.lock (so we can see the versions of the pods that are used).

**Comment by ArtSabintsev** [comment]
Sure, @kylef. Here you go!

```
PODS:
  - IDmeSDK (1.0.4)
  - PrintlnMagic (1.2.0)
  - Siren (0.3.3)
  - UIColor-ColorWithHexAndAlpha (1.2.0)

DEPENDENCIES:
  - IDmeSDK
  - PrintlnMagic
  - Siren
  - UIColor-ColorWithHexAndAlpha

SPEC CHECKSUMS:
  IDmeSDK: 60cdd502994eb0457750cf72f2016ea19016f3e1
  PrintlnMagic: 5f6aa008b70c953eab2dde09f63057858179629a
  Siren: d2f8d7874daf206c52007c9307e6836bd22d2e5c
  UIColor-ColorWithHexAndAlpha: ed237e455f0b036b986e031a2ce649324cabe6dd

COCOAPODS: 0.36.0.rc.1

```

**Comment by neonichu** [comment]
Looks to me as if it is a duplicate of #3106 - I believe using `public_headers` instead of `source_files` for IDmeSDK should fix it for the time being.

**Comment by ArtSabintsev** [comment]
So, should I change the variable I use to `public_headers` or wait until you modify the logic for the `should_build?` boolean as you mentioned in #3106?

**Comment by neonichu** [comment]
Would be nice to verify that using `public_headers` indeed fixes your problem, also would be immediate - so depends also on how urgent the issue is for you.

**Comment by ArtSabintsev** [comment]
I'll verify it tonight. I'll be in touch. Thanks, Boris!

**Comment by ArtSabintsev** [comment]
Sadly, that doesn't fix the problem. 

Side note: I noticed that when I `import IDmeSDK`, but don't have any code referencing the library, everything compiles without a problem. However, if I add in a few lines of code that references the library, hit build/run, that's when I get the compilation issue, irrespective of it being a 32-bit sim, 64-bit sim, or device. 

This same behavior is exhibited for both `public_headers` and `sources_files`.

**Comment by neonichu** [comment]
It seems to work fine for me with `public_headers` only. Can you `rm -rf Pods` and also clean out Derived Data - there will be a leftover "IDmeSDK.framework" created by CP from previous integrations.

**Comment by ArtSabintsev** [comment]
Really? Can you:
- `import `IDmeSDK` into any file, 
- Add the following lines of code:

 ```swift
let sdk = IDmeSDK.sharedInstance()
sdk.startWithClientID("x", andClientSecret: "y")
```

- Clean/Build/Run

Does that work for you? I did that in a brand new project after changing to `public_headers` and updating Cocoapods to 0.36 GM, and I still received that error.

**Comment by neonichu** [comment]
Yep, that compiles and links fine for me.

**Comment by neonichu** [comment]
BTW, regardless of the linking issue, this will break at runtime at the moment because "IDmeSDK.framework" is dynamic and we do not embed frameworks right now (see #1993).

**Comment by ArtSabintsev** [comment]
Linking issue still persists for me, but if it's going to break at runtime, then this point is moot. I'll make a comment on the README of my project stating this issue, and I'll subscribe to #1993 and wait for your team to add support down the road.

Thanks for all your help! I TRULY appreciate it!

**Comment by ArtSabintsev** [comment]
I guess I may have to go back to building Static Libraries....sigh :\
