### ISSUE TITLE
[ -n $XCASSET_FILES ] breaks when a project has multiple *.xcassets file.

### ISSUE THREAD

**Issue by sodastsai** [CocoaPods/CocoaPods#3247]
got
```
<SOURCE_ROOT>/Pods/Target Support Files/Pods/Pods-resources.sh: line 177: [: 'ImageAssets.xcassets': binary operator expected
```
while executing the ```Pods-resources.sh``` generated by Cocoapods 0.36.0.

I think it's due to my project have 2 local podspec which contains *.xcassets respectably, so the ```$XCASSET_FILES``` is equal to ```'a.xcassets' 'b.xcassets'```.
The space inside it breaks the ```-n``` test.

Should be fixed to ```[ -n "$XCASSET_FILES" ]```

**Comment by segiddins** [comment]
Please send a pull request!

**Comment by sodastsai** [comment]
oops, sorry, I have no idea about how to fix this in code. (I'm not a ruby developer)

**Comment by sodastsai** [comment]
ok, never mind, I found it and fixed. :smile:

**Comment by orta** [comment]
Nice work @sodastsai :+1:
