### ISSUE TITLE
`podspec :name=>xxx` not apply `libraries` and `frameworks` in the podspec

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3249]
I work for a framework, and I write a Podfile:
```
podspec :name=>'MyFramework.podspec'
```

Then, I write a MyFramework.podspec:

```
  s.dependency 'iOS-QR-Code-Encoder'
  s.libraries = 'sqlite3'
  s.frameworks = 'ImageIO'
```

After `pod install`, I got the `Pods.debug.xcconfig`:

```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Public"  "${PODS_ROOT}/Headers/Public/iOS-QR-Code-Encoder" /usr/include/libxml2
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public"  -isystem "${PODS_ROOT}/Headers/Public/iOS-QR-Code-Encoder"
OTHER_LDFLAGS = -ObjC  -l"Pods-iOS-QR-Code-Encoder" -l"xml2"  -l"z.1"
OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)
PODS_ROOT = ${SRCROOT}/Pods
```

The dependency `iOS-QR-Code-Encoder` is right, but the `libraries` and `frameworks` are wrong. I hope they are in the `OTHER_CFLAGS`.

**Comment by segiddins** [comment]
Using `podspec` in your Podfile only pulls in the dependencies declared in your podspec, so everything is working as intended.

**Comment by orta** [comment]
Docs: http://guides.cocoapods.org/syntax/podfile.html#podspec

**Comment by Whirlwind** [comment]
I think it is good way if the `podspec` apply the `libraries` and `framework`. So I will not add the dependencies in the Xcode.

**Comment by Whirlwind** [comment]
@segiddins @orta Can you add the `libraries` and `frameworks` support in the `podspec`?

**Comment by orta** [comment]
Hrm, this is an odd one, in order to do this we'd have to actually change the user's project settings, which is a CocoaPods-no-no. The `podspec` is _only_ supposed to ensure that your pod dependencies are set up fine through CocoaPods, not that your library code is set up right.

So in retrospect, I don't think we will do this.

**Comment by Whirlwind** [comment]
I don't think it is an odd one. :(
I think it will not change the user's project settings, just add the link flags to the `Pods.xcconfig`.

If I will develop a pod target and demo target. I just write a podspec , then use the `podspec` to add all dependencies and system framework, so I will not add any dependency to the Xcode.

Now, I will write a podspec and add the dependency to the Xcode again, I think it is bad way!

**Comment by segiddins** [comment]
In that case, you should use the 'pod' DSL directive passing in a 'path' instead of using 'podspec '. The two methods do different things 

-Samuel E. Giddins
segiddins.me

**Comment by handywang** [comment]
> In that case, you should use the 'pod' DSL directive passing in a 'path' instead of using 'podspec '. The two methods do different things
> 
> -Samuel E. Giddins
> segiddins.me
> 
> > On Mar 15, 2015, at 7:45 PM, Whirlwind [notifications@github.com](mailto:notifications@github.com) wrote:
> > I don't think it is an odd one. :(
> > I think it will not change the user's project settings, just add the link flags to the Pods.xcconfig.
> > If I will develop a pod target and demo target. I just write a podspec , then use the podspec to add all dependencies and system framework, so I will not add any dependency to the Xcode.
> > Now, I will write a podspec and add the dependency to the Xcode again, I think it is bad way!
> > —
> > Reply to this email directly or view it on GitHub.

Right, Every things have their borned responsibility.
