### ISSUE TITLE
Icons.xcassets     Failure Reason: No such file or directory

### ISSUE THREAD

**Issue by mohamedadly** [CocoaPods/CocoaPods#3251]
After updating to 0.36 version, the script for resources fails.

how can i fix this or how to downgrade?

**Comment by neonichu** [comment]
We like to keep the issue tracker about actual bugs in CocoaPods, please read our contribution guidelines on how to report one so that it can be acted upon: <https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#bug-reports>

Usage questions, like how to downgrade, should be asked on StackOverflow.

**Comment by peeinears** [comment]
I got this too in 0.36.0 when using a pod with xcassets. This does appear to be an "actual bug" in CocoaPods. [It looks like it was addressed 2 days ago](https://github.com/CocoaPods/CocoaPods/commit/9cd9ce4152c4e7f89aee122a4b5879ccc5c02e82), but is not yet in the latest CocoaPods gem.

Make that change above to your Pods-resources.sh file to fix this temporarily.

I should mention though that after doing that I'm now running into other issues, but I think they're related to #1546.

**Comment by mohamedadly** [comment]
Yes, modifying the resources script will temporarily solve the issue.

Anyway i downgraded to 0.35.0 until this problem is solved completely.

**Comment by gantulgats** [comment]
+1 i'm some problem here. How to downgrade ?

**Comment by orta** [comment]
```
gem uninstall cocoapods
[sudo] gem install cocoapods --version 0.35.2
``` 
I believe

**Comment by gantulgats** [comment]
@orta Thank. it works

**Comment by iphonebytes** [comment]
Is this fixed i am still getting same error.
