### ISSUE TITLE
Getting error in setting up Cocoa Pods and install update for Ruby

### ISSUE THREAD

**Issue by shekharece** [CocoaPods/CocoaPods#3252]
I am trying to setup cocoapods to my iOS application But when I go for command:

sudo gem update --system
I get error : Latest version currently installed. Aborting.

When I go to next step for cocoapods:

sudo gem install cocoapods

I get error on Mac OS 10.8.5 :
ERROR:  Error installing cocoapods:
cocoapods-trunk requires Ruby version >= 2.0.0.

I tried same on Mac OS 10.9.4 and getting error :
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
      Unable to download data from https://rubygems.org/ - Errno::ECONNREFUSED: Connection refused - connect(2) (https://rubygems.org/latest_specs.4.8.gz)​

**Comment by shekharece** [comment]
When trying to install ruby and rvm, I am getting error : 

RVM sourcing line not found for Zsh, rerun this command with '--auto-dotfiles' flag to fix it. 

and warning : 
* WARNING: You have '~/.profile' file,
 you might want to load it, to do that add the following line to '/Users/sharmas/.bash_profile': source ~/.profile 

and error for ruby: 

No binary rubies available for: osx/10.8/x86_64/ruby-2.0.0-p598

**Comment by orta** [comment]
We follow the support path of the latest Xcode releases, and so support the default rubies on `10.9`, and `10.10`. 
I'm afraid you'll have to learn how to use RVM / Rbenv / Chruby in order to get that ruby version, and this is an issue tracker for CocoaPods, not a public forum like StackOverflow for getting help.

**Comment by shekharece** [comment]
But it is not allowing me to update ruby version also
