### ISSUE TITLE
Error while trying to install Bugsnag

### ISSUE THREAD

**Issue by eminbugrasaral** [CocoaPods/CocoaPods#3255]
Hello, I am using my Mac with multiple users and I had several permission errors with brew recently but I fixed them. Anyways, today I wanted to update my pods by simply calling "pod install" but I got a prompt on the shell while installing Bugsnag:

![screen shot 2015-03-11 at 8 27 15 pm](https://cloud.githubusercontent.com/assets/2864828/6611692/05a414e8-c82d-11e4-818f-6afef6ab1a36.png)

I also tried saying yes but it didn't work. I saw this prompt for the first time. I couldn't fix this issue. I tried to remove and install Cocoapods again ("sudo gem install cocoapods && sudo gem install cocoapods"). I deleted known_hosts. I deleted Cocoapods' master. 

I couldn't fix this problem for hours. Any idea why this is happening?

**Comment by segiddins** [comment]
This looks like a `git` issue to me.

**Comment by orta** [comment]
Yep, this happens to me occasionally, it is github flaking out alas.

**Comment by eminbugrasaral** [comment]
Thanks for the replies.
FYI I re-generated my ssh key for github, and now the problem is gone. 
Peace.
