### ISSUE TITLE
add support for static framework.

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3256]
I develop a static framework, and I want to use CP to manage its dependencies. But I found that the library target should not be added the `Pods.a` dependency and should not copy any resource in the dependencies.

I just use CP to download dependencies and add the header search path.

`OTHER_LDFLAGS` and copy resource shell should not add to the static framework. Is it right?

I hope add a flag to support this case, for example:
```
target :framework, :library=>true do 
   pod 'xxx'
end
```

**Comment by segiddins** [comment]
This is what `cocoapods-packager` or the `--no-integrate` option is used for.
