### ISSUE TITLE
Improved handling of Unicode target names

### ISSUE THREAD

**Issue by Tiger6688** [CocoaPods/CocoaPods#3257]
when I update cocoapods to 0.36.0, 
run pod install in a new project,get such chaotic code
![2015-03-12 8 01 31](https://cloud.githubusercontent.com/assets/8372025/6617331/ad523c72-c8f2-11e4-9ce1-43baa3f66492.png)

**Comment by Tiger6688** [comment]
the appname  is in chaotic code too

**Comment by Tiger6688** [comment]
![2015-03-12 8 18 57](https://cloud.githubusercontent.com/assets/8372025/6617586/0eb4a854-c8f5-11e4-8560-919342bea5d6.png)
the filename in chinese is chotic too!~

**Comment by orta** [comment]
For now I'd recommend switching back to `0.35` and reverting to a previous commit.

**Comment by Tiger6688** [comment]
thanks your reply!

**Comment by neonichu** [comment]
This has been fixed by CocoaPods/Xcodeproj#251
