### ISSUE TITLE
Flatten http source except zip-Archives

### ISSUE THREAD

**Issue by Dajchan** [CocoaPods/CocoaPods#3258]
Why are you flatten all types of Archives except .zip after downloading? Is it possible to prevent the installer from flatten tgz-Archives?

I have a vendored_framework in my podspec and the contents of the *.framework Folder is moved to the pod-root (flattened), obviously this messes up everything

**Comment by neonichu** [comment]
There is `preserver_paths` to change that behaviour: <http://guides.cocoapods.org/syntax/podspec.html#preserve_paths>

**Comment by Dajchan** [comment]
no not realy, this prevents only that the files are removed, but does not change the fact that the paths after unarchiving are wrong 
if have a pod XYZ with a framework XYZ.framework as vendored_framework
after unarchiving i get the following folder structure:

XYZ/XYZ.framework (empty)
XYZ/Headers/..
XYZ/Versions/..

basicaly everything is moved from XYZ.framework to root, and if you look in the code this is done for everything except zip.
https://github.com/CocoaPods/cocoapods-downloader/blob/a5a642e572937eb08097fbf65b30e1e7a3c449e9/lib/cocoapods-downloader/http.rb

**Comment by neonichu** [comment]
I see, the referenced issue #727 explains the rationale.

**Comment by Dajchan** [comment]
ok, thank you!
