### ISSUE TITLE
Could not load keyring

### ISSUE THREAD

**Issue by XBeg9** [CocoaPods/CocoaPods#3262]
After updating to CocoaPods 0.36, I can't pod install anymore. What's that guys?

```bash
pod install
Analyzing dependencies
Pre-downloading: `Keys` from `https://github.com/ashfurrow/empty-podspec.git`
[!] Could not load keyring
```

**Comment by segiddins** [comment]
This belongs over on https://github.com/orta/cocoapods-keys.

**Comment by XBeg9** [comment]
@segiddins that's strange because I don't use it in this project. Ok, everything works from 
```bash
bundle exec pod install
```
