### ISSUE TITLE
Is there a way/method to check if the Pods are installed using the `use_frameworks!` flag?

### ISSUE THREAD

**Issue by MuscleRumble** [CocoaPods/CocoaPods#3265]
I'm interested in a way/method to check if a user has installed his Pods using the new `use_frameworks!` flag at compile-time. Probably a macro (something with `#ifdef`) would be the easiest way. Is there something like that available or is it maybe already planned?

My use case: I want to activate/deactivate IBDesignable for my library, depending on whether `use_frameworks!` is being used or not. I don't really want to force anyone to requiring this new flag, because I would like to support iOS versions below 8.

Thanks!

**Comment by pronebird** [comment]
I concur. The bug related to IBDesignable still exists on the latest Xcode and developers need some clean way to enable this feature for users using frameworks.

**Comment by kylef** [comment]
Apparently IBDesignable are available for static libraries too so this check should not be necessary.

/cc @mrackwitz https://github.com/CocoaPods/blog.cocoapods.org/pull/74

**Comment by MuscleRumble** [comment]
Can't confirm that at all. :confused:

**Comment by pronebird** [comment]
IB throws error during rendering when using static library.

**Comment by MuscleRumble** [comment]
Any update on this? Should we just solve this issue ourselves? E.g. with self-defined macros or multiple branches?

**Comment by segiddins** [comment]
closing due to kyle's comment.

**Comment by pronebird** [comment]
Does Xcode 7 support IBDesignable with static pods?
