### ISSUE TITLE
Pod installation failure on some transitive dependencies

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#3267]
I use `use_frameworks!` and get the following error on `pod install`:

```
[!] The 'Pods-Beer' target has transitive dependencies that include static binaries: 
(/Users/user/Beer/Pods/Parse/Parse.framework and 
/Users/user/Beer/Pods/ParseFacebookUtils/ParseFacebookUtils.framework)
```

Why is that so? Can I disable frameworks for Parse only to workaround that issue? I have other user-facing pods that need frameworks for IBDesinable to work.

**Comment by neonichu** [comment]
See discussion in the original issue #2926

**Comment by sarbogast** [comment]
What is the solution to that then? I don't get it in the referred discussion.

**Comment by pronebird** [comment]
@sarbogast you can't have the same pod linked as framework and static library at the same time. This is what happens here due to cross-dependencies. 

@neonichu 
I vote for `force_frameworks!` to ignore sub-specs and use frameworks even if sub-spec has no idea of their existence. Will this blow up? Otherwise we can pray for next two years that iOS 7 is gone and then maybe we can switch to frameworks by default.

**Comment by neonichu** [comment]
@pronebird This is what already happens, this error is for Pods which include *binaries*.

The eventual solution is for those Pods to ship dynamic instead of static frameworks.

**Comment by sarbogast** [comment]
@pronebird So does that mean I can only wait for Parse to fix their Podspec somehow? Or is there anything I can do to fix that in the meantime?

**Comment by zirinisp** [comment]
I am having the same problem

**Comment by pronebird** [comment]
@sarbogast I don't think we can do anything until vendors switch to dynamic frameworks.

**Comment by mrowles** [comment]
The whole Facebook and Parse thing is a mess atm, ParseFacebookUtils references FacebookSDK.h which doesn't exist anymore as of version Facebook iOS 4.0.1 (it is now FBSDKCoreKit). I tried to go to pods to sort this out, but no luck it seems.

**Comment by andreicrisan** [comment]
@mrowles  have you had any luck making your Facebook iOS 4.0.1 pod to work? I have been struggling with that issue and cannot get the files to work at all. Seems like facebook managed to screw it up...

**Comment by mrowles** [comment]
@andreicrisan Check out this developers issue for more information, but looks to be a fix next release:
https://developers.facebook.com/bugs/362995353893156

**Comment by sergdort** [comment]
@sarbogast  I've fixed this by downloading parse frameworks from https://parse.com/docs/downloads and add them manually

<img width="746" alt="screen shot 2015-08-17 at 6 13 55 pm" src="https://cloud.githubusercontent.com/assets/4622322/9308270/cc275dd6-450b-11e5-9035-b4835aac7e49.png">

**Comment by krzyzanowskim** [comment]
I don;t use dynamics frameworks, yet I have this error.

**Comment by Maheepk** [comment]
Hi @segiddins,

I am using cocoapods 
1.1.0.beta.1 Latest one.

and trying to install

platform :ios, '7.0'

inhibit_all_warnings!

use_frameworks!

pod 'Firebase'
pod 'FirebaseMessaging'
pod 'Reachability'
pod 'AFNetworking'

target 'XXX_Example' do
    pod 'XXX', :path => '../'

    target 'XXX_Tests' do
        inherit! :search_paths

    end
end
[!] The 'Pods-XXX_Example' target has transitive dependencies that include static binaries: (/Users/XXX/Desktop/XXX/XXXSDK/XXX-ios/Example/Pods/FirebaseMessaging/Frameworks/FirebaseMessaging.framework)

Please let me know how can i resolve it?

thanks,

**Comment by sergiofraile** [comment]
@Maheepk I was having the same issue but with CardIO. @cooler333 fix in https://github.com/CocoaPods/CocoaPods/issues/3289 seems to work fine, although I had to place it in the Podfile, not in the podspec, to make it work, but I'm not familiar with the pre_install option (let me know if there's a better way).

**Comment by Maheepk** [comment]
@sergiofraile i followed that. That fixed Dependency error but gives me 
     ld: warning: Auto-Linking supplied '/Users/XXX/Desktop/XXX/XXXSDK/XXX-ios/Example/Pods/FirebaseInstanceID/Frameworks/FirebaseInstanceID.framework/FirebaseInstanceID', framework linker option at /Users/XXX/Desktop/XXX/XXXSDK/XXX-ios/Example/Pods/FirebaseInstanceID/Frameworks/FirebaseInstanceID.framework/FirebaseInstanceID is not a dylib

thanks,

**Comment by Maheepk** [comment]
@sergiofraile 

I am getting /Users/XXX/Desktop/XXX/XXXSDK/XXX-ios/Example/Pods/Headers/Private/Firebase/Firebase.h:1:9: 'FirebaseAnalytics/FirebaseAnalytics.h' file not found

**Comment by Hammad345** [comment]
just add this line into your pod file before "" target 'project name' do ""
inhibit_all_warnings!

its work for me

**Comment by danielReporty** [comment]
Since 1.3.0.beta.2 the workaround is now like this:

pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
