### ISSUE TITLE
ld: library not found for -lPods-Parse after updating to 0.36

### ISSUE THREAD

**Issue by cakl** [CocoaPods/CocoaPods#3274]
```
pod --version
0.36.0

pod install
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.1.4)
Installing FXForms (1.2.12)
Installing OCHamcrest (4.1.1)
Installing OCMockito (1.4.0)
Installing Parse (1.6.4)
Installing SDWebImage (3.7.1)
Generating Pods project
Integrating client project

```

Screenshot of Targets (missing Pods-Parse)
![Targets](https://s3.amazonaws.com/f.cl.ly/items/3q3I0f1b1j1T0K141X1m/Image%202015-03-16%20at%204.19.57%20nachm..png)

Build Error: Apple Mach-O Linker Error (pre-cleaned and pre-deleted derived data)
```
ld: library not found for -lPods-Parse
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Now downgrade cocoapods to 0.35 and install pods in a newly cloned repo
```
sudo gem uninstall cocoapods
Select gem to uninstall:
 1. cocoapods-0.35.0
 2. cocoapods-0.36.0
 3. All versions
> 2
Successfully uninstalled cocoapods-0.36.0

pod --version
0.35.0

pod install
Analyzing dependencies
CocoaPods 0.36.0 is available.
To update use: `gem install cocoapods`
For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.
Downloading dependencies
Installing Bolts (1.1.4)
Installing FXForms (1.2.12)
Installing OCHamcrest (4.1.1)
Installing OCMockito (1.4.0)
Installing Parse (1.6.4)
Installing SDWebImage (3.7.1)
Generating Pods project
Integrating client project
```

Screenshot of Targets (Pods-Parse is **NOT** missing)
![Targets2](https://s3.amazonaws.com/f.cl.ly/items/3z3k0e0g1q2A141V1Y0I/Image%202015-03-16%20at%204.27.35%20nachm..png)

Result: Building without Errors (pre-cleaned and pre-deleted derived data)

Maybe the same issue as in https://github.com/CocoaPods/CocoaPods/issues/3157 but I can only reproduce it for the pod parse. So I think it depends on that pod.

**Comment by segiddins** [comment]
Hm. Linking against `Pods-Parse` should be unecessary in 0.36, since you should be linking directly against the vendored binaries that the Parse pod provides. @neonichu any ideas?

**Comment by neonichu** [comment]
Indeed, the additional pod target is no longer needed. 

I think the issue here is that we do not clean up the dependency of the aggregate target to the no longer existing Parse pod target.

@caki could you please manually delete the "Pod" target before running `pod install` with 0.36 and report back to verify that this is the issue?

**Comment by cakl** [comment]
@neonichu As you can see in my first code block:
```
pod --version
0.36.0

pod install
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.1.4)
Installing FXForms (1.2.12)
Installing OCHamcrest (4.1.1)
Installing OCMockito (1.4.0)
Installing Parse (1.6.4)
Installing SDWebImage (3.7.1)
Generating Pods project
Integrating client project
```
Im calling ```pod install``` in a fresh, new cloned repo without a Pods/ nor a .xcworkspace folder in it. So I don't think theres an aggregate target. Or am I wrong? 

What do you mean with delete the "Pod" target? Do you mean the "Pods" target (first target in xcode target list)?

**Comment by neonichu** [comment]
@cakl Sorry, I got confused by the "updating" in your title to think that you were running `pod install` in an existing project. Disregard what I said in the previous comment.

However, the target not being created is correct for a vendored framework, it still being referenced is the problem.

**Comment by neonichu** [comment]
Hm, I am unable to reproduce this in a fresh project depending on the Parse pod. There's no linking to a non-existing Parse pod target in the XCConfigs or the Pods project.

Is it possible you manually added the `-lPods-Parse` somewhere in the client project? Can you identify where it actually comes from?

**Comment by cakl** [comment]
I don't think that I've added this manually as I installed everything with cocoapods and it worked fine. May I ask where I've to search for that option?

**Comment by neonichu** [comment]
A simple `grep 'Pods-Parse' *.xcodeproj/project.pbxproj` should suffice as a sanity check.

**Comment by cakl** [comment]
```
grep 'Pods-Parse' *.xcodeproj/project.pbxproj
					"-l\"Pods-Parse\"",
					"-l\"Pods-Parse\"",
					"-l\"Pods-Parse\"",
					"-l\"Pods-Parse\"",
```
http://cl.ly/image/1m2n2B3x1x32

**Comment by cakl** [comment]
I removed these other linker flags and the build succeeds now. I'm really sorry, I forgot to check here, but I was really sure that I never added these flags manually (but maybe I'm wrong). Thanks for you help @neonichu.

**Comment by neonichu** [comment]
You probably edited the linker flags in your project while using a previous version of CocoaPods; editing copies the flags from XCConfigs to your target.

**Comment by Enriquecm** [comment]
I had the same problem and, magically, the linker flags changed. I reseted the value and the build succeeds. Thanks for the help!

**Comment by cakl** [comment]
Sorry if I reopen this issue, but as I ```pod update``` parse from 1.6.4 to 1.7.2.1 there is a new build error:
```
ld: framework not found Parse
```

I re-greped the xcodeproj with ```"-l\"Pods-Parse\"",``` and there are not strings found.
Pod version ```pod --version 0.36.4 ```

The Ld Path contains the following "Parse" strings
```
-framework Parse
-lParse
-lPods-Parse
```
There is still a "-lPods-Parse" in the xcconfigs file but if I replace it with a "-framework Parse" it does not work either.

**Comment by neonichu** [comment]
The previous answer still applies, CocoaPods will never add linker flags for linking specific libraries/frameworks to your project file directly, only via XCConfigs, but editing the linker flags copies the flags from XCConfigs to your target. This is simply how the Xcode project editor behaves. Since CP never adds those things to your project, it will also never remove them.

**Comment by rafaelc0sta** [comment]
@neonichu How can I remove the copied file and return to the original? Any info on how to do that?
