### ISSUE TITLE
copy bundle resource error on v0.36.0

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3278]
I found a issue , when I install `WeiboSDK`, I get a incorrect bundle copy:

In the `Pods-resources.sh`:
```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource "${BUILT_PRODUCTS_DIR}/Weibo.bundle"
fi
if [[ "$CONFIGURATION" == "Release" ]]; then
  install_resource "${BUILT_PRODUCTS_DIR}/Weibo.bundle"
fi
```

What is the `Weibo.bundle`? Just a `WeiboSDK.bundle` in the `WeiboSDK`.

When I run a app with the `WeiboSDK`, I found that:
```
├── Weibo.bundle
│   └── WeiboSDK.bundle
│       ├── images
│       │   ├── close.png
│       │   ├── close@2x.png
....
```
There is a `WeiboSDK.bundle` under the `Weibo.bundle`.

How to fix it?

**Comment by Whirlwind** [comment]
I found there is a `Pods-WeiboSDK-Weibo` target in the `Pods` project, and there is a config in the `WeiboSDK.podspec.json`: 
```
    "resource_bundles": {
        "Weibo": "libWeiboSDK/WeiboSDK.bundle"
    }, 
```

It seem that it is the new feature of 0.36.0.

**Comment by segiddins** [comment]
This sounds to me like a bad podspec more than anything else?

**Comment by neonichu** [comment]
I agree, that will correctly create a bundle inside a bundle, as this is what is being asked for, see <http://guides.cocoapods.org/syntax/podspec.html#resource_bundles>.

@Whirlwind you should report that upstream to the author of the WeiboSDK spec.
