### ISSUE TITLE
duplicate symbols for architecture x86_64 static library

### ISSUE THREAD

**Issue by madhavajay** [CocoaPods/CocoaPods#3279]
I have created a pod lib, then coded my pod, added tests with OCMock and Specta.
The test app runs perfectly.

I then created an aggregate target which uses lipo to produce a final fat file.
This fat file contains, armv7, arm64, x86_64 and i386. (on a side note is armv7s no longer supported?)

Everything works perfectly if I then create a new separate test project add AFNetworking to it with pod and then fire it up, drag and drop my lib.a and header.h into the project and hit run.

However, if I add it via a pod it gives me the duplicate errors below.

My podspec looks like this:
Pod::Spec.new do |s|
  s.name             = "xyz"
  s.version          = "0.0.2"
  s.summary          = "misc"
  s.homepage         = "http://xyz.com/"
  s.license          = {"type" => "Copyright", "text" => "Copyright 2015 xyz. All Rights Reserved."}
  s.author           = { "Madhava Jay" => "me@madhavajay.com" }
  s.source           = { :git => "https://github.com/my/project.git", :tag => s.version.to_s }

  s.platform     = :ios, '7.0'
  s.requires_arc = true

  #s.source_files = 'Pod/Classes/WYTracker.h'
  s.vendored_libraries = 'Pod/StaticLib/libTracker.a'
  s.libraries = 'Tracker';
  s.public_header_files = 'Pod/Classes/**/*.h'

  s.dependency 'AFNetworking', '~> 2.5'
end

Which lints correctly, but if I play with having source files instead of public headers on different builds sometimes pod lib lint complains about stuff.
But right now pod lib lint says everything is good.

Now in my test project I have a pod file like this:

pod 'AFNetworking'
pod 'Tracker', :git => 'https://github.com/my/project'

Note, I have renamed some of the github urls and class names for this post so there isnt any issue with my file naming or paths that all works fine.

So on build I get this:
duplicate symbol _OBJC_METACLASS_$_PodsDummy_Pods_Tracker_Tracker in:
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(Pods-Tracker-Tracker-dummy.o)
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(Pods-Tracker-Tracker-dummy.o)
duplicate symbol _OBJC_CLASS_$_PodsDummy_Pods_Tracker_Tracker in:
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(Pods-Tracker-Tracker-dummy.o)
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(Pods-Tracker-Tracker-dummy.o)
duplicate symbol _OBJC_IVAR_$_WYTracker._customerId in:
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
duplicate symbol _OBJC_IVAR_$_WYTracker._advertisingId in:
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
duplicate symbol _OBJC_IVAR_$_WYTracker._requestManager in:
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
duplicate symbol _OBJC_CLASS_$_WYTracker in:
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
duplicate symbol _OBJC_METACLASS_$_WYTracker in:
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
    /Users/madhavajay/Desktop/dev/iOSTracker/StaticLibraryExample/Pods/Tracker/Pod/StaticLib/libTracker.a(WYTracker.o)
ld: 7 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I even tried extracting the slices and removing the dummy.o from each and putting it back together but that just reduced the number of duplicates but didnt fix the problem.

Surely it cant be that hard to include a static library in a cocoapod?

What am I doing wrong?

**Comment by neonichu** [comment]
You should remove `s.libraries = 'Tracker';`, the `libraries` directive is meant for system libraries. That might lead to linking the same library twice somehow.

If you want to distribute the static library, you should also take a look at <https://github.com/CocoaPods/cocoapods-packager> to streamline the creation process.

**Comment by madhavajay** [comment]
Your correct.

I got it working with:

s.source_files = 'Pod/Classes/xyz.h'
s.vendored_library = 'Pod/StaticLib/libxyz.a'

Thanks. :)
