### ISSUE TITLE
Documentation not updating

### ISSUE THREAD

**Issue by danieldahan** [CocoaPods/CocoaPods#3280]
Hi this page's documentation is not updating: http://cocoapods.org/pods/GKGraphKit

**Comment by orta** [comment]
It's based on the last public release. But ATM CocoaDocs ( which generates these readmes ) is currently in partial operation as we move it to a new server, this will update itself soon. Follow https://github.com/CocoaPods/cocoadocs.org/issues/320 if you're interested.

**Comment by danieldahan** [comment]
Great! Thank you :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan
