### ISSUE TITLE
0.36 Pods-frameworks.sh doesn't copy vendored_framework into ../Frameworks/*

### ISSUE THREAD

**Issue by DaveX101** [CocoaPods/CocoaPods#3281]
Hi, 

This is more just a general question, rather than an issue. This is my first time using Cocoa Pods, so sorry off the bat for any trivial questions. I'm using version 0.36 and I'm trying to create a Pod for an iOS Framework built on iOS8 and Swift. 

I'm testing with this podspec here: https://github.com/DaveX101/DaveXTestPod/blob/master/WildcardSDK.podspec 

I want to package up just a framework I have already built as a vendored framework, the pod won't directly reference any source files. It seems to pass the validation fine, and I've pushed up.

My dependency Podfile looks like this at the moment:
```
platform :ios, '8.0'
use_frameworks!
pod 'WildcardSDK'
```

When running a demo application with this dependency, I'm getting a runtime error because my vendored framework does not seem to have been copied to the right location for the application. 

```
dyld: Library not loaded: @rpath/WildcardSDK.framework/WildcardSDK
```
I believe the Pod-frameworks.sh is doing the same job -- and probably some more -- of what the "Embed Frameworks" Build Phase does by default. My Pod-frameworks.sh just seems to define install_framework(), but I can't find where that function is actually being called. It might not be called at all? I thought it might have been called at the end of the function definitions inside the script itself.

So, inside the Frameworks/ dir inside my application's build directory, I just see the standard Swift runtimes, but I'm not seeing WildcardSDK.framework, which I was expecting to see.

Again, this is my first pod so sorry if any of my basic understanding of things is off. 

Thanks in advance

**Comment by segiddins** [comment]
This is a known issue, I believe.

**Comment by neonichu** [comment]
Yep, indeed, see #1993

**Comment by DaveX101** [comment]
Thanks
