### ISSUE TITLE
add ability to link_with all targets

### ISSUE THREAD

**Issue by munsie** [CocoaPods/CocoaPods#3282]
Currently link_with defaults to the first target in a project and you can override it in the Podfile to as many targets as you want.  It would be useful to be able to specify all targets in some way on the link_with line instead of having to list out each one manually.

**Comment by segiddins** [comment]
You already can do `link_with 'MyApp', 'MyOtherApp'`.

**Comment by munsie** [comment]
Yes, I realize you can manually specify each target.  But I have a project I'm working with that has 50 targets, and each of them need to be linked with all of the pods.  Maintaining a list of apps in the Podfile has a lot of disadvantages.  It would be much better if you could specify some sort of wildcard instead of having to list out each one individually.

**Comment by segiddins** [comment]
That will be done when we eventually get the new Podfile DSL written.
