### ISSUE TITLE
unable  "pod trunk push" with error "[!]The podspec does not validate."

### ISSUE THREAD

**Issue by iOSNerd** [CocoaPods/CocoaPods#3284]
I'm trying to push my podspec with Trunk:
![000000](https://cloud.githubusercontent.com/assets/4392747/6701576/99ab8744-cd59-11e4-8843-5ae10af5746a.png)
but get some errors logs:
![11121321](https://cloud.githubusercontent.com/assets/4392747/6701577/99ef2134-cd59-11e4-8375-eb1746ac3d75.png)

this podspec was made for my github [repositorie](https://github.com/iOSNerd/PagedScrollView) for the first time,i'm following the Trunk guide(http://guides.cocoapods.org/making/getting-setup-with-trunk.html ),i did the register, wrote my podspec,push trunk, then got that error.may someone help me to deal with the error.thanks.

**Comment by orta** [comment]
Can you try it with CocoaPods `0.36` the most recent version? I think we may have added a check to only support the latest version when pushing a new pod. Unsure if this is shown in the errors on 0.35, as I'd expect to see it in that command.

**Comment by segiddins** [comment]
No, that's happening because of the warning.

**Comment by iOSNerd** [comment]
@orta i upgrade CocoaPods to 0.36.0 and try again,no,the console said the same error.
@segiddins that's the point!  i add a tag, push the tag to remote,then try it again,it just works! thanks O(∩_∩)O
