### ISSUE TITLE
How to change the pod if I have to fix something while using cocoapods

### ISSUE THREAD

**Issue by wongzigii** [CocoaPods/CocoaPods#3285]
See this question also:
http://stackoverflow.com/questions/29113978/how-to-change-the-pod-if-i-have-to-fix-something-while-using-cocoapods

**Comment by AliSoftware** [comment]
Please keep this CocoaPods issue tracker here on GitHub only for issues with CocoaPods, and ask questions on SO only.

But just for you know, the answer from Jamin Zhang on your SO question is the way to go. That solution is also [documented here in our official Guides](http://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo).

**Comment by wongzigii** [comment]
Excellent！
