### ISSUE TITLE
FormatterKit in PodSec " failed: No such file or directory"

### ISSUE THREAD

**Issue by mikeRozen** [CocoaPods/CocoaPods#3288]
I have a strange issue when try to use FormatterKit in PodSec:`pod lib lint` generate the following error:
   ``` - NOTE  | [ARNUHelpersVer2/FormatterKit]  error: make directory /var/folders/vy/cw2t3p5s3xsfmjcp9w7t5brw0000gn/T/CocoaPods/Lint/build/Release-iphonesimulator/Pods/FormatterKit.framework/ca.lproj: File exists   ```
 ```   - NOTE  | [ARNUHelpersVer2/FormatterKit]  error: couldn't remove '/var/folders/vy/cw2t3p5s3xsfmjcp9w7t5brw0000gn/T/CocoaPods/Lint/build/Release-iphonesimulator/Pods/FormatterKit.framework/ca.lproj' after command failed: No such file or directory```
I see no file ```ca.lproj``` at all at the build directory.(So Xcode try to remove something that not exist)
I read that issue :https://github.com/mattt/FormatterKit/issues/88
My PodSec:
```    
Pod::Spec.new do |s|

s.name         = "ARNUHelpersVer2"
  s.version      = "0.0.1"
  s.summary      = "A short description of ARNUHelpersVer2."
  s.frameworks = 'QuartzCore', 'UIKit', 'Foundation', 'SystemConfiguration'
  s.description  = <<-DESC
                   A longer description of ARNUHelpersVer2 in Markdown format.

                   * Think: Why did you write this? What is the focus? What does it do?
                   * CocoaPods will be using this to generate tags, and improve search results.
                   * Try to keep it short, snappy and to the point.
                   * Finally, don't worry about the indent, CocoaPods strips it!
                   DESC

  s.homepage     = "http://EXAMPLE/ARNUHelpersVer2"
  s.requires_arc = true
  s.author             = { "Mike" => "myMail@gmail.com" }
  s.platform     = :ios, "7.0"
  s.ios.deployment_target = "7.0"
  s.source       = { :git => "git@bitbucket.org:Private", :submodules => true  }
  s.source_files  = 'ARNUHelpersVer2/*.{h,m}'


  #  s.subspec 'Choosy' do |ss|
   #     ss.dependency 'Choosy'
   # end
    s.subspec 'FormatterKit' do |ss|
        ss.dependency 'FormatterKit'
    end
end
```
Is It a bug? Did any body had this problem?What will be the correct solution so that people who will use my library wont see this kind of error.

**Comment by segiddins** [comment]
Can you please provide a reproducible case that we could look into?

**Comment by mikeRozen** [comment]
Sure, segiddins can you pleas create podsec and use FormatterKit as dependency and then try to run validation? Curious if you  will receive them also?

**Comment by neonichu** [comment]
This should be solved by #3315, the issue is that FormatterKit duplicates the resource bundles for all its subspecs.

**Comment by mikeRozen** [comment]
So was it solved ??? coz I use the last ver and still has it?

**Comment by neonichu** [comment]
Nope, the PR is not merged, yet.
