### ISSUE TITLE
Installing targets is extremely slow in 0.36

### ISSUE THREAD

**Issue by alcrus** [CocoaPods/CocoaPods#3290]
Upgraded to 0.36 and trying to run 'pod install' on our project. When used 0.35 whole process took 20-30 seconds. After upgrade it takes more than 30 minutes. If I run it with --verbose option it stops on each
   - Installing target 'abc...'
   - Installing target 'xyz...'
and waits sometimes seconds sometimes minutes. Last target takes about 15 minutes, nothing too big there, only unit tests. Just in case, there are 32 targets in the project.

**Comment by segiddins** [comment]
Could you please share both your full verbose output and your podfile?

**Comment by INRIX-Aleksei-Zhilin** [comment]
Sent by email. Sorry, can't share it here.

**Comment by alcrus** [comment]
Sent by email. Sorry, can't share it here.

**Comment by segiddins** [comment]
From what you sent me, I can't see why installation would take so long.

**Comment by kylef** [comment]
Could it be slow internet / large pod spec repo syncing?
#3237 should help with syncing times.

**Comment by alcrus** [comment]
If I understand right, it happens after syncing. Looks like slow updating of workspace and project files if there are cross-references between targets.

**Comment by kylef** [comment]
@alcrus Would you be able to create an example project that exhibits this "slowness" as you describe?

**Comment by alcrus** [comment]
Will try to create something. After some experiments found that speed depends on number of source files in local subspecs. We describe it in this way:

s.subspec 'Subspec1' do |ss|
    ss.source_files =
      'Classes/Class1Private.h',
      'Classes/Class1.{h,m}'
    ss.private_header_files =
      'Classes/Class1Private.h'
end

So there are 60 subspecs and about 200 source files, each separately defined as 'SomeClass.{h,m}'

If I move everything to a single subspec with single file mask 'pod install' becomes really really fast.

s.subspec 'Subspec1' do |ss|
    ss.source_files =
      'Classes/*Private.h',
      'Classes/*.{h,m}'
    ss.private_header_files =
      'Classes/*Private.h'
end

**Comment by segiddins** [comment]
In that case, to debug we definitely will need to be able to run `pod install` ourselves to profile.

**Comment by neonichu** [comment]
Since there was reaction for a long time, we can close this.
