### ISSUE TITLE
How to skip a pod when running installing(via install) or updating(via update)?

### ISSUE THREAD

**Issue by hagile** [CocoaPods/CocoaPods#3294]
I've few libraries added in my pod file. One of the pod files need to update by me as per my requirement, I know in future if I'll run `$ pod update` it will also update the pod in which I've made the changes before. How to skip that pod when I will run `$ pod install` or  `$ pod update` command? And yes, I've around 15 pods so I don't want to run `$ pod update <podname>` for each file? I think it would be bad idea?

What I can do to preserve my changes for a particular pod?

I already read [this](http://stackoverflow.com/questions/16613464/will-pod-update-overwrite-my-code-changes-when-a-new-version-of-the-pod-is-ava) and I don't think this would be a good idea!

**Comment by neonichu** [comment]
Forking is the only good way to keep your changes. 

Skipping Pods is not possible, running `pod update <podname>` multiple times works just fine, though. If you run it in quick succession, you might want to pass `--no-repo-update` to speed it up a bit.

**Comment by hagile** [comment]
--no-repo-update ? where to use it?

**Comment by orta** [comment]
`pod update <podname> --no-repo-update`
