### ISSUE TITLE
Duplicated resources

### ISSUE THREAD

**Issue by valeriomazzeo** [CocoaPods/CocoaPods#3295]
I am not sure this is related to `Cocoapods` or `FormatterKit`, but I thought it was worth mentioning it in here as well:

https://github.com/mattt/FormatterKit/issues/161

**Comment by orta** [comment]
What version of cocoapods

**Comment by valeriomazzeo** [comment]
0.36.0

**Comment by neonichu** [comment]
Seems like it is happening because each subspec contains `ss.resources = 'Localizations/**'`.

**Comment by valeriomazzeo** [comment]
but somehow that wasn't happening before, is this to be considered a regression in Cocoapods?

**Comment by segiddins** [comment]
No, its intentional on CocoaPods' part. We only include the resources the spec tells us to. If it tells us to include resources multiple times, we do.

**Comment by neonichu** [comment]
Yep, just checked, it did also happen when integrating with static libraries in 0.35:

```
$ grep uk.lproj Pods-resources.sh|wc -l
       9
```

There just was no warning, because the script just silently overwrote them.

**Comment by valeriomazzeo** [comment]
I will link this discussion on the pod page, thanks.
