### ISSUE TITLE
Feature Request: Trunk should guard against publishing pods whose source is not publicly available.

### ISSUE THREAD

**Issue by brianpartridge** [CocoaPods/CocoaPods#3296]
Coming out of a discussion in #3275 , it would be great if calls to `pod trunk push` validated the availability of a pod before publishing it.

For example:
I'm working on my pod, which references my company's internal SCM server, if I `pod trunk push` my pod, the trunk service should reject it because the the source URL is either inaccessible or requires authentication.

This would help prevent private pods from accidentally being published, and ensure that all published pods are actually accessible to all pod consumers.

**Comment by kylef** [comment]
I'm not entirely sure how to achieve this, but perhaps via sandboxing #2848. With sandboxing, we can prevent `git` and any CocoaPods-downloader from having access to files like `~/.netrc` and `~/.ssh` where credentials are stored.

**Comment by brianpartridge** [comment]
If it's implemented server-side we could skip sandboxing entirely because the trunk service will never have the credentials for third party resources (private SCM servers, private github repos, etc).

**Comment by segiddins** [comment]
We try to keep trunk as lean as possible. Doing downloads would probably be more than a single server can safely handle.

**Comment by brianpartridge** [comment]
Oh, I didn't realize it didn't do downloads, I guess client-side would be the way to go then.

**Comment by orta** [comment]
Can't trunk make an ACK-like request to the different types of code hosting?

**Comment by segiddins** [comment]
That would require building and testing additional logic for each downloader type. At the end of the day, I don't think that sort of effort is worth it.

**Comment by segiddins** [comment]
This is being tracked at https://github.com/CocoaPods/trunk.cocoapods.org/issues/136, and work is already in progress on this.
