### ISSUE TITLE
Lowercase "specs" directory on case-sensitive volume

### ISSUE THREAD

**Issue by eholley** [CocoaPods/CocoaPods#3297]
If a pod spec contains a "specs" directory instead of "Specs" on a case-sensitive volume, at least two things happen: 1) pod update fails with "[!] Unable to find a specification for", and 2) pod list fails with "[!] An unexpected version directory".

These issues are not present on case-insensitive volumes.

Changing "specs" directory to "Specs" clears up both problems.

**Comment by segiddins** [comment]
Yes, the directory is `Specs`.

**Comment by eholley** [comment]
That's what I expected. But, another group in our org misnamed it and my build server is case-sensitive.

Thanks.

**Comment by orta** [comment]
@segiddins think it's worth including something for this?

**Comment by segiddins** [comment]
Nope. `Specs` is the dir.
