### ISSUE TITLE
CJK folder name converted to unicode digital number.

### ISSUE THREAD

**Issue by Guou** [CocoaPods/CocoaPods#3298]
The latest 0.36.0 will convert folder name encoded in CJK to corresponding unicode digital number.

For example:
original group name in Xcode project is '中文乱码'
after `pod install`
group name will be transformed to `&#20013;&#25991;&#20081;&#30721;`

Downgraded to 0.35.0 will be OK.

Any ideas?

Thanks

**Comment by segiddins** [comment]
@neonichu is it possible that the new Xcodeproj serialization doesn't correctly handle unicode?

**Comment by neonichu** [comment]
Should be the other way around, e.g. there's a spec for emoji. My guess is that the XML fallback is being hit, I'll investigate.
