### ISSUE TITLE
Configurations with a number prefix will generate an invalid Pods-*-environment.h

### ISSUE THREAD

**Issue by HeEAaD** [CocoaPods/CocoaPods#3301]
# Bug
## Given
* project `ExampleApp` with a build configuration `1 - Develop`
* a Podfile with a definition `pod 'HockeySDK', :configuration => ['1 - Develop']`

## Bug description
`pod install` will generate an invalide Pods-ExampleApp-environment.h:
```
#ifdef 1___DEVELOP

  // HockeySDK
  #define COCOAPODS_POD_AVAILABLE_HockeySDK
  #define COCOAPODS_VERSION_MAJOR_HockeySDK 3
  #define COCOAPODS_VERSION_MINOR_HockeySDK 6
  #define COCOAPODS_VERSION_PATCH_HockeySDK 2

#endif
```

Because a define with a leading number is invalid: `#ifdef 1___DEVELOP`
## Error
```
Pods-ExampleApp-environment.h:16:8: error: macro names must be identifiers
#ifdef 1___DEVELOP
       ^
1 error generated.
```
# Enviroment
```
$ pod --version
0.36.0
$ xcodebuild -version 
Xcode 6.2
Build version 6C131e
```

**Comment by segiddins** [comment]
Are non-c99ext identifiers valid configuration names?

**Comment by HeEAaD** [comment]
I can't find any restrictions in the apple documentations.

The generated define should be match generated preprocessor definition `_1___DEVELOP=1`
