### ISSUE TITLE
Improve CLI by autocorrecting commands

### ISSUE THREAD

**Issue by MarcoSero** [CocoaPods/CocoaPods#3307]
It would be nice if the CLI would autocorrect commands in the same way `git` does.

e.g.
```bash
$ pod instal
WARNING: You called a Pod command named 'instal', which does not exist.
Continuing under the assumption that you meant 'install'
```

**Comment by neonichu** [comment]
I'd like that - do you want to contribute a PR? :)

**Comment by MarcoSero** [comment]
It sounds like a fun feature to implement, but I can't guarantee anything as my Ruby-foo is lacking :)

**Comment by neonichu** [comment]
Sounds like a good opportunity to improve it :) Feel free to create a WIP branch and I'll be happy to help when you get stuck.

**Comment by segiddins** [comment]
Definitely don't want this -- I much prefer the suggestion. This way, no destructive action gets performed accidentally.

**Comment by orta** [comment]
We can whitelist the things this should happen for? Or blacklist things that are destructive, though I guess you'd class `install` / `update` as destructive?

**Comment by segiddins** [comment]
Yes I would. I actually really really dislike that `git` does this.

**Comment by orta** [comment]
I believe it is a custom option to turn it on:

```
$ git ad .                                                                                                              
git: 'ad' is not a git command. See 'git --help'.

Did you mean one of these?
	add
	cad

$ git comit as
git: 'comit' is not a git command. See 'git --help'.

Did you mean this?
	commit
```

For long commands like `install` or `update` I can't even think of other commands which are similar enough in string distance to return a fuzzy match. It feels like a better user experience with this included.

**Comment by kylef** [comment]
We already have suggestions...

![screen shot 2015-03-31 at 03 41 16](https://cloud.githubusercontent.com/assets/44164/6911383/d9db8d5c-d757-11e4-918d-48903495b6f0.png)

I agree with @segiddins, this could potentially be really dangerous and we should never autocorrect commands with our best guess. Especially if a plugin was to introduce a command with a similar name. For example a typo of `pod dependencies`  resulting in `pod deintegrate` (a highly destructive action).

I vote we leave the suggestions as they are, as suggestions.

**Comment by orta** [comment]
Cool, then lets close this :+1: - democracy at work.

**Comment by neonichu** [comment]
failed design dictatorship 🙈😛

**Comment by MarcoSero** [comment]
:+1:
