### ISSUE TITLE
Offer alternative ways to release a new CocoaPod

### ISSUE THREAD

**Issue by dkhamsing** [CocoaPods/CocoaPods#3308]
Ability to update a CocoaPod from the web or app (tag release, update podspec etc) via https://twitter.com/modocache/status/580079116851896320 @modocache @mattbischoff

**Comment by orta** [comment]
This is definitely something we could look into for [CocoaPods.app](https://github.com/CocoaPods/CocoaPods.app) as a v2 release.

**Comment by dkhamsing** [comment]
cc @modocache @mattbischoff

**Comment by neonichu** [comment]
As for doing it away from :computer:, I still think the best way is tying it to CI. Since we recently added an env variable for the trunk token, it should be possible to push new specs once a tag is created.

**Comment by kylef** [comment]
What about something like the following:

```ruby
Pod::Spec do |spec|
  spec.name = 'QueryKit'
  spec.version = `git describe --tags`.chomp
end
```

Then the process would be:

```shell
$ git tag 0.5.2
$ pod trunk push
```

**Comment by orta** [comment]
As we do shallow clones, would that work with `:git => "http://..."`?

**Comment by kylef** [comment]
@orta Yes, remember, the spec pushed to trunk is a JSON version. This will be evaluated locally and the pod spec will have the correct version from the tag.

**Comment by kylef** [comment]
I'll make a PR on pod-template.

**Comment by orta** [comment]
yeah, my question was when you use `:git`, it ignores the Specs repo, and grabs the stated repo and uses "name.podspec" from the root of the repo, which may not have any tags?

**Comment by kylef** [comment]
Ah, that's a good point.

**Comment by segiddins** [comment]
As long as the repo has tags, it will evaluate the podspec before cleaning the downloaded pod source.

**Comment by orta** [comment]
but would it shallow clone without tags?

**Comment by segiddins** [comment]
I don't believe so?

**Comment by segiddins** [comment]
No, the tags are not available after a shallow clone.

**Comment by orta** [comment]
wait, this entire discussion is moot. Who does a shallow clone of their own repo? Ignore everything I've said for the last day.

**Comment by kylef** [comment]
@orta My idea was flawed as you pointed out:

```
pod 'Foo', :git => 'path-to-foo'
```

Should result in a shallow clone.

**Comment by orta** [comment]
Yeah, but you're not really going to be push a release from inside another app with a Podfile, you would do it from it's own repo.

```
$ MyApp: cd Pods/MyPods/XPod
$ XPod: git tag 1.2.3
$ XPod: git trunk push
````

**Comment by segiddins** [comment]
Sure but it would mean your users could never use your pod by pointing at an unreleased branch

**Comment by orta** [comment]
Oh yeah, now I remember my real point :-/
Thanks @segiddins

**Comment by segiddins** [comment]
Closing since this can all be done using the existing CocoaPods ecosystem.

**Comment by neonichu** [comment]
Just dropping this here, because it describes that process: https://fuller.li/posts/automated-cocoapods-releases-with-ci/
