### ISSUE TITLE
Specify xcconfig settings in spec only for pod, not for consuming project.

### ISSUE THREAD

**Issue by brianpartridge** [CocoaPods/CocoaPods#3309]
I've been trying to port some existing libraries over to CocoaPods and I want to maintain some of the build settings (compiler warnings and the like) which were configured when the pods were static library targets in an xcodeproj.  I'm looking to move these settings the podspec using the [xcconfig](http://guides.cocoapods.org/syntax/podspec.html#xcconfig) option, but it's not behaving the way I was expecting.

When I include `s.xcconfig = { "BP_TEST" => "1" }` in my podspec. The pod in the podspec is built with this user-defined build setting, which is correct, but so it the consuming app, which I did not expect.  Why do these build setting seem through into the consuming project?  

I can't tell if this is a bug or intentional. Is there anyway to specify build settings that apply only to the pod?  If it is intentional, perhaps this is just a [documentation](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L720) issue that could be clarified.

**Comment by mxcl** [comment]
Doesn’t happen with `use_frameworks!`. Just FYI.

**Comment by brianpartridge** [comment]
Thanks, I think that makes perfect sense, since the framework is a self contained bundle. Unfortunately, I'm not able to use Frameworks in this project.

**Comment by segiddins** [comment]
This is now possible using https://guides.cocoapods.org/syntax/podspec.html#pod_target_xcconfig, which was introduced in 0.38.

**Comment by brianpartridge** [comment]
:+1: Thanks!
