### ISSUE TITLE
Pushing podspec fails in 0.36 for OSX resource bundle.

### ISSUE THREAD

**Issue by brianpartridge** [CocoaPods/CocoaPods#3310]
I have a podspec for a library which supports OSX and iOS and contains a resource bundle which is used on both platforms.  Recently, when trying to push a new version to our private spec repo (`pod repo push <repo> <podspec>`), the OSX version has failed when validating the resource bundle:

```
/usr/bin/codesign --force --sign - /var/folders/6j/4__tztjj7j3_gn_4bjmsvzq8000253/T/CocoaPods/Lint/build/Release/SquareCoreResources.bundle
/var/folders/6j/4__tztjj7j3_gn_4bjmsvzq8000253/T/CocoaPods/Lint/build/Release/SquareCoreResources.bundle: bundle format unrecognized, invalid, or unsuitable
Command /usr/bin/codesign failed with exit code 1
```

This works fine with CocoaPods 0.35, but is a new issue with 0.36.  The pod is installed and built into it's local example project just fine.  I know some changes went into 0.36 with fixed another bug with resource bundles, maybe this is a side effect?

For reference here's the spec:

```
Pod::Spec.new do |s|
  s.name         = "SquareCore"

#snip
  
  s.ios.deployment_target = "7.0"
  s.osx.deployment_target = "10.8"
  
#snip
  
  s.resource_bundle = { "SquareCoreResources" => ["Resources/SquareCoreResources/*"]}
}
```

**Comment by kylef** [comment]
Would either of you be able to share a podspec we can use to reproduce this issue via `pod spec lint`?

**Comment by pietbrauer** [comment]
@kylef Sorry, not able as everything is closed source. (Thats probably one of the reason it fails :wink:)

**Comment by brianpartridge** [comment]
@kylef Here you go: https://github.com/brianpartridge/SquareCore

**Comment by gregcotten** [comment]
A thousand times this.

Here's one of mine: https://github.com/videovillage/CocoaLUT

**Comment by segiddins** [comment]
@neonichu as I recall, you've worked on some of the code signing stuff. would you be able to look into this?

**Comment by neonichu** [comment]
Seems like passing `CODE_SIGN_IDENTITY=-` to `xcodebuild` is the culprit, trying to sign OS X resource bundles if it is passed.

**Comment by neonichu** [comment]
Thankfully `CODE_SIGN_IDENTITY=-` doesn't mess with iOS targets and we do not need to pass it for OS X targets anyway.  ¯\_(ツ)_/¯

**Comment by brianpartridge** [comment]
Thanks guys!

**Comment by gregcotten** [comment]
@kylef Any idea when you guys will be versioning up? This kind of breaks OSX CocoaPods with resource bundles...

Greg
