### ISSUE TITLE
Cocoapods 0.36.0 Breaks agvtool

### ISSUE THREAD

**Issue by keab42** [CocoaPods/CocoaPods#3312]
Duplicate of #2464 

Installing xcproj via brew and then running xcproj touch seems to have resolved this temporarily.

**Comment by neonichu** [comment]
Could you please check if your Xcode environment is configured correctly by running `nm -g "`xcode-select -p`/../PlugIns/Xcode3Core.ideplugin/Contents/Frameworks/DevToolsCore.framework/DevToolsCore"|grep PBXProject|wc -l`

If this shows an error, you should use `xcode-select -s` to correct the configuration.

**Comment by keab42** [comment]
That command returns "58"

**Comment by neonichu** [comment]
OK, that is how it should be - unsure why it doesn't get loaded correctly in your case. Which version of Xcode do you use?

In general, things like this will be easier to diagnose when CocoaPods/Xcodeproj#252 is done.

**Comment by keab42** [comment]
I'm using Xcode 6.2

**Comment by kylef** [comment]
I've figured out why CocoaPods saves XML for some users and moved this ticket to https://github.com/CocoaPods/Xcodeproj/issues/257.
