### ISSUE TITLE
Console message to open .xcworkspace file versus .xcproject

### ISSUE THREAD

**Issue by iwasrobbed** [CocoaPods/CocoaPods#3314]
On certain projects, we choose to source control the `.xcworkspace` file and we have server engineers who need to run the iOS builds. 

In the past, CocoaPods used to print a nice hint to the console after running `pod install` that they need to open the `.xcworkspace` file that just got done being created/integrated instead of opening the `.xcproject` file and getting build errors. Unfortunately that message isn't shown in the 0.36.0 release. 

Would it be possible to bring this helpful message back for those who aren't used to working with CocoaPods?

**Comment by neonichu** [comment]
That message still exists in 0.36, though, the wording has slightly changed:

```bash
$ pod install
Analyzing dependencies
Downloading dependencies
Using Alamofire (1.1.4)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `Yolo.xcworkspace` for this project from now on.
```

AFAIK, it was never shown if the *.xcworkspace* already existed, only when CP creates it.

**Comment by iwasrobbed** [comment]
Any reason it shouldn't be shown for the scenario where a workspace file is already in place?

**Comment by neonichu** [comment]
Avoiding unnecessary noise for most users. Especially the new message only makes sense the first time.

**Comment by iwasrobbed** [comment]
The above message definitely makes sense only during the creation, but I would still vote for outputting a similar message during any type of overwriting install as a point of clarity. In this case, I don't see it as unnecessay noise and would be interested in hearing other opinions.

**Comment by orta** [comment]
I think superfluous messages would be more annoying overall, as you eventually end up with [600 lines of text](https://twitter.com/qrush/status/580393148158971904) for a single command.

I'd recommend creating a message in your [setup script](https://github.com/artsy/eigen/#oss-quick-start) for the repo that tells people to open the workspace.
