### ISSUE TITLE
CocoaPods mistakenly flagging a warning when using multiple build configurations

### ISSUE THREAD

**Issue by jaderedu** [CocoaPods/CocoaPods#3316]
I have three build configurations in my App, `Release`, `Debug` & `Beta`. When running `pod install` CocoaPods flags a warning about my project already having a custom config set. Everything works, but this is the warning I get:

```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Gojimo` to `Pods/Target Support Files/Pods/Pods.beta.xcconfig` or include the `Pods/Target Support Files/Pods/Pods.beta.xcconfig` in your build configuration.
```

This is my `Podfile`:
```
platform :ios, '7.0'

xcodeproj 'XXXXX.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

pod 'DTCoreText', '~> 1.6.13'
pod 'Reachability', '~> 3.1.1'
pod 'AFNetworking',  :head
pod 'AFDownloadRequestOperation', '~> 2.0.0'
pod 'JVFloatLabeledTextField', :git => 'https://github.com/synchromation/JVFloatLabeledTextField.git'
pod 'SSZipArchive', '~> 0.3.1'
pod 'NYXImagesKit', :git => 'https://github.com/synchromation/NYXImagesKit.git'
pod 'NSData+Base64', '~> 1.0.0'
pod 'Mixpanel'
pod 'GoogleConversionTracking'
pod 'RMStore', '~> 0.7'
```

And my project's build configuration:
![screen shot 2015-03-25 at 10 07 36](https://cloud.githubusercontent.com/assets/10706062/6822394/47e62d96-d2d7-11e4-83f9-e640aa5a8b83.png)

**Comment by neonichu** [comment]
Did you manually change the XCConfigs for the Beta configuration to "Pods.release" or was this done by CocoaPods?

**Comment by jaderedu** [comment]
No manual changes @neonichu

**Comment by keab42** [comment]
I've noticed this before. If you've already got Cocoapods set up, then duplicate an existing configuration to create a new one, this is what happens. I'd guess you copied Release here, hence why the targets all have pods.release set as the config.

The way I've gotten round it is to set all the configurations to "none" then run pod install again.

**Comment by jaderedu** [comment]
@keab42 your solution worked but it only set the configuration correctly for my main target. I had to set the other configurations manually on the other targets, which is not the end of the world I guess.

I'm closing this issue as it was probably something cased by duplicating the build configuration as pointed out by @keab42

**Comment by neonichu** [comment]
You can configure your custom build configurations, see <http://guides.cocoapods.org/syntax/podfile.html#xcodeproj>

**Comment by jaderedu** [comment]
Thanks @neonichu I didn't know you could do that. That definitely solves the problem!
