### ISSUE TITLE
use_frameworks for cretain pod

### ISSUE THREAD

**Issue by Fl0p** [CocoaPods/CocoaPods#3317]
``` inhibit_all_warnings ``` attribute can be used per pod like:
``` pod 'SSZipArchive', :inhibit_warnings => true ```

Would be great possibility to enable ``` use_frameworks ``` for certain pod only
``` pod 'TTTAttributedLabel', :use_frameworks => true ```

For now it parsed like source parameter
```
[!] Unknown external source parameters for `TTTAttributedLabel`: `{:use_frameworks=>true}`
```

Also as option disable framework for pod when ``` use_frameworks! ``` something like this

```
:use_frameworks!
pod 'TTTAttributedLabel', :not_use_frameworks => true 
```

Is it possible ?

**Comment by neonichu** [comment]
This won't be possible, because of transitive dependencies and would vastly increase complexity. We still have to document this, though, see CocoaPods/guides.cocoapods.org#53

**Comment by hectormatos2011** [comment]
@neonichu Is there any way to get around this while still using Cocoapods? The GoogleAnalyticsiOSSDK uses a static library and when using `:use_frameworks!` (due to having swift pods), the compiler issues this warning:

```ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by ammoqq** [comment]
Yeah i'm using LiveSDK and got same problem, it doesn't work with "use_frameworks!"
I would love this issue to be implemented, any chance for that ?

**Comment by efirestone** [comment]
A workaround I've been using:

In your podspec:
```
  s.prepare_command = <<-CMD
    echo "
      #import <Foundation/Foundation.h>

      @interface SomeDummy : NSObject
      @end

      @implementation SomeDummy
      @end
    " > Source/SomeDummy.m
  CMD

  # CocoaPods prefers to build using dynamic frameworks, and in fact requires it for Swift projects. 
  # This means that it can't link a static lib directly. As a workaround we create a dynamic framework 
  # wrapper around the static library using the following steps:
  #   - Create a dummy class so that we actually have something to build.
  #   - Build that dummy class as a dynamic framework.
  #   - Link the static library into that dynamic framework using forced linker flags (see the xcconfig below).
  s.source_files = "Source/**/*.{h,m}"
  s.preserve_paths = "./libStaticLib.a"
  s.xcconfig = { "OTHER_LDFLAGS" => "-force_load $(PODS_ROOT)/#{ s.name }/libStaticLib.a" }
end
```

**Comment by orta** [comment]
Nice hack, this should work for Pods that aren't depended on by other pods ( that's when things will break :+1:  )

**Comment by efirestone** [comment]
What's the issue with dependencies? I haven't seen any issues with this being the leaf in a two-layered dependency structure. It's only the dependency for one parent, so maybe a duplicate symbols issue if multiple specs depend on it? I wouldn't expect that, but haven't tried it.

**Comment by hk0i** [comment]
So this is a bit of a stretch, but I'm experiencing similar issues with the MoPub Ads `mopub-ios-sdk` pod. Except in this case my problems arise at runtime. I'm not 100% sure this is my problem, but if I compile the static lib and use that, the code works as expected every time.

I'll try fiddling with other things as well, but I want to keep an eye on this issue. I almost don't believe this would help me, but as of right now it's all I have to go on.
