### ISSUE TITLE
Command /bin/sh failed with exit code 23 for version 0.36.0

### ISSUE THREAD

**Issue by heatherSnepenger** [CocoaPods/CocoaPods#3319]
I'm getting the following error when I try to build my Cocoapod:

    rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
    Command /bin/sh failed with exit code 23

I thought this was resolved?

**Comment by kylef** [comment]
@heatherSnepenger Could you provide a bit more information? Complete steps to reproduce this or an example project exhibiting this issue would be helpful.

**Comment by jshier** [comment]
I'm also currently seeing this with CocoaPods 0.36.3. 
```
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
```
I'm also getting this warning at the same time:
```
Pods was rejected as an implicit dependency for 'libPods.a' because it doesn't contain platform 'iphonesimulator' in its SUPPORTED_PLATFORMS 'macosx'
```

This is using Xcode 6.2 on 10.10.2.

**Comment by kylef** [comment]
@jshier Again, can you provide more information? There is nothing we can do about this problem without steps to reproduce or an example project.

**Comment by jshier** [comment]
I can't seem to produce a reduced example and the project I'm seeing it on is private. 0.35 works fine on the same project, and 0.36 had previously failed because of a compilation issue with MockInject (new flag in 0.36 lead to a compile issue which I have PR up for MockInject, it was a casting issue). Let me know if there's something I can get for you, but a straight up copy of the project isn't possible.

**Comment by segiddins** [comment]
Unless you can create a project that you can share with us that reproduces the problem, whether it's the original project or a new one, we won't really be able to investigate, sorry.

**Comment by jshier** [comment]
I seem to have traced the issue to a bad post install hook. I was trying to set a particular preprocessor flag for all of the pods when a particular configuration was active and it seems to have only worked for that configuration, and broken the generation of the configuration file for all other configurations. Here's what I was doing:
```
  installer.project.targets.each do |target|
      target.build_configurations.each do |config|
          if config.name = 'FunctionalTests'
              config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'KIF=1']
          end
      end
  end
```
After removing that the project built without the warning I was seeing and without the original rsync error. 

BTW, any recommendations on how to accomplish what I wanted with that post install hook?

**Comment by kylef** [comment]
@jshier What's your goal with setting `GCC_PREPROCESSOR_DEFINITIONS`? I.e, at a larger scale what problem are you trying to solve by setting `KIF=1`?

You should simply be able to install KIF specific to a configuration:

```ruby
target 'FunctionalTests', :exclusive => true do
  pod 'KIF', '~> 3.0', :configurations => ['Debug']
end
```

**Comment by jshier** [comment]
I'm trying to modify the behavior of private pods when running KIF tests, by say, setting the number of retry attempts for a network call to zero when KIF = 1. So I'm trying to do:
```
#if KIF
// different behavior
#endif

I'm already using the configuration to load particular pods only for particular configurations.

**Comment by segiddins** [comment]
@jshier in your case, why not do that at runtime, by checking if any of the KIF classes are available?

**Comment by jshier** [comment]
An interesting solution. You mean NSClassFromString(@"KIFHelper") != nil, correct? A preprocessor check seems "simpler" but I suppose a runtime solution would work if what I want isn't possible as a post install hook.

**Comment by segiddins** [comment]
I'm sure it is possible as a post-install hook, but in general I always recommend doing that sort of thing at runtime instead of compile-time (but you should probably only be doing this in DEBUG builds anyways)

**Comment by jshier** [comment]
Thinking on it more, I'm not sure I like the runtime solution, as it would mean that the check is hit in the production app and would, of course, be false. I know it's a fairly small amount of work, but I'm still not really comfortable doing something that's 100% pointless in release mode. So, how am I supposed to get preprocessor flags to pods?

**Comment by segiddins** [comment]
Have you tried

```ruby
  installer.project.targets.each do |target|
      target.build_configurations.each do |config|
          if config.name = 'FunctionalTests'
              (config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= '') <<  '$(inherited) KIF=1'
          end
      end
  end
```

**Comment by jshier** [comment]
Nope, same warning as before.

**Comment by pakmee** [comment]
Anyone found any solution for this. Having the same issue but only when archiving.

**Comment by neonichu** [comment]
Could you retry this with the 0.38 beta?

**Comment by markiv** [comment]
I tried this with 0.38.0.beta.2 and got the following error:
```[!] An error occurred while processing the post-install hook of the Podfile.
undefined method `project' for #<Pod::Installer:0x007fe56af28cb0>```

**Comment by segiddins** [comment]
@markiv change `project` in your post-install hook to `pods_project`

**Comment by neonichu** [comment]
I feel like we can close this without response for a while.

**Comment by philipheinser** [comment]
same error in 3 projects -.-
```
Command /bin/sh failed with exit code 23
```

**Comment by simoncoulton** [comment]
Getting this in Xcode 7 at the moment:

```
sent 130941 bytes  received 42 bytes  261966.00 bytes/sec
total size is 130816  speedup is 1.00
rsync -auv "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftSecurity.dylib" "/Users/simon/Library/Developer/Xcode/DerivedData/Core-gsugaskgvvljlsbbrlqwgexjknrz/Build/Products/Debug-iphonesimulator/CoreTests.xctest/Frameworks"
building file list ... rsync: link_stat "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftSecurity.dylib" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

**Comment by fitch** [comment]
I seem to be getting this also with 0.38.2, Xcode 7.0 (7A220), and when building to a simulator.

**Comment by karthikAdaptavant** [comment]
Delete the Derived data and build it again. worked for me

**Comment by martinmose** [comment]
I can confirm that deleting the "Derived data" works - what @karthikAdaptavant said. You can do it with the following command:
```
rm -rf ~/Library/Developer/Xcode/DerivedData/* 
```

**Comment by karthikAdaptavant** [comment]
we can delete derived data by : 
go to xcode -> windows -> Project -> chose your Project -> Delete Derived Data () - Thats all

**Comment by fitch** [comment]
I can also confirm that deleting derived data solves the issue.

**Comment by rvilches** [comment]
I can also confirm. Delete derived data solves the "Command /bin/sh failed with exit code 23" issue

**Comment by LetterV** [comment]
not work for me ,what a fuck

**Comment by segiddins** [comment]
@LetterV that sort of language is uncalled for

**Comment by banchichen** [comment]
I get the same error, finally I soved it by remove pod 'MWPhotoBrowser', '2.1.2 from Podfile...

**Comment by NagarjunNL** [comment]
@martinmose this worked. This happened when i selected SAFE AREA LAYOUT GUIDE and unchecking it back.
