### ISSUE TITLE
Lint fails with warnings in project

### ISSUE THREAD

**Issue by mickeyreiss** [CocoaPods/CocoaPods#3322]
In 0.35.0, a warning within the project results in a `NOTE` output in the results of `pod lib lint`. In 0.36.0, however, the result is a `WARNING` which causes the lint to fail.

I didn't see this change documented in the changelog and it was unexpected for me. Was this change intentional?

**Comment by segiddins** [comment]
Yes, this change was intentionally made in https://github.com/CocoaPods/CocoaPods/pull/2978.

**Comment by mickeyreiss** [comment]
OK. Thanks for the link. This change was backwards incompatible and broke our release script. We will find a workaround.

For the record, we are [intentionally producing a warning](https://github.com/braintree/braintree_ios/blob/56b4bb2985b6681cbce5a88f234e42b4a4d23c37/Braintree/3D-Secure/%40Public/BTThreeDSecure.h#L1) to indicate that a certain piece of functionality is in a public beta. I don't personally consider this a quality issue.

**Comment by intelliot** [comment]
I think we're going to use `pod lib lint --allow-warnings` as a workaround.

**Comment by segiddins** [comment]
Since a user might very well have `-Werror` enabled, a pod with warnings could be unable to compile.
