### ISSUE TITLE
Case sensitivity check for `pod spec lint` is easily subverted on case insensitive systems

### ISSUE THREAD

**Issue by gfontenot** [CocoaPods/CocoaPods#3325]
it looks like `pod spec lint` uses the name of the podspec passed on the command line, instead of checking the name of the file on disk. This means that on case insensitive systems, changing the case of the CLI argument will allow you to subvert the case sensitivity check in the linting command.

(Note that I never renamed the file in the screenshot below)
![image 2015-03-27 at 14-48-34](https://cloud.githubusercontent.com/assets/124499/6874959/a9441790-d491-11e4-89bf-0ace8be7f6c0.png)

**Comment by segiddins** [comment]
Well, this is a tricky one. It's kinda possible to still check on HFS+, because even in case-insensitive mode, it's case-preserving, but otherwise there's really no way to fix this on a generic case-insensitive FS.

**Comment by segiddins** [comment]
I'm closing this as non-actionable.
