### ISSUE TITLE
 Unknown option character `X' in: -Xlinker.

### ISSUE THREAD

**Issue by asotog** [CocoaPods/CocoaPods#3326]
Have a swift project using pods (initially only objective-c pods dependencies, building fine), so i needed to add a swift pod dependency and got "Unknown option character `X' in: -Xlinker." on project build, reading issues history found that use_frameworks!  is required on pod  file when using swift dependencies (so added that to pods file and now linker errors gone) but now the rests of libraries began to complain, for example in bridging header, multiple "file not found" (#import "MBProgressHUD.h" ... ..) errors came, and so on,

Thanks in advance

**Comment by neonichu** [comment]
Please take a look at our [contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#bug-reports) on how to file an actionable bug report. You have given us almost zero to work with here.
