### ISSUE TITLE
Pod was working in 0.36.0 but will no longer build in 0.36.1 (in RubyMotion project)

### ISSUE THREAD

**Issue by matthewsinclair** [CocoaPods/CocoaPods#3329]
I have a very simple Pod (https://github.com/tillless/bcscanner) that was working perfectly fine with a RubyMotion project on Cocoapods version 0.36.0, but ever since the upgrade to 0.36.1, the Pod will no longer be included in the build for compilation and linking.

Running `bundle exec rake pod:install` works without incident, and the `vendor/Pods` directory contains all of the pods specified in the `Rakefile`. However, when I build the project, the only pod that does _not_ end up in the `vendor/build/Pods.build/Release-iphonesimulator` is my pod. 

And then of course, when my app starts up, it promptly fails with a unresolved link error because the Obj-C class specified in my pod is not found. This is not surprising because I can see from the output of the build that the `.h` and `.m` files for my pod have not been compiled. Each pod mentioned in my rake file has a `Build ./Pods.xcodeproj [<podname> - Release]`entry in the build output, except for my pod. 

As I said, this was working perfectly well with 0.36.0, so I'm pretty sure I haven't done anything on my side. Has something changed in the way a pod is setup between 0.36.0 and 0.36.1? I have run the cocoapods linter over the spec, and it came up error free.

This is a show-stopper for me at the moment, so any help would be much appreciated.

**Comment by matthewsinclair** [comment]
Update: I've gone back and checked this with `0.36.0` and it still doesn't work, so it's almost certainly not something that is wrong with Cocoapods specifically, but the interplay between it, motion-cocoapods and something wrong with my podspec.

**Comment by matthewsinclair** [comment]
I have also raised the same issue in `motion-cocoapods` here: https://github.com/HipByte/motion-cocoapods/issues/112

**Comment by matthewsinclair** [comment]
On further investigation, it looks like it's not 0.36.0 / 0.36.1 related. But perhaps happening somewhere in the recent upgrade of motion-cocoapods or maybe even RubyMotion. It may even go back to a pre-0.36 version of Cocapods and it was working simply because I had not ever completely removed the `vendor/` directory up until very recently.

The odd thing is that 5 or 6 other pods are working perfectly, and the only difference is that my pod is coming from a non-Cocoapods repo. I didn't want to push my stuff into the Cocoapods master repo until I had it working, and so it's currently coming in from a `:git` reference in my RubyMotion `Rakefile` like this:

```
  app.pods do
    pod 'GoogleAnalytics-iOS-SDK'
    pod 'AFNetworking', '~> 1.3.4'
    pod 'RestKit'
    pod 'NSData+MD5Digest'
    pod 'NSData+Base64'
    pod 'SVProgressHUD'
    pod 'JMImageCache'
    pod 'TSMessages'
    pod 'ABPadLockScreen'
    pod 'SVGKit'
    pod 'CardIO'
    pod 'TilllessBCScanner', :git => 'git@github.com:tillless/bcscanner.git'
  end
```

I get no issues when I `lint` the podspec, and I get no compiler or linker errors when building. However, the one problem is that there is no entry in the build directory for my pod, and I can see during the compilation process that the source code in my pod is never compiled. 

I have subsequently vendored the class and header files from the pod directly into my project using this `app.vendor_project("vendor/tillless-bcscanner", :static)`, which works without a hitch. 

Is there some way to debug the Cocoapods build and compilation process so that I can see what is happening when it processes my pod?

**Comment by segiddins** [comment]
Can you reproduce the issues when using that Podfile normally, out of a RubyMotion project?

**Comment by matthewsinclair** [comment]
That's a good question, and no, I haven't tried that. I've never built anything using Cocoapods that _wasn't_ RubyMotion ...

**Comment by matthewsinclair** [comment]
Running `rake pod:install` with `COCOAPODS_VERBOSE=1` turned on, gives me a detailed list of the output of the `rake pod:install` command, and I have put it into a Gist here: https://gist.github.com/matthewsinclair/f52d60b9fe2400d9c70f

If you search for "Installing TilllessBCScanner" you can see that it is the only pod that doesn't have any download info. Is this expected behaviour for a non-master / private pod? if so, then it's not the problem, but if not, then it's probably pointing towards the cause of the issue.

**Comment by matthewsinclair** [comment]
Oh, just noticed re-reading that gist that the download of the private pod happens right at the top in the "Fetching external sources" section, so the pod code has definitely been downloaded. It's just not compiling for some reason. Argh.

**Comment by matthewsinclair** [comment]
And right on cue. I just loaded the Pod.xcodeprj into XCode and sure enough (thanks @willrax who suggested to me today "are you sure that all of your pods are compiling properly?") there was an error in the `SVGKit` pod. And for whatever reason, no other pod _after_ that was being properly compiled. 

This error in `SVGKit` has only come about since the upgrade to the latest Xcode (6.2) and RubyMotion (3.8). 

Possibly Cocoapods could do with some better error checking in this case? :)

**Comment by neonichu** [comment]
CocoaPods doesn't compile the Pods, so I think the better error checking needs to be done in motion-cocoapods.

**Comment by matthewsinclair** [comment]
Yep, good point. I've posted the same issue on that project as well.
