### ISSUE TITLE
Trunk verify error

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/CocoaPods#3331]
I am trying to verify an email address by following a link to:

 > https://trunk.cocoapods.org/sessions/verify/[REDACTED]

This produces the error:

 > Application Error
 > An error occurred in the application and your page could not be served. Please try again in a few moments.
 > If you are the application owner, check your logs for details.

**Comment by kylef** [comment]
This has been verified now. There was/are some issues related to GitHub being intermittently down (https://status.github.com).
