### ISSUE TITLE
Error - Undefined symbols for architecture arm64: (While building on Xcode 6.2). Please help.

### ISSUE THREAD

**Issue by adongarwar** [CocoaPods/CocoaPods#3335]
I get following errors while compiling after doing pod install -
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RKMappingResult", referenced from:
      l_OBJC_$_CATEGORY_RKMappingResult_$_QCAdditions in RKMappingResult+QCAdditions.o
  "_OBJC_METACLASS_$_RKObjectManager", referenced from:
      _OBJC_METACLASS_$_QCRestObjectManager in QCRestObjectManager.o
  "_OBJC_CLASS_$_RKObjectManager", referenced from:
      objc-class-ref in QCNetworking.o
      _OBJC_CLASS_$_QCRestObjectManager in QCRestObjectManager.o
  "_OBJC_CLASS_$_RKValueTransformer", referenced from:
```

 Configurations in core.xcconfig -
```
ARCHS = $(ARCHS_STANDARD_INCLUDING_64_BIT)

SDKROOT = iphoneos8.2
TARGETED_DEVICE_FAMILY = 1,2
IPHONEOS_DEPLOYMENT_TARGET = 7.1
VALID_ARCHS = armv7 armv7s arm64
```

Config in Podfile - 
```
platform :ios, '7.1'
inhibit_all_warnings!
post_install do |installer_representation|

    installer_representation.project.targets.each do |target|

        target.build_configurations.each do |config|

            config.build_settings['SDKROOT'] = 'iphoneos8.2'

            config.build_settings['ARCHS'] = "$(ARCHS_STANDARD_INCLUDING_64_BIT)"

            #"armv7 armv7s arm64"

            config.build_settings['VALID_ARCHS'] = "armv7 armv7s arm64"

        end

    end

    

    require 'fileutils'

    FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-Acknowledgements.plist', ’Something/Settings.bundle/Acknowledgements.plist', :remove_destination => true)

end
```

**Comment by kylef** [comment]
@adongarwar You have absolutely no pods in your Podfile? It doesn't seem to be possible for you to get such an error if this is the case.

Please include full details to reproduce your problem and take a look at out [contributing guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) which mentions the kind of information we need for bug reports.

**Comment by adongarwar** [comment]
That's correct.  I thought it's pretty much understood. If information on what pods i use is necessary, here is the info -
platform :ios, '7.1'
inhibit_all_warnings!

xcodeproj "Something/Something.xcodeproj"

pod 'KSReachability'
pod 'MBProgressHUD'
pod 'HPGrowingTextView'
pod 'RestKit/Network'
pod 'RestKit/ObjectMapping'
pod 'TPKeyboardAvoiding'
pod 'MMDrawerController'
pod 'RETableViewManager'
pod 'SwipeView'
pod 'SocketRocket'
pod 'Block-KVO'
pod 'WYPopoverController'
pod 'SZTextView'
pod 'RequestUtils'
pod 'LibComponentLogging-Core'
pod 'LibComponentLogging-LogFile'
pod 'LibComponentLogging-qlog'
pod 'LibComponentLogging-pods'
pod 'DLWidgetMenu', :git => 'https://github.com/regexident/DLWidgetMenu'

pod 'LUKeychainAccess'
pod 'FPPopover'



post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SDKROOT'] = 'iphoneos8.2'
            config.build_settings['ARCHS'] = "$(ARCHS_STANDARD_INCLUDING_64_BIT)"
            #"armv7 armv7s arm64"
            config.build_settings['VALID_ARCHS'] = "armv7 armv7s arm64"
        end
    end
    
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-Acknowledgements.plist', 'Something/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end

**Comment by adongarwar** [comment]
My xcconfig file is as follows -


#include "../../Pods/Target Support Files/Pods/Pods.release.xcconfig"

PRODUCT_NAME = Something

BUNDLE_IDENTIFIER = com.careinsync.Something.enterprise.devbr
PRODUCT_NAME = Test

VERSIONVALUE = 6.01


INFOPLIST_FILE = Something-Info.plist

ARCHS = $(ARCHS_STANDARD_INCLUDING_64_BIT)

SDKROOT = iphoneos8.2
TARGETED_DEVICE_FAMILY = 1,2
IPHONEOS_DEPLOYMENT_TARGET = 7.1

CLANG_ENABLE_MODULES = YES

VALID_ARCHS =  arm64

CLANG_ENABLE_OBJC_ARC = YES

GCC_VERSION = 

GCC_THUMB_SUPPORT = NO

// Needed for unit tests. TODO verify it is ok for shipped bits.
GCC_SYMBOLS_PRIVATE_EXTERN = NO

GCC_C_LANGUAGE_STANDARD = c99
OTHER_CFLAGS = ${OTHER_CFLAGS} -DNS_BLOCK_ASSERTIONS=1

THIRDPARTYROOT = $(SRCROOT)/../3rdParty

FRAMEWORK_SEARCH_PATHS = $(FRAMEWORK_SEARCH_PATHS) "/Library/Frameworks" $(THIRDPARTYROOT) $(PROJECT_DIR)/Frameworks

LIBRARY_SEARCH_PATHS = $(LIBRARY_SEARCH_PATHS) $(SRCROOT) $(PROJECT_DIR)/Frameworks

OTHER_LDFLAGS = ${inherited} $(OTHER_LDFLAGS) -ObjC -all_load

ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage

ALWAYS_SEARCH_USER_PATHS = NO

GCC_PRECOMPILE_PREFIX_HEADER = YES
GCC_PREFIX_HEADER = Something_Prefix.pch

DEBUG_INFORMATION_FORMAT = dwarf-with-dsym


GCC_WARN_CHECK_SWITCH_STATEMENTS = YES
GCC_WARN_SHADOW = YES
GCC_WARN_64_TO_32_BIT_CONVERSION = YES
GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED = YES
GCC_WARN_ABOUT_RETURN_TYPE = YES
GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS = YES
GCC_WARN_SIGN_COMPARE = YES
GCC_WARN_STRICT_SELECTOR_MATCH = missing value
GCC_WARN_TYPECHECK_CALLS_TO_PRINTF = YES
GCC_WARN_UNDECLARED_SELECTOR = YES
GCC_WARN_UNUSED_FUNCTION = YES
GCC_WARN_UNUSED_LABEL = YES
GCC_WARN_UNUSED_VALUE = YES
GCC_WARN_UNUSED_VARIABLE = YES
GCC_TREAT_WARNINGS_AS_ERRORS = YES
GCC_WARN_MISSING_PARENTHESES = YES
GCC_WARN_UNINITIALIZED_AUTOS = YES
GCC_WARN_ABOUT_RETURN_TYPE = YES
CLANG_WARN_CONSTANT_CONVERSION = YES
CLANG_WARN_ENUM_CONVERSION = YES
CLANG_WARN_INT_CONVERSION = YES
CLANG_WARN_EMPTY_BODY = YES
GCC_WARN_ABOUT_MISSING_NEWLINE = NO

RUN_CLANG_STATIC_ANALYZER = YES
VALIDATE_PRODUCT = YES

PREBINDING = NO

GCC_OPTIMIZATION_LEVEL = 0

**Comment by kylef** [comment]
I created an example project using this xcconfig file and your Podfile and this error is due to the fact you are overriding `OTHER_LDFLAGS` in your config file. If you remove this line, or make it include all your pods it would work:

```
-l"Pods-AFNetworking" -l"Pods-BFPaperCheckbox" -l"Pods-Bolts" -l"Pods-CocoaLumberjack" -l"Pods-Facebook-iOS-SDK" -l"Pods-MHPrettyDate" -l"Pods-RestKit" -l"Pods-SDWebImage" -l"Pods-SOCKit" -l"Pods-SVProgressHUD" -l"Pods-TPKeyboardAvoiding" -l"Pods-TransitionKit" -l"Pods-UIAlertView-Blocks" -l"Pods-UIColor+BFPaperColors" -framework "CFNetwork" -framework "CoreData" -framework "CoreGraphics" -framework "Foundation" -framework "ImageIO" -framework "MobileCoreServices" -framework "QuartzCore" -framework "Security" -framework "SystemConfiguration" -weak_framework "Accounts" -weak_framework "AudioToolbox" -weak_framework "CoreGraphics" -weak_framework "CoreLocation" -weak_framework "Foundation" -weak_framework "QuartzCore" -weak_framework "Security" -weak_framework "Social" -weak_framework "UIKit"
```

```
OTHER_LDFLAGS = ${inherited} $(OTHER_LDFLAGS) -ObjC -all_load
```

There may also be other issues to to overiding other flags such as `LIBRARY_SEARCH_PATHS` etc.

**Comment by adongarwar** [comment]
Thanks. Commenting out OTHER_LDFLAGS resolved the issue. But still want to figure out, what can be the impact of doing so?
