### ISSUE TITLE
use_frameworks Compile Issues

### ISSUE THREAD

**Issue by fabb** [CocoaPods/CocoaPods#3338]
I have a mixed Objective-C/Swift project and activated use_frameworks! for the unit test target only. The unit test target does not compile though, when one of the test classes #imports a header from the app target, and that header #imports a header from a pod that is only activated for the app target. Without use_frameworks! it works fine.

I used cocoapods 0.36.1

Example project: https://github.com/fabb/UseFrameworksTest

**Comment by webventil** [comment]
I have a similar problem. I am using mixed Objective-C pods in my project. After adding a Swift project and adding the `use_frameworks!` option, the app compiles, but than crashes when calling the first method of an Objective-C Framework.  

Cocoapods: 0.36.3

**Comment by segiddins** [comment]
When using `use_frameworks!`, you should probably be using `@import` in your Objective-C code?

**Comment by webventil** [comment]
I have a Swift only project... When I am using `use_frameworks!`I have to import each framework `import frameworkName`. But unfortunately it does not work. I uploaded a sample project. The call on the swift library works. The call on the Objective-C library not.

Example Project:
https://github.com/webventil/CocoapodFrameworkTest

**Comment by neonichu** [comment]
@webventil your problem seems to be very specific to the used pod, see <https://github.com/sweetmandm/ionicons-iOS#installation-step-2>

**Comment by webventil** [comment]
You are right. I'm so sorry :-) Thank you!

**Comment by allanmacatingrao** [comment]
How to use_frameworks! to only one library:

Example:
target :'MyApp' do
use_frameworks!
pod 'AFNetworking', '~> 2.0'

#don't use framework from here:
pod ...
pod ...
end

**Comment by fabb** [comment]
I have updated the example project to 0.37.1, the problem still persists.

**Comment by captainchung** [comment]
I have a sample project with what seems like related issues. my podfile has 1 framework and several non framework files. i am using the Podfile format as described by @allanmacatingrao . What is happening to me is I am getting compile errors from my non-framework files and I am pretty confused as to why.  https://github.com/captainchung/PodFrameworkExample

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
