### ISSUE TITLE
Cant get rid of warnings missing file, “Missing File” while building in Xcode

### ISSUE THREAD

**Issue by adongarwar** [CocoaPods/CocoaPods#3341]
I did a pod install with Xcode 6 and cocoapods-0.36.1 and started getting warnings. Please find more information about warnings in attached screenshot. 

![screen shot 2015-03-30 at 11 48 49 pm](https://cloud.githubusercontent.com/assets/4019449/6921182/04c5929a-d778-11e4-89ab-a9f9800cf50a.png)

My xcconfig file is as follows -

```
#include "../../Pods/Target Support Files/Pods/Pods.release.xcconfig"

PRODUCT_NAME = Something

BUNDLE_IDENTIFIER = com.Something.Something.enterprise.devbr
PRODUCT_NAME = Test

VERSIONVALUE = 6.01

INFOPLIST_FILE = Something-Info.plist

ARCHS = $(ARCHS_STANDARD_INCLUDING_64_BIT)

SDKROOT = iphoneos8.2
TARGETED_DEVICE_FAMILY = 1,2
IPHONEOS_DEPLOYMENT_TARGET = 7.1

CLANG_ENABLE_MODULES = YES

VALID_ARCHS = arm64

CLANG_ENABLE_OBJC_ARC = YES

GCC_VERSION =

GCC_THUMB_SUPPORT = NO

// Needed for unit tests. TODO verify it is ok for shipped bits.
GCC_SYMBOLS_PRIVATE_EXTERN = NO

GCC_C_LANGUAGE_STANDARD = c99
OTHER_CFLAGS = ${OTHER_CFLAGS} -DNS_BLOCK_ASSERTIONS=1

THIRDPARTYROOT = $(SRCROOT)/../3rdParty

FRAMEWORK_SEARCH_PATHS = $(FRAMEWORK_SEARCH_PATHS) "/Library/Frameworks" $(THIRDPARTYROOT) $(PROJECT_DIR)/Frameworks

LIBRARY_SEARCH_PATHS = $(LIBRARY_SEARCH_PATHS) $(SRCROOT) $(PROJECT_DIR)/Frameworks

OTHER_LDFLAGS = ${inherited} $(OTHER_LDFLAGS) -ObjC -all_load

ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon
ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME = LaunchImage

ALWAYS_SEARCH_USER_PATHS = NO

GCC_PRECOMPILE_PREFIX_HEADER = YES
GCC_PREFIX_HEADER = Something_Prefix.pch

DEBUG_INFORMATION_FORMAT = dwarf-with-dsym

GCC_WARN_CHECK_SWITCH_STATEMENTS = YES
GCC_WARN_SHADOW = YES
GCC_WARN_64_TO_32_BIT_CONVERSION = YES
GCC_WARN_INITIALIZER_NOT_FULLY_BRACKETED = YES
GCC_WARN_ABOUT_RETURN_TYPE = YES
GCC_WARN_ABOUT_MISSING_FIELD_INITIALIZERS = YES
GCC_WARN_SIGN_COMPARE = YES
GCC_WARN_STRICT_SELECTOR_MATCH = missing value
GCC_WARN_TYPECHECK_CALLS_TO_PRINTF = YES
GCC_WARN_UNDECLARED_SELECTOR = YES
GCC_WARN_UNUSED_FUNCTION = YES
GCC_WARN_UNUSED_LABEL = YES
GCC_WARN_UNUSED_VALUE = YES
GCC_WARN_UNUSED_VARIABLE = YES
GCC_TREAT_WARNINGS_AS_ERRORS = YES
GCC_WARN_MISSING_PARENTHESES = YES
GCC_WARN_UNINITIALIZED_AUTOS = YES
GCC_WARN_ABOUT_RETURN_TYPE = YES
CLANG_WARN_CONSTANT_CONVERSION = YES
CLANG_WARN_ENUM_CONVERSION = YES
CLANG_WARN_INT_CONVERSION = YES
CLANG_WARN_EMPTY_BODY = YES
GCC_WARN_ABOUT_MISSING_NEWLINE = NO

RUN_CLANG_STATIC_ANALYZER = YES
VALIDATE_PRODUCT = YES

PREBINDING = NO

GCC_OPTIMIZATION_LEVEL = 0
```

podfile looks like -

```ruby
platform :ios, '7.1'
inhibit_all_warnings!

xcodeproj "Something/Something.xcodeproj"

pod 'KSReachability'
pod 'MBProgressHUD'
pod 'HPGrowingTextView'
pod 'RestKit/Network'
pod 'RestKit/ObjectMapping'
pod 'TPKeyboardAvoiding'
pod 'MMDrawerController'
pod 'RETableViewManager'
pod 'SwipeView'
pod 'SocketRocket'
pod 'Block-KVO'
pod 'WYPopoverController'
pod 'SZTextView'
pod 'RequestUtils'
pod 'LibComponentLogging-Core'
pod 'LibComponentLogging-LogFile'
pod 'LibComponentLogging-qlog'
pod 'LibComponentLogging-pods'
pod 'DLWidgetMenu', :git => 'https://github.com/regexident/DLWidgetMenu'

pod 'LUKeychainAccess'
pod 'FPPopover'



post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SDKROOT'] = 'iphoneos8.2'
            config.build_settings['ARCHS'] = "$(ARCHS_STANDARD_INCLUDING_64_BIT)"
            #"armv7 armv7s arm64"
            config.build_settings['VALID_ARCHS'] = "armv7 armv7s arm64"
        end
    end

    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods/Pods-Acknowledgements.plist', 'Something/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
```

**Comment by segiddins** [comment]
Have you tried closing and reaping your workspace?

**Comment by adongarwar** [comment]
I did quit Xcode, opened again, performed a clean and tried building. Does not work. Is there something else i should try?

**Comment by adongarwar** [comment]
Other things i already tried are-
1) Setting User Header search paths to "$(BUILT_PRODUCTS_DIR)" and making it recursive-non-recursive.
2) Deleting derived data folder.

None of these worked.

**Comment by neonichu** [comment]
These warnings are not build warnings, they are about your SVN repository. It is correct that the directories shown no longer exist, CocoaPods stores the headers in Pods/Headers/{Private,Public} now. You have to update your working copy to reflect those changes.

**Comment by adongarwar** [comment]
So u mean, committing this should resolve the warnings.

**Comment by neonichu** [comment]
Yep.

**Comment by chriszhang4213** [comment]
thanks! that is really help me also

**Comment by n13** [comment]
FWIW - this also happens with git. 

Deleting CocoaPods creates these warnings. Checking all changes into git removes the warnings.

So this is basically a bug in Xcode 8.

**Comment by AaoIi** [comment]
It happen with me after i removed GooglePlaces from pod on Xcode 8 where it happened after executing pod update.

But what might fix it is to update project settings (it will be suggested for the first time you open your project in Xcode 8). and also do clean, clean cache modules,derived data.

Hope it helps.

**Comment by mitesh-mobedig** [comment]
Thanks @neonichu committing code removed those warning

**Comment by AT5Hack** [comment]
I had to also delete my derived data after the commit to make the warnings disappear.

**Comment by hlung** [comment]
Seems like I need to actually "commit" all the file changes to git after deleting pod. I build again (without cleaning), now those warnings are gone. :)

**Comment by TeamWe** [comment]
in terminal.
`cd yourProject/Pods`
then
`sudo find . -type d -name .svn | xargs rm -rf`
remove all svn files.everything will be ok.

**Comment by singlag1993** [comment]
Try this and all the warnings will be gone.

Disable source control
Xcode -> Preferences -> Source Control -> uncheck (Enable Source Control)

In this case you won't be able to use Source Control provided by Xcode environment.
