### ISSUE TITLE
Pods project "Update to recommended settings" Xcode warning

### ISSUE THREAD

**Issue by gregcotten** [CocoaPods/CocoaPods#3342]
Running 0.36.1 here Xcode 6.2. After a successful pod install Xcode wants me to "Combine High Resolution Artwork" for all of the Targets inside the Pods project. What gives?

**Comment by gregcotten** [comment]
Looks a lot like #508

**Comment by segiddins** [comment]
What Xcode version are you running? What's in your Podfile? Can you give us a reproduction script?

**Comment by gregcotten** [comment]
@segiddins So sorry - I thought I wrote Xcode 6.2. Podfile below:

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '10.9'

workspace 'Lattice'

target :Lattice, :exclusive => true do
  pod 'CocoaLUT'
  pod 'VVSceneLinearImageRep'
  pod "AFNetworking", "~> 2.0"
  pod 'DCOAboutWindow'
  pod 'oiiococoa'
  pod 'VVLUT1DFilter'
  pod 'FXKeychain'
  pod 'NSString-Hashes'
  pod 'AFDownloadRequestOperation'
  pod 'UnzipKit'
  pod 'RandomSequence'
  pod 'UAObfuscatedString'
  xcodeproj 'Lattice.xcodeproj'
end

target :LatticeQuickLook, :exclusive => true do
  pod 'CocoaLUT', path: '../CocoaLUT'
  pod 'oiiococoa', path: '../oiiococoa'
  pod 'VVLUT1DFilter'
  xcodeproj 'LatticeQuickLook/LatticeQuickLook.xcodeproj'
end

**Comment by segiddins** [comment]
For the record, this is what I'm seeing. @mrackwitz @neonichu, do we need to update the project settings in Xcodeproj at all?

![screenshot 2015-03-31 15 22 30](https://cloud.githubusercontent.com/assets/1946610/6930639/ead5ec58-d7b9-11e4-95f6-a66b5ba83d48.png)

**Comment by neonichu** [comment]
Possibly, I'm wondering if this will go away once we merge CocoaPods/Xcodeproj#253, because Xcode will then assume the project has already been checked.

**Comment by neonichu** [comment]
So, it is indeed the case that when `LastUpgradeCheck` is >= the Xcode version being used, this dialog will never come up, regardless of the "recommended" settings are being used for the project.

**Comment by 0xced** [comment]
I just stumbled on this problem too. You can easily reproduce it on 0xced/XCDYouTubeKit@ad45bbe083e4c477da92352e96d189228c19bbc7:
* Add this Podfile inside the `XCDYouTubeKit Demo` directory
```ruby
xcodeproj 'XCDYouTubeKit Demo.xcodeproj'
workspace '../XCDYouTubeKit Demo.xcworkspace'

def import_pods
  pod 'CocoaLumberjack', '~> 2.0.0'
end

target 'XCDYouTubeKit iOS Demo' do
  platform :ios, '5.0'
  import_pods
end

target 'XCDYouTubeKit OS X Demo' do
  platform :osx, '10.7'
  import_pods
end
```
* Run `pod install` (version 0.37.1)
* Open `XCDYouTubeKit Demo.xcworkspace` (with Xcode 6.2)

Now Pods.xcodeproj has a *Validate Project Settings* warning asking to enable "Combine High Resolution Artwork".

I wonder if this happens because of the mixed iOS / OS X nature of this project.

**Comment by neonichu** [comment]
@0xced hm, this doesn't appear to happen for me, using the same versions of tools.

What result do you get when running:

```bash
grep LastUpgradeCheck Pods/Pods.xcodeproj/project.pbxproj
```

**Comment by 0xced** [comment]
I get `0640`.

And now sometimes I can reproduce this warning and sometimes I can’t. I tried different combinations of deleting derived data and/or quitting Xcode but I can't find a reliable way to reproduce this issue!

**Comment by 0xced** [comment]
I found a way to reproduce this!

1. Open `XCDYouTubeKit Demo.xcworkspace` in Xcode 6.1.1
2. Quit Xcode
3. Open `XCDYouTubeKit Demo.xcworkspace` in Xcode 6.2, the warning is back!

**Comment by mrackwitz** [comment]
@0xced: Does the value for `LastUpgradeCheck` change in between?

**Comment by 0xced** [comment]
No, it only changes when I apply the recommended Xcode settings.

**Comment by segiddins** [comment]
Closing as not reproducible.

**Comment by gregcotten** [comment]
@segiddins

Seems a bit rash to close! Still reproducible for me! And it seems like others can as well.

**Comment by segiddins** [comment]
@gregcotten we've since updated the constants in the latest version of Xcodeproj.
