### ISSUE TITLE
Provide a better error explanation when a pod only has prerelease versions

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#3348]
:rainbow: 

Consider the following Podfile:

```ruby
platform :ios, '7.0'
pod 'GoogleAds-IMA-iOS-SDK-For-AdMob'
```

This results in the following:

```
$ pod install
[!] Unable to satisfy the following requirements:

- 'GoogleAds-IMA-iOS-SDK-For-AdMob' required by 'Podfile'
```

The reason for it not being satisfiable is that currently there are only prerelease versions of this pod and the Podfile does’t indicate that prerelease versions are acceptable. Changing to the following does work:

```ruby
pod 'GoogleAds-IMA-iOS-SDK-For-AdMob', '> 3.0.beta.0'
```

In the case where a pod does exist, but none can be activated because they’re all prelease versions, CocoaPods should print an error like:

> Unable to activate any GoogleAds-IMA-iOS-SDK-For-AdMob version, because there are only prerelease versions available: 3.0.beta.5, 3.0.beta.6, 3.0.beta.7, 3.0.beta.8, 3.0.beta.9, 3.0.beta.10, 3.0.beta.11, and 3.0.beta.12.
>
> To be able to use any of these versions, your Podfile should indicate that a prerelease version is acceptable, e.g.:
>
>     pod 'GoogleAds-IMA-iOS-SDK-For-AdMob', '>= 3.0.beta.12'

/cc @AliSoftware @segiddins

**Comment by AliSoftware** [comment]
:+1: /cc @ikiki

**Comment by kylef** [comment]
Just also to point out, this error could also come from a pod's dependencies, example `MIHCrypto` depends on `OpenSSL-Universal`.

**Comment by segiddins** [comment]
I believe this has already been done.
