### ISSUE TITLE
Build Failed with 'Failure Reason: File name too long' when 'Copy Pods Resources' in 0.36.x.

### ISSUE THREAD

**Issue by PeterWang0124** [CocoaPods/CocoaPods#3350]
Hi, in my team project, we have a new member in. He `pod update` the project and build it, then got the error, so I try to do again got the same error of below:
> ...
sent 12960 bytes  received 578 bytes  27076.00 bytes/sec
total size is 10522  speedup is 0.78  
>  /* com.apple.actool.errors */
: error: Failed to read file attributes for "/Users/PeterWang/mart-ios/Mart/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Alamofire/Example/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Curly/CurlySample/CurlySample/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Moya/Demo/Demo/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Promissum/examples/FadeExample/FadeExample/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Promissum/extensions/Alamofire/Example/Images.xcassets /Users/PeterWang/mart-ios/Vendor/RHMVVMHelpers/RHMVVMHelpers/Images.xcassets /Users/PeterWang/mart-ios/Vendor/RSBarcodes/RSBarcodesSample/RSBarcodesSample/Images.xcassets /Users/PeterWang/mart-ios/Vendor/SimpleAlert/SimpleAlertExample/SimpleAlertExample/Images.xcassets /Users/PeterWang/mart-ios/Vendor/SLPagingViewSwift/Demos/TinderLike/TinderLike/Images.xcassets /Users/PeterWang/mart-ios/Vendor/SLPagingViewSwift/Demos/TwitterLike/TwitterLike/Images.xcassets /Users/PeterWang/mart-ios/Vendor/SwiftyJSON/Example/Images.xcassets /Users/PeterWang/mart-ios/Vendor/XCGLogger/XCGLogger/Demo"  
>      Failure Reason: File name too long  
> /* com.apple.actool.notices */
: warning: Failed to read file attributes for "/Users/PeterWang/mart-ios/Mart/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Alamofire/Example/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Curly/CurlySample/CurlySample/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Moya/Demo/Demo/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Promissum/examples/FadeExample/FadeExample/Images.xcassets /Users/PeterWang/mart-ios/Vendor/Promissum/extensions/Alamofire/Example/Images.xcassets /Users/PeterWang/mart-ios/Vendor/RHMVVMHelpers/RHMVVMHelpers/Images.xcassets /Users/PeterWang/mart-ios/Vendor/RSBarcodes/RSBarcodesSample/RSBarcodesSample/Images.xcassets /Users/PeterWang/mart-ios/Vendor/SimpleAlert/SimpleAlertExample/SimpleAlertExample/Images.xcassets /Users/PeterWang/mart-ios/Vendor/SLPagingViewSwift/Demos/TinderLike/TinderLike/Images.xcassets /Users/PeterWang/mart-ios/Vendor/SLPagingViewSwift/Demos/TwitterLike/TwitterLike/Images.xcassets /Users/PeterWang/mart-ios/Vendor/SwiftyJSON/Example/Images.xcassets /Users/PeterWang/mart-ios/Vendor/XCGLogger/XCGLogger/Demo"  
    Failure Reason: File name too long  
/* com.apple.actool.compilation-results */
/Users/PeterWang/Library/Developer/Xcode/DerivedData/Mart-adxfewucewqguhhjalskbnyynmdb/Build/Products/Debug-iphoneos/Mart.app/Assets.car

I go back to the old version, found out there no problem in 0.35.x. And I compare the 'Pods-resources.sh' found a little different at the last part of the shell.
In 0.35.x:  
```  
find "${PWD}" -name "*.xcassets" -print0 | xargs -0 actool --output-format human-readable-text --notices --warnings --platform "${PLATFORM_NAME}" --minimum-deployment-target "${IPHONEOS_DEPLOYMENT_TARGET}" ${TARGET_DEVICE_ARGS} --compress-pngs --compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"  
```  
In 0.36.x:  
```  
while read line; do XCASSET_FILES="$XCASSET_FILES '$line'"; done <<<$(find "$PWD" -name "*.xcassets" | egrep -v "^$PODS_ROOT")
  echo $XCASSET_FILES | xargs actool --output-format human-readable-text --notices --warnings --platform "${PLATFORM_NAME}" --minimum-deployment-target "${IPHONEOS_DEPLOYMENT_TARGET}" ${TARGET_DEVICE_ARGS} --compress-pngs --compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"  
```  
I think it would read all the xcasset files in one command line and cause the issue.
Our project is swift/objective-c mixed project, and target iOS 7 and up.

Thanks ~

**Comment by segiddins** [comment]
It looks to me like that string is over-quoted? @AliSoftware ?

**Comment by AliSoftware** [comment]
Yeah some people changed it recently, IIRC there was a bug in 0.36.2 with quotes that got worked-around in 0.36.3.
That `Pods-resources.sh` script will disappear eventually when #3263 gets merged so I won't spend much time trying to fix that script.

@PeterWang0124 could you test your `Podfile` against my CocoaPods's `ali-xcassets-1546` branch and tell if it solved your problem? ([instructions here](https://github.com/CocoaPods/CocoaPods/pull/3263#issuecomment-88965154)) That would help me ensure my branch is ready to ship and provide a better solution for the next CP release.

**Comment by PeterWang0124** [comment]
Thanks~  I will test it now.

**Comment by PeterWang0124** [comment]
After testing, it don't get any errors. Now, it works well in my team project. If there will any problems, I will report it as soon as passible.

Thank you ~
Thanks CocoaPods makes project easy to manage third-party libraries. ^_^

**Comment by AliSoftware** [comment]
Thanks for the feedback!

I'm actually surprised that `pod update` worked, as as far as I understand `bundler` I would I thought that you needed to `bundle exec pod update` to ensure using the locally installed version instead of the system-installed one?

Otherwise thanks for the test, that's promising for my PR :)

**Comment by PeterWang0124** [comment]
Actually, I'm surprised, too. 
After my friend told me that I'm wrong with using `bundler`.
And I test it again (use `bundle exec pod update`), it still work well.

Thanks ~ :)

**Comment by kylef** [comment]
@PeterWang0124 Is this still a problem for you in either 0.36.4 or 0.37.1? I have a feeling https://github.com/CocoaPods/CocoaPods/commit/fdf80d2447740c330cb4ab38f6dbe8ff7039be6e may have fixed this one.

**Comment by PeterWang0124** [comment]
Sorry for responding such late.
There are no problem in 0.36.4 or 0.37.1.
Still work very well.

Thank~  :)

**Comment by fostersanders** [comment]
Well, I had the same problem. 
But then I searched on the internet for a solution and I ran into 

L 
o 
n 
g 


P 
a 
t 
h 

T 
o 
o 
l. 

It´s really effective and you can solve your problem in less than 2 minutes
