### ISSUE TITLE
[Plugins] Provide plugin options as a HashWithIndifferentAccess.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#3354]
Currently it’s too easy to run into issues where a user provides options as symbols and the plugin expects them to be strings or vice-versa. Instead of having the plugin implementers deal with this every time, it’s probably safer to use ActiveSupport’s [HashWithIndifferentAccess](http://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html).

**Comment by segiddins** [comment]
I don't really like `HashWithIndifferentAccess`. It seems to me like it should be up to each plugin to say what sort of options hash it expects.

**Comment by orta** [comment]
its not the plugin, it's that a Podfile could have people writing different syntax, and so every plugin has to accommodate both regardless. May as well just deal with it properly at the source.

**Comment by segiddins** [comment]
The plugin needs to define how it expects its own options to be formatted by the user.

**Comment by orta** [comment]
Eh, that's nice to say, but I don't want my plugin to `exit(0)` because you used strings not symbols in your hash. Every plugin with options would end up supporting both.

**Comment by segiddins** [comment]
My plugins wouldn't ;)

**Comment by orta** [comment]
:palm_tree:
