### ISSUE TITLE
[IntegrationSpec] Add a test to check an incremental installation where a new target is integrated

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#3355]
There was a test `install_multiple_targets_add_target`, which was expected to do this job, but never run.

Assume an installation from a Podfile like this:

``` ruby
target "A" do
   pod "BananaLib"
end
```

The **before** state should be equal to the state after running: `pod install`

After that the Podfile should be extended e.g:

``` diff
target "A" do
   pod "BananaLib"
end

+target "B" do
+   pod "BananaLib"
+end
```

The test should check, that the further target `B` will be correctly integrated after running `pod install` another time.

Ideally the interim state could be composed programmatically from an existing integration spec, so that the before state of the new test can be rebuild using the rake task (`spec:rebuild_integration_fixtures`). Eventually this could happen on runtime of the integration specs or there could be another rake task for that, which would copy e.g. the after state of `install_multiple_targets` to `install_multiple_targets_add_target/before`. In the latter case, this would naturally also run after invoking `rake spec:rebuild_integration_fixtures`.

In addition, here's some free snippet, how the test could be called from integration.rb.

``` ruby
    describe 'Integrate a further target of an installation with multiple target definitions' do
      behaves_like cli_spec 'install_multiple_targets_add_target',
                            'install --no-repo-update'
    end
```

**Comment by segiddins** [comment]
@mrackwitz maybe we could also use this spec to test de-integrating removed targets?
