### ISSUE TITLE
[ali-xcassets-1546 WIP branch] Undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by yorkepb** [CocoaPods/CocoaPods#3356]
### Command

```
/Users/yorkepb/CocoaPods/bin/pod install
```

### Report

* What did you do?

using the branch `ali-xcassets-1546` attempted to run `pod install` (or) `pod update` on my project.

* What did you expect to happen?
excepted the install to complete successfully

* What happened instead?
ended with an error.

### Stack

```
   CocoaPods : 0.36.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.1
        Host : Mac OS X 10.10.2 (14C1514)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5500443895842ff04790dca534bd8168b373a3d8
               nytimes - git@github.com:nytm/ios-podspecs.git @ 5cf3368b2d4799797000ae36b01596e229e4525a
```

### Plugins

```
cocoapods-dependencies : 0.4.0
cocoapods-plugins      : 0.4.1
cocoapods-trunk        : 0.6.0
cocoapods-try          : 0.4.3
```

### Podfile

```ruby
///Contact me in private for contents of podfile
```

### Error

```
NoMethodError - undefined method `path' for nil:NilClass
/Users/yorkepb/CocoaPods/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:152:in `map'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:152:in `add_pods_resources'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:33:in `block in integrate!'
/Users/yorkepb/CocoaPods/lib/cocoapods/user_interface.rb:49:in `section'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:29:in `integrate!'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer/user_project_integrator.rb:114:in `block in integrate_user_targets'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer/user_project_integrator.rb:113:in `each'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer/user_project_integrator.rb:113:in `integrate_user_targets'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer/user_project_integrator.rb:61:in `integrate!'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer.rb:619:in `block in integrate_user_project'
/Users/yorkepb/CocoaPods/lib/cocoapods/user_interface.rb:49:in `section'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer.rb:616:in `integrate_user_project'
/Users/yorkepb/CocoaPods/lib/cocoapods/installer.rb:97:in `install!'
/Users/yorkepb/CocoaPods/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/yorkepb/CocoaPods/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/bundler/gems/CLAide-4cb13d48a907/lib/claide/command.rb:312:in `run'
/Users/yorkepb/CocoaPods/lib/cocoapods/command.rb:46:in `run'
/Users/yorkepb/CocoaPods/bin/pod:44:in `<main>'
```

**Comment by segiddins** [comment]
We won't be able to really debug this without the Podfile. Additionally, does this still happen on 0.36.3?

**Comment by yorkepb** [comment]
no not with 36.3 but 36.3 has a bug in it that may be fixd in ali-xcassets-1546 that I am specifically testing for.

I can provide the podfile

**Comment by AliSoftware** [comment]
@yorkepb sure, email it to `olivier` <at> `cocoapods` -dot- `org`

**Comment by AliSoftware** [comment]
@yorkepb got your email thanks! Will investigate as soon as I got some bandwidth.

**Comment by AliSoftware** [comment]
@yorkepb Could you try again your project / Podfile with the latest commits on my PR/branch ?

Don't forget to `bundle update` before trying `bundle exec pod update` again on your project, to ensure that you test using the latest version.
I also needed to update the `Xcodeproj` gem to make my PR work, so you may need to add `gem "Xcodeproj", :git => "git://github.com/cocoapods/Xcodeproj", :branch => "master"` to your Gemfile too to ensure it uses the latest Xcodeproj too.

**Comment by yorkepb** [comment]
Sorry I have been delayed on other things. I will try to get to this later today. thanks!

**Comment by yorkepb** [comment]
ok I am really sorry but I am failing at this but I think it is largely because I just don't know enough about ruby. This is really my first exposure to it.

Where do I find the Gemfile for xcodeproj?


What I have been doing thus far is cloning the cocoapods repo and using a specific branch, using bundler to install it and then running the `pod` executable that results from that. 

Should I be doing that differently?

**Comment by segiddins** [comment]
Given Olivier's PR has been closed for a while, I'm going to close this.
