### ISSUE TITLE
Podfile.lock is changed on `pod install`

### ISSUE THREAD

**Issue by ayushgoel** [CocoaPods/CocoaPods#3359]
On `pod install`, the `Podfile.lock` changes. The changes are mostly like:

```
SPEC CHECKSUMS:
-  AFNetworkActivityLogger: d6a2d2755fada3a1fbf1f490ec0dd92224e092a4
-  AFNetworking: 0aabc6fae66d6e5d039eeb21c315843c7aae51ab
+  AFNetworkActivityLogger: e82c9ba285b37042d86729bff5b14036c4312cd7
+  AFNetworking: 41d45d2c14219af0fa5addf3cfd433a002c13c9f
```

Since the diff only shows that the checksums have changed without a change in the version, it seems the podspec files have changed. Is it because of [this commit](https://github.com/CocoaPods/Specs/commit/d05c8cc2fd247198db1d6c56bcc25874fe66508d)?

**Comment by orta** [comment]
Yes, it is due to that commit, we shouldn't need to ever do something like this again, sorry about that.
