### ISSUE TITLE
Add an environment variable to disable to new version message

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#3364]

**Comment by kylef** [comment]
Do we really want to encourage this? Everyone should run the latest until we reach 1.0.

**Comment by orta** [comment]
I think hit sis related to a jazzy issue

**Comment by segiddins** [comment]
@kylef this wouldn't be _encouraging_ people to ignore those notices, just making it possible without needed to write to the `~/.cocoapods/config.yaml`

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/issues/3453.
