### ISSUE TITLE
ld: library not found for -lPods 

### ISSUE THREAD

**Issue by Guicai-Li** [CocoaPods/CocoaPods#3366]
Pods was rejected as an implicit dependency for 'libPods.a' because its architectures 'arm64' didn't contain all required architectures 'armv7'

I had removed all about CocoaPods.Then install again.This issus also had.

**Comment by segiddins** [comment]
@Guicai-Li you've really not given us enough info to go on. Feel free to reopen the issue if you have a project that reproduces the problem you're experiencing.
