### ISSUE TITLE
Podfile.lock changing spec checksums for pods with git URLs in Cocoapods 0.36.3

### ISSUE THREAD

**Issue by uditiiita** [CocoaPods/CocoaPods#3371]
I have a Podfile with some of the Pods using custom git urls using `:git`. After upgrading to Cocoapods 0.36.3 and running `pod install`, I get following spec checksum changes in `Podfile.lock`

![screen shot 2015-04-07 at 4 21 02 pm](https://cloud.githubusercontent.com/assets/1570541/7021695/243931e8-dd42-11e4-828a-8fb52bf652df.png)

Pod is included like this:
`pod 'Block-KVO', :git => 'https://github.com/iMartinKiss/Block-KVO.git', :tag => 'v2.2.2'`

When I run this command to find the SHA of podspec:
`curl "https://raw.githubusercontent.com/iMartinKiss/Block-KVO/v2.2.2/Block-KVO.podspec" | shasum`

I get `094a3fb38f161468d7c406031af7d3daacc48ab0`

Since the spec's SHA is still `094a3fb38f161468d7c406031af7d3daacc48ab0`, then why the spec checksum for the pod in lock file is changing to: `513631d6055c08af9b4e02b44b0ab976957406fb`

**Comment by kylef** [comment]
@uditiiita The spec checksum used to be raw checksums of the files, but in a recent version they are now calculated based on a JSON representation which is internally stored.

```json
{
  "name": "Block-KVO",
  "version": "2.2.2",
  "summary": "Objective-C Key-Value Observing made easier with blocks.",
  "homepage": "https://github.com/iMartinKiss/Block-KVO",
  "authors": {
    "Martin Kiss": "martin.kiss@me.com"
  },
  "license": {
    "type": "MIT",
    "file": "LICENSE.md"
  },
  "source": {
    "git": "https://github.com/iMartinKiss/Block-KVO.git",
    "tag": "v2.2.2"
  },
  "source_files": [
    "Sources",
    "Sources/**/*"
  ],
  "public_header_files": "MTKObserving.h",
  "requires_arc": true
}
```

**Comment by uditiiita** [comment]
Thanks @kylef . Can you suggest me any steps to generate this new checksum `513631d6055c08af9b4e02b44b0ab976957406fb ` from raw `https://raw.githubusercontent.com/iMartinKiss/Block-KVO/v2.2.2/Block-KVO.podspec`

**Comment by kylef** [comment]
```ruby
Pod::Specification.from_file('Block-KVO.podspec').checksum
094a3fb38f161468d7c406031af7d3daacc48ab0
```

**Comment by kylef** [comment]
eh, thats wrong.

**Comment by kylef** [comment]
Here's how you can do it from a shell:

```
$ pod ipc spec Block-KVO.podspec | openssl sha1
513631d6055c08af9b4e02b44b0ab976957406fb
```

**Comment by uditiiita** [comment]
@kylef  Thanks a lot for prompt help.

**Comment by zgordon01** [comment]
@kylef We are running into a similar issue. We have the below:
```
  "source": {
    "http": "file:///`...`/node_modules/react-native-storyboard/ios/"
  },
```
This is being autogenerated by react-native as it's an automatically linked library, so we have no control over the generation of this json. Most of our packages are obviously downloads, but this package specifically needs to be checked in as it's from a vendor.

Any helpful advice would be appreciated
