### ISSUE TITLE
Podspec dependency on a specific commit

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/CocoaPods#3372]
I have submitted a pull request to blakewatters/TransitionKit#27. This PR introduces among other things a new `TKStateMachineDidChangeStateTransitionUserInfoKey` constant. The pull request has been merged but a new version of the library has not yet been made available. I have a project which depends on TransitionKit with this pull request merged. I can specify in the Podfile which exact commit to use but how do I create a valid podspec? Using `s.dependency "TransitionKit", "~> 2.1.1"` does not validate because of a compilation error: 

    use of undeclared identifier 'TKStateMachineDidChangeStateTransitionUserInfoKey'; did you mean 'TKStateMachineDidChangeStateEventUserInfoKey'

I totally understand why you can’t [break the version promises](http://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of/22475228#22475228) in a podspec. But how can I produce a valid podspec that depends on an unreleased version of a dependency?

**Comment by segiddins** [comment]
@0xced the first step is to ask the owner of the Pod to create a new release. If that doesn't happen within a reasonable timeframe, you'll have to fork the Pod :(. We've talked in the past about adding better support for forks in https://github.com/CocoaPods/CocoaPods/issues/1707
