### ISSUE TITLE
Due to the previous naïve CocoaPods resolver...which now leads to a conflict

### ISSUE THREAD

**Issue by Sully73** [CocoaPods/CocoaPods#3373]
I am using version 0.36.3 and I'm having a similar problem reported in [#2920](https://github.com/CocoaPods/CocoaPods/issues/2920), I'm using a MagicalRecord on a development branch and I receive the error
>[!] Due to the previous naïve CocoaPods resolver, you were using a pre-release version of `MagicalRecord`, without explicitly asking for a pre-release version, which now leads to a conflict. Please decide to either use that pre-release version by adding the version requirement to your Podfile (e.g. `pod 'MagicalRecord', '= 3.0.0.dev.1428414311'`) or revert to a stable version by running `pod update MagicalRecord`.

I can `pod update MagicalRecord` and it works fine, but I would like to use this on a CI server which uses `pod install` and therefore doesn't build.  Any solutions?

**Comment by segiddins** [comment]
As the error message says, just change your dependency on `MagicalRecord` to include a pre-release identifier.

**Comment by Sully73** [comment]
How do I specify an alternative branch? 
I currently have
`pod 'MagicalRecord', :git => "https://github.com/magicalpanda/MagicalRecord.git", :branch => "release/3.0"`

As suggested I tried this
`pod 'MagicalRecord','= 3.0.0.dev.1428414311'`

but it gives 

[!] Unable to satisfy the following requirements:

- `MagicalRecord (= 3.0.0.dev.1428414311)` required by `Podfile`

**Comment by segiddins** [comment]
What about just running `pod update MagicalRecord` this one time and committing the results, and using `pod install` hereafter?

**Comment by kdawgwilk** [comment]
Even after committing a `pod update MagicalRecord` to git, CI server fails the `pod install` with the above error.

**Comment by fjcaetano** [comment]
This also started happening for me. My Podfile explicitly asks for the pre-release version, but I can't run a `pod update` because it's the CI that is failing.

**Comment by kdawgwilk** [comment]
I got things to work but had to fork the repo and remove the generated timestamp in the podspec from the version number

**Comment by balazsnemeth** [comment]
I had to run `pod repo update` to get rid off this issue

**Comment by phatblat** [comment]
`pod repo update` solved this issue on CI for me. In my case, the CI server's `master` repo had RxSwift `4.0.0-beta.0`, but not the `4.0.0-beta.1` version the app was asking for.

**Comment by khadkaPratik** [comment]
I tried to update `pod repo update` but i ddnt work so i removed all the pod file inside ios folder and recreate `Podfile` and `pod install `.

**Comment by Sander-Kornev** [comment]
@kdawgwilk, I've done the same, had to fork MagicalRecord. I just wonder, what is the reason to write
`  s.version  = "3.0.0.dev.#{Time.now.to_i}"` in podspec ?
