### ISSUE TITLE
Pod try problem

### ISSUE THREAD

**Issue by f33chobits** [CocoaPods/CocoaPods#3375]
Hey there.
    I've push a few repos in pods, but the `pod try` always bring in an build error.  Run `pod update` in the `try` project can get rid of it. But why the version of the repo in `pod try` is always older? Is there a reviewing procedure?

**Comment by kylef** [comment]
@f33chobits can you share an actual example that exhibits this problem?

**Comment by f33chobits** [comment]
`pod try FSCalendar` . `pods version` is 0.5.3 but `try version` is 0.5.0.
OS 10.10.2, Xcode 6.2

**Comment by neonichu** [comment]
This happens because the lock file of your example specifies version 0.5.0 - see https://github.com/f33chobits/FSCalendar/blob/master/Example/Podfile.lock#L2

**Comment by f33chobits** [comment]
Thanks. I should have updated the local pods project before run `pod trunk push`
