### ISSUE TITLE
Cocoapods 0.36.3 attempts to create a master repo when it is not asked

### ISSUE THREAD

**Issue by amg** [CocoaPods/CocoaPods#3381]
> $ pod install
> Analyzing dependencies
> Creating shallow clone of spec repo `master-1` from `https://github.com/CocoaPods/Specs.git`
> [!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
> You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

I'm restricting here the folder to not let cocoapods create anything.

The problem is I'm using the private repo that I have called "master" on purpose so it doesn't clone the cocoapods public repo. Existence of the public repo makes every pod install/update slower and I do not require public one.

Please, have an option to not load the master repository.

**Comment by fuxiaohui** [comment]
I have same problem 
Creating shallow clone of spec repo `master-1` from `https://github.com/CocoaPods/Specs.git`

**Comment by magin** [comment]
Same problem here. Any ideas?

**Comment by segiddins** [comment]
This is intentional -- CocoaPods expects to own the repo named `master`

**Comment by xilin** [comment]
@segiddins But in these cases we had already add a repo named master using `pod repo add master http://xxxxx`.

**Comment by segiddins** [comment]
Yeah, don't do that. But we should explicitly error when attempting to add a repo named `master`.

**Comment by amg** [comment]
This is sad because it's a downgrade. I don't want a link to public repo
for security reasons. Private one serves as an artifactory in maven.

**Comment by xilin** [comment]
@amg You can specify your source again in your Podfile. Then it will not create a new repo `master-1`

**Comment by neonichu** [comment]
If you specify explicit sources in your Podfile, the master repo won't be cloned, e.g.:

```ruby 
source 'https://github.com/contentful/CocoaPodsSpecs'

pod 'ContentfulDialogs'
```

**Comment by amg** [comment]
Thanks, will give it a go.
