### ISSUE TITLE
Can't update the pods

### ISSUE THREAD

**Issue by yishuiliunian** [CocoaPods/CocoaPods#3385]
i use on pod  "https://github.com/yishuiliunian/DZCache", it's version is 1.0.7 at Github, but it's version is 1.0.2. The versions do not equal.  And i can not update the pods. why?

```
-> DZCache (1.0.2)
   内存缓存组件
   pod 'DZCache', '~> 1.0.2'
   - Homepage: https://github.com/yishuiliunian/DZCache
   - Source:   https://github.com/yishuiliunian/DZCache.git
   - Versions: 1.0.2, 1.0.0 [master repo]
```

**Comment by orta** [comment]
You need to do a `pod repo update` to update your local copy of the Specs repo.
