### ISSUE TITLE
`xcode-select: Error: unknown command option '-p'.` in v0.36.3

### ISSUE THREAD

**Issue by capnslipp** [CocoaPods/CocoaPods#3387]
🌈 As of CocoaPods 0.36.3, I'm getting the follow error whenever I run a `pod install`:

> `$ pod install`
> `Analyzing dependencies`
> <code><b>xcode-select: Error: unknown command option '-p'.</b></code>
> …

The previous version of CocoaPods I had installed was 0.35.0, which did not have the issue.

I'm using:
* OS X 10.8.5 _(the latest 10.8.x)_
* RVM Ruby 2.1.3
* Xcode 5.1.1 _(the latest 5.x, and latest for OS X 10.8)_

**Comment by capnslipp** [comment]
I should mention that this seems not to affect the operation of `pod install`— it just appears to a naive CocoaPods user as a “false positive” error.

It looks like the latest version of the `xcode-select` manpage (https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcode-select.1.html) advises against using the `-p` flag from/for scripts:
>       -p, --print-path
>              Prints  the path to the currently selected developer directory. This is useful for inspection,
>              but scripts and other tools should use xcrun(1) to locate tool  inside  the  active  developer
>              directory.

A saner solution might be something like:
~~~
# [existing xcode-select call]
xcodebuild_path = begin
  path = `xcrun --find xcodebuild`
  concise_path = xcodebuild_path[%r'(/.*/)usr/bin/xcodebuild', 1]
  concise_path || path
end
puts "Using Xcode directory: #{xcodebuild_path}"
~~~

**Comment by neonichu** [comment]
I believe the intention of that advice is not hardcoding paths to specific tools as their location inside the Xcode bundle is suspect to change. Alas, hardcoding the relative path to `xcodebuild` would make this more brittle, not less.

Back to the original issue, does the Xcode 5.x `xcode-select` have `--print-path`?

BTW, this is not a hard error, because it is used inside the Xcodeproj gem to locate the DevToolsCore.framework for writing the project file as an ASCII plist, and if that fails it'll fall back to writing XML.

**Comment by neonichu** [comment]
Ah, I see `xcode-select` is not tied to the Xcode version at all, but to the OS version. Could you please share the output of `xcode-select --help` on 10.8?

**Comment by capnslipp** [comment]
`xcode-select --help` on OS X 10.8.5:
~~~
xcode-select: Error: unknown command option '--help'.

xcode-select: Report or change the path to the active
              Xcode installation for this machine.

Usage: xcode-select --print-path
           Prints the path of the active Xcode folder
   or: xcode-select --switch <xcode_path>
           Sets the path for the active Xcode folder
   or: xcode-select --version
           Prints the version of xcode-select
~~~

**Comment by neonichu** [comment]
Thanks, `--print-path` it will be. I wasn't aware that the short-hand wasn't available in older OS versions.

**Comment by capnslipp** [comment]
Works for me.  Cheers.
