### ISSUE TITLE
How to tell podspec to always use the latest commit?

### ISSUE THREAD

**Issue by onmyway133** [CocoaPods/CocoaPods#3388]
I'm developing local pods, as [Using the files from a local path](http://guides.cocoapods.org/syntax/podfile.html#pod)
```
pod 'MyDevLibrary', :path => '~/Documents/MyDevLibrary'
```

I see that the `podspec` `source` can only use `tag` [source](http://guides.cocoapods.org/syntax/podspec.html#source)
```
spec.source = { :git => 'https://github.com/AFNetworking/AFNetworking.git',
                :tag => spec.version.to_s }
```

How can I tell podspec source to always use the latest commit?

**Comment by segiddins** [comment]
You need to do that in your `Podfile`, rather than the podspec.

**Comment by onmyway133** [comment]
@segiddins you mean the `:head` option, like ```pod 'Objection', :head``` ?
From what I know, the purpose of the Podfile is to find the Podspec, so what should be in my Podfile?

**Comment by orta** [comment]
[Here](https://github.com/artsy/eigen/blob/master/Podfile#L51) is an example always using head. [Here](https://github.com/artsy/eigen/blob/master/Podfile#L87) is an example of using the most local commit, and `pod update` will update it to a new one.

**Comment by foobra** [comment]
@orta but use :head in pod update always download the repo no matter the repo had changed or not. Can cocoapods cache the last head sha1, if sha1 changed, then re download the repo, or just skip to save pod update time
