### ISSUE TITLE
Alamofire 1.2.0 and 1.1.5 Missing From Trunk

### ISSUE THREAD

**Issue by mattt** [CocoaPods/CocoaPods#3389]
On Thursday, @cnoon and I submitted versions 1.1.5 [[1]](https://github.com/Alamofire/Alamofire/issues/422#issuecomment-91267693) and 1.2.0, respectively, to CocoaPods trunk. However, users have recently been reporting that the latest they can find is 1.1.4.

Trying this just now, I get the same results:

```
$ pod --version
0.36.3

$ pod search Alamofire --full 

-> Alamofire (1.1.4)
   Elegant HTTP Networking in Swift
   pod 'Alamofire', '~> 1.1.4'
   - Homepage: https://github.com/Alamofire/Alamofire
   - Source:   https://github.com/Alamofire/Alamofire.git
   - Versions: 1.1.4, 1.1.3 [master repo]
```

Any idea what happened to previous submissions? Is this just data loss, or something else?

**Comment by mattt** [comment]
(Also, this [TKAlamofire](https://github.com/nicolastinkl/TKAlamofire) repo shows up in search as well. Any idea what this is, and how to remove it?)

**Comment by orta** [comment]
Likely they need to do a `pod repo update`

```
~/eigen $ pod search Alamofire --full  

-> Alamofire (1.2.0)
   Elegant HTTP Networking in Swift
   pod 'Alamofire', '~> 1.2.0'
   - Homepage: https://github.com/Alamofire/Alamofire
   - Source:   https://github.com/Alamofire/Alamofire.git
   - Versions: 1.2.0, 1.1.5, 1.1.4, 1.1.3 [master repo]


-> AmazonS3RequestManager (0.3.0)
   A Alamofire based request manager that serializes requests to the AWS S3 (Amazon Simple Storage Solution). Based on AFAmazonS3Manager
   pod 'AmazonS3RequestManager', '~> 0.3.0'
   - Homepage: https://github.com/AnthonyMDev/AmazonS3RequestManager
   - Source:   https://github.com/AnthonyMDev/AmazonS3RequestManager.git
   - Versions: 0.3.0, 0.2.0, 0.1.0 [master repo]


-> Promissum (0.2.2)
   A promises library written in Swift featuring combinators like map, flatMap, whenAll, whenAny.
   pod 'Promissum', '~> 0.2.2'
   - Homepage: https://github.com/tomlokhorst/Promissum
   - Source:   https://github.com/tomlokhorst/Promissum.git
   - Versions: 0.2.2, 0.2.1 [master repo]
   - Subspecs:
     - Promissum/Core (0.2.2)
     - Promissum/Alamofire (0.2.2)
     - Promissum/UIKit (0.2.2)


-> RACAlamofire (0.0.6)
   ReactiveCocoa extensions for Alamofire
   pod 'RACAlamofire', '~> 0.0.6'
   - Homepage: https://github.com/ararog/Alamofire-RACExtensions
   - Source:   https://github.com/ararog/Alamofire-RACExtensions.git
   - Versions: 0.0.6 [master repo]


-> TKAlamofire (1.1.4)
   Elegant HTTP Networking in Swift
   pod 'TKAlamofire', '~> 1.1.4'
   - Homepage: https://github.com/nicolastinkl/TKAlamofire
   - Source:   https://github.com/nicolastinkl/TKAlamofire.git
   - Versions: 1.1.4, 1.0.2 [master repo]
```

**Comment by orta** [comment]
re: TKAlamofire, looks like @nicolastinkl has a habit of taking [OSS](https://github.com/nicolastinkl/TKMessagesViewController/blob/master/messagedemo/JSDemoViewController.m) and renaming it. It seems to not come up on the website search though, which is interesting.

**Comment by mattt** [comment]
Thanks, @orta.

I wouldn't have expected search to use the local class unless manually refreshed, but this worked for me.

**Comment by mattt** [comment]
As for @nicolastinkl and other folks who submit pods with misleading names, this is the cost of having a low barrier to contribution, unfortunately. It's a difficult problem of policy and process, which I hope the team can implement at some point.
