### ISSUE TITLE
Add spec version numbers to acknowledgements plist

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#3391]
Looks like it would be relatively easy to add this feature as a "Version" field: https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/acknowledgements/plist.rb

**Comment by orta** [comment]
This is likely to be deprecated soon in favor of https://github.com/cocoapods/cocoapods-acknowledgements - we should get this feature in there

**Comment by chrisballinger** [comment]
Ah great, thanks!
