### ISSUE TITLE
can't pod repo update

### ISSUE THREAD

**Issue by Onetaway** [CocoaPods/CocoaPods#3392]
I use `pod repo update`.
Here's the result.
![screen shot 2015-04-14 at 09 39 14](https://cloud.githubusercontent.com/assets/3251826/7128812/367167de-e28a-11e4-823e-f35d0625811f.png)
 
How can I solve this problem?
pod version is 0.36.3

**Comment by kylef** [comment]
This sounds similar to the broken specs repository problem, please checkout this blog post and see if it fixes your problems: http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/

**Comment by Onetaway** [comment]
@kylef Thanks. I will try.

**Comment by kishykumar** [comment]
@Onetaway Can you please list here what steps solved your problem?
