### ISSUE TITLE
use_frameworks! breaks other pod functionality

### ISSUE THREAD

**Issue by Shmaff** [CocoaPods/CocoaPods#3393]
Hi,

 My app uses many pods currently and I've just tried adding my first swift-based pod which insists I add "use_frameworks!" to my podfile. It would be great if this would work per pod as opposed to forcing all pods to compile as frameworks. I understand this is still beta functionality.

An example of why this breaks is with [RaptureXML](https://github.com/ZaBlanc/RaptureXML) as its code references its own Bundle. Its intended functionality is to target the app bundle and not the framework bundle with the following line:
`[[NSBundle bundleForClass:[self class]] pathForResource:filename ofType:extension];`
Where `[self class]` resolves to RXMLElement and now references its framework instead of the app bundle as desired.

Perhaps I'm mistaken with the desired functionality of this method but obviously that a conversation for another place. Obviously the programmer could have written `[NSBundle mainBundle]`. Point being, am I barking up the wrong tree with this type of pod-related error?

**Comment by Shmaff** [comment]
A shorter version to my question is, "can we have a hybrid compile solution for pods as frameworks or not frameworks?"

**Comment by segiddins** [comment]
No, this is not currently possible nor on the roadmap. You should fix the upstream framework to reference the bundle it ought to be referencing.

**Comment by Shmaff** [comment]
Thanks! I'm just noticing the blog post that covers the reasons for this.

**Comment by armanshan12** [comment]
@segiddins, Could you explain "You should fix the upstream framework to reference the bundle it ought to be referencing." in more details please?

**Comment by Shmaff** [comment]
In my example, I was using `[NSBundle bundleForClass:[self class]]` and this would resolve to the bundle or framework that I was using in my project whilst using the use_frameworks! cocoapods directive. This forces all bundles to be added to the project as frameworks and thus would target its framework which is a subdirectory of my main app bundle, i.e., `[NSBundle mainBundle]`. Once I changed this, my desired functionality returned. Check [this blog post](http://blog.cocoapods.org/CocoaPods-0.36/) for a full explanation.
