### ISSUE TITLE
Making private headers accessible to unit tests?

### ISSUE THREAD

**Issue by mjholgate** [CocoaPods/CocoaPods#3394]
This isn't really a bug as such, more a query to see if it is possible!

Is there a way of exposing a Pod's private headers in certain limited situations, such as for use in unit tests? For example, it might be nice to able to do something like:

target 'Tests', :exclusive => true do
  pod "MyPod", :path => "../", :allowPrivateHeaders => true
end

I tried to hack something myself by using a sub-spec for the private headers, but that didn't work very well.

Thanks!

**Comment by neonichu** [comment]
It is currently not possible, but planned for the eventual cleanup of the Podfile DSL: #840 - in the meantime, the best workaround is to add a `post_install` hook which amends the header search paths manually.

**Comment by mjholgate** [comment]
Ah, great, thanks @neonichu!
