### ISSUE TITLE
Does :path support :branch?

### ISSUE THREAD

**Issue by onmyway133** [CocoaPods/CocoaPods#3395]
I'm using `:path` to do `Development Pods`. I read from [Local CocoaPods](https://www.cocoanetics.com/2013/05/8130/) that `:path` can go together with `:branch`

```
platform :ios, '5.0'
pod 'DTCoreText', :path => '~/Documents/Projects/DTCoreText/', :branch => 'develop'
```

How does `:path` work with `:branch`? I see that `:path` just make reference to the local repo (whatever is in the working copy)

**Comment by segiddins** [comment]
`:path` doesnt work with any other options.
