### ISSUE TITLE
missing required module 'X'

### ISSUE THREAD

**Issue by tomaskraina** [CocoaPods/CocoaPods#3396]
I'm having a problem with integrating a cocoa pod (`CocoaLumberjack` in this case).

I have a hierarchy of modules (dynamic frameworks) like this:

- `CommonModule`
- `ModelsModule` (has a dependency `CommonModule`)

And finally, the main app:

- `MySwiftApp` (dependency both `ModelsModule` and `CommonModule`)

Now, `CocoaLumberjack` is used in several files in `CommonModule` and works as expected. However, every time I do `import CommonModule` in any file in `ModelsModule`, I get the following compile error:

```
/Users/tomaskraina/Developer/ModelsModule/ModelsModule/SomeFile.swift:2:8: error: missing required module 'CocoaLumberjack'
import CommonModule
       ^
```

Any idea how to solve this issue?

**Comment by neonichu** [comment]
This is a duplicate of #3095
