### ISSUE TITLE
Extract UI module into its own gem

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#3398]
@karla-isabel-sandoval

**Comment by Karla-Isabel-Sandoval** [comment]
segiddins said:
it’s basically taking the banner components from CLAide and the Pod::UI module and extracting that into a new gem

**Comment by Karla-Isabel-Sandoval** [comment]
https://github.com/CocoaPods/CLAide/blob/master/lib/claide/command/banner.rb

https://github.com/CocoaPods/Cork

**Comment by Karla-Isabel-Sandoval** [comment]
Add Cork as a dependency to CocoaPod and make Pod::UI be a reference t oa subclass of Cork::Board.

**Comment by orta** [comment]
This has been done, it's just not come back into CocoaPods now 👍
