### ISSUE TITLE
Installing a pod via `:git` in the Podfile fails for the wrong reason when it doesn't have a podspec

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#3399]
### Steps to reproduce
1. Create the following Podfile:

    ```ruby
    platform :osx, '10.10'
    pod 'Molinillo', :git => 'https://github.com/CocoaPods/Molinillo'
    ```
2. Run `pod install`

    ```
    pod install --no-integrate --no-repo-update
    ```

### Expected result

I'm to be told that this source I've selected doesn't have a podspec.

### Actual result

I'm told a local JSON podspec file inside the Pods directory doesn't exist.

```
Analyzing dependencies
Pre-downloading: `Molinillo` from `https://github.com/CocoaPods/Molinillo`
[!] No podspec exists at path `/Users/kyle/Pods/Molinillo/Molinillo.podspec.json`.
```

**Comment by segiddins** [comment]
That's probably fixed on the download cache branch?
