### ISSUE TITLE
Development Pods project structured changed

### ISSUE THREAD

**Issue by tbrannam** [CocoaPods/CocoaPods#3404]
after upgrading to 0.36.3  I have noticed that pods that are being locally (development pods) are being importing into Xcode with a folder structure that reflects the relative path on disk.   This is a new behavior - and looks a little crazy if your cocopod consists of multiple subspecs.

Was this an expected change? or is there a new flag related to paths for development pods?

![screen shot 2015-04-15 at 2 07 38 pm](https://cloud.githubusercontent.com/assets/78813/7165957/dade7ff2-e378-11e4-8512-8fcaa66f5c97.png)
![screen shot 2015-04-15 at 2 07 57 pm](https://cloud.githubusercontent.com/assets/78813/7165970/e1043516-e378-11e4-85af-643c2ca75058.png)

**Comment by segiddins** [comment]
This is indeed a new feature of 0.36 that allows you to have a bit more control over how Xcode groups your pods in development, by reflecting your directory structure in the groups it creates.

**Comment by tbrannam** [comment]
My search-foo in the release notes missed it - but sure enough it is documented as a change.   I guess I was using subspecs to implement the same behavior - so I'll clean up my stuff.

Thanks
