### ISSUE TITLE
Add pre-install hook for Plugins

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#3409]
There are at least two CocoaPods plugins that are hacking into CocoaPods in order to provide pre-install setup integration. Both of which want to make runtime changes to the available pods, and the current way the do this removes the need for the plugin to be defined in the Podfile.

Adding support for another plugin hook at the before the install function should offer an opportunity to remove some of these hacks and to encourage bigger-picture plugins for cocoapods.

**Comment by segiddins** [comment]
What information would these plugins need ?

**Comment by orta** [comment]
I think it would want access to the current Podfile representation, `Pod::Config.instance.podfile` and it's own settings dictionary.
