### ISSUE TITLE
Get rid of `Pods-XX-Dummy.m` files completely

### ISSUE THREAD

**Issue by AliSoftware** [CocoaPods/CocoaPods#3410]
These `Pods-Dummy.m` files were introduced to workaround [a known bug in LLVM's linker when building a lib that contained categories only, **but this bug has been fixed since Xcode 4.3**](https://llvm.org/bugs/show_bug.cgi?id=7431)

The fix in the linker is confirmed by my own experience (I remember following this linker bug closely and my relief when I learned and confirmed that it has been fixed), but also by [this SO answer](http://stackoverflow.com/questions/2567498/objective-c-categories-in-static-library/9224606#9224606) as well as [this one](http://stackoverflow.com/a/2615407/803787) (validated by Dave DeLong in comments). See also [this Technical Q&A page from Apple](https://developer.apple.com/library/mac/qa/qa1490/_index.html), that got amended on 2014-08-05 to remove the workarounds no longer needed.

---

Since Xcode 4.3 is long adopted and gone now, we can get rid of these classes, that sometimes generate side effects and issues (e.g. #1767). _(See also discussion in Slack 20mn ago for another side-effect that generate issues)_

**Comment by neonichu** [comment]
I remember this warning still being present last year: 

> warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for library: {some library} for architecture: {some architecture} the table of contents is empty (no object file members in the library define global symbols)

also talked with @hpique back when he posted <http://stackoverflow.com/questions/27602998/silence-table-of-contents-is-empty-warning> - I think he didn't find a solution

**Comment by neonichu** [comment]
BTW, we should probably either have this or #1767 - duplication doesn't really help :)

**Comment by segiddins** [comment]
Closing in favor of the other issue.
