### ISSUE TITLE
Faster way to switch a pod with many subspecs to use :path instead of released version and back?

### ISSUE THREAD

**Issue by Buju77** [CocoaPods/CocoaPods#3415]
Again I'm speaking from my transition from 0.33.1 to 0.36.3 as mentioned in my other post.

Assuming I have this Podfile utilizing many subspecs from same pod:

	pod 'myLib/core', 		'~> 0.3.4'
	pod 'myLib/subspec1', 	'~> 0.3.4'
	pod 'myLib/subspec2', 	'~> 0.3.4'
	pod 'myLib/subspec3', 	'~> 0.3.4'

Previously with the old resolver if I wanted to change it to use `:path` for local development I would just need to add a new line on top and it would activate my local podspec

	pod 'myLib/core', 		:path => '~/dev/myLib'

	pod 'myLib/core', 		'~> 0.3.4'
	pod 'myLib/subspec1', 	'~> 0.3.4'
	pod 'myLib/subspec2', 	'~> 0.3.4'
	pod 'myLib/subspec3', 	'~> 0.3.4'

Now with the new resolver I would need to change **all** lines of `myLib` to use `:path` which is not very comfortable. Because if I'm done with my development I had to delete just one line previously. 

Is there a way to accelerate this process to quickly switch from a released version to `:path`, `:git + :branch` and back to released version?

**Comment by kylef** [comment]
(This is upcoming syntax for CocoaPods 0.37): https://github.com/CocoaPods/Core/issues/221

```ruby
pod 'myLib', :path => '~/dev/myLib', :subspecs => ['subspec1', 'subspec2', 'subspec3']
```

Does this solve your problem?

**Comment by Buju77** [comment]
ah nice, so my podfile would look like this to quickly switch between them:

	# pod 'myLib', :subspecs => ['subspec1', 'subspec2', 'subspec3'], 	:path => '~/dev/myLib'
	pod 'myLib', :subspecs => ['subspec1', 'subspec2', 'subspec3'], 	:git => 'http://...', :branch => 'fixBranch'
	# pod 'myLib', :subspecs => ['subspec1', 'subspec2', 'subspec3'], 	'~> 0.3.4'

correct?

**Comment by kylef** [comment]
Yes that's right

**Comment by segiddins** [comment]
@Buju77 it would have to be

```ruby
# pod 'myLib', '~> 0.3.4', :subspecs => ['subspec1', 'subspec2', 'subspec3']
```

**Comment by Buju77** [comment]
hmm why must the version be as the 2nd parameter? the version i proposed would make a much better readable Podfile because local path and git path can be rather long. It would it more difficult to compare if you missed a subspec definition or not

**Comment by orta** [comment]
@Buju77 because it uses the ruby hash/dictionary argument syntax, you need to define non-hash arguments first

**Comment by Buju77** [comment]
@orta what about adding an optional hashed version argument in addition to non-hashed? this way both of us would be satisfied ;)

    pod 'myLib', :subspecs => ['subspec1', 'subspec2', 'subspec3'],  :version =>  '~> 0.3.4'
    pod 'myLib', '~> 0.3.4', :subspecs => ['subspec1', 'subspec2', 'subspec3']

would both be the same.

**Comment by segiddins** [comment]
That's DSL creep, imho

**Comment by orta** [comment]
I understand where you're coming from @Buju77 but I'm with @segiddins - it adds another place for confusion that I'd prefer to not see.
