### ISSUE TITLE
Obj-C Pod built with use_frameworks! does not have access to StoreKit

### ISSUE THREAD

**Issue by marcpalmer** [CocoaPods/CocoaPods#3417]
First I’d like to thank everyone for their work over recent months to get Swift and Frameworks support into Cocoapods. It is just fantastic that you guys got this done.

I have a private Objective-C pod that wraps up some StoreKit functionality.

I am including this pod of mine in a Swift project using Cocoapods 0.36.3, with use_frameworks! enabled.

Everything works OK but when this pod of mine is used to instantiate a StoreKit view controller, the VC is nil:

```
   SKStoreProductViewController *storeController = [[SKStoreProductViewController alloc] init];
```

…storeController is nil when the code is in my pod. If I put this same code into my main app (converting it to Swift, obviously) it works.

There would appear to be a linkage/availability problem in the framework created by the pod. FWIW the generated xcconfig for the pod looks like it refs the framework OK:

```
PODS_XXXXX_UIFRAMEWORK_OTHER_LDFLAGS = -framework "MessageUI" -framework "StoreKit" -framework "UIKit"
```

Have I done something wrong or is there an issue with the way the dynamic linking is set up such that when the App calls code in the Pod, the Pod has not linked at runtime with StoreKit? Forgive me if this is not Pods related, but it is hard to work out right now whether it is or not

**Comment by neonichu** [comment]
Hard to say what's going on here, would be really helpful if you were able to provide an example which reproduces your issue. Thanks!

**Comment by neonichu** [comment]
We unfortunately never got an example for this, so this issue is not actionable.
