### ISSUE TITLE
Invalid symlinks (Headers) prevents submission to App Store

### ISSUE THREAD

**Issue by gvalmon** [CocoaPods/CocoaPods#3418]
I'm getting following error when trying to submit osx application: 

```
We have discovered one or more issues with your recent delivery for "Planiro Tracker". To process your delivery, the following issues must be corrected:

Invalid Symlink - Your package contains a symbolic link 'com.droidlabs.PlaniroTracker.pkg/Payload/PlaniroTracker.app/Contents/Frameworks/Alamofire.framework/Headers' which resolves to a location 'com.droidlabs.PlaniroTracker.pkg/Payload/PlaniroTracker.app/Contents/Frameworks/Alamofire.framework/Versions/Current/Headers' that does not exist or is outside of the package.

Invalid Symlink - Your package contains a symbolic link 'com.droidlabs.PlaniroTracker.pkg/Payload/PlaniroTracker.app/Contents/Frameworks/PromiseKit.framework/Headers' which resolves to a location 'com.droidlabs.PlaniroTracker.pkg/Payload/PlaniroTracker.app/Contents/Frameworks/PromiseKit.framework/Versions/Current/Headers' that does not exist or is outside of the package.
```

I checked contents of the applications, and all frameworks installed by cocoapods contains invalid "Headers" symlink. Cocoapods version 0.36.4

**Comment by gvalmon** [comment]
I added `mkdir -p "${destination}/$1/Versions/A/Headers"` to Pods-frameworks.sh as temporary workaround, but it's strange that dirs are not created (not sure where it should happen).

**Comment by chrisvxd** [comment]
I'm also having this issue, and attempting the temporary workaround suggested by @gvalmon. Will edit this post once Apple respond.

**Comment by knutigro** [comment]
Hi  I'm also having this issue with my Swift, OSX projects using Cocoapod Version `0.37.1`
I had same error as @gvalmon in the beginning but after adding the suggested workaround I got a new error from Itunes Connect:

```Invalid Symlink - Your package contains a symbolic link 'com.cocmoc.appreviews.pkg/Payload/App Reviews.app/Contents/Frameworks/Alamofire.framework/Modules' which resolves to a location 'com.cocmoc.appreviews.pkg/Payload/App Reviews.app/Contents/Frameworks/Alamofire.framework/Versions/Current/Modules' that does not exist or is outside of the package. ```

I then manually deleted this `Modules` symlink from within my package and uploaded a new version to Appstore. This time it went into Review without complaints.

**Comment by chrisvxd** [comment]
I have managed to pass submission by using the workaround from @gvalmon for all symlinks. @knutigro why don't you try that next time?

    mkdir -p "${destination}/$1/Versions/A/Headers"
    mkdir -p "${destination}/$1/Versions/A/Modules"
    mkdir -p "${destination}/$1/Versions/A/Resources"

**Comment by knutigro** [comment]
thanks @chrisvxd  :-)

**Comment by chrisvxd** [comment]
FYI my app got rejected by Apple during review. I've switched to [Carthage](https://github.com/Carthage/Carthage) for now, which I don't believe will run into the same issues due to it's unobtrusive approach.

**Comment by gvalmon** [comment]
@chrisvxd what was the reason of rejection? My app was approved with this solution.

**Comment by devxoul** [comment]
I had same problem and didn't figure out how to solve this. I dropped using CocoaPods and used [CocoaSeeds](https://github.com/devxoul/CocoaSeeds) instead.

**Comment by segiddins** [comment]
Those are both Swift frameworks, so the question is, why is Xcode creating Headers directories for either of them? Might it be the generated umbrella header that we create?

**Comment by Ashton-W** [comment]
Are your pods checked in to source control?
Is this being built on a CI server?

**Comment by neonichu** [comment]
Closing, as we never got enough information to make this actionable.
