### ISSUE TITLE
IRKit Issue for COCOAPODS

### ISSUE THREAD

**Issue by hardikiOS** [CocoaPods/CocoaPods#3419]
Hi 

I tried so many solutions given from so many websites like update cocoa pods, install cocoa pods etc. but nothing is working out for me. 
I am using Xcode 6.1.1, Please help, I am trapped in the issue.

Thanks in advance.

Hardik.

![screen shot 2015-04-17 at 7 41 22 pm](https://cloud.githubusercontent.com/assets/9332828/7203278/24b133f8-e537-11e4-81c4-19a42a903526.png)

**Comment by segiddins** [comment]
Have you followed the instructions in that error message and run pod install?

**Comment by hardikiOS** [comment]
Hi Segiddins,

Yes I did it so many times but it's not working. I am installing POD in the project directory where cocoa pods file is located. Is this correct way?

Hardik.

**Comment by orta** [comment]
This feels like you will need to go back to consult the [guides](http://guides.cocoapods.org/). This isn't a bug with CocoaPods nor a feature request.
