### ISSUE TITLE
0.36.3 breaks the plugin creator

### ISSUE THREAD

**Issue by Inferis** [CocoaPods/CocoaPods#3422]
To reproduce:

```
pod plugins create y-u-no-work
```

results in:

```
-> Creating `cocoapods-y-u-no-work` plugin

[!] using template 'https://github.com/CocoaPods/cocoapods-plugin-template.git'
[!] /usr/local/bin/git clone\ \'https://github.com/CocoaPods/cocoapods-plugin-template.git\'\ cocoapods-y-u-no-work

git: 'clone 'https://github.com/CocoaPods/cocoapods-plugin-template.git' cocoapods-y-u-no-work' is not a git command. See 'git --help'.
```

Now I know I could clone the repo myself and start fiddling with it, but chance for errors is more likely so I'd like to use the creator. 

This is on 10.10.3.

**Comment by segiddins** [comment]
The plugins plugin needs to be updated to use the new Executable API.

**Comment by Inferis** [comment]
But that's already done, it seems: https://github.com/CocoaPods/cocoapods-plugins/commit/c829d77b93015a37d92f5a4741eb804b47ffcc46

**Comment by Inferis** [comment]
Updated plugins, and it works now. ¯\_(ツ)_/¯ 

(I should learn to try to update to most recent versions where possible)
