### ISSUE TITLE
Subgroup Organization With Subspecs Does Not Match Filesystem

### ISSUE THREAD

**Issue by Twigz** [CocoaPods/CocoaPods#3423]
A recent change in cocoapods 0.36 introduced a new subgroup structure to better match filesystem organization.

0.36.0.beta.1

> Installer changed to organize a development pod's source and resource files into subgroups reflecting their organization in the filesystem.

This works great, until you start using subspecs. It creates an output that looks something like this:
![screen shot 2015-04-17 at 11 40 39 am](https://cloud.githubusercontent.com/assets/1043416/7205729/570ab592-e4f9-11e4-8fcd-b30582cce117.png)

As you may be able to tell, the `Pod/Classes` portion of the filesystem is now duplicated across all subspecs. This seems to go against the purpose of allowing the groups in Xcode to reflect the organization in the file system.

Here is a sample project demonstrating the issue: https://www.dropbox.com/s/ljzzbqjq0kmibbm/TestPod.zip?dl=0

If there's any other information I can provide, let me know.

**Comment by segiddins** [comment]
So, @Twigz, what would you say the expected behavior would be?

**Comment by Twigz** [comment]
I suppose if you wanted to preserve the file structure, as well as allow the naming of subspecs to be considered an additional group, it would have to look something like this:

<img width="262" alt="screen shot 2015-07-05 at 5 00 25 pm" src="https://cloud.githubusercontent.com/assets/1043416/8513402/1ec0b452-2338-11e5-804c-aabd314cdef7.png">

If you didn't want to have the name of a subspec affect the group structure anymore, then the groups `Subspec1`, `Subspec2`, and `Subspec3` go away. This would match the file system closer, however now your subspec name is not represented on the file system (unless the creator of the pod chooses to name a folder on the file system identically to the name of the subspec), which could lead to confusion by clients attempting to use subspecs.

If I had to choose I would probably go with the option outlined in the screenshot. It seems like it would make more sense in practical use, although slightly less sense when strictly thinking that the group structure should mirror the file system.

**Comment by sanghavan** [comment]
This only occur on local podspec (Development Pods).

**Comment by segiddins** [comment]
I really don't know how to reconcile subspecs and reflecting the file system :/ Thoughts, @orta?

**Comment by orta** [comment]
Given that `Pod/Classes` is a default, we could whitelist that exact combination for skipping when creating the dev pod groups, killing 90% of the problem and still respecting the folder layout people use. 

The older version which was just a flat map of all files per specs a lot like above and it got hard with dupes, and general size.
