### ISSUE TITLE
pod install not working after upgrading to OS X Yosemite with xcode 6.3

### ISSUE THREAD

**Issue by afriedman94** [CocoaPods/CocoaPods#3425]
I am getting this error upon attempting to to install a pod

     /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such           -- xcodeproj/prebuilt/universal.x86_64-darwin14-2.0.0/xcodeproj_ext (LoadError)
	    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.16.1/lib/xcodeproj/ext.rb:6:in `rescue in <top      (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.16.1/lib/xcodeproj/ext.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.16.1/lib/xcodeproj.rb:30:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.32.1/lib/cocoapods.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.32.1/bin/pod:32:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'

I have tried uninstalling then reinstalling cocoapods. I get this response. 

     ERROR:  While executing gem ... (Errno::EEXIST)
    File exists @ dir_s_mkdir - /usr/local/Cellar/ruby/2.1.2/lib/ruby/gems

**Comment by neonichu** [comment]
The first error is a result of the C extension needing to be rebuilt after an OS update. This happens because you were using a very old version of CP (0.32.1) - newer versions to no longer require C extensions.

Can't specifically pinpoint the cause of the second error, as a lot of context is missing, but it looks more like an issue with your local ruby installation than CP itself.
