### ISSUE TITLE
Validate module maps by -Wincomplete-umbrella

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#3428]
##### Extracted from https://github.com/CocoaPods/CocoaPods/pull/3004#issuecomment-93713933:

We could add [`-Wincomplete-umbrella`](http://clang.llvm.org/docs/Modules.html#header-declaration) to all generated Pod targets:
>Any headers not included by the umbrella header should have explicit header declarations. Use the -Wincomplete-umbrella warning option to ask Clang to complain about headers not covered by the umbrella header or the module map.

This could help to find misconfigurations of the header visibility in the podspec with `pod [spec|lib] lint`. This could also be helpful in combination with custom modulemaps or we disable it in that case and don't add this additional flag for warnings. But the documentation doesn't cover how clang handles `project` headers, which are since #3145 possible with CocoaPods, by adding headers in the `source_files` of a podspec, which are neither matched by `public_headers` nor by `private_headers`.

**Comment by mxcl** [comment]
For PromiseKit 2 I intend to have a header that is *not* in the umbrella header. It’s my method for having stuff on the objective c version of a promise that isn't on the Swift version.

**Comment by mrackwitz** [comment]
@mxcl: Thanks for leaving your feedback. I saw on your `2.0` branch, that you have now a custom modulemap. I think with the header exclusions, you would be good to go as the headers are explicitly covered. Is the new podspec working for you?

**Comment by mxcl** [comment]
Yes, sorry I meant to return and say, custom module map proved good enough so it would be fine for this warning to be enacted even for edge cases like mine.
