### ISSUE TITLE
Should beta versions really be advertised?

### ISSUE THREAD

**Issue by clemensg** [CocoaPods/CocoaPods#3434]
Hi, I am a little bit annoyed by the advertising of beta versions with every pod command.

Can we please either do this only for release candidate versions or add some switch to turn this "feature" off?

Or at least don't show it with every command, once a day would also be enough.. right?

https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/sources_manager.rb#L269

**Comment by neonichu** [comment]
As an open source project, we need to encourage users to test those betas, that's why these messages exists. If they don't get tested, actual stable releases will inevitably be more buggy.

**Comment by orta** [comment]
You can remove it, we've not documented this outside of the source code though, https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/config.rb#L7-L12

**Comment by clemensg** [comment]
Thank you very much @orta !

**Comment by kylef** [comment]
@clemensg As we are not 1.0 yet, this still makes sense to have. We may revisit this once a 1.0 of CocoaPods it out and our release plans change.
