### ISSUE TITLE
[0.37.0.beta.1] Caching of downloader breaks with `prepare_command` contract

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#3435]
The new caching of the downloader introduces a regression by cleaning and storing the Pod before the `prepare_command` was run.

>A bash script that will be executed after the Pod is downloaded. This command can be used to create, delete and modify any file downloaded and will be ran before any paths for other file attributes of the specification are collected.
>
>**This command is executed before the Pod is cleaned** and before the Pods project is created.

**Comment by segiddins** [comment]
so the way I see it, for any pod that has a `prepare_command`, we just won't be able to clean it before caching?

**Comment by neonichu** [comment]
I'd think `prepare_command` shouldn't depend on any global state and we could run it just once before caching?

**Comment by segiddins** [comment]
@neonichu but can't the prepare command depend on the target architectures / platform, SDK, etc?

**Comment by neonichu** [comment]
I don't think it has access to those things so far. There's an open issue to support that, though: CocoaPods/CocoaPods#2115, so maybe in the interest of forward compatibility, it would be better to simply skip cleaning if `prepare_command` is present.

**Comment by segiddins** [comment]
The `PodDirCleaner` should probably just not be called if there's a prepare command, though that will mean the download cache can grow to be _huge_, because git dirs.
