### ISSUE TITLE
Framework inside embedded framework

### ISSUE THREAD

**Issue by damienpontifex** [CocoaPods/CocoaPods#3440]
I have a project using Xcode 6 with an embedded Framework target. For this target, I have one pod for it and have the use_frameworks! flag set in my Podfile.

When I run `pod install` and then eventually submit to iTunes connect for test flight testing, I get the errors:

* Invalid Bundle. The bundle at 'AppName.app/Frameworks/DataFramework.framework' contains disallowed file 'Frameworks'.
* Invalid Bundle. The bundle at 'AppName.app/Frameworks/DataFramework.framework' contains disallowed texted bundles.

Removing the 'Embed pods Frameworks' and 'Embed Pods Resources' build phases from the framework target. And then adding the scripts that were in these build phases to the corresponding build phases of the main app fixes the issue and everything works fine.

Should pods built into secondary targets have this copying phase only in the main app? Or should the folder they are copied into be called something else? I have noticed other solutions like http://zapone.org/barrie/2015/01/17/validation-error-the-bundle-contains-disallowed-file-frameworks/ that copy the frameworks into a 'Shared Frameworks' folder and the issue goes away.

**Comment by neonichu** [comment]
Seems like the script should be adjusted automatically based on target type.

cc @mrackwitz

**Comment by damienpontifex** [comment]
I also had to add $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-DataFramework to the Framework Search Paths as well so I could use some of the exposed methods from my framework in my app code.

Could other pod targets be added to the main app target in the xcconfig file to avoid this?

**Comment by neonichu** [comment]
@damienpontifex that sounds more like the issue laid out here: CocoaPods/CocoaPods#3095

**Comment by damienpontifex** [comment]
@neonichu agreed, my second point seems to be the same. The original issue I believe is still separate though.

**Comment by neonichu** [comment]
@damienpontifex yah, totally - it seems like the script generator should be adjusted to take care of it. Thanks for reporting!

**Comment by RedPlumber** [comment]
Hi all,
I think I have similar problem (or similar to https://github.com/CocoaPods/CocoaPods/issues/3095) and I created a sample project.
As I explain in the readme file, everything is fine on the master branch but I have a problem in develop branch adding a different kind of pod.. can you please help me with https://github.com/RedPlumber/SwiftProject ? Thanks

**Comment by maxmouchet** [comment]
I had the same `Invalid Bundle` problem and I can confirm that moving the frameworks and resources scripts to the main app's target fixes it :+1:

**Comment by RedPlumber** [comment]
@maxmouchet the error I am getting just on "Develop" branch of my example project is 
"dyld: Library not loaded" 
the goal of my project is to use the pod inside the embedded framework and also expose it outside.

**Comment by patricks** [comment]
I also get the "dyld: Library not loaded" error. Any ideas how to fix this?

**Comment by damienpontifex** [comment]
@patricks that would normally be because the framework hasn't been copied inside the application. Check it is copied either via the Embed frameworks build phase or by the cocoa pods copy frameworks shell script

**Comment by patricks** [comment]
I have removed the build this 2 build phases from the extension target (watchkit), because if I have a framework folder in my extension, apple rejects my upload.

**Comment by neonichu** [comment]
@patricks are you using Xcode 7? => #3661

**Comment by patricks** [comment]
@neonichu no, I have installed Xcode 7, but don't use it with this project.

**Comment by RedPlumber** [comment]
All issues have been fixed on my sample project with latest cocoa pods beta version 0.38.0.beta.2
check out https://github.com/RedPlumber/SwiftProject

**Comment by piercifani** [comment]
I had to manually remove the `Embed Pods Frameworks` from the .framework target even when using `Cocoapods 0.38.0.beta.2` in order to fix this issue

Sample Podfile:

```
target :SampleApp, :exclusive => true do

pod 'Cartography'

end

target : SampleAppKit, :exclusive => true do

pod 'Alamofire', '~> 1.2.0'

end
```

**Comment by neonichu** [comment]
@piercifani Yes, you should rather create a private podspec for "SampleAppKit" and declare its dependencies in there.

**Comment by piercifani** [comment]
@neonichu that seems odd: you're saying that in order to use a Pod from a Framework, the Framework itself has to be built as a Pod? 

Shouldn't it work like if it's an App target, then embed all the Pod's frameworks, else just link the Pod's frameworks so it can compile?

**Comment by neonichu** [comment]
It's not that easy, in order for this to "just work", CP would need to do a recursive analysis of dependencies in your Xcode project and also somehow ensure that you would never use the build product in another context. Adding the framework as a Pod itself on the other hand ensures that the dependency graph is known from the Podfile contents itself.

**Comment by piercifani** [comment]
Ok, I get it now. I'll start moving my `SampleAppKit` to a Pod right away 😁

However, it does sounds like the kind of tradeoff people should know right before starting to work with Cocoapods and Frameworks. This limitation should be made more explicit, otherwise people are going to realise this limitation when uploading to the App Store, and they could lose it trying to find out what's exactly going on.

Do you think that's a good idea?

Thanks a lot @neonichu !

**Comment by neonichu** [comment]
That's a good point, maybe we could have a warning that recommends users to create a private Pod if they integrate a framework target?

CC @orta

**Comment by orta** [comment]
> That's a good point, maybe we could have a warning that recommends users to create a private Pod if they integrate a framework target?

As in "You're integrating CocoaPods frameworks into a Frameworks target. it is recommended that you convert this to a CocoaPod in order to ensure [...]" ?

**Comment by neonichu** [comment]
Yah, something like that.

**Comment by m1entus** [comment]
As @piercifani said i had to manually add Embed Pod Frameworks script for Build Phases of my target.

**Comment by sarunw** [comment]
Just got the same error, so the solution is turn my framework to a private pod? Can anyone guide me to the best solution. pod 0.39

```
ERROR ITMS-90206: "Invalid Bundle. The bundle at 'my-app-name.app/Frameworks/my-app-name-kit.framework' contains disallowed file 'Frameworks'.
```

**Comment by FelixII** [comment]
@sarunw The solution for me was to go into the build settings of my framework target and set the EMBEDDED_CONTENT_CONTAINS_SWIFT flag to 'No'. I now get warnings during 'pod install' but the build and upload works just fine.

There is an open issue discussing this approach:  https://github.com/CocoaPods/CocoaPods/issues/4515
