### ISSUE TITLE
"The signature of CLAide#arguments has changed" warning

### ISSUE THREAD

**Issue by natanrolnik** [CocoaPods/CocoaPods#3442]
When running **any** CocoaPods command, I get the following warning (in yellow):

`[!] The signature of CLAide#arguments has changed. Use CLAide::Argument (Pod::Command::Open: [["-a", :optional]])`

I already updated, uninstalled/installed and it keeps showing. Any idea of what's the reason of this warning?

Thanks for all the efforts for the iOS Community.

**Comment by segiddins** [comment]
@natanrolnik what's the output of `pod plugins installed`? It's likely you're using an outdated plugin.

**Comment by natanrolnik** [comment]
@segiddins indeed. I was using version 0.0.7 of cocoapods-open and needed to install cocoapods-open-0.0.8. Having a better way to understand the problem would be ideal.
