### ISSUE TITLE
Module not being detected in Swift (No such module)

### ISSUE THREAD

**Issue by pablolvillar** [CocoaPods/CocoaPods#3443]
🌈

I'm trying to integrate a private repo (named *IdeoLib*) that has a podspec and uses its own dependencies (such as *GoogleAnalytics-iOS-SDK*, *MBProgressHUD*, *NMRangeSlider*, etc) through [cocoapods](https://github.com/cocoapods/).

I've already followed [these](http://guides.cocoapods.org/making/private-cocoapods.html) steps.

Everything works fine when I execute `pod install` on the project at which I want to integrate *IdeoLib*, but I'm not able to compile it... When trying to compile I get:

***No such module 'IdeoLib'*** at the `import IdeoLib` statement.

Already did clean, removed derived data folder, quit Xcode, restarted computer... Nothing of that seems to solve the problem. Spent the whole day looking for a solution but couldn't make it work.

**Note: I'm using Xcode 6.3 and Cocoapods 0.36.4. IdeoLib is written in Swift, so the project I'm trying to integrate it into. (I also tried with Xcode 6.1 and it doesn't work either).**

**Comment by segiddins** [comment]
@pablolvillar to debug this sort of issue, we'd really need to be able to access the project. My guess is that it's unable to build as a module because some header dependency isn't being satisfied.

**Comment by pablolvillar** [comment]
Hello @segiddins , thanks for answering.

I've found out that the problem is in the *IdeoLib* framework. 

The 'why' the module isn't found is because it isn't actually being generated. The framework can't be compiled.

I'm getting the popular **Include of non-modular header inside framework module 'XXXXX'** compiler error. I've been deeply investigating this issue and trying lots of possible solutions without any positive result.

Since I can't give you access to the *IdeoLib* repo, what I did is I created an example from scratch (kind of empty) project with a framework target that ends up throwing the same error.

This sample project only contains a basic podfile configuration to use the *MBProgressHUD* dependency. When I try to use it, I get the compiler error mentioned above.

Just in case, I think it's worth it to clarify that I don't have this issue when working on an *application target* instead of a *framework target*.

You can find the sample project [here](https://github.com/inaka/swift-cocoapods-issue-example/).

My idea is that it's likely the same solution would apply to the *IdeoLib* framework, since the issue seems to be the same.

Let me know if you need anything else...
Thanks in advance.

**Comment by neonichu** [comment]
So, the issue in your example project is this:

```diff
-#import <MBProgressHUD.h>
+#import <MBProgressHUD/MBProgressHUD.h>
```

Custom frameworks need to be referenced with their module name, just like system frameworks.
