### ISSUE TITLE
EEXIST - File exists  workspace/Pods

### ISSUE THREAD

**Issue by jimpeters145** [CocoaPods/CocoaPods#3446]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.36.4
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.4.6
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a881068b1f8b97ee8a5cfbfc4ed7dcde3d397d17
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, "7.0"

target 'HIMSS' do

pod 'AFNetworking', '2.5.2'

end

target 'HIMSSTests' do

end
```

### Error

```
Errno::EEXIST - File exists - /Users/jenkins/dev/jenkins/workspace/HIMSS-iOS/Pods
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/sandbox.rb:54:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/config.rb:169:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/config.rb:169:in `sandbox'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command/project.rb:69:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.4/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by jimpeters145** [comment]
Running Cocoapods plugin in Jenkins

**Comment by segiddins** [comment]
Do you have a `Pods` file instead of a directory?

**Comment by jimpeters145** [comment]
I had a Pods file, then deleted it and got the same error

**Comment by kylef** [comment]
It would seem that something outside of CocoaPods is creating this file called Pods causing CocoaPods to fail. Would you be able to do some digging and see if anything is creating this file.

Confirm that the following works or not:

```bash
rm -fr Pods
pod install
```

**Comment by segiddins** [comment]
I'm not sure if this is a case we really want to handle inside CocoaPods?

**Comment by segiddins** [comment]
(but if we want to, the following ought to do the trick)

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 40cc941..488b078 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -200,4 +200,4 @@ DEPENDENCIES
   xcodeproj!
 
 BUNDLED WITH
-   1.10.0
+   1.10.2
diff --git a/lib/cocoapods/sandbox.rb b/lib/cocoapods/sandbox.rb
index e301553..7b44845 100644
--- a/lib/cocoapods/sandbox.rb
+++ b/lib/cocoapods/sandbox.rb
@@ -55,8 +55,10 @@ module Pod
     # @param [String, Pathname] root @see root
     #
     def initialize(root)
-      FileUtils.mkdir_p(root)
       @root = Pathname.new(root).realpath
+      @root.rmtree if @root.file?
+      @root.mkpath
+
       @public_headers = HeadersStore.new(self, 'Public')
       @predownloaded_pods = []
       @head_pods = []
```

**Comment by morph85** [comment]
Similar issue happened when I have a common library linked to 2 targets (an app and an app extension), the export with bitcode failed. 0.39 and 1.0.0 beta-2 both doesn't work.

Error: An error occurred during export

`ipatool failed with an exception: #<Errno::EEXIST: File exists - /var/folders/st/lbdy0w497l544lncz5wbrshm0000gn/T/ipatool20160203-13333-v71mw/MachOs/iphoneos/armv7/(dylibs)/FLAnimatedImage>
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:93:in `initialize'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:93:in `open'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:93:in `createExclusive'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1455:in `block (2 levels) in CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1445:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1445:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1440:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1440:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1500:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1499:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1499:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1500:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1499:in `each'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1499:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:1687:in `ProcessIPA'
    /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2210:in `<main>'`

**Comment by lizeray** [comment]
same issue 1.0.0 beta-2

**Comment by AnthonyMDev** [comment]
I'm having this issue now on `1.1.0.rc.2` and the command from @kylef above didn't solve it. Any other suggestions?

**Comment by AnthonyMDev** [comment]
Got it fixed using @benasher44 's suggestion from #5804

**Comment by zirinisp** [comment]
same issue on 1.1.0.rc.2

**Comment by jtdavid** [comment]
Same issue.

**Comment by ArtSabintsev** [comment]
Getting this in 1.1.0.rc.2 as well

**Comment by jtdavid** [comment]
This is only happening for shared pods between targets...

**Comment by ArtSabintsev** [comment]
That's good to know - we share a ton of Pods between a few targets.

**Comment by ArtSabintsev** [comment]
Yup, commenting out the other targets that share pods got it to install.

**Comment by jtdavid** [comment]
Yes, I confirm. Can't find anyone with the same issue yet. Tried to change "Use Legacy Swift Language Version" do "No" and "Yes" and still the same. It was "No" by default...this SWIFT_VERSION seems to be the solution for everyone but not for me (or us)...

**Comment by jtdavid** [comment]
I think because we share pods between target we end up in a different bug... not quiet sure.

**Comment by ArtSabintsev** [comment]
This is definitely the bug - the sharing of at least one repository between multiple targets throws the FILE EXISTS error in 1.1.0.rc.2 and on the master branch.

**Comment by jtdavid** [comment]
Should we fill in a new issue?

**Comment by ArtSabintsev** [comment]
Sure, I'll make one and link this one.

**Comment by jtdavid** [comment]
Thanks. I will follow up and help on that one.

**Comment by benasher44** [comment]
This is mostly a dup of #5864. The issue is that CocoaPods doesn't properly handle swift targets and non-swift targets that share pods. You can workaround this by just setting `SWIFT_VERSION` on your non-swift targets to be the same as your swift targets. I plan on fixing this issue for rc3

**Comment by benasher44** [comment]
In any case, it's known and will be addressed shortly!

**Comment by ArtSabintsev** [comment]
Ah good to know. I just opened: https://github.com/CocoaPods/CocoaPods/issues/5942 for clarity without seeing that post.

**Comment by jtdavid** [comment]
@benasher44 thanks for the input!

**Comment by jtdavid** [comment]
@benasher44 In my case I have a Framework target (objC) and a app target (Swift). Both share pods. Where/how can I change SWIFT_VERSION on my Framework target?

**Comment by benasher44** [comment]
You can set it in an xcconfig. I think there's also a user-defined flags section in the build settings for your target, and you could add it there as well.

**Comment by jtdavid** [comment]
@benasher44...I got it...user-defined as you specified. Thanks!

**Comment by jtdavid** [comment]
@benasher44, @ArtSabintsev it's working now! That would work until we have RC3. Thank you all again ;) great community.

**Comment by crossle** [comment]
When RC3 release?

**Comment by fbernaly** [comment]
I got the same error, but I tried

```
rm -fr Pods
pod install
```

and it worked!!!
