### ISSUE TITLE
Running pod install doesn't update pods

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [CocoaPods/CocoaPods#3447]
I have version 0.36.4 installed. In the Podfile`, I haven't specified the specific versions.

```
use_frameworks!
platform :ios, '8.0'

pod 'Facebook-iOS-SDK'
pod 'googleplus-ios-sdk'
pod 'IHKeyboardAvoiding'
```

Which means every time I run `pod install`, it should check each pod if they have a newer version and reinstall it, right? It doesn't happen. This is a Swift project by the way.

I have to remove the entire pod and reinstall it to get the latest version.

Is this a known bug that's been worked on?

**Comment by segiddins** [comment]
You have to run pod update if you want to update your pods. Pod install installs the versions specified in your Podfile.lock.
