### ISSUE TITLE
Add CLI option to list installed packages and versions

### ISSUE THREAD

**Issue by r3mus** [CocoaPods/CocoaPods#3448]
Per [this question](http://stackoverflow.com/questions/29783234/list-installed-cocoapods-and-versions/29787648#29787648) it would be really handy to quickly list installed packages and versions. Could even take this one step further by allowing for a dif between what a `pod install` would do and the current versions.

Something like:

`pod list installed`
`pod install check`

**Comment by segiddins** [comment]
@r3mus that's essentially what `pod dependencies` (provided by cocoapods-dependencies) and `pod outdated` do.

**Comment by r3mus** [comment]
Ah, wasn't aware of cocoapods-dependencies. Would be awesome to see that rolled into the main project ;)
