### ISSUE TITLE
Submission errors from Pods-<prjname>-resources.sh copying over .sh files

### ISSUE THREAD

**Issue by langford** [CocoaPods/CocoaPods#3449]
Apple on 4/22/2015 started checking for unsigned .sh files in iOS apps submitted to iTunes Connect.

If you use a Crittercism Pod (or others with .sh files I assume), you can have a problem where [Appname.App/scriptname.sh] gets a submission error when trying to "upload to app store" for test flight or the app store.

Adding the following lines appears to fix it

    *.sh)
      echo "Skipping $1 to not get signing bug from 4/22/2015"
      ;;

This is between the /* and * case in the .sh file. I'll try to get a patch together later this week if someone else doesn't want to fix it before then.

**Comment by langford** [comment]
ITMS-90035 is the name of the error you get on submission from this bug

**Comment by daveanderson** [comment]
I added it here
```
    *.xcassets)
      ;;
    *.sh)
      echo "Skipping $1 to not get signing bug from 4/22/2015"
    ;;
    /*)
      echo "$1"
      echo "$1" >> "$RESOURCES_TO_COPY"
      ;;
    *)
```

**Comment by langford** [comment]
This might just be a Crittercism issue https://twitter.com/robkwok/status/590921241772457984, but I'll probably make the patch anyhow: I don't see why iOS apps need unsigned scripts in them

**Comment by segiddins** [comment]
This is definitely a Pod issue.
