### ISSUE TITLE
How to remove the libPods.a from my project in the `post_install`?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3450]
I have a script to build the Pods project, it will speed up the Pods build. So I want to remove the libPods.a  after `pod install`.

I try to use the `pod install --no-integrate`, but there is a wrong `PODS_ROOT` in the xcconfig and I hope integrate the `xcconfig` and `Check Pods Manifest.lock` in my project. so the `--no-integrate` is not what I want.

Anybody can tell me how to remove the `libPods.a` from my project in the `post_install`?

**Comment by segiddins** [comment]
I think using `--no-integrate` is going to be the supported answer to this question.
