### ISSUE TITLE
How to use CP to manage the script repo?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3451]
I have a repo which there are some shell scripts and they are used by the Xcode, so the scripts are neither the resouces nor the source files.

How to use CP to control the script version? I hope update them with CP.

**Comment by segiddins** [comment]
That's not really what CocoaPods is meant for, so you'd probably have to make your own plugin to do that.

**Comment by Whirlwind** [comment]
But the script is to the project, I mean that the script will add the `build phases`, so it is not a plugin

**Comment by segiddins** [comment]
I'm not really understanding.

**Comment by Whirlwind** [comment]
I have a repo.
There are some shell scripts in the repo.
Now, I add them by go to the target -> Build Phases -> New run script, add the script path.
I hope I can use the CP to control the script version, and auto add them to other project by command line.

**Comment by Kapin** [comment]
@Whirlwind are you essentially saying you have some scripts you wrote in bash and want to make them into a pod to use in multiple iOS/OSX projects? I don't believe that is supported.

**Comment by Whirlwind** [comment]
@Kapin yes.
I think that the scripts have many versions, some dependencies and other somethings like any pods.
So I want to make them into a pod. The CP just clone, then I manual add to the `build phases`. But I don't known how to write the podspec. Because the script is not a resource ( will not be copied to app bundle ), and it is not a source file ( will not compiled). The script files just clone into the Pods fold.

**Comment by Kapin** [comment]
I agree with @segiddins that this is not what CocoaPods is meant for. I'd suggest using git submodules.
