### ISSUE TITLE
Inconsistent Podfile.lock files between Ruby versions

### ISSUE THREAD

**Issue by cbrauchli** [CocoaPods/CocoaPods#3452]
🌈

It looks like the `Podfile.lock` has different path strings for development pods depending on which version of Ruby is being used. 

On Ruby 2.2.2:

```
EXTERNAL SOURCES:
  MobileShared:
    :path: "./mobile-iphone-shared"
```

On Ruby 2.0.0:

```
EXTERNAL SOURCES:
  MobileShared:
    :path: ./mobile-iphone-shared
```

**Comment by segiddins** [comment]
So, this is happening because I'm using Psych to encode strings before they get into the lockfile, and I _think_ the inconsistency is coming for psych. I'm really not sure what we can do about this.

**Comment by segiddins** [comment]
I opened an issue on Psych at https://github.com/tenderlove/psych/issues/232, but I think I can do something to avoid re-writing the file if the contents is, other than the quoting difference, exactly the same. It won't save you from irrelevant diff lines, but it could mean that `pod install` can avoid dirtying your git status. Would that be worth doing?

**Comment by cbrauchli** [comment]
@segiddins I think so. People not familiar with the Podfile.lock might assume that they've done something wrong to change it.

**Comment by segiddins** [comment]
@cbrauchli in that case, https://github.com/CocoaPods/Core/commit/51334721f5754e561d6f98cfc7f632db9ce49f8e should help! It won't save you from longer diffs, but it will hopefully mean that, when the semantic contents of the lockfile haven't changed, the file won't change the quotes.

**Comment by cbrauchli** [comment]
Works for me! Is there any chance this change will make it onto the `0.36` branch or will we have to wait for `0.37`?

**Comment by segiddins** [comment]
I don't know if we'll have another 0.36 release, since releases take a few hours, but that's probably @kylef's call.

**Comment by cbrauchli** [comment]
This is till happening in `0.37.1` and I noticed tenderlove/psych#232 is closed as invalid. Can we expect a long-term fix in CocoaPods or is the solution to get everyone on the same Ruby version?

**Comment by segiddins** [comment]
It's not really a problem CocoaPods can fix, unfortunately. Both are valid YAML files.
