### ISSUE TITLE
Can :head in podfile make a cache for downloaded version

### ISSUE THREAD

**Issue by foobra** [CocoaPods/CocoaPods#3459]
In inner-enterprise develop, we use private cocoapods trunk to store modules. Our modules are bleed-edge, and it's tedious to "modify module codes - change podspec version - push to private trunk - main app workspece execute pod update'

We use :head in Podfile, and we can always get the latest module codes, but there is only one problem: when I pod update, the pod downloader will download the latest commit of moudle no matter it changed or not.

So I think could cocoapods cache the last :head sha1 string, and the next time I execute pod update, the pod downloader will check the :head sha1 string and compare with the cache value. If it's not changed, just skip. If it changed, download the lastest commit. It will significate speed up the pod update, and save us lots of time, thx

**Comment by neonichu** [comment]
Caching is coming in a future release, see #3236
