### ISSUE TITLE
Embeding binary framework with cocoapods

### ISSUE THREAD

**Issue by DaliborK** [CocoaPods/CocoaPods#3461]
I have binary framework which I would like to distribute using Cocoapods. I am able to add the framework to the project but having trouble linking it. Any thoughts if this is possible?

**Comment by neonichu** [comment]
If it is a static "fake" framework, see <https://github.com/layerhq/releases-ios/blob/master/LayerKit.podspec> for an example. If it is a dynamic framework, they're not fully supported at the moment, see #1993
