### ISSUE TITLE
Podspec xcconfig values are not applied to aggregate/user targets when integrating with frameworks

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#3465]
If a podspec declares e.g. a preprocessor definition in a xcconfig, it used to be applied to the aggregate target. The aggregate target's xcconfig is shared with the integrated user target, so that the defintion is applied also to the user target. This behavior is not exactly documented in the DSL, but there are podspecs out there as e.g. [Braintree's iOS SDK](https://github.com/braintree/braintree_ios), which rely on that. With the integration with frameworks, this possibility to inject build settings to the user target broke, because it happens in the context of linking vendored framework and libraries, which doesn't need to happen for frameworks over the aggregate target's xcconfig, because they are linked on their own.
In general there is the issue with the prior behavior, that those definitions could be conflicting, because they are not namespaced, which relates to #2467. Conflicts for build settings, which take multiple values, could be potentially resolved by just including all values (while the presence of some common named preprocessor definitions could have potentially unexpected side-effects to other Pods), but multiple specifications for single-value build settings should let the integration fail or at least warn the user about the conflict.
It could make sense with frameworks to split the Podspec DSL attribute into two separate attributes:
* `xcconfig`: is only applied to the pod target
* `user_target_xcconfig`: is only applied to the aggregate target

/c @orta @AliSoftware

**Comment by neonichu** [comment]
I'm for splitting it up, but if we change the behaviour, the old attribute should be deprecated completely and not change its behaviour.

So I'd say let us use `pod_target_xcconfig` instead of `xcconfig`, keep the current behaviour of `xcconfig` for static libraries for one release and then completely remove that attribute.

**Comment by orta** [comment]
> So I'd say let us use pod_target_xcconfig instead of xcconfig, keep the current behaviour of xcconfig for static libraries for one release and then completely remove that attribute.

:+1:

**Comment by mrackwitz** [comment]
When implementing this functionality, I realized again, how much can go wrong, when we allow in podspecs to add arbitrary build settings to the user target, what we do at the moment. These settings should remain largely in the control of the user. I think, it is a first step, to make it more explicit, what happens with these build settings and keep the effects separated, but we should also think about restricting the possibilities.

With static libraries, it makes sense to allow access to the linker build settings as a static library isn't linked by itself. If you need access to build settings, which influence the compiler frontend, then there is mostly something wrong about the encapsulation of the interface.

I put a [gist with data of all podspecs in the master repo](https://gist.github.com/mrackwitz/54e0d00c0e6ed7330d9b) together to see, which build settings are used.

**Comment by AliSoftware** [comment]
We should totally get rid of that `xcconfig` in the next DSL.

**Comment by mrackwitz** [comment]
>We should totally get rid of that `xcconfig` in the next DSL.

@AliSoftware: That may sound tempting from maintaining CocoaPods, but is not really feasible.

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/issues/3573!

**Comment by 0xced** [comment]
@mrackwitz It looks like you missed platform dependent xcconfig definitions in your script, see https://github.com/0xced/XCDYouTubeKit/blob/2.2.0/XCDYouTubeKit.podspec#L17 for example.
