### ISSUE TITLE
[QUESTION] Reference local pods from other local pods in a single repo.

### ISSUE THREAD

**Issue by tabuchid** [CocoaPods/CocoaPods#3470]
I'm working on a project where we are breaking functionality out into pods that are shared between multiple apps. 
The code is proprietary so we have to use private pods.
At the same time to ease development, deployment and reviews we have been experimenting with a monolithic repo for all the apps and some of the pods.
This was all working fine till we hit the issue that you can't reference a pod by a path in a podspec.
This is what the structure looks like.

```
app1
  depends on shared_components, shared_api
app2
  depends on shared_components, shared_api
app3
  depends on shared_components, shared_api
app4
  depends on shared_components, shared_api, lib_1
shared_components
 depends on shared_api, lib_1
lib_1
  standalone_pod
shared_api 
  standalone_pod
```

The problem I'm having is the shared_components pod project. I'm unable to have its podspec reference lib_1 and shared_api because podspecs can't reference dependancies locally.
Am I missing something or is there a better way?

**Comment by kylef** [comment]
I think it would make far more sense to create your own private spec repository. Then you can use it like so:

```ruby
source 'https://github.com/artsy/Specs'

pod 'Artsy+UILabels'
```

Note, `Artsy+UILabels` depends on another private pod (https://github.com/artsy/Specs/blob/master/Artsy%2BUILabels/1.3.1/Artsy%2BUILabels.podspec#L18). The benefits for this approach is it's far simpler and you get proper version management of the pods.

**Comment by tabuchid** [comment]
We had that in place before trying this single-repo approach. The downside is if you make a change to a library that affects multiple apps then you end up with a PR for the library change, and one for each app that has to incorporate the change. This is fine for public libraries but not for internal ones this is added time and complexity for the reviewer and the developer.

**Comment by tabuchid** [comment]
Ok, Even with separate pod repos, and a podspec repo what is the best workflow for the follow scenario?

You have 1 app and 2 pods.
MyApp which depends on MyLoginVC which depends on MyNetworkClient.
You are working on a bug that involves making changes in all 3 projects so you want to setup your dev env to work off of all 3 locally. Is the only option to specify that in the Podfile of MyApp?

**Comment by neonichu** [comment]
Yes, you would set up your Podfile to reference MyLoginVC/MyNetworkClient as development Pods via `:path`, then you would be able to work on all three from the app's Xcode project.
