### ISSUE TITLE
Build fails if project target name contains space

### ISSUE THREAD

**Issue by wesoo** [CocoaPods/CocoaPods#3474]
Hi, as the subject, I have a problem when I compile the project after installing a dependency with cocoapods. The error is: "ld: library not found for -lPods-Project validation."
The problem seems to be derived from space in the target name. I have two targets and I need to add dependency for both.

I have last version of cocoapods.

Thanks

**Comment by neonichu** [comment]
Spaces in target names are generally not a problem. If your target is called "Project validation", linking against "libPods-Project validation.a" would be correct.

Please share a bit more info like your Podfile, an example project, etc. - see [our contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#bug-reports) for more info.

**Comment by wesoo** [comment]
I have modified my Podfile like this: 
xcodeproj '../Drinkout.xcodeproj/'

# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'Drinkout validazione' do
    pod 'Braintree'
end

target 'Drinkout test' do
    
end

target 'Drinkout' do
    pod 'Braintree'
end

Rerunned 'pod install' and now my target 'Drinkout validazione' works fine, but when build 'Drinkout' (production target) i receive another error: "ld: library not found for -lPods". The configuration of the target seems equal!

In a "Link binary with libraries" have:
Drinkout validazione: libPods.a and libPods-Drinkout validazione.a are missing but this target compile.
Drinkout: have libPods-Drinkout.a and missing libPods.a but this target doesn't compile.

**Comment by neonichu** [comment]
Hm, there shouldn't be a libPods.a in play at all with this Podfile. I'm thinking it is some artefact of reshuffling the Podfile which hasn't been removed properly by CP.

Could you try running <https://github.com/kylef/cocoapods-deintegrate> to reset and the redoing the `pod install`?

**Comment by wesoo** [comment]
Okay, deintegrate command and again pod install works fine!

Thanks!!!
