### ISSUE TITLE
Clarify linter message

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/CocoaPods#3476]
It seems to be a common assumption that linting will only fail on errors, not on warnings (see #3475 for an example). I think we should clarify the message in case there are only warnings.

Current message:

```
[!] The spec did not pass validation.
```

My proposal:

```
[!] The spec did not pass validation, due to 75 warnings.
```

**Comment by segiddins** [comment]
Should probably also mention the number of errors, and that `--allow-warnings` exists if there are warnings but no errors.

**Comment by neonichu** [comment]
If we mention `--allow-warnings` we should... warn against using it, though

**Comment by orta** [comment]
I agree with ^ - let's do this
