### ISSUE TITLE
`pod lib lint` fails for JSON podspecs

### ISSUE THREAD

**Issue by irace** [CocoaPods/CocoaPods#3477]
Spits out the following error:

```
[!] Unable to find a podspec in the working directory
```

Surprisingly, `pod spec lint` does seem to work.

**Comment by segiddins** [comment]
What version of CocoaPods? Are you manually specifying the podspec file to lint? Do you have a reproducible case?

**Comment by irace** [comment]
@segiddins :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:
