### ISSUE TITLE
'Depends on' section on cocoapods.org generates broken links

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/CocoaPods#3484]
For pods that have dependencies, cocoapods.org displays links to the dependencies in the 'Depends on' section. 

It is currently generating links to other pods with `pod` in the URL instead of `pods` -- e.g. http://cocoapods.org/pod/AFNetworking instead of http://cocoapods.org/pods/AFNetworking . This results in all dependency links being broken.

**Comment by segiddins** [comment]
This belongs on https://github.com/CocoaPods/cocoapods.org

**Comment by hkellaway** [comment]
thanks, i'll move it
