### ISSUE TITLE
Targets that have dependencies removed from podfile fail to build

### ISSUE THREAD

**Issue by marcpalmer** [CocoaPods/CocoaPods#3485]
If you have a target that once had dependencies, but then later does not because of a change of plan, your project fails to build even after running `pod install` again.

This is because Cocoapods installed build phases to check the pods manifest, embed frameworks and copy pods resources for the target. These fail when there are no dependencies for the target.

This problem is rather ugly because to make your target build again you have to remove those three Build Phases. Therefore if you later add a Pod dependency to that target again in future, you will have obscure problems because the required Pods Build Phases are not present.

This is because running `pod install` after adding a dependency onto this target again will not re-add the Build Phases to it.

Tested with latest Cocoapods 0.37.0 release.
 
My suggestion is to make have Cocoapods continue to generate an empty manifest if the target is declared in your main Podfile, even if it has no dependencies, and ensure that the Embed Pods Frameworks and Copy Pods Resources scripts do not choke if there is nothing to do.

*Update*: Even when you've done all of this to "unwind use of pods in a framework", you then get failures during archiving because the Pod_XXXX.frameworks are linked still and you have to remove these from every target too. Sounds like 1st-world problem for sure... but in the world of apps with multiple app extensions, plus watchkit extensions and your own internal dynamic frameworks, this ends up being really quite tiresome.

[FYI I ended up in this situation because I had to stop using pods on my dynamic frameworks and app/watch extensions because of the problem of duplicate embedded frameworks for which there appears to be no fix yet?]

**Comment by marcpalmer** [comment]
The *good* news here is that after fixing the dupe dylibs and removing all the failing Pods_XXX deps and Pods scripts on targets other than my main App target, my app now Archives in such a way that it appears in Xcode Organizer whereas it was archiving before but not appearing there. I presume this is because of the lack of duplicate embedded frameworks now. (see https://github.com/CocoaPods/CocoaPods/issues/3240)

**Comment by neonichu** [comment]
You can use <https://github.com/kylef/cocoapods-deintegrate> to fully deintegrate your project and then run `pod install` with your updated Podfile. Targets which don't link to the Pods framework or static library will be integrated when running `pod install`.

**Comment by marcpalmer** [comment]
Thanks @neonichu that's very handy to know. Feels like this work should be included for the case when pod install detects a target having no dependencies where it previously did.

**Comment by kylef** [comment]
Proper target deintegration is planned, but simply hasn't been implemented yet. It's tracked by #2471.
