### ISSUE TITLE
pod lib lint passes but pod repo push doesn't for a private cocoapod

### ISSUE THREAD

**Issue by abushnaq-work** [CocoaPods/CocoaPods#3496]
Hi all,

I'm using Xcode 6.3 and cocoapods 0.37 to set up a private spec repo and a private cocoapod for my company. I have the following pod spec:

Pod::Spec.new do |s|
  s.name             = "WUAuthenticationKit"
  s.version          = "0.0.7"
  s.summary          = "Authentication kit."
  s.description      = <<-DESC
                       Authentication kit.

                       * Markdown format.
                       * Don't worry about the indent, we strip it!
                       DESC
  s.homepage         = "https://github.com/TheWeatherCompany/"
  # s.screenshots     = "www.example.com/screenshots_1", "www.example.com/screenshots_2"
  s.license        = { :type => 'MIT', :file => 'LICENSE' }

  #s.license          = 'LICENSE'
  s.author           = { "Ahmad Bushnaq" => "ahmad.bushnaq@weather.com" }
  s.source           = { :git => "sourceURL.git", :tag => s.version.to_s}
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.platform     = :ios, '8.0'
  s.requires_arc = true

  s.source_files = 'Pod/Classes/**'
  s.resource_bundles = {
    'WUAuthenticationKit' => ['Pod/Assets/*.png']
  }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  s.dependency 'SSKeychain'
end

(I've obfuscated some URLs, they are private github repos). From the main directory of the pod(the one that contains the podspec file and the Pod directory), if I run pod lib lint, my pod passes just fine. However, when I attempt to push it to my repo:

pod repo push wu-pod-specs WUAuthenticationKit.podspec 

I get:
 WUAuthenticationKit (0.0.7)
    - ERROR | [iOS] The `source_files` pattern did not match any file.

I thought if pod lib lint passes it should mean I'm all set to push?

**Comment by segiddins** [comment]
Pod repo push runs pod spec lint internally-- make sure you've pushed your tag.

**Comment by abushnaq-work** [comment]
Seems like this is my deficient github/git knowledge. If I go to github and look under tags for the pod's repo, I see my tag. But when I go to the files themselves, I see the previous tag and checkin./
