### ISSUE TITLE
pod lib create always creating an example project whether I want one or not

### ISSUE THREAD

**Issue by abushnaq-work** [CocoaPods/CocoaPods#3497]
I have cocoapods 0.37 with Xcode 6.3(I have Xcode 6.4 beta on disk as well). When I run pod lib create mypod , even though I answer No to the question of whether or not I want an example project, I still get one.

**Comment by orta** [comment]
This looks legit - thanks @abushnaq-work - this is now fixed with https://github.com/CocoaPods/pod-template/commit/7d4ed907d024a9a0696264dac623c95faf105f92
