### ISSUE TITLE
Build fails with Podfile.lock & Manifest.lock diff

### ISSUE THREAD

**Issue by jhersh** [CocoaPods/CocoaPods#3502]
In 0.37 my [CI builds run `pod install` and then fail](https://circleci.com/gh/splinesoft/SSDataSources/56) with `⌦  The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

Some extra output in [this CI build](https://circleci.com/gh/splinesoft/SSDataSources/57) reveals the problem. This project includes a pod specified by `:path`.

In `Podfile.lock`:

```
EXTERNAL SOURCES:
  SSDataSources:
    :path: "../SSDataSources.podspec"
```

In `Manifest.lock`:

```
EXTERNAL SOURCES:
  SSDataSources:
    :path: ../SSDataSources.podspec
```

The quotes are not present in `Manifest.lock`. cc @segiddins

**Comment by segiddins** [comment]
The root cause of this is https://github.com/tenderlove/psych/issues/232.

**Comment by segiddins** [comment]
As far as I can surmise, the choice is between this and https://github.com/CocoaPods/CocoaPods/issues/3452

**Comment by segiddins** [comment]
We _could_ change that diff to compare the two hashes using ruby?

**Comment by neonichu** [comment]
Hm, I'd be a bit wary of using ruby in a run script, so many things could go wrong and "break" the project.  Why do the two lockfiles diverge in the first place, shouldn't they be written at the same time, by the same ruby version?
