### ISSUE TITLE
Using subspecs with different configurations (Debug, Release)

### ISSUE THREAD

**Issue by ide** [CocoaPods/CocoaPods#3503]
The React podspec has a several subspecs including the core library and a debugging library. I want to pull in both subspecs when developing, but omit the debugging subspec for release.

``` ruby
pod 'React', :path => 'react-native', :subspecs => ['Core']
pod 'React', :path => 'react-native', :configuration => ['Debug'], :subspecs => [
  'RCTWebSocketDebugger',
]
```

CocoaPods 0.37.0 tells me:

> [!] The subspecs of `React` are linked to different build configurations for the `Pods` target. CocoaPods does not currently support subspecs across different build configurations.

so I presume this is a known limitation but wanted to provide a real use case and express interest for the feature.

**Comment by kylef** [comment]
Yes, this is a known limitation. You cannot install parts of a Pod across different build configurations. A pull request to add support for this would be more than welcome.

**Comment by revolter** [comment]
I stumbled upon this warning too while trying this:

```ruby
pod 'MyKit/Debug', configurations: %w[Debug Staging]
pod 'MyKit/Release', configurations: %w[Release]
```

**Comment by hanumanAbacus** [comment]
I ran in to similar issue, I have 2 Subspec and needed to include based on build configuration, unable to find how I can achieve it
pod 'MyKit/Debug', configurations: %w[Debug Staging]
pod 'MyKit/Release', configurations: %w[Release]
