### ISSUE TITLE
CocoaPods cannot resolve files in source_files

### ISSUE THREAD

**Issue by jpsim** [CocoaPods/CocoaPods#3507]
Attempting to lint `Realm.podspec` located at https://github.com/realm/realm-cocoa/pull/1774, CocoaPods could not find several files included in the `source_files` despite being declared there:

```
$ export COCOAPODS_SKIP_CACHE=1 && pod spec lint Realm.podspec     

 -> Realm (0.91.5)
    - WARN  | The URL (https://realm.io/docs/objc/0.91.5) is not reachable.
    - ERROR | Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  |  Realm/Realm/RLMArrayLinkView.mm:19:9: fatal error: 'RLMArray_Private.hpp' file not found
    - NOTE  |  Realm/Realm/RLMAccessor.mm:21:9: fatal error: 'RLMArray_Private.hpp' file not found
    - NOTE  |  Realm/Realm/RLMArray.mm:19:9: fatal error: 'RLMArray_Private.hpp' file not found
    - NOTE  |  Realm/Realm/RLMMigration.mm:23:9: fatal error: 'RLMObjectSchema_Private.hpp' file not found

Analyzed 1 podspec.

[!] The spec did not pass validation.
```

According to @segiddins, this may be because the project files are being cleared from the cache prematurely.

/cc @segiddins @mrackwitz

**Comment by mrackwitz** [comment]
That's the problem, which occurs through the bug in the downloader cache, which is supposed to be fixed by #3498. I patched my local CP installation to validate the bugfix. So my proposed workaround didn't seem to work, actually.

**Comment by segiddins** [comment]
@jpsim did you patch the podspec as Marius' directions said to do before linting? If I follow his instructions, I cannot reproduce this.

**Comment by jpsim** [comment]
I did not follow Marius's instructions as was under the impression that they were for CocoaPods 0.37. Sorry for the trouble.
