### ISSUE TITLE
Add cache cleaning command

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#3508]
`pod cache clean [PODNAME]`

**Comment by AliSoftware** [comment]
Do you see any other `cache` subcommands that could be worth adding?

**Comment by AliSoftware** [comment]
I'm also wondering if that new `cache` command should all go in a dedicated plugin (better code separation, but is it worth it?) — even if we install it by default like we do with `cocoapods-plugins` and `cocoapods-try`

**Comment by segiddins** [comment]
No, the cache lives inside CocoaPods proper, so should the commands related to it.

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/issues/3563!
