### ISSUE TITLE
pod try appears to be broken in Cocoapods 0.37.0

### ISSUE THREAD

**Issue by pwillsey** [CocoaPods/CocoaPods#3510]
When I attempt to use pod try on any cocoapod in cocoapods v0.37.0 I get this message:

[!] Unable to find any project in the source files of the Pod: `/private/tmp/CocoaPods/Try/PODNAME`

If I go into that directory it seems like everything has been stripped out except the README.md, LICENSE and the folder containing the actual pod source files.

**Comment by segiddins** [comment]
This belongs on https://github.com/CocoaPods/cocoapods-try.
