### ISSUE TITLE
Reference to 'enum_value' is ambiguous

### ISSUE THREAD

**Issue by mergesort** [CocoaPods/CocoaPods#3511]
As documented [here](https://github.com/MortimerGoro/MGSwipeTableCell/issues/101) since I upgraded my project to `use_frameworks` in Cocoapods, I cannot reference values in enums. Any of the enum values I access throw that error. I tried following [this suggestion](http://stackoverflow.com/questions/25378474/reference-to-x-is-ambiguous/25425302#25425302), but no luck.

If I don't use frameworks, it works fine, so my suspicion is it's something to do with that.

Any help would be great!

**Comment by orta** [comment]
@ashfurrow - you seeing this?

**Comment by ashfurrow** [comment]
I have not seen this. @mergesort could you provide a small Xcode project demonstrating the bug? Versions of Xcode and CocoaPods would be :+1: too.

**Comment by mergesort** [comment]
I can't seem to recreate it in a new project, only one that it's already integrated into. I've tried cleaning, deleting derived data, removing the pod, restarting Xcode, and so on.

Something I could be missing?

![ambiguous](https://cloud.githubusercontent.com/assets/716513/7495967/52af0652-f3df-11e4-9e7b-9f56e2f96b42.png)

**Comment by ashfurrow** [comment]
Could it be linked twice somehow? Could you show the contents of the `Podfile`?

**Comment by mergesort** [comment]
Ah, yes, it was linked twice through an category.
Sorry for the hassle, thanks for the help!

**Comment by ashfurrow** [comment]
Not at all – I've done this before. It's worse when the compiler doesn't catch it, trust me.

**Comment by solidfox** [comment]
@mergesort I think I'm haveing the same issue you did. Would be super helpful if you could elaborate on how you determined that it was linked twice and what you did about it.

**Comment by orta** [comment]
@solidfox look inside your build phases, I bet it was double linked in there somewhere

**Comment by solidfox** [comment]
Searched high and low, even tried removing the `Link Binary with Libraries` phase altogether. Still getting tons of errors like `Reference to 'SDWebImageRetryFailed' is ambiguous` and `Duplicate definition of category 'WebCache' on interface 'UIImageView'`. (Not just for SDWebImage, other pods as well.)

**Comment by muppetkermit** [comment]
Updated cocoapod to 1.2.0 and pod update. Now have same issue for AFNetworkReachabilityStatus enums. Anyone have same issue?

**Comment by benasher44** [comment]
@solidfox if you could post a Podfile and/or a Sample project, that'd be super helpful. Thanks!

**Comment by fedser** [comment]
I have similar problem with enum, but I solved it. I have local pod, and in main Podfile I have option "use_frameworks!". And in some places I add this pod as `@import MyPod;`, and in some places of the app I used as `#include "MyPod.h";`. So, when I replace it and use everywhere `@import MyPod;` then it's solved.

**Comment by dnkoutso** [comment]
I believe `@import` is not the same as a quoted `""` import. So that makes sense.
