### ISSUE TITLE
[0.37.0] some compile parameters missed causes compile failed

### ISSUE THREAD

**Issue by lzyy** [CocoaPods/CocoaPods#3512]
#3491 after digging into it, i found the reason cause it compile failed is missing some parameters which exists in 0.36.4

```
-DOS_MACOSX -DLEVELDB_PLATFORM_POSIX -fno-objc-arc -w -Xanalyzer -analyzer-disable-checker -Xanalyzer deadcode
```

without these parameters, compile can't be passed.

**Comment by kylef** [comment]
This was fixed in 0.37.1.

> C++ source files with .cc, .cxx and .c++ extensions now have their compiler flags set correctly
