### ISSUE TITLE
[0.37.0] No execute permission for some pods containing binaries

### ISSUE THREAD

**Issue by allenhsu** [CocoaPods/CocoaPods#3513]
My case is when integrating Rollout.io, build failed due to `Permission Denied` error.
After switching back to 0.36.4, there's no error and project builds successfully.

I found that `pod install` with 0.37.0, binaries from Rollout.io in lib sub-directory has no execution permission, while with 0.36.4 they do have execution permission.

**Comment by dbarden** [comment]
Problem is that the files are being locked by [setting their permissions to 0444](https://github.com/CocoaPods/CocoaPods/blob/bc43a69e3f884a9d50e3f72d2805b613780c6dca/lib/cocoapods/installer/pod_source_installer.rb#L107)

@segiddins I don't have the background of this feature, but I believe that what we want to do is just to [avoid user to modify the Pods](https://github.com/cocoapods/cocoapods/issues/1154). I couldn't find a ruby library to simply remove the write permissions without feeling hacky.

Do you have anything against using system commands? `chmod a-w` should do the trick without removing the write permissions.

**Comment by dbarden** [comment]
*executable* permissions

**Comment by segiddins** [comment]
I believe there's an open PR to fix this

**Comment by dbarden** [comment]
yeap.

**Comment by dbarden** [comment]
And @mglidden did a way nicer work that what I would have done :+1:

**Comment by kylef** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/pull/3506
