### ISSUE TITLE
Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by hardikiOS** [CocoaPods/CocoaPods#3516]
Hi

I am getting error like below when I run app. I tried in both simulators and devices but both have same error. Can anyone help me to resolve this?

![screen shot 2015-05-06 at 1 36 05 pm](https://cloud.githubusercontent.com/assets/9332828/7489573/d7e1ebb2-f3f5-11e4-87bd-8ab630de0834.png)

Hardik

**Comment by orta** [comment]
@hardikiOS please read the [CONTRIBUTING](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). You're a programmer, you know what a good bug report looks like. Please improve this one. We need more context.

**Comment by hardikiOS** [comment]
Hi Orta,

Please see below detail context, also if possible look at screen shot I attached in earlier post. I am using iOS 7.1 cocoapods 0.35.0. Please do let me know if you need more information.

cp:cannot overwrite directory /Users/hardiknimavat/Desktop/ios-sdk-master/IRKit/IRKit.bundle/IRWifiSecuritySelectViewController.nib with non-directory /Users/hardiknimavat/Library/Developer/Xcode/DerivedData/IRKit-fdpddjgvkytaobchqsjszzkpvpdk/Build/Products/Debug-iphonesimulator/IRKit.bundle/IRWifiSecuritySelectViewController.nib

In few files I am getting above error.

Hardik.

**Comment by segiddins** [comment]
Are you sure this is the CocoaPods copy resources script that is failing? IIRC, we use `rsync` and not `cp`?

**Comment by kylef** [comment]
This error message isn't from a CocoaPods build phase but either a custom or one of Apple's and this doesn't seem to be anything to do with CocoaPods.

I'm going to close as there is nothing to action here. This is most likely a mis-configuration problem in your project and has very little to do with CocoaPods itself. If you can create an example project which can reproduce this issue proving it is a bug in CocoaPods then please re-open this issue.
