### ISSUE TITLE
Any bug in the version 0.37.0? 

### ISSUE THREAD

**Issue by kamoljan** [CocoaPods/CocoaPods#3518]
Hi guys

after update of `CocoaPods`
     
    $ pod --version
    0.37.0

I am getting the following error:

    [!] The 'Pods-ShoppingXXX' target has transitive dependencies that include static binaries: (/Users/user/w/ShoppingXXX/iOS/ShoppingXXX/Pods/Parse/libParse.a)

My `Podfile`:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!
    xcodeproj 'ShoppingXXX.xcodeproj'

    target 'ShoppingXXX' do
        pod 'Parse', '1.7.2'
        pod 'ParseFacebookUtils', '1.7.2'
        pod 'ParseCrashReporting', '1.7.2'
        pod 'Facebook-iOS-SDK', '3.23.2'
        pod 'Bolts', '1.1.5'
        pod 'RBStoryboardLink', '0.1.4'
        pod 'PubNub', '3.7.10.8'
        pod 'Alamofire', '~> 1.2'
    end

    target 'ShoppingXXXTests' do

    end

**Comment by neonichu** [comment]
This is by design, see #3267

**Comment by kamoljan** [comment]
@neonichu so, we just have to wait for Parse to fix their design issue?
