### ISSUE TITLE
Vendored Pods should have generated modulemaps

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#3519]
If a pod's `PodTarget`, integrated with `use_frameworks!`, is `should_build? == false`, because it only consists out headers and a vendored library or framework, then it should still have a generated modulemap in the integration, if not a custom modulemap was specified in the podspec. So it is ensured that it can be imported using module imports, which also means it can be imported directly from Swift without bridging header. As the `PodTarget` isn't integrated as native target in the `Pods.xcodeproj`, the modulemap must be injected over the aggregate target's xcconfig into the user project by adding the path to the build setting `SWIFT_INCLUDE_PATHS`.
This should be tested with an integration spec.

**Comment by neonichu** [comment]
This should IMHO, only apply to `vendored_libraries`, we shouldn't inject a module map into a `vendored_framework`

**Comment by segiddins** [comment]
We tried this. It failed horribly.
