### ISSUE TITLE
Is there a way to preserve folder reference in the resource_bundles

### ISSUE THREAD

**Issue by cipriancaba** [CocoaPods/CocoaPods#3521]
```
s.resource_bundles = {
    'MyBundle' => ['Assets/folder_reference_to_be_preserved/*']
}
```

I have a special need for a folder reference inside a resource bundle.. Right now, all of the files from within this folder will be included in `MyBundle` but they will be added on root level (within a group).. but I need them inside a folder reference(blue icon in Xcode)

**Comment by kylef** [comment]
I'm not entirely sure I follow, but is [`spec.preserve_paths`](https://guides.cocoapods.org/syntax/podspec.html#preserve_paths) what you are looking for?

**Comment by cipriancaba** [comment]
After running pod install the `resource_bundles` directive will create a new target called `Pods-MyBundle`

This target will contain all the files in the mentioned path `Assets/folder_reference_to_be_preserved/*` something like this:
https://www.dropbox.com/s/6057mxbjyug67nd/Screenshot%202015-05-07%2015.04.04.png?dl=0

However, i need to also preserve a subfolder that is found at `Assets/folder_reference_to_be_preserved/subfolder` like this:
https://www.dropbox.com/s/sn3z8w18hcd9yho/Screenshot%202015-05-07%2015.05.17.png?dl=0

If I would manually add the folder, I would check the `Create folder references` rather than `Create groups`

Does this make more sense?

**Comment by cipriancaba** [comment]
Maybe there is a way to add this in the post_install step? Maybe in combination with preserve_paths?

**Comment by cipriancaba** [comment]
I've managed to find a solution myself:

```
post_install do |installer|
    installer.project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == "TargetWhereToAddTheFolderOrFileReference"
          source_files = target.source_build_phase.files
          folderReference = installer.project.add_file_reference("/AbsolutePath/To/FileOrFolder", installer.project.pod_group("PodGroupWhereToAddTheFileOrFolder"), true)
          target.source_build_phase.add_file_reference(btsdata, true)
        end
      end
    end
end
```

**Comment by Anachid** [comment]
@cipriamcaba I tried your script, but it is not working for me. I am running cocoapods 0.39. I changed the "project" to "pod_projects" because I believe that was changed in version 0.39. 

Also, how we enable the puts method to work? I was trying to debug it, but nothing.

**Comment by Anachid** [comment]
Nevermind. I had another post_install in my podfile. I seems I can only have one.

**Comment by OceanHorn** [comment]
spec.resources = ['Assets/folder_reference_to_be_preserved']

**Comment by jonahn** [comment]
spec.resources = ['path/folder/**']
all the subfolder in folder will be blue icon

**Comment by Kalvin126** [comment]
To still use dynamic bundle target from Cocoapods, you can provide an array of paths. If a path to a folder is provided, then it will preserve that folder.

```ruby
  s.resource_bundles = {
    'MyBundle' => [
      'Assets/**/*.{storyboard,xib,xcassets,json,imageset,png,lproj}'
      'Assets/folder_reference_to_be_preserved/'
    ]
  }
```
