### ISSUE TITLE
Can you push to remote from within a project?

### ISSUE THREAD

**Issue by akaralar** [CocoaPods/CocoaPods#3525]
If a added a fork of a pod to a project by specifying :git parameter in the podfile, and made changes to the source of the pod, can I send those changes to remote in any way?

**Comment by segiddins** [comment]
Not currently, since the git download is cleaned. I'm sure we have an open issue that has this feature request.

**Comment by kylef** [comment]
We certainly have this capability planned, but it will be within a plugin with a command for `pod edit` allowing you to fork, update and submit a pull request for a Pod.

Doesn't appear to be any existing ticket but this has certainly been though of.

**Comment by orta** [comment]
I think this is probably a good place for a plugin, and probably not worth moving into cocoapods. Closing, but tagged as plugin idea.
