### ISSUE TITLE
Error during pod install

### ISSUE THREAD

**Issue by RyanCopley** [CocoaPods/CocoaPods#3526]
```
Analyzing dependencies
dyld: lazy symbol binding failed: Symbol not found: _rb_ary_new_from_values
  Referenced from: /Users/ryancopley/.rvm/gems/ruby-2.1.1/gems/psych-2.0.13/lib/psych.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_ary_new_from_values
  Referenced from: /Users/ryancopley/.rvm/gems/ruby-2.1.1/gems/psych-2.0.13/lib/psych.bundle
  Expected in: flat namespace
```

I ran `sudo gem install cocoapods` and tried again, still receiving this error.

**Comment by segiddins** [comment]
This looks to be an issue with your ruby's installation of `Psych`, which is the YAML parser that ship with Ruby.

**Comment by RyanCopley** [comment]
Rather than just closing my issue immediately... is there a known version of Ruby that works with Cocoapods? I'm using RVM and I'm on ruby-2.1.1, I don't really write much ruby, so is there a version I should be on?

**Comment by segiddins** [comment]
This isn't a ruby version issue, but rather an issue with your specific installation.

**Comment by RyanCopley** [comment]
What would help with this? Is it an issue with my installation of ruby, or the packages installed? Again, I'm not a ruby person. Would reinstalling Ruby mitigate this?

**Comment by RyanCopley** [comment]
If anyone else runs into this issue:

I upgraded to ruby 2.2.2 via rvm (`rvm install ruby-2.2.2; ruby use ruby-2.2.2`) and I can now run `pod install`

**Comment by pcarn** [comment]
For anyone else trying, the second command should be `rvm use ruby-2.2.2`
