### ISSUE TITLE
Google maps as a dependency. 

### ISSUE THREAD

**Issue by markst** [CocoaPods/CocoaPods#3528]
Appologies if this is an existing issue.

If I have `Google-Maps-iOS-SDK` defined as a dependency:
```
s.subspec 'Map' do |ss|
	ss.source_files = 'Defaults/Map/**/*{h,m}'
	ss.dependency     'Google-Maps-iOS-SDK', '~> 1.9.2'
end
```
I get:

![pasted_image_at_2015_05_07_12_40_pm](https://cloud.githubusercontent.com/assets/274318/7507709/4c292910-f4b7-11e4-947e-9244ee2a24ea.png)

**Comment by segiddins** [comment]
Please read [the contributing guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) for what constitutes a helpful issue -- what you've reported is really not enough to go on.

**Comment by markst** [comment]
you cunt.

**Comment by markst** [comment]
I've provided adequate details on my issue. did you even try reproducing before closing this issue?

**Comment by segiddins** [comment]
I'm sorry, but after the comment you originally posted (and then deleted), I'm going to have to lock this issue. We do not tolerate abusing language here.

**Comment by alloy** [comment]
@segiddins Such a gentleman response, perfect :clap: 

@markst There is no point in arguing the guidelines if you want people to spend their spare time helping you out. Do try again when you feel like you get it.
