### ISSUE TITLE
Post-install hook: Permission denied

### ISSUE THREAD

**Issue by mikaoj** [CocoaPods/CocoaPods#3529]
We have a post-install step which removes AFNetworkings UIImageView category:
```ruby
    pod.source_files.each do |pathname|
        if pathname.to_s.include? "/AFNetworking/UIImageView"
            File.open(pathname, 'w').write("/* REMOVED USE SDWEBIMAGE INSTEAD */")
        end
    end
```

As of 0.37 (0.37.0 and 0.37.1) this no longer works:
```
Permission denied - /PATH_TO_APP/Pods/AFNetworking/AFNetworking/UIImageView+AFNetworking.h
```

**Comment by orta** [comment]
This is a part of 0.37, which removes the ability to change your pods, I expect you will need to do a `chmod` to give yourself write address before replacing the text

**Comment by mikaoj** [comment]
Fixed it by doing a chmod

**Comment by segiddins** [comment]
We should run the post install hooks before locking?

**Comment by orta** [comment]
IMO, yes

**Comment by orta** [comment]
and plugins on the `:post_install` hook
