### ISSUE TITLE
Private Closed-Source Framework Does Not Install Until Second Pod Install

### ISSUE THREAD

**Issue by JosephEarl** [CocoaPods/CocoaPods#3538]
I am developing a closed source framework that I'd like to distribute via Cocoapods.
I've set up a private pod spec repository, with the binary artifacts hosted on an HTTP server.

However when I do a pod install, CocoaPods does not actually download any of the files. I've added a Pod distributed in the same fashion (Reveal SDK) and that works fine. 

Oddly enough running a second `pod install` command works.

I'm using CocoaPods 0.37.1.

The first pod install:

    [master] joseph on Josephs-Work-MacBook-Pro in ~/Downloads/TestCocoa 
    $ pod install --verbose
      Preparing
    [!] Unable to load a specification for the plugin `/Users/joseph/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-try-release-fix-0.1.2`

    Analyzing dependencies

    Updating spec repositories
    Updating spec repo `master`
      $ /usr/bin/git pull --ff-only
      Already up-to-date.

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-TestCocoa`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-TestCocoaTests`: (``)

    Fetching external sources
    -> Pre-downloading: `MyCompanyKit` from `ssh://git@mycompany.com:7999/ptk/ptk-ios-specs.git`, branch `test-http-hosting`
     > Git download
     > Git download
         $ /usr/bin/git clone ssh://git@mycompany.com:7999/ptk/ptk-ios-specs.git /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6654-3tb5x4
         --single-branch --depth 1 --branch test-http-hosting
         Cloning into '/var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6654-3tb5x4'...
         remote: warning: unable to access '/root/.config/git/attributes': Permission denied        
      > Copying MyCompanyKit from `/Users/joseph/Library/Caches/CocoaPods/Pods/External/MyCompanyKit/597732d13f15c038f3c90cc4c7697ec7` to `Pods/MyCompanyKit`

    Resolving dependencies of `Podfile`
    Starting resolution (2015-05-08 10:33:50 +0100)
    Creating possibility state for MyCompanyKit (from `ssh://git@mycompany.com:7999/ptk/ptk-ios-specs.git`, branch `test-http-hosting`) (1 remaining)
      Attempting to activate MyCompanyKit (0.3.0-beta1430929051)
      Activated MyCompanyKit at MyCompanyKit (0.3.0-beta1430929051)
      Requiring nested dependencies ()
      Creating possibility state for Reveal-iOS-SDK (14 remaining)
        Attempting to activate Reveal-iOS-SDK (1.5.1)
        Activated Reveal-iOS-SDK at Reveal-iOS-SDK (1.5.1)
        Requiring nested dependencies ()
    Finished resolution (2 steps) (Took 0.130214 seconds) (2015-05-08 10:33:50 +0100)
    Unactivated: 
    Activated: MyCompanyKit, Reveal-iOS-SDK

    Comparing resolved specification to the sandbox manifest
      A MyCompanyKit
      A Reveal-iOS-SDK

    Downloading dependencies

    -> Installing MyCompanyKit (0.3.0-beta1430929051)

    -> Installing Reveal-iOS-SDK (1.5.1)
      > Copying Reveal-iOS-SDK from `/Users/joseph/Library/Caches/CocoaPods/Pods/Release/Reveal-iOS-SDK/1.5.1-c9c55` to `Pods/Reveal-iOS-SDK`
      - Running pre install hooks

    Generating Pods project
      - Creating Pods project
      - Adding source files to Pods project
      - Adding frameworks to Pods project
      - Adding libraries to Pods project
      - Adding resources to Pods project
      - Linking headers
      - Installing targets
        - Installing target `Pods-TestCocoa` iOS 8.2
      - Running post install hooks
      - Writing Xcode project file to `Pods/Pods.xcodeproj`
      - Writing Lockfile in `Podfile.lock`
      - Writing Manifest in `Pods/Manifest.lock`

    Integrating client project

    Integrating target `Pods-TestCocoa` (`TestCocoa.xcodeproj` project)

If I inspect the directory for the Pod it is empty:

    [master] joseph on Josephs-Work-MacBook-Pro in ~/Downloads/TestCocoa 
    $ ls Pods/MyCompanyKit/
    [master] joseph on Josephs-Work-MacBook-Pro in ~/Downloads/TestCocoa 

Calling the install command a second time seems to resolve things:

    $ pod install --verbose
      Preparing
    [!] Unable to load a specification for the plugin `/Users/joseph/.rvm/gems/ruby-2.0.0-p247@global/gems/cocoapods-try-release-fix-0.1.2`

    Analyzing dependencies

    Updating spec repositories
    Updating spec repo `master`
      $ /usr/bin/git pull --ff-only
      Already up-to-date.

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-TestCocoa`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-TestCocoaTests`: (``)

    Finding Podfile changes
      - MyCompanyKit
      - Reveal-iOS-SDK

    Resolving dependencies of `Podfile`
    Starting resolution (2015-05-08 10:34:04 +0100)
    Creating possibility state for MyCompanyKit (from `ssh://git@mycompany.com:7999/ptk/ptk-ios-specs.git`, branch `test-http-hosting`) (1 remaining)
      Attempting to activate MyCompanyKit (0.3.0-beta1430929051)
      Activated MyCompanyKit at MyCompanyKit (0.3.0-beta1430929051)
      Requiring nested dependencies ()
      Creating possibility state for Reveal-iOS-SDK (1 remaining)
        Attempting to activate Reveal-iOS-SDK (1.5.1)
        Activated Reveal-iOS-SDK at Reveal-iOS-SDK (1.5.1)
        Requiring nested dependencies ()
    Finished resolution (2 steps) (Took 0.110052 seconds) (2015-05-08 10:34:05 +0100)
    Unactivated: 
    Activated: MyCompanyKit, Reveal-iOS-SDK

    Comparing resolved specification to the sandbox manifest
      M MyCompanyKit
      - Reveal-iOS-SDK

    Downloading dependencies

    -> Installing MyCompanyKit 0.3.0-beta1430929051 (was 0.3.0-beta1430929051)
     > Http download
       $ /usr/bin/curl -f -L -o /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/file.zip
       http://mycompany.com/MyCompany/sdk/ios/MyCompanyKit/SNAPSHOT/MyCompanyKit-20150506.125440-2.zip
       --create-dirs
         % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                        Dload  Upload   Total   Spent    Left  Speed
    100 1517k  100 1517k    0     0  4411k      0 --:--:-- --:--:-- --:--:-- 4425k
       $ /usr/bin/unzip /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/file.zip -d
       /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc
       Archive:  /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/file.zip
          creating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/
          creating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/MyCompanyKit.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKAcceptedPaymentMethod.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKAccessToken.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKAppLink.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKAudioTagDetector.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKBarcode.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKBarcodeTagDetectorView.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKBasket.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKBasketItem.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKBasketManager.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKBaskets.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKErrors.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKMerchant.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKMoney.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKProduct.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKProductAttribute.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKProductImage.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKProductOption.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKProductVariant.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKTag.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKTouch2BuyTagDetector.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKWorkflow.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKWorkflowManager.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Headers/PTKWorkflowType.h  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Info.plist  
          creating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Modules/
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/Modules/module.modulemap  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/MyCompanyKit  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/zbar-back.png  
         inflating: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/zbar-help.html  
        extracting: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/zbar-helpicons.png  
        extracting: /var/folders/gr/g2f9lxvs0cdbz1wpdzb5sdrh0000gn/T/d20150508-6725-tidcgc/MyCompanyKit.framework/zbar-samples.png  
      > Copying MyCompanyKit from `/Users/joseph/Library/Caches/CocoaPods/Pods/External/MyCompanyKit/1bb73431d969932919e5cf437489ca7e-2d00f` to `Pods/MyCompanyKit`

    -> Using Reveal-iOS-SDK (1.5.1)
      - Running pre install hooks

    Generating Pods project
      - Creating Pods project
      - Adding source files to Pods project
      - Adding frameworks to Pods project
      - Adding libraries to Pods project
      - Adding resources to Pods project
      - Linking headers
      - Installing targets
        - Installing target `Pods-TestCocoa` iOS 8.2
      - Running post install hooks
      - Writing Xcode project file to `Pods/Pods.xcodeproj`
      - Writing Lockfile in `Podfile.lock`
      - Writing Manifest in `Pods/Manifest.lock`

    Integrating client project

    Integrating target `Pods-TestCocoa` (`TestCocoa.xcodeproj` project)
    [master] joseph on Josephs-Work-MacBook-Pro in ~/Downloads/TestCocoa 

Things then look alright:

    $ ls Pods/MyCompanyKit/
    MyCompanyKit.framework

The Podspec for the framework:

    {
      "version": "0.3.0-beta1430929051",
      "source_files": "MyCompanyKit.framework/Headers/*.h",
      "preserve_paths": "MyCompanyKit.framework",
      "xcconfig": {
        "FRAMEWORK_SEARCH_PATHS": "\"$(PODS_ROOT)/MyCompanyKit/\""
      },
      "vendored_frameworks": "MyCompanyKit.framework",
      "requires_arc": true,
      "homepage": "http://www.MyCompany.com",
      "summary": "MyCompany Kit",
      "name": "MyCompanyKit",
      "source": {
        "http": "http://mycompany.com/MyCompany/sdk/ios/MyCompanyKit/SNAPSHOT/MyCompanyKit-20150506.125440-2.zip"
      },
      "platforms": {
        "ios": "7.0"
      },
      "authors": {
        "John Doe": ""
      },
      "license": {
        "type": "Commercial"
      }
    }

And the Podfile for the testing application project:

    # Uncomment this line to define a global platform for your project
    # platform :ios, '6.0'

    target 'TestCocoa' do
    pod 'MyCompanyKit', :git => 'ssh://git@mycompany.com:7999/ptk/ptk-ios-specs.git', :branch => 'test-http-hosting'
    pod 'Reveal-iOS-SDK'
    end

    target 'TestCocoaTests' do
    
    end

**Comment by neonichu** [comment]
I think this is an issue with specifying the `:git` option in the Podfile. Normally, this is supposed to overwrite the specification's source. Could you try leaving the extra options out?

**Comment by segiddins** [comment]
You shouldn't be specifying your Specs repo in the `git` option, that's what the top-level `sources` flag is for.

**Comment by JosephEarl** [comment]
Sorry for the confusion - it's not a private spec repo, the Git repo just has the podspec file at the root, with the actual zip hosted on an HTTP server. 

 With that -- I thought the :git option should work?

**Comment by segiddins** [comment]
Nope, you'll need to point directly to the zip in your Podfile. 

-Samuel E. Giddins

On May 10, 2015, at 1:14 PM, Joseph Earl <notifications@github.com> wrote:

Sorry for the confusion - it's not a private spec repo, the Git repo just has the podspec file at the root, with the actual zip hosted on an HTTP server.

With that -- I thought the :git option should work?

**Comment by JosephEarl** [comment]
Thanks, will try pointing to the zip directly with http. Does the pod spec need to be inside the Zip in that case? Or is it fine just having the zipped up framework?

**Comment by segiddins** [comment]
If you're pointing to it directly from the Podfile, it will need to contain a spec. Otherwise, my suggestion would be to use a specs repository. 

-Samuel E. Giddins

On May 10, 2015, at 1:31 PM, Joseph Earl <notifications@github.com> wrote:

Thanks, will try pointing to the zip directly with http. Does the pod spec need to be inside the Zip in that case? Or is it fine just having the zipped up framework?

**Comment by JosephEarl** [comment]
Thanks, much appreciated.
