### ISSUE TITLE
Cannot copy frameworks with `use_frameworks!` when `CONFIGURATION_BUILD_DIR` is set. 

### ISSUE THREAD

**Issue by codecaffeine** [CocoaPods/CocoaPods#3541]
:rainbow:

`pod --version 0.37.1`
[Example Project](https://github.com/codecaffeine/CocoaPodsIssue)

When I build my app, I have a custom `CONFIGURATION_BUILD_DIR` set. I attempted to switch over to framework using the `use_frameworks!` flag in my Podfile, but I get an error attempting to copy the frameworks when I build:
`xcodebuild -scheme "Foobar" -workspace Foobar.xcworkspace clean build CONFIGURATION_BUILD_DIR=~/Desktop/CocoaPodsIssue/build`

I get the following error:
```
PhaseScriptExecution Embed\ Pods\ Frameworks /Users/thomasm1/Library/Developer/Xcode/DerivedData/Foobar-fivdsqseavaweeherliqklhcmcyk/Build/Intermediates/Foobar.build/Debug-iphoneos/Foobar.build/Script-8BB2184733BEAB91622B6492.sh
    cd /Users/thomasm1/Desktop/CocoaPodsIssue
    /bin/sh -c /Users/thomasm1/Library/Developer/Xcode/DerivedData/Foobar-fivdsqseavaweeherliqklhcmcyk/Build/Intermediates/Foobar.build/Debug-iphoneos/Foobar.build/Script-8BB2184733BEAB91622B6492.sh
mkdir -p /Users/thomasm1/Desktop/CocoaPodsIssue/build/Foobar.app/Frameworks
rsync -av --filter - CVS/ --filter - .svn/ --filter - .git/ --filter - .hg/ --filter - Headers/ --filter - PrivateHeaders/ --filter - Modules/ /Users/thomasm1/Desktop/CocoaPodsIssue/build/Pods-Foobar/AFNetworking.framework /Users/thomasm1/Desktop/CocoaPodsIssue/build/Foobar.app/Frameworks
building file list ... rsync: link_stat "/Users/thomasm1/Desktop/CocoaPodsIssue/build/Pods-Foobar/AFNetworking.framework" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

And my build folder looks like this:
![screen shot 2015-05-08 at 2 24 43 pm](https://cloud.githubusercontent.com/assets/71474/7543112/0f678ba0-f590-11e4-9dfb-727179411904.png)

but when I build without the `CONFIGURATION_BUILD_DIR` set:
`xcodebuild -scheme "Foobar" -workspace Foobar.xcworkspace clean build`

The build succeeds and my products directory looks like this (notice the frameworks are embedded in a folder):
![screen shot 2015-05-08 at 2 18 55 pm](https://cloud.githubusercontent.com/assets/71474/7543139/3eaee368-f590-11e4-9fb7-91f4dfefc246.png)

**Comment by neonichu** [comment]
Thanks for your detailed issue. This is one of the known problems related to the scoping of frameworks we apply per user target. It is tracked by #3095.
