### ISSUE TITLE
dyld: Library not loaded. [reopen] [0.37.1]

### ISSUE THREAD

**Issue by minuscorp** [CocoaPods/CocoaPods#3543]
Hi there.

I'm really sorry that I've got to open this issue again, referring to #3505 

Yesterday, with the project I provided in the link, it was running well as you checked after a format and a clean install of the system. Afterwards, I started to install the same pods in the main project I'm working on and, sadly, I recieved the same issue again.

I'm really concerned about this, and thinking It was a bad joke, I tried in other Mac. Same issue running in a real device (with the main project)

This time, I'd like to share with you the main project as today is giving the same error in two completely different Mac computers.

This is the link: https://www.dropbox.com/sh/b404pdnvm20mebe/AAD894hKFHgh8JTUeoY7GDFNa?oref=e

Please, tell me that this time at least you get the same error as me and I'm not spending my time in trying to catch a ghost.

Thank you very much.

**Comment by neonichu** [comment]
I just took a quick look, but the issue you have here is that the "Copy Pods frameworks" build phase was missing, did you by any chance add the dependency on "Pods.framework" manually?

Adding

```ruby
link_with 'HolaSwift'
```

to your Podfile will integrate your project properly.
