### ISSUE TITLE
use_frameworks! with non Swift libraries

### ISSUE THREAD

**Issue by uncarlo** [CocoaPods/CocoaPods#3547]
Hello,
I'm trying to use AFNetworking and SwiftyJSON together, but for SwiftyJSON I need to add the "use_frameworks!" directive; in which case, my AFNetworking bridging header stops working, and my project doesn't compile. Any idea on how to fix this issue?

http://screencast.com/t/HuyZEXSfkBYD

**Comment by neonichu** [comment]
The user header import syntax isn't available for frameworks. Either do:

```objc
#import <AFNetworking/AFNetworking.h>
```

or a proper module import:

```objc
@import AFNetworking;
```

The bridging header is also unnecessary with frameworks, you can directly import them into Swift:

```swift
import AFNetworking
```
