### ISSUE TITLE
pod trunk push no longer handles source keyword in subspecs

### ISSUE THREAD

**Issue by drewmccormack** [CocoaPods/CocoaPods#3552]
Perhaps this was never officially supported, but I have been using `source` in a subspec to include a framework dependency from my own github repo, like this

    s.subspec 'Dropbox' do |ss|
        ss.dependency 'Ensembles/Core'
        ss.ios.dependency 'Dropbox-iOS-SDK'
        ss.osx.dependency 'Dropbox-OSX-SDK'
        ss.source = {:git => 'git://github.com/drewmccormack/dropbox-sdk-ios.git'}
        ss.source_files = 'Framework/Extensions/CDEDropboxCloudFileSystem.{h,m}'
    end

This stopped working recently. I now get this error.

    -> "{\"error\":\"The Pod Specification did not pass validation.\",\"data\":{\"errors\":[\"Can't set `source` 
    attribute for subspecs (in `Ensembles/Dropbox`).\"]}}"
    read 148 bytes
    Conn keep-alive
    [!] The Pod Specification did not pass validation.

What I want to do seems like it should be common. I have a a subspec that depends on a framework, and I have to host my own version of that framework.

Is this a bug in `pod trunk`, or can someone point to how this should be done?

**Comment by orta** [comment]
To my knowledge CocoaPods has never supported `source` in a subspec, the declaration of a source should come from the user's podfile, so a user should put:

```
pod "Dropbox-OSX-SDK", :git => "git://github.com/drewmccormack/dropbox-sdk-ios.git"
pod "Ensembles", :subspecs => ["Thing", "Dropbox"]
```

**Comment by drewmccormack** [comment]
I have been using source like that since the beginning, so it was definitely passing validation. Pretty sure it worked too, because people were definitely using the subspec.

Anyway, I guess I can see why the user should stipulate where the Dropbox repo is, but it does post a problem, namely that my framework requires a particular Dropbox repo. Is there a way around that, or do I just have to instruct my customers to add the :git line to their podfile?

**Comment by segiddins** [comment]
Definitely agree that it was a bug if that ever worked.
