### ISSUE TITLE
Characters are not escaped when integrating with Swift pods

### ISSUE THREAD

**Issue by alex-taffe** [CocoaPods/CocoaPods#3555]
When using a Swift pod with use_frameworks, the app fails to compile because of this error:

```
/Users/Alex/Library/Developer/Xcode/DerivedData/Man's_Best_Friend-gzjemoifisjyhfecndtoqmrqqtsi/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-AlecrimCoreData.build/unextended-module-overlay.yaml:6:66: error: unknown key
    'name': '/Users/Alex/Library/Developer/Xcode/DerivedData/Man's_Best_Friend-gzjemoifisjyhfecndtoqmrqqtsi/Build/Products/Debug-iphonesimulator/Pods/AlecrimCoreData.framework/Modules'
                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<unknown>:0: error: invalid virtual filesystem overlay file '/Users/Alex/Library/Developer/Xcode/DerivedData/Man's_Best_Friend-gzjemoifisjyhfecndtoqmrqqtsi/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-AlecrimCoreData.build/unextended-module-overlay.yaml'
<unknown>:0: error: clang importer creation failed
```

The arrow is pointing to the apostrophe in the path. I think the software is just failing to escape it somewhere.

**Comment by segiddins** [comment]
I think this might just be a case where Xcode is broken when you have non-alphanumeric characters in your target name :/

**Comment by alex-taffe** [comment]
Manual integration does work though?

**Comment by neonichu** [comment]
Hm, the "virtual filesystem overlay file" is created internally by the Xcode build process, we can't directly influence it at all. 

Maybe the difference is that your build with manual integration ends up in a "build" folder instead of DerivedData because you don't use a workspace?

**Comment by neonichu** [comment]
Managed to create the same issue by creating a workspace manually, so it is an Xcode bug. Will file a radar for it :satellite:

**Comment by neonichu** [comment]
See <http://www.openradar.me/20933735>

**Comment by alex-taffe** [comment]
I was using a workspace, I'll file a bug report with Apple too

**Comment by neonichu** [comment]
Yah, it's not entirely clear to me under what conditions the "virtual filesystem overlay file" is created during the build process, it seems like not every framework needs it.

**Comment by alex-taffe** [comment]
It looks to me like it's only Swift cocoa pods that do. Even when mixing Swift and Objective C, the Objective C pods are fine. Swift ones are the trouble.

**Comment by alex-taffe** [comment]
Bug report 20942263 filed with Apple
