### ISSUE TITLE
Read Only File Permissions

### ISSUE THREAD

**Issue by hishamabri** [CocoaPods/CocoaPods#3557]
With the new Cocoapods update, all files are written under read-only permissions.
This is causing an issue for users who use .sqlite database files that were already created but only moved/copied to the device.
Because the permissions are read-only, when the database is open, it is open as read-only as well. This obviously breaks if we try to write any data to that database.

I understand that this was only changed recently. But can we have any options to all read-write files?
Meanwhile, I will downgrade to 0.36.1 as it was the last version that worked without read-only permissions

**Comment by segiddins** [comment]
@mglidden ?

**Comment by mglidden** [comment]
Hey @hishamabri – do you have an example of a pod that does this?

I'll put together a PR for this bug

**Comment by hishamabri** [comment]
The pod that is causing this issue is unfortunately internal.
To illustrate this is the scenario that we have:

1. We have a .sqlite database file that contains some data.
2. We use this .sqlite file to be deployed to the device. It will be copied straight out from the Payload to the app documents for writing.
3. Then we use this database to update records from the user.

**Comment by segiddins** [comment]
Should probably just not `chmod` the permissions on resources, @mglidden ...

**Comment by segiddins** [comment]
This has been fixed.
