### ISSUE TITLE
Can't find frameworks when using custom build location

### ISSUE THREAD

**Issue by exsortis** [CocoaPods/CocoaPods#3560]
I have an app written in Swift that uses CocoaPods, building its dependencies as frameworks. The app builds fine when I build on my local development machine using the default build location (the generated frameworks are placed in the build location in a subdirectory called "Pods").

I also have a Jenkins CI server that builds the same application. However, on the Jenkins server, the Xcode plugin is configured to override the build location (CONFIGURATION_BUILD_DIR=${WORKSPACE}/build) so that the built artifacts are placed inside the project workspace. This is done so that I'm able to have Jenkins archive the build artifacts, and so that I can run a Crashlytics script to upload the binary for distribution to my beta testers. When built with this override, the build fails, because the generated frameworks from CocoaPods are placed in the root of the build location instead of in the "Pods" subdirectory, and the "Pods-frameworks.sh" script is expecting to find them in the "Pods" subdirectory.

If I don't override the build directory, the build succeeds as expected, but them I'm unable to use Jenkins' archiving feature, or the Crashlytics upload.

**Comment by neonichu** [comment]
This is one of the known problems related to the scoping of frameworks we apply per user target. It is tracked by #3095.
