### ISSUE TITLE
Current OTHER_LIBTOOLFLAGS solution breaks IB_DESIGNABLE

### ISSUE THREAD

**Issue by scott-ce** [CocoaPods/CocoaPods#3564]
Previously IB_DESIGNABLE required frameworks and didn't support static libs (see #2792 ). Fortunately, that's no longer the case.

However, if an app that wants to use IB_DESIGNABLE includes a static lib that uses Cocoapods, the current behavior for OTHER_LIBTOOLSFLAGS causes the IB Designables build to fail, because IB Designable doesn't support the -ObjC flag as described by @dunahebel in issue #2666.

FYI, we're using the following post_install hook as a workaround:

```ruby
post_install do |installer_representation|
  # This iterates through the top-level Pod generated for each  of our static library targets
  # and if it finds `OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)` in the corresponding
  # xcconfig file, it replaces `$(OTHER_LDFLAGS)` with the contents of OTHER_LDFLAGS
  # after stripping out `-ObjC`
  installer_representation.installer.aggregate_targets.each do |target|
    if target.user_targets.any? { |t| t.symbol_type == :static_library } then
      target.xcconfigs.each do |variant, xcconfig|
        path = target.client_root + target.xcconfig_relative_path(variant)
        if xcconfig.attributes['OTHER_LIBTOOLFLAGS'] == '$(OTHER_LDFLAGS)' then
          xcconfig.attributes['OTHER_LIBTOOLFLAGS'] = xcconfig.to_hash['OTHER_LDFLAGS'].gsub('-ObjC', '')
          xcconfig.save_as( path )
        end
      end
    end
  end

end
```

**Comment by segiddins** [comment]
This seems to more more an IB bug than a CocoaPods bug?

**Comment by scott-ce** [comment]
> This seems to more more an IB bug than a CocoaPods bug?

Or an incomplete feature. Previously Xcode didn't support static libs. Now they do but their tool doesn't recognize -ObjC. I haven't tried looking under the hood to see if there's a good reason.

I don't know the implications of updating OTHER_LIBTOOLFLAGS on other projects, and we do have a workaround for ours. So I won't protest if this is closed as low priority.

However, if CocoaPods never accounted for Apple's Xcode/IB bugs, would anything ever work? ;-)

**Comment by segiddins** [comment]
This should be fixed by CocoaPods no longer specifying `OTHER_LIBTOOLFLAGS`
