### ISSUE TITLE
when use comment 'pod spec lint' to check my repository has failed validation.

### ISSUE THREAD

**Issue by TechD-Robin** [CocoaPods/CocoaPods#3574]
when i use comment 'pod spec lint' to check my repository has failed validation,
then pod show the fail code like this:

-> TDDownloadManager (0.0.5)
    - WARN  | [iOS]  TDDownloadManager/TDDownloadManager/TDDownloadManager.m:848:16: warning: initialization of pointer of type 'TDDownloadManager *' to null from a constant boolean expression [-Wbool-conversion]

I find the bug and fix it, and recommit and push to my private's git server.
when i reuse the comment 'pod spec lint', the pod always show  these error above.

That must change podspec version to 0.0.6 and add a new tag to my private's git server.
I just have some question why the older version cannot reuse, and where this version temporary ?

Thank you.
Sorry for my question and my English is pretty basic.

----
$ pod --version
0.37.1

**Comment by orta** [comment]
When you have warnings that you think are acceptable to release, you can add `--allow-warnings` to [your command](https://guides.cocoapods.org/terminal/commands.html#pod_spec_lint) to have it pass validations.
