### ISSUE TITLE
spec.prepare_command not working 0.37.1

### ISSUE THREAD

**Issue by wsvn53** [CocoaPods/CocoaPods#3575]
Upgrade cocoapods to 0.37.1, it seems `spec.prepare_command ` not work correct.

**Comment by orta** [comment]
This isn't enough information to do anything with @wsvn53 - you're a programmer, give us a bug report you'd like to read.

**Comment by wsvn53** [comment]
Ha, so sorry. I found that my scripts defined in `spec.prepare_command` was executed, but with a different environment variables, the `spec.prepare_command` working path seems changed to `/Users/Ethan/Library/Caches/CocoaPods/Pods/Release/..`. 

 So, this issue should change to **How can I get `pod install/update` working path during `spec.prepare_command` execution?**

**Comment by segiddins** [comment]
You currently can't. Why is that something you need?

**Comment by wsvn53** [comment]
We need to change some settings for target projects, in my case, when `pod install` my pod, it will add a build phase to project targets, in order to execute some scripts when building project target.

**Comment by segiddins** [comment]
That's not really something that we want to support from the `prepare_command` -- that's more something that should happen via a plugin.

**Comment by Fl0p** [comment]
:+1: 
Same for me
prepare_command does nothing

- I have a local repo with specs in ruby format
- I use one pod from local specs repo with prepare command like this

```
  spec.prepare_command = <<-CMD
 touch spec.txt
 pwd > ./spec.pwd.txt
 ls > ./spec.ls.txt
 CMD
```

nothing

**Comment by Fl0p** [comment]
prepare_command not working for subspecs

**Comment by Koshub** [comment]
The same:
I create a private pod to make an enterprise apps and have to automate a bit pod install process to add target build phase scripts. But with prepare_command I can't get path to user project.

**Comment by fragno** [comment]
The same：
really need this feature
