### ISSUE TITLE
pod install ignores Podfile

### ISSUE THREAD

**Issue by OlegAnghelov** [CocoaPods/CocoaPods#3576]
Hey guys!

```
pod --version
0.36.3
```

Thank again for doing great job :)
But we sometimes encounter a weird behaviour.

As I understand, `pod install` instales the versions of the pods that are in `Podfile`.
`pod update`, on the other hand, install the latest versions.

If somebody does a mistake, and mistakenly instead of `pod install` does `pod update`, he gets latest versions, and the `Podfile.lock` gets overwritten with latest version.
As I understand in this case, putting `pod install` should revert the changes, install the versions from the `Podfile`, and bring `Podfile.lock` to a state with older versions. 

Sadly, it's not what actually happens.
More than that:
even after deleting the Pods directory, the workspace, and the lock file, doing the `pod install` still ignores the Podfile settings and install the latest version.
More than that, cloning same repo from github into another folder, and doing `pod install` there - does everything fine. 

This is how we tell pod to use specific versions:
`pod 'AFNetworking', '~> 2.5.2'`
 
So doing pod install, it was trying to install the 2.5.4 version.

Could somebody enlighten me what is the actual issue?

**Comment by neonichu** [comment]
This works as intended. If there is no lock file, `pod install` will install the newest versions satisfying the constraints of the Podfile. If the lock file exists, `pod install` will install that exact version and `pod update` will install the newest version.

**Comment by OlegAnghelov** [comment]
Does it mean that I incorrectly set the constraints?
Why does it install 2.5.4 on `pod install` when `pod 'AFNetworking', '~> 2.5.2'` is specified?

**Comment by neonichu** [comment]
See <https://guides.cocoapods.org/syntax/podfile.html#pod> for what the operators mean. Pinning to an exact version would be `pod 'AFNetworking', '2.5.2'`.
