### ISSUE TITLE
Add the ability for specs to require plugins?

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#3578]
Might this be something we want to do?

\c @kylef @orta

**Comment by orta** [comment]
I can see it as a might, but can we think of any real concrete examples?

**Comment by segiddins** [comment]
Whatever it is https://github.com/CocoaPods/CocoaPods/issues/3575 is doing, also like a crash reporter pod that needs dsyms to be uploaded?

**Comment by segiddins** [comment]
Closing because we agreed: no.

**Comment by msoliman** [comment]
@orta @segiddins Is this something that you plan to do later?
We've been using this at Instabug for uploading dsyms as you mentioned and it's been very convenient for our users. Any other workarounds?

**Comment by segiddins** [comment]
@msoliman nah, this is something we decided against doing.
