### ISSUE TITLE
Error: ld: file is universal (2 slices) but does not contain a(n) armv7s slice

### ISSUE THREAD

**Issue by winterzou** [CocoaPods/CocoaPods#3579]
Hello,
When I add a third-party library archive is always fail,It's also linker command failed with exit code 1 (use -v to see invocation).After I upgraded to xcode6.3.
The podfile is 

```ruby
platform :ios,'7.0'
pod "MJRefresh"
pod "Masonry"
pod 'SDWebImage'
pod 'AMapSearch'
pod 'AFNetworking'
pod 'UMengAnalytics-NO-IDFA'
pod 'AMapNavi'
pod 'pop'
pod 'MJExtension'
```

the error 
ld: file is universal (2 slices) but does not contain a(n) armv7s slice: /Users/apple/Library/Developer/Xcode/DerivedData/DuCarClient-ftmhkxhdylrbudbczrznfgratpcs/Build/Products/Debug-iphoneos/libPods-MJExtension.a file '/Users/apple/Library/Developer/Xcode/DerivedData/DuCarClient-ftmhkxhdylrbudbczrznfgratpcs/Build/Products/Debug-iphoneos/libPods-MJExtension.a' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by segiddins** [comment]
That's odd, given that I believe apple no longer require armv7s slices.

**Comment by winterzou** [comment]
We need to support the old user

**Comment by segiddins** [comment]
armv7s CPUs can run armv7 code

**Comment by winterzou** [comment]
So ,now ,we project can abandon armv7s support, apple will not rejected?

**Comment by winterzou** [comment]
I think I found the reason,This is cocoaPods warning,how can I do it

The `DuCarClient [Release]` target overrides the `ARCHS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by neonichu** [comment]
You can remove the build setting by highlighting it in Xcode and pressing "Delete".

In any case, this is not actually a CocoaPods issue, so I'll close it.

**Comment by winterzou** [comment]
It may be CocoaPods compatible with xcode6.3 problem, It's become bad after Upgrade to the Xcode 6.3

**Comment by neonichu** [comment]
AFAIK, Xcode 6 never build armv7s by default, see <http://www.cocoanetics.com/2014/10/xcode-6-drops-armv7s/>
