### ISSUE TITLE
Message libpods-mobileAppTracker.a not found on Release by upgrade  35.0 -> 37.1

### ISSUE THREAD

**Issue by appmagnetics** [CocoaPods/CocoaPods#3580]
Using pod 'MobileAppTracker', '3.9.1' 
This pod library is missing in Archive (Release) build - the project does not compile under 37.1

**Comment by neonichu** [comment]
Their Pod looks broken, it should use [`vendored_libraries`](https://guides.cocoapods.org/syntax/podspec.html#vendored_libraries): https://github.com/MobileAppTracking/cocoapod/blob/master/MobileAppTracker.podspec.json#L24

It was probably a coincidence that it ever worked, please file an upstream issue with them.

**Comment by appmagnetics** [comment]
According to this thread https://github.com/MobileAppTracking/cocoapod/issues/7  MAT Team has adjusted their pod configuration according your advice. But with new configuration I get  "library not found for -lPods-MobileAppTracker"  WITH PODS VERSION > 0.35.2.  MAT team could not find the root cause so far. Would you advice on where should we look to check why it's not working?
