### ISSUE TITLE
[Cocoapods 0.37.1] 'pod update' accidentally deletes some relevant files from 'Target Support Files' directory.

### ISSUE THREAD

**Issue by Maxim-38RUS-Zabelin** [CocoaPods/CocoaPods#3582]
After updating to **Cocoapods 0.37.1**, I've become unable to update any of the pods I use in a project: for no reason *'pod update'* deletes some relevant files from *'Target Support Files'* directory (even if I simply execute *'pod update'*, applying no changes to the *Podfile*).

Here is the list of pods I use:

*pod 'AFNetworking', '~> 2.5'
pod 'Alamofire', '~> 1.2'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'HMSegmentedControl', '~> 1.5'
pod 'Observable-Swift', '~> 0.4'
pod 'SwiftyJSON', '~> 2.2'
pod 'ViewUtils', '~> 1.1'*

Here is the log I see in the terminal after *'pod update'* is executed:

	modified:   Podfile.lock
	modified:   Pods/Manifest.lock
	modified:   Pods/Pods.xcodeproj/project.pbxproj
	deleted:    Pods/Target Support Files/Pods-CrashlyticsFramework/Info.plist
	deleted:    Pods/Target Support Files/Pods-CrashlyticsFramework/Pods-CrashlyticsFramework-Private.xcconfig
	deleted:    Pods/Target Support Files/Pods-CrashlyticsFramework/Pods-CrashlyticsFramework-dummy.m
	deleted:    Pods/Target Support Files/Pods-CrashlyticsFramework/Pods-CrashlyticsFramework-prefix.pch
	deleted:    Pods/Target Support Files/Pods-CrashlyticsFramework/Pods-CrashlyticsFramework-umbrella.h
	deleted:    Pods/Target Support Files/Pods-CrashlyticsFramework/Pods-CrashlyticsFramework.modulemap
	deleted:    Pods/Target Support Files/Pods-CrashlyticsFramework/Pods-CrashlyticsFramework.xcconfig
	modified:   Pods/Target Support Files/Pods/Pods-frameworks.sh
	modified:   Pods/Target Support Files/Pods/Pods-resources.sh
	modified:   Pods/Target Support Files/Pods/Pods.debug.xcconfig
	modified:   Pods/Target Support Files/Pods/Pods.release.xcconfig

**Comment by neonichu** [comment]
Does this cause any actual build failures?

**Comment by Maxim-38RUS-Zabelin** [comment]
Yes, it does.

**Comment by neonichu** [comment]
Would you be so kind to share them with us? It is rather difficult to debug a problem when given partial information.

**Comment by Maxim-38RUS-Zabelin** [comment]
Unfortunately, I can't share the source code of the project itself, but I can try to set up a test environment for you. Would it be OK?

**Comment by neonichu** [comment]
Sure, it would be enough to first simply share the build errors - maybe you can anonymise them enough so you could share?

**Comment by Maxim-38RUS-Zabelin** [comment]
Ok, I'll see what I can do.

**Comment by Maxim-38RUS-Zabelin** [comment]
Please navigate to [this page](http://textuploader.com/fe0z) to see the error log. Currently, I'm not able to set up a test environment for you, but I'll do it ASAP.

**Comment by neonichu** [comment]
Hm, seems like your product actually doesn't link to Foundation - could you add that to "Linked Frameworks and Libraries" of your own target?

**Comment by Maxim-38RUS-Zabelin** [comment]
I don't really think the issue is up to the Foundation framework. Please have a look a this [diff](http://joxi.ru/E2pvavYSykqyrY). The updated xcconfig is on the left. To me it is strange that *FRAMEWORK_SEARCH_PATHS* no longer comprises a path to the Crashlytics framework after update.

**Comment by Maxim-38RUS-Zabelin** [comment]
Please take my apologizes for the delay; here is a [sample project](https://github.com/Maxim-38RUS-Zabelin/compound-workspaces-along-with-cocoapods/tree/another_solution) that demonstrates the described issue.

**Comment by Maxim-38RUS-Zabelin** [comment]
Turning back to the Foundation framework, I don't think this is a problem. Please check out [this commit](https://github.com/Maxim-38RUS-Zabelin/compound-workspaces-along-with-cocoapods/commit/058825239cdf6bf2661517760b835558ccfaa440); the project should compile faultlessly.

**Comment by neonichu** [comment]
That project doesn't demonstrate the problem you described originally and does contain significant manual changes to the default integration done by CP, e.g. you are doing your own framework embedding.

**Comment by Maxim-38RUS-Zabelin** [comment]
What kind of changes do you mean? I didn't do any significant changes - the only change I did was manual linking with the configs the Pods generated for me.

**Comment by neonichu** [comment]
You're not using the default "Copy Frameworks" shell scripts, which makes the project not build for me, because some of the other dependencies cannot be found. If I resolve those problems, the project builds fine for me, I see no issues regarding the Crashlytics framework. Same result when I integrate the "CrashlyticsFramework" pod into a completely fresh project.

**Comment by Maxim-38RUS-Zabelin** [comment]
Ok, I see. I'll take your advice. Thank you for your time!

p.s. To tell the truth, the only thing that still bothers me is why there was no such an issue under Cocoapods 0.36.3.

**Comment by neonichu** [comment]
We changed how vendored frameworks are integrated. Before they would be directly linked against the application if `source_files` was empty, now they'll also be if `source_files` only contains headers. But, this should not lead to build failures, only to a bit simpler integration, that's why some no longer necessary files were missing from "Target Support Files".

**Comment by Maxim-38RUS-Zabelin** [comment]
Thank you for the explanation!

**Comment by logananderson** [comment]
I'm having the same issues, sorry what was needed in order to resolve this?
