### ISSUE TITLE
transitive dependencies again

### ISSUE THREAD

**Issue by mobdim** [CocoaPods/CocoaPods#3583]
Hello.
When installing pods I get: [!] The 'Pods' target has transitive dependencies that include static binaries: (.../Pods/OpenSSL-Universal/lib-ios/libcrypto.a and .../Pods/OpenSSL-Universal/lib-ios/libssl.a

I looked up similar issues, but did not understand whether there is now a solution to this problem?

**Comment by neonichu** [comment]
Nope, the only solution lies in the Pod in question switching to dynamic libraries or frameworks.

**Comment by levigroker** [comment]
@mobdim Did you get this resolved? I'm seeing the same error against OpenSSL-Universal. I filed an issue there: https://github.com/krzyzanowskim/OpenSSL/issues/9

**Comment by levigroker** [comment]
@neonichu Can you please point to documentation, or further illustrate how a podspec would need to be altered to prevent this error?

**Comment by sirnacnud** [comment]
You can try using OpenSSL-Framework instead of OpenSSL-Universal to have OpenSSL included as a framework, rather than a static library,

**Comment by levigroker** [comment]
Thanks for the thought, though I don’t think that will work in my situation as I need OpenSSL to be available to iOS as well as OS X.

Levi
On June 8, 2015 at 14:46:42, Duncan Cunningham (notifications@github.com) wrote:

You can try using OpenSSL-Framework instead of OpenSSL-Universal to have OpenSSL included as a framework, rather than a static library,

**Comment by neonichu** [comment]
@levigroker basically shared libraries/frameworks have to be used instead of static ones.

**Comment by gabriel** [comment]
I can't publish updates to my pods that use `OpenSSL-Static` or OpenSSL-Universal` because of this issue. Not sure what to do :(


```
    GHBigNum (0.1.8) - Analyzing on iOS 7.0 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `GHBigNum` from `/Users/gabe/Projects/GHBigNum/GHBigNum.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A GHBigNum
  A OpenSSL-Static

Downloading dependencies

-> Installing GHBigNum (0.1.8)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/gabriel/GHBigNum.git /var/folders/84/7q50__3j4yscqtt4qmrv8rtr0000gn/T/d20150812-88753-1l95c5w --single-branch --depth 1 --branch 0.1.8
     Cloning into '/var/folders/84/7q50__3j4yscqtt4qmrv8rtr0000gn/T/d20150812-88753-1l95c5w'...
     Note: checking out 'a12e4ae4ae44769e90fef476c9efdc37065c7d4c'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b new_branch_name
     
  > Copying GHBigNum from `/Users/gabe/Library/Caches/CocoaPods/Pods/External/GHBigNum/3a4230c74085cff5307f58831d7969b8-911f4` to
  `../../../../private/var/folders/84/7q50__3j4yscqtt4qmrv8rtr0000gn/T/CocoaPods/Lint/Pods/GHBigNum`

-> Installing OpenSSL-Static (1.0.2.c1)
  > Copying OpenSSL-Static from `/Users/gabe/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Static/1.0.2.c1-bd17e` to
  `../../../../private/var/folders/84/7q50__3j4yscqtt4qmrv8rtr0000gn/T/CocoaPods/Lint/Pods/OpenSSL-Static`
  - Running pre install hooks
 -> GHBigNum (0.1.8)
    - ERROR | [iOS] Encountered an unknown error (The 'Pods' target has transitive dependencies that include static binaries: (/private/var/folders/84/7q50__3j4yscqtt4qmrv8rtr0000gn/T/CocoaPods/Lint/Pods/OpenSSL-Static/lib-ios/libcrypto.a and /private/var/folders/84/7q50__3j4yscqtt4qmrv8rtr0000gn/T/CocoaPods/Lint/Pods/OpenSSL-Static/lib-ios/libssl.a)) during validation.

[!] The podspec does not validate.
```

**Comment by segiddins** [comment]
`pod trunk push --use-libraries`, @gabriel ?

**Comment by gabriel** [comment]
yup that worked thanks!

On Wed, Aug 12, 2015 at 2:54 PM, Samuel E. Giddins <notifications@github.com

**Comment by ceoacai** [comment]
I do not know the reason,but it's worked for me.
by use pod install --verbose found that

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:422:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'

so I open the installer.rb go to line 422 then add a "!" to the ruby file, like this
unless !static_libs.empty?
raise Informative, "The '#{aggregate_target.label}' target has " \
"transitive dependencies that include static binaries: (#{static_libs.to_sentence})"

it's works~

**Comment by maojj** [comment]
@segiddins 
```
pod trunk push --use-libraries
```
works, thx.

**Comment by phanisai4u** [comment]
**add below line of code in your pod file to ignore transitive dependencies**
           ```
pre_install` do |installer|
             'def installer.verify_no_static_framework_transitive_dependencies; end
       end`
```
