### ISSUE TITLE
Overriding dependency resolution in pod spec lint

### ISSUE THREAD

**Issue by PatrickNLT** [CocoaPods/CocoaPods#3585]
I understand from #3276 that specifying a repository or commit in the dependency section won't be supported in the future.

However, that means that `pod spec lint` may return an error if the library is incompatible with the 'official' version of a dependency. Would it be possible to add an option to the lint command to support manual dependency resolution? Something like `pod spec lint --dependencies Dependency1:http://myrepository1.git,Dependency2:http://myrepository2.git` would be terrific.

NB: I know there is a --sources option, so maybe we could list the fork of our dependency here, but it requires to create a separate Specs repository, which is really not what we want here. Plus, the documentation doesn't state if the first repo listed in the sources will have precedence over the second repo if a spec is listed in each of them.

**Comment by segiddins** [comment]
I think forking specs repos (if you really need to `lint`) is fine -- the sources are preferred in the order you specify them. The added complexity of being able to override dependencies like that probably isn't worth the implementation cost, sorry.
