### ISSUE TITLE
Always overwriting xcodeproj with the update command

### ISSUE THREAD

**Issue by albtsantos** [CocoaPods/CocoaPods#3588]
No matter what's changed, everytime the update command is executed, the main *xcodeproj* file gets new object ID's for all the items it have – forcing Xcode to refresh the project and, with some gigantic projects and/or slow machines it can be quite sad. Is there any reason why this hasn't been implemented (like Xcode limitations that aren't documented as far as I searched)?

What I thought was to, whenever the command's executed, download Pods separately (if there's any change available), making a diff with the current code and just changing that. The Xcode still refreshes the content but (1) just when it's really needed and (2) it's not the whole file that gets changed.

![Example of ID change without any updates to do](https://cloud.githubusercontent.com/assets/1762338/7716901/0eb3baa0-fe99-11e4-8c50-c28093afea5a.png)

**Comment by segiddins** [comment]
We're already tracking this feature at https://github.com/CocoaPods/CocoaPods/issues/1118.
