### ISSUE TITLE
Dynamic framework dependencies not copied on archive

### ISSUE THREAD

**Issue by damienpontifex** [CocoaPods/CocoaPods#3594]
With the change #3489 after I raised #3440 any pods built against a dynamic framework are now no longer embedded inside the framework. This resolves the submission issue, but now those pods aren't embedded at all. 

With a clean project and doing a pod install, and then archiving the application. Both embed shell scripts are still created, but only the embed of the app pods is actually executed. 

Would it not make sense to include all pods embed phase inside the one app script and then link them against the appropriate target when updating the xcodeproj?

**Comment by neonichu** [comment]
Yes, it seems like this would be appropriate, not only for frameworks, but also application extensions and maybe other kind of code bundles which can be part of an application.

The main problem with this is that CocoaPods at the moment doesn't know which user targets might be embedded into which other user targets, we first have to build that knowledge into it. We also need to solve the issue of the same dependencies with different subspecs being required for that. The larger issue will have to be solved for #3550.

I am not sure we can come up with a short term solution that really works well before #3550 - my recommendation for the short term would be to have a local podspec for your framework, similar to how it is done in <https://github.com/a2/arex-7/blob/master/ArexKit.podspec>

**Comment by damienpontifex** [comment]
At this stage I am just defining all required pods against my main app target and then manually linking the required ones against my Dynamic Framework target. Then in that framework target adding search paths as `$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-<AppName>` and it seems to be working appropriately without too much extra effort

**Comment by samdmarshall** [comment]
That seems like it should be `$(CONFIGURATION_BUILD_DIR)/Pods-$(PRODUCT_NAME)` but that may break depending on how an individual user has configured their Xcode build locations.
