### ISSUE TITLE
Using link_with makes my project failed, Cocopads 0.37

### ISSUE THREAD

**Issue by qiulang** [CocoaPods/CocoaPods#3595]
All my targets use the same libraries, so I use link_with to make my podfile neat. But to my surprise the project compiled failed. Xcode complains it can't find some files in pod, e.g.

    diff: /../Podfile.lock: No such file or directory diff: /Manifest.lock: No such file or directory error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

And

    'DDLog.h' file not found

I run pod install again and clean xcode again and again. But no luck. I was not able to figure out why. From what I can see cocopods only changed shellScript for each target to one single Pods-resources.sh, which is what link_with is supposed to do, right?

shellScript = "\"${SRCROOT}/Pods/Target Support Files/Pods-CloudPhone/Pods-"my target"-resources.sh\"\n";
shellScript = "\"${SRCROOT}/Pods/Target Support Files/Pods/Pods-resources.sh\"\n";

Is this a cocopods's bug? I am using latest one 0.37 and now I went back to specify each target individually.

**Comment by neonichu** [comment]
Do you see any warnings when running `pod install`?

**Comment by qiulang** [comment]
No

**Comment by segiddins** [comment]
Closing since `link_with` is gone in 1.0
