### ISSUE TITLE
AdformAdvertising pod description doesn't update

### ISSUE THREAD

**Issue by vladasdrejeris** [CocoaPods/CocoaPods#3598]
Hi,

I have updated the AdformAdvertising pod to version 2.+, but when I go to "https://cocoapods.org/pods/AdformAdvertising" the description of the pod (readme) is not updated and shown from the old version 0.2.

Thanks for your help.

**Comment by orta** [comment]
The README update isn't instant, it's showing up to `0.2.1` to me. If it's not showing the latest in http://cocaodocs.org ( where those readme's are generated ) then it's worth making an issue on it's repo. :+1:

**Comment by vladasdrejeris** [comment]
How fast it should update? 
In http://cocoadocs.org documentation and readme is up to date.
