### ISSUE TITLE
Unable to find podspecs in private repo

### ISSUE THREAD

**Issue by jonbrooks** [CocoaPods/CocoaPods#3599]
I have a private spec repo configured and installed, but podfiles which refer to pods in this repo can no longer find them.  `pod install` fails with 'Can't find spec for pod xxx' but `pod search xxx` succeeds.  

It looks like the `source` directive has been added as a requirement for podfiles that want to target alternate repos.  (This isn't an option for us, since urls for our private repo are unique per user.)

According to commit 7840787e05afb1da24bcfafa4a62f0de41ebf07a, it looks like `source` directive was intentionally added as a requirement, but then reverted.  My reading of the changelog as it currently stands is that if a podfile doesn't specify a `source` directive, it's supposed to search all available specs.  Is this correct?

The relevant code looks to be in https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer.rb line 490.

**Comment by segiddins** [comment]
Please see https://guides.cocoapods.org/syntax/podfile.html#source. You need to specify that `source` in your Podfile, and that is intentional.

**Comment by jonbrooks** [comment]
So the changelog related to commit 7840787e05afb1da24bcfafa4a62f0de41ebf07a is no longer valid?  I had read through the release notes and found none more recent related to this.  

Do you have suggestions for dealing with a private github repo where each user's url will be unique?

**Comment by neonichu** [comment]
See <https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#breaking> for the changelog entry regarding `source`.

As the `Podfile` can contain arbitrary Ruby, you could read the repo url from a file or an environment variable.

**Comment by jonbrooks** [comment]
Thanks.  That's helpful.
