### ISSUE TITLE
[!] ERROR: Parsing unable to continue due to parsing error:

### ISSUE THREAD

**Issue by kidsid49** [CocoaPods/CocoaPods#3603]
After updating cocoapods to v0.37.1  "Pod update" and and "Pod install" stopped working. It generates  error : 

[!] ERROR: Parsing unable to continue due to parsing error:

https://github.com/CocoaPods/CocoaPods/issues/3597

**Comment by neonichu** [comment]
Should be enough to have #3597 open for this.

**Comment by kidsid49** [comment]
@neonichu Can you help in #3597 I am having a private pod and trying to update it in my app and this error comes up. And hence couldn't able to ship the app new update.  Nobody commented over there from last 2 days :-(
