### ISSUE TITLE
Configuration for pod in default target does not get used by other targets

### ISSUE THREAD

**Issue by JesseCrocker** [CocoaPods/CocoaPods#3605]
### Sample Podfile
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "6.0"
link_with 'App1', 'App2'
pod 'SimulatorStatusMagic', :configurations => ['Debug']

target :app3 do
    link_with 'App3'
    pod 'AFNetworking'
end
```

### Expectation:
SimulatorStatusMagic should be included in the debug config, but not the release config for all 3 targets.

### Result with Cocoapods 0.37.1:
SimulatorStatusMagic is included in only the debug config for App1 and App2, but is included in debug and Release configs for App3

### Workaround for now
adding `pod 'SimulatorStatusMagic', :configurations => ['Debug']` to app3 target fixes the problem.

Note: I have not actually tested the above podfile, this is based on my experience with a much larger podfile, with 20+ pods and 5 targets.

**Comment by johnboiles** [comment]
I'm seeing the same thing on 0.38.2. Duplicating the `pod` line in the target specific section fixes the issue.

My `Pods.release.xcconfig` will correctly omit `SimulatorStatusMagic` from the `OTHER_LDFLAGS` section, however, my `Pods-AppName.release.xcconfig` does not correctly omit `SimulatorStatusMagic` from the `OTHER_LDFLAGS` section.

Here's a condensed version of my Podfile with the fix applied:

```
platform :ios, '8.0'
...
pod 'SVProgressHUD', '~> 1.1.2', :configurations => ['Debug', 'Enterprise']
pod 'SimulatorStatusMagic', :configurations => ['Debug']
pod 'OHHTTPStubs', '~> 4.0.1', :configurations => ['Debug', 'Enterprise']

target :Peer do
    ...
    # There's a bug in CocoaPods where configuration-specific pods don't play nicely with target-specific pods. Because of that, we have to duplicate these lines here.
    pod 'SimulatorStatusMagic', :configurations => ['Debug']
    pod 'OHHTTPStubs', '~> 4.0.1', :configurations => ['Debug', 'Enterprise']
    pod 'SVProgressHUD', '~> 1.1.2', :configurations => ['Debug', 'Enterprise']
end
target :PeerTests do
    pod 'Expecta+Snapshots', '~> 2.0.0'
    pod 'Specta', '~> 1.0.3'
end
```
