### ISSUE TITLE
Why not install pods straghtly from all Repo?

### ISSUE THREAD

**Issue by geek5nan** [CocoaPods/CocoaPods#3612]
I have two `Spec Repo` in my Mac ,the one is Cocopods repo named `master` and the other one is my personal repo named `MyRepo`
![eaff1a75-730f-403a-9506-e7300fdb3641](https://cloud.githubusercontent.com/assets/3816374/7851782/626870fc-0527-11e5-8f91-da976b8bcd98.png)
There is a pod lib named `podtest` in `MyRepo`.
![120503fc-cbec-4ae4-8c88-d2896aa33d03](https://cloud.githubusercontent.com/assets/3816374/7852066/93b0f582-052a-11e5-972d-ca85bf3d0964.png)

 It's must write `source` in `Podfile`  before  use `pod install`  to install `podtest` to my project
![ef238d81-f7b2-44b4-a108-63e02a9a96bb](https://cloud.githubusercontent.com/assets/3816374/7852203/581618ac-052c-11e5-83c9-fe9d3fd9ef40.png)

It's there have a any more convenient method to install pod from all `spec repo`?
Why not install pod from all repo straightly ?

**Comment by segiddins** [comment]
I can't understand what exactly you're asking?

**Comment by segiddins** [comment]
@geek5nan you could do, at the top of your podfile:

```ruby
Pod::SourcesManager.all.map(&:url).each { |u| source u }
```
