### ISSUE TITLE
"pod update RealmSwift" doesn't update the but "pod update" does it

### ISSUE THREAD

**Issue by marcvanolmen** [CocoaPods/CocoaPods#3613]
hi, I just ran this: cocoapod 0.37.1

```
pod update RealmSwift
...
Using Realm (0.92.4)
Using RealmSwift (0.92.4)
...
```
doesn't update it...

When I run

```
pod update
...
Installing Realm 0.93.0 (was 0.92.4)
Installing RealmSwift 0.93.0 (was 0.92.4)
...
```

It gets updated.

**Comment by orta** [comment]
Wonder if it's dependency on Realm keeps it at the same version?

**Comment by segiddins** [comment]
Can you please share your Podfile and Podfile.lock from before running pod update?

**Comment by marcvanolmen** [comment]
Podfile: https://gist.github.com/marcvanolmen/5069831ce1acd7f2753d
Podfile.lock: https://gist.github.com/marcvanolmen/c32e3eaccbc9955f8cb7

**Comment by segiddins** [comment]
Given that podfile, you're seeing the intended result, since you also manually specified Realm. `pod update Realm RealmSwift` will work, as would removing the explicit `Realm` dependency.
