### ISSUE TITLE
prepare_command was never called.

### ISSUE THREAD

**Issue by ArthurBelmonte** [CocoaPods/CocoaPods#3614]
prepare_command is not called because of the "if" condition in line 48 in pod_source_installer.rb
PodSourcePreparer.new(root_spec, root).prepare! if local?

I've read the Pod::Sandbox docs and it says
#local?(name) ⇒ Bool
Checks if a Pod is locally sourced?.

The prepare_command was never called for pods that are sourced remotely.

**Comment by segiddins** [comment]
Can you please provide us with steps to reproduce this issue?

**Comment by ArthurBelmonte** [comment]
Hi Samuel,

I have a prepare_command in my .podspec and I just execute pod install.
That's it.

After a few debugging i found out the my prepare command is not called.

On Thursday, May 28, 2015, Samuel E. Giddins <notifications@github.com>
wrote:

> Can you please provide us with steps to reproduce this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CocoaPods/CocoaPods/issues/3614#issuecomment-106351850>
> .
>


-- 
Regards,
Art Belmonte
*Client Engineering Team*
*Voyager Innovations, Inc.*
*Mobile: (0947) 3371503*


*Get SmartNet on you mobile!*
*Access your Facebook and Twitter with no data costs.*
*www.smartnet.ph* <http://www.smartnet.ph/> |Download on *Appstore*
<https://itunes.apple.com/ph/app/smartnet-for-iphone/id534507373?mt=8&ign-mpt=uo%3D4>
|
Download on *GooglePlay*
<https://play.google.com/store/apps/details?id=ph.com.smart.netphone&feature=search_result#?t=W251bGwsMSwxLDEsInBoLmNvbS5zbWFydC5uZXRwaG9uZSJd>

**Comment by segiddins** [comment]
This still isn't enough for me to reproduce the issue you're seeing. Keep in mind, as of 0.37.1, the prepare command is run before caching the pod, and not on each install.

**Comment by ArthurBelmonte** [comment]
Hi Samuel,

This is the same issue I'm experiencing:
https://github.com/CocoaPods/CocoaPods/issues/3575

So I'll close this issue and just follow issue #3575

Thanks
