### ISSUE TITLE
how to install a specific pod with update the orthers ?

### ISSUE THREAD

**Issue by mrkey0310** [CocoaPods/CocoaPods#3615]
How to install a specific pod with update the orthers ? I had made some change with third framework ,so I want to keep the current version, but when I install new pod ,is still update themselves event I use 'pod install --no-repo-update'

**Comment by segiddins** [comment]
Can you please clarify what's happening that's unexpected?

**Comment by kylef** [comment]
`pod install` shouldn't update pods but instead pin to the versions mentioned in Podfile.lock. Can you please elaborate and include your Podfile and Podfile.lock and perhaps the output from `pod install`.

**Comment by neonichu** [comment]
Let's consider this resolved, as no more information was given.
