### ISSUE TITLE
subspec generating duplicate nested folders when using :path (Development Pods)

### ISSUE THREAD

**Issue by r3mus** [CocoaPods/CocoaPods#3618]
Seeing some strange behaviour when using `:path => '~/Dev/MyPodProject'` in my podspec. Using this as an example subspec:

    s.subspec 'SubProject' do |ss|
        ss.dependency 'Project/Core'
        ss.source_files = 'Project/SubProject/*.{h,m}'
    end

When published, I get a folder structure inside the Xcode project's `Pods` folder like this -- it's working as expected:

    Project
        SubProject
            SomeClass.h
            SomeClass.m
            AnotherClass.h
            AnotherClass.m
        Core
            CoreClass.h
            CoreClass.m

But when I use the `:path` location instead and look in `Development Pods`, it looks like this:

    Project
        SubProject    
            Project
                SubProject
                    SomeClass.h
                    SomeClass.m
                    AnotherClass.h
                    AnotherClass.m
        Core
            Project
                Core
                    CoreClass.h
                    CoreClass.m

**Comment by segiddins** [comment]
I believe this is intentional?

**Comment by r3mus** [comment]
Seems pretty weird to me, but if it's intentional, then ok. I'd personally prefer that Dev Pods behaved the same way Pods does though.

**Comment by neonichu** [comment]
Yes, this is a feature, introduced in 0.36, see #2647

**Comment by r3mus** [comment]
That feature looks to me like it's talking about `preserve_paths` for dev pods - that I get completely. I'd like to understand the value of having the duplicate folder hierarchy though?

**Comment by neonichu** [comment]
The point isn't to duplicate it, but rather to reflect the folders of the filesystem as Xcode groups. It just appears to be duplicated for you, because your folder structure is using the same names as your spec and subspecs.

**Comment by r3mus** [comment]
Ahh ok thanks for the clarification.
