### ISSUE TITLE
Storyboard instances from Cocoapod framework not treated as such in Storyboard

### ISSUE THREAD

**Issue by yoiang** [CocoaPods/CocoaPods#3620]
Hey y'all!
I've ran into an issue with using an instance of a class within a storyboard when that class is defined in a Pod treated as a framework. That's a mouth full. The issue is that where source requires one to import the framework the Storyboard *requires* you to specify *no custom module* for the instance. If you do specify the framework as the custom module it gives this error and will not create your instance:
```
Unknown class _TtC14LLSimpleCamera14LLSimpleCamera in Interface Builder file.
```

I've created an example project here with a working storyboard and a non-working storyboard: [yoiang/Reproduce_CocoapodsCustomModuleStoryboard](https://github.com/yoiang/Reproduce_CocoapodsCustomModuleStoryboard)

Thanks for your time!

**Comment by neonichu** [comment]
I don't think this has anything to do with CocoaPods, apparently using the "custom module" option in IB only works for Swift classes, as seen by the loading mechanism looking for a Swift mangled name. 

It does work completely fine without using "custom module", doesn't it? Any particular reason why you wanted to use that?

**Comment by yoiang** [comment]
Ah so are you saying this is happening because the class isn't a Swift class? When I have a chance I'll test that! If that's the case...oy Apple

Besides being confusing if you use any tools that process storyboards and generate source ((seguecode)[https://github.com/Adorkable/seguecode], (Natalie)[https://github.com/krzyzanowskim/Natalie], etc) the tool can't only rely on the custom module field for knowing what needs to be imported in the generated source that references the class found in a Cocoapod or, from the sound of it, framework.

**Comment by neonichu** [comment]
OK, the behaviour is exactly the same with frameworks created by Xcode, so nothing we can do about it. 

Seems to be radar-worthy, though, as it is indeed confusing to simply assume the use of Swift just because Clang modules are involved.  ¯\\\_(ツ)\_/¯
