### ISSUE TITLE
Update with Merge feature request

### ISSUE THREAD

**Issue by gghanak** [CocoaPods/CocoaPods#3636]
I know CocoaPods is not for version control, but it would be useful to allow for optional merging of changes or some other level of basic conflict resolution if you really need to make a minor change to the code in any particular pod that could not be done by other means...

**Comment by orta** [comment]
I'm not really sure what you mean? This is what forks or local development pods are for. If you wanted to apply a patch to specific pods you could make a plugin that allows this, but it's not really CococaPods' domain.
