### ISSUE TITLE
Duplicate framework

### ISSUE THREAD

**Issue by MarcAudefroy** [CocoaPods/CocoaPods#3637]
Hello,

If we specify in podfile two times the same pod and we use "use_frameworks!".(Because I have a list of "common_pods" for different target).
 Cocoapods generate two same framework. Maybe cocoapods must detect this duplicate framework.

Here a example project with issue : 

https://www.zipshare.com/download/eyJhcmNoaXZlSWQiOiI5NmE0YTVmYS1kZTcxLTQ5Y2YtYTY1ZS03ZmE0NTlkZWM3N2QiLCJlbWFpbCI6ImF1ZGVmcm95Lm1hcmNAZ21haWwuY29tIn0=

**Comment by segiddins** [comment]
This sounds like the exact thing #3550 is meant to fix.
