### ISSUE TITLE
diff: /../Podfile.lock: No such file or directory

### ISSUE THREAD

**Issue by Babelfisch** [CocoaPods/CocoaPods#3641]
After creating my first `Podfile` with:

```
platform :ios, '7.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
```

… running `pod install` and starting Xcode with my project, I get only this build error:

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

What’s wrong?

**Comment by Babelfisch** [comment]
Oh, the error still appears after removing all Pod files from the project. Great :-1:

**Comment by neonichu** [comment]
You can use <https://github.com/kylef/cocoapods-deintegrate> to fully remove CP from your project. 

As far as your error is concerned, checkout this comment <https://github.com/CocoaPods/CocoaPods/issues/2303#issuecomment-48604196> for some info on determining the cause of it.

**Comment by neonichu** [comment]
Let's consider this resolved, as no more information was given.
