### ISSUE TITLE
Move `spec/fixtures/spec-repos/test_repo` to separate repository

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#3642]
### How

* [x] Come up with a more self-explanatory name than `test_repo` (lives alongside the `master` repo, which is named `Specs`)
* [x] Create a repository on GitHub in the CocoaPods organization
* [x] Use `git filter-branch` on a fresh clone to extract the history to a new repository
* [x] Include the new repository as submodule

### Why

It can be used as a valid spec repo in our tests without mocking. This makes it easier to test specific dependency graphs.

**Comment by segiddins** [comment]
:+1:

**Comment by neonichu** [comment]
:+1:

**Comment by nwest** [comment]
In my clone, I ran
```sh
git filter-branch --subdirectory-filter spec/fixtures/spec-repos/test_repo  -- --all
```

and then: 
```sh
git tag | xargs git tag -d
```
(The gem's tags don't really make sense in this new repo)

Which resulted in this:

![screen shot 2016-05-18 at 11 29 32 am](https://cloud.githubusercontent.com/assets/466674/15364795/d83c41b4-1ceb-11e6-855c-3b103ed3bb0b.png)


What should we name the repo? TestSpecs?

**Comment by nwest** [comment]
Actually, `cocoapods-test-specs` would follow the form of https://github.com/CocoaPods/cocoapods-integration-specs.
