### ISSUE TITLE
Pod's resource bundle not copied into app main resource bundle

### ISSUE THREAD

**Issue by aplourde** [CocoaPods/CocoaPods#3643]
I'm running cocoapods 0.37.2.

I have a pod which requires some resources to be copied.
I created my pod with "pod lib create MyPod".
In my podspec, I have this : 
    
    s.resource_bundles = {
        'MyPod' => ['Pod/Assets/*']
    }
    
When I build my example project. The MyPod.bundle file doesn't get copied in the app bundle.
When I look into the Products folder, I see the MyPod.bundle file in the Pods-MyPod_Example folder but it wasn't copied in the into the .app content.

I believe the issue is somewhere in the generated "Copy Pods Resources" script.

**Comment by neonichu** [comment]
This is correct, the pod templates integrates using frameworks now, which leads to the resource bundles being part of their corresponding framework bundle. See remarks about `mainBundle` in <http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/>.
