### ISSUE TITLE
APPLICATION_EXTENSION_API_ONLY=YES  not applied to Pods included in framework with that build setting

### ISSUE THREAD

**Issue by darrenclark** [CocoaPods/CocoaPods#3644]
Setup a demo project here:  https://github.com/darrenclark/ducking-archer  (Though I worked around it in https://github.com/darrenclark/ducking-archer/commit/5074174ffa5c3197b570de524fbe62f7f79f39be)

The 'DataKit' target (a framework shared between the main app & watch extension) has `APPLICATION_EXTENSION_API_ONLY` = `YES` in it's build settings.  However, this doesn't get applied to any Pods that I include in that target.

This isn't a huge issue for me, as we were able to work around it via the `post_install` hook (https://github.com/darrenclark/ducking-archer/blob/master/Podfile#L25).

**Comment by neonichu** [comment]
Sounds like a reasonable thing to do.

**Comment by neonichu** [comment]
Basically would need to amend the detection [here](https://github.com/CocoaPods/CocoaPods/blob/524abbfacb1dc8f1a926e7f6d33197d72c0bfb5a/lib/cocoapods/installer.rb#L563) to also include user target which set this build setting.
