### ISSUE TITLE
Is it possible to have pod install not die if a server is unavailable

### ISSUE THREAD

**Issue by mbjtrifork** [CocoaPods/CocoaPods#3647]
Some of our pods are only available on certain nets. This is a problem as some of our developers do not have access to our private repos. Would it be possible to make pod install simply skip the repos, which it does not have access to?

**Comment by neonichu** [comment]
That wouldn't make much sense, considering that dependencies are hard requirements. The best approach to deal with something like this is checking in your Pods folder.

**Comment by mbjtrifork** [comment]
Our Pods folder is already part of the committed folders, the problem is that the developers who do not have access to our private Pods cannot add new pods from the main repo.

**Comment by segiddins** [comment]
You still should be able to add new pods, as long as you're not removing the Pods directory.

**Comment by mbjtrifork** [comment]
I cannot, I get the following:
[!] Unable to add a source with url `https://code.xxx.com/pods` named `xxxpods`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

**Comment by segiddins** [comment]
Not a situation we plan on supporting, since it would be nearly impossible to guarantee dependency resolution occurred successfully. All developers running `pod install` must have access to all of the specs repos.
