### ISSUE TITLE
Cocoapod is no longer respects the defined folder structure in podspec file?

### ISSUE THREAD

**Issue by kidsid49** [CocoaPods/CocoaPods#3651]
I am working on private pod and used to have a folder hierarchy in my development pods.
I took reference from AFnetworking podspec file.

eg. 

    s.subspec 'Custom UI' do |ss|

        ss.subspec 'Charts' do |sss|
        sss.source_files = 'EagleEye/Custom UI/Charts/*.{h,m}'
        sss.resources = 'EagleEye/Custom UI/Charts/*.{xib}'
        end
    end

And this line used to create a folder Custom UI and a subfolder Charts inside it in Xcode. eg. Custom UI -> Charts
But since I updated my Cocoapod version it creates folder structure eg. CustomUI -> Eagle Eye -> Custom UI -> Charts -> .h&.m files

I didn't get why it's creating unwanted folder structure in XCode.
On the other side on disk eg.  Eagle Eye -> Custom UI -> Charts -> .h&.m files
files are saved like this.

Is it something changed in new versions or am I missing something?

**Comment by neonichu** [comment]
See #3618

**Comment by kidsid49** [comment]
@neonichu appreciate this feature now I don't have to write .podpsec file. But what exactly to specify in 

    s.source_files = ""

so it will replicate the disk folder structure in the XCode. I am cleanning up my .podpsec file and avoid writing any subspecs now.

**Comment by kidsid49** [comment]
@neonichu Btw I start using  

    s.source_files = 'Pod A/**/*'

This works fine for files but fails to create a separate resources folder for .Xibs inside a particular folder.

**Comment by kidsid49** [comment]
Resolved it by using this

    s.resources = 'Pod A/**/*.{xib}' 

It creates different structure for .xibs though. Using subspecs the .xib and .h and .m files used to stay together in same folder.
