### ISSUE TITLE
Using $(var) in podspec's xcconfig causes the value to be duplicated

### ISSUE THREAD

**Issue by ikonst** [CocoaPods/CocoaPods#3652]
For example, let my podspec contain:
```json
  ...
  "xcconfig": {
    "FOO": "bar $(baz)"
  }
  ...
```

then following `pod install` I'd have:

* Pods/Target Support Files/Pods-MyLib/Pods-MyLib.xcconfig:
```
PODS_MYLIB_FOO = bar $(baz) bar $(baz)
```
* Pods/Target Support Files/Pods/Pods.debug.xcconfig:
```
FOO = bar $(baz) bar $(baz)
```

Note how "bar $(baz)" is duplicated.

**Comment by segiddins** [comment]
Can you please share the entire podspec?

**Comment by ikonst** [comment]
A sample podspec will be the Realm podspec, as can be seen here:
https://github.com/realm/realm-cocoa/blob/master/Realm.podspec
(or by adding Realm to your Cocoa project)

Note the line triggering the problem:
```
'OTHER_CPLUSPLUSFLAGS' => '-std=c++1y $(inherited)'
```

Hint: `OTHER_CPLUSPLUSFLAGS` nor `$(Inherited)` plays any role here. My "foobar" sample reproduces the issue just as well.

**Comment by ikonst** [comment]
Was this enough information?
