### ISSUE TITLE
Project not building if I include `use_frameworks!`

### ISSUE THREAD

**Issue by PadraigK** [CocoaPods/CocoaPods#3654]
If I create a new project and add this pod https://github.com/ZaBlanc/RaptureXML/blob/master/RaptureXML.podspec it fails to build with `use_frameworks!` because it can't find referenced libxml headers. Without `use_frameworks!` if works as expected. 

Possibly related to https://github.com/CocoaPods/CocoaPods/issues/3499

**Comment by segiddins** [comment]
The issue is that there's no module map for libxml

**Comment by PadraigK** [comment]
I'm not sure what to do next — is this something the author of that pod needs to add?  All I've found from a few minutes of googling is: http://stackoverflow.com/questions/25171680/swift-framework-with-libxml

**Comment by segiddins** [comment]
It's not a pod, its a system library

**Comment by PadraigK** [comment]
Is the bottom line that no pods that use system libraries can be used with frameworks?

**Comment by neonichu** [comment]
You could try to provide your own module map for libxml, similar to this: <https://github.com/neonichu/SQLite.swift/blob/master/SQLite.swift.podspec#L25-L33>

Also submit a radar, so that this can be eventually unnecessary.

**Comment by PadraigK** [comment]
I just filed Radar 21274224 about this and suggested that work around to the original author of Rapture XML. Thanks for your help @neonichu.

**Comment by neonichu** [comment]
@PadraigK Thanks!

I'll close the issue, as it is not actionable for us.
