### ISSUE TITLE
How to exclude some pods in  tests target?

### ISSUE THREAD

**Issue by hqman** [CocoaPods/CocoaPods#3655]
Is there any standard solution to exclude pods in tests target?

with default setting i have two targets MyApp and MyAppTests
my podfile:
```
source 'https://gitcafe.com/akuandev/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!

pod 'SDWebImage', '~> 3.7.1'
pod 'TTTAttributedLabel', '~> 1.10.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'ODRefreshControl', '~> 1.1.0'
pod 'MJRefresh'

target :'MyAppTests' , :exclusive => false do
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
    pod 'UIViewController+Swizzled', '~> 1.2' , :configurations => ['Debug']
end
```

**Comment by neonichu** [comment]
`:exclusive => true`, see <https://guides.cocoapods.org/syntax/podfile.html#target>

Another option is using target blocks for all targets and define nothing at the root level.

**Comment by hqman** [comment]
@neonichu  I found the real problem is when i add target block and pod install the cocoapods configrations isn't change , https://github.com/kylef/cocoapods-deintegrate the project really save me .

**Comment by steakknife** [comment]
**Needed:** A minimal, working example of common pods, `*Tests'`-only pods and app-only pods.
