### ISSUE TITLE
cocoapods 0.35.0 pod install log is confused

### ISSUE THREAD

**Issue by yangzhihao** [CocoaPods/CocoaPods#3658]
when i run pod install  log is confused,like this

![72e25546-960a-42b0-a968-a0d60d9ae828](https://cloud.githubusercontent.com/assets/3049530/8024563/71331a38-0d6a-11e5-9098-9dcdb09e2da4.png)

how to slove this question?

**Comment by segiddins** [comment]
This only happens with `--verbose`.

**Comment by yangzhihao** [comment]
@segiddins  how can i fix this ?
