### ISSUE TITLE
Reject cocoapods submissions where the submitter didn't alter the default text

### ISSUE THREAD

**Issue by dburr** [CocoaPods/CocoaPods#3664]
So it looks as though the New Cocoapods RSS feed has suddenly sprang back to life. Whoever was responsible for fixing that, Thank you. I actually am probably one of the few people on the planet who still uses an RSS reader, and being able to see a stream of new Pods as they come in is extremely useful to me.

The problem though is that I have been seeing a lot of new pods come across the wire with descriptions like this:

```
A longer description of (pod withheld to protect the ~~innocent~~ guilty) in Markdown format.

Think: Why did you write this? What is the focus? What does it do?
CocoaPods will be using this to generate tags, and improve search results.
Try to keep it short, snappy and to the point.
Finally, don't worry about the indent, CocoaPods strips it!
Authored by (name withheld to protect the ~~innocent~~ guilty)
```

which are absolutely NO help whatsoever.

Would be nice if the cocoapods submission process would reject submissions where the person didn't even bother to change the template text.

**Comment by segiddins** [comment]
We do attempt to do so, see the validator in both CocoaPods and Core.

**Comment by neonichu** [comment]
This is already happening: <https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/linter.rb#L246-L258>
