### ISSUE TITLE
local pod don't work

### ISSUE THREAD

**Issue by lzwjava** [CocoaPods/CocoaPods#3665]
I use
```
    pod 'LeanChatLib', :path => '../LeanChatLib' 
```

LeanChatLib is my framework.

![image](https://cloud.githubusercontent.com/assets/5022872/8075935/bbda6914-0f78-11e5-93f9-8eafe886e0af.png)

But it build failed , say Undefined symbols .These symbols are in the LeanChatLib .So, the local pod is not included.

LeanChatLib also uses cocoapods .

Because it doesn't work, I remove the LeanChatLib pod, but as LeanChatLib use cocoapods, I couldn't drag the LeanChatLib.xcworkspace into the my main workspace.

Hope advice to help me work in two workspace, need directly edit framework source files.

Thanks!

**Comment by jshier** [comment]
I belive I'm seeing the same thing when attempting to validate @kyelf's changes to the Gigya pod I maintain (https://github.com/jshier/GigyaSDK/pull/4). I haven't had time to investigate fully, but at the time it looked like it was properly installing the Gigya framework from the zip file (wasn't even downloaded) and so I ended up with an empty group in Xcode, just like the screenshot above. It happened when I pointed to a git branch or local folder.

**Comment by lzwjava** [comment]
It's my fault.

I changed my podspec from 

```
  s.source_files = 'LeanChatLib/LeanChatLib/Classes/**/*.{h,m}'
```
to 
```
  s.source_files = 'LeanChatLib/Classes/**/*.{h,m}'
```

Then all thins well.

Originally, because pod can not find the sources file, so when use :path to include local pod, there are just empty directory.
