### ISSUE TITLE
Public headers missing from nested pod 🌈 

### ISSUE THREAD

**Issue by jishaq-epoc** [CocoaPods/CocoaPods#3668]
This issue exhibits under CocoaPods 0.37.2.

[MyApplication](https://github.com/jishaq-epoc/cocoapods-header-issue-MyApplication) indicates a dependency upon the iOS static library [OuterLib pod](https://github.com/jishaq-epoc/cocoapods-header-issue-OuterLib) as follows:

```
# MyApplication's Podfile
pod "OuterLib", :path => "../InnerLib"
```

The iOS static library [OuterLib pod](https://github.com/jishaq-epoc/cocoapods-header-issue-OuterLib) indicates a dependency upon the iOS static library [InnerLib pod](https://github.com/jishaq-epoc/cocoapods-header-issue-InnerLib) as follows:

```
# OuterLib's Podfile
pod "InnerLib", :path => "../InnerLib"
```

If I do a pod install from MyApplication's root directory, the resulting Pods/Headers/Public path contains an OuterLib folder; as expected, this contains .h files from the OuterLib project.  You can try it out yourself by syncing the three git-hub projects in the URL links above.  However, there isn't also a corresponding Pods/Headers/InnerLib folder with InnerLib's .h files.  As such, MyApplication fails to build because its Pods-MyApplication-OuterLib target can't find InnerLib.h:

`OuterLib.m:10:9: fatal error: 'InnerLib.h' file not found`

You can reproduce this build error by syncing the three git-hub projects in the URL links above, doing a `pod install` in the MyApplication directory, and then attempting to build the workspace in Xcode.

How can I tell CocoaPods that OuterLib needs to expose InnerLib's public header files?

One workaround I found was to have MyApplication explicitly indicate a dependency on InnerLib in its Podfile; however, MyApplication shouldn't need to know the details of OuterLib's dependencies, so I consider this a hack:

```
# MyApplication's Podfile
pod "OuterLib", :path => "../OuterLib"

# MyApplication has no business knowing that OuterLib is using InnerLib
# behind the scenes, so I consider this a hack:
pod "InnerLib", :path => "../InnerLib" 
```

**Comment by neonichu** [comment]
You need to have a `dependency` between both your Pods for this to work. Dependencies are declared in the [podspec](https://guides.cocoapods.org/syntax/podspec.html#dependency).

**Comment by jishaq-epoc** [comment]
@neonichu: Thanks for confirming this.  And, therein lies the problem I am having.  How, *exactly*, does one define a Podspec dependency when the pod reference is via the `:path =>` directive? 

For example, adding this to [OuterLib's Podspec](https://github.com/jishaq-epoc/cocoapods-header-issue-OuterLib/blob/master/OuterLib.podspec):
```
      s.dependency "InnerLib", "0.0.1"
```
... produces the following error:
```
11:44:50-jishaq@jishaq-mbpr15:~/Desktop/MyApplication$ pod install
Analyzing dependencies
Fetching podspec for `OuterLib` from `../OuterLib`
[!] Unable to find a specification for `InnerLib (= 0.0.1)` depended upon by `OuterLib`
11:45:08-jishaq@jishaq-mbpr15:~/Desktop/MyApplication$ 
```

While we are in the process of moving our pods to being hosted on a private git repository, they presently aren't; in this interim, we must use filesystem referneces, and therefore the `:path =>` directive, rather than specifying a git-hosted `source`.  

So it seems, ultimately, is that the `dependency` directive doesn't seem capable of supporting pods referenced via `:path =>`.  Unless there is some sneaky syntax to do this that I've not yet discovered, I would consider this a bug / feature request; please let me know if you agree, and how I can best log this in the system for consideration.

Thanks again for your time.  Any input is appreciated!

**Comment by neonichu** [comment]
It is by design that the specification defines the what and the Podfile defines the where of dependencies (See also #2937). As you already state in your comment, custom spec repos are the correct solution for this.
