### ISSUE TITLE
Xcode 7, Swift, pod modules not found

### ISSUE THREAD

**Issue by jshier** [CocoaPods/CocoaPods#3669]
In attempting to see how well a Swift core app with the iOS 9 SDK but an iOS 7 deployment target works with strictly Objective-C dependencies (don't ask), I'm running into an issue where none of the modules from the pods are able to be `import`d into Swift code or `@import`d into Objective-C code. However, I was able to workaround the issue by `#import`ing them into the bridging header Xcode generated when I added some Objective-C files.

[Here's a snapshot of the project.](https://www.dropbox.com/s/fyslqpojj9m50b3/9to7Test.zip?dl=0)

**Comment by segiddins** [comment]
Yes, that's necessary as you're not integrating your pods as frameworks.

**Comment by jshier** [comment]
Makes sense. Sorry.
