### ISSUE TITLE
add watchOS platform support

### ISSUE THREAD

**Issue by danielphillips** [CocoaPods/CocoaPods#3673]
I am unable to use CocoaPods with my new watchOS 2 application in Xcode 7 beta.

`Pods was rejected as an implicit dependency for 'libPods.a' because it doesn't contain platform 'watchsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'`

**Comment by joeboyscout04** [comment]
Having the same problem...it worked briefly, but then something went wrong when I opened the same project in Xcode 6 and now I can't get it working again.  Keep getting the error above.

**Comment by beltex** [comment]
Hi @danielphillips!

See https://github.com/CocoaPods/CocoaPods/pull/3681

**Comment by neonichu** [comment]
You especially want to check out <https://github.com/neonichu/native-watchOS-example>

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/pull/3681.
