### ISSUE TITLE
A Podspec's 'prepare_command' is not executed under certain circumstances on '0.37.2'.

### ISSUE THREAD

**Issue by haShalosh** [CocoaPods/CocoaPods#3674]
🌈
When using Cocoapods 0.37.2, and having a config file, "~/.cocoapods/config.yaml", that disables caching using "skip_download_cache : true", the "prepare_command" of a podspec is not executed.

Example:
Make a Podfile that uses UrbanAirship version '4.0.4'. See that it doesn't convert "UANativeBridge.js" to "UANativeBridge.c".

Note:
Make sure to delete the Pods folder when 'skip_download_cache' is enabled/disabled, as to not mask the issue being introduced/resolved.

**Comment by neonichu** [comment]
@segiddins I believe this is relevant to your interests.
