### ISSUE TITLE
linting hangs forever when linting swift library

### ISSUE THREAD

**Issue by tskulbru** [CocoaPods/CocoaPods#3679]
So I've created this swift library [NBMaterialDialogIOS](https://github.com/tskulbru/NBMaterialDialogIOS). I'm now ready to publish it to trunk but for some reason the `pod lib lint`tool simply stops/hangs when running `xcodebuild clean build -target Pods CODE_SIGN_IDENTITY=- -sdk iphonesimulator 2>&1`

I've included the output of said command: [gist](https://gist.github.com/tskulbru/dab8c95e4a1a4e22f8db) Everything just hangs after the last line and i get a swift process in my activity monitor which uses 100% of my cpu.

Im using xcode 6.3.2 with latest cocoapods and command line tools.

**Comment by neonichu** [comment]
Interesting, if you run this command separately, outside of `pod lib lint`, does it exhibit the same behaviour?

**Comment by tskulbru** [comment]
You mean `xcodebuild clean build -target Pods CODE_SIGN_IDENTITY=- -sdk iphonesimulator 2>&1`? If so, then yes. The included gist is the output of that command.

**Comment by neonichu** [comment]
OK, this is amazing!

Apparently, compiling `NBMaterialAlertDialog.swift` works fine from the Xcode UI, but hangs indefinitely when building on the command line via `xcodebuild`.

Unfortunately, this issue is out of our control, as it happens inside Xcode. Please file a radar with Apple.

**Comment by tskulbru** [comment]
Thanks, ill contact them and hear.

**Comment by neonichu** [comment]
FYI, the difference between Xcode and `xcodebuild` is caused by a difference in build configurations. In Xcode, `Debug` is used by default whereas `xcodebuild` uses `Release`. This is still an Xcode issue, but of a different kind.

**Comment by neonichu** [comment]
I filed a radar for this myself now, see <http://www.openradar.me/21421339>
