### ISSUE TITLE
Can any one install on OS X 10.11

### ISSUE THREAD

**Issue by powhu** [CocoaPods/CocoaPods#3680]
Try a lot  but still get this error on 10.11

    ERROR:  While executing gem ... (Errno::EPERM)
        Operation not permitted - /usr/bin/xcodeproj

**Comment by segiddins** [comment]
what about `sudo gem install cocoapods` ? There might be some issues with the rootless changes in El Capitan, but I haven't talked to the RG folks about that yet. Anyways, this is purely about rubygems, and isn't a cocoapods issue. You can always use CocoaPods.app in the meantime!

**Comment by powhu** [comment]
Thank you. I follow this [link](https://gorails.com/setup/osx/10.11-el-capitan) update ruby for el capital and it work.

**Comment by kylebrowning** [comment]
I don't want to install home-brew, any other way?

**Comment by postmechanical** [comment]
Without homebrew there seems to be no other way at the moment. `sudo gem install cocoapods` results in the same error.

**Comment by segiddins** [comment]
You can `gem install` using a `GEM_HOME` that you can write to. Outside of that, _definitely_ file a radar, since `gem install` should work by default.

**Comment by kylebrowning** [comment]
I found out how, and answered here. 

http://stackoverflow.com/questions/30812777/cannot-install-cocoa-pods-after-uninstalling-results-in-error/30851030#30851030

**Comment by postmechanical** [comment]
@kylebrowning :clap: :clap: thanks!

**Comment by postmechanical** [comment]
Got it working with @segiddins recommendation by updating my `~/.bash_profile` with:

    export GEM_HOME=~/.gems
    export PATH=$PATH:~/.gems/bin

**Comment by rajeshr** [comment]
As rootless does not affect /usr/local/bin, the following succeeds:

    sudo gem install -n /usr/local/bin cocoapods

Any caveats?

**Comment by nicolastinkl** [comment]
Im assuming you're running OS X 10.11.

This is happening because Apple has enabled rootless on the new install.

If you type sudo nvram boot-args="rootless=0"; sudo reboot in terminal.app Your computer will reboot with it disabled.

Once that is done, type

sudo gem install cocoapods -V

the -V is for verbose and will spit out any errors if they happen.

from stackoverflow.com

**Comment by kylebrowning** [comment]
@nicolastinkl Why would you copy and paste what I already said?

**Comment by segiddins** [comment]
No, please do not disable rootless just to install a gem.

**Comment by kylebrowning** [comment]
@segiddins. What?

**Comment by gehero** [comment]
@rajeshr  it's good, thank you

**Comment by appdog** [comment]
Can confirm that solution of @rajeshr worked for me.

**Comment by fernandolicon** [comment]
@rajeshr solution worked for me too.

**Comment by RichFell** [comment]
@rajeshr  solution works for me as well.

**Comment by hardikdevios** [comment]
@rajeshr :+1:  mate soultion is working for me too

**Comment by therohansanap** [comment]
@rajeshr thanks a lot!

**Comment by tzungtzu** [comment]
@rajeshr solution works for me too!

**Comment by thewhitewood** [comment]
@rajeshr solution works for me as well!

**Comment by CowPanda** [comment]
@kylebrowning thanks!

**Comment by aubada-taljo** [comment]
@powhu It worked for me too, thank you

**Comment by hanushka** [comment]
@rajeshr Your solution worked. Thanks (Y)

**Comment by dchollo82** [comment]
Thanks @rajeshr, your solution helped me install a bunch of gems including sass and compass.
However, I did originally run sudo nvram boot-args="rootless=0" as suggested in @nicolastinkl post; 
Does anyone know how to revert this? Just concerned about security as I'm not sure what this has done. Thanks

**Comment by davegerard** [comment]
Thanks @Powhu, that worked for me.

**Comment by ToonoW** [comment]
` sudo gem install -n /usr/local/bin cocoa pods ` 
It is useful.

**Comment by joliylee** [comment]
@rajeshr :+1: Thanks

**Comment by Jerry-Lau** [comment]
@rajeshr thanks for the solution!

**Comment by duk42111** [comment]
Thanks.

**Comment by raymondle** [comment]
@rajeshr Thanks, it worked for me :+1:

**Comment by harveyzhang1028** [comment]
The following works for me. My Mac version is OS X EI Capitan 10.11.3. Thanks guys!
sudo gem install -n /usr/local/bin cocoapods

**Comment by charleskubicek** [comment]
@rajeshr worked for me, thanks!

**Comment by duk42111** [comment]
worked for me, thanks

**Comment by Schemetrical** [comment]
Worked, thanks :)

**Comment by naishta** [comment]
Still doesn't work for me. I still get the error
ERROR:  Could not find a valid gem 'cocoapods' (>= 0) in any repository

with the command 'sudo gem install -n /usr/local/bin cocoapods'

Please help !

**Comment by helabenkhalfallah** [comment]
@rajeshr worked for me, thanks !

**Comment by misbell** [comment]
@rajeshr worked for me as well. I tried to manually create xcodeproj in usr bin, even sudo wouldn't let me.

**Comment by renguochao** [comment]
@rajeshr solution works for me as well.

**Comment by Tamilarasu2608** [comment]
worked for me, thanks !

**Comment by timlehr** [comment]
`sudo gem install -n /usr/local/bin cocoapods`
Works with 1.0.0 and OS X 10.11.5 for me. Thanks! 👍

**Comment by elliwood** [comment]
`sudo gem install -n /usr/local/bin cocoapods` works for me
but i continued type `pod setup` and i got error message

> [!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master
> 
> Cloning into 'master'...
> error: RPC failed; curl 56 SSLRead() return error -9806
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed

My Mac version is OS X EI Capitan 10.11
Please help !

**Comment by elliwood** [comment]
OK, i did it working by myself. This is my solution:

> 1. `sudo gem install -n /usr/local/bin cocoapods`
> 2. `pod setup` and go to folder .cocoapods/repos/master and copy folder .git  and Ctrl + C
> 3. Now, create again folder master and copy folder .git in previous step to inside it.
> 4. Manually download from url 'https://github.com/CocoaPods/Specs/archive/master.zip' and extract t folder master.
> 5. Go to project folder
>      - `touch Podfile` and insert your code
>      - `pod install --no-repo-update`

Done !

See last answer in link [http://stackoverflow.com/questions/21022638/pod-install-is-staying-on-setting-up-cocoapods-master-repo#comment53771519_32964100](url)

**Comment by juanmorillios** [comment]
thans @rajeshr ,  Works with 1.0.0 and OS X 10.11.5 for me. Thanks!

**Comment by lzybala** [comment]
@rajeshr solution works! but pop command still not found?
