### ISSUE TITLE
Pod Targets should be ordered as case insensitive

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#3684]
![screen shot 2015-06-14 at 16 51 13](https://cloud.githubusercontent.com/assets/49038/8151012/a6a4784c-12b5-11e5-9bbc-6e642f5bbc21.png)

**Comment by marcelofabri** [comment]
Shouldn't this also apply to other lists? Such as the result of `pod install` and the `Pods` group inside `Pods.xcodeproj`.

**Comment by segiddins** [comment]
Yup, @marcelofabri ! Basically anywhere we sort based on a string, we should sort based on a normalized version of that string that makes case uniform, and probably strips out unicode characters for their ascii equivalents

**Comment by emkosz** [comment]
Working on this one and should have a PR ready by next week.

**Comment by segiddins** [comment]
Done by @emkosz !
