### ISSUE TITLE
Sorry but can someone tell me what should I do with this error?

### ISSUE THREAD

**Issue by whoiswayne** [CocoaPods/CocoaPods#3686]
LoadError - dlopen(/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/x86_64-darwin14.0.0/psych.bundle, 9): Library not loaded: /usr/local/lib/libyaml-0.2.dylib
  Referenced from: /Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/x86_64-darwin14.0.0/psych.bundle
  Reason: image not found - /Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/x86_64-darwin14.0.0/psych.bundle
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/psych.rb:1:in `<top (required)>'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/2.0.0/yaml.rb:5:in `<top (required)>'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/sources_manager.rb:310:in `version_information'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/sources_manager.rb:273:in `repo_compatible?'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/sources_manager.rb:337:in `master_repo_functional?'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:40:in `parse'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:266:in `run'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/gems/2.0.0/gems/cocoapods-0.34.4/lib/cocoapods/command.rb:50:in `run'
/Users/wayne/.rvm/rubies/ruby-2.0.0-p594/lib/ruby/gems/2.0.0/gems/cocoapods-0.34.4/bin/pod:33:in `<top (required)>'
/Users/wayne/.rvm/gems/ruby-2.0.0-p594/bin/pod:23:in `load'
/Users/wayne/.rvm/gems/ruby-2.0.0-p594/bin/pod:23:in `<main>'
/Users/wayne/.rvm/gems/ruby-2.0.0-p594/bin/ruby_executable_hooks:15:in `eval'
/Users/wayne/.rvm/gems/ruby-2.0.0-p594/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by whoiswayne** [comment]
Oh my ruby installation is missing psych.

**Comment by mmiroslav** [comment]
`$ sudo gem update `
