### ISSUE TITLE
Please can you remove EvercamNetworking cocoapod?

### ISSUE THREAD

**Issue by supertalent1982** [CocoaPods/CocoaPods#3690]
Hello,
I have published a pod called EvercamNetworking, but now it is unusuable.
Owner of pod is Jiang Wei. The linked github url is not working .

Thanks for your help.

**Comment by neonichu** [comment]
We're extremely cautious about removing pods completely, the database was created to be read only, so our policy is to have people submit PRs to the specs repo adding a deprecated flag: https://github.com/CocoaPods/Specs/pull/12199
