### ISSUE TITLE
[0.37.2] Stale .podspec files in `Pods/Local Podspecs`

### ISSUE THREAD

**Issue by Inferis** [CocoaPods/CocoaPods#3691]
I had an issue with development pods where stale .podspec files in the `Pods/Local Podspecs` folder were taking precedence over the .podspec.json files for the same development pods. So in essence, for each development pod there were two podspecs (a `.podspec` and `.podspec.json`). 

The problem with this is that even though the `.podspec.json` file is updated, the out of date `.podspec` file is used  as a reference. Adding dependencies or making changes to the source podspec would not have effect.

I fixed this by manually deleting all `.podspec` files with an accompanying  `.podspec.json` equivalents. After that, everything worked fine.

**Comment by neonichu** [comment]
Related #3038

But you said in a private conversation that these Pods were actually created post this fix, so that there should have never been a `.podspec` in the first place. Other tidbit is that you're checking in the `Pods` folder.

**Comment by segiddins** [comment]
The migration to 0.36 should've fixed this?

**Comment by Inferis** [comment]
Confirmed that we check in pods. 

The pods where created somewhere in April, so that was after this was introduced?
The timestamps on two of the podspecs were May 21th, so that's the last time they were updated. That's not saying much in itself.

AFAIK all team members are on 0.37.

**Comment by segiddins** [comment]
I'm kinda tempted to say just nuke those stale ruby podspecs and chalk this up to a migration hiccup, if that's OK?

**Comment by Inferis** [comment]
Yeah, fine by me. ;)
