### ISSUE TITLE
Podspec `vendored_` keywords are poorly named

### ISSUE THREAD

**Issue by zygoat** [CocoaPods/CocoaPods#3693]
The Podspec keywords `vendored_frameworks` and `vendored_libraries` are poorly named, making their purpose non-obvious.

The [Podspec documentation] (https://guides.cocoapods.org/syntax/podspec.html#vendored_frameworks) explains that these file pattern keywords indicate “the paths of the (framework bundles | libraries) that come shipped with the Pod.”

Apparently “vendored” is a neologism used by a subset of the software industry, but a word uncommon to regular English speakers (for whom “vendor” is a noun, and “vend” is the verb). Aside from its familiarity as jargon to some people, this term obscures the intended meaning and affords little extra value over commonplace words that naturally convey the same. Improved names would make the purpose of the keywords more self-evident.

Clearer alternatives might include *“prepackaged”, “bundled”, “provided”, “included”*, or *“shipped”* (so as to create keywords named like `prepackaged_frameworks` and `prepackaged_libraries`).

🌈

**Comment by neonichu** [comment]
The term is pretty widely established, also it doesn't really feel like a minor language issue like this would be worth breaking backwards compatibility for.

**Comment by segiddins** [comment]
I can appreciate the sentiment behind wanting a clearer word, but I agree with @neonichu here that the complexity introduced by such a change wouldn't really be worth it.
