### ISSUE TITLE
Specifying 'platform :ios' in Podfile results in no code files for subspec-only podspec

### ISSUE THREAD

**Issue by emaloney** [CocoaPods/CocoaPods#3696]
A user of [MBToolbox](https://cocoapods.org/pods/MBToolbox) reported a problem when specifying the platform in his `Podfile` as follows:

```
platform :ios
```

Explicitly specifying the playform resulted in a nearly-empty directory within `Pods/MBToolbox`.

This project is an iOS-only Cocoapod and everything works correctly when the text `platform :ios` is omitted from the Podfile.

I tried tweaking the contents of the [`MBToolbox.podspec`](https://github.com/emaloney/MBToolbox/blob/master/MBToolbox.podspec), to no avail. (Releases 1.1.0 —> 1.1.4 all contain different versions of the podspec, none of which worked correctly when `platform :ios` was specified in the `Podfile`.)

Here are the contents of `Pods/MBToolbox` when `platform :ios` is present in the `Podfile`:

```
 8 -r--r--r--   1 emaloney  staff   1.1K Jun 17 12:02 LICENSE
24 -r--r--r--   1 emaloney  staff    10K Jun 17 12:02 README.md
```

When `platform :ios` is omitted, the directory contains everything as expected:

```
 0 drwxr-xr-x   3 emaloney  staff   102B Jun 17 13:23 BuildControl/
 0 drwxr-xr-x  19 emaloney  staff   646B Jun 17 13:23 Code/
 8 -r--r--r--   1 emaloney  staff   1.1K Jun 17 13:23 LICENSE
24 -r--r--r--   1 emaloney  staff    10K Jun 17 13:23 README.md
```

The Cocoapod is comprised entirely of subspecs, and originally the platform and deployment target were specified [at the level of the containing spec](https://github.com/emaloney/MBToolbox/blob/1.1.0/MBToolbox.podspec#L20-L21) (version 1.1.0):

```
s.platform              = :ios, '8.0'
s.ios.deployment_target = '7.0'
```

Since that wasn't working with `platform :ios`, I tried explicitly specifying the platform and deployment target [at the level of each subspec](https://github.com/emaloney/MBToolbox/blob/1.1.1/MBToolbox.podspec#L56-L57) also. (That was versions 1.1.1 and 1.1.2).

That didn't work either, so I tried adding a Mac OS X deployment, forgetting that I'm importing UIKit (doh!), and of course the podspec wouldn't work. (Version 1.1.3)

Finally, for [version 1.1.4](https://github.com/emaloney/MBToolbox/tree/1.1.4) (the latest), I simply removed the explicit base SDK from the `platform`, so it is now:

```
s.platform              = :ios
```

Still no luck.

I could've sworn this worked correctly several versions of Cocoapods ago, and I'm at a loss for what I'm doing wrong (if anything) in the podspec. It feels like a bug in Cocoapods itself, but perhaps I'm wrong.

### Steps to Reproduce

1. Create a new Xcode project for an iOS app
2. Create a `Podfile` with the following contents:

```
platform :ios

pod 'MBToolbox', '~> 1.1.0'
```

3. Run `pod install`
4. `cd` into `Pods/MBToolbox`
5. List the directory contents

### Expected Result

The `Pods/MBToolbox` directory would contain `BuildControl`, `Code`, `LICENSE` and `README.md`.

### Actual Result

`Pods/MBToolbox` contains only `LICENSE` and `README.md`.

### Additional information

Removing `platform :ios` from the `Podfile` works around the issue (but doesn't seem correct).

**Comment by segiddins** [comment]
@emaloney can you please provide us with more complete steps to reproduce the issue? Thanks!

**Comment by emaloney** [comment]
Sorry, I accidentally posted before I was done editing. Working on it now!

**Comment by emaloney** [comment]
Ok, it's all fleshed out now.

**Comment by segiddins** [comment]
The issue with this is the default when you specify `platform :iOS` is the `4.3` deployment target, which is obviously incompatible with you podspec's 7.0 requirement.

If they specify `platform :ios, '7.0'`, everything should work!
