### ISSUE TITLE
`pod lib create` creates not working project with predefined Quick tests

### ISSUE THREAD

**Issue by skywinder** [CocoaPods/CocoaPods#3704]
Check screenshot, for `./Example/*.xcodeworspace` opened right after installation:

![screen shot 2015-06-19 at 11 00 56](https://cloud.githubusercontent.com/assets/3356474/8249437/a289605e-1672-11e5-9a54-360acc4c88af.png)

All these errors and warnings could be fixed automatically, as Xcode suggests, but one problem still exist, and don't know how to fix it:
Error:
> ProjName/Example/Pods/Quick/Quick/World.swift:138:78: '[Example]' does not have a member named 'contains'

for string:

            let spec = rootExampleGroupForSpecClass(specClass).examples.filter { included.contains($0) }

![screen shot 2015-06-19 at 11 05 20](https://cloud.githubusercontent.com/assets/3356474/8249470/1e00549a-1673-11e5-99b1-d6afe8b96bf1.png)

**Comment by segiddins** [comment]
What version of Xcode are you using?

**Comment by skywinder** [comment]
Version 6.3.1 (6D1002)

**Comment by DenHeadless** [comment]
This happened to me yesterday as well. I was making new pod with Swift and Quick/Nimble, and saw the same warnings and errors. 

This seems like an issue of latest Quick, though i'm not sure.

**Comment by neonichu** [comment]
The issue is that the newest Quick release 0.4.0 only supports Swift 2.0 - we need to pin the pod template to `'~> 0.3.1'`

**Comment by orta** [comment]
Yeah

**Comment by orta** [comment]
https://github.com/CocoaPods/pod-template/commit/185ef8980e7d33e14373f2266b6603eb2c7cdd19
