### ISSUE TITLE
Add support for multiple platforms

### ISSUE THREAD

**Issue by mikker** [CocoaPods/CocoaPods#3710]
As the doc explains you can make your pod universal by not specifying a platform. But if your pod is written in Swift, `pod lib lint` will tell you that it needs iOS >= 8.

How about:

```
s.platform = {ios: '~> 8', osx: '~> 10.10'}
```

instead of the current array form?

**Comment by neonichu** [comment]
This is already possible: 

```ruby
  s.ios.deployment_target = '5.0'
  s.osx.deployment_target = '10.7'
```

**Comment by mikker** [comment]
Boom! Thank you.
