### ISSUE TITLE
Errno::ENOENT - No such file or directory when upgrade to 0.37.2

### ISSUE THREAD

**Issue by ouyongyong** [CocoaPods/CocoaPods#3715]
I ran "pod lib lint" and it throw this error
Errno::ENOENT - No such file or directory - /private/var/folders/3y/xt03_rxd5sn965y8s3dfrzyc0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj/xcuserdata/ouyongyong.xcuserdatad/xcschemes/Pods-KILib-KILib.xcscheme

I open the folder in /private/var/folders/3y/xt03_rxd5sn965y8s3dfrzyc0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj/xcuserdata/ouyongyong.xcuserdatad/xcschemes/ and I only find this file Pods-KILib.xcscheme

it was OK when I use cocoapod v-0.34.4

**Comment by neonichu** [comment]
We need a bit more info here, e.g. can you share the Pod or at least your podspec, please?

**Comment by ouyongyong** [comment]
Finally I find a way to fix it .
I fix all the warning in codes of my develop pod, and pass the validate.
but I still have a problem, if I use the third party pod 'UMengAnalytics', and when I run the example project, it throw an error "Embedded dylibs/frameworks only run on iOS 8 or late"
It happened only when I use cocoa pod 0.37.x, not when I use 0.36.x or below.

here is my subspec define
s.subspec '_3PPUtils' do |_3PP|
      _3PP.source_files = 'Pod/Classes/3PPUtils/**/*.{m,h}'
      _3PP.public_header_files = 'Pod/Classes/3PPUtils/**/*.h'
      _3PP.dependency 'UMengAnalytics'
      _3PP.dependency 'KILib2/CommonTools'
  end

**Comment by segiddins** [comment]
@ouyongyong that's not an issue, but that error should be more relaxed in the next release.
