### ISSUE TITLE
Download size metric is correct?

### ISSUE THREAD

**Issue by skywinder** [CocoaPods/CocoaPods#3716]
Hi.
I found -10 point in my pod metric:
http://cocoapods.org/pods/GaugeKit/quality

for "Download size". But Download size is only 25 KB. I have images and animated gif in repo (to show, how it works in readme.md), but these files is not part of my pod. The Folder of installed Pod is only 25 KB. Probably there is some mistake in calculations of these metric?
![screen shot 2015-06-22 at 14 46 10](https://cloud.githubusercontent.com/assets/3356474/8281194/0ea9bcb6-18ee-11e5-932f-b41387cabfc1.png)

**Comment by k0nserv** [comment]
Hey @skywinder,

the download size penalty is applied to the whole repo because we still have to download it all when using it as a dependency. This was recently clarified https://github.com/CocoaPods/cocoadocs-api/pull/6/files  

![image](https://cloud.githubusercontent.com/assets/1333960/8281331/1a9f18ce-18e7-11e5-9ab0-aa21c67e276e.png)

**Comment by skywinder** [comment]
Ok. I think it's not quite correct measure.

FYI: answer of @orta by mail:

>This is a mis-match with my current thoughts on how that size should be measured, currently it measures the full repo download size which is 10meg for GuageKit - I think that the impact on your app is more important and will probably be changing the metric pretty soon.

**Comment by k0nserv** [comment]
Yeah I agree with @orta here too

**Comment by neonichu** [comment]
I totally disagree, because if the download size and installation size are mismatching a lot, the repo is just badly organised. Why put irrelevant stuff in the same repo as your Pod?

**Comment by orta** [comment]
I don't think "Is this a bad library" if it takes longer to clone, that means it's either more mature or has more examples. I think 'Is this a bad library" when it includes megabytes of stuff in my app.

**Comment by k0nserv** [comment]
Well in the case of GaugeKit there are a lot of nice gifs showcasing how it works which IMO is really important when building a view/UI component.

**Comment by neonichu** [comment]
But why do those GIFs have to live inside the repo in a way that they get downloaded all the time? They could be hosted externally or live in a submodule.

**Comment by k0nserv** [comment]
@neonichu I agree, but that complicates things for maintainers and the common solution ATM is to keep such assets in the repo

**Comment by skywinder** [comment]
@neonichu What the reason to store images separately? Usually tests could be bigger, than project itself, is it means, that tests is also should be stored in other repo?

**Comment by neonichu** [comment]
Well, the reason is to not download 10MB of unnecessary stuff all the time. But since everyone else disagrees with me, we *should* change the metric, so it is more in line with people's expectations.

**Comment by k0nserv** [comment]
@skywinder That is a fair point, but tests are still code so they will not be large enough to make an impact

Here's the division of size for GaugeKit

```bash
 40K	./.git/hooks
4.0K	./.git/info
4.0K	./.git/logs/refs/heads
4.0K	./.git/logs/refs/remotes/origin
4.0K	./.git/logs/refs/remotes
8.0K	./.git/logs/refs
 12K	./.git/logs
  0B	./.git/objects/info
6.8M	./.git/objects/pack
6.8M	./.git/objects
4.0K	./.git/refs/heads
4.0K	./.git/refs/remotes/origin
4.0K	./.git/refs/remotes
  0B	./.git/refs/tags
8.0K	./.git/refs
6.9M	./.git
 56K	./Example/Example/Base.lproj
188K	./Example/Example/Images.xcassets/AppIcon.appiconset
 12K	./Example/Example/Images.xcassets/BurnDashboardIcon.imageset
116K	./Example/Example/Images.xcassets/logo30.imageset
136K	./Example/Example/Images.xcassets/logo76.imageset
452K	./Example/Example/Images.xcassets
524K	./Example/Example
4.0K	./Example/Example.xcodeproj/project.xcworkspace
 24K	./Example/Example.xcodeproj
8.0K	./Example/ExampleTests
556K	./Example
 32K	./GaugeKit
4.0K	./GaugeKit.xcodeproj/project.xcworkspace
 20K	./GaugeKit.xcodeproj
4.0K	./GaugeKit.xcworkspace/xcshareddata
8.0K	./GaugeKit.xcworkspace
8.0K	./GaugeKitTests
5.0M	./Images
 13M	.
```

The images are most of the size. Again I agree that the size of the repo should not impact the quality, but @neonichu has a good point about download time too
