### ISSUE TITLE
Is there a way to get the local folder location of a cocoapod?

### ISSUE THREAD

**Issue by Inferis** [CocoaPods/CocoaPods#3717]
For the link phase of my project, I need to reference a file which is inside a CocoaPod. So I'd like to get the local folder location of the pod, so that I can pass the full filename to the linker (using LD_FLAGS). 

I don't see a way to reference that file (by either an absolute or a relative file path) in a transparant way. Or am I doing this wrong?

**Comment by Inferis** [comment]
Also, I'd like to add that this pod is (currently) a development pod but will move to a private pod later on.

**Comment by segiddins** [comment]
Not currently possible, but you could get the path via a post install hook in your Podfile.
