### ISSUE TITLE
Equivalent to `bundle check` for Cocoapods.

### ISSUE THREAD

**Issue by dtrenz** [CocoaPods/CocoaPods#3718]
As an iOS developer,
I would like to be able to use `pod check` in a `post-merge` git hook,
so that I can detect if I need to run `pod install` due to the dependency updates.

Bundler has `bundle check` (http://bundler.io/v1.1/bundle_check.html), I would like a similar command to be available for Cocoapods. Thanks

**Comment by segiddins** [comment]
@dtrenz this sounds like it would be perfect for a plugin! Would you be interested in building it?

**Comment by dtrenz** [comment]
I was just thinking the same. I will give it a go.

**Comment by segiddins** [comment]
This plugin could just diff `config.sandbox.manifest_path` with `config.lockfile_path`.

**Comment by JakePayton** [comment]
yep, we considered the same approach when we started looking at this.  We'd at least save you from opening Xcode and seeing the Podfile.lock is not in sync with Manifest.lock, run pod update.....

**Comment by segiddins** [comment]
Yup! Again, we'd love to see someone publish that as a plugin :)

**Comment by JakePayton** [comment]
I think @dtrenz is probably out, but i'd be willing to take this

**Comment by dtrenz** [comment]
Thanks @JakePayton!

**Comment by mdiiorio** [comment]
I've got an implementation of this we've been using internally for a week or so. What's the best way to publish it? Create a github project and ping the cocoapods-plugins project?

**Comment by orta** [comment]
:+1: sounds like a good idea

**Comment by mdiiorio** [comment]
I just submitted https://github.com/CocoaPods/cocoapods-plugins/issues/64 to publish this as a plugin.

**Comment by segiddins** [comment]
Closing because https://github.com/square/cocoapods-check exists!

**Comment by dtrenz** [comment]
Oh, nice!
