### ISSUE TITLE
pod install crash in Xcode 7.0 beta 2

### ISSUE THREAD

**Issue by evgenyneu** [CocoaPods/CocoaPods#3723]
## How to reproduce

1. Install Xcode 7 beta 2.
1. Switch command line tools to `Xcode 7.0 (7A121l)` from Xcode -> Preferences -> Locations.
1. Create a new single page iOS app
1. Create a Podfile with following content:

```
use_frameworks!
pod 'Dodo', '~> 2.0'
```

Finally, run `pod install`.

Here is the error that I am getting

```
$ pod install
Analyzing dependencies
Downloading dependencies
Using Dodo (2.0.2)
Generating Pods project
2015-06-24 14:00:06.116 ruby[67792:374765] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8123.33/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fcaae958990>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x0000000101ae4047 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x0000000101ae37d4 _DVTAssertionHandler (in DVTFoundation)
  2  0x0000000101ae3a40 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x0000000101ae39a2 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x00000001037bf1a9 IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x00000001076d5a5d +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x00000001076d75e2 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff8e8c4f44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6
```

## Works in Beta 1

The `pod install` work in Xcode 7.0 Beta 1 (7A120f).

**Comment by segiddins** [comment]
I'll make a PR with a fix for this in a minute. I've already filed the relevant radar (there seems to be a missing plugin that Xcode needs to work)

**Comment by ravero** [comment]
Having the same issue.

**Comment by chriseidhof** [comment]
@ravero as a workaround, do an `xcode-select` back to the non-beta version, then run your cocoapods commands, and then revert back to Xcode-beta

**Comment by ravero** [comment]
@chriseidhof thanks for your reply... The main issue is that OS X 10.11 Beta 2 doesn't allow running Xcode 6.
The workaround that I've applied was to download the xcodeproj repo branch with @segiddins fix, generate the gem and install it locally over the official release. It worked fine now.

**Comment by pepibumur** [comment]
I had a similar problem using the Beta of XCode, as @chriseidhof says, selecting the non-beta version and executing Pod install works.

**Comment by karthikkeyan** [comment]
i had a similar issue, i just run "sudo xcode-select -r" and then install pods.

**Comment by cybertk** [comment]
`sudo xcode-select -r` fixed the issue

**Comment by wrutkowski** [comment]
Same issue on Xcode 7 GM. Fixed by switching to Xcode 6.4 just for the install, but I think it should be reopened now.

**Comment by neonichu** [comment]
See #3829 — make sure you have a version of Xcodeproj where this is fixed installed.

**Comment by rockylive** [comment]
sudo xcode-select -r fixed the issue

**Comment by chrisvalford** [comment]
I'm having the same problem with the release version, and sudo Xcode-select -r hasn't worked

**Comment by mshhmzh** [comment]
@neonichu  thank you so mach.  I fixed this problem thouth "gem install xcodeproj -v 0.24.3"

**Comment by Zhxmzm** [comment]
The "gem install xcodeproj -v 0.24.3" does not help me.

**Comment by xujingbao** [comment]
@neonichu  I fixed this problem thouth "gem install xcodeproj -v 0.24.3"

**Comment by williamnoto** [comment]
worked for me as well after running that gem command.

**Comment by AndreyEgorovCSI** [comment]
"gem install xcodeproj -v 0.24.3" helped me with xCode 7, thanks.

**Comment by Kowaio** [comment]
Doing the following worked for me: 

>sudo gem uninstall cocoapods
sudo gem install cocoapods
pod install

**Comment by tenaz3** [comment]
Kowaio +1

**Comment by emergencyhug** [comment]
@Kowaio +1

**Comment by doodoori2** [comment]
@Kowaio :+1:

**Comment by chanimeison** [comment]
Doing the following worked for me:

    sudo gem uninstall cocoapods
    sudo gem install cocoapods
    pod install

PERFECT!!!

**Comment by mattiaskronberg** [comment]
@Kowaio +1

**Comment by pavel0712** [comment]
@Kowaio  +1

**Comment by almaskz** [comment]
Any other solutions? non of the above worked for me =((((

**Comment by skyefreeman** [comment]
@Kowaio +1

**Comment by ebohdas** [comment]
@Kowaio +1

**Comment by radiovisual** [comment]
@Kowaio :+1:

**Comment by wangyhzzz** [comment]
@Kowaio  +1

**Comment by almaskz** [comment]
FIXED, if anybody still wonders (mine was very specific): 
'pod --version' returned 0.37.2 (even after updating cocoa pods to 0.38.2) it would update but still for some reason use 0.37.2 for all pod commands
So what I did: 
1) run 'pod --verbose' to locate the 0.37.2, delete it manually
2) run 'gem list --local | grep cocoapods' to find all cocoa pods installed on machine
2.1) 'gem uninstall' everything returned by step2 
2.2) run 'gem list --local | grep cocoapods' just to make sure everything is deleted
3) '[sudo] gem uninstall cocoapods'
4) '[sudo] gem install cocoapods'

**Comment by jsooriah** [comment]
+1

**Comment by orta** [comment]
I'm locking this, we don't need a thread emailing the devs for every `+1` thanks, but thanks for the current solution @Kowaio
