### ISSUE TITLE
"Duplicate symbols" error when using subspecs as frameworks

### ISSUE THREAD

**Issue by lukasspiess** [CocoaPods/CocoaPods#3725]
We have recently switched the podspec for the HockeySDK to use seperate subspecs for seperate features. Unfortunately, users are [reporting issues](https://github.com/bitstadium/HockeySDK-iOS/issues/176) when using our podspec with CocoaPods' `use_frameworks!` option.

This is the error we're seeing:
```
ld: 15 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
And also some warnings like this one:
```
Warning: Multiple build commands for output file /Users/lukas/Library/Developer/Xcode/DerivedData/HockeySDK-Source-dcupmcrbboadpcgksamqrfeokycq/Build/Products/Debug-iphonesimulator/Pods-HockeySDK-Source/HockeySDK_Source.framework/Headers/BITHockeyBaseViewController.h
```

I created an example project which demonstrates the issue [here](https://github.com/lukasspiess/HockeySDK-Source-Example). I'd be awesome if anyone could help us out with a hint about what we're doing wrong in our podspec of if this might be an issue with CocoaPods itself. Thanks!

**Comment by orta** [comment]
You likely have multiple subspaces including the same file. This works fine in Xcode's static libs, but doesn't compile in frameworks. This should be fixed in master https://github.com/CocoaPods/Xcodeproj/pull/273, but to support older builds of CP I'd recommend trying to make the subspecs not overlap.

**Comment by lukasspiess** [comment]
Thanks @orta! I was able to fix the issue with this commit: https://github.com/bitstadium/HockeySDK-iOS/commit/d15e13143efe0339cc3b1c0ad96f60c65c64523f
Still great to see that this will be fixed in a future version of CP :)

**Comment by orta** [comment]
:+1:
