### ISSUE TITLE
Specifying module_map should automatically be on the public_header_files list

### ISSUE THREAD

**Issue by jafara** [CocoaPods/CocoaPods#3728]
If a `.podspec` includes a `module_map` it should be exposed as a public header.

`s.module_map = module.modulemap`

It only works if I set `s.public_header_files = Sources/**/*.{h,modulemap}`

**Comment by jafara** [comment]
Is this intended?

**Comment by segiddins** [comment]
@jafara can you please share an example project that reproduces whatever issue you're seeing?

**Comment by jafara** [comment]
I cannot provide a sample from our internal source but here's a project that consumes CocoaLumberjack which declares a module map, however, doing `@import CocoaLumberjack;` fails the build.'

https://www.zipshare.com/download/eyJhcmNoaXZlSWQiOiJmZGI2N2JlNi1hZDQyLTQ1MjgtODk5NS02Yzk4M2VjZjY1ZmUiLCJlbWFpbCI6ImxpOHJhc0Bob3RtYWlsLmNvbSJ9

**Comment by jafara** [comment]
Seems like the file must be named `module.modulemap` and also exposed as a public header for it to work.

**Comment by jafara** [comment]
What is the best way to link a project to use the module_map? Should this be automatically setup by Cocoapods when `pod install` executes?

**Comment by segiddins** [comment]
@jafara that's already done when you use `use_frameworks!` in your podfile.

**Comment by jafara** [comment]
Interesting, will try that. But would that work for iOS 7?

What about if you have a `.podspec` that depends on this `.podspec` instead?

**Comment by jafara** [comment]
Doesn't seem to work. Did you try the sample app? I know the link is a bit sketchy but I can just paste the `Podfile` here instead.

**Comment by jafara** [comment]
I can make it work with `use_frameworks!` for CocoaLumberjack, but not without it. Whats the best way if I dont use `use_frameworks!`?

**Comment by segiddins** [comment]
Custom module maps are only supported with frameworks.
