### ISSUE TITLE
CocoaPods with static and dynamic vendored_libaries, switched on use_frameworks!

### ISSUE THREAD

**Issue by perotinus** [CocoaPods/CocoaPods#3729]
I'm working on CocoaPods with vendored_libaries. Right now, those vendored_libraries are static, but we would like to distribute dynamic frameworks as well. Would it be feasible (and reasonable) to modify the Podspec language so that, depending on whether a Podfile has use_frameworks!, either the static vendored_library or the dynamic vendored_library is used?

It seems unfortunate to have to maintain two equivalent sets of pods, one with static libraries and one with dynamic libraries. I'm looking into whether we can create dynamic libraries from our static libraries with some magical Podspec configuration, but I've run into some hiccups. We'll eventually want to do the more proper thing and package the libraries as dynamic libraries, but we don't want to drop support for the static versions of our libraries now.

**Comment by neonichu** [comment]
Choosing dynamic vs. static libraries doesn't have to be done based on integration strategy, it is rather a matter of deployment target, as dynamic libraries are not supported on iOS 7 and earlier.

Probably the best solution for bundling both types of libraries in one podspec would be subspecs. You could have a "dynamic" subspec which is default and a "static" subspec which can be optionally selected.

Also keep in mind that dynamic libraries aren't well supported in CP just yet, see #1993

**Comment by perotinus** [comment]
Seems reasonable. Thanks for your response, and sorry for my delay; I've been plugging away unsuccessfully at trying to dynamify our vendored pods.

Would having some sort of "default subspec" be a reasonable addition to CocoaPods? Say, a "_dynamic" subspec, a "_static" subspec (and, because it's coming soon, a "_bitcode" subspec)? Then, any vendored pod that wants to support these use cases can implement subspecs with these special names, and CocoaPods will automatically resolve the dependencies. Prefixing the names with _ or some other special prefix should hopefully avoid any confusion, and there could be a flag that enables this behavior.

I've spent a lot of time now trying to figure out how to make dynamic frameworks with vendored_libraries work without changes to CocoaPods, but there's too many variables to make it all work consistently with the tree of pods that we have to maintain. I really think that adding some provision to CocoaPods to make this easier is the only way I'll be able to have pods that support all our users.

I could use the deployment_target, but couldn't a podfile for an app targeting iOS 9 not have use_frameworks! ? A developer could choose not to use dynamic libraries, even though their deployment target supports them, so I'm not sure that the deployment target is a perfect indicator of whether or not a given pod is being integrated as a dynamic framework or a static library.

**Comment by segiddins** [comment]
Using dynamic vendored frameworks shouldn't be a problem even if the developer isn't using CocoaPods with `with_frameworks!`, _unless_ they for some reason need a static lib, such as if building a command line tool, where static linking is preferable. (Again, contingent upon https://github.com/CocoaPods/CocoaPods/issues/1993)

**Comment by perotinus** [comment]
Ah, cool! I'm looking forward to the day when we can move to shipping our own dynamic frameworks.

I think our immediate problem, though, is kind of the reverse: we have static libraries and want to support developers using ```use_frameworks!```. And, in the future, we'll want to support developers using bitcode, which will require us to somehow be able to switch which file developers are trying to link into their projects.

**Comment by segiddins** [comment]
You can always include bitcode in your static libs, there's no backwards compatibility issues there as far as I've seen so far.

**Comment by perotinus** [comment]
But doesn't that prevent us from also providing non-bitcode? There's no way in the Podspec language (that I can see) to have a vendored pod that provides both bitcode and non-bitcode vendored libraries.

**Comment by segiddins** [comment]
No, bit code is merely a segment to your static library -- it lives alongside architecture slices.

**Comment by perotinus** [comment]
Hmm. I'll look into that. I thought that static libraries that had bitcode and static libraries that didn't were mutually exclusive.

**Comment by perotinus** [comment]
How do you get bitcode and regular architecture slices to coexist in a static library?

I archived a static library twice, first with bitcode and then without, ending up with four .a files, armv7, arm64, bitcode_armv7, and bitcode_arm64. When I try to libtool them together into a static library, it warns me that:
```
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: warning for architecture: armv7 same member name (Test.o) in output file used for input files: armv7.a(Test.o) and: armv7_bc.a(Test.o) due to use of basename, truncation and blank padding
```

When I run ```file``` on the result, there are only two slices.

Of course, this is still Xcode beta, and Apple hasn't talked about bitcode that much, but it doesn't look like you can include bitcode and non-bitcode slices for the same symbols in the same static library.

**Comment by segiddins** [comment]
I think you can just use the version built with bitcode, since that also includes the non bitcode slice? But not sure

**Comment by segiddins** [comment]
Closing this as a wont fix.
