### ISSUE TITLE
Deduplicate pod targets across platforms if possible

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#3730]
##### Idea

After #3550, we could go one step further and remove the platform as a criteria preventing de-duplication of targets by generating [universal targets](https://github.com/mrackwitz/xcconfigs) if the same pod is used on multiple platforms. That could be interesting for different use cases, as e.g. shared frameworks between apps for iOS and watchOS, or between an iOS app and a OS X CLI tool to prepare seeds.

##### Difficulties

That's only possible as long as the podspec doesn't specify platform-specific values in any used subspec. This doesn't necessarily include the xcconfig attributes, as those could be assigned conditionally.

##### Tradeoff

It introduces complexity in CocoaPods _and_ in the integration to avoid duplication of generated configuration. Xcode scopes target products by default in platform-specific directories. The new `ModuleCache` is meanwhile platform independent. This means it doesn't actually reduce the number of required builds as #3550 did effectively, but it would have an impact on the build times as everything from the `ModuleCache` can be reused.

**Comment by neonichu** [comment]
I'm thinking this might be more trouble than it's worth. Especially relying on the shared `ModuleCache` to provide better build times seems bold, considering how often it gets screwed up even when just dealing with one platform.

It sounds like a cool thing to work on, though :)

**Comment by segiddins** [comment]
I agree this sounds like more trouble than it's worth

**Comment by neonichu** [comment]
Allright, since nothing has happened on this and most us thought it was too much trouble, I'm closing this. Feel free to reopen once you are working on it, @mrackwitz 😏

**Comment by mrackwitz** [comment]
Not worth the effort, podspecs can easily be defined that they can't be deduplicated across platforms and it would be just to much fighting against Xcode.
