### ISSUE TITLE
Empty resource bundle with Pod shipping a zip

### ISSUE THREAD

**Issue by lukasspiess** [CocoaPods/CocoaPods#3731]
We just recently switched our main Pod to shipping our static library binary as a zipped framework with an accompanying resource bundle, instead of direct source integration.
Now we are noticing that, for some reason, our resource bundle is not properly copied to the app bundle. It always has a size of zero bytes.
When the using the `use_frameworks!` option this even results in a compiler error:
```
/Users/lukas/Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-iphonesimulator/HockeySDKResources.bundle
building file list ... rsync: link_stat "/Users/lukas/Library/Developer/Xcode/DerivedData/CocoaPodsDebug-ObjC-ezfcljgqrmohurfoicwohygsuwff/Build/Products/Debug-iphonesimulator/HockeySDKResources.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

I created a [sample project](https://github.com/lukasspiess/CocoaPodsDebug-ObjC) that demonstrates the issue.Our current podspec can be found [here](https://github.com/bitstadium/HockeySDK-iOS/blob/a918cb9d0775fcef86b31735956028c05543cd65/HockeySDK.podspec).
Another interesting tidbit: Of a user upgrades from our previous version 3.6.4 to the new version 3.7.0 and doesn't do `clean build` in the meantime, everything continues to work.

**Comment by neonichu** [comment]
I think the issue is that you're referencing a non-existent path for your resources. 

The `Resources` directory is inside `HockeySDK-iOS/HockeySDK.embeddedframework`, not directly in the root <https://github.com/bitstadium/HockeySDK-iOS/blob/a918cb9d0775fcef86b31735956028c05543cd65/HockeySDK.podspec#L33>

**Comment by anlinde** [comment]
Thanks @neonichu  ! OH my goodness, what a fail, sorry for that.

Would it be possible for you guys to consider accepting the pull request at https://github.com/CocoaPods/Specs/pull/13210 to help us fix the bugs we introduced in our updated podspecs?

Would be great!

**Comment by orta** [comment]
looked good to me, merged.
