### ISSUE TITLE
Issues with `pod install` and `pod update` on El Capitan Beta 2

### ISSUE THREAD

**Issue by justinmakaila** [CocoaPods/CocoaPods#3732]
I recently updated to El Capitan Beta 2, and now I can't run `pod install` or `pod update`.

Here's my crash [log](https://gist.github.com/justinmakaila/fa8efc4a6700b318498f).

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/CocoaPods/commit/ef5f9a4fe0b5772909312ec31e994269e5e9a330

**Comment by justinmakaila** [comment]
How can I build that version?

**Comment by neonichu** [comment]
see <https://guides.cocoapods.org/using/a-gemfile.html#using-master-cocoapods> for a guide on using master

**Comment by justinmakaila** [comment]
I'm not familiar with `Gemfile`s in the slightest, so this was a bit of an adventure.

I installed `bundler, then created a `Gemfile` in an empty directory. I ran `bundle install`, and it looks like it all installed properly.

However, when I run `pod install`, I get the same output. I'm almost 90% sure I did something wrong with the `bundle install` play.

Can someone offer a bit more clarification?

```
$ pod --version
0.37.2
```

**Comment by segiddins** [comment]
`bundle exec pod install`?

**Comment by justinmakaila** [comment]
Where do I execute that? In the CocoaPods repo? In the empty dir with the modified `Gemfile`? In my project dir?

**Comment by esttorhe** [comment]
@justinmakaila put the `Gemfile` on the same folder where your `Podfile` is; then run

```console
bundle install
```

and then
```console
bundle exec pod install
```

**Comment by justinmakaila** [comment]
@esttorhe Thanks, that worked.

I'm now encountering a new issue!

```
$ bundle exec pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `Moya` from `https://github.com/ashfurrow/Moya.git`, branch `swift-2.0`
[!] Unable to find a specification for 'Moya'.

[!] Unable to load a podspec from `Moya.podspec`, skipping:

undefined method `validate_cocoapods_version' for #<Pod::Specification name="Moya">
```

**Comment by segiddins** [comment]
ah yeah, that would be happening. Anyways, that output would imply the underlying issue is fixed :)

**Comment by justinmakaila** [comment]
Agreed. Any insight as to why that's happening or what I can do to fix it?

**Comment by segiddins** [comment]
You can add the following to your Gemfile

```ruby
gem 'cocoapods-core', github: 'CocoaPods/Core'
```

**Comment by justinmakaila** [comment]
Great, that worked, and now Moya is downloading fine. Thanks!

**Comment by stuffmc** [comment]
Still need to install this way? No beta version of cocoapods for El Capitan?

**Comment by neonichu** [comment]
I don't think this issue was ever strictly related to El Capitan. Check out [this comment](https://github.com/CocoaPods/CocoaPods/issues/3692#issuecomment-113847612) for how to install on there.
