### ISSUE TITLE
Symlink - MacAppStore

### ISSUE THREAD

**Issue by valeIT** [CocoaPods/CocoaPods#3741]
Dear developer,

We have discovered one or more issues with your recent delivery for "ProRavel". To process your delivery, the following issues must be corrected:

Invalid Symlink - Your package contains a symbolic link 'com.me.ProRavel.pkg/Payload/ProRavel.app/Contents/Frameworks/Alamofire.framework/Headers' which resolves to a location 'com.me.ProRavel.pkg/Payload/ProRavel.app/Contents/Frameworks/Alamofire.framework/Versions/Current/Headers' that does not exist or is outside of the package.

Invalid Symlink - Your package contains a symbolic link 'com.me.ProRavel.pkg/Payload/ProRavel.app/Contents/Frameworks/Alamofire.framework/Modules' which resolves to a location 'com.me.ProRavel.pkg/Payload/ProRavel.app/Contents/Frameworks/Alamofire.framework/Versions/Current/Modules' that does not exist or is outside of the package.

Invalid Symlink - Your package contains a symbolic link 'com.me.ProRavel.pkg/Payload/ProRavel.app/Contents/Frameworks/SwiftyJSON.framework/Headers' which resolves to a location 'com.me.ProRavel.pkg/Payload/ProRavel.app/Contents/Frameworks/SwiftyJSON.framework/Versions/Current/Headers' that does not exist or is outside of the package.

Invalid Symlink - Your package contains a symbolic link 'com.me.ProRavel.pkg/Payload/ProRavel.app/Contents/Frameworks/SwiftyJSON.framework/Modules' which resolves to a location 'com.me.ProRavel.pkg/Payload/ProRavel.app/Contents/Frameworks/SwiftyJSON.framework/Versions/Current/Modules' that does not exist or is outside of the package.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team

---------------
I've never submitted an app to the MacAppStore before, so maybe I'm doing something wrong myself..?

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/CocoaPods/pull/3702!
