### ISSUE TITLE
DVTAssertion on pod install

### ISSUE THREAD

**Issue by pourhadi** [CocoaPods/CocoaPods#3742]
Whenever I run 'pod install', in any project, after upgrading to El Capitan Beta 2:

Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.5.4)
Installing ReactiveCocoa (2.5)
Installing TheAmazingAudioEngine (1.4.6)
Generating Pods project
2015-06-26 14:23:37.836 ruby[937:21035] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8123.33/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fd614f2caa0>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x0000000100d94047 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x0000000100d937d4 _DVTAssertionHandler (in DVTFoundation)
  2  0x0000000100d93a40 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x0000000100d939a2 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x000000010f8491a9 IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000011371ea5d +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x00000001137205e2 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff90174f14 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6

**Comment by segiddins** [comment]
Thanks for reporting this, but it's already bit fixed in Xcodeproj by https://github.com/CocoaPods/Xcodeproj/pull/275.

**Comment by pourhadi** [comment]
Thanks!
