### ISSUE TITLE
Updating to 0.38.0.beta.1 successfully, my version is still 0.37.2

### ISSUE THREAD

**Issue by dalu93** [CocoaPods/CocoaPods#3759]
Hi,
This is my problem
![schermata 2015-07-01 alle 14 57 07](https://cloud.githubusercontent.com/assets/9826047/8454965/7e4c189c-2001-11e5-9678-d3f3e0bcdd21.png)

How can I solve it? I tried also with `sudo gem uninstall cocoapods-0.38.0.beta.1` and installing again it but it didn't work

**Comment by neonichu** [comment]
This is a rubygems issue, see #3746
