### ISSUE TITLE
Trying to create a PR for not adding recursive folders

### ISSUE THREAD

**Issue by twoboxen** [CocoaPods/CocoaPods#3760]
Hello... so i'm trying to fork and write a PR for the ability to NOT add search paths for every header file.  That seems like a crazy use case to want recursive header paths for each dependency [issue #1437 ](https://github.com/CocoaPods/CocoaPods/issues/1437)

in headers_store.rb you have 

```
      def add_files(namespace, relative_header_paths, platform)
        add_search_path(namespace, platform)
```

I commented out the "add_search_path" and it works great.  I wanted to add an option to disable search paths for header files, but I can't figure out how to make it have something like:

```
      def add_files(namespace, relative_header_paths, platform)
        add_search_path(namespace, platform) if spec_options.add_header_dirs_to_search_path
```

We are quite blocked and for now are just commenting this out.  I know others are suffering from this issue and I believe it's pretty easy to fix if you know the codebase.  Can anyone help me??

**Comment by segiddins** [comment]
what would "an option to disable search paths for header files" do?

**Comment by twoboxen** [comment]
Right now folders are added recursively for each subdirectory if
preserve_paths is set (which many frameworks, such as j2objc, need).  They
require something like java/util/Time.h.  So if you preserve the paths,
cocoapods automatically adds each subdirectory to the include path.

Currently adding that one header would add:

Pods/J2ObjC
Pods/J2ObjC/java
Pods/J2ObjC/java/util

which can have bad side effects... say if you have a file named the same as
a system include file (j2ObjC has several of these... time.h is a bad
offender).  This means that any other library that includes <time.h> will
get the j2ObjC one instead of the system time.h that they wanted.  The
header search paths had been polluted.

To fix this you really want to be able to only have Pods/J2ObjC added to
the header search paths and still preserve the folder structure of your
headers.  Commenting that line out does fix it, but it should be an opt-in
option so existing code isn't affected.

Hope this helps!

**Comment by segiddins** [comment]
I think we're agreeing to get rid of the recursive addition of the search paths, full stop?

**Comment by twoboxen** [comment]
That would suffice for sure. This was a workaround to make it an option,
but recursive paths should never be used IMO

**Comment by segiddins** [comment]
Agreed

**Comment by jcanizales** [comment]
> I think we're agreeing to get rid of the recursive addition of the search paths, full stop?

OMG yes. Although that's bound to break some people right?

**Comment by segiddins** [comment]
@jcanizales maybe, but at this point it's a choice between breaking people relying on weird behavior, and breaking people who are doing everything right.

**Comment by segiddins** [comment]
@twoboxen did you ever get to a point where you could make a PR for this?

**Comment by twoboxen** [comment]
We have been using a locally patched version, but here is a PR:
https://github.com/CocoaPods/CocoaPods/pull/4042
