### ISSUE TITLE
Generated 'Copy Pods Resources' script contains invalid paths

### ISSUE THREAD

**Issue by vfn** [CocoaPods/CocoaPods#3761]
🌈Copied the name of issue https://github.com/CocoaPods/CocoaPods/issues/3082 since the bug didn't go away as the path is still incorrect.

Pods such as HockeySDK describing resource bundles cause the generated script Pods-resources.sh to contain statements such as the following:
```bash
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource '${BUILT_PRODUCTS_DIR}/HockeySDKResources.bundle'
fi
```

Resulting in the error below:

```bash
[redacted]
Build/Products/Debug-iphoneos/HockeySDKResources.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

**PODS_FRAMEWORK_BUILD_PATH** should be used instead of **BUILT_PRODUCTS_DIR** and the later doesn't contain the **/Pods** folder in the path

The proposed solution should result in the code below that when expanded will point to the correct directory
```bash
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource '${PODS_FRAMEWORK_BUILD_PATH}/HockeySDKResources.bundle'
fi
```

**Comment by segiddins** [comment]
So, `${PODS_FRAMEWORK_BUILD_PATH}` is only defined when building a pod with frameworks -- does that mean you're only seeing the issue when using frameworks, @vfn?

**Comment by segiddins** [comment]
(\c @mrackwitz)

**Comment by vfn** [comment]
@segiddins that's correct. I'll be creating a PR with the fix. Can you point me to a pod without frameworks that has resources?

**Comment by vfn** [comment]
@segiddins what would be preferable ** PODS_FRAMEWORK_BUILD_PATH** or ** BUILT_PRODUCTS_DIR/Pods**?

**Comment by segiddins** [comment]
That's up to @mrackwitz

**Comment by vfn** [comment]
@segiddins @mrackwitz It looks like on current master there is no more the **Pods** folder. Everything is copied to the ** BUILT_PRODUCTS_DIR**. Was it done deliberately?

**Comment by vfn** [comment]
https://github.com/vfn/CocoaPods/commit/8374a9cc02d432cf2edb5338540bb41a9c4c68ea

**Comment by neonichu** [comment]
Yes, it is deliberate that there is no Pods folder anymore.

**Comment by mrackwitz** [comment]
It was done by #3550. To elaborate: That means there still can be a `Pods(-[A-Za-z_])` folder, but it doesn't always exist, only when a pod's generated target has to be `scoped?`, which means that it can't be reused across two targets because they use either different platforms or different subspec sets.

**Comment by vfn** [comment]
For people experiencing the issue described by this ticket a temporary solutions is to add a post install hook to your Podfile, to band-aid the path, until a new version of CocoaPods is released with the fix

```ruby
post_install do |installer_representation|
    workDir = Dir.pwd
    resourceCopyScriptPath = "#{workDir}/Pods/Target Support Files/Pods/Pods-resources.sh"
    resourceCopyScript = File.read(resourceCopyScriptPath)
    
    originalPath = 'install_resource "${BUILT_PRODUCTS_DIR}/HockeySDKResources.bundle"'
    newPath = 'install_resource "${BUILT_PRODUCTS_DIR}/Pods/HockeySDKResources.bundle"'
    resourceCopyScript.gsub! originalPath, newPath
    
    File.open(resourceCopyScriptPath, "w") { |file| file << resourceCopyScript}
end
```

**Comment by vfn** [comment]
@mrackwitz fixed code based on your comments https://github.com/vfn/CocoaPods/commit/8374a9cc02d432cf2edb5338540bb41a9c4c68ea

Although that code works when applied on tag `0.37.2` it makes the build fail if applied to master. that's because at least on my scenario the `/Pods` folder is not created anymore and all the libs are dumped on `BUILT_PRODUCTS_DIR`

Can you point me to a pod that that would, as you said before, generate a `Pods(-[A-Za-z_])` folder so I can modify my code accordingly?

**Comment by segiddins** [comment]
This should be fixed on `master` now
