### ISSUE TITLE
Pods-Acknowledgements.plist doesn't build on 0.37.2

### ISSUE THREAD

**Issue by niklassaers** [CocoaPods/CocoaPods#3762]
Hi,

I just noticed that Pods-Acknowledgements.plist is missing from my newest project,

find Pods|grep -i Acknowledgements

gives me nothing.

My Podfile has no common pods, but two targets that each list their pods. Can that have anything to do with it?

Cheers

   Nik

**Comment by segiddins** [comment]
It should be in `Pods/Target Support Files/Pods`. If it's not, after running `pod install`, please share a project that reproduces the issue.

**Comment by niklassaers** [comment]
Thinking I had reproduced it nicely, I instead discovered why I didn't see it: I was expecting a Pods-Acknowledgements.plist file, but the file actually is a directory lower in Pods-<Target>/Pods-<Target>-acknowledgements.plist.

Sorry about the confusion, and I hope someone being as confused as me finds the answer here through Google ;-)
