### ISSUE TITLE
How would I setup my Podfile to set "Treat warnings as errors" to yes

### ISSUE THREAD

**Issue by szweier** [CocoaPods/CocoaPods#3765]
I'm trying to setup my workspace so that each project within it has "Treat warnings as errors" set to yes. I've set it in my other projects which works just fine, but a pod install will wipe out that setting in the Pods project. Is there a way I can have a pod install set that to yes each time?

**Comment by orta** [comment]
You could create a CocoaPods plugin that does this :+1: .

**Comment by szweier** [comment]
Thanks for the response.  I ended up going the post_install route.

```
post_install do |installer|
    installer.project.build_configurations.each do |config|
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = "YES"
    end
end
```
