### ISSUE TITLE
Development Pods Visible

### ISSUE THREAD

**Issue by ashfurrow** [CocoaPods/CocoaPods#3766]
Added in [this pull request](https://github.com/CocoaPods/CocoaPods/pull/3600), CocoaPods shares schemes of development pods. One side effect is that these schemes become shown in Xcode's dropdown list:

![screen shot 2015-07-02 at 3 54 34 pm](https://cloud.githubusercontent.com/assets/498212/8486559/5cf40c68-20d3-11e5-8160-f0b479f3544d.png)

Another side effect is that they can become [selected by default](https://github.com/orta/cocoapods-keys/issues/98) when changing branches of when doing a `pod install`. 

Xcode's UI presents an option to share a scheme without showing it in the Xcode dropdown list. Would it be possible to share these schemes while keeping them hidden? If so, would that use case interfere with use by non-CocoaPods users?

**Comment by segiddins** [comment]
@ashfurrow do you know how Xcode does hidden shared schemes?

**Comment by ashfurrow** [comment]
I don't – investigating now.

**Comment by ashfurrow** [comment]
Hmm. In the user data, I can hide things:

```xml
<key>Pods-KioskTests-Keys.xcscheme</key>
<dict>
	<key>isShown</key>
	<false/>
</dict>
```

But that's only my user data in `xcschememanagement.plist`. I've looked through and it's not apparent where this would be stored.

**Comment by segiddins** [comment]
In that case, I don't really know what we can do :/. I think it would be reasonable for Keys to hide its own schemes, since it relies on `pod install` being run each time, but otherwise...

**Comment by ashfurrow** [comment]
Yeah, I mean, it doesn't look like the scheme hiding/showing is based in the scheme file itself; it could be a user-specific setting. I dunno. Anyone we could ping to verify the hidden-ness of targets is per-user? 

If that's the case, we can close the issue and get cocoapods-keys to un-share the scheme.

**Comment by orta** [comment]
This existed to let people support Carthage via shared schemes and dev pods, for the moment that is too important to remove. We can, and will, fix this in keys.

**Comment by ashfurrow** [comment]
Sounds good. I'll try and submit a PR to keys this weekend.

**Comment by dtweston** [comment]
Did this PR happen? I'd love to find a way to solve this for my own projects.
