### ISSUE TITLE
Can't trunk push spec with pod_target_xcconfig

### ISSUE THREAD

**Issue by pixelglow** [CocoaPods/CocoaPods#3772]
I've added the `pod_target_xcconfig` setting to my podspec on CocoaPods 0.38.0.beta.1. It passes `pod lib lint` and `pod spec lint` but when I try to `pod trunk push`, it complains that:

```
[!] The Pod Specification did not pass validation.
The following validation failed:
- Warnings: Unrecognized `pod_target_xcconfig` key.
```

`pod trunk push --allow-warnings` doesn't work either.

Presumably the `trunk` web service is not updated to 0.38 yet? Any workarounds? This particular update is important to support iOS frameworks for [ZipZap](/pixelglow/ZipZap), including support for Swift.

See https://github.com/pixelglow/ZipZap/commit/0e4e6aa885196640ca86462c6748e68a50c66ee9

**Comment by segiddins** [comment]
Thanks for the reminder, @pixelglow , I'm deploying an update to trunk right now.
