### ISSUE TITLE
0.38.0.beta.1 "dyld: Symbol not found" error when using pod distributed as static library

### ISSUE THREAD

**Issue by dopcn** [CocoaPods/CocoaPods#3773]
🌈I updated to 0.38.0.beta.1 because 0.37.2 can't work with command line tool shipped with xcode7 beta 2 then I run across a "dyld: Symbol not found" error. This only occur when I included a pod distributed as a static library. I create a new project with that specific pod to demonstrate the problem you can download [here](https://github.com/dopcn/testPod)

This is what I get when clean-build-run
<img width="1280" alt="screen shot 2015-07-03 at 16 00 59" src="https://cloud.githubusercontent.com/assets/1253817/8495095/68ae6c4a-219d-11e5-8d95-b034a0eda390.png">

Here is the test project overview
<img width="1280" alt="screen shot 2015-07-03 at 16 20 39" src="https://cloud.githubusercontent.com/assets/1253817/8495378/d24ae2e4-219f-11e5-91f4-b8aa03325f4e.png">

More weird thing is when I send this test project to another colleague. He can run it without any problem after `pod update`.  His cocoapods version is 0.37.1 and xcode6. But when I change back to 0.37.2 xcode6 and xcode-select -p /Applications/Xcode.app/Contents/Developer the same problem is still there.

Is 0.38 beta change some Xcode setting? or something about xcode7 beta?

Thanks in advance

one more thing this "dyld: Symbol not found" error only occur when run on simulator

**Comment by neonichu** [comment]
I couldn't actually reproduce your issue, because for me, 0.38 beta 1 doesn't even symlink the headers of AWOSCloud and AVOSCloudSNS correctly, so the build breaks much earlier. The symlinking issue is also still present in master.

**Comment by neonichu** [comment]
BTW, you can keep using 0.37.2 if you update xcodeproj to 0.24.3

**Comment by dopcn** [comment]
@neonichu Thanks for your reply

**Comment by neonichu** [comment]
Reopening this, because the actual issue is still present.

**Comment by segiddins** [comment]
@neonichu any clue what the underlying issue is?

**Comment by neonichu** [comment]
@segiddins not yet, got tangled up in other things

**Comment by ItsTipTop** [comment]
Same here
 <code>dyld: Symbol not found: _VKActivityTypePost
  Referenced from: /private/var/mobile/Containers/Bundle/Application/FB0F7CCE-1DD2-4A33-B1DE-7CD4F96AC5B7/MYAPP.app/MYAPP
  Expected in: /private/var/mobile/Containers/Bundle/Application/FB0F7CCE-1DD2-4A33-B1DE-7CD4F96AC5B7/MYAPP.app/Frameworks/VK_ios_sdk.framework/VK_ios_sdk
 in /private/var/mobile/Containers/Bundle/Application/FB0F7CCE-1DD2-4A33-B1DE-7CD4F96AC5B7/MYAPP.app/MYAPP</code>

**Comment by shams-ahmed** [comment]
same as above comment... does anyone have a workaround? 

```
dyld: Symbol not found: _OBJC_CLASS_$_PFProduct
  Referenced from: /Users/shamsahmed/git/[HIDDEN]/[HIDDEN]Build/Products/Debug-iphonesimulator/ParseUI.framework/ParseUI
  Expected in: flat namespace
 in /Users/shamsahmed/git/[HIDDEN]/[HIDDEN]/Build/Products/Debug-iphonesimulator/ParseUI.framework/ParseUI
```

if you need any other info me know...

**Comment by mrsweaters** [comment]
I'm having similar issues since upgrading:

```
dyld: Symbol not found: __TWPu0_Rq_Ss13GeneratorType_GVSs20MapSequenceGeneratorq_q0__S_Ss
  Referenced from: /private/var/mobile/Containers/Bundle/Application/A521FC32-3BE3-4D8C-9B5D-D80B895372ED/Notable.app/Frameworks/Alamofire.framework/Alamofire
  Expected in: /private/var/mobile/Containers/Bundle/Application/A521FC32-3BE3-4D8C-9B5D-D80B895372ED/Notable.app/Frameworks/libswiftCore.dylib
 in /private/var/mobile/Containers/Bundle/Application/A521FC32-3BE3-4D8C-9B5D-D80B895372ED/Notable.app/Frameworks/Alamofire.framework/Alamofire
```

**Comment by mrsweaters** [comment]
Downgrading to `0.37.2` fixed the issue.

**Comment by nlutsenko** [comment]
Fabulous, I was able to track down the issue happening with AVOSCloud and our Parse podspecs.
Both AVOSCloud and us distribute pod as a static library + empty source file, to be able to support both static and dynamic frameworks via pre-compiled static library.

`0.37.2` was also adding `-ObjC` linker flag to the specific pod framework target
`0.38.2` - that flag is gone, which gets us into the state, where the static library is not linked to the dynamic pod framework at all, since no symbols are referenced from it. Crazy right?

Temporary fix I was able to come up with is to have at least one source file inside the pod that references at least one symbol from the pod. Maybe we can add a linker flag to the pod framework target, though didn't try it yet.

@segiddins @neonichu Not sure about the reasons on why '-ObjC' flag is gone from the pod framework targets... Would love to help out with further tracking of the issue and fixing it.

**Comment by nlutsenko** [comment]
Further investigation got me to #3537 and implementation in #3757 which apparently removes `-ObjC` flag if there is no need for it, but both of the pods referenced above ^^ actually have `vendored_library` :(

Best solution I was able to come up with: `spec.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC' }`

**Comment by segiddins** [comment]
Yeah, it should still be added if there's a static lib. Would either of you be willing to make a PR fixing CocoaPods so `-ObjC` is still added if there any any vendored libraries?

**Comment by nlutsenko** [comment]
Be willing - absolutely. Have capacity - not sure. Will try my best.

**Comment by segiddins** [comment]
`-ObjC` is now added when needed

**Comment by nlutsenko** [comment]
Perfect, thank you, kind sir!

**Comment by keith** [comment]
Still seeing this issue with `Appboy-iOS-SDK`. `-ObjC` is not added to the flags so we get these errors at compile time. Adding them fixes it.

**Comment by keith** [comment]
We're able to fix this locally with this in our Podfile:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Appboy-iOS-SDK"
        config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
      end
    end
  end
end
```

**Comment by segiddins** [comment]
Ah so the issue is with the pod target in your case, @keith -- a slightly different issue

**Comment by keith** [comment]
:+1: is there an open issue for this somewhere?

**Comment by dopcn** [comment]
Updated to 0.38.2 this issue no longer exist. closed

**Comment by keith** [comment]
@segiddins is there an issue for the other case? This is still an issue with 0.39 beta 4.

**Comment by segiddins** [comment]
@keith no idea.
