### ISSUE TITLE
HEADER_SEARCH_PATHS build config not set sometimes

### ISSUE THREAD

**Issue by mwaterfall** [CocoaPods/CocoaPods#3774]
In my current project I have noticed that `HEADER_SEARCH_PATHS` is not set in the `Pods.debug.xcconfig` build configuration, which is causing import issues in my Obj-C bridging header (in my Swift project). 

I created a new project and used the same pods in the new podfile and this project has `HEADER_SEARCH_PATHS` set correctly for each pod:

```
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/MWPhotoBrowser"
```

I wiped the pods from my existing project and re-installed but still no header search paths. Why is this sometimes not set? 

Using Cocoapods 0.37.2.

**Comment by segiddins** [comment]
@mwaterfall using bridging headers for frameworks doesn't really work -- you should instead just `import` the modules you're using.

**Comment by mwaterfall** [comment]
Thanks @segiddins, yes I was confused for a while there. 

Swift's `import` wasn't working as my pod library framework it was failing to be built as an Obj-C module. I resolved this by properly importing headers from other pods that my library depends on. I.e.:

```obj-c
#import <MBProgressHUD/MBProgressHUD.h>
```
instead of 
```obj-c
#import "MBProgressHUD.h"
```

Hope this helps anyone else who stumbles upon the same problem.
