### ISSUE TITLE
Tests not being correctly recognized for Xcode 7

### ISSUE THREAD

**Issue by joemasilotti** [CocoaPods/CocoaPods#3776]
🌈I'm building [some helpers](https://github.com/joemasilotti/JAMTestHelper.git) for UI Testing in Xcode 7 and just pushed v0.0.1 to the trunk. The pod is tested with XCTest and uses the normal XCTAssert* macros. However, on cocoapods.org the [page notes that the pod does not include any tests](https://cocoapods.org/pods/JAMTestHelper).

**Comment by segiddins** [comment]
This belongs over on https://github.com/CocoaPods/cocoadocs.org, since it's that repo that generates the testing stats -- I believe it's implemented in the testing idealist?

**Comment by joemasilotti** [comment]
Gotcha. Just opened the issue over there. I'm going to close this one. Thanks!
