### ISSUE TITLE
Loading assets from resource bundle (when used as static lib or framework)

### ISSUE THREAD

**Issue by mwaterfall** [CocoaPods/CocoaPods#3779]
I've been playing with the default lib template workspace and I'm migrating a pod of mine towards it. I have a question about loading assets from the resource bundle.

My pod supports iOS <= 8 so it needs to support being added to a project as a framework or a static library. Hence there's two different locations where the generated resource bundle could reside.

My resources are defined like this:

```ruby
s.resource_bundles = {
  'MyLib' => ['Pod/Assets/*.png']
}
```

Is this then the recommended way to load assets, by performing those checks? Or is there a neater way?

```obj-c
// Attempt to load asset from resource bundle inside main app's bundle
UIImage *asset = [UIImage imageNamed:@"MyLib.bundle/Icon.png"];
if (asset == nil) {
    // Not found so attempt to load from resource bundle in the pod framework
    asset = [UIImage imageNamed:@"Frameworks/MyLib.framework/MyLib.bundle/Icon.png"];
}
```

**Comment by neonichu** [comment]
The right way is to utilise `NSBundle.bundleForClass()` to determine the correct bundle resources for a specific class reside in.

**Comment by mwaterfall** [comment]
Ah, for some reason it wasn't working previously but this does seem to work:

```objc
NSBundle *bundle = [NSBundle bundleForClass:[self class]];
NSString *assetPath = [bundle pathForResource:@"MyLib.bundle/Icon" ofType:@"png"];
UIImage *asset = [UIImage imageWithContentsOfFile:assetPath];
```
Cheers!
