### ISSUE TITLE
Copy to clipboard button disappears when viewing pod details

### ISSUE THREAD

**Issue by hk0i** [CocoaPods/CocoaPods#3781]
# Issue
I find the copy button extremely useful. It might be nitpicking, but when I noticed its disappearance the other day I was a little frustrated that I had to go into the **Installation Instructions** and actually highlight, then copy.

# Repro
1. Search for a pod via cocoapods.org
2. List of pods appears, each with a clipboard copy icon
3. Click on the pod name to expand details
4. Copy button disappears

# Suggestion
Keep the copy button visible, preferably in the same spot. I actually spent more time looking around for that button to try to use it than I would have spent just going into the **Installation Instructions** screen and copying manually.

**Comment by segiddins** [comment]
The belongs on the CocoaPods.org repo.
