### ISSUE TITLE
0.38.0.beta.2 - wrong scheme created - `pod package` fails

### ISSUE THREAD

**Issue by xslim** [CocoaPods/CocoaPods#3782]
I don't know if this was already reported, can't find similar issues
- Install latest `cocoapods-packager`
- Use `0.38.0.beta.2`
- `pod package MyLib.podspec` fails - the scheme `Pods-MyLib` not found, so no `libPods-MyLib.a` is created

With `cocoapods-0.37.2` and earlier - all works well.

PS: with `0.38.0.beta.2` instead of `Pods-MyLib` scheme, `MyLib` scheme is created

**Comment by segiddins** [comment]
This is an issue with the packager, but I believe it's been fixed over there on master.

**Comment by xslim** [comment]
This is still the issue. please re-open

**Comment by segiddins** [comment]
Again, this would be an issue with the packager, not with CocoaPods proper.
