### ISSUE TITLE
Can't build pod when using use_frameworks!

### ISSUE THREAD

**Issue by rvi** [CocoaPods/CocoaPods#3783]
May be related to : #3654 

Here is my podfile : 
```
platform :ios, '8.1'
inhibit_all_warnings!
use_frameworks!

pod 'msgpack'
```

If I remove `use_frameworks!` everhything works well, but with it, it can't build. I've got several errors on preprocessor macros from msgpack saying that they're not defined.

I'm stuck, I don't know how to fix it.

Any help is appreciated, Thanks.

**Comment by neonichu** [comment]
If I build the example of https://github.com/rvi/msgpack-objective-C with `use_frameworks!`, it seems to work fine. Could you please elaborate on the errors you are receiving or provide an example? Also please retry with 0.38 beta 2 if you didn't already.

**Comment by rvi** [comment]
Thanks for your help.

No it's still not working even with the latest beta.

You can see a sample project here : https://github.com/rvi/msgPackSwift

I tested [MsgPackSerialization](https://github.com/mattt/MsgPackSerialization), and I've got the same problem with `use_frameworks!`.

Here is the kind of errors I've got : 
<img width="255" alt="screen shot 2015-07-06 at 17 31 24" src="https://cloud.githubusercontent.com/assets/1455122/8526198/729bcd82-2405-11e5-98d1-0481a5de6714.png">

**Comment by neonichu** [comment]
The msgpack Pod will have to be updated to work as a framework. 

Issues include:
- The 'unpack_template.h' header doesn't look like as if it should be a public header
- It uses zlib for which Apple does not ship a module map, that needs to be provided by the Pod

Please report this upstream.

**Comment by rvi** [comment]
Thanks. Is it normal that `pod lib lint` succeed ?

**Comment by neonichu** [comment]
It's unfortunately normal, because `lint` only builds the framework and does not try to import it. There is an existing issue to improve this.

**Comment by rvi** [comment]
Thanks, I fixed the pod msgpack !

**Comment by neonichu** [comment]
great :tada:
