### ISSUE TITLE
Can't seem to build a static library pod

### ISSUE THREAD

**Issue by klattimer** [CocoaPods/CocoaPods#3784]
I'm having a curious problem when trying to build a simple category into a static library, make it a pod and re-use it. 

I've used this tutorial to create the project 
http://blog.sigmapoint.pl/developing-static-library-for-ios-with-cocoapods/

However when I run 
pod lib lint TestLibrary.podspec --verbose

My output ends with this. Which doesn't seem right at all, the library builds fine, the tests run fine in xcode the code is certainly usable but it tells me that the linker has exited with an error. If you could point me at how to debug this issue I'd be very grateful.

** BUILD SUCCEEDED **

 -> TestLibrary (0.0.1)
    - ERROR | [OSX] Returned an unsuccessful exit code.
    - NOTE  | [OSX]  clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by neonichu** [comment]
Could you please share the full verbose output with us?

**Comment by klattimer** [comment]
Never mind, I was using s.ios.library instead of s.library.
