### ISSUE TITLE
[Feature] Automatically generate accessors for Resource Bundles

### ISSUE THREAD

**Issue by AnthonyMDev** [CocoaPods/CocoaPods#3786]
It would really convenient to have an easy way to access the resource bundles for a pod that is generated automatically from the pod spec. I've seen a lot of people have trouble using resource bundles correctly. The additions to the documentation discussed in CocoaPods/guides.cocoapods.org#18 are really helpful, but it would be nice to have these automatically generated.

I'm thinking that this could be done as global computed properties in the umbrella header?

Does this seem doable?

**Comment by segiddins** [comment]
@AnthonyMDev sounds like a overreach, to be perfectly honest -- we prefer to stay away from codegen whenever possible, since it's just a world of hurt.

**Comment by AnthonyMDev** [comment]
That's fair. I've just noticed a lot of troubles with grabbing my resources and the same issues with other people.

**Comment by orta** [comment]
You could make a CocoaPods plugin for this though! We need a label "Should be a plugin."

**Comment by segiddins** [comment]
@orta such a think belongs on the cocoapods-plugins repo, not here.

**Comment by AnthonyMDev** [comment]
@orta That makes sense. I would be willing to make a plugin if I could, but I have zero experience with ruby at the moment...
