### ISSUE TITLE
0.38.0.beta.2 cannot lint PromiseKit.podspec

### ISSUE THREAD

**Issue by mxcl** [CocoaPods/CocoaPods#3787]
🌈

I'm sorry I have cleared my terminal and lost the error message (I'd re-run it but linting PromiseKit takes ~30 minutes), but it was to do with the CloudKit subspec, which is famous because:

* it has an OS X deployment target of 10.10
* **but** PromiseKit’s root spec has an OS X deployment target of 10.9

https://github.com/mxcl/PromiseKit/blob/master/PromiseKit.podspec

Possibly this is my fault because I am running **El Capitan beta 2** and I have Xcode 7 beta 2 installed. However my command line tools are the Xcode 6.4 set.

I was able to lint and push (PromiseKit 2.1.0) after downgrading to 0.37.2.

**Comment by segiddins** [comment]
Can you try just listing the given subspec that's failing?

**Comment by mxcl** [comment]
That works, though I'm not sure that helps since my hypothesis was it's the conflict between the root spec and the subspec.

I finished pushing the new version so I can do a full lint later this evening and post the output again.

**Comment by segiddins** [comment]
```
 -> PromiseKit (2.1.0)
    - WARN  | There was a problem validating the URL http://promisekit.org.
    - WARN  | There was a problem validating the URL http://promisekit.org/introduction/.

[!] PromiseKit did not pass validation, due to 2 warnings (but you can use `--allow-warnings` to ignore them).
You can use the `--no-clean` option to inspect any issue.
```

**Comment by mxcl** [comment]
Probably my setup then. Apologies.
