### ISSUE TITLE
Implicit pod dependencies for static library not built in Xcode 6.4 (6E35b)

### ISSUE THREAD

**Issue by rubnov** [CocoaPods/CocoaPods#3789]
Using Xcode 6.4 (6E35b), linking pods with a static library fails with libtool errors. 

Podfile:

    target 'MyApp' do
        pod 'CocoaAsyncSocket', '~> 7.4.1'
        pod 'SSZipArchive'
        pod 'Fabric'
        pod 'Fabric/Crashlytics'
    end

    target 'staticLib' do
        pod 'AFNetworking', '~> 2.5'
        pod 'CocoaLumberjack', '~> 2.0'
    end 

When building target ```MyApp```, I get the following errors: 

    warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified, -all_load invalid
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified the following flags are invalid: -ObjC -ObjC 
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-staticLib-AFNetworking
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-staticLib-AFNetworking is not an object file (not allowed in a library)
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-staticLib-CocoaLumberjack
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-staticLib-CocoaLumberjack is not an object file (not allowed in a library)
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-staticLib
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-staticLib is not an object file (not allowed in a library)

```-lPods-staticLib-AFNetworking```, ```-lPods-staticLib-CocoaLumberjack``` are not built at all. Xcode does not detect these implicit dependencies. Is there a workaround for this?

**Comment by samdmarshall** [comment]
Is there a sample project you can upload that exhibits this behavior?

**Comment by segiddins** [comment]
Closing due to lack of a sample project.
