### ISSUE TITLE
Adding GCC_PREPROCESSOR_DEFINITIONS on pods targets after 0.38.0.beta.x install

### ISSUE THREAD

**Issue by dalu93** [CocoaPods/CocoaPods#3790]
Hi,
On 0.37.2 and before I was using this post_install code to define a preprocessor_macro on a specific pods target:

    post_install do |installer_representation|
        installer_representation.project.targets.each do |target|
            if target.name === 'Pods-LIB_NAME-ORIGIN_TARGET_NAME'
    		    target.build_configurations.each do |config|
      			    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) APP_STORE_RELEASE=1'
                end
            end
            if target.name === 'Pods-LIB_NAME-ORIGIN_TARGET_NAME'
                target.build_configurations.each do |config|
                    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) IS_BETA=1'
                end
            end
        end
      end

Now I edited this code with the one below:

    post_install do |installer_representation|
        installer_representation.pods_project.targets.each do |target|
            if target.name === 'Pods-ORIGIN_TARGET_NAME'
    	    	target.build_configurations.each do |config|
      	    		config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) APP_STORE_RELEASE=1'
                end
            end
            if target.name === 'Pods-ORIGIN_TARGET_NAME'
                target.build_configurations.each do |config|
                    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) IS_BETA=1'
                end
            end
        end
    end

But now this is not working how was expecting. This is because I'm not setting a macro to the lib, so it can't read it from the "master" pod target. I would like to define a macro for the single pods target that is used on a different origin-project target. If I choose the Beta target on the master project, I would like to find a macro IS_BETA on the lib I link with it. How can I achieve this solution? thanks

**Comment by dalu93** [comment]
I solved defining this `deduplicate_targets: false` in the `config.yaml` file. This is something that will be deleted on future cocoa pods versions? Because I really need it.

**Comment by neonichu** [comment]
The target names changed with 0.38, that's why your `if` statement is never true anymore. Please have a look at your actual Pods project to see the new target names.

**Comment by dalu93** [comment]
Below is the actual targets tree

    -Pods-PROJECT_TARGET_NAME ---> libName
    -Pods-PROJECT_TARGET_NAME ---> libName

Before the tree was

    -Pods-PROJECT_TARGET_NAME1-libName
    -Pods-PROJECT_TARGET_NAME2-libName
    -Pods-PROJECT_TARGET_NAME3-libName

So, if in the Podfile I will modify the PREPROCESSOR for the `libName`, I will set the macro on all the targets. This is the problem I'm having. But I solved it using this flag on the configuration file.
