### ISSUE TITLE
Readme.md not picked up for projects without a git repo

### ISSUE THREAD

**Issue by slavasav** [CocoaPods/CocoaPods#3791]
There should be a way to specify a path to the Readme.md file in the podspec for projects that don't specify a git repo (I suppose Readme.md is only picked up from git?).

**Comment by orta** [comment]
It takes it from the opened & downloaded file from the Podspec, so if one is included in a .zip - I'm pretty sure CocoaDocs will pick it up. If this isn't the case it's definitely a bug and can you raise an issue with an example on [CocoaDocs](https://github.com/CocoaPods/cocoadocs.org)
