### ISSUE TITLE
Change a uploaded podspec because of some dependency errors

### ISSUE THREAD

**Issue by mRs-** [CocoaPods/CocoaPods#3793]
I have messed up and the internet is hating me now ;)

I would like to change some podspec of my trunk of my current version or remove this version completely. Is there a way to make this possible?

**Comment by orta** [comment]
If it's minor changes you can make a PR to the [Specs](https://github.com/CocoaPods/Specs/) repo, but really you should be making a patch release for it, and pushing that up to trunk.

**Comment by mRs-** [comment]
sound's fair enough ;)
