### ISSUE TITLE
Unable to find specification for ...

### ISSUE THREAD

**Issue by klattimer** [CocoaPods/CocoaPods#3799]
I've created my own pod repo and added a bunch of pods to it however I can't seem to install those pods into a project with pod install,

if I run 

pod search PODNAME 

I get the pod spec coming up, however pod install results in 

Unable to find specification for PODNAME

Any ideas what I could have done wrong?

**Comment by segiddins** [comment]
You need to specify the `source` in your podfile, see https://guides.cocoapods.org/syntax/podfile.html#source.

**Comment by klattimer** [comment]
I thought that would have already been configured at a system level?

**Comment by segiddins** [comment]
Nope, the sources used for dependency resolution are per-podfile.
