### ISSUE TITLE
Are there file sync function for private repo?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3801]
I found the specs repo is too large, and the git history is too long!!! So I have to cast much time to wait `git pull` complete.

I think we don't care about the spec history. So I hope that I can keep specs latest over file sync in my private repo, is it possible?

**Comment by segiddins** [comment]
We already use shallow cloning on the master specs repo, which discards the git history.

**Comment by Whirlwind** [comment]
In my private repo, I found it will be clone as a complete git repo:
```
pod install --verbose
  Preparing

Analyzing dependencies

Updating spec repositories
Updating spec repo `company-specs`
  $ /usr/local/bin/git pull --ff-only
  From gitlab.mycompany.com:git/specs
     1fc26d7..4d22c7d  master     -> origin/master
  Updating 1fc26d7..4d22c7d
  Fast-forward
.....
```

It is not a shadow clone, or it still pull all histories.

How to do it?

**Comment by segiddins** [comment]
`pod repo add --shallow`

**Comment by Whirlwind** [comment]
My repo is downloaded by the `Podfile`:
```
source 'git@mycompany.com:git/specs.git'
```
is It not a shadow clone?

**Comment by segiddins** [comment]
No. If you want a shallow clone, you'll need to add it manually.

**Comment by Whirlwind** [comment]
Can the CP support file system sync over HTTP?
