### ISSUE TITLE
Header search paths not respecting targets

### ISSUE THREAD

**Issue by jmejiaxogrp** [CocoaPods/CocoaPods#3805]
I have two targets in my project, the main app and the test target

I noticed that the test target gets the same header search paths as the main app, which should not be the case.

**Comment by segiddins** [comment]
@jmejiaxogrp can you please share the info requested in https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md ? This isn't a sufficient bug report to know what's wrong, if anything.

**Comment by jmejiaxogrp** [comment]
Apologize, I was actually meaning to not post as I searched and found similar issues..

This the same issue I am having on the latest and does not seem fixed:
https://github.com/CocoaPods/CocoaPods/issues/904

**Comment by neonichu** [comment]
It mentions #1249 as the canonical dupe.
