### ISSUE TITLE
Can I use the use_framework option on a single pod or does it have to be globally enabled?

### ISSUE THREAD

**Issue by hfossli** [CocoaPods/CocoaPods#3807]
This is the recommended way of dealing with one or more pod which got swift code:
```
platform :ios, '8.0'
use_frameworks!
```

Now this gives me some headache as some pods stop working properly. 

<img width="976" alt="screen shot 2015-07-10 at 12 39 50" src="https://cloud.githubusercontent.com/assets/3652587/8617103/ccd9f1ae-2700-11e5-8c3c-e1e5cf28c910.png">

I can create PR's for all pods which is not importing the frameworks correctly, but it will be quite time consuming.

It would instead be great to apply the `use_frameworks` flag to those pods which got swift code e.g.:

```
pod 'SomePod', :use_frameworks
```

But I guess my understanding of this is completely nonsense and my suggestion is no way possible...

**Comment by hfossli** [comment]
Also, where do I find a list of all possible flags and options for 
```
pod 'SomePod', ......
```
?

**Comment by orta** [comment]
You have to make all Pods work as frameworks alas. All docs can be found on the guides, the docs for `pod` are: https://guides.cocoapods.org/syntax/podfile.html#pod

**Comment by hfossli** [comment]
Thanks!

**Comment by dmathewwws** [comment]
@hfossli can i ask how you fixed this issue in your project?

I also have a pod (Realm) that needs use_frameworks! flag to be on, but have other pods that won't import the framework correctly

**Comment by hfossli** [comment]
Haven't fixed it yet. I'm considering replacing the one swift pod or using Carthage for it if there's no dependency problems.

**Comment by hfossli** [comment]
Spending time on metatasks like this sucks big time and feels like throwing money out the window to me. 

I think Carthage + Cocoapods should work as long as they don't have the same dependencies.

**Comment by dmathewwws** [comment]
Thanks @hfossli. I personally used Carthage to fix the issue. see: https://github.com/realm/realm-cocoa/issues/2141
