### ISSUE TITLE
Unable to find a specification for `monkey (< 1.0.9, ~> 1.0.1)` depended upon by BananaLib (1.0).

### ISSUE THREAD

**Issue by yoiang** [CocoaPods/CocoaPods#3809]
Quickly doing a search in the CocoaPods repo has monkey and BananaLib come up in what look like example Pod definitions. Where in the past I had no problem recently for whatever reason running `pod spec lint` on Travis CI as a Build Phase of a Target no longer works and instead dumps this error.

https://travis-ci.org/Adorkable/SegueingInfo/jobs/70437641

Let me know if I can provide any additional information!

**Comment by neonichu** [comment]
The problem doesn't seem to be CP, because running `pod spec lint` against a checkout of that repo works just fine. My assumption would be that through some accident in the CI setup, podspecs from the CP fixtures directory are ending of in your working directory when running lint.

**Comment by yoiang** [comment]
Sure, so is this something I should take up with Travis? Rather than relying on whatever automatic Travis provides I put in a forced `gem install cocoapods` and that fixed it. Oy, the frustration with the lack of insight into Travis when working with it. 

Thanks for your time @neonichu !

**Comment by neonichu** [comment]
@yoiang I'm sure Travis would like to know about it.
