### ISSUE TITLE
Trying to add reachability to a library project Reachability.h file not found

### ISSUE THREAD

**Issue by klattimer** [CocoaPods/CocoaPods#3812]
I've been through the header not found troubleshooting notes here:
https://guides.cocoapods.org/using/troubleshooting.html

Everything seems fine. 

I have a unit test which builds and executes correctly using Reachability and I'm including reachability into my project like so:

#import \<Reachability/Reachability.h\>

I've got two targets set up in my podfile which are both simply pointing to the class and the class's test cases. Both with pod Reachability specified.

I'm not entirely sure how to proceed, all of the advice I can find online seems to point at the same issues which I've already been sure to resolve. (header search paths, target configuration etc...)

**Comment by klattimer** [comment]
To be clear I get header not found when running pod lib lint ONLY. Tests run fine.

I actually have the same problem in two separate pods, and was hoping to solve it here first.

**Comment by neonichu** [comment]
`pod lib lint` uses `use_frameworks!` by default, your tests probably don't.

**Comment by klattimer** [comment]
any way to fix this?

**Comment by neonichu** [comment]
Hard to say, are you able to share more information? Like the podspec, example project, etc?

**Comment by klattimer** [comment]
It's just a cocoa static library template at the minute, building reachability, testing a basic class and importing a pod.

**Comment by klattimer** [comment]
podspec looks like
Pod::Spec.new do |s|
s.name         = "Library"
s.version      = "0.0.1"
s.summary      = "A static library test."
s.platform = :ios
s.description  = <<-DESC
Simple cocoa static library + podspec test
DESC
s.homepage     = "http://gitweburl"
s.author             = { "Karl Lattimer" => "email" }
s.source             = { :git => "ssh://giturl", :tag => s.version }
s.source_files  = "Library/**/*.{h,m}"
s.exclude_files = "Library/Exclude"
s.public_header_files = "Library/**/*.h"
end

**Comment by klattimer** [comment]
podfile looks like 

target 'Library' do
pod 'Reachability'
workspace 'Library'
end

target 'LibraryTests' do
pod 'Reachability'
workspace 'Library'
end

**Comment by neonichu** [comment]
Your dependency needs to be declared in the podspec, not the Podfile.

**Comment by klattimer** [comment]
Can you explain how I can fix this? 

I've tried adding s.dependency "Reachability" but that hasn't helped. Wouldn't it make sense for the podspec to inherit dependencies from a podfile?

**Comment by neonichu** [comment]
Podfiles aren't visible to CocoaPods when resolving dependencies. You can inherit the other way around, though, using `podspec` (see <https://guides.cocoapods.org/syntax/podfile.html#podspec>)
