### ISSUE TITLE
`user_target_xcconfig` doesn't merge build settings which accept multiple values (0.38.0.beta2)

### ISSUE THREAD

**Issue by sodastsai** [CocoaPods/CocoaPods#3813]
Here I have a podspec of Overcoat (https://github.com/Overcoat/Overcoat/blob/865d0df37663558ed5afe286c828026c227a0314/Overcoat.podspec) 

I've assigned some different `GCC_PREPROCESSOR_DEFINITIONS` via `user_target_xcconfig`, but they are not merged at all.

My testing Podfile is 
```ruby
inhibit_all_warnings!
use_frameworks!
pod 'Overcoat', :subspecs => ['Social', 'CoreData'], :git => 'https://github.com/Overcoat/Overcoat.git', :branch => 'master'
```

Resolved `GCC_PREPROCESSOR_DEFINITIONS` is 
```
$(inherited) COCOAPODS=1 OVERCOAT_SUPPORT_SOCIAL=1
```
but should be
```
$(inherited) COCOAPODS=1 OVERCOAT_SUPPORT_SOCIAL=1 OVERCOAT_SUPPORT_COREDATA=1 OVERCOAT_SUPPORT_URLSESSION=1
```

This issue only happens when the Podfile has `use_frameworks!`, if there's no such line, the resolved `GCC_PREPROCESSOR_DEFINITIONS` is correct for me.

**Comment by MattKiazyk** [comment]
Same issue here with the following podfile

```
platform :ios, '8.0'
use_frameworks!

pod 'Realm'
pod 'RealmSwift'
pod 'CLKTooltip'
```

pod install is returning:
```
[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.
```

for now i'm removing the `CLKTooltip` which has a `pop` dependency and things are working.

**Comment by segiddins** [comment]
@MattKiazyk that's not an issue, since `CLANG_CXX_LANGUAGE_STANDARD` _is_ singular and there's no way to merge it

**Comment by MattKiazyk** [comment]
@segiddins so this is more on the pod developers?

**Comment by segiddins** [comment]
yup

**Comment by sodastsai** [comment]
:+1:

**Comment by suhinini** [comment]
Guys, I have the same problem as @MattKiazyk:

`[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.`

Downgrading to `0.37.1` to workaround this for now, but please can anyone provide a more "dummy" explanation? I get it that:

'pop' uses `'CLANG_CXX_LANGUAGE_STANDARD' => 'c++11'`
'Realm' uses `'CLANG_CXX_LANGUAGE_STANDARD' => 'compiler-default'`

And this can't be merged to a single value, ok. But who should fix this? Like, I need both Realm & pop in my project and `0.38.2` complains on using them both. Definitely I can't force any of those pod authors to change their config, so are there any adequate actions to take?

Thanks

**Comment by iantheparker** [comment]
I'm in the exact same boat as @suhinini (Realm vs. pop) - I'm downgrading for now, but eager to figure out the best steps forward. Thanks!

**Comment by keyclipse** [comment]
Same problem here! Downgrading for now!

**Comment by rais38** [comment]
The same problem here with `MobileVLCKit` and `pop`.

> [!] Can't merge user_target_xcconfig for pod targets: ["MobileVLCKit", "pop"]. Singular build setting CLANG_CXX_LIBRARY has different values.

**Comment by keyclipse** [comment]
Shouldnt someone reopen this issue?

**Comment by sodastsai** [comment]
I think it's better to creat a new issue and then add a reference back to this one. 
This issue mainly targeted on merging failure of settings accepting multiple valises. But the new issue is merging failure of settings that doesn't accept multiple values.

In my opinion, I think these are podspec provides side issues. Because in some cases, we could not just decide which value to keep. Maybe one library is only okay with a specific value and another is only okay with another value. For build settings, maybe the Cocoapods could add new interfaces for each pod targets. But for linker settings, I think it's podspec provides' responsibilities.

**Comment by segiddins** [comment]
No, there's no issue here -- CocoaPods can't do anything about build settings that cannot be combined, besides telling you so and pointing Pod authors to use `pod_target_xcconfig` whenever possible.

**Comment by pronebird** [comment]
Still getting this:

```
[!] Can't merge user_target_xcconfig for pod targets: ["Realm", "Headers", "pop"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.
```

**Comment by RishatShamsutdinov** [comment]
The issue still exists on 1.2.0. I have 2 pods that have specific defines in subspecs, Cocoapod uses defines only from one pod (defines from 2nd pod dropped at all and doesn't exist in target's config).

**Comment by benasher44** [comment]
@RishatShamsutdinov thanks for the report! Could you file a new issue with more details? Thanks!

**Comment by RishatShamsutdinov** [comment]
@benasher44 Hi! I create sample project and filled new issue: https://github.com/CocoaPods/CocoaPods/issues/6569
