### ISSUE TITLE
Cannot use dependency from private repo

### ISSUE THREAD

**Issue by klattimer** [CocoaPods/CocoaPods#3814]
I'm trying to pull in a dependency from a private repo, into a library, I added s.dependency "PodName" to the library podspec but I'm told it's unable to find the spec. If I do "pod search Library" it shows up. 

I faced a similar problem with creating another project as a consumer of the library and I added source to the podfile with the repo url. There doesn't appear to be an equivalent in the podspec.

**Comment by segiddins** [comment]
You need to use the `source` method in your podfile, or the `--sources` flag when linting.

**Comment by klattimer** [comment]
the source method _IS_ in the podfile, however it still doesn't accept the dependency.

**Comment by segiddins** [comment]
Then please include a reproducible failure case in your issue so we can investigate

**Comment by klattimer** [comment]
--sources works when linting, but the dependency handling seems wildly inconsistent between podfile and podspec - if these two files worked better in tandem then I'd have had many fewer problems with using cocoapods
