### ISSUE TITLE
compile but not link, and missing headers

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#3817]
Podfile
```
target :MyLibrary do
	platform :ios, "6.0"
	pod 'OpenSSL-Universal', '= 1.0.1.h'
	link_with 'MyLibraryTests'
end
```

it result that ObjectivePGP target can't be build because headers are not found, because cocoapods configuration do not apply to "MyLibrary" target at all, it's all to 'MyLibraryTests'

The thing is, it use to work (I have working version with cocoapods 0.32) then stop working for the very same podspecs

I think this is somehow related to: https://github.com/CocoaPods/CocoaPods/issues/3804

**Comment by segiddins** [comment]
Does it work if you do `link_with 'MyLibrary', 'MyLibraryTests'` ?

**Comment by krzyzanowskim** [comment]
yes, but I don't want to do it.
There cause of this is missing configuration for target.

**Comment by segiddins** [comment]
It makes almost no sense to expect CocoaPods to link against a target you're explicitly telling it _not_ to link against?

**Comment by krzyzanowskim** [comment]
Exactly, yet I'd like to have pod headers around. Build, but not link.

**Comment by segiddins** [comment]
That's not currently an option with CocoaPods, but it will be once the new Podfile DSL is done.

**Comment by neonichu** [comment]
New Podfile DSL is tracked by #840, so I believe we can close this.
