### ISSUE TITLE
Archive failed by build failed   but it can be run into devices 

### ISSUE THREAD

**Issue by persenlee** [CocoaPods/CocoaPods#3821]
hello,guys
  when i try archive ,it failed by build failed reason,but i can run project into my device . and I have tried with demo project without pos it works fine.
  can anyone help~~
 xcode : 6.3.1  pods : 0.38.0.beta.2

**Comment by segiddins** [comment]
This bug report is not sufficient for us to investigate -- please reopen with an example project we can use to reproduce the issue, thanks!
