### ISSUE TITLE
Discussion: strategy for graceful deprecation and subsequent removal of pods

### ISSUE THREAD

**Issue by dcow** [CocoaPods/CocoaPods#3827]
It's no secret that CocoaPods is *the* go-to dependency manager for iOS projects. And rightly so, it's a great tool. However, as CocoaPods becomes more popular and gains more users, people come to rely on artifacts existing consistently. Especially in the enterprise realm, but generally true for many projects, builds need to be reproducible. The developer needs to be able to checkout an old release branch of their project, apply a hotfix, and build the project. The intent here is to facilitate a discussion around best practices for deprecation and removal of artifacts from CocoaPods central repository. I think it's important to have a consistent story around artifact retention before hitting a 1.0 release.

It's also the responsibility of the developer to manage their dependencies. Practically, it's unreasonable to expect that old pod specifications should *always* exist. Hence, I propose a few guidelines to ease the removal process for all artifacts that do not warrant special treatment.

Here's my suggestion:

* All pod specs must be deprecated (with developer facing warning) before being removed, and
* deprecated pod specs should remain in the central repository for a period of [6mo? | 1yr?], after which they can be hastily and fully purged.

Finally, there are certainly scenarios where prompt removal of artifacts is desired (e.g. legal issues or security vulnerabilities). For special cases where such action is required, I propose:

* If an exception to the above guidelines should be made, the community should be notified as promptly as possible and ideally *before* such removal occurs.

For large projects with lots of planning, these requirements should sound pretty familiar. If we want to drive CocoaPods adoption further into the enterprise development space, expectations like these will really ease people's concern around whether can rely on CocoaPods in a project with strict deadlines and prompt release and delivery expectations.

**Comment by keith** [comment]
Rules about needing to deprecate a pod are actually defined here: https://github.com/CocoaPods/Specs/pull/12199 (although they are not as specific). In this case these weren't abided by.

**Comment by billinghamj** [comment]
+1 to putting them back.

**Comment by neonichu** [comment]
Just a note: as also stated [here](https://github.com/CocoaPods/Specs/pull/13313#issuecomment-122203524) CocoaPods cannot and does not guarantee the stability of your builds, because it does not host any of a Pod's actual sources.

**Comment by dcow** [comment]
@neonichu of course CocoaPods doesn't guarantee general build stability. (But given that it is transparent where pods are hosted, it is possible to audit the source to determine reliability.) The only thing you can do to get 100% stability is to check all bits in that are needed for your build. No argument there.  We're besides the point arguing about general build stability. 

Network issues are excusable, mistakes happen. But Specs#13313 was not a network issue or mistake (at least as people on the CP team seem to view it) that was quickly reverted. It was a *decision* made by the CocoaPods team to act against the better judgement laid down in Specs#12199 and remove pods specs which were being actively used by a non-trivial number of people with **no warning** whatsoever to the community.

It's a finer distinction, sure, but important nonetheless. No one is asking CocoaPods to, "give me all the build stabilitiezzz". And I'm not trying to move that responsibility off individual teams and make CP carry more burden that it should, either. But Specs#12199 or similar guidelines (like the ones proposed here) exist to mitigate exactly the issue that happened with Specs#13313.

At the end of the day, there is not a silver bullet to navigate sticky dependency management scenarios. But I'd like to stress that communication is essential when the uglier things need to happen. A simple "Heads up, we're going to have to remove some old specs. They will be removed at this time. Please plan accordingly." would have gone a very long way.

**Comment by segiddins** [comment]
Since this issue doesn't actually involve any of the code in _this_ repo, I'm going to close it and suggest moving discussion to the Specs repo.
