### ISSUE TITLE
pod lib lint generates exception on Xcode7 b2

### ISSUE THREAD

**Issue by terhechte** [CocoaPods/CocoaPods#3829]
Hey,

I'm trying to create a pod for a new Swift 2.0 framework, and when I'm doing a `pod lib lint` on the commandline (following this guide: https://guides.cocoapods.org/making/making-a-cocoapod.html) I'm getting the following exception:

```
2015-07-16 14:31:00.340 ruby[89773:421357] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8123.33/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fcda5917a70>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x000000010c1d1047 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x000000010c1d07d4 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010c1d0a40 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000010c1d09a2 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x000000010d7bf1a9 IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000011172ea5d +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x00000001117305e2 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff95f82f44 ffi_call_unix64 (in libffi.dylib)
[1]    89773 abort      pod lib lint
```

**Comment by segiddins** [comment]
`gem install cocoapods -v 0.24.3` ?

**Comment by terhechte** [comment]
pod --version
0.37.2

```
gem install cocoapods -v 0.24.3
ERROR:  Could not find a valid gem 'cocoapods' (= 0.24.3) in any repository
ERROR:  Possible alternatives: cocoapods
```

**Comment by segiddins** [comment]
sorry, too early in the morning
`gem install xcodeproj -v 0.24.3

**Comment by terhechte** [comment]
That worked. Awesome, thanks!

**Comment by hkellaway** [comment]
this just helped me out - thanks !

**Comment by RyPoints** [comment]
This worked great for me as well.

**Comment by jimcervone** [comment]
Different STR, same exception. I was trying to run `pod install` using Cocoapods 0.37.2 and Xcode 7.0's Command Line Tools, and seeing this exception at `Generating Pods project`. @segiddins had the solution that got me up and running again. :+1: thanks!

**Comment by aksswami** [comment]
I have updated my cocoapods(0.38.2) gem and xcodeproj(0.27.2), but still getting error:-

- Writing Xcode project file to `Pods/Pods.xcodeproj`
2015-09-24 09:40:27.969 ruby[12098:428715] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8227/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fb9adbd99d0>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x000000011038ca5c -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x000000011038c1e9 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000011038c455 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000011038c3b7 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x00000001118c5f5c IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000011451deb9 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x000000011451fa3e +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff8da7df44 ffi_call_unix64 (in libffi.dylib)
[1]    12098 abort      pod install --verbose

@segiddins 's solution not working for me, as cocoapods 0.38.2 depends upon xcodeproj 0.26, So I am not able to downgrade.

Please suggest some solution.

**Comment by stephanebruckert** [comment]
Here is a *suggestion*, Deintegrate Cocoapods from your project (if already existing) and integrate it again.

    gem install cocoapods-deintegrate
    pod deintegrate
    pod install

**Comment by aksswami** [comment]
@stephanebruckert I am trying to install pod to a new project. So no pods exists.

**Comment by yukhdev** [comment]
With cocoapods 0.38.2 and xCode 7 with latest "Command line tool" works for me.

**Comment by dNadiia** [comment]
```
gem uninstall cocoapods
gem install cocoapods
```
after that Xcode7 works with pod --version 0.38.2

**Comment by zinwalin** [comment]
gem install xcodeproj -v 0.24.3   
it works for me.
