### ISSUE TITLE
CocoaPods to do 'install' or 'update' command unsuccessful

### ISSUE THREAD

**Issue by doudouhihi** [CocoaPods/CocoaPods#3831]
My step:
We have a project which depended on our packaged private sdk.Our sdk was managed by cocoapods.
When I do the update operation from subversion，and build my project，it gives me the issue that can not found the Podfile.lock. Then I do the 'Pod update'/'Pod install'，but still is not successful. After that，I delete the Pods folder and the Podfile.lock，to retry，but is still unsuccessful. Then I send search command，and find this framework ，but the source url is not the url shown in the install/update command

The following is the issues:

Pre-downloading: `TorqueSDK` from `http://git01.dds.com/cm/torque_sdk_ios.git`, branch `develop`
Downloading dependencies
Installing AFMacros (1.3.1)
Installing AFNetworking (1.3.4)
Installing CocoaLumberjack (2.0.1)
Installing CoreTextLabel (HEAD based on 1.5.13)
Installing EAIntroView (2.7.4)
Installing EARestrictedScrollView (0.2.0)
Installing IQKeyboardManager (3.2.4)
Installing ISO8601DateFormatterValueTransformer (0.6.0)
Installing MJRefresh (2.2.1)
Installing NSString-HTML (0.0.1)
Installing RKValueTransformers (1.1.2)
Installing RegexKitLite (4.0)

[!] Error installing RegexKitLite
[!] /usr/bin/svn export --non-interactive --trust-server-cert --force "https://svn.code.sf.net/p/regexkit/code/RegexKitLite" -r "69" /Users/gongshuying/Desktop/Torque_Lite_IOS/Pods/RegexKitLite

svn: E175002: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/regexkit/code/RegexKitLite'

svn: E175002: OPTIONS of 'https://svn.code.sf.net/p/regexkit/code/RegexKitLite': could not connect to server (https://svn.code.sf.net)

Then I do the search command:
$ Pod search RegexKitLite

-> RegexKitLite (4.0)
   Lightweight Objective-C Regular Expressions using the ICU Library.
   pod 'RegexKitLite', '~> 4.0'
   - Homepage: http://regexkit.sourceforge.net/RegexKitLite/
   - Source:   https://svn.code.sf.net/p/regexkit/code/RegexKitLite
   - Versions: 4.0 [master repo]

-> RegexKitLite-NoWarning (1.1.0)
   It is cloned from official subversion (RegexKitLite-4.0). This fork fix some wwarning raised.
   pod 'RegexKitLite-NoWarning', '~> 1.1.0'
   - Homepage: https://github.com/zhangao0086/RegexKitLite-NoWarning
   - Source:   https://github.com/zhangao0086/RegexKitLite-NoWarning.git
   - Versions: 1.1.0, 1.0.0 [master repo]

**Comment by doudouhihi** [comment]
access the https://svn.code.sf.net/p/regexkit/code/RegexKitLite

the safari show: can not open the url

**Comment by segiddins** [comment]
As the error message says, the issue is that that SVN repo appears to be unreachable.
