### ISSUE TITLE
Xcode which is Version 6.4 will be dead when i open in the first time everyday

### ISSUE THREAD

**Issue by yslwjj** [CocoaPods/CocoaPods#3833]
Xcode which is Version 6.4 will be dead when i open in the first time everyday.Sometimes I need to open several times in a row. 
Today I encountered this problem again, it is CocoaPods cause told me

**Comment by neonichu** [comment]
Are you saying that Xcode crashes for you and you believe it is because of CocoaPods? If yes, please provide an example project or steps to reproduce this. In any case, you should also report Xcode crashes to Apple at <https://bugreport.apple.com>.

**Comment by yslwjj** [comment]
![cocoapod](https://cloud.githubusercontent.com/assets/8616761/8761190/e24b449a-2d75-11e5-8108-ad3cc1ef369f.png)
yes,it is.Today I met this problem again，please refer to the image above. I can't make sure the cocoaPods cause the Xcode crashes, but the error is that “When using CocoaPods plug-in Xcode exit”.

My friends also met the problem, and one of my friends told me that “Uninstall cocoaPods would not have happened”.

Xcode which is version 6.3 could't happened, maybe  the result of Xcode 6.4.

**Comment by neonichu** [comment]
Oh you're using one of the CocoaPods Xcode plugins. You've come to the wrong repo for those, none of them is made by the CocoaPods project itself.
