### ISSUE TITLE
Use correct paths for file references of the build products in the Pods.xcodeproj

### ISSUE THREAD

**Issue by pinxue** [CocoaPods/CocoaPods#3835]
So far the products location full path is pointing to path like: ...Build/Products/Debug/MyPod.framework

But nowadays Xcode uses Debug-iphoneos or Debug-iphonesimulator instead. Which causes the product is always red in Xcode (means not found).

Considering the Xcode itself set product location using Debug-iphoneos, could CocoaPods targets use Debug-iphoneos instead of Debug?

**Comment by orta** [comment]
So this seems to be a question around "why are these showing Red in my Xcode" even though they are fully built: 

![screen shot 2015-07-21 at 16 19 29](https://cloud.githubusercontent.com/assets/49038/8804463/49a6b264-2fc4-11e5-9661-383bd1819ef0.png)

**Comment by pinxue** [comment]
Yep. For the targets generated by Xcode wizard, build once for device instead of simulator can turn the colour right :-)

**Comment by segiddins** [comment]
This is actually Xcode's default -- `CONFIGURATION_BUILD_DIR = $(BUILD_DIR)/$(CONFIGURATION)`

**Comment by segiddins** [comment]
Hm, we actually do use `CONFIGURATION_BUILD_DIR = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)`, so I have no idea what's causing the issue

**Comment by segiddins** [comment]
Is this still an issue?

**Comment by mrackwitz** [comment]
I can't reproduce this issue, even with the new scoping introduced by 1.0.
