### ISSUE TITLE
Wrong stars number

### ISSUE THREAD

**Issue by skywinder** [CocoaPods/CocoaPods#3836]
Hi. Here is mu profile page:
https://cocoapods.org/owners/3223

And there is 0 stars for [GaugeKit](https://github.com/skywinder/GaugeKit)
![screen shot 2015-07-17 at 16 26 13](https://cloud.githubusercontent.com/assets/3356474/8748090/bf101d8c-2ca0-11e5-82cb-9c11e537525d.png)

But there is more 450 stars already.

**Comment by segiddins** [comment]
This probably belongs over on the metrics.cocoapods.org repo

**Comment by skywinder** [comment]
@segiddins I think you're right. I create same issue in that repo: https://github.com/CocoaPods/metrics.cocoapods.org/issues/31
