### ISSUE TITLE
pod-template: rename Pod folder to MyLibrary name

### ISSUE THREAD

**Issue by malcolmhall** [CocoaPods/CocoaPods#3840]
Hi I'd like to suggest when using 'pod lib create' instead of putting the source in Pod/Classes it puts it in a folder with MyLibrary name. That way when valuable new eyes browse the project on Github they can easily find the source code. Thanks!

Maybe Example could be renamed Demo too :-)

**Comment by segiddins** [comment]
This belongs on https://github.com/CocoaPods/pod-template, thanks!
