### ISSUE TITLE
0.38.0: New "Include of non-modular header" errors when building tests

### ISSUE THREAD

**Issue by jshier** [CocoaPods/CocoaPods#3847]
Podfile:
```ruby
platform :ios, '7.1'

pod 'MBProgressHUD', '~> 0.9.1'
pod 'GoogleMaps', '~> 1.10.0'

link_with 'App'

target :'AppTests', :exclusive => true do
  pod 'OHHTTPStubs'
end

target :'AppUITests', :exclusive => true do
  pod 'OHHTTPStubs'
end
```

This is a bit strange. After updating to 0.38.0, my project suddenly fails to build for testing (the AppTests target). The GoogleMaps build fails with repeated "Include of non-modular header inside framework module 'GoogleMaps'". Same code works just fine with 0.37.2. My main target builds fine and the app runs fine as well. Before I screw around with my project settings, are there any relevant changes I should know about, or perhaps this is a bug?

**Comment by jshier** [comment]
Likely relevant bit of info: this is using Xcode 7 beta 3.

**Comment by muccy** [comment]
Same problem with Google-Mobile-Ads-SDK

**Comment by keith** [comment]
I see this problem intermittently with Stripe as well. I'm able to clean the project, rebuild and it be gone. Using Xcode 6.4.

**Comment by jshier** [comment]
Still an issue with 0.38.1. Just my test target is broken.

**Comment by jshier** [comment]
Still and issue with 0.39.0.beta.1.

**Comment by lumenlunae** [comment]
Alamofire seems to be requiring 0.38.2, so to get that pod to even run pod install, I get this same issue in regards to the DigitsKit pod. It's reporting the error only on my test target, which does not include the pod, similar in setup to jshier. Each target has "Allow non-modular includes in Framework modules" and I tried this in the pod:
```
post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end
```

**Comment by henriquesobral** [comment]
Hi,

I found a workaround, at least for GoogleMaps. Describing each header in its ```module.modulemap``` file. 
I got the same issue every time that I used printObject ```po``` in lldb command-line, when I was debugging my app.

```
framework module GoogleMaps {
umbrella header "GoogleMaps.h"
export *
module * { export * }

header "GMSAddress.h"
header "GMSAutocompleteFilter.h"
header "GMSAutocompleteMatchFragment.h"
header "GMSAutocompletePrediction.h"
header "GMSCALayer.h"
header "GMSCameraPosition.h"
header "GMSCameraUpdate.h"
header "GMSCircle.h"
header "GMSCoordinateBounds.h"
header "GMSGeocoder.h"
header "GMSGeometryUtils.h"
header "GMSGroundOverlay.h"
header "GMSIndoorBuilding.h"
header "GMSIndoorDisplay.h"
header "GMSIndoorLevel.h"
header "GMSMapLayer.h"
header "GMSMapView+Animation.h"
header "GMSMapView.h"
header "GMSMarker.h"
header "GMSMarkerLayer.h"
header "GMSMutablePath.h"
header "GMSOrientation.h"
header "GMSOverlay.h"
header "GMSPanorama.h"
header "GMSPanoramaCamera.h"
header "GMSPanoramaCameraUpdate.h"
header "GMSPanoramaLayer.h"
header "GMSPanoramaLink.h"
header "GMSPanoramaService.h"
header "GMSPanoramaView.h"
header "GMSPath.h"
header "GMSPlace.h"
header "GMSPlaceLikelihood.h"
header "GMSPlaceLikelihoodList.h"
header "GMSPlacePicker.h"
header "GMSPlacePickerConfig.h"
header "GMSPlacesClient.h"
header "GMSPlacesMacros.h"
header "GMSPlaceTypes.h"
header "GMSPolygon.h"
header "GMSPolyline.h"
header "GMSProjection.h"
header "GMSServices.h"
header "GMSSyncTileLayer.h"
header "GMSTileLayer.h"
header "GMSUISettings.h"
header "GMSURLTileLayer.h"
header "GMSUserAddedPlace.h"
}
```

**Comment by neonichu** [comment]
This happens due to the changes in #3867 — basically non-modular includes when integrating as frameworks worked previously because we had an additional copy of headers in the sandbox. This change was deliberate, unfortunately this has masked problems with certain Pods in versions < 0.38. Pod authors will have to fix their Pods so that they work correctly as modules, until then [this workaround](https://github.com/CocoaPods/CocoaPods/issues/3847#issuecomment-135620583) by @lumenlunae is the right call.

**Comment by jshier** [comment]
@lumenlunae Did that workaround work for you? Your post seems ambiguous.

**Comment by lumenlunae** [comment]
Sorry, I may have posted that too soon. This is all specific to Fabric / DigitsKit at the moment, and that fix doesn't seem to get it 100% working. I can build my project, but debugging gives me errors like:  
```
  Swift had fatal errors constructing the ast context for this module: <module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/matthewaherz/Documents/Work/TheWilds/App/TheWilds/Pods/Digits/DigitsKit.framework/Headers/DigitsKit.h"
        ^
/Users/matthewaherz/Documents/Work/TheWilds/App/TheWilds/Pods/Digits/DigitsKit.framework/Headers/DigitsKit.h:23:9: error: include of non-modular header inside framework module 'DigitsKit'
#import <TwitterCore/TwitterCore.h>
```

Twitter's recommendation was to go directly into the Pods/Framework/Header files and change those outside imports like:
```
#import <OtherLibrary/OtherFile.h>
```
into:
```
@import OtherLibrary;
```

Trying that worked and I get my debugger back! Hopefully a combination of that Cocoapods build setting and the above can have things working right for people.

**Comment by jonmanzo** [comment]
@henriquesobral - Thanks, you're the man!!!!

**Comment by hoangtx90** [comment]
As for Google Maps, you should follow this tutorial on RayWenderLich: http://www.raywenderlich.com/81103/introduction-google-maps-ios-sdk-swift

You just need to create a bridging header and put this single line there:
`#import <GoogleMaps/GoogleMaps.h>`

**Comment by ctrevarthen** [comment]
In addition to @hoangtx90 's suggestion, make sure you remove any existing uses of "import GoogleMaps" from your Swift code.

**Comment by mutech** [comment]
I have two Objective-C frameworks, AKACommons and AKAControls, controls depends on commons. I can build both, but when I try to build a demo project (also Objective-C) using AKAControls it fails with "include of non-modular header..." errors.

From what I see, I use @import everywhere where it's possible. I allowed modular imports or not, doesn't make any difference.

@neonichu: You said "Pod authors will have to fix their Pods", how should we do this? I tried about everything I can think of and I just cannot fix this problem.

Is there a way to switch off every attempt of cocoa pods or Xcode or whomever does that to generate umbrella files or module maps and let me manually write one that doesn't include the AKACommons/AKACommons.h file? Would that solve the problem? I didn't find any documentation on how to do that manually anywhere...

**Comment by neonichu** [comment]
@mutech you can specify a custom module map in your podspec: https://guides.cocoapods.org/syntax/podspec.html#module_map

Another quick workaround can also be setting `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES` to `YES`, possibly via a post-install hook.

**Comment by mutech** [comment]
@neonichu, thanks for the pointer, I never saw this option (shame on me)...

Allow modular includes did not help (it did before, but not in this round).

But what is the proper way to provide Objective-C frameworks that do not fail? I don't understand the problem in first place. Why do we need another umbrella header when a project defines a Project/Project.h header? Why is that header included in the generated umbrella header? If I exclude it from public_headers spec, I get other warnings saying that it's not public (when compiling Swift sources). What a mess...

**Comment by neonichu** [comment]
@mutech way too many Pods had a `ModuleName/ModuleName.h` header that wasn't really an umbrella header, so we decided to ensure that the umbrella header includes all public headers defined by the podspec by generating one when the frameworks support was originally conceived. Generally, this approach works fine.

It's hard to say what exactly makes your headers "non-modular" without having additional information.

**Comment by robsmall** [comment]
For me removing the master pod repo, re setting it up, re-installing, and rebuilding solved the problem. Quick and easy fix.

To do this:
```bash
$ cd path/to/project
$ pod repo remove master
$ pod setup
$ pod install
```
then rebuild in xcode.

**Comment by fsproru** [comment]
The only way I found that fixes it is to include the `GoogleInteractiveMediaAds` framework manually :disappointed:. Would love to use CocoaPods for it though.

**Comment by cvby** [comment]
@lumenlunae you are ture man
