### ISSUE TITLE
pod install takes several minutes to write Xcode project file

### ISSUE THREAD

**Issue by ranunez** [CocoaPods/CocoaPods#3852]
Since upgrading to v0.38, running `pod install --verbose` hangs for several minutes (up from several seconds compared with v0.37.2) on:
```
 Writing Xcode project file to `Pods/Pods.xcodeproj`
```

After several seconds, it finishes writing, and then prints the rest of the output
```
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods` (`enroll.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from
    `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb`

Sending stats
      - AFNetworking, 2.5.4
      - CCTemplate, 0.2.0
      - CocoaLumberjack, 2.0.0
      - FCFileManager, 1.0.10
      - NMRangeSlider, 1.2.1
      - SAMTextField, 0.1.2
      - SAMTextView, 0.2.2
      - XNGMarkdownParser, 0.3.2
```

**Comment by segiddins** [comment]
You you please share you Podfile so we can try and optimize it? In the meantime, you can set the `COCOAPODS_DISABLE_DETERMINISTIC_UUIDS` environment variable.

**Comment by ranunez** [comment]
I would, but my podfile consists primarily of private pods. I have tried removing some dependencies, and it seems the less dependencies my pod uses, the faster it takes to write the Xcode project file. I will try to find a podfile consisting of public pods which have this same issue.

**Comment by segiddins** [comment]
Just curious, how many total pod targets does your `Pods.xcodeproj` have?

**Comment by ranunez** [comment]
45

**Comment by segiddins** [comment]
I'm going to close this issue, as it doesn't include a project we can use to test performance improvements. Feel free to re-open if you can share a pod file, Thanks!

**Comment by orta** [comment]
For comparison [artsy/eigen](https://github.com/artsy/eigen) has a similar number and doesn't see the same behavior.
