### ISSUE TITLE
Static library project don't support libraries in Xcode 6.4 ?

### ISSUE THREAD

**Issue by gonefish** [CocoaPods/CocoaPods#3853]
I create a new static library project

My Podfile content:
pod 'Qiniu', '~> 7.0.11.1' 

But build error, the Qiniu Podspec has a line: s.libraries = 'z'

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified the following flags are invalid: -ObjC 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lz
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lz is not an object file (not allowed in a library)

**Comment by neonichu** [comment]
This should have been fixed by 0.38, I think. See <https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#bug-fixes-3> and #3677

**Comment by gonefish** [comment]
Yep, this version fix my problem. it is very timely :+1:
