### ISSUE TITLE
pod trunk push --allow-warnings fails because of warnings

### ISSUE THREAD

**Issue by gabro** [CocoaPods/CocoaPods#3855]
```sh
pod trunk push --allow-warnings ReactiveCocoa.podspec.json
Updating spec repo `master`
Validating podspec
 -> Reac -> ReactiveCocoa (3.0.0-RC.1)
    - WARN  | The version should be included in the Git tag.

[!] The Pod Specification did not pass validation.
The following validation failed:
- Warnings: The version should be included in the Git tag.
```

On the other hand, `pod spec lint` works just fine

```sh
pod spec lint --allow-warnings ReactiveCocoa.podspec.json

 -> ReactiveCocoa (3.0.0-RC.1)
    - WARN  | The version should be included in the Git tag.

Analyzed 1 podspec.

ReactiveCocoa.podspec.json passed validation.
```

I'm using version 0.38.0

**Comment by segiddins** [comment]
Pretty sure that warning is actually coming from the trunk server? I'll have to double check thougj

**Comment by ashfurrow** [comment]
It is

**Comment by gabro** [comment]
news on this?

**Comment by segiddins** [comment]
So, iirc, the point of `--ignore-warnings` on `pod trunk push` was really only to ignore compilation warnings, not warnings in the spec itself -- we want the specs on trunk to all lint  cleanly.

**Comment by gabro** [comment]
Oh I see, that's quite confusing then. Maybe a message explaining this could help

gabriele
~ buildo

**Comment by ashfurrow** [comment]
Interesting. I guess I'll ask the question, then: should this _really_ be a warning? In this case, the pod authors don't have access to create a new tag on the repo, and I believe that specifying a commit is also a warning, right? Looking through the git history, the warning has existed for as long as the linter has been in Core – maybe it's time to reevaluate this decision. As a compromise, could there be a way to surface this feedback to the user, but not create a warning?

**Comment by alloy** [comment]
> I guess I'll ask the question, then: should this really be a warning?

In my opinion, this does _not_ need to be a warning on Trunk.

> As a compromise, could there be a way to surface this feedback to the user, but not create a warning?

I don’t think that’s even needed and would only complicate things.

**Comment by ashfurrow** [comment]
Cool cool. I've gotten good at deleting code, even Ruby, so I'd be happy to do this if that's the consensus.

**Comment by segiddins** [comment]
imho the answer is to allow passing the `allow_warnings` option to trunk

**Comment by alloy** [comment]
Agreed 👍

**Comment by gabro** [comment]
Agreed, that feels like the clearest option, because it would make it behave as `pod spec lint`

**Comment by orta** [comment]
This is enabled in https://github.com/CocoaPods/trunk.cocoapods.org/pull/143
