### ISSUE TITLE
Header search paths are not properly set for static library pods when use_frameworks! is enabled

### ISSUE THREAD

**Issue by perotinus** [CocoaPods/CocoaPods#3857]
After commit https://github.com/CocoaPods/CocoaPods/commit/df34f79ffc2e0a0ddb5a851cebfd89407ec434b5, Pods with static ```vendored_libraries``` as dependencies can be handled and linked if there are no dynamic pods that depend on them. This means that a user target can have both embedded frameworks and  However, the code in ```aggregate_xcconfig.rb``` that munges header search paths and such properly expects that all pods will either be statically linked or turned into frameworks. This is still true in the static case, but not in the dynamic case: in the dynamic case, a dependency tree of pods that is completely static will be linked statically.

A simple fix could be just checking if there are any pod targets where ```should_build?``` is false when using frameworks, and if so, include the header search paths for static libraries. Doing so would lead to more header search paths than necessary. This isn't ideal, but I don't think it breaks anything.

**Comment by segiddins** [comment]
@perotinus that's probably the right thing to do. Want to make a PR adding it?

**Comment by neonichu** [comment]
An anecdote I heard in a talk about Swift build times yesterday is that each entry in the header search path slows down the build of Swift targets, that might be something to consider for this.
