### ISSUE TITLE
Does CocoaPods support alpha versions?

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/CocoaPods#3858]
It looks like [with RubyGems](http://docs.travis-ci.com/user/deployment/rubygems/#Pre-releasing) you can conditionally overwrite the version number of a `gemspec` like so:

    s.version = "#{s.version}-alpha-#{ENV['TRAVIS_BUILD_NUMBER']}" if ENV['TRAVIS']

Is this supported in a `podspec`?

Further, is there any plan for adding [integrated deployment](http://docs.travis-ci.com/user/deployment/) to Travis? That would allow for super-simple deployment, like so:

```none
deploy:
  - provider: cocoapods
    email: "YOUR COCOAPODS EMAIL"
    deployment: "POD NAME"
    api_key "YOUR COCOAPODS API KEY"
```

**Comment by segiddins** [comment]
Yes, CocoaPods supports alpha version. As for integrated deployment, it looks like that's a question to ask travis?
