### ISSUE TITLE
Target Deduplication in 0.38.0: clang parameters still contain target-specific libs

### ISSUE THREAD

**Issue by JaNd3r** [CocoaPods/CocoaPods#3862]
It seems, that the libs that were created for "duplicated" targets are still referenced in the clang call but are no longer present as CocoaPods 0.38.0 does not create these targets any more (which is a nice feature btw).

I have anonymized and shortened an example output from the build's log... There are two targets, named `AppName` and `AppName MonkeyTalk` and several public and private pods which are contained in both targets. The build for the second target fails:

     [exec]     /Users/cislave/[...]/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Users/cislave/[...]/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/cislave/[...]/DerivedData/Build/Products/MonkeyTalk-iphoneos -L/Users/cislave/[...]/Pods/Scanner/SocketMobileSDK -L/Users/cislave/[...]/Pods/MonkeyTalkExtensions -F/Users/cislave/[...]/DerivedData/Build/Products/MonkeyTalk-iphoneos -filelist /Users/cislave/[...]/DerivedData/Build/Intermediates/AppName.build/MonkeyTalk-iphoneos/AppName\ MonkeyTalk.build/Objects-normal/arm64/AppName_MonkeyTalk.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -all_load -ObjC -lJSONModel -lMonkeyTalk-2.0.9 -lAlertCenter -lHandshake -lLogger -lMonkeyTalkExtensions -lOperation -lRestClient -lScanner -lUtil -lScanApi -ObjC -lMonkeyTalk-2.0.9 -lPods-MonkeyTalk-JSONModel -lPods-MonkeyTalk-AlertCenter -lPods-MonkeyTalk-Handshake -lPods-MonkeyTalk-Logger -lPods-MonkeyTalk-MonkeyTalkExtensions -lPods-MonkeyTalk-Operation -lPods-MonkeyTalk-RestClient -lPods-MonkeyTalk-Scanner -lPods-MonkeyTalk-Util -lScanApi -liconv -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreVideo -framework QuartzCore -fobjc-arc -fobjc-link-runtime -L/Users/cislave/[...]/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/cislave/[...]/DerivedData/Build/Intermediates/AppName.build/MonkeyTalk-iphoneos/AppName\ MonkeyTalk.build/Objects-normal/arm64/AppName_MonkeyTalk.swiftmodule -lstdc++.6.0.9 -lsqlite3 -framework CFNetwork -lstdc++ -framework AudioToolbox -framework ExternalAccessory -liconv -framework QuartzCore -framework CoreVideo -framework CoreMedia -framework AVFoundation -lPods -lPods-MonkeyTalk -Xlinker -dependency_info -Xlinker /Users/cislave/[...]/DerivedData/Build/Intermediates/AppName.build/MonkeyTalk-iphoneos/AppName\ MonkeyTalk.build/Objects-normal/arm64/AppName_MonkeyTalk_dependency_info.dat -o /Users/cislave/[...]/DerivedData/Build/Intermediates/AppName.build/MonkeyTalk-iphoneos/AppName\ MonkeyTalk.build/Objects-normal/arm64/AppName_MonkeyTalk
     [exec] ld: library not found for -lPods-MonkeyTalk-JSONModel
     [exec] clang: error: linker command failed with exit code 1 (use -v to see invocation)
     [exec] 
     [exec] ** BUILD FAILED **

As a workaround I have disabled target deduplication as described in the [0.38.0 Change Log](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#highlighted-enhancement-that-needs-testing).

**Comment by segiddins** [comment]
Can you try running https://github.com/kylef/cocoapods-deintegrate and then `pod install` again?

**Comment by JaNd3r** [comment]
Tried this on a local developer machine, but still the build fails with the same error.

Besides: The buildserver wipes the whole workspace (project + derived data) prior to building, and the whole `Pods` folder is not under SCM. So each build does a fresh `pod install` as a build step.

**Comment by segiddins** [comment]
OK, in that case, can you please share a project that demonstrates this issue? Thanks!

**Comment by JaNd3r** [comment]
Unfortunately I cannot share the original project that caused this issue. I will set up a new project and try to reproduce the linker error.

**Comment by neonichu** [comment]
Let's close this until we get a reproducible project.

**Comment by JaNd3r** [comment]
For the sake of completeness: We figured out, why the linker was complaining about missing libraries when turning target deduplication on. For whatever reason these libraries were stated explicitly in the build settings additionally to the `${inherited}` entry. After reducing the settings to `${inherited}`, target deduplication works!

**Comment by neonichu** [comment]
Most probably, you edited the linker flags at some point, which causes Xcode to copy everything from the XCConfig , unfortunately.
