### ISSUE TITLE
OSX 10.11 El Capitan Compatibility

### ISSUE THREAD

**Issue by mogsten** [CocoaPods/CocoaPods#3864]
CocoaPods Installs, and shows in "gem list"
but when I type in "pod install", it says "pod: Command Not Found"

Is there anyway to get CocoaPods working on OSX 10.11

**Comment by neonichu** [comment]
See #3692

**Comment by ihemantd** [comment]
@neonichu 
In linked solution using 'Custom GEM_HOME' method, there is a typo in the path, 
it should be 'Software'
$ export PATH=$PATH:$HOME/Sofware/ruby/bin
