### ISSUE TITLE
Cannot install my pod anymore till CocoaPod v0.38.0

### ISSUE THREAD

**Issue by martoche9** [CocoaPods/CocoaPods#3865]
The pod install was working fine in the 0.37 version but till the update I cannot install my pod anymore.

This is the error I'm facing now:

$ pod install --verbose
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `Azot` required by `Podfile`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:209:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:131:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:130:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

- `Azot` required by `Podfile`

This is my Podspec: 

```
Pod::Spec.new do |s|

  # ―――  Spec Metadata  ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  These will help people to find your library, and whilst it
  #  can feel like a chore to fill in it's definitely to your advantage. The
  #  summary should be tweet-length, and the description more in depth.
  #

  s.name         = "Azot"
  s.version      = "0.0.5"
  s.summary      = "Azot is a mobile analysis SDK that runs directly inside phones or tablets."

  s.description  = <<-DESC
                   A longer description of Appstrack in Markdown format.

                   * Think: Why did you write this? What is the focus? What does it do?
                   * CocoaPods will be using this to generate tags, and improve search results.
                   * Try to keep it short, snappy and to the point.
                   * Finally, don't worry about the indent, CocoaPods strips it!
                   DESC

  s.homepage     = "http://hiveinmyapp.com"
  # s.screenshots  = "www.example.com/screenshots_1.gif", "www.example.com/screenshots_2.gif"


  # ―――  Spec License  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  Licensing your code is important. See http://choosealicense.com for more info.
  #  CocoaPods will detect a license file if there is a named LICENSE*
  #  Popular ones are 'MIT', 'BSD' and 'Apache License, Version 2.0'.
  #

  s.license      = "MIT"
  s.license      = { :type => "MIT", :file => "LICENSE" }


  # ――― Author Metadata  ――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  Specify the authors of the library, with email addresses. Email addresses
  #  of the authors are extracted from the SCM log. E.g. $ git log. CocoaPods also
  #  accepts just a name if you'd rather not provide an email address.
  #
  #  Specify a social_media_url where others can refer to, for example a twitter
  #  profile URL.
  #

  s.author             = { "Rémy Marty" => "rmarty@appstud.me" }
  # Or just: s.author    = "Rémy Marty"
  # s.authors            = { "Rémy Marty" => "rmarty@appstud.me" }
  # s.social_media_url   = "http://twitter.com/RemyMrt"

  # ――― Platform Specifics ――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  If this Pod runs only on iOS or OS X, then specify the platform and
  #  the deployment target. You can optionally include the target after the platform.
  #

  # s.platform     = :ios
  s.platform     = :ios, "7.1"

  #  When using multiple platforms
  # s.ios.deployment_target = "5.0"
  # s.osx.deployment_target = "10.7"


  # ――― Source Location ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  Specify the location from where the source should be retrieved.
  #  Supports git, hg, bzr, svn and HTTP.
  #

  s.source       = { :git => "https://github.com/appstud/Azot.git", :tag => "v0.0.5" }


  # ――― Source Code ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  CocoaPods is smart about how it includes source code. For source files
  #  giving a folder will include any h, m, mm, c & cpp files. For header
  #  files it will include any header in the folder.
  #  Not including the public_header_files will make all headers public.
  #

  #s.source_files  = "azotProdPod", "Azot.framework/Headers/**/*"
  s.vendored_framework  = "Azot.framework"
  s.exclude_files = "./Exclude"

  # s.public_header_files = "Classes/**/*.h"


  # ――― Resources ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  A list of resources included with the Pod. These are copied into the
  #  target bundle with a build phase script. Anything else will be cleaned.
  #  You can preserve files from being cleaned, please don't preserve
  #  non-essential files like tests, examples and documentation.
  #

  # s.resource  = "icon.png"
  # s.resources = "Resources/*.png"

  # s.preserve_paths = "FilesToSave", "MoreFilesToSave"


  # ――― Project Linking ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  Link your library with frameworks, or libraries. Libraries do not include
  #  the lib prefix of their name.
  #

  # s.framework  = "SomeFramework"
  # s.frameworks = "SomeFramework", "AnotherFramework"

  # s.library   = "iconv"
  # s.libraries = "iconv", "xml2"


  # ――― Project Settings ――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  If your library depends on compiler flags you can set them in the xcconfig hash
  #  where they will only apply to your library. If you depend on other Podspecs
  #  you can include multiple dependencies to ensure it works.

  s.requires_arc = true

  # s.xcconfig = { "HEADER_SEARCH_PATHS" => "$(SDKROOT)/usr/include/libxml2" }
  s.dependency "AFNetworking"
  s.dependency "Realm"
  s.dependency "Reachability"

end
```
Did I miss something mandatory in the change log or is there something forbidden that I'm doing ?

Regards,

Rémy

**Comment by segiddins** [comment]
Does your Podfile specify a platform of iOS 7.1 or greater?

**Comment by thedamfr** [comment]
Mine specify ios 7.0
I use to have warning like "OMG this pods is 8.0 minimum but I guess you know what you do"
Now it's just : "Fuck"

**Comment by pronebird** [comment]
I experience the same problem:

➜  blah git:(master) ✗ pod install 
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `MagicalRecord` from `https://github.com/magicalpanda/MagicalRecord.git`
Pre-downloading: `PBPopinController` from `https://github.com/pronebird/PBPopinController.git`
[!] Unable to satisfy the following requirements:

- `Fabric (~> 1.3)` required by `Podfile`

Podfile (I omitted irrelevant pods for sanity):

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Fabric', '~> 1.3'
pod 'Fabric/Crashlytics', '~> 1.3'
```

Looking at cocoapods.org, the latest version of Fabric is 1.3.2 and is available on website. https://cocoapods.org/pods/Fabric

However `pod search` returns some random information:

```
-> Fabric (1.2.8)
   Fabric by Twitter, Inc.
   pod 'Fabric', '~> 1.2.8'
   - Homepage: https://fabric.io
   - Source:  
   https://kit-downloads.fabric.io/ios/io.fabric.sdk.ios/1.2.8/io.fabric.sdk.ios-default.zip
   - Versions: 1.2.8 [master repo]
   - Subspecs:
     - Fabric/Base (1.2.8)
```

**Comment by segiddins** [comment]
@thedamfr set your platform higher if you want that platform to be considered.

**Comment by thedamfr** [comment]
It works using target as 7.0 with dependencies that states 8.0 minimum.
I can deploy via Crashlytics.

For sure it's not going on the appstore, but anyway I can't go on the
appstore with Swift dependencies. I have to include them directly in the
project each time. Or using CocoaSeeds.

So I would really like
1. You consider being more tolerant like 0.37 was
2. You consider being more explicit in the dependency break that it's
relative to the target. It's really not obvious right now
3. If you don't plan to do otherway about option 1, that you broadcast a
message to Swift pod Maker telling that they should reconsider their
minimum requirements for target.

What do you think?

**Comment by segiddins** [comment]
I'd love to do (2) but haven't thought of a good way of doing it. A PR would be awesome, though!
