### ISSUE TITLE
Setting pod configurations stopped working in 0.38.0

### ISSUE THREAD

**Issue by CraigSiemens** [CocoaPods/CocoaPods#3866]
I'm using a pod that uses private APIs that I only want included in the Debug build. Since I updated to 0.38.0, the pod is also being included with Release builds which causes my app to be rejected for Non-public API usage.

This is how it appears in my Podfile.
```
pod 'SimulatorStatusMagic', :configurations => ['Debug']
```

Edit:
Just downgraded to 0.37.2 and it works fine.

**Comment by segiddins** [comment]
This should be fixed on master by https://github.com/CocoaPods/CocoaPods/pull/3843, could you give master a try? Thanks!

**Comment by CraigSiemens** [comment]
Yup, master works fine.

**Comment by segiddins** [comment]
Ace!
