### ISSUE TITLE
Check cocoapods version programmatically.

### ISSUE THREAD

**Issue by herzi** [CocoaPods/CocoaPods#3871]
Right now, when we use cocoapods on our CI server, this message pops up:

> CocoaPods 0.38.0 is available.
> To update use: `gem install cocoapods`

Within our CI system, it would be useful if I could add a dedicated step to check the cocoapods version. I propose to extend the `outdated` command to have a flag `--selftest` which will return with an exit code of `0` if cocoapods is up to date and with an exit code of `1` otherwise. Executing `pod outdated --selftest` would still print the same information as quoted above (so it can be properly integrated into a CI warning).

**Comment by segiddins** [comment]
`ruby -rcocoapods -e 'puts Pod::VERSION'`

**Comment by herzi** [comment]
@segiddins That just prints the current version number (just as `pod --version` does). I'm asking for a way to trigger the check for a new version.

**Comment by segiddins** [comment]
I'd just check that via `gem`, personally.

**Comment by herzi** [comment]
Like this?

    einstein:~ herzi$ pod --version
    0.37.2
    einstein:~ herzi$ gem outdated | grep pod
    einstein:~ herzi$ 

Does not seem to work. (Also, CocoaPods already contains working code, why not make it useable like this?)

**Comment by segiddins** [comment]
Maybe a plugin to do this would make sense, but I don't think it needs to be in the main CocoaPods CLI.

**Comment by neonichu** [comment]
Should also be achievable by simply using the CP gem from a small custom script.
