### ISSUE TITLE
Pod configuration ignored, includes pod in all configurations

### ISSUE THREAD

**Issue by czechboy0** [CocoaPods/CocoaPods#3872]
We encountered a pretty bad bug. Our binary wasn't valid for the App Store this morning after we upgraded to CocoaPods 0.38.0. We use Reveal pod **only** in Debug (because it uses private APIs, so it gets rejected in the App Store). The Podfile snippet below worked fine in 0.37.2, however updating to 0.38.0 broke it. 

```
target :MyApp do
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end
```

This is a big issue and we had to revert back to 0.37.2 everywhere. Did the semantics for only including a pod in a certain configuration change or is this a regression? (The worst part is that CocoaPods didn't warn us of this happening at all during `pod install`, so we had no idea before the submission.)

**Comment by segiddins** [comment]
Is this fixed on master? I believe https://github.com/CocoaPods/CocoaPods/pull/3843 might've fixed it

**Comment by czechboy0** [comment]
Yup, so this is a duplicate of #3842.
