### ISSUE TITLE
-bash: /usr/bin/pod: Permission denied

### ISSUE THREAD

**Issue by sacred0x01** [CocoaPods/CocoaPods#3873]
Can't launch pod since update to 0.38.

**Comment by perotinus** [comment]
What are the permissions of ```/usr/bin/pod```? What are the results of running ```ls -l /usr/bin/pod```? It seems like the ```pod``` binary lost execute permissions.

You could run ```chmod a+x /usr/bin/pod``` to update the permissions. You might need to ```sudo``` it.

**Comment by sacred0x01** [comment]
I solved this by chown for almost all ruby gems on /Library and for this executable.
Yeah, sounds like something very stupid, but even complete reinstalling wont help.

so bad, because of breaking almost a half of working day to fixing this.

**Comment by perotinus** [comment]
Perhaps you should file a bug against RubyGems? It doesn't look like this had anything in particular to do with CocoaPods, since it affected other gems too. Did you previously install with ```sudo gem``` and this time without, or vice versa?

**Comment by segiddins** [comment]
This is a Ruby issue -- can you make sure that the directory containing your gem `EXECUTABLE DIRECTORY`  (found via `gem env`) is on your `PATH`?

**Comment by sacred0x01** [comment]
@perotinus i used sudo only. All broke up only after updating cocoapods. 

@segiddins all works before. i use only cocoapods. And today i update them. And it was bad idea and a lot of wasted time

**Comment by hariseldon78** [comment]
for anybody who find this problem i solved it with 

    sudo chmod a+rx /usr/bin/pod
    sudo chmod -R a+rX /Library/Ruby/Gems/2.0.0/gems

note the capital X in the second line

**Comment by matthewcheok** [comment]
I get a new error now after running `chmod`:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: Permission denied -- /usr/bin/pod (LoadError)
```

**Comment by claaslange** [comment]
I have the same issue as @matthewcheok

**Comment by youyan1989** [comment]
I have the same issue as @matthewcheok

**Comment by rsanchezsaezsc** [comment]
I had the same problem. @hariseldon78 solution worked but changing the second command as follows.

    sudo chmod a+rx /usr/bin/pod
    sudo chmod -R a+rX /Library/Ruby/Gems/2.0.0/
