### ISSUE TITLE
Handle module maps for static libraries

### ISSUE THREAD

**Issue by perotinus** [CocoaPods/CocoaPods#3874]
Currently the Podspec ```module_map``` is only used when the pod is integrated as a framework. However, static library targets can also have and use module maps. All that seems to be necessary is a correct module map in the header search paths.

 I think it would be possible to extend ```module_map``` so that, when compiling a static library (or a ```vendored_libraries``` pod), the ```module.modulemap``` is linked into the sandbox in ```Headers/Public```.

Reference for using static libraries with module maps: http://blog.bjhomer.com/2015/05/defining-modules-for-custom-libraries.html

**Comment by segiddins** [comment]
Doesn't your pull request handle this?

**Comment by neonichu** [comment]
See #3796

**Comment by perotinus** [comment]
Mine doesn't, but the one @neonichu referenced does (thanks!).
