### ISSUE TITLE
Private Library Pod target will not build due to implicit dependency rejection

### ISSUE THREAD

**Issue by kraftydevil** [CocoaPods/CocoaPods#3876]
I've seen similar issues reported here on github but I'm not able to come to a similar solution.

The project is my IP but I'm hesitant to share publicly. Is there any way I can give access to someone with Owner?

If you want to know more, here are some things that may or may not be special about my private pod:
- It's a library.
- It has it's own pod dependencies.
- It has a separate target for use of Core Data with the .xcodemodel included in the library target as a resource. Not sure if this is proper usage but my client apps can use the model so I'm not concerned right now.
- The library target hasn't built for probably over a year, but I've still been able to use cocoapods to deliver code to my client projects. I need to get this library building so I can unit test it.

Here are the current warnings/errors:

Warning:
`Pods was rejected as an implicit dependency for 'libPods.a' because its architectures 'x86_64' didn't contain all required architectures 'i386 x86_64'`  

Error(s):
`error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods is not an object file (not allowed in a library)`

My cocoapods version is `0.38.0`.

Things I've tried:
- Changing the project's architectures to match what was required.
- Setting `Build Active Architecture Only` to `NO` (produces many `Undefined symbols for architecture x86_64` errors)
- Added $(inherited) to FRAMEWORK_SEARCH_PATHS
- Rebuilding the workspace by removing and re-adding cocoapods completely 
(http://stackoverflow.com/questions/16427421/how-to-remove-cocoapods-from-a-project)

Just from looking at my attempted solutions, another problem is that I'm taking stabs in the dark at things I do not fully understand. 

If you are able to help then please let me know how you can inspect my project without me posting a git url here.

Thank you!

**Comment by segiddins** [comment]
I think we'll probably need a project that demonstrates these issues to be able to debug?

**Comment by kraftydevil** [comment]
Yes please, but how can I get that to you or any other owners in a private way?

**Comment by segiddins** [comment]
My email is on my github, same goes for most of the rest of the core team

**Comment by segiddins** [comment]
Hm, so I for some reason didn't pick up on the fact you're integrating _into_ a static library target. You should probably be using cocoapods-packager instead to accomplish this

**Comment by kraftydevil** [comment]
Thank you - I will take a look into the plugin and see if it works for my needs
