### ISSUE TITLE
CocoaPods 0.38.1: Ambiguous expansion of macro errors

### ISSUE THREAD

**Issue by x2on** [CocoaPods/CocoaPods#3881]
With CocoaPods 0.38.1 and the usage of `CocoaLumberJack` in a project i get the following error:

`Ambiguous expansion of macro 'LOG_LEVEL_DEF'`

Using CocoaPods 0.38.0 it works fine.

Any ideas what could be the cause for that?

**Comment by okuramasafumi** [comment]
I encountered the same problem. Downgrading to `0.38.0` works.

**Comment by neonichu** [comment]
Just to clarify, is that an error `pod install` shows or an error when building with Xcode?

**Comment by x2on** [comment]
@neonichu a error in Xcode after upgrading to CocoaPods 0.38.1 and run `pod install` with the new version. Switching back to 0.38.0 works.

**Comment by neonichu** [comment]
Unfortunately, I cannot reproduce this in a simple project. Can one of you share a code snippet that is causing that or even better an example project?

**Comment by segiddins** [comment]
This ought to be fixed in 0.38.2.
