### ISSUE TITLE
Deduplication and framework target question

### ISSUE THREAD

**Issue by ploddi** [CocoaPods/CocoaPods#3882]
Final product of my project is XCode 6 iOS framework, configured for static linking. I am using CocoaPods for managing my framework dependencies, but framework supposed to be distributes as binary and used without CocoaPods.

My framework has two types of dependencies: static libs and other frameworks. After building my framework target and integrating it with test project manually I got linker errors. It looks like static libraries dependencies are not linked in my framework binary, due deduplication. 

How can I configure Podfile to include all static libs dependencies in Framework final binary (and frameworks dependencies will be provided by users of my framework).

All works fine if test integration project uses CocoaPods environment.

**Comment by ploddi** [comment]
Probably not deduplication related, because `deduplicate_targets: false` have no effect. Static lib dependecies are not included in framework binary.

**Comment by neonichu** [comment]
The way Xcode 6 handles static libraries made it less feasible for this kind of setup when using CocoaPods. In general, your best bet for distribution is using <https://github.com/cocoapods/cocoapods-packager>

**Comment by ploddi** [comment]
Great! Thank for tip.
