### ISSUE TITLE
Default Podfile summary and description fields

### ISSUE THREAD

**Issue by daveverwer** [CocoaPods/CocoaPods#3883]
I wanted to just start a discussion about this really before even thinking about writing any code or making any changes.

I spend a fait bit of time looking through new pods and the number of times I see this is quite surprising:

![default-description](https://cloud.githubusercontent.com/assets/5180/8870483/75a2b830-31e6-11e5-82b2-d7e282cff106.png)

I'd like to write a small patch to reduce the chances of this happening. If the default text for the summary and description fields generated by pod create were to be moved to be comments above the fields rather than the content of the fields that it would force people to put at least a little thought into what they were submitting.

Lint doesn't allow a blank summary, or a description which is shorter than the summary so it would *force* user written responses to both those fields before a pod could be submitted.

I understand that the recent quality index changes will mean that those badly described pods will not get much visibility. However, think about it from the perspective of the pod author. If they took the time to create a podspec, that's a step they took to make their code available or give it some visibility. Allowing these boilerplate fields to be submitted means that the path of least resistance is simply not to do anything and they hurt their pod before it even gets started.

Thoughts?

**Comment by neonichu** [comment]
There's already a warning for not touching the `summary`:

```bash
- WARN  | The summary is not meaningful.
```

But it definitely makes sense to me to decrease the likelihood of people submitting a bogus description.

**Comment by orta** [comment]
It could be worth turning that into a legit failure if we find that it still is basically the default text?

**Comment by daveverwer** [comment]
OK so here's a proposal for a fix. I can see why you might not like this as you don't really use comments outside the header comment blocks but I felt it worked better just above the description field. I'm willing to modify it if you'd prefer a different style though. One small problem might be that it's less obvious that the DESC delimiters are needed now and people unfamiliar with Ruby might remove them and get errors. I've added a note in the comment about to try and help with this.

@orta I considered adding a failure for a default description. However, you do see see specs with very minimal changes to the default text (something added at the top, for example) which could then pass lint but still be confusing to people. I think the key thing here is that the default text is being used as documentation and would be better as a comment.

I also think that a warning is the correct error level for leaving the default description (even after this change, when it's blank). As a spec author if you decide that you want no description that's OK (well, kinda 😃). I believe no description is better than boilerplate text because at least it doesn't look like is a description.
