### ISSUE TITLE
Alot of new errors after 0.38.1

### ISSUE THREAD

**Issue by arbitur** [CocoaPods/CocoaPods#3884]
<img width="948" alt="skarmavbild 2015-07-24 kl 11 41 54" src="https://cloud.githubusercontent.com/assets/1361280/8871886/087db79c-31f9-11e5-83c8-1f7be6d77ebb.png">

My podfile:

    platform :ios, "7.1"

    pod "Mapbox-iOS-SDK", "1.6.0"
    pod "Braintree"

I only get these error when trying to load them in my bridging header.

It worked before I updated `gem install cocoapods` from 0.38.0 to 0.38.1 and `pod update`.

**Comment by neonichu** [comment]
The changes in #3878 are probably causing this.

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/pull/3898.
