### ISSUE TITLE
0.38.1: Linker errors due to incompatible semver versions

### ISSUE THREAD

**Issue by flufff42** [CocoaPods/CocoaPods#3887]
As of version 0.38.1 I am encountering issues with pods that have semantic versioning compliant versions which do not match the linker's rule for library versions.

```
ld: malformed 64-bit a.b.c.d.e version number: 2.5.3.16-xx-b
```

Since https://guides.cocoapods.org/syntax/podspec.html specifies that `version` supports [semantic versioning](semver.org) I believe this is a regression.

This appears to be caused by using

```
DYLIB_CURRENT_VERSION = $(CURRENT_PROJECT_VERSION)
```

for the framework targets in the Pods project, however this appears to have been around for a while, so I believe this may be caused by another change in 0.38.1.

**Comment by flufff42** [comment]
Workaround: Manually adjust versions the linker complains about in the pods project. This of course only persists until the next operation which updates this.

**Comment by segiddins** [comment]
@mrackwitz can you look into this one?

**Comment by keith** [comment]
I see a similar error when including `SocketRocket` as a dependency of `libPusher`

```
ld: malformed 32-bit x.y.z version number: 0.3.1-beta2
```

**Comment by alloy** [comment]
@mrackwitz I guess we’ll just have to no include prerelease information and also test that `u.v.w.x.y.z` also works and not just 3 components.

**Comment by neonichu** [comment]
Just to clear up any possible confusion: while this commit was indeed older, it has only recently made its way into master via #3802 — that's why this issue is only present with 0.38.1

**Comment by neonichu** [comment]
> 3 components leads to a warning:

```bash
$ clang -current_version 1.2.3.4 -dynamiclib yolo.c 
ld: warning: truncating -current_version to fit in 32-bit space used by old mach-o format
```

**Comment by neonichu** [comment]
Looking at the Specs repo, we also support funny things like "2.0beta4". Made [this gist](https://gist.github.com/neonichu/9dc92a545d30c9ee03d1) with a full list of versions which break.

**Comment by segiddins** [comment]
I think we can always just set it to `major.minor.patch`

**Comment by neonichu** [comment]
Generally, yes, but apparently `Pod::Version` allows `patch` to be a string:

```ruby
irb(main):002:0> v = Pod::Version.new('3.0.beta.15')
=> <Pod::Version version=3.0.beta.15>
irb(main):003:0> p v.patch
"beta"
```

**Comment by segiddins** [comment]
@neonichu in that case I'll fix `Pod::Version` to ensure that `major`, `minor`, and `patch` all return numbers
