### ISSUE TITLE
0.38.1 Compilation Issues

### ISSUE THREAD

**Issue by czechboy0** [CocoaPods/CocoaPods#3888]
Same as other reported issues, 0.38.1 completely broke our build, see:

<img width="409" alt="screenshot 2015-07-24 14 02 52" src="https://cloud.githubusercontent.com/assets/2182121/8874900/12bfaab2-320d-11e5-9d95-27009f2185c5.png">

**Comment by tommeier** [comment]
Also seeing compilation issues from sub pods (`CocoaHTTPServer`) when using the latest `CocoaLumberjack` dependency. (https://github.com/robbiehanson/CocoaHTTPServer/pull/141 - raising on a warning that wasn't seen in 0.38.0)

**Comment by perotinus** [comment]
Is this with ```use_frameworks!``` ? I tested this locally using the Avro-C pod with 0.38.1 and didn't see these compilation failures. What does your ```Podfile``` look like?

**Comment by czechboy0** [comment]
No, it's an Objective-C project, no Swift, no `use_frameworks!`. It's a private Podfile, I can't share that, but it's a dependency of another pod we have.

**Comment by neonichu** [comment]
The changes in #3878 are probably causing this.

**Comment by sguillope** [comment]
Having the same problem here but with RestKit. See https://github.com/RestKit/RestKit/issues/2251

**Comment by perotinus** [comment]
I was able to replicate the issue with Arvo-C. It looks like it ```jansson.h``` calls ```#import <jansson_config.h>```, which makes the module generation/lookup code go all screwy. When it changed that to ```#import <jansson/jansson_config.h>```, it compiled correctly. I'm not quite sure what causes Xcode to find the file and follow the module tree like that, though.

It seems like automatic static library module creation is more complicated than it looks. :\

**Comment by perotinus** [comment]
I cannot, however, replicate the issue with RestKit -- it builds fine both with and without ```use_frameworks!```.

From the errors, it looks like the RestKit issue is different.

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/pull/3898.
