### ISSUE TITLE
Cocoapods 0.38.1 failed to create valid Archive.

### ISSUE THREAD

**Issue by rckoenes** [CocoaPods/CocoaPods#3889]
Since updating to cocoapods 0.38.1 I can't archive my app any more. It runs fine on the simulator and device. But when I archive my app it create a `Generic Xcode Archive` and not the expected `iOS app archive`.

I've looked all over and found that you should set the Skip install to yes on any sub project, which was set correctly. Als the main project has is set to NO.

The only difference I can see in the archive is an added directory:
![screen shot 2015-07-24 at 15 11 01](https://cloud.githubusercontent.com/assets/277766/8874999/3adcfab4-3216-11e5-8240-ea2130c8e169.png)

This was never there and I can't find where is coming, Here is my Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

workspace 'MyApp.xcworkspace'

xcodeproj 'MyApp/MyApp.xcodeproj'
xcodeproj 'MyAppSDK/MyAppSDK.xcodeproj'

target :MyAppSDK, :exclusive => true  do
    link_with 'MyAppSDK'
    xcodeproj 'MyAppSDK/MyAppSDK.xcodeproj'
    
    pod 'AFNetworking'
    pod 'AFOAuth2Manager'
end

target :MyAppSDKTests, :exclusive => true  do
    xcodeproj 'MyAppSDK/MyAppSDK.xcodeproj'
end

target :MyApp, :exclusive => true do
    link_with ['MyApp', 'MyApp Test Live', 'MyApp Development', 'MyApp Test', 'MyApp Development-cal']
    xcodeproj 'MyApp/MyApp.xcodeproj'
    
    pod 'AFNetworking'
    pod 'AFOAuth2Manager'
    
	pod 'SVProgressHUD'
    pod 'TTTAttributedLabel'
    pod 'DTFoundation/UIKit_BlocksAdditions'
    pod 'Masonry'
    
    pod 'UrbanAirship-iOS-SDK'
    pod 'GoogleAnalytics'
    
end

target :MyAppTests, :exclusive => true do
    xcodeproj 'MyAppp/MyApp.xcodeproj'
    link_with 'MyAppTests'
    
    pod 'OCMockito'
end
```
(Xcode 6.4 on Yosemite)

**Comment by neonichu** [comment]
Seems like the umbrella headers created by #3878 are actually being installed into the build product.

**Comment by rounak** [comment]
I've been facing the same issue as well.

**Comment by pepibumur** [comment]
I'm affected as well!

**Comment by burakkilic** [comment]
+1 , I am also affected

**Comment by rishabhtayal** [comment]
+1, Having the same issue.

**Comment by segiddins** [comment]
closed by https://github.com/CocoaPods/CocoaPods/pull/3898.

**Comment by nebiros** [comment]
Thank you for fixing this, <3

**Comment by rishabhtayal** [comment]
Thanks for fixing. Works now.

**Comment by pepibumur** [comment]
Thanks :)

**Comment by georgbachmann** [comment]
Is there something I am missing? I still have the problem. Used 0.38.2 which didn't work and the latest 0.39 beta4 is also not helping :( And I am pretty lost. Can't submit my app cause I can't get a valid iOS archive. Compiling directly onto my device works properly, but archiving doesn't :(

I already removed all pods and let it create a new project for me again... also no luck...
Any help is so much appreciated!

**Comment by rckoenes** [comment]
Yep I'm still having the issue.

**Comment by 4tapsmobile** [comment]
Confirmed that 0.38.2 did not create a valid archive for me either.

**Comment by Dids** [comment]
Even 0.39.0.beta.4 is broken. :(

**Comment by Dids** [comment]
I can confirm that this fixed it for me:
https://github.com/CocoaPods/CocoaPods/issues/4119#issuecomment-137169818

I did have to remember to remove the path from both private and public header search paths, and for all the pods, plus I also removed any derived data and cleaned the project.

**Comment by chasing** [comment]
Seeing some issue relating to this, as well.

**Comment by ryanmeisters** [comment]
I had this issue as well. My last `pod install` was with Cocoapods 0.38.2. A simple `pod install` with Cocoapods 0.39.0 seems to have fixed the problem.
