### ISSUE TITLE
Semver linker differences

### ISSUE THREAD

**Issue by ashfurrow** [CocoaPods/CocoaPods#3892]
Having trouble installing prerelease software with 0.38.1.

It looks like CocoaPods introduced the feature of setting the pod version as the lib version: https://github.com/CocoaPods/CocoaPods/pull/3802 This seems like a good idea, unless your pod uses the [beta semver format](http://semver.org/spec/v1.0.0-beta.html) like [Reactive Cocoa 3.0.0-beta.6](https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/3.0-beta.6/ReactiveCocoa.podspec.json). When using CocoaPods 0.38.1, I get the following linker error:

```
 ld: malformed 64-bit a.b.c.d.e version number: 3.0-beta.6 
```

It looks like the linker wants a strict version number format that's not compatible with the semver pre-release format. 

Maybe CocoaPods could sanitize the version number?

**Comment by keith** [comment]
Related: https://github.com/CocoaPods/CocoaPods/issues/3887

**Comment by ashfurrow** [comment]
Ha, whoops. I swear _I did_ actually look to see if this had been reported yet.

**Comment by alloy** [comment]
Dupey dupe.
