### ISSUE TITLE
0.38.1 creates invalid xcconfig yielding "Cannot specify -o when generating multiple output files"

### ISSUE THREAD

**Issue by russbishop** [CocoaPods/CocoaPods#3893]
It generates them with a missing space between the `-iquote` and `-isystem` sets of parameters:

`OTHER_CFLAGS = $(inherited) "$CONFIGURATION_BUILD_DIR/libextobjc.framework/Headers"-isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/GoogleConversionTracking" 
`

This results in `Cannot specify -o when generating multiple output files` errors from clang.

Manually editing the `Pods.xcconfig` (and any others) and inserting the missing space fixes the errors.

**Comment by russbishop** [comment]
Could this be due to commit ec2b020a9e01c8, where it does this:

```
@@ -103,9 +102,15 @@ def generate_settings_to_import_pod_targets
+            if pod_targets.any? { |t| !t.should_build? }
+              # Make library headers discoverale by `#import "…"`
+              library_header_search_paths = target.sandbox.public_headers.search_paths(target.platform)
+              build_settings['HEADER_SEARCH_PATHS'] = XCConfigHelper.quote(library_header_search_paths)
+              build_settings['OTHER_CFLAGS'] += XCConfigHelper.quote(library_header_search_paths, '-isystem')
+            end
```

I'm not a Ruby expert but does that not just smash the strings together with no spaces?

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb#L112 probably just needs a space there, if you could make a PR!

**Comment by russbishop** [comment]
@segiddins Will do

**Comment by russbishop** [comment]
@segiddins Opened PR https://github.com/CocoaPods/CocoaPods/pull/3896

**Comment by segiddins** [comment]
Thanks @russbishop !

**Comment by damianesteban** [comment]
I'm having this same issue
