### ISSUE TITLE
0.38.1 - Erro when set 'OTHER_LDFLAGS' => '-lc++',

### ISSUE THREAD

**Issue by prsolucoes** [CocoaPods/CocoaPods#3894]
Hi,

After update to cocoapods 0.38.1, we are getting error in pods that have the line:
```'OTHER_LDFLAGS' => '-lc++'```

The projects are created without this parameter(i checked it verifying diff between the two projects). When i use cocoapods 0.38.0 it is working nice. What the problem with cocoapods 0.38.1 when set this parameter?

The pods with error is:
https://github.com/AlexDenisov/iActiveRecord

The pod file with error is:
https://github.com/AlexDenisov/iActiveRecord/blob/master/iActiveRecord.podspec

Thanks.

**Comment by neonichu** [comment]
Unfortunately, I can't reproduce this with a simple project using iActiveRecord, so we will need more information. Please give us the actual error you're seeing, the Podfile or ideally an example project which exhibits the issue.

**Comment by segiddins** [comment]
Also, can you verify if the issue is still present in 0.38.2?

**Comment by neonichu** [comment]
@prsolucoes closing for now, we can reopen if you give us the necessary information to reproduce.
