### ISSUE TITLE
Cocoa pods 0.38.1 Apple LLVM 6.1 Error cannot specify -o when generating multiple output files

### ISSUE THREAD

**Issue by codywinton** [CocoaPods/CocoaPods#3897]
I'm trying to archive my project for upload to the App Store. I'm using `platform :ios, '8.0'` and
`use_frameworks!`

I'm getting an error for framework `Pods-ProjectTarget`:

`Apple LLVM 6.1 Error`
`Cannot specify -o when generating multiple output files`

What's going on? I was also trying to archive with v 0.38.0

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/CocoaPods/pull/3896

**Comment by codywinton** [comment]
@segiddins Ok, thanks.

**Comment by segiddins** [comment]
The fix for this has now been merged to master.

**Comment by pepibumur** [comment]
Thanks for the fix @segiddins
