### ISSUE TITLE
No Public Headers in Pods folder 

### ISSUE THREAD

**Issue by cpage13** [CocoaPods/CocoaPods#3902]
Hi

I have updated to version 0.38.1 from 0.38.0. I kept receiving errors bundle at MainApp.app/Plugins/TodayExtension.app contains disallowed nested bundles and MainApp.app/Plugins/TodayExtension.app contains disallowed file Frameworks while attempting to submit the app to the store. I thought the update may address the issue. Now I cannot even compile the project.

Podfile setup

link_with 'MainApp', 'MyTodayExtension'
platform :ios, '8.0'
use_frameworks!

def shared_pods
    pod 'SomePod', '~> 2.2.0'
end

target 'MainAppTests' do
end

target 'MainApp' do
    shared_pods
end

target 'MyTodayExtension' do
    shared_pods
end

I ran pod install, deleted my Derived Data and tried compiling the project again.
I get clang error no such file or directory MainAppDir/Pods/Headers/Public

Only the Private folder is generated. The headers search paths for both require the public directory.

HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Public"  from Pods-MyTodayExtension.xcconfig

 Edit : 

Note this error occurs while compiling the dummy file. If I just mkdir Headers/Public I get a new error (clang: error: cannot specify -o when generating multiple output files)

**Comment by neonichu** [comment]
Could you please retry this with 0.38.2? 

If there's still an issue, please add more information. Since you redacted all pods you are using, it's going to be hard to reproduce.

**Comment by cpage13** [comment]
Thanks! 0.38.2 fixed it 

I apologize. I was just trying to keep the issue concise. In the future I will be sure to add the pods used. I have posted it below in case it could be useful to others. I still have the issue trying to submit the app to the store, but not really sure if that is a cocoa pods problem. Will post it separately.

use_frameworks!
link_with 'MainApp', 'TodayWidget' 
platform :ios, '8.0'

def shared_pods
    pod 'SwiftyJSON', '~> 2.2.0'
    pod 'Argo'
    pod 'Firebase', '>= 2.1.2'
    pod "CocoaAsyncSocket", ">= 7.4.1"
    pod 'SWXMLHash', '~> 1.0.0'
    pod 'GBPing', :git => 'https://github.com/cpage13/GBPing.git'
end

target 'MainApp' do
    shared_pods
    pod "AFNetworking", "~> 2.0"
    pod 'SDWebImage', '~>3.7'
    pod 'IQKeyboardManager'
end

target 'TodayWidget' do
    shared_pods

end




l

**Comment by joshuatbrown** [comment]
I seem to be having this same issue with CocoaPods 0.38.2. When I run `pod install` or `pod update`, my public headers get deleted.
