### ISSUE TITLE
0.38.2 Pods directory has 0777 permissions

### ISSUE THREAD

**Issue by keith** [CocoaPods/CocoaPods#3904]
After running `pod install` with 0.38.2 all the directories in the Pods directory now have 0777 permissions. Based on the changelog I assume this was a side effect of https://github.com/CocoaPods/CocoaPods/pull/3900

It also looks like files still have read and write permissions, which it doesn't seem like they should.

**Comment by segiddins** [comment]
Do source files still have write permissions? If so, that's a real bug.

**Comment by keith** [comment]
Yes files do

**Comment by neonichu** [comment]
Also the Pods directory should have 755 permissions.

**Comment by oysta** [comment]
The fix appears to be to change line 117 of `lib/cocoapods/installer.rb` to

    FileUtils.chmod_R(‘u+w', sandbox.root)

Original change is in 8f15a9bcc9a696f02a6097b6c7046d0b7b41b632 as #3900

This won’t fix existing `Pods` directories that have been affected by this though, and I’m not sure what the standard CocoaPods policy is about trying to repair things like this.

**Comment by segiddins** [comment]
This should now be fixed on `master`.

**Comment by 0xced** [comment]
Will it also fix "damaged" Pods directories with 0777 permissions?

**Comment by segiddins** [comment]
No.

**Comment by 0xced** [comment]
So maybe we should add en entry in the changelog explaining how to restore proper permissions before running CocoaPods 0.38.3? Would this fix the issue? `find Pods -exec chmod og-w {} \;`

**Comment by segiddins** [comment]
Well I presume if people actually have issues, they'll just nuke the `Pods` directory and re-install?
