### ISSUE TITLE
Unable to Submit Build to appstore

### ISSUE THREAD

**Issue by cpage13** [CocoaPods/CocoaPods#3905]
I am trying to submit my app to the store, however I get two errors while doing so.

ERROR ITMS-90205: "Invalid Bundle. The bundle at 'xxx Extension.appex' contains disallowed nested bundles."

ERROR ITMS-90206: "Invalid Bundle. The bundle at 'xxx Extension.appex' contains disallowed file 'Frameworks'."

To remedy the error I have to open the app archive and delete the Framewoks folder for the Extension.

rm -rf ./Products/Applications/MainApp.app/PlugIns/Extension.appex/Frameworks.

I am not sure if it is cocoa pods adding the Frameworks to the directory. It appears to be the case because this  file
"${SRCROOT}/Pods/Target Support Files/Pods-QuickView/Pods-Extension-frameworks.sh"

is executed in the Embed Pods Frameworks step. The scripts copies all of the frameworks to the app bundle. Should the frameworks be copied for a Distribution build?

**Comment by neonichu** [comment]
I am assuming you're using the same podspec from #3902?

**Comment by cpage13** [comment]
Yes, that is correct. 

use_frameworks!
link_with 'MainApp', 'TodayWidget' 
platform :ios, '8.0'

def shared_pods
    pod 'SwiftyJSON', '~> 2.2.0'
    pod 'Argo'
    pod 'Firebase', '>= 2.1.2'
    pod "CocoaAsyncSocket", ">= 7.4.1"
    pod 'SWXMLHash', '~> 1.0.0'
    pod 'GBPing', :git => 'https://github.com/cpage13/GBPing.git'
end

target 'MainApp' do
    shared_pods
    pod "AFNetworking", "~> 2.0"
    pod 'SDWebImage', '~>3.7'
    pod 'IQKeyboardManager'
end

target 'TodayWidget' do
    shared_pods

end

**Comment by mrackwitz** [comment]
Do you remember which version of CocoaPods you used to originally setup the integration using frameworks with your extension? You may have the embed frameworks build phase for your extension historically because it was created by older versions. (< 0.37.1) To fix this issue, please just delete the embed frameworks build phase from your extension.

**Comment by OliverZiegler** [comment]
Had this same error with cocoa pods 1.0.1
Even after deintegrating cocoapods , deleting all cocoapods build phases and reintegrating with `pod install` I had the build phase @mrackwitz claims to delete readded to my project.

Is there another specific fix/workaround for cocoapods 1.0.1?

**Comment by timgcarlson** [comment]
Also having the same problem in 1.0.1. Why is is this still a problem and is there any known way to fix this? I've used added the build script to remove frameworks to no avail.

    cd "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/"
    if [[ -d "Frameworks" ]]; then
       rm -fr Frameworks
    fi

**Comment by dnasello** [comment]
This saved the day
http://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr

**Comment by Radhika-Geek** [comment]
@timgcarlson If we delete framework folder. then how we can use all these frameworks inside that folder.
