### ISSUE TITLE
pod_target_xcconfig ends up applied to aggregate target

### ISSUE THREAD

**Issue by pixelglow** [CocoaPods/CocoaPods#3906]
In the [Podspec Syntax Reference](https://guides.cocoapods.org/syntax/podspec.html#pod_target_xcconfig), the `pod_target_xcconfig` setting is documented as applying only to the private pod target `xcconfig` file, but ends up applying to the aggregate/project target as well.

Steps to reproduce:
* Create a Xcode iOS project (6.3 or later).
* Use the following podfile in the project directory:
```
platform :ios, '8.0'
pod 'zipzap'
```
* Run `pod install` from that directory.
* Open the new `xcworkspace` file.
* Note that the created `Pods.debug.xcconfig` and `Pods.release.xcconfig` files contain `CLANG_CXX_LANGUAGE_STANDARD=c++11`, `OTHER_CPLUSPLUSFLAGS=-fno-exceptions` etc. and the project uses these configurations.
* Note that in the [current zipzap podspec](/CocoaPods/Specs/blob/fc990092b33bb10ba498668e9f7c93815ce19ba8/Specs/zipzap/8.0.4/zipzap.podspec.json), these flags are found in the `pod_target_xcconfig` setting and nowhere else.

Reference: pixelglow/ZipZap#105

Versions: Xcode 6.3.2, CocoaPods 0.38.2, ZipZap 8.0.4

**Comment by segiddins** [comment]
@mrackwitz this seems to be caused by https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb#L143, which would mean that any non-framework targets don't actually see separation of xcconfigs.
