### ISSUE TITLE
Read only source files causing permission issues when building framework

### ISSUE THREAD

**Issue by kand617** [CocoaPods/CocoaPods#3909]
Hi guys,

We are currently building a framework from an xcode project that has pod dependencies. 
As part of the build process we copy public headers from pod libraries. 
However in a recent update this seems to result in permission errors since header files have ready only. 
This is a following snippet the would be called in the build phase. 
````
# Copy the public headers into the framework
/bin/cp -r "${PODS_ROOT}/Headers/Public/JSONModel/" \
"${FRAMEWORK_LOCN}/Versions/A/Headers"
````

I have attached the project for reproducing the scenario. 
https://www.dropbox.com/s/noqefo4wtnj71ac/calculatorCocoaPods.zip?dl=1

**Comment by segiddins** [comment]
Is this still an issue for you on 0.38.2?

**Comment by kand617** [comment]
Sorry, I gave the wrong file. 
Please check the source code now.

**Comment by kand617** [comment]
actually, its seems to be fixed in the new one. 
odd. Sorry I thought I tested in the new version. 

Sorry for the trouble

**Comment by kand617** [comment]
Hi, 
It seems to be fixed. 

Thank you.
