### ISSUE TITLE
Error validating private pod when there's an embedded library

### ISSUE THREAD

**Issue by LightD** [CocoaPods/CocoaPods#3911]
Hi, so I'm trying to build a private framework for the app I'm working on, and when I try to execute: `pod repo --allow-warnings push APISpec APISpec.podspec --verbose` I get an error that `no such module  ReactiveCocoa`, keep in mind that I downloaded the latest reactive cocoa swift framework and embedded it in my code, and the code compiles perfectly fine in XCode, but it doesn't when I try to `pod repo push`.. this could've been any library, that is no integrated through cocoapods.. any solution to this? or a work around or smthn?

**Comment by neonichu** [comment]
With that amount of information, it's impossible to judge what is going on. How did you embed it? How does your podspec look like?

**Comment by LightD** [comment]
fair enough..
1. I added the framework (with copy files if needed), and then added a new `Copy Files Phase` under `Build Phases`, and set it to frameworks and added `ReactiveCocoa` and it's dependencies there. and used it in my project and all runs nicely and all.
2. here's my podspec file:
``` ruby
Pod::Spec.new do |s|
  s.name             = "APISpec"
  s.version          = "0.1.1"
  s.summary          = "The API repo my project."
  s.description      = <<-DESC
                        The API framework of project awesome app!
                       DESC
  s.homepage         = "https://github.com/actual private repo URL here"
  s.license          = 'MIT'
  s.author           = { "Light Dream" => "nourforgive@gmail.com" }
  s.source           = { :git => "https://github.com/ actual private repo URL here" }
  s.platform     = :ios, '8.0'
  s.requires_arc = true
  s.source_files = 'APISpec/*'

  s.dependency 'Alamofire'
  s.dependency 'ObjectMapper'
  s.dependency 'CryptoSwift'
  s.dependency 'Valet'
  s.dependency 'SwiftyUserDefaults'
end

```

and here's the terminal run:
`pod repo --allow-warnings push project-specs ~/Development/project/ios-API/APISpec.podspec --verbose`, with the following errors:
``` 
 BookyaAPI (0.1.1)
    - WARN  | Git sources should specify a tag.
    - WARN  | Github repositories should end in `.git`.
    - WARN  | The URL (https://github.com/bookyacom/actual private repo URL here) is not reachable.
    - ERROR | [iOS] Returned an unsuccessful exit code.
    - WARN  |  CryptoSwift/CryptoSwift/IntExtension.swift:39:16: warning: 'integerWithBytes' was deprecated in * version 0.8
    - WARN  |  CryptoSwift/CryptoSwift/UInt32Extension.swift:23:16: warning: 'integerWithBytes' was deprecated in * version 0.8
    - WARN  |  CryptoSwift/CryptoSwift/UInt64Extension.swift:23:16: warning: 'integerWithBytes' was deprecated in * version 0.8
    - ERROR |  APISpec/APISpec/MyAuthenticator.swift:11:8: error: no such module 'ReactiveCocoa'

```

keeping in mind that when the project was clean, without any dependencies or whatever, it was deployed without any errors!

Thanks in advance for the help @neonichu

**Comment by neonichu** [comment]
I think you're misunderstanding how a podspec works, it knows nothing about your Xcode project. So, as your podspec doesn't reference anything ReactiveCocoa-related, it cannot be found. 

You should add ReactiveCocoa as a regular dependency or alternatively add a prebuilt version of it and its dependencies as a `vendored_framework` if that's necessary for some reason.

**Comment by LightD** [comment]
Hmmm.. I'm sorry, but the information/tutorials available about this things are not a lot, and not really clear, so there was a lot of speculations.. As an embedded framework I thought it would be build the framework and integrate in the code and then cocoapods would just run build command..
I tried listing it as an explicit dependency, and it's trying to install V2.5, whereas I want the first candidate release, which is why I installed it as a framework.. how can I tell cocoapods to take the installed framework from the project? or how do I use `vendored_framework`?

**Comment by neonichu** [comment]
I believe <https://guides.cocoapods.org/making/making-a-cocoapod.html> is what you want. There's also a syntax reference. You can check out [this](https://github.com/ashfurrow/Moya/blob/master/Moya.podspec#L35) to see how to reference a prerelease of RAC.
