### ISSUE TITLE
pod repo push should support --sources option

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#3912]
We have a Pod named "Facade" internally which conflicts with the one published on master repo (found here https://cocoapods.org/pods/Facade).

Doing `lint` with `--sources` and specifying our internal repo first, the build is successful, however, doing ` repo push` CocoaPods resolve the one on the master repo instead of the internal one.

There should be the same option available for `repo push` to avoid this problem.

**Comment by segiddins** [comment]
`pod repo push` automatically uses all repos available on the machine

**Comment by dnkoutso** [comment]
Yeah but the order of resolution should matter.

**Comment by segiddins** [comment]
Sure, a pull request to add the CLI option would be awesome

**Comment by dnkoutso** [comment]
@segiddins I got a working fix for this. However, would you prefer if the command receives `--sources` or if we just re-order master repo to be at the bottom?

**Comment by segiddins** [comment]
`--sources` would be great!

**Comment by dnkoutso** [comment]
Excellent PR coming up.

**Comment by segiddins** [comment]
<3
