### ISSUE TITLE
Vendored "static framework" not working in combination with use_frameworks!

### ISSUE THREAD

**Issue by tonyarnold** [CocoaPods/CocoaPods#3917]
I've noticed that enabling `use_frameworks!` is causing the Reveal SDK not to load. Commenting it out, and re-running `pod update` makes everything function as expected. 

Any ideas as to what's causing this, and how I can work around the problem? I've attached [a sample project demonstrating the issue](https://dl.dropboxusercontent.com/u/153352/VendoredStaticLibraryTest.zip).

The expectation is that when the Reveal iOS SDK is properly linked to an app, it will print something akin to the following to Xcode's console:

```
2015-07-28 08:47:49.791 VendoredStaticLibraryTest[20114:2081743]  INFO: Reveal Server started (Protocol Version 18).
```

**Comment by segiddins** [comment]
@tonyarnold what version of CocoaPods are you using?

**Comment by segiddins** [comment]
(I'm guessing this will be fixed by https://github.com/CocoaPods/CocoaPods/pull/3832/files#diff-0c367d31dd76a0d7160f4510bf6b227fL53)

**Comment by tonyarnold** [comment]
@segiddins I'm using:

```
$ pod --version
0.38.2
```

**Comment by kylef** [comment]
@tonyarnold Would you be able to test out #3832 and check if it solves your problem?

**Comment by tonyarnold** [comment]
Sure thing @kylef — is there a quick guide to running CP from source? I've never had to do that before!

**Comment by orta** [comment]
https://guides.cocoapods.org/contributing/dev-environment.html

but I'd recommend [a Gemfile](https://guides.cocoapods.org/using/a-gemfile.html).

**Comment by tonyarnold** [comment]
Brilliant and simple, thanks O-man!

**Comment by nsforge** [comment]
Just noticed this same issue with `0.38.2`. @tonyarnold did you get a chance to test that PR, or one of the `0.39.0` betas?

**Comment by nsforge** [comment]
I have tested `0.39.0.beta.4`, and it has resolved this issue for me.

**Comment by tonyarnold** [comment]
Yeah, sorry guys I have not checked this yet. @nsforge was it Reveal you were checking with? I'd be happy for the guys to take your success as verification.

**Comment by nsforge** [comment]
@tonyarnold yes, it was Reveal that I tested/verified with.

**Comment by tonyarnold** [comment]
Yeah, this is working now. Thanks guys!
