### ISSUE TITLE
How to know whether a pod exist after the environment header be removed in 0.38

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3923]
Before 0.38, I use below code to know whether a pod exists:
```
#ifdef COCOAPODS_POD_AVAILABLE_A_POD
#endif
```
I know I can use `has_include` to do it.
But if the pod is only for a debug configuration, the `has_include` always be true!

After 0.38, CP remove the environment header, and how should I do?

**Comment by amorde** [comment]
One way to do it is to check for the existence of a class within the pod

```Objective-C
if (NSClassFromString("AFHTTPClient")) {
    // AFNetworking is available
}
```
This does, however, move the check to runtime.

Another option is to use the `__has_include` preprocessor macro, as seen [here](https://github.com/RestKit/RestKit/blob/development/Code/Network/RKObjectManager.m#L41)

**Comment by Whirlwind** [comment]
@amorde 
Thanks for your reply.

But, your way is not good ways.

The first way, if I use runtime to coding, I think it is very hard!

```
if (NSClassFromString("AFHTTPClient")) {
     // How to call a class method without compiler error?
     // How to call a method and compiler can analyze it (not id)?
}
```

The second way, if I use a pod for a configuration:
```
pod "NSLogger", :configurations=>"Debug"
```

Under `Release` configuration, the `NSLogger.h` can be searched, and the `__has_include` return true!!!

**Comment by amorde** [comment]
```
How to call a method and compiler can analyze it (not id)?
```
Even with the environment header, if the pod did not exist you did not get any auto completion / compiler analysis. 

As it stand now, the header has been removed so you will need to find another solution to your issue

**Comment by Whirlwind** [comment]
```
Even with the environment header, if the pod did not exist you did not get any auto completion / compiler analysis.

```
NO! With the environment header, I will got auto completion when the pod exists, and the compiler will skip the code without error when the pod NOT exists.
```
#ifdef COCOAPODS_POD_AVAILABLE_NSLOGGER
// if the pod not exists, these code will not be complied.
// if the pod exists, we will get autocompletion.
#endif
```

**Comment by amorde** [comment]
Skipping the code still means you don't get auto completion and analysis, does it not?

**Comment by Whirlwind** [comment]
yeah, but the pod is Only for DEBUG configuration, so it exists when I write the code!

**Comment by amorde** [comment]
Why not just wrap the code in `#ifdef DEBUG` then?

**Comment by Whirlwind** [comment]
It is just a example. :(

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
