### ISSUE TITLE
0.38.2 use_frameworks! still fails to archive properly

### ISSUE THREAD

**Issue by codywinton** [CocoaPods/CocoaPods#3924]
0.38.2 `use_frameworks!` still fails to archive properly. The archive doesn't automatically show up and when I try to open the archive I get the this message: `The archive may be corrupt or unreadable`

**Comment by segiddins** [comment]
Can you please share a project that reproduces the issue, as this isn't enough detail to go on to fix anything? Thanks!

**Comment by codywinton** [comment]
@segiddins Sorry for the delay. Here's a test project with basically the exact podfile I'm using in my project: https://github.com/codywinton/CocoapodFrameworks

Using Cocoapods 0.38.2, I still am unable to archive the project successfully.

**Comment by nubbel** [comment]
:+1:

**Comment by codywinton** [comment]
@nubbel - Except my project fails to archive in Xcode 6.4

**Comment by codywinton** [comment]
Any updates on this?

**Comment by segiddins** [comment]
No, haven't had a chance to look into it yet

**Comment by prnewman** [comment]
I'm having the same issue. My team has spent the entire week trying to resolve this as we are unable to submit to App Store.

**Comment by brentleyjones** [comment]
We turned off `use_frameworks!` in order to submit. Haven't turned it back on yet because of this.

**Comment by segiddins** [comment]
Please open a new issue detailing the problems y'all are seeing, as this one is closed (and confirm that the issue is still present in 0.39.0.beta.4)
