### ISSUE TITLE
Linting a podspec without explicit platform definitions fails on Xcode < 7.0

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/CocoaPods#3925]
```bash
[…]
    - ERROR | [watchOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [watchOS]  [BEROR]error: There is no SDK with the name or path 'watchos'
    - NOTE  | [watchOS]  error: There is no SDK with the name or path 'watchos'
[…]
```

This is because without any platform specification, a Pod is now automatically building for iOS, OS X and watchOS. Building for watchOS obviously fails on Xcodes which don't support it.

I'm marking this as discussion because the question is how to handle this:

1. Do nothing, Xcode 7 is gonna be the default for most people soon anyway
2. Improve the error, so that users will know to explicitly state platforms
3. Ignore watchOS build errors on older Xcodes — seems dangerous because people could easily ship broken Pods that way

**Comment by segiddins** [comment]
I'm torn between 1 and 2.

**Comment by segiddins** [comment]
Closing. We're going to go with #1 -- I much prefer people make things explicit to begin with.
