### ISSUE TITLE
Removing all dependencies from a target causes build to fail

### ISSUE THREAD

**Issue by amorde** [CocoaPods/CocoaPods#3927]
## Steps to reproduce

* Create new project
* Run `pod init`
* Add a single dependency to your Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TestEmptyTarget' do
    pod 'AFNetworking'
end

target 'TestEmptyTargetTests' do

end
```
* run `pod install` - Everything works as expected at this point
* Remove the dependency
```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TestEmptyTarget' do

end

target 'TestEmptyTargetTests' do

end
```
* Run `pod install`
* Attemping to build yields an error in Xcode:
`
/Users/eric.amorde/Library/Developer/Xcode/DerivedData/TestEmptyTarget-cjyankutwhmhricfwwjncpziwjes/Build/Intermediates/TestEmptyTarget.build/Debug-iphonesimulator/TestEmptyTarget.build/Script-9A7A63035C6B940FCE4008D7.sh: line 2: /Users/eric.amorde/Desktop/TestEmptyTarget/Pods/Target Support Files/Pods-TestEmptyTarget/Pods-TestEmptyTarget-resources.sh: No such file or directory
`

It appears the run script is not removed from the build sequence if the script no longer exists.

Tested on Cocoapods `v 0.38.2` and Xcode `6.4`

**Comment by segiddins** [comment]
Yup, this is a known issue, see https://github.com/CocoaPods/CocoaPods/issues/2471

**Comment by amorde** [comment]
Ah, okay didn't see that. I did not remove the target, however, I just don't have any pods at the moment. I ran into this when removing a pod from my test target which left it empty.

**Comment by amorde** [comment]
Also appears to be the same issue as #3617
