### ISSUE TITLE
Post_install can't find project property

### ISSUE THREAD

**Issue by Iyuna** [CocoaPods/CocoaPods#3928]
I have post_install section in podfile like this:
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        target.build_configurations.each do |config|
...
        end
    end
end
And with last cocoapods version (0.38.2) it doesn't work anymore. Fails with error:
[!] An error occurred while processing the post-install hook of the Podfile.
undefined method `project' for #<Pod::Installer:0x007fa9491c9d88>

**Comment by neonichu** [comment]
Yep, this is due to changes in the hooks API which you're using in your Podfile, see http://blog.cocoapods.org/CocoaPods-0.38/ for more information.
