### ISSUE TITLE
"Sending stats" takes long time on bad network

### ISSUE THREAD

**Issue by hfossli** [CocoaPods/CocoaPods#3929]
If I understand this right, this is a task which is not required for the user in order to use the workspace. Could it instead be async? On a slow network it feels really bad to have to wait for this to finish.

**Comment by neonichu** [comment]
Not sure if it can be, but there's always the opt-out via `COCOAPODS_DISABLE_STATS`.

cc @orta

**Comment by segiddins** [comment]
See https://github.com/CocoaPods/cocoapods-stats/issues/5 for some background

**Comment by esetnik** [comment]
I'm not sure if the stats collector is down right now, but I'm experiencing a similar issue where sending stats takes about 3 minutes to complete. It's not a big deal but it probably should have a timeout of 10s. I am not experiencing any other network issues at the moment.

**Comment by hfossli** [comment]
IMO timeout should be even lower (e.g. 5 seconds!).

**Comment by segiddins** [comment]
Feel free to make a PR to stats changing it

**Comment by tals** [comment]
Just got bitten by this. The request never completed for me.

I'm trying to get work done and Cocoapods suddenly decided to get in my way :(

**Comment by orta** [comment]
I agree that a timeout is a good idea :+1: 

Async is also a nice to have too, I can imagine it get complex with making sure it finishes before CocoaPods too. Again, would prefer this, stats really shouldn't get in the way.

**Comment by neonichu** [comment]
It seems quite excessive, because one can just quit CP if sending stats takes too long, right?

**Comment by segiddins** [comment]
@neonichu no, because the lockfile won't be written yet

**Comment by hfossli** [comment]
I don't understand what the policy is wrt closing issues. Isn't there concensius that this should be dealt with? At least a very simple oneline fix (low timeout)? I appeal to keep this open so that anyone wanting to contribute may contribute to this trivial (hopefully) fix.

**Comment by segiddins** [comment]
Async stats sending has already been merged into cocoapods-stats
