### ISSUE TITLE
pod spec lint doesn't pull from git if the source is already cached

### ISSUE THREAD

**Issue by ghost** [CocoaPods/CocoaPods#393]
I recently changed the directory structure of my Pod. That is, I moved things around and pushed them to GitHub, I also updated re-attached the tag accordingly. 

I then updated the podspec of that Pod to reflect the changes. However, the following: 

```
  `pod spec lint XXXX.podspec' 
```

failed with the following errors: 

```
  - ERROR | The sources did not match any file
  - ERROR | The resources did not match any file
  - ERROR | The preserve_paths did not match any file
```

I found out that lint doesn't really pull the source files from git because it finds a cached copy of the repo under ~/Library/caches/CocoaPods/Git/[HASH], however this cache was clearly no longer relevant as it held the old directory structure of the pod. 

Trying to work around this, I changed the version of the podspec, hoping that lint would pick up the change and generate a new hash, thus pulling the source again into the cache. It didn't. 

This is very confusing and I wonder if it is the desired behavior. If it is, it should be clearly documented under lint command notes, and an option should be given to _force_ pulling the source from git. 

If there is another way to go about this, please let me know.

**Comment by Juddster** [comment]
This just happened to me as well. I deleted the cached data (under External and Spec/External) and that allowed the pod spec lint to pass.
My scenario was similar to 100grams'. I kept fixing one issue after another (this was my first pod) and so I deleted and retagged newer commits with the same tag (0.1.0). It finally passed `pod lib lint` but then failed the `pod spec lint` with issues that I have fixed already. It was clearly a stale cache issue.
This is worth re-evaluating (unless of course it was addressed in v1.0. My pod is v0.39.0).

**Comment by tadija** [comment]
I had a same problem, `pod spec lint` failed, I fixed the error in code, made a push and tag again, but it kept failing until I manually removed cached files from `~/Library/Caches/CocoaPods/Pods`.
It would be nice to have something as a `--force` argument which would then override the local cache.

**Comment by segiddins** [comment]
https://guides.cocoapods.org/terminal/commands.html#pod_cache_clean

**Comment by tadija** [comment]
Thanks @segiddins, that's it! :)

**Comment by Juddster** [comment]
Thanks...!

**Comment by AlbertoMDieguez** [comment]
Thanks @segiddins, works for me!
