### ISSUE TITLE
How to generate different .a for different targets

### ISSUE THREAD

**Issue by Arthraim** [CocoaPods/CocoaPods#3934]
Might be my fault.

Say I have 2 targets in my project, one is 'MyApp' the other one is 'MyExtension'
I am using 0.38.2, and don't use frameworks. Cocoapods generates single one `libAFNetworking.a` for both of these 2 targets. How can I generate `libPods-MyApp-AFNetworking.a` and `libPods-MyExtension-AFNetworking`.

I have a image showing that some of my dependencies are separated, but some are not.
![image](https://cloud.githubusercontent.com/assets/133202/8979225/a45100e4-36da-11e5-96e1-47cf5bed5c17.png)

**Comment by neonichu** [comment]
This is due to target deduplication, see the [Changelog](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#highlighted-enhancement-that-needs-testing) on how to opt-out.

**Comment by Arthraim** [comment]
thanks! @neonichu
