### ISSUE TITLE
Improve error information to mention the root cause when failed to install pod because of platform version

### ISSUE THREAD

**Issue by pinxue** [CocoaPods/CocoaPods#3939]
Creating a pod in my private repo, it worked fine till I made some uncertain changes. Now running 'pod install' in Example will complain:
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `DataModel (from `../`)` required by `Podfile`
- `DataModel (from `../`)` required by `Podfile`
- `DataModel (= 0.1.0)` required by `Podfile.lock`

And eventually, I figured it out, it is caused by iOS platform version which I just modified to reflect truth of framework in bundle requires 8.0.
  s.platform     = :ios, '8.0'
It works like a charm when the version is 7.0 or 7.1 . Well, I just didn't give the iOS version in Podspec file. It will work with right iOS platform version, like:
platform :ios, '8.0'

The error information didn't mention platform version, it should have saved my day!

**Comment by segiddins** [comment]
Agreed! This is already being tracked over at https://github.com/CocoaPods/CocoaPods/issues/3926.
