### ISSUE TITLE
"Incompatible library version" after upgrading to 0.38.2

### ISSUE THREAD

**Issue by Jamonek** [CocoaPods/CocoaPods#3940]
```
dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: /private/var/mobile/Containers/Bundle/Application/16798DA4-216C-49FC-B3C7-9588C91AF9FC/Coded.app/Coded
  Reason: Incompatible library version: Coded requires version 4.0.0 or later, but FBSDKCoreKit provides version 1.0.0
```

When I upgraded to 0.38.2 and installed a pod, I ran into this issue when building and running the app on my iPhone. Any idea what changed?

**Comment by AndreiBoariu** [comment]
Hi, 

I already had troubles with this. Really really strange...
I tried on my side any possible way, and no success.

Finally, I created another folder, and cloned code in that folder. Run and worked... may be there were some relationships done incorectly, or no idea... 

Just try this one, and let me know!

**Comment by mr-seiler** [comment]
Possible dup of #3903

**Comment by segiddins** [comment]
Yup, dup of #3903.

**Comment by Jamonek** [comment]
@pronebird's fix helped slightly. I had to delete DerivedData folder for it to fully work.
