### ISSUE TITLE
Unable to find Spec

### ISSUE THREAD

**Issue by f2prateek** [CocoaPods/CocoaPods#3941]
After upgrading from CocoaPods 0.37.2 to 0.38.2; I've been seeing the following error.

```
[!] Unable to satisfy the following requirements:

- `MoEngage-iOS-SDK (= 1.6)` required by `Podfile`
- `MoEngage-iOS-SDK (= 1.6)` required by `Podfile`
```

<img width="1014" alt="screen shot 2015-07-30 at 7 54 27 pm" src="https://cloud.githubusercontent.com/assets/843979/8999875/0dc82ac4-36f5-11e5-8762-9609ad11714e.png">

I've verified that the library [does exist on CocoaPods](https://github.com/CocoaPods/Specs/blob/master/Specs/MoEngage-iOS-SDK/1.6/MoEngage-iOS-SDK.podspec.json), and is fetched on my computer (by running `cat ~/.cocoapods/repos/master/Specs/MoEngage-iOS-SDK/1.6/MoEngage-iOS-SDK.podspec.json`).

<img width="1440" alt="screen shot 2015-07-30 at 7 54 17 pm" src="https://cloud.githubusercontent.com/assets/843979/8999861/e635700c-36f4-11e5-964b-9734a6b5397b.png">

**Comment by segiddins** [comment]
I'm guessing the issue here is a platform mismatch?

**Comment by segiddins** [comment]
Closing due to lack of response.

**Comment by f2prateek** [comment]
@segiddins sorry I forgot to reply, the issue was indeed the platform mismatch. Thanks for pointing me in the right direction :)
