### ISSUE TITLE
`SDKROOT`-relative source files

### ISSUE THREAD

**Issue by stephencelis** [CocoaPods/CocoaPods#3942]
This may already be possible, but after looking at the guides and some of the CocoaPods source code I'm still unable to discover it.

Basic question: is there a way to add an `SDKROOT`-relative source file to a podspec? Currently, the best way to import non-modular SDK headers into Swift is to drag the current SDK header into your project (don't copy it), make it public, and import it into the umbrella header. Doing so adds a line to the **.xcodeproj** file relative to `SDKROOT`, _e.g._

```
55C030…051264D /* sqlite3.h */ = {… path = usr/include/sqlite3.h; sourceTree = SDKROOT; };
```

Is there any way to compose a podspec that generates something like the above?

I've been using a custom module map (which CocoaPods supports) to import these kinds of headers into Swift instead, but it's a much clumsier solution.

**Comment by segiddins** [comment]
Not that I can think of

**Comment by stephencelis** [comment]
Can we consider this a feature request? I'd be willing to give contributing it a shot, I'd just want a little guidance as to how such a feature would be implemented.

Maybe something like the following?

``` rb
s.source_files = "**/*.{h,m}", "SDKROOT" => "usr/include/CommonCrypto/CommonCrypto.h"
# def source_files=(*patterns, **source_tree_patterns)
```

**Comment by segiddins** [comment]
I can't think of any way we can support that in a sane backwards-compatible way, unfortunately, and it adds a huge amount of complication

**Comment by stephencelis** [comment]
Maybe a new option that doesn't break compatibility? Does the https://github.com/CocoaPods/Xcodeproj offer a way of doing this?

**Comment by segiddins** [comment]
I mean xcodeproj can handle it, but we'd need a way to serialize that info in the podfile, and it would (likely) add a lot of complexity, and I'm just not convinced that complexity is worth it.

**Comment by groue** [comment]
Podfiles support the `private_header_files` key ([doc](https://guides.cocoapods.org/syntax/podspec.html#private_header_files)):

```ruby
s.private_header_files = '**/*_private.h'
```

If we would introduce a `sdk_header_files` key, there would be no compatibility issue with the existing `source_files` key:

```ruby
s.sdk_header_files = 'usr/include/CommonCrypto/CommonCrypto.h'
```

**Comment by groue** [comment]
@segiddins wrote:

> I'm just not convinced that complexity is worth it.

Well, the problem is that, unless I miss something, a module map can not contain a SDK-relative path, and must contain absolute paths. And absolute paths do not vary depending on the SDK which is supposed to provide the linked library, and this is a source of potential issues.

The `sdk_header_files` key proposed above is compatible, in spirit, with the podfile format, and may lift the complexity of adding an feature that is indeed useful, don't you think?

**Comment by neonichu** [comment]
This has been superseded by #5071
