### ISSUE TITLE
pod install is removing my Test target from my main scheme (private CocoaPod)

### ISSUE THREAD

**Issue by RaviDesai** [CocoaPods/CocoaPods#3944]
I'm developing a private CocoaPod that I created using 'pod lib create'.  I specified that I'm using tests and a sample project and it properly created two schemes (in addition to the pod schemes) one for the pod itself with 2 targets, the pod and the unit tests.  And a second for the example project.

However, the scheme it creates for the Pod itself does not properly add the test target under the Test sidebar here:

https://photos-3.dropbox.com/t/2/AACb8Oeu3NuFQ6UTnVLhMuZeoH5AEjUn5aymIuUBpH8z_Q/12/75724256/png/32x32/1/_/1/2/Screenshot%202015-07-31%2008.52.31.png/EImE4ToYvsMCIAIoAg/iNOzKrkS96FGRg6ftU5DLKZBiJPhkjLA73m8_Lq2gLQ?size=1280x960&size_mode=2

Worse, after I add the target manually, if I need to update the podspec and re-run 'pod install' it keeps removing the test target on me, and I have to keep replacing it manually.  Is there some way to work around this behavior?  I know it sounds minor, but after the sixth time of replacing the test target in the screen just this morning, I am incredibly annoyed.  I can't believe I'm the only person encountering this.

**Comment by segiddins** [comment]
@RaviDesai I can't view that image. Could you possibly share an example project that demonstrates the issue you're seeing?

**Comment by RaviDesai** [comment]
You know, I'm going to close this one.  I realize that the issue was that I was modifying the the 'pod' scheme whose container was the 'pods project' to run my unit tests.  If instead, I switched to using the 'example' scheme (which is located to be contained in the 'workspace') the issue largely went away.  I say largely, because whenever I run pod install now, it switches me back to the 'pod' scheme, but at least the 'example' scheme is not changed, and it is trivial to switch schemes.

**Comment by segiddins** [comment]
:+1:

**Comment by kunalbalani** [comment]
Thanks @RaviDesai I found this very helpful.
