### ISSUE TITLE
ld: library not found for -lGoogleAnalyticsServices

### ISSUE THREAD

**Issue by jetstream-mode** [CocoaPods/CocoaPods#3948]
Report

What did you do?
Ran pod install on my project.

What did you expect to happen?
pods would update and I can build my project.

What happened instead?
After opening new workspace file and attempting to build i get this:
ld: library not found for -lGoogleAnalyticsServices

Pertinent Info
Here is the pod install info for attempting to install google analytics:
ranger:universal ranger$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using Google (1.0.7)
Using GoogleAnalytics (3.13.0)
Using GoogleNetworkingUtilities (1.0.0)
Using GoogleSymbolUtilities (1.0.0)
Using GoogleUtilities (1.0.1)
Generating Pods project
Integrating client project
Sending stats

[!] The `AtEventUniversal [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-AtEventUniversal/Pods-AtEventUniversal.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `AtEventUniversal [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-AtEventUniversal/Pods-AtEventUniversal.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by segiddins** [comment]
@jetstream-mode did you address the issues pointed out in the warnings?

**Comment by jetstream-mode** [comment]
i tried the $(inherited) tag which produced this error:

ld: library not found for -lPods-AtEventUniversal

hmmm. hopefully getting closer.

**Comment by jetstream-mode** [comment]
also did clean pod install and that generated no errors.

**Comment by jetstream-mode** [comment]
i ended up setting build active architecture to yes which allowed app to compile. i then set it back to no, and it still compiles. so, it is finally working. thanks for the nudge in right direction.
