### ISSUE TITLE
I18n::InvalidLocaleData - can not load translations from 

### ISSUE THREAD

**Issue by diazweb** [CocoaPods/CocoaPods#3950]
Hello, When I make podinstall it returns the next error message:

I'm using ruby 2.2.2 on OSX Yosemite.

		I18n::InvalidLocaleData - can not load translations from /Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/locale/en.yml: #<NoMethodError: undefined method `load_file' for Psych:Module>
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:184:in `rescue in load_yml'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:181:in `load_yml'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:165:in `load_file'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:15:in `block in load_translations'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:15:in `each'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:15:in `load_translations'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/simple.rb:57:in `init_translations'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/simple.rb:71:in `lookup'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:26:in `translate'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:158:in `block in translate'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:154:in `catch'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:154:in `translate'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/transliterator.rb:11:in `transliterate'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:236:in `transliterate'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/specification.rb:171:in `c99ext_identifier'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/specification.rb:154:in `module_name'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/target/pod_target.rb:94:in `product_module_name'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:377:in `map'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:377:in `block (2 levels) in verify_no_duplicate_framework_names'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:373:in `each'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:373:in `block in verify_no_duplicate_framework_names'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:372:in `each'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:372:in `verify_no_duplicate_framework_names'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:107:in `install!'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
		/Users/diazweb/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
		/Users/diazweb/.rbenv/versions/2.2.2/bin/pod:23:in `load'
		/Users/diazweb/.rbenv/versions/2.2.2/bin/pod:23:in `<main>'

Thanks

**Comment by segiddins** [comment]
This looks like a bug in `i18n` more than cocoapods.

**Comment by diazweb** [comment]
So, any suggestion? Nobody with the same problem?

**Comment by segiddins** [comment]
No, I have no clue.

**Comment by neonichu** [comment]
Looks like an issue with the unrelated i18n gem to me as well.

**Comment by delba** [comment]
@diazweb I had the same issue. Remove the `psych` gem and it will be alright.

```bash
$ gem uninstall psych
```

**Comment by diazweb** [comment]
Thanks @delba! Works great your solution

**Comment by RSully** [comment]
Hm same problem here (removing psych worked). Was psych previously a dependency, or perhaps it came from something else (which may now be broken)?

**Comment by segiddins** [comment]
Psych is a gem built into MRI
