### ISSUE TITLE
Invalidating cache

### ISSUE THREAD

**Issue by kzaher** [CocoaPods/CocoaPods#3952]
Hi guys,

when I do 

```
pod trunk push RxSwift.podspec
pod trunk push RxCocoa.podspec
pod trunk push RxBlocking.podspec
```

and after I push, when I try to test that everything went ok, and go to my test project

```
cd [test project path]
pod update
```

I get old version of the podspec, and not the one I have just pushed.

After I manually

```
rm -rf ~/Library/Caches/CocoaPods
pod update
```

everything works fine.

Is it possible to invalidate the cache automatically after I've pushed my podspec?

Thnx, Kruno

**Comment by segiddins** [comment]
The cache keys off of versions, so that's probably not actually the issue. What version of CocoaPods are you using?

**Comment by segiddins** [comment]
Also, what's in the Podfile of the project you're trying to update?

**Comment by kzaher** [comment]
```
pod --version
0.38.2
```

Yeah, it's probably caching stale versions. But it would be nice if that would be invalidated automatically :) 

I'm sure that not a lot of normal users hit this, but for project maintainers it would be sweet :)

**Comment by segiddins** [comment]
Again, this should be impossible, since the cache keys off of the version of the podspec, and handles released and non-released pod separately

**Comment by kzaher** [comment]
I've tried to update from RxSwift/Cocoa/Blocking from 1.8.1 to 1.9.

It is ofc possible that I was doing something wrong.

After the release, when I would just do
```
rm -rf Pods
pod update
```

it wouldn't help, it would read old versions (1.8.1).

When I would do 

```
rm -rf ~/Library/Cache/CocoaPods
pod update
```

it would recognize and update to new version (1.9).

I'm not sure what released and non-released pods mean. I'm assuming that when I do `pod trunk push xxx` I release new version of the pod.

**Comment by segiddins** [comment]
Could you please share your Podfile?

**Comment by kzaher** [comment]
Sure,

```
Pod::Spec.new do |s|
  s.name             = "RxSwift"
  s.version          = "1.9"
  s.summary          = "Microsoft Reactive Extensions (Rx) for Swift and iOS/OSX platform"
  s.description      = <<-DESC
			This is a Swift port of Reactive extensions.

			[https://github.com/Reactive-Extensions](https://github.com/Reactive-Extensions)

			Like the original Rx, its intention is to enable easy composition of asynchronous operations and event streams.

			It tries to port as many concepts from the original Rx as possible, but some concepts were adapted for more pleasant and performant integration with iOS/OSX environment.

			Probably the best analogy for those who have never heard of Rx would be:


			```
			git diff | grep bug | less          #  linux pipes - programs communicate by sending
							    #  sequences of bytes, words, lines, '\0' terminated strings...
			```
			would become if written in RxSwift
			```
			gitDiff() >- grep("bug") >- less    // rx sink (>-) operator - rx units communicate by sending
							    // sequences of swift objects
			```
                        DESC
  s.homepage         = "https://github.com/kzaher/RxSwift"
  s.license          = 'MIT'
  s.author           = { "Krunoslav Zaher" => "krunoslav.zaher@gmail.com" }
  s.source           = { :git => "https://github.com/kzaher/RxSwift.git", :tag => s.version.to_s }

  s.requires_arc          = true

  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.9'

  s.source_files          = 'RxSwift/RxSwift/**/*.swift'
end
```

```
Pod::Spec.new do |s|
  s.name             = "RxCocoa"
  s.version          = "1.9"
  s.summary          = "RxSwift Cocoa extensions"
  s.description      = <<-DESC
			* UI extensions
			* NSURL extensions
			* KVO extensions
                        DESC
  s.homepage         = "https://github.com/kzaher/RxSwift"
  s.license          = 'MIT'
  s.author           = { "Krunoslav Zaher" => "krunoslav.zaher@gmail.com" }
  s.source           = { :git => "https://github.com/kzaher/RxSwift.git", :tag => s.version.to_s }

  s.requires_arc          = true

  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.9'

  s.source_files          = 'RxCocoa/RxCocoa/RxCocoa.h', 'RxCocoa/RxCocoa/Common/**/*.{swift,h,m}'
  s.ios.source_files      = 'RxCocoa/RxCocoa/iOS/**/*.swift'
  s.osx.source_files      = 'RxCocoa/RxCocoa/OSX/**/*.swift'

  s.dependency 'RxSwift'
end
```

**Comment by segiddins** [comment]
Those are the podspecs, can I see the `Podfile`?

**Comment by kzaher** [comment]
Sry, this is my podfile. I always push to develop before running `pod update`

```
#Podfile

use_frameworks!

pod 'RxSwift', :git => "git@github.com:kzaher/RxSwift.git", :tag => 'develop'
pod 'RxCocoa', :git => "git@github.com:kzaher/RxSwift.git", :tag => 'develop'
pod 'RxBlocking', :git => "git@github.com:kzaher/RxSwift.git", :tag => 'develop'
```

**Comment by segiddins** [comment]
Doing `pod trunk push` will have no effect with that podspec, and you should be using `branch` instead of `tag` there, the cache assumes that tags will always point to the same ref.

**Comment by kzaher** [comment]
Thnx, I'll use branch instead.
