### ISSUE TITLE
"Generating Pods project" horribly slow with 0.38

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/CocoaPods#3957]
🌈

Today we upgraded CocoaPods from 0.37.2 to 0.38.2. Then I removed our app project's workspace, its `Pods` directory and its `Podfile.lock` to make a clean reinstall of all Pods.

With CocoaPods version 0.38.2 `pod install` and `pod update` do now take about **15 minutes**.

```shell
$ time pod install

Updating local specs repositories
Analyzing dependencies
Fetching podspec for `…` from `…` (34 times)
Downloading dependencies
Using … (55 times)
Generating Pods project           << this is what takes so long!
Integrating client project
Sending stats

real   13m54.067s
user   13m22.360s
sys     0m17.510s
```

It's the same with `pod update`.

The project has 16 Pods, 5 transitive Pods & 34 Development Pods
Other smaller projects don't have this issue.

As this issue is difficult to reproduce (beside having access to the whole project) we'd like to help finding the cause of this issue as well as a temporary workaround.

----

**Update**

We tested CocoaPods 0.38.0 which is also affected.
We tested CocoaPods 0.38.0.beta.2 which is also affected.
**We tested CocoaPods 0.38.0.beta.1 which is NOT affected**.

**Comment by segiddins** [comment]
Yup, this is due to predictable UUID generation. You can either opt out of it or help us speed it up :)

**Comment by fluidsonic** [comment]
Thanks for the info. I guess the MD5 hashing isn't cached which causes this insane delay?

I don't know why it's an environment variable but in case anyone else has the same issue and needs to disable this feature directly from within the `Podfile` then here you go:

```ruby
pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3957
	installer.config.deterministic_uuids = false
end
```

I'll leave the issue open since this very high delay definitively is an issue.

**Comment by segiddins** [comment]
Well, there's nothing in this issue for me to really try and optimize with ;)

**Comment by n8tr** [comment]
@fluidsonic adding that to our Podfile generates this error:
```
[!] An error occurred while processing the pre-install hook of the Podfile.
undefined method `deterministic_uuids=' for #<Pod::Config:0x007fd8a21bdc08
```

**Comment by segiddins** [comment]
Closing due to lack of actionable information.

**Comment by maddanio** [comment]
what is that predictable UUID generation good for? if it has such a high price tag...
