### ISSUE TITLE
changing platform version of my podspec gives me "Unable to satisfy the following requirements"

### ISSUE THREAD

**Issue by skydivedan** [CocoaPods/CocoaPods#3959]
I have a podspec that I'm writing. The "platform" specifier has looked like this for a long time:
s.platform     = :ios, "7.0"

If I switch that to a minimum of "8.0",  I get this:
`````
[!] Unable to satisfy the following requirements:

- `mySpecialPod (from `../`)` required by `Podfile`
`````

If I switch back to 7.0 (or 7.1) it works fine. I tried doing a "verbose" on the update, and no other information was there to give me a hint about the problem.

**Comment by segiddins** [comment]
This is addressed by https://github.com/CocoaPods/CocoaPods/pull/3953.

**Comment by skydivedan** [comment]
yeah, I noticed that if I changed my Podfile to explicitly say "8.0" (to match the podspec) then this problem goes away. Although, I didn't have any "platform" argument in the podfile prior to this. But anyway, that got me around the problem.
