### ISSUE TITLE
Why does lint only run against RELEASE configuration?

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#3961]
Shouldn't there be an option to allow a DEBUG configuration to execute at the podspec level or is this just incomplete atm?

**Comment by segiddins** [comment]
Can you elaborate as to why that would be beneficial?

**Comment by dnkoutso** [comment]
Suppose you `#if DEBUG` checks in the sources. It turns out lint for one of my projects successfully passed but that was sort of a mistake since when I consumed the podspec in a DEBUG build it actually failed because a dependency was missing for DEBUG configuration.

**Comment by segiddins** [comment]
Hmmm. I just don't know that it's worth doubling the time it takes to lint

**Comment by dnkoutso** [comment]
Would you settle with an option such as `--all-configurations` perhaps? It can be a bit deceiving if lint is successful and publishes but cannot be consumed.

**Comment by dnkoutso** [comment]
Or even a configuration override `--configuration=Debug` or something so you only have to build once.

**Comment by segiddins** [comment]
I think that's starting to slip into the territory of "it's the developers responsibility", but let's see what the rest of @cocoapods/core thinks?

**Comment by neonichu** [comment]
I agree with @segiddins
