### ISSUE TITLE
Introduce a setting in the Podfile to set 'Allow non-modular includes...' option 'Yes' in Pod project

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#3965]
I'm sure I'm not the only person suffering from this issue after enabling `use_frameworks!` for your builds.
At the moment, EVERY time I do a `pod install` (which is every time that a file is added or moved or renamed in a development pod) I end up with a broken project.

This is because some pods (including some Development Pods that I build) use non-modular imports. e.g. Facebook's `FBSDKCoreKit`.

Perhaps a quick `post_install` script will do the job (I've not seen any in the wild) but surely this is enough of an issue Cocoapods might want to address this?

**Comment by segiddins** [comment]
I think this is exactly what the `post_install` hook is for :)

**Comment by neonichu** [comment]
I agree, there's no need to offer DSL to work around broken Pods.

**Comment by fatuhoku** [comment]
@segiddins Sorry can you please point me in the right direction? Doing a brute-force gsub doesn't appear to work. I think the `Pods.xcodeproj` is written out too late, after `post_install` occurs. Am I right?

**Comment by fatuhoku** [comment]
i.e. how do I add build settings on the project level, rather than per-target?

**Comment by segiddins** [comment]
```ruby
post_install do |installer|
  installer.pods_project.targets.build_configurations.each { |bc| bc.settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'Yes' }
end
```

or something like it should do the trick

**Comment by fatuhoku** [comment]
http://www.rubydoc.info/gems/cocoapods/Pod/Project

There's no way to access the `pods_project`'s build_configuration...

**Comment by segiddins** [comment]
@fatuhoku sorry, should be `pods_project.targets.flat_map(&:build_configurations).each`

**Comment by fatuhoku** [comment]
@segiddins okay, with that `flat_map` expression I now get:

`undefined method `settings' for #<Xcodeproj::Project::Object::XCBuildConfiguration:0x007fba354bc598>`

**Comment by fatuhoku** [comment]
Okay, my mistake was to rely on the documentation. It's clearly not complete.

I ended up with 
```ruby
post_install do |installer|
  # puts installer.pods_project.inspect
  installer.pods_project.build_configurations.each { |bc|
      bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  }
end
```

**Comment by segiddins** [comment]
http://www.rubydoc.info/github/CocoaPods/Xcodeproj/Xcodeproj/Project

**Comment by k06a** [comment]
Working copy/paste solution:
```ruby
post_install do |installer|
    installer.pods_project.targets.flat_map(&:build_configurations).each { |bc|
        bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'Yes'
    }
end
```
