### ISSUE TITLE
Builds fails with OS X El Capitan 10.11 Beta (15A244d) | Xcode Version 7.0 beta 4 (7A165t)

### ISSUE THREAD

**Issue by nyotis** [CocoaPods/CocoaPods#3970]
I follow steps described in https://github.com/CocoaPods/CocoaPods/issues/3692
I install CocoaPods as shown below, but pod --version fails 

![screen shot 2015-08-05 at 12 03 41 pm](https://cloud.githubusercontent.com/assets/658719/9083442/86c1f7c4-3b6a-11e5-81ff-4b54b4b8ce97.png)

**Comment by nyotis** [comment]
"gem which cocoapods"
/Users/nikyotis/Software/ruby/gems/cocoapods-0.38.2/lib/cocoapods.rb

**Comment by kylef** [comment]
@nyotis You've typoed "Software" within your `$PATH`. It's set to `/Users/nikyotis/Sofware/ruby/bin` where it should be `/Users/nikyotis/Software/ruby/bin` as per how you've configured `$GEM_HOME`.

**Comment by nyotis** [comment]
![screen shot 2015-08-05 at 12 48 35 pm](https://cloud.githubusercontent.com/assets/658719/9084110/5603e9c0-3b70-11e5-9d4b-10b7e1bf9061.png)
PATH and GEM_HOME are now identical, I still cannot get the pod --version work though

**Comment by nyotis** [comment]
![screen shot 2015-08-05 at 12 50 47 pm](https://cloud.githubusercontent.com/assets/658719/9084127/9fcae482-3b70-11e5-9e5e-93a4fb131667.png)

**Comment by kylef** [comment]
@nyotis This time, you've missed out the `/bin` subdirectory from what you've added to `$PATH`. As I said in my previous message, it should be `/Users/nikyotis/Software/ruby/bin`.

**Comment by nyotis** [comment]
![screen shot 2015-08-05 at 12 56 06 pm](https://cloud.githubusercontent.com/assets/658719/9084194/5d2a85aa-3b71-11e5-912d-c4d29b5abcf3.png)

**Comment by kylef** [comment]
No, `/Users/nikyotis/Software/ruby/bin` should be in your `$PATH`. `/Users/nikyotis/Software/ruby` should be in your `$GEM_HOME`. `$GEM_PATH` doesn't need to be set.

So:

```shell
$ export GEM_HOME=/Users/nikyotis/Software/ruby
$ export PATH=$GEM_HOME/bin:$PATH
```

**Comment by nyotis** [comment]
;-) thanks

**Comment by l800891** [comment]
Thanks it works for me!!
