### ISSUE TITLE
Pod lib lint is not working XCode 6.4 Pods 0.38.2 

### ISSUE THREAD

**Issue by hiteshvadlamudi** [CocoaPods/CocoaPods#3973]
When I compile my pod in XCode it builds and runs fine. But when I run this command, my pod spec validation fails. 

I get errors like
    - ERROR |  <ProjectName>/Pod/Classes/Log.swift:10:8: error: no such module 'Parse'

**Comment by neonichu** [comment]
Please make sure you added Parse as a dependency in your podspec. If that doesn't help, please add more info to this, e.g. the podspec you're linting, see <https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#bug-reports>
