### ISSUE TITLE
Can CP support spec repo of SVN/HG/HTTP?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#3974]
We have some pod spec private repos, but they are not all the git repo.

Can CP support that SVN spec repo?

And we hope the spec repo is mini without commit history, I want to add some features to support other type spec repo. What about the idea?

**Comment by segiddins** [comment]
This is addressed by https://github.com/CocoaPods/CocoaPods/pull/3792.
