### ISSUE TITLE
Framework bundle is not available with resource_bundles

### ISSUE THREAD

**Issue by nderkach** [CocoaPods/CocoaPods#3978]
I've created a framework using ```pod lib create``` with a test app.

In its podspec I include resource_bundles to copy framework resources, like this:

```
  s.resource_bundles = {
    'FlightKit' => ['Pod/Assets/*']
  }
```

Later on, I'm trying to access this bundle as follows:

```swift
let path = NSBundle.mainBundle().pathForResource("FlightKit", ofType: "bundle")
```
The path is nil here. I've noticed that during the build, the framework is indeed copied together with the accompanying resources, i.e. I was able to find it at ```FlightKit_Example.app/Frameworks/FlightKit.framework/FlightKit.bundle``` installed on the simulator. It's seems that the issue is in how I'm trying to access the bundle in the code.

What's the problem here?

**Comment by nderkach** [comment]
I finally sorted it out. Apparently, embedded frameworks are location outside the main bundle, so you need to address them like this:

```swift
let bundle = NSBundle(forClass: FlightKit.Flight)
```

One would have to create a public class inside of framework (```Flight```) in this case to be able to load the bundle. I don't quiet understand the logic behind it. It seems that using a bundle identifier would be more straightforward, unfortunately it doesn't seem that cocoapods provides you with an option to specify those atm (see #3032)

**Comment by orta** [comment]
Yeah, this is just how frameworks vs libraries work, I'm afraid. As they say in #3032 providing a bundle ID wouldn't work because you'd have to do 2 separate code paths depending on the pod consumers choices.

**Comment by nderkach** [comment]
@orta what do you mean by "pod consumer choices"?

**Comment by orta** [comment]
someone using your CocoaPod who can either consume it as a static library ( where everything is in one bundle ) or as a framework ( where everything is self contained )
