### ISSUE TITLE
Expected symbol not found by dyld

### ISSUE THREAD

**Issue by lzwjava** [CocoaPods/CocoaPods#3981]
![image](https://cloud.githubusercontent.com/assets/5022872/9140544/9cff3122-3d64-11e5-945a-1ea98f8725d8.png)

When I install `pod install --verbose`, It reports error such like that, so the process exit. Then I run project , but it didn't work. It said some symbol not found :

![image](https://cloud.githubusercontent.com/assets/5022872/9140562/c1eb8210-3d64-11e5-9817-9368b0065299.png)

And AVOSCloudIM framework isn't exists in left Pods frameworks,

![image](https://cloud.githubusercontent.com/assets/5022872/9140652/57f339a6-3d65-11e5-859d-dfebe50eafef.png)

It don't work in 0.38.2. When I use 0.37.2, it works fine.

**Comment by segiddins** [comment]
Failing to send stats is fine, that shouldn't stop the rest of the install process from finishing.

**Comment by segiddins** [comment]
@lzwjava could you please share the project that you're having trouble with?

**Comment by lzwjava** [comment]
@segiddins  Fine, the project is at https://github.com/lzwjava/WukongSNS , podfile is in directroy PenYQ. Thank you for help.

**Comment by lzwjava** [comment]
@segiddins Hi, bro, any discovery?

**Comment by segiddins** [comment]
No, I haven't really had a chance to investigate yet, sorry.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
