### ISSUE TITLE
can't make google-cast-sdk part of my podspec, with 0.38.2

### ISSUE THREAD

**Issue by skydivedan** [CocoaPods/CocoaPods#3982]
I'm using "google-cast-sdk", version 2.7.1, pod as a dependency in my private podspec. I was using cocoapods 0.35, but recently upgraded to 0.38.2, now I get a compile error -- it can't find the header files, using a framework-style import.

I realize that the problem is that what I'm looking at is probably a "fake" framework, and the way that they specify the framework paths. I've already notified Google about the issue, but in the meantime, I'd really like to get this to work, even if their podspec isn't quite up-to-code.

So, I'm wondering, is there a way I can change my own podspec, such that it "fixes" the issues with google-cast-sdk, and I can import their headers?

Here's my repo:
git@github.com:skydivedan/google-cast-pod-fail.git

Thanks for any help you can provide

**Comment by neonichu** [comment]
Running `pod install` in your example and building it using either Xcode 6.4 or 7.0 works just fine for me. Could you point out what the steps are you're taking with that project to receive a compilation error?

**Comment by skydivedan** [comment]
Ugh, sorry about the missing detail on that. 

There's a file named **ReplaceMe.m** -- this file is a file within my private pod. I can't use the framework-style header <GoogleCast/GoogleCast.h>, because of the way that GoogleCast's podspec is set up. If I do this within the *app* (not the pod), it works fine. But if I want to reference it within the pod, I get an error.

**Comment by neonichu** [comment]
Right, I think you're seeing the same issue as in CocoaPods/Specs#13369, the headers for a vendored framework aren't automatically linked anymore.

**Comment by skydivedan** [comment]
OK, so for the time being (until the podspec gets fixed) I'm pulling this out of my podspec, and just using google-cast-sdk as a vendored framework. Thanks for your input.

**Comment by segiddins** [comment]
Closing since I believe we've fixed this.
