### ISSUE TITLE
Info.plist for a Swift framework?

### ISSUE THREAD

**Issue by nderkach** [CocoaPods/CocoaPods#3983]
I have a Swift framework, which I want to be installed via CocoaPods. The framework uses CLLocation and therefore requires modification of Info.plist for a build target (namely for NSLocationWhenInUseUsageDescription).

Is there a way to do this kind of modification out of the box?

**Comment by segiddins** [comment]
Not currently, no.

**Comment by amorde** [comment]
I feel like letting a pod modify the "capabilities" of the base target (and therefore modifying it's Info.plist) is not the right way to go. That's something that, if unknown to the developer, could seriously affect how their submission to the App Store is received by Apple.

That's just my opinion, however.

**Comment by segiddins** [comment]
Yeah, @amorde's reasoning is why that's not possible.
