### ISSUE TITLE
Touching the pch causes longer builds after pod install

### ISSUE THREAD

**Issue by hfossli** [CocoaPods/CocoaPods#3991]
🌈

When is it necessary for xcode to recompile after `pod install`? Does it have to recompile all source for all pods in even the simplest setups or is there some things that I should be aware of which triggers the need to recompile? 

Xcode: 6.4
Cocoapods: 0.38.0

###### Background
The source for several of our applications is managed by cocoapods. So whenever we add a new source file we have to run `pod install` to have that file available in xcode. I'm trying to get this process as effective as possible since I don't like having a fear of adding classes because of the time it takes to do so.

**Comment by neonichu** [comment]
Can you clarify your question a bit? Are you seeing recompiles happening that you think shouldn't be necessary or are you talking about manually cleaning and rebuilding?

**Comment by hfossli** [comment]
When I do this:

1. `pod install`
1. open workspace
1. build and run app in simulator
1. close xcode
1. `pod install`
1. open workspace
1. build and run app in simulator

No changes to podspec, podfile or any source file has been made and yet Xcode needs to compile every source for every pod at step 3 and 7. 

Is it possible to avoid unnecessary compilations of source files between `pod install`'s?

**Comment by neonichu** [comment]
Can you share the Podfile with which this is happening? 

In general, Xcode relies on file modification times, so it should not recompile files where that doesn't change. It will however still relink each framework and probably do even more for Swift projects, because those are still handled differently and prone to more recompilation. Did you actually compare build times and determine that the second compilation takes as long as the first one?

**Comment by neonichu** [comment]
BTW, you can show build times inside Xcode using:

```bash
$ defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES
```

**Comment by neonichu** [comment]
One note: if you're using `:head` for some Pods, this will also negatively affect build times.

**Comment by orta** [comment]
> One note: if you're using :head for some Pods, this will also negatively affect build times.

Sorry to take this aside, but I'm interested in why this is. If it's any different from the above comment.

**Comment by hfossli** [comment]
```
source 'https://bitbucket.org/agens/agenspodspec.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/schibsted/CocoaPods-Specs.git'

platform :ios, '7.0'

pod 'IVYCore', :path => '../../IVYCore.podspec'

target :IVYTests do
	pod 'OHHTTPStubs', '~> 3'
	pod 'OCHamcrest', '~> 4.0'
	pod 'OCMock', '~> 3.1.2'
end

post_install do |installer|

	# Predefined constants
	build_properties = File.open('build_properties') {|f| f.read }
	hash = eval(build_properties)
	installer.pods_project.targets.each do |target|
		if target.name.start_with?('IVY') || target.name.start_with?('Pods-IVY')
			target.build_configurations.each do |config|
				config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
				hash['GCC_PREPROCESSOR_DEFINITIONS'].each do |property|
					config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << property
				end
			end
		end
	end

	# Debug symbols
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			if config.name != 'Release' && config.name != 'AppStore'
				config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'YES'
				config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
				config.build_settings['COPY_PHASE_STRIP'] = 'NO'
				config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
			end
		end
	end

end
```

**Comment by neonichu** [comment]
@orta I think this happens because there's no check if anything has actually changed before copying over the files

**Comment by neonichu** [comment]
@hfossli OK, this includes a private Pod, so it's hard to actually test. 

Is stuff like OHHTTPStubs actually being recompiled for you? If it is, I'm wondering if that is due to the post install hook stuff you are doing.

**Comment by segiddins** [comment]
Pretty sure that touching the XCConfig files alone would be enough to trigger a full rebuild.

**Comment by neonichu** [comment]
@segiddins aren't those rewritten every time when one does a `pod install`? For a pure ObjC project with only released Pods, the time difference between building before and after an "empty" `pod install` is almost zero.

**Comment by hfossli** [comment]
@neonichu yes, it is a private pod. I will try to setup a public sandbox project for verifying my findings. 

My desired outcome of this discussion is an exhaustive list of things that will trigger recompile. Up until now you have mentioned:

1. Touching XCConfig
1. Pointing to a podspec using `:head`

**Comment by hfossli** [comment]
@neonichu OHHTTPStubs is being recompiled if I run unit tests, not otherwise.

**Comment by hfossli** [comment]
Seems like it is recompiling even with this simple setup https://github.com/hfossli/Cocoapods-3991

**Comment by hfossli** [comment]
Does that mean that we can append use of local pods to the list?

**Comment by hfossli** [comment]
Okay, so my setup over at https://github.com/hfossli/Cocoapods-3991 (same as above) is triggering recompile in even the simplest setup.

**Comment by neonichu** [comment]
Thanks for the detailed example. 

I am unsure why your project behaves differently than the one I was testing with, but looking at the build times, there's definitely not a full rebuild going on — on my machine it take ~40 seconds for the initial build and ~25 for building after a `pod install`. 

In any case, it would be interesting to find out what causes that indeed, I guess @segiddins is right and touching the XCConfigs does trigger Xcode to do more than necessary.

**Comment by neonichu** [comment]
I think the culprit is actually the dummy source, which gets recreated each time. That's why only one file per Pod is rebuild, but that plus link time makes up more than half of the full build time.

**Comment by neonichu** [comment]
Have played around a bit, and it turns out :tm: that the modification time of the PCH makes the difference. Running `find . -iname "*.pch" -exec touch -t 01010000 "{}" \;` after a `pod install` brings the recompilation time down to a few seconds.

I guess we should consider keeping the PCH mtime intact if we actually don't change their contents. Or maybe finally :fire: them entirely? :)

**Comment by segiddins** [comment]
Hm, i'm not sure its worth bending over backwards to preserve the mtime since the issue only arises the first time after running `pod install`, but that would seem to be the best solution.

**Comment by hfossli** [comment]
Interesting find!

**Comment by hfossli** [comment]
Yes, indeed. After running `pod install` most pch files changed. I ran `pod install` 11:23. 

```
➜  ACME  ls -la **/*.pch
-rwxrwxrwx@ 1 maria  staff  193 Aug 11 00:02 Pods/HockeySDK/Support/HockeySDKTests/HockeySDKTests-Prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/AFNetworking/AFNetworking-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/AGAssert/AGAssert-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/AGGeometryKit/AGGeometryKit-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/ALSystemUtilities/ALSystemUtilities-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/ARSafariActivity/ARSafariActivity-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/BlocksKit/BlocksKit-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/CargoBay/CargoBay-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/CocoaLumberjack/CocoaLumberjack-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/EDColor/EDColor-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/FMDB/FMDB-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/FXKeychain/FXKeychain-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/FXReachability/FXReachability-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/GBDeviceInfo/GBDeviceInfo-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/HockeySDK/HockeySDK-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/JLRoutes/JLRoutes-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/JRSwizzle/JRSwizzle-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/JSONModel/JSONModel-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/NSLogger-CocoaLumberjack-connector/NSLogger-CocoaLumberjack-connector-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/NSLogger/NSLogger-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/RNCryptor/RNCryptor-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/ReactiveCocoa/ReactiveCocoa-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/SSZipArchive/SSZipArchive-prefix.pch
-rw-r--r--  1 maria  staff  242 Aug 11 23:13 Pods/Target Support Files/UISS/UISS-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/iCarousel/iCarousel-prefix.pch
-rw-r--r--  1 maria  staff   48 Aug 11 23:13 Pods/Target Support Files/pop/pop-prefix.pch
-rwxrwxrwx@ 1 maria  staff  194 Aug 11 00:02 Pods/UISS/Project/UISS/UISS-Prefix.pch
```

It seems like that podspecs which have set a prefix_header_file is not affected by this, but those who hasn't are. :D 

Though this issue only arises the first time after `pod install` it can be quite the drag. Some people run `pod install` many times a day. Reading from this issue it seems I'm not alone https://github.com/CocoaPods/CocoaPods/issues/3824.

**Comment by segiddins** [comment]
I agree it would be _nice_ to improve this, but I don't really se it being worth the refactoring effort that @neonichu and I determined it would take to make this feasible.

**Comment by hfossli** [comment]
Allright, I see. The findings are still useful to me as I now can just add a simple pch flle to my biggest local pod (hopefully) and improve build time that way.

**Comment by hfossli** [comment]
Will test tomorrow.

**Comment by neonichu** [comment]
You could also add a post-install hook which uses `touch -t` to reset the mtimes as mentioned above.

**Comment by hfossli** [comment]
Just wanted to let you know that this is a world of difference to me. 
Whenever I run `pod install` and *I know* the pch files hasn't changed I do this
```
pod install && find . -iname "*.pch" -exec touch -t 01010000 "{}" \\;
```

Thanks @neonichu

**Comment by segiddins** [comment]
Closing because this is ultimately the fault of clang / Xcode, and the amount of changes necessary in CocoaPods to avoid this is utterly infeasibly.

**Comment by foobra** [comment]
find . -iname "*.pch" works for me! You save my day!
Another little problem, the pods project will not recompile again and again, but the main project will still recompile every source file, How can I avoid it?

**Comment by foobra** [comment]
@segiddins @neonichu Pods project recompile problem done, but the main project still recomplile every time after I pod update, How can I resolve it?

**Comment by foobra** [comment]
I execute pod install and compile the whole workspace.
After then, I execute find . -iname "*.pch" -exec touch -t 01010000 "{}" \; 
And every source file in pods will recompile again.
That means, touch pch will make pods recompile. 
How to not recompile in xcode 7.3? 

@neonichu

**Comment by keith** [comment]
FWIW just touching the `pch` files for our project didn't work. But this seems to:

```
pod install && find Pods -iname "*.pch" -exec touch -t 01010000 "{}" \; && find Pods -iname "*-dummy.m" -exec touch -t 01010000 "{}" \; && find Pods -iname "*-umbrella.h" -exec touch -t 01010000 "{}" \;
```
