### ISSUE TITLE
CocoaPods 0.38.2 does not build some of pods

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#3993]
Hi,

I use a Lookback pod which mysteriously disappeared from Pods project once I've updated to 0.38.2.

My Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Lookback', '~> 1.0.5', :configurations => ['Debug', 'Testing']
pod 'LookbackSafe', '~> 1.0.5', :configurations => ['Release']
```

pod install output:

```
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using Lookback (1.0.5)
Using LookbackSafe (1.0.5)
Using SSZipArchive (0.3.2)
Generating Pods project
Integrating client project
Sending stats
```

Boom, it's gone:

<img width="224" alt="screenshot 2015-08-10 11 48 57" src="https://cloud.githubusercontent.com/assets/704044/9167834/f9815504-3f55-11e5-9fd9-329dbe86e78e.png">

**Comment by mrackwitz** [comment]
That's the expected behavior, because Lookback is a vendored framework.
You will see that the Lookback binaries are placed in your Pods directory:
```shell
$ tree Pods/Lookback -L 3
Pods/Lookback
└── lookback
    ├── HD
    │   └── Lookback.framework
    └── Lookback-Resources
        └── Lookback.bundle
```
As they come already as binaries, they don't need to be build further and so also don't a Xcode target. The linkings happens over `OTHER_LDFLAGS` in the generated xcconfig.

**Comment by pronebird** [comment]
@mrackwitz thanks, makes sense. But it does not get included in project then like other frameworks? Do I have to manually drop it into the app?

**Comment by mrackwitz** [comment]
How do you mean it's symbols return nil? Return sounds like runtime to me. If it wouldn't be linked, it would cause a linker error and your app wouldn't run.

**Comment by pronebird** [comment]
I mean, I use their macro apparently which uses NSClassFromString(@"Lookback") in return. Returns nil.

**Comment by neonichu** [comment]
This should be fixed by this PR #3832, the issue is that `-ObjC` is needed for the vendored framework to work and it wasn't added.

**Comment by arielelkin** [comment]
@mrackwitz How exactly does one fix this issue?

Using cocoapods v0.38.2 and the latest Lookback pod, I get the runtime error @pronebird reported. 

The only fix I found was running `pod _0.37.2_ install`... But I wouldn't consider this issue closed?

**Comment by neonichu** [comment]
@arielelkin are you saying you have tried out #3832 and it doesn't fix this issue?

**Comment by arielelkin** [comment]
@neonichu: No, I haven't tried out https://github.com/CocoaPods/CocoaPods/pull/3832

**Comment by pronebird** [comment]
It may be not the best place to ask but, how can I roll into beta and have it working today? Thanks.
