### ISSUE TITLE
Lint fails on Import Metal

### ISSUE THREAD

**Issue by woofyman99** [CocoaPods/CocoaPods#3995]
I'm trying to build a pod thats uses the iOS Metal framework.  This causes "pod lib lint" to fail (and pod repo push) since it uses the iphonesimulator as the SDK when it runs xcodebuild.  Metal is not supported in the simulator.  Is there a way of skipping the build step ?

**Comment by neonichu** [comment]
Nope, I guess the only workaround for now is to manually push your spec.

Generally, I'm unsure how to avoid it. It'd be vary to skip building in lint, that defeats most of its point and building for the device requires code-signing to be set up. I guess the best way would be to optionally allow building for device, so linting a Pod which uses Metal would require code-signing being set up.

**Comment by segiddins** [comment]
Ideally, a pod that includes metal would have `#ifdef`s around the metal code, so that it can also be compiled for the simulator, even if it's then empty?

**Comment by woofyman99** [comment]
Swift doesn't have ifdefs.  An option to repo push not to link would work.

**Comment by segiddins** [comment]
Swift does let you switch based on CPU architecture
