### ISSUE TITLE
Not able to install pod on OSX 10.10.4 and XCode-beta 7.0 

### ISSUE THREAD

**Issue by pvn** [CocoaPods/CocoaPods#3996]
**Not able to install pod.**
----------------------------------

>sudo gem install cocoapods --verbos

*Environment of system:*
=================
>**xcodebuild -version**
Xcode 7.0
Build version 7A165t

>**xcode-select -p**
/Applications/Xcode-beta.app/Contents/Developer

>**ruby --version**
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

<img width="570" alt="screen shot 2015-08-10 at 9 30 50 pm" src="https://cloud.githubusercontent.com/assets/506406/9176126/18eae008-3fa7-11e5-8f0b-466830271c84.png">

Let me know, If you need more info.
I have tried all the way but could not succeed.

**Comment by pvn** [comment]
Closing this issue.
Fixed it by myself after installing ruby using 
>brew install ruby
and then
>sudo gem install cocoapods --verbose
Hope this trick might help others

**Comment by orta** [comment]
Thanks for reporting your fix @pvn

**Comment by pvn** [comment]
Anytime orta :) I have seen posts related to this issue on other sites. So thought to put my fix here as well.
