### ISSUE TITLE
fatal: Not a git repository: Pods/LibComponentLogging-pods/configure/../.git/modules/configure

### ISSUE THREAD

**Issue by adongarwar** [CocoaPods/CocoaPods#3997]
I'm trying to push a project to git. It fails with the error mentioned in title. Terminal logs are as follows.

```
adongarwar:ios adongarwar$ git init
Initialized empty Git repository in /Users/adongarwar/CIS-Git/ios/.git/
adongarwar:ios adongarwar$ git add ios
fatal: pathspec 'ios' did not match any files
adongarwar:ios adongarwar$ cd ..
adongarwar:CIS-Git adongarwar$ git add ios
fatal: Not a git repository (or any of the parent directories): .git
adongarwar:CIS-Git adongarwar$ cd ios
adongarwar:ios adongarwar$ git add .
fatal: Not a git repository: Pods/LibComponentLogging-pods/configure/../.git/modules/configure
```

Important point - My Project is in SVN already. I manually copy the project folder to a new folder and then try initialing git.

Thanks in advance.

**Comment by segiddins** [comment]
Just curious here, but what makes this an issue with CocoaPods? It seems more like an issue using git to me.

**Comment by adongarwar** [comment]
The .git file located at Pods/LibComponentLogging-pods/configure says gitdir: ../.git/modules/configure. Probably this is what makes git think that its not a git repo.

**Comment by segiddins** [comment]
Sure, but this seems like a git issue, not a CocoaPods one?

**Comment by adongarwar** [comment]
Thanks

**Comment by aharren** [comment]
Looks like git complains about a `.git` folder from a spec with a `"submodules": true` setting. This can be solved locally by just removing the `.git` folder in `Pods/LibComponentLogging-pods/configure/`.

I will update the `LibComponentLogging-pods` specs and adapt the `preserve_paths`.
