### ISSUE TITLE
Cocapods 0.38.2 and Google Maps fail in lint but installs correctly

### ISSUE THREAD

**Issue by Zoukar** [CocoaPods/CocoaPods#3998]
I have a private pod that uses the Google Maps pod, everything was fine until I updated to 0.38.2.
I use this podspec in the main project of my application and it installs, updates and builds correctly, but it is impossible to lint(and as consequence push to the spec repo). 
I keep getting  this error when I run lint:
    - ERROR | [iOS] Encountered an unknown error (The 'Pods' target has transitive dependencies that include static binaries: (/private/var/folders/xp/lwzc6vrx08gfh8s9fngh60s40000gn/T/CocoaPods/Lint/Pods/GoogleMaps/Frameworks/GoogleMaps.framework)) during validation.

I still build the application to IOS 7 so i can't use framewoks but as a test I've upgraded to IOS 8 and now the application fails to build, I get duplicate deffinitions of functions of another pod that does not uses Google Maps.
What am I doing wrong? I am rellatively new to cocoapods so I can't tell if this has sufficient data to find the problem, please ask if more information is needed.

**Comment by neonichu** [comment]
You might want to try linting using `--use-libraries`, the default is to lint as a framework.

**Comment by Zoukar** [comment]
It worked partly, I don't get the previous error. But now it has double definitions of methods errors, a lot of them.
Any hints?

**Comment by neonichu** [comment]
Sorry, but without any more information, it is impossible to diagnose the error. Ideally, you have a project you can share which exhibits the same problem, but we will at least need to exact errors you're seeing and your podspec.

**Comment by Zoukar** [comment]
There was a duplicated include in the pods, now it is working. 
Thanks.
