### ISSUE TITLE
Include Podfile checksum in Podfile.lock

### ISSUE THREAD

**Issue by Ashton-W** [CocoaPods/CocoaPods#3999]
The addition or removal of `inhibit_all_warnings!` to a Podfile does not create a change in the Podfile.lock. 

So users are not warned by the *Check Pods Manifest.lock* build phase when there is a (minor) change to the podfile. That small change can cause build failures and other problems depending on the projects configuration.

I think any change to the contents of the `Podfile` that changes the generated projects should change the lock.

**Comment by segiddins** [comment]
I tend to disagree -- I think things like build settings changes (which is what this is) are the user's responsibility to run `pod install` after.

**Comment by Ashton-W** [comment]
When there are multiple users, the lock file is used to stop the build until `pod install` updates your local pods. I think configuration should be included in that, it creates confusion around why one machine builds fine but another doesn't.

**Comment by segiddins** [comment]
Can you think of a good way of adding that info to the lockfile?

**Comment by Ashton-W** [comment]
Could we simply include a checksum of the `Podfile` in the lock? Is that too much?

**Comment by Ashton-W** [comment]
If it is a point of contention, we could try and implement it so it is a warning, not an error when the Podfile is changed but the dependencies haven't.

**Comment by amorde** [comment]
From cocoapods.org:
># What is Podfile.lock?
> This file is generated after the first run of pod install, and tracks the version of each Pod that was installed. 

I think the lock was always intended specifically to ensure correct versions of dependencies are installed. Introducing build settings here doesn't seem like a good idea to me. Especially since, by default, `inhibit_all_warnings!` shouldn't make the difference between your build failing or not.

Maybe a plugin that checks for 100% equality between the `Podfile` and the `Podfile.lock` would be a good approach.

**Comment by neonichu** [comment]
I agree this check would be against the original intention of the lockfile. However, the "Check Pods Manifest.lock" build phase's intention is to check if a `pod install` is required and this can definitely be the case without the lockfile changing, e.g. when switching to `use_frameworks!`

@segiddins do you think doing a check against  a known checksum of the Podfile makes sense in general?

**Comment by segiddins** [comment]
@neonichu we could include a checksum of the podfile's `internal_hash` in the lockfile? But that might be expensive, as the hash would need to be converted to a stable string format in order to be checksummed.

**Comment by neonichu** [comment]
@segiddins maybe that's something we can do once we figure out a serialisation format after doing the new Podfile DSL?

**Comment by segiddins** [comment]
Sure :)

**Comment by Ashton-W** [comment]
> new Podfile DSL

Can we link that issue #

**Comment by neonichu** [comment]
New Podfile DSL is issue #840
