### ISSUE TITLE
Create self-contained installer package.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#400]
For people who are unfamiliar with CLI/Ruby, we should provide a complete self-contained installer package.

This should include things like:

* Latest Ruby
* Latest RubyGems
* Pre-installed gems of Xcodeproj/CocoaPods and their dependencies
* Configure load path

The user should **not** have had to install the Xcode Command-Line tools.

Updating:

* CocoaPods should notify a new version is available and ask the user wether or not to update
* Update packages should be delta updates

**Comment by orta** [comment]
Taking off 1.0 milestone, this should not stop that.

**Comment by kylef** [comment]
Since this is pretty close, perhaps we can try make this happen for 0.37 or 0.38. IMO some of the [release milestone tasks](https://github.com/CocoaPods/CocoaPods.app/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22First+release%22) are perhaps not necessary and we can get out a beta?

**Comment by segiddins** [comment]
Closing because CocoaPods.app
