### ISSUE TITLE
Podspec dependency rules do not appear to respect semver beta versions

### ISSUE THREAD

**Issue by cnoon** [CocoaPods/CocoaPods#4000]
I'm trying to use the Alamofire `2.0.0-beta.1` release as a dependency in another library and CocoaPods appears to be having difficulty resolving the version name as far as I can tell. Here's my info:

### Podspec

```ruby
Pod::Spec.new do |s|
  s.name = 'MagicLibrary'
  s.version = '1.0.0'
  s.license = { :type => 'COMMERCIAL' }
  s.summary = 'Removed...'
  s.authors = { 'Christian Noon' => 'christian.noon@gmail.com' }

  s.source = { :git => 'internally-hosted-repo', :tag => s.version }
  s.source_files = 'Source/*.swift'

  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.10'
  s.watchos.deployment_target = '2.0'

  s.dependency 'Alamofire', '2.0.0-beta.1'
end

```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

source 'private-spec-repo'

target 'SampleApp' do
  pod 'MagicLibrary', '1.0.0'
end
```

### Output from `pod update`

```bash
cnoon:~/Desktop/SampleApp$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Alamofire (= 2.0.0-beta.1)` required by `Podfile`
```

I have used beta versions in the past as dependencies and have had success with beta versions listed as `1.1.3b1` or `2.0.3b3`. Could someone help point me in the right direction? The [documentation](https://guides.cocoapods.org/syntax/podspec.html#dependency) doesn't seem to have any information about beta version resolution.

Thanks in advance!

**Comment by segiddins** [comment]
You need to also include the master source repo in the list of sources, `source 'https://github.com/CocoaPods/Specs.git'`.

**Comment by cnoon** [comment]
Ah that's my bad, that definitely fixed up the issue. Thanks @segiddins for the quick response, much appreciated. 🍻
