### ISSUE TITLE
How can I silence warnings from all pods except local pods?

### ISSUE THREAD

**Issue by hfossli** [CocoaPods/CocoaPods#4006]
Big pods like pop, AFNetworking, HockeySDK among others are yielding warnings and polluting my development environment. Making it harder for me to have a 0 warning tolerance on our team. 

🌈[I have asked](http://stackoverflow.com/questions/31644959/how-can-i-silence-warnings-from-all-pods-except-local-pods) on stackoverflow with a bounty of 150, but no one answers. So now I have started a new bounty of 300 and turning to github as I am not getting enough attention on stackoverflow.

I want to silence all warnings from pods which is not local pods. I want to do this dynamically ([not like this](http://stackoverflow.com/a/31779324/202451)).

As implied on related issues it should be possible to write a plugin or write a post_install hook that is doing this. https://github.com/CocoaPods/CocoaPods/issues/3109 https://github.com/CocoaPods/CocoaPods/issues/3949 https://github.com/CocoaPods/CocoaPods/issues/1587

**Comment by neonichu** [comment]
Please do not open issues solely to get questions answered, especially when those already exist in earlier issues.

You can get more info on how to write your own plugin by looking at existing ones or reading [this post](http://engineering.tumblr.com/post/124712775024/adventures-in-making-a-cocoapods-plugin). You can look the code to find out how to silence them: <https://github.com/CocoaPods/CocoaPods/search?utf8=✓&q=inhibit_warnings>

**Comment by hfossli** [comment]
thanks...

**Comment by grigorye** [comment]
I believe you can solve it using [cocoapods-developing-folder](https://github.com/leavez/cocoapods-developing-folder#-inhibit-warnings-for-specific-pods) plugin like below:

```
plugin 'cocoapods-developing-folder'

inhibit_warnings_with_condition do |pod_name, pod_target|
  pod_target.file_accessors.first.root.to_path.start_with? pod_target.sandbox.root.to_path
end
```
