### ISSUE TITLE
Sources flag failing to resolve private pod dependencies in Pod Spec Lint 

### ISSUE THREAD

**Issue by altyus** [CocoaPods/CocoaPods#4007]
Hi! 

As per documentation and other issues, I've added our private spec repo via SSH link to Pod Spec Lint, along with the main spec repo's HTTPS url with a comma delimiter. 

 Any private pod that's depended upon by the repo I'm linting is failing.  `- MSTrunKit (~> 0.1.3)` required by `MSNetworking (1.0.4)`.  

I have verified that the individual pods are working just fine and can access them using pod try from the command line or by adding to a project's Podfile and installing.  

My lint command looks like this: `pod spec lint --verbose --sources=git@github.com:MYCOMPANY/iOS-Specs.git,https://github.com/CocoaPods/Specs' MyPrivatePodSpec.podspec ` 

resulting error: 

```
Resolving dependencies of 
 -> PrivatePod (1.0.4)
    - WARN  | Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR | [iOS] Encountered an unknown error (Unable to satisfy the following requirements:

- `PrivatePodDependency (~> 0.1.3)` required by `PrivatePod (1.0.4)` during validation.

```

relates to #2543

**Comment by segiddins** [comment]
What happens if you do `https://github.com/CocoaPods/Specs.git` (notice the extra `.git` at the end) ?

**Comment by segiddins** [comment]
And what's the output when you run `pod search PrivatePodDependency` ?

**Comment by altyus** [comment]
```
$ pod search MSTrunKit

-> MSTrunKit (0.1.3)
   Common Toolbox for miscellaneous little tasks
   pod 'MSTrunKit', '~> 0.1.3'
   - Homepage: https://github.com/COMPANY/MSTrunKit
   - Source:   git@github.com:COMPANY/MSTrunKit.git
   - Versions: 0.1.3, 0.1.2, 0.1.1, 0.0.1 [COMPANY repo] - 0.1.3, 0.1.2, 0.1.1, 0.0.1 [COMPANY-1 repo]
```

**Comment by segiddins** [comment]
Hm. Is it possible that `MSTrunKit` has a higher minimum deployment target than `MSNetworking` ? (We already have a better error message for that in `master`)

**Comment by altyus** [comment]
Deployment target is 7.0 for each pod. 

MSTrunKit is a very simple little pod, so there are no other dependencies that could have higher targets either.  I just updated CocoaPods to the latest build and I'm seeing the same error message.

**Comment by segiddins** [comment]
Could you please share the podspecs for both pods, as well as `pod repo list --verbose` ?

**Comment by altyus** [comment]
I'm happy to, but any chance can we offline that in some way?

**Comment by segiddins** [comment]
Closing due to lack of response.
