### ISSUE TITLE
Question - Is it possible to have a compiler flag to prefix all pod classes 

### ISSUE THREAD

**Issue by avnerbarr** [CocoaPods/CocoaPods#4008]
I want to prefix all of my dependencies classes when compiling because I have class name conflicts when integrating my compiled source to different customer projects. (They use the same classes that I use)

I have seen solutions such as adding "other compiler flags" and replacing every occurrence of "ClassA" with a prefixed version "XXXClassA"

Is there a way to automate this process at the ```pod install``` stage?

**Comment by segiddins** [comment]
Take a look at the cocoapods-packager gem.

**Comment by avnerbarr** [comment]
I couldn't get it to work properly when I had dependencies in my Podspec that were swift

**Comment by segiddins** [comment]
Ah well that's because there's an open issue over there for adding dynamic framework support.

**Comment by neonichu** [comment]
@avnerbarr you can take a look at <https://github.com/CocoaPods/cocoapods-packager/blob/master/lib/cocoapods-packager/mangle.rb> for how the symbol mangling is done — that approach will not work for Swift dependencies, though.
