### ISSUE TITLE
BombSDK

### ISSUE THREAD

**Issue by wnz27** [CocoaPods/CocoaPods#4016]
在xode7上，Deployment Target用8.4。出了这样一个错“[!] Oh no, an error occurred.”
在pod中我是这样配置的：
platform :ios,'8.4'
pod 'BmobSDK'
pod 'BombSDK','-> 1.6.1'

**Comment by pronebird** [comment]
Bmob or Bomb?

**Comment by neonichu** [comment]
Please see our [contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) for which information we need for an issue, especially missing here is what the actual problem is. Also note that you have typoed "BmobSDK" multiple times, maybe that's already the issue?
