### ISSUE TITLE
Local podspec with external http source not added to Pods directory

### ISSUE THREAD

**Issue by vhariable** [CocoaPods/CocoaPods#4017]
I am working on adding a new version of a podspec, but want to test it locally. I can see in my cache directory that it does pull down the source and leaves the *.h and libAppLovinSdk.a as I need. However, it never copies any of that into my Pods directory. Even when executing in verbose mode there are no errors thrown. It looks like it downloads it to the local cache correctly, but just never moves it into the Pods directory.

1. What am I doing wrong? If this is a bug, can someone point me to the right direction and I will work on a PR for a fix.

2. This SDK is problematic in that the company removes the previous version tar files when uploading new ones. What is the preferred way of handling this in a podspec like this where I am not affiliated with the company that created this SDK, so I am unable to enforce leaving previous version of tar files there so that previous versions of podspecs continue to work.

### Podspec

```
Pod::Spec.new do |s|  
  s.name         = "AppLovinSDK"
  s.version      = "3.0.2"
  s.summary      = "Applovin SDK for iOS."

  s.description  = <<-DESC
                   Placeholder Applovin SDK for iOS description.
                   DESC

  s.homepage     = "https://www.applovin.com/integration#iosIntegration"
  s.license      = 'MIT (example)'
  s.author       = { "Applovin" => "support@applovin.com" }
  s.platform     = :ios, '5.0'
  s.source       = { :http => "http://sdk.applovin.com/applovin-ios-sdk-3.0.2.tar.bz2" }
  s.source_files  = '**/*.{h,m}'
  s.public_header_files = 'headers/*.h'
  s.vendored_libraries = 'libAppLovinSdk.a'
  s.frameworks   = 'AdSupport', 'AVFoundation', 'CoreGraphics', 'CoreMedia', 'CoreTelephony', 'MediaPlayer', 'SystemConfiguration', 'UIKit'
  s.requires_arc = true

end
```

**Comment by segiddins** [comment]
@vhariable can you share the Podfile you're using to install?

**Comment by vhariable** [comment]
Sure, the AppLovinSDK.podspec is located in the ../Cocoapods directory, relative from where this Podfile is located. I should have noted also that it adds the correct Xcode project other linker arguments for the AppLovinSDK lib file, the file just does not exist in the Pods directory anywhere. I am using the latest 0.38.2 and also have tested with the latest code from master.

```
platform :ios, "6.0"  
target "TestProject" do
pod 'AdColony', '~> 2.5'
pod 'AFNetworking', '~> 2.5'
pod 'ZipArchive', '~> 1.4'
pod 'Appirater', '~> 2.0'
pod 'ChartboostSDK', '~> 5.3'
pod 'FBAudienceNetwork', '~> 4.1'
pod 'GoogleAnalytics', '~> 3.12'
pod 'GoogleMobileAds', '~> 7.3'
pod 'Heyzap', '~> 8.2'
pod 'VungleAdvertiserSDK', '~> 3.0'
pod 'AppLovinSDK', :path => '../Cocoapods'
end  
target "TestProjectTests" do  
end
```

**Comment by segiddins** [comment]
Since you're using `path`, it shouldn't be downloading anything at all -- perhaps you meant to use `:podspec => '../CocoaPods/AppLovinSDK.podspec'` ?

**Comment by vhariable** [comment]
That works great, thank you! Sorry, was just me being new to using podspecs locally. What about my question 2 from the original comment?

**Comment by segiddins** [comment]
I'd recommend against publishing specs if the source won't stick around, and pressuring the creator of the library to not remove outdated downloads unnecessarily.

**Comment by vhariable** [comment]
@segiddins Thank you!
