### ISSUE TITLE
Podspec with 'WatchKit' framework dependency

### ISSUE THREAD

**Issue by fabiomassimo** [CocoaPods/CocoaPods#4018]
I've created a pod which is an helper for my watchkit extensions.

In its `podspec` it defines dependency to WatchKit framework like follow:

```ruby
Pod::Spec.new do |s|
  s.name             = "WatchKitHelper"
  s.version          = "0.1.1"
  s.summary          = "Manage communication between containing app and the Watch Kit Extension."
[...]

  s.frameworks = 'WatchKit'
  s.platform     = :ios, '7.0'
  s.watchos.deployment_target = "1.0"
  s.requires_arc = true

  s.source_files = 'Classes/**/*'
end
```

In my `Podfile` I use it like this

```ruby
platform :ios, '7.0'

link_with 'Main app', 'WatchKit Extension'

def shared_pods
    # In house dependecies
    pod 'WatchKitHelper', :path => [..]
end

target 'Main app' do
    shared_pods
    pod 'ReactiveCocoa', '~> 2.5'
    [...]
end

target 'WatchKit Extension' do
    shared_pods
end
```

After running `pod install` I receive neither warning or errors.
When compiling my target the `WatchKitHelper` implementation file which is using `WatchKit` framework gives a compiler error 

```objective-c
#import <WatchKit/WatchKit.h>    // WatchKit/WatchKit.h file not found
```

Am I using it in a wrong way?

**Comment by neonichu** [comment]
Unfortunately, I can't reproduce the problem, we'll need an example project. 

One hint if you're actually using those deployment targets: WatchKit needs at least iOS 8.2

**Comment by fabiomassimo** [comment]
The app in case has a deployment target set to 7.0 (as also specified in its `Podfile`) but it includes watch kit targets such that they are available on devices running >= iOS 8.2.

If I try to define ` s.platform     = :ios, '8.2'` in my WatchKit helper `Podspec` then `pod install` fails because of ' Unable to satisfy the following requirements'. 

It has his point though.

Could it be this weird scenario causing this issues?

**Comment by neonichu** [comment]
The error makes sense, because your Podfile defines 7.0 as platform.

**Comment by fabiomassimo** [comment]
Indeed but I'm not sure I want to change platform to 8.2 for all my pods.
I'll give it try and see if everything is still working otherwise I'd like to define as:

- This pods have 7.0 platform dependency
- This pod has 8.2 platform dependency.

I'm not sure I can do it but I'll try to change my platform to 8.2 overall in the `Podfile` as how it'll go.

**Comment by neonichu** [comment]
Having different deployment targets for different Pods isn't really supported by CP, but you could try using 8.2 in your Podfile and resetting other Pods to 7.0 in a post-install hook.

**Comment by fabiomassimo** [comment]
Ok change the platform in my `Podfile` to 8.2 solved the issue indeed.
If the project won't work as expected I'll try the post-install hook solution you suggested.

Anyway I consider this closed.

Thanks for your help and time.
