### ISSUE TITLE
`pod lib lint` and `pod spec lint` failing for Swift 2.0 project

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/CocoaPods#4024]
`pod lib lint` is failing for a Swift 2.0 project - specifically on syntax that is invalid in Swift 1.2. i tried upgrading to 0.38.2 from 0.37.2 but this caused `pod lib lint` to hang and never resolve. the result is not being able to push specs :confounded: i haven't found a resolution for this among the issues - anything i'm missing?

**Comment by segiddins** [comment]
What version of Xcode do you have selected? `xcodebuild -version` (set via `xcode-select`). Can you share the output of `pod lib lint --verbose` where it's hanging? Thanks!

**Comment by neonichu** [comment]
I would suspect that it is `xcodebuild` hanging, there are definitely cases where that happens when using "Release" (which lint uses) vs. "Debug" configs.

**Comment by hkellaway** [comment]
@segiddins :

Version:
```
Xcode 6.4
Build version 6E35b
```

Failing at the following for `0.37.2`
```
    - ERROR | [iOS] Returned an unsuccessful exit code.
    - WARN  | [iOS] ... warning: constant 'property' inferred to have type 'AnyObject', which may be unexpected
    - NOTE  | [iOS] ... note: add an explicit type annotation to silence this warning
    - ERROR | [iOS]  ... error: cannot convert return expression of type '[String : String?]' to expected return type 'JSON?'
```
Note: these are all Swift 1.2 specific issues.

Hanging at the following for `0.38.2`:

```
 - Running post install hooks
   Building with xcodebuild. 
xcodebuild clean build -target Pods CODE_SIGN_IDENTITY=- -sdk iphonesimulator 2>&1
```

**Comment by hkellaway** [comment]
@neonichu it does look like its hanging at `xcodebuild` in the message above. Do you know how to resolve that?

**Comment by neonichu** [comment]
Xcode 6.4 does only support Swift 1.2, so it's not surprising that it can't build 2.0 code :) You have to install and select a version of Xcode which can build your code before linting.

As for the compiler hang, the only solution is to report it to Apple so that it can be fixed in a future version. Maybe it is the same issue as <http://openradar.appspot.com/radar?id=6676111861743616>, then it has been fixed in recent betas of Xcode 7.

**Comment by hkellaway** [comment]
thanks, that was the key!

for others who come upon the same issue:

i ran `xcode-select --print-path` and found it _was_ pointing to Xcode 6.4:
```
terminal> xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
```

i then ran `xcode-select -switch` to switch it to my Xcode 7.0 beta directory:
```
terminal> sudo xcode-select -switch /Applications/Xcode-beta.app/Contents/Developer/
```
