### ISSUE TITLE
Class file and Nib for same VC in separate bundles

### ISSUE THREAD

**Issue by bencallis** [CocoaPods/CocoaPods#4025]
We are creating a private pod that includes multiple UI elements some of which are created using IB in nib files. 

I was expecting the nib and and the viewController to be in the same bundle So I could use the standard init method and the nib with the same name would automatically be found and loaded.

However, it seems the class and the nib are not in the same bundle.

```
 po [NSBundle bundleForClass:[SKYTotemViewController class]]
NSBundle </Users/bencallis/Library/Developer/CoreSimulator/Devices/1702B2EA-E714-4C22-9915-5045907C1DEE/data/Containers/Bundle/Application/6F669EB2-BCB8-48A7-B0D8-4AD21CD49525/xxx.Totem.iOS.app> (loaded)

Printing description of nibBundle:
NSBundle </Users/bencallis/Library/Developer/CoreSimulator/Devices/1702B2EA-E714-4C22-9915-5045907C1DEE/data/Containers/Bundle/Application/6F669EB2-BCB8-48A7-B0D8-4AD21CD49525/xxx.Totem.iOS.app/yyy.Totem.iOS.bundle> (not yet loaded)
```

Our current pod spec looks like this:
```
  "platforms": {
    "ios": "7.0"
  },
  "requires_arc": true,
  "source_files": [
    "Pod/Classes/*",
    "Pod/Classes/**/*"
  ],
  "resource_bundles": {
    "yyy.Totem.iOS": [
      "Pod/Assets/*.xib"
    ]
  },
  "private_header_files": [
    "Pod/Classes/Private/*.h",
    "Pod/Classes/Private/**/*.h"
  ],
```

Workaround is to specify the exact bundle where the nib is contained.
```
- (instancetype)init {
    NSString *bundlePath = [[NSBundle mainBundle] pathForResource:@"yyy.Totem.iOS" ofType:@"bundle"];
    NSBundle *bundle = [NSBundle bundleWithPath:bundlePath];
    self = [super initWithNibName:NSStringFromClass([self class]) bundle:bundle];
    return self;
}
```

Or not put the nibs in a resource_bundles and specify that they should be in the main bundle

```
  "resource":  "Pod/Assets/*.xib"
    
```

Is there a cleaner way of doing this? Ideally it would be nice if we could just use the default init method and providing the nib and class have the same name then the nib would be loaded.

**Comment by neonichu** [comment]
When using static libraries, all classes end up in the main bundle, so using `resource` is the only way to have resource in the same bundle. You could integrate using frameworks, then each Pod ends up in its own framework bundle. In any case, using `resource_bundle` always creates a separate bundle.
