### ISSUE TITLE
Extensions can use only a subset of the frameworks of their app target

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#4029]
### State of the Art

At the moment, we rely on the AppStore rules as sensible defaults to figure out whether pod frameworks should be integrated for a target type or not. But we do not ensure that if a extension has a dependency to a pod, which is not shared by its hosting app, that the framework for the pod is also embedded in the frameworks folder of the app bundle. So it works only if the extension use only a subset of the frameworks, which are used in the app target, which is often given, but doesn't necessarily need to be the default.

### Underlying Issue

We don't have a sufficient model of the user project / integration scenario. We don't know to which app target an extension belongs. Either we try to become better at that and figure it out over `Xcodeproj` or we could require to declare dependencies differently with #840.
Perhaps we should also allow to overwrite whether a target need to be embedded or not. E.g. if you build a Swift CLI tool, you want to embed frameworks in a bundle, which may be an umbrella framework and your CLI target is just a thin shell around that.

**Comment by segiddins** [comment]
In that example scenario, your framework should just be a development pod though, no?

**Comment by mrackwitz** [comment]
#4004 will fix this issue as extensions may have their own frameworks folder, as seen in [App Extension Essentials > Handling Common Scenarios > Using an Embedded Framework to Share Code](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW5):
>For example, if you develop an image filter for use in your Photo Editing extension as well as in its containing app, put the filter’s code in a framework and **embed the framework in both targets.** 

AppStore issues like seen below led me to the false assumption that this wouldn't be possible.

>ERROR ITMS-90205: "Invalid Bundle. The bundle at 'xxx Extension.appex' contains disallowed nested bundles."

>ERROR ITMS-90206: "Invalid Bundle. The bundle at 'xxx Extension.appex' contains disallowed file 'Frameworks'."

But seemingly they originate only from deeper file hierarchies as:

```
MyApp.app/PlugIns/MyExtension.appex/Frameworks/MyFramework.framework/Frameworks
```
