### ISSUE TITLE
No email received for 'pod trunk register'

### ISSUE THREAD

**Issue by jameswangz** [CocoaPods/CocoaPods#4030]
Hi team,

Somehow I lost my session on my MacBook so I wanted to register a new session, but it seems I couldn't get the verification email,  the command I used was:

```
pod trunk register james.wang@software.dell.com 'James Wang' --description="James' MacBook at Dell"
```

I tried to use another email and it worked,  but I must use this email because I have the FoglightAPM podspec which was owned by my dell email,  please help.

Thanks,
James

**Comment by orta** [comment]
We're seeing a lot of emails sent and classed as delivered from the dell mail server, could they be in spam?

![screen shot 2015-08-17 at 7 33 26 am](https://cloud.githubusercontent.com/assets/49038/9304085/4b30b1a4-44b2-11e5-9ada-eb79552a901d.png)

**Comment by jameswangz** [comment]
Yes they are in the Junk mail folder,  I have unjunk them and it works now,  thanks!

**Comment by xclidongbo** [comment]
@orta 


version 1.2.0

lidongbo:XCkit lidongbo$ pod trunk me
[!] Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session.
lidongbo:XCkit lidongbo$ pod trunk register xclidongbo@gmail.com 'xclidongbo' --description='macboo
kpro'
[!] Please verify the session by clicking the link in the verification email that has been sent to xclidongbo@gmail.com

**Comment by NianJi** [comment]
Same problem, use 1.7.5,   can't find email in junk folder either.
