### ISSUE TITLE
Disable cocoapods-stats, options

### ISSUE THREAD

**Issue by Ashton-W** [CocoaPods/CocoaPods#4032]
In certain strict security environments **cocoapods-stats** is not desirable. Often the networking is such that the stats plugin can't even access the outside world, unfortunately right now it 'hangs' while waiting for a timeout (I'm sure the corporate proxy is more to blame here for not following HTTP).

I'd like to get a list of ways to disable the stats plugin. I know of the environment variable, but I am hoping there is a project specific way to disable it.
Can **bundler** or **rbenv** be configured to not include the plugin or set the environment variable per project? Is there something we could add to the `Podfile`? Some kind of `.cocoapods` configuration?

---

- Environment variable `COCOAPODS_DISABLE_STATS` set to `true`.

**Comment by segiddins** [comment]
You can set the env var in your Podfile

**Comment by segiddins** [comment]
Anyways, this is a question rather than a bug report and belongs better over on SO. If there's a bug, that belongs over on the cocoapods-stats repo.

**Comment by Ashton-W** [comment]
Can I rephrase it as 'Can't disable cocoapods-stats per project'?
I was hoping this would start a `discussion` as to how we can best support users that aren't in the ideal environment.

**Comment by segiddins** [comment]
Just set the env var in the Podfile, that was my first suggestion.

**Comment by BB9z** [comment]
@Ashton-W You should set the ENV variable as a string, this works:

```
# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
```

**Comment by orta** [comment]
I updated his post :+1:
