### ISSUE TITLE
Target Deduplication removes necessary Pods project targets 🌈

### ISSUE THREAD

**Issue by smileyborg** [CocoaPods/CocoaPods#4034]
I ran into this issue when upgrading from CocoaPods `0.37.2` to `0.38.0`, and it's not fixed as of `0.38.2`.

This issue is a bit long, but only because I wanted to make it very clear what is happening -- the [sample project](https://github.com/smileyborg/CPTargetDeduplication) should make this very easy to understand.

## Background
I ran into this issue with the QuickBooks app I work on, which has an unusually complex build configuration. Aside from CocoaPods, we have a workspace of multiple separate Xcode projects, and each Xcode project generally has 2 framework targets -- one for iOS and one for Mac. This is because we use these independent Xcode projects (and their frameworks) to share code between multiple iOS and OS X apps. We're also using CocoaPods to manage our third-party dependencies.

I've created a [small git repo](https://github.com/smileyborg/CPTargetDeduplication) that contains a sample workspace that represents a simple version of the structure of our real QuickBooks workspace. In this git repo:

* `ProjectABWorkspace`
  * `ProjectA` (has a dependency on `Pods`)
    * `ProjectA-iOS`
    * `ProjectA-Mac`
  * `ProjectB` (has a dependency on `ProjectA`, and on `Pods`)
    * `ProjectB-iOS`
    * `ProjectB-Mac`
  * `Pods`

As you can see, there are 2 separate Xcode projects and a Pods project (generated by CocoaPods). Each of the `ProjectA` and `ProjectB` projects has 2 framework targets it produces, one for iOS and one for OS X. Both `ProjectA` and `ProjectB` depend on a CocoaPod (INTUGroupedArray). And finally, `ProjectB` depends on `ProjectA`, by embedding & linking the `ProjectA.framework`.

The [Podfile in this repo](https://github.com/smileyborg/CPTargetDeduplication/blob/master/Podfile) has a separate Pod target for each framework target, making 4 total Pod targets.

## The Issue
With `0.37.2` all of the framework targets build fine. (You can checkout [this commit](https://github.com/smileyborg/CPTargetDeduplication/commit/dda3a6cdf5b6fe732c5fa390728e8dffac1694a5) to see that.)

However, with `0.38.0` or higher, both of the ProjectB framework targets fail to build (use the `ProjectB-iOS` and `ProjectB-Mac` schemes). The build failure itself is within the `ProjectBFile.m` import to the INTUGroupedArray CocoaPod.

The actual issue here is more clear when you look at the git log for the repo. If you look at the diff for [the commit that runs `pod install` using `0.38.2`](https://github.com/smileyborg/CPTargetDeduplication/commit/bbd8d1f16905aa653e7e2ee31326c5a561767d0f) (after already having run `pod install` using `0.37.2`), you can see two significant sets of deletions:
* All the files in `Pods/Target Support Files/Pods-ProjectB-Mac-INTUGroupedArray/` have been removed
* All the files in `Pods/Target Support Files/Pods-ProjectB-iOS-INTUGroupedArray/` have been removed

If you look at the Pods project itself at this point, it is also missing the `Pods-ProjectB-iOS-INTUGroupedArray` and `Pods-ProjectB-iOS-INTUGroupedArray` targets. So the root cause of the compilation error is that the INTUGroupedArray pod is no longer being linked with the ProjectB targets.

CocoaPods `0.38.0` introduced [target deduplication](http://blog.cocoapods.org/CocoaPods-0.38/#target-deduplication), which appears to be causing this issue. It looks to me like the *Target Deduplicator* decided these were not necessary (even though they were) and removed them.

This issue is blocking us from upgrading beyond CocoaPods `0.37.2`.

Let me know if you have any questions or want more information!

**Comment by smileyborg** [comment]
Looking at this closer, it looks like the `Pods-ProjectB-Mac` and `Pods-ProjectB-iOS` targets in the `Pods` project actually **do** have a Target Dependency -- but it's on the **ProjectA** target. If the INTUGroupedArray Pod target is to be shared here, this doesn't seem right.

**Comment by AliSoftware** [comment]
For debugging purposes, did you try with 0.38.2 but with `target_deduplication: false` in your `~/.cocoapods/config.yaml` to opt-out of this feature and see if it solves the issue?

**Comment by smileyborg** [comment]
Oh cool, I didn't realize that `deduplicate_targets: false` was an option.

I just tried adding it to my CocoaPods config file. Then I reset the sample project repo to `dda3a6cdf5b6fe732c5fa390728e8dffac1694a5` (which is just after running `pod install` with `0.37.2`), and I ran `pod install` using `0.38.2`.

All 4 framework targets build successfully, with no errors.

Here is what the Pods project looks like after the above -- note that the Pods project does indeed have INTUGroupedArray targets for each of the framework targets:

<img width="1310" alt="screen shot 2015-08-19 at 8 18 09 pm" src="https://cloud.githubusercontent.com/assets/1372557/9374896/6ea8c028-46af-11e5-9ab9-140963bb2afe.png">

Let me give this a try with the real QuickBooks workspace just to confirm the same thing happens. But it definitely looks like this issue is being caused by the target deduplication feature as suspected.

**Comment by smileyborg** [comment]
OK, I just did the same test with our QuickBooks workspace -- disabling the target deduplication feature does indeed fix the build errors there, and running `pod install` with `0.38.2` works fine otherwise.

Let me know if you need any more info, but this seems like it should be fairly straightforward to address from here. I would use the sample project as a test case of sorts, when the target deduplication is working correctly for that project then this issue is likely fixed.

**Comment by smileyborg** [comment]
One other thing, I was looking at #3550, and just wanted to note that for this particular scenario I don't see any reason why CocoaPods couldn't or shouldn't deduplicate targets here -- the INTUGroupedArray pod target should be shared between ProjectA-iOS and ProjectB-iOS (and another target for ProjectA-Mac and ProjectB-Mac). It just seems like the current implementation is not handling this setup well causing the breakage.

**Comment by AliSoftware** [comment]
Maybe @mrackwitz would know better, he's the one who worked on this feature in 0.38

**Comment by mrackwitz** [comment]
>One other thing, I was looking at #3550, and just wanted to note that for this particular scenario I don't see any reason why CocoaPods couldn't or shouldn't deduplicate targets here -- the INTUGroupedArray pod target should be shared between ProjectA-iOS and ProjectB-iOS (and another target for ProjectA-Mac and ProjectB-Mac). It just seems like the current implementation is not handling this setup well causing the breakage.

@smileyborg: I can confirm, what you suspect here. It seems like the pod target for `Pods-ProjectA-Mac-INTUGroupedArray` is deduplicated and shared across the aggregate targets `Pods-ProjectA-Mac` and `Pods-ProjectB-Mac`, but still remains scoped. The same applies respectively for the iOS targets. I will try to dig into that and find out why that happens.

**Comment by smileyborg** [comment]
@mrackwitz Sounds good. The title of this issue should probably be something like "Target Deduplication incorrectly shares Pod target" or something.

**Comment by mrackwitz** [comment]
The issue is that the installer isn't currently integrating pod targets correctly which were **deduplicated as scoped**. To fix the integration, which would be the preferable way to resolve this over duplicating the targets, we have to:
* [ ] _optional_: scope them with a label independent from the target definition, rather a label, which indicates why they are scoped, in this case e.g. a platform specific suffix as `-iOS`, `-OSX`.
* [ ] ensure  for all aggregate targets that the scoped framework search path is included in the pod xcconfig and that the pod target frameworks are embed from the correct origins

**Comment by bassrock** [comment]
:+1:  for this. Removing target duplication fixed this issue for me as I was seeing pods not getting added to the search paths. 

For the target duplication current workaround, is there a way to set that per project?

**Comment by Brett-Best** [comment]
I posted the below in #4121.

Adding deduplicate_targets: false to config.yaml lets the project build and lets the tests build as well now I am facing the UI Tests not working see this gist for the error: https://gist.github.com/Brett-Best/c32bda701536aea337c1 the verbose pod update is here https://gist.github.com/Brett-Best/1141ec24cac6dc558a01

Regarding the reduplication will something be done to fix that in the future and as @bassrock asked can it be set in the pod file?

----
@neonichu so that wouldn't cause frameworks not getting found?
Podfile used below... The error I am getting is: ld: framework not found Alamofire

Can give more information if needed but if this isn't related to the above warnings I don't want to post it here but rather in the place that you recommend. 
Using Xcode 7 GM on OS X 10.11.
```
use_frameworks!

target 'Pazzle iOS' do
  platform :ios, '9.0'
  pod 'Alamofire'
end

target 'Pazzle iOS Tests' do
  platform :ios, '9.0'
  pod 'Alamofire'
end

target 'Pazzle iOS UITests' do
  platform :ios, '9.0'
  pod 'Alamofire'
end

target 'Pazzle OS X' do
  platform :osx, '10.11'
  pod 'Alamofire'
end

target 'Pazzle OS X Tests' do
  platform :osx, '10.11'
  pod 'Alamofire'
end

target 'Pazzle OS X UITests' do
  platform :osx, '10.11'
  pod 'Alamofire'
end

```
Thanks!

----
