### ISSUE TITLE
How to select which spec repo to use when there are same name specs in different repo?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#4035]
I package some pods in CocoaPods Spec to static framework. So I get two repos and they have same specs.

`Podfile`:
```
sourec "Framework Spec"
source "Cocoapods Spec"

pod "A"
pod "B"
```

The `A` and `B` spec are in both `Cocoapods Spec` and `Framework Spec`.

Now, I want to use source version of `A` and framework version of `B`. How should I do?

**Comment by segiddins** [comment]
CocoaPods does not support a spec being in multiple source repos at the same version, and we strongly advise against keeping the same pod in multiple repos at all -- that is intentional.

**Comment by Whirlwind** [comment]
I don't agree with you.

The version for a pod is same in multiple source repos, because a repo is binary pod and anther repo is source pod.

I hope we can pick the pod if it is both in my private repo and cocoapods repo.

**Comment by segiddins** [comment]
That's just not a scenario we intend to support, you might want to write a plugin to accomplish that instead.

**Comment by amorde** [comment]
@Whirlwind If you have control of the source repo, why not rename the binary version of the pod?

Ie. `AFNetworking-framework`

Regardless, it is well described that [Cocoapods uses the first version it can find](https://guides.cocoapods.org/syntax/podfile.html#source) that meets the version requirements, and it is intended behavior.

**Comment by Whirlwind** [comment]
@amorde If I rename the binary version of the pod, and it is dependencied by another pod, CP will not find it.

`C`'s podspec:
```
s.dependency "AFNetworking"
```

It will install `AFNetworking` rather than `AFNetworking-framework`.
