### ISSUE TITLE
Cocoapods updates my `.xcschemes`; adds '.app' suffix to all of my targets; forces me to git checkout every time

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#4040]
This is contrary to when I use AppCode, which tries to **remove** all `.app` or `.xctest` suffices from my targets.

So basically my tools can't decide which format it wants. I end up having to `git checkout` to avoid writing my Git history full of these meaningless changes.

What's the solution here?

**Comment by neonichu** [comment]
Could you be a bit more specific on what the steps are to get CP to touch your application's schemes?

**Comment by fatuhoku** [comment]
Sorry I realised that this is an AppCode issue, which they really really should fix!
