### ISSUE TITLE
CocoaPods 0.38.2 deletes public headers

### ISSUE THREAD

**Issue by joshuatbrown** [CocoaPods/CocoaPods#4041]
I have public headers under my `Pods/Headers/Public` directory that were installed with a previous version of CocoaPods. After updating to CocoaPods 0.38.2, when I run `pod update`, the entire `Public` directory is deleted. The same happens when I run `pod install`, even though it doesn't install any new pods. The end result is that I can't build my project - there are errors in my `Bridging-Header.h` related to `#import`s of CocoaPods that cause the build to fail since it can't find the header.

**Comment by segiddins** [comment]
What happens if you just delete the pods directory and re-install?

**Comment by neonichu** [comment]
Can you be a bit more specific about the headers which are deleted? It is actually intentional that headers are no longer symlinked for the `use_frameworks!` case, for example.

**Comment by joshuatbrown** [comment]
We are using `use_frameworks!`, so I suppose that explains why the headers disappeared. But why would it fail to build?

**Comment by segiddins** [comment]
Can you share the build failures, in addition to your bridging header?

**Comment by neonichu** [comment]
I think you have to use module imports for frameworks when using a bridging header and those might have incidentally worked before because there was a non-modular copy of each header as well.

**Comment by neonichu** [comment]
BTW, you also won't really need a bridging header for frameworks anyway.

**Comment by joshuatbrown** [comment]
@neonichu thanks. It appears that we need the bridging header for some non-frameworks we're using.

**Comment by segiddins** [comment]
I think @neonichu's answer about using module imports is correct.
