### ISSUE TITLE
Omit :git when using :branch from pod's repo

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#4046]
Hi,

When I want to install a specific branch of a published podspec, I have to specify :git parameter otherwise it won't work. This is absolutely impractical, I believe in most cases you use the same repo as published pod, would be great if :git parameter would be taken from podspec's source by default.

**Comment by segiddins** [comment]
This is actually impossible to do, because it the upstream git repo can change (and the pod can not be published, etc.). We've discussed adding a sort of options inheritance, but decided it was too complicated for such a small benefit.

**Comment by pronebird** [comment]
Strange to hear it was complicated because this is how you install :head builds now. What's the difference if you swap master to branch...

**Comment by segiddins** [comment]
I personally dislike `:head`, and it causes issues internally in CocoaPods...

**Comment by neonichu** [comment]
Also `:head` works different, it gives you the source files from HEAD, but the podspec from the spec repo. 

I agree that while this would be nice, it is not really worth the effort.
