### ISSUE TITLE
Podspec validation fails with CocoaPods 0.38.2

### ISSUE THREAD

**Issue by gonzalezreal** [CocoaPods/CocoaPods#4047]
Hi there,

I am not sure what's wrong with this [podspec](https://github.com/gonzalezreal/Groot/blob/master/Groot.podspec). With CocoaPods 0.37.2 it validates correctly without any issues, but since I updated to CocoaPods 0.38.2 it outputs the following if I run `pod spec lint --verbose`:

```
  Groot (1.1) - Analyzing on OS X platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `Groot` from `/Users/gonzalezreal/Documents/developer/projects/Groot/Groot.podspec`

Resolving dependencies of 
 -> Groot (1.1)
    - ERROR | [OSX] Encountered an unknown error (Unable to satisfy the following requirements:

- `Groot/Swift (= 1.1)` required by `Groot (1.1)`) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/spec/lint.rb:72:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

I have tested the pod spec in both OS X and iOS projects and builds without any issues.

Any help will be greatly appreciated.

Thanks in advance!

**Comment by segiddins** [comment]
Is the osx deployment target compatible will that of all of the dependencies?

**Comment by gonzalezreal** [comment]
That was one of the first things I tested. The pod installs and builds correctly on an os x project with the specified deployment target.

This pod depends on Foundation, Core Data and the Swift standard library (only in one of the sub specs).

Is there any command I can run to get more details about the error?

**Comment by segiddins** [comment]
Oh I know! You need to set a minimum deployment target for the root spec that matches the swift subspec 's. Sorry for the slow response!

**Comment by gonzalezreal** [comment]
It works. Thank you sir! :smile:

**Comment by lmirosevic** [comment]
+1. Was seeing the same error because my root spec had a lower min deployment target than one of the deps. Would be nice if the error messages gave a little more detail.

**Comment by neonichu** [comment]
We have improved the error message in 0.39 betas.
