### ISSUE TITLE
"transitive dependencies that include static binaries" ignores subspecs

### ISSUE THREAD

**Issue by TomHarte** [CocoaPods/CocoaPods#4048]
I have a pod, X. That pod has two subspecs. The first of these vends a static library (i.e. declares as a vendored_library). The second does not — it incorporates unbuilt .h and .m files only. The second does not depend upon the first or upon any other subspec.

I have a further pod Y that declares the second subspec as a dependency.

I have a project that imports pod Y. I am presented with the "target has transitive dependencies that include static binaries".

If this is a valid analysis of my dependency graph, am I right to think this is a bug because there is no static binary in the build chain? One is referenced by X but is not a dependency since it is not included in the subspec in use.

**Comment by segiddins** [comment]
Can you please share the podspec? It's hard to figure out what's happening without that concrete detail.

**Comment by TomHarte** [comment]
It's commercially sensitive so I'll endeavour to create a minimal reproduction.

**Comment by segiddins** [comment]
Re-reading this, my _guess_ is that this is behaving as intended because there are also source files, so the static binaries are being linked into the pod target, rather than the user's target, but I can't be sure without a concrete project.

Feel free to re-open if that guess is incorrect.
