### ISSUE TITLE
Multiple projects, Multiple targets, shared pods.

### ISSUE THREAD

**Issue by szweier** [CocoaPods/CocoaPods#4049]
I'm currently running 0.37.1

I have a workspace that is being built with 5 different xcodeproj's.  Each of these projects share numerous pods.  It seems as though my current setup is compiling these pods for each project when I try to run a scheme that tests all 5 projects.  Is it possible (using link_with or something else) to have these shared files actually be shared and compile once rather than for each?

Below is a simplified example of what my podfile currently looks like.

```
source 'https://github.com/CocoaPods/Specs.git'
workspace 'ios'
platform :ios, '7.1'

def shared_pods
 pod '1'
 pod '2'
end

xcodeproj '1.xcodeproj'
xcodeproj '2.xcodeproj'
xcodeproj '3.xcodeproj'
xcodeproj '4.xcodeproj'
xcodeproj '5.xcodeproj'

target :1_production do
  xcodeproj '1.xcodeproj'
  shared_pods
end

target :1_internal do
  xcodeproj '1.xcodeproj'
  shared_pods
end

target :2_production do
  xcodeproj '2.xcodeproj'
  shared_pods
end

target :2_internal do
  xcodeproj '2.xcodeproj'
  shared_pods
end

target :3_production do
  xcodeproj '3.xcodeproj'
  shared_pods
end

target :3_internal do
  xcodeproj '3.xcodeproj'
  shared_pods
end

target :4_production do
  xcodeproj '4.xcodeproj'
  shared_pods
end

target :4_internal do
  xcodeproj '4.xcodeproj'
  shared_pods
end

target :5_production do
  xcodeproj '5.xcodeproj'
  shared_pods
end

target :5_internal do
  xcodeproj '5.xcodeproj'
  shared_pods
end
```

It feels quite wrong to be using the shared_pods in each target like this and I'm hoping there's a solution someone can point me to that might simplify what is going on here.

Thanks

**Comment by szweier** [comment]
I saw some people talking about nesting projects to achieve something like this but haven't yet tested it. Does anyone know if that might be the path to go down?

**Comment by segiddins** [comment]
I'm guessing that this is an edge case that CocoaPods just doesn't handle ideally? Or it might just be how Xcode works -- I'm not sure whether DerivedData is per-workspace or per-project.

**Comment by szweier** [comment]
It seems like something that should be doable in some way even if not specifically through cocoapods. Having dependencies that exist in multiple projects in a single workspace compiled for each project in that workspace means running a scheme to test five projects compiles each pod for each project. It also seems like Xcode runs the scheme more efficiently than xcodebuild does. I'll be on this most of the day today. Will post back if I get anywhere.

**Comment by szweier** [comment]
If all projects use the same pods is it possible to have them all use the same Pods.debug.xcconfig and Pods.release.xcconfig rather than Pods-appname.release.xcconfig?  If so how would that be done and do we think that might allow for a more intelligent compile process when building projects?

**Comment by neonichu** [comment]
I don't think the scheme adds any additional scoping to the build products.

**Comment by szweier** [comment]
Is it possible to keep the Pods project from creating explicit targets for each project that uses say AFNetworking for example.  This seems to be adding significant time to compile times when running a scheme that tests all projects since it's building Pods-AFNetworking, Pods-Target1-AFNetworking, Pods-Target2-AFNetworking and so on (307 targets in this case) rather than all projects using Pods-AFNetworking and hopefully compiling it once when running a test scheme.

**Comment by neonichu** [comment]
That's something @mrackwitz would know.

**Comment by szweier** [comment]
Thanks @neonichu

**Comment by samdmarshall** [comment]
DerivedData locations are based on what you have open and are building from. This means if you have a workspace open, builds from within that workspace will happen into a directory based on the path of that workspace. If you open individual project, then it will be using a DerivedData location based on that path.

TBH I think that having that many targets in a single workspace is going to make the build artifacts unmanageable. If your dependency graphs are such that you need that many targets then I'd suggest looking into setting up external targets that can run `xcodebuild` for targets in project files that you don't include in the workspace. Frankly while Xcode *can* support working with this many targets I don't recommend doing this because you will quickly run into issues with build artifacts and the GUI struggling to keep up with the volume of schemes and doing implicit dependency resolution when performing builds.

**Comment by szweier** [comment]
Well, in the end we're talking about 5 projects each with an internal and production build target.  Each of those has a scheme and then two other schemes one of which tests all 5 projects (on production) and another that builds all 5 internal apps.  Having 12 schemes doesn't seem to be unmanageable currently.  The only issue that seems to be coming about from having this type of setup is that targets that pods is generating.  Ideally we'd be generating a shared Pods-AFNetworking target (for example) and all 12 targets would point to that.  Instead what we end up with is that Pods-AFNetworking being used once, and Pods-App1-AFNetworking being used and so on.  Resulting in massive amounts of seemingly useless repetition amongst pods. Which is why I'm here. Keeping these projects together is allowing us to make easier global changes to our shared internal pods and making changes across all 5 apps without having to import this new pod into 5 separate projects each time something is changed that they all share.

**Comment by szweier** [comment]
Ideally I'd like to turn off implicit dependency resolution and specific what is needed in the schemes.

**Comment by neonichu** [comment]
@szweier explicit dependencies are only possible with subprojects

**Comment by samdmarshall** [comment]
@szweier I'd have to have a better understanding of how your project configuration is setup to give any more advice at the moment but I'd hazard that you might be able to make this easier by using build configurations to your production/internal management and consolidate into a single target per project.

**Comment by szweier** [comment]
I'll look into consolidating to a single target per project.

As for the explanation of the current setup I'll try my best here:

We have a suite of 5 applications which share a far amount of components (a local pod), api (a private pod from another repo), and other third party dependencies. Of these 5 applications 4 of them use the exact same pods, the fifth application adds one other dependency which isn't required by the others. I'd like to setup my Podfile in a way that the generated workspace would know that these four applications are sharing pods and simply point to the same xcconfig etc when building to avoid multiple compiles when a scheme that has all 5 apps is run.

Hopefully that gives a better overview.

**Comment by mrackwitz** [comment]
@szweier: CocoaPods brings target deduplication with version 0.38. That ensures that as long as the targets are build on the same platform, and they and all their transitive dependencies don't differentiate in their subspec sets, are built only once. So you would have a target `AFNetworking` instead of `Pods-Target1-AFNetworking`, `Pods-Target2-AFNetworking`. They are still injected as explicit dependencies of a generated individual aggregate target per user project target, but it's works even across multiple user projects. So you should be fine by just updating your installation.

**Comment by szweier** [comment]
@mrackwitz that seemed to help a ton in speeding up the builds thank you.  I do however seem to have a problem where the tests now being run via xctool (which is specifying a destination and OS=latest throws an error when any test is run against something introduced in iOS 7 or later, for example a test on UITextView.isSelectable will return unrecognized selector.  Are you aware of this issue?  I've only upgraded to 0.38.2 which introduced this issue.

**Comment by szweier** [comment]
This also only seems to be broken when running on CircleCI, is there a minimum version of Xcode or anything that I may need to upgrade to work along with 0.38.2?

**Comment by szweier** [comment]
Looks like this second issue is on CircleCI and has nothing to do directly with the cocoa pods setup.  Thanks for helping with the issue here.
