### ISSUE TITLE
CocoaPods & OS X El Capitan 

### ISSUE THREAD

**Issue by AlGross** [CocoaPods/CocoaPods#4050]
I'm just trying to install CocoaPods on my new partition of my Mac with OS X El Capitan beta 5 but every time I (successfully) installed it and want to use it I get the error `-bash: pod: command not found`. Any ideas how to solve this?

**Comment by segiddins** [comment]
This is a RubyGems issue. Make sure it is installing Gem binaries into a directory on your `$PATH`.

**Comment by AlGross** [comment]
How to do this?

**Comment by segiddins** [comment]
verify your `gem env` is set up correctly

**Comment by AlGross** [comment]
guess it is

**Comment by neonichu** [comment]
See also <https://github.com/CocoaPods/CocoaPods/issues/3692#issuecomment-113847612>

**Comment by AlGross** [comment]
already saw it but doesn't work for me. tested to twice...

**Comment by RedPlumber** [comment]
Same for me..

**Comment by RedPlumber** [comment]
I found a solution suggested by @kylef https://github.com/CocoaPods/CocoaPods/issues/3970
