### ISSUE TITLE
"transitive dependencies that include static binaries" in a private pod with GoogleAnalytics dependency

### ISSUE THREAD

**Issue by thomasjoulin** [CocoaPods/CocoaPods#4053]
Apologies for not sharing the full Podfile, as this involves a private pod. But here is the issue:

```
source 'https://github.com/CocoaPods/Specs.git'
source 'git@git.private.com/Specs.git'

platform :ios, '8.0'
use_frameworks!

pod 'PrivateAnalytics'
````

My private repo has this podpsec:

```
Pod::Spec.new do |s|
  s.name             = "PrivateAnalytics"
  s.version          = "1.0.0"
  s.summary          = "Helper to track with Google Analytics"
  s.homepage         = 'http://www.private.com'
  s.screenshots      = ""
  s.license          = 'Redacted'
  s.author           = { "Redacted" => "redacted@redacted.com" }
  s.source           = { :git => "git@git.private.com/PrivateAnalytics.git", :tag => '1.0.0' }

  s.platform = :ios, '8.0'
  s.ios.deployment_target = '8.0'
  s.requires_arc = true
  s.source_files = 'Pod/Classes/**/*.{h,m}'
  s.dependency 'GoogleAnalytics', '3.0'

end
```

And here is the error I get:

```
$>  pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using GoogleAnalytics (3.13.0)
Installing PrivateAnalytics (1.0.0)
[!] The 'Pods' target has transitive dependencies that include static binaries: (/Path/To/Project/TestGA/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a)
```

This does not happen if I don't add `use_frameworks!` (but I want to, as I'm making a swift watch app), or if the GoogleAnalytics is only in the Podfile and not a dependency of another Pod (but I want to, since my Pod uses it)

I saw multiple issues related to transitive dependencies but not quite sure if this is supposed to be fixed as most are closed. I'd be happy with any workaround you have :)

**Comment by segiddins** [comment]
This is intended behavior -- Google really would need to provide a dynamic framework in order for it to be usable as a transitive dependency when integrating with frameworks, exactly as the error says.

**Comment by Maheepk** [comment]
Hi @segiddins,

I am using cocoapods 
1.1.0.beta.1 Latest one.

and trying to install 

platform :ios, '7.0'

inhibit_all_warnings!

use_frameworks!

pod 'Firebase'
pod 'FirebaseMessaging'
pod 'Reachability'
pod 'AFNetworking'

target 'XXX_Example' do
    pod 'XXX', :path => '../'
    
    target 'XXX_Tests' do
        inherit! :search_paths
        
    end
end

[!] The 'Pods-XXX_Example' target has transitive dependencies that include static binaries: (/Users/XXX/Desktop/XXX/XXXSDK/XXX-ios/Example/Pods/FirebaseMessaging/Frameworks/FirebaseMessaging.framework)

Please let me know how can i resolve it?

thanks,

**Comment by igordeoliveirasa** [comment]
+1

**Comment by mkalmes** [comment]
@Maheepk Do you need to use dynamic frameworks? If so, your are out of luck as long as Google provides their pods with static binaries.

**Comment by Maheepk** [comment]
yes you are right @mkalmes, but i copied all framework, not use as dependencies that worked for me.

**Comment by LinkRober** [comment]
@Maheepk  me too.but i want to use dependencies,who can help me

**Comment by Maheepk** [comment]
@LinkRober there are two way either you can use dependency or you can do put that in your folder and use as vendor framework, what issue you got?
