### ISSUE TITLE
Use of unresolved identifier 'MyPod'

### ISSUE THREAD

**Issue by oney** [CocoaPods/CocoaPods#4054]
I want to write my own Pod with Swift, and create if by `pod lib create MyPod`. Everything is good in development. After finishing development, I upload the repository to github. I create new xcodeproj and add Podfile, and then run `pod install`
```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'MyPod', :git => 'git@github.com:oney/MyPod.git'
```
However, when I use MyPod in my view controller, it says `Use of unresolved identifier 'MyPod'`

What do I miss?

**Comment by oney** [comment]
Alright, if adding `import MyPod` in view controller, the problem is resolved, But why? How to not add it?

**Comment by segiddins** [comment]
Swift requires you to add `import` statements.
