### ISSUE TITLE
Attach date to changelog entries

### ISSUE THREAD

**Issue by ashfurrow** [CocoaPods/CocoaPods#4055]
The current changelog doesn't have dates corresponding to releases. Of course, this is accessible [via rubygems.org](https://rubygems.org/gems/cocoapods), but it would be handy to have it inline.

**Comment by segiddins** [comment]
Do you mean next to the release numbers? If so, I agree this is something we should do going forward -- I'll write a script to backfill.

**Comment by orta** [comment]
:+1:

**Comment by segiddins** [comment]
(I'll also add this to Rainforest. Should those dates be UTC?)

**Comment by orta** [comment]
UTC sounds good to me

**Comment by segiddins** [comment]
@orta check out https://github.com/CocoaPods/Rainforest/issues/43
