### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ArmMkr** [CocoaPods/CocoaPods#4059]
Hi. When i try to add XNGAPIClient in my xcode project Pod file it shows error. ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+-+%2FUsers%2Farmenuhi%2FDownloads%2Funtitled+folder%2Fgnix-ios%2FPods%2FHeaders%2FPrivate%2FXNGAPIClient%2FNSDictionary%2BTypecheck.h&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
Don't forget to anonymize any private data! 

 What it means, Can any one help?

**Comment by segiddins** [comment]
There's actually an open PR that fixes this issue.
