### ISSUE TITLE
public_header_files & header_dir broken?

### ISSUE THREAD

**Issue by iragsdale** [CocoaPods/CocoaPods#4061]
Hi all, I've been trying all morning to construct a new Podspec for libsasl2 that uses the public_header_files and header_dir configurations to allow third-party code to use includes like ```#include <sasl/sasl.h>``` as it is normally used.

I've used both ruby and json specs, and tried a ton of different styles for specifying source files and public include files, and no matter what, the generated target doesn't have any public header files, and my header_dir configuration is ignored - it always ends up as '/usr/local/include' no matter what I specify in the pod spec.

If I manually move the headers to public and specify the public headers folder path to "include/sasl", other code works correctly, but I can't seem to construct a podfile that doesn't require manual updates after an install.

Is there a way to do this?

**Comment by segiddins** [comment]
Can you share your podspec? This is a usage question, and it probably belongs better on StackOverflow, as GH issues are for tracking bugs and feature requests to CocoaPods itself.

**Comment by iragsdale** [comment]
Happy to share the podspec. I'm submitting it here because I don't believe this is a usage issue, but a bug in the current version of the cocoapods tool. I'm not the only one seeing this - see the footnote here: http://www.schukin.com/achieving-awesomeness-with-local-cocoapods/.

Podspec: 
```
Pod::Spec.new do |s|
  s.name     = 'sasl'
  s.version  = '2.1.26'
  s.license  = 'BSD'
  s.summary  = 'Cyrus SASL Library.'
  s.homepage = 'http://asg.web.cmu.edu/sasl/sasl-implementations.html'
  s.authors  = 'Carnegie Mellon University'
  s.source       = { :http => "http://ftp.andrew.cmu.edu/pub/cyrus-mail/cyrus-sasl-2.1.25.tar.gz" }
  s.source_files = "include/*.h","lib/*.{h,c}", "plugins/{anonymouspec.c,anonymous_init.c,cram.c,crammd5_init.c,login.c,login_init.c,plain.c,plain_init.c,plugin_common.c,plugin_common.h,digestmd5.c,digestmd5.h}", "config.h"
  s.public_header_files = "include/*.h", "plugins/*.h"
  s.header_dir = 'sasl'
  s.exclude_files = "lib/{getaddrinfo.c,getnameinfo.c,windlopen.c}"
  s.requires_arc = false
  s.prepare_command = "        if [ -e 'configure' ]\n        then\n          ./configure --disable-gssapi\n          sed 's/WITH_DES/WITHOUT_DES/' < config.h > config.h.new \n          mv config.h.new config.h \n        fi\n"
end
```

The spec also says "If no public headers are specified then all the headers are considered public." (https://guides.cocoapods.org/syntax/podspec.html#public_header_files), and if I remove that line, all the headers still end up in the "project headers" section instead of the "public headers" section.

**Comment by iragsdale** [comment]
It appears that this functionality has been broken since https://github.com/CocoaPods/CocoaPods/commit/b07945b15bd3ecae6b95929e30b42fb8101494a9#diff-b330fa5e79c6b5e63c36c4ff6b333cdfR67. 

That setting is completely ignored unless your podfile specifies use_frameworks!, which I cannot use. So, this appears to be a bug that has existed since November.

So @segiddins, can we please reopen this issue?

**Comment by segiddins** [comment]
No, that commit didn't break things, since the "attributes" for header files only apply when building frameworks

**Comment by iragsdale** [comment]
Sorry, never looked at the source before that's what it looked like. Ignoring that check fixes the problem for me. From looking at the source, I don't see any other way to get those things to apply, and it doesn't seem like they would only apply to frameworks. I.E. it makes plenty of sense for a static library to include public headers, right?

**Comment by segiddins** [comment]
Static libraries actually don't have any headers associated with them -- you manually need to set up header search paths, which we do via `-isystem` and `-iquote`. My guess without running any code is that the `header_dir` needs to be `include` instead of `sasl`,but I have to admit the code responsible for `header_dir` is cryptic even to me.

**Comment by iragsdale** [comment]
Hmmm - that doesn't quite square up with my understanding of how builds are supposed to work in recent versions of Xcode. If you specify public headers, then Xcode will automatically copy them to ${BUILT_PRODUCTS_DIR}. Xcode will *also* look for headers and static libraries in BUILT_PRODUCTS_DIR. So, by making the headers public, they will easily be usable in other projects.

If you set PUBLIC_HEADERS_FOLDER_PATH, that will affect *where* in BUILT_PRODUCTS_DIR they go. So, to use my libsasl2 project as an example, if I make all it's headers public, and set PUBLIC_HEADERS_FOLDER_PATH to "sasl", than any other project can automatically use it as <sasl/sasl.h> without having to do any other setup, which is great.

**Comment by orta** [comment]
For reference, have you checked the other [sasl podspec](https://cocoapods.org/pods/libsasl2)?

**Comment by iragsdale** [comment]
@orta Yes, I have - it was suffering from this issue, which is why I started trying to update the spec.

**Comment by neonichu** [comment]
@iragsdale Could you please provide a reproduction sample? Using your podspec with CP 0.38.2 works just fine, the public headers end up where they should and I can use `#import <sasl/sasl.h>` just fine.

**Comment by iragsdale** [comment]
@neonichu would be happy to - what do you want to see, just the final generated Xcode project? Note that if you use the ```use_frameworks!``` setting in your Podfile it does work correctly.

**Comment by iragsdale** [comment]
Ok, I've generated a project from the spec listed and you can find it here:

https://gist.github.com/iragsdale/4b72f10a6c2bf2c36c8d

I noticed when looking through the directory that the files specified as public end up in the public headers directory, but because they aren't considered public headers in the Xcode project they don't get copied to the built products directory as expected.

**Comment by neonichu** [comment]
I'm now confused by what the actual issue is you're seeing: do you have a problem to use the headers from a user target or are we simply talking about the public headers ending up in the built products directory? The latter has never been the case, but if you're seeing a problem with the former, we will need such a project to debug the issue.

**Comment by iragsdale** [comment]
It sounds like perhaps the issue is as simple as confusing documentation. When the Podfile spec says 
```
public_header_files

A list of file patterns that should be used as public headers.
```
then it seems like it is a reasonable expectation for them to end up as public headers in the Xcode target.

If that is NOT the case, I think some clarification in the documentation might be in order - that is pretty confusing.

I'd also suggest that even if it hasn't historically worked that way, you should consider changing it. If every project copies it's public headers and generated targets to the right places in the built projects directory, then the default Xcode configuration for projects will find them automatically. I believe that is the whole reason Apple created that configuration option for targets.

**Comment by segiddins** [comment]
There's no such thing as public or private headers when building a static library -- static libraries are just a bunch of linked object files -- they're not a bundle.

**Comment by iragsdale** [comment]
I'm very confused - I don't see how you can say "there's no such thing"?

A) The configuration option exists in Xcode - I posted a screen shot in that link. B) Xcode treats those files differently - they get copied to the built files directory, where they can be found automatically by other targets during the build process.

It's true that they don't end up in a framework, but that doesn't mean that setting that configuration option doesn't have value.

Without marking those headers as public (in the Xcode target), I have to go and change the third party project to look in new places to find those files. If I *can* mark those as public, they end up in a place where the other project can find them without having to change that project. Or I can just manually change the project after installing via cocoa pods. Neither changing the 3rd party library or manually updating the pods project seem like the right thing to do.

I don't understand what the rationale would be to NOT allow setting this configuration for static libraries? Does it break other things?

Anyway, if the answer is that this should be closed "as designed", then, I guess the right thing to do is to close this issue and open a new one for updating the documentation to make clear what public_header_files actually does, and to specify that it is not applied unless you're building frameworks.

**Comment by neonichu** [comment]
I think the right expectation for a public header in CP is that you can import it from other targets when using CP. That is and has always been the case with `public_header_files`.

**Comment by iragsdale** [comment]
Ok, I guess I'll drop it, it's your project. I don't really understand why it wouldn't be useful for it to be usable from projects not managed by CocoaPods, especially in a situation where I'm trying to migrate an existing project to CocoaPods in pieces, but it's certainly not your job to convince me.

**Comment by segiddins** [comment]
It _is_ applied when not building as frameworks, since the generated XCConfig's `HEADER_SEARCH_PATHS` will only expose those headers that are marked as public.

**Comment by iragsdale** [comment]
Yeah, I understand that now.

I still think that by not marking them in the *target* as public header files you're preventing a very handy use case, and don't understand the argument for not doing that (given that it does have an effect), but if that's out of scope for you guys or there are other considerations I'm not aware of, that's fine - you can't please everyone.

However, I do think it makes sense to update the documentation to specify that they won't ever show up as public headers in the Xcode target - I wasted multiple hours trying to do that and had to open an issue to understand what was going on, I think that would save both you and other pod authors some time, if only so that you don't have to deal with another person like me. :)

**Comment by segiddins** [comment]
I think we could consider a PR that makes them public, unless that breaks something?

**Comment by iragsdale** [comment]
If that's something you guys might consider, I might look into writing one. :) In the meantime, I've added this ticket in the hopes that I might save someone else some time: https://github.com/CocoaPods/CocoaPods/issues/4069

**Comment by segiddins** [comment]
Awesome, thanks @iragsdale !

**Comment by neonichu** [comment]
@iragsdale Thanks, I agree that it makes more sense to change this than to document it, if possible. Considering all our recent adventures with clang modules, it wouldn't surprise me if changing this will break things, though :)
