### ISSUE TITLE
exclude_files ignored for resource_bundles

### ISSUE THREAD

**Issue by knox** [CocoaPods/CocoaPods#4065]
As it seems ```exclude_files``` is ignored for ```resource_bundles```. Example:

    s.exclude_files = 'Some/resources/**/Tutorial*.png'
    s.resource_bundle = { 'someResources' => [ 'Some/resources/**/*.{png,lproj}' ] }

The problem [has been mentioned before] (https://github.com/CocoaPods/CocoaPods/issues/1393#issuecomment-26402612) i think but the above does not work as expected.

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/CocoaPods/pull/4098!
