### ISSUE TITLE
- ERROR | Encountered an unknown error (end of file reached) during validation.

### ISSUE THREAD

**Issue by danieldahan** [CocoaPods/CocoaPods#4066]
Pod::Spec.new do |s|
    s.name = 'GK'
    s.version = '3.16.0'
    s.license = { :type => 'AGPLv3+', :file => 'LICENSE' }
    s.summary = 'A Powerful Data-Driven Framework In Swift'
    s.homepage = 'http://www.graphkit.io'
    s.social_media_url = 'https://www.facebook.com/graphkit'
    s.authors = { 'GraphKit Inc.' => 'support@graphkit.io' }
    s.source = { :git => 'https://github.com/GraphKit/GraphKit.git', :tag => s.version }
    s.ios.deployment_target = '8.0'
    s.osx.deployment_target = '10.10'
    s.source_files = 'Source/*.swift'
    s.requires_arc = true
end

**Comment by danieldahan** [comment]
I keep getting an issue with end of line as the comment. Any suggestions?

Thanks!

**Comment by segiddins** [comment]
I'm guessing that your pod is just failing to compile, and that's the xcodebuild error?

**Comment by danieldahan** [comment]
> GK (3.16.0)
    - ERROR | Encountered an unknown error (end of file reached) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/spec/lint.rb:72:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by danieldahan** [comment]
It doesn't even reach the build operation.

**Comment by neonichu** [comment]
The issue appears to be that the `homepage` that the spec points to is broken:

```bash
$ curl -I http://www.graphkit.io
curl: (52) Empty reply from server
```

**Comment by neonichu** [comment]
However, we should fallback to not using `HEAD` in this case, seems like `REST::DisconnectedError` is not a `REST::Error`

**Comment by danieldahan** [comment]
http://www.graphkit.io is not broken, maybe the proxy is causing an issue. It goes through an nginx proxy.

**Comment by neonichu** [comment]
Well, broken as in "does respond to HEAD requests in an unexpected way" :)

**Comment by danieldahan** [comment]
ah, yes, it is only allowing GET and POST

**Comment by danieldahan** [comment]
Thank you!

**Comment by neonichu** [comment]
Made a PR to nap (Fingertips/nap#9) so that this can be handled better, eventually.
