### ISSUE TITLE
Documentation for public_header_files could use clarification 

### ISSUE THREAD

**Issue by iragsdale** [CocoaPods/CocoaPods#4069]
(I hope this is an acceptable issue 🌈)

The pod spec documentation around header files is potentially confusing for pod authors. The spec says:

```
A list of file patterns that should be used as public headers. 

These are the headers that will be exposed to the user’s project and from which documentation will be generated. If no public headers are specified then all the headers are considered public.
```

It is very clear that files matched by this pattern will become public headers, but what CP means by a public header is not exactly the same as what a stock Xcode project means by a public header, so it might be helpful to clarify the difference.

A pod author may expect for those headers to be marked as public in the Xcode target, which will only happen if the end user has specified that they will be building frameworks. As a pod author who has been mightily confused by this, I think it would be good to clarify exactly what the effect of this setting will be (they are copied to the **cocoapods** public header directory where they can be found by projects using the CP xcconfig files), which is not the same as the traditional Xcode public header file setting (they get copied to the built projects directory).

**Comment by kylef** [comment]
Thanks for the feedback @iragsdale, if you have any suggestions for new wording, we would really appreciate any help by creating pull request and improving the wording here.

The source for this documentation can be found at https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L1027 .

**Comment by kylef** [comment]
#4104 changes this.
