### ISSUE TITLE
Allow modulemaps in public_header_files?

### ISSUE THREAD

**Issue by perotinus** [CocoaPods/CocoaPods#4070]
Module maps are still useful to projects that aren't compiled as frameworks: a pod that has a bunch of ```vendored_libraries``` can still provide a ```module.modulemap``` file that makes it easier for Swift users to use the pod.

I have this working internally with a ```vendored_library``` pod that includes a modulemap file in ```public_header_files```, but that pod does not pass linting, because the modulemap isn't considered a public header. It worked fine with and without ```use_frameworks!```, because our pods were always linked statically.

Would it be reasonable to add ```modulemap``` to the set of valid header file extensions to allow this use case? It shouldn't hurt anything, and it seems reasonable (well, at least not unreasonable) that module maps would be allowed in the header directory.

**Comment by segiddins** [comment]
@neonichu / @mrackwitz thoughts?

@perotinus my only concern with this is how it would interact with `use_framework!`, or indeed any pod that actually has source that gets built.

**Comment by perotinus** [comment]
That's a good point.

My thinking was that only podspecs that will work with this behavior need to add a modulemap to their public headers. Since headers are validated, this shouldn't break any existing pods, because they won't have modulemaps in their header files right now. Any pods that add modulemaps to their header files would have to test with and without ```use_frameworks!```.

It does create a potentially odd situation, though, where a project specifies a ```module_map``` and includes a modulemap in its ```public_header_files```. An alternative is to extend the podspec DSL and add a field, ```library_module_map``` or something, for a modulemap that should be linked into the public header files when integrating as a library. That way, pod creators can specify different module maps for the framework and library cases. That's certainly a more heavyweight change, but it won't break anyone except people who use it and don't verify that it works in all cases.

**Comment by neonichu** [comment]
Honestly, I think it makes more sense to make the vendored binary a fake framework, where you can simply drop in a module map.

**Comment by perotinus** [comment]
Hmm. That might be a long-term change we can make, but that would take quite a bit of reworking to have our libraries do that, and its not something we necessarily want to put a lot of effort into with the impending need to release dynamic libraries.

**Comment by segiddins** [comment]
Yeah, I think @neonichu's suggestion is the right one -- it's probably a mistake for CocoaPods to try and "solve" this problem, given the amount of headaches we introduced the last time we tried this.

**Comment by neonichu** [comment]
@perotinus hm, in principle it's just a matter of assembling the right directory structure, as you already have all the build artifacts.

**Comment by segiddins** [comment]
Closing because I believe the correct answer here is to use 'fake' static frameworks.
