### ISSUE TITLE
cocoa pod forcing existing static library from not using libssl.a and crypto.a 

### ISSUE THREAD

**Issue by siddhesh12** [CocoaPods/CocoaPods#4071]
without cocoa pod everything works perfect, static library using libssl.a and crypto.a for making tls connection but after installing cocoa pod static library is not using connection method from libssl.a, it is trying to use different ssl library. Is there any way force existing library to use libssl.a and crypto.a everytime. Or is there anything in cocoa pod I can change so that it won't try to change the existing library dependency ?

**Comment by neonichu** [comment]
Your description is way too broad to answer this. What is changes to lead to the behaviour you're describing and how can we reproduce it? Also check out our [contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) on how to write actionable issues.

**Comment by siddhesh12** [comment]
Sorry for giving broad answer.
I am using web socket library which use open ssl and crypto to make a tls connection, before installing pod everything was working perfect but after pod it was getting crashed with error saying ss3_connect bad access, I tried adding logs in openssl and I found out is, it is not going in ssl_handshake method and somehow system or pod forcing or overriding openssl.   
however I figured out the solution. Actually for accessing objective C categories from static library, POD was adding -objC in other linker flag. I disabled that flag from xCode, and web socket was successfully using openssl for making tls connection.

But now I am facing new problem, as I disabled -objC flag I am not able to access objective C categories from static library which are there in POD. 

Now what I thought is removing pod completely and make framework of all the libraries I want and add to project. But yes this will create one problem of updating libraries all the times and recreating framework everytime. 
I am not finding any other solution right now, If you have any other solution or suggestion it will be great :) 
Please correct me If I am doing anything wrong.

**Comment by segiddins** [comment]
This sounds like it's a problem with a specific pod that you're using?

**Comment by siddhesh12** [comment]
Yes might be. I am using AFNetworking, SDImage and yeah there are using categories so that might be the problem. Is there any way I can tell pod use -objC flag only for specified libraries ?

**Comment by segiddins** [comment]
At the moment, no.

**Comment by siddhesh12** [comment]
Alright. Hope it will in future! Thank you for quick reply.
