### ISSUE TITLE
Library not found error for AFOAuth2Client, AFgzipRequestSerializer with pod -v 0.38.2

### ISSUE THREAD

**Issue by boundsj** [CocoaPods/CocoaPods#4072]
__Issue__

Cannot build project with AFOAuth2Client, AFgzipRequestSerializer in Podfile. 

What these projects have in common is that they are really just an implementation and header file with no actual xcode project file associated with them. It seems like cocoapods is not compatible with this starting somewhere in 0.38.x. I'd be happy to make a PR to the affected libraries to make them compatible again but I'm not quite sure what exactly needs to be done, or, if this is an issue with cocoapods itself and the intention was not to drop support for this this type of project.

__Steps to Repro__

- Start with Xcode 6.4, cocoapods 0.37.2
- Build project, no issue
- Update to cocoapods 0.38.2
- Run `pod install`, clean, delete derived data
- Build project and get linker error `ld: library not found for -lPods-AFOAuth2Client` (also `ld: library not found for -lPods-AFgzipRequestSerializer` if AFOAuth2Client is removed from Podfile)
- Revert back to 0.37.2
- Run `pod install`, clean, delete derived data
- Build project, no issue

__Podfile__

```
source 'https://github.com/CocoaPods/Specs.git'

pod 'AFNetworking'
pod 'AFgzipRequestSerializer'
pod 'AFOAuth2Client'
```

**Comment by segiddins** [comment]
This sounds like a de duplication update issue, any ideas @mrackwitz ?

**Comment by neonichu** [comment]
Might just be a deintegration problem in that the linker flags still contain references to no longer existing static libraries.

**Comment by neonichu** [comment]
[This comment](https://github.com/CocoaPods/CocoaPods/issues/3274#issuecomment-98391704) could also be relevant if linker flags were ever manually edited.

**Comment by boundsj** [comment]
@neonichu @segiddins thanks that was the issue. closing.
