### ISSUE TITLE
pod lib create MyLibrary

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [CocoaPods/CocoaPods#4073]
Hi, I'm using `pod lib create Mylibrary` I follow the steps everything gets created perfect. I'm having also dependency from `RestKit`( s.dependency 'RestKit', '~> 0.25.0' ) that also works I see all the files.  
The problem is that when I build the pod from xcode I get build error
I get error from xcode `ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_AFHTTPClient", referenced from:
      objc-class-ref in `

I have try several things 
1-Change valid architectures to (armv6 armv7 armv7s)
2-Build Active Architecture Only = No
No luck

but if I use the command line `pod lib lint  my.podspec --allow-warnings --use-libraries` pass the validation.

**Comment by segiddins** [comment]
That's functioning as intended?

**Comment by orta** [comment]
It is functioning as intended, by default we declare it as iOS framework in the Podfile, you would need toremove that @cesar-oyarzun-m

**Comment by cesar-oyarzun-m** [comment]
How can I run the project inside XCODE???? @orta , I just want to make a call from the example project to my pod library

**Comment by orta** [comment]
@cesar-oyarzun-m please respect our time [and be nicer](https://realm.io/news/altconf-orta-therox-being-nice-in-open-source/). Language like that will not help.

Remove the `use_frameworks!` from your Podfile, run `pod install` again.
