### ISSUE TITLE
Use both provided path and realpath when determining clean paths

### ISSUE THREAD

**Issue by ohayon** [CocoaPods/CocoaPods#4074]
Using paths in the `"public_header_files"` key that contain symlinks raise errors that the pattern doesn't match anything. But using the same paths in iOS based pods validates fine with `pod spec lint`.

![screen shot 2015-08-25 at 4 51 10 pm](https://cloud.githubusercontent.com/assets/2587018/9479050/83c18b54-4b49-11e5-8254-f01039e6b163.png)
![screen shot 2015-08-25 at 4 39 30 pm](https://cloud.githubusercontent.com/assets/2587018/9479064/94cd59aa-4b49-11e5-9772-003bf12bafa3.png)

```
‣ pod trunk push Fabric-OSX.podspec.json
Updating spec repo `master`
Validating podspec
 -> Fabric-OSX (1.4.0)
    - ERROR | [OSX] [Fabric-OSX/Base] The `public_header_files` pattern did not match any file.

[!] The podspec does not validate.
```

**Comment by segiddins** [comment]
If using something that's symlinked, the destination of those links needs to be preserved either through another attribute or via `preserve_paths`.

**Comment by segiddins** [comment]
(It's likely fine for iOS only because iOS frameworks by default don't have `Headers` as a symlink)

**Comment by ohwutup** [comment]
that'll do it! thanks @segiddins !!

**Comment by segiddins** [comment]
This is tough, because `realpath` doesn't take into account intermediary symlinks.

**Comment by ohwutup** [comment]
hey @segiddins, just cleaning up some of my issues on GH and this is my only outstanding issue. is this still enroute to be fixed? or can we close it as moot as there is the other approach you listed above?

**Comment by segiddins** [comment]
Nope, it still exists, and fixing it isn't a huge priority.
