### ISSUE TITLE
IB_DESIGNABLE in pod: Failed to load designables from path (null)

### ISSUE THREAD

**Issue by danie11am** [CocoaPods/CocoaPods#4082]
I have an internal pod that uses IB_DESIGNABLE. Currently Xcode Storyboard gives

    error: IB Designables: Failed to render instance of MyClass: Failed to load designables from path (null)

According to this [SO post](http://stackoverflow.com/questions/28204108/ib-designables-failed-to-update-auto-layout-status-failed-to-load-designables), using `use_framework!` would solve the problem but unfortunately my app has to support iOS7. Are there workarounds for this?

This problem is also mentioned in:

- https://github.com/MuscleRumble/THLabel/issues/28

**Comment by segiddins** [comment]
No, IB designables are only support by IB when in dynamic frameworks, not static libraries.

**Comment by vickyrappier** [comment]
How to apply use_framework! only to specific pods as if i use in podfile it gives other libraries warnings and errors.

Can help.

#Side menu for panic and settings
pod 'SWRevealViewController', '~> 2.3'

#Tooltip
pod 'CMPopTipView'

#Calender
//I want to use the use 'use_framework!' only for this Calender.
pod 'FSCalendar'

**Comment by orta** [comment]
You can't do this, it's all frameworks or nothing I'm afraid. Please ask these kind of questions on StackOverflow.
