### ISSUE TITLE
Lint fails due to incompatible semver versions

### ISSUE THREAD

**Issue by knox** [CocoaPods/CocoaPods#4083]
With 0.38.2 linting my pod fails
  
    ld: malformed 64-bit a.b.c.d.e version number: 5.41.35658

The same error message was reported in #3887 which is said to be fixed in 0.38.2.

**Comment by segiddins** [comment]
@mrackwitz  should we just disable the version stuff?

**Comment by mrackwitz** [comment]
The alternative would be to check whether the version fulfills the requirements of the toolchain. But then it has really questionable sense, when it is only active for selected pods. I'd vote for disabling. :+1:

**Comment by orta** [comment]
Note: @kylef found out that `9999` is the highest integer of any component allowed by clang
