### ISSUE TITLE
pod lint uses incompatible dependency version

### ISSUE THREAD

**Issue by knox** [CocoaPods/CocoaPods#4084]
My podspec specifies platform ```:ios, '6.0'``` and a dependency to AFNetworking ```~> 2.5```. When i reference this as a development pod the best compatible version of AFNetworking gets installed, which is 2.5.4 because 2.6 requires iOS 7. But when i lint this podspec i get the following notice

    [!] The platform of the target `Pods` (iOS 6.0) may not be compatible with `AFNetworking (2.6.0)` which has a minimum requirement of iOS 7.0 - OS X 10.9 - watchOS 2.0.

Obviously an incompatible version of AFNetworking is beeing used during lint.

**Comment by segiddins** [comment]
I'm pretty sure this should actually be fixed in CocoaPods 0.38.2?

**Comment by knox** [comment]
$ pod --version
    0.38.2

**Comment by segiddins** [comment]
Can you share a podspec we can use to investigate? Thanks!

**Comment by knox** [comment]
Here is a somewhat simplified version (i have stripped a few subspecs which i found unrelated to the issue):

    Pod::Spec.new do |s|
    
        s.name            = 'mylib'
        s.version         = '1.2.foo123.4'
        s.summary         = 'something'
    
        s.author          = { 'me' => 'no@spam.com' }
        s.license         = { :type => 'No License', :text => 'Copyright (c) 2014, 2015 my company' }
        s.homepage        = 'https://gitlab.local.mycompany.de/mylib'
    
        s.platform        = :ios, '6.0'
        s.requires_arc    = true
    
        s.source          = { :git => 'https://gitlab.local.mycompany.de/mylib.git', :tag => s.version.to_s }
    
        s.subspec 'Calendar' do |t|
            t.source_files = 'mylib/Calendar/*.{h,m}'
         end
    
        s.subspec 'Classes' do |t|
            t.source_files = 'mylib/Classes/*.{h,m}'
            t.dependency 'Mantle', '~> 1.5'
            t.dependency 'mylib/Calendar'
         end
    
        s.subspec 'RequestManager' do |t|
            t.source_files = 'mylib/RequestManager/*.{h,m}'
            t.dependency 'mylib/Classes'
            t.dependency 'AFNetworking', '~> 2.5'
         end
    
	    s.default_subspecs = 'RequestManager'
    
    end

**Comment by segiddins** [comment]
This seems to be happening because the `platform` attribute (which I'd love to deprecate) isn't getting inherited by the subspec. In the meantime, if you replace it with `s.ios.minimum_deployment_target = '6.0'`, things _should_ work.

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/CocoaPods/pull/4097
