### ISSUE TITLE
SVN support custom credentials via --username and --password parameters

### ISSUE THREAD

**Issue by dalu93** [CocoaPods/CocoaPods#4086]
Hi,

I have to export a library from SVN (private library) using this command:

    svn export --non-interactive --trust-server-cert --force --username USERNAME --password PASSWORD https://scm.nexse.com/svn/eurobet/nx-betting-core-ios/trunk/ DEST_FOLDER

instead of 

    svn export --non-interactive --trust-server-cert --force https://scm.nexse.com/svn/eurobet/nx-betting-core-ios/trunk/ DEST_FOLDER

How can I achieve this?

**Comment by segiddins** [comment]
Can you not set SVN credentials globally, or via environment variables, or in the URL?
Either way, this belongs on https://github.com/CocoaPods/cocoapods-downloader if there really is a CocoaPods issue.

**Comment by dalu93** [comment]
I tried with http basic authentication in the URL, but the server rejects the authentication challenge. I will post there, @segiddins thanks!
