### ISSUE TITLE
SystemStackError - stack level too deep (0.39.beta.1 only)

### ISSUE THREAD

**Issue by adamsp** [CocoaPods/CocoaPods#4092]
:rainbow: 
- I can successfully `pod install` with 0.38.2, but `pod _0.39.0.beta1_ install` gives me the following. 
- I can reproduce this on a brand new project.
- If I remove the targets, I do not get this issue.
- I've attached the verbose output - let me know if there's anything else you need.

As an aside, I came across this while trying to [fix this issue](http://stackoverflow.com/questions/32236929/class-appears-to-be-loaded-from-different-nsbundle-in-tests-after-updating-cocoa) - I'm happy to open another issue for that if that's appropriate.

<pre>
Adams-MacBook-Pro:Closeout Adam$ pod _0.39.0.beta.1_ install --verbose
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     e16ed07..3688092  master     -> origin/master
  Updating e16ed07..3688092
  Fast-forward
   Specs/Bond/4.0.0-alpha.3/Bond.podspec.json         | 39 +++++++++++++++
   .../2.3.3/CWStatusBarNotification.podspec.json     | 24 +++++++++
   .../UIViewController+Subcontrollers.podspec.json   | 23 +++++++++
   Specs/ZSAdditions/0.1.16/ZSAdditions.podspec.json  | 23 +++++++++
   .../3.0.0-beta-9/gujemsiossdk.podspec.json         | 58 ++++++++++++++++++++++
   Specs/podtest-ios/0.1.0/podtest-ios.podspec.json   | 25 ++++++++++
   6 files changed, 192 insertions(+)
   create mode 100644 Specs/Bond/4.0.0-alpha.3/Bond.podspec.json
   create mode 100644 Specs/CWStatusBarNotification/2.3.3/CWStatusBarNotification.podspec.json
   create mode 100644 Specs/UIViewController+Subcontrollers/0.0.2/UIViewController+Subcontrollers.podspec.json
   create mode 100644 Specs/ZSAdditions/0.1.16/ZSAdditions.podspec.json
   create mode 100644 Specs/gujemsiossdk/3.0.0-beta-9/gujemsiossdk.podspec.json
   create mode 100644 Specs/podtest-ios/0.1.0/podtest-ios.podspec.json

CocoaPods 0.39.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-Closeout`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-CloseoutTests`: (``)

Finding Podfile changes
  - AviarySDK
  - BBBadgeBarButtonItem
  - CWStatusBarNotification
  - FlurrySDK
  - OHHTTPStubs
  - Reachability
  - RestKit
  - RestKit/Testing
  - SDWebImage
  - SSKeychain
  - TPKeyboardAvoiding
  - TSMessages

Resolving dependencies of `Podfile`
</pre>

### Command

```
/Users/Adam/.rvm/gems/ruby-2.1.1/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0.beta.1
        Ruby : ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /Users/Adam/.rvm/rubies/ruby-2.1.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3688092a20dea667e101f0e89e7f89d882b7ad58
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.6.0
cocoapods-trunk   : 0.6.2
cocoapods-try     : 0.5.0
```

### Podfile

```ruby
platform :ios, '8.0'

target 'Closeout', :exclusive => true do
    pod 'RestKit'
    pod 'SSKeychain'
    pod 'Reachability'
    pod 'AviarySDK'
    pod 'FlurrySDK'
    pod 'SDWebImage'
    pod 'CWStatusBarNotification'
    pod 'TSMessages'
    pod 'TPKeyboardAvoiding'
    pod 'BBBadgeBarButtonItem'
end

target 'CloseoutTests' do
    pod 'RestKit/Testing'
    pod 'OHHTTPStubs'
end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-Closeout/Pods-Closeout-acknowledgements.plist', 'bridgit-ios/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
```

### Error

```
SystemStackError - stack level too deep
/Users/Adam/.rvm/gems/ruby-2.1.1/gems/cocoapods-0.39.0.beta.1/lib/cocoapods/target/pod_target.rb:63
```

**Comment by segiddins** [comment]
Thanks, @adamsp! This should be plenty info to debug with.

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/CocoaPods/pull/4096!

**Comment by adamsp** [comment]
Tested & working, can run `pod install` succesfully with a build from that branch. You're a :star:!

**Comment by segiddins** [comment]
Ace! Will try and get that finished up this weekend
