### ISSUE TITLE
Undefined method `pod' for #<Pod::Podfile:0x007fcefa197758>

### ISSUE THREAD

**Issue by beakr** [CocoaPods/CocoaPods#410]
For some reason when I run:

``` sh
$ pod install SpaceBattle.xcodeproj
```

it outputs: `undefined method 'pod' for #<Pod::Podfile:0x007fcefa197758>`

Why would the Podfile say that `pod` is not a method?

**Comment by mobiletopcode** [comment]
I have received this issue, but the reason arent clear.

I'd like to discuss more details once you are online.
