### ISSUE TITLE
Podspec public headers documentation not clear enough.

### ISSUE THREAD

**Issue by alistra** [CocoaPods/CocoaPods#4100]
> These are the headers that will be exposed to the user’s project and from which documentation will be generated. If no public headers are specified then all the headers are considered public.

It should say:

> These are the headers that will be exposed to the user’s project and from which documentation will be generated. If no public headers are specified then all the headers in `source_files` are considered public.

Because this could mean that all headers found recursively from the root directory.

If I have a directory structure:
    
    Classes/
    Frameworks/
    Libraries/

And I have some headers in all of those, but `source_files` points at `Classes/` then it's where the documentation can get confusing.

**Comment by segiddins** [comment]
A PR to that excited targeting CocoaPods/Core would be excellent!

**Comment by kylef** [comment]
As @segiddins mentioned, a pull request would be much appreciated. The relevant file/section can be found at https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L1027

**Comment by AdamCampbell** [comment]
PR: https://github.com/CocoaPods/Core/pull/270

**Comment by orta** [comment]
thanks
