### ISSUE TITLE
"use_frameworks!" let objectC library be not found   ps：my project is based on swift language

### ISSUE THREAD

**Issue by chelsh** [CocoaPods/CocoaPods#4107]
do not use "use_frameworks!"， it is ok。
ps：AFNetworking   Qiniu  is based on ObjectC language。

![image](https://cloud.githubusercontent.com/assets/10752360/9566979/51d3406c-4f4d-11e5-9db4-7049bb689c68.png)

![image](https://cloud.githubusercontent.com/assets/10752360/9566981/6610b730-4f4d-11e5-99e6-658f3efc2a5e.png)

**Comment by chelsh** [comment]
because i want to use SwiftyJSON library which is based on swift language, and the SwiftyJSON library need add "use_frameworks!", but when i only add "use_frameworks!" ,it errors:

![image](https://cloud.githubusercontent.com/assets/10752360/9567011/32167eaa-4f4e-11e5-8a49-2023503172aa.png)

**Comment by chelsh** [comment]
![image](https://cloud.githubusercontent.com/assets/10752360/9567042/ebc48162-4f4e-11e5-8d50-0577967fab4b.png)

**Comment by neonichu** [comment]
Looks like the Qiniu SDK is using quoted imports for its dependencies, so it'll need to be updated upstream to work as a framework. You should also get rid of your bridging header and use `import` directly from Swift.
