### ISSUE TITLE
Downloads and Installs stats are not visible

### ISSUE THREAD

**Issue by priteshshah1983** [CocoaPods/CocoaPods#4109]
Hi,
I'm curious why clicking on ````Expand```` on this page: https://cocoapods.org/?q=rest2mobile does not show  the ````Downloads```` and ````Installs```` stats. Do I need to opt-in to get these stats to show up?

**Comment by segiddins** [comment]
This issue doesn't belong here, it belongs on the CocoaPods.org repo, but my guess is that your pod hadn't gotten any installs by the start of today, as stats are aggregated daily and we don't show them if there's no data.

**Comment by priteshshah1983** [comment]
Thanks @segiddins! I didn't realize there was a separate repo for CocoaPods.org, sorry about that.
