### ISSUE TITLE
[Request] Cache versions for quicker update

### ISSUE THREAD

**Issue by williammorrisssc** [CocoaPods/CocoaPods#4111]
The common workflow is
git checkout dev-branch
pod install / update
...
I am often switching between two versions and yet it redownloads each time. Ideally, we could store other versions and this would save time on the downloading times.

**Comment by orta** [comment]
CocoaPods will cache anything that has not changed in the Podfile.lock - so anything that's not changed between the branches basically. If it says 'using XXX' it means it's used the local cache.

**Comment by segiddins** [comment]
CocoaPods also has a download cache as of 0.37, and it should handle your use case. If it isn't, please share a project we can use to debug why the cache isn't being hit.

**Comment by williammorrisssc** [comment]
Okay we are using 0.35. Thanks!
