### ISSUE TITLE
0.38.0 can not specify a pod source.

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#4112]
Sometime, I need use a pod which in my private repo, and the pod is specified by another pod:

Logger.podspec
```
s.dependencies "NSLogger-CocoaLumberjack-connector"
```

I hope use my private version:

Podfile:
```
pod 'NSLogger-CocoaLumberjack-connector', :git=>"git@my.com/NSLogger-CocoaLumberjack-connector.git", :tag=>"1.5"
pod "Logger"
```

It failed:
```
[!] There are multiple dependencies with different sources for `NSLogger-CocoaLumberjack-connector` in `Podfile`:

- NSLogger-CocoaLumberjack-connector (from `git@my.com/NSLogger-CocoaLumberjack-connector.git`, tag `1.5`)
- NSLogger-CocoaLumberjack-connector
```

I remember it is ok before v0.38.

Is it a bug?

**Comment by segiddins** [comment]
Is that your entire `Podfile`?

**Comment by Whirlwind** [comment]
@segiddins It just is a part of my entire Podfile

**Comment by segiddins** [comment]
I can't determine if it's a bug or not without seeing the entire Podfile.

**Comment by Whirlwind** [comment]
I found a same issue #2902

**Comment by segiddins** [comment]
In that case, things are behaving as intended.

**Comment by Whirlwind** [comment]
I don't think so. I can't use my pod in my private repo.

**Comment by imton** [comment]
+1

**Comment by kam800** [comment]
+1
