### ISSUE TITLE
Include Acknowledgements in app

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#4114]
What's the best option to do that without using Settings.bundle? This instruction is for Settings.bundle... https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements

**Comment by mrackwitz** [comment]
There are [multiple pods](https://cocoapods.org/?q=acknowledge), which may help you to show a view controller to attribute appropriately.

**Comment by pronebird** [comment]
@mrackwitz thanks!
