### ISSUE TITLE
Possible to remove the need for 'use_frameworks!' with Swift altogether?

### ISSUE THREAD

**Issue by mhuusko5** [CocoaPods/CocoaPods#4115]
From my somewhat shallow understanding/memory of the transition to dynamic frameworks for Swift, there wasn't really any good reason other than "it's the only way it'll build" in the case of CocoaPods being built from source (since the reason *Apple* put the restriction in place, was to ease the Swift runtime mismatch hurdle).

But as of https://github.com/johnno1962/Accelerator, it seems that it's not in fact the only way it'll build, and Swift frameworks can actually be statically linked (with possible performance gains, as well as the definitive gain of being able to target iOS 7).

I guess... thoughts?

**Comment by segiddins** [comment]
Apple does not support statically linking third party swift frameworks, and I don't know that anyone has actually successfully shipped to the App Store using that particular hack.

**Comment by mhuusko5** [comment]
App Store support is the big question in my mind as well.. I guess we'll have to wait and see..

**Comment by neonichu** [comment]
I think even if this works fine for the App Store, it'd be more appropriate for a plugin than integration into CP itself. A non-standard way of building seems too fragile to be the default and I don't think adding it as an option is worth the complexity.

**Comment by mrackwitz** [comment]
I don't think that App Store support would be necessarily an issue with that.
This came already up before we had support for dynamic frameworks, but we decided as @neonichu points out, that it seems to be too fragile.
But dynamic frameworks don't have only disadvantages. They allow a better separation of resources and sharing of dependencies across app and extensions and their platforms, which reduces the size and the memory footprint of the app.
I think we can close this issue for now.
