### ISSUE TITLE
Inject custom license information in Acknowledgements.plist generated for Settings.bundle

### ISSUE THREAD

**Issue by winkelsdorf** [CocoaPods/CocoaPods#4116]
Some pods are missing license information. Non-Pod libraries have license information too.

What's the best way to integrate them automated into the Acknowledgements.plist generated by CocoaPods?

I am looking for a hook where I can adjust the generation of the plist and manually inject used frameworks/libraries and it's licenses beside the information already gathered automatically..

Somebody able to point me to the right direction?

**Comment by orta** [comment]
Please don't use our issues tracker for usage questions like this, it's really hard to try keep track of our bugs and actual issues. 

You could use - https://github.com/cocoapods/cocoapods-acknowledgements

**Comment by winkelsdorf** [comment]
Ok, sorry for the misuse. Probably best to pin that statement into README.md, using GH issue trackers for usage questions is not that uncommon and I didn't find anything about in the wiki 😁

Anyway, thanks for the hint!

**Comment by orta** [comment]
To unfortunately be a pedant, because others will see this issue, we do mention it in the [CONTRIBUTING.md](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) that is linked in the create a new issue page.

I think duplicating it in the wiki is a great idea though!

**Comment by orta** [comment]
I've added it to the wiki :+1:  - https://github.com/CocoaPods/CocoaPods/wiki/Before-you-make-an-Issue

**Comment by winkelsdorf** [comment]
Haha, ok you caught me - I didn't check the `contributing` as I knew I was not going to contribute with that question.

Great addition, hope it helps to reduce the amount of unrelated questions on the Issue Tracker :+1:
