### ISSUE TITLE
Multiple page playground error on Xcode 7 Beta 6 using Cocoapods 0.38.2

### ISSUE THREAD

**Issue by davidbjames** [CocoaPods/CocoaPods#4117]
Adding multiple pages to playgrounds causes pods to fail when building Xcode 7 Beta 6 project as a pod, using Cococpods 0.38.2 or 0.39.0.beta.3. There are no build errors in Xcode itself.

The goal here is to include playgrounds for the purpose of demonstrating how to use a library. If I run `pod lib lint` I get:

> 2015-09-01 17:20:10.878 ruby[5879:237999] warning:  The file reference for "Contents.swift" is a member of multiple groups ("Page1.xcplaygroundpage" and "Page2.xcplaygroundpage"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
>  - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
>  - NOTE  | [iOS]  <unknown>:0: error: filename "Contents.swift" used twice: '/path/to/Examples.playground/Pages/Page1.xcplaygroundpage/Contents.swift' and '/path/to/Examples.playground/Pages/Page1.xcplaygroundpage/Contents.swift'
>  - NOTE  | [iOS]  <unknown>:0: note: filenames are used to distinguish private declarations with the same name

If I remove Page2 (leaving only 1 page in the playground)

>  - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
>  - ERROR |  /path/to/Examples.playground/Pages/Page1.xcplaygroundpage/Contents.swift:87:1: error: expressions are not allowed at the top level
>  - ERROR |  /path/to/Examples.playground/Pages/Page1.xcplaygroundpage/Contents.swift:91:1: error: expressions are not allowed at the top level
>  - ERROR |  /path/to/Examples.playground/Pages/Page1.xcplaygroundpage/Contents.swift:2:8: error: cannot import module being compiled

This ^^ appears to be happening on lines where I execute a statement that is neither in a function/class or assignment to a variable.

Podspec:

    Pod::Spec.new do |spec|
      spec.name         = 'Name'
      spec.version      = '0.0.1'
      spec.license      = 'MIT'
      spec.summary      = 'summary'
      spec.homepage     = 'https://source'
      spec.author       = 'David James'
      spec.source       = { :git => 'https://path/to', :tag => spec.version }
      spec.source_files = 'Library/**/*.swift'
      spec.resources    = 'Library/**/*.md'
      spec.requires_arc = true
      spec.platform     = :ios, '9.0'
      spec.ios.deployment_target = '8.0'
      spec.dependency 'Mantle', '2.0.4' 
    end

**Comment by segiddins** [comment]
I'm fairly confident that we don't yet support including playgrounds as part of a pod's source?

**Comment by davidbjames** [comment]
It seems even if I exclude the playground, I still get the error.

`spec.exclude_files = 'Library/**/*.playground'`

**Comment by davidbjames** [comment]
But I could definitely see the use-case for supporting playgrounds for documentation.

**Comment by segiddins** [comment]
Could you share a valid podspec that we can use to debug? Thanks!

**Comment by davidbjames** [comment]
I can't really share the pod spec. :/ I know, not very helpful, but it _should_ be easy to reproduce.

Btw, fixed the exclusion (previous was wrong), which gets me back on my feet.

`spec.exclude_files = 'Library/**/*.playground/**/*'`

**Comment by neonichu** [comment]
The problem is pretty clear: since a Playground is just a directory, the individual pages will get added to the build of the Pod itself.

**Comment by davidbjames** [comment]
Cocoapods play. What a great find! Will be great for adhoc experimentation.

However, what I'm proposing is really the inverse of that, which is to use [rich](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Playground_Ref/Chapters/MarkupReference.html) (readonly?) playgrounds as a living documentation demonstrating the pod in action, including "how-to" type content.

**Comment by neonichu** [comment]
@davidbjames oh yeah, I meant that maybe that plugin could be extended to provide this functionality, i.e. if one has it installed it evaluates some kind of additional configuration, similar to CocoaPods/cocoapods-try#39

**Comment by neonichu** [comment]
I don't think there's anything we can do here.
