### ISSUE TITLE
Unable to install a pod

### ISSUE THREAD

**Issue by ttback** [CocoaPods/CocoaPods#4118]
CocoaPod info:
CocoaPod Version: 0.38.2
Ruby: ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

Podfile: 
````
platform :ios, '7.0'
pod "youtube-parser", :git => 'https://github.com/toygard/youtube-parser.git'
````

Error:
pod install
Updating local specs repositories

CocoaPods 0.39.0.beta.3 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `youtube-parser` from `https://github.com/toygard/youtube-parser.git`
[!] Unable to satisfy the following requirements:

- `youtube-parser (from `https://github.com/toygard/youtube-parser.git`)` required by `Podfile`

**Comment by segiddins** [comment]
`youtube-parser` has a minimum iOS deployment target of 8.0 (https://github.com/toygard/youtube-parser/blob/master/youtube-parser.podspec#L19). This has a better error message in the 0.39 beta.
