### ISSUE TITLE
iOS app + iOS Extensions + Mac App target :: Directory not found warnings and No such module

### ISSUE THREAD

**Issue by lluisgerard** [CocoaPods/CocoaPods#4122]
![With Mac App Target](https://raw.githubusercontent.com/lluisgerard/cocoapods-issue-mac-target/master/images/mactarget.png)
As you can see, the very same Pods for the extensions can't find the frameworks directory.
`Apple Mach-O Linker Warning`
`Directory not found for option '-F...`
And the extension:
`No such module 'SnapKit'`

I encountered this issue and to find the true source I decided to create a new project and replicate everything and start removing/adding things.

The `Podfile` looks like this:
```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

# Shared pods
def base_pods

	# Autolayout
	pod 'SnapKit'

	# Coding and debugging
	pod 'XCGLogger'

end

################################
# iOS App

target 'appWithExtensions' do
	platform :ios, '8.0'
	base_pods
	# Extra for this extension:
	pod 'FontAwesome.swift'
end

################################
# APP Extensions

# iOS SHARE EXTENSION
target 'ShareExtension' do
	platform :ios, '8.0'	
	base_pods
end

# iOS ACTION EXTENSION
target 'ActionExtension' do
	platform :ios, '8.0'	
	base_pods
end

################################
# MAC APP
target 'MacApp' do
	platform :osx, '10.10'
	base_pods
end
```

Until I found what seems to be causing it:
```
target 'MacApp' do
	platform :osx, '10.10'
	base_pods
end
```

This has been a real headache because I was trying to solve it by going to the iOS extensions, and playing with the Framework search paths, etc...

When removing the target `MacApp` and mac pods from the `Podfile` you can finally compile everything again without issues (that warning is unrelated):
![Withput Mac App Target](https://raw.githubusercontent.com/lluisgerard/cocoapods-issue-mac-target/master/images/nomactarget.png)

Right now I'm using `CocoaPods 0.39.0.beta.4` but I upgraded to it because of this issue, so I'm sure this happens also on the current release.

You can download the source code here in this repo https://github.com/lluisgerard/cocoapods-issue-mac-target

I think this is a bug from CocoaPods but maybe is something I should be doing when having multiple targets and multiple platforms at the same time? Any ideas? Thank you all :+1: 

*My workaround in the meantime is to add the only libraries I need for Mac manually

**Comment by neonichu** [comment]
I'm not sure we can do much here from the CocoaPods side, you are basically running into a variant of [this Xcode bug](http://openradar.appspot.com/22392501). Implicit dependencies are generally stringly typed in Xcode, so if you have two frameworks with the same module name, but different platforms, it doesn't work.

**Comment by lluisgerard** [comment]
@neonichu maybe you are right. Now that I removed the mac target, the archive works but sometimes I can see some errors of `import` failing for a blink. But it only fails when doing it with CocoaPods in my case. Will keep an eye on it.
I forgot to mention, I'm using `Xcode 6.4`

If this is the "accepted" answer I will close this issue in the next hours.

**Comment by lluisgerard** [comment]
I close the issue, will keep an eye on that radar that @neonichu mentioned.
