### ISSUE TITLE
Would be nice to have a "Done" statement after pod install

### ISSUE THREAD

**Issue by thisisjeffwong** [CocoaPods/CocoaPods#4124]
This is useful when using the Xcode Cocoapods plugin and the output goes to Xcode console, but you don't get a prompt telling you it's done, like on Terminal.

**Comment by orta** [comment]
In this case bundler does this:

``` sh
...
Using second_curtain 0.3.0
Installing slather 1.8.1
Using bundler 1.10.6
Bundle complete! 8 Gemfile dependencies, 94 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

TBH though, I don't think your use case is a good example of _why_ we should have one, that is just that the plugin isn't waiting to see when the command has finished - they could add it very easily.

**Comment by neonichu** [comment]
I think a bundler-style summary message would make sense, especially considering that we end on "Sending stats" now.
