### ISSUE TITLE
Xcode won't archive to "iOS Apps". Goes to "Other Items" instead

### ISSUE THREAD

**Issue by frakman1** [CocoaPods/CocoaPods#4125]
(Please bear with me, I am an absolute newbie to cocoapods and Xcode dependency/build settings management. I have however used Xcode+Pods to submit an app to the AppStore successfully in the past with my setup)
versions:

COCOAPODS: 0.39.0.beta.4 (recently updated from 0.38.0)
XCODE: Version 6.3.2 (6D2105)
MAC: MacbookAir .Yosemite:10.10.3 (14D136)
for Platform :iphone iOS 8.3

I've been using cocoapods for a while now with no problems (I have only one entry for EZAudio). I recently added a dependency (pod 'XCDYouTubeKit', '~> 2.2.0'). Although everything compiles and builds fine for my iPhone, I can no longer get the "Archive" command to properly output to the "iOS Apps" Instead, it keeps outputting to the "Other Items" section. I checked the package's Info.plist and it is indeed missing the ApplicationProperties key. 

During the "pod install" phase. I saw this message (I don't think it is an error since I was able to open the resultant xcworkspace file. I checked and I already have the $inherited flag set in Target-Build Settings->Apple LLVM 6.1 Custom Compiler Flags -> Other C Flags ->Release

[!] The `LIFX Ambience [Release]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods-LIFX Ambience/Pods-LIFX Ambience.release.xcconfig'. This can lead to problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.

(edit:I removed the other c flags build setting and it reverted to non-bold ie non overwritten, and the error/warning went away. However, the "Archive" command still does not work)

I've read all the various issues and forums regarding this type of issue but I don't understand the terms used exactly in the proposed solutions (how do I remove "Copy Pods Resources" and "Check Pods Manifests.lock"? I found references to them in .xcodeproj->project.pbxproj but aren't we supposed to use .xcworkspace now?). In any case, they all say that it is fixed in this version. multiple "pod install" and "pod update" s didn't make any difference either.

-I checked and made sure that the Installation Directory for the main target app is in /Applications 
-I made sure "skip install" was NO for main target and YES for the pods.
-I tried removing the entry under: Packaging, Private Headers Folder Path and Public Headers Folder Path: /usr/local/include. no difference

Let me know if I missed anything or if you have any further questions. I will be happy to provide more details. 

Thank you for your consideration. My apologies in advance if I missed something obvious.

**Comment by frakman1** [comment]
As a test, I reverted to version "cocoapods-0.38.0" and now it works again. That was the only change.
I hope that helps somebody.

**Comment by segiddins** [comment]
Your edit comment makes it sound as if you resolved the issue?

**Comment by frakman1** [comment]
No, the edit comment was something I tried (while I was writing up the issue) that made the "pod install" warning go away but still resulted in the Archive not working. I had to do a "sudo gem uninstall cocoapods" and revert to an earlier version before it would work again.

**Comment by gregcotten** [comment]
This happens with me as well.

**Comment by segiddins** [comment]
I think this is the same as another issue which points the problem at setting he public and private attributes on headers.

**Comment by frakman1** [comment]
As I mentioned in the issue description, I tried that but without  success:

"-I tried removing the entry under: Packaging, Private Headers Folder Path and Public Headers Folder Path: /usr/local/include. no difference"

Is that what you meant?

Regardless, rolling back the version of cocoapods shouldn't fix this.

**Comment by gregcotten** [comment]
Rolling back certainly fixed it for me!

**Comment by neonichu** [comment]
@frakman1 can you see any difference between the integration with the different versions? Are you positive you're not seeing #4119?

**Comment by frakman1** [comment]
All right, I looked into it again and this is indeed issue [#4119](https://github.com/CocoaPods/CocoaPods/issues/4119)

I updated to version 0.39.0.beta.4 of cocoapods and went through **EACH** pod's `Build Settings`->`Packaging` and cleared the `Public Headers Folder Path` and `Private Headers Folder Path` entries. 
(In my earlier test,  I must have only cleared one of the Pods)

This time, creating an archive worked. I don't understand why though. Could someone please explain what is going on? Thank you

**Comment by neonichu** [comment]
Thanks for checking, it's a bug introduced by a supposedly small change in beta 4, we're going to fix it for the next beta. Since this turns out to be a duplicate, I'm closing it.

**Comment by georgbachmann** [comment]
@neonichu do you already know when you will be releasing the next beta? cause the clearing of the headers didn't fix it for me and I am already pretty frustrated :(
