### ISSUE TITLE
Make Sending Stats an optional behaviour ? It's sometimes very slow.

### ISSUE THREAD

**Issue by lzwjava** [CocoaPods/CocoaPods#4128]
![image](https://cloud.githubusercontent.com/assets/5022872/9698006/e63b0a76-53d7-11e5-9536-45dc2f4fe72b.png)

The program blocked for 5 minutes. I'm in China. So I think may be in some countries, sending stats may be very slow.

Pod sometimes say 'Failed to send stats:  Operation timed out - SSL_connect', but when the internet is not blocked totally, just some other reason makes it cannot send data. Pod can block for a long time.

So could you make an option `--no-sending-stats` to make it optional.

I always use `pod install --verbose --no-repo-update` make pod fast and use it very a lot. Now sending stats part gradually become slow. So propose this idea to make pod fast.

@segiddins

**Comment by orta** [comment]
Stats has always been optional, you can add `ENV["COCOAPODS_DISABLE_STATS"] = "true"` to your Podfile it will not send it. Also, `0.39+` sends stats async so it shouldn't exhibit the same behavior in terms of locking your terminal.

**Comment by joarwilk** [comment]
@orta Just want to highlight that this issue still remains for me. The install runs fast and then stops on "sending stats". Disabling stats decreases runtime by a non-significant factor.

Version 1.5.3

**Comment by amorde** [comment]
@joarwilk yup that is tracked in #8316
