### ISSUE TITLE
How to develop a pod which by another dependency?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#4134]
I want to develop a pod project `FBDetail`, and it dependency the project `FBTrade`. But the `FBTrade` dependency my `FBDetail`, so they are the `Cycle dependences`.

The podspec of `FBTrade`:
```
s.name = 'FBTrade'
s.dependency 'FBDetail'
```
If I just pod the `FBTrade` in my podfile of `FBDetail`:
```Podfile
pod 'FBTrade'
```
The CP will clone `FBDetail` from private source, then I have duplicate symbols.

How to solves the `Cycle dependences`?

**Comment by segiddins** [comment]
If you have two pods that form a cyclic dependency, then they really should be just one pod.

**Comment by Whirlwind** [comment]
But In my company, there are many modules must dependency others, and be dependencies by others, but they are developed by different teams.

**Comment by neonichu** [comment]
I don't think it will be possible for CP (or any dependency manager really) to solve this for you.

**Comment by mrackwitz** [comment]
One other solution can be:

1. extract the subset of functionalities of `FBDetail` you need in `FBTrade` in an own dedicated pod e.g. `FBShared`
2. depend from `FBTrade` on `FBShared`
3. depend from `FBDetail` on `FBShared` and `FBTrade`

But this only possible when the subset described in `1.` doesn't depend in itself on `FBTrade`. If you can't weaken the dependencies and reduce the coupling of the components, than it really should be just one pod.

**Comment by Whirlwind** [comment]
Sometimes, there are three pods that called `A`, `B` and `C`. 

`A` -> `B` -> `C`, but `C` -> `A`!!!

They are not directly dependencied by other, but they still are `cyclic dependency`.

**Comment by segiddins** [comment]
Yeah, the solution is the same.
