### ISSUE TITLE
error: integer literal overflows when stored into 'Int'

### ISSUE THREAD

**Issue by Cee** [CocoaPods/CocoaPods#4138]
I want to push my spec [PFColorHash](https://github.com/PerfectFreeze/PFColorHash) to CocoaPods and use `pod spec lint --verbose` to find out the problem. The pod tells me that `error: integer literal overflows when stored into 'Int'`.

When I checkout this repo on another Mac, it passes the test! This is a strange problem. 

In addition, my `.podspec` file used to be:
```ruby
Pod::Spec.new do |s|
  s.name                  = "PFColorHash"
  s.version               = "0.1"
  s.summary               = "Generate color based on the given string."
  s.homepage              = "https://github.com/PerfectFreeze/PFColorHash"
  s.license               = { :type => "MIT", :file => "LICENSE" }
  s.author                = { "Cee" => "cee@chu2byo.com" }
  s.social_media_url      = "https://twitter.com/Ceecirno"
  s.platform              = :ios 
  s.ios.deployment_target = 8.0
  s.source                = { :git => "https://github.com/PerfectFreeze/PFColorHash.git", :tag => "v#{s.version.to_s}" }
  s.source_files          = "Class/*.swift"
  s.requires_arc          = true
end
``` 

And I changed `s.ios.deployment_target = 8.0` to `s.ios.deployment_target = 8.1`, this repo also passed the lint test. 

So now I don't know what's wrong with this repository. :(

**Comment by segiddins** [comment]
I'm guessing that failure is happening when longing your pod, and thus is coming from the swift compiler?

**Comment by Cee** [comment]
I fix this problem after adding a new tag to this repo.
