### ISSUE TITLE
At the same time there are multiple lint command

### ISSUE THREAD

**Issue by charlesdbs** [CocoaPods/CocoaPods#4140]
[!] /usr/bin/unzip /private/tmp/CocoaPods/Lint/Pods/MagicPlayer/file.zip -d /private/tmp/CocoaPods/Lint/Pods/MagicPlayer

unzip:  cannot find or open /private/tmp/CocoaPods/Lint/Pods/MagicPlayer/file.zip, /private/tmp/CocoaPods/Lint/Pods/MagicPlayer/file.zip.zip or /private/tmp/CocoaPods/Lint/Pods/MagicPlayer/file.zip.ZIP.

I have a program to using lint comman to check podspec，it seams different time have different result. I think maybe because  zip file in the same  directory  .

**Comment by neonichu** [comment]
The problem description is pretty vague, please check out our [contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) and add more information.

**Comment by segiddins** [comment]
Closing due to lack of follow-up.
