### ISSUE TITLE
`use_frameworks!` fails to resolve transitive dependencies

### ISSUE THREAD

**Issue by Ruenzuo** [CocoaPods/CocoaPods#4141]
I couldn't reproduce this issue with completely new and empty application Xcode project/Podspecs, yet I feel I'm missing something obvious here.

I can't use `XNGAPIClient` on a Swift project using `use_frameworks!`. Xcode complains about missing symbols related to AFNetworking. If I modify the `XNGAPIClient.podspec` file to include AFNetworking as a dependency everything works as expected.

You can check the issue on this example project: https://github.com/Ruenzuo/Test
You can check my attempt to reproduce the issue here: https://github.com/Ruenzuo/Test/tree/reproduce_steps (Same project, LibraryA (that would be XNGAPIClient) depends on LibraryB (that would be XNGOAuth1Client) which depends on AFNetworking, this one is working  ¯\_(ツ)_/¯)
And the actual thing working (with the fix mentioned before): https://github.com/Ruenzuo/Test/tree/fixed

**Comment by segiddins** [comment]
It sounds like the fix is to add the AFNetworking dependency to the podspec?

**Comment by Ruenzuo** [comment]
Yeah, I'm just wondering why is that? shouldn't that be resolved by CocoaPods?

**Comment by segiddins** [comment]
If `XNGAPIClient` directly depends on `AFNetworking`, it'll need to declare that dependency in it's Podspec.

**Comment by Ruenzuo** [comment]
I get that, but it doesn't. It directly depends on `XNGOAuth1Client`.

**Comment by segiddins** [comment]
I get that, but if changing the spec fixes it... ¯\_(ツ)_/¯

**Comment by Ruenzuo** [comment]
¯\_(ツ)_/¯

**Comment by neonichu** [comment]
As @segiddins said, the issue is that there is also a direct dependency from XNGAPIClient on AFNetworking. When using static libraries, this distinction never mattered, but with frameworks, this will be visible because each framework on its own also needs to link successfully.

**Comment by Ruenzuo** [comment]
@neonichu oh, so with direct dependency you mean that for instance in this [case](https://github.com/xing/XNGAPIClient/blob/4e939a160a28303831c654f3d4531cc7a2c18cab/XNGAPIClient/XNGOAuthHandler.m#L81), we need AFNetworking symbols to resolve that type (`AFHTTPRequestOperation`) right? That was fine with static libraries but it doesn't really work with frameworks?

**Comment by neonichu** [comment]
@Ruenzuo Yep, that's what I meant.

**Comment by Ruenzuo** [comment]
@neonichu ah got it! Thanks for the explanation Boris :blush:
