### ISSUE TITLE
Don't crash if the argument provided to `pod repo lint` is not a directory

### ISSUE THREAD

**Issue by yellokrow** [CocoaPods/CocoaPods#4142]
After uninstalling cocoapods-* using gem and deleting the .cocoapods folder, I reinstalled it. I issued `pod setup` after the install. When I issue the command `pod repo lint PodSpecName.podspec` for my previously working podspecs I get the error 'ENOTDIR - Not a directory'. I even tried to copy and paste the Artsy podspec from the tutorials on cocoapods.com and I get the same error when running the command. Help would be appreciated.

Linting spec repo `artsy.podspec`

[in /Users/MyUserName]

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod repo lint artsy.podspec
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cb3d21caae2d3bbc729584b2818628a75155d259
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby

```

### Error

```
Errno::ENOTDIR - Not a directory - artsy.podspec
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/source.rb:90:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/source.rb:90:in `entries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/source.rb:90:in `pods'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.38.2/lib/cocoapods-core/source/health_reporter.rb:53:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/repo/lint.rb:48:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/repo/lint.rb:40:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/repo/lint.rb:40:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by segiddins** [comment]
This is happening because you have no specs repo named artsy.podspec. You maybe meant pod spec lint or pod lib lint? In any case, we should be giving a nicer error here, thanks for reporting it!

**Comment by yellokrow** [comment]
Thanks.

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/pull/4442.
