### ISSUE TITLE
Build configuration names are UPPER_CASED and set as preprocessor macros, which can cause build errors

### ISSUE THREAD

**Issue by irace** [CocoaPods/CocoaPods#4143]
CocoaPods takes build configurations like **Debug** and **Release** and auto-magically snakecases and uppercases their names to create preprocessor macros like **DEBUG** and **RELEASE**. This is problematic if you include a pod that is not expecting one of these macros to exist, and can result in an error such as the following (sample project [here](http://cl.ly/3U0m0P3b2G2x/CocoaPodsBuildConfigurationPreprocessorBug.zip)):

<img width="1072" alt="screen shot 2015-09-08 at 8 36 16 pm" src="https://cloud.githubusercontent.com/assets/399560/9750700/4b0da948-5669-11e5-8a55-2ede3705b0ed.png">

According to @mrackwitz this can be worked around by clobbering these macros in post-install hook, though I have not yet figured out how to actually do this.

**Comment by brianmichel** [comment]
This is precisely the problem I ran into.

**Comment by jaredsinclair** [comment]
Present at least as recently as 0.38.2.

**Comment by irace** [comment]
> Present at least as recently as 0.38.2.

And as early as 0.38.0.

**Comment by mrackwitz** [comment]
As a temporary workaround the following _untested(!)_ post install hook could help:
```ruby
post_install do |installer|
  # Remove automatically added preprocessor macro named after
  # the configuration to avoid conflicts with identifiers in source.
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = nil
  end
end
```

**Comment by irace** [comment]
This worked, thank you so much @mrackwitz
