### ISSUE TITLE
Duplicate symbols error

### ISSUE THREAD

**Issue by bawn** [CocoaPods/CocoaPods#4145]
I'm using the latest version 0.38.2 cocoapods, For more information see [demo](https://github.com/bawn/CocoaPodsDemo), This project is the existence of such an error.

**Comment by neonichu** [comment]
You have manually edited the linker flags of your application target at some point in that project and need to clear them out so that the XCConfig settings can be applied again.

**Comment by bawn** [comment]
@neonichu Thanks
