### ISSUE TITLE
Investigate tvOS support

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#4149]

**Comment by danydev** [comment]
That would be cool!
I'm curious if someone has some temporary workaround to make it working.

**Comment by blanham** [comment]
I'm looking into it now

**Comment by segiddins** [comment]
https://github.com/CocoaPods/Core/pull/263

**Comment by neonichu** [comment]
Also CocoaPods/Xcodeproj#301and #4152

**Comment by neonichu** [comment]
Those branches seem to work fine in a real project integrating Alamofire (<https://github.com/neonichu/Alamofire/blob/tvos/Alamofire.podspec#L13>), so I think the investigation can be closed and discussion can happen in the actual PRs. :mag:
