### ISSUE TITLE
Xcode 7 crashes when opening the Pods.xcodeproj or the Workspace

### ISSUE THREAD

**Issue by reesemclean** [CocoaPods/CocoaPods#4150]
Hey,

I have a few Pod projects created using the `pod lib create` tool that have been working great up through Xcode 6.4. When I try to open the workspace in Xcode 7, after a few seconds Xcode crashes with the following crash log: https://gist.github.com/reesemclean/76a81a5d9150cc50d79f

This happens when I open the Pods.xcodeproj on it's own as well. Opening the example project file (not the workspace) does not crash though.

If I comment out the local pod from the pod file and do a `pod install` I am able to open the project:

    target 'Tests', :exclusive => true do
       pod "Nimble"
        # pod "PROMaterialDesignKit", :path => "../"
    end

Any ideas what might be happening here? Thanks!

**Comment by segiddins** [comment]
¯\_(ツ)_/¯ that seems like an Xcode bug to me, since it should be resilient against opening any project file

**Comment by reesemclean** [comment]
What's weird is that it is happening for all 3 of the projects we have that were created using the `pod lib create` tool.

And now checking 7.1 beta 1 those same projects are working fine. Hmm...

**Comment by neonichu** [comment]
@reesemclean did those projects open fine with earlier betas of Xcode 7?

**Comment by reesemclean** [comment]
They did not – the first one that I tried was the beta before the GM (I tried it yesterday and was hoping it would be working when the GM came out).

**Comment by neonichu** [comment]
Strange — are you able to share one of those projects? Does this also happen on a new one you create right now?

**Comment by marcelofabri** [comment]
I've seen this crash on projects created using [liftoff](https://github.com/thoughtbot/liftoff/). Turns out that the culprit in that case was that the Storyboards where being added to the Compile build phase (https://github.com/thoughtbot/liftoff/issues/239).

**Comment by reesemclean** [comment]
Yep, I just narrowed it down to that. We have a storyboard in the folder of the source_files path and no specifier of file suffix. Remove it and the crash goes away.

**Comment by reesemclean** [comment]
Example project: https://github.com/reesemclean/CocoaPods_Issue_4150

**Comment by marcelofabri** [comment]
@reesemclean I think that the problem is that your Podspec is including the storyboard as a source file (`s.source_files = 'Pod/Classes/**/*'`).

I've created a test library (using `pod lib create`) and it does the right thing and doesn't add any Storyboards to the Compile build phase.

Maybe CocoaPods could be smart and warn you (on lint?) if your Podspec is adding a Storyboard as a source file.

**Comment by segiddins** [comment]
The bug is exactly what Marcelo pointed out.
