### ISSUE TITLE
https://github.com/CocoaPods/Specs.git: No such file or directory

### ISSUE THREAD

**Issue by nishantdongare** [CocoaPods/CocoaPods#4156]
I am clicking on pod file present on my project. It is showing this error. Can anyone help me with this.

**Comment by neonichu** [comment]
Could you elaborate a bit more what you mean by "clicking on pod file"? Please also check our [contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) for more advice on how to give us all the information we need for acting on issues.

**Comment by nishantdongare** [comment]
Sorry for posting it so badly. I solved this issue. It was a permission issue. Thanks Neonichu

**Comment by tanjiaweiGitHub** [comment]
source 'https://github.com/CocoaPods/Specs.git'


source: no such file or directory: https://github.com/CocoaPods/Specs.git

![image](https://user-images.githubusercontent.com/42061835/70999098-b3089200-2113-11ea-95fd-de17c87fe77a.png)

**Comment by vaynevayne** [comment]
same issue  
<img width="612" alt="image" src="https://github.com/CocoaPods/CocoaPods/assets/124666577/e84b1e53-af18-4080-87ff-5a91004b7c51">
