### ISSUE TITLE
Cocoapods on SVN

### ISSUE THREAD

**Issue by priore** [CocoaPods/CocoaPods#4158]
How can I use the pods files from a remote SVN server, a private server protected by username and password, after creating the complete structure needed for Cocoapods ?

thanks

**Comment by segiddins** [comment]
@priore this is a usage question that belongs more on StackOverflow than here -- GH issues is for tracking bugs in CocoaPods itself.

You might find that https://guides.cocoapods.org/syntax/podspec.html#source from our guides answers this particular question, though.
