### ISSUE TITLE
Framework using pods leads to crash

### ISSUE THREAD

**Issue by codepodu** [CocoaPods/CocoaPods#4159]
I have an app `TestApp`, which embeds a framework `SDK` which uses one or more pods (`Alamofire` in my example)

Running TestApp in a simulator works perfectly. However, running it on any device (iPad 3, iOS 8.4.1 in my case) leads to a crash with this message: 

```
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/mobile/Containers/Bundle/Application/493A4A6B-D0C8-4D35-9073-DA71D61A5C79/TestApp.app/Frameworks/SDK.framework/SDK
  Reason: image not found
```

This was the closest I'd seen on SO - http://stackoverflow.com/questions/29126835/swift-framework-depending-on-cocoa-pod but the solutions there didn't work :(

Test project here: https://github.com/codepodu/pods-framework-issue
1. Podfile is in /SDK/. Run pod install
2. Open the workspace.
3. Run TestApp in device.

**Comment by neonichu** [comment]
Yah, this won't work because we cannot embed frameworks into the SDK.framework because that will be rejected by the App Store. You will need to add its dependencies manually to the Podfile of TestApp or preferably integrate SDK.framework via a podspec of its own.

**Comment by JoeMatt** [comment]
I don't know if this will be accepted into the store but our app is doing the following,

1. Run the embed frameworks script on the framework target
By adding Script phase to SDK framework
`"${SRCROOT}/Pods/Target Support Files/Pods-SDK/Pods-SDK-frameworks.sh"`
2. Re-code sign after copying frameworks in main target using this script as the last build phase https://gist.github.com/JoeMatt/ac39261692f67bbe9e5d

This has worked for me using AdHoc distributed builds, we haven't submitted to store yet so I can't comment on that.

**Comment by segiddins** [comment]
What @neonichu said is the official cocoapods stance -- we don't really support integrating pods into framework / library targets, and instead recommend those be built as pods themselves.
