### ISSUE TITLE
Updated xcodeproject generates generic archive

### ISSUE THREAD

**Issue by mark2b** [CocoaPods/CocoaPods#4160]
After updating to CocoaPods 0.39.0.beta.4, Xcode Build Archive builds generic archive (can not be uploaded to AppStore)
Rolling back to release 0.38 fix it

**Comment by segiddins** [comment]
This is a known issue with beta 4.

**Comment by ZuYuanZhou** [comment]
My god, struggle several hours in this issue...

**Comment by neonichu** [comment]
Closing as a duplicate of #4119
