### ISSUE TITLE
Command /bin/sh failed with exit code 23

### ISSUE THREAD

**Issue by alexliubj** [CocoaPods/CocoaPods#4162]
sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23

**Comment by alexliubj** [comment]
Xcode 7 + with swift 2.0

**Comment by alexliubj** [comment]
cocoapods-0.38.2.

**Comment by segiddins** [comment]
I believe this is a known issue with app extensions.

**Comment by alexliubj** [comment]
@segiddins what do you mean by 'app extensions'?

**Comment by alexliubj** [comment]
Fix by doing this:

http://stackoverflow.com/questions/31914456/no-such-file-or-directory-2-for-libswiftsecurity-dylib-on-xcode-7-beta-5
