### ISSUE TITLE
[0.39.0.beta.4] Failing to resolve public pod dependency in private Pod Spec Lint

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#4163]
In my podspec I want to use version 2.2.x:

    s.dependency 'MagicalRecord', '~> 2.2.0'

With Cocoapod 0.39.0.beta.4:

    $ pod spec lint --verbose --allow-warnings
    
        MyCoreDataStore (0.1.2) - Analyzing on iOS 7.0 platform.
      Preparing
    
    Analyzing dependencies
    
    Fetching external sources
    -> Fetching podspec for `MyCoreDataStore` from `/Users/coeur/Development/MyCoreDataStore/Example/Pods/Local Podspecs/MyCoreDataStore.podspec.json`
    
    Resolving dependencies of 
     -> MyCoreDataStore (0.1.2)
        - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
        - ERROR | [iOS] unknown: Encountered an unknown error (Unable to satisfy the following requirements:
    
    - `MagicalRecord (~> 2.2.0)` required by `MyCoreDataStore (0.1.2)`) during validation.
    
    Analyzed 1 podspec.
    
    [!] The spec did not pass validation, due to 1 error.
    
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/command/spec/lint.rb:77:in `run'
    /Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.4/lib/cocoapods/command.rb:48:in `run'
    /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.4/bin/pod:44:in `<top (required)>'
    /usr/bin/pod:23:in `load'
    /usr/bin/pod:23:in `<main>'

With Cocoapod 0.38.2:

    $ pod spec lint --verbose --allow-warnings
    
        MyCoreDataStore (0.1.2) - Analyzing on iOS 7.0 platform.
      Preparing
    
    Analyzing dependencies
    
    Fetching external sources
    -> Fetching podspec for `MyCoreDataStore` from `/Users/coeur/Development/MyCoreDataStore/Example/Pods/Local Podspecs/MyCoreDataStore.podspec.json`
    
    Resolving dependencies of 
    
    Comparing resolved specification to the sandbox manifest
      A MyCoreDataStore
      A MagicalRecord
    
    Downloading dependencies
    
    -> Installing MyCoreDataStore (0.1.2)
      > Copying MyCoreDataStore from
      `/Users/coeur/Library/Caches/CocoaPods/Pods/External/MyCoreDataStore/1c677faa3af05fdf708b581217de20ac-f933c`
      to
      `../../../../../../private/var/folders/ls/z6kqgrv51535ndzfg6fzd7rm0000gn/T/CocoaPods/Lint/Pods/MyCoreDataStore`
    
    -> Installing MagicalRecord (2.2)
      > Copying MagicalRecord from
      `/Users/coeur/Library/Caches/CocoaPods/Pods/Release/MagicalRecord/2.2-f8a56`
      to
      `../../../../../../private/var/folders/ls/z6kqgrv51535ndzfg6fzd7rm0000gn/T/CocoaPods/Lint/Pods/MagicalRecord`
      - Running pre install hooks
    
    Generating Pods project
      - Creating Pods project

**Comment by neonichu** [comment]
This is the same issue as #4175 — there's no version 2.2.0 of MagicRecord, only 2.2

**Comment by Coeur** [comment]
@neonichu , how to specify you want anything *2.2.x* if *'~> 2.2.0'* doesn't work for 2.2?

**Comment by Coeur** [comment]
OK, I guess the fix is to use '< 2.3' when you want anything 2.2.x. That could make the operator '~>' undesirable now.
