### ISSUE TITLE
Minor: CFNetwork entry in Xcodeproj keeps moving up and down between Cocoapods' pod projects entries

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#4165]
![screen shot 2015-09-11 at 11 32 12](https://cloud.githubusercontent.com/assets/430233/9812920/e594b162-5878-11e5-8ae6-60284e45613e.png)

This shows up on my Git client once very so often — a bit of a nuisance, since logically absolutely nothing changed.

**Comment by segiddins** [comment]
Looks like a case sensitivity issue. Are you consistently installing in the same exact environment?

**Comment by segiddins** [comment]
Closing due to lack of response.
