### ISSUE TITLE
[0.39.0.beta.*] Conflict between 2 dependencies

### ISSUE THREAD

**Issue by mrezk** [CocoaPods/CocoaPods#4166]
:rainbow: I have a project which includes the following dependencies (see [Demo project](https://dl.dropboxusercontent.com/u/2444087/ExampleProject.zip)):
```
pod 'Mantle', '~> 1.5.5'
pod 'libextobjc/EXTScope', '~> 0.4'
```

This project builds perfectly using CocoaPods 0.38.2, but fails to do so starting on v0.39.0 with the following error: 
```
/Pods/Mantle/Mantle/MTLModel.m:229:2: Unknown type name 'mtl_propertyAttributes'; did you mean 'ext_propertyAttributes'?
```

This happens because Mantle includes `extobjc` as a subspec (see [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/Mantle/2.0.4/Mantle.podspec.json#L26)), but using their [own modified sources](https://github.com/Mantle/Mantle/blob/master/Mantle/extobjc/EXTScope.m) (they use `mtl_` prefix instead of `ext_` prefix).
As it can be observed on [Mantle's source code](https://github.com/Mantle/Mantle/blob/master/Mantle/MTLModel.m#L12), it tries to import its local version of `EXTScope.m`.

Any clue on why this used to work on v0.38.2 and it does not work anymore?

**Comment by segiddins** [comment]
Probably due to the removal of recursive header search paths?

**Comment by neonichu** [comment]
Not sure, but it was probably coincidental that this ever worked. 

One option is making sure that the right headers are used by changing the import statements:

```objectivec
#import <Mantle/EXTRuntimeExtensions.h>
#import <Mantle/EXTScope.h>
```

**Comment by RonanLB** [comment]
I would be very grateful if that change would make it to version 1.5.x because I am having the very same issue and we're not ready yet to move to Mantle 2.x
