### ISSUE TITLE
Duplicate FRAMEWORK_SEARCH_PATHS in xcconfig

### ISSUE THREAD

**Issue by garohussenjian** [CocoaPods/CocoaPods#4167]
Currently using CocoaPods 0.38.2 in Xcode 7 with three targets, each target has its own pod. One of my pods for a unit test target duplicates the FRAMEWORK_SEARCH_PATHS value in the generated xcconfig files:

FRAMEWORK_SEARCH_PATHS = $(inherited) $(DEVELOPER_FRAMEWORKS_DIR) "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(DEVELOPER_DIR)/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks" "$(SDKROOT)/Developer/Library/Frameworks" $(inherited) $(DEVELOPER_FRAMEWORKS_DIR) "$(PLATFORM_DIR)/Developer/Library/Frameworks" "$(DEVELOPER_DIR)/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks" "$(SDKROOT)/Developer/Library/Frameworks"

**Comment by segiddins** [comment]
Does this cause any actual compilation / linking issues?

**Comment by garohussenjian** [comment]
It's a minor quibble. The pod links and compiles. Just something I thought you want to be aware if it's a very simple fix, certainly not a high priority issue. I noticed this while trying to track down the linker warning from #4168, split into separate issues b/c they're unrelated.

**Comment by segiddins** [comment]
Yeah, I don't think there's any reason to try and change this if it's not harming anything. Thanks for reporting it, though!
