### ISSUE TITLE
Linker warning due to $(SDKROOT)/Developer/Library/Frameworks in iOS 9 SDK

### ISSUE THREAD

**Issue by garohussenjian** [CocoaPods/CocoaPods#4168]
Using CocoaPods 0.38.2 in Xcode 7 / iOS 9 SDK. In one of my targets, $(SDKROOT)/Developer/Library/Frameworks is generating a linker warning b/c this "Frameworks" directory has been renamed to "PrivateFrameworks".

**Comment by segiddins** [comment]
No way around this, unfortunately, as we still support Xcode 6.

**Comment by garohussenjian** [comment]
Thanks, and totally understood. My two cents, if I may - when I removed this, there was no effect on our build other than resolving the warning b/c there are at least three other framework search paths to link the SDK frameworks (not including $inherited settings). I'd love to understand better why/when this path is in fact necessary? I am concerned b/c if this path has been renamed we should expect things to break regardless for projects that do use it. Therefore, would you intend to add another search path for the new SDK, one that points now to a "PrivateFrameworks" directory? Seems to me this is a sign that (maybe) we shouldn't be pointed there any more?

**Comment by neonichu** [comment]
This is needed because of the location of the XCTest framework in Xcode 6, see 9fdeeb8e1894cf90d4d7044b597ac5b5c0fca5f3

**Comment by garohussenjian** [comment]
Those additions are not referring to the same path... it's $(PLATFORM_DIR)/path that is needed for XCTest, not $(SDKROOT)/path. Whatever needed the SDK rather than platform version of the path is probably using private SDK headers, hence the rename in Xcode 7?

**Comment by garohussenjian** [comment]
So I did some more digging, found this issue: https://github.com/CocoaPods/CocoaPods/issues/653 from 2012. The $(SDKROOT)/path appears to have been added to support SenTestingKit/OCUnit for Kiwi. But that was before Apple introduced XCTest with Xcode 5. 

I also setup a test project in Xcode 6 and built a pod with Kiwi w/o any issues. Perhaps there are some more substantial projects that can be tested? I'd hate for all users of Xcode 7 to get a linker warning from CocoaPods unless it was truly necessary. Is it safe to assume CocoaPods no longer needs to support Xcode 4 or 5? How has this kind of thing been handled in the past?

**Comment by segiddins** [comment]
Now that Xcode 7 is released, I feel we can drop 5 support?

**Comment by orta** [comment]
> Now that Xcode 7 is released, I feel we can drop 5 support?

I also think this is reasonable

**Comment by neonichu** [comment]
Agreed.

@garohussenjian thanks for digging :)

**Comment by garohussenjian** [comment]
Thanks guys. Truly a pleasure to help the community and their projects achieve zero warnings!! ;-)

**Comment by czechboy0** [comment]
Just updated our stack to Xcode 7 and am seeing the same issues. I'm very attached to my 0-warning builds and I'd like to get them back. What is the next action in resolving this issue? (Anything I can help with to get it into the next release?) :)

**Comment by segiddins** [comment]
@czechboy0 a PR removing that errant search path would be perfect!

**Comment by yas375** [comment]
@neonichu thanks for fixing this! :+1:
