### ISSUE TITLE
error

### ISSUE THREAD

**Issue by WeeDone** [CocoaPods/CocoaPods#4169]
Errno::ENOENT - No such file or directory @ rb_file_s_stat - /Users/Yomat/Desktop/Project1(2) 2/Pods/AMapSearch/AMapSearchKit.framework/Resources
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:904:in `stat'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:904:in `symbolic_modes_to_i'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:951:in `fu_mode'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1025:in `block (2 levels) in chmod_R'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1477:in `preorder_traverse'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1023:in `block in chmod_R'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1022:in `each'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/2.2.0/fileutils.rb:1022:in `chmod_R'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/Yomat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/Yomat/.rbenv/versions/2.2.2/bin/pod:23:in `load'
/Users/Yomat/.rbenv/versions/2.2.2/bin/pod:23:in `<main>'

**Comment by segiddins** [comment]
This has been resolved in the 0.39 betas.
