### ISSUE TITLE
Is it possible to create the podspec conditionally on the platform specified in the Podfile?

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/CocoaPods#4170]
I need to have a podspec to behave differently depending on the platform specified in the Podfile. Here is what I need ([because of radar 17076670](http://www.openradar.me/17076670)):

```ruby
Pod::Spec.new do |s|
  if podfile.platform.ios >= 7.0
    s.ios.frameworks         = "MediaPlayer", "JavaScriptCore"
  else
    s.ios.frameworks         = "MediaPlayer"
    s.ios.user_target_xcconfig = { "OTHER_LDFLAGS" => "-Wl,-U,_JSContextGetGlobalObject -Wl,-U,_JSEvaluateScript -Wl,-U,_JSGlobalContextCreate -Wl,-U,_JSGlobalContextRelease -Wl,-U,_JSObjectCallAsFunction -Wl,-U,_JSObjectIsFunction -Wl,-U,_JSObjectMake -Wl,-U,_JSObjectSetProperty -Wl,-U,_JSStringCopyCFString -Wl,-U,_JSStringCreateWithCFString -Wl,-U,_JSStringRelease -Wl,-U,_JSValueIsObject -Wl,-U,_JSValueIsString -Wl,-U,_JSValueMakeString -Wl,-U,_JSValueToStringCopy" }
  end
end
```

I haven’t even tried because I know that `if podfile.platform.ios >= 7.0` won’t work but is there some magic trick I could do that is equivalent to this pseudo podspec?

**Comment by segiddins** [comment]
No. Other than manually specifying a different subspec with the XCConfig.

**Comment by 0xced** [comment]
OK thanks. I think I’ll just drop iOS 5 and 6 support, it will be easier!
