### ISSUE TITLE
0.39.0 beta 4 causes a gem clash with fastlane 1.25.1

### ISSUE THREAD

**Issue by ekurutepe** [CocoaPods/CocoaPods#4173]
CP 0.39b4 depends on xcodeproj ~> 0.27 

fastlane 1.25 depends on slather 1.8.1 which requires xcodeproj ~>0.26

when CP is run it tries to load slather 1.8.1 but cannot because of xcodeproj 0.27…

Gem::ConflictError - Unable to activate slather-1.8.1, because xcodeproj-0.27.2 conflicts with xcodeproj (~> 0.26.2)

**Comment by orta** [comment]
This is not strictly a CP problem. 

@krausefx - IMO having a hard dependency on slather is a bad idea, we regularly have to take it out of our Gemfile as slather is generally slow on releasing a new build for CP and CP is nearly always going to be [a more important gem](https://github.com/artsy/energy/blob/a33366f15f0f23e0c8d2a7c07cffbac5c9d988a5/Gemfile). It's always locked to a single xcodeproj commit.

**Comment by ekurutepe** [comment]
@orta sure not. I just created the issue here because it bit me with CP. 

Slather as an optional dependency for fastlane should fix this for everybody as far as I understand?

**Comment by orta** [comment]
Well the only real way to get it to work together is to get a build of slather that works with the latest xcodeproj, currently the two are incompatible. [Changing this line](https://github.com/venmo/slather/blob/master/slather.gemspec#L30) to allow any pre-1.0 xcodeproj is going to fix the slow updates ( looks like the last one took roughly a month. ) 

My advice for Felix was more that he's going to be introducing this breaking change for a lot of people accidentally.

**Comment by KrauseFx** [comment]
Sorry about this, I'm on it!

**Comment by KrauseFx** [comment]
Here we go: https://github.com/KrauseFx/fastlane/releases/tag/1.26.0 :rocket: 

Let me know if that works for you

**Comment by neonichu** [comment]
We should finally make a Xcodeproj 1.0 to solve this :)

**Comment by orta** [comment]
@segiddins said when we hit 1.0 he wants all libs migrated to that too.

**Comment by neonichu** [comment]
awesome :tada:
