### ISSUE TITLE
library not found for -lPods-AFNetworking

### ISSUE THREAD

**Issue by HelloPig** [CocoaPods/CocoaPods#4176]
XCODE 6.4  Pods 0.38.2
ld: library not found for -lPods-AFNetworking
error when i build for the iOS device, but success built for the simulator
what i try:
1. Clean & Clean again
2. Clean & delete the libPods.a and Link Binary in Build Phases & pod install/update
3. Clean & delete the pods directories & pod install
none of them can deal with this problem...
Any suggestion?

**Comment by HelloPig** [comment]
The same codes&project work fine in another MBP

**Comment by neonichu** [comment]
Can you try running <https://github.com/kylef/cocoapods-deintegrate> and see if that fixes the problem?

**Comment by HelloPig** [comment]
tried & didn't work, i have checked out one more copy of my codes to another directory and it worked fine, so i gave up to solve this problem now :laughing:
