### ISSUE TITLE
How to use Objective-c category in swift project.

### ISSUE THREAD

**Issue by JoeShi** [CocoaPods/CocoaPods#4182]
I use pod 'UIScrollView-InfiniteScroll', '~>0.7.3' in the podfile. It is a objective-c category.

And I declare #import "UIScrollView+InfiniteScroll.h" in the bridging file. However, Xcode says "UIScrollView+InfiniteScroll.h" not found. 

If I directly copy those objective-c files into my project and using bridging file, it works. If I use normal objective-c library in cocoapods way, it also works. However, it does not work, if I want to use a objective-c category in cocoapods way.

**Comment by neonichu** [comment]
You have to use bracket-style imports, in this case probably `#import <UIScrollView-InfiniteScroll/UIScrollView+InfiniteScroll.h> — if you happen to integrate as frameworks, you have to use module imports.

**Comment by JoeShi** [comment]
Thank you. @neonichu . I got the problem, use objective-c category as framework is as the same as normal library. I have figured out the problem, I have two objective-c category in my project. 
<img width="304" alt="screen shot 2015-09-16 at 12 52 10 pm" src="https://cloud.githubusercontent.com/assets/2173635/9896654/f2d42a22-5c71-11e5-8b72-2a472f988b3c.png">

I can use  import SVPullToRefresh, but if I do import NSDate-Escort, Xcode says error. Do you know how to fix this, I googled a lot, I googled a lot but no result.
