### ISSUE TITLE
pod trunk push for swift 2.0 code not working when Xcode 6.4 & 7.0 installed

### ISSUE THREAD

**Issue by AnthonyMDev** [CocoaPods/CocoaPods#4183]
I have both Xcode 6.4 and Xcode 7.0 GM seed on my machine currently.

When trying to do a `pod trunk push` for a pod written using Swift 2.0 I get a bunch of errors that all have to do with Swift 2.0 language features not being recognized. (For example: `use of unresolved identifier 'guard'`).

I'm assuming this is because `pod trunk push` is verifying my library by building it in Xcode 6.4. Is there a way to force it to build in Xcode 7.0?

Thanks

**Comment by orta** [comment]
Trunk uses your default Xcode install, you can use [xcode-select](http://iosdevelopertips.com/xcode/xcode-select-managing-multiple-versions-of-xcode.html) to switch between versions in the command line.

**Comment by AnthonyMDev** [comment]
Thank you @orta

**Comment by orta** [comment]
:+1:
