### ISSUE TITLE
[cocoapods 0.38] podspec for two platforms instead of three

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#4185]
I'd like to support iOS and OSX, but not WatchOS. I understood I need to alter the default multi-platform, but the documentation doesn't tell how.

In a podspec, should I use:

    s.platform = :ios
    s.platform = :osx

Or:

    s.platforms = { :ios => nil, :osx => nil }

Or:

    s.ios.deployment_target = nil
    s.osx.deployment_target = nil

Or something else?

**Comment by orta** [comment]
Looks like the [platform section of the guides could do with an update](https://guides.cocoapods.org/syntax/podspec.html#platform): 

There are two ways to do it multi-platform

```
s.platforms = { :ios => "8.0", :osx => "10.7", :watchos => "2.0", :tvos => "9.0" }
```
or

```
s.ios.deployment_target = ""
s.osx.deployment_target = ""
s.watchos.deployment_target = "" 
s.tvos.deployment_target = ""
```

Both are different properties in xcode but will have the same effect in making your code cross-platform. You can use the `s.xxx` to do different [work per platform](https://github.com/artsy/Artsy-Authentication/blob/tvos/Artsy%2BAuthentication.podspec).

**Comment by Vyeche** [comment]
What is "s" in this case? How do I declare "s". Do I need to apply "s" per repository and target platform?

**Comment by Coeur** [comment]
Vyeche, you declare "s" from first line of your .podspec when you write `Pod::Spec.new do |s|`.

**Comment by Vyeche** [comment]
Interesting, @Coeur  this post is related to podspec? http://guides.cocoapods.org/terminal/commands.html#pod_spec_create

**Comment by Coeur** [comment]
@Vyeche https://guides.cocoapods.org/syntax/podspec for doc
@Vyeche https://cocoapods.org/ for examples, by looking for any pod, then clicking red "Expand" button, then red "See Podspec" link. There are two kinds, the .podspec files and the newer .podspec.json files.
