### ISSUE TITLE
Error while 'pod install'

### ISSUE THREAD

**Issue by netdemo123** [CocoaPods/CocoaPods#4187]
When I am trying to execute command 'pod install' it setup other things ok but at last it gives error 'RuntimeError - [Xcodeproj] Consistency issue: no parent for object `XMPPRoom.xcdatamodel`: `VersionGroup`, `BuildFile`' and says '[!] Oh no, an error occurred.'  Please see attached image.

![screen shot 2015-09-16 at 2 56 48 pm](https://cloud.githubusercontent.com/assets/14306634/9901151/3657e75a-5c83-11e5-9cab-7caa959e974b.png)

**Comment by segiddins** [comment]
Could you share your project setup so we can debug?in the meantime, you can disable deterministic uuid generation.

**Comment by netdemo123** [comment]
I have taken the code from https://github.com/ChatSecure/ChatSecure-iOS  and follow the steps provided in it.

**Comment by joekh** [comment]
I am also facing the same issue

**Comment by ashutoshag** [comment]
I am also facing the same issue.

**Comment by itolisto** [comment]
Same here! Any idea?

**Comment by NevilAppetals** [comment]
I am also facing same issue!!!Any idea??

**Comment by orta** [comment]
I took a stab at looking at this from the ChatSecure side, as we're pretty overwhelmed with issues ATM.

**Comment by segiddins** [comment]
I'm able to reproduce this, but i'm flummoxed as to why that `xcdatamodel` file apparently has no referrers when it's clearly inside an `XCVersionGroup`

**Comment by segiddins** [comment]
And 60 seconds later, I have to eat my words! I should have a fix for this in Xcodeproj shortly!

**Comment by orta** [comment]
:dancers:
