### ISSUE TITLE
Can not change the code of library in "pods" folder,because it's locked.

### ISSUE THREAD

**Issue by seanLee** [CocoaPods/CocoaPods#4193]
No matter I run ````pod update```` or  ````pod install```` or remove the cocoapods and  reinstall it ,I can's change to code.After upgrading to Xcode 7 GM,and upgrading to 0.39 beta4,it becomes so  strange.

**Comment by segiddins** [comment]
This is intended behavior with recent versions of CocoaPods.

**Comment by seanLee** [comment]
@segiddins  So sorry for my stupid~haha~

**Comment by segiddins** [comment]
No worries :)
