### ISSUE TITLE
Generating Pods project -> [!] An error occurred while processing the pod install

### ISSUE THREAD

**Issue by loumzy** [CocoaPods/CocoaPods#4194]
2015-09-17 17:35:05.277 ruby[9186:768977] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8227/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fc7361ed820>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x000000010a2b6a5c -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x000000010a2b61e9 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010a2b6455 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000010a2b63b7 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x000000010b748f5c IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000010e3a0eb9 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x000000010e3a2a3e +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff92608f44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6

**Comment by loumzy** [comment]
This problem occurred when i update  "Command Line Tools (OS X 10.10) for Xcode", Xcode

**Comment by mihahribar** [comment]
Had the same problem with v0.37.2. Works with v0.38.2.

**Comment by loumzy** [comment]
@mihahribar  works with v0.38.2 for you？

**Comment by joshuatam** [comment]
confirmed v0.38.2 solved the problem

**Comment by mihahribar** [comment]
:+1:

**Comment by loumzy** [comment]
@mihahribar @mihahribar Thank you，I have solved the problem
