### ISSUE TITLE
Why Cocoapods didn't download repos and backup one to user root dictionary(center repo)?

### ISSUE THREAD

**Issue by startry** [CocoaPods/CocoaPods#4195]
I am very confused. Why Cocoapods didn't keep backups of downloaded sources of repos? I meaning I should download the same repo sources again and again if I made a new project. 

I found Cocoapods keep repos specs in user root dictionary(``.cocoapods``). Why didn't keep repos in .cocoapods diectionary like specs? Cocoapods could just copy the same reop from central repo(``.cocoapods``) to target project(``TargetProject/Pods``) when download the same repo sources at different project. 

for example: 
A workspace Podfile contain this line:
```
"AFNetworking": "~> 2.6.0"
```

B workspace Profile contain this line too:
```
"AFNetworking": "~> 2.6.0"
```

Is possible for AFNetworking download once and used for A and B workspace?

**Comment by startry** [comment]
Click 'Close' button Accidentally. I didn't mean it.

**Comment by orta** [comment]
CocoaPods does cache the repos is downloads, http://blog.cocoapods.org/CocoaPods-0.37/
