### ISSUE TITLE
I can not update XCDYouTubeKit (2.3)

### ISSUE THREAD

**Issue by arno608rw** [CocoaPods/CocoaPods#4196]
![screen shot 2558-09-16 at 22 17 04](https://cloud.githubusercontent.com/assets/3774145/9933370/b323359a-5d74-11e5-80e2-3353088f5f75.png)

**Comment by orta** [comment]
Please provide us with more information. You are a developer, give us a bug report you would like to receive so we can help you in our spare time.

**Comment by segiddins** [comment]
Closing due to lack of response.
