### ISSUE TITLE
`pod install` prints wrong error message

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/CocoaPods#4197]
Hi,

During adding a private pod into a project, if a specific version is not specified in the Podfile and there are only pre-release versions available for the pod, `pod install` command fails with the following output:

```
[!] Unable to satisfy the following requirements:

- `PrivatePodName` required by `Podfile`

Specs satisfying the `PrivatePodName` dependency were found, but they required a higher minimum deployment target.
```

If I explicitly specify pre-release version in the Podfile, `pod install` succeeds without any problem.

I dug into the issue a little, and discovered that the conflict that resulted from this case was not handled correctly in `handle_resolver_error` method of `resolver.rb` file. There should be another check that detects the case and print a meaningful output to user.

I've actually implemented this and will provide a PR.

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/issues/4198.
