### ISSUE TITLE
README and CHANGELOG are not updating

### ISSUE THREAD

**Issue by dcirne** [CocoaPods/CocoaPods#4204]
README and CHANGELOG are not displaying changes when a pod is updated. For example: changes are being displayed correctly on GitHub (https://github.com/mParticle/mParticlePod), but incorrectly at CocoaPods (https://cocoapods.org/pods/mParticle). It should be showing version 4.4.0, instead it is showing data from version 4.3.0

**Comment by orta** [comment]
This issue is being handled in cocoapods.org - https://github.com/CocoaPods/cocoapods.org/issues/201
