### ISSUE TITLE
API for CocoaPods?

### ISSUE THREAD

**Issue by tejasmanohar** [CocoaPods/CocoaPods#4205]
I'm writing a server-side Ruby app that I want to interact w/ CocoaPods... better if it can talk to the gem's API itself rather than the installed program / running shell commands. Do you have any tips / documentation / examples on this?

**Comment by segiddins** [comment]
Using the CocoaPods CLI is currently the only supported API, outside of the plugin APIs, so manually invoking Pod::Command.run is probably your best bet. The internals of CocoaPods are fairly well documented, but we're not promising we won't make breaking changes to them.

**Comment by tejasmanohar** [comment]
Got it. Would you suggest invoking `Pod::Command.run` form Ruby after requiring this gem, or just interacting with the CLI / program itself?

**Comment by tejasmanohar** [comment]
For more context, I'm considering writing an (open-source) web-hooks server that listens to GitHub repo, checks if Podfile changed after a commit and if so, runs `pod install` in the directory of that repo's cloned source (or uses Cocoapods core API to fetch the sources directly) and archives the pods.

This way, we don't have to clutter the iOS repo with a bunch of Pods packages and have a stable backup in case one of the sources goes down/away.

**Comment by segiddins** [comment]
Calling run via ruby should be good! She'll out if you want it to be out of process, that decision is totally up to you.

**Comment by tejasmanohar** [comment]
Perfect- thanks, @segiddins!
