### ISSUE TITLE
Android NDK Standalone Toolchain lint interference 

### ISSUE THREAD

**Issue by mrrobby** [CocoaPods/CocoaPods#4206]
This is actually resolved and I just wanted to make a note as it took a bit to unravel, for anyone else that may have this issue.
  
I installed cocoapods on a dev machine I used to use for android native development, running OS X.  I was getting errors on pod spec lint, even with --use-libraries flag.  It turned out to be my PATH and CC environment variables were pointing to the androideabi-gcc.  Still there should be a way to get around it, but I didn't spend much time more time on that, other than getting rid of it.

Just for anyone that has the issue, the error looked like:
- ERROR | [iOS] Returned an unsuccessful exit code.

then with --verbose set, I saw:
error: Error Domain=NSPOSIXErrorDomain Code=1 "Non-zero exit code 1 returned from shell command: /Users/some/path/MyLibraries/android-toolchain/bin/arm-linux-androideabi-gcc -v -E -dM -arch x86_64 -isysroot ...

Cleaned .bash_profile and did a full uninstall/re-install of cocoapods and the problem ceased.
Cheers!

**Comment by neonichu** [comment]
Thanks, this might help someone at some point when searching!
