### ISSUE TITLE
Podfile.lock not honored for local podspecs

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#4211]
We have a dependency that the .lock file has it locked in version 1.2.3.

Going back to this commit and doing `pod install` we see the .lock file being updated with version 1.2.4.

The podspec that depends on this dependency is a local podspec using `:path`, could that be a clue? How and why does CocoaPods thinks there is a new version despite the fact the lock file mentions otherwise?

Can you provide more info on how the lock file is honored and when is it considered "dirty"?

**Comment by dnkoutso** [comment]
Version 0.39.0.beta4

**Comment by dnkoutso** [comment]
This appears to be that the local podspecs are always treated as specs to be updated. Is there a reason for this? Perhaps due to the fact that they are considered local pods?

**Comment by justinseanmartin** [comment]
It is tied back to this change from July:
https://github.com/CocoaPods/CocoaPods/issues/3764

**Comment by justinseanmartin** [comment]
Should there be something like a --frozen equivalent as bundler?

https://github.com/bundler/bundler/blob/406e069b7a6c870fe7db4dc6d891adde85b96f47/lib/bundler/definition.rb#L326

**Comment by segiddins** [comment]
Pretty sure this is the intended behavior?

**Comment by dnkoutso** [comment]
There should be at least a flag perhaps similar to `-frozen` that will not update the dependencies...We use some local podspecs that we commit into the repos without publishing them so we can slice our project structure.

**Comment by segiddins** [comment]
Unfortunately, that's just not how development pods work :(

**Comment by dnkoutso** [comment]
Would you consider a `--frozen` flag in `pod install` command that doesnt update any pod?

**Comment by segiddins** [comment]
If anything, it would belong in the Podfile... Maybe we could have something like an alias for path that doesn't implicitly unlock? Thoughts, @orta?

**Comment by justinseanmartin** [comment]
I wasn't suggesting a `--frozen` flag on dependencies in the podfile or podspec, but rather on the `pod install` command line, similar to the way it is in deployment mode for bundler.

**Comment by dnkoutso** [comment]
I feel like a `:frozen => true` would be sufficient within the Podfile. It looks like it might be rather easy to add support as well.

I'll wait for your feedback and then I can implement this.

**Comment by neonichu** [comment]
How would this work, though? Local Pods use symlinks, so there's just the newest version of everything available, no matter which version it would pretend to be.

**Comment by dnkoutso** [comment]
This is more about its transitive dependencies that have been published rather than the sources of the local pod itself.

Overall it caught us by surprise to see that going back to a release branch our `pod install` command actually updated the published dependencies of the local pod.

**Comment by kyleve** [comment]
I think I agree with @dnkoutso (though I admittedly know little about Pods or Bundler). Seems like the lock file should be the source of truth.

**Comment by danielribeiro** [comment]
Hi @neonichu 

I've exemplified the bug here: https://github.com/danielribeiro/Podfilelock-for-path-dependencies

**Comment by orta** [comment]
Interesting, so this is about it breaking the dependencies outside of the one that is defined as a dev/path pod, I can see why you'd expect the `Podfile.lock` to be respected here. Just because the dependency is defined in the dev pod, shouldn't mean "always make the transitive reps be the highest in the constraints." I'd say this is something we should look at. Thanks for the demo, made it much easier to understand the problem.

**Comment by danielribeiro** [comment]
No problem @orta !

**Comment by dtweston** [comment]
@segiddins, what's the status of this issue? Can we just make `pod try` ignore Podfile.lock for local dependencies?

**Comment by segiddins** [comment]
@dtweston I don't think this issue has anything to do with `pod try`, and I'm of the belief that the current behavior is the least wrong.

**Comment by dtweston** [comment]
As @dnkoutso said a while back this is more about the dependencies of the pod that is being referenced via path as opposed to the pod itself.

It makes sense that we don't enforce the version for the pod on the path, but it makes less sense (to me, at least) that we consider each of that local pod's dependencies as targets to be updated.

**Comment by segiddins** [comment]
If you care about those versions though, you should be explicitly locking them in your podfile imho.

**Comment by dtweston** [comment]
I don't care about the versions per se, I just want the build to be repeatable.

**Comment by segiddins** [comment]
If you want repeatability, you probably shouldn't be using dev pods, since cocoapods can't lock them.

**Comment by dtweston** [comment]
We have repeatability for the dev pod because it's referenced via a git submodule. Might be considered an odd setup, but it's been more or less working so far.

**Comment by dtweston** [comment]
*bump* Can I ask what the current feeling is on this issue?

We'd really like to move to the latest version of Cocoapods (especially now that you're getting to 1.0), but this is a blocker for us, so we're also looking at alternatives.

@dnkoutso, does your offer to implement this still stand? :grin:

**Comment by segiddins** [comment]
We've asked before for a PR to stop implicitly unlocking all dependencies of Dev pods. We've yet to receive one. If you send a documented, well-tested PR, we'd be happy to merge it.

**Comment by dtweston** [comment]
I must have missed that request. Thanks for the clarification @segiddins!

I would love to contribute a PR, and I'll get started on it, but it may take me quite a while, so if someone else has the ability to step in and help out, that would be awesome.

**Comment by justinseanmartin** [comment]
I think this is the same issue called out in #4580.

Our current workaround is to monkey patch Cocoapods with this:
```
class ::Pod::Installer::Analyzer
  # Github source: https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer.rb
  def generate_version_locking_dependencies
    if update_mode == :all || !lockfile
      LockingDependencyAnalyzer.unlocked_dependency_graph
    else
      pods_to_update = result.podfile_state.changed + result.podfile_state.deleted
      pods_to_update += update[:pods] if update_mode == :selected
      # FIXME: go back to master once this is fixed: https://github.com/CocoaPods/CocoaPods/issues/4211
      # pods_to_update += podfile.dependencies.select(&:local?).map(&:name)
      LockingDependencyAnalyzer.generate_version_locking_dependencies(lockfile, pods_to_update)
    end
  end
end
```

I think this will break `pods try` though, as it explicitly reverses the behavior from #3764.
