### ISSUE TITLE
Updating local specs repositories,when pod update or pod install

### ISSUE THREAD

**Issue by fewspider** [CocoaPods/CocoaPods#4218]
My system is OS X EI Caption `10.11.1`.
pod version is `0.38.2`.
It seems `Updating local specs repositories` is every moment,when  `pod update` or `pod install`.
Is there some config that i am missed?
![shell](https://cloud.githubusercontent.com/assets/3256161/9976548/d58020f2-5f19-11e5-80cc-c643fcad69c7.png)

**Comment by segiddins** [comment]
Yes, by default the specs repos you specify will be updated. You can skip updating them by running with --no-repo-update`

**Comment by fewspider** [comment]
@segiddins thanks a lot
