### ISSUE TITLE
[search] Enabling approximate matching for `pod search`

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/CocoaPods#4220]
Hi,

I wish to hear from you about whether providing an approximate string matching policy for `pod search` would be a valuable enhancement. 

Currently it has a --regex option which provides a way to make fuzzy searches intentionally. However, the default search works only if a pod contains __exactly__ the given query string.

We may provide an approximate search policy (e.g. using edit distance for the simplest case) by default in order to be able to give results even if user makes some typo like missing a character or typing a wrong character inside the query.

I can make some prototype implementation to see the effects on both search results and the performance, but first I want to be sure that it would worth to give an effort. Do you have any statistics on the usage for `pod search` command? I personally use it but maybe the majority is using the cocoapods.org to search for pods.

I appreciate any feedback!

**Comment by segiddins** [comment]
I think we have an issue / PR open for this _somewhere_ that hasn't been touched in a while. Fuzzy search would be awesome, it just hasn't been a priority for us

**Comment by orta** [comment]
I'm willing to bet the vast majority is done via cocoapods.org ( we see about 25,000 searches a day )

<img width="946" alt="screen shot 2015-09-25 at 06 51 10" src="https://cloud.githubusercontent.com/assets/49038/10093964/d7191a40-6351-11e5-9f5e-060a5200621f.png">

**Comment by manuyavuz** [comment]
I feel this is not much needed at the moment because cocoapods.org is the main place to search and even it does not contain a fuzzy search. I tested with some words and verified that cocoapods.org does not perform fuzzy search. 

@orta, is there a planned date to add fuzzy search to cocoapods.org?  Maybe I can help with this if there is no ongoing work.

**Comment by orta** [comment]
No plans for a fuzzy search on the website, a lot of our time right now on is going towards stability and reducing memory on the search server ATM. You're welcome to take a look! We run a [picky instance](http://pickyrb.com) on [search.cocoapods.org](https://github.com/CocoaPods/search.cocoapods.org)

**Comment by floere** [comment]
@manuyavuz I've actually removed (explicit) fuzzy search from cocoapods.org since it was used so little (and, in this type of search it is not as useful as in full text searching).

**Comment by manuyavuz** [comment]
@floere, was it available via something like a check box? I think the main aim of having a fuzzy search is correcting user typos like google ('did you mean' thing). Therefore, I don't think an explicit fuzzy search would be helpful, but we may consider adding fuzzy search implicitly. What do you think?

**Comment by floere** [comment]
@manuyavuz It was using the `~` Lucene fuzzy search operator.

An idea would be to perhaps employ it when people don't find anything. Currently, we do autosplitting and suggestions when that happens. See an example in action here: https://cocoapods.org/?q=apialert The reasoning was that stuck together search terms were the most common occurrence, while typos – perhaps surprisingly – were not.

I'll try to put together some statistics on this soonish, so we can reason about it :)

**Comment by manuyavuz** [comment]
Oh, I really wish to see the statistics you have, It will be very informative and decisive. I really surprised about typo rate being low :)

I wasn't aware of the current policy for the sample case you sent. It's a very proper and efficient way to handle the issue, liked it. Maybe we could add similar suggestions via searching for things having edit distance value one or two when no exact search found. Of course only if it worths :)

**Comment by floere** [comment]
Here are the top 500 ways of how people don't find anything on cocoapods.org: https://gist.github.com/floere/6227cc59b721dfe51130
I see some typos, but also just a lot of searches on swift which truly yield no results (and are then covered with the "no results" search), like https://cocoapods.org/?q=lang%3Aswift%20on%3Aios%20scenekit (scenekit on ios+swift).
It's too late here to do any real analysis, but here you go :)
