### ISSUE TITLE
No error logging on invalid dependency version

### ISSUE THREAD

**Issue by valnoc** [CocoaPods/CocoaPods#4222]
I have faced a bug in error logging, i think.
I've made a mistake in my podspec when writing dependencies. Console log did not give me any useful information, i have spend a lot of time while searching for a problem. Some additional logging here could have saved me))

**Invalid code**
```
  s.dependency 'UIButton+BackgroundColor', '~> 1.0'
```

**VALID code**
```
  s.dependency 'UIButton+BackgroundColor', '~> 0.1'
```
Console log of `pod lib lint`
```
Valeriys-Mac-mini:UIKit-VBProgrammaticCreation valnoc$ pod lib lint
[!] UIKit+VBProgrammaticCreation did not pass validation, due to 1 error and 2 warnings.
You can use the '--no-clean' option to inspect any issue.
Valeriys-Mac-mini:UIKit-VBProgrammaticCreation valnoc$ pod lib lint --no-clean
[!] UIKit+VBProgrammaticCreation did not pass validation, due to 1 error and 2 warnings.
```

P.S. Thank you for CocoaPods project, it solves lots of developer problems in a very developer friendly way)))

**Comment by segiddins** [comment]
What's the output with `--verbose`? I can't remember in what version we made this a bit more informative, it may only be in the 0.39 betas.

**Comment by neonichu** [comment]
Looks like it is there since 0.39 beta 4: b16f25ccd1d1c4f5581c60e51fadf2ff439e0280
