### ISSUE TITLE
SystemStackError - stack level too deep

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4229]
When two targets have a build dependancy on each other, Cocoapods will crash with this error.

**Comment by segiddins** [comment]
@jcampbell05 can you please provide steps to reproduce the issue?

**Comment by jcampbell05** [comment]
Set up a new xcode project. In the build phases for the Unit Tests make the "Target Dependancies" contain the main app target,  In the build phases for the app target make the "Target Dependancies" contain the Unit Tests.

Now try to install any kind of pod and cocoapods will crash with a SystemStackError.

**Comment by segiddins** [comment]
Confirmed, this is a bug in Xcodeproj's project initialization code.
