### ISSUE TITLE
mix cocoa pods and 'legacy' dependencies -> cocoa pods overwrites frameworks search path

### ISSUE THREAD

**Issue by Daij-Djan** [CocoaPods/CocoaPods#4230]
Hi,
due to having a large closed source base, I need to mix cocoa pods and 'legacy' dependencies. The problem with that is that cocoa pods overwrites frameworks search path and doesn't add $(inherited)

if I add it manually, it works fine anyway but I don't really like to edit the xconfig files ;)

`FRAMEWORK_SEARCH_PATHS = "$(PODS_ROOT)/GoogleMaps/Frameworks"`

TO

`FRAMEWORK_SEARCH_PATHS = $(inherited) "$(PODS_ROOT)/GoogleMaps/Frameworks"`

---

this is my podfile:

    platform :ios, '7.0'
    inhibit_all_warnings!

    pod 'GoogleMaps', '~> 1.10.1'
    pod 'DTRichTextEditor', '~> 1.6.10'
    pod 'SMCalloutView', '~> 2.1.2'
    pod 'GTMNSStringHTMLAdditions', '~> 0.1.1'
    pod 'TouchXML', '~> 0.1'
    pod 'XBPageCurl', '~> 1.0.1'
    pod 'Reachability', '~> 3.2'

**Comment by Daij-Djan** [comment]
I checked the GoogleMaps pod spec but it correctly uses vendors frameworks and doesn't write something to the config directly

**Comment by segiddins** [comment]
Yup, this should be an easy thing to fix -- we just need to make sure `FRAMEWORK_SEARCH_PATHS` has `$(inherited)` at the end of it -- someone can use https://github.com/CocoaPods/CocoaPods/pull/4063 as a template for how to make this fix & test it.

**Comment by segiddins** [comment]
This should be fixed now? by https://github.com/CocoaPods/CocoaPods/commit/36e700159074e0c2233934f8f128becb51d8c1c8
