### ISSUE TITLE
Cannot install dependencies for tvOS project

### ISSUE THREAD

**Issue by zeusent** [CocoaPods/CocoaPods#4235]
Hi!

I am trying to build a project for tvOS and using CocoaPods is something that I need. But after defining my Podfile (see structure bellow) and run `pod install` I get this error:

> Unsupported platform. Platform must be `:ios`, `:osx`, or `:watchos`.

Here are the contents of my `Podfile`

> link_with 'MyTarget'
> pod 'APod', :git => 'git@some_private_repo'
> use_frameworks!

Is there a beta version or unreleased version that I can install to make CocoaPods support tvOS?

Thanks!

**Comment by orta** [comment]
Follow this PR - https://github.com/CocoaPods/CocoaPods/pull/4152

This Gemfile will get you set up: https://github.com/orta/Elasticity/blob/master/Gemfile

**Comment by zeusent** [comment]
Awesome! Any hints for a noob in gem files? :) I mean how do I go ahead and use it?

**Comment by orta** [comment]
We have a guide: http://guides.cocoapods.org/using/a-gemfile.html - this should get you understanding

**Comment by zeusent** [comment]
Perfect! Thanks!

**Comment by wouterds** [comment]
Hmm, I get 
	Fetching https://github.com/CocoaPods/CocoaPods.git
	fatal: ambiguous argument 'tvos': unknown revision or path not in the working tree.

**Comment by segiddins** [comment]
@wouterds it's been merged to master now, just use 0.39.0.rc.1
