### ISSUE TITLE
When integrating a dynamic iOS framework with CocoaPods, I get 'A signed resource has been added, modified, or deleted'

### ISSUE THREAD

**Issue by julianiaccopucci** [CocoaPods/CocoaPods#4236]
We are building a dynamic library (.framework) that we want to distribute with CocoaPods. When testing the podspec on a test project, I encounter that the framework is copied into .app, but it's not signed afterwards, leading to a message saying (when installing the app): "A signed resource has been added, modified, or deleted."

I can confirm that if I add the framework manually, Xcode does a 'codesign' after the copy phase and no error appears.

The podspec looks like:
---------------------------------------------------------
Pod::Spec.new do |s|

  ... a few lines omitted...

  s.vendored_frameworks = 'MyframeworkName.framework'
  s.resource = 'MyFrameworkName.framework'
  s.xcconfig = { 'LD_RUNPATH_SEARCH_PATHS' => '"$(PODS_ROOT)/MyFrameworkName_SDK/Frameworks"' }
  s.frameworks = 'MyFrameworkName'
end
--------------------------------------------------------

And my podfile like:

--------------------------------------------------------
target 'testproject' do
    source "git@github.com:mypodspec.git"
    platform :ios, '8.0'
    use_frameworks!
pod 'MyFrameworkName', '0.1.4'
end
--------------------------------------------------------

**Comment by segiddins** [comment]
What version of CocoaPods are you using? Dynamic vendored frameworks are only supported as of 0.39.
Additionally, you should only be setting the dynamic framework attribute in the spec, not any of the others.

**Comment by julianiaccopucci** [comment]
I'm using 0.38.2
I'll update my version now.
Thanks

**Comment by julianiaccopucci** [comment]
I'm having the same issue with version 0.39.
When the script frameworks.sh runs, the function install_framework() does not run, so the codesign never happens. Is that expected to happen?

**Comment by julianiaccopucci** [comment]
If I follow you advice, of leaving only vendored_framework I get this error:
-------------------------------------------------
dyld: Library not loaded: @rpath/....
  Referenced from: ....
Image not found
------------------------------------------------

Looking at the .app under Products folder, the application Xcode has no copied anything to the /Frameworks folder

**Comment by segiddins** [comment]
And you're using the CocoaPods 0.39 beta?

**Comment by julianiaccopucci** [comment]
Yes 0.39 beta



Julian Iaccopucci
07780178894

**Comment by segiddins** [comment]
In that case, could you please upload a project that can be used to reproduce the issue? Thanks!

**Comment by julianiaccopucci** [comment]
Yes of course.


The .framework and pod spec are in a private .git repo. To reproduce, I’d need a public .framework with a dylib so I can share it here. Do you know of any .framework out there I can use to try reproducing?

**Comment by julianiaccopucci** [comment]
I created a new issue for clarity, as the title of this issue doesn't relate to the current problem. The new issue is now this one https://github.com/CocoaPods/CocoaPods/issues/4244
I can provide you with a project to reproduce the issue, how can I send it over?
