### ISSUE TITLE
hundreds of warnings during Archive in Xcode 7

### ISSUE THREAD

**Issue by mackuba** [CocoaPods/CocoaPods#4237]
After upgrading to Xcode 7, when I archive my app, I get a long list of warnings saying `unable to open object file: No such file or directory`, like this:

```
GenerateDSYMFile /Users/psionides/Library/Developer/Xcode/DerivedData/Zoomer-dplrrfzmmmmlgxeyrzondlvrjyvo/Build/Intermediates/ArchiveIntermediates/Zoomer\ Staging/BuildProductsPath/Release\ (staging)-iphoneos/Zoomer.app.dSYM /Users/psionides/Library/Developer/Xcode/DerivedData/Zoomer-dplrrfzmmmmlgxeyrzondlvrjyvo/Build/Intermediates/ArchiveIntermediates/Zoomer\ Staging/InstallationBuildProductsLocation/Applications/Zoomer.app/Zoomer
    cd /Users/psionides/Projects/Zoomer
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/psionides/Library/Developer/Xcode/DerivedData/Zoomer-dplrrfzmmmmlgxeyrzondlvrjyvo/Build/Intermediates/ArchiveIntermediates/Zoomer\ Staging/InstallationBuildProductsLocation/Applications/Zoomer.app/Zoomer -o /Users/psionides/Library/Developer/Xcode/DerivedData/Zoomer-dplrrfzmmmmlgxeyrzondlvrjyvo/Build/Intermediates/ArchiveIntermediates/Zoomer\ Staging/BuildProductsPath/Release\ (staging)-iphoneos/Zoomer.app.dSYM

warning: (armv7) /Users/psionides/Library/Developer/Xcode/DerivedData/Zoomer-dplrrfzmmmmlgxeyrzondlvrjyvo/Build/Intermediates/ArchiveIntermediates/Zoomer Staging/BuildProductsPath/Release (staging)-iphoneos/libCocoaLumberjack.a(CocoaLumberjack-dummy.o) unable to open object file: No such file or directory
warning: (armv7) /Users/psionides/Library/Developer/Xcode/DerivedData/Zoomer-dplrrfzmmmmlgxeyrzondlvrjyvo/Build/Intermediates/ArchiveIntermediates/Zoomer Staging/BuildProductsPath/Release (staging)-iphoneos/libCocoaLumberjack.a(DDAbstractDatabaseLogger.o) unable to open object file: No such file or directory
warning: (armv7) /Users/psionides/Library/Developer/Xcode/DerivedData/Zoomer-dplrrfzmmmmlgxeyrzondlvrjyvo/Build/Intermediates/ArchiveIntermediates/Zoomer Staging/BuildProductsPath/Release (staging)-iphoneos/libCocoaLumberjack.a(DDASLLogCapture.o) unable to open object file: No such file or directory
(...)
Showing first 200 warnings only
```

The list seems to only includes files from pods (many pods, not just one), so I'm assuming it's something CocoaPods-related (this is on version 0.39.0.beta.3 or 4, but the same thing happened on 0.38). Any idea?

This is my Podfile:

```rb
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

link_with 'Zoomer', 'ZoomerTests'

pod 'CocoaLumberjack'
pod 'ISO8601'
pod 'le', :git => 'git@github.com:logentries/le_ios.git'
pod 'libPusher', :git => 'https://github.com/lukeredpath/libPusher.git'
pod 'MBXMapKit', '~> 0.7'
pod 'Mixpanel'
pod 'SocketRocket', '0.3.1-beta2', :inhibit_warnings => true

# debug builds only
pod 'PonyDebugger', :configurations => ['Debug', 'Debug (live)']

# build flag overrides
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "le"
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].push('LE_DEBUG_LOGS=0')
            end
        end
    end
end
```

I'm using Swift (2.0) almost exclusively in the app. Also, in case that's relevant, I have 5 different build configurations in the project, most of which have parentheses or spaces in the name.

**Comment by neonichu** [comment]
I don't think this is CP-related — but rather an Xcode issue with configurations which include parentheses. I can reproduce it in a test project and the path the warnings complain about do actually exist on disk. I would recommend filing a radar or renaming your build configurations.

**Comment by iGriever** [comment]
I'm experiencing the same issue, with CocoaPods version 0.38.2 and Xcode 7.0. No weird build configurations name.

**Comment by neonichu** [comment]
@iGriever would be great if you could open a separate issue for it with more information (Podfile, warnings, ideally a sample project)

**Comment by iGriever** [comment]
Just tried with a sample project, with the exact same environment (Xcode version, CocoaPods version, Podfile), and I have no issues. It seems the original project has been corrupted in some way, I tried removing the pods and reinstalling them, but no luck. Talked to other developers who had the same issue, and they ended up creating a new project and copying everything.

**Comment by iGriever** [comment]
Looks like I find the culprit: I had no Build Configuration names with parenthesis in them, but my Build Schemes had some. Removing them fixed the issue.

**Comment by schristmann** [comment]
For anyone else stumbling across this issue, we had build schemes named things like

App Name (Debug)
App Name (App Store)

And we were getting the errors as well, removing the parenthesis fixed it for us as well.

**Comment by ShurupuS** [comment]
Yes, removing the parenthesis fixed this issue for us too

**Comment by zakkhoyt** [comment]
I can confirm that removing parenthesis worked for me as well:

I changed the scheme name:
MyProject (internal) -> MyProject_internal

**Comment by victorvasilica** [comment]
Same here, no parenthesis no issues

**Comment by bestimmaa** [comment]
Can confirm that changing XYZ (ABC) to XYZ-ABC resolved these warnings for me...

**Comment by bernikowich-cedoni** [comment]
Maybe someone can fix this on Cocoapods side? Xcode allows using (), Cocoapods should allow this too I think.
