### ISSUE TITLE
Invalid Swift Support

### ISSUE THREAD

**Issue by ishortman** [CocoaPods/CocoaPods#4238]
Using cocoapods 0.39.0.beta.4 and receiving an error message when submitting to the app store for beta testing via xcode.  Error returns:

Invalid Swift Support - The files libswiftWebKit.dylib, libswiftCoreLocation.dylib don’t match /Payload/.app/Frameworks/libswiftWebKit.dylib, /Payload/.app/Frameworks/libswiftCoreLocation.dylib.

Currently using xcode 7 GM and have tried several hacks to fix this issue but no luck.  Any suggestions or new updates coming along to address this issue?

**Comment by neonichu** [comment]
See #4188
