### ISSUE TITLE
SystemStackError - stack level too deep  Any idea?

### ISSUE THREAD

**Issue by FreudGit** [CocoaPods/CocoaPods#4239]
Hi.  This have worked with pod previous version(probably 3.8)

Not get " SystemStackError - stack level too deep"

Updating local specs repositories

CocoaPods 0.39.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0.beta.3
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.2.1
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0 (7A220)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bc9693b5ead2b78e34b2d6f2d6c0550494666d2b
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.6.1
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'



target '1001 bières v0.5' do
        pod 'Parse', '~> 1.2'
	pod 'Fabric'
	pod 'Crashlytics'
        pod 'Google/Analytics', '~> 1.0.0'
	pod 'ParseUI'
	pod 'ParseFacebookUtilsV4', '~> 1.3'
	pod 'FMDB', '~> 2.2'
	pod 'NGAParallaxMotion', '~> 1.0'
	pod 'EDStarRating', '~> 1.1'
	pod 'skpsmtpmessage', '~> 0.0'
	pod 'CZPhotoPickerController', '~> 1.2'
	pod 'AFNetworking', '~> 2.3'
	pod 'SVProgressHUD', '~> 1.1'
end

target 'Widget1001' do
        pod 'Parse', '~> 1.2'

	pod 'Fabric'
	pod 'Crashlytics'
end
```

### Error

```
SystemStackError - stack level too deep
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.3/lib/cocoapods/target/pod_target.rb:64
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=stack+level+too+deep&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by cbrauchli** [comment]
Sounds the same as #4229.

**Comment by FreudGit** [comment]
So how can I solve this?

**Comment by FreudGit** [comment]
ALso, this result with same problem:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'


def shared_pods
	pod 'Parse', '~> 1.2'
	pod 'Fabric'
	pod 'Crashlytics'


end

target '1001 bières v0.5' do
        shared_pods
        pod 'Google/Analytics', '~> 1.0.0'
	pod 'ParseUI'
	pod 'ParseFacebookUtilsV4', '~> 1.3'
	pod 'FMDB', '~> 2.2'
	pod 'NGAParallaxMotion', '~> 1.0'
	pod 'EDStarRating', '~> 1.1'
	pod 'skpsmtpmessage', '~> 0.0'
	pod 'CZPhotoPickerController', '~> 1.2'
	pod 'AFNetworking', '~> 2.3'
	pod 'SVProgressHUD', '~> 1.1'
end

target 'Widget1001' do
	shared_pods
end

**Comment by segiddins** [comment]
I can't reproduce this, could you please share a full project we can download and run that exhibits the issue? Thanks!

**Comment by FreudGit** [comment]
@segiddins Project have sensitive data.  How about a screen share?

**Comment by segiddins** [comment]
A project without the sensitive data that reproduces the issue is also ok!

**Comment by neonichu** [comment]
We never got a project to reproduce — will reopen if we do.
