### ISSUE TITLE
Dynamic frameworks and watchOS 2 causes 10+ minute pod installs

### ISSUE THREAD

**Issue by maxmeyers** [CocoaPods/CocoaPods#4240]
🌈

We're trying to switch over to `use_frameworks!` for one of our projects, which has several targets: 3 iOS apps, 5 iOS extensions, and 2 watchOS extensions. Using static libraries, our `pod install` had takes roughly 2 or 3 minutes. After enabling `use_frameworks!`, it takes about 11 or 12 minutes, most of which is spent on "- Linking headers" and "Installing targets". Disabling the watchOS frameworks returns the `pod install` time to normal. Note that while the other targets have many dependencies, the watchOS ones have only two (AFNetworking and a private development pod).

I've tried to reproduce this in a blank project, with no luck. Let me know if there's other information I can provide.

Using 0.38.2, but 0.39.0.beta.4 has the same effect.

Thanks for all your excellent work.

**Comment by segiddins** [comment]
Can you share a Podfile (or even better, a project)? This won't really be enough information to investigate.

**Comment by neonichu** [comment]
We never got a project to reproduce — will reopen if we do.
