### ISSUE TITLE
Rermove Pod raises Error: dyld: Library not loaded:

### ISSUE THREAD

**Issue by confile** [CocoaPods/CocoaPods#4241]
I use Cocoapods in my Xcode project and I installed SwiftyJSON as a pod: 

```
    target 'TestProject' do 
       pod 'SwiftyJSON', '~> 2.3.0' 
    end
```

After a while I removed it from the pod and did: ``pod install`` to perform the delete. 

When I run my project on the simulator I have no problem but when I run I on a device the app crashes with the error: 

```
    dyld: Library not loaded: @rpath/SwiftyJSON.framework/SwiftyJSON
      Referenced from: /var/mobile/Containers/Bundle/Application/87774D56-6869-40B8-87BC-373C160CCE95/TestProject.app/TestProject
      Reason: image not found
    (lldb) 
```

**Comment by segiddins** [comment]
Have you done a clean build and/or deleted derived data?

**Comment by confile** [comment]
Which commands should I use?

**Comment by kaka1220** [comment]
me too

**Comment by orta** [comment]
Come on you two, try searching for those terms if you don't understand them: [how to delete derived data](http://stackoverflow.com/questions/24039932/how-to-delete-derived-data-in-xcode6) - [xcode clean build](https://www.google.co.uk/search?hl=en&q=xcode+clean+build&gws_rd=cr&ei=2ksCVry3IYGQaI7dr6AH#hl=en-GB&q=xcode+do+clean+build)

**Comment by kaka1220** [comment]
dyld: Library not loaded: /usr/lib/libiconv.2.dylib
  Referenced from: /Users/tony1220/Library/Developer/CoreSimulator/Devices/50A352C6-EA7D-47F6-A6A9-DB9FFEE928B9/data/Containers/Bundle/Application/B0F0E6A2-6772-44EC-8BCA-CF6AADB46C0C/xxxxxxx.app/xxxxxxx
  Reason: no suitable image found.  Did find:
	/usr/lib/libiconv.2.dylib: mach-o, but not built for iOS simulator
How to resolve this situation , it seems a little bit different and the landlord。please tell me，thank you

**Comment by TonnyTao** [comment]
+1

dyld: Library not loaded: @rpath/Pods_*.framework/Pods_Project
  Referenced from: /private/var/mobile/Containers/Bundle/Application/D3324FBE-61E5-4CDB-9B9A-3BA2421B0667/Project.app/Project
  Reason: image not found


Xcode 7.0.1
pods 0.39.0.beta.4

framework  Required

**Comment by segiddins** [comment]
@TonnyTao have you tried my suggestion?

**Comment by neonichu** [comment]
BTW, `Pods_Project.framework` should be weak linked — did you manually change it to be required?

**Comment by neonichu** [comment]
Closing because of lack of response.

**Comment by confile** [comment]
Still it does not work. @neonichu Please reopen.

**Comment by confile** [comment]
Pods_Project.framework should be optional?

**Comment by confile** [comment]
After ``pod install`` ``Pods_Project.framework`` is set as required.

**Comment by segiddins** [comment]
@confile as of cocoapods 0.39, it is no longer weak linked, since the aggregate target is built as a static binary, as outlined in the CHANGELOG
