### ISSUE TITLE
Delete .yardopts

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#4242]
https://github.com/CocoaPods/CocoaPods/blob/master/.yardopts ?

**Comment by neonichu** [comment]
Maybe @alloy still knows what this was supposed to do?

**Comment by orta** [comment]
Looks like an doc-like tool - http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md

Don't see it in the Gemfile - https://github.com/CocoaPods/CocoaPods/blob/master/Gemfile

**Comment by segiddins** [comment]
Nope. It's used when generating the docs that we use in dash, and also probably for the guides.
