### ISSUE TITLE
Target 'Pods' of project 'Pods' was rejected as an implicit dependency for 'libPods.a' because it doesn't contain platform 'appletvsimulator' in its SUPPORTED_PLATFORMS 'iphonesimulator, iphoneos'

### ISSUE THREAD

**Issue by SwiftNextStep** [CocoaPods/CocoaPods#4243]
Similar to issue #3681but for the new tvOS, problem happen in the xcode 7.1beta importing a POD for tvOS.

Just update Cocoapods for latest pre release before test and post this issue.

**Comment by neonichu** [comment]
the betas don't support tvOS, yet — you can assemble the branches from the various PRs, though, with a Gemfile like this:

```ruby
source 'https://rubygems.org'

gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git', :branch => 'tvos'
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git', :branch => 'tvos-support'
gem 'xcodeproj', :git => 'https://github.com/CocoaPods/Xcodeproj.git', :branch => 'tkos-support'
```

See <https://guides.cocoapods.org/using/unreleased-features> for more info on how to do this.
