### ISSUE TITLE
0.39 Pods-frameworks.sh doesn't copy vendored_framework into ../Frameworks/*

### ISSUE THREAD

**Issue by julianiaccopucci** [CocoaPods/CocoaPods#4244]
This issue was mentioned for version 0.36 here https://github.com/CocoaPods/CocoaPods/issues/3281 and I was said here https://github.com/CocoaPods/CocoaPods/issues/4236 that it was resolved for version 0.39 but it still happens.

When copying to device, an appears saying:

dyld: Library not loaded: @rpath/....
Referenced from: ....
Image not found

And the /Frameworks folder is empty within the .app archive.

I can provide an example with a private podspec if it's needed

**Comment by segiddins** [comment]
This is insufficient information to debug the issue -- please provide a project we can download that reproduces the problem you're seeing. Thanks!

**Comment by julianiaccopucci** [comment]
I've uploaded 2 version to replicate: device and simulator. podfile points to a local podspec, and the podspec source property point to the root folder where the framework sits.

Download
Unzip
run pod update
Open workspace and run the project

device https://drive.google.com/uc?export=download&id=0B9zg9VcQFkJrdTlsS0FCSVhMbms
simulator https://drive.google.com/uc?export=download&id=0B9zg9VcQFkJrWkZUWG1WenpPUW8

**Comment by segiddins** [comment]
Running `pod update` on that zip fails for me

**Comment by julianiaccopucci** [comment]
It works for me and two other. Did you unzip it? What the terminal log for the error?

**Comment by julianiaccopucci** [comment]
I just run pod --version and I'm still on on 0.38.2, not on 0.39 as I thought.
Running sudo gem install cocoapods --pre still makes me stay on 0.38.2, and I'm not sure how get away from it....

After researching, pod update on the zip would work on 0.38.2 but not on the beta version...

I need to be able to upgrade to beta, before reopening this issue. Any idea why i have this upgrade problem?

**Comment by segiddins** [comment]
just run `pod _0.39.0.beta.4_ install`, but beware that there are a few open issues about the beta

**Comment by julianiaccopucci** [comment]
Could this be an issue?
0.38.2 works fine 0.39 doesn't
<img width="920" alt="screen shot 2015-09-25 at 15 42 50" src="https://cloud.githubusercontent.com/assets/5910320/10103558/7854f5ce-639c-11e5-8b37-8c083b641e33.png">

**Comment by segiddins** [comment]
Your pod spec is missing a version

**Comment by julianiaccopucci** [comment]
I added a version to my podspec but it still doesn't copy to the framework... This is my podspec:


    s.name           		= "MySDK"
    s.version 			= '1.0.0'
    s.source				= {:local => './MySDK.framework'}
    s.vendored_frameworks = 'MySDK.framework'
    s.platform = :ios, '8.0'
    s.ios.deployment_target = '8.0'
    s.requires_arc = true 

A new version with the version included is here https://drive.google.com/uc?export=download&id=0B9zg9VcQFkJrTXFmODVLeDhvR1U

Thanks

**Comment by segiddins** [comment]
The issue now seems to be that the vendors framework you've build doesn't have simulator slices: 

```
ld: warning: ignoring file /Users/segiddins/Downloads/cocoatt/MySDK.framework/MySDK, missing required architecture x86_64 in file /Users/segiddins/Downloads/cocoatt/MySDK.framework/MySDK (2 slices)
```

**Comment by julianiaccopucci** [comment]
I have a 64bit machine and if I add the 32bit library manually, xcode still builds, copies and signes the .framework, but doing it through Cocoapods it still doesn't copy the resource 

I have created a .framework for both 32 and 64. There is a new link here with the updated resource

https://drive.google.com/uc?export=download&id=0B9zg9VcQFkJrVWduUEt6NTV1dW8

**Comment by segiddins** [comment]
Got it! Think it was a migration error that was failing to add the embed frameworks phase to your target. Will make a PR very shortly.

**Comment by sathishvgs** [comment]
@julianiaccopucci , can you explain How you have created the .framework for 32 and 64 bit. I'm also facing this issue.

**Comment by JIACCOPU-ford** [comment]
@sathishvgs follow this link with a sample
https://drive.google.com/uc?export=download&id=0B9zg9VcQFkJrVWduUEt6NTV1dW8
