### ISSUE TITLE
Target overrides the `FRAMEWORK_SEARCH_PATHS` build setting

### ISSUE THREAD

**Issue by romanalexk** [CocoaPods/CocoaPods#4246]
Hello,

I use Xcode7 IDE and Cocoapods 0.38.0. When I run 'pod install' command in the terminal, I get 2 warnings.

[!] The `LendwiseBorrowerTests [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-ProjectNameTests/Pods-ProjectNameTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation

    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `LendwiseBorrowerTests [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-ProjectNameTests/Pods-ProjectNameTests.release.xcconfig'. This can lead to problems with the CocoaPods installation

    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

In order to resolve the warning, I added $(inherited) to the target `FRAMEWORK_SEARCH_PATHS`. The warnings were gone when I ran 'pod install' but there was a new warning in Xcode now.

ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk/Developer/Library/Frameworks'

Could you tell me how to resolve the issue? Thank you.

**Comment by neonichu** [comment]
That warning has been fixed in #4219 and will no longer appear in future releases.

**Comment by 3lvis** [comment]
Thanks! This was so annoying.
