### ISSUE TITLE
[0.39.0.beta.3] Headers for framework dependency are not found

### ISSUE THREAD

**Issue by rgal75** [CocoaPods/CocoaPods#4247]
:rainbow:
I had to switch to v0.39.0.beta.3 since v0.38.2 prevents generating iOS App Archives with XCode 7.

With v0.39.0.beta.3, the umbrella header of a framework dependency of my application (namely ScoutMaps-iOS-SDK) can no more be found, i.e. the 
`#import <SKMaps/SKMaps.h>`
line has an error: "**file not found**". (With v0.38.2 and the same Podfile, this was not an issue.)

 Having checked the target build settings I found that
* HEADER_SEARCH_PATH has the entry: `"${PODS_ROOT}/Headers/Public/ScoutMaps-iOS-SDK"`. However, that folder does not exist. `${PODS_ROOT}/Headers/Public/` contains all other dependencies except ScoutMaps-iOS-SDK, which is a framework (and by the way not open source).

Here is my Podfile for reference:
```ruby
workspace 'MyWorkspace'
platform :ios, '8.0'

xcodeproj 'MyLib/MyLib', 'Coverage' => :debug

pod 'AFNetworking', '2.5.4'
pod 'ZipArchive', '1.3.0'
pod 'FMDB', '2.5'

target 'MyLibTests' do
    pod 'OCMock', '3.1.2' 
    pod 'OCHamcrest'
end

target 'MyApp' do
    xcodeproj 'MyApp/MyApp', 'Coverage' => :debug
    pod 'AFNetworking', '2.5.4'
    pod 'ZipArchive', '1.3.0'
    pod 'FlurrySDK', '6.7.0'
    pod 'FMDB', '2.5'
    pod 'ScoutMaps-iOS-SDK', '2.5'
    pod 'Typhoon', '3.1.8'

    target 'MyAppTests', :exclusive => true do
        pod 'OCMock', '3.1.2'
        pod 'OCHamcrest'
        pod 'ScoutMaps-iOS-SDK', '2.5'
    end
end

pre_install do |installer|
    _shellScript = "scout-maps-stripper.sh"
    system("sh #{_shellScript}")
end
```

**Comment by segiddins** [comment]
Seems to me like the `SKMaps` headers should be using framework-style includes.

**Comment by rgal75** [comment]
`#import <SKMaps/SKMaps.h>` is a framework-style include, isn't it? 
Still, the header is not found.

**Comment by segiddins** [comment]
No, the headers inside the `SKMaps` framework itself are using quoted includes instead of framework includes, and I believe that's causing the issue.

**Comment by rgal75** [comment]
Indeed, the includes within SKMaps.h are not framework style. 
I informed Scout (the provider of ScoutMaps-iOS-SDK) to fix this issue. 

Thanks.

**Comment by sjmadsen** [comment]
We've run into the same issue for the same reason. The pod that's causing our problems is AWSiOSSDK (1.7.1). This version of the SDK is deprecated (for new projects) and Amazon isn't making any new changes to it. We can't switch to version 2, though, because it's not source-level compatible and the necessary rewrites aren't in our schedule.

Is there a way to work around this issue within the Podfile?

**Comment by segiddins** [comment]
@sjmadsen you could probably hack together a post install hook?
