### ISSUE TITLE
Is it possible to skip "Resolving Dependencies" stage during `pod install`

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#4250]
`pod install` for our project takes 2m 10seconds right now which is a lot of time. About a minute or so is spent on resolving dependencies but I am failing to see why since they are all listed in the Podfile.lock?

Feel free to close if there is no actionable item or discussion that can be made here...we're profiling internally the process and `analyzer.analyze` takes a long of time.

**Comment by dnkoutso** [comment]
I guess I understand how core to the installation process is to resolve dependencies but why spend so much time if all of them are specified in the lock file?

**Comment by segiddins** [comment]
Without a project we can use to investigate, I don't know what to tell you.

**Comment by dnkoutso** [comment]
Cant do that, its a huge project with 50 dependencies and a lot of confidential files.

I guess a sample project might make more sense but for now I am closing since this wont yield any results...
