### ISSUE TITLE
[0.39.0.beta.4] File not embed in the project.

### ISSUE THREAD

**Issue by seanLee** [CocoaPods/CocoaPods#4251]
When I use ````0.39.0.beta.4````,every time I run ````pod update````,it will appear a issue that not find file ````xxxx.h````,I clicked on the menu,the file is not embed in the project.
And downgrading to ````0.38.2````,every is OK.

**Comment by segiddins** [comment]
Can you please follow the instructions outlined in the contributing guidelines and provide us with steps to reproduce the issue you're experiencing? Thanks!

**Comment by seanLee** [comment]
Sorry,just see this now.I don't know how to reappear the issue,but the issue is appear in this project````https://github.com/Coding/Coding-iOS.git````.Using cocoapods[0.39 beta4],maybe u can see this.

**Comment by segiddins** [comment]
@seanLee the error I'm seeing when building your project is

```
clang: error: no such file or directory: '/var/folders/p3/950_j_ps7xq47vrzdj1qvg940000gn/T/Coding-iOS/Coding_iOS/Coding_iOS-Prefix.pch'
clang: error: no input files
```

which is caused by the fact that `Coding_iOS/Coding_iOS-Prefix.pch` doesn't exist, only `Coding_iOS/Coding_iOS-Prefix.pch.example`, which is not a CocoaPods issue.

**Comment by neonichu** [comment]
Closing because of lack of response.
