### ISSUE TITLE
iOS App + Today Widget + WatchKit App = "No such module" error

### ISSUE THREAD

**Issue by C4Grey** [CocoaPods/CocoaPods#4254]
Hi! I've just added a WatchOS 2 target to my project and after running "pod install" my application target(or today widget target, if I swap order of target in the podfile)  cannot found any of shared modules. I've also tried to create a new project from scratch, clean the DerivedData, and so on, same result with both v0.39.0.beta.4 and v0.38.2. Here is my podfile:
````ruby
platform :ios, '9.0'
use_frameworks!

def extension_pods
    pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift.git', :branch => 'swift-2'
    pod 'Timepiece', :git => 'https://github.com/C4Grey/Timepiece.git', :branch => 'patch-1'
end

def main_pods
    extension_pods
    pod 'IQKeyboardManager'
    pod 'XLForm', :git => 'https://github.com/xmartlabs/XLForm.git'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'
end

target :'MainApp' do
    main_pods
end

target :'TodayWidget' do
    extension_pods
end

target :'WatchKit App Extension' do
    platform :watchos, '2.0'
    pod 'Timepiece', :git => 'https://github.com/C4Grey/Timepiece.git', :branch => 'patch-1'
end
````
And, as result it can not find a module 'Timepiece' pointing to the line
````swift
import Timepiece
````
In the targets section of a Pods project I've noticed two framework targets: one prefixed with a name of the main app target, and another one is prefixed with a name of the WatchOS target. This iOS-specific target(something like "Pods-MainApp-Timepiece") is used in the TodayWidget and MainApp targets, but somehow it is not working for one of targets(as I wrote before, it depends of an order of targets in the podfile). For now I am using a workaround specifing a different platform for the TodayWidget target, so CocoaPods creates three framework targets, but this is not seems right.
P.S. The problem is definitely not in the specific framework, I've also tried to use a few other frameworks shared between all three targets, same result.

**Comment by neonichu** [comment]
You might be having the same issue as #4231

**Comment by C4Grey** [comment]
@neonichu Thank you, disabling of the targets deduplication feature may help, but I hope it is a temporary solution, since a time of project compilation increases dramatically...

**Comment by neonichu** [comment]
It is supposed to be temporary, yes. 

I'm closing this issue, because your Podfile is very similar to the one in #4231
