### ISSUE TITLE
Can't push podspec even though it validates

### ISSUE THREAD

**Issue by solrankos** [CocoaPods/CocoaPods#4255]
I get an error claiming that my podspec does'nt validate event though it just passed validation.
```
pod lib lint --sources= xxxxxxxxx,master --use-libraries --allow-warnings --verbose

xxxxxxxxx passed validation.
```

```
$ pod repo push xxxxxxxxx --use-libraries --allow-warnings

Validating spec
[!] The `xxxxxxxxx.podspec` specification does not validate.
```

**Comment by orta** [comment]
Trunk may be giving you errors, in 0.39 we show them, but you can do `--verbose` on `pod repo push` to see them. Could be that your tag isn't there yet.

**Comment by solrankos** [comment]
Just saw that i forgot to push the tag... :grimacing:

**Comment by orta** [comment]
yeah `lib lint` runs local `spec lint` does that test too

**Comment by solrankos** [comment]
Ok! Will use that next time. Thanks!
