### ISSUE TITLE
[Question] How to specify different branches of the same pod for different targets?

### ISSUE THREAD

**Issue by bruceflowers** [CocoaPods/CocoaPods#4256]
I have a project that has an iOS target and a tvOS target. Both need to use the same pod, but each needs to use a different branch of that pod. I've tried to do this (using 0.39.0.beta.4), but without success:

target :Target1, :exclusive => true do
        pod ‘Blah' , :git => 'https://github.com/blah', :branch => ‘branch1'
end

target :Target2, :exclusive => true do
        pod ‘Blah' , :git => 'https://github.com/blah', :branch => ‘branch2'
end

But pod install tells me something like this:

[!] There are multiple dependencies with different sources for 'Blah' in 'Podfile'

Is what I'm trying to do possible and I'm just doing something wrong?

**Comment by segiddins** [comment]
That's not possible -- you'll need to settle upon a single branch for the `Blah` pod, sorry.

**Comment by orta** [comment]
You could do something like this too: https://github.com/artsy/Artsy-Authentication/blob/tvos/Artsy%2BAuthentication.podspec#L23-L26

**Comment by bruceflowers** [comment]
@orta thanks for the tip, I may ending trying that out.
