### ISSUE TITLE
"pod lib lint --use-frameworks"  deprecated? Errors 'Unknown option: `--use-frameworks`'

### ISSUE THREAD

**Issue by valerius** [CocoaPods/CocoaPods#4257]
I modularize applications I create with Cocoapods (all in Objective C), which uses a subspec SCFacebook which in turn, has subspec's for Faceebook. I may use the Facebook subspec's directly without issue, and may likewise use the sample app included in SCFacebook which also uses the Facebook spec's without issue, yet using SCFacebook as a wrapper causes problems when imported into a new Swift project with various messages of:
```
include of non-modular header inside framework module 
```
Thus, to it seems 'subspec' related, and to debug the issue as hinted in post announcing Swift support:
```
http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
```

It read in part:

**
To use this subspec in Swift without a generated umbrella header, you would need to create a bridging header and use an import like #import <AFNetworking/AFNetworking+UIKit.h>. With the generated umbrella header, you just need to import AFNetworking if you have the subspec included in your Podfile. If your pod doesn't work out of the box, you can use pod lib lint --use-frameworks <YourPod.podspec>, to check what is wrong.
**

However, which I use the --use-frameworks switch it fails with error:

```
pod lib lint --use-frameworks SCFacebook.podspec 
[!] Unknown option: `--use-frameworks`
Did you mean: --use-libraries
```

Wherefore, I'm guessing its been deprecated, is there an equivalent option or is it no-longer necessary and I can rely on the errors generated without the option? Any help with the option or at least a means or direction to debug such errors would be greatly appreciated. My goal was to submit a pull request to SCFacebook instead of a issue if necessary, but am having trouble finding the same level of documentation for this use case of Objective-C -> Swift/Module subspec, etc. I was hoping the option might tell me more. Thanks in advance :)

**Comment by segiddins** [comment]
No, frameworks are now the default when linting, and `--use-libraries` must now be specified if you wish to lint as a static library.

**Comment by valerius** [comment]
Thanks segiddins!!! Thats the beginning I needed :)
