### ISSUE TITLE
Bitcode marker-error when submitting app to testflight

### ISSUE THREAD

**Issue by ramyala** [CocoaPods/CocoaPods#4260]
I'm on Xcode7 / iOS 9 and have been having trouble with uploading my binaries to TestFlight.

First, I got the following error which was fixed by using cocoapods from #4221.

```
Invalid Swift Support - The files 
libswiftAssetsLibrary.dylib, libswiftCoreLocation.dylib don’t match
/Payload/Test.app/Frameworks/libswiftAssetsLibrary.dylib, 
/Payload/Test.app/Frameworks/libswiftCoreLocation.dylib. 

Make sure the files are correct, rebuild your app, and resubmit it. 
Don’t apply post-processing to 
/Payload/Test.app/Frameworks/libswiftAssetsLibrary.dylib, 
/Payload/Test.app/Frameworks/libswiftCoreLocation.dylib.
```

Then, I got another error email from TestFlight with this message:

```
Invalid Bundle - Failed to verify bitcode in AERecord.framework/AERecord: error: Bundle only contains bitcode-marker Test.app/Frameworks/AERecord.framework/AERecord (armv7) ...

Invalid Bundle - Failed to verify bitcode in Alamofire.framework/Alamofire: error: Bundle only contains bitcode-marker Test.app/Frameworks/Alamofire.framework/Alamofire (armv7) ...

Invalid Bundle - Failed to verify bitcode in Bolts.framework/Bolts: error: Bundle only contains bitcode-marker Test.app/Frameworks/Bolts.framework/Bolts (armv7) ...

...
<same error for all other pods and private framework targets>
```

Does anyone know how to fix this or why this is happening? This has only started to be an issue after moving to Xcode 7. We had no issues before that with cocoapods 0.38.2.

I tried disabling Bitcode in Xcode for the Application, Share extension and Framework targets, but that didn't fix the error.

Here's the podfile for my project:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

# Order the following dependencies alphabetically
target 'Application' do
  pod 'AERecord'
  pod 'Alamofire'
  pod 'Bolts/Tasks'
  pod 'Parse'
  pod 'ParseCrashReporting'
  pod 'SDWebImage'
  pod 'SlackTextViewController'
end

target 'XYZKit' do
  pod 'AERecord'
  pod 'Bolts/Tasks'
  pod 'Parse'
  pod 'SDWebImage'
end

target 'Share' do
  pod 'AERecord'
  pod 'ColorUtils'
  pod 'KMPlaceholderTextView'
  pod 'Parse'
  pod 'RSKImageCropper'
  pod 'UIImage-Resize'
end

target 'XYZKitTests' do
  pod 'AERecord'
  pod 'Bolts/Tasks'
  pod 'Parse'
  pod 'SDWebImage'
end

```

**Comment by segiddins** [comment]
How are you creating your archive? Xcode should automatically handle using `-fembed-bitcode` instead of `fembed-bitcode-marker` when you do an `Archive` build.

**Comment by ramyala** [comment]
Currently I just let http://Ship.io CI do the archiving. I don't see either of those flags in the build logs either. May be cocoapods didn't set up the flags properly for archive? It didn't make a difference whether i set Enable Bitcode to YES or NO in Xcode for my targets. Any suggestions on how to debug this issue?

Unfortunately if i use xcode locally to build an archive, the organizer doesn't recognize them as an ipa. I'm seeing this error which I wasn't able to fix but this could be a different build issue unrelated to this:
https://developer.apple.com/library/ios/technotes/tn2215/_index.html

**Comment by segiddins** [comment]
Do you have any more details on how ship builds the archive? Otherwise, it'll be really hard for us to investigate

**Comment by ramyala** [comment]
As far as i know, ship.io is using xcode 7 to build it in a container env.

Here's the build log from the console. Does this help?
http://pastebin.com/8AMr36dw

**Comment by segiddins** [comment]
It's using xctool, which I know absolutely nothing about ¯\_(ツ)_/¯
Perhaps there's an `xctool archive` command they should be using?

**Comment by neonichu** [comment]
FWIW, you'll get the "Failed to verify bitcode" when some binaries in your bundle have bitcode and some don't.

**Comment by segiddins** [comment]
So, what can we actually do about this? I'm inclined to write this off as an xctool issue?

**Comment by ramyala** [comment]
I notified ship.io and waiting for them to respond. I am able to archive from Xcode locally and submit to testflight. Hence, I'm ok with closing this issue.

Sent while mobile

**Comment by segiddins** [comment]
Awesome, let us know what they say!
