### ISSUE TITLE
Get this when try to build my project 

### ISSUE THREAD

**Issue by philipheinser** [CocoaPods/CocoaPods#4270]
```
sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

**Comment by segiddins** [comment]
Can you please provide the information requested in the contributing guidelines? This bug report doesn't contain enough info for us to really know what's going on.

**Comment by David2XN** [comment]
Same problem after upgrading to xcode 7. Cocoapod version 0.38.2

My Podfile:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 2.0'
pod 'Crashlytics'
pod 'Fabric'

pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

**Comment by David2XN** [comment]
Deleting project data in Library/Developer/Xcode/DerivedData solved problem

**Comment by geowarsong** [comment]
Had same issue using Xcode 7.3.1 and deleting files from Library/Developer/Xcode/DerivedData solved problem for me too.
