### ISSUE TITLE
Enable declaring required `LSApplicationQueriesSchemes` in a podspec

### ISSUE THREAD

**Issue by chrismaddern** [CocoaPods/CocoaPods#4271]
As of iOS 9, libraries that need to check the availability of an app or implementer of a URL scheme through `canOpenURL:` need to pre-register those schemes in their `info.plist`. For libraries distributed with CocoaPods this is now a manual step after integrating the pod.

A few examples of this are the Facebook SDK, Venmo SDK, (Anybody doing app-switch auth) as well as anything handling app installation or deep linking (e.g. Button - where I originally had this though).

I propose a new `Podspec` field to add schemes to the `info.plist` file:

```ruby
   spec.required_query_schemes = ["fb", "fbapi"]
```

Before taking any steps to introduce this, I wanted to see what people thought of this?

- Do Query Schemes fall under the remit of CocoaPods?
- Should CocoaPods be modifying the info.plist file?
- Are there other ways I'm overlooking to achieve this in the current Podspec standard. (e.g. Post-integration build scripts could have done it in the past)

Would love thoughts from any and all - +1 / -1 welcome!

**Comment by segiddins** [comment]
I don't feel like pods should be allowed to modify the info.plist -- there's just too much room for things to go wrong there. I also really really dislike adding new fields to the podspec, since we need to support them for _forever_. All in all, I think it's fine for users to need to modify their own info.plist files as necessary.

**Comment by chrismaddern** [comment]
@segiddins How do you communicate that to the developer?

**Comment by segiddins** [comment]
Documentation? The pod can also introspect the main bundle plist at runtime to verify things are set up.

**Comment by orta** [comment]
Yeah, I'm with @segiddins here :+1:

**Comment by orta** [comment]
OK, calling this one - love you gents, but I don't think it's happening
