### ISSUE TITLE
Copying resources for Watch Extensions need to go to the Watch App

### ISSUE THREAD

**Issue by michaelochs** [CocoaPods/CocoaPods#4275]
When adding a pod that contains resources to a Watch Extension, these resources need to be copied to the Watch App instead of the Watch Extension.

Two potential systems of doing that come to my mind:
a) There needs to be an instruction in the `Podfile` that links watch extensions to its corresponding watch apps. (There can be multiple of both due to watchOS 1 and watchOS 2 apps/extensions.)
b) You simply add the same pod to both, the watch extension and the watch app and cocoa pods needs to ensure that for the watch app no framework or library will be linked and for the watch extension no resources will be copied.

Note: This issue is related to #4178 as copying resources to an extension will break the archive process of Xcode.

**Comment by neonichu** [comment]
I think we can determine the relationship between watch app and extension from the user project itself.

**Comment by michaelochs** [comment]
That would be the best solution if this is possible. Haven't looked into the build settings, but e.g. in our App we have two watch apps with the same bundle identifier (watchOS 1 and watchOS 2) and two watch extensions with different bundle identifiers. But I guess it is possible somehow as iOS is able to check that as well...

**Comment by neonichu** [comment]
Seems like the link between them is established via the `IBSC_MODULE` build setting in the watch app, which contains the module name of the corresponding watch extension. I'm assuming this has to be unique?

**Comment by segiddins** [comment]
@neonichu there can be multiple targets with the same module name that have different built product names?

**Comment by jcampbell05** [comment]
@segiddins  Could you not look at the dependencies or build phases ? i.e If a watch app embeds an extension or has that extension as a dependency then they are related :)

**Comment by segiddins** [comment]
I had a branch that tried to do it but @neonichu talked me out of it
