### ISSUE TITLE
Extension safe API helper

### ISSUE THREAD

**Issue by Mazyod** [CocoaPods/CocoaPods#4277]
I wonder if it makes sense to add a helper function, like `use_frameworks!`, but that sets all targets as app extension safe API?

My use case is, I have written 5 separate framework projects, that link to some pods, and I plan to use them in an app extension. I could write a post install hook in all of them to set the configuration, but that would be too much duplication, methinks:
http://stackoverflow.com/questions/29102814/unable-to-archive-build-with-share-extension-and-afnetworking-cocoapod

Thanks!
Maz

**Comment by segiddins** [comment]
Post install hook with a loop is the right way imho

**Comment by neonichu** [comment]
Yep, we shouldn't introduce more DSL for build settings.
