### ISSUE TITLE
use_frameworks! - Duplicate definition of category on interface

### ISSUE THREAD

**Issue by opfeffer** [CocoaPods/CocoaPods#4280]
I know this has been asked multiple times (see [here](http://stackoverflow.com/q/28746129), [here](https://github.com/CocoaPods/CocoaPods/issues/1729), or [here](http://blog.sigmapoint.pl/avoiding-dependency-collisions-in-ios-static-library-managed-by-cocoapods/)).. but they're mostly working with statically linked libraries. In my case, I'm trying to use iOS8+'s dynamically linked frameworks:

Here's my project structure:

#### Project/Podfile
```
platform :ios, '8.1'
use_frameworks!

target :MyProject do
	#pod 'PromiseKit'
	pod 'MyDynamicFramework', :path => '../MyDynamicFrameowork'
end
```

#### MyDynamicFramework.podspec
```
Pod::Spec.new do |s|
[..]
s.dependency 'PromiseKit'
[..]
end
```

I typically import my framework via its umbrella header, like so:
`#import <MyDynamicFramework/MyDynamicFramework.h>`.

However, it so happens that not only my framework requires `PromiseKit` but also my actual project. I got weird `no known class method for selector` errors initially but I was able to get rid of those as long as I would `#import` PromiseKit BEFORE importing my framework's umbrella header, like so:

#### RandomViewController.m

```
#import "RandomViewController.h"
// WORKS:
#import <PromiseKit/PromiseKit.h>
#import <MyDynamicFramework/MyDynamicFramework.h>

// DOES NOT WORK:
//#import <MyDynamicFramework/MyDynamicFramework.h>
//#import <PromiseKit/PromiseKit.h>

@implementation RandomViewController
[..]
@end
```

While my project now actually compiles and runs, I have hundreds of `Duplicate definition of category 'PromiseKit' on interface '*'` warnings... If I expand the warning I get

> In module 'MyDynamicLibrary'
> Imported from /Users/..../Builds/Products/iphone-simulator/MyDynamicLibrary.framework/headers/SomeFrameworkClass.h:10

Is there anything obvious I'm missing here?

PS: I added an example project for reference: https://github.com/opfeffer/CocoaPodsTest

**Comment by segiddins** [comment]
What happens if you change the imports to modular imports, i.e. `@import`?

**Comment by neonichu** [comment]
I can't repro this issue with your example project, if I remove the PromiseKit import from your view controller, it just works as expected.

Possibly the difference is that the Podfile you have in the issue has the PromiseKit dependency commented out for your application target whereas the example does not.

If you directly use a transitive dependency somewhere, you have to explicitly specify it when using frameworks.

**Comment by haifengkao** [comment]
got the same problem

**Comment by ergunkocak** [comment]
I also started seeing 
"/Pods/Headers/Public/FirebaseAnalytics/FirebaseAnalytics/FIRAnalytics+AppDelegate.h:19:12: Duplicate definition of category 'AppDelegate' on interface 'FIRAnalytics'"
as a warning after switching to "use_modular_headers!" instead of "use_frameworks!"
