### ISSUE TITLE
Generic Xcode Archive----v0.39.beta.4 Archive can not make app Type 

### ISSUE THREAD

**Issue by oday0311** [CocoaPods/CocoaPods#4282]
hi, my last update of pod, make my project no longer to make the right Archive any more, which we still need to support iOS 7,,

I have tried to update to using_framework!  way, this can help to fix this problem , but using_framework means i have to give up support to iOS 7, So , is there any way to fix this "Generic Xcode Archive----v0.39.beta.4 Archive can not make app Type " with support to iOS7?????

![2015-09-29 12 07 42](https://cloud.githubusercontent.com/assets/892644/10155084/b6a75142-66a2-11e5-88e7-b3f558346243.png)

///////////////////////////////

BTW, I also try some trick like set Skip_install = YES, but , does not work, i already sure it is the new version cocoapod cause this problem.

even a complete new project , with v0.39, using normal config like

platform :ios, '7.0'

pod 'MHPrettyDate'

can not archive a APP ipa any more,,,,

any help ?????

**Comment by segiddins** [comment]
This has been fixed in master

**Comment by oday0311** [comment]
thanks, ,temply back to v0.38 version....
