### ISSUE TITLE
Unable to submit to iTunesConnect with latest master cocoapods (Invalid Bundle)

### ISSUE THREAD

**Issue by tonyxiao** [CocoaPods/CocoaPods#4283]
Following the issue here https://github.com/CocoaPods/CocoaPods/issues/4188, I upgraded to use the latest version of cocoapods from master. However once I create an ipa using this latest cocoapods I get the following error when trying to submit to iTunesConect. 
```
Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/tmp/circle-artifacts.Eq15x1t/Package.itmsp - Error Messages:
		ERROR ITMS-90035: "Invalid Signature. Invalid signature (code or signature have been modified). Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"
		ERROR ITMS-902ERROR ITMS-90206: "Invalid Bundle. The bundle at 'Taylr.app/Frameworks/Core.framework' contains disallowed file 'Frameworks'."
```

**Comment by neonichu** [comment]
This looks like a completely different issue, because it involves code-signing issues. Historically, those have always boiled down to configuration problems, please check the existing issues for that. If that doesn't help you, please attach an example project which exhibits the issue.

**Comment by tonyxiao** [comment]
The only difference between two commits, one worked, the other didn't, is this. 

```
Tony:ios (prod)$ git diff head~2 head~
diff --git a/circle.yml b/circle.yml
index c2fc8cd..b22be67 100644
--- a/circle.yml
+++ b/circle.yml
@@ -21,6 +21,8 @@ dependencies:
     - sudo gem install cupertino shenzhen sigh xcpretty
     - ./scripts/import_credentials.sh
   override:
+    - sudo gem install specific_install
+    - sudo gem specific_install https://github.com/CocoaPods/CocoaPods.git
     - pod update Meteor SugarRecord PKHUD
   cache_directories:
     - "Pods"
```

Before this commit, I used to get problem described in this issue https://github.com/CocoaPods/CocoaPods/issues/4188. After this commit, I'm getting this message `Invalid Bundle. The bundle at 'Frameworks/Core.framework' contains disallowed file 'Frameworks`. There are no other changes. We have a framework target in the same project that gets compiled into the application target. I'm not sure whether that has anything to do with it.

**Comment by tonyxiao** [comment]
@neonichu
