### ISSUE TITLE
Archive failed in Xcode 7 with WatchOS 2 and Extension Targets

### ISSUE THREAD

**Issue by swissdev** [CocoaPods/CocoaPods#4284]
Hi,

We are trying to build an archive for hours and it doesn't work.. :(
Parallelize Builds are turned off, Copy Pods Ressources are removed, Cocoapods Beta 4 is installed, Bitcode disabled and deduplicate_targets is set to false.

It works perfect on simulator and device.

If we build the archive it success with some umbrella warnings:
"Umbrella header for module Alamofire does not include header 'Pods-App-Today-Alamofie-Umbrella.h"

And lots of .. warning: skipping copy phase strip, binary is code signed:...

After Archiving the app does not show in the Organizer, because of:
29.09.15 11:29:42.361 Xcode[99103]: Cannot make directory /Users/xx/Library/Developer/Xcode/Archives/2015-09-29/app.xcarchive/dSYMs/Alamofire.framework.dSYM: File exists

What are we doing wrong?

Our podfile is:
***
platform :ios, '8.0'
use_frameworks!

def shared_pods
    pod 'Alamofire', '~> 2.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'
end

target 'App' do
    shared_pods
    pod 'Fabric'
    pod 'Crashlytics'
end

target 'App-Today' do
    shared_pods
end

**Comment by neonichu** [comment]
Setting `deduplicate_targets` to `false` won't work for application extensions.

**Comment by swissdev** [comment]
Ah, ok. I've misread this in another issue. Great! Many thanks. Finally it works now.
We compared and updated the build settings with a new project too, which had some differences.

**Comment by neonichu** [comment]
Good to hear it works now :tada:

**Comment by swissdev** [comment]
Hi,

we are now experience the same issue again after updating to El Capitan and Cocoapods 0.39:

Umbrella header warnings..
And after archiving it says in the console:
12.10.15 09:52:11.841 Xcode[36551]: Cannot make directory /Users/xx/Library/Developer/Xcode/Archives/2015-10-12/Landi 12.10.15, 09.52.xcarchive/dSYMs/Alamofire.framework.dSYM: File exists

Target deduplication is on..

**Comment by danilotorrisi** [comment]
Same problem here, El Capitan and CocoaPods 0.39.
