### ISSUE TITLE
Getting linker error ld: library not found for -lPods-ObjectiveSugar

### ISSUE THREAD

**Issue by squalx** [CocoaPods/CocoaPods#4286]
My cocoa pods installation works right now, but the moment I try and install something new , I get this error with Objective Sugar. 

```ld: library not found for -lPods-ObjectiveSugar```

Also, when I do the install, with the latest version of Cocoa Pods I get 20 of these messages.

```
[!] `<PBXGroup name=`Global` UUID=`725540F41BA7110C009D31E7`>` attempted to initialize an object with an unknown UUID. `9DA47FCD690DACD8BF9B05E9` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.
```

I’ve asked this same question in Stackoverflow, but the question has been sitting there for a week.

http://stackoverflow.com/questions/32768516/cocoapods-ld-library-not-found-for-lpods-objectivesugar

All this started happening after installing Xcode 7 and running a Shenzhen script to try and build.

https://github.com/nomad/shenzhen

The shenzhen command to build is very simple, I’m not doing anything fancy: ipa build --clean -s “App_iOS_CI" -c "Release" --ipa app.ipa

Here’s my latest podfile:

```
pod 'ObjectiveSugar', '~> 1.1'
pod 'SWRevealViewController', '~> 2.3'
pod 'Masonry', '~> 0.6'

pod 'AUISelectiveBordersView', '~> 0.0'
pod 'AFNetworking', '~> 2.6'
#pod 'DSNestedAccordion', '~> 0.1'
#pod 'MBProgressHUD', '~> 0.9'

#pod 'SparkInspector'
pod 'Typeset', '~> 1.1'
pod 'CocoaLumberjack', '~> 2.0'
```

I moved ObjectiveSugar down the list and still got issues with it, so I went ahead and removed the library and linked it myself, outside of cocoa pods. The issue still remains.

Tried everything on this post: Cocoapods ld: library not found for -lPods-Projectname (http://stackoverflow.com/questions/24078597/cocoapods-ld-library-not-found-for-lpods-projectname)

Removing and adding the library again (pod install) Deleting the -lPods-Projectname.a in Link Binary ( deleting binary from link binary with libraries on App target, build phases.)

Tried Build Active Architectures YES and NO.

Tried pod deintegrate, removing the workspace after this happens, removing the Podfile.lock (which I’m sure does nothing, really) and then pod install.

I haven’t uninstalled Xcode, and reinstalled cocoa pods, etc… That seems overkill.

Also tried everything in this troubleshooting guide http://guides.cocoapods.org/using/troubleshooting.html (4. If Xcode complains when linking)

Ask for any info you might need, please. Unfortunately, I can’t share my code. Company policy and all that.

I couldn’t find a solution in your issue list, but maybe I missed something because I’m not searching correctly? If you point me to an answer I can try more stuff, but I did try several things that I found in some of the issues on this site.

Any help would be appreciated. Thanks.

**Comment by segiddins** [comment]
Since you haven't shared the actual corrupt project file, I'm not really sure what we can do?

**Comment by squalx** [comment]
Ok, then I'll close the issue. Thanks anyway.
