### ISSUE TITLE
Is it possible to have additional licenses included in the generated Pods-Acknowledgements.plist?

### ISSUE THREAD

**Issue by matt-curtis** [CocoaPods/CocoaPods#4287]
In my project, I have additional third-party libraries that aren't pods. Is it possible to use custom `LICENSE` files (or other mechanism) and have them included in the generated `Pods-Acknowledgements.plist`?

**Comment by segiddins** [comment]
You could use a `prepare_command` to `cat` together a bunch of different files, or do so in your podspec when setting the `license` property.

**Comment by matt-curtis** [comment]
I don't have any `podspec`s, so I assume that's not an option... `Pods-Acknowledgements.plist` is a fully-formed XML file, so simply concatenate licenses together won't quit work AFAIK?

**Comment by segiddins** [comment]
Ah. I thought you had a pod that included non-pod frameworks. You could use a `post_install` hook in the podfile to manipulate the acknowledgements files?
