### ISSUE TITLE
Incorrect behavior with tag and branch of same name

### ISSUE THREAD

**Issue by shortstuffsushi** [CocoaPods/CocoaPods#4289]
So, this was mostly a bug on the end of the pod releasing their product, but it brought up a question that I haven't searched through the internals of Cocoapods to figure out.

In my podspec, say I have

```
s.source = {
   url: 'https://github.com/branchmetrics/branch-ios-sdk',
   tag: '0.11.5'
}
```

But for some reason, say that I have both a tag named 1.0 and a branch named 1.0 that are at different commit pointers. I would expect that, even in this awkward situation, the *tag* would be pulled, as I specified that I wanted a tag, not a branch. However, the opposite seems to be true -- I ended up getting the branch instead of the tag.

Depending on the implementation of Cocoapods, this may or may not be an underlying git thing, I haven't looked. In either case, it would still be preferable (if possible) that Cocoapods explicitly pull the requested resource instead of the one that git decides is correct (if that's what's happening).

**Comment by segiddins** [comment]
This _is_ an underlying git thing, since we use `--branch` to clone, and there is no equivalent `--tag` option.

**Comment by shortstuffsushi** [comment]
Why not use something like `git checkout tags/{tag}`?

**Comment by segiddins** [comment]
Because then wed still need to clone the entire repos history.

**Comment by shortstuffsushi** [comment]
Hmm, I guess I don't know how you're currently fetching the remote resources, but it seems there ought to be a way to fetch tags without getting the whole history. At any rate, the current method won't work in this scenario, whether you guys want to come up with a workaround or not is up to you. As I said, this was brought to my attention due to an issue with the way the pod was released anyway, so it won't be an issue for me any longer.

**Comment by segiddins** [comment]
We do shallow clones to make downloading potentially hundreds of times faster :/ I suppose this edge case is the one cost of that
