### ISSUE TITLE
xcode 7, cocoapods 0.38.0 ~ 0.39.0.beta.4, Library not found for -lPods,

### ISSUE THREAD

**Issue by AbooJan** [CocoaPods/CocoaPods#4292]
OSX 10.10.5
Xcode 7.0(7A220)
IOS 9.0 SDK

there is your company website answer：

----------------------
If Xcode complains when linking, e.g. Library not found for -lPods, it doesn't detect the implicit dependencies:

1. Go to Product > Edit Scheme
2. Click on Build
3. Add the Pods static library, and make sure it's at the top of the list
4. Clean and build again
5. If that doesn't work, verify that the source for the spec you are trying to include has been pulled from GitHub. Do this by looking in <Project Dir>/Pods/<Name of spec you are trying to include>. If it is empty (it should not be), verify that the ~/.cocoapods/master/<spec>/<spec>.podspec has the correct git hub url in it.
6. If still doesn't work, check your Xcode build locations settings. Go to Preferences -> Locations -> Derived Data -> Advanced and set build location to "Relative to Workspace".

-----------------------

Although I do with this guidance，the error is still exist。However I clean and build many times，this problem can not resolve。

Can someone help？Thanks！！！

**Comment by cyvoit** [comment]
Same here for OS X 10.10.5 / Xcode 7.0(7A220) / iOS 9.0 SDK.
I see #3661 but it doesn't help me.
I disable bitcode, clean project and quit xcode, then

```
sudo rm -fr ~/Library/Caches/CocoaPods/;
sudo rm -fr ~/.cocoapods/repos/master/; 
rm -rf Pods/Podfile.lock ;
pod install
```
It still not works.

**Comment by neonichu** [comment]
Two things you can try:

- Make sure this is not an old build setting which got copied by manually editing the project. Hit delete on the linker flags build setting to go back to the defaults from the XCConfig CocoaPods generates
- Use <https://github.com/kylef/cocoapods-deintegrate> to reset the CP integration into your project

If the problem persists, please provide necessary information to debug it, see [our contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

**Comment by AbooJan** [comment]
Ld Build/Products/Debug-iphoneos/jianzhimao_enterprise.app/jianzhimao_enterprise normal arm64
    cd /Users/zhongbaojian/Desktop/jianzhimao_enterprise
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/zhongbaojian/Desktop/jianzhimao_enterprise/Build/Products/Debug-iphoneos -LPods/UMengAnalytics -LPods/UMengAnalytics/umsdk_IOS_analytics_idfa_v3.5.16 -LPods/UMengAnalytics/umsdk_IOS_analytics_idfa_v3.5.16/UMAnalytics_Sdk_3.5.16 -L/Users/zhongbaojian/Desktop/jianzhimao_enterprise/Pods/EaseMobSDK/EaseMobSDK/lib -L/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/JPush -L/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/ShareSDK/Extend/SinaWeiboSDK -L/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/ShareSDK/Extend/WeChatSDK -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/lib/system -L/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Pay/Alipay -L/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/VoiceConvert/opencore-amrnb -L/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/VoiceConvert/opencore-amrwb -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/Build/Products/Debug-iphoneos -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/Pods/Bugtags -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/ShareSDK/Connection -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/ShareSDK/Core -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/ShareSDK/Extend/QQConnectSDK -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/ShareSDK -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Thrid/ShareSDK/UI -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Resource -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise/jianzhimao_enterprise/Pay/Alipay -F/Users/zhongbaojian/Desktop/jianzhimao_enterprise -filelist /Users/zhongbaojian/Desktop/jianzhimao_enterprise/Build/Intermediates/jianzhimao_enterprise.build/Debug-iphoneos/jianzhimao_enterprise.build/Objects-normal/arm64/jianzhimao_enterprise.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=7.0 -dead_strip -ObjC -lAFNetworking -lAspects -lEaseMobClientSDKLite_arm64 -lEaseMobClientSDKLite_armv7 -lEaseMobClientSDKLite_armv7s -lEaseMobClientSDKLite_i386 -lEaseMobClientSDKLite_x86_64 -lFMDB -lIQKeyboardManager -lMBProgressHUD -lMJExtension -lMJRefresh -lMasonry -lMobClickLibrary -lRegexKitLite -lSDWebImage -liconv -licucore -lresolv -lsqlite3 -lstdc++ -lstdc++.6 -lxml2 -lz -framework AVFoundation -framework AddressBook -framework Bugtags -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework Foundation -framework ImageIO -framework MapKit -framework MobileCoreServices -framework Security -framework SystemConfiguration -framework UIKit -ObjC -lPods-AFNetworking -lPods-FMDB -lPods-IQKeyboardManager -lPods-MBProgressHUD -lPods-MJExtension -lPods-MJRefresh -lPods-RegexKitLite -lPods-SDWebImage -licucore -lsqlite3 -framework CoreGraphics -framework ImageIO -framework MobileCoreServices -framework Security -framework SystemConfiguration -fobjc-arc -fobjc-link-runtime -stdlib=libc++ -framework JWStatistics -lssl -framework ImageIO -lstdc++.6.0.9 -lWeChatSDK -framework ShareSDKShareActionSheet -framework TencentWeiboConnection -framework MessageUI -framework ShareSDKCoreService -lresolv -lz -framework TencentOpenAPI -liconv -framework QQConnection -lWeiboSDK -framework MOBFoundation -framework ShareSDKFlatShareViewUI -lxml2 -framework QZoneConnection -lsqlite3 -lstdc++.6 -lopencore-amrwb -framework AlipaySDK -framework Security -lcrypto -framework ShareSDK -framework MobileCoreServices -lsqlite3.0 -lopencore-amrnb -framework CFNetwork -framework SystemConfiguration -framework CoreTelephony -framework AGCommon -framework WeChatConnection -licucore -lstdc++ -framework BaiduMapAPI -framework SinaWeiboConnection -lPushSDK-1.8.2 -lPods -Xlinker -dependency_info -Xlinker /Users/zhongbaojian/Desktop/jianzhimao_enterprise/Build/Intermediates/jianzhimao_enterprise.build/Debug-iphoneos/jianzhimao_enterprise.build/Objects-normal/arm64/jianzhimao_enterprise_dependency_info.dat -o /Users/zhongbaojian/Desktop/jianzhimao_enterprise/Build/Products/Debug-iphoneos/jianzhimao_enterprise.app/jianzhimao_enterprise


ld: library not found for -lPods-AFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)


I have use 'pod reintegrate'  to reset.

OSX 10.11
Xcode 7 / IOS 9.0 SDK
cocoapods 0.39.0
gem 2.0.14
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

**Comment by AbooJan** [comment]
i finally know the reason.
because in my project build setting , other linker flags has any      -l"Pods     item,when i delete all    -l"Pods     item, then clean and build,i build success.~~~~

**Comment by zenghaojim33** [comment]
@AbooJan I came across the same problem , I did the same as you did but it still not work :(

**Comment by AbooJan** [comment]
@zenghaojim33 maybe you need to use cocoapods-deintegrate to reset the workspace, and pod install again.
