### ISSUE TITLE
Sample project including test fails to link tests

### ISSUE THREAD

**Issue by jymen** [CocoaPods/CocoaPods#4295]
How to reproduce :
- Using XCODE 7.0.1 and cocoapods 0.39.0.beta.4
- Create a standard Iphone SWIFT based project 'SamplePods' with test and uitests options
- Add a watchkit target 
- define following podfile : 
```
inhibit_all_warnings!
use_frameworks!
link_with 'SamplePods', 'SamplePodsTests'

def shared_pods
pod 'XCGLogger'
pod 'Alamofire', '~> 2.0'
end

target 'SamplePods' do
platform :ios, '9.0'
shared_pods
pod 'Dropbox-iOS-Dropins-SDK', '~> 1.2'
pod 'GoogleMaps'
end

target 'SamplePodsTests' do
platform :ios, '9.0'
shared_pods
end

target 'SamplePods Watchkit Extension' do
platform :watchos, '2.0'
shared_pods
end
```
- close project
- build pods
- open workspace
- open the test directory using test navigator and select the testExample function
- run it 

you'll then get 

```
ld: warning: directory not found for option '-F/Users/jymen/Library/Developer/Xcode/DerivedData/SamplePods-cnkzwtzradfwqwgqtgqahcvvpoao/Build/Products/Debug-iphonesimulator/Pods-SamplePodsTests'
ld: framework not found Alamofire
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
![screen shot 2015-09-30 at 15 34 41](https://cloud.githubusercontent.com/assets/644653/10194433/ed213bac-6788-11e5-8788-3c1357588980.png)

**Comment by neonichu** [comment]
Sounds like a deduplication issue and will probably be addressed by #4146. You can also try to disable deduplication.

**Comment by jymen** [comment]
I confirm that setting deduplicate_targets: false in config.yaml makes the problem go away

**Comment by neonichu** [comment]
OK, then we can close this.
