### ISSUE TITLE
Xcode 7 & Swift 2.0 - The spec did not pass validation.

### ISSUE THREAD

**Issue by matiasgualino** [CocoaPods/CocoaPods#4297]
Hi, I'm getting validation errors when I run "pod spec lint [MY_PROJECT].podspec".
This happen after I downloaded Xcode 7 and refactored my code in Swift 1.2 to Swift 2.0.
Some errors:
"error: expected 'while' in 'do-while' loop"
"error: consecutive statements on a line must be separated by ';'"
Can you help me, please?
Thanks a lot!

**Comment by segiddins** [comment]
Have you `xcode-select`Ed the appropriate Xcode?

**Comment by matiasgualino** [comment]
I don't understand the answer. I installed XCode 7 beta 2 from AppleDeveloper site.

**Comment by segiddins** [comment]
Cocoapods will use your currently selected Xcode. If you've installed a new one that you want to use, you have to select it first.

**Comment by matiasgualino** [comment]
Thanks a lot! It works!
