### ISSUE TITLE
Import header file located in project is not found

### ISSUE THREAD

**Issue by linked67** [CocoaPods/CocoaPods#4300]
I have create a pod that use some values i have put in a header file(MyKeys.h). These values change for every users, that's why it's in a separate file.

The problem is that in the Pods folder, my code use:

    #import "MyKeys.h"

This file is in my project but it looks like the link between Pod and project make this header not visible.
I get a "file not found error".

Is there a way to say that Pod files must look into the project ?

**Comment by orta** [comment]
Not really, normally those keys would be set in the application and then passed in as arguments to the API. E.g. with [cocoapods-keys](https://github.com/orta/cocoapods-keys) - [like this](https://github.com/artsy/eidolon/blob/master/Kiosk/App/Networking/APIKeys.swift#L42) and then [this](https://github.com/artsy/eidolon/blob/master/Kiosk/App/Networking/ArtsyAPI.swift#L135-L142).

**Comment by segiddins** [comment]
Yeah, what @orta said. Pods can't import headers from the user's project, only other pods.

**Comment by linked67** [comment]
Thanks for the answer but it doesn't fit my needs. I use 2 different computers, i should store the keys twice.And the keys don't need to be secure.
Maybe another way, would it be possible with plist files (or anything else) in user's project ?

**Comment by orta** [comment]
They both are fine alternatives, but the point is that the actual variables live in your app, and then you move them as references into the library.

**Comment by linked67** [comment]
Ok, it works now with a plist that is in my project. For the code in pod, i just read the plist and pass them where i need. No need to import something and to don't forget something, i just trow exceptions if need.
