### ISSUE TITLE
Warnings on Xcode 7

### ISSUE THREAD

**Issue by aryaxt** [CocoaPods/CocoaPods#4301]
Today I updated the code to run swift 2.0 on Xcode7 and I'm getting about 200 warnings.
Any idea what's causing this, and how I can resolve it?

- I turned off bitcode on my project
- Updated to latest version of cocoapods
- Completely removed all pods and workspace and did a pods install

![screen shot 2015-10-01 at 10 55 09 am](https://cloud.githubusercontent.com/assets/3460069/10229089/2f079456-682b-11e5-86b8-0109b14a1b7f.png)

**Comment by segiddins** [comment]
It's a bug in xcode when using parenthesis in scheme and configuration names.

**Comment by aryaxt** [comment]
thanks will rename them and confirm

**Comment by neonichu** [comment]
Closing because of lack of response.
