### ISSUE TITLE
No email received for 'pod trunk register'

### ISSUE THREAD

**Issue by worldpay-cse-mobile-support** [CocoaPods/CocoaPods#4306]
Hi,

Recently we've been trying to register a machine with ```pod trunk register```. 

```shell
$ pod trunk register csesupport_at_worldpay_dot_com 'CSE Support' --description='build machine'
$ [!] Please verify the session by clicking the link in the verification email that has been sent to csesupport_at_worldpay_dot_com
```
But no verification email was received. 
Doing the same thing with a different email from the same domain, worked as expected.

Could you please check if there are any issues on your end with the registration of the csesupport_at_worldpay_dot_com email.

**Comment by orta** [comment]
I can't get to a computer to check for a while, normally when it's a 'same domain, different email' problem our mail provider has blacklisted the address for basically getting a mail 404.

**Comment by worldpay-cse-mobile-support** [comment]
Thanks for the reply, is there a way to whitelist the email address ?

**Comment by segiddins** [comment]
We're getting a `Bounced Address` on our end

**Comment by xfreebird** [comment]
Thanks for the information @segiddins. 

The first time we run the ```pod trunk register``` that email address wasn't accepting any emails from outside, then we fixed that.
I think that is why now you are getting ```Bounced Address```.
Is there a way to revert that ? Or we have to wait for some time for the email server to whitelist it again ?

**Comment by segiddins** [comment]
No clue, we use a third party service to send out emails.

**Comment by worldpay-cse-mobile-support** [comment]
Could please you tell the name of your third party service or how we could contact them ?

**Comment by worldpay-cse-mobile-support** [comment]
Are you using [Sendgrid](sendgrid.com) ?

I found in their support docs  [My-emails-are-being-dropped](https://support.sendgrid.com/hc/en-us/articles/200181728-My-emails-are-being-dropped-).

Is that something you could do ? 
To remove the email from the suppression list.

Thanks !

**Comment by worldpay-cse-mobile-support** [comment]
@orta @segiddins could please check if you can remove csesupport_at_worldpay_dot_com email from the "suppression list".

**Comment by orta** [comment]
I've removed it from the bounce list :+1:

**Comment by worldpay-cse-mobile-support** [comment]
Thanks ! 🚀

**Comment by miklselsoe** [comment]
I have the same problem for mikkel_at_shape_dot_dk. Could you try the same procedure?

**Comment by MoathOthman** [comment]
I found the verification email  in the spam folder

**Comment by burning-git** [comment]
I received emial，but can't use .  the error 
![image](https://cloud.githubusercontent.com/assets/8384858/14036420/a426bb90-f273-11e5-817a-74935f934988.png)

**Comment by Souro7** [comment]
Hi, @orta @segiddins 

We are facing the same issue while trying to register a session. 

Can you please remove sachin@mobstac.com from the bounce list?

Thanks.

**Comment by nimati** [comment]
Hi @orta @segiddins I'm having issues with my email as well nimat6462@yahoo.ca (nothing in inbox or spam either)

**Comment by rogermolas** [comment]
@orta @segiddins I'm having the same problem, no email received in both inbox and spam 'contact@rogermolas.com'

**Comment by razamerchantwork** [comment]
@orta @segiddins I'm having the same problem, no email received in both inbox and spam 'developer016@invisionsolutions.ca'

**Comment by crspybits** [comment]
Ditto. I added an issue too on the Google Group for Cocoapods. I've tried this across three days. No email even in spam.

**Comment by McGarveyMobile** [comment]
@orta @segiddins Could you please do the same with my email? `ryan@larky.com`

**Comment by nimati** [comment]
Hi, has anyone been able to resolve the issue?
