### ISSUE TITLE
Lint fails when using private_header_files

### ISSUE THREAD

**Issue by paulmelnikow** [CocoaPods/CocoaPods#4309]
I'm trying to add a new version of the libbson podspec. 🌈

### Description

I see this error when I run `pod spec lint`:

```
 -> libbson (1.1.11)
    - ERROR | Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR |  libbson/src/bson/bson-json.c:26:10: error: use of private header from outside its module: 'bson-iso8601-private.h'
```

I get a similar error when I lint an old version of the podspec:

```
- ERROR |  libbson/src/bson/bson.c:23:10: error: use of private header from outside its module: 'bson-private.h'
```

I can *install the updated pod* and use it in Xcode just fine. It simply will not lint.

### Steps to reproduce

1. Create this podspec:

    ```rb
    Pod::Spec.new do |s|
      s.name                 = "libbson"
      s.version              = "1.1.11"
      s.summary              = "A BSON utility library."
      s.description          = "https://github.com/mongodb/libbson#libbson"
      s.homepage             = "https://github.com/mongodb/libbson"
      s.license              = { :type => "Apache License, Version 2.0", :file => "COPYING" }
      s.author               = "MongoDB"
      s.social_media_url     = "http://twitter.com/mongodb"
      s.source               = { :git => "https://github.com/mongodb/libbson.git", :tag => "#{s.version}" }
      s.prepare_command      = './autogen.sh && ./configure'
      s.source_files         = "src/bson/*.{c,h}", "src/yajl/*.{c,h}"
      s.header_mappings_dir  = "src"
      s.private_header_files = "src/bson/*-private.h"
      s.compiler_flags       = "-DBSON_COMPILATION"
      s.requires_arc         = false
    end
    ```

2. Run `pod spec lint`

I'm running CocoaPods 0.38.2 + xcodeproj 0.28.0 + Xcode 7.0.1

### Workaround

I can work around the problem by making all the header files public. That is, by commenting out the line with `s.private_header_files`.

I'd appreciate any assistance!

**Comment by segiddins** [comment]
When you're using the pod, are you using it as a framework? Because that error would only affect using it as a framework, not as a static library.

**Comment by paulmelnikow** [comment]
No, as a static library. I created a test project, I think using `pod init` and `pod install`. Is there an easy way to test it as a framework? Hmmm…

**Comment by segiddins** [comment]
`use_frameworks!`

**Comment by segiddins** [comment]
just add `s.module_name = 'bson'`.

**Comment by paulmelnikow** [comment]
Thanks @segiddins! That's a huge help.
