### ISSUE TITLE
Project with watch extension (OS1) fail to upload when linking frameworks to extension target

### ISSUE THREAD

**Issue by NSCabezon** [CocoaPods/CocoaPods#4310]
I'm getting the error  "ITMS90206 contains disallowed file Frameworks" when uploading to iTunes connect and It fails when I link the shared pods to the watch kit extension. Here is my podfile:

```
platform :ios, '7.0'

def shared_pods
	pod 'Mantle'
end


target 'Consumos' do
	shared_pods
	pod 'Appirater'
	pod 'AFNetworking'
	pod 'CJPAdController'
	pod 'Crashlytics'
	pod 'DateTools'
	pod 'Fabric'
	pod 'Masonry'
	pod 'MBProgressHUD'
	pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :tag => 'null-string-beta-2'
	pod 'RBQFetchedResultsController'
	pod 'Reachability'
end


target 'Consumos WatchKit 1 Extension' do
	shared_pods
end
```

The part of:
```
target 'Consumos WatchKit 1 Extension' do
	shared_pods
end
```

When I do a pod install with that I can't get it to upload to iTunes.

btw I'm using: COCOAPODS: 0.39.0.beta.5

**Comment by segiddins** [comment]
I believe we already have an issue that covers this

**Comment by NSCabezon** [comment]
I saw one but with OS2, sorry if it's duplicated :(
