### ISSUE TITLE
pod deintegrate does not remove pods project reference, pods framework reference and Podfile.lock from workspace which cause problems when pod is integrated again

### ISSUE THREAD

**Issue by vikram-rao** [CocoaPods/CocoaPods#4313]
When we do `pod deintegrate`, the reference to Pods project in workspace is not removed and so is the pods framework reference under Frameworks group. Podfile.lock remains too. So this is not a complete pod deintegration. 

Now post `deintegrate`, when pod is installed again afresh via `pod install`, the copy resources and copy frameworks build phases are not added to the targets.

The workaround is to manually remove the pod project, framework and podfile.lock and then integrate cocoapod again for the build phases to show up correctly.

**Comment by neonichu** [comment]
Please report this as a bug on <https://github.com/kylef/cocoapods-deintegrate> itself.
