### ISSUE TITLE
FR: Rename integration size to download size and add integration size

### ISSUE THREAD

**Issue by beriberikix** [CocoaPods/CocoaPods#4315]
The current metric for integration size actually represents download size (discussed #3716.) I was wondering if you could separate out size into 2 metrics - actual integration size and download size. Integration size would represent the increase in final app size as submitted to the App Store while the download size refers to the size a Pod talks up on my dev machine.

While I agree both are important for the reasons mentioned in #3716, impact on final app size is the metric most folks we've spoken to care about. The two separate metrics can (and hopefully should) be weighted differently.

**Comment by segiddins** [comment]
Wrong repo -- this probably belongs either on cocoadocs, where the metrics are generated, or on metrics.cocoapods.org

**Comment by beriberikix** [comment]
Ah, good point. Moving.
