### ISSUE TITLE
Resolving dependencies, Unable to satisfy the following requirements (different one)

### ISSUE THREAD

**Issue by foffux** [CocoaPods/CocoaPods#4323]
Hello
I had to update cocoa pods to a newer release, from 0.37.2 to 0.38.2 since I have switched to xCode 7.
In my pod file I had a pods that have as a minimum requirement iOS 8 but my project wanted to support also iOS 7. I thought to handle this later on. But now, check at the beginning of an update or install is blocking on requirements while it was not before. It would be better to warn user instead of blocking it, or at least, to have a way to setup this to let me, and all others, choose among which behavior to have.
Is it a workaround for this? Is it possible to have a newer version as I told you?
Thank you very much.

**Comment by segiddins** [comment]
You can set the platform in your pod file, and that's what cocoapods will use to resolve.

**Comment by foffux** [comment]
not so easy

[!] Unable to satisfy the following requirements:

- `DRPageScrollView` required by `Podfile`

In my pod file I have imported third party pods that require iOS 8 but I want to support also iOS 7. I will handle this later fixing them. But know I cannot use my project at all, as I explained you in previous message. With 0.37.2 only a warning was shown if requirements were not satisfied, but know an error is generated.

Now is the problem clear?

**Comment by segiddins** [comment]
You can specify `platform :ios, '8.0'` if you want it to resolve for 8.0.

**Comment by foffux** [comment]
In my pod file I have imported third party pods that require iOS 8 but I want to support also iOS 7
If I specify platform :ios, '7.1' this is what I got
[!] Unable to satisfy the following requirements:

DRPageScrollView required by Podfile

And I cannot change third party pods...

You know with 0.37.2 only a warning was shown. Now error.
This is the problem

**Comment by segiddins** [comment]
I know, and you can fix it by changing the platform only in the podfile.

**Comment by foffux** [comment]
Hello
In fact that would not be the only chance 
As I told it would be sufficient that Cocoa pods when running swapped between error and warning when a requirement was not met exactly like it did in the past release 
I have always use it in that way
You changed that recently 
It is better to let user choose what to do

Inviato da iPhone

**Comment by segiddins** [comment]
I'm sorry you disagree with the choice we've made, but we're not going to revert that change.

**Comment by foffux** [comment]
what about given us the choice to configure cocoa pods?
by default, the behaviour is what you like it, but from command line or
whatever, I can set a variable to have just a warning.
what do you think?

2015-10-07 8:14 GMT+02:00 Samuel E. Giddins <notifications@github.com>:

**Comment by orta** [comment]
Sorry @foffux - every configuration and user choice means more tests, more complexity and buggier releases for CocoaPods. Things we only do for very big features like pod-target-deduplication. We maintain CocoaPods in our spare time, and we have to make hard decisions. We're not going to make this a choice to be configurable I'm afraid.
