### ISSUE TITLE
HEADER_SEARCH_PATH value of a target's xcconfig file included header paths of all pods even if a pod is not included in target

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/CocoaPods#4325]
Hi,

When an xcconfig file is generated, it's HEADER_SEARCH_PATHS value contains paths for all pods even if a pod is not included in target.

This may cause collisions if any two pods contain a header file with the same name.

I think HEADER_SEARCH_PATHS value should include only the paths of the pods that are included by that specific target.

**Comment by manuyavuz** [comment]
It seems like the xcconfig generation is performed in `generate_settings_to_import_pod_targets` method of `lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb` file.

Paths are gathered in line 124:

```
            header_search_paths = target.sandbox.public_headers.search_paths(target.platform)
```

Resulted path array contains paths for all pods defined in the Podfile regardless of whether they are included by the target or not.

We should filter in some way to include only the ones that are included by the target.

I can help with this but I couldn't find a proper way to do the filtering.

**Comment by neonichu** [comment]
This cannot be changed at the moment, because of test targets. Once #840 is implemented and we have a "header only" option for dependencies, we'll be able to change it.

**Comment by manuyavuz** [comment]
@neonichu got it.

If so, is there any workaround way to handle this until the major change is completed? I tried `:exclusive => true` but it did not work either. 

Currently I have two targets each has a different dependency, but these two dependencies have a header with the same name, and the interfaces are different. Therefore I get build errors.

**Comment by neonichu** [comment]
@manuyavuz unfortunately, I don't think so

**Comment by manuyavuz** [comment]
Bad. Seems like I have to use use_frameworks! until Podfile architecture change.

Thanks for the help!
