### ISSUE TITLE
Xcode 7 Coverage on Dev Pods

### ISSUE THREAD

**Issue by szweier** [CocoaPods/CocoaPods#4328]
I have a development pod in my workspace that is being used in multiple projects across the workspace.  I also have a project for that development pod where I place the tests for the development pod classes.  Tests run fine but coverage reporting is only shown for the files which exist specifically inside of my test project (it shows coverage reports for AppDelegate.m and main.m) but shows no data for any of the classes in the dev pod. Is there a way I can get the data for coverage to show up in this scenario?

**Comment by neonichu** [comment]
There's another issue about this #3706
