### ISSUE TITLE
Please warn when the Podfile platform version doesn't match the target's platform version

### ISSUE THREAD

**Issue by hiltonc** [CocoaPods/CocoaPods#4329]
True story: we set the Podfile platform version to '7.0', but forgot to update the target's platform version in Xcode from '6.1' to '7.0'. The resulting project built, worked, got submitted, and now crashes on thousands of iOS 6 devices. We are sad. We still <3 Cocoapods, but a warning would have been nice.

**Comment by segiddins** [comment]
This is behaving as intended -- the platform in the podfile is what's used for resolution.

**Comment by hiltonc** [comment]
I'm not saying it behaves poorly. I'm saying if you get the versions out of sync, it can cause problems. So a warning would be helpful.

**Comment by segiddins** [comment]
But then that warning would be warning about perfectly valid behavior, which I'm sure would annoy people.

**Comment by hiltonc** [comment]
When is it useful for the Podfile to assume a newer version of iOS than the app target?

**Comment by segiddins** [comment]
If the user wants to conditionally use a pod with a higher deployment target than their app as a whole

**Comment by neonichu** [comment]
I agree that we shouldn't warn about this.

@hiltonc you can add your own warning/failure, though via a post-install hook. Something like

```ruby
post_install do |installer|
  installer.aggregate_targets.each do |aggregate_target|
    project = Xcodeproj::Project.open(aggregate_target.user_project_path)

    project.targets.each do |target|
      pods_deployment_target = aggregate_target.platform.deployment_target
      user_deployment_target = target.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      
      p 'fail' if pods_deployment_target != user_deployment_target
  	end
  end
end
```

should work (untested).
