### ISSUE TITLE
Adding development pod with mismatched version generates lackluster error message

### ISSUE THREAD

**Issue by jefflovejapan** [CocoaPods/CocoaPods#4330]
I tried to add a development pod (platform iOS 8.0) to an existing podfile targeting iOS 7.0, generating this warning:

~~~
Fetching external sources
-> Fetching podspec for `my-pod` from `/Users/jeff/Pods/my-pod`

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `my-pod (from `/Users/jeff/Pods/my-pod/`)` required by `Podfile`
~~~

The reason this is failing is because of the mismatched version numbers but that isn't being surfaced, even in verbose mode. I'd be happy to take this on if someone can point me in the right direction.

**Comment by segiddins** [comment]
This should have a more informative error message in 0.39, did you try out the rc?

**Comment by jefflovejapan** [comment]
Can confirm that this is fixed in 39.rc1
