### ISSUE TITLE
lib lint fails for custom modulemap (version 0.38.2)

### ISSUE THREAD

**Issue by fscz** [CocoaPods/CocoaPods#4333]
In order to import CommonCrypto in a Swift-Pod, I am currently working on, I am using a
custom module map that resides in $MYPOD/Pod/modulemaps/CommonCrypto/module.modulemap

contents:
module CommonCrypto [system] {
    header "/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS2.0.sdk/usr/include/CommonCrypto/CommonCrypto.h"
    header "/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS2.0.sdk/usr/include/CommonCrypto/CommonRandom.h"
    export *
}

To make this modulemap available to XCode after my pod installs, I have added:
s.pod_target_xcconfig = { 'SWIFT_INCLUDE_PATHS' => '$(PROJECT_DIR)/../../Pod/modulemaps' }

to my podspec.

I can compile and run it just fine, however the linter fails on my podspec:
 -> AppUnderControl-Bridge (0.1.0)
    - ERROR | [iOS] Returned an unsuccessful exit code.
    - ERROR |  /Volumes/EXT/Dropbox/devel/ios/AppUnderControl-Bridge/Pod/Classes/TokenVerification.swift:13:8: error: no such module 'CommonCrypto'

**Comment by zihanzzz** [comment]
Is there a solution to this?
