### ISSUE TITLE
Headers are not made public if they are in subfolder ( 0.39.0.beta.5 )

### ISSUE THREAD

**Issue by knutigro** [CocoaPods/CocoaPods#4337]
Hi,

I am not sure if this should be considered an issue with `Cocoapods` or with `SlackTextViewController` so I will add this issue to both repos.

After upgrading to `0.39.0.beta.5` I got an error with pod `SlackTextViewController` (https://github.com/slackhq/SlackTextViewController/). My project claimed that the `#import "SLKTextViewController.h"`  reffered to a file that didn't exist. After some investigation I noticed that there were actually  <b>no public headerfiles</b> visible to my project in this pod.

My fix for this was to fork `SLKTextViewController` and make some changes to the folder structure. Here is the original folder structure which fails:

<img width="688" alt="skarmavbild 2015-10-07 kl 16 19 09" src="https://cloud.githubusercontent.com/assets/591532/10340388/0b6c09c0-6d10-11e5-8483-f22cac7b1fd7.png">

And here is the podspec:

<img width="492" alt="skarmavbild 2015-10-07 kl 16 19 58" src="https://cloud.githubusercontent.com/assets/591532/10340387/0b68e3ee-6d10-11e5-923f-ae23ddc7ef00.png">

What I did is that I removed these two subfolders `Additions` and `Classes` and copied all files within these two to the groundlevel of folder `Source`.

Here is my fork: https://github.com/knutigro/SlackTextViewController/tree/master-foap/Source which give me no errors in 0.39.0.beta.5.

I have too little knowledge about how cocoapods work or should work to say if this is a bug in Cocoapods or in SlackTextViewController, but to me it look like Cocopods do not make public headers from files within subfolders.

/Knut

**Comment by knutigro** [comment]
Here is the issue I created in SlackTextViewController: https://github.com/slackhq/SlackTextViewController/issues/281

**Comment by neonichu** [comment]
I can't reproduce this — headers are correctly put in the sandbox with 0.39 RC1 for me and all the examples of SlackTextViewController also work fine. Please attach an example project which exhibits the problem if you still have it.
