### ISSUE TITLE
Is It possible to use different versions of Pods in different targets ? 

### ISSUE THREAD

**Issue by manonthemoon42** [CocoaPods/CocoaPods#4339]
This is what I'm trying to do in Podfile :

    platform :ios, '7.0'

    target TargetOne, :exclusive => true do  
       pod 'AFNetworking', '2.6.0'
    end

    target TargetTwo, :exclusive => true do  
        pod 'AFNetworking', '2.5.0'
    end

Here's the output : 

    [!] Unable to satisfy the following requirements:

    - `AFNetworking (= 2.6.0)` required by `Podfile`
    - `AFNetworking (= 2.5.0)` required by `Podfile`

There is not anyway that I can have multiple targets with different versions of pods ? 
Even by setting : `:exclusive => true do`, it doesn't change anything.

**Comment by segiddins** [comment]
No, that's not supported.
