### ISSUE TITLE
‘pod lib lint’ Command support Swift 2.0 ?

### ISSUE THREAD

**Issue by boyXiong** [CocoaPods/CocoaPods#4342]
‘pod lib lint’ Command support Swift 2.0 ?

Why I compile and run is ok,However, according to the command terminal prompt information modification, Xcode7 Error reporting

pod --version
0.38.2

**Comment by segiddins** [comment]
Make sure that you've `xcode-select`Ed Xcode 7, cocoapods only uses the active Xcode.
