### ISSUE TITLE
0.39.0.rc.1 => Private Podspec issues

### ISSUE THREAD

**Issue by jpshelley** [CocoaPods/CocoaPods#4347]
*Currently using 0.39.0.rc.1.*

Running `bundle exec pod lib lint --private` works great for my private repo, as it should.

However `bundle exec pod repo push ... ...` doesn't seem to work.
[The `xyz.podspec` specification does not validate.]

~ And it seems counter-intuitive to have a `--private` option for linting but a `--no-private` option for the prod push.

Is this a bug or maybe doing something wrong?

**Comment by segiddins** [comment]
Can you share a pod spec we can use to reproduce this? The issue is too generic for us to really know what's going on.

**Comment by jpshelley** [comment]
@segiddins Both the lib repo and spec repo are private. But the lib podspec follows:
*(I used '...' to denote private urls since both repos are private)*
```
Pod::Spec.new do |s|
  s.name             = "HPlayer"
  s.version          = "0.1.0"
  s.summary          = "An ios library for ..."

  s.description      = <<-DESC
This Cocoapod provides ...
                       DESC

  s.homepage         = "https://github.com/..."
  s.license          = 'MIT'
  s.author           = { "John Shelley" => "john.shelley.p@gmail.com" }
  s.source           = { :git => "https://github.com/ ... .git", :tag => s.version.to_s }

  s.platform     = :ios, '8.0'
  s.requires_arc = true

  s.source_files = 'Pod/Classes/**/*'
  s.resource_bundles = {
    'HPlayer' => ['Pod/Assets/*.png']
  }

  s.frameworks = 'Foundation', 'AVFoundation'
end
```

**Comment by segiddins** [comment]
That won't allow us to actually reproduce. You'll need to boil things down so we can debug, otherwise we'll have to close the issue as unactionable

**Comment by jpshelley** [comment]
@segiddins well the `.podspec` is pretty basic. And both our lib repo and spec repo are private.
If there is no possible issues with having two private repos in the 0.39.0.RC then I'm not sure whats wrong.

I know in the past (reading through issues & pr's), that private repos wouldn't validate during a `pod repo push` so I'm wondering if that ever got fixed.

**Comment by jpshelley** [comment]
@segiddins Turned on `--verbose` and figured out the issue. Thanks though.
