### ISSUE TITLE
SenTestingKit framework search paths

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#435]
Automatically add the following to the xcconfig if `SenTestingKit` is detected:

```
{ 'FRAMEWORK_SEARCH_PATHS' => '"$(SDKROOT)/Developer/Library/Frameworks" "$(DEVELOPER_LIBRARY_DIR)/Frameworks"' }
```

Not sure if this is a good idea.

**Comment by balumusic2012** [comment]
how can i use SenTestingKit frame work in xcode...any one can u pls explain step by step
