### ISSUE TITLE
HEADER_SEARCH_PATHS error for all framework

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#4351]
I upgrade 0.38.2 to 0.39.0.rc.1, I found the all header files in the frameworks can not be found.

Podfile:
```
pod 'PushCenterSDK'
pod 'AliUniversalAccount'
```

I found the `HEADER_SEARCH_PATHS` in the `Pods.debug.xcconfig`:
```
HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Public/AliUniversalAccount" "${PODS_ROOT}/Headers/Public/PushCenterSDK"
```

But, I check the file system, I found the header files is not in the root folder! There are subfolders!!

```
$ tree
Header
└── Public
    ├── AliUniversalAccount
    │   └── AliUniversalAccount
    │       ├── AliUniversalAccountSdk.h -> ../../../../AliUniversalAccount/AliUniversalAccount.framework/Versions/A/Headers/AliUniversalAccountSdk.h
    │       ├── aluAlipayAsoHandler.h -> ../../../../AliUniversalAccount/AliUniversalAccount.framework/Versions/A/Headers/aluAlipayAsoHandler.h
    │       ├── aluAppInfo.h -> ../../../../AliUniversalAccount/AliUniversalAccount.framework/Versions/A/Headers/aluAppInfo.h
    └── PushCenterSDK
        └── PushCenterSDK
            ├── PushCenterDefine.h -> ../../../../PushCenterSDK/PushCenterSDK.framework/Versions/A/Headers/PushCenterDefine.h
            ├── PushCenterSubscribeConfigObject.h -> ../../../../PushCenterSDK/PushCenterSDK.framework/Versions/A/Headers/PushCenterSubscribeConfigObject.h
```

The `aluAppInfo.h` is not in the `${PODS_ROOT}/Headers/Public/AliUniversalAccount`, is `${PODS_ROOT}/Headers/Public/AliUniversalAccount/AliUniversalAccount`.

Is it a bug?

**Comment by segiddins** [comment]
No, that's all looking the way it should look.

**Comment by Whirlwind** [comment]
I found the `HEADER_SEARCH_PATH` is different with 0.38.2. When I use 0.38.2, I got:

```
HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Public/AliUniversalAccount" "${PODS_ROOT}/Headers/Public/AliUniversalAccount/AliUniversalAccount" "${PODS_ROOT}/Headers/Public/PushCenterSDK" "${PODS_ROOT}/Headers/Public/PushCenterSDK/PushCenterSDK"
```

So, the 0.39.0 will cause that can not found the header!

**Comment by neonichu** [comment]
That was an intentional change, see the changelog: <https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#0390beta1-2015-08-26>

**Comment by Whirlwind** [comment]
I known, but What should I do to fix the error?

**Comment by Whirlwind** [comment]
I often change the Framework to Sourcecode..

**Comment by numbbuaa** [comment]
I have met the same problem.Is there some configure to fix it.

**Comment by yanzhiwei147** [comment]
@numbbuaa what is the solution for fix it?

**Comment by numbbuaa** [comment]
@yanzhiwei147 Reinstall the older version, like 0.37.x.
