### ISSUE TITLE
Vendored framework with categories not loading

### ISSUE THREAD

**Issue by jgimenez** [CocoaPods/CocoaPods#4353]
It looks like in #6 it's agreed that all CocoaPods execution will lead to adding `-ObjC` to `OTHER_LDFLAGS` but with a pure Swift project in Xcode 7 it looks like this is no longer the case. Categories are unavailable.

Could you please help me through this? I need to make them available. If that helps, you can find our Podspec here: https://github.com/bugfender/BugfenderSDK-iOS 

Thanks

**Comment by segiddins** [comment]
Is the vendored framework a static framework or a dynamic framework? What version of CocoaPods are you using?

**Comment by jgimenez** [comment]
Hi @segiddins . Thanks for your answer.

I'm including a dynamic framework and using CocoaPods 0.38.2.

**Comment by segiddins** [comment]
Try with the 0.39 RC, I believe I've fixed this particular bug

**Comment by jgimenez** [comment]
It worked, thank you!

You made my day. If you happen to visit Barcelona sometime you have a beer on me!
