### ISSUE TITLE
Shallow Clone for Specs?

### ISSUE THREAD

**Issue by psophis** [CocoaPods/CocoaPods#4356]
Would it be possible to shallow clone the specs?

From my testing it saves 314Mb of disk space.

**Comment by segiddins** [comment]
By default, I believe a shallow clone is already performed for the master specs repo.

**Comment by neonichu** [comment]
Yep, in fact the whole checkout should only be ~350MB:

```bash
$ du -sh ~/.cocoapods/repos/master
364M	/Users/boris/.cocoapods/repos/master
```

I'm assuming @psophis' checkout predates the switch to shallow clones?

**Comment by orta** [comment]
Yep to all of this, unless we actively want to try and reset people with full clones, I think this is fine as is.
