### ISSUE TITLE
Unknown command installed

### ISSUE THREAD

**Issue by ShiWeiCN** [CocoaPods/CocoaPods#4357]
When I run `gem installed` I get this error

ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command installed

**Comment by segiddins** [comment]
What does this have to do with cocoapods?

**Comment by ShiWeiCN** [comment]
I find this step when I read the issue #3692

**Comment by segiddins** [comment]
That's an error in ruby gems running a ruby gems command.
