### ISSUE TITLE
v0.39.0 broken

### ISSUE THREAD

**Issue by pashaisthebest** [CocoaPods/CocoaPods#4358]
I updated to 0.39.0 and even without any other pod commands specific to a project, all my iOS Obj-c projects that are using cocoapods stopped building successfully. Says 'file not found' for some RestKit file. I tried uninstalling al pods from a poject and installing again, with no luck. I fell back to 0.38.2, everything was back to normal. I attach my podfile, maybe somehting should be changed in it. If you need any additional details - I can provide them.

``` ruby
platform :ios, '7.0'

pod 'RestKit'
pod 'Reachability'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'GoogleAnalytics'
pod 'Appirater', '=2.0.4'
pod 'VK-ios-sdk'
pod 'FBSDKLoginKit', '=4.2.0'
pod 'JDStatusBarNotification'
pod 'TTTAttributedLabel', '=1.13.4'
pod 'SIAlertView', '=1.3'
pod 'UITextView+Placeholder'
pod 'MZTimerLabel'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'MZFormSheetController'
```

**Comment by segiddins** [comment]
I'm pretty sure this is a restkit issue that there's a PR over there fixing.

**Comment by neonichu** [comment]
@segiddins I'm guessing we're talking about this PR? RestKit/RestKit#2310

**Comment by segiddins** [comment]
Yup.

**Comment by ewhite-dev** [comment]
@pashaisthebest my solution to the files not being found was to make sure search header paths were set to 'recursive' for all libraries. It is in build settings for each target
