### ISSUE TITLE
Landing page should say 'sudo gem install -n /usr/local/bin cocoapods'

### ISSUE THREAD

**Issue by zolomatok** [CocoaPods/CocoaPods#4359]
...for OS X 10.11 rather than 'sudo gem install cocoapods' because the latter doesn't work because of [System Integrity Protection](http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really). (on https://cocoapods.org/)

**Comment by neonichu** [comment]
[According to Apple](https://github.com/CocoaPods/CocoaPods/issues/3736#issuecomment-146134647) this should not be the case in the default install. Can you take a look at your `gem env` and determine if you updated RubyGems? That way I can update the radar with new information if necessary.

**Comment by zolomatok** [comment]
Sure, gem env says:
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.7
  - RUBY VERSION: 2.0.0 (2015-04-13 patchlevel 645) [universal.x86_64-darwin15]
....
  - EXECUTABLE DIRECTORY: /usr/bin

**Comment by neonichu** [comment]
Yup, that means you have updated your RubyGems installation and that leads to the changed executable directory. The OS X 10.11 defaults are:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14
  - RUBY VERSION: 2.0.0 (2015-04-13 patchlevel 645) [universal.x86_64-darwin15]
  - EXECUTABLE DIRECTORY: /usr/local/bin
```

**Comment by cnfan123** [comment]
Is there any way I can downgrade back to El Capitan default Ruby version?
