### ISSUE TITLE
`preserve_paths` not be linked when develop a pod

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#4360]
I am developing a pod named `TBHDTheme`, and it has a ruby script. The ruby script is not a resource file and it just be executed by user application in the `Build Settings`. So I config the `preserve_paths` to the ruby script path:
```
Pod::Spec.new do |s|
  s.name         = "TBHDTheme"
....
  s.preserve_paths = "Script/theme_merge.rb"
```

My application `TBHDMain` will pod it:
```Podfile
pod 'TBHDTheme',:path=>"../TBHDTheme"
```

After `pod install`, I add a run script in the `TBHDMain`'s `Build Settings`:
```
bash -l -c "${PODS_ROOT}/TBHDTheme/theme_merge.rb"
```

I found that there is not any `TBHDTheme` files in the `Pods` folder, So I can not found the ruby script in `${PODS_ROOT}/TBHDTheme/theme_merge.rb`!!

The application is a normal app, So I don't want to change the path when I just to debug the pod.

**Comment by segiddins** [comment]
Can you share an example project we can use to investigate?

**Comment by segiddins** [comment]
Closing due to lack of response.
