### ISSUE TITLE
(0.39) Development Pods without version number do no longer work

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/CocoaPods#4362]
🌈

Our iOS app is split up into ~40 separate Pods which are linked together in the `Podfile` as Development Pods. After upgrading from CocoaPods 0.38.2 to 0.39 none of these Development Pods were accepted by `pod update` or `pod install`.

### Configuration & Output

`pod install`:
```
[!] Unable to satisfy the following requirements:

`XSessionService (from `Modules/Services/Session`)` required by `Podfile`
```

`Podfile` (excerpt):
```
pod 'XSessionService', :path => 'Modules/Services/Session'
```

`Modules/Services/Session/XSessionService.podspec`:
```
Pod::Spec.new do |s|

	s.name         = 'XSessionService'
	s.platform     = :ios, '8.0'
	s.source_files = '**/*.swift'

	s.dependency 'JetPack'
	s.dependency 'XCore'
end
```

### Workaround

After some trial & error and adding `s.version = '0.0.0'` to all 40 Development Pods `pod update` was working as expected.

### Conclusion

Either omitting a version number in Development Pods should work as it did in earlier versions of CocoaPods or else there should be a helpful error message indicating a missing version number in the Podspec.

**Comment by segiddins** [comment]
There's already an open issue for validating external source pods that would cover this.

**Comment by segiddins** [comment]
This has been addressed.
