### ISSUE TITLE
"Found multiple specifications for" in 0.39.0

### ISSUE THREAD

**Issue by welkinman** [CocoaPods/CocoaPods#4363]
I use the plugin "cocoapods-repo-svn" for my private repo，then get the waring:
![qq20151012-1](https://cloud.githubusercontent.com/assets/5791830/10425247/8f4a6d76-7108-11e5-98ae-5a36777a60c5.png)

**Comment by segiddins** [comment]
Are you sure this isn't a bug with the svn plugin?

**Comment by TimeSkyBlack** [comment]
@clarkda I need your help😢，i use cocoapods-repo-svn plugin 2.0.1,and i get this

**Comment by JamieREvans** [comment]
This is a forum for issues with Cocoapods, rather than a place to find help. You may want to open up a question on http://stackoverflow.com with the tag `cocoapods`.

**Comment by TimeSkyBlack** [comment]
@JamieREvans thanks for the tip,but i think it's a issues for Cocoapods or the plugin named 'cocoapods-repo-svn'

**Comment by neonichu** [comment]
Looks like this is being tracked by clarkda/cocoapods-repo-svn#12 and is not an issue with CP itself.
