### ISSUE TITLE
ObjC #import "OtherPod.h" vs <OtherPod.h>

### ISSUE THREAD

**Issue by zdenektopic** [CocoaPods/CocoaPods#4364]
Hello,

I am trying to make a new Pod that has dependency on AFNetwowking.
I have issue with using `#import`. If I use <> it works fine with iOS App projects. But If I am trying to make another Pod that is dependent on first Pod I have to use "AFNewtorking.h".
And If I mix ObjC with Swift it breaks down completely `could not build Objective-C module 'SecondPod'`

So what is actually correct? I always thought <> is for external files and "" for internal.

**Comment by samdmarshall** [comment]
Using `< >` with an include or import statement means to search the system directories for the requested file. Using `" "` will tell the compiler to search the user's path for headers. Depending on how you have your build settings configured you could use both variants for including these headers. From what you described this sounds like correct behavior to me.
