### ISSUE TITLE
It's a problem when use version '2.5.0' to install Reactive.

### ISSUE THREAD

**Issue by WilliamZang** [CocoaPods/CocoaPods#4365]
I found it had a very interesting bug in cocoapods 0.39.0.
I created a new empty project, and used `pod init` to create "Podfile" add some lines like this:

```ruby
Analyzing dependencies
[!] Unable to satisfy the following requirements:
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'testCocoapods' do
  pod 'ReactiveCocoa', '~> 2.5.0'
end

target 'testCocoapodsTests' do

end

target 'testCocoapodsUITests' do

end

```
When I executed as command `pod install`, I got this:

```
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `ReactiveCocoa (~> 2.5.0)` required by `Podfile`
```
But If I modify my Podfile, use version '2.5' instead '2.5.0'. It works!
Output like this:

```
Creating shallow clone of spec repo `master` from `https://github.com/CocoaPods/Specs.git`
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing ReactiveCocoa (2.5)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `testCocoapods.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total
pod installed.
```

Is this  a bug in 0.39.0?

**Comment by segiddins** [comment]
I think this has to do with some comparison changes we made in Core, I think we should restore the old zero padding behavior of at all possible.

**Comment by orta** [comment]
>  I think we should restore the old zero padding behavior

Yeah, I think that makes sense :+1:

**Comment by iwasrobbed** [comment]
Thanks for switching the version padding back. Got bit by this one since latest Travis for Xcode 7.1 is using 0.39.0 and we always put a trailing zero to stop minor release updates for pods that are specified as `x.x` instead of `x.x.x`

**Comment by larryaasen** [comment]
I see this issue is waiting for validation and we are also waiting for this fix. Is there a plan to release 0.39.1 with this change in it?

**Comment by segiddins** [comment]
This will be included in the next release, but we don't have a fixed release schedule.
