### ISSUE TITLE
0.39.0 breaks pod targeting specific branch

### ISSUE THREAD

**Issue by tbaranes** [CocoaPods/CocoaPods#4366]
Since I update to the 0.39.0, I can't target directly a specific branch without creating a git release of the pod.

Podfile syntax:
```
	pod '...', :git => 'https://github.com/{...}/{...}.git', :branch => 'BranchName'
```

Output error:
```
[!] /usr/bin/git clone https://github.com/.../... /var/folders/r3/mww97ktd7rd344qq7z6lg61h0000gn/T/d20151012-22204-10tngfb --single-branch --depth 1 --branch 1.0.0

Cloning into '/var/folders/r3/mww97ktd7rd344qq7z6lg61h0000gn/T/d20151012-22204-10tngfb'...
warning: Could not find remote branch 1.0.0 to clone.
fatal: Remote branch 1.0.0 not found in upstream origin
```

By looking the error, it seems looking for the version set in the Podspec instead of the branch. 
I also try to make a fake release, and that made it works, but it's not a good solution.

**Comment by tbaranes** [comment]
Also, I didn't get the error by targeting directly `cocoapods`, `cocoapods-core`, and `xcodeproj` master.

**Comment by orta** [comment]
This seems strange, I'm using 0.39 here and this is [working fine](https://github.com/artsy/energy/blob/orta-cp/Podfile#L43). Could it be because you're referring to a branch but actually referencing a tag?

**Comment by segiddins** [comment]
Could you share an actual Podfile we can use to reproduce the issue? Thanks!

**Comment by tbaranes** [comment]
Well, it doesn't seem referring a tag, the syntax didn't change, did he?
I'm using it this way for a private core of my project, but the Podfile is more or less like this:

```
source 'https://github.com/CocoaPods/Specs.git'
workspace './Project.xcworkspace'
xcodeproj 'pathToTheProject/.xcodeproj'

inhibit_all_warnings!
plugin "cocoapods-no-dev-schemes"

# shared
def import_all_platform_pods	
	pod 'ProjectCore', :git => 'https://github.com/username/project-core.git', :branch => 'experimental'
	# Others regular pods...

end

def import_ios_osx_pods
	# Some regular pods...
end

target :ios do
	platform :ios, '7.0'
	import_all_platform_pods
	import_ios_osx_pods
	# And others pods...
end

target :osx do
	platform :osx, '10.10'
	import_all_platform_pods
	import_ios_osx_pods
	
#  And others pods...
end

#Core unit tests
target :'Core Tests', :exclusive => true do
	import_all_platform_pods
	import_ios_osx_pods
end
```

The pod that getting the error is the following one:

```
	pod 'ProjectCore', :git => 'https://github.com/username/project-core.git', :branch => 'experimental'
```

It has:
 - Any releases / tags on the github
 - The branch exists for real

Also, I was using another project targeting directly the branch, which wasn't working either since the version specify in the podspec didn't have a tag corresponding. Creating the tag of the podspec solves the issue (I did it to try that).

**Comment by segiddins** [comment]
@tbaranes that's not a Podfile I can run `pod install` on, as the referenced git repo doesn't exist.

**Comment by tbaranes** [comment]
Yeah, as I said, it's a private pod, so I can't share it...

**Comment by segiddins** [comment]
Well, I don't know how to debug the issue then, since I can't reproduce it with any of my own pods ¯\_(ツ)_/¯

**Comment by tbaranes** [comment]
I will try to reproduce it by creating a public project tomorrow.

**Comment by segiddins** [comment]
OK, let us know!

**Comment by tbaranes** [comment]
Nevermind, looks like the night + reboot of the mac solve the issue. Sorry to report this wrong issue and for the loss of time. Thanks for your help!

**Comment by orta** [comment]
No problem!
