### ISSUE TITLE
Pod install spends a lot of time on Xcodeproj::Project.open

### ISSUE THREAD

**Issue by danielribeiro** [CocoaPods/CocoaPods#4374]
🌈

Hi,

We have found that pod install spends a lot of time on Xcodeproj::Project.open. Since it is called multiple times with the same path, with a simple cache, we have managed to speed it up by 100%.

A sample of the speedup and how we achieved it is in this public fork of Braintree's sdk: https://github.com/danielribeiro/braintree_ios/commit/627f24202e2065266a76a05b5dc0f6b7b5588dfc#diff-4a25b996826623c4a3a4910f47f10c30

The profile output showing the time spend can be seen [here](http://danielribeiro.github.io/braintree_ios/ProfileForCallStackPrinter.html).

On one of our largest iOS repos, this 2x speedup amounts to a few minutes saved. I'd love to see this performance improvement be made more broadly available. Any thoughts?

**Comment by segiddins** [comment]
Thanks for investigating! I don't think the cache in Xcodeproj is the right answer, but we probably could do a better job of holding onto the projects in the installer instead of re-opening them?

**Comment by danielribeiro** [comment]
No problem :smile: 

I agree caching in Xcodeproj feels a bit out of place. Maybe caching on the call sites inside CococaPods would be better?

I've summed up the call sites [here](https://github.com/danielribeiro/braintree_ios/blob/danielrb/logging-who-calls-XcodeprojProject.open/callsiteanalysis.txt) (the raw data was generated by [this code](https://github.com/danielribeiro/braintree_ios/pull/3/files)) . The summary is:

```
This callsite was called 6 times: 
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/analyzer/target_inspector.rb:32:in `compute_results'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:659:in `block (2 levels) in inspect_targets_to_integrate'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:657:in `each'

This callsite was called 6 times: 
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer.rb:552:in `block (2 levels) in prepare_pods_project'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer.rb:551:in `map'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer.rb:551:in `block in prepare_pods_project'

This callsite was called 6 times: 
$GEMS/cocoapods-0.39.0/lib/cocoapods/target/aggregate_target.rb:82:in `user_targets'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer.rb:645:in `block in set_target_dependencies'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer.rb:644:in `each'

This callsite was called 5 times: 
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:308:in `user_project'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:271:in `native_targets'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:43:in `block in integrate!'

This callsite was called 6 times: 
$GEMS/cocoapods-0.39.0/lib/cocoapods/target/aggregate_target.rb:82:in `user_targets'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:146:in `block in warn_about_xcconfig_overrides'
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:145:in `each'

This callsite was called 6 times: 
$GEMS/cocoapods-stats-0.6.2/lib/cocoapods_stats/target_mapper.rb:15:in `block in pods_from_project'
$GEMS/cocoapods-stats-0.6.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
$GEMS/cocoapods-stats-0.6.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
```

I'm not super familiar with CocoaPods codebase, so I'm not sure where a single cache to be used among these call sites would be best placed...

**Comment by segiddins** [comment]
Honestly, best Hong would be for the installer to have a reference and inject it where needed. If you don't get around to making a PR, I'll try and look into it soon.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/issues/4380 should make it so that each user project is only ever opened once

**Comment by danielribeiro** [comment]
Sounds good @segiddins. Looking forward to having it merged!

**Comment by segiddins** [comment]
If you could verify it speeds things up for you, that'd be super helpful

**Comment by danielribeiro** [comment]
Sure! I'll try it out.

**Comment by danielribeiro** [comment]
@segiddins , it is better, but there are still a few replicated calls (validating code [here](https://github.com/danielribeiro/braintree_ios/pull/4)).

The callsites which are still parsing the same pbxproj:

```
$GEMS/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:661
$GEMS/cocoapods-stats-0.6.2/lib/cocoapods_stats/target_mapper.rb:15
```

In link form: 
https://github.com/CocoaPods/CocoaPods/blob/seg-open-project-once/lib/cocoapods/installer/analyzer.rb#L661
https://github.com/CocoaPods/cocoapods-stats/blob/0.6.2/lib/cocoapods_stats/target_mapper.rb#L15

Note that target_mapper is parsing the same pbxproj 6 times.

**Comment by orta** [comment]
We might be able to get the xcodeproj out of the plugin context

**Comment by segiddins** [comment]
Yup, stats is a separate plugin that will need to be updated to use the new attribute in the hook context, so that's totally expected.

**Comment by danielribeiro** [comment]
For now, `ENV['COCOAPODS_DISABLE_STATS'] ='true'` should be a good way around it for us.
