### ISSUE TITLE
lbs.amap Cocoapods

### ISSUE THREAD

**Issue by fuxidream** [CocoaPods/CocoaPods#4375]
I use Cocoapods to install lbs.amap ,but cocoapods tell me wrong,
Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_file_s_stat+-+%2FUsers%2Fxuxinyuan%2FDesktop%2FDemo%2FPods%2FAMapSearch%2FAMapSearchKit.framework%2FResources&type=Issues

what's the problem to me?

**Comment by orta** [comment]
We're going to need more information @fuxidream can you provide us with a reproducible Podfile?

**Comment by fuxidream** [comment]
xuxinyuandeMacBook-Pro:Demo xuxinyuan$ pod update
Update all pods

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin13.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0 (7A220)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 241c507e9b442dd33b1a215346b73cb5115472f5
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.6.0'
pod 'MJRefresh', '~> 2.4.3'
pod 'AMap2DMap', '~> 3.1.0'
pod 'AMapSearch', '~> 3.0.0'
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_file_s_stat - /Users/xuxinyuan/Desktop/Demo/Pods/AMapSearch/AMapSearchKit.framework/Resources
/Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib/ruby/2.1.0/fileutils.rb:901:in `stat'
/Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib/ruby/2.1.0/fileutils.rb:901:in `symbolic_modes_to_i'
/Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib/ruby/2.1.0/fileutils.rb:948:in `fu_mode'
/Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib/ruby/2.1.0/fileutils.rb:1022:in `block (2 levels) in chmod_R'
/Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib/ruby/2.1.0/fileutils.rb:1481:in `preorder_traverse'
/Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib/ruby/2.1.0/fileutils.rb:1020:in `block in chmod_R'
/Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib/ruby/2.1.0/fileutils.rb:1019:in `each'
/Users/xuxinyuan/.rvm/rubies/ruby-2.1.0-default/lib/ruby/2.1.0/fileutils.rb:1019:in `chmod_R'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/bin/pod:23:in `load'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/bin/pod:23:in `<main>'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/bin/ruby_executable_hooks:15:in `eval'
/Users/xuxinyuan/.rvm/gems/ruby-2.1.0-default/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_file_s_stat+-+%2FUsers%2Fxuxinyuan%2FDesktop%2FDemo%2FPods%2FAMapSearch%2FAMapSearchKit.framework%2FResources&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by orta** [comment]
it's likely they are not doing correct Semantic Versioning on their pods, try updating [to 3.0.0](https://github.com/CocoaPods/Specs/blob/master/Specs/AMapSearch/3.0.0/AMapSearch.podspec.json).

**Comment by orta** [comment]
That said, we probably shouldn't be crashing if the del does not match up with the file system, got opinions on it @segiddins  ?

**Comment by neonichu** [comment]
This is actually an issue that should be fixed in 0.39 — @fuxidream please retry with that.

**Comment by fuxidream** [comment]
@neonichu Thanks,but I don't know how to fix it,can you tell me details?

**Comment by neonichu** [comment]
@fuxidream just upgrade to the 0.39 version of CP and retry.
