### ISSUE TITLE
Installing ReactiveCocoa 2.5 with Mantle 2.0.5

### ISSUE THREAD

**Issue by TiagoVeloso** [CocoaPods/CocoaPods#4376]
I have just done a clean install of El Capitan.
I have installed CocoaPods 0.38.2.

I have `ReactiveCocoa, '2.5'` and `Mantle, '2.0.5'`in my podfile.

When I try to build i get:

    ReactiveCocoa/NSObject+RACKVOWrapper.m:49:3: Unknown type name 'rac_propertyAttributes'; did you mean 'mtl_propertyAttributes'?

Debugging, I found that my ReactiveCocoa pod is importing `#import "EXTRuntimeExtensions.h"`. And it should be importing `#import "RACEXTRuntimeExtensions.h"`

I have tried removing my `Pods` folder, my `~/.cocoapods` folder, my `Podfile.lock`. Ran `pod install` and still got the same error.

Right now I've manually changed the files on my ReactiveCocoa pod to import `RACEXTRuntimeExtensions.h` and it seems to be building just fine (for now).

Now to the witchcraft, I have a colleague right next to me that has done the exact same thing as me. Cleared `Pods` folder, `~/.cocoapods` folder and `Podfile.lock` but he is not getting the same error.

I don't know why this is happening. Perhaps someone here can shed some light on this issue?

**Comment by tomtaylor** [comment]
This issue has been reported a few times, in both ReactiveCocoa and Mantle. It looks like it depends on the search order of the headers, as to whether the correct import gets picked for each dependency - it's just luck that it works for you.

For reference:

https://github.com/Mantle/Mantle/issues/570
https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2464
http://stackoverflow.com/questions/30810452/getting-error-compiling-reactivecocoa

**Comment by segiddins** [comment]
I believe @ashfurrow is the maintainer of the podspec.

**Comment by ashfurrow** [comment]
Yes, the ReactiveCocoa team has refused my offer to officially maintain the podspec, so I have to do so on my own, which you can imagine for a project like ReactiveCocoa is a lot of work. 

I haven't installed El Capitan yet, but I'll try to reproduce the issue when I can.

As a side note, I rarely specify hard versions in my podfile. Instead of `pod 'ReactiveCocoa', '2.5'`, try `pod 'ReactiveCocoa', '~> 2.5'` and the same with Mantle.

**Comment by TiagoVeloso** [comment]
I am depending on `ReactiveCocoa` through `ARAnalitycs/DSL`. If there is a need for me to change anything let me know.

**Comment by ashfurrow** [comment]
Not sure – unfortunately I no longer have the original podspec, just [the json version](https://github.com/CocoaPods/Specs/blob/master/Specs/ReactiveCocoa/2.5/ReactiveCocoa.podspec.json). I'm working off of the 4.0 alpha and I'm on a tight deadline at work, so this won't be a high priority for me :disappointed: If anyone else can help, I'd be happy to answer questions.

**Comment by segiddins** [comment]
Why not just add a `prepare_command` to `gsub` the libextobjc imports to be namespaces?

**Comment by ashfurrow** [comment]
Sounds familiar – pretty sure we used to do that.

**Comment by TiagoVeloso** [comment]
How can I do a `prepare_command`? Sorry I don't know much about writing / maintaining podspecs.

**Comment by segiddins** [comment]
https://guides.cocoapods.org/syntax/podspec.html#prepare_command

**Comment by TiagoVeloso** [comment]
Well I've looking deeper into this. I went into my local podspec for ReactiveCocoa 2.5 and it already has such a `prepare_command` (I will copy it here for completeness)

      "prepare_command": "    find . \\( -regex '.*EXT.*\\.[mh]$' -o -regex '.*metamacros\\.[mh]$' \\) -execdir mv {} RAC{} \\;\n    find . -regex '.*\\.[hm]' -exec sed -i '' -E 's@\"(EXT.*|metamacros)\\.h\"@\"RAC\\1.h\"@' {} \\;\n    find . -regex '.*\\.[hm]' -exec sed -i '' -E 's@<ReactiveCocoa/(EXT.*)\\.h>@<ReactiveCocoa/RAC\\1.h>@' {} \\;\n",

From what I understand, it should be already working. I don't know how I can test that command "ad-hoc", nor know if it ran without errors during `pod install`

**Comment by ashfurrow** [comment]
You can create a Podfile and add ReactiveCocoa with a local path:

```rb
pod 'ReactiveCocoa', :path => '../ReactiveCocoa/'
```

**Comment by notjosh** [comment]
Not sure if this is still an issue for others, but it is for us. I've hastily hacked in a workaround that lives in the `post_install` in our Podfile:

```ruby
post_install do |rep|
	# weird stuff for Mantle vs RAC on Pods v0.39.0
	`find Pods/Mantle \\( -regex '.*EXT.*\\.[mh]$' -o -regex '.*metamacros\\.[mh]$' \\) -execdir mv {} MTL{} \\;`
    `find Pods/Mantle -regex '.*\\.[hm]' -exec sed -i '' -E 's@"(EXT.*|metamacros)\\.h"@"MTL\\1.h"@' {} \\;`
	`find Pods/Mantle -regex '.*\\.[hm]' -exec sed -i '' -E 's@<ReactiveCocoa/(EXT.*)\\.h>@<ReactiveCocoa/MTL\\1.h>@' {} \\;`

	rep.pods_project.targets.select { |target| "Mantle" == target.name }.each do |mantle|
		renameables = mantle.project.files.select do |file|
			next false if not file.path.include?('Mantle')
			case
			when file.name && file.name.start_with?('EXT')
				next true
			when file.name == 'metamacros.h'
				next true
			else
				next false
			end
		end

		renameables.each do |renameable|
			renameable.name.gsub!(/^/, 'MTL')
			renameable.path.gsub!(/\/EXT/, '/MTLEXT')
			renameable.path.gsub!(/\/metamacros/, '/MTLmetamacros')
		end
	end
end
```

**Comment by orta** [comment]
To stress this point, these pod specs are maintained _by the community_. The library authors have stated multiple times they will not keep them in sync.

I would strongly recommend that someone from the community who is actively engaged in using ReactiveCocoa take over in maintaining the [Podspec](https://github.com/ashfurrow/ReactiveCocoa/blob/ashfurrow-testing/ReactiveCocoa.podspec) from @ashfurrow. He's been maintaining it for the [thousands of apps](http://metrics.cocoapods.org/api/v1/pods/ReactiveCocoa) using it and Artsy isn't keeping [up to date](http://artsy.github.io/blog/2015/09/18/Cocoa-Architecture-Dependencies/) on ReactiveCocoa anymore so there's no incentive for us other than people keep bugging him. 

You need to have a fork of the projects, add the podspec, verify that things are working and submit a new build to trunk when a new release of the library comes out against the official library.

**Comment by mhuusko5** [comment]
I have confirmed that once pod installing, doing a find/replace of `#import <ReactiveCocoa/*.h>` with `#import "*.h"` in the file `ReactiveCocoa/UI/ReactiveCocoa.h` makes everything build/run fine, as a direct or transitive dependency. It seems like this edit of this file could easily be done in the prepare_command of @ashfurrow's existing podspec (https://github.com/ashfurrow/ReactiveCocoa/blob/ashfurrow-testing/ReactiveCocoa.podspec). 

Unfortunately I just don't know what the syntax for putting inline ruby in the prepare_command is, and I really don't know how to accomplish the edit with bash...

**Comment by orta** [comment]
No need for all the fanciness, CocoaPods can handle the umbrella heade. Appending 

```
  # re: https://github.com/CocoaPods/CocoaPods/issues/4376
  # Let CocoaPods handle generating the umbrella header
  s.prepare_command = "rm ReactiveCocoa/ReactiveCocoa.h"
``` 

To the Podspec works for me. https://github.com/orta/ReactiveCocoa/blob/orta_400_2/ReactiveCocoa.podspec

**Comment by mhuusko5** [comment]
Oh gosh, sweet. Can we.. can we push that?

P.S. (cc @ashfurrow) I'd be happy to take over/assist in maintaining the Podspec. I'm very much incentivised for the time being.

**Comment by mhuusko5** [comment]
P.S. Here would be a working one for alpha 2.. https://github.com/orta/ReactiveCocoa/blob/76ef732b5eeb6774b89854891d8fa9485d0fd97a/ReactiveCocoa.podspec

**Comment by orta** [comment]
`o.0'` - how did you manage to commit on my repo?

**Comment by mhuusko5** [comment]
I don't know. I just clicked edit on the link you posted, it said the usual "we're going to fork for you" kind of thing, but then when I made the edit it brought me to a "this is your patch", "wanna create a pull request?" page, on your repo. I got confused/ditched that page, only to find my changes persisted.

**Comment by mhuusko5** [comment]
And now this is the state of my newly created fork.. its got a patch, but also says its par with your master.. 
<img width="803" alt="screen shot 2015-10-25 at 10 57 51 a m" src="https://cloud.githubusercontent.com/assets/733409/10715251/50a9e5ca-7b07-11e5-8d56-d67ee428de04.png">

**Comment by ashfurrow** [comment]
Huh. 

Anyway, I'm happy to add you as an owner to the pod – what email address do you use? I think @neonichu discussed changing the podspec once but discounted the idea. Can't remember why...

**Comment by mhuusko5** [comment]
Thanks! mhuusko5@gmail.com

**Comment by ashfurrow** [comment]
Done 🎉

**Comment by orkenstein** [comment]
@mhuusko5, so did you push that workaround to podspec?

**Comment by mhuusko5** [comment]
NSScotland just finished.. getting to it now. Tried the method @orta suggested earlier (just removing ReactiveCocoa.h), and unfortunately it didn't work when consuming as a Swift pod, because ReactiveCocoa-Swift.h was looking for/needed it. We can re-examine in the long term, but it seems that the only solution in the short term that works for Obj-C and Swift is to do a find/replace of <ReactiveCocoa/..> to ".." on the file.

Unfortunately I'm having a hard time getting it working.. because bash.
`sed -i '' 's#<ReactiveCocoa/\(.*\.h\)>#"\1"#g' ReactiveCocoa/ReactiveCocoa.h`
above works perfectly when run from command line, but does nothing (the regex isn't matching) when inserted in prepare_command.
I'm pretty sure its all to do with what characters are being escape (it took some playing around with escape chars just to get it working in terminal.. thus is life.. or at least regex.

Any help appreciated. Once that works, I'll test/push '4.0.3-alpha-1', '4.0.0-alpha-2', and '4.0.0-alpha-3'.

**Comment by charlag** [comment]
Thanks, @mhuusko5 , it works! You saved my day!

**Comment by mhuusko5** [comment]
Glad that making the changes manually works/helps, but do very much need to get the podspec changed so everyone can benefit.

***Somebody***, prepare_command, bash, sed... know what could be going wrong?

**Comment by mhuusko5** [comment]
Nevermind,

```ruby
s.prepare_command = <<-'END'
    sed -i '' 's@<ReactiveCocoa/\(.*\)>@"\1"@g' ReactiveCocoa/ReactiveCocoa.h
END
```

did the trick. Specs have been updated/tested/pushed.

**Comment by orkenstein** [comment]
@mhuusko5, thank you! Can you help me to setup my `podfile`? I'm trying use this:
```
pod 'ReactiveCocoa', :podspec => 'https://rawgithub.com/mhuusko5/Podspecs/blob/master/ReactiveCocoa.podspec'
```

But this does not work:
```
[!] Failed to fetch podspec for `ReactiveCocoa` at `https://rawgithub.com/mhuusko5/Podspecs/blob/master/ReactiveCocoa.podspec`.
 Error: 404 Not Found
```

How should I set up my `podfile`?

**Comment by mhuusko5** [comment]
No need to point to my repo. The pod specs have been pushed to trunk. Consume as usual.

**Comment by orkenstein** [comment]
Yep, already figured out.
Thanks @mhuusko5

**Comment by neonichu** [comment]
Seems like there's nothing CP can do here.

See also Mantle/Mantle#610 for scoped usage of the libextobjc headers that could help solving such issues upstream.

**Comment by raylillywhite** [comment]
I'm still getting this error with `ReactiveCocoa (4.0.0-alpha-3)` and `Mantle (2.0.5)` (with Xcode 7.1):
> ./Pods/ReactiveCocoa/ReactiveCocoa/Objective-C/NSObject+RACKVOWrapper.m:49:3: Unknown type name 'rac_propertyAttributes'; did you mean 'mtl_propertyAttributes'?

This is working for everyone else now though?

**Comment by antrix1989** [comment]
@raylillywhite, I have the same error.
 XCode 7.1 (7B91b)
Mantle 2.0
ReactiveCocoa, 4.0.4-alpha-1.

**Comment by orkenstein** [comment]
Yep, it's happening again.

**Comment by DukeHuang** [comment]
@mhuusko5 
it's happening again 
Xcode7.1
Mantle2.0.5
ReactiveCocoa, 4.0.4-alpha-1

**Comment by mhuusko5** [comment]
Unfortunately I don't know the solution to this one. I just fixed the headers/build issue. :(

**Comment by aceontech** [comment]
Same here. No idea how to fix/work around.

**Comment by beloso** [comment]
Hi, I did forgot to follow this up.

But at the time I ended up solving this by simply removing the `gnu-sed` package that I had installed with homebrew.

I would appear that `gnu-sed` and macOS' default `sed` are not compatible.
