### ISSUE TITLE
Ensure changes to Podfile DSL don't break pod ipc backwards compatability

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#4377]
AppCode relies on this, just want to make sure that we have something to remind us of this for 1.0.0.

**Comment by orta** [comment]
Some of my ideas for the Mac app also will probably rely on the `pod ipc` bits too.

**Comment by segiddins** [comment]
The whole point of 1.0 is to break backwards compatibility once.

**Comment by orta** [comment]
then we better let them know, this is going to come as a surprise which could cause crashers for them

**Comment by segiddins** [comment]
I mean, it'll still output YAML, just the contents of that will be different. Seeing as we've never promised that output would be stable, other than the serialization format, I think we're fine.

**Comment by orta** [comment]
:+1:

**Comment by orta** [comment]
I'm leaving this open, unless you have strong opinions to remind me to email jetbrains when there's a branch they can run locally.

**Comment by segiddins** [comment]
¯\_(ツ)_/¯ I mean, that'll probably be the first 1.0 beta, or master shortly before then?

**Comment by segiddins** [comment]
@orta ping on this. anything in particular for me to do?

**Comment by orta** [comment]
No, it was for me, I'll close it and send off an email to jetbrains

**Comment by segiddins** [comment]
:rocket: awesome
