### ISSUE TITLE
 I can't update my frame.

### ISSUE THREAD

**Issue by boyXiong** [CocoaPods/CocoaPods#4378]
pod trunk info XWSwiftRefresh

XWSwiftRefresh

Versions:
0.1.2 (2015-10-11 13:37:49 UTC)
Owners:
Unclaimed unclaimed-pods@cocoapods.org
Why I can't update my code
pod trunk me

Name: boyXiong

This frame is my upload, but I can't change now, and it's not me, what should I do

**Comment by segiddins** [comment]
Since its unclaimed, you should just be able to `pod trunk push`.

**Comment by boyXiong** [comment]
I did this, but I don't allow it.

./XWSwiftRefresh.podspec 
Updating spec repo `master`
Validating podspec
 -> XWSwiftRefresh (0.1.3)

[!] You are not allowed to push new versions for this pod.

**Comment by boyXiong** [comment]
pod trunk push ./XWSwiftRefresh.podspec 
Updating spec repo `master`
Validating podspec
 -> XWSwiftRefresh (0.1.3)

[!] You are not allowed to push new versions for this pod.

**Comment by segiddins** [comment]
In that case, file a dispute at trunk.cocoapods.org requesting access to the pod.
