### ISSUE TITLE
Pods-Acknowledgements is gone

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#4379]
after update to 0.39. Bummer. What happened?

**Comment by segiddins** [comment]
What's the contents of your `Pods` directory? This bug report is really not enough to go on to investigate anyting

**Comment by pronebird** [comment]
False alarm, sorry for that. I figured out that after I moved my app into separate target, CocoaPods created a separate target for it. This happened at the same time I updated CocoaPods.
