### ISSUE TITLE
Pod install can become no-op if Manifest.lock and Podfile.lock are in sync

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#4385]
Our `pod install` process takes a while (almost 2minutes). Developers are forced daily each time they `git pull` to `pod install` which can become very annoying if no dependencies have changed.

It could become almost instant if the Manifest.lock and Podfile.lock files are in sync to skip the whole process and output a message saying everything is updated.

WDYT?

**Comment by dnkoutso** [comment]
By the way we've decided to not check in our `Pods/` folder since its too big for our repo but I am not sure this will matter here.

**Comment by jafara** [comment]
+1 our pod install time takes a while here too would be nice to skip most of the steps if they are not needed.

**Comment by segiddins** [comment]
We've concluded in another issue that this isn't possible, due to development pods, but we welcome a `pod check` plugin that would let you do `pod check || pod install` if you wish :)

**Comment by dnkoutso** [comment]
Can you explain slightly more what is it about development pods that make this a non-starter? Are they not included in the Manifest.lock?

If not that's fine It seems to me that still `pod install` can perform the `check` internally and skip if a development pod is present...

**Comment by danielribeiro** [comment]
@segiddins  Do you mean this issue? https://github.com/CocoaPods/CocoaPods/issues/4346

**Comment by segiddins** [comment]
Yes

**Comment by neonichu** [comment]
I believe the discussion in #4346 was conclusive, so we can close this.
