### ISSUE TITLE
Feature request: ability to specify multiple header search paths

### ISSUE THREAD

**Issue by jcanizales** [CocoaPods/CocoaPods#4386]
I maintain a podspec for a C library that needs both `.` and `include/` (relative to the root repo) to be on the header search paths in order to compile. The headers directory structure can't be flattened, though.

Right now I have to do [this](https://github.com/jcanizales/grpc/blob/make-testing-sane/gRPC.podspec#L531) to accomplish it:
```ruby
xcconfig = { 'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/Headers/Private/gRPC" ' +
                                      '"$(PODS_ROOT)/Headers/Private/gRPC/include"' }
```

But:
* `PODS_ROOT` is deprecated.
* The directory structure within `PODS_ROOT` is an implementation detail I'm abusing.
* This is too complex to achieve something that's conceptually simple.

Ideally it would suffice to specify something like:
```ruby
header_include_dirs = '.', 'include'
```

And that would have the same effect as th `xcconfig` above, only in a supported way.

(There is an alternative workaround we were using, that consisted on using `prepare_command` to copy everything under `include/` one directory up. But the list of headaches this produces for day-to-day development is big, in addition to it also being a hack for a simple concept.)

**Comment by segiddins** [comment]
I believe using the prepare command to get everything into a single header dir is the official answer, sorry.

**Comment by segiddins** [comment]
Alternatively, we could make a build setting that is `$(PODS_ROOT)/pod name` that is stable...

**Comment by jcanizales** [comment]
I'd be equally happy with being able to write something like:
```ruby
xcconfig = { 'HEADER_SEARCH_PATHS' => '"$(POD_HEADERS)" "$(POD_HEADERS)/include"' }
```
I only suggested an "include_dirs" property because that's how GYP and Bazel solve this use case.

But the `prepare_command` hack is really a big PITA for local development and testing: It has to modify `#include` directives all over the repo, and those changes can't be .gitignore'd, so they have to be reverted again and again. We share the repo with other 7 languages that all use the same C library, and for interop testing we compile servers in those other languages: As our `prepare_command` rewrites files all over, those servers need to be compiled _before_ `pod install`, and the effects of `pod install` reverted before we can run the test script again. It slows development a lot, and training developers to contribute to our library is full of "wat moments" due to this.

**Comment by segiddins** [comment]
I mean, in all honesty, what you currently have for the xcconfig is totally fine, we're not going to break that for a loooong time.
