### ISSUE TITLE
Pods copy resources script does not set the minimum deployment target when compiling storyboards

### ISSUE THREAD

**Issue by aleh** [CocoaPods/CocoaPods#4388]
We have a pod with storyboards where "Builds for" is set to "Project Deployment Target". Our project is targeting iOS 7.0, but when the pods resource script compiles these storyboards it calls ibtool without specifying the minimum deployment version (unlike XCode, which would use --minimum-deployment-target 7.0  switch). It looks like with XCode 6.4+ ibtool assumes iOS 8.0+ when the target deployment version is not specified, which leads to crashes when storyboards are loaded on iOS 7.0.

As a workaround we can specify a concrete version in "Builds for" field, but this might be not desirable for  reusable pods.

I am using Cocoapods 0.38.2, btw.

**Comment by segiddins** [comment]
Can you make a pull request adding this to the `ibtool` invocation in the copy resources script?

**Comment by manuyavuz** [comment]
Closing the issue regarding problem solved with #4410 and there is no validation feedback. Feel free to reopen again if solution does not work for you.
