### ISSUE TITLE
`pod outdated` does not follow the Podfile platform requirements

### ISSUE THREAD

**Issue by iGranDav** [CocoaPods/CocoaPods#4390]
Hi, 

When I run `pod outdated` on my project I got some outdated pods that are available **only** for iOS 8 and more when my `Podfile` reference `platform :ios, '7.0'`

Example:
```
$ pod outdated
Updating spec repo `master`
Analyzing dependencies
The following pod updates are available:
- GTScrollNavigationBar 0.2 -> 0.2 (latest version 0.3)
```

`GTScrollNavigationBar` became available only for iOS 8 in it's version 0.3 

I run cocoapods **v0.39.0**

**Comment by segiddins** [comment]
This is the intended output. Notice that 0.3 is only being stated as the latest version, but 0.2 is what running pod update would update to.

**Comment by iGranDav** [comment]
@segiddins Totally agree concerning `pod update` but why `pod outdated` does not behave the same way?

I mean seeing this I just updated my `Podfile` and run `pod update` to finally get an error that it is impossible to install `GTScrollNavigationBar 0.3` (without any platform mention by the way).

**Comment by iGranDav** [comment]
Why did you closed the issue?

Even if it's the current intended output I think there is an issue here and I am open to discuss about it.

**Comment by segiddins** [comment]
Because its behaving exactly as intended. It says both the highest version that would satisfy your podfiles constraints and the absolute highest version.

**Comment by iGranDav** [comment]
Ok :+1: so you have another issue because in my case each outdated pod shows the same version before and after the arrow even if it can be updated (that's why I did not understand the meaning of this at first sight).

For example:
```
- HexColors 2.2.1 -> 2.2.1 (latest version 2.3.0)
```
while `HexColors 2.3.0` is available for iOS 5 and higher. If I understand you well it should displays:
```
- HexColors 2.2.1 -> 2.3.0 (latest version 2.3.0)
```

**Comment by iGranDav** [comment]
Ok `HexColors` is a dependency in this case... so it indeed cannot be updated. Not really obvious.

Perhaps `pod outdated` should annotate dependencies. But that's a feature request.

Sorry for bothering. Would be happy to work on this :)

**Comment by segiddins** [comment]
I'd be happy to accept PRs improving outdated, it's just obviously not a huge priority :)
