### ISSUE TITLE
vendored_frameworks and swift

### ISSUE THREAD

**Issue by solomon23** [CocoaPods/CocoaPods#4392]
I have a private developer pod that uses the vendored_frameworks to reference a closed source framework.  The ObjC code is able to reference the closed source framework via #import <frameworkname/frameworkname.h> but none of the Swift code is able to access it via import frameworkname - from the 0.39 release notes I gathered this should be possible ?

**Comment by segiddins** [comment]
Do you have headers in the vendored framework? Can you share a project that reproduces the issue, since we have tests that pass for importing vendored frameworks.

**Comment by solomon23** [comment]
Ok, there does seem to be something wonky with the framework I'm using.  I confirmed that if I use a framework like Bolts.  I'm able to import it properly.  

This framework I would typically need to include in my bridging header to make it work with Swift.  So I believe it's a non-module framework? Here's an example project that uses the CrashReporter framework that doesn't seem to be useable from swift pod:

https://www.dropbox.com/s/hjkuclzh3wi02oz/VendorTest.zip?dl=0

**Comment by segiddins** [comment]
It would need to include a module map, because that's a prerequisite for importing things directly in swift.

**Comment by solomon23** [comment]
So in this case I don't have access to the framework to add a module map.  I can make it work in Swift by adding it to the bridging header in the main project.  Not sure if that's possible to do in the pods project.

**Comment by segiddins** [comment]
Nope, swift frameworks can't have bridging headers.
