### ISSUE TITLE
Extension API Checkbox not set for TV Services Extensions

### ISSUE THREAD

**Issue by jeffbowen** [CocoaPods/CocoaPods#4393]
Just as some changes were needed to get the "Allow app extension API only" checkbox to be checked for WatchKit Extensions in #3153, I believe some similar work needs to be done to do the same for [TV Services Extensions](https://developer.apple.com/library/prerelease/tvos/documentation/TVServices/Reference/TVServices_Ref/index.html). I'm currently getting the `Linking against dylib not safe for use in application extensions` warning.

Here's my `Podfile`:

    platform :tvos, '9.0'
    use_frameworks!

    target 'MyApp' do

    end

    target 'MyApp TV Services Extension' do
      pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'tvOS'
      pod 'SwiftyJSON', :git => 'https://github.com/jeffbowen/SwiftyJSON.git', :commit => 'fa3fc27c14602e43f69e8d70da4fc2f9a084a987'
    end

**Comment by neonichu** [comment]
Thanks, it appears that TV Services Extensions got their own target type, so we have to add them to the list of extension targets to automatically receive the application extensions API build setting.

**Comment by orta** [comment]
baseline support has been added in https://github.com/CocoaPods/Xcodeproj/pull/318

**Comment by segiddins** [comment]
This should be very easy to implement if anyone wants to make a PR, just adding the tv extension symbol to the list of extension types, somewhere in `installer.rb` iirc.
