### ISSUE TITLE
Can't push pod when lint shows an error in a dependency. (And that error doesn't seem correct)

### ISSUE THREAD

**Issue by ConfusedVorlon** [CocoaPods/CocoaPods#4396]
🌈
I'm trying to push 

`https://github.com/ConfusedVorlon/HSGoogleDrivePicker`

using CocoaPods 0.39.0

This pod relies on the Google Drive SDK.

Ideally, I'd give the user instructions on where to get the sdk manually, or give them the option of using the existing (but suboptimal) 

`pod 'Google-API-Client', '~> 1.0'`

However, If I don't include the google API, then my pod won't lint (It doesn’t build without the relevant files from the Google SDK being present).

If I do include the google pod as a dependency (it currently _is_ included), then lint still fails me. This time it fails because of (presumably spurious) errors on the Google-API-Client pod 

`error: duplicate interface definition for class 'GTMHTTPUploadFetcher'`

I know the Google-API-Client pod compiles and runs in practice for me which is why I'm assuming the error is spurious.

I seem to be stuck between a rock and a hard place. I think I have a useful Pod that works, and that I'd like to push, but I can't submit it. 

It seems like there should be an option something like

pod trunk push --ignore-errors-on-dependencies

any suggestions?

**Comment by orta** [comment]
This could be because you're using `#import "thing"` for google libraries, which when compiled as a framework can have different semantics I think. 

You could try using `--use-libraries` on your command to not have the framework part tested, but this might mean people using swift can't use your library.

**Comment by neonichu** [comment]
Linting Google-API-Client shows the same error, so it is really something for them to fix. Possibly it is either incompatible with frameworks or newer versions of Xcode.

In any case, an option to ignore errors should definitely **not** exist, there's no use in having Pods on trunk that are known not to work in practice.

**Comment by ConfusedVorlon** [comment]
@neonichu linting the google-api-client does fail. But using the pod and actually compiling a project using it does not fail. 

Doesn't this mean there is an error with the linting?

**Comment by ConfusedVorlon** [comment]
@orta I'm not quite sure what you mean here. 

An example is that my code has 

#import "GTLDrive.h"

@orta I'm not quite sure what you mean here. 

An example is that my code has 

`#import "GTLDrive.h"`

[HSDriveManager.h](https://github.com/ConfusedVorlon/HSGoogleDrivePicker/blob/master/HSGoogleDrivePicker/HSGoogleDrivePicker/HSDriveManager.h)

GTLDrive is used within my class, so I think the import really is required. 

Can you expand on your --use-libraries suggestion? I can't find docs on that.

**Comment by ConfusedVorlon** [comment]
@neonichu digging a little further - this is the 'duplicate definition'
it is at GTLService.m:86

It is within the Google API (and it really does work)

`// If the upload fetcher class is available, it can be used for chunked uploads
//
// We locally declare some methods of the upload fetcher so we
// do not need to import the header, as some projects may not have it available
@interface GTLUploadFetcherClass : GTMBridgeFetcher

#if GTL_USE_SESSION_FETCHER
+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
                          uploadMIMEType:(NSString *)uploadMIMEType
                               chunkSize:(int64_t)chunkSize
                          fetcherService:(GTMSessionFetcherService *)fetcherServiceOrNil;

+ (instancetype)uploadFetcherWithLocation:(NSURL *)uploadLocationURL
                           uploadMIMEType:(NSString *)uploadMIMEType
                                chunkSize:(int64_t)chunkSize
                           fetcherService:(GTMSessionFetcherService *)fetcherServiceOrNil;

@property(strong) NSURL *uploadLocationURL;
@property(strong) NSData *uploadData;
@property(strong) NSURL *uploadFileURL;
@property(strong) NSFileHandle *uploadFileHandle;
#else
+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
                              uploadData:(NSData *)data
                          uploadMIMEType:(NSString *)uploadMIMEType
                               chunkSize:(NSUInteger)chunkSize
                          fetcherService:(GTMBridgeFetcherService *)fetcherService;
+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
                        uploadFileHandle:(NSFileHandle *)uploadFileHandle
                          uploadMIMEType:(NSString *)uploadMIMEType
                               chunkSize:(NSUInteger)chunkSize
                          fetcherService:(GTMBridgeFetcherService *)fetcherService;
// Use the old fetcher.
+ (instancetype)uploadFetcherWithLocation:(NSURL *)location
                         uploadFileHandle:(NSFileHandle *)fileHandle
                           uploadMIMEType:(NSString *)uploadMIMEType
                                chunkSize:(NSUInteger)chunkSize
                           fetcherService:(GTMBridgeFetcherService *)fetcherService;
#endif  // GTL_USE_SESSION_FETCHER

- (void)pauseFetching;
- (void)resumeFetching;
- (BOOL)isPaused;
@end`

This does generate a lint error. It does not generate a 'real world' error.
I can ask google to rewrite their API to make lint happy - but I really don't think they will.

**Comment by neonichu** [comment]
@ConfusedVorlon well, lint is just using `xcodebuild` — so I'm assuming the Pod will break when integrating with `use_frameworks!` in practice as well.
