### ISSUE TITLE
what's wrong with importing my dependencies in 0.39.0

### ISSUE THREAD

**Issue by coolgo** [CocoaPods/CocoaPods#4397]
when i use cocoapods in 0.38.2 my import dependencies is ok,
but it's fail when i update the cocoapods to the 0.39.0
my fail like this
![image](https://cloud.githubusercontent.com/assets/1518963/10512648/90e185e8-7374-11e5-9268-6e58a7cb6261.png)

**Comment by orta** [comment]
You should be using `#import <MagicalRecord/MagicalRecord.h>` - http://stackoverflow.com/questions/8424188/what-is-the-difference-between-import-xxx-and-import-xxx

**Comment by coolgo** [comment]
thank you for your answer . in this way i need change all my import with cocoapods.
