### ISSUE TITLE
When running `pod install`, the 'Sending stats' message appears twice

### ISSUE THREAD

**Issue by thomasaw** [CocoaPods/CocoaPods#4398]
With CocoaPods 0.39.0, the 'Sending stats' message appears twice in the console output when you run `pod install`.

**Comment by segiddins** [comment]
Hm, the integration specs don't bear that out. Do you have anything weird going on with your ruby gems setup?

**Comment by thomasaw** [comment]
I recently installed El Capitan, after which the `pod` command was no longer available, so I reinstalled the gem. However, when I run `gem list cocoapods` I get `cocoapods (0.39.0, 0.38.2, 0.35.0)`. So older versions of CocoaPods are still around, but that shouldn't be a problem.

**Comment by segiddins** [comment]
Can you share the output of `pod install --verbose`?

**Comment by thomasaw** [comment]
I noticed that among the old gems there were two versions of cocoapods-stats, like this: `cocoapods-stats (0.6.2, 0.5.3)`. After removing the old version the duplicate `Sending stats` output disappears. Still seems like a bug, but perhaps a bit obscure.

**Comment by segiddins** [comment]
Ok, feel free to comment again if you see this.

**Comment by thomasaw** [comment]
OK, I have another system on which this problem occurs. The 'Sending stats' section of the `pod install --verbose` output looks like this:

````
Sending stats
      - <list of pods removed>
    - cocoapods-stats from `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb`

Sending stats
      - <list of pods removed>
  Pod installation complete! There are 20 dependencies from the Podfile and 22 total pods installed.
````

**Comment by segiddins** [comment]
What's the output of `gem list cocoapods-stats` ? This might be due to one of the old versions of stats not including the gem spec, but I'm not entirely sure.

**Comment by thomasaw** [comment]
`cocoapods-stats (0.6.2, 0.5.3)`

**Comment by segiddins** [comment]
Yeah, I'll just chalk this up to the old versions of stats being broken. Thanks for digging in, though!

**Comment by guillaume-algis** [comment]
Reproduced this problem consistently with old `cocoapods 0.38.2` and `cocoapods-stats 0.5.3` lying around. Running `gem cleanup` solved it. Thanks!
