### ISSUE TITLE
Pod install doesn't add copy resources or check manifest.lock build phase

### ISSUE THREAD

**Issue by tuzonghua** [CocoaPods/CocoaPods#4401]
Running 0.39.0 and using the `use_frameworks!` option. Had an issue with a pod, so I ran `pod deintegrate` followed by `pod install`. As the deintegrate script removes all CocoaPods-related build phases from the project file, I assumed the install process would add them back in. However, it only added the `Embed Pods Frameworks` phase back in and not `Check Pods Manifest.lock` or `Copy Pods Resources`. I believe this is causing an issue with one of the other pods I'm using ([FontAwesome+iOS](https://cocoapods.org/pods/FontAwesome+iOS)) since the resources from that pod (namely, a *.ttf file) aren't being included in the build.

Is this a bug or is there a different approach I should be using for pods that use the `resources` attribute in their podspec?

**Comment by tuzonghua** [comment]
Happy to post this on the cocoapods-deintegrate project itself if it's a bug with that process and not CocoaPods.

**Comment by segiddins** [comment]
Hm, interesting. Can you share the project in the post-deintegration but pre-install state so we can investigate? Thanks!

**Comment by tuzonghua** [comment]
@segiddins Unfortunately, it's a closed source project. I've created a test project [here](https://github.com/tuzonghua/cocoapods_test) with separate commits for deintegrating, then reintegrating Cocoapods, but it looks like that worked. Closing for now unless I can reproduce.
