### ISSUE TITLE
public_header_files ignored for framework

### ISSUE THREAD

**Issue by aleph7** [CocoaPods/CocoaPods#4402]
I am trying to create a podspec for my swift framework that depends on a C library. I include the C library in source form. When I create the podspec I specify which headers are public but I get `error: include of non-modular header inside framework module` because the header files are not marked as public in the generated Pod project. 

<img width="337" alt="screen shot 2015-10-16 at 1 16 41 pm" src="https://cloud.githubusercontent.com/assets/167236/10552342/2b3a3f8e-7408-11e5-80ac-b5b71e899985.png">
 
I have to manually move the public headers to the public section and then it works.

Podspec: https://github.com/aleph7/HDF5Kit/blob/master/HDF5Kit.podspec

**Comment by segiddins** [comment]
What version of CocoaPods are you using? We've fixed that recently.

**Comment by aleph7** [comment]
Fixed in `0.39.0`. Thanks!
