### ISSUE TITLE
pod update occur an error

### ISSUE THREAD

**Issue by greenmjy** [CocoaPods/CocoaPods#4405]
Errno::ENOENT - No such file or directory - /Users/apple/Downloads/runners-master/Runner/Pods/AMapSearch/AMapSearchKit.framework/Resources

**Comment by orta** [comment]
Hey @greenmjy - can yu please read the [contributing guide](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) and provide us with some more information. You're a programmer, give us a bug report you'd like to receive.

**Comment by neonichu** [comment]
Closing because of lack of response.
