### ISSUE TITLE
Lint gives false-positive error on the Google API - so related pods can't be pushed.

### ISSUE THREAD

**Issue by ConfusedVorlon** [CocoaPods/CocoaPods#4406]
🌈

linting 

`pod 'Google-API-Client', '~> 1.0'`

gives the error

`error: duplicate interface definition for class 'GTMHTTPUploadFetcher'`

However this error is seems to be a false positive. 

The code seems to be correct, and doesn’t generate warnings or errors when used in a real project.

(The code triggering the error is listed below.)

This means that any pod which depends on the Google API can’t be pushed.

I understand that lint is trying to keep pods that don’t work from the list, but just want to emphasise that the google api *does work* in a real project without compilation errors.

In the real project, as far as I can tell, they’re using defines to detect whether the relevant class is already defined, and are substituting the classname for a non-conflicting one.

We can ask Google to write their code differently, but they have good reason for including the duplicate definition which is triggering the error (and it doesn’t seem reasonable to ask them to change in order to fix an error which doesn’t occur in a real build)

Similarly - my pod (which depends on the google api) does work in a real project.

`https://github.com/ConfusedVorlon/HSGoogleDrivePicker`

I have no idea how to fix the lint false-positive, and suspect it is non-trivial.

In the meantime, I would appreciate it if there was some method to allow me to publish my pod (perhaps via a different process where someone manually approves it while the lint fails).

the problematic code in google’s api is here. Their comment explains why they have done this. If you actually install the pod and compile, you’ll see that the relevant classnames become defines.

```
`// If the upload fetcher class is available, it can be used for chunked uploads
//
// We locally declare some methods of the upload fetcher so we
// do not need to import the header, as some projects may not have it available
@interface GTLUploadFetcherClass : GTMBridgeFetcher

#if GTL_USE_SESSION_FETCHER
+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
                          uploadMIMEType:(NSString *)uploadMIMEType
                               chunkSize:(int64_t)chunkSize
                          fetcherService:(GTMSessionFetcherService *)fetcherServiceOrNil;

+ (instancetype)uploadFetcherWithLocation:(NSURL *)uploadLocationURL
                           uploadMIMEType:(NSString *)uploadMIMEType
                                chunkSize:(int64_t)chunkSize
                           fetcherService:(GTMSessionFetcherService *)fetcherServiceOrNil;

@property(strong) NSURL *uploadLocationURL;
@property(strong) NSData *uploadData;
@property(strong) NSURL *uploadFileURL;
@property(strong) NSFileHandle *uploadFileHandle;
#else
+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
                              uploadData:(NSData *)data
                          uploadMIMEType:(NSString *)uploadMIMEType
                               chunkSize:(NSUInteger)chunkSize
                          fetcherService:(GTMBridgeFetcherService *)fetcherService;
+ (instancetype)uploadFetcherWithRequest:(NSURLRequest *)request
                        uploadFileHandle:(NSFileHandle *)uploadFileHandle
                          uploadMIMEType:(NSString *)uploadMIMEType
                               chunkSize:(NSUInteger)chunkSize
                          fetcherService:(GTMBridgeFetcherService *)fetcherService;
// Use the old fetcher.
+ (instancetype)uploadFetcherWithLocation:(NSURL *)location
                         uploadFileHandle:(NSFileHandle *)fileHandle
                           uploadMIMEType:(NSString *)uploadMIMEType
                                chunkSize:(NSUInteger)chunkSize
                           fetcherService:(GTMBridgeFetcherService *)fetcherService;
#endif  // GTL_USE_SESSION_FETCHER

- (void)pauseFetching;
- (void)resumeFetching;
- (BOOL)isPaused;
@end`
```

**Comment by neonichu** [comment]
Please do not open duplicates, the answer why you seem to think it is a false positive has been explained in [this comment](https://github.com/CocoaPods/CocoaPods/issues/4396#issuecomment-148378921) already. Linting is done with integration as a framework, while "Google-API-Client" appears to only work as a static library. You can lint as a static library using the `—use-libraries` option.
