### ISSUE TITLE
Development mode and new source file

### ISSUE THREAD

**Issue by ThomasCassany** [CocoaPods/CocoaPods#4411]
Hi,

When you are in your demo project and want to use/test a new file, you have to run `pod install` or `pod update` to avoid compilation error because it regenerates the "Headers" aliases in the pod folder. That's annoying and takes time. Should it be possible you change it when we are in pod development mode ?

Thanks,
Thomas

**Comment by segiddins** [comment]
There's no way around that, sorry!
