### ISSUE TITLE
Pod dependencies don't comply to the `inhibit_warnings` flag

### ISSUE THREAD

**Issue by ldiqual** [CocoaPods/CocoaPods#4414]
`Analytics/Mixpanel` installs the `Mixpanel 2.8.2` dependency, which ignores the `inhibit_warnings` flag.

For instance:

```
pod 'Analytics/Mixpanel', '2.0.12', :inhibit_warnings => true
```

gives this during compilation:

![](https://www.dropbox.com/s/6x7stuz0o13tnrd/Screenshot%202015-10-19%2019.19.33.png?raw=1)

Cocoapods 0.39.0

**Comment by segiddins** [comment]
This is the intended behavior.

**Comment by ldiqual** [comment]
@segiddins Would you mind elaborating a bit on this? How do I silence those warnings then? My guess is that I'd have to add Mixpanel as an explicit dependency and silence warnings there, but that seems a bit cumbersome.

**Comment by neonichu** [comment]
Yah, you can either add it as an explicit dependency or use `inhibit_all_warnings!` to silence warnings from all dependencies.
