### ISSUE TITLE
Specify private podspec repo branch in podfile

### ISSUE THREAD

**Issue by rgallagherzonoff** [CocoaPods/CocoaPods#4415]
podfile has this line:
source 'git@url:ios/ios-podspecrepo.git'

How do I specify a certain branch within that repo?
ex: source 'git@url:ios/ios-podspecrepo.git', :branch => 'otherbranch'

Use case:
iOS app with several private pod projects being imported via cocoapods. Working in master branch, everything is fine. Once we branch for a release, we need to branch each project. In order to not run into versioning conflicts between branches, we also need to branch our private podspec repo. 
Is there a different way Cocoapods recommends we handle branching strategies? Or can I specify a branch in my podfile source?

**Comment by segiddins** [comment]
Not possible -- source repos are flat file stores and don't support forking. You'd need to differentiate between the different versions of your pods.
