### ISSUE TITLE
Why does Pods add ALL HEADER_SEARCH_PATHS for ALL pods?

### ISSUE THREAD

**Issue by jafara** [CocoaPods/CocoaPods#4416]
We have about 30 pods in our project and overall things seem a bit fast. However, when I look into the generated Pods.xcodeproj targets each one of them their header search paths point to all pods. This slows down our builds dramatically.

Why dont the targets include the header search paths only for the target the pod depends upon?

**Comment by segiddins** [comment]
I'm sure there's already an issue for this, but long story short, we can't fix this until some work for 1.0 gets done

**Comment by neonichu** [comment]
See #4325 for a bit more explanation.
