### ISSUE TITLE
Error after removing CocoaPods from my project

### ISSUE THREAD

**Issue by rajankambaliya** [CocoaPods/CocoaPods#4418]
I am getting this error after ununstalling CocoaPods from my project. I also uninstall cocoaPods from my mac. I followed this link to uninstall cocoaPods from my project. http://www.jmeveryday.com/how-to-remove-cocoapods-from-a-project/

PhaseScriptExecution Embed\ Pods\ Frameworks /Users/multidotsmacmini/Library/Developer/Xcode/DerivedData/Selfie_SoapBox-ajtptszzxrccwwelyqfsftsmdutq/Build/Intermediates/Selfie\ SoapBox.build/Debug-iphonesimulator/Selfie\ SoapBox.build/Script-94F4FA83D0684B3614AA7FFD.sh
    cd /Users/multidotsmacmini/Documents/Checkouts/SelfieSoapBox
    /bin/sh -c \"/Users/multidotsmacmini/Library/Developer/Xcode/DerivedData/Selfie_SoapBox-ajtptszzxrccwwelyqfsftsmdutq/Build/Intermediates/Selfie\ SoapBox.build/Debug-iphonesimulator/Selfie\ SoapBox.build/Script-94F4FA83D0684B3614AA7FFD.sh\"

/Users/multidotsmacmini/Library/Developer/Xcode/DerivedData/Selfie_SoapBox-ajtptszzxrccwwelyqfsftsmdutq/Build/Intermediates/Selfie SoapBox.build/Debug-iphonesimulator/Selfie SoapBox.build/Script-94F4FA83D0684B3614AA7FFD.sh: line 2: /Users/multidotsmacmini/Documents/Checkouts/SelfieSoapBox/Pods/Target Support Files/Pods-Selfie SoapBox/Pods-Selfie SoapBox-frameworks.sh: No such file or directory

**Comment by segiddins** [comment]
Cocoapods does not currently support native uninstallation, you'll need to use cocoapods-deintegrate, which will be provided as a default plugin in the next release.

**Comment by rajankambaliya** [comment]
Thanks for the replay.

**Comment by rajankambaliya** [comment]
How can I remove a particlar library installed using cocoapods then?

**Comment by segiddins** [comment]
Just remove that lib from your podfile and run pod install.
