### ISSUE TITLE
Multiple copies of Swift stdlib copied into application by default

### ISSUE THREAD

**Issue by kujenga** [CocoaPods/CocoaPods#4419]
I have a Swift based application that installs all Cocoapods dependencies into a framework, through which the main application can use them. Since some of the pods I am using contain Swift, Cocoapods sets `EMBEDDED_CONTENT_CONTAINS_SWIFT` to `YES` in the Pods.debug.xcconfig and Pods.release.xcconfig files for my project. This in turn causes Xcode to copy the Swift standard libraries into my framework alongside the Cocoapods frameworks, which results in my application containing two copies of the stdlib, one in the main application and one in the embedded framework, unnecessarily increasing it's size.

I have found a simple workaround by setting "Embedded Content Contains Swift Code" to `NO` manually in my build settings for my framework, which works, but results in the following warnings:

```
[!] The `MyFramework [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `MyFramework [Release]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

It seems like Cocoapods should detect if the linked target already has access to the swift stdlib and avoid setting this flag if that is the case. The following technical Q&A has a message at the bottom about just this issue.

https://developer.apple.com/library/ios/qa/qa1881/_index.html

**Comment by segiddins** [comment]
Can you share a project we can use to investigate? Thanks!

**Comment by neonichu** [comment]
@kujenga which Xcode version are you using? I was under the impression that the linked tech note no longer applies for Xcode >= 7

**Comment by samdmarshall** [comment]
I was under that impression as well. Also that tech note is not correct and doesn't reflect the true behavior of the build setting or the swift-stdlib-tool in previous versions of xcode.

**Comment by kujenga** [comment]
I'm using version 7.0.1 of Xcode. Here is an example project demonstrating the issue:

https://github.com/kujenga/DoubleSwift

In creating that demo I realized that I forgot about/overlooked one non-standard piece of the settings in my application. I manually moved the "Embed Pods Frameworks" and the "Copy Pods Resources" build phases from the main target application to the embedded framework. This might have something to do with the issue.

**Comment by segiddins** [comment]
@kujenga yeah, that's not supported and would probably be the cause of the issue

**Comment by neonichu** [comment]
Also embedding frameworks into a framework will be rejected by iTC.

**Comment by dimohamdy** [comment]
+1
