### ISSUE TITLE
Uploads to iTunes Connect fail when pods' Info.plist versions do not conform to %d.%d.%d format

### ISSUE THREAD

**Issue by blixt** [CocoaPods/CocoaPods#4421]
**Edit:** The original issue no longer happens, however versions must now be in the format `1.2.3` (so `1.2.3-rc2` is invalid, for example). See comments below for details.

This is most likely an iTunes Connect server issue that just shouldn't happen, but is there anything that can be done from the Cocoapods end until Apple resolves the issue?

Here's an example (my actual bundle version in this case is 0.3.3, but I have a pod with version 0.2.0 installed):

<img width="945" alt="screen shot 2015-10-21 at 7 24 59 pm" src="https://cloud.githubusercontent.com/assets/158591/10653719/531a94fa-7830-11e5-8513-cdf39b18d784.png">

Here's a few developer forums posts regarding the issue:

* https://forums.developer.apple.com/thread/23581
* https://forums.developer.apple.com/thread/23527

**Comment by bgerstle** [comment]
I don't think it's Xcode related, running Xcode 7 here and seeing similar issues.  In our case, iTC uploads are failing due to invalid `CFBundleShortVersionString` values in our frameworks. For example, Tweaks based on HEAD:

```
./Podfile.lock:  - Tweaks (HEAD based on 2.0.0)
./Pods/Manifest.lock:  - Tweaks (HEAD based on 2.0.0)
./Pods/Target Support Files/Tweaks/Info.plist:  <string>HEAD based on 2.0.0</string>
```

This just started failing a couple hours ago. I'm not sure why Apple is suddenly checking these, hopefully they fix the issue soon...

Also hi @blixt! :wave:

**Comment by segiddins** [comment]
What version are you running?

**Comment by blixt** [comment]
@bgerstle Hi! :)

I think it's the iTunes Connect servers entirely, and not Xcode 7.0 nor Xcode 7.1. This issue appears to have started around 10 am PDT. It is definitely a bug, and we fixed it by bumping our dependency's Info.plist `CFBundleShortVersionString` up to the same version as our app, and voila – iTunes Connect accepted the bundle.

@segiddins I think client-side versions don't matter but I'm using Xcode 7.1 with CocoaPods 0.39.0.

The reason I opened this issue is because maybe there is a way to make CocoaPods remove the plist files from the final bundle (I doubt they are used once the pods are packaged?) or some other fix. Obviously that might turn out to be a fix that's not needed for very long, but I think a lot of people are suffering from this issue today.

**Comment by segiddins** [comment]
I'm pretty sure those bundles need to have an Info.plist, but we should definitely make sure the version in there is just a version string, none of the HEAD info

**Comment by bgerstle** [comment]
Also running Xcode 7.01 & CocoaPods 0.39.0. Making the identifiers valid should help, but the dev forums make it seem as though people whose dependencies have higher version numbers than their project are also rejected. Not sure what the best approach would be there...

I haven't dug into how Apple handles dynamic frameworks, but is the idea that they don't want to download versions of frameworks embedded in an app which are already present on the device?

**Comment by segiddins** [comment]
Ah well yeah. That just sounds like a plain iTC bug to me :(

**Comment by orta** [comment]
For a quickie, I added this to my Podfile to set all the frameworks bundle IDs to my apps one;

``` ruby
post_install do |installer|
  app_plist = "Emergence/Info.plist"
  plist_buddy = "/usr/libexec/PlistBuddy"
  version = `#{plist_buddy} -c "Print CFBundleShortVersionString" #{app_plist}`.split
  puts "Updating CocoaPods' version numbers to #{version}"

  installer.pods_project.targets.each do |target|
    `#{plist_buddy} -c "Set CFBundleShortVersionString #{version}" "Pods/Target Support Files/#{target}/Info.plist"`
  end
end
```

**Comment by heiberg** [comment]
Thanks a bunch @orta !

One note: I had to change `#{version}` in the last line to `#{version[0]}` as `split` returns an array and we would otherwise output "[1.0.0]" instead of "1.0.0" to the Info.plists

**Comment by orta** [comment]
oh yeah, I don't want `split`, I want `strip` - fixed

**Comment by neonichu** [comment]
Same issue on Carthage: Carthage/Carthage#859 — this seems to be new behaviour on the iTC server side introduced in the last few weeks. We should all file radars, because this really doesn't make sense. In the meantime, use @orta's workaround :)

**Comment by neonichu** [comment]
It's not an iTC bug, BTW, or at least one that has been declared a feature, see [this comment](https://github.com/Carthage/Carthage/issues/859#issuecomment-150114125)

**Comment by blixt** [comment]
@neonichu The referenced Apple documentation in that comment regards to app and watch targets though, which has been the case for quite some time, and is checked by Xcode itself.

Framework targets in a separate project (i.e., Pods) haven't been under this rule (and Xcode 7.1 still doesn't check for it), but it seems yesterday morning the iTC servers decided to care about it. I would argue that it's still a bug because the app/watch-versions-have-to-match feature has been around for quite some time, working just swell with CocoaPods, while this issue just appeared unannounced (and it doesn't really make sense for third-party deps to match their version).

**Comment by neonichu** [comment]
@blixt like I said, I agree that this doesn't make sense, but the docs seem to confirm the behaviour, because they mention "sub frameworks". Just wanted to make sure that filed radars can contain the full picture :)

**Comment by blixt** [comment]
I suppose it's all conjecture at this point and only time will tell. :) I didn't understand "apps that have sub-frameworks" as referring to the linked frameworks themselves needing to have the same version (especially since linked frameworks like Crashlytics, ContactsUI, etc aren't changeable by the user), but that might be what they are indicating.

**Comment by raylillywhite** [comment]
As mentioned in [this comment](https://github.com/Carthage/Carthage/issues/859#issuecomment-150308037), they seem to have relaxed the new constraints a bit this morning. It's no longer requiring that the version numbers match, but it's still requiring that they're all `a period-separated list of at most three non-negative-integers`.

I'm currently using the following post_install hook to set the patch version of non-conformant pods to `999` and strip out everything else.

```ruby
# Strip alpha/beta notations from build numbers
post_install do |installer|
  plist_buddy = "/usr/libexec/PlistBuddy"

  installer.pods_project.targets.each do |target|
    plist = "Pods/Target Support Files/#{target}/Info.plist"
    version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip

    stripped_version = /^([\d\.]*)/.match(version).captures[0]

    version_parts = stripped_version.split('.').map { |s| s.to_i }

    # ignore properly formatted versions
    unless version_parts.slice(0..2).join('.') == version

      major, minor, patch = version_parts

      minor ||= 0
      patch = 999

      fixed_version = "#{major}.#{minor}.#{patch}"

      puts "Changing version of #{target} from #{version} to #{fixed_version} to make it pass iTC verification."

      `#{plist_buddy} -c "Set CFBundleShortVersionString #{fixed_version}" "#{plist}"`
    end
  end
end
```

Using this, I was able to submit.

**Comment by neonichu** [comment]
Yep, seems like the original issue doesn't apply anymore, but that we have to make sure the version numbers in framework's Info.plist are conforming to clang's `-current_version` as this seems to be the thing enforced here by iTC.

**Comment by aexmachina** [comment]
The solution in [@raylillywhite's comment](https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-150372394) works for me.

**Comment by orkenstein** [comment]
Will it be added to cocoapods code in any form?

**Comment by segiddins** [comment]
Yeah, this is already fixed on master and there might be a 0.39.1 that includes it in the near term.

**Comment by AndrewSmall** [comment]
Is the Info.plist for a Pod optional? I have 17 pods in my Podfile but only one has an Info.plist in the Pods/Target Support Files/apptentive-ios/ folder.
I tried @raylillywhite's script but application loader still gave me ERROR ITMS-90049: "This bundle is invalid. The bundle identifier contains disallowed characters. [See the section of the Application Programming Guide entitled The Application Bundle.]"

Eventually I had to delete the one Info.plist in the pod. See a discussion here.
http://stackoverflow.com/questions/33271789/various-itms-errors-when-trying-to-submit-archive-to-app-store

I don't know the purpose of having the Info.plists from the pod dependencies in the app bundle and I wonder whether Cocoapods can remove them. It seems that with the current state of iTunesConnect, I will have to manually delete Info.plists from pods.

**Comment by orta** [comment]
Him, I'm not sure if the current CocoaPods master digs inside vendors frameworks to change the `info.plist`s, it's a good question as to whether we should too.

**Comment by futuretap** [comment]
@raylillywhite's solution produced `.0.999` for a pod with `Head based on 3.7.3`. This slightly changed code produces `3.7.3` instead:

	post_install do |installer|
		plist_buddy = "/usr/libexec/PlistBuddy"
	
		installer.pods_project.targets.each do |target|
			plist = "Pods/Target Support Files/#{target}/Info.plist"
			version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip
		
			stripped_version = /([\d\.]+)/.match(version).captures[0]
		
			version_parts = stripped_version.split('.').map { |s| s.to_i }
		
			# ignore properly formatted versions
			unless version_parts.slice(0..2).join('.') == version
			
				major, minor, patch = version_parts
			
				major ||= 0
				minor ||= 0
				patch ||= 999
			
				fixed_version = "#{major}.#{minor}.#{patch}"
			
				puts "Changing version of #{target} from #{version} to #{fixed_version} to make it pass iTC verification."
			
				`#{plist_buddy} -c "Set CFBundleShortVersionString #{fixed_version}" "#{plist}"`
			end
		end
	end

**Comment by jerolimov** [comment]
Here is my post_install hack (based on the versions above, thanks!) which just fix to long versions:

```ruby
post_install do |installer|
    plist_buddy = "/usr/libexec/PlistBuddy"
    installer.pods_project.targets.each do |target|
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        original_version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip
        changed_version = original_version[/(\d+\.){1,2}(\d+)?/]
        unless original_version == changed_version
            puts "Fix version of Pod #{target}: #{original_version} => #{changed_version}"
            `#{plist_buddy} -c "Set CFBundleShortVersionString #{changed_version}" "Pods/Target Support Files/#{target}/Info.plist"`
        end
    end
end
```

**Comment by yas375** [comment]
@orta (or anyone else who know the answer) out of curiosity, why you also had to [fix this problem](https://github.com/artsy/eigen/blob/462c7ca0eea87cd420a4e693297a2850818c6e5d/Podfile#L128-L135) in artsy/eigen. But you [don't need](https://github.com/artsy/eidolon/blob/04a0c8488525be4b918e212e92a29f143e0f5838/Podfile) to fix this in artsy/eidolon.

I'm currently in the process of switching to `use_frameworks!` and got this problem. Trying to understand when the suggested `post_install` fixes are needed and when they aren't.

Thanks in advance!

**Comment by orta** [comment]
Eidolon doesn't get shipped to the store, so it doesn't need it.

**Comment by yas375** [comment]
@orta gotcha. Thanks for the clarification! :)

**Comment by pcantrell** [comment]
The workarounds on this thread all appear to run in the client project’s podspec. Is there a way for a pod provider using a prerelease version to fix this issue library-side?

It doesn’t seem to be possible to put a `post_install` hook in a podspec (which makes good security sense, but would appear to put the onus on clients).

**Comment by wraithseeker** [comment]
@futuretap's version works for me.
