### ISSUE TITLE
Error validating private spec

### ISSUE THREAD

**Issue by thecritic** [CocoaPods/CocoaPods#4422]
I have been using development pods for a good while now, but I actually want to have dependencies between my (private) pods, and as far as I know, creating private pods is the only solution for that (as you cannot specify a local pod in the .podspec file as a dependency...). 

So I followed this guide https://guides.cocoapods.org/making/private-cocoapods.html, created the specs repo and added one of my development pods. Worked like a charm. Now, here is the thing: When I try to add another dev repo, upon linting 

    pod repo push my-specs [MY_PRIVATE_REPO].podspec  --verbose --sources='git@bitbucket.org:[Bitbucket_Username]/specs.git,https://github.com/CocoaPods/Specs' --allow-warnings

it gives me the following errors: 

Summary: 

    - NOTE  | [iOS] xcodebuild:  : error: Not enough arguments provided; where is the input document to operate on?

Excerpt of --verbose validation output:

	CompileStoryboard [MY_PRIVATE_REPO]/Pod/Classes/Browser.storyboard
	    cd /var/folders/06/8yhn6qhn73ggckqptybrtbjm0000gn/T/CocoaPods/Lint/Pods
	    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/Cellar/android-sdk/android-ndk-r9d/:/usr/local/Cellar/ant/1.9.5/libexec/bin:/Users/thecritic/android-sdks/tools:/Users/thecritic/android-sdks/platform-tools:/Users/thecritic/android-sdks:/Users/thecritic/Downloads/cocos2d-x-3.6/templates:/Users/thecritic/Downloads/cocos2d-x-3.6/tools/cocos2d-console/bin:/usr/local/php5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
	    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
	    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module [MY_PRIVATE_REPO] --output-partial-info-plist /var/folders/06/8yhn6qhn73ggckqptybrtbjm0000gn/T/CocoaPods/Lint/build/Pods.build/Release-iphonesimulator/[MY_PRIVATE_REPO].build/Browser-SBPartialInfo.plist --auto-activate-custom-fonts --target-device iphone --target-device ipad --minimum-deployment-target 8.0 --output-format human-readable-text --compilation-directory /var/folders/06/8yhn6qhn73ggckqptybrtbjm0000gn/T/CocoaPods/Lint/Pods/[MY_PRIVATE_REPO]/Pod/Classes/Browser.storyboard
	/* com.apple.ibtool.errors */
	: error: Not enough arguments provided; where is the input document to operate on?

	** BUILD FAILED **

	The following build commands failed:
		CompileStoryboard [MY_PRIVATE_REPO]/Pod/Classes/Browser.storyboard

**Comment by segiddins** [comment]
We'll need an example pod that reproduced the issue

**Comment by thecritic** [comment]
@segiddins Well unfortunately the thing is, I cannot disclose much of the code from that pod.

**Comment by segiddins** [comment]
That's fine, if you can boil it down to a new pod that also demonstrates it. If not, there's really nothing that we can do.

**Comment by thecritic** [comment]
@segiddins I created a fresh pod and added a storyboard file, nothing more... here is the pod: https://bitbucket.org/melkhaiat/testpod

**Comment by segiddins** [comment]
Thanks!

**Comment by segiddins** [comment]
Ah so the issue here is that the storyboard needs to be a resource, not a source file.

**Comment by thecritic** [comment]
@segiddins First of all I want to thank you for your support! So I basically add storyboards/nib files into the Assets folder for example and specify a glob in the specfile like this:   spec.resources = ["Pod/Assets/*.storyboard"] ? How come my development pod does not explain ?

**Comment by segiddins** [comment]
No clue

**Comment by thecritic** [comment]
Okay this seems to work, thanks!

**Comment by segiddins** [comment]
🎉
