### ISSUE TITLE
inhibit_all_warnings! doesn't inhibit all warnings ;-)

### ISSUE THREAD

**Issue by sendoa** [CocoaPods/CocoaPods#4423]
I'm working on a project (Swift) with a deployment target of 9.0 and using the Alamofire pod. I get the following warning even though I have `inhibit_all_warnings!` flag enabled in my Podfile:

> Unnecessary check for 'iOSApplicationExtension'; minimum deployment target ensures guard will always be true

My current Podfile:

```
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!
inhibit_all_warnings!

target 'My Project' do
    pod 'Alamofire', '~> 3.0'
    pod 'ObjectMapper', '~> 0.19'
    pod 'SWRevealViewController', '~> 2.3'
    pod 'XCDYouTubeKit', '~> 2.3'
    pod 'JTSImageViewController', '~> 1.5'
end
```

I am using
* OS X El Capitan (10.11.0)
* Xcode Version 7.0
* Swift 2

Thank you for all the great work!

**Comment by segiddins** [comment]
I think this warning in particular will be fixed by an open PR to use the pods actual deployment target.

**Comment by cnoon** [comment]
I agree @segiddins. I just created a [sample project](https://github.com/cnoon/AvailabilityWarningRadar) to demonstrate the issue we face on Alamofire. Since we're supporting four different variations of the framework for each OS (iOS, OSX, tvOS and watchOS), we have a significant amount of availability checks to handle the different cases.

I was originally going to file a radar, but I think what Apple is doing already is the correct approach. I have many more details in the README of the sample project, but the only solution that I could come up with was to build each pod against the deployment target specified in the podspec for that Pod. That's the only way we (the Pod developers) can ensure availability warnings won't be triggered.

More details can be found in [Alamofire #871](https://github.com/Alamofire/Alamofire/issues/871).

cc @kylef for visibility

**Comment by segiddins** [comment]
@cnoon can you verify the relevant cocoapods PR fixes the issue for you?

**Comment by cnoon** [comment]
I've never setup a CocoaPods dev build before. Followed this [guide](https://guides.cocoapods.org/using/unreleased-features) and I'm stuck in weird `bundle install` issues. Maybe someone else could try this out that already has it set up?

**Comment by frogcjn** [comment]
same issue here

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

    pod 'IQKeyboardManagerSwift' , '>= 3.3.4'

**Comment by segiddins** [comment]
This should now be fixed on master.

**Comment by aaronwhite** [comment]
This doesn't appear to be 'closed' as of 0.39. The following Podfile still generates 1 warning each from the two pods included despite the inhibit flag

```
platform :ios, '9.0'
xcodeproj 'myproj'
use_frameworks!
inhibit_all_warnings!

pod 'ReactiveCocoa', '~> 4.0.0-RC1'
pod 'Alamofire',     '~> 3.0'

**Comment by adomanico** [comment]
Yes seeing this as well for the following pods:

```
pod 'Masonry'
pod 'ChimpKit'
pod 'Appirator'
```

**Comment by orta** [comment]
What are the warnings? I'm not sure it's possible for CP to cover all the warnings anymore ( I'm pretty sure we apply a llvm flag that says "no warnings" with this )

**Comment by adomanico** [comment]
"C99 forbids casting non-scalar type...." and iOS 9 deprecation warnings are the ones that I am seeing

**Comment by kurko** [comment]
As of 0.39.0, I'm getting

```
** BUILD SUCCEEDED **

 -> UDSync (0.1.0)
    - WARN  | xcodebuild:  Alamofire/Source/Request.swift:208:20: warning: unnecessary check for 'OSX'; minimum deployment target ensures guard will always be true
    - WARN  | xcodebuild:  Alamofire/Source/ParameterEncoding.swift:230:12: warning: unnecessary check for 'OSX'; minimum deployment target ensures guard will always be true
    - WARN  | xcodebuild:  Alamofire/Source/MultipartFormData.swift:259:12: warning: unnecessary check for 'OSX'; minimum deployment target ensures guard will always be true

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 3 warnings (but you can use `--allow-warnings` to ignore them).
```

**Comment by virl** [comment]
Error still persists when Swift project uses some Objective-C code: pods warnings (deprecated UIAlertView) are not inhibited for Objective-C code, because that code uses auto-generated *-Swift.h headers (which contain references to UIAlertView).

Example pod: Armchair.

**Comment by sareninden** [comment]
You can also suppress the warnings per included pod (which does work....)

pod 'Alamofire', :inhibit_warnings => true

**Comment by bj97301** [comment]
I had to clean my project to get the warnings to go away.

**Comment by bolee** [comment]
@sareninden and @RishabhTayal  not working in my Xcode 9.4.1 with Objective-C.

**Comment by bolee** [comment]
> I had to clean my project to get the warnings to go away.

use which ways?

**Comment by zackdotcomputer** [comment]
Still struggling with this one, these days with
```
pod 'AWSMobileClient', '~> 2.12.0', :inhibit_warnings => true
```
in a Swift project.

Even with the above inhibit, an `inhibit_all_warnings!` at the top of the file, and this block at the bottom:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
        end
    end
end
```
I'm still getting "Pointer is missing a nullability type specifier" warnings after running `pod install` and a local clean.

Am I missing an obvious issue with my approach here or is this just a new case not covered by the existing warning-inhibit macros?

**Comment by tylerjames** [comment]
@zackdotcomputer 
I'm getting this as well while using AWS libraries. Went from 8 to a cool 137 warnings.

Where exactly do you put `-Xcc -Wno-nullability-completeness`?

**Comment by zackdotcomputer** [comment]
@tylerjames 
1. Select my app project in the navigator
2. Select my app's target in the main window
3. Select "Build Settings" and make sure it's filtered to "All" rather than "Basic" or "Customized".
4. Search for "Swift" and find the "Other Swift Flags" setting under the "Swift Compiler - Custom Flags" section.
5. Double click and add it to the bottom of the list there.
