### ISSUE TITLE
Xcode 7.1 wants to update Pods.xcodeproj to "recommended settings"

### ISSUE THREAD

**Issue by blixt** [CocoaPods/CocoaPods#4426]
This is not a biggie, but Xcode keeps popping the warning that it wants to adopt "Product Bundle Identifier" build setting and turn on "Enable Testability" for Pods.xcodeproj:

<img width="1176" alt="screen shot 2015-10-22 at 8 54 31 am" src="https://cloud.githubusercontent.com/assets/158591/10665698/1044504c-789b-11e5-9716-f8f03f59bdcc.png">

Perhaps CocoaPods can resolve these warnings when it creates Pods.xcodeproj?

**Comment by neonichu** [comment]
Yah, some of it actually has to happen over in Xcodeproj land, but the plist changes are in CP itself, I think.

**Comment by RaviDesai** [comment]
It is a bit of a nuisance because the warning occurs every time you do a pod update (especially if you have a zero warnings policy).  It appears only to add 'org.cocoapods.<CocoaPod-Name>' as the Product Bundle Identifier when you click Perform changes.  Is there some post_install hook I can place in my Podfile as a work around?

**Comment by segiddins** [comment]
So I'm happy to make this change in the generated Info.plist, but iirc this will be a breaking change for anyone using Xcode 6.x?

**Comment by segiddins** [comment]
Never mind, this should be good! (and should be handled by https://github.com/CocoaPods/CocoaPods/issues/4451)

**Comment by priteshshah1983** [comment]
@segiddins Should `ENABLE_TESTABILITY` be set to `YES` for debug as well?

**Comment by segiddins** [comment]
@priteshshah1983 It should all be up-to-date with Xcode's own defaults on master now

**Comment by priteshshah1983** [comment]
@segiddins Thanks! I will try it out.
