### ISSUE TITLE
Copy Pods Resources is missing in my workspace - 0.39.0

### ISSUE THREAD

**Issue by mRs-** [CocoaPods/CocoaPods#4432]
Yesterday I updated to **0.39.0** und rebuild my xcworkspace file and now the **Copy Pods Resources** in the **Build Phases** is missing and the **Embed Pods Frameworks** is there instead.

But my current project isn't finding any resources now. 

As a workaround I added the the **Pods-resources.sh** by myself

**Comment by orta** [comment]
I presume you migrated to `use_frameworks!`, this is a feature of using frameworks, and is working as intended. Frameworks can host their own resources instead of having them bundled into the app. You will need to use `[[NSBundle bundleForClass:XXX] pathFor...` to get access to framework resources.

**Comment by mRs-** [comment]
`use_frameworks!` is commented out :(

**Comment by orta** [comment]
Looks like it migrated to frameworks, and now you want to go back? I'd recommend running [cocoapods-deintegrate](https://github.com/CocoaPods/cocoapods-deintegrate) and re-run `pod install`

**Comment by mRs-** [comment]
I will try it and give you feedback if it's working again. Thanks for your help @orta

**Comment by mRs-** [comment]
Works fine! Easy as pie!

**Comment by mRs-** [comment]
Found out a new thing. When I run `pod update` it's integrating the frameworks always :(
