### ISSUE TITLE
Creates empty Frameworks folder that iTC doesn't like (0.39.0)

### ISSUE THREAD

**Issue by sdarlington** [CocoaPods/CocoaPods#4434]
I have a pretty simple Podfile that looks something like this:

    platform :ios, '8.0'
    inhibit_all_warnings!

    pod 'MMWormhole'
    pod 'RMStore'
    pod 'RMStore/AppReceiptVerificator'
    pod 'RMStore/KeychainPersistence'

    target 'Save Bookmark', :exclusive => true do
        pod 'MMWormhole'
    end

Note: I'm not using frameworks because RMStore has a dependency on OpenSSL which is built as a static library and CP can't figure out how to make that as a framework (summarising something I don't fully understand... point being I can't use frameworks).

When I run `pod update` it gets all the right files and building/running the app locally works fine. However, when I upload to iTunes Connect I get the following error:

![screen shot 2015-10-22 at 12 40 04](https://cloud.githubusercontent.com/assets/416582/10690934/118a7502-797d-11e5-8eb8-8f51b3a2007c.png)

Looking inside the archive, I see that the "Embed Pods Frameworks" script has created an empty Frameworks folder. My workaround has been to remove that build stage from my app extensions. It seems that this should be harmless enough and, arguably, is a problem on Apple's side but it's a reality that we need to work with...

Is there an option I can add to my Podfile to help or does this need a code change?

**Comment by segiddins** [comment]
There are other issues open about this

**Comment by sdarlington** [comment]
I did look before I posted. Now I see #8343.
