### ISSUE TITLE
Enforcement of at most three non-negative period separated integers for version numbers of dynamic frameworks.

### ISSUE THREAD

**Issue by nlutsenko** [CocoaPods/CocoaPods#4437]
Hey guys,

Turns out Apple enforces the version constraint for dynamic frameworks that are shipped with the app.
It should always be at most three non-negative period separated integers for version numbers.

E.g.
`4.7.0` - valid
`4.7.0.1` - invalid

We've seen a breakage on `FBSDKLoginKit` pod, where the current latest version of the pod is `4.7.0.1`, which apparently breaks uploads to iTC.
External bug report: https://developers.facebook.com/bugs/828229420628334/

This impacts only dynamic frameworks generated by CocoaPods (which is default now).
Not sure about the best way to make this happen, but here are my thoughts:
- enforcing specific versioning on pod versions is probably not the best idea, since a lot of people do `0.39.0.beta.5`
- this doesn't matter for non-framework generated pods, so that piece could be left intact
- since you cannot have different versions of pods in the same target, maybe automatically trim anything after the `patch` of the version at the moment of pod generation?

cc @segiddins, @mingflifb, @chrisp-fb

**Comment by orta** [comment]
We've been sending people to this fix ATM https://github.com/CocoaPods/CocoaPods/issues/4421#issuecomment-150139578, but yeah, we will have to figure something into CocoaPods to fix this at a global scale somehow.

**Comment by segiddins** [comment]
This should be super easy to fix, just changing the version to be major minor and patch joined with a period.

**Comment by nlutsenko** [comment]
Sounds good, thanks guys. How can I help?

**Comment by segiddins** [comment]
A PR with that fix and some tests would be 👍🏻. Otherwise, I'll have to do it tomorrow

**Comment by neonichu** [comment]
Fixed by #4444
