### ISSUE TITLE
Swift framework are not debuggable in lldb (looks optimized)

### ISSUE THREAD

**Issue by friedtofu** [CocoaPods/CocoaPods#4440]
Cocoapod version 0.39.0
Xcode version 7.0

I have a swift project and have multiple swift pods. 
I use the use_framework! in my podfile to install these swift pods for my project. 
One issue I noticed is that upon debugging the code in these pods, I cannot see any value of any variables at the scope of the break point. I even tried to do po varname in lldb and it returns "use of unresolved identifier".
I look at the optimization settings for my Pod  and it says that for the debug, it uses None[-Onone] and I even attempted to apply this for every scheme but it doesn't seem to fix the issue. 

Any help?

**Comment by segiddins** [comment]
Pretty sure this is just swift being buggy. What makes you think it's caused by CocoaPods?

**Comment by reversepanda** [comment]
Added some information: I have the same problem with debugging *my own code* in a workspace created by Cocoapods.

Mind you: I'm not sure if it's Swift or Cocoapods also, I just can refer to this post regarding some Twitter frameworks - https://twittercommunity.com/t/xcode-7-debugger/50792/43 - which concluded to downgrade Cocoapods for a (temp) solution. Seems to me, they haven't isolated the cause themselves.

I don't use these Twitter frameworks, but totally different one in my project. So it's either a workspace/project configuration problem triggered by Cocoapods 39.0 (which didn't happen in a previous version) or Swift debugging is currently (very) buggy.

**Comment by friedtofu** [comment]
@segiddins It could be Swift frameworks but running a debugger on a Swift project is working fine. I'll run a test with a project with a Swift frameworks built and include it as a dependency not using cocoapod to see if I see the same issue and update this thread.

**Comment by segiddins** [comment]
Thanks! If it is indeed a CocoaPods issue, we'll need an example project to debug.

**Comment by friedtofu** [comment]
This looks like a Swift/Xcode issue. I upgraded to 7.1 and the issue is fixed.

**Comment by reversepanda** [comment]
I also have Xcode 7.1 and still have the problem.

**Comment by segiddins** [comment]
@reversepanda please open a new issue that includes a project we can use to debug?

**Comment by reversepanda** [comment]
Xcode 7.2 beta release notes: "Swift data types that are imported into Swift from C struct types (CGRect, CGPoint, etc) can now be inspected in the debugger. (23088739)" - that might be related to my problem. I can't currently update to the beta to see if that's true, but I will keep you updated as soon as I can.
