### ISSUE TITLE
vendored_frameworks not handled properly when used in two sub-project

### ISSUE THREAD

**Issue by ex3ndr** [CocoaPods/CocoaPods#4441]
1) Create iOS App
2) Create Cocoa Touch Framework
3) Make iOS App depends on Framework
4) Fill Podfile
```
platform :ios, '8.0'
use_frameworks!

workspace 'Workspace'
xcodeproj 'AppProject.xcodeproj'
xcodeproj 'FrameworkProject.xcodeproj'

inhibit_all_warnings!

link_with 'AppProject'

target 'AppProject' do
    xcodeproj 'AppProject.xcodeproj'

    # For example Crashlytics
    pod 'Crashlytics'
end

target 'FrameworkProject' do
    xcodeproj 'FrameworkProject.xcodeproj'

   pod 'Crashlytics'
end
```

Result: 
```Class Crashlytics is implemented in both Framework and App```

It seems that vendored frameworks are treated as just static libraries

**Comment by segiddins** [comment]
It's intended that all frameworks be pods -- integrating with a framework target is currently unsupported.

**Comment by ex3ndr** [comment]
Why? This is so simple. I workarounded this issue by just copying *-frameworks.sh file and setting path to my "vendored" framework

**Comment by segiddins** [comment]
If it is indeed simple, a pull request adding support along with test coverage would be much appreciated!

**Comment by neonichu** [comment]
IIRC, this can't be solved for the general case, because we cannot embed frameworks into frameworks without being rejected by iTC. So it is not possible to build a self-contained framework with dependencies.

**Comment by neonichu** [comment]
If I understand correctly, you're also assuming that symbols from a static vendored framework (Crashlytics is one) can be reexported without problems. This is also not necessarily the case.
