### ISSUE TITLE
Xcode 7.1 CocoaPods error: 'RKObjectManager.h' file not found

### ISSUE THREAD

**Issue by jwmuchow** [CocoaPods/CocoaPods#4445]
Upgraded to Xcode 7.1 and I now get the following error as it relates to RestKit and CocoaPods:

'RKObjectManager.h' file not found

I am running CocoaPods 0.39.0 and using RestKit 0.23.1 (I've also tried 0.25.0 with no success).

I've tried setting the search paths to recursive with no luck. Any ideas?

**Comment by segiddins** [comment]
Lint passes with 0.25, so I don't really know what's wrong

**Comment by neonichu** [comment]
Please add more information or preferably an example project so that we can investigate the issue.

**Comment by jwmuchow** [comment]
I think I've found the issue, it was a system config problem that for some reason did not present itself until Xcode 7.1. As part of my troubleshooting process, I found I had rvm (Ruby Version Mgr) installed. Once I removed the rvm, reinstalled CocoaPods 0.38.2 and RestKit 0.24.1, I was able to get a clean build.
