### ISSUE TITLE
Can't use '&' in Xcode project's name.

### ISSUE THREAD

**Issue by nRewik** [CocoaPods/CocoaPods#4446]
I have an Xcode project name "A&B". After, I `pod install`. It gave me this error.

```
REXML::ParseException - #<RuntimeError: Illegal character '&' in raw string "group:A&B 2015.xcodeproj">
```

and

```
Illegal character '&' in raw string "group:A&B.xcodeproj"
Line: 5
Position: 129
Last 80 unconsumed characters:
```

After I remove `&` in my project's name, pod run fine. So, I think there might be other characters that cause the same issue. 

It's not a good practice to name project with this character. But more useful information, for example, "project's name cannot contain &"—will help beginners to solve the issue.

**Comment by segiddins** [comment]
Sounds like we need to be entity escaping some XML in Xcodeproj :(

**Comment by neonichu** [comment]
Looks like the problem actually lies in the generated workspace. 

When it is created via Xcode:

```location = "group:yolo &amp; yolo.xcodeproj">```

what CP generates:

```location = "group:yolo & yolo.xcodeproj">```

**Comment by cjwirth** [comment]
Just sent a pull request that fixed the problem for me.

**Comment by k0nserv** [comment]
Related to this https://github.com/CocoaPods/CocoaPods/issues/2807 with the fix https://github.com/CocoaPods/Xcodeproj/pull/220
