### ISSUE TITLE
CocoaPods 0.39 '-umbrella.h' include every .h files

### ISSUE THREAD

**Issue by andreyslyusar** [CocoaPods/CocoaPods#4447]
I have a private pod with podspec does not included 's.public_header_files', but while generating pod '-umbrella.h' include all .h files from project. Should it be like this?

**Comment by segiddins** [comment]
Yes -- the umbrella header must include every public header

**Comment by andreyslyusar** [comment]
Sure umbrella file should include every public header, but my podspec does not specify any 's.public_header_files', it means it should be none files in umbrella file.

**Comment by segiddins** [comment]
By default, that means all headers are public
