### ISSUE TITLE
Import .framework using vendored_frameworks with Swift

### ISSUE THREAD

**Issue by AvdLee** [CocoaPods/CocoaPods#4448]
In my pod I'm trying to include the CrashReporter.framework without succes.

I'm using the following podspec:

```
Pod::Spec.new do |s|
s.name             = "TIFCrashReporter"
s.version          = "0.1.0"
s.summary          = "Description short"
s.description      = "Description long"
s.license          = { :type => "MIT", :file => "LICENSE" }
s.source           = { ** secret **  }

s.platform     = :ios, '8.0'
s.ios.deployment_target = '8.0'
s.tvos.deployment_target = '9.0'
s.requires_arc = true

s.ios.source_files = 'Pod/Classes/**/*', 'Pod/Vendor/CrashReporter.framework/Headers/*.h'
s.ios.frameworks = 'SystemConfiguration', 'MobileCoreServices', 'CrashReporter'
s.ios.vendored_frameworks = 'CrashReporter.framework'
s.ios.public_header_files  = 'CrashReporter.framework/Headers/*.h'

s.dependency 'Alamofire', '~>3.0.1'
s.dependency 'ReachabilitySwift', '~>2.1'
end
```

I've tried a lot, but without any success. Each time I'm getting `Use of unresolved identifier PLCrashReporter`

What is the correct way to import a local .framework inside your pod and use it in Swift?

**Comment by segiddins** [comment]
Unfortunately, his isn't enough to investigate the issue. Can you share a project we can try running that reproduces it? Thanks!

**Comment by AvdLee** [comment]
Hi Segiddins, 

I've uploaded a simple version of the project, showing the problem I'm encountering:
https://github.com/AvdLee/ALCrashReporter

Feel free to check it out. You'll notice the error in `TIFCrashReporter.swift`:
```
    private func startReporting(){
        // This line isn't working:
        let crashReporter = PLCrashReporter.sharedReporter()
    }
```

I'm using pod version:
```
pod --version
0.39.0
```

**Comment by AvdLee** [comment]
Maybe good to know, the initial reason for trying to include this .framework is because of the dependency :

`s.dependency 'PLCrashReporter'`

Throws the error:

`target has transitive dependencies that include static binaries`

I'm also very happy when this could be fixed.

**Comment by segiddins** [comment]
That would require PLCrashReporter to release a new version that uses a dynamic framework.

**Comment by AvdLee** [comment]
Finally I succeeded to fix this indeed by create a dynamic framework of it myself. This issue can be closed. @segiddins thanks for your help!

**Comment by Ogel** [comment]
@AvdLee - we're running into this exact issue: trying to develop a CocoaPod that relies on other non-dynamic pods.  Can you share some information on how you created a dynamic version of PLCrashReporter?  Thanks!
