### ISSUE TITLE
[!] Unable to satisfy the following requirements:

### ISSUE THREAD

**Issue by zuil7** [CocoaPods/CocoaPods#4449]
Hi good day,

I am having a issue installing alamofire in my swift project.

My OS is Yosemite
Cocoapods version is 0.39.0
Xcode 7.1

This is the error:

Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

Alamofire (= 3.1.0) required by Podfile
[!] CocoaPods was not able to update the master repo. If this is an unexpected issue and persists you can inspect it running pod repo update --verbose

Hope you can help me on this issue.

Thanks!

**Comment by segiddins** [comment]
What's the output of `pod search Alamofire`, and what's the contents of your Podfile?
In the future, though, this is a usage question that belongs on StackOverflow, issues are generally reserved for bug reports and feature requests.

**Comment by zuil7** [comment]
hi thanks for the quick response.

i can only see 

> Alamofire (2.0.0-beta.1)
   Elegant HTTP Networking in Swift
   pod 'Alamofire', '~> 2.0.0-beta.1'
   - Homepage: https://github.com/Alamofire/Alamofire
   - Source:   https://github.com/Alamofire/Alamofire.git
   - Versions: 2.0.0-beta.1, 1.3.1, 1.3.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.5, 1.1.4, 1.1.3 [master repo].

i see now why its not installing Alamofire 3.1.0.  how can i update the almofire search to 3.1.0? so that i can install almofire 3.1.0.

Thanks

**Comment by segiddins** [comment]
Have you tried `pod repo update`?

**Comment by zuil7** [comment]
yeah when i run pod repo update i get only this

Updating spec repo `master`

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

thanks

**Comment by segiddins** [comment]
Well, what's the output when you run the suggested command?

**Comment by zuil7** [comment]
it was a broken specs repo. Was able to solve it using this step
http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/

$ sudo rm -fr ~/.cocoapods/repos/master
$ pod setup

thanks @segiddins for assisting me :+1:

**Comment by segiddins** [comment]
:+1:
