### ISSUE TITLE
Pod Lib Create Template not working with Swift

### ISSUE THREAD

**Issue by n-studio** [CocoaPods/CocoaPods#4456]
Hi,

I think that the process to create a pod library in Swift is broken.

I followed the guide https://guides.cocoapods.org/making/using-pod-lib-create.html
with the options "Swift", "with demo", "no test", "no view-based test".

Then I created a class ReplaceMe in ReplaceMe.swift, added ```import MyLibrary``` and ```let r = ReplaceMe()``` in the example view controller.

But I can't compile the example project (error: Use of unresolved identifier 'ReplaceMe').

I re-run pod install/pod update, but no luck. The example application doesn't seem to have access to the class in the pod. What am I missing?

Thanks a lot!

cocoapods 0.39.0
Xcode 7.1
OS X: 10.11.1

**Comment by segiddins** [comment]
Require isn't a swift keyword, did you mean to use import?

**Comment by n-studio** [comment]
Yes, sorry, typo. I meant import.

**Comment by orta** [comment]
I've just run though the exact same process and got a working build, is there anything odd in your environment?

<img width="643" alt="screen shot 2015-10-27 at 15 32 53" src="https://cloud.githubusercontent.com/assets/49038/10762954/00cb2428-7cc0-11e5-92bd-3cbca46cff4e.png">


<img width="524" alt="screen shot 2015-10-27 at 15 32 34" src="https://cloud.githubusercontent.com/assets/49038/10762957/02a47b96-7cc0-11e5-99e0-4ed92b0e26e6.png">

**Comment by n-studio** [comment]
@orta Did you also manage to instance a class from the pod? The import instruction does work, but it is as if the module was empty.
![screen shot 2015-10-28 at 12 54 05 am](https://cloud.githubusercontent.com/assets/617116/10763729/6eb6ba80-7d0e-11e5-9cef-081269e7e8f3.png)

**Comment by segiddins** [comment]
@n-studio did you mark the class as public?

**Comment by n-studio** [comment]
And I... didn't.

Damn, I feel very stupid now. Thank you for the help! Sorry for being stupid and wasting your time > .<

**Comment by segiddins** [comment]
No worries 😄
We've all made the exact same mistake
