### ISSUE TITLE
duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by tcurdt** [CocoaPods/CocoaPods#4457]
There are couple of older issue open (or closed) but none sound quite the same - so I opened another one. Feel free to close a duplicate if there is one that matches the problem I am facing.

I just updated cocoapods and a few pods. The pods project builds fine but my project fails to build.
I've used `pod deintegrate` and then `pod install` again. Still I am getting:

    ...
    duplicate symbol _OBJC_CLASS_$_TCAboutWindowController in:
     [...]/Build/Products/Debug/libTCAppCommon.a(TCAboutWindowController.o)
     [...]/Build/Products/Debug/libPods-TCAppCommon.a(TCAboutWindowController.o)
    ....
    ld: 19 duplicate symbols for architecture x86_64

I checked the "Link Binary With Library" section but I only see `libPods.a` in there once. The source files are not in the "Compile Sources" section either. So the question is - where are those duplicate symbols coming from? Here is a prettified version of the linker command

    xctoolchain/usr/bin/clang -arch x86_64 -isysroot [...]/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
    -L[...]/Build/Products/Debug
    -F[...]/Build/Products/Debug
    -F[...]/Pods/Crashlytics-OSX
    -F[...]/Pods/Fabric-OSX
    -F[...]
    -filelist [...]/x86_64/Project.LinkFileList
    -mmacosx-version-min=10.10
    -ObjC
    -lTCAppCommon
    -lTCBuildtools
    -lTCLocalizer
    -lc++ -lz
    -framework Crashlytics
    -framework Fabric
    -framework Security
    -framework SystemConfiguration
    -lPods-TCAppCommon
    -lPods-TCBuildtools
    -lPods-TCLocalizer
    -lc++ -lz
    -framework Crashlytics
    -framework Fabric
    -framework Security
    -framework SystemConfiguration
    -fobjc-arc
    -fobjc-link-runtime
    -lPods
    -lz -lc++
    -framework WebKit
    -framework Carbon
    -framework Cocoa
    -Xlinker
    -dependency_info
    -Xlinker [...]/x86_64/Project_dependency_info.dat
    -o [...]

and fair enough - that looks a bit odd to me.

This is with cocoapods version `0.39.0` building an OSX project.

**Comment by segiddins** [comment]
Hmmm.... What does your Podfile look like?

**Comment by tcurdt** [comment]
source 'https://github.com/CocoaPods/Specs.git'

    platform :osx, '10.10'

    pod 'Fabric-OSX', '~> 1.5.5'
    pod 'Crashlytics-OSX', '~> 3.3.4'

    pod 'TCBuildtools', :git => 'git@github.com:tcurdt/TCBuildtools.git'
    pod 'TCLocalizer', '~> 1.1.0'
    pod 'TCAppCommon', :git => 'git@bitbucket.org:tcurdt/tcappcommon.git'

**Comment by tcurdt** [comment]
`TCAppCommon` also has a dependency on `TCLocalizer` but it all resolves fine on `pod install` and the pod build works, too. And this never was a problem before.

**Comment by tcurdt** [comment]
on OSX 10.10.5, Xcode Version 7.1 (7B91b)

**Comment by segiddins** [comment]
That's really odd... This is definitely a bug, since all the pods should be deduplicated. Would you happen to have a runnable project we could use to investigate?

**Comment by tcurdt** [comment]
Unfortunately one of the few non-open-source projects I have :-/

**Comment by tcurdt** [comment]
Let me see if I can strip the project down...

**Comment by tcurdt** [comment]
Now this is interesting. While stripping down I removed the TCAppCommon dependency. After a fresh `pod install` I still have it in the linker flags

    -lPods-TCAppCommon
    -lPods-TCBuildtools
    -lPods-TCLocalizer

and is giving me (of course) another error

    ld: library not found for -lPods-TCAppCommon

while there should no longer be a reference in the project.
I don't know if that helps - but that stripped down project I could provide.

**Comment by segiddins** [comment]
That's odd. Does running deintegrate again help at all? If not, the project would be super helpful!

**Comment by tcurdt** [comment]
There you go! http://vafer.org/pub/test.zip

I did only try deintegrate on the other project so far. Probably worth trying on the test project as well.

**Comment by segiddins** [comment]
Thanks! We'll try and get around to checking it out soon

**Comment by hyj223** [comment]
You can try it like this ~ #4454

**Comment by tcurdt** [comment]
Indeed - cleaning out all of the "Other Linker Flags" fixed the build.
So those references were added by CocoaPods before and now longer used (and left there)?

**Comment by tcurdt** [comment]
I guess this should probably be reported to https://github.com/CocoaPods/cocoapods-deintegrate
