### ISSUE TITLE
Header Search Paths doesn't contain sub-folder for some pods

### ISSUE THREAD

**Issue by mberube09** [CocoaPods/CocoaPods#4458]
After updating to Cocoapods 0.39, my project was not compiling anymore, it gave an error that some restkit header file was not found. 

Turned out that `"${PODS_ROOT}/Headers/Public/RestKit/CoreData" "${PODS_ROOT}/Headers/Public/RestKit/Network" "${PODS_ROOT}/Headers/Public/RestKit/ObjectMapping" "${PODS_ROOT}/Headers/Public/RestKit/Support"` were not in the header search path of my Pods.xcconfig (debug) anymore.

Is this wanted and should I fix something?

**Comment by segiddins** [comment]
This is intended, and what you're experiencing is a bug in RestKit that I have an open PR fixing over there.

**Comment by middiu** [comment]
Just for the record I had to add the following dirs in my HEADER_SEARCH_PATHS variable: "${PODS_ROOT}/Headers/Public/RestKit/RestKit/CoreData" "${PODS_ROOT}/Headers/Public/RestKit/RestKit/Network" "${PODS_ROOT}/Headers/Public/RestKit/RestKit/ObjectMapping" "${PODS_ROOT}/Headers/Public/RestKit/RestKit/Support" "${PODS_ROOT}/Headers/Public/RestKit/RestKit"
