### ISSUE TITLE
False-positive warning: book quotes in comments

### ISSUE THREAD

**Issue by aral** [CocoaPods/CocoaPods#4459]
CocoaPods erroneously reports a warning if it encounters English curved quotation marks (book quotes; e.g., “like this” or ‘like this’) instead of ambidextrous quotation marks (typewriter quotes; "like this", or 'like this') in a Podfile comment. This is incorrect. It should only warn if they’re used outside of comments. Using typographical quotation marks in comments is perfectly correct and should be the preferred, typographically-correct form.

    [!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

Example of correct usage that flags the erroneous warning:

    # So we don’t have to manually create a bridging header.
    use_frameworks!

**Comment by segiddins** [comment]
Yeah, can't think of a way of fixing this.

**Comment by aral** [comment]
Does Ruby’s RegExp support negative look-behind? (Sorry, not a Ruby person myself) :) 

    if contents.tr!('“”‘’‛', %(""'''))

In https://github.com/CocoaPods/Core/blob/c91e84a264ce9ab5fc500cc8bd8ffad9c9ecd3cf/lib/cocoapods-core/podfile.rb#L268

**Comment by segiddins** [comment]
I believe it does, but remember that you can have a `#` inside other things, where it won't necessarily begin a comment.

**Comment by aral** [comment]
Ah… well, it’s a nice to have ;)

**Comment by segiddins** [comment]
I'm going to close this as not worth implementing, but if someone manages to make a PR to CocoaPods/Core making it happen, we'd be happy to accept it!
