### ISSUE TITLE
Cocoapods Setup in OSX El - captain

### ISSUE THREAD

**Issue by rockykusuma** [CocoaPods/CocoaPods#4460]
I need help in resolving the issue of cocoa pods setup in OSX El- Captain. My Problem is illustrated clearly below..

Rakeshs-MacBook-Pro:~ rakeshkusuma$ sudo gem install -n /usr/local/bin cocoapods

Successfully installed cocoapods-0.39.0

Parsing documentation for cocoapods-0.39.0

Installing ri documentation for cocoapods-0.39.0

1 gem installed

Rakeshs-MacBook-Pro:~ rakeshkusuma$ pod setup

Setting up CocoaPods master repo

[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1

Cloning into 'master'...

error: RPC failed; result=56, HTTP code = 200

fatal: The remote end hung up unexpectedly

fatal: early EOF

fatal: index-pack failed

Rakeshs-MacBook-Pro:~ rakeshkusuma$ pod setup --verbose

Setting up CocoaPods master repo

Creating shallow clone of spec repo master from

https://github.com/CocoaPods/Specs.git (branch master)

$ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1

Cloning into 'master'...

error: RPC failed; result=56, HTTP code = 200

fatal: The remote end hung up unexpectedly

fatal: early EOF

fatal: index-pack failed

[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1

Cloning into 'master'...

error: RPC failed; result=56, HTTP code = 200

fatal: The remote end hung up unexpectedly

fatal: early EOF

fatal: index-pack failed

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/executable.rb:70:in `execute_command'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/executable.rb:27:in `block in executable'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:74:in `block in clone_repo'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:71:in `chdir'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:71:in `clone_repo'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:43:in `block in run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:41:in `run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods- 0.39.0/lib/cocoapods/command/setup.rb:84:in `add_master_repo'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/setup.rb:40:in `block in run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/setup.rb:32:in `run'

/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `'

/usr/local/bin/pod:23:in `load'

/usr/local/bin/pod:23:in `'

Rakeshs-MacBook-Pro:~ rakeshkusuma$

**Comment by segiddins** [comment]
Do you have a working net connection, and are you able to clone from github manually?

**Comment by neonichu** [comment]
Closing due to lack of response.

**Comment by rockykusuma** [comment]
Thank you so much guys for your responses. I got resolved my Problem.

**Comment by HajerBO** [comment]
I have the same problem, how did you resolve it plz ?

**Comment by zhangyunchen** [comment]
I have the same problem, how did you resolve it? @rockykusuma

**Comment by MarkMolina** [comment]
A solution would be nice

**Comment by jakubknejzlik** [comment]
I'm currently having this problem too...but it looks like github problem.

**Comment by xtreme-doug-boutillier** [comment]
We're running into this error as well, with the same error message as @MarkMolina.
We are able to clone `https://github.com/CocoaPods/Specs.git` manually. I let it sit for about 10 mins, came back, and it was done.

**Comment by leiming110** [comment]
Hello,brother, I have the same problem, how did you resolve it? @rockykusuma

**Comment by dhavalsoni1928** [comment]
Hello, i am having the same problem. Unable to pods set up. kindly let me know what issue it can be. i having stable internet connection still it gets stuck and doesn't work.

**Comment by kotercy** [comment]
hello guys,i have the same problem,how did you slove it,share some information?
