### ISSUE TITLE
Update aws link 

### ISSUE THREAD

**Issue by sachinranka4u** [CocoaPods/CocoaPods#4463]
I am getting this error while updating podfile.

Downloading dependencies

-> Installing Mapbox-iOS-SDK (2.1.2)
 > Http download
   $ /usr/bin/curl -f -L -o
   /var/folders/1s/7dbz4h512cx75ypf9v9hfn040000gn/T/d20151029-15470-1ed6lkm/file.zip
   http://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-2.1.2.zip
   --create-dirs

The "http://mapbox.s3.amazonaws.com/ma...." needs to be "https://mapbox.s3.amazonaws.com/ma..."

Please update it,

**Comment by segiddins** [comment]
The maintainers of that pod will need to push a new version.
