### ISSUE TITLE
Embed Pods Frameworks spawns endless xcodebuild processes

### ISSUE THREAD

**Issue by petaren** [CocoaPods/CocoaPods#4464]
I'm running OS X 10.11.1, Xcode 7.1 and Cocoapods 0.39.0. 

Suddenly today I noticed while trying to build my project that something would spawn endless amounts of xcodebuild processes. So many that it crashes my activity monitor on my mac. I have managed to pinpoint the problem to the file `Pods/Target Support Files/Pods/Pods-resources.sh`. The issue occurs when xcode reports that it is running custom scripts. If I empty this file, the problem disappears. So it is most definitely this file.

I have tried to reinstall Xcode, reinstall cocoa pods, remove my `Pods` folder from my project and reinstall my pods with `pod install`. The problem still persists.

**Comment by orta** [comment]
I'd recommend making us an example project so we can look, or adding some echo statements into the `Pod-resources.sh` so you can find out where it is locking up.

**Comment by petaren** [comment]
If you create a new project in iOS and add the following pod file to it the problem happens:

```
platform :ios, "9.0"

xcodeproj "TestCocoaPods"

pod "Firebase", ">= 2.4.1"
pod "RealmSwift"
pod "Mapbox-iOS-SDK"
pod "SWXMLHash"
pod "UIColor_Hex_Swift"

use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

Substitute `TestCocoaPods` for your projects name.

**Comment by petaren** [comment]
Okey, the problem might not necessarily come from cocoapods. I have just had the problem occur on an empty, newly created project as well. Although it just disappeared everywhere now since I tried building with my iPad connected instead of my iPhone. And now I cannot reproduce it anywhere. I'm not sure what to think.

**Comment by petaren** [comment]
Okey, I'm here again now. Seems like the previous message was wrong too. 
Here I am with some more research now. The problem has started to reoccur now and only on projects that are using cocoa pods. I have managed to isolate the problem to the `Pods-resources.sh` file located in `Pods/Target Support Files/Pods`. The problem happens on this line:
```shell
if [[ -n "${WRAPPER_EXTENSION}" ]] && [ "`xcrun --find actool`" ] && [ -n "$XCASSET_FILES" ]
```
More specifically when the command `"`xcrun --find actual`"` is being executed. What is interesting is that when executing this command in the terminal by my self I get the proper output: `/Applications/Xcode.app/Contents/Developer/usr/bin/actool`. But when run from Xcode during a build, be it in the cocoa pods scripts or in a custom one just containing that row it spawns an infinite amount of `xcorebuild` processes.

**Comment by petaren** [comment]
Not related to CocoaPods but Apples tools.

**Comment by segiddins** [comment]
Thanks for following up!

**Comment by petaren** [comment]
Just for those who might be googling the same thing:
I have managed to find out that when I run the command `xcrun --find actual` in the terminal, everything works. However, when run from xcode during a build it completely flips out the system. Running `xcrun -n --find actool` or `xcrun -k` the same problem occurs in the terminal too. However everything works if I run any of the commands using `sudo`. I have not managed to find a solution to the issue. Reinstalling Xcode and xcode command line tools doesn't help. I will be reinstalling my system to try to remedy the issue.
