### ISSUE TITLE
"File not found" error in development pod

### ISSUE THREAD

**Issue by DmIvanov** [CocoaPods/CocoaPods#4466]
Hola! There is some background of my issue here: https://github.com/CocoaPods/CocoaPods/issues/4135 looks close to it

But the issue is: I have my development pod (objC) with some dependent pods (objC). And I wanna use my development pod in some swift project. As a result my pod's files don't see files from dependent pods - I have "file not found" error. Tried to add `public_header_files` as it was written before, but the result was almost the same. (I've checked my pod with objC project - everything worked correctly - so the problem connected with main project written on swift).

I made a test project: https://github.com/DmIvanov/TEST.testPods

Thanks for any help or ideas!

**Comment by atmikev** [comment]
I've been having the same issue. Temp workaround to keep dev going is putting all dependent headers in Public in my Copy Headers build phase.

**Comment by pronebird** [comment]
I have the same problem out of blue. Headers are missing when archiving the pod.

**Comment by segiddins** [comment]
@pronebird what version of CocoaPods were you using? This might be fixed in the 1.0 beta.

**Comment by pronebird** [comment]
@segiddins I had 0.39.

**Comment by segiddins** [comment]
Please try with 1.0, as @kylef marked this as awaiting validation, implying a fix had been proposed at some point.

**Comment by kylef** [comment]
I wouldn't rely on that logic @segiddins. This may not be the case.

**Comment by segiddins** [comment]
The error here is that the pod needs to be using angle bracket imports for headers from other pods.
