### ISSUE TITLE
Xcode7 cocoapods 0.39.0 EI Capitan 10.11.1 update duplicate

### ISSUE THREAD

**Issue by AliThink** [CocoaPods/CocoaPods#4467]
Workspace generated by cocoapods early version before update to EI Captian.
Now after run "pod install" or "pod update" for add some new spec will lead the project compile failed.
Error description like this below:
ld: 75 duplicate symbols for architecture x86_64

**Comment by AliThink** [comment]
when i remove all the -l"Pods-xxx" in the other linker flags ,the project compiled successfully. what's the reason?

**Comment by segiddins** [comment]
You'll need to share more specifics of you want us to be able to look into this, like a project.

**Comment by neonichu** [comment]
Closing due to lack of response.
