### ISSUE TITLE
Dynamic libraries name's extension should be removed in linker flags

### ISSUE THREAD

**Issue by andreacremaschi** [CocoaPods/CocoaPods#4468]
Hi,
in my .podspec I am specifying two dynamic libraries whose extension is ".dylib":

```ruby
cs.vendored_libraries = "geos/lib/libgeos_c.dylib", "geos/lib/libgeos.dylib"
```

What happens is that CocoaPods setup the target's Linker Flags like this:

```
-l"geos.dylib" -l"geos_c.dylib"
```

As a result the pod refuses to validate. I would expect this instead:

```
-lgeos -lgeos_c
```

Modifying the linker flags by hand everything works ok.

**Comment by segiddins** [comment]
Good catch! This should probably be a simple change in the xcconfig helper, if you're willing to make a PR!

**Comment by andreacremaschi** [comment]
uhh I'd love to, but you know, ruby.. :)
ok I'll give it a try
