### ISSUE TITLE
Pod with vendored_libraries and no source files 

### ISSUE THREAD

**Issue by andreacremaschi** [CocoaPods/CocoaPods#4474]
Hi,

I am trying to create a pod to distribute two dynamic libraries and one header file. 
If I specify only the header file in the `source_files` the consumer project does not include a specific target and the dynamic libraries are directly linked with the main target with a linker flag. I.e.:

```ruby
  s.source  = { :http  => "https://github.com/andreacremaschi/geos-fat-dynamic-bitcode/releases/download/3.4.2-alpha.1/geos-3.4.2.zip" }
  s.source_files = "include/geos_c.h"
  s.vendored_libraries = "lib/libgeos_c.dylib", "lib/libgeos.dylib"
  s.public_header_files = "include/geos_c.h"
```

In my main project's target xcconfig this will generate: 

```
OTHER_LDFLAGS = $(inherited) -lgeos -lgeos_c
```

This is correct and works as expected if the pod is consumed directly in an executable target. 
But actually what I am trying to do is to consume this first pod with the two dynamic libraries (`geosprebuilt`) in a second one (`GEOSwift`). Since when dealing with Swift Cocoapods uses frameworks, I set up a test project with a framework target consuming the first pod:

```ruby
use_frameworks!
link_with 'GEOSwift'
pod 'geosprebuilt', :path => "/Users/andreacremaschi/dev/GEOSwift/geos-iOS/geosprebuilt.podspec"
```

Since the [compiler has become more strict in Xcode 7.1](https://github.com/CocoaPods/CocoaPods/issues/4420#issuecomment-151674437) now when I try to import the header file `geos_c.h` in the framework target the compiler throws an error ("Include of non-modular header inside framework module").

So I tried to include an empty "Dummy-file.m" implementation file in `geosprebuilt` to fool CocoaPods:

```ruby
  s.source_files = "Dummy-file.m", "include/geos_c.h"
```

As I expected, now a separate target for my Pod is generated in the GEOSwift test project. Now I can import the header file in my project and the compiler is happy, but this time it is the linker that complains, saying that it can't find the symbols I am using. I checked in the `Product` folder in `Derived data`: the Pod framework is where it is expected to be, it contains the two libraries I am trying to distribute and the dummy `geosprebuilt` executable.

```
.
├── Base.lproj
│   ├── LaunchScreen.storyboardc
│   │   ├── 01J-lp-oVM-view-Ze5-6b-2t3.nib
│   │   ├── Info.plist
│   │   └── UIViewController-01J-lp-oVM.nib
│   └── Main.storyboardc
│       ├── BYZ-38-t0r-view-8bC-Xf-vdC.nib
│       ├── Info.plist
│       └── UIViewController-BYZ-38-t0r.nib
├── Frameworks
│   ├── geosprebuilt.framework
│   │   ├── Info.plist
│   │   └── **geosprebuilt**
│   ├── **libgeos.dylib**
│   ├── **libgeos_c.dylib**
│   ├── libswiftContacts.dylib
│   ├── libswiftCore.dylib
│   ├── libswiftCoreGraphics.dylib
│   ├── libswiftCoreImage.dylib
│   ├── libswiftDarwin.dylib
│   ├── libswiftDispatch.dylib
│   ├── libswiftFoundation.dylib
│   ├── libswiftObjectiveC.dylib
│   └── libswiftUIKit.dylib
├── Info.plist
└── PkgInfo
``` 

I tried to `otool -L` the dummy executable and everything seems fine:

```
geosprebuilt.framework/geosprebuilt:
	@rpath/geosprebuilt.framework/geosprebuilt (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libgeos.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgeos_c.dylib (compatibility version 11.0.0, current version 11.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1241.14.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

So here are my observations:

1. when a pod provides no implementation files but only vendored libraries CocoaPods doesn't create any additional Pod framework targets. This creates an issue with dependent pods that try to import the first pod's non-modular header files. Is it the desired behavior?

2. for some reason I can't get, when consuming a pod that provides dynamic libraries I can't access the symbols of those libraries from outside the pod, but AFAIK I should be able to. Is there anything I am misunderstanding here?

Sorry for the long story, I hope it is clear enough. Cheers!

**Comment by segiddins** [comment]
1) Yes, this is intended -- you'll need to use module includes.
2) You said it was having it link directly against the app, which is how it's supposed to be done -- the symbols should then be available to the app.

**Comment by andreacremaschi** [comment]
Hey Samuel, thank you very much for your input.

1) What do you mean with "use module includes"? Am I supposed to write a .modulemap that reproduces the whole interface defined in `geos_c.h`, to distribute with the `geosprebuilt` pod? 
2) Actually I am trying to create two pods, the first one providing the two dylibs and the header, and the second one consuming the first one. This is the dependency tree:

```
App
└─ GEOSwift (consuming geos with Swift code)
   └─ geosprebuilt (containing the two dylibs and the header `geos_c.h`)
```

**Comment by segiddins** [comment]
No, but include it using angle bracket includes instead of quotes.
To be honest, to debug this, we'd need to be able to try and compile the project (or one that reproduces these issues) ourselves.

**Comment by andreacremaschi** [comment]
Ah ok: I did it, but still I get an "Include of non-modular header inside framework module" error.
I'll try to setup a sample project. Thanks!

**Comment by andreacremaschi** [comment]
ok, here is the sample project: https://github.com/andreacremaschi/GEOSwift-dylib-integration-test.git
it is an empty project with two targets, the app "integration-test" and the framework "GEOSframework". The `Podfile` integrates the external pod with the two dylibs in the framework (it will take a while to download them while installing):

```ruby
use_frameworks!

target 'integration-test' do
end

target 'GEOSframework' do
pod 'geosprebuilt', :git => "https://github.com/andreacremaschi/geos-fat-dynamic-bitcode.git", :branch => "try/GEOSwift-integration"
end
```

Just remember to modify the .xcconfig files to reflect the bug described in https://github.com/CocoaPods/CocoaPods/issues/4468 if needed.

Thank you!

**Comment by andreacremaschi** [comment]
Hi,

I think I have found a good solution for this issue: when distributing a pod including only dynamic libraries one should provide a module map that includes all the public headers of the pod. In my case I had to add a module map made like this:

```
module geos [system] {
    header "geos_c.h"
    export *
}
```

And I had to add this line to the .xcconfig files in my test project:

```
SWIFT_INCLUDE_PATHS= "${PODS_ROOT}/geosprebuilt/include"
```

So, to automate this, CocoaPods should be able to:
- integrate custom module maps in the Pods folder structure (i.e. in the `Headers` folder?)
- include the path of these modules in the "SWIFT_INCLUDE_PATHS" project's setting

**Comment by segiddins** [comment]
If that's the case, it sound like the dylib should just be packaged into a framework to begin with.

**Comment by andreacremaschi** [comment]
Well, this sounds to me as a reasonable workaround, but still I think that in this case CocoaPods would behave inconsistently. Consider the case of a pod containing only dylibs:

- if integrated directly in a project, the dylibs would be linked directly with the main executable and the symbols would be made available through the public header. I.e., this would work:

```
App
└─ geosprebuilt (containing the two dylibs and the header `geos_c.h`)
```

- if integrated as a dependency of a pod module, CocoaPods would link the libs with the executable and make symbols available to the dependency through the public header. But this would NOT work, since a framework module cannot directly import C headers. The resulting workspace would fail to build with the error: "Include of non-modular header inside framework module":

```
App
└─ GEOSwift (consuming geos with Swift code)
   └─ geosprebuilt (containing the two dylibs and the header `geos_c.h`)
```

In my opinion CocoaPods should be able to create the module.map file and declare all the public header files in case of a pod containing only dylibs. I know that this can seem an edge case, but all the GNU C projects (i.e. OpenSSL, SQLite, GEOS etc..) are distributed as dynamic libraries, and this modification would make them accessible in the iOS/OSX ecosystems through CocoaPods, as vanilla as possible.
What do you think?

**Comment by segiddins** [comment]
We can't create the modulemap for dylibs, since it has the potential to break other pods.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
