### ISSUE TITLE
Failed to install swift-sodium via CocoaPods.

### ISSUE THREAD

**Issue by galinyonchev** [CocoaPods/CocoaPods#4480]
Trying to install swift-sodium via CocoaPods, got this message:

[!] Unable to find a specification for Sodium (~> 0.1)

Here is the library: https://github.com/jedisct1/swift-sodium

**Comment by segiddins** [comment]
What version of cocoapods are you running? Did you try running `pod repo update`? Did you manually verify that pod exists for the platform you're trying to install for?

**Comment by kylef** [comment]
There is no pods in the master spec repository called 'Sodium'. You should file an issue with https://github.com/jedisct1/swift-sodium that their installation instructions are incorrect.

Closing this issue as the underlying issue isn't with CocoaPods.
