### ISSUE TITLE
Why does the generated umbrella header include Cocoa?

### ISSUE THREAD

**Issue by TGOS** [CocoaPods/CocoaPods#4481]
My framework doesn't need Cocoa and never linked against it but the umbrella header always has  `#import <Cocoa/Cocoa.h>` on top.

**Comment by segiddins** [comment]
Legacy reasons. We can't get rid of it or a bunch of existing pods could break.

**Comment by TGOS** [comment]
Not so fast. There is the ` spec.framework` setting in a Podspec, right? So whoever uses that setting and does not specify Cocoa there, even though his code needs Cocoa, must expect the build to fail in the first place, right? On the other hand, whoever doesn't need Cocoa will not put Cocoa there (and maybe just Foundation for example). So why don't you just look if that setting is present and what this setting does say about dependencies? I mean, very old pods may not have that setting at all, okay, in that case do whatever you like or do whatever you think is correct but whoever is using that setting must also use it correctly, otherwise breaking is expected, not to say required behavior.

**Comment by segiddins** [comment]
No, because those frameworks have always been linked, regardless of whether they have been explicitly specified.

**Comment by TGOS** [comment]
Okay, then let's get rid of this issue and replace it with a feature request (just adding this here if some reader comes across that issue):
Add a podspec parameter to suppress all implicit linking 
#4494
