### ISSUE TITLE
Why does the generated umbrella header includes headers "flat"?

### ISSUE THREAD

**Issue by TGOS** [CocoaPods/CocoaPods#4482]
All my headers are in a sub-directory, like "ProjectX", so when I want to imported them, I did this:

    #import <ProjectX/SomeClass.h>

I have the `header_mappings_dir` in my podspec to keep that structure and it has been working. Yet in the generated umbrellea header, it is imported as

    #import "SomeClass.h"

Why flat? Why `" "` and not `< >`? (for frameworks there is no real distinction between user and system as far as I can tell) And if I look into the SDK, e.g. Foundation, then all imports are

    #import <Foundation/...>

So shouldn't umbrella headers use path prefixed imports?

**Comment by segiddins** [comment]
Does the current way it's done cause any actual issues for you?

**Comment by TGOS** [comment]
If you link against two pod frameworks and both have a header `blah.h`, there are two `blah.h` in the user search path and if you don't use `@import` (which is still used rarely in most code) but just standard imports, then these standard imports cause the umbrella header to imported (pars pro toto principle) and then it's not defined which header `blah.h` will be used (the compiler will just use the first one it finds which is only defined by the order the framework or headers search paths are provided).

I see no reason why not doing it the same way Apple does it. As Apple invents and develops all this, rule of the thumb is: If you are not doing it like Apple is doing it, you are doing it wrong. Doing it wrong can work but only doing it right is guaranteed to work and also be future proof.

**Comment by TGOS** [comment]
When you create a new framework in Xcode, Apple creates a template umbrella header for you and it says:

    // In this header, you should import all the public headers of your framework
    // using statements like #import <XXX/PublicHeader.h>

Where XXX is the name of your framework. "Should" is not must, but do you have any reason not to follow what Apple requests? Just wondering.

**Comment by mrackwitz** [comment]
You can use imports like shown there, you would just need to make sure that you configure the module name correctly. Usually CocoaPods derives that from the podspec name. If that doesn't match for you, you can use the podspec attribute [`module_name`](http://guides.cocoapods.org/syntax/podspec.html#module_name) to specify another name than shown. Using `header_mappings_dir` is not the right solution.

**Comment by TGOS** [comment]
I am already using `module_name` (I've always been using that) and I need the `header_mappings_dir` as otherwise the code itself won't build. Consider a H file of the framework; this H file needs to work in two different situations:

1) I build the framework itself. An import like this in a H file:

    #import <ModuleName/SomeOtherClass.h>

will fail while building the module itself if all headers are flat within a folder. Instead you do it like this: You create a folder `include` and within that folder you create a folder `ModuleName`, then you put all your headers in the folder `ModuleName` but add the folder `include` itself (which contains not a single header!) to the header search path. Voilla, problem solved, as now `ModuleName/SomeOtherClass.h` refers to a H file that will be found when building the framework itself. In this case `ModuleName` is just the name of a folder and to preserve that folder, `header_mappings_dir` is required, otherwise the H file is just not found.

2) Using the framework in another project. Here the framework is already a framework, so here all headers can be flat in `ModuleName.framework/Headers` (which is actually a symlink) and still the import will work because this time there is no folder `ModuleName` as this time `ModuleName` actually is the module name (the name of the framework).

That way the same header files work for both cases, building the framework and using the framework - otherwise I'd need different includes for either task. This is also how Apple does it and it's common knowledge for ages.

Importing with quotes in an external source is dangerous. Quote imports are only for the user (that's what their name already implies) and if you put `#import "SomeClass.h"` into an umbrella header and the user has a file name `SomeClass.h` in his project, it may as well be his file getting imported here and not the file of the framework; the order how header searches paths are searched is the order how these were fed to the compiler and relying on a specific order here is not a very clever idea.

**Comment by segiddins** [comment]
I don't think that's an issue here since the umbrella header is only used when building the clang module, and isn't ever being imported as a normal external header.

**Comment by TGOS** [comment]
That's not true. The header is copied into the framework and marked as umbrella header in the module map. See code sample for issue #4494. Compiling the C file in that code sample (first target) fails because the umbrella header that CP generated is imported into that C file. Note that the C file itself never even tries to import that header, it just tries to import some other H file from the framework which would work nicely, but whenever a framework has an umbrella header and you import any header from that framework (no matter which one!), the result is that the umbrella header is being imported instead of the requested header (that is also documented exactly that way by Apple).

And this is inheritly dangerous and can easily break builds as your umbrella header uses non-modularized imports (which by itself already is bad), but to make things even worse, these are user search path header imports. And so far you have not been able to provide any good reason for intentionally violate Apple's recommendations. Is asked you the same question at issue #4496 and the answer was, that this will break archiving of static libs, which I can hardly believe, sorry. I'd like to reproduce that issue but I don't have the required info for this.

CP relies way to mach on the fact that header names are unique and no two identically names will ever show up in different places. So it adds all headers pretty much to all search paths, which will make imports very comfortably as pretty much every kind of import/import style will just magically work right but if there's ever a name conflict, hell just breaks lose as you can see at issue #4489 which is also such a name conflict that wouldn't even exists if CP would follow what is defined in the Podfile and otherwise would stick to Apple's recommendations.

**Comment by malhal** [comment]
Is there an option to specify our own umbrella header or disable the generation of an extra umbrella?

**Comment by segiddins** [comment]
@malhal if you specify a module map, CocoaPods won't generate an umbrella header

**Comment by RbBtSn0w** [comment]
> [@malhal](https://github.com/malhal) if you specify a module map, CocoaPods won't generate an umbrella header

Usually, we use the default name in the podspec as the moduleName.
Therefore, the default generated umbrella file will be used, but the umbrella file generation format does face a problem that Apple's normalization. This is the path of the specification that the richer LLDB encounters in debugging.

It is desirable that the format in the auto-generated umbrella file satisfies the #import<moduleName/xxsx.h>
