### ISSUE TITLE
ONLY_ACTIVE_ARCH =NO in Debug xcconfig

### ISSUE THREAD

**Issue by grantjbutler** [CocoaPods/CocoaPods#4483]
I've got an issue where CocoaPods 0.39.0 is generating an xcconfig file for my project that sets `ONLY_ACTIVE_ARCH ` to `NO` for all configurations of my project. However, this behavior seems to run counter to what is outlined in the [troubleshooting docs](http://guides.cocoapods.org/using/troubleshooting.html#running-into-build-failures-after-migrating-to-xcode--and-cocoapods-) on how to make sure Pods build (specifically that first item on the list). I can fix the build by resetting `ONLY_ACTIVE_ARCH ` to `YES` in the target's build settings, but then CocoaPods complains that I've overwritten the build setting when running `pod install`.

The build specifically fails when linking. I get a bunch of warnings and errors logged, an example of both has been included below:

```
ld: warning: ignoring file libCocoaLumberjack.a, file was built for archive which is not the architecture being linked (i386): libCocoaLumberjack.a
```

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_DDLog", referenced from:
```

**Comment by neonichu** [comment]
Could you please provide an example project or steps to reproduce this?

**Comment by grantjbutler** [comment]
False alarm. It was a specific pod that we had installed that specified that as part of its spec. Closing this issue.
