### ISSUE TITLE
Viewing swift dynamic framework public api for vendored_libraries

### ISSUE THREAD

**Issue by marcus174** [CocoaPods/CocoaPods#4484]
I have a compiled dynamic framework hosted in a xcode project as a dependency utilizing the vendored_libraries in my podspec which works great. I can autocomplete classes in xcode, look at documentation in quick help and build/run my application.

However when I try to click through on the import FrameworkName in my swift classes (to view the framework public API) Xcode says  "Couldn't Generate Swift Repersetnation Error (from Source Kit): Could not load module: FrameworkName".

If I create a new project and manually embed these frameworks it works fine.

The issue looks similar to the following screenshot:
http://i.stack.imgur.com/2MoIE.png

**Comment by segiddins** [comment]
Without an example project that demonstrates this issue, I'm afraid we'll be unable to investigate.

**Comment by marcus174** [comment]
I will set up a sample project on git hub reproducing it.

**Comment by marcus174** [comment]
Hi Sam,

I've set up a really quick sample showing it, this was built for Xcode 7.1.

Please put the following dependency in your Podfile

pod 'TestProject', :git => 'https://github.com/marcus174/CPDynamicFramework.git', :branch => 'master'

Try importing the framework as follows and try to access the public api of Test Project by clicking through the import.

import UIKit
import TestProject

class ViewController : UIViewController {
 
   override  func viewDidLoad() {
        var api : MyApi
    }
}

repo urls 

https://github.com/marcus174/CPDynamicFramework  - This is an xcode project hosting just the binary framework.
https://github.com/marcus174/CPDynamicFrameworkSource - This is the source code of the framework.

**Comment by segiddins** [comment]
Off the bat, I can tell you that you shouldn't manually be specifying `OTHER_LDFLAGS`

**Comment by marcus174** [comment]
Have tried removing it and issue still exists.

**Comment by marcus174** [comment]
Any additional information required to diagnose this?

**Comment by segiddins** [comment]
Not sure, I've been working on other Cocoapods things lately.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
