### ISSUE TITLE
Circular Pod Dependencies

### ISSUE THREAD

**Issue by hugey010** [CocoaPods/CocoaPods#4485]
I have two Objective-C libraries that depend on each other in a small way. There isn't an easy way to structure the hierarchy of my libraries differently in order to avoid this. When I pod update in one of these libraries, I get itself (or a version of itself) as a dependency, and therefore duplicate symbols when linking. Removing the files in the pod from Target Membership does allow the project to build successfully, but this is hardly a solution.

Is there a way to force a pod to not download and link in the Podfile. Something like:
```
pod-skip 'ThisPodsName'
```

Thanks for any help you can offer!

**Comment by kylef** [comment]
@hugey010 Not sure I fully understand your problem, but from what it sounds like, your target is the source for your Pod. This sounds like you want to use `podspec`.

Example: https://github.com/the-hypermedia-project/Hyperdrive/blob/master/Podfile#L4

```ruby
use_frameworks!

target 'Hyperdrive' do
  podspec
end

target 'HyperdriveTests' do
  podspec
end
```

There is also an existing issue to track adding this "skip" feature at https://github.com/CocoaPods/Core/issues/150

**Comment by hugey010** [comment]
Having the podspec determine the dependencies doesn't solve the issue. The 'skip' feature seems to be what I'm looking for but I'm not entirely sure after I read more of the discussion.

Let me try to clarify the issue. Library A depends on Library B, and B depends on A. When working in library A, pod update pulls in library B, which in turn, pulls in library A as a dependency. Now I have two copies of library A.

1. Merge the two libraries into one. Personally, I don't want this.
2. Using pod ```pod 'MyCurrentPod', :configurations => ['Release'] ``` actually fixes the issue and allows me to debug without duplicate symbols. I wish i could use ```pod 'MyCurrentPod', :configurations => [] ``` to specify 0 configurations to link against.

**Comment by kylef** [comment]
Circular dependencies are not supported, if you have a library that depends on another library that depends back on the first library. CocoaPods will throw a circular dependency and a user won't be able to use either of these pods together.

See https://github.com/CocoaPods/Specs/issues/12819#issue-49310318 for more information.

> From a practical perspective, if two specs 'have to be installed together', then they really are one dependency. As such, you will need to combine these together in the Podspec.

Perhaps in your case it would make sense to create a third library (C) which encapsulates the logic that creates the circular dependency.

**Comment by hugey010** [comment]
Thanks @kylef. It's starting to sound like I'm stepping into feature request territory to support circular dependencies. For my use case it doesn't seem that difficult; just don't copy and don't link those circular files!

**Comment by segiddins** [comment]
Nope, circular dependencies won't ever be supported. This decision was made over a year ago for a variety of reasons, and won't be changed.
