### ISSUE TITLE
Understanding pod update someUpdate

### ISSUE THREAD

**Issue by anoop4real** [CocoaPods/CocoaPods#4488]
Hi,

I want to update one of my pod without touching others,

I tried doing the 'pod update SomeUpdate' command and below is the result

 '   pod update UrbanAirship-iOS-SDK.....
........
    Using Bolts (1.1.5)
    Using Facebook-iOS-SDK (4.1.0)
    Using FormatterKit (1.3.2)
    Using GoogleAnalytics-iOS-SDK (3.11)
    Using GoogleConversionTracking (3.2.0)
    Using HockeySDK (3.5.7)
    Using KVOController (1.0.3)
    Using PonyDebugger (0.4.3)
    Using SDWebImage (3.7.2)
    Using SSKeychain (1.2.3)
    Using SocketRocket (0.2.0)
    Using ToastMaster (0.1)
    Using UIActionSheet+Blocks (0.9)
    Using UrbanAirship-iOS-SDK (5.1.1)
    Using ZBarSDK (1.3.1)
    Using dyci (0.1.5.6)
    Generating Pods project
    Integrating client project'

After this if I check my SourceTree, I can see around 300 new files waiting to be added to the project, which includes files from Facebook SDK, ZBarSDK, HockeyAppSDK etc, I just wanted updates on UrbanAirship SDK.

Is this suppose to happen? Is it because UrbanAirship SDK has some dependencies with the above other SDKs?

In between, I had Cocoapods 0.35.0 earlier and updated sometime back to 0.36.1 may be is it because of this? I have no clue, request some help from Pod experts out here.

**Comment by segiddins** [comment]
It's impossible to tell from just the information you've shared so far, but yes, it's intentional that dependencies of the pod you're updating that are not specified in the Podfile also get updated.
If that's not what's happening here, you'll need to share a Podfile and Podfile.lock that reproduce the issue.

**Comment by anoop4real** [comment]
I am unable to attach file so posting here

Podfile
_________
source 'https://github.com/CocoaPods/Specs.git'

link_with ‘app’

platform :ios, '7.0'
inhibit_all_warnings!

pod 'dyci', :configurations => ['Develop']
pod 'PonyDebugger', '~> 0.4.0', :configurations => ['Develop']
pod 'HockeySDK',              '~> 3.5.0b2'
pod 'ZBarSDK', '~> 1.3.1'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'GoogleConversionTracking', '~> 3.1'
pod 'Facebook-iOS-SDK', '~> 4.1.0'
pod 'FormatterKit', '~> 1.3.0'
pod 'SDWebImage', '>= 3.5.2'
pod 'SSKeychain', '~> 1.2.1'
pod 'UIActionSheet+Blocks', '~> 0.8'
pod 'UrbanAirship-iOS-SDK', '~> 5.1.0'

# Old pods
pod 'ToastMaster', :path => 'Local Pods/Toastmaster'

Podfile.lock
_________

PODS:
  - Bolts (1.1.5):
    - Bolts/AppLinks (= 1.1.5)
    - Bolts/Tasks (= 1.1.5)
  - Bolts/AppLinks (1.1.5):
    - Bolts/Tasks
  - Bolts/Tasks (1.1.5)
  - dyci (0.1.5.6):
    - dyci/Injections (= 0.1.5.6)
  - dyci/Injections (0.1.5.6)
  - Facebook-iOS-SDK (4.1.0):
    - Bolts (~> 1.1)
    - Facebook-iOS-SDK/CoreKit (= 4.1.0)
    - Facebook-iOS-SDK/LoginKit (= 4.1.0)
    - Facebook-iOS-SDK/ShareKit (= 4.1.0)
  - Facebook-iOS-SDK/CoreKit (4.1.0):
    - Bolts (~> 1.1)
    - Facebook-iOS-SDK/CoreKit/no-arc (= 4.1.0)
  - Facebook-iOS-SDK/CoreKit/no-arc (4.1.0):
    - Bolts (~> 1.1)
  - Facebook-iOS-SDK/LoginKit (4.1.0):
    - Bolts (~> 1.1)
    - Facebook-iOS-SDK/CoreKit
  - Facebook-iOS-SDK/ShareKit (4.1.0):
    - Bolts (~> 1.1)
    - Facebook-iOS-SDK/CoreKit
  - FormatterKit (1.3.2):
    - FormatterKit/AddressFormatter (= 1.3.2)
    - FormatterKit/ArrayFormatter (= 1.3.2)
    - FormatterKit/ColorFormatter (= 1.3.2)
    - FormatterKit/LocationFormatter (= 1.3.2)
    - FormatterKit/OrdinalNumberFormatter (= 1.3.2)
    - FormatterKit/TimeIntervalFormatter (= 1.3.2)
    - FormatterKit/UnitOfInformationFormatter (= 1.3.2)
    - FormatterKit/URLRequestFormatter (= 1.3.2)
  - FormatterKit/AddressFormatter (1.3.2)
  - FormatterKit/ArrayFormatter (1.3.2)
  - FormatterKit/ColorFormatter (1.3.2)
  - FormatterKit/LocationFormatter (1.3.2)
  - FormatterKit/OrdinalNumberFormatter (1.3.2)
  - FormatterKit/TimeIntervalFormatter (1.3.2)
  - FormatterKit/UnitOfInformationFormatter (1.3.2)
  - FormatterKit/URLRequestFormatter (1.3.2)
  - GoogleAnalytics-iOS-SDK (3.11):
    - GoogleAnalytics-iOS-SDK/Core (= 3.11)
  - GoogleAnalytics-iOS-SDK/Core (3.11)
  - GoogleConversionTracking (3.2.0)
  - HockeySDK (3.5.7)
  - KVOController (1.0.3)
  - PonyDebugger (0.4.3):
    - SocketRocket
  - SDWebImage (3.7.2):
    - SDWebImage/Core (= 3.7.2)
  - SDWebImage/Core (3.7.2)
  - SocketRocket (0.2.0)
  - SSKeychain (1.2.3)
  - ToastMaster (0.1)
  - UIActionSheet+Blocks (0.9)
  - UrbanAirship-iOS-SDK (5.1.1):
    - UrbanAirship-iOS-SDK/Core (= 5.1.1)
  - UrbanAirship-iOS-SDK/Core (5.1.1)
  - ZBarSDK (1.3.1)

DEPENDENCIES:
  - dyci
  - Facebook-iOS-SDK (~> 4.1.0)
  - FormatterKit (~> 1.3.0)
  - GoogleAnalytics-iOS-SDK (~> 3.10)
  - GoogleConversionTracking (~> 3.1)
  - HockeySDK (~> 3.5.0b2)
  - PonyDebugger (~> 0.4.0)
  - SDWebImage (>= 3.5.2)
  - SSKeychain (~> 1.2.1)
  - ToastMaster (from `Local Pods/Toastmaster`)
  - UIActionSheet+Blocks (~> 0.8)
  - UrbanAirship-iOS-SDK (~> 5.1.0)
  - ZBarSDK (~> 1.3.1)

EXTERNAL SOURCES:
  ToastMaster:
    :path: Local Pods/Toastmaster

SPEC CHECKSUMS:
  Bolts: aac24961496d504aa56fc267cde95162a71bac39
  dyci: 099c2e6dc98abb8f21b370cabbf1443ff700608a
  Facebook-iOS-SDK: f42dfb27283bf5f05e3a9edc88459a75b9892d99
  FormatterKit: e8e201770b33c4cf41c72d5c7124165f9ec1490f
  GoogleAnalytics-iOS-SDK: fb15cc7e3d01d06d531653f37443fda90274d53d
  GoogleConversionTracking: e451aecf6baaa0f2b9aa6e4cfc6b2f8a74febac0
  HockeySDK: 9af986df24fbb034ca7578d7a1cd7711bfb943d5
  KVOController: 9fd8f0343670994e4b6f9f0b31f5a45663f3e1cf
  PonyDebugger: 52f96f501df018dc2b7153fa18464b82553e700c
  SDWebImage: 71b7cdc1d1721d6a82ed62889030225f2c249e29
  SocketRocket: 54a4ac2f354c4e8c51ef5dcd4a13bc556d4f2b7c
  SSKeychain: 3f42991739c6c60a9cf1bbd4dff6c0d3694bcf3d
  ToastMaster: 71d7d79db1f4e108439eb15e691192090ecefcc0
  UIActionSheet+Blocks: e180b7dad0a721ab7f212ac9742af799008bb358
  UrbanAirship-iOS-SDK: e97975b3bacb0c772cf25f35d42e8618e66825dd
  ZBarSDK: 4c1b5daeb7d6cc67dc9355e690af0230a661f6ec

COCOAPODS: 0.35.0

**Comment by anoop4real** [comment]
Any clues?? I am not sure how to change the label status from "awaiting input".

**Comment by segiddins** [comment]
Sorry, haven't had time to look into this specific issue yet

**Comment by timbodeit** [comment]
@anoop4real The Podfile.lock you provided, is that before or after the `pod update UrbanAirship-iOS-SDK` call?

Please make sure to provide the one before, not the one after. 

Also, next time you're sharing a file this way, please put three backticks ``` in the line before and after to mark it as a code block.

**Comment by segiddins** [comment]
Closing due to lack of response.
