### ISSUE TITLE
Cyclic reference of headers caused by avoidable header name collision

### ISSUE THREAD

**Issue by TGOS** [CocoaPods/CocoaPods#4489]
We have a framework and this framework has a header named `assert.h` - yes, that's named like a standard C header, but that was never a problem because to get to that header, you had to do

    #import <FrameworkXYZ/assert.h>

Now I tried to convert that framework into a Pod. I used the `s.header_mappings_dir` setting to preserve the directory structure of the headers, which are in a folder

    ./include/FrameworkXYZ/...

so even within the Framework Code I can use imports as shown above. The Pod built just fine but when I tried to use it in another project, I got strange compiler errors about a "Circular References" that I've never seen before.

It turned out that the problem was, that you create symlinks to all headers in 

    ./Pods/Headers/Private/FrameworkXYZ/FrameworkXYZ/....

Don't wonder, that `FrameworkXYZ` exists twice, this is expected, one is the target name and one is because of the preserved directory structure (`.header_mappings_dir`). Why these headers are in private, even though the podspecs marks them public (*and they are public within the build framework!*) is also a mystery to me.

Anyway, the problem is that not just `./Pods/Headers/Private/FrameworkXYZ/` is added to the header search path but also ` ./Pods/Headers/Private/FrameworkXYZ/FrameworkXYZ` and it is not just added to the user search path, it is added to the system search path. That means if some header file does an

    #import <assert.h>

it now will import `<FrameworkXYZ/assert.h>` and this lead to the cyclic reference as Cocoa does include `assert.h` somewhere and my `assert.h` included `Cocoa/Cocoa.h`.

IMHO `./Pods/Headers/Private/FrameworkXYZ/FrameworkXYZ` should not be in the search path, only `./Pods/Headers/Private/FrameworkXYZ` should be. And whether they should be in the system search path is arguable as well. IMHO they should be only in the user header search path. The real headers in the built framework will be in the system header search path but these must be included prefixed with the framework name anyway.

**Comment by segiddins** [comment]
They'll be in both public and private. Also, this behavior changed in CocoaPods 0.39, can you verify that's the version you're testing with (recursive search paths are no longer constructed).

**Comment by TGOS** [comment]
I use 0.39.0 and the only way not to have this recursion is to rename my `assert.h` to something else. Everything I wrote above is how 0.39.0 works. And no, they are not both public and private, there exists only the Private dir, there is no Public dir  (they are only public in the framework built in the built output dir).

**Comment by segiddins** [comment]
Ah well there's a PR open that stops creating the private headers directory for frameworks, you should see if it fixes things for you.

**Comment by neonichu** [comment]
@TGOS Since #4476 has been merged now, could you verify if it fixes your issue?

**Comment by segiddins** [comment]
Closing due to lack of response.
