### ISSUE TITLE
Xcode 7.2 and CocoaPods

### ISSUE THREAD

**Issue by jshier** [CocoaPods/CocoaPods#4491]
Xcode 7.2 beta 2 is out today, and I noticed that the release notes called out CocoaPods by name. I don't know if this has been seen or what, just though I'd post it here. Seems like this could be important.

> The Swift compiler is now stricter about including non-modular header files. Debugging a Swift target requires that frameworks be properly modular, meaning all of the publicly-imported headers are either accounted for in the framework's umbrella header, imported from another modular framework, or listed explicitly in a custom module.modulemap file (advanced users only).
> The compiler will run into issues if the same header file is accessible both through Header Search Paths (`-I`, `-isystem`) and Framework Search Paths (`-F`, `-iframework`), even if there are symbolic links involved. In these cases, you should prefer using Framework Search Paths alone. (Note that this invalid configuration may be generated by external systems, such as CocoaPods.) (23341162)

**Comment by alloy** [comment]
Thanks for the FYI! The underlying issue has been getting discussion here #4420.
