### ISSUE TITLE
Cocoa touch framework with pods, works in sim but not on device

### ISSUE THREAD

**Issue by RossOliver** [CocoaPods/CocoaPods#4493]
If I add a cocoa touch framework to my project and include it in the Podfile the app works fine in the simulator but I get a crash when launching on a real device:

dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/mobile/Containers/Bundle/Application/93306426-101B-485A-B5AF-365047A26973/Test2.app/Frameworks/Test2Common.framework/Test2Common
  Reason: image not found

Here is a test project demonstrating the issue:

https://www.dropbox.com/s/ioi398ojlgehct2/Test2.zip?dl=0

I'm using Cocoapods v0.39.0, here's the Podfile:

```
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Test2’ do
    platform :ios, "8.0"

end

target 'Test2Common' do
    platform :ios, "8.0"

    pod 'Alamofire'
end

pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3957
    installer.config.deterministic_uuids = false
end
```

**Comment by neonichu** [comment]
We don't really support integrating Pods into framework targets, you'll be better off creating a podspec for "Test2Common".

**Comment by RossOliver** [comment]
Thanks for the suggestion - I take it I could just create a local Podspec and list Alamofire as a dependency this way? do you know if I can keep the framework in the same project and achieve this or am I best to refactor it into it's own project?

**Comment by segiddins** [comment]
@RossOliver correct.

**Comment by RossOliver** [comment]
That worked great, cheers!
