### ISSUE TITLE
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

### ISSUE THREAD

**Issue by goktugyil** [CocoaPods/CocoaPods#4497]
http://stackoverflow.com/questions/33524503/command-applications-xcode-app-contents-developer-toolchains-xcodedefault-xctoo

**Comment by orta** [comment]
Hi @goktugyil - please don't create issues like this on the CocoaPods issues. If you'd like to write an issue on here for CocoaPods bugs or feature requests, please write it out.

**Comment by goktugyil** [comment]
Sorry. Created a new one: 
https://github.com/CocoaPods/CocoaPods/issues/4498
