### ISSUE TITLE
CocoaPods integration with embedded framework

### ISSUE THREAD

**Issue by andreyslyusar** [CocoaPods/CocoaPods#4499]
I have next setup of my project:

![screenshot 2015-11-04 16 32 22]
(https://cloud.githubusercontent.com/assets/1401690/10942770/be9f3ce4-8311-11e5-8635-d32c7bc3b1ae.png)

![screenshot 2015-11-04 16 33 33](https://cloud.githubusercontent.com/assets/1401690/10942788/d0f6e5f4-8311-11e5-8e43-f685dd1e8170.png)

![screenshot 2015-11-04 16 35 41](https://cloud.githubusercontent.com/assets/1401690/10942856/1dd26fd8-8312-11e5-8beb-c79bd15ade42.png)

Try to run and get next error:
![screenshot 2015-11-04 16 33 59](https://cloud.githubusercontent.com/assets/1401690/10942804/e94e1f0a-8311-11e5-9283-f1d3699dee68.png)

I try to clean Derived Data, remove and setup workspace from start.

I have xCode 7.1 and CocoaPods 0.39.0. Am I doing something wrong with pod setup? Initial idea is to split application source code in embedded framework, but also have access pod dependencies all over the project.

**Comment by orta** [comment]
I'd recommend running `gem install cocoapods-deintegrate` then `pod deintegrate`. 

Looks like there's still a reference to globally scoped Pods from the Podfile before. Also check out the `link binary` build phase, to see if there's a reference to the `Pods.framework`

![screen shot 2015-11-04 at 10 43 42 am](https://cloud.githubusercontent.com/assets/49038/10943109/0c9d7e96-82e1-11e5-93b6-560531fc7e1c.png)

**Comment by andreyslyusar** [comment]
Save my day @orta, ```Pods.framework``` was in ```Link Binary With Libraries```.
