### ISSUE TITLE
Incorrect Paths in Copy Pods Resources phase with use_frameworks!

### ISSUE THREAD

**Issue by orkoden** [CocoaPods/CocoaPods#4500]
I changed my Podfile to use frameworks with `use_frameworks!`. Now I get the following error in the **Copy Pods Resources** build phase.
```
building file list ... rsync: link_stat "/Users/joerg/Library/Developer/Xcode/DerivedData/PodCastAndHockey-azyqptahyqmbgdcupfhuoutvxjxs/Build/Products/Debug-iphonesimulator/HockeySDKResources.bundle" failed: No such file or directory (2)
rsync: link_stat "/Users/joerg/Library/Developer/Xcode/DerivedData/PodCastAndHockey-azyqptahyqmbgdcupfhuoutvxjxs/Build/Products/Debug-iphonesimulator/CastFrameworkAssets.bundle" failed: No such file or directory (2)
done
```
```
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

I looked at the Build folder in DerivedData and found that the frameworks in question were in a subfolder named `Pods` (when specifying a target in the Podfile the folder is `Pods-targetname`).
So the expected path is `Debug-iphonesimulator/CastFrameworkAssets.bundlePods` but the actual path is `Debug-iphonesimulator/Pods/CastFrameworkAssets.bundlePods`.

![Screenshot with path Debug-iphonesimulator/Pods/CastFrameworkAssets.bundlePods](http://i.imgur.com/gaCzxzr.png)

I was able to work around this by editing the script in question: `Pods/Pods-resources.sh` (when specifying a target in the Podfile: `Pods-targetname-resources.sh`). To correct the path. Insert the following after line 60.

```
BUILT_PRODUCTS_DIR_POD_RESOURCES_PODS="${BUILT_PRODUCTS_DIR}/Pods"
BUILT_PRODUCTS_DIR_POD_RESOURCES_PODS_TARGET="${BUILT_PRODUCTS_DIR}/Pods-${TARGET_NAME}"
if [ -d "${BUILT_PRODUCTS_DIR_POD_RESOURCES_PODS}" ]; then
	BUILT_PRODUCTS_DIR_POD_RESOURCES=${BUILT_PRODUCTS_DIR_POD_RESOURCES_PODS}
elif [ -d "${BUILT_PRODUCTS_DIR_POD_RESOURCES_PODS_TARGET}" ]; then
	BUILT_PRODUCTS_DIR_POD_RESOURCES=${BUILT_PRODUCTS_DIR_POD_RESOURCES_PODS_TARGET}
else
	BUILT_PRODUCTS_DIR_POD_RESOURCES="${BUILT_PRODUCTS_DIR}"
fi
```

Then edit the parameter passed to `install_resource`, to use the corrected path like the following for all configurations.

```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource "google-cast-sdk/GoogleCastSDK-2.10.0-Release/GoogleCast.framework/GoogleCastResources.bundle"
  install_resource "${BUILT_PRODUCTS_DIR_POD_RESOURCES}/HockeySDKResources.bundle"
  install_resource "${BUILT_PRODUCTS_DIR_POD_RESOURCES}/CastFrameworkAssets.bundle"
fi
```

I created a [sample project where you can reproduce the problem](https://github.com/orkoden/PodCastAndHockey).

The `Podfile` looks like this.
```
use_frameworks!
platform :ios, :deployment_target => '8.0'
pod 'HockeySDK'
pod 'google-cast-sdk'
```

Cocoapods version 0.39.0

**Comment by orkoden** [comment]
As I understand from [neonacho's comment](https://github.com/CocoaPods/CocoaPods/issues/3761#issuecomment-117922586) the `Pods` subfolder should not even be created.

**Comment by sirnacnud** [comment]
I am running in to the same problem. Is there a fix?

**Comment by orkoden** [comment]
I removed the Pod and installed the dependency manually.

**Comment by segiddins** [comment]
This should be fixed on `master` now.
