### ISSUE TITLE
Assets (in xcassets) aren't compiled as a car when bundling

### ISSUE THREAD

**Issue by astralbodies** [CocoaPods/CocoaPods#4501]
# System specs
* Xcode 7.1
* CocoaPods 0.39.0
* Mac OS X 10.11.1

# Scenario
I have a pod (https://github.com/wordpress-mobile/WordPressCom-Stats-iOS) that I'm trying to move to include the assets in an asset catalog rather than straight copying the PNGs to the resource bundle. I'm trying to move to us using vector PDFs for our assets so that PNGs are created upon compile time. It also allows us to add `tintColor` to the `UIImageView`s instead of creating separate assets for every color/state.

# Changes made to the project

The podspec was updated as so:
```
-  s.resource_bundle = { 'WordPressCom-Stats-iOS' => ['WordPressCom-Stats-iOS/**/*.storyboard', 'WordPressCom-Stats-iOS/**/*.xib', 'WordPressCom-Stats-iOS/**/*.otf', 'WordPressCom-Stats-iOS/**/*.png'] }
+  s.resource_bundle = { 'WordPressCom-Stats-iOS' => ['WordPressCom-Stats-iOS/*.storyboard', 'WordPressCom-Stats-iOS/*.xib', 'WordPressCom-Stats-iOS/*.otf', 'WordPressCom-Stats-iOS/Images.xcassets'] }
```

# Expected result
The idea was we would load assets using the newer methods on `UIImage` to load images named from a bundle.

# Actual result
The assets are not being compiled and included in the bundle at the end.
![2015-11-04_10-45-34](https://cloud.githubusercontent.com/assets/373903/10944959/30b2a5ae-82e1-11e5-9522-44561bf55849.png)

# Workaround
I worked with @orta a bit to see if we could come up with a solution that worked. We ended up coming up with a workaround that does function.

```
-  s.resource_bundle = { 'WordPressCom-Stats-iOS' => ['WordPressCom-Stats-iOS/*.storyboard', 'WordPressCom-Stats-iOS/*.xib', 'WordPressCom-Stats-iOS/*.otf', 'WordPressCom-Stats-iOS/Images.xcassets'] }
+  s.resource_bundle = { 'WordPressCom-Stats-iOS' => ['WordPressCom-Stats-iOS/*.storyboard', 'WordPressCom-Stats-iOS/*.xib', 'WordPressCom-Stats-iOS/*.otf'] }
+  s.resource = 'WordPressCom-Stats-iOS/Images.xcassets'
```
The problem with this, however, is that the assets are then compiled in the host application's main bundle in the Assets.car. We have to load images, then, by not specifying a bundle name. That's probably okay but the issue lies with all of our Storyboards breaking. We end up with a warning `Could not load the "icon-eye-16x16" image referenced from a nib in the bundle with identifier "(null)"` because the assets aren't in the same bundle with the storyboard.

I can come up with a simple demo project if that helps!

**Comment by neonichu** [comment]
Thanks for the detailed issue! An example project would be really helpful.

**Comment by astralbodies** [comment]
@neonichu - here's a demo project that shows the issue. 

https://github.com/astralbodies/PodsAssetsDemo

The project PodsDemo is a simple/useless Framework with a podspec. The subfolder PodsDemoApp contains an app that is consuming the podspec via local pods. The app bundle that is created does contain the PodDemo resource bundle but no xcassets are included.

**Comment by manuyavuz** [comment]
@astralbodies First of all thanks for clean explanation and the demo project!

I tested and verified the issue, and will tackle it soon. I'll inform you when fix is ready.

Cheers!

**Comment by astralbodies** [comment]
Happy to hear I presented the issue well :smile:. Let me know what I can do to help!

**Comment by manuyavuz** [comment]
@astralbodies, I've made the needed change, could to try CocoaPods from master if the issue is resolved for you?

**Comment by astralbodies** [comment]
@manuyavuz Looks like the issue was resolved! Thanks!!
