### ISSUE TITLE
Frameworks not buillt for UnitTests.

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4502]
For simulator iOS 9.0 on Xcode 7.1, I am having issues where the fremworks for the pods specified for my unit tests aren't in my dervied data.

This means I can build my app but not my tests. 

My podfile is:
    
    platform :ios, '8.0'
    use_frameworks!
    
    pod 'For both'
    
    target 'SupTests' do
          pod 'For Tests'
    end

I've also tried

My podfile is:
    
    platform :ios, '8.0'
    use_frameworks!
    
     pod 'For both'

     target 'Sup' do

     end
    
     target 'SupTests' do
           pod 'For Tests'
     end

When I tried this one below, it kept complaining about not finding my lock or manifest file even after a clean install:

    platform :ios, '8.0'
    use_frameworks!
    
   

     target 'Sup' do
          pod 'For both'
     end
    
     target 'SupTests' do
           pod 'For both'
            pod 'For Tests'
     end

**Comment by segiddins** [comment]
The bottom podfile is what you'll need at the moment. Try running cocoapods-deintegrate and then installing again.

**Comment by jcampbell05** [comment]
Seems to work for some of my schemes but not others.

**Comment by segiddins** [comment]
Can you share a project that demonstrates it not working? Thanks!

**Comment by neonichu** [comment]
Closing due to lack of response.
