### ISSUE TITLE
Running on device fails with "image not found" when Framework depends on Pods

### ISSUE THREAD

**Issue by vpdn** [CocoaPods/CocoaPods#4503]
**Environment**
CocoaPods version: 0.39.0
Xcode 7.1

**Description**
I created a new project and added a framework target (called OneFramework for this example).  The framework itself depends on a library that is integrated with CocoaPods. So the dependency chain is roughly like this: SomeLib <-- OneFramework <-- App

The project runs fine when the app runs in the simulator, but crashes on startup when it runs on a device.  The problem seems to be that the framework itself can't find the pod it depends on:

```
dyld: Library not loaded: @rpath/UIColor_Hex_Swift.framework/UIColor_Hex_Swift
  Referenced from: /private/var/mobile/Containers/Bundle/Application/A8434C2E-1221-49FA-B8D0-0E16AB020604/Captain.app/Frameworks/OneFramework.framework/OneFramework
  Reason: image not found
``` 

**Podfile**

```
platform :ios, '8.2'

use_frameworks!

target 'OneFramework' do
    pod 'UIColor_Hex_Swift', '1.4'
end
```

Here's also a link to the [sample project](https://www.dropbox.com/s/qf2x8bhk31qwkza/CaptainSampleProject.zip?dl=1).

**Comment by zhxnlai** [comment]
Just had the same issue here. `rm -rf ~/Library/Developer/Xcode/DerivedData/` works for me.

**Comment by neonichu** [comment]
see #4493

**Comment by vpdn** [comment]
@neonichu Thanks for the clarification, didn't know that frameworks aren't supported as targets.

In case someone has the same issue, my work around was now to:

- create a local pod spec for the framework (referencing other pods as dependencies)
- add that pod spec as a dependency to the main project.
- In the framework target, link the pods the framework depends on manually

**Podfile looks roughly like this:**

```
platform :ios, '8.2'

use_frameworks!
inhibit_all_warnings!

def modules
  pod 'MyAwesomeModule',  :path => "./Modules/MyAwesomeModule"
  pod 'AnotherModule', :path => "./Modules/AnotherModule"
end

target 'AppDev' do
  modules
end

target 'AppRelease' do
  modules
end
```

**Local Podspec**

```
Pod::Spec.new do |s|
  s.name         = "MyAwesomeModule"
  s.version      = "0.0.1"
  s.summary      = "..."

  s.author       = "Me"
  s.platform     = :ios
  s.platform     = :ios, "8.0"
  s.license      = "Proprietary"
  s.homepage     = "http://127.0.0.1"

  s.source       = { :git => "../.." }

  s.source_files  = "./**/*.{h,m,swift}"

  s.dependency 'SnapKit', '0.16.0'
  s.dependency 'RealmSwift', '0.96.2'
end
```

**Comment by neonichu** [comment]
@vpdn Thanks for the detailed solution :tada:
