### ISSUE TITLE
How do I include a static framework into Cocoapods ? 

### ISSUE THREAD

**Issue by thecritic** [CocoaPods/CocoaPods#4504]
I have a Cocoapods Swift framework which should include a static Objective-C framework. 

Here are the steps that I followed: 

1) Copied the framework to the following path: Pod/Frameworks/MyFramework.framework
2) Added this line to the spec file: 

    s.ios.vendored_frameworks = 'Pod/Frameworks/MyFramework.framework'

3) Added 'Pod/Frameworks' to the "Framework Search Paths" in the pod's build settings. 

When I try to include the Obj-C headers from the framework into my pods umbrella header like so:

    #import <MyFramework/SomeHeaderFile.h>

it gives me errors like this: 

"Include of non-modular header inside framework module 'MyPod'"

Is there any way I can fix this issue ?

**Comment by segiddins** [comment]
Can you please provide an actual project that demonstrates this issue? Thanks!

**Comment by thecritic** [comment]
@segiddins Hi Samuel, thanks for your help. 

Here is the example repo: https://bitbucket.org/melkhaiat/testlib

**Comment by thecritic** [comment]
@segiddins Were you able to resolve this error ?

**Comment by segiddins** [comment]
I haven't had a chance to look into this

**Comment by thecritic** [comment]
Oh, okay, yeah no worries!

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
