### ISSUE TITLE
ENABLE_TESTABILITY flag resets to NO after `pod update`

### ISSUE THREAD

**Issue by raphaeloliveira** [CocoaPods/CocoaPods#4505]
🌈
Hey guys, I'm developing my own pod and I created it using `pod lib create` so the project structure should be familiar. I have a couple of internal Classes on my pod that I'd like to test and therefore I'm making use of the new `@testable` available in Swift 2.0. The issue is every time I run `pod update` on my pod the `ENABLE_TESTABILITY` flag present on **Pods.xcodeproj/project.pbxproj** resets to `NO` which generates a compilation error (*Module 'MyModule' was not compiled for testing*). The modification is not persisted since **/Pods** is on **.gitignore**. Is this working as designed or is there a way to solve this?

**Comment by segiddins** [comment]
This should be fixed on master now, can you give it a try?

**Comment by raphaeloliveira** [comment]
I'm sorry for the probably silly question but how do I install the version on master?

**Comment by segiddins** [comment]
You can either do `gem install beta-pod` and `beta-pod master install` or try following https://guides.cocoapods.org/using/unreleased-features.html.

**Comment by raphaeloliveira** [comment]
Yep, working on `master`. Thanks!
