### ISSUE TITLE
file not found / include of modular header in Xcode 7.0.1 through 7.2beta2

### ISSUE THREAD

**Issue by timbodeit** [CocoaPods/CocoaPods#4507]
This issue is similar to #4420, but most likely not the same issue (as the regression commit has been merged into master later than #4420 was reported). Though some peoples findings in #4420 might be because of this issue and not because of #4420 itself.

---

In one of my projects, where we are using RestKit in a Swift/ObjC mixed framework, I am getting numerous error like the following:
```
error: include of non-modular header inside framework module 'RestKit.ObjectMapping'
#import "RKObjectMapping.h"
        ^
```

This seems to be a regression in ce442f4ab004861ba32eceb9b91a0a53cf753e12 by @segiddins. 
When using 4738e9c2863c9222b2676e7699a59407d2386779 to run `pod install` the project builds fine.

---

I tried to create an example project to show this behavior, but after 4 hours of trying I could not get it to throw the same exact same error.
However the symptoms in the example project are very similar: The build fails, but instead of complaining about `non-modular imports`, it throws errors like this:
```
error: 'RKObjectMapping.h' file not found
#import "RKObjectMapping.h"
        ^
```

The errors in the example project are thrown on the exact same lines, on the exact same file imports, that my other project with the same dependency is throwing `non-modular import` errors.

I created [the example project](https://github.com/timbodeit/CocoaPodsBugExampleProject) by: 
- Creating a new single view application with Swift
- `pod init`
- Add `use_frameworks!` and `pod 'RestKit'
- Add `import RestKit` to a Swift file in the Project.

I included a travis file, that build the example project with the following matrix:
- CocoaPods
  - `BAD` ce442f4ab004861ba32eceb9b91a0a53cf753e12
  - `GOOD` 4738e9c2863c9222b2676e7699a59407d2386779
  - `CANDIDATE` `seg-no-framework-build-headers`
- Xcode
  - 7.0.1
  - 7.1
  - 7.2 beta 1

CocoaPods  | Xcode 7.0 | Xcode 7.1 | Xcode 7.2 beta 1 
---------------- | -------------- | ------------- | ------------------------
`GOOD` | ✅ | ✅ | ✅
`BAD` | ❌ | ❌ | ❌
`CANDIDATE` | ❌ | ❌ | ❌

You can find the Travis Build here: https://travis-ci.org/timbodeit/CocoaPodsBugExampleProject/builds/89480559

Unfortunately `seg-no-framework-build-headers` does not fix my problem.

**Comment by segiddins** [comment]
RestKit is what's broken here, I'm 99% sure, since I've spent a bunch of time trying to fix it.

**Comment by timbodeit** [comment]
Ok, if the RestKit podspec explicitly asked for the header structure to be preserved, there's nothing that CocoaPods can do about it. 

It seems to me though, that header_mappings_dirs isn't documented anywhere. A Google search only finds the CHANGELOG. And the [Podspec Syntax Reference](https://guides.cocoapods.org/syntax/podspec.html) doesn't mention it either.

What exactly does this attribute do?
