### ISSUE TITLE
Cocoapods 0.39.0, the resources of s.resource_bundles cannot be copied if the resource directory contains sub-directories

### ISSUE THREAD

**Issue by iwill** [CocoaPods/CocoaPods#4510]
BBSFramework.podspec:
```ruby
s.resource_bundles = {
    "BBSFramework" => ["BBSFramework.bundle/*"]
}
```

BBSFramework.bundle/:
Three are some images and some sub-directories in `BBSFramework.bundle/`;

pod install:
All images cannot be copied;

But Cocoapods `0.38.2` works fine;

**Comment by neonichu** [comment]
Please clarify more what is happening. Are you receiving any error messages for the images? If possible, share an example which exhibits the issue.

**Comment by iwill** [comment]
I cannot clarify it in English and it seems OK now .... so, forget it.
