### ISSUE TITLE
Cocoapods 0.39 drops header_dir requirement in xcconfig

### ISSUE THREAD

**Issue by levigroker** [CocoaPods/CocoaPods#4513]
With Cocoapods 0.38.2 and the CorePlot 1.6 podspec, the resulting `Pods.<target>.xcconfig` would contain the following in the `HEADER_SEARCH_PATHS` (and similar `osx` references in the file).

    "${PODS_ROOT}/Headers/Public/CorePlot" "${PODS_ROOT}/Headers/Public/CorePlot/osx"

With Cocoapods 0.39 and the CorePlot 1.6 podspec, the resulting `Pods.<target>.xcconfig` no longer contains the `osx` references which result in a `"CorePlot.h" file not found.` build error.

Looking at the CorePlot 1.6 podspec it clearly specifies the header directory:

    s.osx.header_dir = 'osx'

and, as mentioned, this worked in 0.38.2, but is now broken in 0.39.

**Comment by segiddins** [comment]
This was an intentional change in 0.39 -- core plot may need to be updated.

**Comment by levigroker** [comment]
Can you comment on what that update might entail please?

**Comment by segiddins** [comment]
It'll probably entail making sure all import use fully qualified paths. As for `header_dir`: https://guides.cocoapods.org/syntax/podspec.html#header_dir.

**Comment by levigroker** [comment]
Thanks... though, I *did* read that before filing this. It's not clear, to me, what that means in practice. Perhaps an example would be helpful.

**Comment by segiddins** [comment]
To be honest, I'm not sure either. Best bet is probably to read the code / help update the guides :/

**Comment by levigroker** [comment]
Hmm. Can you provide information about why this was an intentional change?

**Comment by segiddins** [comment]
Because the old way made it impossible to compile certain libraries. The new way can be worked around.
