### ISSUE TITLE
UIRequiredDeviceCapabilities is now also required for frameworks info.plist for tvOS apps

### ISSUE THREAD

**Issue by marcvanolmen** [CocoaPods/CocoaPods#4514]
hi,

We had issues submitting our 1st update for our tvOS app, it looks Apple added an extra requirement since last week, since we submitted our first tvOS app.

ERROR ITMS-90502: "Invalid Bundle. Apps that only contain the arm64 slice must also have 'arm64' in the list of UIRequiredDeviceCapabilities in Info.plist

https://forums.developer.apple.com/thread/25411

We discovered that the frameworks, info.plist (not just the app info.plist) now also need the key UIRequiredDeviceCapabilities and the devices supported.

After we manually updated all the info.plist and added the UIRequiredDeviceCapabilities to all the pods info.plist in the build settings, rebuild the app and resubmitted our app was accepted.

Marc

**Comment by segiddins** [comment]
That sounds like an iTC issue to me? Could you try filing a radar about that?

**Comment by marcvanolmen** [comment]
Sure I will file a radar, I hope this doesn't become a requirement.. neither..

**Comment by bassrock** [comment]
Seems to be a change on ITC, as it is still valid as of this comment and a thread https://forums.developer.apple.com/message/85053

**Comment by bassrock** [comment]
Also for the time being is this possible via a post install hook?
