### ISSUE TITLE
tvOS and iOS framework

### ISSUE THREAD

**Issue by mlloyd** [CocoaPods/CocoaPods#4521]
I have a project which has a core framework, across tvOS and iOS platform, but I'm getting the

is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.

https://github.com/mlloyd/PodExample_tvos_ios_bug

**Comment by segiddins** [comment]
Thanks, think I finally have a fix for this one.
