### ISSUE TITLE
Header Search Paths not respected per target

### ISSUE THREAD

**Issue by colinhumber** [CocoaPods/CocoaPods#4522]
This was apparently fixed in #1249, but it seems to have popped up again, unless I'm totally missing something.

I'm currently using version 0.39.0. My Podfile is setup as below (this is just an example project to illustrate the issue):

```ruby
platform :ios, "8.0"

target :PodTest do
    pod 'KissXML'
end

target :PodTest2 do
    pod 'OAStackView'
end
```

The `PodTest` target includes the KissXML headers, as expected, as well as links to libXML. However, the `PodTest2` target also includes the KissXML header in the HEADER_SEARCH_PATHS in the .xcconfig, as below.

```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/KissXML" "${PODS_ROOT}/Headers/Public/OAStackView"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/KissXML" -isystem "${PODS_ROOT}/Headers/Public/OAStackView"
OTHER_LDFLAGS = $(inherited) -ObjC -l"OAStackView"
PODS_ROOT = ${SRCROOT}/Pods
```

**Comment by segiddins** [comment]
This is currently the intended behavior, and it will be rectified once he Podfile DSL refactor is completed.

**Comment by colinhumber** [comment]
Great, thanks for the quick response!
