### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by raffaelps** [CocoaPods/CocoaPods#4528]
Hello,

I'm using the cocoapods v0.39.0 and i get this error when build the .xcworkspace project:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AFHTTPRequestOperation", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in ImageCache.o
      objc-class-ref in MenuView.o
  "_OBJC_CLASS_$_AFImageResponseSerializer", referenced from:
      objc-class-ref in ImageCache.o
  "_OBJC_CLASS_$_AFJSONResponseSerializer", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in MenuView.o
  "_OBJC_CLASS_$_GADBannerView", referenced from:
      objc-class-ref in ViewView.o
      objc-class-ref in FavoritosView.o
      objc-class-ref in HistoricoView.o
      objc-class-ref in ComprasView.o
      objc-class-ref in CompartilharView.o
  "_OBJC_CLASS_$_GADRequest", referenced from:
      objc-class-ref in ViewView.o
      objc-class-ref in FavoritosView.o
      objc-class-ref in HistoricoView.o
      objc-class-ref in ComprasView.o
      objc-class-ref in CompartilharView.o
  "_OBJC_CLASS_$_RNActivityView", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_SWRevealViewController", referenced from:
      objc-class-ref in AppDelegate.o
  "_kGADAdSizeBanner", referenced from:
      -[ViewView initWithFrame:] in ViewView.o
      -[FavoritosView initWithFrame:] in FavoritosView.o
      -[HistoricoView initWithFrame:] in HistoricoView.o
      -[ComprasView initWithFrame:] in ComprasView.o
      -[CompartilharView initWithFrame:] in CompartilharView.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Someone help me?
Thanks

**Comment by segiddins** [comment]
Please follow the instructions in the contributing guidelines. This isn't enough to debug an issue, please share a project that reproduces the issue. Thanks!

**Comment by pikaboo** [comment]
@raffaelps check that this isnt your error: https://github.com/CocoaPods/CocoaPods/issues/4562

**Comment by raffaelps** [comment]
Thanks @pikaboo

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
