### ISSUE TITLE
Redefinition error after updating to 0.39.0

### ISSUE THREAD

**Issue by Claus79** [CocoaPods/CocoaPods#4530]
I updated cocoapods to version 0.39.0 and I now I get a lot of redefinition error in SDWebImageDownloader.h
For the records this are the pods I'm using:

Using AFNetworking (1.3.4)
Using ChameleonFramework (2.0.4)
Using Crashlytics (3.4.0)
Using DZNEmptyDataSet (1.7.2)
Using ECSlidingViewController (2.0.3)
Using Fabric (1.6.0)
Using FontAwesomeKit (2.2.0)
Using GoogleAnalytics (3.14.0)
Using Heap (2.2.1)
Using ISO8601DateFormatterValueTransformer (0.6.1)
Using RKValueTransformers (1.1.2)
Using RMMapper (1.1.5)
Using RestKit (0.25.0)
Using SDWebImage (3.7.3)
Using SOCKit (1.1)
Using SVProgressHUD (1.1.3)
Using SwipeView (1.3.2)
Using TLYShyNavBar (0.9.8)
Using TTTAttributedLabel (1.13.4)
Using TransitionKit (2.1.1)
Using UIActivityIndicator-for-SDWebImage (1.2)
Using iRate (1.11.4)

**Comment by segiddins** [comment]
Can you please share a project that reproduces this issue? Thanks!

**Comment by Claus79** [comment]
I have just fixed it removing one library import from my .pch file. Thanks
