### ISSUE TITLE
Slow app launch with many embedded libraries for swift projects

### ISSUE THREAD

**Issue by pgherveou** [CocoaPods/CocoaPods#4532]
I found this ticket on apple forum that describe exactly an issue we are having in our app  https://forums.developer.apple.com/message/82399#82399

> Hi, recently got an issue that after adding some amount of pods app starts to launch very slow.
> (it's similar to this one http://stackoverflow.com/questions/31080284/adding-several-pods-increases-ios-app-launch-time-by-10-seconds)
> This issue always reproducible on iPhone 5, but not on iPad mini 2.
>  
> While i'm using 5 pods - app launches very fast in around 1 second. But once i add one more pod (any pod) - it became to launch in 10+ seconds.

When printing logging info in Xcode Device window, we can see a lot of 
```
<Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
```

Any idea what's going on here ?

**Comment by segiddins** [comment]
What leads you to think this is a cocoapods specific issue?

**Comment by neonichu** [comment]
This is probably the best discussion about this problem: artsy/eigen#586

**Comment by pgherveou** [comment]
Yep thanks for the link
