### ISSUE TITLE
ORGANIZATIONNAME Key is reset after pod update

### ISSUE THREAD

**Issue by raphaeloliveira** [CocoaPods/CocoaPods#4533]
🌈I'm creating my pod and every time I run `pod install` it wipes the `ORGANIZATIONNAME` key on `project.pbxproj` used on the header comments of each new file. Is this a bug?

<img width="258" alt="organization" src="https://cloud.githubusercontent.com/assets/2700131/11105651/65fbe0ec-8924-11e5-9c9a-52d73753b8a8.png">

**Comment by segiddins** [comment]
In which project file? Can you attach a project we can use to reproduce the issue? Thanks!

**Comment by raphaeloliveira** [comment]
The file is **Pods.xcodeproj/project.pbxproj** on section
```
/* Begin PBXProject section */
		D41D8CD98F00B204E9800998ECF8427E /* Project object */ = {
			isa = PBXProject;
			attributes = {
				LastSwiftUpdateCheck = 0700;
				LastUpgradeCheck = 0710;
				ORGANIZATIONNAME = MyOrganization;
			};
```
If I run `pod install` `ORGANIZATIONNAME` becomes empty.
Just to reiterate, it's a development pod.
Will upload an example project soon.

**Comment by segiddins** [comment]
I don't think we ever set the organization name, iirc it walkways shouldn't be in the project.

**Comment by raphaeloliveira** [comment]
Here you have it: https://github.com/raphaeloliveira/ExampleProject. Sorry for the delay.

Basically if you change the Organization and run `pod update` it will override it.

**Comment by segiddins** [comment]
Yeah, it's intentional that the pods project not be edited by the user.

**Comment by raphaeloliveira** [comment]
I see, just boring to have to manually add the company copyright but it's ok. Thank you!

**Comment by orta** [comment]
If you have to add it, it's probably worth automating inside a Podfile `post_install` hook.
