### ISSUE TITLE
Podfile.lock checksum behavior

### ISSUE THREAD

**Issue by justinseanmartin** [CocoaPods/CocoaPods#4535]
#3999 introduced a checksum in the Podfile.lock. I have two things to call out for this:

1. This doesn't fail the `pod install` action if the Podfile.lock doesn't match the existing checksum, which I would expect it to. Otherwise, what is the point of having the checksum in the lockfile if it doesn't break anything on being dirty?
2. This causes issues in our workflow on merging an upstream change into a branch that also has changes in the Podfile. In this case, the result of the merge will generate a different checksum, which means the lockfile will be left dirty for the next person to run `pod install` on the merged result.

This behavior seems unnecessary to me in general, because you already have source control keeping track of changes in the Podfile. If it is definitely staying, can we opt out of it in the Podfile somehow?

Let me know if you want to break this out into two issues.

CC: @segiddins @Ashton-W @neonichu @amorde

**Comment by segiddins** [comment]
No, the way it works is as intended. It's so the check manifest script build phase can also account for changed options in the podfile

**Comment by justinseanmartin** [comment]
Thanks for the prompt response. I understand that it is behaving the way you intended, but it is problematic in our workflows, so I'd like to understand a bit more.

I don't understand the use case for the guarantee the checksum gives. Is it that the podfile is the same between `pod install` time and build time? For any Podfile changes, a user will need to "pod install" again to get an updated Podfile.lock? Otherwise, we'll end up with dirty workspaces on other developers machines after a `pod install`.

Does the workflow issues (#2 above) that I called out make sense? Do you have a recommendation for how to mitigate this? Potentially, we'd run a PR on the post-merge target and reject the commit before it is merged upstream to master (e.g. unbreakable workflow). That has its own set of tradeoffs however.

Can you explain why an additional piece of metadata that can't be `git merge`d needs to be added to the `Podfile.lock` that validates the `Podfile` in the same folder hasn't changed? Thanks!

**Comment by segiddins** [comment]
It's no different than any other piece of metadata in the lockfile, with regard to merges...

**Comment by Ashton-W** [comment]
What changes to the `Podfile` are you merging in your workflow? If any pods or their configuration changes, your local pods are now out of date. Are you tracking `Podfile.lock` in git?

**Comment by justinseanmartin** [comment]
@segiddins - This came up on a PR where the source branch hadn't bumped to Cocoapods master yet, which is why it didn't generate a merge conflict. In the normal case, you're right that it would be surfaced as a merge conflict and require a rebase, which is reasonable. The unfortunate thing is that the merge conflict seems unnecessary to me if the Podfile can be cleanly merged.

@Ashton-W - Yes, we commit the Podfile.lock in git, because we lock our dependencies to a specific version and only bump individual dependencies when needed. This is a necessity for bumping only a transitive dependency that isn't explicitly used in the top level project, but has a bug fix that is necessary for a given release.

**Comment by segiddins** [comment]
@justinseanmartin again, that could happen with any part of the lock file, and there's nothing really we can do about that.

**Comment by neonichu** [comment]
@justinseanmartin The idea of the checksum in the `Podfile.lock` is to be able to check the integrity of the sandbox, e.g. when someone adds `use_frameworks!` to the `Podfile`, now the "Check Pods Manifest.lock" build phase will fail in case no `pod install` has happened since then.

**Comment by justinseanmartin** [comment]
@neonichu - Got it, that makes sense, it is when you've made a change locally and you want to ensure that you re-run `pod install` so the settings take. That also makes sense as to why the checksum is being updated on `pod install` rather than `pod update`.

Now that I have more of an understanding of why we hit the issue, it will be a minor annoyance, but it won't generally break our workflow. The cause was from having a pull request that was still running 0.39.0, but also making changes to the Podfile merge, which then changed the checksum in master after the merge, which leaves git dirty after pod install. Soon, all of our PRs will be using the newer version of Cocoapods, so it'll generate a conflict before merging.

Would it be reasonable to have this written to the `Manifest.lock` but not the `Podfile.lock`? We don't check in our `Pods` folder. I don't know how crazy/bad of an idea that is.

**Comment by neonichu** [comment]
@justinseanmartin that wouldn't work, because we rely on the fact that we can check the integrity of the sandbox by comparing `Podfile.lock` against `Manifest.lock`. If the checksum would only be in one, the check wouldn't make sense anymore (also the way we do the check would break as it assumes both files are identical).

**Comment by justinseanmartin** [comment]
Oh, yep, they're just raw diffed against each other, so it would take some extra work for that to live outside of the Podfile.lock.

I'm going to close this issue, as the initial reaction was from the conversion to having the checksum added. It'll be less painful now that nobody should have a local Podfile.lock without a checksum.
