### ISSUE TITLE
Pod in custom source failing linter

### ISSUE THREAD

**Issue by MaxGabriel** [CocoaPods/CocoaPods#4536]
:rainbow: 

I have a custom Cocoapods source at https://github.com/Heyzap/CocoapodsSource. A new podspec I've added (`HZInMobi/5.0.2`) is failing the linter with:

```
 -> HZInMobi (5.0.2)
    - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `vendored_libraries` pattern did not match any file.
```

Here's the full output of `pod spec lint --verbose --no-clean` [as a gist](https://gist.github.com/MaxGabriel/83e08c0b1ae20a1e62ea).

I've dropped `binding.pry` around the Cocoapods source and found that the `curl` and `unzip`s succeed. However, in the project directory that Cocoapods creates, none of the files from the zip file are present (here's the [tree output](https://gist.github.com/MaxGabriel/51c99fff419ccd759e58)).

I'm fairly sure the Podspec is correct, especially because a nearly identical one (`HZInMobi/5.0.1`) passes the linter just fine. It's possible I've just made a mistake in the Podfile, but after significant time debugging and a coworker taking a look I can't find anything wrong, and thought there could be a bug in Cocoapods.

Steps to reproduce:

```
git clone https://github.com/Heyzap/CocoapodsSource.git
cd CocoapodsSource/Specs/HZInMobi/5.0.2
pod spec lint --verbose --no-clean
```

**Comment by segiddins** [comment]
Try adding the `:flatten => true` option to the source in the podspec

**Comment by MaxGabriel** [comment]
Here's the output with `:flatten => true` added to the `source`: https://gist.github.com/MaxGabriel/2a8b75cfbbdc0d59245f

```
s.source           = { :http => "https://s3.amazonaws.com/hz-sdk/third-party/inmobi/inmobi-#{s.version}.zip", :flatten => true }
```

**Comment by segiddins** [comment]
¯\_(ツ)_/¯ in that case, you'll need to prefix the paths in your spec with `Lib`, since that's how your zip expands.

**Comment by neonichu** [comment]
The `:flatten` option only works if there's one top-level folder, IIRC — I guess the `__MACOSX` prevents it in this case.

**Comment by MaxGabriel** [comment]
I changed to zipping the file from the command line (`zip -r file.zip sourceFolder`) and added the `:flatten => true` option and the podspec is validating successfully. Previously I was zipping using the OS X Finder right click -> compress option, which I guess started adding the `__MACOSX` thing?
