### ISSUE TITLE
[cocoapods.org] Pod spec link is invalid for current version

### ISSUE THREAD

**Issue by michaelochs** [CocoaPods/CocoaPods#4541]
Summary:
The link on cocoapods.org for the XMLDicrionary pod links to an invalid pod spec file. From my understanding this shouldn't happen as both, the pod spec and the cocoa pods page should be updated by publishing a pod release to the trunk.

Steps to reproduce:
- Go to https://cocoapods.org/?q=XMLDictionary
- In the right click on 'See Podspec'

Expected behaviour:
You see the pod spec of the current version (2.0.0) for this pod spec like for other pods

Actual behaviour:
You are directed to a 404 github page.

Notes:
Changing the URL of the link from https://github.com/CocoaPods/Specs/blob/master/Specs/XMLDictionary/2.0.0/XMLDictionary.podspec.json to https://github.com/CocoaPods/Specs/tree/master/Specs/XMLDictionary shows that the versions are present up to 1.4.0, however github also shows an error saying 'Failed to load latest commit information.'

**Comment by orta** [comment]
I think you weren't giving it enough time, it's working fine for me: 
![screen shot 2015-11-13 at 8 21 55 am](https://cloud.githubusercontent.com/assets/49038/11146830/abbaaa08-89df-11e5-8a6b-47de19fad0d8.png)

**Comment by michaelochs** [comment]
@orta This is the screenshot from cocoapods.org. Did you also follow step 2 of my steps and clicked on the 'See Podspec' link?

**Comment by orta** [comment]
Interesting, looks like someone must have deleted the pod in the Specs repo, making the trunk database out of sync :-/

**Comment by orta** [comment]
I've deleted the 2.0.0 version from the trunk db, and now it settles on 1.4 - thanks for the reminder that I wasn't reading the issue correctly

![screen shot 2015-11-13 at 8 56 18 am](https://cloud.githubusercontent.com/assets/49038/11147530/7af805be-89e4-11e5-9f39-c9fe15eb0c59.png)

**Comment by orta** [comment]
it will show in search as 2.0.0 for a while, but will eventually move back down to 1.4.0

**Comment by michaelochs** [comment]
That's what I thought, too. But how is that possible? I thought you can only push new versions. The reason why I opened that issue is basically: Is there a bug in cocoa pods that could cause versions to be removed?

**Comment by michaelochs** [comment]
I think there should be some way of the website noticing this, as I guess this is not the only pod that probably has the issue. I stumbled up on this by accident...

**Comment by orta** [comment]
if there's a critical reason, we allow deletions via the Specs repo PRs, but we end up with stuff like this to deal with later.

**Comment by orta** [comment]
its a political bug, not a cocoapods/cocoapods.org one ( though both of these can help alleviate the issue; https://github.com/CocoaPods/trunk.cocoapods.org/pulls )

**Comment by michaelochs** [comment]
Okay, thanks for the clarification! :+1:
