### ISSUE TITLE
Cannot update pod

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#4543]
Fabric told me to update Crashlytics from 3.3.4 to 3.4.0. My Podfile does not specify the version of Crashlytics so I run update directly as:

```
pod update 'Crashlytics'
```

Output:

```
[...]

Using Crashlytics (3.3.4)

[...]
```

Pod file:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'Fabric'
pod 'Crashlytics'
```

Using CocoaPods 0.39.0.

**Comment by segiddins** [comment]
you'll have to run `pod update Fabric` since Fabric has a dependency upon Crahslytics

**Comment by orta** [comment]
Or include both if you want to be super specific: `pod update Fabric Crashlytics`

**Comment by pronebird** [comment]
Thanks guys! That was it!
