### ISSUE TITLE
Pod project warnings in pch & umbrellas when -Wauto-import is activated

### ISSUE THREAD

**Issue by bithavoc** [CocoaPods/CocoaPods#4549]
When a Podspec activates `-Weverything` it naturally activates `-Wauto-import`, which means that the target Pod project should not use `#import` but `@import ` in headers(PCH and Umbrellas).

I fixed it in my rainforest by changing `Pod::Generator::Header` as follows:

```rb
      def generate_platform_import_header
        case platform.name
        when :ios then "@import UIKit;\n"
        when :tvos then "@import UIKit;\n"
        when :osx then "@import Cocoa;\n"
        else "@import Foundation;\n"
        end
      end
```

This of course breaks all the test integration specs in Cocoapods.

I believe `Pod::Generator::Header` should be able to generate both kind of imports in the headers(PCH & Umbrellas), so in my limited knowledge of this source code two solutions come to my mind:

* **A:** use `@import` in headers when `use_frameworks!` is enabled, this would work fine when integrating with target projects(`pod install`), however, I believe `pod lib lint` and `pod spec lint` would fail since the verification project doesn't use `use_frameworks!` by default.
* **B:** use `@import` automatically in headers when `spec.ios.deployment_target > '8.0'; spec.osx.deployment_target > '10.9'`. This would fix it for both target projects and `pod lint`.

Thoughts?

**Comment by segiddins** [comment]
B won't work if the user has modules disabled. It should be fine to use modular imports for frameworks, but I really don't see the benefits of a podspec specifying extra warnings.

**Comment by bithavoc** [comment]
I activated `-Weverything` so the compilation of the Pod source code to run the Test suite of my Pod throw me compilation errors(in combination with `-Werror`) in CI before I accept pull requests.

This way I don't find surprising warnings in my code when I try do to `pod trunk push`.

**Comment by segiddins** [comment]
No need to inhibit warnings, linting will show all normally enabled warnings.

**Comment by bithavoc** [comment]
yes, it will. but by default Pod install wouldn't throw me compilation errors of for example, nullability, etc. pod lint does, which is a pain in the ass because I only realize of these issues when I do `pod spec lint` which is usually before `pod trunk push`.

Point is, there is a flag to force the developer activate warning strictness and I'd like to use it in my Pod.

Any tips?

**Comment by segiddins** [comment]
Not really, but I personally run `pod lib lint` on CI for my pods.

**Comment by bithavoc** [comment]
ok cool, how do I increase the warning levels of `pod lib lint`?

**Comment by bithavoc** [comment]
anyone?

**Comment by neonichu** [comment]
The easiest solution for you is probably to use `-Weverything -Wno-auto-import` (untested)

**Comment by bithavoc** [comment]
Can't do -Wno, there is an special rule in cocoapods that forbids you from disabling warnings.

**Comment by bithavoc** [comment]
@neonichu @segiddins how about this? We either figure out to disable the restriction that forbids you from disabling warnings or fix the specific case of `-Wauto-import` by generating `@import` in the headers only when `use_frameworks!` is activated. this would also mean **pod linting** would automatically enable `use_frameworks!` in the verification project when iOS min target is 8.0.

It sounds like we should allow disabling warnings so I can use `-Wno-auto-import`, it'd be easier.

**Comment by neonichu** [comment]
You can just inject those flags into the Pods project using a `post-install` hook in the Podfile of your Example project, I see no need to have them included in the podspec itself, especially as that would break non-framework integration of it for no good reason.

**Comment by bithavoc** [comment]
@neonichu what should I be doing in `post-install`?

**Comment by adamhrz** [comment]
What about wrapping the umbrella with ignore code:
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wauto-import"

#import <UIKit/UIKit.h>

#pragma clang diagnostic pop
```

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
