### ISSUE TITLE
Deployment target is set incorrectly

### ISSUE THREAD

**Issue by mlloyd** [CocoaPods/CocoaPods#4552]
Testing on cocoapods master, commit 0f3eb52b3ec9a27635f872b53c5b5f99d5148447

Testing a previous issue, I've noticed that the deployment targets are not being set correctly.
![screen shot 2015-11-17 at 12 30 40](https://cloud.githubusercontent.com/assets/2125109/11211384/ffd4a658-8d26-11e5-99dc-441a9d7e06ed.png)

The issue is present here in this sample project;
https://github.com/mlloyd/PodExample_tvos_ios_bug

**Comment by segiddins** [comment]
Please verify if https://github.com/CocoaPods/CocoaPods/pull/4537 fixes this for you.

**Comment by mlloyd** [comment]
Yes works great thanks for the quick reply.

**Comment by mlloyd** [comment]
@segiddins Did this get merged into master?

**Comment by segiddins** [comment]
No, it hasn't been merged yet, as the PR is still open.
