### ISSUE TITLE
Can't open xcworkspace

### ISSUE THREAD

**Issue by KamingInWork** [CocoaPods/CocoaPods#4554]
My project named Jessica&Kaming, after pod init, i can't open workspace. It warn me that project's name shouldn't contain '&' and suggest me to submit a new issue here.

**Comment by KamingInWork** [comment]
Complement:After change my project named which not exit '&' or other special symbol , it can work!

**Comment by segiddins** [comment]
What version of CocoaPods are you using? I think we might've fixed this recently -- if not, it's possible that it's fixed on master?

**Comment by KamingInWork** [comment]
My cocoapods version is 0.38.2.

**Comment by segiddins** [comment]
Can you try with 0.39 or CocoaPods master? If not, sharing a project that reproduces the issue would be very helpful.

**Comment by KamingInWork** [comment]
Ok

**Comment by neonichu** [comment]
Closing because of lack of response.
