### ISSUE TITLE
Categories in vendor_library not linking?

### ISSUE THREAD

**Issue by themackworth** [CocoaPods/CocoaPods#4556]
I think I have hit the same thing as #4353 except for vendored_library.

I have a compiled static library that uses categories (L1).  I have another static library project (L2) that uses this library (L1)  and uses the category methods.  I then have an application that uses the source code of L2 via a podspec.  The podspec declares L1 as a vendored_library.  When I run the application, it crashes since it can't find the category in the vendored_library.  However, if I recompile L1 as a static framework and declare it as a vendored_framework in L2's podspec, the app doesn't crash.

https://github.com/themackworth/CocoapodsVendorStaticLib

There are two folders, work and nowork.  work uses a vendored_framwork and nowork uses a library.  WrapperProject represents L2 above, and DigestingProject is the application.

Running .39. Thank you :rainbow:

**Comment by gabrielafonsogoncalves** [comment]
hi @themackworth I have the same problem.

What did you do to make it work? I have a vendored_framework in my pod. My pod build and run but when I try to use an extension that is in the vendored_framework it crashes. Why did you do to make it work?

**Comment by themackworth** [comment]
@gabrielafonsogoncalves I am not sure why the vendored_framework isn't working you, as it works for me in .39.

However, in my actual project, I didn't switch to use a framework, but I did add `s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC' }` to my podspec which resolved the issue for me.  That might work for you temporarily.

**Comment by gabrielafonsogoncalves** [comment]
@themackworth thanks for your answer.

I think it doesn't work because it is a "fake" framework and I think Cocoapods is not linking it properly. I create another issue for that here https://github.com/CocoaPods/CocoaPods/issues/4619 

Also I tried adding `-ObjC` but it cause me other issues.

**Comment by segiddins** [comment]
@kcoleman731 want to look into this one?

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
