### ISSUE TITLE
ERROR | [iOS] unknown: Encountered an unknown error

### ISSUE THREAD

**Issue by MMasahito** [CocoaPods/CocoaPods#4559]
MacBookPro:SwipNavigationController m$ pod trunk push SwipNavigationController.podspec --verbose

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.
Validating podspec
    SwipNavigationController (1.0.0) - Analyzing on iOS 7.0 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `SwipNavigationController` from `/Users/mizokakimasahito/SwipNavigationController/SwipNavigationController.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A SwipNavigationController

Downloading dependencies

-> Installing SwipNavigationController (1.0.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/MMasahito/SwipNavigationController.git /var/folders/4l/3v8g8tld5n77qkg_2ft6s83r0000gp/T/d20151119-7548-1ldevoo --branch 1.0.0
     Cloning into '/var/folders/4l/3v8g8tld5n77qkg_2ft6s83r0000gp/T/d20151119-7548-1ldevoo'...
     fatal: Remote branch 1.0.0 not found in upstream origin

[!] Error installing SwipNavigationController
 -> SwipNavigationController (1.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/MMasahito/SwipNavigationController.git /var/folders/4l/3v8g8tld5n77qkg_2ft6s83r0000gp/T/d20151119-7548-1ldevoo --branch 1.0.0

Cloning into '/var/folders/4l/3v8g8tld5n77qkg_2ft6s83r0000gp/T/d20151119-7548-1ldevoo'...
fatal: Remote branch 1.0.0 not found in upstream origin
) during validation.

[!] The podspec does not validate.

**Comment by MMasahito** [comment]
Cause not sure

**Comment by segiddins** [comment]
Have you pushed your tag to GitHub yet?

**Comment by neonichu** [comment]
You haven't tagged the "1.0.0" release in your repo: <https://github.com/MMasahito/SwipNavigationController/tags> — so it cannot be checked out.

**Comment by sw0906** [comment]
version in spec is different from the release version
fix steps:
1. set the version number in spec
2. push to remote
3. add release at this commit
