### ISSUE TITLE
SSL issue when trying to install cocoapods on el captin

### ISSUE THREAD

**Issue by appwell** [CocoaPods/CocoaPods#4561]
hi i am trying to install the cocoapods on my newly udpdated el captian and i keep getting this error 

Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (https://rubygems.global.ssl.fastly.net/latest_specs.4.8.gz)

i have looked all the threads regarding this issue but i cant seem to be finding the answer i even installed BREW by mistake , im kindda new to all this as u can tell so pls if possible give me some steps

**Comment by appwell** [comment]
i even tryed using these codes to install : 

sudo nvram boot-args="rootless=0"; sudo reboot
sudo gem install cocoapods -V


![](http://i.stack.imgur.com/aaw8P.jpg)

**Comment by neonichu** [comment]
Sounds like there is some SSL issue in your RubyGems installation, maybe [this](http://ga.be/blog/2013/10/02/fixing-rubygems-ssl-issues-certificate-verify-failed/) can help. Another option is to use the OS X app as installation method instead: <https://github.com/CocoaPods/CocoaPods-app/releases/tag/0.39.0>

**Comment by appwell** [comment]
i used the app file and it seems to be working great thank u so much for ur solution
