### ISSUE TITLE
pod search cannot get the latest version 

### ISSUE THREAD

**Issue by dogvscat** [CocoaPods/CocoaPods#4563]
Cocoapods version is 0.39.0,and when i pod search Alamofire,below is what i get:
![screen shot 2015-11-20 at 10 51 34 am](https://cloud.githubusercontent.com/assets/13897335/11290761/b62faa34-8f74-11e5-8c9e-a41c0e2cc99c.png)

and Alamofire latest version is 3.0.1.

http://stackoverflow.com/questions/25985325/cannot-use-pod-search-sdwebimage-to-get-the-latest-sdwebimage-verison   

Any idea? Thanks.

**Comment by segiddins** [comment]
Try running pod repo update? Or use the --web flag?

**Comment by dogvscat** [comment]
@segiddins  those guys who can get latest version cocoapods version is 0.38.2, `gem list cocoapods` , i get 0.39.0 and 0.38.2, so i just `pod _0.38.2_ setup` 

![screen shot 2015-11-20 at 12 18 36 pm](https://cloud.githubusercontent.com/assets/13897335/11291898/36c6d364-8f81-11e5-868d-e9077d6f039b.png)

Now i can get the right version now,` pod repo update `waited a long time.
