### ISSUE TITLE
ld: framework not found AFNetworking clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by artiy** [CocoaPods/CocoaPods#4567]
In my project I got cocoapod installed. Here is the structure of Podfile

    platform :ios, '8.0'
    use_frameworks!
  
    workspace 'TempWorkspace'
    inhibit_all_warnings!

    target 'proj1' do

        pod 'ApplicationInsights', '1.0-beta.4'
        pod 'Google/Analytics'
        pod 'AFNetworking', '0.9.1'
        pod 'MBProgressHUD'
        pod 'Reachability'

    end

    target 'proj1Tests' do

    end
   
    target 'proj1UITests' do

    end

In this, ApplicationInsights and GoogleAnalytics pod are not creating any issues. But if I add any pod except these 2 in this file, this is giving me following error

"ld: framework not found AFNetworking clang: error: linker command failed with exit code 1 (use -v to see invocation)"

Its not just about AFNetworking only if I write any other pod name also then also it is giving me same error with that pod name.

I tried looking for pod limitations but not it has not given me anything relevant. Also after reading lot about cocoapod I can say that there an issue with configuration file but I am not able to understand what is that issue.

When I am writing pod 'MBProgressHUD' or any any except google and application insights pod it is not giving me any linking error but yes its is also unable to identify MBProgressHUD.h file inside bridging header file.

If somebody has any idea please tell me.

Thanks in advance!!!

**Comment by segiddins** [comment]
Can you please share a project we can use to investigate the issue? Thanks!

**Comment by artiy** [comment]
I am sorry but sharing you my whole project will create some issues on side. If you want to go through some code please let me know I can share that particular file with you.

**Comment by segiddins** [comment]
Could you reproduce the issue in a clean project then? Without something we can run, it's unlikely we'll be able to investigate the issue.

**Comment by artiy** [comment]
I am able to generate same issue again and  I have uploaded my full project on given
https://github.com/artiy/sampleWorkspace.git.

**Comment by artiy** [comment]
If I run proj1 and proj2 individually from their respective .xcworkspace file then this linking error is not coming. I think there must be some config issue because I am opening my project from common .xcworkspace file.

**Comment by CraigCottingham** [comment]
I had the same issue with CocoaPods 1.0.0.beta.6 and CocoaLumberjack. I originally filed an issue with them (see https://github.com/CocoaLumberjack/CocoaLumberjack/issues/715), but downgrading CocoaPods to 0.39.0 fixed it.

I can try recreating from scratch with a new project if that would be helpful.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
