### ISSUE TITLE
Dependency of a dependency, when both are development pods, creates separate Pods target for 2nd dependency in the main project

### ISSUE THREAD

**Issue by lemonkey** [CocoaPods/CocoaPods#4570]
**Question**: did the removal of :path from the podspec's dependency attribute ultimately make it impossible to have a dependency of a dependency, where both are development pods? I'm using CocoaPods v0.39 with use_frameworks! and iOS 8.0 because I need Swift support for both dependencies.

Here's my situation:

    Main
      pod1
        pod2

I have an iOS app (Main) that has a submodule development pod dependency (pod1) that also has its own submodule development pod dependency (pod2). Neither submodule dependencies can have their podspec hosted on a private or public specs repository and are purely submodule development pods.

Pod1's podspec has a dependency set for pod2 without a version set (`s.dependency 'pod2'`). Since we can no longer define the path for pod2's podspec in pod1's podspec, we have to include it before the sources defined in main's Podfile. If we didn't do this, running a `pod install` on the main Podfile will fail to find pod2's spec.

The path for pod2's podspec defined at the top of the main Podfile before the sources looks like:
`pod 'pod2', :path => './pod1/pod2'`

The rest of the main app's Podfile looks like (unrelated lines removed):

    platform :ios, '8.0'

    use_frameworks!

    target : 'MainApp' do
      pod 'pod1', :path => './pod1'
    end

    target : 'MainAppTests' do
      pod 'pod1', :path => './pod1'
    end`

What results is the following after `pod install` on main's Podfile:

    Integrating target `Pods` (`MainApp.xcodeproj` project)
    Integrating target `Pods-MainApp` (`MainApp.xcodeproj` project)
    Integrating target `Pods-MainAppTests` (`MainApp.xcodeproj` project)

Due to the first "Pods" target being created in the new Pods project that is part of the overall generated workspace, the MainApp target's project build configuration for debug and release is already set to Pods.debug.xcconfig and Pods.release.xcconfig. This causes the warning that is displayed just after the above output:

    [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `MainApp` to `Pods/Target Support Files/Pods-MainApp/Pods-MainApp.debug.xcconfig` or include the `Pods/Target Support Files/Pods-MainApp/Pods-MainApp.debug.xcconfig` in your build configuration.

    [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `MainApp` to `Pods/Target Support Files/Pods-MainApp/Pods-MainApp.release.xcconfig` or include the `Pods/Target Support Files/Pods-MainApp/Pods-MainApp.release.xcconfig` in your build configuration.

After opening the workspace, I can verify that while Pods-MainApp.debug.xcconfig and Pods-MainApp.release.xcconfig were generated under the Pods project `Target Support Files` folder, they couldn't be applied to the main app's target per the main app project build configurations because it is already set to Pods.debug.xcconfig and Pods.release.xcconfig.

In the Pods project, the build configurations for debug and release do include both the Pods target as well as MainApp and MainAppTests, with MainApp having Pods-MainApp.debug.xcconfig and Pods-MainApp.release.xcconfig files set. However, within these xcconfig files, they are missing the link to the pod2 dependency but they do link to pod1. Pods.debug and release xcconfig files only link to the pod2 dependency. 

The MainAppTests target in both the main app project and the Pods project has the correct xcconfig files for debug and release that link to both pod1 and pod2 dependencies. Note that if `:exclusive => true` were used when assigning pod1 to the targets, the MainAppTests target would NOT end up linking to the pod2 dependency per the xcconfig files.

Is this a known issue with development pod dependencies that have their own development pod dependencies ever since the :path parameter was no longer allowed in the podspecs? I don't think this is specific to use_frameworks! and besides, going back to using libraries isn't an option for me.

Pod2 is already a public pod (built via a separate job) that is a dynamic framework without the source files. I would prefer to be able to have it also be a development pod so that I could both modify the code in the same overall main app workspace as well as be able to step through its code.

Thanks!

**Comment by segiddins** [comment]
Can you try running `pod deintegrate` from https://github.com/CocoaPods/cocoapods-deintegrate? If that doesn't work, a project that reproduces the issue would be excellent!

**Comment by lemonkey** [comment]
You can find a sample project here: https://github.com/lemonkey/NestedDevelopmentPods

With my initial commit of Pod1 and Pod2 Cocoa Touch Frameworks that don't contain any classes yet (https://github.com/lemonkey/NestedDevelopmentPods/commit/159d201fee9ed7263c54a1a4786970fe0656833e) I am noticing that the xcconfigs generated for the Pods target do include both Pod1 and Pod2, where in my original project I was only seeing Pod2 being linked.  However, the `pod install` warning did appear and the Project configuration still has the wrong xcconfigs for the main target.

Once I add a sample class with public target header membership to both Pod1 and Pod2's umbrella header and do a `pod install` on Pod1 and then on Main, I do reproduce the issue detailed in my initial post.

`pod install` log for this sample project:
https://gist.github.com/lemonkey/384633ec75865504af8c

Workspace screenshot:
http://aribraginsky.d.pr/195hQ

Project configuration screenshot:
http://aribraginsky.d.pr/195hQ

Also, I am in a situation where I need to commit the Pods folders for my main app and its submodule development pods.

**Comment by lemonkey** [comment]
Now that I was able to reproduce the issue with a simplistic sample project, I'm going to try deintegrate on the main project.

**Comment by lemonkey** [comment]
Running `pod deintegrate` on Pod2, Pod1 and Main and then `pod install` on Main has the same incorrect outcome.

**Comment by lemonkey** [comment]
Looks like @orta doesn't think this is possible: https://twitter.com/orta/status/668415034301816832

**Comment by lemonkey** [comment]
It would be nice if one of the CocoaPod maintainers could verify this with my sample project.

**Comment by segiddins** [comment]
@lemonkey we certainly intend to look into it, but we all do this in our spare time -- it's incredibly hard to resolve all issues in the span of a day.

**Comment by lemonkey** [comment]
I understand, thanks for replying.

**Comment by freennnn** [comment]
@lemonkey what did you end up doing? I also have Pod1 -> Pod2 -> Pod3 hierarchy and trying to use submodules + cocoapods to organize those libraries.  The essential goal is to be able to develop/modify those libraries from within one main workspace. Did you switch to pure git submodules or carthage?

**Comment by lemonkey** [comment]
Submodules while using a private spec repo for the private podspec dependencies.  Make sure your private spec repo source is defined first in you app's Podfile.

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
