### ISSUE TITLE
subspec preserve_paths outside of header mappings dir

### ISSUE THREAD

**Issue by timbodeit** [CocoaPods/CocoaPods#4573]
When a Pod has `source_files` covered by `preserve_paths` that are located outside of its `header_mappings_dir`, the headers are copied to places they shouldn't go:

<img width="701" alt="screen shot 2015-11-22 at 15 40 04" src="https://cloud.githubusercontent.com/assets/4222754/11324610/db90dc62-9136-11e5-8452-f9bc6fc31ac6.png">

RestKit's podspec specifies:
```ruby
Pod::Spec.new do |s|
  # ...
  s.header_mappings_dir = 'Code'
  # ...
  s.subspec 'Support' do |ss|
    ss.source_files   = 'Code/RestKit.h', 'Code/Support.h', 'Code/Support'
    ss.preserve_paths = 'Vendor/LibComponentLogging/Core' # Preserved because they are symlinked
    # ...
  end
  # ...
end
```

`Code/Support/lcl_RK.h` -- symlinks to -> `Vendor/LibComponentLogging/Core/lcl_RK.h`

When installing RestKit, `lcl_RK.h` is copied with its path relative to the the `header_mappings_dir`.
This leads it to be positioned outside of the `PROJECT_HEADERS_FOLDER_PATH`:
<img width="912" alt="screen shot 2015-11-22 at 15 18 09" src="https://cloud.githubusercontent.com/assets/4222754/11324609/d871f822-9136-11e5-86ce-5cd3b0cb8bf8.png">

---

I'm not sure what the proper way to handle this is.
Shouldn't CocoaPods ensure that the copy location of framework headers is somewhere inside `$(PUBLIC_HEADERS_FOLDER_PATH)`?
Is using `preserve_paths` for a path outside the `header_mappings_dir` simply something that a Pod shouldn't do (Fully making this a RestKit issue)?

See also [RestKit#2360](https://github.com/RestKit/RestKit/issues/2360)

**Comment by neonichu** [comment]
I don't see the same problem here when integrating RestKit, are you using an older version of CP by any chance?

**Comment by timbodeit** [comment]
I was using e8e7e6035361df8ea51db8e86673067a7e248d9b from two days ago, together with RestKit `0.26.0` and Xcode 7.1. Updated to the current CocoaPods master and still seeing the same behavior.

I've added a .travis.yml to my test project and pushed it to GitHub.
https://travis-ci.org/timbodeit/RestKitTest
https://github.com/timbodeit/RestKitTest

**Comment by segiddins** [comment]
This has been fixed in RestKit, and the linter now warns when headers are outside of the header_mappings_dir.
