### ISSUE TITLE
Problem with installing cocoaPods from terminal

### ISSUE THREAD

**Issue by l800891** [CocoaPods/CocoaPods#4574]
When I run gem install cocoapods
I get following error messages:
Fetching: nap-1.0.0.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I looked into https://github.com/CocoaPods/CocoaPods/issues/792 and added a "sudo" before command:

I get:
Fetching: nap-1.0.0.gem (100%)
Successfully installed nap-1.0.0
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: minitest-5.8.3.gem (100%)
Successfully installed minitest-5.8.3
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-4.2.5.gem (100%)
Successfully installed activesupport-4.2.5
Fetching: molinillo-0.4.0.gem (100%)
Successfully installed molinillo-0.4.0
Fetching: cocoapods-try-0.5.1.gem (100%)
Successfully installed cocoapods-try-0.5.1
Fetching: cocoapods-stats-0.6.2.gem (100%)
Successfully installed cocoapods-stats-0.6.2
Fetching: cocoapods-search-0.1.0.gem (100%)
Successfully installed cocoapods-search-0.1.0
Fetching: xcodeproj-0.28.2.gem (100%)
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/xcodeproj

I am using OSX 10.11.1, Kindly help me for fixing the issues, thx in advance

**Comment by l800891** [comment]
Using the following command resolved this issue:

>sudo gem install -n /usr/local/bin cocoapods

**Comment by timelincoln7648** [comment]
thanks!

**Comment by JamesBream** [comment]
Thanks, +1 for adding this to docs?

**Comment by xiuyuwu** [comment]
thanks!

**Comment by piegandolfi** [comment]
Thanks!

**Comment by amigo1815** [comment]
Thanks! You save my day! +1 to docs

**Comment by Eddy-Rogier** [comment]
Thanks mate +1 too

**Comment by fsevgili** [comment]
Thanks!

**Comment by bibrahimbas** [comment]
Thanks 👍

**Comment by josepino** [comment]
Thanks!

**Comment by gautamBellare** [comment]
Awesome... thanks.. searched a lot for this and finally got through.

**Comment by vinodkalathiya** [comment]
Try with this following link. this link is clerify step by step description for install cocoapod

https://webappcodes.com/integarte-cocoapods-in-xcode-project-objective-c-or-swift

**Comment by DjKiDD** [comment]
This helped me!

**Comment by mohammadkalim** [comment]
Thanks it's worked

**Comment by NTJ3** [comment]
> sudo gem install -n /usr/local/bin cocoapods

Still having same problem


```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.

```

**Comment by blue492** [comment]
> > sudo gem install -n /usr/local/bin cocoapods
> 
> Still having same problem
> 
> ```
> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
> ```

Same issue for me also

**Comment by NTJ3** [comment]
> > sudo gem install -n /usr/local/bin cocoapods
> 
> Still having same problem
> 
> ```
> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
> ```

I solved this @blue492 by installing additional Ruby with RVM and then installed the `sudo gem install cocoapods`

My Mac has BigSur 11.6.3.
and Xcode has Version 13.2.1 (13C100)
