### ISSUE TITLE
CocoaPods Master Repo?

### ISSUE THREAD

**Issue by Spacelapp** [CocoaPods/CocoaPods#4578]
What happend to the master repo?

```javascript
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1

Cloning into 'master'...
error: RPC failed; result=18, HTTP code = 200
fatal: The remote end hung up unexpectedly
```

**Comment by aceontech** [comment]
+1

**Comment by neonichu** [comment]
Works fine here, also can't see any relevant :octocat: outage. If it turns out to be more than a random network problem, check out [this](http://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning/6849424#6849424) for ways to debug a `git clone` on your end.
