### ISSUE TITLE
Different Pods-Resources.sh per target

### ISSUE THREAD

**Issue by jaernouts** [CocoaPods/CocoaPods#4579]
Is it possible to have a different Pods-Resources.sh per target? I have two targets, targetA and targetB with both different pods, so there are two Pods-targetA and Pods-targetB folders beside the Pods folder in the Target Support Files... But when I change the path that's configured in the 'Copy Pods Resources' build phase, it's reset back to the original one (the general one, in the Pods folder) when I do a pod install again...

Any clue?

**Comment by segiddins** [comment]
The copy resources script is generated once per target in the Podfile. If that's not the case for you, please share a project that reproduces the issue. Thanks!

**Comment by jaernouts** [comment]
Yes, correct, that script is indeed created once per target, that's not the problem. The problem is that in my Xcode Project settings - Build Phases - Copy Pods Resources, the path is always reset to '"${SRCROOT}/Pods/Target Support Files/Pods/Pods-resources.sh"'... So it doesn't take the new ones into account...

**Comment by neonichu** [comment]
Could you please share your Podfile?

**Comment by segiddins** [comment]
@jaernouts can you try running `pod-deintegrate` and reinstalling?

**Comment by jaernouts** [comment]
@segiddins, thx, it's fixed now! Great to see such a fast response here on this team, keep up the good work!
