### ISSUE TITLE
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later

### ISSUE THREAD

**Issue by raylillywhite** [CocoaPods/CocoaPods#4581]
I have `platform :ios, '8.0'` in my Podfile, but when I run `pod install` using the latest cocoapods from master (currently `e547edd6b8de88e9323e83381e42c50808db796f`), I get the following warning for a bunch of my pods:

`ld: warning: embedded dylibs/frameworks only run on iOS 8 or later`

And the deployment target for the targets that are triggering the warnings are indeed below 8.0. Not sure if the answer is to bring those targets up to a deployment target of 8.0 or if the warning should just be removed as long as the main project's deployment target is high enough.

**Comment by segiddins** [comment]
Can you verify if https://github.com/CocoaPods/CocoaPods/pull/4537 fixes things for you?

**Comment by raylillywhite** [comment]
Yep, that fixes it! Thanks @segiddins — I tried looking for related issues but didn't see that one
