### ISSUE TITLE
Encoding::CompatibilityError - incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by Clear2** [CocoaPods/CocoaPods#4582]
My Podspec is

Pod::Spec.new do |s|
s.name             = "testpod"  
s.version          = "1.0.0"  
s.summary          = "test pod for my project"  
s.description      = <<-DESC  
It is a marquee view used on iOS, which implement by Objective-C.  
                 DESC  
s.homepage         = "https://github.com/Clear2/Testpod"  
s.license          = "MIT"
s.author           = { "zjx" => "12110331@qq.com" }  
s.source           = { :git => "/Users/zjx/Testpod/testpod",:tag => "1.0.0"} 
s.platform     = :ios, "5.0"
s.requires_arc = true
s.source_files = "testpod/**/*.{h,m}"  
end  

why I’m wrong

**Comment by Clear2** [comment]
I am getting the following error in my terminal:
### Error

```
Encoding::CompatibilityError - incompatible character encodings: ASCII-8BIT and UTF-8
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/standard_error.rb:88:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/linter.rb:36:in `rescue in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/linter.rb:32:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/validator.rb:32:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/validator.rb:32:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:154:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:154:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:153:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by neonichu** [comment]
What's the output of `locale` on your system?

**Comment by Clear2** [comment]
localhost:MyModel zjx$ pod spec lint

[!] The spec did not pass validation, due to 2 errors.


No why I error output,so I don't no how to resolve this

**Comment by neonichu** [comment]
`pod spec lint --verbose` might give more insight.

**Comment by Clear2** [comment]
Resolving dependencies of 
 -> MyModel (1.0.0)
    - ERROR | [OSX] unknown: Encountered an unknown error (Unable to find a specification for `Foundation` depended upon by `MyModel`) during validation.

Analyzed 1 podspec.


Thank you very much. I saw my mistake.

**Comment by developeryh** [comment]
the same error with you ,can you tell me how you resolve it?

**Comment by leandroBorgesFerreira** [comment]
I got the same error =/

**Comment by songhongkang** [comment]
the same error with you ,can you tell me how you resolve it?

help help

**Comment by NoneUnique** [comment]
you can see https://github.com/CocoaPods/CocoaPods/issues/2642 to solve it, your directory path has chinese characters,chang it to eng
