### ISSUE TITLE
single pod file with multiple projects in one workspace

### ISSUE THREAD

**Issue by artiy** [CocoaPods/CocoaPods#4585]
I've create a workpace and added two projects in it. The directory structure of my project is:

- root
 - testworkspace.xcworkspace
 - root/project1
   - root/project1/project1.xcodeproj
 - root/project2
   - root/project2/project2.xcodeproj

How can I've single podfile for both the projects? I created one pod file under project1 and manually moved it under root directory. Here is how pod file looks like.
```
workspace ‘testworkspace’

xcodeproj ‘project1/project1.xcodeproj’
target ‘project1’ do
pod 'testworkspace', :path => '.'
pod ‘AFNetworking’
end

xcodeproj ‘project2/project2.xcodeproj’
target ‘project2’ do
pod 'testworkspace', :path => '.'
pod ‘MBProgressHUD’
end
``` 

*pod install --verbose* gives me error: **Unable to find a target named `project1`**

**Comment by orta** [comment]
Offhand, not at a computer, I think you want to use the targets as scopes for the xcproject/workspaces. So something like this per target to integrate

```
target ‘project1’ do
   workspace ‘testworkspace’
   xcodeproj ‘project1/project1.xcodeproj’
   pod 'testworkspace', :path => '.'
   pod ‘AFNetworking’
end

```

**Comment by artiy** [comment]
tried above solution but its still giving me same issue as I specified in question.

**Comment by segiddins** [comment]
@artiy can you please share your modified podfile?

**Comment by artiy** [comment]
updated pod file is :
```
workspace 'testworkspace'

xcodeproj 'project1/project1.xcodeproj'

target 'project1' do

workspace 'testworkspace'
pod 'AFNetworking'
end

xcodeproj 'proj2/proj2.xcodeproj'

workspace 'testworkspace'
target 'proj2' do
pod 'MBProgressHUD'
end
```

**Comment by segiddins** [comment]
Try putting the `xcodeproj` directives inside the `target` blocks.

**Comment by artiy** [comment]
Solved my issue. Thanks a lot!!!

**Comment by mmsaddam** [comment]
```
platform :ios, '9.0'

workspace 'TestWorkSpace'
xcodeproj 'Project1/Project1.xcodeproj'
xcodeproj 'Project2/Project2.xcodeproj'

target 'Project1' do
    xcodeproj 'Project1/Project1.xcodeproj'
   #Pods for Project1
    pod 'SwiftyJSON', '~> 4.0'
end

target 'Project2' do
    xcodeproj 'Project2/Project2.xcodeproj'
   #Pods for Project2
    pod 'SwiftyJSON', '~> 4.0'
end

```

**Comment by wulongwang** [comment]
> ```
> platform :ios, '9.0'
> 
> workspace 'TestWorkSpace'
> xcodeproj 'Project1/Project1.xcodeproj'
> xcodeproj 'Project2/Project2.xcodeproj'
> 
> target 'Project1' do
>     xcodeproj 'Project1/Project1.xcodeproj'
>    #Pods for Project1
>     pod 'SwiftyJSON', '~> 4.0'
> end
> 
> target 'Project2' do
>     xcodeproj 'Project2/Project2.xcodeproj'
>    #Pods for Project2
>     pod 'SwiftyJSON', '~> 4.0'
> end
> ```

do you kown cocoapods create mutultiple projects with podspec file?

**Comment by shamil707** [comment]
platform :ios, '9.0'

workspace 'TestWorkSpace'
xcodeproj 'Project1/Project1.xcodeproj'
xcodeproj 'Project2/Project2.xcodeproj'

target 'Project1' do
    xcodeproj 'Project1/Project1.xcodeproj'
   #Pods for Project1
    pod 'SwiftyJSON', '~> 4.0'
end

target 'Project2' do
    xcodeproj 'Project2/Project2.xcodeproj'
   #Pods for Project2
    pod 'SwiftyJSON', '~> 5.1'
end


Possible to have different version of same SwiftyJSON framework for diff target?

**Comment by paulb777** [comment]
@shamil707 It's not possible. A workspace can only include one version of a pod.

**Comment by shamil707** [comment]
> @shamil707 It's not possible. A workspace can only include one version of a pod.

Any workaround for this?
We are in situation were we cant have u-turn.

we have multiple targets for diff countries and same workspace.

we dont have to have duplicate the framwork in diff name.

SPM can solve this or multiple workspace or ?
