### ISSUE TITLE
Build error in xcode

### ISSUE THREAD

**Issue by manishdubey-epita** [CocoaPods/CocoaPods#4586]
Hi,

I am using CocoaPods in my application. After couple of changes, I suddenly started getting below error:

Undefined symbols for architecture x86_64:
  "___asan_init", referenced from:
      _asan.module_ctor in Pods_Smartertime(Pods-Smartertime-dummy.o)
  "___asan_version_mismatch_check_v6", referenced from:
      _asan.module_ctor in Pods_Smartertime(Pods-Smartertime-dummy.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I tried pod clean, install and update but all in vain. Could I get some insight to resolve this error?

Thanks!

**Comment by neonichu** [comment]
Please provide steps to reproduce the issue, so that we are able to look into it.

**Comment by manishdubey-epita** [comment]
I tried cleaning DerivedData but the same folder reappears:

![screen shot 2015-11-24 at 16 05 27](https://cloud.githubusercontent.com/assets/11277712/11370754/6b513e66-92c5-11e5-9ece-ced4c05a9afa.png)

Below is the full screenshot of build log:

![screen shot 2015-11-24 at 16 04 56](https://cloud.githubusercontent.com/assets/11277712/11370771/85084a20-92c5-11e5-9e28-6263c4f63b14.png)

**Comment by manishdubey-epita** [comment]
Here is my pod file:

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Smartertime' do
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'SWRevealViewController'
    pod 'Bond', '4.0.1'
    pod 'FMDB'
    pod 'sqlite3', '3.9.0.0'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKMessengerShareKit'
    pod 'FBSDKShareKit'
pod 'j2objc-shared-debug', :configuration => ['Debug'], :path => './../SmarterTimeApp/shared/build'
pod 'j2objc-shared-release', :configuration => ['Release'], :path => './../SmarterTimeApp/shared/build'

end

**Comment by manishdubey-epita** [comment]
Found the solution after so many workarounds. Disabled the Project runtime sanitization.
