### ISSUE TITLE
rsync issue with cocoa pods + Xcode 7

### ISSUE THREAD

**Issue by mkagita** [CocoaPods/CocoaPods#4588]
We are running into new issue where adding TOCropViewController (which builds bundle resource) causes rsync issue.

PhaseScriptExecution Copy\ Pods\ Resources /Users/mkagita/Library/Developer/Xcode/DerivedData/PodIssue-dmdgpvfqnkatjqekldplqnngqegb/Build/Intermediates/PodIssue.build/Release-iphoneos/PodIssue.build/Script-254389A526B019B8ACB4B526.sh
    cd /Users/mkagita/Desktop/PodIssue/PodIssue
    /bin/sh -c /Users/mkagita/Library/Developer/Xcode/DerivedData/PodIssue-dmdgpvfqnkatjqekldplqnngqegb/Build/Intermediates/PodIssue.build/Release-iphoneos/PodIssue.build/Script-254389A526B019B8ACB4B526.sh
/Users/mkagita/Library/Developer/Xcode/DerivedData/PodIssue-dmdgpvfqnkatjqekldplqnngqegb/Build/Products/Release-iphoneos/TOCropViewControllerBundle.bundle
building file list ... rsync: link_stat "/Users/mkagita/Library/Developer/Xcode/DerivedData/PodIssue-dmdgpvfqnkatjqekldplqnngqegb/Build/Products/Release-iphoneos/TOCropViewControllerBundle.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23

To reproduce:
1. clone https://github.com/mkagita/PodIssue2
2. edit build.sh to proper provision info
3. sh build.sh

**Comment by mkagita** [comment]
note that there is no issue building this project from Xcode IDE. This only fails when you use xcodebuild command line.

**Comment by segiddins** [comment]
What version of CocoaPods are you using?

**Comment by mkagita** [comment]
I tried both 0.37.2 and latest 0.39 (whatever gem install cocoapods give me) and the results were same.

**Comment by neonichu** [comment]
See #4589, you have chosen a very particular set of `xcodebuild` arguments that seems to break implicit dependencies.
