### ISSUE TITLE
ld: library not found issue with cocoa pods + Xcode 7 (using xcodebuild)

### ISSUE THREAD

**Issue by mkagita** [CocoaPods/CocoaPods#4589]
running into issue where using cocoa pods with Xcode 7's xcodebuild doesn't work as expected.

ld: library not found for -lALAssetsLibrary-CustomPhotoAlbum
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

If I look at Releases-iphoneos folder, no library (.a files) get generated when compiling using xcodebuild command. If you compile from Xcode IDE, there is no problem.

Below is sample project demonstrating this issue.
build.sh has the command to build. you will need to replace with appropriate iOS provision info.
https://github.com/mkagita/PodIssue3

**Comment by neonichu** [comment]
This seems to rather be an `xcodebuild` problem or with the particular arrangement of arguments you chose — if you build the project without your custom set of arguments, it builds just fine.
