### ISSUE TITLE
Testflight.h file not found

### ISSUE THREAD

**Issue by besi** [CocoaPods/CocoaPods#459]
Today I started using CocoaPods and I have already been using Testflight for a while now. 
So I deleted the Testflightfiles from my project and added it to my Podspec:

```
platform :ios
pod 'MBProgressHUD',  '~> 0.5' 
pod 'TestFlightSDK', '~> 1.0'
```

I run `pod install` and the files show up in Xcode. However the `#import "Testflight.h"` does no longer work and I get the following error:

```
'Testflight.h' file not found
```

**Update**: I just realized that this is also the case for `#import "MBProgressHUD.h"` depending on the order I import those I get either of the errors.

**Comment by blakeperdue** [comment]
@besi your solution worked for me. I tried several solutions from StackOverflow before finding yours. It worked perfectly, so thanks.
