### ISSUE TITLE
Transitive dependencies error even local target uses same pod

### ISSUE THREAD

**Issue by appcoders** [CocoaPods/CocoaPods#4590]
As mentioned in https://github.com/CocoaPods/CocoaPods/commit/df34f79ffc2e0a0ddb5a851cebfd89407ec434b5

if a pod is used in both the user target and another pod - transitive dependency check should not fail. But it does.

I got a private spec "lets call it SSLSuite" which includes OpenSSL as a pod dependency. 
I have a project which uses a podfile containing

pod "OpenSSL"
pod "SSLSuite"

which leads to 

[!] The 'Pods-Sample' target has transitive dependencies that include static binaries: (.../Pods/OpenSSL/lib/libcrypto.a and .../Pods/OpenSSL/lib/libssl.a)

How can this be fixed?
Thanks!

**Comment by neonichu** [comment]
This is precisely where it has to fail, because you would end up with two copies of the same symbols being around, leading to undefined Objective-C runtime behaviour and/or duplicated symbols. Your best bet is to not use `use_frameworks!` and let everything be linked directly into the user target.

**Comment by appcoders** [comment]
As we are using swift in the main project this is not an option. I solved it by creating two dynamic frameworks for libssl and libcrypto - using vendored_frameworks.
