### ISSUE TITLE
ANT library integration with Xcode 6.4

### ISSUE THREAD

**Issue by sauravambastha** [CocoaPods/CocoaPods#4592]
Hi, I want to run ANT Library MACOSX package 2.9 on my Xcode 6.4. Although i have successfully compile and run DEMO.LIB of this library but its output come on console only. I want its output to come on my designed layout (output screen of my Xcode project). I am trying to integrate this with my Xcode project but not able to do so. I am newbie into this. Can anyone guide me with this ?? 
Thanks

**Comment by neonichu** [comment]
See #4591
