### ISSUE TITLE
Bundle asset is not copied along with binary framework

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#4593]
Follow up on #3993, while binary issues were solved, framework bundles were never a part of this fix (I believe).

This is still a problem with latest Lookback. I tried `pod deintegrate` but "Copy Bundle Resources" phase is never being added to the project.

```
➜  app git:(master) ✗ tree Pods/Lookback -L 3
Pods/Lookback
└── lookback
    ├── HD
    │   └── Lookback.framework
    └── Lookback-Resources
        └── Lookback.bundle
```

Looking at their pod spec they have Lookback.bundle listed in resources so I'd expect it to be copied into the app.

https://github.com/CocoaPods/Specs/blob/master/Specs/Lookback/1.1.4/Lookback.podspec.json

Pods-resources.sh looks good to me:

```
[...]

if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_resource "Lookback/lookback/Lookback-Resources/Lookback.bundle"
fi
if [[ "$CONFIGURATION" == "Release" ]]; then
  install_resource "LookbackSafe/lookback/Lookback-Resources/Lookback.bundle"
fi
if [[ "$CONFIGURATION" == "Testing" ]]; then
  install_resource "LookbackSafe/lookback/Lookback-Resources/Lookback.bundle"
fi

[...]
```

I found out that Pods-resources.sh was never run, so I've added Run Script phase to my app:

```
"${SRCROOT}/Pods/Target Support Files/Pods/Pods-resources.sh"
```

which solved the issue.

**Comment by segiddins** [comment]
Adding the build phase script will be fixed by an open PR of mine.

**Comment by pronebird** [comment]
@segiddins cheers!

**Comment by neonichu** [comment]
@segiddins would that be #4544?

**Comment by segiddins** [comment]
@neonichu yup!

**Comment by segiddins** [comment]
This should now be fixed on master.
