### ISSUE TITLE
pod trunk not validate.

### ISSUE THREAD

**Issue by Clear2** [CocoaPods/CocoaPods#4594]
localhost:HuiMaiModel zjx$ pod trunk push

[!] Found podspec `HuimaiModel.podspec`
Updating spec repo `master`
Validating podspec
[!] The podspec does not validate.

localhost:HuiMaiModel zjx$ pod lib lint

 -> HuimaiModel (1.0.0)

HuimaiModel passed validation.

I pod trunk not validate,but pod lib lint is success, why trunk push not validate

**Comment by segiddins** [comment]
What's the output of `pod trunk push --verbose`?

**Comment by neonichu** [comment]
Closing because of lack of response.
