### ISSUE TITLE
Add contents of prefix header to top of umbrella header?

### ISSUE THREAD

**Issue by timbodeit** [CocoaPods/CocoaPods#4595]
It seems to me, that when Xcode treats a framework as a clang module, its prefix header is not applied to the umbrella header.
Neither are any definitions in the class that imports this module.

Some (older) Pods rely on the prefix header quite heavily. An example is AFNetworking 1.3.4 which is still used by RestKit.

It includes a `#import <SystemConfiguration/SystemConfiguration.h>` statement in the prefix header. 
The presence of on the `_SYSTEMCONFIGURATION_H` macro defined in `SystemConfiguration.h` is then [used to determine whether certain functionality is available](https://github.com/AFNetworking/AFNetworking/blob/1.3.4/AFNetworking/AFHTTPClient.h#L76-L83).

My first thought is to add the content of the podspec's `prefix_header_contents` attribute to the top of the umbrella header.
Does that make sense?

Happy to open a pull request, if I get some input on this.

This is becoming an issue now, since the current CocoaPods master makes Xcode treat `#import <AFNetworking/AFNetworking.h>` as a module import of the AFNetworking module (going through the AFNetworking-umbrella.h file. CocoaPods 0.39 made Xcode use AFNetworking's own `AFNetworking.h` file directly without building it as a module or going through the umbrella header.

**Comment by segiddins** [comment]
Pretty sure that's just a consequence of how old versions of AFNetworking chose to do feature detection. Adding new the prefix header contents to the umbrella header would expose a pods prefix header contents to all of its consumers, which wouldn't work.

**Comment by valeriomazzeo** [comment]
this is exactly the same as #5390

**Comment by segiddins** [comment]
Commented on #5390.
