### ISSUE TITLE
how can s.dependency link to custom git

### ISSUE THREAD

**Issue by threeknife** [CocoaPods/CocoaPods#4597]
```ruby
#  -------------------------------------------
 #  s.dependency 'SDWebImage', '~> 3.7.2'
 >  s.dependency 'SDWebImage/WebP' , :git=> 'https://github.com/redengineer/libwebp.git'
 #  s.dependency 'ReactiveCocoa', '~> 2.5'
 #  -------------------------------------------
```

**Comment by threeknife** [comment]
[!] Invalid `HaloFramework.podspec` file: [!] Unsupported version requirements. Updating CocoaPods might fix the issue.

**Comment by neonichu** [comment]
Could you please share the whole podspec?

**Comment by segiddins** [comment]
You can't specify the source for a pod in your podspec.

**Comment by neonichu** [comment]
Oh right, I overlooked that. The right way to do this is choose a unique name for your fork and use your own spec repo.
