### ISSUE TITLE
After Pod install, build project error PhaseScriptExecution Embed\ Pods\ Frameworks

### ISSUE THREAD

**Issue by Vampire7** [CocoaPods/CocoaPods#4598]
I Use the Xcode 7.1.1 + cocopods 0.39.0 , perform "pod install --no-repo-update --verbose" Everything is all right, But build project have the error. This problem bothering me for a week, I'm looking for related issues, no fix.  Who has suffered from this problem?

PhaseScriptExecution Embed\ Pods\ Frameworks /Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Intermediates/ShenTuShe_IOS.build/Debug-iphoneos/ShenTuShe_IOS.build/Script-6069F4559C3322D0D50A432E.sh
    cd /Users/Vampire/Desktop/ShenTuShe_IOS/ShenTuShe_IOS
    /bin/sh -c /Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Intermediates/ShenTuShe_IOS.build/Debug-iphoneos/ShenTuShe_IOS.build/Script-6069F4559C3322D0D50A432E.sh

mkdir -p /Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Products/Debug-iphoneos/ShenTuShe_IOS.app/Frameworks
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Products/Debug-iphoneos/Alamofire.framework" "/Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Products/Debug-iphoneos/ShenTuShe_IOS.app/Frameworks"
building file list ... done
Alamofire.framework/
Alamofire.framework/Alamofire
Alamofire.framework/Info.plist
Alamofire.framework/_CodeSignature/CodeResources

sent 1086051 bytes  received 92 bytes  2172286.00 bytes/sec
total size is 1085573  speedup is 1.00
Code Signing /Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Products/Debug-iphoneos/ShenTuShe_IOS.app/Frameworks/Alamofire.framework with Identity iPhone Developer: Tao Liu (RVX5253NXB)
/usr/bin/codesign --force --sign AFC326058C3CFE98B9F2F804134FF486C5EC0E37 --preserve-metadata=identifier,entitlements "/Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Products/Debug-iphoneos/ShenTuShe_IOS.app/Frameworks/Alamofire.framework"
/Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Products/Debug-iphoneos/ShenTuShe_IOS.app/Frameworks/Alamofire.framework: replacing existing signature
/Users/Vampire/Library/Developer/Xcode/DerivedData/ShenTuShe_IOS-boxvagecwuolqhewfhnfslwsfyzw/Build/Products/Debug-iphoneos/ShenTuShe_IOS.app/Frameworks/Alamofire.framework: the codesign_allocate helper tool cannot be found or used
Command /bin/sh failed with exit code 1

**Comment by segiddins** [comment]
`the codesign_allocate helper tool cannot be found or used` -- that's really strange

**Comment by neonichu** [comment]
Sounds like something is up with your installation, what's the result when you run `ls -l `xcode-select -p`/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate`?

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
