### ISSUE TITLE
Shared framework between the app and watch extension 

### ISSUE THREAD

**Issue by mohwaili** [CocoaPods/CocoaPods#4601]
Hi everyone, 

I've a shared framework which I want te use for my main and watch app. After installing the pods and trying to run the app I receive this error. 

dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /Users/[Username]/Library/Developer/Xcode/DerivedData/Avans-aggztpesjvsvfkaukkhpdgxdgyde/Build/Products/Debug-iphonesimulator/AvansDataManager.framework/AvansDataManager
  Reason: image not found

<img width="209" alt="screen shot 2015-11-27 at 09 06 14" src="https://cloud.githubusercontent.com/assets/9988884/11436611/8d4e83a2-94e6-11e5-881b-db6deaf49729.png">

<img width="850" alt="screen shot 2015-11-27 at 09 06 29" src="https://cloud.githubusercontent.com/assets/9988884/11436615/946c1096-94e6-11e5-9754-4829232c523d.png">

This is how my pod file looks like
<img width="305" alt="screen shot 2015-11-27 at 09 06 42" src="https://cloud.githubusercontent.com/assets/9988884/11436618/a3330026-94e6-11e5-8e40-003924a4b1d3.png">

**Comment by segiddins** [comment]
It'll be hard to debug without an actual project that we can run that reproduces the issue.

**Comment by mohwaili** [comment]
I'll upload the project tomorrow when I'm home

**Comment by mohwaili** [comment]
Here is a demo project 
https://github.com/mohwaili/Test

**Comment by mohwaili** [comment]
any updates guys?

**Comment by segiddins** [comment]
@mohwaili we haven't had a chance to investigate this yet, but we will, that's why the issue is still open -- anyone is also welcome to submit a pull request with a fix!

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
