### ISSUE TITLE
Cocoapods looks at wrong branch while searching for private specs

### ISSUE THREAD

**Issue by alexs555** [CocoaPods/CocoaPods#4602]
We have a private repo with specs, so inside our Podfile, besides github source, we also have our repo as source.

While trying pod update on one particular macbook, we get error "Unable to find a specification for ${PodName}", although other computers can see this spec with no problem.

Moreover, while 'pod install' we noticed, that versions of our private-pods, that can only be installed on this mac are corresponding to develop branch in our repo with specs. (other machines pull info from master branch)

What can be the reason?

**Comment by AndreyPanov** [comment]
I solved the problem, just switched to '~/.cocoapods/repos' path and manually deleted the local specs directory.
'Pod install' works correctly after that.

**Comment by segiddins** [comment]
We do this intentionally, to allow people to branch if absolutely necessary for specs repos they don't control.
