### ISSUE TITLE
Sandbox-Exec: Operation Not Permitted

### ISSUE THREAD

**Issue by burkeholland** [CocoaPods/CocoaPods#4603]
Currently on El Capitan, `sandbox-pod` throws the error...

    sandbox-exec: /Users/burkeholland/.rvm/gems/ruby-2.2.2@global/gems/cocoapods-0.39.0/bin/pod: Operation not permitted

**Comment by segiddins** [comment]
Interesting... @alloy could you please look into this, since I'm not familiar with the sand boxing stuff?

**Comment by alloy** [comment]
@burkeholland Can you check you console log for any extra details about what it is that’s not permitted?

**Comment by burkeholland** [comment]
I changed my Ruby to 2.1.1 and that cleared the error. I actually don't think this is related to CocoaPods at all, but rather the way that @nativescript is calling them. Opening the issue there.

**Comment by alloy** [comment]
Cool, thanks for checking :+1: 

And I also just learned about the existence of NativeScript :sparkles:
