### ISSUE TITLE
Cannot install cocoapods due to i18n 0.7.0 requiring ruby 1.9.3

### ISSUE THREAD

**Issue by 1-61803** [CocoaPods/CocoaPods#4604]
ERROR:  Error installing cocoapods:
    	i18n requires Ruby version >= 1.9.3.

    tests-Mac:~ test$ ruby -v
    ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    tests-Mac:~ test$ 
    tests-Mac:~ test$ gem -v
    2.5.0
    tests-Mac:~ test$ 

I'm enjoying `cocoapods` installation in OS X 10.8.5, Xcode 5.1.1. Any ideas?

**Comment by segiddins** [comment]
CocoaPods currently requires Ruby >= 2.0.

**Comment by 1-61803** [comment]
I posted my version of `ruby`.

**Comment by segiddins** [comment]
What's the output of `which gem` and `which ruby`?

**Comment by 1-61803** [comment]
tests-Mac:~ test$ which -a ruby
    /usr/bin/ruby
    tests-Mac:~ test$ ruby -v
    ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    tests-Mac:~ test$ 
    tests-Mac:~ test$ which -a gem
    /usr/bin/gem
    tests-Mac:~ test$ 
    tests-Mac:~ test$ gem -v
    2.5.0

**Comment by segiddins** [comment]
¯\_(ツ)_/¯ sounds like a RubyGems issue to me then.

**Comment by 1-61803** [comment]
Hmm...I'm at a loss. I don't speak `ruby`, I just need `cocoapods` to compile an application.

**Comment by segiddins** [comment]
You might be interested in http://cocoapods.org/app, then

**Comment by 1-61803** [comment]
Just installed it, but I get the same error.

**Comment by segiddins** [comment]
are you using the app's version of the `pod` binary

**Comment by 1-61803** [comment]
I think I eventually made this sequence, but I don't remember anymore because I messed this VM and have to reproduce the whole :D YMMV

    port install rvm
    rvm install ruby-1.9.3-p551
    rvm install ruby-2.2.1
    rvm use 1.9.3
    gem install i18n -v 0.7.0
    rvm use 2.2.1
    sudo gem install cocoapods -V && pod setup

**Comment by segiddins** [comment]
¯\_(ツ)_/¯ seems like a ruby gems / RVM issue to me, I'm not really seeing anything CocoaPods-specific in there.

**Comment by 1-61803** [comment]
This is what I did in a new VM with OS X 10.8.5 Xcode 5.1.1.

    curl -L get.rvm.io | bash -s stable
    rvm install 2.2.1
    sudo gem install cocoapods -V && pod setup

No errors so far.

**Comment by segiddins** [comment]
Glad to hear you've got things working!
