### ISSUE TITLE
Xcode and AppCode require incompatible #import

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#4608]
Xcode 7.1.1, AppCode 3.3.1, Cocoapod 0.39.0.

Podfile: `pod 'GCJSONKit', '~> 1.5'`

Xcode will only accept:
* `#import <JSONKit/JSONKit.h>` or `#import "JSONKit/JSONKit.h"`

AppCode will only accept:
* `#import <GCJSONKit/JSONKit.h>` or `#import "GCJSONKit/JSONKit.h"`

How to get an import statement that works for both IDE?

**Comment by segiddins** [comment]
That's quite strange. I don't have appcode so I can't look into it, but whatever Xcode accepts is probably canonical.

**Comment by Coeur** [comment]
https://www.jetbrains.com/objc/download/

**Comment by orta** [comment]
I think this is likely a project specific thing, I use AppCode on [artsy/energy](https://github.com/artsy/energy)
![screen shot 2015-11-30 at 10 15 32 am](https://cloud.githubusercontent.com/assets/49038/11475418/58d5a92c-974b-11e5-887c-689c92289911.png) fine without any differences between xcode/appcode.

Did you try making a demo project and seeing if that has the same problem?

**Comment by neonichu** [comment]
Might have something to do with the spec using `header_dir` (<https://github.com/CocoaPods/Specs/blob/master/Specs/GCJSONKit/1.5.0/GCJSONKit.podspec.json#L18>) — don't see how it could break in AppCode, though

**Comment by Coeur** [comment]
@orta it is specific to GCJSONKit.
@neonichu nice find, and how does "header_dir" translate when you install a Pod? I'll try tell JetBrains about the issue.

Now, I also notice: https://cocoapods.org/pods/GCJSONKit is maintained by Unclaimed with version 1.5.0 and `header_dir`, while the repo itself serves a one year old version 1.5.1 and never had the keyword `header_dir` in its history: https://github.com/gamechanger/JSONKit/blob/master/GCJSONKit.podspec

**Comment by Coeur** [comment]
Issue doesn't happen anymore, using AppCode 3.3.1 with Xcode 7.2. I believe it was an issue with AppCode cache.
