### ISSUE TITLE
Autocomplete for Installed Pods Not Functioning

### ISSUE THREAD

**Issue by praveensharma** [CocoaPods/CocoaPods#4610]
Hi everyone! Using Xcode 7.1.1 and a single pod installed, CocoaAsyncSocket, autocomplete and syntax highlighting have ceased to work.

I've tried all the usual XCode derived data fixes and autocomplete does work with all other classes but the single pod I'm using - although installed and functioning - is not recognized by autocomplete or syntax highlighting.

My workspace includes targets for tvOS and iOS using the same pod (with separate settings in the pod file) so I even attempted to install the pod only for one target in case that was the issue. No dice.

One interesting note is that on installing the pods I receive the following warnings:

    warning:  The file reference for "CocoaAsyncSocket.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.

and then:

    [!] [Xcodeproj] Generated duplicate UUIDs:

That statement is followed by: 

    PBXFileReference -- /mainGroup/children/children:displayName:CocoaAsyncSocket.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:CocoaAsyncSocket.framework,path:CocoaAsyncSocket.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:CocoaAsyncSocket.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:CocoaAsyncSocket.framework,path:CocoaAsyncSocket.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:CocoaAsyncSocket.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:CocoaAsyncSocket.framework,path:CocoaAsyncSocket.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:CocoaAsyncSocket.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:CocoaAsyncSocket.framework,path:CocoaAsyncSocket.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:CocoaAsyncSocket.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:CocoaAsyncSocket.framework,path:CocoaAsyncSocket.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_TuneClash.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_TuneClash.framework,path:Pods_TuneClash.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_TuneClashMobile.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_TuneClashMobile.framework,path:Pods_TuneClashMobile.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_TuneClashMobileTests.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_TuneClashMobileTests.framework,path:Pods_TuneClashMobileTests.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_TuneClashMobileUITests.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_TuneClashMobileUITests.framework,path:Pods_TuneClashMobileUITests.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_TuneClashTests.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_TuneClashTests.framework,path:Pods_TuneClashTests.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Products,isa:PBXGroup,name:Products,sourceTree:<group>,/Products/children/displayName:CocoaAsyncSocket.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:CocoaAsyncSocket.framework,path:CocoaAsyncSocket.framework,sourceTree:BUILT_PRODUCTS_DIR,/Products/CocoaAsyncSocket.framework

I can avoid these warnings by placing the following in my .profile 

    export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES

Let me know if I can help figure this out in any way.

My podfile:

    # Uncomment this line to define a global platform for your project
    # platform :ios, '6.0'

    use_frameworks!

    target 'TuneClashMobile' do
        platform :ios, '9.0'
        pod 'CocoaAsyncSocket', :git => 'https://github.com/robbiehanson/CocoaAsyncSocket.git'
    end

    target 'TuneClash' do
        platform :tvos, '9.0'
        pod 'CocoaAsyncSocket', :git => 'https://github.com/robbiehanson/CocoaAsyncSocket.git'
    end

    target 'TuneClashTests' do
        platform :tvos, '9.0'
        pod 'CocoaAsyncSocket', :git => 'https://github.com/robbiehanson/CocoaAsyncSocket.git'
    end

    target 'TuneClashMobileTests' do
        platform :ios, '9.0'
        pod 'CocoaAsyncSocket', :git => 'https://github.com/robbiehanson/CocoaAsyncSocket.git'
    end

    target 'TuneClashMobileUITests' do
        platform :ios, '9.0'
        pod 'CocoaAsyncSocket', :git => 'https://github.com/robbiehanson/CocoaAsyncSocket.git'
    end

**Comment by segiddins** [comment]
The duplicate UUID error is both unrelated and already fixed. What version of CocoaPods are you running? I think this particular issue has already been fixed on master by @neonichu

**Comment by praveensharma** [comment]
0.39

**Comment by praveensharma** [comment]
Hey @segiddins - huge apologies for even starting this issue - I removed the export path and started a new project to submit an example project and everything is working fine there - seems unrelated to cocoa pods and related to the project itself. Closing now.

**Comment by segiddins** [comment]
Awesome, thanks for following up :)
