### ISSUE TITLE
Unable to retrieve a pod with a specific commit version if pod author does not include the pod spec in repo.

### ISSUE THREAD

**Issue by andrewjl** [CocoaPods/CocoaPods#4611]
I'm trying to checkout the most recent commit of the `ISO8601DateFormatter` pod. The author does not include the pod spec in the repo. When I specify the pod version as follows:

```
	pod 'ISO8601DateFormatter', :git => 'https://github.com/boredzo/iso-8601-date-formatter.git', :commit => '8a4bc97'
```

I get the following error on `pod install`:

```
Fetching external sources
-> Pre-downloading: `ISO8601DateFormatter` from `https://github.com/boredzo/iso-8601-date-formatter.git`, commit `8a4bc97`
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/boredzo/iso-8601-date-formatter.git
     /var/folders/fc/z3_zj3kj6vn85nk4twfnxqfr0000gn/T/d20151130-70196-195dvyu
     Cloning into '/var/folders/fc/z3_zj3kj6vn85nk4twfnxqfr0000gn/T/d20151130-70196-195dvyu'...
   $ /usr/local/bin/git checkout --quiet 8a4bc97
[!] Unable to find a specification for 'ISO8601DateFormatter'.

```

I specify the Cocoapods specs repo in the podfile as follows: `source 'https://github.com/CocoaPods/Specs.git'`

Is it possible to make an inline declaration of the pod spec? Or better yet, is there a way to provide a pod spec that's tied to a SHA instead of a version/tag?

**Comment by segiddins** [comment]
You can use `podspec` to point at whatever podspec you want.
