### ISSUE TITLE
UIKit not added when linting with new linter

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#4612]
Should the new linter that generates the `App.xcworkspace` include `UIKit` for the iOS sample app? Again we are at the bleeding edge release that fixed this https://github.com/CocoaPods/CocoaPods/issues/4523 validator issue but now we are hitting this.

Or should the podspec include `UIKit` in its frameworks?

It only works when I manually add `UIKit` in the generated sample app...

**Comment by dnkoutso** [comment]
Also should the app be built with `Release` configuration rather than `Debug`? This is a bigger change because the previous linter would lint all pods for `Release` configuration.

**Comment by dnkoutso** [comment]
Looks like xcode doesnt add the UIKit framework either by default...so it seems the answer here is that the podspec should specify it.

**Comment by dnkoutso** [comment]
Maybe its important to mention that we are linting using `--use-libraries`

**Comment by segiddins** [comment]
The configuration shouldn't have changed?

**Comment by dnkoutso** [comment]
From running lint internally in our project I see

```=== BUILD TARGET Pods OF PROJECT Pods WITH CONFIGURATION Debug ==```

**Comment by segiddins** [comment]
Odd. I'd love a PR returning it to what it used to be

**Comment by dnkoutso** [comment]
Any thoughts on the UIKit problem?

**Comment by dnkoutso** [comment]
Its because the old linter used the `target` than `scheme` and its default config for command line builds is set to 'Release`.
![screen shot 2015-11-30 at 6 47 55 pm](https://cloud.githubusercontent.com/assets/310370/11491037/e43d6e04-9792-11e5-88b9-083081493ed8.png)

**Comment by segiddins** [comment]
I'm not sure I fully understand what the problem is, and I'd need to see the spec you're trying to lint to know for sure.

**Comment by dnkoutso** [comment]
OK I'll leave this issue open for the UIKit problem and then open up a PR to fix the configuration problem for the new linter. Its basically two issues in this issue and I started it :)

**Comment by dnkoutso** [comment]
@segiddins I cannot 100% reproduce but it appears that because the generated `main.m` is missing `@import UIKit;` xcode doesnt link it.

Again not 100% sure how to repro but the problem comes in:

when linting: pre-built dependency A depends on pre-built dependency B where B depends on UIKit then it fails.

when linting: just pre-built dependency B where B depends on UIKit then it works, perhaps because nothing is importing anythign from that library and so it doesnt have to link anything.

Would you be OK to add `@import UIKit;` on the generated `main.m` file?

**Comment by dnkoutso** [comment]
Also its weird cause I am using `--use-libraries` flag why is the `main.m` using the `@import` style

**Comment by dnkoutso** [comment]
Ah nevermind my last comment I see the code now. I stick with my intention to add `@import UIKit`

**Comment by segiddins** [comment]
Yeah, should be added for iOS and tvOS, I suppose.

**Comment by dnkoutso** [comment]
Its weird because I just created a sample lib and did not see this behavior...I guess it happens only with my scenario of multiple dependencies...

**Comment by dnkoutso** [comment]
I think overall its safe to add this...and can fix other edge cases even though I have no 100% repro steps.
