### ISSUE TITLE
Xcode does not autocomplete #import files in Development Pods project

### ISSUE THREAD

**Issue by ersentekin** [CocoaPods/CocoaPods#4617]
Here's my development pod project directory structure
![screen shot 2015-12-01 at 14 00 18](https://cloud.githubusercontent.com/assets/1521998/11500188/3242279c-9834-11e5-874c-696e84c8e83b.png)

Here's also I could not get autocomplete for `ETVariantCalculations` 
![screen shot 2015-12-01 at 14 00 40](https://cloud.githubusercontent.com/assets/1521998/11500222/66f64608-9834-11e5-94b7-f8da0e1909ee.png)

What could be the reason? 
I've tried to fix it by making some changes for `HEADER_SEARCH_PATHS`

What do you think?
Thanks!

**Comment by neonichu** [comment]
Could you please share the podspec you're referring to?

**Comment by ersentekin** [comment]
@neonichu 
```
{
  "name": "ETVariant",
  "version": "0.1.0",
  "summary": "A short description of ETVariant.",
  "description": "",
  "homepage": "https://github.com/<GITHUB_USERNAME>/ETVariant",
  "license": "MIT",
  "authors": {
    "Ersen Tekin": "xxx@gmail.com"
  },
  "source": {
    "git": "https://github.com/<GITHUB_USERNAME>/ETVariant.git",
    "tag": "0.1.0"
  },
  "platforms": {
    "ios": "7.0"
  },
  "requires_arc": true,
  "source_files": "Pod/Classes/**/*",
  "resource_bundles": {
    "ETVariant": [
      "Pod/Assets/*.png"
    ]
  }
}

```

Thanks!

**Comment by orta** [comment]
I think this is because you should be using `< ETVariant/ETVariantCalculations.h>` instead

**Comment by ersentekin** [comment]
Hey @orta  thanks for your help,
But it is not working in that way too. By the way, I've matched my groups with the real paths in Xcode, as you can see in the screenshot below. For example, `ETVariant` group's **File Inspector**
![screen shot 2015-12-01 at 17 32 12](https://cloud.githubusercontent.com/assets/1521998/11505180/c67b40ac-9851-11e5-8f84-a0729551e63d.png)

**Comment by segiddins** [comment]
I believe @neonichu fixed this recently, is this still an issue in the 1.0 betas?

**Comment by segiddins** [comment]
Closing due to lack of response.
