### ISSUE TITLE
cannot use Categories from vendored_framework

### ISSUE THREAD

**Issue by gabrielafonsogoncalves** [CocoaPods/CocoaPods#4619]
Hi,

I have my pod which have an example app. In my `podspec` I included this line:
`s.vendored_frameworks = 'Pod/Frameworks/JUM.framework'`
because I need that framework in my pod. My Example app build and run pretty well, every class from that framework seems to work fine but when I try to use a category that is in the framework I get this error: 
`unrecognized selector sent to instance`

So I don't know why is it happening, Do I'm missing something? or is it a bug?

I ran `pod install` using cocoapods 0.39.0 and the previous version.
IMPORTANT: My pod is using `use_frameworks!` for iOS8

**Comment by segiddins** [comment]
Is the framework a proper dynamic framework or a "fake" static framework?

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/blob/e8c9366e75fe9eb635a7e50894952d41b59de0c8/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb#L48 might need to be changed to pass `true` as the second arg when there are vendored static artifacts. If that's the case, a PR doing so would be much appreciated!

**Comment by gabrielafonsogoncalves** [comment]
Thanks for your answer @segiddins 
It is a "fake" framework. You can find it here http://mobile-sdk.jumio.com/com/jumio/ios/jumio-mobile-sdk/1.6.1/

**Comment by gabrielafonsogoncalves** [comment]
so this is a bug that needs some work? I found a related issue here: https://github.com/CocoaPods/CocoaPods/issues/4556

**Comment by gabrielafonsogoncalves** [comment]
@segiddins I read the code, if I change it to pass true when there is a static artifact would be the same as if I put in my podspec this line, right?:

```
s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC' }
```

after adding it I get three build errors:

```
Undefined symbols for architecture x86_64:
  "_vImageBoxConvolve_ARGB8888", referenced from:
      -[UIImage(JMUtilities) JMapplyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in JumioCore(UIImage+JMUtilities.o)
  "_vImageMatrixMultiply_ARGB8888", referenced from:
      -[UIImage(JMUtilities) JMapplyBlurWithRadius:tintColor:saturationDeltaFactor:maskImage:] in JumioCore(UIImage+JMUtilities.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by segiddins** [comment]
@kcoleman want to look into this one?

**Comment by gabrielafonsogoncalves** [comment]
It used to work when my pod wasn't build as a framework and I included it via `dependency` in my podspec. After moving it to build as a framework I couldn't include that framework via ´dependency´ in my podspec anymore, so I tried including it as a vendored_framework, which worked! but I cannot call any category now because it crash :-1: @segiddins @kcoleman

**Comment by segiddins** [comment]
@gabrielafonsogoncalves we understand it's frustrating, and we'll try and look into fixing the bug as soon as we have the time.

**Comment by gabrielafonsogoncalves** [comment]
@segiddins thank you!

**Comment by themackworth** [comment]
@segiddins For what its worth, unless I am misunderstanding your comment, my test project in #4556 seems to show categories working in "fake" static library frameworks.

**Comment by kcoleman** [comment]
@segiddins Hello Samuel.  I suspect you intended this for another user.

**Comment by gabrielafonsogoncalves** [comment]
@themackworth did you try updating your project to build as a framework? using `use_frameworks!` in your podfile inside your pod.

Please let me know if it works for you or if you can share your test project :+1: it would really help me

**Comment by gabrielafonsogoncalves** [comment]
@themackworth I tested your project (here: https://github.com/themackworth/CocoapodsVendorStaticLib) and yes it works, but when I add the third party framework I'm using it crashes when I try to call an extension class. 

I tried to push that to your repo but I don't have permissions, so I push my changes to this repo https://github.com/gabrielafonsogoncalves/testCocoapodsFramework you can check the "work" folder which include the framework that doesn't work. If you run the project you can see that is going to crash when it calls the extension method.

**Comment by gabrielafonsogoncalves** [comment]
@segiddins @themackworth I manage to make it work. I just need to add some extra frameworks like this:

`s.frameworks = 'SystemConfiguration', 'Accelerate', 'MobileCoreServices'`

so I agree with @themackworth, it is not a Cocoapods issue. Going to close this issue.

Thanks for your help :+1:
