### ISSUE TITLE
Don't stop development, support ObjC

### ISSUE THREAD

**Issue by jafara** [CocoaPods/CocoaPods#4623]
Apple announced Swift Package Manager which very early in development. If you are going to give up Swift support in CocoaPods then please continue work on ObjC. There are countless of apps that use ObjC and are too big to be converted to Swift.

**Comment by alloy** [comment]
Hi, thanks for reaching out and letting us know :+1: 

Over the next days we’ll be reviewing the situation and if and how CocoaPods makes sense to continue.

**Comment by alloy** [comment]
FYI https://github.com/CocoaPods/guides.cocoapods.org/pull/91

**Comment by orta** [comment]
This isn't actionable alas, other than, well continuing to keep working  on CP. So this issue isn't something we should keep around, thanks for the input @jafara! We all still have projects that depend on CP.
