### ISSUE TITLE
Class is implemented in both warning when running unit tests

### ISSUE THREAD

**Issue by aydegee** [CocoaPods/CocoaPods#4626]
When the unit test target includes a pod which shares dependencies with that from the application target, Xcode shows the following in the debug console when running the unit tests e.g.

> Class `AFQueryStringPair` is implemented in both `/Users/andrew/Library/Developer/CoreSimulator/Devices/7BBE0E8C-6CD1-4BFC-88CA-60BC2523DE75/data/Containers/Bundle/Application/4A81F309-461E-4A31-8C60-64FBF8C6EA03/DuplicateClassImplementation.app/DuplicateClassImplementation` and `/Users/andrew/Development/example/DuplicateClassImplementation/Build/Products/Debug-iphonesimulator/DuplicateClassImplementationTests.xctest/DuplicateClassImplementationTests`. One of the two will be used. Which one is undefined

I've created a sample project which demonstrates the issue using the RestKit and RestKit/Testing pods. https://github.com/aydegee/DuplicateClassImplementation.git. However, it doesn't appear to be specific to RestKit because we've experienced it with our own internal pods as well.

This only happens when running the tests in the iOS9 simulator. iOS 8.4 simulator is fine.
We've been able to reproduce this with CocoaPods 0.37.2 and CocoaPods 0.39.0

At first I thought it was this issue https://github.com/CocoaPods/CocoaPods/issues/4355 but the solution doesn't seem applicable?
Is this a CocoaPods problem and is there a Podfile configuration that would fix it? Thanks.

**Comment by segiddins** [comment]
Yup, the podfile refactor I've been working on will fix this.

**Comment by aydegee** [comment]
Ah that's great. Thanks very much.

**Comment by Rahul0106231** [comment]
Im facing the same issue , did we get the solution for this ?

**Comment by dzensik** [comment]
Any news on this? We have the same issue.

**Comment by neonichu** [comment]
1.0 contains the podfile refactor which resolves this.

**Comment by dzensik** [comment]
Thank you for the quick answer! However 1.0.0 is available as beta 6 right?

**Comment by segiddins** [comment]
Yes

**Comment by dzensik** [comment]
Just installed the 1.0.0 beta 6 and have the same issue as previously.

>
> objc[6594]: Class GAIUtil is implemented in both /var/containers/Bundle/Application/0A8AA964-4FCA-4E42-831B-9911AEA8164E/App.app/App and /var/containers/Bundle/Application/0A8AA964-4FCA-4E42-831B-9911AEA8164E/App.app/PlugIns/App Unit Tests.xctest/App Unit Tests. One of the two will be used. Which one is undefined.
> objc[6594]: Class GAIEcommerceFields is implemented in both /var/containers/Bundle/Application/0A8AA964-4FCA-4E42-831B-9911AEA8164E/App.app/App and /var/containers/Bundle/Application/0A8AA964-4FCA-4E42-831B-9911AEA8164E/App.app/PlugIns/App Unit Tests.xctest/App Unit Tests. One of the two will be used. Which one is undefined.
> 

The Podfile is:

> target 'App' do
> 	pod 'GoogleAnalytics' , '~> 3.0'
> 	pod 'GoogleTagManager' , '~> 3.0'
>     
>     pod 'SDWebImage', '~>3.7'
>     platform :ios, '8.0'
>     use_frameworks!
> end
> 
> target 'App Enterprise' do
> 	pod 'GoogleAnalytics' , '~> 3.0'
> 	pod 'GoogleTagManager' , '~> 3.0'
>     
>     pod 'SDWebImage', '~>3.7'
>     platform :ios, '8.0'
>     use_frameworks!
> end

I already read some posts about this issue and look into non trivial Podfiles like https://github.com/artsy/energy/blob/master/Podfile I would much appreciate you advice!

**Comment by orta** [comment]
This Podfile doesn't seem to include a test target? Unless `App Enterprise` is your test target, in which case you are indeed included those classes twice.

I'd recommend looking at [this Podfile](https://github.com/artsy/eigen/blob/master/Podfile) for a 1.0 example, notably this is how you handle [test targets](https://github.com/artsy/eigen/blob/master/Podfile#L111-L112)

**Comment by dzensik** [comment]
Thank you for the help. Now it works. I had just put the App Unit Test target into the Main App target:

> target 'App' do
> 	pod 'GoogleAnalytics' , '~> 3.0'
> 	pod 'GoogleTagManager' , '~> 3.0'
>     
>     pod 'SDWebImage', '~>3.7'
>     platform :ios, '8.0'
>     use_frameworks!
>     
>     target 'App Unit Tests' do
>         inherit! :search_paths
>     end
> end
> 
> target 'App Enterprise' do
>     pod 'GoogleAnalytics' , '~> 3.0'
>     pod 'GoogleTagManager' , '~> 3.0'
>     
>     pod 'SDWebImage', '~>3.7'
>     platform :ios, '8.0'
>     use_frameworks!
> end
