### ISSUE TITLE
Unable to have two targets use two different subspecs in the same project

### ISSUE THREAD

**Issue by plivesey** [CocoaPods/CocoaPods#4629]
In my specific example, I have a library with two subspecs: Main and Test. Main is to be used in the main application, and Test is to be used only in the unit tests target. Test requires XCTest framework so cannot be used in the main application.

I've created a sample project which demonstrates this problem. I'm able to run the application target, but not the unit tests (it actually runs, but errors out).

https://github.com/plivesey/CocoapodsSubspecProblems/

This problem seems to be related to #4370, but I decided to create a new ticket because this ticket seems to complain about the warning (saying it's harmless), but in my case, I cannot actually run the project.

ps. It seems like what I want to do is something like:
```
import Pods_PodsSubspecTest_MyLib // In main app
import Pods_PodsSubspecTestTests_MyLib // In unit tests
```
But it complains that this module cannot be found. Is there a workaround which would allow me to use an import like this?

**Comment by segiddins** [comment]
Not really, the best bet is to use a separate pod instead of subspecs as far as I can think

**Comment by plivesey** [comment]
Yeah, I was wondering if that would be the solution. On a semi related question, if I were to go with two pods (MyLibWithTest, MyLib), would I be able to easily deprecate one of them in the future if this functionality is ever added to CocoaPods? As in, deprecate without deleting and confusing everyone who's projects won't build anymore with no useful error message.

**Comment by segiddins** [comment]
Yup! Podspecs can specify deprecation.

**Comment by plivesey** [comment]
Ok. Thanks for your quick help. I'd suggest keeping this open as a feature request if you think it may be supported sometime in the future? But otherwise, feel free to close as I have all the info I need.

**Comment by segiddins** [comment]
I don't think so -- in fact, the Podfile DSL refactor I've been working on will make getting into this situation harder -- but thanks for writing up a great issue!

**Comment by plivesey** [comment]
Sounds good. Thanks.
