### ISSUE TITLE
Can not set the bundle identifier of a pod in a podspec

### ISSUE THREAD

**Issue by sebastienbrault** [CocoaPods/CocoaPods#4632]
For a pod I have created, cocoa pod set org.cocoapods as prefix for the bundle identifier of my pod. I would like to be able to set my own prefix but I did not find any option to do that in a podspec.Does this option exist ?

Regards. 
Sébastien.

**Comment by segiddins** [comment]
No, this option currently does not exist.

**Comment by sebastienbrault** [comment]
OK, thanks.

**Comment by sebastienbrault** [comment]
It could be a useful option to use Storyboard references : 

<img width="522" alt="capture d ecran 2015-12-07 a 15 07 52" src="https://cloud.githubusercontent.com/assets/473751/11628817/7d3a59b2-9cf4-11e5-936e-c7f0df4e79c4.png">

To link to a storyboard provided through a pod, I need to specify the stroyboad name and the bundle identifier (it does not work without the bundle). 

So I would like to use my own prefix instead of org.cocoapods.

Regards.
Sébastien.

**Comment by orta** [comment]
I think this is good example of why the attribute, and we'd _probably_ take a very well tested Pull Request with the feature, but we're very conservative in respect to adding DSL attributes to the Podspec. 

Each new attribute makes it harder to ensure all of the possible Podspec working perfectly. I doubt we'll ever change the `org.cocoapods` prefix, so it's a low priority for us to add the complexity from another attribute when it works currently as a convention.

**Comment by neonichu** [comment]
Allright, let's close this as we are not going to tackle this ourselves.

**Comment by sebastienbrault** [comment]
A possible workaround is to use the post_install handler. Here is a sample script : https://gist.github.com/daltonclaybrook/e109033af85e6efd6972
