### ISSUE TITLE
pod lib create missing LaunchScreen

### ISSUE THREAD

**Issue by onmyway133** [CocoaPods/CocoaPods#4633]
Hi, using `pod lib create` with Example demo option will create a project, but it misses the `LaunchScreen.storyboard`. And that will cause http://stackoverflow.com/questions/32641240/ios-9-xcode-7-application-appears-with-black-bars-on-top-and-bottom

**Comment by segiddins** [comment]
I believe this belongs on the pod-template repo

**Comment by onmyway133** [comment]
@segiddins thanks, I will ask on `pod-template`
