### ISSUE TITLE
commit 8dc7e3e defaults pod deployment target to iOS 4.3

### ISSUE THREAD

**Issue by oliverhu** [CocoaPods/CocoaPods#4636]
Previously, the default deployment target is the environment set by platform :ios, '8.0'. Each pod library will take the Pod project setup.

However, after that commit, each Pod target explicitly sets IPHONEOS_DEPLOYMENT_TARGET to iOS 4.3 and all pods using 'weak' keyword / auto layout (dynamic library) will fail to build.

**Comment by segiddins** [comment]
Those Pods have the incorrect deployment target set in their specification, I'm guessing.

**Comment by oliverhu** [comment]
@segiddins they have not deployment target set in the podspec. But still, we should default to the Pod project specification, not 4.3?

**Comment by segiddins** [comment]
Nope, the default iOS deployment target is 4.3. If they don't support that, they need to specify a deployment target in the podspec.
