### ISSUE TITLE
Method for setting up a clean project

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4637]
Currently Xcodeproj's method for creating a project makes a few assumptions which is great for Cocoapods but not so much for other gems.

In xcake I made a subclass where I could setup the Project my own custom way:
https://github.com/jcampbell05/xcake/blob/master/lib/xcake/xcode/project.rb

When I was creating a project where it wasn't setting the object version so I had to manually make it return latest all the time.

It also added two configurations "Debug" and "Release", 

Xcake needed for these to not be there so it could keep track of what it had added (The User may for some reason not like these names in which case Xcake would have has to remove them). So I only add configurations the user specifies (or debug or release as defaults if they don't but the gem still retains full control), my method in my subclass only setups up a blank project, nothing more, nothing less.

I realise that without these configurations the xcode project can't open, so maybe there is some way when we save we could generate some default configurations for it to open :)

**Comment by segiddins** [comment]
It sounds like this issue would better belong over on https://github.com/CocoaPods/Xcodeproj?

**Comment by jcampbell05** [comment]
@segiddins  belonged voer there, sorry!
