### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by velikanov** [CocoaPods/CocoaPods#4642]
![ce58d32fb4](https://cloud.githubusercontent.com/assets/4798469/11697059/d57a1f1a-9ec8-11e5-9e2a-d9c81909106e.jpg)

for about… 30-40 minutes

**Comment by segiddins** [comment]
Thanks for the heads up! I've restarted the server and things appear to be working now.

**Comment by velikanov** [comment]
:+1: thank you!
