### ISSUE TITLE
Operation timeout

### ISSUE THREAD

**Issue by sachmans** [CocoaPods/CocoaPods#4643]
Hi everyone,

We are seeing this issue:
`rescue in receive_message_on_socket': Timed out waiting on socket read. (Mongo::OperationTimeout)

Is this an issue with the mongodriver?  Anyone else had a problem? Everytime I run this now it starts to import again (and you can imagine after 13m records I don't want to start again)

So my questions:
1. Is there a way to in the initial import track where it got to so it doesn't start again
2. Has anyone else experienced the timeout issue?

=== Here is the fuller log before it ===

[2015-12-06T19:11:18.239385 #18888] DEBUG -- : (0.005296s) INSERT INTO "images" ("image_uid", "date_taken", "location", "index_img", "permission", "owner_id", "updated_at", "privacy_setting", "status", "region", "album_id", "upload_status", "views", "comments", "likes", "_extra_props") VALUES ('559cb5186170700a6ac81f00', '2015-07-08 04:02:18.000000+0000', NULL, 27322, '{}', '551c7e2f6170706a28a65e00', '2015-07-08 05:28:56.859000+0000', 1, 0, 1, '559cb5186170700a6ad41f00', NULL, NULL, NULL, NULL, '{"b":252555}') RETURNING "image_uid"
 INFO MoSQL: Imported 13572000 rows (67100.413586931s, 63683.05204914429s SQL)...
/var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/networking.rb:336:in `rescue in receive_message_on_socket': Timed out waiting on socket read. (Mongo::OperationTimeout)
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/networking.rb:330:in `receive_message_on_socket'
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/networking.rb:191:in `receive_header'
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/networking.rb:182:in `receive'
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/networking.rb:146:in `receive_message'
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/cursor.rb:606:in `send_get_more'
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/cursor.rb:534:in `refresh'
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/cursor.rb:139:in `next'
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/cursor.rb:342:in `each'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:146:in `block (2 levels) in import_collection'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:70:in `block in with_retries'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:68:in `times'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:68:in `with_retries'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:145:in `block in import_collection'
        from /var/lib/gems/1.9.1/gems/mongo-1.12.4/lib/mongo/collection.rb:291:in `find'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:144:in `import_collection'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:122:in `block (2 levels) in initial_import'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:120:in `each'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:120:in `block in initial_import'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:108:in `each'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:108:in `initial_import'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/streamer.rb:28:in `import'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/cli.rb:172:in `run'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/lib/mosql/cli.rb:16:in `run'
        from /var/lib/gems/1.9.1/gems/mosql-0.4.3/bin/mosql:5:in `<top (required)>'
        from /usr/local/bin/mosql:23:in `load'
        from /usr/local/bin/mosql:23:in `<main>'

**Comment by orta** [comment]
I think you've posted this to the wrong repo, this is for CocoaPods the iOS/Mac dependency manager.
