### ISSUE TITLE
Pod project settings

### ISSUE THREAD

**Issue by danipralea** [CocoaPods/CocoaPods#4646]
Hello. Each time I'm adding the pod, it's overriding the project's setting : Build Active Architecture Only to YES, and I always need to turn it back to NO in order to be able to compile.

Is there any way I can have that setting to remain as it is after updating the podfile every time and not have to change it every time?

Thanks in advance.

**Comment by neonichu** [comment]
The Pods project will be regenerated each time you run `pod install` — see <https://guides.cocoapods.org/syntax/podfile.html#post_install> for documentation on how to make such a change programmatically.
