### ISSUE TITLE
Embedded framework that uses Cocoa Pods does not load dlibs 

### ISSUE THREAD

**Issue by stringcode86** [CocoaPods/CocoaPods#4650]
# CocoaPodsIssueSample
I have Swift iOS project called `Sample`. `Sample` project embeds framework `SampleKit`. `SampleKit` uses cocoa pods. 
```
platform :ios, '8.0'
use_frameworks!

target 'SampleKit' do
  pod 'Alamofire', '~> 3.0'
end
```
When I run it on simulator it works fine. Whe I run on device it fails to load dlibs

```
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/mobile/Containers/Bundle/Application/B3646E19-3239-460D-8304-215A0C2E4F7F/Sample.app/Frameworks/SampleKit.framework/SampleKit
  Reason: image not found
```

Have been banging my head against it hours now. What am I doing wrong ?

Pods version : 0.39.0
Sample project : https://github.com/stringcode86/CocoaPodsIssueSample

**Comment by segiddins** [comment]
CocoaPods does not support integrating into frameworks, instead we recommend making SampleKit into a pod.

**Comment by stringcode86** [comment]
Thank your reply, is this something that is potentially going to be supported in a future ?

**Comment by segiddins** [comment]
Likely not.
