### ISSUE TITLE
Generated Framework Search Path No Longer Valid in Xcode 7.2

### ISSUE THREAD

**Issue by mikehenson** [CocoaPods/CocoaPods#4651]
When building the example project of a newly-initialized pod lib, there is a warning for a missing Framework search path when building with Xcode 7.2:

(cocoapods version: 0.39.0)
pod lib create ReproduceIssue

language: Swift
Include demo: No
Include testing: None
View based testing: No

Select "ReproduceIssue-Example" target and an iPhone simulator.
Build.
The following warning should appear:

"ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/Developer/Library/Frameworks'"

The correct framework path is also included in the build command:
"-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks"

So, this warning is just an unnecessary build option.

**Comment by segiddins** [comment]
I believe this has been fixed on master?

**Comment by mikehenson** [comment]
I didn't see anything similar in the closed issues list. I've tried running Cocoapods from master with:

git clone https://github.com/CocoaPods/CocoaPods.git
cd CocoaPods
bundle install
bundle exec pod lib create
etc...

The resulting project from that process still had this issue.

**Comment by segiddins** [comment]
Ok we'll look into it, thanks!

**Comment by neonichu** [comment]
lol, I think they changed it back in Xcode 7.2 — the path we removed in c128c5a4d7af91e88a40fd714563ecf10af6ec17 exists again, but the other one has been removed 😢

**Comment by yogesh-zendrive** [comment]
Any updates on this?

**Comment by neonichu** [comment]
This is still a valid issue, so I'm going to keep it open.

**Comment by mitchtreece** [comment]
Any update on this? Still an issue a year later.

**Comment by jlubeck** [comment]
Ok, I just did: https://github.com/CocoaPods/CocoaPods/issues/7703

Thanks!

**Comment by dnkoutso** [comment]
@jlubeck thank you!
