### ISSUE TITLE
Pushing a new release doesn't update documentation

### ISSUE THREAD

**Issue by gk-brown** [CocoaPods/CocoaPods#4654]
I recently pushed the Podspec for MarkupKit 1.5. The documentation for that specific version was published correctly:

http://cocoadocs.org/docsets/MarkupKit/1.5/

However, the main docs still reflect an earlier version:

https://cocoapods.org/pods/MarkupKit

It seems like the main docs should always reflect the most recent release.

**Comment by segiddins** [comment]
@gk-brown it takes some time for stuff to propagate. I see that now version 1.5 is showing up on cocoapods.org.
