### ISSUE TITLE
pod lint returns an error, but xcode compiler executes this code correctly without warnings

### ISSUE THREAD

**Issue by priore** [CocoaPods/CocoaPods#4658]
[!] Found podspec `SnowFallingFramework.podspec` (https://github.com/priore/SnowFalling)
Updating spec repo `master`
Validating podspec
 -> SnowFallingFramework (1.4.3)
    - WARN  | [iOS] license: Unable to find a license file
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  __SnowFallingFramework/SnowFalling/Classes/SnowFalling.m:72:1: error: property with 'retain (or strong)' attribute must be of object type__

[!] The podspec does not validate.

**Comment by orta** [comment]
You could have a  different version of Xcode on the command line compared to what you are using via the GUI. Try add `--verbose` to the command and check which version it is running against.

**Comment by priore** [comment]
Many thanks, i update the cmd line and now work fine, thanks for fantastic fast response!
