### ISSUE TITLE
The issue of installing cocoapod

### ISSUE THREAD

**Issue by MarcSteven** [CocoaPods/CocoaPods#4660]
open the shell and then input the order:sudo gem install cocoapods .then display the information as below:
"Successfully installed cocoapods-0.39.0
Parsing documentation for cocoapods-0.39.0

1 gem installed"

My version of Ruby is "ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin15.0.0]".

And then I executed this order,but error displayed these information as picture....I was puzzled about it..I cannot solve it by myself....
The version of Mac:10.11.2
The version of Xcode:7.2
The version of shell:v2.6.1(361.1)
<img width="564" alt="2015-12-10 12 51 10" src="https://cloud.githubusercontent.com/assets/13824297/11772648/8a6a0712-a259-11e5-9704-e1a40dcd8269.png">
Thank for your help,everyone...

**Comment by neonichu** [comment]
Since you are using `rvm`, `gem install cocoapods` might be more appropriate. Using `sudo` will install the gem system-wide.

**Comment by MarcSteven** [comment]
Thank you so much....
