### ISSUE TITLE
"Gather Coverage Data" and Pods

### ISSUE THREAD

**Issue by attheodo** [CocoaPods/CocoaPods#4661]
Hello, 
I am trying to enable Code Coverage Data by checking the respective checkbox in my scheme for the Testing phase. However when I am trying to build & run my tests (cmd + U) I am getting a builder error `ld: framework not found Pods`

Any ideas?

**Comment by neonichu** [comment]
Your description is quite broad, please have a look at [our contribution guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) on how to post an actionable issue.

**Comment by segiddins** [comment]
Closing due to lack of response.
