### ISSUE TITLE
prepare_command not working for subspecs

### ISSUE THREAD

**Issue by andreacremaschi** [CocoaPods/CocoaPods#4662]
Hi,

when defining different subspecs in a .podspec, subspecs' `prepare_command`s are not executed.
I.e., I want to write a pod spec that contains two subspecs: `Core` builds a fat library while installing using a Makefile, `Prebuilt` distributes a precompiled version of the library:

```ruby
  s.subspec "Core" do |sp|
    sp.prepare_command = <<-CMD
      make
    CMD
    sp.source_files = "include/geos_c.h"
    sp.vendored_libraries = "lib/libgeos_c.dylib", "lib/libgeos.dylib"
    sp.public_header_files = "include/geos_c.h"
  end

  s.subspec "Prebuilt" do |sp|
    sp.prepare_command = <<-CMD
       # TODO: download the prebuilt distribution package
    CMD
    sp.source_files = "include/geos_c.h"
    sp.vendored_libraries = "lib/libgeos_c.dylib", "lib/libgeos.dylib"
    sp.public_header_files = "include/geos_c.h"
  end

  s.default_subspec = "Core"
```

This works correctly if not using subspecs, i.e.:

```ruby
    s.prepare_command = <<-CMD
      make
    CMD
    s.source_files = "include/geos_c.h"
    s.vendored_libraries = "lib/libgeos_c.dylib", "lib/libgeos.dylib"
    s.public_header_files = "include/geos_c.h"
```

Note: this issue improves https://github.com/CocoaPods/CocoaPods/issues/3575 that was poorly described but have been closed, probably by mistake.

**Comment by segiddins** [comment]
This is intentional. The prepare command is a root attribute only -- it only applies on the root spec. If you need multiple, I advise splitting your subspecs out into separate pods.

**Comment by andreacremaschi** [comment]
Ok thanks
