### ISSUE TITLE
Linker input unused

### ISSUE THREAD

**Issue by cojoj** [CocoaPods/CocoaPods#4663]
I've currently jumped into older project and there seems to be some sort of problems with CocoaPods.
Whenever I try to build or run the application amongst all other project warnings I get these two (which actually are many, but condensed into two...)

<img width="235" alt="zrzut ekranu 2015-12-14 o 21 52 17" src="https://cloud.githubusercontent.com/assets/4522407/11793629/facb98b0-a2ac-11e5-87df-d1cefe6edb1c.png">

When I try to find out more about them I actually get nothing 😒
So I dug into where these two things are used and it turned out that everything leads me to **Build Settings** and to section called **Custom Compiler Flags**, so I've tried to remove values which were stored there.
No luck here either 😭 Now when I run `pod install` I get this:

```
[!] The `XYZ [Debug]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYZ [Release]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

It's actually not that big a deal, because I can run app using Xcode, but when I switch to AppCode it breaks, because it can't find some dependency files etc.

Maybe anyone know what's going on?

**Comment by neonichu** [comment]
![](http://www.reactiongifs.com/r/do.gif)

I'm guessing you now overwrote some settings instead of removing them? Or did you get the warnings about `OTHER_CFLAGS` previously as well?

**Comment by cojoj** [comment]
@neonichu since day one I'm in this project there were those two warnings, and `OTHER_CFLAGS` started showing after I removed them from **Custom Compiler Flags**.
Right now I got everything back to the state where I have those two warnings, cause in this scenario I can run the project 😂

Also, somewhere there might blink an info that some of my targets are overriding `Targets Support Files/Pods/Pods.debug.xcconfig` and `Targets Support Files/Pods/Pods.release.xcconfig`.

**Comment by neonichu** [comment]
OK, so you didn't remove `OTHER_CFLAGS` but are now setting it to `""` — to actually remove a build setting so that it can be derived from the XCConfigs again, you need to highlight and hit delete in Xcode. I'm thinking your initial warnings also arise from build settings being manually edited.

**Comment by cojoj** [comment]
![zrzut ekranu 2015-12-15 o 10 31 56](https://cloud.githubusercontent.com/assets/4522407/11807003/1c6e6f8c-a317-11e5-8b48-4e7e823773c3.png)

So when I remove everything I get this:
```
[!] The `XYZ [Debug]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `XYZ [Release]` target overrides the `OTHER_CFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by neonichu** [comment]
Hm, is there maybe an override still being done at the project level?

**Comment by cojoj** [comment]
Boom 💥
That was the case here! 

@neonichu thanks for your help 😉
