### ISSUE TITLE
Framework with only headers

### ISSUE THREAD

**Issue by ronak2121** [CocoaPods/CocoaPods#4664]
Hello,

We're trying to make frameworks that contain nothing but public Objective-C header files. We've noticed that Cococpods version 0.39.0 does not actually generate a .framework out of these header files, while Xcode itself does it without issue.

We saw that if we put a dummy source file, everything seems to be fine. Is there a reason why Cocoapods has this limitation? Can this be fixed?

Our pod spec looks similar to:

Pod::Spec.new do |s|

  s.name = "APMetrics"

  s.author = { 'Ronak Patel' => 'test@test.com' }

  s.license	= {:type => 'NONE', :text => 'LICENSE Not for Outside Distribution LICENSE' }

  s.homepage = "<home page>"

  s.summary = "..."

  s.ios.deployment_target = '8.0'

  s.osx.deployment_target = '10.10'

  s.tvos.deployment_target = '9.0'

  s.watchos.deployment_target = '2.0'

  s.version = "0.0.3"

  s.source = { :git => "ssh://git.privateServer.com/pkg/APMetrics", :tag => s.version }

  s.frameworks = 'Foundation'

  s.public_header_files = "Source/**/*.{h}"

  s.source_files = "Source/**/*.{h,m,swift}"

  s.requires_arc = true

end

**Comment by segiddins** [comment]
It's actually done intentionally, to allow linking transitive static dependencies if necessary. I'd recommend just adding a dummy source file.

**Comment by ronak2121** [comment]
Can we make this dummy source file private as well?
