### ISSUE TITLE
"Redefinition of X" errors in 0.39

### ISSUE THREAD

**Issue by linqiang** [CocoaPods/CocoaPods#4665]
I'm import masonry by coocapods,the Xcode give me errors in " static const
![2015-12-15 11 39 32](https://cloud.githubusercontent.com/assets/3182952/11801410/8a389e8a-a320-11e5-81c0-fec3289ec3ee.png)
 redefinition of ..." thx for your help

**Comment by neonichu** [comment]
This issue was caused by a compiler change in Xcode 7.1 and has been fixed on `master`.
