### ISSUE TITLE
Pods for universal frameworks

### ISSUE THREAD

**Issue by SiarheiFedartsou** [CocoaPods/CocoaPods#4666]
Hi! I am using [universal framework config](https://github.com/mrackwitz/xcconfigs) to build framework with shared logic for my iOS and tvOS app. My Podfile looks like this
```ruby
...
target 'UniversalFramework' do
#	platform :tvos, '9.0'
#	platform :ios, '8.0'
#     MY DEPENDENCIES HERE
end
...
```
But now I have to define concrete platform(tvos or ios) when I build my framework. For example when I'm going to build framework for iOS I have to go to Podfile and uncomment ```platform :ios, '8.0'``` line, and when I'm going to build framework for tvOS I have to go to Podfile and uncomment ```platform :tvos, '9.0'``` line. Is there some solution for such problem?

**Comment by neonichu** [comment]
This is not supported, a `target` needs to have exactly one `platform`.

**Comment by SiarheiFedartsou** [comment]
@nenichu And you don't even plan to support such kind of targets?

**Comment by segiddins** [comment]
@SiarheiFedartsou not really, no. We reccomend that frameworks that need to link against pods be built via CocoaPods and a podspec themselves.

**Comment by SiarheiFedartsou** [comment]
@segiddins Okay... So, I need to make custom pod for my framework and then use it?

**Comment by segiddins** [comment]
That would be what I'd recommend

**Comment by orta** [comment]
:+1:
