### ISSUE TITLE
pod install assuming specific state ? 

### ISSUE THREAD

**Issue by gemmakbarlow** [CocoaPods/CocoaPods#4668]
Hi CocoaPods team,

Just wanted to alert you to an issue I saw quite a while ago now, but one that seems to be ongoing due to the upvotes I've been receiving over the past year on my StackOverflow answer. 

Here's the initial problem:
http://stackoverflow.com/questions/23489920/error-ld-library-not-found-for-lpods-with-cocoapods

Here's my answer (and speculative reasoning)
http://stackoverflow.com/a/26724469/189711

Happy to help with further investigation where required.

- G

**Comment by segiddins** [comment]
@gemmakbarlow can you provide steps to reproduce the issue?

**Comment by gemmakbarlow** [comment]
Yup - can take a look @ this over the weekend.

**Comment by segiddins** [comment]
Closing due to lack of response.
