### ISSUE TITLE
'string' file not found

### ISSUE THREAD

**Issue by SiarheiFedartsou** [CocoaPods/CocoaPods#4669]
Hi! I'm trying to make a custom pod from my framework. I've written such podspec:
```json
{
  "name": "ViadenGamingPlatform",
  "version": "0.0.2",
  "license": {"type": "proprietary", "text" : "Copyright by Viaden Media 2015"},
  "summary": "Viaden Gaming Platform API",
  "homepage": "http://viaden.com",
  "authors": "Siarhei Fedartsou",
  "requires_arc": true,
  "source_files": ["ViadenGamingPlatform/**/*{h,m,mm,cc,swift}"],
  "exclude_files": "ViadenGamingPlatform/**/*Tests*",
  "dependencies" : {
    "GoogleProtobuf" : [],
    "CocoaAsyncSocket" : [],
    "ReactiveCocoa" : [],
    "Objective-LevelDB" : [],
    "FastCoding" : [],
    "FXKeychain" : [],
    "ViadenCore" : [],
    "ViadenCRMCore" : [],
    "ViadenPokerOdds" : []
  },
  "xcconfig": {
    "HEADER_SEARCH_PATHS": "$(PODS_ROOT)/GoogleProtobuf/src"
  },
  "source": {
    "path": "."
  },
  "frameworks": [
    "CoreLocation",
    "AdSupport",
    "StoreKit"
  ],
  "platforms": {
    "ios": "8.0",
    "tvos": "9.0"
  }
}
```

I have some public headers with C++ code and when I'm trying to build this podspec I see:
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/sergey.fedortsov/Poker/Pods/Target Support Files/ViadenGamingPlatform/ViadenGamingPlatform-umbrella.h"
        ^
/Users/sergey.fedortsov/Poker/Pods/Target Support Files/ViadenGamingPlatform/ViadenGamingPlatform-umbrella.h:4:9: note: in file included from /Users/sergey.fedortsov/Poker/Pods/Target Support Files/ViadenGamingPlatform/ViadenGamingPlatform-umbrella.h:4:
#import "access_management_domain.pb.h"
        ^
/Users/sergey.fedortsov/Poker/ViadenGamingPlatform/ViadenGamingPlatform/gp/access_management_domain.pb.h:7:10: error: 'string' file not found
#include <string>
         ^
<unknown>:0: error: could not build Objective-C module 'ViadenGamingPlatform'
```
![Compiler Errors]
(https://leto33h.storage.yandex.net/rdisk/d2c759dba075980e36e6723e7274843f6949b9a1dad89c9d6ed909659c5a90cd/inf/S08eoiNHJqpcz79T7hDp_4oDXBEZExTdA2BEYzQLWH6oegh6NmdyTo0ZR4Lo4IYNYOmdTMbDaRLcpC-HfDi-cw==?uid=0&filename=2015-12-17%2011-20-47%20ChillingoSocialHoldem.xcworkspace.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&rtoken=8af2563e52041f63c2e175a8cdb4c824&force_default=no&ycrid=na-badaba894a0deb7335aee69495979314-downloader2h)
access_management_domain.pb.h is auto-generated Google Protocol Buffers header and it is public.

How can I fix such error? Is there some approach to make available some headers only from *.mm-files(for example through ```#ifdef __cplusplus```)?

P.S. I need to add that I have some other custom pods that have C++ public headers and it seems to work perfect.

**Comment by neonichu** [comment]
You're including C++ headers in a module that is in turn imported into Swift. This won't work because you cannot import C++ code directly into Swift. The only way out is to create a C or Objective-C++ wrapper.
