### ISSUE TITLE
Stats on implicit dependencies

### ISSUE THREAD

**Issue by ashfurrow** [CocoaPods/CocoaPods#4670]
From @searls' [talk on open source thingies](https://youtu.be/e_-qV8waPVM?t=577), I saw the following idea:

<img width="1440" alt="screen shot 2015-12-16 at 8 00 37 pm" src="https://cloud.githubusercontent.com/assets/498212/11875707/03149360-a4b4-11e5-921a-b44e9f0e9026.png">

I think this would be really cool for CocoaPods. I may take a stab at the easy parts (like # of transitive dependencies) but I imagine the information about # of pods that you'd be unable to use requires more discussion.

**Comment by segiddins** [comment]
Tbh it kinda feels like added noise to me. Why would this information be worth displaying to the user every time?

**Comment by ashfurrow** [comment]
Well there are lots of reasons, which the talk discusses. But framed in the context of the iOS community, consider the common complaint from _those people_ that dislike CocoaPods: developers don't appreciate that their "app" isn't just the code they've written but also the code in their dependencies. This would be a great refutation.

When AFNetworking had that security problem, developers using it had to take responsibility for updating to a new version. Providing context about the software _our software_ uses can help developers be more informed.

**Comment by orta** [comment]
I feel like the last "`bundle update` was unable to update x gems to the last version" is something useful if you have done `bundle update`, maybe less so on an install.

**Comment by segiddins** [comment]
Makes sense.

**Comment by neonichu** [comment]
Aren't we already showing the first part of this?

```bash
[…]
Pod installation complete! There are 2 dependencies from the Podfile and 4 total
pods installed.
```

In this example, two Pods are declared in the Podfile and an additional two are transitive dependencies. Or are we talking about wording?

**Comment by neonichu** [comment]
TBH, I would consider this noise, `pod install` is already very verbose. If we implement this, there should be an off-switch, IMO.

**Comment by orta** [comment]
Going off @neonichu - I agree in general that the current state is good for an install.

I don't think I'd gain anything from knowing about the "preclude the installation of x other pods" on CP, but I do agree with myself here still: https://github.com/CocoaPods/CocoaPods/issues/4670#issuecomment-165516040 :dancers:

**Comment by neonichu** [comment]
Think we can close this as it never went anywhere?
