### ISSUE TITLE
Libraries seem to be linked twice when running unit tests 

### ISSUE THREAD

**Issue by Rahul0106231** [CocoaPods/CocoaPods#4671]
Not sure if this is the right place to bring my issue ,but I have been breaking my head for last 1 week , tried all the solutions described in stack over flow but none of them helped me .. My project is using cocoa pods to add dependancy libraries . Recently i have started writing unit tests for my project , but when i run them i receive the following type of warnings during my unit tests execution from all the classes in third part libraries i have used..

Class AFHTTPRequestOperation is implemented in both 435F-AD72-
37BA5BDD442E/data/Containers/Bundle/Application/2417BC8D-5677-4E2D-B69E- CA0BF7CE93BD/xyz.app/xyzand
/Users/administrator/Library/Developer/Xcode/DerivedData/SkillSoft-canlqtqcxxaqqjejbmeyxszeoqht/Build/Products/Debug- iphonesimulator/xyz.xctest/xyztests. One of the two will be used. Which one is undefined.

Here's my detailed problem statement from stack over flow ..It would be extremely helpful for me if someone looks into it .. 
http://stackoverflow.com/questions/34330538/cocoa-pods-with-unit-tests-issue

P.S Im a complete newbie to pods ,This is the first time im using so please let me know if there is something wrong with pod file or if you need more info ..

**Comment by segiddins** [comment]
This is a known issue that will be addressed with the new podfile DSL I've been working on.

**Comment by Rahul0106231** [comment]
Thanks segiddins for the swift reply.. When can we expect the new podfile ? .. The bigger problem for me here is since the libraries have been linked twice , the static variables in one of the library i have been using(RZVinyl for coredata) is being generated twice which is causing a lot of problem in my unit tests .. Please refer to the stackoverflow link above for the detailed description of the problem .. Is there a work around for it ?

**Comment by segiddins** [comment]
@Rahul0106231 there's an open PR for it now... the only potential workaround is using `exclusive: true` when specifying your test target in your podfile
