### ISSUE TITLE
Remove :head dependency declaration

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#4673]
The `:head` dependency declaration allows to use the last published podspec with the current source code in the repo. That could be easily an untested configuration, if there were structural changes to the pod. The behavior of that declaration isn't quite obvious and easily leads to the misconception that it would use also the latest version of the podspec.

**Comment by segiddins** [comment]
I'm :+1: on this for 1.0

**Comment by segiddins** [comment]
@cocoapods/core will need to weigh in on this

**Comment by orta** [comment]
Yeah, I never use this and never recommend it to people because it really confuses me.

**Comment by neonichu** [comment]
I'm :+1: on this — I think everyone is confused about it at first and doesn't add too much value over explicitly specifying source.

**Comment by levigroker** [comment]
Hey All,

I use this feature quite a bit to pull in internal pods which have code changes often but do not need an updated podspec. What's the best way to accomplish this without having to push a new pod version every code change?

**Comment by neonichu** [comment]
You can use something like `pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git'`

**Comment by levigroker** [comment]
Thanks @neonichu. I'll give it a try.
