### ISSUE TITLE
--sources should not be needed when running lint and pushing with local repo dependencies

### ISSUE THREAD

**Issue by lucacorti** [CocoaPods/CocoaPods#4674]
I'm pushing `podspecs` to a local repo. When running `pod lib lint `, `pod spec lint` and `pod repo push` I need to add `--sources=my-repo,master` so that dependencies from the local repository are resolved.

Is this expected behavior? Shouldn't this be handled automatically if the repo is added via pod repo add?

**Comment by orta** [comment]
It's expected that you'd use `--private` which should negate the need for those, and a few other tests.

**Comment by lucacorti** [comment]
With `pod lib lint --private` I still get:

```
 - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `MyPodA` depended upon by `MyPodB`) during validation.
```

**Comment by neonichu** [comment]
It cannot be automatically handled for the same reasons non-default sources need to be explicit in the Podfile, e.g. the order of sources has meaning. The behaviour is supposed to match [the Podfile](https://guides.cocoapods.org/syntax/podfile.html#source).

**Comment by orta** [comment]
Makes sense
