### ISSUE TITLE
Pod targets have odd precompiled headers based on configuration name

### ISSUE THREAD

**Issue by DougBanksPersonal** [CocoaPods/CocoaPods#4675]
My project has several different configurations.  Three based on debug, where I want everything "debug" flavored, like DEBUG=1 set as preprocessor flag.
![screen shot 2015-12-18 at 10 44 38 am](https://cloud.githubusercontent.com/assets/7455525/11904778/6072f56a-a577-11e5-8567-d3ce3b9aad0d.png)

When I run pod install and check the preprocessor flags on pod project's targets, it seems to have dropped the DEBUG=1 flag and added some flag based on configuration name:
![screen shot 2015-12-18 at 10 46 55 am](https://cloud.githubusercontent.com/assets/7455525/11904809/8f437324-a577-11e5-9936-b48b303041b4.png)

For the React pod target, I want/need it to have the DEBUG=1 flag set.

I can set that by hand after running pod install, but then things get reset when I run pod install again (I have to do that a lot, separate issue).

With a lot of pain, using post_install command, I got what I want (pod_install sets DEBUG=1 flag on pod targets for my debug-flavored configs).  But this felt bizarrely complicated.  Shouldn't a configuration derived from the default Debug config automatically propagate DEBUG=1 flag on all related targets?

**Comment by segiddins** [comment]
@mrackwitz thoughts on this proposal?

**Comment by neonichu** [comment]
One can already configure configurations as being based on another in the Podfile:

```ruby
xcodeproj 'WordCounter', 'Debug In Memory' => :debug, 'Debug Test Data' => :debug
```

This may or may not do what is asked, but is in any case the minimum configuration needed for CP to even know that a configuration is based on another.

**Comment by DougBanksPersonal** [comment]
This may be more a commentary on my skills than your project, but this not working as I expected it to cost several days to deal with.  A few days to figure out why Debug features on React Native weren't working (because DEBUG=1 is set for my project but not for the React Native cocoa pod) and a few more days to figure out why that's true and what I can do about it (learn about how to do post-install config, do the right one, deal with other issues that cropped up).

I don't understand the answer given by @neonichu. Meaning, in those days I spent researching all this, that solution never came up.  Not sure how/where I would discover that.  Also don't know what 'CP' is, or what the given code snipped would actually do (like what is "Debug In Memory", the name of a configuration?)

**Comment by mrackwitz** [comment]
Using further custom configurations is from my regard not quite a beginner option. But that shouldn't be a justification that overall this could be a bit more user-friendly and obvious. If you see something, CocoaPods could do better, your proposals are welcome.

>Also don't know what 'CP' is

CP is short for **C**ocoa**P**ods.

> or what the given code snipped would actually do (like what is "Debug In Memory", the name of a configuration?)

The CocoaPods Guides' [Podfile Syntax Reference](https://guides.cocoapods.org/syntax/podfile.html#xcodeproj) documents, where and how you can specify further custom configurations and how they should be treated. So yes, "Debug In Memory" should be here an example for a user-defined configuration.

**Comment by mrackwitz** [comment]
@segiddins: You were referencing me here earlier. I'm not sure whether that really was originally intended as a proposal, but the derived name could be indeed improved by taking camel-case into account. We had another discussion, whether we want to add those macros at all. I wasn't able though to find the ticket for that. I think we decided that they should be prefixed at least with `POD_`.

**Comment by neonichu** [comment]
@DougBanksPersonal sorry for my brief answer. I didn't mean that you should have discovered it on your own, but that we already have some configuration for this and it might do what you need. 

This would belong in the `Podfile` and "WordCounter" would be the name of your Xcode project, "Debug in Memory" and "Debug Test Data" would be the names of your custom build configurations.

**Comment by DougBanksPersonal** [comment]
Cool, thanks.

Appreciate the followup.

Took this job to force me to learn new things... mission accomplished....

Doug

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
