### ISSUE TITLE
Xcode 7.2 Cocoapods 0.39.0 archive is successful does not populate in Organizer. 

### ISSUE THREAD

**Issue by Kkhattab** [CocoaPods/CocoaPods#4676]
I have tried the following from past issues. I have been following related threads closely. 
1. Deleting `Copy Pods Resources` from build phases 
2. I tried unchecking in editing schemes parallelize builds 
3. Tried installing and uninstalling cocoapods 

Here is a screen shot of my successful archive build. Followed by nothing in organizer. 

![]
(https://cloud.githubusercontent.com/assets/6819847/11923116/a578bd7e-a753-11e5-80cb-1874e8bd8b5b.png)

![](https://cloud.githubusercontent.com/assets/6819847/11923122/c3f40466-a753-11e5-987c-ac60148648f8.png)

**Comment by neonichu** [comment]
Can you share an example project that exhibits the issue?

**Comment by Kkhattab** [comment]
@neonichu sure i can try to upload something that exhibits the same issue as soon as possible. Should I upload a zip here? Or create a repository?

**Comment by neonichu** [comment]
A repo would be best, thanks.

**Comment by Kkhattab** [comment]
@neonichu so after running archives on a vanilla project using version 0.39.0 it archives successfully... is there any configurations i may have altered in my actual project that are required?

**Comment by Kkhattab** [comment]
After reinstalling cocoapods like before my `Copy Pods Resources` was re added to my project's build phases. Should I try to remove this again? 

Asking because of i found this https://github.com/CocoaPods/CocoaPods/issues/4274

![screen shot 2015-12-23 at 1 46 50 am](https://cloud.githubusercontent.com/assets/6819847/11974238/3116fc64-a917-11e5-9c9b-2ff0176bb330.png)

**Comment by neonichu** [comment]
That's a specific workaround for WatchKit extensions, if you don't have one, you shouldn't need to delete that build phase.

**Comment by Kkhattab** [comment]
@neonichu would it be possible if i add you to a private repo so you can experience this first hand?

**Comment by Kkhattab** [comment]
@neonichu after checking opening my DerivedData Folder I noticed there was a Archives Folder right above it... there all the archives I was running were being stored there... including my main project that was not showing up in Organizer. 


![screen shot 2015-12-23 at 2 29 09 am](https://cloud.githubusercontent.com/assets/6819847/11974852/fc5de964-a91c-11e5-88bd-97c4fe5af0b5.png)

**Comment by Kkhattab** [comment]
Figured it out. 

1. Searched `Installation Directory` in `Build Settings` 
2. Removed `@executable_path/../Frameworks` as the value for Installation Directory 
3. Typed the following for the Installation Directory  `$(LOCAL_APPS_DIR)` 

Reference: **Xcode successfully archived my application, but the Archives Organizer does not list my archive** https://developer.apple.com/library/ios/technotes/tn2215/_index.html

**Comment by neonichu** [comment]
Interesting, thanks for reporting back your solution.
