### ISSUE TITLE
New podspec unable to link when dependant pods have subspecs, manifests as "Undefined symbols for architecture x86_64:" when building

### ISSUE THREAD

**Issue by limey** [CocoaPods/CocoaPods#4678]
Xcode 7.2, CocoaPods 0.39.0 🌈

It appears than podspecs don't correctly link to dependent pod subspecs. Manifests as compilation errors both in XCode and **pod lint**.  This issue & sample repo podspec [here](https://github.com/limey/pod-subspec-dependency-issue) show the problem. I first noticed this in a .podspec with about a dozen pods. After introducing an AWS subspec dependency, it began failing. Here are steps to reproduce:

* Create a new pod.

```
$ pod lib create PodSubspecDependencyIssue
```
lang = ObjC, demo application = Yes, testing framework = None, view based testing = No, class prefix PSDI

* Edit .podspec and add a dependency to a regular pod, and a subspec.

```
s.dependency 'AFNetworking', '~> 2.3'
s.dependency 'AWSiOSSDKv2/DynamoDB', '~> 2.3'
```

* Run pod install

```
$> pod install
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `PodSubspecDependencyIssue` from `../`
Downloading dependencies
Installing AFNetworking (2.6.3)
Installing AWSCore (2.3.2)
Installing AWSDynamoDB (2.3.2)
Installing AWSiOSSDKv2 (2.3.2)
Installing PodSubspecDependencyIssue 0.1.0 (was 0.1.0)
Generating Pods project
Integrating client project
```

* Add a Pod class that references a subspace dependency. 

See PSDIAWSDynamoImporter.h/.m from the sample project.

* Open workspace in Xcode and try to build the pod
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AWSDynamoDB", referenced from:
      objc-class-ref in PSDIAWSDynamoImporter.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This screenshot shows that the pods project has pulled in references to all required pods.
<img width="515" alt="pod-issue-allpods" src="https://cloud.githubusercontent.com/assets/511328/11952777/fc7f8c08-a8ff-11e5-8e43-e3132bde3850.png">

This screenshot from the pod Scheme shows that the AWSDynamoDB has not been included as a library. However, adding new dependant pods and running **pod update** will add them to this list - so long as they aren't subspecs.

<img width="815" alt="pod-issue-build-targets-no-subspecs" src="https://cloud.githubusercontent.com/assets/511328/11952907/dd205954-a900-11e5-87a9-0ff86fab2b15.png">

Hope this is helpful and that I'm not missing something obvious. Let me know if you need any more info, more than happy to help.

**Comment by neonichu** [comment]
The issue you are seeing is a side-effect of using frameworks integration. As each framework needs to link successfully by itself, it needs to explicitly state all its dependencies. See also discussion in #4141

**Comment by limey** [comment]
Thank you for the help. It was still not clear what syntax to use to import dependencies. The format turns out to be crucial. 

Using the "/" delimiter for path-like reference found the specs, but did not add frameworks to my project correctly so the linking problem persisted:
```
s.dependency 'AWSiOSSDKv2/DynamoDB', '~> 2.3'
s.dependency 'AWSiOSSDKv2/AWSCore', '~> 2.3'
```

Rather, direct referral to the pods using their top level names works:
```
s.dependency 'AWSDynamoDB', '~> 2.3'
s.dependency 'AWSCore', '~> 2.3'
```

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
