### ISSUE TITLE
use_frameworks! issue

### ISSUE THREAD

**Issue by craigzour** [CocoaPods/CocoaPods#4680]
Hi guys,

I currently have a scenario which I can summarize like this:

My app
  -> includes "My internal Pod" library
My internal Pod
  -> includes "AFNetworking" library

I have "use_frameworks!" in the Podfile of "My app". After I deployed it to Crashlytics, I installed the app on an iOS 8.4.1 device and when I started it I got the following error:

"Dyld Error Message:
  Symbol not found: ___NSArray0__
  Referenced from: /private/var/mobile/Containers/Bundle/Application/BDF03503-D81B-4B2A-BD0D-C9C708D31C92/Myapp.app/Frameworks/AFNetworking.framework/AFNetworking (which was built for iOS 9.1)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /private/var/mobile/Containers/Bundle/Application/BDF03503-D81B-4B2A-BD0D-C9C708D31C92/Myapp.app/Frameworks/AFNetworking.framework/AFNetworking
  Dyld Version: 353.12"

Indeed it is working on an iOS 9.1 device. (Not even on iOS 9.2 but I am wondering if this is something different because I am getting a lot of "mis using empty blacklist" logs).

My question is:
- Is there a way to make cocoapods prepare the AFNetworking framework in order to make it compatible with every iOS versions ?

Thank you !

**Comment by neonichu** [comment]
You can set the deployment target inside the Podfile:

```ruby
platform :ios, '8.4'
```

I am assuming you're currently using 9.1 or none at all?

**Comment by craigzour** [comment]
Hi @neonichu,

"My app" podfile specified platform 9.1
"My internal pod" specified platform 9.1

If I changed it to 8.4 is it gonna work with all iOS versions that came after ? Do I need to be consistent about "platform" version between the "Internal pod" spec and "My app" Podfile ?

**Comment by neonichu** [comment]
As far as the linker is concerned, it should work with all newer versions once you specify 8.4. You need to be consistent in so far as your app's minimum deployment target needs to be equal or greater than the one of the pod, e.g. a pod requiring 9.1 won't be allowed to install when your app specifies 8.4, but they don't have to be equal.

**Comment by craigzour** [comment]
Alright, I am gonna test that and I will confirm you if it worked !

**Comment by craigzour** [comment]
@neonichu It perfectly worked ! Thank you for your help :)
