### ISSUE TITLE
Dependency's framework is not propagated to the target app

### ISSUE THREAD

**Issue by VilemKurz** [CocoaPods/CocoaPods#4681]
I am the maintainer of a library. This library has subspecs, and one of them has a dependency - Dropbox ios sdk. **If I do pod install and run the demo project, everything runs fine**. If I run `pod spec lint --subspec=ShareKit/Dropbox --verbose ShareKit.podspec`, the **lint ends with these errors**:

*Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_DBRequest", referenced from:
      objc-class-ref in SHKDropbox.o
  "_OBJC_CLASS_$_DBRestClient", referenced from:
      objc-class-ref in SHKDropbox.o
  "_OBJC_CLASS_$_DBSession", referenced from:
      objc-class-ref in SHKDropbox.o
ld: symbol(s) not found for architecture i386*

and

*Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DBRequest", referenced from:
      objc-class-ref in SHKDropbox.o
  "_OBJC_CLASS_$_DBRestClient", referenced from:
      objc-class-ref in SHKDropbox.o
  "_OBJC_CLASS_$_DBSession", referenced from:
      objc-class-ref in SHKDropbox.o
ld: symbol(s) not found for architecture x86_64*

These 3 missing headers are the only ones from DropboxSDK actually used within my library. I set up demo for a reference, it is [here] (https://github.com/VilemKurz/ShareKit-Demo-App.git), **please make sure you checkout DropboxDemo branch**

Wonder if the problem is in my (ShareKit) podspec, Dropbox podspec or lint? Please help...

**Comment by neonichu** [comment]
`pod spec lint` uses framework integration by default, it might be that the DropboxSDK's podspec doesn't work properly with it. Could you try if passing `--use-libraries` to `lint` helps?

**Comment by VilemKurz** [comment]
`--use-libraries` helped, thank you :+1: Wonder, why the default for podfiles is different? (I suppose they use libraries as default -please correct me, if I am wrong).

**Comment by orta** [comment]
It will do both to ensure it can support both ( for people wanting swift support for example )

On my phone, replies will be curt.

**Comment by igagis** [comment]
This one https://github.com/CocoaPods/CocoaPods/issues/4630 might be related

**Comment by segiddins** [comment]
Closing since `--use-libraries` is the answer in this case.
