### ISSUE TITLE
Strip beta version specifiers.

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4682]
iTunes requires all frameworks to have a version matching this format "x.x.x" however when uploading a library which uses beta notation "x.x.x-betaX" iTunes rejects it.

It would be great if cocoapods could somehow strip this out when making the plist files for frameworks so "2.0.0-beta4" became "2.0.0". Currently I've had to do this manually.

**Comment by segiddins** [comment]
I believe this is already fixed on master?

**Comment by jcampbell05** [comment]
@segiddins I'm currently using 0.39.0, haven't tested it with master.

**Comment by jcampbell05** [comment]
Got a infinite dependancy when trying to install from master.

**Comment by segiddins** [comment]
@jcampbell05 can you be more specific? You `git clone`d CocoaPods/CocoaPods and ran `bin/pod` ?

**Comment by jcampbell05** [comment]
I specified the master branch as a dependancy in my Gemfile but I do have a clone of the repo so I can try that.

**Comment by jcampbell05** [comment]
@segiddins  https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md Can't see this in the changelog for master. Trying `bin/pod` now :)

**Comment by segiddins** [comment]
Closing this as fixed in the 1.0 betas.
