### ISSUE TITLE
XCConfig intergration issues

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4688]
I have two targets I generated with my gem for iOS and a unit test. Cocopods integrates the xcconfigs for the iOS Application on the unit test target as well which then causes it to fail to integrate the unit test's real xcconfigs. How does config  infer how to integrate these to the targets ? I am trying to find a tweak for my gem so cocoapods doesn't get confused.

**Comment by segiddins** [comment]
Can you please be more specific about what's going on that's unexpected behavior? Thanks!

**Comment by jcampbell05** [comment]
@segiddins I have two targets iOS and iOSTests. Pods complains that iOSTests has its XCConfig already set.

I check the project before I ran `pod install` nothing set. But when I look at the file after I ran `pod install`, the XConfig for iOS is integrated with both iOS and iOSTests. When in fact I should have one XCConfig integrated for iOS and another for iOSTests.

There is something about the project generated by my other tool that causes cocoapods to integrate iOS's XCConfig to both iOS and iOSTest, causing it to fail to integrate iOSTest's XCConfig to iOSTest.

Causing this error:

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `iOSTests` to `Pods/Target Support Files/Pods-iOSTests/Pods-iOSTests.release.xcconfig` or include the `Pods/Target Support Files/Pods-iOSTests/Pods-iOSTests.release.xcconfig` in your build configuration.

I'm just wanting to know where a good place to start is ? (I've attached my pre `pod install` file here):
[Project.xcodeproj.zip](https://github.com/CocoaPods/CocoaPods/files/72455/Project.xcodeproj.zip)

**Comment by jcampbell05** [comment]
@segiddins  Does that make sense ?

**Comment by segiddins** [comment]
Ah. I'm betting this is already fixed on master, but for the sake of being sure, what's your Podfile?

**Comment by jcampbell05** [comment]
Here you go https://gist.github.com/fe1632accc461fa32410

**Comment by segiddins** [comment]
I'm not surprised that's not working. The issue will be the implicit target inheritance, which my open podfile DSL refactor pull request should address.

**Comment by segiddins** [comment]
This should be fixed in the 1.0 betas.
