### ISSUE TITLE
Install error using pre-release pod

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#4690]
I've got this:

> [!] Due to the previous naïve CocoaPods resolver, you were using a pre-release version of `MagicalRecord`, without explicitly asking for a pre-release version, which now leads to a conflict. Please decide to either use that pre-release version by adding the version requirement to your Podfile (e.g. `pod 'MagicalRecord', '= 3.0.0.dev.1451136769'`) or revert to a stable version by running `pod update MagicalRecord`.

which is a bummer because I use my own branch and fork.

```ruby
pod 'MagicalRecord', :git => 'https://github.com/pronebird/MagicalRecord.git', :branch => 'merged-patches'
```

**Comment by segiddins** [comment]
Can you just try running `pod update MagicalRecord`? If that doesn't work, we'd need to see your `Podfile.lock` to be able to investigate. Thanks!

**Comment by pronebird** [comment]
@segiddins thanks! Yes that was it! It's still confusing that `:git` + `:branch` combo upsets CocoaPods.

**Comment by segiddins** [comment]
It should only be a one-time issue. If not, we'll need the lockfile to be able to see what else could be causing the problem.

**Comment by pronebird** [comment]
No you are right, one time issue. This wasn't an issue for a while until my last `pod install`. I assume some things changed on CocoaPods or MagicalRecord side.
