### ISSUE TITLE
Unable to satisfy the following requirements Afnetworking

### ISSUE THREAD

**Issue by JenyaKirmiza** [CocoaPods/CocoaPods#4691]
I'm new to ios especially to pods( im android developer). Now i want to build the project that already has inited profile for pods and getting pod error. I installed cocoapods and the run comman 'pod install' on terminal, here is what i got:

pod install
Updating local specs repositories
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `ARChromeActivity (= 1.0.0)` required by `Podfile.lock`
- `ARChromeActivity (= 1.0)` required by `JBWebViewController (1.0.7)`

Specs satisfying the `ARChromeActivity (= 1.0.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by JenyaKirmiza** [comment]
ok. now i fixed it. i've installed only AFNetworking and then the other pods, and it worked. But still for some reason on xcode i get 
ld: library not found for -lAFNetworking
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I see the AFNetwork folder in pods., it means it's there but why xcode doesn't see it?

**Comment by JenyaKirmiza** [comment]
ok. i fixed it. I've deleted all pods cleaned the project, reinstalled the pods and it worked

**Comment by duplicater** [comment]
using `pod update` not `pod install`
