### ISSUE TITLE
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+-+%2FUsers%2Fcosmin%2Fcheckouts%2FSpecs%2Fgoogle-toolbox-for-mac%2F2.0%2Fgoogle-toolbox-for-mac.podspec&type=Issues

### ISSUE THREAD

**Issue by ReshmiMajumder** [CocoaPods/CocoaPods#4693]
I am implementing https://github.com/RisingOak/otp-authenticator while following the steps as provided I got this error , please provide your suggestions on this.

**Comment by segiddins** [comment]
Could you please share the full error template?

**Comment by segiddins** [comment]
Closing due to lack of response.
