### ISSUE TITLE
Dependency private lib issue

### ISSUE THREAD

**Issue by Pluto-Y** [CocoaPods/CocoaPods#4695]
I have a private Podspec in my private Spec.
Just like this:
![image](https://cloud.githubusercontent.com/assets/10654142/12015738/d43ae500-ad7b-11e5-88e9-7241589e89a3.png)

Then in the other Podspec, I want to this podspec dependency this private Podspec.
```
  s.dependency       'CsBtUtil', '~> 1.0.0'
```
When i run the shell pod lib lint, the error will occur.
```
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `CsBtUtil (~> 1.0.0)` depended upon by `TestPrivatePodspec`) during validation.
```

What should I do?

**Comment by segiddins** [comment]
If it's private, you can lint it with the `--private` flag

**Comment by orta** [comment]
You probably have to include the sources you want to reference in [your lint command](https://guides.cocoapods.org/terminal/commands.html#pod_spec_lint)
