### ISSUE TITLE
Build a WatchOS target w/out podspec author explicitly declaring support

### ISSUE THREAD

**Issue by zachlucas** [CocoaPods/CocoaPods#4696]
I have a project with twenty or so pods, and I'd like to add a WatchOS 2 component. However, from what I've read, each podspec author has to explicitly declare watch support.  As I understand it, my options now are either fork each repo and add support or just not have a watchOS component.  Is there any way to get around this?

**Comment by segiddins** [comment]
I believe @orta made a plugin, but the officially supported thing to do is to get the upstream podspecs updated.

**Comment by zachlucas** [comment]
Cool!  I can't seem to find the plugin, is it public?

**Comment by zachlucas** [comment]
Ah, is this it?  https://github.com/orta/cocoapods-expert-difficulty

**Comment by segiddins** [comment]
@zachlucas yup, that's it!

**Comment by zachlucas** [comment]
@segiddins is there any to simply not build the main application's pods for the watchOS target?  Like using target isolation like so:

```target "Watch" do

end```

**Comment by segiddins** [comment]
Yup, just put your main app pods in their own target block as well.
