### ISSUE TITLE
Error on pod install 

### ISSUE THREAD

**Issue by tygermeow** [CocoaPods/CocoaPods#4698]
I'm not sure why this pod won't install correctly.  

```
matsu-macbook:currencyconverter matsuthornton$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing CurrencyRequest (0.1.0)

[!] Error installing CurrencyRequest
[!] /opt/local/bin/git clone https://github.com/samkaufman/CurrencyRequest.git /var/folders/h7/tbs8lkbj32j8713z4f1_dc1w0000gn/T/d20151228-65144-rh0ma8 --single-branch --depth 1 --branch 0.1.0

error: unknown option `single-branch'
usage: git clone [options] [--] <repo> [<dir>]

PODFILE:
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'CurrencyConverter' do

pod 'CurrencyRequest','~>0.1'

end

target 'CurrencyConverterTests' do

end
```

**Comment by segiddins** [comment]
What version of git do you have installed?

**Comment by tygermeow** [comment]
not sure how do I check that?

**Comment by orta** [comment]
Run `git --version` in your terminal. E.g.

```
~/d/m/a/CocoaPods-app (bundled_rake) ⏛  git --version
git version 2.5.4 (Apple Git-61)
```

**Comment by tygermeow** [comment]
1.7.3

**Comment by tygermeow** [comment]
Upgraded to 2.6.3 but it still gives error.  Unkown option single-branch.

I tried running the line 

/opt/local/bin/git clone https://github.com/samkaufman/CurrencyRequest.git /var/folders/h7/tbs8lkbj32j8713z4f1_dc1w0000gn/T/d20151228-67261-crytsv --single-branch --depth 1 --branch 0.1.0

without --single-branch and it worked but the pod still won't install.

**Comment by neonichu** [comment]
Can you double-check that `/opt/local/bin/git` is really the `git` you upgraded and not another one installed somewhere else? The `—single-branch` option was added in 1.7.10 (see https://lkml.org/lkml/2012/3/28/418)

**Comment by tygermeow** [comment]
Ah you are right, I downloaded the mac install package and ran it but when I run git --version it still says 1.7.3.  How do I update the git in the correct location?

**Comment by tygermeow** [comment]
Ok, I added:
export PATH=/usr/local/bin:$PATH
to my ~/.bashrc file 

then I had to run 
source ~/.bashrc from the directory I wanted to install pods into and now it works.

Thank you for the help!!

**Comment by neonichu** [comment]
Great that it works now.
