### ISSUE TITLE
Confusion documentation for :configurations and :configuration options

### ISSUE THREAD

**Issue by thisisjeffwong** [CocoaPods/CocoaPods#4700]
The docs for the Podfile :configurations option are pretty confusing.

"For debug purposes or for other reasons, they can be enabled only on a given list of build configuration names"
```
pod 'PonyDebugger', :configurations => ['Release', 'App Store']
```

That sounds like a whitelist. But then

"Alternatively you can white-list only a single build configuration."

```
pod 'PonyDebugger', :configuration => ['Release']
```

Which is the actual white list parameter?

The examples don't make practical sense either. Why would you want the debugger pod in release and app store mode and not debug? This sounds like a list of configurations not to use.

It would probably be better to name the filter something more explicit because
* :configuration vs :configurations are very easy to mix up they look very similar. If the config list is wrong, it doesn't obviously look wrong.
* the meanings are also fairly arbitrary. why would :configurations be a filter list? Seems like it would be less confusing as :include-in-configurations or :exclude-from-configurations. I'd have to look back at this doc to recall which is which.

**Comment by segiddins** [comment]
It's all inclusion. A PR to CocoaPods/Core improving the docs would be ace!

**Comment by thisisjeffwong** [comment]
If they're both the same, should the option names be different? the single
:configuration seems superfluous.

**Comment by thisisjeffwong** [comment]
I also couldn't find which repo to pull to make this change.

To change this document:

https://guides.cocoapods.org/syntax/podfile.html#pod

the closest thing that looks like that is

https://github.com/CocoaPods/guides.cocoapods.org/blob/master/source/using/the-podfile.html.md

**Comment by orta** [comment]
It's in CocoaPods/Core - here's a [direct link](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/podfile/dsl.rb#L94) ( we keep the comments with the source so they don't get out of sync! )

**Comment by orta** [comment]
Fixed by https://github.com/CocoaPods/Core/issues/318
