### ISSUE TITLE
FOR THE LOVE OF GOD PLEASE MAKE IT SO THAT PODS DONT UPDATE IF SAME VERSION

### ISSUE THREAD

**Issue by fresh83** [CocoaPods/CocoaPods#4704]
We screwed up , we edited alot of the files in our pods and now were stuck in a horrible hell of cuting and pasting all bc cocoa pods likes to update ALLLL our files everytime we want to add a pod even if were already on AFNetworking 2.0 and the so called "udpate" is to AFNetworking 2.0 ....WHY THE HECK DO YOU HAVE TO UPDATE ALL MY PAST PODS AND WHY CANT I JUST ADD IN A SINGLE NEW POD WITHOUT SCREWING WITH OLD ONES!!!! ITS COSTED ME SOOO MUCH TIME AND ENERGY....defeats the whole purpose of this standard.

**Comment by orta** [comment]
Hi @fresh83 - you really shouldn't be directly editing your pods, we make them locked by default for a reason. You're obviously fighting against the system. If you want to have Pods that are considered editable then you should use `:path` Pods, or [development pods](https://www.cocoanetics.com/2014/07/development-pods/).
