### ISSUE TITLE
Updating podfile cause error after i update the cocoapods version

### ISSUE THREAD

**Issue by luziqin** [CocoaPods/CocoaPods#4705]
update the cocoapods to version 1.0.0 beta1 and i try to update the exsiting podfile cause the error :

'Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `Niunai_Example`.. Updating CocoaPods might fix the issue.'

=======podfile===========

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Niunai_Example', :exclusive => true do
  pod "Niunai", :path => "../"
  
  pod 'Typhoon', '~> 3.4.2'
  pod 'AFNetworking', '~> 2.6.0'
  pod 'YapDatabase', '~> 2.7.1'
  pod 'ReactiveCocoa','~>2.5'
  pod 'Mantle', '~> 2.0.5'
  pod 'LCNavigationController', '~>1.0.2'
  pod 'YYKit', '~> 0.9.6'
  pod 'LKDBHelper', '~> 2.1.7'
  pod 'JHChainableAnimations', '~> 1.3.0'
  
  pod 'AlipaySDK-2.0', '~> 15.0.2'
  pod 'KKWeChatSDK', '~> 1.6.2'

end

target 'Niunai_Tests', :exclusive => true do
  pod "Niunai", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  
end

=========podfile.lock============

PODS:
  - AFNetworking (2.6.3):
    - AFNetworking/NSURLConnection (= 2.6.3)
    - AFNetworking/NSURLSession (= 2.6.3)
    - AFNetworking/Reachability (= 2.6.3)
    - AFNetworking/Security (= 2.6.3)
    - AFNetworking/Serialization (= 2.6.3)
    - AFNetworking/UIKit (= 2.6.3)
  - AFNetworking/NSURLConnection (2.6.3):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/NSURLSession (2.6.3):
    - AFNetworking/Reachability
    - AFNetworking/Security
    - AFNetworking/Serialization
  - AFNetworking/Reachability (2.6.3)
  - AFNetworking/Security (2.6.3)
  - AFNetworking/Serialization (2.6.3)
  - AFNetworking/UIKit (2.6.3):
    - AFNetworking/NSURLConnection
    - AFNetworking/NSURLSession
  - AlipaySDK-2.0 (15.0.2):
    - AlipaySDK-2.0/Core (= 15.0.2)
  - AlipaySDK-2.0/Core (15.0.2)
  - CocoaLumberjack (2.2.0):
    - CocoaLumberjack/Default (= 2.2.0)
    - CocoaLumberjack/Extensions (= 2.2.0)
  - CocoaLumberjack/Core (2.2.0)
  - CocoaLumberjack/Default (2.2.0):
    - CocoaLumberjack/Core
  - CocoaLumberjack/Extensions (2.2.0):
    - CocoaLumberjack/Default
  - FBSnapshotTestCase (2.0.7):
    - FBSnapshotTestCase/SwiftSupport (= 2.0.7)
  - FBSnapshotTestCase/Core (2.0.7)
  - FBSnapshotTestCase/SwiftSupport (2.0.7):
    - FBSnapshotTestCase/Core
  - FMDB (2.5):
    - FMDB/standard (= 2.5)
  - FMDB/common (2.5)
  - FMDB/standard (2.5):
    - FMDB/common
  - JHChainableAnimations (1.3.0)
  - Kiwi (2.4.0)
  - KKWeChatSDK (1.6.2)
  - LCNavigationController (1.0.2)
  - LKDBHelper (2.1.7):
    - FMDB
  - Mantle (2.0.6):
    - Mantle/extobjc (= 2.0.6)
  - Mantle/extobjc (2.0.6)
  - Niunai (0.1.0):
    - AFNetworking (~> 2.6.0)
    - JHChainableAnimations (~> 1.3.0)
    - LCNavigationController (~> 1.0.2)
    - LKDBHelper (~> 2.1.7)
    - Mantle (~> 2.0.5)
    - ReactiveCocoa (~> 2.5)
    - Typhoon (~> 3.4.2)
    - YapDatabase (~> 2.7.1)
    - YYKit (~> 0.9.6)
  - ReactiveCocoa (2.5):
    - ReactiveCocoa/UI (= 2.5)
  - ReactiveCocoa/Core (2.5):
    - ReactiveCocoa/no-arc
  - ReactiveCocoa/no-arc (2.5)
  - ReactiveCocoa/UI (2.5):
    - ReactiveCocoa/Core
  - Typhoon (3.4.4):
    - Typhoon/no-arc (= 3.4.4)
  - Typhoon/no-arc (3.4.4)
  - YapDatabase (2.7.7):
    - YapDatabase/standard (= 2.7.7)
  - YapDatabase/standard (2.7.7):
    - CocoaLumberjack (~> 2)
  - YYKit (0.9.8):
    - YYKit/no-arc (= 0.9.8)
  - YYKit/no-arc (0.9.8)

DEPENDENCIES:
  - AFNetworking (~> 2.6.0)
  - AlipaySDK-2.0 (~> 15.0.2)
  - FBSnapshotTestCase
  - JHChainableAnimations (~> 1.3.0)
  - Kiwi
  - KKWeChatSDK (~> 1.6.2)
  - LCNavigationController (~> 1.0.2)
  - LKDBHelper (~> 2.1.7)
  - Mantle (~> 2.0.5)
  - Niunai (from `../`)
  - ReactiveCocoa (~> 2.5)
  - Typhoon (~> 3.4.2)
  - YapDatabase (~> 2.7.1)
  - YYKit (~> 0.9.6)

EXTERNAL SOURCES:
  Niunai:
    :path: ../

SPEC CHECKSUMS:
  AFNetworking: cb8d14a848e831097108418f5d49217339d4eb60
  AlipaySDK-2.0: 346e006fd2999d5ca5dd8869d03bc0a260fc48e0
  CocoaLumberjack: 17fe8581f84914d5d7e6360f7c70022b173c3ae0
  FBSnapshotTestCase: 7e85180d0d141a0cf472352edda7e80d7eaeb547
  FMDB: 96e8f1bcc1329e269330f99770ad4285d9003e52
  JHChainableAnimations: 22085fcb04ca87349e584573558e637f659fd769
  Kiwi: f49c9d54b28917df5928fe44968a39ed198cb8a8
  KKWeChatSDK: 40d2a12cf7d909d5c15fc1bc16524fcad35aea0f
  LCNavigationController: 61aca6b0f00a117c0509cc008753e293b0bb0bdf
  LKDBHelper: 9f2227e47b3c9b7f177ed2f6312367f937204c14
  Mantle: 299966b00759634931699f69cb6a30b9239b944d
  Niunai: 421d94a9c20df7e4ee4f5f447e1b3e6926cf0af2
  ReactiveCocoa: e2db045570aa97c695e7aa97c2bcab222ae51f4a
  Typhoon: e937c62b9048f73a93c1aa94f00627d97cecd588
  YapDatabase: a7a1ae3e0f89c319e3b22615c2351987fbbdbded
  YYKit: 1eadb09e245f0c0f6892599fe7871c67507c4ad5

COCOAPODS: 0.39.0

**Comment by segiddins** [comment]
Correct, the `exusive` option was removed in the 1.0 beta, as documented in the CHANGELOG.

**Comment by orta** [comment]
You can get some info here: https://github.com/CocoaPods/CocoaPods/issues/4706

**Comment by TigerWolf** [comment]
Please remove the `exclusive` option from the template: https://github.com/CocoaPods/pod-template.git

**Comment by purrrminator** [comment]
weird. The podfile was contradictorily generated by 1.0. (by using `pod lib create` routine)
