### ISSUE TITLE
Mini Updating to 1.0 migration guide

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#4706]
Hey anyone thinking of writing an issue about the 1.0 migration, we'll probably be posting a full blog post with the changes in the DSL, when that comes out I'll close this. Here's a good source of info from the guides that's [not deployed yet](https://github.com/CocoaPods/guides.cocoapods.org/blob/3a9b2b0c02ffa98db5b8d0c42fcc9d1b3da43c81/source/using/the-podfile.html.md)

So, we've changed a bunch of the API. The biggest change is that implicit targets don't exist anymore. This [means](https://github.com/CocoaPods/guides.cocoapods.org/pull/98) if you had a Podfile like:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

xcodeproj 'MyProject'

# these are implicit, cause there's no target wrapping them
pod 'ObjectiveSugar', '~> 0.5'
pod 'Artsy+UILabels', '~> 1.0'

target :test do
    pod 'OCMock', '~> 2.0.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts target.name
    end
end
```

it would now look like:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'MyApp' do
  xcodeproj 'MyProject'
  pod 'ObjectiveSugar', '~> 0.5'
  pod 'Artsy+UILabels', '~> 1.0'

  # App has it's own copy of ObjectiveSugar and Artsy+UILabels
  # Tests can access to GoogleAnalytics via the app
  # that hosts the test target, but also has its own pods

  target 'MyAppTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 2.0.1'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
```

Pods for testing targets now should always contain `inherit! :search_paths`. This means they don't get their own copies of the pods but can see they exist via the header files. You used to be able to pull this off with the `:exclusive` flag, but it declares exactly how it works.

**Comment by keith** [comment]
It doesn't look like the migration of:

```ruby
pod "Foo", :configurations => ["Beta"]
```

Is covered here, but it now throws an error on `pod install`. I'm happy to create an issue about it just wanted to make sure that wasn't expected. I didn't notice anything in the changelog or the diff that was obviously a change to this.

**Comment by orta** [comment]
I don't recall any discussion around changes to configurations for 1.0, they should work as expected, think an issue is a great call :+1:

**Comment by keith** [comment]
Awesome filed! https://github.com/CocoaPods/CocoaPods/issues/4707

**Comment by arsonik** [comment]
what about an app with multiple targets using the same pods ?
how should we write that ?
cause that doenst work:
```
target 'App1', 'App2' do
NOR
target ['App1', 'App2'] do
```

**Comment by orta** [comment]
This should do it

```
def shared_pods
   pod "Thing", "1.2.3"
  pod "Other", "1.33.2"
end

target "One" do
  shared_pods
end

target "Two" do
  shared_pods
end
```

@segiddins any thoughts on supporting array targets?

**Comment by arsonik** [comment]
Or i've just tried that:
Working:
```
abstract_target 'DummyTarget' do
    pod "..."
    target 'App1' do
    end
    target 'App2' do
    end
end
```  
Thank you

**Comment by orta** [comment]
Ah yeah, good use of `abstract_target`

**Comment by arsonik** [comment]
yep, just weird to type empty target block

**Comment by segiddins** [comment]
You don't need a block if it's going to be empty 😉

**Comment by orta** [comment]
Hey everyone, there's now a blog post with all this information and more: https://blog.cocoapods.org/CocoaPods-1.0
