### ISSUE TITLE
IOError - Unable to open stream when pod install is called in jenkins

### ISSUE THREAD

**Issue by vinay32724** [CocoaPods/CocoaPods#4708]
I m trying to do pod install using jenkins on my mac and build step during this step.I sense this is a permission issue.I have been struggling hard to solve this.Could u pls help me out

Started by user anonymous
[EnvInject] - Loading node environment variables.
Building in workspace /Users/vinayk/.jenkins/jobs/test1/workspace

Finished getting version 'C1732'.
[workspace] $ /bin/sh -xe /var/folders/hq/6s08c7pn0hn1_k3xhfxdbn_m0000gn/T/hudson8698595311721494508.sh
+ cd /Users/vinayk/Desktop/Milkywayautomationbuild
+ /usr/local/bin/pod install
[33mWARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:

export LANG=en_US.UTF-8
[0m
Updating local specs repositories

CocoaPods 1.0.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.6.3)
Using AXRatingView (1.0.3)
Using Apptimize (2.15.3)
Using Bolts (1.5.0)
Using Crashlytics (3.4.1)
Using FBSDKCoreKit (4.7.1)
Using FBSDKLoginKit (4.7.1)
Using FPPopover (1.4.1)
Using Fabric (1.6.1)
Using FontAwesome-iOS (0.0.4)
Using FontAwesomeTools (1.2)
Using HMSegmentedControl (1.5.2)
Using HexColors (2.2.1)
Using JTCalendar (2.1.4)
Using Localytics (3.6.0)
Using MBProgressHUD (0.9.2)
Using MGSwipeTableCell (1.5.3)
Using MSDynamicsDrawerViewController (1.5.1)
Using MagicalRecord (2.3.0)
Using Mantle (2.0.6)
Using MarqueeLabel (2.4.2)
Using Masonry (0.6.3)
Using NewRelicAgent (5.3.4)
Using SDWebImage (3.7.3)
Using SMCalloutView (2.1.2)
Using TSMessages (0.9.12)
Using UIDeviceAddition (1.0)
Using iCarousel (1.8.2)
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2bce9414a426b763657d0911c68034903878fb41
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
pod 'AFNetworking', '~> 2.5'
pod 'Mantle', '~> 2.0'
pod 'SMCalloutView', '~> 2.1'
pod 'MSDynamicsDrawerViewController', '~> 1.5'
pod 'FBSDKCoreKit', '~> 4.7.1'
pod 'FBSDKLoginKit', '~> 4.7.1'
pod 'MagicalRecord', '~> 2.2'
pod 'Masonry', '~> 0.6'
pod 'AXRatingView', '~> 1.0'
pod 'Apptimize', '~> 2.12'
pod 'HMSegmentedControl', '~> 1.5'
pod 'UIDeviceAddition', '~> 1.0'
pod 'Localytics', '~> 3.5'
pod 'MBProgressHUD', '~> 0.9'
pod 'TSMessages'
pod 'MGSwipeTableCell', '~> 1.4'
pod 'iCarousel', '~> 1.8'
pod 'JTCalendar', '~> 2.0'
pod 'FPPopover', '~> 1.4'
pod 'MarqueeLabel', '~> 2.3'
pod 'FontAwesome-iOS'
pod 'FontAwesomeTools'
pod 'SDWebImage', '~>3.7'
pod 'Fabric'
pod 'Crashlytics'
pod 'NewRelicAgent'
#pod 'PMCircularCollectionView', '~> 0.9'
```

### Error

```
IOError - Unable to open stream.
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:174:in `RubyHashPropertyListWrite'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:141:in `ruby_hash_write_xcode'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:48:in `write'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:18:in `write_plist'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:323:in `save'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:698:in `block in write_pod_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:690:in `write_pod_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:159:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:153:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Unable+to+open+stream.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by neonichu** [comment]
I agree that this is probably a permission issue. Since it happens while trying to write the Pods project, I would recommend checking the permissions on "Pods/Pods.xcodeproj" and the files inside.

**Comment by segiddins** [comment]
Closing due to lack of response.
