### ISSUE TITLE
Error installing cocoapods: activesupport requires Ruby version >= 2.2.2

### ISSUE THREAD

**Issue by SSteve** [CocoaPods/CocoaPods#4711]
I'm unable to install CocoaPods. I get the error "activesupport requires Ruby version >= 2.2.2". I'm running OS X 10.10.5.

```
$ which ruby
/Users/steve/.rvm/rubies/ruby-2.1.2/bin/ruby
$ ruby --version
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
```

**Comment by segiddins** [comment]
Looks like you'll need to install a 4.x version of active support?

**Comment by SSteve** [comment]
It seems more like a problem with rvm. After executing `rvm use system`, the installation worked even though the system Ruby is 2.0.0.

**Comment by strfn** [comment]
Facing the same problem when installing cocoa pods on Mac OSX 10.11.4

**Comment by Tulleb** [comment]
Same problem on Mac OSX 10.11.5.

**Comment by neonichu** [comment]
See CocoaPods/Xcodeproj#393

You can work around this by manually installing a compatible `activesupport` first:

```ruby
[sudo] gem install activesupport -v 4.2.6
```

**Comment by Tulleb** [comment]
I installed the Ruby 2.2 version instead...  
    rvm install 2.2
    rvm use 2.2

**Comment by yilufeng0** [comment]
You just need to update your ruby version, and use the version bigger than 2.2.2

 `rvm install 2.2.5`
`sudo gem install cocoapods`

for me this two works ! !

**Comment by Ajmalajji** [comment]
This worked for me 

> sudo gem install activesupport -v 4.2.6
> sudo gem install cocoapods

**Comment by kavinkily** [comment]
@Ajmalajji 
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods
 Also worked for me

**Comment by Jerry-Lau** [comment]
@neonichu thanks, this helped me!

**Comment by Cacchioni** [comment]
Hi everyone
i had same problem with OS X 10.11.5. I had update ruby to 2.3.1 but same error

I used:
 sudo gem install activesupport -v 4.2.6
sudo gem install cocoa pods

and it goes :)

**Comment by segiddins** [comment]
This has been addressed in the 1.1 beta as well

**Comment by akirna** [comment]
I also had to include (for OS X 10.11.5):
sudo gem install -n /usr/local/bin cocoapods﻿

...as mentioned by Srikanth Suryawanshi on the [Google Developer Cocoapods video](https://youtu.be/iEAjvNRdZa0)

**Comment by HarveyZhang360** [comment]
[sudo] gem install activesupport -v 4.2.6
[sudo] sudo gem install cocoapods

This works for me. Thanks.

**Comment by SAI1000** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoa pods

it works for me

**Comment by Ellz27** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods 


It works.Thank you for the help.

**Comment by cameron-badgley** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

This worked for me as well. I received one warning while installing activesupport, but it didn't prevent the gem from installing:
unable to convert "\x84" from ASCII-8BIT to UTF-8 for lib/active_support/values/unicode_tables.dat

**Comment by xyloweb** [comment]
I try
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

macbookpro-472d:~ jmm$ sudo gem install cocoapods
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/fuzzy_match

**Comment by xyloweb** [comment]
With
sudo gem install -n /usr/local/bin cocoapods
it's work great !

**Comment by yadhilho** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

this work!!! thankyou

**Comment by lemonkey** [comment]
Brittle.

**Comment by karunhappy** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

this worked for me!!! thank you

**Comment by jettandres** [comment]
@neonichu 's solution also worked for me. Thank you!

`[sudo] gem install activesupport -v 4.2.6`

**Comment by RobertSosa** [comment]
I tried using

sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

But I keep Getting

ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/fuzzy_match

**Comment by RobertSosa** [comment]
Figured Out My problem and Just in case Anybody had the same issue Try using 

sudo gem install -n /usr/local/bin cocoapods

Worked like a charm

**Comment by jemsnaban** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoa pods

that worked for me too

**Comment by abbutt** [comment]
/Library/Ruby/Site/2.0.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.0.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/pod:22:in `<main>'
what is the solution for this?
can anybody help? please

**Comment by 5uper0** [comment]
Right, guys. Had the same Error: requires Ruby version >= 2.2.2. I made:
gem install activesupport -v 4.2.6

And after that begins to install CocoaPods, but I had the same as last problem:

While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/fuzzy_match

**Comment by dmitriyborodko** [comment]
@5uper0 try:
sudo gem install activesupport -v 4.2.6

**Comment by MaeseppTarvo** [comment]
sudo gem install activesupport -v 4.2.6 worked.

**Comment by 5uper0** [comment]
@dmitriyborodko Thanks, but it didn't work for me
I made 
`sudo gem install -n /usr/local/bin cocoapods`
and installed 12 gems
When I try
`sudo gem install activesupport -v`
I'm getting this
`ERROR:  While executing gem ... (OptionParser::MissingArgument)`
`    missing argument: -v`

**Comment by 5uper0** [comment]
@dmitriyborodko, thanks! I made
`sudo gem install -n /usr/local/bin cocoapods`
and installed 12 gems, and then made
`sudo gem install activesupport -v 4.2.6`
with this message
`Successfully installed activesupport-4.2.6`
`Parsing documentation for activesupport-4.2.6`
`unable to convert "\x84" from ASCII-8BIT to UTF-8 for lib/active_support/values/unicode_tables.dat, skipping`
`1 gem installed`

**Comment by kameroli** [comment]
I was having the same problem but sudo gem install activesupport -v 4.2.6 and sudo gem install cocoapods  worked for me. 

Thank you all!

**Comment by misolubarda** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoa pods

worked!

**Comment by neelpatel05** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

worked

**Comment by carlos517** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

worked!! Thank you man

**Comment by ibenjanik** [comment]
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I got this ERROR.

**Comment by ibenjanik** [comment]
oh, it is working . Thanks.

**Comment by alirp88** [comment]
It still has the problem, if you want to fresh install cocoapods

**Comment by alirp88** [comment]
After I run "sudo gem install activesupport -v 4.2.6", cocoapods installed

**Comment by thufaili** [comment]
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

worked!! Thank you man

**Comment by orta** [comment]
I've mentioned this on the front page of http://cocoapods.org too

**Comment by ariessanchezsulit** [comment]
Both solution works for me (different machines)

- non rvm machine
sudo gem install activesupport -v 4.2.6
sudo gem install cocoapods

- with rvm machine
rvm install 2.2
rvm use 2.2
