### ISSUE TITLE
1.0.0b Causes FBSDKLoginKit to stop working

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#4723]
Two zip files of the same Podfile with Full project: http://cl.ly/1Q0S0h2T1Y40

0.39 compiles fine. 1.0.0 fails with this error:

![screen shot 2016-01-04 at 12 46 51](https://cloud.githubusercontent.com/assets/49038/12089875/3ec5391a-b2e1-11e5-8421-fc566a596839.png)

Podfile:

```ruby
platform :ios, '8.0'
use_frameworks!

target 'FBIssue' do
  pod 'FBSDKCoreKit', '4.9.0-beta2'
  pod 'FBSDKLoginKit', '4.9.0-beta2'
end
```

Podspec looks like this: https://github.com/CocoaPods/Specs/blob/master/Specs/FBSDKLoginKit/4.9.0-beta2/FBSDKLoginKit.podspec.json

**Comment by neonichu** [comment]
We already got this one in #4713

**Comment by orta** [comment]
Aww, and I put so much effort into the issue :crying_cat_face:

**Comment by neonichu** [comment]
Now you know how that feels ;)
