### ISSUE TITLE
project fails to link because Pods project only compiles active architecture

### ISSUE THREAD

**Issue by jpaas** [CocoaPods/CocoaPods#4725]
I started a brand new project and added a few cocoapods. And it was good. Then I added a couple more pods and I started getting linker errors because one of the pods had not been compiled in the required architecture.

The only way I was able to workaround was to edit the Pods project build settings so that all architectures are built even when building the Debug configuration. Ran a project clean, and voila, successful compilation.

I'm unsure whether there's something wrong with cocoapods itself, my Podfile, or the podspecs of one of the two pods that had the issue.

The problem began when I added the RealmSwift and RealmResultsController pods. RealmResultsController depends on RealmSwift and was unable to link some of symbols from it. 

My Podfile:

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
link_with 'newproj'

def core_pods
  pod 'Cartography', '0.6.0'
  pod 'Crashlytics'
  pod 'Fabric'
  pod 'DynamicColor', '2.3.0'
  pod 'LGSideMenuController', '1.0.10'
  pod 'RealmResultsController', '0.3.1'
  pod 'RealmSwift', '0.97.0'
  pod 'XCGLogger', '3.2'
end

target 'newproj' do
  core_pods
end
```

**Comment by neonichu** [comment]
Hm, the only issue I get when using the given Podfile with a new project is that the pinned version of RealmSwift apparently does not contain bitcode, so I had to disable that to successfully link. 

You can disable bitcode for the Pods project using a post-install hook like:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

If that's not your problem, please share an Xcode project as well, so that we can reproduce this.

**Comment by jpaas** [comment]
Here's a simple xcode project that demonstrates it https://github.com/jpaas/cocoapods_issue_4725
