### ISSUE TITLE
Add ability to install pod and write it to the podfile

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4726]
In NPM you can tell it to install a dependancy and write it to the list of dependancies for a project.

I could imagine this working well with `pod try` so once you like a pod you can say something like `pod add` or `pod install --add` and it would add it to the podfile complete with fuzzy version matching.

I am happy to implement with guidence.

**Comment by neonichu** [comment]
I think this would be :+1:, but the main issue right now is that we don't have any serialisation except YAML, which probably no one uses for their Podfiles. So first step would probably be to add a sensible serialisation to the Ruby DSL.

**Comment by segiddins** [comment]
This would make for a fine plugin imho -- have a look at how bundler implements `bundle inject`
