### ISSUE TITLE
Podfile.lock local path checksums changed after new years

### ISSUE THREAD

**Issue by justinseanmartin** [CocoaPods/CocoaPods#4730]
It appears that at the turn of the new year, the checksums for local path pods started to compute to different values. I can confirm that changing the date from 12/31/15 to 1/4/2015 and then re-running pod install will change the contents of the Podfile.lock.

**Comment by segiddins** [comment]
Can you share the contents of the podspecs for those development pods?

**Comment by justinseanmartin** [comment]
I'll email them to you.

**Comment by segiddins** [comment]
@justinseanmartin they're changing because the podspec is changing -- you have `Date.today.year` in them.

**Comment by justinseanmartin** [comment]
Sorry for the slow response. I was surprised that the checksum was on the result of evaluating the Podfile itself and not just the raw text. Is there a reason for that? I know that it could evaluate differently based on environment and other factors, but I didn't think that would be considered as change to the file's checksum.

**Comment by segiddins** [comment]
Because it checksums the JSON version of the podspec.
