### ISSUE TITLE
post_install issue on 1.0.1 beta, regression from 0.39

### ISSUE THREAD

**Issue by alistra** [CocoaPods/CocoaPods#4731]
🌈

When I updated to beta cocoapods some custom part of my `post_install` hooks stopped working.

When I open the original project using `Xcodeproj` gem in the post hooks and change something in it and save it, it doesn't appear to have saved the changes.

Possibly some logic to save the user project was moved after the `post_install` hook.

This is a reduced Podfile with the example problem. Here I try to add files to a target "Tests" in the `post_install` hook, but it appears that it starts working during the 2nd `pod update` or `pod install`. It doesn't work during the first time.
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

def common_pods
  pod 'ios-sdk', :path => '../modules/ios-sdk'
  […] # bunch of development pods
end

target 'SWA' do
  common_pods
end

target 'Tests' do
  common_pods
  pod 'FBSnapshotTestCase/Core'
  [...] 
end

def add_files_for_unit_tests(code_directory, code_directory_glob, project, target, group)
  puts "Adding test code from #{code_directory} directory"
  Dir.glob(code_directory_glob) do |f|

    if project.reference_for_path(f)
      next
    end

    if f.include? '.m'
      file_handle = group.new_file("#{f}")
      puts 'Adding %s to %s Source Build Phases' % [file_handle, target.name]
      target.source_build_phase.add_file_reference(file_handle, avoid_duplicates = true)
    elsif f.include? '.h'
      file_handle = group.new_file("#{f}")
      puts 'Adding %s to project' % [file_handle]
      target.headers_build_phase.add_file_reference(file_handle, avoid_duplicates = true)
    end
  end if File.directory?(code_directory)
end

def get_target_by_name(project, name)
  project.targets.select { |target| target.name == name }[0]
end

def get_group_by_name(project, name)
  project.main_group.children.select {|group| group.path == name}[0]
end

post_install do |installer_representation|

  project = Xcodeproj::Project.open('SWA.xcodeproj')
  test_target = get_target_by_name(project, 'Tests')

  code_directory = Dir.pwd + '/../modules/'
  code_directory_glob = code_directory + '**/*Tests.{h,m}'

  add_files_for_unit_tests(code_directory, code_directory_glob, project, test_target, get_group_by_name(project, 'Tests'))

  project.save
end
```
I realize this may not be a canonical way of using the `post_install` hooks, i.e. modifying the original project, not the `Pods` project. If this is not a good way of doing this, I'm open to change my ways and try some other way of doing this.

The problem is that I need to add files dynamically to the original project, because I have over 200 Apps sharing this one Podfile and I want to dynamically add files depending on the App.

**Comment by segiddins** [comment]
Try grabbing the user target / user project off of the aggregate targets from the installer in the hook instead of re-opening the project.

**Comment by alistra** [comment]
@segiddins  So `installer.aggregate_targets` and then where should I search for the project reference?

I was going through this http://www.rubydoc.info/gems/cocoapods/Pod/AggregateTarget#user_targets-instance_method and all I see are project paths, can't see the reference.

**Comment by segiddins** [comment]
@alistra those Are the docs for 0.39, not 1.0.0.beta.1. Check out the user_project and user_target methods on aggregate target.

**Comment by alistra** [comment]
@segiddins Don't know if you care, but your suggestion worked, thanks. I was able to test it now with 1.0.0.beta.7 fixes.

**Comment by segiddins** [comment]
Awesome!
