### ISSUE TITLE
Add support for sparse checkout.

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4732]
One idea may be to start using the sparse checkout system from git for faster install times.

Say I have a pod called  "Hat" in a repo full of 10,000 pods. If I specified my pod right now, cocoapods has to clone the entire repo with the 10,000 of pods, then find my pod and then clone the source for my pod.

With sparse checkout, if a pod repository conforms to the cocoapods structure then we could optimize this (http://stackoverflow.com/questions/600079/is-there-any-way-to-clone-a-git-repositorys-sub-directory-only/13738951#13738951). 

We can use a sparse checkout to clone the sub-directory for that pod i.e "pods/Hat" meaning it only needs to pull down the specification from my repo for that pod.

I would like to spike something, which part of cocoapods would handle this ?

**Comment by segiddins** [comment]
Have you profiled what the time difference is?

**Comment by neonichu** [comment]
I don't see how this could work without calculating the dependency graph remotely, without that we don't know which Pods from that spec repo we would need and fetching each specification separately would likely be even slower than keeping a local copy in sync as we do right now.

**Comment by jcampbell05** [comment]
That's true, I was thinking if the downloader supports zips. Could we build something similar to RubyGems with the CocoaPods website ?  The .gem files that are downloaded from that site are essentially .zips containing the code and the dependancies (The dependancies are generated when you build one of these .gem files).

I've uploaded one as an example.
[xcake-0.4.7.zip](https://github.com/CocoaPods/CocoaPods/files/78594/xcake-0.4.7.zip)

**Comment by segiddins** [comment]
That would require CocoaPods to pay for storing the source of _every singe pod_, which simply is not feasible for us.

**Comment by orta** [comment]
> Could we build something similar to RubyGems with the CocoaPods website

No, I don't think this is reasonable given them amount of work / hosting fees this would cost us

**Comment by jcampbell05** [comment]
Could

**Comment by jcampbell05** [comment]
Cool. Thought we could host the files on git but don't worry :)
