### ISSUE TITLE
CocoaPods 1.0.0.beta2 headers not found

### ISSUE THREAD

**Issue by keith** [CocoaPods/CocoaPods#4733]
Using CP 1.0.0.beta2 including the `FBSDKLoginKit` now produce build errors on internal import lines such as this one:

```
#import <FBSDKCoreKit/FBSDKMacros.h>
```

Using this Podfile:

```ruby
use_frameworks!

target 'Example' do
  pod 'FBSDKLoginKit'
end
```

Here's the example project I used to reproduce this error: [Example.zip](https://github.com/CocoaPods/CocoaPods/files/79199/Example.zip)

Here's my `pod env` just in case:

```

### Stack

'''
   CocoaPods : 1.0.0.beta.2
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.7.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 738b4d849c86305d4f4c427c40ee7e88f084e078
'''

### Installation Source

'''
Executable Path: /Users/ksmiley/.gem/bin/pod
'''

### Plugins

'''
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.2
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.2
'''

### Podfile

'''ruby
use_frameworks!

target 'Example' do
  pod 'FBSDKLoginKit'
end
'''
```

:rainbow:

**Comment by keith** [comment]
Note that this was also an issue in beta 1

**Comment by segiddins** [comment]
This is an issue with Facebook's podspec, there's a existing closed issue detailing it.

**Comment by keith** [comment]
Ah there are already 2! Sorry about that! closing

**Comment by allaire** [comment]
I'm having the same issue. @segiddins links to existing closed issue? Can't find it.

Thanks!

**Comment by orta** [comment]
I was looking at this with FB, for now, a fix is:

```
target 'FBIssue' do
  pod 'FBSDKLoginKit', :git => "https://github.com/chrisp-fb/facebook-ios-sdk"
  pod 'FBSDKCoreKit', :git =>"https://github.com/chrisp-fb/facebook-ios-sdk"
end
```

**Comment by allaire** [comment]
@orta great thanks for the unofficial fix. I suppose this issue has to be fixed on FB side? I might wait for their next Pod update :)

**Comment by jlubeck** [comment]
How is this fixed on the code side? I'm having the same issue with this library: https://github.com/CEWendel/SWTableViewCell and would be happy to create a pull request for them
