### ISSUE TITLE
Linking problems after adding watchos target

### ISSUE THREAD

**Issue by mikkokut** [CocoaPods/CocoaPods#4736]
Hi,
I am getting linking errors after I added WatchOS target and installed Parse via CocoaPods for it.

<pre>
ld: warning: ignoring file /Users/mikkokut/Library/Developer/Xcode/DerivedData/Testing-girgtanqxvykukblinlhlechyxbg/Build/Products/Debug-iphonesimulator/Bolts.framework/Bolts, file was built for i386 which is not the architecture being linked (x86_64): /Users/mikkokut/Library/Developer/Xcode/DerivedData/Testing-girgtanqxvykukblinlhlechyxbg/Build/Products/Debug-iphonesimulator/Bolts.framework/Bolts
ld: warning: ignoring file /Users/mikkokut/Library/Developer/Xcode/DerivedData/Testing-girgtanqxvykukblinlhlechyxbg/Build/Products/Debug-iphonesimulator/Parse.framework/Parse, file was built for i386 which is not the architecture being linked (x86_64): /Users/mikkokut/Library/Developer/Xcode/DerivedData/Testing-girgtanqxvykukblinlhlechyxbg/Build/Products/Debug-iphonesimulator/Parse.framework/Parse
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Parse", referenced from:
      type metadata accessor for __ObjC.Parse in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

My Podfile looks like this:
<pre>
use_frameworks!

target 'Testing' do
    platform :ios, '8.0'
	pod 'Parse'

end

target 'Watch Extension' do
    platform :watchos
    pod 'Parse'
    
end

target 'TestingTests' do

end

target 'TestingUITests' do

end
</pre>

I can reproduce the error also with new project also: [Testing.zip](https://github.com/CocoaPods/CocoaPods/files/79820/Testing.zip). I could reproduce this with Alamofire too, so this might not be related to the pod.

It builds correctly for iPhone 4s and iPhone 5 (simulators) but not for iPhone 5s-->. Weird thing is that in my original project, the result was opposite. 

<b>Details:</b>
- XCode version 7.2 (7C68)
- CocoaPods version 1.0.0.beta.2 (got the error with the earlier version too)

Is there any known issues about that?

<b>Update 1 </b>
I removed pods from extension target and ran <code>pod install</code>. Ran in iPhone 5s simulator (worked well). I added pods again to the extension and installed them again. Now it runs on iPhone 5s-> well but not in iPhone 4s and iPhone 5.

**Comment by neonichu** [comment]
Maybe some kind of DerivedData issue? I can build different targets of the given project just fine for both 32- and 64-bit. I tried both the "Testing" as well as the "Watch" target.

**Comment by mikkokut** [comment]
That was the problem. I cleaned DerivedData (Window -> Projects) for the project and it started working. One more trick learned. Thank you a lot @neonichu !

**Comment by smittysmee** [comment]
This Helpful.  Thank you.
