### ISSUE TITLE
`pod lib create` generates a Podfile non-compatible with cocoapods 1.0.0

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#4737]
$ pod lib create foo
    Cloning `https://github.com/CocoaPods/pod-template.git` into `foo`.
    [...]
    Running pod install on your new library.
    [!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `foo_Example`.. Updating CocoaPods might fix the issue.

**Comment by segiddins** [comment]
This belongs on https://github.com/CocoaPods/pod-template, but there's no way to have it spit out different Podfiles depending upon the CocoaPods version, so as long as 1.0 is in beta, I don't think we can really update it...

**Comment by Coeur** [comment]
In the end, I got a working example with this manual Podfile:

    use_frameworks!

    target 'MyPod_Example' do
      pod "MyPod", :path => "../"
    
      target 'MyPod_Tests' do
        inherit! :search_paths 
      end
    end

**Comment by Coeur** [comment]
You could have two branches on pod-template, and pull accordingly.

**Comment by segiddins** [comment]
Unfortunately, that's not how the `pod lib create` command works, and I don't think it's worth the engineering effort to do that when it will stop being necessary once 1.0 final is released.
