### ISSUE TITLE
"Re-creating CocoaPods due to major version update." each time you `pod update`

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#4738]
Each time you `pod update`, you get:

> Re-creating CocoaPods due to major version update.

Should only happen once.

**Comment by segiddins** [comment]
What's the output of `pod env` ?

**Comment by Coeur** [comment]
Ah, nevermind, I thought it was a one time procedure to re-create local specs repositories. I didn't know it was a project-specific re-creation.
