### ISSUE TITLE
'UIImageView+WebCache.h' file not found when CocoaPods updated

### ISSUE THREAD

**Issue by archerLj** [CocoaPods/CocoaPods#4744]
i didn't change anything before and after update CocoaPods. and everything is okay before CocoaPods 1.0.0.beta.2.  but when i updated my CocoaPods to 1.0.0.beta.2. it said "'UIImageView+WebCache.h' file not found"  and all the header files have the same issue.

i tried to install CocoaPods 0.39.0, but it didn't work, the issue still there. and i don't know is there some thing was changed in my project when i execute 'pod install' with 1.0.0.beta.2. (i didn't change anything in my project, i just updated CocoaPods to 1.0.0.beta.2)

**Comment by segiddins** [comment]
Can you share a project we can use to investigate the issue? Thanks!

**Comment by archerLj** [comment]
the issue was resolved
the reason is:
i have three targets in my project. and when CocoaPods updated, i need to add all the targets in Podfile (it's so weird, i didn't need to do that before)
anyway, thanks for your help

**Comment by segiddins** [comment]
Yeah, that's new as of 1.0. I'm glad you figured it out!
