### ISSUE TITLE
No such module in Development Pod

### ISSUE THREAD

**Issue by BalestraPatrick** [CocoaPods/CocoaPods#4745]
I'm trying to generate my own Podpsec for a project I'm about to release. My project has two dependencies and I declared one in this way in the .podspec file:

`s.dependency "RxSwift", '~> 2.0.0'`

Unfortunately the second dependency is unsupported at this moment because it is a fake framework and results in this error: 
![screen shot 2016-01-09 at 1 30 24 pm](https://cloud.githubusercontent.com/assets/3658887/12216046/2bf25460-b6d5-11e5-98ac-8f538d99ed10.png)

So what I do is that in my Pods project's Podfile I specify the `TwitterKit` pod to be installed and it looks like this.
![screen shot 2016-01-09 at 1 31 59 pm](https://cloud.githubusercontent.com/assets/3658887/12216054/64141932-b6d5-11e5-8e79-11977252bc09.png)

The problem is that my `TwitterKit-Rx.swift` file can't see the module `TwitterKit` installed in the Pods directory and fails to compile with the `No such module 'TwitterKit'` when I try to import it in my class.

Is there any way I can fix it?

Thanks a lot!

**Comment by segiddins** [comment]
Can you please share a project we can use to reproduce the issue? Thanks!

**Comment by BalestraPatrick** [comment]
Of course, the project is located here: https://github.com/BalestraPatrick/TwitterKit-Rx

Open the `TwitterKit-Rx.xcworkspace` which is in the Example directory to see the issue.
Thanks a lot :smile:

**Comment by neonichu** [comment]
You cannot work around the transitive dependency problem by simply removing the dependency, this will lead to it not being found, as you are experiencing. Each framework needs to link successfully on its own, linking the application target against a transitive dependency is not sufficient when using frameworks.

You can try using `-undefined dynamic_lookup` to ignore the linker error, see #2926 for some discussion on using such a workaround.

**Comment by BalestraPatrick** [comment]
@neonichu Can you please elaborate on using the `-undefined dynamic_lookup` workaround? 
`pod lib lint` fails even when using `--use-libraries`. I can't release my pod at the moment.

**Comment by dlo** [comment]
I'm having the same issue. Is this a CocoaPods bug? Not sure what the resolution is.
