### ISSUE TITLE
`install! :deduplicate_targets=>false` crashes

### ISSUE THREAD

**Issue by OneSadCookie** [CocoaPods/CocoaPods#4751]
with cocoapods 1.0.0.beta.2, using

```install! 'cocoapods',
    :deduplicate_targets => false```

crashes:

```
NoMethodError - undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/target/pod_target.rb:67:in `block in scoped'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/target/pod_target.rb:65:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/target/pod_target.rb:65:in `scoped'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:332:in `block (2 levels) in generate_pod_targets'
```

This is because analyzer.rb passes a `nil` cache to `scoped`, which unconditionally references it on line 67.

Fixing this is straightforward enough, but then causes a bunch more knock-on crashes to which the solutions are not so obvious.

**Comment by segiddins** [comment]
@mrackwitz would you like to look into fixing this?

**Comment by mrackwitz** [comment]
Yes, I'll have a look into that and other (de)duplication related things this week.
