### ISSUE TITLE
pod update local failed

### ISSUE THREAD

**Issue by franck4690** [CocoaPods/CocoaPods#4753]
I had merge the libraries with the command 
lipo -create /Users/linyunfeng/ASILib/release/libASINetworkLib.a  /Users/linyunfeng/ASILib/sim/libASINetworkLib.a /Users/linyunfeng/ASILib/debug/libASINetworkLib.a  -output /Users/linyunfeng/ASILib/libASINetworkLib.a
but it failed;
After then when I pod update my local git with the command "pod update",it makes the error with reason:
 JSON::ParserError - 757: unexpected token at 'lipo -create /Users/linyunfeng/ASILib/release/libASINetworkLib.a  /Users/linyunfeng/ASILib/sim/libASINetworkLib.a /Users/linyunfeng/ASILib/debug/libASINetworkLib.a  -output /Users/linyunfeng/ASILib/libASINetworkLib.a'
here is the pod file command
source 'http://git.xx.im/iOS/imyspecs.git'
pod 'MYPublic',:head

Wish for your help

**Comment by neonichu** [comment]
Where did you add the `lipo` command you are describing? I assume inside your podspec? If yes, please share that.

**Comment by franck4690** [comment]
I don't add the `lipo` command in my podspec. I just use the command to complie the `ASIHttpRequest` library in terminal tool.After that, there is the error,even pod update in an empty project.
Apologetic for my poor English, and thanks for your help.

**Comment by segiddins** [comment]
@franck4690 if you want us to look into this, you'll have to upload a project that reliably reproduces the issue, sorry.

**Comment by segiddins** [comment]
Closing due to lack of response.
