### ISSUE TITLE
Removing pod do not clean up Other linker flags

### ISSUE THREAD

**Issue by kafejo** [CocoaPods/CocoaPods#4756]
Removing pod preserves -framework <Podname> flag in target which leads to 

```
dyld: Library not loaded: @rpath/Podname.framework/Podname
  Referenced from: /var/mobile/Containers/Bundle/Application/FD1316B6-3A64-4F38-AA05-A4C163A8918C/xxx.app/xxx
  Reason: image not found
```

**Comment by neonichu** [comment]
This is not true for the general case. Could you please elaborate more on your specific issue? 

Another cause for this can be manually editing "Other Linker Flags" in the user target, which will copy flags from the generated XCConfig the first time it is done and CocoaPods will no longer be able to change that build setting.

**Comment by tolgaytoklar** [comment]
> This is not true for the general case. Could you please elaborate more on your specific issue?
> 
> Another cause for this can be manually editing "Other Linker Flags" in the user target, which will copy flags from the generated XCConfig the first time it is done, and CocoaPods will no longer be able to change that build setting.

@neonichu  Is there a way to "undo" this behavior? I manually edited "Other Linker Flags" for once now it doesn't update automatically. I removed the edit by pressing the delete button on the keyboard so the key return to the regular font from bold but it still doesn't update automatically when I run pod install.
