### ISSUE TITLE
Adding a Podspec for a Dynamic Framework

### ISSUE THREAD

**Issue by tirodkar** [CocoaPods/CocoaPods#4759]
Considering that CocoaPods has had support for dynamic frameworks for a while now, I’ve been trying to write a Podspec for a dynamic framework I’ve written. This dynamic framework is available at a certain location on the device. I want to link to this dynamic framework from my XCTest target. When I provide this framework as a vendored_framework, it gets copied into the XCTest generated bundle, and is treated as an embedded framework. I do not want that. I want the framework to be weakly linked. How can I achieve that using CocoaPods with a PodSpec. Please note that adding this as a static library is not an option for me. CocoaPods currently provides me two ways for adding a framework - 
1. Add it as a vendored_framework. This means that the framework will now always be embedded since “Embed Pods Framework“ is always called. I really do not want this.
2. Add it as a weak_framework. After experimenting a lot with this, I noticed that in this case, the framework was not downloaded at all. It required me to add a vendored_framework (again) which takes me back to 1.

Is there any way that I could add a dynamic framework to our project, but not have it embedded?

**Comment by segiddins** [comment]
Add the pod to the target you wish for it to be embedded in?

**Comment by tirodkar** [comment]
Sorry if the question wasn’t clear. I don’t want the framework to be embedded at all. I want targets to be able to reference the dynamic framework’s header files and weakly-link to it. Unfortunately, that does not seem to be possible with the two ways mentioned above.

**Comment by segiddins** [comment]
That's currently not possible, so this will have to be considered as a feature request.

**Comment by tirodkar** [comment]
Thanks for the info. I was thinking of maybe creating an option in the "PodSpec" that said "weak_vendored_framework" which would be similar to a vendored_framework, but would not be embedded by default and could be weakly linked with. Is there another alternate route you would suggest for this?

If it's fine from your side, I could file a feature request and submit a PR for it.

**Comment by segiddins** [comment]
I'm still not sold on the need for it, and adding podspec DSL attributes has a _very_ high barrier, since it factorially increases the amount of things we need to test and maintain perpetually.

**Comment by tirodkar** [comment]
Consider a framework embedded in an application. For testing the application you would require a separate test target. To test parts of the app that use the framework, the target would now need to reference the headers of the framework. 
So with the current CocoaPods flow, I would now add the same framework to my Test Target, which if it is a vendored_framework, would embed itself into my testing target as well, causing double inclusion when I run my tests because it is now embedded in both the test bundle and the app bundle. Thus, it is rather detrimental to have the framework embed itself every time here.

The need in this case is for the “Embed Pods Framework” script to not embed that framework in the test target. Please do tell me if there is a better way to solve this issue.

**Comment by segiddins** [comment]
The better way to solve that would be to change the way _dependencies_ work -- by adding in 'weak' dependencies. But again, not 100% the added benefit is worth the maintenance overhead.

**Comment by tirodkar** [comment]
Considering that dynamic frameworks are becoming quite ubiquitous, I’m sure many other projects will find this useful. Xcode provides us with a way to do this and I’m trying to migrate all my projects to CocoaPods. I would really appreciate it if there was a way to do what I’m trying to do in CocoaPods.

**Comment by khandpur** [comment]
Hi Samuel,

I've run into this issue with static libraries. We had to deal with a situation where the static library was being included in both the App and the Test. Because the test bundle was loaded dynamically by XCTest, it caused dyld to spew out duplicate symbols definition logs at runtime. We still haven't solved that problem. Realistically speaking, how much maintenance overhead would it be to introduce weak dependencies? From the perspective of testing an app, this would be a very useful feature to have.

**Comment by orta** [comment]
@khandpur this is because you're not meant to be including your application's libraries in your test bundles, only exposing their headers. The test bundle should only have the test pods. The new 1.0 syntax makes this [much more explicit](https://github.com/CocoaPods/CocoaPods/issues/4706).

**Comment by khandpur** [comment]
@orta Ah, very cool! that's exactly what I was looking for. Thanks!

But soon enough, we're going moving away from static libraries to embedded frameworks because it's easier to bundle up more shareable resources that way. We haven't finished the migration process yet but I imagine we will stumble upon this issue when we do.

**Comment by neonichu** [comment]
Doesn't `inherit! :search_paths` already achieve this? There shouldn't be a need to weak link the vendored framework to the test bundle.

**Comment by tirodkar** [comment]
@orta @neonichu, in my case, the dynamic framework has to be embedded in the application itself. 

I tested adding the dependency [to the application](https://github.com/CocoaPods/CocoaPods/issues/4706) with a dynamic framework and a simple test bundle. Unfortunately, `inherit! :search_paths` did not copy the required `FRAMEWORK SEARCH PATHS` that are needed for the test bundle to reference the framework’s headers. More importantly, after adding the required `FRAMEWORK SEARCH PATHS` manually to the test target, the test target was still unable to find the symbols from the framework headers.

The test target doesn't seem to be linking against the dynamic framework, which was the reason I initially mentioned that we should provide a way to allow explicit weak linking for dynamic frameworks.

**Comment by neonichu** [comment]
This makes sense, I misread your original post. I think it would make sense to offer an inheritance strategy that weak links inherited frameworks, as we already have a similar issue with application extensions.

**Comment by walter211** [comment]
@tirodkar i met this probleme too，conflict reference is pain, how you solve this now? I thought It would be helpfule for cocoapods to make a template for static library dev project structure.

**Comment by khandpur** [comment]
To work around this problem, we ended up writing a ruby script that modifies the app under test target. see the [EarlGrey project.](https://github.com/google/EarlGrey/blob/master/Scripts/configure_earlgrey_pods.rb)
