### ISSUE TITLE
Question about private pods

### ISSUE THREAD

**Issue by Pluto-Y** [CocoaPods/CocoaPods#4760]
I have a pirvate Sepc Repo named 'PrivateRepo'.
And there are two lib named 'A' and 'B'.
And the lib 'B' is denpendecy 'A' and other open souce lib like 'AFNetworking'.
Finally, I want to create an application use 'B' lib.

But when I run command `pod install` 

```
Unable to find a specification for `A(~> 1.0.1)` depended upon by `B`
```

And the A.podspec file use dependency like this:
```
...
  s.dependency              'A', '~>1.0.1'
  s.dependency              'AFNetworking', '~>2.6.0'
...
```

And the Application Podfile like this:
```
pod 'B', :path => '../B'
```

So what should i do?

**Comment by segiddins** [comment]
Put the source for your private specs repo and the master repo in your podfile

**Comment by Pluto-Y** [comment]
Like this?
Podfile:
```
source 'git@*****:**/PrivateRepo.git'
pod 'B', :path => '../B'
```

**Comment by Pluto-Y** [comment]
Okay, I know.
Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
source 'git@*****:**/PrivateRepo.git'
pod 'B', :path => '../B'
```

You save me.

**Comment by orta** [comment]
Yep :+1:
