### ISSUE TITLE
pod trunk push failing because String extension is not loaded

### ISSUE THREAD

**Issue by tannernelson** [CocoaPods/CocoaPods#4761]
`pod trunk push --verbose` is failing because of the follow error:
        
    /var/folders/29/qltf8j0x4rgd2kc_6zf9kp7c0000gn/T/CocoaPods/Lint/Pods/escaConfig/Pod/Classes/Beacon.swift:286:39: 
    error: value of type 'String' has no member 'data'
    peripheral.writeValue(password.data, forCharacteristic: characteristic, type: .WithResponse)

The project builds fine in Xcode, and I can see that the `NSDataExtensions.swift` file (which contains the `String` extension `var data`) is being compiled later.

Could this be an issue with the order in which they are compiled? In that case, how can I change this ordering?

**Comment by segiddins** [comment]
What's the full podspec for the pod you're trying to push? Does it declare all of its dependencies?

**Comment by tannernelson** [comment]
Here is the `Podspec`. Where can I insert that a dependency is `NSDataExtensions.swift`?

```ruby
#
# Be sure to run `pod lib lint escaConfig.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = "escaConfig"
  s.version          = "1.0.0"
  s.summary          = "Configure esca beacons."

  s.description      = "Allow your iOS application to connect to and configure esca beacons. Modify iBeacon, Eddystone, TxPower, Advertising Interval, and more."

  s.homepage         = "https://github.com/BlueBiteLLC/escaconfig-ios"
  # s.screenshots     = "www.example.com/screenshots_1", "www.example.com/screenshots_2"
  s.license          = 'MIT'
  s.author           = { "Tanner Nelson" => "tanner@bluebite.com" }
  s.source           = { :git => "https://github.com/BlueBiteLLC/escaconfig-ios.git", :tag => s.version.to_s }
  s.social_media_url = 'https://twitter.com/bluebite'

  s.platform     = :ios, '8.0'
  s.requires_arc = true

  s.source_files = 'Pod/Classes/**/*'
  s.resource_bundles = {
    'escaConfig' => ['Pod/Assets/*.png']
  }

  s.frameworks = 'CoreBluetooth'

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.dependency 'AFNetworking', '~> 2.3'
end
```

**Comment by neonichu** [comment]
The extension in your repo only defines `dataUsingEddystoneUrlEncoding` for `String` (see <https://github.com/BlueBiteLLC/escaconfig-ios/blob/master/Pod/Classes/NSDataExtensions.swift#L172>) as far as I can see. Just to make sure: `pod trunk push` will build the given remote source, not your local copy.

**Comment by tannernelson** [comment]
Double checking the remote showed I typed the git tag wrong.

It's working now. Thanks!
