### ISSUE TITLE
resource_bundle is broken in 1.0.0.beta.2

### ISSUE THREAD

**Issue by djbe** [CocoaPods/CocoaPods#4762]
Any pod in my Podfile that uses the resource_bundles property is broken: the copy bundle resources step for each corresponding bundle target contains no items. If I rollback to 0.39.0, everything works as it is supposed to.

Example pod with (now) broken resource_bundles step:
https://github.com/TimOliver/TOWebViewController/

Also happens in a private podspec with the following bundles:

	s.resource_bundles = {
		'Appwise-iOS' => ['Appwise-iOS/Resources/*.lproj']
	}

**Comment by efirestone** [comment]
Looks like this is related to my change in https://github.com/CocoaPods/CocoaPods/pull/4635

Looking into it now.

**Comment by djbe** [comment]
Beta 3 fixes this for me.

Thx @efirestone!

**Comment by danielgalasko** [comment]
Can anyone confirm if this is working in beta 6? One of my dependencies `pod NYTPhotoViewer` is now failing for the same error

    error: /Path/To/Build/Products/Debug-iphonesimulator/NYTPhotoViewer/NYTPhotoViewer.bundle: No such file or directory

**Comment by danielgalasko** [comment]
In fact I just checked with beta 3 now and its still broken
