### ISSUE TITLE
support for remote pod_target_xcconfig

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#4764]
This might be a weird suggestion but we have 100 libraries as pods that we want them to share the same xcconfig as in `pod_target_xcconfig`.

We can probably bake some code into the podspec itself to download/parse and use the xcconfig but it would be nice if CocoaPods can handle this internally.

Something like:

`s.pod_target_xcconfig = { :http => "path/to/xcconfig" }`

Where CocoaPods can cache the file they download upon installation of the pod and then parse it as a hash to use.

WDYT?

**Comment by segiddins** [comment]
Probably not going to happen, but you can put JSON.load(open(URL)) or similar in your ruby podspecs.

**Comment by dnkoutso** [comment]
Would this be invoked everytime you do `pod install` if not then that might be OK.

**Comment by segiddins** [comment]
Since JSON podspecs are stored everywhere, it'll only be downloaded when pushing or when the cache is parsing the podspec.

**Comment by dnkoutso** [comment]
Thanks I think that might work then.
