### ISSUE TITLE
how to use NSLocalizedStringFromTable in framework

### ISSUE THREAD

**Issue by skyhacker2** [CocoaPods/CocoaPods#4766]
I create a pod lib with custom `strings` file

```
s.resources = ["OTALib/UI/*.{lproj,storyboard,strings}"]
```

When I use `NSLocalizedStringFromTable` it cannot find the string.

I remove the line `uses_framework!` in Podfile then `NSLocalizedStringFromTable` work.

**Comment by neonichu** [comment]
You should be able to use `NSLocalizedStringFromTableInBundle` referencing the frameworks bundle as `NSLocalizedStringFromTable` only queries the main bundle, AFAIK.
