### ISSUE TITLE
pod trunk delete not work

### ISSUE THREAD

**Issue by Mqhong** [CocoaPods/CocoaPods#4768]
This command is in the official document, but it cannot be used locally.

**Comment by Mqhong** [comment]
$ pod trunk delete xxxxxxxx 1.0.6
WARNING: It is generally considered bad behavior to remove versions of a Pod that others are depending on!
Please consider using the `deprecate` command instead.
Are you sure you want to delete this Pod version?
> y

[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

**Comment by orta** [comment]
Yeah, there's an active PR on the issue, but there's only so much time in the day alas - https://github.com/CocoaPods/trunk.cocoapods.org/issues/162

**Comment by neonichu** [comment]
Allright, closing as a dupe.
