### ISSUE TITLE
Trying to use Cocoapods 1.0

### ISSUE THREAD

**Issue by kcorey** [CocoaPods/CocoaPods#4773]
Hi All,

I can't seem to get the 1.0 Podfile setup to work.

We compile all the Pods into a libPods-CLEngine.a.
We compile all the back end code and Pods-CLEngine.a into libCLEngine.a.
We compile The front ends into <WhiteLabelName>, and link with libCLEngine.a.

We had this working under the 0.3.x branches.

However, several of the constructs in the Podfile seem to have changed for 1.0.

Right now, I can't get anything linked into libPods-CLEngine.a, so of course the symbols from the Podfile are missing.

The new format is easy:

```ruby
platform :ios, "7.0"

#use_frameworks!

def sharedPodfiles
  pod 'PureLayout', "~> 3.0.1"
  pod 'BlocksKit', "~> 2.2.5"
  pod 'YLProgressBar', "~> 3.8.0"
  pod 'Toast', "~> 2.4"
  pod 'DateTools', "~> 1.7.0"
  pod 'WYPopoverController', "~> 0.3.7"
  pod 'DTCoreText', "~> 1.6.13"
  pod 'CSURITemplate', "~> 0.3"
  pod 'AFNetworking', "~> 1.1"
  pod 'AFOAuth2Client',git:"https://github.com/crowdlab-uk/AFOAuth2Client.git"
  pod 'MagicalRecord', "~> 2.3"
  pod 'TDSemiModal', "~> 1.0.0"
  pod 'OpenUDID', "~> 1.0.0"
  pod 'TPKeyboardAvoiding', "~> 1.2.4"
  pod 'APLKeyboardControls', "~> 0.1.2"
  pod 'AFAmazonS3Client',git:"https://github.com/crowdlab-uk/AFAmazonS3Client.git", branch:"1.x"
  pod 'ObjectiveSugar', "~> 1.1.0"
  pod 'MOAlertController', "~> 1.1.0"
end

target :CLEngine do
  xcodeproj 'CLEngine'

  sharedPodfiles
end

target :CrowdLab do
  xcodeproj 'CLEngine'

  target "CrowdLabTests" do
    inherit! :search_paths
    pod 'KIF','~> 3.0'
  end
end

#target :CLEngineTests, :exclusive => true do
target :CLEngineTests do
  inherit! :search_paths
  pod 'Kiwi', "> 2.3.0"
end

#target :CrowdLabTests, :exclusive => true do
target :WhiteLabelTests do
  inherit! :search_paths
  pod 'KIF','~> 3.0'
end
```

Can anyone tell me what else I need to do to get the pod files' contents archived into libPods-CLEngine.a?

Thanks,

-Ken

**Comment by orta** [comment]
I think you want to use the target hierarchy here:

```ruby 
target :CLEngine do
  xcodeproj 'CLEngine'

  sharedPodfiles

  target :CrowdLab do
    xcodeproj 'CLEngine'

    target "CrowdLabTests" do
      inherit! :search_paths
      pod 'KIF','~> 3.0'
    end
  end

  target :CLEngineTests do
    inherit! :search_paths
    pod 'Kiwi', "> 2.3.0"
  end

  target :WhiteLabelTests do
    inherit! :search_paths
    pod 'KIF','~> 3.0'
  end
end
```

So that those pods get passed along via the `search_paths`

**Comment by kcorey** [comment]
That's a big help, but now there's a new problem: it's asking for Pods-CrowdLab too.  There is no Pods-CrowdLab because the Pods code is statically linked to the library libCLEngine.a.

Is there a way to tell Cocoapods to /not/ create a Pods-CrowdLab in this setup?

**Comment by orta** [comment]
You use `abstract_target` I believe here

``` ruby
  abstract_target "CrowdLab" do
    xcodeproj 'CLEngine'

    target "CrowdLabTests" do
      inherit! :search_paths
      pod 'KIF','~> 3.0'
    end
  end

  target :CLEngineTests do
    inherit! :search_paths
    pod 'Kiwi', "> 2.3.0"
  end

  target :WhiteLabelTests do
    inherit! :search_paths
    pod 'KIF','~> 3.0'
  end
```

I have a PR on the guides with [the changes](https://github.com/CocoaPods/guides.cocoapods.org/pulls) - but as the majority of people are still using 1.0 syntax, I was waiting for the 1.0 official to migrate. Ideally we should be getting a blog post with the hows/whys before then

**Comment by kcorey** [comment]
Hey Orta,

Thanks for your help!

In the end, this is the Podfile that would allow me to build the app, test the app, for my main product.  I'll expand it from here to handle whitelabels.

For me this is now a solved problem.  Hope it helps someone.

-Ken

#Podfile

platform :ios, "7.0"

def sharedPodfiles
  pod 'PureLayout', "~> 3.0.1"
  pod 'BlocksKit', "~> 2.2.5"
  pod 'YLProgressBar', "~> 3.8.0"
  pod 'Toast', "~> 2.4"
  pod 'DateTools', "~> 1.7.0"
  pod 'WYPopoverController', "~> 0.3.7"
  pod 'DTCoreText', "~> 1.6.13"
  pod 'CSURITemplate', "~> 0.3"

  pod 'AFNetworking', "~> 2.5.4"
  pod 'AFOAuth2Manager', "~>2.2.0"
  pod 'AFAmazonS3Manager', "~>3.2.1"
  pod 'MagicalRecord', "~> 2.3"
  pod 'TDSemiModal', "~> 1.0.0"
  pod 'OpenUDID', "~> 1.0.0"
  pod 'TPKeyboardAvoiding', "~> 1.2.4"
  pod 'APLKeyboardControls', "~> 0.1.2"
  pod 'ObjectiveSugar', "~> 1.1.0"
  pod 'MOAlertController', "~> 1.1.0"
end

target :CLEngine do
  xcodeproj 'CLEngine'

  sharedPodfiles

  target :CrowdLab do
    xcodeproj 'CLEngine'

    target "CrowdLabTests" do
      inherit! :search_paths
      sharedPodfiles
      pod 'KIF','~> 3.0'
    end
  end

  target :CLEngineTests do
    inherit! :search_paths
      sharedPodfiles
    pod 'Kiwi', "> 2.3.0"
  end
end

**Comment by orta** [comment]
Thanks for coming back with your answer @kcorey
