### ISSUE TITLE
CocoaPod Error - Unable to find a specification for

### ISSUE THREAD

**Issue by raulsilvamx** [CocoaPods/CocoaPods#4774]
When execute pod update or pod install get the next error
[!] Unable to find a specification for... 

I checked CocoaPods Specs and has a Error (Failed to load latest commit information)

Could you fix this error please? 

All repositories are failed!

![captura de pantalla 2016-01-15 a las 12 46 22 p m](https://cloud.githubusercontent.com/assets/710990/12363980/2c8c8b6c-bb89-11e5-8fce-f636d194c81d.png)

**Comment by segiddins** [comment]
Can you please share the entire output of `pod install --verbose`? Thanks!

**Comment by raulsilvamx** [comment]
$ pod install --verbose
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.

CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.


Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target
  `Pods-MasterlockBLETests`: (``)

Finding Podfile changes
  - CocoaLumberjack
  - GoogleAnalytics-iOS-SDK
  - Masonry
  - OCHamcrest
  - OCMock
  - ReactiveCocoa
  - SSKeychain
  - TTTAttributedLabel
  - Typhoon

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `ReactiveCocoa (~> 2.4.0)`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by raulsilvamx** [comment]
pod 'ReactiveCocoa', '~> 2.4.0'
pod 'Typhoon', '~> 3.0.2'
pod 'Masonry', '~> 0.6.2'
pod 'SSKeychain', '~> 1.2.2'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'CocoaLumberjack', '2.0'
pod 'TTTAttributedLabel', '~> 1.13'

**Comment by raulsilvamx** [comment]
if i switch ReactiveCocoa or Typhoon return Typhoon like error.

**Comment by raulsilvamx** [comment]
$ pod --version
0.38.2

**Comment by raulsilvamx** [comment]
Please check this other image...

![captura de pantalla 2016-01-15 a las 1 31 57 p m](https://cloud.githubusercontent.com/assets/710990/12364954/f8a37742-bb8e-11e5-8334-740bd2dd6e2d.png)

**Comment by segiddins** [comment]
Yeah, the github web UI can't 'handle our scale', but that doesn't effect the actual git repo.

**Comment by orta** [comment]
See: https://github.com/CocoaPods/Specs/tree/master/Specs/ReactiveCocoa
<img width="230" alt="screen shot 2016-01-15 at 21 59 08" src="https://cloud.githubusercontent.com/assets/49038/12366460/3cea220e-bbd3-11e5-92e3-f4ea4d4056ab.png">

There is no version of ReactiveCocoa that fits your definition of `'~> 2.4.0'`  - if you change it to `'~> 2.4'` - it will be found! This video will explain [how it works](https://www.youtube.com/watch?v=x4ARXyovvPc)

**Comment by segiddins** [comment]
I can't reproduce this using CocoaPods 0.38.2. Can you try and boil this down to a Podfile that reproduces the issue in a clean project

**Comment by segiddins** [comment]
@orta thats not correct -- 2.4.x matches

**Comment by orta** [comment]
Ah, fair, deleting my post - not gonna leave bad info out there.

**Comment by raulsilvamx** [comment]
I installed cocoapods-1.0.0.beta.2 and has returned the same error... i send you a project new and the verbose log... 

[CocoaPodTest.zip](https://github.com/CocoaPods/CocoaPods/files/92619/CocoaPodTest.zip)

**Comment by segiddins** [comment]
That project installs fine for me. Can you `rm -rf ~/.cocoapods/repos/master` and try installing again?

**Comment by raulsilvamx** [comment]
Thank You! Now... It works!

![niw](https://cloud.githubusercontent.com/assets/710990/12367739/d919cc42-bba1-11e5-8411-5da929c00ec2.jpg)
