### ISSUE TITLE
Import vendor framework into swift code has errors

### ISSUE THREAD

**Issue by avnerbarr** [CocoaPods/CocoaPods#4776]
I think my issue is similar to https://github.com/CocoaPods/CocoaPods/issues/4448

Framework is "embedded" mixed swift/objc and compiled universally. The framework's header file is standard out-of-the-box header generated from a "Embedded framework" target in XCode;

```
MyFramework.h
FOUNDATION_EXPORT double MyFrameworkVersionNumber;

//! Project version string for MyFramework.
FOUNDATION_EXPORT const unsigned char MyFrameworkVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <MyFramework/PublicHeader.h>

#import <MyFramework/Header_one.h>
#import <MyFramework/Header_two.h>
...
```

Now I need to wrap my embedded framework (Mixed swift+obj-c) with a "vendor" podspec

Using pods:
If the host app tries to import the framework in a swift file it fails with an error 
"Include of non-modular header inside framework module 'MyFramework'" (In the framework's umbrella header with the <MyFramework/Header.h> syntax)

But from Objective-c code all works as expected.
(Manually embedding ,i.e. "Drag-and-drop" framework to host app, works as expected in both swift and obj-c files of host app.)

The pod spec is:
(omitting boiler)
```
Pod::Spec.new do |s|
  s.name         = "MyFramework"
  s.source       = { :http => "http://path/to/my/framework/zip/MyFramework.zip" }
  s.public_header_files = "MyFramework.framework/Headers/*.h"
  s.module_map = "MyFramework.framework/Modules/module.modulemap"
  s.preserve_paths = "MyFramework.framework/*"
  s.vendored_frameworks = "MyFramework.framework"
  s.requires_arc = true
end
```

In the corresponding pod file:

```
source '/path/to/my/private/spec/repo.git'
use_frameworks!
pod 'MyFramework'
```

**Comment by neonichu** [comment]
I'm assuming you are using CP 0.39 and Xcode 7.1 or later? Then this is most likely #4420.

**Comment by JessThrysoee** [comment]
I see this problem with 1.0.0.beta.2 and Xcode 7.2

The dynamic framework headers are copied and included as "-isystem Pods/Headers/Public/MyFramework" in HEADER_SEARCH_PATHS and at the same time "-framework MyFramework" is added to OTHER_LDFLAGS

[So, this seems to be a description of the problem](https://forums.developer.apple.com/thread/23554#81066). At least my build works if I in post_install clear the paths to framework headers from HEADER_SEARCH_PATHS.

**Comment by segiddins** [comment]
Can you try again with beta 5, please?

**Comment by JessThrysoee** [comment]
I still get "include of non-modular header inside framework module" with 1.0.0.beta.5

Below is the workaround I use at the moment:

```
def remove_from_header_search_paths(installer, target_name, pattern)
    installer.pods_project.targets.each do |target|
      if target.name == target_name
            target.build_configurations.each do |config|
                xcconfig_path = config.base_configuration_reference.real_path

                # read xcconfig file to build_settings dictionary
                build_settings = Hash[*File.read(xcconfig_path).lines.map{|x| x.split(/\s*=\s*/, 2)}.flatten]

                # remove paths matching <pattern> from HEADER_SEARCH_PATHS to prevent non-modular errors
                build_settings['HEADER_SEARCH_PATHS'] = build_settings['HEADER_SEARCH_PATHS'].split().reject {|x| x.match(/#{pattern}/)}.join(' ')

                # write build_settings dictionary to xcconfig file
                File.open(xcconfig_path, "w")  do |file|
                   build_settings.each do |key,value|
                     file.puts "#{key} = #{value}"
                   end
                end
            end
        end
    end
end

post_install do |installer|
   remove_from_header_search_paths installer, "Pods-MySwiftExample", "MyDynamicVendorFramework"
end
```

**Comment by neonichu** [comment]
I believe we have fixed this in the meantime.

**Comment by keduardo2117** [comment]
I added EstimoteSDK as a vendored framework, but I can't use it neither in the example project app or in the Development Pod files, I'mtrying to create a pod that connect to a web service, downloads beacon information and it uses the EstimoteSDK to monitor for those beacons, but I can't call the EstimoteSDK form anywhere

`Pod::Spec.new do |s|
  s.name             = 'BeaconManagerSDK'
  s.version          = '0.1.0'
  s.summary          = 'A short description of BeaconManagerSDK.'

  s.ios.deployment_target = '9.3'
  s.ios.vendored_frameworks = 'BeaconManagerSDK/EstimoteSDK/EstimoteSDK.framework'
  s.source_files = 'BeaconManagerSDK/Classes/**/*'
  s.public_header_files = 'BeaconManagerSDK/EstimoteSDK/EstimoteSDK.framework/Headers/*.h'
  s.frameworks = 'EstimoteSDK'
end
`

**Comment by igordeoliveirasa** [comment]
Is there any solution?
