### ISSUE TITLE
installing cocoapods 1.0 beta over 0.39.0

### ISSUE THREAD

**Issue by lizeray** [CocoaPods/CocoaPods#4777]
Hello,

I run the command 

sudo gem install cocoapods --pre

Successfully installed cocoapods-1.0.0.beta.2
Parsing documentation for cocoapods-1.0.0.beta.2
Done installing documentation for cocoapods after 2 seconds
1 gem installed

But when I run pod --version I get:
0.39.0

Then I run 
gem uninstall cocoa pods

Select gem to uninstall:
 1. cocoapods-0.39.0
 2. cocoapods-1.0.0.beta.2
 3. All versions
> 1
Successfully uninstalled cocoapods-0.39.0

But when I run again

pod --version

I get 

0.39.0

Any idea ? 

Thanks,

Stéphane

**Comment by segiddins** [comment]
`pod _1.0.0.beta.2_ --version`

**Comment by biolinh** [comment]
@segiddins : when I run as you said, it returns:
pod _1.0.0._ --version
0.39.0
