### ISSUE TITLE
When I run a pod install command error encountered

### ISSUE THREAD

**Issue by renyufei8023** [CocoaPods/CocoaPods#4778]
/Users/renyufei/Downloads/CocoaPods.app/Contents/Resources/bundle/bin/git clone https://github.com/AFNetworking/AFNetworking.git /var/folders/8b/skbhgyln78718lwjds4398k80000gn/T/d20160118-4500-17wrn7b --single-branch --depth 1 --branch 2.6.3 --recursive

Cloning into '/var/folders/8b/skbhgyln78718lwjds4398k80000gn/T/d20160118-4500-17wrn7b'...
fatal: unable to access 'https://github.com/AFNetworking/AFNetworking.git/': SSL: CA certificate set, but certificate verification is disabled

**Comment by neonichu** [comment]
This sounds like a git configuration issue — are you seeing the same error when running the `git clone` command on its own?

**Comment by krzd** [comment]
I am encountering a similar issue using CocoaPods 1.0.0.beta.2, no error occurs when running the command on its own.

```
[!] /Applications/Xcode.app/Contents/Developer/usr/bin/git clone https://chromium.googlesource.com/webm/libwebp /var/folders/gj/4xsxlf555n1dzvfgn2jfcxpr0000gn/T/d20160121-38362-6mixw6 --single-branch --depth 1 --branch v0.5.0

Cloning into '/var/folders/gj/4xsxlf555n1dzvfgn2jfcxpr0000gn/T/d20160121-38362-6mixw6'...
fatal: unable to access 'https://chromium.googlesource.com/webm/libwebp/': SSL: certificate verification failed (result: 5)
```

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by icecrystal23** [comment]
I am seeing this on the 1.0.0 release:

    $ pod lib create MyNewPod
    Cloning `https://github.com/CocoaPods/pod-template.git` into `MyNewPod `.
    [!] /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git clone https://github.com/CocoaPods/pod-template.git MyNewPod

    Cloning into 'MyNewPod'...
    fatal: unable to access 'https://github.com/CocoaPods/pod-template.git/': SSL: CA certificate set, but certificate verification is disabled

    $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git clone https://github.com/CocoaPods/pod-template.git MyNewPod
    Cloning into 'MyNewPod'...
    warning: templates not found /Users/orta/dev/mac/apps/CocoaPods-app/destroot/bundle/share/git-core/templates
    fatal: Unable to find remote helper for 'https'

This StackOverflow answer suggests changing `https` to `git` in the URL solves the issue (and it seems to): http://stackoverflow.com/a/12236255/3558220

    $ /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git clone git://github.com/CocoaPods/pod-template.git MyNewPod
    Cloning into 'MyNewPod'...
    warning: templates not found /Users/orta/dev/mac/apps/CocoaPods-app/destroot/bundle/share/git-core/templates
    remote: Counting objects: 1869, done.
    remote: Compressing objects: 100% (49/49), done.
    remote: Total 1869 (delta 17), reused 0 (delta 0), pack-reused 1819
    Receiving objects: 100% (1869/1869), 347.48 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (955/955), done.
    Checking connectivity... done.`

**Comment by orta** [comment]
This might be a bug with the CocoaPods mac app, could be worth raising that over there

**Comment by icecrystal23** [comment]
Filed: https://github.com/CocoaPods/CocoaPods-app/issues/355
