### ISSUE TITLE
Cocoapods 1.0.0 Preprocessor Macros Ignored

### ISSUE THREAD

**Issue by raulsilvamx** [CocoaPods/CocoaPods#4780]
Hello i installed Cocoapods 1.0.0 beta 2 and i think i found a error... when you use pod install or pod update the Pods.xcodeproj ignore Preprocessor Macros from main xcodeproj.

I've put them manual to each macro and worked!!

The next image is resulted of manual edition...

![captura de pantalla 2016-01-18 a las 12 20 14 p m](https://cloud.githubusercontent.com/assets/710990/12400530/ddd8464e-bddd-11e5-854a-e494fb2fdddb.png)

**Comment by segiddins** [comment]
It's intentional that's the pods project doesn't have the same defines as the users Xcodeproj.
