### ISSUE TITLE
CocoaPods fails to find properly tagged and available remote branch

### ISSUE THREAD

**Issue by srosmd** [CocoaPods/CocoaPods#4782]
Hey there!
I'm trying to release a private CocoaPod, but I keep running into the below error:

    [!] Error installing MyCocoaPod
     -> MyCocoaPod (0.3.0-RC1)
        - ERROR | [iOS] unknown: Encountered an unknown error ([!] /opt/homebrew-cask/Caskroom/cocoapods/0.37.0/CocoaPods.app/Contents/Resources/bundle/bin/git clone ssh://git@my.host.example.com/Path/To/My/MyCocoaPod.git /var/folders/42/1xp0pnv14_d1bd_h64hs11m000010g/T/d20160118-12293-ui5jqd --single-branch --depth 1 --branch 0.3.0-RC1

    Cloning into '/var/folders/42/1xp0pnv14_d1bd_h64hs11m000010g/T/d20160118-12293-ui5jqd'...
    warning: Could not find remote branch 0.3.0-RC1 to clone.
    fatal: Remote branch 0.3.0-RC1 not found in upstream origin
    fatal: The remote end hung up unexpectedly
    ) during validation.

    [!] The `MyCocoaPod.podspec` specification does not validate.

I know the branch is tagged (`v0.3.0-RC1`) and available on the remote as I'm able to pull it onto a different machine and see all of it. The accounts involved all have proper permissions to clone and push. I'm running into this issue using the following command:

`pod repo push MyPodSpecRepo MyCocoaPod.podspec --verbose`

and I'm a little confused what I could be doing wrong. I've released dozens of versions this way, so I'm unsure what changed or what I could be doing wrong. I tried updating to the latest beta, but that didn't fix the issue. I tried rolling back to 0.39.0, which didn't fix the issue. Any ideas?

**Comment by segiddins** [comment]
Is the `v` in the tag in the podspec?

**Comment by srosmd** [comment]
No. The version numbers are X.Y.Z and the tags are vX.Y.Z. Previously I never included the tag as the version in the podspec, but I can give this a shot and get back to you.

**Comment by srosmd** [comment]
I tried your suggestion and got the same results. Specifically what I did was update the tag in the podspec to `"v" + s.version.to_s` where it was just `s.version.to_s` before. I pushed the branch and tried `pod repo push MyCocoaPod.spec --verbose` and it looked for the v0.3.0-RC1 branch.

**Comment by srosmd** [comment]
I tracked down the issue to being a permissions issue on the branch object itself within the bare git repo I had on our server. This was unique to our group.

**Comment by haifengkao** [comment]
I got the same problem. Reason is incorrect git url in podspec
