### ISSUE TITLE
inherit! :search_paths creates invalid xcconfig

### ISSUE THREAD

**Issue by OneSadCookie** [CocoaPods/CocoaPods#4783]
With a Podfile like this:

    target "My App" do
        pod "A"
        target "Tests" do
            inherit! :search_paths
            pod "B"
        end
    end
    
    target "WatchExt" do
        pod "A"
    end

cocoapods-1.0.0.beta.2 creates an xcconfig for the Tests target like:

    FRAMEWORK_SEARCH_PATHS = $(inherited) $(PLATFORM_DIR)/Developer/Library/Frameworks "$PODS_FRAMEWORK_BUILD_PATH"
    ...
    PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-Tests $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-My App

Which is incorrect (it creates one framework search path pointing at a space-separated concatenation of paths, which is generally invalid but particularly bad when one of the paths has a space)

It should instead create:

    FRAMEWORK_SEARCH_PATHS = $(inherited) $(PLATFORM_DIR)/Developer/Library/Frameworks $PODS_FRAMEWORK_BUILD_PATH
    ...
    PODS_FRAMEWORK_BUILD_PATH = "$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-Tests" "$(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-My App"

(Note lack of quotes in FRAMEWORK_SEARCH_PATHS & addition of per-path quotes in PODS_FRAMEWORK_BUILD_PATH)

Unfortunately, I can't upload my actual Podfile 'cos it's full of proprietary stuff... hopefully I've regressed this correctly :(

**Comment by segiddins** [comment]
This looks about right! I think there's an xcconfig helper to deal with the quoting, if you want to have a stab at making a PR.

**Comment by OneSadCookie** [comment]
It's not quite straightforward.

The (major) problem lies in `Xcodeproj::Config::merge_attributes!` where it simply slaps together two strings with a space.  However, changing this to always quote the concatenated strings enforces quotes around the `"$PODS_FRAMEWORK_BUILD_PATH"`.

I'm unconvinced there's a one-size-fits-all solution here.

**Comment by segiddins** [comment]
No, I mean where we set the actual values for the build setting, we should quote it there.

**Comment by OneSadCookie** [comment]
By then the *intended* argument boundaries are well lost (eg. as soon as you call `Hash#merge!` with a string containing a space)

I think the `@attributes` ivar of `Xcodeproj::Config` which is currently a Hash from String to String needs to become a Hash from String to Array of String.  Then the argument boundaries can be preserved for long enough to merge things correctly.

**Comment by OneSadCookie** [comment]
Hmm, it might be OK to make it `Hash{String => String|Array{String}}`, it looks like mostly it's not externally manipulated.

**Comment by OneSadCookie** [comment]
Sorry, I finally realized what you meant <_<

Yes, that works fine and much more simply than what I was thinking.

**Comment by OneSadCookie** [comment]
Ugh, so the tests fail in that PR, for obvious reasons.  But I can't actually run `rake bootstrap` successfully so this is in the too-hard basket now :/  Maybe someone else can pick it up.
