### ISSUE TITLE
How can I make it add iOS frameworks to the project?

### ISSUE THREAD

**Issue by galkeidar** [CocoaPods/CocoaPods#4786]
I use Cocoapods to integrate my lib into other projects. For my lib to work, the hosting application must include other iOS frameworks, such as SystemConfiguration, CoreTelephony and an iOS library: libicucore.tbd.

My question is, can I add these dependencies to my podspec file so these framework and lib will be added automatically to the hosting application, once my lib is installed via Cocoapods?

I looked for hours and couldn't find the way to do so, or my trials failed.

ADDITIONS:

This is what I added to my podspec:

```s.frameworks = 'SystemConfiguration', 'CoreTelephony', 'Security'```
Tried this as well:

```s.vendored_frameworks = 'SystemConfiguration.framework', 'CoreTelephony.framework', 'Security.framework'```
I created a test project and added my lib to it using Cocoapods. Lib was added successfully, but the frameworks are not included in the project.

**Comment by segiddins** [comment]
`s.frameworks = 'SystemConfiguration', 'CoreTelephony', 'Security'` should be sufficient...

**Comment by galkeidar** [comment]
I know, but it doesn't work!
Please take a look at my podspec.
[Growmobile-iOS-SDK.podspec.txt](https://github.com/CocoaPods/CocoaPods/files/96280/Growmobile-iOS-SDK.podspec.txt)

**Comment by galkeidar** [comment]
Is this error i'm getting may be related?

```
### Command

```
/Users/galK/.rvm/gems/ruby-2.1.5/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.4.3
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/galK/.rvm/rubies/ruby-2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d0746f0f6e1685c004cd28df80e8ab1134ed68a3
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MyYTest' do
pod 'Growmobile-iOS-SDK'
end

target 'MyYTestTests' do

end

target 'MyYTestUITests' do

end
```

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007fdf19b1bd90>
/Users/galK/.rvm/gems/ruby-2.1.5@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/Users/galK/.rvm/gems/ruby-2.1.5@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Users/galK/.rvm/gems/ruby-2.1.5@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Users/galK/.rvm/gems/ruby-2.1.5@global/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/galK/.rvm/gems/ruby-2.1.5/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/galK/.rvm/gems/ruby-2.1.5@global/gems/cocoapods-1.0.0.beta.2/bin/pod:44:in `<top (required)>'
/Users/galK/.rvm/gems/ruby-2.1.5/bin/pod:23:in `load'
/Users/galK/.rvm/gems/ruby-2.1.5/bin/pod:23:in `<main>'
/Users/galK/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/galK/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
Just run `gem install cocoapods-stats --pre` to fix that error.

**Comment by galkeidar** [comment]
I did. I made sure the podspec in github is updated, I made sure the pod install did install the latest version and still, no frameworks or libs were added to my testapp.

**Comment by orta** [comment]
Can you please submit a project exhibiting the problem?

**Comment by galkeidar** [comment]
@orta What do you mean 'submit a project'?

**Comment by orta** [comment]
A zipped folder with an Xcode project showcasing the bug :+1:

**Comment by galkeidar** [comment]
[Archive.zip](https://github.com/CocoaPods/CocoaPods/files/204359/Archive.zip)

@orta There you go...

The attached project is the project I'm adding to lib to it. Is that what meant?

**Comment by mrackwitz** [comment]
The project you attached doesn't seem to reproduce the issue you describe with the latest version of CocoaPods.
