### ISSUE TITLE
Limit active support to < 5 (which is beta)

### ISSUE THREAD

**Issue by raubas** [CocoaPods/CocoaPods#4789]
Running `sudo gem install cocoapods` on OSX 10.11.2 returns:

ERROR:  Error installing cocoapods:
	activesupport requires Ruby version >= 2.2.2.

The problem is a new release of activesupport, propose this change in cocoapods.gemspec

`s.add_runtime_dependency 'activesupport', '>= 4.0.2'`

to

`s.add_runtime_dependency 'activesupport', '>= 4.0.2', '<5'`

Installing activesupport using `gem install activesupport` installs 4.2.5 which also solves the issue for you guys googling! 

:)

**Comment by segiddins** [comment]
But we support activesupport 5... This sounds like a rubygems issue more than anything to me. What version of RubyGems are you running?

**Comment by raubas** [comment]
True, had some issues installing but it worked after installing activesupport (4.2.5). Anyhow versions are below.!

$ ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]
$ gem -v
2.2.2

**Comment by segiddins** [comment]
I think rubygems 2.5 should be smarter about this.
