### ISSUE TITLE
RTF-Type License is not allowed

### ISSUE THREAD

**Issue by mRs-** [CocoaPods/CocoaPods#4791]
Cocoapods 1.0.0.beta.2 are only allowing .txt / .md / .markdown files and not rtf and it's breaking Things in my implementation.

Maybe this should not be so harsh in the restriction (https://github.com/CocoaPods/Core/commit/a5a790b4c706a1245eef34af0c16c70af3c08002)

**Comment by orta** [comment]
Any reason to use RTF? Licenses are supported to be "vanilla" text documents. I've never seen a license file that requires images/formatting.

**Comment by mRs-** [comment]
I have no intention to use RTF, but one of my dependencies (https://github.com/mpospese/MPFlipViewController) got one rtf file. And the dependency is dead. 

For a workaround I forked it and renamed the file from .rtf to .txt

**Comment by segiddins** [comment]
I think this is a 'wont support', sorry, as parsing RTF is way outside the purview of CocoaPods.

**Comment by mRs-** [comment]
I can completely understand this, is there an easy way to see how many pods are affected by this change?

**Comment by orta** [comment]
So far this is the first. We've been supporting this since [Sept 2014](https://github.com/CocoaPods/Core/releases/tag/0.34.1)

**Comment by mRs-** [comment]
Okay, I'm just using my workaround. Just wanted to mention this, because it could be a bigger thing.

**Comment by orta** [comment]
:+1: thanks!
