### ISSUE TITLE
DocuSignESign is listed multiple times

### ISSUE THREAD

**Issue by gsnavin** [CocoaPods/CocoaPods#4793]
Hi,
I pushed a cocoapod and on the cocoapod.org its showing up multiple times. Can you please look into it?
Pod Name: DocuSignESign
Naveen

**Comment by neonichu** [comment]
I'm not sure what you mean, there's just one result for that pod when I search for it. Can you be more specific and attach a screenshot?

**Comment by orta** [comment]
Probably a dupe of https://github.com/CocoaPods/cocoapods.org/issues/248

**Comment by gsnavin** [comment]
Hi orta
Yes it's the same issue that I have too. Do you have any update on this
issue from the past issues reported?

Naveen

**Comment by orta** [comment]
Nothing that is not in that issue, closing as this isn't a CocoaPods ( the gem ) issue and already has an issue.
