### ISSUE TITLE
TYPO https://guides.cocoapods.org/syntax/podfile.html#group_target_configuration

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/CocoaPods#4799]
Typo here
https://guides.cocoapods.org/syntax/podfile.html#group_target_configuration

Here it is
![screen shot 2016-01-21 at 2 10 31 pm](https://cloud.githubusercontent.com/assets/382183/12491377/bf1a1a30-c048-11e5-8435-27acb4a1f1b7.png)

Also that page does not say where to fork/PR or send errors. So I'm assuming this is where they go.

**Comment by segiddins** [comment]
A PR to the inline docs in CocoaPods/Core would be ace
