### ISSUE TITLE
"Updating CocoaPods might fix the issue" could be more helpful

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/CocoaPods#4800]
Debugging a Podfile is frustrating enough.

Would the advice

> Updating CocoaPods might fix the issue

please be updated to include a copy-pastable command that will do what it recommends, and provide a shimmer of hope of fixing the problem.

**Comment by segiddins** [comment]
Tbh I'd like to get rid of that sentence entirely.

**Comment by segiddins** [comment]
@orta thoughts on getting rid of that sentence now that we're hitting 1.0?

**Comment by orta** [comment]
At this point doesn't CP already know if it's at the latest build cause of the CocoaPods/Specs repo? Can we hide it if it's at the latest?

**Comment by segiddins** [comment]
not really, since that error comes from Core, and that knowledge is in the SourcesManager of CocoaPods/CocoaPods

**Comment by segiddins** [comment]
(But given we'll print the new version available message, I see no need to say to update in the Core DSL error as well)

**Comment by orta** [comment]
OK, then I think it's fine to remove that, yeah :+1:  message should show when CP is not latest already.
