### ISSUE TITLE
Multiple targets - some with static libs, others with frameworks

### ISSUE THREAD

**Issue by mjholgate** [CocoaPods/CocoaPods#4802]
I have a podfile that looks like this:

```
target 'TargetA' do
  pod "MyDependency", :path => "../"
end

target 'TargetB' do
  use_frameworks!
  pod "MyDependency", :path => "../"
end

target 'Tests' do
  use_frameworks!
  pod "MyDependency", :path => "../"
end
```

This all builds fine, but when running the TargetA, I get a runtime error trying to load one of the dependencies of MyDependency:

```
dyld: Library not loaded: @rpath/JVFloatLabeledTextField.framework/JVFloatLabeledTextField
  Referenced from: /var/mobile/Containers/Bundle/Application/....
```

Looking at the DerivedData folder, it looks like TargetA has been built with frameworks

Is this a valid thing to try and do, and is there any way of working around the problem?

Using CocoaPods 1.0 beta.

**Comment by segiddins** [comment]
Can you share a project that reproduces the issue?

@mrackwitz is this possibly an issue with deduplcation?

**Comment by mrackwitz** [comment]
@segiddins: This might be the case.
@mjholgate: Does your Pods project has a target `Pods-TargetA`, which has a static library target `MyDependency` as dependency?

**Comment by segiddins** [comment]
Closing due to lack of response.
