### ISSUE TITLE
Hint to use generated workspace shouldnot be shown when linting

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#4804]
Currently it shows up, because it is triggered from the installation for the sample project.

``` diff
  - Writing Manifest in `../../../../../private/var/folders/yp/qv8dfc357kb62nkb6dtsc4bw0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`

Integrating client project

+[!] Please close any current Xcode sessions and use `App.xcworkspace` for this project from now on.

Integrating target `Pods-App` (`../../../../../var/folders/yp/qv8dfc357kb62nkb6dtsc4bw0000gn/T/CocoaPods/Lint/App.xcodeproj` project)
  Adding Build Phase 'Embed Pods Frameworks' to project.
```

**Comment by orta** [comment]
This is only with `--verbose`?

**Comment by mrackwitz** [comment]
Yes, but running the linter without `--verbose` is useless, if it doesn't succeed.

**Comment by orta** [comment]
Agreed, I wonder if that should be the real fix

**Comment by segiddins** [comment]
Is it _really_ worth the effort to not show that message? If so, feel free to make a PR @mrackwitz

**Comment by mrackwitz** [comment]
It is super unimportant and we might be able to do bigger improvements to the outputs of the linter in non-verbose mode and verbose mode by tackling other things first, but it's the only thing in verbose mode which absolutely doesn't belong in there. So why not remove it?
