### ISSUE TITLE
Still getting non-modular header inside framework errors with 1.0.0-beta2

### ISSUE THREAD

**Issue by neitzj** [CocoaPods/CocoaPods#4805]
Hi,
we are creating a vendored framework that is distributed as a binary in cocoapods.

When including our framework with swift code we were getting errors just like case:
XCode 7.1 - Include of non-modular header inside framework #4420

We noticed that these errors went away if we removed the Public headers directory created by cocoapods. This directory appears to just be symlinking to all of our public headers from our framework.

Taking a look at the commit for 4420 it looks like you removed the generation of headers for the Private headers that are generated from frameworks but not for the Public headers. I would suggest that this should also be done for the Public headers.

Please let us know if this is something that is going to be addressed. Of if we can modify our podspec to prevent the public headers being generated from our framework.

Thanks.

**Comment by segiddins** [comment]
Can you share a project that demonstrates the issue? Thanks!

**Comment by neitzj** [comment]
I'm not sure if this will work as we are using a private cocoa pods repo for our new version of our framework. I will upload our test samples. Scribble application has a couple of swift files that should should show the issue.

[sample.zip](https://github.com/CocoaPods/CocoaPods/files/101152/sample.zip)

Our pod spec for our library looks like the following
Pod::Spec.new do |s|
  s.name      = "PureWebNightly"
  s.version      = "4.2.0.16"
  s.summary      = "Your software, out there: online, mobile & shared"
  s.description  = <<-DESC
                   The PureWeb platform lets you expose your complex or graphics 
                   intensive application as a back end service so it can be hosted 
                   online and accessed from new interfaces on browsers and mobile 
                   devices.
                   DESC
  s.homepage     = "http://www.calgaryscientific.com/pureweb"
  s.license      = { :type => 'Commercial', :text => 'Copyright 2014 Calgary Scientific Inc.' }
  s.author       = "Calgary Scientific Inc."
  s.platform     = :ios, '8.0'
  s.source       = { :http => "https://s3.amazonaws.com/pureweb-na/nightlies/PW/iOS/PureWeb-4.2.0-16-gc301edd.zip" }
  s.preserve_paths      = "PureWeb.framework"
  s.vendored_frameworks = "PureWeb.framework"
  s.frameworks = 'CFNetwork', 'CoreData', 'CoreGraphics', 'MobileCoreServices', 'QuartzCore', 'SystemConfiguration'
  s.libraries = 'icucore', 'xml2', 'z'
  s.requires_arc = true
  s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }
  s.dependency 'CocoaLumberjack'
end

I think you should be able to hit our S3 bucket to get the framework and go from there. Please let me know if there is anything else we can help with.

**Comment by segiddins** [comment]
I can't clone https://github.com/calgaryscientific/pureweb-ios-cocoapods, so I'm unable to install that sample.

**Comment by neitzj** [comment]
Yes it's a private repo I was hoping you could use the podspec plus our s3 bucket to recreate the repo yourself. If you can't do so I'll have to see if I can get permission to make our cocoapods repo public.

**Comment by segiddins** [comment]
Or you could just upload a project that has already been installed.

**Comment by neitzj** [comment]
I've added you as a collaborator you should have access now.

**Comment by segiddins** [comment]
The Podfile references `..` so I still can't install it. Could you please upload a full project that you've already run `pod install` on?

**Comment by neitzj** [comment]
Ok try this one
[sample.zip](https://github.com/CocoaPods/CocoaPods/files/105242/sample.zip)

**Comment by segiddins** [comment]
Builds fine for me

**Comment by neitzj** [comment]
We are seeing non-modular header includes because of the Public Headers directory Pods/Headers/Public/PureWebNightly/PureWeb/. Which seems to be the same case as #4420. Are you building the Scribble example because that contains swift code which is causing the problem for us?
 Is there anything we can do to prevent these headers from being generated?

**Comment by segiddins** [comment]
Yes, scribble builds fine for me in the project you sent.

**Comment by neitzj** [comment]
Try editing the scheme and building in release

**Comment by segiddins** [comment]
Also builds in release...

**Comment by neitzj** [comment]
And your using Xcode 7.2?

**Comment by segiddins** [comment]
yes

**Comment by neitzj** [comment]
One last attempt can you try a pod install and build

**Comment by houssr** [comment]
I was able to reproduce this using the sample posted after executing a "pod install".  Is there any progress on this issue?

**Comment by segiddins** [comment]
I've already spent a few hours investigating this issue, if someone wants to make a PR with a fix that'd be appreciated @houssr .

**Comment by kikolobo** [comment]
+1 Getting this using  [Groot Pod] (https://github.com/gonzalezreal/Groot) on an objective-c project with option set to use frameworks! in Podfile
