### ISSUE TITLE
Can't access preprocessor macro in framework if use_frameworks is in effect

### ISSUE THREAD

**Issue by ExoticObjects** [CocoaPods/CocoaPods#4806]
Caveat: This might be how things work and not an issue with cocoapods at all. The complications surrounding `use_frameworks!` are pretty arcane, so apologies in advance...

I began having this issues since trying to refactor a large library to `use_frameworks!`

This class

```objective-c
#import "EOConstantsLogging.h"
#import "DDLog.h"

@implementation EOConstantsLogging

int const ddLogLevel = LOG_LEVEL_VERBOSE;

@end
```

attempts to use `LOG_LEVEL_VERBOSE`, which is defined inside `DDLog.h`, which is part of `CocoaLumberjack`

resulting in this error:

`Use of undeclared identifier 'LOG_LEVEL_VERBOSE`

I'm guessing that since CocoaLumberjack is now a framework and not a static lib, I can't access preprocessor macros therein. But I'm not sure how I should deal with this. I've attempted all possible variations on the import statement for DDLog, to no avail...

**Comment by segiddins** [comment]
can you share a podfile we can use to debug this? Thanks!

**Comment by segiddins** [comment]
Perhaps you meant `DDLogLevelVerbose`?

**Comment by segiddins** [comment]
Ah its because https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Classes/DDLegacyMacros.h checks whether DD_LEGACY_MACROS is true, and that sort of check doesn't work with clang modules

**Comment by ExoticObjects** [comment]
This won't work?

`#if DD_LEGACY_MACROS`

If so, a lot of code is going to break!

Is there a list somewhere of things that don't work with clang modules?

**Comment by orta** [comment]
Probably a post install hook in the Podfile?

**Comment by ExoticObjects** [comment]
It really would be great if I could choose whether to use a dependency as a static library or a framework. The fact that I must do one or the other is causing a lot of issues. The post_install hook can't be the solution to every problem...
