### ISSUE TITLE
Can we selectively use frameworks more easily?

### ISSUE THREAD

**Issue by BenjaminBriggs** [CocoaPods/CocoaPods#4808]
Similar to the way `inhibit_all_warnings!` can be used on a individual pod (i.e `pod 'PodName' :inhibit_warnings => true`) can we have a way `use_frameworks!` can be applied to only specific pods (e.g `pod 'PodName' :use_framework  => true`?

I've worked out how to get my mix of frameworks by using something like this:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, 9.0

target :Frameworks do
  use_frameworks!
  link_with 'MyNewApp'
# Frameworks compatible pods
  pod 'SwiftyJSON'
end

target :MyNewApp do
# Framework incompatible pods
  pod 'Google', :inhibit_warnings => true
end
```

But it would be rather nice to have something a little neater; Maybe like this:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, 9.0

pod 'SwiftyJSON', :use_framework  => true
pod 'Google', :inhibit_warnings => true
```

Is this something that can be done?

**Comment by segiddins** [comment]
We've decided in the past that this introduces way too much complexity to the CocoaPods installer, and that our time is much better spent implementing other features. We'd be open to reviewing a PR that adds this functionality, but its unlikely we will write it ourselves.

**Comment by ExoticObjects** [comment]
Also, this example uses `link_with`, which is no longer supported.

**Comment by BenjaminBriggs** [comment]
@ExoticObjects Is there an official way to this?

**Comment by orta** [comment]
Use [CocoaPods-Rome](https://github.com/neonichu/Rome) or help us out :+1:
