### ISSUE TITLE
Preserving a Custom Build Phase Script

### ISSUE THREAD

**Issue by matthewcarroll** [CocoaPods/CocoaPods#4810]
In a pod project, I have a custom build phase script that runs before the standard Compile Source phase. When I run pod update for a target app, the downloaded Xcode project of the pod has the custom build phase script as expected. But the generated xcodeproj does not, causing the build to fail. Is it possible to  preserve the custom build script in the generated xcodeproj?

**Comment by segiddins** [comment]
No, podspecs can't specify custom build phases at the moment and it's not likely it's a feature that will be implement soon.

**Comment by mrackwitz** [comment]
There is the Podspec attribute [`prepare_command`](https://guides.cocoapods.org/syntax/podspec.html#prepare_command), but this is only executed once when the pod is integrated / after the download.

**Comment by abarth** [comment]
Related: http://stackoverflow.com/questions/20072937/add-run-script-build-phase-to-xcode-project-from-podspec

**Comment by segiddins** [comment]
I'm for closing this as out of scope for CocoaPods.

**Comment by orta** [comment]
Aye, me too.
