### ISSUE TITLE
ArgumentError - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by Andywcy** [CocoaPods/CocoaPods#4813]
I update the cocoapods to 1.0.0.beta.2 ,when I excute "pod install" ,the problem is as following:

### Error

```
ArgumentError - invalid byte sequence in UTF-8
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.0.beta.2/lib/cocoapods-core/podfile.rb:279:in `tr!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.0.beta.2/lib/cocoapods-core/podfile.rb:279:in `from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.0.beta.2/lib/cocoapods-core/podfile.rb:253:in `from_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/config.rb:189:in `podfile'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command.rb:112:in `verify_podfile_exists!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command/project.rb:96:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

Anyone can help me?

**Comment by segiddins** [comment]
Can you please gist your podfile? Also, what encoding do you have set as your default?

**Comment by Andywcy** [comment]
I wrote a demotest.Simply,only include JSONKit.It is the Podfile.

platform :ios, ‘7.0’
pod 'JSONKit'

the locale output is following:

LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

I am a newcomer to use cocoapods,so could you give me some suggestion? I can use cocoapods commands normally before,when updated, it appeared the problems.

**Comment by segiddins** [comment]
Quick fix would be to fix the smart quotes in the Podfile.
What's the output of `ruby -e 'puts Encoding.default_external'`? If it's not UTF-8, then that's the issue.

**Comment by Andywcy** [comment]
Sorry ,it is my fault.I check the Podfile carefully,the problem is the single quotes.Thank you very much!

**Comment by DengshanZhang** [comment]
@segiddins   ,I use the    ruby -e 'puts Encoding.default_external'   command, the result is   UTF-8, while the same problem occurs,   oh my!   could  you  help me.

**Comment by ashokds** [comment]
@segiddins For me `ruby -e 'puts Encoding.default_external'` output is `UTF-8`. This error is happening intermittently for some branches only. 

Podfile diff only has change in the branch a pod is pointing. 
We have a internal pod (framework) and branches are switched frequently in the podfile. 

Do you think some error in the podspec could affect it?

`pod env`
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.10
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3767083dfacddcf972ffcc05917c70e8dd0f27c2
```

### Installation Source

```
Executable Path: /usr/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```
