### ISSUE TITLE
Project headers are copied into build directory when header_mapping_dir is set

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#4819]
If a target is integrated with frameworks and the podspec specifies a value for `header_mapping_dir`, project headers are copied into the build directory instead of an expected framework header path. This is because the build phase created by the `PodTargetInstaller` relies on `PROJECT_HEADERS_FOLDER_PATH`, which doesn't exist by default.

**Comment by segiddins** [comment]
Ah, so it's only an issue for project headers -- `PUBLIC_HEADERS_FOLDER_PATH` and `PRIVATE_HEADERS_FOLDER_PATH` both exist. This should be enough info to know where to look now, thanks for investigating @mrackwitz :)

**Comment by segiddins** [comment]
The following may be a sufficient fix, I'm not sure.

```diff
diff --git a/lib/cocoapods/installer/target_installer/pod_target_installer.rb b/lib/cocoapods/installer/target_installer/pod_target_installer.rb
index 34a1ef2..d5ad812 100644
--- a/lib/cocoapods/installer/target_installer/pod_target_installer.rb
+++ b/lib/cocoapods/installer/target_installer/pod_target_installer.rb
@@ -349,7 +349,7 @@ module Pod
                 'Project'
               end
 
-        if target.requires_frameworks? && header_mappings_dir
+        if target.requires_frameworks? && header_mappings_dir && acl != 'Private'
           relative_path = file_ref.real_path.relative_path_from(header_mappings_dir)
           sub_dir = relative_path.dirname
           copy_phase_name = "Copy #{sub_dir} #{acl} Headers"
```

**Comment by mrackwitz** [comment]
Yeah, that should be possible to fix it like suggested as project headers shouldn't be necessary at all for the compiler to build against a framework.

**Comment by segiddins** [comment]
it actually doesn't in its entirety.
