### ISSUE TITLE
Compile errors when adding new pod

### ISSUE THREAD

**Issue by amir-sabbaghi** [CocoaPods/CocoaPods#4826]
I have a working project which has 2 pods and its working.
Then I add this line to one of the targets: pod 'Google/AppInvite', '~> 1.0.2'
and 'pod install' works without errors.
But when I try to build the project OTHER pods do not compile and the errors come from low level headers.
![screen shot 2016-01-27 at 11 55 22 am](https://cloud.githubusercontent.com/assets/3251721/12608081/dce6a6c8-c4ee-11e5-87b0-4efe070416cb.png)

### Stack

```
   CocoaPods : 1.0.0.beta.2
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.7.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ be91c3a0127b83bb5d023b5f8763dbb3b8e33299
               pichak - git@gitlab.******.**:****-********/specs.git @ 3dbba63268b02d8e7c56f900e22be0654d655634
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.2
```

**Comment by orta** [comment]
Hi, this looks like a problem with the source code from one of the pods you've included, you might want to raise an issue on their repos.

**Comment by amir-sabbaghi** [comment]
Then why is it compiling without problems if I don't add AppInvite?

**Comment by orta** [comment]
Because AppInvite is adding more source code to your project, CocoaPods the tool doesn't add any code to your project, the pods do.

**Comment by amir-sabbaghi** [comment]
I found out that if you add both libsodium and AppInvite together in a target you will see the errors.
But they are working If I don't add them to a single target.
It is absolutely CocoaPods that cannot integrate them nicely together.
And the errors come from very low level system headers, not their source code.
The errors are in 'NSObjCRuntime.h', 'NSZone.h', 'NSObject.h' ...

**Comment by orta** [comment]
This is a much better error report, awesome. 
Can you please provide an example project?

**Comment by amir-sabbaghi** [comment]
1 - Create a new iOS project.
2 - pod init
3 - add pod 'libsodium'
4 - add pod 'Google/AppInvite', '~> 1.0.2'
5 - pod install
6 - build the project
:D

**Comment by amir-sabbaghi** [comment]
I had the same problem with the stable version (0.39) as well.

**Comment by amir-sabbaghi** [comment]
This happens with 'Google/Analytics' too.

**Comment by neonichu** [comment]
The issue here is that both the Google Pod and libsodium have a header called "core.h". While building libsodium, its header search paths will also include the Google headers and therefore the wrong header is picked. 

A workaround is to change libsodium's core.c to explicitly `#include <libsodium/core.h>`

**Comment by gioenn** [comment]
I have the same issue with Google/CloudMessaging

**Comment by segiddins** [comment]
Closing as an issue with the given pods.
