### ISSUE TITLE
Compiling Workspace with CONFIGURATION_BUILD_DIR option fails

### ISSUE THREAD

**Issue by matzew** [CocoaPods/CocoaPods#483]
I have the following project, which is successfully using Cocoapods:
https://github.com/aerogear/aerogear-ios/

However what bugs me is that I can only change the 'build' directory via Xcode (File->Workspace Settings...)

When I change the location in the 'Build Setting->Build Locations' section from the 'AeroGear-iOS' target, I am getting an error....

I am getting the same error when issuing the following command on the command line:

```
xcodebuild -scheme AeroGear-iOS -sdk iphonesimulator -workspace AeroGear-iOS.xcworkspace -configuration Release clean build CONFIGURATION_BUILD_DIR='buildy'
```

The error that I am getting is the following 

```
    Libtool buildy/libAeroGear-iOS.a normal i386
    cd /Users/wessi/Work/JBoss/iOS/aerogear-ios/AeroGear-iOS
    setenv MACOSX_DEPLOYMENT_TARGET 10.6
    setenv PATH "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/asf/maven/current/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only i386 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.1.sdk -L/Users/wessi/Work/JBoss/iOS/aerogear-ios/AeroGear-iOS/buildy -filelist /Users/wessi/Work/JBoss/iOS/aerogear-ios/AeroGear-iOS/BUILD/AeroGear-iOS/Build/Intermediates/AeroGear-iOS.build/Release-iphonesimulator/AeroGear-iOS.build/Objects-normal/i386/AeroGear-iOS.LinkFileList -ObjC -framework Foundation -lPods -o /Users/wessi/Work/JBoss/iOS/aerogear-ios/AeroGear-iOS/buildy/libAeroGear-iOS.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: -dynamic not specified the following flags are invalid: -ObjC 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods is not an object file (not allowed in a library)
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool failed with exit code 1


** BUILD FAILED **


The following build commands failed:
    Libtool buildy/libAeroGear-iOS.a normal i386
(1 failure)
```

However, without the CONFIGURATION_BUILD_DIR the build works fine...

```
xcodebuild -scheme AeroGear-iOS -sdk iphonesimulator -workspace AeroGear-iOS.xcworkspace -configuration Release clean build
```

**Comment by nadyaA** [comment]
Hi guys,

I have ran into this issue, building a project with cocoapods [CocoaLumberjack](https://github.com/CocoaLumberjack/CocoaLumberjack) and [GCDWebServer](https://github.com/swisspol/GCDWebServer) and using xcodebuid with **CONFIGURATION_BUILD_DIR** explicitly set.

As it is stated in the [documentation](http://help.apple.com/xcode/mac/8.3/#/itcaec37c2a6) -  **CONFIGURATION_BUILD_DIR** specifies the Build Products Path - i.e. the base path where build products will be placed during a build for a given configuration. By default, this is set to $(BUILD_DIR)/$(CONFIGURATION).  This way all pods were build in the same place and in my case the GCDWebServer [sees the headers](https://github.com/swisspol/GCDWebServer/blob/83f1c062b52a21ed62168580f98f3f91f4bad856/GCDWebServer/Core/GCDWebServerPrivate.h#L62) of CocoaLumberjack, tries to load some source and fails with the following error:

Undefined symbols for architecture arm64:
 "_OBJC_CLASS_$_DDLog", referenced from:
     objc-class-ref in GCDWebServer.o
     objc-class-ref in GCDWebServerConnection.o
     objc-class-ref in GCDWebServerFileResponse.o
     objc-class-ref in GCDWebServerFunctions.o
     objc-class-ref in GCDWebServerMultiPartFormRequest.o
     objc-class-ref in GCDWebServerRequest.o
ld: symbol(s) not found for architecture arm64

The workaround I found is to build the project setting explicitly the **BUILD_DIR** instead. It works fine that way.

Hope this saves some time :slightly_smiling_face:

**Comment by matteocollina** [comment]
This is my gist that makes .app for simulator : https://gist.github.com/matteocollina/8d0fe3a569695b2924654975046da2fe
