### ISSUE TITLE
CocoaPods hangs on unpacking boost 1.59 when executing pod install

### ISSUE THREAD

**Issue by issue2k** [CocoaPods/CocoaPods#4830]
Hello,

when trying to integrate boost library into one of our projects the pod installation process hangs on extracting the downloaded file,  nothing happens after the last line:

```
 $ /usr/bin/tar xfz /var/folders/gc/6x2pdd557zsg_p2lcrhvq8p80000gn/T/d20160127-36204-18s54gb/file.tgz -C /var/folders/gc/6x2pdd557zsg_p2lcrhvq8p80000gn/T/d20160127-36204-18s54gb
```

pod install --verbose
```
Installing boost (1.59.0)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/gc/6x2pdd557zsg_p2lcrhvq8p80000gn/T/d20160127-36204-18s54gb/file.tgz http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz
   --create-dirs
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0   353    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     0   429    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
     0   343    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100 79.8M  100 79.8M    0     0   521k      0  0:02:36  0:02:36 --:--:--  669k
   $ /usr/bin/tar xfz /var/folders/gc/6x2pdd557zsg_p2lcrhvq8p80000gn/T/d20160127-36204-18s54gb/file.tgz -C /var/folders/gc/6x2pdd557zsg_p2lcrhvq8p80000gn/T/d20160127-36204-18s54gb
```

Any suggestions?

**Comment by issue2k** [comment]
ok after waiting for around 10-15 minutes it continued. Maybe it makes sense to speed that up somehow? When i execute the same extraction command on another shell it is done within seconds.

**Comment by orta** [comment]
We're running the commands you're seeing in the log, you're welcome to dig into [cocoapods-downloader](https://github.com/CocoaPods/cocoapods-downloader) to see if there's anything that could cause it to go slower?

**Comment by dnkoutso** [comment]
FWIW running `curl -f -L -o /var/folders/gc/6x2pdd557zsg_p2lcrhvq8p80000gn/T/d20160127-36204-18s54gb/file.tgz http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz` on the command line just by itself takes a long time for me as well.

I dont think its CocoaPods related...

**Comment by issue2k** [comment]
@orta @dnkoutso please read my post again. Its not related to the download, the speed of the curl of course depends on server and line speed... What takes time is unpacking the tar, but only when using CocoaPods. If i do it manually its unpacked in a couple of seconds.

**Comment by segiddins** [comment]
Either way, if this is an issue it belongs to cocoapods-downloader, not CocoaPods proper.

**Comment by issue2k** [comment]
@segiddins ok thanks i will create an issue there

**Comment by madhavajay** [comment]
This exact thing just happened to me, same version of boost. It took like... 5 minutes or so? Really long to extract. The download in verbose was 16 seconds. When I extracted it myself using the same command it ran, it was a few seconds. Something weird definitely going on.

I even did a full update of everything ruby and cocoapods related, but it didn't help.

**Comment by DikeyKing** [comment]
Met the same problem ...
Reboot mac and pod update again solve this problem (wait for about 5 minutes after finished downloading)

**Comment by ohtangza** [comment]
I am also experiencing this...

**Comment by philolo1** [comment]
@issue2k can you link your newly created issue here?

**Comment by issue2k** [comment]
@philolo1 i never did that, no longer using cocoapods, feel free to proceed

**Comment by sergeyzhukov** [comment]
same here, cocoapods 1.3.1

**Comment by a-r-d** [comment]
Yes if you follow the instructions on the [React native getting started guide](http://facebook.github.io/react-native/docs/integration-with-existing-apps.html) for integrating with an existing app, you will be able to reproduce this problem.

I opened this [issue](https://github.com/CocoaPods/CocoaPods/issues/7210) before I saw this one, I never thought of waiting 15 minutes.

**Comment by shaikatz** [comment]
I did a test and disabling cocoapods cache solves that issue, there most be some problematic behavior in the caching mechanism.

You can disable it by creating a ~/.cocoapods/config.yaml file with the following contents.

`skip_download_cache: true`

**Comment by chrismcleod** [comment]
same thing happened to me but turned out to be bc my internet dropped.  probably just me, but who knows

**Comment by lakhman** [comment]
checkout my answers here:

- https://github.com/CocoaPods/cocoapods-downloader/issues/69#issuecomment-351159255
- https://github.com/react-community/create-react-native-app/issues/436#issuecomment-351159011

**Comment by Pranit-Harekar** [comment]
Same cocoapods 1.3.1
@lakhman How would you do that on travis ? The only way I can think of is writing a [sed](https://www.gnu.org/software/sed/manual/sed.html) substitute script to replace the download url. Is there any better way of changing that url ?

**Comment by lakhman** [comment]
I think it should be done via the repository somewhere.
Maybe: https://github.com/CocoaPods/Specs?

I _think_ the url has changed, but the repository hasn't been updated, or maybe I had a version mismatch locally.

``` bash
# Notice the '9/9/d/' - my version didn't have that
# but I had an older version that threw a 404.
# repos/master/Specs/9/9/d/boost/1.59.0/boost.podspec.json
```

I don't know how to do this on travis, this is just a "quick fix" - hopefully someone can figure out a permanent solution.

**Comment by Pranit-Harekar** [comment]
@lakhman Thanks for your response. Yes we need to fix this permanently.

**Comment by itinance** [comment]
The issue is caused by an invalid tar.gz-file for boost that only contains plain text with html-code of SourceForge:

```
/usr/bin/curl -f -L -o /private/tmp/ZizzleApp/ios/Pods/boost/file.tgz http://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz --create-dirs --netrc-optional

less /private/tmp/ZizzleApp/ios/Pods/boost/file.tgz
```

the `less` command will list something like:

```
<!doctype html>
<!-- Server: sfs-consume-5 -->

<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]>--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><script type="text/javascript">(window.NREU
```


![screen shot 2018-01-04 at 08 52 10](https://user-images.githubusercontent.com/1758597/34554321-97bb1752-f12c-11e7-961c-9ac6a18804dc.png)

**Comment by itinance** [comment]
Apparently the people behind boost aren't interested in fixing their issue. Is it possible to install boost from another location where i can fix it by myself?

**Comment by orta** [comment]
Could you PR this to boost? https://github.com/CocoaPods/Specs/pull/14361

**Comment by Pranit-Harekar** [comment]
** **This is only for Travis builds.**
If you are facing this issue on Travis like I mentioned [here](https://github.com/CocoaPods/CocoaPods/issues/4830#issuecomment-351788142), you can wait for boost tarfile to unpack using `travis_wait`. It takes almost 20-25 minutes to unpack for the first time, but if you have pod cache enabled like this
```yaml
cache: 
    - cocoapods
```
then it will take few seconds from second time onwards. If you don't do `travis_wait` then build will timeout after 10 minutes causing it to fail.

**Comment by vjpr** [comment]
Use @lakhman's intructions but use url: https://github.com/boostorg/boost/archive/boost-1.59.0.tar.gz

sourceforge didn't work for me.

**Comment by pisacode** [comment]
@vjpr I have waited more than 20 min for the yoga running pre install hooks and it did not finish. I had to cancel pod install

**Comment by khiettran** [comment]
@pisacode  I got the same issue, then I updated to RN 0.55, it's resolved but I don't prefer this workaround.

**Comment by FrederickEngelhardt** [comment]
Trying not to necro this topic but to speed up the install, you will need to **multithread tar extraction**.

On mac by default boost is extracted by tar on a single thread. As a workaround, in bash you can do something like this.

1. Install [pbzip2](https://linux.die.net/man/1/pbzip2) which unpacks tar in parallel (multiple threads / cores) `brew install pbzip2`
2. Add something like this script to your shell environment. Example spot if you use zsh  would be the `$HOME/.zshrc` file.

```shell
tar(){  
  if [ $(command -v ) ]; then
    command pbzip2 -dkv file.tbz | tar $1 $2.out $3 $4 ${5:@}
    else
    command tar $@
  fi
}
```

Noting that this script will only override the tar method if pbzip2 exists. But it may break other tar extraction scripts. Consider adding [direnv](https://direnv.net/) and adding a .envrc file with this script in your repo.
