### ISSUE TITLE
Cant fetch podspec

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#4831]
I have a local pod spec that points to CocoaMarkdown.

```ruby
Pod::Spec.new do |s|
  s.name  = 'CocoaMarkdown'
  s.version = '1.0'
  s.summary = 'Markdown parsing and rendering for iOS and OS X'
  s.author = { 'Sincerely' => 'dev@sincerely.com' }
  s.homepage = 'https://github.com/indragiek/CocoaMarkdown.git'
  s.license = 'MIT'
  s.source = {
    :git => 'https://github.com/indragiek/CocoaMarkdown.git',
    :branch => 'master',
    :submodules => true
  }
  s.frameworks = 'Foundation'
  s.library = 'xml2'

  s.platform     = :ios, '8.0'
  s.requires_arc = true
  s.source_files = 'CocoaMarkdown/Classes/**/*'
  s.public_header_files = 'CocoaMarkdown/Classes/*.h'
end
```

My Podfile:

```ruby
pod 'CocoaMarkdown', :path => './Local Podspecs/CocoaMarkdown.podspec'
```

And everything is cool until I build for device. it says file is not found. At the same time this works for simulator.

```
#import <CocoaMarkdown/CocoaMarkdown.h>
```

**Comment by segiddins** [comment]
What version of CocoaPods are you using? Are you sure you mean to use `path` and not `podspec`?

**Comment by pronebird** [comment]
Just trying to feed it with podspec because I want it to use remote repo that doesn't have a podspec in it. I think I have cocoa pods 0.39 latest stable.

**Comment by pronebird** [comment]
I think you are right and I have to use podspec, not path. I will check that shortly

**Comment by pronebird** [comment]
I changed to path to pod spec:

```rb
pod 'CocoaMarkdown', :podspec => './Local Podspecs/CocoaMarkdown.podspec'
```

And fixed the pod spec itself where I by mistake put the wrong paths.

```rb
Pod::Spec.new do |s|
  s.name  = 'CocoaMarkdown'
  s.version = '1.0'
  s.summary = 'Markdown parsing and rendering for iOS and OS X'
  s.author = { 'Sincerely' => 'dev@sincerely.com' }
  s.homepage = 'https://github.com/indragiek/CocoaMarkdown.git'
  s.license = 'MIT'
  s.source = {
    :git => 'https://github.com/indragiek/CocoaMarkdown.git'
  }
  s.framework = 'UIKit'
  s.library = 'xml2'

  s.platform = :ios, '8.0'
  s.requires_arc = true
  s.source_files = 'CocoaMarkdown/**/*'
  s.public_header_files = 'CocoaMarkdown/*.h'

  s.dependency 'cmark'
  s.dependency 'Ono'
end
```

However now randomly some of modules are missing. E.g. PureLayout cannot be found anymore while previously it worked. Markdown module seem to be present. I tried deintegrate and fresh installation without luck. So I am trying cocoa pods beta now to see if that makes any difference.

**Comment by pronebird** [comment]
I don't know what's going but apparently the issue is that Pods project does not build automatically and I have to switch to it manually, build it and then switch back to the app to be able to run the app. Pods.framework is in Linked Frameworks in app target.

**Comment by pronebird** [comment]
Solved

**Comment by orta** [comment]
Can you write up what you did incase someone else is [following your path](https://xkcd.com/979/)?

**Comment by pronebird** [comment]
@orta I've added "Pods" framework in Scheme management under Build tab and moved it above the app. I don't know why "Linked Frameworks" does not establish the dependency.

**Comment by pronebird** [comment]
Related to #4839. Implicit dependencies should be on to ensure that all dependencies are built before the app.
