### ISSUE TITLE
Failed to verify code signature

### ISSUE THREAD

**Issue by Payload-Lee** [CocoaPods/CocoaPods#4832]
When attempting to run iOS app using the standard Release build configuration (or custom build configurations created by duplicating the Release or Debug build configuration) on a development device (ID added to dev account) connected to Xcode the build succeeds but the app fails to install on iOS 8.3 devices (installs successfully on iOS 9.0 or 9.2 devices). Xcode displays an error alert “App installation failed - The application does not have a valid signature”

If I build and run using the standard Debug build config the app installs successfully on an iOS 8.3 device.

Our app is comprised of a Swift Cocoa Touch Framework project (PayloadCommon which you'll see referenced in the logs below) and a Swift iOS Application project (PayloadApp). Most of the pods we're using are added to PayloadCommon but a few are added to PayloadApp. Some of the pods are native Swift frameworks such as RealmSwift and Alamofire.

All of the pods frameworks from PayloadCommon plus the PayloadCommon.framework and Pods_PayloadCommon.framework are included under Embedded Binaries for the PayloadApp iOS application target.

The device logs contain the following:

```
Jan 14 09:54:39 iPhone installd[36] <Error>: 0x581000 -[MICodeSigningVerifier performValidationWithError:]: 188: Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.zJta5l/extracted/PayloadApp.app/Frameworks/Pods_PayloadCommon.framework identifier = org.cocoapods.Pods-PayloadCommon type = 8> : 0xe8008019 (Application signature not valid)

Jan 14 09:54:39 iPhone installd[36] <Error>: 0x581000 -[MIInstaller performInstallationWithError:]: Verification stage failed

Jan 14 09:54:39 iPhone streaming_zip_conduit[173] <Error>: 0x481000 __MobileInstallationInstallForLaunchServices_block_invoke240: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.zJta5l/extracted/PayloadApp.app/Frameworks/Pods_PayloadCommon.framework identifier = org.cocoapods.Pods-PayloadCommon type = 8> : 0xe8008019 (Application signature not valid)" UserInfo=0x15674f50 {LibMISErrorNumber=-402620391, LegacyErrorString=ApplicationVerificationFailed, FunctionName=-[MICodeSigningVerifier performValidationWithError:], NSLocalizedDescription=Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.zJta5l/extracted/PayloadApp.app/Frameworks/Pods_PayloadCommon.framework identifier = org.cocoapods.Pods-PayloadCommon type = 8> : 0xe8008019 (Application signature not valid), SourceFileLine=188}

Jan 14 09:54:39 iPhone streaming_zip_conduit[173] <Warning>: ERROR: MobileInstallationInstallForLaunchServices returned nil

Jan 14 09:54:39 iPhone streaming_zip_conduit[173] <Warning>: __dispatch_source_read_socket_block_invoke:203: Failed to install application at file:///var/mobile/Media/PublicStaging/PayloadApp.app/ : Error Domain=LaunchServicesError Code=0 "The operation couldn’t be completed. (LaunchServicesError error 0.)" UserInfo=0x15675030 {Error=ApplicationVerificationFailed, ErrorDetail=-402620391, ErrorDescription=Failed to verify code signature of <MIExecutableBundle : path = /private/var/mobile/Library/Caches/com.apple.mobile.installd.staging/temp.zJta5l/extracted/PayloadApp.app/Frameworks/Pods_PayloadCommon.framework identifier = org.cocoapods.Pods-PayloadCommon type = 8> : 0xe8008019 (Application signature not valid)}
```

**Comment by segiddins** [comment]
They should be embedded by the CocoaPods embed framework script, instead of putting them under embedded binaries in the Xcode project.

**Comment by Payload-Lee** [comment]
Thanks for the reply @segiddins - Based your response I removed these from the embedded binaries in the Xcode iOS app project. Now when I compile and run the app the app immediately crashes on launch with the error:
```dyld: Library not loaded: @rpath/OAStackView.framework/OAStackView
  Referenced from: /var/mobile/Containers/Bundle/Application/5911CC0E-6F71-4B17-B640-7489174CF794/PayloadApp.app/PayloadApp
  Reason: image not found
```

OAStackView is one of the frameworks CocoaPods is building. If I manually add this framework back under embedded binaries in the Xcode project, build and run then the same crash happens but the error will show another one of the frameworks CocoaPods is building for use by our PayloadCommon Cocoa Touch Framework target.

The Embed Pods Frameworks script for the PayloadApp target is "${SRCROOT}/../Pods/Target Support Files/Pods-PayloadApp/Pods-PayloadApp-frameworks.sh”

In taking a look at the contents of Pods-PayloadApp-frameworks.sh (which I can confirm from the build logs is being executed without error) I don’t see any references to Pods-PayloadCommon-frameworks.sh which I understand would be the CocoaPods embed framework script for our Cocoa Touch Framework target. I also see that our Cocoa Touch Framework target does not have a CocoaPods embed framework script build phase. So perhaps Pods-PayloadCommon-frameworks.sh is not being executed and this is the root cause? Either way am I missing something in our CocoaPods configuration that is causing this issue?

**Comment by segiddins** [comment]
Wait, are you using CocoaPods to integrate into a framework? That's currently unsupported

**Comment by Payload-Lee** [comment]
That's correct. I've read a lot of the CocoaPods documentation and haven't seen mention of this limitation. Could you please point me to where this is documented? Also, are you aware of any plans to support this in the near future?

**Comment by segiddins** [comment]
It's not really documented, we just support integrating into app targets. It's fundamentally not possible to support, since all frameworks need to be copied into the app directly anyways.

**Comment by Payload-Lee** [comment]
@segiddins - Thanks for your previous response, having thought that through more I now understand why there’s a limitation for Cocoa Touch Frameworks. 

I do however wish to confirm whether or not CocoaPods officially supports integrating into a Cocoa Touch Static Library? I have used this successfully in the past (circa iOS 6) with a production app deployed to the App Store. I had pods integrating into both a Cocoa Touch Static Library project target and an app project target. Code in the app project called methods in the Cocoa Touch Static Library project.

The reasoning behind this architecture is that I had common business logic in the a Cocoa Touch Static Library project that was also consumed by a second, different app project.

Thanks again.

**Comment by segiddins** [comment]
Nope. We only would support turning your static library target into a pod itself.
