### ISSUE TITLE
Too many configurations for Pods project

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#4834]
I create a new project and define three configurations:
![three configurations](http://i.imgur.com/OHCBC24.png)

I add a Podfile, but generated Pods project has five configurations:
![five configurations](http://i.imgur.com/N8bINoi.png)

Would it be possible, for the Pods project, to have only 2 configurations (release/debug) or X configurations (the podfile targets configs), and not X+2?

**Comment by segiddins** [comment]
Do the additional configurations actually cause a bug?

**Comment by Coeur** [comment]
No bug, but it causes confusion.

In Podfile, `:debug` and `:release` only work for [a whole xcodeproj](https://guides.cocoapods.org/syntax/podfile.html#xcodeproj)? I can't define it for a project configuration or a project scheme?

**Comment by Coeur** [comment]
Oh, to answer my own question, I figured out how the syntax works:

    xcodeproj `MyProject`, 'Custom 1' => :release, 'Custom 2' => :debug, 'Custom 3' => :debug

**Comment by Coeur** [comment]
Apparently, all those X configurations are strictly identical to Release configuration. So initially they are useless. *I suggest that at `pod install`, only Debug and Release should be created.*

**Comment by segiddins** [comment]
@Coeur not possible, because of how Xcode does implicit target resolution

**Comment by Coeur** [comment]
OK.
