### ISSUE TITLE
About include of non-modular header inside framework module

### ISSUE THREAD

**Issue by hilen** [CocoaPods/CocoaPods#4835]
Hi, I found that when I use cocoapods in my Swift project, there always come out the error ` include of non-modular header inside framework module xxx`. About three libraries has this error, same as #4504 #4420,  It make me comfuse for a long time.

Just now I remember that I add this line `${SRCROOT} ` to the `Build Settings -> Header Search Paths ` , as the image show : ![image](https://cloud.githubusercontent.com/assets/2245840/12638051/06ad17c6-c5d5-11e5-96bd-8e0893142c67.png)

But when I remove it , everything is ok. I think there must be something wrong with the `recursive` and the `framework`. Whey does this happen?

**Comment by segiddins** [comment]
Yeah, recursive header search paths often create massive headaches.

**Comment by hilen** [comment]
If I am using the recursive header search paths, is there a solution to fix it ?

**Comment by segiddins** [comment]
not sure. I'd go so far as to say that this isn't technically a _bug_ but just how recursive search paths work.

**Comment by hilen** [comment]
ok, Thanks
