### ISSUE TITLE
Two targets get the same support files dir

### ISSUE THREAD

**Issue by niklassaers** [CocoaPods/CocoaPods#4837]
In my Podfile I need to have two different xcodeprojs. They each have a target called "Unit tests" for which I define my target like this:

```
target 'Unit tests' do
  xcodeproj 'MainProject.xcodeproj'

  pod 'KGNoise'
end

target 'Unit tests' do
  xcodeproj '../CommonFramework/CommonFramework.xcodeproj'

  pod 'MyRandomDataGenerators'
end
```

This gives me the following error:

```
Errno::EEXIST - File exists - /Users/niklas/projects/MainProject/Pods/Target Support Files/Pods-Unit tests
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/target_installer.rb:90:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/target_installer.rb:90:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/target_installer.rb:90:in `create_support_files_dir'

---
```

The reason I cannot simply make a pod spec for the CommonFramework project is that it links to binaries, and that then gives me an error about transitive binary dependencies.

My temporary workaround is to prefix the 'Unit tests' targets.

The details:
### Stack

```
   CocoaPods : 1.0.0.beta.2
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.3 (7D129n)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e5ec0130096eb530b79e0d6c8390fffb8bd45014
               niklassaers - https://github.com/niklassaers/PrivatePods.git @ 45f5f42ab57aa183334f5c2668ef2f2ee4bc793c
```
### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-keys        : 1.6.0
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.2
```

**Comment by segiddins** [comment]
We currently don't support targets with the same name in different Xcode projects, but this should give a more helpful error.

**Comment by fcy** [comment]
I started reorganizing my projects and decided to use CocoaPods 1.0 - currently beta 6 - and got this same error. It feels to me that the target inheritance is broken, for example:

```
workspace 'MyCompany'

target 'AppA` do
  project 'AppA/AppA.xcodeproj'

  target 'UnitTests` do
    inherit! :search_paths

    pod 'Kiwi'
  end
end

target 'AppB' do
  project 'AppB/AppB.xcodeproj' 

  target 'UnitTests` do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
```

I really like the 1.0 DSL, it looks like everything is nicely scoped. Until I got the same problem as he because of targets with the same name in different projects not being supported. Here is my vote for supporting this, it makes me sad to have to rename my targets because my beloved dependency management tools doesn't support the way they are now.

**Comment by orta** [comment]
This is just the "CocoaPods name", which can work by implicit matching, you could use a different structure ( I think. )

```
target 'AppB' do
  project 'AppB/AppB.xcodeproj' 

  abstract_target 'AppBUnitTests` do
    inherit! :search_paths
    target 'UnitTests' 

    pod 'Kiwi'
  end
end
```

**Comment by fcy** [comment]
@orta that workaround(?) worked. It reminded me of this sentence from the Migrating to 1.0 blog post:

> A large fraction of the bug reports we receive is due to the ambiguity in the Podfile. It gave a lot of freedom to create all kinds of CocoaPods setups that **would work by luck of implementation details**, or work but are significantly more complex than they needed to be.

Emphasis mine. Does it work just because of lucky implementation detail?

---

Related to abstract targets, could I define one `SharedUnitTests` abstract target and apply it to both real targets? Something like this:

```
abstract_target 'StandardUnitTests' do
  inherit! :search_paths
  pod 'Kiwi', '~> 3.0'
end

target 'AppA' do
   # somehow implements/apply the abstract target to real target
  target 'AppAUnitTests do
    apply_abstract_target 'StandardUnitTests`
  end
end
```
