### ISSUE TITLE
Headers are not found

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#4839]
I receive a lot of `File <Framework/Header.h>` is not found. I switched to beta and now back to 0.39 to see if that makes any difference. It doesn't. CMD+click on #import statement actually works so I am not sure why headers cannot be found during compilation.

I tried pod deintegrate without any luck.

My pod file:

```rb
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

pod 'libextobjc/EXTScope', '~> 0.4.1'
pod 'libextobjc/EXTSynthesize', '~> 0.4.1'

pod 'Lookback', '~> 1.1.4', :configurations => ['Debug']
pod 'LookbackSafe', '~> 1.1.4', :configuration => ['Release', 'Testing']

pod 'AFNetworking', '~> 2.6.0'
pod 'Mantle', '~> 2.0.5'
pod 'Fabric'
pod 'Crashlytics'
pod 'Ensembles', '~> 1.4.3'
pod 'PureLayout', '~> 3.0.1'
pod 'CHCSVParser', '~> 2.1.0'
pod 'ZipUtilities', '~> 1.7.0'
pod 'MD5Digest', '~> 1.1.0'

pod 'LNNotificationsUI', :git => 'https://github.com/LeoNatan/LNNotificationsUI.git'
pod 'CocoaMarkdown', :git => 'https://github.com/pronebird/CocoaMarkdown.git', :branch => 'feature/podspec'

# dev pods
# pod 'MagicalRecord', :path => './MagicalRecord'
# pod 'Operative', :path => './Operative'

pod 'MagicalRecord', :git => 'https://github.com/pronebird/MagicalRecord', :branch => 'merged-patches-and-concurrency-debug-fix'
pod 'Operative', :git => 'https://github.com/pronebird/Operative', :branch => 'develop'

target 'Tests1' do
#  pod 'Aspects', '~> 1.4.1'
end

target 'Tests2' do
  pod 'Aspects', '~> 1.4.1'
end
```

**Comment by segiddins** [comment]
Can you share a project that reproduces the issue, or try and dig into whether the {FRAMEWORK,HEADER}_SEARCH_PATHS are set correctly?

**Comment by pronebird** [comment]
@segiddins can't really share. I think my project was somehow destroyed by cocoapods so now I am seeing all kind of weird things... I gotta check search paths first and let you know about my findings.

**Comment by pronebird** [comment]
So essentially after creating a test project, I see that in test project frameworks are being built first, then the app. In my project app is built first and frameworks are never built. I checked search paths configuration and it's exactly the same. The important piece is Custom Compiler Flags, this is where I can see all paths to Headers folders for each framework in build directory. I am still looking why and how to make it build Pods project first. I can't visually find the way to specify that dependency, both test project and my project look the same.

**Comment by pronebird** [comment]
"Find implicit dependencies" was the case. I cannot believe Xcode does not automatically establish dependencies for linked frameworks.

<img width="283" alt="screenshot 2016-01-28 17 20 37" src="https://cloud.githubusercontent.com/assets/704044/12652688/db7f19aa-c5e3-11e5-853a-486b604961aa.png">
