### ISSUE TITLE
`install!` should show all the options in it's reference documentation

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#4842]
Likely just mixing https://guides.cocoapods.org/syntax/podfile.html#install_bang with https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/installation_options.rb#L104-L108

**Comment by segiddins** [comment]
That's tough, since the options don't live in Core. We could special case this in the guides doc generation process, though.

**Comment by orta** [comment]
Could add a note in `installation_options.rb` that they should be documented in the Podfile DSL rb?

**Comment by segiddins** [comment]
No, that would be horrific duplication. We should instead join them in the guides.

**Comment by orta** [comment]
argh, I was hoping you wouldn't say that :P
