### ISSUE TITLE
Overriding xcconfig file path to prevent warning about custom config set

### ISSUE THREAD

**Issue by m1entus** [CocoaPods/CocoaPods#4843]
I have edge case in my application, i have included Project B which is also in Workspace B and is using CocoaPods in Workspace B, to by Workspace A which also is using Pods, i would like to override or just hide warnings about "[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set.". Project B have xcode configuration files from Workspace B an this is fine for me, but during pod install in Workspace A i am getting warnings about "[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set.".

**Comment by segiddins** [comment]
You can add the magic comment to your own xcconfig to suppress the warning.

**Comment by m1entus** [comment]
Magic comment? Can you tell more?

**Comment by segiddins** [comment]
I'm not at a computer now but it's in xcconfig_integrator.rb if you're curious.

**Comment by segiddins** [comment]
`// @COCOAPODS_SILENCE_WARNINGS@ //`

**Comment by m1entus** [comment]
Okay thanks, should i add this 

> // @COCOAPODS_SILENCE_WARNINGS@ // 

 to the end of xcconfig file ?

**Comment by segiddins** [comment]
Yes, if you want to silence the warning.
