### ISSUE TITLE
resource bundle files appear to get processed twice in the build process

### ISSUE THREAD

**Issue by CapnSpellcheck** [CocoaPods/CocoaPods#4849]
It sure seems like a lot of people would be complaining if resource bundles were this globally broken, but I'll report this anyway. Using just a simple resource_bundles config,

```
s.resource_bundles = {
    'Cadenza' => ['Pod/Assets/**/*']
  }
```

And a pretty simple structure in Assets
```
../Pod/Assets/
├── ApplicationUpgradeViewController.xib
├── CadenzaBindings.json
├── Images
├── Info.plist
├── LaunchViewController.xib
├── LivePlayerControls.xib
├── ModalErrorViewController.xib
├── PlayerViewController.xib
├── SlideshowSlideContentView.xib
├── Tiles
└── VODPlayerControls.xib
```
(Images and Tiles are directories which I suppressed with -L1)
This results in duplicate processing of the entire Assets tree. Reflection of this odd circumstance is inside the workspace, Xcode has two entries for "images" and "Tiles", one being a folder icon and one a group. This duplicate processing results in the .bundle containing the entire raw directory tree of Assets, unprocessed (i.e. xib's are .xibs) in addition to the 'processed' form.
![screen shot 2016-02-01 at 5 26 44 pm](https://cloud.githubusercontent.com/assets/512016/12736937/5b6bfb60-c909-11e5-8d01-c2ebaa15da29.png)

(Xcode 7.0-7.2)

**Comment by segiddins** [comment]
What CocoaPods version are you using?

**Comment by CapnSpellcheck** [comment]
0.39

**Comment by segiddins** [comment]
This ought to be fixed in the 1.0 betas and on master.

**Comment by CapnSpellcheck** [comment]
Is that the next release?

**Comment by segiddins** [comment]
Yes, it will be, if you want to verify the bug is indeed fixed that'd be a great help.

**Comment by CapnSpellcheck** [comment]
We hope to try this by end of week.

**Comment by segiddins** [comment]
Awesome, thanks!

**Comment by asharma-atx** [comment]
I was experiencing the same issue w/ 0.39. Upgrading to 1.0.beta.3 fixed the issue for me.
