### ISSUE TITLE
You are not allowed to push new versions for this pod.

### ISSUE THREAD

**Issue by MakeZL** [CocoaPods/CocoaPods#4850]
$ pod lib lint MLSelectPhoto.podspec --allow-warnings
result : 
MLSelectPhoto passed validation.

but $ pod trunk push MLSelectPhoto.podspec --allow-warnings
result : 
[!] You are not allowed to push new versions for this pod

Why? . Looking forward to your suggestions !

**Comment by segiddins** [comment]
Are you pushing with `zhangleowork@163.com` ?

**Comment by MakeZL** [comment]
@segiddins Thanks!! 
Originally registered mail is wrong.
