### ISSUE TITLE
1.0.0.beta.3 - Project targets that aren't referenced in Podfile have their configs removed

### ISSUE THREAD

**Issue by justinseanmartin** [CocoaPods/CocoaPods#4854]
🌈

We have our main xcodeproj in which we've manually integrated several library targets (that all have the same downstream dependencies) rather than having CocoaPods integrate each one individually (performance reasons). What we're seeing is that configurations are being recreated and removed from other project targets that aren't referenced directly in our Podfile.

I did some testing, and it appears that this only happens when the xcconfig file being referenced is a Pods generated one. As this isn't really a standard usage, we could probably copy the xcconfigs after integration completes and manually integrate the copies instead.

That being said, it seems like CocoaPods could ignore the config of any targets in a project that aren't referenced in the Podfile, even if they do point at a config within the Pods directory. Thoughts?

**Comment by justinseanmartin** [comment]
We're also looking into seeing how `abstract_target` would behave and if that would alleviate our problems.

**Comment by neonichu** [comment]
Sounds to me as if we should ignore targets referenced in the Podfile, but maybe I'm missing a reason why we don't.

**Comment by segiddins** [comment]
It's intentional that targets not referenced in the Podfile are de integrated. That's a major new 1.0 feature.

**Comment by justinseanmartin** [comment]
Yea, that seems reasonable as a desirable trait for a majority of the time. We'll find something that works for our edge case. Thanks for all the hard work!

**Comment by segiddins** [comment]
@justinseanmartin I'd recommend either writing a post-install hook or just `#include`ing the configs you want.

**Comment by justinseanmartin** [comment]
We just messed around with abstract targets and it seems to work pretty well! Increases pod install time by about 2x to around 90s unfortunately though. Using an include in the config seems like a great alternative, thanks.

**Comment by justinseanmartin** [comment]
Also, FYI, this isnt any slower than it used to be before we made the optimization to do manual integration.
