### ISSUE TITLE
pod version 1.0.0.beta.3 cannot use "pod update --no-integrate"

### ISSUE THREAD

**Issue by espgrandia** [CocoaPods/CocoaPods#4855]
I update the pod version to 1.0.0.beta.3.
Now I meet a problem. 
I cannot use command line "pod update  --no-integrate"
The error message like as "[!] Unknown option: `--no-integrate`"

The reference website as follow:
http://guides.cocoapods.org/using/faq.html

The command line has changed?

===========
Now I do some thing to solve it.
step1: pod update
step2: rename folder Pods to _Pods
step3: pod deintegrate
step4: rename folder _Pods to Pods

But this is not a good solution.

**Comment by segiddins** [comment]
You need to use `install! 'cocoapods', integrate_targets: false` in your podfile as of CocoaPods 1.0.

**Comment by espgrandia** [comment]
Thanks for your answer.
I try it, it's ok.

=========================
The sample content of Podfile as follow:
platform:ios, "7.0"

# pod version 1.0.xxx set no integrate .
install! 'cocoapods', integrate_targets: false

workspace 'WorkSpaceName'

xcodeproj 'ProjectName'

target 'TargetName'

pod 'AFNetworking', '~> 2.5.4'
pod 'CocoaLumberjack', '~> 1.9'
pod 'MIHCrypto', '~> 0.3.3'
pod 'SSKeychain' ,'~> 1.2.3'
pod 'JSONModel', '~>1.1.0'


=========================
terminal log as follow:

xxx$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.5.4)
Using CocoaLumberjack (1.9.2)
Using JSONModel (1.1.2)
Using MIHCrypto (0.3.3)
Using OpenSSL-Universal (1.0.1.16)
Using SSKeychain (1.2.3)
Generating Pods project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 6 total pods installed.
