### ISSUE TITLE
Expand Podspec DSL for better test support

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#4864]
Local development of a pod with test sources can be difficult and requires manual scaffolding to make it easy.

Take for example a case where you want to develop a pod locally under a larger context, but also be able to run its tests or add new tests. Today we have to manually include a new test bundle target and use a subspec in the podspec that brings in test sources.

As a side-note, using a subspec to bring in test sources prevents Xcode from displaying the diamonds on the left for executing the tests, because the sources are part of a static library target or framework instead of a test bundle target. The only way to run the tests is by having a wrapper test bundle target that allows to run all tests, instead of individual tests.

It feels that the podspec DSL could be expanded to support this case and create test bundle targets.

```ruby
Pod::Spec.new do |s|
  s.name         = "SamplePod"
  s.version      = "1.0.0"
  s.summary      = "SamplePod"
  s.homepage     = "http://www.google.com"
  s.license      = { :type => "Proprietary", :text => "LICENSE" }
  s.author       = { "ImaginaryAuthor" => "someone@imaginary.com" }
  s.source       = { :git => "git-repo.git", :tag => "1.0.0" }

  s.ios.deployment_target = "7.0"

  s.dependency 'PodA', '~> 1.0'
  s.source_files = 'Source/**/*.{h,hh,m,mm}'
  s.private_header_files = 'Source/**/Internal/**/*.{h,hh}'
  s.resource_bundle = ['Resources/**/*']

  # New DSL
  s.test.dependency 'TestPodA', '~> 1.0'
  s.test.framework = 'XCTest'
  s.test.source_files = 'Unit Tests/**/*.{h,hh,m,mm}'
  s.test.resource_bundle = ['TestResources/**/*']
end
```

Furthermore, there is no reason why for example `pod lib lint` or `pod spec lint` cannot infer that test sources are present and automatically generate, build and test the project. Would be very helpful for CI as well. It might be a bit challenging to pick which SDK or Simulator to use to run the tests but that can be configured possibly.

As far as local development is concerned, if a pod is locally consumed, CocoaPods could automatically create a test bundle target to allow the option to run the tests. The test bundle target could just inherit the search paths of the parent and link the `test_dependencies` and `test_frameworks`.

Another option would be to provide a flag at the Podfile level for local pods to add test sources, something like:

```ruby
pod 'SamplePod', :path => '/some/path/to/SamplePod.podspec', :include_test_targets => true
```

I don’t believe consuming a pod normally (i.e. not for local development) should ever “install” test sources and it should be safe to assume the publisher of the pod has properly tested it.

Depending more and more on the podspec to automate these things help remove the burden of having to workaround these limitations by creating xcode projects manually. We have over 150 internal pods, and each one of them includes a small xcodeproj with the test sources which is hard to manage, and does not help us with local development. I am not proposing this because of our internal situation, I believe this could be a great improvement in test support from CocoaPods in general.

The final piece could be to extend support for `pod lib` command add a new sub-command perhaps something like:

```
pod lib install
```
or

```
pod lib generate
```

This produces the `App.xcworkspace` (which `pod lib lint` and `pod spec lint` already do now since 1.0.0) along with `Pods/` and `Pods/Pods.xcodeproj` and immediately allows you to develop. 

This is meant to be a high-level brainstorm about extending test support for CocoaPods. I am sure there are a lot of little details to be taken into consideration. I'd like to hear the thoughts you have overall about providing better test support in CocoaPods!

Thanks for reading!

**Comment by segiddins** [comment]
There's already an issue open on Core for test subspecs which @kylef has worked on.

**Comment by kylef** [comment]
Yes, DSL change was done in PR https://github.com/CocoaPods/Core/pull/232

To get this moving, the next step would be to implement the test runner (https://github.com/CocoaPods/cocoapods-test/issues/1).

**Comment by dnkoutso** [comment]
Sounds good to me, I was not aware of the Core issue, otherwise I may have not filed this in :) Either way cocoapods-test sounds great and who knows maybe in my free time I can help push this through.

I like the idea of `s.test_spec` that can just be parsed like any other spec.

**Comment by segiddins** [comment]
Ok, let's continue discussion on the core issue then.

**Comment by robertjpayne** [comment]
Can we re-open this? Maybe it's just me but seems like CocoaPods/Core#232 is sorta dead and obsolete now?

Official support to allow spec's to define test bundles would be fantastic, it would help ensure you can run all 3rd party tests when doing CI too.

**Comment by benasher44** [comment]
I don't understand why it'd be a good idea to run the tests of your dependencies outside of the development pods scenario. This seems like the job of the dependency author as a task to run before publishing a new version. If you could clarify that, then that'd help.
