### ISSUE TITLE
cannot use 'project' in my podfile to specify :debug or :release configurations

### ISSUE THREAD

**Issue by skydivedan** [CocoaPods/CocoaPods#4866]
My project, named "SpecialProj" does not use the basic "Debug" and "Release" configurations. It uses "DEV", "QA" and "PROD".

But, DEV and QA are based off of the Debug config, and PROD is based off the Release config.

So, I stumbled on this page of the cocoapods docs:
https://guides.cocoapods.org/syntax/podfile.html#project

It describes in "Using Custom Build Configurations" how one might go about saying that certain configs are based off debug or release. The example given looks like this:

`project 'TestProject', 'Mac App Store' => :release, 'Test' => :debug`

So, I figured I could add this line to my Podfile:
`project 'SpecialProj', 'DEV' => :debug, 'QA' => :debug, 'PROD' => :release
`

However, when I run "pod install", I get this:
> Invalid `Podfile` file: undefined method `project' for #<Pod::Podfile:0x007fe02aa0c438>. Updating CocoaPods might fix the issue.

I'm using version 0.39.0 right now, and am using "use_frameworks!" The rest of the podfile is very simple, I'm just including a handful of dependencies. This is really important to me, so I can actually step through and debug, which is extremely hard to do right now.

**Comment by orta** [comment]
project is only available in 1.0.0, it's called `xcodeproj` in pre-1.0 versions: http://blog.cocoapods.org/CocoaPods-1.0/

**Comment by skydivedan** [comment]
a) Isn't it a bit premature to update the documentation before 1.0.0 gets out of beta?
b) Never having used the "xcodeproj" tag before, and seeing as the docs are totally blank, just saying that this can be deleted once we get to 1.0, how was I to know this?

I mean, thanks for the fast response on this, it's greatly appreciated. But I'd prefer that the docs only reflect the actual, non-beta, cocoapods to avoid problems like this is in the future. OR, have a separate link (somehow) to the "beta" documentation. 

Again, thanks for the help, though.

**Comment by orta** [comment]
I appreciate that, but we've not had the time to build versioned docs I'm afraid.

**Comment by skydivedan** [comment]
Is there a reason why the docs can't have a

> Deprecated in 1.0, replaced by "project"

Or something? Sorry, I'm not trying to have a big argument here, but it would be nice if the docs were a little more clear on this.

**Comment by orta** [comment]
Yeah, it definitely could :+1: - they're [generated from here](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/podfile/dsl.rb#L450)

**Comment by segiddins** [comment]
@skydivedan a PR making the docs clearer would be much appreciated :rocket:

**Comment by phillfarrugia** [comment]
How exactly are the cocoapods.org docs generated? It seems like all the information that is required already exists alongside the `@deprecated` prefix.

I'd love to submit a PR that allows `# @deprecated #{xcodeproj} was renamed to #{project}.` to be parsed into something meaningful in the documentation, just not exactly sure if that's something that can be done.

**Comment by orta** [comment]
We generate the documentation from the source code comments by  
* [running rubydoc against our gems](https://github.com/CocoaPods/guides.cocoapods.org/blob/master/lib/doc/) outputting yaml ( which are .gitignored )
* [Parsing that yaml file](https://github.com/CocoaPods/guides.cocoapods.org/blob/master/source/templates/dsl.html.slim) into html docs

This is pretty tough code to work in, the reason it's classed as a d:1 is cause the simplest option is to add it to the comments of `project` rather than try generate a sane list of deprecations

**Comment by orta** [comment]
Alright, this was done in CocoaPods/Core - thanks @phillfarrugia
