### ISSUE TITLE
the 'xcodeproj' argument doesn't respect SWIFT_OPTIMIZATION_LEVEL flags

### ISSUE THREAD

**Issue by skydivedan** [CocoaPods/CocoaPods#4867]
I'm having trouble using the "xcodeproj" (soon to be "project") argument in my Podfile.

I'm using the "xcodeproj" argument to describe which configurations should be treated as "debug" and which should be treated as "release" like this:

`xcodeproj 'SpecialProj', 'DEV' => :debug, 'QA' => :debug, 'PROD' => :release
`

While this flag does set the optimization levels correctly for Apple LLVM 7.0, it does not do something similar for the Swift compiler. Shouldn't it?

**Comment by segiddins** [comment]
It should be setting the same that Xcode 7.2 uses -- and those defaults come from https://github.com/CocoaPods/Xcodeproj, not CocoaPods.

**Comment by skydivedan** [comment]
ok, happy to take this over to that project, thanks.
