### ISSUE TITLE
Error pod trunk push --allow-warnings --verbose

### ISSUE THREAD

**Issue by MMizogaki** [CocoaPods/CocoaPods#4871]
omparing resolved specification to the sandbox manifest
  A RNNMBSwitch

Downloading dependencies

-> Installing RNNMBSwitch (1.0.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/MMizogaki/RNNMBSwitch.git /var/folders/4l/3v8g8tld5n77qkg_2ft6s83r0000gp/T/d20160208-28852-1qkmavp --single-branch --depth 1 --branch 1.0.0
     Cloning into '/var/folders/4l/3v8g8tld5n77qkg_2ft6s83r0000gp/T/d20160208-28852-1qkmavp'...
     warning: Could not find remote branch 1.0.0 to clone.
     fatal: Remote branch 1.0.0 not found in upstream origin

[!] Error installing RNNMBSwitch
 -> RNNMBSwitch (1.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/MMizogaki/RNNMBSwitch.git /var/folders/4l/3v8g8tld5n77qkg_2ft6s83r0000gp/T/d20160208-28852-1qkmavp --single-branch --depth 1 --branch 1.0.0

Cloning into '/var/folders/4l/3v8g8tld5n77qkg_2ft6s83r0000gp/T/d20160208-28852-1qkmavp'...
warning: Could not find remote branch 1.0.0 to clone.
fatal: Remote branch 1.0.0 not found in upstream origin
) during validation.

[!] The podspec does not validate.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:114:in `validate_podspec'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-0.6.4/lib/pod/command/trunk/push.rb:59:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by MMizogaki** [comment]
no branch 1.0.0 ???

**Comment by orta** [comment]
For others reading in the future, this was that @MMizogaki hadn't pushed the tag.

**Comment by MMizogaki** [comment]
@orta Thank !
