### ISSUE TITLE
Double quotes in project's name causes unbound variable exception upon sandbox-pod install

### ISSUE THREAD

**Issue by Mitko-Kerezov** [CocoaPods/CocoaPods#4874]
Simple repro:

``` BASH
$ mkdir a\"b
$ cd a\"b
$ echo pod 'IQKeyboardManager' > Podfile
$ sandbox-pod install
```

Fails with:
`sandbox-exec: line 73: unbound variable: b"`

Whereas executing `$ pod install` passes that phase.

The problem lies [here](https://github.com/CocoaPods/CocoaPods/blob/master/bin/sandbox-pod#L97) because `Pod::Config.instance.project_root` needs to be escaped in order for the regex to be properly constructed.

**Comment by orta** [comment]
Awesome, any chance you can send a PR fixing this? We've not put much dev effort behind `sandbox-pod` in the last 2 years.

**Comment by Mitko-Kerezov** [comment]
@orta my ruby skills are far from great.
Along with a colleague of mine we've tried to escape the quotation marks inside `Pod::Config.instance.project_root` with a custom written function and seen that it comes out as `\"` instead of just `"` but the exception was still thrown.... any ideas?

For reference, [this](http://pastebin.com/WpUgN21u) is the custom function we've used to escape all quotation marks inside `Pod::Config.instance.project_root.to_s`

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/issues/4875 should fix this

**Comment by segiddins** [comment]
... Unless someone wants to look up how to escape strings for `sandbox-exec`, this will be a wontfix

**Comment by segiddins** [comment]
I think we ought to close this. I never came up with a way to make this work, and I don't think demand is high enough to warrant the further work.
