### ISSUE TITLE
Can't install a new version of pod after previously deleting the last version with 'pod trunk delete'

### ISSUE THREAD

**Issue by silyevsk** [CocoaPods/CocoaPods#4876]
Yesterday I used 'pod trunk delete' to delete Rollout.io versions 0.14.0 and 0.14.1 (they were unstable and we roll back to 0.13). Today I've  deployed 0.14.2, but for some reason it can't be installed, neither buy specifying the version with "pod 'Rollout.io', '0.14.2'", nor with "pod 'Rollout.io'".

'pod install' results in the following error:
[!] Error installing Rollout.io
[!] /usr/bin/git clone .git /var/folders/b8/vxrsrks16p71v95z1t6wxj9r0000gn/T/d20160208-47829-1titofr --single-branch --depth 1 --branch 0.14.2

fatal: repository '.git' does not exist

**Comment by segiddins** [comment]
https://github.com/CocoaPods/Specs/blob/master/Specs/Rollout.io/0.14.2/Rollout.io.podspec.json#L25 it appears you specified the wrong source in your podspec.

**Comment by silyevsk** [comment]
oh :(
Thank you!
