### ISSUE TITLE
Problem archiving app with use_frameworks! when I use the same framework on both of app and today widget.

### ISSUE THREAD

**Issue by Ying1986** [CocoaPods/CocoaPods#4879]
cocoa pod: 0.39
Xcode 7.2.1:
I can't build iPA when I use the same framework on both of app and today widget.

Please check the followings:

![podsetting](https://cloud.githubusercontent.com/assets/6648212/12910468/a1be6a48-cf13-11e5-9e39-4598dbabc028.png)
![bitcode-compile](https://cloud.githubusercontent.com/assets/6648212/12910464/a0c12ae0-cf13-11e5-9848-999c645c7b61.png)
![ipaerror-1](https://cloud.githubusercontent.com/assets/6648212/12910466/a1b94f04-cf13-11e5-9930-b5394c5f8731.png)
![ipaerror-2](https://cloud.githubusercontent.com/assets/6648212/12910467/a1bb71da-cf13-11e5-9e80-10e207dd67df.png)

**Comment by segiddins** [comment]
Can you try again using CocoaPods 1.0.0.beta.4?
