### ISSUE TITLE
How to add Pod headers to test target

### ISSUE THREAD

**Issue by aliHafizji** [CocoaPods/CocoaPods#488]
I'm using the SenTesting framework to run tests. 
Here is my pod file, 

platform:ios
pod 'MKNetworkKit', '~>0.85'

What changes to I need to do to include the header in the testing framework. 
I tried adding the dependencies to the test target in the podfile but I get the following error

ld: duplicate symbol _OBJC_CLASS_$_MKNetworkEngine.....
...clang: error: linker command failed with exit code 1 (use -v to see invocation)

Anyone face this issue. Any solutions?

**Comment by andhieka** [comment]
@arashkashi I had the same problem. But @besi 's solution works very well for me! Very convenient.
