### ISSUE TITLE
Podspec arc/no-arc "pod lib lint" compiler error

### ISSUE THREAD

**Issue by klusinyan** [CocoaPods/CocoaPods#4881]
Hi all, I have one question about arc/no-arc podspec definitions. Currently I am trying to push MyLib to private git repository. The problem is similar defined in issue #892 with a difference that my whole project is written in NON ARC. So together with non-arc files I have a few files written in ARC. 
There is no way to pass "pod lib lint" command. It gives me an error saying that the header declared in NON ARC are not visibile inside of ARC files. This is an example of my podspec which I am trying to push:

```
   #project is "no-arc"
   s.requires_arc = false

    #declaring arc_files
    arc_files = 'MyLib/Classes/Slider/**/*.{h,m}'
   
   #adding source files 
   s.source_files = 'MyLib/Classes/**/*.{h,m}'
    s.exclude_files = arc_files

    #adding "arc" to pod
    s.subspec 'arc' do |ss|
        ss.requires_arc = true
        ss.source_files = arc_files
    end
```
  
Thanks in advance.

**Comment by segiddins** [comment]
Yes, that's to be expected.

**Comment by klusinyan** [comment]
Hi, thank you for your quick response. 
So, how can I resolve this issue? which will be the correct implementation?

**Comment by segiddins** [comment]
You'll need to wrangle the subspecs a bit, but this is the sort of question best answered on SO -- its not an issue in CocoaPods per-se.

**Comment by klusinyan** [comment]
Ok. Thanks
