### ISSUE TITLE
include of non-modular header inside framework module

### ISSUE THREAD

**Issue by bonebox** [CocoaPods/CocoaPods#4884]
I'm seeing this error on lint after upgrading from CocoaPods  `0.39.0` to `1.0.0.beta.3`. This is a Swift framework that is including another Swift framework as a dependency, and the included framework has OnePasswordExtension as a dependency in its podspec, which is in Objective-C.  Reverting to `0.39.0` fixes the problem.  This is with Xcode 7.2.1.

```   
 - NOTE  | xcodebuild:  <module-includes>:1:9: note: in file included from <module-includes>:1:
 - ERROR | xcodebuild:  Target Support Files/1PasswordExtension/1PasswordExtension-umbrella.h:3:9: error: include of non-modular header inside framework module 'OnePasswordExtension'
```

**Comment by segiddins** [comment]
You'll need to share a project with us -- this is insufficient information to debug.

**Comment by bonebox** [comment]
Theoretically it can be reproduced by creating a Swift framework/podspec with OnePasswordExtension (or possibly any other Objective-C library) as a dependency, then a 2nd Swift framework that includes the first as a dependency.  I unfortunately can't share the projects where I'm experiencing this issue, but will throw the above together when I get a chance.

**Comment by radazzouz** [comment]
Hi there,

My name is Rad and I am the lead developer and maintainer of the [1Password App Extension API](https://github.com/AgileBits/onepassword-app-extension). We have seen [reports](https://github.com/AgileBits/onepassword-app-extension/issues/289) about this issue from our users who are using the 1.0.0 CocoaPods betas. 

So far I've been able to find consistent steps to reproduce this issue. It involves having CocoaPods 1.0.0 beta 3, `use_frameworks!` in the Podfile and a Swift Project.

#### Here are the steps to reproduce:

* Make sure that you are using CocoaPods 1.0.0 beta 3.
* Download the [`ACME Swift CocoaPods use_frameworks!` sample project](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20Swift%20CocoaPods%20use_frameworks!.zip).
* `cd` to `ACME Swift CocoaPods use_frameworks!` and run `pod install`.
* Open the newly created workspace (`App Demo for iOS Swift.xcworkspace`) in Xcode (7.2.1 stable from the Mac App Store)
* Build and run.

#### Expected:

The app should build and run. No compile errors are expected. Following the exact same steps to reproduce while CocoaPods 0.39.0 stable is installed will result in a successful build.

#### Actual:

We get the following build errors: `Include of non-modular header inside framework module 'OnePasswordExtension'`

![](http://cl.ly/2v3e240O391z/Image%202016-02-10%20at%201.08.06%20PM.png)

Please do let me know if this helps :smiley:

All the Best,

**Comment by segiddins** [comment]
Question, does `pod spec lint` pass with the 1.0 beta?

**Comment by radazzouz** [comment]
Hi @segiddins,

Thanks for the prompt response :+1: 

No, it does not pass with `1.0.0 beta 3` and here's the result:

![](http://cl.ly/1v1W2Q16333C/Image%202016-02-10%20at%206.09.46%20PM.png)

Please note that I does pass with `0.39.0`

![](http://cl.ly/0s2Q2Q2y342V/download/Image%202016-02-10%20at%206.16.46%20PM.png)

Please let me know if there's anything we can do on our end to address this issue.

I look forward to your reply :wink: 

Cheers!

**Comment by segiddins** [comment]
If it doesn't pass lint with the beta, then it not working with the beta is expected. I'd recommend trying to get it to lint on the beta.

**Comment by bonebox** [comment]
Not sure what you're asking.  How do we get the beta to lint successfully when it is the source of the failure?  Are you asking to investigate what the beta is doing differently with project setup than in 0.39.0?

**Comment by segiddins** [comment]
Fix the errors the beta is reporting to you when linting, then if you're still having issues we can investigate.

**Comment by bonebox** [comment]
I guess I don't understand how manually fixing the issue would help since it would just be reintroduced by CocoaPods the next time you do a `pod install` / `pod update`.

**Comment by radazzouz** [comment]
Thanks for the feedback @segiddins!

I am not sure I fully understand how to address this errors reported by `lint` when using the beta.

I tested the same [project](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20Swift%20CocoaPods%20use_frameworks!.zip), pointing to the same branch (`master`), using the same `Podfile`, using both the stable and beta versions of CocoaPods and I got different results.

The 1Password App Extension API](https://github.com/AgileBits/onepassword-app-extension) does not use any modules. It simply provides the source code (`OnePasswordExtension.h` and `OnePasswordExtension.m`) and an `xcasset`.

Thank you!

**Comment by orta** [comment]
I've got the podspec to lint locally on 1.0.0b3  by removing:

``` diff
-  spec.header_dir 			= "OnePasswordExtension"
-  spec.header_mappings_dir 	= "OnePasswordExtension"
```

From the podspec, as they refer to folder that don't exist in your repo. 👍🏾 

``` sh
~/d/i/l/onepassword-app-extension (master) ⏛  git diff
diff --git a/1PasswordExtension.podspec b/1PasswordExtension.podspec
index efecde1..8e4c998 100644
--- a/1PasswordExtension.podspec
+++ b/1PasswordExtension.podspec
@@ -1,8 +1,6 @@
 Pod::Spec.new do |spec|

   spec.name                            = "1PasswordExtension"
-  spec.header_dir                      = "OnePasswordExtension"
-  spec.header_mappings_dir     = "OnePasswordExtension"
   spec.version                                 = "1.7"
   spec.summary                                 = "With just a few lines of code, your app can add 1Password support."
   spec.description                     = <<-DESC

~/d/i/l/onepassword-app-extension (master) ⏛  pod _1.0.0.beta.2_ spec lint

 -> 1PasswordExtension (1.7)

Analyzed 1 podspec.

1PasswordExtension.podspec passed validation.
```

Do you know why they were there?

**Comment by radazzouz** [comment]
Hi @orta

Thanks so much for the amazing find :+1:

We added `header_dir` and `header_mappings_dir` to our `podspec` for `use_framework!` compatibility with CocoaPods 0.36.x (See issue [180](https://github.com/AgileBits/onepassword-app-extension/issues/180) and PR [182](https://github.com/AgileBits/onepassword-app-extension/pull/182)). If I remember correctly, one of the main reasons why we did this was to have the generated framework named `OnePasswordExtension` instead of `_1PasswordExtension`.

Anyway, here's what I did to test:

* I followed your recommendation and removed in the two attributes from our podspec in this [branch](https://github.com/AgileBits/onepassword-app-extension/tree/improvement/improved-compatibility-with-cocoapods-1.0.0) and updated our podspec file as follows:

```
platform :ios, '7.0'

use_frameworks!

pod '1PasswordExtension', :git => 'https://github.com/AgileBits/onepassword-app-extension.git', :branch => 'improvement/improved-compatibility-with-cocoapods-1.0.0'

target 'ACME Swift' do

end
```

* Used both CocoaPods 0.39.0 and 1.0.0 beta 3

### Results

* `pod spec lint` is successful
* Used the Swift project mentioned in my previous comments and ran `pod install` - Success. Note that I had the replace all occurences of `import OnePasswordExtension` with `import _1PasswordExtension` in the code.
* Ran `pod install` using this [Objective-C sample project](https://com-agilebits-users.s3.amazonaws.com/rad/ACME%20CocoaPods%20use_frameworks!.zip), which also uses `use_frameworks!` and all is working as expected.

### Questions

* Is it safe to remove the `header_dir` and `header_mappings_dir` attributes from our podspec moving forward?
* Other than the generated framework being named `_1PasswordExtension`, are there any other know side effects or issues?

Once again, thank you so much for the assist, @orta!

@bonebox, could you please try and update your podfile as seen above, so that it points to the new branch rather than to master or the latest tag and confirm that it works for you?

Cheers everyone!

**Comment by segiddins** [comment]
You can specify the `module_name` directly in the podspec.

**Comment by radazzouz** [comment]
@segiddins, you mean re-add the deleted attributes and add `module_name` or simply add `module_name`?

**Comment by orta** [comment]
He means `spec.module_name = "1PasswordExtension"` - which wasn't deleted, I think ( ah was added here https://github.com/AgileBits/onepassword-app-extension/commit/1489f41115eeb9e381ac652fa656aceb9f3d515b ) which is what controls the name of the framework. I'm surprised that you get `_1PasswordExtension` though FWIW, maybe I don't understand the clang module naming rules.

You should be safe WRT the `header_dir` / `header_mappints_dir` though.

**Comment by radazzouz** [comment]
Thanks so much @orta and @segiddins :+1: 

I just tried all combinations of the three attributes (`module_name`, `header_dir` and `header_mappings_dir`). I used `pod spec lint` as well as tested it with the sample apps and adding `spec.module_name = "OnePasswordExtension"` seems to do the trick. Note that having `header_dir` and `header_mappings_dir` in the podspec still cause the initial problem.

@orta it seems that clang doesn't like module names that start with a numeral character.

![](https://www.evernote.com/l/AVTLrSBsWndM5qAoK3xI9Zi6Bu0A8tDm0BgB/image.png)

Thanks so much for the help!

**Comment by bonebox** [comment]
Thanks everyone for helping resolve this.

@radazzouz it builds locally when pointing the Podfile to your new branch, but since I'm including it in my own framework/podspec, I'll still need an updated podspec for 1PasswordExtension on the CocoaPods master repo.  I'll keep an eye out for it.

**Comment by radazzouz** [comment]
Thanks @bonebox! 

I will merge https://github.com/AgileBits/onepassword-app-extension/pull/302 to master as soon I get more confirmations that it fixes this issue for others.

Let's chat on https://github.com/AgileBits/onepassword-app-extension/issues/289 if you require any assistance.

Cheers!

**Comment by orta** [comment]
BTW @radazzouz doing `spec.module_name = "OnePasswordExtension"` may mean that the podspec is not end-user source code backwards compatible, anyone using Swift of `@import` in objective-c would have to change their references

**Comment by radazzouz** [comment]
Good thinking @orta :+1: 

Previously, before my proposed change, we had `spec.header_dir = "OnePasswordExtension"` and `spec.header_mappings_dir = "OnePasswordExtension"` which resulted in a `OnePasswordExtension.framework` generated by `use_framework!`. My proposed change will still generated a `OnePasswordExtension.framework`.

My thinking is that current users already have `@import OnePasswordExtension` in their source code. Therefore, no errors should be expected. Am I missing something?

Thanks so much!

**Comment by segiddins** [comment]
Nope, that reasoning sounds right to me

**Comment by radazzouz** [comment]
:+1:

**Comment by jlott1** [comment]
I've got a question.  If I'm using someone else's cocoa pod and I'm seeing this issue, what should I do?  Wait for them to update their cocoa pod?   Fork their cocoa pod and try to fix it myself?   Downgrade to older CocoaPods version?   I have no clue why this is a problem or what is the root cause for this error?

**Comment by cchestnut91** [comment]
☝️

**Comment by benasher44** [comment]
@jlott1 @cchestnut91 if you all have repro steps, then we would appreciate a new Github issue. Thanks!
