### ISSUE TITLE
Problems with modules/headers after update

### ISSUE THREAD

**Issue by tomaszwojcik** [CocoaPods/CocoaPods#4885]
Recently I've updated XCode to `7.2.1` and CocoaPods to `1.0.0.beta.3`. The project is for iOS 8+, mostly in Swift with very few lines in Obj-C/C.

However after this change my includes/imports in the source and bridging header cannot be resolved (`Module <some file> not found` or `<some file> file not found`).

I get those errors for pods such like Google Analytics, FBSDKCoreKit or StreamingKit (from Github).
I've been trying different solutions from [this post](http://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files) with no success.

Moreover `$(inherited)` looks like an empty string in the header search paths.

Here's my Podfile. It worked like a charm before update :/

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

# Uncomment for getting rid of warning from all pods
inhibit_all_warnings!

pod 'Alamofire', '~> 3.0'
pod 'SWRevealViewController', '~> 2.3'
pod 'StreamingKit', git: 'git@github.com:tomaszwojcik/StreamingKit.git'
pod 'Google/Analytics', '~> 1.0.0'
pod 'SDWebImage', '~> 3.7'

pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

target '<ProjectNameTests>' do
  pod 'Quick', git: 'git@github.com:Quick/Quick.git'
  pod 'Nimble', git: 'git@github.com:Quick/Nimble.git'
end
```

**Comment by segiddins** [comment]
That podfile doesn't specify your app target at all, are you sure thats not the issue?

**Comment by tomaszwojcik** [comment]
Hmm that helped a bit, got rid of 5 out of 6 errors.

However there's still an issue with `#import <Google/Analytics.h>` in the bridging header (`'Google/Analytics.h' file not found`).

Now Podfile looks like this:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target '<ProjectName>' do
  pod 'Alamofire', '~> 3.0'
  pod 'SWRevealViewController', '~> 2.3'
  pod 'StreamingKit', git: 'git@github.com:tomaszwojcik/StreamingKit.git'

  pod 'SDWebImage', '~> 3.7'

  pod 'FBSDKCoreKit', '~> 4.10'
  pod 'FBSDKShareKit', '~> 4.10'
  pod 'FBSDKLoginKit', '~> 4.10'

  pod 'Google/Analytics'
end

target '<ProjectNameTests>' do
  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '3.0.0'
end
```

**Comment by orta** [comment]
Couldn't it be imported directly from Swift into your app, rather than through the bridging header?

**Comment by tomaszwojcik** [comment]
That solved the issue with bridging header, but then tests failed (`No such module Google` or something like that).

However i've changed my Podfile a bit and was finally able to build and run the project after updates:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

def project_pods
  pod 'Alamofire', '~> 3.0'
  pod 'SWRevealViewController', '~> 2.3'
  pod 'StreamingKit', git: 'git@github.com:tomaszwojcik/StreamingKit.git'

  pod 'SDWebImage', '~> 3.7'

  pod 'FBSDKCoreKit', '~> 4.10'
  pod 'FBSDKShareKit', '~> 4.10'
  pod 'FBSDKLoginKit', '~> 4.10'

  pod 'Google/Analytics'
end

def test_pods
  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '3.0.0'
end

target '<ProjectName>' do
  project_pods
end

target '<ProjectNameTests>' do
  project_pods
  test_pods
end
```

I have mixed feelings about including `project_pods` in the tests target.
However if this is the proper solution we can close this thread.

Thanks @orta and @segiddins for help!

**Comment by orta** [comment]
You want to structure your Podfile like this:

```
use_frameworks!
inhibit_all_warnings!

target 'ORStackView_Example' do
  pod "ORStackView", :path => "../"

  target 'ORStackView_Tests' do
    inherit! :search_paths

    pod 'Quick'
  end
end
```

then there's no duplication - which will fix that, see http://blog.cocoapods.org/CocoaPods-1.0/ for full info!
