### ISSUE TITLE
Please don't require certain Podspec fields when using a local podspec

### ISSUE THREAD

**Issue by jcanizales** [CocoaPods/CocoaPods#4886]
Before v1, you could use podspec files without `authors`, `homepage`, `source` and `summary` (and maybe `license`?), as long as you were just referring to them locally (e.g. the wouldn't pass `pod lint` so the main Cocoapods repo is safe from them).

Now `pod install` errors out with those podspec files, requiring to go ahead and add dummy values for those fields, for no useful purpose.

**Comment by segiddins** [comment]
Sorry, I don't think we're going to do this -- just add dummy values for those fields. In the long run, it'll prove to be a useful resource to people using the pod.

**Comment by jcanizales** [comment]
Some use cases for these podfiles doesn't involve them ever being uploaded to a repo, just checked in alongside source files. Like you would do with a `Makefile`. In that case, `authors`, `summary`, and `license` aren't useful, and `homepage` and `source` might not even make sense.

**Comment by segiddins** [comment]
It's just a complication to handle the separately, and one that I don't look forward to maintaining years into the future.

**Comment by neonichu** [comment]
Could we lint treat them as private specs? IIRC, a few attributes aren't mandatory in that case, right?

**Comment by segiddins** [comment]
@neonichu we already do, but that only effects warnings.

**Comment by neonichu** [comment]
OK, I agree we shouldn't do more than that, as having a local podspec that is never published in any form is quite an edge case.

**Comment by jcanizales** [comment]
I think that's fair; thanks for the explanation!
