### ISSUE TITLE
Pod install duplicates existing local specs repo

### ISSUE THREAD

**Issue by diogoguimaraes** [CocoaPods/CocoaPods#4893]
I'm using Cocoapods `0.39.0` and performing the following steps to create a repo and add my Pod:
* Create and initialise my local git repository `Specs.git` through `git init --bare`
* Add my repository to local repos using `pod repo add PrivateSpecs ~/.cocoapods/private-repos/Specs.git` 
* Creating my podspec `Foobar.podspec.json`and pushing it to the repo through `pod repo push PrivateSpecs Foobar.podspec.json`

All goes well and I have the repository created with the following folder structure: `~/.cocoapods/repos/PrivateSpecs/Foobar/0.0.1/Foobar.podspec.json`

The issue happens when I perform `pod install --verbose`, CocoaPods is creating a new local repository `users-diogoguimaraes-.cocoapods-private-repos-specs`with the exact same contents of `PrivateSpecs`. It doesn't throw any errors but now I have duplicated repositories.

Do you have any idea of why is this happening?
Thank you.

**Comment by segiddins** [comment]
Whats the contents of your `Podfile`?

**Comment by diogoguimaraes** [comment]
My Podfile has the following structure:
```
source 'file:///Users/diogoguimaraes/.cocoapods/private-repos/Specs.git'

platform :ios, '9.0'
use_frameworks!

pod 'Foobar'
```

**Comment by segiddins** [comment]
In that case, cloning the repo to `.cocoapods/repos` is the expected behavior.
