### ISSUE TITLE
求教这个如何处理https://github.com/CocoaPods/search?q=undefined+method %60to_ary%27+for+%23%3CPod%3A%3ASpecification+name 

### ISSUE THREAD

**Issue by JackBatman** [CocoaPods/CocoaPods#4896]
https://github.com/CocoaPods/search?q=undefined+method %60to_ary%27+for+%23%3CPod%3A%3ASpecification+name

**Comment by JackBatman** [comment]
https://github.com/CocoaPods/search?q=undefined+method %60to_ary%27+for+%23%3CPod%3A%3ASpecification+name

**Comment by segiddins** [comment]
This isn't a helpful bug report -- please include all the information requested in https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md.

**Comment by JackBatman** [comment]
![cocoapodsbug](https://cloud.githubusercontent.com/assets/17262957/13066296/7b2f679c-d49f-11e5-911e-a97a4aa1a03a.jpg)

**Comment by segiddins** [comment]
That issue has been opened several times, and has been fixed in the 1.0 betas. Either upgrade to the beta or use a ruby version prior to 2.3.
