### ISSUE TITLE
subspec not added to local pod file

### ISSUE THREAD

**Issue by dbworku** [CocoaPods/CocoaPods#4898]
I'm working to migrate an iOS project with local podspec files to subspecs(facebook/componentkit#483). Previously, the files were referenced using some nested local podspecs and `linked_with` in the `Podfile`. 

Now, the build broke and the headers of the nested libraries can no longer be referenced. Which step am I missing?

My approach:
- Podspec was updated with subspecs from the content of the local podspecs
- The `subspec` was added to the target in the `Podfile`

The podspec and Podfile of my specific project state can be found on [this branch](https://github.com/dbworku/componentkit/tree/Subspec-ComponentSnapshotTestCase).

**Comment by neonichu** [comment]
As far as I can see, the dependencies you have set up don't match the actual required dependencies, e.g. "ComponentKitTests" imports headers from "ComponentKitTestHelpers" without actually depending on that subspec.

**Comment by dbworku** [comment]
@neonichu Yes, missing the subspec in the "ComponentKitTest" target is incorrect. However, that is not my core issue because the error remains after changing that target too: 
```
target 'ComponentKitTests' do
	pod 'OCMock', '~> 2.2'
	pod 'ComponentKit/ComponentKitTestHelpers', :path => '.'
	pod 'ComponentKit/ComponentKitTestLib', :path => '.'
end
```

Another better example: The `ComponentSnapshotTestCase/CKComponentSnapshotTestCase.h` file cannot be imported in the "ComponentTextKitApplicationTests" or "ComponentKitApplicationTests" targets. Both of these targets depend on the subspec.

**Comment by neonichu** [comment]
Right, the other issue is that subspecs are for selecting parts of a library, so the headers for the "ComponentKit/ComponentKitTestHelpers" subspec will be available as "ComponentKit/*" and not as "ComponentKitTestHelpers/*" as you are expecting it.

**Comment by dbworku** [comment]
@neonichu Ahh. That was my core misunderstanding. Thank you!
