### ISSUE TITLE
We cannot search our library in cocapods website

### ISSUE THREAD

**Issue by JulienLacr0ix** [CocoaPods/CocoaPods#4899]
Hello!

We have push yesterday (15 February 2016) a new library named MFCore (2.2.0-RC1)

But we cannot find it on your website. And if we launch `pod trunk push MFCore.podspec --allow-warnings`

**[!] Unable to accept duplicate entry for MFCore (2.2.0-RC1)**

Do you have a filter for RC versioning ? Or can you analyse this issue on your system ?

Thx for your replies

Best regards,
Julien.

**Comment by orta** [comment]
I wonder if our resolver is failing on the website, the pod is pushed: https://github.com/CocoaPods/Specs/tree/master/Specs/MFCore

**Comment by neonichu** [comment]
I think since CocoaPods/search.cocoapods.org@e7c6c4337c3601c9f731af72d8a99214a395bc84 we don't include RCs in search anymore.

**Comment by orta** [comment]
Yeah, but I thought there was a fallback if all the versions were beta/RCs

**Comment by neonichu** [comment]
Judging from the code it doesn't look like there is one to me.

**Comment by orta** [comment]
Yep - http://blog.cocoapods.org/Release-Versions-Only/ this is as expected, @JulienLacr0ix - this is a closed as working as expected, we don't show pre-release only versions on CP.org

**Comment by JulienLacr0ix** [comment]
Ok ! Thx for your quick replies !! 

Have a nice day !
