### ISSUE TITLE
Umbrella header is generated even though one is provided

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#4903]
About an hour ago, CocoaPods 0.39.0 started generating an additional umbrella header for CocoaAsyncSocket despite the inclusion of `CocoaAsyncSocket.h` in the podspec. The generated umbrella header includes our existing umbrella header, which breaks all sorts of things like non-modular includes, and duplicate definitions.

You can fix the issue by manually deleting the repo's own umbrella header and removing its reference from CocoaPods generated umbrella header. However, I was under the impression that CocoaPods wouldn't generate an umbrella header if it found a pre-existing one.

If this is the intended behavior, it's no big deal, I'll just go modify the podspec to ignore the included umbrella header. What's really baking my noodle is that I have no idea why this behavior seemed to change spontaneously in the last hour or so.

You can see this behavior in the following repo: https://github.com/chrisballinger/ProxyKit/tree/master/Tests/iOS

Failing Travis build output here: https://travis-ci.org/chrisballinger/ProxyKit/builds/109712462

And the podspec which seems to be now confusing the umbrella generator: https://github.com/robbiehanson/CocoaAsyncSocket/blob/master/CocoaAsyncSocket.podspec#L27

**Comment by chrisballinger** [comment]
What's even more mind-boggling is that this seems to work *sometimes*. Here's the same podspec and code (as a development pod) integrated as a framework into the test target:

* https://travis-ci.org/robbiehanson/CocoaAsyncSocket#L299

**Comment by segiddins** [comment]
It is the intended behavior unless you've specified a custom module map. Does it work with the 1.0 beta?

**Comment by chrisballinger** [comment]
Ah ok, thanks! I've fixed the podspec to ignore the extra header. 

Not sure about the 1.0 beta, but I've been avoiding it because the deprecation of `link_with` breaks my builds and moving to `target` doesn't seem to fix it. I guess I should probably report that separately at some point.
