### ISSUE TITLE
Error loading the plugin with path `/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/cocoapods-keys-1.6.0/lib/cocoapods_plugin.rb`.

### ISSUE THREAD

**Issue by bblanco1** [CocoaPods/CocoaPods#4905]
This was the issue that was occurring for me when I was trying to run pod install.
I tried some of these options 
* Reinstalled the bundler
* Reinstalled CocoaPods gem
* Reinstalled CocoaPods-Key gem
* Updated RVM 

Now the errors went away by themselves today but yesterday this is what was going on.

		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:45:20: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                   strlen(service), service,
		                   ^~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:46:31: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                   username ? strlen(username) : 0, username,
		                              ^~~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:51:22: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                     strlen(service), service,
		                     ^~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:53:33: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                     username ? strlen(username) : 0, username,
		                                ^~~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:90:20: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                   strlen(service), service,
		                   ^~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:91:43: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                   username == NULL ? 0 : strlen(username), username,
		                                          ^~~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:97:24: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                       strlen(password), password);
		                       ^~~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:102:24: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                       strlen(service), service,
		                       ^~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:103:47: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                       username == NULL ? 0 : strlen(username), username,
		                                              ^~~~~~~~~~~~~~~~
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:104:24: error:
		      implicit conversion loses integer precision: 'unsigned long' to 'UInt32'
		      (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
		                       strlen(password), password,
		                       ^~~~~~~~~~~~~~~~
		10 errors generated.
		
		---------------------------------------------
		Error loading the plugin with path `/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/cocoapods-keys-1.6.0/lib/cocoapods_plugin.rb`.
		
		CompilationError - error executing "gcc -dynamic -bundle  -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -fno-common  -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Werror=pointer-arith -Werror=write-strings -Werror=declaration-after-statement -Werror=shorten-64-to-32 -Werror=implicit-function-declaration -Werror=division-by-zero -Werror=deprecated-declarations -Werror=extra-tokens  -fno-common -pipe -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -I /Users/bblanco/.rvm/rubies/ruby-2.3.0-preview2/include/ruby-2.3.0 -I /Users/bblanco/.rvm/rubies/ruby-2.3.0-preview2/include/ruby-2.3.0/x86_64-darwin15 -I /Users/bblanco/.rvm/rubies/ruby-2.3.0-preview2/include -L/Users/bblanco/.rvm/rubies/ruby-2.3.0-preview2/lib -o \"/Users/bblanco/.ruby_inline/ruby-2.3.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.bundle\" \"/Users/bblanco/.ruby_inline/ruby-2.3.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.c\" -lc -framework Security -framework CoreFoundation -framework CoreServices ": pid 84237 exit 1
		Renamed /Users/bblanco/.ruby_inline/ruby-2.3.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.c to /Users/bblanco/.ruby_inline/ruby-2.3.0/Inline_OSXKeychain_5b2f8d1cd1bde9c4ff3fea49f09cd5c1.c.bad
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/RubyInline-3.12.4/lib/inline.rb:618:in `build'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/RubyInline-3.12.4/lib/inline.rb:856:in `inline'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:17:in `<class:OSXKeychain>'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/osx_keychain-1.0.1/lib/osx_keychain.rb:6:in `<top (required)>'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/cocoapods-keys-1.6.0/lib/keyring.rb:1:in `require'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/cocoapods-keys-1.6.0/lib/keyring.rb:1:in `<top (required)>'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/cocoapods-keys-1.6.0/lib/cocoapods_plugin.rb:1:in `require'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/gems/cocoapods-keys-1.6.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `require'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
		/Users/bblanco/.rvm/rubies/ruby-2.3.0-preview2/bin/pod:23:in `load'
		/Users/bblanco/.rvm/rubies/ruby-2.3.0-preview2/bin/pod:23:in `<main>'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/bin/ruby_executable_hooks:15:in `eval'
		/Users/bblanco/.rvm/gems/ruby-2.3.0-preview2/bin/ruby_executable_hooks:15:in `<main>'
		---------------------------------------------
		
		[!] Your Podfile requires that the plugin `cocoapods-keys` be installed. Please install it and try installation again.

**Comment by segiddins** [comment]
This looks like an issue with the OS X-keychain gem rather than CocoaPods.
