### ISSUE TITLE
`bundle exec pod install` via boxen fails to find credentials

### ISSUE THREAD

**Issue by notjosh** [CocoaPods/CocoaPods#4912]
Hi!

1) I'm using `cocoapods (0.39.0)`
1) My system setup uses [boxen](https://github.com/boxen/our-boxen), which has a [credential manager](https://github.com/boxen/our-boxen/blob/master/script/boxen-git-credential)
1) Our project has a private podspec repo (hosted on github.com), which the `Podfile` refers to as a source (so, requires auth via `boxen-git-credential`)

`pod install` works completely fine, but `bundle exec pod install` fails with:

```
$ bundle exec pod install --verbose
  Preparing

Updating local specs repositories

Updating spec repo `biowink`
  $ /opt/boxen/homebrew/bin/git pull --ff-only
  /opt/boxen/bin/boxen-git-credential:29:in `require': cannot load such file -- boxen/config (LoadError)
  	from /opt/boxen/bin/boxen-git-credential:29:in `<main>'
Username for 'https://github.com':
```

There's a ~fix~ for this, but I don't know the greater impacts, so I won't send a PR just yet. But basically, in `executable.rb` you can wrap shell calls in `Bundler.with_clean_env { ... }` and it :sparkles:works:sparkles: just fine. That seems to be the recommended approach according to https://github.com/boxen/our-boxen/issues/25, and there's a precedent in Octopress at https://github.com/imathis/octopress/commit/00d15913220b25ebe55c581d557069d6833cf44b.

BUT, after that, running `pod install` directly (without `bundle exec`) causes ~problems~ (`NameError - uninitialized constant Pod::Executable::Bundler`) and I don't know the best way to work around that. Check for bundler gem, check for bundler ENV, and wrap calls if it looks like we're in a bundler env? Maybe there's a better way :)

I'm happy to fire off a PR, just need some advice.

Thoughts?

**Comment by notjosh** [comment]
Looking a little closer, we can probably get away with something pretty daft/simple:

```ruby
if defined?(Bundler)
  Bundler.with_clean_env { ... }
else
  ...
end
```

**Comment by segiddins** [comment]
Sounds like you need to put `boxen-git-credential` in your gemfile?

**Comment by notjosh** [comment]
Sort of. `boxen-git-credential` isn't a gem, it's a helper script (see: https://github.com/boxen/our-boxen/blob/master/script/boxen-git-credential).

The closest to that would be `gem 'boxen'` (as described in https://github.com/boxen/our-boxen/issues/25#issuecomment-13420766) but it's unnecessary (as described later in that thread) by executing with `Bundler.with_clean_env`.

**Comment by segiddins** [comment]
But the issue with that is users might _want_ their ewxecutables to be found using the gems in their gemfile.

**Comment by notjosh** [comment]
Ah, that's a good point. Would it make sense to wrap the calls to `git`/`git!` then? It seems a pretty fair assumption that you're probably not using a `git` gem (though..I'm sure there's an edge case, ha!).

Or, worst case, add an env var to toggle the `with_clean_env` around the `git`/`git!` call, in case they have a particular gem+git setup.

**Comment by segiddins** [comment]
I'd just add a shim to your path, tbh.

**Comment by notjosh** [comment]
Do you mean `GEM_PATH` or `PATH`? I'm not super up on Ruby so I don't really know how paths will work under Bundler. Happy to give it a shot though :)

**Comment by segiddins** [comment]
Just an executable in `PATH` that calls `Bundler.with_clean_env` or manually does the equivalent work.

**Comment by notjosh** [comment]
For some closure on this now that I have some time, my solution (which feels like a Bad Way of Doing Things™) was to create a shim for `boxen-git-credential` (and rewrote `~/.gitconfig` to point to it) that looks like:

```sh
#!/bin/bash

SYSTEM_BUNDLER_PATH="/Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3"

BUNDLE_GEMFILE=${BOXEN_HOME}/repo/Gemfile
RUBYLIB=${SYSTEM_BUNDLER_PATH}/lib
PATH=${SYSTEM_BUNDLER_PATH}/bin:/usr/bin:${PATH}

bundle exec ${BOXEN_BIN_DIR}/boxen-git-credential $@
```

Besides hard-coding the `SYSTEM_BUNDLER_PATH`, it seems relatively safe. Hope it helps someone!

**Comment by bgerstle** [comment]
i might ask the boxen folks about merging my workaround, but I'm curious what you think, @notjosh. basically, just wrap the real boxen-git-credential script w/ something that cleans bundler env before running if needed:

``` ruby
#!/usr/bin/env ruby

cmd = "/opt/boxen/repo/script/_boxen-git-credential #{ARGV.join(" ")}"
if defined? Bundler
  Bundler.clean_system cmd
else
  system cmd
end
```

**Comment by notjosh** [comment]
@bgerstle if that works, then that's probably a (far) cleaner solution. I can't remember exactly what, but I was having tons of subtle, weird little issues trying an approach similar to that.
