### ISSUE TITLE
The ibtool processing of storyboards needs the "target-device" flags when building for less than iOS 8.0

### ISSUE THREAD

**Issue by seaders** [CocoaPods/CocoaPods#4913]
We were getting hit with the build process creating a zero bytes compiled storyboard, and poking around things, we found the culprit to be the `ibtool` step,

    ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target 6.0 --output-format human-readable-text --compile BuildDir/SwrveConversation.storyboardc SourceDir/SwrveConversation.storyboard --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk

And then reading up about this on stackoverflow, I found,
    http://stackoverflow.com/questions/29563618/xcode-no-valid-compiled-storyboard-at-path/29563997

Which pointed to the `Use Size Classes` which I think essentially turns a Universal storyboard into a per-device one.

Then looking at the stop that XCode do themselves, it seems this has been resolved in their build process, but CocoaPods has fallen behind.

In their step, they do,

    ibtool --errors --warnings --notices --module TestyBedy --output-partial-info-plist /Developer/workspaces/xcode/TestyBedy/Build/Intermediates/TestyBedy.build/Debug-iphonesimulator/TestyBedy.build/SwrveConversation-SBPartialInfo.plist --auto-activate-custom-fonts --target-device iphone --target-device ipad --minimum-deployment-target 6.0 --output-format human-readable-text --compilation-directory /Developer/workspaces/xcode/TestyBedy/Build/Intermediates/TestyBedy.build/Debug-iphonesimulator/TestyBedy.build /Developer/workspaces/xcode/TestyBedy/TestyBedy/SwrveConversation.storyboard

So then, for us, altering the top command to just,

    ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target 6.0 --output-format human-readable-text --compile BuildDir/SwrveConversation.storyboardc SourceDir/SwrveConversation.storyboard --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk  --target-device iphone --target-device ipad

Then produced a correctly compiled storyboard, and fixed all our issues.

**Comment by segiddins** [comment]
Can you share a project that reproduces the issue you're experiencing? Thanks!

**Comment by seaders** [comment]
Certainly, it's the Swrve-iOS-SDK, https://cocoapods.org/pods/SwrveSDK | https://github.com/Swrve/swrve-ios-sdk, with the specific storyboard in question, https://github.com/Swrve/swrve-ios-sdk/blob/release-4_2/Sdk/Conversation/Resources/SwrveConversation.storyboard.

Just set your min deployment target to less than 8.0 and you'll find the SwrveConversation.storyboardc file in the build directory to be an empty directory / zero bytes, but if you manually include the sdk, it builds correctly, with the `target-device` flags.

**Comment by segiddins** [comment]
And what version of CocoaPods are you using? Are you building with frameworks? Have you tried with the latest 1.0 beta?

**Comment by seaders** [comment]
CocoaPods version: `1.0.0.beta.1`

I'll update to the latest and try that.

As for frameworks, it's not really got anything to do with them, I don't think.  If I check the `TestApp-resources.sh` file, the `ibtool` command is in there,

    ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target ${!DEPLOYMENT_TARGET_SETTING_NAME} --output-format human-readable-text --compile "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/`basename \"$RESOURCE_PATH\" .storyboard`.storyboardc" "$RESOURCE_PATH" --sdk "${SDKROOT}"

Using / not using frameworks wouldn't have anything to do with that command.

**Comment by seaders** [comment]
I've just updated to `1.0.0.beta.3` and no difference.  Again the `ibtool` command hasn't changed a huge amount,

    ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target ${!DEPLOYMENT_TARGET_SETTING_NAME} --output-format human-readable-text --compile "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/`basename \"$RESOURCE_PATH\" .storyboard`.storyboardc" "$RESOURCE_PATH" --sdk "${SDKROOT}"

**Comment by segiddins** [comment]
If you could make a PR updating that `ibtool` invocation, that'd be great!

**Comment by seaders** [comment]
I'm not 100% it's "d1:easy" as I think it should change based on the target.  Is there information passed into that area to define whether it's building to iPhone, iPad or Universal?

The reason I'm asking is because you wouldn't pass in all of them for every build, because again it wouldn't be the same as the XCode build.  If you change your target to just iPhone, or iPad, their command changes appropriately,

    ibtool --errors --warnings --notices --module TestyBedy --target-device iphone --minimum-deployment-target 6.0 --compilation-directory BuildDir/ Resources/SwrveConversation.storyboard

**Comment by segiddins** [comment]
`$TARGET_DEVICE_FAMILY`

**Comment by seaders** [comment]
That was showing up empty, I think you mean `$TARGETED_DEVICE_FAMILY`

**Comment by seaders** [comment]
In fact, the reason I know that is because this bit is in the .sh file already, at the bottom,


    if [[ -n "${WRAPPER_EXTENSION}" ]] && [ "`xcrun --find actool`" ] && [ -n "$XCASSET_FILES" ]
    then
      case "${TARGETED_DEVICE_FAMILY}" in
        1,2)
          TARGET_DEVICE_ARGS="--target-device ipad --target-device iphone"
          ;;
        1)
          TARGET_DEVICE_ARGS="--target-device iphone"
          ;;
        2)
          TARGET_DEVICE_ARGS="--target-device ipad"
          ;;
        *)
          TARGET_DEVICE_ARGS="--target-device mac"
          ;;
      esac

But as far as I can tell, it's only used with `xcrun actool`?

**Comment by segiddins** [comment]
Then we probably should use it for `ibtool` as well?

**Comment by seaders** [comment]
I've created the pull request here, https://github.com/seaders/CocoaPods/pull/1/files

As for using it across *all* `ibtool` commands, I would think it won't harm anything, and I'm sure that it's correct for processing the storyboards (because that's what XCode does itself), but I can't comment on xibs, and that step.  We haven't encountered an issue, and I currently can't see the exact command of that by XCode.

**Comment by segiddins** [comment]
Could you make the PR onto this repo? Don't worry about the integration specs, I can handle regenerating them after merge

**Comment by seaders** [comment]
D'oh, getting late in the day here, that's obviously what I meant to do...

Done: https://github.com/CocoaPods/CocoaPods/pull/4915

**Comment by segiddins** [comment]
Danke!

**Comment by seaders** [comment]
Fáilte romhat!

**Comment by segiddins** [comment]
Closed by https://github.com/CocoaPods/CocoaPods/commit/b5813f3bbfa4ccb979a65917c6b179de5bd8fec0.
