### ISSUE TITLE
Quick Pod Install

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4917]
When a podfile is update is the reference to the github repo cached in the podfile lock? Right now it appears that Travis CI is having to pull down all of the specifications.

This would be great if it was since cocoapods wouldn't need to download the full cocoapods repo. If a podfile.lock is missing a dependency or a user runs `pod update`, only then should cocoapods need to pull down the repo, as it will need to resolve the version number.

**Comment by segiddins** [comment]
That adds a lot of complication and it isn't worth it imho. You can always run with `--no-repo-update`

**Comment by jcampbell05** [comment]
@segiddins  Issue is on Travis CI it needs this repo for each VM, if we could somehow pulldown the specifications directly via a github blob that would be amazing.

**Comment by segiddins** [comment]
We had that once. Not worth the complication to maintain. But you could write a source plugin if you really wanted to.

**Comment by jcampbell05** [comment]
Will do
