### ISSUE TITLE
How can I remove one pod lib?

### ISSUE THREAD

**Issue by AbooJan** [CocoaPods/CocoaPods#4918]
I read guides on your official website, there has guide for how to create lib or podspec and push to cocoapod storehouse , but I can't find any guides for how to remove it .

I execute `pod spec` or `pod repo` command to get some help, but get nothing. 

Some one can help? Thanks!

I don't know where I can contact you, so I create one issues here.

**Comment by segiddins** [comment]
`pod trunk deprecate` on the 1.0 betas.
