### ISSUE TITLE
Custom configuration does not play nicely with embedded framework

### ISSUE THREAD

**Issue by bimusiek** [CocoaPods/CocoaPods#4923]
Hey,
I have project that has another target called ProjectAPI. This is framework with all apis request I am amking. 
I use Pods for both, main and this api target. 
When I had standard configuration (debug & release) everything works fine.
However, I created new configurations and even that ProjectAPI builds correctly, when I try to build main target that has dependency on ProjectAPI, I am getting error `No such module "SwiftyJSON"`. 

![screenshot 2016-02-22 10 45 50](https://cloud.githubusercontent.com/assets/1025588/13214692/7819922e-d951-11e5-8cf5-f33d397c8822.png)

Here you can see that AhoyAPI can be built:
![screenshot 2016-02-22 10 46 19](https://cloud.githubusercontent.com/assets/1025588/13214706/8cb88c76-d951-11e5-8db1-dc5883b0a32e.png)

And how configurations look like:
![screenshot 2016-02-22 10 47 04](https://cloud.githubusercontent.com/assets/1025588/13214729/a50c4b46-d951-11e5-9155-5ca781557346.png)

Do you have any idea what am I doing wrong? I checked with stable cocoapods, then with 1.0.0-beta3. Also I tried with `linked_with` option as well as specify targets separately. 

And here my Podfile:
```
# ignore all warnings from all pods
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'Ahoy' do
    pod 'Smooch'
    pod 'SVProgressHUD'
    pod 'SDWebImage'
    pod 'FontAwesomeKit', :git => 'https://github.com/PrideChung/FontAwesomeKit.git', :commit => '7e86f53b0f4e9f83d2b2acc59992fea33766fb73'
    pod 'FXKeychain'
    pod 'Fabric'
    pod 'Digits'
    pod 'TwitterCore'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'RealmSwift'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'libPusher'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxBlocking'
    pod 'HanekeSwift'
    pod 'Google/Analytics'
end


target 'AhoyAPI' do
    pod 'Smooch'
    pod 'SVProgressHUD'
    pod 'SDWebImage'
    pod 'FontAwesomeKit', :git => 'https://github.com/PrideChung/FontAwesomeKit.git', :commit => '7e86f53b0f4e9f83d2b2acc59992fea33766fb73'
    pod 'FXKeychain'
    pod 'Fabric'
    pod 'Digits'
    pod 'TwitterCore'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'libPusher'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxBlocking'
    pod 'HanekeSwift'
    pod 'Google/Analytics'
end


post_install do |installer|
    plist_buddy = "/usr/libexec/PlistBuddy"
    installer.pods_project.targets.each do |target|
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        original_version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip
        changed_version = original_version[/(\d+\.){1,2}(\d+)?/]
        unless original_version == changed_version
            puts "Fix version of Pod #{target}: #{original_version} => #{changed_version}"
            `#{plist_buddy} -c "Set CFBundleShortVersionString #{changed_version}" "Pods/Target Support Files/#{target}/Info.plist"`
        end
    end
end

```

**Comment by neonichu** [comment]
When you look at the generated XCConfigs for the different configurations, do they differ in a meaningful way? Also, based on the off-chance you didn't do that yet, did you try deleting DerivedData and rebuilding?

**Comment by bimusiek** [comment]
No difference between xcconfig files.
```
diff "./Pods/Target Support Files/Pods-Ahoy/Pods-Ahoy.debug.xcconfig" "./Pods/Target Support Files/Pods-Ahoy/Pods-Ahoy.devdebug.xcconfig"
```
returns empty result. 

Also I have added to `Podfile` 
```
xcodeproj 'Ahoy', {
  'DevDebug' => :debug,
  'RCDebug' => :debug,
  'LiveDebug' => :debug,
  'RCRelease' => :release,
  'LiveRelease' => :release,
}
```
(also tried with `project` and 1.0.0-beta3) 

Yes, I cleared `DerivedData` as well as cleaned project. I have also tried to remove `Pods/` dir and `.lock` files to reinstall everything. Did not help.

I also followed http://stackoverflow.com/questions/30102976/how-to-add-custom-project-configurations-to-xcode-when-using-cocoapods to add to schema `Ahoy`, in build `Pods-Ahoy` target. Also did not help.
`AhoyAPI` builds properly, but `Ahoy` that has this framework embedded does not. :(

**Comment by neonichu** [comment]
This looks like it should work to me, we would need a project to debug this further. Are you able to reproduce this in a smaller project which you can share?

**Comment by bimusiek** [comment]
@neonichu I will try tomorrow to cut out code and I will provide you with small project.

**Comment by segiddins** [comment]
This ought to be fixed in Beta 4. Closing due to lack of response.
