### ISSUE TITLE
Include ressources and/or bundles in host project

### ISSUE THREAD

**Issue by arn00s** [CocoaPods/CocoaPods#4925]
Hi there,
I'm looking for a real solution to this problem :
I have an internal project, available for internal pods.
I'd like to include some resources (images, storyboards, ...) in all my apps.
I tried with several settings in my pod spec, for example : 

`s.resource_bundles, s.resource_bundle, s.resource, s.resources`

but none of these allow me to use these resources in the host project.

Can you please give me a real solution ?
What code do you use in the host project to load the resources ?

PS : I'm using CocoaPods 0.39

Thanks for your help!

**Comment by segiddins** [comment]
This is a usage question that probably better belongs on Dtack Overflow, sorry.

**Comment by LadiesChris** [comment]
http://www.oyeloca.com/t3/?tpl=join12&path=&nats=psmhouseal4.2.9.952.85.0.0.0.0&group=144&stvars=eyJjYW1wYWlnbl9pZCI6MjE1NzEsImJhbm5lcl9pZCI6MzMwMjEsInRpbWUiOjE0NTYyNTU4ODIsImlwX2FkZHJlc3MiOiIyMDkuMjM5LjE2Mi4xOTQiLCJwaHBfc2Vzc2lvbiI6Ijg4NDNnNGU4MXBsaGg3cnFvdXY5anY4dXUxIiwiY3BtIjoiMC4xNyJ9&autotags=camp21571%2Cbanner33021%2Ccontinuation&clientIP=67.0.158.162&ua=Mozilla%2F5.0+%28iPhone%3B+CPU+iPhone+OS+9_2_1+like+Mac+OS+X%29+AppleWebKit%2F601.1.46+%28KHTML%2C+like+Gecko%29+Version%2F9.0+Mobile%2F13D15+Safari%2F601.1&aclid=jrPMVgAAAACFXQAAeUOkO6u19EH2BwAAhV0AAAAAAAD_____AAAAAA==
Fuck

On Feb 23, 2016, at 12:14 PM, Samuel E. Giddins <notifications@github.com> wrote:

Closed #4925.

**Comment by orta** [comment]
interesting spam there.
