### ISSUE TITLE
"directory not found for option" when using the same Pod in two different targets

### ISSUE THREAD

**Issue by GaborWnuk** [CocoaPods/CocoaPods#4926]
Hi,

i want to use the same Pod in two targets (one iOS and one WatchOS). When i define my podfile like this (used Alamofire just as an example, it's consistent with any Pod you like):

```
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target "MyApp" do
    platform :ios, '8.2'
    # (...)
    pod 'SDWebImage'
end

target "MyAppWatchKitExtension" do
    platform :watchos, '2.0'
    pod 'Alamofire'
end
```

everything works properly, i can use Alamofire with no problem if i use it with `MyApp` OR `MyAppWatchKitExtension` but not BOTH.

If i try to use it in BOTH targets like this:

```
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target "MyApp" do
    platform :ios, '8.2'
    # (...)
    pod 'SDWebImage'
    pod 'Alamofire'
end

target "MyAppWatchKitExtension" do
    platform :watchos, '2.0'
    pod 'Alamofire'
end
```

i have following Linker error:

`ld: warning: directory not found for option '-F/Users/Superhero/Library/Developer/Xcode/DerivedData/Newsy-bfpyjerwoighfdcwmcebibrgeevc/Build/Products/Debug-watchsimulator/Pods-MyAppWatchKitExtension'`

It's not Alamofire-specific problem as it's consistent with every WatchOS supporting Pod i've tried.

**Comment by segiddins** [comment]
I believe @mrackwitz's open PR will fix this

**Comment by GaborWnuk** [comment]
#4920

**Comment by GaborWnuk** [comment]
Beta 4 resolved this issue, thank You!
