### ISSUE TITLE
Can't install pod with private source

### ISSUE THREAD

**Issue by nghiaphunguyen** [CocoaPods/CocoaPods#4929]
This below is my Podfile:
use_frameworks!

source 'https://nghiaphunguyen@bitbucket.org/nghiaphunguyen/privatelib.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Demo' do
    pod 'PirvateLib', '1.1.2'
end

But have an error occurred after pod install. What's wrong with me?
[!] An unexpected version directory `PirvateLib` was encountered for the `/Users/nghianguyen/.cocoapods/repos/bitbucket-privatelib/PrivateLib` Pod in the `PirvateLib` repository.

but it's work for me if i change Podfile to:

use_frameworks!

target 'Demo' do
    pod 'PirvateLib', '1.1.2', :git => 'https://nghiaphunguyen@bitbucket.org/nghiaphunguyen/privatelib.git'
end

Nghia,
Thanks

**Comment by neonichu** [comment]
The `source` directive is for the usage of private spec repos, not for the repos of Pods. See <https://guides.cocoapods.org/making/private-cocoapods.html> for more information on private spec repos.
