### ISSUE TITLE
Pods Linking not working with a "core" Lib which is linked into other Projects

### ISSUE THREAD

**Issue by dasoli** [CocoaPods/CocoaPods#4932]
#### What did you do?

 Run `pod install`

#### What did you expected to happen?

Install all pod dependencies correctly.
That my lib builds with the nested cocolibs. And this lib is linked as precompile condition without any problems.

Small hint: I have a lib (Core) that needs the pods, this should build and after that its linked as precondition in other projects.

#### What happened instead?

All of my pods in podfile dont get linked into project, so i run into symbols not found so i think the linking has problem. I fixed this problem longer ago with hacking the .sh files. But this time this did not work for me. 

I could fix it with manual linking of lib-pod-x, and other resources like bundles. But thats no solution... otherwise i wouldn't need the pods =)

Note:
Also i want to have said at this point, i didnt setup that process so i also expect problems on my side or miss configurations.

### Podfile

```ruby
workspace 'CrowdRadioWS'
#xcodeproj 'CrowdRadio/CrowdRadio.xcodeproj'
xcodeproj 'CrowdRadioCore/CrowdRadioCore.xcodeproj'
inhibit_all_warnings!

target :crowdRadioCore do
    platform :ios, '7.0'
    pod 'URBMediaFocusViewController'
    pod 'SRGMediaPlayer'
    pod 'UIColor+FlatColors'
    pod 'APParallaxHeader'
    pod 'JSONModel'
    pod 'SDWebImage'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'Reachability'
    pod 'MBProgressHUD'
    pod 'MarqueeLabel'
    pod 'MSPullToRefreshController'
    xcodeproj 'CrowdRadioCore/CrowdRadioCore.xcodeproj'
end
```

Thx for help and hopefully other people could also help =)
Oliver

**Comment by neonichu** [comment]
The description of your actual problem is quite vague, so it'll be pretty hard to identify the problem. 

One thing to check if this is an older project or one you're inheriting (that what it sounds like from your description), is if "Other linker flags" have been edited manually. If they appear bold in your target, they've been edited and you should reset them to actually use the values from the XCConfigs CocoaPods created for you.

**Comment by dasoli** [comment]
Short question, >If they appear bold in your target<  in the lib (which is the core and will be handled as pre condition)? or in the final target, ill have 19 targets so.. I only link the pods in the core lib not the final target which will be build.

**Comment by neonichu** [comment]
Only the target you're integrating with CocoaPods is relevant here.

**Comment by dasoli** [comment]
Ok i figured out that my question was useless.. i found it. They appear bold but when ill try to edit only $inherited is still in there, but i can see them. How could i reset them ? 

![bildschirmfoto 2016-02-23 um 16 38 22](https://cloud.githubusercontent.com/assets/8521948/13256675/f1a605e6-da4b-11e5-91f7-6786a2da026b.png)

**Comment by dasoli** [comment]
Other question, should i better link the pods vs. all targets instead of the "core" ? But iam bit confused, because my "core" is a target dependency and will be build before the main project is build. So maybe all is also misconfigured? Sorry for much questions..

**Comment by dasoli** [comment]
I fixed the problems with garbaging the project and resetup everthing, but a fail everytime with the cocopods is that i have to choose the architecture again and again in the pods.xproject file

greetings

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
