### ISSUE TITLE
PodDirCleaner doesn't preserve public_header_files or private_header_files

### ISSUE THREAD

**Issue by SSheldon** [CocoaPods/CocoaPods#4936]
I was writing a podspec for a vendored library, so I included `public_header_files` but no `source_files`. Turns out that `public_header_files` are stripped out by `PodDirCleaner`, so my pod worked great during development and `pod lib lint`, but the necessary files were being stripped when I would `pod spec lint`.

Perhaps it's expected that only `source_files` will be preserved. In that case maybe we should update [the documentation](https://guides.cocoapods.org/syntax/podspec.html#public_header_files) for `public`/`private_header_files` to indicate that the files should only be a subset of the files specified in `source_files`?

**Comment by segiddins** [comment]
They need to be in source files. Did you try running `pod lib lint`?

**Comment by SSheldon** [comment]
@segiddins yep, `pod lib lint` is successful if you only put headers in `public_header_files` and not in `source_files`.

I resolved the issue by using `source_files` instead of `public_header_files`, but I wanted to get your take on what the expected behavior is here :)

Maybe `pod lib lint` should be checking to make sure all header files are also part of the source files? If I had gotten an error message like that I would've understood right away.

**Comment by segiddins** [comment]
Yeah, it should check that all `{public,private}_header_files` are in `source_files`. If you want to make a PR implementing that, that'd be great :)

**Comment by SSheldon** [comment]
Thanks @segiddins, sorry I wasn't able to beat you to it :)
