### ISSUE TITLE
No longer possible to use local pods.

### ISSUE THREAD

**Issue by markst** [CocoaPods/CocoaPods#4937]
We use local pods, which never get uploaded. 
Since 1.0.0 it seems `source` is now a requirement.

```
[!] The `Generated` pod failed to validate due to 1 error:
    - WARN  | attributes: Missing required attribute `license`.
    - ERROR | attributes: Missing required attribute `source`.
    - WARN  | license: Missing license type.
```

How do you propose we use local pods without a `source`?

**Comment by neonichu** [comment]
You can define a `:path`-based `source` like `s.source = { :path => '.' }`. If you're using `:path` in your `Podfile`, it will be overridden anyway, so the value does not really matter in that case.

**Comment by markst** [comment]
thanks @neonichu

**Comment by EesaJacobs** [comment]
Encountered an unknown error (Unsupported download strategy `{:path=>"."}`.) during validation

**Comment by benmarten** [comment]
+1 this does not work anymore :/

**Comment by skander300** [comment]
it worked well for me, thanks.

**Comment by sspbond007** [comment]
I'm using cocoapod:
**$ pod --version
1.1.1**

**pod spec lint** returns following error 
**- ERROR | [iOS] unknown: Encountered an unknown error (Unsupported download strategy `{:path=>"."}`.) during validation.**

If I use some unknown download strategy than cocoapod warns with message:
**- WARN  | [iOS] keys: Missing primary key for `source` attribute. The acceptable ones are: `git, hg, http, path, svn`.**
this shows that path is supported strategy.

Please let me know if someone has the solution for the problem.

**Comment by benasher44** [comment]
Hi @sspbond007! It's not clear from your description exactly what you're trying to do, but it appears you might be trying to use the `:path` option in a dependency in your podspec. This is unsupported, since push a podspec with that in it would not be usable by others attempting to install that pod. Best of luck, and we encourage you to file a new issue if you're still having trouble!

**Comment by sspbond007** [comment]
Thanks for quick response @benasher44!
I was confused with the warning where it shows git, hg, http, path, svn etc options for source attribute and throws error if I use path attribute. 
Anyways it worked the way I wanted. I needed that pod use locally in one of my project, so pod install worked fine and created workspace with correct dependency. It was throwing error only when I validate podspec file using 'pod spec lint'.
Once again thanks for your response!

**Comment by scue** [comment]
@neonichu Can you give a example Podfile, thanks!

**Comment by jbarros35** [comment]
Where is the solution????!
