### ISSUE TITLE
Storyboard command still producing zero byte compiled file storyboardc

### ISSUE THREAD

**Issue by seaders** [CocoaPods/CocoaPods#4941]
:rainbow: This is down to the poor formatting of my previous suggested fix for `copy_resources_script.rb`.

I've created a PR for this change, https://github.com/CocoaPods/CocoaPods/pull/4940 but in basic terms when adding `${TARGET_DEVICE_ARGS}`, I'd put that just at the end of the command, but by mistake, I'd put it within the `--sdk` flag, which caused the command to execute in an incorrect, odd way, and again produce a zero byte storyboardc.

The previous PR was supposed to fix the zero byte storyboardc issue, but with how it was implemented, it was keeping it exactly the same.

*BAD*:

    ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target ${!DEPLOYMENT_TARGET_SETTING_NAME} --output-format human-readable-text --compile "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/`basename \"$RESOURCE_PATH\" .storyboard`.storyboardc" "$RESOURCE_PATH" --sdk "${SDKROOT} ${TARGET_DEVICE_ARGS}"

*GOOD*:

    ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target ${!DEPLOYMENT_TARGET_SETTING_NAME} --output-format human-readable-text --compile "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/`basename \"$RESOURCE_PATH\" .storyboard`.storyboardc" "$RESOURCE_PATH" --sdk "${SDKROOT}" ${TARGET_DEVICE_ARGS}

While I'm incredibly thankful for the quick turn around from the previous PR, and wholly accept my part in committing bad code, I do have to ask what the internal process was for this?  Was there an internal check to ensure that my original bug was in fact fixed by my PR?

**Comment by segiddins** [comment]
You verified the fix yourself for us ;)

**Comment by seaders** [comment]
Dang, was hoping it wasn't all down to me!  Sorry about that.  I was 100% sure I had verified the check while running it in XCode, but obviously not.

**Comment by segiddins** [comment]
No worries :)
I can release a new beta with the fix soon.

**Comment by jafara** [comment]
Was bitten by this also. The fix seems to work, any estimate on when it can be merged?

**Comment by segiddins** [comment]
Closed by 1160056edda716a06a814c17f920b6065df9950d.
