### ISSUE TITLE
inherit! :search_paths broken in 1.0.0.beta.4 for abstract targets

### ISSUE THREAD

**Issue by benasher44** [CocoaPods/CocoaPods#4943]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

### Report

Previous to this release, you could could use `inherit! :search_paths` in an abstract_target, and all of its child targets (at least immediately children) would inherit the search paths of the abstract_target's parent. This is useful when you have multiple test targets that share common testing pods and need to inherit search paths from the app under test.

#### What did you do?

Attempt to build and run the tests in this project, wherein one of the tests imports a header from a pod included for the app.

#### What did you expected to happen?

The tests would build and run.

#### What happened instead?

The test bundle failed to compile because it could not find the pod's header.

### Podfile

```ruby
abstract_target 'SharedDeps' do
  pod 'AFNetworking'

  target 'InheritSearchPathsBroken' do
    abstract_target 'TestsShared' do
      inherit! :search_paths
      pod 'OCMock'
      target 'InheritSearchPathsBrokenTests'
    end
  end

  target 'InheritSearchPathsBroken WatchKit 1 Extension'
end
```
I have a sample xcode project coming soon to Github. I'll comment on this issue as soon as it's posted.

**Comment by benasher44** [comment]
Sample project posted here: https://github.com/benasher44/CocoaPods4943

Repro steps in this project:
1. bundle install and pod install
2. With the InheritSearchPathsBroken target selected (with any valid iOS simulator), attempt to run the sample test suite

It should error in InheritSearchPathsBrokenTests.m trying to `#import <AFNetworking/AFNetworking.h>`

**Comment by segiddins** [comment]
Thanks, working on a fix

**Comment by benasher44** [comment]
@segiddins awesome thanks!

**Comment by benasher44** [comment]
#308 fixes it for us. Nice work!
