### ISSUE TITLE
github see Swift pod create with pod lib create as shell project

### ISSUE THREAD

**Issue by sarunw** [CocoaPods/CocoaPods#4946]
I made pod project with `pod lib create` and when I submit code to github it always recognize as shell project.

Here are some examples https://github.com/sarunw/SWSegmentedControl https://github.com/sarunw/SWActivityIndicatorView

**Comment by segiddins** [comment]
There's nothing we can really do about that -- since you only have very few swift files and are commit your `Pods` directory, github's stats aren't inaccurate.

**Comment by ayalcinkaya** [comment]
If you send your swift file first, Github recognizes the repository as Swift. Then you can send other files to the repo.
