### ISSUE TITLE
## Facing Architecture related problem with Pod Integration

### ISSUE THREAD

**Issue by SarveshRS** [CocoaPods/CocoaPods#4947]
## What I did?

Decided to add pods in my existing project.
Migrated most of the frameworks and libraries to pod successfully.
Meanwhile while doing the same, I received loads of linking errors related to architectures.
Resolved them by removing arm64 architecture from my Project Targets
Below is the link that shows my current architecture.

![screen shot 2016-02-25 at 4 25 40 pm](https://cloud.githubusercontent.com/assets/5631705/13317699/763e5cb8-dbdc-11e5-951f-1e067f4913d3.png)

## What is the exact problem?

>  With the above architecture, I am able to run the app on simulator and iPhone 4/4s but fail to run the same for 5s,6,6+ and 6s

The linking error I am facing is

> file is universal (4 slices) but does not contain a(n) armv7s slice: /Users/Abby/Documents/CocoaPod Demo (Failed)/AppName Development/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a file '/Users/Abby/Documents/CocoaPod Demo/AppName Development/Pods/GoogleAnalytics/Libraries/libGoogleAnalytics.a' for architecture armv7s

## What did I expected to happen?

> I want to analyse the reason behind this error and provide support for all devices while using pods.
> Would like to know if I am doing anything wrong here,

## Podfile Specifications -
 
pod 'AFNetworking'
pod 'CleverTap-iOS-SDK’
pod 'Crashlytics'
pod 'Fabric'
pod 'Pushwoosh'
pod 'iCarousel'
pod 'RSKImageCropper'
pod 'PKRevealController'
pod 'AppsFlyer-SDK'
pod 'GoogleTagManager'
pod 'GoogleAnalytics'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

## Please help me fix this !!
Help will be appreciated :+1:

**Comment by neonichu** [comment]
You're building for `armv7s` but GoogleAnalytics does not ship with an `armv7s` slice. Since it is a binary Pod, there's nothing you or CocoaPods can do to mitigate it, except for not building `armv7s`.

**Comment by SarveshRS** [comment]
I removed GoogleAnalytics and GoogleTagManager from pod and added them manually and wohoo...It worked

**Comment by SarveshRS** [comment]
@neonichu 
I am facing another probem. This time with GoogleSignIn New Sdk
For armv7 and armv7s architecture I am getting same slicing error.
