### ISSUE TITLE
Problem with Cocoapods installation in new Macbook Pro OS 10.11

### ISSUE THREAD

**Issue by PSIPhone** [CocoaPods/CocoaPods#4948]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
$ sudo gem install cocoapods

$ sudo gem install cocoapods

## What did you expected to happen?

> ℹcocoapods to be installed so i can run pod commands.

## What happened instead?

> ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - /usr/local/bin

```

**Comment by neonichu** [comment]
See <https://github.com/CocoaPods/CocoaPods/issues/3692#issuecomment-113847612>
