### ISSUE TITLE
 could not build Objective-C module since beta.4

### ISSUE THREAD

**Issue by muhasturk** [CocoaPods/CocoaPods#4950]
1.0.0.beta.3 has no problem. Problem seens alive since beta.4
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Tried build my iOS project
## What did you expected to happen?

Build successfully
## What happened instead?

```
/Users/muhasturk/Library/Developer/Xcode/DerivedData/Kidofun-dnpyvqmdyyathecqamzttcigtjgt/Build/Products/Debug-iphonesimulator/pop/pop.framework/Headers/POP.h:13:9: error: 'pop/POPDefines.h' file not found
#import <pop/POPDefines.h>
        ^
<unknown>:0: error: could not build Objective-C module 'pop'

```
## Podfile

``` ruby
platform :ios, '8.0'
use_frameworks!

target 'BlaBla' do
    pod 'Alamofire', '~> 3.0'
    pod 'Crashlytics'
    pod 'Fabric'
    pod 'Koloda', '~> 2.0.8'
    pod 'SwiftyJSON'
end
```

**Comment by mrackwitz** [comment]
Have you tried to clean your build folder and re-build from scratch?

**Comment by muhasturk** [comment]
Yes I did two times. 1.0.0.3 has no problem.

**Comment by segiddins** [comment]
In that case, could you share a project we can use to debug?

**Comment by ejensen** [comment]
I'm experiencing something similar with beta 4:
``` shell
error: 'RxCocoa/RxCocoa.h' file not found
#import <RxCocoa/RxCocoa.h>
        ^
<unknown>:0: error: could not build Objective-C module 'RxCocoa'
```

Podfile:
``` YAML
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
use_frameworks!

target 'The Target' do
    pod 'AsyncDisplayKit', :git => 'https://github.com/facebook/AsyncDisplayKit'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'RxCocoa'
end
```

 Worked without a problem in beta 2 & 3

**Comment by matthijs2704** [comment]
Same here! I tried rebuilding, cleaning and removing derived data, but no results...

**Comment by segiddins** [comment]
Can anyone share a project?

**Comment by muhasturk** [comment]
I can't because it's commercial project.

**Comment by segiddins** [comment]
Then boil it down to something simpler that we can run. Otherwise, were less likely to investigate the issue.

**Comment by ejensen** [comment]
@segiddins https://github.com/ejensen/CocoaPodsBeta4Issue is a boiled down project that displays the issue. The 1st commit uses CP 1.0 beta 3. The 2nd commit updates to CP 1.0 beta 4, which causes the project to fail compilation.

**Comment by niklassaers** [comment]
I am seeing the same or something very similar. I have two mixed Swift/ObjC projects where one is dependent on the other. CocoaPods has always added the dependent project to the workspace even though it is already there, and lately it then complains of double references. Works good, though. But since 1.0.0.b4 it will not import modules such as Alamofire anymore. Only thing I need to do is gem update to 1.0.0.b4 (from 1.0.0.b3) and do a "pod install" and it will fail.

I am working on getting this project open sourced, so while I cannot share it openly just yet, I can share it privately with you, and I'd love to do a session together to try to find it together (I'm on GMT+1)

**Comment by segiddins** [comment]
@mrackwitz any interest in looking at this one?

**Comment by feifanzhou** [comment]
This project is just a template Swift project from Xcode with [Atlas](https://github.com/layerhq/Atlas-iOS) as the only dependency. It built fine on Cocoapods 0.39, but broke with 1.0.0b4 and 1.0.0b5. 

[Atlas-Swift-Test (no pods).zip](https://github.com/CocoaPods/CocoaPods/files/169724/Atlas-Swift-Test.no.pods.zip)

**Comment by mgrebenets** [comment]
I have created a repo with a demo target, which demonstrates an issue with tests targets.
https://github.com/mgrebenets/cocoapods-tests-with-transient-binary. The repo is using `1.0.0.beta5`, this is also directly related to #4944.

**Comment by muhasturk** [comment]
any progress for this issue? Should I upgrade cocoapods to latest?

**Comment by isair** [comment]
I'm having this issue on 1.0.0 release.

**Comment by marcmatta** [comment]
Having the same issue also on 1.0.0 release. Can someone help fix this please?

**Comment by jacobjiangwei** [comment]
Having the same issue also on 1.0.0 release. Can someone help fix this please?

**Comment by mrackwitz** [comment]
It's not yet confirmed to which extent this is an actual issue with CocoaPods. With the latest release some things got re-aligned, which might have caused in some cases that previously accidentally working podspecs don't work anymore. If you can still reproduce this issue, even after cleaning derived data, cleaning the CocoaPods cache, nuking the local Pods directory and installing again from scratch, then please report what podspec is causing issues for you, in the best case including a minimum reproduce sample project.

**Comment by Fawxy** [comment]
I had this issue, I cleared `pod cache`, nuked the `Pods` folder, redid `pod install`, and now i'm getting another error:

    error: ....fssaygqyocsdwwejsgiszaapqvpc/Build/Products/Debug-iphoneos/Pods.framework: No such file or directory

Haven't been able to get past this.

**Comment by aronspringfield** [comment]
I was experiencing this issue but have now solved it. The issue is with Derived Data which is why it can't be replicated in a new project. 

To fix it, in XCode go to Window->Projects, find your project in that list (usually the top one if it's the open one). Then click the Delete button next to the Derived Data section. Rebuild should work.

**Comment by niklassaers** [comment]
So, perhaps a bit late, but what I saw in 1.0.0b4 is solved in 1.0.0. :-)

**Comment by yuchengzhixia** [comment]
@aronspringfield Your answer solved my problem, thanks!

**Comment by laurilehmijoki** [comment]
On JetBrains App Code, I got around the problem with the following steps:

1. Run –> Clean Build Folder
2. Run –> Clean
3. Build

**Comment by stpeterthe1** [comment]
I have the same problem
