### ISSUE TITLE
pod's platform setting overrides project's platform setting

### ISSUE THREAD

**Issue by mackuba** [CocoaPods/CocoaPods#4952]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
gem install cocoapods --pre
pod _1.0.0.beta.4_ install
```

and then Cmd+B.

## What did you expected to happen?

I expected the project to build successfully.

## What happened instead?

I got a message: `clang: error: -fobjc-arc is not supported on versions of OS X prior to 10.6`.

## Podfile

Problem reproduced in a clean project with just one pod:

```ruby
target 'PodsOSVersionExample' do
  platform :osx, '10.7'

  pod 'MASPreferences', '1.1.2'
end
```

I've noticed that the [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/MASPreferences/1.1.2/MASPreferences.podspec.json) for that pod lists 10.5 as the platform, so that's probably where the 10.5 comes from. However, my podfile says it should build everything for 10.7, so that should take priority, right? Anyway, when I build the project with an older version of CocoaPods (0.39.0), I don't get that error, so it must be building the pods for 10.7.

**Comment by segiddins** [comment]
Nope, it uses the value from the podspec now. If the podspec doesn't actually support 10.5, someone will need to push a new version.
