### ISSUE TITLE
Prebuilt Frameworks are getting errors related to the umbrella header

### ISSUE THREAD

**Issue by heyzooi** [CocoaPods/CocoaPods#4956]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Prebuilt Frameworks are getting errors related to the umbrella header.

## What did you do?
`pod install` then try build on Xcode
PS: Podfile.lock indicates: - Kinvey (3.0.5)

## What did you expected to happen?
Install all pod dependencies correctly.

## What happened instead?
Got this error
```
Include of non-modular header inside framework module 'Kinvey'
```
but Kinvey.framework actually contains the header files mentioned in the umbrella header

## Podfile
```ruby
inhibit_all_warnings!
use_frameworks!

target 'Bookshelf' do

    pod 'SVProgressHUD'
    pod 'Kinvey'

end
```

**Comment by segiddins** [comment]
What version of CocoaPods are you using?

**Comment by heyzooi** [comment]
I tried 0.39.0 and 1.0.0.beta.4

**Comment by segiddins** [comment]
I can't find a published spec named `Kinvey`, so I'm having trouble debugging this.

**Comment by heyzooi** [comment]
https://github.com/CocoaPods/Specs/tree/master/Specs/Kinvey

**Comment by segiddins** [comment]
Works for me if I change `Kinvey.h` to

```objc
//
//  Kinvey.h
//  Kinvey
//
//  Created by Victor Barros on 2015-12-08.
//  Copyright © 2015 Kinvey. All rights reserved.
//

@import UIKit;

//! Project version number for Kinvey.
FOUNDATION_EXPORT double KinveyVersionNumber;

//! Project version string for Kinvey.
FOUNDATION_EXPORT const unsigned char KinveyVersionString[];

#import "KNVReadPolicy.h"
#import "KNVRequest.h"
#import "KNVDataStore.h"

// KinveyKit
#import "KCSRealmEntityPersistence.h"
#import "KCSReachability.h"
#import "KCSPush.h"
#import "KCSKeychain.h"
#import "KCSMICLoginViewController.h"
#import "KCSQueryAdapter.h"

// NSPredicate-MongoDB-Adaptor => https://github.com/tjboneman/NSPredicate-MongoDB-Adaptor
#import "MongoDBPredicateAdaptor.h"
```

**Comment by heyzooi** [comment]
But Apple recommends something different right?
If you create a new Framework project you will see something like...

```
// In this header, you should import all the public headers of your framework using statements like #import <Kinvey/PublicHeader.h>
```

**Comment by segiddins** [comment]
But that doesn't work, as your pod demonstrates

**Comment by heyzooi** [comment]
Well, it does work if I link my framework manually. So, i'm wondering how my podspec file should look like to link the same way when I do manually.

**Comment by segiddins** [comment]
¯\_(ツ)_/¯ no idea why it doesn't work and I won't have time to investigate this particular issue for a bit, but  the above workaround should work for now

**Comment by heyzooi** [comment]
Great! Thanks a lot @segiddins for your help.
I used a `prepare_command` to run a script to replace my imports from `#import <Kinvey/KNVKinvey.h>` to `#import "KNVKinvey.h"` and it worked!
