### ISSUE TITLE
Facing another problem with armv7s architecture. This time with GoogleSignIn New SDK

### ISSUE THREAD

**Issue by SarveshRS** [CocoaPods/CocoaPods#4959]
## With reference to #4947
Facing another problem with armv7s architecture. This time with GoogleSignIn New SDK

For armv7 and armv7s architecture I am getting same slicing error in both cases. By implementing GoogleSignIn using pods and manually as well. My architecture is the same mentioned in above issue. Although I was not facing this problem with Google+ Sign In SDK which I was using prior to this (deprecated now).

## Can anyone explain why googles static libs from many google SDK's don't have support for armv7s !! 

Help will be appreciated :+1:

**Comment by segiddins** [comment]
Honestly, it sounds like you should ask google support if your issues are confined to their pods.

**Comment by orta** [comment]
Yeah, @segiddins is right here I'm afraid, this isn't an issue about CocoaPods but with the Pods shipped by Google. Best contact their support / developer channels.
