### ISSUE TITLE
Dependency on tput causes error when run as root

### ISSUE THREAD

**Issue by randythompson** [CocoaPods/CocoaPods#4961]
* [yes ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run 'pod install'

## What did you expected to happen?

Expected the GoogleMaps pod to be installed in an Xcode project

## What happened instead?

The install failed with the comment "Oh no, an error occurred."

## Podfile

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
xcodeproj '/Users/randy/Development/story_drop_repo/StoryDrop.xcodeproj'

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ae4c8a663b8b62c8fefa5a1b84d5244228e57cdc
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
xcodeproj '/Users/randy/Development/story_drop_repo/StoryDrop.xcodeproj'
```

### Error

```
Errno::EBADARCH - Bad CPU type in executable - tput
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/banner.rb:292:in ``'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/banner.rb:292:in `terminal_width'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/banner.rb:255:in `wrap_with_indent'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:380:in `wrap_string'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:155:in `info'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:471:in `print_post_install_message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:465:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment]
Ugh. What happens if you run `tput` by itself? This should probably be handled inside https://github.com/CocoaPods/CLAide, though, if the issue persists.

**Comment by randythompson** [comment]
Frankly, I'm a complete noob to CocoaPods, Ruby, etc, and I don't even know what "tput" is. I guess I can get in the terminal and try to emulate what it was trying to do if there was enough info in that error report to do so. (I'm not in front of the computer right now.)


Sent via Email+ secured and managed by MobileIron

________________________________

From: "Samuel E. Giddins"
Date: Monday, February 29, 2016 at 2:44:30 PM
To: "CocoaPods/CocoaPods"
Cc: "Thompson, Randy R."
Subject: Re: [CocoaPods] Can't Install GoogleMaps Pod in Xcode Project (#4961)


Ugh. What happens if you run tput by itself? This should probably be handled inside https://github.com/CocoaPods/CLAide, though, if the issue persists.

**Comment by segiddins** [comment]
Yes, please just try executing `tput` in your terminal

**Comment by randythompson** [comment]
Just got back from a quick business trip, so I was away from the computer that has issues.

So I opened a terminal and entered "tput - V", with the following results...

===
randy% tput -V
ncurses 5.7.20081102
===

Looks like it is behaving as expected.

**Comment by randythompson** [comment]
Perhaps the issue is that the machine I am running this on uses Quad-Core Intel Xeon CPUs... an older vintage Intel CPU from early 2008?  (And yet it still runs Mac OS X El Capitan.)

**Comment by segiddins** [comment]
I have no clue, to be honest. Though there is something I can try in CLAide, if you give me a few days

**Comment by randythompson** [comment]
Strange!  I just found out that if I run "tput" as root, or even using "sudo", it does NOT run correctly.  It gives the "Bad CPU type in executable" error.  But if I run it as a standard user, it does just fine.

**Comment by randythompson** [comment]
Ah ha.

There is another put on my system which behaves correctly: /usr/bin/tput.

I think that the other one (in the /sw area) may have been installed via "Fink".  I think that I need to get all the stuff in /sw out of my path.
