### ISSUE TITLE
Path passed to install_resource is incorrect for some pods

### ISSUE THREAD

**Issue by gcox** [CocoaPods/CocoaPods#4963]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Issue #4954 changes the path generated and passed to ```install_resource```. This appears to generate the correct path for some pods but, at least for the ```google-cast-sdk``` pod, it produces an invalid path. The path it produces is ```$CONFIGURATION_BUILD_DIR/google-cast-sdk/CastFrameworkAssets.bundle``` but the ```CastFrameworkAssets.bundle``` is actually located at ```$CONFIGURATION_BUILD_DIR/google-cast-sdk/CastFrameworkAssets.bundle```.

The path generated using CocoaPods 1.0.0.beta 4 is valid.

[Sample Project](https://github.com/Tundaware/CocoaPods-copy-resources-bug) demonstrating the problem.

## What did you do?
Created an empty project with an iOS application target and a Podfile with a single dependency on ```google-cast-sdk```
Ran ```pod install``` using my local copy of CocoaPods which points to 142d282
Tried to build the project
## What did you expected to happen?
A successful build

## What happened instead?
The build fails due to an error during the copy pod resources script.  The error indicates that ```CastFrameworkAssets.bundle``` cannot be found. 

## Podfile

```ruby
target :'Demo' do
  project 'Demo.xcodeproj'
  
  pod 'google-cast-sdk'
end
```

**Comment by segiddins** [comment]
@mrackwitz or @efirestone if either of you could take a look at this, that'd be awesome!

**Comment by ajmas** [comment]
I suspect this is the same issue I ran into the same issue today? The work around was to remove the project name from the "per-configuration build products path". In my case they were frameworks I was depending on (AFNetworking and Alamofire). I had been using 0.39.0

**Comment by efirestone** [comment]
This looks related to your changes in https://github.com/CocoaPods/CocoaPods/pull/4954, @mrackwitz. I haven't looked into the internals of the new deduping, so not sure what the right fix is myself.

**Comment by segiddins** [comment]
Can you check if this is fixed on `master` for you, @gcox ? https://guides.cocoapods.org/using/unreleased-features.html

**Comment by gcox** [comment]
@segiddins It's not fixed in ```master```.  But it doesn't look like anything was changed in ```master``` since I reported this that would have fixed the problem. Does the sample project compile for you after running ```pod install``` using ```master```?

**Comment by appveng3r** [comment]
@segiddins I do have a similar issue with the HockeySDKResource.bundle. I used cocoapods 1.0.0.beta.5 for pod install
```
Resource "/Users/andreas.grauel/Library/Developer/Xcode/DerivedData/Chefkoch-bqdylzztuvjnhjcjqubvpuxqjvbn/Build/Products/Debug-iphonesimulator/HockeySDK/HockeySDKResources.bundle" not found.
```

If I use cocoapods 1.0.0.beta.3 everything is fine.

**Comment by rist** [comment]
Have the same issue with HockeySDK

```
PhaseScriptExecution 📦\ Copy\ Pods\ Resources /Users/rist/Library/Developer/Xcode/DerivedData/George_Go-apafzrkkkygzdtgowfdxrsjquuvz/Build/Intermediates/George\ Go.build/Debug-iphonesimulator/George\ Go\ Internal.build/Script-A23A49D70554267B9E9BEE6C.sh
    cd /Users/rist/projects/bee.one/MTA/ios
    /bin/sh -c \"/Users/rist/Library/Developer/Xcode/DerivedData/George_Go-apafzrkkkygzdtgowfdxrsjquuvz/Build/Intermediates/George\ Go.build/Debug-iphonesimulator/George\ Go\ Internal.build/Script-A23A49D70554267B9E9BEE6C.sh\"

error: Resource "/Users/rist/Library/Developer/Xcode/DerivedData/George_Go-apafzrkkkygzdtgowfdxrsjquuvz/Build/Products/Debug-iphonesimulator/HockeySDK/HockeySDKResources.bundle" not found. Run 'pod install' to update the copy resources script.
```

**Comment by lumaxis** [comment]
@appveng3r @rist Sorry you're having issues integrating HockeySDK! I just stumbled upon this issue when trying to publish a new version of our SDK a few hours ago. For a quick workaround you can switch  to the `HockeySDK-Source` pod which for me still works with 1.0.0.beta.5 😊

**Comment by mrackwitz** [comment]
Sorry y'all for being unresponsive on this! It's true what @efirestone supected, I broke it with #4954. A fix and improved unit test coverage for resource bundles are on the way.

**Comment by appveng3r** [comment]
This is not fixed, if I use https://github.com/appveng3r/gujemsiossdk as pod the `gujemsiossdk.bundle` is not installed in `$CONFIGURATION_BUILD_DIR/gujemsiossdk/gujemsiossdk.bundle` it is installed to `$CONFIGURATION_BUILD_DIR/gujemsiossdk/gujemsiossdk/gujemsiossdk.bundle`.

**Comment by segiddins** [comment]
@appveng3r did you try with beta 6? If it's not fixed, open a new issue.

**Comment by appveng3r** [comment]
@segiddins I will create a new issue tomorrow. It was tested with Beta6.

**Comment by gereons** [comment]
This resurfaced on my CI box today when trying to use the `HockeySDK` pod, as seen by @rist

**Comment by segiddins** [comment]
@gereons please open a new issue

**Comment by erema** [comment]
error: Resource "/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-bgszvlzstziakddnkornjorikbox/Build/Products/Adhoc-iphoneos/HockeySDK-Source/HockeySDKResources.bundle" not found. Run 'pod install' to update the copy resources script

we have a problem on our CI agent. any ideas?

**Comment by aphex3k** [comment]
I'm confused by the state of this ticket. It is confirmed defect but closed with no obvious pointer to the solution???

**Comment by orta** [comment]
It was closed when https://github.com/CocoaPods/CocoaPods/pull/5028 was merged automatically, so it's either in the master version of CocoaPods or the beta release.

**Comment by hetrix** [comment]
Is this still an issue? We are seeing it with v1.2.0. We are using private pods and are experiencing the same problem.

**Comment by hemangshah** [comment]
+1

**Comment by eagleonefight** [comment]
1.9.0 +1
