### ISSUE TITLE
prepare_command in local podspec

### ISSUE THREAD

**Issue by scinfu** [CocoaPods/CocoaPods#4964]
Hi
How can i run a command in a local podspec ?

the documentation say:
> If the pod is installed with the :path option this command will not be executed.
and this my case , there is a way to avoid this restriction?

Thank you .

**Comment by segiddins** [comment]
At the moment, you'll have to manually run whatever is in your `prepare_command` if the pod is a development / `path` pod.

**Comment by keeshux** [comment]
@segiddins would you at least explain why you're sticking with this behaviour? It's not the first similar issue you close without giving any explanation as to why you prefer it the way it is. The addition seems to make sense for a lot of people, perhaps if you provide us valuable reasons not to insist you're going to prevent new issues from being created in the first place.

Thanks.
