### ISSUE TITLE
module_map definitions in pod specs are not respected if they are defined on a per operating system basis.

### ISSUE THREAD

**Issue by ronak2121** [CocoaPods/CocoaPods#4968]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
module_map definitions in pod specs are not respected if they are defined on a per operating system basis.

## What did you do?
Tried to set our pod spec to the following:

s.ios.module_map = "Source/TestiOS.modulemap"
s.tvos.module_map = "Source/TestTVOS.modulemap"
s.osx.module_map = "Source/TestOSX.modulemap"
s.watchos.module_map = "Source/TestWatchOS.modulemap"

After running pod install on a pod spec like the above, it looks like Cocoapods doesn't see any of those settings and uses its own module map.

## What did you expected to happen?
We were looking for Cocoapods to respect the module map overrides we had provided.

## What happened instead?
Cocoapods ignored the above settings and generated its own module map instead.

## Podspec

```ruby
Pod::Spec.new do |s|

    s.name      =       "Test"

    s.author    =       { 'test Team' => 'test@test.com' }

    s.license   =       {:type => 'NONE', :text => 'LICENSE Not for Outside Distribution LICENSE' }

    s.homepage  =       "http://www.google.com"

    s.summary   =       "Test for Illustrative purposes"

    s.ios.deployment_target     = '8.0'

    s.osx.deployment_target = '10.10'

    s.tvos.deployment_target = '9.0'

    s.watchos.deployment_target = '2.0'

    s.version = "0.0.10"

    s.source = { :git => "ssh://somelocation", :tag => s.version }

    s.libraries = 'xml2.2'

    s.xcconfig = { 'HEADER_SEARCH_PATHS' => '"$(SDKROOT)/usr/include/libxml2"' }

    s.ios.frameworks = 'Foundation', 'CoreTelephony', 'SystemConfiguration', 'UIKit'

    s.osx.frameworks = 'Foundation', 'SystemConfiguration', 'AppKit'

    s.tvos.frameworks = 'Foundation', 'SystemConfiguration', 'UIKit'

    s.watchos.frameworks = 'Foundation', 'UIKit', 'WatchKit'

    s.ios.module_map = "Source/TestiOS.modulemap"
   
    s.tvos.module_map = "Source/TestTVOS.modulemap"

    s.osx.module_map = "Source/TestOSX.modulemap"
    
    s.watchos.module_map = "Source/TestWatchOS.modulemap"

     s.private_header_files = "Source/SomeFile.h", "Source/SomeOtherFile.h"

    s.source_files = "Source/**/*.{h,m,mm,swift}"

    s.watchos.exclude_files = "Source/SomeFile.h", "Source/SomeOtherFile.h"

    s.requires_arc = true

end
```

**Comment by segiddins** [comment]
I believe this is because you cannot specify per-platform module maps.

**Comment by ronak2121** [comment]
You can do this in XCode itself without any issue....

**Comment by segiddins** [comment]
This will require refactoring https://github.com/CocoaPods/CocoaPods/blob/142d282f8f10863cf75aeb459a0adf0992cd2ec2/lib/cocoapods/sandbox/file_accessor.rb#L287 to go through the spec consumer instead of directly accessing things on the root spec

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/pull/4969 should fix this, sorry!
