### ISSUE TITLE
Please remove AVAnimator pod from CocoaPods/Specs

### ISSUE THREAD

**Issue by mdejong** [CocoaPods/CocoaPods#4970]
Hello, I am the author of the AVAnimator library and I would request that the pod for this library be removed from your site. I did not create this pod spec and now I am getting complaints about it being out of date like the following:

https://github.com/mdejong/AVAnimator/issues/20

Please remove the AVAnimator pod spec, so that people will know they need to go to my site to get the most recent version.

**Comment by orta** [comment]
Sure thing, I've marked it as deleted, in an hour or two it won't show up on the site. It'll show up in the local search and still be available as you have [at least 25 apps](http://metrics.cocoapods.org/api/v1/pods/AVAnimator) using it, and I'm not breaking those projects.
