### ISSUE TITLE
Question: multiple projects/targets in workspace, how to ignore on podspec?

### ISSUE THREAD

**Issue by idokleinman** [CocoaPods/CocoaPods#4971]
I have a pod I am publishing, it's built in a `.xcworkspace`, lately I've added a new project with framework target (not part of the pod) to this workspace. This now causes build errors when I try `pod lib lint`.
Is there a way to make `pod` ignore this new target/project all together? via `podspec` file? other means?
Thanks!

**Comment by segiddins** [comment]
What are the build errors? Can you share a project that reproduces the issues you're seeing? Thanks!

**Comment by idokleinman** [comment]
Sure, project is [here](https://github.com/spark/spark-sdk-ios).
Errors:
```
 -> Spark-SDK (0.4.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  /Users/ido/Library/Developer/Xcode/DerivedData/App-bvysfdpccgsqujadoxrqdjqzadrw/Build/Products/Release-iphonesimulator/Spark-SDK/Spark_SDK.framework/Headers/Spark-SDK-umbrella.h:3:9: fatal error: 'Spark-SDK-Bridging-Header.h' file not found
    - NOTE  | [iOS] xcodebuild:  /var/folders/cs/fd7952qj5s53313lphmrfqph0000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'Spark_SDK'
```

all related to the non-pod project. Builds fine in XCode. this file `Spark-SDK-umbrella.h` doesn't even exist

**Comment by segiddins** [comment]
That header file, `Spark-SDK-Bridging-Header.h`, isn't included amongst your Pod's source files.

**Comment by segiddins** [comment]
```diff
diff --git a/Spark-SDK.podspec b/Spark-SDK.podspec
index 0cc8d20..c469167 100644
--- a/Spark-SDK.podspec
+++ b/Spark-SDK.podspec
@@ -29,7 +29,7 @@ Pod::Spec.new do |s|
     s.requires_arc = true
 
     s.public_header_files = 'Pod/Classes/*.h'
-    s.source_files = 'Pod/Classes/Spark-SDK.h'
+    s.source_files = 'Pod/Classes/*.h'
 
     s.subspec 'Helpers' do |ss|
         ss.source_files = 'Pod/Classes/Helpers/*.{h,m}'
```

fixes it for me

**Comment by idokleinman** [comment]
Thanks! Fixed. What I don't understand:
error was in `.framework` target: `.../Spark-SDK/Spark_SDK.framework/Headers/Spark-SDK-umbrella.h:3:9: fatal error:...` which is not part of the `pod`, how come modifying the podspec fixes that?
