### ISSUE TITLE
When are post_install actions run compared to post install hook plugins

### ISSUE THREAD

**Issue by nicolasbraun** [CocoaPods/CocoaPods#4973]
# Report

I am trying to remove folder after `pod_install` using the `post_install` command.
I want to remove the xcuserdata and xcshareddate folder from the pod because of #3824

I used this code :

```ruby
post_install do |installer|
  pod_pbxproj_path = installer.pods_project.path
  shared_scheme_path = "#{pod_pbxproj_path}/xcshareddata/"
  user_scheme_path = "#{pod_pbxproj_path}/xcuserdata/"
  puts "Shared #{shared_scheme_path}"
  
  if Dir.exist?(shared_scheme_path)
    puts "Removing schemes from #{shared_scheme_path}"
    FileUtils.rm_r(shared_scheme_path)
  end
  if Dir.exist?(user_scheme_path)
    puts "Removing schemes from #{user_scheme_path}"
    FileUtils.rm_r(user_scheme_path)
  end
end
````

## What did you expected to happen?

I expected these folder to be removed at the end of pod install

## What happened instead?

The folder where deleted during the pod_install phase, but reappear after the `Integrating client project` phase.

I tried using https://github.com/orta/cocoapods-no-dev-schemes : this works well but only deletes one folder.

I wonder why this hook is not executed at the same time my post_install actions are?

## Pod

I am using Cocopods 0.39

**Comment by segiddins** [comment]
They're intentionally executed at different times. Your best bet might be to make a PR improving or ta's plugin
