### ISSUE TITLE
"pod spec lint" does not catch no source files being listed in Podspec

### ISSUE THREAD

**Issue by danielrhodes** [CocoaPods/CocoaPods#4975]
# Report
## What did you do?

In building a new version of a pod, I mistakenly deleted the source files line in the Podspec:

`s.source_files = 'Pod/Classes/**/*'`

I ran `pod spec lint` and upon success ran `pod trunk push ActionCableClient.podspec`.

The pod was deployed as usual. However, predictably, when I tested the pod out by running `pod update` in my test project, there were no source files.
## What did you expect to happen?

So obviously this is my fault, since I deleted that line. However, I expected that running `pod spec lint` would pick up on this rather large omission from the Podspec.

I looked in the CocoaPod source briefly, and there are hints that for Objective-C there are some checks. So without any other information, I am guessing this might be an issue with Swift CocoaPods.
## Example Podspec

```
Pod::Spec.new do |s|
  s.name             = "ActionCableClient"
  s.version          = "0.1.3"
  s.summary          = "A Swift client for the Rails ActionCable WebSocket server."
  s.description      = <<-DESC
  ActionCable is a new WebSocket server being released with Rails 5 which makes it easy to add real-time features to your app. This Swift client makes it dead-simple to connect with that server, abstracting away everything except what you need to get going.
                       DESC

  s.homepage         = "https://github.com/danielrhodes/Swift-ActionCableClient"
  s.license          = 'MIT'
  s.author           = { "Daniel Rhodes" => "rhodes.daniel@gmail.com" }
  s.source           = { :git => "https://github.com/danielrhodes/Swift-ActionCableClient.git", :tag => s.version.to_s }
  s.social_media_url = 'https://twitter.com/danielrhodes'

  s.platform     = :ios, '8.0'
  s.requires_arc = true

  s.frameworks = 'Foundation'
  s.dependency 'Starscream', '~> 1.1.2'
  s.dependency 'SwiftyJSON', '~> 2.3.1'
end
```

**Comment by segiddins** [comment]
It is valid to have pods with no source files.

**Comment by orta** [comment]
The thing is, there are reasons for people to ship Pods without source code. 

However, IMO I think it's worth writing a warning for "No source code found." It covers the 90% use case.

**Comment by danielrhodes** [comment]
I assume those empty source file pods just distribute assets or something. Perhaps a solution for this case could be:
```ruby
s.source_files = []
```
followed by a warning, as mentioned by @orta.

However, if `s.source_files` are never defined, this would be error worthy.

That way, at least it's more intentional and catches the unintentional cases.

**Comment by orta** [comment]
This feels like a nice idea to me, @segiddins - opinion?

**Comment by segiddins** [comment]
That would require completely rewriting how specifications handle storing attributes and just isn't worth it imho when just trying to use the pod will pretty quickly show you you're missing something, not to mention tests being unable to compile.

**Comment by neonichu** [comment]
I think we should close this as the discussion never went anywhere?
