### ISSUE TITLE
clang: error: no such file or directory: '(-ObjC)'

### ISSUE THREAD

**Issue by williamgp** [CocoaPods/CocoaPods#4979]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install
then, tried to run my project

## What happened instead?

project won't run, getting a compiler error:
clang: error: no such file or directory: '(-ObjC)'

## Podfile
```ruby
#
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'my application' do

pod 'EZAudio', '~> 1.1.4'

end
```

**Comment by segiddins** [comment]
Can you give us some more information? What version of CocoaPods are you using? Where is the error coming from?

**Comment by segiddins** [comment]
Closing due to lack of response.
