### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by winnersmedia** [CocoaPods/CocoaPods#4981]
When using templates with shortcodes it would be good if that when a pod isn't defined the template allows you to put the loop within the template. For example if you want to include a surrounding table around a comparison table and don't want it modified per page.

e.g
[pods template="Comparison Table"]

Instead of:
[pods name="site" template="Comparison Table"]

> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> ℹ Please replace this with what you did.  
> e.g. Run `pod install`

## What did you expected to happen?

> ℹ Please replace this with what you expected to happen.  
> e.g. Install all pod dependencies correctly.

## What happened instead?

> ℹ Please replace this with of what happened instead.  
> e.g. Pod A is missing the subspec B for target C.

## Podfile

> ℹ Please paste the contents of your Podfile below.    
>  (e.g. via `cat Podfile | pbcopy`)  
> You can remove this hint then.

```ruby
# Paste your Podfile contents HERE.
```

**Comment by segiddins** [comment]
I'm really confused what this is actually referring to?

**Comment by orta** [comment]
This is for the wrong repo: you want https://github.com/pods-framework/pods
