### ISSUE TITLE
Install/Setup Not working

### ISSUE THREAD

**Issue by nathanandersen** [CocoaPods/CocoaPods#4988]
* [ X ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod setup`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
Nothing at all. Hung up and crashed.
` fatal: unable to access 'https://github.com/CocoaPods/Specs.git/': transfer closed with outstanding read data remaining`
`[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --depth=1`

`Cloning into 'master'...
fatal: unable to access 'https://github.com/CocoaPods/Specs.git/': transfer closed with outstanding read data remaining`

`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/executable.rb:70:in 'execute_command'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/executable.rb:27:in 'block in executable'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:74:in 'block in clone_repo'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:71:in 'chdir'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:71:in 'clone_repo'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:43:in 'block in run'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in 'section'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/repo/add.rb:41:in `run'
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/setup.rb:84:in 'add_master_repo'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/setup.rb:40:in 'block in run'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in 'section'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/setup.rb:32:in 'run'`
`/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in 'run'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in 'run'`
`/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
`/usr/local/bin/pod:23:in 'load'`
`/usr/local/bin/pod:23:in '<main>'`

## Podfile

```ruby
pod "YouTube-Player-iOS-Helper", "~> 0.1"
pod 'CocoaSoundCloudAPI', '1.0.1'
pod 'CocoaSoundCloudUI', '1.0.5'
```

**Comment by segiddins** [comment]
GitHub seems to be having some issues with clones of the Specs repo at the moment -- I'd watch status.github.com for updates, as there's nothing we can do about it.
