### ISSUE TITLE
Transforming Dependencies

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4992]
For my plugin I would love to be able to transform the type of dependencies in the podfile to something else or to create custom Source object I could use to change where they come from.

Is this possible without monkey patching right now ?

**Comment by segiddins** [comment]
Not currently, no, since nothing mutable is passed in the pre install hooks context.

**Comment by jcampbell05** [comment]
@segiddins currently I manually setup the Installer, in theory I could pass in a modified Podfile. What would be the easiest way to modify the sources of the dependencies ? I know there is an internal hash of some-sort, is this quite easy to modify ? 

I want to preserve all the targets etc the user has setup.

**Comment by segiddins** [comment]
You should just be able to mutate the dependency objects on a podfile, I.e. `Config.instance.podfile`

**Comment by jcampbell05** [comment]
@segiddins so I noticed for the target_definition class it has a store_pod. Would I be able to somehow use this to modify these dependencies.

to make 
```
pod "MyPod", "2.1.1"
```
to become
```
pod "MyPod", :podspec => "Some URL"
```

**Comment by segiddins** [comment]
In theory you could also monkey patch that, yes.

**Comment by jcampbell05** [comment]
@segiddins  Cool kept the 3 monkey patches I have to use in my project. In theory these could be replaced by a hook in a future version of Cocoapods as what they do isn't that complex..
