### ISSUE TITLE
Install size metric is not accurate

### ISSUE THREAD

**Issue by RDSpinz** [CocoaPods/CocoaPods#4994]
:rainbow:

https://cocoapods.org/pods/BeaconsInSpace/quality
[ :heavy_check_mark: ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

>  I uploaded my cocoapod using
`pod trunk push`

## What did you expected to happen?

I expected this to upload with no points subtracted for install size

## What happened instead?

I got -10 for having an install size greater than 10,000 kb (10MB). However when I look at my uncompressed file it is only 3.4MB, and compressed it is half that size.

The quality index for my cocoapod is here:

https://cocoapods.org/pods/BeaconsInSpace/quality

Somehow this isn't being calculated correctly.

**Comment by orta** [comment]
I wonder this is related to https://github.com/CocoaPods/cocoadocs.org/issues/395 - which at some point I'd like to change, however, this isn't a CocoaPods ( the gem ) problem, so I'm going to close this, now that it's linked to the CocoaDocs issue
