### ISSUE TITLE
Enable Custom CocoaPods Specs Repository URL

### ISSUE THREAD

**Issue by art-divin** [CocoaPods/CocoaPods#4997]
> * [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# It Should be Possible to Enable CocoaPods Specs Replication & Usage

## Why it is Important?

[Recently](https://github.com/CocoaPods/CocoaPods/issues/4989) there was an issue with some weird GitHub outage. The same goes for bad networks etc. This has caused many issues with running `pod setup`, `pod install`, `pod update` etc. for a number of developers.

Problem was not related to Podfile configuration and did not had to do with anything configuration-related. It was specifically about `git clone https://github.com/CocoaPods/Specs.git` failing 1 out of 10 times for whatever reason (bad network, service outage etc.)

## Expected Outcome

- As a CocoaPods, I'd like to set Specs repo url (`https` / `git`)
- So I can fetch public specs from it
- And I can work without involving network communication with GitHub itself
- And I can remove any internet and continue working with `pod install`, `pod setup` if I want to (on train, in airplane etc.)

# Notes
- There's an option not to checkout repositories, but what to do if there's no original copy of the specs repo?
- With an option not to update specs repository, it is possible to _miss_ changes that might be very important
- Replication of GitHub repo to a local git repository will make it a lot quicker to run `pod install`
- This feature request is only about _public_ specs repository
- Of course, `pod cache clean --all` will make it impossible to run `pod install` & Co without having an internet connection

**Comment by orta** [comment]
> Replication of GitHub repo to a local git repository will make it a lot quicker to run pod install

This is what CocoaPods does right now.

##### Re-changing the Repo URL

Git has a config around this, to quote [Alloy](https://github.com/CocoaPods/CocoaPods/issues/2724#issuecomment-60364405)

```
$ git config --global url.git://github.com/.insteadOf https://github.com/
$ git clone https://github.com/artsy/Specs.git artsy
[…]
$ cd artsy
$ git ls-remote --get-url
git://github.com/artsy/Specs.git
$ git config --get remote.origin.url
https://github.com/artsy/Specs.git
```

So, this might work:
```
git config --global url."https://bitbucket.com/My/Fork".insteadOf "https://github.com/CocoaPods/Specs"
```

Docs are here: http://git-scm.com/docs/git-config

**Comment by lazerwalker** [comment]
Just wanted to chime in a bit on this.

Most of the time, pointing to a non-GitHub copy of the Specs repo won't actually do what you're hoping it will. I can think of a few reasons you'd have network connectivity issues:

* You have no network connection (you're on a plane, to use your example)
* You have a network connection, but all of GitHub is down
* You can reach GitHub, but the Specs repo specifically isn't accessible

The third case is what happened in the linked issue. It's an edge case, not the norm, and it seems like the CocoaPods and GitHub folks are well on their way to helping ensure it won't happen again.

In the first two cases, being able to point to an alternate fork of the Specs repo, be it locally hosted or on a non-GitHub server, won't help you. The Specs repo just contains podspecs – plaintext data files – that merely point to the git repos that contain actual code. If your goal is to run `pod install` or `pod update` and actually download or update third-party code, you'll still need access to the actual repos of the code you're trying to download. 

If for some reason you're averse to having a hard dependency on GitHub as a git provider, I could imagine a scenario where you'd maybe want to mirror both the Specs repo and the repos of every single individual CocoaPod you rely on, but that's a very different (and much larger) undertaking.

**Comment by art-divin** [comment]
thanks @orta , I think your proposal here (which is Alloy's suggestion in the past) is certainly a good approach for at least two reasons:

1. It works and configurable not only globally, but repository-specific
2. No need to update CocoaPods (and for some companies updating CocoaPods is very painful)

However, it would be good to have a configuration flag within Podfile itself that will specify exactly from which URL should CocoaPods checkout Specs.

I think this will add a value for offline development, as well as for development within corporate networks which cannot access GitHub directly for security reasons whatsoever.

I imagine something like:
`pod setup --offline # takes Specs from a mirror; set mode to offline`
... Consequently:
```ruby
pod update # or --cached - doesn't checkout new copies of dependencies
pod install # or --cached - doesn't checkout new copies of dependencies
pod cache clean --all # warns if current mode is `offline`; requires --force to remove offline caches
```

If you don't see any real value in this feature request, please close it, thanks for your time!

**Comment by segiddins** [comment]
I honestly don't see anyone on the team implementing this feature, sorry. But this is the sort of thing that'd be well-suited to a plugin.

**Comment by sdvigov** [comment]
pod setup
Setting up CocoaPods master repo
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
  Cloning into 'master'...
  remote: Not Found
  fatal: repository 'https://bitbucket.com/My/Fork.git/' not found
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress

Cloning into 'master'...
remote: Not Found
fatal: repository 'https://bitbucket.com/My/Fork.git/' not found
