### ISSUE TITLE
Support switching to not updating the Specs Repo by default

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#5004]
A part of feedback from GitHub: https://github.com/CocoaPods/CocoaPods/issues/4989

This requires:

- [x] Converting a `pod install` to not trigger a repo update.
- [x] Switch `--no-repo-update` to be `--repo-update`.
- [ ] When doing a `pod install` with no Specs Repo, offering advice about doing a Pod Repo Update

Roads to potentially examine:

- [ ] How we can let people know that their Specs repo is to of date ( potentially mixed with #5001 ?)
- [x] Should `pod update` trigger a repo update?

**Comment by orta** [comment]
This will need work in CocoaPods-App, as it assumes that there will be updates to the Specs repo, and provides no controls around updating the repo.

**Comment by marcelofabri** [comment]
@orta `pod install` probably should still trigger a repo update if `Podfile.lock` couldn't be satisfied, right?

**Comment by jcampbell05** [comment]
@orta when implementing the `--repo-update`functionality we need to make sure the entire tool respects it.

When implementing my plugin I found that the original `--no-repo-update` was respected in the sense that the master repo wasn't cloned. But then the Analyser would detect a Podfile hadn't declared any sources, it would default to the Specs repo and then create or fetch it.

**Comment by orta** [comment]
@marcelofabri nah, we're probably gonna go the Homebrew route

**Comment by Stunner** [comment]
With regards to:

>  Should `pod update` trigger a repo update?

My thinking is it should perform a repo update when a flag is specified (i.e. `--all`). Considering we want to lessen the amount of repo updates performed by most users in most cases, I think it best to require people to deliberately specify what they want to do. In the event `pod update` is specified without a specific repo name or the `-all` flag, usage info should be displayed.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (426/400 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:58392 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmN6-000apL-BT
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:46 +0100
Date: Mon, 14 Mar 2016 13:29:43 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457987383;
	bh=evRYkytPf4WBwlTwrxazBSbEnWOcB1ly3a9V8PwIzRs=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=h2i6qE2hPdxKSAmLN60a7TUb0Kf0FeYyrX/t124yHkRWRJmjKpkPSFYb2LXno4y/f
	 HjYiYGP5o5cYX245Dm5R2UPUNEtPFSYRzOf/MEhbtndNpuLHP7waE782snXWleK8Qy
	 kev4LRqFuSDPcUluAQFKgvs3vUKhOrCPEhoJpxWE=
