### ISSUE TITLE
Push validation fails but `spec lint` passes

### ISSUE THREAD

**Issue by ricardopereira** [CocoaPods/CocoaPods#5006]
# Report

## What did you do?

I'm trying to push a new podspec but the `pod trunk push` validation fails. I think it's a bug because the `pod spec lint` passes successfully.

## What did you expected to happen?

I read from #2712 that the `pod trunk` validation should be consistent with `pod spec lint` and it's not.

## What happened instead?

`$ pod spec lint Ably.podspec --verbose`: [Log](https://gist.github.com/ricardopereira/e33eea9122e5ebde68aa#file-ably_podspec_lint-log)

`$ pod trunk push Ably.podspec --verbose`: [Log](https://gist.github.com/mattheworiordan/590df0b0f20c55bcf8ad#file-pod-log)

## Podspec

```ruby
Pod::Spec.new do |s|
  s.name              = "Ably"
  s.version           = "0.8.0-beta.1"
  s.summary           = "iOS client for Ably"
  s.description       = <<-DESC
                        iOS client library for ably.io, the realtime messaging service, written in Objective-C and ready for Swift 2.0.
                        DESC
  s.homepage          = "https://www.ably.io"
  s.license           = { :type => 'Apache 2.0', :file => 'LICENSE' }
  s.author            = { "Ably" => "support@ably.io" }
  s.source            = { :git => "https://github.com/ably/ably-ios.git", :tag => s.version.to_s }
  s.requires_arc      = true
  s.social_media_url  = 'https://twitter.com/ablyrealtime'
  s.documentation_url = "https://www.ably.io/documentation"
  s.platform          = :ios, '8.0'
  s.requires_arc      = true
  s.source_files      = 'Source/*.{h,m}'
  s.module_map        = 'Source/Ably.modulemap'
  s.pod_target_xcconfig = { 'HEADER_SEARCH_PATHS' => '$CONFIGURATION_BUILD_DIR/SwiftWebSocket.framework/Headers' }
  s.dependency 'SwiftWebSocket', '~> 2.5'
end
```

**Comment by segiddins** [comment]
Do me a favor and try running `pod cache clean --all` and pushing again?

**Comment by ricardopereira** [comment]
@mattheworiordan ^

**Comment by ricardopereira** [comment]
@segiddins Unfortunately, the same happens.

**Comment by segiddins** [comment]
That's super weird....

**Comment by segiddins** [comment]
Is it possible you ran `pod spec lint` and `pod trunk push` with different versions of CocoaPods? The output from `pod spec lint` would suggest that it wasn't run with beta 5, as the `pod trunk push` was.

**Comment by ricardopereira** [comment]
Yes, it's possible. I will check. Thank you.

**Comment by ricardopereira** [comment]
@segiddins Confirmed! The log with failure (`pod trunk push Ably.podspec --verbose`) has beta 5.

**Comment by ricardopereira** [comment]
I'm using `0.39.0` and `pod spec lint Ably.podspec --verbose` passes.

**Comment by segiddins** [comment]
In that case it seems like everything is working normally (you might need to update your podspec for 1.0)

**Comment by ricardopereira** [comment]
@segiddins Any upgrade guide for 1.0? Is it backward compatible?

**Comment by orta** [comment]
http://blog.cocoapods.org/CocoaPods-1.0/ should cover you. I think if you run with `--verbose` you get the error messages out

**Comment by ricardopereira** [comment]
@orta Thank! Great guide.
Is it possible to go back to 0.39 (for now) and then I update the `podspec` when the 1.0 is ready in production?

**Comment by orta** [comment]
Yep

**Comment by ricardopereira** [comment]
Just for the record:
```
gem uninstall cocoapods
gem install cocoapods -v 0.39.0
```

**Comment by ricardopereira** [comment]
Well, it's working with the old version but now I have a different problem.
I will close this and open a new one.
