### ISSUE TITLE
CocoaPods Best Practices Until v1.0?

### ISSUE THREAD

**Issue by Stunner** [CocoaPods/CocoaPods#5007]
Seeing as this repository is [consuming more resources than intended for our friends at GitHub](https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193772935) and is impacting usage as a result. I think us users can help do our part by being considerate citizens and use CocoaPods in a manner that alleviates resource usage on GitHub servers, allowing others that have the need, to use CocoaPods without seeing errors.

From what I could gather:

- Use `pod install --no-repo-update` as opposed to `pod install` when installing new pods (and the master repo is already cloned)

If we could add to this thread to come up with a list of some best practices when using production versions of CocoaPods (pre v1.0) that would be great!

**Comment by orta** [comment]
The strong piece of advice is [this one](https://twitter.com/CocoaPods/status/707340665462636544):

> If you’re seeing CP Specs issues, or even if you’re not. We’d recommend running:
> cd ~/.cocoapods/repos/master && git fetch --unshallow

Which should reduce the _strain_ on the GitHub servers, as that is what is causing the majority of the trouble.

**Comment by jcampbell05** [comment]
Does the update prompt for CocoaPod users allow for custom messages ? Could we hack it for the time being to display some sort of information dialog about this ? 

```
< New CocoaPods Available >
Note to 0.39.0 User: If you’re seeing CP Specs issues, or even if you’re not. We’d recommend running:
cd ~/.cocoapods/repos/master && git fetch --unshallow
```

**Comment by segiddins** [comment]
@jcampbell05 as evidenced by https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/sources_manager.rb#L359-L390, it does not.

**Comment by jcampbell05** [comment]
Noted.

**Comment by segiddins** [comment]
Beta 6 should handle most of this with the new `--repo-update` flag, and the removal of the automatic specs repo update. Closing as this is not an actionable issue for us, but feel free to comment with further questions / tips for others.
