### ISSUE TITLE
CocoaPods + CI infrastructure 

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#5009]
from @solarce in #4989 

> Hey there, I am the infrastructure manager for Travis CI and my team is responsible for our OSX build images, which includes CocoaPods and the speed of the `pod setup` operation in each build is something we've been discussing lately.
> 
> We'd definitely love to hear more about we how could:
> 1. Improve how we do an initial install and setup of cocoapods and the specs, when we build new images for new Xcode updates, e.g. `7.3b5` yesterday. Right now we just do https://github.com/travis-infrastructure/osx-image-bootstrap/blob/master/bootstrap.sh#L73-L75
> 2. If there are some improvements we can make to the things we do at runtime, in https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/objective_c.rb and/or how our build in caching handles the specs

**Comment by orta** [comment]
As the thread is locked, we don't want to lose this sub-thread

WRT setup: I'm a bit stumped so far, I think we're still figuring that one out too

WRT Runtime:

I wonder if this can be improved via [cocoapods-check](https://github.com/square/cocoapods-check) - which would act similar to how Circle handles CocoaPods installation. [This line](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/objective_c.rb#L64) could then change to `pod check || pod install`. Which should speed up anyone already cached, and not do a repo update.

**Comment by jcampbell05** [comment]
@orta Would that work even if there is no Master Repo cloned and the source files for the Pod is in the `Pod` folder ? 

That may still trigger the Specs repo to be cloned.

**Comment by orta** [comment]
Bootstrapping the mac image adds CocoaPods, and runs setup: https://github.com/travis-infrastructure/osx-image-bootstrap/blob/master/bootstrap.sh#L73-L75 - so it would exist at runtime

**Comment by orta** [comment]
> If we run pod setup then why does it need to update at all ? It's my understanding that pod setup would ensure that the master repo is up to date.

I think you're missing the difference between creating an image, and then using the image.  We know your plugin exists, there's no need to mention it multiple times per day on our issues too :P

**Comment by jcampbell05** [comment]
I was meaning if the first step is to pull down the master repo as part of `pod setup` would it not be at HEAD ? 

So `pod install` wouldn't need to update the repo so it could be told to just skip the repo :).

Haha ;) sorry, got a bit carried away :P

**Comment by orta** [comment]
Nah, it would be at `HEAD` when the image was created, but the image is then reused for a very long time ( from the list, looks like potentially ~2 years ) - so the Specs repo would be at a different point when it's booted up, with the repo from when it was created. I don't know if there's a policy WRT updating the images, but I'd imagine they're pretty set in stone for stability reasons.

![screen shot 2016-03-09 at 2 03 54 pm](https://cloud.githubusercontent.com/assets/49038/13646953/cfbe8b8c-e5ff-11e5-82a1-c7ed4bd44a87.png)

**Comment by jcampbell05** [comment]
Ah now I grok it. Potentially with the new HTTP method on its way you could potentially update the image once in a while and use that to see if you need to update the repo on-top of `pod setup`. But again I guess it's down to the stability :)

**Comment by jcampbell05** [comment]
@orta One idea I would like to propose for this is a way to declare where the repo is stored.

If we can change it via a parameter to the same location where the pods are. Then in theory there would be a bigger hit on the first run but if you combined this with Travis's caching of the Pods folder then it would mean it could be kept up to date and still be fast.

**Comment by orta** [comment]
This was discussed here: https://github.com/CocoaPods/CocoaPods/issues/4997

**Comment by jcampbell05** [comment]
@orta I was meant choosing where the folder should be cloned to. Rather than choosing a different "mirror" to clone the master repo from.

**Comment by segiddins** [comment]
@jcampbell05 the repo directory is already configurable, go see `config.rb`.

**Comment by jcampbell05** [comment]
@segiddins Is the config configurable via the command line ?

**Comment by jcampbell05** [comment]
Cool saw that you can use `CP_REPOS_DIR` Env, will see if this can speed up my Travis CI Builds.
