### ISSUE TITLE
Hardcoded ansi color codes displayed when --no-ansi is passed on the command line

### ISSUE THREAD

**Issue by samdmarshall** [CocoaPods/CocoaPods#5013]
# Report

## What did you do?

Ran `pod install --no-ansi`

## What did you expected to happen?

No text with ansi color codes will be displayed.

## What happened instead?

I get a warning message that uses ansi color codes to inform me to update my `~/.profile` with the text encoding of UTF-8.

The lines in question appear to be hardcoded to use color codes: https://github.com/CocoaPods/CocoaPods/blob/master/bin/pod#L3-L11

**Comment by alloy** [comment]
_Could_ check `ARGV` for `--no-ansi`, but just removing it completely seems fine to me as well.
