### ISSUE TITLE
Removing use_frameworks does not remove Emed Pods Frameworks build phase

### ISSUE THREAD

**Issue by mtitolo** [CocoaPods/CocoaPods#5015]
* [:rainbow:] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Removed `use_frameworks` from my Podfile and re-ran `pod install`

## What did you expected to happen?
All libraries would be switched to the old static library system and the Embed Pods Frameworks build phase removed.

## What happened instead?
The Embed Pods Frameworks build phase was not removed.

## Podfile

```ruby
platform :ios, '9.0'

target 'FrameworksIntegration' do 
	pod 'CocoaLumberjack'
end
```

[Sample project](https://github.com/mtitolo/FrameworksIntegration/tree/48794d592b85245b9c9c08597cbaf09badb36f6f)

**Comment by segiddins** [comment]
The embed pods frameworks build phase is intentionally added to all targets, not only those that use frameworks.

**Comment by segiddins** [comment]
(You may note that the embed frameworks phase doesn't actually install any frameworks in your example project)

**Comment by mtitolo** [comment]
@segiddins yeah but it's still weird to see even though I took out frameworks...?

**Comment by segiddins** [comment]
It's necessary because you could potentially have dynamic vendored frameworks, and this reduces churn the in user project.

**Comment by mtitolo** [comment]
Was this changed between beta3 and beta4? I didn't used to see this and it appears to have fixed the other issue I ran into

**Comment by segiddins** [comment]
No, it has not changed since beta one as far as I'm aware.

**Comment by mtitolo** [comment]
Well something changed between beta3 and beta4 because I didn't see this before and now I can't reproduce the other bug I found ¯\_(ツ)_/¯
