### ISSUE TITLE
Don't shallow clone specs repos

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#5016]
- [x] Don't shallow clone specs repositories
- [x] Try and convert shallow clones to deep clones
  - [x] `--unshallow` or `rm && clone`? (@vmg / @mhagger I'd appreciate feedback on this one)

**Comment by Coeur** [comment]
Could that be linked to this kind of answers on Stackoverflow: http://stackoverflow.com/a/33699136/1033581
People are encouraging *--depth=1* when in China. Otherwise cloning takes hours.

**Comment by segiddins** [comment]
Shallow clones make up a large portion of the issue with serving the master specs repo, so we _cannot_ officially support shallow cloning the master specs repo any more -- it would be incredibly unfair to GitHub.

**Comment by vmg** [comment]
> People are encouraging --depth=1 when in China. Otherwise cloning takes hours.

Unfortunately, and because of a bug in Git itself that we're investigating upstream, a `--depth=1` clone in a repository like CocoaPods will end up downloading *several times more data over time* (as you keep fetching on top of the shallow clone) than a full clone would take. So unshallowing the repository is better on the long run for everybody, even those with limited internet connections.

> `--unshallow` or `rm && clone`?

Both should have the same effect. I would lean towards `rm` because that's going to work 100% of the time. :smile: (not that I've seen `--unshallow` fail in practice, but whatevs)

**Comment by AntiMoron** [comment]
Hey! I'm angry on the sight of this issue.
As @Coeur said, users like me in China need to clone Specs with ```--depth=1```. But you say it would be unfair to all the GitHub users. I totally disagree. 
You can make it ```--unshallow``` by default but you shouldn't force people git clone --unshallow.
Why there's no such command flag to give people more options?

**Comment by AntiMoron** [comment]
You guys should already know that there's really huge amount of commits. Deep cloning definitely takes lots of time in many countries not only China, etc. Apis should be powerful and flexible but don't force and push users plz.

**Comment by benasher44** [comment]
Hi @AntiMoron! Thanks for your feedback! We don't provide an option for this in CocoaPods because of the issues experienced by GitHub users, which is explained in detail by a GitHub engineer [here](https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193772935). Have a great day!

**Comment by AntiMoron** [comment]
@benasher44  OIC, but the problem hasn't been solved. I can hardly clone Specs to my pc...
Has the Cocoapods team planning other ways to improve fetching performance such as building up a CDN service just like what 'npm' do?

**Comment by segiddins** [comment]
The team is open to proposals for other ways of storing specs metadata for use in dependency resolution, but given everyone works on cocoapods in their free time, it is unlikely any of us will be able to undertake such a substantial project.
