### ISSUE TITLE
"pod lib create" creates an invalid Podfile, according to itself

### ISSUE THREAD

**Issue by danielrhodes** [CocoaPods/CocoaPods#5023]
# Report

CocoaPods throws the following error after creating a Pod, and then continues.

```ruby
[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `Toolbox_Example`..

 #  from /<path>/Toolbox/Example/Podfile:4
 #  -------------------------------------------
 #
 >  target 'Toolbox_Example', :exclusive => true do
 #    pod 'Toolbox', :path => '../'
 #  -------------------------------------------
```

Then if you fix this problem by removing ```exclusive => true``` (on a brand new Pod) and run `pod install` on the `Example` project, you get the following error:

```bash
> pod install
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `Toolbox` from `../`
[!] The `Toolbox` pod failed to validate due to 1 error:
    - WARN  | summary: The summary is not meaningful.
    - ERROR | description: The description is empty.
```

I guess the above means that I need to write the spec file first before starting a project? That can't be right.

## What did you do?

```bash
> pod lib create <podname>
```

and
```bash
> pod install
```

## Versions
```bash
> pod --version
1.0.0.beta.5
> ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

**Comment by orta** [comment]
Thanks!

This is known, we'll be switching it to 1.0 syntax when 1.0 gets out of beta - https://github.com/CocoaPods/pod-template/pull/144
