### ISSUE TITLE
Adding a progress indicator for `Updating spec repositories`

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#5027]
## What did you do?

Run `pod install`, `pod update` or `pod try`

## What did you expected to happen?

Give progress of how much is being downloaded when cloning or pulling repositories. Especially the `Updating spec repositories` step.

## What happened instead?

It takes forever to complete step `Updating spec repositories`. People think it's a bug and they go to undesirable solutions (shallow cloning, etc.).
https://stackoverflow.com/questions/34522708/cocoapods-installation-stuck-on-updating-local-specs-repositories
https://stackoverflow.com/questions/25109629/cocoapods-pod-update-and-pod-install-takes-forever
https://stackoverflow.com/questions/23755974/cocoapods-pod-install-takes-forever
https://stackoverflow.com/questions/21680573/cocoapods-setup-stuck-on-pod-setup-command-on-terminal
https://stackoverflow.com/questions/21022638/pod-install-is-staying-on-setting-up-cocoapods-master-repo

**Comment by segiddins** [comment]
You should see progress if you run with --verbose. In general, I don't like showing progress bars, as its usually just noise in a CLI environment.

**Comment by orta** [comment]
I'm a nope on this one too, NPM does this https://github.com/npm/npm/issues/11283 - and it considerably affects the time to do it's work.

```
$ rm -r node_modules
$ npm set progress=false
$ time npm install
npm install  19.91s user 2.66s system 71% cpu 31.667 total

$ rm -r node_modules
$ npm set progress=true
$ time npm install
npm install  33.26s user 3.19s system 74% cpu 48.733 total
```

**Comment by Coeur** [comment]
There is no progress given with `--verbose`. It will still stuck for plenty of minutes on:

    Updating spec repo `master`
      $ /usr/bin/git pull --ff-only

**Comment by Coeur** [comment]
@orta, what about adding an option like `--progress` that would activate the feature? Or activating the progress feature just for `--verbose`?

**Comment by orta** [comment]
Someone could write a plugin that swizzles the function that starts the specs repo update either with `git clone --progress` or tries to wrap that in a plugin, but unless someone in the core team cares strongly enough to build it, it probably won't be coming from us.
