### ISSUE TITLE
pod spec lint cannot find my LICENSE file

### ISSUE THREAD

**Issue by mmower** [CocoaPods/CocoaPods#503]
I'm trying to get my first podspec working and, no matter what I try, pod spec lint refuses to find my LICENSE file.

It's at the same project level as the podspec (but I've also tried putting it in the with the sources). I've tried using the default (no :file) behaviour as well as specifiying :file => "LICENSE". I've also tried it as LICENSE.md to match other working pods I found.

As far as I can see the lint provides no useful information about _why_ it can't find it, esp. since the given path is in /tmp so I'm really trying to figure out why it's not being copied in the first place.

Any help would be much appreciated.

Kind regards,

Matt

Shaddam:Gen matt$ pod spec lint Gen.podspec

 -> Gen
          ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 0.13.0
        Ruby : ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.1.0]
    RubyGems : 1.8.24
        Host : Mac OS X 10.8.1 (12B19)
       Xcode : 4.4.1 (4F1003)
Ruby lib dir : /Volumes/Corrino/matt/.rvm/rubies/ruby-1.9.3-p194/lib
Repositories : local - /Volumes/Corrino/matt/Projects/cocoapodspecs @ 5fe14089e06c449e836c137d9b484ce559d39ccc
               master - https://github.com/CocoaPods/Specs.git @ 96b627752ea05ff9b33c24dc7dfb21b310e56393
```
### Error

```
No such file or directory - /tmp/CocoaPods/Lint/Pods/Gen/LICENSE.md
/Volumes/Corrino/matt/.rvm/gems/ruby-1.9.3-p194/gems/cocoapods-0.13.0/lib/cocoapods/local_pod.rb:318:in `read'
/Volumes/Corrino/matt/.rvm/gems/ruby-1.9.3-p194/gems/cocoapods-0.13.0/lib/cocoapods/local_pod.rb:318:in `license_text'


```

**Comment by patrickjmcgoldrick** [comment]
I think the solution is to change the license filename to 'BSD'.
