### ISSUE TITLE
"pod search ReactiveCocoa" fails

### ISSUE THREAD

**Issue by mishagray** [CocoaPods/CocoaPods#5031]
# Report

## What did you do?
'''pod search ReactiveCocoa'''
## What did you expected to happen?

Find the ReactiveCocoa pod spec information.

## What happened instead?

Lots of other pods are listed that have that name as part of the string.  Except the ReactiveCocoa pod.   Which is weird.  Works on the website search.  But not the command line.

## Podfile

N/A  Not related to a pod file!

**Comment by segiddins** [comment]
Please paste the output of the search that you're seeing?

**Comment by mishagray** [comment]
-> ReactiveCocoaApply (0.2.4)
   ReactiveCocoa Singal and SignalProducer extensions for RAC4 for applying operators similar to |> from RAC3.
   pod 'ReactiveCocoaApply', '~> 0.2.4'
   - Homepage: https://github.com/nikita-leonov/ReactiveCocoaApply
   - Source:   https://github.com/nikita-leonov/ReactiveCocoaApply.git
   - Versions: 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.0 [master repo]

-> ReactiveCocoaLayout (0.4)
   Reactive layout framework built on top of ReactiveCocoa.
   pod 'ReactiveCocoaLayout', '~> 0.4'
   - Homepage: https://github.com/ReactiveCocoa/ReactiveCocoaLayout
   - Source:   https://github.com/ReactiveCocoa/ReactiveCocoaLayout.git
   - Versions: 0.4, 0.3.2, 0.3.1, 0.3 [master repo]

-> ALReactiveCocoaExtension (3.0.2)
   Contains replacements for the RAC and RACObserve macros in Swift and adds multiple cast methods.
   pod 'ALReactiveCocoaExtension', '~> 3.0.2'
   - Homepage: https://github.com/AvdLee/ALReactiveCocoaExtension
   - Source:   https://github.com/AvdLee/ALReactiveCocoaExtension.git
   - Versions: 3.0.2, 3.0.1, 3.0.0, 2.1.0, 2.0.0, 1.0.2, 1.0.1, 1.0.0 [master repo]

-> XLReactiveCocoaExtensions (2.0.6)
   The missing part of ReactiveCocoa for development
   pod 'XLReactiveCocoaExtensions', '~> 2.0.6'
   - Homepage: https://github.com/xareelee/XLReactiveCocoaExtensions
   - Source:   https://github.com/xareelee/XLReactiveCocoaExtensions.git
   - Versions: 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.1, 2.0.0 [master repo]
   - Subspecs:
     - XLReactiveCocoaExtensions/Core (2.0.6)
     - XLReactiveCocoaExtensions/UIKit (2.0.6)

-> EPSReactiveCocoaExtensions (0.2.0)
   Extensions to ReactiveCocoa classes.
   pod 'EPSReactiveCocoaExtensions', '~> 0.2.0'
   - Homepage: https://github.com/ElectricPeelSoftware/EPSReactiveCocoaExtensions
   - Source:   https://github.com/ElectricPeelSoftware/EPSReactiveCocoaExtensions.git
   - Versions: 0.2.0, 0.1.0 [master repo]

-> Parse-ReactiveCocoa (0.1.1)
   Extensions to use Parse with ReactiveCocoa
   pod 'Parse-ReactiveCocoa', '~> 0.1.1'
   - Homepage: https://github.com/gertjanleemans/Parse-ReactiveCocoa
   - Source:   https://github.com/gertjanleemans/Parse-Reactivecocoa.git
   - Versions: 0.1.1, 0.1 [master repo]

-> Expecta+ReactiveCocoa (0.2.0)
   Expecta matchers for ReactiveCocoa.
   pod 'Expecta+ReactiveCocoa', '~> 0.2.0'
   - Homepage: https://github.com/kylef/Expecta-ReactiveCocoa
   - Source:   https://github.com/kylef/Expecta-ReactiveCocoa.git
   - Versions: 0.2.0, 0.1.0 [master repo]

-> ReduxKitReactiveCocoa (0.1.0)
   ReactiveCocoa bindings for ReduxKit
   pod 'ReduxKitReactiveCocoa', '~> 0.1.0'
   - Homepage: https://github.com/ReduxKit/ReduxKitReactiveCocoa
   - Source:   https://github.com/ReduxKit/ReduxKitReactiveCocoa.git
   - Versions: 0.1.0 [master repo]

-> Overcoat+ReactiveCocoa (4.0.0-beta.2)
   Overcoat is a small but powerful library that makes creating REST clients simple and fun.
   pod 'Overcoat+ReactiveCocoa', '~> 4.0.0-beta.2'
   - Homepage: https://github.com/overcoat/Overcoat
   - Source:   https://github.com/overcoat/Overcoat.git
   - Versions: 4.0.0-beta.2 [master repo]

-> AFNetworking-ReactiveCocoa (0.0.2)
   Make AFNetworking reactive.
   pod 'AFNetworking-ReactiveCocoa', '~> 0.0.2'
   - Homepage: https://github.com/uasi/AFNetworking-ReactiveCocoa
   - Source:   https://github.com/uasi/AFNetworking-ReactiveCocoa.git
   - Versions: 0.0.2, 0.0.1 [master repo]

-> UIGestureRecognizer+ReactiveCocoa (0.1.0)
   Handle gestures with ReactiveCocoa! No more ugly selectors!
   pod 'UIGestureRecognizer+ReactiveCocoa', '~> 0.1.0'
   - Homepage: https://github.com/kaiinui/UIGestureRecognizer-RACExtension
   - Source:   https://github.com/kaiinui/UIGestureRecognizer-RACExtension.git
   - Versions: 0.1.0 [master repo]

-> DCHMVVMKit (0.0.5)
   A MVVM develop kit for Objective-C.
   pod 'DCHMVVMKit', '~> 0.0.5'
   - Homepage: https://github.com/seraphcxl/DCHMVVMKit
   - Source:   https://github.com/seraphcxl/DCHMVVMKit.git
   - Versions: 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1 [master repo]

-> ETTextField-TestHelper (0.0.1)
   UITextField category with convenience methods for testing.
   pod 'ETTextField-TestHelper', '~> 0.0.1'
   - Homepage: https://github.com/esttorhe/ETTextField-TestHelper
   - Source:   https://github.com/esttorhe/ETTextField-TestHelper.git
   - Versions: 0.0.1 [master repo]

-> HaidoraBrick (0.0.1)
   HaidoraBrick.
   pod 'HaidoraBrick', '~> 0.0.1'
   - Homepage: https://github.com/Haidora/HaidoraBrick
   - Source:   https://github.com/Haidora/HaidoraBrick.git
   - Versions: 0.0.1 [master repo]
   - Subspecs:
     - HaidoraBrick/Core (0.0.1)
     - HaidoraBrick/Extension (0.0.1)
     - HaidoraBrick/Extension/Navigation (0.0.1)

-> MEReactiveKit (1.0.11)
   A collection of classes that extend the UIKit framework, built on top of ReactiveCocoa.
   pod 'MEReactiveKit', '~> 1.0.11'
   - Homepage: https://github.com/TeamMaestro/MEReactiveKit
   - Source:   https://github.com/TeamMaestro/MEReactiveKit.git
   - Versions: 1.0.11, 1.0.8, 1.0.6 [master repo]

-> MERTwitterKit (0.1.0)
   A Twitter 1.1 API wrapper, built on top of AFNetworking and ReactiveCocoa. Compatible with iOS, 7.0+
   pod 'MERTwitterKit', '~> 0.1.0'
   - Homepage: https://github.com/MaestroElearning/MERTwitterKit
   - Source:   https://github.com/MaestroElearning/MERTwitterKit.git
   - Versions: 0.1.0 [master repo]

-> MMPReactiveCoreLocation (0.6.2)
   A reactive CoreLocation wrapper for use with ReactiveCocoa
   pod 'MMPReactiveCoreLocation', '~> 0.6.2'
   - Homepage: https://github.com/mpurbo/MMPReactiveCoreLocation
   - Source:   https://github.com/mpurbo/MMPReactiveCoreLocation.git
   - Versions: 0.6.2, 0.6.1, 0.6.0, 0.5.2, 0.5.1, 0.5.0, 0.4.1, 0.4.0, 0.3.0, 0.2.0, 0.1.1 [master repo]

-> Moya-ModelMapper (1.2.0)
   ModelMapper bindings for Moya.
   pod 'Moya-ModelMapper', '~> 1.2.0'
   - Homepage: https://github.com/sunshinejr/Moya-ModelMapper
   - Source:   https://github.com/sunshinejr/Moya-ModelMapper.git
   - Versions: 1.2.0, 1.1.1, 1.1.0, 1.0.0 [master repo]
   - Subspecs:
     - Moya-ModelMapper/Core (1.2.0)
     - Moya-ModelMapper/RxSwift (1.2.0)
     - Moya-ModelMapper/ReactiveCocoa (1.2.0)

-> NPictureSelectArrayView (0.0.2)
   select picture and show as cells, column and total number can be change, you can delete, replace image
   pod 'NPictureSelectArrayView', '~> 0.0.2'
   - Homepage: http://nagiyan.github.io/NPictureSelectArrayView/
   - Source:   https://github.com/NagiYan/NPictureSelectArrayView.git
   - Versions: 0.0.2, 0.0.1 [master repo]

-> PXRotatorView (0.5.8)
   An auto rotating carousel view based on iCarousel and ReactiveCocoa
   pod 'PXRotatorView', '~> 0.5.8'
   - Homepage: https://github.com/drinking/PXRotatorView
   - Source:   https://github.com/drinking/PXRotatorView.git
   - Versions: 0.5.8, 0.5.7, 0.5.4, 0.5.3, 0.5.2 [master repo]

-> ReactiveCache (0.1.0)
   Cache for ReactiveCocoa.
   pod 'ReactiveCache', '~> 0.1.0'
   - Homepage: https://github.com/haifengkao/ReactiveCache
   - Source:   https://github.com/haifengkao/ReactiveCache.git
   - Versions: 0.1.0 [master repo]

-> ReactiveEstimote (0.1.1)
   ReactiveCocoa extensions for the Estimote SDK.
   pod 'ReactiveEstimote', '~> 0.1.1'
   - Homepage: https://github.com/eliperkins/ReactiveEstimote
   - Source:   https://github.com/eliperkins/ReactiveEstimote.git
   - Versions: 0.1.1, 0.1.0 [master repo]

-> ReactiveNetworking (1.5.1)
   Mixes the great AFNetworking with ReactiveCocoa.
   pod 'ReactiveNetworking', '~> 1.5.1'
   - Homepage: https://github.com/plu/ReactiveNetworking
   - Source:   https://github.com/plu/ReactiveNetworking.git
   - Versions: 1.5.1, 1.5.0, 1.4.0, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.0, 1.1.0, 1.0.3, 1.0.2, 1.0.1, 1.0.0 [master repo]
   - Subspecs:
     - ReactiveNetworking/Core (1.5.1)
     - ReactiveNetworking/Dependencies (1.5.1)
     - ReactiveNetworking/Testing (1.5.1)

-> ReactiveViewModel (0.3)
   Model-View-ViewModel, using ReactiveCocoa.
   pod 'ReactiveViewModel', '~> 0.3'
   - Homepage: https://github.com/ReactiveCocoa/ReactiveViewModel
   - Source:   https://github.com/ReactiveCocoa/ReactiveViewModel.git
   - Versions: 0.3, 0.2, 0.1.1 [master repo]

-> RESTClient (0.1.0)
   An iOS REST Client that is based on MVVM using ReactiveCocoa
   pod 'RESTClient', '~> 0.1.0'
   - Homepage: https://github.com/abaraka/RESTClient
   - Source:   https://github.com/abaraka/RESTClient.git
   - Versions: 0.1.0 [master repo]

-> RxViewModel (3.0.1)
   `RxViewModel` is the marriage between `MVVM` and `Rx` extensions. A blatant «imitation» of `ReactiveViewModel` using `RxCocoa`.
   pod 'RxViewModel', '~> 3.0.1'
   - Homepage: https://github.com/RxSwiftCommunity/RxViewModel
   - Source:   https://github.com/RxSwiftCommunity/RxViewModel.git
   - Versions: 3.0.1, 3.0.0, 2.4.1, 2.4.0, 2.3.1, 2.3.0, 2.2.0, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1.0, 2.0.0, 1.1.0, 1.0.0, 0.2.1 [master repo]

-> XPRACSignal (1.1.3)
   一组非常有用的ReactiveCocoa工具集.
   pod 'XPRACSignal', '~> 1.1.3'
   - Homepage: https://coding.net/u/huangxinping/p/XPRACSignal/git
   - Source:   https://git.coding.net/huangxinping/XPRACSignal.git
   - Versions: 1.1.3, 1.1.1, 1.0.1 [master repo]

**Comment by segiddins** [comment]
@manuyavuz care to look into this?

**Comment by manuyavuz** [comment]
@mishagray, could you try `pod search --simple ReactiveCocoa` and share the output?

**Comment by mishagray** [comment]
that works better:

-> ReactiveCocoa (4.0.4-alpha-4)
   A framework for composing and transforming streams of values.
   pod 'ReactiveCocoa', '~> 4.0.4-alpha-4'
   - Homepage: https://github.com/ReactiveCocoa/ReactiveCocoa
   - Source:   https://github.com/ReactiveCocoa/ReactiveCocoa.git
   - Versions: 4.0.4-alpha-4, 4.0.4-alpha-1, 4.0.3-alpha-3, 4.0.3-alpha-1, 4.0.2-alpha-3, 4.0.2-alpha-1, 4.0.1, 4.0.1-alpha-3, 4.0.1-alpha-1, 4.0.0, 4.0.0-alpha-3, 4.0.0-alpha-2, 4.0.0-alpha-1, 4.0.0-RC.2, 4.0.0-RC.1, 3.0.0, 3.0.0-swift2, 3.0-beta.9, 3.0-beta.6, 3.0-alpha.3, 3.0.0-alpha.1, 3.0-RC.1, 2.5, 2.4.7, 2.4.6, 2.4.5, 2.4.4, 2.4.2, 2.3.1, 2.3, 2.2.4, 2.2.3, 2.2.2, 2.2, 2.1.8, 2.1.7, 2.1.6, 2.1.5, 2.1.4, 2.1.3, 2.1.2, 2.1.1, 2.1, 2.0, 1.9.7, 1.9.6, 1.9.5, 1.9.4, 1.8.1, 1.8.0, 1.7.2, 1.7.1, 1.7.0, 1.6.0, 1.5.0, 1.4.0, 1.3.1, 1.0.0, 0.17.1, 0.16.1, 0.13.1, 0.12.0, 0.10.0, 0.9.0, 0.8.0, 0.6.0, 0.5.0, 0.0.1 [master repo]
   - Subspecs:
     - ReactiveCocoa/no-arc (4.0.4-alpha-4)
     - ReactiveCocoa/Core (4.0.4-alpha-4)
     - ReactiveCocoa/UI (4.0.4-alpha-4)

-> ReactiveCocoaApply (0.2.4)
   ReactiveCocoa Singal and SignalProducer extensions for RAC4 for applying operators similar to |> from RAC3.
   pod 'ReactiveCocoaApply', '~> 0.2.4'
   - Homepage: https://github.com/nikita-leonov/ReactiveCocoaApply
   - Source:   https://github.com/nikita-leonov/ReactiveCocoaApply.git
   - Versions: 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.0 [master repo]

-> ReactiveCocoaLayout (0.4)
   Reactive layout framework built on top of ReactiveCocoa.
   pod 'ReactiveCocoaLayout', '~> 0.4'
   - Homepage: https://github.com/ReactiveCocoa/ReactiveCocoaLayout
   - Source:   https://github.com/ReactiveCocoa/ReactiveCocoaLayout.git
   - Versions: 0.4, 0.3.2, 0.3.1, 0.3 [master repo]

-> ALReactiveCocoaExtension (3.0.2)
   Contains replacements for the RAC and RACObserve macros in Swift and adds multiple cast methods.
   pod 'ALReactiveCocoaExtension', '~> 3.0.2'
   - Homepage: https://github.com/AvdLee/ALReactiveCocoaExtension
   - Source:   https://github.com/AvdLee/ALReactiveCocoaExtension.git
   - Versions: 3.0.2, 3.0.1, 3.0.0, 2.1.0, 2.0.0, 1.0.2, 1.0.1, 1.0.0 [master repo]

-> XLReactiveCocoaExtensions (2.0.6)
   The missing part of ReactiveCocoa for development
   pod 'XLReactiveCocoaExtensions', '~> 2.0.6'
   - Homepage: https://github.com/xareelee/XLReactiveCocoaExtensions
   - Source:   https://github.com/xareelee/XLReactiveCocoaExtensions.git
   - Versions: 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.1, 2.0.0 [master repo]
   - Subspecs:
     - XLReactiveCocoaExtensions/Core (2.0.6)
     - XLReactiveCocoaExtensions/UIKit (2.0.6)

-> EPSReactiveCocoaExtensions (0.2.0)
   Extensions to ReactiveCocoa classes.
   pod 'EPSReactiveCocoaExtensions', '~> 0.2.0'
   - Homepage: https://github.com/ElectricPeelSoftware/EPSReactiveCocoaExtensions
   - Source:   https://github.com/ElectricPeelSoftware/EPSReactiveCocoaExtensions.git
   - Versions: 0.2.0, 0.1.0 [master repo]

-> Parse-ReactiveCocoa (0.1.1)
   Extensions to use Parse with ReactiveCocoa
   pod 'Parse-ReactiveCocoa', '~> 0.1.1'
   - Homepage: https://github.com/gertjanleemans/Parse-ReactiveCocoa
   - Source:   https://github.com/gertjanleemans/Parse-Reactivecocoa.git
   - Versions: 0.1.1, 0.1 [master repo]

-> Expecta+ReactiveCocoa (0.2.0)
   Expecta matchers for ReactiveCocoa.
   pod 'Expecta+ReactiveCocoa', '~> 0.2.0'
   - Homepage: https://github.com/kylef/Expecta-ReactiveCocoa
   - Source:   https://github.com/kylef/Expecta-ReactiveCocoa.git
   - Versions: 0.2.0, 0.1.0 [master repo]

-> ReduxKitReactiveCocoa (0.1.0)
   ReactiveCocoa bindings for ReduxKit
   pod 'ReduxKitReactiveCocoa', '~> 0.1.0'
   - Homepage: https://github.com/ReduxKit/ReduxKitReactiveCocoa
   - Source:   https://github.com/ReduxKit/ReduxKitReactiveCocoa.git
   - Versions: 0.1.0 [master repo]

-> Overcoat+ReactiveCocoa (4.0.0-beta.2)
   Overcoat is a small but powerful library that makes creating REST clients simple and fun.
   pod 'Overcoat+ReactiveCocoa', '~> 4.0.0-beta.2'
   - Homepage: https://github.com/overcoat/Overcoat
   - Source:   https://github.com/overcoat/Overcoat.git
   - Versions: 4.0.0-beta.2 [master repo]

-> AFNetworking-ReactiveCocoa (0.0.2)
   Make AFNetworking reactive.
   pod 'AFNetworking-ReactiveCocoa', '~> 0.0.2'
   - Homepage: https://github.com/uasi/AFNetworking-ReactiveCocoa
   - Source:   https://github.com/uasi/AFNetworking-ReactiveCocoa.git
   - Versions: 0.0.2, 0.0.1 [master repo]

-> UIGestureRecognizer+ReactiveCocoa (0.1.0)
   Handle gestures with ReactiveCocoa! No more ugly selectors!
   pod 'UIGestureRecognizer+ReactiveCocoa', '~> 0.1.0'
   - Homepage: https://github.com/kaiinui/UIGestureRecognizer-RACExtension
   - Source:   https://github.com/kaiinui/UIGestureRecognizer-RACExtension.git
   - Versions: 0.1.0 [master repo]

**Comment by orta** [comment]
Sounds like it's not prioritizing exact matches?

**Comment by manuyavuz** [comment]
Seems like there exist a problem during index generation, I'll check it out.

@mishagray, thanks for the report!

**Comment by manuyavuz** [comment]
@mishagray, could you share the file in the following path:

```
~/Library/Caches/CocoaPods/search_index.json
```

Regenerating the index fixed the issue in my machine, previous index was having the above problem. So I couldn't reproduce the issue.

Could you also try `pod search ReactiveCocoa` again after deleting the above file, and check if the issue is resolved for you?

**Comment by mishagray** [comment]
Here is copy of the 'bad' index:
https://www.dropbox.com/s/ac9oxdlxxjxfces/search_index.json.zip?dl=0

After deleting it and re-running (using 1.0.0.beta.5) and the issue went away.
