### ISSUE TITLE
Specs using resource_bundle broken on CocoaPods 1.0.0.beta.6

### ISSUE THREAD

**Issue by danielgalasko** [CocoaPods/CocoaPods#5034]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

The [documentation](http://guides.cocoapods.org/syntax/podspec.html#resource_bundles) for the usage of resource bundles suggests that Spec files use a format like so:

```ruby
spec.resource_bundles = {
    'MapBox' => ['MapView/Map/Resources/*.png'],
    'OtherResources' => ['MapView/Map/OtherResources/*.png']
  }
```

When this declaration is done cocoapods generates a new target for the copy resources phase of the bundle. It looks like the path for this bundle is incorrect as it now ends up in `Pod/Pod/Pod.bundle` where the expected path from the copy script phase is `Pod/Pod.bundle`.

Changing the spec to use `spec.resource = 'Path/To/Bundle.bundle'` resolves the issue and removes the extra target.

## What did you do?

Created a simple podfile under CocoaPods 1.0.0.beta.2 -> 1.0.0.beta.6 using a Spec that uses `resource_bundle`. Ran pod install and then attempt to build the resulting project. 

## What did you expected to happen?

The project to build and a happy simulator to open up with the app running.

## What happened instead?

The copy bundle resources phase fails to identify the bundle and the bundle is also not present in the project structure.

It seems as though I should find a `.bundle` under the specific pods directory but instead I see a folder structure of `POD_NAME/Assets/ios/{Resources that should be in a bundle but are now clearly visible}`

Interestingly enough Specs that use the `resources` tag and specify bundles work normally. As an example the [GoogleAppIndexing](https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleAppIndexing/2.0.3/GoogleAppIndexing.podspec.json) pod works fine and one will see the `.bundle` in the correct location.

My suspicion is that this is a regression of #4762 ?

## Podfile

```ruby
use_frameworks!

target 'NYTPhotoViewerFun' do
	pod 'NYTPhotoViewer'
end
```

## Working Spec

I forked 'NYTPhotoViewer' [https://github.com/danielgalasko/NYTPhotoViewer/blob/danielgalasko-cocoapods-1.0.0/NYTPhotoViewer.podspec#L19] and this works

## Failing Spec

The original Spec that was working on CocoaPods 0.39.0 can be found [here](https://github.com/NYTimes/NYTPhotoViewer/blob/develop/NYTPhotoViewer.podspec#L19)

**Comment by danielgalasko** [comment]
Could also be related to #4963

**Comment by lucacorti** [comment]
I confirm I have the same issue, this used to work on beta5.

**Comment by diejmon** [comment]
I've been able to fix this issue locally by modifing bundle pod target, where I change CONFIGURATION_BUILD_DIR from: $CONFIGURATION_BUILD_DIR/BUNDLE_NAME to $CONFIGURATION_BUILD_DIR

**Comment by appveng3r** [comment]
I have the same Issue. The bundle is in the wrong location it's in $CONFIGURATION_BUILD_DIR/TARGET_NAME/TARGET_NAME/BUNDLE_NAME instead of $CONFIGURATION_BUILD_DIR/TARGET_NAME/BUNDLE_NAME

**Comment by tkuichooseyou** [comment]
@appveng3r @diejmon can you explain how you modify the bundle pod target? Is it supposed to be inside the `Pods/Target Support Files/Pods-TARGET_NAME/Pods-TARGET_NAME-resources.sh` file?

**Comment by appveng3r** [comment]
@tkuichooseyou I changed in Pod-Target-resource.sh one line from
`install_resource "$CONFIGURATION_BUILD_DIR/gujemsiossdk/gujemsiossdk.bundle"` to `install_resource "$CONFIGURATION_BUILD_DIR/gujemsiossdk/gujemsiossdk/gujemsiossdk.bundle"` to make it work.

**Comment by danielgalasko** [comment]
My suspicion is that this may be a result of Specs passing actual file extensions inside of the bundle declaration:

```ruby
    ss.ios.resource_bundle = { s.name => ['Pod/Assets/ios/*.png'] }
```

Whereas simply passing the bundle path like so

```ruby
    ss.ios.resource_bundle = { s.name => ['Path/To/Bundle/MYBundle.bundle'] }
```

Will try and see if I can get a spec working with the latter

**Comment by danielgalasko** [comment]
My bad, I see the [documentation](https://guides.cocoapods.org/syntax/podspec.html) explicitly states it should be done this way i.e. `ss.ios.resource_bundle = { s.name => ['Pod/Assets/ios/*.png'] }`

**Comment by danielgalasko** [comment]
Looks like the culprit is using `resource_bundle`. I went ahead and changed the pod spec to use `resource` and the project builds. See the new Spec [here](https://github.com/danielgalasko/NYTPhotoViewer/blob/danielgalasko-cocoapods-1.0.0/NYTPhotoViewer.podspec#L19)

**Comment by danieljimenez** [comment]
Ah, having the same issue with beta 6. Reverted to beta 5 for now.

**Comment by danieljimenez** [comment]
Documentation recommends using `resource_bundles` instead of `resources`:

> We strongly recommend library developers to adopt resource bundles as there can be name collisions using the resources attribute.

**Comment by fuxx** [comment]
Having the same issue since beta6. beta5 works fine.

**Comment by danieljimenez** [comment]
Here is my workaround for beta 6:

```
# Hax around bug in Cocoapods 
resource_bundles = {
'Resources' => [
  'AppServices/ios/FFThemeKit/FFThemeKit/*.{png,storyboard,xib,otf}',
  'AppServices/ios/FFThemeKit/FFThemeKit/Settings.bundle/**/*',
  ]
}

s.ios.resource_bundle = resource_bundles
s.watchos.resource_bundle = resource_bundles
```

**Comment by fuxx** [comment]
I am using separated bundles, i think the workaround does not fit for that. 
`s.resource_bundles = {
    'C24CoreUI' => ['Pod/Assets/UI/**/*.storyboard', 'Pod/Assets/UI/**/*.xib', 'Pod/Assets/UI/Images/**/*'],
    'C24CorePlist' => ['Pod/Assets/Plist/**/*.plist'],
    'C24CoreSQLiteDB' => ['Pod/Assets/Database/**/*.sqlite'],
    'C24CoreJSON' => ['Pod/Assets/JSON/**/*.json'],
    'C24CoreHTML' => ['Pod/Assets/HTML/**/*'],
  }`

**Comment by danieljimenez** [comment]
Should still work, essentially it works when set at the platform level but not above that. You just have to make it a variable and pass that in at the platform level.

**Comment by fuxx** [comment]
Thank you for your answer, unfortunately not. Looks like i have to wait for beta7 :)

**Comment by danieljimenez** [comment]
Sorry, looks like I faked myself out, my workaround did not work.

**Comment by exherb** [comment]
Temporary workaround: Change every

` install_resource "$CONFIGURATION_BUILD_DIR/{LibName}/{BundleName}.bundle"` to ` install_resource "$CONFIGURATION_BUILD_DIR/{LibName}/{LibName}/{BundleName}.bundle"`

in Pods/Pods-{ProductName}-resources.sh

**Comment by catarino** [comment]
this -> http://stackoverflow.com/questions/28080318/run-custom-shell-script-copy-pods-resources-error

fixed it for me.

**Comment by tkuichooseyou** [comment]
@exherb I tried changing my Pods-{ProductName}-resources.sh file to that but I still got the same error with not finding the .bundle file, I'm on beta5

**Comment by exherb** [comment]
@tkuichooseyou look into the error message and match the path.

**Comment by fuxx** [comment]
When i work on a framework with bundles, would not a pod install overwrite the path changes every time? Unfortunately i have todo so every time i pull our latest version.

**Comment by benasher44** [comment]
Confirmed that this is happening to me as well. The issue is that the build phase is trying to a copy a the resource from `$BUILT_PRODUCTS_DIR/PodName/PodName.bundle`, but the bundle actually lives in `$BUILT_PRODUCTS_DIR/PodName/PodName/PodName.bundle`.

Looks like something in CocoaPods has nested the pod one extra level deep in the folder hierarchy than required.

I should note that the built framework itself is correctly placed at `$BUILT_PRODUCTS_DIR/PodName/PodName.framework`. It's just the bundle that is located at `$BUILT_PRODUCTS_DIR/PodName/PodName/PodName.bundle`.

**Comment by benasher44** [comment]
@mrackwitz this appears to be a regression from #5028. I've made a [branch](/benasher44/CocoaPods/tree/basher_1.0.0.beta.6) where I reverted that merge, and if I install that, my project builds again.

**Comment by mrackwitz** [comment]
@benasher44: Thanks for the hint. Yes, this is a regression.
Sorry y'all for breaking that (again). In face of that I opened #5048. Contributions in that direction would be really welcome!

**Comment by eranmarom** [comment]
@danielgalasko Your solution works perfectly!

**Comment by fcy** [comment]
FWIW I'm also having this problem with beta6 and MWPhotoBrowser 2.1.1, changing the `install_resource` line also "fixes" the problem for me.

**Comment by dral3x** [comment]
I fixed the problem by removing the override on the `Per-configuration Build Product Path` setting in the Pods project resource bundle target.

**Comment by odrobnik** [comment]
I am using a resource_bundle in ProductLayerSDK, the bundle gets created in

`/Users/oliver/Library/Developer/Xcode/DerivedData/ProdlyApp-gvyzwkhhrigehfcbcfriqozupkkw/Build/Products/Debug-iphonesimulator/ProductLayerSDK/ProductLayerSDK/ProductLayerSDK.bundle`

But the final step - where it copies that into the framework expects it at this location:

`/Users/oliver/Library/Developer/Xcode/DerivedData/ProdlyApp-gvyzwkhhrigehfcbcfriqozupkkw/Build/Products/Debug-iphonesimulator/ProductLayerSDK/ProductLayerSDK.bundle`

So the second path has one more ProductLayerSDK in it.

<img width="634" alt="screen shot 2016-04-09 at 18 00 06" src="https://cloud.githubusercontent.com/assets/333270/14404688/f1268938-fe7c-11e5-8a4a-728c338193a4.png">

Does this help?

**Comment by segiddins** [comment]
@odrobnik this is a known issue with a open PR fixing it, see if Marius's PR addresses the issue for you?

**Comment by odrobnik** [comment]
@segiddins No idea how I would do that. I am only able to update Cocoapods via gems, and have messed with its source code.

**Comment by segiddins** [comment]
There is a guides page for "using unreleased features"

**Comment by cuddergambino** [comment]
This still seems to be an issues.

I'm getting

error: /Users/Library/Developer/Xcode/DerivedData/DopamineKit-bqzpbftalgimbyaujrgefxksivjl/Build/Products/Debug-iphonesimulator/DopamineKit/DopamineKit.framework: No such file or directory
I'm using s.ios.resource_bundle and adding a bundle with a name different than my framework

**Comment by cuddergambino** [comment]
This still seems to be an issues.

I'm getting

```
error: /Users/Library/Developer/Xcode/DerivedData/DopamineKit-bqzpbftalgimbyaujrgefxksivjl/Build/Products/Debug-iphonesimulator/DopamineKit/DopamineKit.framework: No such file or directory
```


I'm using `s.ios.resource_bundle` and adding a bundle with a name different than my framework
