### ISSUE TITLE
Allow plugins to add data to the Lockfile

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#5035]
I would like to propose we add the repo a pod came from in the `Lockfile`, I think I've seen that bundler does this like so:

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
```

This may speed up pod resolution for CocoaPods (we could only clone the repos actually needed) as well as the plugin I wrote which currently cycles through all of the sources until it gets a match (It would directly go to the repo it needs).

Potentially this could be an extra section in the lockfile, like so:

```
POD REPOS:
 - https//www.github.com/CocoaPods/CocoaPods.git
    - AFNetworking
 - https://www.github.com/My/Repo.git
    - MyCustomPod
```

**Comment by segiddins** [comment]
I'm hesitant to add that functionality just for a single plugin to use -- in bundler, we need the source information since the Pods aren't copied into a per-project directory and thus specs have to be looked up a runtime, and CocoaPods doesn't have that need.

**Comment by jcampbell05** [comment]
@segiddins Okay understood, would there be a provision to being able to add custom data to a lockfile ? i.e could a plugin when installed add it's own metadata to the lockfile. 

That way I can get the information my plugin needs without you having to modify cocoapods just for one plugin.

**Comment by segiddins** [comment]
@jcampbell05 yeah, I think that would be acceptable! A PR adding a way for plugins to add / retrieve data from the lockfile would be great!
