### ISSUE TITLE
Cocoa Pod flats the directory in xcode (it doesn't preserve the folder structure)

### ISSUE THREAD

**Issue by umut-genlik** [CocoaPods/CocoaPods#5036]
I am trying to add a pod to my project.
I need the folder structure in example "FLAC/all" or "FLAC++/all"

following https://github.com/CocoaPods/CocoaPods/issues/1437 I created podspec file as 

    s.header_mappings_dir = 'libFLAC/include'
    s.private_header_files = 'libFLAC/**/*.{h}'
    s.source_files = 'libFLAC/src/**/*.{h,m,c}', 'libFLAC/include/**/*.{h,m,c}'
    s.requires_arc = false
    s.preserve_paths = 'libFLAC/*', 'libFLAC/**/*'
    s.xcconfig = {
      'USE_HEADERMAP' => 'NO',
      'USER_HEADER_SEARCH_PATHS' => '"${PODS_ROOT}/FLACiOS/libFLAC"',
      'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/Target Support Files/FLACiOS"',
      'ALWAYS_SEARCH_USER_PATHS' => 'NO'
    }

this technically works because when I go to directory in finder, I can see

pods/flac or pods/headers/public has the folder structure.
[![enter image description here][1]][1]

[![enter image description here][2]][2]

but in the xcode

[![enter image description here][3]][3]

why this is happening? If I use a subspec, it also has similar issues.

config files is this 

    ALWAYS_SEARCH_USER_PATHS = NO
    GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
    HEADER_SEARCH_PATHS = "$(PODS_ROOT)/Target Support Files/FLACiOS" $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/AFNetworking" "${PODS_ROOT}/Headers/Public/BEMSimpleLineGraph" "${PODS_ROOT}/Headers/Public/Common" "${PODS_ROOT}/Headers/Public/FLACiOS" "${PODS_ROOT}/Headers/Public/FontAwesome+iOS" "${PODS_ROOT}/Headers/Public/InAppSettingsKit" "${PODS_ROOT}/Headers/Public/Reachability" "${PODS_ROOT}/Headers/Public/XVRClient"
    OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/AFNetworking" -isystem "${PODS_ROOT}/Headers/Public/BEMSimpleLineGraph" -isystem "${PODS_ROOT}/Headers/Public/Common" -isystem "${PODS_ROOT}/Headers/Public/FLACiOS" -isystem "${PODS_ROOT}/Headers/Public/FontAwesome+iOS" -isystem "${PODS_ROOT}/Headers/Public/InAppSettingsKit" -isystem "${PODS_ROOT}/Headers/Public/Reachability" -isystem "${PODS_ROOT}/Headers/Public/XVRClient"
    OTHER_LDFLAGS = $(inherited) -ObjC -l"AFNetworking" -l"BEMSimpleLineGraph" -l"Common" -l"FLACiOS" -l"FontAwesome+iOS" -l"InAppSettingsKit" -l"Reachability" -framework "CoreGraphics" -framework "Foundation" -framework "MessageUI" -framework "MobileCoreServices" -framework "Security" -framework "SystemConfiguration" -framework "UIKit"
    PODS_ROOT = ${SRCROOT}/Pods
    USER_HEADER_SEARCH_PATHS = "${PODS_ROOT}/FLACiOS/libFLAC"

How can I fix this?

  [1]: http://i.stack.imgur.com/97MaE.png
  [2]: http://i.stack.imgur.com/bwncj.png
  [3]: http://i.stack.imgur.com/uTRA0.png

**Comment by segiddins** [comment]
This is intentional -- the directory structure is only preserved for development pods, but it shouldn't actually effect compiling pods at all.

**Comment by UnikworkEmp** [comment]
@umut-genlik did you find any solution for above issue?
