### ISSUE TITLE
Adding new pod is not updating Pods Xcode project and Targets.

### ISSUE THREAD

**Issue by dbarros** [CocoaPods/CocoaPods#5043]
I've been using a steady set of pods for a project, but recently I tried to add a new one.

I've added "pod 'PLCrashReporter'" to my Podfile, then ran `pod install`. But the new pod is not added as an Xcode Target in the Pods project. 

Has anyone else seen this bug? Any workaround?

I'm using Cocoapods 1.0.0.beta.5.

**Comment by orta** [comment]
Can you provide a breaking example of this please? I've not seen something like this before

**Comment by dbarros** [comment]
@orta I've created a test project [here](https://github.com/dbarros/cocoaPods-test).

These are the steps I took to get to the point of the sample project:

1. Created a workspace in Xcode.
2. Created a project.
3. Created a Podfile (initially without the PLCrashReporter pod).
4. ran `pod install`

At this point I am able to build the complete workspace, including all the pods in the Podfile.

I then added a new pod `PLCreashReporter` to the Podfile. Then ran `pod install` again.

The PLCrashReporter pod seems to have been installed OK.

But, if you look at the Pods project in Xcode, the new pod is not listed in either the Schemes for the project, nor is it added as a Target in the Pods project (like all the original ones are).

Hope this helps. Any further information, please let me know.

**Comment by dbarros** [comment]
When building in Xcode, after adding the new pod, this is the error I get:

```
ld: '/Users/diego/ios/cocoapods-test/Pods/PLCrashReporter/iOS Framework/CrashReporter.framework/CrashReporter(libCrashReporter-iphoneos.a-arm64-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When seeing this error is why I then noticed that PLCrashReporter was not added by Cocoapods as a Target (when I went to look for its Target build settings to adjust them to fix the build error).

**Comment by segiddins** [comment]
PLCrashReporter uses a vendored binary, therefore it is expected that it not show up as a target in the Pods project. You should ask the PlausibleLabs people to cut a new version with bit code support, as theres nothing CocoaPods can do about that.
