### ISSUE TITLE
pod spec lint uses a wrong ARC flag

### ISSUE THREAD

**Issue by kenichi-fukushima** [CocoaPods/CocoaPods#5045]
# Report

Run pod spec link on this file:
https://github.com/CocoaPods/Specs/blob/master/Specs/cordova-plugin-dialogs/1.2.0/cordova-plugin-dialogs.podspec.json

## What did you expected to happen?

The command finishes successfully.

## What happened instead?

The command fails with false warnings about ARC. This seems to be because the command uses a wrong ARC flag ( -fno-objc-arc).

**Comment by orta** [comment]
Which version of CocoaPods are you using?

**Comment by kenichi-fukushima** [comment]
I'm using 1.0.0.beta.6.

**Comment by orta** [comment]
Can you include some of the output when you run the command too please?

**Comment by kenichi-fukushima** [comment]
This is output of pod lint --verbose.
https://gist.github.com/kenichi-fukushima/269286adba303295eec4

This is not just a lint error but my project doesn't build now without a tweak because of this false positive.

**Comment by segiddins** [comment]
The issue here is that your podspec uses the string `"true"` rather than the boolean `true`.

**Comment by kenichi-fukushima** [comment]
Thanks for debugging this careless mistake of mine. Maybe this is a kind of error that the linter is expected to catch?

**Comment by segiddins** [comment]
In 1.0, it would fail to compile if you ran `pod spec lint`
