### ISSUE TITLE
diff: /../Podfile.lock: No such file or directory

### ISSUE THREAD

**Issue by gerchicov-bp** [CocoaPods/CocoaPods#5046]
I have the same issue:
https://github.com/CocoaPods/CocoaPods/issues/2303
but this topic is closed for conversation.

I want to ask for another way to solve this issue. I deleted all the visible pod files and directories but it still shows the same errors. How to delete these pods completely?

**Comment by nootfly** [comment]
the same here.
[1] $ pod --version                                                                                                  
1.0.0.beta.6

**Comment by orta** [comment]
You want to remove the CocoaPods build phases on the targets that you have used with CocoaPods, it's best that you run `pod deintegrate` to remove all of the pieces automatically :+1:

**Comment by nootfly** [comment]
This issue still exists on multiple targets.
