### ISSUE TITLE
Add an example with resource bundles to the test harness

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#5048]
CocoaPods supports different possibilities for podspecs to declare resources. One of these are resource bundles. At installation time, CocoaPods generates an additional target for each resources bundles. The resources are added to that. At runtime, Xcode applies the built-in build rules to these files, just like it is done for resources in app or framework targets. The built product is a bundle directory, which holds the processed resources. This resources bundle has to be copied into the app bundle, which is done by the generated copy resources script.
The test suite defines via unit and integration specs how a working installation should look like. But this working installation is mostly based on human assumptions and reasoning. There are no specs currently which actually execute a copy resources script, which copies a resource bundle from a build directory into an app bundle. If any path around that is broken that might not be caught just by code review (as happened with #4954, #5028).
Our [examples](https://github.com/CocoaPods/CocoaPods/tree/master/examples) would be suitable for adding an example with a podspec, which uses resource bundles.
## Notes
- The examples are validated via the exit code of `xcodebuild`. This can be triggered via a Rake task which can be executed by [`rake examples:build`](https://github.com/CocoaPods/CocoaPods/blob/master/Rakefile#L244-L282).
- Only iOS and OS X examples are actually build and contribute in such a way to test coverage.
- Local podspecs / development pods as seen in the existing examples are preferable. Large downloads increase the execution time of the test suite, which makes them undesirable and should be avoided at all cost.
- Ideas for additional inspections / validations of the build products are welcome!

**Comment by benasher44** [comment]
@mrackwitz I was having a look at what would be involved to do this, and I'd want to have example podspecs that illustrate all of the different ways resources can be added. Is there some CocoaPods.org search foo that can help me find pods that have these different kinds of specs? Or, could I just make local pods with a parent project Podfile that use :path to point to where the pods/specs are? It seemed like this was what you were implying with "local podspecs / development pods," but just by looking at some of the existing Podfiles in the example projects, I don't see development/local pods.

**Comment by mrackwitz** [comment]
@benasher44: Coverage for all different ways of integrating resources would be even better. What you describe was exactly what I meant. But the Alamofire example for example is using a local podspec. (Which I added back then before there was an official podspec. Given it's popularity / the resulting likeliness it stays around and is updated, it might make sense to switch the approach there.)

**Comment by benasher44** [comment]
Ah yes I see it is. Alright, I'll have a look at this

**Comment by benasher44** [comment]
I figured out what was wrong with `rake examples:build` and fixed it in #5069. I'll update this PR once that was is merged.
