### ISSUE TITLE
Regression in 1.0.0beta5: missing error message for minimum deployment target

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#5052]
# Report

## What did you do?

Run `pod install` with a problematic Podfile.

## What did you expected to happen?

Get error ``Specs satisfying the `MyPod (from `../`)` dependency were found, but they required a higher minimum deployment target.``

## What happened instead?

With 1.0.0beta4 I get the correct error message.
With 1.0.0beta5 and 1.0.0beta6, I get a different error: ``It seems like you've changed the constraints of dependency `MyPod` inside your development pod `MyPod`.
You should run `pod update MyPod` to apply changes you've made.``
Running `pod update MyPod` keep displaying the same wrong error message.

## Podfile

```ruby
target 'MyPod_Example' do
  platform :ios
  pod 'MyPod', :path => '../'
end
```

(note: I know that I should have use `platform :ios, '7.0'`, but the issue here is the incorrect error message)

**Comment by mrackwitz** [comment]
@manuyavuz: Can you take a look at this?

**Comment by manuyavuz** [comment]
Hi @Coeur,

Can you share the contents of `Podfile.lock` and `MyPod.podspec` files?

**Comment by neonichu** [comment]
This issue has been inactive for some time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by Coeur** [comment]
@neonichu it is reproducible with 1.0.0 rc1.

Steps:

    pod lib create MyPod
    cd MyPod/Example/
    echo -e "target 'MyPod_Example' do\nplatform :ios\npod 'MyPod', :path => '../'\nend" > Podfile
    pod install

Result: wrong error message. Please check the first message to see the expected error message.

**Comment by Coeur** [comment]
@manuyavuz there is no Podfile.lock. Follow the steps from previous message to get an example project. And compare with 1.0.0beta4 to get the expected correct error message.

**Comment by siuying** [comment]
I have encountered same issue with 1.0.0. Try to clone following project: https://github.com/siuying/CocoapodsIssue5052

and run ``pod update`` in Example folder, you will get error:

```
[!] Unable to satisfy the following requirements:

- `Issue5052 (from `../`)` required by `Podfile`

It seems like you've changed the constraints of dependency `Issue5052` inside your development pod `Issue5052`.
You should run `pod update Issue5052` to apply changes you've made.
```

**Comment by haemi** [comment]
I'm facing the same issue - any progress/ideas here?

**Comment by HamzaGhazouani** [comment]
I got the same issue
The bug was the deployment target of the sample project  was higher than my pod deployment target
To fix it just change the deployment target of the sample project OR the pod deployment target in the YourPod.podpec file 
Hope that helps

**Comment by franzejr** [comment]
@HamzaGhazouani can you explain it better?

**Comment by HamzaGhazouani** [comment]
@franzejr  For example if you set `s.ios.deployment_target = '9.0'` in your .podspec file
the target of your project should has the same iOS version (9.0) or higher
