### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by ifgyong** [CocoaPods/CocoaPods#5053]
### Error

```
NoMethodError - undefined method `all' for Pod::Platform:Class
/Library/Ruby/Gems/2.0.0/gems/cocoapods-search-1.0.0.beta.1/lib/cocoapods-search/command/search.rb:34:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:334:in `new'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:334:in `parse'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:330:in `parse'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:308:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60all%27+for+Pod%3A%3APlatform%3AClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by orta** [comment]
Have you tried this with the latest beta?

**Comment by ifgyong** [comment]
yes,now I try this with 0.38.2 beta, it  works well.

**Comment by orta** [comment]
I mean from the CocoaPods 1.0.0 branch, so beta 6? Any chance you can try it there?

**Comment by ifgyong** [comment]
I try the latest beta,it is 1.0.0 beta 6,it does not work.
but the Cocoapods it is 0.39.0 works good.
pod --version
0.39.0

**Comment by orta** [comment]
Thanks @ifgyong 

@manuyavuz is this ^ known

**Comment by segiddins** [comment]
The issue from the stack trace is that the beta version of search is being used with 0.37 version of CocoaPods -- uninstall the beta version of `cocoapods-search` if you intend to use the older version of CocoaPods.

**Comment by xumeng** [comment]
Thanks, Helpful for me:)
