### ISSUE TITLE
Error in 1.0.0.beat.6: No such file or directory

### ISSUE THREAD

**Issue by parleer** [CocoaPods/CocoaPods#5054]
# Report

Cocoapods 0.39.0 works fine, but Cocoapods 1.0.0.beat.6 results in the following compilation error:

> error: /Users/me/Library/Developer/Xcode/DerivedData/MyApp-eavcqvuyfoaigcdewzjocnqnvmqn/Build/Products/Debug-iphonesimulator/TOWebViewController/TOWebViewControllerLocalizable.bundle: No such file or directory

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target 'MyApp' do
    pod 'Alamofire', '~> 3.0'
    pod 'TOWebViewController', '~> 2.0.5'
end
```

**Comment by JayZhao** [comment]
This bug is happening again...

**Comment by mrackwitz** [comment]
That's a duplicate of #5034.

**Comment by ryderjack** [comment]
resolved?

**Comment by benasher44** [comment]
Hi @ryderjack! Thanks for reporting this! Unfortunately, there's not enough information here for us to help you. If you could file a new ticket and fully fill out the issue template, we'd be happy to help. Have a great day!
