### ISSUE TITLE
Modules not found when 'gather coverage data' is enabled.

### ISSUE THREAD

**Issue by szweier** [CocoaPods/CocoaPods#5058]
# Report

## Versions

CocoaPods 0.39.0
Xcode 7.2.1

## What did you do?

I added test libraries to to the test target on a project and found that when 'gather coverage data' is enabled for tests that the `@import`'s fail to auto complete and that `command + click`ing on the module cannot find it. 

Steps:

1. Clone my example `git clone git@github.com:szweier/CocoapodsImportIssue.git`
2. cd into the folder and run `pod install`
3. open `Example.xcworkspace`
4. select the `SubExample` scheme
5. toggle open the `SubExample` project and go to `SubExampleTests->SubExampleTests.m`
6. place your cursor on `Nimble` or `Quick` on the import lines (lines 10 or 11) and hit escape for auto complete (note: nothing will auto complete) you may also try command clicking it to see `?` pop up.
7. Note "Module 'Quick' not found" message. 
8. To this point these items missing I'm okay with since we haven't yet built anything.
9. Run tests and see that it runs and tests pass without issue.
10. Note that command clicking / auto complete still doesn't work.
11. Edit the SubExample scheme Test phase and uncheck "gather coverage data"
12. Run tests again, everything still passes but now auto complete and command clicking both work.

Things I've noticed:

When "gather coverage data" is enabled and I build fresh (clearing out derived data) the Build->Products folder remains empty and Intermediates is filled with data.  I'm assuming the xcconfig files generated by CocoaPods is pointing to the Products folder and isn't accounting for this change by Xcode.

When "gather coverage data" is disabled, the products directory is filled and all is right with the world.  Except that I have no coverage information ¯\\\_(ツ)\_/¯ .

## What did you expected to happen?

I expected that after running tests with "gather coverage data" enabled that I would be able to auto complete my imports.

## What happened instead?

Import auto completion wasn't available until I turned off "gather coverage data"

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.3'

workspace 'Example'
xcodeproj 'Example.xcodeproj'

use_frameworks!

target 'SubExampleTests' do
  xcodeproj 'SubExample/SubExample.xcodeproj'
  pod 'Quick', '0.9.1'
  pod 'Nimble', '3.1.0'
end
```

Is there some setting I'm missing or is this a larger issue?

Thanks.

**Comment by segiddins** [comment]
Is the issue actually with building, or only with import autocompletion? If only the latter, can you verify that this is indeed a CocoaPods issue and not an Xcode issue? Thanks!

**Comment by szweier** [comment]
Based on the research I've done into this issue it looks like it's something Xcode changed with the build path on builds with coverage reports being generated but I can try to find more time to dig deeper.

**Comment by szweier** [comment]
Also it was only with auto completion which seems to return if I individually build each framework. Or turn off generate code coverage.

**Comment by segiddins** [comment]
To be honest, this sounds like an Xcode issue rather than a CocoaPods issue to me.

**Comment by szweier** [comment]
It could be I'm honestly not sure at this point but I wouldn't be surprised if it was.  Was just wondering if CocoaPods was putting some framework search path code into the xcconfig's it generates or something of the like that may be pointing to the wrong location when generate code coverage is enabled. If those search paths are pointing to the framework location used when builds are made without code coverage and I run it with code coverage I was wondering if there was something to check for.  But maybe Xcode just changed this in 7.3 accidentally and will change back in an update.

**Comment by segiddins** [comment]
Wouldn't be the first time 🙃

**Comment by Blackjacx** [comment]
The same issue on my side with Xcode 8 beta 6. We should keep an eye on that!
