### ISSUE TITLE
Private Dependency causing lint failure

### ISSUE THREAD

**Issue by jacobbullock** [CocoaPods/CocoaPods#5059]
I have a private spec repo and I have added a couple of specs to that. 

I am trying to set a dependency on ZORACoreDataStack to use ZORAUtil

when I run 'pod lib lint' it fails because it can't find a reference to the private pod

I tried using the --sources option:
> pod lib lint --sources='https://jacob_bullock@bitbucket.org/intomotion/zora_cocoapods.git,https://github.com/CocoaPods/Specs' --verbose

However I still get the following error:
```
    ZORACoreDataStack (0.1.0) - Analyzing on iOS 9.0 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `ZORACoreDataStack` from `/Data/work/intomotion/pods/ZORACoreDataStack`

Resolving dependencies of
 -> ZORACoreDataStack (0.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `ZORAUtil` depended upon by `ZORACoreDataStack`) during validation.

[!] ZORACoreDataStack did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

/Users/jacob/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:181:in `block in run'
/Users/jacob/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:153:in `each'
/Users/jacob/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command/lib.rb:153:in `run'
/Users/jacob/.rvm/gems/ruby-2.2.1@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/jacob/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/jacob/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/jacob/.rvm/rubies/ruby-2.2.1/bin/pod:23:in `load'
/Users/jacob/.rvm/rubies/ruby-2.2.1/bin/pod:23:in `<main>'
/Users/jacob/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/jacob/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

I have looked all over and it appears to me that I have set all of this up properly to use the private dependencies

**Comment by segiddins** [comment]
Can you please share the directory layout of https://jacob_bullock@bitbucket.org/intomotion/zora_cocoapods ?

**Comment by jacobbullock** [comment]
Right now that folder is located at ~/.cocoapods/repos/zorapods  (oddly enough though, another folder was created in there, maybe from a link command... repos/bitbucket-zora_cocoapods)  I never created that folder.

repos/zorapods
     ZORAService
          0.1.0
               ZORAService.podspec
     ZORAUtil
          0.1.0
               ZORAUtil.podspec

**Comment by segiddins** [comment]
ah sorry, it's probably the `repos/bitbucket-zora_cocoapods` repo thats being used due to the same issue as https://github.com/CocoaPods/CocoaPods/issues/5062.

**Comment by jacobbullock** [comment]
is that the right issue reference? I looked through it and doesn't seem related.

should i remove one of the repos?

**Comment by segiddins** [comment]
If you'd like, sure.

**Comment by jacobbullock** [comment]
do you have a suggestion on which one should be removed or if i should kill them both and start over?

**Comment by segiddins** [comment]
Ummmm. Killing both sounds good?

**Comment by neonichu** [comment]
This issue has been inactive for some time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by Youshea** [comment]
I have the same issue, i am adding a private pod A (a cocoa framework) into another private pod B (a single view project). Till this point everything works fine. Now when i add the pod B that is using pod A into another project (my actual application) it gives me an error on private pod B that the module (using swift 'private pod A') is not available. I have tried adding the private pod A into the private pod B .podspec file as a dependency but then the .podspec file does not get validated.

**Comment by boilWater** [comment]
I have the same problems with you @jacobbullock  , do you have solved your issues.   
can you share your solution?

my problem is:

SLAliyunOSSManagerKit (1.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `SLNetworkingProtocol~> 0.0.2` depended upon by `SLAliyunOSSManagerKit`) during validation.

**Comment by jacobbullock** [comment]
@boilWater I wasn't able to get this resolved.  I ended up using git submodules.  As mentioned above they closed this bug so they could have a clean slate with their 1.0 release and I didn't have time to debug it anymore, so there was never any resolution to the actual problem.

**Comment by boilWater** [comment]
I have solved the problem, the solution is that: pod repo push "Specrepo" "SLAliyunOSSManagerKit.podspec" --sources=http://gitlab.poco.cn/SLLibrarySpecrepos/Specrepo.git,https://github.com/CocoaPods/Specs.git --use-libraries 
--source=="private my Sperepo in gitlab","public Specs.git in github"
