### ISSUE TITLE
There is an error when i install

### ISSUE THREAD

**Issue by codestoryWY** [CocoaPods/CocoaPods#5065]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> ℹ Please replace this with what you did.  
> e.g. Run `pod install`

## What did you expected to happen?

> ℹ Please replace this with what you expected to happen.  
> e.g. Install all pod dependencies correctly.

## What happened instead?

> ℹ Please replace this with of what happened instead.  
> e.g. Pod A is missing the subspec B for target C.

## Podfile

> ℹ Please paste the contents of your Podfile below.    
>  (e.g. via `cat Podfile | pbcopy`)  
> You can remove this hint then.

```ruby
# Paste your Podfile contents HERE.
```
AppledeMacBook-Air:cocoapodsDemo apple$ pod --version
0.39.0

**Comment by orta** [comment]
I'm afraid you've given us no information to go with here @codestoryWY  - please read the contributing document when making issues
