### ISSUE TITLE
Using cocoapods 1.0.0.beta.6, Xcode cannot find Libraries' correct path.

### ISSUE THREAD

**Issue by liuwin7** [CocoaPods/CocoaPods#5070]
# Report

## What did you do?
My app’s Deployment Target is set 6.0, and I use Cocoapods to integrate some pods like SSKeychain,  when I build on my iPhone 4s (iOS 7.1), failed. However using iPhone 6 plus (iOS 9.3) it work well.

## What did you expected to happen?
Just expected to build successfully on different devices

## What happened instead?
Build failed on iPhone 4s (iOS 7.1)

## What I found
I found that the real path of the static libs in Products group in Pods project, are not coincident with the information prompted by Xcode. For example, Library pop.a in Products, its real path is xxx/pop/pop.a. But Xcode gave that "cannot find xxx/pop.a"

ℹ And now I use cocoapods 0.39.0, it work well.

## Podfile

```ruby
platform :ios, '6.0'
target 'PSP' do
    # pop
    pod 'pop', '~> 1.0'
    # keychain
    pod 'SSKeychain'
end
```

**Comment by yannickl** [comment]
I have the same issue with Objective-C pods and Xcode 7.3. I downgrade to the v1 beta 5 version and it works.

So the break seems to be only in the beta 6 of the v1.0.0.

**Comment by liuwin7** [comment]
@yannickl Yeah, I downgrade to 0.39.0 version. It works!

**Comment by segiddins** [comment]
@mrackwitz is it possible this is related to changes in scoping?

**Comment by yuldong** [comment]
I met a similar problem within Xcode 7.3 and cocoapods 0.39. Even update cocoapods to 1.0 beta 6. it still has the same. "fatal error: 'openssl/rsa.h' file not found"

**Comment by mrackwitz** [comment]
That might be related to the changes in scoping and integrating with static libraries. But I've no explanation, why it could fail building for one device and not fail building for another.

@liuwin7 and all who second this issue: Have you tried to build completely from scratch / deleted derive data?

**Comment by liuwin7** [comment]
I have to change cocoapods to lasted version as I have downgraded it to 0.39.0. But, I will try!

**Comment by liuwin7** [comment]
Unfortunately I could not reproduce the issue. Maybe what you said above can solve my problem before.  I'll close this issue. 
Still thanks!
