### ISSUE TITLE
'pod lib create' includes an older Nimble version by default in the Podfile

### ISSUE THREAD

**Issue by icanzilb** [CocoaPods/CocoaPods#5074]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

When you use 'pod lib create' you end up with these two lines in your test target section of the podfile:

```ruby
  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
```
The current version of Nimble is 3.2.0 and more importantly 3.0.0 fails to compile under Xcode 7.3

## What did you do?

'pod lib create' and chose to include view tests

## What did you expected to happen?

The generated project to compile on Xcode 7.3

## What happened instead?

The generated project did **not** compile on Xcode 7.3

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxGesture_Example', :exclusive => true do
  pod 'RxGesture', :path => '../'
end

target 'RxGesture_Tests', :exclusive => true do
  pod 'RxGesture', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
```

**Comment by orta** [comment]
Cool, ship a PR to CocoaPods/pod-template :+1: 

Make them:
```ruby
  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
```

**Comment by icanzilb** [comment]
I like how you close issues 🦄
