### ISSUE TITLE
Cocoapods doesn't generate FRAMEWORK_SEARCH_PATHS or PODS_FRAMEWORK_BUILD_PATH

### ISSUE THREAD

**Issue by ronak2121** [CocoaPods/CocoaPods#5075]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Cocoapods doesn't generate FRAMEWORK_SEARCH_PATHS and PODS_FRAMEWORK_BUILD_PATH settings for a pod with no warning.

## What did you do?
pod install

## What did you expected to happen?
Install all pod dependencies correctly.

## What happened instead?

The affected pod has a generated xcconfig that looks like:

GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Private/iOSLib" "${PODS_ROOT}/Headers/Public"
OTHER_LDFLAGS = -l"z" -framework "AdSupport" -framework "CoreTelephony" -framework "Foundation" -framework "LocalAuthentication" -framework "MobileCoreServices" -framework "SystemConfiguration"
PODS_ROOT = ${SRCROOT}
SKIP_INSTALL = YES

Here's what my Podfile looks like:

workspace 'TestApp'
use_frameworks!

xcodeproj 'TestApp.xcodeproj'

target :TestApp do
    platform :ios, '8.0'

    pod 'iOSLib', '6.8.0'
    pod 'Identity', '0.0.12'
    pod 'Logging', '0.0.12'
end

target :WatchOSShellAppExtension do
    platform :watchos, '2.0'

    pod 'Logging', '0.0.12'
end

**Comment by ronak2121** [comment]
The pod spec of the affected pod looks like this:

pod::Spec.new do |s|

  s.name         = "iOSLib"

  s.version      = "6.8.0"

  s.author       = { "Test Team" => "test-team@test.com" }

  s.homepage     = "https://www.yahoo.com"

  s.summary      = "This is a Pod spec for iOSLib."

  s.license      = "No License. Only internal distribution"

  s.ios.deployment_target     = '8.0'

  s.prefix_header_file = "iOSLib/SupportingFiles/iOSLib-Prefix.pch"

  s.frameworks = 'Foundation', 'MobileCoreServices', 'SystemConfiguration', 'LocalAuthentication', 'CoreTelephony', 'AdSupport'

  s.libraries = 'z'

  s.source       = { :git => "ssh://test.com/pkg/iOSLib", :tag => s.version.to_s }

  s.source_files  = "iOSLib/**/*.{h,m}"

  s.public_header_files = "iOSLib/**/*.h"

  s.requires_arc = true

end

**Comment by orta** [comment]
Have you tested on the 1.0 betas?

**Comment by ronak2121** [comment]
I just tried it and I get duplicate symbols all of a sudden with Cocoapods 1.0.0.

**Comment by ronak2121** [comment]
I don't see any duplicate files, #imports of .m files, there are no static libraries that are interfering...

**Comment by ronak2121** [comment]
For some reason, the project is compiling the source files twice...even when I remove all of the source files and add them back.

**Comment by ronak2121** [comment]
I poured through the project settings; and everything looks to be okay. Really dumbfounded by which setting is causing this...

**Comment by ronak2121** [comment]
I found the problem in the code that I was trying to convert. Thanks.
