### ISSUE TITLE
Update to Xcode 7.3 brings a build error to Mac app with 1.0.0beta6

### ISSUE THREAD

**Issue by icanzilb** [CocoaPods/CocoaPods#5078]
## Goals

What do you want to achieve?
Use RealmSwift pod in an OSX app

## Expected Results

The project to compile

## Actual Results

![image](https://cloud.githubusercontent.com/assets/633862/13999061/c7701892-f13a-11e5-87c0-7181dba4bab2.png)

RealmSwift fails to build (it used to build in Xcode 7.2.1 and it does build with latest stable cocoapods)

## Steps to Reproduce

- create a new xcode 7.3 project - a Swift OSX app
- add a Pofile (use your own target name)
```ruby
use_frameworks!

target 'RealmMac' do
    pod 'RealmSwift'
end
```
- from the console run `pod install`
- open the newly generated workspace and press Cmd + B

## Code Sample

Link to the project: https://www.dropbox.com/s/ew8j0itmoykr59q/RealmMac.zip?dl=1

## Version of Realm and Tooling

Xcode version: 7.3

iOS/OSX version: 10.11.4

Dependency manager + version: Cocoapods 1.0.0beta6

**Comment by orta** [comment]
This is probably safe to assume as being an issue on Realm's side, given that if it was at CocoaPods level we'd be seeing a lot of the reports, looks like it's being tracked here: https://github.com/realm/realm-cocoa/issues/3356

**Comment by icanzilb** [comment]
Yeah I wasn't sure who's to take care of it and provided this works with the latest stable cocoapods version I though I'd leave it here. But if it's already handled at realm's side that's fine with me
