### ISSUE TITLE
Deprecated method warning not suppressed when using 'inhibit_all_warnings!' in podfile. 

### ISSUE THREAD

**Issue by JettF** [CocoaPods/CocoaPods#5079]
# Report

## What did you do?

Installed [DKImagePickerController](https://github.com/zhangao0086/DKImagePickerController), which has a dependency on [DKCamera](https://github.com/zhangao0086/DKCamera).

## What did you expect to happen?

I expected warnings from other pods, DKCamera in this specific case, to be suppressed since I am using `inhibit_all_warnings!` in my podfile. 

## What happened instead?

I am getting a warning in my project from DKCamera saying " 'interfaceOrientation' was deprecated in iOS 8.0"

I have submitted an issue to Zhang to use non-deprecated methods. I thought that you guys should know about a warning that was sneaking through.

## Podfile

```ruby
platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

def import_pods
  pod 'DKImagePickerController', '~> 3.0'
end

target :MyApp' do
  import_pods
end
```

**Comment by orta** [comment]
Thanks @JettF! This looks like this issue alas: https://github.com/CocoaPods/CocoaPods/issues/4423 - which is that we give the right flags to LLVM, but they ignore the flags for some features.

**Comment by virl** [comment]
https://github.com/CocoaPods/CocoaPods/issues/4423#issuecomment-222834307
