### ISSUE TITLE
Custom specfile for libevent passes `spec lint` with 0.39.0, fails with 1.0.0.beta.6

### ISSUE THREAD

**Issue by dpassage** [CocoaPods/CocoaPods#5080]
🌈
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have an iOS project which depends on [libevent](http://libevent.org). I've been using a custom-built podspec to build and include it, no problem. When upgrading CocoaPods from 0.39.0 to 1.0.0.beta.6, it started failing to build. Build failure happens with `pod spec lint` as well, so that's what I'm including here.

The specfile is available at https://gist.github.com/dpassage/afe986ce1956bd1670d3; bit long to put in the issue directly.

`libevent` has a sort of odd structure: the private `.h` files are at the top level, and the public files are down in `include/event2/*.h`. They expect to be included into the `.c`'s with `#include "event2/foo.h"`.

Xcode 7.2.1 on OS X 10.11.4 in both cases.

## What did you expect to happen?

What happens with CocoaPods 0.39.0, which is this:

```
$ pod spec lint libevent.podspec --allow-warnings

 -> libevent (2.1.5-beta)
    - WARN  | [iOS] compiler_flags: Warnings must not be disabled(`-Wno compiler` flags).

Analyzed 1 podspec.

libevent.podspec passed validation.
```

## What happened instead?

Here's what happens with 1.0.0.beta.6:

```
$ be pod spec lint libevent.podspec --allow-warnings

 -> libevent (2.1.5-beta)
    - WARN  | [iOS] compiler_flags: Warnings must not be disabled(`-Wno compiler` flags).
    - ERROR | [iOS] header_mappings_dir: There are header files outside of the header_mappings_dir (bufferevent-internal.h, changelist-internal.h, defer-internal.h, epolltable-internal.h, evbuffer-internal.h, evconfig-private.h, event-internal.h, evmap-internal.h, evrpc-internal.h, evsignal-internal.h, evthread-internal.h, ht-internal.h, http-internal.h, iocp-internal.h, ipv6-internal.h, kqueue-internal.h, log-internal.h, minheap-internal.h, mm-internal.h, ratelim-internal.h, strlcpy-internal.h, time-internal.h, util-internal.h).
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  libevent/bufferevent_filter.c:33:10: fatal error: 'event2/event-config.h' file not found
    - NOTE  | [iOS] xcodebuild:  libevent/buffer.c:28:10: fatal error: 'event2/event-config.h' file not found
    - NOTE  | [iOS] xcodebuild:  libevent/bufferevent_pair.c:26:10: fatal error: 'event2/event-config.h' file not found
    - NOTE  | [iOS] xcodebuild:  libevent/bufferevent_ratelim.c:35:10: fatal error: 'event2/event.h' file not found
    - NOTE  | [iOS] xcodebuild:  libevent/bufferevent.c:28:10: fatal error: 'event2/event-config.h' file not found
    - NOTE  | [iOS] xcodebuild:  libevent/bufferevent_sock.c:29:10: fatal error: 'event2/event-config.h' file not found
    - NOTE  | [iOS] xcodebuild:  libevent/evdns.c:51:10: fatal error: 'event2/event-config.h' file not found
    - NOTE  | [iOS] xcodebuild:  libevent/event.c:27:10: fatal error: 'event2/event-config.h' file not found

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 2 errors.
```

## Podfile

The podspec is 250 lines long, as it includes the files which `automake` and friends would have generated. It's available at this gist: https://gist.github.com/dpassage/afe986ce1956bd1670d3

**Comment by dpassage** [comment]
Hmm, try to follow all the rules, and crickets. :)

I'll maybe ask a more specific question: what changed in how `spec lint` works between 0.39 and 1.0 beta? If it's gotten more strict, fair enough; could use some guidance on how to address it.

**Comment by orta** [comment]
It's both spring break, and a few of us are on vacation - I'm responding from Siberia for example, where I'm trying to be OOO. 

I'm pretty sure your issue is the same one mentioned here: https://github.com/CocoaPods/CocoaPods/issues/4723

**Comment by dpassage** [comment]
Hey, sorry if I sounded unappreciative - and thanks for interrupting your vacation to help! I'll look at the linked issue. Thanks!

**Comment by segiddins** [comment]
Yeah, the libevent spec will need to be updated -- previously, headers outside the `header_mappings_dir` were allowed to pass lint, but those specs didn't always work properly.
