### ISSUE TITLE
Post install hook build settings issue

### ISSUE THREAD

**Issue by fergalrooney** [CocoaPods/CocoaPods#5085]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I configured a post install hook in my Podfile to append a custom variable to the GCC_PREPROCESSOR_DEFINITIONS build setting. I ran pod install using CocoaPods v0.39.0 and using Xcode 6.4.

## What did you expected to happen?

I expected the CUSTOM_FLAG variable to be defined along with the inherited GCC_PREPROCESSOR_DEFINITIONS build settings defined in CocoaPods xcconfig.

## What happened instead?

The CUSTOM_FLAG variable was configured successfully in the GCC_PREPROCESSOR_DEFINITIONS build settings, but the $(inherited) flag was not included. Therefore the GCC_PREPROCESSOR_DEFINITIONS build settings defined in CocoaPods xcconfig were not inherited.

## Podfile

    platform :ios, '8.0'

    source 'https://github.com/CocoaPods/Specs.git'
    source 'Path to private repo'

    workspace 'project.xcworkspace'

    target 'project' do
       pod 'PrivateLibrary', '1.0'
    end

    post_install do |installer|
       installer.pods_project.targets.each do |target|
          target.build_configurations.each do |configuration|
             if target.name == 'PrivateLibrary' && configuration.name == 'Debug'
                target.build_settings(configuration.name)['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','CUSTOM_FLAG=1']
             end
          end
       end
    end

**Comment by segiddins** [comment]
You should be setting it to a string instead of an array.
