### ISSUE TITLE
NSPrincipalClass entry is not preserved for frameworks 

### ISSUE THREAD

**Issue by josevazquez** [CocoaPods/CocoaPods#5086]
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
When a pod is built as a Framework, the Framework has a generated Info.plist file that has a blank NSPrincipalClass.

This makes development of things like plugins difficult, since usually developers use NSPrincipalClass to indicate which class users of the Framework can use to activate the plugin. The Cocoapods line in question is https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/info_plist_file.rb#L114. It would be nice if Cocapods used the NSPrincipalClass from a framework target inside the pod, but I imagine that would be difficult. Another possible option might be to allow us to specify an NSPrincipalClass value in the pod spec.

## What did you do?

Run `pod install`

## What did you expected to happen?

I expect the Info.plist in my framework to still contain the value that I specified for NSPrincipalClass

## What happened instead?

The Info.plist in my framework had it's NSPrincipalClass entry set to an empty string. 

## Podfile
```
"Please run `pod install` with bundle exec instead." unless defined?(Bundler)
platform :ios, '8.0'

use_frameworks!

source 'https://internal.specs.repo.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'MainApplication' do
   # removed internal pods
    pod 'MGSwipeTableCell', '~>1.4.3'
    pod 'DeepLinkKit', '~>1.1.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
```

**Comment by orta** [comment]
Hey @josevazquez - I think this is a niche enough case that we won't include support inside CocoaPods itself, but this is definitely something you can, and should create as a [cocoapods-plugin](https://github.com/cocoapods/cocoapods-plugins) ( or modify your `post-install` hook to do the work as a one-off)
