### ISSUE TITLE
How to edit EKEvent in Objective-C? 

### ISSUE THREAD

**Issue by VivekGoswami** [CocoaPods/CocoaPods#5093]
[https://dpaste.de/sVJ9](url)
here is my code i have tried eventwithidentifier method but i dont know how to pass that identifier for specific event edit
` EKEventStore *store = [[EKEventStore alloc] init]; [store requestAccessToEntityType:EKEntityTypeEvent completion:^(BOOL granted, NSError *error) {
        NSLog(@"acces to §Reminder granded %i ",granted);
          }];

    NSPredicate *fetchCalendarEvents = [store predicateForEventsWithStartDate:currentDate endDate:eventDate calendars:nil];
    NSString *identifier =@"0CBED512-BD93-48F1-B5EA-3D9109C718BC";
    
    eventList = [store eventWithIdentifier:identifier;
    
  
    EKEvent *event = [EKEvent eventWithEventStore:store];

  
    event.title = @"new 2";
    event.notes= @"new 3";
    

    NSError *err = nil;
//    [store saveEvent:event span:EKSpanFutureEvents commit:YES error:&err];
    [store saveEvent:event span:EKSpanThisEvent commit:YES error:&err];`

**Comment by alloy** [comment]
This is not related to CocoaPods in any way.

**Comment by VivekGoswami** [comment]
ok ok sorry
