### ISSUE TITLE
"Library Not Found" error with Test Target Only Pod. 

### ISSUE THREAD

**Issue by Nomad00** [CocoaPods/CocoaPods#5094]
* 🌈 I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Upgraded to Xcode 7.3.
Created empty new empty project.
Ran `pod init` (Using CocoaPods 1.0.0-beta 5)
Added `OCMock` to `podfile` for `LibraryNotFoundDemoTests` target.
NOTE: Any Pod which is in the Test target and not the main target exhibits the issue.
Executed `pod install`
Executed test target on device.

## What did you expected to happen?
Test target execute on device.

## What happened instead?

Test target failed to execute.
```
Failed to load test bundle from file:///private/var/containers/Bundle/Application/.../LibraryNotFoundDemo.app/PlugIns/LibraryNotFoundDemoTests.xctest: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/var/containers/Bundle/Application/.../LibraryNotFoundDemo.app/PlugIns/LibraryNotFoundDemoTests.xctest/LibraryNotFoundDemoTests): Library not loaded: @rpath/OCMock.framework/OCMock
```

## Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LibraryNotFoundDemo' do

end

target 'LibraryNotFoundDemoTests' do
# Issue occurs with either of these Pods.
#   pod 'KIF', '~> 3.3.0'
  pod 'OCMock','~> 3.2.2'
end

# Uncomment this if using `KIF`
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['ENABLE_BITCODE'] = 'NO'
#     end
#   end
# end
```
[Sample Project](https://github.com/Nomad00/LibraryNotFoundDemo)

**Comment by Nomad00** [comment]
Upon some further experimentation, it appears this issue occurs whenever a Pod is within at Test target and _not_ in the main target.

**Comment by john-langley** [comment]
+1 I'm having the same issue with OHHTTPStubs

**Comment by Nomad00** [comment]
Update: CocoaPods 1.0.0-beta6 appears to resolve this issue. (I was using the CocoaPods app which is still at beta5.)

cc: @john-langley
