### ISSUE TITLE
Question about local dependencies

### ISSUE THREAD

**Issue by ThiagoMiranda** [CocoaPods/CocoaPods#5095]
Hi. Sorry if this is not the place to make such a question ( I've tried [stackoverflow](http://stackoverflow.com/questions/36162548/creating-a-podspec-file-with-local-dependencies) with no success )

Basically I wanna add two dependencies in my lib but I don't know how to do it.
1- I'm trying to add the [SwiftEventBust](https://github.com/cesarferreira/SwiftEventBus) but as the podspec doesn't accept `:git =>` it turns out that maybe I should clone it as a submodule of my project and add it which brings me to my second question.

2- I have a SDK ( MobilePlayerIOS to be exact ) and I wish to add it as my dependency. First of all I've add it using the `s.dependency 'MobilePlayer'`and it works nicely. But I have to customize their framework to adapt it in my own SDK so I was planning in clone a submodule of it and use the custom version. I've tried several things like this:
```
s.dependency = 'MobilePlayer', :path => 'library/mobileplayer-ios'
s.dependency = 'MobilePlayer', :podspec => 'library/mobileplayer-ios/MobilePlayer.podspec'
```
but it did not work. Is there a way to do it? If so, how?

Again.. I'm sorry for the question but I'm in a little pressure here. 

Thanks.

**Comment by neonichu** [comment]
You cannot depend on local or private specs like that, the correct way to handle this kind of situation is creating your own spec repo: <https://guides.cocoapods.org/making/private-cocoapods.html>
