### ISSUE TITLE
Add minimum require Xcode to Spec/Podfile

### ISSUE THREAD

**Issue by maschall** [CocoaPods/CocoaPods#5098]
I recently did a pod update that would not compile because my project is on an old Xcode.

As a consumer of pods, I want to specify which version of Xcode I am using.

As a producer of pods, I want to specify what the minimum version of Xcode is required.

**Comment by neonichu** [comment]
I could see this as being useful, on the other hand, not even Xcode itself really has such a capability and leaves this up to the user.

**Comment by segiddins** [comment]
This has come up before. Ultimately, we came to the conclusion that it would cause more harm than good, since it would require everyone to push a new version of their pod each time a new version of Xcode is released.

**Comment by orta** [comment]
Yeah, I'm on the side of not adding it, especially as Swift versions are now even less tied to exact Xcode builds too.

**Comment by neonichu** [comment]
Going to close this as the consensus among the team seems to still be to not add this functionality.
