### ISSUE TITLE
Cannot call value of non-function type 'module<CocoapodName>'

### ISSUE THREAD

**Issue by arielelkin** [CocoaPods/CocoaPods#5099]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

When I try to use a Cocoapod I created, I get this error:

```
Cannot call value of non-function type 'module<CocoapodName>'
```

## What did you do?

I created a Cocoapod:
https://github.com/project-a/paddedview

Successfully added it to the trunk, run `pod install`

## Small example project showing the problem

https://github.com/arielelkin/PadTester

**Comment by segiddins** [comment]
Try using `PaddedView.PaddedView`, since the name of the framework conflicts with the name of the class inside of it.

**Comment by arielelkin** [comment]
No joy. If I try with `PaddedView.PaddedView, I get this error:

```
Module 'PaddedView' has no member named 'PaddedView'
```

Any thoughts?

**Comment by segiddins** [comment]
Ah yeah, you also need to make `PaddedView` public.

**Comment by orta** [comment]
Closing - this looks like just Swift :+1:
