### ISSUE TITLE
Unable to find a specification for a private pod hosted on a private bintray repository

### ISSUE THREAD

**Issue by pkhetrapal** [CocoaPods/CocoaPods#5100]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I am trying to distribute my library from `bintray` private repository using access control. The distributing file would be a `.zip` file containing the `.framework` file.
I add this in the `Podfile`:
`pod 'MyLibrary', :http => 'https://<user>:<password>@bintray.com/ios_sdk/MyLibrary.zip'`
## What did you expected to happen?

After running `pod install`, it was expected that the pod dependency would be installed correctly, but it gave me an error `Unable to find a specification for MyLibrary`
## What happened instead?

Error - `Unable to find a specification for MyLibrary`
## Podfile

``` ruby
target 'MyTestApp' do
pod 'MyLibrary', :http => 'https://<user>:<password>@bintray.com/ios_sdk/MyLibraryUniversal.zip'
end
```

**Comment by neonichu** [comment]
Does the ZIP file contain a podspec?

**Comment by pkhetrapal** [comment]
Yes, it does. Do I need to use the `'https://<user>:<password>@bintray.com/ios_sdk/MyLibraryUniversal.zip'` in the spec.source as well or can I use it without the credentials?

**Comment by segiddins** [comment]
Can you please share the the zip file (or create a reproducible case you can share) ? Otherwise, I don't see how to debug this. Thanks!

**Comment by pkhetrapal** [comment]
Is there anything else needed from my side?

**Comment by segiddins** [comment]
Not at the moment, thanks!

**Comment by pkhetrapal** [comment]
Hey @segiddins ,

Is there any update on the issue?

**Comment by segiddins** [comment]
Not yet, but anyone is more than welcome to look into it!

**Comment by pkhetrapal** [comment]
Hey @segiddins @neonichu ,

Can you please guide me with the steps to debug the problem?

**Comment by AmineG** [comment]
I have an old project having iOSKruxLib in its pods dependency.
It was using the git repository https://github.com/krux/krux-cocoa-pods.git
now this repository disappeared.

I downloaded iOSKruxLibUniversal.zip and added it somewhere in my server to test the solution, but still not working for me. Here is the error I have

```
[!] Unable to find a specification for 'iOSKruxLib'.

[!] Unable to load a podspec from `iOSKruxLib.podspec`, skipping:

Pod::DSLError
```

I have a copy of the old project with the pod installed when the repository was there, is there any way to use that ?
Is there any way to use

**Comment by AndyGettingAn** [comment]
@pkhetrapal 
I am currently facing the same issue. Have you managed to solve this problem?
