### ISSUE TITLE
No such Module, target Overrides FRAMEWORK_SEARCH_PATHS

### ISSUE THREAD

**Issue by bryan1anderson** [CocoaPods/CocoaPods#5103]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Running xcode 7.3. Swift 2.2. Cocoapods 1.0.0.beta.5
I added a pod to my Podfile, and ran pod install. This happened:
Xcode Workspace seems to work fine with pods. I have access to the all the pod related code inside my files. No compiler errors are thrown, and autocomplete works. However, when I build the project. Error is thrown at random import SomePodLibrary statements all over. `No such module 'SomePodLibrary'` If I remove that the import statement which xcode complains about not having a module, it moves on to the next import statement. Finally, if I remove all the import statements for that specific pod, it begins doing the same thing for other pods.

Also whenever I run pod install/update I get these errors:
```
[!] The `AppName [Debug]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `../Pods/Target Support Files/Pods-AppName/Pods-AppName.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `AppName [Release]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `../Pods/Target Support Files/Pods-AppName/Pods-AppName.release.xcconfig'. This can lead to problems with the CocoaPods installation

    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

## What did you do?
I ran pod install. Same thing. 
I ran pod update. Same thing. 
I deleted the pods directory and then ran pod install and pod update each respectively. Same thing. 
I removed all my pods from Podfile. Ran pod install. Then put my pods back. Ran pod install. Same thing
 
I ran this inside my project directory:
```
rm -rf Pods
	rm -rf *.lock
	rm -rf *.xcworkspace
	rm -rf ~/Library/Caches/com.apple.dt.Xcode/*
	rm -rf ~/Library/Developer/Xcode/DerivedData/*
	pod install
```
Same thing.

I've searched for the error messages but the only time I could find these warnings being given was from two years ago, and cocoapods closed those issues and said that they would be fixed with an update. I'm honestly not sure if they have anything to do with my problem

## What did you expected to happen?

> ℹ Please replace this with what you expected to happen.  

Be able to use pod libraries in my swift code.

## What happened instead?
Error: no such module

## Podfile
```ruby
workspace 'AppName'
xcodeproj 'AppName/AppName.xcodeproj'

use_frameworks!

target "Swop" do
	pod 'OAuthCore'
	pod 'OAuthSwift'
	pod 'FBSDKCoreKit'
	pod 'FBSDKLoginKit'
	pod 'KLCPopup', '~> 1.0'
	pod 'MBProgressHUD'
	pod 'MMDrawerController'
	pod 'SWTableViewCell'
	pod 'PKImagePicker', '~> 0.0.5'
	pod 'LECropPictureViewController', '~> 0.1'
	pod 'Alamofire', '~> 3.1'
	pod 'AsyncSwift'
	pod 'Nuke'
	pod 'Nuke-Alamofire-Plugin'
  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod “PinterestSDK”, :git => “https://github.com/pinterest/ios-pdk.git”
  pod 'LinkedinIOSHelper', '~> 1.0'
end
```

**Comment by neonichu** [comment]
Did you try to remove your custom override of `FRAMEWORK_SEARCH_PATHS` and see if that fixes your issue?

**Comment by bryan1anderson** [comment]
Yes. I removed all custom overrides. Still get this message

**Comment by segiddins** [comment]
If you're getting the message, its unlikely you've actually removed the overrides. Please double check, and if that doesn't fix things, please share a project that reproduces the issue that we can run. Thanks!

**Comment by segiddins** [comment]
Closing due to lack of response.
