### ISSUE TITLE
Copy Pods Resources script failing

### ISSUE THREAD

**Issue by codeman9** [CocoaPods/CocoaPods#5104]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I created an empty project, ran 'pod init' and edited the Podfile to look like this:

```
target 'Test' do
    pod 'apptentive-ios', '~> 2.1'
end
```

Opened up the Test.xcworkspace and pressed cmd-R

## What did you expected to happen?

I expected to be able to run the app.

## What happened instead?

Run custom shell script 'Copy Pods Resources' phase
error: Resource "~/Library/Developer/Xcode/DerivedData/Test-elzymriwucewhpcmxyieabbuyias/Build/Products/Debug-iphonesimulator/apptentive-ios/ApptentiveResources.bundle" not found. Run 'pod install' to update the copy resources script.

## Podfile

```
target 'Test' do
    pod 'apptentive-ios', '~> 2.1'
end
```

-----------------------
We are looking at upgrading from cocoa pods 0.37.2 ! to the latest beta 1.0.0.beta6. In the process we had the above issue. We notice that the Build directory in the DerivedData looks much different than when we were using 0.37.2. For example, in 0.37.2, the bundle resources and the .a files, etc were all at the same level, but in the latest beta, there are directories representing all of the various pods. These new directories have header files and more directories within them.

I have attached the Test project that is failing for us.

[Test.zip](https://github.com/CocoaPods/CocoaPods/files/195821/Test.zip)

**Comment by codeman9** [comment]
I tried beta5 and all is well... so something must have changed between beta5 and beta6.

**Comment by shannonchou** [comment]
same for me

**Comment by AnthonyMDev** [comment]
This is a known issue with `1.0.0.beta.6`

This should be fixed in the next beta build. @mrackwitz Any news on when we can expect a fix?

See: #5082 #5034

**Comment by mrackwitz** [comment]
Yeah, this is a duplicate.Thanks for pointing out to @AnthonyMDev. Thanks for this perfect exemplary bug report though, @coderman9.
I'm currently on vacation, but will look into getti g everything ready as soon as I'm back. Can't give any more exact ETA than that.
