### ISSUE TITLE
Cannot integrate the workspace

### ISSUE THREAD

**Issue by dennisgec** [CocoaPods/CocoaPods#5107]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I tried to install the "XMPPFramework" pod in my own workspace. Everything works fine until it tries to integrate the client projects and an error occurs.

I added the following pod file:

## Podfile

workspace 'App/Instantley.xcworkspace'
platform :ios, ‘8.0’

use_frameworks!

xcodeproj 'App/App.xcodeproj'
xcodeproj 'Domain/Domain.xcodeproj'
xcodeproj 'Data/Data.xcodeproj'

target :App do
    xcodeproj 'App/App.xcodeproj'
    pod 'XMPPFramework'
end

target :Domain do
    xcodeproj 'Domain/Domain.xcodeproj'
    pod 'XMPPFramework'
end

target :Data do
    xcodeproj 'Data/Data.xcodeproj'
    pod 'XMPPFramework'
end

## What did you expected to happen?

I expected the frameworks to integrate and no error to happen.

## What happened instead?

An error occurred indicating it could not find the workspace.

### Error

```
RuntimeError - Developer workspace file reference type is not yet #<Xcodeproj::Workspace::FileReference:0x007f8416fedcf0>
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace/file_reference.rb:79:in `absolute_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:119:in `block in load_schemes'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:118:in `each'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:118:in `load_schemes'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:55:in `from_s'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/workspace.rb:34:in `new_from_xcworkspace'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:91:in `create_workspace'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/user_project_integrator.rb:62:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:750:in `block in integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:747:in `integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:112:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main

**Comment by segiddins** [comment]
https://github.com/CocoaPods/Xcodeproj does not yet support having Workspace file references that have type `developer` -- the issue probably belongs over on that repo. In the meantime, try changing your file references to be either `group` or absolute.

**Comment by dennisgec** [comment]
Thanks so much! @segiddins 
Changing it to group did the trick!
