### ISSUE TITLE
Linting has false positives with Swift @availability checks

### ISSUE THREAD

**Issue by groue** [CocoaPods/CocoaPods#5108]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

🌈 This issue is a follow-up of https://github.com/CocoaPods/trunk.cocoapods.org/issues/175, as requested by @segiddins.

## What did you do?

I tried to pod trunk push with latest Xcode and latest CocoaPods beta:

```
$ pod --version
1.0.0.beta.6

$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

$ xcodebuild -version
Xcode 7.3
Build version 7D175

$ pod trunk push
```

## What did you expected to happen?

I expected [GRDB.swift v0.54.0](https://github.com/groue/GRDB.swift/tree/v0.54.0) to be successfully pushed.

## What happened instead?

Instead, the `pod trunk push` command issued an error:

```
$ pod trunk push
[!] Found podspec `GRDB.swift.podspec`
Updating spec repo `master`
Validating podspec
 -> GRDB.swift (0.54.0)
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:639:23: error: 'localizedCapitalizedString' is only available on iOS 9.0 or newer
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:639:23: note: add 'if #available' version check
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:639:23: note: add @available attribute to enclosing class let
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:639:23: note: add @available attribute to enclosing extension
    - ERROR | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:658:23: error: 'localizedLowercaseString' is only available on iOS 9.0 or newer
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:658:23: note: add 'if #available' version check
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:658:23: note: add @available attribute to enclosing class let
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:658:23: note: add @available attribute to enclosing extension
    - ERROR | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:677:23: error: 'localizedUppercaseString' is only available on iOS 9.0 or newer
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:677:23: note: add 'if #available' version check
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:677:23: note: add @available attribute to enclosing class let
    - NOTE  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:677:23: note: add @available attribute to enclosing extension
    - ERROR | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:639:23: error: 'localizedCapitalizedString' is only available on OS X 10.11 or newer
    - ERROR | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:658:23: error: 'localizedLowercaseString' is only available on OS X 10.11 or newer
    - ERROR | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:677:23: error: 'localizedUppercaseString' is only available on OS X 10.11 or newer

[!] The podspec does not validate.
```

The errors come from lines that are guarded with an @available clause: https://github.com/groue/GRDB.swift/blob/v0.54.0/GRDB/Core/Database.swift#L621-L679

```swift
@available(iOSApplicationExtension 9.0, OSXApplicationExtension 10.11, *)
...
```

The [podspec](https://github.com/groue/GRDB.swift/blob/v0.54.0/GRDB.swift.podspec) requires iOS8, because I expect iOS9-only features to be guarded by the @available clause seen above:

```ruby
s.ios.deployment_target = '8.0'
```

This issue appeared at v0.54.0 of the repository, where I introduced the @available clauses.

I was later able to push [v0.54.1](https://github.com/groue/GRDB.swift/blob/v0.54.1/GRDB.swift.podspec), *with artificial restrictions on iOS 9+ and OS X 10.11+*. These restrictions are only there to let `pod trunk push` complete. My goal is to remove them, and come back to a pod spec that requires iOS 8+ and OS X 10.9+.

But I don't quite know how to avoid those errors.

Thanks in advance for your help.

**Comment by groue** [comment]
Hello,

Some new elements: now the [v0.56.0 podspec](https://github.com/groue/GRDB.swift/blob/v0.56.0/GRDB.swift.podspec) won't lint and won't trunk push, with the following errors:

```
$ pod --version
1.0.0.beta.6
```

```
$ pod lib lint

 -> GRDB.swift (0.56.0)
    - WARN  | xcodebuild:  /Users/groue/Documents/git/groue/GRDB.swift/GRDB/Core/Database.swift:166:12: warning: unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true
    - WARN  | xcodebuild:  /Users/groue/Documents/git/groue/GRDB.swift/GRDB/Core/Database.swift:166:12: warning: unnecessary check for 'OSX'; minimum deployment target ensures guard will always be true

[!] GRDB.swift did not pass validation, due to 2 warnings (but you can use `--allow-warnings` to ignore them).
You can use the `--no-clean` option to inspect any issue.
```

```
$ pod trunk push

[!] Found podspec `GRDB.swift.podspec`
Updating spec repo `master`
Validating podspec
 -> GRDB.swift (0.56.0)
    - WARN  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:166:12: warning: unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true
    - WARN  | xcodebuild:  GRDB.swift/GRDB/Core/Database.swift:166:12: warning: unnecessary check for 'OSX'; minimum deployment target ensures guard will always be true

[!] The podspec does not validate.
```

The warnings target [this line](https://github.com/groue/GRDB.swift/blob/v0.56.0/GRDB/Core/Database.swift#L166):

```swift
if #available(iOS 9.0, OSX 10.11, *) {
```

Problem is: the code does perform those checks, because the lib is able to run under iOS7 and OS X 10.9. But the podspec artificially targets iOS9 and OS X 10.11, as a workaround for this very issue #5108. This workaround does not work any longer...

**Comment by groue** [comment]
OK, it passes with the --allow-warnings option:

```
$ pod trunk push --allow-warnings
```

We're back to the initial issue which is the forced deployment targets.

**Comment by neonichu** [comment]
I'm unable to reproduce the original issue when changing the podspec to `s.ios.deployment_target = '8.0'` — linting works just fine.

**Comment by groue** [comment]
Thanks for the hint @neonichu: I was able to successfully lint and trunk push the version 0.56.1 with deployment targets reset to iOS 8 and OSX 10.9.

The v0.54.1 had somes troubles that are solved now. I don't quite know what happened.

Sorry for the inconvenience. I guess I can close the issue. Thanks again for your help.

**Comment by neonichu** [comment]
It's really curious, since none of the tools involved really changed. My guess: for some environmental reason a different version of `xcodebuild` was invoked and that caused the warnings.

**Comment by groue** [comment]
I agree, that is curious. I also had [other compilation issues](https://github.com/sqlcipher/sqlcipher/issues/162) that automagically solved by themselves later. I hear here and there that one should never download Xcode from the App Store, and I'm starting wondering if I have a rogue Xcode :scream:

**Comment by neonichu** [comment]
You should definitely use `https://github.com/neonichu/xcode-install` :grin:
