### ISSUE TITLE
Error message when using :configuration in a Podfile could show more information

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#5113]
So, I've added a configuration to one of my Pods in my Podfile:

``` ruby 
target 'Artsy' do
  pod 'ALPValidator', :configuration => 'Release'
end
```

But the name doesn't match up with my configurations:

![screen shot 2016-04-03 at 21 13 31](https://cloud.githubusercontent.com/assets/49038/14234691/edcacf7e-f9e0-11e5-944b-b7c2c31d493b.png)

And the message I receive is:

``` sh
[!] Unknown configuration whitelisted: release.
```

This could be expanded to include the configurations CP found, and the Pod:

```
[!] Unknown configuration for the Pod ALPValidator, "release". 
    CocoaPods found "Debug", "Store" and "Demo" - did you mean one of these?
```

**Comment by segiddins** [comment]
can you share the verbose output of that, per chance? I'm having trouble `git grep`ing for where the error is being raised
