### ISSUE TITLE
Cocoa Pods - Framework Linking issue 

### ISSUE THREAD

**Issue by pavithra123456** [CocoaPods/CocoaPods#5115]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

Hi , I am trying to integrate GoogleMap through CocoaPods , but i am getting linker error saying Library not found 

I created pod give using  pod init and pod install command
i  Installed all pod dependencies correctly.

My pod file look like below 
``platform :ios, '8.0'
use_frameworks!

target 'Feed Me' do
pod 'SwiftyJSON', '~> 2.3.0'
pod 'GoogleMaps', '~> 1.10.4'
end

**Comment by orta** [comment]
Did you open the Xcode workspace?

**Comment by pavithra123456** [comment]
Hi Orta,
Previously i didn't opened my workspace , but now i opened and it is working , Thanks a lot .
But could be please explain me , why to open the workspace instead of actual project.

**Comment by orta** [comment]
CocoaPods uses a workspace to keep your pods separate from your app, https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by pavithra123456** [comment]
ok . Thanks :)
