### ISSUE TITLE
Two lint actions running simultaneously break each other

### ISSUE THREAD

**Issue by beloso** [CocoaPods/CocoaPods#5117]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

🌈 - Two lint actions running simultaneously break each other
## What did you do?

I have a CI server with two slots for processing jobs.
I have two distinct jobs to lint my pod spec.
One job does:
`pod lib lint SDK.podspec --allow-warnings --private`
On open merge requests to the podspec

The other job does:
`pod repo push podspecs 'SDK.podspec' --allow-warnings`
When a merge request is accepted to lint and push pod spec to my private pod specs repo`
## What did you expected to happen?

I expect that both lint processes run in parallel.
## What happened instead?

Instead, when one process is running and the other starts at the same time, they both do their operations on the same temp folder. Causing one of the processes to fail cause it can't find given source files.
## Suggestion

Both lint actions were using the same folder in `/tmp` perhaps it could be as easy as not using the same folder for every lint action.

**Comment by segiddins** [comment]
Yeah, this is an easy fix -- use `Dir.mktmpdir` in the validator, if you'd like to send in a PR.

**Comment by TiagoVeloso** [comment]
I'll try doing that, I am not very familiar with ruby though, if no-one tries it before.

**Comment by dnkoutso** [comment]
@segiddins I believe this is fixed by bf1535a975b0098d25e0678c4b866384edc1c653

**Comment by segiddins** [comment]
Nope, that doesn't use `Dir.mktmpdir`, only `Dir.tmpdir`
