### ISSUE TITLE
Link-editing issue with development pod environment (know issue)

### ISSUE THREAD

**Issue by bpoplauschi** [CocoaPods/CocoaPods#5118]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
* I would like to mention from the start that **this is not a CocoaPods issue**, but rather **an issue from Xcode that arises while using CocoaPods**. It sure looks like a CocoaPods issue at first. I've searched through the CocoaPods issues and didn't find anything helpful regarding the issue. I thought that adding an issue (and closing it soon) will allow people to search and find it.

# Report

## What did you do?

- We are building an in-house framework and determined to distribute it as a private pod. Let's call it **MyFramework**
- Our dev environment includes the framework sources and project in the same workspace as an example app using MyFramework. The example app (let's call it **MyExampleApp**) references MyFramework as a development pod (via `:path`).
- So far so good.

1. add some new stuff to the framework (like new classes inside existing files or methods)
1. build the framework target
1. switch to the example app
1. add some example code that uses the new stuff from the framework
1. build the example app

## What did you expected to happen?

- One would expect that switching between building the framework or the example app works flawlessly. Both targets should compile at any time.

## What happened instead?

- The odd thing is in this case, the example app target will not compile because it does not have access to "the new stuff". Here's why...

### Details on the reasoning

- note: the `CONFIGURATION_BUILD_DIR` Xcode environment variable is resolved to something like `~/Library/Developer/Xcode/DerivedData/Workspace-abcdefghij/Build/Products/Debug-iphonesimulator`
- the framework target will be built by default in
`CONFIGURATION_BUILD_DIR/MyFramework.framework`
- the example app target will also get built to the same DerivedData folder: `CONFIGURATION_BUILD_DIR/MyExampleApp.app`
- next to the example app are all the other artifacts built for the example app. Since the example includes the framework as a pod dependency, the framework built by CocoaPods will be built into:
`CONFIGURATION_BUILD_DIR/MyFramework/MyFramework.framework`. Notice the small difference between this artifact and the one from the Framework target itself.
- and now the "magic": it seems Xcode will automatically add the `CONFIGURATION_BUILD_DIR` as a `Framework Search Path`, so when we look at the Link phase messages, something like `-F/Users/MY_USER/Library/Developer/Xcode/DerivedData/WORKSPACE-cinfayhfkdmozoaiizputouuxgsa/Build/Products/Debug-iphonesimulator`. A later `Framework Search Path` element is the one where CocoaPods includes the path to our Framework, so it's `-F/Users/MY_USER/Library/Developer/Xcode/DerivedData/WORKSPACE-cinfayhfkdmozoaiizputouuxgsa/Build/Products/Debug-iphonesimulator/MyFramework` and then the actual link to our framework: `-framework MyFramework`
- I don't know for sure, but I assume Xcode will pick up the first `MyFramework.framework` from all the `Framework Search Paths` included and this is why it will not be able to link the new elements from the Framework.
- If we manually delete everything from the DerivedData folder, everything gets back to normal, but as soon as you build the Framework target, the issue reappears. This is very annoying.

### How we got around the issue

- we did a very simple thing, just renamed the MyFramework target to something like `MyFrameworkFrmwk` and this makes sure the 2 `.framework` artefacts from our build folder have different names.

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs'
source 'OUR_IN_HOUSE_SPECS_REPO

platform :ios, '8.0'

use_frameworks!

xcodeproj 'MyExampleApp'
workspace 'WORKSPACE'

target :MyExampleApp do
    pod 'MyFramework', :path => '../'
end
```

**Comment by segiddins** [comment]
Did you run `pod install` after adding new files to the framework target?

**Comment by bpoplauschi** [comment]
Of course. But the odd issue is when you don't add new files. For example, just a method for an existing class.

**Comment by segiddins** [comment]
In that case, could you share this example project so someone can take a look and try to debug? Thanks!

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by bpoplauschi** [comment]
Guys, sorry it took so long, but I finally created the demo project. As I said in the description, the real issue here is the way Xcode handles dependencies, but I thought other people should not struggle with this as we did. The Demo project is here, for anyone interested: https://github.com/bpoplauschi/DevPodLinkIssue
