### ISSUE TITLE
How to update pod source while working on project that uses it as a dependency?

### ISSUE THREAD

**Issue by attheodo** [CocoaPods/CocoaPods#5120]
Hello,

I need to pick your brains for some advise related to easing up my workflow a bit.

I am working on 2-3 different projects that use a couple of private pods that we've developed internally. Now, every once in a while I come across some enhancements that need to be added to one of this private pods and what is convenient for me to do is go to the Pods folder in the project navigator of my current project, make the changes make sure the pod and project compile successfully and then go to that Pods project, duplicate the changes there and then push it to our private trunk as an updated version. 

Is there a better way to lay down things so as any changes I make to a pod through the project folder get committed to the Pod's git dir so I don't have to do that back and forth duplicating the changes? Much like how Example Project is setuped with `pod lib init` but for multiple projects.

Is that somehow possible?

Thanks!

**Comment by neonichu** [comment]
You're looking for the `:path` option: https://guides.cocoapods.org/syntax/podfile.html#pod
