### ISSUE TITLE
I had 10 pods, but cocoapods.org show 9 only

### ISSUE THREAD

**Issue by iTofu** [CocoaPods/CocoaPods#5126]
Cocoapods.org page: https://cocoapods.org/owners/11787

But I run `pod trunk me`:
````
bogon:hexo Leo$ pod trunk me
  - Name:     Leo
  - Email:    devtip@163.com
  - Since:    April 1st, 05:09
  - Pods:
    - LCActionSheet
    - LCNewFeature
    - LCProgressHUD
    - LCDownloadManager
    - LCLoadingHUD
    - LCCoolHUD
    - LCNavigationController
    - LCBannerView
    - LCTabBarController
    - LCTabBarControllerForLM
  - Sessions:
    - April 1st, 05:09 -  August 7th, 05:22. IP: 106.120.23.226
    - April 4th, 20:44 - August 10th, 20:58. IP: 106.120.23.226
    - April 4th, 21:37 - August 13th, 01:27. IP: 106.120.23.226
````

Maybe it lose `LCTabBarController`...

**Comment by orta** [comment]
This is likely because CocoaDocs isn't at 7.3 yet, I might be able to get around to this on the weekend.

**Comment by iTofu** [comment]
I'm expecting to hear your good news!

**Comment by segiddins** [comment]
Closing because this isn't an issue with CocoaPods the tool.

**Comment by iTofu** [comment]
@orta 
And it has 3 buttons, most reps have 1 only:
![qq20160408-0](https://cloud.githubusercontent.com/assets/10044430/14373864/0c75a4dc-fd81-11e5-8afb-ee36019cdba5.png)
