### ISSUE TITLE
Pods was rejected as an implicit dependency for 'libPods.a' because its architectures '' didn't contain all required architectures 'i386'

### ISSUE THREAD

**Issue by jkunzelman** [CocoaPods/CocoaPods#5130]
## What did you do?

> ℹ Please replace this with what you did.  
> e.g. Run `pod install`

Running pod install or pod update breaks all dependancies. Following trouble shooting documents I'm able to usually resolve the issue via setting build active architectures to no, and/or using deintegrate. then removing pods completely from the project. deleting build scripts or anything else deintegrate leaves behind.

## What did you expected to happen?
run pod install, download dependencies, build project, or run test.
no link errors.

## What happened instead?
project is unable to find pods at build time or Pods is rejected as an implicit dependency do to required architectures.
## Podfile

> ℹ Please paste the contents of your Podfile below.    
# Uncomment this line to define a global platform for your project
platform :ios, '8.2'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GPSi-Standard-iOS' do
pod 'AFNetworking'
pod 'FDKeychain', :git =>'https://github.com/GPSInsight/FDKeychain.git', :commit => '5b9f28bf90e51b2652b224d6e5131ac7dad5fcec'
pod 'GoogleMaps'
pod 'KSDeferred'
pod 'ChameleonFramework'
pod 'STCollapseTableView'
pod 'SplunkMint'
pod 'SWRevealViewController'
end

target 'GPSi-Standard-iOSTests' do
pod 'AFNetworking'
pod 'OHHTTPStubs', '~> 4.8.0'
pod 'OHHTTPStubs/default'
pod 'FDKeychain', :git =>'https://github.com/GPSInsight/FDKeychain.git', :commit => '5b9f28bf90e51b2652b224d6e5131ac7dad5fcec'
pod 'Cedar'
pod 'CedarAsync'
pod 'GoogleMaps'
pod 'KSDeferred'
pod 'STCollapseTableView'
pod 'SWRevealViewController'
end

**Comment by segiddins** [comment]
Are you sure you're building from the workspace instead of the project?

**Comment by jkunzelman** [comment]
yes absolutly sure 
<img width="1549" alt="pods" src="https://cloud.githubusercontent.com/assets/641430/14370006/b8ca132e-fcde-11e5-8225-3d308e1d5060.png">

**Comment by jkunzelman** [comment]
confirmed this error on a fresh pod install. My steps,

pod deintigrate
deleted pod project from workspace
removed all scripts from build phases related to cocoa pods
deleted workspace, pod lock file and pod directory in workspace
only original project file and pod file remains
ran pod install
opened fresh workspace file

got the following error.
Target 'Pods-GPSi-Standard-iOS' of project 'Pods' was rejected as an implicit dependency for 'Pods_GPSi_Standard_iOS.framework' because its architectures 'x86_64' didn't contain all required architectures 'i386 x86_64'

**Comment by jkunzelman** [comment]
I ended up finding a solution here:
http://stackoverflow.com/questions/26445784/target-overrides-the-framework-search-paths-build-settings
