### ISSUE TITLE
No frameworks has been created after pod init

### ISSUE THREAD

**Issue by Pitometsu** [CocoaPods/CocoaPods#5132]
# Report

## What did you do?

Just `pod install && open ./*.xcworkspace`
OS X Yosemite, XCode 7.2, Swift 2.1

```
$ pod --version
1.0.0.beta.6
```
## What did you expected to happen?

Got few swift-based pods.

## What happened instead?

No frameworks in folders, just headers folder, a lot of linking errors.

[Screenshot](http://i.imgur.com/ViApiP9.png)

## Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'KiranChallenge' do
  pod 'AFNetworking+ImageActivityIndicator', '~> 1.0.2'
  pod 'ReactiveCocoa', '~> 4.0.1' # compatible with Swift 2.1 version
end
```

**Comment by Pitometsu** [comment]
Same with 0.39.0 version after complete cocoapods reinstall (i put it by official guide to system gems).

**Comment by neonichu** [comment]
I'm able to build just fine with your Podfile and either version of CP. Can you share a project which reproduces this problem?

**Comment by Pitometsu** [comment]
[look here](https://www.dropbox.com/s/9c1oppnsmhn71g0/KiranChallenge.zip?dl=0)

**Comment by segiddins** [comment]
This is an issue with the `AFNetworking+ImageActivityIndicator` pod -- it needs to change the import in `AFNetworking+ImageActivityIndicator.h` to `#import <AFNetworking_ImageActivityIndicator/UIImageView+AFNetworking_UIActivityIndicatorView.h>`
 or `#import "UIImageView+AFNetworking_UIActivityIndicatorView.h"`
