### ISSUE TITLE
 Unit Test Targets do not copy resources (specifically storyboards) to the correct location

### ISSUE THREAD

**Issue by seaders** [CocoaPods/CocoaPods#5133]
* [:rainbow:] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Added a Unit Test Testing target to my project with reference to storyboards references in a CocoaPod (SwrveSDK)

## What did you expected to happen?

The test to be able to properly reference the storyboard at runtime

## What happened instead?

```2016-04-08 16:24:18.389 UnitTestsCocoaPods[42397:839885] Unable to load Conversation Item View Controller. Could not find a storyboard named 'SwrveConversation' in bundle NSBundle </Developer/repos/git/swrve/swrve-sdk/ios/UnitTestsCocoaPods/Build/Debug-iphonesimulator/UnitTestsCocoaPods.app/PlugIns/UnitTestsCocoaPods.xctest> (loaded)```

Very similar to https://github.com/CocoaPods/CocoaPods/issues/5022, this is (likely) due to a different TARGET_BUILD_DIR causing @rpath to be further down the tree from the main CONFIGURATION_BUILD_DIR where the resources are.

## Podfile

```ruby
platform :ios, '6.0'

abstract_target 'SwrveCocoaPods' do
    pod 'SwrveSDKCommon', :path => '../public'
    pod 'SwrveConversationSDK', :path => '../public'
    pod 'SwrveLocationSDK', :path => '../SwrveLocationSDK'
    pod 'SwrveSDK', :path => '../public'
    target 'UnitTestsCocoaPods'
    target 'UnitTestsCocoaPodsUnitTestsCocoaPods'
end
```

**Comment by segiddins** [comment]
This has been merged!
