### ISSUE TITLE
Improve helpfulness of spec-repo out-of-date possibility.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#5135]
```
[!] Unable to satisfy the following requirements:
- `Nimble-Snapshots` required by `Podfile`
- `Nimble-Snapshots (= 4.0.0)` required by `Podfile.lock`

None of the spec sources contain a spec satisfying the `Nimble-Snapshots` dependency.
You have either; mistyped the name or version, not added the source repo that hosts the Podspec to your Podfile, or not got the latest versions of your source repos.

None of the spec sources contain a spec satisfying the `Nimble-Snapshots (= 4.0.0)` dependency.
You have either; mistyped the name or version, not added the source repo that hosts the Podspec to your Podfile, or not got the latest versions of your source repos.
```

There are a few things that can be improved here:
* Don’t specify basically the same error message twice.
* With the change to no longer auto-update repos on `pod install`, it’s much more likely that the repo is out-of-date than the user mistyping anything, so that should move to the front otherwise you risk the user mentally signing-off after the first part of the message. This can be improved even more by separating the various suggestions into a list.

  > None of the spec sources contain a spec satisfying the `Nimble-Snapshots (= 4.0.0)` dependency. You have either:
  > * out-of-date source repos which you can update with `pod repo update`
  > * not added the source repo that hosts the Podspec
  > * or mistyped the name or version.

**Comment by orta** [comment]
Probably worth mentioning the change:

> None of the spec sources contain a spec satisfying the `Nimble-Snapshots (= 4.0.0)` dependency. You have either:
> * out-of-date source repos which you can update with `pod repo update`
> * not added the source repo that hosts the Podspec
> * or mistyped the name or version.
>
>Note: as of CocoaPods 1.0, `pod repo update` is not called before `pod [install or update]` 

( where we change the update/install depending on the command given )

**Comment by alloy** [comment]
`pod repo update` is still being called before `pod update`, no?

**Comment by orta** [comment]
> pod repo update is still being called before pod update, no?

yes
