### ISSUE TITLE
README and CHANGELOG not updating

### ISSUE THREAD

**Issue by dehli** [CocoaPods/CocoaPods#5137]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I ran `pod trunk push TouchDraw.podspec` for version 1.2.3. I then repeated it after making some changes for 1.2.4 to see if my issues would resolve.

[cocoapods.org/pods/TouchDraw](https://cocoapods.org/pods/TouchDraw)
 
## What did you expect to happen?

I expected version 1.2.3 and 1.2.4 to be pushed properly and for the README, CHANGELOG, and CocoaDocs to reflect the changes.

## What happened instead?

- README and CHANGELOG still reference 1.2.2
- CocoaDocs didn't update to the latest version
- When I click on Potential error info on CocoaDocs, I get a timeout for the url (http://api.cocoadocs.org:4567/error/TouchDraw/1.2.4)

## Podfile

I removed the `Podfile` from the master branch of my repository because my local project was able to consume the library fine without it but I can add it back if needed. The `Podfile` is present on both the 1.2.3 and the 1.2.4 tags (it was removed a few commits after 1.2.4).

```ruby
platform :ios, '8.0'

target 'TouchDraw' do

end

target 'TouchDrawTests' do

end
```

Thanks for all the work you guys do!

**Comment by orta** [comment]
Thanks - looks like CocoaDocs is down, I've made an issue on CocoaDocs to represent it ( it's not a cocoapods the tool bug ) https://github.com/CocoaPods/cocoadocs.org/issues/437

**Comment by orta** [comment]
When it gets back up, it will self-heal and run older pods - so no need to worry there

**Comment by dehli** [comment]
I wasn't sure if I should post it here or there since there were issues with the README and CHANGELOG as well. I guess those are generated from CocoaDocs then. Thanks a lot for your help! :)
