### ISSUE TITLE
Error loading plugin Cocoapods Try

### ISSUE THREAD

**Issue by Brett-Best** [CocoaPods/CocoaPods#5138]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `bundle exec pod install`

## What did you expected to happen?

Not get an error loading the plugin.

## What happened instead?

Got this error:

```
---------------------------------------------
Error loading the plugin `cocoapods-try-1.0.0.beta.3`.

NameError - uninitialized constant Pod::Command::Try::RepoUpdate
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:10:in `<class:Try>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:9:in `<class:Command>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:6:in `<module:Pod>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/pod/command/try.rb:5:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/cocoapods_plugin.rb:1:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.0.0.beta.3/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:95:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:95:in `block in safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:95:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:95:in `safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.5/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.5/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------
```
## Bundle File

```ruby
source "https://rubygems.org"

gem "cocoapods", "1.0.0.beta5"
gem "cocoapods-acknowledgements"
gem "cocoapods-deintegrate"
gem "cocoapods-try"
gem "fastlane"
```

## Pod Env

```
### Stack

```
```
   CocoaPods : 1.0.0.beta.6
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f276b7f0e6aa9a7bacee59717e3fd2b9d3b97b7a
```
```

### Installation Source

```
```
Executable Path: /usr/local/bin/pod
```
```

### Plugins

```
```
cocoapods-acknowledgements : 1.1.0
cocoapods-deintegrate      : 1.0.0.beta.1
cocoapods-plugins          : 1.0.0.beta.1
cocoapods-search           : 1.0.0.beta.1
cocoapods-stats            : 1.0.0.beta.3
cocoapods-trunk            : 1.0.0.beta.2
cocoapods-try              : 1.0.0.beta.3
```

## Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

def pods_snapshot
  pod 'Alamofire'
  pod 'Moya'
  pod 'HanekeSwift'
  pod 'PromiseKit'
  pod 'HockeySDK'
end

target 'Snapshot Wall' do
  pods_snapshot

  target 'Snapshot Wall Tests' do
    inherit! :search_paths
  end

  target 'Snapshot Wall UI Tests' do
    inherit! :search_paths
  end
end
```

**Comment by Brett-Best** [comment]
Oops my bad. Just found this issue: https://github.com/CocoaPods/cocoapods-try/issues/50
Updating to Cocoapods 1.0.0.beta.6 fixed the issue.

**Comment by Vinod-Square** [comment]
Error loading the plugin `cocoapods-try-1.1.0`.

ArgumentError - could not find a temporary directory
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:34:in `tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:70:in `<class:Try>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:10:in `<class:Command>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:6:in `<module:Pod>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:5:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `block in safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

again issue in sudo gem install -n /usr/local/bin cocoapods -v 1.1.0

**Comment by Brett-Best** [comment]
@Vinod-Square I'd recommend reporting a new issue.
