### ISSUE TITLE
CocoaPods fails silently when cache contents are invalid

### ISSUE THREAD

**Issue by Ruenzuo** [CocoaPods/CocoaPods#5141]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

This happens on a VM with OS:

```
System Version: OS X 10.10.5 (14F1021)
Kernel Version: Darwin 14.5.0
```

With CocoaPods version:

```
1.0.0.beta.4
```

Command executed:

```
bundle exec pod install
```

## What did you expected to happen?

Dependencies installed correctly or CocoaPods installation to fail.

## What happened instead?

CocoaPods installation failed silently. Pod install command succeeds, but later on while compiling the project we get the following error:

```
/Users/jenkins/Jenkins/workspace/ios-iphone-app-deploy-alpha/Classes/XNGCollectionViewMYMKCell.h:2:9: 'XNGFeed/XNGFeedMYMKView.h' file not found

#import <XNGFeed/XNGFeedMYMKView.h>
```

Looking into the CocoaPods output we found the following:

```
-> Installing XNGFeed 1.11.2 (was 1.11.2)
  > Copying XNGFeed from `/Users/jenkins/Library/Caches/CocoaPods/Pods/Release/XNGFeed/1.11.2-a5674` to `Pods/XNGFeed`
```

XNGFeed is the only dependency hitting cache, everything else uses the local copy like:

```
-> Using XNGEvents (0.3.3)
```

So when I look at the contents of the cache, the directory is empty, and so is the copied directory under Pods/XNGFeed

Is this a known issue? I'm sorry I can't share our Podfile/full command output at the moment, but if it's necessary we could share a edited version of both. 

For the moment, we decided to use `COCOAPODS_SKIP_CACHE` environment variable, but maybe it makes sense to add an additional check into [`downloader.rb`](https://github.com/CocoaPods/CocoaPods/blob/856045e4ebfc3292101e9af004fe56d1c2a4e0b1/lib/cocoapods/downloader.rb#L38) or `downloader/cache.rb` to verify that the `cache_path` actually contains something in there. Let me know if this makes sense to you guys, and I gladly open a PR with the suggested approach.

**Comment by segiddins** [comment]
It sounds like there's just a bug with that one pod -- I'd like to investigate that first before presuming that the cache is busted.

**Comment by Ruenzuo** [comment]
Fair enough. Pod is closed source, can I help you providing any more information?

**Comment by segiddins** [comment]
Well unless you can provide a reproducible example of the error, I don't really know what we can do about it

**Comment by neonichu** [comment]
This issue has been inactive for some time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
