### ISSUE TITLE
Don't use emoji in build phase names

### ISSUE THREAD

**Issue by vmalyi** [CocoaPods/CocoaPods#5143]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have cocoapods in my project and I use AppCode for development. AppCode converts emoji in project.pbxproj file to ASCII after each start. It causes weird changes which I have to revert each time I have to commit something:

![bildschirmfoto 2016-04-12 um 10 46 17](https://cloud.githubusercontent.com/assets/1609148/14455016/a7d4e4d2-009d-11e6-8383-5f71cdf0fba7.png)

AppCode developers refused to fix this on their side and stated this issue as related to cocoapods: https://youtrack.jetbrains.com/issue/OC-11493#

## What did you expected to happen?

There are two options:
- don't use emoji in build phases names
- make AppCode don't convert emoji to ASCII when opening/saving project [(WONTFIX)](https://youtrack.jetbrains.com/issue/OC-11493#)

## What happened instead?

AppCode converts emoji to ASCII after each launch

**Comment by alloy** [comment]
> AppCode developers refused to fix this on their side and stated this issue as related to cocoapods

I’m not actually reading it like such. It seems more like they just followed @pietbrauer’s suggestion to close the ticket.

I would say that this doesn’t necessarily have to do with CocoaPods, AppCode doesn’t support something that Xcode does. They are free to choose to not support that off course, in which case we might change it, but I think the right course of action is to first check with them.

/cc @amakeev

**Comment by pietbrauer** [comment]
I suggested to close this issue a year ago way before CocoaPods added an emoji to every build script phase as it was an easy fix in our project. But I know agree with @alloy that it should be fixed by the AppCode team.

**Comment by amakeev** [comment]
Will be fixed [OC-11493](https://youtrack.jetbrains.com/issue/OC-11493), thanks!

**Comment by vmalyi** [comment]
Thank you @amakeev !

**Comment by alloy** [comment]
@amakeev Ace, thanks for commenting! 👍
