### ISSUE TITLE
CocoaPods 0.39.0 won't copy resource_bundles of development pods in to app

### ISSUE THREAD

**Issue by carmelosui** [CocoaPods/CocoaPods#5144]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> I'm upgrading my app from CocoaPods 0.35.0 to CocoaPods 0.39.0.
> Since I need to support iOS7, I can't use 
`user_frameworks!`
> It can build now, but the resources of my development pods which declared in resource_bundles
> is not contained any where in the app I built.
> How could I find way for these resources into may app?

## What did you expected to happen?

> resources declared in resource_bundles be packed into app

## What happened instead?

> resources declared in resource_bundles wasn't packed into app
> In project I can see resources at
`Development Pods/MyFramework/Resources/Pod/Assets/`

## Podfile
```
Pod::Spec.new do |s|
s.platform = :ios, '7.0'
s.requires_arc = true
s.resource_bundles = {
    'MyFramework' => ['Pod/Assets/*.png', 'Pod/Assets/PullAnimation.bundle']
}
end
```

**Comment by jcampbell05** [comment]
Could you add your actual `Podfile` and could you zip up a simple project and pod library that reproduces the issue ?

**Comment by carmelosui** [comment]
Thanks @jcampbell05 , I found the problem is that the building phase of my project misses 'copy pod resources', and I don't know why it happened.  
 I used this tool https://github.com/CocoaPods/cocoapods-deintegrate to deintegrated my project from CocoaPods and rerun 'pod install', everything works fun now.
