### ISSUE TITLE
why it happend and how solve it?

### ISSUE THREAD

**Issue by zhangjikuan** [CocoaPods/CocoaPods#5145]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> ℹ Please replace this with what you did.  
> e.g. Run `pod install`

## What did you expected to happen?

> ℹ Please replace this with what you expected to happen.  
> e.g. Install all pod dependencies correctly.

## What happened instead?

> ℹ Please replace this with of what happened instead.  
> e.g. Pod A is missing the subspec B for target C.

## Podfile

> ℹ Please paste the contents of your Podfile below.    
>  (e.g. via `cat Podfile | pbcopy`)  
> You can remove this hint then.

```ruby
# Paste your Podfile contents HERE.
```
localhost:test ZCHZ$ pod search AFNetWorking
Setting up CocoaPods master repo
Username for 'https://git.oschina.net': k721684713@163.com
Password for 'https://k721684713@163.com@git.oschina.net':

**Comment by zhangjikuan** [comment]
localhost:test ZCHZ$ pod search AFNetWorking
Setting up CocoaPods master repo
Username for 'https://git.oschina.net': k721684713@163.com
Password for 'https://k721684713@163.com@git.oschina.net':

**Comment by segiddins** [comment]
@zhangjikuan do you have a proxy to github setup?

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
