### ISSUE TITLE
I can't  pod XXNibBridge

### ISSUE THREAD

**Issue by Huaida** [CocoaPods/CocoaPods#5147]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> ℹ Please replace this with what you did.  
> Run `pod install` and show me that "Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Illformed+requirement+%60%22XXNibBridge.h%22%60&type=Issues"

## What did you expected to happen?

> ℹ Please replace this with what you expected to happen.  
> e.g. Install all pod dependencies correctly.

## What happened instead?

> ℹ Please replace this with of what happened instead.  
> cann't pod 'XXNibBridge' 

## Podfile

> ℹ Please paste the contents of your Podfile below.    
>  s.dependency 'Masonry','XXNibBridge'

```ruby
# Paste your Podfile contents HERE.
```

**Comment by orta** [comment]
This issue isn't really understandable, you might need to go and [read the guides](https://guides.cocoapods.org/) in order to have a better understanding of what CocoaPods is.
