### ISSUE TITLE
Problem resolving dependencies when building on Travis with CocoaPods 1.0.0.beta.6

### ISSUE THREAD

**Issue by theyonibomber** [CocoaPods/CocoaPods#5149]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

**NOTE:** 
I'm not sure if this is a Travis issue or a CocoaPods issue, since I can't reproduce this locally but only on Travis. However - since what Travis does when failing is running `pod install` and it seems to be a very clear problem in dependency mechanism I doubt it's not related to CocoaPods itself.
I managed to reproduce the problem on this repo: https://github.com/joytunes/cocoapods-bug
And problem can be seen in Travis build's log: https://travis-ci.org/joytunes/cocoapods-bug/builds/122806124

## What did you do?

Trying to run a Travis build of a very straightforward pod with cocoapods 1.0.0.beta.6, after running pod update locally and committing the Podfile.lock.
In the example it has only DTCoreText as a dependency, although I saw this happen with other pods as well.

## What did you expected to happen?

Travis would easily manage to run `pod install`

## What happened instead?

Travis writes this error which doesn't make sense (dependencies aren't conflicting and 1.7.10 seems like a very legit version in the Specs repo):

```
[!] Unable to satisfy the following requirements:
- `DTFoundation/Core (= 1.7.10)` required by `Podfile.lock`
- `DTFoundation/Core (~> 1.7.5)` required by `DTCoreText (1.6.17)`

None of the spec sources contain a spec satisfying the `DTFoundation/Core (= 1.7.10)` dependency.
You have either; mistyped the name or version, not added the source repo that hosts the Podspec to your Podfile, or not got the latest versions of your source repos.
```

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
project 'cocoapods-bug.xcodeproj'

target 'cocoapods-bug' do
    pod 'DTCoreText'
end
```

**Comment by theyonibomber** [comment]
A workaround would be to put
`pod 'DTFoundation/Core'  '=1.7.5'` in the Podfile, but this is of course a lousy workaround.

**Comment by segiddins** [comment]
Maybe you need to run `pod install` with `--repo-update` if Travis isn't providing an up-to-date specs repository and you're not checking in your `Pods` directory.

**Comment by theyonibomber** [comment]
Yep this solved it. Thanks! 😄
