### ISSUE TITLE
Local pod

### ISSUE THREAD

**Issue by Urkman** [CocoaPods/CocoaPods#5150]
# Report

## What did you do?

I included a local pod into my project like this:
```ruby
target 'my-app-ios' do
    use_frameworks!
    platform :ios, '8.1'
    # local pods
    pod MyFoundation', :path => '../my-foundation-ios'
end
```

## What did you expected to happen?

I expect the same as it was in 0.39...
When I edit a file inside this "Development Pod"(MyFoundation) I just rebuild the project and my changes are shown up.

## What happened instead?

But since 1.0.0.beta.6 (perhaps earlier), my changes are simply ignored and the old version of the file is executed...
I tried a clean build and so on... Nothing works :(

## Polfile
```ruby
source 'https://github.com/CocoaPods/Specs.git'
target 'my-app-ios' do
    use_frameworks!
    platform :ios, '8.1'
    # local pods
    pod MyFoundation', :path => '../my-foundation-ios'
end
```

**Comment by segiddins** [comment]
@Urkman that's the first we've heard of this issue! If you could share a project that we could use to reproduce it locally, that would be stellar. Otherwise, does running `pod install` after making the changes to the development pod fix things perchance?

**Comment by neonichu** [comment]
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
