### ISSUE TITLE
Project failing to build

### ISSUE THREAD

**Issue by muasir** [CocoaPods/CocoaPods#5151]
## What did you do?
> Everything was working till I added an swift project which required me to add "use_frameworks!" in the podfile.  Since then, I have clean the project, deleted all cache, and reverted to old code from my source control.  This is with Restkit lib.  Please see the screen shot.
<img width="268" alt="screen shot 2016-04-13 at 4 18 44 pm" src="https://cloud.githubusercontent.com/assets/593065/14509961/ad4f8762-0194-11e6-8f46-1f5f5483a316.png">
<img width="1003" alt="screen shot 2016-04-13 at 4 19 04 pm" src="https://cloud.githubusercontent.com/assets/593065/14509963/af91f6f4-0194-11e6-912f-97e2d9c75b6e.png">

## What did you expected to happen?

After removing the "use_frameworks!" I expected everything to work like before.

## What happened instead?

I am getting errors around expected identifier

## Podfile

platform :ios, '8.1'
target 'RetellMobile'
pod 'SDWebImage', '~>3.7'
pod 'RestKit', '~> 0.24.0'
pod 'DZNEmptyDataSet'
pod 'TWMessageBarManager'

## version of pod
$ pod --version
1.0.0.beta.6

**Comment by segiddins** [comment]
This is an issue with the RestKit podspec, there are already a bunch of open issues on https://github.com/RestKit/RestKit.

**Comment by muasir** [comment]
can you link to one of the issues.. is it https://github.com/RestKit/RestKit/issues/2271?

**Comment by segiddins** [comment]
There are a bunch of different ones, but no one has fixed RestKit yet.

**Comment by muasir** [comment]
Thanks.  Any workarounds are available or any way to reset things?

**Comment by segiddins** [comment]
Nope, someone needs to fix RestKit, or you can use an old version of CocoaPods
