### ISSUE TITLE
 Not able to upload my app to App Store. Need 64bit support which was removed because of few Pod libraries and linking errors.

### ISSUE THREAD

**Issue by SarveshRS** [CocoaPods/CocoaPods#5154]
# Not able to upload my app to App Store. Need 64bit support which was removed because of few Pod libraries and linking errors.

## What did I do?

> Recently added cocoa pods dependency to my project. Got loads of linking errors which were solved with some advice that I received from fellow mates here on Github.
I removed 64bit support for the project which solved all my linking problems.

## Problem?

> Now the problem here is when I am trying to upload my app to App Store, I get below warning.

![screen shot 2016-04-14 at 6 47 24 pm](https://cloud.githubusercontent.com/assets/5631705/14529910/46d6514c-0274-11e6-879c-ac82e090be98.png)

## Podfile

> My Podfile contents are

pod 'CleverTap-iOS-SDK’, ‘2.0.5’
pod 'Crashlytics'
pod 'Fabric'
pod 'iCarousel'
pod 'RSKImageCropper'
pod 'AppsFlyer-SDK'
pod 'FBSDKLoginKit','4.10.0'
pod 'FBSDKShareKit'
pod 'GoogleSignIn'

>Below is my Project Target Architecture

![screen shot 2016-04-14 at 7 12 23 pm](https://cloud.githubusercontent.com/assets/5631705/14530096/127d9fbc-0275-11e6-8c7e-0162b7967241.png)

Please help me find a work around. Help will be appreciated.

**Comment by neonichu** [comment]
You have to change "Valid Architectures" to contain `arm64` again. Not sure which linking errors you faced, but you won't be able to submit to the store without 64bit support.
