### ISSUE TITLE
Cocoapods beta version keep creating subfolders for bundle

### ISSUE THREAD

**Issue by fans3210** [CocoaPods/CocoaPods#5157]
# Report

## What did you do?

> ℹ  Run `pod install` (Take JSBadgaView for example)

## What did you expected to happen?

>  Project runs well without error

## What happened instead?

> error: Resource "/**path of simulator or device**/JSBadgeView/JSBadgeView.bundle" not found. Run 'pod install' to update the copy resources script.

## temporarily solution

> I found the 'JSBadgeView.bundle' in a subfolder which is 'JSBadgeView/JsBadgeView/JSBadgeView.bundle'. So I have to manually move the bundle to root folder to solve the problem. For other libraries with bundles, cocoapods beta version also create subfolders for them.

**Comment by segiddins** [comment]
What version of CocoaPods are you using?

**Comment by fans3210** [comment]
Hi it's 1.1.0 beta 6

**Comment by fans3210** [comment]
Sorry, 1.0.0 beta 6

**Comment by segiddins** [comment]
This ought to be fixed in beta 7, please give that a try? Thanks!

**Comment by fans3210** [comment]
Ok I will try it and revert. Thanks

**Comment by fans3210** [comment]
Hi it's fixed. Thanks!

**Comment by segiddins** [comment]
Awesome!
