### ISSUE TITLE
:source for local pods

### ISSUE THREAD

**Issue by fabb** [CocoaPods/CocoaPods#5158]
# Report

## What did you do?

I have a local library in my project, which has its own `podspec`, so I can integrate it via `:path` in my `Podfile`. The library is not available in the internet, and it has no dedicated repo url, as it is just a part of my project.
Since cocoapods 1.0.0, it is necessary to provide the attribute `source` in the `podspec` though. I'm not sure what to fill it with.

## What did you expected to happen?

Have a way to skip specifying the `source` for local pods integrated via `:path`.

## What happened instead?

I didn't find documentation on what I could provide the attribute `source` with in order to tell it "I have no source for this".

## Podfile

```ruby
pod 'MyLocalPod', :path => 'external/cocoapods-managed/MyLocalPod'
```

**Comment by segiddins** [comment]
You can add whatever to the source attribute, it won't be used for local pods, but changing the validator to make that one exception would be a real pain so we haven't.
