### ISSUE TITLE
MessagePack pod has problems with header file `object.h`

### ISSUE THREAD

**Issue by wkoszek** [CocoaPods/CocoaPods#5165]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

**OSX**: El Captain 10.11.4 + XCode 7.3.
**pod**: 0.39
**Ruby**: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

I tried `MessagePack` pod, but upon importing `MessagePack/MessagePack.h` it threw errors about not being able to find `object.h`.

Couldn't ask the author of the original code, since the https://github.com/msgpack/msgpack-objectivec has disabled issues. This repo also has no `.podspec`.

I got the same functionality from `MPMessagePack`, which is featured on the `msgpack` website.

## What did you do?

I put:

`pod MessagePack`

into `Podfile` and I typed:

`pod install`

## What did you expected to happen?

I'd expect the project to compile fine.

## What happened instead?

Errors. XCode can't find `object.h`

## Podfile

```
use_frameworks!
platform :ios, '8.0'

def mypods
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'AWSCore'
  pod 'AWSS3'
  pod 'AWSCognito'

  pod "Lock", :inhibit_warnings => true
  pod "JWTDecode"
  pod "SimpleKeychain"

  pod "NSLogger"

  pod 'GBDeviceInfo', '~> 3.5'
  pod 'BZipCompression', '~> 1.0.0'
  #pod 'MessagePack'
  pod "MPMessagePack"

  pod 'DZNEmptyDataSet'
end

target 'Sensorama' do
  mypods
end

target :SensoramaTests, :exclusive => true do
  mypods
end

target 'SensoramaUITests' do
  mypods
end
```

**Comment by wkoszek** [comment]
@chrishulbert Just checking if you're still using `MessagePack`. For me I couldn't build it.

**Comment by segiddins** [comment]
Are you sure this isn't just an error with the MessagePack podspec?

**Comment by wkoszek** [comment]
@segiddins That's the podspec:

https://github.com/CocoaPods/Specs/blob/master/Specs/MessagePack/1.0.0/MessagePack.podspec.json

It varies from:

https://github.com/CocoaPods/Specs/blob/master/Specs/MPMessagePack/1.3.5/MPMessagePack.podspec.json

with format. I don't have enough Cocoapods fu to judge.

**Comment by segiddins** [comment]
Perhaps that podspec needs to specify a `header_mappings_dir`? Since it compiles fine as a static library.

**Comment by neonichu** [comment]
This issue has been inactive for some time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
