### ISSUE TITLE
Allowing :macos as an alias for :osx in Podfile and .podspec

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#5166]
If confirmed during WWDC, OSX might be rebranded as MacOS for consistency with iOS, tvOS and watchOS: http://www.macrumors.com/2016/04/14/apple-webpage-update-macos/

If confirmed, we should consider allowing :macos as an alias for :osx in Podfile and .podspec.

**Comment by segiddins** [comment]
@orta thoughts?

**Comment by orta** [comment]
IMO, a good idea, `:osx` is always the most confusing for me as it's the only the one I have to look up ( is it `:mac`, `:macos` or `:osx`? never comes directly to mind ) 

I wonder if we can support all in ruby, but always parse down  `:osx` for json + backwards compat?

**Comment by segiddins** [comment]
It would be easy to do for the Podfile, but rather difficult for the podspec.

https://github.com/CocoaPods/Core/blob/d7e5272304795740d0abee37c25556d45c6e0ec5/lib/cocoapods-core/podfile/target_definition.rb#L460

https://github.com/CocoaPods/Core/blob/d7e5272304795740d0abee37c25556d45c6e0ec5/lib/cocoapods-core/specification/dsl.rb#L487
https://github.com/CocoaPods/Core/blob/d7e5272304795740d0abee37c25556d45c6e0ec5/lib/cocoapods-core/specification/dsl.rb#L1390

**Comment by orta** [comment]
It's hard for me to look at that and figure out it's difficulty, but I'd say it's probably worth making it as an easy first step ( e.g. we could provide the unit tests and someone else could use it as a way to contribute? )

**Comment by Coeur** [comment]
Could we do it for Podfile only for a start?

**Comment by segiddins** [comment]
@orta except it's not an easy first step. And I'd like to keep the podfile and podspec DSL in sync, otherwise things will get really confusing for users.

**Comment by Coeur** [comment]
Note: *macos* was today officially announced.

**Comment by Coeur** [comment]
*bump*

This month was WWDC17, a year after this request, and the marketing name *macOS* has not changed for Apple.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/Core/pull/333

**Comment by dnkoutso** [comment]
@segiddins should we close this or is there more work?

**Comment by orta** [comment]
Perhaps guides updates etc

**Comment by segiddins** [comment]
@dnkoutso I can't remember if that PR addresses both specs & podfiles
