### ISSUE TITLE
JSONModel file not found

### ISSUE THREAD

**Issue by kyleduo** [CocoaPods/CocoaPods#5169]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expected to happen?

Install all pod dependencies correctly.

## What happened instead?

alert `'JSONModel/JSONModel.h' file not found` at `#import <JSONModel/JSONModel.h>`, but I can jump to the file when click this line when pressing commend.

## Podfile

source 'https://git.coding.net/kyleduo/PodSpecs.git'
platform :xxx, '7.0'
xcodeproj 'xxx.xcodeproj'
pod 'Masonry'
pod 'iCarousel'
pod 'JTCalendar'
pod 'JSONModel'

```ruby
# Paste your Podfile contents HERE.
```

**Comment by kyleduo** [comment]
After straggled half-day time, I found it is the problem of PrefixHeader.pch. Can not import any class from pods in PrefixHeader.pch.

**Comment by jcampbell05** [comment]
Could you upload a simple Project that recreates the issue.

**Comment by kyleduo** [comment]
Sorry, I check the error again and I found it was a mistake occurred when using multiple targets. The project has two targets and both of them has a PrefixHeader.pch file importing the same one .h file, and only one of these targets had the configuration of pods. So the other one alert the error. And I uploaded the test project here https://github.com/kyleduo/BlogSourceCode/tree/master/PCHImportProblem.

**Comment by segiddins** [comment]
@kyleduo locking at that project, it seems you have `#import "JSONModel.h"` instead of `#import <JSONMode/JSONModel.h>`

**Comment by kyleduo** [comment]
It doesn't matters, the problem is the header did not be set in Header Search Path.

**Comment by segiddins** [comment]
It shouldn't need to be, its in the Framework Search Paths

**Comment by kyleduo** [comment]
I've double checked the project and using `#import <JSONModel/JSONModel.h>` instead of `#import "JSONModel.h"` and clean/rebuild the project and nothing changed. The problem was alerted from the other target but the default target. And the `HEADER_SEARCH_PATHS` is only set to the default target. Is there any configs I missed when using pods?

**Comment by neonichu** [comment]
This issue has been inactive for some time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!
