### ISSUE TITLE
`pod lib create` broken?

### ISSUE THREAD

**Issue by attheodo** [CocoaPods/CocoaPods#5170]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod lib create TestPod`. Options: Swift/no example/no testing framework/no view-based testing

## What did you expected to happen?

Create boilerplate project structure and open XCode with the project configured and ready for the library to be developed.

## What happened instead?

 - Got error `[!] Invalid `Podfile` file: syntax error, unexpected end-of-input, expecting keyword_end. Updating CocoaPods might fix the issue.`

- XCode didn't open

## Podfile

```ruby
use_frameworks!

target 'TestPod_Example', :exclusive => true do
target 'TestPod_Tests', :exclusive => true do
  pod 'TestPod', :path => '../'

  
end
```

**Comment by orta** [comment]
Fixed by https://github.com/CocoaPods/pod-template/pull/159
