### ISSUE TITLE
CocoaPods crasharoo on pod install

### ISSUE THREAD

**Issue by justlikealltherest** [CocoaPods/CocoaPods#5174]
* [🌈 ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
  Summary: from a fresh install of cocopods, tried to do 'pod install'. I am on the newest version of xcode (7.3) and OSX 10.11.4
  
curl -sSL https://get.rvm.io | bash -s stable --ruby
source /Users/blah/.rvm/scripts/rvm
gem install cocoapods
pod setup
pod install
  
## What did you expected to happen?

Install all pod dependencies correctly.

## What happened instead?

Crash
### Command

```
/Users/blah/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/blah/.rvm/rubies/ruby-2.3.0/lib
Repositories : brion - https://github.com/brion/OGVKit-Specs.git @ 7e271579961bde8804b1a738e0d5380379467acb
               master - https://github.com/CocoaPods/Specs.git @ 3822bbacf6f6784f102aabd71b7dfab34576a8b6
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '7.0'

pod 'NSLogger'
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="NSLogger">
Did you mean?  to_query
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/blah/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/blah/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/blah/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/blah/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/blah/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27+for+%23%3CPod%3A%3ASpecification+name%3D%22NSLogger%22%3E%0ADid+you+mean%3F++to_query&type=Issues

**Comment by segiddins** [comment]
This issue has been opened over 20 times -- please search closed issues in the future: https://github.com/CocoaPods/CocoaPods/search?utf8=✓&q=undefined+method+%60to_ary%27+for+Did+you+mean%3F++to_query&type=Issues. You can either use a ruby version < 2.3 or upgrade to the CocoaPods 1.0 betas.

**Comment by justlikealltherest** [comment]
Thank you for getting back to me segiddins.

The reason why i took the time to open the issue was because when i followed the instructions at the end of the error:
   
  Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60to_ary%27+for+%23%3CPod%3A%3ASpecification+name%3D%22NSLogger%22%3E%0ADid+you+mean%3F++to_query&type=Issues

There weren't any listed.  

As a suggestion, maybe it could provide the existing search as well as a truncated issue so that it gets more search hits. This way the user is less likely to think that they are helping by posting, and get to the solution quickly.

**Comment by justlikealltherest** [comment]
For those of you following along at home, in April 2016, rvm updated their stable version to 2.3 which broke the ability to install cocoapods.  Then when you try to build you will get an error, which will take you to the internet, and you will find one of the many threads of people complaining about this issue and not being able to build cocoapods.  After some digging you will see the two recommendations (which the nice gentleman listed for me here of
  1) installing cocopods beta (which i had done in the past and all hell had broken loose so lets skip this option)
  2)   use a ruby version < 2.3

Let's go for option 2.  Being an ios person, I'm not familiar with this 'roobies' thing, but something tells me its nothing like 'boobies'.  Any who, dafuq you install a version of ruby other than the most recent? Well, you'll google around and it should take you to something like this

curl -sSL https://get.rvm.io | bash -s -- --version 2.2 --ruby

hmm, I'm a reasonable person, so let's GUESS a ruby version hmm how about 2.2.. thats a number less than 2.3 because im good with the mafs.  

WRONG

curl -sSL https://get.rvm.io | bash -s -- --version 2.2 --ruby
ERROR: Something went wrong, unrecognized version '2.2'

YOU FOOL!! You should know that there is no version 2.2

hmmm ok lets guess some more, where dafuq do you find what are valid version numbers.. well you can try a bunch of guesses or you can get hella craft like..
  * the ruby announcements page, https://www.ruby-lang.org/en/news/2016/
>> EXTRA EXTRA READ ALL ABOUT IT...
     Ruby 2.1.10 Released

AHHHA GOT YOU LITTLE BITCH!!
        
LET'S LIGHT THIS ROCKET

curl -sSL https://get.rvm.io | bash -s -- --version 2.1.10  --ruby
Downloading https://github.com/rvm/rvm/archive/2.1.10.tar.gz
curl: (22) The requested URL returned error: 404 Not Found

Could not download 'https://github.com/rvm/rvm/archive/2.1.10.tar.gz'.
  curl returned status '22'.

Downloading https://bitbucket.org/mpapis/rvm/get/2.1.10.tar.gz
curl: (22) The requested URL returned error: 404 NOT FOUND

Could not download 'https://bitbucket.org/mpapis/rvm/get/2.1.10.tar.gz'.

YOU FOOL!! DONT YOU KNOW CURL 22? YOU CANNOT HAVE THIS FILE, HAVE CURL 22 INSTEAD!

--------------------------------------------------------------------------

.. AT THIS POINT, WE PAUSE IN OUR STORY TO SAY FUCK THIS SHIT, AND TRY ANOTHER APPROACH..

THAT APPROACH IS TO INSTALL THE CURRENT STABLE VERSION OF RUBY, THEN TELL IT TO USE AN OLDER VERSION (INSTEAD OF STARTING THE INSTALLATION FROM SCRATCH LIKE WE WERE DOING ABOVE) 

curl -sSL https://get.rvm.io | bash -s stable --ruby
source /Users/blah/.rvm/scripts/rvm
rvm install 2.1.10
rvm use 2.1.10
rvm gemset create rails2.1.10
gem install cocoapods

OMG ITS WORKING ITS WORKING!!! WAIT FOR IT... 

ERROR:  Error installing cocoapods:
	activesupport requires Ruby version >= 2.2.2

YOU FOOL!! COCOAPODS SAYS WTF IS THIS 2.1.10 SHIT?? BE GONE! AWAY WITH YOU!  

WHEN THE NICE GENTLEMAN SAID 'use a ruby version < 2.3 ',

WHAT HE ACTUALLY MEANT IS 
'use any ruby version < 2.3, but if you want it to work, use version = 2.2.2 OR GTFO',

AND SO DEAR READER WE ARRIVE AT OUR 

*********SOLUTION**********

curl -sSL https://get.rvm.io | bash -s stable --ruby
source /Users/blah/.rvm/scripts/rvm

rvm install 2.2.2
rvm use 2.2.2
rvm gemset create rails2.2.2
gem install cocoapods
pod setup
pod install

* I wanna give a shout out to my boy cocoapods, for making this all possible and his lil shorty roobies! The struggle is real.
 2k16

**Comment by segiddins** [comment]
@justlikealltherest please try and keep things civil in issues, and the cursing to a minimum -- it doesn't really contribute to a comfortable environment.

**Comment by justlikealltherest** [comment]
@segiddins thanks again for your help.  please pardon my language.  cocoapods just knows how to get my panties in a twist.  I appreciate you getting back to me so promptly.

**Comment by orta** [comment]
@justlikealltherest sorry, I don't want language like this on our public message board. It's awesome that you're passionate - but it's not how we want to have people participate 👍

**Comment by orta** [comment]
So I've edited out some of the more explicit stuff, but left the useful gold 🍰

**Comment by justlikealltherest** [comment]
@orta no problem, I understand.  For those of you playing along at home, the PROGRAMMERS GONE WILD: TOO HOT FOR GITHUB EDITION (UNCENSORED) can be found here http://pastebin.com/dZmujxmK
