### ISSUE TITLE
The podspec does not validate.

### ISSUE THREAD

**Issue by JV17** [CocoaPods/CocoaPods#5176]
# Report
> Error while trying to `pod trunk push JVMenuPopover.podspec` after `pod lib lint` with passed validation. 
> I get an error message saying,
> -> JVMunePopover (1.2)
> - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit coed. You can use '--verbose' for more information
> - NOTE | [iOS] xcodebuild: JVMenuPopover/Source/Classes/JVMenuViews/JVMenuPopoverView.m:12:9: fatal error: 'UIImage+JVMenuCategory.h' file not found
> [ ! ] The podspec does not validate.
 
## What did you do?

> I was trying to push a new version of my cocoapods framework. I ran all the regular commants/steps outlined on [https://guides.cocoapods.org/making/making-a-cocoapod.html](https://guides.cocoapods.org/making/making-a-cocoapod.html).

## What did you expected to happen?

> No errors and the new version of the pods version published online/cocoapods.

## What happened instead?

> I received the error outlined above.

## Podfile

```ruby
#
# Be sure to run `pod lib lint JVMenuPopover.podspec' to ensure this is a
# valid spec and remove all comments before submitting the spec.
#
# Any lines starting with a # are optional, but encouraged
#
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = "JVMenuPopover"
  s.version          = "1.2"
  s.summary          = "A Simple popover like menu."
  s.description      = "JVMenuPopover is a simple and cool menu popover like. It animates the view controllers and scales them to make  a similar iOS switch window like animation."
  s.homepage         = "https://github.com/JV17/JVMenuPopover"
  # s.screenshots     = "www.example.com/screenshots_1", "www.example.com/screenshots_2"
  s.license          = 'MIT'
  s.author           = { "Jorge Valbuena" => "jorgevalbuena2@gmail.com" }
  s.source           = { :git => "https://github.com/JV17/JVMenuPopover.git", :tag => s.version.to_s }
  s.social_media_url = 'https://twitter.com/Justv17'

  s.platform     = :ios, '8.0'
  s.requires_arc = true

  s.resource_bundles = {
    'JVMenuPopover' => ['Source/Assets/*.png']
  }

  s.public_header_files = 'Source/Classes/**/*.h'
  s.source_files = 'Source/Classes/**/*'
  s.frameworks = 'UIKit', 'Accelerate', 'Foundation'

  # s.dependency 'AFNetworking', '~> 2.3'
end
```

**Comment by neonichu** [comment]
The file `UIImage+JVMenuCategory.h` doesn't exist in your repo, possibly you did not commit it.

**Comment by JV17** [comment]
Thanks! I will look into it. So weird that I pull the repo and I had my files locally and in my Xcode project but for some reason they were not on GitHub or either showing on my source control. I also checked on `.gitignore` and nothing there as well. 

No idea why this header files were not committed but showing everywhere else.

Thank you!
