### ISSUE TITLE
Framework not found when trying to install PureLayout

### ISSUE THREAD

**Issue by w007up** [CocoaPods/CocoaPods#5178]
I have been trying to install PureLayout Pod into my project. But I have encountered some issues.

I get the following error when building.

ld: framework not found PureLayout

I have tried editing the search paths in the project target with no luck.

Any help would be appreciated. 

## Podfile
```ruby
use_frameworks!

target '***' do

    pod 'Google/Analytics'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'PureLayout'

end

target '***' do

end
```

**Comment by orta** [comment]
Are you using the workspace?

**Comment by w007up** [comment]
Yes using the workspace. I used Pod install. Cleaned Derived Data and Build Folder. But somewhere its not linking to the PureLayout framework

**Comment by w007up** [comment]
Just tried a pod deintegrate. Opened my project and searched through build settings, anything related to cocoa pods i removed.

I then did a fresh pod install but still get the same error.

**Comment by orta** [comment]
OK, cool, thanks for trying, can you please upload a small example app that shows this, and note down which version of CocoaPods you're using too

**Comment by w007up** [comment]
Managed to solve this issue by:

Point to your Pods project, set the BaseSDK to iOS SDK since 'pod install' process clear it. Also set Build Valid Architecture Only to NO.

It now builds :) Thank You for your time

**Comment by orta** [comment]
👍
