### ISSUE TITLE
Issue with static libraries in a private pod

### ISSUE THREAD

**Issue by jaumevn** [CocoaPods/CocoaPods#5179]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I've created a private Pod that has multiple dependencies to other third party Pod such as GoogleAnalytics, Facebook or CocoaLumberjack. It's has been used for 2 years in Objective-C projects with any issue. Now we are using it in a new Swift project.

## What did you expected to happen?

Install all pod dependencies correctly as I do in Objective-C projects.

## What happened instead?

The app Podfile includes our own private Pod. Executing commands `pod install` or `pod update` I get the following error, 
```
[!] The 'Pods' target has transitive dependencies that include static binaries: (/App/Pods/Google/Libraries/libGGLAnalytics.a and /App/Pods/Google/Libraries/libGGLCore.a)
```
If in the app I remove the private Pod dependency from the Podfile and I add the Pods directly in the podfile they are installed correctly.
 
## Podfile

Private pod Podfile
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'BoraKit' do

    pod 'UIImage-ResizeMagick'
    pod 'HexColors', '2.3.0'
    pod 'GoogleAnalytics'
    pod 'FBSDKCoreKit', '4.11.0'
    pod 'FBSDKLoginKit', '4.11.0'
    pod 'FBSDKShareKit', '4.11.0'
    pod 'STTweetLabel'
    pod 'CCInfiniteScrolling'
    pod 'PureLayout'
    pod 'pop'
    pod 'CocoaLumberjack'
    pod 'InstagramKit', '~> 3.0'
    pod 'AnimatedGIFImageSerialization', '~> 0.2.0'

end
```

App pod Podfile
```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'BoraKit', :git => '{custom-domain}BoraKit.git', :branch => 'dev'
pod 'RealmSwift'
pod 'Alamofire', '~> 3.3'
pod 'ObjectMapper'
```

**Comment by orta** [comment]
You can't have static libraries as transitive dependencies in dynamic frameworks, whereas you can in static libraries, which is why it used to work. The fix is to request that Google to release dynamic frameworks I'm afraid.

**Comment by neonichu** [comment]
You can find the original discussion on this in #2926 — that should explain why this check exists.
