### ISSUE TITLE
Pod Install with custom source repo fails

### ISSUE THREAD

**Issue by codeman9** [CocoaPods/CocoaPods#5181]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
## What did you do?
I upgraded from CocoaPods 1.0.0.beta.5 to 1.0.0.beta.8
Then I ran 'pod install'

## What did you expected to happen?
I expected my workspace to be created correctly and all Pods to be fetched and integrated.

## What happened instead?
I received an error saying something to the effect of "[!] Unable to find a specification for `XYZ`"

## Podfile
Posting my Podfile won't really help because you won't have access to our custom internal Spec repo. But note that downgrading to 1.0.0.beta.5 works fine.

**Comment by segiddins** [comment]
What's the output of `ruby -rcocoapods -e 'puts Pod::Config.instance.all.map(&:url)'` and the URLs specified in your Podfile?

**Comment by codeman9** [comment]
the output of the command you provided is:
-e:1:in `<main>': undefined method `all' for #<Pod::Config:0x007fcd6a188820> (NoMethodError)

The URL in the Podfile for source is: 
source 'https://git@git.company.net/scm/ao/projectspec.git'

**Comment by orta** [comment]
I think he means: `ruby -r cocoapods -e 'puts Pod::Config.instance.sources_manager.all.map(&:url)'`

**Comment by codeman9** [comment]
Ah, ok, the output of that is:
https://github.com/CocoaPods/Specs.git
https://git@git.company.net/scm/ao/projectspec.git

**Comment by segiddins** [comment]
And in your podfile?

**Comment by codeman9** [comment]
source 'https://git@git.company.net/scm/ao/projectspec.git'

**Comment by segiddins** [comment]
Weird. And if you run `pod install --repo-update`, it still doesnt work?

**Comment by codeman9** [comment]
Took me a while to respond, sorry. That is correct, `pod install --repo-upate` does not work.

**Comment by segiddins** [comment]
No clue then, and there's not much I can do to investigate since there's no way for us to reproduce.

**Comment by codeman9** [comment]
Are you saying that custom repos work for you? I'll do a diff on beta.5 and beta.8 and see if I can see any differences.

**Comment by otymartin** [comment]
@segiddins I get the same issue with `pod 'EasyPeasy` ` whereas every other pod works. Can you try and see? thanks

**Comment by segiddins** [comment]
I can install a podfile with `pod 'EasyPeasy'` without a problem.

**Comment by codeman9** [comment]
After looking through the diffs, I don't see anything that stands out. So I tried seeing if there was a problem with one of the podspecs we were using. It turns out that one of the podspecs we were using had an error revealed during pod lint. The error is:

```
 -> Leanplum-iOS-SDK (1.3.8.1)
    - ERROR | [iOS] public_header_files: The pattern includes header files that are not listed source_files
(/private/var/folders/69/0h06mnz11hl014k0kld92mj4s4200t/T/CocoaPods/Lint/Pods/Leanplum-iOS-SDK/Leanplum.framework/Headers/Leanplum.h,
/private/var/folders/69/0h06mnz11hl014k0kld92mj4s4200t/T/CocoaPods/Lint/Pods/Leanplum-iOS-SDK/Leanplum.framework/Headers/LPNewsfeed.h).
```

Could this be causing the `[!] Unable to find a specification for `NOR-LeanPlum-iOS-SDK (= 1.3.8.1)` error when running `pod install`?

**Comment by codeman9** [comment]
Here is their podspec for reference:

```
Pod::Spec.new do |s|
  s.name = 'Leanplum-iOS-SDK'
  s.version = '1.3.9'
  s.summary = 'Mobile A/B testing, personalization & analytics in one powerful platform.'
  s.description = 'Leanplum! Mobile A/B testing, personalization & analytics in one powerful platform.'
  s.homepage = 'https://www.leanplum.com'
  s.license = { :type => 'Commercial', :text => 'See https://www.leanplum.com/tos' }
  s.author = { 'Leanplum' => 'support@leanplum.com' }
  s.social_media_url = 'https://twitter.com/leanplum'
  s.platform = :ios, '5.0'
  s.requires_arc = true
  s.source = { :git => 'https://github.com/Leanplum/Leanplum-iOS-SDK.git', :tag =>  '1.3.9'}
  s.frameworks = 'CFNetwork', 'Foundation', 'Security', 'SystemConfiguration', 'UIKit'
  s.weak_frameworks = 'AdSupport', 'StoreKit'
  s.xcconfig = { 'OTHER_LDFLAGS' => '-ObjC' }
  s.preserve_paths = 'Leanplum.framework'
  s.documentation_url = 'https://www.leanplum.com/docs#/docs'
  s.public_header_files = 'Leanplum.framework/Headers/*.h'
  s.vendored_frameworks = 'Leanplum.framework'
end
```

It seems like the `s.public_header_files` line may be causing problems. When I remove that line and run `pod spec lint` it passes but I can't seem to get the error to go away.

**Comment by codeman9** [comment]
Any word on how this pod spec should be changed? I see 1.0.0 was released. I still have the same problem with this pod spec and also the Slyce SDK pod spec.

**Comment by segiddins** [comment]
Well did you fix the error lint was giving you?

**Comment by codeman9** [comment]
I'm not sure what to fix or how I can interpret that error to fix something. I need some help.

**Comment by codeman9** [comment]
Some more information. The pod spec lint fails on the podspec presently, but in an empty project with this as the only pod, the pod install completes successfully.

**Comment by codeman9** [comment]
Looks like we had a case insensitivity problem. In our Podfile we had 'LeanPlum' which seemed to work on 1.0.0.beta.5, but in the latest release, it is 'Leanplum'. Making everything the same case worked for this podspec.
