### ISSUE TITLE
Documentation: Add info for specifying _version_ in pod commands

### ISSUE THREAD

**Issue by letvargo** [CocoaPods/CocoaPods#5185]
I recently upgraded to the `1.0.0.beta.8` version of CocoaPods, at which point I had both `0.39.0` and the beta installed on my system.

I had a tough time figuring out how to specify which version of CocoaPods to use when running commands. Through StackOverflow I learned that you can do this:

```
pod _1.0.0.beta.8_ install
```

...and that it works for other `pod` commands as well.

That feature, and how to use it, wasn't documented anywhere in the Guides that I could see. (I may have missed it.)

It seems like it would be a useful thing to have in the command-line guide that explains the syntax for all the different `pod` commands.

**Comment by letvargo** [comment]
BTW, adding this to the documentation is something I'd be happy to help with, but I'm not sure how to get started doing that. References to materials that explain how to contribute to the documentation would be welcome.

**Comment by segiddins** [comment]
This has nothing to do with CocoaPods, its a feature of the binstubs that RubyGems generates when you run `gem install`

**Comment by letvargo** [comment]
Ah...it may not be wise to try and document something that is controlled by a third party.

**Comment by orta** [comment]
That said though, this _is_ a useful feature, I think it could go in the [Troubleshooting](https://guides.cocoapods.org/using/troubleshooting.html) section of the guides - https://github.com/CocoaPods/guides.cocoapods.org/blob/master/source/using/troubleshooting.html.md
