### ISSUE TITLE
Pod cache contents interferes with 'pod spec lint' operations

### ISSUE THREAD

**Issue by Curtis-Halbrook** [CocoaPods/CocoaPods#5186]
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

While working with a private CocoaPod, we had a Swift file that we removed from the project, and removed from the GitHub repository.  When trying to perform a 'pod spec lint --verbose' on a new version, the compilation kept complaining that the file that we removed was causing a compilation error.

Performing a 'pod cache clean' fixed the problem, suggesting that the "ghost" file still remained in the cache.

## What did you expected to happen?

Performing a 'pod spec lint' operation should use the code that is in the current repository.

## What happened instead?

The 'pod spec lint' failed because a removed file from my repository was not removed from my pod cache.

**Comment by segiddins** [comment]
Did you change what the git tag pointed to, perchance?

**Comment by Curtis-Halbrook** [comment]
I did indeed.

**Comment by segiddins** [comment]
That's purposefully unsupported -- if you change what a git tag points to, you'll have to clean the cache by running `pod cache clean POD`
