### ISSUE TITLE
pod lib lint should not check spec-related information

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/CocoaPods#5188]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Run `pod lib lint XCDYouTubeKit.podspec` before releasing a new version of XCDYouTubeKit.
## What did you expected to happen?

The command runs without warnings and exits with code 0.
## What happened instead?

Two warnings are produced and the command exits with code 1.

```
 -> XCDYouTubeKit (2.5.2)
    - WARN  | url: The URL (https://raw.github.com/0xced/XCDYouTubeKit/2.5.2/Screenshots/XCDYouTubeVideoPlayerViewController.png) is not reachable.
    - WARN  | screenshot: The screenshot https://raw.github.com/0xced/XCDYouTubeKit/2.5.2/Screenshots/XCDYouTubeVideoPlayerViewController.png is not a valid image.
    - NOTE  | [OSX] xcodebuild:  note: Registration was skipped, code -50
```

Of course, the screenshot is not found because I have not released the new version yet.

Running <code>pod <b>lib</b> lint</code> and not <code>pod <b>spec</b> lint</code> I was not expecting the linter to check the screenshot. After a quick look at [validator.rb](https://github.com/CocoaPods/CocoaPods/blob/242da6b56683dd173b1ab9f3c998308374c9415c/lib/cocoapods/validator.rb#L258-L261), I think that `validate_homepage`, `validate_screenshots`, `validate_social_media_url` and `validate_documentation_url` should not be called when `local?` is true.

**Comment by segiddins** [comment]
I'm not sure I agree -- you can always ignore warnings while linting, but we want problems with the spec to bubble up sooner rather than later.

**Comment by 0xced** [comment]
If I wanted to validate the spec, I’d run <tt>pod <b>spec</b> lint</tt> instead of <tt>pod <b>lib</b> lint</tt>. Or am I misunderstanding what should be the difference between these two commands?

**Comment by segiddins** [comment]
The difference is only that `lib` uses the local source whereas `spec` uses the source attribute in the podspec

**Comment by 0xced** [comment]
Quoting @alloy
> There should be a diff between spec-warnings and build-warnings
> Can you file a ticket for that?
> Right now there’s no workaround but allowing all warnings I think

I’d really like to be able to validate only build-related stuff. `pod trunk push` will take care to validate everything spec-related anyway.
