### ISSUE TITLE
Spec did not pass validation

### ISSUE THREAD

**Issue by luiyezheng** [CocoaPods/CocoaPods#5189]
# Report

I received `The Spec did not pass validation, due to 2 errors`, but I can't figure out what the errors are.
## What did you do?

> I used` pod spec create` to create the .podspec file in my project(Swift) folder. Inside project folder, source files are in `Source` folder, demo project  is in `Example` folder. LICENSE was also created.
>

## What did you expected to happen?

> The spec pass validation 

## What happened instead?

> I received `The spec did not pass validation, due to 2 errors`

## Podfile

```
Pod::Spec.new do |s|

  s.name         = "StickerTextView"
  s.version      = "0.1.0"
  s.summary      = "add text(multiple line support) to imageView, edit, rotate or resize them as you want, then render the text on image"

  s.homepage     = "https://github.com/luiyezheng/StickerTextView"

  s.license      = { :type => 'MIT', :file => 'LICENSE' }

  s.author       = { "luiyezheng" => "luiyezheng@126.com" }

  s.source       = { :git => "https://github.com/luiyezheng/StickerTextView.git", :tag => "0.1.0" }

  s.platform = :ios, "8.0"

  s.source_files  = "Source"

  s.requires_arc = false

  s.frameworks = "UIKit"

end

``````ruby
# Paste your Podfile contents HERE.
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

You'll want to include the error messages too 👍
