### ISSUE TITLE
Cocoapods 1.0β8 not installing Pods correctly on Frameworks

### ISSUE THREAD

**Issue by piercifani** [CocoaPods/CocoaPods#5190]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
When using Cocoapods 1.0.0β8 it seems like the pods are not correctly installed in a framework created using Xcode instead of defining it in a podspec. This makes the app crash at launch with the error:

```
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
```

And as it turns out, it [looks like](https://i.imgur.com/RCnJdrA.png) Alamofire is not in copied over the final `.app`

An example project can be found [here](https://github.com/piercifani/HelloCocoapods)

## What did you do?

Attempt to create use a Cocoapods library from a framework instead of an app

## What did you expected to happen?

For the required framework to being linked correctly and the app being executed normally

## What happened instead?

The app crashes on launch and I had to go back to use the 0.39.0 version

## Podfile

```ruby
platform :ios, '9.0'
use_frameworks!  

abstract_target 'Hello' do
  pod 'Cartography'

  target 'HelloCocoapodsKit' do
    inherit! :search_paths
    pod 'Alamofire'
  end

  target 'HelloCocoapodsTests' do
    inherit! :search_paths
  end

  target 'HelloCocoapods'
end
```

**Comment by segiddins** [comment]
CocoaPods does not currently supporting integrating into framework or static library targets -- what we're working on for extensions will fix this eventually, however.

**Comment by piercifani** [comment]
The fact that it works on the 0.39 version is coincidental? Shall I move away from a Framework and create a Podspec instead?

**Comment by segiddins** [comment]
Yes.

**Comment by piercifani** [comment]
👍🏻 thanks
