### ISSUE TITLE
Add resources directly to framework, instead of using resource bundle

### ISSUE THREAD

**Issue by piercifani** [CocoaPods/CocoaPods#5192]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

I'd like to add resources directly to a framework instead of having to resort to using separate bundles. This was extremely useful when static libraries were the only way of building and distributing pods, but frameworks allow resources to be directly inside them, making resource bundles redundant.
## What did you expected to happen?

In order to access my resources from the framework, I'd like to write this code:

``` swift
private struct InterfaceBundle {
    private static let bundle = NSBundle(forClass: InterfaceKit.self)
    private class InterfaceKit: NSObject {}
}
```
## What happened instead?

...instead of this:

``` swift
private struct InterfaceBundle {
    private static let bundle = NSBundle(path: NSBundle(forClass: InterfaceKit.self).pathForResource("BSWInterfaceKit", ofType: "bundle")!)
    private class InterfaceKit: NSObject {}
}
```

**Comment by neonichu** [comment]
This should already be the case if you're using `spec.resources` instead of `spec.resource_bundle`. Are you seeing something different?

**Comment by piercifani** [comment]
Yes @neonichu, you are right, if I use your proposed solution it works correctly.

Sorry about this, but I completely ignored this option since on the [podspec](https://guides.cocoapods.org/syntax/podspec.html) specification it recommends using the `resource_bundle` instead. Now that I read into it, I don't it's accurate when it says "there can be name collisions using the resources attribute", since it's included in the framework built using the podspec, so the only name collision would be between two resources in the same framework with the same name. Or maybe I'm wrong (again 😁 )?

**Comment by neonichu** [comment]
You're right, I think this part of the documentation predates frameworks integration. @orta should we change this in the docs?

**Comment by dsarfati** [comment]
Just found this discussion after trying to figure out how the resources targets were being set. The docs seem to say that the resource_bundle is the right way of including resources. If that is not the case anymore due to the addition of frameworks, then the docs need to be updated.
[https://stackoverflow.com/questions/45015978/how-to-specify-a-cocoa-pod-asset-target](https://stackoverflow.com/questions/45015978/how-to-specify-a-cocoa-pod-asset-target/45029176#45029176)

**Comment by orta** [comment]
Sure, want to send us a PR updating it?
