### ISSUE TITLE
Defining subspecs will ignore base source_files

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#5201]
Cocoapods 1.0.0 beta 8
## First issue
I have a .podspec like:

    s.source_files = 'Pod/Classes/*.{h,m,swift}'

If I write this in my Podfile:

    pod 'MyPod', :path => '../', :subspecs => []

...then all base source_files will be missing.

## Second issue
I have a .podspec like:

    s.source_files = 'Pod/Classes/*.{h,m,swift}'
    s.subspec 'AAA' do |sp|
      sp.source_files = 'Pod/Classes/AAA/*.{h,m,swift}'
    end
    s.subspec 'BBB' do |sp|
      sp.source_files = 'Pod/Classes/BBB/*.{h,m,swift}'
    end

If I write this in my Podfile:

    pod 'MyPod/AAA', :path => '../'

...then all base source_files will be missing.

## Workaround
My current workaround is in two parts:
1) reinject all base source_files in each subspec
2) create an '!' subspec in case we don't want neither AAA or BBB subspecs. The name of '!' is because CocoaPods is fetching subspecs alphabetically, and we want the core files in this group.

So in the end my .podspec is like:

    s.subspec '!' do |sp|
      sp.source_files = 'Pod/Classes/*.{h,m,swift}'
    end
    s.subspec 'AAA' do |sp|
      sp.source_files = 'Pod/Classes/*.{h,m,swift}', 'Pod/Classes/AAA/*.{h,m,swift}'
    end
    s.subspec 'BBB' do |sp|
      sp.source_files = 'Pod/Classes/*.{h,m,swift}', 'Pod/Classes/BBB/*.{h,m,swift}'
    end

To avoid spreading the habit of an '!' subspec, fixing the inclusion of base source_files would be nice.

**Comment by neonichu** [comment]
You can solve your issue by instead using this as your podspec:

```ruby
s.default_subspec = 'Core'

s.subspec 'Core' do |sp|
  sp.source_files = 'Pod/Classes/*.{h,m,swift}'
end
s.subspec 'AAA' do |sp|
  sp.dependency 'YourPod/Core'
  sp.source_files = 'Pod/Classes/AAA/*.{h,m,swift}'
end
s.subspec 'BBB' do |sp|
  sp.dependency 'YourPod/Core'
  sp.source_files = 'Pod/Classes/BBB/*.{h,m,swift}'
end
```

By using `default_subspecs` you don't have to rely on implicit behaviour and by explicitly declaring the dependencies between your subspecs you won't have to repeat yourself.

**Comment by mrackwitz** [comment]
I can confirm that this is the supposed behavior, even though it might not always appear completely obvious, there are dozens of podspecs relying on this.
