### ISSUE TITLE
Header files are missing when trying to pod install  a closed-sourced archive

### ISSUE THREAD

**Issue by Lucashuang0802** [CocoaPods/CocoaPods#5204]
# Report

## What did you do?
> I was trying to push my closed-source framework to CocoaPod and it got uploaded successfully. But, all header files are missing when `pod install`. I exported it as a framework and zipped it. Since I wanted to make it closed-source so I upload the compressed file to Github as a downloadable link. The framework is called `OTAcceleratorPackUtil`(https://cocoapods.org/pods/OTAcceleratorPackUtil), BTW.

> Additional information: The `OTAcceleratorPackUtil` is built on top of a static library `OpenTok`.

## What did you expected to happen?

> I expected the pod to be installed successfully to my project and be able to see there has two header files.

## What happened instead?

> All header files is missing. It can't go throught the compiler

## Podfile
```ruby

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

target 'OneToOneSample' do 
  pod 'OpenTok', '~> 2.7.1'
  pod 'SVProgressHUD'
  pod 'OTAcceleratorPackUtil'
end

target 'OneToOneSampleTests' do 
  pod 'Kiwi'
end
```

**Comment by neonichu** [comment]
I was unable to try this, because there's a 403 when trying to install OpenTok:

```
Installing OpenTok (2.8.0)

[!] Error installing OpenTok
[!] /usr/bin/curl -f -L -o /var/folders/by/znchwbl51gdfht48wv0m4t6r0000gn/T/d20160428-1399-18pvylb/file.tbz https://tokbox.com/downloads/OpenTok-iOS-2.8.0.tar.bz2 --create-dirs --netrc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   116  100   116    0     0    358      0 --:--:-- --:--:-- --:--:--   359
curl: (22) The requested URL returned error: 403 Forbidden
```

**Comment by rkpradeep20** [comment]
Hey, neonichu. Were you able to download openttok framework? I'm getting the same error as you, while installing the pod file. If you have some workaround or info please share.

**Comment by Lucashuang0802** [comment]
Perhaps you guys can use the 2.7.1 version.

**Comment by rkpradeep20** [comment]
Sure, Thanks. I'll check it out.

**Comment by Lucashuang0802** [comment]
btw @rkpradeep20, I made it opened-source at version 1.0.0. If you want to give it a try, you need to install previous version like `0.1.*`. Thx.

**Comment by Lucashuang0802** [comment]
Seems that the link is invalid already. I will recover it tomorrow. I am just wondering what's the best guide to push closed-source framework to CocoaPods?
