### ISSUE TITLE
Delete old link target when upgrading from 0.39 to 1.0

### ISSUE THREAD

**Issue by skyline75489** [CocoaPods/CocoaPods#5208]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I upgraded my CocoaPods from 0.39 to 1.0 beta8. I didn't have any target setting in my old Podfile. I add a new target surrounding all my pods in order to follow the new target requirement.

## What did you expected to happen?

Everything should just works.

## What happened instead?

The compiling part was OK. But the linking part was not. After `pod install` I now have two libraries in `Link Binary With Libraries`:

* `libPods.a`
* `libPods-MyTarget.a`

I had to manually delete the old `libPods.a` to link those pods successfully.

## Podfile

Not really needed in this issue.

**Comment by segiddins** [comment]
Can you try running `pod deintegrate && pod install` and seeing if that fixes things?

**Comment by segiddins** [comment]
If not, we'd need to be able to investigate the project from before you upgraded to 1.0 to try and debug. Thanks!

**Comment by skyline75489** [comment]
Turns out `pod deintegrate` fixed this. 

However, my `xcodeproj` and `Podfile` are not in the same folder. And `pod deintegrate` is not actually looking for `project` in `Podfile`, but in the current directory. If I do `pod deintergrate` directly at where my `Podfile` is, it errors out:

>[!] A valid Xcode project file is required.

So I specified the path of `xcodeproj` and `pod deintegrate` before `pod install`. And everything finally works.

Still, I find the need of `pod deintegrate` vague and confusing. I don't see this in [Migration Guide](http://blog.cocoapods.org/CocoaPods-1.0/), nor in any command line output.

**Comment by segiddins** [comment]
Right, which is why I'm also asking for the project before you upgraded so we can actually see why automatic deintegration didn't happen.

**Comment by skyline75489** [comment]
This is a private project I've been working on with my friend. I'll come back later after I make contact with him.

**Comment by skyline75489** [comment]
OK. [This](https://github.com/AveryLiu/Kamplus-Pro) is the project we've been working on. The iOS project is in `Frontend` folder. For development we are not tracking `Pods/` and `Podfile.lock`. And we uses a mirror CocoaPods repo.

**Comment by segiddins** [comment]
Ah, so it turns out this is intentional: https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer.rb#L496. It would automatically de-integrate if your xcodeproj was in the root project directory, if not you do need to manually run `pod deintegrate`

**Comment by skyline75489** [comment]
Is this mentioned anywhere in the doc? If not I highly recommend adding this instruction. Or we could just enhance this behaviour by more places other than root directory.

**Comment by segiddins** [comment]
We considered glowing in other places, but concluded it would lead to too many false-positives.
