### ISSUE TITLE
Library not found for -lPods

### ISSUE THREAD

**Issue by dleviathan** [CocoaPods/CocoaPods#5209]
I have problem with build project. Although i have never taken that before with it.

>I have try all solutions in here
> [https://github.com/onmyway133/issues/issues/27](url)
> Or here 
> [http://guides.cocoapods.org/using/troubleshooting.html](url)
> even last, I had deintegrate pod and reinstall but error still appear.

This my pod file:

` platform :ios, '7.0'`
` target 'AppName' do`
`      pod 'NendSDK_iOS'`
`      pod 'NendSDK_iOS_MediationAdapter'`
`      pod 'Google-Mobile-Ads-SDK', '~> 7.0'`
`end`

And here error

> Ld /Users/dlev/Library/Developer/Xcode/DerivedData/AppName-dybnhqkacvunvodaihiwtfsysfjt/Build/Products/Debug-iphonesimulator/AppName.app/AppName normal x86_64
    cd /Users/dlev/Work/AppName
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/Users/dlev/Library/Developer/Xcode/DerivedData/AppName-dybnhqkacvunvodaihiwtfsysfjt/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/libxml2 -L/Users/dlev/Work/AppName/Pods/NendSDK_iOS/NendSDK_iOS-3.1.0/Nend/NendAd -L/Users/dlev/Work/AppName/Pods/NendSDK_iOS_MediationAdapter/NendSDK_iOS_MediationAdapter-1.2.4 -F/Users/dlev/Library/Developer/Xcode/DerivedData/AppName-dybnhqkacvunvodaihiwtfsysfjt/Build/Products/Debug-iphonesimulator -F/Users/dlev/Work/AppName/Pods/Google-Mobile-Ads-SDK/GoogleMobileAdsSdkiOS-7.7.1 -F/Users/dlev/Work/AppName/AppName -filelist /Users/dlev/Library/Developer/Xcode/DerivedData/AppName-dybnhqkacvunvodaihiwtfsysfjt/Build/Intermediates/AppName.build/Debug-iphonesimulator/AppName.build/Objects-normal/x86_64/AppName.LinkFileList -mios-simulator-version-min=7.0 -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lxml2 -lPods -all_load -ObjC -lAdapterNend -lNendAd -framework AVFoundation -framework AdSupport -framework AudioToolbox -framework CoreGraphics -framework CoreMedia -framework CoreTelephony -framework EventKit -framework EventKitUI -framework GoogleMobileAds -framework ImageIO -framework MediaPlayer -framework MessageUI -framework Security -framework StoreKit -framework SystemConfiguration -weak_framework AdSupport -ObjC -lxml2 -all_load -lNendAd -lAdapterNend -framework GoogleMobileAds -fobjc-link-runtime -framework ImageIO -framework MessageUI -framework CoreMedia -framework AVFoundation -weak_framework AdSupport -framework EventKitUI -framework EventKit -framework CoreTelephony -framework QuartzCore -framework CoreGraphics -framework AudioToolbox -framework Security -framework SystemConfiguration -framework UIKit -framework iAd -framework StoreKit -framework CFNetwork -framework MobileCoreServices -framework Foundation -lPods-AppName -Xlinker -dependency_info -Xlinker /Users/dlev/Library/Developer/Xcode/DerivedData/AppName-dybnhqkacvunvodaihiwtfsysfjt/Build/Intermediates/AppName.build/Debug-iphonesimulator/AppName.build/Objects-normal/x86_64/AppName_dependency_info.dat -o /Users/dlev/Library/Developer/Xcode/DerivedData/AppName-dybnhqkacvunvodaihiwtfsysfjt/Build/Products/Debug-iphonesimulator/AppName.app/AppName

### but when i go folder 
> /Users/dlev/Library/Developer/Xcode/DerivedData/AppName-dybnhqkacvunvodaihiwtfsysfjt/Build/Products/Debug-iphonesimulator/

### i still my libPod-AppName.a appeare here.

Any solution for this. Thanks support!

**Comment by neonichu** [comment]
This is likely related to remaining state in your project. Please check your linker flags and remove any custom values you have added, by hitting delete when the build setting is selected in the Xcode project editor. When editing linker flags, Xcode will copy the value from the XCConfig generated by CocoaPods and it can never be updated by CP again.

If it turns out this isn't the issue you are facing, please share a project to reproduce and we can reopen this issue.

**Comment by dleviathan** [comment]
My error had solved by config at Project -> Pods -> Configurations remove other configs, now only have 2 config (debug, release).
