### ISSUE TITLE
podfile with libraries or library not working with xcode

### ISSUE THREAD

**Issue by wws19125** [CocoaPods/CocoaPods#5210]
I was writing a podspec , I found that libraries or library not working with xcode
> s.library = "bz2"
> s.libraries =  "stdc++","xml2","z","bz2", "iconv"

i need to add them to my project by myself

**Comment by neonichu** [comment]
Please have a look at <https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md> and tell us what specifically isn't working and how we can reproduce your issue.

**Comment by wws19125** [comment]
Report
What did you do?

    ℹ Please replace this with what you did.
    pod MobileVLCKit
  the podspec file has already configed s.libraries, but that do not working,  I need to add the libraries by myself

What did you expected to happen?

   Install all  libraries correctly.

What happened instead?

    all the libraries were not beed installed 

Podfile

    ℹ Please paste the contents of your Podfile below.
  > s.frameworks = 'AudioToolbox', 'CoreAudio', 'OpenGLES', 'CFNetwork', 'CoreText', 'QuartzCore', 'CoreGraphics','AVFoundation','Security', 'UIKit'
  > s.vendored_frameworks = 'JHIndustryModule/MobileVLCKit.framework'
  > s.libraries =  "stdc++","xml2","z","bz2", "iconv"
