### ISSUE TITLE
Missing resources for 'vendored_libraries' when using 'use_frameworks!' in Podfile

### ISSUE THREAD

**Issue by vmatsnev** [CocoaPods/CocoaPods#5215]
# Report
## What did you do?

Trying to install AdToApp library.
## What did you expected to happen?

AdToApp static library will installed **with resources**.
## What happened instead?

AdToApp static library was installed **without resources.**
## Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

use_frameworks!

pod 'iRate'
pod 'AdToApp'
```

**Comment by neonichu** [comment]
This is happening because vendored static binaries are linked directly to the user target when using frameworks integration, but resources would be added to the Pod target, which is non-existent. Solution should be adding the resources to the user target as well.

**Comment by vmatsnev** [comment]
The solution for me was:
- commented use_frameworks!
- run pod deintegrate
- run pod install
- uncommented use_frameworks!
- run pod update

It looks like in this sequence of operation **Copy Pods Resources** script was added in Build Phases and resources also became available in compiled application.

It's not obvious for me why not to add **Copy Pods Resources** for vendored_libraries pods even if use_frameworks! is defined?

**Comment by neonichu** [comment]
It's a bug  ¯\\\_(ツ)\_/¯

**Comment by yahalawa** [comment]
any update on this bug?
