### ISSUE TITLE
Project is re-added to existing workspace

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#5216]
# Report
## What did you do?
1. Created a new project.
2. Saved the project as workspace.
3. Run `pod install`.
## What did you expected to happen?

CocoaPods would use the existing workspace and recognize the existing project file reference in there.
## What happened instead?

CocoaPods added the project a second time to the existing workspace.
## Podfile

``` ruby
workspace "MyExample.xcworkspace"

target "MyExample" do
    project "MyExample.xcodeproj"
end
```
## Workspace-Diff

``` diff
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
      location = "container:MyExample.xcodeproj">
   </FileRef>
   <FileRef
      location = "group:Pods/Pods.xcodeproj">
   </FileRef>
+   <FileRef
+      location = "group:MyExample.xcodeproj">
+   </FileRef>
</Workspace>
```
## Question

Are `group` and `container` interchangeable here?
## Hint

If the behavior should be changed, that would need to be done in `UserProjectIntegrator#create_workspace`. This expects that a possible existing file reference would be exactly equal to the one, which would be created, while matching values for `absolute_path` would be likely sufficient.

/c @neonichu

**Comment by segiddins** [comment]
@samdmarshall any hints about the difference between `group` and `container`?

**Comment by orta** [comment]
Any idea if this would be present using the Nanaimo?

**Comment by segiddins** [comment]
@orta unrelated
