### ISSUE TITLE
Enabling pod for list of configurations is ignored for its dependencies 

### ISSUE THREAD

**Issue by lukewar** [CocoaPods/CocoaPods#5220]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
```
pod --version
0.39.0
```
## What did you do?

I have few `Debug`-only pods. I did setup my Podfile as described in [Guide](https://guides.cocoapods.org/syntax/podfile.html#pod) section `Build configurations`.

`pod 'ReactiveCocoa', :configuration => 'Debug'`

Then installed pods. `pod install`.

## What did you expected to happen?

I expected that all pods, main and a all its dependency are going to be linked with specified `Debug` configuration.

## What happened instead?

As expected `ReactiveCocoa` is linked only with `Debug` configuration. But this pod has a dependency to `Result` pod. Unfortunately `Result` is linked with all configurations.

## Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'Example' do
	pod 'ReactiveCocoa', '~> 4.1.0', :configurations => ['Debug']
end
```

Example project: [Example.zip](https://github.com/CocoaPods/CocoaPods/files/240888/Example.zip)

**Comment by lukewar** [comment]
I have found a way to workaround this, by specifying configuration for dependencies as well
```ruby
pod 'Result', 					 :configurations => ['Debug']
```

**Comment by segiddins** [comment]
This is intentional. If you don't want result to be linked in release, you'll need to specify it manually

**Comment by lukewar** [comment]
That's interesting. As this feature often is used to integrate debug tools, it creates a threat of introducing into `Release` build code that is not secure enough or abuse private APIs.
Do you think we could revisit this and open for a discussion? I think that rule here should be rather inverse. User of a library should be explicit and specify need of using dependent pods for all configurations by adding it to the pod spec, like:
`pod 'Result', '~> 2.1.0'`

**Comment by neonichu** [comment]
While I think we all agree that it is a bit unintuitive to be this way, it was chosen to balance the build configuration feature with overall impact on the complexity of CocoaPods as a whole. 

However, thanks for pointing this out again, I just updated the docs with a remark on this in CocoaPods/Core#323.
