### ISSUE TITLE
Test target fails to compile with CocoaPods beta 8

### ISSUE THREAD

**Issue by Ruenzuo** [CocoaPods/CocoaPods#5221]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Using CocoaPods beta 8 with a parent/child target configuration.

## What did you expected to happen?

Test target to compile.

## What happened instead?

Xcode fails to build the testing target when referencing Pods from the parent target in tests.

## Podfile

```ruby
platform :ios, '9.0'

use_frameworks!

target 'Example' do
  pod 'Google-Mobile-Ads-SDK', '~> 7.5.0'

  target 'ExampleTests' do
    inherit! :search_paths
    pod 'Expecta'
  end
end
```

## Example project

Looking into the latest changes in CocoaPods, I found https://github.com/CocoaPods/CocoaPods/pull/5146. In fact, reverting https://github.com/CocoaPods/CocoaPods/pull/5146/commits/58a5c0436fec11a295200b1c192bdd9b7a6d000f fixes the issue.

You can reproduce it by checking out this repository: https://github.com/Ruenzuo/supreme-waffle
On the `master` branch, you'll find a project using beta 8 which fails to compile the testing target with the following error:

```
/Users/renzo.crisostomo/Downloads/Example/ExampleTests/ExampleTests.m:11:9: fatal error: 'GoogleMobileAds/GoogleMobileAds.h' file not found
#import <GoogleMobileAds/GoogleMobileAds.h>
        ^
1 error generated.
```

If you checkout `revert_58a5c04`, which it's the same as beta 8 just reverting 58a5c04, test target compiles perfectly. I tried to make sense out of it, but the fact is that both Header Search Paths and Framework Search Paths looks exactly the same, so maybe something is different with the inherited configurations between targets?

I would love to submit a PR if you point me in the right direction, or maybe this is expected behaviour and either my Podfile or my test target setup is wrong.

**Comment by neonichu** [comment]
This is probably a dupe of #5173.

I think the problem lies in the fact that there's no good way for `inherit! :search_paths` to work with static frameworks and it previously coincidentally worked because of the duplicated copies of headers in the sandbox. A potential fix might be adding a "deep" path into those frameworks to the header search path, e.g. `$(SRCROOT)/Pods/YOLO/YOLO.framework/Versions/A/Headers`.

**Comment by Ruenzuo** [comment]
Yes, looks like a duplicated issue.

Thanks for the detailed explanation, I get it now. I worked-around the issue by [duplicating the vendored static framework for the testing target](https://github.com/Ruenzuo/supreme-waffle/commit/8b765c1fa90d0c1d345fe04523c571ea5f5df19a). Hope this is of some help for people with similar issues.

I'll close the issue as there is https://github.com/CocoaPods/CocoaPods/issues/5173 to keep track of it.
