### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by lyricdon** [CocoaPods/CocoaPods#5224]
> I run this command

pod lib lint --use-libraries --allow-warnings --sources='http://gitlab-proxy.bbwc.cn/pods/slatespecs.git' --verbose  --no-clean

>  It show me this error : 
  
 'User/BBLoginAndRegisterControl.h' file not found 
  Why can dependency Notification, but User can't?
 
> my spec here 
  
```
Pod::Spec.new do |s|
  s.name         = "Slate"
  s.version      = "3.4.1"
  s.summary      = "Slate FrameWork."
  ...
  s.frameworks = 'Foundation', 'UIKit'
  s.dependency 'SlateCore', '~> 3.4.1'
  s.dependency 'ProtocolBuffer', '~> 0.1.0'

  # Notification
  s.subspec 'Notification' do |notification|
    notification.prefix_header_file = "Libs/Notification/Notification/Notification-Prefix.pch"
    notification.source_files  = 'Libs/Notification/Notification/*.{h,m}'
    notification.resource = 'Libs/Notification/Notification/*.proto'
  end

  # User
  s.subspec 'User' do |user|
    user.prefix_header_file = "Libs/User/User/User-Prefix.pch"
    user.source_files  = 'Libs/User/User/*.{h,m}'
    user.resource = 'Libs/User/Resources/*.{strings,xib}', 'Libs/User/User/*.proto'
  end

 # Card
  s.subspec 'Card' do |card|
    card.prefix_header_file = "Libs/Card/Card/Card-Prefix.pch"
    card.source_files  = 'Libs/Card/**/*.{h,m}'
    card.resource = 'Libs/Card/Card/Resource/*', 'Libs/Card/**/*.proto'
    card.dependency 'Slate/Notification'
    card.dependency 'Slate/User'
  end

end
```

**Comment by neonichu** [comment]
We won't really be able to debug this without having a full Pod which reproduces this. I would advise you to look at the generated Xcode project to figure out what is going wrong or post a reproducible example.

**Comment by lyricdon** [comment]
>can this work ?


Pod::Spec.new do |s|

  s.name         = "Slate"
  s.version      = "3.4.1"
  s.summary      = "Slate FrameWork."

  s.description  = <<-DESC
		   Now for Test.	
       This is the frameworks of the slate/webSlate
       It contains the basic packaged venders    
                   DESC
  s.homepage     = "http://gitlab-proxy.bbwc.cn/ios/slate3"
  s.license      = "MIT"
  s.author             = { "lyricdon" => "lyricdon@hotmail.com" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "http://gitlab-proxy.bbwc.cn/ios/slate3.git", :branch => "feature-pods" }
  
  s.frameworks = 'Foundation', 'UIKit'
  s.dependency 'SlateCore', '~> 3.4.1'
  s.dependency 'ProtocolBuffer', '~> 0.1.0'

  # User
  s.subspec 'User' do |user|
    user.prefix_header_file = "Libs/User/User/User-Prefix.pch"
    user.source_files  = 'Libs/User/User/*.{h,m}'
    user.resource = 'Libs/User/Resources/*.{strings,xib}', 'Libs/User/User/*.proto'
  end
  
  # Subscription
  s.subspec 'Subscription' do |subscription|
    #subscription.prefix_header_file = "Libs/Subscription/Subscription/Subscription-Prefix.pch"
    subscription.source_files  = 'Libs/Subscription/**/*.{h,m}'
    subscription.resource = 'Libs/Subscription/**/*.{strings,xib}', 'Libs/Subscription/Subsription/*.proto'
    subscription.dependency 'Slate/User'
  end

end

> what do you mean by generated Xcode project ?
   I can successfully done with subspec 'User', but when I denpency  Slate/User, It won't work

**Comment by neonichu** [comment]
Sorry, we cannot really do anything with this issue without a full Pod. I'm closing it for now.
