### ISSUE TITLE
pod skpsmtpmessage 

### ISSUE THREAD

**Issue by taojigu** [CocoaPods/CocoaPods#5225]
I pod search "skpsmtpmessage"  ,  it points to  "https://github.com/jetseven/skpsmtpmessage" , the last moment library code updated is 4 years ago.

I also add the skpsmtpmessage to my github (https://github.com/taojigu/skpsmtpmessage) and modify the code , it woks on iOS 9.

I wonder , whether I could replace my "skpsmtpmessage" with the current one in pod.

Thank you.

**Comment by segiddins** [comment]
Nope, you'll need to contact the person who owns the pod on trunk. `pod trunk info skpsmtpmessage` will give you the email address they registered with.

**Comment by taojigu** [comment]
My I registera new trunk with another name ?

**Comment by orta** [comment]
[It's currently unclaimed](https://cocoapods.org/pods/skpsmtpmessage), so you could sign up and register for ownership on https://trunk.cocoapods.org
