### ISSUE TITLE
exclude_files not overriding preserve_paths

### ISSUE THREAD

**Issue by ajmacd** [CocoaPods/CocoaPods#5229]
I'm working on distributing a library via a private pod. The files are specified with the `preserve_paths` rule. The downstream project will install it based on a git hash, with submodules enabled. The resulting files in the root repository are correct, but the submodule behavior is surprising.

If I use a glob pattern without a file extension, (e.g. `preserve_files = 'foo/*, foo/**/*'`) hidden files in the submodule are included after the pod install, and in particular the `.git` file. Even if I attempt to exclude those files with `exclude_files  = 'foo/**/.git'`, they appear.

Using glob patterns with extensions (e.g. `preserve_files = 'foo/*.cc'`) removes the `.git` file as expected.

I've reproduced this behavior using version 0.39, 1.0beta8 and a build from source (37e120b).

I have a sample project that demonstrates it here:
https://github.com/ajmacd/pod-playground

```
git clone https://github.com/ajmacd/pod-playground
cd pod-playground
pod update
ls -a Pods/pod-playground/foo/pod-playground-submodule
```

reveals the errant `.git` file.
- [x] I've read and understood the [CONTRIBUTING guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) and have done my best effort to follow.

**Comment by segiddins** [comment]
Someone will probably need to dig into how `PathList` handles `exclude_files` in https://github.com/CocoaPods/CocoaPods/blob/367eed70ec75e5d145fa98c21adc78f9652011ae/lib/cocoapods/sandbox/path_list.rb#L136 to understand why this is happened, though I'd agree that it's a bug

**Comment by segiddins** [comment]
This is happening due to the `path.include?(candidate) || candidate.include?(path)` and the `/*` in the preserve path in the spec

**Comment by segiddins** [comment]
Sorry, I can't figure out how to fix this :(

**Comment by ajmacd** [comment]
Thanks for investigating! In case anyone else comes across this, I'm using the `prepare_command` podspec hook as a workaround:
`prepare_command = 'find lib -name ".git" -exec rm {} \;'`

**Comment by mrackwitz** [comment]
:warning: You have to be very careful with that. Running `pod lib lint` to lint your pod in place or using the pod as development pod would nuke the `.git` history.
