### ISSUE TITLE
Overwriting xcconfig files.

### ISSUE THREAD

**Issue by ErikEvenson** [CocoaPods/CocoaPods#523]
Currently, `pod install` overwrites the configurations set if an Xcode project is already using .xcconfig files to manage its configuration.

I would suggest adding an option that lets the user include the `Pods.xcconfig` file rather than to silently overwrite the existing information.  Something like:

```
#include "Pods.xcconfig"
```

Also, make sure the configuration settings append to rather than rewrite any configuration settings.

**Comment by iosdevben** [comment]
Still an issue in 2019.

$inherited does not prevent pre-existing values from being overwritten.
