### ISSUE TITLE
pod trunk push results in 403 when referencing large zip files

### ISSUE THREAD

**Issue by macmacen** [CocoaPods/CocoaPods#5234]
# Report
## What did you do?

```
pod --verbose trunk push <Name>.podspec
```
## What did you expected to happen?

Podspec file pushed to cocapods trunk server.
## What happened instead?

403 error occurred:
Source code for your Pod was not accessible to CocoaPods Trunk. Is it a private repo or behind a username/password on http?

In Pod spec file: Source references a zip file on Github added to a Github Release Tag.
The Repository is public available.
The zip file is about 170 MB.
If we use a smaller zip file (around 7 MB) than it works as expected.
## Podspec

``` ruby
...
s.source = { :http => 'http://github.com/<company>/<identifier>/releases/download/<file>.zip'}
...
```

**Comment by segiddins** [comment]
What's the content of the podspec? Looks like it would be an issue with CocoaPods/trunk.cocoapods.org if the source really is publicly accessible.

**Comment by macmacen** [comment]
Here is my anonymized podspec file:

```ruby
Pod::Spec.new do |s|

  s.name         = "<SDK>"
  s.version      = "1.0.0"
  s.summary      = "..."
  s.license      = { :type => "Commercial", :file => "<SDK>/LICENSE.md" }
  s.author       = { "John Doe" => "john@doe.com" }
  s.source       = { :http => 'http://github.com/<company>/<identifier>/releases/download/<file>.zip'}
  s.homepage	 = "https://www.<SDK>.de"
  s.platform = :ios
  s.ios.deployment_target = '7.0'
  
  s.requires_arc = true
  s.source_files = '<SDK>/include/*.h'
  s.resources = ["<SDK>/resources/*.jpg"]
  s.vendored_libraries = '<SDK>/<SDK>-universal.a'
  s.preserve_paths = '**/*.*'
  s.module_map = '<SDK>/include/module.modulemap'
  s.frameworks = 'Accelerate', 'WebKit'
  s.libraries = 'z'
  s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(PODS_ROOT)/<SDK>/<SDK>/include' }
  
  s.dependency 'AFNetworking', '~> 2.6.3'
  
end
```

Yes i double checked it, the zip file is public available.

**Comment by segiddins** [comment]
We can't really investigate if it's anonymized, sorry. You'll have to dig into the trunk.cocoapods.org PodsController yourself.

**Comment by neonichu** [comment]
Once the trunk push succeeds, the podspec will be publicly visible anyway. So I'm not really sure why you would need to anonymise it?

**Comment by macmacen** [comment]
We have some new findings:
Using the same (large) zip file on another server (not Github) works like expected.
So it seems like an issue accessing large files on Github. 
Maybe its a redirect issue.

The non working pod spec:

```ruby
Pod::Spec.new do |s|

  s.name         = "IDnowSDK"
  s.version      = "2.2.0"
  s.summary      = "Provides functionality for instantiating a video and/or photo identification."
  s.license      = { :type => "Commercial", :file => "idnow-sdk/LICENSE.md" }
  s.author       = { "Armin Bauer" => "armin.bauer@idnow.de" }
  s.source       = { :http => 'https://github.com/idnow/de.idnow.ios/releases/download/de.idnow.ios-2.2.0/idnow-ios-2.2.0.tar.gz'}
  s.homepage	 = "https://www.idnow.de"
  s.platform = :ios
  s.ios.deployment_target = '7.0'
  
  s.requires_arc = true
  s.source_files = 'idnow-sdk/include/*.h'
  s.resources = ["idnow-sdk/resources/*.jpg", "idnow-sdk/resources/IDNowImages.xcassets", "idnow-sdk/resources/IDnowSDKLocalization.bundle"]
  s.vendored_libraries = 'idnow-sdk/libidnow-sdk-universal.a'
  s.preserve_paths = '**/*.*'
  s.module_map = 'idnow-sdk/include/module.modulemap'
  s.frameworks = 'Accelerate', 'WebKit'
  s.libraries = 'z'
  s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(PODS_ROOT)/IDnowSDK/idnow-sdk/include' }
  
  s.dependency 'Masonry', '~> 0.6.3'
  s.dependency 'SocketRocket', '~> 0.4'
  s.dependency 'AFNetworking', '~> 2.6.3'
  s.dependency 'UIAlertView+Blocks', '~> 0.8.1'
  s.dependency 'OpenTok', '~> 2.6.1'
end
```

Working pod spec:
```ruby
Pod::Spec.new do |s|

  s.name         = "IDnowSDK"
  s.version      = "2.2.0"
  s.summary      = "Provides functionality for instantiating a video and/or photo identification."
  s.license      = { :type => "Commercial", :file => "idnow-sdk/LICENSE.md" }
  s.author       = { "Armin Bauer" => "armin.bauer@idnow.de" }
  s.source       = { :type => "zip", :http => 'https://downloads.idnow.de/ios/idnow-ios-2.2.0.tar.gz'}
  s.homepage	 = "https://www.idnow.de"
  s.platform = :ios
  s.ios.deployment_target = '7.0'
  
  s.requires_arc = true
  s.source_files = 'idnow-sdk/include/*.h'
  s.resources = ["idnow-sdk/resources/*.jpg", "idnow-sdk/resources/IDNowImages.xcassets", "idnow-sdk/resources/IDnowSDKLocalization.bundle"]
  s.vendored_libraries = 'idnow-sdk/libidnow-sdk-universal.a'
  s.preserve_paths = '**/*.*'
  s.module_map = 'idnow-sdk/include/module.modulemap'
  s.frameworks = 'Accelerate', 'WebKit'
  s.libraries = 'z'
  s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(PODS_ROOT)/IDnowSDK/idnow-sdk/include' }
  
  s.dependency 'Masonry', '~> 0.6.3'
  s.dependency 'SocketRocket', '~> 0.4'
  s.dependency 'AFNetworking', '~> 2.6.3'
  s.dependency 'UIAlertView+Blocks', '~> 0.8.1'
  s.dependency 'OpenTok', '~> 2.6.1'
end
```

Thanks for your fast response!

**Comment by neonichu** [comment]
If I try to access the files from your repo's releases via `curl`, I'm also getting a 403 — so seems like a :octocat: thing to me.

```
$ curl -sLI 'https://github.com/idnow/de.idnow.ios/releases/download/de.idnow.ios-2.2.0/idnow-ios-
2.2.0.zip'
[…]
HTTP/1.1 403 Forbidden
x-amz-request-id: 02B8C9076DD8E871
x-amz-id-2: YtSTFGuC05P7WovrSIzZaH7v+4Dm8rtSWG+FBUXD9xV/z/+OfBCTVfkqbmTAgKBZ1fGeDJWQbPM=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Mon, 02 May 2016 15:17:22 GMT
Server: AmazonS3
```

**Comment by dunkelstern** [comment]
Seems like amazon S3 buckets do not allow `HEAD` requests with the same key as a `GET` request, if you call a `GET` request on that file it works as intended. This is kind of a github issue as they give you the wrong signed URL on a `HEAD` request (the forward location is signed for `GET` only, not for `HEAD`)

**Comment by neonichu** [comment]
Hm, looks like trunk should be already using `HTTP.validate_url` which will fallback to `GET` if `HEAD` fails with an error. I'll have a closer look.

**Comment by neonichu** [comment]
What's actually happening here is that since `HEAD` doesn't succeed the `GET` fallback is being used, but there's also a 5 sec timeout in trunk, which is then being hit. In the second case, the `HEAD` request succeeds and therefore does submission to trunk.

I don't have a good idea for a solution, maybe special case GH releases and already accept the initial 301 as an accessible source?

**Comment by dunkelstern** [comment]
I already mailed Github support with a link back to this issue, perhaps they could fix it as it is their bug basically. We put the zip file onto another server until this can be resolved.

**Comment by dunkelstern** [comment]
Response from Github Support:

> I'm afraid HEAD requests aren't currently supported at this time. 
> We have logged an issue internally to review this though.
>
> I can't promise if/when we would implement but please be assured this is on our radar.

So it seems a workaround would be the best bet.

**Comment by tux-mind** [comment]
By searching a little more I found that the responsable is the way s3 handle requests to S3 buckets, as explained [in this SO question](https://stackoverflow.com/questions/27469801/403-forbidden-error-on-s3-rest-api-head-request).

Even if github will support HEAD requests by forging requests signed with HEAD methods those links will not be valid for a successive GET operation.

So you'll need to manage the `*.s3.amazonaws.com` domain in a different way in [http.rb](https://github.com/CocoaPods/Core/edit/master/lib/cocoapods-core/http.rb), if you get an URL using HEAD you cannot use it for a GET.

Thank you for your time and work, cheers :blush:
