### ISSUE TITLE
CheckSum in Podfile.lock

### ISSUE THREAD

**Issue by MickeyHub** [CocoaPods/CocoaPods#5235]
I update with `pod update`, and not all updated libraries I want to use, so I picked some necessary libs in Podfile and Podfile.lock to commit and push, and I found the CHECKSUM changes in Podfile.lock, I do not know whether to pick it for other develops in team, and I found no detail or description in https://cocoapods.org/, so I do not know what is CHECKSUM, and what is the responsibility.

**Comment by orta** [comment]
The checksum is the SHA of the Podfile at the time of `pod install`

**Comment by neonichu** [comment]
Checksum generation happens here: <https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/podfile.rb#L226>
