### ISSUE TITLE
Problem with pod rc1 missing --no-integrate 

### ISSUE THREAD

**Issue by jspenc72** [CocoaPods/CocoaPods#5240]
rc1 is missing --no-integrate flag
# Report
## What did you do?
```bash
$ gem install cocoapods -v 1.0.0.rc.1
$ pod install --no-integrate --no-repo-update
[!] Unknown option: `--no-integrate`
Did you mean: --no-ansi?
Usage:

    $ pod install

      Downloads all dependencies defined in `Podfile` and creates an Xcode Pods
      library project in `./Pods`.

      The Xcode project file should be specified in your `Podfile` like this:

          project 'path/to/XcodeProject.xcodeproj'

      If no project is specified, then a search for an Xcode project will be made. If
      more than one Xcode project is found, the command will raise an error.

      This will configure the project to reference the Pods static library, add a
      build configuration file, and add a post build script to copy Pod resources.

Options:

    --repo-update                       Force running `pod repo update` before install
    --project-directory=/project/dir/   The path to the root of the project directory
    --silent                            Show nothing
    --verbose                           Show more debugging information
    --no-ansi                           Show output without ANSI codes
    --help                              Show help banner of specified command
```
## What did you expected to happen?
> e.g. Install all pods but skip integration

## What happened instead?
Got this error
```bash
[!] Unknown option: `--no-integrate`
Did you mean: --no-ansi?
Usage:

    $ pod install

      Downloads all dependencies defined in `Podfile` and creates an Xcode Pods
      library project in `./Pods`.

      The Xcode project file should be specified in your `Podfile` like this:

          project 'path/to/XcodeProject.xcodeproj'

      If no project is specified, then a search for an Xcode project will be made. If
      more than one Xcode project is found, the command will raise an error.

      This will configure the project to reference the Pods static library, add a
      build configuration file, and add a post build script to copy Pod resources.

Options:

    --repo-update                       Force running `pod repo update` before install
    --project-directory=/project/dir/   The path to the root of the project directory
    --silent                            Show nothing
    --verbose                           Show more debugging information
    --no-ansi                           Show output without ANSI codes
    --help                              Show help banner of specified command
```
## Podfile
```ruby
platform :ios, '9.3'
pod 'AFNetworking/Serialization', '3.1.0'
pod 'AFNetworking/Security', '3.1.0'
pod 'AFNetworking/Reachability', '3.1.0'
pod 'AFNetworking/NSURLSession', '3.1.0'
pod 'AFNetworking/UIKit', '3.1.0'
```

**Comment by orta** [comment]
This isn't deleted, it's been moved to [inside the Podfile](http://blog.cocoapods.org/CocoaPods-1.0/#options-to-install!)

``` ruby
platform :ios, '9.3'
install! 'cocoapods', :integrate_targets => false
pod 'AFNetworking/Serialization', '3.1.0'
pod 'AFNetworking/Security', '3.1.0'
pod 'AFNetworking/Reachability', '3.1.0'
pod 'AFNetworking/NSURLSession', '3.1.0'
pod 'AFNetworking/UIKit', '3.1.0'
```

**Comment by jspenc72** [comment]
This flag is needed to maintain compatibility with the xamarin command line tool objective sharpie. 
Are there any plans to add the flag as a command line option as well?

**Comment by jspenc72** [comment]
https://developer.xamarin.com/guides/cross-platform/macios/binding/objective-sharpie/

**Comment by orta** [comment]
This is totally new to us, [heh](https://xkcd.com/1172/), I'd happily discuss ways to work with automated tools in this way - @CocoaPods/core could sharpie use a scoped config? Guess global might not be a good idea ( though they could turn the setting on, then off I guess )

**Comment by neonichu** [comment]
Looks like the tool is generating its `Podfile`, so it should just add `install! 'cocoapods', :integrate_targets => false` to file it is generating.

**Comment by orta** [comment]
Aye, submitted a bug: https://bugzilla.xamarin.com/show_bug.cgi?id=40822

**Comment by abock** [comment]
I've just released [Objective Sharpie 3.1](http://forums.xamarin.com/discussion/67908/objective-sharpie-3-1) which supports (and requires) CocoaPods 1.0 or newer by using @neonichu's suggestion of using `:integrate_targets => false` in the generated Podfile.

Thanks!

**Comment by AliSoftware** [comment]
Thx for the follow-up @abock :+1:

**Comment by jspenc72** [comment]
Thanks for the lightning fast response!!! ⚡️🔥

**Comment by michael-r-may** [comment]
This page on the site needs updating to reference this new way of doing --no-intregrate

http://guides.cocoapods.org/terminal/commands.html#pod_install

**Comment by orta** [comment]
Cool, want to look at updating that?

**Comment by michael-r-may** [comment]
Oh wow, this totally got lost in my inbox. Anyway, yeah I can do that. No idea how though!

**Comment by awgeorge** [comment]
Trying the following from http://guides.cocoapods.org/using/faq.html

>Note that CocoaPods itself does not require the use of a workspace. If you prefer to use sub-projects, you can do so by running pod install --no-integrate, which will leave integration into your project up to you as you see fit.

Perhaps this should be changed too if it's no longer relevant.
