### ISSUE TITLE
Analyzer rejects Podfiles with dependencies exclusively used in abstract targets

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#5242]
# Report

## What did you do?

Run `pod install`.

## What did you expected to happen?

The installation to succeed.

## What happened instead?

The installation is aborted with an error:
>[!] The dependency `Fabric` is not used in any concrete target.

## Podfile

e.g. based on the guides

```ruby
# Optional to reproduce
install! 'cocoapods', :integrate_targets => false

abstract_target 'Shows' do
    pod 'Fabric'

    target 'ShowsiOS' do
        platform :ios, '9.0'
    end
end
```

**Comment by segiddins** [comment]
Please be more specific with the expected behavior -- what does succeeding look like? Should ShowsiOS include Fabric even though there's a platform mismatch?

**Comment by mrackwitz** [comment]
>Should ShowsiOS include Fabric even though there's a platform mismatch?

How is there a platform mismatch?

**Comment by segiddins** [comment]
Because the abstract target doesn't declare a platform

**Comment by mrackwitz** [comment]
Why would the abstract target require an explicit platform? Isn't it just a container which allows to declare shared dependencies?

**Comment by segiddins** [comment]
Probably?

**Comment by orta** [comment]
Yeah, I think that's what I'd expect it to be 👍
