### ISSUE TITLE
libpods.a not found

### ISSUE THREAD

**Issue by sara-shokry** [CocoaPods/CocoaPods#5245]
# Report
I cab't archive or run  the project because of libpods.a not found 
cocoapods version 0.39.0

## What did you do?
> i deleted  pods related and run pod install again 
> checked pods configurations same as target configurations 

## Podfile

> platform :ios, '8.0'
>inhibit_all_warnings!
>use_frameworks!
>source 'https://github.com/CocoaPods/Specs.git'
>pod 'AFNetworking', '~> 2.2'
>pod 'Appirater', '~> 2.0'
>pod 'DVCoreDataFinders', '~> 0.5'
>pod 'GoogleAnalytics-iOS-SDK', '~> 3.0'
>pod 'IAPManager', '~> 0.2'
>pod 'JSQMessagesViewController', '~> 6.1.3'
>pod 'MCNotificationManager', '~> 0.1'
pod 'NSString-Hashes', '~> 1.2'
>pod 'Reachability', '~> 3.2'
>pod 'SVProgressHUD', '~> 1.0'
>pod 'SVPullToRefresh', '~> 0.4'
>pod 'TFGRelativeDateFormatter', '~> 1.0'
>pod 'XMPPFramework', :git => 'https://github.com/projecttoe/XMPPFramework'
>pod 'LayerKit', '~> 0.20.2'
>pod 'Atlas'
>pod 'UIImageEffects'

**Comment by segiddins** [comment]
Can you try with the CocoaPods 1.0 release candidate, please?

**Comment by sara-shokry** [comment]
when i run pod install again after new installation 
i got this warnings

[!] The `Project  [Debug - Dev]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug - dev.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Project  [Debug - Production]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug - production.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Project  [Release - Production]` target overrides the `FRAMEWORK_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods/Pods.release - production.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.


which not found before

**Comment by segiddins** [comment]
Did you address the warnings?

**Comment by sara-shokry** [comment]
can't fix it, can you plz guide me how to fix?

**Comment by orta** [comment]
A quick google for [this results](https://encrypted.google.com/search?hl=en&q=libpods%20not%20found) in a lot of answers to your question, this one looks comprehensive, - https://github.com/onmyway133/issues/issues/27

**Comment by sara-shokry** [comment]
after i follow many steps of @orta thread i can run the project on device/simulator but still can't archive it.
