### ISSUE TITLE
pod init on new Cocoa Touch Framework results in error at run time

### ISSUE THREAD

**Issue by JRG-Developer** [CocoaPods/CocoaPods#5256]
🌈 I've read and understood the [CONTRIBUTING](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) guidelines and have done my best effort to follow these.

### Overview

On the latest CocoaPods release version `1.0.0.rc.1`, `pod init` on new `Cocoa Touch Framework` results in error at runtime:

> The bundle [Project_Name]Tests couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
> ...
> Library not loaded: @rpath/[Library from main target]
> Referenced from: [Unit test targer location]
> Reason: image not found).

### What did you do?

Here's the verbose, step-by-step instructions to reproduce. I've also created a [demo project](https://github.com/JRG-Developer/CocoaPodsSearchPathsBug) showing this error.

(1) Create a new Xcode project of type `Cocoa Touch Framework` (dynamic framework), making sure `Include Unit Tests` is checked.
(2) Close the newly created project.
(3) Open Terminal, `cd` into the new project's directory, and run `pod init`.
(4) Open the `Podfile` and do the following:

- Uncomment `platform :ios, '9.0' `
- Ensure `use_frameworks!` is _not_ commented (default)
- Ensure `inherit! :search_paths` is _not_ commented (default)
- Add a Swift pod to the main target (any is okay, but I used `pod 'Alamofire', '~> 3.3'`)
- Add a Swift pod to the unit test target (any is okay, but I used `pod 'EVReflection', '~> 2.28')

(5) Close the `Podfile` and back in Terminal run `pod install`.
(6) Open the new workspace.
(7) Try to run unit tests.
(8) Observe said error above is received at runtime.

### What did you expected to happen?

Unit tests should run without errors at runtime given the above setup.

### What happened instead?

Above error received at runtime.

### Podfile

    platform :ios, '9.0'

    target 'CocoaPodsSearchPathsBug' do
      use_frameworks!

      pod 'Alamofire', '~> 3.3'

      target 'CocoaPodsSearchPathsBugTests' do
        inherit! :search_paths  # results in linker error, `Library not loaded`, at runtime

        pod 'EVReflection', '~> 2.28'
      end
    end

### Error Cause

This appears to be caused by the default inclusion of `inherit! :search_paths` within the default `pod init` generated `Podfile`.

Removing this line and re-running `pod install` resolves this error.

I've also checked this doesn't have any problems in an app project, and it doesn't appear to have any negative consequence (unit tests build fine with or without this line in an app project).

Recommendation: can `pod init` _not_ add `inherit! :search_paths` by default?

**Comment by JRG-Developer** [comment]
This issue may be related to #4714, but this is unclear as this other issue doesn't have a full description.

**Comment by segiddins** [comment]
No, the issue here is that CocoaPods does not yet support integrating into frameworks or static libraries.

**Comment by JRG-Developer** [comment]
> No, the issue here is that CocoaPods does not yet support integrating into frameworks or static libraries.

I'm confused as I've been doing this...?

**Comment by segiddins** [comment]
It's unsupported.

**Comment by JRG-Developer** [comment]
Unit tests target depending on framework/library is unsupported?

As CocoaPods defines a syntax for pod spec dependencies, surely libraries / dynamic framework creation via CocoaPods is supported.

Can you clarify what you mean by "it's unsupported?"

**Comment by segiddins** [comment]
Integrating pods with your own framework or library targets is unsupported -- only integrating with apps or  app extensions is something that we support at the moment.

**Comment by JRG-Developer** [comment]
One of the main benefits of CocoaPods is that it defines a syntax where pod specs can declare _other pods_ that they need, i.e. `s.dependency` syntax. 

This has been possible for a while; I believe several years now?

In order to locally develop pods, a la TDD-style, we need a mechanism to be able to declare which pods are being used locally during development.

I'd speculate that many, many existing pods use a `Podfile` to pull in needed dependencies, even for dynamic frameworks or libraries.

Has this only worked "by coincidence" per se? Further, is this explicitly something that's not recommended? And if so, what's the general consensus on developing pods as a library/framework that depend on other pods?

IMHO, this seems like a critical feature that CocoaPods should support.

**Comment by segiddins** [comment]
> what's the general consensus on developing pods as a library/framework that depend on other pods

testing the pod inside an app -- see how `pod lib create` does it

**Comment by JRG-Developer** [comment]
Ok, this was a "bug ticket," yet this seems like a completely different scoped "feature request."

In lieu of this, I'm closing this issue...

Thanks for the clarification, @segiddins 😄
