### ISSUE TITLE
error after 'Analyzing Dependencies' ,[!] An unexpected version directory `WebCore` was encountered for the......

### ISSUE THREAD

**Issue by DragonNightShade** [CocoaPods/CocoaPods#5257]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> ℹ Please replace this with what you did.  
> e.g. Run `pod install`

## What did you expected to happen?

> ℹ Please replace this with what you expected to happen.  
> e.g. Install all pod dependencies correctly.

## What happened instead?

> ℹ Please replace this with of what happened instead.  
> e.g. Pod A is missing the subspec B for target C.

## Podfile

> ℹ Please paste the contents of your Podfile below.    
>  (e.g. via `cat Podfile | pbcopy`)  
> You can remove this hint then.

```ruby
# Paste your Podfile contents HERE.
```

**Comment by DragonNightShade** [comment]
can you tell me an solution or suggest to a post, am a newbie:-)

On Fri, May 6, 2016 at 2:27 AM, Samuel Giddins <notifications@github.com>
wrote:

> Closed #5257 <https://github.com/CocoaPods/CocoaPods/issues/5257>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CocoaPods/CocoaPods/issues/5257#event-651958413>
>



-- 
   Regards & Best Wishes..
      *ACHINTYA GUPTA*
      Link To:LinkedIn.. <http://in.linkedin.com/in/guptaachintya>
      Link To:Email I-D <Email-accy.gupta@gmail.com>

**Comment by segiddins** [comment]
You didn't fill out the issue template, if you do so we can try and help ;)

**Comment by DragonNightShade** [comment]
is template alright now?

**Comment by segiddins** [comment]
Have a look at https://guides.cocoapods.org/syntax/podfile.html#source -- you're specifying the source for the pod rather than the source for the specs repo.
