### ISSUE TITLE
FEATURE REQUEST : Installing private pods from file hosting servers with credentials support as zip file

### ISSUE THREAD

**Issue by pkhetrapal** [CocoaPods/CocoaPods#5262]
I have a scenario where I need to only allow those people to whom I have provided the access-keys/credentials to download and use my pod. I am hosting my private pod on a file hosting server as a zip file. The file hosting service provides me with an API to download the latest file automatically using a dynamic URL

`curl "https://<username>:<access_key>@hostname.com/content/<user>/<repo>/<path>/<of>/<file>/$latest/<filename>-$latest.jar;bt_package=<package_name>" -JLOv`

where, `$latest` is the resolved at runtime.

Is there a possibility to add the support to the Podfile to download the zip file directly, something like

`pod 'MyLibrary', :http => 'https://<user>:<password>@dynamic-url.com'`

**Comment by segiddins** [comment]
you can already do that, see https://guides.cocoapods.org/syntax/podfile.html#pod for more information

**Comment by pkhetrapal** [comment]
Thanks for the info, though I am still confused.
1) Cocoapod-keys is used to import keys in the code. I want the keys to be used to download the pods from a private file hosting server.

2) If can use the URL with credentials in the `:podspec` tag in the `pod` command, but how can I pass the credentials or access the source URL with credentials in the podspec file

**Comment by segiddins** [comment]
That's not possible, and is outside the purview of CocoaPods -- keep in mind you can write plugins or just straight use ruby in your podfile

**Comment by pkhetrapal** [comment]
Can you please give me an example of adding a downloaded framework file (using ruby in podfile) to my application using ruby?

**Comment by segiddins** [comment]
you can do `pod 'MyLibrary', :http => "whatever code you need to get the URL"`

**Comment by pkhetrapal** [comment]
I tried that but it was failing while installing the pod in the application. I have an issue opened for that too.

https://github.com/CocoaPods/CocoaPods/issues/5100

**Comment by orta** [comment]
This technique works for PSPDFKit I believe ( [though they use](https://pspdfkit.com/guides/ios/current/getting-started/using-cocoapods/) `:podspec`)

**Comment by pkhetrapal** [comment]
Thanks @orta for the help.

I can use the same method :podspec` that PSPDFKit are using but I am not sure how they are resolving the access key in the `s.source` at runtime.

Any ideas on how to solve that problem?
