### ISSUE TITLE
>  Xcode project navigator is not showing any pod installed libraries. I have tried with fresh project but the result is same. 

### ISSUE THREAD

**Issue by Sudhir007** [CocoaPods/CocoaPods#5267]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> ℹ Please replace this with what you did.  
> e.g. Run `pod install`

## What did you expected to happen?

> ℹ Please replace this with what you expected to happen.  
> e.g. Install all pod dependencies correctly.

## What happened instead?

> ℹ Please replace this with of what happened instead.  
> e.g. Pod A is missing the subspec B for target C.

## Podfile

> ℹ Please paste the contents of your Podfile below.    
>  (e.g. via `cat Podfile | pbcopy`)  
> You can remove this hint then.

```ruby
# Paste your Podfile contents HERE.
```

**Comment by Sudhir007** [comment]
<img width="255" alt="screen shot 2016-05-07 at 5 51 13 pm" src="https://cloud.githubusercontent.com/assets/9363616/15092105/8224635e-147d-11e6-8696-09c6b1e654d7.png">

**Comment by orta** [comment]
Please fill in the issue template, @Sudhir007 - this gives us very little to work with.

**Comment by neonichu** [comment]
Closing because of lack of response.

**Comment by maxvonhippel** [comment]
@Sudhir007 this issue is often caused by opening the .xcodeproj instead of the .xcworkspace, so that may be the issue.
