### ISSUE TITLE
[1.0.0] Can't find symbols in Pod header, yet the header is there and symbol navigation works

### ISSUE THREAD

**Issue by jshier** [CocoaPods/CocoaPods#5276]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Attempting to the use `3_0_0` branch of AFNetworkActivityLogger results in symbols in the non-AFNetworkActivityLogger.m/h files being unavailable to the client application. For example, attempting to load the `AFNetworkActivityLoggerProtocol` type results in the unknown symbol compiler error.

## What did you do?

I've created a demo project which replicates this issue [here](https://github.com/jshier/PodHeaderUndeclared). It points to my own fork of AFNetworkActivityLogger that I made to try different `podspec` implementations. None of my changes have helped. It includes the `Pods` folder.

## What did you expected to happen?

Types in all of the included source code should be available to the client application.

## What happened instead?

The compiler can't find anything that isn't declared in the AFNetworkActivityLogger.m/h files, yet the pod itself builds fine.

## Podfile

```ruby
platform :ios, '9.0'

target 'LoggerTest' do
  pod 'AFNetworkActivityLogger', :git => 'https://github.com/jshier/AFNetworkActivityLogger', :branch => "3_0_0"
  pod 'AFNetworking'
end
```

**Comment by k0nserv** [comment]
The syntax referencing the logger is incorrect.

```objective-c
AFNetworkActivityLoggerProtocol *logger = ...
```
is not valid objective-C

for Protocols you want

```objective-c
id<AFNetworkActivityLoggerProtocol> logger = ...
```

which does work with your provided project :)

**Comment by jshier** [comment]
Oh yeah. A side effect of  programming in Swift for the last year. Thanks.

**Comment by k0nserv** [comment]
It happens :) Great issue report by the way
