### ISSUE TITLE
Xibs are not successfully compiled when minimum target is set to 7.0

### ISSUE THREAD

**Issue by luosheng** [CocoaPods/CocoaPods#5282]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

One of our internal libraries `A` specifies an xib (`test.xib`) as its resource in the pod spec file. I installed Cocoapods 1.0 and executed `pod install` on an iOS project which had a dependency on `A` and had its minimum deployment target set at `7.0`. Then I compiled and ran the project.

## What did you expected to happen?

The project ran without crashing.

## What happened instead?

The project crashed while loading the xib:

```objective-c
[[NSBundle mainBundle] loadNibNamed:@"test" owner:self options:nil]
```

I opened the bundle path in Finder and `test.nib` wasn't there.

It was because the following command fail to compile the xib file while Xcode was running the “Copy Pods Resources” phase.

```bash
ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target 7.0 --output-format human-readable-text --compile test.nib test.xib --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk
```

However the command will succeed if `--minimum-deployment-target` paramaters is not specified, or the minimum deployment target is set to 8.0 or higher.

The `--minimum-deployment-target` parameter was introduced in commmit c9846d3aff40496d0e1dc601903cbb47b9fa1345.

I've attached the xib file so you can give it a try.

[test.xib.zip](https://github.com/CocoaPods/CocoaPods/files/259051/test.xib.zip)

**Comment by neonichu** [comment]
I can reproduce this, quite annoying that `ibtool` doesn't exit with a failure or print errors, but just silently doesn't produce any output.

When dragging the `xib` into Xcode and setting the deployment target to 7.0, it'll use this command:

```
/Applications/Xcode-7.3.1.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module test --output-partial-info-plist /Users/boris/Library/Developer/Xcode/DerivedData/test-emvexelzxuoopicxdjohqkkzsjht/Build/Intermediates/test.build/Debug-iphonesimulator/test.build/test-PartialInfo.plist --auto-activate-custom-fonts --target-device iphone --minimum-deployment-target 7.0 --output-format human-readable-text --compile /Users/boris/Library/Developer/Xcode/DerivedData/test-emvexelzxuoopicxdjohqkkzsjht/Build/Products/Debug-iphonesimulator/test.app/test.nib /Users/boris/Downloads/test.xib
```

The important part seems to be the `--target-device iphone` — without that parameter compilation fails similarly to how it does when using the resources script.

**Comment by neonichu** [comment]
As by #4388, simply not passing the deployment target flag will likely also lead to a runtime crash. I wonder if this fix ever actually worked, though.

**Comment by luosheng** [comment]
Adding the `--target-device iphone` parameter works for me.

The output file name is `test~iphone.nib` if the deployment target is 7.0 or `test.nib` when it's 8.0 or higher, which might be the cause why `ibtool` failed to work if the parameter is not specified.

If the project's deployment device is set to iPad, a `--target-device ipad` parameter will be needed in place. Notably, it the project's deployment device is set to universal, both `--target-device iphone` and `--target-device ipad` are required.

**Comment by Coeur** [comment]
So:
TARGETED_DEVICE_FAMILY 0 → --target-device mac???
TARGETED_DEVICE_FAMILY 1 → --target-device iphone
TARGETED_DEVICE_FAMILY 2 → --target-device ipad
TARGETED_DEVICE_FAMILY 3 → --target-device tv???
TARGETED_DEVICE_FAMILY 4 → --target-device watch

And families can be combined with commas.

**Comment by neonichu** [comment]
I'm guessing this is not an issue with TV, watch and potentially Mac, because it is related to the deployment target specifically.
