### ISSUE TITLE
header search path (v1.0)

### ISSUE THREAD

**Issue by hjanuschka** [CocoaPods/CocoaPods#5283]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expected to happen?

 * imports to work

## What happened instead?

`#import <AFNetworking/AFNetworking.h>` -> not found - and others

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hjanuschka/mypods.git'
source 'git@gitlab.krone.at:mobile/KMMPODS.git'

use_frameworks!


platform :ios, "8.0"

target "fivexfive" do
    pod "kmmsologin"
    pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :branch => 'master'
    #pod 'AcknowledgementsBundle'
    pod 'UIColor-HexString', :git=>'https://github.com/hjanuschka/UIColor-HexString.git'
    pod "CustomKINWebBrowser"
# pod 'Google/Analytics'
    pod 'GoogleAnalytics'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'ISRefreshControl', '~> 1.4.1'
    pod 'OneSignal'
    pod 'UIAlertView+Blocks', '~> 0.8'
    pod 'iRate', '~> 1.11'
    #pod 'PSUpdateApp', '~> 2.0'
    pod 'SDWebImage'
    pod 'UIActivityIndicator-for-SDWebImage'
    pod 'MWPhotoBrowser', :git => 'https://github.com/hjanuschka/MWPhotoBrowser.git', :branch => 'master'
    pod 'NSString-HYPContainsString', :git =>'https://github.com/hyperoslo/NSString-HYPContainsString.git'
    pod 'UITableView-NXEmptyView'
    pod 'Fabric'
    pod 'Crashlytics'
    #pod 'GBDeviceInfo'
    pod 'IQKeyboardManager'
    pod 'DAAppsViewController'
    pod 'EAIntroView'
    #pod 'AdTech-SDK'
    pod 'FXForms'
    pod 'TWSReleaseNotesView'
    #pod 'UIView+UIImageEffects'
    pod 'NSString-UrlEncode', :git => 'https://github.com/kevinrenskers/NSString-URLEncode.git'
    pod "SpinKit"
    pod "MRoundedButton", :git => "https://github.com/rohanaurora/MRoundedButton.git"
    pod 'REFrostedViewController'
    pod 'DCKeyValueObjectMapping'
    pod 'NSObject-ObjectMap'
    pod 'FXBlurView'
    pod 'LGPlaceholderView'
    pod "RMStepsController"

    pod 'UIActionSheet-Blocks'
    pod 'UIImage-ResizeMagick'
    pod 'DateTools'
    pod 'TTTAttributedLabel'
    pod 'FXNotifications'
    pod 'SimulatorRemoteNotifications'
    pod 'M13BadgeView'
    pod 'FLAnimatedImage'
    pod 'JVFloatLabeledTextField'
    pod 'PNChart'
    pod 'HCSStarRatingView'

    pod 'OEWA_Spring'
    pod 'AdTech-SDK'


end

```

**Comment by neonichu** [comment]
Can't reproduce this with a new project. Header search path should also be irrelevant as you are using `use_frameworks!`. Please share a project that reproduces the issue.

**Comment by hjanuschka** [comment]
ok if i remove `remove_frameworks!`  - it works, but thats not an option.
i am not sure how to do a stripped-down sample project.


do you have any other ideas how i can trace this? - the project initialy was a "non `use_frameworks!` once.

**Comment by hjanuschka** [comment]
update! - if i downgrade to the 0.39 - and 


``
rm Pods Podfile.lock fivexfive.xcworkspace
pod install
``

and it builds fine - damn!
any idea how i can provide usefull help? 

@neonichu

**Comment by segiddins** [comment]
@hjanuschka try starting with a new project and adding pods in one at a time until it reproduces the issue? If you can't get it to reproduce, then chances are it might be a configuration issue with your own project.

**Comment by hjanuschka** [comment]
others seem to have the same troubles

https://github.com/CocoaPods/CocoaPods/issues/4950


@segiddins going to try this, if it sorts out to be project specific, how the hell should i find this one out :(

**Comment by hjanuschka** [comment]
ok the following (or one of it, did the trick)

```
fastlane run clear_derived_data
pod cache clean --all
rm -vfr Pods/ Podfile.lock
pod install
```

**Comment by neonichu** [comment]
My bet is on cleaning Derived Data tbh :)

**Comment by hjanuschka** [comment]
yeah mine too - damn xcode!
