### ISSUE TITLE
CocoaPods 1.0.0 breaks unit test compilation

### ISSUE THREAD

**Issue by JanGorman** [CocoaPods/CocoaPods#5285]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

After updating CocoaPods to 1.0.0 and changing the `Podfile` syntax to the new abstract/nested target format, unit test compilation doesn't work anymore, it's unable to resolve types from the main target that it's supposed to test.

## What did you do?

Run `pod install` followed by executing the unit tests.

## What did you expected to happen?

Unit tests run

## What happened instead?

Unit tests cannot resolve any of the classes from the actual app target

## Podfile

```ruby
inhibit_all_warnings!
install! 'cocoapods', :deterministic_uuids => false

abstract_target 'CommonPods' do
  # some private pods

  target 'AppTarget' do
    pod 'CSNotificationView', '~> 0.5'
    ...
    target 'TestTarget' do
      inherit! :search_paths
    end
  end
end
```

**Comment by neonichu** [comment]
Please share a project which reproduces this issue.

**Comment by JanGorman** [comment]
On a fresh project it works as advertised.

It's an older code (and it doesn't check out) – down the rabbit hole then. I'll post back when I find a solution. Put this on hold or close. Thanks

**Comment by JanGorman** [comment]
Update which makes it work for our old project setup:

With CocoaPods > 1.0.0 we didn't actually define a test target in the Podfile at all. We don't use any test specific pods and it just worked. After updating it, I got an error that it couldn't find files in the Bridging-Header (which the test target shares with the app target) which lead me to nest the test target as mentioned in the issue. What I did now is:

```ruby
abstract_target 'CommonPods' do
  pod 'SomePrivatePods'
  
  abstract_target 'ApplicationTargetPods' do
    pod 'JLRoutes', '~> 1.5'
    …
    target 'dailymotion' do
      target 'dailymotionTests' do
      end
    end

    target 'TV' do
      pod '…'
    end
    …
  end
end
```

So two empty targets inside of the abstract target. Everything compiles and works as expected.

**Comment by JanGorman** [comment]
FYI there is a regression with CocoaPods 1.0.1 – the setup I used to fix this stopped working, it's back to square 1.

**Comment by segiddins** [comment]
@JanGorman please open a new issue, including a project

**Comment by break2k** [comment]
any progress here or at least a ticket ?

**Comment by JanGorman** [comment]
@break2k Not yet as I haven't been able to isolate the issue and create a sample project that reproduces the issue. From your question I assume you're experiencing the same? I'll try _now_ and create a new ticket if I'm able to reproduce

**Comment by break2k** [comment]
@JanGorman i depended on the location we integrated the target in the pod file.

We have pods created with different pod versions beginning from 0.32.x -> 0.39.x.

There are pods that have to be defined with:
```
use_frameworks!

target 'PodName_Example' do
  pod "PodName", :path => "../"
end

target 'PodName_Tests' do
  pod "PodName", :path => "../"
end
```

and:
```
use_frameworks!

target 'PodName_Example' do
  pod "PodName", :path => "../"

  target 'PodName_Tests' do
  	pod "PodName", :path => "../"
  end
end
```
