### ISSUE TITLE
"Could not build Objective-C module '...' " in Swift project as of 1.0.0 release and rc's.

### ISSUE THREAD

**Issue by 123kyky** [CocoaPods/CocoaPods#5286]
* [ x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

🌈 

# Report

> Running into issues after pod install on 1.0.0 release on a Swift 2.2. project with an Obj-C pod.
> I started to notice this problem sometime during the 1.0.0 betas/rc's so I had been working in 0.39.0 though the issue persists with the 1.0.0 official release. My project is public and can be found here: https://github.com/123kyky/SteamReader

## What did you do?

> Podfile contains MagicalRecord
> Ran pod install in Swift 2.2 project
> All pods install correctly

## What did you expected to happen?

> To be able to run the app without compiler errors

## What happened instead?

> After pod install, encountering two compiler errors with MagicalRecord
> Errors are:
> Could not build Objective-C module 'MagicalRecord'" on MagicalRecord import
> "Pods/MagicalRecord/MagicalRecord/Categories/DataImport/MagicalImportFunctions.h:10:9: 'MagicalRecord/MagicalRecordXcode7CompatibilityMacros.h' file not found" in MagicalRecord

## Podfile
```ruby
platform :ios, '9.0'
use_frameworks!

target 'SteamReader' do
pod 'Alamofire', '~> 3.3'
pod 'AlamofireImage', '~> 2.4'
pod 'SwiftyJSON', '~> 2.3'
pod 'MagicalRecord', '~> 2.3'
pod 'SnapKit', '~> 0.20'
pod 'AsyncSwift', '~> 1.7'
#pod 'Spring', '~> 1.0'
end
```

**Comment by segiddins** [comment]
I can't reproduce the issue in a clean project with the given Podfile.

**Comment by neonichu** [comment]
Doesn't reproduce with <https://github.com/123kyky/SteamReader>, either. Have you tried deleting DerivedData?

**Comment by danielborges93** [comment]
Hello, I'm getting the same error, but it occurs only building for a device. In simulator, the project runs very well.

This is my Podfile:
```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Project' do
    pod 'SWRevealViewController', '~> 2.3.0'
    pod 'TPKeyboardAvoiding', '~> 1.2'
    pod 'YLProgressBar', '~> 3.8.0'
    pod 'Alamofire', '~> 3.2.0'
    pod 'AlamofireObjectMapper', '~> 2.1.0'
    pod 'MBProgressHUD', '~> 0.9.0'
    pod 'SDWebImage', '~> 3.7.0'
    pod 'MZFormSheetPresentationController', '~> 2.4.0'
    pod 'SFEmptyBackButton', '~> 2.0.0'
    pod 'LGPlusButtonsView', '~> 1.1.0'
    pod 'OAStackView', '~> 1.0.0'
    pod 'RSKGrowingTextView', '~> 1.0.0'
    pod 'ObjectMapper', '1.1.5'
    pod 'NSString-UrlEncode', '~> 2.1.0'
    pod 'Google/Analytics'
    pod 'PureLayout', '~> 3.0.1'
end
```

**Comment by 123kyky** [comment]
Sorry for the trouble! Have not had to clear derived data in quite a while so did not think of that. And it does fix it for me. Thanks for the time
