### ISSUE TITLE
pod no longer runs after update to 1.0.0

### ISSUE THREAD

**Issue by rosskimes** [CocoaPods/CocoaPods#5287]
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I attempted to update to CocoaPods 1.0.0 by running `sudo gem update cocoapods`.

## What did you expected to happen?

I expected CocoaPods 1.0.0 to be updated and ready to use.

## What happened instead?

Anytime I use the `pod` command, I am getting this error.
```
Ross-MacBook-Pro:~ rosskimes$ pod --version
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/sources_manager.rb:159:in `<module:SourcesManagerMissingConstant>': uninitialized constant Pod::SourcesManagerMissingConstant::Set (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/sources_manager.rb:158:in `<module:Pod>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/sources_manager.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods.rb:71:in `<module:Pod>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods.rb:17:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:36:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

```

## Things I Tried

- I removed code from .bash_profile to set a custom GEM_HOM.
```bash
$ export GEM_HOME=/Users/rosskimes/Development/Ruby
$ export PATH=$GEM_HOME/bin:$PATH
```

- I uninstalled all versions of CocoaPods and did a fresh install using `sudo gem install cocoapods -n /usr/local/bin`. (I have to specify the install directory due to a Ruby error [as mentioned here](https://github.com/CocoaPods/CocoaPods/issues/3692#issuecomment-113847612)).

--
Note that a clean install of 0.39 using `sudo gem install cocoapods -n /usr/local/bin -v 0.39` *does* work, but breaks again as soon as I update.

I am running OS X 10.11.4.

Any ideas?

**Comment by kmav** [comment]
I am experiencing the same issue. 

I use the same OS X 10.11.4.

In order to work I uninstalled the latest version of cocoapods 1.0.0.

I used the following command to do a clean install of v0.39:
`sudo gem install cocoapods -v0.39`

The `-n /usr/local/bin` option did not work in my case.

Thank you for opening this issue.

**Comment by segiddins** [comment]
@kmav there's an open PR fixing the issue

**Comment by kmav** [comment]
Dear Samuel,

I have hard coded your suggestion (require set) in the related file in my configuration. Yes. This resolves this issue. But, after running pod install it results in a misconfiguration of my project. So, I rolled back to old version. I can provide further details for my setup late today.

Regards,

Konstantinos Mavroudakis

12 Μαΐ 2016, 5:23 πμ, ο/η Samuel Giddins <notifications@github.com> έγραψε:

**Comment by segiddins** [comment]
@kmav please open a new issue for that

**Comment by offbye** [comment]
I also meet this issue.
被坑了

**Comment by grosch** [comment]
Why is this issue closed?  This still happens with a gem install of cocoapods done today

**Comment by orta** [comment]
Because the PR has been merged into master, it will be fixed in the next release,

**Comment by grosch** [comment]
And when will that be?  Now I'm broken :(

**Comment by kajensen** [comment]
@grosch Its one line, just temporarily fix it manually.

**Comment by Natelegreat1** [comment]
@kajensen What is the one line fix? How do we do it?...

**Comment by kajensen** [comment]
@Natelegreat1 https://github.com/CocoaPods/CocoaPods/pull/5288/files

**Comment by coryhymel** [comment]
@kajensen how are you suppose to go about editing this file?

**Comment by orta** [comment]
CocoaPods 1.0.1 came out a few hours ago, I think this is in that.
