### ISSUE TITLE
[1.0] inhibit_all_warnings! doesn't silence warnings from pods

### ISSUE THREAD

**Issue by adomanico** [CocoaPods/CocoaPods#5290]
* [*] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

-Inserted inhibit_all_warnings! into our podfile
-ran pod install

## What did you expected to happen?

Expected to not see warnings from our pods when compiling project

## What happened instead?

Files from our pods are showing warnings in the project

- Masonry, Braintree and Branch all show their warnings

## Podfile

```ruby
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

# Please keep pods in alphabetical order!
# Full pod update after every appstore submission.

target "Gametime" do
    pod 'AFNetworking'
    pod 'APParallaxHeader', git: 'git@github.com:gametimesf/APParallaxHeader.git'
    pod 'Apptimize'
    pod 'Braintree'
    pod 'Braintree/Apple-Pay'
    pod 'Braintree/Venmo'
    pod 'Braintree/DataCollector'
    pod 'Branch'
    pod 'CardIO'
    pod 'Crashlytics'
    pod 'CSStickyHeaderFlowLayout'
    pod 'EasyTipView'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'Fabric'
    pod 'libPusher'
    pod 'Localytics'
    pod 'Masonry'
    pod 'Mixpanel'
    pod 'Nuke'
    pod 'Realm'
    pod 'ZXingObjC'
end

```

**Comment by neonichu** [comment]
Please share a project that reproduces this project and tell us more concretely which warnings you are seeing. I see none when using your Podfile in a fresh project with Xcode 7.3.1 tbh.

**Comment by adomanico** [comment]
Seems to only occur if use_frameworks! and inhibit_all_warnings! are both specified in the pod file. 

We are moving to static frameworks due to an Apple bug anyways I guess we have a workaround

**Comment by gmarm** [comment]
I'm having the same issue. Yes, I am using both `use_frameworks!` and `inhibit_all_warnings!`.

All the warnings I'm getting are `No newline at end of file`. Could be a coincidence though.

Is there anything that fixes this at the moment?

**Comment by pRizz** [comment]
@gmarm, here is what I put in my Podfile to inhibit swift warnings. I want to add it to CocoaPods, but cannot figure out where to add it. @neonichu can you help? I've tried looking in CocoaPods core, but it is still not obvious.

Here is a [gist](https://gist.github.com/pRizz/df6da844959ca1e814a55403e50bcf9c) of my work:

```ruby
class Warnings
  def self.inhibit_in_workspace(options)
    require 'xcodeproj'
    workspace = Xcodeproj::Workspace.new_from_xcworkspace(options[:workspace_path])
    project_file_references = workspace.file_references
    project_file_references.each do |project_file_reference|
      inhibit_in_project(Xcodeproj::Project.open("../#{project_file_reference.path}")) # FIXME, don't use ../
    end
  end

  def self.inhibit_in_project(project)
    require 'xcodeproj'
    project.build_configurations.each do |build_configuration|
      project.targets.each do |target|
        if target.build_settings(build_configuration.name)["OTHER_SWIFT_FLAGS"].nil?
          target.build_settings(build_configuration.name)["OTHER_SWIFT_FLAGS"] = "-suppress-warnings"
        else
          target.build_settings(build_configuration.name)["OTHER_SWIFT_FLAGS"] += " -suppress-warnings"
        end
      end
    end
    project.save
  end
end

post_install do |installer|
  Warnings.inhibit_in_project(installer.pods_project)
end
```

You may have to monkey around with the paths in this script.

**Comment by segiddins** [comment]
@pRizz objc inhibiting is done in https://github.com/CocoaPods/CocoaPods/blob/5ae5ef8d340366a81da2ebdb61666c7c63068b41/lib/cocoapods/installer/target_installer/pod_target_installer.rb#L312, so probably adding that somewhere in the pod target installer?

**Comment by pRizz** [comment]
Thanks for that @segiddins ! I will try merging it in and test that out.
