### ISSUE TITLE
Issues with compiling C-only source in 1.0.0

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#5291]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

YapDatabase+SQLCipher doesn't compile using CocoaPods 1.0.0. If you upgrade to CocoaPods 1.0.0 and try to compile a simple project using YapDatabase+SQLCipher, you get weird errors compiling yap_vfs_shm.c.

It's because the SQLCipher umbrella header includes UIKit.h, and then is included in a C-only file in another Pod. It should conditionally include UIKit based on language.

More information is here:

https://github.com/yapstudios/YapDatabase/issues/322#issuecomment-218535586

**Comment by segiddins** [comment]
👍 a PR with the `#ifdef __OBJC__` would be great

**Comment by chrisballinger** [comment]
This should probably fix the issue, but I haven't tested it yet because I'm not exactly sure how to run it locally.

https://github.com/chrisballinger/CocoaPods/commit/3031fc3a22960c4635ce3ad40eb6226cd2cd760a

**Comment by segiddins** [comment]
@chrisballinger just make a PR for it, we don't have great tests around the actual `xcodebuild` part of linting, unfortunately

**Comment by chrisballinger** [comment]
Well, I'm not sure how to see if this fix actually works for our problem.. although I'm pretty sure it does. I'll see if I can figure it out.

**Comment by chrisballinger** [comment]
This is still broken in rc3... in a new way. :(

```objc
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#endif

#import "sqlite3.h"

FOUNDATION_EXPORT double SQLCipherVersionNumber;
FOUNDATION_EXPORT const unsigned char SQLCipherVersionString[];
```

`FOUNDATION_EXPORT` isn't defined unless you `#import <Foundation/Foundation.h>`, but if you import that, you're back where you started by including Obj-C in a C-only build target. I'll try to figure out another workaround.

**Comment by chrisballinger** [comment]
`FOUNDATION_EXPORT` is defined in `<Foundation/NSObjCRuntime.h>`, as an alias to `FOUNDATION_EXTERN`, which does this:

```objc
#if defined(__cplusplus)
#define FOUNDATION_EXTERN extern "C"
#else
#define FOUNDATION_EXTERN extern
#endif
```

We could do something similar in the umbrella header:

```obj-c
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
```

**Comment by chrisballinger** [comment]
Specifically the failure happens when SQLCipher `"sqlcipher/sqlite3.h"` is included in `sqlfs.c`:

https://github.com/guardianproject/libsqlfs/blob/master/sqlfs.c#L54
