### ISSUE TITLE
Missing XCTest in framework search path for inherited dependencies

### ISSUE THREAD

**Issue by fcy** [CocoaPods/CocoaPods#5293]
🌈
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

This [seems to be a variation](https://github.com/CocoaPods/CocoaPods/issues/5264#issuecomment-218593290) of #5264. The difference is that the missing dependency is XCTest instead of other pods. I've made small changes to the sample code to reproduce the problem, you can find the new [sample here](http://felipecypriano.com/files/missing-xctest.zip).

The main difference is that `sharedlib/Testing` is now a separate pod instead of a subspec. And I added an `#import` to make sure `sharedlibtesting` tries to compile `testkit` code (which is the one that depends on XCTest).

Move it to a separate pod because [@segiddins mentioned](https://github.com/CocoaPods/CocoaPods/issues/5264#issuecomment-217546461) that inheriting a subspec might not be possible. But I don't believe this change is related to the problem, I did it so the sample project matches my actual project.
## What did you do?
1. Download the sample code
2. Select the App scheme
3. CMD+SHIFT+U (Build for Testing)
## What did you expected to happen?

The build to work.
## What happened instead?

Fails to compile because it doesn't find `XCTest/XCTest.h`. The problem is that sharedlibtesting doesn't inherit the framework search path for XCTest from `testkit`.
## Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'App' do

  pod 'logger', path: '../logger'
  pod 'sharedlib', path: '../sharedlib'
  pod 'asserts', path: '../asserts'

  target 'Test' do
    inherit! :search_paths

    pod 'testkit', path: '../testkit'
    pod 'sharedlibtesting', path: '../sharedlib'
  end
end
```
### testkit

```
Pod::Spec.new do |s|
  s.name         = "testkit"
  s.source       = { path: '.' }

  s.source_files  = "Classes/**/*.{h,m}"

  s.framework = 'XCTest'

  s.dependency 'asserts'
end
```
### sharedlibtesting

```
Pod::Spec.new do |s|
  s.name         = "sharedlibtesting"
  s.source       = { path: '.' }

  s.source_files  = "Classes/Testing/*.{h,m}"
  s.dependency 'sharedlib'
  s.dependency 'testkit'
end
```

**Comment by fcy** [comment]
any ideas for a workaround while this isn't fixed?

**Comment by neonichu** [comment]
so `sharedlibtesting` uses XCTest? Then it should have `s.framework = 'XCTest'`, every Pod needs to be self-contained in terms of dependencies when building with frameworks integration.

**Comment by fcy** [comment]
No. The file that is failing to compile is from testkit not sharedlibtesting.

**Comment by neonichu** [comment]
Ah, I missed the example project at first. So `testkit` leaks its dependency on `XCTest` via the headers, you can still fix it by adding `s.framework = 'XCTest'` to `sharedlibtesting`. 

Generally, I don't think it would be correct for a Pod to inherit transitive framework dependencies. It might make sense in some cases, but more often than not, such a dependency would not be exposed via the headers and therefore unnecessary to be inherited.

**Comment by fcy** [comment]
Hummm 🤔. To me it feels weird to require the client of a pod to declare the pod's own dependencies in order to work.

> Generally, I don't think it would be correct for a Pod to inherit transitive framework dependencies.

I think I didn't understand the difference between transitive framework dependencies vs other transitive dependencies. Could you elaborate?

**Comment by neonichu** [comment]
If `sharedlibtesting` depends on `testkit` and `testkit` in turn depends on `XCTest`, then `XCTest` is a transitive dependency of `sharedlibtesting` vs. `testkit` which is a direct one.

Generally, a Pod wouldn't expose all of its dependencies via its public headers. For example, if you're writing an API client and you use a networking library or a library for parsing dates, your clients wouldn't need to know about that. I think the same applies here, albeit `XCTest` might be a bit of a special case.

**Comment by fcy** [comment]
That makes sense. I actually like that concept makes dependencies easy to manage.

Since Swift doesn't have headers wouldn't figuring out what dependencies are "propagate-able" harder? In Objective-C seems like anything a header imports "should" be a dependency of the client but in Swift an import could be used by a private or internal class. 🤔

And now I'm wondering, was it ever discussed having a explicit way to declare dependencies that should be transitive in a `podspec`?

**Comment by neonichu** [comment]
Don't think it was ever discussed, because in static library times, this distinction wasn't really interesting as all Pods were lumped into one aggregate library. 

The advantage of Swift is that this accidental leakage of transitive dependencies won't really happen, because there are no headers. If a transitive dependency is exposed, e.g. by reusing some types in the public interface, it will be more obvious that it is required, because your own Pod would directly deal with those types.

**Comment by segiddins** [comment]
@neonichu how does Xcode handle this by default, if you manually create frameworks?

**Comment by neonichu** [comment]
It works exactly the same way in Xcode, you would have to manually specify for each framework that it links against `XCTest`.

**Comment by fcy** [comment]
Xcode doesn't handle any kind dependencies right? Everything is manually setup.

What still feels wrong to me is treating `s.framework` totally different than a regular `s.dependency`. In one the user is responsible to setup the transitive dependencies the other CocoaPods does it for you. I really like the idea of having two kinds of dependencies but currently we don't have that notion and because of that I don't think a `s.framework` should be treated differently than `s.dependency`, no user would expect that and the tool feels broken.

**Comment by neonichu** [comment]
It should work the same for both cases, though, AFAIK.

**Comment by fcy** [comment]
I'm confused now. Isn't this issue showing that it is not behaving the same for `s.framework`?

**Comment by neonichu** [comment]
I don't think so, if a Pod depends on another Pod which in turns depends on AFNetworking and puts an `#import <AFNetworking/AFNetworking.h>` in one of its public headers, the same kind of problem should arise.

**Comment by fcy** [comment]
I don't think it does, specially after the fix for #5264. If I understood what you are saying correctly, #5266 shouldn't have been merged and pod developers that depend on others pods should implicitly know how to manage the other pods dependencies.

At this point my understanding is that CocoaPods works as expected as a dependency manager with static libraries (dependencies build without any manual intervention) but when using `use_frameworks!` it  breaks the build and don't even explain what is wrong.

Your example sounds to me like this "CocoaPods can manage the dependencies on one level, if you add another one than you're own your own". I can't stop feeling that something is wrong with this approach.

**Comment by fcy** [comment]
I'll try to summarize my point of view in this issue better.

1. Given the same set of dependencies (no vendored binary ones) in a Podfile it should work the same with and without `use_frameworks!`. Meaning CocoaPods should resolve all the dependencies to make everything build.
2. If we want to use Dynamic Frameworks ability to better control what dependencies are propagate and which aren't we should add extra settings for this special case. Something like `s.dependency 'ABC', private: true` this new setting wouldn't do anything when using static libraries but would better organize the dependencies of dependencies when using Dynamic Frameworks

**Comment by neonichu** [comment]
To me, it feels wrong to assume that all of a Pod's dependencies are automatically made public to its clients. That has huge implications on the interface a single Pod exports.

You bring up a good point with #5264, though, I have to look at that a bit closer.

**Comment by fcy** [comment]
> it feels wrong to assume that all of a Pod's dependencies are automatically made public to its clients

I agree in principle. My point is not about that by itself since CocoaPods is not being created today, it is about the huge difference in behavior that a single keyword is causing.
