### ISSUE TITLE
Pod directory is empty after `pod install` succeeds

### ISSUE THREAD

**Issue by marcboquet** [CocoaPods/CocoaPods#5294]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

> Run `pod install` with ruby 2.2.3 on a directory with unicode characters.

## What happened?

> Installation says it succeeded, but individual pod directories are empty, there are no sources or other files.

## How to reproduce

> Any project with a unicode path should cause this issue, and I think it only happens on ruby 2.2.3.
> CocoaPods.app 1.0.0 seems to be bundling ruby 2.2.3 and this is how I ran into the issue.
> Here's an Xcode project that should fail when installing with the app: [Bügling.zip](https://github.com/CocoaPods/CocoaPods/files/260353/Bugling.zip)

## Investigation

> It looks like it might be a bug with `Pathname` and unicode characters in the path, where the characters are sometimes represented by different byte lengths.
> This causes `PathList#read_file_system` to miscalculate the root path size and remove an extra character from the path when converting from absolute to relative.
> At the end, this seems to cause `PodDirCleaner#used_files` to be empty, so the cleaning process removes all the files in the directory.

Not sure about any of this, and it's a bit difficult to test. But I think I might have a solution, I'll send a PR if I manage to fix it.

**Comment by neonichu** [comment]
Can repro with CP.app and the example project (:ok_hand: on the naming). PR highly welcome, of course 👍

**Comment by segiddins** [comment]
Can you share what an example Unicode path name is that triggers the issue? Thanks!

**Comment by marcboquet** [comment]
I saw it happening with paths containing accents or similar. You should be able to check with `irb`.
If I switch to `/Users/marc/ü` and run `Pathname.pwd.to_s.chars` the output in ruby 2.2.3 or older shows `["u", "̈"]` for the `ü` char, and in ruby 2.3.1 it shows `["ü"]`

**Comment by segiddins** [comment]
Thanks!
