### ISSUE TITLE
When creating library with 0.39 - we get a "podfile" invalid syntax 

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#5295]
With 0.39 - Due to updates to the syntax, the create library function now throws an error due to downloading the new 1.0 template.

Perhaps for 1.1 and beyond we should download the correct version of the template / prompt them to update.

**Comment by neonichu** [comment]
I think @orta was looking into this.

**Comment by orta** [comment]
I fixed this in:

* Obj-C - https://github.com/CocoaPods/pod-template/blob/master/templates/ios/Example/Podfile#L2
* Swift - https://github.com/CocoaPods/pod-template/blob/master/templates/swift/Example/Podfile#L3

@jcampbell05 can you make an issue on pod-template (it always pulls from master) with the choices you made ( e.g. swift, quick, etc ) please 👍

**Comment by orta** [comment]
Oh, yeah, sorry, realised you wanted 0.39 compatibility, this issue is about that - https://github.com/CocoaPods/pod-template/issues/170
