### ISSUE TITLE
Question: Can I have two Pods projects with different dependencies and settings

### ISSUE THREAD

**Issue by mrdekk** [CocoaPods/CocoaPods#5298]
Related to transitive binary dependencies.

Can I have this scenario - two Pods projects for the same my project one of them use use_frameworks! with Swift dependencies and other doesn't use use_frameworks! and with static binary dependencies.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
