### ISSUE TITLE
Header issue with FBSnapshotTestCase pod

### ISSUE THREAD

**Issue by crazyjooe** [CocoaPods/CocoaPods#5300]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

After migrating to 1.0.0 CocoaPods version, FBSnapshotTestCase isn't compiling with "Use of private header outside its module error".

## What did you do?

`pod _1.0.0_ try FBSnapshotTestCase`, Product->Test
`pod _0.39.0_ try FBSnapshotTestCase`, Product->Test

## What did you expected to happen?

Project compiles in both cases.

## What happened instead?

Only 0.39.0 works as expected.

## CocoaPods Environment

Not applicable

## Project that demonstrates the issue

Using `try` is enough to reproduce.

**Comment by orta** [comment]
This is an issue you should bring up with FBSnapshotTestCase, I think master is currently fixed.
