### ISSUE TITLE
Inherit :search_paths does not include some pods in the test target (I think it is because they are binaries, not sure)

### ISSUE THREAD

**Issue by fcy** [CocoaPods/CocoaPods#5303]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Some pods are not being inherited by the test target. It is happening in my projects with these ones: Fabric, Crashlytics, and GoogleMaps. I believe it is because they are all binary dependencies.

My test target needs to inherit the search path for these pods as well in order to be able to use a mock to set expectations on the usage of their classes by the app.

## What did you do?

1. Create a new project
2. Run `pod init`
3. Add `use_frameworks!`
4. Add `pod 'Crashlytics` to the app target
5. Run `pod install`
6. Add `@import Crashlytics` to a test target class

## What did you expected to happen?

Build to work and when running no messages of duplicate classes.

## What happened instead?

The build fails because the test target doesn't have `"${PODS_ROOT}/Headers/Public/Crashlytics"` in its framework search path.

*Tried workaround:* Adding the pod directly to the test target makes the build succeeds but when running the tests there are runtime messages of duplicate implementation:

> Class CLSInternalReport is implemented in both...

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 473a82317872477804a6a8159f07ba09fed8f7df
               thumbtack - ssh://git@github.com/thumbtack/PodSpecs.git @ 5235a22ee4f46dd828d071714f66c4799b779a02
               thumbtack-1 - /Users/felipe/.cocoapods/repos/thumbtack @ 5684d57c262098967789671f3f6b5a38e07c67dd
```

### Installation Source

```
Executable Path: /Users/felipe/.gem/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'MissingPod' do
  pod 'Crashlytics'

  target 'MissingPodTests' do
    inherit! :search_paths

    # pod 'Crashlytics'  # causes Class CLSInternalReport is implemented in both
  end
end
```

## Project that demonstrates the issue

http://felipecypriano.com/files/MissingPod.zip

**Comment by neonichu** [comment]
This is part of a larger issue with vendored static frameworks and search path inheritance, see  #5173

**Comment by coolnalu** [comment]
@neonichu reason that it's closed and is this an issue you guys are actively working on? Looked at #5146 but we are still experiencing the problem.

**Comment by segiddins** [comment]
@coolnalu it's closed as a duplicate of the issue that boris linked to
