### ISSUE TITLE
always clone master spec repo if there is not `source` in Podfile.

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#5306]
I'm in China, and the github server is very slow. So I have a mirror server to clone the master spec repo.

But I don't want to use the git server, so I use other protocol server, eg: rsync, oss .

I write a plugin to hook the source provider:

```
plugin 'cocoapods-repo-rsync', :sources => ['my.mirror.com']
```

There is not any `source` in the Podfile.

But I found the master repo still clone to my computer. I check the code:

CP 0.39.0: 

install.rb

```
    def resolve_dependencies
      analyzer = create_analyzer

      plugin_sources = run_source_provider_hooks
      analyzer.sources.insert(0, *plugin_sources)

      ....
   end
```

analyzer.rb

```
      def sources
        @sources ||= begin
          sources = podfile.sources
          if sources.empty?
            url = 'https://github.com/CocoaPods/Specs.git'
            [SourcesManager.find_or_create_source_with_url(url)]
          else
            sources.map do |source_url|
              SourcesManager.find_or_create_source_with_url(source_url)
            end
          end
        end
      end
```

The sources always are not empty!! If podfile.sources is empty, CP will clone the master repo !!!

I check the CP 1.0.0.The behavior is similar.

**Comment by segiddins** [comment]
This behavior is, I believe, intentional.

**Comment by Whirlwind** [comment]
I think that add master repo to sources in the `resolve_dependencies` is better:

```
    def resolve_dependencies
      analyzer = create_analyzer

      plugin_sources = run_source_provider_hooks
      analyzer.sources.insert(0, *plugin_sources)

      # if podfile.sources and source_provider are both empty, we add the master source.
      if analyzer.sources.empty?
            url = 'https://github.com/CocoaPods/Specs.git'
            analyzer.sources.append(SourcesManager.find_or_create_source_with_url(url))
      end

      .....
```

**Comment by segiddins** [comment]
Ah, in that case a tested PR would be 🚀 !

**Comment by orta** [comment]
👍

**Comment by wjbuys** [comment]
FYI, at least one plugin has already [monkey-patched around this limitation](https://github.com/JFrogDev/cocoapods-art/blob/master/lib/cocoapods_plugin.rb#L76-L101).

Would it make sense to move the `run_source_provider_hooks` method into the `Analyzer`'s construction? Or to at least provide its results to the `Analyzer` initializer, rather than setting sources after the fact.
