### ISSUE TITLE
Trouble building target in debug configuration after update to 1.0

### ISSUE THREAD

**Issue by DarkInsight85** [CocoaPods/CocoaPods#5307]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
After update CocoaPods to 1.0, project can no longer be build in debug configuration. Other configurations still works; in fact, I have even archived and submitted to app store.

## What did you do?

Update CocoaPods: sudo gem install cocoapods

- Updated pods: pod update
- Archived project, works fine
- Removed 'Embed Pod Frameworks' from my WatchKit extension and Today extension targets, following instruction from [here](https://github.com/CocoaPods/CocoaPods/issues/4203)
- Submitted to app store, works fine
- Next day, tried to debug the project, ran into error: "'Mantle/MTLJSONAdapter.h' file not found" for my WatchKit extension and Today extension targets
- Tried to 'pod update', 'pod install', both doesn't work
- Tried 'pod deintegrate' followed by 'pod install', still doesn't work
- Checked from TestFlight the build I have uploaded to iTunesConnect the previous day, the build works fine, I just couldn't debug the same project on Xcode

## What did you expected to happen?
- Able to debug my project

## What happened instead?
- Ran into error: "'Mantle/MTLJSONAdapter.h' file not found" for my WatchKit extension and Today extension targets

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ace7f23e78aa54d26f3637319f9814bc52c2a570
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, "8.0"
use_frameworks!
inhibit_all_warnings!

target "CallLevels" do
	pod 'AFNetworking', '~> 3.0'
    pod 'Crashlytics'
    pod 'EGOCache', '~> 2.1'
    pod 'Fabric'
    pod 'Lockbox', '~> 2.1'
    pod 'Mantle', '~> 2.0'
    pod 'AppsFlyer-SDK'
    pod 'Branch'
    pod 'Charts'
    pod 'DGElasticPullToRefresh', '~> 1.0'
    pod 'FBSDKCoreKit',  '~>4.8'
    pod 'FBSDKLoginKit', '~>4.8'
    pod 'FBSDKShareKit', '~>4.8'
    pod 'Google/Analytics'
    pod 'GoogleIDFASupport'
    pod 'HTMLReader', '~> 0.9'
    pod 'iRate', '~> 1.11'
    pod 'M13Checkbox'
    pod 'Mixpanel'
    pod 'Parse', '~> 1.11'
    pod 'pop', '~> 1.0'
    pod 'SVProgressHUD', '~> 1.1.3'
    pod 'SVPullToRefresh', '~> 0.4'
    pod 'SWTableViewCell', '~> 0.3'
    pod 'TPKeyboardAvoiding', '~> 1.2'
    pod 'ViewUtils', '~> 1.1'
end

target "CallLevelsTests" do

end

target "CallLevels WatchKit Extension" do
    pod 'AFNetworking', '~> 3.0'
    pod 'Crashlytics'
    pod 'EGOCache', '~> 2.1'
    pod 'Fabric'
    pod 'Lockbox', '~> 2.1'
    pod 'Mantle', '~> 2.0'
end

target "CallLevels Widget" do
    pod 'AFNetworking', '~> 3.0'
    pod 'Crashlytics'
    pod 'EGOCache', '~> 2.1'
    pod 'Fabric'
    pod 'Lockbox', '~> 2.1'
    pod 'Mantle', '~> 2.0'
end
```

**Comment by segiddins** [comment]
@benasher44 want to tack this onto the list of extension issues?

**Comment by Coeur** [comment]
@DarkInsight85, you could try this syntax:

    #import <MTLJSONAdapter.h>

**Comment by orta** [comment]
( also worth seeing if `@import Framework;` fixes it too )

**Comment by dstranz** [comment]
I have similar problem probably - I'm not able to build project with Debug configuration after adding new file. It ends up with 
```
ld: symbol(s) not found for architecture x86_64
  "_OBJC_CLASS_$_AdLoader", referenced from:
***
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
When I change configuration to Release, it builds and run without problem.

Changing import to 
`#import <AdLoader.h>`
doesn't help.

**Comment by segiddins** [comment]
@dstranz please share a project that reproduces the issue. Thanks!

**Comment by dstranz** [comment]
@segiddins I will try to reproduce it on example project.

**Comment by benasher44** [comment]
@segiddins I'm not sure that the fix for the issue I'm working on is going to have any affect on header search paths, but I'll be sure to ping on this issue as well when I have a working branch ready, just in case

**Comment by Coeur** [comment]
@dstranz, in case you have trouble to reproduce the issue on a different project, try to delete the `~/Library/Developer/Xcode/DerivedData` folder.

**Comment by proskd** [comment]
@DarkInsight85 i'm also seeing the same issue with Mantle.  What's weird is I created a brand new sample project and used basically the exact podfile we're currently using in our main project and it builds just fine, which makes no sense to me at all.  I've compared the build settings between our main project and the sample and don't see any meaningful difference.  I also tried deleting the DerivedData folder but to no avail.  

Would be really curious to know if anyone actually figures out what the underlying issue here really is.

**Comment by Coeur** [comment]
Maybe you didn't close Xcode while deleting the DerivedData, or you didn't empty the trash before reopening Xcode. Either way, good news it got fixed for you, @proskd. I had the same kind of issues a few months ago with the beta releases, so I'm happy to help people moving to the stable release.

**Comment by proskd** [comment]
@Coeur yeah it's certainly possible that's what happened.

**Comment by dstranz** [comment]
@Coeur `rm -rf ~/Library/Developer/Xcode/DerivedData` helped! Thank you!

**Comment by DarkInsight85** [comment]
Thanks! Can confirm remove DerivedData works!

**Comment by DarkInsight85** [comment]
Should I close this issue?

**Comment by Coeur** [comment]
@DarkInsight85, yes please.
