### ISSUE TITLE
Automated cocapods installation and version selection

### ISSUE THREAD

**Issue by vorobievalex** [CocoaPods/CocoaPods#5308]
Different versions of cocoapods often incompatible with complex Podfiles of other versions. This makes teams use single old version of cocapods for all apps and update version very rarely.
It would be great if 'pod install' could download the version defined in Podfile.lock of current project (when needed) and run it.

So cocoapods versions for every app can be updated separately, developers and CI servers can work with all these apps simultaneously.

-- As a possible option reference: there is an Android plugin that does the same for Android SDK: https://github.com/JakeWharton/sdk-manager-plugin

**Comment by orta** [comment]
This is what [gemfiles](https://guides.cocoapods.org/using/a-gemfile.html) and bundler are for, there's no need for CocoaPods to try and replicate this functionality.
