### ISSUE TITLE
can't add --allow-warnings at the end of `pod repo push`

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#5309]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod repo push my-coeur-repo Coeur.podspec --allow-warnings`

## What did you expected to happen?

Pushing spec to private repo.

## What happened instead?

``[!] Unknown command: `—-allow-warnings```

## Workaround

inserting the command at the beginning works:

`pod --allow-warnings repo push my-coeur-repo Coeur.podspec`

## CocoaPods Environment

CocoaPods 1.0.0

**Comment by segiddins** [comment]
The flags have to go after the command, so `pod repo push --allow-warnings`

**Comment by Coeur** [comment]
fair enough :)
