### ISSUE TITLE
No estimated time of sharding the CocoaSpecs repo

### ISSUE THREAD

**Issue by WiesnerPeti** [CocoaPods/CocoaPods#5312]
> Hi guys,
>
> according to the [Master spec-repo rate limiting post‑mortem|http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/] blog post, the CocoaSpecs repo will be sharded. However there is no mention of estimated time for this change (only that it will be shortly after the 1.0.0 release). Can you give us please some update on this topic?
>
> I opened this issue to have a thread, where we could talk about this Please suggest better platform and close this issue, if you find this inappropriate  :)
>
>Thank you very much!
>
> p.s: Sorry for not following the issue template, but as you can see, this did not fit in

@orta @alloy

**Comment by alloy** [comment]
Is your concern due to being ‘stuck’ on an older CP version?

**Comment by WiesnerPeti** [comment]
Yes, we still use _0.39_ and we would like to schedule the update to 1.0, want to know how much time do we have :)

**Comment by alloy** [comment]
Gotcha. I’ll leave giving any estimates to @segiddins, but iirc it was in the order of months, specifically because of this issue.

**Comment by segiddins** [comment]
You have at least one and a half months and no more than about three. The exact timing of the sharding will depend on my schedule, but rest assured that you'll always just be able to check out the pre-shard tag that we'll make and use that if for whatever reason you haven't updated to 1.0 by then.

**Comment by tamaskarai** [comment]
@segiddins Thanks for the info.

**Comment by WiesnerPeti** [comment]
Thank you @alloy and @segiddins for the quick answers! I will close the issue now, cheers!
