### ISSUE TITLE
Unable to import OS X frameworks using private headers and header_mappings_dir

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#5313]
## What did you do?

Integrated Realm in an OS X target.

## What did you expected to happen?

The integrating target would build.

## What happened instead?

The generated pod target for Realm itself builds, but it can't be imported. Clang complains about missing headers from the module map:

```
Realm.framework/Modules/module.modulemap:8:16: error: header 'RLMAccessor.h' not found
        header "RLMAccessor.h"
               ^

DataImporter.swift:20:8: error: could not build Objective-C module 'Realm'
import Realm
       ^
```

Inspecting the build products and comparing them with the binaries we build ourselves from our Xcode project, it turns out, that the `PrivateHeaders` symlink in the root directory of the framework bundle is missing. While the actual `PrivateHeaders` dir exists within `Versions/A`. My suspicion is that the custom copy files build phase, which ensures to retain the header layout of the `header_mappings_dir` creates the `PrivateHeaders` directory in a way Xcode doesn't expect, preventing the automatic creation of the symlink.

So this seems to be an instance of a more general error, which is only relevant for podspecs using `header_mappings_dir`, a custom module map and private headers, which are explicitly declared in the module map.

## CocoaPods Environment

```
   CocoaPods : 1.0.0
       Xcode : 7.3 (7D175)
```

## Project that demonstrates the issue

https://github.com/realm/realm-cocoa-converter/tree/to-0.102.0-update

**Comment by segiddins** [comment]
If I understand, this is only an issue for OS X?

**Comment by mrackwitz** [comment]
Yes, because it fails just because of the missing symlink, which is only present in the framework structure used by OS X.

**Comment by segiddins** [comment]
Joy 😭

**Comment by mrackwitz** [comment]
I see two ways how we could solve that:
1. create a private dummy header, which uses Xcode's builtin copy header files build phase
2. create the symlink ourselves by a shell script build phase

Adding a dummy header like in 1. outside of the `header_mappings_dir`, which would be added to the builtin copy header files build phase isn't allowed, because header files have to be children of the `header_mappings_dir`.

But it is possible to partially work around that from the podspec as seen below, but this doesn't follow the exact structure and could theoretically break AppStore-compatibility if not already now then possibly in the future.
```ruby
s.osx.pod_target_xcconfig = {
  'PUBLIC_HEADERS_FOLDER_PATH' => '$(WRAPPER_NAME)/Headers',
  'PRIVATE_HEADERS_FOLDER_PATH' => '$(WRAPPER_NAME)/PrivateHeaders'
}
```

Note that the `PUBLIC_HEADERS_FOLDER_PATH` has to be overridden here as well. That's because once the `PRIVATE_HEADERS_FOLDER_PATH` is overridden, the symlink for the public headers is also not correctly created anymore. ![http://i.giphy.com/S0fkVjadqdLDW.gif](That doesn't make any sense to me.)

**Comment by segiddins** [comment]
I guess let's look into a build phase to make the symlinks?
