### ISSUE TITLE
The `exclude_files` file pattern is not respecting `resources` paths

### ISSUE THREAD

**Issue by cnoon** [CocoaPods/CocoaPods#5317]
# Report
## What did you do?

I tried to exclude an `lproj` directory from my `resources` using `exclude_files`.

``` ruby
Pod::Spec.new do |s|
  s.name = 'Library'
  s.version = '2.1.2'
  s.license = 'license'
  s.summary = 'summary'
  s.homepage = 'homepage'
  s.authors = 'Various'

  s.source = { :git => 'ssh://git@project_path/library.git', :tag => s.version }

  s.source_files = [
    'Library/Core/**/*.{h,m,swift}',
    'Library/Library.h'
  ]

  s.resources = [
    'Library/Resources/Images/*.png',
    'Library/Resources/Localization/*.lproj'
  ]

  s.exclude_files = [
    'Library/Resources/Localization/pseudo.lproj',
    'Library/Resources/Localization/pseudo.lproj/Global.strings'
  ]

  s.module_map = 'Library/Library.modulemap'

  s.ios.deployment_target = '9.0'
end
```
## What did you expected to happen?

I expected `pseudo.lproj` to remove be excluded from the project when using `pod lib lint --no-clean`.
## What happened instead?

The `pseudo.lproj` folder and `Global.strings` file are included in the temp project.
## CocoaPods Environment

I tried both `1.0.0.beta.3` and `1.0.0`. Both versions had the same issue.
## Project that demonstrates the issue

I'd be happy to create a sample project if necessary. But it will take me some time to actually do. First I'd like to have someone verify I'm not just missing something obvious.

**Comment by segiddins** [comment]
@efirestone want to take a look into this?

**Comment by efirestone** [comment]
I'd have to dig in to why it's not working, but before spending too much time on it, can you update to the new, more-correct syntax for including resources and see if that fixes it? You'll want to replace `'Library/Resources/Localization/*.lproj'` with `'Library/Resources/Localization/**/*.lproj'` and re-run it.

**Comment by cnoon** [comment]
I can give this a shot on Monday @efirestone and get back to you. 👍🏼

**Comment by cnoon** [comment]
@efirestone, here's what I found.

### Option 1

```ruby
s.resources = 'Library/Resources/Localization/**/*'
# or
s.resources = 'Library/Resources/**/*'
```

This resulted in the `Localization` folder being imported twice, once as a folder and once as a group. The `pseudo.lproj` is removed from the group in this case, but not the folder. Additionally, all strings files are duplicated because of the double import.

### Option 2

```ruby
s.resources = 'Library/Resources/Localization/**/*.{lproj,png}'
```

This option resulted in the same behavior originally reported.

**Comment by efirestone** [comment]
This looks to be an issue with the exclude code. It's not specific to the resources code, and should apply to any attributes that use `:include_dir => true`.

Specifically, here's what's happening:

In `path_list.relative_glob`, the file list includes the value `Resources/pseudo.lproj` (no trailing slash), but in the code below a trailing slash is added to the pattern:

```
        list = Array(patterns).map do |pattern|
          if directory?(pattern) && dir_pattern
            pattern += '/' unless pattern.end_with?('/')
            pattern += dir_pattern
          end
          expanded_patterns = dir_glob_equivalent_patterns(pattern)
```

Afterward, our match pattern is `Resources/pseudo.lproj/**/*` (the `**/*` is the hardcoded `dir_pattern` for exclude patterns), which doesn't match the `Resources/pseudo.lproj` value from the file system.

I think the best way to handle this is to include the original pattern in the exclude patterns if we modify it. Like so:

```
        list = Array(patterns).map do |pattern|
          expanded_patterns = []
          if directory?(pattern) && dir_pattern
            expanded_patterns << pattern
            pattern += '/' unless pattern.end_with?('/')
            pattern += dir_pattern
          end
          expanded_patterns += dir_glob_equivalent_patterns(pattern)
```

This works, but the glob code is pretty complex, and I haven't touched it before, so would love some feedback. /cc @segiddins

**Comment by segiddins** [comment]
@efirestone if it works, I think we can live with that level of inelegance, so long as it's tested.
