### ISSUE TITLE
cUrl 401 Authorization Required after upgrading to 1.0.0

### ISSUE THREAD

**Issue by nmccann** [CocoaPods/CocoaPods#5318]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Updated from 0.39 to 1.0.0
Ran `pod install`

## What did you expected to happen?

Pods should have installed correctly

## What happened instead?

The following error was reported when trying to install a pod that has a username/password embedded in it's URL:
(Error edited for privacy)
```
[!] Error installing POD_NAME
[!] /usr/bin/curl -f -L -o /var/folders/temp/file.zip https://username:password@domain.com/file.zip --create-dirs --netrc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 401 Authorization Required
```

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.7
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/user/.rvm/rubies/ruby-2.2.2/lib
Repositories : custom-specs - ssh://domain.com:7999/ilb/specs.git @ 5823f9448a22ba75f6d3178b55a274d8c646f245
               master - https://github.com/CocoaPods/Specs.git @ 718aac8045b2e79ebc9fbc0bca34e475c2c31fa5
```

### Installation Source

```
Executable Path: /Users/user/.rvm/gems/ruby-2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@domain.com:7999/ilb/specs.git'

project 'Project.xcodeproj'

platform :ios, '9.0'

target 'Project' do
pod 'AffectedPod', '1.0.0'
end
```

### Workaround

Add credentials to `~/.netrc` file in the format:

```
machine DOMAIN
  login USERNAME
  password PASSWORD
```

Changing the command from:

```
/usr/bin/curl -f -L -o /var/folders/temp/file.zip https://username:password@domain.com/file.zip --create-dirs --netrc
```

To:

```
/usr/bin/curl -f -L -o /var/folders/temp/file.zip https://username:password@domain.com/file.zip --create-dirs --netrc-optional
```

Also resolves the problem, but from what I can tell this would require a change to Cocoapods.

### Summary

The new version of Cocoapods introduced authentication issues for a pod accessed with username/password. There is a reasonable workaround (which is probably the more correct approach). I'm more interested in knowing if this change was intentional or if it was an unexpected side effect of some other change.

Thank you for your time,
Noah

**Comment by segiddins** [comment]
@nmccann I believe changing https://github.com/CocoaPods/cocoapods-downloader to pass `--netrc-optional` would be 🚀

**Comment by sguillope** [comment]
Thanks @segiddins for the suggestion. Submitted CocoaPods/cocoapods-downloader#56
