### ISSUE TITLE
ARC settings should be specify-able for individual files.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#532]
So besides taking a boolean, it should also be able to take a file list/pattern.

**Comment by RayAnd** [comment]
agree with @VilemKurz exclusion pattern will help a lot. As quite often you have to exclude only one or two files now as non-arc, as all other are arc. So in most real life scenarios list all files apart from one in project is not make a lot of sense...

**Comment by AliSoftware** [comment]
@VilemKurz @RayAnd There is a very simple solution: simply put your ARC files and non-ARC files in separate subfolders, and then use:

```
s.requires_arc = 'classes/arc/*.m'
s.source_files = 'classes/arc/', 'classes/non-arc/'
```

**Comment by VilemKurz** [comment]
Yeah, that is how we had to do it in ShareKit too. But I would rather call it a workaround, not a solution.
