### ISSUE TITLE
Testing pods fail to lint with 1.0

### ISSUE THREAD

**Issue by nhgrif** [CocoaPods/CocoaPods#5321]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod lib lint`.  Also ran `pod spec lint`.  

In addition to trying on current head, also rolled back to the last tagged commit which successfully linted previous to 1.0 update.   

## What did you expected to happen?

Linting to succeed.

## What happened instead?

Linting failed.

```
 -> MTK (0.1.5)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

Here are the linker errors:

`ld: framework not found XCTest for architecture i386`

`ld: framework not found XCTest for architecture x86_64`

`XCTest` is a dependency of my library.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.7.4
Ruby lib dir : /Users/ngriffith/.rvm/rubies/ruby-2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 05f9fb7084ce906da05fb8e5772dde448deb4d8a
               metova - https://github.com/metova/ThunderCats.git @ 85fe53bdd01845057f42aba3981053d9c72ff766
               siriusxm-mzingman-ccl - https://github.siriusxm.com/mzingman/CCL.git @ 34d929d4721f5dcc211d3b5fad1d089a96fb1d64
```

### Installation Source

```
Executable Path: /Users/ngriffith/.rvm/gems/ruby-2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

https://github.com/metova/MetovaTestKit

Issue can be replicated on current master or current develop (`pod lib lint`), or even at the `0.1.5` tag (which is already in the CocoaPods master spec repo).

**Comment by neonichu** [comment]
@segiddins I think we should not to the app integration validation as part of lint for testing Pods?

**Comment by nhgrif** [comment]
Adding 

```
  s.user_target_xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '$(PLATFORM_DIR)/Developer/Library/Frameworks' }
```

allows the lint to succeed.

Is this correct?  Should I add this or should CocoaPods be updated to work without this specification (it worked without specifying pre-1.0)?

**Comment by segiddins** [comment]
@neonichu I want to see if we can make this work first

**Comment by juzooda** [comment]
I am getting a very similar issue:

`The following build commands failed:
	CompileC /Users/juzooda/Library/Developer/Xcode/DerivedData/App-dpbzztpryqlrgtaioarcnsikoofc/Build/Intermediates/Pods.build/Release-iphonesimulator/ExampleSDK.build/Objects-normal/i386/Tests.o ExampleSDK/ExampleSDK/Example/Tests/Tests.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
 -> ExampleSDK (0.1.0)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  ExampleSDK/ExampleSDK/Example/Tests/Tests.m:9:9: fatal error: module 'XCTest' not found

Analyzed 1 podspec.`

**Comment by dnkoutso** [comment]
Use `--verbose` and see where the build failed. 

Please open a new issue instead of commenting on an old issue.

**Comment by dnkoutso** [comment]
Use `--verbose` and see where the build failed. 

Please open a new issue instead of commenting on an old issue.
