### ISSUE TITLE
Add Support for :subspecs to :podspec

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#5327]
- [x] I've read and created the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

``` ruby
platform :ios, '9.0'
use_frameworks!

target 'StateView' do
  podspec :path => "StateView.podspec", :subspecs => ['Core', 'SnapKit']
end
```
## What did you expected to happen?

I'd hoped to get the dependencies of both Core, and SnapKit installed.
## What happened instead?

```

[!] Invalid `Podfile` file: Unrecognized options for the podspec method `{:path=>"StateView.podspec", :subspecs=>["Core", "SnapKit"]}`.

 #  from /Users/orta/dev/ios/StateView/Podfile:5
 #  -------------------------------------------
 #  target 'StateView' do
 >      podspec :path => "StateView.podspec", :subspecs => ['Core', 'SnapKit']
 #  end
 #  -------------------------------------------
```
## CocoaPods Environment

1.0, via the App.
## Project that demonstrates the issue

Don' think this need one.

**Comment by segiddins** [comment]
A tested PR in Core that implements this  would be nice ;)

**Comment by Coeur** [comment]
Would this work as well?

    target 'StateView' do
      pod 'StateView/Core', :podspec => 'StateView.podspec'
      pod 'StateView/SnapKit', :podspec => 'StateView.podspec'
    end

**Comment by segiddins** [comment]
@Coeur it already does, but since `pod` has the `subspecs` option, it only makes sense to add it to `podspec` as well

**Comment by orta** [comment]
( @Coeur - `podspec` and `pod` as the root attribute have [different behaviors](https://guides.cocoapods.org/syntax/podfile.html#group_dependencies) too 👍 )

**Comment by Coeur** [comment]
@orta is it OK for probot-stale to close issues opened less than 2 months ago by an Owner like you?

**Comment by orta** [comment]
I don't really have strong opinions on the issue, it's a nice to have and someone may be able to make it sometime - but I'd rather probot be pruning.
