### ISSUE TITLE
Empty Pod/Headers Folder

### ISSUE THREAD

**Issue by rikola** [CocoaPods/CocoaPods#5330]
# Report

## What did you do?

1. Upgraded CocoaPods to 1.0
2. Attempted to build my project by running `pod install`
3. :'(

## What did you expected to happen?

I expected the updated pods to be reinstalled into the project and work properly.

## What happened instead?

* My Pod/Headers folder is completely empty
* Most of my Pods are failing to build and throwing an import error when trying to do an import in brackets `<Abc/AbcIOS.h>`

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/eric/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9f75fcbdbc64d6ba5e4a1d23ca0b45e4a921222d
```

### Installation Source

```
Executable Path: /Users/eric/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '9.3'
use_frameworks!

def main_pods
	pod 'SWRevealViewController'
	pod 'TPCircularBuffer'
	pod 'EZAudio', '~> 1.1.4'
	pod 'KAProgressLabel'
	pod 'EAIntroView', '~> 2.8.0'
	# Used for layout inspection in Reveal 
	pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'CocoapodsShitstorm' do
  main_pods
end
```

## Project that demonstrates the issue

[Error Sample Project](https://github.com/rikola/CocoapodsErrorSample)

**Comment by neonichu** [comment]
It is expected that `Pods/Headers` is empty when using frameworks integration.

The only issue I can see with your example project is that the `EZAudio` Pod doesn't seem to work with frameworks integration because it tries to import its own headers using paths like `EZAudioiOS` which is not the same as its module name, so this seems to be an issue that you should report to its author.

**Comment by rikola** [comment]
I figured out the issue was fixed by nuking my `build/` and `DerivedData/` folders. Weird stuff. Thanks for checking it out though!

**Comment by adams3** [comment]
Hey there, I have the same problem. My pods not working after update to 1.0.0 . Could you describe your solution? 'No such module <pod>' in XCode

**Comment by rikola** [comment]
Hi,

I deleted the entire project build folder and derived data folder and did a build and clean and everything worked. Seems to be that cocoapods isn't picking up the old files and replacing them.

**Comment by achakra21** [comment]
@rikola above steps doesn't solved my problem
