### ISSUE TITLE
New cocoapods 1.0 scoped pod targets lead to runtime problems with dynamic frameworks

### ISSUE THREAD

**Issue by mkujalowicz** [CocoaPods/CocoaPods#5340]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Let's say I have a simple swift app (source code available at: https://github.com/mkujalowicz/cocoapods_frameworks_test.git)

which consists of the following targets:

- cocoapods_test (main app)
- internal_module (dynamic framework with some custom classes that inherit from pod-based classes)
- internal_moduleTests (unit tests for my internal module without the HOST app)

This is the Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

target 'cocoapods_test' do
    pod 'BEMSimpleLineGraph'
end

```
I have one custom class in the internal module: CustomBEMSimpleLineGraphView which inherits from BEMSimpleLineGraphView (pod BEMSimpleLineGraph). The custom class supports rendering UI in the Interface Builder (IBDesignable)

## What did you expected to happen?

I'd expect that I could build the app, run unit tests, use my custom class in the interface builder. It did work with cocoapods 0.39

## What happened instead?

1: Building fails with error: 

> internal_module/CustomBEMSimpleLineGraphView.swift:10:8: No such module 'BEMSimpleLineGraph' 

Without scoped pod targets, it was possible to import pod frameworks even if the target wasn't listed in the Podfile because Xcode could easily find compiled modules in the CONFIGURATION_BUILD_DIR path which was the same for all products

This can be fixed by integrating pods with all targets:

## Solution 1 - Integrate cocoapods with all targets

```
target 'cocoapods_test' do
    pod 'BEMSimpleLineGraph'

#    Solution 1
    target 'internal_moduleTests' do
        inherit! :search_paths
    end
    
    target 'internal_module' do
        inherit! :search_paths
    end
end

```

... unfortunately it doesn't solve next problems:

2: Unit testing fails with error:

> The bundle “internal_moduleTests” couldn’t be loaded because it is damaged or missing necessary resources.
> Library not loaded: @rpath/BEMSimpleLineGraph.framework/BEMSimpleLineGraph
>   Reason: image not found)
> Program ended with exit code: 82

3: Rendering custom class CustomBEMSimpleLineGraphView in interface builder (Main.storyboard) fails with error:

> IB Designables: Failed to render instance of CustomBEMSimpleLineGraphView: dlopen(internal_module.framework, 1): Library not loaded: @rpath/BEMSimpleLineGraph.framework/BEMSimpleLineGraph
>   Referenced from: internal_module.framework
>   Reason: image not found

## Solution 2 - Disable scoped pod targets

```
 post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            xcconfig_path = configuration.base_configuration_reference.real_path
            xcconfig_settings = Hash[*File.read(xcconfig_path).lines.map{|x| x.tr("\n","").split(/\s*=\s*/, 2)}.flatten]
            xcconfig_settings['CONFIGURATION_BUILD_DIR'] = '$(PODS_CONFIGURATION_BUILD_DIR)'
            File.open(xcconfig_path, "w") { |file|
                xcconfig_settings.each do |key,value|
                    file.puts "#{key} = #{value}"
                end
            }
        end
    end
 end
```

All 3 problems fixed! Cocoapods needs to be integrated only with the main target

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : aspera-pods-pods - https://gitlab.aspera.us/pods/pods.git @ 22f53958a80734ae05a71ebb840ec8d28b38bd9d
               master - https://github.com/CocoaPods/Specs.git @ 5000b86559090834d60ae48f941d53e79799e4d8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
slather               : 2.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

target 'cocoapods_test' do
    pod 'BEMSimpleLineGraph'
end
```

## Project that demonstrates the issue

https://github.com/mkujalowicz/cocoapods_frameworks_test.git

**Comment by segiddins** [comment]
@mrackwitz this is another scoping issue 😁

**Comment by neonichu** [comment]
I think actually linking the test bundle against its required frameworks instead of just inheriting search paths will fix the test issue. As far as `IBDesignable` is concerned, I guess that is exactly the same issue as #5334, maybe we can genericise the solution.

**Comment by segiddins** [comment]
@neonichu but that would only work for `use_frameworks!`, no?

**Comment by neonichu** [comment]
Scoping itself is only relevant for frameworks anyway, isn't it?

**Comment by mrackwitz** [comment]
Nope, it's relevant for both.

**Comment by neonichu** [comment]
Ah, I didn't realise that. But I guess module auto-loading as it happened here doesn't work for static libraries, does it?

**Comment by mrackwitz** [comment]
>But I guess module auto-loading as it happened here doesn't work for static libraries, does it?

Imho that doesn't matter, because CocoaPods requires that every target explicitly declare its dependencies. Sharing them with targets, which are not declared in the Podfile is not explicitly supported.

So is there any issue here beyond what's documented in #5334?

**Comment by neonichu** [comment]
Don't think so, we can close it as a dupe
