### ISSUE TITLE
Development Pod Needs Derived Data Cleared - Xcode 7.3 Cocoapods 1.0.0

### ISSUE THREAD

**Issue by mrrobby** [CocoaPods/CocoaPods#5341]
# Report

The problem showed itself as an inability to observe changes in a development pod when rebuilt.  
That is, changing the podfile syntax to:
```ruby
pod 'Name', :path => '~/code/Pods/'
```
allowed for editing as usual, but did not reflect changes made when the master app was built.

> *This is solved and I'm providing a description.  The Solution is to delete the Derived Data.*

## What did you do?

We were initially just attempting to turn on our debug logging when integrating some new functionality, which in this case, involved bringing in one of our pods as a development pod.  
In addition to the podfile change above, several steps were also taken, as per the usual, delete Cocoapods cache and Pods directory first.
```sh
rm -rf ~/Library/Caches/CocoaPods
rm -rf ./Pods/
```

## What did you expected to happen?
It was expected for the pod in the development pod folder to be editable and build with changes made, which at first, was simply enabling NSLog-type debug calls, which evolved into making trivial code changes to verify changes were not applied in the build. 

## What happened instead?
Nothing happened.  Changes were not applied.  Setting breakpoints in the code where getting hit, but any changes to the code made did nothing.  Product clean, steps above, etc.. did nothing to help. Some warnings were also showing appearing to be `CLANG MODULE` type issues.  I don't have them anymore (sorry), but similar to [here](https://forums.developer.apple.com/thread/17921).  The solution steps listed on apple dev were not applied here.  It's all the `Derived Data.`  Just delete that when in doubt.

## CocoaPods Environment

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : ~/.rvm/rubies/ruby-2.3.0/lib
Repositories : contentful - https://github.com/contentful/CocoaPodsSpecs.git @ b345dbd8ec819403b466678312f5c04e69101726
               master - https://github.com/CocoaPods/Specs.git @ 813212d91d9feeb2d90011ef4bd57b36f51fc900
               private-specs-repo - https://private/specs/URL.git @ stuff
```

### Installation Source

```
Executable Path: ~/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by mrackwitz** [comment]
Thanks for bringing that to our attention here. This is due the changes around the scoping. Pod targets are build now into a subdirectory of the default `CONFIGURATION_BUILD_DIR`, but the base dir is by default part of the `FRAMEWORK_SEARCH_PATHS`, so that the old stale build artifacts lurking there are picked up by the compiler first, so that it misses the new shiny build products from the scoped build directory.

We could have done a better job in documenting that in the release blog post. It might still make sense to push something official out around that. :+1:

/c @orta

**Comment by orta** [comment]
Could we update the de-integrator's copy to recommend this also? 

I'll make a quick edit to the blog post too.

**Comment by mrrobby** [comment]
Right on.  Thanks guys!

**Comment by benasher44** [comment]
It sounds like everything to do is done here. In other news, Xcode 8 + macOS Sierra made a lot of headway in terms of amount of required derived data clearing. Going to close this one. Thanks!

**Comment by graph** [comment]
I'm using cocoapods version 1.3.1 and I experience this issue too with current stable version of Xcode 8.3.3 (8E3004b). Every time I change a development pod I need to do a build->clean. Interestingly though when I make a change to the source file it seems to compile it, and do linking steps like it should. But final application that gets uploaded to device is using old build.

**Comment by flockoffiles** [comment]
Is there any known work-around for this issue? I am experiencing it with cocoapods 1.4.0

**Comment by aunnnn** [comment]
Try add that pod (framework) as a build target to a scheme.

**Comment by flockoffiles** [comment]
Unfortunately, adding the pod to the scheme does not help in my case... Any other work-arounds?

**Comment by JettF** [comment]
This seems to have cropped up again. I am using Cocoapods version 1.5.3. Can this issue be re-opened?

**Comment by Aranoledur** [comment]
Same problem, Cocoapods version 1.5.3, Xcode 9.4.1

**Comment by grigorye** [comment]
Same story, CocoaPods 1.5.3, Xcode 10 beta 6/new build system.

**Comment by mkubista** [comment]
Same for me. When using incremental build in XCode10 beta 6, the changes are compiled, but new framework is not copied into the .app package. When I copy it manually and run Build and run again, it works and changes are visible in app. Also clean build helps.

**Comment by zhz821** [comment]
Same problem, I'm using XCode10 release version.

**Comment by dnkoutso** [comment]
This is a known issue https://github.com/CocoaPods/CocoaPods/issues/8073.
