### ISSUE TITLE
inherit! :search_paths not inheriting from abstract targets

### ISSUE THREAD

**Issue by fcy** [CocoaPods/CocoaPods#5342]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

`inherit :search_paths` doesn't seem to be working for abstract targets. The child target does not get any of the pods from the parent target in its Framework Search Paths.

Here is [a question](https://groups.google.com/forum/#!topic/cocoapods/mErQz0YBHxw) I sent to the mailing list regarding this way of using abstract targets. Take a look if you want more context on why I need it.
## What did you do?
1. Download [sample project](http://felipecypriano.com/files/NothingInherited.zip)
2. Open AllApps.xcworkspace
3. Click on NothingInherited project
4. Select either UnitTests or NothingInheritedTests
5. Build Settings / Framework Search Path
## What did you expected to happen?

The test target's Framework Search Path to contain its own direct dependencies and the pods from the parent target.
## What happened instead?

The test targets don't have any of the pods from the parent project in its Framework Search Path.
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ec824ecf1906f2d6885b12e2f1fbe0ded68f0647
               thumbtack - ssh://git@github.com/thumbtack/PodSpecs.git @ 5235a22ee4f46dd828d071714f66c4799b779a02
               thumbtack-1 - /Users/felipe/.cocoapods/repos/thumbtack @ 5684d57c262098967789671f3f6b5a38e07c67dd
```
### Installation Source

```
Executable Path: /Users/felipe/.gem/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
use_frameworks!

workspace 'AllApps'

abstract_target 'App' do
  pod 'AFNetworking'

  target 'NothingInherited'
  # target 'AnotherAppTarget'

  abstract_target 'TestGroup1' do
    inherit! :search_paths

    pod 'Kiwi'

    target 'UnitTests'
    # target 'AnotherAppTargetUnitTests'
  end

  abstract_target 'SnapshotTestsGroup' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'

    target 'NothingInheritedTests'
    # target 'AnotherAppTargetSnapshotTests'
  end
end
```
## Project that demonstrates the issue

http://felipecypriano.com/files/NothingInherited.zip

**Comment by segiddins** [comment]
That should be raising an exception -- inheriting search paths from an abstract target is kinda nonsensical

**Comment by fcy** [comment]
The weird thing is that it had been working fine since I posted the question on the mailing list (Mar 30th). My goal then was to not depend on any hidden implementation detail. I went with it since I got no response 😕.

What is the correct way to share pods between different targets - in possible different projects?

For reference this is the `Podfile` I posted in the mailing list:

```
abstract_target 'AppCommons' do
  pod 'InternalSharedKit', { path: 'InternalSharedKit' }
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'Reveal-iOS-SDK', :configurations => ['Debug']

  target 'AppA' do
    project 'AppA/AppA'
  end

  target 'AppB' do
    project 'AppB/AppB'

    pod 'Facebook-iOS-SDK', '~> 3.0'
  end

  abstract_target 'UnitTests' do
    inherit! :search_paths

    pod 'Nocilla', NOCILLA_VERSION
    pod 'Kiwi', KIWI_VERSION

    target 'AppAUnitTests' do
      project 'AppA/AppA'
    end

    target 'AppBUnitTests' do
      project 'AppB/AppB'
    end
  end
end
```

+1 for throwing an exception is it should be invalid.

**Comment by segiddins** [comment]
Oh you can share pods with `abstract_target` just fine, the issue is that in order for search paths to be inherited, the inheriting target needs a concrete use of that pod to point to

**Comment by fcy** [comment]
So the only to share pods between targets in different projects and with different parent apps using `abstract_target` would be to have an `implements` option, something like this:

```
abstract_target 'UnitTests' do
  pod 'Specta'
  pod 'Expecta'
end

abstract_target 'AppCommons' do
  pod 'Something'

  target 'AppA' do
    project 'AppA/AppA'

    target 'AppATests' do
      inherit! :search_paths

      implements 'UnitTests'
    end
  end

  target 'AppB' do
    project 'AppB/AppB'

    target 'AppBTests' do
      inherit! :search_paths

      implements 'UnitTests'
    end
  end
end
```

right?

**Comment by segiddins** [comment]
or just use a ruby method for that ¯\_(ツ)_/¯

**Comment by fcy** [comment]
😳I guess I need to work on my Ruby skills

**Comment by evanjmg** [comment]
```
def all_pods
# go here - pods
end

target 'App'
all_pods
end
```
works for me
