### ISSUE TITLE
Feature Request: support multiple header_mappings_dirs in podspecs

### ISSUE THREAD

**Issue by hborders** [CocoaPods/CocoaPods#5344]
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I'm podifying my project, and podifying one of my cross-platform C++ projects was difficult because I could only specify one `header_mappings_dir`. For additional folders, I had to add a `pod_target_xcconfig` and ensure that `HEADER_SEARCH_PATHS` included my extra directories. This works, but supporting one than one `header_mappings_dir` seems simpler.

Thanks!

**Comment by mrackwitz** [comment]
`header_mappings_dir` is used by very few podspecs and is already now quite cumbersome to maintain. I would like to avoid making that even more complex for edge cases, which can be still resolved by just slightly more complex podspecs.

**Comment by hborders** [comment]
That's fine. I didn't realize this was such a sparsely used, expensive feature. It's easy enough to work around with `pod_target_xcconfig`, so I retract my feature request.
