### ISSUE TITLE
Problem with Hockeyapp

### ISSUE THREAD

**Issue by erema** [CocoaPods/CocoaPods#5345]
error: Resource "/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-bgszvlzstziakddnkornjorikbox/Build/Products/Adhoc-iphoneos/HockeySDK-Source/HockeySDKResources.bundle" not found. Run 'pod install' to update the copy resources script

we have a problem on our CI agent. any ideas?

**Comment by neonichu** [comment]
Either the resource bundle has not been build or your sandbox is out-of-date and you have to run `pod install` again. If you believe this is an issue with CocoaPods, please share a project that reproduces the issue.

**Comment by erema** [comment]
We did "pod install", but it didn't help. I can't share a project. I think it depends on string from  file Pods-XXX-resources.sh "install_resource "$PODS_CONFIGURATION_BUILD_DIR/HockeySDK-Source/HockeySDKResources.bundle"".

**Comment by segiddins** [comment]
If you can't share a project that reproduces this issue, I'm afraid you're on your own -- its kinda hard to debug things you can't reproduce!

**Comment by erema** [comment]
I saw few issues with the same problem.

**Comment by akkuprin** [comment]
I have a same problem with HockeySDKResources.bundle

**Comment by aphex3k** [comment]
Same here

**Comment by mmackowiak** [comment]
+1, same issue found.

**Comment by matthew-an** [comment]
+1, same issue found.

**Comment by wolf81** [comment]
I experience the same when building on Jenkins with the HockeySDK. Building directly from Xcode works just fine.
