### ISSUE TITLE
the order problem

### ISSUE THREAD

**Issue by billychen2014** [CocoaPods/CocoaPods#5347]
## What did you do?

Run `pod install`

## What did you expected to happen?

Install all pod dependencies correctly.

## What happened instead? 

Pod installed Failed

## CocoaPods Environment

CocoaPods version 1.0.0

## Project that demonstrates the issue

Let's use one example to show this issue: (note the order of contents for 1 and 2)

1. wrote Podfile like below:

```ruby
target "TestCoCoaPods" do

platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'
end
```

Result : this work well

2.Wrote Pofile like below:

```ruby
target "TestCoCoaPods" do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'

platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'
end
```

Result : error pops up:

```
[!] Unable to satisfy the following requirements:

- `AFNetworking (~> 3.0)` required by `Podfile`

Specs satisfying the `AFNetworking (~> 3.0)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by mrackwitz** [comment]
The order doesn't matter. The DSL is evaluated to build an abstract representation of your requirements per target. The last `platform` declaration overwrites all former values.

**Comment by mrackwitz** [comment]
To make that more clear, CocoaPods should reject Podfiles like yours and explain that the `platform` might only declared once per block. This is now tracked by https://github.com/CocoaPods/Core/issues/328.
