### ISSUE TITLE
Abstract target not building symbols for armv7k (Apple Watch)

### ISSUE THREAD

**Issue by macecchi** [CocoaPods/CocoaPods#5349]
🌈\* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I updated my Podfile from 0.39 to 1.0, migrating a previous `def shared_pods` to an `abstract_target` and fixed the targets (iOS, watchOS 2) to be inside the abstract target.
## What did you expected to happen?

The targets should build normally, with the shared pods being imported to my iOS app and my WatchKit Extension.
## What happened instead?

The WatchKit Extension failed to build because the shared libraries were not build for the Apple Watch architecture (armv7k). I can confirm that the Pods for the WatchKit Extension target are being linked when building.

The errors:

> **Undefined symbols for architecture armv7k:**
>   "realm::SharedGroup::export_linkview_for_handover(std::__1::shared_ptrrealm::LinkView const&)", referenced from:
>       realm::_impl::ListNotifier::ListNotifier(std::__1::shared_ptrrealm::LinkView, std::__1::shared_ptrrealm::Realm) in libRealm-watchOS.a(list_notifier.o)
>       realm::_impl::ListNotifier::do_detach_from(realm::SharedGroup&) in libRealm-watchOS.a(list_notifier.o)
>   "realm::_impl::TransactLogEncoder::select_descriptor(unsigned long, unsigned long const_)", referenced from:
>       realm::_impl::TransactReverser::select_descriptor(unsigned long, unsigned long const_) in libRealm-watchOS.a(transact_log_handler.o)
> ...
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5fc18b914aad538604eaffeeb591981496055592
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
abstract_target 'TDG' do
  pod 'AFNetworking', '3.1.0'
  pod 'Realm', '0.102.1'

  target 'MyApp' do
    platform :ios, '8.0'

    pod 'GoogleAnalytics'

  end

  target 'MyApp WatchKit Extension' do
    platform :watchos, '2.0'
  end
end
```

**Comment by neonichu** [comment]
Hm, when I integrate using the given Podfile, I don't even see a target being created specifically for watchOS. @mrackwitz Might be a deduplication issue?

**Comment by macecchi** [comment]
Any updates?

**Comment by mrackwitz** [comment]
Sorry the lack of feedback so far. I'll look into that and hopefully figure out what exactly is going on here.

**Comment by twomedia** [comment]
I seem to be experiencing the exact same issue, using Realm as well. Eager to find a solution to this.

**Comment by twomedia** [comment]
I managed to fix this issue by forcing pods to reinstall Realm. Not sure if this is relevant in this case, but worth a try.
`rm -r Pods/Realm*
rm -r ~/Library/Caches/CocoaPods/Pods/Released/Realm*
pod install`

**Comment by twomedia** [comment]
Alright I'm experiencing this issue still, I've spoken to an Apple Engineer at WWDC and even he could work out what was going on. We are expecting the exact same issue as above.

**Comment by macecchi** [comment]
This doesn't seem to happen with the latest versions. It's been a while there is not activity in this issue, so please feel free to close it :)

**Comment by benasher44** [comment]
Ah thanks for checking on that and letting us know! I'll close this then. Have a great day!
