### ISSUE TITLE
Feature Request: fail `pod install` if a podspec source_files entry doesn't exist

### ISSUE THREAD

**Issue by hborders** [CocoaPods/CocoaPods#5354]
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I'm creating a podspec from an unpodified 3rd party library that has a bunch of cross-platform CPP code. Not all of the code can be compiled for iOS, so I have to specify a bunch of individual `.cpp` files in my podspec's source_files. However, I had a typo in my list, and I wasted an hour trying to figure out linker problems before I figured out all of my files weren't compiled.

If a source_files entry doesn't match any files (through a file glob or otherwise), `pod install` should fail.

**Comment by segiddins** [comment]
`pod spec/lib lint` already does this

**Comment by hborders** [comment]
Thanks. I usually run lint last because it requires that I have a tag in place first. This is the first time I've had to enter this many `source_files` entries, so of course I made some mistakes.

Is there a way to run the linter without putting the podspec in source control?

**Comment by segiddins** [comment]
`pod lib lint` does exactly that

**Comment by hborders** [comment]
Thanks!
