### ISSUE TITLE
Linking against frameworks not available in the iOS Simulator SDK

### ISSUE THREAD

**Issue by Thomvis** [CocoaPods/CocoaPods#5356]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

I have an internal pod (let's call it Core) and a project that depends on Core. Core uses Metal, so it has `weak_frameworks = 'Metal', 'MetalKit', 'MetalPerformanceShaders'` in its podspec. I ran `pod install` and tried to run the project on the iOS Simulator.

## What did you expected to happen?

I would like to be able to build & run the project without further modifications.

## What happened instead?

The linker fails with the following error:

> ld: framework not found MetalKit
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I can fix this error by modifying the Other Linker Flags of the Core framework target inside the Pods project like so:

![screen shot 2016-05-18 at 10 49 43](https://cloud.githubusercontent.com/assets/134170/15352803/4a30e3fc-1ce6-11e6-9e20-84dc3dfbd513.png)

I more or less understand why this is needed. My guess is that Metal is not included at all in the iOS Simulator SDK, so that it can't link to it (even not weakly). 

I think it'd be great if we can somehow specify this in the podspec, so that manual changes after each integration are not needed. Perhaps by allowing something like `s.iossim.weak_frameworks =` next to `s.ios.weak_frameworks = `. 

Alternatively, I might be able to solve this in the Podfile of the project with a `post_install` hook? However, we have a lot of projects depending on this Core pod so we would need the same code in a lot of Podfiles, which makes it less preferable.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p576 (2014-09-19 revision 47628) [x86_64-darwin14.0.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.4.0
Ruby lib dir : /Users/Thomas/.rvm/rubies/ruby-2.0.0-p576/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ dea96ed41c0f5b3c73772383c2c189233396c348
               touchwonders-components-cocoapods - https://gitlab.touchwonders.com/components/cocoapods.git @ 8128c56552e67c4d48da53252e8fa6f8806e4d42
```

### Installation Source

```
Executable Path: /Users/Thomas/.rvm/gems/ruby-2.0.0-p576/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 0.4.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.touchwonders.com/components/cocoapods.git'

platform :ios, '8.0'

use_frameworks!

target 'Whitelabel' do

	pod 'Core', :path => '/path/to/core'

end
```

## Project that demonstrates the issue

I could provide a project if it is useful.

**Comment by neonichu** [comment]
Yah, there's no `Metal` in the iOS simulator. IMO, using a `post_install` hook is the way to go as this is probably quite an edge case.

**Comment by segiddins** [comment]
This is pretty much a duplicate feature request as https://github.com/CocoaPods/CocoaPods/issues/5071, which is still awaiting a proposal the core team can evaluate.

**Comment by neonichu** [comment]
True, let's close this as a dupe, then.

**Comment by Thomvis** [comment]
I thought I'd searched for existing issues enough, guess not. Thanks, I'll keep track of the other issue and try the post_install approach.
