### ISSUE TITLE
Missing header files for pod with only headers and vendored library on 1.0 #3499

### ISSUE THREAD

**Issue by jrz** [CocoaPods/CocoaPods#5357]
Continuation of #3499

Used pod init to convert a swift iOS (+tvOS) to pods.
Added FBSKCore and use_frameworks!
pod install 
The headers directory is empty.
If I remove use_frameworks!, the headers are being symlinked again

$ pod --version
1.0.0

**Comment by neonichu** [comment]
This is expected behaviour. The headers are a part of the built framework when using frameworks integration.

**Comment by jrz** [comment]
Ok, but the framework isn't being built because it cannot find the header files

**Comment by neonichu** [comment]
Please fill out <https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md> then, without an actual error or a reproducible project, we can't do anything.

**Comment by VMPURANIK** [comment]
I am having a similar problem with pods version 1.0.1.
pod install works correctly, but the Headers folder is empty since I use frameworks in the Podfile. Submitted issue using the ISSUE_TEMPLATE.

**Comment by gabrielafonsogoncalves** [comment]
@jrz did you fix that issue? I have a similar one.

**Comment by VenuKotha** [comment]
i am having similar issue. My issue is i am writing private pod which is implemented using objectiveC and swift. when I build my private pod it referred to swift compiler header and built successfully, When I add as dependent for the main project giving error "xxxxx-swift.h" file not found.  Is there any solution. please share
