### ISSUE TITLE
file not found after adding a framework using "vendored_frameworks"

### ISSUE THREAD

**Issue by gabrielafonsogoncalves** [CocoaPods/CocoaPods#5365]
Hi everybody,

I'm adding a `vendored_framework` using cocoa pods 1.0. It seems to be ok, but when I try to build and run my example app I got an error saying that it cannot find a header that I imported in one class from `vendored_framework`.

so maybe I'm missing something.

That's how I'm adding that `vendored_framewok`
`s.vendored_frameworks = ['Pod/Frameworks/SomeFramework_API.framework']`

This is how I'm importing a class from that framework 
`#import <SomeFramework_API/BBComponent.h>` 

This is the error I get:
`SomeFramework_API/BBComponent.h file not found`

Do I'm missing something? I'm working with Objective-c using `use_frameworks!`

**Comment by segiddins** [comment]
Please fill out the [issue template](https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md), including a sample project, so we can take a look. Thanks!

**Comment by gabrielafonsogoncalves** [comment]
@segiddins let me check if I can provide a sample project.

**Comment by gabrielafonsogoncalves** [comment]
@segiddins a quick question, is there a way to include just specific headers in the auto generated umbrella header?

**Comment by segiddins** [comment]
@gabrielafonsogoncalves only one module map. And only public headers are added to the module map.

**Comment by gabrielafonsogoncalves** [comment]
@segiddins good, thanks !... I tried to add a `public_headers_files` to my subspecs but it seems that it doesn't make any difference. I got a -umbrella with all headers. Maybe I'm doing something wrong.

**Comment by cnstar** [comment]
example?

**Comment by mjwheatley** [comment]
@gabrielafonsogoncalves did you ever get this working?  If so, could you provide some guidance?
