### ISSUE TITLE
unexpected error from 'pod trunk deprecate ...'

### ISSUE THREAD

**Issue by mr-fixit** [CocoaPods/CocoaPods#5372]
🌈

# Report

## What did you do?

    $ pod trunk deprecate CtrlZ
    
## What did you expected to happen?

I thought I might get a message, hopefully indicating 'success'.

## What happened instead?

'An unexpected error ocurred', followed by HTML.  See [tmp.html.TXT](https://github.com/CocoaPods/CocoaPods/files/273217/tmp.html.TXT)

For grins, I did it again
    $ pod trunk deprecate CtrlZ

and saw
    [!] There were no published versions to deprecate.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/eslosser/.rbenv/versions/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d6f418d80168c250e361ab66a55fc5e8b0305bb5
```

### Installation Source

```
Executable Path: /Users/eslosser/.rbenv/versions/2.2.3/bin/pod
```

### Plugins

```
cocoapods-acknowledgements : 1.0.0
cocoapods-deintegrate      : 1.0.0
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-trunk            : 1.0.0
cocoapods-try              : 1.0.0
```

As long as I'm reporting bugs, 'occurred' should not be spelled 'ocurred'.

**Comment by k0nserv** [comment]
Do you know when this roughly so I can find the error?

**Comment by orta** [comment]
This is a known bug with trunk: https://github.com/CocoaPods/trunk.cocoapods.org/issues/168 - we just need to fix it there 👍
