### ISSUE TITLE
Storyboard IBDesignable is broken in 1.0.0.beta4 - 1.0.0 Release.

### ISSUE THREAD

**Issue by wfilleman** [CocoaPods/CocoaPods#5377]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Our team was using CocoaPods 1.0.0.beta.2 without issues. We updated to the official release of 1.0.0 and discovered Storyboard rendering breaks with the error: "Failed to render instance of XXXX:dlopen(IBDesignablesView.framework, 1): Library not loaded: @rpath/JSBadgeView.framework/JSBadgeView"

XXXX represents each file with IBDesignable that's attempting to render on the Storyboard in IB.

IBDesignablesView is the name of our embedded framework containing only IBDesignable files for IB rendering.

JSBadgeView is a pod we use to add badges to UIViews.

Updating to CocoaPods 1.0.0.beta.3 works just like beta.2. Updating to beta.4 breaks Storyboard rendering. Issue is also present in the official 1.0.0 release.

It appears to be related to this enhancement introduced in beta.4:
https://github.com/CocoaPods/CocoaPods/pull/4146

## What did you expected to happen?

We expected to see rendering in the Storyboard just like in 1.0.0.beta.2

## What happened instead?

Storyboard rendering is broken staring in 1.0.0.beta.4. We confirmed that 1.0.0.beta.3 works as expected. 

## CocoaPods Environment

```
   CocoaPods : 1.0.0.beta.4
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7ed1d1c6ce59711198da8ef07457a98e0a3afd31
```

**Comment by neonichu** [comment]
Yep, we are tracking this issue already as #5334
