### ISSUE TITLE
Pod Init Output is inconsistient

### ISSUE THREAD

**Issue by edjiang** [CocoaPods/CocoaPods#5378]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

On some projects, I run `pod init` and it gives me:

```Ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
```

On others, I get:

```Ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Empty Project' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Empty Project

end
```

## What did you do?

I ran `pod init` in several empty, new projects. 

## What did you expected to happen?

I expected the targets to show up in the podfiles. 

## What happened instead?

The target is missing in new podfiles

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/edjiang/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4efa06ed5a4069e3ad66e7039ae686b89be1ac14
```

### Installation Source

```
Executable Path: /Users/edjiang/.rvm/gems/ruby-2.2.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by orta** [comment]
can you give us some examples zipped up?

**Comment by neonichu** [comment]
I just noticed the same thing with this project: [test12.xcodeproj.zip](https://github.com/CocoaPods/CocoaPods/files/273677/test12.xcodeproj.zip)

It has two targets:

```
$ xcodebuild -list
Information about project "test12":
    Targets:
        test12
        Extension
```

But the generated `Podfile` only has one:

```
$ pod init
$ grep target Podfile 
target 'Extension' do
```

**Comment by edjiang** [comment]
It's really inconsistient for me; I created a few projects and it seemed to do either way on a consistient basis. But it would do the same thing for each project. 

Here's two of the folders I'm working with: https://github.com/edjiang/cocoapods-issue-5378

**Comment by segiddins** [comment]
My guess is that's because they have Test in the target name, but I'm unsure.

**Comment by edjiang** [comment]
Ah, that makes sense. I'm building a pod so have a bunch of random projects named 'XYZ Test" recently. Thought it was potentially a change in 1.0. I thought Cocoapods used to also generate a target for tests though?

**Comment by orta** [comment]
It does, but it assumes that "XXX Test" is a test on "XXX" - so when "XXX" doesn't exist, it doesn't show it. Sounds like a a bug.

**Comment by segiddins** [comment]
Agree it's a bug, just was guessing at the cause 😉

**Comment by neonichu** [comment]
Oh, it should probably use the product type to determine the identity, not the name :)

**Comment by segiddins** [comment]
@neonichu iirc I didn't do that because `Xcodeproj##AbstractTarget` didn't have a helper for `test_target_type?`

**Comment by edjiang** [comment]
Thanks for fixing this!
