### ISSUE TITLE
File Acknowledgments.plist 

### ISSUE THREAD

**Issue by leoniralves** [CocoaPods/CocoaPods#5387]
'Acknowledgements' files containing license for each Pod, changed location in Cocoapods 1.0. New path: ```Pods/Target Support Files/Pods-<target name>/Pods-<target name>-acknowledgements.plist```

**Comment by orta** [comment]
This isn't really an actionable issue, so I'm going to close it - thanks for leaving breadcrumbs for others though.

**Comment by leoniralves** [comment]
In fact i tried to update the ```wiki``` at https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements , but I was not able to send a PR.
