### ISSUE TITLE
The dependency `GoogleMaps` is not used in any concrete target.

### ISSUE THREAD

**Issue by RahulTak** [CocoaPods/CocoaPods#5388]
##  i installed the CocoaPod

ℹ i installed the CocoaPod then i create the Podfile and write the code for the GoogleMaps   
e.g. Run `sudo gem install cocoapods`
 after that create the podfile and write the codes
Run `pod install`

## got an error 

ℹ after that i got an error  The dependency `GoogleMaps` is not used in any concrete target.
i update the cocoapods after searching on the internet about this error

**Comment by segiddins** [comment]
Please fill our the entire issue template, including your podfile.

**Comment by yanioro** [comment]
Hello, I have the same issue. can you let me know the solution?
Thanks

**Comment by AngelGarcia13** [comment]
You should use 

> pod init

 and use the default template, then run 

> pod install

.

It seems like things changed in the new version.

**Comment by CanOpener** [comment]
Adding a target to my Podfile helped. like this

```
target 'AppName'
source 'https://github.com/CocoaPods/Specs.git'
pod 'GoogleMaps'
```
