### ISSUE TITLE
Prefix not added to umbrella header

### ISSUE THREAD

**Issue by valeriomazzeo** [CocoaPods/CocoaPods#5390]
## What did you do?
```
Podfile
pod RestKit
```

Run `pod install`

## What did you expected to happen?

Project compiling correctly.

## What happened instead?

Project doesn't compile

## CocoaPods Environment

I have found out that
```
#if __IPHONE_OS_VERSION_MIN_REQUIRED
  #import <SystemConfiguration/SystemConfiguration.h>
  #import <MobileCoreServices/MobileCoreServices.h>
  #import <Security/Security.h>
#else
  #import <SystemConfiguration/SystemConfiguration.h>
  #import <CoreServices/CoreServices.h>
  #import <Security/Security.h>
#endif
```
it's correctly present in the `AFNetworking-prefix.pch` file as it should, but for some reason (using frameworks) the prefix file is ignored.
If we try add the above to the umbrella header `AFNetworking-umbrella.h`, it magically compiles.

Perhaps cocoapods when generating the umbrella header should include the content of the prefix file?

## Project that demonstrates the issue

http://www.speedyshare.com/jKSMd/restkit-cocoapods.zip

**Comment by neonichu** [comment]
Just to clarify, this is not a regression in any way, is it?

**Comment by valeriomazzeo** [comment]
I don't think it's a regression

**Comment by segiddins** [comment]
I don't think this is something we want to do -- prefix headers are explicitly for _building_ a target and not for consumers of that target.
