### ISSUE TITLE
Symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by dms90** [CocoaPods/CocoaPods#5391]
After update to 1.0.0, I have this error while building my project: "Symbol(s) not found for architecture arm64"

Pods affected: Alamofire and CocoaLumberjack

**Comment by segiddins** [comment]
Please fill out the issue template (https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by dms90** [comment]
Sorry @segiddins for the lazy report!

I fixed the error running `pod deintegrate` and then `pod install` :)
