### ISSUE TITLE
pod install can't satisfy the requirement

### ISSUE THREAD

**Issue by maxLoveCode** [CocoaPods/CocoaPods#5393]
pod --version returns 0.39.0

podfile as following:

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'huiyan' do
platform :ios, "7.0"  
pod 'AFNetworking’,’~>3.1.0’
pod 'SDWebImage’,’~>3.7.5’
pod 'MJRefresh’,’~>3.1.0’
pod 'Masonry’,’~>1.0.0’
pod 'RealReachability’,’~>1.1.3’
pod 'AMapSearch’,’~> 3.3.0’
pod 'AMapLocation’,’~> 1.2.2'
pod 'AMap2DMap’,’~> 3.3.0’
pod 'RongCloudIMKit’,’~> 2.5.0'
pod "Qiniu", "~> 7.0"
end

target 'huiyanTests' do

end

target 'huiyanUITests' do

end

===========================================================================
When I use 'pod install' command it returns 

[!] Unable to satisfy the following requirements:

- `AFNetworking (~> 3.1.0)` required by `Podfile`
- `AFNetworking (= 3.1.0)` required by `Podfile.lock`
- `AFNetworking (~> 2.0)` required by `Qiniu (7.0.0)`

===========================================================================

And the result of 'pod --verbose':
 Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     5154104..d04c68a  master     -> origin/master
  Updating 5154104..d04c68a
  Fast-forward
   Specs/ReactiveKit/2.0.1/ReactiveKit.podspec.json | 26 +++++++++++
   Specs/eeGeo/1.0.579/eeGeo.podspec.json           | 56 ++++++++++++++++++++++++
   2 files changed, 82 insertions(+)
   create mode 100644 Specs/ReactiveKit/2.0.1/ReactiveKit.podspec.json
   create mode 100644 Specs/eeGeo/1.0.579/eeGeo.podspec.json

CocoaPods 1.0.0 is available.
To update use: `gem install cocoapods`
Until we reach version 1.0 the features of CocoaPods can and will change.
We strongly recommend that you use the latest version at all times.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-huiyan`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-huiyanTests`:
  (``)
  Using `ARCHS` setting to build architectures of target `Pods-huiyanUITests`:
  (``)

Finding Podfile changes
  A Qiniu
  - AFNetworking
  - AMap2DMap
  - AMapLocation
  - AMapSearch
  - MJRefresh
  - Masonry
  - RealReachability
  - RongCloudIMKit
  - SDWebImage

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `AFNetworking (~> 3.1.0)` required by `Podfile`
- `AFNetworking (= 3.1.0)` required by `Podfile.lock`
- `AFNetworking (~> 2.0)` required by `Qiniu (7.0.0)`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:411:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:57:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

Can someone help? I want to install 'Qiniu Library version 7.0'. Thank you very much.

**Comment by manuyavuz** [comment]
Hi,

`Qiniu (7.0.0)` seems to require `2.x` versions of AFNetworking, and you are forcing AFNetworking to have `3.1.x` versions via podfile, which naturally causes a conflict. Either you should remove that constraint, or send a PR to Qiniu to make the library work with AFNetworking `3.x` versions.
