### ISSUE TITLE
Could not load NIB in bundle with v1.0.0

### ISSUE THREAD

**Issue by molon** [CocoaPods/CocoaPods#5395]
```
Pod::Spec.new do |s|
s.name         = "XXXCommon"
s.version      = "1.0.0"
s.summary      = "XXXCommon"

s.license      = { :type => 'MIT'}
s.author       = { "molon" => "xxx@qq.com" }

s.platform     = :ios, '7.0'
s.public_header_files = 'Classes/**/*.h'

s.source = {:path=>'.'}
s.homepage = 'http://molon.me'

s.source_files  = 'Classes/**/*.{h,m}'
s.resource = "Classes/**/*.{bundle,xib,plist}"
s.requires_arc  = true
```
I create a private pod as `common` library and always running ok before.

After I installed v1.0.0.
pod tell me that must to provide the `source` key.
Then I wrote `s.source = {:path=>'.'}` in `.podspec`
But unfortunately, when I build and run my project.
It print `Could not load NIB in bundle`.
The `.xib` in the `Common` pod displays in the `Pods.xcodeproj`,But the application compiled cant find it.

Now I downgrade to 0.39.0, every is ok.

Sorry for my poor english...:)

**Comment by segiddins** [comment]
Please share a project that can be used to debug the issue. Thanks!

**Comment by molon** [comment]
@segiddins 
Sorry, I cant reproduce this problem.

I create a new project with same podspec and podfile to test.(Xcode 7.3.1)
Then I found that everything is ok. There are xibs in the application archive(~ /Library/Developer/CoreSimulator/Devices/xxxxx).

But the project which is created with old Xcode version(maybe 6 or 5) still has the problem.
After buildding, there are no xibs(which in xxxcommon pod) in the application archive.
The project is private, I cant share it.

Fortunately，I will no longer maintain old project.  
So maybe we can ignore this issue. :)
