### ISSUE TITLE
Copy Pods Resource script now uses the --minimum-deployment-target flag with ibtool, causing failed builds in 1.0.0

### ISSUE THREAD

**Issue by rayray** [CocoaPods/CocoaPods#5397]
🌈
# Report
## What did you do?
- I upgraded from 0.39 to 1.0.0 (final)
- ran `pod install`
## What did you expected to happen?

My project to build as usual.
## What happened instead?

"`UIVisualEffectView` used before iOS 8" error generated by a .xib in a library, causing the build to fail.  **The project built fine with Cocoapods 0.39.**

The .xib uses `UIVisualEffectView`, but is not referenced by our code, and this .xib was previously ignored during the build/compile process after having run `pod install` via Cocoapods 0.39.
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.6.0
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : [redacted] - git@[redacted] @ [redacted]
               master - https://github.com/CocoaPods/Specs.git @ 89b7a820228c03442ab368da182b8c663a64cd04
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Project

Issue is with a private library that contains a xib.  The .xib is referenced in the `podspec` as:

```
ss.resources = Helpers.res '*HUD*.{png,xib}', 'MSD*Activity*.png', '*SharingResources/*.xib'
```

Once again, the lib version did not change between usage of CP 0.39 and CP 1.0.0.

**Comment by rayray** [comment]
Well, I found the culprit.

The diff on the "Copy Pods Resources" script between 0.39 and 1.0.0 reveals this:

![image of diff](http://i.imgur.com/jVrpzQq.png)

The flag `--minimum-deployment-target` was added to the `ibtool` command.  Not sure whether the end result is good, since in my case it prevents me from using the library I was using before!

Anyone have input on why this flag was added?

**Comment by rayray** [comment]
Commit here, couldn't find the reasoning: https://github.com/CocoaPods/CocoaPods/commit/c9846d3aff40496d0e1dc601903cbb47b9fa1345#diff-81a515a6548afa6bb211544200a709ed

**Comment by segiddins** [comment]
@rayray I don't think it should be undone -- really, the right way around this is to use frameworks or resource bundles, since those get compiled outside of the copy resource script

**Comment by rayray** [comment]
Would using a resource bundle avoid an `ibtool` compile-time check for .xibs that aren't explicitly referenced?

**Comment by segiddins** [comment]
It would just use the pod's deployment target, rather than the app's

**Comment by rayray** [comment]
Hmm, so the library would still have to drop iOS 7 support in this instance. 😩

**Comment by neonichu** [comment]
BTW, apparently `ibtool` generates an empty nib when not providing this option, see  #4913 — so reverting this would lead to problems being deferred to runtime

**Comment by yyjim** [comment]
I found out that adding `--minimum-deployment-target` option will have an issue on xib file that using the Size Classes.
It can't generate nib file at all.

I'll need to add suffix `~iphone` and `~ipad` to the output file.
eg. ```
ibtool --errors --warnings --notices --minimum-deployment-target 7.0 --compile ${OUTPUT_PATH}/MyView~iphone.nib 
${INPUT_PATH}/MyView.xib --sdk ${SDKROOT}"
```

**Comment by neonichu** [comment]
Apparently, multiple output files is how size classes work when compiled down to iOS 7, at least for Storyboards (see <http://stackoverflow.com/a/25795533>). I believe the option has been found by looking  at the behaviour of Xcode when compiling Storyboars/XIBs.
