### ISSUE TITLE
Stuck on "Setting up CocoaPods master repo"

### ISSUE THREAD

**Issue by aemgtz** [CocoaPods/CocoaPods#5398]
cmd: pod install --verbose
Cloning spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master
  Cloning into 'master'...

I have been waiting for an hour. Nothing happen

**Comment by neonichu** [comment]
Hard to say what is happening there, you can use `GIT_CURL_VERBOSE` to potentially find out.

**Comment by aemgtz** [comment]
Finally, It's done
Because, I did the fresh install so, I will take long time at first.
PS. Please make sure that the internet connection is stable.
