### ISSUE TITLE
pod 'wax', :git ,:tag from github failed

### ISSUE THREAD

**Issue by zrhdev** [CocoaPods/CocoaPods#5403]
# Report

## What did you do?

pod 'wax', :git => 'https://github.com/alibaba/wax.git', :tag => '1.1.0'

## What did you expected to happen?

Install all pod successfully.

## What happened instead?

Pre-downloading: `wax` from `https://github.com/alibaba/wax.git`, tag `1.1.0`
[!] The `wax` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `source`.

It did successfully in CocoaPods 0.39.0.

the case from https://guides.cocoapods.org/using/the-podfile.html can't do successfully too.
To use a tag of the repo:
pod 'AFNetworking', :git => 'https://github.com/gowalla/AFNetworking.git', :tag => '0.7.0'

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : cms - http://gitlab.365eche.com/Frame/CMSpecs.git @ 7906b0bf8dea0ee498dff7e3d6db67eb1cbe938a
               master - https://github.com/CocoaPods/Specs.git @ 641c7387876151b01a6d186a98afd5556ad7124a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by neonichu** [comment]
Your podspec <https://github.com/alibaba/wax/blob/master/wax.podspec> is missing the required `source` attribute. This is why it is being rejected.
