### ISSUE TITLE
Unable to test and use custom framework, which uses CocoaPods.

### ISSUE THREAD

**Issue by bensarz** [CocoaPods/CocoaPods#5405]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have an app which uses a custom framework (not embedded).
This custom framework uses pods.
You can clone and test the project:
https://github.com/berzerker-io/ledger-ios

Running the tests for LedgerKit fails:
```
2016-05-25 10:29:53.470 xctest[43703:1383865] The bundle “LedgerKitTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-05-25 10:29:53.471 xctest[43703:1383865] (dlopen_preflight(/Users/berzerker/Library/Developer/Xcode/DerivedData/Ledger-blncfyiblynwpjcvdbixvxderddd/Build/Products/Debug-iphonesimulator/LedgerKitTests.xctest/LedgerKitTests): Library not loaded: @rpath/SwiftyBeaver.framework/SwiftyBeaver
  Referenced from: /Users/berzerker/Library/Developer/Xcode/DerivedData/Ledger-blncfyiblynwpjcvdbixvxderddd/Build/Products/Debug-iphonesimulator/LedgerKit.framework/LedgerKit
  Reason: image not found)
Program ended with exit code: 82
```

Running the app also fails:
```
dyld: Library not loaded: @rpath/SwiftyBeaver.framework/SwiftyBeaver
  Referenced from: /Users/berzerker/Library/Developer/Xcode/DerivedData/Ledger-blncfyiblynwpjcvdbixvxderddd/Build/Products/Release-iphonesimulator/LedgerKit.framework/LedgerKit
  Reason: image not found
(lldb) 
```

I have cleaned my `DerivedData` folder multiple times. I have also tried adding "Copy Files" phases to both targets in some fashion. Either I'm missing something or this is not possible?

## What did you expected to happen?

I expected to be able to use pods from my custom framework, test it, and use it in my app.

## What happened instead?

See above error messages.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/berzerker/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 545261cbc6c747c0ac1703d281cd202fd998ffa2
```

### Installation Source

```
Executable Path: /Users/berzerker/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
#
#  Podfile
#  Ledger
#
#  Created by Benoit Sarrazin on May 1, 2016.
#  Copyright (c) 2016 Berzerker IO. All rights reserved.
#

platform :ios, '9.0'

target 'Ledger' do
  use_frameworks!

  target 'LedgerTests' do
    inherit! :search_paths
  end

end

target 'LedgerKit' do
  use_frameworks!
  pod 'SwiftyBeaver'

  target 'LedgerKitTests' do
    inherit! :search_paths
  end

end
```

## Project that demonstrates the issue

https://github.com/berzerker-io/ledger-ios

**Comment by bensarz** [comment]
The produced framework ends up in the build products folder, under its own folder.
Copying (or moving) the missing framework from its own folder, into the parent folder (the build products folder) fixes the problem and I am able to run the tests.

![pasted_image_2016-05-25__11_38_am](https://cloud.githubusercontent.com/assets/1077441/15546283/51805db8-226d-11e6-9ef4-a05b58155800.png)

Is this a known issue? Is there a workaround? or am I missing some settings somewhere?

**Comment by segiddins** [comment]
Is `LedgerKit` a framework target?

**Comment by bensarz** [comment]
@segiddins yes, it is, _not_ embedded into Ledger app target

**Comment by segiddins** [comment]
We do not yet support integrating into framework targets -- we reccomend making that framework into a pod.

**Comment by bensarz** [comment]
@segiddins is it considered? or planned?

**Comment by segiddins** [comment]
Yes, there are several open issues about it. It's something we'll support as soon as we get better support for extensions (just embedded targets in general).

**Comment by priyankamistry09** [comment]
I am facing the same issue, any solution for this?

**Comment by mapedd** [comment]
Hey all, is it possible to create App target with certain pods, then the App links to some custom frameworks which also have unique pods linked to them? I guess that the issue we are talking about here. I'm having situation like this, I ended up linking all pods to all targets but the effect is even smallest framework is 5MB
