### ISSUE TITLE
subspecs not imported via cocoapods 1.0

### ISSUE THREAD

**Issue by jonasman** [CocoaPods/CocoaPods#5406]
# Report

## What did you do?
Adding a pod with subspecs does not work

Podfile:
```ruby
use_frameworks!

target 'Portfolio' do
pod 'PromiseKit', '~> 3.0'
pod "PromiseKit/StoreKit"
end
```

## What did you expected to happen?

The subspec "StoreKit" to be available

## What happened instead?

Subspec "StoreKit" is not available

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b21ea9a93cc6c58a7411ead64b0bd404480a4526
               popcorntimetv - https://github.com/PopcornTimeTV/Specs.git @ d565104d79a42b7e7be40cf91eb268286d5e8d95
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Portfolio' do
pod 'ObjectMapper', '~> 1.3'
pod 'PromiseKit', '~> 3.0'
pod "PromiseKit/StoreKit"
end

target 'StockPortfolioTests' do

end

target 'StockPortfolioUITests' do

end
```

## Project that demonstrates the issue
No project but the issue is explained here too:
https://github.com/mxcl/PromiseKit/issues/427

**Comment by neonichu** [comment]
Can't see any issues when integrating into a new project using the given Podfile. Do you have some older build artifacts lying around by any chance? Please try deleting DerivedData.

**Comment by jonasman** [comment]
Integration works fine. 

Pod install does not fail

The issue is that the extension from the subspec is not available.

**Comment by neonichu** [comment]
Unsure what you mean by "available", the files from the subspec are added correctly to the Pods project for me when integrating into a new project.

**Comment by jonasman** [comment]
Right.
Now try to use in your code those methods from the extension.
You will notice that there are not available. (As if the extention is not there)

**Comment by neonichu** [comment]
I'm sorry, but I can't reproduce that, either. 

Would encourage you to try in a fresh project, maybe that helps to determine what condition might lead to that and you can share this here once you know how to reproduce.

**Comment by jonasman** [comment]
You are right! WTF. it works when i create a clean project! Sorry about that.
