### ISSUE TITLE
CocoaPod metrics not updated today?

### ISSUE THREAD

**Issue by salqadri** [CocoaPods/CocoaPods#5407]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Invoked https://metrics.cocoapods.org/api/v1/pods/Firebase.json

## What did you expected to happen?
Expected to see updated stats for today

## What happened instead?
It showed me the exact same stats today as it did yesterday, except for the updated_at field which changed (to "2016-05-25 09:03:31 UTC"). This is the first time this has happened in the one week I've been monitoring the stats (in particular the app_total field).

## CocoaPods Environment
N/A

## Project that demonstrates the issue
https://metrics.cocoapods.org/api/v1/pods/Firebase.json

**Comment by orta** [comment]
This isn't a problem with CocoaPods the dependency manager, so I've moved it to stats.cocoapods.org
