### ISSUE TITLE
CocoaPods 1.0.0 Umbrella Header Regression for Development Pods

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#5409]
- [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Upgrade to CocoaPods 1.0, run pod install, and then try to compile parent project.
## What did you expected to happen?

Compile like it did on 0.39.
## What happened instead?

The umbrella header in 0.39 looks like this:

``` objc
#import <UIKit/UIKit.h>

#import "NSData+OTRDATA.h"
#import "OTRDataGetOperation.h"
#import "OTRDataHandler.h"
#import "OTRDataIncomingTransfer.h"
#import "OTRDataOutgoingTransfer.h"
#import "OTRDataRequest.h"
#import "OTRDataTransfer.h"
#import "OTRHTTPMessage.h"
#import "OTRKit.h"
#import "OTRTLV.h"
#import "OTRTLVHandler.h"

FOUNDATION_EXPORT double OTRKitVersionNumber;
FOUNDATION_EXPORT const unsigned char OTRKitVersionString[];
```

In 1.0.0 it looks like this:

``` objc
#ifdef __OBJC__
#import <UIKit/UIKit.h>
#endif

#import "../../OTRKit/OTRData/NSData+OTRDATA.h"
#import "../../OTRKit/OTRData/OTRDataGetOperation.h"
#import "../../OTRKit/OTRData/OTRDataHandler.h"
#import "../../OTRKit/OTRData/OTRDataIncomingTransfer.h"
#import "../../OTRKit/OTRData/OTRDataOutgoingTransfer.h"
#import "../../OTRKit/OTRData/OTRDataRequest.h"
#import "../../OTRKit/OTRData/OTRDataTransfer.h"
#import "../../OTRKit/OTRData/OTRHTTPMessage.h"
#import "../../OTRKit/OTRKit.h"
#import "../../OTRKit/OTRTLV.h"
#import "../../OTRKit/OTRTLVHandler.h"

#ifdef __OBJC__
FOUNDATION_EXPORT double OTRKitVersionNumber;
FOUNDATION_EXPORT const unsigned char OTRKitVersionString[];
#endif
```

The relative paths make the compiler complain about non-modular includes, and when I manually change them back to look like the previous example, it can't find the headers, indicating that the header search paths behavior must have changed between 0.39 and 1.0.

I've had a number of issues with other libraries that I was able to fix, but I can't seem to figure out a workaround for this one.
## CocoaPods Environment

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.2
Ruby lib dir : /Users/chrisbal/.rbenv/versions/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9648a5efa10ff66ab53f7b25e80d3e10d9c54639
```
### Installation Source

```
Executable Path: ./bin/pod
```
### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.0.0
cocoapods_debug        : 0.1.0
```
## Project that demonstrates the issue
- https://github.com/chatsecure/otrkit
- OTRKit is included as a development pod in https://github.com/chatsecure/otrkit

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/blob/e5afc825eeafa60933a1299f52eb764c267cc9b2/lib/cocoapods/installer/target_installer/pod_target_installer.rb#L29 is probably the relevant source

**Comment by neonichu** [comment]
This is probably because of the `header_mappings_dir` changes.

**Comment by chrisballinger** [comment]
I'm thinking the only workaround would be to use `preserve_paths` and an xcconfig HEADER_SEARCH_PATHS addition. The stuff inside header mappings are private headers for inside the framework.

The main drawback is that I need to use PODS_ROOT twice to support both regular pod installation and when used as a development pod, which is brittle because it's based on your relative path. For example:

https://github.com/chrisballinger/OLMKit/blob/olmkit/olm.podspec#L97

**Comment by jafara** [comment]
Similar (or same?) issue here. 1.0.0 fails with Protobuf.podspec (https://github.com/CocoaPods/Specs/tree/master/Specs/Protobuf/3.0.0-beta-3) because it has top level headers and 2 subdirectory headers.

The pod fails to build as a framework because "google/protobuf/SomeHeader.h" cannot be found. Only when the HEADER_SEARCH_PATHS are updated to include this path then the library can be built as a framework.

**Comment by jafara** [comment]
```ruby
source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'

use_frameworks!

target 'SampleApp' do
  pod 'Protobuf', '3.0.0-alpha-4.1'
end
```

Protobuf can be compiled in with 0.39.0 but fails with 1.0.0.

**Comment by neonichu** [comment]
@chrisballinger yah, we have an issue about that already in #5375, that would offer a proper solution for setting `HEADER_SEARCH_PATHS` regardless of integration type.

**Comment by chrisballinger** [comment]
@neonichu Oh awesome! I'll keep an eye on that.
