### ISSUE TITLE
pod trunk me  Errno::EACCES - Permission denied - /Users/niupark/.netrc

### ISSUE THREAD

**Issue by gb-6k-house** [CocoaPods/CocoaPods#5411]
niuparkdeMac-mini-2:ruby niupark$ pod trunk me

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/niupark/Software/ruby/bin/pod trunk me
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ eeef2b1c6d4ca333e88ce5cadf286cd2e07d7f81
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
Errno::EACCES - Permission denied - /Users/niupark/.netrc
/Library/Ruby/Gems/2.0.0/gems/netrc-0.7.8/lib/netrc.rb:49:in `read'
/Library/Ruby/Gems/2.0.0/gems/netrc-0.7.8/lib/netrc.rb:49:in `read'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:90:in `netrc'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk.rb:95:in `token'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/me.rb:18:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/niupark/Software/ruby/bin/pod:23:in `load'
/Users/niupark/Software/ruby/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+-+%2FUsers%2Fniupark%2F.netrc&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by neonichu** [comment]
CP tries to read `/Users/niupark/.netrc` here and you don't seem to have read permissions for it. Correcting that should fix the issue.

**Comment by segiddins** [comment]
@neonichu we should be raising a more helpful error here

**Comment by gb-6k-house** [comment]
@

**Comment by gb-6k-house** [comment]
i have "chmod 666" for "/Users/niupark/.netrc",but it don't  work.

**Comment by gb-6k-house** [comment]
i have fix this problem. there are the steps:
1. "chmod 660 ~/.netrc " ，then you will get aothor problem like"~/netrc should be 0600 but are 666". then next;
2.modify the check permission ruby code . find  'netrc.rb' file。in file there is a function 'check_permissions', you can delete it.
