### ISSUE TITLE
Playground issue with frameworks when using CocoaPods

### ISSUE THREAD

**Issue by squarefrog** [CocoaPods/CocoaPods#5412]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Unable to call framework methods in Playgrounds after using CocoaPods.

## What did you do?

1. Create a new Cocoa Touch framework project
2. Create a simple struct, and func, e.g `public func sayHi() -> String { return "Hi" }`
3. `pod init`
4. Add any dependency to the `Podfile`
5. `pod install`
6. Clean build the framework
7. Create a playground file, add it to the workspace and import the framework
8. Call the previously created function in the playground: `let hi = Foo.sayHi()`

## What did you expected to happen?

The playground should output "Hi".

## What happened instead?

Playground presents an error.

```
Playground execution failed: error: Couldn't lookup symbols:
  __TFV3Foo3FooCfT_S0_
  __TMV3Foo3Foo
```

Removing the framework import and code from the playground, and then calling whatever dependency you injected works fine. It's only the framework target itself that causes the issue.

After observing this behaviour, run `pod deintegrate`, and remove the `Pods` project reference from the workspace. Clean, build and open the playground. *Note*: the playground works as expected by printing `"Hi"`.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/pi/.rvm/rubies/ruby-2.2.1/lib
Repositories : arcam - xx@xx.xx.xx.xx/repositories/iOSPodRepo.git @ 1b56e5a6590ffb8e6b56bb0b337ec81284457e00
               artsy - https://github.com/artsy/Specs.git @ ef8ffbf6d794b7853a662bdc067036382380d45b
               master - https://github.com/CocoaPods/Specs.git @ 55349007aa3065fe859bf90c5ec905f58d496bdc
```

### Installation Source

```
Executable Path: /Users/pi/.gem/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-keys        : 1.6.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
slather               : 2.0.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Foo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya'

  target 'FooTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

https://github.com/squarefrog/cocoapodsplaygroundissue

Any recommendations for a workaround?

**Comment by neonichu** [comment]
Haven't seen that exact error, but it has very likely the same cause as #5334 — would recommend using <https://github.com/neonichu/ThisCouldBeUsButYouPlaying> for now.

**Comment by squarefrog** [comment]
Cheers @neonichu `cocoapods-playgrounds` will do for now, and I'll keep an eye on #5334 !
