### ISSUE TITLE
About to give up

### ISSUE THREAD

**Issue by bigbadboz** [CocoaPods/CocoaPods#5415]
## What did you do?
Had this problem before, thought my Ruby was broken so reinstalled OS X El Capitan. 
Then, ran `pod install`

## What did you expected to happen?
It installs the dependencies

## What happened instead?
It says there is a 'TypeError' for each dependency -- can't convert ruby values to CFTypeRef.

Incomplete log:
TypeError - Unable to convert Ruby value `"JSQSystemSoundPlayer"' into a CFTypeRef.
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:383:in `RubyValueToCFTypeRef'
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'

goes on.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.2.0
Ruby lib dir : /usr/local/Cellar/ruby/2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c96c715c42a19c8a60013539cbc1f1f3f9b7b27f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!
target 'ChatChat' do
    pod 'Firebase'
    pod 'JSQMessagesViewController'
end
```

## Project that demonstrates the issue

[ChatChat-starter3.zip](https://github.com/CocoaPods/CocoaPods/files/285154/ChatChat-starter3.zip)

**Comment by orta** [comment]
A search for `TypeError - Unable to convert Ruby value ""' into a CFTypeRef` gave these results in issues:

https://github.com/CocoaPods/CocoaPods/issues/5270
https://github.com/CocoaPods/CocoaPods/issues/5200
https://github.com/CocoaPods/CocoaPods/issues/5037

Have you read and understood them?

**Comment by orta** [comment]
Looks like a Ruby bug: https://github.com/CocoaPods/CocoaPods/issues/5270#issuecomment-217751400

**Comment by mjholgate** [comment]
Hi there, the documentation still recommends using the built in OS X ruby (https://guides.cocoapods.org/using/getting-started.html). Is there a plan to work around this bug in Cocoapods, or should the documentation be updated? Many thanks!

**Comment by orta** [comment]
You need to be using a different version of ruby that the 2.0 release that is shipped with the OS to encounter this, e.g. `Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]`

Is this reproducible with the system ruby that is shipped with the OS?

**Comment by mjholgate** [comment]
Sorry for the slow reply here - just to confirm, I've tested with the OS version of Ruby and it works fine! Apologies for my misunderstanding!

**Comment by kennebecstars** [comment]
This is the current fix:

$ rvm reinstall ruby-2.2.2
$ rvm --default use ruby-2.2.2
$ gem install cocoapods
$ pod install
