### ISSUE TITLE
[!] The dependency `GoogleMaps` is not used in any concrete target.

### ISSUE THREAD

**Issue by yanioro** [CocoaPods/CocoaPods#5422]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expected to happen?

I expected to install google map sdk in my xcode project

## What happened instead?

I got;
 "The dependency `GoogleMaps` is not used in any concrete target."

## CocoaPods Environment

LearniOSFreecoms-Mac:GoogleMap yan$ pod env

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8125f1d973994d27d5fefffc6fe75c67b80b86cd
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
```

LearniOSFreecoms-Mac:GoogleMap yan$

**Comment by neonichu** [comment]
You can have implicit targets anymore in CocoaPods 1.0, please check the guides: <https://guides.cocoapods.org/syntax/podfile.html>

**Comment by Tanvir-Nayem** [comment]
**"[!] The dependency `GoogleMaps` is not used in any concrete target"**
i recently updated to OSX 10.11 EL capitan...my cocoapods version is 1.0.0.0 
I am facing this problem not only with GoogleMaps but also with all other sdk to intigrate with mt project.
I have stuck here. Plz help me with this problem. TIA..

**Comment by neonichu** [comment]
See above, the guides should tell you how to use explicit targets. Another way is to just run `pod init` to let CocoaPods create a Podfile for you.

**Comment by Tanvir-Nayem** [comment]
I have found the sollution..
1.first create a project
2.Then go to your project folder
3.Then open the terminal and go to your project directory using ( cd /your/project/directory )
4.then type "pod init" command
5.now type "open -a xcode podfile" command
6. add these two lines
           source 'https://github.com/CocoaPods/Specs.git'
           pod 'GoogleMaps'
after ==> ( target 'your project name' do ) this line in your podfile
7.save your podfile and 
8.type command " pod install " voala..
happy coding

**Comment by A1catraz** [comment]
Thanks Tanvir-Nayem. I have followed the the steps you've written (with minor change) and it worked perfectly.
`source 'https://github.com/CocoaPods/Specs.git'
pod 'GoogleMaps'
target 'your project name'`

**Comment by Vasil920** [comment]
Thanks A1catraz .
It was very helpful for me.

**Comment by thistle1990** [comment]
Thanks Tanvir!! Very helpful, save me from the endless environment setting!

**Comment by Tamanna09** [comment]
![podfile_and_news24_ _-bash_ _79x19_and_assets_xcassets](https://cloud.githubusercontent.com/assets/23517027/20379876/be8a937a-acc8-11e6-84bc-6304f6deba36.png)

**Comment by Tamanna09** [comment]
Please anyone help me. I can't add any pod installation in xcode.

![news24_ _-bash_ _79x19_and_podfile_and_assets_xcassets](https://cloud.githubusercontent.com/assets/23517027/20379967/3fc2c200-acc9-11e6-87b7-855bc781fd92.png)

**Comment by A1catraz** [comment]
Tamanna09, you dont have this line (source 'https://github.com/CocoaPods/Specs.git') in your podfile. Make sure you have and try again.
PS: I don't think this line (platform :ios, '10.1') is needed either

**Comment by Tamanna09** [comment]
Thanks A1catraz,  tried by this line, but no luck....Finally, i remove my pod and setup it again. Now, this problem has solved. But my project can't find these.

**Comment by A1catraz** [comment]
I haven't used Facebook SDK on my project, so, I don't know this will work or not for you, but take a look at this problem and its accepted solution: [http://stackoverflow.com/questions/30117253/facebook-ios-sdk-v-4-1-0-in-swift-with-cocoapods-cannot-import-modules]

And also try to add `'FBSDKCoreKit'` to pod and install.

**Comment by Tanvir-Nayem** [comment]
Hi tamanna09. First of all, you have to download and extract your "fbsdk"  zip file to your document directory. then add below lines to your podfile.

    platform :ios, '9.0'

    target 'your-project-name' do
    pod 'FBSDKLoginKit'
    end

then save the file and after that install your podfile.
