### ISSUE TITLE
Error Installing Podfile Libraries

### ISSUE THREAD

**Issue by Stephanehk** [CocoaPods/CocoaPods#5423]
# Report

## What did you do?

After adding a podfile to the pod nano file, I ran pod install.

## What did you expected to happen?

I expected the podfile to be downloaded.

## What happened instead?

Instead I got an error.

## CocoaPods Environment

The error read "Installing SCLAlertView (0.5.8)

[!] Error installing SCLAlertView
[!] /usr/local/bin/git clone https://github.com/vikmeup/SCLAlertView-Swift.git /var/folders/1c/k1hjjv7j0559mz8t6x7dk5bc5k8626/T/d20160528-80617-1w7qaxw --template= --single-branch --depth 1 --branch 0.5.8

Cloning into '/var/folders/1c/k1hjjv7j0559mz8t6x7dk5bc5k8626/T/d20160528-80617-1w7qaxw'..."

**Comment by segiddins** [comment]
Does cloning manually work?

**Comment by Stephanehk** [comment]
Dear segiddins

I am very new to using ruby/terminal so this may sound like a stupid question, but what does cloning manually mean and how do you do it? Thanks.

**Comment by segiddins** [comment]
Can you run that git command that's failing in the terminal? Chances are it fails outside CocoaPods as eell

**Comment by Stephanehk** [comment]
I just tried that but it did not work.

**Comment by orta** [comment]
This command works for me, you're going to have to give us more information, e.g. the logs. It's likely a local setup issue.

```
/t/SimplePDF (develop) ⏛  git clone https://github.com/vikmeup/SCLAlertView-Swift.git --template= --single-branch --depth 1 --branch 0.5.8
Cloning into 'SCLAlertView-Swift'...
remote: Counting objects: 151, done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 151 (delta 32), reused 123 (delta 22), pack-reused 0
Receiving objects: 100% (151/151), 1.20 MiB | 0 bytes/s, done.
Resolving deltas: 100% (32/32), done.
Checking connectivity... done.
Note: checking out '68fafd2befd4e28fbc2e1dc8c39c67cbf8d86988'.
```

**Comment by Stephanehk** [comment]
Dear Orta and Segiddins

What exactly is the specific command you ran. I may have typed in the wrong one. Thanks.

**Comment by Stephanehk** [comment]
Dear Dear Orta and Segiddins

I ran the git command that was failing and this is the output that I was given:

`remote: Counting objects: 151, done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 151 (delta 32), reused 123 (delta 22), pack-reused 0
Receiving objects: 100% (151/151), 1.20 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (32/32), done.
Checking connectivity... done.
Segmentation fault: 11
`

**Comment by segiddins** [comment]
Seems like an issue in git, in that case

**Comment by orta** [comment]
Try re-installing git, somehow you've corrupted your version.

**Comment by Stephanehk** [comment]
I tried re-installing git, but that also did not work. The error still persists.

**Comment by orta** [comment]
Then I think it's worth trying to figure that problem out on your own, there seems to be quite a few results on google for [git segfault 11](https://encrypted.google.com/search?hl=en&q=git%20Segmentation%20fault%3A%2011) - I'd recommend you start there, and I'm going to close this issue as I don't think this a CocoaPods bug.
