### ISSUE TITLE
Resources fail to install when the path specifies a directory with a name ending in '.xcassets'

### ISSUE THREAD

**Issue by ranunez** [CocoaPods/CocoaPods#5424]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?
- Specified `resources` for a podspec with a path that contained a `.` in a directory name 
  - example: `s.resources = 'Test/Assets/Images.xcassets/**/*'`
- Ran `pod install` to install this pod
## What did you expected to happen?

Copy resources correctly for that pod
## What happened instead?

Resources failed to install correctly if a directory in that path ended in a '.xcassets'.
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/rnunez/.rvm/rubies/ruby-2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 196c9b3bf94d4932e160c3ade902adf693f7e1d1
```
### Installation Source

```
Executable Path: /Users/rnunez/.rvm/gems/ruby-2.2.2/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
## Project that demonstrates the issue

https://github.com/ranunez/cocoapods-bug-test

**Comment by neonichu** [comment]
Did you see this warning:

> …/cocoapods-bug-test/Example/Test/Images.xcassets: The image set "coffee" references a file "coffee.JPG", but that file does not have a valid extension.

**Comment by ranunez** [comment]
Yes, I had a duplicate image referenced from the project's xcassets, I have now removed all build warnings from the project.

**Comment by ranunez** [comment]
This bug is still reproducible in Cocoapods 1.0.1

**Comment by DanToml** [comment]
@ranunez It appears that your example project has been removed, please could you confirm that this is still an issue?
