### ISSUE TITLE
Use of Private header from outside its model: when answering yes to view based testing

### ISSUE THREAD

**Issue by miller-ms** [CocoaPods/CocoaPods#5425]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Created a new library: "pod lib create testswift"
2. Answered questions as follows
  -    What language do you want to use??  **Swift**
  -    Would you like to include a demo application with your library? **Yes**
  -    Which testing frameworks will you use? **None**
  -    Would you like to do view based testing? **Yes**
3. The workspace opens in xcode when pod lib create completes
4. Build the pods project with no changes to any files in the workspace.

## What did you expected to happen?

Expected the build to succeed

## What happened instead?

Build failed with following errors:

-UIImage+Diff.m
  - Use of Private header from outside its model: 'FBSnapshotTestCase/UIIMage+Diff.h'

-UIImage+Compare.m
  - Use of Private header from outside its model: 'FBSnapshotTestCase/UIIMage+Compare.h'

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7577aba2c440a026ec7b13f3b4a3255ffef39b08
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
## Project that demonstrates the issue

This is repeatable by anyone by following the following steps:

1. execute "pod lib create <somelibrary>" and answer questions as follows:
  -    What language do you want to use??  **Swift**
  -    Would you like to include a demo application with your library? **Yes**
  -    Which testing frameworks will you use? **None**
  -    Would you like to do view based testing? **Yes**

2. Build the library immediately after the workspace opens

**Comment by orta** [comment]
Thanks for the issue @miller-ms - this looks like a bug with the Facebook Snapshots pod, which they have raised here: https://github.com/facebook/ios-snapshot-test-case/issues/162

Hopefully this should get resolved soon, but it's not worth us keeping around an extra issue for that.
