### ISSUE TITLE
C++ header file not found 

### ISSUE THREAD

**Issue by jiangyancong** [CocoaPods/CocoaPods#5428]
# Report

## What did you do?
I  create a podSpec for AliPay SDK.
```
Pod::Spec.new do |s|
  s.name         = "AliSDKPod"
  s.version      = "0.3"
  s.summary      = "AliSDKPod"
  s.description  = "AliSDKPodAliSDKPodAliSDKPod"
  s.homepage     = "https://github.com/jianyancong/AliSDKPod"
  s.license      = "MIT"
  s.author  = { "StanleyJiang" => "jiangyancong@gmail.com" }
  s.platform     = :ios, "7.1"
  s.source = {:git => "https://github.com/jiangyancong/AliSDKPod.git"}
  s.framework = "Security","SystemConfiguration","CoreGraphics","CoreTelephony","CoreMotion","CFNetwork","QuartzCore","CoreText"
  s.libraries = "iconv","sqlite3","stdc++","z","c++"
  s.requires_arc = true
  
 s.source_files = 'AlixPay/2016_04_28/**/*.{h,m}'
  s.header_mappings_dir = 'AlixPay/2016_04_28/'
  s.resource = 'AlixPay/2016_04_28/AlipaySDK.bundle'
  s.vendored_libraries = "AlixPay/2016_04_28/libcrypto.a","AlixPay/2016_04_28/libssl.a"
  s.vendored_frameworks = "AlixPay/2016_04_28/AliPaySDK.framework"
end
```
 and run 
```
pod trunk push AliSDKPod.podspec --verbose --allow-warnings
```
## What did you expected to happen?
push to trunk repo successfully

## What happened instead?
```
'openssl/asn1.h' file not found.
```
In AlixPay/2016_04_28/Util/openssl_wrapper.m (Line 11) include "rsa.h", and rsa.h include   
```
<openssl/asn1.h>
```

When I change 
```
include <openssl/asn1.h>
```
to 
```
include "asn1.h"
```
it works. but in openssl header files, there're thousands of place in include like that(with **<openssl/***.h>**). Acroding to the guideline of Podspec, I have added header_mappings_dir in Podspec, I doubt that is it because openssl header files are the C++ base, so the header_mappings_dir doesn't work.

Moreover, I have referred to a similar case in https://groups.google.com/forum/#!searchin/cocoapods/include$20C$2B$2B/cocoapods/6V4qL571wgQ/l7znrqa-52AJ
But the solution there also doesn't work in my case.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : jiangyancong - https://github.com/jiangyancong/NingMiPlatform.git @ f21e936ac9c1a1ee9ad642b485c9b79351d708df
               master - https://github.com/CocoaPods/Specs.git @ 8d755033d4425632a59ebe60ffe7ccc2b3c0fe81
               NMTest - https://github.com/qhd/test.git @ 48237c860cb2c08c2bdb3204194ac4c8ee24b607
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue
https://github.com/jiangyancong/AliSDKPod.git

**Comment by neonichu** [comment]
This is basically the same situation as #5409, where you need a subset of your headers to have different paths.

**Comment by luqyluqe** [comment]
How was the problem solved?

**Comment by XiaoZhongKen** [comment]
For those who stuck in Alipay 'openssl/asn1.h' file not found.'  problem,  FYI, Alipay can run independently without openssl thing entirely, signing is better be done on server side.

**Comment by MengYP** [comment]
I have the same problem.  
`
 - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  AliPaySDK/AliPaySDK/openssl/rsa.h:62:10: fatal error: 'openssl/asn1.h' file not found

Analyzed 1 podspec.
`
