### ISSUE TITLE
Library not loaded integrating C-target into Swift framework

### ISSUE THREAD

**Issue by benasher44** [CocoaPods/CocoaPods#5431]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran pod install and tried to run our test suite

## What did you expected to happen?

Framework and test suite builds and runs.

## What happened instead?

Framework and test suite builds, but it fails to launch claiming that the framework cannot be found

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.6.0
Ruby lib dir : /Users/benasher/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9793c9ad7c0ce540e1b3770e5d480c981197a182
```

### Installation Source

```
Executable Path: /Users/benasher/.rvm/gems/ruby-2.2.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'ShapeSwift' do
  pod 'proj4', :podspec => './podspecs/proj4.podspec'
  target 'ShapeSwiftTests' do
    inherit! :search_paths
  end
end
```

## Project that demonstrates the issue

https://github.com/benasher44/Shapeswift
This project is very much a work-in-progress, but it does currently build on the latest Xcode, and the test suite builds as well.

**Comment by benasher44** [comment]
Screenshot of `BUILT_PRODUCTS_DIR`:
![screen shot 2016-05-30 at 1 33 36 pm](https://cloud.githubusercontent.com/assets/1120429/15657966/2cee07e6-266b-11e6-8259-c07ddf2aec9a.png)

The framework that it's having trouble finding is proj4, which, if you notice in the screenshot, is nested one level deep in a folder with that framework's name. Moving proj4.framework up a level onto the same level as all of the other frameworks fixes the issue. I just have to do this manually right now, which is getting tiring :)

**Comment by segiddins** [comment]
`ShapeSwift` is a framework, and CocoaPods does not yet support integrating into framework targets, but your work on extension support should actually end up addressing this

**Comment by benasher44** [comment]
Ah okay. This makes sense. Thanks! I'll just integrate the framework into my test target as a pod.

**Comment by irace** [comment]
@benasher44 @segiddins Any known timetable for this work? I would love love love love love to be able to integrate into a framework target.

**Comment by benasher44** [comment]
@irace I had planned on attempting an app submission with my branch that fixes #4203 2 weeks ago, but a few things didn't align. So, I'm going to attempt this today (we submit every 2 weeks)! If all goes well, I'll be putting together the PR this week.

That said, I'm not sure that my fix for #4203 will cascade into a fix for issues that don't seem to be related to app extensions to me. However, it's possible that in reviewing the PR the solution implementation changes, and my changes will fix this issue as well. In any case, I'll be sure to update relevant threads once the PR is posted.

In the meantime, I was able to get a working development setup that works for framework development (at least in this case). Have a look [here](/benasher44/shapeswift/blob/3354a18284a93ab9cbecbc74114c18ca1741f5da/Podfile).

**Comment by segiddins** [comment]
I think @benasher44 had a mostly working branch?

**Comment by benasher44** [comment]
@segiddins yep! I'd post more encouraging things about using/testing it, but I updated with master last night and am now having issues running tests/getting them to work that I may ask about later today on slack if I can't get it sorted.
