### ISSUE TITLE
sharedApplication' is unavailable: not available on iOS via CocoaPods 1.0

### ISSUE THREAD

**Issue by mcmatan** [CocoaPods/CocoaPods#5434]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Upgraded to Cocoapod v 1.0

## What did you expected to happen?

Application should run as before, with no errors.

## What happened instead?

I get error on the line:

UIWindow *window = [UIApplication sharedApplication].delegate.window;

Error:
sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

## CocoaPods Environment
1.0

**Comment by segiddins** [comment]
This is intended -- you can't use methods like that in an iOS app extension.

**Comment by mcmatan** [comment]
@segiddins Sorry I didn't say before, but I'm using it in:

#if !defined(SHARE_EXTENSION)
  UIWindow *window = [UIApplication sharedApplication].delegate.window;
#endif

**Comment by mcmatan** [comment]
Sorry, by define wasn't correct, thank you for your super quick response @segiddins

**Comment by mcmatan** [comment]
I'ts strange,  after changing scheme this resulved it self.. Thanks for the super quick response @segiddins
