### ISSUE TITLE
1.0 trashes my Xcode project

### ISSUE THREAD

**Issue by jwombat** [CocoaPods/CocoaPods#5435]
On doing a 'pod update' it told me 1.0 was available, so I installed it first, and then did a pod update.

Now it tells me that all of my pods are not used in any concrete project, and apparently has removed them, since Xcode won't compile because it's missing all the header files from the pods.

Is there something that 1.0 is expecting that's new? This project has been in development for months without problem.

Failing that, how do I roll back Cocopods?

**Comment by manuyavuz** [comment]
As you can see in [CocoaPods 1.0 Migration Guide](http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/), 1.0 version has breaking changes, so you should update your podfile following the migration guide.

If you don't want to make this migration now, you can return back to 0.39.0 version using `gem install cocoapods -v 0.39.0` command.
