### ISSUE TITLE
update a private pod dependency and failed

### ISSUE THREAD

**Issue by PangPangPangPangPang** [CocoaPods/CocoaPods#5437]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Run `pod update`

## What did you expected to happen?

ℹ I want to add a private pod dependency

## What happened instead?

As below

## CocoaPods Environment

MaxdeMacBook-Pro:aaaa Max$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `MXDataBasePoolManager` from `http://gitlab/yefeng1/MyTest/blob/master/MXDataBasePoolManager/0.0.1/MXDataBasePoolManager.podspec`

[!] Invalid `MXDataBasePoolManager.podspec` file: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
MXDataBasePoolManager.podspec:2: syntax error, unexpected '<'
<html lang='en'>
 ^
MXDataBasePoolManager.podspec:3: syntax error, unexpected '<'
<head>
 ^
MXDataBasePoolManager.podspec:5: syntax error, unexpected '<'
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
 ^
MXDataBasePoolManager.podspec:5: syntax error, unexpected tIDENTIFIER, expecting end-of-input
<meta content='IE=edge' http-equiv='X-UA-Compatible'>
                            ^.

 #  from MXDataBasePoolManager.podspec:1
 #  -------------------------------------------
 >  <!DOCTYPE html>
 #  <html lang='en'>
 #  -------------------------------------------
## Project that demonstrates the issue

Sorry,it`s a private repo.

**Comment by manuyavuz** [comment]
We can not say anything unless you share the contents of your `.podspec` file.

If you can not share the contents, you will have to find the problem yourself.

You can look into [Podspec Syntax Reference](https://guides.cocoapods.org/syntax/podspec.html) for details.

**Comment by PangPangPangPangPang** [comment]
Sorry,this is the file

Pod::Spec.new do |s|
  s.name         = "MXDataBasePoolManager"
  s.version      = "0.0.1"
  s.summary      = "MXDataBasePoolManager is a wrapper of FMDB"
  s.homepage     = "http://mmmmmax.wang/"
  s.license      = "MIT"
  s.author       = { "Max Wang" => "446964321@qq.com" }
  s.source       = { :git => "http://gitlab/yefeng1/MyTest.git", :tag => "0.0.1" }
  s.source_files = "source/*.{h,m}"
  s.requires_arc = true
  s.platform     = :ios, '6.0'
end

**Comment by manuyavuz** [comment]
I don't get any syntax error with the content you provide above. Are you sure this is exactly the same content with the `.podspec` file inside your private repo?

In the error that you report I see error is caused by the string `<!DOCTYPE html>`, but in the spec that you shared, there is no such string. So, we still can't say what is the cause until we see the erroneous file.

Can you share contents of your Podfile related to the pod?

**Comment by PangPangPangPangPang** [comment]
I copy the path throw the broswer. >.< 

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'aaaa' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for aaaa
  pod 'MXDataBasePoolManager', :podspec => 'http://gitlab/yefeng1/MyTest/blob/master/MXDataBasePoolManager/0.0.1/MXDataBasePoolManager.podspec'

    pod 'JSPatch'

end
