### ISSUE TITLE
Importing a C library via module map into a framework

### ISSUE THREAD

**Issue by iwasrobbed** [CocoaPods/CocoaPods#5442]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod lib lint` or `pod spec lint`

## What did you expected to happen?

Expected CocoaPods to find the `libcmark` module that I declared within a framework (works fine on travis-ci and building normally)

## What happened instead?

`pod lib lint` gives very different error messages from `pod spec lint` 

`pod lib lint` gives: 
>- ERROR | xcodebuild:  /Users/rob/Down/Source/Renderers/DownASTRenderable.swift:10:8: error: no such module ‘libcmark'

`pod spec lint` gives:
>- ERROR | xcodebuild:  Down/Source/cmark/cmark.h:5:10: error: cyclic dependency in module 'Down': Down -> libcmark -> Down
>- ERROR | xcodebuild:  /privateTarget Support Files/Down/Down-umbrella.h:5:9: error: could not build module 'libcmark'
>- NOTE  | xcodebuild:  <unknown>:0: error: could not build Objective-C module 'Down'

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/rob/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 96589532cfc3079b2b079defe2526ae3db98ba58
```

### Installation Source

```
Executable Path: /Users/rob/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

https://github.com/iwasrobbed/Down/tree/cocoapods

## Podspec Definition

```ruby
Pod::Spec.new do |spec|
  spec.name         = "Down"
  spec.summary      = "Blazing fast Markdown rendering in Swift, built upon cmark."
  spec.version      = "0.1"
  spec.homepage     = "https://github.com/iwasrobbed/Down"
  spec.license      = { :type => "MIT", :file => "LICENSE" }
  spec.authors      = { "Rob Phillips" => "rob@desideratalabs.co" }
  spec.source       = { :git => "https://github.com/iwasrobbed/Down.git", :tag => "v" + spec.version.to_s }
  spec.source_files = "Source/**/*"
  spec.platform		= :ios, "9.0"
  spec.requires_arc = true
  spec.module_name = "Down"
  spec.preserve_path = 'Source/cmark/module.modulemap'
  spec.pod_target_xcconfig = { 'HEADER_SEARCH_PATHS' => '$(PODS_ROOT)/Down/module' }
  spec.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(PODS_ROOT)/Down/module', 'SWIFT_INCLUDE_PATHS' => '$(PODS_ROOT)/Down/Source/cmark' }
end
```

## Explored Other Issues

- https://github.com/CocoaPods/CocoaPods/issues/5271
- https://github.com/CocoaPods/CocoaPods/issues/4420
- http://stackoverflow.com/questions/32273050/define-custom-module-map-file-in-cocoapods-podspec

**Comment by neonichu** [comment]
I think the issue is that `pod lib lint` won't work because it uses local Pods, for which the `SWIFT_INCLUDE_PATHS` declaration won't be valid. See #5375 for tracking this issue. I think `pod spec lint` should work fine, though.

**Comment by iwasrobbed** [comment]
@neonichu Thanks for giving it a second pair of eyes. Finally got it working by following [this article](https://medium.com/swift-and-ios-writing/using-a-c-library-inside-a-swift-framework-d041d7b701d9#.jmup5emti)

Changes from a non-CocoaPods project here for others to compare: https://github.com/iwasrobbed/Down/commit/758db9de993333cf4f627128b86156eaf3cdb605

**Comment by iwasrobbed** [comment]
Following up later after I hit this a second time: to the above point, it's best to use `$ pod spec lint` for linting your work prior to doing a `$ pod trunk push`. 

Using `$ pod lib lint` uses local files only and (in this case) breaks the build; but, checking out the remote using `$ pod spec lint` works 👍 

Thanks again @neonichu
