### ISSUE TITLE
inhibit_all_warnings doesn't enhibit warnings for Objective-C code that uses *-Swift.h

### ISSUE THREAD

**Issue by virl** [CocoaPods/CocoaPods#5444]
# Report

inhibit_all_warnings doesn't enhibit warnings for Objective-C code that uses *-Swift.h
When Swift project uses some Objective-C code: pods warnings (deprecated UIAlertView) are not inhibited for Objective-C code, because that code uses auto-generated *-Swift.h headers (which contain references to UIAlertView).

Example pod: Armchair.

Also see #4423

## What did you do?

1. Use in Podfile some Swift pod that produces warning (like Armchair)
2. Add inhibit_all_warnings! directive
3. Run `pod install`
4. In your project, create any Objective-C class.
5. See that deprecated warning in the Pod still persists.

## What did you expected to happen?

Warning is supressed

## What happened instead?

Warning is not supressed.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7e9571384abf832a883c44e9c1faa2eec2ddfac2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

def appPods
pod 'XCGLogger', '3.1.1'
pod 'XCGLoggerNSLoggerConnector', '0.1.1'

pod 'Realm', '1.0.0'
pod 'RealmSwift', '1.0.0'
pod 'SwiftyJSON', '2.3.2'
pod 'FMDB', '2.6.2'
pod 'GCDWebServer/WebDAV', '3.3.2'
pod 'Toast', '3.0'
pod 'MSWeakTimer', '1.1.0'
pod 'SDVersion', '2.5.2'
pod 'SwiftPriorityQueue'

# Analytics
pod 'Armchair'
pod 'Fabric'
pod 'Crashlytics'
pod 'GA-SDK-IOS'
pod 'HockeySDK', '~> 4.0.0'
pod 'Mixpanel'
pod 'Flurry-iOS-SDK/FlurrySDK'
end

target 'MyApp' do
	appPods
end
```

**Comment by neonichu** [comment]
Maybe this is fixed by #5414 as well?

**Comment by virl** [comment]
Don't know, I'm using release version of cocoapods.

**Comment by benasher44** [comment]
@virl can you try with CocoaPods 1.1.1?

**Comment by virl** [comment]
@benasher44 No, I cannot: I moved to Carthage because it is better.

**Comment by benasher44** [comment]
@virl no prob. Thanks for getting back!

**Comment by vburojevic** [comment]
@benasher44 This is still an issue in 1.2.0. Any news on this?

**Comment by jafara** [comment]
@virl Carthage sucks. Its only dynamic frameworks which is bullshit with static libraries.

**Comment by virl** [comment]
@jafara Static libraries are not needed in Swift, because they require excessive compilation on project rebuild.
Also, the CocoaPods who sucks, because it requires from libraries/frameworks authors to create separate non-standard CocoaPods-specific build files (in non-statically typed language unrelated to iOS/macOS!) which are completely unrelated to Xcode build system. CocoaPods design is flawed at its core.

**Comment by orta** [comment]
Alright, I'm locking this thread and deleting the last two posts. Our issues are not a playground for petty squabbling. Please keep to the topics at hand.

**Comment by benasher44** [comment]
@vburojevic if you could, please open a new issue and fill out the issue template. If you could do that and provide some way for us to reproduce the issue, we'd be happy to help. Have a great day!
