### ISSUE TITLE
Upgrade Cocoapods 1.0 after,local pod code not effect when change.

### ISSUE THREAD

**Issue by seasun** [CocoaPods/CocoaPods#5447]
Upgrade Cocoapods 1.0 after.Very unfortunately，build error.
So I try new project, then build success!
but my project is modularization.
example :
![image](https://cloud.githubusercontent.com/assets/1314160/15741661/3ee6aec4-28ed-11e6-80f0-7886876e8c24.png)
when i change the code and build. unfortunately,the code can't to work!
the project still run on old code.

**Comment by segiddins** [comment]
Please fill out the full issue template, including sharing an example project, so we can try and understand what's going on. Thanks!

**Comment by seasun** [comment]
I had solved it. Becourse local pod structure have change,no longer call 'pod'，it's change to target name.
but have other problems.such as podspec item:resource_bundles. default is annotation，if not，after pod install,target can't install to pods;

Another example：some third libraries([MBProgessHUD](https://github.com/CocoaPods/Specs/blob/master/Specs/MBProgressHUD/0.9.2/MBProgressHUD.podspec.json)). The platforms item is null. old version of cocoapods is no problem.but after version 1.0 , it will be ios 4.3.😂;

please close this question.
