### ISSUE TITLE
Double nested header folders

### ISSUE THREAD

**Issue by nevyn** [CocoaPods/CocoaPods#5452]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

<img width="2045" alt="screenshot 2016-06-02 14 08 12" src="https://cloud.githubusercontent.com/assets/34791/15761264/1cad0702-28cc-11e6-8616-3d33bbe3e4c8.png">

The headers are nested into TWO levels of folders called "WebRTC", but I only want one level, and that seems to be the case for other pods such as SocketRocket (`Headers/Public/SocketRocket/SocketRocket.h`).
## What did you do?
- Wrote the podspec seen above
- Cocoapods 1.0.1
- `pod install`
## What did you expected to happen?

All WebRTC headers nestled nicely into `Pods/Headers/Public/WebRTC/*.h`
## What happened instead?

All WebRTC headers nestled un-nicely into `Pods/Headers/Public/WebRTC/WebRTC/*.h`
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11 (15A282b)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f6dd2c921afa7e190062cd25aa98f8b7b5f7f730
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
platform :ios, '8.0'

install! 'cocoapods', :integrate_targets => false

# These deps are here for having headers at build time. They will be pulled in by the subspec "Live" in the
# podspec for the end user.
target 'LookbackLive' do
    # Built from https://github.com/lookback/webrtc/commit/f938490a9309e18fb18161e0bd580ed2e0163e6f
    pod 'WebRTC', :podspec => 'https://lookback-public.s3.amazonaws.com/sdk/webrtc/12816/Release/1/WebRTC.podspec'
    pod 'SocketRocket'
end
```
## Project that demonstrates the issue

https://www.dropbox.com/s/2gqh661gnicj7yw/cptest.zip?dl=0

**Comment by neonichu** [comment]
I think this is just what we do for `vendored_frameworks` in general, not sure about the specifics of why that is. Seems like the generated XCConfig references this correctly, `-isystem "${PODS_ROOT}/Headers/Public/WebRTC"` — do you see build failures because of this?

**Comment by nevyn** [comment]
Thanks for the reply! No, not a build error when integrating automatically, but when I integrate manually and set header include path to `Pods/Headers/Public` (to have a single header search path to find all the pods' headers), it fails. It seems weird to handle vendored framework headers and built-from-source libraries differently in terms of headers. I'd really like to be able to set a single include path, and from how SocketRocket headers are laid out, it seems like CocoaPods wants to enable that too, so from my perspective it seems like a bug that vendored frameworks are handled differently?

**Comment by neonichu** [comment]
I agree that it seems weird, unsure if there were reasons to handle them differently. Maybe @segiddins knows?

**Comment by segiddins** [comment]
Hmmmm..... I can't remember, I'd recommend looking at the blames around that code
