### ISSUE TITLE
Uploading an archive containing Pods causes iTunes Connect warning ITMS-90080

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/CocoaPods#5453]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) 🌈

# Report

## What did you do?

I've uploaded an archive to the App Store for an app which consists of a lot of Pods.
## What did you expected to happen?

App Store should not report any issues.

## What happened instead?

For each Pod, the App Store returned a warning like this:

> WARNING ITMS-90080: "The executable 'Payload/Redacted.app/Frameworks/AFNetworking.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to [Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library](https://developer.apple.com/library/ios/qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)."

There is no such warning for the app's own binary.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1012)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7f57654d3d2d85fcdae434750f3f87b45e10fb3c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
workspace 'Redacted'
project 'App'
platform :ios, '8.2'

install! 'cocoapods', :deterministic_uuids => false, :share_schemes_for_development_pods => false
use_frameworks!

target 'App Store'
target 'Beta'
target 'Development'
target 'Testing'

# libraries
pod 'AFNetworking',         '2.6.3'
pod 'Analytics',            '3.1.0'
pod 'AppsFlyerFramework',   '4.4.1'
pod 'FBSDKCoreKit',         '4.11.0'
pod 'FBSDKLoginKit',        '4.11.0'
pod 'FBSDKShareKit',        '4.11.0'
pod 'GoogleAnalytics',      :podspec => 'Modules/Managers/Tracking/Support/GoogleAnalytics.podspec.json'
pod 'GPUImage',             '0.1.7'
pod 'HockeySDK-Source',     '3.8.6', :inhibit_warnings => true
pod 'Mixpanel',             '2.9.9'
pod 'Parse',                :git => 'https://github.com/Widgetlabs/Parse-SDK-iOS-OSX.git', :branch => 'fix-issue-817'
pod 'Stripe',               '7.0.1'
pod 'twitter-text',         '1.13.4'
pod 'uservoice-iphone-sdk', '3.2.7', :inhibit_warnings => true

# <many more development pods>

pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	def installer.verify_no_static_framework_transitive_dependencies; end
end


post_install do |installer|
	project = installer.pods_project
	project.build_configuration_list.build_settings('Debug')['OTHER_SWIFT_FLAGS']          = '$(inherited) -DDEBUG'
	project.build_configuration_list.build_settings('Release')['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'

	installer.aggregate_targets.each do |target|
		project.build_configurations.each do |build_configuration|
			configFilePath = target.xcconfig_path(build_configuration.name)
			configFile = File.read(configFilePath)
			configFile = configFile.gsub(/-framework "AppsFlyer" /, '')
			configFile = configFile.gsub(/-framework "GoogleAnalytics" /, '')
			File.open(configFilePath, "w") { |file| file << configFile }
		end
	end
end
```

**Comment by neonichu** [comment]
Interesting, according to the instructions for verifying, the built framework is indeed not PIE:

```bash
$ otool -hv build/Release-iphoneos/AFNetworking/AFNetworking.framework/AFNetworking
build/Release-iphoneos/AFNetworking/AFNetworking.framework/AFNetworking (architecture armv7):
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
   MH_MAGIC     ARM         V7  0x00       DYLIB    26       3276   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
build/Release-iphoneos/AFNetworking/AFNetworking.framework/AFNetworking (architecture arm64):
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   ARM64        ALL  0x00       DYLIB    26       3792   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
```

but all the preconditions are fulfilled for it being build as PIE.

**Comment by fluidsonic** [comment]
Why is the build setting `GCC_DYNAMIC_NO_PIC` set to `NO` explicitly for the `Pods` project?

![screenshot 2016-06-03 02 15 29](https://cloud.githubusercontent.com/assets/85242/15765112/2a8d8288-2931-11e6-970c-c807489455a6.png)

For the App project it's set to default (which also resolves to `NO`). Yet the app binary has the `PIE` flag set.

Maybe for archive builds the default value is `YES` which is in turn overwritten with `NO` explicitly by the `Pods` project.

**Comment by meilers** [comment]
Same problem here.

**Comment by 128keaton** [comment]
I'm having the exact same issue. I'm wondering if it is on Apple's end. They've been having trouble all day.

**Comment by Phoenix7351** [comment]
Same issue here too.

**Comment by fluidsonic** [comment]
It's worth noting that framework binaries in archives created half a year ago also had no `PIE` flag set.

So it's likely that Apple just recently added this warning for frameworks. But I have no idea yet how to get the dylibs built with position-independent code.

**Comment by 128keaton** [comment]
@fluidsonic maybe trying to drive people toward the upcoming Swift Library Manager?

**Comment by neonichu** [comment]
Frameworks build via the default "Cocoa Touch Framework" target created in a fresh Xcode project also don't have PIE:

```bash
otool -hv build/Release-iphoneos/yolo.framework/yolo 
build/Release-iphoneos/yolo.framework/yolo (architecture armv7):
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
   MH_MAGIC     ARM         V7  0x00       DYLIB    17        828   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
build/Release-iphoneos/yolo.framework/yolo (architecture arm64):
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64   ARM64        ALL  0x00       DYLIB    17        928   NOUNDEFS DYLDLINK TWOLEVEL NO_REEXPORTED_DYLIBS
```

So seems like this is not an issue specific to CocoaPods and y'all should file radars, etc.

**Comment by 128keaton** [comment]
@neonichu alternatively, wait until Apple gets their crap together. their whole CDN seems to be having an issue, maybe some sysadmin fat fingered a config file or something

**Comment by tin612** [comment]
Same issues too

**Comment by motammi** [comment]
Having the same issue.

**Comment by bgolson** [comment]
Same issue as well

**Comment by SamBellerose** [comment]
Same here

**Comment by dimsky** [comment]
Same issue

**Comment by jeeeyul** [comment]
I'm pretty sure that this is temporary iTunesConnect problem.

I've inspect all my old archives that passed iTunes connect validation without any warnings.
All own custom frameworks that belongs to archives doesn't have PIE flag.

So, I think absent of PIE flag is not a real problem.

**Comment by danhuanggt** [comment]
I just tried uploading a new build now and 7 hours ago, same issue.

Today is just not Apple's day.

**Comment by iAugux** [comment]
Same issue here

**Comment by Atsumi3** [comment]
Same problem

**Comment by sydneyitguy** [comment]
same here :(

**Comment by yanlinaung30** [comment]
Same problem :(

**Comment by Bragegs** [comment]
Same problem! Build still working in testflight, but will it be rejected from app submission?

**Comment by xor22h** [comment]
@Bragegs same problem. It better won't be rejected. It's just the warning thought. Not an error yet. Also, as @neonichu stated older builds where same, just hadn't warning. 

I would guess apple is preparing for WWDC, new XCode and iOS where whese going to be errors instead of warning. We going to see soon if this is a problem or not

**Comment by yanlinaung30** [comment]
**I got the following mail from apple.**

Dear developer,

We have discovered one or more issues with your recent delivery for "BMW/MINI - アクシデントアシスタンス". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Non-PIE Binary - The executable 'Payload/アシスタンス.app/Frameworks/Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/#qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

Non-PIE Binary - The executable 'Payload/アシスタンス.app/Frameworks/COSTouchVisualizer.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/#qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

Non-PIE Binary - The executable 'Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/#qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

Non-PIE Binary - The executable 'COSTouchVisualizer.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/#qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team

**Comment by yanlinaung30** [comment]
**I got the following mail from apple.**

Dear developer,

We have discovered one or more issues with your recent delivery for "MyApp". Your delivery was successful, but you may wish to correct the following issues in your next delivery:

Non-PIE Binary - The executable 'Payload/MyApp.app/Frameworks/Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/#qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

Non-PIE Binary - The executable 'Payload/MyApp.app/Frameworks/COSTouchVisualizer.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/#qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

Non-PIE Binary - The executable 'Alamofire.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/#qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

Non-PIE Binary - The executable 'COSTouchVisualizer.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to [Technical Q&A QA1788 - Building a Position Independent Executable](https://developer.apple.com/library/ios/#qa/qa1788/_index.html#/apple_ref/doc/uid/DTS40013354)

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team

**Comment by zoeGuo** [comment]
anyone has fixed

**Comment by orta** [comment]
I'm locking this thread to avoid the +1s piling on, this is what github added reactions for. If someone learns something _new_ please make a new issue.

**Comment by bumstyla** [comment]
Same here

**Comment by 0xced** [comment]
As it’s been said, this is a bug in iTunes connect. Here’s why: a dynamic framework MUST have position-independent code (PIC). Quoting [Mach-O Programming Topics  / Position-Independent Code](https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/MachOTopics/1-Articles/dynamic_code.html)
> Position-independent code is typically **required for shared libraries** and bundles to allow the dynamic loader to relocate them to different addresses at load time. However, it is not required for applications that typically reside at the same address in virtual memory.

Position-independent executable (PIE) as its name somehow imply is for *main* executables only. A framework can not have the PIE flag because it only makes sense for main executables. This is explained in [mach-o/loader.h](https://github.com/aosm/xnu/blob/9653931b282e653805655cc56831195d0fb162aa/EXTERNAL_HEADERS/mach-o/loader.h#L189-L192):
```objc
#define MH_PIE 0x200000 /* When this bit is set, the OS will
                           load the main executable at a
                           random address.  Only used in
                           MH_EXECUTE filetypes. */
```

The iTMS team must understand that and stop checking for the PIE flag in frameworks…

In the meantime, it’s easy to set the PIE flag on any Mach-O binary, even a framework. I just did it manually with Hex Fiend and I guess such a binary would pass iTMS validation. If someone feels adventurous, please test and report.
```
$ otool -hv AFNetworking+PIE 
AFNetworking+PIE (architecture armv7):
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
   MH_MAGIC     ARM         V7  0x00       DYLIB    26       3276   NOUNDEFS DYLDLINK TWOLEVEL PIE NO_REEXPORTED_DYLIBS
```
