### ISSUE TITLE
Pod is assumed empty if it has only platform-specific source_files

### ISSUE THREAD

**Issue by odrobnik** [CocoaPods/CocoaPods#5457]
# Report

## What did you do?

I have a pod spec that had only `spec.ios.source_files` as well as `spec.osx.source_files`. As of cocoa pods 1.0.0 this causes lint to fail, because there is no `spec.source_files`

## What did you expected to happen?

Linting should work. WORKAROUND: moving the common files into a new `source_files` works around the issue.

## What happened instead?

This error

```
Validating podspec
 -> BarCodeKit (1.3.1)
    - ERROR | File Patterns: The BarCodeKit (1.3.1) spec is empty (no source files, resources, resource_bundles, preserve paths, vendored_libraries, vendored_frameworks, dependencies, nor subspecs).
    - ERROR | [OSX] unknown: Encountered an unknown error (The `BarCodeKit` pod failed to validate due to 1 error:
    - ERROR | File Patterns: The BarCodeKit (1.3.1) spec is empty (no source files, resources, resource_bundles, preserve paths, vendored_libraries, vendored_frameworks, dependencies, nor subspecs).

) during validation.
``

## CocoaPods Environment

[in /Users/oliver/Documents/Projects]

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/oliver/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f1ac23f60a9784af499e6484e3f6748c7a52ae3d
```

### Installation Source

```
Executable Path: /Users/oliver/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '4.3'
pod 'DTFoundation/Core' #=> works
pod 'DTCoreText' #=> works
```

## Project that demonstrates the issue

https://github.com/Cocoanetics/BarCodeKit/blob/9750d1739fb0e31ef6c459c81fc08015b8333b5b/BarCodeKit.podspec

**Comment by neonichu** [comment]
Since you're not explicitly declaring supported platforms, the default of building for all platforms is being used. No `source_files` are declared for either `watchOS` or `tvOS`, that's why you're getting the error.
