### ISSUE TITLE
Running `bundle exec rake spec` switches away from development branch, changes git remote origin

### ISSUE THREAD

**Issue by benasher44** [CocoaPods/CocoaPods#5458]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Checked out my development branch (for this repo) and ran `bundle exec rake spec`

## What did you expected to happen?

Tests to run on my development branch

## What happened instead?

The tests finished (many failures), and I noticed I'm back on the master branch. If I look at .git/config, origin is set to https://github.com/CocoaPods/Specs.git. I suspect this is happening in one of the specs in spec/functional/command/repo/, but disabling various specs doesn't seem to help (or I'm disabling wrong).

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-darwin15.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.3
Ruby lib dir : /Users/basher/.rvm/rubies/ruby-2.1.9/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b6cd88b9ec1277a5de3f3bb220c39c91c802e364
               ooyala - https://github.com/ooyala/ios-sdk-podspecs.git @ 8a82621cfbb23fb0ddae2a6426cb65f225cb436b
               yelpcorp-yelpspecs - ssh://git@git.yelpcorp.com/ios/YelpSpecs @ b32977d8a83f23fcc7b1ef7a37e96889a39b79a4
```

### Installation Source

```
Executable Path: /Users/basher/.rvm/gems/ruby-2.1.9/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.0.0
cocoapods_debug        : 0.1.0
```

## Project that demonstrates the issue

I haven't added any new tests/specs yet, but my in-progress branch where this is happening is [here](/benasher44/CocoaPods/tree/basher_improved_extension_handling)

**Comment by benasher44** [comment]
This happens if you don't have the proper submodules checked out/initialized. `git submodule update --init --recursive` fixed the issue.

I'm trying to figure out some way to warn/error if you don't have the submodules checked out when running `bundle exec rake spec`. So far, I've come up with just running `git submodule status --recursive` and checking for symbols before the listed shas (as specified in the help for `git submodule status`) in the Rakefile. Thoughts?

**Comment by segiddins** [comment]
yeah, a task to check that submodules are checked out would be good, and the spec tasks can depend on that task

**Comment by benasher44** [comment]
Okay sounds good. I'll have a look at this soon.
