### ISSUE TITLE
Pods/Headers folder empty on new project

### ISSUE THREAD

**Issue by cbrandsma-cs** [CocoaPods/CocoaPods#5460]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I created a new Swift based iOS project using XCode 7.1, on OSX 10.11.

The PodFile looks like this:

```
platform :ios, '8.0'
use_frameworks!

target 'TestApp' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
  pod 'MBProgressHUD' , '~> 0.9.1'
end

```
Ran `pod install`  Which creates the Pods folder.

My bridging header now looks like this:

#import "MBProgressHUD.h"
#import "AFNetworking.h"

## What did you expected to happen?

In general, I expected this to compile.  But the import on MBProgressHUD.h causes a "File not found"

## What happened instead?

The other "interesting piece of information" is the ./Pods/Headers folder is empty.  I sort of expect that to have something in it.

## CocoaPods Environment

[in /Users/cbrandsma/development/TestApp]

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e2f173219c98a79f9ce9e7bda191831bf5588105
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'TestApp' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
  pod 'MBProgressHUD' , '~> 0.9.1'
end
```

## Project that demonstrates the issue

https://dl.dropboxusercontent.com/u/8679411/TestApp.zip

**Comment by neonichu** [comment]
When using frameworks, you can only import their headers using explicit module imports (`@import`) in the bridging header. It is much easier, though, to just directly import into Swift, you won't actually need a bridging header when using frameworks.
