### ISSUE TITLE
PATH environment variable should include `/usr/local/bin`

### ISSUE THREAD

**Issue by sadlerjw** [CocoaPods/CocoaPods#5461]
(And presumably `/usr/local/sbin` too)
(Or it should use default path)

🌈
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

The problem is that the `PATH` used by `pod` includes only the following directories:
- Wherever `pod` lives
- `/usr/bin`
- `/bin`
- `/usr/sbin`
- `/sbin`

However binaries no longer tend to be installed there due to system integrity protection on El Capitan -- `brew`, for instance, now installs things to `/usr/local/bin`.  Any `prepare_command` that invokes an executable installed in this manner will fail.

I propose adding `/usr/local/bin` and `/usr/local/sbin` to the `PATH`.
## What did you do?

Tried to use the [CommonMark](https://github.com/chriseidhof/commonmark-swift) pod, which includes [cmark](https://github.com/jgm/cmark) ([podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/cmark/0.24.1/cmark.podspec.json))

`cmark`'s `prepare_command` uses `cmake`

My attempted commands. (See very bottom of report for even easier steps to reproduce)

``` bash
brew update
brew install cmake
pod install
```
## What did you expected to happen?

All pods successfully install. `cmark` successfully executes its `prepare_command`
## What happened instead?

```
[!] /bin/bash -c
set -e
echo `pwd`
sed -i '' 's/include <\(cmark.*\)>/include "\1"/' src/cmark.h
mkdir -p build; cd build && cmake -G Xcode ..

/Users/jsadler/Library/Caches/CocoaPods/Pods/Release/cmark/0.24.1-ec027
/bin/bash: line 4: cmake: command not found
```

Note the following:

``` bash
$ which cmake
/usr/local/bin/cmake

$ echo $PATH
/usr/local/opt/rbenv/shims:/usr/local/sbin:/Users/jsadler/bin:/Users/jsadler/bin:/usr/local/bin:/usr/local/mysql/bin:/Applications/Android Developer Tools/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gems
```
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b4ac62c0601e185ef3b91c82d1abc895f49403fa
```
### Installation Source

```
Executable Path: /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod
```
### Plugins

```
cocoapods-check           : 0.2.1.beta.1
cocoapods-deintegrate     : 1.0.0
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.0.0
cocoapods-try             : 1.0.0
```
### Podfile

``` ruby
platform :ios, '9.0'
use_frameworks!

target 'Envee' do
  pod 'SwiftyDropbox', '~> 3.0'
  pod 'StaticDataTableViewController', '~> 2.0.5'
  pod 'Signals', '~> 3.0.0'
  pod 'ReachabilitySwift', '~> 2.3.3'
  pod 'Marklight', '~> 0.1.4'
  pod 'CommonMark', '~> 0.24.0'
end
```
## Project that demonstrates the issue

Can be reproduced via `pod try cmark` (after having installed `cmake` to `/usr/local/bin/`, e.g. via `brew install cmake`)

**Comment by neonichu** [comment]
I guessing the issue here is that you are setting up a custom `PATH` in your `.bashrc` which will only be considered for interactive shells, where `prepare_command` is executed in a non-interactive shell. 

Don't think we should be messing with the user's environment, there might be good reasons why they have it setup in that way.

**Comment by sadlerjw** [comment]
Okay, I probably misunderstand the issue. How can I set the path for
noninteractive shells?
Thsnks!
Jason

**Comment by sadlerjw** [comment]
FWIW, and I am no expert in `bash` or Ruby, when I use `bash -c` with a cleared environment, my path does seem to be initialized properly:

```
$ env -i bash -c "echo $PATH"
/usr/local/sbin:/Users/jsadler/bin:/Users/jsadler/bin:/usr/local/bin:/usr/local/mysql/bin:/Applications/Android Developer Tools/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/rbenv/shims:/usr/local/sbin:/Users/jsadler/bin:/usr/local/mysql/bin:/Applications/Android Developer Tools/sdk/platform-tools/usr/local/opt/gems
```

(Yes, a lot of paths are repeated. I need to clean up my rc and profile files...)

Not sure if this helps figure out what's happening, or whether it's a complete red herring.
