### ISSUE TITLE
[Question] Using a sub project (xcodeproj, xcworkspace) as Pod

### ISSUE THREAD

**Issue by WoodySlum** [CocoaPods/CocoaPods#5467]
Hi,

I would like to integrate my framework as a subproject instead of directly source code. I mean having the following source tree:
```
\ Development Pods
    |-- MyFramework
           |--- MyProject.xcodeproj
                    |--- My Source code
```

Is it possible ?

**Comment by orta** [comment]
No, you could build this yourself as a `post_install` hook. However it's not something CocoaPods supports.
