### ISSUE TITLE
Can I push a pod without build simulator architecture  

### ISSUE THREAD

**Issue by CodingForMoney** [CocoaPods/CocoaPods#5472]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

 pod repo push xxx xxxx.podspec --allow-warnings --verbose

But there is a `vendored_libraries` in the podspec .The library file do not have the i386 and x86_64 slices.

I just want to ask ,can we push a pod without build some architecture ? Can we set the enable architectures of a pod ?

I know `--use-libraries`, and I do not want to use it.

## What did you expected to happen?

I  want to push the static library to my private repo.

## What happened instead?

But in pushing , Cocoapods reported `symbol(s) not found for architecture i386` `symbol(s) not found for architecture x86_64`.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 94-specs - git://10.75.94.133/Specs.git @ d54b521d2756bb2d233a4824edcef2eada5b0232
               master - https://github.com/CocoaPods/Specs.git @ 2318739355ce6a3996e71140709451dea4370376
               mucfc-specs - buster@10.75.94.133:/usr/local/cocoaPodsRepo/Specs.git @ d54b521d2756bb2d233a4824edcef2eada5b0232
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by orta** [comment]
> I know --use-libraries, and I do not want to use it.

Any reason for this? It sounds like CocoaPods is checking it supports being used as a framework, and it's failing. This is why we added the flag.

**Comment by segiddins** [comment]
I think restricting architectures is not something we want to encourage.

**Comment by CodingForMoney** [comment]
My pods are all using the ` --use-libraries` flag . Something wrong happened when  I tried to use `use_frameworks!` in my podfile. I thought error happened because the two flags were conflicted.But I try again, finding two flags work successfully now.  
So , I can use the `--use-libraries` flag now.
I see that there is no way to restrict architectures in CocoaPods now. Thanks for answering.
