### ISSUE TITLE
Declaring multiple post_installer results in only latest being run and other being silently ignored

### ISSUE THREAD

**Issue by Sajjon** [CocoaPods/CocoaPods#5474]
# Report

## What did you do?
I am using 0.39 but I have verified that this issue exists in cocapods 1.0 as well

**Declare two or several post_install, you can add a debug print in top of each one.**

Run `pod install`

## What did you expected to happen?
I expect either the all code in all post_install scopes will be executed OR cocoapods to warn me about the podfile being badly formatted (since it is not possible to execute code in separate post_install)

## What happened instead?
Only code in the scope of the latest declared post_install is run

## CocoaPods Environment
"pod env" does not work in 0.39, but I have verified that this bug exists in Cocoapods 1.0 as well.

## Project that demonstrates the issue
Checkout [this minimal project](
https://github.com/Sajjon/PodsIgnoresMultiplePostInstall) and run pod install and you won't see the output from the first puts statement in the first post_install, only the second one.

**Comment by orta** [comment]
Would love a to see PR on this, should be nice and simple.

**Comment by Sajjon** [comment]
@orta so that should be the expected behaviour? Either a warning? Or failing pod install? Or allowing multiple declarations of post_install? :)

**Comment by orta** [comment]
IMO it should fail when a second one has been set during Podfile parsing, you could end up with an inconsistent `Pods` setup otherwise, as you probably noticed when it first happened

**Comment by Sajjon** [comment]
@orta agreed, I wasted over 1h on this :P so would be best to force users to only declare one post_installer
