### ISSUE TITLE
Cocoa Pods /Xcode 7.3 ""

### ISSUE THREAD

**Issue by NithyaVenkat** [CocoaPods/CocoaPods#5475]
pod install
Re-creating CocoaPods due to major version update.
Setting up CocoaPods master repo
[!] Unable to add a source with url https://github.com/CocoaPods/Specs.git named master.
You can try adding it manually in ~/.cocoapods/repos or via pod repo add.

The above is the issue am facing.The project was actually created using 7.1.1 and now trying to run in 7.3

When I try to rebuild am getting above error.Please some one suggest

**Comment by segiddins** [comment]
Whats the output of `pod setup --verbose` and `pod env`?

**Comment by NithyaVenkat** [comment]
pod env
--> 

pod env

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```


pod setup -- verbose

 pod setup --verbose

Setting up CocoaPods master repo

Cloning spec repo `master` from `https://github.com/CocoaPods/Specs.git` (branch `master`)
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master
  Cloning into 'master'...
  error: RPC failed; result=56, HTTP code = 200
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master

Cloning into 'master'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed


/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:69:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:71:in `block in clone_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:69:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:69:in `clone_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:41:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/add.rb:39:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:54:in `add_master_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:27:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:21:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

The above is the output am getting for the comments you gave.

**Comment by NithyaVenkat** [comment]
I tried this as well
Go to ~/.cocoapods/repos and run git clone https://github.com/CocoaPods/Specs.git master

output is :
git clone https://github.com/Cocoapods/Specs.git master
Cloning into 'master'...
fatal: unable to access 'https://github.com/Cocoapods/Specs.git/': Could not resolve host: github.com

**Comment by NithyaVenkat** [comment]
Hi Segiddins,

Any update please ?

**Comment by segiddins** [comment]
This looks like a got issue unrelated to CocoaPods to me, sorry

**Comment by avinashtag** [comment]
I am also facing the same issue.

**Comment by vasanthanprem** [comment]
hi NithyaVenkat, did you solve this issue?
