### ISSUE TITLE
Support "--quick" for pod repo push?

### ISSUE THREAD

**Issue by circleplus** [CocoaPods/CocoaPods#5476]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
When trying to do "pod repo push" for our private pod, we hit some compiling errors from inclusion of non-modular headers when performing the phase of "Integrating client project". Since we want to allow the inclusion of non-modular headers from this pod in our own client project, we would like to be able to override some Xcode setting in generated "App.xcodeproj" or simply support "--quick" like in "pod lib lint".

## What did you do?
`pod repo push --verbose ourpod.podspec`

## What did you expected to happen?
we can pass validation by allowing the inclusion of non-modular headers in our pod.

## What happened instead?
"error: include of non-modular header inside framework module .... [-Werror,-Wnon-modular-include-in-framework-module]

**Comment by segiddins** [comment]
Try `--use-libraries` 😉

**Comment by circleplus** [comment]
Hey, Thanks! Unfortunately, I've tried, still the same result. The problematic headers are from CommonCrypto which has been known for issues. I just don't want to create separate module map for that. Is there any way to pass in Xcode build settings to lint validation (when building client integration project)?

**Comment by segiddins** [comment]
not really, beyond the various `xcconfig` specification attributes (and whatever env vars Xcode picks up)

**Comment by circleplus** [comment]
then is it possible to allow customizing the xcconfig of client integration validation project, shown as "App.xcodeproj"?

**Comment by segiddins** [comment]
`user_target_xcconfig` does exactly that

**Comment by circleplus** [comment]
awesome! this worked. I'll close this issue. thanks for jumping on this issue so quickly.
