### ISSUE TITLE
pod transitive decencies and static binaries

### ISSUE THREAD

**Issue by samuel-gallet** [CocoaPods/CocoaPods#5483]
# Report

## What did you do?
I Wrote a Podfile to include 2 pods to my project. The first pod is written in swift. The second one has a dependency with google-cast-sdk.

run pod install

## What did you expected to happen?
I expected to have a successful pod installation 

## What happened instead?
I got an error first saying "Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it." so I add use_frameworks! in my podfile.

Then I got the error : "The 'Pods-TargetName' target has transitive dependencies that include static binaries: (/pathToMyProjet/Pods/Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework"

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : applidium-cocoapodsspecs - git@scm.applidium.net:CocoaPodsSpecs.git @ e96754417eaf50516fcdcbf864cb4f3f9221bda1
               master - https://github.com/CocoaPods/Specs.git @ f0d79e4ff4a146593874bc6e859140c60526db78
               smartnsoft - https://github.com/smartnsoft/SmartCocoapods.git @ 7399b5176da9946e5f0775d668eda5d10a505946
               TestDevPod - /Users/samuelgallet/Desktop/TestCocoapod/TestDevPod @ e2ab01ffae7cd5a352d535106031f81466b49577
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0

```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

pod 'Watchdog', '~>2.0'
pod 'podWithGoogleCastSDKDepency'

target 'TestCocoapod'
```

**Comment by orta** [comment]
This isn't an error, you cannot use transitive static dependencies in a frameworks project. You should request a dynamic framework from Google.
