### ISSUE TITLE
pod can't specify version well

### ISSUE THREAD

**Issue by L-Jovi** [CocoaPods/CocoaPods#5485]
I post question on [stackoverflow](http://stackoverflow.com/questions/37696803/pod-cant-specify-version-well/37702507),  would you mind have a look?

thanks for your time.

**Comment by orta** [comment]
I don't want to keep around issues that are not actionable bugs or feature requests for CocoaPods, so I'm going to close this issue.

**Comment by L-Jovi** [comment]
@orta  To this I'm sorry, and would you mind take a look about my question on stackoverflow.

thanks for your reply :)
