### ISSUE TITLE
ibtool causing huge slowdown on "Copy Pod Resources"

### ISSUE THREAD

**Issue by scosman** [CocoaPods/CocoaPods#5488]
* [ √ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run a project using cocoapods in the simulator.

## What did you expect to happen?

It to launch in a reasonable amount of time, especially when the pods are already built & cached.

## What happened instead?

Every run, the "Copy Pod Resources" custom build step takes > 30s (even warm builds). This greatly slowing down development speed. All of the time is spent in the ibtool step, processing files that could have been done in the build phase and cached for all future builds. 

Commenting out the ibtool step of `Pods-Project-resources.sh` takes the time down from >30s to 2s. 

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.4.3
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.2.1
Ruby lib dir : /Users/asdf/.rvm/rubies/ruby-2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0cebf14447d85fe1f561a6fc0e0da068ff79aa6c
```

### Installation Source

```
Executable Path: /Users/asdf/.rvm/gems/ruby-2.1.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '7.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'Asdf' do
  pod 'Kite-Print-SDK'
  pod 'Kite-Print-SDK/PayPal'
end

**Comment by segiddins** [comment]
Try integrating your pods as frameworks, that might help

**Comment by scosman** [comment]
@segiddins that will take a bit of work so I won't be able to report back asap (some pods using static libs).

Assuming frameworks are the way forward, and improving speed of the old method won't meet the bar for new development? If so, feel free to close.

**Comment by segiddins** [comment]
It's just something that's really hard to improve -- we got a PR a while back that tried to cache the results but it ended up having a bunch of small issues. It's not something I'm opposed to improving, but those improvements are unlikely to come from us. Thanks for understanding!

**Comment by neonichu** [comment]
Closing this, because I don't think there unfortunately isn't anything actionable we can do here right now.
