### ISSUE TITLE
PivotalCoreKit Long Directory Name break

### ISSUE THREAD

**Issue by mgoovaer** [CocoaPods/CocoaPods#5491]
# Report
Original issue filed with PivotalCoreKit here: https://github.com/pivotal/PivotalCoreKit/issues/191

## What did you do?
Updated our podfile dependencies ('pod update')

## What did you expect to happen?
Install all pod dependencies correctly

## What happened instead?
We received an error ‘ENAMETOOLONG’ for installing our PivotalCoreKit pod as shown in attached images

![fe855462-2990-11e6-9922-c95140ba0d8b](https://cloud.githubusercontent.com/assets/3597484/15910785/8dfb8014-2d9a-11e6-8609-0abd8ef887f5.png)
![fe7e7ebc-2990-11e6-8cbf-22dc4f670a79](https://cloud.githubusercontent.com/assets/3597484/15910787/8e06e54e-2d9a-11e6-8bdb-d6e7090133a9.png)
![fe7d3dae-2990-11e6-9050-0e57139cefcd](https://cloud.githubusercontent.com/assets/3597484/15910786/8dfc1254-2d9a-11e6-8a19-64de599deeda.png)

**Comment by neonichu** [comment]
Could you please share the error reporting, including the used Podfile as text — that way folks won't have to retype it when trying to reproduce

**Comment by neonichu** [comment]
Maybe @mrackwitz wants to check this one out — I'm thinking beyond a certain length the auto generated name becomes non-human readable anyway and we could switch to a different format (hash of the full name?).

**Comment by orta** [comment]
I _think_ turning off de-duplicating targets removes the fancy names

**Comment by mrackwitz** [comment]
Dang! @orta is right. That's a problem with the names generated by the target deduplication to differentiate the targets. Maybe we should just use numbers all together?

As an alternative workaround you could also share the same subspecs across both targets.

**Comment by jjamminjim** [comment]
I am having the same issue, and can not share all the subspaces across targets, as different subspaces in the pod target different platform sets, and each target in my podfile is platform specific.

**Comment by mgoovaer** [comment]
@neonichu attached are the Podfile and the error as text, thanks for looking into this!

[Podfile.txt](https://github.com/CocoaPods/CocoaPods/files/312000/Podfile.txt)
[pod_install_error.txt](https://github.com/CocoaPods/CocoaPods/files/312032/pod_install_error.txt)

**Comment by juliozatarain** [comment]
@neonichu Is there any update on this?
the input seems to be provided.

**Comment by orta** [comment]
We know the problem, but no-one has worked on this yet I'm afraid. This is the crux of the problem:

>  That's a problem with the names generated by the target deduplication to differentiate the targets.

re:

> Maybe we should just use numbers all together?

Could we do it if it's over _x_ chars? E.g. 60?

**Comment by segiddins** [comment]
@orta could do that, or take an MD5 sum if it's over x chars as well

**Comment by mgoovaer** [comment]
@orta @segiddins any eta on this fix? it looks like you have an idea of what approach to take...

**Comment by mrackwitz** [comment]
No ETA yet, but I've a work in progress fix, I'll put up soon.

**Comment by mgoovaer** [comment]
@mrackwitz thanks!

**Comment by juliozatarain** [comment]
bump @mrackwitz

**Comment by cooldhiman** [comment]
Hey guys, is there an update on this?

**Comment by devluyy** [comment]
I have a common problem, when use a private repos?

**Comment by segiddins** [comment]
There's an open PR addressing this now
