### ISSUE TITLE
How to switch version of Ruby for CocoaPod ?

### ISSUE THREAD

**Issue by kong707** [CocoaPods/CocoaPods#5492]
I installed Ruby version 2.3.1 by rbenv. If I type ruby --version  , it showns the version 2.3.1 is working. 
But if I type  pod env . Here is what I got 

  CocoaPods : 1.0.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)

I think this make have the error when run 'pod install'
it just keep saying
TypeError - Unable to convert Ruby value `"AFNetworking"' into a CFTypeRef.
/usr/local/lib/ruby/gems/2.2.0/gems/xcodeproj-1.1.0/lib/xcodeproj/plist/ffi/core_foundation.rb:383:in `RubyValueToCFTypeRef'

Please help

**Comment by neonichu** [comment]
You should check out this: <https://github.com/rbenv/rbenv/wiki/Understanding-binstubs> — this situation is not really CocoaPods specific, but rather a general Ruby thing. If you're not normally using Ruby, it might be much easier to use the Mac app instead: https://cocoapods.org/app
