### ISSUE TITLE
Unsupported characters in the charset UTF-8

### ISSUE THREAD

**Issue by jasperblues** [CocoaPods/CocoaPods#5493]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

installed some dependencies with CocoaPods pod install

## What did you expect to happen?

Appcode validation reports no errors. 

## What happened instead?

Everything works fine, except that AppCode's inspections report issues in the project.pbxproj file - unsupported characters. 

![charset](https://cloud.githubusercontent.com/assets/430321/15916711/1e2cb54e-2e28-11e6-9222-384def025bfb.png)

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.1
Ruby lib dir : /Users/jblues/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c14a1b4fa99df02781063e4fc011b85f6262eb06
```

### Installation Source

```
Executable Path: /Users/jblues/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0

**Comment by orta** [comment]
This was fixed in 1.0.1, where we switched to use `[CP]` 👍

**Comment by jasperblues** [comment]
Oops must've run install with old verison of CP. Apologies.

**Comment by orta** [comment]
No problem
