### ISSUE TITLE
`pod update` does not respect `--no-repo-update` flag

### ISSUE THREAD

**Issue by shrutisharmavsco** [CocoaPods/CocoaPods#5494]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
```
    pod repo add <private_specs_repo> <private_specs_repo_url>
    (cd ~/.cocoapods/repos/<private_specs_repo>  && pod repo lint .)
    pod update --no-repo-update
```
## What did you expect to happen?

for the private_specs_repo to not update or clone from git again but for the pod to just update

## What happened instead?
Error: 
```
Cloning spec repo `<private_specs_repo>-1` from `<private_specs_repo_url>`

[!] Unable to add a source with url `<private_specs_repo_url>` named `<private_specs_repo>-1`.

You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
```

## CocoaPods Environment

1.0.0

**Comment by segiddins** [comment]
It's not updating, it's just trying to clone, and there's no getting around that.

**Comment by shrutisharmavsco** [comment]
even if the repo is already cloned, it will try to clone again?

**Comment by segiddins** [comment]
Whats the output of pod repo list and the contents of your podfile?

**Comment by shrutisharmavsco** [comment]
never mind, I figured it out - the pod file lists the private_pod_repo as a source in `https://github.com/private_pod_repo.git` format and the git user trying to run pod update did not have https access but only ssh (`git@`) access to the private pod repo. Adding https access rights for this user fixed the problem.

What is still a mystery to me is that since I was cloning in the private_pod_repo using `git@` before calling pod update, why would it try to clone the repo again using `https`?

**Comment by segiddins** [comment]
If you share the actual URLs I'd be happy to try a create a failing unit test

**Comment by shrutisharmavsco** [comment]
the pod repos are private github repos so even if I were to share the URLs, I'm not sure you'd be able to access them. :/

**Comment by segiddins** [comment]
The URLs are all we'd need to debug re-cloning

**Comment by shrutisharmavsco** [comment]
I first ran `pod repo add my-specs git@github.com:my-org/my-specs.git`

the beginning of my Podfile looked like this:
```
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/my-org/my-specs.git'

target ...
```
Then I ran `pod update --no-repo-update`, this was the output:
```
Cloning spec repo `my-specs-1` from `https://github.com/my-org/my-specs.git`
[!] Unable to add a source with url `https://github.com/my-org/my-specs.git` named `my-specs-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
```
does this help?

**Comment by segiddins** [comment]
it does, thanks!

**Comment by segiddins** [comment]
I'd recommend using the same URL for now -- if using https doesn't work for you for some reason, you can put the `git@github.com:my-org/my-specs.git` URL in your Podfile

**Comment by shrutisharmavsco** [comment]
Ah ok, makes sense. For now, the https version does work after I fixed all the permissions issues for git user running `pod update`
thanks!
