### ISSUE TITLE
Issue while installing pods with cocoapod version 1.0.1

### ISSUE THREAD

**Issue by vishal91** [CocoaPods/CocoaPods#5496]
Trying to install podfile of project. 

Tried pod install with gem install cocoapods -v 1.0.1

Not able to install pods.

Getting this error, i removed rvm, cocoapods and reinstalled everything with cocoapods -clean

<img width="981" alt="screenshot 2016-06-09 16 38 41" src="https://cloud.githubusercontent.com/assets/3819785/15927704/c028e5ce-2e60-11e6-8574-e90ce2eeef39.png">

**Comment by orta** [comment]
There is a problem with your `post_install` hook in your Podfile, it's syntax is wrong. Try running through [the migration guide](http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/) ( if you've just updated to 1.0 )
