### ISSUE TITLE
trouble with pod-template.git when git user name has an apostrophe

### ISSUE THREAD

**Issue by koconnor** [CocoaPods/CocoaPods#5498]
- [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Ran `pod lib create testLib`
## What did you expect to happen?

Create bootstrap pod for a library
## What happened instead?

The pod install command failed because the git user name has an apostrophe, which broke the parsing of the configured pod spec. 

~/.gitconfig is 

```
[user]
    name = Kevin O'Connor
    email = KOConnor@null.org
[push]
    default = current
[core]
    excludesfile = /Users/koconno1/.gitignore_global
[difftool "sourcetree"]
    cmd = opendiff \"$LOCAL\" \"$REMOTE\"
    path = 
[mergetool "sourcetree"]
    cmd = /Applications/SourceTree.app/Contents/Resources/opendiff-w.sh \"$LOCAL\" \"$REMOTE\" -ancestor \"$BASE\" -merge \"$MERGED\"
    trustExitCode = true
[merge]
    renamelimit = 30000
[color]
    ui = true
[commit]
    template = /Users/koconno1/.stCommitMsg
[filter "lfs"]
    smudge = git-lfs smudge %f
    required = true
    clean = git-lfs clean %f
```

The `configure` script that is run resulted in the following on line 27 of `testLib.podspec`:

```
  s.author           = { 'Kevin O'Connor' => 'KOConnor@null.org' }
```

A possible solution is to adjust the `NAME.podspec` template file to have the following at line 27.

```
   s.author           = { "${USER_NAME}" => '${USER_EMAIL}' }
```

rather than

```
   s.author           = { '${USER_NAME}' => '${USER_EMAIL}' }
```

There may be other ways to solve it with appropriate quoting of the `user_name`.
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/koconno1/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0d75319cbcddb5044e9c0658f35c84d8080a1a15
```
### Installation Source

```
Executable Path: /Users/koconno1/.rvm/gems/ruby-2.3.0/bin/pod
```
### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.0.0
cocoapods_debug        : 0.1.0
```

**Comment by koconnor** [comment]
Perhaps, but I don't think that will have quite the desired effect.  
`dump` does not appear to consider an apostrophe a special character.

If I edit line 125 in TemplateConfigurator.rb to be
```
        text.gsub!("${USER_NAME}", user_name.dump)
```
The result for line 27 in the configured pod spec is 
```
    s.author           = { '"Kevin O'Connor"' => 'KOConnor@null.org' }
```

This yields the following complaint from the `pod install` call
```
[!] Invalid `kevster.podspec` file: syntax error, unexpected tCONSTANT, expecting =>
...           = { '"Kevin O'Connor"' => 'KOConnor@null.org...
...                               ^
/Users/koconno1/tmp/podtest/k/kevster.podspec:27: unterminated string meets end of file
/Users/koconno1/tmp/podtest/k/kevster.podspec:27: syntax error, unexpected end-of-input, expecting keyword_end.

 #  from /Users/koconno1/tmp/podtest/k/kevster.podspec:27
 #  -------------------------------------------
 #    s.license          = { :type => 'MIT', :file => 'LICENSE' }
 >    s.author           = { '"Kevin O'Connor"' => 'KOConnor@null.org' }
 #    s.source           = { :git => 'https://github.com/<GITHUB_USERNAME>/kevster.git', :tag => s.version.to_s }
 #  -------------------------------------------
```

**Comment by segiddins** [comment]
Right but it adds quotes itself, so we'd have to do that instead of manually quoting in the template

**Comment by koconnor** [comment]
ah, I see, just have the `${USER_NAME}` without any quotes, single or double, in the template.  Yes.

I guess i can do this by hand in the meantime, is this something that would go in the queue soon?

**Comment by segiddins** [comment]
If we can think of a way of making the change in a backwards compatible manner, I'd love to merge a PR doing so

**Comment by koconnor** [comment]
Oh, so the template `NAME.podspec` and/or the `TemplateConfigurator.rb` are shared among multiple packages?  Too bad, if they were only used in the `git clone https://github.com/CocoaPods/pod-template.git <name>` it would be easy as they are both removed after the single use and backwards compatibility wouldn't be an issue since they are removed after the `pod lib create <name>`.
Thanks for looking into this.  Would this be closed after some release of a fix, PR or otherwise?

**Comment by segiddins** [comment]
Ah if both of those are in the pod template than we can just fix them there 👍🏻

**Comment by koconnor** [comment]
I can say that they are both in there and they both are removed by the end of the `pod lib create <name>` call. (I had to do the `git clone https://github.com/CocoaPods/pod-template.git <name>` by hand to get a hold of them to play around.) But I can't say what goes on behind your curtain. 😉

**Comment by segiddins** [comment]
A PR to https://github.com/CocoaPods/pod-template with that change would be 🚀 then!

**Comment by koconnor** [comment]
🍻

**Comment by henriwatson** [comment]
This is a Bit More Fun Than Expected.

Making the changes suggested above will result in the following when running `pod lib lint`

    [!] Invalid `NAME.podspec` file: `${' is not allowed as a global variable name
    /Users/henri/w/notmine/Rainforest/pod-template/NAME.podspec:27: syntax error, unexpected end-of-input, expecting '}'
      s.author           = { ${USER_NAME} => '${USER_EMAIL}' }
                              ^.

Hopefully [CocoaPods/pod-template#187](https://github.com/CocoaPods/pod-template/pull/187) can better handle this.

**Comment by segiddins** [comment]
Maybe it's about time we change that template to use ERB instead of gsub'ing in templates values?

**Comment by orta** [comment]
The new one is a whole new ball game, I believe, https://github.com/CocoaPods/pod-template/pull/187
