### ISSUE TITLE
Feature Request: Support symlinked Pods directory

### ISSUE THREAD

**Issue by hborders** [CocoaPods/CocoaPods#5499]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

My team uses github enterprise and we get in our `Pods` directory. This generates a lot of noise in our diffs. To work around this noise, I want to commit our `Pods` directory into a submodule. This currently works fine. However, I have a bunch of other workspaces in the same repo for small reusable bits of code we currently manage with development pods. I'd like those `Pods` directories to go into the submodule as well.

Thus, I have the following directory structure:

```
Common/ #contains my development pod, workspace, projects, and Podfile for testing
Common/Pods/ #symlinked to ../pods_submodule/Main/Pods
Main/ # contains my main workspace, projects, and Podfile
Main/Pods/ #symlinked to ../pods_submodule/Main/Pods
pods_submodule/ # root of the git submodule that will hold all my CocoaPods generated files
pods_submodule/Common/Pods / #symlink target for /Main/Pods
pods_submodule/Main/Pods/ #symlink target for /Main/Pods
```

I expected that this would work, but unfortunately, the `[CP] Check Pods Manifest Lock` Build Phase fails because it refers to `Podfile.lock` relative to `$PODS_ROOT` rather than relative to `Podfile` or the workspace. I worked around this by symlinking `Podfile.lock` into my above directory structure:

```
Common/Podfile.lock #symlinked to ../pods_submodule/Common/Podfile.lock
Main/Podfile.lock #symlinked to ../pods_submodule/Main/Podfile.lock
pods_submodule/Common/Podfile.lock #symlink target for /Common/Podfile.lock
pods_submodule/Main/Podfile.lock #symlink target for /Main/Podfile.lock
```

But this seems a bit hackish, and I'm afraid it will break in future releases. Would you accept a patch to support symlinked `Pods` directories by making the `[CP] Check Pods Manifest Lock` better at finding `Podfile.lock` in this case?

**Comment by segiddins** [comment]
We could probably just assume it's `$SRCROOT/Podfile.lock`?

**Comment by hborders** [comment]
That's what I hoped. I changed my `[CP] Check Pods Manifest Lock` script to
```
diff "${SRCROOT}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
```

And everything worked great.

**Comment by DanToml** [comment]
@hborders 👍 - A pull request would be welcome changing this to ${SRCROOT}

**Comment by Coeur** [comment]
The merged pull request will be reverted by its author with #6476

**Comment by dnkoutso** [comment]
@hborders after #6483 lands would you be able to verify it works? Otherwise this will remain closed and assumed its fixed.

**Comment by hborders** [comment]
How do I use cocoapods from `master` ? When I landed my patch before, I just edited the files in my gems directory directly, but I'd like to learn how to do things properly.

**Comment by orta** [comment]
Would recommend a Gemfile: https://guides.cocoapods.org/using/a-gemfile.html

**Comment by hborders** [comment]
Thanks! I tried that, but I can't install locally:

```
$ bundle install --path ./gems
Fetching https://github.com/CocoaPods/CocoaPods.git
Fetching https://github.com/CocoaPods/Core.git
Fetching https://github.com/CocoaPods/Xcodeproj.git
Fetching https://github.com/orta/cocoapods-keys.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Rubygems 2.0.14.1 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Installing CFPropertyList 2.3.5
Installing ZenTest 4.11.1
Installing i18n 0.8.0
Installing json 1.8.6 with native extensions
Installing minitest 5.10.1
Installing thread_safe 0.3.5
Installing mini_portile2 2.1.0
Installing claide 1.0.1
Installing fuzzy_match 2.0.4
Installing nap 1.1.0
Installing cocoapods-deintegrate 1.0.1
Installing cocoapods-downloader 1.1.3
Installing cocoapods-search 1.0.0
Installing cocoapods-stats 1.0.0
Installing netrc 0.7.8
Installing cocoapods-try 1.1.0
Installing colored2 3.1.2
Installing escape 0.0.4
Installing fourflusher 2.0.1
Installing gh_inspector 1.0.3
Installing molinillo 0.5.6
Installing ruby-macho 0.2.6
Installing nanaimo 0.2.3
Installing dotenv 2.2.0
Installing highline 1.7.8
Installing multipart-post 2.0.0
Installing net-ssh 4.0.1
Installing plist 3.1.0
Installing rouge 1.11.1
Installing rubyzip 1.2.1
Installing sbconstants 1.2.0
Installing security 0.1.3
Installing unicode-display_width 1.1.3
Using bundler 1.12.5
Installing RubyInline 3.12.4
Installing tzinfo 1.2.2
Installing nokogiri 1.7.0.1 with native extensions

Gem::InstallError: nokogiri requires Ruby version >= 2.1.0.
Installing cocoapods-plugins 1.0.0
Installing cocoapods-trunk 1.1.2
Installing commander 4.4.3
Installing faraday 0.11.0
Installing net-sftp 2.1.2
Installing xcpretty 0.2.4
Installing terminal-table 1.7.3
Installing osx_keychain 1.0.1
Installing activesupport 4.2.7.1
An error occurred while installing nokogiri (1.7.0.1), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.7.0.1'` succeeds before bundling.
```

I'm not a ruby developer, so I really don't want to install a new ruby on my system and possibly mess it up. Any quick advice for working around this before I use a VM?

**Comment by segiddins** [comment]
@hborders just put an order nokogiri in your gemfile
