### ISSUE TITLE
Invalid Swift Support

### ISSUE THREAD

**Issue by croccio** [CocoaPods/CocoaPods#5501]
* [V ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

i've executed a build of ipa with xcodebuild and upload to store (test flight)

## What did you expect to happen?

will start he approbation

## What happened instead?

get this error "Invalid Swift Support"

## CocoaPods Environment

```

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c6b06ccfdb64ec23ea29b38d238e9d27da3a4bc9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-repo-svn    : 2.0.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
slather               : 2.2.0
```

### Podfile

```ruby
platform :ios, "8.0"

use_frameworks!

target :TornaQUI do

	pod 'MBProgressHUD'
	pod 'SHGestureRecognizerBlocks'
	pod 'Google/Analytics'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts "#{target.name}"
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```

```

**Comment by neonichu** [comment]
Sounds similar to #4188 — but that should be fixed in 1.0 — we'll need more information from you in order to investigate this, including the full error from iTunes Connect.

**Comment by croccio** [comment]
I'm doing all with Jenkins, with xcodebuild plugin. I've seen that in the
final ipa some folders are missing. Infact unzipping it add folders and
files, store doesnt give me thst errore, but give me error on some symlink
of pod framework
Il 10 giu 2016 7:29 PM, "Boris Bügling" <notifications@github.com> ha
scritto:

**Comment by neonichu** [comment]
Sorry, but this description is still way too vague to make this issue actionable. Could you please share what you did to resolve your problem and how that relates to CocoaPods integration?

**Comment by plu** [comment]
Using `xcodebuild` does not properly include the `SwiftSupport`. See also for workarounds:

* https://github.com/nomad/shenzhen/blob/0215d6df4637ea020455ec5327f39dae93595e09/lib/shenzhen/commands/build.rb#L99
* https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/gym/lib/gym/xcodebuild_fixes/swift_fix.rb

**Comment by orta** [comment]
Thanks @plu - calling this one closed for the moment then.
