### ISSUE TITLE
Umbrella header not being created when running lint tool

### ISSUE THREAD

**Issue by dlbuckley** [CocoaPods/CocoaPods#5506]
# Report 🌈
## What did you do?

I've landed myself a project which has a bunch of different frameworks written in both ObjC and Swift that are split down into a repository each. These frameworks make up a dependancy chain to produce a couple of frameworks that can be imported into the main project. 

To simplify management and code review of these frameworks I'm moving them all into a single repo and converting them into pods. The idea is to have a single pod that can be imported into a project. The pods spec for this pod will consist of a bunch of subspecs for each of the individual frameworks that I'm migrating to this new method of dependancy management.

So far I've created a couple of subspaces and all seems to have gone well, running `pod lib install` passes and the world is a happy place. All of the files are imported into the same project in Xcode and it builds fine and gets imported into an example project fine. But I've only added the root podspecs that don't depend on any other subspaces yet (other than a single external pod that works fine).

I'm now to the point where I want the next subspec to rely on 2 other subspecs. I've defined these using `ss.ios.dependency` for both of the subspaces that I require. The one is written in Swift and the other is in ObjC.

Now when I run  'pod lib lint` I get an error saying that the header file for my pod cannot be found.

`xcodebuild:  <module-includes>:2:9: note: in file included from <module-includes>:2:
 xcodebuild:  /Users/.../Build/Products/Release-iphonesimulator/XXXKit/XXXKit.framework/Headers/XXXKit-Swift.h:101:9: error: 'XXXKit/XXXKit.h' file not found`

I've tried a couple of things in the podspec like making sure the public headers are defined in the ObjC subspec dependancy are all correct, but I'm a bit lost as to whats happening. The project still builds in Xcode correctly and gets imported into the example project fine, but running `pod lib lint` seems to flag up a bunch of problems.

I've tried the verbose setting on the linter and can see that 2 headers are being created `XXXKit-Swift.h` and `XXXKit-umbrella.h`, but nothing to wrap them both up which is required (as demonstrated in the errors above).
## What did you expect to happen?

I expect that the correct umbrella header to be created so the pod can be installed correctly and the linter to pass.
## CocoaPods Environment

I have included the podspec below but renamed a few things as the project is under NDA at the moment. The subspec that's causing the issues is the `SwiftFramework2` subspec.
### PodSpec

```
Pod::Spec.new do |s|

  s.name             = 'XXXKit'
  s.version          = '0.1.0'
  s.summary          = ''
  s.homepage         = ''
  s.license          = { :type => 'NONE', :text => 'NONE' }
  s.author           = { 'XXX' => 'info@XXX.com' }
  s.source           = { :git => 'https://github.com/XXX/XXXKit.git', :tag => s.version.to_s }
  s.module_name      = 'XXXKit'

  s.ios.deployment_target = '9.0'

  s.subspec 'ObjCFramework1' do |ss|
    ss.source_files   = 'Source/ObjCFramework1/**/*.{h,m}'
    ss.frameworks     = 'Foundation', 'CoreBluetooth', 'CoreGraphics', 'GLKit'
    ss.public_header_files = ['Source/ObjCFramework1/Path/File1.h', 'Source/ObjCFramework1/Path/File2.h']
  end

  s.subspec 'ObjCFramework2' do |ss|
    ss.source_files   = 'Source/ObjCFramework2/**/*.{h,m}'
    ss.frameworks     = 'Foundation', 'AVFoundation'
  end

  s.subspec 'SwiftFramework1' do |ss|
    ss.ios.source_files   = 'Source/SwiftFramework1/**/*.swift'
    ss.ios.frameworks     = 'Foundation', 'UIKit'
    ss.ios.dependency 'SSZipArchive', '1.2'
  end

  s.subspec 'ObjCFramework3' do |ss|
    ss.ios.source_files     = 'Source/ObjCFramework3/**/*.{h,m,c}'
    ss.ios.frameworks       = 'Foundation', 'UIKit', 'GLKit'
    ss.ios.resource_bundle  = { 'ObjCFramework3Resources' => 'Source/ObjCFramework3/Resources/**/*' }
  end

  s.subspec 'SwiftFramework2' do |ss|
    ss.ios.source_files = 'Source/SwiftFramework2/**/*.{swift}'
    ss.ios.frameworks = 'Foundation', 'CoreBluetooth'
    ss.ios.dependency 'XXXKit/ObjCFramework1'
    ss.ios.dependency 'XXXKit/SwiftFramework1'
  end

end
```
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 72750745cc4177a95e5e85b49a2fd120af254706
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
# Podfile
source 'https://github.com/CocoaPods/Specs.git'

workspace 'XXXKit'
use_frameworks!

platform :ios, '9.0'

target 'XXXKit' do
  podspec
end

target 'XXXKitTests' do
  podspec
end

target 'XXXKitExample' do
  project 'Example/XXXKitExample.xcodeproj'
  pod 'XXXKit', :path => '.'
end
```

Any help with this would be great. I'm very new to creating subspecs so I don't know the ins and outs as to whats going on under the hood which makes solving this issue a bit of a minefield.

**Comment by dlbuckley** [comment]
I've tried creating new project and importing the pod locally and I'm getting the same problem with the `XXXKit.h` file now being created correctly. It's looking more like a problem in my podspec file than in the listing tool (the linting tool is flagging up the issue correctly).

As a test I tried adding in `public_header_files` and directing it towards my local `XXXKit.h` header but that complained even more that the files that were being included weren't the root spec (which is correct as they are in a subspec).

My search continues...

**Comment by dlbuckley** [comment]
I've been playing around for a while with little success. It's starting to feel like it's something to do with mixing Swift and ObjC but I'm not sure for certain.

What I'm thinking to do now is to split the frameworks down into different projects within the same workspace and each should have their individual podspec. That way I can keep the Swift and ObjC files in their own respective frameworks and simply have pod dependencies in each podspec rather than having subspec dependencies. Hopefully that solution will mean each framework stays in a single language and I don't have random weirdness with imports or umbrella headers.

If anyone else has any thoughts then any hints would be great.

**Comment by neonichu** [comment]
I think you're running into #3767
