### ISSUE TITLE
Anyone coming at WWDC2016?

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#5511]
Hello and sorry for the off-topic,

It's almost my first time in USA, I don't know anyone here, so I was wondering if any of you would attend the WWDC event in SF. As I have no easy other way to reach fellow github developpers, I thought about using the CocoaPods issue tracker as I've heard there will be a CocoaPods State of the Union party! https://sotu.cocoapods.org

If you look for me, I will be among the few with a pink MacBook, and name Antoine.

@laptobbe, @tomaz, @samgreen, @orta, @neonichu, @manuyavuz, @segiddins, ...

**Comment by samgreen** [comment]
@Coeur You're more than welcome to stop by the Mixpanel office! Email me at first.last@mixpanel.com to arrange it :)

**Comment by tomaz** [comment]
Haha, no reason to apologize, you can also try an `@channel` ping on appledoc Slack. I'm not going myself, but am driving to our CocoaHeads group to watch the keynote together.

**Comment by Coeur** [comment]
Thank you all for coming to the CocoaPods event, it was great and I was very pleased to meet you all.

ps: Sam, I'll write to you soon.

**Comment by orta** [comment]
👍
