### ISSUE TITLE
1.0.1: Missing framework search path on Unit Test target

### ISSUE THREAD

**Issue by plu** [CocoaPods/CocoaPods#5512]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Sample project available here: https://github.com/plu/SearchPath

`Podfile`

``` ruby
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

target 'SearchPath' do
  platform :ios, '8.0'

  pod '1PasswordExtension'
  pod 'Google-Mobile-Ads-SDK'

  target 'SearchPathTests' do
    inherit! :search_paths
  end
end
```

`SearchPathTests.swift`

``` swift
import XCTest
import OnePasswordExtension // OK
import GoogleMobileAds // NOK: No such module GoogleMobileAds
@testable import SearchPath

class SearchPathTests: XCTestCase {

    func testExample() {
        XCTAssert(true)
    }

}
```
## What did you expect to happen?

That it can compile and execute `SearchPathTests.swift`.
## What happened instead?

It fails to compile, error `No such module GoogleMobileAds`. However it can find the `OnePasswordExtension` module. I'd expect the framework search path to be the same for the app target and the test target, when I specify `inherit! :search_paths` in the `Podfile`. I'm not sure why it would make a difference between `OnePasswordExtension` and `GoogleMobileAds`. In the attached screenshots you can see that the `SearchPathTests` target is missing `"$(PODS_ROOT)/Google-Mobile-Ads-SDK/Frameworks"` but contains `"$PODS_CONFIGURATION_BUILD_DIR/1PasswordExtension"`.
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.5.2
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/joplunien/.rvm/rubies/ruby-2.1.2/lib
Repositories : ebay-cocoapods-specs - git@github.corp.ebay.com:eBay-Kleinanzeigen/cocoapods-specs.git @ cf942c64824c2afefcd668b8d4203a341799dcda
               master - https://github.com/CocoaPods/Specs @ d7e019e4b893db3e9a8b198599d5909e80fdf127
```
### Installation Source

```
Executable Path: /Users/plu/.rvm/gems/ruby-2.1.2/bin/pod
```
### Plugins

```
cocoapods-deintegrate      : 1.0.0
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-superdeintegrate : 0.0.1
cocoapods-trunk            : 1.0.0
cocoapods-try              : 1.0.0
```
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

target 'SearchPath' do
  platform :ios, '8.0'

  pod '1PasswordExtension'
  pod 'Google-Mobile-Ads-SDK'

  target 'SearchPathTests' do
    inherit! :search_paths
  end
end
```
## Project that demonstrates the issue

https://github.com/plu/SearchPath

![app_target](https://cloud.githubusercontent.com/assets/31597/15998079/6540bafa-313b-11e6-9e7a-92bc0a4bf0a9.png)
![test_target](https://cloud.githubusercontent.com/assets/31597/15998080/65415ec4-313b-11e6-9ddf-54600cc265c8.png)
![test_target_build_failure](https://cloud.githubusercontent.com/assets/31597/15998081/6541bce8-313b-11e6-92a1-afcb9fec2aee.png)

**Comment by plu** [comment]
When I look at the list of dependencies in our app that are affected from this issue, it's not only `GoogleMobileAds`, it's a few more. They all seem to have in common that their `podspec` is providing them as `vendored_libraries` (or `vendored_frameworks`). Maybe this gives you guys some hint where to dig in the `CocoaPods` source. Here's the list of dependencies, in case you're curious:

* [Crashlytics](https://github.com/CocoaPods/Specs/blob/master/Specs/Crashlytics/3.7.1/Crashlytics.podspec.json)
* [Fabric](https://github.com/CocoaPods/Specs/blob/master/Specs/Fabric/1.6.7/Fabric.podspec.json)
* [Google-Mobile-Ads-SDK](https://github.com/CocoaPods/Specs/blob/master/Specs/Google-Mobile-Ads-SDK/6.11.1/Google-Mobile-Ads-SDK.podspec.json)
* [GoogleAppIndexing](https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleAppIndexing/2.0.3/GoogleAppIndexing.podspec.json)
* [Optimizely-iOS-SDK](https://github.com/CocoaPods/Specs/blob/master/Specs/Optimizely-iOS-SDK/1.5.0/Optimizely-iOS-SDK.podspec.json)
* [RFMAdSDK](https://github.com/CocoaPods/Specs/blob/master/Specs/RFMAdSDK/4.2.0/RFMAdSDK.podspec.json)
* [Reveal-iOS-SDK](https://github.com/CocoaPods/Specs/blob/master/Specs/Reveal-iOS-SDK/1.6.2/Reveal-iOS-SDK.podspec.json)

**Comment by plu** [comment]
See also:

* https://raw.githubusercontent.com/plu/SearchPath/master/Pods/Target%20Support%20Files/Pods-SearchPath/Pods-SearchPath.debug.xcconfig

vs.

* https://raw.githubusercontent.com/plu/SearchPath/master/Pods/Target%20Support%20Files/Pods-SearchPathTests/Pods-SearchPathTests.debug.xcconfig

**Comment by plu** [comment]
I found the reason why these dependencies are skipped:

https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb#L243

It filters for dependent targets that should build something. Removing this `.select(&:should_build?)` filter fixes this issue, but I'm not sure what else it will break instead :).

**Comment by plu** [comment]
And I found a fix. Side effects unknown yet ;)

**Comment by plu** [comment]
After applying the fix, the changes in the given sample project look like this (and it is building the test target without error):

```diff
diff --git a/Pods/Target Support Files/Pods-SearchPathTests/Pods-SearchPathTests.debug.xcconfig b/Pods/Target Support Files/Pods-SearchPathTests/Pods-SearchPathTests.debug.xcconfig
index f4e42de..4de062c 100644
--- a/Pods/Target Support Files/Pods-SearchPathTests/Pods-SearchPathTests.debug.xcconfig	
+++ b/Pods/Target Support Files/Pods-SearchPathTests/Pods-SearchPathTests.debug.xcconfig	
@@ -1,8 +1,9 @@
-FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/1PasswordExtension"
+FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/1PasswordExtension" "${PODS_ROOT}/Google-Mobile-Ads-SDK/Frameworks"
 GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
 HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Google-Mobile-Ads-SDK"
 LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
 OTHER_CFLAGS = $(inherited) -iquote "$PODS_CONFIGURATION_BUILD_DIR/1PasswordExtension/OnePasswordExtension.framework/Headers" -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/Google-Mobile-Ads-SDK"
+OTHER_LDFLAGS = $(inherited) -framework "AVFoundation" -framework "AudioToolbox" -framework "CoreBluetooth" -framework "CoreGraphics" -framework "CoreMedia" -framework "CoreTelephony" -framework "EventKit" -framework "EventKitUI" -framework "GoogleMobileAds" -framework "MediaPlayer" -framework "MessageUI" -framework "StoreKit" -framework "SystemConfiguration" -weak_framework "AdSupport" -weak_framework "SafariServices"
 PODS_BUILD_DIR = $BUILD_DIR
 PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
 PODS_ROOT = ${SRCROOT}/Pods
diff --git a/Pods/Target Support Files/Pods-SearchPathTests/Pods-SearchPathTests.release.xcconfig b/Pods/Target Support Files/Pods-SearchPathTests/Pods-SearchPathTests.release.xcconfig
index f4e42de..4de062c 100644
--- a/Pods/Target Support Files/Pods-SearchPathTests/Pods-SearchPathTests.release.xcconfig	
+++ b/Pods/Target Support Files/Pods-SearchPathTests/Pods-SearchPathTests.release.xcconfig	
@@ -1,8 +1,9 @@
-FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/1PasswordExtension"
+FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/1PasswordExtension" "${PODS_ROOT}/Google-Mobile-Ads-SDK/Frameworks"
 GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
 HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Google-Mobile-Ads-SDK"
 LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
 OTHER_CFLAGS = $(inherited) -iquote "$PODS_CONFIGURATION_BUILD_DIR/1PasswordExtension/OnePasswordExtension.framework/Headers" -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/Google-Mobile-Ads-SDK"
+OTHER_LDFLAGS = $(inherited) -framework "AVFoundation" -framework "AudioToolbox" -framework "CoreBluetooth" -framework "CoreGraphics" -framework "CoreMedia" -framework "CoreTelephony" -framework "EventKit" -framework "EventKitUI" -framework "GoogleMobileAds" -framework "MediaPlayer" -framework "MessageUI" -framework "StoreKit" -framework "SystemConfiguration" -weak_framework "AdSupport" -weak_framework "SafariServices"
 PODS_BUILD_DIR = $BUILD_DIR
 PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
 PODS_ROOT = ${SRCROOT}/Pods
```

**Comment by wafisher** [comment]
Are there any updates on this? This seems like a not-insignificant bug — if you want a test target and you have non-open source code, you'll run into this, as I am now. Would at least love a quick fix to get those vendored frameworks inherited. Thanks!

**Comment by orta** [comment]
There is a pull request linked to in this thread, https://github.com/CocoaPods/CocoaPods/pull/5514 - it's being blocked on adding tests 👍 - you're welcome to take a stab at adding some of those

**Comment by vogonistic** [comment]
Until this is released, what is the workaround?
