### ISSUE TITLE
Irrelevant information in the log

### ISSUE THREAD

**Issue by Antondomashnev** [CocoaPods/CocoaPods#5513]
Hi there,

In the log while doing some action with CocoaPods and new version is available user will see the message:
"Until we reach version 1.0 the features of CocoaPods can and will change.
We strongly recommend that you use the latest version at all times."

I can see that message even if my version is 1.0.0, so I think it can be removed from the log output in case the installed version of CocoaPods is >= 1.0

**Comment by manuyavuz** [comment]
This is fixed in 1.0.1, you can update to last version with `gem install cocoapods`.
