### ISSUE TITLE
When using integrate_targets => false, note in install workspace file not created

### ISSUE THREAD

**Issue by xin-savysoda** [CocoaPods/CocoaPods#5517]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
Run `pod install`

## What did you expect to happen?
expected workspace file to be generated

## What happened instead?
workspace file wasnt created, but a message should of notified me

**Comment by DanToml** [comment]
Please can you provide steps to reproduce, including a sample project that reproduces the issue?

**Comment by segiddins** [comment]
That's intended behavior when not integrating targets.

**Comment by orta** [comment]
This issue is about changing our messaging slighting when using  `:integrate_targets => false` ( I was in the WWDC labs at the time and spotted the issue. )

Currently it looks like this, and the absence of `Integrating client project` implies what's going on

e.g.

```
Analyzing dependencies
Downloading dependencies
Using AsyncSwift (1.7.2)
Using FileKit (2.0.0)
Using Interstellar (1.4.0)
Using Nimble (4.0.0)
Using PXSourceList (2.0.7)
Using Quick (0.9.1)
Generating Pods project
Sending stats
Pod installation complete! There are 6 dependencies from the Podfile and 6 total pods
installed.
```

I wonder if instead we make it say:

```
Analyzing dependencies
Downloading dependencies
Using AsyncSwift (1.7.2)
Using FileKit (2.0.0)
Using Interstellar (1.4.0)
Using Nimble (4.0.0)
Using PXSourceList (2.0.7)
Using Quick (0.9.1)
Generating Pods project
Skipping client integration
Sending stats
Pod installation complete! There are 6 dependencies from the Podfile and 6 total pods
installed.
```

then the intention is clearer, what do you think?

**Comment by neil477** [comment]
@orta for what it's worth I like that messaging change, would've helped me save some time.

**Comment by segiddins** [comment]
👍 adding that shouldn't be too difficult, something along these lines would work:

```diff
diff --git a/lib/cocoapods/installer.rb b/lib/cocoapods/installer.rb
index 6138762..602cd56 100644
--- a/lib/cocoapods/installer.rb
+++ b/lib/cocoapods/installer.rb
@@ -114,7 +114,11 @@ module Pod
       verify_no_static_framework_transitive_dependencies
       verify_framework_usage
       generate_pods_project
-      integrate_user_project if installation_options.integrate_targets?
+      if installation_options.integrate_targets?
+        integrate_user_project
+      else
+        UI.section 'Skipping client integration'
+      end
       perform_post_install_actions
     end
 ```

**Comment by orta** [comment]
^ 👍
