### ISSUE TITLE
[Xcode 8 beta] pod spec lint: "iPhone 4s is not available"

### ISSUE THREAD

**Issue by gooner22** [CocoaPods/CocoaPods#5519]
# Report

## What did you do?

Trying to lint pod spec with Xcode 8 beta

'pod spec lint $SPEC_PATH --verbose'

## What did you expect to happen?

Lint runs just fine

## What happened instead?

    - ERROR | [iOS] unknown: Encountered an unknown error (Simulator iPhone 4s is not available.) during validation.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A201w)
       Xcode : 8.0 (8S128d)
         Git : git version 2.8.1 (Apple Git-69)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4af6f57bafa9d9c22206a0a794801b5126987902
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
slather               : 2.2.0
```

The reason for that I think is that iPhone 4s has been removed in iOS 10

**Comment by k3zi** [comment]
I'm seeing some correlation with #5515 having an issue with iPhone 4s not supporting iOS 10. Their issue was resolved after downloading the 9.3 simulator. (So `lint` can switch to 9.3 for the 4s). Could you give that a try?

**Comment by gooner22** [comment]
@k3zi you're right. 
Both lint and push work as expected with 9.3 simulator installed.

**Comment by waitingfor168** [comment]
add Simulator iPhone 4s

**Comment by bch007** [comment]
add Simulator iOS 9.3

**Comment by fenglinxiu** [comment]
@waitingfor168 how to add ? Please explain it in detail, thanks.

**Comment by waitingfor168** [comment]
Xcode->Window->Devices->。。。

**Comment by fenglinxiu** [comment]
@waitingfor168 Thank you

**Comment by talezion** [comment]
@fenglinxiu Easy way to add through Xcode, is to install either 8.x/9.x SDK

<img width="755" alt="Xcode 8.0" src="https://cloud.githubusercontent.com/assets/1576575/19268766/fb5817ea-8fbe-11e6-82e0-0f5b244c7c8f.png">

**Comment by fenglinxiu** [comment]
@talezion thanks a lot. I have found it.

**Comment by edthereaper** [comment]
OMG!!! I have the same issue here, found when i build in swift 3.x with a iPhone 4s v8.x... always find problems with all libraries, but with v9.x works everything ok

Thanks mates

**Comment by littlepod** [comment]
I get this issue when I do lint for my podspec file
$pod spec lint
---------------
- ERROR | [iOS] unknown: Encountered an unknown error (/usr/bin/xcrun simctl list -j devices

2017-01-10 10:47:25.337 simctl[7569:724483] CoreSimulator is attempting to unload a stale CoreSimulatorService job.  Detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Applications/Xcode8.0.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework) and version (303.8) does not match existing job path (/Applications/Xcode8.1.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc) and version (307.14.2).
2017-01-10 10:47:25.591 simctl[7569:724483] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.
---------------
If you can guide please?

**Comment by benasher44** [comment]
@littlepod That doesn't look like something we could fix by patching CocoaPods. I recommend opening an issue on Stackoverflow, and I'm sure some knowledgeable folks can help out!
