### ISSUE TITLE
Codesigning in Xcode 8

### ISSUE THREAD

**Issue by opswhisperer** [CocoaPods/CocoaPods#5523]
* [ x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` or `pod update`

## What happened instead?

Pods are installed but there is no Development Team set. You must select every target in the Pods project and set the team

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A201w)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fdeab0150c4f811dc33db08c74e66cb75b54697e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!
Target 'some appt' do
pod 'Onboard'
pod 'Localytics'
pod 'BuddyBuildSDK'
pod 'Doorbell'
pod 'Google/Analytics'
pod "LaunchKit"
pod "Branch"
pod 'Charts', :git => "https://github.com/opswhisperer/Charts.git", :branch => "xcode8_swift23"
pod "AFNetworking"
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'iRate'
pod 'GoogleConversionTracking'
pod 'UIBarButtonItem-Badge', :git => "https://github.com/mikeMTOL/UIBarButtonItem-Badge.git"
pod 'GoogleIDFASupport'
end
```

## Project that demonstrates the issue

any project

**Comment by opswhisperer** [comment]
I've been looking but I don't see a way to handle this in a post_install hook. I see I can change build configurations pods_project.targets but not the `DevelopmentTeam` and `DevelopmentTeamName` of the actual project.pbxproj

**Comment by opswhisperer** [comment]
Is there anything I can do to help this along? While I have a manual work around to set a development team, this is breaking my CI builds. Perhaps there is some post_install foo I haven't figured out yet?

**Comment by segiddins** [comment]
@opswhisperer can you test out https://github.com/CocoaPods/CocoaPods/issues/5528 ?

**Comment by opswhisperer** [comment]
Tested, works great

**Comment by sssuourabh** [comment]
Select each target in pod and select the team in General tab section 
It resolve the problem
