### ISSUE TITLE
Mixed transitive dependencies

### ISSUE THREAD

**Issue by lzanol** [CocoaPods/CocoaPods#5526]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I have a media player library written in **Swift** with the given `podspec`:

```
s.preserve_paths = 'Vendor'
s.vendored_frameworks = 'Vendor/GoogleInteractiveMediaAds.framework'
s.dependency 'Alamofire', '~> 3.4'

s.source_files = 'Source/*.swift', 'Vendor/GoogleMediaFramework'
s.resources = 'Vendor/GoogleMediaFramework/Resources/**'
```

Notice that I have mixed dependencies (local Swift + ObjC code, bundled `.framework` dep, remote Swift dep).

Then I ran `pod lib lint`.
## What did you expect to happen?

To have a valid lib/podspec and `pod` properly finding its subdependencies as such:
- [GMF](https://github.com/googleads/google-media-framework-ios) (ObjC interoperable code)
- [IMA](https://developers.google.com/interactive-media-ads/docs/sdks/ios/) (ObjC `.framework`)
- [Alamofire](https://github.com/Alamofire/Alamofire) (Swift code)
## What happened instead?

It cannot find GMF files:

```
ERROR | xcodebuild:  /Users/zanol/projects/player-sdk-ios/Vendor/GoogleMediaFramework/GMFContentPlayhead.h:3:9: error: 'GoogleMediaFramework/GoogleMediaFramework.h' file not found
```
### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.6.4
Ruby lib dir : /Users/zanol/.rvm/rubies/ruby-2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4ff8046a464a019437c2bb4242ae55c407fe0f91
```
### Installation Source

```
Executable Path: /Users/zanol/.rvm/gems/ruby-2.2.2/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
## Project that demonstrates the issue

Unfortunately I wasn't able to publish it yet due to these issues.

**Comment by neonichu** [comment]
`vendored_frameworks` are linked against your application target, not the current Pod

**Comment by lzanol** [comment]
@neonichu By that, do you mean `pod lib lint` isn't able to validate a `podspec` when using `vendored_frameworks`?

By the way, given such mixed deps scenario, is there maybe a better approach I could go for? What's your recommendation?

**Comment by DanToml** [comment]
It looks like you are including the sources of Vendor/GoogleMediaFramework directly in your Pod, so they will be in the Pod module, not GoogleMediaFramework.
