### ISSUE TITLE
how to use -foceload with CocoaPods

### ISSUE THREAD

**Issue by ceekay1991** [CocoaPods/CocoaPods#5532]
how to use -foceload with CocoaPods

**Comment by orta** [comment]
Can you please fill this issue out more, there' not really any context here.

**Comment by ceekay1991** [comment]
我的问题是【pod 'Masonry','~> 1.0.1' Masonry 包含扩展有扩展, Other Link Flags 如何使用-force_load?】,现在的做法是加上-force_load "${TARGET_BUILD_DIR}/libMasonry.a" （工程里有公司内部的2个库都包含a.m，不能用all_load,-Objc ）。如果pod引用了10个都有扩展的库，那得加十个-force_load。有没有更好的办法解决这个问题？

**Comment by ceekay1991** [comment]
My question is [pod 'Masonry', '~> 1.0.1' Masonry contains category, Other Link Flags how to config  -force_load?], The current practice is to add -force_load "$ {TARGET_BUILD_DIR} /libMasonry.a" (In my project, there are two internal library contains a.m, can not be used all_load, -Objc). If the pod has cited 10 extension library that was added ten -force_load. Is there a better way to solve this problem?

**Comment by orta** [comment]
You can make CocoaPods apply all load and force load via [a podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/ZDPageNavigationController/0.1.2/ZDPageNavigationController.podspec.json#L24) - you may need a custom podspec if you need to do this.

**Comment by ceekay1991** [comment]
how to config Podfile with "-force_load"?
