### ISSUE TITLE
Living with 0.37.1 and 1.0.1 

### ISSUE THREAD

**Issue by maschall** [CocoaPods/CocoaPods#5538]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I am working on a project and we want to update to 1.0.1 Cocoapods for our next release, however this means that we need to keep using 0.37.1 until that release goes out.

I am curious on if we need to maintain two CI servers when the Spec repo is sharded?  

If we update the 'master' repo by running 1.0.1 cocoapods, will be breaking the repository for running with 0.37.1, when the shard changes happen?

**Comment by segiddins** [comment]
You can manually checkout the (I believe it will be ) 0.34 tag once we shard.
