### ISSUE TITLE
Ruby 1.9.3 install external podspec

### ISSUE THREAD

**Issue by netbe** [CocoaPods/CocoaPods#554]
Hi,

I've tried to install an external podspec hosted on github as a gist, and the install failed with the following error:

`SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

I've tried with Ruby 1.8.7 and it worked without any issues.

Thanks for your help

**Comment by ashokds** [comment]
@alloy, @netbe 

Same issue, Just following worked, didn't need to download fresh certificates
`require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE`

`~ $openssl version
OpenSSL 0.9.8zg 14 July 2015
~ $pod --version
1.0.1
~ $ruby -v
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]`

Thanks.
