### ISSUE TITLE
Add command to bump the version

### ISSUE THREAD

**Issue by Haroenv** [CocoaPods/CocoaPods#5544]
🌈 I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```sh
$ # edit version number in podspec
$ git commit -am "v0.1.0"
$ git tag v0.1.0
$ git push
$ git push --tags
$ pod trunk push NAME.podspec
```

## What did you expect to happen?

I expected to be able to run something like `pod lib version` which would do all those steps (à la `npm`)

## What happened instead?

I had to write 5 commands and open a text editor

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2a4227e02f17d20019c1ec3fb2609bdd3e3f652d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

Every project has this issue.

**Comment by orta** [comment]
Thanks, this is already available as a plugin ATM - https://github.com/CocoaPods/cocoapods-plugins/blob/master/plugins.json#L136

We opted to keep it there, not everyone uses git 👍

**Comment by Haroenv** [comment]
Aha, thanks for listing that plugin. I'll use it
