### ISSUE TITLE
None of your spec sources contain a spec satisfying the dependencies

### ISSUE THREAD

**Issue by shalem93** [CocoaPods/CocoaPods#5545]
# Report

## What did you do?

Ran pod install, have attempted to remove Podfile.lock, Pods/, etc. Set the deployment target equal to iOS min version. Nothing seems to work, have tried most all past steps from old open cases. There doesn't seem to be anything to help fix this newer error message, just comments about the wording of the error messages!

## What did you expect to happen?
The pod install to work and my Xcode Project to Build

## What happened instead?
Continue to get this error message over and over:
[!] Unable to satisfy the following requirements:

- `Quickblox-WebRTC` required by `Podfile`
- `Quickblox-WebRTC (= 2.2)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `Quickblox-WebRTC, Quickblox-WebRTC (= 2.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

## CocoaPods Environment
1.0

**Comment by orta** [comment]
Did you note this part of the error message:

> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

and run `pod repo update`?

**Comment by shalem93** [comment]
yes, i ran pod repo update and problem still persists

**Comment by orta** [comment]
Can you share your Podfile please? I guess the only other thing could be that you don't have the CocoaPods specs repo in there

**Comment by shalem93** [comment]
# Uncomment this line to define a global platform for your project
# platform :ios, '8.1'
inhibit_all_warnings!

target 'Xpandu' do
    pod 'AFNetworking', '~> 2.5'
    pod 'SVProgressHUD', '~> 1.1'
    pod 'TPKeyboardAvoiding', '~> 1.2.3'
    pod 'QuickBlox'
    pod 'Quickblox-WebRTC'
    pod 'Heap', '~> 3.0'
    pod 'MISDropdownViewController'
    pod 'ChimpKit'
    pod 'SBJson', '~> 4.0.0'
end

**Comment by segiddins** [comment]
I cannot reproduce the issue with the provided Podfile

**Comment by shalem93** [comment]
Figured it out, pretty much followed this: http://stackoverflow.com/questions/34509310/cocoapods-pod-update-installs-old-pods

**Comment by WCL-LV** [comment]
you can try to delete Podfile.lock

**Comment by ooopscc** [comment]
@Juice007 @segiddins  Thanks, it works. But I want to know why. Still has this problem in 1.5.3

**Comment by ArturKvaratshelia** [comment]
@shalem93 I think in this case some of pod used in your podfile, also used inside pod. Try use "pod update", or synchronize both versions of used pods. 
For example I have been used SDWebImage that I think uses KSPhotoBrowser. And I also use KSPhotoBrowser in my podfile. I just synchronized versions of KSPhotoBrowser and issue resolved.
My error:
`
[!] CocoaPods could not find compatible versions for pod "SDWebImage/GIF":
  In Podfile:
    KSPhotoBrowser was resolved to 0.2.5, which depends on
      SDWebImage/GIF

None of your spec sources contain a spec satisfying the dependency: `SDWebImage/GIF`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
`

**Comment by NicholasMunson** [comment]
Removing cocoapods and reinstalling the gem allowed me to pod install when `pod repo update` failed. 

 `rm -rf ~/.cocoapods`
`sudo gem install cocoapods`
`pod install`

**Comment by OmarBasem** [comment]
Whenever publishing a new version for one of my cocoa pods, it takes forever for "pod install" to find it. "pod repo update" and "pod install --repo-update" do not fix the problem.

**Comment by spiderion** [comment]
for M1 :
 arch -x86_64 sudo gem install ffi
 arch -x86_64  pod install

worked for me

**Comment by daman-talkshoplive** [comment]
"pod deintegrate"
"pod update"

worked!
