### ISSUE TITLE
Slow local path'd pod install integration when path falls outside the project's directory 

### ISSUE THREAD

**Issue by mattyohe** [CocoaPods/CocoaPods#5546]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?
`pod install` with a locally `:path`'d dependency

## What did you expect to happen?
The operation should complete in a timely manner.

## What happened instead?
Integration of a single pod (Alamofire) took upwards of 15-20 seconds.

## Further Information
This first appeared as I attempted to fork and fix a public podspec. I noticed that integration was taking much too long as compared to integration with a remotely hosted podspec. Below in `Project that demonstrates the issue` I have included a link to a project that times different integrations.

Side note: I see that I have a few cocoapods plugins installed as well, I'm not sure if these are causing issues, but I will disable them and report back.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.4
Ruby lib dir : /Users/mattyohe/.rubies/2.2.2/lib
Repositories : CocoaPods-InternalSpecs - git@github.com:XXXXXXX/CocoaPods-InternalSpecs.git @ 904b4fc11f1904920f24fc20fc21feafcd5a145e
               master - https://github.com/CocoaPods/Specs.git @ 5d21b9faddef22a13ebdc99f0866b7d71e06b899
               XXXXXXX - https://github.com/XXXXXXX/XXXXXXX-cocoapods.git @ 574c6f6a756024c66aeb2364abdcbdc814fff9bb
```

### Installation Source

```
Executable Path: /Users/mattyohe/.gem/ruby/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate    : 1.0.0
cocoapods-no-dev-schemes : 1.0.0
cocoapods-plugins        : 1.0.0
cocoapods-search         : 1.0.0
cocoapods-stats          : 1.0.0
cocoapods-trunk          : 1.0.0
cocoapods-try            : 1.0.0
slather                  : 2.2.1
```

### Podfile

```ruby
target 'SlowIntegration' do
    use_frameworks!
    #pod 'Alamofire'
    pod 'Alamofire', path: '/Users/mattyohe/Desktop/Alamofire.podspec.json'
end
```

## Project that demonstrates the issue
https://github.com/mattyohe/SlowIntegration

This project contains the script I was running to output integration, and also to time each method of integration. That script is at the root of the repo titled `time_integration.sh` and it shows output in each different integration case with the time to integrate appended.

https://github.com/mattyohe/SlowIntegration/blob/remote-podspec/output.txt - 2.862s ✅
https://github.com/mattyohe/SlowIntegration/blob/expand-home/output.txt - 25.952s 😭
https://github.com/mattyohe/SlowIntegration/blob/same-relative-dir/output.txt - 1.680s ✅
https://github.com/mattyohe/SlowIntegration/blob/explicit-folder/output.txt - 19.309s 😭

Note in each of these, the only things changing are the location of the podspec. The two fastest runs being the remote podspec, and when the podspec was in the same relative directory as the project.

**Comment by segiddins** [comment]
The two slow examples were only a few seconds each for me.


### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.8.1
Ruby lib dir : /Users/segiddins/.rubies/2.3.1/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 74555e9d6a1aeceddf675c2cc1fa8f9e0b740d34
               buithuyen - https://github.com/buithuyen/Specs.git @ a6e6fe0cef7644fe55139842bf8529013f9821dc
               calgaryscientific - https://github.com/calgaryscientific/pureweb-ios-cocoapods @ e2d88e911e4939ba44fe0396a3d7ece90aa91eff
               eyeem - https://github.com/eyeem/CocoaPods-Specs.git @ e5d20deb9c06d8557bec7bb8659155ac41313f96
               master - https://github.com/CocoaPods/Specs.git @ cb9196193ca889c6af166c7d6440a2c49f331cd5
               unityappstudio - https://github.com/unityappstudio/Specs.git @ 4c5d9046d47906df7b3bafa6641cb4e752f057a7
```

### Installation Source

```
Executable Path: /Users/segiddins/Development/Rainforest/CocoaPods/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.0.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
target 'SlowIntegration' do
    use_frameworks!
    #pod 'Alamofire'
    pod 'Alamofire', path: '/Users/segiddins/Desktop/Alamofire.podspec.json'
end
```

**Comment by mattyohe** [comment]
Updated ruby to match yours @segiddins. Similar results on the `explicit-folder` branch.
`pod install --verbose 2>&1 > output.txt  18.19s user 5.32s system 93% cpu 25.035 total`

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.4
Ruby lib dir : /Users/mattyohe/.rubies/2.3.1p112/lib
Repositories : CocoaPods-InternalSpecs - git@github.com:XXXXXXX/CocoaPods-InternalSpecs.git @ 904b4fc11f1904920f24fc20fc21feafcd5a145e
               master - https://github.com/CocoaPods/Specs.git @ 3065a9ae7e3081be9b5fad5523a51dc302de282e
               XXXXX - https://github.com/XXXX/XXXX-cocoapods.git @ 574c6f6a756024c66aeb2364abdcbdc814fff9bb
```

### Installation Source

```
Executable Path: /Users/mattyohe/.gem/ruby/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
target 'SlowIntegration' do
    use_frameworks!
    #pod 'Alamofire'
    pod 'Alamofire', path: '/Users/mattyohe/Desktop/Alamofire.podspec.json'
end
```

**Comment by segiddins** [comment]
`pod install --verbose 2>&1 > output.txt  1.63s user 0.71s system 84% cpu 2.770 total` for me 🤔 I honestly don't know why it'd be so much slower for you

**Comment by mattyohe** [comment]
I'm willing to spelunk a bit, but I am not a rubyist, so any guidance into tools I could use to explore where time is being spent I would happily run.

**Comment by neonichu** [comment]
Closing this, because I don't think there unfortunately isn't anything actionable we can do here.
