### ISSUE TITLE
Introduce --use-legacy-linter for linting

### ISSUE THREAD

**Issue by Aaang** [CocoaPods/CocoaPods#5548]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
We've recently upgraded to the long expected CocoaPods 1.0.0 version, which is really awesome. It works like a charm for all our pods, except one.

Reason: this is a pod in which we're using  React Native. In order to publish this pod including the React Native source files and use it in Apps, we created static libraries for all the required React Native sources. This turns out to be a problem when releasing a new pod for an Apple submission of an App using this very pod, because **we can only add the device slices** for the React Native source files to the static library for submission.

This means linting with CocoaPods 1.0.0 fails due to the missing Simulator slices for the new approach of actually building a test app in the Simulator and we can't do anything about it.

## What did you expect to happen?
Linting succeeds by using the legacy linting approach with a flag like `--use-legacy-linter`.

## What happened instead?
Linting fails, it's the expected behavior with the current implementation though.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p594 (2014-10-27 revision 48167) [x86_64-darwin13.4.0]
    RubyGems : 2.4.3
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/XXX/.rvm/rubies/ruby-2.0.0-p594/lib
Repositories : facebook - https://github.com/facebook/react-native @ cdb86a6589a1dbf26f6038091b4976b07f84baaf
               master - https://github.com/CocoaPods/Specs.git @ 5f65e7de65f07278cebffd0d38ff31373a27d49b
               XXX
```

### Installation Source

```
Executable Path: /Users/XXX/.rvm/gems/ruby-2.0.0-p594/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by segiddins** [comment]
I'd rather we fix the linter to actually work -- why is it your pod can't build for the simulator, exactly?

**Comment by Aaang** [comment]
Thank you for the quick response.

We use static libraries which only contain device slices (armv7, arm64), because if the static libraries would also contain Simulator slices (i386, x86_64) we would get rejected by Apple (see [Open Radar)](http://www.openradar.me/radar?id=6409498411401216)).

This means the React Native header files cannot be linked in the Simulator environment and therefore the build fails.

Here's a generic version of our .podspec just for a better understanding:
````
Pod::Spec.new do |s|
  s.name                  = 'our-react-native-pod'
  s.version               = '0.0.1'
  s.summary               = 'A library to provide some React Native features.'
  s.author                = { 'XXX' => 'email@domain.com' }
  s.license               = { :type => 'Proprietary', :text => 'XXX' }
  s.source                = { :git => 'ssh://git@XXX', :tag => s.version.to_s }

  s.platform              = :ios, '8.0'
  s.ios.deployment_target = '8'
  s.compiler_flags        = '-Werror' # Turn warnings into errors
  s.frameworks	          = 'Foundation'

  s.header_dir            = 'MyReactNativePod'
  s.source_files          = 'ios/someFeature/Classes/**/*.{h,m}',
  s.resources             = 'ios/someResources/FeatureResources.bundle'
  s.public_header_files   = 'ios/someFeature/Classes/*.{h}'

  s.libraries             = "React", "RCTImage", "RCTLinking", "RCTNetwork", "RCTText", "RCTWebSocket" # the React Native libraries we're currently using and building as static libs
  s.preserve_paths        = 'ios/ReactNativeLibraries'
  s.xcconfig              = {
                              "LIBRARY_SEARCH_PATHS" => "$(PODS_ROOT)/our-react-native-pod/ios/ReactNativeLibraries",
                              "HEADER_SEARCH_PATHS" => "$(PODS_ROOT)/our-react-native-pod/ios/ReactNativeLibraries/include/**"
                            }

  # Dependencies
  s.dependency   'some-other-dependency',                    '~> 1.0.0'
end
````

**Comment by segiddins** [comment]
Why not just depend upon the `React` pod?

**Comment by neonichu** [comment]
The radar you're linking to is only relevant for dynamic frameworks, when using static libraries, the unused slices will get dropped automatically.

**Comment by Aaang** [comment]
@segiddins unfortunately the current `React` pod is totally outdated and deprecated.
@neonichu thank you very much, I've missed this important fact! This would fix the problem, I'll double check this again.

So do you think providing the legacy linter functionality would make sense or would you discourage introducing this option and stick to the new approach, which is actually awesome?

**Comment by segiddins** [comment]
I'd like to hold out a bit longer and wait until there's something that _cannot_ be worked around with the new linter before adding a way to easily opt out of using it

**Comment by Aaang** [comment]
Alright, makes sense.

Thank you very much for the great support.
I'll close this issue then.
