### ISSUE TITLE
A valid provisioning profile for this executable was not found.

### ISSUE THREAD

**Issue by iTofu** [CocoaPods/CocoaPods#5549]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
Run `pod install` in my project.

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
Import the rep what I need. And than run OK.

## What happened instead?

ℹ Please replace this with of what happened instead.  
Before I create Podfile file and run `pod install`, runs OK.
After I create Podfile file and run `pod install`, I clicked Run button, it show "App installation failed" and "A valid provisioning profile for this executable was not found."

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by iTofu** [comment]
Xcode 7.3.1
Pod 1.0.0
On my iPhone 6 s (iOS 9.3.2) and iPhone 5 s (iOS 9.3.2)

**Comment by orta** [comment]
This looks like a problem with your Xcode setup for provisioning profiles - I'd recommend reading up on how they all work: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ProvisioningDevelopment.html

**Comment by iTofu** [comment]
Maybe not...
Before I create Podfile file and run pod install, runs OK.
After I create Podfile file and run pod install, I clicked Run button, it show "App installation failed" and "A valid provisioning profile for this executable was not found."...

**Comment by TonnyTao** [comment]
+1

**Comment by mingming1222** [comment]
+1

**Comment by wao813** [comment]
+1

**Comment by kuwait** [comment]
+1

**Comment by crixalves** [comment]
+1

**Comment by Samigos** [comment]
+1

**Comment by orta** [comment]
If you are having this problem, a well written explanation of your problem in a new issue and ways in which it can be reproduced would be significantly more useful than a plus one.
