### ISSUE TITLE
Cocoapods 1.0.1 sets wrong deployment target version for some pods

### ISSUE THREAD

**Issue by Voley** [CocoaPods/CocoaPods#5552]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
One of my pods (MBProgressHUD) started working in a wrong way. After some research I have found that this happens due to wrong deployment target set for this pod by Cocoapods. 

Add 'MBProgressHUD' to your project, do pod install.
After that navigate to its setting in pods, and check Deployment target.
[Image of settings](http://i.imgur.com/HD8WYZQ.png)

## What did you expect to happen?
I expected deployment target to match the deployment target in their podspec file (6.0)
[Podspec link](https://github.com/jdg/MBProgressHUD/blob/master/MBProgressHUD.podspec)

## What happened instead?

What happened is that it has 4.3 deployment target. There are some checks inside the code of pod and that essentially breaks it.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d0b6ad229874ae3e88d8172641e62fa321386887
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '8.0'

inhibit_all_warnings!

abstract_target 'Core' do
    pod 'MBProgressHUD'

    target 'myapp-iOS-Dev' do
	end

    target 'myapp-iOS' do 
    end 
    
    target 'myapp-iOSTests'  do
    end
        
    target 'myapp-iOSUITests' do
    end
    
end
```

**Comment by segiddins** [comment]
The latest released version of MBProgressHUD does not specify a deployment target for iOS. https://github.com/CocoaPods/Specs/blob/master/Specs/MBProgressHUD/0.9.2/MBProgressHUD.podspec.json
