### ISSUE TITLE
Xcode found bundle with the same identifier using cocoapods frameworks

### ISSUE THREAD

**Issue by WXGBridgeQ** [CocoaPods/CocoaPods#5556]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
XCode found bundle with the same identifier using cocoapods frameworks

## What did you do?
`pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
My problem is same as this one, http://stackoverflow.com/questions/35378833/xcode-found-bundle-with-the-same-identifier-using-cocoapods-frameworks
I'm using Jenkins for CI, and our build command set the `PRODUCT_BUNDLE_IDENTIFIER` and `PROVISIONING_PROFILE`, I think that's why we have problem. Just want to know how to fix it correctly. 

## CocoaPods Environment
1.0.1

```
platform :ios, '8.0'
use_frameworks!

target 'XXXX' do
  pod 'Alamofire', '~> 3.2.1'
  pod 'MJRefresh', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'Fabric', '~> 1.6.7'
  pod 'Crashlytics', '~> 3.7.0'
  target 'XXXX Tests' do
      inherit! :search_paths
  end
end
```

**Comment by segiddins** [comment]
what command are you using to build?

**Comment by WXGBridgeQ** [comment]
```
xcodebuild clean archive -workspace XXXX.xcworkspace -scheme XXXX -configuration Release -archivePath /tmp/xxxx.xcarchive -destination generic/platform=iOS PROVISIONING_PROFILE=xxxx PRODUCT_BUNDLE_IDENTIFIER=xxxx -derivedDataPath /tmp
```

**Comment by segiddins** [comment]
there's no way around it, the build settings passed via `xcodebuild` are used for all targets -- you might want to look into using xcconfigs to customize your build settings instead?

**Comment by WXGBridgeQ** [comment]
ok, thanks for your answer, I will try

**Comment by Abhishek9634** [comment]
Please help i have facing this issue

![screen shot 2016-08-20 at 4 54 05 pm](https://cloud.githubusercontent.com/assets/10388287/17830855/db127af2-66f6-11e6-9350-e09e543fbde3.png)
