### ISSUE TITLE
[Feature request] Choose the Podfile when pod installing/updating

### ISSUE THREAD

**Issue by colasbd** [CocoaPods/CocoaPods#5557]
I am maintaining a project where I have two `Podfile`: one for development (with direct link to my private pods) and one for release (with link to the versioned private pods).

It would be nice if I could do something like:
`pod update Podfile_dev` or `pod update Podfile_release`

Thanks

**Comment by neonichu** [comment]
Not sure if it makes sense as a feature, but you could achieve this by evaluating an environment variable in your Podfile and specifying Pods based on that, as the Podfile can contain any arbitrary Ruby.

**Comment by segiddins** [comment]
Yeah, I think doing this in ruby is going to be our answer for now -- this seems like a feature with very limited application with the potential to make things way more confusing for people.

**Comment by colasbd** [comment]
I think it is not a feature complicated to implement and not at all confusing for people. Just do as usual but if you want to name your Podfile differently, you can do it.
