### ISSUE TITLE
'Allow app extension API only' not set for new messages extension

### ISSUE THREAD

**Issue by ConfusedVorlon** [CocoaPods/CocoaPods#5558]
# Report

I am currently developing a Messages extension using some cocoa pods. The "Allow app extension API only" checkbox for a is not set for a messages extension.

Presumably, the detection code needs to be updated for the new extension types in iOS 10 similar to #3153

## What did you do?

Create app with messages template in Xcode 8.0 (beta)
Add a single pod
Build

## What did you expect to happen?

Unicorns and daisies

## What happened instead?

```ld: warning: linking against a dylib which is not safe for use in application extensions: .../Build/Products/Debug-iphonesimulator/PureLayout/PureLayout.framework/PureLayout```

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.3
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/rob/.rvm/rubies/ruby-2.3.0/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 052980aae9e417149d5e1e9c67b45f88101925b5
```

### Installation Source

```
Executable Path: /Users/rob/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
	pod 'PureLayout', '~> 3.0'
end

target 'Message' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Message
	shared_pods
end

target 'STMPR' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STMPR
  shared_pods

end
```

`

**Comment by neonichu** [comment]
Makes sense, they probably have a new product type
