### ISSUE TITLE
Build targets are missing from generated workspace file. Cocoapods 1.0.1

### ISSUE THREAD

**Issue by neitzj** [CocoaPods/CocoaPods#5563]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I upgraded to cocoapods 1.0.1

sudo gem install cocoapods

Then I updated my Podfile as per the new guidelines

**Old file:**
source 'https://github.com/CocoaPods/Specs.git'
workspace './PureWebFramework'

use_frameworks!

link_with 'FrameworkTests'
xcodeproj 'Framework.xcodeproj', 'Framework' => :release, 'FrameworkTests' => :debug
pod 'PureWeb', :path => './Pureweb.podspec'

post_install do |installer_representation|
   installer_representation.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
     end
  end
end

**New file** 
source 'https://github.com/CocoaPods/Specs.git'
workspace './PureWebFramework'

use_frameworks!

target 'PureWeb' do
   pod 'PureWeb', path => './PureWeb.podspec'
   target 'FrameworkTests' do
          inherit! :search_paths
   end
end

post_install do |installer_representation|
   installer_representation.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
     end
  end
end

I then run pod install on the new podfile

## What did you expect to happen?

I expected all dependencies to be installed and for
The PureWeb target to appear as one of the schemes that can be built
This was the case for cocoapods 0.39.

## What happened instead?

With cocoapods 1.0.1 there is no scheme for PureWeb in the generated workspace file.
Although all dependencies downloaded and installed fine

As a result I cannot build my PureWeb target

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : calgaryscientific -  @ fatal: Not a git repository (or any of the parent directories): .git
               calgaryscientific-1 - git@github.com:calgaryscientific/common-cocoapods.git @ 4355140c3ec06ea6530559efdefbfcb06a032baf
               master - https://github.com/CocoaPods/Specs.git @ 5290e2d5762f7d19b731a67fb9f9295dfed8d986
               nightly - git@github.com:calgaryscientific/pureweb-ios-cocoapods @ 0b60970eaaec6023913e19240f03c1e6c737ad36
               PureWeb - https://github.com/calgaryscientific/pureweb-ios-cocoapods @ d1f6ba3d21698935bdc1ca9f4241ba42ad64e030
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
workspace './PureWebFramework'

use_frameworks!

platform :ios, '8.0'

target 'PureWeb' do
	pod 'PureWeb', :path => './PureWeb.podspec'
	target 'FrameworkTests' do
		inherit! :search_paths
	end
end

post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
```

## Project that demonstrates the issue

I've linked a project that demonstrates the issue.

[FrameworkFail.zip](https://github.com/CocoaPods/CocoaPods/files/330612/FrameworkFail.zip)

**Comment by neonichu** [comment]
Yes, the generated target and scheme are called "Pods-PureWeb" instead, this is intentional. Could you please elaborate why that is an issue for you?

**Comment by neitzj** [comment]
I don't see any schemes accept for Documentation and PureWeb-Universal. With 0.39 there was a PureWeb scheme that was generated. Without it I can't build. Are you seeing something different?

**Comment by neonichu** [comment]
Oh right, there's a new installation option now for generating schemes for development pods:

```ruby
install!('cocoapods', :share_schemes_for_development_pods => true)
```

should give you the old behaviour.

**Comment by neitzj** [comment]
Where do I include it in the Podfile? I just tried including it near the top of my Podfile. But I still only see the Documentation and PureWeb-Universal schemes.

**Comment by neitzj** [comment]
Nevermind that is working for me in my actual project. Thanks!
