### ISSUE TITLE
Build fails after changing from single target to abstract_target

### ISSUE THREAD

**Issue by herzbube** [CocoaPods/CocoaPods#5565]
🌈
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

* The original Podfile only contained Pods for a single target.
* I then edited the Podfile to use `abstract_target` (as recommended in [The Podfile](https://guides.cocoapods.org/using/the-podfile.html)) and added the original target plus the unit test targets underneath the `abstract_target` declaration.
* Finally, I executed `pod install`.

## What did you expect to happen?

I expected CocoaPods to update the project to the new configuration, which includes removing things (.xcconfig files, libraries, possibly other stuff) from the old configuration.

## What happened instead?

CocoaPods created everything correctly for the new configuration, but didn't clean up things (.xcconfig files, libraries) from the old configuration. As a result, the build failed because an old library was still present in the project.

The problem can easily be fixed by manually cleaning up, but it still would have been nice if CocoaPods would have done this for me. It's your fault, you have spoiled me! :-)

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 562b7f3dc68cc01ac0f3ee7030a7427a80a59611
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
abstract_target 'All Targets' do
  pod 'MBProgressHUD'

  target 'cocoapods-abstracttarget-test' do
  end

  target 'cocoapods-abstracttarget-testTests' do
  end

  target 'cocoapods-abstracttarget-testUITests' do
  end
end
```

## Project that demonstrates the issue

I created a dummy project whose Git history has a step-by-step demonstration of the issue: https://github.com/herzbube/cocoapods-abstracttarget-test

**Comment by skyline75489** [comment]
+1 on this. Automatic clean-up would be nice.

**Comment by segiddins** [comment]
Does running `pod deintegrate && pod install` fix things?

**Comment by neonichu** [comment]
Closing this because of lack of response.
