### ISSUE TITLE
Consistency of --sources between commands

### ISSUE THREAD

**Issue by maschall** [CocoaPods/CocoaPods#5569]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Setup a private repository with a few podspecs
Ran `pod lib lint --allow-warnings --use-libraries`
Ran `pod spec lint --allow-warnings --use-libraries`
Ran `pod repo push InHousePodsRepo --allow-warnings --user-libraries`
## What did you expect to happen?

I expect all three commands to act the same way.
## What happened instead?

For `pod lib lint` and `pod spec lint`, I need to specify `--sources=InHousePodsSpec,master`, but `pod repo push` will succeed to validate the spec, because it assumes all sources in `pod repo`.

For me it seems intuitive that `pod lib lint` and `pod spec lint` would assume all sources just like `pod repo push`

Just wanted to see what others thought.

**Comment by neonichu** [comment]
I think if we were to change something, `pod repo push` should also require manually specifying sources. However, this would make it useless by default, as pushing to the master repo is done via `pod trunk` — I don't remember exactly, but I guess that was the rationale behind having it behave differently.

**Comment by maschall** [comment]
After looking at it more, I think you're right, being explicit instead of implicit would be better.

We have two private repos for different projects, they share some Pods in between.  Because `pod lib lint` requires the `--sources`, we didn't notice that `pod repo push` needs `--sources` in order to validate correctly.

It worked out for a long time until we started a migration to Cocoapods 1.0.1 from 0.37.1.

**Comment by maschall** [comment]
I would like to suggest, that `--sources` for `pod repo push` should default to the @repo being pushed to and master.

**Comment by orta** [comment]
connecting to https://github.com/CocoaPods/CocoaPods/issues/5807
