### ISSUE TITLE
error: Resource "/Users/dev-server/Library/Developer/Xcode/DerivedData/Comi-cewsxxvvkzbtlefhbjbjmntrudhk/Build/Products/Release-iphoneos/MWPhotoBrowser/MWPhotoBrowser.bundle" not found. Run 'pod install' to update the copy resources script.

### ISSUE THREAD

**Issue by comicool** [CocoaPods/CocoaPods#5573]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
 when i build my project in jenkins, i report the error message. but build the workspace manually， it is ok. 

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
    
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /usr/local/homebrew/Cellar/ruby/2.3.0/lib
Repositories : JSBrowserViewController - https://git.oschina.net/genobili/JSBrowserViewController.git @ 95813b01fb9d54ee5c5cc954b07a719d8c431b9c
               master - https://github.com/CocoaPods/Specs.git @ f450b2be501554509e224230fb9fabfc68e89553
```

### Installation Source

```
Executable Path: /usr/local/homebrew/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
project './Comi/Comi.xcodeproj'
platform :'ios', '7.0'
inhibit_all_warnings!

target 'Comi' do
  ...
  pod 'EaseUI', :git => 'ssh://git@dev.ismanhua.com:10022/ios/ease_ui_ios.git', :tag => '0.0.40'
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
```

and my  EaseUI.podspec  
Pod::Spec.new do |s|
      s.name         = "EaseUI"
      s.version      = "0.0.40"
      ...

      **s.dependency 'MWPhotoBrowser', '~> _2.1.2'**

end

**Comment by neonichu** [comment]
Are you manually setting `CONFIGURATION_BUILD_DIR` by any chance? If yes, this is likely a duplicate of #5358.

**Comment by comicool** [comment]
yes, it's the same of issue #5358, i set CONFIGURATION_BUILD_DIR param in jenkins. thanks a lot.

**Comment by DarrylBayliss** [comment]
@neonichu Is there any specific guidance on how to solve this? Looking at various issues raised around this I'm beginning to think a lot of people using Jenkins as their CI through the [Xcode Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Xcode+Plugin) and don't truly understand what is going on underneath the hood (myself included).

**Comment by segiddins** [comment]
@DarrylBayliss set BUILD_DIR instead of CONFIGURATION_BUILD_DIR

**Comment by Coeur** [comment]
@DarrylBayliss, in my case, moving the "Build output directory" value to "SYMROOT" value did the trick.

**Comment by machinefixer** [comment]
@DarrylBayliss ,in jenkins xcode plugin configuration,  leave the "Build output directory" field empty, and set "SYMROOT" field to "$WORKSPACE/build",
