### ISSUE TITLE
The Pod target is missing when I add a new dependency

### ISSUE THREAD

**Issue by Lucashuang0802** [CocoaPods/CocoaPods#5576]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I added an extra dependency to my pod: `OTKAnalytics`
## What did you expect to happen?

It should be working normally and `OTKAnalytics` is available.
## What happened instead?

The CLI does not print anything wrong. However, the pod target gets removed when I opened up my XCode space file.
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ aa41c3163ca7781f17b04c77fccca003dbc140a4
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
target 'OTAcceleratorPackUtil_Example' do
  pod 'OTAcceleratorPackUtil', :path => '../'

  target 'OTAcceleratorPackUtil_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  end
end
```
## Project that demonstrates the issue

https://github.com/opentok/acc-pack-common

You can download it and add a new dependency `OTKAnalytics` from `OTAcceleratorPackUtil.podspec`, the target `OTAcceleratorPackUtil` in the XCode space file will be missing after running `pod install` in the example project.

**Comment by neonichu** [comment]
Thanks for the example!
