### ISSUE TITLE
ld: library not found for -lPods

### ISSUE THREAD

**Issue by holyen** [CocoaPods/CocoaPods#5582]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

 Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly, and build app correctly.

## What happened instead?
first,Install all pod dependencies correctly,but when we build the app in xcode ,the error info:
Ld /Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/NeoTV.app/NeoTV normal arm64
    cd /Users/xxx/Desktop/neotv
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode_7.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode_7.3.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode_7.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode_7.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/AFNetworkActivityLogger -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/AFNetworking -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/CTAssetsPickerController -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/CocoaLumberjack -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/MBProgressHUD -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/Masonry -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/PureLayout -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/RDVTabBarController -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/RESideMenu -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/SDWebImage -L/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/SVProgressHUD -L/Users/xxx/Desktop/neotv/Pods/WeiboSDK/libWeiboSDK -F/Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos -filelist /Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Intermediates/NeoTV.build/Debug-iphoneos/NeoTV.build/Objects-normal/arm64/NeoTV.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -no_deduplicate -ObjC -lAFNetworkActivityLogger -lAFNetworking -lCTAssetsPickerController -lCocoaLumberjack -lMBProgressHUD -lMasonry -lPureLayout -lRDVTabBarController -lRESideMenu -lSDWebImage -lSVProgressHUD -lWeiboSDK -lsqlite3 -lz -framework CoreGraphics -framework CoreTelephony -framework CoreText -framework Foundation -framework ImageIO -framework MobileCoreServices -framework Photos -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -fobjc-arc -fobjc-link-runtime -weak_framework Photos -lPods -lPods-NeoTV -Xlinker -dependency_info -Xlinker /Users/xxx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Intermediates/NeoTV.build/Debug-iphoneos/NeoTV.build/Objects-normal/arm64/NeoTV_dependency_info.dat -o /Users/xx/Library/Developer/Xcode/DerivedData/NeoTV-asvywzkmeykbzjcwkthiuahmvvri/Build/Products/Debug-iphoneos/NeoTV.app/NeoTV

ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fac1127bc47a5fc98ec46d9b05f078681155dba9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'NeoTV' do

  # Pods for NeoTV
pod 'Masonry', '0.5.3'
pod 'RESideMenu', '~> 4.0.7'
pod 'CocoaLumberjack', '2.0.0'
pod 'CTAssetsPickerController',  '~> 3.3.0'
pod 'AFNetworking', '2.5.1'
pod 'AFNetworkActivityLogger', '2.0.3'
pod 'RDVTabBarController', '1.1.9'
pod 'SVProgressHUD', '1.1.3'
pod 'WeiboSDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git'
pod 'SDWebImage', '~> 3.7'
pod 'MBProgressHUD', '~> 0.9'

end
```

**Comment by neonichu** [comment]
This is likely related to remaining state in your project. Please check your linker flags and remove any custom values you have added, by hitting delete when the build setting is selected in the Xcode project editor. When editing linker flags, Xcode will copy the value from the XCConfig generated by CocoaPods and it can never be updated by CP again.

If it turns out this isn't the issue you are facing, please share a project to reproduce and we can reopen this issue.

**Comment by holyen** [comment]
but i didn't add any custom values in linker flags...
