### ISSUE TITLE
Incomplete incremental installation of pod if same spec was installed before with a subset of platforms

### ISSUE THREAD

**Issue by mrackwitz** [CocoaPods/CocoaPods#5584]
# Report
## What did you do?

Create Podfile with:

``` ruby
install! 'cocoapods',
         :integrate_targets => false
target 'iOS' do
   platform :ios, '9.3'
   pod 'Crashlytics'
end
```

Run:

``` bash
pod install
```

Modify Podfile so that it contains:

``` ruby
install! 'cocoapods',
         :integrate_targets => false
target 'iOS' do
   platform :ios, '9.3'
   pod 'Crashlytics'
end
target 'OSX' do
   platform :osx, '10.11'
   pod 'Crashlytics'
end
```

Run:

``` bash
pod install
```
## What did you expect to happen?

The pod should be installed completely on iOS and macOS.
## What happened instead?

The installation succeeded, but the macOS target is missing platform-specific files, because the incremental installation used the sources in the `Pods/` directory, which were cleaned before when we installed only on iOS. That causes that platform-specific files for macOS were deleted and are now missing. Due the fact that file accessors don't enforce that the specified files actually exist, these kinds of errors can be easily missed, because the pod installation won't fail, it will be just partially installed.

**Note**: Potentially this affects also situations, when a subset of subspecs were selected in a previous installation and more subspecs are selected in a subsequent installation.
## Project that demonstrates the issue

https://github.com/mrackwitz/CocoaPods-5584
## Workaround

``` shell
rm -rf Pods/
```

**Comment by neonichu** [comment]
See #3150, but since this one is more detailed, I'm closing the older one :)
