### ISSUE TITLE
Local Authentication .podspec when there are mistakes

### ISSUE THREAD

**Issue by AllLuckly** [CocoaPods/CocoaPods#5586]
Local Authentication .podspec when there are mistakes，
I do not know how to solve
project address:https://github.com/AllLuckly/LBLaunchImageAd
Requesting for help！Thanks

`pod lib lint --allow-warnings`

```
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  /Users/gold/Desktop/LBLaunchImageAd/LBLaunchImageAd/AppDelegate.m:10:9: fatal error: 'LBLaunchImageAdView.h' file not found

```

**Comment by neonichu** [comment]
You can use the `--no-clean` option to leave the generated project in place and inspect it manually — you should be able to determine the reason for the compilation error that way.
