### ISSUE TITLE
When I was running "pod setup",it threw a issue

### ISSUE THREAD

**Issue by Mingmingmew** [CocoaPods/CocoaPods#5592]
# Report

## What did you do?
Run `pod setup`

## What did you expect to happen?
setup the cocoapods successfully

## What happened instead?
heweimingdeMacBook-Pro:~ heweiming$ pod setup
Setting up CocoaPods master repo
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master

Cloning into 'master'...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

## CocoaPods Environment
cocoapods version is 1.0.1   
system version  OS X EI Capitan 10.11.5 (15F34)

I just ran "sudo gem install -n /usr/local/bin cocoapods"
This is successful.
But when I was running the "pod setup",it threw a issues that "Setting up CocoaPods master repo
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master

Cloning into 'master'...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed"

I've retried many times but I can't fix this

**Comment by neonichu** [comment]
Looks like some kind of issue with your connection to GitHub. I'm assuming you're getting the same result when running `/usr/bin/git clone https://github.com/CocoaPods/Specs.git master` outside of CocoaPods?

**Comment by Mingmingmew** [comment]
Oh,thanks! I‘ve taken your advice.Then I need to config “.gitconfig” in my mac by "git config --global user.email xxxxxxx@xx.com",adding my email address.But I dont't konw why it will work.I didn't config that file before I changed my macbook.At last,thank you very much!

**Comment by vineetsansare** [comment]
Hi @Mingmingmew, if you're still facing the issue. You should look at the comment by @segiddins [here](https://github.com/CocoaPods/CocoaPods/issues/4293). It worked for me and many others. Hope it works for you too. :)
