### ISSUE TITLE
Sub dependencies do not respect configuration options

### ISSUE THREAD

**Issue by jcavar** [CocoaPods/CocoaPods#5596]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have the following Podfile:
```
platform :ios, '9.0'

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'CocoaPodsConfigBug' do
    pod 'FBMemoryProfiler', :configurations => ['Debug']
end
```

## What did you expect to happen?

FBMemoryProfiler and it's sub dependencies(FBAllocationTracker, FBRetainCycleDetector) are included only in Debug configuration

## What happened instead?

FBMemoryProfiler is included only in Debug but it's sub dependencies are not. They are in Release as well. And if I check generated xcconfig files i can see `-lFBAllocationTracker -lFBRetainCycleDetector`, which I guess should not be there?

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.3
Ruby lib dir : /Users/josip04/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8b345f28bba34a523d867de801ed37d2df6de8ec
               novastone-ios_podspecs - git@gitlab.novastone.net:ios/ios_podspecs.git @ 16952e7b339c19fc0f0246b5ca6fd2c7183e75d8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '9.0'

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'CocoaPodsConfigBug' do
    pod 'FBMemoryProfiler', :configurations => ['Debug']
end
```

## Project that demonstrates the issue

https://www.dropbox.com/sh/aarddwj5s4pi0oz/AAA1XqlAV_0L4-nTRBWEHL8ua?dl=0

**Comment by neonichu** [comment]
This is intentional and documented as such, see #5220

**Comment by jcavar** [comment]
Thanks!
