### ISSUE TITLE
Test target fails to import bridging header when including Google Analytics

### ISSUE THREAD

**Issue by JanGorman** [CocoaPods/CocoaPods#5605]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

A Swift project that includes the `Google/Analytics` pod and includes the library in it's bridging header doesn't compile.

## What did you do?

* Add `pod 'Google/Analytics'` to a project
* Include GA in a bridging header as per [their documentation](https://developers.google.com/analytics/devguides/collection/ios/v3/?ver=swift) (as it doesn't generate a Swift module)
* Add this bridging header to the test target
* `pod install` and compile the unit test target

## What did you expect to happen?

* The test target compiles correctly

## What happened instead?

I get an error telling me `#import <GGLCore/GGLCore.h>` cannot be found:

```
/Users/j.gorman/Desktop/GAPodIssue/GAPodIssue/GAPodIssue-Bridging-Header.h:5:9: note: in file included from /Users/j.gorman/Desktop/GAPodIssue/GAPodIssue/GAPodIssue-Bridging-Header.h:5:
#import <Google/Analytics.h>
        ^
/Users/j.gorman/Desktop/GAPodIssue/Pods/Headers/Public/Google/Google/Analytics.h:1:9: error: 'GGLCore/GGLCore.h' file not found
#import <GGLCore/GGLCore.h>
        ^
<unknown>:0: error: failed to import bridging header '/Users/j.gorman/Desktop/GAPodIssue/GAPodIssue/GAPodIssue-Bridging-Header.h'
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.0
Ruby lib dir : /opt/boxen/rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 96446ebad973c5679d632840ba59cf5f681e1fb4
```

### Installation Source

```
Executable Path: /opt/boxen/rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 0.5.1
cocoapods-plugins      : 1.0.0
cocoapods-podfile_info : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.0.0
```

### Podfile

```ruby
target 'GAPodIssue' do
  use_frameworks!

  pod 'Google/Analytics'

  target 'GAPodIssueTests' do
    inherit! :search_paths
  end

end
```

## Project that demonstrates the issue

[GAPodIssue](https://github.com/JanGorman/GAPodIssue)

**Comment by benasher44** [comment]
Dup of #5173
