### ISSUE TITLE
Pod fail to compile with CocoaPods v1.0.1 - headers not found for development pods in SIWFT with Bridging-Header.h

### ISSUE THREAD

**Issue by klusinyan** [CocoaPods/CocoaPods#5609]
Using CocoaPods v1.0.1 in Swift and can not find headers for development PODS, other pods (not pointed as development) work perfectly. I have tried to set in project build settings RECURSIVE HEADER SEARCH for HEADER SEARCH PATHS key, no result and the problem continues to insist in MyProject -Bridging-Header.h file.

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'MyProject' do
    pod 'CommonUtils', :path => '../../iOS+/CommonUtils'
    pod 'EasyAnimation'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'FastEasyMapping'
    pod 'CommonCoreData', '~> 0.0.1-beta'
    pod 'PKHUD'
end`

**Comment by segiddins** [comment]
Please fill out the [issue template](https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md) so we can get a better idea of what's going wrong here. Thanks!

**Comment by klusinyan** [comment]
Thank you very much for your quick reply!
Hope that I could explain the issue in correct way.

# Report

## What did you do?

I have a library CommonUtils written in Objective-C
My project which includes CommonUtils written in Swift.
Here is the podfile of the final project:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'MyProject' do
     pod 'CommonUtils', :path => '../CommonUtils'
     //other pods 
end

```
## What did you expect to happen?

In my project I create "Bridging-Header.h" with 

```
#import "CommonPageContent.h"
#import "CommonBook.h"
#import "CommonKeyboard.h"
//other headers
```


## What happened instead?

Compiler's error "CommonPageContent.h" (for all headers). Directory "Pods/Headers is empty". In the directory "Pods/Local Podspecs" there is "CommonUtils.podspec" file. The only place where I can find the CommonUtils library's headers is "Pods/Target Support Files/" and the only way to make it work with project is to commit and upload the library to CocoaPod's to the remote repository then execute "pod update" command.

## Project that demonstrates the issue
Here is the library's link:
[(https://cocoapods.org/pods/CommonUtils)]

**Comment by neonichu** [comment]
You don't need a bridging header with `use_frameworks!`. If you still want to use one, you need to use module imports (`@import`) to import your Pod, `#import` will not work in this case.
