### ISSUE TITLE
Question - Which Xcode versions are installing my pod

### ISSUE THREAD

**Issue by avnerbarr** [CocoaPods/CocoaPods#5610]
# Report
Is it possible to get statistics on which versions of XCode are being used for a particular podspec?

## What did you do?
I checked the cocoa spec info site. I checked "cocoa statistics". 

## What did you expect to happen?
Get stats about the environment which installed the pod

Got general stats . i.e. github,cocoadocs,stats

## What happened instead?
General stats

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories :     master - https://github.com/CocoaPods/Specs.git @ 3da4315c03ec77605c33882a451183f2f90b957d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.2.0
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 0.5.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :osx, '10.10'
plugin 'cocoapods-rome'
target 'kuku' do
pod 'Swiftline'
end
```

**Comment by orta** [comment]
If you run with `--verbose` you should get that information from your computer as it's being compiled.  However, there is no metadata like that available online from CocoaPods' side, if you're looking for the version of swift a library supports, you're best off reading their README.

**Comment by avnerbarr** [comment]
Let me re-phrase my question , 

I am providing a podspec to my customers. I want to understand which versions of XCode they are using when they are installing the pod from their side. 

For instance get the count of my users that are are integrating using XCode 7.2 rather than 7.3 or 8.0. This is useful for me as the swift syntax is changing and I need to know when I can drop support for older versions of swift.

Thanks

**Comment by orta** [comment]
Ah, no, we're not providing that kind of user data [in stats](http://blog.cocoapods.org/Stats/), we aimed for those to be strictly about CocoaPods' domain e.g the target structure, and nothing about individual users or their projects.
