### ISSUE TITLE
Provide an option to skip App target generation while linting private podspec 

### ISSUE THREAD

**Issue by eugeneshih** [CocoaPods/CocoaPods#5612]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I have a private static library (Library 1) which is intended to be used with another private static library (Library 2). I do not want to combine them into a single library for various reasons. One reason is that library 1 contains ObjC++ while Library 2 is fully ObjC. Combining them would be a pain. 

The specific issue I'm having with `pod lib lint` is that I get a failure like `ld: symbol(s) not found for architecture x86_64` when I run it on Library 1's podspec because Library 1 declares a C method that is defined in Library 2 (using extern "C"). This only happens for 1.0.x because Cocoapods now "generates an app target in 1.0 which imports [the] Pod". 

## What did you do?

Ran `pod lib lint --private` on private podspec

## What did you expect to happen?

I expected the podspec validation to pass. I believe in 0.39.x, the podspec would have validated.

## What happened instead?

I have a private static library (Library 1) which is intended to be used with another private static library (Library 2). The specific issue I'm having with `pod lib lint` is that I get a failure like `ld: symbol(s) not found for architecture x86_64` when I run it on Library 1's podspec because Library 1 declares a C method that is defined in Library 2 (using extern "C"). This only happens for 1.0.x because Cocoapods now "generates an app target in 1.0 which imports [the] Pod". 

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : CMTPublicSpecs - git@bitbucket.org:cambridgemobiletelematics/cmtpublicspecs.git @ 49854e11f3b4c44be70d2357c1e0cbe66fc58bde
               master - https://github.com/CocoaPods/Specs.git @ 654c79258cf77b64fe5c23d941e05961f9ff22fb
               mirego - git@github.com:mirego/MCPodSpecs.git @ fd92822e75cbd14599a1b19585bbacc93f6de9a5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```
I removed the podfile, but in honesty, there is nothing special in here. If you really need it, I can sanitize and paste here.
```
## Project that demonstrates the issue

This is a private spec. I can try to create a project the reproduces this problem, but my description is pretty accurate. If I copy the static library into a project that includes both Library 1 and Library 2, the project compiles and links successfully without error.

**Comment by segiddins** [comment]
Does `pod lib lint --use-libraries" work?

**Comment by neonichu** [comment]
I don't agree that it makes sense to support linting incomplete Pods.

**Comment by eugeneshih** [comment]
No, `pod lib lint --use-libraries` does not work.

I agree that for public podspecs, you should not support linting incomplete Pods. But for private pods, it would be convenient if you allowed it. If this is not something CocoaPods wants to support, I can fork work around it and push to my private spec directory without using `pod push`.

**Comment by eugeneshih** [comment]
I think I can work around this by using weak linking. Thus, for my use, I think this issue is no longer relevant for me.

**Comment by segiddins** [comment]
👍
