### ISSUE TITLE
no email received for 'pod trunk register'

### ISSUE THREAD

**Issue by piemonte** [CocoaPods/CocoaPods#5615]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

hey friends, i've been trying to register my email (found on my github user page) and the POST succeeds, yet i don't receive the email.

i've checked my spam folder as well. it's my university forwarding address, which i've registered and used in the past on other machines.
## What did you do?

pod trunk register [email] [name]
## What did you expect to happen?

receive an email after some time.
## What happened instead?

no email received
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ afed56c142aa5aaec34032f9763d49279bd1de91
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
## Project that demonstrates the issue

NA

**Comment by segiddins** [comment]
Might be something up with https://github.com/CocoaPods/trunk.cocoapods.org but I don't remember getting any error alerts today

**Comment by benasher44** [comment]
@piemonte can you try registering again? If you still don't get an email, please file a new issue. Thanks!

**Comment by piemonte** [comment]
hey @benasher44 i've tried numerous times over the past couple months and am still not receiving the validation email. not sure what's happening because i can register other email addresses, just not this one. the one email does receive emails from other senders which is what's strange.

**Comment by benasher44** [comment]
Hmm we're not seeing any issues. We'll have to get the email you're using specifically to check it. You can DM me on Twitter if you like.

**Comment by piemonte** [comment]
@benasher44 thanks, i followed you on twitter but it won't let me DM unless you follow back. my email is also the one on my GitHub profile page.

**Comment by orta** [comment]
Think I remember this got sorted out of this issue. 👍

**Comment by piemonte** [comment]
yes, thank you!
