### ISSUE TITLE
duplicate symbol error when linting with --use-libraries

### ISSUE THREAD

**Issue by aufflick** [CocoaPods/CocoaPods#5617]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod spec lint --allow-warnings --use-libraries --verbose

## What did you expect to happen?

Great success.

## What happened instead?

```
duplicate symbol _Redacted in:
    /Users/aufflick/Library/Developer/Xcode/DerivedData/App-cugekmebxsveqvcrseaarqtqzevr/Build/Intermediates/App.build/Release/App.build/Objects-normal/x86_64/main.o
    /Users/aufflick/Library/Developer/Xcode/DerivedData/App-cugekmebxsveqvcrseaarqtqzevr/Build/Products/Release/RedactedPod/libRedactedPod.a(RedactedClass.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin15.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.8.3
Ruby lib dir : /Users/aufflick/.rubies/ruby-2.1.3/lib
Repositories : redacted-podspecs - ssh://git@redacted/podspecs.git @ 8274f847ad7fae3cadad595e97eef033fa1877b6
               master - https://github.com/CocoaPods/Specs.git @ 9ed4203ed81d9d705080e3c7420c70deec37d8ba
```

### Installation Source

```
Executable Path: /Users/aufflick/.gem/ruby/2.1.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

I'll try to reduce it, but basically I have an old-ish podspec which for now is only used in an old ObjC project, hence the --use-libraries. I the symbol in question is a const NSString, declared as an extern in exactly one header, and defined in exactly one .m file (as proven by grep). It seems that the linting mechanism with --use-libraries is compiling the .m into both the lib and main.o, and then trying to link them together.

**Comment by neonichu** [comment]
According to the linker output the symbol is present in `main.o` — can you please double check it is actually marked as `extern` in the header?

**Comment by neonichu** [comment]
Closing because of lack of response.
