### ISSUE TITLE
Lint failed to validate podspecs with dependecy containing '-' symbol

### ISSUE THREAD

**Issue by pavelosipov** [CocoaPods/CocoaPods#5619]
I have a [pod](https://github.com/pavelosipov/POSHockeyAppExtension) with dependency on ''HockeySDK-Source' pod. Lint failed to validate its podspec with error `fatal error: 'HockeySDK-Source/HockeySDK.h' file not found` 

I run `pod spec lint POSHockeyAppExtension.podspec --verbose` and found a reason for that strange behaviour. The problem is on the copying headers stage. Here is how files of HockeySDK-Sources are copied to template project:

```
CpHeader HockeySDK-Source/Classes/BITInternal.h /Users/<redacted>/Library/Developer/Xcode/DerivedData/App-flpmuhfjupppxtbulsabnvsjtkzy/Build/Products/Release-iphonesimulator/HockeySDK-Source/HockeySDK_Source.framework/Headers/BITInternal.h
```
It looks like '-' symbol was replaced with underline symbol '_' and that is why code with such import statement as `#import <HockeySDK-Source/HockeySDK.h>` was failed to compile.

Any workaround?

**Comment by orta** [comment]
This isn't an issue with CocoaPods, more that it is how Frameworks [name their modules](http://blog.cocoapods.org/CocoaPods-0.39/). You cannot use `-`s in the name, your best option is to either do imports [like this](https://github.com/artsy/Artsy-UILabels/blob/master/Pod/Classes/Artsy%2BUILabels.m#L5) or to use the `@import` syntax, which should be the same between libs/frameworks

**Comment by pavelosipov** [comment]
Thanks for advise. I fixed my podspec using the recommended approach.
