### ISSUE TITLE
Pod Repo Push to Different Branch

### ISSUE THREAD

**Issue by gngrwzrd-intel** [CocoaPods/CocoaPods#5621]
# Report

I'd like the pod repo push command to push to whatever branch I have checked out in `~/.cocoapods/repos/myrepo/`
## What did you do?

```
cd ~/.cocoapods/repos/myrepo
git checkout develop
cd ~/myproject
pod repo push MyPrivatePodSpec.podspec --allow-warnings
#output:
[Everything up to date]
```
## What did you expect to happen?

I expect cocoapods to push whatever the current branch is.
## What happened instead?

It seems like it only pushes master. Because it only pushes master my updated podspec that I want on a develop branch do not get pushed.
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : basis-specs - https://github.com/Basis/Specs.git @ 19f2fef0dc3b9fbcda72fdab9e3e1ad66baad482
               master - https://github.com/CocoaPods/Specs.git @ d5826522b9b8360a54828e24e153aeaa68d5c569
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
## Additionally

I tried setting git.config.push to multiple different values - simple, current, etc. But it seems like the command pod repo push only pushes to master?

I'd love to see this fixed or some kind of option to control it.

Our development team automates all of our internal work, including automated podspec updates to our private podspec repo.

We want to be pushing the podspecs to a develop branch (without changing the default branch), so that master remains 'stable' podspecs, and develop is for bleeding edge - our development team would checkout the develop branch for the podspec repo so their getting bleeding edge pods.

Also note that I've tried using pod update with a develop branch checked out. And it works properly by installing latest pod that was in that branch.

**Comment by segiddins** [comment]
This is done at https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/repo/push.rb#L211, I'd be OK with changing it to use to current branch.

**Comment by HIMANSHU-ELIGIBLE** [comment]
@segiddins would it be possible to allow to push the pods to current branch instead of master branch so, release of new pod can undergo review before getting into master.

**Comment by orta** [comment]
Yep, feel free to make the PR @HIMANSHU-ELIGIBLE

**Comment by baguio** [comment]
Being proposed at #8630
