### ISSUE TITLE
[1.1.0.beta.1] multiple projects in a same workspace,I want to config pods for each project,How to achieve？

### ISSUE THREAD

**Issue by selectersky** [CocoaPods/CocoaPods#5622]
# Report

## What did you do?
dictroy list：~/my/app/:
pluginA/puginA.xcodeproj
pluginB/puginB.xcodeproj
master/master.xcodeproj

1. `pluginA` need cocoapod mange pod `AFNetworking`,
1. `pluginB` need cocoapod mange pod `MJRefresh`,`AFNetworking` 
1.  `master` need cocoapod mange pod `SDWebImage`、`MJRefresh`
1. `master` need `pluginA`、`pluginB`。i hand set in `master/master.xcodeproj`

## What did you expect to happen?

1. create pod:

   ```sh
    cd ~/my/app
    pod init master/master.xcodeproj
    ```
2. open ./master.workspace,add file pluginA/puginA.xcodeproj，pluginB/puginB.xcodeproj

3.  edit ./Podfile:

    ```
    platform :ios, '8.0'
    workspace 'MAppPlatform'
    use_frameworks!

    target 'master' do
      pod 'SDWebImage'
      pod 'MJRefresh'
      project 'master/master'
    end
        
    target 'pluginA' do
      pod 'AFNetworking'
      project 'pluginA/pluginA'
    end

    target 'pluginB' do
      pod 'AFNetworking'
      pod 'MJRefresh'
      project 'pluginB/pluginB'
    end
    ```

4. run `pod install` or `pod update`

## What happened instead?
I got error:

    ```
     pod update
    Update all pods
    Updating local specs repositories
    Analyzing dependencies
    [!] Unable to find host target for Pods-PluginA,Pods-PluginB. Please add the host targets for     the embedded targets to the Podfile.
    ```

I find old version someone do it:<https://github.com/CocoaPods/CocoaPods/issues/738>
but this version can't 

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0fc85760ebd85a51ec4ee15091a7d3f143099070
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
1. <https://github.com/CocoaPods/CocoaPods/issues/738>
2. <https://github.com/CocoaPods/CocoaPods/issues/5620>
3. <https://github.com/CocoaPods/CocoaPods/issues/5561>

**Comment by segiddins** [comment]
@benasher44 another possible bug with host target detection?

**Comment by selectersky** [comment]
I found a way to solve:

1. first `deintegrate` master project pods file,re init pluginA\pluginB\master. before init next project,need to delete current directroy Podfiles.below commads:

    ```sh
cd ~/my/app
pod deintegrate master/master.xcodeproj
rm Podfile*
pod init pluginA/pluginA.xcodeproj
rm Podfile*
pod init pluginB/pluginB.xcodeproj
rm Podfile*
pod init master/master.xcodeproj
  ```  
2. edit Podfile,content was:
 
    ```sh
platform :ios, '8.0'
workspace 'master'
use_frameworks!

target 'master' do
  pod 'SDWebImage'
  pod 'MJRefresh'
  project 'master/master'
end

target 'pluginA' do
  pod 'AFNetworking'
  project 'pluginA/pluginA'
end

target 'pluginB' do
  pod 'AFNetworking'
  pod 'MJRefresh'
  project 'pluginB/pluginB'
end
```

3. run `pod install`

Command was successful !!!

```sh
pod install
Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.6.3)
Installing MJRefresh (3.1.10)
Installing SDWebImage (3.8.1)
Using XMLReader (0.0.2)
Generating Pods project
Integrating client projects
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
```

**Comment by selectersky** [comment]
That is, you must first init project.  rather than automatically. However, init only once, so there must first delete podfile, then init operation

next step，Cocoapods there an easier way??

**Comment by benasher44** [comment]
@segiddins I found some issues with integrating a project that depends on a sub-project's framework that has pod deps. TBH, I have no idea how what @selectersky did fixed anything, since this case should still be quite broken IMO. I have a test case I'm working with locally, and I think I know the steps to fix it now.

**Comment by benasher44** [comment]
@selectersky I have some PRs up to fix this. Can you try updating your Gemfile to look like this, and then try `pod install`ing again:

```
gem 'cocoapods', :git => 'https://github.com/benasher44/CocoaPods', :ref => '24e840d88ea5047ae7a901021f475c10eabf681f'
gem 'xcodeproj', :git => 'https://github.com/benasher44/Xcodeproj', :ref => '74669928c2bce1d160b913bc6c9469643f2cd1e1'
```

**Comment by selectersky** [comment]
thanks @benasher44 .  Since one of the init previous works, are now using `pod install` normal install pods. But using `pod update` there will be problems at first.

Now our project to build a complete, already in use. Thanks for feedback and bug fixes @benasher44  @segiddins

**Comment by opfeffer** [comment]
@selectersky, are you able to build `pluginA` or `pluginB` standalone as well?

We have a similar cocopoads/project setup but I'm struggling to have "the best of both worlds" by being able to run `pod install` from the app folder and use the shared workspace as well as `cd pluginA && pod install` and being able to build a single plugin as a standalone project.

Cocoapods throws
```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `PluginA` to `../Pods/Target Support Files/Pods-PluginA/Pods-PluginA.debug.xcconfig` or include the `../Pods/Target Support Files/Pods-PluginA/Pods-PluginA.debug.xcconfig` in your build configuration (`PluginA/Pods/Target Support Files/Pods-PluginA/Pods-PluginA.debug.xcconfig`).
```
