### ISSUE TITLE
Getting "target has transitive dependencies that include static binaries" error when trying to create a pod with GoogleMaps dependency

### ISSUE THREAD

**Issue by eyaldar** [CocoaPods/CocoaPods#5624]
# Report

Hi,
I'm trying to create a pod with GoogleMaps dependency.
Both my example and my library is dependent upon GoogleMaps framework. 
At first I tried using the "dependency" property in the Podspec and got the aforementioned error when trying to run "pod install" or "pod lib lint".
Then I tried to use the "vendored_frameworks" property with a GoogleMaps.framework file which did solve the original error and passes the "pod lib lint" test but the problem with this approach is that my Example no longer recognizes the GoogleMaps module or in case I add the GoogleMaps to the example's Podfile I get an error: "The '[Example project name]'  target has frameworks with conflicting names: GoogleMaps.".

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/Ran/.rvm/rubies/ruby-2.3.0/lib
Repositories : danylokostyshyn - https://github.com/danylokostyshyn/private-podspecs.git @ 609e933f52636727af7ee93971076b68ba4c843b
               master - https://github.com/CocoaPods/Specs.git @ 90bde4fec9c4389372ecb168fc7c4ebb3bf7bee5
```

### Installation Source

```
Executable Path: /Users/Ran/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'GoogleMapsUtilsSwift_Example' do
    pod 'GoogleMaps'
	pod 'GoogleMapsUtilsSwift', :path => "../"
end
```

## Project that demonstrates the issue

I don't have an entire project to show, but this is my project prior to trying to create a pod (created a new project with "pod lib create" and moved files to correct locations:
https://github.com/eyaldar/google-maps-ios-utils-swift

and this is my podsec:
```
Pod::Spec.new do |s|
  s.name             = 'GoogleMapsUtilsSwift'
  s.version          = '0.1.0'
  s.summary          = 'A clustering library for Google Maps'

  s.description      = 'This is a swift implementation of DDRBoxman clustering'
  s.homepage         = 'https://github.com/eyaldar/google-maps-ios-utils-swift'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'eyaldar' => 'eyaldar@gmail.com' }
  s.source           = { :git => 'https://github.com/eyaldar/google-maps-ios-utils-swift.git', :tag => s.version.to_s }

  s.ios.deployment_target = '8.0'
  s.source_files = 'GoogleMapsUtilsSwift/Classes/**/*', '*.framework'
  
  s.requires_arc = true
  s.module_name  = 'GoogleMapsUtilsSwift'
  s.libraries	 = 'c++', 'icucore', 'z'
  s.frameworks   = 'Accelerate', 'AVFoundation', 'CoreData', 'CoreLocation', 'CoreText', 'Foundation', 'OpenGLES', 'QuartzCore', 'ImageIO', 'GLKit', 'SystemConfiguration', 'UIKit', 'MapKit', 'GoogleMaps'
  s.vendored_frameworks = 'Dependencies/GoogleMaps.framework'
#  s.dependency 'GoogleMaps'
end
```

**Comment by orta** [comment]
Until GoogleMaps is released as a dynamic framework, you can only support it as a transitive dependency as a library. However, as you are using a swift framework - you can't support that either. Your best option is to request Google release their libraries as a dynamic framework I'm afraid.

**Comment by eyaldar** [comment]
So it means that ATM there are no swift libraries dependent upon Google libraries? 
Are there no ways to at least bypass the conflicting name error? obviously its less optimal than using the "dependency" property but its better than nothing at all I guess...

**Comment by neonichu** [comment]
Vendoring the framework won't really help you, as it will be linked against the app target, not your framework regardless. There's plenty of discussion regarding this in the original issue #2926

**Comment by ivampir** [comment]
I getting exactly same error. Did you solve it?

**Comment by tirrorex** [comment]
Same here
