### ISSUE TITLE
[Xcode 7.3.1, CocoaPods 1.0.0] Framework directory not found when the default `Debug` and `Release` configurations are absent

### ISSUE THREAD

**Issue by gerald-coddut** [CocoaPods/CocoaPods#5627]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

🌈 

# Report

## What did you do?
I've successfully made a private pod after a lot of trial and error. Afterwards tried to integrate it into my app using `pod install`. 

## What did you expect to happen?

I expected the XCode project to successfully build.

## What happened instead?

Building the app failed with the notorious `-F framework not found for directory`.
My project has four configurations (NTRL, ACPT, PROD and APPSTORE). I suspect that this has something to do with it. 

_Why?_

Because building the app doesn't fail when I add the configurations `Debug` and `Release` (which are included by default) to my project, and run `pod update`. But now my project has six configurations, of which I do not use `Debug` and `Release`.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 36b13053d2fb17124b191304a88248cd492910f6
               private - git@github.com:REPLACED_FOR_OBESCURITY_username/REPLACED_FOR_OBESCURITY__private podspec repo@ b305500ba65ebb445cd25a1b23bf6dd87bbefc6c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'git@github.com:REPLACED_FOR_OBESCURITY__username/REPLACED_FOR_OBESCURITY__private podspec repo'
source 'https://github.com/CocoaPods/Specs.git'

project 'MyProject.xcodeproj'

platform :ios, '8.0'

target 'MyProject' do
  use_frameworks!

  #pod 'MyPrivatePod'
  # If you need to use a specific MyPrivatePod branch, comment out the pod above
  # and use the one below (change the branch if needed)
  pod 'MyPrivatePod', :git => 'git@github.com:REPLACED_FOR_OBESCURITY__username/REPLACED_FOR_OBESCURITY__private podspec repo', :branch => 'cocoapods/cocoapods-private_pod'

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```

## Project that demonstrates the issue

> I cannot include a project since the code is confidental.

**Comment by neonichu** [comment]
Does explicitly specifying build configurations help here? See <https://guides.cocoapods.org/syntax/podfile.html#project>

**Comment by gerald-coddut** [comment]
I'll try that and post the results here. Might be a few days before I'm able to try it though (vacation)
