### ISSUE TITLE
`ModuleName-Swift.h` autogenerated header fails to import umbrella header exposed by `pod lib create`

### ISSUE THREAD

**Issue by nobre84** [CocoaPods/CocoaPods#5628]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

• Create a sample project with `pod lib create SwiftExtension` Swift / Mixed sources.
• Created `ObjcClass.m/h` with the following methods:

```
- (void)method:(NSString *)key withFormat:(NSString*)format, ... NS_FORMAT_FUNCTION(2,3) NS_REFINED_FOR_SWIFT;
- (void)method:(NSString *)key withFormatArgs:(va_list)arguments NS_REFINED_FOR_SWIFT;
```
Created `ObjcClass+Swifty.swift` extension which exposes a proper API for Swift consumption:
```
extension ObjcClass {
    @nonobjc func method(key: String, format args: CVarArgType...) {
    }
}
```
• Build the project

## What did you expect to happen?

Build succeeds and all callers can happilly consume proper APIs from their language

## What happened instead?

Build fails with message
```SwiftExtension.framework/Headers/SwiftExtension-Swift.h:97:9: 'SwiftExtension/SwiftExtension.h' file not found```

The header file tries to expose the Swift version of my extension to ObjC code, importing the umbrella header to maybe be able to see the ObjC version to extend.
Being generated by Xcode, it tries to import with `#import <SwiftExtension/SwiftExtension.h>`, which is the expected umbrella created by its own library template. However CocoaPods expects me to import it with `#import "SwiftExtension-umbrella.h"`. Changing this manually works, however of course after cleaning and rebuilding the error appears again.
Is there a workaround or any work being done to change the way umbrella headers are created/imported in CocoaPods libraries ?
Based on the discussion at #4482 it looks like its not in the interest of the team, would this use case be a valid turn around point for that discussion ?

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.4.2
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.8.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bf3295bdd06842b2cc16cb0ce82a6a2d453fbc3c
               qranio - https://bitbucket.org/qranioios/Specs.git @ 20f6270ab7b7f08381a743aaf6eb38a9d235d9ed
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate     : 1.0.0
cocoapods-playgrounds     : 0.1.0
cocoapods-plugins         : 1.0.0
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.0.0
cocoapods-try             : 1.0.0
cocoapods-try-release-fix : 0.1.1
```

### Podfile

```ruby
use_frameworks!

target 'SwiftExtension_Example' do
  pod 'SwiftExtension', :path => '../'

  target 'SwiftExtension_Tests' do
    inherit! :search_paths

    
  end
end
```

## Project that demonstrates the issue

https://github.com/nobre84/SwiftExtension

**Comment by neonichu** [comment]
There's an open issue for this here: #3767
