### ISSUE TITLE
Clone CocoaPods master repo hangs on MAC OSX 10.12

### ISSUE THREAD

**Issue by M144-Coder** [CocoaPods/CocoaPods#5629]
# Report

## What did you do?
Run these commands 

`cd ~/.cocoapods/repos
GIT_TRACE=1; GIT_CURL_VERBOSE=1 git clone http://github.com/CocoaPods/Specs.git master --verbose`

## What did you expect to happen?

The master repo of Cocoapods to get cloned successfully so I can start using Cocoapods

## What happened instead?
The operation hanged at 1% and receiving objects and after a while it finalized with an error
here is the terminal output:-

`Cloning into 'master'...
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 192.30.253.112...
* Connected to github.com (192.30.253.112) port 80 (#0)
> GET /CocoaPods/Specs.git/info/refs?service=git-upload-pack HTTP/1.1
Host: github.com
User-Agent: git/2.7.4 (Apple Git-66)
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 301 Moved Permanently
< Content-length: 0
< Location: https://github.com/CocoaPods/Specs.git/info/refs?service=git-upload-pack
< Connection: close
< 
* Closing connection 0
* Issue another request to this URL: 'https://github.com/CocoaPods/Specs.git/info/refs?service=git-upload-pack'
* Couldn't find host github.com in the .netrc file; using defaults
*   Trying 192.30.253.112...
* Connected to github.com (192.30.253.112) port 443 (#1)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: github.com
* Server certificate: DigiCert SHA2 Extended Validation Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /CocoaPods/Specs.git/info/refs?service=git-upload-pack HTTP/1.1
Host: github.com
User-Agent: git/2.7.4 (Apple Git-66)
Accept: */*
Accept-Encoding: gzip
Pragma: no-cache

< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-upload-pack-advertisement
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: 69EEB048:2D36F:6AF964:57888CD0
< X-Frame-Options: DENY
< 
* Connection #1 to host github.com left intact
POST git-upload-pack (305 bytes)
* Couldn't find host github.com in the .netrc file; using defaults
* Found bundle for host github.com: 0x7fc3d750be30
* Re-using existing connection! (#1) with host github.com
* Connected to github.com (192.30.253.112) port 443 (#1)
> POST /CocoaPods/Specs.git/git-upload-pack HTTP/1.1
Host: github.com
User-Agent: git/2.7.4 (Apple Git-66)
Accept-Encoding: gzip
Content-Type: application/x-git-upload-pack-request
Accept: application/x-git-upload-pack-result
Content-Length: 305

* upload completely sent off: 305 out of 305 bytes
< HTTP/1.1 200 OK
< Server: GitHub Babel 2.0
< Content-Type: application/x-git-upload-pack-result
< Transfer-Encoding: chunked
< Expires: Fri, 01 Jan 1980 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, max-age=0, must-revalidate
< Vary: Accept-Encoding
< X-GitHub-Request-Id: 69EEB048:2D36F:6AFF66:57888CD9
< X-Frame-Options: DENY
< 
remote: Counting objects: 747987, done.
remote: Compressing objects: 100% (17/17), done.
* SSLRead() return error -9806/747987), 2.16 MiB | 437.00 KiB/s   
* Closing connection 1
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed`

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A201w)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : Specs -  @ fatal: Not a git repository (or any of the parent directories): .git
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by neonichu** [comment]
I'm using CP successfully on 10.12 for a few weeks now, so I don't think this is a general problem, but rather related to your network environment.

**Comment by M144-Coder** [comment]
Yes it appears like a network issue, but the rest of my apps are working correctly.
Is there a manual way to setup the master repo? perhaps downloading it to a specific location then execute a specific command?

**Comment by neonichu** [comment]
You could try download the ZIP GitHub provides, but I am not sure if that'll be updatable via Git.

**Comment by bartdag** [comment]
FWIW, I am having intermittent connection issues with github (192.30.253.112) since 4-5 days. I often need to retry a push or a clone.

**Comment by M144-Coder** [comment]
I confirm it's a network issue on my side. I executed this command on a Windows 10 machine
`git clone http://github.com/CocoaPods/Specs.git master`
Then copied the master repo to this directory on the MAC OSX machine using the terminal cp command (normal copy using Finder hangs for hours):
`~/.cocoapods/repos/master`

Then finally doing pod init then pod install --verbose on my project directory worked like a charm.
