### ISSUE TITLE
No email received for pod trunk register

### ISSUE THREAD

**Issue by ben-moore** [CocoaPods/CocoaPods#5630]
* [X ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run the following:
```
 pod trunk register sdk@mobiledonky.com 'Ben Moore' --description='Bens MacBook Pro'
```
## What did you expect to happen?
Receive an email with a link to start a session
## What happened instead?
No email received
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ac41089c2d54276f635f63f1435a4ebe8891e53b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
## Additional Information
We recently had some issues with non-delivery of emails to sdk@mobiledonky.com.  This has been resolved however we are still not seeing any emails from cocoapods.  Please check our address has not been blacklisted etc as we have an urgent release to do.

**Comment by orta** [comment]
We're seeing them as having bounced : `550 5.7.64 TenantAttribution; Relay Access Denied`

<img width="961" alt="screen shot 2016-07-15 at 07 55 58" src="https://cloud.githubusercontent.com/assets/49038/16873483/96ccf46e-4a61-11e6-86c8-aa10150d7627.png">

I've removed this email from the blacklist, next one should try and go through 👍

**Comment by ben-moore** [comment]
Yes that's worked, thank you!
