### ISSUE TITLE
Support for Swift's canImport and optional dependencies

### ISSUE THREAD

**Issue by srdanrasic** [CocoaPods/CocoaPods#5631]
Swift 3 is introducing `#if canImport(ModuleName)` configuration test ([SE-0075](https://github.com/apple/swift-evolution/blob/master/proposals/0075-import-test.md)) that will allow us to conditionally compile code based on the importability of the module / framework so I'm interested if there is any discussion going on whether CocoaPods should provide better support this feature? 

Let's say that I have a framework A that can be used both in a standalone fashion, but can also extend features of framework B if such is importable. I'd like to distribute framework A without the dependency on framework B, but I'd also like that, if user adds framework B to his project, framework A is compiled with extensions for framework B.

My guess is that such support would require additional property in Podspec and additional rule for dependency resolution.
 
1. In A.Podspec there would be an entry for optional dependency on framework B. Something like `s.optional_dependency 'B', '~> 1.0'`
2. When the app's Podfile contains both A and B, CocoaPods will resolve dependencies in a way that framework B is built first and made available for the building of the framework A so that A's `canImport` tests succeed.

Thanks everyone here for your hard work!

**Comment by orta** [comment]
From a relatively cursory glance, I think we would support this feature already, well, when it's ready.

The optional dependency is interesting.  Currently this behaviour is done [via subspecs](https://github.com/CocoaPods/Specs/blob/master/Specs/Moya/7.0.0/Moya.podspec.json#L56-L640), which I think does a pretty good job of handling the "my library + extended with someone else's stuff." 

@CocoaPods/core any more nuanced opinions?

**Comment by neonichu** [comment]
Yah, I agree, I think subspecs are the way to go for something like this and should already work.

To make sure everyone is on the same page, basically one would create an optional subspec which has a strong dependency on B in the given example. Users could then opt into using it by declaring something like `pod "A/B"` (depending on the subspec's name).

**Comment by segiddins** [comment]
Optional dependencies are something I want to implement in our dependency resolver eventually, they're just a super hard problem. Until then, the subspec approach is going to be the best way to do this

**Comment by mrackwitz** [comment]
Agree on what was previously said here! :+1:
Just want to add a little hint: you can use `pod_target_xcconfig` to add a custom flag to `OTHER_SWIFT_FLAGS` via option `-d`, which is available to the preprocessor in all Swift files of the pod, so that it can be used for conditionally using e.g. otherwise unavailable symbols if that was made available by the user by including a subspec in the Podfile.

**Comment by neonichu** [comment]
I can think we can close this for now, as we all agree that for now, subspecs are the way to go.

**Comment by wellbranding** [comment]
@srdanrasic @orta @neonichu  Hello, it does not work.. If I use subspec and  #if canImport() tag, then our main framework cannot access code from subspec.. Why it is  case?
