### ISSUE TITLE
Only the headers of 'vendored_frameworks' are copied into framework

### ISSUE THREAD

**Issue by xwang-phunware** [CocoaPods/CocoaPods#5634]
I add a vendord framework `MyInternal.framework` like the below in my `MyProject.podspec`
....
s.vendored_frameworks = 'Vendor/MyInternal.framework'
....

And the `MyInternal.framework` structure like:
MyInternal.framework
|--Headers
|         |--MyInternal.h
|         |--Others.h
|--Resources
|         |--en.lproj
|--MyInternal 

Run `pod package MyProject.podspec xxx`, the `MyProject.framework` was successfully generated, but the library of MyInternal.framework wasn't embedded in it, and the final structure is like:
MyProject.framework
|--Modules
|         |--module.modulemap
|--Headers
|         |--MyProject.h
|         |--MyInternal
|                     |--MyInternal.h
|         |--Others.h
|--MyProject

I tried Cocoapods v0.39.0, v1.0.1 and Cocoapods-Packager v1.2.1, v1.3.0, v1.4.0, always have the problems:
1. The `MyInternal.framework/MyInternal` wasn't embedded to `MyProject.framework`
2. Why the `MyInternal.framework/Headers/xx` was embedded to `MyProject.framework`

**Comment by orta** [comment]
Please move this to https://github.com/cocoapods/cocoapods-packager - which is the repo for the package project, which it looks like this is about

**Comment by xwang-phunware** [comment]
Thanks.
