### ISSUE TITLE
Error after installation via brew

### ISSUE THREAD

**Issue by nallwhy** [CocoaPods/CocoaPods#5642]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
`brew install cocoapods`

## What did you expect to happen?
`pod` command works well

## What happened instead?
Error occurs
```
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/json/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/json/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

fish: 'pod install' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

## CocoaPods Environment
CocoaPods : 1.0.1
ruby-2.2.1

@keith Hi, I read the #2238.
I tried to install cocoapods via Homebrew, but `pod` makes errors.
```
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/json/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/json/.rvm/gems/ruby-2.2.1/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

fish: 'pod install' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
I guess the reason of this is the version of json gem. (https://github.com/AtomLinter/linter-rubocop/issues/84)
I've changed ruby version from 2.2.1 to 2.0.0-p648 via rvm and it works well.

Could you fix it?

**Comment by segiddins** [comment]
We don't maintain the homebrew formula for CocoaPods, so your best bet will be to bring it up with whoever does, sorry!

**Comment by nallwhy** [comment]
@segiddins No problem. Thanks!
