### ISSUE TITLE
when use ijkplayer  in project, Cocoapods  excute 'pod lib lint' BUILD FAILED with  fatal error: 'libavformat/avformat.h' file not found

### ISSUE THREAD

**Issue by cqhcqhcqh** [CocoaPods/CocoaPods#5644]
Please help me

**Comment by segiddins** [comment]
Please fill out the [issue template](https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md) so we can try and help you. Thanks!

**Comment by cqhcqhcqh** [comment]
https://github.com/cqhcqhcqh/VMMediaPlayer
This is my project 

Run pod lib lint --no-clean --verbose
I want that project pass validation
But has a error:fatal error: 'libavutil/avassert.h' file not found

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3 (7D175)
         Git : git version 2.8.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : FirstSpecs - https://chengqihan@git.vmovier.cc/scm/~chengqihan/firstspecs.git @ f18e100ec5f4de8dd32ec27e2830cb64eaddaf34
               MagicBoxSpecs - https://git.vmovier.cc/scm/im3/magicboxspecs.git @ 3d1ac33b80141468024f0ca3727ea58a053fffcc
               master - https://github.com/CocoaPods/Specs.git @ 389167e078f63c5416bb324a687ff504cd9fc942
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by neonichu** [comment]
As far as I can see, this is not a CocoaPods issue, but rather a compilation issue with your Pod. 

You need to set up your headers so that they satisfy the expectations of your code. You might also want to check out existing Pods for ffmpeg, like <https://cocoapods.org/pods/FFmpeg> instead of bundling your own version.
