### ISSUE TITLE
🌈 pod spec lint gives incorrect warning

### ISSUE THREAD

**Issue by asib** [CocoaPods/CocoaPods#5646]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I ran `pod spec lint` on my [project](https://github.com/asib/CPJSONRPC).

## What did you expect to happen?

Expected the linter to validate my podspec.

## What happened instead?

The spec did not pass validation, due to 1 warning:

`- WARN  | xcodebuild:  CPJSONRPC/CPJSONRPC/Classes/Public/CPJSONRPCResponse.m:72:23: warning: unused variable 'rpcErr' [-Wunused-variable]`

The thing is, I'm certain this variable is used for these reasons:

* Line 73 (the line below the declaration of `rpcErr`) is the following:

```[resp setObject:rpcErr forKey:JSON_RPC_ERROR_KEY];```

* I built the project myself and Xcode did not flag an `unused variable` warning.
* I even added an unused variable on line 74 (`NSError *bla;`) to be sure that Xcode was actually flagging unused variables as it's supposed to. Indeed, on building, Xcode flagged `bla` as an unused variable.

I should mention that the warning was initially correct (`rpcErr` was unused). I corrected the problem, recreated the tag, pushed to remote, etc., then ran `pod spec lint` again and the warning persisted. After trying little things here and there, which didn't work, I decided to create this issue.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin13]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8bacc4a67fc400bca536360fb5283893027e1ddf
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[This](https://github.com/asib/CPJSONRPC) is the project that is giving me the problem.

**Comment by orta** [comment]
> I should mention that the warning was initially correct (rpcErr was unused). I corrected the problem, recreated the tag, pushed to remote, etc., then ran pod spec lint again and the warning persisted. After trying little things here and there, which didn't work, I decided to create this issue.


Sounds like you're hitting a caching problem, try [running](https://guides.cocoapods.org/terminal/commands.html#pod_cache_clean) `pod cache clean`, to see if that updates you to the latest version of that tag.

**Comment by asib** [comment]
Yeh that's fixed it. Thank you!
