### ISSUE TITLE
fatal error: could not build module

### ISSUE THREAD

**Issue by cqhcqhcqh** [CocoaPods/CocoaPods#5648]
# Report

pod lib lint --no-clean --verbose --allow-warnings

## What did you expect to happen?

project passed validation

## What happened instead?
App/main.m:3:9: fatal error: could not build module 'VMOpenssl'

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3 (7D175)
         Git : git version 2.8.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : FirstSpecs - https://chengqihan@git.vmovier.cc/scm/~chengqihan/firstspecs.git @ cf3c83e9f4f4da547a83db4d3115ee8f3ab5c76b
               MagicBoxSpecs - https://git.vmovier.cc/scm/im3/magicboxspecs.git @ 3d1ac33b80141468024f0ca3727ea58a053fffcc
               master - https://github.com/CocoaPods/Specs.git @ 389167e078f63c5416bb324a687ff504cd9fc942
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

https://github.com/cqhcqhcqh/VMOpenssl

**Comment by neonichu** [comment]
Have a look at the verbose build log, you can see the actual failure:

```
    - NOTE  | xcodebuild:  /Users/boris/Library/Developer/Xcode/DerivedData/App-djcmyhnfmmxljtdjaazwiyeiwzte/Build/Products/Release-iphonesimulator/VMOpenssl/VMOpenssl.framework/Headers/aes.h:55:10: fatal error: 'openssl/opensslconf.h' file not found
```

Since your Pod has compilation errors, it cannot pass validation. Looks like your `HEADER_SEARCH_PATHS` are configured incorrectly.

**Comment by cqhcqhcqh** [comment]
How to  cconfigure HEADER_SEARCH_PATHS ?
Please help me pass validation

**Comment by cqhcqhcqh** [comment]
How to configure HEADER_SEARCH_PATHS in **.podspec file
Please help me ,i has been struggling for a long time
