### ISSUE TITLE
pod "Setting up CocoaPods master repo" everytime when use  "pod install --verbose --no-repo-update"

### ISSUE THREAD

**Issue by fero2004** [CocoaPods/CocoaPods#5651]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

## What did you do?

I use "pod install --verbose --no-repo-update"
but Everytime pod "Setting up CocoaPods master repo"

## What did you expect to happen?

I expected the pod Don't download master repo when I use "pod install --verbose --no-repo-update"

## What happened instead?

pod download master repo

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/luozg/.rvm/rubies/ruby-2.3.0/lib
Repositories : artsy - https://github.com/Artsy/Specs.git @ 40004aaa5870afdc655bfbbdc84a2718ec8c1805
               master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

### Installation Source

```
Executable Path: /Users/luozg/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## PodFile
```
platform:ios,'7.0'
pod "SDWebImage"
pod "AFNetworking", '~> 3.0'
pod "MJRefresh"
pod 'Masonry'
pod 'MHVideoPhotoGallery'
pod 'Bugtags'
pod "UITextView+Placeholder"
pod 'MBProgressHUD'
pod "MWPhotoBrowser"
pod 'FMDB'
pod 'DZNEmptyDataSet'
```
## Project that demonstrates the issue

I cannot include a project since the code is confidental.

**Comment by DanToml** [comment]
@fero2004 Did you already have the CocoaPods Master repo setup on your machine?

**Comment by fero2004** [comment]
@DanToml YES.I checked ~/.cocoapods/ and The folder size is 788M.But when I used pod install --verbose --no-repo-update . there folder size is 384kb.then pod begin "Setting up CocoaPods master repo"

**Comment by neonichu** [comment]
Hm, this doesn't look too good:

```
master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

I would suggest trying to manually delete the master checkout from `~/.cocoapods` and retry.

**Comment by neonichu** [comment]
Closing because of lack of response.

**Comment by nick3389** [comment]
Hi guys,

the same happens to me after every pod command. The "Setting up CocoaPods master repo" appears again and again. What can I do?

**Comment by jsky222** [comment]
I had the same problem. After about 5 minutes it finally said Pod installation complete!

**Comment by AdnanNazir** [comment]
I have this issue too.

**Comment by priyankamistry09** [comment]
Did you found any solution for this?

**Comment by ledikari** [comment]
issue still persist

**Comment by shuiqingliu** [comment]
I have this issue too.

**Comment by hongz1125** [comment]
I have this issue too. @neonichu

**Comment by ukiyoevega** [comment]
same here
