### ISSUE TITLE
all Third-party libraries reinstalled after update pod.

### ISSUE THREAD

**Issue by fero2004** [CocoaPods/CocoaPods#5652]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I update pod 0.39.0 to 1.0.1.and I add new Third-party libraries to pod file. then I used pod install.But all Third-party libraries reinstalled! My changes to the third party library are gone. 

## What did you expect to happen?

just add new Third-party libraries and not change other libraries

## What happened instead?

all Third-party libraries reinstalled

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/luozg/.rvm/rubies/ruby-2.3.0/lib
Repositories : artsy - https://github.com/Artsy/Specs.git @ 40004aaa5870afdc655bfbbdc84a2718ec8c1805
               master - https://github.com/CocoaPods/Specs.git @ ec66a66bb1e8c8eea8a7a61130337d303ed0d6a5
```

### Installation Source

```
Executable Path: /Users/luozg/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform:ios,'7.0'
target:aiyuke do
pod "SDWebImage"
pod "AFNetworking", '~> 3.0'
pod "MJRefresh"
pod 'Masonry'
pod 'MHVideoPhotoGallery'
pod 'Bugtags'
pod "UITextView+Placeholder"
pod 'MBProgressHUD'
pod "MWPhotoBrowser"
pod 'FMDB'
pod 'DZNEmptyDataSet'
end
```

**Comment by fero2004** [comment]
I solved this issue by edit the Podfile.lock.

change the Podfile.lock file last line COCOAPODS: 0.39.0 to COCOAPODS: 1.0.1

**Comment by orta** [comment]
This was the migration step between 0.39 and 1.0, this isn't a bug, but to make sure your system is completely up to date 👍
