### ISSUE TITLE
Specify gitconfig to use when pushing to private repo

### ISSUE THREAD

**Issue by skyline75489** [CocoaPods/CocoaPods#5654]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I try to push a podspec to my company private repo, which requires me to use my company gitconfig for username and email.

## What did you expect to happen?

It works.

## What happened instead?

CocoaPods used my global gitconfig with my own personal username and email. And the push was rejected.

## CocoaPods Environment

No need

## Project that demonstrates the issue

No need.

**Comment by skyline75489** [comment]
Actually I don't even know what gitconfig CocoaPod is using. I changed my global gitconfig and it still doesn't work.

**Comment by orta** [comment]
How would you expect the custom gitconfig to work? 
Do they go per folder? 
Would you expect a parameter to the command?

**Comment by skyline75489** [comment]
I think we pretty much just need a new parameter, specifying whether CocoaPods should use global or repo gitconfig.

**Comment by segiddins** [comment]
If you configure the specs repo with the desired git config, that will be used when pushing.

**Comment by skyline75489** [comment]
How do I config `the specs repo with the desired git config`, exactly?

**Comment by segiddins** [comment]
`cd ~/.cocoapods/repos/SPEC_REPO && git config`

**Comment by skyline75489** [comment]
@segiddins OK. I'll close this. Thanks for the clarification.
