### ISSUE TITLE
Error loading the plugin cocoapods-try-1.1.0.

### ISSUE THREAD

**Issue by Vinod-Square** [CocoaPods/CocoaPods#5655]
ArgumentError - could not find a temporary directory
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:34:in tmpdir' /Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:70:inclass:Try'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:10:in <class:Command>' /Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:6:inmodule:Pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:5:in <top (required)>' /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in require' /Library/Ruby/Gems/2.0.0/gems/cocoapods-try-1.1.0/lib/cocoapods_plugin.rb:1:in'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in require' /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:inrequire'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in block in safe_activate_and_require' /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:ineach'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in safe_activate_and_require' /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:inblock in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in map' /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:inload_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:326:in block in run' /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:ineach'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:325:in run' /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command.rb:50:inrun'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/bin/pod:55:in <top (required)>' /usr/local/bin/pod:22:inload'
/usr/local/bin/pod:22:in `

**Comment by orta** [comment]
Please create a new issue, and fill out the example issue metadata 👍 - we have that there to answer a lot foo the questions we'd have to ask.
