### ISSUE TITLE
`pod repo update` keeps cloning master-1/2/3 repos

### ISSUE THREAD

**Issue by wkoszek** [CocoaPods/CocoaPods#5656]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
```
        rvm gemspec create test
        gem update
        gem cleanup
        gem install bundler
        gem install cocoapods --pre
        gem install fastlane --pre
        pod repo update
```

## What did you expect to happen?

I expected that the CocoaPods repo will be updated, and it'll finish in a reasonable time.

## What happened instead?

Looks like it does the clone of `master`, and once it's finished, it starts cloning `master-1`, `master-2` etc. It takes forever and I can't understand why ... it seems to be cloning same thing many times.

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.4
Ruby lib dir : /Users/wk/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2168008a55e032e6289e24ed943cc80b252db500
               master-1 - https://github.com/CocoaPods/Specs.git @ 2168008a55e032e6289e24ed943cc80b252db500
               master-2 - https://github.com/CocoaPods/Specs.git @ 0c712bb3b94b070bab026afd289a075b41f3b893
               master-3 - https://github.com/CocoaPods/Specs.git @ 8b9d7cab9404f769e6fe357a17f738ad7950f4c8
```

### Installation Source

```
Executable Path: /Users/wk/.rvm/gems/ruby-2.2.4@real_test/bin/pod
```

### Plugins

**pods / Ruby**
```
pod --version
1.1.0.beta.1
ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
```

**pod env**
```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

```
git clone https://github.com/wkoszek/sensorama-ios.git
cd sensorama-ios
rvm gemspec create test
./scripts/travis_script.sh
```

**Comment by Brett-Best** [comment]
I'm not completely sure but it looks like multiple repos have been added to the Cocoapods configuration. You can set up a custom repo to hold pods e.g. internally at a company.

```bash
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2168008a55e032e6289e24ed943cc80b252db500
               master-1 - https://github.com/CocoaPods/Specs.git @ 2168008a55e032e6289e24ed943cc80b252db500
               master-2 - https://github.com/CocoaPods/Specs.git @ 0c712bb3b94b070bab026afd289a075b41f3b893
               master-3 - https://github.com/CocoaPods/Specs.git @ 8b9d7cab9404f769e6fe357a17f738ad7950f4c8
```

I'd try removing `master-1`, `master-2` and `master-3`.
To do this try running:
```bash
pod repo remove master-1 && pod repo remove master-2 && pod repo remove master-3
```

**Comment by wkoszek** [comment]
@Brett-Best I don't get it, since I never requested master-2 and master-3 explicitly, but removing them helped me. Thanks. I'll close it for now, and re-open if it happens again.

**Comment by Brett-Best** [comment]
@wkoszek I'm not sure why they were added multiple times. Someone on the Cocoapods team might though. Glad it fixed it for you, even temporarily.
