### ISSUE TITLE
Pod push: Unable to add a source with url `` named `-1`

### ISSUE THREAD

**Issue by kooliokey** [CocoaPods/CocoaPods#5660]
# Report

## What did you do?

Run `pod repo push [PRIVATEREPONAME] [PODSPECPATH]`
I've also run it with a couple of the different flags available that I thought could help, local-only, verbose.

## What did you expect to happen?

Push my podspec to the private repo

## What happened instead?

The podspec is not added to the repo and I get an error about being unable to add a source.
```
Validating spec
Cloning spec repo `-1` from ``
[!] Unable to add a source with url `` named `-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
```

If I run this verbose I get the same error along with an error from git cloning a repo:
```
[!] Unable to add a source with url `` named `-1`.
(/usr/bin/git clone  -1

error: unknown switch `1'
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : JAPGPodsSpec - git@keyrBitbucket:keyr/JAPGPodsSpec @ 5f0fd6311325cb469ce5472276497765a8eace8d
               keyrbitbucket -  @ fatal: Not a git repository (or any of the parent directories): .git
               keyrbitbucket:keyr-japgpodsspec - git@keyrBitbucket:keyr/JAPGPodsSpec @ 5f0fd6311325cb469ce5472276497765a8eace8d
               master - https://github.com/CocoaPods/Specs.git @ 5a3d57b8b2026499d8ec89e93979dd9acaf5e118
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

I don't have a publicly available link to share

**Comment by orta** [comment]
Looks like something went wrong with this repo: `keyrbitbucket -  @ fatal: Not a git repository (or any of the parent directories): .git`

Would recommend deleting it, and re-adding it.

**Comment by kooliokey** [comment]
I noticed that too and I'm not sure why it is even there. That repo name is the name of my SSH identity used to connect to my private repo, so I guess I typo-ed something to get that one there. I just deleted it and it looks like it runs as expected! Sorry for the bother, but now it's in the issues if someone else comes across a similar one! :)

**Comment by FlyingNoob** [comment]
I have the seam problem. I also deleting it, and re-adding it. I switch the source
url https or ssh. But also have the problem. @orta @kooliokey

**Comment by wangpeiyan** [comment]
I have the seam problem. I also deleting it, and re-adding it. I switch the source
url https or ssh. But also have the problem. @orta @kooliokey

**Comment by benasher44** [comment]
Hi @wangpeiyan! Thanks for letting us know! This issue is quite old, and there isn't enough info in your comment for us to help debug. If you could please file a new issue and fully fill out the issue template, we'd be happy to help. Thanks!

**Comment by jacinzhang** [comment]
It's still have this problem!!! @benasher44

**Comment by amorde** [comment]
@jacinzhang if you are experiencing this, could you please submit a new issue with steps to reproduce the problem? Thanks!

**Comment by Pulichev** [comment]
I was trying to fix it directly but unsuccessfully.
So, my solution was to do all manually:
1) Copy podspec to /Users/<username>/.cocoapods/repos/<your directory>
2) open in source tree this directory
3) push changes
U do manually steps:
"pod repo push REPO [NAME.podspec]
      Validates `NAME.podspec` or `*.podspec` in the current working dir, creates a
      directory and version folder for the pod in the local copy of `REPO`
      (/Users/vladislav/.cocoapods/repos/[REPO]), copies the podspec file into the
      version directory, and finally it pushes `REPO` to its remote."
