### ISSUE TITLE
How to delete the content from CocoaDocs

### ISSUE THREAD

**Issue by sharleenZhu** [CocoaPods/CocoaPods#5662]
I deleted the repositories from Cocoapods with the command:'pod trunk delete' and can no longer search from the 'http://cocoapods.org' and 'http://cocoadocs.org'.But it still be accessed through the old URL to view its documentation from cocoadocs.How to delete the contents of the page has expired from cocoadocs? Thanks

**Comment by orta** [comment]
Hrm ideally the cocoadocs repo would listen for deletion events and remove them, give that you're the first to request this, it might be worth doing as a one-off, what are the pods you're trying to remove?

**Comment by orta** [comment]
This turned to email for privacy reasons - however, I removed them, and added a rake command to cocoadocs to make it easier in the future https://github.com/CocoaPods/cocoadocs.org/commit/631b691a922bb65dfd4c62b1a940098f70046e6d

**Comment by y2chaits** [comment]
Hi @orta,

Looks like cocoapods also supports deleting specific versions of the pod. Will CocoaDocs listen to the delete events for specific versions and remove docs for those versions?

Thanks!

**Comment by orta** [comment]
It can, it needs to be added to the web hook system, happy to gets some PRs on it
