### ISSUE TITLE
The 'Pods_XXX_Example' target has transitive dependencies that include static binaries: (/Users/XXX-ios/Example/Pods/FirebaseMessaging/Frameworks/FirebaseMessaging.framework

### ISSUE THREAD

**Issue by Maheepk** [CocoaPods/CocoaPods#5665]
Hi,

I am using cocoapods 
1.1.0.beta.1 Latest one.

and trying to install

     platform :ios, '7.0'

     inhibit_all_warnings!

     use_frameworks!

     pod 'Firebase'
     pod 'FirebaseMessaging'
     pod 'Reachability'
     pod 'AFNetworking'

     target 'XXX_Example' do
         pod 'XXX', :path => '../'

         target 'XXX_Tests' do
             inherit! :search_paths

         end
     end
[!] The 'Pods-XXX_Example' target has transitive dependencies that include static binaries: (/Users/XXX/Desktop/XXX/XXXSDK/XXX-ios/Example/Pods/FirebaseMessaging/Frameworks/FirebaseMessaging.framework)

Please let me know how can i resolve it?

thanks,

**Comment by skyline75489** [comment]
I'm guessing you are developing a Swift project, which requires `use_frameworks!` for Swift dependencies. However, if you have dependencies that's static binaries, you can't add those with `use_frameworks!`. This is due to restrictions from Apple that you can only use embeded(dynamic) framework with Swift project.

**Comment by Maheepk** [comment]
Yes, that works without
     use_frameworks!
 but problem is when installing some libraries like ''TKKeyboardControl" that needs use_frameworks!.

**Comment by skyline75489** [comment]
For those swift dependecies, you can directly add their source code into your project. By doing this `use_frameworks!` won't be necessary. 

I know, this literally throws `dependency management` away. It's a workaround, though.

**Comment by Maheepk** [comment]
yes, that is what i am doing now, but i was curious that if it download from cocoa pods with using use_frameworks!

**Comment by segiddins** [comment]
Sorry, but this is not an issue with CocoaPods. As the error message says, you cannot have transitive static dependencies while integrating pods as frameworks.

**Comment by Maheepk** [comment]
thanks @skyline75489 and @segiddins 💯

**Comment by FlyingNoob** [comment]
@segiddins I have the same problem. I cannot have transitive static dependencies. Is There any solution for this issue ?  Don't  use the tag 'use_framework!' ? Or direct use the static lib in podfile without dependency?
