### ISSUE TITLE
deployment_target attribute is not fully inherited by subspecs

### ISSUE THREAD

**Issue by b-ray** [CocoaPods/CocoaPods#5669]
🌈
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
Error message saying `The platform of the target 'CPTestTv' (tvOS 9.0) is not compatible with 'CPTest/swift (0.1.0)', which does not support 'tvos'.`

The documentation of the `podspec` states that `a ‘sub-specification’ inherits the value of the attributes of the parents so common values for attributes can be specified in the ancestors`. 
However, it seems that the `s.tvos.deployment_target` attribute is not getting inherited in the attached sample project. When adding this attribute also in the subspec (e.g. by uncommenting the line in this [sample podspec](https://github.com/b-ray/CPTest/blob/master/CPTest.podspec) ), everything works fine.

CocoaPods 1.0.1 and 1.1.0.beta.1 both show the same behaviour.

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.5.3
Ruby lib dir : /Users/stefanpuehringer/.rvm/rubies/ruby-2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 122283250354bc98dcb468e4894beec393d2858e
               private - private git repo
```

### Installation Source

```
Executable Path: /Users/stefanpuehringer/.rvm/gems/ruby-2.2.5@cocoapods-1-1-0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'CPTest_Example' do
    platform :ios, '8.0'
    pod 'CPTest', :path => '../', :subspecs => ['swift']
    
    target 'CPTest_Tests' do
        inherit! :search_paths
    end
end

target 'CPTestTv' do
    platform :tvos, '9.0'
    pod 'CPTest', :path => '../', :subspecs => ['swift']
end
```

## Project that demonstrates the issue
https://github.com/b-ray/CPTest

**Comment by segiddins** [comment]
That's intentional -- since you're overriding the iOS deployment target, it actually prevents inheriting the entire internal platform hash in the subspec.

**Comment by Buju77** [comment]
@segiddins thx for the quick answer. But this is not really the expected behavior. We expected everything to be inherited from parent like in normal programming languages. This is also not documented in podspec syntax docu.

whats the reason to prevent inheriting the entire internal platform hash?

**Comment by segiddins** [comment]
because then there would be no way to say that a subspec can only be used on a subset of platforms that the parent spec supports

**Comment by Buju77** [comment]
@segiddins thx for the quick answer. But this is not really the expected behavior. We expected everything to be inherited from parent. This is also not documented in podspec syntax docu.

whats the reason to prevent inheriting the entire internal platform hash?

**Comment by b-ray** [comment]
@segiddins thanks for the explanation! 👍
