### ISSUE TITLE
pod spec lint: duplicate symbol _main

### ISSUE THREAD

**Issue by igagis** [CocoaPods/CocoaPods#5670]
- [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

pod spec lint
## What did you expect to happen?

success
## What happened instead?

failure. Linker failed with error:

`duplicate symbol _main`

This happened because my library actually defines function main(). The user of the library is not supposed to define their function main at all, because library does it. Cocoa pods spec lint tries to link the library to some dummy app which has function main and linkage fails. Is there a way to overcome this? Suppress linking to dummy app during lint or something else?
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : igagis - https://github.com/igagis/cocoapods-repo.git @ 26d94c8bda341c6001f8e9877d5c94b9cfac134d
               master - https://github.com/CocoaPods/Specs.git @ e32b4165d722333dba6dce4f17962ead50d3dd21
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 0.5.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.0.0
```
## Project that demonstrates the issue

none

**Comment by segiddins** [comment]
Not at the moment, but I don't think we necessarily want to encourage pods defining `main` :/

**Comment by igagis** [comment]
@segiddins what would be the reason to forbid pods defining main?

**Comment by segiddins** [comment]
@igagis it would likely lead to a lot of confusion & linker errors for users

**Comment by igagis** [comment]
@segiddins that's unlikely. Users read documentation before using the library, don't they?

**Comment by samdmarshall** [comment]
I think that the most likely scenario is the user consumes your pod will encounter the error then look up why. As a note, if possible your code shouldn't rely on defining `main` as that could be redefined to be mapped to another symbol. If this is for library initialization then you should look at the `-init` flag that `ld` accepts for initializing your library when it gets loaded by the dynamic linker.

**Comment by igagis** [comment]
@samdmarshall I have never seen a user was using a library without knowing what it does and without reading how to use it. My library defines `main()` and it is reflected in documentation. I understand that in MacOS/iOS world program entry point is always `main()`, but there are other OSes also which may have different entry point, for example on Windows it is called `WinMain()` and I even not talking about Android. So, forbidding to have a function named `main()` is a bit strange, then we should forbid to have any functions in the library to be sure user won't have misunderstanding and confusion.
No, in my case `main()` is not for initialization on loading the library, does anybody do it that way O_O? I use it for normal purposes, it is only so that user does not have to define it manually when using my library. And this is the only way I can go due to pecularities of other OSes where I intend to run my library.

**Comment by samdmarshall** [comment]
Since CococaPods is an Apple-centric tool, even if the libraries that are consumed through it aren't built specifically targeting an Apple platform. Taking that into account, I think it is entirely reasonable for CocoaPods to make the assumption that any libraries it consumes shouldn't (by default) cause errors upon integration. While it may be true that your documentation explicitly forbids the use of `main` as a symbol in the app that is consuming this library, that documentation doesn't carry over to a clean integration method without dirtying the user's code. I have seen instances where the user does want to define their own `main` function for work that they must do as part of their app. This is not unheard-of. Additionally, I am assuming that you mean for this library to only be consumed as a static library and linked into the main executable of the app, vs having it be dynamically linked and thus unable to have the `main` symbol properly defined in the app's executable binary.

**Comment by igagis** [comment]
Of course CocoaPods is Apple-centric tool, it only makes sence on Mac OS and with XCode, but that does not mean that users will only use libraries written specifically for Apple environment.
I don't understand what you always mean by saying "cause errors by default upon integration"... It looks like you assume that application developers when they start their new project just throw everything they can find in cocoapods repo right to their project, or what? In my experience, it is a bit different, people first realize what they want to do, then they search for appropriate libraries over the internet, read reviews and tutorials, then they write code which uses those libraries in accordance with usage documentation, and then they build their app and linking to the library.
No doubts, often `main()` is needed to be explicitly defined, and this is the case when my library is inappropriate and should not be used for such cases, that's it. If you don't want, nobody forces you to use it.
Looks like you want to take too much responsibility on deciding for the users how they should write their programs. CocoaPods is a good tool for deploying libraries, but it should not dictate how to name functions in my library.
My library can be linked either statically, or dynamically, the way of linking is not related to where the `main()` is defined. The only thing is that dynamic linking makes not much sense on iOS, since dynamic libs are distributed bundled with the app anyway, so static linking is enough. For desktop MacOS I use homebrew and there I use dynamic linking.

**Comment by samdmarshall** [comment]
My comment was directed at the fact of using any iOS application template, your library will fail to integrate with the app target because the app target already defines a `main`. So unless the user of the library modifies their app to accommodate the changes you require, they will not be able to integrate it with an existing template.

The definition of `main` does matter when linking for the definition of `LC_MAIN` in the mach-o executable that is generated. This tells the dynamic linker where it should be starting to execute code from.

As @segiddins pointed out, I don't think it is ideal to have pods be able to define their own `main` as this places a restriction on developers in ways that they cannot work with more than one. I'm not sure if this is the responsibility of the dependency manager to also assist in symbol resolution for the linker as well.

**Comment by igagis** [comment]
Well, I have that special case when user is not supposed to use any "general iOS app template" at any stage of their app development. The point is that user writes application in desktop environment, linux, windows or macosx and is able to run it in desktop env. And then he can just build an iOS variant without any modifications of sources. All is needed just to install necessary libraries.

I don't understand how function named `main()` differ from any other function from library point of view. I understand that you are trying to make CocoaPods fool-proof, but in my opinion this is not the case. I wouldn't think that all who can code in C and C++ are not aware of what they are doing.

By the way, why is that check done at all, I mean why `pod spec lint` tries to link the lib against dummy app? Is that done exactly for catching the case of library defining `main()`?

**Comment by samdmarshall** [comment]
The requirement isn't on `main` not being defined, it is a requirement of being able to link to a standard iOS application template without any errors. This is done to ensure you are shipping code that works.

**Comment by igagis** [comment]
So what else is checked during that linking process? Other than this `main` thing?

**Comment by orta** [comment]
I'm pretty sure we made it to make sure that static libraries linked correctly, as well as the plethora of xcconfig additions that people can customize.

**Comment by samdmarshall** [comment]
@igagis the `main` duplicate symbol is a byproduct of the default iOS application templates as i mentioned before. I believe when performing a lint you are having the code be built and linked to an app that mirrors the default iOS application templates. this validates that it "works" for shipping your code and you aren't missing any dependencies or specific configuration changes with the build environment.

**Comment by segiddins** [comment]
See https://github.com/CocoaPods/CocoaPods/pull/5677 for a potential workaround

**Comment by igagis** [comment]
@samdmarshall ok, I understood about the template. Hopefully, there will be way to validate against different types of apps in the future. Maybe it would be more correct if library would provide its test apps and the validation would be done against the test app of the library... just as a suggestion for the future.

@segiddins it looks promising!

**Comment by DanToml** [comment]
This needs #5677 to be finished, if anyone wants to add tests and file a new PR based on that.

**Comment by dnkoutso** [comment]
#5677 was completed by #6420.

This should fix this issue by providing an option to skip linking during lint.
