### ISSUE TITLE
want to redevelop cocoapods to support cvs

### ISSUE THREAD

**Issue by jaychen04** [CocoaPods/CocoaPods#5672]
I want to want to redevelop cocoapods to support cvs. Could you give me some suggestions? I am  a newbie for ruby . Is there a guide for source code?

**Comment by jcampbell05** [comment]
ExternalSources.rb is the best place to start I think

**Comment by jaychen04** [comment]
ok ,I try to start with it ,thank you!

**Comment by segiddins** [comment]
Take a look at the cocoapods downloaded gem -- it's where all the download logic is implemented
