### ISSUE TITLE
No such module 'UIKit' / 'AppKit'

### ISSUE THREAD

**Issue by zolomatok** [CocoaPods/CocoaPods#5673]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Ran `pod lib lint`

## What did you expect to happen?
I expected my lib to pass validation.

## What happened instead?

I got the following errors when running `pod lib lint` on my library.

```
 -> Johnny (1.0)
    - WARN  | github_sources: Github repositories should end in `.git`.
    - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  /Users/zolo/_iOS/Johnny/Johnny/Extensions/UIButton+Johnny.swift:9:8: error: no such module 'UIKit'
    - ERROR | xcodebuild:  /Users/zolo/_iOS/Johnny/Johnny/Extensions/AppKit+Johnny.swift:10:8: error: no such module 'AppKit'
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.4.1
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6aabad50c8f3771640e95bd75ab9bb85eb750172
               zolomatok - https://github.com/zolomatok/Async @ 01a23b4efc5f5e7f792d93460a56c5c4a08033a6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
use_frameworks!

target 'Johnny iOS' do
    platform :ios, '8.0'
    pod 'AsyncSwift', :git => 'https://github.com/zolomatok/Async'
end

target 'Johnny macOS' do
    platform :osx, '10.10'
    pod 'AsyncSwift', :git => 'https://github.com/zolomatok/Async'
end

target 'Johnny tvOS' do
    platform :tvos, '9.0'
    pod 'AsyncSwift', :git => 'https://github.com/zolomatok/Async'
end

target 'Johnny watchOS' do
    platform :watchos
    pod 'AsyncSwift', :git => 'https://github.com/zolomatok/Async'
end
```

## Project info

- The lib has **four targets** for ios, osx, tvos and watchos.
- The project builds **fine** for all targets in Xcode.
- The target for iOS depends on UIKit, the OSX target depends on AppKit etc. This is indicated in the single podspec file, which looks like this:

```
Pod::Spec.new do |s|
    s.name        = "Johnny"
    s.version     = "1.0"
    s.summary     = "Elegant Caching in Swift"
    s.homepage    = "https://github.com/zolomatok/Johnny"
    s.license     = { :type => "MIT" }
    s.authors     = { "Zoltán Matók" => "bellamycpt@gmail.com" }

    s.osx.deployment_target = "10.10"
    s.ios.deployment_target = "8.0"
    s.tvos.deployment_target = "9.0"
    s.watchos.deployment_target = "2.0"

    s.source   = { :git => "https://github.com/zolomatok/Johnny", :tag => "1.0"}
    s.source_files = "Johnny/**/*.swift"
    s.requires_arc = true
    s.module_name = 'Johnny'

    s.osx.frameworks = 'AppKit', 'Foundation'
    s.ios.frameworks = 'UIKit', 'Foundation'
    s.tvos.frameworks = 'UIKit', 'Foundation'

    s.dependency 'AsyncSwift'
end
```
- One of the offending files (according to the error message) looks like this:

```
import UIKit

extension UIButton {

    public func imageWithURL(url: String?, placeholder: UIImage? = nil, completion: ((image: UIImage?)->Void)? = nil) {
        self.imageView?.imageWithURL(url, placeholder: placeholder, completion: completion)
    }
}
```

## Project that demonstrates the issue

https://github.com/zolomatok/Johnny

**Comment by segiddins** [comment]
You have to make sure that your source files are appropriate for each individual platform -- right now, the AppKit extensions are being used when building for iOS and the UIKit ones when building for macOS.

**Comment by zolomatok** [comment]
Thanks @segiddins 

In case anyone is wondering, what he meant is that I needed to change the `source_files` attribute in the `podspec` from this:

`s.source_files = "Johnny/**/*.swift"`

To this:

```
    s.osx.source_files = 'Johnny/*.swift', 'Johnny/Extensions/common/*.swift', 'Johnny/Extensions/macOS/*.swift'
    s.ios.source_files = 'Johnny/*.swift', 'Johnny/Extensions/*.swift', 'Johnny/Extensions/common/*.swift'
    s.tvos.source_files = 'Johnny/*.swift', 'Johnny/Extensions/*.swift', 'Johnny/Extensions/common/*.swift'
    s.watchos.source_files = 'Johnny/*.swift', 'Johnny/Extensions/common/*.swift', 'Johnny/Extensions/UIColor.swift', 'Johnny/Extensions/UIImage.swift'
```

Either the podspec guide is really lacking in information or I couldn't find anything about this, since I basically had to guess  whether you can do something like 's.osx.source_files'. Even the mentioning of this drill down pattern is omitted from the official guide, I just happened to see it on some blog or forum post.

**Comment by orta** [comment]
The guides aren't set in stone, if you have some ideas for improvement - please send up a PR 👍

**Comment by zolomatok** [comment]
@orta I'd seriously love to, but I'm talking about [these](https://guides.cocoapods.org/making/specs-and-specs-repo.html) guides. Or are there guides on github I don't know about? Or is the site also on gh?

**Comment by segiddins** [comment]
Those guides pull from the API docs in https://github.com/CocoaPods/Core
