### ISSUE TITLE
"pod setup" takes ridiculously long time

### ISSUE THREAD

**Issue by krypt-lynx** [CocoaPods/CocoaPods#5674]
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Full uninstall of CocoaPods
pod setup --verbose

## What did you expect to happen?

pod will ready to use in, let say, one minute.

## What happened instead?

It still cloning master repo. For an hour at current moment.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F1808)
       Xcode : 7.1 (7B91b)
         Git : git version 2.3.5
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

### Installation Source

```
Executable Path: /usr/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by segiddins** [comment]
There's nothing really we can do about that -- using the CocoaPods master repository requires cloning it, the speed of which depends heavily on your network.

**Comment by krypt-lynx** [comment]
There is partial git repo cloning available, maybe you can use it?

**Comment by orta** [comment]
Afraid not, we've been there and it's caused a lot of trouble - http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/
