### ISSUE TITLE
Project containing multiple headers with the same name doesn't create header build phase as expected

### ISSUE THREAD

**Issue by dlo** [CocoaPods/CocoaPods#5675]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I created a custom podspec for an outdated library and ran pod install. The podspec is located at: https://gist.github.com/dlo/f04456857ff2068f54116f5add681436
## What did you expect to happen?

I expect Cocoapods to copy over the correct, individual header files. E.g.,

<img width="545" alt="screen shot 2016-07-26 at 11 40 05 am" src="https://cloud.githubusercontent.com/assets/38447/17146871/b68d2996-5325-11e6-934e-eae65be0c2c9.png">
## What happened instead?

The library contains multiple header files with the same name, but in different directories. The generated project file header build phase, instead of copying over just one of each to the correct path, copies over multiple copies of the last file encountered with that name. Screenshot:

<img width="563" alt="screen shot 2016-07-26 at 11 37 42 am" src="https://cloud.githubusercontent.com/assets/38447/17146799/62057e64-5325-11e6-86f6-e1e72d8c996c.png">
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.0
Ruby lib dir : /Users/dan/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ef84ed0986a40351f8a99abea86862529d0c4455
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-playgrounds : 1.2.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by segiddins** [comment]
You'll probably want to use http://guides.cocoapods.org/syntax/podspec.html#header_mappings_dir for your podspec, in that case.

**Comment by dlo** [comment]
@segiddins That's what I'm using...

**Comment by segiddins** [comment]
I don't believe you can specify different mappings dirs for different subspecs

**Comment by dlo** [comment]
It does actually seem to work. Not sure what I changed but deleting the Cocoapods cache seemed to fix it. Is there any way to specify the order of the headers? The build is still not compiling since an internal library is expecting one of the headers, but getting another.

<img width="563" alt="screen shot 2016-07-26 at 2 41 05 pm" src="https://cloud.githubusercontent.com/assets/38447/17152789/fe8dc6b0-533e-11e6-807a-e9ea17d0d9d3.png">

**Comment by segiddins** [comment]
What do you mean, the order of the headers?

**Comment by dlo** [comment]
In this project, there are certain imports which are ambiguous since there are multiple headers with the same name. For instance, when I compile the project, certain imports, e.g., 

```objc
#include <zxing/MultiFormatReader.h>
```

*seem* to work because that file does exist, but Xcode pulls in the incorrect one since the first header in that list I pasted above is *not* the one it's really looking for (in this case, it needs the one in zxing/cpp/core/src/zxing, NOT the one in zxing/iphone/ZXingWidget/Classes).

In the Xcode UI, if you drag the correct "MultiFormatReader.h" (in zxing/cpp/core/src/zxing) above the other one, the project compiles correctly. Is there any way to specify in what order these headers appear in the project file?

**Comment by dlo** [comment]
Could we reopen this issue?

**Comment by segiddins** [comment]
@samdmarshall do you know if using duplicate public header names like that is supposed to work?

**Comment by samdmarshall** [comment]
I don't think so because there is no way to accurately distinguish between them unless you are using relative import paths instead of just a direct import (doing `#import "zxing/cpp/core/src/zxing/MultiFormatReader.h"` would work whereas `#import "MultiFormatReader.h"` would not).
