### ISSUE TITLE
CocoaPods 1.x is incompatible with old podfiles

### ISSUE THREAD

**Issue by krypt-lynx** [CocoaPods/CocoaPods#5676]
[🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

CocoaPods 1.x is incompatible with old podfiles because it requares target block. In makes  impossible to switch back in git history and test some version without additional manipulations

## What did you do?

Tried to install pods using podfile without target block in it.

## What did you expect to happen?

Successful installation of pods.

## What happened instead?

pods is not installed

```
Analyzing dependencies
[!] The dependency `AFNetworking` is not used in any concrete target.
The dependency `ReactiveCocoa (= 2.4.7)` is not used in any concrete target.
The dependency `SDWebImage` is not used in any concrete target.
The dependency `TWMessageBarManager` is not used in any concrete target.
The dependency `DZNPhotoPickerController/Editor` is not used in any concrete target.
The dependency `SocketRocket` is not used in any concrete target.
The dependency `CocoaAsyncSocket` is not used in any concrete target.
The dependency `JSQMessagesViewController` is not used in any concrete target.
The dependency `BlocksKit/Core` is not used in any concrete target.
The dependency `OrderedDictionary` is not used in any concrete target.
The dependency `Masonry (= 0.6.2-k-1)` is not used in any concrete target.
The dependency `CocoaLumberjack (= 2.2.0-k-2)` is not used in any concrete target.
```

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.7.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories 
<private repos was there>
               master - https://github.com/CocoaPods/Specs.git @ 3531d9883174ee429cbcff5f20ce2264a1d8a518
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :'ios', '8.0'
inhibit_all_warnings!
use_frameworks!

source 'http://github.com/krypt-lynx/pod_Specs.git'

pod 'AFNetworking'
pod 'ReactiveCocoa', '2.4.7'
pod 'SDWebImage'
pod 'TWMessageBarManager'
pod 'DZNPhotoPickerController/Editor'
pod 'SocketRocket'
pod 'CocoaAsyncSocket'
pod 'JSQMessagesViewController' 
pod 'BlocksKit/Core'
pod 'OrderedDictionary'
pod 'Masonry', '0.6.2-k-1'
pod 'CocoaLumberjack', '2.2.0-k-2'
```

**Comment by krypt-lynx** [comment]
By the way:
Insertion of private urls in debug output is a bad idea

**Comment by orta** [comment]
Yep, this isn't a bug - we conform to Semantic Versioning, so used the 1.0 release to break backwards compatibility - this is covered in http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/ and http://blog.cocoapods.org/CocoaPods-1.0/

**Comment by krypt-lynx** [comment]
Old versions of podfiles in repository wasn't magically updated. So, we need some way to install pods with legacy version of podfile.

Now a can't just checkout old version of project from repo and test it. Now I need to fix podfile in nontrivial way every time.

**Comment by segiddins** [comment]
or you can extract the CocoaPods version from the Podfile.lock and use that to determine what version of the gem you use

**Comment by krypt-lynx** [comment]
Only one version of CocoaPods can be installed in system simultaneously, isn't it?

**Comment by segiddins** [comment]
No, CocoaPods is installed via RubyGems which supports installing multiple gem versions simultaneously, and you can invoke different installed versions of the `pod` command via `pod __$VERSION__ install`

**Comment by orta** [comment]
Or you can use [a Gemfile](https://guides.cocoapods.org/using/a-gemfile.html)

**Comment by krypt-lynx** [comment]
I wasn't known about it. Thanks

**Comment by KBvsMJ** [comment]
I was this operation in the podfile：
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target "targetprojectname" do

pod "AFNetworking"


end
