### ISSUE TITLE
pod install not cloning dependencies into the Pods directory

### ISSUE THREAD

**Issue by croach** [CocoaPods/CocoaPods#568]
I just decided to give cocoapods a try and it doesn't seem to work for me. I'm on a Mac using OS X v10.7.4 and I've tried using cocoapods with both the system ruby (v1.8.7) and with a fresh install of the latest ruby (v1.9.3-p194) using rbenv and ruby-build and in both cases whenever I call `pod install` it creates the Pods directory and the proper workspace, but the source code folder for the dependency within the Pods folder is completely empty. My Podfile is listed below:

``` ruby
# Podfile

platform :osx
pod 'AFNetworking'
```

The output from running `pod install --verbose` is listed below:

```
Resolving dependencies of `./Podfile'

Updating spec repositories
Updating spec repo `master'
  $ /usr/local/bin/git pull
  Already up-to-date.

Resolving dependencies for target `default' (OS X 10.6)
  - AFNetworking

Downloading dependencies

-> Installing AFNetworking (1.0)
 > Cloning git repo
   $ /usr/local/bin/git rev-list --max-count=1 1.0RC3
   ac19057c72c5d805112c0f32b021053aad34cf56
   $ /usr/local/bin/git init
   Initialized empty Git repository in /Users/croach/Developer/cocoa/AirBoard/Pods/AFNetworking/.git/
   $ /usr/local/bin/git remote add origin
   '/Users/croach/Library/Caches/CocoaPods/Git/a7f129229d47b74a225e1e2ed0bc604f35d71ac7'
   $ /usr/local/bin/git fetch origin tags/1.0RC3
   From /Users/croach/Library/Caches/CocoaPods/Git/a7f129229d47b74a225e1e2ed0bc604f35d71ac7
    * tag               1.0RC3     -> FETCH_HEAD
   $ /usr/local/bin/git reset --hard FETCH_HEAD
   HEAD is now at ac19057 Merge branch 'master' of github.com:AFNetworking/AFNetworking
   $ /usr/local/bin/git checkout -b activated-pod-commit
   Switched to a new branch 'activated-pod-commit'
 > Installing documentation
[!] Skipping documentation generation because appledoc can't be found.

Generating support files
  - Running pre install hooks
  - Generating project
  - Installing targets
    - Generating xcconfig file at `./Pods/Pods.xcconfig'
    - Generating prefix header at `./Pods/Pods-prefix.pch'
    - Generating copy resources script at `./Pods/Pods-resources.sh'
  - Running post install hooks
  - Writing Xcode project file to `./Pods/Pods.xcodeproj'
  - Writing lockfile in `./Podfile.lock'

[!] From now on use `AirBoard.xcworkspace'.
```

Judging by the state of the `./Pods/AFNetworking` folder it would appear that none of the git commands are working. I am seeing the AFNetworking library cloned in the `Caches` directory, but the `AFNetworking` directory is not a git repository and is completely empty.

I'd love any help you could give on this issue, as cocoapods looks fantastic, but as of right now I am still stuck with downloading the individual projects and adding their source to Xcode by hand.

Thanks for your help.

**Comment by guptapriyanka** [comment]
I am running into the same issue. I am trying to test my own project and this is how I am including my source files:
s.source_files = 'ProjectName/**/*.{h,m}'

When I run pod install, I only get the readme. What am I doing wrong?

**Comment by guptapriyanka** [comment]
Just fixed it. Deleting the pods folder and reinstalling it fixed it for me.

**Comment by evictor** [comment]
@guptapriyanka thanks, I'm in Pods 1.2.1 and still had this issue -- and deleting pod folders prior to `pod install` fixed.

**Comment by epasquier-ecocea** [comment]
Hello, I still have the issue with Pods 1.2.1 and HanekeSwift dependencies (branch feature/swift3). Haneke folder in Caches (~/Library/Caches/Cocoapods/) contains only Licence & Readme. Cocoapods copies only these files in Pods folder of project and so the project has missing dependencies.

I resolved the issue by clean the cache with ```pod cache clean```. 

Is Cocoapods cleaned the Cache automatically ? Or macOs ?
