### ISSUE TITLE
Build phase issue with Watch target / extension since CocoaPods 1.0.0

### ISSUE THREAD

**Issue by fcapon** [CocoaPods/CocoaPods#5681]
# Report

## What did you do?

My app is an universal bin with Watch target and extension. I'm using Fastlane to deploy my app.
watchOS Deployment Target : watchOS 2.0
Watch base SDK : Latest watchOS (watchOS 2.2)
iOS Deployment Target : 7.1
iOS Base SDK : Latest iOS (iOS 9.3)
Xcode version : 7.3.0 (7D175)
CocoaPods version : 1.0.1
Fastlane version : 1.98.0

## What did you expect to happen?

Build my app to deploy it.

## What happened instead?

The compiling phase failed with Watch pods only. Here is the message:
> ❌  ld: library not found for -lUIColor-HexString-watchOS
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Sometimes it's another library, but always about Watch:
> ❌  ld: library not found for -lMantle-watchOS
> ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Here is the command line executed by Fastlane:
`xcodebuild -workspace ./MyApp.xcworkspace -scheme MyApp -destination 'generic/platform=iOS' -archivePath './fastlane/DerivedData/.xcarchive' archive CODE_SIGN_IDENTITY=iPhone\ Distribution:\ XXXX | tee /Users/Shared/Jenkins/Library/Logs/gym/MyApp-MyApp\MyApp.log | xcpretty`

**I can fix it if I add the _libPods-Watch.a_ to _Linked Frameworks and Libraries_ for my _Watch Extension_ and not _Watch target_ as CocoaPods 1.0.1 do it.** But of course, a pod install undo my changes.
I noticed that CocoaPods < 1.0.0 add it to Watch Extension, and it's why it was working before my CocoaPods update.

I also try with Xcode 7.3.1, CocoaPods 1.0.0, CocoaPods 1.1.0.beta.1 with no success...

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : XXXXX
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
slather               : 2.3.0
```

### Podfile

```ruby
platform :ios, '7.1'

source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all Pods
inhibit_all_warnings!

target :'MyApp' do
	pod 'AFNetworking'
	pod 'Azetone', '~> 4.0'
	pod 'AzureEngagement', '~> 3.2'
	pod 'BlocksKit/Core'
	pod 'CocoaLumberjack', '~> 2.x'
	pod 'ComScore', '~> 3.1503.24'
	pod 'Crashlytics'
	pod 'EDColor'
	pod 'EAnalytics'
	pod 'Fabric'
	pod 'Facebook-iOS-SDK', '3.24.4'
	pod 'IdentityMapper'
	pod 'IVPlayer'
	pod 'JHChainableAnimations', '~> 1.3.0'
	pod 'JLRoutes'
	pod 'JSBadgeView'
	pod 'KVOController'
	pod 'libextobjc/EXTScope'
	pod 'LiveServer', '~> 1.5.x'
	pod 'NibLoader'
	pod 'MagicalRecord'
	pod 'Mantle', '~> 1.x'
	pod 'Masonry'
	pod 'MBProgressHUD'
	pod 'MMDrawerController'
	pod 'MMDrawerController+Storyboard'
	pod 'MWFeedParser/NSString+HTML'
	pod 'PromiseKit'
	pod 'PromiseKit-AFNetworking'
	pod 'ReactiveCocoa'
	pod 'SimpleKeychain'
	pod 'SocketRocket', '~> 0.3.1-beta2'
	pod 'SSPullToRefresh'
	pod 'SwipeView'
	pod 'Typhoon', '~> 2.3.x'
	pod 'UIColor-HexString'
	pod 'UIImage+Additions', '~> 2.1.x'
	pod 'UIKitCategoryAdditions', '~> 0.0.1'
	pod 'UIScrollView-InfiniteScroll'
	pod 'WEPopover'
end

target :'MyAppTests' do
	pod 'Kiwi'
end

target :'Watch' do
  platform :watchos
  
  pod 'BlocksKit/Core'
  pod 'EDColor'
  pod 'IdentityMapper'
  pod 'Mantle', '~> 1.x'
  pod 'MWFeedParser/NSString+HTML'
  pod 'UIColor-HexString'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name != 'AppStore'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1']
            end
        end
    end
end
```

## Project that demonstrates the issue

I can't share you the project, it's a private one.

**Comment by segiddins** [comment]
Please share a sample project we can use to debug the issue, thanks!

**Comment by neonichu** [comment]
Closing because of lack of response.
