### ISSUE TITLE
CocoaPod page not updating to reflect new README.md

### ISSUE THREAD

**Issue by sean7512** [CocoaPods/CocoaPods#5684]
* [X ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
The README file of the new version of my library, [RestEssentials](https://cocoapods.org/pods/RestEssentials) is not updating on the CocoaPods page.  The CocoaPods page is showing the old README file and is not accurate.

Looks like this was broken before: https://github.com/CocoaPods/CocoaPods/issues/5137

**Comment by orta** [comment]
This isn't a CocoaPods/CocoaPods bug, it should go on [cocoapods/cocoadocs.org](https://github.com/cocoapods/cocoadocs.org) - however, I triggered a re-deploy and it fixed itself 👍

**Comment by sean7512** [comment]
@orta Thank you so much! 👍
