### ISSUE TITLE
WatchOS dependencies require manual setting of Development signing certificate after install

### ISSUE THREAD

**Issue by andrewloyola** [CocoaPods/CocoaPods#5686]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Using the 1.1.0b1 cocoapods master, i used 'pod install' to install dependencies to a project with both iOS9 and WatchOS2 Targets.  The dependencies support both watchOS2 and iOS builds already.

## What did you expect to happen?

Pods install and build for all platforms without signing errors.

## What happened instead?

The iOS version seemed to work fine, but when building in XCode8b3 with the Build Only "Generic iOS Device" config, the iOS targets build without any changes, but the watchOS targets show all show this error text:

**Dependency Analysis Error
No signing certificate 'iOS Development' found
No 'iOS Development' signing certificate with a private key was found.**

If I click "Automatically manage signing in each individual target's General settings in XCode, it resolves the issue so the build proceeds, but it has to be redone on every pod install.  This is not necessary for the iOS targets.

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 8.0 (8S174q)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : cocoapods-specs - https://github.com/Openfolio/cocoapods-specs.git @ b638ca93d4bc1cc155137417238f4865cbad1831
               cocoapods-specs-github - https://github.com/Openfolio/cocoapods-specs.git @ b638ca93d4bc1cc155137417238f4865cbad1831
               master - https://github.com/CocoaPods/Specs.git @ 9330eaca564539ca4ae600ba18ff4a3aea7e9baa
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def shared_pods_watch
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift2.3'
    pod 'SwiftDate'
    pod 'SwiftyJSON'
end

def shared_pods
    
    #Logging
    pod 'CocoaLumberjack/Swift'
end


target 'watchapp Extension' do
    platform :watchos, '2.0'
    shared_pods_watch
    shared_pods
end

target 'WatchPodIssue' do
    platform :ios, '9.0'
    
    shared_pods
end
```

## Project that demonstrates the issue

https://github.com/andrewloyola/WatchPodIssueDemo

**Comment by segiddins** [comment]
We might just need to update the Xcodeproj defaults for Xcode 8

**Comment by neonichu** [comment]
I think the issue lies in the fact that we're only setting this to empty for `iphoneos`: https://github.com/CocoaPods/CocoaPods/pull/5528/files#diff-38f6da95e04f241c354bdac3cee39386R57 — probably need to do the same for `watchos` and `appletvos`.
