### ISSUE TITLE
Podspec validation fails for Pre-Compiled Framework in Swift

### ISSUE THREAD

**Issue by pragmapilot** [CocoaPods/CocoaPods#5689]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

My goal is to have a Pre-Compiled Swift Framework created with the 'pod lib create' command.

After configuring the podspec with the appropriate (as per official documentation) entries to generate a vendored framework the pod spec validation fails.

## What did you do?

```
pragmapilot@Kilmister:pod lib create PPPreCompiledFramework
Cloning `https://github.com/CocoaPods/pod-template.git` into `PPPreCompiledFramework`.
Configuring PPPreCompiledFramework template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and double click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > 
swift
Would you like to include a demo application with your library? [ Yes / No ]
 > 
yes
Which testing frameworks will you use? [ Quick / None ]
 > 
quick
Would you like to do view based testing? [ Yes / No ]
 > No

Running pod install on your new library.

Analyzing dependencies
Fetching podspec for `PPPreCompiledFramework` from `../`
Downloading dependencies
Installing Nimble (3.2.0)
Installing PPPreCompiledFramework (0.1.0)
Installing Quick (0.9.2)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `PPPreCompiledFramework.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 3 total pods installed.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'PPPreCompiledFramework/Example/PPPreCompiledFramework.xcworkspace'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

```
At this point I edited the podspec file so it looks like the one [here](https://github.com/pragmapilot/PPPreCompiledFramework/blob/master/PPPreCompiledFramework.podspec), namely I added the `preserve_paths, public_header_files, vendored_frameworks`entries.

At this point I was able to build the project in Xcode successfully.

## What did you expect to happen?

Podspec validation to be successful. 

The Xcode project 'Pods' has a target for the framework `PPPreCompiledFramework.framework`. This target is built when the project is built and sits on the expected location. See image below:

![framework_builds_and_exists_on_file_system](https://cloud.githubusercontent.com/assets/5132870/17204508/dba4b932-549d-11e6-8b8c-704f8352655f.png)

## What happened instead?

Podspec validation failed with the following message:

```
pragmapilot@Kilmister:pod lib lint

 -> PPPreCompiledFramework (0.1.0)
    - ERROR | file patterns: The `preserve_paths` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `vendored_frameworks` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `public_header_files` pattern did not match any file.

[!] PPPreCompiledFramework did not pass validation, due to 3 errors.
You can use the `--no-clean` option to inspect any issue.
```

I also ran the `pod lib lint --no-clean` command.

```
pragmapilot@Kilmister:pod lib lint --no-clean

 -> PPPreCompiledFramework (0.1.0)
    - ERROR | file patterns: The `preserve_paths` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `vendored_frameworks` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `public_header_files` pattern did not match any file.

Pods workspace available at `/var/folders/7t/fnk86byn4rl53cjdq3d6qpcr0000gn/T/CocoaPods/Lint/App.xcworkspace` for inspection.

[!] PPPreCompiledFramework did not pass validation, due to 3 errors.

```
Opening the App.xcworkspace (`open /var/folders/7t/fnk86byn4rl53cjdq3d6qpcr0000gn/T/CocoaPods/Lint/App.xcworkspace`) I can see it also contains a target for the framework and the product is built on the expected location. See image below:

![framework_builds_and_exists_on_file_system_app_xcworkspace](https://cloud.githubusercontent.com/assets/5132870/17204667/b830c1a2-549e-11e6-8773-247f9a557ab7.png)

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 78c5846984640964710489f7ee29d7ffee3bdad6
               talkdesk - ssh://git@github.com/Talkdesk/cocoapods.git @ ad405d7ab57a6b3fe404fd8c67e1963c41e25e99
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[Demo Project](https://github.com/pragmapilot/PPPreCompiledFramework)

**Comment by neonichu** [comment]
I think you're misunderstanding how `vendored_frameworks` is working. You're specifying the path `PPPreCompiledFramework/PPPreCompiledFramework.framework`, yet, this framework does not exist in your repo — that's also what the linter error is trying to convey. If you have ideas on how to clarify this in the guides, please open an issue or a PR with suggestions.

It feels like what you're trying to accomplish is building a framework from a Pod, you might want to check out the cocoapods-packager plugin to do that.

**Comment by pragmapilot** [comment]
Thanks a lot. 
You're right: I misunderstood the `vendored_frameworks` as I thought it would do what cocoapods-packager does. 

My goal was in fact to build the framework from the Pod which cocoapods-packager helped me doing the trick.
