### ISSUE TITLE
Advice. The developer wants a solution to change pod library between source and binary.

### ISSUE THREAD

**Issue by mdsb100** [CocoaPods/CocoaPods#5690]
We have already do it in our private repo.
Using cocoapods-packager to build binary.
podspec like this:
```
  if ENV['IS_SOURCE'] || ENV["#{s.name}_SOURCE"]
      puts '-------------------------------------------------------------------'
      puts "Notice:#{s.name} is source now"
      puts '-------------------------------------------------------------------'
      s.source_files = 'Pod/Classes/**/*'
  else
      puts '-------------------------------------------------------------------'
      puts "Notice:#{s.name} is binary now"
      puts '-------------------------------------------------------------------'
      s.source_files = 'Pod/Classes/*.h'
      s.public_header_files = 'Pod/Classes/*.h'
      s.ios.vendored_libraries = "Pod/lib/lib#{s.name}.a"
  end
```
Install:
```
IS_SOURCE=1 pod install
```
or
```
AFNetwork_SOURCE=1 pod install
```
or 
Install binary if the pod library provide.
```
pod install
```
The two questions is:
1. It must be in private repo, because there is a json file in github repo and there is a podspec file in private repo.
2. If I  am going to change pod between source and binary, I have to clean cache first and remove Pods/ dictionary.

The developer wants a solution to change pod between source and binary.

Be careful using macro.

If someone read Chinese, please check [this](http://www.yiqixiabigao.com/2016/07/15/ios-cocoapodszu-jian-ping-hua-er-jin-zhi-hua-fang-an-ji-xiang-xi-jiao-cheng/)

When we do 'pod install', the project will rebuild all pods. Even if we only change one pod`s version. Carthage can solve this trouble.
If CocoaPods@2.0 can support this feature, it can solve this trouble too. I am very happy to listen it.

Please reply me. 

Thanks!

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

For an example of switching between binary/source see HockeySDK's solution - https://cocoapods.org/?q=hockeysdk

**Comment by alexlee002** [comment]
This is a useful feature for a big project that modularize the business to lot's of private pods.
