### ISSUE TITLE
How to resolve the issue [!] The version of CocoaPods used to generate the lockfile (1.0.1) is higher than the version of the current executable (1.0.0). Incompatibility issues may arise.

### ISSUE THREAD

**Issue by pradeepb28** [CocoaPods/CocoaPods#5693]
[!] The version of CocoaPods used to generate the lockfile (1.0.1) is higher than the version of the current executable (1.0.0). Incompatibility issues may arise.

The moment I updated my cocoa pods to v 1.0.0 and the executed pod install.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by thehalvo** [comment]
Yeah we get your point, and I agree. StackOverflow is where questions like this should be answered. But now Google has ranked this high in the results while searching for this issue. So maybe linking to a StackOverflow answering this question, or simply answering it here would be appropriate for your audience.
