### ISSUE TITLE
spec lint source path error (cocoa pod 1.0.1) while create pod

### ISSUE THREAD

**Issue by alexwillrock** [CocoaPods/CocoaPods#5694]
i need create cocoa pod and have some problem. In Xcode create Framework, after add my .h and .m files, compile. init pod spec and rewrite some parameters. After pod spec lint in console in and see error 

> "ERROR | [iOS] file patterns: The source_files pattern did not match any file." 

But my framework created in directory release.

my struct folder "Classes" 
<img width="945" alt="screen shot 2016-07-27 at 21 39 15" src="https://cloud.githubusercontent.com/assets/6507402/17239583/625403a6-558f-11e6-8c8b-4185fb0086c8.png">

my struct folder "Classes" 
>` s.source_files  = "Classes/**/**/*.{h,m}", "Classes/**/*.{h,m}", "Classes/*.{h,m}"`

pls help me

**Comment by neonichu** [comment]
From the screenshot, this looks correct. Please note that CocoaPods does not use your existing Xcode project at all, so the fact that you can build that doesn't have much significance.

I don't see a way for us to debug this further without a project that reproduces this.

**Comment by neonichu** [comment]
Closing because of lack of response.
