### ISSUE TITLE
how can I read a defined variable in podfile

### ISSUE THREAD

**Issue by jaychen04** [CocoaPods/CocoaPods#5695]
How can I read a defined variable in podfile? For example,platform :
ios, '8.0'
$myversion = ‘1.0’
target 'rubytest' do
pod 'AFNetworking', '~> 3.0'
end

myversion is the custom of a variable,in which module i can read it?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
