### ISSUE TITLE
Deleting a framework from the podfile causes the project to no longer build. 

### ISSUE THREAD

**Issue by samjohn** [CocoaPods/CocoaPods#5696]
🌈
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?
- Create a new project. 
- Install Cocoapods. 
- Add a pod (Appsee)
- Reopen the XCWorkspace
- Add a framework target
- Write the framework target into the podfile:

```
target 'TestProj' do
  pod 'Appsee'
  target 'MyFramework' do
  end
end
```
- pod install
- run the app (this causes another error, will update this when I add the issue for that) 
- delete the `target 'MyFramework'` lines from the podfile
- pod install
- run the project
## What did you expect to happen?
- the app should build and run
## What happened instead?

Could not run the app and got this error: 

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.4.3
Ruby lib dir : /Users/samanthajohn/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4c3950af85f7c7bca089e06e45e1284634599d0d
```
### Installation Source

```
Executable Path: /Users/samanthajohn/.rbenv/versions/2.2.2/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoapodsFrameworkBug' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Appsee'

end
```
## Project that demonstrates the issue

https://github.com/samjohn/CocoapodsBug

**Comment by orta** [comment]
There's been a lot of work around linking to frameworks in the 1.1 release, can you verify with that?
