### ISSUE TITLE
Duplicate symbols error when using a framework target with certain pods

### ISSUE THREAD

**Issue by samjohn** [CocoaPods/CocoaPods#5699]
🌈
* [x]  I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
- create a new  xcodeproject
- `pod init`
- `pod install`
- open the .xcworkspace file
- add a framework, F1
- write the podfile: 
```
target 'TestProj' do
  pod 'Appsee'
  target 'F1' do
    pod 'DateTools'
  end
end
```
- `pod install`
- run the app

**Note:** the important thing here is to use the `Appsee` pod or the `HockeySDK` pod. I'm sure there are others too. If you switch out `Appsee` for `MTGeometry` you will not get this issue

## What did you expect to happen?

Expect the app to run

## What happened instead?
Got a bunch of duplicate symbol error messages 
``` Class UVVideoRecorder is implemented in both 
/Users/samanthajohn/Library/Developer/Xcode/DerivedData/CocoapodsFrameworkBug-bigvyozqsetprfchpgayyjowttgt/Build/Products/Debug-iphonesimulator/F1.framework/F1 and /Users/samanthajohn/Library/Developer/CoreSimulator/Devices/5ECED776-47E3-48A4-8F1F-6CA8CAD47B11/data/Containers/Bundle/Application/3061A8B5-C4FE-4403-A0E5-C4C5037DD06A/CocoapodsFrameworkBug.app/CocoapodsFrameworkBug. One of the two will be used. Which one is undefined.```

Messages like this for every single class in the Appsee pod. 

## CocoaPods Environment

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.4.3
Ruby lib dir : /Users/samanthajohn/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4c3950af85f7c7bca089e06e45e1284634599d0d
```

### Installation Source

```
Executable Path: /Users/samanthajohn/.rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoapodsFrameworkBug' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Appsee'
  
  target 'F1' do
      pod 'DateTools'
  end
  # Pods for CocoapodsFrameworkBug

end
```

## Project that demonstrates the issue

https://github.com/samjohn/CocoapodsBug/tree/f/before-framework

The branch: `f/before-framework` demonstrates the issue. It's on a branch because I demonstrated a different issue in the master branch: https://github.com/CocoaPods/CocoaPods/issues/5696

**Comment by neonichu** [comment]
I don't think this can be considered a bug. You're requesting that the same Pod is integrated into both your app and your framework target, this Pod happens to include a static binary, so this is being added to both targets. 

There's really no other way to behave for CocoaPods in this case, safe for rejecting this scenario, which doesn't seem necessary. Most likely, you won't see any repercussions from this as both copies of the class are equivalent.

**Comment by samjohn** [comment]
Hi @neonichu, apologies, I failed to mention that the project will not build in with duplicate symbols. 

Is there a workaround if you need to share code between frameworks? So far I have not been able to upgrade to Cocoapods 1.0 due to this issue. Looking at the [docs](https://guides.cocoapods.org/syntax/podfile.html) it seemed like the recommended Podfile implementation is to nest frameworks in a main target. If you have a project with frameworks that need to share pods (even the test framework) this results in the project not being able to build.

**Comment by neonichu** [comment]
Yah, that is the recommendation for most Pods, however static binaries are a special case. You'll probably be fine by just specifying it as a dependency of the framework, but that can also depend on the binary in question. 

Ideally, all vendors shipping binaries will eventually provide dynamic frameworks where this wouldn't even happen.
