### ISSUE TITLE
when i input pod install  he gives me this

### ISSUE THREAD

**Issue by zeroClub** [CocoaPods/CocoaPods#5701]
/usr/bin/curl -f -L -o /var/folders/y1/trq1ym9d4zj08zmpdcjvp8nh0000gn/T/d20160802-416-ougf6n/file.zip http://lbs.amap.com/wp-content/uploads/2014/06/AMap_iOS_API_3DMap_Lib_V2.4.0.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

**Comment by DanToml** [comment]
@zeroClub It looks like you're trying to install a binary pod that doesn't exist? - If not, can you fill in the [Issue Template](https://raw.githubusercontent.com/CocoaPods/CocoaPods/master/.github/ISSUE_TEMPLATE.md) so we can identify the problem.

**Comment by neonichu** [comment]
Closing because of lack of response.
