### ISSUE TITLE
[CocoaPods 1.0.1] Can't build *Tests scheme for pods; header files missing

### ISSUE THREAD

**Issue by wkoszek** [CocoaPods/CocoaPods#5710]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I've upgraded to the 1.0.1 CocoaPods. I'm able to build my project fine, however I can no longer build unit tests. XCode complains that several several header files from the Pods I'm using are missing.

## What did you expect to happen?

I expected that upon an upgrade I'll be able to build both the app scheme, and the tests scheme.

## What happened instead?

Regression has been introduced from 0.39.0 version, which used to work fine for me, and with 1.0.1 there are issues with finding header files.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.4
Ruby lib dir : /Users/wk/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1dfc15de5e4fd6b8b535a03181b8a47c13c10ea8
```

### Installation Source

```
Executable Path: /Users/wk/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

You can see the issue here in this project:

[sensorama_cocoapods_1.0.1.txt](https://github.com/CocoaPods/CocoaPods/files/400937/sensorama_cocoapods_1.0.1.txt)

Examples:

```
/Users/wk/r/tmp/sensorama-ios/Sensorama/Sensorama/SRDataFile.m:9:9: 
'MPMessagePack/MPMessagePack.h' file not found
...
 /Users/wk/r/tmp/sensorama-ios/Sensorama/Sensorama/SRDataPoint.h:13:9: 'Realm/Realm.h' file not found
...
/Users/wk/r/tmp/sensorama-ios/Sensorama/Sensorama/SRUtils.m:16:9: 
...
'GBDeviceInfo/GBDeviceInfo.h' file not found
'InAppSettingsKit/IASKAppSettingsViewController.h' file not found
```
The complete source code of the project:

https://github.com/wkoszek/sensorama-ios
https://github.com/wkoszek/sensorama-ios/blob/master/Sensorama/Podfile

**Comment by benasher44** [comment]
@wkoszek can you try updating your Podfile to use target inheritance like this:

```
target 'Sensorama' do
  mypods
  target 'SensoramaTests' do
    inherit! :search_paths
  end
  target 'SensoramaUITests' do
    inherit! :search_paths
  end
end
```

**Comment by wkoszek** [comment]
@benasher44 Changed it as you suggested. Full podfile: 

https://gist.github.com/wkoszek/197b20ca587f9c8ef8daf438aed086ce

Doesn't seem to help. Full log:

[sensorama_with_upgraded_podfile.txt](https://github.com/CocoaPods/CocoaPods/files/402360/sensorama_with_upgraded_podfile.txt)

**Comment by hiralnaik** [comment]
@benasher44  @wkoszek  I am having the same issue. My project is working fine but when I run unit tests I am seeing the same error with GoogleMaps and OHHTTPStubs. It keeps complaining about "GoogleMaps Module not found."

Below is my podfile

`
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

use_frameworks!
inhibit_all_warnings!

def appCocoaPods
    pod 'SVProgressHUD'
    pod 'GoogleAnalytics'
    pod 'OHHTTPStubs'
    pod 'SWTableViewCell'
    pod 'JSONModel'
    pod 'GoogleMaps'
    pod 'SMCalloutView'
end

target 'apps' do
    winesCocoaPods
    
    target 'appsTests' do
        inherit! :search_paths
    end
end
`

Thanks

**Comment by wkoszek** [comment]
@benasher44 @neonichu So I've done:

```
rm -rf Sensorama.xcworkspace Pods
rm Podfile.lock
pod repo update
pod install
```

I opened the workspace, added schemes for tests and the application (UITests scheme was present by default), marked them shared, marked them both for "Running".

Same issue. I can't seem to find a workaround for this.

**Comment by wkoszek** [comment]
@neonichu can you unmark it as "awaiting input" ?

**Comment by benasher44** [comment]
@wkoszek I cloned sensorama, and running tests works fine for me. Here's what I did. After cloning the repo, I `cd`'d into the Sensorama folder and ran `pod install` (running 1.0.1). After this, I opened the workspace and ran `command+u` (runs the tests for the current target) with the Sensorama scheme and iPhone 6 simulator for iOS 9.3 selected. It then failed with an error because I don't have a Fabric API key setup. After removing the Fabric build phase, it built and ran the tests just fine (aside from a crash that seems unrelated to this issue).

**Comment by wkoszek** [comment]
@benasher44 This is weird. I have 0 success on El Captain OSX + XCode 7.3.1. Let me try on my Mac Mini today. Which XCode do you have?

**Comment by benasher44** [comment]
It was 7.3.1 running the latest El Cap

**Comment by wkoszek** [comment]
@benasher44 So on my MacMini it's OK too. So I guess it's some transient state on my laptop. Should I try to do something with `pod cache clean` after moving to 1.0.1?

**Comment by wkoszek** [comment]
I've done:

```
pod cache list | grep '^[A-Za-z]' | sed 's/://' | xargs -n 1 pod cache clean
```

and now `pod cache list` is empty. Issue is still there.

**Comment by benasher44** [comment]
@wkoszek have you tried clearing derived data? This often fixes stale-build issues.

To do this in Xcode 7, you can do this by selecting Projects in the Window menu. There, select your project in the left pane, and then click Delete… next to Derived Data in the right pane.

**Comment by hiralnaik** [comment]
I fixed this issue in my project with cocoapods 1.0.1. I am not using 'inherit! :search_paths' for any of the targets. 

Below is my podfile and steps. 
- First delete all your previous cocoapods references. You can also use deintegrate-cocoapods and then delete the workspace as well and derived data as well.
- Install pods again 
- Open workspace 
- Manage scheme
- then click on 'Autocreate Schemes Now', in drop down select workspace project
- let 'Index Processing' finished
- Clean your project and build it
- Try to run unit tests.
- If you still seeing errors, put that library in bridging headers
- Make sure all your unit tests class have `@testable import <Target Name>`
- For stubbing network call, make sure you import library in every tests class 

You may need to change some of the build setting for the project. 
The above approach worked for me. Now it is also running successfully on our devops.

podfile

`workspace '../projectName.xcworkspace'

project 'projectName.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'

inhibit_all_warnings!

pod 'SVProgressHUD'
pod 'GoogleAnalytics'
pod 'OHHTTPStubs', :configurations => ['Debug']
pod 'GoogleMaps'
pod 'GoogleMaps/M4B'


use_frameworks!

target 'projectName' do
end

target 'projectNameTests' do
end
`

**Comment by wkoszek** [comment]
@benasher44 That is it. Made myself this:

$ alias rm_xcode_cache
alias rm_xcode_cache='rm -rf ~/Library/Developer/Xcode/DerivedData/*'

and after I run it, I'm able to build the project again. This is quite unexpected, but thanks for help. I guess we can close this bug report, unless `pod` could somehow warn about this stuff, but I guess not.

@hiralnaik Didn't have to do any of that. Just run the deriver data cleanup command and it just worked for me.

**Comment by benasher44** [comment]
AFAIK we cannot detect this. Supposedly Xcode 8 is better about stale/corrupt derived data.
