### ISSUE TITLE
Unable to install a dependency correctly

### ISSUE THREAD

**Issue by ukelady** [CocoaPods/CocoaPods#5712]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
Run `pod install`

This is my Podfile:
```
platform :ios, '7.0'

target 'PhotoPostExample' do

pod 'TMTumblrSDK'

end
```
## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
TMTumblrSDK should be installed correctly under my XCode project
https://github.com/tumblr/TMTumblrSDK

## What happened instead?

ℹ Please replace this with of what happened instead.  
TMTumblrSDK is not installed correctly. Some files are missing and some code blocks are missing. 

To be more specific, the codes in the following format are all missing

```
#ifdef __ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__ 
....  // some functions
#endif

```

## CocoaPods Environment

And TMSDKConstants.h TMSDKConstants.m are missing (They are in TMTumblrSDK/Core/)

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`
```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cb84754900651ee8c4cdfad42099e4d1aec9d686
               tumblr - https://github.com/tumblr/TMTumblrSDK.git @ a150128526738193a4babb322a8f6063b9cc79b1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '7.0'

target 'PhotoPostExample' do

pod 'TMTumblrSDK'

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.
https://github.com/tumblr/TMTumblrSDK

**Comment by neonichu** [comment]
The files you are referring to are not part of the latest release of this Pod, see <https://github.com/tumblr/TMTumblrSDK/tree/4.0.4/TMTumblrSDK/Core> — see the `:git` option if you want to use newer development versions: <https://guides.cocoapods.org/syntax/podfile.html#pod>
