### ISSUE TITLE
Green-ify Successful pod installation ?

### ISSUE THREAD

**Issue by hamin** [CocoaPods/CocoaPods#5713]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

*NOTE* First brought this issue up in Cocoapods Mac app: https://github.com/CocoaPods/CocoaPods-app/issues/354

Love cocoa pods, longtime user since its first release (back when it was still in MacRuby ;) ). One little thing that I think would be a nice to have. Would it be possible to have the very last line's text color in green? I find myself not being a 100% sure whenever i'm looking at the log. This is what i'm referring to:

![screen shot 2016-08-02 at 12 33 05 pm](https://cloud.githubusercontent.com/assets/28212/17336720/6ba8fbf2-58ad-11e6-970b-8062f0786114.png)

Maybe its just me but would be great to have: "Pod installation complete! There are 9 dependencies from the Podfile and 11 total pods installed." in green. Maybe I'm just getting old :)

More than happy to submit a PR if ppl are cool with the suggestion.

## What did you do?

ℹ Please replace this with what you did.  
Run `pod install`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
I expected the successful installation message to be in green:  "Pod installation complete! There are 9 dependencies from the Podfile and 11 total pods installed."

## What happened instead?

ℹ Please replace this with of what happened instead.  
The Pod installation line was in plain text color (white for command line and and black for the mac app)

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by segiddins** [comment]
A PR doing this would be great, the string should be somewhere in the `Installer`

**Comment by orta** [comment]
Yeah, I'm a 👍

**Comment by hamin** [comment]
awesome, will have an update soon :)

**Comment by hamin** [comment]
lol sorry I didn't get to this sooner great job @schayes04 :) 👍
