### ISSUE TITLE
Modifying certain build settings results in incoherent pods project settings.

### ISSUE THREAD

**Issue by allenhumphreys** [CocoaPods/CocoaPods#5714]
* [✅] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I tried to define a macro for all the pods imported in my project to solve a very specific development pod dependency. I did this via the post install hook like this:
```
  config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ALPHA=1']
```

This was based on various suggestions from stackoverflow.com, etc. 

## What did you expect to happen?

I expected the macro to be added to the targets with no other side effects.

## What happened instead?

The pod project that was generated had various issues. The most obvious is that no deployment target was set. Xcode defaulted to OS X which doesn't work because this is in iOS project.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2b19bf82cb1663f09281a2773bd4d3b489929a32
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 0.5.2
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

abstract_target 'CocoapodsBugAll' do
    platform :ios, '9.0'
    target 'CocoapodsBug' do
        platform :ios, '9.0'
        pod 'Bolts'

        target 'CocoapodsBugTests' do
            platform :ios, '9.0'
            inherit! :search_paths
            # Pods for testing
        end
    end

end

post_install do | installer |
    require 'fileutils'

    installer.pods_project.targets.each do |target|
        # Ensures all targets have the minimum deployment target we choose
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
            if config.name == 'Alpha'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ALPHA=1']
            elsif config.name = 'Jenkins'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'JENKINS=1']
            end
        end

    end
end
```
## Project that demonstrates the issue

https://github.com/allenhumphreys/CocoapodsBug

**Comment by segiddins** [comment]
Does this happen even without the post install hook?

**Comment by allenhumphreys** [comment]
@segiddins It only happens if the post install hook modifies the `GCC_PREPROCESSOR_DEFINITIONS` build setting. It does NOT happen when only modifying the `IPHONEOS_DEPLOYMENT_TARGET`.

**Comment by segiddins** [comment]
The bug here is `config.name = 'Jenkins'`

**Comment by allenhumphreys** [comment]
Oh wow, I'm an idiot. That's why they say put the constants on the left I guess. Thanks a lot. Sorry for your time.

**Comment by segiddins** [comment]
No worries, sorry for the delayed response! (It took me a good ten minutes to find the issue as well :P)
