### ISSUE TITLE
CocoaPods missing new Swift Legacy flag

### ISSUE THREAD

**Issue by philipposslicher** [CocoaPods/CocoaPods#5717]
[* ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Install the 'Material' CocoaPod

## What did you expect to happen?
Dependencies would work correctly

## What happened instead?
Since Cocoapods does not have the ability to specify an option for the new swift legacy flag, not just this, but other ios 10 pods fail to compile.

## CocoaPods Environment

This gives an empty response for some reason.

**Comment by orta** [comment]
Have you tested this on the beta?

**Comment by philipposslicher** [comment]
Yes, latest xcode build. (beta 4)

**Comment by orta** [comment]
Ah sorry, I mean the [CocoaPods 1.1.0 beta](https://rubygems.org/gems/cocoapods/versions/1.1.0.beta.1)

**Comment by philipposslicher** [comment]
Yep

**Comment by philipposslicher** [comment]
Attached is a clean demo project with no changes.
[Pod Test.zip](https://github.com/CocoaPods/CocoaPods/files/405217/Pod.Test.zip)

**Comment by neonichu** [comment]
This is a known issue, we were discussing possible solutions here: #5650

In the meantime, you can use a post-install hook as a workaround:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end
```
