### ISSUE TITLE
Incorrect precedence for prerelease version numbers

### ISSUE THREAD

**Issue by pcantrell** [CocoaPods/CocoaPods#5718]
# Report

It seems that CocoaPods does apply proper precedence rules to alphanumeric prerelease version numbers.

## What did you do? What did you expect to happen?

This pod specification:

    pod 'Siesta', '>=1.0-beta.8a'

…should download Siesta `1.0-beta.8a`.

## What happened instead?

It downloads `1.0-beta.8`.

This specification works, however (no `>=`):

    pod 'Siesta', '1.0-beta.8a'

Perhaps it’s too much to ask for `>=` to work with such a finnicky version number, but if the goal is to follow the Semantic Versioning spec, then this is pretty clearly a bug. From that spec:

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. **Numeric identifiers always have lower precedence than non-numeric identifiers.** A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

(http://semver.org, section 11; emphasis added)

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1012)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/paul/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 10ce80a31c33a8072612debe6c14788ab9f291c3
```

### Installation Source

```
Executable Path: /Users/paul/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.0
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
platform :ios, '8.0'

target 'Issue88' do
  use_frameworks!

  pod 'Siesta', '>=1.0-beta.8a'
end
```

## Project that demonstrates the issue

Podfile above should be sufficient to reproduce.

**Comment by benasher44** [comment]
I'm not sure CocoaPods code cares about this, but to follow correct semver `1.0-beta.8` should probably be `1.0.0-beta.8`(section 9):
>A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.

That said, I think I see where this is breaking in CocoaPods Core. I'll have a look soon.

**Comment by segiddins** [comment]
```diff
diff --git a/spec/version_spec.rb b/spec/version_spec.rb
index 69ee093..08c5e1d 100644
--- a/spec/version_spec.rb
+++ b/spec/version_spec.rb
@@ -99,6 +99,7 @@ module Pod
         Version.new('1.9.0-alpha').should.be < Version.new('1.9-beta')
         Version.new('2.0.0-beta').should.be < Version.new('2.0-rc')
         Version.new('2.0.0.0.0.0.1-beta').should.be > Version.new('2.0-rc')
+        Version.new('1.0-beta.8a').should.be > Version.new('1.0-beta.8')
       end
 
       it 'tie-breaks between semantically equal versions' do
```

**Comment by orta** [comment]
Interesting, so I threw all of their examples into pry and had a look around too

```ruby
require 'cocoapods'

# get example semvers, and random sort them
ordered_versions = ["1.0.0-alpha", " 1.0.0-alpha.1", " 1.0.0-alpha.beta", " 1.0.0-beta", " 1.0.0-beta.2", " 1.0.0-beta.11", " 1.0.0-rc.1", " 1.0.0"]
versions = ordered_versions.sort_by { rand }

# convert to semver objects
pod_versions = versions.map { |v| Pod::Version.new(v) }
sorted = pod_versions.sort

# Takes the sorted version, converts to string 
sorted.map { |pod_v| pod_v.version }

# ["1.0.0-alpha.beta", "1.0.0-alpha", "1.0.0-alpha.1", "1.0.0-beta", "1.0.0-beta.2", "1.0.0-beta.11", "1.0.0-rc.1", "1.0.0"]
```

**Comment by benasher44** [comment]
Yup. I put together this test case based on the semver.org section 11 example + example + one in this ticket:
```
      it 'Follows semver when comparing between pre-release versions' do
        # Example from section 11 on semver.org
        Version.new('1.0.0-alpha').should.be < Version.new('1.0.0-alpha.1')
        Version.new('1.0.0-alpha.1').should.be < Version.new('1.0.0-alpha.beta')
        Version.new('1.0.0-alpha.beta').should.be < Version.new('1.0.0-beta')
        Version.new('1.0.0-beta').should.be < Version.new('1.0.0-beta.2')
        Version.new('1.0.0-beta.2').should.be < Version.new('1.0.0-beta.11')
        Version.new('1.0.0-beta.11').should.be < Version.new('1.0.0-rc.1')
        Version.new('1.0.0-rc.1').should.be < Version.new('1.0.0')

        # Example from CocoaPods/CocoaPods#5718
        Version.new('1.0-beta.8').should.be < Version.new('1.0-beta.8a')
      end
```

It fails in a few places.

**Comment by pcantrell** [comment]
@benasher44: I checked the spec, and you’re quite right: the patch number is always required, even if it's zero. Version like `1.0` and `1.0-beta` are common enough that CocoaPods probably should support them — but it is indeed off-spec.

**Comment by benasher44** [comment]
@pcantrell agreed. I thought it worth bringing up for some reason, but it turns out to not be related to the bug in question. Apologies, my mistake!

**Comment by pcantrell** [comment]
No apologies needed — I just learned something!

**Comment by segiddins** [comment]
```diff
diff --git a/lib/cocoapods-core/version.rb b/lib/cocoapods-core/version.rb
index 9f6e96e..dd35e72 100644
--- a/lib/cocoapods-core/version.rb
+++ b/lib/cocoapods-core/version.rb
@@ -198,10 +198,13 @@ module Pod
         limit = [segments.size, other_segments.size].max
 
         (0..limit).each do |i|
-          lhs = segments[i] || 0
-          rhs = other_segments[i] || 0
+          lhs = segments[i]
+          rhs = other_segments[i]
 
           next if lhs == rhs
+          return -1 if lhs.nil?
+          return  1 if rhs.nil?
+
           return lhs <=> rhs if lhs <=> rhs
           return -1 if lhs.is_a?(String) && rhs.is_a?(Numeric)
           return  1 if lhs.is_a?(Numeric) && rhs.is_a?(String)
diff --git a/spec/version_spec.rb b/spec/version_spec.rb
index 69ee093..08c5e1d 100644
--- a/spec/version_spec.rb
+++ b/spec/version_spec.rb
@@ -99,6 +99,7 @@ module Pod
         Version.new('1.9.0-alpha').should.be < Version.new('1.9-beta')
         Version.new('2.0.0-beta').should.be < Version.new('2.0-rc')
         Version.new('2.0.0.0.0.0.1-beta').should.be > Version.new('2.0-rc')
+        Version.new('1.0-beta.8a').should.be > Version.new('1.0-beta.8')
       end
 
       it 'tie-breaks between semantically equal versions' do
```

**Comment by segiddins** [comment]
If someone makes that PR to Core with added test coverage and a CHANGELOG entry, that should do the trick

**Comment by benasher44** [comment]
@segiddins I can put it together tomorrow morning, if you'd like

**Comment by benasher44** [comment]
I'd like to add those other test cases from the semver.oeg example.
