### ISSUE TITLE
dyld error in command line project

### ISSUE THREAD

**Issue by JojoSc** [CocoaPods/CocoaPods#5719]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Create a new 'command line tool' project in Xcode. cd into the directory, run pod install, add a single pod in the Podfile (e.g. Alamofire, but this happens for all pods). Hit run.

## What did you expect to happen?

The program should start normally and print 'Hello World', which is what happens when you create a new command line tool and don't change anything.

## What happened instead?

I get this error:

```
dyld: Library not loaded: @rpath/Alamofire.framework/Versions/A/Alamofire
Referenced from: /Users/...
  Reason: image not found
Program ended with exit code: 9
```

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : JojoPodsRepo - https://github.com/JojoSc/JojoPodsRepo.git @ c89bc5e47b77482ce71b7f08a462edd841815028
               jojosc - https://github.com/JojoSc/OverTheEther.git @ bcaae20dc2d756082045601ddef8086384eeb011
               master - https://github.com/CocoaPods/Specs.git @ 00e383b432bfcbb483c7ebff9eb2e8d9e986d02e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'de' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for de
pod 'CocoaLumberjack'
end
```

## Project that demonstrates the issue

https://github.com/JojoSc/Cocoapods_dyld_error

**Comment by neonichu** [comment]
This is expected behaviour, since a commandline application has no concept of embedding frameworks. You are responsible to ensure that the frameworks are made available at runtime in this case.
