### ISSUE TITLE
[Enhancement] expose a PODS_ environment variable for the configuration basis

### ISSUE THREAD

**Issue by hborders** [CocoaPods/CocoaPods#5720]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I need to disable assertions in the `Release` configurations of my build. That's easy to do when the projects consuming my pods build with `Release`, but sometimes they create other configurations and associate them with:

```
project 'TestProject', 'Mac App Store' => :release, 'Test' => :debug
```

In this case, my pods need to enumerate all the configurations that consumers could use, or else consumers need to alter the `GCC_PREPROCESSOR_DEFINITIONS` in `post_install`.

Currently, I do this:

```
spec.pod_target_xcconfig = {
  'MY_CONFIGURATION_' => 'Release', # The default value for $(MY_CONFIGURATION)
  'MY_CONFIGURATION_Debug' => 'Debug',
  'MY_CONFIGURATION__Debug' => 'Debug',
  'MY_GCC_PREPROCESSOR_DEFINITIONS_Debug' => '',
  'MY_GCC_PREPROCESSOR_DEFINITIONS_Release' => 'NDEBUG=1',
  'MY_CONFIGURATION' => '$(MY_CONFIGURATION_$(MY_CONFIGURATION__$(CONFIGURATION)))',
  'GCC_PREPROCESSOR_DEFINITIONS' => '$(MY_GCC_PREPROCESSOR_DEFINITIONS_$(MY_CONFIGURATION))'
}
```

which sets `MY_CONFIGURATION` to `Release` unless it's exactly equal to `Debug`. It would be much nicer if there was a `PODS_BASE_CONFIGURATION` that would be `Release` or `Debug` depending on whether the target was associated with `:release` or `:debug`.

**Comment by neonichu** [comment]
Hm, why aren't you reversing the logic and rely on the existing `DEBUG` preprocessor macro?

**Comment by hborders** [comment]
I have to compile some cross-platform code that I don't control. Also, this is just an example. I have a bunch more flags I have to set in `Release` and `Debug` -ish configurations, and my consumers have 6 different Configurations, half `Release`-ish, half `Debug`-ish. Right now, I assume unknown ones are `Release`, which at least guarantees that assertions aren't compiled to production, but I'd rather know for sure what a configuration is supposed to be.

**Comment by neonichu** [comment]
But isn't that exactly what `DEBUG` already gives you? If it is `1`, you are in a debug configuration, if it is not, you are in a release configuration — what am I missing?

**Comment by hborders** [comment]
I'll double-check when I'm at my MacBook, but I'm pretty sure `DEBUG` isn't available at `xcconfig` time.

**Comment by samdmarshall** [comment]
IMO this seems like something that xcconfig files are intended to solve, by providing the environment to build in based on the configuration of the build. Depending on the code you may need to pass `DEBUG=1` in the Debug configuration and `NDEBUG` in the Release configuration.

**Comment by hborders** [comment]
>But isn't that exactly what DEBUG already gives you? If it is 1, you are in a debug configuration, if it is not, you are in a release configuration — what am I missing?

I tried using `DEBUG` at `xcconfig`-time, and it isn't present:

```
spec.pod_target_xcconfig = {
  'MY_CONFIGURATION_' => 'Release', # The default value for $(MY_CONFIGURATION)
  'MY_CONFIGURATION_1' => 'Debug',
  'MY_CONFIGURATION' => '$(MY_CONFIGURATION_$(DEBUG))',
  'MY_GCC_PREPROCESSOR_DEFINITIONS_Debug' => '',
  'MY_GCC_PREPROCESSOR_DEFINITIONS_Release' => 'NDEBUG=1',
  'GCC_PREPROCESSOR_DEFINITIONS' => '$(MY_GCC_PREPROCESSOR_DEFINITIONS_$(MY_CONFIGURATION))'
}
```

`$(MY_CONFIGURATION)` always comes back as `Release`.

**Comment by hborders** [comment]
>IMO this seems like something that xcconfig files are intended to solve, by providing the environment to build in based on the configuration of the build.

@samdmarshall, can you spell this out more simply for me? I don't understand what you mean. I'm trying to pass `DEBUG=1` (though CocoaPods does this for me, so I don't have to make it explicit) or `NDEBUG=1` depending on whether I'm in a `Debug` or `Release` -based `$(Configuration)`.

**Comment by samdmarshall** [comment]
@hborders What you are attempting to do by performing variable substitution in your previous post:
```
'MY_CONFIGURATION_1' => 'Debug',
'MY_CONFIGURATION' => '$(MY_CONFIGURATION_$(DEBUG))',
```
Is due to the fact that the variable `DEBUG` isn't a build setting/environment variable, it is the contents of `GCC_PREPROCESSOR_DEFINTIONS`. The impression I am getting from this is that you would want to structure it as such:
```
spec.pod_target_xcconfig = {
  'MY_GCC_PREPROCESSOR_DEFINITIONS_Debug' => 'DEBUG=1',
  'MY_GCC_PREPROCESSOR_DEFINITIONS_Release' => 'NDEBUG',
  'MY_GCC_PREPROCESSOR_DEFINITIONS_' => 'NDEBUG',
  'GCC_PREPROCESSOR_DEFINITIONS' => '$(MY_GCC_PREPROCESSOR_DEFINITIONS_$(CONFIGURATION))'
}
```

**Comment by hborders** [comment]
Yes, that's basically what I want. However, my consumers create Configurations like `APP_STORE` (which is based on `Release`) and `UNIT_TEST` (which is based on `Debug`), so in my configuration, I need to do this:

```
spec.pod_target_xcconfig = {
  'MY_CONFIGURATION_' => 'Release', # The default value for $(MY_CONFIGURATION)
  'MY_CONFIGURATION_Debug' => 'Debug',
  'MY_CONFIGURATION__Debug' => 'Debug',
  'MY_CONFIGURATION__UNIT_TEST' => 'Debug',
  'MY_GCC_PREPROCESSOR_DEFINITIONS_Debug' => 'DEBUG=1',
  'MY_GCC_PREPROCESSOR_DEFINITIONS_Release' => 'NDEBUG=1',
  'MY_CONFIGURATION' => '$(MY_CONFIGURATION_$(MY_CONFIGURATION__$(CONFIGURATION)))',
  'GCC_PREPROCESSOR_DEFINITIONS' => '$(MY_GCC_PREPROCESSOR_DEFINITIONS_$(MY_CONFIGURATION))'
}
```

I don't have to specify a setting for `APP_STORE` because my configuration above assumes anything it doesn't explicitly know about is `Release`. However, it would be nice if I could tell what configuration CocoaPods used to generate `$(CONFIGURATION)`, so I wouldn't need to add a new `MY_CONFIGURATION__FOO` line for every new configuration my consumers create.

**Comment by samdmarshall** [comment]
I see. Since the contents of an `.xcconfig` file is not dynamic beyond the values that the known environment variables/build settings are, there isn't much you can do here. You could try to use the conditional assignment based on configuration:
```
GCC_PREPROCESSOR_DEFINITIONS = NDEBUG
GCC_PREPROCESSOR_DEFINITIONS[config="Debug"] = DEBUG=1
```
This may yield the results you are looking for, if not then I think the only solution here is to have users do a post-install hook or something to query and create these values in the xcconfig file (or another one, that is generated) based on access to the project file so they can dictate which are "Debug" vs "Release" configurations.

**Comment by hborders** [comment]
I see, so CocoaPods would have to create a `PODS_BASE_CONFIGURATION` `xcconfig` variable and insert it into the existing `spec.pod_target_xcconfig` hash.

**Comment by samdmarshall** [comment]
That would be my assumption, but I don't know much about this particular system in CocoaPods so I don't know if what I suggested is feasible or not.

**Comment by Ashton-W** [comment]
I'm facing similar difficulty when trying to provide a `GCC_PREPROCESSOR_DEFINITIONS` to enable conditional compilation of some insecure / non-AppStore code. Using `DEBUG` is too generic, Enterprise/Internal app builds may want to have this conditional code included.

I did try and enable this with a subspec that sets the xcconfig, but found out that subspecs across different build configurations isn't supported.

    [!] The subspecs of `SecurityStuff` are linked to different build configurations for the `Pods-App` target. CocoaPods does not currently support subspecs across different build configurations.

I can solve this with a `post_install` hook in the `Podfile`, but it is a little messy:

```ruby
target 'App' do
  pod 'SecurityStuff'
end

post_install do |installer|
  installer.pods_project.targets { |t| t.name == 'SecurityStuff' }.map do |target|
      release = target.build_configurations.find { |c| c.name == 'Release' }
      release.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'MAGIC=1']
  end
end
```

My ideal API for this would be options that could be attached to the `pod` statement in the `Podfile`

```ruby
pod 'SecurityStuff', :xcconfig => { 'GCC_PREPROCESSOR_DEFINITIONS' => 'MAGIC=1' }
```

Thoughts?
