### ISSUE TITLE
`--allow-errors` for the private podspecs with unsolvable errors?

### ISSUE THREAD

**Issue by ReDetection** [CocoaPods/CocoaPods#5721]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 

# 🌈 Report 

## What did you do?

`pod repo push my-specs`

## What did you expect to happen?

Spec pushed to my private podspecs repo

## What happened instead?

```
 -> ScanditBarcodeScanner (4.14.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  ld: warning: object file (ScanditBarcodeScanner/ScanditSDK/ScanditBarcodeScanner.framework/ScanditBarcodeScanner(scandit-barcodescanner.o)) was built for newer iOS version (10.11) than being linked (8.0)
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Note the `was built for newer iOS version (10.11) than being linked (8.0)` on the right.
Nothing actually changes if I pass `--use-libraries`. Can't google anything about this crazy mix of OS X and iOS versions.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F1909)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 095bfa20f0e129b2d2c8d7a16742e43b00f9810a
               master - https://github.com/CocoaPods/Specs.git @ 2bda0a0ed05b49bc6d3248c8c34a0ebb07e0c0d5
               my-specs - # redacted
```

### Installation Source

```
Executable Path: /usr/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

Well, this is a bit complicated. I was writing private podspec for the @scandit iOS SDK, because they don't have a public repo podspec. You can [download their SDK](http://www.scandit.com/products/barcode-scanner/) and add this podspec: 
```ruby
Pod::Spec.new do |s|
  s.name             = 'ScanditBarcodeScanner'
  s.version          = '4.14.0'
  s.summary          = 'Enterprise-Grade Barcode Scanner for Mobile Apps'
  s.homepage         = 'http://www.scandit.com/products/barcode-scanner/'
  s.license          = { :type => 'Apache 2.0', :file => 'ScanditSDK/LICENSE-2.0.txt' }
  s.author           = 'Scandit team'
  s.source           = { :git => '' , :tag => s.version.to_s } #git url redacted

  s.platform = :ios, '6.0'

  s.ios.vendored_frameworks = 'ScanditSDK/ScanditBarcodeScanner.framework'
end
```

**Comment by ReDetection** [comment]
Of course, `pod lib lint --private` shows the same results. I did used `--no-clean`, but had no luck to fix the problem because it's the vendored binary, I can't just rebuild it. 

Any suggestions? At the moment I workarounded issue by specifying particular `:git` parameter in the `Podfile`, but it would be more convenient to have it pushed to the specs repo.

**Comment by neonichu** [comment]
I would suggest just doing a manual git push in a situation like this.

**Comment by ReDetection** [comment]
@neonichu ok. seems like it does not break anything. thanks
