### ISSUE TITLE
Pods are not found when compiling for device running iOS 10

### ISSUE THREAD

**Issue by pronebird** [CocoaPods/CocoaPods#5723]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I installed latest beta on my device and I have Xcode 8 beta 4. I switched to device target from dropdown in Xcode and hit run.

## What did you expect to happen?

Expected for app to be compiled for device running iOS 10 beta.

## What happened instead?

I receive errors that headers are not found for number of pods such PureLayout and MagicalRecord and some others. I don't experience this when running on simulator.

## CocoaPods Environment

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

def commonPods()
  pod 'PureLayout', '~> 3.0.1'
  pod 'MD5Digest', '~> 1.1.0'
  pod 'MagicalRecord'
end

def pods()

    pod 'Fabric'
    pod 'Crashlytics'
    
    commonPods

end

target 'App' do
  pods
end

target 'Widget' do
  commonPods

  post_install do |installer|
    # NOTE: If you are using a CocoaPods version prior to 0.38, replace `pods_project` with `project` on the below line
    installer.pods_project.targets.each do |target|
      if target.name.end_with? "PureLayout"
        target.build_configurations.each do |build_configuration|
          if build_configuration.build_settings['APPLICATION_EXTENSION_API_ONLY'] == 'YES'
            build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'PURELAYOUT_APP_EXTENSIONS=1']
          end
        end
      end
    end
  end
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by pronebird** [comment]
Oh my... clean rebuild worked...

**Comment by umarchohan** [comment]
Same error with me.
Even tried clean and rebuild

**Comment by benasher44** [comment]
@umarchohan can you file a new issue with repro steps please? Thanks!!

**Comment by umarchohan** [comment]
@benasher44  this is my podfile 

# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'Inspection App' do

pod 'Realm'

  target 'Inspection AppTests' do
    inherit! :search_paths
    
pod 'Realm/Headers'

  end

end

**Comment by benasher44** [comment]
@umarchohan the issue template in a new issue helps us gather useful information to help with debugging. Could you please file a new issue with repro steps?

**Comment by umarchohan** [comment]
@benasher44 sure I shall report a new issue
