### ISSUE TITLE
Trying to update just 1 pod fails

### ISSUE THREAD

**Issue by JamaicanRumCream** [CocoaPods/CocoaPods#5725]
* [ X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
use command  "pod update 'podname'"

## What did you expect to happen?
In previous Cocoapods, i.e. 0.38, this updated just that one pod without updating any other pods

## What happened instead?
[!] Invalid `Podfile` file: undefined method `abstract_target' for #<Pod::Podfile:0x007f823aca4360>. Updating CocoaPods might fix the issue.

 #  from /Users/paveglioc/Dev/iOS/AccuWeather/Podfile:7
 #  -------------------------------------------
 #  
 >  abstract_target 'Flagship' do
 #  
 #  -------------------------------------------

## CocoaPods Environment
[!] Unknown command: `env`
Did you mean: ipc

so this is with Cocoapods App installed , version 1.0.0 (1.0.0)

## Project that demonstrates the issue
seems to be a tool problem and any project would have this issue.

**Comment by orta** [comment]
You'll need to port this Podfile to 1.0 syntax - http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/

**Comment by JamaicanRumCream** [comment]
Oh my version "in terminal" say 0.39.0. I thought installing the CocoaPods app would update all instances to the 1.0.0 version systemwide.

**Comment by orta** [comment]
Nope, you can optionally install the command-line tools, but the Mac app hosts it's own version of CocoaPods' `pod` - so by default it doesn't change your terminal environment. So your terminal is still at 0.39.

**Comment by segiddins** [comment]
You can either `gem install cocoapods` to get 1.0, or use the app to install the command line tool, or use the app to run `pod install`.
