### ISSUE TITLE
The signature of CLAide#arguments has changed

### ISSUE THREAD

**Issue by izhoubin** [CocoaPods/CocoaPods#5727]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by izhoubin** [comment]
/usr/local/bin/pod update --no-repo-update

[33m[!] The signature of CLAide#arguments has changed. Use CLAide::Argument (Pod::Command::CheckLatest: `[["NAME", :required]]`)[39m
Update all pods
Analyzing dependencies

**Comment by neonichu** [comment]
Looks like you're using this plugin <https://github.com/yujinakayama/cocoapods-check_latest/blob/master/lib/pod/command/check_latest.rb#L5> which hasn't been updated in a while. Please report the issue upstream. Also note that this is only a warning.

**Comment by sirghi** [comment]
@neonichu What if I'm not using any plugin, I get this from just `pod --version` even?
