### ISSUE TITLE
pod spec lint fail - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code

### ISSUE THREAD

**Issue by crash-wu** [CocoaPods/CocoaPods#5728]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod spec lint xx.podspec --verbose

## What did you expect to happen?

** BUILD FAILED **

## What happened instead?

    The following build commands failed:
	  Ld  /var/folders/6t/55twqhbj2_qgnkl5qgg_lr8m0000gn/T/CocoaPods/Lint/build/Pods.build/Release-iphonesimulator/SGSketchLayer.build/Objects-normal/x86_64/SGSketchLayer normal x86_64(1 failure)
         -> SGSketchLayer (0.0.1)
            - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
            - NOTE  | xcodebuild:  ld: warning: Auto-Linking supplied  '/XX/Library/SDKs/ArcGIS/iOS/ArcGIS.framework/ArcGIS', framework linker option at /XX/Library/SDKs/ArcGIS/iOS/ArcGIS.framework/ArcGIS is not a dylib
            - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

## CocoaPods Environment

CocoaPods : 0.39

## Project that demonstrates the issue

   https://github.com/crash-wu/SGSketchTool

## Podspec

Pod::Spec.new do |s|

       # ―――  Spec Metadata  ――――――――――
       s.name         = "SGSketchLayer"
       s.version      = "0.0.1"
       s.summary      = "SGSketchLayer."

       s.description  = "A layer that allows the user to interactively sketch geometries on the map .You can sketch point(点) ,FoldLine(折线),Curve(曲线),Surfaces(曲面),Polygon(多边形) geometries from scratch."

       s.homepage     = "https://github.com/crash-wu/SGSketchTool"
       s.license      = "MIT"
       # s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
       # ――― Author Metadata  ―――――――― #
        s.author             = { "吴小星" => "crash_wu@163.com" }
       # ――― Platform Specifics ―――――― #
       s.platform     = :ios
       s.platform     = :ios, "8.0"
       s.ios.deployment_target = "8.0"
       s.source       = { :git => "https://github.com/crash-wu/SGSketchTool.git", :tag => "0.0.1" }
       s.source_files  = "SGSketchTool/SketchTool/*.swift"
       #s.framework  = "ArcGIS"
       s.requires_arc = true
       other_ldflags = '-ObjC' + '-framework' + 'ArcGIS' + '-lz'  + '-lstdc++'
       #other_ldflags = '-lObjC'+ '-framework' +'ArcGIS'  + '-lstdc++'
       s.xcconfig = {

        "FRAMEWORK_SEARCH_PATHS" => "$(HOME)/Library/SDKs/ArcGIS/iOS" ,

        "OTHER_LDFLAGS[arch=arm64]"  => other_ldflags,
        "OTHER_LDFLAGS[arch=armv7]"  => other_ldflags,
        "OTHER_LDFLAGS[arch=armv7s]" => other_ldflags,

        #"OTHER_LDFLAGS"  => other_ldflags,

        'ENABLE_BITCODE' => 'NO',
        'ENABLE_MODULES' => 'YES'

       }
      #s.dependency "ArcGIS-Runtime-SDK-iOS", "~>10.2.5"
      end

Thanks

**Comment by neonichu** [comment]
This is not really a CocoaPods issue, there's a concrete `xcodebuild` error message:

```
xcodebuild:  ld: warning: Auto-Linking supplied  '/XX/Library/SDKs/ArcGIS/iOS/ArcGIS.framework/ArcGIS', framework linker option at /XX/Library/SDKs/ArcGIS/iOS/ArcGIS.framework/ArcGIS is not a dylib
```

You'll have to resolve that to make linting pass.

**Comment by janbaz87** [comment]
Just remove .swift from  s.source_files it will work
