### ISSUE TITLE
"Framework not found" with 1.0.1 version.

### ISSUE THREAD

**Issue by akshaynhegde** [CocoaPods/CocoaPods#5729]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Updated to the latest Cocoapods version and ran `pod Install`

This is the output of it : 

> Re-creating CocoaPods due to major version update.
> Analysing dependencies
> Downloading dependencies
> Installing Alamofire (3.4.0)
> Installing AppsFlyerFramework (4.5.2)
> Installing Bolts (1.7.0)
> Installing CocoaLumberjack (2.3.0)
> Installing Crashlytics (3.7.0)
> Installing CryptoSwift (0.4.1)
> Installing FBSDKCoreKit (4.12.0)
> Installing FBSDKLoginKit (4.12.0)
> Installing Fabric (1.6.7)
> Installing FirebaseAnalytics (3.2.0)
> Installing FirebaseInstanceID (1.0.6)
> Installing Google (3.0.3)
> Installing GoogleAppUtilities (1.1.1)
> Installing GoogleAuthUtilities (2.0.1)
> Installing GoogleInterchangeUtilities (1.2.1)
> Installing GoogleNetworkingUtilities (1.2.1)
> Installing GoogleSignIn (4.0.0)
> Installing GoogleSymbolUtilities (1.1.1)
> Installing GoogleUtilities (1.3.1)
> Installing MagicalRecord (2.3.2)
> Installing Mixpanel (2.9.9)
> Installing ObjectMapper (1.3.0)
> Installing R.swift (2.3.0)
> Installing R.swift.Library (2.1.0)
> Installing RxCocoa (2.5.0)
> Installing RxSwift (2.5.0)
> Installing SAMKeychain (1.5.0)
> Installing SVProgressHUD (2.0.3)
> Generating Pods project
> Integrating client project
> 
> [!] Please close any current Xcode sessions and use `SignEasy.xcworkspace` for this project from now on.
> Sending stats
> Pod installation complete! There are 16 dependencies from the Podfile and 28
> total pods installed.
> 
> [!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
> 
> [!] The `SignEasy [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-SignEasy/Pods-SignEasy.debug.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.
> 
> [!] The `SignEasy [Release]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-SignEasy/Pods-SignEasy.release.xcconfig'. This can lead to problems with the CocoaPods installation
>     - Use the `$(inherited)` flag, or
>     - Remove the build settings from the target.

## What did you expect to happen?

Install all pod dependencies correctly and I should be able to build the main app target.

## What happened instead?

Get the Following error : 

> ld: framework not found Alamofire for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : iOS-App-V2-PodSpecs - https://github.com/signeasy/iOS-App-V2-PodSpecs.git @ ed20421e816a2b07f161b3761f97e5e683759b3a
               master - https://github.com/CocoaPods/Specs.git @ 7a59909d3791f04ed62f5281bd67f0264afc6ad7
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-keys        : 1.6.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
 use_frameworks!

#######################  Pods clubbed in with definitions so that it can shared ##############################

# Shared Pods - That are shared between multiple targets
def shared_pods
    
    pod 'RxSwift'
    pod 'SAMKeychain'

end

# Pods for logging
def logging_pods
    
    pod 'CocoaLumberjack/Swift'

end

# Pods for Analytics and Crash Reporting
def analytics_and_reporting_pods
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Mixpanel'
    pod 'AppsFlyerFramework’
    
end

# Pods for Networking
def networking_pods
    
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'CryptoSwift'
    shared_pods
    
end

# Pods used for Core Data
def coredata_pods
    
    pod 'MagicalRecord'

end

########################## Podas for SignEasy App Target and Test targets #########################################

target 'SignEasy' do

    pod 'RxCocoa'
    pod 'R.swift'
    pod 'SVProgressHUD'
    pod 'Google/SignIn'
    pod 'FBSDKLoginKit'

    shared_pods
    
    analytics_and_reporting_pods
    
    logging_pods
    
    coredata_pods

end

target 'SignEasyTests' do
    
    shared_pods

end

target 'SignEasyUITests' do

end

######################## Pods Used for SignEasyNetworking Target and Test targets ###################################

target 'SignEasyNetworking' do
    
    networking_pods
    logging_pods
    
end


target 'SignEasyNetworkingTests' do
    
    networking_pods
    
end


###################### Pods Used for SignEasyAnalytics Target and Test Targets #####################################

target 'SignEasyAnalytics' do
    
    pod 'RxSwift'
    analytics_and_reporting_pods
    logging_pods
    
end


target 'SignEasyAnalyticsTests' do
    

end

**Comment by neonichu** [comment]
I'm guessing "SignEasyNetworking" is a framework used by the "SignEasy" application target? If that's the case, this is expected, because there is no support in CocoaPods 1.0 for framework targets.

However, that changed in 1.1.0, you might want to test out the beta.

**Comment by akshaynhegde** [comment]
@neonichu the app now builds without any issues using the beta. Thank you!

**Comment by neonichu** [comment]
Thanks for verifying!
