### ISSUE TITLE
Nested pods ( Cocoapods )

### ISSUE THREAD

**Issue by araujotadeu** [CocoaPods/CocoaPods#5730]
I'm trying to do something that I don't know if is right or possible, but is not working.

The scenery is, I have two Swift projects with some nested/hierarchical/shared pods, but some of the pods are ObjectiveC and others Swift. I'm attaching an image to make easy to understand.

The problem is, the final projects ( ProjectA and ProjectB ) are not seeing the SharedLibrary ( ObjectiveC ) content. Someone already have some similar problem?

![Projects/Pods Structure](https://cloud.githubusercontent.com/assets/9177950/17520501/5578a9d0-5e26-11e6-9385-51c09189428f.png)

- We add this SwiftSharedLibrary, as a way to migrate the legacy ObjectiveC slowly.
- The structure are fully controlled by the cocoapods, and the private projects have configured podspec files with the dependencies.
- Cocoapods 0.39.0 (with the 1.0.0 version have the same problem)
- Using use_frameworks! is all podfiles

**Comment by neonichu** [comment]
You'll need a direct dependency from your projects to the ObjC shared library if you directly want to access any of its functionality, a transitive dependency is not sufficient when using dynamic linking.
