### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by wangfaguo** [CocoaPods/CocoaPods#5738]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod lib lint --allow-warnings --verbose

## What did you expect to happen?

success 

## What happened instead?

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UMSocialData", referenced from:
      objc-class-ref in QLUmengShare.o
  "_OBJC_CLASS_$_UMSocialDataService", referenced from:
      objc-class-ref in QLUmengShare.o
  "_UMShareToQQ", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToQzone", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToSina", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToSms", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToWechatSession", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToWechatTimeline", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Intermediates/Pods.build/Release-iphonesimulator/QLUmengShare.build/Objects-normal/i386/QLUmengShare normal i386
    cd /var/folders/yh/kx1qq0055ws70svkb9dl3fkm0000gn/T/CocoaPods/Lint/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode 6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode 6.app/Contents/Developer/usr/bin:/Applications/Xcode 6.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/wangfaguo/.composer/vendor/bin"
    /Applications/Xcode\ 6.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -dynamiclib -isysroot /Applications/Xcode\ 6.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk -L/Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Products/Release-iphonesimulator/QLUmengShare -F/Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Products/Release-iphonesimulator/QLUmengShare -F/Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Products/Release-iphonesimulator/SDWebImage -filelist /Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Intermediates/Pods.build/Release-iphonesimulator/QLUmengShare.build/Objects-normal/i386/QLUmengShare.LinkFileList -install_name @rpath/QLUmengShare.framework/QLUmengShare -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -objc_abi_version -Xlinker 2 -framework UIKit -fobjc-arc -fobjc-link-runtime -framework Foundation -framework SDWebImage -framework UIKit -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Intermediates/Pods.build/Release-iphonesimulator/QLUmengShare.build/Objects-normal/i386/QLUmengShare_dependency_info.dat -o /Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Intermediates/Pods.build/Release-iphonesimulator/QLUmengShare.build/Objects-normal/i386/QLUmengShare
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_UMSocialData", referenced from:
      objc-class-ref in QLUmengShare.o
  "_OBJC_CLASS_$_UMSocialDataService", referenced from:
      objc-class-ref in QLUmengShare.o
  "_UMShareToQQ", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToQzone", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToSina", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToSms", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToWechatSession", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
  "_UMShareToWechatTimeline", referenced from:
      -[QLUmengShare ShareMenu:didTapOnItem:atIndex:] in QLUmengShare.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld /Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Intermediates/Pods.build/Release-iphonesimulator/QLUmengShare.build/Objects-normal/x86_64/QLUmengShare normal x86_64
	Ld /Users/wangfaguo/Library/Developer/Xcode/DerivedData/App-gyfefocsoywhdggyzzuwagioujlz/Build/Intermediates/Pods.build/Release-iphonesimulator/QLUmengShare.build/Objects-normal/i386/QLUmengShare normal i386
## CocoaPods Environment

Pod::Spec.new do |s|
  s.name             = 'QLUmengShare'
  s.version          = '0.2.0'
  s.summary          = ' QLUmengShare is a  share tool.'

  s.homepage         = 'http://******/QLUmengShare'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'wangfaguo' => '452290424@qq.com' }
  s.source           = { :git => 'http://*******/QLUmengShare.git', :tag => s.version.to_s }

  s.ios.deployment_target = '7.0'

  s.source_files = 'QLUmengShare/Classes/**/*'
  
   s.resource_bundles = {
     'QLUmengShare' => ['QLUmengShare/Assets/*.png']
   }

   s.public_header_files = 'QLUmengShare/Classes/**/*.h'
   s.frameworks = 'UIKit'
   s.dependency 'UMengSocialCOM', '~> 5.2.1'
   s.dependency 'SDWebImage', '~> 3.7.0'
end

**Comment by neonichu** [comment]
Looking at the naming of the "UMengSocialCOM" source (see <https://github.com/CocoaPods/Specs/blob/master/Specs/UMengSocialCOM/5.1.0/UMengSocialCOM.podspec.json#L16>), I am assuming it ships only with `arm64` slices, but none for the simulator, therefore linting will not be possible.
