### ISSUE TITLE
Deprecate aneen deprecated  old pod thats alread

### ISSUE THREAD

**Issue by kylebrowning** [CocoaPods/CocoaPods#5741]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I have an old pod that was deprecated in favor of a new name, and that name has changed again.

When attempting to deprecate to setup a new redirect I get the following error

`There were no published versions to deprecate.`

## What did you do?

`pod trunk deprecate drupal-ios-sdk --in-favor-of=waterwheel`

## What did you expect to happen?
Redeprication of old pod to new pod.

## What happened instead?

`There were no published versions to deprecate.`

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A286a)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 848ffd86a708faf10beac3b35ff1aefc5f0fb0fd
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by segiddins** [comment]
This seems to be the intended behavior, at least from reading the code: https://github.com/CocoaPods/trunk.cocoapods.org/blob/master/app/models/pod_version.rb#L91. If you'd like us to revisit that, please open an issue on the trunk web app repo. Thanks!

**Comment by kylebrowning** [comment]
Done.

https://github.com/CocoaPods/trunk.cocoapods.org/issues/185
