### ISSUE TITLE
Pod setup error

### ISSUE THREAD

**Issue by iTofu** [CocoaPods/CocoaPods#5744]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
e.g. Run `pod install`

`pod setup`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

````
LeodeMacBook-Pro:~ Leo$ pod setup
Setting up CocoaPods master repo
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master

Cloning into 'master'...
error: RPC failed; curl 56 SSLRead() return error -36
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

LeodeMacBook-Pro:~ Leo$ 
````

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`

````
LeodeMacBook-Pro:~ Leo$ pod env

### Stack

\```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/Leo/.rvm/rubies/ruby-2.3.0/lib
Repositories : 
\```

### Installation Source

\```
Executable Path: /usr/local/bin/pod
\```

### Plugins

\```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
\```

LeodeMacBook-Pro:~ Leo$ 
````

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by iTofu** [comment]
I had solved this problem.
#4293 @segiddins 's answer.

**Comment by josyzhao** [comment]
I have the same issue now, Could you tell me how you solved this?

**Comment by iTofu** [comment]
@josyzhao 
Go to ~/.cocoapods/repos and run git clone https://github.com/CocoaPods/Specs.git master

**Comment by josyzhao** [comment]
Thank you very much! It works!
