### ISSUE TITLE
Massive install size

### ISSUE THREAD

**Issue by poisa** [CocoaPods/CocoaPods#5745]
I've just installed CocoaPods for the first time and to my surprise I found that my `~/.cocoapods/ `dir had 780Mb in it. This seems excessive for a package manager (I have no other package manager close to this size). As examples, npm is 23Mb, and composer 1.6Mb.
Looking into the cocoapods dir I see that `Specs` takes up (411Mb) and then `.git` takes up `368Mb`. Is the .git dir necessary for this to work? Is there some way to reduce the size of the install? 

By the way, I'm not criticising, I'm just trying to save some precious SSD space.

**Comment by Brett-Best** [comment]
@poisa I think this is related to #4989, in the past I think that a shallow clone was taken. Also see #5297.

**Comment by neonichu** [comment]
There isn't really a way for you to reduce the size of this, unless you want to strictly stick to your own private spec repos. We had to switch that to a full clone due to issues @Brett-Best referenced.
