### ISSUE TITLE
Header files not found after creating library project

### ISSUE THREAD

**Issue by benmarten** [CocoaPods/CocoaPods#5746]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
~/d/pod_test $ pod lib create lib2                                                                                   09:21:29
Cloning `https://github.com/CocoaPods/pod-template.git` into `lib2`.
Configuring lib2 template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and double click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > ObjC

Would you like to include a demo application with your library? [ Yes / No ]
 > 
yes
Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > No

What is your class prefix?
 > LP

Running pod install on your new library.

Analyzing dependencies
Fetching podspec for `lib2` from `../`
Downloading dependencies
Installing lib2 (0.1.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `lib2.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'lib2/Example/lib2.xcworkspace'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
```

Now in the opened workspace, when i add an import to LPAppDelegate.m:
`#import "ReplaceMe.m"`
It shows `ReplaceMe.m file not found` error message

I am trying this on this basic level because I am running into this issue with a complex library project too, but as I can see here already with a fresh lib project, it happens right away.

## What did you expect to happen?

The imports are correctly resolved.

## What happened instead?

It shows the error message, that the file cannot be found.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : leanplum - https://github.com/Leanplum/CocoaPods.git @ 271ec364b8395382771c9ca37ecd081f5435f5db
               master - https://github.com/CocoaPods/Specs.git @ 9518712202c7043504b74fc21521491aaa1048aa
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/benmarten/pod-lib-test

Any help appreciated!

**Comment by segiddins** [comment]
does `#import <lib2/ReplaceMe.h>` work?

**Comment by benmarten** [comment]
No it doesn't work either, I've updated the sample project.

Also I've added real CocoaTouchClass (all default settings), and pushed it to here: https://github.com/benmarten/pod-lib-test/tree/test/real

When I uncomment   `use_frameworks!` in the Podfile it works!

**Comment by segiddins** [comment]
If deleting derived data fixes it, then yeah, seems like an Xcode issue

**Comment by benmarten** [comment]
Ok, but is there anything that can be done by cocoapods to avoid that? I've been running into this issue lately a lot, because we have migrated a lot of our projects to dynamic cocoapod libraries.
The above mentioned approach seems kinda flaky too... Maybe you can see something from the diff commit?

**Comment by segiddins** [comment]
Apparently Xcode 8 makes deleting derived data necessary less frequently, but I'm afraid it's something we've just gotten used to doing. It turns out, caching is hard!
