### ISSUE TITLE
Can't use AMapLocation pod in Swift?

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#5751]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1) Create a new Swift project.
2) Add a Podfile with AMapLocation
3) App `import AMapLocation` in a swift file

## What did you expect to happen?

It builds without error.

## What happened instead?

> No such module 'AMapLocation'

And I don't see any [modulemap](https://guides.cocoapods.org/syntax/podspec.html#module_map) file created by CocoaPods, when it should be by default.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0d40c4864f501eb51f6703884330cb2780ac6ac2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

abstract_target 'default_pods' do
    pod 'AMapLocation', '~> 2.1'
    target 'myApp'
end
```

**Comment by neonichu** [comment]
Looks like "AMapLocation" is a vendored framework. They need to provide a module map themselves in that case. If they don't, using a bridging header will be necessary.

**Comment by Coeur** [comment]
Thank you @neonichu. I would suggest CocoaPods reject vendored frameworks based podspecs in the future if they don't include a module map.
