### ISSUE TITLE
using spec.header_mappings_dir results in project level visibility for all headers 

### ISSUE THREAD

**Issue by mutex1980** [CocoaPods/CocoaPods#5752]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I set up a local pod for the J2ObjC Headers:

```
Pod::Spec.new do |spec|
  spec.name         = 'J2ObjCRuntimeHeaders'
  spec.version      = '1.0'
  spec.license      = 'Unknown'
  spec.homepage     = 'None'
  spec.authors      = { 'Unknown' => 'a@b.com' }
  spec.summary      = 'None'
  spec.source       = { :path => '<AbsPath>/modules/J2ObjCRuntime' }
  spec.platform     = :ios, '9.3' 
  spec.source_files = 'src/**/*.h', 'src/dummy.m'
  spec.header_mappings_dir = 'src' # this prevents header flattening, and makes all headers visibility "project" :-(
end
```

And installed it with use_frameworks! to my project.
## What did you expect to happen?

Since I do not use the public_header_files filter, I expect all headers to have visibility "public" in the resulting XCode target. (The documentation says: "If no public headers are specified then all the headers in source_files are considered public.")
## What happened instead?

All headers have "project" level visibility in the resulting Xcode target. Only the framework umbrella header has public visibility. If I remove the line

```
spec.header_mappings_dir = 'src'
```

all headers are flattened (which I cannot use). But in the flattened mode all headers get "public" visibility together with the generated umbrella header.

So I guess giving public visibility in conjunction with setting spec.header_mappings_dir is somehow broken?
### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2811e9761e9c339ce61cc0846b6659015f21366e
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by segiddins** [comment]
Do you have a project we could use to reproduce the bug? Thanks!
