### ISSUE TITLE
Support for Framework Target with Multiple Host Targets?

### ISSUE THREAD

**Issue by Ben-G** [CocoaPods/CocoaPods#5753]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Attempted to define an embedded target that is shared between two host targets.

## What did you expect to happen?

I expected to find a valid way to define an embedded target that is shared between host targets.

## What happened instead?

To my best effort I could not find a valid way to define  an embedded target that is shared between host targets when using CocoaPods `1.1.0.beta.1`.

The approach that worked in older versions of CocoaPods (not defining any host target) now produces an error message: `Unable to find host target for Pods-PGSharedTestUtils. Please add the host targets for the embedded targets to the Podfile` (though this seems to be converted into a warning in #5733).

In the example project below the goal is to embed the **PGSharedTestUtils** target in both **PlanGridUnitTests** and **PlanLibTests**.

In my understanding the only way to define a host target is by embedding the definition of the embedded target in the host target, e.g.:

```
target 'MyApp' do
  pod 'GoogleAnalytics', '~> 3.1'

  target 'MyAppTests' do
    ...
  end
end
```

If trying to use this approach for an embedded target that is shared between multiple targets I would duplicate the target definition, which would result in an invalid `Podfile` as well.

Sorry if I'm missing something obvious here!

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/bencz/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d1d518db2685f7ce4c856886505b4caf9c742fb7
               plangrid - git@github.com:plangrid/plangrid-cocoapods.git @ 098688acdacff7a23a67c9eeb8bfce706e0ac1a5
```

### Installation Source

```
Executable Path: /Users/bencz/.rvm/gems/ruby-2.2.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

*Note: I have trimmed the podfile slightly to reduce some noise.*

```ruby
#as of 0.34.x, cocoapods wants an explicit spec source
source 'https://github.com/CocoaPods/Specs.git'

# for PSPDFKit or other private pod updates; make sure you upload the podspec here when a new version is released!
# see the readme on the plangrid-cocoapods repo for details
source 'git@github.com:plangrid/plangrid-cocoapods.git'

workspace 'PlanGrid.xcworkspace'
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
	pod 'Bugsnag', '5.1.0'
	pod 'PDKeychainBindingsController', '0.0.1'
	pod 'CocoaLumberjack/Swift', '2.3.0'
	pod 'Result', '2.0.0'
	pod 'ReactiveCocoa', '4.1.0'
	pod 'FMDB/standalone', '2.6.2'
	pod 'FMDBMigrationManager/Standalone', '1.4.1'
	pod 'PEGKit', '0.4.2'
end

def legacy_pods
	pod 'AFNetworking', '2.5.4'
	pod 'AFNetworking/NSURLSession', '2.5.4'
end

def testing_pods
	pod 'Quick', '~> 0.9.2'
	pod 'Nimble', '~> 4.0.0'
end

def app_shared_pods
	pod 'PSPDFKit', '5.4.1'
end

project 'PlanGrid/PlanGrid.xcodeproj'
project 'PlanLib/PlanLib.xcodeproj'
project 'PGSharedTestUtils/PGSharedTestUtils.xcodeproj'

target 'PlanLib' do
	project 'PlanLib/PlanLib.xcodeproj'
	shared_pods
end

target 'PlanGrid' do
	project 'PlanGrid/PlanGrid.xcodeproj'
	shared_pods
	app_shared_pods
	legacy_pods
	pod 'Amplitude-iOS', '3.7.1'
	pod 'AppsFlyerFramework', '4.4.0'
	pod 'FBSDKCoreKit', '4.10.1'
	pod 'Optimizely-iOS-SDK', '1.4.2'
	pod 'SlackTextViewController', '1.9.1'
	pod 'TTTAttributedLabel', '1.13.4'
	pod 'Cartography', '0.6.0'
	pod 'BSImagePicker', :git => 'https://github.com/plangrid/BSImagePicker.git', :commit => '7eb246c4e7fcc73a05a415447a5a5125c3c15791'
	pod 'UIImageViewModeScaleAspect', '1.3'
	pod 'BSGridCollectionViewLayout', :git => 'https://github.com/plangrid/BSGridCollectionViewLayout.git', :commit => '99b5b4532071e074c0a5db5a5e3eddb889b8c7f5'
	pod 'OpenCV', '3.0.0'
end

target 'PlanLibTests' do
	project 'PlanLib/PlanLib.xcodeproj'
	shared_pods
	testing_pods
end

target 'PlanGridUnitTests' do
	project 'PlanGrid/PlanGrid.xcodeproj'
	shared_pods
	app_shared_pods
	legacy_pods
	testing_pods
end

target 'PGSharedTestUtils' do
	project 'PGSharedTestUtils/PGSharedTestUtils.xcodeproj'
	shared_pods
	testing_pods
end
```

**Comment by segiddins** [comment]
Is the framework actually listed under the embedded frameworks for the PBXNativeTarget in Xcode?

**Comment by Ben-G** [comment]
Sorry my use of "embedded framework" was incorrect. The framework is not listed in the `PBXNativeTarget` section.  It's just a regular framework that is linked in `PBXFrameworksBuildPhase`.

**Comment by segiddins** [comment]
Actually, I think this should be fixed by https://github.com/CocoaPods/CocoaPods/pull/5733 ?

**Comment by Ben-G** [comment]
I was wondering if this case is captured by #5733. 

Looking through the commit history it seems like this error was added with embedded targets in mind, because these require pods being copied to the host target (https://github.com/CocoaPods/CocoaPods/commit/f2118095ebf5b7a555f4509d96c73a50a239116f#diff-f5c3fee776e864ada6541431a1532b00). That isn't necessary for this framework that is linked against a test target.

So after #5733 shipped I should be able to ignore the warning.

Thanks for helping me clarify this (wasn't sure if I'm missing some obvious feature for defining multiple host targets for a framework).
