### ISSUE TITLE
Development Pods do not See Headers of Each Other

### ISSUE THREAD

**Issue by benmarten** [CocoaPods/CocoaPods#5754]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have scaffolded two new CocoaPod library projects via: `pod lib create lib1`
I use, ObjC, Demo applciation, No testing or view testing fw, class prefix LP.

They use the default settings, `use_frameworks!` and `inherit! :search_paths`, they are called lib1 and lib2. I am including lib2 as a dependency in the lib1 project.

I can successfully import and use both libraries classes in the example and tests target, e.g.:
#import "lib1/LPlib1.h"
#import "lib2/LPlib2.h"

But when I include `lib2/LPlib2.h within `lib1/LPlib1.h/m` the import does not resolve. I am getting a `file not found` error.
<img width="537" alt="screen shot 2016-08-15 at 1 51 26 pm" src="https://cloud.githubusercontent.com/assets/5960238/17680072/49b280e0-62f3-11e6-808a-79ee6c78c377.png">

## What did you expect to happen?

Lib2 can be used/imported in Lib1.

## What happened instead?

`LPLib2.h file not found` error in LPlib1.h.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : CocoaPods-Test-Repository - https://github.com/benmarten/CocoaPods-Test-Repository.git @ b87ff1dcde766ac9b2db6cafbc2b559146df84b4
               leanplum - https://github.com/Leanplum/CocoaPods.git @ 271ec364b8395382771c9ca37ecd081f5435f5db
               Leanplum-CocoaPods-Private - https://github.com/leanplum/CocoaPods-Private.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               master - https://github.com/CocoaPods/Specs.git @ 5a98665b91ca53c2c5038898024e9d2e0f475bed
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'lib1_Example' do
  pod 'lib1', :path => '../'
  pod 'lib2', :path => '../../lib2/'

  target 'lib1_Tests' do
    inherit! :search_paths


  end
end
```

## Project that demonstrates the issue
https://github.com/benmarten/pod_test_2

In this project you can see the error when you open `lib1/Example/lib1.xcworkspace` and build it...

I've tried to add the header search paths to either the lib1/lib1_Example or Pods/lib1 targets with sth like this:
"${PODS_ROOT}/../../../lib2/lib2/Classes/"
which didn't help either... please help!?

**Comment by neonichu** [comment]
lib1 needs to have an explicit dependency on lib2 in the podspec.

**Comment by benmarten** [comment]
Indeed this line fixed it: https://github.com/benmarten/pod_test_2/blob/master/lib1/lib1.podspec#L42
Thanks for your help!
