### ISSUE TITLE
Adding aggregate targets to a pod-template fails when trying to run pod lib create --template=URL

### ISSUE THREAD

**Issue by pkrmf** [CocoaPods/CocoaPods#5758]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I create my own pod-template repository that I basically cloned from https://github.com/CocoaPods/pod-template . I simply added a new **Framework Target** to it and an **Aggregate Target.** After a few modifications to the **project.pbxproj** I was able to install my own template successfully using the pod lib create InfTemplate --template-url=https://myownurl/pod-template.git

The problem happens when I try to run the pod lib create --template-url=... and I select to Not to include the demo application then the execution of the command fails with the following error:
`/ProjectManipulator.rb:48:in block in remove_demo_project': undefined method 'product_type' for #<Xcodeproj::Project::Object::PBXAggregateTarget:0x007f84b9ab2f30> (NoMethodError)
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ProjectManipulator.rb:48:in 'select'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ProjectManipulator.rb:48:in 'remove_demo_project'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ProjectManipulator.rb:32:in 'run'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ConfigureiOS.rb:73:in 'perform'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ConfigureiOS.rb:7:in 'perform'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/TemplateConfigurator.rb:79:in 'run'
	from ./configure:9:in '<main>'
`

 At that point seems that the **ProjectManipulator.rb** tries to parse the **project.pbxproj** and assign the **product_type** variable for each target, which fails because Aggregate Targets don't have a productType defined by apple.

## What did you expect to happen?

I was expecting all my targets(except the demo target) to be renamed and have the demo target deleted from the Project.

## What happened instead?

`pod lib create InfTemplate --template-url=https://myownurl/pod-template.git' failed with the following error:  '/ProjectManipulator.rb:48:in 'block in remove_demo_project': undefined method 'product_type' for #<Xcodeproj::Project::Object::PBXAggregateTarget:0x007f84b9ab2f30> (NoMethodError)
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ProjectManipulator.rb:48:in 'select'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ProjectManipulator.rb:48:in 'remove_demo_project'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ProjectManipulator.rb:32:in 'run'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ConfigureiOS.rb:73:in 'perform'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/ConfigureiOS.rb:7:in 'perform'
	from /Users/itk5291/iOS/Modularization/InfTemplate/setup/TemplateConfigurator.rb:79:in 'run'
	from ./configure:9:in '<main>'
`

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0e6a775e4a93cc252b92b52b4a8b4cbc10537fd8
               usaa-grp-inf-ios-usaa-private-cocoapods - https://gitlab.usaa.com/grp-inf-ios/USAA-Private-CocoaPods.git @ 740d45aff19ade6bbc3cba6de2bd53a8e2f6f2a0
               usaa-grp-inf-ios-usaa-private-cocoapods-test - https://gitlab.usaa.com/grp-inf-ios/usaa-private-cocoapods-test.git @ eefed4eb31204f5c7ba3c0c709db1fcbe2381d5e
               USAA-Private-CocoaPods - git@gitlab.usaa.com:grp-inf-ios/USAA-Private-CocoaPods.git @ 740d45aff19ade6bbc3cba6de2bd53a8e2f6f2a0
               usaa-usaa-private-cocoapods - git@gitlab.usaa.com:grp-inf-ios/USAA-Private-CocoaPods.git @ b4239535b227bcfece4a82c58b57b052b655b7cb
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-art         : 0.9.5
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

I can always attach the project.pbxproj if needed.

**Comment by segiddins** [comment]
This should be fixed by https://github.com/CocoaPods/pod-template/pull/189

**Comment by pkrmf** [comment]
@segiddins What happens if I have more than 1 Native com.apple.product-type.bundle.unit-test Target? Is there a way to select it by product_name?

**Comment by segiddins** [comment]
You'll have to change that logic in your own template, I'm afraid
