### ISSUE TITLE
ld: framework not found Pods_Leanplum_iOS_SDK_Tests

### ISSUE THREAD

**Issue by benmarten** [CocoaPods/CocoaPods#5762]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a added unit tests to my library project and for some reason the build for the test target is failing with an error message.

I cannot really make sense of it, so any help is very much appreciated!

## What did you expect to happen?

The build for the test target succeeds.

## What happened instead?

The build fails with this error message:
```
ld: framework not found Pods_Leanplum_iOS_SDK_Tests
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```
error: cannot parse the debug map for "/Users/Ben/Library/Developer/Xcode/DerivedData/Leanplum-iOS-SDK-goopdvcfaxomcicohleyhupcctiq/Build/Products/Debug-iphoneos/Leanplum-iOS-SDK_Example.app/PlugIns/Leanplum-iOS-SDK_Tests.xctest/Leanplum-iOS-SDK_Tests": No such file or directory
```
<img width="1440" alt="screen shot 2016-08-17 at 4 47 00 pm" src="https://cloud.githubusercontent.com/assets/5960238/17757451/bb4b161e-649b-11e6-81a6-887a1c06fc8f.png">

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : CocoaPods-Test-Repository - https://github.com/benmarten/CocoaPods-Test-Repository.git @ b87ff1dcde766ac9b2db6cafbc2b559146df84b4
               Leanplum-CocoaPods - https://github.com/Leanplum/CocoaPods.git @ 271ec364b8395382771c9ca37ecd081f5435f5db
               Leanplum-CocoaPods-Private - https://github.com/leanplum/CocoaPods-Private.git @ 0b7d9fbb4e76c2ec88fe2eabee7cdfaea2097b3f
               master - https://github.com/CocoaPods/Specs.git @ 5a98665b91ca53c2c5038898024e9d2e0f475bed
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'Leanplum-iOS-SDK_Example' do
  pod 'Leanplum-iOS-SDK', :path => '../'

  target 'Leanplum-iOS-SDK_Tests' do
    pod 'OCMock', '~> 3.3.1'

  end
end
```

## Project that demonstrates the issue

Unfortunately I cannot reproduce the issue in an isolated issue. I know that's not ideal, but since it's inhouse company code I cannot share at this point. Any help on how I can dig to the root of the problem is appreciated very much though!

**Comment by benmarten** [comment]
Ok, after playing around with the build targets. The issue seems to be resolved for me.

![1](https://cloud.githubusercontent.com/assets/5960238/17757784/9a7b3a38-649e-11e6-840c-b533ad2b0b26.png)

Turned out the Pods_Leanplum_iOS_SDK_Tests.framework was adde to the linking step of the test target.
Removing it from there or simply deleting the xcworkspace and running pod install again resolved it for me... 

Not sure how this framework ended up in there... Please comment if that's not a proper solution ;)

**Comment by gaoshanyu** [comment]
I also meet this problem, and remove the <pods framework> from "Linked Frameworks and Libraries" will disappear the error. But if we run command "pod install" the <pods framework> will coming again, and the error will appear after we re-build project. It's not nice I think, any solution can to let cocoa pods does not add <pods framework> to "Linked Frameworks and Libraries"?

**Comment by AlexKel** [comment]
Legend! Just had the same issue, spend an hour trying to resolve.. This was caused by me adding additional tests target to my project... then removing it as decided unnecessary. Then in linking I've had 2 frameworks, one of which wasn't there anymore.

**Comment by srafik-jd** [comment]
Same thing happened to me, spent a good hour trying to resolve it. It was an unnecessary file inside the framework folder. I just deleted it and everything worked fine.

**Comment by lucasangelilima** [comment]
Thank's man, really helped!
