### ISSUE TITLE
use_frameworks! is not able to read the resources from private pod

### ISSUE THREAD

**Issue by baby03201** [CocoaPods/CocoaPods#5763]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a private pod which is sharing resources with my current project.
In the podspec, i do set `s.resources = "Resources/*"` which is the folder contains some plist files I wanna to share between the projects.
Recently, I added `use_frameworks!` to my current project.

## What did you expect to happen?
`pod update` in current project, the files below the Resources folder are accessible.

## What happened instead?
The files were missing. 

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.5.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ac9cd4e749fef8f8a6057ed2ac0261ee12d4fffc
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'MyProject' do
#--BEGIN LOCAL In-House Dependencies
    pod 'My-Private-Kit', :path => '~/PodsLocal/My-Private-Kit'
#--END LOCAL In-House Dependencies
end
```

**Comment by neonichu** [comment]
Are the resources actually not there or just no longer in the main bundle? See remarks about mainBundle in http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/.

**Comment by baby03201** [comment]
Hi @neonichu Thanks for responding~ 
I'm not familiar with podspec and wonder where the files set in `s.resources` will be located if I'm using use_frameworks! in my pod.
I tried to list out the files within`[[NSBundle mainBundle] resourcePath]` but couldn't find the files until i remove `use_frameworks!` and rerun `pod update`

According to a similar question I found in [StackOverflow](http://stackoverflow.com/a/29459936/3871220), I tried the solution by using resource_bundles, but it is still empty. I dunno which part I'm missing out in the setting. Hope you can help :)

**Comment by segiddins** [comment]
You should be using `[NSBundle bundleForClass:]` to find the correct bundle, instead of solely using the main bundle

**Comment by baby03201** [comment]
Hi @segiddins thanks for your reply , I would love to use `[NSBundle bundleForClass:]` which is an alternative method for me right now. Meanwhile, I'm curious about where will the files in `s.resources` be allocated to which part of my project, I will prefer to remain current setting instead of adding another `s.resource_bundles` unless it is necessary to use `s.resource_bundles` to share the files.

Thanks again for help and hope this part will have a clue >_<

**Comment by segiddins** [comment]
They should be bundled in with the framework when integrating as a framework and the main bundle when integrating as a static library

**Comment by baby03201** [comment]
@segiddins thank you for explaining this part to me.
confirm again from what i understand here:

if i have an *shareData.plist* under Resources folder in **My-Private-Kit** project,
and i set `s.resources = "Resources/*" ` in my private pod **My-Private-Kit**
when I want to access them in *MyProject* which using `use_frameworks!` in Podfile 

If I have to get *shareData.plist* file, I should use the path`My-Private-Kit.framework/shareData.plist`. Am I right at this part? Btw, I did try this method, but it doesn't work as well. 

Another question is should I add 'My-Private-Kit' into `s.frameworks` list which is in its own project's podspec?

**Comment by segiddins** [comment]
No need to add it as a framework in the podspec

**Comment by baby03201** [comment]
@segiddins thanks a lot, i finally got it work.
i use `[[NSBundle bundleForClass:<#PodSpecClass>] resourcePath]` instead of `[[NSBundle mainBundle] resourcePath]` and finally understand how `use_frameworks!` does.
