### ISSUE TITLE
CocoaPods build phases duplicate

### ISSUE THREAD

**Issue by daviyang35** [CocoaPods/CocoaPods#5764]
## What did you do?
Change Podfile
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.
Project Build Phases no chage,just have one step
 [CP] Check Pods Manifest.lock 

## What happened instead?

pod add new Build Phases [CP] Check Pods Manifest.lock
now Project have 6 step of 
 [CP] Check Pods Manifest.lock 

and Embed Pods Frameworks,Copy Pods Resources duplicate too

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d67263f6e0bdbabdaa6a724cd88067fcfdf2290c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

##other info
we have 13 developer，everyone will run Pod install sync the Pod dependency and upload project.pbxproj to SCM

**Comment by neonichu** [comment]
Since this works fine for most people, we'll need more information to reproduce. Can you share a project which triggers this behaviour or do you have more concrete steps for triggering it?

**Comment by daviyang35** [comment]
isa = PBXNativeTarget;
			buildConfigurationList = 061EFA961963A0DB00DCBE57 /* Build configuration list for PBXNativeTarget "kartor3" */;
			buildPhases = (
				35933C3ADEA27B3130043507 /* [CP] Check Pods Manifest.lock */,
				C98B4B299E45BC1F2D7194A1 /* [CP] Check Pods Manifest.lock */,
				5C280283DDA2982DD54DA6C9 /* [CP] Check Pods Manifest.lock */,
				3A81AD6E9C80CA93166CA15B /* [CP] Check Pods Manifest.lock */,
				456A24D74DC4DAD014181378 /* [CP] Check Pods Manifest.lock */,
				9500DC64BC56853CDD10BE00 /* [CP] Check Pods Manifest.lock */,
				666032693DA1AF2B5905930F /* [CP] Check Pods Manifest.lock */,
				061EFA661963A0DB00DCBE57 /* Sources */,
				061EFA671963A0DB00DCBE57 /* Frameworks */,
				061EFA681963A0DB00DCBE57 /* Resources */,
				AE8213681CCF6A8700A3977C /* ShellScript */,
				78DDFB08DEA028026BD8929F /* [CP] Embed Pods Frameworks */,
				E3869FEEF5EE78CA1AC9EE6C /* [CP] Copy Pods Resources */,
				6EE0C7D6F6D5A20C207C5FD9 /* 📦 Embed Pods Frameworks */,
				72799A1E13E2FF6A6BCE6E79 /* 📦 Copy Pods Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = kartor3;
			productName = kartor3;

**Comment by daviyang35** [comment]
## everytime output this

Generating Pods project
Integrating client project
Pod installation complete! There are 28 dependencies from the Podfile and 29 total pods installed.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.


[!] The `kartor3 [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3/Pods-kartor3.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3 [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3/Pods-kartor3.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_xinqite [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_xinqite/Pods-kartor3_xinqite.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_xinqite [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_xinqite/Pods-kartor3_xinqite.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_lushang [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_lushang/Pods-kartor3_lushang.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_lushang [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_lushang/Pods-kartor3_lushang.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_libao_appstore [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_libao_appstore/Pods-kartor3_libao_appstore.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_libao_appstore [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_libao_appstore/Pods-kartor3_libao_appstore.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_shangshe_appstore [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_shangshe_appstore/Pods-kartor3_shangshe_appstore.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_shangshe_appstore [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_shangshe_appstore/Pods-kartor3_shangshe_appstore.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_xinqite_appstore [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_xinqite_appstore/Pods-kartor3_xinqite_appstore.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_xinqite_appstore [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_xinqite_appstore/Pods-kartor3_xinqite_appstore.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_iyuexiang [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_iyuexiang/Pods-kartor3_iyuexiang.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_iyuexiang [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_iyuexiang/Pods-kartor3_iyuexiang.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_sailing [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_sailing/Pods-kartor3_sailing.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_sailing [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_sailing/Pods-kartor3_sailing.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_sailing_appstore [Debug]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_sailing_appstore/Pods-kartor3_sailing_appstore.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `kartor3_sailing_appstore [Release]` target overrides the `HEADER_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-kartor3_sailing_appstore/Pods-kartor3_sailing_appstore.release.xcconfig'. This can lead to problems with the CocoaPods installation

**Comment by orta** [comment]
My guess is that you have multiple developers using different versions of CocoaPods on the same project, I would recommend using [a Gemfile](https://guides.cocoapods.org/using/a-gemfile.html). 

It could be worth putting  a de-duplicator in CP though (for example @dbgrandi saw this on one of his projects recently too )

**Comment by neonichu** [comment]
I think 1.0.1 became a bit more lenient on names it accepts as meaning a build phase is present because of the emoji removal. I'd be a bit scared of having a fuzzy matching removal of existing build phases from user projects.

**Comment by DanToml** [comment]
It looks like this could happen if:

Developer A (CocoaPods 1.0.1):
- Runs pod install. Generates the e.g. `[CP] Embed Pods Frameworks`.
- Commits and Pushes

Developer B (CocoaPods 1.0.0):
- Runs pod install, doesn't know about the message, so adds an emoji phase
- Commits and Pushes

A:
- Runs pod install again, the `user_project_integrator` calls find, and only returns the first phase, and does nothing because the names are equal

This does not however explain the number of `[CP] Check Pods Manifest.lock` phases 😕.

---

@daviyang35 could you try removing all of the CocoaPods build phases manually, and running `pod install` again please? as well as ensuring that everyone on the team has the same version.

**Comment by daviyang35** [comment]
@DanToml sure,tonight I will try it.

**Comment by daviyang35** [comment]
## deintegrate output
```bash
$ pod deintegrate
Deintegrating `kartor3.xcodeproj`
Deleted 1 'Copy Pods Resources' build phases.
Deleted 1 'Embed Pods Frameworks' build phases.
- libPods-kartor3.a
- libPods-kartor3.a
- Pods-kartor3.debug.xcconfig
- Pods-kartor3.release.xcconfig
```

## now build config

```
isa = PBXNativeTarget;
			buildConfigurationList = 061EFA961963A0DB00DCBE57 /* Build configuration list for PBXNativeTarget "kartor3" */;
			buildPhases = (
				35933C3ADEA27B3130043507 /* [CP] Check Pods Manifest.lock */,
				C98B4B299E45BC1F2D7194A1 /* [CP] Check Pods Manifest.lock */,
				5C280283DDA2982DD54DA6C9 /* [CP] Check Pods Manifest.lock */,
				3A81AD6E9C80CA93166CA15B /* [CP] Check Pods Manifest.lock */,
				456A24D74DC4DAD014181378 /* [CP] Check Pods Manifest.lock */,
				9500DC64BC56853CDD10BE00 /* [CP] Check Pods Manifest.lock */,
				666032693DA1AF2B5905930F /* [CP] Check Pods Manifest.lock */,
				061EFA661963A0DB00DCBE57 /* Sources */,
				061EFA671963A0DB00DCBE57 /* Frameworks */,
				061EFA681963A0DB00DCBE57 /* Resources */,
				AE8213681CCF6A8700A3977C /* ShellScript */,
				78DDFB08DEA028026BD8929F /* [CP] Embed Pods Frameworks */,
				E3869FEEF5EE78CA1AC9EE6C /* [CP] Copy Pods Resources */,
			);
```

**Comment by daviyang35** [comment]
## manually remove all build phases

```
isa = PBXNativeTarget;
			buildConfigurationList = 061EFA961963A0DB00DCBE57 /* Build configuration list for PBXNativeTarget "kartor3" */;
			buildPhases = (
				061EFA661963A0DB00DCBE57 /* Sources */,
				061EFA671963A0DB00DCBE57 /* Frameworks */,
				061EFA681963A0DB00DCBE57 /* Resources */,
				AE8213681CCF6A8700A3977C /* ShellScript */,
			);
```

use pod 1.0.1 Run pod install
```
			isa = PBXNativeTarget;
			buildConfigurationList = 061EFA961963A0DB00DCBE57 /* Build configuration list for PBXNativeTarget "kartor3" */;
			buildPhases = (
				5F4EE4FEA9CA9524858F8FEB /* [CP] Check Pods Manifest.lock */,
				061EFA661963A0DB00DCBE57 /* Sources */,
				061EFA671963A0DB00DCBE57 /* Frameworks */,
				061EFA681963A0DB00DCBE57 /* Resources */,
				AE8213681CCF6A8700A3977C /* ShellScript */,
				4F1C53A96D343C1BCCB6A740 /* [CP] Embed Pods Frameworks */,
				EFB9D4956807D486C7E79B28 /* [CP] Copy Pods Resources */,
			);
```

**Comment by DanToml** [comment]
@daviyang35 Thanks. I submitted https://github.com/CocoaPods/cocoapods-deintegrate/pull/27 yesterday after realising that we weren't getting rid of all of the `[CP]` targets on deintegration.

It looks like you're getting the correct output now, and should continue to do so if your team are all running the same version.

**Comment by daviyang35** [comment]
@DanToml Thanks for all. Best Regards.
