### ISSUE TITLE
[1.1.0.beta.1] Unable to find host target

### ISSUE THREAD

**Issue by piercifani** [CocoaPods/CocoaPods#5766]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Attempting to do a `pod install` with 1.1.0 beta 1 fails with the `Unable to find host target` error. Same Podfile generates a correct workspace with version 1.0.1.

## What did you do?
Run `pod install`

## What did you expect to happen?

Workspace generated correctly.

## What happened instead?
`[!] Unable to find host target for Pods-BSWFoundationPlayground. Please add the host targets for the embedded targets to the Podfile.`

## CocoaPods Environment

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/piercifani/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d2b542a4f83c704de50954678bc9adfa5e9238c6
               
```

### Installation Source

```
Executable Path: /Users/piercifani/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-amimono     : 0.0.1
cocoapods-deintegrate : 1.0.0
cocoapods-playgrounds : 1.2.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

abstract_target 'Common' do
    pod 'BSWFoundation', :path => '../BSWFoundation.podspec'

    target 'BSWFoundationPlayground'
    target 'Tests'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
```

## Project that demonstrates the issue

You can find a project that experiences this behaviour here: [BSWFoundation](https://github.com/BlurredSoftware/BSWFoundation) (you'll have to `cd` into `BSWFoundationPlayground` folder)

**Comment by segiddins** [comment]
This should be downgraded to a warning now on master

**Comment by piercifani** [comment]
Awesome! But the. What is triggering the warning? I'm asking in order to fix the underlying issue

**Comment by benasher44** [comment]
On master, you'll get this warning:
```
[!] The Podfile contains framework targets, for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).
```

**Comment by piercifani** [comment]
Awesome! Thanks!!

**Comment by nicksnyder** [comment]
@piercifani Any idea when the next beta will be tagged?

**Comment by piercifani** [comment]
I don't know for sure, but I'm guessing when iOS 10 is released @nicksnyder

**Comment by benasher44** [comment]
@nicksnyder @piercifani the 1.1.0.beta.2 is out! Please give it a try and let us know how it goes!

**Comment by piercifani** [comment]
Yep, it looks like it's working! Thanks!

**Comment by maxx555** [comment]
@piercifani did you eventually find out what caused this warning and how to make it do away?
