### ISSUE TITLE
unable to find target library by 'pod search'

### ISSUE THREAD

**Issue by Lotheve** [CocoaPods/CocoaPods#5770]
I use 'pod search 'AFNetWorking' to search AFNetWorking,but couldnt find 'AFNetWorking'  in the search-results.I just find some surrounding libraries related to 'AFNetWorking',such as 'AFNetworking+RX','AFNetworking+Ext',etc. However,I check local 'repo' directory ,and find 'AFNetWorking' is there.Why is this so？？
<img src="http://chuantu.biz/t5/29/1471666160x1822611318.png">
<img src="http://chuantu.biz/t5/29/1471666017x1822611324.png">
 Actually not only 'AFNetWorking',other library such as 'SDWebImage' also appeared in the same situation.
<img src="http://chuantu.biz/t5/29/1471666277x1822611318.png">
<img src="http://chuantu.biz/t5/29/1471666319x1822611318.png">

Cocoapods version 1.0.1
OSX EI 10.11.5

Please forgive my poor English！

**Comment by neonichu** [comment]
Weird, it seems to work as expected for me. Does the result change if you leave out the quotes?

**Comment by Lotheve** [comment]
I got the culprit!
rm ~/Library/Caches/CocoaPods/search_index.json
then everything works fun!
