### ISSUE TITLE
Include of non-modular header inside framework module error - when pod has a static lib dependency

### ISSUE THREAD

**Issue by nmarkovic04** [CocoaPods/CocoaPods#5776]
# Report

## What did you do?

Trying to implement Segment framework (pod 'Analytics') with the Google Analytics dependency(pod 'Segment-GoogleAnalytics'). Ran pod install. Build the project.

## What did you expect to happen?
Expected a successful build.

## What happened instead?
Build failed with 

> "Include of non-modular header inside framework module 'Segment_GoogleAnalytics.SEGGoogleAnalyticsIntegration' "

 on line 

> #import \<GoogleAnalytics/GAI.h\>

inside the pod.

## CocoaPods Environment

CocoaPods version: 0.39.0

Podfile:

```
xcodeproj "CocoaPods-SegmentImpl.xcodeproj"
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

def pods

    #Segment
    pod 'Analytics'
    pod 'Segment-GoogleAnalytics'

end


target 'CocoaPods-SegmentImpl' do
    pods
end


pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer|

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['PRODUCT_NAME'] == "Segment_GoogleAnalytics"
            config.build_settings['LIBRARY_SEARCH_PATHS'] = ["$(inherited)", "$(PODS_ROOT)/GoogleAnalytics/Libraries", "$(PODS_ROOT)/GoogleIDFASupport/Libraries"]
            config.build_settings['OTHER_LDFLAGS'] = %Q{-weak_framework "CoreData" -weak_framework "SystemConfiguration" -l"z" -l"sqlite3" -l"sqlite3.0" -l"GoogleAnalytics"}
            end
        end
    end

    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end


    `rm -rf Pods/Headers/Private`
    `find Pods -regex 'Pods\/.*\.modulemap' -print0 | xargs -0 sed -i '' 's/private header.*//'`

end

```

Segment-GoogleAnalytics pod depends on the GoogleAnalytics pod which is build as a static library (podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleAnalytics/3.16.0/GoogleAnalytics.podspec.json).

I've tried some solutions from [#4420](https://github.com/CocoaPods/CocoaPods/issues/4420) but no luck. 

Errors:

![ss1](https://www.dropbox.com/s/esun8afu8x554fz/Screen%20Shot%202016-08-22%20at%205.35.07%20PM.png?raw=1)

![ss2](https://www.dropbox.com/s/wanli7zdqs7ookh/Screen%20Shot%202016-08-22%20at%205.49.46%20PM.png?raw=1)

**Comment by neonichu** [comment]
This case is not actually supported by CocoaPods and you can just run `pod install` because you disabled `verify_no_static_framework_transitive_dependencies`.

**Comment by YankaiLiu** [comment]
i also ran into this issue?  how you fixed it?
