### ISSUE TITLE
[1.1.0-beta1] `pod install` doesn’t import requested subspecs

### ISSUE THREAD

**Issue by mxcl** [CocoaPods/CocoaPods#5778]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

🌈

# Report

## What did you do?

Did `pod install` for an Xcode 8 beta 6 project on the following `Podfile`:

```ruby
platform :ios, '9.0'
use_frameworks!

target "foo" do
  pod "Alamofire", git: 'https://github.com/Alamofire/Alamofire.git', branch: "swift3"
  pod "PromiseKit/Alamofire", git: 'https://github.com/mxcl/PromiseKit.git', branch: "swift-3.0", submodules: true
  pod "PromiseKit/CoreLocation", git: 'https://github.com/mxcl/PromiseKit.git', branch: "swift-3.0", submodules: true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

## What did you expect to happen?

All `PromiseKit` subspecs to be imported.

## What happened instead?

Only `PromiseKit/CorePromise` and `Alamofire` were imported.

## CocoaPods Environment

I have since downgraded to 1.0.1 which **does** import all the subspecs so my `pod env` will be un-useful unless I upgrade again, which I will if required.

## Project that demonstrates the issue

I will provide a project upon request.

**Comment by segiddins** [comment]
When you say imported, are you saying that public declarations in `PromiseKit/CoreLocation` aren't available when you `import PromiseKit`?

**Comment by mxcl** [comment]
Sorry if I wasn't clear. Here is a screenshot of what I want:

![screen shot 2016-08-22 at 11 25 39 am](https://cloud.githubusercontent.com/assets/58962/17866384/30ca02d4-685b-11e6-9a54-ed678dfcb3a1.png)

With `1.1.0-beta1` the `CoreLocation` and `Alamofire` subspecs are missing.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/cocoapods-downloader/issues/61 should fix things for you
