### ISSUE TITLE
upgrading to cocoapods 1.0 fails with ld: library not found for -l error

### ISSUE THREAD

**Issue by mkagita** [CocoaPods/CocoaPods#5779]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I upgraded from working 0.0.39 cocoapods and upgraded to 1.0 and getting a link error.

Changed the :exclusive => true with inherit! :search_paths in the podfile.
Ran pod
## What did you expect to happen?
pod install 
then compiled the project using xcodebuild

It should compile
## What happened instead?
I get dreaded ld: library not found for -l error. The files it tries to link does exist so really no clue.

I can't share the source but hoping if there is a good way or some command to find out why this error is occurring. My main issue is this was working properly with previous cocoapods

**Comment by orta** [comment]
This report doesn't really give us enough information to help you, here's our [migration guide](http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/) if you'd like to help yourself. 

If you'd like to give us an example Podfile, and a list of things you've tried we can help out

**Comment by mkagita** [comment]
@orta  thanks. Stripped down version of the Podfile (best I can do here).
The link fails on internallibrary where it's just bunch of c/c++ sources.
The same podspec we had did have any problems with previous version of cocoapods.
If there are any obvious formatting issue with podfile let me know.
meanwhile, I will try to investigate this further to see if I can narrow this down a little.

```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


source 'git@git.corp.company.com:Project/DevelopSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target ‘Project’ do

# Standard frameworks
pod ‘InternalLibrary’, '3.1'

pod 'eigen', '3.2.0', :inhibit_warnings => true

pod 'ZipKit', '~> 1.0.3', :inhibit_warnings => true
pod 'HockeySDK', '3.8.5',  :inhibit_warnings => true
pod 'CXAlertView', :inhibit_warnings => true
pod 'SwipeBack'
pod 'WYPopoverController'
pod 'SevenSwitch', '1.4.0'
pod 'EDSemver'
#pod 'ALAssetsLibrary-CustomPhotoAlbum'
pod 'JRSwizzle'

pod 'MBProgressHUD', '0.9.2'

pod 'SSZipArchive', '0.3.3', :inhibit_warnings => true

pod 'Bolts', '~> 1.7'

end




target ‘UITests’ do
   inherit! :search_paths
pod 'KIF', '~> 3.0', :configurations => ['Debug']
end


target 'KIFTests' do
     inherit! :search_paths
    pod 'KIF', '~> 3.0', :configurations => ['Debug']
end

```

**Comment by neonichu** [comment]
Have you edited `OTHER_LINKER_FLAGS` of the "Project" target at some point by any chance? If you did, it might not be picking up settings from the XCConfigs generated by CocoaPods correctly.

**Comment by mkagita** [comment]
I checked and there appears to be no entry there.
There was libPod.a in project setting and saw a new one libPod-Project.a. I deleted the libPod.a and it seems to work. Maybe change in cocoapods 1.0 renames the libPod name?

**Comment by neonichu** [comment]
Yah, the name is based on the target name, so I'm guessing you were using the implicit top-level target previously.

Sounds like this was a deintegration issue, but those are hard to pin down without an example project, so I'm going to close this.

**Comment by gulzatique** [comment]
I just deleted libPod.a from Target-Build phases - OTHER_LINKER_FLAGS and it worked

**Comment by DavidFafinski** [comment]
gulzatique: Sir, you just saved my day !

**Comment by robertherdzik** [comment]
@gulzatique you save my day! 👏

**Comment by matrixreal** [comment]
@gulzatique
you saved my day 💃

**Comment by llitfkitfk** [comment]
delete libPod.a from Target-Build phases - Link Binary With Libraries

**Comment by gumdal** [comment]
@gulzatique

Your suggestion worked! Thank you!!
