### ISSUE TITLE
target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting

### ISSUE THREAD

**Issue by jeremymankin** [CocoaPods/CocoaPods#5785]
* [*] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
pod update 'NewRelicAgent'

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
Install all pod dependencies correctly without error.

## What happened instead?

ℹ Please replace this with of what happened instead.  
Get the following error:
[!] The `Unlimited [App Store]` target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting defined in `Pods/Target Support Files/Pods-Unlimited/Pods-Unlimited.app store.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8S201h)
         Git : git version 2.6.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d983127d925f544d598baa6c21c9b9789ba26579
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios,"8.0"
inhibit_all_warnings!
use_frameworks!

target "Unlimited" do

    pod 'AFNetworking', '~> 1.3.2'
    pod 'Base64', '~> 1.0.1'
    pod 'iCarousel', '1.7.4'
    pod 'OHAttributedLabel', '~> 3.5.5'
    pod 'TTTAttributedLabel', '~> 1.13.0'
    pod 'NewRelicAgent'
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift2.3'
    pod 'ISO8601DateFormatter', '~> 0.7'
    pod 'Haneke', :path => 'Haneke/'
    pod 'Optimizely-iOS-SDK'
end

target "Unlimited-Tests" do

end

target "Unlimited Debug" do

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
```

**Comment by jeremymankin** [comment]
This is running Xcode 8 Beta 6. Was fine with our iOS9 branch.

**Comment by jeremymankin** [comment]
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}/Pods

**Comment by neonichu** [comment]
This should be a warning, not an error — does `pod update` actually fail for you because of it? Also does the target not override the `GCC_PREPROCESSOR_DEFINITIONS` build setting?

**Comment by jeremymankin** [comment]
Hi Boris, thanks for your reply.

The pod update worked file. I noticed that the Pods/Pods.xcodeproj/project.pbxproj removed SWIFT_VERSION = 2.3; references for our Alamofire networking code. This is why we could not build the app. The reference to TargetAttributes was also removed during the pod update.

**Comment by neonichu** [comment]
This is expected, the Pods project gets rewritten from scratch every time you run `pod install` or `pod update`. You can persist custom build settings by setting them in your existing `post_install` hook. 

Also note that Xcode 8 isn't actually supported by CP 1.0, you will probably run into various problems.

**Comment by Izzyjm** [comment]
Hello I get warnings when I run pod update for "OTHER_LDFLAGS" & "GCC_PREPROCESSOR_DEFINITIONS"  and it says this can lead to problems with cocoapods installation, but what is it refererring to by "it can lead to problems with cocoapods installation" like when I build my project ? because i've ran my xcode project and everything worked fine so not sure what the errors are referring to
