### ISSUE TITLE
CocoaPods Lib Create Project Symlink

### ISSUE THREAD

**Issue by chrisdhaan** [CocoaPods/CocoaPods#5786]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
Ran ```pod lib create```

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
Creation of a CocoaPod library.

## What happened instead?

ℹ Please replace this with of what happened instead.  
Everything went fine. CocoaPod library was created. I had a question regarding the "Symlink to your Project for Carthage support" mentioned in this development guide "https://guides.cocoapods.org/making/using-pod-lib-create.html". Are there any tutorials that show how to use this symlink to integrate with Carthage or any documentation that you support? I haven't been able to find any and I couldn't find any contact info on your website to reach out and ask this question.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
N/A

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
CDYelpKit

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by segiddins** [comment]
Im sorry, I don't quite understand what the issue is?

**Comment by chrisdhaan** [comment]
There was no an issue. As I mentioned, I was just trying to get some info on how a specific subset of CocoaPods worked and I could not find any contact information on the website which is why I turned to GitHub. Thank you @orta for the StackOverflow suggestion. While I searched StackOverflow first for an answer I did not think to ask a question there.
