### ISSUE TITLE
Transitive static framework dependency is not detected as such

### ISSUE THREAD

**Issue by alvivi** [CocoaPods/CocoaPods#5789]
🌈
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I created a pod with a pod dependency ([Firebase/Crash](https://cocoapods.org/?q=Firebase)) and
tried to lint the pod.
## What did you expect to happen?

Lint the pod correctly.
## What happened instead?

Seems that the project cannot be built because the module is not linked, but works using XCode.

```
user@host:dir$ pod lib lint 

 -> CocoapodLibExample (0.0.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] xcodebuild:  dir/CocoapodLibExample/Something.swift:3:8: error: no such module 'FirebaseCrash'

[!] CocoapodLibExample did not pass validation, due to 2 errors.
You can use the `--no-clean` option to inspect any issue.
```
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 95efac829566baf81af726558eaf219acd2fb3ed
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
### Podfile

``` ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoapodLibExample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Crash'

  # Pods for CocoapodLibExample

  target 'CocoapodLibExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
## Project that demonstrates the issue

https://github.com/alvivi/CocoapodLibExample

**Comment by neonichu** [comment]
Looks like "FirebaseCrash" is a static framework which are only linked against the application target by CocoaPods. This should have actually been detected by `verify_no_static_framework_transitive_dependencies` and failed much earlier.

**Comment by alvivi** [comment]
@neonichu that means that pod is working correctly even the lint does not success? Or the opposite?

**Comment by neonichu** [comment]
It's not possible to build this Pod at all, unfortunately, because you cannot have transitive static dependencies while integrating pods as frameworks. Firebase would need to ship dynamic frameworks for this to be supported.

**Comment by chrisballinger** [comment]
@neonichu Is there a writeup about why this is true? Can't the static library be linked into the framework? I've also seen examples of transitive static dependencies working when not caught by the linter.

Also this: https://pewpewthespells.com/blog/convert_static_to_dynamic.html
