### ISSUE TITLE
Headers of development pod included via symlink get acl 'Project' instead of 'Public'

### ISSUE THREAD

**Issue by Thomvis** [CocoaPods/CocoaPods#5790]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?
- run `pod install`. The Podfile includes a development pod via a symlinked path. The podspec of the  dependency has no `public_header_files` property so all headers are public.
## What did you expect to happen?
- the development pod's framework target is correctly created in the Pods project and compiles. All headers should be Public.
## What happened instead?

Errors similar to https://github.com/CocoaPods/CocoaPods/issues/4056 are shown in the umbrella header. When looking at the target membership of the headers in the framework, they are all 'Project'. Only the -umbrella header is 'Public'
### Podfile

``` ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'url of private repo'

platform :ios, '8.0'

use_frameworks!

highstreet_options = {}
highstreet_options[:path] = '/Users/path/with/symlink/to/highstreet'

target 'TargetName' do

    pod 'Highstreet', highstreet_options

end
```
## Project that demonstrates the issue

Can provide project if needed.
## Possible cause & fix

I think the issue is at https://github.com/CocoaPods/CocoaPods/blob/0fce91836f1651cd36e3bf29c20d1f59ca6a58ba/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L373. My best guess is that it is comparing paths where the symlink has not yet been resolved with paths where the symlink has been resolved.

**Comment by segiddins** [comment]
Seems like a likely cause

**Comment by ir-fuel** [comment]
I have a similar issue here. I wrote a framework in Swift that uses some Objc classes. The objc code is inside the framework and the header files are included in the main framework header file. My "standalone" framework project compiles correctly, but when including it as a local dependency via Cocoapods in another project I get a similar error. Investigating the pods project that was generated shows me that my objective C headers files which are marked as public (so I can use them in the main framework header and use them in Swift code) are set to 'project'. This basically means it's impossible for me to include my framework via Cocoapods.

I actually get the same error when writing my podspec and linting it. It downloads my code and gives a build error.

`xxxxxx.h:10:9: Include of non-modular header inside framework module MyFramework.MyFramewoek'`

It seems to ignore the 'public' setting of those headers.

**Comment by dmorrow** [comment]
I have a similar problem with a Swift project that includes Objc pods.
While working on the pod in Development Pods, the header files in the -umbrella.h file can't be found.  They have an acl of 'Project'.  Changing the acl to 'Public' seems to fix the issue.  This should be the default setting for a project with no `public_header_files` set and in Development mode.

**Comment by dev-gao** [comment]
I have a similar issue.

In pod A's podspec file: I wrote
s.public_header_files = "PodName/Module/ModuleProtocol/**/*.h"
When I depend this pod in main project with :git, it work well. ：
pod 'PodName', :git => 'https://git.xx.x.x.x.com/xxxxx/Podname.git'
But when I depend this pod in main project with :path, it went wrong:
pod 'PodName', :path => '/Users/GaoYu/Podlibs_Root/Podname'

The main project's 'Build Phases -> Headers' went wrong: In the Headers all headers became 'project' other than public or private. But when use :git it works well.

**Comment by dev-gao** [comment]
But, how to fix this issue？   Is there any answer?
