### ISSUE TITLE
Add a linter on the files found inside spec.resources

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#5794]
- [x] I've read and helped author the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

Highlight from @ejebleed in https://github.com/CocoaPods/CocoaPods/issues/4331#issuecomment-242970618

> Btw! A little additional feature would be still nice to have from CocoaPods Team.
> Considering to the part of our current issue, pod spec lint command could check the value of the s.resource directive and at least warn if the specified path contains some unusual resource files(like *.swift files in my case).
> That would let developer know if something is wrong already within early stages of development not when it is about to uploading the finished app to app-store.
## What did you do?

Include source files inside the resources directive on a Podspec
## What did you expect to happen?

Ideally it would not pass the linter, or would trigger a warning if anyone can come up with a reason why you would want this.
## What happened instead?

Linter passes, and https://github.com/CocoaPods/CocoaPods/issues/4331 happens - which is really hard to debug.
## CocoaPods Environment

N/A
## Project that demonstrates the issue

N/A

**Comment by segiddins** [comment]
I disagree -- it very well could be valid for source files to be used as resources -- imagine you're shipping a dev tool app that ships withs examples?

**Comment by orta** [comment]
Yeah, that's definitely possible - does feel like it might make a better warning. I think most of the time that would happen it's an unwanted accident though.
