### ISSUE TITLE
use Pod instead of import Parse and Bolts framework

### ISSUE THREAD

**Issue by AnChiChang** [CocoaPods/CocoaPods#5798]
Currently I have a project and import Parse and Bolts framework manually. I want to use Pod to instead of manually import. After Pod install, Build project is fine. However, When I use simulator to run project then get below error message

```
fatal error: lipo: input file (/Users/anchi/Library/Developer/Xcode/DerivedData/xxxxxxx/Build/Products/Debug-iphonesimulator/xxxxxxx.app/Frameworks/Bolts.framework/Bolts) must be a fat file when the -extract option is specified fatal error: lipo: can't open input file: /Users/anchi/Library/Developer/Xcode/DerivedData/xxxxxxx/Build/Products/Debug-iphonesimulator/xxxxxxx.app/Frameworks/Bolts.framework/Bolts-x86_64 (No such file or directory) mv: /Users/anchi/Library/Developer/Xcode/DerivedData/xxxxxxx/Build/Products/Debug-iphonesimulator/xxxxxxx.app/Frameworks/Bolts.framework/Bolts-merged: No such file or directory rm: /Users/anchi/Library/Developer/Xcode/DerivedData/xxxxxxx/Build/Products/Debug-iphonesimulator/xxxxxxx.app/Frameworks/Bolts.framework/Bolts-x86_64: No such file or directory
```

```
fatal error: lipo: input file (/Users/anchi/Library/Developer/Xcode/DerivedData/xxxxxxx/Build/Products/Debug-iphonesimulator/xxxxxxx.app/Frameworks/Parse.framework/Parse) must be a fat file when the -extract option is specified fatal error: lipo: can't open input file: /Users/anchi/Library/Developer/Xcode/DerivedData/xxxxxxx/Build/Products/Debug-iphonesimulator/xxxxxxx.app/Frameworks/Parse.framework/Parse-x86_64 (No such file or directory) mv: /Users/anchi/Library/Developer/Xcode/DerivedData/xxxxxxx/Build/Products/Debug-iphonesimulator/xxxxxxx.app/Frameworks/Parse.framework/Parse-merged: No such file or directory rm: /Users/anchi/Library/Developer/Xcode/DerivedData/xxxxxxx/Build/Products/Debug-iphonesimulator/xxxxxxx.app/Frameworks/Parse.framework/Parse-x86_64: No such file or directory
```

use simulator run app will display error message, after clear and re-run will success. However, stop simulator and re-run will fail. That means, every time run simulator I have to clear first. Have any expert can help ? (xcode 7.3.1)

**Comment by Brett-Best** [comment]
Hi @AnChiChang.
I'd try removing derived data first and see if that helps.
Run this in terminal:
```
rm -rf /Users/anchi/Library/Developer/Xcode/DerivedData/
```

**Comment by AnChiChang** [comment]
I had removed my dervied data, but still the same problem.

**Comment by Brett-Best** [comment]
@AnChiChang okay.
Could you fill [this](https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md) out and post it here please?

**Comment by AnChiChang** [comment]
What did you do?
ℹ 
run pod install 
run pod update
start myproject.xcworkspace
use simulator run app, first is fine, then stop simulator
re-use simulator run app, will get above error message
use Product --> Clear
and re-use simulator run app, will fine

What did you expect to happen?
ℹ every time re-run app will success, not get above error message

What happened instead?
ℹ 
use simulator run app, first is fine, then stop simulator
re-use simulator run app, will get above error message
use Product --> Clear
and re-use simulator run app, will fine

CocoaPods Environment
ℹ 
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7d2e15aa7231912ca68d3b046a91674cdb809805
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

Project that demonstrates the issue
ℹ 
you may download my test project from below link:
https://drive.google.com/open?id=0Bw3J75gtMLePUHhrUFBkLWo4eEE

**Comment by Brett-Best** [comment]
@AnChiChang it looks like a custom run script added to the build phases of the GroupBuy target in the project settings is causing this issue.

I removed it (the script that isn't the fabric one) and that resolved the issue, I am unsure what the script actually achieved though.

**Comment by AnChiChang** [comment]
thanks, I think this script had generated by Fabric when update Fabric version. Do you have any idea about, I want to use Pod to instead of manually import Fabric?

**Comment by Brett-Best** [comment]
@AnChiChang sorry I meant the script that was causing the problem is this one:

```
APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"

find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK; do
EXTRACTED_ARCHS=()

FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"

for ARCH in $ARCHS; do
lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
done

lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"

mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"
rm "${EXTRACTED_ARCHS[@]}"

/usr/bin/codesign -f -s "${CODE_SIGN_IDENTITY}" $FRAMEWORK
done
```

That doesn't seem related to Fabric to me.
