### ISSUE TITLE
pod repo push updates local repo if push fails

### ISSUE THREAD

**Issue by brandonroth** [CocoaPods/CocoaPods#5799]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

ran `pod repo push` to a private repo that I only had read access to 
## What did you expect to happen?

I expected that the local and remote repos would remain untouched.
## What happened instead?

Updates to the remote repo were rejected because I did not have write access.  However the update was pushed to my local pod repo in `~/.cocoapods/repos`

This makes it appear to the local user that even though there was an error the update succeeded because running a `pod install` or `pod update` will install the updated version of the pod. However when other users attempt to run those commands they will fail because the update didn't really happen.

The other issue that comes up with this is that if another user updates the pod and runs `pod repo push` then whenever you attempt to do a `pod repo update` it will fail because the local and remote repos will have conflicts. 
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/brandonroth/.rbenv/versions/2.3.0/lib
Repositories : anonyome-pod-repository - git@gitlab.gc.anonyome.com:anonyome/pod-repository.git @ 7bbd2cb6a79a84257d69889688a8ef7441257113
               master - https://github.com/CocoaPods/Specs.git @ c1d9cc6c538a503c646bbac983bb426596d31217
               master-1 - git@github.com:CocoaPods/Specs.git @ c1d9cc6c538a503c646bbac983bb426596d31217
```
### Installation Source

```
Executable Path: /Users/brandonroth/.rbenv/versions/2.3.0/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by benasher44** [comment]
I think resetting the local repo if the push fails is a great idea. We'd happily accept a PR!
