### ISSUE TITLE
NoMethodError - undefined method `uuid' for nil:NilClass

### ISSUE THREAD

**Issue by lbb631160503** [CocoaPods/CocoaPods#5800]
### Error

```
NoMethodError - undefined method `uuid' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:559:in `map'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:559:in `block in host_targets_for_embedded_target'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:557:in `select'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:557:in `host_targets_for_embedded_target'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:542:in `block in embedded_targets_in_native_target'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:541:in `select'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:541:in `embedded_targets_in_native_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/analyzer.rb:243:in `block in copy_embedded_target_pod_targets_to_host'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/analyzer.rb:242:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/analyzer.rb:242:in `copy_embedded_target_pod_targets_to_host'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/analyzer.rb:299:in `block in generate_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/analyzer.rb:298:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/analyzer.rb:298:in `generate_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:238:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:152:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:151:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60uuid%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NoMethodError - undefined method `uuid' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/5685 [closed] [5 comments]
   2 weeks ago

 - NoMethodError - undefined method `platform' for nil:NilClass error after running pod install from master branch
   https://github.com/CocoaPods/CocoaPods/issues/5783 [closed] [9 comments]
   2 days ago

 - How to remove a file From CocoaPods to avoid duplicates?
   https://github.com/CocoaPods/CocoaPods/issues/3107 [closed] [2 comments]
   14 Jul 2016

and 3 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60uuid'%20for%20nil&type=Issues&utf8=✓

**Comment by benasher44** [comment]
This was fixed in #5637, which is currently on master and not in a release yet. The fix will be available in the next release (1.1.0.beta.2); you can use master to get the fix early until then.

**Comment by lbb631160503** [comment]
How do I change to use 1.1.0.beta.2

**Comment by benasher44** [comment]
It's not released yet. You can however modify your Gemfile to point to the master branches of CocoaPods/CocoaPods and CocoaPods/Xcodeproj in the meantime. This page on Bundler's website explains how: http://bundler.io/git.html

**Comment by benasher44** [comment]
It's now released! You can either update your Gemfile or run `gem install cocoapods --pre`
