### ISSUE TITLE
help me! cocoapods  pod trunk push - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

### ISSUE THREAD

**Issue by Kejiasir** [CocoaPods/CocoaPods#5802]
Xcode Version 7.3.1 (7D1014)
cocoapods Version 1.0.1

podspec:
https://github.com/Kejiasir/YYInfiniteLoopView-demo/blob/master/YYInfiniteLoopView.podspec
 
use
`pod trunk push YYInfiniteLoopView.podspec --allow-warnings --use-libraries`

Get an error message:

- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

- NOTE  | [iOS] xcodebuild:  YYInfiniteLoopView/YYInfiniteLoopView-demo/YYInfiniteLoopView-demo/YYInfiniteLoopView/YYInfiniteLoopView.m:13:9: fatal error: 'YYWeakTimer.h' file not found

My .podspec document should not be wrong of,  please help me

Thanks!

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
