### ISSUE TITLE
Multiple branch versiones

### ISSUE THREAD

**Issue by Pluto-Y** [CocoaPods/CocoaPods#5803]
Is cocoapods possible for user to create multiple branch versiones?
For example, maybe I want to have two version like this:
> branch one: this is based on AFN2.6+
> branch two: this is based on AFN3.+

And branch one I want to push `version 1.*.+` to Cocoapods,
And branch two I want to push `version 2.*.+` to Cocoapods.

And I want to maintain two branch and often to push two difference version to cocoapods.

Is it possible to do this?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
