### ISSUE TITLE
adding --sources to pod update (and possibly install)

### ISSUE THREAD

**Issue by maschall** [CocoaPods/CocoaPods#5807]
🌈
- [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I started looking into implementing this functionality and wanted to start the conversation here.

I work on a project where we share a lot of internal dependencies.  These dependencies (for better or worse) update frequently, such that we made it part of our workflow to `pod update` in Jenkins to make sure we have the latest.  However this means that 3rd party dependencies are also update frequently when not necessarily desired.

What I'd like to do is tell update to only update pods that are in a specific cocoapod repo.

The suggested syntax would be `pod update --sources=InternalRepo,master` and for our team, we'd just use `pod update --sources=InternalRepo` to skip any updates in master.

`--sources` would default to all repos currently added in the Podfile, like we do for `lint` and `repo push` commands.

Additionally, I'm thinking the same code could also be used in `pod install` to explicitly prevent dependencies not in a specific source.  For instance if you wanted to force all dependencies be stored in a InternalRepo.  (This may already be handled with the Podfile source syntax)

**Comment by orta** [comment]
Interesting, I'm a 👍 for this, seems like a useful and well scoped idea

**Comment by orta** [comment]
This is merged 👍

**Comment by zhigangfang** [comment]
@maschall the '--sources' syntax didn't skip master update, using pod version 1.2.0
