### ISSUE TITLE
Is it possible to include xcconfig into one that generated by CocoaPods

### ISSUE THREAD

**Issue by Antondomashnev** [CocoaPods/CocoaPods#5808]
Hi there,

The question is: the CocoaPods generates the `xcconfig` file for my project and I want to include my `xcconfig` file as a dependency into it. Am I able to do in for example in `post_install` hook?
I've only found that the `XCBuildConfiguration` has `build_settings` hash, but as far as I understood I can add or change only keys and not include statements with that hash.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by Antondomashnev** [comment]
@orta thanks, this is the [question](http://stackoverflow.com/questions/39281128/is-it-possible-to-include-xcconfig-into-one-that-generated-by-cocoapods), maybe you know the answer =)
