### ISSUE TITLE
[Xcode 8 beta] pod spec lint: "iPhone 4s is not available"

### ISSUE THREAD

**Issue by dmathewwws** [CocoaPods/CocoaPods#5810]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Trying to lint pod spec with Xcode 8 beta

## What did you expect to happen?

Lint validates

## What happened instead?

- ERROR | [iOS] unknown: Encountered an unknown error (Simulator iPhone 4s is not available.) during validation.

However, iOS 10 does not support iPhone 4S, and my pod support iOS 10+ (because of the Messages Framework)

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 92f229df3d9c62c81f492a19b340346ea857941d
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.0.1/libexec/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

https://github.com/StickerKit/StickerKit-iOS-SDK

**Comment by segiddins** [comment]
This should be fixed in the 1.1 beta

**Comment by dmathewwws** [comment]
Thanks.

**Comment by fenglinxiu** [comment]
@dmathewwws how did you do ? Just update cocoapods to version 1.1 beta?
