### ISSUE TITLE
CocoaPods Website does not show the correct Changelog for a zipped source.

### ISSUE THREAD

**Issue by tirodkar** [CocoaPods/CocoaPods#5811]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

EarlGrey recently updated their CocoaPods to 1.2.0. We use a pre-built framework that we zip up. We use preserve_paths to ensure that our CHANGELOG, README etc. is picked up.

## What did you expect to happen?

On updating to 1.2.0, we expect the [changelog](http://cocoapods.org/pods/EarLGrey#changelog) on the CocoaPods EarlGrey page to be updated to the 1.2.0 that can be obtained by unzipping the archive [here](https://github.com/google/EarlGrey/releases/tag/1.2.0).

## What happened instead?

The changelog on the CocoaPods EarlGrey page is still pointing to 1.1.0.

## CocoaPods Environment

This is independent of the environment.

## Project that demonstrates the issue

* Go to the EarlGrey CocoaPods [site](http://cocoapods.org/pods/EarLGrey#changelog).
* Download the Zip [here](https://github.com/google/EarlGrey/releases/tag/1.2.0).
* Notice that the two changelogs are not the same.

**Comment by tirodkar** [comment]
Yes, the README still shows 1.1.0 as well. Is this latency something that's known of? Maybe we should document that.

**Comment by orta** [comment]
Aye, well, it depends on [the traffic](https://status.cocoapods.org) and how complex the pods are to document, and how many platforms they support - they usually take a few minutes per pod.

 it's showing 1.2.0 now ( I also re-triggered a parse just in case )
