### ISSUE TITLE
🌈 0.39.0 cocoapod not allowing me to pod install correctly

### ISSUE THREAD

**Issue by SirSamShaw** [CocoaPods/CocoaPods#5812]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
 Run `pod install`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
`Unable to load a specification for the plugin `/Users/iosdevelopment/.rvm/gems/ruby-`2.3.0@global/gems/cocoapods-deintegrate-1.0.0`

`NoMethodError - undefined method `to_ary' for #<Pod::Specification name="IHKeyboardAvoiding">`

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
`pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

[https://github.com/ltebean/Live]

Using v. 0.39.0 as instructed on webpage.

**Comment by orta** [comment]
Thanks for the issue, this [is a known issue](https://github.com/CocoaPods/CocoaPods/issues?q=is%3Aissue+to_ary+is%3Aclosed) with 0.39 and ruby 2.3. You can either use a different ruby version or use the new 1.0 branches.

**Comment by SirSamShaw** [comment]
Thank you for this information @orta I apologize for the repeat.
