### ISSUE TITLE
install cocapods-keys to /usr/local/lib/ruby/site_ruby/2.3.0/ path

### ISSUE THREAD

**Issue by Heroex** [CocoaPods/CocoaPods#5814]
Hello,

i have a problem with install cocoapods-keys. If i use sudo gem install cocoapods-keys, so path /Library/Ruby/*****/2.0.0/ is without cocoapods-keys. 

Terminal print out: 
Successfully installed cocoapods-keys-1.7.0
Parsing documentation for cocoapods-keys-1.7.0
Done installing documentation for cocoapods-keys after 0 seconds
1 gem installed

But pod install print: 

---------------------------------------------
Error loading the plugin `cocoapods-keys-1.7.0`.

LoadError - cannot load such file -- /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-keys-1.7.0/lib/cocoapods_plugin.rb
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `block in safe_activate_and_require'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:95:in `safe_activate_and_require'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `map'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command/

This path is different than i found.

Any advices, please?

Thank you

**Comment by neonichu** [comment]
Seems like you have different versions of ruby installed and the one in `/usr/local` has precedence. You should try installing without `sudo`.

**Comment by loudmouth** [comment]
If you're running into the same issue I did and gem installations fail without `sudo`, make sure you
```
chown -R username:group ~/.gem
```

Where of course `username` is your username and `group` is your user's group (in OSX you can see your groupname by navigating to System Preferences > Users & Groups, unlock to make changes and Option + click on your user to see "Advanced Options". The group should be displayed in the newly displayed window).
