### ISSUE TITLE
File not found after adding a framework using 'vendored_frameworks'

### ISSUE THREAD

**Issue by Antondomashnev** [CocoaPods/CocoaPods#5819]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

This issue is similar to #5365

## What did you do?

Setup empty dynamic framework project with one source file and third party framework. Create a `podspec` with `vendored_frameworks` option. Run `pod lib lint`

## What did you expect to happen?

The podspec lints without any error.

## What happened instead?

The podspec doesn't lint because of `- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.` and specifically it can not find files related to this third party framework.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/antondomashnev/.rvm/rubies/ruby-2.2.3/lib
Repositories : artsy - https://github.com/artsy/Specs @ 62a47b357a5c6f5eb2941adbfd185261e044343b
               conichigmbh - git@github.com:conichiGMBH/ios-specs.git @ 461fdfe8a01f40cf611792226ae8d93c3916171c
               conichigmbh-1 - https://github.com/conichiGMBH/ios-specs @ 9bde9d380f77c6b48f2b49f1d60e914b82379696
               czechboy0 - https://github.com/czechboy0/Podspecs.git @ faebf3543d12ab21efdac4a7af094f05c4a31805
               master - https://github.com/CocoaPods/Specs.git @ 5f9a321a320ef4c3791eb4fe4042de1be93f68ea
               master-1 - https://github.com/CocoaPods/Specs.git @ d2dd1b607f4f9872b46a5ecfcdcf758b804f0b53
               master-2 - git@github.com:CocoaPods/Specs.git @ d2dd1b607f4f9872b46a5ecfcdcf758b804f0b53
```

### Installation Source

```
Executable Path: /Users/antondomashnev/.rvm/gems/ruby-2.2.3/bin/pod
```

### Plugins

```
claide-plugins             : 0.9.1
cocoapods-check            : 1.0.0
cocoapods-deintegrate      : 1.0.1
cocoapods-keys             : 1.6.1
cocoapods-packager         : 1.4.0
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-superdeintegrate : 0.0.1
cocoapods-trunk            : 1.0.0
cocoapods-try              : 1.1.0
```

## Project that demonstrates the issue

https://github.com/Antondomashnev/CocoaPodsVendoredFrameworkIssues

**Comment by Antondomashnev** [comment]
I found the workaround, but I believe that is a really bad solution and maybe it works only for my specific case.

I replaced the import of Framework's files from `#import <xxx/yyy.h>` to `#import "yyy.h"`. And after that, I added the `header_search_path` to the headers of the framework.

You can find the updated project in the `possible_workaround` branch of https://github.com/Antondomashnev/CocoaPodsVendoredFrameworkIssues

**Comment by Coeur** [comment]
vendored framework needs to be at the same level as podspec: https://github.com/CocoaPods/CocoaPods/issues/1993#issuecomment-131757189

So move the framework and change it to:

    s.vendored_frameworks = 'PaylevenInAppSDK.framework'

**Comment by Antondomashnev** [comment]
@Coeur thanks for the suggestion, I'll try to apply it and post the update here

**Comment by Antondomashnev** [comment]
@Coeur unfortunately, it's the same. I've updated the example project with the new `PaylevenInAppSDK.framework` but it didn't help.

**Comment by Antondomashnev** [comment]
I've fixed the issue by wrapping the static `PaylevenInAppSDK.framework` into the dynamic framework and create a CocoaPod for it.
