### ISSUE TITLE
Xcode 8 Support

### ISSUE THREAD

**Issue by DanToml** [CocoaPods/CocoaPods#5825]
Outstanding blockers for the release of `1.1.0.rc.1` :shipit: 
- [x] Fix Pod Repo Push https://github.com/CocoaPods/CocoaPods/pull/5822 https://github.com/CocoaPods/Core/pull/352
- [x] Fix Xcodeproj performance regression https://github.com/CocoaPods/Xcodeproj/pull/415

Outstanding blockers for the release of `1.1.0.rc.2`
- [x] Set Swift Version when Linting https://github.com/CocoaPods/CocoaPods/pull/5650 / #5841 

Other
- [ ] Update Examples to build on Swift 2.3 https://github.com/CocoaPods/CocoaPods/pull/5821

**Comment by orta** [comment]
Closing due to done 👍
