### ISSUE TITLE
using cocoapods in static library cause link error

### ISSUE THREAD

**Issue by tiger8888** [CocoaPods/CocoaPods#5830]
such is my project:
<img width="259" alt="1111" src="https://cloud.githubusercontent.com/assets/1930815/18375725/4cee5184-768b-11e6-877c-3505ca9c48d5.png">

podsfile:

``` ruby
platform :ios,'7.0'
workspace 'V.xcworkspace'
target ‘Main’ do
pod 'TMCache','2.1.0'
project ‘Main/Main’
end

target ‘Lib’ do
pod 'ReactiveCocoa', '2.4.7'
project ‘Lib/Lib’
end
```

the Main Project Reference the Lib Project with static library, but when I run the Main, cause such link Error, how to resolve:
PS: Building Active Architecture has set to NO, in all project
<img width="691" alt="4444444" src="https://cloud.githubusercontent.com/assets/1930815/18375787/cc07abb4-768b-11e6-9508-3209f9359053.png">

cocoapod log:

``` ruby
Update all pods
Analyzing dependencies
Downloading dependencies
Using ReactiveCocoa (2.4.7)
Using TMCache (2.1.0)
Generating Pods project
Integrating client projects
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods
installed.

[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
```

**Comment by PrateekVarshney** [comment]
same +1

**Comment by orta** [comment]
CocoaPods has only just supported linking to frameworks ( and I'm not  even sure if it links to static libraries ( @benasher44 ? ) )

Can you please try with the latest release.

**Comment by benasher44** [comment]
@tiger8888 @PrateekVarshney could either of you provide a sample project? I'd be happy to have a look. :)

**Comment by benasher44** [comment]
@tiger8888 I do see though that you have your library project in your workspace. For dependency management (and anecdotally setups I've seen this work), it's to have the library project as a sub-project of the project it's going to be integrated into (i.e. your app project).

**Comment by tiger8888** [comment]
[TestProject.zip](https://github.com/CocoaPods/CocoaPods/files/605694/TestProject.zip)
@benasher44

**Comment by tiger8888** [comment]
@orta 
Yeah,using framework work well

**Comment by benasher44** [comment]
@tiger8888 I plan on taking a look, but it might take me a few weeks to get to it. I'm pretty swamped at work atm.

**Comment by benasher44** [comment]
Hello @tiger8888! I Just wanted to give you a heads up that this has been fixed on master. I have an example project working here: https://github.com/benasher44/CocoaPodsLibExample. Have a great day!

**Comment by evgeniyd** [comment]
Hi @benasher44 

I come over this issue, while searching the solution for #3972 (I am on v1.2.0).
Your sample project (*staticlib* example) also does not work for me:

```
  "_OBJC_CLASS_$_DDTTYLogger", referenced from:
  "_OBJC_CLASS_$_DDLog", referenced from:
```

Even, adding `OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)` does not help your sample to build.
Nevertheless, it helps my project.
