### ISSUE TITLE
module was compiled by old version

### ISSUE THREAD

**Issue by jacobjiangwei** [CocoaPods/CocoaPods#5832]
# Report

## What did you do?

use 1.1.0.beta.2

pod install everything from scratch, trying to upgrade my project

## What did you expect to happen?

Install all pod dependencies correctly.
Compilable

## What happened instead?

After fix something upgrade with swift3, now it pop up only last one error, I believe it's cocoapod's issue, not 3rd library.

GlipUILoadingView.swift:10:8: Module file was created by an older version of the compiler; rebuild 'SnapKit' and try again: /Users/jacob/Library/Developer/Xcode/DerivedData/Glip-akjgkoztjubxjtaktxgfjyefaaex/Build/Products/Debug-iphoneos/SnapKit.framework/Modules/SnapKit.swiftmodule/arm64.swiftmodule

Please help figure out why the snapkit module was compiled by old version??

**Comment by DanToml** [comment]
@jacobjiangwei Please try clearing your derived data folder and try again.

**Comment by gabriellanata** [comment]
I was having the same problem, clearing the derived data folder worked for me
