### ISSUE TITLE
Several platforms for one target

### ISSUE THREAD

**Issue by mariohahn** [CocoaPods/CocoaPods#5833]
Is it possible to do something like this?

```
target 'TVKit' do
    platform :ios, "9.0"
    platform :tvos, "9.0"
    pod 'ObjectMapper'
end
```

To have several platforms for one target?

I would like to do the same like in this article below with Pods.

http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

**Comment by orta** [comment]
Afraid not. This is a nice hack, but as noted in the blog post: this not officially supported in Xcode, it just happens to work. 

We have enough issues keeping in sync with Xcode without trying to add CocoaPods support for things like this I'm afraid. It might make a nice plugin though, so you should give it a shot 👍
