### ISSUE TITLE
Manually download from github

### ISSUE THREAD

**Issue by yurevich1** [CocoaPods/CocoaPods#5835]
Is it possible to download any github project manually?
That is, I do not want to clone the project from repo. Just install project if it exists in directory.
E.g., download here and use:
`/Users/admin/Library/Caches/CocoaPods/Pods/Release/EasyPeasy/1.2.1-b39f8` . is it possible to setup suffix?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
