### ISSUE TITLE
Should verify_no_static_framework_transitive_dependencies execute if integrate_targets is false?

### ISSUE THREAD

**Issue by jafara** [CocoaPods/CocoaPods#5851]
I don't see a reason to execute this check if automatic integration is turned off and leave it up to the developer to control which dependencies get linked and where.

**Comment by neonichu** [comment]
I think it would be OK to do this, but the affected Pod targets would probably still not build out of the box without manual intervention to the Pods project.

**Comment by dnkoutso** [comment]
I agree, if the pod targets do not build correctly with manual integration that should be the developers "fault" :)

**Comment by segiddins** [comment]
I'd be fine with this, but it should at least stay a warning
