### ISSUE TITLE
pod spec lint fails

### ISSUE THREAD

**Issue by eliudnis** [CocoaPods/CocoaPods#5855]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
e.g. Run `pod spec lint --use-libraries --sources=XXXX`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
e.g.Give warnings 

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. My Xcode had updated to Xcode8.The pod lint just fail.   

- ERROR | [iOS] unknown: Encountered an unknown error (Unable to add a source with url `ssh://git@git.sankuai.com/ios/specs.git` named `sankuai-specs-4`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.) during validation.

and i have run "pod repo add" several times and the error is just the same.
every time it fails,the name suffix add 1 

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
CocoaPods : 1.0.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.3.1

**Comment by heshamsalman** [comment]
As a temporary workaround:

Delete your repo from your `~/.cocoapods/repos`, delete the `XYZ-1` repo that got generated in the directory of your pod, re-add your repo, and run it again.

**Comment by benasher44** [comment]
This is fixed in 1.1.0.rc.1
