### ISSUE TITLE
inhibit_all_warnings! not inhibiting documentation warnings on Xcode 8

### ISSUE THREAD

**Issue by tbaranes** [CocoaPods/CocoaPods#5863]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Starting with Xcode8, we got documentation warnings from the dependancies even if `inhibit_all_warnings!` is included in the `Podfile`.

<img width="259" alt="screen shot 2016-09-14 at 09 17 56" src="https://cloud.githubusercontent.com/assets/1402212/18503287/63772cda-7a5c-11e6-8d1a-193e82b7b8c5.png">

## What did you do?

Just include one library (AFNetworking for example), then `pod install`

## What did you expect to happen?

No warnings should be reported!

## What happened instead?

Warnings are reported when compiling the project

## CocoaPods Environment

Using the last `CocoaPods` rc: 1.1.0.rc.2

```
source 'https://github.com/CocoaPods/Specs.git'
workspace './ProjectName.xcworkspace'

use_frameworks!
inhibit_all_warnings!

def shared_pods    
   # Few pods...
end

abstract_target 'ProjectName  Core' do

    shared_pods
    pod 'AFNetworking', '~> 3.0.4'

    project './ProjectName  Core/ProjectName  Core.xcodeproj'
    target 'ProjectName  Core iOS' do
        platform :ios, '8.0'
        target 'ProjectName  Core iOSTests' do
            inherit! :search_paths
        end
      end

    target 'ProjectName  Core macOS' do
        platform :osx, '10.10'

        target 'ProjectName  Core macOSTests' do
            inherit! :search_paths
        end
    end    
end

abstract_target 'ProjectName Apps' do 
    shared_pods

    target :'ProjectName macOS' do
        project './ProjectName macOS/ProjectName macOS.xcodeproj'
        platform :osx, '10.10'
    end

    target :'ProjectName iOS' do
        project './ProjectName iOS/ProjectName iOS.xcodeproj'
        platform :ios, '8.0'
    end
end
```

**Comment by benasher44** [comment]
I've verified that we're still passing the `-w` flag in that scenario for each file compiled in the pod target. This flag causes `clang` to suppress all warnings.

> Starting with Xcode8, we got documentation warnings from the dependancies even if inhibit_all_warnings! is included in the Podfile…

Given that this is on Xcode launch, this sounds like flakiness that would go away when clearing derived data and performing a full build. I'm going to close this for now, but please file a new issue if someone can come up with a project that reproduces the issue.

**Comment by justMaku** [comment]
@benasher44 I've managed to reproduce this:
https://github.com/justMaku/CocoaPodsDocumentationWarnings

To reproduce, checkout that repo and build the tests target. Clearing Derrived Data doesn't help.

**Comment by benasher44** [comment]
Hi @justMaku! I believe someone else has reproduced this as well, and it sounds like a fix is being worked on. You can follow along on in #5589. Have a great day!

**Comment by jkmathew** [comment]
Hi @benasher44 , I could reproduce this, my case is like following.
Podfile is
```
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'NPG Agency' do
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'ECSlidingViewController', '~> 2.0.3'
  pod 'TPKeyboardAvoiding'
end

```
Mine is an objectiveC project. And I am getting Some warnings from this pods. What I could understand is as you said while compiling source files, cocoapods passing `-w` flag. But warning is generated in header files. For example in `SDWebImageCompat.h` a warning is generated with message, ` This block declaration is not a prototype` in `typedef void(^SDWebImageNoParamsBlock)();`

I hope this info is enough for you to understand this issue..

**Comment by yas375** [comment]
Getting same issue. Motivated me to upgrade to the latest version of some pods we are using. Also as a workaround I've disabled some of them with:

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wstrict-prototypes"
@import LibraryName;
#pragma clang diagnostic pop
```
