### ISSUE TITLE
using vendored_frameworks has some warning

### ISSUE THREAD

**Issue by AngryBaby** [CocoaPods/CocoaPods#5865]
- NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/CMBWebKeyboard.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/CmbBase64.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/Common.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/Utility.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/CMBPasswordEncrypt.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/NSData+Encrypt.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/NSString+Additions.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/NSString+Url.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/UrlParser.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/IKeyboardView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/KeyboardNumberButtons.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/PKeyboardNumbersView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/SKeyboardNumbersView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/SKeyboardView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/SKPressedView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/cmbkeyboard_vers.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/CMBWebKeyboard.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/CmbBase64.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/Common.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/Utility.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/CMBPasswordEncrypt.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/NSData+Encrypt.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/NSString+Additions.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/NSString+Url.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/UrlParser.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/IKeyboardView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/KeyboardNumberButtons.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/PKeyboardNumbersView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/SKeyboardNumbersView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/SKeyboardView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/SKPressedView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/cmbkeyboard_vers.o unable to open object file: No such file or directory

CMBPay passed validation.

i wanna to fix out warning, how to do it?

**Comment by orta** [comment]
Please create this using issue template, you're not giving us very much information to work with. Remember, you're a programmer, and we're donating our spare time to help you - give us an error that you'd like to see.
