### ISSUE TITLE
1.1.0.rc2 resets my git remote to CocoaPods/Specs on trunk push

### ISSUE THREAD

**Issue by robertjpayne** [CocoaPods/CocoaPods#5866]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod trunk push`

## What did you expect to happen?

Pod to be linted and pushed to trunk and my git repo to remain pointed at my remote origin.

## What happened instead?

Command finished and my git repo is now pointing at https://github.com/CocoaPods/Specs.git

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12 (16A319)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/var/rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 853203fcb92d4a312cca297d54cde02f208859ff
```

### Installation Source

```
Executable Path: /usr/local/var/rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podspec

```ruby
Pod::Spec.new do |s|
  s.name     = 'Masonry'
  s.version  = '1.0.1'
  s.license  = 'MIT'
  s.summary  = 'Harness the power of Auto Layout NSLayoutConstraints with a simplified, chainable and expressive syntax.'
  s.homepage = 'https://github.com/cloudkite/Masonry'
  s.author   = { 'Jonas Budelmann' => 'jonas.budelmann@gmail.com' }
  s.social_media_url = "http://twitter.com/cloudkite"

  s.source   = { :git => 'https://github.com/cloudkite/Masonry.git', :tag => "v#{s.version}" }

  s.description = %{
    Masonry is a light-weight layout framework which wraps AutoLayout with a nicer syntax.
	Masonry has its own layout DSL which provides a chainable way of describing your
	NSLayoutConstraints which results in layout code which is more concise and readable.
    Masonry supports iOS and Mac OSX.
  }

  pch_AF = <<-EOS
    #ifndef TARGET_OS_IOS
        #define TARGET_OS_IOS TARGET_OS_IPHONE
    #endif
    #ifndef TARGET_OS_TV
        #define TARGET_OS_TV 0
    #endif
  EOS

  s.source_files = 'Masonry/*.{h,m}'

  s.ios.frameworks = 'Foundation', 'UIKit'
  s.tvos.frameworks = 'Foundation', 'UIKit'
  s.osx.frameworks = 'Foundation', 'AppKit'

  s.ios.deployment_target = '6.0' # minimum SDK with autolayout
  s.osx.deployment_target = '10.7' # minimum SDK with autolayout
  s.tvos.deployment_target = '9.0' # minimum SDK with autolayout
  s.requires_arc = true
end
```

### Podfile

```ruby
workspace 'Masonry'

platform :ios, '8.0'

xcodeproj 'Examples/Masonry iOS Examples'
target 'Masonry iOS Examples', :exclusive => true do
  pod 'Masonry', :path => './'
end

target 'Masonry iOS Tests', :exclusive => true do
  xcodeproj 'Tests/Masonry Tests'
  pod 'Expecta'
end

target 'MasonryTestsLoader', :exclusive => true do
  xcodeproj 'Tests/Masonry Tests'
  pod 'Masonry', :path => './'
end

# add settings needed to generate test coverage data
post_install do |installer|

  COV_TARGET_NAME = "Pods-MasonryTestsLoader"
  EXPORT_ENV_PHASE_NAME = "Export Environment Vars"
  EXPORT_ENV_PHASE_SCRIPT = "export | egrep '( BUILT_PRODUCTS_DIR)|(CURRENT_ARCH)|(OBJECT_FILE_DIR_normal)|(SRCROOT)|(OBJROOT)' > $SRCROOT/../script/env.sh"
  
  # find target
  classy_pods_target = installer.pods_project.targets.find{ |target| target.name == COV_TARGET_NAME }
  unless classy_pods_target
   raise ::Pod::Informative, "Failed to find '" << COV_TARGET_NAME << "' target"
  end
       
  # add build settings
  classy_pods_target.build_configurations.each do |config|
    config.build_settings['GCC_GENERATE_TEST_COVERAGE_FILES'] = 'YES'
    config.build_settings['GCC_INSTRUMENT_PROGRAM_FLOW_ARCS'] = 'YES'
  end

  # add build phase
  phase = classy_pods_target.shell_script_build_phases.select{ |bp| bp.name == EXPORT_ENV_PHASE_NAME }.first ||
    classy_pods_target.new_shell_script_build_phase(EXPORT_ENV_PHASE_NAME)
      
  phase.shell_path = "/bin/sh"
  phase.shell_script = EXPORT_ENV_PHASE_SCRIPT
  phase.show_env_vars_in_log = '0'

end
```

I understand this is a really hard one to track down, but this is an incredibly annoying bug that if shipped could be frustrating to a lot of users.

Am willing to help provide any information necessary.

**Comment by robertjpayne** [comment]
We use the Podfile locally to integrate the framework back into the examples but this issue is strictly about why Cocoapods would *ever* reset my remote git repo in the first place.

**Comment by robertjpayne** [comment]
One other note, this happened after I installed `1.1.0.rc2` and then uninstalled `1.0.1`

**Comment by benasher44** [comment]
@robertjpayne can you try again and ensure that `pod --version` prints `1.1.0.rc.2` before running `pod trunk push`. This issue has been fixed once already in `1.1.0.rc.1`. I've had issues locally where I install one version of cococapods, but the active version (shown when I run `pod --version`) is still the previous version. Thanks!

**Comment by robertjpayne** [comment]
@benasher44 I'm 95% positive I had completely uninstalled all other versions before the run mucked it up.

But there is 5% chance that isn't the case. Was it happening 100% of the time in rc.1? If so I managed to push again without it happening so it may have been what you described.

**Comment by benasher44** [comment]
The reason why is that ruby's `Dir.chdir`, which should change directories to the Specs repo before doing git ops on the the Specs repo, broken when upgraded to Xcode 8. In 1.1.0.rc.1, we moved this responsibility onto git via `git -C` (does git ops from the directory you pass it).

**Comment by benasher44** [comment]
@robertjpayne it was an issue previous to 1.1.0.rc.1, and it was fixed in that version.

**Comment by robertjpayne** [comment]
@benasher44 ok, it was probably a weird dependency thing, again I wasn't 100% sure it was using the latest version so I'll close this if it's something you're pretty sure is fixed. If I see it again I'll re-open.
