### ISSUE TITLE
Include of non-modular header inside framework

### ISSUE THREAD

**Issue by NikKovV** [CocoaPods/CocoaPods#5868]
# Report
Error when use "pod lib lint"
There are headers in **UIImageView+CircularProgressView.h** https://github.com/NikKovV/SDWebImage-CircularProgressView
Note, that there are no project in repo, only class files.
```
#import "CircularProgressViewSettings.h"
#import "DACircularProgressView.h"
#import "LinearProgressViewSettings.h"
#import "UIImageView+WebCache.h"
```
## What did you do?
Run "pod lib lint"
## What did you expect to happen?
Check pod to load to cocoapod repo.
## What happened instead?
```
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
- ERROR | xcodebuild:  /Users/***/Library/Developer/Xcode/DerivedData/App-cqeaxqgumyyiwidhghomdfhfumnc/Build/Products/Release-iphonesimulator/SDWebImage-CircularProgressView/SDWebImage_CircularProgressView.framework/Headers/UIImageView+CircularProgressView.h:10:9: error: include of non-modular header inside framework module 'SDWebImage_CircularProgressView.UIImageView_CircularProgressView' [-Werror,-Wnon-modular-include-in-framework-module]
- ERROR | xcodebuild:  /Users/***/Library/Developer/Xcode/DerivedData/App-cqeaxqgumyyiwidhghomdfhfumnc/Build/Products/Release-iphonesimulator/SDWebImage-CircularProgressView/SDWebImage_CircularProgressView.framework/Headers/UIImageView+CircularProgressView.h:12:9: error: include of non-modular header inside framework module 'SDWebImage_CircularProgressView.UIImageView_CircularProgressView' [-Werror,-Wnon-modular-include-in-framework-module]
- NOTE  | xcodebuild:  /var/folders/x2/kp72ysnx7fdcdztrzh1lq2bc0000gp/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'SDWebImage_CircularProgressView'
```
## CocoaPods Environment
cocoapods-1.0.1
## Project that demonstrates the issue
https://github.com/NikKovV/SDWebImage-CircularProgressView

**Comment by orta** [comment]
Did you research the problem?

This is an xcode frameworks issue, in CP 1.x we lint that you can run your pod as a framework so that people can use your libraries in Swift. I'm willing to bet you're using `#import "thing.h"` instead of `#import <thing/thing.h>`

**Comment by NikKovV** [comment]
Yes, i found a couple of same errors, and even find a '<>' way for fixing this problem, but didn't implement it. Sorry. Now, i see, that it works.
Headers after updating:
```
#import "CircularProgressViewSettings.h"
#import "LinearProgressViewSettings.h"
#import <DACircularProgress/DACircularProgressView.h>
#import <SDWebImage/UIImageView+WebCache.h>
```
You can do this ticket as a FAQ +)

**Comment by orta** [comment]
👍
