### ISSUE TITLE
jenkins build with error

### ISSUE THREAD

**Issue by huixisheng** [CocoaPods/CocoaPods#5869]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. jenkins build 

## What did you expect to happen?

build success 

## What happened instead?

```
[ios-test] $ /bin/bash /Users/Shared/Jenkins/tmp/hudson9070822494871381303.sh
/Users/huixisheng/.rvm/rubies/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command.rb:141: warning: Insecure world writable dir /Users/huixisheng/Library/Android/sdk/tools in PATH, mode 040777
Update all pods
  Preparing

Re-creating CocoaPods due to major version update.

Setting up CocoaPods master repo
  $ /Applications/Xcode.app/Contents/Developer/usr/bin/git remote set-url origin https://github.com/CocoaPods/Specs.git
  $ /Applications/Xcode.app/Contents/Developer/usr/bin/git checkout master
  error: Your local changes to the following files would be overwritten by checkout:
  	BYBeautyTips.xcodeproj/project.pbxproj
  Please commit your changes or stash them before you can switch branches.
  Aborting
  [!] Failed: /Applications/Xcode.app/Contents/Developer/usr/bin/git checkout master

Updating spec repo `master`
```

## CocoaPods Environment

```
### Stack


   CocoaPods : 1.1.0.beta.2
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/huixisheng/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d3b9a43a40da6209ba59de63b66585b3e7cd40d4


### Plugins


cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0


## Project that demonstrates the issue

none

**Comment by orta** [comment]
This looks like it is a problem with your Jenkin setup, you need to migrate to 1.0 on your local dev setup. 

Please notes, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by benasher44** [comment]
It also looks like you're using Xcode 8 with 1.1.0.beta.2. You should be using 1.1.0.rc.2.

**Comment by huixisheng** [comment]
thanks
@orta @benasher44

**Comment by huixisheng** [comment]
update  `1.1.0.rc.2`.   it works.  https://github.com/CocoaPods/CocoaPods/issues/5872
