### ISSUE TITLE
Trunk push fails with multiple errors with Swift 3 library

### ISSUE THREAD

**Issue by elsesiy** [CocoaPods/CocoaPods#5871]
* [ x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I just updated a library I'm maintaining to Swift 3 and tried pushing the Podspec to Trunk.

`pod trunk push CVCalendar.podspec`

## What did you expect to happen?

Successful push to TRUNK so others are able to use the library.

## What happened instead?

xcodebuild threw 151 errors and 47 warnings, even though it builds and runs fine through Xcode 8.

## CocoaPods Environment

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/elsesiy/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ef392d414b1bb296a133028851ee2e8478098e2d
```

### Installation Source

```
Executable Path: /Users/elsesiy/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/Mozharovsky/CVCalendar

**Comment by orta** [comment]
Hi, we have had quite a few working Swift 3 libraries come through so far, [are you using a](https://github.com/CocoaPods/blog.cocoapods.org/pull/135#discussion_r78783275) `.swift-version` file?

**Comment by elsesiy** [comment]
Hi, thanks for getting back to me so quickly. No, what is it for?

**Comment by orta** [comment]
I linked you to our blog post about it, explaining why and how. Does the blog post need expanding?

**Comment by elsesiy** [comment]
Oh I missed that, works fine now thanks! I'd suggest to make that clearer in the docs somewhere...
