### ISSUE TITLE
Pod accessability

### ISSUE THREAD

**Issue by froimer** [CocoaPods/CocoaPods#5874]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm trying to achieve this, but I'm not sure if it is possible using Cocoapods:

Main app A includes Pod B, that includes a sub application
Pod B includes sub application, as mentioned in point 1, that uses Alamofire library, installed in its pod
Is it possible to access Alamofire pod installed in Pods B, from main app A?

## What did you expect to happen?

I'm trying to achieve this by pod spec file from Pod B, by source_files parameter, but by the moment, with no results. The objective is to avoid redundancy and align all the apps (main and sub) with same Alamofire version.

## CocoaPods Environment

Version 1.0.1

## Project that demonstrates the issue

Many thanks.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by froimer** [comment]
HI orta,

Many thanks for your reply, but it's also asked in StackOverflow for over a day with no response. I'm surprised because I think it's a good practice to avoid pods redundancy, but still no answer...

http://stackoverflow.com/questions/39491611/pod-accessability

Kind regards.
