### ISSUE TITLE
Error pushing a private pod depending on another private pod containing a static library since 1.0.0 update

### ISSUE THREAD

**Issue by LeT0C** [CocoaPods/CocoaPods#5877]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod repo push $MyPrivateRepo $My1stPod.podspec --verbose --use-libraries --allow-warnings`
`pod repo push $MyPrivateRepo $My2ndPod.podspec --verbose --use-libraries --allow-warnings`

* My1stPod contains a static library built for standard architectures (arm64, armv7, armv7s) with bitcode enabled, and has no dependencies.
* My2ndPod contains only code and depends on various pods, including My1stPod.

## What did you expect to happen?

Both pods being pushed to my repo as it did until cocoapods 0.39.0.

## What happened instead?

When I try to push My2ndPod, I have a compilation error due to "Undefined symbols" from the binary of My1stPod for architectures x86_64 and i386, so it doesn't validate.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.10.0
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : ** HIDDEN : $MyPrivateRepo **
               master - https://github.com/CocoaPods/Specs.git @ 547660e61a96b40acce78d1f125cdb4d1d56f1c3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Comments

This problem appeared at the release of Cocoapods 1.0.0, I did extensive research to find a solution to my problem at that time but I couldn't, so I was still using Cocoapods 0.39.0. Now Cocoapods 0.39.0 is not compatible anymore with Xcode 8 and iOS 10, so I spent another day trying to fix my problem. My conclusion is the following :

* My problem is linked to the fact that my static library inside My1stPod is not built for simulator (i386 and x86_64 architectures) but only for standard architectures. Therefore, I managed to solve it by compiling the binary inside My1stPod for both device architectures and simulator architectures and then merge the two binaries with `lipo -create`. Then, I was able to push My1stPod (with the binaries containing all the architectures) and then to push My2ndPod with a dependency on this last version of My1stPod. The problem is that I have to do this manually as Xcode advises not to do so (see [here](http://stackoverflow.com/questions/3520977/build-fat-static-library-device-simulator-using-xcode-and-sdk-4)), and that the final binary, with both bitcode enabled and multiple architectures included is HUGE, making the git repo containing these binaries event more huge rapidly increasing (25Mo for the final binary, with 1 or 2 releases a week, it's becoming a nightmare to work with this git repo)  !

* It worked completely fine without simulator architectures embedded in the binary of My1stPod until Cocoapods 0.39.0.

## Final questions

* Why pushing My1stPod doesn't cause any trouble even when the binary inside it is only compiled for device architectures ?

* Why was it working with Cocoapods 0.39.0 and not anymore since Cocoapods 1.0.0 ?

* Do you have any advice on how I can solve my problem without taking multiple steps to push my pod and without producing a  HUGE binary for My1stPod.

**Comment by benasher44** [comment]
This looks like a dup of #5854. Closing.
