### ISSUE TITLE
SequenceType compiler error

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [CocoaPods/CocoaPods#5879]
Hi I'm trying to add generic response in a collection but I'm getting compiler error. Here is the error

```Undefined symbols for architecture arm64: "ExpSwift.SearchResults.generate () -> Swift.IndexingGenerator<[A]>", referenced from: ExpSwift_Example.ViewController.(viewDidLoad () -> ()).(closure #1).(closure #3) in ViewController.o ld: symbol(s) not found for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Here are my classes
```swift
    public final class SearchResults<T> {
    
    var results: [T] = []
    let total: Int64
    
    required public init?(results: [T], total: Int64) {
        self.results = results
        self.total = total
    }
    
    public func getResults() -> [T] {
        return self.results
    }
    
    public func getTotal() -> Int64 {
        return self.total
    }
    
    }

    extension SearchResults : SequenceType {
    public func generate() -> IndexingGenerator<Array<T>> {
        return results.generate()
    }
    }
```
Here is my call with alamofire

```swift
ExpSwift.findLocations(["limit":10, "skip":0, "sort":"name"]).then { (locations: SearchResults<Location>) -> Void in
            for location:Location in locations{
                debugPrint(location.get("name"))
            }

            }.error { error in
                debugPrint(error)
        }
    }
```

I did test the same code on a single class and it works, so my only guess is something related to  cocoapods I'm using version 1.0.1 and xcode 7.3.1
I have created a branch here to test the code https://github.com/ScalaInc/exp-ios-sdk/tree/feature/content-children

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by cesar-oyarzun-m** [comment]
I did ask on stackoverflow but after my research is something related with cocoapods, because if I add the same clase inside the project it works, the problems is when the class is part of the library in cocoapods. Here is also the link to the question in stackoverflow http://stackoverflow.com/questions/39498274/sequencetype-generator-generic-swift
