### ISSUE TITLE
pod trunk push fails, likely because it fails to checkout git submodule

### ISSUE THREAD

**Issue by p2** [CocoaPods/CocoaPods#5880]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). I've read all the other issues with submodules, but they mostly apply to **using** Pods with submodules, I'm trying to **push** a Pod that uses submodules.

# Report

## What did you do?

Run `pod trunk push`

## What did you expect to happen?

New version of the library, which passes `pod lib lint`, to be pushed to the repo.

## What happened instead?

Implicit linting of `pod trunk push` fails with errors indicating that it hasn't successfully checked out the submodule.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A313a)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fb689b7dd4abf83f064faa4ec52d30fe3012fc31
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

This concerns the [p2.OAuth2](https://github.com/p2/OAuth2.git) library. I can clone and `swift build` or `xcodebuild` successfully, even `pod lib lint --allow-warnings` works, however `pod trunk push --allow-warnings` fails. I can also use the Pod with:

    pod 'p2.OAuth2', :git => 'https://github.com/p2/OAuth2', :submodules => true

When trying pod trunk push, the build process fails with the error:

> error: use of undeclared type 'KeychainGenericPasswordType'

which is a type defined in the submodule. When using `--verbose` I see that `git submodule update --init --recursive` is run right after cloning, since the temp checkout dir is gone however I cannot verify.

Not sure it matters, but between the previous version (2.3) and the new version (3.0), the remote of the submodule has changed.

**Comment by mxcl** [comment]
I’m hitting this trying to push PromiseKit 4.0.2 too, I think.

**Comment by benasher44** [comment]
@DanToml this looks like another `Dir.chdir` issue, but this time it's affecting `cocoapods-downloader`. It'd be a good one to check once the fix you shipped makes it to CocoaPods. I could also look at applying the `git -C` workaround here as well.
