### ISSUE TITLE
My pod has error on https://cocoapods.org/pods

### ISSUE THREAD

**Issue by terenceLuffy** [CocoaPods/CocoaPods#5884]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Simply open https://cocoapods.org/pods/ASHorizontalScrollView and it shows internal server error while other pods are fine. On the github I can still see my library on Spec (https://github.com/CocoaPods/Specs/tree/master/Specs/ASHorizontalScrollView), but I am not able to push my new release to pod, please help!!

## What did you expect to happen?

I should see my pod details and can push my library to pod server

## What happened instead?

It fails with message "[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later."

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d4aa4957329f39a05025d04d9d60969193c1c31a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://cocoapods.org/pods/ASHorizontalScrollView

**Comment by orta** [comment]
This is now fixed - you should be fine to push your Pods again 👍
