### ISSUE TITLE
Push Access Currently Disabled for claiming pods?

### ISSUE THREAD

**Issue by davecom** [CocoaPods/CocoaPods#5885]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

This seems like an erroneous error message. The blog posts linked to are from 2014.

## What did you do?

Run `pod trunk push` with my podspec

## What did you expect to happen?

pod to be successfully pushed to trunk

## What happened instead?

```
pod trunk push SwiftPriorityQueue.podspec 
Updating spec repo `master`
Validating podspec
 -> SwiftPriorityQueue (1.1.1)

[!] Push access is currently disabled while we allow for owners to claim their Pods. Please read our blog posts: http://blog.cocoapods.org/CocoaPods-Trunk/ and http://blog.cocoapods.org/Claim-Your-Pods/
```

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d4aa4957329f39a05025d04d9d60969193c1c31a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/davecom/SwiftPriorityQueue

**Comment by orta** [comment]
I've just updated the message: https://github.com/CocoaPods/trunk.cocoapods.org/pull/188 

Please give us some time to figure it out.
