### ISSUE TITLE
Unable to pass the validation with a Swift 3 library

### ISSUE THREAD

**Issue by dalu93** [CocoaPods/CocoaPods#5886]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I'm trying to pass the validation calling `pod trunk push` to upload my library update to Swift 3, but it doesn't pass the validation, while **Xcode 8** and **buddybuild** are fine with it 

## What did you do?
I executed `pod trunk push LibraryName.podspec --verbose`

## What did you expect to happen?
That it goes well and my update is released

## What happened instead?
I'm getting errors during the `App.xcworkspace` building: seems like the command is executed with a old version of Xcode since it triggers all the errors due to the new Swift 3 syntax

This is an example

```
/var/folders/cx/hj027cgn34gdp2vk20mgzdr40000gn/T/CocoaPods/Lint/Pods/SwiftHelpSet/Sources/Foundation/NSURLRequestExtensions.swift:18:18: error: use of undeclared type 'URLRequest'
public extension URLRequest {
```

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : dalu93 - https://github.com/dalu93/OpenWeatherAPI.git @ c665c6e68083b0d5e2e65c0dcaef831aed47e9fa
               master - https://github.com/CocoaPods/Specs.git @ cbe6f990bc542c66d82ef8e69a7caabcfd44f712
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/dalu93/SwiftHelpSet

**Comment by orta** [comment]
We're conforming to the swift-version standard in the latest 1.1 RC - see the [changelog](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#enhancements-1)
