### ISSUE TITLE
pod trunk push failing for project upgraded to Swift 3

### ISSUE THREAD

**Issue by ankurp** [CocoaPods/CocoaPods#5887]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I ran `pod trunk push Dollar.podspec` for my project on github https://github.com/ankurp/Dollar

## What did you expect to happen?

Pod should publish without any errors as this used to publish before without any issues.

## What happened instead?

It failed to publish due to the following error `“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

This is despite setting Swift version to 3.0 in the build settings as seen by my commit here https://github.com/ankurp/Dollar/commit/190ba262eac738efd09408a12a433a68cc51d735

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p451 (2014-02-24 revision 45167) [x86_64-darwin12.5.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/apatel471/.rvm/rubies/ruby-2.0.0-p451/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d4aa4957329f39a05025d04d9d60969193c1c31a
```

### Installation Source

```
Executable Path: /Users/someuser/.rvm/gems/ruby-2.0.0-p451@business/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

This is the project that has issue publishing now https://github.com/ankurp/Dollar
More details can be found in this stackoverflow question I posted as well http://stackoverflow.com/questions/39522139/use-legacy-swift-language-version-swift-version-error-when-publishing-cocoap

**Comment by orta** [comment]
We're conforming to the swift-version standard in the latest 1.1 RC - see the [changelog](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#enhancements-1)
