### ISSUE TITLE
Does Cocapods define any (swift) compiler flags while building?

### ISSUE THREAD

**Issue by AndrewSB** [CocoaPods/CocoaPods#5889]
I was wondering if there was any way to distinguish between when the a framework is being compiled by Cocoapods? Possibly through some compiler flag?

I'm currently working on https://github.com/Moya/Moya/pull/563#issuecomment-247729157 and need to alter source code based on whether or not Cocoapods is building the project

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

However, there is a `COCOAPODS` env var in the xcconfig:

e.g.
```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 $(inherited) BITHOCKEY_VERSION="@\"3.8.5\"" BITHOCKEY_C_VERSION="\"3.8.5\"" BITHOCKEY_BUILD="@\"57\"" BITHOCKEY_C_BUILD="\"57\""

```

**Comment by AndrewSB** [comment]
Will keep in mind for any future questions I have about using Cocoapods!

Thanks @orta :smile:
