### ISSUE TITLE
pod install takes 48 seconds for me :(

### ISSUE THREAD

**Issue by hborders** [CocoaPods/CocoaPods#5890]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

This isn't meant to throw shade on CocoaPods. I love it.

`pod install` takes 48 seconds to do a clean install. Since I commit my `Pods/` directory, I often have conflicts in my project and resolve them with `rm -rf Pods Podfile.lock; pod install`. It's frustrating that `pod install` takes so long. I've attached a [`ruby-prof` profile](https://github.com/CocoaPods/CocoaPods/files/477973/call-stack.zip).

Based on the profile, and looking at the source for `Pod::Installer::FileReferencesInstaller#refresh_file_accessors`, it looks like calls to `Pods::Sandbox::PathList#read_file_system` have no data dependencies, so maybe if I implemented this with a multi-threaded C extension it would go faster. `Pods::Sandbox::PathList#read_file_system` also dominates `Pod::Installer#verify_no_duplicate_framework_names`, so maybe a C extension would help there, too.

I've never written a ruby C extension before or submitted a pull request to cocoapods before. Is this something that is likely to be accepted?

## What did you do?
```
$ pod install #after this, all dependencies are downloaded
$ rm -rf Pods Podfile.lock
$ time pod install
Analyzing dependencies
Fetching podspec for [redacted]
Downloading dependencies
Installing [redacted]
Generating Pods project
Integrating client projects
Sending stats
Pod installation complete! There are 19 dependencies from the Podfile and 19 total pods installed.

real	0m48.246s
user	0m45.330s
sys	0m2.203s

## What did you expect to happen?

I expected this to be faster

## What happened instead?

It was slow.

## CocoaPods Environment

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a21bb157fe407753e1b8c73a2f65ee419e62275f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

**Comment by orta** [comment]
We've spent time specifically removing all native extensions from CocoaPods, too many people with too many different ruby setups that make it hard for us to reliably say that "gem install cocoapods" works. 

So from my perspective - probably not, there's probably a lot of uncached lookups etc that is much lower hanging fruit for speed improvements

**Comment by hborders** [comment]
Is there a standard way in ruby to multi-thread? I feel like this is a problem that could be solved very quickly with parallelism.

**Comment by orta** [comment]
not really, not in the way that we're used to in cocoa etc

**Comment by hborders** [comment]
Good news! I worked around the problem without needing threads. I'm waiting for permission from my boss to submit a PR.
`Pod::Sandbox::PathList.read_file_system` is the hot method:
```
      def read_file_system
        unless root.exist?
          raise Informative, "Attempt to read non existent folder `#{root}`."
        end
        escaped_root = escape_path_for_glob(root)
        absolute_paths = Pathname.glob(escaped_root + '**/*', File::FNM_DOTMATCH)
        dirs_and_files = absolute_paths.reject { |path| path.basename.to_s =~ /^\.\.?$/ }
        relative_paths = dirs_and_files.map { |path| path.relative_path_from(root) }
        sorted_paths = relative_paths.map(&:to_s).sort_by(&:upcase)
        @dirs, @files = sorted_paths.partition { |path| File.directory?(root + path) }
        @glob_cache = {}
      end
```

I made the following optimizations:
* Used a simple `String.slice` to create relative paths instead of `path.relative_path_from(root)`. Since we already know that all files must exist under `root` (because we globbed `absolute_paths` from `root`), we can just remove the first `root.to_s.length + 1` characters from an `absolute_path` to get a `relative_path`.
* Partition `dirs` and `files` first since we already get an array of absolute paths back from `Pathname.glob`, removing unnecessary string concat: `File.directory?(root + path)`
* Used `lazy` arrays to reduce array iteration.

I [profiled my new code again](https://github.com/CocoaPods/CocoaPods/files/478512/call-stack2.html.zip), and `read_file_system` practically disappears.

```
# old code
real     0m59.095s
user     0m46.133s
sys      0m2.360s
# new code
real     0m23.712s
user     0m14.492s
sys      0m2.030s
```

**Comment by alloy** [comment]
@hborders Sweet 👌👏

**Comment by orta** [comment]
<3

**Comment by DanToml** [comment]
Fixed in https://github.com/CocoaPods/CocoaPods/pull/5927
