### ISSUE TITLE
CocoaPods 1.1.0 RC2 not respecting explicit versions

### ISSUE THREAD

**Issue by mradzinski** [CocoaPods/CocoaPods#5892]
# Report

## What did you do?
Installed a new version of a Pod, tried reverting the changes to use the previous version but cocoapods keeps installing the newest (problematic) version regardless of my instructions.

1 - removed the Pods directory
2 - removed Podfile.lock
3 - wrote ```Pod 'IQKeyboardManagerSwift', '4.0.5'``` on my podfile
4 - run pod install

## What did you expect to happen?
I expected Cocoapods to install version 4.0.5

## What happened instead?
Cocoapods decided to ignore my explicit version and installed 4.0.6
```Using IQKeyboardManagerSwift (4.0.6)```

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 93231caa7203a64869b6b9b41f7a1ba322504536
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'DMF' do

  # Pods for DMF
  pod 'QorumLogs' #Logging utility
  pod 'Alamofire', '~> 3.4.2' # Networking
  pod 'AlamofireImage', '~> 2.4.1' # Networking Images
  pod 'ObjectMapper', '~> 1.4.0' # JSON
  pod 'DataCache' # Cache
  pod 'Fabric' # Crashlytics
  pod 'Crashlytics' # Crashlytics
  pod 'TOCropViewController' # Image cropper
  # pod 'DeviceKit', '~> 0.3.4' # Device info
  pod 'IQKeyboardManagerSwift', '4.0.5' # Keyboard Manager
  pod 'MMLoadingButton', '~> 0.3.0' # Loading button
  pod 'GKActionSheetPicker' # Pickers
  pod 'KBRoundedButton' # Rounded Buttons
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.0.0' # Field Validation
  
end
```

**Comment by benasher44** [comment]
If you'd like an explicit version, I recommend removing the `~>` and just having the version you want in quotes

**Comment by Coeur** [comment]
As a workaround, can you attempt 'pod install --repo-update'?

**Comment by benasher44** [comment]
Oh whoops I see you did that. Hmm. Try removing your lock file and installing again?

**Comment by benasher44** [comment]
I've tried this locally and cannot reproduce it using CocoaPods 1.1.1. Please try with the latest version and file a new issue with full verbose output if you're still experiencing this. Thanks!
