### ISSUE TITLE
Will dynamic framework increase binary size than static library?

### ISSUE THREAD

**Issue by foobra** [CocoaPods/CocoaPods#5896]
Like AFNetworking.Build it in .a(static) or .framework(dynamic), its own binary size is about 1.2M.

    In static library way, all .a will merge into libPods.a, and unused symbols will not link, so the actual size which include in the final ipa will much less than 1.2M.But in dynamic framework way, the AFNetworking.framwork will entirely included in the final ipa, that's will increase the size of app binary.

    Am i misunderstood something? Will use dynamic frameworks will increase the binary size than static library?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by foobra** [comment]
@orta sorry, I just switch from old podfile format to use_frameworks!, and the final binary size increased!

**Comment by orta** [comment]
No problem, your question is a good one, it's just that the right place to ask it is StackOverflow 👍
