### ISSUE TITLE
Avoid explicitly stating every target in Podfile with Cocoapods 1.x

### ISSUE THREAD

**Issue by idsky2** [CocoaPods/CocoaPods#5898]
I have over 20 targets in my XCode project, and I often add or remove one.

Cocoapods v0.x created libPods.a which was linked to all my targets.  Easy.

With Cocoapods v1.x, I have to specify every target in the Podfile. It creates over 20 identical library files, and if I change the targets, I have to update the Podfile and run pod install again.

I want to just make "libPods.a" or "libPods-common.a" and link this to all targets.  
Is there a way?  
If not, please add this 'common library' for all targets feature because right now Cocoapods 1.x is a lot worse than v0 for me.

**Comment by neonichu** [comment]
Could you share your Podfile? In theory, when using abstract targets common Pods should be deduplicated automatically.

**Comment by idsky2** [comment]
Here's my Podfile (with all my different target names changed to '...').
The abstract_target is the default so I didn't bother stating it explicitly.

My 2 annoyances I have with 1.x that I didn't have on 0.x are:
- I need to update my Podfile when I add or remove a target
- I have over 20 libPods-<target_name>.a binaries identical except in name, each linked into one target.

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

    pod 'GoogleMaps'
    
    pod 'MXSegmentedPager'
    pod 'MBProgressHUD'
    pod 'Reachability'
    pod 'AFNetworking'
    pod 'MZFormSheetController'
    pod 'ObjectiveLuhn'
    pod 'TSMessages'
    pod 'NVHTarGzip'

    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'Flurry-iOS-SDK/FlurrySDK'


#Why the #!? do we have to specify every target in Cocoapods 1.x and make 20+ copies of the same lib with different names!?
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'
target '...'

project '../Project.xcodeproj'

post_install do |installer_representation|
    installer_representation.pods_project.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'
        config.build_settings['CLANG_MODULES_AUTOLINK'] = 'NO'
    end
end`

**Comment by orta** [comment]
If you give it a specific abstract target, then it will name the pods library after that. And you might just be better off using xcodeproj in the pod file if you have that many targets that are changing, as it's just a ruby file

```ruby
abstract_target "mypods" do # probably names it something like PodsMyPods.a
   project = Xcodeproj::Project.open "../Project.xcodeproj"
   project.targets.each { |t| target t.name }
   ...
end
```

We changed it because a lot of user problems were due to the implicit target matching I'm afraid, so now it's explicit.

**Comment by idsky2** [comment]
Thanks, I like the .each loop.
That gave me LibPods-mypods-target_name.a for each target without specifying them all.  Pretty good.

I'd still like to get target_name out of there.  If I duplicate a target, I need to manually delete the link with binary and re-run pod install but that's not a big deal.

I had 1 target that needed an extra pod, so I'm using the following that gives me LibPods-target_name.a for each target (where they are all identical except the one special one).

def common_pods
    pod 'GoogleMaps'
    pod 'MXSegmentedPager'
    pod 'MBProgressHUD'
    pod 'Reachability'
    pod 'AFNetworking'
…
end

project = Xcodeproj::Project.open "../Project.xcodeproj"
project.targets.each do |t|
  target t.name do
    common_pods
    if t.name == 'Special Target'
      pod 'extra pod'
    end
  end
end

**Comment by orta** [comment]
Closing as I don't really have anymore ideas, you're welcome to keep digging and pass on anything you've learned @idsky2

**Comment by soumyamahunt** [comment]
None of the workarounds described above worked for me, cocoapods version: 1.11.2. @neonichu  @orta is something like this still possible?

**Comment by pawankmrai** [comment]
@soumyamahunt Its works perfectly for me, just make sure the `Project.xcodeproj` file path is correct and **Project** is name of your project.
_pod version - 1.11.2_
