### ISSUE TITLE
Getting error with pod trunk push DatePickerDialog.podspec --verbose

### ISSUE THREAD

**Issue by lfarah** [CocoaPods/CocoaPods#5901]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I ran ```pod trunk push DatePickerDialog.podspec --verbose'''

## What did you expect to happen?
I expected my pod to be released since ```pod spec lint``` passed validation

## What happened instead?
I got this error:
```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Updating spec repo `master`
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin16.0.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12 (16A320)
       Xcode : 8.0 (8A218a)
         Git : git version 2.9.0
Ruby lib dir : /Users/lucasfarah/.rvm/rubies/ruby-2.0.0-p648/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

### Installation Source

```
Executable Path: /Users/lucasfarah/.rvm/gems/ruby-2.0.0-p648/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
## Project that demonstrates the issue
[UIDatePickerDialog](https://github.com/squimer/DatePickerDialog-iOS-Swift)

## Other comments
I saw that there were some issues open about this problem but my pod is public

**Comment by orta** [comment]
It looks like something is off with your local copy of your Specs repo: 

```
Repositories : master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Or your git instance... Hard to tell. Can please you try deleting the spec repo and re-try? `rm -rf ~/.cocoapods/repos/master/`

**Comment by lfarah** [comment]
It worked... Thanks Orta 😄
