### ISSUE TITLE
wrong xcodebuild swift version when linting podspec

### ISSUE THREAD

**Issue by SahandTheGreat** [CocoaPods/CocoaPods#5907]
# Report

I'm trying to run ```pod lib lint``` and I receive an error from xcodebuild stating that my syntax is wrong. I recently updated Xcode to 8.0 and also updated CocoaPods to the pre-release.

## What did you do?

I ran ```pod lib lint```

## What did you expect to happen?

Lint the pod successfully.

## What happened instead?

```
ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] xcodebuild:  /Users/sahandedrisian/Desktop/FantasticView/FantasticView/FantasticView.swift:13:32: error: type 'UIColor' has no member 'red'
    - ERROR | [iOS] xcodebuild:  /Users/sahandedrisian/Desktop/FantasticView/FantasticView/FantasticView.swift:20:37: error: use of unresolved identifier 'Timer'
```

The second and third errors indicate that xcodebuild doesn't recognize the new Swift 3.0 syntax, since ```UIColor.redColor()``` has converted to ```UIColor.red``` and ```NSTimer``` has converted to ```Timer```.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A304a)
       Xcode : 8.0 (8A218a)
         Git : git version 2.9.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 213387ec3efa5da6b567d51a43af44d71df95585
               SENoiceTable - https://github.com/SahandTheGreat/SENoiceTable @ 80968c1c4a3e96ee9c114658b8991b77e7ca8e02
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/SahandTheGreat/FantasticView

**Comment by hilen** [comment]
+1

**Comment by neonichu** [comment]
See #5881 which updated the documentation on how to configure the Swift version used for linting.
