### ISSUE TITLE
How to install 1.1.0.rc.2 version?

### ISSUE THREAD

**Issue by magic3584** [CocoaPods/CocoaPods#5909]
I uninstall and  then reinstall, or `sudo gem install cocoapods --pre`, nerther works.

```
pod --version
1.1.0.beta.2
```

### Stack

```
   CocoaPods : 1.1.0.beta.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.9.0
Ruby lib dir : /Users/wang/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0ac650da50234300bf4b55a2e608c95653b07612
```

### Installation Source

```
Executable Path: /Users/wang/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by neonichu** [comment]
Are you using another remote source than `https://rubygems.org/` by any chance? You can check by running `sudo gem env`

**Comment by MickeyHub** [comment]
You can check if 1.1.0.rc.2 version exists in your added sources first by issuing following command `gem search cocoapods --pre`, if the latest prerelease version is not it, you should change the source.
In China, rubyChina's source is better than Taobao IMO, https://gems.ruby-china.org/

**Comment by benasher44** [comment]
@magic3584 if you `gem install cocoapods --pre` successfully and `pod --version` still prints an old version, then try `gem uninstall cocoapods`. It should present you with a list of versions to uninstall. Do this until you're left with one version of cocoapods left installed, and then you should be in good shape.

**Comment by GitterYang** [comment]
sudo gem install -n /usr/local/bin cocoapods --pre

**Comment by magic3584** [comment]
Yeah, I was using the taoBao's source. After I changed the source to `https://rubygems.org/` it works. It seems that I have to `echo 3.0 > .swift-version` ?
Thanks all!

**Comment by MickeyHub** [comment]
yeah, rubygems is not always works in China, RubyChina's mirror is prefered.👍
