### ISSUE TITLE
ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.     - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

### ISSUE THREAD

**Issue by hilen** [CocoaPods/CocoaPods#5910]
# Report

## What did you do?
`pod spec lint TSVoiceConverter.podspec --verbose`

## What did you expect to happen?
pod spec correctly

## What happened instead?

```
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = iphonesimulator10.0

xcodebuild: error: 'App.xcworkspace' does not exist.
 -> TSVoiceConverter (0.1.3)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command/spec/lint.rb:77:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/bin/pod:22:in `load'
/usr/bin/pod:22:in `<main>'
```

## CocoaPods Environment
CocoaPods : 1.1.0.beta.2

**Comment by neonichu** [comment]
You need to use the latest release candidate instead of the betas if you are using Xcode 8.

**Comment by hilen** [comment]
I uninstall the version 0.39.0, and run `sudo gem install cocoapods --pre` . And the version is 1.1.0.beta.2

**Comment by neonichu** [comment]
Could you take a look at #5909 and check your remote source as described there

**Comment by hilen** [comment]
Mine is `https://ruby.taobao.org/"`. Is there something wrong with this?

**Comment by neonichu** [comment]
My guess is that it isn't 100% up-to-date with `https://rubygems.org/`, unfortunately.

As you can see on <https://rubygems.org/gems/cocoapods>, the latest version is 1.1.0.rc.2

**Comment by hilen** [comment]
Thanks, everything works fine. The key problem is the GFW.

**Comment by neonichu** [comment]
Yah, just read up on it <https://www.stefanwienert.de/blog/2016/05/13/protip-install-rubygems-in-china/> — wondering if they have a specific issue with mirroring release candidates on `https://ruby.taobao.org/`

**Comment by hilen** [comment]
Thanks 💯

**Comment by NagiYan** [comment]
FXXX the GFW

**Comment by maojj** [comment]
use https://gems.ruby-china.org/  if in China

**Comment by littlepod** [comment]
I was able to resolve this after installijng iOS 9.3 simulator.

Thanks,
Om
