### ISSUE TITLE
pod lib lint: ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. - NOTE | [iOS] xcodebuild: xcodebuild: error: 'App.xcworkspace' does not exist.

### ISSUE THREAD

**Issue by Winter-Yang** [CocoaPods/CocoaPods#5911]
Building with xcodebuild.
xcodebuild clean build -workspace App.xcworkspace -scheme App -configuration Release
xcodebuild: error: 'App.xcworkspace' does not exist.
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR |[ iOS]:xcodebuild: Returned an unsuccessful exit code.
    - NOTE  |[ iOS]:xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

Pods workspace available at `/var/folders/_z/8d24f6811n9403518mv13mn40000gn/T/CocoaPods/Lint/App.xcworkspace` for inspection.

**Comment by neonichu** [comment]
You need to use the latest release candidate if you are using Xcode 8.

**Comment by zzgo** [comment]
@neonichu 
I have same error.
Using Xcode8, cocoapods version to 1.1.0.beta.2.

**Comment by TyroneZhang** [comment]
I have the same error.

**Comment by benasher44** [comment]
You'll need to use 1.1.0.rc.3. If you're experiencing this issue with that version, please open a new issue.

**Comment by sunshineLixun** [comment]
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist. Using Xcode8 cocoapods version to 1.1.0.beta.2

**Comment by benasher44** [comment]
Hi @sunshineLixun! 1.1.1 is the latest stable release that is compatible with Xcode 8. If you could please upgrade and give it a try, we'd really appreciate it! If you're still having issues after that, please open up a new issue and fill out the issue template. Thanks!
