### ISSUE TITLE
Failed to install dependencies from branches

### ISSUE THREAD

**Issue by pietbrauer** [CocoaPods/CocoaPods#5912]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

When integrating `OctoKit.swift` into my project using the `swift-3.0` or `swift-2.3` I also need to install `NBNRequestKit` from branch `swift-3.0` or `swift-2.3` branch respectively. I get an error:

```bash
Analyzing dependencies
Pre-downloading: `NBNRequestKit` from `https://github.com/nerdishbynature/RequestKit.git`, branch `swift-3.0`
Pre-downloading: `OctoKit.swift` from `https://github.com/nerdishbynature/OctoKit.swift.git`, branch `swift-3.0`
[!] Unable to satisfy the following requirements:

- `NBNRequestKit (from `https://github.com/nerdishbynature/RequestKit.git`, branch `swift-3.0`)` required by `Podfile`
- `NBNRequestKit (~> 0.3.0)` required by `OctoKit.swift (0.6.1)`
```

The Podfile:

```ruby
platform :ios, '10.0'
use_frameworks!

target 'MyProject' do
  pod 'NBNRequestKit', :git => 'https://github.com/nerdishbynature/RequestKit.git', :branch => 'swift-3.0'
  pod 'OctoKit.swift', :git => 'https://github.com/nerdishbynature/OctoKit.swift.git', :branch => 'swift-3.0'
end
```

## What did you expect to happen?

It should install both dependencies from the branches.

I remember that in old version of CocoaPods this was working and the Podfile overrides the version requirement of dependencies. 

## What happened instead?

It is not installing anything. 😢 

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.4.6
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4e80c725e4f89886f200b08d0e6b533ac667270d
```

### Installation Source

```
Executable Path: /Users/pietbrauer/.gem/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
use_frameworks!

target 'TanukiKitTest' do
  pod 'NBNRequestKit', :git => 'https://github.com/nerdishbynature/RequestKit.git', :branch => 'swift-3.0'
  pod 'OctoKit.swift', :git => 'https://github.com/nerdishbynature/OctoKit.swift.git', :branch => 'swift-3.0'
end
```

## Project that demonstrates the issue

This occurred in https://github.com/nerdishbynature/octokit.swift/pull/49#issuecomment-239662920 and an example project can be found here https://github.com/pietbrauer/OctoKit-Swift-Branch-Test.

**Comment by hamchapman** [comment]
I think it'll be because in the RequestKit podspec on the swift-3.0 branch the version of the pod has been updated to 1.0.0 (https://github.com/nerdishbynature/RequestKit/blob/swift-3.0/NBNRequestKit.podspec#L3)

However, in the Octokit repo the dependency is still specified as `~> 0.3.0`, which `1.0.0` will not satisfy.

Looks like you might have come to that conclusion in the other issue already on closer inspection!

**Comment by pietbrauer** [comment]
Ugh, sorry about that. Thanks for the quick response. ❤️
