### ISSUE TITLE
"pod lib lint" fail when cocoapods version is 1.0.1

### ISSUE THREAD

**Issue by AngryBaby** [CocoaPods/CocoaPods#5913]
use "pod lib lint" , i get error
  - ERROR | [iOS] unknown: Encountered an unknown error (Simulator iPhone 4s is not available.) during validation.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod lib lint`

## What did you expect to happen?

Pass the linter check.

## What happened instead?

- ERROR | [iOS] unknown: Encountered an unknown error (Simulator iPhone 4s is not available.) during validation.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : FHSpecs - http://ham@192.168.1.174:8082/r/FHSpecs.git @ a079962e3c1feef479e2a8bdeaacc34465074fa6
               master - https://github.com/CocoaPods/Specs.git @ 168ad0ac8c86d0a3119c434aebce4d2b89f706d6
               ...
               ...
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by AngryBaby** [comment]
xcrun simctl list

== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
== Runtimes ==
iOS 10.0 (10.0 - 14A345) (com.apple.CoreSimulator.SimRuntime.iOS-10-0)
tvOS 10.0 (10.0 - 14T328) (com.apple.CoreSimulator.SimRuntime.tvOS-10-0)
watchOS 3.0 (3.0 - 14S326) (com.apple.CoreSimulator.SimRuntime.watchOS-3-0)
== Devices ==
-- iOS 10.0 --
    iPhone 5 (4BB5C399-11D8-4676-A570-E526F13EA179) (Shutdown)
    iPhone 5s (7D6884E8-0A9C-436E-9C01-A6D8FEBDA2E8) (Shutdown)
    iPhone 6 (F6292E9E-F097-4F6B-A9B9-4BE81745AD26) (Shutdown)
    iPhone 6 Plus (72AD7964-85E2-43F6-A4DB-B0AB4E09EF99) (Shutdown)
    iPhone 6s (250858BF-5736-44D6-B2A0-FC88B7347657) (Shutdown)
    iPhone 6s Plus (1B606470-8442-4567-B950-48F0AF1AFD12) (Shutdown)
    iPhone 7 (062BCE8F-3F4D-4475-AC0D-A51F223E40AF) (Shutdown)
    iPhone 7 Plus (EC809948-563A-49BF-90A4-ABCFF23BA688) (Shutdown)
    iPhone SE (F6293088-BFC8-4458-ADC1-0D61800237F8) (Shutdown)
    iPad Retina (3A90CD61-9395-46EA-9CB2-72D7112F52AB) (Shutdown)
    iPad Air (8D4E85E7-2392-429C-8022-D4E52B0C7DFF) (Shutdown)
    iPad Air 2 (0B1325F5-9ED6-4C34-88A0-1DE2F3F5DA97) (Shutdown)
    iPad Pro (9.7 inch) (64A205B9-DA02-4986-B27F-3901C86C4968) (Shutdown)
    iPad Pro (12.9 inch) (EC54B3F5-434B-4BE9-814A-2D1AE264212A) (Shutdown)
-- tvOS 10.0 --
    Apple TV 1080p (A00B869A-FB85-4333-A454-2316D40C8D82) (Shutdown)
-- watchOS 3.0 --
    Apple Watch - 38mm (EA21F0A7-790D-48B5-879F-B55DC5C92FEF) (Shutdown)
    Apple Watch - 42mm (1657A45C-4110-47E2-B236-003E69F29EE1) (Shutdown)
    Apple Watch Series 2 - 38mm (433D8E63-1F0B-4DF6-B0F0-6779652A198A) (Shutdown)
    Apple Watch Series 2 - 42mm (3DA7D68C-82F2-4928-95CA-9DB1127A83C4) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-8-1 --
    iPhone 4s (CD95F5DD-847A-4CD0-A35A-C4A2072BF5F7) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (73B1098C-86DC-441D-9142-2EB2123BCF6F) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (ECC3A5D2-1B91-4457-89F9-1AC7A93F44DA) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (1AA54E6B-1D99-428E-835A-C3B69B938B7D) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (913E4F37-441C-4A95-8B64-0FAE7D373E64) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (039CFE0D-B8B0-4774-9669-4A119756CB46) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (E27EDCF0-B5EF-4567-BF66-06494DCDEBF5) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (1FB4B46F-EE24-419B-8238-36CB46F4B2C0) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPad (803F5ED6-FB31-4180-BE1A-E39E32CA7BC9) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPhone (68D9BC1C-8248-4FF1-AD97-8CC19D41C5DB) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-8-2 --
    iPhone 4s (67DCB167-A1E0-4A0B-8E75-1404B991F4A3) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (7FB2B26E-E8AA-4093-ABF4-67F80637E409) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (0F01BF9B-236B-4301-9BF4-645C0D34CF6A) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (3661044C-D05D-4111-8A51-97632257B1EC) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (7E97B43B-7956-435C-8032-C3B857B6994B) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (BEF3C6E1-B1A1-41CD-8210-458B9E1F1FF8) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (1DA04C59-58EC-41A3-8445-38741647344E) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (E3FD6280-F94B-4427-82EE-D498FD75DD8C) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPad (87EBE24D-C8BF-48CF-8E4B-5FDA29832324) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPhone (A9F84D98-6543-46C2-8D08-E2441E0FA503) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-8-3 --
    iPhone 4s (ABB04852-86CB-452C-B0E8-09F4939208FF) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (EA52D61C-D347-4085-92F4-805D73EC099E) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (E755680E-58CE-4815-877A-97957A0E9990) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (739F46D7-5900-4CD4-A490-5F6DAECD02CD) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (B174C283-81BF-486E-93DB-00878B16FA6E) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (50BCBBDE-878A-440F-9D73-7F6BCADE2239) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (FA685CCD-27DC-490A-B46B-68C11177DFB3) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (810952CF-7654-451A-8F79-398F7F2B702A) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPad (7E214822-D08F-4455-A6F1-AB285DFF82CB) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPhone (8AEB0B2D-611D-4E09-96FC-F1E065E0DA7B) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-8-4 --
    iPhone 4s (244C7916-AA6B-42E9-A76A-5793CA433043) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (604F55B1-6521-4A1A-825D-802C3444551B) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (1BA17113-CE83-43DA-89C8-52F545BD4892) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (4E399853-706D-4600-98C7-04CB31C74E48) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (BAC6984A-C1AC-459B-8A1D-B18F782AD2DE) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (9B78BE9E-1301-41C4-9F8C-8A96400FC0DD) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (9249721F-53F9-4F5F-8860-CFFDF2B6D0A6) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (48AFF644-AFE5-441C-9767-47DC4A09D69C) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPad (29B456D8-4002-4EB5-9841-A334A47A4915) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPhone (50806695-4319-41EF-A39D-2733E0E785B1) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-1 --
    iPhone 4s (DFBECB1E-0362-4C0B-9849-F5ACFBC75A17) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (5EFAAEE5-6702-4564-8FBA-F39F75664345) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (D0A49D25-96A4-4CBD-8EA2-BFEF8A7917B9) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (C6C32E7F-D2E1-42A5-BEAB-B3325653E151) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (111F0199-57A2-4FF1-B712-87C814EB4A89) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (2FD94DD7-1E1C-4167-B783-71257A6E97FA) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (AAF3431F-0F96-4509-AE19-BCE5A595261F) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (2959161D-471B-449F-874D-4E2DBC150EB1) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (476F9F61-3CD4-48A3-B157-FC9DDB219C46) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (E4CAC146-FB3F-42F9-BD3E-52EDC32D8351) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (C31FD418-7A08-4353-A4E5-BE43A17978E7) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (E51BF5CA-C4A6-46AA-8DD5-93E689985AD4) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-2 --
    iPhone 4s (031A26D0-0A49-4213-B619-031673C88EB1) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (C1E703CD-B831-48A7-B00E-C911DCE01297) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (DC1988EB-2217-4B58-B6D2-492DBCEC34CA) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (DBBA024B-00E9-402B-B3F2-C42D31BE5308) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (DC5A867B-F2DE-40D7-B771-FE2F10F69209) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (022B7A49-0BDF-4B55-AE6B-803B51227002) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (1FFD0069-44BB-43CE-833E-10F6FBF59874) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (A985002E-B591-4767-81DB-222828537B02) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (5A102250-7032-496D-977C-84BDAE8E9BF0) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (7F7F9669-C6C5-4C2F-9C11-10F6A59A243D) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (BC6B141E-D1B7-46C1-8493-4AEF7A7D226E) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (AAA67DAF-FD0A-44A5-8DFE-F89C02652246) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-9-3 --
    iPhone 4s (93EC9D58-2429-40E0-803F-BFBB2E931BD8) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (E2ECF828-C80A-4537-A79D-D77C3F7E63EE) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (F63B4BA0-7C34-4E7F-BCF9-7E2D8B3B4FF2) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (E12AC4FC-9B53-4110-9DAF-C5F6EDC8DEAD) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (C6369B3D-38FA-48B3-9B7F-D836AB30CAA5) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s (38A472CA-FC9A-4F64-9F5B-9F8389DE7CDE) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6s Plus (CEDBC234-6D7D-4C56-BC2A-8FB2D888070C) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (189CE05F-FDA2-49CF-B5E9-F8A52F2FA974) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (4C1F208B-01F3-47E4-9B39-34EF88B981B1) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (09FF2843-5F4E-4E61-A8CA-6E90740FC582) (Shutdown) (unavailable, runtime profile not found)
    iPad Air 2 (62FFA620-F087-4B21-B8B4-616217EFC27C) (Shutdown) (unavailable, runtime profile not found)
    iPad Pro (B603D9F1-F06A-44A7-89CF-BC988883C4DC) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-0 --
    Apple TV 1080p (5356811F-6BFA-4E3C-BE8B-596EF35D33A1) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-1 --
    Apple TV 1080p (C7952F62-BFDC-49C6-A127-EC092C934734) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.tvOS-9-2 --
    Apple TV 1080p (2705F045-A3CF-498C-AEBA-7F0C50FE377B) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-0 --
    Apple Watch - 38mm (3C47491D-57DF-4D8A-9CC1-A773856C8CF7) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (2DF6AD8B-AA73-4D0F-87B5-B52BA78930AC) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-1 --
    Apple Watch - 38mm (1F71AB6A-B128-4988-82E5-EFE9EB9F82D2) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (51BF5B44-9217-486B-883A-D8BF35896F12) (Shutdown) (unavailable, runtime profile not found)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-2 --
    Apple Watch - 38mm (2831D3DA-C13E-4822-A997-ABBB23724E19) (Shutdown) (unavailable, runtime profile not found)
    Apple Watch - 42mm (3E12ADD2-8F83-441F-9217-7E2C1BE005CF) (Shutdown) (unavailable, runtime profile not found)
== Device Pairs ==
DC80B019-534A-4F7F-80FE-F8A8A76F3D5B (active, disconnected)
    Watch: Apple Watch Series 2 - 38mm (433D8E63-1F0B-4DF6-B0F0-6779652A198A) (Shutdown)
    Phone: iPhone 7 (062BCE8F-3F4D-4475-AC0D-A51F223E40AF) (Shutdown)
B2E440B0-5E17-4F4D-A50F-70BF3B2959E4 (active, disconnected)
    Watch: Apple Watch Series 2 - 42mm (3DA7D68C-82F2-4928-95CA-9DB1127A83C4) (Shutdown)
    Phone: iPhone 7 Plus (EC809948-563A-49BF-90A4-ABCFF23BA688) (Shutdown)
8C79D0B2-CA8A-4639-8B2E-3138BD98737A (unavailable)
    Watch: Apple Watch - 38mm (3C47491D-57DF-4D8A-9CC1-A773856C8CF7) (Shutdown)
    Phone: iPhone 6s (2FD94DD7-1E1C-4167-B783-71257A6E97FA) (Shutdown)
341B96EE-BCF0-4697-B23D-2EA37288951B (unavailable)
    Watch: Apple Watch - 42mm (2DF6AD8B-AA73-4D0F-87B5-B52BA78930AC) (Shutdown)
    Phone: iPhone 6s Plus (AAF3431F-0F96-4509-AE19-BCE5A595261F) (Shutdown)
71259D6B-4DFB-4F06-BD84-2A931AA2758B (unavailable)
    Watch: Apple Watch - 38mm (1F71AB6A-B128-4988-82E5-EFE9EB9F82D2) (Shutdown)
    Phone: iPhone 6s (022B7A49-0BDF-4B55-AE6B-803B51227002) (Shutdown)
44CACD41-AF75-42D9-A422-1A75502A433F (unavailable)
    Watch: Apple Watch - 42mm (51BF5B44-9217-486B-883A-D8BF35896F12) (Shutdown)
    Phone: iPhone 6s Plus (1FFD0069-44BB-43CE-833E-10F6FBF59874) (Shutdown)
520C4C16-CE0B-4369-A9A9-219A1B3AD8D8 (unavailable)
    Watch: Apple Watch - 38mm (2831D3DA-C13E-4822-A997-ABBB23724E19) (Shutdown)
    Phone: iPhone 6s (38A472CA-FC9A-4F64-9F5B-9F8389DE7CDE) (Shutdown)
8BFB41E9-E0E3-4957-A2BE-E5F0D8447E52 (unavailable)
    Watch: Apple Watch - 42mm (3E12ADD2-8F83-441F-9217-7E2C1BE005CF) (Shutdown)
    Phone: iPhone 6s Plus (CEDBC234-6D7D-4C56-BC2A-8FB2D888070C) (Shutdown)

**Comment by AngryBaby** [comment]
after cocoapods update to v1.1.0.beta.2 

pod lib lint 

occur another error

- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

aha

**Comment by neonichu** [comment]
Please update to the latest release candidate instead of using the beta.
