### ISSUE TITLE
Integrating pre-built Swift frameworks causes crash on application launch

### ISSUE THREAD

**Issue by connorcimowsky** [CocoaPods/CocoaPods#5919]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Pre-build a Swift framework into a `.framework` bundle (in this case, [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON), while omitting the macOS, watchOS, and tvOS deployment targets)
2. Create a corresponding `podspec`file
3. Host the two files in a [GitHub repository](https://github.com/connorcimowsky/binarypods/tree/master/SwiftyJSON/2.3.2)
4. Create an empty iOS application using the “Single View Application” template and using Objective-C as the language
5. Create a `Podfile` to integrate SwiftyJSON into the sample application
6. Invoke `bundle exec pod install --repo-update`
7. Enable the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build option
8. Drag `SwiftyJSON.framework` from the Pods Xcode project into the “Embedded Binaries” section of the application target's “General” tab (this feels like something CocoaPods should have done)
9. Fix the path of the embedded framework from `ios/SwiftyJSON.framework` to `Pods/SwiftyJSON/ios/SwiftyJSON.framework` (Xcode seems to have gotten it wrong)
10. Build and run the application

## What did you expect to happen?

Expected the application to launch to a blank screen (as is standard for the “Single View Application” template).

## What happened instead?

Both `libswiftCore.dylib` and the `SwiftyJSON` executable are unable to be dynamically linked, and hence the application cannot launch.

<img width="1645" alt="screen shot 2016-09-20 at 4 21 38 pm" src="https://cloud.githubusercontent.com/assets/443395/18692526/c107874e-7f4f-11e6-9fef-836c191e4c33.png">

## CocoaPods Environment

The Gemfile's dependencies are satisfied

### Stack

The Gemfile's dependencies are satisfied

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.2
Ruby lib dir : /Users/connor/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 62bf0ee59cce533a67ebde72b8e3a592ec325798
               binarypods - https://github.com/connorcimowsky/binarypods.git @ c337d37ae29ae3b9cbadb8836141a355c78b4d69
```

### Installation Source

```
Executable Path: /Users/connor/.rvm/gems/ruby-2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/connorcimowsky/binarypods.git'

platform :ios, '8.0'

target 'CocoaPodsSampleApp'

pod 'SwiftyJSON', '2.3.2'
```

## Project that demonstrates the issue

[CocoaPodsSampleApp on GitHub](https://github.com/connorcimowsky/CocoaPodsSampleApp)

**Comment by neonichu** [comment]
I'm unsure why you think this is a CocoaPods issue. It's up to you to ensure that the app you're building is embedding the Swift standard libraries, not sure why that does not happen in your case despite the `EMBEDDED_CONTENT_CONTAINS_SWIFT`.
