### ISSUE TITLE
pod lib lint Error Unable to find a specification for ‘XX’

### ISSUE THREAD

**Issue by 393385724** [CocoaPods/CocoaPods#5920]
use Xcode 7 and  CocoaPods 0.39.0  it work fine, but when upgrade to the latest version，In the following error

Xcode 8.0
CocoaPods Version 1.0.1

pod lib lint --no-clean --verbose --use-libraries --allow-warnings

    DDSocial (1.2.7) - Analyzing on iOS 7.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `DDSocial` from `/Users/lilingang/Desktop/DDProject/DDSocial`

Resolving dependencies of 
 -> DDSocial (1.2.7)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `FBSDKLoginKit (~> 4.12.0)` depended upon by `DDSocial/Facebook`
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:57:in `resolve'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `block in download_pod'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `each'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `download_pod'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:269:in `block in perform_extensive_analysis'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `each'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:81:in `validate'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:58:in `block in run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `each'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/lilingang/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `load'
/Users/lilingang/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `<main>'
) during validation.

Pods workspace available at `/var/folders/d6/mzjfh7vd00n2pfwy5vlr5vnw0000gn/T/CocoaPods/Lint/App.xcworkspace` for inspection.

[!] DDSocial did not pass validation, due to 1 error.

/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:75:in `block in run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `each'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/lib/lint.rb:47:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/lilingang/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `load'
/Users/lilingang/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `<main>'

**Comment by 393385724** [comment]
Pod::Spec.new do |s|  
  s.name             = "DDSocial"  
  s.version          = "1.2.7"  
  s.summary          = "A share auth wheels based on the official library content wecaht sina tencent facebook twitter google mi"  
  s.homepage         = "https://github.com/393385724/DDSocial"  
  s.license          = 'MIT'  
  s.author           = { "llg" => "393385724@qq.com" }  
  s.source           = { :git => "https://github.com/393385724/DDSocial.git", :tag => s.version.to_s }  
  
  s.platform     = :ios, '7.0'  
  s.requires_arc = true 

  s.subspec 'Core' do |core|
    core.source_files  = 'DDSocial/Core/*.{h,m}'
    core.frameworks    = 'Foundation', 'UIKit', 'Accelerate'
  end

  s.subspec 'Tencent' do |tencent|
    tencent.source_files = 'DDSocial/Tencent/Handler/*.{h,m}'
    tencent.ios.vendored_frameworks = 'DDSocial/Tencent/TencentSDK/*.framework'
    tencent.resource = "DDSocial/Tencent/TencentSDK/*.bundle"
    tencent.libraries = 'z', 'sqlite3','stdc++','iconv'
    tencent.frameworks = 'SystemConfiguration','CoreGraphics', 'CoreTelephony', 'Security'
    tencent.dependency 'DDSocial/Core'
  end

  s.subspec 'Wechat' do |wechat|
    wechat.source_files = 'DDSocial/Wechat/Handler/*.{h,m}','DDSocial/Wechat/WeChatSDK/*.h'
    wechat.ios.vendored_libraries = 'DDSocial/Wechat/WeChatSDK/*.a'
    wechat.libraries = 'z', 'sqlite3','stdc++'
    wechat.frameworks = 'SystemConfiguration','CoreTelephony'
    wechat.dependency 'DDSocial/Core'
  end

  s.subspec 'Sina' do |sina|
    sina.source_files = 'DDSocial/Sina/*.{h,m}'
    sina.dependency 'WeiboSDK', '~> 3.1.3'
    sina.dependency 'DDSocial/Core'
  end

  s.subspec 'Facebook' do |facebook|
    facebook.source_files = 'DDSocial/Facebook/*.{h,m}'
    facebook.dependency 'FBSDKLoginKit', '~> 4.12.0'
    facebook.dependency 'FBSDKShareKit', '~> 4.12.0'
    facebook.dependency 'DDSocial/Core'
  end

  s.subspec 'Twitter' do |twitter|
    twitter.source_files = 'DDSocial/Twitter/*.{h,m}'
	twitter.xcconfig = { 'CLANG_ENABLE_MODULES' => 'NO' }
    twitter.dependency 'TwitterKit', '~> 1.15.3'
    twitter.dependency 'DDSocial/Core'
  end
  
  s.subspec 'MiLiao' do |miliao|
    miliao.source_files = 'DDSocial/MiLiao/Handler/*.{h,m}'
    miliao.ios.vendored_frameworks = 'DDSocial/MiLiao/MiLiaoSDK/*.framework'
    miliao.dependency 'DDSocial/Core'
  end

  s.subspec 'MI' do |mi|
    mi.source_files = 'DDSocial/MI/**/*.{h,m}'
    mi.ios.vendored_frameworks = 'DDSocial/MI/Resources/*.framework'
    mi.resource = "DDSocial/MI/Resources/*.bundle"
	  mi.xcconfig = { 'ENABLE_BITCODE' => 'NO' }
    mi.libraries = 'stdc++'  
    mi.dependency 'DDSocial/Core'
    mi.dependency 'TTTAttributedLabel', '~> 1.13.4'
  end

  s.subspec 'Google' do |google|
    google.source_files = 'DDSocial/Google/*.{h,m}'
    google.dependency 'Google/SignIn', '~> 3.0.3'
    google.dependency 'DDSocial/Core'
  end

  s.subspec 'Share' do |share|
    share.source_files  = 'DDSocial/Handler/DDSocialShareHandler.{h,m}'
    share.dependency 'DDSocial/Core'
  end
end

**Comment by neonichu** [comment]
If you are using Xcode 8, you need to use CocoaPods 1.1.0.rc.2 — you can install that using `[sudo] gem install cocoapods --pre`.

**Comment by 393385724** [comment]
Xcode 8 and Cocopods 1.1.0.rc.2
pod lib lint --no-clean --verbose --use-libraries --allow-warnings   error

** BUILD SUCCEEDED **

 -> DDSocial (1.2.7)
    - ERROR | [DDSocial/Tencent, DDSocial/Sina, DDSocial/Twitter, and more...] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [DDSocial/Google] xcodebuild:  /Users/lilingang/Desktop/DDProject/DDSocial/DDSocial/Google/DDGoogleHandler.m:11:9: fatal error: 'Google/SignIn.h' file not found
    - NOTE  | [iOS] [DDSocial/Tencent] xcodebuild:  ld: warning: ignoring file /Users/lilingang/Desktop/DDProject/DDSocial/DDSocial/Tencent/TencentSDK/TencentOpenAPI.framework/TencentOpenAPI, missing required architecture i386 in file /Users/lilingang/Desktop/DDProject/DDSocial/DDSocial/Tencent/TencentSDK/TencentOpenAPI.framework/TencentOpenAPI (3 slices)
    - NOTE  | [iOS] [DDSocial/Tencent] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [iOS] [DDSocial/Sina] xcodebuild:  /Users/lilingang/Desktop/DDProject/DDSocial/DDSocial/Sina/DDSinaHandler.m:10:9: fatal error: 'WeiboSDK/WeiboSDK.h' file not found
    - NOTE  | [iOS] [DDSocial/Twitter] xcodebuild:  /Users/lilingang/Desktop/DDProject/DDSocial/DDSocial/Twitter/DDTwitterHandler.m:11:9: fatal error: 'Fabric/Fabric.h' file not found
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/38PSIBUE77T2M/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
    - NOTE  | [DDSocial/MiLiao] xcodebuild:  note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will be degraded due to incomplete debug information.
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/38PSIBUE77T2M/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/38PSIBUE77T2M/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/38PSIBUE77T2M/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/38PSIBUE77T2M/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/38PSIBUE77T2M/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/3MPDGD35Y2LN7/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/3MPDGD35Y2LN7/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/3MPDGD35Y2LN7/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/3MPDGD35Y2LN7/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/3MPDGD35Y2LN7/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/JJ5A32AO9U80/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/JJ5A32AO9U80/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/JJ5A32AO9U80/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/JJ5A32AO9U80/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/JJ5A32AO9U80/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/JJ5A32AO9U80/CoreGraphics-N94D31PLFESQ.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/1FO8E5A4Y2QCW/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/1FO8E5A4Y2QCW/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/1FO8E5A4Y2QCW/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/1FO8E5A4Y2QCW/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
    - NOTE  | [iOS] [DDSocial/MiLiao] xcodebuild:  warning: /var/folders/zj/nxr55l596jn0v9yw97d2j1rw0000gn/C/org.llvm.clang.zhaozilong/ModuleCache/1FO8E5A4Y2QCW/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory

Pods workspace available at `/var/folders/d6/mzjfh7vd00n2pfwy5vlr5vnw0000gn/T/CocoaPods/Lint/App.xcworkspace` for inspection.

[!] DDSocial did not pass validation, due to 1 error.

/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/lib/lint.rb:75:in `block in run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/lib/lint.rb:47:in `each'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/lib/lint.rb:47:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Users/lilingang/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/Users/lilingang/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `load'
/Users/lilingang/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `<main>'

**Comment by 393385724** [comment]
@neonichu new issue
