### ISSUE TITLE
warning about i386 x86_64 after pod lib lint

### ISSUE THREAD

**Issue by AngryBaby** [CocoaPods/CocoaPods#5921]
# Report

## What did you do?
pod lib lint

## What did you expect to happen?
no warning after pod lib lint

## What happened instead?

- NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/CMBWebKeyboard.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/CmbBase64.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/Common.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/Utility.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/CMBPasswordEncrypt.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/NSData+Encrypt.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/NSString+Additions.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/NSString+Url.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/UrlParser.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/IKeyboardView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/KeyboardNumberButtons.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/PKeyboardNumbersView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/SKeyboardNumbersView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/SKeyboardView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/SKPressedView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/i386/cmbkeyboard_vers.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (i386) /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a(arclite.o) unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/CMBWebKeyboard.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/CmbBase64.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/Common.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/Utility.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/CMBPasswordEncrypt.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/NSData+Encrypt.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/NSString+Additions.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/NSString+Url.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/UrlParser.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/IKeyboardView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/KeyboardNumberButtons.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/PKeyboardNumbersView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/SKeyboardNumbersView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/SKeyboardView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/SKPressedView.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Users/cmbsec/Documents/Project/SKeyboardTest/DerivedData/SKeyboardTest/Build/Intermediates/SKeyboardTest.build/Debug-iphonesimulator/cmbkeyboard.build/Objects-normal/x86_64/cmbkeyboard_vers.o unable to open object file: No such file or directory
    - NOTE  | [iOS] xcodebuild:  warning: (x86_64) /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a(arclite.o) unable to open object file: No such file or directory

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : FHSpecs - http://ham@192.168.1.174:8082/r/FHSpecs.git @ a079962e3c1feef479e2a8bdeaacc34465074fa6
               master - https://github.com/CocoaPods/Specs.git @ 11fb6d1f5f475c31abc098eff057d22afc388b28
               O2Specs - https://git.coding.net/angrybaby/O2Specs.git @ 58670dc99a8eea466ff9ffb805607a1a58805ee4
               O2View - https://git.coding.net/angrybaby/O2View.git @ 8591832dd0edbf3a69f73ab1b6a3512f3adf36f1
               podtest - https://git.coding.net/angrybaby/podtest.git @ 639213937ef82420835c0fc29c40c3346454ef5f
               podTestLibrary - https://git.coding.net/angrybaby/podTestLibrary.git @ f909cb49044d51de1c41e7c608e2d9097ae07294
               YLPod - https://git.coding.net/angrybaby/YLPod.git @ c3e2a43d29cfe87e9d68634ce238f011944c42ee
               YLPodTest - https://git.coding.net/angrybaby/YLPodTest.git @ 6e42e24a95911e185e45b8608b0191850e6b2ab2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

##Podspec
Pod::Spec.new do |s|
  s.name         = "FHOpenShare"
  s.version      = "0.1.6"
  s.summary      = "封装了第三方的SDK"
  s.description  = <<-DESC
                    ...
                    ...
                   DESC
  s.homepage     = "https://coding.net/u/angrybaby/p/FHOpenShare"
  s.license      = "MIT"
  s.author             = { "HamYu" => "1669387345@qq.com" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://git.coding.net/angrybaby/FHOpenShare.git", :tag => "0.1.6" }
  s.source_files  = "Pod/Classes/**/*.{h,m}"
  s.resource     = "Pod/Assets/FHOpenShare.bundle"
  s.vendored_library = "Pod/Classes/SDKExport/libWeChatSDK.a"
  s.vendored_frameworks = 'Pod/Frameworks/cmbkeyboard.framework'
  s.frameworks = "UIKit", "Foundation", "SystemConfiguration", "CoreTelephony"
  s.libraries = "z", "sqlite3.0", "c++"
end

**Comment by neonichu** [comment]
Seems to be a similar issue as CocoaPods/cocoapods-packager#101, you might need to rebuild your vendored framework with `GCC_GENERATE_DEBUGGING_SYMBOLS` disabled to get rid of these warnings.

In any case, this is related to how that framework was build and how Xcode treats it, not to CocoaPods, so I'll be closing this.

**Comment by AngryBaby** [comment]
@neonichu thanks! 
after i update cocoapods version to >= 1.0.0,i always get new error when the lasted be fixed.T T

now i try to fix error is about "refrence to  is ambiguous"

XCode8 and cocoapods make error one by one hahahahahaha_____

**Comment by AngryBaby** [comment]
@neonichu i try fix error about "refrence to is ambiguous" in order to the project build success,
but,it report other error 

ld: warning: directory not found for option '-F/Users/yuham/Documents/IOS/fonehui_ios/Fenghui/WXExtensions'
ld: warning: directory not found for option '-F/Users/yuham/Documents/IOS/fonehui_ios/Fenghui/WXFrameworks'
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/AFNetworking.framework/AFNetworking) for architecture armv7
 
AFNetworking v3.x Minimum iOS Target is 7.0

should i add new issue? or

**Comment by AngryBaby** [comment]
@neonichu i fix it ^ ^
my project language is oc ,i remove  use_frameworks! podfile, it's work
