### ISSUE TITLE
Can Import header in swift using use_frameworks!

### ISSUE THREAD

**Issue by haseebOptini** [CocoaPods/CocoaPods#5923]
# Report
I published my pod named PredictIO its version 3.0.1 is available i works fine with the Objective C but in case of Swift when i use the  'use_frameworks!' in pod file the header files are not imported in my swift project.
I am using the Xcode 7.3.1 and cocoapod version 1.0.1

## What did you do?
I install multiple pods like AFNetworking, KVTimer, MBProgress all of the pods are imported to my project after using use_frameworks! 

## What did you expect to happen?
PredictIO header file must be able to import in project.

## What happened instead?
Unable to import PredictIO header file in swift project.

## CocoaPods Environment

CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : BlinkingLabel2Specs - https://github.com/ahaseebchina01/BlinkingLabel2Specs.git @ e0acd391b00a2bbe2e843e8a5efd28688dd2513d
               BlinkingLabelSpec - https://github.com/ahaseebchina01/BlinkingLabelSpec.git @ b6b6af2ac2548214c7274d333e8221c60b9b4bb0
               DummyBlinkingLabelTestSpec - https://github.com/ahaseebchina01/DummyBlinkingLabelTestSpec @ 162cfcae28dbeff4a591101b4879e0a3f68fa2bb
               DummyPodAHaseebChina01Spec - https://github.com/ahaseebchina01/DummyPodSpec @ 90e481f2e428f20bc127c0fc35913ec7fd63b593
               DummyPodTestingSpec - https://github.com/ahaseebchina01/DummyPodTestingSpec.git @ d2d42047547d93c0e1b43dceb5df055e3642b06e
               master - https://github.com/CocoaPods/Specs.git @ 7512c06b9210bba0978b253b9564144b7459fde5
               ParktagPod2Spec - https://github.com/ahaseebchina01/ParktagPod2Spec.git @ cac1aa6a318f9a24fd92d8d1d5ee44845d317248
               ParktagPodSpec - https://github.com/ahaseebchina01/ParktagPodSpec.git @ 380a2b2639f9c46d97e3bcf38eaaa68514435dc0
               predict-ioSpec - https://github.com/predict-io/predict-ioSpec.git @ c5b8c58577f8278c7e6cf42516cde0a7df6901a8
               predict.ioSpec - https://github.com/predict-io/predict.ioSpec @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               PredictIO - https://github.com/parktag/PredictIOSpec @ 100b4e997cdb672683c6c50ce268ea28d503a6a8
               PredictIO-iOSSpec - https://github.com/predict-io/PredictIO-iOSSpec.git @ cf806fc47bc274f1b0a99c48c117d7fd07ada2b4
               PredictIO3.0 - https://github.com/parktag/PredictIOSpec @ bac7487cf97a2ca4571331388da165673d8ffd7b
               PredictIOPodSpec - https://github.com/ahaseebchina01/PredictIOPodSpec @ 70bda76b31296ebcf9dcf88f0b673f4e2bf87a91
               PredictIOPodSpecUpdated - https://github.com/parktag/PredictIOSpec @ 97bc880d741c075d24a8a89b8f081569d6973d95
               PredictIOSpec - https://github.com/ahaseebchina01/PredictIOSpec.git @ 0c69f338a0d55eef97fb9147cdad7608f1976d90
               PredictIOSpec2 - https://github.com/predict-io/PredictIOSpec.git @ 5c153b9b6f1cf8d52113926f3187650e641dd45a
               PredictIOSpec3 - https://github.com/predict-io/PredictIOSpec.git @ 160a898fcd0e9e4451bf5adc6bfd73470e1d8baf
               PredictIOSpec4 - https://github.com/predict-io/PredictIOSpec.git @ a261883ab355a76cf8cb8cf05a5c3781bb2116a0
               predictIOSpec5 - https://github.com/predict-io/PredictIOSpec @ 3fd2fc954abf5cb9eb5a6790a84914e1457ad33a
               PredictIOSpecUpdated - https://github.com/parktag/PredictIOSpec @ b7712a7ffe7254e3630ec1d8d713f742efc13903
               PredictIOTestPodSpec - https://github.com/predict-io/PredictIOTestPodSpec @ e846eac2d026d2cc00a0cc7c711e9b9cf8ab4ff9
               RWPodSpecs - https://github.com/ahaseebchina01/RWPodSpecs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               RWPodSpecs2 - https://github.com/ahaseebchina01/RWPodSpecs2.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               TestMultiRepoPodPredictIOSpec - https://github.com/ahaseebchina01/TestMultiRepoPodPredictIOSpec @ 07ab5ad58dc82fc319d79567447d974b54f62734
               TestParktagPods2Spec - https://github.com/ahaseebchina01/TestParktagPods2Spec.git @ ba3089f88e1c4ee9c1b5b98f336d183f15387a63
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.0
cocoapods-docs        : 0.2.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
 use_frameworks!

 platform :ios, '7.0'

target 'PodQASwift731' do
  
  
  pod 'PredictIO'
  pod 'KVTimer'
  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD'
end
```

**Comment by neonichu** [comment]
Could you elaborate more on what exactly isn't working? If you are trying to import into the bridging header, make sure you use module imports (`@import`), the alternatives do not work when using frameworks integration.

**Comment by haseebOptini** [comment]
I am trying to import without bridging header in my project in case of bridging header i can import my header file as expected.

**Comment by neonichu** [comment]
Please share a sample project that demonstrates the issue, then.

**Comment by haseebOptini** [comment]
[Uploading PodQASwift731.zip…]()

**Comment by haseebOptini** [comment]
[PodQASwift731.zip](https://github.com/CocoaPods/CocoaPods/files/484639/PodQASwift731.zip)

**Comment by haseebOptini** [comment]
Please find the project in Zip fie

**Comment by haseebOptini** [comment]
Please find the project in Zip file.

**Comment by benasher44** [comment]
It looks like there's no module map generated for PredictIO's pod, which means you won't be able to import it without creating a bridging header. This is an issue that should be filed in PredictIO's github issue tracker, since they'll need to update their podspec to support this.

**Comment by haseebOptini** [comment]
Can you please help me out how to generate Module map for PredictIO.

**Comment by benasher44** [comment]
PredictIO should update their podspec, and then one will be properly generated for you. There are a few tutorials out there about creating custom module maps for CommonCrypto, and the instructions are roughly the same for doing it with this pod.

**Comment by haseebOptini** [comment]
Actually PredictIO is my pod i need to do changes on podspec can you help me for the changes required for automatic module generation you can find PredictIO pod spec on following link. https://github.com/predict-io/PredictIO-iOS/blob/master/PredictIO.podspec

**Comment by benasher44** [comment]
Here's an example of another pod that has a vendored static lib and a module map https://github.com/comScore/ComScore-iOS-SDK

**Comment by ahaseebchina01** [comment]
i installed 'ComScore' CocoaPod to my project but unable to import 'ComScore' to my app delegate can you please provide any tutorial from where i can add the module generation to my CocoaPod.

**Comment by haseebOptini** [comment]
i installed 'ComScore' CocoaPod to my project but unable to import 'ComScore' to my app delegate can you please provide any tutorial from where i can add the module generation to my Pod.

**Comment by benasher44** [comment]
Their podspec looks mostly right to me. I'm not sure how I can provide more info given that there's a CocoaPods guides on how we support module maps, there's the module map documentation online, and now I've provided an example that you can copy and tweak until it works for you. This is exactly what I would do
