### ISSUE TITLE
pod lib create in 1.1.0 rc2 compatibility with Swift 3

### ISSUE THREAD

**Issue by RedBrett7** [CocoaPods/CocoaPods#5930]
🌈
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [✔︎ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run pod lib create 'Project' with and without .swift-version file

## What did you expect to happen?

Create a new Xcode project using Swift 3.0 and open its workspace 

## What happened instead?

Created a new Xcode project in Swift 2.3 and couldn't create the workspace.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bitbucket-red7mobile-cocoa-pods - https://bitbucket.org/red7mobile/cocoa-pods.git @ 87a90d9b6d1011e96fac1d88e704f25674b12e83
               cocoa-pods - git@bitbucket.org:red7mobile/cocoa-pods.git @ 87a90d9b6d1011e96fac1d88e704f25674b12e83
               jumio-distribution - http://mobile-sdk.jumio.com/distribution.git @ 22834a79540c0575da8cb6ac7a3ceb17e57cc8c5
               master - https://github.com/CocoaPods/Specs.git @ d15efea3e776c92b688575a20ca411ffd2ff2831
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Cloning `https://github.com/CocoaPods/pod-template.git` into `Project`.
Configuring Project template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and double click links to open in a browser. )

What language do you want to use?? [ Swift / ObjC ]
 > Swift

Would you like to include a demo application with your library? [ Yes / No ]
 > Yes

Which testing frameworks will you use? [ Quick / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > No

Running pod install on your new library.

[!] No `Podfile' found in the project directory.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'Project/Example/Project.xcworkspace'
The file /Users/me/Projects/Pods/Projects/Project/Example/Project.xcworkspace does not exist.

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

**Comment by orta** [comment]
We've got a big update for that coming once 1.1.0 is out, for now you're welcome to send a PR to cocoapods/pod-template to get the current version up and running  👍
