### ISSUE TITLE
Pod Headers fails to make the shortcuts

### ISSUE THREAD

**Issue by Srinivas-Tringapps** [CocoaPods/CocoaPods#5931]
Hi,

In our project, we have added pods newly and we have sent our code in zipped format to client. When they unzip the files files inside the "Headers" folder turns in to files instead of shortcuts, so the files has the below text only. 
`../../../Mixpanel/Mixpanel/Mixpanel.h` 
(Mixpanel SDK) 

So it's makes trouble with errors whenever we compile it. 

What is the reason for it? how to fix it?(other than installing the pod files again)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by Srinivas-Tringapps** [comment]
:(
