### ISSUE TITLE
Allow configuration for --repo-update

### ISSUE THREAD

**Issue by maschall** [CocoaPods/CocoaPods#5932]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I understand and like that `pod install` does not update the repo's, but I'd like to suggest the idea of being able to add a configuration to re-enable this, if it makes sense.

**Comment by benasher44** [comment]
You can already pass `--repo-update` to `pod install`

**Comment by benasher44** [comment]
Unless your asking something else?

**Comment by BluMist** [comment]
+1 to the request
would prefer to have a flag/configuration in the podfile instead of the command line options

**Comment by maschall** [comment]
I was thinking for the lines of either a global config and/or project config setting, similar to gitconfig.

This could be taken further to provide default flags and settings for other commands.

**Comment by neonichu** [comment]
We should really not do this, as we have specifically changed the default to reduce the stress on GitHub's servers.

**Comment by benasher44** [comment]
I agree. It's also trivial to add a Makefile or other build script to your project that always runs `pod install` with a default set of arguments.
