### ISSUE TITLE
xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist

### ISSUE THREAD

**Issue by HappyiOSYuan** [CocoaPods/CocoaPods#5935]
Pod::Spec.new do |s|

s.name = 'JLYKit'
s.version = '0.2.6'
s.license = 'MIT'
s.summary = 'A simple framework on iOS.'
s.homepage = 'https://github.com/HappyiOSYuan/JLYKit'
s.authors = { '宁袁' => '1294752518@qq.com' }
s.source = { :git => 'https://github.com/HappyiOSYuan/JLYKit.git', :tag => s.version.to_s }
s.requires_arc = true
s.platform = :ios
s.ios.deployment_target = "8.0"
s.source_files = 'JLYKit/Classes/**/*'
s.public_header_files = 'JLYKit/Classes/**/*.h'
s.frameworks = 'UIKit','ImageIO','QuartzCore','Security','CoreGraphics','Foundation','SystemConfiguration'

s.dependency 'AFNetworking'
s.dependency 'MLInputDodger', '~>1.4.0'
s.dependency 'Reachability'
s.dependency 'SDAutoLayout'
s.dependency 'SDWebImage'
s.dependency 'Masonry'
s.dependency 'DGActivityIndicatorView'
s.dependency 'ISHPermissionKit'
s.dependency 'SVProgressHUD'
s.dependency 'MJRefresh'
s.dependency 'JDStatusBarNotification'

end

what's wrong?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by HappyiOSYuan** [comment]
Thanks
