### ISSUE TITLE
 ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code，NOTE | [iOS] xcodebuild: xcodebuild: error: 'App.xcworkspace' does not exist

### ISSUE THREAD

**Issue by kingly09** [CocoaPods/CocoaPods#5938]
An error occurred while executing the following command：

`＃pod trunk push LBinBarButtonItem.podspec --verbose` 

**Error log is as follows:**

`WARNING: Failed to load plugin at path: "/Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz): no suitable image found.  Did find:
	/Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz: mmap() error 1 at address=0x112FEA000, size=0x00017000 segment=__TEXT in Segment::map() mapping /Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz, NSDebugDescription=dlopen_preflight(/Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz): no suitable image found.  Did find:
	/Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz: mmap() error 1 at address=0x112FEA000, size=0x00017000 segment=__TEXT in Segment::map() mapping /Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin/Contents/MacOS/Alcatraz, NSBundlePath=/Users/kingly/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin, NSLocalizedDescription=The bundle “Alcatraz” couldn’t be loaded because it is damaged or missing necessary resources.}`

xcodebuild: error: 'App.xcworkspace' does not exist.
 -> LBinBarButtonItem (0.0.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

[!] The spec did not pass validation, due to 1 error.

**CocoaPods Environment**
- CocoaPods:1.1.0.rc.2
- Ruby: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
- RubyGems : 2.5.1
- Host : Mac OS X 10.11.6 (15G1004)
- Xcode : 8.0 (8A218a)
- Git : git version 2.8.4 (Apple Git-73)

Repeated testing are reported this wrong, does anyone encountered this question, ask how to fix him, very grateful! 🙏

**Comment by neonichu** [comment]
Could you please retry after setting the FORK_XCODE_WRITING environment variable to true?

**Comment by kingly09** [comment]
@neonichu  
Yes, I try, thank you

**Comment by daveverwer** [comment]
I had this same issue and setting that environment variable fixed it.

Xcode 8 final on 10.11.6, latest cocoapods stable gem

**Comment by k06a** [comment]
I had this same issue and setting that environment variable fixed it.

Xcode 8 final on 10.12, CocoaPods 1.1.0rc2

**Comment by wenyc** [comment]
I had this same issue,but i don`t know how to set the FORK_XCODE_WRITING environment variable,Who can tells me? Thank you in advance.

**Comment by wenyc** [comment]
@neonichu @daveverwer @k06a

**Comment by wenyc** [comment]
@neonichu @k06a @daveverwer 
I had this same issue,but i don`t know how to set the FORK_XCODE_WRITING environment variable,Who can tells me? Thank you in advance.

**Comment by k06a** [comment]
@weny, type in terminal:
`export FORK_XCODE_WRITING=true`

**Comment by wenyc** [comment]
Thank you very much ! @k06a

**Comment by benasher44** [comment]
This is fixed as part of #6048. Thanks for filing!

**Comment by RiberWang** [comment]
@neonichu @kingly09 
I had this same issue,but i don't know how to set the FORK_XCODE_WRITING environment variable,Who can help me? Thank you in advance.

**Comment by benasher44** [comment]
@RiberWang if you upgrade to at least CocoaPods 1.2.0, this issue should be fixed (latest is 1.2.0). If not, please file a new issue and fill out the issue template. We'd be happy to help you out!
