### ISSUE TITLE
`Copy Pods Resources` Build Phase lacks environment variable `PODS_ROOT`

### ISSUE THREAD

**Issue by cgrushko** [CocoaPods/CocoaPods#594]
Manual solution is to access a project's Build Phases panel, and changing

```
"${SRCROOT}/Pods/Pods-resources.sh"
```

into

```
PODS_ROOT=Pods "${SRCROOT}/Pods/Pods-resources.sh"
```

Otherwise, `Pods-resources.sh` fails to copy files.

**Comment by hissain** [comment]
I am getting below build error for an iOS project which was buildable previously without any source code modification.
```

rsync: failed to open files-from file Repo/Pods/resources-to-copy-Project.txt: Permission denied
Unexpected Failure
```

Similar issue has been raised but solution does not work for my case. In my project I found no script like `${SRCROOT}/Pods/Pods-resources.sh`

**How to resolve it?** My Mac is offline and I cannot run pod install anymore. Just need to build previously buildable project.

**Comment by amorde** [comment]
@hissain Please don't comment on old issues (this is almost *8 years* old). CocoaPods changes and evolves over time, and it's difficult for us to follow when old issues get commented on.

If you've found a bug in CocoaPods, please submit a new issue with a sample project that reproduces it. Thanks!
