### ISSUE TITLE
Installation fails when using different subspecs of same pod in app and extension

### ISSUE THREAD

**Issue by b-ray** [CocoaPods/CocoaPods#5940]
🌈
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I have a Xcode project including an iOS-App target and a today extension.
Both the app target and the today extension have one pod dependency (to the same pod), however, they are using **different subspecs**.

## What did you do?
 
run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Using version 1.0.1 everything is installed correctly.
Using version 1.1.0.rc.2 pod installation fails with the following error message:

```
Analyzing dependencies
Downloading dependencies
Using AFNetworking (3.1.0)
[!] The 'Pods-CPExtSubspecs' target has frameworks with conflicting names: afnetworking.
```

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.5.3
Ruby lib dir : /Users/stefanpuehringer/.rvm/rubies/ruby-2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 36281bb604546e47f00159d988fae22f0ddbd5a5
               private ...
```

### Installation Source

```
Executable Path: /Users/stefanpuehringer/.rvm/gems/ruby-2.2.5@cocoapods-1-1-0/bin/pod
```

### Plugins

```
cocoapods-ack_filter  : 0.2.0
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'CPExtSubspecs' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CPExtSubspecs
  pod 'AFNetworking', :subspecs => ['Serialization']
end

target 'TodayExtension' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodayExtension
  pod 'AFNetworking'
end
```

## Project that demonstrates the issue

Demo Project can be found there:
https://github.com/b-ray/CPExtSubspec

___

I have tried to get to the bottom of this problem and from what I understand, the problem seems to be around embedding extension frameworks in the host target (the `copy_embedded_target_pod_targets_to_host` method in `analyzer.rb`), where CocoaPods seems to only check for pods with the same subspecs.
If this is indeed an issue, I could try to fix this problem over the weekend? Any help would be very much appreciated :)

And thanks again for this amazing tool!!

**Comment by neonichu** [comment]
Thanks for the detailed issue, you can find some more info about it in #5643 especially [this comment](https://github.com/CocoaPods/CocoaPods/issues/5643#issuecomment-233727907) — the gist is that even though this succeeded with previous versions of CP, the AFNetworking Pod defined for the extension was actually never embedded into the application bundle.

**Comment by arifken** [comment]
@neonichu Just wondering, do you think it would work to have the product name for the subspec be different? e.g. in this example you'd have AFNetworking.framework and AFNetworking-Serialization.framework. Since the frameworks will not be linked against the same binary (AFNetworking linked to the main app, and AFNetworking-Serialization linked to the today extension?)
