### ISSUE TITLE
/Release-iphonesimulator/App.build/Objects-normal/x86_64/App ld: framework not found 

### ISSUE THREAD

**Issue by madhurawat** [CocoaPods/CocoaPods#5944]
i am using xcode 8 and  created a dynamic framework and  adding a podspec to import it to sample applications.

pod spec validation gives me a error 

pod version 1.1.0.rc.2

pod spec snipped:

s.source_files = '*/XXXX.framework/Headers/*.h'
 s.public_header_files = '*/XXXX.framework/Headers/*.h'
 s.vendored_frameworks  = "XXXX.framework/XXXX"
 s.xcconfig            = {
   'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}"'
 }

Error on pod spec lint --verbose:
/Library/Developer/Xcode/DerivedData/App-cfzzymafuexbmpgzcbnfbbetoynd/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App
ld: framework not found XXXX
/Xcode/DerivedData/App-cfzzymafuexbmpgzcbnfbbetoynd/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App
ld: framework not found XXXX

**Comment by DanToml** [comment]
Please file a new issue completing the Issue Template including the output of pod env
