### ISSUE TITLE
Add "pod update" and "pod install" targets to the Pods project

### ISSUE THREAD

**Issue by gary-wade-panasonic-aero** [CocoaPods/CocoaPods#5945]
Feature Request:
It would be helpful to add build targets to the Pods project that can be used to perform an update or install without needing to go to a command line.  With these, doing a build on the particular target will perform the command.  An example PBXLegacyTarget section within the Xcode project with these follows:

```
/* Begin PBXLegacyTarget section */
		788C21271D94B2E70055CF78 /* pod update */ = {
			isa = PBXLegacyTarget;
			buildArgumentsString = update;
			buildConfigurationList = 788C212A1D94B2E70055CF78 /* Build configuration list for PBXLegacyTarget "pod update" */;
			buildPhases = (
			);
			buildToolPath = /usr/local/bin/pod;
			buildWorkingDirectory = "$(SRCROOT)/..";
			dependencies = (
			);
			name = "pod update";
			passBuildSettingsInEnvironment = 1;
			productName = "pod update";
		};
		788C212B1D94B30B0055CF78 /* pod install */ = {
			isa = PBXLegacyTarget;
			buildArgumentsString = install;
			buildConfigurationList = 788C212C1D94B30C0055CF78 /* Build configuration list for PBXLegacyTarget "pod install" */;
			buildPhases = (
			);
			buildToolPath = /usr/local/bin/pod;
			buildWorkingDirectory = "$(SRCROOT)/..";
			dependencies = (
			);
			name = "pod install";
			passBuildSettingsInEnvironment = 1;
			productName = "pod install";
		};
/* End PBXLegacyTarget section */

```

**Comment by orta** [comment]
This is an interesting idea, I'm half-half on it. 

Leaning towards no, I don't really think `pod install` or `update` are actions that's used often enough to warrant being unhidden in the scheme and added to every user's dropdown in Xcode:

<img width="467" alt="screen shot 2016-09-24 at 08 48 09" src="https://cloud.githubusercontent.com/assets/49038/18806958/a715024e-8233-11e6-9035-41c75cb43b2c.png">

But if they're hidden, any user wanting to actually use them would have to unhide it every time there was a `pod install` which kinda negates the point.

**Comment by dnkoutso** [comment]
Isnt this something that can be accomplished very easily with a `post_install` hook?

**Comment by gary-wade-panasonic-aero** [comment]
I try to stay out of the Terminal as much as possible, and if I can redo a set of pods dependencies by choosing Build after selecting an Xcode target, that makes my life so much easier.

As for the post_install suggestion, I'd be happy to add that, but I really just want to spend my time figuring out how to develop software for Apple's ecosystems rather than learning another tool.  Feel free to post the info here, and I'd suggest it be added in a commented-out form to any default pod files in the future for those who might want it..

**Comment by benasher44** [comment]
You could always add a build phase that runs `pod install`. Would that work?

**Comment by gary-wade-panasonic-aero** [comment]
The pod update or pod install wipes out the targets

**Comment by gary-wade-panasonic-aero** [comment]
Sorry, I was thinking of something else about the build phase suggestion, but that would make it pretty much automatic, but a user would almost always want this to be manual.  Of course, it may be possible with Xcode 8 and extensions to make this integrated in a really great way with appropriate warnings and the like when new pods are available, but the ability to add just the targets on the generated Pods project would be enough.

**Comment by benasher44** [comment]
Right. Aside from a build phase, I recommend checking out the CocoaPods Mac app, if you want to avoid the cli

**Comment by orta** [comment]
Yeah, I looked at making an extension inside the Mac app, but apple doesn't have a big enough API surface to even run a pod install realistically. Alright, I'm calling this as a no thanks. If someone wants to make the `post_install` hook, you're welcome to comment it below 💯
