### ISSUE TITLE
Problem installing CocoaPods 1.1.0.rc.2

### ISSUE THREAD

**Issue by Adarkas2302** [CocoaPods/CocoaPods#5957]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
```
localhost:d.b.g. Melder DBG_MacAB$ mkdir -p §HOME/Software/ruby
localhost:d.b.g. Melder DBG_MacAB$ export GEM_HOME=§HOME/Software/ruby
localhost:d.b.g. Melder DBG_MacAB$ gem install cocoapods --pre
Fetching: cocoapods-1.1.0.rc.2.gem (100%)
Successfully installed cocoapods-1.1.0.rc.2
Parsing documentation for cocoapods-1.1.0.rc.2
Installing ri documentation for cocoapods-1.1.0.rc.2
1 gem installed
localhost:d.b.g. Melder DBG_MacAB$ export PATH=$PATH:$HOME/Software/ruby/bin
```
## What did you expect to happen?

cocoarpods Version 1.1.0 installed

## What happened instead?
```
localhost:d.b.g. Melder DBG_MacAB$ pod --version
1.0.1
```
## CocoaPods Environment
```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bfe37dea873630a4c6be6e71567f7a405a7853e5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.1.0'
use_frameworks!

target 'd.b.g. Melder' do

#pod 'AsyncSwift'
pod 'PhotoSlider'
pod 'SwiftyRSA', '3.0.0'
pod 'SwiftyJSON'
pod 'ZTDropDownTextField'
#pod 'Kingfisher', '~> 3.0'
```
What am i doing wrong?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

However, you can use `pod _1.1.0.rc.2_ --version` to use an exact version from your ruby gems library.

**Comment by Adarkas2302** [comment]
Oh, ok. Thanks for the quick reply.
