### ISSUE TITLE
unable to add-owner pod 

### ISSUE THREAD

**Issue by Maheepk** [CocoaPods/CocoaPods#5958]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by Maheepk** [comment]
pod trunk add-owner XXXXXX abc@xxxxxxx.com

**Comment by orta** [comment]
Did you verify that you are logged in, and own the pod in question?

**Comment by Maheepk** [comment]
yes, i do.

**Comment by orta** [comment]
Then what error messages are you seeing? please put the full log in - remember you're a programmer, give us a useful bug report as I'm helping you out in my spare time.

**Comment by Maheepk** [comment]
Does this bug related to bellow as well?

None of your spec sources contain a spec satisfying the dependency: `Nudgespot (~> 2.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by Maheepk** [comment]
pod trunk add-owner podName email
[!] You are not allowed to add owners to this pod.

**Comment by Maheepk** [comment]
Hi Orta,

Can you please check Nudgespot pod if its not deprecated, I deprecated
once, then i update it with new version.

As for some customers its showing this error message.

[!] Unable to satisfy the following requirements:


- `Nudgespot (~> 2.5)` required by `Podfile`

- `Nudgespot (~> 2.5)` required by `Podfile`


None of your spec sources contain a spec satisfying the dependency:
`Nudgespot (~> 2.5)`.


You have either:

 * out-of-date source repos which you can update with `pod repo update`.

 * mistyped the name or version.

 * not added the source repo that hosts the Podspec to your Podfile.


Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod
install` by default.

thanks,

**Comment by orta** [comment]
2.5 is the latest version:  http://cocoapods.org/pods/Nudgespot

I feel like you're not reading any of the error messages that CocoaPods is outputting:

> You have either:

>  * out-of-date source repos which you can update with `pod repo update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.

> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod
install` by default.

and re ownership

> [!] No owner found with the specified email address.

Can you please re-read all of your messages. Verify that you are logged in as who you expect to be. That does not look like you're logged in.

**Comment by Maheepk** [comment]
@orta 

there are 2 separate errors i am getting:-

1. when i try to login with maheep@boomtrian.com and add owner with this email. i can't able to do that.

2. some customer is not able to download Nudgespot correctly they are getting this error:-

[!] Unable to satisfy the following requirements:


- `Nudgespot (~> 2.5)` required by `Podfile`

- `Nudgespot (~> 2.5)` required by `Podfile`


None of your spec sources contain a spec satisfying the dependency:
`Nudgespot (~> 2.5)`.


You have either:

 * out-of-date source repos which you can update with `pod repo update`.

 * mistyped the name or version.

 * not added the source repo that hosts the Podspec to your Podfile.


Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod
install` by default.

and yes i tried to login with maheep@boomtrain.com and got link as well but as long as i tried to add owner as Nudgespot it doesn't allow me.

gave this error message:-

Last login: Tue Sep 27 11:37:07 on console
Nudgespots-MacBook-Pro:~ nudgespot$ pod trunk add-owner Nudgespot maheep@boomtrain.com
[!] You are not allowed to add owners to this pod.
Nudgespots-MacBook-Pro:~ nudgespot$ 

thanks,

**Comment by neonichu** [comment]
You can only add new owners if you're already an owner, so adding yourself cannot work.

**Comment by Maheepk** [comment]
you are right but i am owner at maheep@nudgespot.com and want to add new owner maheep@boomtrain.com.

**Comment by orta** [comment]
Does `pod trunk me` tell you that you are logged in as that email?

**Comment by Maheepk** [comment]
Nudgespots-MacBook-Pro:~ nudgespot$ pod trunk me
  - Name:     Maheep Kaushal
  - Email:    maheep@boomtrain.com
  - Since:    September 26th, 16:57
  - Pods:     None
  - Sessions:
    - September 26th, 16:57 - February 2nd, 2017 11:54. IP: 106.51.65.110
    Description: Macbook Pro
    - September 27th, 11:55 - February 3rd, 2017 13:56. IP: 106.51.65.110
    Description: Macbook Pro

**Comment by Maheepk** [comment]
@orta  it solved when i logged again from my account and logout from where i need to make email address. thanks,
