### ISSUE TITLE
Pod spec lint gives error i386,x86_64 framework not found

### ISSUE THREAD

**Issue by madhurawat** [CocoaPods/CocoaPods#5960]
# Report

## What did you do?

 pod spec lint --verbose

## What did you expect to happen?

Should not have  lint errors and pod install to include dynamic framework as embedded framework in application (Install all pod dependencies) .

## What happened instead?

/Library/Developer/Xcode/DerivedData/App-cfzzymafuexbmpgzcbnfbbetoynd/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App ld: framework not found XXXX /Xcode/DerivedData/App-cfzzymafuexbmpgzcbnfbbetoynd/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App ld: framework not found XXXX

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 446aa9b1804b38d61a38b51df61403d7ae544177
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/madhurawat/TestFramework

**Comment by neonichu** [comment]
Yes, please do provide a sample project.

**Comment by madhurawat** [comment]
Sample https://github.com/madhurawat/TestFramework

**Comment by AnD010** [comment]
I have the same problem 
```
s.source_files = "DSFramework/*.{h,m}",'DSFramework/DriveSmartFramework.framework/Headers/*.h'
s.public_header_files = 'DSFramework/DriveSmartFramework.framework/Headers/*.h'
s.framework = 'DriveSmartFramework'
```

> pod spec lint  DSFramework.podspec --allow-warnings  --use-libraries --verbose


> Ld /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386
>     cd /var/folders/lf/5hd49f8s24bd0k38_x5sgzt00000gp/T/CocoaPods/Lint
>     export IPHONEOS_DEPLOYMENT_TARGET=8.0
>     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin"
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -L/Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Products/Release-iphonesimulator -F/Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Products/Release-iphonesimulator -filelist /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -object_path_lto -Xlinker /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -framework DriveSmartFramework -framework Foundation -lPods-App -Xlinker -dependency_info -Xlinker /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App_dependency_info.dat -o /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App
> ld: framework not found DriveSmartFramework
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> Ld /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
>     cd /var/folders/lf/5hd49f8s24bd0k38_x5sgzt00000gp/T/CocoaPods/Lint
>     export IPHONEOS_DEPLOYMENT_TARGET=8.0
>     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin"
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk -L/Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Products/Release-iphonesimulator -F/Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Products/Release-iphonesimulator -filelist /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=8.0 -Xlinker -object_path_lto -Xlinker /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -ObjC -framework DriveSmartFramework -framework Foundation -lPods-App -Xlinker -dependency_info -Xlinker /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App_dependency_info.dat -o /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App
> ld: framework not found DriveSmartFramework
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ** BUILD FAILED **


> The following build commands failed:
> 	Ld /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386
> 	Ld /Users/administrador/Library/Developer/Xcode/DerivedData/App-dfgwmhjcbmyxahguzusezdpetlzb/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
> (2 failures)
>  -> DSFramework (0.1.0)
>     - WARN  | description: The description is shorter than the summary.
>     - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
>     - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> Analyzed 1 podspec.
> 
> [!] The spec did not pass validation, due to 1 error.
> 
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/spec/lint.rb:77:in `run'
> /Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'

**Comment by neonichu** [comment]
- `vendored_framework` needs to point to the framework bundle itself, not to a file inside it.
- `framework` is intended only for system frameworks, not for your own.
