### ISSUE TITLE
HELP pod install no generate .lock .xcwrokspace,print [1] 10971 trace trap pod install --verbose

### ISSUE THREAD

**Issue by stoneF** [CocoaPods/CocoaPods#5961]
OS X 10.11.6
xcode 8
cocoapods 1.1.0.beta.2
gem 2.6.6
xcodeproj 1.3.1

  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-dzx`: (``)

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A AFNetworking

Downloading dependencies

-> Installing AFNetworking (3.1.0)
  > Copying AFNetworking from
  `/Users/fengbin/Library/Caches/CocoaPods/Pods/Release/AFNetworking/3.1.0-5e0e1`
  to `Pods/AFNetworking`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `AFNetworking` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support
      Files/AFNetworking/Info.plist`
      - Generating module map file at `Pods/Target Support
      Files/AFNetworking/AFNetworking.modulemap`
      - Generating umbrella header at `Pods/Target Support
      Files/AFNetworking/AFNetworking-umbrella.h`
    - Installing target `Pods-dzx` iOS 9.0
      - Generating Info.plist file at `Pods/Target Support
      Files/Pods-dzx/Info.plist`
      - Generating module map file at `Pods/Target Support
      Files/Pods-dzx/Pods-dzx.modulemap`
      - Generating umbrella header at `Pods/Target Support
      Files/Pods-dzx/Pods-dzx-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
[1]    9970 trace trap  pod install --verbose
![181e7bc0-731f-42cc-a2ad-5b88e142df36](https://cloud.githubusercontent.com/assets/5800383/18866151/26ab0e5a-84d1-11e6-903b-a9f48ce45191.png)

**Comment by stoneF** [comment]
![181e7bc0-731f-42cc-a2ad-5b88e142df36](https://cloud.githubusercontent.com/assets/5800383/18866121/ff08f092-84d0-11e6-8103-e9b390132b9a.png)

**Comment by neonichu** [comment]
`trace trap` sounds like the process got a `SIGTRAP`, i.e. an uncaught exception. Could you please try the latest release candidate instead of beta 2?

**Comment by stoneF** [comment]
OS X 10.11.6
xcode 8
cocoapods 1.0.1
gem 2.6.6
xcodeproj 1.3.1

➜  dzx  pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of
  target `Pods-dzx`: (``)

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A AFNetworking

Downloading dependencies

-> Installing AFNetworking (3.1.0)
  > Copying AFNetworking from
  `/Users/fengbin/Library/Caches/CocoaPods/Pods/Release/AFNetworking/3.1.0-5e0e1`
  to `Pods/AFNetworking`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `AFNetworking` iOS 8.0
      - Generating Info.plist file at `Pods/Target
      Support Files/AFNetworking/Info.plist`
      - Generating module map file at `Pods/Target
      Support
      Files/AFNetworking/AFNetworking.modulemap`
      - Generating umbrella header at `Pods/Target
      Support
      Files/AFNetworking/AFNetworking-umbrella.h`
    - Installing target `Pods-dzx` iOS 9.0
      - Generating Info.plist file at `Pods/Target
      Support Files/Pods-dzx/Info.plist`
      - Generating module map file at `Pods/Target
      Support Files/Pods-dzx/Pods-dzx.modulemap`
      - Generating umbrella header at `Pods/Target
      Support Files/Pods-dzx/Pods-dzx-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to
  `Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
[1]    10971 trace trap  pod install --verbose
![75435f8f-f868-4c25-ae4c-95c3b58c4e64](https://cloud.githubusercontent.com/assets/5800383/18897530/ae52e080-855d-11e6-949e-1c921bd51aad.png)
I try to replace the cocoapods 1.0.1 version result is still the same.
Could you fix it ?

**Comment by orta** [comment]
@neonichu  means by using the pre-release of `1.1.0` - e.g.

```
gem install cocoa pods --pre
pod _1.0.0.rc.2_ install
```

**Comment by stoneF** [comment]
@neonichu @orta Hi, sudo gem uninstall cocoapods-* , uninstall all of cocoapods Plugins, then sudo gem install cocoapods -n /usr/local/bin  -v 1.0.0.rc.2 . It work for me, but other version of cocopods  result is still the same error.
![216bf981-8dc2-42fc-b4bd-3f50fc1ce19b](https://cloud.githubusercontent.com/assets/5800383/18907591/ce41820c-859e-11e6-8b35-d36fd223440b.png)

pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-dzx`: (``)

Finding Podfile changes
  - AFNetworking

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  - AFNetworking

Downloading dependencies

-> Using AFNetworking (3.1.0)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `AFNetworking` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/AFNetworking/Info.plist`
      - Generating module map file at `Pods/Target Support Files/AFNetworking/AFNetworking.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/AFNetworking/AFNetworking-umbrella.h`
    - Installing target `Pods-dzx` iOS 9.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-dzx/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-dzx/Pods-dzx.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-dzx/Pods-dzx-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-dzx` (`dzx.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from
    `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.rc.1/lib/cocoapods_plugin.rb`

Sending stats
      - AFNetworking, 3.1.0
  Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by orta** [comment]
Yep, we only support Xcode 8 in the RC releases, Xcode changes considerably every year I'm afraid in ways that breaks CocoaPods.

**Comment by stoneF** [comment]
awesome

**Comment by liuzhuoming** [comment]
I got a  new Macbook pro, installed Xcode 8.2 and cocoapod 1.1.1。 when i check out my project from gitlab ,and $pod update . i found the same wrong.I try everything but doesn‘t work , untill i install [CocoaPods-app](https://github.com/CocoaPods/CocoaPods-app/releases)

**Comment by benasher44** [comment]
Hi @liuzhuoming! Thanks for letting us know! Unfortunately, there's not enough info here for us to help debug, and this issue is quite old. If you could please file a new issue and fully fill out the issue template, we'd be happy to help. Have a great day!
