### ISSUE TITLE
When Install The Pod

### ISSUE THREAD

**Issue by khawar512** [CocoaPods/CocoaPods#5966]
Last login: Wed Sep 28 16:42:45 on ttys000
Khawars-MBP:~ khawarislam$ cd Desktop/CurrencyApp
Khawars-MBP:CurrencyApp khawarislam$ ls
CurrencyApp		CurrencyApp.xcodeproj
Khawars-MBP:CurrencyApp khawarislam$ pod init
Khawars-MBP:CurrencyApp khawarislam$ pod install

[!] Invalid `Podfile` file: syntax error, unexpected ',', expecting keyword_end
    'CurrencyRequest' , '-> 0.1'
                       ^.

 #  from /Users/khawarislam/Desktop/CurrencyApp/Podfile:6
 #  -------------------------------------------
 #     
 >      'CurrencyRequest' , '-> 0.1'
 #    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 #  -------------------------------------------
Khawars-MBP:CurrencyApp khawarislam$ pod install

[!] Invalid `Podfile` file: syntax error, unexpected ',', expecting keyword_end
    'CurrencyRequest','-> 0.1'
                      ^.

 #  from /Users/khawarislam/Desktop/CurrencyApp/Podfile:6
 #  -------------------------------------------
 #     
 >      'CurrencyRequest','-> 0.1'
 #    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 #  -------------------------------------------
Khawars-MBP:CurrencyApp khawarislam$ pod install

[!] Invalid `Podfile` file: syntax error, unexpected ',', expecting keyword_end
    'CurrencyRequest','->0.1'
                      ^.

 #  from /Users/khawarislam/Desktop/CurrencyApp/Podfile:6
 #  -------------------------------------------
 #     
 >      'CurrencyRequest','->0.1'
 #  
 #  -------------------------------------------
Khawars-MBP:CurrencyApp khawarislam$ pod install

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyApp' do
   
pod 'CurrencyRequest','-> 0.1'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CurrencyApp

end
```

### Error

```
ArgumentError - Illformed requirement `"-> 0.1"`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/dependency.rb:116:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:747:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:747:in `block in pod_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:743:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:743:in `pod_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:95:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:73:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile.rb:90:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile.rb:90:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:772:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Illformed+requirement+%60%22-%3E+0.1%22%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - ArgumentError - Illformed requirement `" UI = 0.1.0"`
   https://github.com/CocoaPods/CocoaPods/issues/2898 [closed] [18 comments]
   02 Dec 2015

 - error
   https://github.com/CocoaPods/CocoaPods/issues/4841 [closed] [2 comments]
   28 Jan 2016

 - ERROR ON POD INSTALL
   https://github.com/CocoaPods/CocoaPods/issues/4622 [closed] [2 comments]
   03 Dec 2015

Khawars-MBP:CurrencyApp khawarislam$ sudo gem install cocoapods
Password:
Successfully installed cocoapods-1.0.1
Parsing documentation for cocoapods-1.0.1
1 gem installed
Khawars-MBP:CurrencyApp khawarislam$ pod install

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyApp' do
   
pod 'CurrencyRequest','-> 0.1'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CurrencyApp

end
```

### Error

```
ArgumentError - Illformed requirement `"-> 0.1"`
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:63:in `parse'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:88:in `map!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:34:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/requirement.rb:34:in `create'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/dependency.rb:116:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:747:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:747:in `block in pod_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:743:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:743:in `pod_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:95:in `non_inherited_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile/target_definition.rb:73:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile.rb:90:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.0.rc.2/lib/cocoapods-core/podfile.rb:90:in `dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/analyzer.rb:772:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Illformed+requirement+%60%22-%3E+0.1%22%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - ArgumentError - Illformed requirement `" UI = 0.1.0"`
   https://github.com/CocoaPods/CocoaPods/issues/2898 [closed] [18 comments]
   02 Dec 2015

 - error
   https://github.com/CocoaPods/CocoaPods/issues/4841 [closed] [2 comments]
   28 Jan 2016

 - ERROR ON POD INSTALL
   https://github.com/CocoaPods/CocoaPods/issues/4622 [closed] [2 comments]
   03 Dec 2015

Khawars-MBP:CurrencyApp khawarislam$

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

However, you want to use `~>` not `->` in your Podfile

**Comment by SuccessfullyHappy** [comment]
Thnks Orta 👍
