### ISSUE TITLE
Pod seems to work for Swift but breaks on ObjectiveC

### ISSUE THREAD

**Issue by haseebOptini** [CocoaPods/CocoaPods#5968]
# Report
I have a CocoaPod named [PredictIO](https://github.com/predict-io/PredictIO-iOS) using the static library we use the module map so that user can import using use_framework. My pod seems to work fine on swift but i import it in ObjectiveC i get the following error  
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PredictIO", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
my pod can be found on the following [link](https://github.com/predict-io/PredictIO-iOS) 
## What did you do?
I used the Module map and in module map i have my header file named PredictIO.h. and same file contains my protocol and shared instance to use.

## What did you expect to happen?
I am able to use the PredictIO.h in Objective C just like swift, and use my shared instance as expected

## What happened instead?
when ever i used shared instance of PredictIO the compiler throws me error as follow 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PredictIO", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
## CocoaPods Environment
```
```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bharath2020 - https://github.com/bharath2020/CalcLibrary @ e4e9333d89a06e94f28cc13ceb845227fbc80742
               BlinkingLabel2Specs - https://github.com/ahaseebchina01/BlinkingLabel2Specs.git @ e0acd391b00a2bbe2e843e8a5efd28688dd2513d
               BlinkingLabelSpec - https://github.com/ahaseebchina01/BlinkingLabelSpec.git @ b6b6af2ac2548214c7274d333e8221c60b9b4bb0
               DummyBlinkingLabelTestSpec - https://github.com/ahaseebchina01/DummyBlinkingLabelTestSpec @ 162cfcae28dbeff4a591101b4879e0a3f68fa2bb
               DummyPodAHaseebChina01Spec - https://github.com/ahaseebchina01/DummyPodSpec @ 90e481f2e428f20bc127c0fc35913ec7fd63b593
               DummyPodTestingSpec - https://github.com/ahaseebchina01/DummyPodTestingSpec.git @ d2d42047547d93c0e1b43dceb5df055e3642b06e
               DummyTestingPodSpec - https://github.com/ahaseebchina01/DummyTestingPodSpec @ 01d057326a3ba2b9db0872169db3a7e927572675
               master - https://github.com/CocoaPods/Specs.git @ ccc10c50d0e1e3acd0d40bdd095ddecba9f4cdb0
               ParktagPod2Spec - https://github.com/ahaseebchina01/ParktagPod2Spec.git @ cac1aa6a318f9a24fd92d8d1d5ee44845d317248
               ParktagPodSpec - https://github.com/ahaseebchina01/ParktagPodSpec.git @ 380a2b2639f9c46d97e3bcf38eaaa68514435dc0
               predict-ioSpec - https://github.com/predict-io/predict-ioSpec.git @ c5b8c58577f8278c7e6cf42516cde0a7df6901a8
               predict.ioSpec - https://github.com/predict-io/predict.ioSpec @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               PredictIO - https://github.com/parktag/PredictIOSpec @ 100b4e997cdb672683c6c50ce268ea28d503a6a8
               PredictIO-iOSSpec - https://github.com/predict-io/PredictIO-iOSSpec.git @ cf806fc47bc274f1b0a99c48c117d7fd07ada2b4
               PredictIO3.0 - https://github.com/parktag/PredictIOSpec @ bac7487cf97a2ca4571331388da165673d8ffd7b
               PredictIOPodSpec - https://github.com/ahaseebchina01/PredictIOPodSpec @ 70bda76b31296ebcf9dcf88f0b673f4e2bf87a91
               PredictIOPodSpecUpdated - https://github.com/parktag/PredictIOSpec @ 97bc880d741c075d24a8a89b8f081569d6973d95
               PredictIOSpec - https://github.com/ahaseebchina01/PredictIOSpec.git @ 4f47ab0027ec2d0a78f2af03bbff0c4bac1351f2
               PredictIOSpec2 - https://github.com/predict-io/PredictIOSpec.git @ 5c153b9b6f1cf8d52113926f3187650e641dd45a
               PredictIOSpec3 - https://github.com/predict-io/PredictIOSpec.git @ 160a898fcd0e9e4451bf5adc6bfd73470e1d8baf
               PredictIOSpec4 - https://github.com/predict-io/PredictIOSpec.git @ a261883ab355a76cf8cb8cf05a5c3781bb2116a0
               predictIOSpec5 - https://github.com/predict-io/PredictIOSpec @ 3fd2fc954abf5cb9eb5a6790a84914e1457ad33a
               PredictIOSpecUpdated - https://github.com/parktag/PredictIOSpec @ 587f9ecc22923dbc980feeba86d581176965bb0e
               PredictIOTestPodSpec - https://github.com/predict-io/PredictIOTestPodSpec @ e846eac2d026d2cc00a0cc7c711e9b9cf8ab4ff9
               RWPodSpecs - https://github.com/ahaseebchina01/RWPodSpecs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               RWPodSpecs2 - https://github.com/ahaseebchina01/RWPodSpecs2.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               TestMultiRepoPodPredictIOSpec - https://github.com/ahaseebchina01/TestMultiRepoPodPredictIOSpec @ 07ab5ad58dc82fc319d79567447d974b54f62734
               TestParktagPods2Spec - https://github.com/ahaseebchina01/TestParktagPods2Spec.git @ ba3089f88e1c4ee9c1b5b98f336d183f15387a63
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.0
cocoapods-docs        : 0.2.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

Abduls-MacBook-Pro:PredictIO-iOS abdulhaseeb$ 
```

## Project that demonstrates the issue
Please find project with problem on attachement
[testingPodRelease.zip](https://github.com/CocoaPods/CocoaPods/files/498678/testingPodRelease.zip)

**Comment by neonichu** [comment]
I think the issue you're running into is that since your Pod and your vendored library share exactly the same name ("PredictIO"), the linker cannot distinguish between the two and only the Pod gets linked. Could you try renaming the vendored library and re-try to verify this?

**Comment by haseebOptini** [comment]
Thank you that thing worked like a charm ... 👍
