### ISSUE TITLE
Running the target in Xcode after `pod install`

### ISSUE THREAD

**Issue by RishabhTayal** [CocoaPods/CocoaPods#5969]
I have and idea about new feature. Is it possible to add a script which will run the selected target in the Xcode after `pod install` is finished?

If it's possible I will be glad to help implement it.

**Comment by neonichu** [comment]
I think this is more suited for a plugin.

**Comment by RishabhTayal** [comment]
Any pointers on how we can implement this in a plugin?

**Comment by neonichu** [comment]
This blog post gives some pointers on how to implement a post-install plugin: https://engineering.tumblr.com/post/124712775024/adventures-in-making-a-cocoapods-plugin

**Comment by RishabhTayal** [comment]
👍
