### ISSUE TITLE
pod trunk push An error has occurred 

### ISSUE THREAD

**Issue by aimobier** [CocoaPods/CocoaPods#5973]
hello, 
Hello, when I was  `pod trunk push demo.podspec`  there was the following error
````
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.
````
I see a person said, using `sudo gem install cocoapods --pre`,Upgrading Cocoapods to 1.1.0.rc.2 can solve this problem

But When I'm done `sudo gem install cocoapods --pre`

`gem list`

I found that the Cocoapods version is as follows

````
cocoapods (1.1.0.beta.2)
cocoapods-core (1.1.0.beta.2)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.1)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.0.0)
cocoapods-try (1.1.0)
````

I don't know whether it's a podtrunk version of the problem.

then l try `sudo gem install cocoapods-trunk --pre`

````
MisterdeMini:OddityUI mister$ sudo gem install cocoapods-trunk --pre
Password:
Successfully installed cocoapods-trunk-1.0.0
Parsing documentation for cocoapods-trunk-1.0.0
Done installing documentation for cocoapods-trunk after 0 seconds
1 gem installed
````

Where did I go wrong? How do I submit the new version?

**Comment by benasher44** [comment]
After installing the latest using --pre, run `gem uninstall cocoapods`, and you'll prompted to select the version you want to remove. Then you should be able to delete the older versions.

**Comment by aimobier** [comment]
I have already tried this. But it seems to have no use. cocoapod-trunk is still 1.0.0

**Comment by benasher44** [comment]
Oh that's okay. That's the lates version of that gem

**Comment by neonichu** [comment]
Have a look at #5909 if you're having trouble installing rc.2

**Comment by aimobier** [comment]
The problem lies in：

````
MisterdeMini:OddityUI mister$ pod --version
1.1.0.beta.2
MisterdeMini:OddityUI mister$ pod trunk push OddityUI.podspec
Updating spec repo `master`

CocoaPods 1.1.0.rc.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.2

Validating podspec
 -> OddityUI (0.1.3)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

[!] The spec did not pass validation, due to 1 error.
MisterdeMini:OddityUI mister$
````

My version is rc.2 but still not, or will appear this problem......

**Comment by neonichu** [comment]
No, your version is beta.2, this is not the same as rc.2
