### ISSUE TITLE
Don't create workspace. cocoapods 1.1.0.rc.2 and Xcode8

### ISSUE THREAD

**Issue by huangboju** [CocoaPods/CocoaPods#5976]
<img width="979" alt="2016-09-30 9 12 28" src="https://cloud.githubusercontent.com/assets/14818224/18977622/83f4efda-86ee-11e6-988f-3d50d2fe6a41.png">

**Comment by orta** [comment]
Please fill out the issue template, rather than creating an issue with a screenshot in it. It helps a lot in debugging, and please test with the latest beta if you're using Xcode 8.
