### ISSUE TITLE
CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

### ISSUE THREAD

**Issue by Maheepk** [CocoaPods/CocoaPods#5977]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by Maheepk** [comment]
Hi,  [!] Unable to satisfy the following requirements:  - `Nudgespot (~> 2.3)` required by `Podfile` - `Nudgespot (~> 2.6)` required by `Podfile`  None of your spec sources contain a spec satisfying the dependency: `Nudgespot (~> 2.3)`.  You have either:  * out-of-date source repos which you can update with `pod repo update`.  * mistyped the name or version.  * not added the source repo that hosts the Podspec to your Podfile.  Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by orta** [comment]
Hi @Maheepk - 
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by orta** [comment]
Remember to read the errors too - this is probably because of this:

> Note: as of CocoaPods 1.0, pod repo update does not happen on pod install by default.

**Comment by Maheepk** [comment]
actually i am dev at Nudgespot sdk so, one of our customer got this bug, want to know that is there a way i can fix that from Nudgespot cocoapods as customer is not getting that bug in other pods.

**Comment by orta** [comment]
You can't, it's a problem with their setup, as I said, they probably need to do the things that error report tells them to do.

**Comment by Maheepk** [comment]
thanks @orta
