### ISSUE TITLE
Error while setting up CocoaPods

### ISSUE THREAD

**Issue by mubashirhussain** [CocoaPods/CocoaPods#5979]
pod setup --verbose

Setting up CocoaPods master repo

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
### Command

```
/usr/local/bin/pod setup --verbose
```
### Report
- What did you do?
- What did you expect to happen?
- What happened instead?
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 1.8.4
Ruby lib dir : /Users/kashif/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fd0e7c0a2dd929ca64a89ad915f6b689fe3afe9c
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```
### Error

```
ArgumentError - invalid byte sequence in UTF-8
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:89:in `split'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:89:in `which'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:110:in `which!'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:49:in `execute_command'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/executable.rb:23:in `block in executable'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:44:in `block in set_master_repo_url'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:43:in `chdir'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:43:in `set_master_repo_url'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:23:in `block in run'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/command/setup.rb:21:in `run'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/kashif/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/Users/kashif/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/kashif/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+UTF-8&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by orta** [comment]
If you are using Xcode 8,  have you tried using the CocoaPods pre-release versions?

**Comment by mubashirhussain** [comment]
Yes I am using Xcode 8 and I have tried pre-release versions before.

**Comment by DanToml** [comment]
@mubashirhussain Xcode 8 is not supported by CocoaPods < 1.1.0. To install the beta, please run `[sudo] gem install cocoapods --pre`

**Comment by mohshin-shah** [comment]
Please open the terminal and execute this 
git config --global user.email "youremail@xxx.xxx"
then try pod install

**Comment by benasher44** [comment]
@mubashirhussain can you please post your Podfile? It's hard to debug this issue without it. Thanks!

**Comment by mubashirhussain** [comment]
Here are podfile contents,

target 'BUKImagePickerController-Example' do
  pod "BUKImagePickerController", :path => "../"

  target 'Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end

**Comment by benasher44** [comment]
@mubashirhussain I won't be able to test using that Podfile because it has a `:path` argument that points to something I don't have on my machine.

But, this error indicates some kind of encoding issue. You could try editing this using an editor that's not TextEdit. I also notice that you're mixing and matching quotes. This is fine, but maybe one set is the wrong kind of quotes? Maybe try using all single quotes?

As a last ditch ever to solve this, you could try just retyping your Podfile by hand, since it's not that big.

**Comment by mubashirhussain** [comment]
I have tried the simple podfile by typing myself but still got the same issue,

platform :ios, '8.0'
use_frameworks!

target 'BSImagePicker_Example' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
end

/////// ******* Error *********////

## Command

```
/Users/kashif/.rvm/gems/ruby-2.2.1/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 1.8.4
Ruby lib dir : /Users/kashif/.rvm/rubies/ruby-2.2.1/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'BSImagePicker_Example' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
end
```

### Error

```
ArgumentError - invalid byte sequence in UTF-8
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/executable.rb:89:in `split'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/executable.rb:89:in `which'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/executable.rb:110:in `which!'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/executable.rb:49:in `execute_command'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/add.rb:71:in `block in clone_repo'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/add.rb:69:in `chdir'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/add.rb:69:in `clone_repo'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/add.rb:41:in `block in run'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/add.rb:39:in `run'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/setup.rb:54:in `add_master_repo'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/setup.rb:27:in `block in run'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/setup.rb:21:in `run'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:25:in `find_or_create_source_with_url'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:814:in `block in sources'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `map'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:813:in `sources'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:143:in `resolve_dependencies'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/kashif/.rvm/gems/ruby-2.2.1/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/kashif/.rvm/gems/ruby-2.2.1/bin/pod:23:in `load'
/Users/kashif/.rvm/gems/ruby-2.2.1/bin/pod:23:in `<main>'
/Users/kashif/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/kashif/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=invalid+byte+sequence+in+UTF-8&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Pod install fails on invalid byte sequence while having LANG=en_US.UTF-8 in profile
   https://github.com/CocoaPods/CocoaPods/issues/5780 [closed] [5 comments]
   11 hours ago

 - Error while setting up CocoaPods
   https://github.com/CocoaPods/CocoaPods/issues/5979 [open] [7 comments]
   10 minutes ago

 - ArgumentError - invalid byte sequence in US-ASCII
   https://github.com/CocoaPods/CocoaPods/issues/5348 [closed] [3 comments]
   18 May 2016

and 12 more at:
https://github.com/cocoapods/cocoapods/search?q=invalid%20byte%20sequence%20in%20UTF-8&type=Issues&utf8=✓

**Comment by benasher44** [comment]
@mubashirhussain can you check to make sure you have `LANG=en_US.UTF-8` set in your terminal? You can see if this fixes it by doing `LANG=en_US.UTF-8 pod install`

**Comment by mubashirhussain** [comment]
This is `locale` output, 

```
MubashirsMacPro:Example kashif$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

Also tried `LANG=en_US.UTF-8 pod install` but same error. :(

**Comment by benasher44** [comment]
That's odd. I have the same output for `locale`. Can you show me the contents of `echo $PATH`?

**Comment by mubashirhussain** [comment]
Here you go,

```
MubashirsMacPro:~ kashif$ echo $PATH
/Users/kashif/.rvm/gems/ruby-2.2.1/bin:/Users/kashif/.rvm/gems/ruby-2.2.1@global/bin:/Users/kashif/.rvm/rubies/ruby-2.2.1/bin:/usr/local/php5/bin:/opt/local/bin:/opt/local/sbin:/Applications/XAMPP/xamppfiles/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin??n’export:/Users/kashif/.rvm/bin
```

**Comment by benasher44** [comment]
Can you remove `/sbin??n’export` entry from your path? Looks like this is malformed. So just do PATH=<everything but that> (keeping each part separated by a colon). Once you do that print out your path again to verify. If that looks good, try your pod command again

**Comment by mubashirhussain** [comment]
Tried above path now gives output without that portion but unfortunately error is still there.

```
MubashirsMacPro:~ kashif$ echo $PATH
/Users/kashif/.rvm/gems/ruby-2.2.1/bin:/Users/kashif/.rvm/gems/ruby-2.2.1@global/bin:/Users/kashif/.rvm/rubies/ruby-2.2.1/bin:/usr/local/php5/bin:/opt/local/bin:/opt/local/sbin:/Applications/XAMPP/xamppfiles/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/Users/kashif/.rvm/bin
```

**Comment by benasher44** [comment]
@mubashirhussain can you do `PATH=''` and then try the pod command again? At least that way, maybe we can confirm it's something in your `PATH`?

**Comment by mubashirhussain** [comment]
Got this while trying above description,

```
MubashirsMacPro:Example kashif$ pod install
-bash: pod: No such file or directory
```

**Comment by benasher44** [comment]
@mubashirhussain you'll have to specify the full path to the pod command while you're testing with an empty PATH. you can get the full path by running `which pod` in a new terminal window.

**Comment by mubashirhussain** [comment]
I got this error when installing cocoa-pods, although I already have master repo downloaded using this command,

`git clone https://github.com/CocoaPods/Specs.git master`


**ERROR**
```
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-3`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
```

**Comment by benasher44** [comment]
Ah okay yeah this is going to fail in all kinds of ways with an empty `PATH`. There's some kind of bad character in your `PATH`, and it's going to take some trial and error on your part to figure out which item in your `PATH` is causing the issue. I'm not sure there's more I can do here.

One other thing to be aware of is that at least CocoaPods 1.1.0 (1.1.1 is available now) is required when using Xcode 8.

**Comment by mubashirhussain** [comment]
After you above comment I again checked the `PATH` and it was reverted to old value in which it had this `/sbin??n’export`garbage entry. After that I tried pod install and it worked quietly. 

Thanks for all the support guys. 👍

**Comment by benasher44** [comment]
No prob! You'll have to look in your `.bash_profile` or `.bashrc` to see what's setting up your PATH to have the garbage value and then remove it.

**Comment by DarkZhao** [comment]
> Here you go,
> 
> ```
> MubashirsMacPro:~ kashif$ echo $PATH
> /Users/kashif/.rvm/gems/ruby-2.2.1/bin:/Users/kashif/.rvm/gems/ruby-2.2.1@global/bin:/Users/kashif/.rvm/rubies/ruby-2.2.1/bin:/usr/local/php5/bin:/opt/local/bin:/opt/local/sbin:/Applications/XAMPP/xamppfiles/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin??n’export:/Users/kashif/.rvm/bin
> ```

It seems I have the same problem.I have tried every method I could find, but none of them worked.
This problem happened after I update my MacOS from `10.13.4` to `10.13.6`.
Here is my path:
```
~> echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
I don't know if there is any problem here.

This is `locale` output:

```
LANG="en_US.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL="C"
```

my  `bash_profile`
```
# make .bash_profile same as .bashrc
if [ -f "${HOME}/.bashrc" ]; then
    source "${HOME}/.bashrc"
fi

export LANG=en_US.UTF-8
```

My English is very poor, if there  any words confuse you,I am very sorry.

**Comment by DarkZhao** [comment]
@benasher44 Please
