### ISSUE TITLE
ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES Inherited creates project validation issues

### ISSUE THREAD

**Issue by lukef** [CocoaPods/CocoaPods#5981]
* [ X ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Running `pod install` gives the following warnings: 

```
[!] The `<project name> [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `<.xcconfig location>'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

If you manually set the project setting to `$(inherited)` or remove the setting then xcode will ask you to update the project to recommended settings.

## What did you expect to happen?

Is there a way to silence this warning if Xcode requires the setting to be YES in certain cases?

## What happened instead?

Every time I run `pod install/update` I see the same warning.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A319)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/luke/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0bc2638d6e7f807e304464a2f79f9ef64b4cff7c
```

### Installation Source

```
Executable Path: /Users/luke/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by benasher44** [comment]
You should remove those settings from your targets that CocoaPods integrates, since CocoaPods sets them for you.

**Comment by benasher44** [comment]
It'll set them appropriately based on whether or not the target its integrating contains Swift and/or the pods its integrating contain Swift.

**Comment by lukef** [comment]
Deleting the options does not seem to work. Xcode wants to set them explicitly and will show this as a warning every time. Also, EMBEDDED_CONTENT_CONTAINS_SWIFT is now obsolete in Xcode 8 (swift 3 only?).

**Comment by benasher44** [comment]
In Xcode 8 it's deprecated for 2.3 and 3. Hm. Try deleting the settings, quitting Xcode, `pod install`ing, and then starting Xcode?

**Comment by benasher44** [comment]
Just to update, the fix is being worked on in #5933.

**Comment by benasher44** [comment]
The fix here was merged in #5933/#6016 and will be available in an upcoming release. Thanks for filing!

**Comment by whittenator** [comment]
I was able to fix this problem by doing the following:
1. Go into Build Settings
2. At the top select All and Completed
3. Under Build Options you should see **Always Embed Swift Standard Libraries** and it is bold. 
4. Click on it and click delete. It should now be unbolded. 
5. Pod install and the error/errors should go away!
![screen shot 2016-12-28 at 4 56 09 pm](https://cloud.githubusercontent.com/assets/17066507/21532583/93df897e-cd1f-11e6-9f17-d25cb81a2a53.png)

**Comment by johnantoni** [comment]
This worked for me

<img width="752" alt="screen shot 2017-01-08 at 6 02 54 pm" src="https://cloud.githubusercontent.com/assets/15571/21754386/d4d6b136-d5cc-11e6-81f4-d42cb0cc3e2f.png">

<img width="875" alt="screen shot 2017-01-08 at 6 03 04 pm" src="https://cloud.githubusercontent.com/assets/15571/21754384/d4d35b44-d5cc-11e6-9dad-1631bf7ee15e.png">

<img width="882" alt="screen shot 2017-01-08 at 6 03 12 pm" src="https://cloud.githubusercontent.com/assets/15571/21754385/d4d44d56-d5cc-11e6-930c-35f9c7b7877f.png">

<img width="868" alt="screen shot 2017-01-08 at 6 03 18 pm" src="https://cloud.githubusercontent.com/assets/15571/21754387/d4d76450-d5cc-11e6-8a79-f79823a6346d.png">

**Comment by johnantoni** [comment]
Cleared and green:

Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

I tried clearing the error via terminal but no go, the CocoaPods app is way friendlier at adding pods and reporting errors.

**Comment by chlebta** [comment]
@johnantoni I've followed the same steps but always getting those warning : 
```
[!] The `gather-iosTests [Debug Staging]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-gather-iosTests/Pods-gather-iosTests.debug staging.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `gather-iosTests [Debug Production]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-gather-iosTests/Pods-gather-iosTests.debug production.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `gather-iosTests [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-gather-iosTests/Pods-gather-iosTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by xulianpeng** [comment]
when I import SDWebImage in my project second time,It worn that Module FLAnimatedImage not found,and when I pod install ,it warn  "... ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES ... - Use the `$(inherited)` flag, or - Remove the build settings from the target." 
At last, I find the way that  remove the SD completely,specialy in the  finder ,in the pods' products,and delete the project in the simulator , then import SD again.

**Comment by malisanjay5433** [comment]
Helped

**Comment by b-tiwari** [comment]
I was getting below errors:
`
[!] The `myApp [Debug]`` target overrides the `LD_RUNPATH_SEARCH_PATHS`` build setting defined in `Pods/Target Support Files/Pods-myApp/Pods-myApp.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `myApp [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-myApp/Pods-myApp.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
`

what worked for me - based on error messages above, I figured some Run Path/Search path build setting of my app overriding the Pods build setting. Went to xcode, and made below changes to my app's build settings 

![1](https://user-images.githubusercontent.com/13605214/35888361-f91c10b0-0b5c-11e8-92ac-338ca5a2acc1.png)

![2](https://user-images.githubusercontent.com/13605214/35888385-10fd1102-0b5d-11e8-96ab-387df58b17bd.png)

from Xcode top menu, Product -> Clean

And pod install again now worked with no error:
`Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.`

**Comment by sureshkamal** [comment]
@b-tiwari great!! It worked for me.

**Comment by saiful2396** [comment]
[!] The `midlandonline [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-midlandonline/Pods-midlandonline.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `midlandonline [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-midlandonline/Pods-midlandonline.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
**I have this issue what should i do now please help me**

**Comment by Sifatsb** [comment]
The `Runner [Profile]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.


Still now I am getting the same error. Anyone can help me?
