### ISSUE TITLE
Pod spec lint fails after adding s.dependency to spec

### ISSUE THREAD

**Issue by miller-ms** [CocoaPods/CocoaPods#5983]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
ttps://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Updated the pod spec with a dependency
 - s.dependency = 'MMSCameraViewController'
- ran 'pod spec lint' at command line

## What did you expect to happen?

Expected to get the following message:

*MMSProfileImagePicker.podspec passed validation.*

**Before adding the dependency it passed validation.**

## What happened instead?

 -> MMSProfileImagePicker.podspec
    - ERROR | spec: The specification defined in `MMSProfileImagePicker.podspec` could not be loaded.

[!] Invalid `MMSProfileImagePicker.podspec` file: undefined method `dependency=' for #<Pod::Specification name="MMSProfileImagePicker">.

 #  from MMSProfileImagePicker.podspec:34
 #  -------------------------------------------
 #    s.frameworks = 'UIKit', 'AVFoundation', 'CoreMedia', 'ImageIO'
 '>    s.dependency = 'MMSCameraViewController'
 #  
 #  -------------------------------------------

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5c4eb75699f8c1918feb8c9d1fc7cce6e7d55e70
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/miller-ms/MMSProfileImagePicker

**Comment by orta** [comment]
Sorry, we're waiting on the next RC release for the guides to fix themselves - https://github.com/CocoaPods/Core/pull/355, there should be no `=` in there

**Comment by miller-ms** [comment]
Thank you.  I need to learn how to search better.   I'm embarrassed to say how many searches i did and #355 never came up.

**Comment by orta** [comment]
Hopefully this will now pop up for other people now!
