### ISSUE TITLE
`pod try` incorrectly generates a Swift 2 project for Swift 3 pod

### ISSUE THREAD

**Issue by pcantrell** [CocoaPods/CocoaPods#5986]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod try Siesta`

## What did you expect to happen?

Project all set to go!

## What happened instead?

Xcode brings up a “Convert to Current Swift Syntax?” dialog for the project, despite the fact that the pod itself already uses Swift 3, and contains a `.swift-version file`.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/paul/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 077bc2a09b17811d273698164e33432db05c61fb
```

### Installation Source

```
Executable Path: /Users/paul/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.0
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

## Project that demonstrates the issue

`pod try Siesta`

**Comment by pcantrell** [comment]
Hmm, can’t reproduce after restarting Xcode. ?!?

Will close if I still can’t reproduce tomorrow.

**Comment by pcantrell** [comment]
Got it! Nothing to do with Xcode — the problem was that I ran it at first from my local clone of Cocoadocs, which bundles an old version of the CocoaPods gem.

Sorry for the noise. This does explain why CocoaDocs isn’t generating docs for Swift 3 projects, though!

**Comment by orta** [comment]
👍
