### ISSUE TITLE
Install cocoapods-1.1.0.rc.2

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#5987]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

In terminal:
sudo gem install cocoapods --pre
give me:
Successfully installed cocoapods-1.1.0.rc.2
Parsing documentation for cocoapods-1.1.0.rc.2
Done installing documentation for cocoapods after 2 seconds
1 gem installed

## What did you expect to happen?

pod --version
give me:
 1.1.0 rc 2

## What happened instead?

pod --version
give me:
 1.0.1

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12 (16A323)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.4.5
Ruby lib dir : /Users/patrickbodet/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b4176e001368a16798b76f33fc2ed9776316cfb1
```

### Installation Source

```
Executable Path: /Users/patrickbodet/.rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

**Comment by iDevelopper** [comment]
Then I re-installed Xcode 7 to pod lint validation passe!

**Comment by benasher44** [comment]
Run `gem uninstall CocoaPods`, and then it'll give you the option to uninstall the older versions you have installed.

Going to close, since this isn't an issue with CocoaPods.

**Comment by iDevelopper** [comment]
Thanks @benasher44 for reply 👍
