### ISSUE TITLE
Cannot create new pod - incorrect argument label in call

### ISSUE THREAD

**Issue by gsabran** [CocoaPods/CocoaPods#5991]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk push Name.podspec`

## What did you expect to happen?

The code to be pushed to the pod repo

## What happened instead?

The linting/testing failed with:

`- ERROR | [iOS] xcodebuild:  GLMatrix/GLMatrix/Classes/Extensions.swift:43:12: error: incorrect argument label in call (have 'scnVector4:', expected 'SCNVector4:')` while the project and its tests run fine within xcode. The code that is triggering this error is [here](https://github.com/gsabran/GLMatrix/blob/master/GLMatrix/Classes/Extensions.swift#L41-L49)

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/guigou/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3355ecfa1b70fda8c2087985fc8eefe142d79f95
```

### Installation Source

```
Executable Path: /Users/guigou/.rvm/gems/ruby-2.3.1/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/gsabran/GLMatrix/blob/master/GLMatrix

**Comment by DanToml** [comment]
Your .swift-version file has a trailing dot in the file name, so you're building using the wrong version of swift

**Comment by gsabran** [comment]
Excellent catch. No idea how it got here.
