### ISSUE TITLE
How to add Pods.xcodeproj as subproject?

### ISSUE THREAD

**Issue by adamszeremeta** [CocoaPods/CocoaPods#5992]
Hello, 
I'm developing my cocoa framework and I want to use few dependencies using cocoapods. I'm using xCode 7 and Swift 2.2, Cocoapods RC1.1

This is my podfile: (I don't want to create workspace, I want to add cocoapods as subproject)
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

install! 'cocoapods', :integrate_targets => false

target 'MySDK' do
    pod 'Alamofire', '~> 3.4.1'
    pod 'SwiftyJSON', '~> 2.3.2'
    pod 'RxSwift', '~> 2.6.0'
    pod 'RxCocoa', '~> 2.6.0'
    pod 'SDWebImage', '~> 3.8.1'

    pod 'GoogleMaps', '~> 1.13.2'
end
```

Then I'm dragging generated by pod install Pods.xcodproj to my framework project but then in compilation I'm getting: "No such Module RxSwift"
I'm trying also to add RxSwift and other frameworks to Linked frameworks but without any success. What I'm missing here?

Thanks for help

**Comment by muvic08** [comment]
I am having the same issue. Did you figure out a solution?

**Comment by dnkoutso** [comment]
If you use `integrate_targets => false` then you have to do the integration yourself after you drag the `Pods.xcodeproj` to your project. CocoaPods won't setup the header search paths or dependencies for you.
