### ISSUE TITLE
command /bin/sh failed with exit code 133

### ISSUE THREAD

**Issue by kkaliher** [CocoaPods/CocoaPods#5995]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

Attempt to build and run project in Xcode 8 / Sierra on device

## What did you expect to happen?

Successful build

## What happened instead?

During Run custom shell script '[CP] Embed Pods Frameworks', Command /bin/sh failed with exit code 133
Tried deintegrate + install, but same result.  Also tried deleting derived data, cleaning, and so on.  
Builds and runs fine on simulator though.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 60f39439754a3b8a345859a7ff68f256111a5f2b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'app' do

pod 'Fabric'
pod 'Crashlytics'
pod 'Digits'
pod 'PusherSwift'
pod 'Alamofire', '~> 4.0'
pod 'AlamofireImage', '~> 3.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

end

**Comment by benasher44** [comment]
Do you have any more info from that script phase in the build log?

**Comment by kkaliher** [comment]
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/kk/Library/Developer/Xcode/DerivedData/app-ahernaloopcisealicqmoteosskb/Build/Intermediates/app.build/Debug-iphoneos/app\ dev.build/Script-AD08BAB3345EFC71FFED1692.sh
    cd /Users/kk/Work/app/ios/code/iOS
    /bin/sh -c \"/Users/kk/Library/Developer/Xcode/DerivedData/app-ahernaloopcisealicqmoteosskb/Build/Intermediates/app.build/Debug-iphoneos/app\ dev.build/Script-AD08BAB3345EFC71FFED1692.sh\"

mkdir -p /Users/kk/Library/Developer/Xcode/DerivedData/app-ahernaloopcisealicqmoteosskb/Build/Products/Debug-iphoneos/app dev.app/Frameworks
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/kk/Library/Developer/Xcode/DerivedData/app-ahernaloopcisealicqmoteosskb/Build/Products/Debug-iphoneos/Alamofire/Alamofire.framework" "/Users/kk/Library/Developer/Xcode/DerivedData/app-ahernaloopcisealicqmoteosskb/Build/Products/Debug-iphoneos/app dev.app/Frameworks"
building file list ... done

sent 133 bytes  received 20 bytes  306.00 bytes/sec
total size is 1786840  speedup is 11678.69
Code Signing /Users/kk/Library/Developer/Xcode/DerivedData/app-ahernaloopcisealicqmoteosskb/Build/Products/Debug-iphoneos/app dev.app/Frameworks/Alamofire.framework with Identity iPhone Developer: kk
 (SZZL8L88F7)
/usr/bin/codesign --force --sign 9F0ECE9D152BF766BC3233AF79DD4DA90BF221E2  --preserve-metadata=identifier,entitlements "/Users/kk/Library/Developer/Xcode/DerivedData/app-ahernaloopcisealicqmoteosskb/Build/Products/Debug-iphoneos/app dev.app/Frameworks/Alamofire.framework"
/Users/kk/Work/app/ios/code/iOS/Pods/Target Support Files/Pods-app dev/Pods-app dev-frameworks.sh: line 58: 39862 Trace/BPT trap: 5       /usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS} --preserve-metadata=identifier,entitlements "$1"
Command /bin/sh failed with exit code 133

**Comment by ralito** [comment]
I have the same issue. Did you manage to find a fix?

**Comment by kkaliher** [comment]
My current workaround is to build and archive using El Capitan.

**Comment by ralito** [comment]
Is there any update on this issue?

**Comment by benasher44** [comment]
I haven't been able to reproduce this one. If someone could provide a sample project that reproduces the issue, then that would be helpful.

**Comment by benasher44** [comment]
I'd also recommend updating your CocoaPods to 1.1.1 and try again.

**Comment by ralito** [comment]
For me this is happening with every project. I've updated CocoaPods to 1.1.1 and still nothing.

**Comment by kkaliher** [comment]
I believe this to be an underlying issue with code signing on Sierra 12.x + Xcode 8.x where code signing fails with exit code 5, and not with Cocoapods, so am closing this.
I opened an issue with Apple on it.  

Other developers have run into this issue but with no clear workaround other than to archive/build to device on El Capitan.
http://stackoverflow.com/questions/39664079/command-usr-bin-codesign-failed-with-exit-code-5

**Comment by vegidio-symbio** [comment]
I was having the exact same problem described here, but it got solved when I upgrade to Cocoapods to version **1.1.1**.

@ralito Just out of curiosity, how did you install version 1.1.1? Initially I was installing it using `gem update cocoapods`, and even thought it was apparently installing version 1.1.1, it only worked when I actually installed using `gem install cocoapods -v 1.1.1`.

@kkaliher I might be wrong, but I personally don't think the problem is related to Sierra 12.x + Xcode 8.x because now it's working for me and I have exactly this configuration on my Mac.

**Comment by kkaliher** [comment]
@vegidio-symbio - I thought that was the case due to this line from output, correlating with exit code 5's on code sign I was getting on other projects.  
trap: 5 /usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS} --preserve-metadata=identifier,entitlements "$1"

There may be other reasons for your 133 that 1.1.1 fixed.

For anyone hitting this general exit code 5 on code sign, deleting and reinstalling all keys worked for me (watch out for the buggy "1" key).  ref: http://stackoverflow.com/a/40341286/1473791

**Comment by vegidio-symbio** [comment]
@kkaliher Ok, thanks for the clarification. Just so you know, the version that was not working before in my Mac was version `1.2.0.beta.1` currently in Beta, so you might be able to check that before the release :)
