### ISSUE TITLE
source_files including framework caused linking error

### ISSUE THREAD

**Issue by briancaw** [CocoaPods/CocoaPods#5999]
# Report

## What did you do?

Integrated [`Appboy-tvOS-SDK podspec`](https://github.com/Appboy/appboy-ios-sdk/blob/master/Appboy-tvOS-SDK.podspec) with Swift and `use_frameworks!`, `pod install`, and build project.

## What did you expect to happen?

`Appboy_tvOS_SDK` correctly linked.

## What happened instead?

We got an undefined symbols error at compile time for our main interface.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Appboy", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.6.3
Ruby lib dir : ~/.rvm/rubies/ruby-2.1.2/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 095bfa20f0e129b2d2c8d7a16742e43b00f9810a
               master - https://github.com/CocoaPods/Specs.git @ de385c21e58ba9c124f5b8ce5c5d477de72fc024
```

### Installation Source

```
Executable Path: ~/.rvm/rubies/ruby-2.1.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-keys         : 1.7.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TestPublicRepoTv' do
  pod 'Appboy-tvOS-SDK', :path => './../appboy-iOS-SDK/'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        if target.name == "Appboy-iOS-SDK"
            config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
        end
        if target.name == "Appboy-tvOS-SDK"
            config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
        end
    end
  end
end
```

## Project that demonstrates the issue

Example project in https://github.com/peruginni/appboy-ios-sdk/tree/master/Example.

## Comments

We're able to resolve the issue by updating the source files in the Podspec to only include the public headers - currently our match there includes our Framework as well. 

i.e. we went from 

```
s.source_files = 'Appboy-tvOS-SDK/AppboyTVOSKit.framework/**/*.*'
```

to 

```
s.source_files = 'Appboy-tvOS-SDK/AppboyTVOSKit.framework/Headers/*.h'
```

 Is it intended/expected behavior that including a Framework in the source files would cause an issue like this?  For projects that aren't open source, is there a recommended configuration for the source_files attribute?

**Comment by benasher44** [comment]
For this one, I think you want to use [vendored_frameworks](https://guides.cocoapods.org/syntax/podspec.html#vendored_frameworks) instead.

**Comment by benasher44** [comment]
Have a look at the podspec DSL I mentioned there that's specifically for this scenario. Specifying a file pattern like `Appboy-tvOS-SDK/AppboyTVOSKit.framework/**/*.*` ignores the file extension of the files you're including as source, which can result in any number of strange build-time issues.

If you experience an issue using `vendored_frameworks` in your podspec, then please file a new issue.
