### ISSUE TITLE
Pod Spec Lint fails on Swift 3.0 pod dependency

### ISSUE THREAD

**Issue by miller-ms** [CocoaPods/CocoaPods#6001]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Podspec has dependency on another pod that builds in swift 3
- Pod with dependency is an objective-c project
- Has FBSnapshotTestCase in podfile
- Everything builds and fine with the Dependency building in swift 3, the FBSnapshot builds in swift 2.3, and the primary pd building in objective-c.
- Once testing was completed, executed pod trunk push.

## What did you expect to happen?

- Expected for it to successfully push to cocoapods

## What happened instead?

- The dependent pod fails to compile with over 100+ errors.
- Pod is in git at https://github.com/miller-ms/MMSProfileImagePicker

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6a5329830a2e9cfef33ae2af42a84abebf577f1b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/miller-ms/MMSProfileImagePicker

**Comment by DanToml** [comment]
This should work if you create a `.swift-version` file in your repo (`echo "3.0" > .swift-version`).
