### ISSUE TITLE
[Question] Clicking on a pod found at cocoapods.org redirects to GitHub

### ISSUE THREAD

**Issue by sasojadrovski** [CocoaPods/CocoaPods#6003]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run pod trunk push [NAME.podspec].

## What did you expect to happen?

I expected my [pod](https://github.com/sasojadrovski/SJFluidSegmentedControl) to be visible on [cocoapods.org](https://cocoapods.org/). 
It can be installed successfully by adding it to the `Podfile`, but if I try to access the details of the pod on [cocoapods.org](https://cocoapods.org/?q=sjfluidsegmentedcontrol) it redirects me to the GitHub repository of the pod.

## What happened instead?

The GitHub page of the pod is opened. Please let me know if I should make some changes so that the users will be able to see the pod details directly on cocoapods.org.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d141897f33c3b654d8d21a6bd46496f7df893e47
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

There are no issues with the project. I just wanted to ask whether the redirect to the GitHub page is something new, or there is an issue that prevents my pod to be displayed directly on cocoapods.org.

The pod name is `SJFluidSegmentedControl`.

I tried to find some information related to this, but no luck.

Thanks in advance!

**Comment by orta** [comment]
@sasojadrovski - please raise this on the CocoaPods.org repo - this repo is only for the CocoaPods command line tool 👍

**Comment by sasojadrovski** [comment]
Hey @orta,

Sorry, my bad :( I have opened the issue (question) [here](https://github.com/CocoaPods/cocoapods.org/issues/297). 

Thanks for the info!

Cheers!

**Comment by hsusmita** [comment]
Hey @orta , 
I am facing the same issue with my pod SwiftResposiveLabel.
`http://cocoadocs.org/docsets/SwiftResponsiveLabel/1.1/` is working fine.
`http://api.cocoadocs.org:4567/redeploy/SwiftResponsiveLabel/latest` gives this `{"parsing":true}`
`http://api.cocoadocs.org:4567/error/SwiftResponsiveLabel/1.1` give the following error.
```
report_error({"message":"undefined method `strip' for nil:NilClass","trace":["/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:429:in `block in document_spec'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:416:in `tap'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:416:in `document_spec'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:532:in `document_spec_at_path'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:152:in `block in doc'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `each'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:147:in `doc'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:219:in `block in cocoadocs_url'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:153:in `open_uri'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:704:in `open'","/Users/cocoadocs/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/open-uri.rb:34:in `open'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:216:in `cocoadocs_url'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:167:in `cocoadocs'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:102:in `initialize'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:564:in `new'","/Users/cocoadocs/cocoadocs.org/./cocoadocs.rb:564:in `<main>'"]}
)
```
`http://metrics.cocoapods.org/api/v1/pods/SwiftResponsiveLabel` gives this.
```
{"github":{"subscribers":1,"stargazers":2,"forks":1,"contributors":1,"open_issues":0,"open_pull_requests":0,"created_at":"2016-05-12 18:08:45 UTC","updated_at":"2016-08-10 04:42:58 UTC","language":"Swift","closed_issues":0,"closed_pull_requests":0},"cocoadocs":null,"stats":{"download_total":363,"download_week":32,"download_month":55,"app_total":16,"app_week":2,"tests_total":1,"tests_week":0,"created_at":"2016-05-13 09:06:35 UTC","updated_at":"2016-10-21 09:07:16 UTC","extension_week":0,"extension_total":0,"watch_week":0,"watch_total":0,"pod_try_week":0,"pod_try_total":0,"is_active":true}}
```
