### ISSUE TITLE
Feature Request: Add download progress indicator

### ISSUE THREAD

**Issue by miclaus** [CocoaPods/CocoaPods#6004]
When running `pod install` for the first time, the following message is displayed like ... **forever**:

**Setting up CocoaPods master repo**

The whole community is making fun of it 😄
http://stackoverflow.com/questions/21022638/pod-install-is-staying-on-setting-up-cocoapods-master-repo

**Comment by orta** [comment]
There's a PR for this 👍 , you're welcome to help out on it https://github.com/CocoaPods/CocoaPods/pull/5297

**Comment by miclaus** [comment]
Oh thanks ! Seem to have missed that.
