### ISSUE TITLE
Pod install not working with Rover

### ISSUE THREAD

**Issue by minhhieu052** [CocoaPods/CocoaPods#6007]
# Report

## What did you do?
Recently, I can not install the Rover on my project. I don't why it happen. In the past, it works well

Run `pod install`
I got this error as below 

> Re-creating CocoaPods due to major version update.
> Analyzing dependencies
> [!] Unable to satisfy the following requirements:
> 
> - `Rover` required by `Podfile`
> - `Rover (= 3.0.9)` required by `Podfile.lock`
> 
> None of your spec sources contain a spec satisfying the dependencies: `Rover, Rover (= 3.0.9)`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

## CocoaPods Environment
 pod --version
1.0.1

I also  run 'pod repo update' and pod install again. The issue is still happen
<img width="1133" alt="screen shot 2016-10-07 at 4 58 51 pm" src="https://cloud.githubusercontent.com/assets/4659476/19186221/76acef64-8caf-11e6-9c6d-b1c18f060541.png">

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

Note, the error report says you might want to try running `pod repo update`

**Comment by minhhieu052** [comment]
Thanks
