### ISSUE TITLE
pod lib lint: Must be in the root of the repo

### ISSUE THREAD

**Issue by tangzhentao** [CocoaPods/CocoaPods#6009]
# Report

## What did you do?

pod lib lint

## What did you expect to happen?

pass validation. no error.

## What happened instead?

have a error:
 - ERROR | [iOS] unknown: Encountered an unknown error (Must be in the root of the repo (/Users/tang/.cocoapods/repos/master), instead in /Volumes/Data/github/mypod/libpodtest.) during validation.

### Stack

```
   CocoaPods : 1.1.0.beta.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 876f60f96487c473b0b83e689259ac6a40c631f4
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/tangzhentao/libTest.git

**Comment by vinbhai4u** [comment]
same here 
did pod lib lint --no-clean --verbose

[!] CLImageViewPopup did not pass validation, due to 12 errors and 2 warnings.

# Project that demonstrates the issue
https://github.com/vinbhai4u/CLImageViewPopup

**Comment by orta** [comment]
Can you please test with 1.1.0.rc.3 we've made some chdir changes

**Comment by vinbhai4u** [comment]
@orta that worked

**Comment by benasher44** [comment]
CocoaPods 1.1.0.rc.3 is required when using Xcode 8. If this is still broken for you when testing with 1.1.0.rc.3, please file a new issue. Thanks!

**Comment by tangzhentao** [comment]
@vinbhai4u Could you tell me how to install CocoaPods 1.1.0.rc.3?
I downloaded 1.1.0.rc.3, but don't know how to intall.Thanks!

**Comment by vinbhai4u** [comment]
@tangzhentao `sudo gem update cocoapod --pre`
