### ISSUE TITLE
pod spec lint error

### ISSUE THREAD

**Issue by Insofan** [CocoaPods/CocoaPods#6012]
When I commit my framework to cocoapod encountered an error.I use Xcode 8 and swift 3, cocoapod version is 1.1.0.rc.2.How to fix it？

- ERROR | unknown: Encountered an unknown error (uninitialized constant REST::DisconnectedError) during validation.

**Comment by vinbhai4u** [comment]
same here

**Comment by orta** [comment]
Looks like you're having problems sending the Podspec to trunk, are you on a VPN that doesn't allow HTTPS?

**Comment by benasher44** [comment]
This looks very much like a connection issue that seems unrelated to CocoaPods. Going to close for now. If you're still experiencing this, please open a new issue and fill out the issue template. Thanks for filing!
