### ISSUE TITLE
Must be in the root of the repo when pod update 

### ISSUE THREAD

**Issue by ifgyong** [CocoaPods/CocoaPods#6013]
Pod::StandardError - Must be in the root of the repo (/Users/Jerry/.cocoapods/repos/master), instead in /Users/Jerry/Desktop/ios_afu/xiaoqu-ios.
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:403:in `ensure_in_repo!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:431:in `git_commit_hash'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `block in requires_update?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:31:in `requires_update?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/master_source.rb:14:in `update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:88:in `block (2 levels) in update'

**Comment by ifgyong** [comment]
when I run pod setup .it is ok.

**Comment by orta** [comment]
Please use the issue template, it's much harder to help you with that information - have you tried using the CocoaPods beta also?

**Comment by benasher44** [comment]
This has been fixed in recent 1.1.0 release candidates. Please update to CocoaPods 1.1.0.rc.3, and open a new issue if you're still experiencing this. Thanks for filing!
