### ISSUE TITLE
waring

### ISSUE THREAD

**Issue by ifgyong** [CocoaPods/CocoaPods#6014]
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:140: warning: Insecure world writable dir /Users/Jerry/Desktop in PATH, mode 040707

when I run something. always print this.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
