### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by DrBeak1** [CocoaPods/CocoaPods#6018]
# Report

## What did you do?
Installed [SocketIO](https://github.com/socketio/socket.io-client-swift/issues/535) cocoapod using `pod install`. I then import the module using `@import SocketIO` into the class where I will be using the module.

## What did you expect to happen?
The SocketIO module imports as expected into my project.

## What happened instead?
The SocketIO module is imported, builds, and runs correctly. However, when I make an edit to the class where the module is imported, I get an error message "Module SocketIO not found". It also sees any object defined in the SocketIO module as an `int`. Then if I cmd+s to save the class where I am `@import`ing the file, the error goes away. So the error appears after any modifications are made to the importing class.

## CocoaPods Environment

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 67c0f2953ec37c301338190aeea561b99e447550
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
use_frameworks!

def import_pods
    pod 'Socket.IO-Client-Swift', '8.0.2'

    pod 'React', :path => 'node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket', # needed for debugging # Add any other subspecs you want to use in your project
    'RCTImage',
    ]
end

target 'projectname' do
    import_pods
end

post_install do | installer |

    # disables bit code
    installer.pods_project.targets.each do |target|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end

        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
```
## Additional comments:
Initially I thought this was an issue related solely to SocketIO, however this has been happening with several other modules as well. Exact same behavior. [This thread](https://github.com/CocoaPods/CocoaPods/issues/4944) seems to elude to the same odd behavior, where saving the file removes the errors; however, it seems mostly directed towards separate builds. Though it is spot on to what I am seeing in terms of the error message. The biggest issue I have with this is that it blocks autocompletion of property and function names from within the module (as noted above it sees all objects declared in the module as an `int`). Building and running works fine; it's coding within the importing class that is a pain the butt.

Furthermore, I suspect that this has to do with the header and or framework search paths (as was the case with the above noted thread), but I cannot figure out what the correct paths are. I've also tried removing the pod from my project, reinstalling (pod install), cleaning the project, and deleting derived data. Nothing seems to work.

**Comment by DrBeak1** [comment]
Installed cocoapods 1.1.0.rc.3 today. Ran pod deintegrate, then reinstalled pods. Still no luck. Anyone have any insight here? This is killing me :^(

**Comment by DrBeak1** [comment]
I created a brand new project using xcode 8. integrated cocoapods. added a single module. everything worked fine. I figured this was something related to the transition from xcode 7 to xcode 8, but wasn't 100%. This test made me think so even more.

So I proceeded to deintegrate again (`pod deintegrate`), only this time I also went into the project and removed every line related to cocoapods in the project/target settings (not the code base). Afterwards I deleted the pod lock file and move the Podfile out of the project directory. Then I did `pod init`, opened the new Podfile and added each module in one-by-one. Tedious as hell, but in the end things were working again.

**Comment by dturnq** [comment]
Try updating your Swift version

<img width="674" alt="pods link" src="https://user-images.githubusercontent.com/10344343/39685867-4188cab0-517a-11e8-8217-065d7973b2ee.png">

<img width="611" alt="pods swift version" src="https://user-images.githubusercontent.com/10344343/39685865-41617780-517a-11e8-8d35-4c1d0cca9680.png">
