### ISSUE TITLE
xcodebuild: error: 'App.xcworkspace' does not exist.

### ISSUE THREAD

**Issue by zzgo** [CocoaPods/CocoaPods#6021]
*  I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I use `Xcode8`, `CocoaPods 1.1.0.beta2`. `macOS Sierra 10.12`.

I find a same promblem in stackoverflow [App.xcworkspace does not exists](http://stackoverflow.com/questions/39637123/cocoapods-app-xcworkspace-does-not-exists),

so I install cocoapods 1.1.0.beta.2 ,but it can't work with me.

## What did you do?
 Run `pod lib lint --no-clean --verbose`

## What did you expect to happen?
pass validation.

## What happened instead?
not pass validation.
show the info:
```
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

- NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

Pods workspace available at `/var/folders/wp/vmfq83md7lx2j2ds6p3ykw6r0000gn/T/CocoaPods/Lint/App.xcworkspace` for inspection.
```

## CocoaPods Environment
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5e18c677b52de4e63d3b01aa264714b9155939c3

### Installation Source

Executable Path: /usr/local/bin/pod

### Plugins

cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0

**Comment by DanToml** [comment]
This should be fixed in the latest `1.1.0.rc.3`, although depending on your project, you may also need to set the `FORK_XCODE_WRITING` environment variable.
