### ISSUE TITLE
Unable to Build Archive Using `xcodebuild`, References Pods Issue?

### ISSUE THREAD

**Issue by yorkepb** [CocoaPods/CocoaPods#6022]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ran xcodebuild on the command line to generate an archive

## What did you expect to happen?

Archive should be generated

## What happened instead?

I received the following error: 

```
** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/jenkins/Library/Developer/Xcode/DerivedData/***-fcrhcdienaqqbcfoyedkcpstctlp/Build/Intermediates/ArchiveIntermediates/***/IntermediateBuildFilesPath/***.build/Alpha-watchos/***\ Watch\ App\ Extension.build/Script-E421E66A19AAF683E3570147.sh
```

## CocoaPods Environment
```ruby
unless defined?(Bundler)
  print "\e[#{31}m[!] Please run `pod [install|update|…]` via `bundle exec pod [install|update|…]` instead.\e[0m\n"
  print "    See the project README for details.\n"
  exit!
end

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:nytm/ios-podspecs.git'

platform :ios, '9.0'

use_frameworks!

def testing_pods
  pod 'Quick'
  pod 'Nimble'
  pod 'Nimble-Snapshots', '~> 4.1.0'
end

target '***' do
  workspace '***'
  project '***'

  pod 'HockeySDK', '~> 4.0.1'
  pod 'SwiftGen', '~> 1.1.0'
  pod 'Reusable', '~> 2.3.0'
  pod 'SwiftyBeaver', '~> 0.6.5'
  pod 'KZFileWatchers', '~> 0.1.0'
  pod 'SideMenu', '~> 1.2.1'

 ... (other proprietary podfile details)
```

## Project that demonstrates the issue

The project itself is proprietary and I cannot send it, however if there are specific things you are looking for I can send them. I am mostly trying to figure out what would cause such and issue as I cannot seem to find any info on what is actually causing the problem.

**Comment by yorkepb** [comment]
NM Sorry it looks like this is a bug on our end, I am going to close this issue.

**Comment by TMSantos** [comment]
@yorkepb how you fixed this?
