### ISSUE TITLE
None of your spec sources contain a spec satisfying the dependency: CSVImporter (~> 1.3).

### ISSUE THREAD

**Issue by hellohelloye** [CocoaPods/CocoaPods#6023]
I met the following issue, I tried sudo gem install cocopods --pre and also pod repo update, no progress, any help would be appreciated. Thank you.

pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:

CSVImporter (~> 1.3) required by Podfile
CSVImporter (~> 1.3) required by Podfile
None of your spec sources contain a spec satisfying the dependency: CSVImporter (~> 1.3).

You have either:

out-of-date source repos which you can update with pod repo update.
mistyped the name or version.
not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, pod repo update does not happen on pod install by default.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

However, note the first line of the recommendations:

> out-of-date source repos which you can update with `pod repo update`.

Try that

**Comment by hellohelloye** [comment]
Thank you Orta, I fixed it by removing the version.

pod 'CSVImporter'    THEN pod install automatically detecting the suitable version, which is 1.2.0
