### ISSUE TITLE
1.1.0.rc.3 fails to lint Swift 2.2 podspec

### ISSUE THREAD

**Issue by BridgeTheGap** [CocoaPods/CocoaPods#6027]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod lib lint`

## What did you expect to happen?

The lint should succeed since I already pushed this same podspec to the trunk.

## What happened instead?

It spews an error, which using `--verbose` is further explained that `“Use Legacy Swift Language Version” (SWIFT_VERSION) ` needs to be set, when Xcode 7.3.1 doesn't even have that option.

Funny enough, I've already passed the lint when using up to 1.1.0.rc.2 and pushed the same podspec to the trunk. It only stopped working since I updated to rc3, but now, even though I've removed rc3 and went back to rc2, still won't pass.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/josh/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5c3c6251dd324624ac1cef3e5abaa6acfd30074e
```

### Installation Source

```
Executable Path: /Users/josh/.rbenv/versions/2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.0.beta.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

This is happening regardless of the project. All Swift 2.2 projects are affected.

**Comment by benasher44** [comment]
Based on your description, it sounds like you're expecting to be using Xcode 7.3.1, but `pod env` shows that you're using Xcode 8.0. You can verify this locally by running `xcodebuild -version`.

**Comment by BridgeTheGap** [comment]
I'm actually using both. 

Let me show you this screenshot, so you can have a better understanding.

Nothing from by Xcode environment changed; i.e. I was using both Xcode 7.3.1 and 8.0. 
In the screenshot, I canceled `pod trunk push` because I updated cocoapods during the push.
In any case, you can clearly see the lint succeeded, and was indeed pushed.

<img width="1136" alt="screen shot 2016-10-12 at 12 16 54 pm" src="https://cloud.githubusercontent.com/assets/12147008/19296783/9323cee2-9079-11e6-82a0-65cfb8bbf919.png">

This is what happened right after updating to rc3.
<img width="807" alt="screen shot 2016-10-12 at 12 19 36 pm" src="https://cloud.githubusercontent.com/assets/12147008/19296827/fbeaad60-9079-11e6-9e3e-6e7b2ee34508.png">

**Comment by BridgeTheGap** [comment]
Another interesting thing is I used another iMac in my office that I never updated to rc3, and I get the same error. Maybe it has nothing to do with rc3 but why did it work before?

**Comment by BridgeTheGap** [comment]
Sorry about the hassle.
I passed validation and pushed by using `sudo xcode-select --switch (path_to_Xcode7.3.1)` to use Xcode 7.3.1.
I don't understand why in the first image, lint worked because I never used that command before.

Anyways, if anyone encounters a similar issue, I guess people could be advised to use the above-mentioned command.

**Comment by benasher44** [comment]
Glad you got it resolved! Thanks!
