### ISSUE TITLE
Could not find a valid gem 'cocoapods'

### ISSUE THREAD

**Issue by rlaferla** [CocoaPods/CocoaPods#6030]
# Report

## What did you do?

$ sudo gem install cocoapods --pre

## What did you expect to happen?

Update CocoaPods

## What happened instead?

ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)

## CocoaPods Environment

[31m[!] Unknown arguments: env[0m

CocoaPods, the Objective-C library package manager.

Commands:

    * [32mhelp        [0m   Show help for the given command.
    * [32minit        [0m   Generate a Podfile for the current directory.
    - [32minstall     [0m   Install project dependencies
    * [32mipc         [0m   Inter-process communication
    * [32mlib         [0m   Develop pods
    * [32mlist        [0m   List pods
    * [32moutdated    [0m   Show outdated project dependencies
    * [32mpodfile-info[0m   Shows information on installed Pods.
    * [32mpush        [0m   Push new specifications to a spec-repo
    * [32mrepo        [0m   Manage spec-repositories
    * [32msearch      [0m   Searches for pods
    * [32msetup       [0m   Setup the CocoaPods environment
    * [32mspec        [0m   Manage pod specs
    * [32mupdate      [0m   Update outdated project dependencies

Options:

    --silent     Show nothing
    --version    Show the version of CocoaPods
    --no-color   Show output without color
    --verbose    Show more debugging information
    --help       Show help banner of specified command

## Project that demonstrates the issue

n/a

**Comment by orta** [comment]
Looks like you're having problems connecting to Rubygems -  I'd advise looking for issues around that:

```
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)
```

Which isn't a CocoaPods bug I'm afraid, so I'm closing this.

**Comment by michael-mckenna** [comment]
To anyone who runs across this, I had to set the source to be my company's internal facing gem repo
`sudo gem install cocoapods --source <our internal url>`

**Comment by zachariuz** [comment]
@michael-mckenna as I’m just using it for personal use , what url would I need to use
