### ISSUE TITLE
[!] An unexpected version directory `Classes` was encountered for the

### ISSUE THREAD

**Issue by IphoneCoder** [CocoaPods/CocoaPods#6035]
# Report

## What did you do?

create private cocoapods

pod repo push OSChinaSpecs  BtimeVideoLibrary.podspec

## What did you expect to happen?

below local repos,new repo created sucess

## What happened instead?

all project files has push in the repo,like this 

![image](https://cloud.githubusercontent.com/assets/8368850/19347942/0b7a3980-917e-11e6-891d-8a06a5da75b3.png)

## podspec

<pre><code>
#
# Be sure to run `pod lib lint BtimeVideoLibrary.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = 'BtimeVideoLibrary'
  s.version          = '0.1.2'
  s.summary          = 'xxxxxxxxxxxxx'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC

  s.homepage         = 'https://www.baidu.com/BtimeVideoLibrary'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'wangyaqiang' => 'wangyaqiang@qq.com' }
  s.source           = { :git => 'https://git.oschina.net/littlecodergitxxx/PrivateCocoapods.git', :tag => s.version }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.ios.deployment_target = '8.0'

  s.source_files = 'BtimeVideoLibrary/Classes/**/*'
  
  # s.resource_bundles = {
  #   'BtimeVideoLibrary' => ['BtimeVideoLibrary/Assets/*.png']
  # }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  # s.dependency 'AFNetworking', '~> 2.3'
end
</code></pre>

# When use
## podfile
<pre><code>
platform :ios, '8.0'
#inhibit_all_warnings!
use_frameworks!
source 'https://git.oschina.net/littlecodergitxxx/PrivateCocoapods.git'
target 'PodTest' do
  pod 'BtimeVideoLibrary'
end
</code></pre>

## error image

![image](https://cloud.githubusercontent.com/assets/8368850/19348166/20c39196-917f-11e6-84b4-f8d5e961466a.png)

**Comment by orta** [comment]
Are you using Xcode 8, and not the `1.1.0.rc.3`?

**Comment by IphoneCoder** [comment]
@orta ,yes, i using Xcode 8 and the pod version 1.0.1 ,must 1.1.0.rc.3 ?

**Comment by orta** [comment]
Yes, Xcode 8 breaks in 1.0.x - that should fix it 👍

**Comment by gzncland** [comment]
@orta the same exception with pod --version `1.1.1`
that's my operation logs:

```
 $ pod repo add Foobar https://git.foo.bar/foobar/Foobar.git
 $ pod lib create Foobar
 //...
 git add / remote add / push / tag operations
 //...
```

and override `.podspec` file to:

```
s.source           = { :git => 'https://git.foo.bar/foobar/Foobar.git', :tag => s.version.to_s }
s.requires_arc = true
s.module_name = 'Foo'
```

```
 $ pod lib lint
 $ pod spec lint
 $ pod repo push Foo Foo.podspec
```

Finally, create a xcodeproj and use podfile:

```
source 'https://git.foo.bar/foobar/Foobar.git'
platform :ios, ‘7.0’
target 'test' do
pod 'Foo'
end
```

```
 $ pod install
```

the Terminal shows:

```
Analyzing dependencies
[!] An unexpected version directory `Assets` was encountered for the `/Users/Zapper/.cocoapods/repos/LXFramework/LXFramework` Pod in the `LXFramework` repository.
```

remove the `Assets` folder, retry:

```
Analyzing dependencies
[!] An unexpected version directory `Classes` was encountered for the `/Users/Zapper/.cocoapods/repos/LXFramework/LXFramework` Pod in the `LXFramework` repository.
```

**Comment by gzncland** [comment]
I changed `s.source_files`:
`/Foobar/Foobar/Classes` to `/Foobar/Pod/Classes`.
work.

**Comment by ixp9891** [comment]
@orta I using xcode8(8A218a) and pod version 1.1.0.rc3 but have same problem ,how should I do?

**Comment by benasher44** [comment]
Can you show the directory tree for `/Users/Zapper/.cocoapods/repos/Foobar`?

**Comment by rafaelnobrepd** [comment]
I experienced this problem when working with a private pod's repo that was its own improvised Specs repo. In the <lib-name> dir, it had entries for its podspec's versions 1.0 , 1.1, etc, along with the Classes and Assets folder of its actual source. Pod install rejected the unexpected directory names.

**Comment by keshiim** [comment]
@garnett 你的路径是在spec文件里做的修改吗？ pod lib lint能过？

**Comment by SanyasiraoM** [comment]
@gzncland  Did you solve it?

**Comment by kevinkang88** [comment]
still having same issues

**Comment by moekyo** [comment]
delete Classes and Assets folder

**Comment by cslmark** [comment]
I encountered the same problem in my private pod. What should I do, I am so confused! Looking for reply! somebody
![image](https://user-images.githubusercontent.com/13198159/42277410-df498c58-7fc9-11e8-9be6-cbaccad0f3b9.png)
![image](https://user-images.githubusercontent.com/13198159/42277520-3363f788-7fca-11e8-8111-2da56a00cf09.png)
I folder tree is showed as blow.
![image](https://user-images.githubusercontent.com/13198159/42277495-233f46f0-7fca-11e8-8032-127a5c951f5d.png)

**Comment by sathishvgs** [comment]
@cslmark By removing Assets and Classes worked for me. I'm not sure how its working after removed the both. Can anyone give brief explanation about it.

**Comment by ChengRuipeng** [comment]
maybe you should create a folder named 'Pod' and put classes and asssets into it

**Comment by nazywamsiepawel** [comment]
+1, same issue here

**Comment by xiaoxu1234** [comment]
+1, same issue here

**Comment by samuelandkevin** [comment]
+1, same issue here

**Comment by PandaWX** [comment]
+1, same issue here

**Comment by PandaWX** [comment]
maybe, your XXX.podspec corresponding git is wrong

> # Report
> ## What did you do?
> create private cocoapods
> 
> pod repo push OSChinaSpecs BtimeVideoLibrary.podspec
> 
> ## What did you expect to happen?
> below local repos,new repo created sucess
> 
> ## What happened instead?
> all project files has push in the repo,like this
> 
> ![image](https://cloud.githubusercontent.com/assets/8368850/19347942/0b7a3980-917e-11e6-891d-8a06a5da75b3.png)
> 
> ## CocoaPods Environment
> ## podspec
> ```
> 
> #
> # Be sure to run `pod lib lint BtimeVideoLibrary.podspec' to ensure this is a
> # valid spec before submitting.
> #
> # Any lines starting with a # are optional, but their use is encouraged
> # To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
> #
> 
> Pod::Spec.new do |s|
>   s.name             = 'BtimeVideoLibrary'
>   s.version          = '0.1.2'
>   s.summary          = 'xxxxxxxxxxxxx'
> 
> # This description is used to generate tags and improve search results.
> #   * Think: What does it do? Why did you write it? What is the focus?
> #   * Try to keep it short, snappy and to the point.
> #   * Write the description between the DESC delimiters below.
> #   * Finally, don't worry about the indent, CocoaPods strips it!
> 
>   s.description      = <<-DESC
> TODO: Add long description of the pod here.
>                        DESC
> 
>   s.homepage         = 'https://www.baidu.com/BtimeVideoLibrary'
>   # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
>   s.license          = { :type => 'MIT', :file => 'LICENSE' }
>   s.author           = { 'wangyaqiang' => 'wangyaqiang@qq.com' }
>   s.source           = { :git => 'https://git.oschina.net/littlecodergitxxx/PrivateCocoapods.git', :tag => s.version }
>   # s.social_media_url = 'https://twitter.com/'
> 
>   s.ios.deployment_target = '8.0'
> 
>   s.source_files = 'BtimeVideoLibrary/Classes/**/*'
>   
>   # s.resource_bundles = {
>   #   'BtimeVideoLibrary' => ['BtimeVideoLibrary/Assets/*.png']
>   # }
> 
>   # s.public_header_files = 'Pod/Classes/**/*.h'
>   # s.frameworks = 'UIKit', 'MapKit'
>   # s.dependency 'AFNetworking', '~> 2.3'
> end
> ```
> 
> # When use
> ## podfile
> ```
> 
> platform :ios, '8.0'
> #inhibit_all_warnings!
> use_frameworks!
> source 'https://git.oschina.net/littlecodergitxxx/PrivateCocoapods.git'
> target 'PodTest' do
>   pod 'BtimeVideoLibrary'
> end
> ```
> 
> ## error image
> ![image](https://cloud.githubusercontent.com/assets/8368850/19348166/20c39196-917f-11e6-84b4-f8d5e961466a.png)

1. to '~/.cocoapods/' , Check your repos
2.in profile,  maybe....You provide the 'source' is wrong

**Comment by wzq11015219** [comment]
pod 文件里是 specs的git地址，不是code的git地址！

**Comment by Rj707** [comment]
No solution was provided, then how the issue is marked **CLOSED**!!!!
