### ISSUE TITLE
Target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by k06a** [CocoaPods/CocoaPods#6036]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

`pod lib lint --private --verbose`
## What did you expect to happen?

Verify my podspec with following dependencies:

```
s.dependency 'RuntimeRoutines', '~> 0.3'
s.dependency 'PLCrashReporter', '~> 1.2'
s.dependency 'libMachO', '~> 0.1'
```
## What happened instead?

> ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/b0/cqvfzy9j3h33dsb342j6n9dh0000gr/T/CocoaPods/Lint/Pods/PLCrashReporter/iOS Framework/CrashReporter.framework)
### Stack

```
   CocoaPods : 1.1.0.rc.3
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/k06a/.rvm/rubies/ruby-2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6d12506e22aeee67fd93e5a2560adebcc0fb3319
```
### Installation Source

```
Executable Path: /Users/k06a/.rvm/gems/ruby-2.2.5/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.0.beta.1
cocoapods-try         : 1.1.0
```

**Comment by k06a** [comment]
Used this code in podfile to avoid error:
```

**Comment by k06a** [comment]
Found similar problem https://github.com/CocoaPods/CocoaPods/issues/6028

**Comment by k06a** [comment]
Looks like I am not able to push my new library to CocoaPods trunk, because of PLCrashReporter dependency.

**Comment by orta** [comment]
You probably want to look at the `--use-libraries` argument - this may pass, the error message may indeed be legitimate but only for framework based pods

**Comment by k06a** [comment]
@orta thanks, that works fine!

**Comment by k06a** [comment]
Still fave problems with PLCrashReporter dependency. Both --use-frameworks and --use-libraries flags produces error while `pod lib lint` step:
```
 -> PuppyWatchdog (0.1.0)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  /Users/k06a/Projects/Searchie/PuppyWatchdog/PuppyWatchdog/Classes/MLWPuppyWatchdog.m:24:9: fatal error: 'CrashReporter/CrashReporter.h' file not found
```

Here is the project: https://github.com/ML-Works/PuppyWatchdog

**Comment by k06a** [comment]
`--verbose` flag gives me hint:
```
-> Installing PLCrashReporter (1.2.0)
  > Copying PLCrashReporter from `/Users/k06a/Library/Caches/CocoaPods/Pods/Release/PLCrashReporter/1.2.0-16927` to
  `../../../../../private/var/folders/b0/cqvfzy9j3h33dsb342j6n9dh0000gr/T/CocoaPods/Lint/Pods/PLCrashReporter`
```

```
$ ls -l /Users/k06a/Library/Caches/CocoaPods/Pods/Release/PLCrashReporter/1.2.0-16927
-rw-r--r--  1 k06a  staff  2320 19 окт 22:50 LICENSE.txt
drwxr-xr-x  5 k06a  staff   170 19 окт 22:57 Mac OS X Framework
drwxr-xr-x  4 k06a  staff   136 19 окт 22:57 iOS Framework
```

```
$ ls -l ../../../../../private/var/folders/b0/cqvfzy9j3h33dsb342j6n9dh0000gr/T/CocoaPods/Lint/Pods/PLCrashReporter
-rw-r--r--  1 k06a  staff  2320 19 окт 22:58 LICENSE.txt
```

**Comment by k06a** [comment]
Looks like `iOS Framework` directory is really missing. Can `pod lib lint` misinterpret PLCrashReportper.podspec @orta?

**Comment by DanToml** [comment]
Superseded by https://github.com/CocoaPods/CocoaPods/issues/6070
