### ISSUE TITLE
CocoaPods should treat Xcode project target whose `IPHONEOS_DEPLOYMENT_TARGET` is not setted as latest iOS version.

### ISSUE THREAD

**Issue by ainopara** [CocoaPods/CocoaPods#6038]
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`
Podfile include a local pod whose podspec indicate it's minimum deployment target is iOS 8.0.
```
 s.platform     = :ios, "8.0"
```
My project did not set `IPHONEOS_DEPLOYMENT_TARGET` in all levels (project level and target level) . As a result Xcode 8.0 shows it will be `10.0` by default.

If I set either project level or target level `IPHONEOS_DEPLOYMENT_TARGET` to `8.0`, CocoaPods will work fine.
## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?
```
Specs satisfying the `NameOfThePod` dependency were found, but they required a higher minimum deployment target.
```
### Stack

```
   CocoaPods : 1.1.0.rc.3
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 9c305e16a057d3062373aaaa1d8584bbd764fa55
               master - https://github.com/CocoaPods/Specs.git @ 15692a9cdf32da3efb39efac71aa331ba3dea569
               twilio - https://github.com/twilio/cocoapod-specs @ 7c74edb7072c3aad9b0803286d7a238c227cecc9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.0
cocoapods-check       : 1.0.0
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 1.6.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.0.beta.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

I will add a demo project soon.

**Comment by orta** [comment]
You could use [deployment_target](https://guides.cocoapods.org/syntax/podspec.html#deployment_target) instead?

**Comment by ainopara** [comment]
```
s.ios.deployment_target = '8.0'
```
Get the same result.
```
Specs satisfying the `NameOfThePod` dependency were found, but they required a higher minimum deployment target.
```

**Comment by orta** [comment]
The current values for a Podfile's platform [are](https://guides.cocoapods.org/syntax/podfile.html#platform):

> CocoaPods provides a default deployment target if one is not specified. The current default values are 4.3 for iOS, 10.6 for OS X, 9.0 for tvOS and 2.0 for watchOS.

So it won't take Xcode's into account, you'll need to add `platform :ios, '10.0'` to your Podfile.

**Comment by orta** [comment]
If CocoaPods moved those with Xcode, it would not be backwards compatible with older projects, so we keep them as constants.

**Comment by ainopara** [comment]
Got it. Thank you for your reply. 💯
