### ISSUE TITLE
vendored_frameworks have the c++ code

### ISSUE THREAD

**Issue by IphoneCoder** [CocoaPods/CocoaPods#6046]
# Report

## What did you do?

in my project , the vendor  frameworks which  use the c++ code

## What did you expect to happen?

generate the repo success

## What happened instead?

the c++ code compile error 

## CocoaPods Environment

i config the podspec

s.library = 'c++'
s.pod_target_xcconfig = {
       'CLANG_CXX_LANGUAGE_STANDARD' => 'c++11',
       'CLANG_CXX_LIBRARY' => 'libc++',
       'ENABLE_BITCODE' => 'NO'
  }

![image](https://cloud.githubusercontent.com/assets/8368850/19434309/3c1015a8-9497-11e6-8ac0-0c279ec380fb.png)

## Project that demonstrates the issue

the c++ pointer method error 

![image](https://cloud.githubusercontent.com/assets/8368850/19434346/6f823eca-9497-11e6-8864-3d17d0049613.png)

**Comment by orta** [comment]
Can you please provide an example project we can download and run, and show us how you think it should be please?

**Comment by IphoneCoder** [comment]
@orta ,Half a moment，thanks

**Comment by orta** [comment]
Also, have you tried with the CocoaPods 1.1.0 beta?

**Comment by IphoneCoder** [comment]
@orta ，i find the framework which use the c++ reference too much framework，it is hard to create a demo ,year ,i use the 1.1.0.rc.2

**Comment by IphoneCoder** [comment]
@orta ,i get some method through https://github.com/CocoaPods/CocoaPods/issues/5152,the console like it 

![image](https://cloud.githubusercontent.com/assets/8368850/19435781/1a4f48f0-949f-11e6-91ae-420accec145d.png)

**Comment by IphoneCoder** [comment]
@orta ,i create a demo to show the problem

https://github.com/IphoneCoder/DeviceOnlyDemo

expect you help,thanks

**Comment by benasher44** [comment]
I believe this is a combo of #5152 and/or #5854. Going to close this one, but please feel free to add any additional information to those 2 other issues. Thanks for filing!
