### ISSUE TITLE
How to solve overlapping pods dependencies between app and framework. 

### ISSUE THREAD

**Issue by tonyxiao** [CocoaPods/CocoaPods#605]
Currently I'm building a app which uses a framework. But the app and the framework has overlapping pods dependencies. So when I link the app against the framework, I get a ton of compiler warnings and unexpected behavior, such as 

```

objc[33543]: Class RKMutableBlockDictionaryBlockValue is implemented in both /Users/Tony/Library/Developer/Xcode/DerivedData/Proj-chuovrchxcwrraffvylnvroalekh/Build/Products/Debug/FileSystem.framework/Versions/A/FileSystem and /Users/Tony/Library/Developer/Xcode/DerivedData/Proj-chuovrchxcwrraffvylnvroalekh/Build/Products/Debug/MyProj.app/Contents/MacOS/MyProj. One of the two will be used. Which one is undefined.
objc[33543]: Class RKMutableBlockDictionary is implemented in both /Users/Tony/Library/Developer/Xcode/DerivedData/Proj-chuovrchxcwrraffvylnvroalekh/Build/Products/Debug/FileSystem.framework/Versions/A/FileSystem and /Users/Tony/Library/Developer/Xcode/DerivedData/Proj-chuovrchxcwrraffvylnvroalekh/Build/Products/Debug/MyProj.app/Contents/MacOS/MyProj. One of the two will be used. Which one is undefined.
objc[33543]: Class RKOrderedDictionary is implemented in both /Users/Tony/Library/Developer/Xcode/DerivedData/Proj-chuovrchxcwrraffvylnvroalekh/Build/Products/Debug/FileSystem.framework/Versions/A/FileSystem and /Users/Tony/Library/Developer/Xcode/DerivedData/Proj-chuovrchxcwrraffvylnvroalekh/Build/Products/Debug/MyProj.app/Contents/MacOS/MyProj. One of the two will be used. Which one is undefined.

```

What's the correct way to solve this problem?

**Comment by Vampire7** [comment]
@tonyxiao  Hello,I met the same problem with you. Could you tell me how do you solve？

**Comment by JonathanBouaziz** [comment]
Hey guys, I'm also encountering the same issue. Is there any solution using the latest version of CocoaPods?

**Comment by orta** [comment]
Check out https://github.com/CocoaPods/cocoapods-packager

**Comment by JonathanBouaziz** [comment]
Thanks for the link @orta. Please correct me if I'm wrong but that doesn't seem to provide a suitable solution for the problem here.

> This plugin is for CocoaPods developers, who need to distribute their Pods not only via CocoaPods, but also as frameworks or static libraries for people who do not use Pods.

Whereas here we're on the app developer side who's going to include the pods. I believe that [this post](http://stackoverflow.com/questions/27727455/class-x-is-implemented-in-both-framework-and-application-one-of-the-two-will) explains the problem a little better by doing this schema:
```
CoolPod -> MyFramework \
                        MyApplication
               CoolPod /
```

**Comment by orta** [comment]
I hear that the next 1.1 beta will support linking pods to a framework, so I think this will be possible i the next release, but isn't right now.

**Comment by benasher44** [comment]
@JonathanBouaziz is MyFramework actually your framework? Or is it a library you got from a 3rd party?

- If it's yours, I recommend adding this target to your Podfile and defining its dependencies there. The next 1.1.0 beta will have improved support for this.
- If it's not yours, I recommend defining a podspec for it that defines its dependencies. Better yet, go back to the vendor and ask them to define one :)

**Comment by JonathanBouaziz** [comment]
@benasher44 it is my framework, the workspace is as followed:
```
- Workspace
-- Project#1: Main
--- Reference to MyFramework (for target dependencies)
-- Project#2: MyFramework
-- Project#3: Pods
```
And in the Podfile, each target of each project is being assigned its respective required pods. Does that make sense?

**Comment by benasher44** [comment]
@JonathanBouaziz great! Then adding a target for MyFramework to your Podfile like so:
```
target 'MyFramework' do
  project 'Project2'
  // pod deps go here
end
```
I encourage you to try this using CocoaPods master, and let us know how it goes!

**Comment by JonathanBouaziz** [comment]
@benasher44 that's already what's happening:
```
inhibit_all_warnings!
use_frameworks!
workspace 'Some.xcworkspace'

# ========================
# Pods
#
def basic_pods
    
    pod 'AFNetworking'
    pod 'JSONModel'
    pod 'CocoaLumberjack'
end

[...]

# ========================
# Frameworks
#
def shared_ios_pods
    platform :ios, '8.0'
    
    pod 'SDWebImage/WebP'
    pod 'GoogleAnalytics'
end
def shared_tvos_pods
    platform :tvos, '9.0'
    
    pod 'SDWebImage/WebP'
end
targets = [ 'MyFramework_iOS', 'MyFramework_tvOS']
targets.each do |target_name|
    target target_name do
        project 'MyFramework/MyFramework.xcodeproj'
        
        if target_name.end_with? "iOS"
            shared_ios_pods
            
        elsif target_name.end_with? "tvOS"
            shared_tvos_pods
        end
        
        
        basic_pods
    end
end
```
What else is there to do?

That aside, will it be / is it possible to access the MyFramework pods in the Main project? Like embedding `AFNetworking` into the framework and accessing it from any target that's embedding it.

**Comment by benasher44** [comment]
Yep! In 1.1.0, it recognizes that frameworks are embedded somewhere, and it copies the pods to the places where the framework is embedded, so then you shouldn't have duplicate symbol issues.

On a side note, I recommend reformatting your Podfile for CocoaPods 1.0 target inheritance like this:
```
inhibit_all_warnings!
use_frameworks!
workspace 'Some.xcworkspace'

pod 'AFNetworking'
pod 'JSONModel'
pod 'CocoaLumberjack'

abstract_target 'MyFrameworks' do
  project 'MyFramework/MyFramework.xcodeproj'
  pod 'SDWebImage/WebP'
  target 'MyFramework_iOS' do
    platform :ios, '8.0'
  
    pod 'GoogleAnalytics'
  end

  target 'MyFramework_tvOS'  do
    platform :tvos, '9.0'
  end
end
```

**Comment by JonathanBouaziz** [comment]
Great news then!💃 Does the current beta does the job too?

Thanks for the tip!

**Comment by benasher44** [comment]
It does, but it has a bug related to framework targets being in sub-projects, which your project would likely reproduce. This is fixed on master, and the fix will be in an upcoming beta. You can try using CocoaPods master, if you want to try it out before the next beta comes out.

**Comment by JonathanBouaziz** [comment]
Got it! Will do then, thanks a bunch.

**Comment by benasher44** [comment]
@JonathanBouaziz 1.1.0.beta.2 is out! Please give it a try and let us know how it goes!

**Comment by loryhuz** [comment]
Hi, I've the same issue with cocoa pod 1.3.1 and Xcode 9.0.

I use a single Xcode project with one app target and another target for my own framework.
But I have a tons of these errors, and the app crash at launching:

`Class AKFCodeVerifyingViewController is implemented in both /Users/loryhuz/Library/Developer/Xcode/DerivedData/BabySittor-ctukdmnmprqalsfilltzzuxoahgb/Build/Products/Debug-iphonesimulator/BabysittorKit.framework/BabysittorKit (0x112312db0) and /Users/loryhuz/Library/Developer/CoreSimulator/Devices/F0DA8FC5-8D1C-4E46-B6C6-2622261971DC/data/Containers/Bundle/Application/46924134-0A79-4FA0-8BFD-D5D4B19DCECE/BabySittor.app/BabySittor (0x10a934838). One of the two will be used. Which one is undefined.`

I tried the config @benasher44 mentionned:

`platform :ios, '9.0'
use_frameworks!

workspace 'BabySittor.xcworkspace'

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

def app_pods
    pod 'PhoneNumberKit', '~> 2.0'
end

def main_pods
    pod 'ObjectMapper', '~> 3.0'
    pod 'Moya'
    pod "PromiseKit", "~> 4.0"
    pod 'Bolts'
    pod 'FBSDKCoreKit' 
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'RealmSwift'
    pod 'AWSS3'
    pod 'AccountKit'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Fabric'
    pod 'Crashlytics'
end


abstract_target 'BabysittorProjects' do
    project '../BabySittor/BabySittor.xcodeproj'
    main_pods

    target 'BabySittor' do
        app_pods
    end

    target 'BabysittorKit' do
        target 'BabysittorKitTests' do
            inherit! :search_paths
            testing_pods
        end
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end`

**Comment by anieduard** [comment]
Did you manage to solve this?

**Comment by loryhuz** [comment]
@anieduard yes, see this thread https://github.com/CocoaPods/CocoaPods/issues/7126, there is a workaround

**Comment by anieduard** [comment]
Thanks a lot!
