### ISSUE TITLE
Cocoapods Acknowledgements - Is it possible to skip licenses of some libraries?

### ISSUE THREAD

**Issue by adongarwar** [CocoaPods/CocoaPods#6050]
I have a podfile pointing to certain git repos. One of them is my organization specific private repo and i want to skip its license details to be reflected in Acknowledgements. Please help how to achieve this. My enviornment is XCODE 8 and swift 3. Thanks in advance.

**Comment by benasher44** [comment]
As far as I know there is no way to do this. What specifically is wrong with the current implementation?

**Comment by b-ray** [comment]
We're using [this component](https://github.com/y310/cocoapods-ack_filter) to achieve this, especially [this fork](https://github.com/endowzoner/cocoapods-ack_filter) which is also compatible with CocoaPods > 1.0.0 and lets you specify a `filterfile`.

**Comment by benasher44** [comment]
Ah cool sounds like there's a good plugin to help out with this. Going to close. Thanks for filing!

**Comment by Brett-Best** [comment]
https://github.com/CocoaPods/cocoapods-acknowledgements

This should work:
`plugin 'cocoapods-acknowledgements', :settings_bundle => true, :exclude => ['PrivateKit', 'SecretLib']`

**Comment by winkelsdorf** [comment]
Sidenote: This does not help with the newly generated markdown. ```cocoapods-acknowledgements``` plugin only handles ```plist``` generation.
