### ISSUE TITLE
vendored_frameworks device-only   missing required architecture i386

### ISSUE THREAD

**Issue by IphoneCoder** [CocoaPods/CocoaPods#6051]
# Report
## What did you do?
the  vendored_frameworks  device-only

## What did you expect to happen?

repo success

## What happened instead?

the frameworks have the warning,and when i use --allow-warnings no work

## CocoaPods Environment

Spec like it:
![image](https://cloud.githubusercontent.com/assets/8368850/19468575/b11c1c0e-9549-11e6-9871-9ac255ed8035.png)

## Project that demonstrates the issue

![image](https://cloud.githubusercontent.com/assets/8368850/19468658/40a8528e-954a-11e6-9229-11b303dad931.png)

**Comment by IphoneCoder** [comment]
hello everyone ,i create a demo to show the problem

https://github.com/IphoneCoder/DeviceOnlyDemo

expect you help,thanks

**Comment by benasher44** [comment]
This looks like a dup of #5854. Going to close this one in favor of that one, but please feel free to add any new information to the other issue. Thanks for filing!
