### ISSUE TITLE
Clarification on Acknowlegements handling, here: exclude debug configuration & generate markdown

### ISSUE THREAD

**Issue by winkelsdorf** [CocoaPods/CocoaPods#6056]
I am aware that this feature request and discussion came up repeatingly, but the current situation probably still requires a bit of clarification.

Especially now in the transition of 1) CocoaPods ```1.1.0.rc``` and 2) the ```cocoapods-acknowledgements``` plugin.

If I understood the issue archive correctly the preferred way of handling the acknowledgements integration is to use the new aforementioned plugin. This is not reflected in the wiki or blog yet, but looks like it's the official way.

Now in some recent version CocoaPods core added the generation of markdown for the acknowledgements automatically, which is btw very convenient for a well designed UI.

**But:** This in turn is not reflected by the ```cocoapods-acknowdlegements``` plugin which only generates ```plist```.

So the "old", "deprecated" way is able to do more than the newly suggested way? Or is the plugin only meant to replace the plist generation?

The reason for the question (a.k.a. "what I want to achieve"): I would like to _exclude_ two pods' licenses, namely the SimulatorStatusBar and Reveal. _And_ have a markdown file generated.

Consider the following example pod file:
```shell
platform :ios, '9.0'
use_frameworks!

target :myProject do
    pod 'SimulatorStatusMagic', :configurations => ['Debug']
    pod 'Reveal-SDK', :configurations => ['Debug']
    pod 'Fabric'
    pod 'Crashlytics'
end
```

Excluding them with ```cococapods-acknowledgements``` is a no-brainer. Just use the ```:exclude``` parameter.

But excluding them for the markdown is complicated as of now. Manual parsing or using thirdparty plugins (like ```ack-filter``` mentioned in the references) is something I would like to avoid if possible.

Would it be possible to either

1) let ```cocoapods-acknowledgements``` generate markdown, too?
or
2) exclude ```:configurations => ['Debug']``` licenses automatically?

I would have expected CocoaPods to be able to omit debug-only configuration licenses automatically when generating the acknowledgements, which would make a lot of sense to me to _not_ include them.

-- Frederik

References: #1924 and #2465

**Comment by orta** [comment]
I know cocoapods-acknowledgements has markdown parsing in it - https://github.com/CocoaPods/cocoapods-acknowledgements/pull/15 

I'd recommend making improvements to it, so that it covers your use-case, one day we're going to remove the acknowledgements from CocoaPods and have it in the plugin.

**Comment by winkelsdorf** [comment]
Thanks for the clarification on what's the way to go in future (= using the plugin).

Basically right, somebody submitted a PR and it uses ```redcarpet``` now to parse the markdown in each pod description. But as of now this is only inbound parsing.

From what I can tell the whole plugin would require a rewrite of it's core method (the registered hook) in https://github.com/CocoaPods/cocoapods-acknowledgements/blob/master/lib/cocoapods_acknowledgements.rb.

That implementation differs a lot from the current spec/unit/generator implementation I see in the main repo and is above my ruby knowledge.

Closing this issue here and keeping the feature req open in the plugin repo, that's where it belongs.
