### ISSUE TITLE
Documentation for install! keys needed

### ISSUE THREAD

**Issue by jeffrwon** [CocoaPods/CocoaPods#6057]
# Report 🌈
Could we have documentation for what the `install!` keys do?
https://guides.cocoapods.org/syntax/podfile.html#install_bang

I could look through the source and do it myself but I might not understand the full implications of it and perhaps whoever contributed each of these keys could provide the context or their intentions behind it. Thanks!

## What did you do?

ℹ Please replace this with what you did.   **Not applicable.**

ℹ Please replace this with what you expected to happen.  **Not applicable.**

ℹ Please replace this with of what happened instead.  **Not applicable.**

ℹ Please replace this with the output of `pod env`. **Not applicable.**

ℹ Please link to a project we can download that reproduces the issue.  **Not applicable.**

**Comment by orta** [comment]
Can you please raise this on the CocoaPods guides repo instead, or even better - send us a PR adding that documentation 👍
