### ISSUE TITLE
Could not install CocoaPods 1.1.1

### ISSUE THREAD

**Issue by brandtdaniels** [CocoaPods/CocoaPods#6060]
# Report

## What did you do?

ℹ Please replace this with what you did.  
Ran `gem install cocoapods`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
Install CocoaPods 1.1.1 correctly

## What happened instead?

ℹ Please replace this with of what happened instead.  
$ gem install cocoapods
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/bdaniels/.rbenv/versions/2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 28250fedbb639d96564254314248b68124ce1341
```

### Installation Source

```
Executable Path: /Users/bdaniels/.rbenv/versions/2.1.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.0
cocoapods-dependencies : 0.5.2
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.0.0
```

### Podfile

Would rather keep the Podfile private.

**Comment by lightbow** [comment]
This is what I get when attempting to visit rubygems.org in Safari:

<img width="750" alt="screen shot 2016-10-20 at 3 32 31 pm" src="https://cloud.githubusercontent.com/assets/5239751/19574986/827dd3be-96da-11e6-8f00-699e612342f4.png">

**Comment by lightbow** [comment]
http://guides.rubygems.org/ssl-certificate-update/

> If you reached this page, means you’ve hit this SSL error when trying to pull updates from RubyGems: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
> This error is produced by changes in rubygems.org infrastructure, you can read the background below. Please follow the instructions below to update your rubygems.

Your report indicates you're using RubyGems 2.4.5. I'm guessing everything will be fine once you update to RubyGems 2.6.7.  It seems this has nothing to do with CocoaPods, although I imagine the issue will affect a large swath of CocoaPods users.

**Comment by lightbow** [comment]
Hmm, I'll admit this is beyond my understanding of how RubyGems (and cert management) even work, but this glitch in the matrix from this past week seems like a big red flag: 

https://status.fastly.com/incidents/2tf2hvkj2z50
https://twitter.com/rubygems_status/status/786586986194739200
https://downloads.globalsign.com/acton/attachment/2674/f-06d2/1/-/-/-/-/globalsign-incident-report-13-oct-2016.pdf

Honestly, all I did was restart my computer, and suddenly everything is working again.

**Comment by benasher44** [comment]
This isn't an issue with CocoaPods, so I'm going to close this one. I believe the links provided by @lightbow should be able to help as well. Thanks for filing!

**Comment by brandtdaniels** [comment]
Maybe not, but it's an issue with CocoaPods users. How about a KB article or something?

**Comment by benasher44** [comment]
Did the links above not help? It seems this is a known rubygems issue that just requires updating rubygems.

**Comment by brandtdaniels** [comment]
I didn't follow them specifically, I updated the whole chain: brew, rbenv, ruby, bundler, and then cocoapods 1.1.1 updated just fine.

**Comment by lyahdav** [comment]
For me upgrading to the latest RubyGems wasn't enough to fix this. If it matters, I have ruby installed via [RVM](https://rvm.io/). I had to run the following per [here](https://rvm.io/support/fixing-broken-ssl-certificates):
```
rvm osx-ssl-certs update all
```
