### ISSUE TITLE
[!] The repo `QDVendor` at `../../../.cocoapods/repos/QDVendor` is not clean

### ISSUE THREAD

**Issue by Winter-Yang** [CocoaPods/CocoaPods#6062]
how do it when pod repo push 
pod 1.1.1  xcode 8.0

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
