### ISSUE TITLE
1.1.1 doesn't seem to read SWIFT_VERSION and results in #5981

### ISSUE THREAD

**Issue by thebluepotato** [CocoaPods/CocoaPods#6067]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
🌈🌈🌈🌈

# Report

## What did you do?
I was running into the issue mentioned in #5981 and thought I had fixed it by deleting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES in the target (and setting it explicitly in the *project* to calm Xcode down) and deleting EMBEDDED_CONTENT_CONTAINS_SWIFT. According to #5933/#6016 I expected EMBEDDED_CONTENT_CONTAINS_SWIFT not to exist in the .xcconfig files generated by `pod install` but it was still there so I tracked it down.
I ran `pod install` multiple times, also after `pod superdeintegrate` to start from scratch, added a .swift-version file for 3.0, added some `puts`debugging lines to aggregate_xcconfig.rb (and that's kinda the extent of my Ruby knowledge...) : 
```ruby
def embedded_content_settings
    swift_version = Gem::Version.new(target_swift_version)
    should_embed = !target.requires_host_target? && pod_targets.any?(&:uses_swift?)
    embed_value = should_embed ? 'YES' : 'NO'
           
    puts 'Swift version is : #{swift_version}'
    puts swift_version
    puts target.native_target.resolved_build_setting('SWIFT_VERSION')
    puts target.native_target

    config = {
        'ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES' => embed_value,
        'EMBEDDED_CONTENT_CONTAINS_SWIFT' => embed_value,
    }

    if swift_version >= EMBED_STANDARD_LIBRARIES_MINIMUM_VERSION || !should_embed
        config.delete('EMBEDDED_CONTENT_CONTAINS_SWIFT')
    end

    config
end
```
I also tried adding a post-install step to explicitly set `SWIFT_VERSION` to 3.0 for the targets (inspired by #6008).
## What did you expect to happen?

I expected CocoaPods to recognise the swift version and only set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to YES.

## What happened instead?

I have both ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES and EMBEDDED_CONTENT_CONTAINS_SWIFT set to YES in my .xcconfig files and Xcode complains.
The result of my debugging lines *consistently* resulted in the following, even with all options I tried : 
```bash
Analyzing dependencies
Fetching podspec for `SwiftMarshal` from `/Users/jonaszaugg/Documents/Projects/SwiftMarshal`
Downloading dependencies
Using 1PasswordExtension (1.8.4)
Using AlamoFuzi (1.0.2)
Using Alamofire (4.0.1)
Using Eureka (2.0.0-beta.1)
Using Fuzi (1.0.0)
Using KeychainAccess (3.0.1)
Using MRProgress (0.8.3)
Using SwiftMarshal (0.0.1)
Generating Pods project
Swift version is : #{swift_version}

{"Release"=>nil, "Debug"=>nil}
Pods-Project
Swift version is : #{swift_version}

{"Release"=>nil, "Debug"=>nil}
Pods-Project
Integrating client project
Sending stats
Pod installation complete! There are 10 dependencies from the Podfile and 8 total pods installed.
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.1 (16B2548a)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/jonaszaugg/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 67824072cbb257537c04ec9ec36f9a18b4be3353
```

### Installation Source

```
Executable Path: /Users/jonaszaugg/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-clean            : 0.0.1
cocoapods-deintegrate      : 1.0.1
cocoapods-docs             : 0.2.0
cocoapods-open             : 0.0.8
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-superdeintegrate : 0.0.1
cocoapods-trunk            : 1.1.1
cocoapods-try              : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Project' do
    pod 'Alamofire', '~> 4.0'
    pod 'Fuzi', '~> 1.0'
    pod 'KeychainAccess', '~> 3.0'
    pod 'MRProgress/ActivityIndicator'
    pod 'MRProgress/NavigationBarProgress'
    pod 'MRProgress/Overlay'
    pod 'SwiftMarshal', :path => '/Users/jonaszaugg/Documents/Projects/SwiftMarshal'
    pod 'AlamoFuzi', '~> 1.0'
    pod '1PasswordExtension', '~> 1.8'
    #pod 'RealmSwift', '~> 2.0'
    pod 'Eureka', '~> 2.0.0-beta'
    #pod 'Ono'
    #pod 'SwiftyJSON'
    #pod 'PureLayout'
    #pod 'Log'
    #pod 'SwiftyBeaver'
    #pod 'Static'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

**Comment by benasher44** [comment]
What's the value of "Use Legacy Swift Language Version" in your project?

**Comment by thebluepotato** [comment]
My project has been migrated to Swift 3 shortly after WWDC so the SWIFT_VERSION key has been 3.0 for quite some time for the converted *targets*. I've tried explicitly setting SWIFT_VERSION in my *project* before posting this issue and still the read values are nil.

**Comment by benasher44** [comment]
`SWIFT_VERSION` aside, can you check the value of `Use Legacy Swift Language Version`?

**Comment by thebluepotato** [comment]
Sorry for the late reply! `Use Legacy Swift Language Version` is set to `No` in both the project's and the target's build settings. The same setting is set to `No` in all targets of the Pods.xcodeproj but the `Pods` project itself has `Unspecified` (and therefore not resolved).

**Comment by thebluepotato** [comment]
Here's a tiny project demonstrating the issue : https://github.com/thebluepotato/Issue6067
I made a dummy project, ran `pod init`, ran`pod install`, opened the Workspace, built, close, opened again and there began the Xcode warning -> CocoaPods warning cycle. The deprecated key is still present.

**Comment by benasher44** [comment]
Hm okay. I don't think it needs to be set for the pods project, since we just set it for every target. I'm traveling at the moment, but I'll have a look at this early this week.

**Comment by kwosu87** [comment]
@thebluepotato @benasher44 I found workaround in this situation after version `1.1.1`

I had same problem when I set `Use Legacy Swift Language Version` of my project setting to `No` explicitly like this. (presented in bold text)
<img width="508" alt="2016-10-24 6 26 51" src="https://cloud.githubusercontent.com/assets/2222333/19640445/aba9b8ee-9a17-11e6-9522-044e0aed6e54.png">

I reset this option by **clicking this option and pressing 'Delete key'**, and it still shows `No` presented in plain text. I apply this all of my targets.

<img width="491" alt="2016-10-24 6 33 19" src="https://cloud.githubusercontent.com/assets/2222333/19640586/5f6b6ab2-9a18-11e6-95b2-194608065173.png">

Now I have no errors with `pod install`

**Comment by thebluepotato** [comment]
@kwosu87 Thanks for the tip! I've actually tested the #6068 PR and it works without having to tweak your own project (as it should, working out of the box).

**Comment by kwosu87** [comment]
Thanks for the PR link. Hope that `1.1.2` will be released soon.

**Comment by mingsai** [comment]
In my case, I highlighted and deleted the **Always Embed Swift Standard Libraries** from the build settings of the **project**, and **all of the targets** outlined in the warning message. Although the setting was still visible in the IDE, I saved and closed the project. Rerunning pod install resulted in no further warnings.

**Comment by whittenator** [comment]
I was able to fix this problem by doing the following:
1. Go into Build Settings
2. At the top select All and Completed
3. Under Build Options you should see **Always Embed Swift Standard Libraries** and it is bold. 
4. Click on it and click delete. It should now be unbolded. 
5. Pod install and the error/errors should go away!
![screen shot 2016-12-28 at 4 56 09 pm](https://cloud.githubusercontent.com/assets/17066507/21532583/93df897e-cd1f-11e6-9f17-d25cb81a2a53.png)
