### ISSUE TITLE
Can't create podspec for PLCrashReporter

### ISSUE THREAD

**Issue by k06a** [CocoaPods/CocoaPods#6070]
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I am working on creating `PLCrashReporter-DynamicFramework.podspec` to use it like dependency for my new library because of transitive dependencies with static libraries problem: https://github.com/CocoaPods/CocoaPods/issues/6036

Here are some ideas about this PLCrashReporter podspec: https://github.com/CocoaPods/CocoaPods/issues/1696

Right now I faced a problem of compiling `*.defs` to `*.h` files. This file exactly: `${SDKROOT}/usr/include/mach/mach_exc.defs` should be compiled with this command:

``` bash
mig -arch "${CURRENT_ARCH}" -header "${DERIVED_FILE_DIR}/${CURRENT_ARCH}/${INPUT_FILE_BASE}.h" -server /dev/null -user "${DERIVED_FILE_DIR}/${CURRENT_ARCH}/${INPUT_FILE_BASE}User.c" "${INPUT_FILE_PATH}"
```

We need this build step to run this custom script before compilation of source files. Looks like `prepare_command` is not able to access project file and can't be used to add build steps to library target.

I have error:

```
    - NOTE  | [OSX] xcodebuild:  **/PLCrashMachExceptionServer.m:105:11: fatal error: 'mach_exc.h' file not found
```
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/k06a/.rvm/rubies/ruby-2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 78dd3c4d227cbadb801c6b5e43e1162adc400b67
```
### Installation Source

```
Executable Path: /Users/k06a/.rvm/gems/ruby-2.2.5/bin/pod
```
### Plugins

```
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.1.1
cocoapods-try          : 1.1.0
```
## Podspec

``` ruby
Pod::Spec.new do |s|
  s.name             = 'PLCrashReporter-DynamicFramework'
  s.version          = '1.3.0'
  s.summary          = 'Reliable, open-source crash reporting for iOS and Mac OS X.'

  s.description      = <<-DESC
                        Plausible CrashReporter provides an in-process crash reporting 
                        framework for use on both iOS and Mac OS X, and powers many of 
                        the crash reporting services available for iOS, including 
                        HockeyApp, Flurry, Crittercism and FoglightAPM.
                       DESC

  s.homepage         = 'https://github.com/plausiblelabs/plcrashreporter'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Plausible Labs Cooperative, Inc.' => 'contact@plausible.coop' }
  s.source           = { :git => 'https://github.com/plausiblelabs/plcrashreporter.git', :commit => "5347b1e1e5f2e134f624dd0c47de74b8b40a57eb" }

  s.ios.deployment_target = '7.0'
  s.osx.deployment_target = '10.8'

  s.source_files = 'Source/**/*.{h,hpp,c,cc,cpp,m,mm}', 'Dependencies/protobuf-2.0.3/include/google/protobuf-c/protobuf-c.c'
  s.source_files = '${SDKROOT}/usr/include/mach/mach_exc.defs'
  s.exclude_files = '**/*Tests.*', '**/*_test_*', '**/*TestCase.*', '**/*test.*', '**/*main.m'
  s.public_header_files = 'Source/CrashReporter.h', 'Dependencies/**/*.h'
  s.header_mappings_dir = '.'
  s.requires_arc = false

  s.resources = 'Resources/*.proto'
  s.preserve_paths = 'Dependencies/**'

  s.pod_target_xcconfig = { 
    'GCC_PREPROCESSOR_DEFINITIONS' => 'PLCR_PRIVATE',
    #'USER_HEADER_SEARCH_PATHS' => '../Dependencies/protobuf-2.0.3/include'
  }
  s.prepare_command = <<-CMD
    cd "Resources" && "../Dependencies/protobuf-2.0.3/bin/protoc-c" --c_out="../Source" "crash_report.proto" && cd ..
    find . \\( -iname '*.h' -o -iname '*.hpp' -o -iname '*.c' -o -iname '*.cc' -o -iname '*.cpp' -o -iname '*.m' -o -iname '*.mm' \\) -exec sed -i '' -e 's/#include <google\\/protobuf-c\\/protobuf-c.h>/#include "..\\/Dependencies\\/protobuf-2.0.3\\/include\\/google\\/protobuf-c\\/protobuf-c.h"/g' {} \\;
    find . \\( -iname '*.h' -o -iname '*.hpp' -o -iname '*.c' -o -iname '*.cc' -o -iname '*.cpp' -o -iname '*.m' -o -iname '*.mm' \\) -exec sed -i '' -e 's/#import "CrashReporter\\/CrashReporter.h"/#import "CrashReporter.h"/g' {} \\;
  CMD

  s.library = 'c++'
  s.osx.library = 'macho'
end
```

**Comment by benasher44** [comment]
Hm yeah we don't have a way to add build phases to pod targets. Would it be possible to generate headers that have macros that generate the proper code based on the arch being compiled for?

**Comment by k06a** [comment]
@benasher44 do you mean compile `*.defs` file for all supported architectures and wrap in single header file with some kind of `#ifdef`s inside?

**Comment by benasher44** [comment]
@k06a yep!

**Comment by benasher44** [comment]
One advantage to that approach is that it wouldn't rely on Xcode build phases.

**Comment by k06a** [comment]
Heh, I think this solution may works but pod should be updated to support new architectures.

**Comment by benasher44** [comment]
You would still have to update the pod for new architectures anyway, right?

**Comment by k06a** [comment]
Anyway I think CocoaPods should provide some kind of ability to setup custom build steps and their order and compilation rules for different files format. And some tool to convert Xcode project directly to podspec. Is there any work in progress about this ideas?

**Comment by benasher44** [comment]
For this case in particular, `#ifdef`s are the right solution IMO because of the reduced complexity. It works independent of IDE, and this can even be done before distributing the pod.

There's nothing in progress. `prepare_command` is the closest we have to a pre-build (although not quite pre-build) step at the moment. Given that there's a straightforward alternative, I wouldn't expect to see work on this from us anytime soon. That said, we're always open to PRs to explore the option!

**Comment by orta** [comment]
I'd be very, very wary of adding features that make it easy for pods to edit user's Xcodeprojects. 
It would have to be totally watertight, which is pretty much impossible.

**Comment by k06a** [comment]
@orta I mean really edit only pod target settings like this:
```

**Comment by orta** [comment]
Ah, yeah, feels like something that should be done in a prepare_command then

**Comment by benasher44** [comment]
@k06a sorry that last comment was blank, so we can't read it.

**Comment by k06a** [comment]
@benasher44 edited it right after it was sent. @orta some kind of prepare_command with pod_target argument and ruby source code to edit this Pod::Target settings. Maybe:
```ruby
s.prepare_target { |pod_target| 
   ...
}
```

**Comment by k06a** [comment]
@benasher44 @orta looks like we have no nice way to access `${SDKROOT}/usr/include/mach/mach_exc.defs` because `SDKROOT` can not defined while prepare_command is called 😕

**Comment by benasher44** [comment]
`xcrun --sdk iphoneos --show-sdk-path` should do just that.

**Comment by k06a** [comment]
@benasher44 thanks, great idea! Following works fine:
```
s.prepare_command = <<-CMD
  SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
  mig -arch "i386" -header "Source/mach_exc_i386.h" -server /dev/null -user "Source/mach_exc_i386User.inc" "${SDKROOT}/usr/include/mach/mach_exc.defs"
  mig -arch "x86_64" -header "Source/mach_exc_x86_64.h" -server /dev/null -user "Source/mach_exc_x86_64User.inc" "${SDKROOT}/usr/include/mach/mach_exc.defs"

  echo '#ifdef __LP64__'               > Source/mach_exc.h
  echo '#include "mach_exc_x86_64.h"' >> Source/mach_exc.h
  echo '#else'                        >> Source/mach_exc.h
  echo '#include "mach_exc_i386.h"'   >> Source/mach_exc.h
  echo '#endif'                       >> Source/mach_exc.h

  echo '#ifdef __LP64__'                     > Source/mach_exc.c
  echo '#include "mach_exc_x86_64User.inc"' >> Source/mach_exc.c
  echo '#else'                              >> Source/mach_exc.c
  echo '#include "mach_exc_i386User.inc"'   >> Source/mach_exc.c
  echo '#endif'                             >> Source/mach_exc.c
CMD
```

**Comment by k06a** [comment]
The last issue I can't solve: importing from project looks terrible:
```objective-c
#if __has_include(<PLCrashReporter_DynamicFramework/PLCrashReporter-DynamicFramework-umbrella.h>)
#import <PLCrashReporter_DynamicFramework/PLCrashReporter-DynamicFramework-umbrella.h>
#elif __has_include(<PLCrashReporter-DynamicFramework/Source/CrashReporter.h>)
#import <PLCrashReporter-DynamicFramework/Source/CrashReporter.h>
#else
#import <CrashReporter/CrashReporter.h>
#endif
```

It differs between `use_frameworks` and `use_libraries` and original PLCrashRepoter pod.

**Comment by benasher44** [comment]
I think other pods do this by distributing 2 pods: PodX-Dynamic and PodX-Static. Is that what you mean?

**Comment by benasher44** [comment]
Yeah Brightcove does this in their sub specs: https://github.com/CocoaPods/Specs/blob/master/Specs/Brightcove-Player-SDK/5.1.4/Brightcove-Player-SDK.podspec.json
