### ISSUE TITLE
Deprecated pod on cocoapods.org doesnt't display latest readme

### ISSUE THREAD

**Issue by patrickbdev** [CocoaPods/CocoaPods#6071]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
🌈 

# Report

## What did you do?   
Deprecated [INSImageView](https://cocoapods.org/pods/INSImageView) pod by marking the podspec with appropriate changes
```
spec.deprecated = true
spec.deprecated_in_favor_of = 'PBImageView'
```
and running `pod trunk deprecate INSImageView.podspec`

## What did you expect to happen?   
The CocoaPods page for the pod [https://cocoapods.org/pods/INSImageView](https://cocoapods.org/pods/INSImageView) would update to reflect the latest version of the readme.

## What happened instead?    
An older version of the readme displays on [https://cocoapods.org/pods/INSImageView](https://cocoapods.org/pods/INSImageView)

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : gridstone - https://patrickbgit@github.com/Gridstone/SpecRepo-iOS.git @ e8e4c5033417f3abec683010d1e038641b9add29
               master - https://github.com/CocoaPods/Specs.git @ 95bd66d319c50fea00919ef002bfbc7a365fa038
               Specs - https://patrickbgit@github.com/Gridstone/Specs.git @ b0cb82f9319d55239b45261b4362495ffe05c364
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Compare the readme on these two pages.

https://cocoapods.org/pods/INSImageView
https://github.com/instilio/INSImageView

**Comment by orta** [comment]
The READMEs are based on the last non-prerelease version pushed to CocoaPods, updating the pod spec to be deprecated doesn't update the README or any metadata aside from the deprecation I'm afraid.

**Comment by patrickbdev** [comment]
Is there a way somehow to "undeprecate" pod, trigger a refresh, then deprecate it again to get the desired readme update?

**Comment by orta** [comment]
You can push a new version, that has the [deprecated flags](https://guides.cocoapods.org/syntax/podspec.html#deprecated) set, and that will re-trigger all the documentation generation
