### ISSUE TITLE
Add xxx.tbd library in podspec file fail

### ISSUE THREAD

**Issue by PanXianyue** [CocoaPods/CocoaPods#6073]
I want add libstdc++.tbd in podspec file, but failed. I use cocoapods version is 0.39.0 

example:
 
s.libraries = 'libz', 'libstdc++'

Showing Recent Issues
ld: library not found for -llibstdc++

**Comment by dnkoutso** [comment]
Can you try `s.libraries = 'z', 'stdc++'` instead?

**Comment by PanXianyue** [comment]
I have to solve this problem by this method

**Comment by PanXianyue** [comment]
I have to solve this problem by this method
