### ISSUE TITLE
Can't install CocoaPods XCode 8 OSX El Capitan

### ISSUE THREAD

**Issue by mubashirhussain** [CocoaPods/CocoaPods#6076]
$ sudo gem install cocoapods
Password:
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

MacPro:~ User$ ruby --version  
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
MacPro:~ User$ gem --version   
2.4.6

**Comment by orta** [comment]
Your custom ruby installation needs to have new certificates - http://stackoverflow.com/questions/19150017/ddg#19151697
