### ISSUE TITLE
Make pod install atomic (or closer to it)

### ISSUE THREAD

**Issue by benasher44** [CocoaPods/CocoaPods#6079]
It'd be nice if `pod install` were atomic. This means it either makes all of the changes to your working directory or makes no changes if it doesn't finish:
- Generates Pods directory
- Makes xcode project and workspace changes

This would be an improvement for CI, since it would mean that you could kill a build in the middle of `pod install` and not be left with a half-baked Pods directory. This shouldn't be too hard to do, since it just means operating on a temporary copy of the project files and Pods directory, and then copying them in place at the last moment.

**Comment by segiddins** [comment]
1. Copy `Pods/` to `Dir.tmpdir`
2. Set `config.sandbox` to that temp dir
3. Run the installer
4. Copy the temp dir to `Pods/`

Note that there's no way to make _everything_ (writing the project, writing the lockfile, writing the `Pods/` dir) completely atomic

**Comment by benasher44** [comment]
Unless you make copies of those and write to the copies first :)

**Comment by benasher44** [comment]
You could also make backups of the project files, and then roll back to the backup if the process has to exit early

**Comment by segiddins** [comment]
You can't atomically write multiple files, though

**Comment by benasher44** [comment]
Right. That's why some kind of rollback would need to be at least attempted.
