### ISSUE TITLE
XXXX is implemented in both xxx.framework and yyy.app

### ISSUE THREAD

**Issue by iblacksun** [CocoaPods/CocoaPods#6082]
My app have one application target and one framework target, the framework is embedded in app target. Both of then using a third party pod named 'AMap3DMap'.

When build and run the app, Xcode console logs lots of XXXX is implemented in both xxx.framework and yyy.app. 

 I know that 「You're requesting that the same Pod is integrated into both your app and your framework target, this Pod happens to include a static binary, so this is being added to both targets.」

But in my issue, 'AMap3DMap' is a dynamic frameworks.

I did created a demo project at https://github.com/iblacksun/AMapDemo

## What did you do?
Run `pod install`

## What did you expect to happen?
Third party framework only in one place

## What happened instead?
Xcode console logs lots of logs say :XXXX is implemented in both xxx.framework and yyy.app.

## Project that demonstrates the issue
https://github.com/iblacksun/AMapDemo
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.0 (8A218a)
         Git : git version 2.10.1
```

### Installation Source

```
Executable Path: /Users/iblacksun/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'git@gitlab.dxy.net:ios-developer/DXYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "9.0"
inhibit_all_warnings!
use_frameworks!
def amap
    pod 'AMap3DMap', '4.4.0'
end
target 'Haha' do
    amap
end

target 'AMapDemo' do
    amap
end
```

**Comment by benasher44** [comment]
This is a dup of #6065. Going to close this one, but feel free to add any additional information you have to the other ticket. Thanks for filing!
