### ISSUE TITLE
Pod not showing up in search

### ISSUE THREAD

**Issue by rhaining** [CocoaPods/CocoaPods#6084]
🌈

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.

Yes. i'm on v1.1.1

>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
`pod trunk push`

## What did you expect to happen?
The pod to show up on cocoapods.org, cocoapods search, and to be available via Podfiles.

## What happened instead?
The pod url now [works](https://cocoapods.org/pods/PayPalCommerce), and it now is available via Podfiles.
But, it's not showing up in [search](https://cocoapods.org/?q=paypalcommerce).

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/tolar/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 048c4b6626eb8e7488536aa1388afc038b5ac35c
```

### Installation Source

```
Executable Path: /Users/tolar/.rvm/rubies/ruby-2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by rhaining** [comment]
Maybe search just needs to be re-indexed or something? thanks!

**Comment by orta** [comment]
I've moved this issue over to the search project - https://github.com/CocoaPods/search.cocoapods.org/issues/105

**Comment by pavanidivya48** [comment]
Hi, I created my own pod but when  i opened cocoapods.org, and search for my pod it's not showing. I do not know how to resolve this one. Can anyone please help me.

Thanks in Advance.

**Comment by umakanta** [comment]
Hi, I created my own pod [UKPDFReader](https://cocoapods.org/pods/UKPDFReader)
It is available at cocoapods.org But, search for my pod it's not showing. [Here](https://cocoapods.org/)

What i am doing wrong. Please help me, resolving the same.

**Comment by AndyQ** [comment]
This is still an issue! New pods still aren't showing

**Comment by marhas** [comment]
Seems to be the same issue for UAWalkthrough that I pushed a week or two ago. It's available to "pod install" but not showing up in the search.

**Comment by rajeshpremani** [comment]
I'm also getting the same issue, I have created my pod and pushed it on cocoa pods, the pod was successfully created but on cocoa pod's search result, the pod is not showing. It is available through 'pod install'
