### ISSUE TITLE
tvOS with extension Linker Error

### ISSUE THREAD

**Issue by nikitaame** [CocoaPods/CocoaPods#6085]
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
> 
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910
- [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

I was trying to make a build using the fastlane gym tool
## What did you expect to happen?

Make proper build correctly integrated with all pod dependancies. This is for a tvOS app utilizing an extension (TopShelf).
## What happened instead?

❌  ld: library not found for -lPods-Prod - [APP_NAME] - TopShelf
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

*\* ARCHIVE FAILED **

The following build commands failed:
Ld fastlane/deriveddata/[APP_NAME]-PROD-ad-hoc-1.4.0.9-DEVELOP/Build/Intermediates/ArchiveIntermediates/Prod\ -\ [APP_NAME]/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Prod\ -\ [APP_NAME]\ -\ TopShelf.appex/Prod\ -\ [APP_NAME]\ -\ TopShelf normal arm64
## CocoaPods Environment

CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.10.1
Ruby lib dir : /Users/ameln002/.rvm/rubies/ruby-2.3.1/lib
## Project that demonstrates the issue

Private project.

**Comment by benasher44** [comment]
A few things to try: clear derived data, `pod deintegrate`, `pod install` again. Can you try those?

**Comment by nikitaame** [comment]
Thanks for the quick response! Tried those a couple times without any result however.

**Comment by benasher44** [comment]
No prob! Any chance you could put together a sample project that reproduces the issue? This sounds like it's just a build setting that's gotten messed up somewhere, but it's really hard to identify exactly what that means without a sample project.

You can also look at this search: https://github.com/CocoaPods/CocoaPods/search?q=ld%3A+library+not+found+for+-lPods&type=Issues&utf8=✓

There have been a bunch of issues like this, but I haven't seen them crop up in awhile. IIRC, they usually end with a build setting being fixed, clearing derived data, or removing all traces of pods from the project and `pod install`ing again.

**Comment by nikitaame** [comment]
Gotcha! Could it perhaps be a problem with tvOS extensions? I believe there were some issues with watchOS one's until CP fixed them in 1.1.0. 

I've tried looking at the search and checking build settings, derived data, etc but to no avail. I'll try to get a sample project with the same issue together for you ASAP. Thanks again!

**Comment by benasher44** [comment]
No prob! It could be a problem with tvOS extensions, but this isn't the kind of result I'd expect for an issue that's extension-specific.

**Comment by nikitaame** [comment]
I've figured out what the problem was.

When running pod install,  -lPods-Prod - [APP_NAME] - TopShelf.a was being generated in the Frameworks folder of the project workspace. When deleted the fastlane build would work once again, until pod install would be run.

**Comment by benasher44** [comment]
@nikitaame sorry I'm still not quite sure I understand what happened. Would you mind walking me through it?

**Comment by nikitaame** [comment]
Sure, let me know if this explanation is better.

When I cloned the project from a git repo I would try to make a build using fastlane (https://github.com/fastlane) but would get the error:
```
❌  error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
Easy enough, just run pod install to fix this problem. After doing so however, the Frameworks folder of my xcodeproj would generate empty references (they're highlighted red) to libPods - [BUILD_TARGET_NAME] - [APP_NAME].a  & libPods - [BUILD_TARGET_NAME] - [APP_NAME] - TopShelf.a

When running fastlane again to make a build (btw, I do have the xcworkspace open not the xcproj), I would now receive the error:
```
❌ ld: library not found for -lPods-Prod - [APP_NAME] - TopShelf
❌ clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

The following build commands failed:
Ld fastlane/deriveddata/[APP_NAME]-PROD-ad-hoc-1.4.0.9-DEVELOP/Build/Intermediates/ArchiveIntermediates/Prod\ -\ [APP_NAME]/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Prod\ -\ [APP_NAME]\ -\ TopShelf.appex/Prod\ -\ [APP_NAME]\ -\ TopShelf normal arm64
```

This error would be fixed by then going in and deleting those aforementioned references. This isn't a full fix however as I don't want that manual file deletion to be part of the build process whenever pod install is run. I'm trying to figure out what is creating these references now.

**Comment by nikitaame** [comment]
It seems that the references are supposed to be pointing to some derived data which is non existent...

**Comment by benasher44** [comment]
@nikitaame hm I see. Do you provide a sample project that reproduces the issue? That'd go a long way toward helping me debug and put together a fix. Thanks!

**Comment by nikitaame** [comment]
Sorry for forgetting to respond. It was as signing issue. Thank you!

**Comment by benasher44** [comment]
Oh okay great. I'm glad you got it worked out. Have a great day!
