### ISSUE TITLE
pod init error: NameError

### ISSUE THREAD

**Issue by thireven** [CocoaPods/CocoaPods#6097]
# Report

## What did you do?
Run `pod init`

## What did you expect to happen?
Create the Podfile file

## What happened instead?
NameError - uninitialized constant Nanaimo::Reader::StringScanner

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.1
Ruby lib dir : /Users/tnguyen/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d482696da3fc4961cb0605586fb92107885a641d
```

### Installation Source

```
Executable Path: /Users/tnguyen/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
NameError - uninitialized constant Nanaimo::Reader::StringScanner
Did you mean?  StringScanner
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:168:in `const_missing'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/nanaimo-0.1.0/lib/nanaimo/reader.rb:61:in `initialize'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `new'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:102:in `open'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/claide-1.0.1/lib/claide/command.rb:333:in `run'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/tnguyen/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by coderwhy** [comment]
the same to me

**Comment by purej1983** [comment]
I got the same problem

**Comment by 78lab** [comment]
I got the same..

**Comment by orta** [comment]
Are these on a fresh installation?

**Comment by thireven** [comment]
@orta Yes, fresh installation. Fresh, brand-new mac, even.

**Comment by 78lab** [comment]
@orta Yes, fresh installation.

**Comment by orta** [comment]
We started a deploy of a new beta for CocoaPods, but got stuck on the deploy process due to a Specs issue. Looks like you're all using a beta version of Xcodeproj - I would recommend reverting it down to 1.3.0. Think you'd do:

```
[sudo] gem uninstall xcodeproj
[sudo] gem install xcodeproj -v 1.3.3
```

**Comment by thireven** [comment]
Installing xcodeproj 1.3.3 fixes it.

Thanks.

**Comment by sunbijou** [comment]
[sudo] gem uninstall xcodeproj
[sudo] gem install xcodeproj -v 1.3.3

 -> error occur 
You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory error..

What's problem??

Thanks.

**Comment by orta** [comment]
You need to actually include the optional `sudo` bit.

**Comment by 78lab** [comment]
Installing xcodeproj 1.3.3 fixes it.

Thanks.

**Comment by sunbijou** [comment]
Gem::MissingSpecError occur

$ pod init

/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'xcodeproj' (< 2.0, >= 1.3.3) among 58 total gem(s)

Help me..Thanks

**Comment by sunbijou** [comment]
Installing xcodeproj fixes it.
Thank you very much

**Comment by ShakeebM** [comment]
while installing xcodeproj -v 1.3.3, I got the following error

Fetching: xcodeproj-1.3.3.gem (100%)
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/xcodeproj
What should i do?

**Comment by Tr736** [comment]
install xcode pro 1.3.3 and I still get the same error

**Comment by ttaulli** [comment]
I tried the above as well and I'm still not able to create a pod init

**Comment by MohammedMAK** [comment]
i have same issue

**Comment by Tr736** [comment]
Ok so having a little play about with it this morning and got it working by doing the following without skipping any steps

1. uninstall cocoa pods
`sudo gem uninstall cocoa pods`

2. Uninstall xcodeProj
`sudo gem uninstall xcodeproj`

3. install xcode pro 1.3
`sudo gem install xcodeproj -v 1.3.3`

4. install cocoapods normal release
 `sudo gem install cocoapods`

5. try pod init.... should work

if not go back to step 2 and if the option is there to remove xcodeProj 1.4 remove it but keep 1.3

let me know if this resolves it for you

**Comment by ttaulli** [comment]
Hi,
I tried this -- but when doing the install of xcode pro 1.3 for #3, I get the following:

ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/xcodeproj

**Comment by Tr736** [comment]
For step 3 try

sudo gem install -n /usr/local/bin xcodeproj -v 1.3.3

**Comment by ttaulli** [comment]
Looks like it works!  thx!

**Comment by massoud12345** [comment]
Hi,  I followed all the above but on step 3, I get this error message when I run the following command:
sudo gem install -n/usr/local/bin xcodeproj -v 1.3.3
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
