### ISSUE TITLE
Cocoapod Error/Bug. Internal Server error

### ISSUE THREAD

**Issue by patchthecode** [CocoaPods/CocoaPods#6098]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I run ` pod trunk push JTAppleCalendar.podspec`

## What did you expect to happen?
I expected my new CocoaPod version to be updated

## What happened instead?
I got this error message
```
Validating podspec
 -> JTAppleCalendar (6.0.1)

[!] An error occurred on GitHub’s side. Please check GitHub’s status at https://status.github.com and try again later in case the pod is still not published.
```
## CocoaPods Environment
pod env

---------------------------------------------
Error loading the plugin `cocoapods-trunk-1.1.1`.

Gem::LoadError - can't activate cocoapods-trunk-1.1.1, already activated cocoapods-trunk-1.1.0.beta.1
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:2235:in `check_version_conflict'
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:1367:in `activate'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.3/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------

### Stack

```
   CocoaPods : 1.1.0.rc.3
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8T61a)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d482696da3fc4961cb0605586fb92107885a641d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/patchthecode/JTAppleCalendar
Now shows and internal server error ->> https://cocoapods.org/pods/JTAppleCalendar

**Comment by ShiWeiCN** [comment]
I have the same problem...😭

**Comment by patchthecode** [comment]
@ShiWeiCN  yea man ☹️ 
I have a lot of users waiting on my pod update

**Comment by orta** [comment]
I'd recommend keeping your eye on https://status.cocoapods.org - until we can send Podspecs Specs to trunk, there's nothing we can do I'm afraid.

**Comment by orta** [comment]
Alright - looking good now 👍

**Comment by patchthecode** [comment]
@orta Ok. I didnt know. Thanks for the quick response.
I dont know how you code works under the hood, but maybe as a suggestion when someone does and `push` maybe it can check the status first, and if anything is down, it can print to the user's console, that the status is currently down? But I dont know.. only a suggestion. Thanks for the response.
