### ISSUE TITLE
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.

### ISSUE THREAD

**Issue by rony868** [CocoaPods/CocoaPods#6105]
Last login: Sat Oct 29 11:24:30 on console
evas-Mac:~ Rony$ cd /Users/Rony/Desktop/FirebaseProject/
evas-Mac:FirebaseProject Rony$ pod init
evas-Mac:FirebaseProject Rony$ vi Podfile
evas-Mac:FirebaseProject Rony$ pod install
Setting up CocoaPods master repo
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
evas-Mac:FirebaseProject Rony$

**Comment by segiddins** [comment]
Did you try adding it manually as the error message suggests?

**Comment by rony868** [comment]
Yes and this is result
evas-Mac:repos Rony$ git clone https://github.com/CocoaPods/Specs.git master
Cloning into 'master'...
remote: Counting objects: 881324, done.
remote: Compressing objects: 100% (31/31), done.
error: RPC failed; result=56, HTTP code = 200 KiB | 97.00 KiB/s   
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
evas-Mac:repos Rony$

**Comment by segiddins** [comment]
Then it's an issue with your network, and not specifically CocoaPods-related.
