### ISSUE TITLE
xcode 8 update iOS Deployment Target 7.0

### ISSUE THREAD

**Issue by tiandabao** [CocoaPods/CocoaPods#6109]
My app needs to support > = 7.0 but now use xcode8, platform: ios, '7.0' pod install, update the library ios Deployment Target is 8.0, this can be set???????

**Comment by tiandabao** [comment]
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '7.0'
        end
    end
end
Find this, directly change the project.pbxproj in pod

**Comment by xayoung** [comment]
same issue
