### ISSUE TITLE
pod lib lint  cannot pass

### ISSUE THREAD

**Issue by PanXianyue** [CocoaPods/CocoaPods#6111]
when i use a framework in my podspec appear this error, how can i fix it ???

ld: illegal text-relocation to 'cstring' in /Users/XY/Desktop/AJKPlayer/AJKPlayer/Frameworks/wplayer.framework/wplayer(alphablend.o) from '_ff_sws_alphablendaway' in /Users/XY/Desktop/AJKPlayer/AJKPlayer/Frameworks/wplayer.framework/wplayer(alphablend.o) for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by qq912276337** [comment]
@PanXianyue the same error. dou you know how to fix it?
