### ISSUE TITLE
podspec  validation error

### ISSUE THREAD

**Issue by sunnycn2013** [CocoaPods/CocoaPods#6115]
## What did you do?

ℹpodspec  validation error

## What did you expect to happen?

ℹ  podspec  validation passed

## What happened instead?

ℹ  error msg:

```
$ pod spec lint podNameLib.podspec

 -> podNameLib (0.0.1)
    - ERROR | [iOS] frameworks: A framework should only be specified by its name
    - ERROR | [iOS] unknown: Encountered an unknown error (undefined method `dirname' for nil:NilClass) during validation.

Analyzed 1 podspec.
````

**Comment by benasher44** [comment]
Can you please share your podspec?

**Comment by sunnycn2013** [comment]
@benasher44  very very thanks benasher44,！！

What I use is a local private warehouse, I want to do a pod files with a static library, when I was editing podspec files the above mistakes, later found to be set vendored_libraries error(file directory path error).I redefine the local configuration, as follows:
```
s.vendored_libraries  = 'SpecName/libSpecName.a'
  s.frameworks   = 'ImageIO', 'SystemConfiguration', 'CoreText', 'QuartzCore', 'Security', 'UIKit', 'Foundation', 'CoreGraphics','CoreTelephony'
  s.libraries = 'sqlite3', 'z'
```

After all, its OK !!

**Comment by benasher44** [comment]
Okay great! Glad you got it sorted out. Thanks for filing!
