### ISSUE TITLE
Having proprocessor macros with a "\" corrupts xcode project after pod install

### ISSUE THREAD

**Issue by graph** [CocoaPods/CocoaPods#6116]
🌈 It's colorful interesting. Didn't know Unicode emoji's can have color.

This is either an issue with cocoapods or Xcodeproject. Thanks to my coworker for generating the steps to reproduce.

* [√] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
1. Create a new iOS project
2. Add `VERSION_STRING=\"$(VERSION_STRING)\"` to the Preprocessor Macros
3. Close project and run `pod install`
4. Open project again. Project will error with parse failures.

## What did you expect to happen?
project to open properly.

## What happened instead?
Error openning project because of failing to parse project file.

## CocoaPods Environment

`pod env | pbcopy`

### Stack
```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/user/.rvm/rubies/ruby-2.3.0/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ c0e42abaf0c3246346b79151b3cc19328cca9138
               radecated private repos
```
### Installation Source
```
Executable Path: /Users/user/.rvm/gems/ruby-2.3.0/bin/pod
```
### Plugins
```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

The steps to create the project should be sufficient. 

Thank you.

**Comment by mortenbekditlevsen** [comment]
I believe that I am experiencing another variant of the same issue. Cocoapods removes '\' escapes from my own shell script steps.
Diff after running a 'pod update' (with some noise removed):
-			shellScript = "... Resources/Info\\ plists ...";
+			shellScript = "... Resources/Info\ plists ...";

The issue only occurs when cocoapods has other changes to script phases, so after fixing the issue once, it doesn't get reintroduced (until after next cocoapods update, I assume).

**Comment by segiddins** [comment]
Since you haven't provided a project, please `gem install xcodeproj:1.4.1` and try again, thanks!

**Comment by graph** [comment]
xcodeproj 1.4.1 does indeed fix this issue. Thank you.
