### ISSUE TITLE
multiple build configurations -- no such file or directory

### ISSUE THREAD

**Issue by keepingitneil** [CocoaPods/CocoaPods#6127]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Multiple Xcode schemes. Each scheme uses a different build configuration. One scheme works, one fails with the following error:

```
/usr/bin/codesign --force --sign 9A89DB1801B0B09C763754299C62FC037AA903ED  --preserve-metadata=identifier,entitlements /Users/neildwyer/Documents/work_repos/riano-ios/DerivedData/riano/Build/Products/Beta_Debug-iphoneos/riano.app/Frameworks/Alamofire.framework

/Users/neildwyer/Documents/work_repos/riano-ios/DerivedData/riano/Build/Products/Beta_Debug-iphoneos/riano.app/Frameworks/Alamofire.framework: No such file or directory
```

I explored further and noticed that the successful scheme builds into DerivedData/riano/Build/Products/Dev-iphoneos for the riano.app and the riano_pods.framework (and pods related frameworks)

The unsuccessful build goes to DerivedData/riano/Build/Products/Beta_Debug-iphoneos for the riano.app but goes to DerivedData/riano/Build/Products/Build/Products/Release-iphoneos for the riano_pods.framework (and pods related frameworks)

Tried the basics. Clean + pod deintigrate + rm -rf DerivedData etc.

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ eacbaa099c143ae9da4a36f7576795509e056ef2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'riano' do
use_frameworks!

pod 'Fabric'
pod 'Crashlytics'
pod 'SocketRocket'
pod 'RxSwift'
pod 'RxCocoa'
pod 'SDWebImage'
pod 'Realm'
pod 'Alamofire', '4.0.1'
pod 'GCDWebServer', '~> 3.2.5'
pod 'RxDataSources'
pod 'RxKeyboard'
pod 'riano-ios-tooltipper', { :git => 'git@github.com:bebo/riano-ios-tooltipper.git', :branch => 'master' }
pod 'riano-ios-event-tracker', { :git => 'git@github.com:bebo/riano-ios-event-tracker.git', :branch => 'master' }
pod 'riano-ios-use-cases', { :git => 'git@github.com:bebo/riano-ios-use-cases.git', :branch => 'master' }
pod 'riano-ios-http', { :git => 'git@github.com:bebo/riano-ios-http.git', :branch => 'master' }
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by benasher44** [comment]
Ah. Looks like this is a dup of #6121. There's a fix for this in progress. Thanks for filing!

**Comment by keepingitneil** [comment]
Ahhh I saw that issue but it was due to the target having spaces. In my case it was the build configuration having underscores? Thanks.
