### ISSUE TITLE
Headers for depended-on pod not found when linting my pod

### ISSUE THREAD

**Issue by atsakiridis** [CocoaPods/CocoaPods#6131]
# Report

## What did you do?

$ pod lib lint

## What did you expect to happen?

Pass the checks without issues

## What happened instead?

I got an error because a header file from another depended-on pod is not found

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.7
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ baad1d4e667339325a32b7948ef1a51812f6f625
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

I can't share on the central Cocoapods repository because I can't get past the lint phase, so I'm sharing a [.zip](https://drive.google.com/file/d/0BwfD74mG87iMVmtVTUplZXNXVk0/view?usp=sharing) instead.

## Important Notes
- Weirdest thing of all is that the same pod builds fine from within the Sample App provided when generating the pod file structure (i.e. Sample dir within .zip). That is, I check the compile command and the proper include dir is there, while when linting the pod itself verbosely the include dir is missing and the build fails.
- You will notice in my podspec that I have added custom header search path, which I know that isn't a very good idea, I can tell you more about my use case if you want to explain the reasoning behind it (For now I'm trying to avoid too much spam)

**Comment by b-ray** [comment]
`pod lib lint` will lint your pod using dynamic frameworks by default. The same pod lints successful for me using static libraries: `pod lib lint --use-libraries --allow-warnings`.
There is no error in your sample project because you didn't use dynamic frameworks (by adding `use_frameworks!` in the Podfile) in there.

**Comment by atsakiridis** [comment]
Thanks a lot @b-ray, indeed with those options the linting passes fine, but more importantly with the same options I'm finally able to push my pod in the central repository: `$ pod trunk push --use-libraries --allow-warnings`, which was my ultimate goal ;)

The question now is, is there a way to make this work even when the Podfile using the pod uses `use_frameworks!`? I'm trying to make sure that our users will avoid obstacles as much as possible, and right now if a developer uses our pod with `use_frameworks!` they are going to get a build error :(

Thanks again,
Antonis

**Comment by b-ray** [comment]
I'm certainly not an expert, but I think you need to change how the `sofia-sip` framework is included or how it is built.
As a suggestion, I tried changing all framework imports to include the framework name, like so:
I changes it from e.g.: `#include <sofia-sip/sdp.h>`
to: `#include <sofiasip/sofia-sip/sdp.h>`
That makes your project built on my machine using dynamic frameworks and static libraries, but you would need to perform these changes also in your sofia-sip framework-dependency. However, there might be other ways to solve this issue.

**Comment by atsakiridis** [comment]
Thanks @b-ray, I thought of that route too. The problem is that although I can easily update the includes in my pod, it's not that easy to do for the sofia-sip framework dependency, as those headers are created by cross compiling a GNU autotools project, which has specific structure for includes.

Are you aware if I could use a dynamic lib (i.e. .dylib) instead of a framework? Would that work for iOS (given of course that I use it as Embedded Binary, to avoid sharing security issues)

**Comment by DanToml** [comment]
This looks like a problem in the upstream dependency, rather than an issue with CocoaPods itself.
