### ISSUE TITLE
user install fails

### ISSUE THREAD

**Issue by tcurdt** [CocoaPods/CocoaPods#6132]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`gem install cocoapods --user-install`

## What did you expect to happen?

It should just install.

## What happened instead?

When installing cocoapods I am getting the following error:

```
$ gem install cocoapods --user-install
WARNING:  You don't have /Users/tcurdt/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Successfully installed nap-1.1.0
Successfully installed fuzzy_match-2.0.4
Successfully installed cocoapods-core-1.1.1
Successfully installed cocoapods-deintegrate-1.0.1
Successfully installed cocoapods-downloader-1.1.2
Successfully installed cocoapods-plugins-1.0.0
Successfully installed cocoapods-search-1.0.0
Successfully installed cocoapods-stats-1.0.0
Successfully installed netrc-0.7.8
Successfully installed cocoapods-trunk-1.1.1
Successfully installed cocoapods-try-1.1.0
Successfully installed molinillo-0.5.3
Successfully installed escape-0.0.4
Successfully installed fourflusher-2.0.1
Successfully installed cocoapods-1.1.1
15 gems installed
```

## CocoaPods Environment

I am trying to install `cocoapods`. Right now I am not sure it because of `cocoapods` or `chruby` that it's not working. I am setting up `chruby` like this:

```
source /usr/local/opt/chruby/share/chruby/chruby.sh
source /usr/local/opt/chruby/share/chruby/auto.sh
chruby ruby-2.3
```

Looking at the env I see:

```
$ echo $GEM_HOME
/Users/tcurdt/.gem/ruby/2.3.1
$ echo $GEM_PATH
/Users/tcurdt/.gem/ruby/2.3.1:/Users/tcurdt/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0
$ echo $PATH
/Users/tcurdt/.gem/ruby/2.3.1/bin:/Users/tcurdt/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/bin:/Users/tcurdt/.rubies/ruby-2.3.1/bin:/usr/local/sbin:/usr/local/bin:/usr/local/Cellar:/Users/tcurdt/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

## Project that demonstrates the issue

NA

**Comment by tcurdt** [comment]
Hm. Seems like `sudo gem uninstall cocoapods` and `gem install cocoapods` did the trick.

**Comment by benasher44** [comment]
Glad you got it resolved. Going to close, since this appears to have been an issue specific to your shell environment. Thanks!
