### ISSUE TITLE
how to change the trunk name of cocoapods after pod trunk register?

### ISSUE THREAD

**Issue by guiyongdong** [CocoaPods/CocoaPods#6142]
When I use cocoapods trunk register, I used a random name, but now I want make it more readable. But there is no way to change it... Event I use "pod trunk register email 'new name'" again. it doesn't works. :(

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by talezion** [comment]
@segiddins Any fix to this? This does not work https://stackoverflow.com/a/44049895/4697535
