### ISSUE TITLE
Spaces in project name break codesign step with embedded framework - cannot build app.

### ISSUE THREAD

**Issue by graham-perks-snap** [CocoaPods/CocoaPods#6147]
# Report

## What did you do?

Create an iOS project with a space in the name (e.g. Snap Kitchen). Then File->New->Target and choose Cocoa Touch Framework. Call this e.g. CoreSnap and ensure it's embedded in the application (option given while creating the framework).

## What did you expect to happen?

Project should build
## What happened instead?

Xcode now fails to build, due to the space in the project name. In the [CP] Embed Pods Frameworks step it emits:
`Code Signing /Users/grahamperks/Documents/src/SnapKitchen/DerivedData/SnapKitchen/Build/Products/Debug-iphonesimulator/Snap Kitchen.app/Frameworks/AFDateHelper.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements /Users/grahamperks/Documents/src/SnapKitchen/DerivedData/SnapKitchen/Build/Products/Debug-iphonesimulator/Snap Kitchen.app/Frameworks/AFDateHelper.framework
/Users/grahamperks/Documents/src/SnapKitchen/DerivedData/SnapKitchen/Build/Products/Debug-iphonesimulator/Snap: No such file or directory
`

**Note there are no spaces around the path in the `codesign` line.**

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5229c0e2c14a8e6d74c55b2c16909c403e91ce48
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'
use_frameworks!

target 'Two Words' do
    # Analytics
    pod 'Alamofire'
end
```

## Project that demonstrates the issue

https://snapkitchen.box.com/s/jjqpf37h49cu4l4yx4pta8ux4b9c2bco

**Comment by benasher44** [comment]
This is fixed in #6120, which was merged yesterday. The fix will be available in an upcoming release. Thanks for filing!
