### ISSUE TITLE
Using any version after 1.0.1 to integrate React native pod into iMessage extension results in error

### ISSUE THREAD

**Issue by shrutic** [CocoaPods/CocoaPods#6149]
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
     No, I am not using beta release. Cocoapods 1.0.1 has been working for us to integrate React native pod and CodePush ( by Microsoft) pod into iMessage extension written in Swift on Xcode 8.1.
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1) Install the latest cocoapods 1.1.1
2) Run pod install on an iMessage Extension project on Xcode 8.1

## What did you expect to happen?
Install all pod dependencies correctly and able to compile the iMessage extension code.

## What happened instead?
 Get errors inside React native pod code and CodePush pod code ( Cannot use sharedApplication)
NOTE: Install 1.0.1 cocoapods version and do "pod _1.0.1_ install ", then React native pod code and CodePush pod code compile fine and we are able to use them in our iMessage extension

## CocoaPods Environment

Note: I have 2 versions of cocoapods installed ( one beta and one 1.0.1). I have used 1.0.1 to get my iMessage extension project working.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ad13d9eecaac617940a9b6f621237976db76bdb5
               visualstudio-defaultcollection-_git-cocoapods - https://msblox.visualstudio.com/DefaultCollection/_git/CocoaPods @ 7fcc26814a5d6d6f4f43e3e0c30455a177d73eff
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'xxxxxx' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for xxxxxxx

end

target 'MessagesExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessagesExtension
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTImage',
  ]

  pod "HockeySDK"
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
end
```

## Project that demonstrates the issue

I currently do not have a open source project where I can display this issue. Will try to generate one soon

**Comment by benasher44** [comment]
@shrutic can you try using CocoaPods 1.1.0 instead of 1.1.0.rc.2? I made many changes for extensions in 1.1.0, so there may be some missing if you're not using the latest 1.1.x release (1.1.1 is the latest).

**Comment by shrutic** [comment]
I have tried using 1.1.1, but still get the errors associated with React native and CodePush. Let me know if I should specifically try 1.1.0

**Comment by benasher44** [comment]
Oh interesting. Looking at your error now, and we didn't make any changes related extension-safe APIs. In 1.1.0, the frameworks used by your extension will be properly linked, and maybe they weren't before? It sounds like there is some API that hasn't been made safe to use in extensions yet, and the fixes in 1.1.0 have exposed that. Can you isolate which pod has the compile error?

**Comment by shrutic** [comment]
React Native 0.34 version pod

**Comment by benasher44** [comment]
It looks like React Native hasn't marked its APIs that don't work for extensions as `NS_EXTENSION_UNAVAILABLE`, etc. You should file an issue with React Native.

Calling methods that access APIs that aren't available in extensions would likely crash, and I'm unsure how this compiled before. This apparent unintended side-effect of CocoaPods 1.1.0 does seem unfortunate in your circumstance, but in general this is now behaving as expected: APIs that could crash when accessed from extensions should fail to build unless they've been marked with `NS_EXTENSION_UNAVAILABLE` when built for use with an extension.

Going to close this, since this is ultimately an issue with React Native's APIs. Sorry about that!

**Comment by shrutic** [comment]
Thanks for the immediate response. Will follow up with React native
