### ISSUE TITLE
Pod lib lint downloads master repo for specs with no dependencies

### ISSUE THREAD

**Issue by ateliercw** [CocoaPods/CocoaPods#6154]
🌈

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.

no 

> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [X ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod lib lint` as a step on CircleCi

## What did you expect to happen?

Build the pod and make sure the current version of the pod spec is valid

## What happened instead?

CocoaPods first runs `Setting up CocoaPods master repo`, which takes almost five minutes and isn't necessary. I can work around it by supplying a git repo to `pod lib lint --sources=<repo>`, but really I'd like to be able to specify that no external sources should be used.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : raizlabs - https://github.com/raizlabs/Swiftilities @ 74035d7415e564281a1c32a0a3232e498163265e
```

### Installation Source

```
Executable Path: /Users/mskiba/.gem/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/Raizlabs/Swiftilities

**Comment by benasher44** [comment]
@ateliercw this sounds like it'd be a nice addition! I agree that updating specs repos shouldn't be required for `pod lib lint`'ing a pod with no dependencies.
