### ISSUE TITLE
CocoaPods 0.39.0 no longer working with master repo

### ISSUE THREAD

**Issue by wcwynn** [CocoaPods/CocoaPods#6163]
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Using CocoaPods versions less than 1.0.0 seems to have stopped working with the master repo within the past 14 hours (without warning).  Specifically, the use of version 0.39.0 is indicating it cannot be used.  (The project I'm using cannot be updated at this time and so our team is blocked) Error:  [!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)

Is this expected behavior?  Is there a workaround to this issue?  Details below.

## What did you do?
bundle exec pod install --verbose

## What did you expect to happen?

Updating local specs repositories

CocoaPods 1.2.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
...
Generating Pods project
Integrating client projects
Sending stats
Pod installation complete! There are XX dependencies from the Podfile and YY total pods installed.

## What happened instead?

  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.
[!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)
Update CocoaPods, or checkout the appropriate tag in the repo.

<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:258:in `check_version_information'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:224:in `block (2 levels) in update'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:212:in `block in update'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:211:in `each'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/sources_manager.rb:211:in `update'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:213:in `block in update_repositories'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:211:in `each'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:211:in `update_repositories'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:132:in `block in resolve_dependencies'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:131:in `resolve_dependencies'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
<redacted>/bundle/ruby/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
<redacted>/bundle/ruby/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
<redacted>/bundle/ruby/2.0.0/bin/pod:23:in `load'
<redacted>/bundle/ruby/2.0.0/bin/pod:23:in `<main>'
## CocoaPods Environment

[!] Unknown command: `env`
Did you mean: ipc

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + init       Generate a Podfile for the current directory.
    + install    Install project dependencies to Podfile.lock versions
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + plugins    Show available CocoaPods plugins
    + repo       Manage spec-repositories
    + search     Search for pods.
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + trunk      Interact with the CocoaPods API (e.g. publishing new specs)
    + try        Try a Pod!
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command

**Comment by orta** [comment]
This has been documented in the blog about  the repo sharding: http://blog.cocoapods.org/Sharding/

**Comment by bazik123** [comment]
that blogpost explains how to make `pod install` pass, but i can't figure out how to do `pod setup`

**Comment by wcwynn** [comment]
@orta Thanks for sharing the blogpost/explaining what happened. I suspect many CocoaPods users don't poll the blogpost for upcoming version deprecation/stoppage postings. So here is some feedback: I'd *highly recommend* putting a stoppage notice into the update script itself -- similar to the dynamic notice about the latest beta version that is available. A "stoppage warning" notice is arguably more important than a "new beta version available" notice -- at least for users who are building and supporting production apps around this technology. In addition, I'd recommend notifying users of the version being stopped at least 1 month in advance (3 months would be better!) -- 2 weeks in advance is a pretty small time window (especially when notifying users passively via blogpost). The best way to do this is probably via the script itself which the users will definitely see.

CovoaPods is a great tool and I'm grateful to you and all contributors for your contributions. As a user, it's absolutely no fun to find out about version depreciations suddenly and abruptly without warning (as was the case here for me), so I hope you will consider this feedback.

**Comment by segiddins** [comment]
@wcwynn we would have, if there was a way to set messages for old versions, which there isn't -- we provided notice that this would be coming back in May (http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/)

**Comment by wcwynn** [comment]
@segiddins Understood. That is the reason I offered the feedback that it would be useful to build it into the tool. If current versions already have the feature, then my feature suggestion is already implemented.

Indeed, notice was provided via blogpost in May but no specific date was provided. We actually attempted to update around that time but experienced problems with the 1.0.0 betas (the only available upgrade at the time I believe) so had to roll back.

Anyways, we've successfully upgraded to 1.1.0 and problems have been resolved.

**Comment by johndpope** [comment]
hi @orta,  one challenge with this (I'm using a gemfile to hardcode to version 0.39 which works fine - but if I execute a command) -  blows up. Not a show stopper - will have to bite bullet and upgrade app. 
bundle exec pod search hockey
Setting up CocoaPods master repo
Updating bf62207..ade79d1
Fast-forward
 .../1.0.7/PYPhotoBrowser.podspec.json              | 31 ++++++++++++++++++++++
 1 file changed, 31 insertions(+)
 create mode 100644 Specs/b/a/7/PYPhotoBrowser/1.0.7/PYPhotoBrowser.podspec.json
From https://github.com/CocoaPods/Specs
   bf62207..ade79d1  master     -> origin/master
[!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)

**Comment by segiddins** [comment]
The `--no-repo-update` flag will be your friend

**Comment by johndpope** [comment]
thanks
