### ISSUE TITLE
unable to run `pod setup` in 0.39.0 due to '1.0.0 required'

### ISSUE THREAD

**Issue by bazik123** [CocoaPods/CocoaPods#6164]
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [+] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

`pod setup` doesnt work in 0.39.0 . I saw http://blog.cocoapods.org/Sharding/ but it seems pod setup has using the default Specs  built-in

## What did you do?

Run `pod setup`

## What did you expect to happen?

succesfull pod setup run.

## What happened instead?

> bundle exec pod setup  --no-ansi
Setting up CocoaPods master repo
Updating 5a45c4e..64d5908
Fast-forward
 .../e/CNUIKitTools/0.0.3/CNUIKitTools.podspec.json | 33 ++++++++++++++++++++++
 1 file changed, 33 insertions(+)
 create mode 100644 Specs/d/7/e/CNUIKitTools/0.0.3/CNUIKitTools.podspec.json
From https://github.com/CocoaPods/Specs
   5a45c4e..64d5908  master     -> origin/master
[!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)
Update CocoaPods, or checkout the appropriate tag in the repo.

## CocoaPods Environment
$ pod --version
0.39.0
$ pod env
[!] Unknown command: `env`
Did you mean: ipc

**Comment by segiddins** [comment]
`(cd ~/.cocoapods/repos/master && git checkout v0.32.1)`

**Comment by bazik123** [comment]
clarification: I am trying to call pod setup on a clean machine (or, after `rm -rf ~/.cocoapods`)

**Comment by segiddins** [comment]
`(cd ~/.cocoapods/repos && git clone https://github.com/CocoaPods/Specs.git && cd specs && git checkout v0.32.1)`, or upgrade to CocoaPods > 1.0
