### ISSUE TITLE
pod spec lint

### ISSUE THREAD

**Issue by khuong291** [CocoaPods/CocoaPods#6165]
I want to public a framework.

I have created a pod spec in my framework directory, fill pod spec information, then type `pod spec lint`

but it gives me error:

> -> KPImageView (1.0.0)
>     - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/khuong291/KPImageView.git
> /var/folders/t5/rgq4j6cn7h79khx0xsftrjtw0000gp/T/d20161113-67362-1dxzrg4
> --template= --single-branch --depth 1 --branch 1.0.0
> 
> Cloning into
> '/var/folders/t5/rgq4j6cn7h79khx0xsftrjtw0000gp/T/d20161113-67362-1dxzrg4'...
> warning: Could not find remote branch 1.0.0 to clone. fatal: Remote
> branch 1.0.0 not found in upstream origin ) during validation.
> 
> Analyzed 1 podspec.
> 
> [!] The spec did not pass validation, due to 1 error. [!] The
> validator for Swift projects uses Swift 3.0 by default, if you are
> using a different version of swift you can use a `.swift-version` file
> to set the version for your Pod. For example to use Swift 2.3, run:
>     `echo "2.3" > .swift-version`.

my podspec:

    Pod::Spec.new do |s|
      s.name         = "KPImageView"
      s.version      = "0.0.3"
      s.summary      = "UIImageView with Ken Burns effect."
      s.homepage     = "https://github.com/khuong291/KPImageView"
      s.license      = { :type => 'MIT' }
      s.author       = { "khuong291" => "dkhuong291@gmail.com" }
      s.source       = { :git => "https://github.com/khuong291/KPImageView.git", :tag => s.version.to_s }
    
      s.platform     = :ios, '7.0'
      s.requires_arc = true
    
      s.source_files = 'KPImageView/KPImageView/*'
    end

Please help me with this. Thanks.

**Comment by segiddins** [comment]
As the error message says, you have not pushed the `1.0.0` tag to github, which is what your podspec is saying is the tag to use to download your pod.

**Comment by khuong291** [comment]
@segiddins  Thanks 👍

**Comment by reza-khalafi** [comment]
Just using this:  
  `echo "2.3" > .swift-version`

**Comment by shanlaing** [comment]
@reza-khalafi  what means?
