### ISSUE TITLE
Tested not passed and documentation not correct in our Cocoapods page

### ISSUE THREAD

**Issue by oliverou** [CocoaPods/CocoaPods#6166]
# Report

## What did you do?

We run `pod trunk push DJI-SDK-iOS.podspec` to update our SDK podspec on Cocoapods. And it shows publish successfully:

![screen shot 2016-11-13 at 2 50 20 pm](https://cloud.githubusercontent.com/assets/13310805/20244150/8791f61c-a9b0-11e6-9c55-4378806dc06e.png)

## What did you expect to happen?

The Cocoapods page information of our SDK: <https://cocoapods.org/pods/DJI-SDK-iOS> should show **Documented** and **Tested** passed with check mark. And the documentation of the page should show the content of the readme file of our SDK Github Repo: <https://github.com/dji-sdk/Mobile-SDK-iOS>.

## What happened instead?

But when I check the Cocoapods page of our SDK: <https://cocoapods.org/pods/DJI-SDK-iOS>, it said the **Tested** not passed and the documentation is not correct, it should show the readme file's documentation of our iOS SDK Github Repo: <https://github.com/dji-sdk/Mobile-SDK-iOS>

![screen shot 2016-11-13 at 2 46 32 pm](https://cloud.githubusercontent.com/assets/13310805/20244164/0bc610a8-a9b1-11e6-80bb-a34991c05c8e.png)

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7338f789af3efab5c96f557d10a9e40e7b1f1fda
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# platform :ios, '9.0'

target 'DJISdkDemo' do
  pod 'DJI-SDK-iOS', '~> 3.4.1’
end
```

## Project that demonstrates the issue

DJI-SDK-iOS CocoaPods link: <https://cocoapods.org/pods/DJI-SDK-iOS>, 
DJI-iOS-SDK Sample Github Repo: <https://github.com/dji-sdk/Mobile-SDK-iOS>

Thanks!

**Comment by orta** [comment]
Please open this on the CocoaPods.org repo, as this repo is only for CocoaPods the command line tool. 👍

**Comment by oliverou** [comment]
You mean this repo: <https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/3/a/a/DJI-SDK-iOS/3.4.1/DJI-SDK-iOS.podspec.json>? It's a pity that it cannot show the correct documentation on the SDK's Cocoapods website page: <https://cocoapods.org/pods/DJI-SDK-iOS>, is that possible to fix it? Thanks!

**Comment by orta** [comment]
No, I mean for the website: https://github.com/CocoaPods/CocoaPods.org

FWIW, the fix is to ship the README with your framework, as that's what the end users see and the server acts like every other client. WRT the testing, that should get discussed in the issue.

**Comment by oliverou** [comment]
@orta, thanks! We will add the readme file inside the framework zip file in our next SDK version. Already open an issue for the website, please check it and help fix the "tested" not pass issue.
