### ISSUE TITLE
The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)

### ISSUE THREAD

**Issue by khuong291** [CocoaPods/CocoaPods#6167]
I run `sudo gem update cocoapods`

but it says:

> Updating installed gems
> Nothing to update

What should I do now? Please help me. Thanks.

**Comment by segiddins** [comment]
`gem install cocoapods:1.1.1`

**Comment by maicoder** [comment]
I run pod setup , 

it says:

```
[!] The `master` repo requires CocoaPods 1.0.0 -  (currently using 0.39.0)
Update CocoaPods, or checkout the appropriate tag in the repo.
```

When I run `gem install cocoapods:1.1.1` , it  says `successfully installed cocoapods-1.1.1`

When I run `pod --version`, it says `0.39.0`

What should I do now? Please help me. Thanks.

**Comment by segiddins** [comment]
what does `pod _1.1.1_ version` give you?

**Comment by maicoder** [comment]
I run `pod --version`, it only says `0.39.0`

**Comment by segiddins** [comment]
That's odd. What does `gem env` and `which pod` give you? Seems like a RubyGems issue to me :/

**Comment by maicoder** [comment]
I run `gem env`, it says:
```
➜  ~ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.2
  - RUBY VERSION: 2.0.0 (2015-12-16 patchlevel 648) [universal.x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/dongwang/Software/ruby
  - USER INSTALLATION DIRECTORY: /Users/dongwang/.gem/ruby/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/dongwang/Software/ruby/bin
  - SPEC CACHE DIRECTORY: /Users/dongwang/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-15
  - GEM PATHS:
     - /Users/dongwang/Software/ruby
     - /Users/dongwang/.gem/ruby/2.0.0
     - /Library/Ruby/Gems/2.0.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://gems.ruby-china.org"]
  - REMOTE SOURCES:
     - https://gems.ruby-china.org
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/dongwang/Software/ruby/bin
     - /usr/local/bin
     - /Users/dongwang/Sofware/ruby/bin
```

**Comment by bamx23** [comment]
Does backward compatibility for 0.39.0 just has been dropped?

**Comment by Agoer** [comment]
In addition to update, I have no choice but to.....

**Comment by Agoer** [comment]
除了更新，我别无他法。

**Comment by d-metzler** [comment]
Is 0.39.0 broken?  We have several reasons for not upgrading to 1.0.0 yet.

**Comment by khuong291** [comment]
pod --version
1.2.0.beta.1
Thanks @segiddins

**Comment by andree-surya** [comment]
This blog post explain and solve the issue for me.
http://blog.cocoapods.org/Sharding/

**Comment by maicoder** [comment]
I uninstalled pod and reinstalled it. It works.

**Comment by dharmendraiosdev** [comment]
I have also faced same issue that after updating cocoapods using command `$ gem install cocoapods:1.1.1`, is still telling me the same version 0.39.0. 
I used  `$ gem uninstall cocoapods ` and then it ask me which version I want to uninstall. I choose `cocoapods-0.39.0` and got message `Successfully uninstalled cocoapods-0.39.0` and now it returns 1.1.1 on command `$ pod --version`

**Comment by orta** [comment]
I've updated the blog post with some recommendations that allow you to keep using 0.39 and below:  https://github.com/CocoaPods/blog.cocoapods.org/pull/140

**Comment by iTA9178** [comment]
sudo gem install -n /usr/local/bin cocoapods

**Comment by SaikCaskey** [comment]
I just had to sudo gem update cocoapods

**Comment by Struki84** [comment]
Same problem, updated to `cocoapods 1.3.1`, `but pod --versions`, shows `0.39.0`
It seems like `rbenv` shims problem, try running `rbenv rehash`. Solved it for me.
