### ISSUE TITLE
Error on Pod init

### ISSUE THREAD

**Issue by patchthecode** [CocoaPods/CocoaPods#6168]
All i did was `pod init`
And below was the error template i received

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8T61a)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 60ee8ff63254a2394b49937602d9211325f986df
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
NameError - uninitialized constant Nanaimo::Reader::StringScanner
/Users/jt/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:168:in `const_missing'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.0/lib/nanaimo/reader.rb:61:in `initialize'
/Users/jt/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `new'
/Users/jt/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/jt/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/jt/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:102:in `open'
/Users/jt/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:333:in `run'
/Users/jt/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/jt/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
Is this fixed if you `gem update nanaimo`?

**Comment by patchthecode** [comment]
one sec
Trying it nwo

**Comment by patchthecode** [comment]
OK here is the full error i got

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8T61a)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 60ee8ff63254a2394b49937602d9211325f986df
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
NameError - uninitialized constant Nanaimo::Reader::StringScanner
/Users/jt/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:168:in `const_missing'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.1.0/lib/nanaimo/reader.rb:61:in `initialize'
/Users/jt/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `new'
/Users/jt/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/jt/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/jt/.gem/ruby/2.0.0/gems/xcodeproj-1.4.0/lib/xcodeproj/project.rb:102:in `open'
/Users/jt/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:333:in `run'
/Users/jt/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/jt/.gem/ruby/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=uninitialized+constant+Nanaimo%3A%3AReader%3A%3AStringScanner&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - pod lib create fails: uninitialized constant Nanaimo::Reader::StringScanner (NameError)
   https://github.com/CocoaPods/CocoaPods/issues/6106 [closed] [14 comments]
   2 weeks ago

 - Error on Pod init
   https://github.com/CocoaPods/CocoaPods/issues/6168 [open] [2 comments]
   2 minutes ago

 - pod init error: NameError
   https://github.com/CocoaPods/CocoaPods/issues/6097 [closed] [20 comments]
   2 weeks ago

**Comment by segiddins** [comment]
Run `gem install xcodeproj:1.4.1`, that should fix things for you

**Comment by patchthecode** [comment]
it works!!

Did i do something wrong before? Maybe you guys can have something automatically suggest to do this so that others wont have this issue.

thanks a mill.
Cocoapods is an awesome project.

**Comment by patchthecode** [comment]
Sorry. I think I closed it without asking. my bad.
Issue is resolved, but I'll leave you to close it when ready.
