### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by woaomo** [CocoaPods/CocoaPods#6169]
pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.6.3)
Generating Pods project
Abort trap: 6

**Comment by SergeyKovalenko** [comment]
Hello @woaomo. I have the same issue. How did you fix that?
I have this environment: 
```
xcode 8.1, 
ruby 2.3.1 
cocoapodsa 1.1.1
macOS 10.12 
```
and I have the same issue:
 `Abort trap: 6` no any additional details with `--verbose`

**Comment by wangbourne** [comment]
i have the same issue here. and yes, it works after installing 1.2.0.beta.1
