### ISSUE TITLE
[!] Invalid `Podfile` file: [!] Specifying multiple `post_install` hooks is unsupported

### ISSUE THREAD

**Issue by mattiacantalu** [CocoaPods/CocoaPods#6172]
Hi,

i've updated cocoa pods to 1.1.1 (w/ ruby 2.3.1). Now when i run "pod update" an error occurred:
`[!] Invalid `Podfile` file: [!] Specifying multiple `post_install` hooks is unsupported..`

Only one post_install not multiple.

post_install no longer available? Any alternatives?

Thanks

**Comment by orta** [comment]
We've never supported multiple `post_install` hooks, we've just not provided an error before 1.0. You should migrate them to be one hook instead of multiple.

**Comment by TheEngineerz** [comment]
how to migrate to be one hook ?

**Comment by orta** [comment]
It's just normal code, you move it into one hook...

**Comment by mattiacantalu** [comment]
@TheEngineerz  i've changed my code from:

`def main_pods
    post_install do |installer_representation|
    end
end`

to

`def main_pods
end 
post_install do |installer_representation|
end`

**Comment by TheEngineerz** [comment]
@mattiacantalu Thank you. Yes it works

**Comment by progerchai** [comment]
I solved this problem by removing the post_install module to the globle
```
target 'MyAppStarter' do
# other code here
end


# global code  hear
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end

```

**Comment by vektorat-manish948** [comment]
Hello Everyone, 
I am new to react-native development, and i am facing the issue mentioned below.
I dont understand how to resolve this issue. I tried fixing issue with above mentioned approach but seems like not working for me. Basically i was trying to install "yarn add react-native-in-app-review" framework for review and rating feature but when i am running pod i am facing issue

[!] Invalid `Podfile` file: [!] Specifying multiple `post_install` hooks is unsupported..

 #  -------------------------------------------
 #  
 >    post_install do |installer|
 #      installer.pods_project.targets.each do |target|
 #  -------------------------------------------
Couldn't install Pods. Updating the Pods project and trying again...

Any kind of help is appreciable.
