### ISSUE TITLE
App extensions deployment target

### ISSUE THREAD

**Issue by rlepinski** [CocoaPods/CocoaPods#6173]
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Created a pod file to install frameworks into 2 different targets. One of those targets is an NoticationServiceExtension that requires the deployment target to be set to 10, the other is the Main application with deployment target set to 9. Ran `pod install`

I tried working around this issue by setting the deployment target lower on the NotificaitonServiceExtension but it breaks deployment to older iOS devices with this error:
```
This app contains an app extension that specifies an extension
point identifier that is not supported on this version of iOS
for the value of the NSExtensionPointIdentifier key in its Info.plist
```

## What did you expect to happen?
Pods to install.

## What happened instead?
Received this error:
```
[!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):

- Goat (iOS 9.0) and GoatServiceExtension (iOS 10.0) do not use the same platform.
```

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.1
Ruby lib dir : /usr/local/var/rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 456d4f3f7206e052befa18da85c1bfe287c4cd5c
```

### Installation Source

```
Executable Path: /usr/local/var/rbenv/versions/2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

project 'Goat/Goat.xcodeproj'

target 'Goat' do
  pod 'UrbanAirship-iOS-SDK'
end

target 'GoatServiceExtension' do
  pod 'UrbanAirship-iOS-AppExtensions'
end

```

**Comment by benasher44** [comment]
@rlepinski I'm fairly sure that the issue is that both the extension and the app have to be built for the same version of the iOS SDK, so you'll need to check your project file there. It's okay if the extension and app have different deployment targets (i.e. okay to have extensions that only exists in iOS 10 but are distribute your ipa to be downloaded on iOS 9 and iOS 10), but both will have to be built against iOS 10 (just different deployment target settings). Does this make sense?

**Comment by rlepinski** [comment]
@benasher44 The base SDK is set to the same for both targets. I get the error above when only the deployment target is set differently. When I set them to the same deployment target everything pod installs fine but deployment is broken.

I see https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer.rb#L334 is the line that is causing the issue. Looks like its checking the deployment targets and not the base SDK - https://github.com/CocoaPods/CocoaPods/blob/7bef87f95b85ee31ce6ad04e7d14645965ab86bf/lib/cocoapods/installer/analyzer/target_inspector.rb#L144

**Comment by benasher44** [comment]
@rlepinski can you post a sample project that reproduces the issue? We have a similar setup in our app (different deployment targets), and it works fine.

**Comment by benasher44** [comment]
@rlepinski oh i see we're trying to verify deployment target compatibility, but it looks like this check fails in some cases. That's odd because we have this exact scenario in our app and it works fine. I have some ideas on how to fix. For a workaround, can you try re-ordering the targets in your Podfile? I'm curious to know if order matters here. Thanks!

**Comment by rlepinski** [comment]
@benasher44 I noticed it only happens if `use_frameworks!` is added. Ill try rearranging my targets and report back.

**Comment by rlepinski** [comment]
@benasher44 Rearranging the targets did not work. Here is a sample project that reproduces the issue [PodTest.zip](https://github.com/CocoaPods/CocoaPods/files/595594/PodTest.zip).

**Comment by benasher44** [comment]
@rlepinski thanks so much for providing a sample! I'll have a look at it shortly.

**Comment by rlepinski** [comment]
@benasher44 Were you able to reproduce the issue? Do you need any more info?

**Comment by benasher44** [comment]
@rlepinski sorry I haven't found time yet to investigate this further. I'm going to try to make time this week though. Apologies for the delay!

**Comment by yacir** [comment]
@benasher44 i have the same problème :)

**Comment by rlepinski** [comment]
@yacir A quick workaround is to set the targets to the same version, run pod install, then set the targets back.

**Comment by yacir** [comment]
Thx @rlepinski :)
Actually, that's what i do while waiting for a fix.

**Comment by benasher44** [comment]
@yacir @rlepinski I finally got some time to sit down and do the PR. It's up now, and I tested with the attached sample project. Thanks again for being patient here!
