### ISSUE TITLE
Updated CocoaPods rating says "EMPTY README" / "Minimal README" even though it's present in the CocoaPod.

### ISSUE THREAD

**Issue by tirodkar** [CocoaPods/CocoaPods#6175]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

We recently released v1.5.1 of our [EarlGrey CocoaPod](http://cocoapods.org/pods/EarlGrey). We use a prebuilt, zipped up framework and we use `preserve_paths` to point to the README, CHANGELOG etc. In this release, we missed the README, and correctly, our rating dropped to 4/5 from 5/5.

We rectified this by pushing v1.5.2 and v1.5.3.

## What did you expect to happen?

We expected to be back to 5/5 rating, and our README to be visible on the CocoaPods page.

## What happened instead?

The README has not been updated and we're still seeing the same rating.

Please check the 1.5.2 or 1.5.3 release from https://github.com/google/EarlGrey/releases for EarlGrey.zip file containing the requisite README.

## CocoaPods Environment

This seems to be independent of the environment.

## Project that demonstrates the issue

http://cocoapods.org/pods/EarlGrey

**Comment by orta** [comment]
I re-ran the docs and everything is working fine now 👍, please use either the cocoapods.org or cocoadocs.org repo for non-CocoaPods the command line tool issues, they have more info on how to diagnose and fix these problems too

**Comment by tirodkar** [comment]
Thanks a ton @orta!

**Comment by Flawion** [comment]
Hi @orta , i have the same problem https://github.com/CocoaPods/cocoapods.org/issues/392 could you help me?
