### ISSUE TITLE
pod setup

### ISSUE THREAD

**Issue by oceanfive** [CocoaPods/CocoaPods#6176]
hello, when I run pod setup , the following problem happened:
Setting up CocoaPods master repo
[!] Failed to connect to GitHub to update the CocoaPods/Specs specs repo - Please check if you are offline, or that GitHub is down

I have tried something, but no effect, please help

**Comment by orta** [comment]
Looks like you can't seem to connect to github, perhaps you're behind a VPN or are having network issues?

**Comment by oceanfive** [comment]
yes, I am using VPN ,but I can open github in safari , it failed in terminal.

**Comment by orta** [comment]
Then I'm afraid you'll have to get your VPN set up to connect to github in order to use CocoaPods
