### ISSUE TITLE
Delete old pod 

### ISSUE THREAD

**Issue by af-golan** [CocoaPods/CocoaPods#6178]
How can I delete my pod from the master? 
Should I create pull request?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
