### ISSUE TITLE
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.

### ISSUE THREAD

**Issue by scauos** [CocoaPods/CocoaPods#6183]
HaodeMacBook-Air:BluePic-iOS haodong$ pod update
Update all pods
Setting up CocoaPods master repo
fatal: Not a git repository (or any of the parent directories): .git
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
HaodeMacBook-Air:BluePic-iOS haodong$

please help

**Comment by benasher44** [comment]
@scauos what version of CocoaPods and Xcode are you using?

**Comment by elmarko** [comment]
Hi, Same issue CocoaPods v1.1.1 and Xcode 8.1

**Comment by benasher44** [comment]
@elmarko can you file a new ticket and fill out the issue template please? Thanks!

**Comment by benasher44** [comment]
This looks like a duplicate of issues that were fixed in CocoaPods 1.1.0. Going to close this one, since there's not enough info for to help debug. Please file a new issue and fill out the issue template. Thanks for filing!

**Comment by scauos** [comment]
I try to uninstall Cocoapods, and install again. And that work for me

**Comment by Kanna18** [comment]
@scauos  thanks it worked for me
