### ISSUE TITLE
cannot load such file -- macho

### ISSUE THREAD

**Issue by tarekjradi** [CocoaPods/CocoaPods#6187]
Hi, I got this error. Anybody was got this problem before?

LoadError - cannot load such file -- macho
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sandbox/file_accessor.rb:377:in `rescue in dynamic_binary?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sandbox/file_accessor.rb:375:in `dynamic_binary?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sandbox/file_accessor.rb:162:in `block in vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sandbox/file_accessor.rb:161:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sandbox/file_accessor.rb:161:in `vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sandbox/file_accessor.rb:170:in `vendored_static_frameworks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/sandbox/file_accessor.rb:236:in `vendored_static_artifacts'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `block in generate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `any?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:56:in `generate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:87:in `block in create_xcconfig_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:84:in `create_xcconfig_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:160:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:158:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/installer.rb:115:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by segiddins** [comment]
What does `gem which macho` print? If nothing, try running `gem install ruby-macho`

**Comment by mudox** [comment]
I got the same problem too. Error log is same as @tarekjradi 
And I ran `gem install ruby-macho` then `gem which macho` got
> /Users/xxxxx/.gem/gems/ruby-macho-0.2.6/lib/macho.rb

**Comment by segiddins** [comment]
@mudox after running `gem install`, does the issue persist?

**Comment by mudox** [comment]
Yes, I tried `gem install ruby-macho`, problem remains.
<img width="878" alt="screen shot 2016-11-21 at 16 20 50" src="https://cloud.githubusercontent.com/assets/2283394/20475394/a10ef430-b006-11e6-99fd-433c93bddbfd.png">
And I ran `pod install > pod.log` in my project root, this is the log file.

**Comment by mudox** [comment]
Update: I installed the release version cocoapods **1.1.1**, the issue gone.

**Comment by ehlersd** [comment]
Just updated to cocoapods 1.2.0 and now I'm getting the macho error.  Everything was working fine prior...

gem which macho returns `/Users/darrenehlers/.rvm/gems/ruby-2.2.3/gems/ruby-macho-1.0.0/lib/macho.rb`

**Comment by segiddins** [comment]
@ehlersd yes, please open a new issue

**Comment by segiddins** [comment]
Please open a new issue as this one is closed
