### ISSUE TITLE
Pod setup failed with git RPC error -9806

### ISSUE THREAD

**Issue by light-bo** [CocoaPods/CocoaPods#6192]
when execute 

> pod setup

command, the error happened:

**RPC failed; curl 56 SSLRead() return error -9806**

how to solve it ?

**Comment by orta** [comment]
The [top google result for this](https://confluence.atlassian.com/stashkb/git-clone-fails-error-rpc-failed-result-56-http-code-200-693897332.html) implies there is a problem with your VPN or Anti-virus software, did you check those?

**Comment by light-bo** [comment]
I close the VPN and my computer has no Anti-virus software, but still come across the problem. ^_^

**Comment by light-bo** [comment]
I close the VPN and my computer has no Anti-virus software, but still come across the problem. ^_^

**Comment by cloudhm** [comment]
I have the same problem. I am from China. I used Astrill china optimized channel.

**Comment by 937447974** [comment]
me too!!!

**Comment by 937447974** [comment]
我解决了。

1. pod --version,查看版本号,如1.1.1
2. gem list. 查看pod相关插件
3. 卸载大于version版本的插件，如sudo gem uninstall cocoapods-downloader -v 1.2.0.beta.1

**Comment by sunmengxiang** [comment]
It's supposed to the internet connect error,because when internet connect become better, `pod setup` is successful
1.close VPN and Anti-virus software
2.make your internet connect better
3.uninstall your old cocoapods in terminal:sudo rm -rf ~/.cocoapods/
4.do `pod setup` again in terminal

**Comment by DanToml** [comment]
This is a problem with your connection to GitHub, and can be broken by firewall/VPN/Antivirus configurations.

Potential solutions can be found here: https://confluence.atlassian.com/stashkb/git-clone-fails-error-rpc-failed-result-56-http-code-200-693897332.html

**Comment by light-bo** [comment]
Thanks for all guys‘.
