### ISSUE TITLE
Pods group with location path will cause pod install fail.

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#6194]
I write a xcode template and it will auto generate Podfile and podspec under the `Pods` group (files is in root path).

I found that the `pod install` will finish without error, but the Project's xcconfig will lose some configs: just a release xcconfig (without debug xcconfig) . The release xcconfig's path is relate the group, but its path still be `Pods/Target Support Files/Pods-TestFramework/Pods-TestFramework.release.xcconfig`. It cause the full path is `TestFramework/Pods/Pods/Target Support Files/Pods-TestFramework/Pods-TestFramework.release.xcconfig`, so it is red !

I think the pod not check the `Pods` group's location type, it is a bug.

**Comment by benasher44** [comment]
@Whirlwind can you please fill out the issue template and provide a sample project that reproduces the issue? There's not enough context here for us to help debug this. Thanks!

**Comment by Whirlwind** [comment]
The reproduce step is simple.

1. create a new project.
2. create a group `Pods` under the project.
3. set the `Pods` group 's location to the `Pods` folder.
4. write a Podfile and `pod install`

The key step is step 3.

**Comment by Whirlwind** [comment]
Hi, @benasher44 ,
Do you try it?

**Comment by benasher44** [comment]
@Whirlwind `pod install` will setup this group and folder properly in the right place in the workspace. Is there a particular reason why you're trying to do it manually?

**Comment by Whirlwind** [comment]
I write a xcode template to create a project with a Podfile and a Podspec template. In this template, The podfile and podspec will be smart to write some configs as user project. 

But, xcode will create a Folder and a group. I can not disable it.

**Comment by benasher44** [comment]
Can you elaborate more on the "create a Folder and group" part that you can't disable? I'm still not quite following. Thanks for your patience!

**Comment by Whirlwind** [comment]
Please check out this project: https://github.com/dijkst/XcodeTemplate
Install:
```
git clone git@github.com:dijkst/XcodeTemplate.git "~/Library/Developer/Xcode/Templates/Framework & Library"
```
Now, you can create a project with the `Static Framework`, it will create a static framework project with a Podfile and a Podspec.

But, Xcode must create a Pods Folder !!!

**Comment by benasher44** [comment]
Okay I think I understand now. Your template creates a Pods directory, which contains the Podfile and podspec for your project?

**Comment by Whirlwind** [comment]
Yeah.

The Podfile's path is `../Podfile` which is relative to the `Pods`.

**Comment by benasher44** [comment]
@Whirlwind okay. I recommend just naming the folder and group something else then. From my perspective, the behavior is undefined when you have a Pods folder that you intend to keep other things in that are not what `pod install` puts in there. Just naming it something else should eliminate confusion and resolve this issue. Is that reasonable?

**Comment by Whirlwind** [comment]
I think that CocoaPods should read the location of `Pods` group, and set the xcconfig path will relation path for the `Pods` group, if the `Pods` group have a location.

Now, CP set the path of xcconfig to the `Pods/xxxx/xxx.xcconfig`, I think it should be smarter.

**Comment by benasher44** [comment]
Hm. I'm open to making CP smarter. I can't reproduce the issue though. I followed your instructions, and my sample project builds fine. Would you mind providing a sample project that reproduces the issue?

**Comment by Whirlwind** [comment]
Please check out this demo project : https://github.com/Whirlwind/TestFramework

**Comment by benasher44** [comment]
@Whirlwind okay I see what's going on. I'll have a look at this soon.

**Comment by Whirlwind** [comment]
@benasher44 Have you some idea for this issue?

**Comment by benasher44** [comment]
@Whirlwind this is still on my list, but this particular scenario is a bit esoteric and therefore lower priority compared to other issues I'm investigating. If you have some time, I'd be happy to point you to places where you could look at debugging this in CocoaPods as well as advice regarding putting together a PR!
