### ISSUE TITLE
pod trunk push , something wrong

### ISSUE THREAD

**Issue by shaveKevin** [CocoaPods/CocoaPods#6195]
pod trunk push   in terminal  something wrong .
[!] SKNetworkRequest did not pass validation, due to 2 errors.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run:
    `echo "2.3" > .swift-version`.

this is my  spec：
Pod::Spec.new do |s|
  s.name         = "SKNetworkRequest"
  s.version      = "0.0.3"
  s.summary      = "A network  based on  AFNetworking 3.x+"
  s.license      = { :type => 'MIT', :file => 'LICENSE' }
  s.homepage     = "https://github.com/shaveKevin/SKNetworkRequest"
  s.authors      = { 'shavekevin' => 'shavekevin@gmail.com' }
  s.social_media_url   = "http://www.shavekevin.com"
  s.platform     = :ios, "7.0"
  s.requires_arc = true
  s.source_files = 'SKNetworkRequest/**/*.{h,m}'
  s.public_header_files = 'SKNetworkRequest/**/*.{h}'
  s.source       = { :git => "https://github.com/shaveKevin/SKNetworkRequest.git", :tag => "0.0.3" }
  s.dependency "AFNetworking", "~> 3.1.0"
  # s.frameworks = 'UIKit', 'CoreFoundation','CoreText', 'QuartzCore', 'Accelerate', 'MobileCoreServices'
end

**Comment by orta** [comment]
You need to pass validation in order to put your repo on the CocoaPods Trunk - consult [the guides](https://guides.cocoapods.org/) for more information, to test validation locally - use `pod spec lint` and `pod lib lint`.
