### ISSUE TITLE
Pod isn't fully updating

### ISSUE THREAD

**Issue by mikeblanton** [CocoaPods/CocoaPods#6197]
[x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
🌈
# Report

## What did you do?

Run `pod trunk push AffirmSDK.podspec`

## What did you expect to happen?

Install pod correctly, expect to see v2.2.0 as the current version in `pod search AffirmSDK` and also in the web page (https://cocoapods.org/pods/AffirmSDK)

## What happened instead?

`pod trunk push AffirmSDK.podspec` returns "[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later."

`pod search AffirmSDK` returns
-> AffirmSDK (2.1.1)
   Integrate Affirm into your iOS app
   pod 'AffirmSDK', '~> 2.1.1'
   - Homepage: https://github.com/Affirm/affirm-ios-sdk
   - Source:   https://github.com/Affirm/affirm-ios-sdk.git
   - Versions: 2.1.1, 2.1.0, 2.0.0, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0 [master repo]

https://cocoapods.org/pods/?q=AffirmSDK shows 2.2.0 as the latest version.

https://cocoapods.org/pods/AffirmSDK returns an Internal Server Error message.

http://cocoadocs.org/docsets/AffirmSDK/2.2.0/ returns a 404 page.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.8.2
Ruby lib dir : /Users/michaelblanton/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8532b73b2869f30b7dfe0f26a4531554675ea723
```

### Installation Source

```
Executable Path: /Users/michaelblanton/.rvm/rubies/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by segiddins** [comment]
This is being tracked at https://github.com/CocoaPods/trunk.cocoapods.org/issues/207.
