### ISSUE TITLE
pod trunk push yields an internal server error

### ISSUE THREAD

**Issue by NSProgrammer** [CocoaPods/CocoaPods#6198]
🌈* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk push --verbose`

## What did you expect to happen?

pod is updated for everyone to start consuming

## What happened instead?

500 server error

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8532b73b2869f30b7dfe0f26a4531554675ea723
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Logs of issue

$] pod trunk push --verbose

[!] Found podspec `ZipUtilities.podspec`

Updating spec repo `master`

CocoaPods 1.2.0.beta.1 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1

Validating podspec
    ZipUtilities (1.8.0) - Analyzing on iOS 6.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `ZipUtilities` from `/Users/noobrien/Developer/ZipUtilities/ZipUtilities.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A ZipUtilities

Downloading dependencies

-> Installing ZipUtilities (1.8.0)
  > Copying ZipUtilities from
  `/Users/noobrien/Library/Caches/CocoaPods/Pods/External/ZipUtilities/f64a2ed08da2f46bef90296f19067c80-c2a8a`
  to
  `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/ZipUtilities`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `ZipUtilities` iOS 8.0
      - Generating Info.plist file at
      `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/ZipUtilities/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/ZipUtilities/ZipUtilities.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/ZipUtilities/ZipUtilities-umbrella.h`
    - Installing target `Pods-App` iOS 8.0
      - Generating Info.plist file at
      `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods-App/Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods-App/Pods-App.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods-App/Pods-App-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to
  `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
  - Writing Lockfile in
  `../../../../var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Podfile.lock`
  - Writing Manifest in
  `../../../../private/var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/Pods/Manifest.lock`

Integrating client project

[!] Please close any current Xcode sessions and use `App.xcworkspace` for this project from now on.

Integrating target `Pods-App` (`../../../../var/folders/3q/hmntnm3j241gqdgwlxsst82m0000gn/T/CocoaPods/Lint/App.xcodeproj` project)
  Adding Build Phase '[CP] Embed Pods Frameworks' to project.
  Adding Build Phase '[CP] Copy Pods Resources' to project.
  Adding Build Phase '[CP] Check Pods Manifest.lock' to project.
  - Running post install hooks

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild.

...

=== CLEAN TARGET ZipUtilities OF PROJECT Pods WITH CONFIGURATION Release ===

...

=== CLEAN TARGET Pods-App OF PROJECT Pods WITH CONFIGURATION Release ===

...

=== CLEAN TARGET App OF PROJECT App WITH CONFIGURATION Release ===

...
** CLEAN SUCCEEDED **

=== BUILD TARGET ZipUtilities OF PROJECT Pods WITH CONFIGURATION Release ===

...

=== BUILD TARGET App OF PROJECT App WITH CONFIGURATION Release ===

** BUILD SUCCEEDED **

 -> ZipUtilities (1.8.0)

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.1.1\r\nAuthorization: Token 57d921ffd701dbb7d28ea450894a3f26\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 709\r\n\r\n"
<- "{\"name\":\"ZipUtilities\",\"version\":\"1.8.0\",\"summary\":\"Zip Archiving, Unarchiving and Utilities in Objective-C\",\"description\":\"ZipUtilities, prefixed with NOZ for Nolan O'Brien ZipUtilities, is a library of zipping and unzipping utilities for iOS and Mac OS X.\",\"homepage\":\"https://github.com/NSProgrammer/ZipUtilities\",\"license\":{\"type\":\"MIT\",\"file\":\"LICENSE\"},\"authors\":\"Nolan O'Brien\",\"social_media_url\":\"https://twitter.com/NolanOBrien\",\"platforms\":{\"ios\":\"6.0\",\"osx\":\"10.9\"},\"source\":{\"git\":\"https://github.com/NSProgrammer/ZipUtilities.git\",\"tag\":\"1.8.0\"},\"source_files\":\"ZipUtilities/*.{h,m}\",\"exclude_files\":[\"ZipUtilities/ZipUtilities.h\",\"ZipUtilities/*Info.plist\"],\"libraries\":\"z\",\"requires_arc\":true}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Thu, 17 Nov 2016 23:52:46 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk.rb:70:in `print_error'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk.rb:30:in `request_url'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk.rb:36:in `request_path'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:79:in `push_to_trunk'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:65:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by rlepinski** [comment]
Same here. Looks like it broke the pod spec page - https://cocoapods.org/pods/UrbanAirship-iOS-SDK

**Comment by segiddins** [comment]
This is being tracked by https://github.com/CocoaPods/trunk.cocoapods.org/issues/207.
