### ISSUE TITLE
ld: framework not found for architecture x86_64

### ISSUE THREAD

**Issue by goktugyil** [CocoaPods/CocoaPods#6203]
# Report

http://stackoverflow.com/questions/40615168/ld-framework-not-found-for-architecture-x86-64

```
ld: framework not found QorumLogs for architecture x86_64  
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
I'm getting this in my test files which used to work for months now. 

## What did you do?

The only thing I've changed recently is, update cocoapods, (QorumLogs is a pod), then installed Smooch.io pod, then for the first time added objective-c bridging header, created some Obj-C files and imported smooch.io framework.

Using Xcode 7.3, what can be the problem? Also haven't updated cocoapods itself. 

## CocoaPods Environment

My cocoapods version: /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods.rb

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : magnetsystems - https://github.com/magnetsystems/Specs.git @ d3d11c9a95845bc07ce583a651c018f85bdef1c4
               master - https://github.com/CocoaPods/Specs.git @ 8c237408f39adffa32f9bdae4a19f03326b3f102
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

While this says Xcode8. I have both 8 and 7.3 installed in my mac. And in this context I'm using 7.3

**Comment by hansemannn** [comment]
Start by using a stable version of Cocoapods, e.g. 1.1.1 by running `gem install cocoapods`. Might be an RC issue - you are currently running 1.1.0-rc.2

**Comment by yusuftor** [comment]
I'm getting the exact same error! All I did was upgrade to the latest cocoapods. It appears to only happen to the objective-c libraries that I'm installing for my Swift project. To solve it I had to include these objective-c libraries in both the target of the app and its test target in the podfile. Seems like a bug to me.

**Comment by goktugyil** [comment]
Updated pod version to:

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods.rb

Still getting this error:

Tests.swift:10:8: No such module 'QorumLogs'

This is happening to my Swift libraries. But I've installed an objective-c library, which I'm not using in my tests. 

I've also tried going to Test Target and adding my framework or Pods framework manually to: "Link Binary With Libraries" 

Nothing worked

**Comment by goktugyil** [comment]
target :AppTests do
    …
end

This worked for some reason...
