### ISSUE TITLE
Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1'

### ISSUE THREAD

**Issue by artud2000** [CocoaPods/CocoaPods#6204]
My cocoapods stopped. I haven't run pod install in few weeks, I tried to run pod install and it didn't work.

Xcode 8.1 (8B62)

# Report

## What did you do?
sudo gem install cocoapods
pod install
Also tried using pod setup first. 
then pod install

I also tried setting master manually 

cd ~/.cocoapods/repos
git clone https://github.com/CocoaPods/Specs.git

Then move to my project folder again

pod install

## What did you expect to happen?
It installs the pods succesfully

## What happened instead?
Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1'.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 1.8.4
Ruby lib dir : /Users/arturofernandez-espinosa/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 97c08dcc22a21aa03fbb3b6436e2572b7799dae1
               Specs - https://github.com/CocoaPods/Specs.git @ ce206c576821c58f8daf8ab3e68f3ae32cc890fb
```

### Installation Source

```
Executable Path: /Users/arturofernandez-espinosa/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '7.0'
use_frameworks!


target :'Dictionary' do
    pod 'Google-Mobile-Ads-SDK'
    pod 'google-plus-ios-sdk'
    pod 'MobileAppTracker', '3.10.0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'GoogleAppIndexing'
end

target :'DictionaryAdLite' do
    pod 'Google-Mobile-Ads-SDK'
    pod 'google-plus-ios-sdk'
    pod 'MobileAppTracker', '3.10.0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'GoogleAppIndexing'
end

target :'DictionaryUnitTestBundle' do
    pod 'MobileAppTracker', '3.10.0'
    pod 'Google-Mobile-Ads-SDK'
    pod 'google-plus-ios-sdk'
    pod 'GoogleAppIndexing'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'GoogleAppIndexing'
end

#target :'DictionaryUITests' do
#    pod 'MobileAppTracker', '3.10.0'
#    pod 'Google-Mobile-Ads-SDK'
#    pod 'google-plus-ios-sdk'
#    pod 'GoogleAppIndexing'
#    pod 'Fabric'
#    pod 'Crashlytics'
#end
```

Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
Setting up CocoaPods master repo
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

**Comment by segiddins** [comment]
Please update to a newer version of `git`, CocoaPods requires 1.8.5+, https://github.com/CocoaPods/CocoaPods/pull/6174 will make this a more helpful error

**Comment by artud2000** [comment]
Thanks, updating git solved my issue
