### ISSUE TITLE
ijkplayer&Cocoapods : excute 'pod lib lint' BUILD FAILED with fatal error: 'libavformat/avformat.h' file not found

### ISSUE THREAD

**Issue by hemypie** [CocoaPods/CocoaPods#6210]
# Report

## What did you do?

ℹ pod lib lint  

## What did you expect to happen?

ℹ i want " pod lib lint" pass validation

## What happened instead?

ℹ fatal error: 'libavformat/avformat.h' file not found

## CocoaPods Environment

ℹ    CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12 
       Xcode : 8.0
         Git : git version 2.10.1

## Project that demonstrates the issue

ℹ  project:  https://github.com/DerekLix/myproject

**Comment by hemypie** [comment]
Could anyone give some advices ?

**Comment by benasher44** [comment]
To preface, I don't have all that much experience integrating static libs in a podspec. I usually just end up making podspecs specifically for them and then pushing them to a private repo, and that way you can just add them like a standard pod dependency.

That aside, just by looking at your podspec, the `s.libraries` like doesn't look accurate. It's going to look for those libraries at the root of your repo, since you haven't specified paths, but I can see that the libraries in question are located at `CoIJKPlayerFramework/Classes/FFMPEG/lib`

**Comment by hemypie** [comment]
Thank you @benasher44 input:
  (1) if i push FFMPEG/lib  into a private repo, the podspec's dependency don't allow private git path, and don't resolve the file paths
(2) the paths also confuse me , i set header search paths in project, the project can compile success, but the podspec  validate failure. 
I guess whether the cocoa pods doesn't support the nest file paths in this way？

**Comment by benasher44** [comment]
I'm not sure what you mean about (2), but for (1) you'll need to setup a private specs repo, and the specs there can point to the private versions of your pod. Checkout https://guides.cocoapods.org/making/private-cocoapods.html for more info.

**Comment by hemypie** [comment]
Thanks, i'll try your way.

**Comment by benasher44** [comment]
@hemypie also checkout #6245. I was just discussing different ways of integrating local frameworks/libs that are lighter weight than setting up a private specs repo.

**Comment by hemypie** [comment]
Thanks @benasher44 , we've integrated local static(or dynamic) framework project, but we want to set up our private specs repo, so the way #6245 doesn't fit us.

**Comment by benasher44** [comment]
Going to close this one. This doesn't appear to be a bug in CocoaPods and is more of a question of how to use a private specs repo. I certainly don't mind discussing this further here, but I don't think there's any action we can take to patch CP. Thanks for filing!
