### ISSUE TITLE
Clone Specs master repository 

### ISSUE THREAD

**Issue by kokigit** [CocoaPods/CocoaPods#6211]
# Report

## What did you do?

Run `pod setup`

## What did you expect to happen?

Setting up CocoaPods master repo without cloning all the history of master branch of the Specs repository

## What happened instead?
 
it's cloning with the entire history of master branch (915889 objects)

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/Kokila/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ff26ba3f6e9adc0f9feed8bdac8fd80e94cd59c4
```

### Installation Source

```
Executable Path: /Users/Kokila/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'CameraEngineExample' do
  pod 'CameraEngine'
  pod 'PBJVideoPlayer'
  pod 'FCFileManager'
  pod 'FLAnimatedImage'
end
```

## What I suggest is,

Clone Specs repo using git shallow clone inside the setup.rb. As I noticed it's reduced setup time. that's how I did pod setup manually(only the cloning)

```
cd ~/.cocoapods/repos 
git clone http://github.com/CocoaPods/Specs.git master --depth=1

Receiving objects: 100% (269552/269552), 45.55 MiB | 217.00 KiB/s, done.
```

**Comment by DanToml** [comment]
Unfortunately, it is not possible to use a shallow clone of the specs repository as it causes an unreasonable load on GitHub's servers (see http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/ and http://blog.cocoapods.org/Sharding/ for more information and ways in which we are trying to improve performance).

**Comment by kokigit** [comment]
@DanToml  Thanks for the heads up. I didn't see that blog post before. it's informative
