### ISSUE TITLE
pod spec lint - 'XMPP.h' file not found

### ISSUE THREAD

**Issue by linhcn** [CocoaPods/CocoaPods#6212]
# Report

## What did you do?

Previously, I integrated XMPPFramework by using dependencies in podspec: `s.dependency 'XMPPFramework', '3.6.6'`

I'm aware that in order to fix the error of 'Redefinition of module dnssd'. We should pod directly from the master branch: `pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'` 

Unfortunately, we cannot use dependencies without version, so I commented the dependency out and used pull XMPPFramework using podfile. I fixed some minor issues and was able to build the app, but when I tried to do `pod spec lint` I got the following error:

`- NOTE  | xcodebuild:  PHMessaging/PHMessaging/Classes/PHMessagingManager.h:20:9: fatal error: 'XMPP.h' file not found
    - NOTE  | xcodebuild:  PHMessaging/PHMessaging/Classes/PHBasicConversationViewController.h:10:9: fatal error: 'XMPPFramework/XMPPUser.h' file not found`

## What did you expect to happen?

As you can see, I want to push up the PHMessaging as a library to pod it in other projects, but it seems impossible now as it didn't pass the validations

## CocoaPods Environment

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bitbucket-cocoapods-specs - git@bitbucket.org:philology/cocoapods-specs.git @ 2109a80e904794b8a854d13180a7876254a51dc3
               bitbucket-cocoapods-specs-1 - https://RicolWang@bitbucket.org/philology/cocoapods-specs.git @ 2109a80e904794b8a854d13180a7876254a51dc3
               bitbucket-cocoapods-specs-2 - https://philip_cookson@bitbucket.org/philology/cocoapods-specs.git @ 2109a80e904794b8a854d13180a7876254a51dc3
               bitbucket-phcommon - https://philip_cookson@bitbucket.org/philology/phcommon.git @ 0cdeb1e27637f5cec1e3d8cdafcf755d44afe0e4
               bitbucket-prototype - https://philip_cookson@bitbucket.org/philology/prototype.git @ 39efa48f0c467b818db0f71e6ff4e5639c599df8
               master - https://github.com/CocoaPods/Specs.git @ cdf39f39f5f6bcc5d29060c11de34c23c7d69aac
               org:philology -  @ fatal: Not a git repository (or any of the parent directories): .git
               phf - https://philip_cookson@bitbucket.org/philology/phfileexplorer.git @ 2f15da0597b2e48c6ce93fb52471adab9499f760
               phfe - git@bitbucket.org:philology/PHFileExplorer.git @ 2f15da0597b2e48c6ce93fb52471adab9499f760
               phfile - git@bitbucket.org:philology/cocoapods-specs.git @ 2109a80e904794b8a854d13180a7876254a51dc3
               phfileexplorer - git@bitbucket.org:philology/phfileexplorer.git @ 2f15da0597b2e48c6ce93fb52471adab9499f760
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
`````

**Comment by benasher44** [comment]
Just to clarify, `pod spec lint` will always fetch the sources from the remote. If you're trying to verify local changes, you'll want to do `pod lib lint`. Is that the case, or am I misunderstanding?

**Comment by linhcn** [comment]
From [CocoaPods's guides](https://guides.cocoapods.org/making/using-pod-lib-create.html): 

> So you've got your library ready to go. First you should check if the Podspec lints correctly, as you can't deploy with errors. This can be done with two methods, pod lib lint and pod spec lint. The difference between them is that pod lib lint does not access the network, whereas pod spec lint checks the external repo and associated tag.

I just run both `pod spec lint` and `pod lib lint` again and I got the following failure: 

`The following build commands failed:
	CompileC /.../Xcode/DerivedData/App-fkngqolqzwwzlqgamaneaeervogt/Build/Intermediates/Pods.build/Release-iphonesimulator/PHMessaging.build/Objects-normal/i386/PHBasicConversationViewController.o PHMessaging/PHMessaging/Classes/PHBasicConversationViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler`

Any ideas?

**Comment by benasher44** [comment]
Can you share the podspec for the pod you're linting?

**Comment by linhcn** [comment]
@benasher44 FYI,

`Pod::Spec.new do |s|
  s.name         = "PHMessaging"
  s.version      = "0.3.6"
  s.platform     = :ios, '8.0'
  s.summary      = "PHMessaging. XMPP chat framework!"
  s.homepage     = "https://bitbucket.org/philology/phmessaging"
  s.license      = {
     :type => 'Philology',
     :text => <<-LICENSE
              Copyright (C) 2013 Philology Pty. Ltd.

              All rights reserved.
     LICENSE
  }
  s.author       = { "Ashton Williams" => "Ashton.Williams@philology.com.au", "Ricol Wang" => "Ricol.Wang@philology.com.au" }
  s.source       = { :git => "https://RicolWang@bitbucket.org/philology/phmessaging.git", :tag => s.version.to_s }
  s.source_files = 'PHMessaging/Classes', 'PHMessaging/Classes/**/*.{h,m}'
  s.resources    = 'PHMessaging/Classes/*.storyboard', 'PHMessaging/Resources/*.png', 'PHMessaging/Classes/*.lproj', 'PHMessaging/Classes/*.xib'
  s.frameworks   = 'CoreData', 'CoreLocation', 'Security', 'CFNetwork', 'SystemConfiguration'
  s.libraries    = 'xml2', 'resolv'
  s.xcconfig     = {
 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2 $(PODS_ROOT)/XMPPFramework/module',
'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
'OTHER_LDFLAGS' => '"$(inherited)" "-lxml2" "-objc"'
}
  s.requires_arc = true
  s.dependency 'JSQSystemSoundPlayer', '1.5.2'
  s.dependency 'JSMessagesViewController', '4.0.4'
  s.dependency 'CocoaLumberjack', '<=2.0.0'
  s.dependency 'CocoaAsyncSocket'
  #s.dependency 'XMPPFramework'
  s.dependency 'PHCommon', '>=0.4.2'
end`

**Comment by linhcn** [comment]
`Pod::Spec.new do |s|
  s.name         = "PHMessaging"
  s.version      = "0.3.6"
  s.platform     = :ios, '8.0'
  s.summary      = "PHMessaging. XMPP chat framework!"
  s.homepage     = "https://bitbucket.org/philology/phmessaging"
  s.license      = {
     :type => 'Philology',
     :text => <<-LICENSE
              Copyright (C) 2013 Philology Pty. Ltd.

              All rights reserved.
     LICENSE
  }
  s.author       = { "Ashton Williams" => "Ashton.Williams@philology.com.au", "Ricol Wang" => "Ricol.Wang@philology.com.au" }
  s.source       = { :git => "https://RicolWang@bitbucket.org/philology/phmessaging.git", :tag => s.version.to_s }
  s.source_files = 'PHMessaging/Classes', 'PHMessaging/Classes/**/*.{h,m}'
  s.resources    = 'PHMessaging/Classes/*.storyboard', 'PHMessaging/Resources/*.png', 'PHMessaging/Classes/*.lproj', 'PHMessaging/Classes/*.xib'
  s.frameworks   = 'CoreData', 'CoreLocation', 'Security', 'CFNetwork', 'SystemConfiguration'
  s.libraries    = 'xml2', 'resolv'
  s.xcconfig     = {
 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2 $(PODS_ROOT)/XMPPFramework/module',
'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
'OTHER_LDFLAGS' => '"$(inherited)" "-lxml2" "-objc"'
}
  s.requires_arc = true
  s.dependency 'JSQSystemSoundPlayer', '1.5.2'
  s.dependency 'JSMessagesViewController', '4.0.4'
  s.dependency 'CocoaLumberjack', '<=2.0.0'
  s.dependency 'CocoaAsyncSocket'
  #s.dependency 'XMPPFramework'
  s.dependency 'PHCommon', '>=0.4.2'
end

`

**Comment by linhcn** [comment]
```
Pod::Spec.new do |s|
  s.name         = "PHMessaging"
  s.version      = "0.3.6"
  s.platform     = :ios, '8.0'
  s.summary      = "PHMessaging. XMPP chat framework!"
  s.homepage     = "https://bitbucket.org/philology/phmessaging"
  s.license      = {
     :type => 'Philology',
     :text => <<-LICENSE
              Copyright (C) 2013 Philology Pty. Ltd.

              All rights reserved.
     LICENSE
  }
  s.author       = { "Ashton Williams" => "Ashton.Williams@philology.com.au", "Ricol Wang" => "Ricol.Wang@philology.com.au" }
  s.source       = { :git => "https://RicolWang@bitbucket.org/philology/phmessaging.git", :tag => s.version.to_s }
  s.source_files = 'PHMessaging/Classes', 'PHMessaging/Classes/**/*.{h,m}'
  s.resources    = 'PHMessaging/Classes/*.storyboard', 'PHMessaging/Resources/*.png', 'PHMessaging/Classes/*.lproj', 'PHMessaging/Classes/*.xib'
  s.frameworks   = 'CoreData', 'CoreLocation', 'Security', 'CFNetwork', 'SystemConfiguration'
  s.libraries    = 'xml2', 'resolv'
  s.xcconfig     = {
 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2 $(PODS_ROOT)/XMPPFramework/module',
'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
'OTHER_LDFLAGS' => '"$(inherited)" "-lxml2" "-objc"'
}
  s.requires_arc = true
  s.dependency 'JSQSystemSoundPlayer', '1.5.2'
  s.dependency 'JSMessagesViewController', '4.0.4'
  s.dependency 'CocoaLumberjack', '<=2.0.0'
  s.dependency 'CocoaAsyncSocket'
  #s.dependency 'XMPPFramework'
  s.dependency 'PHCommon', '>=0.4.2'
end

```

**Comment by benasher44** [comment]
@linhcn is XMPP.h in XMPPFramework?

**Comment by linhcn** [comment]
Yes, it is.

In my Podspec file I have commented `#s.dependency 'XMPPFramework'` out, but I did import the framework using Podfile:

`pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'`

**Comment by benasher44** [comment]
@linhcn unfortunately `pod lib lint` doesn't use anything from your Podfile. It only honors your podspec. You'll need a working version of XMPPFramework as a podspec dependency

**Comment by linhcn** [comment]
@benasher44 Thank you. But that's also my question, how could I use dependency for XMPPFramework in my Podspec file. If I simply do `s.dependency 'XMPPFramework'` then I will face the error `Redefinition of module dnssd`. Meanwhile, there is no way for me to add something like `s.dependency 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'` in my Podspec as it requires clearly pointing the version of the framework.

**Comment by benasher44** [comment]
You would push a new version of XMPPFramework to your private specs repo, and that spec would point at the commit you need.

**Comment by benasher44** [comment]
@linhcn you can also use the `:podspec` arg in your Podfile to point a podspec locally in your current repo to avoid having to create a private specs repo. Then, you can modify the podspec there to point to whatever commit for XMPPFramework you need.

**Comment by benasher44** [comment]
Yep! But that syntax isn't quite right. It'd be `pod 'PodName', :podspec => 'path_to_podspec'`, and then you can define in the podspec exactly which commit you want that pod to point to.

**Comment by benasher44** [comment]
Oh you know what. I'm sorry. I got confused. You'll have to setup a private specs repo and have a new podspec with a pod called "PodNameMyFork" wherein the podspec there points to the commit you need. Sorry about that. I have a few threads going like this where people want to do more customized things, and I got confused.

**Comment by linhcn** [comment]
No worries @benasher44 It sounds right. I'll try later. Thanks.

**Comment by benasher44** [comment]
Going to close this one. This doesn't appear to be a bug in CocoaPods and is more of a question of how to manage public and private dependencies. I certainly don't mind discussing this further here, but I don't think there's any action we can take to patch CP. Thanks for filing!
