### ISSUE TITLE
LoadError - cannot load such file -- nanaimo

### ISSUE THREAD

**Issue by matzew** [CocoaPods/CocoaPods#6214]
### Command

```
/Users/matzew/.rvm/gems/ruby-2.1.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin14.0]
    RubyGems : 2.6.3
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/matzew/.rvm/rubies/ruby-2.1.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1a71b0c02bed2b5c7bbea27b9be221c870f3ed6b
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

project 'welcome-ios-swift.xcodeproj'
platform :ios, '8.0'
use_frameworks!

target 'welcome-ios-swift' do
	pod 'FeedHenry',  '5.0.0'
	pod 'SWRevealViewController', '~> 2.3'
end
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/matzew/.rvm/gems/ruby-2.1.0@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/matzew/.rvm/gems/ruby-2.1.0/bin/pod:22:in `load'
/Users/matzew/.rvm/gems/ruby-2.1.0/bin/pod:22:in `<main>'
```

**Comment by matzew** [comment]
I've see https://github.com/CocoaPods/CocoaPods/issues/6124

but the suggested workaround did not work for me

**Comment by segiddins** [comment]
What's the output of `gem env`, `gem which nanaimo`, and `ruby -rcocoapods -rnanaimo -e 'puts "all installed"'` ?

**Comment by matzew** [comment]
here we go:

```
gem env
/Users/matzew/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/commands/environment_command.rb:154: warning: Insecure world writable dir /Apache/maven in PATH, mode 040777
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.3
  - RUBY VERSION: 2.1.0 (2013-12-25 patchlevel 0) [x86_64-darwin14.0]
  - INSTALLATION DIRECTORY: /Users/matzew/.rvm/gems/ruby-2.1.0
  - USER INSTALLATION DIRECTORY: /Users/matzew/.gem/ruby/2.1.0
  - RUBY EXECUTABLE: /Users/matzew/.rvm/rubies/ruby-2.1.0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/matzew/.rvm/gems/ruby-2.1.0/bin
  - SPEC CACHE DIRECTORY: /Users/matzew/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/matzew/.rvm/gems/ruby-2.1.0
     - /Users/matzew/.rvm/gems/ruby-2.1.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/matzew/.rvm/gems/ruby-2.1.0/bin
     - /Users/matzew/.rvm/gems/ruby-2.1.0@global/bin
     - /Users/matzew/.rvm/rubies/ruby-2.1.0/bin
     - /Users/matzew/.yarn/bin
     - /Users/matzew/.nvm/versions/node/v4.4.5/bin
     - /opt/chefdk/bin
     - /Applications/Postgres.app/Contents/Versions/9.3/bin
     - /Users/matzew/miniconda3/bin
     - /Volumes/Macintosh HD/ANDROID_HOME/current/platform-tools
     - /Volumes/Macintosh HD/ANDROID_HOME/current/tools
     - /Users/matzew/gradle/current/bin
     - /Apache/maven/current/bin
     - /Users/matzew/SCALA/current/bin
     - /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/MacGPG2/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/bin
     - /Users/matzew/local/bin
     - /Users/matzew/go/bin
     - /Users/matzew/.rvm/bin
```

next was: 
```
gem which nanaimo
/Users/matzew/.rvm/gems/ruby-2.1.0/gems/nanaimo-0.2.2/lib/nanaimo.rb
```

and finally:
```
ruby -rcocoapods -rnanaimo -e 'puts "all installed"'
all installed
```

**Comment by segiddins** [comment]
Then everything should be installed properly, and this looks like a configuration issue with your ruby installation? I'm not sure what else the issue could be

**Comment by Blackjacx** [comment]
I have the same Issue and the same output like above.

**Comment by Blackjacx** [comment]
### Command

```
/Users/stherold/.gem/bin/pod lib lint --verbose --allow-warnings
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C48b)
       Xcode : 8.1 (8B62)
         Git : git version 2.8.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : flinc-specs - git@github.com:flinc/Specs.git @ 192392f3723f114256027f3b6eeed670fe3f3f1b
               master - https://github.com/CocoaPods/Specs.git @ 89e42a5aef752263decc68df8c419c8dcd5509f3
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'SHSearchBar' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SHSearchBar

  target 'SHSearchBarTests' do
    pod 'Quick'
    pod 'Nimble'
  end

end


post_install do |installer|
   installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Users/stherold/.gem/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `block in save'
/Users/stherold/.gem/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `open'
/Users/stherold/.gem/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:353:in `save'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:410:in `create_app_project'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:298:in `block in perform_extensive_analysis'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:293:in `each'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:293:in `perform_extensive_analysis'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:79:in `validate'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/command/lib/lint.rb:62:in `block in run'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/command/lib/lint.rb:50:in `each'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/command/lib/lint.rb:50:in `run'
/Users/stherold/.gem/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/stherold/.gem/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/stherold/.gem/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/stherold/.gem/bin/pod:23:in `load'
/Users/stherold/.gem/bin/pod:23:in `<main>'
```

**Comment by Blackjacx** [comment]
This worked for me: https://github.com/CocoaPods/CocoaPods/issues/6106

**Comment by matzew** [comment]
not for me :-(

**Comment by marija17** [comment]
I was able to get around this by using the bundler:
I ran `bundle install` and then `bundle exec pod install`

**Comment by andromedane** [comment]
## Command
`/usr/local/bin/pod install`

## Report 
* What did you do?

* What did you expect to happen?

* What happened instead?

## Stack 
```
CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3d72b7d29a2bd2ea39cf803dfb5704fed854fdf0
```
### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
 platform :ios, ’10.0’

target 'YoutubeOdevi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YoutubeOdevi
	pod 'Alamofire'
    	pod 'AlamofireImage'
    	pod 'SCLAlertView'
    	pod 'SwiftyJSON'

 end
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

\\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- \\ -- -- \\ -- \\ -- \\ -- \\ -- \\ 

I tried too much, but i couldn't find any solution to this. Do you have any ideas or solution?

**Comment by BrianBatchelder** [comment]
Uninstalling nanaimo-0.2.2 did it for me. Now I only have nanaimo-0.2.3.

**Comment by andromedane** [comment]
When i try to uninstall nanaimo-0.2.2 it throws an error like this. 
I'm kinda new on this subjects, and it's gonna be really tough for me. 
```
Select gem to uninstall:
 1. nanaimo-0.1.2
 2. nanaimo-0.2.2
 3. nanaimo-0.2.3
 4. All versions
> 2
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.
```

**Comment by BrianBatchelder** [comment]
You might need to run "sudo gem uninstall". Or, perhaps, you might try uninstalling nanaimo-0.1.2.

**Comment by andromedane** [comment]
When i try with "Sudo", it worked !! @BrianBatchelder Thank you so much !! :)) Now i can install my pods :)

**Comment by Ashton-W** [comment]
I got this with just `pod init` in the directory of a brand new project. Uninstalling all versions of *nanaimo* and reinstalling cocoapods fixed it.


### Command

```
/Users/ashton/.rbenv/versions/2.1.3/bin/pod init
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin16.0]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.11.0
Ruby lib dir : /Users/ashton/.rbenv/versions/2.1.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ad4d4fb66ff19c75b633bdbe5be65bcf66df3de0
               REDACTED
```

### Plugins

```
claide-plugins               : 0.9.0
cocoapods-acknowledgements   : 1.1.2
cocoapods-art                : 0.9.5
cocoapods-deintegrate        : 1.0.1
cocoapods-keys               : 1.7.0
cocoapods-open               : 0.0.8
cocoapods-playgrounds        : 1.2.2
cocoapods-plugins            : 1.0.0
cocoapods-search             : 1.0.0
cocoapods-stats              : 1.0.0
cocoapods-trunk              : 1.1.1
cocoapods-try                : 1.1.0
cocoapods-update-if-you-dare : 0.1.1
slather                      : 2.2.1
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-1.0.1/lib/claide/command.rb:333:in `run'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/ashton/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/ashton/.rbenv/versions/2.1.3/bin/pod:22:in `load'
/Users/ashton/.rbenv/versions/2.1.3/bin/pod:22:in `<main>'
```

**Comment by joeFlypay** [comment]
@BrianBatchelder that totally works, you rock!
I've just been tearing my hair out for a whole day over this issue, trying & failing to get xcodeproj  up and running, and your fix has solved my issue.
For anyone else in my situation, the TLDR on this issue is as follows: 
If you are trying to use xcodeproj and you are seeing the error ```cannot load such file -- nanaimo (LoadError)```, then all you just need to run ```sudo gem uninstall nanaimo``` and uninstall all versions of nanaimo apart from 0.2.3.
Thanks.

**Comment by jsajadi** [comment]
I had the same issue, but now, after uninstalling "nanaimo  0.2.2" ("gem uninstall nanaimo -v 0.2.2"), everything is ok.

**Comment by manojmahapatra** [comment]
`sudo gem uninstall nanaimo` and I uninstalled all the versions and reinstalling again did worked for me.

**Comment by yopesoios** [comment]
sudo gem uninstall nanaimo -> all
sudo gem install nanaimo
pod install -> enjoy

**Comment by AnilTodkar** [comment]
I have same error above.
.
I tried 

gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14.1
  - RUBY VERSION: 2.0.0 (2015-12-16 patchlevel 648) [universal.x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-16
  - GEM PATHS:
     - /Library/Ruby/Gems/2.0.0
     - /Users/alluresoft/.gem/ruby/2.0.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/


Next:
.
gem which nanaimo
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo.rb


Next:
.
ruby -rcocoapods -rnanaimo -e 'put "all install"'
-e:1:in `<main>': undefined method `put' for main:Object (NoMethodError)

**Comment by h-bomb** [comment]
@BrianBatchelder and @joeFlypay - thank you both! In my case it was multiple versions of `cfpropertylist` (instead of `nanaimo`).

**Comment by zhiyuzhao** [comment]
@h-bomb  work for me. THX

**Comment by scinfu** [comment]
uninstall nanaimo work for me

```
gem list | grep nanaimo //print nanaimo (0.2.3, 0.2.2)
gem ininstall nanaimo -v 0.2.2
```
I removed oldest version

**Comment by Wiingaard** [comment]
I have the same issue, none of the above suggestions has solved my problem.
I've tried reinstalling nanaimo and cfpropertylist, but I'm still not able to successfully run pod init.

`pod init` :

> ### Stack
> 
> ```
>    CocoaPods : 1.1.1
>         Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
>     RubyGems : 2.0.14.1
>         Host : Mac OS X 10.12.2 (16C67)
>        Xcode : 8.2.1 (8C1002)
>          Git : git version 2.10.1 (Apple Git-78)
> Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
> Repositories : donkeyrepublic - https://github.com/DonkeyRepublic/Specs.git @ 8cac59f8de28e6eafada46d18fc3c66e64feb044
>                master - https://github.com/CocoaPods/Specs.git @ ba5486178e4b2edccb0ce629c93d76886ea6e5af
> ```
> 
> ### Plugins
> 
> ```
> cocoapods-deintegrate : 1.0.1
> cocoapods-plugins     : 1.0.0
> cocoapods-search      : 1.0.0
> cocoapods-stats       : 1.0.0
> cocoapods-trunk       : 1.1.1
> cocoapods-try         : 1.1.0
> ```
> 
> ### Error
> 
> ```
> LoadError - cannot load such file -- nanaimo
> /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
> /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
> /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/init.rb:41:in `validate!'
> /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:333:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
> /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'
> ```

`gem which nanaimo` :

> /usr/local/lib/ruby/gems/2.4.0/gems/nanaimo-0.2.3/lib/nanaimo.rb

`ruby -rcocoapods -rnanaimo -e 'put "all install"'`

> /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cocoapods (LoadError)
> 	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
>

**Comment by benasher44** [comment]
Hi everyone! Thanks for sharing all of the workarounds and solutions to help restore people's ruby/gem setups! This appears to be an issue with people's local ruby/gem setups, so there's nothing we can do to patch CocoaPods to help fix this. Because there's no action we can take on our end, I'm going to close this issue. However, please feel free to open a new issue and fill out the issue template if you feel that your issue is a CocoaPods bug. Have a great day!

**Comment by vinicemanuel** [comment]
update your gem

**Comment by apokharel** [comment]
so i encountered this on 10.11. running gem clean up helped.

**Comment by ramakrishna013** [comment]
Uninstalling the `nanaimo` all versions and reinstalling the `nanaimo` is worked for me.

**Comment by Wiingaard** [comment]
I installed rbenv and installed a new version of Ruby (2.3.0) and set it as global Ruby version. Then I reinstalled CocoaPods with that version of Ruby. After that I was able to pod init.

**Comment by mvalbuquerque** [comment]
i have fixed i 

uninstall nanaimo 

gem list | grep nanaimo //print nanaimo (0.2.3, 0.2.2)
gem ininstall nanaimo -v 0.2.2


sudo gem uninstall nanaimo -> all
sudo gem install nanaimo
pod install -> enjoy

**Comment by X901** [comment]
@mvalbuquerque Thank you , you answer worked for me

**Comment by pawriwes** [comment]
just delete one of the nanaimo, and keep the latest version. Doing this worked for me.

**Comment by emrahgunduz** [comment]
a `sudo gem update` solved the error for me.

**Comment by phanisai4u** [comment]
Thanks @emrahgunduz

**Comment by liuyan3176** [comment]
Thanks @emrahgunduz 
and what is nanaimo?....

**Comment by theewind** [comment]
I resolve this problem when i switch ruby version 2.1.1 to 2.2.4

**Comment by hilalbaig** [comment]
I fixied it by first uninstalling cocoapods `sudo gem uninstall cocoapods` and then installing it again `sudo gem cocoapods`

**Comment by cokeduo** [comment]
1.  rvm gemset empty
2. gem install bundler
3. bundle install
then pod install

**Comment by shanglina** [comment]
remove all version nanaimo and reinstall  works !

sudo gem uninstall nanaimo -> all

sudo gem install nanaimo

cd your tagart

pod install -> enjoy

**Comment by matteocollina** [comment]
`gem uninstall nanaimo` works for me

**Comment by chellongCoder** [comment]
i ran `sudo gem uninstall nanaimo` and select `1. nanaimo-0.2.5` and it worked for me
