### ISSUE TITLE
XCode 6.3.2 issue pushing to CocoaPods master, /usr/bin/xcrun simctl list -j devices

### ISSUE THREAD

**Issue by DominicDeCesare-Capita** [CocoaPods/CocoaPods#6215]
# Report

We are going through a process of rebranding following acquisition and I'm trying to push a new named version if our Podspec to master, with plans to then deprecate the version with the out of date branding.

## What did you do?

pod trunk push Pay360Payments.podspec --allow-warnings

## What did you expect to happen?

Pushed Podspec to master, allow us to then deprecate the old version on outdated branding.

## What happened instead?
Validating podspec

 -> Pay360Payments (2.0.0)
    - WARN  | url: There was a problem validating the URL www.example.com/screenshots_1.
    - WARN  | url: There was a problem validating the URL www.example.com/screenshots_2.
    - ERROR | [iOS] unknown: Encountered an unknown error (/usr/bin/xcrun simctl list -j devices

Usage: simctl list [devices|devicetypes|runtimes]
) during validation.

[!] The spec did not pass validation, due to 1 error.

### Stack

```
   CocoaPods : 1.1.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 6.3.2 (6D2105)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ abf442b4a2c70c1c8203474a4ef84a32b957b693
```

### Installation Source

```
Executable Path: /usr/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/pay360/mobilesdk-ios

**Comment by dnkoutso** [comment]
This is due to https://github.com/CocoaPods/CocoaPods/issues/5956 which was fixed by https://github.com/CocoaPods/fourflusher/pull/6.

If you are still on Xcode 6 either: a) update to xcode7 or xcode8, or b) downgrade the `fourflusher` gem to 1.x version and continue using xcode 6

**Comment by DominicDeCesare-Capita** [comment]
Thanks

**Comment by benasher44** [comment]
Yes pod validation no longer works with Xcode 6, since we upgraded to use fourflusher 2, which finds newer simulators more reliably. Thanks for filing!
