### ISSUE TITLE
Cocoapod podspec version is missing.

### ISSUE THREAD

**Issue by BenMaer** [CocoaPods/CocoaPods#6219]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Tried to

* pod install
* trunk delete
* trunk push
a cocoapod version.

## What did you expect to happen?

* Pod install failed, telling me:

> [!] Unable to find a specification for `RIRImageResizing (= 0.1.0)`

* Trunk Delete (`pod trunk delete RIRImageResizing 0.1.0`) failed, telling me:

> [!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

*Trunk Push (`pod trunk push RIRImageResizing.podspec`) failed, telling me:

> [!] Unable to accept duplicate entry for: RIRImageResizing (0.1.0)

## What happened instead?

Explained in above section.

## CocoaPods Environment

For project with `pod install` failure:
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/benjaminmaer/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c68a2d83237ad02a4451b4ca3375f0ea649fd413
```

### Installation Source

```
Executable Path: /Users/benjaminmaer/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Shimmur' do
	pod 'TwitterCore', '1.9.0'
	pod 'TwitterKit', '1.9.0'

	pod 'SVPullToRefresh', '0.4.1'
	pod 'RestKit', '0.27.0'
	pod 'SDWebImage', '3.7.3'
	pod 'UIActionSheet+Blocks', '0.9'
	pod 'TTTAttributedLabel', '2.0.0'
	pod 'FXReachability', '1.3.2'
	pod 'HockeySDK', '3.8.2'
	pod 'Makemoji-SDK', '1.0.64'

	pod 'Fabric', '1.6.7'
	pod 'Crashlytics', '3.7.0'

	pod 'ResplendentUtilities', '0.5.0'
	pod 'RTSMTableSectionManager', '0.1.8'
	pod 'RPOTCMPerformOperationToCompletionManager', '0.2.0'
	pod 'RUTextSize', '0.1.13'
	pod 'RPLPhotoLibraryView', '0.1.4'
	pod 'RUImageCaptureView', '0.1.4'
	pod 'ResplendentRestkit', '0.2.1'
	pod 'RTFCPTextFieldCustomizablePlaceholder', '0.1.3'
	pod 'RIRImageResizing', '0.1.0'

	pod 'GoogleAnalytics', '3.13.0'
	pod 'Mixpanel', '2.9.9'
end
```

For project that fails trunk push and delete (the cocoapod itself):

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/benjaminmaer/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c68a2d83237ad02a4451b4ca3375f0ea649fd413
```

### Installation Source

```
Executable Path: /Users/benjaminmaer/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/Resplendent/RIRImageResizing

## Other notes:
It seems like something weird has happened with my pod. When I search on your site for my pod, it's listed in search results:
`https://cocoapods.org/?q=RIRImageResizing`

But when I click on it, it takes me straight to github, instead of the expanded details page I normally see. Also, when I try clicking on Podspec, I get a 404 on github. It seems something might have happened to my podspec file? Did I somehow mess this up? It's weird because, this wasn't a problem at first - I was able to install this pod of mine for a while after pushing it.

**Comment by BenMaer** [comment]
@segiddins should I be expecting a response on this? I just want to make sure this is going to get looked at, and that I didn't submit this to the wrong place or something.

**Comment by segiddins** [comment]
I'm no longer actively maintaining CocoaPods, I expect someone on the CocoaPods team will look at it when they get a chance

**Comment by orta** [comment]
@BenMaer people working on CocoaPods only have so much time in the day I'm afraid, no-one has taken a look so far. In general though all these revolve around CocoaPods trunk, where there are issues around these problems. https://github.com/CocoaPods/trunk.cocoapods.org/issues/168

Looks like your delete bug was fixed by https://github.com/CocoaPods/trunk.cocoapods.org/pull/214 

and if you're getting a 404 from CocoaPods on a Podspec, on our website -I'd love an issue on the website about it with an example of how you got to it 👍

**Comment by BenMaer** [comment]
Thanks @segiddins and @orta for the replies. Appreciate the updates from you, and double appreciate the fix :) you guys do great stuff!
