### ISSUE TITLE
pod setup taking a long time

### ISSUE THREAD

**Issue by thebasix** [CocoaPods/CocoaPods#6223]
I installed cocoapods

`sudo gem install cocoapods
`
then I run

`cordova requirements`

and get this output

`The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.`

I then execute 

`pod setup`

but it is just stuck there FOREVER

**What should I do???**

**Comment by benasher44** [comment]
`pod setup` clones the master repo into `~/.cocoapods/repos/master`. You could do this manually:

`mkdir -p ~/.cocoapods/repos`
`git clone https://github.com/CocoaPods/Specs ~/.cocoapods/repos/master`

If it complains that `~/.cocoapods/repos/master` already exists, than you can just delete that directory and repeat the steps. Once this is done, go ahead and run `pod setup` again to make sure everything is working okay.

**Comment by thebasix** [comment]
I'm trying to clone this repo, but it gets stuck at 9%

**Comment by benasher44** [comment]
Hmm. GitHub is having an issue right now, but it's being reported as affecting Github pages. I'm not sure there's more I can suggest aside from maybe waiting until status.github.com is green and then trying again.

**Comment by thebasix** [comment]
How can I do this by downloading .zip file? What are the steps after I've downloaded .zip file??

**Comment by benasher44** [comment]
Which .zip file are you referring to? Sorry, I'm not familiar.

**Comment by thebasix** [comment]
This .zip

https://github.com/CocoaPods/Specs

**Comment by benasher44** [comment]
Ah. You could unzip it into the `~/.cocoapods/repos/master` location, but I'd be surprised if there's a `.git` folder. You'll likely still have to run `git init` and then manually setup the remote, etc.

**Comment by thebasix** [comment]
But how would I do that?

**Comment by dnkoutso** [comment]
VIsit the link above and click here:

<img width="478" alt="screen_shot_2016-11-22_at_8_42_19_am" src="https://cloud.githubusercontent.com/assets/310370/20532666/ac692632-b08f-11e6-8bb1-0d0f3524c168.png">

**Comment by benasher44** [comment]
You can unzip it with the `unzip` command, then you can use `mv` to move it into place. Once that done, you can `cd` into that directory, run `git init`, and then do `git remote add origin https://github.com/CocoaPods/Specs.git`. That said, you'll still have to `git pull` at some point, which will get you back to where you started. I recommend just trying again once Github status is green.

**Comment by orta** [comment]
Closing as there's not much more we can do here.

**Comment by braysonjohn148** [comment]
> 
> 
> You can unzip it with the `unzip` command, then you can use `mv` to move it into place. Once that done, you can `cd` into that directory, run `git init`, and then do `git remote add origin https://github.com/CocoaPods/Specs.git`. That said, you'll still have to `git pull` at some point, which will get you back to where you started. I recommend just trying again once Github status is green.

Any one who can please walk me through these steps slowly.. am confusing the location to extract the folder. Please

**Comment by braysonjohn148** [comment]
I have downloaded the file on my pc and extracted it, but where should i put it and what should i do..? somebody please help.. trying this for months now
