### ISSUE TITLE
No such file or directory @ dir_chdir

### ISSUE THREAD

**Issue by kevin00223** [CocoaPods/CocoaPods#6229]
# Report

## What did you do?
add `source "https://github.com/CocoaPods/Old-Specs"` at the top of my podfile as suggested
run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly and run my project well

## What happened instead?
`[!] Error installing YYText`
then i add `:git => 'https://github.com/ibireme/YYText'` after `pod 'YYText',` in my podfile, just like this:
`pod 'YYText', :git => 'https://github.com/ibireme/YYText'`
then i run `pod install` again
![error1](https://cloud.githubusercontent.com/assets/17540284/20549059/d5784e7a-b163-11e6-98a8-1a8ea2d3c375.jpeg)

then an error comes out!!!
`Errno::ENOENT - No such file or directory @ dir_chdir - /Users/myProjectName/.cocoapods/repos/master`
![error02](https://cloud.githubusercontent.com/assets/17540284/20549100/4bca0690-b164-11e6-8513-30231451ec94.jpeg)

## CocoaPods Environment
`CocoaPods : 0.39.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/myProjectName/.rvm/rubies/ruby-2.2.2/lib
Repositories : cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875`

`### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
````

````ruby
platform :ios, '8.0'
use_frameworks!
source "https://github.com/CocoaPods/Old-Specs"
inhibit_all_warnings!

workspace 'Talkmate'
xcodeproj 'Talkmate.xcodeproj'

pod 'YYText', :git => 'https://github.com/ibireme/YYText'
pod "Qiniu", "~> 7.0"
pod 'MagicalRecord', '~> 2.3.0'
pod 'AFNetworking', '~> 2.6.3'
#pod 'AFDownloadRequestOperation', '~> 2.0.1'
pod 'Reachability', '~> 3.2'
pod 'BlocksKit', '~> 2.2.5'
#pod 'CocoaAsyncSocket', '~> 7.4.2'

pod 'SVProgressHUD', '~> 1.1.3'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MBCircularProgressBar', '~> 0.3.4'

pod 'UMengAnalytics-NO-IDFA', '~> 4.0.3'
#pod 'UMengSocialCOM','~> 5.2'

pod 'SDWebImage', '~> 3.7.4'
pod 'SDWebImage/WebP'
pod 'FontAwesomeKit', '~> 2.2.0'
pod 'Masonry', '~> 0.6.4'
#pod 'NimbusKit-AttributedLabel', '~> 1.0.0'

pod 'UIDevice-Hardware', '~> 0.1.7'
pod 'mp3lame-for-ios', '~> 0.1.1'

pod 'MJRefresh', '~> 3.1.0'
pod 'FCUUID'
pod 'FXBlurView', '~> 1.6.4'
pod 'TTTAttributedLabel', '~> 1.13.4'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'GCDWebServer', '~> 3.3.2'
pod 'YYModel', '~> 1.0.4'
pod 'FLAnimatedImage', '~> 1.0'

#pod 'MLeaksFinder', '~> 0.2.0'
````

**Comment by kevin00223** [comment]
please help!!!

**Comment by benasher44** [comment]
Hi @kevin00223! I see you're using Xcode 8. CocoaPods 1.1.0 is the first version of CocoaPods that supports Xcode 8. The issue you're experiencing was fixed in that version. Please upgrade to at least CocoaPods 1.1.1, and then file a new issue if you're still experiencing this.

Thanks for filing!

**Comment by kevin00223** [comment]
Hi @benasher44 , the problem here is all of my teammates are using Xcode 8 CocoaPods 0.39.0 and nothing goes wrong. Is there a workaround that i can run my project with Xcode 8 and CocoaPods 0.39.0?

**Comment by benasher44** [comment]
There isn't one that I know of for that version of CocoaPods. This issue discusses what happened in more detail: https://github.com/CocoaPods/CocoaPods/issues/5661. We had to make a lot of changes to CocoaPods to work around this. You may want to discuss upgrading with your team, since this issue could start happening to them at any time.

**Comment by kevin00223** [comment]
@benasher44 ok, thx for your info! let me see what i can do

**Comment by rafaelmagu** [comment]
I ran into this problem too, but with Xcode 7.2.1 and CocoaPods 0.39.0. My hacky fix has been to rename the folder then re-run `pod install`, as follows:

```
mv $HOME/.cocoapods/repos/cocoapods $HOME/.cocoapods/repos/master
pod install
```
