### ISSUE TITLE
Getting too many commits to Pull from Cocoapods?

### ISSUE THREAD

**Issue by shumaisjs** [CocoaPods/CocoaPods#6231]
# Report
Suddenly I have a HUGE number of commits to pull and all of them are coming from `CocoaPodsBot <eloy.de.enige+cocoapods.github.bot@gmail.com>` also it seems that I am getting commits for just about each and every project on cocoapod?

look at this image : https://postimg.org/image/hvkx7lma5/

## What did you do?
I am not sure if I did something to cause this.

The only change that I made to anything related to pods was adding this script for swift compatibility

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

## What did you expect to happen?

Expected the swift compatibility issue to go away and it did too.

## What happened instead?

Got 144163 commits to pull!!??

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b5edd046292e5dc74d2f9a25e76133cd32c06c2d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target "Jumpshare" do

pod 'NJKWebViewProgress'
pod 'AFNetworking', '~> 2.5'
pod 'POSInputStreamLibrary', '~> 1.0'
pod "SVProgressHUD"
pod 'XNGMarkdownParser'
pod 'Google/Analytics'
pod 'AMPopTip'
pod 'iRate'
pod 'LMMediaPlayer'

pod 'ActionSheetPicker-3.0'
pod 'BlocksKit', '~> 2.2'
pod 'Fabric', '~> 1.5.1'
pod 'Crashlytics', '~> 3.3.1'
pod 'SocketRocket', '~> 0.4.1'
pod 'Bohr'
pod 'VENTokenField', '~> 2.0'
pod 'SDCAlertView', '~> 7.0'
pod 'INSPullToRefresh'
pod 'FLAnimatedImage', '~> 1.0'
pod 'Google/SignIn'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

## Project that demonstrates the issue
I dont know what the issue is and I can not create a sample project to replicate the issue.

**Comment by shumaisjs** [comment]
The number of commits to pull keeps on increasing
It says "x commits to pull from Master". How can my Master be cocoapods?

**Comment by orta** [comment]
You are, this is how the [CocoaPods Specs repo](http://blog.cocoapods.org/Sharding/) works 👍

**Comment by shumaisjs** [comment]
OK, so basically if I do a `pod repo update` then all these Pulls/Pushes should go away and I will be left with only the Pulls/Pushes that concern my project, right?

**Comment by orta** [comment]
No, you have a full clone of every Specs repo that you are using in your projects inside `~/.cocoapods/repos/`

However I think you're misunderstanding what is going on, these are Spec repos, which contain text files they don't hold the source code for projects or anything.

**Comment by shumaisjs** [comment]
You are right, I do not understand what is going on. 
My `.git` folder has gone up to almost 3GB since I started seeing this issue.

I cant even push any commits to my projects repository because then SourceTree asks me for credentials for `https://github.com/CocoaPods/Specs.git`

**Comment by orta** [comment]
Ah, I see, looks like you're using Xcode 8 with an older version of CocoaPods - we did have a notice when you created this issue saying that you need to be using CocoaPods 1.1.0+ for Xcode 8 support - so I thought you were talking about something else:

> Xcode 8 Status: Only works with CocoaPods 1.1.0+ 

I'd recommend updating CocoaPods and re-cloning your repo I'm afraid

**Comment by shumaisjs** [comment]
Orta, thank you for your help.
I was sure that I had updated but I was on 1.0 and not on 1.1.
I think that I must have updated the outdated pods instead of updating cocoapods itself...
You have been of great help to me 👍
