### ISSUE TITLE
 How to mix swift and OC compiler in develop pod?

### ISSUE THREAD

**Issue by happybobo** [CocoaPods/CocoaPods#6232]
when I create develop pod use `pod lib create`, But I want to use both OC and Swift, I don't know how to do

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
