### ISSUE TITLE
`pod try` not downloading submodules

### ISSUE THREAD

**Issue by CooperRS** [CocoaPods/CocoaPods#6233]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod try RMDateSelectionViewController`

## What did you expect to happen?

I expected CocoaPods to download the `RMDateSelectionViewController` demo project, open it in Xcode. Downloaded copy should be working.

## What happened instead?

Demo project has been downloaded and has been opened in Xcode. However, it was non-functional because submodules have not been downloaded.

## Further Info

The repo of `RMDateSelectionViewController` contains one submodule which contains the dependency of `RMDateSelectionViewController` (which is `RMActionController`). Obviously, it is required for running `RMDateSelectionViewController`.

I did not check whether or not `pod try` would run `pod install` after the demo project has been downloaded. For some projects that would work, too. However, not for all.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 13be6f5416475ba7027e3d081aa87ca9d6f99aec
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate     : 1.0.1
cocoapods-plugins         : 1.0.0
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.1.1
cocoapods-try             : 1.1.0
cocoapods-try-release-fix : 0.1.2
```

## Project that demonstrates the issue

The related project is: https://github.com/CooperRS/RMDateSelectionViewController

**Comment by segiddins** [comment]
It does not download the submodules for that repo because the podspec does not specify that submodules need to be downloaded.
