### ISSUE TITLE
`pod lib create` with no example project results in a workspace that cannot build

### ISSUE THREAD

**Issue by ThePantsThief** [CocoaPods/CocoaPods#6234]
* [√] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Create a new cocoapod:
```
$ pod lib create PodName
What language do you want to use?? [ Swift / ObjC ]
> ObjC
# no to all other options
...
What is your class prefix?
> XY
```
- Open project
- Attempt to build project (⌘B)

## What did you expect to happen?

The project should build with no errors.

## What happened instead?

Xcode presents the following error:
> The run destination `<any device>` is not valid for Running the scheme 'PodName'.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0eb037a838a1a1eeb6329da67db84a305c4219a9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
We're waiting on some work on https://github.com/CocoaPods/pod-template/pull/187 before releasing a new template

**Comment by ThePantsThief** [comment]
Last comment is from over a month ago, any ETA? I literally can't test new cocoapods (easily...) until that goes through
