### ISSUE TITLE
pod trunk push or pod repo push

### ISSUE THREAD

**Issue by hengchengfei** [CocoaPods/CocoaPods#6237]
successfully pod trunk push CFRealmCache,

but "pod search CFRealmCache" no result ,

pod repo push is nessary?

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  CFRealmCache (0.1.0) successfully published
 📅  November 24th, 03:22
 🌎  https://cocoapods.org/pods/CFRealmCache
 👍  Tell your friends!
--------------------------------------------------------------------------------
dafeifei:CFRealmCache hchengfei$ pod search CFRealmCache
[!] Unable to find a pod with name, author, summary, or description matching `CFRealmCache`

**Comment by orta** [comment]
Pod repo push is a different command, it's for [private specs repos](https://guides.cocoapods.org/making/private-cocoapods.html) - it's likely that your search cache is out of date. As it shows on the website.
