### ISSUE TITLE
pod lib create uses old Swift version

### ISSUE THREAD

**Issue by elveatles** [CocoaPods/CocoaPods#6242]
# Report

## What did you do?
`pod lib create`
> What language do you want to use?? [ Swift / ObjC ]
`Swift`
> Would you like to include a demo application with your library? [ Yes / No ]
`Yes`
> Which testing frameworks will you use? [ Quick / None ]
`Quick`
> Would you like to do view based testing? [ Yes / No ]
`No`

## What did you expect to happen?
Create a pod lib workspace with Swift 3.

## What happened instead?
Created a pod lib workspace with Swift 2.2.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c1348191e3285ef0ed1287cf476fe139eee46df7
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
We're waiting on objective-c support for https://github.com/CocoaPods/pod-template/pull/187 before using the new template
