### ISSUE TITLE
Unnecessary Clones

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/CocoaPods#6244]
🌈
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm sitting in a train with bad internet connection right now. That's when I noticed that some repositories are cloned multiple times unnecessarily when running `pod install` or `pod update` (using `--verbose`).

## What did you expect to happen?

Let's take the big Facebook SDK for example:

```ruby
pod 'FBSDKLoginKit', '4.17.0'
pod 'FBSDKShareKit', '4.17.0'
```

Both Pods share exactly the same Git repository, branch & commit. So I expected the repository to be cloned only once.

## What happened instead?

CocoaPods cloned the repository twice (once for each Pod). This slows down `pod install` & `pod update` (unless **each** Pod is already cached), causes unnecessary bandwidth usage and puts unnecessary load on the Git servers.

Checking out the Facebook iOS SDK currently takes 5-10 minutes for me. Having to download it multiple times for no reason is quite frustrating.

```
-> Installing FBSDKLoginKit (4.17.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/facebook/facebook-ios-sdk.git /var/folders/56/rd89kq395rl7v_xh0dd4nv180000gn/T/d20161126-2454-i05ezp --template= --single-branch --depth 1 --branch sdk-version-4.17.0
     Cloning into '/var/folders/56/rd89kq395rl7v_xh0dd4nv180000gn/T/d20161126-2454-i05ezp'...
     Note: checking out 'd001870b769410392c9e465250dbd8a566727094'.
     
     (…)
     
  > Copying FBSDKLoginKit from `/Users/marc/Library/Caches/CocoaPods/Pods/Release/FBSDKLoginKit/4.17.0-42b71` to `Pods/FBSDKLoginKit`

-> Installing FBSDKShareKit (4.17.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/facebook/facebook-ios-sdk.git /var/folders/56/rd89kq395rl7v_xh0dd4nv180000gn/T/d20161126-2454-1vkabux --template= --single-branch --depth 1 --branch sdk-version-4.17.0
     Cloning into '/var/folders/56/rd89kq395rl7v_xh0dd4nv180000gn/T/d20161126-2454-1vkabux'...
     Note: checking out 'd001870b769410392c9e465250dbd8a566727094'.
     
     (…)
     
  > Copying FBSDKShareKit from `/Users/marc/Library/Caches/CocoaPods/Pods/Release/FBSDKShareKit/4.17.0-9b573` to `Pods/FBSDKShareKit`
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8ca826b81ba9e8a4c3e186ad6eb42f14afe1bf11
```

### Installation Source

```
Executable Path: /usr/local/rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by segiddins** [comment]
This is intentional, since both are separate release pods -- cocoapods is not currently built to de-duplicate those downloads, and it would likely be a large effort to make that possible.

**Comment by benasher44** [comment]
I think a repo cache would be reasonable, but yes this would be non-trivial.
