### ISSUE TITLE
Recursive dependencies of local frameworks projects not copied

### ISSUE THREAD

**Issue by dagio** [CocoaPods/CocoaPods#6245]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

This issue is similar to #6123 but for a different scenario

## What did you do?

Run an iOS app

## What did you expect to happen?

The app should load properly

## What happened instead?

The app crash because the dynamic loader can not find a required framework

## CocoaPods Environment

cf: https://github.com/dagio/CocoaPodsLibExample

`bundle exec pod env | pbcopy`

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.2
Ruby lib dir : /Users/damiengavard/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b87e4d7732718e1852b52db34756427729b38d3d
```

### Installation Source

```
Executable Path: /Users/damiengavard/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

workspace 'SampleApp.xcworkspace'

target 'SampleApp' do
  project 'SampleApp.xcodeproj'
  pod 'AFNetworking'
end

target 'SampleFramework' do
  project 'SampleFramework/SampleFramework.xcodeproj'
  pod 'CocoaLumberjack'
end

target 'SampleFramework2' do
  project 'SampleFramework2/SampleFramework2.xcodeproj'
  pod 'MDWamp'
end
```

## Project that demonstrates the issue

Message from : https://github.com/CocoaPods/CocoaPods/issues/6123#issuecomment-262753562

Demo : https://github.com/dagio/CocoaPodsLibExample

In that case, SampleFramework is dependant of SampleFramework2. SampleFramework2 itself is dependant of an external framework : MDWamp

It looks like this : 

<img width="355" alt="screen shot 2016-11-24 at 12 16 56" src="https://cloud.githubusercontent.com/assets/74581/20596731/251e026c-b240-11e6-8181-71e42c895670.png">

And the Podfile looks like that : 

```
platform :ios, '9.0'
use_frameworks!

workspace 'SampleApp.xcworkspace'

target 'SampleApp' do
  project 'SampleApp.xcodeproj'
  pod 'AFNetworking'
end

target 'SampleFramework' do
  project 'SampleFramework/SampleFramework.xcodeproj'
  pod 'CocoaLumberjack'
end

target 'SampleFramework2' do
  project 'SampleFramework2/SampleFramework2.xcodeproj'
  pod 'MDWamp'
end
```

When the app start, the dynamic loader can not find "CocoaAsyncSocket" (one of the dependencies of SampleFramework2) : 

```
dyld: Library not loaded: @rpath/CocoaAsyncSocket.framework/CocoaAsyncSocket
  Referenced from: /Users/damiengavard/Library/Developer/Xcode/DerivedData/SampleApp-dalejtiajrnfbyfeuyaqvunmoptd/Build/Products/Debug-iphonesimulator/SampleFramework2.framework/SampleFramework2
  Reason: image not found
(lldb) 
```

The copy framework step file (Pods-SampleApp-frameworks.sh) does not include these frameworks : 

```
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_framework "$BUILT_PRODUCTS_DIR/AFNetworking/AFNetworking.framework"
  install_framework "$BUILT_PRODUCTS_DIR/CocoaLumberjack/CocoaLumberjack.framework"
fi
if [[ "$CONFIGURATION" == "Release" ]]; then
  install_framework "$BUILT_PRODUCTS_DIR/AFNetworking/AFNetworking.framework"
  install_framework "$BUILT_PRODUCTS_DIR/CocoaLumberjack/CocoaLumberjack.framework"
fi
```

**Comment by benasher44** [comment]
@dagio I appreciate you filing a new issue for this one. This is for an iOS app only correct?

**Comment by benasher44** [comment]
The reason that I ask is that according to [this Apple technical note](https://developer.apple.com/library/content/technotes/tn2435/_index.html), "umbrella frameworks" are only supported in macOS, and I believe this framework inside a framework situation you have here would be almost exactly that. While it might build and run on the iOS simulator, I'm fairly sure this would be rejected during App Store submission.

That said, I can think of a couple of ways to work around this:

1. Checkout our guide here on how to setup a private specs repo: https://guides.cocoapods.org/making/private-cocoapods.html. You can publish your frameworks as private pods only available to you. Then, you can integrate your frameworks just like any other pod.
2. If that's too much, you can also try using local podspecs, using the `:podspec` arg in your Podfile, and there's more info on that at the bottom of this page: https://guides.cocoapods.org/syntax/podfile.html#pod. This gives you all of the benefits of integrating your framework dependencies just like the rest of your pods without the hassle of setting up a private specs repo.

Hope this helps!

**Comment by benasher44** [comment]
To add to that, you can even use local podspecs that point to sources within your existing project (i.e. no need to setup 1 git repo per framework dependency). Podspecs support `:path` as a source option: https://guides.cocoapods.org/syntax/podspec.html#source

**Comment by benasher44** [comment]
Hi there! This issue hasn't been updated in sometime, and I think the explanation and suggestions provided are quite thorough. Given that there's no further action that can be taken to patch CP, I'm going to close this. Feel free to re-open or file a new issue though. Have a nice day!

**Comment by shadyk** [comment]
@dagio can you share the solution you implemented?

**Comment by rob-keepsafe** [comment]
@dagio and @iosMentalist I think you can make your local frameworks into local (static lib) pods and just let CocoaPods deduplicate everything properly.

Examples: https://github.com/rob-keepsafe/PodFrameworksIssue
- `master` branch shows duplicate classes and umbrella frameworks
- `deduped` branch makes the internal dynamic frameworks into local pods (as static libs) to de-dupe and still link in the dependencies
