### ISSUE TITLE
Crashing on device

### ISSUE THREAD

**Issue by akatreyt** [CocoaPods/CocoaPods#6248]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I'm using cocoapods for a project and it will run just fine in sim but when I try to run on device, and the code tries to access a method from a pod, it crashes with 
```unrecognized selector sent to instance ```

## What did you do?

Remove Pods dir, Podfile.lock, xcworkspace. pod update.

## What did you expect to happen?

App to run on both sim and device

## What happened instead?

App crashes on device when trying to access a method from a pod.

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ebf214be31136ef43ee1773a23410631ffd75f9d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

	# Pods for MyApp

  	platform :ios, '8.0'
	pod 'SDWebImage'
	pod 'PureLayout'
	pod 'IQKeyboardManager'
	pod 'FXReachability'
	pod 'mailcore2-ios'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'Firebase'

	target 'MyAppTests' do
		inherit! :search_paths
		# Pods for testing
	end

end
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
