### ISSUE TITLE
Can't open project after 'pod update' or 'pod install'

### ISSUE THREAD

**Issue by mperovic** [CocoaPods/CocoaPods#6251]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod update` or `pod install`

## What did you expect to happen?

Open myApp.xcworkspace with Xcode and continue work without any problem.

## What happened instead?

Pod.xcodeproj file is damaged. When I try to open it directly message: "Project /Users/myName/myProjectFolder/Pods/Pods.xcodeproj cannot be opened because the project file cannot be parsed." is shown.

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bcylin - https://github.com/bcylin/Specs.git @ 95581b9904d0dff63295c29923f823c4cdd6629a
               master - https://github.com/CocoaPods/Specs.git @ 9fcd12574486357531e2c5f7669988a001250e1e
               popcorntimetv - https://github.com/PopcornTimeTV/Specs.git @ 8a4b1649abaf174132f97b78961ae711496bbb85
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate       : 1.0.1
cocoapods-expert-difficulty : 1.0.0
cocoapods-keys              : 1.7.0
cocoapods-plugins           : 1.0.0
cocoapods-search            : 1.0.0
cocoapods-stats             : 1.0.0
cocoapods-trunk             : 1.1.1
cocoapods-try               : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

project 'myApp.xcodeproj'

target 'myApp' do
	platform :ios, '9.0'
	use_frameworks!
	
	pod 'Alamofire', '~> 4.0.0'
	pod 'CCMPopup'
	pod 'SwiftyJSON'
	pod '1PasswordExtension'
	pod 'UrbanAirship-iOS-SDK'
	pod 'DeviceKit'
	pod 'Google/Analytics'
	pod 'KeychainAccess'
	pod 'Nuke'
	pod 'DFCache'
	pod 'Preheat'
	pod 'IQKeyboardManagerSwift'
	pod 'AlamofireNetworkActivityIndicator'
	pod 'ReachabilitySwift', '~> 3'
end
```

**Comment by mperovic** [comment]
Same result is after downgrading to 1.1.1

**Comment by orta** [comment]
I can successfully make a project with your podfile with 1.1.1

![screen shot 2016-11-30 at 06 35 47](https://cloud.githubusercontent.com/assets/49038/20742325/4aa4a848-b6c7-11e6-9411-ae9a37367169.png)

Can you try deleting your Pods folder, and trying again, and if it fails paste in a reply with the contents of `pod env`, not sure if that has more info

**Comment by mperovic** [comment]
Yes. Deleted Pod folder Podfile.lock adn xcworkspace, and after that tryied 'pod install' but result is the same.

**Comment by mperovic** [comment]
Problem solved. Just commented all the pod lines in Podfile and uncomment one by one and found that 'UrbanAirship-iOS-SDK' was a problem.
