### ISSUE TITLE
[Question] Why does added build phases take time when pods are not changed?

### ISSUE THREAD

**Issue by gsabran** [CocoaPods/CocoaPods#6252]
After installing pods, two build phases are added in my project:
```bash
# [CP] Embed Pods Framework
"${SRCROOT}/Pods/Target Support Files/Pods-ProjectName/Pods-ProjectName-frameworks.sh"
```
that runs a script generated by [this](https://github.com/CocoaPods/CocoaPods/blob/2d4d97be43574472648b9f83286c92ad6332e242/lib/cocoapods/generator/embed_frameworks_script.rb)
and 
```bash
#[CP] Copy Pods Resources
"${SRCROOT}/Pods/Target Support Files/Pods-ProjectName/Pods-ProjectName-resources.sh"
```
that runs a script generated by [this](https://github.com/CocoaPods/CocoaPods/blob/2d4d97be43574472648b9f83286c92ad6332e242/lib/cocoapods/generator/copy_resources_script.rb)

They take quite a while to run. Do they have run every time when the pods haven't change? If I remove them manually the app compiles fine when the pods have not changed.

**Comment by benasher44** [comment]
Hi there! In general, Xcode will always run script-type build phases, which is what these are. We could add something to verify that these phases have already been completed and don't need to be re-run before running them, but given how fast they usually are, the cost to verify might get close to the cost to just run the script. It's certainly worth investigating though.

That said, is can you add `time` in front of each of the scripts in each build phase your Xcode project? Then, you can see how long they actually take. It'd be curious to know if one took more than a few seconds. Thanks!

**Comment by benasher44** [comment]
Like this for example:
<img width="503" alt="screen shot 2016-11-29 at 1 10 52 pm" src="https://cloud.githubusercontent.com/assets/1120429/20729039/4a6a3b28-b635-11e6-8a5c-683591d89b8f.png">

**Comment by gsabran** [comment]
Thanks. How do I get the output of `time`? I think it roughly takes 5s for me. Which is not the end of the world but which 1/3 of my total build time.

**Comment by benasher44** [comment]
It should show up in your build log (right most panel in the left pane in Xcode).

**Comment by gsabran** [comment]
That's what I thought. Somehow I see logs while the script is running and then they disappear. Anyway my watch is measuring my 5s.

**Comment by benasher44** [comment]
No prob. For which script is it measuring 5s? Is it the resources one or the embed one?

**Comment by gsabran** [comment]
For the embed one

**Comment by benasher44** [comment]
Ah okay. Can you have a look at the comments in [this thread](https://github.com/CocoaPods/CocoaPods/issues/6118) really quick? Specifically, the [linked SO post](http://stackoverflow.com/questions/40257968/slow-app-compilation-with-new-sierra-update/40298722#40298722). People seemed to have success after auditing their keychains for duplicate/expired certs.

**Comment by gsabran** [comment]
I indeed had a number of duplicated keys in my keychain, which I removed, but I don't think it changed things. However setting `COCOAPODS_PARALLEL_CODE_SIGN` to true does make things faster. If that step could be avoided when pods have not changed that'd be great, but I don't know much about the build process so that might not be possible

**Comment by benasher44** [comment]
AFAIK, it can't be completely avoided. Xcode will always run that build step, so at the very least we'll have to do some verification which will also take time.

**Comment by benasher44** [comment]
I think someone could investigate if there's any low hanging fruit here in the way of skipping code signing that's already been done. I'll leave this ticket open, so that someone else can have a look if possible.

**Comment by gsabran** [comment]
Thanks. Yes I meant have the script to run every time, since this is what Xcode will do, but only run expensive stuff when needed, if possible

**Comment by electic** [comment]
I know for a lot of folks it takes 5s but for me it is several minutes. I might have a lot of pods that is why, but I agree, there needs to be some sort of cache check to see if these should be run over and over.

**Comment by benasher44** [comment]
@electic we're certainly open to ideas! At present, there are no new suggestions. In my mind, you'd still have to verify the signature to make sure you didn't need to re-run `codesign` for each framework, and that's also expensive. Typically with runtimes of several minutes, people were able to fix that by finding and removing dups and expired certificates in there keychains.

**Comment by electic** [comment]
Maybe there is a way to hash the file and keep a cache? I am not too familiar with the internals, but if we can keep a cache, and if that hash changes, then we can re-run codesign. From a cursory look at things, it seems like it runs a ruby script.

**Comment by vslavik** [comment]
>I think someone could investigate if there's any low hanging fruit here in the way of skipping code signing that's already been done.

There certainly is. As it currently is, the script always always unconditionally does three things:
1. Use `rsync` to copy the framework (pretty efficient)
2. Possibly strip the binaries (a bit less)
3. Codesign the binaries (very inefficient, typically adds seconds to build time even with `--timestamp=none` & on powerful CPU)

2+3 should be conditional on 1 changing anything. There are at least two ways to accomplish that:

(1) Xcode has builtin dependencies tracking via the *Input Files* and *Output Files* properties of each script action. The action won't run if all output files exist and no input file is newer (i.e. the action is certain to just redo something it already did previously, with the same inputs). See [this article for a bit more details](http://indiestack.com/2014/12/speeding-up-custom-script-phases/). If the action declared its inputs/outputs, Xcode would optimize it out and not run the script at all.

(2) Alternatively, the script can do it itself and use `[ ! $newest_source_file -nt $oldest_destination_file ]` to bail out early ([many ways to get the representative files](http://stackoverflow.com/questions/4561895/how-to-recursively-find-the-latest-modified-file-in-a-directory)). 

(Apologies for not making a PR just yet, I'll return to optimizing build times once I get some more urgent things off my plate.)

**Comment by dnkoutso** [comment]
PR https://github.com/CocoaPods/CocoaPods/pull/6800

**Comment by dnkoutso** [comment]
Closing this. Will ship with 1.3.0.beta.2.
