### ISSUE TITLE
-force_load on all pods, how?

### ISSUE THREAD

**Issue by dklt** [CocoaPods/CocoaPods#6254]
Hi there,

Extremely difficult to find any info regarding this subject, hope someone can help out answer here.

Problem: 
1. cannot use -ObjC or -allload flag, and there are about 20-30 pods I am currently using.
2. need to enable -force_load on all individual pod
3. modified podfile add post_install and apply -force_load flag on LD_FLAGS

for the life of me, I cannot figure out how to do 3.

Any help that will assist fixing 3 is greatly appreciated.

cheers ~

**Comment by benasher44** [comment]
Hi @dklt! We'd be happy to help! Could you please post the output of  `pod env` as well as the contents of the Podfile you're working with? It's not clear to me what you have so far and what exactly is breaking. Thanks!

**Comment by benasher44** [comment]
Going to close this due to inactivity, but please feel free to re-open or file a new issue if you're still experiencing this. Have a nice day!
