### ISSUE TITLE
`pod trunk push` replace local remote to ~/.cocoapods/repos/.

### ISSUE THREAD

**Issue by skywinder** [CocoaPods/CocoaPods#6257]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
Run `pod trunk push` from directory with my pod (i.e. `~/repo/GaugeKit`)

## What did you expect to happen?
Pushed new release

## What happened instead?
Script is hanging. And I found that remote branch for my loacal repo changed to `https://github.com/CocoaPods/CocoaPods`

i.e. `>git remote -vv`
shows that origin is `https://github.com/CocoaPods/CocoaPods` instead of mine repo.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 34edabff02d446f53bc1066597576f4afc1a3e8f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/skywinder/GaugeKit/

**Comment by orta** [comment]
This happens if you use an older version of CocoaPods with Xcode 8, it's been fixed in the 1.1.x releases.

**Comment by skywinder** [comment]
@orta it's on current `1.1.1` version. I just run `1.1.1` before open an issue.

**Comment by benasher44** [comment]
Did you run `gem update cocoapods` before it changed your remote?

**Comment by skywinder** [comment]
@benasher44 Yes, of course

**Comment by benasher44** [comment]
Hm. I think I've double-checked everywhere, and we use `git -C <path_to_repo>` to do most git operations. Switching to that fixed this last time these issues came up.

One thing that I have seen happen myself is that running `gem update cocoapods` gets you the update but the active version is still something old. If you run `gem uninstall cocoapods` are you prompted about which version you'd like to uninstall?

**Comment by batkov** [comment]
Hi, I had same issue
And I'm prompted:
```
gem uninstall cocoapods
Select gem to uninstall:
 1. cocoapods-1.0.1
 2. cocoapods-1.1.1
 3. All versions

```

**Comment by benasher44** [comment]
@batkov I recommend you finish running that command and have it uninstall cocoapods-1.0.1 there to ensure that 1.1.1 is the active CocoaPods. Thanks!

**Comment by benasher44** [comment]
Going to close this due to inactivity, but please feel free to re-open or file a new issue if you're still experiencing this. Have a nice day!
