### ISSUE TITLE
Autogenerated NSManagedObject Subclasses for Core Data can lead to linker error

### ISSUE THREAD

**Issue by GeroHerkenrath** [CocoaPods/CocoaPods#6259]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Building & running an app (written in Objective-C) that uses pods and has autogenerated NSManagedObject subclasses for core data in its target. Those classes were freshly created using the `Create NSManagedObject Subclasses...` command in the editor.
I am using Xcode 8.1.

## What did you expect to happen?

I expected the build to succeed normally with the new subclasses.

## What happened instead?

The linker failed to link the .o files. On further inspection it seems this happened during one of the build phases defined by cocoapods (i.e. in a `Pods-...-.xcconfig` file).

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.3
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fd21d0686bee5dc036a305c3c420b2f0c9957214
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
slather               : 2.3.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GHPodsAndCDAutogenCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GHPodsAndCDAutogenCode
  pod 'AFNetworking', '~> 3.1'

  target 'GHPodsAndCDAutogenCodeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    pod 'OHHTTPStubs'
  end

end
```

## Project that demonstrates the issue

[Demo project](https://github.com/GeroHerkenrath/GHPodsAndCDAutogenCode). Please see its `README-autogenerated-files` to see how to switch the issue on and off. The above `pod env` stats are from this example project.

## Workaround

After creating the NSManagedObject subclasses with Xcode, select their corresponding entities and set their `Codegen` setting to `Manual/None`. This will not delete the freshly created classes from your project, but resolve the issue for the linker. If you need to re-create the classes again later, revert this setting (the default is `Class Definition`). 
I documented and explained this workaround a bit in my demo project above as well.

**Comment by benasher44** [comment]
Hi @GeroHerkenrath! Thanks for filing this! I'm looking into it.

**Comment by GeroHerkenrath** [comment]
Thank you for taking care of this! Once this is live it will probably help me a lot with my project, because I need to update and extend our datamodel soon. :)

**Comment by benasher44** [comment]
Awesome! Glad I could help!

**Comment by vander2675** [comment]
Is this fixed? I'm still having this Issue. My automatic generated NSManagedObject Classes are not available.
