### ISSUE TITLE
[Idea] Keep resolved podspecs

### ISSUE THREAD

**Issue by marcelofabri** [CocoaPods/CocoaPods#6260]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## Feature idea

If CocoaPods kept all resolved podspecs (and not only local ones as today), people who have `Pods/` in their `.gitignore` could still avoid setting up the Specs repo on every machine. Designers and CI for example could benefit from this. This could also benefit GitHub as there would be no need for running `pod repo update` on sandboxed CI providers like Travis and CircleCI.

I can't think of any downsides of this besides the added complexity. Ideally these podspecs wouldn't be inside `Pods/`, as people probably would like to keep ignoring that folder.

This probably could be solved as a plugin as well, but IMO this is important enough to be on the tool itself.

## CocoaPods Environment

Not applied.

## Project that demonstrates the issue

Not applied.

**Comment by benasher44** [comment]
Hi @marcelofabri! This is an excellent idea! I've started discussing this a bit further in a different issue (saw the other one first somehow). I think the comments I've made on #6310 address your ideas/concerns there, so I think we'd should keep the discussion going there. Thanks for taking the time to file this suggestion, and have a nice day!
