### ISSUE TITLE
List and install version of framework by analyzing Podfile.lock history in git.

### ISSUE THREAD

**Issue by lolgear** [CocoaPods/CocoaPods#6264]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I encountered with specific issue.

I am risk lover and I like to install latest pod from master branch.
One day I caught bug (database framework was corrupted).

This framework worked well several versions ('commits' or 'installs') ago.
As a risk lover, I didn't use version '~>version' tag. ( fault )
My first thought was:
How could I find all entries of this framework installs in git?
Of course, Podfile.lock and it's history.

So, I wrote one-liner and analyzed all installs.
```bash
git log -p -- Podfile.lock | perl -lne '$name = q(PODNAME); (/^\s+$name[\w-]*:\s*$/ .. /^\+\s+:commit:/) and print'
```

After that story I thought about improvement.
What if cocoapods shows history of installs of frameworks by analyzing Podfile.lock?

**Comment by orta** [comment]
I think this would make a great CocoaPods plugin, you could have it audit and logging the different versions over time as they had changed. IMO though, this shouldn't be in the lockfile, or in CocoaPods. The lockfile is meant to represent current state, and I'm not sure it's a useful enough to everyone to put into the core program.

**Comment by lolgear** [comment]
@orta could you point to `CocoaPods plugin guidline` if it exists?

**Comment by orta** [comment]
It doesn't exist, running `pod plugins create [name]` will get you started with a Skelton project though

**Comment by lolgear** [comment]
@orta thanks!
