### ISSUE TITLE
git clone fails: dumb http transport does not support shallow capabilities

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#6270]
Today, I update git to v2.11.0, I get a error:
```
-> Installing AFNetworking (3.1.0)
 > Git download
 > Git download
     $ /usr/local/bin/git clone
     http://mirror.github.taobao.org/cgit.cgi/AFNetworking/AFNetworking.git
     /var/folders/hp/b3htdg693h16_2sjxq6yxprm0000gn/T/d20161205-58757-1sohb5m
     --template= --single-branch --depth 1 --branch 3.1.0
     Cloning into '/var/folders/hp/b3htdg693h16_2sjxq6yxprm0000gn/T/d20161205-58757-1sohb5m'...
     fatal: dumb http transport does not support shallow capabilities

[!] Error installing AFNetworking
[!] /usr/local/bin/git clone http://mirror.github.taobao.org/cgit.cgi/AFNetworking/AFNetworking.git /var/folders/hp/b3htdg693h16_2sjxq6yxprm0000gn/T/d20161205-58757-1sohb5m --template= --single-branch --depth 1 --branch 3.1.0

Cloning into '/var/folders/hp/b3htdg693h16_2sjxq6yxprm0000gn/T/d20161205-58757-1sohb5m'...
fatal: dumb http transport does not support shallow capabilities
```

before I update git, I use v2.10.x, it is OK.

I think the `--depth` is not support by HTTP.

**Comment by DanToml** [comment]
Interesting. It looks like your git provider doesn't support smart transport. Based on https://github.com/bower/bower/issues/949 it looks like plain transport doesn't support --depth. 

Maybe we should start doing full clones on non-GitHub/BitBucket repos? (or make it a config option?)

**Comment by Whirlwind** [comment]
I compare the version of git v2.11.0 and v2.10.0, I found that git will print `does not support --depth` in v2.10.0 and will print `dumb http transport does not support shallow capabilities` in v2.11.0. And the CP check the output just match v2.10.0:

```
      def clone(force_head = false, shallow_clone = true)
        ui_sub_action('Git download') do
          begin
            git! clone_arguments(force_head, shallow_clone)
            update_submodules
          rescue DownloaderError => e
            if e.message =~ /^fatal:.*does not support --depth$/im
              clone(force_head, false)
            else
              raise
            end
          end
        end
      end
```

So, If I use git v2.10.0, I will can clone without `--depth` if the server is not support shadow. The CP will try twice times. But if I use 2.11.0, The git output string chagned and CP will not try when `--depth` is not support.

**Comment by DanToml** [comment]
Cool, changing that should be enough then 👍
