### ISSUE TITLE
why change repo directory structure

### ISSUE THREAD

**Issue by charlesdbs** [CocoaPods/CocoaPods#6272]
I found new repo directory structure is different . We have some mirrors in China, and we analyze repo as ${name}/${version}/${name}.podspec.json .  Now we do not know how to mirror https://github.com/CocoaPods/Specs？

**Comment by orta** [comment]
http://blog.cocoapods.org/Sharding/ has all the reasoning about why we had to transition, and links to show how we generate the file paths now 👍
