### ISSUE TITLE
resources will copy all subfiles in `.bundle`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#6273]
I find that if I have some resource files and a bundle resource, I can not use a `*` to search them.

The spec file:
```
  s.resources = "*/**/*.{png,jpg,xib,bundle}"
```
File:
```
|-A
  |-B
    |-x.jpg
    |-C.bundle
      |-d.jpg
```
The CP will copy `x.jpg`, `C.bundle` and `d.jpg` to my project!! The `d.jpg` will match the regex!
I know that I can change the `resources` or use `exclude_files`, but they are not easy to write.

Can the CP stop to search into the `.bundle`? The `.bundle` is match the `resources`.

**Comment by benasher44** [comment]
Hi @Whirlwind! Based on your description, I'm not sure I understand the issue you're experiencing. It appears you want `s.resources` to search the contents of `C.bundle`. Is that correct?

**Comment by Whirlwind** [comment]
I don't want to search the contents of `C.bundle`. But now, CP always search the `C.bundle`.

The CP always copy `x.jpg`, `C.bundle` and `d.jpg` to my project. I hope that CP just copy `x.jpg` and `C.bundle`.

**Comment by benasher44** [comment]
If you change `**` to a `*`, I think that'll do it.

**Comment by benasher44** [comment]
Could you try that and let me know how it goes? Thanks!

**Comment by Whirlwind** [comment]
I test `*/*/*.{bundle,jpg}`, but it match `A/B/x.{bundle, jpg}`, not match `A/B/C/D/E/F/x.{bundle, jpg}`.

`**` match any number of folder, and `*` match a folder.

**Comment by benasher44** [comment]
Hm okay. I recommend just moving the `.bundle`s then, so that you can provide a more specific `s.resources` setting. Something like `s.resources = 'Resources/**/*', 'ResourceBundles/*.bundle'` would ensure that there's no overlap.

**Comment by Whirlwind** [comment]
I know, but I sometime can not move the `.bundle`, and I must write it very carefully.

I hope the CP will can not enter the `.bundle` to match the `resources`.

**Comment by benasher44** [comment]
In that case, I'd recommend moving the other files. Sorry I don't have any better workarounds. Here are my general thoughts on implementing a special case:

- Implementing a special case per-file type adds complexity, and it's unclear to me that others wouldn't be negatively affected by this behavior change.
- This can be easily worked around by making clever changes to file structure to clearly separate `.bundle` or other non-`.bundle` files.

Given these 2 reasons, I don't think it makes sense to patch CocoaPods here. Thanks for filing, but I'm going to close this as a CocoaPods issue. I'm happy to help brainstorm solutions though! And others should definitely chime in if I've glossed over something!

**Comment by Whirlwind** [comment]
I know these way to avoid the problem. But many people in my team don't know these case.

I hope the CP can auto skip the search the `.bundle`. I think that it should be easy.

**Comment by benasher44** [comment]
It might be an easy change to make. We could have some kind of blacklist of file extensions to not to follow. The issue there is that people who do want CocoaPods to follow `.bundle` folders will have no recourse (i.e. no restructuring of the folder tree will help aside from pulling apart the bundle). If you compare that to the current situation, people that want bundle to be handle separately can just move the location of the `.bundle` and handle it with a separate file pattern. This is a comparatively easy workaround.

**Comment by Whirlwind** [comment]
I think we could not create a blacklist. We just void to list the files in a foider that match the `resources`.(i.e. if define `resources = '*/**/*.xx'`, and the `a.xx` is a directory, we always skip search it).  Sometime, we have a directory and some single files to copy resources, and the directory should not be searched.

Could you know what I said?

**Comment by benasher44** [comment]
Yep I understand that makes sense. The previous concern I mentioned still holds though. People who do want CocoaPods to search `a.xx` that are directories will be left with no options, whereas right now there's a straightforward workaround.

This does however sound like something you could maybe accomplish with a plugin. We'd definitely be open to such a plugin, since it would mean people could opt into that behavior as needed.
