### ISSUE TITLE
LoadError - cannot load such file -- nanaimo

### ISSUE THREAD

**Issue by yasiradnan** [CocoaPods/CocoaPods#6281]
### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0fddc10a872d70e56660b4cf112df0367804f627
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Looks like a dup of #6214

**Comment by yasiradnan** [comment]
https://github.com/CocoaPods/CocoaPods/issues/6106 solved my problem. I have two version of **Nanaimo** installed. Removed one and everything is working fine now.

**Comment by JittenderKumar** [comment]
Hey Guys,

I was also facing the same problem.
I solved it only by accessing two commands from terminal.

1--> sudo gem uninstall nanaimo
 and then
2-->sudo gem install nanaimo

Hope so it will help you.

**Comment by momotw** [comment]
Hi JittenderKumar, Your solution hope to me, Thank you very mush.

**Comment by sstigler** [comment]
@JittenderKumar 's solution worked for me too. Thanks!

**Comment by eauw** [comment]
+1 thanks

**Comment by maheshshetti** [comment]
JittenderKumar's response helped fixing the issue. Thanks

**Comment by WillieWu** [comment]
JittenderKumar's response helped fixing the issue. Thanks

**Comment by rajeshm20** [comment]
Thanks @JittenderKumar

**Comment by cgossain** [comment]
Thanks! That fixed it for me.

**Comment by neuralmer** [comment]
Thanks @JittenderKumar

Right, so if everyone has to fix it by hand, maybe it is actually bug?

**Comment by ShivMiet** [comment]
Thanks  @JittenderKumar 

This solution work for me.

**Comment by donggelaile** [comment]
@JittenderKumar  Thanks

**Comment by mhb675** [comment]
Thanks, it worked for me. :)

1: uninstall all versions first with this command

sudo gem uninstall nanaimo

and then
2: install again with this command

sudo gem install nanaimo

**Comment by minusplusminus** [comment]
When I typed  `sudo gem uninstall nanaimo` only one version was  available.   `gem uninstall nanaimo`  (without sudo) had two versions. Selected the older version and removed it.

**Comment by zeinab-reda** [comment]
it works for me also ,Thanksssssssss 👍

**Comment by DanBurkhardt** [comment]
Thanks @JittenderKumar

**Comment by iChirag** [comment]
Thanks @JittenderKumar

**Comment by forehappySun** [comment]
Hi @ JittenderKumar, Thank you very mush.

**Comment by liuyan3176** [comment]
`sudo gem update`   is useless
and thanks @JittenderKumar 
it seems like two conflict version nanaimo...
