### ISSUE TITLE
Pod's internal dependencies do not sign in App Store if not are included in Podfile

### ISSUE THREAD

**Issue by carlosypunto** [CocoaPods/CocoaPods#6286]
* [*] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` for Podfile with pods with internal dependencies, like this:

```ruby
platform :ios, '9.0'

target 'MyApp' do
  use_frameworks!

  pod 'R.swift', '~> 3.1.0'
  pod 'RealmSwift', '~> 2.1.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = "iPhone Developer"
            config.build_settings['DEVELOPMENT_TEAM'] = "MY_MEMBER_ID"
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ""
        end
    end
end
```

## What did you expect to happen?

The same which including directly in the Podfile the internal dependencies of these pods, like here:

```ruby
platform :ios, '9.0'

target 'MyApp' do
  use_frameworks!

  pod 'R.swift', '~> 3.1.0'
  pod 'RealmSwift', '~> 2.1.1'

  # internal dependencies of the above pods
  pod 'R.swift.Library', '~> 3.0.2'
  pod 'Realm', '~> 2.1.1'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = "iPhone Developer"
            config.build_settings['DEVELOPMENT_TEAM'] = "MY_MEMBER_ID"
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ""
        end
    end
end
```

In this case the app sign correctly in App Store

## What happened instead?

MyApp is not completely signed in App Store

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a8bc3fb1b8947cc7f07ca5b3b5f729cd180ef22e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Anyway, the problem is not in the project

**Comment by benasher44** [comment]
Hi @carlosypunto! Is there a particular reason why you've added that post install hook? AFAIK, those settings shouldn't be required for normal signing for App Store or otherwise. Thanks!

**Comment by carlosypunto** [comment]
Hi @benasher44,
With the app I am currently, I have had several problems signing, possibly doing something else wrong. Thanks for the quick response :-), for now I close the issue this weekend I will try to solve it in another way.

**Comment by benasher44** [comment]
@carlosypunto no problem! If/when you fix it, feel free to follow up here to let us know how it went!

**Comment by carlosypunto** [comment]
Thanks again. If I can solve the problem (I have not done so yet 😓) and it is related to CocoaPods, do not doubt that I will report it.
With the hook, was the only time I got sign it in App Store (with "Upload Successful" message) but before it did not appear in iTunes Connect 😓 . Without the hook and adding internal pods is imposible, that's why I made this report.
A fellow has suggested to me that it could be for some script .sh, I can not believe 100% that. Apart from the CocoaPods scripts I have two more in Build Phases. One call to swiftlint and the other is R.swift generator. 
Have you had any similar reports? 
<sub><sup><sub><sup>PS: I should have the app already under review 😢 . Tomorrow is the presentation (only for Android but mine can not upload) and TV advertising is scheduled for two weeks from now.</sup></sub></sup></sub>

**Comment by benasher44** [comment]
I haven't seen similar reports no sorry. If you can give me more details about signing settings in your project, I can try to help. But, you might have more luck on Stackoverflow there. Best of luck with the presentation!

**Comment by carlosypunto** [comment]
Thanks again :-) I do not know Cocoapods's internals, so I have this doubt. Once the application is archived (it's ok), is there any trace of CocoaPod within it?

**Comment by benasher44** [comment]
What kind of trace were you looking for sorry?

**Comment by carlosypunto** [comment]
I'm sorry for my English, I know very little. I say it for dismissing CocoaPods as part of the problem. I mean than once I have done (Product -> Archive) in Xcode and I have the ".xcarchive". Does Cocoapod continue to participate in the following processes to upload to iTunes Connect? Or CP has its work already completed? (Because if it's the latter case I do not think it's a problem with cp)

**Comment by carlosypunto** [comment]
Thanks a lot for helping me with this. Ad hoc or development codee sign both work fine only fails release sign.
![screen shot 2016-12-13 at 20 08 07](https://cloud.githubusercontent.com/assets/1680094/21155233/ab86ac2e-c171-11e6-8c08-33b95870d841.png)
![screen shot 2016-12-13 at 20 20 37](https://cloud.githubusercontent.com/assets/1680094/21155234/ad9a5934-c171-11e6-9c4a-212b0a4d430e.png)

**Comment by carlosypunto** [comment]
Do you know some way to get a log more unambiguous than above? I've done all this message say

**Comment by carlosypunto** [comment]
I've open a new issue with more info and file here: #6305
