### ISSUE TITLE
No Such Module 'QuickbloxWebRTC' - Xcode8 - Swift project - Cocoapods 1.1.1

### ISSUE THREAD

**Issue by PranavJaiswal** [CocoaPods/CocoaPods#6293]
Unable to compile project after 'import QuickbloxWebRTC' statement. Quickblox & QuickbloxWebRTC were installed using cocoapods

Environment Details: Xcode:8.0, iOS Deployment: 10.0, cocoapods (1.1.1), Swift 3.0

# Report

## What did you do?
Created a New singleviewController app using Xcode 8 & swift as base language. 
Then used cocoapods to install dependencies using pod file with contents. Used command Pod install...I see the dependencies installed successfully
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
use_frameworks!
target "QBVideoCallSwift" do
    pod 'Quickblox-WebRTC'
    pod 'QuickBlox'
end

```
In the the project.xcworkspace AppDelegate I added below code
```
import SystemConfiguration
import MobileCoreServices
import Quickblox
import QuickbloxWebRTC 
```
(No such Module 'QuickbloxWebRTC' error is thrown)

## What did you expect to happen?
ℹ I was expecting project to compile successfully without any errors.
e.g. Install all pod dependencies correctly.

## What happened instead?
Unable to compile application.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 078723b85da0599072674bda17a348c3842e5225
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://drive.google.com/file/d/0B5nqEBSJjCriZUpON09nYWNISVE/view?usp=sharing

**Comment by benasher44** [comment]
Hi @PranavJaiswal! It appears that Quickblox-WebRTC doesn't provide a module map nor set it in the podspec. They'll need to provide a custom module map for their vendored framework for that import statement to work properly in Swift. I recommend following up with them. Thanks!
