### ISSUE TITLE
Embed Pods Frameworks fails when target has spaces

### ISSUE THREAD

**Issue by Gerst20051** [CocoaPods/CocoaPods#6294]
Any update regarding this regression? View all the new comments on this issue.

https://github.com/CocoaPods/CocoaPods/issues/3754

**Comment by joeboyscout04** [comment]
Wait, why did you close this issue? Has it been fixed or still waiting?

**Comment by Gerst20051** [comment]
Yes, it's already fixed. A new version just needs to be released.

**Comment by Amindv1** [comment]
And when will this version be released?

**Comment by joedaniels29** [comment]
+1 on the new version. That or instructions on how to use a specific commit where the fix exists.   thanks a bunch!

**Comment by benasher44** [comment]
Hello! A new version will be released shortly. Look for 1.2.0.beta.2. For instructions on how to install a ruby gem from a specific sha/commit in git, checkout bundler.io. Have a great day!

**Comment by luquantan** [comment]
@benasher44: Hey, any thoughts on when 1.2.0.beta.2 will be released?

**Comment by DanToml** [comment]
@luquantan It will be released this weekend. Most of the gems are already released, but I have a couple of tests on cocoapods/cocoapods failing locally.

**Comment by luquantan** [comment]
👌 Thank you

**Comment by Amindv1** [comment]
This wasn't released over the weekend?

**Comment by madsb** [comment]
Just installed 1.2.0 beta 3 with --pre. I can confirm that this build fixes the problem.

**Comment by aksswami** [comment]
Facing this issue on version 1.4.0.
