### ISSUE TITLE
CocoaPods v1.1.1 "missing required architecture"

### ISSUE THREAD

**Issue by JinghuangLiu** [CocoaPods/CocoaPods#6303]
When I use "pod spec lint --verbose" to check my podspec file. It tell me one of my frameworks missing required architecture. I use the command line "lipo info" to check the contained architecture of the framework, it does not missing that required architecture. It's critical for us to submit a new version. Hope to get response quickly and appreciate your help.

![tmp44c1259a](https://cloud.githubusercontent.com/assets/6930613/21141332/83f06078-c177-11e6-98b4-897180723e47.png)

![tmp61d2f9f6](https://cloud.githubusercontent.com/assets/6930613/21141340/8df4d7ca-c177-11e6-90ea-2366f4cb9ca1.png)

**Comment by dnkoutso** [comment]
It seems you are `spec lint` is linting the 3.5.3 version of your pod but in your screenshot it says 3.5.1, is it possible you are comparing two different versions?

Either way I doubt this is actually CocoaPods issue.

**Comment by dnkoutso** [comment]
Remember `spec lint` clones the current tag in your podspec and does not use the local sources for linting, use `lib lint` for this.

**Comment by dnkoutso** [comment]
Maybe try `git checkout v3.5.1` and then run `lipo -info` on the framework, I assume its pre-built.

**Comment by JinghuangLiu** [comment]
@dnkoutso Thanks,you are really attentive. But actually the above v3.5.1 and v3.5.3 are the same package and I check the github's package. 

Ps: We have had more than one SDK has this problem since we update the CocoaPods.

![tmp61768d1e](https://cloud.githubusercontent.com/assets/6930613/21167158/782ae6be-c1e5-11e6-8900-96249dbf0cf0.png)

**Comment by JinghuangLiu** [comment]
Our sdk （https://cocoapods.org/?q=ShareSDK3） user account is kind of huge, It effects so many people. Please solve this problem. Thanks a million.

**Comment by JinghuangLiu** [comment]
Finally，we solve this problem by add the supported framework(make by us). The new version of CocoaPods need every framework alone can build successfully.
