### ISSUE TITLE
Anyone Xcode's archive with this Podfile make an Invalid signature when is upload to App Store

### ISSUE THREAD

**Issue by carlosypunto** [CocoaPods/CocoaPods#6305]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Try to upload an empty app (e.g. Xcode's Single view application), therefore anyone, with the Podfile shown in **_CocoaPods Environment_ section of this issue** don't upload to App Store. Tested several times with several environment combinations using: Xcode 8.1 or 8.2, CocoaPods 1.1.1 or 1.2.0.beta.1, Before and after update RubyGems, with Mac OS X 10.11.6, 10.12.1 and 10.12.2

Except the 1.2.0.beta.1 all were in production version

All pods are the last final versions at moment I write this.

## What did you expect to happen?

The app should upload to App Store for Production

## What happened instead?

The app don't upload (Don't sign) with this message:

![screen shot 2016-12-13 at 23 51 48](https://cloud.githubusercontent.com/assets/1680094/21162714/239ad196-c18f-11e6-96da-bd4b6a0f7372.png)

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.2 (8C38)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/carlos/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 599d96a02bcde56faab28701d7b643859eff3a71
```

### Installation Source

```
Executable Path: /Users/carlos/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'WhatYouWant' do
  use_frameworks!

  pod 'Alamofire', '~> 4.2.0'
  pod 'AudioKit', '~> 3.4.3'
  pod 'CryptoSwift', '~> 0.6.6'
  pod 'R.swift', '~> 3.1.0'
  pod 'RealmSwift', '~> 2.1.1'
  pod 'RxCocoa', '~> 3.0.1'
#  pod 'RxDataSources', '~> 1.0.0'
#  pod 'RxRealm', '~> 0.3.2'
  pod 'RxSwift', '~> 3.0.1'
  pod 'SwiftyJSON', '~> 3.1.3'
  pod 'RappleProgressHUD', '~> 2.1.2'

#  pod 'IQKeyboardManagerSwift', '4.0.6'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

## Project that demonstrates the issue

Please for check try to upload will success, before, change project's build version to 2 and run `pod install` or `pod update`.
[WhatYouWant.zip](https://github.com/CocoaPods/CocoaPods/files/650439/WhatYouWant.zip)
You can use an empty project too, the issue appear always.

**Comment by carlosypunto** [comment]
Having tried one by one pods it seems that the problematic is AudioKit. I close the issue

**Comment by carlosypunto** [comment]
Resolved! I was doing it wrong. 

In case someone else has this error and can not find the solution, If you use AudioKit >= 3.0 and your project has Bitcode enabled, you need add one Build Phase to your application target. 😀

Here are the instructions:
https://github.com/audiokit/AudioKit/blob/master/Frameworks/INSTALL.md#handling-bitcode

**Comment by carlosypunto** [comment]
@benasher44 thank you for giving me an answer and trying to help me

**Comment by benasher44** [comment]
@carlosypunto no problem! I'm glad you got it figured out!
