### ISSUE TITLE
Frameworks search paths not inherited

### ISSUE THREAD

**Issue by stowy** [CocoaPods/CocoaPods#6306]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Tried to have a common cocoapod dependency inherited from an internal framework target by an application target.  The dependency is Firebase, which is distributed as a framework. 

The podfile does not have `use_frameworks!` set, we link with static libraries.

The podfile setup is basically as follows:

```ruby
# The version number specified here is the minimum
platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

project 'SampleApp.xcodeproj'

abstract_target :pods do
    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'
    pod 'Realm', '2.1.1'
    
    target :SampleFramework do

    end

    target :SampleApp do
        inherit! :search_paths
    end
end
```

The search paths for the static libraries are inherited by the sample app, but the framework search paths are not, in the Pods generated `xcconfig` for `SampleApp`.  Thus, in this case, `Realm` is found in `SampleApp`, but `Firebase` is not. 

## What did you do
Used above Podfile, tried to import Firebase in `SampleApp`, but it is not found, unless i manually copy the framework search paths from `Pods-SampleFramework.debug.xcconfig` to `Pods-SampleApp.debug.xcconfig`

## What did you expect to happen?
Expected to be able to import Firebase and use in the Sample app, without specifically importing the framework, because of the dependency from the SampleFramework. 

## What happened instead?
The Firebase import was not found in the SampleApp.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.1 (8B62)
         Git : git version 2.5.0
Ruby lib dir : /Users/sstow/.rvm/rubies/ruby-2.2.4/lib
Repositories : groupondev-ios-groupon-cocoapods - git@github.groupondev.com:ios/ios-groupon-cocoapods.git @ 47f3e050d0eeacd6263ed475af882b1206bcc850
               master - https://github.com/CocoaPods/Specs.git @ 74f81a8ab223d9156716434887fc2c77d78a74f8
```

### Installation Source

```
Executable Path: /Users/sstow/.rvm/rubies/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Implicit sources are deprecated.
# This line adds the cocoapods as an explicit source

source 'https://github.com/CocoaPods/Specs.git'

# The version number specified here is the minimum
platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

project 'SampleApp.xcodeproj'

abstract_target :pods do
    pod 'Firebase/Core'
    pod 'Firebase/RemoteConfig'
    pod 'Realm', '2.1.1'
    
    target :SampleFramework do

    end

    target :SampleApp do
        inherit! :search_paths
    end
end
```

## Project that demonstrates the issue
https://github.com/stowy/CocoaPodsFrameworkHeaders

**Comment by benasher44** [comment]
Hi there! I think this was fixed as part of #6287. Can you please try this with CocoaPods master and get back to us? Thanks!

**Comment by stowy** [comment]
Hi, sure thing I'll let you know this week, thanks for your response 😄

**Comment by vendruscolo** [comment]
I installed cocoapods from master [as explained here](https://guides.cocoapods.org/using/a-gemfile.html), using bundler.

My podfile

```
source 'https://github.com/CocoaPods/Specs'

platform :ios, '10.0'

project 'Conosci_Italiano', 'Debug' => :debug

# Uncomment this line if you use Swift
use_frameworks!

target 'Conosci_Italiano' do
  pod 'Curry', '~> 3.0.0'
  pod 'Firebase', '~> 3.11.0'
  pod 'FirebaseAuth', '~> 3.1.0'
  pod 'FirebaseDatabase', '~> 3.1.1'
  pod 'JVFloatLabeledTextField', '~> 1.1.1'
  pod 'NSObject+Rx', '~> 2.0.0'
  pod 'NSString-Helper', '~> 1.0.5'
  pod 'PureLayout', '~> 3.0.2'
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  pod 'RxDataSources', '~> 1.0.2'
  pod 'RxCocoa', '~> 3.1.0'
  pod 'RxOptional', '~> 3.1.3'
  pod 'RxSwift', '~> 3.1.0'

  target 'UnitTests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
    pod 'OHHTTPStubs'
  end

  target 'FlowTests' do
    inherit! :search_paths

    pod 'KIF', '~> 3.0', :configurations => ['Debug']
  end

end
```

If I run the app, it compiles and works as expected. If I try to run the tests, it fails to compile telling me:

> No such module 'Firebase'

Any idea? How can I further help you?

**Comment by benasher44** [comment]
Hi @vendruscolo! See #6138. I don't think the current issue is related to what you're seeing.

**Comment by vendruscolo** [comment]
Hi @benasher44, after some trial and error I managed to get the whole thing to work. The fix was to remove the `AppDelegate` from the two targets (`UnitTests` and `FlowTests`). I have no idea why it works though.

**Comment by benasher44** [comment]
@vendruscolo glad you got it working! What do you mean by "remove the `AppDelegate`"?

**Comment by vendruscolo** [comment]
@benasher44 in the File inspector I only checked the first checkbox (the app target, the other two are the tests targets).
![screen shot 2017-01-24 at 14 52 29](https://cloud.githubusercontent.com/assets/403372/22249854/f99b3ce2-e244-11e6-8e1d-968e342e6e99.png)

**Comment by benasher44** [comment]
Ah gotcha. Thanks for the update!

@stowy were you able to get this resolved?

**Comment by dnkoutso** [comment]
@stowy this should be fixed on master, can you possibly try and see?

**Comment by dnkoutso** [comment]
I tried with master, looks like this might be an issue with overall having the parent target as abstract.

**Comment by dnkoutso** [comment]
Actually I think this is not covered on master either...Will see if I can fix.

**Comment by dnkoutso** [comment]
@benasher44 I think this is broken without `use_frameworks!`. Would love your help to get it fixed.

**Comment by justinseanmartin** [comment]
If the original goal was to have the dependencies get linked into the SampleFrameworks and not the SampleApp (that's how the Podfile reads to me at least), then this is behaving somewhat as expected. 

You have to explicitly expose internal frameworks outwards from SampleFrameworks by adding `@import FirebaseCore` to the SampleFrameworks.h umbrella header. Then you should be able to access the FirebaseCore symbols in SampleApp by using `import SampleFramework`. If you wanted to access Realm from Swift, you'll need to add it to the Swift bridging header, but that then seems to work as well.

I did all of my testing of this on CocoaPods 1.2.0, so might also need some of the recent fixes for `inherit! search_paths` possibly.

**Comment by dnkoutso** [comment]
This works with `use_frameworks!` because of this:

```ruby
        if installation_options.integrate_targets?
          # Copy embedded target pods that cannot have their pods embedded as frameworks to their host targets
          embedded_targets = aggregate_targets.select(&:requires_host_target?).select(&:requires_frameworks?)
          analyze_host_targets_in_podfile(aggregate_targets, embedded_targets)
          aggregate_targets.each do |target|
            copy_embedded_target_pod_targets_to_host(target, embedded_targets)
          end
        end
```

The analyzer will treat the framework target as part of the app target and so it will copy its pod targets as well. If you do not use frameworks this whole logic is not executed causing it to ignore all framework search paths for the app target.

**Comment by benasher44** [comment]
@stowy I think I have a fix ready for PR soon. Can you explain your reasoning for the `inherit :search_paths` you have in your Podfile? I want to make sure I understand the use case here. Thanks!

**Comment by benasher44** [comment]
Closing via #6575
