### ISSUE TITLE
Getting the error "[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it.The Swift Pod being used is:xxxxxNetworkManagerSwift" when using swift private pod  in mix and match

### ISSUE THREAD

**Issue by VenuKotha** [CocoaPods/CocoaPods#6307]
Hi, 
I got the below issue and not getting resolved. Please help me to resolve the issue if already got it.

I have an existing project written in Objective C which contains private pods. I am writing a new private pod in swift language and  need to integrate with existing objective C project as i have to go with Mix and Match approach. When I give "pod install" command i am getting below error

"[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: XXXXXNetworkManagerSwift"

Here "XXXXXNetworkManagerSwift" is a new pod written in Swift language. It is a framework template.
Existing private pods are written using static lib templates.

My podfile is as below where i am using XXXXXNetworkManagerSwift as a dependency

Podfiile:-
source 'https://github.com/xxxx/ios-specs.git'
source 'https://github.com/cocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target 'XXXXFoundationFramework' do
podspec :path => 'XXXFoundationFramework.podspec'
end

 podspec is as below:-

Pod::Spec.new do |s|
  s.name         = "XXXXXFoundationFramework"
  s.version      = "6.0.0"
  s.summary      = "This is master version"
  s.description  = "This is test file"
  s.homepage     = "http://EXAMPLE/XXXXXFoundationFramework"
  s.license      = "MIT (example)"
    s.author             = { "" => "" }
   s.platform     = :ios, "8.0"
  s.source       = { :git => "https://github.com/m-ize/XXXXXFoundationFramework.git" }
  s.source_files  = "XXXXXXFoundationFramework", "XXXXXFoundationFramework/**/*.{h,m}"
  s.exclude_files = "XXXXXFoundationFramework/Exclude"

  # s.public_header_files = "Classes/**/*.h"
s.prefix_header_contents = '#import "MZGlobalHomeViewController.h"','#import "Constants.h"
    s.vendored_library    = 'XXXXXFoundationFramework/LibUniversal/libmCommLib.a'
    s.library = 'xml2'
    s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }
    s.requires_arc = true
    s.dependency "XXXXXDomainModel", "~>6.0.0"
    s.dependency "XXXXXNetworkManagerSwift", "~>1.0.0"
    s.dependency "XXXXXUtil", "~>6.0.0"
    s.dependency "XXXXXValidationManager", "~>6.0.0"
    s.dependency "Realm", "~>0.102.1"
    s.dependency "Typhoon", "~>3.5.1"
    s.dependency "couchbase-lite-ios","~> 1.2.1"
end

Thank you in advance

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
