### ISSUE TITLE
CocoaPods v1.1.1 "missing required architecture

### ISSUE THREAD

**Issue by liyuansheng** [CocoaPods/CocoaPods#6309]
When I use "pod spec lint --verbose" to check my podspec file. It tell me one of my frameworks missing required architecture. I use the command line "lipo info" to check the contained architecture of the framework, it does not missing that required architecture. It's critical for us to submit a new version. Hope to get response quickly and appreciate your help.

![2016-12-14 17 57 00](https://cloud.githubusercontent.com/assets/16317245/21177587/ce7c9da0-c226-11e6-86e4-61e737c0ce2d.png)
![2016-12-14 17 57 24](https://cloud.githubusercontent.com/assets/16317245/21177590/d1ed714e-c226-11e6-8606-8ea04bd75272.png)

**Comment by benasher44** [comment]
Hi @liyuansheng! We'd be happy to help! Can you try re-running your lint command with `--no-clean`? Then you'll be able to run `lips --info` on the binary referenced by the full path in the `xcodebuild` failure output. Thanks!

**Comment by analysys** [comment]
I met the same problem, in the 0.39.0 version there is no problem, after the upgrade version 1.0.0 verification does not pass:

![image](https://cloud.githubusercontent.com/assets/23375359/21419809/ec5f3e74-c864-11e6-9543-02169d0b1792.png)

**Comment by dnkoutso** [comment]
@analysys the reason why it doesnt fail in 0.39.0 is because there the linter does not link versus in 1.x which it does.

@liyuansheng do you have a podspec and/or repo to clone and test this?

**Comment by chongsuhpark** [comment]
@analysys @liyuansheng @benasher44 
In my objectiv-c iOS project, I'm experiencing exactly the same.  Has anyone found a way to go around this problem?

**Comment by liyuansheng** [comment]
@benasher44 @analysys @dnkoutso 
when I add the dependency framework in the podspedc ,then it's all right.
Like this:
![f59ca697-f44e-4d28-a036-330d07a0ce44](https://cloud.githubusercontent.com/assets/16317245/21639542/a65982c6-d2ab-11e6-8463-2f6dff55ec9f.png)

**Comment by benasher44** [comment]
@liyuansheng oh okay great! So do I understand that you were able to resolve this issue then? Or is there still something wrong?

**Comment by chongsuhpark** [comment]
@benasher44  @liyuansheng   I am trying to get my problem worked out by  suggestion from @liyuansheng  Unfortunately, since my project setting is a bit different from above, I posted another question (https://github.com/CocoaPods/CocoaPods/issues/6374#issuecomment-271019631)  to apply the suggestion yet I am still stuck.

**Comment by chongsuhpark** [comment]
@benasher44  @liyuansheng   Yes, I tried above suggestion from  @liyuansheng  by declaring dependency though it didn't fix problem.  

```
ld: 219 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld DerivedData/App/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386
	Ld DerivedData/App/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
(2 failures)

```

**Comment by benasher44** [comment]
@chongsuhpark can you include the verbose output which should have the duplicate symbols?

**Comment by chongsuhpark** [comment]
@benasher44 

```
** BUILD FAILED **


The following build commands failed:
	Ld DerivedData/App/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
(1 failure)
 -> MyProject-SDK (1.2.4)
    - WARN  | url: There was a problem validating the URL https://webtrends.com.
    - ERROR | [MyProject-SDK/Optics] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [MyProject-SDK/Watch] xcodebuild:  ld: warning: ignoring file MyProject-SDK/libMyProjectWatchSDK.a, file was built for archive which is not the architecture being linked (i386): MyProject-SDK/libMyProjectWatchSDK.a
    - NOTE  | [MyProject-SDK/Optics] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
    - NOTE  | [MyProject-SDK/Watch] xcodebuild:  ld: warning: ignoring file MyProject-SDK/libMyProjectWatchSDK.a, file was built for archive which is not the architecture being linked (x86_64): MyProject-SDK/libMyProjectWatchSDK.a

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error and 1 warning.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/lint.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

```

**Comment by chongsuhpark** [comment]
@benasher44    Here is the duplicate symbol error

> duplicate symbol _OBJC_METACLASS_$_XYZConfigSettings in:
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libOpticsSDK.a(XYZConfigSettings.o)
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libMyProjectSDK.a(XYZConfigSettings.o)
> duplicate symbol _OBJC_CLASS_$_XYZConfigRSTUrlBase in:
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libOpticsSDK.a(XYZConfigRSTUrlBase.o)
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libMyProjectSDK.a(XYZConfigRSTUrlBase.o)
> duplicate symbol _OBJC_METACLASS_$_XYZConfigRSTUrlBase in:
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libOpticsSDK.a(XYZConfigRSTUrlBase.o)
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libMyProjectSDK.a(XYZConfigRSTUrlBase.o)
> duplicate symbol _OBJC_CLASS_$_XYZTask in:
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libOpticsSDK.a(XYZTask.o)
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libMyProjectSDK.a(XYZTask.o)
> duplicate symbol _OBJC_METACLASS_$_XYZTask in:
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libOpticsSDK.a(XYZTask.o)
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libMyProjectSDK.a(XYZTask.o)
> duplicate symbol _OBJC_CLASS_$_XYZConfigBatteryMinimumChargePercentage in:
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libOpticsSDK.a(XYZConfigBatteryMinimumChargePercentage.o)
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libMyProjectSDK.a(XYZConfigBatteryMinimumChargePercentage.o)
> duplicate symbol _OBJC_METACLASS_$_XYZConfigBatteryMinimumChargePercentage in:
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libOpticsSDK.a(XYZConfigBatteryMinimumChargePercentage.o)
>     /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/libMyProjectSDK.a(XYZConfigBatteryMinimumChargePercentage.o)
> ld: 219 duplicate symbols for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
>

**Comment by benasher44** [comment]
@chongsuhpark sorry can you post the podspec as well?

**Comment by chongsuhpark** [comment]
@benasher44   Sure!

```
Pod::Spec.new do |s|
  s.name         = "MyProject-SDK"
  s.version      = "1.2.4"
  s.summary      = "My Project Summary"
  s.license      = 'COMMERCIAL'
  s.homepage     = "https://MyProject.com"
  s.author             = { "My Name" => "My.Name@myProject.com"}
  
  s.ios.deployment_target = "8.0"
  s.ios.frameworks = "Foundation", "UIKit", "SystemConfiguration", "Security", "MainTelephony", "WebKit"
  
  s.source       = { :git => "https://gh.MyProject.com/ios-pod", :tag => "1.2.4" }

  s.subspec 'Watch' do |watch|
    watch.source_files = "WatchHeaders", "WatchHeaders/**/*.h"
    watch.vendored_library = "libMyProjectWatchSDK.a"
    watch.watchos.deployment_target = "2.0"
    watch.ios.deployment_target = "8.0"
  end

  s.subspec 'Main' do |main|
    main.source_files  = "Headers", "Headers/**/*.h"
    main.exclude_files = "Headers/Exclude"
    main.resources = "SharedAssets/*"

    main.libraries = "z","sqlite3" #Zlib for gzip, sqlite3 for event store
    main.vendored_library = "libMyProjectSDK.a"
  end

  s.subspec 'Optics' do |optics|
    optics.source_files  = "Headers", "Headers/**/*.h"
    optics.exclude_files = "Headers/Exclude"
    optics.resources = "SharedAssets/*"
    optics.dependency 'MyProject-SDK/Main'

    optics.libraries = "sqlite3" # sqlite3 for db
    optics.vendored_library = "libOpticsSDK.a"
  end
end
```

**Comment by chongsuhpark** [comment]
@benasher44   All these problems showed up when I updated my project to the Cocoapod v1.1.1   Never had issue with Cocoapod v0.39 interestingly.

**Comment by dnkoutso** [comment]
@chongsuhpark are you linting? Then this makes perfect sense, updating to 1.0 forces the linter to link your project which is actually more correct.

**Comment by chongsuhpark** [comment]
@dnkoutso  I executed 

`$pod spec lint <mypodspecfile.podspec> --verbose`

Yes, if things are changed for whatever reason, I am looking for work around solution for my podspec.

**Comment by benasher44** [comment]
@chongsuhpark it looks like libOpticsSDK and libMyProjectSDK have dup symbols. Are these libs not intended to be used at the same time?

**Comment by chongsuhpark** [comment]
@benasher44   Yes, they are intended to use at the same time.  libOpticsSDK has dependencies to libMyProjectSDK but not the other way.   Indeed, both are just targets under same project and libOpticsSDK shares a lot of code from libMyProjectSDK but not the other.

**Comment by benasher44** [comment]
According to the output there, it appears that those 2 libraries have duplicates of the same code in them. For example, `XYZTask` appears to be in both binaries. Is that unexpected?

**Comment by chongsuhpark** [comment]
@benasher44  I think probably it is the right behavior as @dnkoutso pointed out although I never encountered this problem with 0.39 in the past.   Whatever it maybe, I am trying to find a resolution to go around this problem.  Any suggestion would be greatly appreciated.

**Comment by benasher44** [comment]
I think ideally you make another library that those 2 other specs depend on, which would contain all of the duplicated symbols/classes there. Does that make sense?

**Comment by chongsuhpark** [comment]
@benasher44   Yes, that totally makes sense.  However what I am trying figure out is bypassing the "duplicate symbol" problem during linting without changing the project structure itself.   To be more specific,  I hope there is a way to state  "dependencies" somewhere in the podspec so that lint process skip duplicates.

**Comment by benasher44** [comment]
If you make a podspec for it, you can list it as a dependency :). At present, CocoaPods doesn't have a way to split out dependencies from binaries or recognize that binaries share a dependency.

**Comment by chongsuhpark** [comment]
@benasher44   Yes, that's what I thought and I've already declared the dependency from "Optics" to "Main":  

```
s.subspec 'Optics' do |optics|
    optics.source_files  = "Headers", "Headers/**/*.h"
    optics.exclude_files = "Headers/Exclude"
    optics.resources = "SharedAssets/*"
    optics.dependency 'MyProject-SDK/Main'   <--- right here!

    optics.libraries = "sqlite3" # sqlite3 for db
    optics.vendored_library = "libOpticsSDK.a"
  end
```
where "Main" subspec generates: **libMyProjectSDK.a**  and "Optics" generates: **libOpticsSDK.a**

however, as you may find my previous (see way above podspec file) post, still no effect.  This is something I am trying to figure out. 

```
duplicate symbol _OBJC_CLASS_$_MYConfigAutoSendThresholdPercent in:
    /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/MyProject-SDK/**libOpticsSDK.a**(MYConfigAutoSendThresholdPercent.o)
    /var/folders/1x/rkjxf8rd2cggr719r37gsrgc7q2_7n/T/CocoaPods/Lint/Pods/libMyProject-SDK/**libMyProjectSDK.a**(MYConfigAutoSendThresholdPercent.o)

```
As you see, both **libMyProjectSDK.a** and **libOpticsSDK.a** are independent binaries though linting generate "duplicate symbol" problem.

I'd own you million $$$ if you could help me finding some resolution.

**Comment by benasher44** [comment]
Hmm. I can't think of any great ways around this right now. I'd probably just generate a podspec with a binary that has the right combo of symbols in it that I need for the project. So for example: libMyProjectSDK+libOpticsSDK.a (for when you need both libMyProjectSDK and libOpticsSDK), libMyProjectSDK.a (for when you need only libMyProjectSDK), and libOpticsSDK.a (for when you need only libOpticsSDK). Does that make sense?

I'll update though if I come up with something better.

**Comment by chongsuhpark** [comment]
@benasher44    Yes, I am open for creating combined  file instead.  However I am not  quite sure how I should modify my current podspec file to generate singe  libCombiledSDK.a from libMyProjectSDK and libOpticsSDK.a    Can you give me some tips on that from what I have up there?

**Comment by benasher44** [comment]
@chongsuhpark you'd have to generate that binary outside of CocoaPods, and then make a podspec that uses it.

**Comment by anumshk27** [comment]
Im facing the similar issues, in my case i only have the framework file no any other dependency. when i run 'pod spec lint' it give me error .

<img width="857" alt="screen shot 2017-03-13 at 3 33 49 pm" src="https://cloud.githubusercontent.com/assets/26293676/23850744/88cd2abe-0802-11e7-9ce2-bf22edbae58b.png">

This is how i define architecture.

<img width="833" alt="screen shot 2017-03-13 at 3 35 03 pm" src="https://cloud.githubusercontent.com/assets/26293676/23850793/bd206b82-0802-11e7-91e1-6d4db2394b82.png">

following the 'lipo -info' of the framework.

<img width="758" alt="screen shot 2017-03-13 at 3 37 39 pm" src="https://cloud.githubusercontent.com/assets/26293676/23850862/0c1f85d8-0803-11e7-98c8-17b30ed9c090.png">

I also attached the --verbose log in text edit file as attachment, im seeking urgent help

[--verbose.txt](https://github.com/CocoaPods/CocoaPods/files/837934/--verbose.txt)
Thanks.
