### ISSUE TITLE
Can't search my pod 

### ISSUE THREAD

**Issue by Hanwp** [CocoaPods/CocoaPods#6317]
```
bogon:~ hanwei$ pod trunk me
  - Name:     Hanwp
  - Email:    1019260351@qq.com
  - Since:    December 14th, 05:53
  - Pods:
    - TangramKit
  - Sessions: ..........
bogon:~ hanwei$ pod search TangramKit
[!] Unable to find a pod with name, author, summary, or description matching `TangramKit`
```

**Comment by Hanwp** [comment]
@fabiopelosin @segiddins @alloy @mrackwitz 

Help me check it

**Comment by orta** [comment]
Looks like it's working [on the website](https://cocoapods.org/?q=TangramKit), I guess your search cache is out of date, or your pod repo hasn't been updated

![screen shot 2016-12-27 at 12 03 46 pm](https://cloud.githubusercontent.com/assets/49038/21504393/8fbe5f30-cc2c-11e6-9d0d-1f38059ed94f.png)
