### ISSUE TITLE
[iOS] xcodebuild: Returned an unsuccessful exit code.

### ISSUE THREAD

**Issue by RMLKP** [CocoaPods/CocoaPods#6318]
When I run:

`pod spec lint --verbose  

it gives me this error:

> - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
>     - NOTE  | [iOS] xcodebuild:  HOLLER-iOS/HOLLER-iOS/Classes/Private/HLAnalytic.h:10:9: fatal error: 'Holler/HLError.h' file not found
>     - NOTE  | [iOS] xcodebuild:  HOLLER-iOS/HOLLER-iOS/Classes/Public/HLError.m:10:9: fatal error: 'Holler/HLConstants.h' file not found

My `HLError.m`:

```
#import "HLError.h"
#import "HLConstants.h"
```

My `HLAnalytic.h`:

```
#import <Foundation/Foundation.h>
#import "HLError.h"

```
Please help me with this. Thanks.

**Comment by dnkoutso** [comment]
One thing is that you have two `Holler.h` files in your project.

**Comment by benasher44** [comment]
Hi @RMLKP! Can you please provide the podspec and the file/folder layout/structure in your pod repo? Thanks!

**Comment by benasher44** [comment]
Oh I see it's on Github. It appears you're doing `#import <Holler.h>`. I don't think that style of import will work for importing headers local to your framework. Can you please try doing `#import "Holler.h"` for that one and others like it, where you're importing headers local to your framework/library? Thanks!

**Comment by khuong291** [comment]
I am `RMLKP`, I fixed it by chaging this line

`s.source_files = 'HOLLER-iOS/HOLLER-iOS/Classes/*.{h,m}'`

to

`s.source_files = 'HOLLER-iOS/HOLLER-iOS/Classes/*.{h,m}'`

**Comment by benasher44** [comment]
@khuong291 great I'm glad you got it sorted out! I'm going to go ahead and close this then, since this doesn't appear to be anything we can fix on CocoaPods's end. Have a great day!
