### ISSUE TITLE
'pod lib create' project with no example app cannot run tests in Xcode 8

### ISSUE THREAD

**Issue by hirad** [CocoaPods/CocoaPods#6322]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Using Xcode 8 and Cocoapods 1.1.1, I opened an old cocoapod project (ie. library that I wrote and use through CP) that was written with Cocoapods 0.3.9 and Xcode 7 and tried to modify it. This project is Objective-C only.

This project was set up with `pod lib create`. In Xcode 8, the tests no longer run because "Could not find test host for \<name of project\>" (see below).

To attempt to fix this, I used `pod lib create` again to create a new pod project (with 1.1.1). I chose *not* to add an example project. In this case, too, the generated project would not run the tests in Xcode 8.2.

Both projects (my old pod project, and a new one set up with `pod lib create`) can be tested successfully with Xcode 7.

## What did you do?

The exact steps are as follows:

```
$ pod lib create ATestPod
Cloning `https://github.com/CocoaPods/pod-template.git` into `ATestPod`.
Configuring ATestPod template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide:
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > ObjC

Would you like to include a demo application with your library? [ Yes / No ]
 > No

Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > No

What is your class prefix?
 > ATP

Running pod install on your new library.

Analyzing dependencies
Fetching podspec for `ATestPod` from `../`
Downloading dependencies
Installing ATestPod (0.1.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `ATestPod.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'ATestPod/Example/ATestPod.xcworkspace'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
```

Then open the `.xcworkspace` file and press Cmd-U.

## What did you expect to happen?

I should be able to run tests successfully in Xcode 8.2.

## What happened instead?

Only Xcode 7 can run the tests in the generated project.

Xcode 8.2 produces the following error:
<img width="448" alt="screen shot 2016-12-18 at 5 05 38 pm" src="https://cloud.githubusercontent.com/assets/1005340/21298341/d009f188-c544-11e6-919c-071948bb1e95.png">

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.2 (8C38)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/hiradmotamed/.rvm/rubies/ruby-2.3.0/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 34306c0e7022fda14664004d19757349df024acb
               master - https://github.com/CocoaPods/Specs.git @ 20e54f92cceca04107f12dc67e8be9e176d3da1c
               pendarlabs - https://github.com/PendarLabs/Specs.git @ 5706ec78dfc095077f608381d3425282d72e0687
```

### Installation Source

```
Executable Path: /Users/hiradmotamed/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
Thanks for the issue!

Please take this over to the [pod-template](https://github.com/CocoaPods/pod-template) repo where this can be discussed 👍
