### ISSUE TITLE
pod update changes line in Pods-Answer This-frameworks.sh

### ISSUE THREAD

**Issue by GKHerping** [CocoaPods/CocoaPods#6329]
# Report
## What did you do?
$ pod update
I have an xcode project named Answer this located at 
`/Users/userName/Dropbox/Answer\ This`

## What did you expect to happen?

1. Update all pod dependencies correctly.
2. open project.xcworkspace
3. build without errors

## What happened instead?

1. and 2. works but three return error as described here: 
[http://stackoverflow.com/questions/40615207/run-custom-shell-script-cp-embed-pods-frameworks-no-such-file-or-directory](url)
The fix is in the link above, but it would be great to not having to always edit the line:
`local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS} --preserve-metadata=identifier,entitlements "$1""`

where `"$1"` needs to be replaced by `'$1'`

## CocoaPods Environment
Output from `pod env`:
### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2 (8C38)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 54ca87b32df838ee8e633ff3bda0dbcb0fc226e6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '10.1'

target 'Answer This' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Answer This
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
	pod 'Firebase/Crash'
    pod 'Firebase/Messaging'
	pod 'FBSDKLoginKit'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
    pod 'OneSignal'

end
```

**Comment by benasher44** [comment]
Hi @GKHerping! Thanks for letting us know! 1.2.0.beta.2 will be out shortly, which includes the full fix. Thanks for your patience!
