### ISSUE TITLE
XCode 8.1 - Include of non-modular header inside framework

### ISSUE THREAD

**Issue by xingheng** [CocoaPods/CocoaPods#6330]
It seems the issue #4420 has some difference behaviors in cocoapods 1.1.1, here is it, I have a private pod project which links against libxml2 from system.

`  s.libraries         = 'z', 'xml2'
  s.xcconfig          = { 'LIBRARY_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2', 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2'}
`

The libxml2 is a static library from system SDK, it couldn't be included with `@import`, I also compared my podspec with [KissXML](https://github.com/robbiehanson/KissXML/blob/master/KissXML.podspec) without obvious usage errors.

Temporarily, I fixed it by appending the CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES with YES to xcconfig finally.

`s.xcconfig          = { 'LIBRARY_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2', 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2', 'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES' }`

It works now, but not the right way, so report it here.

Env: cocoapods 1.1.1, ruby 2.3.3p222, Xcode 8.1, OS X 10.11.6.

**Comment by benasher44** [comment]
Hi there! Checkout this SO post about writing custom module maps for just this scenario: http://stackoverflow.com/questions/25171680/swift-framework-with-libxml. Once you have this module map setup, you can import the module's you've defined there. It might take some experimenting to get this to work with CocoaPods, and I'd be curious to hear what you find.

**Comment by benasher44** [comment]
You might be able to do it by just adding the module map to your source files

**Comment by xingheng** [comment]
Sorry, I lost the above environment context, close it temporarily. Maybe later.
