### ISSUE TITLE
Cocoapods warning for ALWAYS_SEARCH_USER_PATHS if its on or off, but in different places

### ISSUE THREAD

**Issue by ecnepsnai** [CocoaPods/CocoaPods#6334]
When I run `pod install` on my project, I get warnings that ALWAYS_SEARCH_USER_PATHS is defined.

This is true, because if I compile my project without that setting defined, I get a build warning that ALWAYS_SEARCH_USER_PATHS is set to yes.

I'm in a catch 22 here, if I update the setting to what pod install suggests, the build has warnings, and if I update to what the build warning suggests, pod install has warnings.

Root Project: Always Search User Paths: **No** (Explicitly defined)
App Target: Always Search User Paths: **No** (Explicitly defined - if let to inherited it's value is yes)

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2 (8C38)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9c9bfa4061936fe82f0beff8e933ecd4e7e245bd
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.3'
#omitted
```

**Comment by benasher44** [comment]
Hi! To fix this, go to that setting you were changing in Xcode, and instead of changing it, highlight it (by just clicking on it to make it highlighted), and hit backspace. This will make that setting inherit from its parent configuration (usually CocoaPods XCConfigs or project-level settings.

**Comment by ecnepsnai** [comment]
I've tried that already:

> Explicitly defined - if let to inherited it's value is yes

**Comment by benasher44** [comment]
If you want the warning to go away, you'll need to highlight the setting and hit backspace, whereas I believe you're saying you've already explicitly set it to Yes. Those are actually two different things, in terms of what CocoaPods sees.

**Comment by dnkoutso** [comment]
@benasher44 I think we should close this, no action needed for cocoapods lib.

**Comment by benasher44** [comment]
I agree. There no follow up to do within CocoaPods at the moment for issues like this. Thanks again for the report though, and have a great day!
