### ISSUE TITLE
want to set configuration debug setting for framework in podSpec

### ISSUE THREAD

**Issue by njafei** [CocoaPods/CocoaPods#6338]
when I use pod , I can use configurations => ['Debug']  when I want to use this only in debug, I can set like this,
but in podSpec,I want to use some framwork only in debug,I can't find the key to set ,any one know it?

**Comment by benasher44** [comment]
Hi @njafei! We don't currently support this for podspecs, since a podspec represents a complete package that someone would install and use in their application. Could you describe some more the use case for this?

**Comment by njafei** [comment]
I use a pod for manager the third-party frameworks , and some of these frameworks are only used in   debug,so I ask this question.

**Comment by benasher44** [comment]
@njafei unfortunately we only allow setting this in the Podfile to avoid having pods that are distributed such that parts of the pod are only usable in certain configurations. Generally, the configuration in which you use the pod is a detail of how the pod is used, not the pod itself. If you could share more about your Podfile and the pod itself, maybe I could help come up with a workable solution?

**Comment by njafei** [comment]
@benasher44  
thanks, I know this is not a common need for those who use cocoapods. so I finally decided use a new pod to do this.

**Comment by benasher44** [comment]
@njafei okay sounds good! I'm glad you were able to find a workaround!

**Comment by zhonglaoban** [comment]
i want to enable assert in debug, disable assert in release, when i set `"GCC_PREPROCESSOR_DEFINITIONS" => "NDEBUG=1"`in `pod_target_xcconfig`,  it override all configuration. what should i do?  thanks you all.
