### ISSUE TITLE
How to avoid Class A is implemented XXX and XXX

### ISSUE THREAD

**Issue by smoothdvd** [CocoaPods/CocoaPods#6339]
I have a Podfile with
```
platform :ios, '8.0'

abstract_target 'common' do
    pod 'AFNetworking', '~> 2.0'

    target 'LibKit' do
    end
end

target 'App' do
    pod 'Orbiter', '~> 2.0'
end
```

LibKit is a framework used in App.
Problem is pod 'Orbiter' dependency  'AFNetworking', after linking the App will meet warning of:
Class AFHTTPRequestOperation is implemented in both XXX and XXX. One of the two will be used. Which one is undefined.

How to avoid this problem?

**Comment by benasher44** [comment]
Hi @smoothdvd! Thanks for reporting this! This is a known issue and a duplicate of #6065. I'm going to close this one, since we're keeping track of it in the other issue. Have a great day!
