### ISSUE TITLE
Unable to satisfy the following requirements when 'pod install'ing on CI server.

### ISSUE THREAD

**Issue by ishaanSejwal** [CocoaPods/CocoaPods#6340]
# Report

## What did you do?

Tried to install cocoapods as a gem through gemfile command `gem 'cocoapods'`. Calling simply bundle install. Then called pod install.

## What did you expect to happen?

Expected dependencies to be installed 

## What happened instead?

Instead got:

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `RealmSwift (~> 2.1.0)` required by `Podfile`
- `RealmSwift (~> 2.1.0)` required by `Podfile`
- `RealmSwift (= 2.1.2)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `RealmSwift (~> 2.1.0), RealmSwift (= 2.1.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```
When building got `error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`
This does not happen on my local machine. But only on the CI server instance.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
    RubyGems : 2.5.2
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e8e5b723a90be3580792ecd4175a2fe72bf65ef4
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '8.4'
pod 'RealmSwift', '~> 2.1.0'
target 'projectNode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for projectNode

  target 'projectNodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'projectNodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0.2'
    end
  end
end
```

**Comment by benasher44** [comment]
Hi @ishaanSejwal! Thanks for reporting this! Since you're using a Gemfile, are you making sure to run `bundle exec pod <pod command>` on CI? Also, can you please provide the exact `pod` command you're using on CI? Thanks!

**Comment by ishaanSejwal** [comment]
`bundle exec pod install` is what i call after `gem install bundler` &`bundle install`

**Comment by segiddins** [comment]
Do you need to add `--repo-update` or run `pod repo update master` on your CI?

**Comment by benasher44** [comment]
Ah yep good call. You'll need to do one of those that @segiddins suggested to ensure that your CI machine can see updated specs.

**Comment by ishaanSejwal** [comment]
@segiddins @benasher44 that did it. I just realised my server was persisting repo checkouts across builds, which I thought was not the case.

**Comment by benasher44** [comment]
@ishaanSejwal that's great to hear! Thanks for letting us know that you got it resolved, and have a great day!
