### ISSUE TITLE
prepare_command not working correctly when linting podspec

### ISSUE THREAD

**Issue by dvor** [CocoaPods/CocoaPods#6343]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Linting pod that was previously working fine (it was submitted ~2 years ago):
`pod lib lint`

## What did you expect to happen?

Linting to work correctly.

## What happened instead?

Command from `prepare_command` cannot be applied, which leads to error. This pod is included to other podspec, which cannot be linted for same reason.

Funny thing is that everything worked on 3 of December and stopped somewhere around 15. I don't remember myself updating anything, also I tried playing with configuration, downgrading to previous CocoaPods/Xcode/whatever - still it didn't work.

Inside `prepare_command` I'm trying to apply patch to source code which is downloaded from other website specified `source` property. I've added `pwd` command to my script and it seems that it is executing in the folder with podspec itself:

```bash
pwd # > /path/to/my/git/repo
pod lib lint
    # somewhere inside
    prepare_command
        pwd # still /path/to/my/git/repo. I assume that here it should output path to downloaded source code instead
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.1 (8B62)
         Git : git version 2.6.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3a4526bdc67900be2c10d166a77f5d21779ec940
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-art         : 0.9.3
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

You can find spec [here](https://github.com/Antidote-for-Tox/libopus).

**Comment by benasher44** [comment]
Hi @dvor! I ran `pod spec lint https://raw.githubusercontent.com/Antidote-for-Tox/libopus/master/libopus-patched-config.podspec`, and this is what I got

```
 -> libopus-patched-config (1.1)
    - ERROR | [libopus-patched-config/fixed,libopus-patched-config/float] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [libopus-patched-config/fixed,libopus-patched-config/float] xcodebuild:  libopus-patched-config/silk/A2NLSF.c:35:10: fatal error: './config.h' file not found
    - NOTE  | [libopus-patched-config/fixed,libopus-patched-config/float] xcodebuild:  libopus-patched-config/silk/ana_filt_bank_1.c:29:10: fatal error: './config.h' file not found
    - NOTE  | xcodebuild:  libopus-patched-config/silk/float/apply_sine_window_FLP.c:29:10: fatal error: './config.h' file not found
    - NOTE  | [tvOS] [libopus-patched-config/fixed] xcodebuild:  libopus-patched-config/silk/fixed/apply_sine_window_FIX.c:29:10: fatal error: './config.h' file not found

Analyzed 1 podspec.
```

Is this similar to the error you got as well?

**Comment by dvor** [comment]
Hi @benasher44! Nope, I don't even get to the `xcodebuild` phase. For me it is failing when trying to apply patch:

```bash
 -> libopus-patched-config^M -> libopus-patched-config (1.1)
    - ERROR | [OSX] unknown: Encountered an unknown error (/bin/bash -c

# ... whole patch goes here

patch -p1 < config-include.patch

/bin/bash: line 2: src/config.h: No such file or directory
) during validation.

Analyzed 1 podspec.
```

As I said before, it seems that it tries to apply patch in current working directory, not to the source code itself.

I guess there is something wrong with my configuration, but I have no idea what. Also this is happening on my second computer, so both of them are somehow corrupted.

**Comment by dvor** [comment]
Any ideas on how this can be fixed?

**Comment by dvor** [comment]
Okay, finally fixed it myself. I simply uninstalled all gems I had and then installed CocoaPods from scratch. Probably there was a gem with different version that introduced the issue.

```bash
[sudo] gem uninstall --all
[sudo] gem install cocoapods
```

**Comment by benasher44** [comment]
@dvor great! I'm glad you got it fixed, and we appreciate you sharing the solution. Have a great day!
