### ISSUE TITLE
How can I pass precompile parameters between the pods

### ISSUE THREAD

**Issue by ZephyrHan** [CocoaPods/CocoaPods#6349]
In PodA : By using spec.pod_target_xcconfig = {  'OTHER_CFLAGS' => '-DXXX' } the macro XXX can be added to the PodA for precompiling.

In PodA : BY using spec.user_target_xcconfig = {  'OTHER_CFLAGS' => '-DXXX' } the macro XXX can be added to the App for precompiling.

Now, I'm using cocoa pods for managing many of my private pods. Is there a way to pass a macro definition for precompiling from a pod A to another pod B? So that the pod B can check whether the pod A has also been import to the App before compiling pod B. This is essential to decouple pod B from pod A.

For example, There are a serious of components managed by cocoa pods in a project. And there is one special component for managing the others components. The management component defined a life cycle of a component integrating process as a protocol and a default implementation as a base class.
In the other components, I will provide a integrating interface class which confirms to the protocol or inherit the default base classes. But I don't want to add a dependence to all the other components to integrate. The integrating interface should be an optional feature. So that I'd like to use precompile to control it. 
When the app only import the component without the management component, there won't be a compiling error.

Thanks a lot.

**Comment by orta** [comment]
There isn't a way for a pod to affect the other Pods targets I'm afraid. For things like your use case a [subspec](https://guides.cocoapods.org/syntax/podspec.html#group_subspecs) that has a hard dependency should work fine.
