### ISSUE TITLE
How to write a vendor_framework for a only device framework in podspec

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#6350]
I have a framework binary that only for device. 

When I write a podspec, I found I can NOT skip the link if the target devcie is a  simulator.

after Google it and found the article : http://blog.carbonfive.com/2014/01/24/cocoapods-for-device-only-ios-libraries/

But I think it is very hard. I hope that there is a easy way to do it.

**Comment by orta** [comment]
Hey there, this looks like a great example of a usage question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by Whirlwind** [comment]
I am requesting a feature, and NOT ask the usage.

**Comment by orta** [comment]
Cool, then can you please write an issue explaining what you'd like to see in order to fix your issue?

**Comment by Whirlwind** [comment]
The `vendor_frameworks` will apply to all device, so I want a new way to apply to some device. eg:

```
s.vendor_frameworks.arm64 = `xxx.framework`
```

Than it will create a xcconfig: 
```
OTHER_LDFLAGS[arch=arm64] = "-framework xxxx"
```

and so on.

**Comment by zeusent** [comment]
I'm interested in this as well... I have a Framework which I don't own and I need to embed it in a private Pod I'm writing, but the Framework only has slices for arm* architectures.

The Pod I'm writing has a "default" behaviour when running on the Simulator and the framework is only included when running on the device using an `#if` statement. But I couldn't, for the love of god, pass the `pod spec lint` when adding the Podspec to my private specs repo.

**Comment by tringkishorekumar** [comment]
Have you find any solution that works on Xcode 8?

**Comment by Whirlwind** [comment]
@orta could you help us to add this feature?

**Comment by akhilcb** [comment]
Any update on this feature request?
