### ISSUE TITLE
"xxxx-swift.h" header file  not found in dependent pod

### ISSUE THREAD

**Issue by VenuKotha** [CocoaPods/CocoaPods#6351]
Hi

I m using cocoapod version :1.0.0
xcode version: 8.1

I created a new project called "NetworkManager" using Swift mix and match approach . As per apple guidelines xcode generated "<Modulename>-swift.h"  header file. So "NetworkManger-swift.h" file generated at "build/intermediates/NetworkManager.build/Debug-iphonesimulator/NetworkManager.build/Derivedsources/" in my system. I added a statement #import "NetworkManager-swift.h" in my obj c file to use swift class. Build was success. Then converted this project into local pod.

I am adding above pod as dependent to client project.  When i compile client project i am getting  below error
fatal error: 'NetworkManager-Swift.h' file not found
#import "NetworkManager-Swift.h"   

This time the "NetworkManager-swift.h" generated at "/Build/Products/Debug-iphoneSimulator/NetworkManger/NetworkManager.framework/Headers" path.

is there any setting i have to set in podspec of my pod or in main project?
I did not find solution and stucked up from last few days
thank you

**Comment by benasher44** [comment]
Hi @VenuKotha! Are you attempting to import that header from outside of the framework project?

**Comment by VenuKotha** [comment]
Yes! because i want to access those from my client projectt

**Comment by VenuKotha** [comment]
I can not share my code so i created sample projects and placed in the below url. I created for just reference and can not execute.
https://github.com/VenuKotha/TestProj.git
https://github.com/VenuKotha/NMObjC.git
https://github.com/VenuKotha/NMSwift.git

Explanation:- "NMSwift" is one of my private pod written in Swift. I want to use this pod as dependent to "NMObjc" project. "NMObjc" is another private pod written in objc. As per apple guidelines if we want to use swift class in ObjC we have to use objective generated interface. So,  I added "#import "NMSwift-Swift.h" in one of the file called "MZNetworkManager.m" in  "NMObjC" project and Build was success.

Now  i am using "NMObjc" as dependent for "TestProj".  If I compile "TestProj" given error "NMSwift-Swift.h" file not found error

**Comment by benasher44** [comment]
In NMObjc, you should be importing NMSwift using angle brackets like this: `#import <NMSwift/NMSwift-Swift.h>`. What I see in the project is `#import "NMSwift-Swift.h"`.

**Comment by VenuKotha** [comment]
I tried like your suggestion also.  If I used the above I am receiving "fatal error: NMSwift/NMSwift-Swift.h' file not found
#import <NMSWift/NMSwift-Swift.h>

at the time of NMObjc project build

**Comment by VenuKotha** [comment]
Hi Ben, 
Thank you very much for your solution. Your solution is working in the reference project but it is not working with my project. After analyze I found one observation is in my project NMObjc project created with Cocoatouch static library template. So it works if I Imported "#import "NMSwift-Swift.h".  In this context build is failed at "TestProject".
How can I handle in this case?
Can't I use swift mix and match if one pod is Staticlibrary template and other pod is singleview template?

**Comment by benasher44** [comment]
Ah! For Swift libraries, you have to use the dynamic library template. That's an unfortunate limitation of Swift at this time.

**Comment by benasher44** [comment]
Can you try with the dynamic library template?

**Comment by VenuKotha** [comment]
Thank you Ben!

**Comment by benasher44** [comment]
@VenuKotha no problem! It sounds like you were able to resolve this issue, so I'm going to close this out. If that's not the case, please feel free to reopen the issue. Have a great day!

**Comment by cristianoccazinsp** [comment]
I'm having the same issue.  

I can build the stand alone project just fine if it has mixed swift/objc files, by just adding the following import to my .h file:
```
#import "MODULE_NAME-Swift.h"
```

However, when trying to build a react native app with cocoapods, I get that "MODULE_NAME-Swift.h" cannot be found. For me, it looks like cocoa is not building/generating the .h file.  How can I fix this?

**Comment by khanakia** [comment]
Any update on the issue? I am using react-native turbo Modules and trying to add the Swift code and getting this error
`'BarcodeVision-Swift.h' file not found when i include the header in `.mm` file `#import "BarcodeVision-Swift.h"`

I have checked my DerivedData folder and file exist there already

```
find ~/library/Developer/Xcode/DerivedData/ -name "*-Swift.h"|xargs basename|sort -u

## output
BarcodeVision-Swift.h
Compatibility
```

**Comment by shirakaba** [comment]
Although this is an old thread, in case anyone ends up here in future, the `-Swift.h` generated header is only generated for frameworks (and I guess libraries? Not sure) that are dynamically linked, not static ones, as Ben said [above](https://github.com/CocoaPods/CocoaPods/issues/6351#issuecomment-273200485):

> Ah! For Swift libraries, you have to use the dynamic library template. That's an unfortunate limitation of Swift at this time.

In your `Podfile`:

```ruby
# Use whatever you like as your default method of packaging (frameworks) and linking (static):
use_frameworks! :linkage => :static

# To override those defaults for a particular Pod, add the following code:
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name == 'BarcodeVision' || pod.name == 'SomeOtherPod'
      def pod.build_type;
        Pod::BuildType.new(:linkage => :dynamic, :packaging => :framework)
      end
    end
  end
end
```

Now run `pod install` to reconfigure your Pods, and you should find that the following header import now works:

```c
#import <BarcodeVision/BarcodeVision-Swift.h>

// Note that if your pod has `_` or `-` characters in the name, and the packaging
// type is framework rather than library, then you may have to swap the `_` to `-`
// or vice versa in this import. It's best to avoid them in your pod name altogether!
// 
// This is all because clang modules don't support hyphens:
// http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
```
