### ISSUE TITLE
Cannot install CocoaPods, undeclared identifier 'rb_cFixnum' and 'rb_cBignum'

### ISSUE THREAD

**Issue by alleyrat** [CocoaPods/CocoaPods#6365]
I ran `sudo gem install cocoapods -V` and the install fails now. This has not happened to me before. What should I do next? I cannot run `pod env` because `pod` is not installed.

Here is the output:

HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=cocoapods
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=activesupport,claide,cocoapods-core,cocoapods-deintegrate,cocoapods-downloader,cocoapods-plugins,cocoapods-search,cocoapods-stats,cocoapods-trunk,cocoapods-try,colored,escape,fourflusher,gh_inspector,molinillo,nap,xcodeproj
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=CFPropertyList,fuzzy_match,nanaimo,netrc
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=concurrent-ruby,i18n,json,minitest,thread_safe,tzinfo
200 OK
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_addition.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_encoding.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_fixtures.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_generate.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_generic_object.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_string_matching.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_unicode.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/.gitignore
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/.travis.yml
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/CHANGES
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/COPYING
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/COPYING-json-jruby
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/GPL
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/Gemfile
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/README-json-jruby.markdown
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/README.rdoc
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/Rakefile
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/TODO
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/VERSION
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/data/example.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/data/index.html
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/data/prototype.js
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/diagrams/.keep
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/fbuffer/fbuffer.h
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator/depend
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator/extconf.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator/generator.c
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator/generator.h
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/parser/depend
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/parser/extconf.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/parser/parser.c
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/parser/parser.h
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/parser/parser.rl
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/extconf.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/install.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/ByteListTranscoder.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/Generator.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/GeneratorMethods.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/GeneratorService.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/GeneratorState.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/OptionsReader.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/Parser.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/Parser.rl
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/ParserService.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/RuntimeInfo.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/StringDecoder.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/StringEncoder.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/java/src/json/ext/Utils.java
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/json-java.gemspec
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/json.gemspec
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/json_pure.gemspec
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/bigdecimal.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/complex.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/core.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/date.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/date_time.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/exception.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/ostruct.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/range.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/rational.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/regexp.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/struct.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/symbol.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/add/time.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/common.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/ext.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/ext/.keep
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/generic_object.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/pure.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/pure/generator.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/pure/parser.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/lib/json/version.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail1.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail10.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail11.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail12.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail13.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail14.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail18.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail19.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail2.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail20.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail21.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail22.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail23.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail24.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail25.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail27.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail28.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail3.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail4.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail5.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail6.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail7.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail8.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/fail9.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/pass1.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/pass15.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/pass16.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/pass17.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/pass2.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/pass26.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/fixtures/pass3.json
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/setup_variant.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_addition.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_encoding.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_fixtures.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_generate.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_generic_object.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_string_matching.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tests/test_json_unicode.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tools/fuzz.rb
/usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/tools/server.rb
Building native extensions.  This could take a while...
current directory: /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
/usr/local/opt/ruby/bin/ruby -r ./siteconf20170101-23391-g0fhj6.rb extconf.rb
creating Makefile
current directory: /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR=" clean
current directory: /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
generator.c:861:25: error: use of undeclared identifier 'rb_cFixnum'
    } else if (klass == rb_cFixnum) {
                        ^
generator.c:863:25: error: use of undeclared identifier 'rb_cBignum'
    } else if (klass == rb_cBignum) {
                        ^
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2143:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2329:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2201:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2167:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2162:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2158:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2143:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2329:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2201:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2167:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2163:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2158:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2143:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2329:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2201:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2168:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs+1, varc, vari+1))
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2162:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2158:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2143:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2329:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2201:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2167:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2162:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2158:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2143:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2329:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2201:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2167:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2162:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2158:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
    rb_scan_args(argc, argv, "01", &opts);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2143:9: note: expanded from macro 'rb_scan_args'
        rb_scan_args0(argc,argvp,fmt,\
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2329:8: note: expanded from macro 'rb_scan_args0'
                     rb_scan_args_verify(fmt, varc), vars)
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2201:11: note: expanded from macro 'rb_scan_args_verify'
        verify = rb_scan_args_verify_count(fmt, varc); \
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: (skipping 5 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2167:6: note: expanded from macro 'rb_scan_args_count_hash'
     rb_scan_args_count_block(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2162:6: note: expanded from macro 'rb_scan_args_count_block'
     rb_scan_args_count_end(fmt, ofs, varc, vari) : \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/ruby/2.4.0/include/ruby-2.4.0/ruby/ruby.h:2158:12: note: expanded from macro 'rb_scan_args_count_end'
    ((vari)/(!fmt[ofs] || rb_scan_args_bad_format(fmt)))
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 warnings and 2 errors generated.
make: *** [generator.o] Error 1
ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
make failed, exit code 2

Gem files will remain installed in /usr/local/lib/ruby/gems/2.4.0/gems/json-1.8.3 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0/json-1.8.3/gem_make.out

**Comment by DanToml** [comment]
Unfortunately CocoaPods is currently broken on Ruby 2.4 because of some dependency issues related to the Bignun/Fixnum merger. Please downgrade to Ruby < 2.4.0.

**Comment by nicolasiJasica** [comment]
that's right !! thank U
