### ISSUE TITLE
Need Help For Search Issue 

### ISSUE THREAD

**Issue by keshavvishwkarma** [CocoaPods/CocoaPods#6366]
Hi CocoaPods Team,
I hope you are doing great

Could you please help me to resolve my pod issue.
why KVConstraintsKit is showing  21 results in search of [https://cocoapods.org/](https://cocoapods.org/)
and how can I resolve it?
[![Screen Shot 2017-01-02 at 3.17.48 AM.png](https://s30.postimg.org/d0guba6gx/Screen_Shot_2017_01_02_at_3_17_48_AM.png)](https://postimg.org/image/avwha74u5/)
The second problem is that why my lib [KVConstraintKit.podspec.json](https://github.com/CocoaPods/Specs/tree/master/Specs/KVConstraintKit/1.0.0/KVConstraintKit.podspec.json)  is not found

It seems I did something wrong please help me.

I have run `pod trunk push KVConstraintKit.podspec` the command to publish my lib.

**Comment by DanToml** [comment]
@keshavvishwkarma Try running `pod repo update` then you should be able to install it locally again.

Could you please file an issue on https://github.com/CocoaPods/search.cocoapods.org wrt the search issue?

**Comment by keshavvishwkarma** [comment]
@DanToml Thanks for your valuable suggestion.
I did that here is the issue id [#110](https://github.com/CocoaPods/search.cocoapods.org/issues/110)

**Comment by DanToml** [comment]
Closing this issue here and continuing discussion in https://github.com/CocoaPods/search.cocoapods.org/issues/110
