### ISSUE TITLE
Can we write unit test cases for private pod ?

### ISSUE THREAD

**Issue by DeepakCarpenter** [CocoaPods/CocoaPods#6367]
I have multiple private pods in my project. My requirement is to write XCtest cases for entire application including the private pods. so can we write unit test cases for private repo/pod ?

**Comment by DanToml** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests.

**Comment by DeepakCarpenter** [comment]
Thanks Dan @DanToml ,
Sorry for this irrelevant question.

**Comment by DanToml** [comment]
@DeepakCarpenter No worries, I hope you find a solution!
