### ISSUE TITLE
 pod install Abort trap: 6

### ISSUE THREAD

**Issue by yysean** [CocoaPods/CocoaPods#6371]
bogon:test wanjianiosmacmini$ pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (3.0.4)
Generating Pods project
Abort trap: 6
bogon:test wanjianiosmacmini$ cd
bogon:~ wanjianiosmacmini$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
bogon:~ wanjianiosmacmini$ gem --version
2.6.7
bogon:~ wanjianiosmacmini$ pod --version
1.1.1

MacOS:10.12.2
Xcode:8.1

**Comment by mltk96** [comment]
same issue...

**Comment by zyvv** [comment]
[https://github.com/CocoaPods/CocoaPods/issues/6335](url)

**Comment by qiulang** [comment]
According to this http://stackoverflow.com/questions/39980096/xcode8-cocoapods-abort-trap6
upgraded to 1.2.0.beta.3 is one way to fix it. But to upgrade to 1.2.0.beta.3, I need to upgrade ruby from 2.0 to 2.6.7.

**Comment by yysean** [comment]
@qiulang  cocoaPod upgraded to 1.2.0.beta.3 ?

**Comment by qiulang** [comment]
YES. These was 1 answer there said "It's problem with ruby in version 2.0.0 and cocoapods 1.1.1, so if you won't use prerelease version of cocoapods, just update your ruby version for example with rvm:

\curl -sSL https://get.rvm.io | bash -s stable" 

I am really interested if it is the case.

**Comment by mkalmes** [comment]
I've checked the dependencies of CocoaPods and noticed outdated gems:

```
> bundler outdated
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...

Outdated gems included in the bundle:
  * cocoapods-downloader (newest 1.1.3, installed 1.1.2)
  * cocoapods-trunk (newest 1.1.2, installed 1.1.1)
  * minitest (newest 5.10.1, installed 5.9.1)
  * molinillo (newest 0.5.4, installed 0.5.1)
  * xcodeproj (newest 1.4.2, installed 1.3.3)
```

`pod install` works now after updating CocoaPods with `bundler update cocoapods`.

**Comment by benasher44** [comment]
Given that people here seem to be getting this fixed be updating or re-installing gems, this seems to be an issue local to your ruby or gem setup. Since there's nothing we can do to patch CocoaPods to help this situation, I'm going to close this issue. If you're still experiencing this, please file a new issue and fully fill out the issue template with any backtrace information you might have. Thanks and have a great day!

**Comment by fabb** [comment]
`bundle update` fixed the problem for me, still using cocoapods 1.1.1 alright

**Comment by mgrider** [comment]
Thanks to qiulang for posting the stackoverflow link. In my case, I had to run `gem update cocoapods`.
