### ISSUE TITLE
Regarding pod install latency. 

### ISSUE THREAD

**Issue by Khalian** [CocoaPods/CocoaPods#6376]
# Report

## What did you do?

As I understand right now Cocoapods install first instance clones from the github repo (effectively treating it as a content delivery network). https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2FCocoaPods%2FCocoaPods%2Fissues%2F4989%23issuecomment-193772935

As such would it be possible to modify the pod install instructions to use a CDN instead - https://rawgit.com/. If so can someone point to the line of code so that I can modify it?

**Comment by orta** [comment]
I think a plugin could do this, but realistically adding it as the default in CocoaPods would unfairly cripple their servers from the traffic.

The safest option would be to have trunk squash the commits and revert the Specs repo to only a few commits once a day, and so the diff would be tiny. Reducing the space required on disk, and the network traffic. There's work in the 1.2.0 release for this, but someone still needs to build the automation.

**Comment by Khalian** [comment]
CDNs are designed to handle high loads. Github's right now rate limiting for the same. 

Fair enough, so whats the entry point to writing a plugin for this ?

**Comment by DanToml** [comment]
I actually have a half finished plugin lying around for use in CI environments that will pull a CDN'd tarball of the repo and do The Right Thing - I'll clean it up a bit in the morning and try and push out an initial release, alongside the job to update said tarball on s3.

**Comment by Khalian** [comment]
@DanToml Awesome. What CDN are you using ?

**Comment by DanToml** [comment]
@Khalian My deployment uses Cloudfront
