### ISSUE TITLE
wen I  pod install

### ISSUE THREAD

**Issue by ZHSD** [CocoaPods/CocoaPods#6378]
[!] Error installing AFNetworking
[!] /usr/bin/git clone https://github.com/AFNetworking/AFNetworking.git /var/folders/6x/jm7g7wgx7xl09nhbqw8pj2080000gp/T/d20170106-21649-1bgng95 --template= --single-branch --depth 1 --branch 3.1.0

Cloning into '/var/folders/6x/jm7g7wgx7xl09nhbqw8pj2080000gp/T/d20170106-21649-1bgng95'...
fatal: unable to access 'https://github.com/AFNetworking/AFNetworking.git/': Failed to connect to github.com port 443: Operation timed out #

**Comment by axl411** [comment]
It clearly said
>Failed to connect to github.com port 443: Operation timed out

which means something is wrong with your network connection.

**Comment by benasher44** [comment]
Hi @ZHSD! Thanks for bring this up! Unfortunately, this appears to be an issue with your network connection as evidence by the following message in your output:

> Failed to connect to github.com port 443: Operation timed out

I'm going to close this, since there's no patch to CocoaPods that would fix your situation. Thanks for filing, and have a great day!
