### ISSUE TITLE
Use a different temp folder per `pod` run, if possible.

### ISSUE THREAD

**Issue by axl411** [CocoaPods/CocoaPods#6379]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I'm using `pod` on my CI to release pods automatically. This includes run commands like `pod lib lint`, `pod repo push`

 I noticed when 2 builds of releasing pods are running concurrently, there is a high chance that both jobs will fail, due to some wired error messages such as:

```
- ERROR | [iOS] unknown: Encountered an unknown error (Directory not empty @ dir_s_rmdir - /var/folders/bv/3yfb18yn1pj3ys1h79b2pkc400007x/T/CocoaPods/Lint
```

If I wait for sometime and rebuild, the releasing of pod will be succeeded.

Digging further, I find that in every build, `pod lib lint` is using the very same temp folder (e.g.: /var/folders/bv/3yfb18yn1pj3ys1h79b2pkc400007x/T/CocoaPods/Lint) to do its work. I suspect this is the reason causing my builds fail.

So if pod is able to use a different temp folder per run, I will be able to run multiple builds of releasing pods at the same time on my CI.

My pod env:

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2 (8C38)
         Git : git version 2.7.0
Ruby lib dir : /Users/xxx/.rvm/rubies/ruby-2.3.3/lib
Repositories : iOS_specs - xxx @ df1818cfe6977003a501af6456526510ea414d51
               master - https://github.com/CocoaPods/Specs.git @ 560b78e96e5fd193bed06e33dfff76805715b741
               me:arch-ios_specs - xxx @ 7b45db8d71e21b30cbb510c4fa706e38355eaaca
               mobile-specs - xxx @ f1f074e05e399fc1b78c8abc9d3e6621d2dd4afb
```

### Installation Source

```
Executable Path: /Users/xxx/.rvm/gems/ruby-2.3.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
this is a good suggestion, or at least the bug should be fixed. I've hit that before myself.

**Comment by dnkoutso** [comment]
@benasher44 @segiddins do you think the `validation_dir` should  include the pods name and version?

**Comment by segiddins** [comment]
Maybe just the PID?

**Comment by dnkoutso** [comment]
PID would do

**Comment by dnkoutso** [comment]
@segiddins its interesting and maybe not an issue but the linter will stomp contents based on what platform its building for could it also be `Pathname(Dir.tmpdir) + "CocoaPods/Lint/#{Process.pid}" + platform`?

**Comment by benasher44** [comment]
👍 Improvements to make CP safer to use in parallel would be most welcome!

**Comment by dnkoutso** [comment]
Alternatively we can use a timestamp instead of PID.

**Comment by samdmarshall** [comment]
PID is much safer than a timestamp to use; you cannot guarantee unique numbers with that.

**Comment by axl411** [comment]
Yes, multiple CI jobs are very likely to be trigged at the same second, so timestamp is not safe.

**Comment by samdmarshall** [comment]
You should never be running multiple builds on the same machine with Xcode, that is going to cause unpredictability with the build system.

**Comment by axl411** [comment]
@samdmarshall You mean on my CI I should assign only one executor to execute all the jobs which utilizes `xcodebuild` one by one?

**Comment by samdmarshall** [comment]
Correct, you shouldn't have `xcodebuild` run more than one concurrent build on a single machine. You can run into shared resource problems with that.

**Comment by axl411** [comment]
Thanks for pointing that out, I'll keep that in mind.

**Comment by axl411** [comment]
Not sure if this issue has been addressed, but I'll just tell @probot-stale[bot] that the issue is still valid.
