### ISSUE TITLE
Generating Pods project Abort trap: 6

### ISSUE THREAD

**Issue by feepees** [CocoaPods/CocoaPods#6380]
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.5.4)
Installing AliPay (2.1.2)
Installing AliyunOSSiOS (2.6.0)
Installing FMDB (2.6.2)
Installing MBProgressHUD (0.9.2)
Installing Mantle (1.5.8)
Installing Masonry (0.5.3)
Generating Pods project
Abort trap: 6

**Comment by DanToml** [comment]
Please can you file a new issue and fill in the issue template? We need more information to be able to identify this.
