### ISSUE TITLE
pod install works ,but when update my own podspecs and use "pod spec lint", it failed

### ISSUE THREAD

**Issue by cxq1221** [CocoaPods/CocoaPods#6383]
cocoapods 1.1.1
xcode 8.1
I create my Spec repo, and update something
this is the podspecs 
```ruby
Pod::Spec.new do |s|
  s.name         = "AccountModule"
  s.version      = "1.0.0.3"
  s.summary      = "AccountModule."
  s.description  = <<-DESC
                    this is AccountModule
                   DESC

  s.homepage     = "https://coding.net/u/coollang_cxq/p/AccountModule/git"
  s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "littleStrong" => "cxq302@126.com" }
  s.platform     = :ios, "8.0"
  s.source       = { :git => "https://git.coding.net/coollang_cxq/AccountModule.git", :tag => 

 s.version.to_s }
  s.source_files  = "AccountModule/AccountModule/**/*","AccountModule/AccountModule/**/*.{h,m}"
  s.resource  = "AccountModule/AccountModule/**/*.xib"
  s.requires_arc = true


  s.dependency "BaseModule"
  s.dependency "OCBaseModule"
  s.dependency "ACTextView"

end
```

i can do "pod install" in this project and works well
but when i do "pod search OCBaseModule"  or "pod spec lint" in  "OCBaseModule"project, it says "Unable to find a pod with name, author, summary, or description matching `OCBaseModule`"
but actualy , i can find this project in my own Spec repo,

in addition, some of my pod can be searched ,while others can't ,i am so confused that hope to get some help there

**Comment by benasher44** [comment]
Hi @cxq1221! Did you make sure to specify the `--sources` flag when running the `pod spec` commands? This specifies the source/spec repo, in which to search. Make sure to specify both your private spec repo and the CocoaPods master repo (if required).
