### ISSUE TITLE
when i update my framework meet a error

### ISSUE THREAD

**Issue by godL** [CocoaPods/CocoaPods#6384]
StreamKit (1.1.6) - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use --verbose for more information. - NOTE | xcodebuild: Headers/Public/StreamKit/StreamKit.h:14:9: fatal error: 'NSObject+StreamKit.h' file not found
<img width="572" alt="qq20170107-0 2x" src="https://cloud.githubusercontent.com/assets/15048055/21742573/abdf2948-d52c-11e6-8903-e11ffddd9c99.png">

**Comment by dnkoutso** [comment]
Your `s.source_files` does not include the `NSObject+StreamKit.h` file.

Maybe try using `s.source_files = 'StreamKit/**/*.{h,m}` to include subdirectories.

**Comment by dnkoutso** [comment]
And change:

````
#pragma mark- UIViewController
#import "UIViewController/UIImagePickerController+StreamKit.h"
#import "UIViewController/UIPageViewController+StreamKit.h"
```

To 
```
#pragma mark- UIViewController
#import "UIImagePickerController+StreamKit.h"
#import "UIPageViewController+StreamKit.h"
```

That made the podspec successfully build for me. Going to close this issue as its not a CocoaPods issue.
