### ISSUE TITLE
`pod --completion-script` not working anymore

### ISSUE THREAD

**Issue by Kerumen** [CocoaPods/CocoaPods#6391]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod --completion-script`.

## What did you expect to happen?

Output the completion script.

## What happened instead?

Output: 
```
[!] Unknown option: `--completion-script`
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.11.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3685db52afa614bc33fb9771da9d217892b2d2e9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'

target 'commander' do

  pod 'CocoaLumberjack'
  pod 'GoogleMaps'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'AFNetworking'
  pod 'Mixpanel'

end
```

**Comment by orta** [comment]
I think you'll need to ensure you have [the claide-completion gem](https://github.com/CocoaPods/claide-completion) installed, I think we moved it out of CocoaPods back in 2015

**Comment by Kerumen** [comment]
How can I install this gem?

```
$ gem install claide_completion
ERROR:  Could not find a valid gem 'claide_completion' (>= 0) in any repository
```

**Comment by benasher44** [comment]
Whoops. I reopened this thinking this would be a good starter task, but I realize now that what I had in mind probably doesn't make sense. Disregard!
