### ISSUE TITLE
Bridge Active Compilation Conditions from App Project

### ISSUE THREAD

**Issue by dmorrow** [CocoaPods/CocoaPods#6394]
This is a feature request.
I have a Swift pod that uses Active Compilation Conditions to set a property - the build type.

    open class var buildType : BuildType {
        get {
            #if DEBUG
                return .dev
            #endif
            #if BETA
                return .beta
            #endif
            return .prod
        }
    }

This code used to be part of my project, so in build settings, Active Compilation Conditions/Debug build configuration has DEBUG, a custom 'Internal' build configuration has BETA and Release configuration has no value.  

However, because this code is compiled by the Pods project, I also need to set my Active Compilation Conditions settings in the Pods project.  Ideally, the Pods project would pick up the settings from the main app project, or something similar to set in only one place.

**Comment by dmorrow** [comment]
Can this be reopened?  I am currently managing in `post_install` hook, but this is not maintainable. 

In addition, I have to set the  `SWIFT_ACTIVE_COMPILATION_CONDITIONS` on each project.  If I try to set it on the target, the projects don't have `$(inherit)` set, so the target props don't cascade.

    post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            
            if config.name == "Debug"
                config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = "DEBUG"
            elsif config.name == "Internal"
                config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = "BETA"
            end
        end
    end
    end

**Comment by andrejacobs** [comment]
Tumbleweeds blowing past. 

I would love to know how this can be done.

**Comment by amorde** [comment]
The post_install hook is the only way to do this currently, but I will mark this as an enhancement in case anyone would like to propose an API for this

**Comment by dnkoutso** [comment]
Can you not do:
```ruby
s.pod_target_xcconfig = {
      'SWIFT_ACTIVE_COMPILATION_CONDITIONS[config=Debug]' => 'DEBUG,
      'SWIFT_ACTIVE_COMPILATION_CONDITIONS[config=Release]' => 'RELEASE',
}
```

**Comment by amorde** [comment]
This is about consumers bridging their own conditions to the dependencies, not the other way around

**Comment by amorde** [comment]
But yes podspecs can do this themselves. I was thinking this was about projects that have their own conditions which they want to include in the project's dependencies

**Comment by dnkoutso** [comment]
I'd argue that the pod author who is doing this logic should communicate that and configure it in the podspec.

**Comment by amorde** [comment]
👍 that sounds good to me. Shall we close?

**Comment by dnkoutso** [comment]
Yes for now and we can-reopen when/if we continue this discussion here!
