### ISSUE TITLE
'No such module' when archiving with sub-projects

### ISSUE THREAD

**Issue by basvankuijck** [CocoaPods/CocoaPods#6399]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
- `pod install`
- Archive it through Xcode

## What did you expect to happen?
I expected it to create an archive

## What happened instead?
`No such module 'ObjectMapper'`

## CocoaPods Environment

```
workspace 'Workspace'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'Project_abstract' do
   pod 'ObjectMapper', '~> 2.0'

   target 'Project-Target' do
     project 'Project.xcodeproj'

     pod 'Fabric'
     pod 'Crashlytics'
   end

   target 'SDK-Target' do
       project 'SDK-Project/SDK-Project.xcodeproj'
   end

   abstract_target 'Tests' do
       inherit! :search_paths
       pod 'Nimble'
       
       target 'Project-TestTarget' do
           project 'Project.xcodeproj'
       end

       target 'SDK-TestTarget' do
           project 'SDK-Project/SDK-Project.xcodeproj'
       end
   end
end
```

## Project structure

```
Workspace
 |_ Project
 |  |_ SDK-Project
 |  |    |_ SDK-Target
 |  |    |_ SDK-TestTarget
 |  |_ Project-Target
 |  |_ Project-TestTarget
 |_ Pods
```
## More information 

`SDK-Project` contains 'File.swift' which has `import ObjectMapper` in the top

When I run it in debug modus the app builds perfectly and runs on my iPhone, but when I want to create an archive (either through Xcode or with fastlane) this swift compiler error occurs.

What I've tried:
 - `pod deintegrate` / `pod install`
 - clearing derived data 
I have done `pod deintegrate` and `pod install`.
Clearing derived data

**Comment by benasher44** [comment]
Hi @basvankuijck! Can you post a project that reproduces the issue or maybe fork this one and reproduce is there: https://github.com/benasher44/CocoaPodsLibExample ?

**Comment by basvankuijck** [comment]
@benasher44: Thanks for your response.
I got it to archive after all.
It looked like the `SDK-Project` was missing a build configuration `Adhoc`. Which `Project` used to archive the project for a specific build scheme. I think the compiler was looking for modules in the `$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)` path

**Comment by benasher44** [comment]
@basvankuijck awesome! Glad you got it figured out!

**Comment by roshansrashtasoft** [comment]
How to resolved this issue ? 

Xcode Version 16.2

![Image](https://github.com/user-attachments/assets/2d46d505-0121-497a-be78-8539a8de0599)
