### ISSUE TITLE
`lint`-ing lib including CoreData CodeGen leads to `file not found` error

### ISSUE THREAD

**Issue by CharlesThierry** [CocoaPods/CocoaPods#6403]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I tried to lint a lib (created using the `pod create lib` template) that uses AutoGenerated CoreData managed object categories.

## What did you expect to happen?
To be amazed by my lib being lint'd without an issue.

## What happened instead?
Was stricken down by the compiler informing me that autogenerated code was apparently not generated 
(`DRTestEntity+CoreDataProperties.m: No such file or directory` using the exemple below).  
It could be related to #6259 

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1212)
       Xcode : 8.2 (8C38)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/charles/.rvm/rubies/ruby-2.3.0/lib
               master - https://github.com/CocoaPods/Specs.git @ a4160c198470400b7e7fd469a636d975b9d2a2ca
```

### Installation Source

```
Executable Path: /Users/charles/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
Problem reproduced with a minimal example code that can be found here: [https://github.com/DeRunco/DRCoreDataTest](https://github.com/DeRunco/DRCoreDataTest)
```
git clone git@github.com:DeRunco/DRCoreDataTest.git
```

**Comment by benasher44** [comment]
Yep! This is a dup. Thanks for filing though! Your demo project is really useful, and I'll be using it as I work on this one. Cheers!
