### ISSUE TITLE
Swift compiler issue

### ISSUE THREAD

**Issue by bolismauro** [CocoaPods/CocoaPods#6405]
I've encountered this issue in my code
http://stackoverflow.com/questions/35673290/extension-of-a-nested-type-in-swift/36577441#36577441

I heavily use nested structures and I never noticed this issue because, probably for pure luck, the files are in the correct order in the project.

I'm now trying to release this library with cocoapods, but of course the code doesn't compile.
Is there a way with cocoapods to define the order with which the files are added to the compilation step in the generated project?

Other workarounds I can think to are:
- rename the files (cocoapods orders them in alphabetical order, right?)
- remove all the nested structures (it would be a huge refactor and I'd prefer to find another way)

I've searched related issue but I didn't find anything

EDIT
Swift bug
https://bugs.swift.org/browse/SR-631

**Comment by orta** [comment]
I'm afraid this isn't a feature CocoaPods supports, or probably will ever support. 

In theory you could recommend adding a quick `post_install` script to re-order the files in the phase, but it's a swift bug  that will eventually be fixed that's not worth the building and maintaining a feature like that for years to come.

**Comment by lucaquerella** [comment]
I've an idea on how to solve this with a cocoapods-plugin. I have a question tho: is it possibile to pass information from the podspec (not Podfile)  to a plugin, or to say it better: is it possibile to add metadata to podspec that is readable from a plugin?

**Comment by orta** [comment]
Hrm, I don't know if anyone is doing it but I would imagine that if you set values to the pod spec's attribute hash the podspec they would get passed through trunk as JSON (I think) - without trying I can't say

```ruby
p = Pod::Spec.new do |s|
  ...
end
p.attributes_hash["thing"] = "OK"
p
```

**Comment by orta** [comment]
But otherwise a plugin would be able to handle the sort of thing you want to do with the post hook.

**Comment by bolismauro** [comment]
I guess @lucaquerella is trying to build a "generic" plugin and not force people to update it every time a new version of the library is released

**Comment by lucaquerella** [comment]
Yep I wanted to specify a weight for some specific source file in the podspec and let the plugin re-order the source files using that info.
I'll try that, thanks!

**Comment by lucaquerella** [comment]
beside I think it could take some time before they fix this problem on Swift :/ so I would like to find a proper solution to it asap.

**Comment by bolismauro** [comment]
@orta by the way your suggestion of passing things through the json works
