### ISSUE TITLE
Podspec validation failed due to a segmentation fault 😞

### ISSUE THREAD

**Issue by Mozharovsky** [CocoaPods/CocoaPods#6413]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod trunk push ATHKit.podspec`

## What did you expect to happen?

Push the `ATHKit` pod to the trunk correctly. 

## What happened instead?

```shell
<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /var/folders/ts/9dg1ktr91zv8k63snbxf5kxh0000gp/T/CocoaPods/Lint/Pods/ATHKit/Source/ATHImagePickerController.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
 -> ATHKit (0.0.9)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  <unknown>:0: error: unable to execute command: Segmentation fault: 11
    - NOTE  | [iOS] xcodebuild:  <unknown>:0: error: compile command failed due to signal (use -v to see invocation)
```

### Stack

```
   CocoaPods : 1.2.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8e6bcfd6541c3832491101e078ea5a14212a26d6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Additional info

Validation has been successfully passed before (e.g. v0.0.6) but since v0.0.7 it started to fail... Since it complains about `ATHImagePickerController.swift` the issue is probably there. Either way, in v0.0.7 (and since then) I have added an internal protocol (`StatusBarUpdatable`) with a constrained extension providing an implementation of the declared method. Besides the protocol, I have added a struct (`ATHImagePickerStatusBarConfig`) that is used as a type for a static variable in `ATHImagePickerController`. I do use Swift 3, Xcode 8.2.1 and `ATHKit` has a `.swift-version` file.

**Comment by dnkoutso** [comment]
Not certain this is a CocoaPods issue, could be a `swiftc` issue. CocoaPods during lint just invokes `xcodebuild`.

**Comment by Mozharovsky** [comment]
I replaced the v0.0.6 pod's source files with the current ones and it worked well, which means all compiles successfully.

**Comment by Mozharovsky** [comment]
Okay, I found out what was wrong. 

I added a struct to contain properties for status bar setup. It looked like: 

```swift
public struct ATHImagePickerAssets {
    public let switchCameraIcon: UIImage?
    public let flashOnImage: UIImage?
    public let flashOffImage: UIImage?
    public let flashAutoImage: UIImage?
    
    public init(switchCameraIcon: UIImage? = nil,
                flashOnImage: UIImage? = nil,
                flashOffImage: UIImage? = nil,
                flashAutoImage: UIImage? = nil) {
        self.switchCameraIcon = switchCameraIcon
        self.flashOnImage = flashOnImage
        self.flashOffImage = flashOffImage
        self.flashAutoImage = flashAutoImage
    }
}
```

Then I added a static variable to the `ATHImagePickerController` class so user changes can be saved there. It looked like this: 

```swift
open class ATHImagePickerController: UINavigationController, ATHImagePickerCommiterDelegate {
// ...
    open static var statusBarConfig = ATHImagePickerStatusBarConfig() // *
// ...
}
```

When I commented (*) line of code the validation passed successfully. 

I'm not sure if this behavior is expected. I was able to compile the source files and run the demo project (by replacing the stable pod source files with v0.0.9 ones) which means the compiler can handle this without issues. So I don't know if it's a lint flaw or not but something obviously doesn't work as expected. 

You can close this issue since it's solved.  :]

**Comment by dnkoutso** [comment]
Thank you for providing an explanation. You should be able to reproduce sort of the segfault without lint by running xcodebuild your self or through Xcode.

Closing.
