### ISSUE TITLE
Unable to find a specification for pod, if Specs are in branch.

### ISSUE THREAD

**Issue by YauheniYarotski** [CocoaPods/CocoaPods#6414]
Hi there, thank you very much for your product! All here is about private pod.
The main idea, is to put Specs to the branch. 
Problem:
If I put specs to master - it works, If I show the path to the pod, it works, 
but if I MOVE specs from master to other branch, I got: Unable to find a specification for pod. 
What I did:
- created repo with command:
```
pod repo add RepoName git@github.com:somo-name/some-Framework.git specs
 cd ~/.cocoapods/repos/RepoName/
pod repo lint .
```

```
Linting spec repo `RepoName`
.
Analyzed 1 podspecs files.
All the specs passed validation.

- In podfile source is shwon in a such way:
source = { :git => 'https://github.com/some-name/some-Framework.git', :branch => 'specs'}
- But I got error:

[!] Unable to find a specification for `RepoName`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:57:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:723:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:721:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
You need to pass the available repo sources during the `lint` command.

For example :

`pod repo lint --sources=<your_source>,master`

To find all available source repos use:

`pod repo list`

**Comment by dnkoutso** [comment]
@YauheniYarotski I am mistaken, this is about the `pod **spec** lint` command, my bad.

**Comment by benasher44** [comment]
Hi @YauheniYarotski! Thank for the report! Can you please show your Podfile and podspec? Thanks!

**Comment by YauheniYarotski** [comment]
Here is podfile:
source = { :git => 'https://github.com/CocoaPods/Specs.git', :branch => 'master'}
source = { :git => 'https://github.com/some-name/some-Framework.git', :branch => 'specs'}

use_frameworks!

def shared_pods
#    pod 'Fabric'
#    pod 'Crashlytics'
    pod 'SomeFramework'
end

target 'SomeTarger' do
	shared_pods
end

Already see my error: I reset source variable. But I got (Unable to find a specification for `SomeFramework`) event if I do this:
source = { :git => 'https://github.com/some-name/some-Framework.git', :branch => 'specs'}

use_frameworks!

def shared_pods
#    pod 'Fabric'
#    pod 'Crashlytics'
    pod 'SomeFramework'
end

target 'SomeTarger' do
	shared_pods
end

podspec:
#
# Be sure to run `pod lib lint SomeFramework.podspec' to ensure this is a
# valid spec before submitting.
#
# Any lines starting with a # are optional, but their use is encouraged
# To learn more about a Podspec see http://guides.cocoapods.org/syntax/podspec.html
#

Pod::Spec.new do |s|
  s.name             = 'SomeFramework'
  s.version          = '2.1.0'
  s.summary          = SomeFramework.'

# This description is used to generate tags and improve search results.
#   * Think: What does it do? Why did you write it? What is the focus?
#   * Try to keep it short, snappy and to the point.
#   * Write the description between the DESC delimiters below.
#   * Finally, don't worry about the indent, CocoaPods strips it!

  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC

  s.homepage         = 'https://github.com/some-name/some-Framework'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Yauheni Yarotski' => 'yauheni_yarotski@me.com' }
  s.source           = { :git => 'https://github.com/some-name/some-Framework.git', :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.ios.deployment_target = '8.0'

  s.source_files = 'SomeFramework/Classes/**/*'
  
  # s.resource_bundles = {
  #   'SomeFramework' => ['SomeFramework/Assets/*.png']
  # }

    s.public_header_files = 'SomeFramework/Classes/**/*.h'
    s.frameworks = 'UIKit'
    s.dependency 'Reachability', '~> 3.2'
end

I will do project example for now, will be added.

**Comment by YauheniYarotski** [comment]
So, here is framework:
https://github.com/YauheniYarotski/YYFramework
In branch specs is specs repo.
Here is example project with pod file:
https://github.com/YauheniYarotski/ExampleWithYYFramewoek

Result: Unable to find a specification for `ExampleWithYYFramewoek
Problem: I can't show in podfile that specs are here: https://github.com/YauheniYarotski/YYFramework/tree/specs
