### ISSUE TITLE
Cannot access xcassets from private Pod, even though they display in storyboard

### ISSUE THREAD

**Issue by da-na** [CocoaPods/CocoaPods#6417]
Hi folks!
I have a similar issue to #4897, and the CURRENT_PROJECT_VERSION in my private pod is set. According to the guideline I should discuss my issue here, so here's the info of my project.

Please let me know if I'm missing something obvious here. I find it astounding, that I can access the image from my private Pod through the storyboard in the Example, but then later on it doesn't show in the app. 

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I've created a private Pod, to hold MyAppUI components, like image assets, custom buttons etc. Then in Example for MyAppUI I created a storyboard with a button and icon as an example.

## What did you expect to happen?

I expected the image in a button to be loaded after running my app - since I had no problem adding it in a storyboard.

## What happened instead?

This is what I have in storyboard:
![screen shot 2017-01-16 at 12 01 20 pm](https://cloud.githubusercontent.com/assets/9628216/21992215/96d9f9a2-dbe3-11e6-9a86-609ebdfa3f7b.png)

And then after running the app I can see the button, but without the image. The image is not displayed, and I can see an error in the console:

2017-01-16 11:39:50.903 MyAppUI_Example[2887:73017] Could not load the "ic_account_circle_18pt_3x.png" image referenced from a nib in the bundle with identifier "com.mycompany.demo.MyAppUI-Example"

This bundle identifier is wrong (I think...) Image is bundled in org.cocoapods.MyAppUI

I have this code in MyAppUI.podspec
```
Pod::Spec.new do |s|
  s.name             = 'MyAppUI'
  s.version          = '0.1.0'
  s.summary          = 'CocoaPod for MyAppUI elements.'

 (...)

  s.ios.deployment_target = '10.2'
  s.source_files = 'MyAppUI/Classes/**/*.{swift}'
  s.resource_bundles = {
   'MyAppUI' => ['MyAppUI/Assets/**/*.{imageset}']
  }

```
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.6.2
Ruby lib dir : /Applications/CocoaPods.app/Contents/Resources/bundle/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d4b534ca6a3d1982e269cae9e7c0fa6fc1a1529d
```

### Installation Source

```
Executable Path: /Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod
```

### Plugins

```
cocoapods-check           : 1.0.0
cocoapods-deintegrate     : 1.0.1
cocoapods-plugins         : 1.0.0
cocoapods-plugins-install : 0.0.1
cocoapods-search          : 1.0.0
cocoapods-stats           : 1.0.0
cocoapods-trunk           : 1.1.2
cocoapods-try             : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'MyAppUI_Example' do
  pod 'MyAppUI', :path => '../'

  target MyAppUI_Tests' do
    inherit! :search_paths
    
  end
end
```

**Comment by da-na** [comment]
After looking closer into it, this seems like a storyboard issue rather than cocoapods issue. So I filed a feature request / bug report here: https://forums.developer.apple.com/message/206903#206903 
I'll update this thread whenever / if Apple replies :) But I guess this can be closed for now?

**Comment by benasher44** [comment]
Hm. I can't see that message, but if you feel like this is an Apple issue and not a CocoaPods issues, I think closing it would be good. It'll might save someone time looking into it. Feel free to re-open though if you change your mind! :)

**Comment by gjleeder** [comment]
FWIW, I also saw this problem. A comment in this thread pointed me towards the Bundle identifier. Mine too was prefixed with org.cocoapods.<FrameworkName> instead of <company>.<frameworkName> 

A workaround for me was navigating to the Pods/<FrameworkName>/Supporting Files/info.plist and making the Bundle identifier <company>.<frameworkName>. This is a real pain because it gets overwritten with every pod install! Seems like it is driven from xcconfig and the change was intentional in cocoapods. Not sure how you workaround this correctly

**Comment by eytanbiala** [comment]
Was there any update here? I am facing the same issue now.

**Comment by gjleeder** [comment]
FWIW: I eventually resolved this using spec.resources instead or spec.bundle_resources in the podspec. I'm no expert on this but if you have your assets specified using bundle_resources you can give it a try.
