### ISSUE TITLE
Pods integration issue

### ISSUE THREAD

**Issue by rohitnagori** [CocoaPods/CocoaPods#6419]
Hi Steve,

I have successfully integrated pods. But when I compile, It give me linker error.

`
ld: library not found for -lAFNetworking

linker command failed with exit code 1 (use -v to see invocation)`

Can you suggest me workaround for this.

Thanks.

**Comment by benasher44** [comment]
Hi @rohitnagori! Thanks for filing an issue! Unfortunately, there's not enough info here for us to help you debug, so I'm going to close this out. When you're ready, please file a new issue and fully fill out the issue template, and then we'd be happy to help you out! Have a great day!
