### ISSUE TITLE
Target to Multi-target throws "Shell Script Invocation Error"

### ISSUE THREAD

**Issue by jcmartinac** [CocoaPods/CocoaPods#6421]
# Report

## What did you do?

I have created four targets from my original one. All works well until I have updated cocoapods to: 
pod --version
1.1.1

(Before I have 1.0.1 version)
Once updated -> Run `pod install`

## What did you expect to happen?

All my dependencies updated and go on.

## What happened instead?

For every target same build error, "Shell Script Invocation Error" with log:
/Users/cmacera/Library/Developer/Xcode/DerivedData/Archaio-aqooorebitjhmfcoyoawfgkwysdz/Build/Intermediates/Archaio.build/Debug-iphonesimulator/Archaio-PRO.build/Script-2A7069DFCDD66C99A4315FEC.sh: line 2: /Users/cmacera/Desktop/Archaio4iOS/Pods/Target Support Files/Pods-Archaio/Pods-Archaio-frameworks.sh: No such file or directory

while generated path for each target would be:
.../Pods/Target Support Files/Pods-Archaio-Archaio-DEV/Pods-Archaio-Archaio-DEV-frameworks.sh

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1b4025dbc23a0d2e87d63e0eddf6b463f24af7d0
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.1'

abstract_target 'Archaio' do
    pod 'AFNetworking', '~> 3.0'
    pod 'Typhoon', '~> 3.5.1'
    pod 'JSONModel'
    pod 'Realm'
    pod 'Crashlytics'
    pod 'OHHTTPStubs'
    pod 'EXTView'
    pod 'ActionSheetPicker-3.0'

    target 'Archaio-PRO'
    target 'Archaio-QA'
    target 'Archaio-DEV'
    target 'Archaio-AppStore'

end

target 'ArchaioTests' do
    
    pod 'Typhoon', '~> 3.5.1'
    pod 'OCMock'
    pod 'OHHTTPStubs'
    pod 'Realm'
    
end

target 'ArchaioIntegrationTests' do
    
    pod 'Typhoon', '~> 3.5.1'
    pod 'OCMock'
    pod 'OHHTTPStubs'
    pod 'Realm'
    
end
```

Thanks for helping

**Comment by dnkoutso** [comment]
Hm, just a guess can you `rm -rf Pods/` folder and `pod install` again and try again?

**Comment by jcmartinac** [comment]
got same error... thanks anyway

**Comment by benasher44** [comment]
Hi! Can you please show the contents of your `[CP]`-marked build phases? Thanks!

**Comment by jcmartinac** [comment]
Thanks for helping! @benasher44, your comment make me realize that in target's build phases, in each "LinkBinaryWithLibraries", was linking to previous target Pod framework. To solve I have deleted everything related to Pods in Build Phases (frameworks inside Link Binary With Libraries, Embed Pods Frameworks and Copy Pods Resources Scripts), and run pod install again.

**Comment by benasher44** [comment]
Awesome! Glad you got it worked out!

**Comment by SalmanAhmedDev** [comment]
I am also facing this type of issue Please help me!

PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/salmanahmed/Library/Developer/Xcode/DerivedData/TestTwitterShare-guqldnjxhergzfcwnorxzqgptzbq/Build/Intermediates.noindex/TestTwitterShare.build/Debug-iphoneos/TestTwitterShare.build/Script-F570C2C17597C52D678D5601.sh
    cd /Users/salmanahmed/Projects/Xcode-Project/Local-IOS-Apps/TestTwitterShare
    /bin/sh -c /Users/salmanahmed/Library/Developer/Xcode/DerivedData/TestTwitterShare-guqldnjxhergzfcwnorxzqgptzbq/Build/Intermediates.noindex/TestTwitterShare.build/Debug-iphoneos/TestTwitterShare.build/Script-F570C2C17597C52D678D5601.sh

mkdir -p /Users/salmanahmed/Library/Developer/Xcode/DerivedData/TestTwitterShare-guqldnjxhergzfcwnorxzqgptzbq/Build/Products/Debug-iphoneos/TestTwitterShare.app/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/salmanahmed/Projects/Xcode-Project/Local-IOS-Apps/TestTwitterShare/Pods/TwitterCore/iOS/TwitterCore.framework" "/Users/salmanahmed/Library/Developer/Xcode/DerivedData/TestTwitterShare-guqldnjxhergzfcwnorxzqgptzbq/Build/Products/Debug-iphoneos/TestTwitterShare.app/Frameworks"
building file list ... done
TwitterCore.framework/
TwitterCore.framework/Info.plist
TwitterCore.framework/TwitterCore

sent 4867474 bytes  received 70 bytes  9735088.00 bytes/sec
total size is 4866642  speedup is 1.00
Stripped /Users/salmanahmed/Library/Developer/Xcode/DerivedData/TestTwitterShare-guqldnjxhergzfcwnorxzqgptzbq/Build/Products/Debug-iphoneos/TestTwitterShare.app/Frameworks/TwitterCore.framework/TwitterCore of architectures: i386 x86_64
Code Signing /Users/salmanahmed/Library/Developer/Xcode/DerivedData/TestTwitterShare-guqldnjxhergzfcwnorxzqgptzbq/Build/Products/Debug-iphoneos/TestTwitterShare.app/Frameworks/TwitterCore.framework with Identity iPhone Developer: Uzair Gadit (D292DBG674)
/usr/bin/codesign --force --sign 8647BF2D53AF52FBD672B79F8830325F634B360A  --preserve-metadata=identifier,entitlements '/Users/salmanahmed/Library/Developer/Xcode/DerivedData/TestTwitterShare-guqldnjxhergzfcwnorxzqgptzbq/Build/Products/Debug-iphoneos/TestTwitterShare.app/Frameworks/TwitterCore.framework'
/Users/salmanahmed/Library/Developer/Xcode/DerivedData/TestTwitterShare-guqldnjxhergzfcwnorxzqgptzbq/Build/Products/Debug-iphoneos/TestTwitterShare.app/Frameworks/TwitterCore.framework: unknown error -1=ffffffffffffffff
Command /bin/sh failed with exit code 1

**Comment by SalmanAhmedDev** [comment]
i have just update the pod version : 

> sudo gem install cocoapods

 work for me.
