### ISSUE TITLE
git clone without depth=1 when clone from branch

### ISSUE THREAD

**Issue by intspt** [CocoaPods/CocoaPods#6423]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod update --verbose --no-repo-update

## What did you expect to happen?

update all pod dependencies correctly.

## What happened instead?

[!] Error installing eLongFlight
[!] /usr/bin/git clone http://code.corp.elong.com/ios/elongflight.git /var/folders/0k/9w0xj_jx24nfd8sn0fjxlx8r0000gn/T/d20170119-5431-1tw74so --template=

Cloning into '/var/folders/0k/9w0xj_jx24nfd8sn0fjxlx8r0000gn/T/d20170119-5431-1tw74so'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

### Stack

```
   CocoaPods : 1.2.0.rc.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.11.6 (15G1212)
       Xcode : 8.2 (8C38)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.0/lib
Repositories : elongspecs - http://code.corp.elong.com/elongspecs/elongspecs.git @ ce048bd551a94cf6729dc96429fbb5c9e749fc1b
               master - https://github.com/CocoaPods/Specs.git @ da6af73fbc22ad64cf1188f59608ad7aec82fb75
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Podfile

pod 'eLongFlight', :git => 'http://code.corp.elong.com/ios/elongflight.git', :branch =>'1.20.0''

git clone failed because the because the parameter depth=1 is missing(.git dir is too large)

**Comment by intspt** [comment]
anyone?

**Comment by simson2010** [comment]
I also encountered this issue, finding that latest pre-release version 1.2.0 beta was not include the --depth 1 parameter in the git clone command.

**Comment by intspt** [comment]
@simson2010  only if you specific the branch, tag param is working(--depth=1)

**Comment by simson2010** [comment]
@intspt  we always using :git => xxx , :branch => 'xxx' for each pod lib, we're using a private GitHub to hold the libs. 

I found the "git.rb" was added a new function for pre-processing the download options.

`def self.preprocess_options(options)
24	        return options unless options[:branch]
25	
26	        command = ['ls-remote',
27	                   options[:git],
28	                   options[:branch]]
8 months ago @champo Added first batch of test coverage	
29	        output = Git.execute_command('git', command)
8 months ago @champo Allow download strategies to preprocess download options	
30	        match = /^([a-z0-9]*)\t.*/.match(output)
31	
32	        return options if match.nil?
33	
34	        options[:commit] = match[1]
35	        options.delete(:branch)
36	
37	        options
38	      end
`

seems the first line "return options unless options[:branch]" would not return the options even if I have the :branch setting in Podfile. It still try ls-remote and delete :branch setting from the options and return the :commit inside options. then the clone_argument() function would bypass the --depth 1 parameter always. 

did u think so?

**Comment by simson2010** [comment]
@intspt but how to install the 1.2.0 rc version? I only can install the beta version from gem install --pre

**Comment by intspt** [comment]
@simson2010 sorry I don't know

**Comment by intspt** [comment]
still exists

**Comment by intspt** [comment]
need to be fixed

**Comment by orta** [comment]
You're welcome to submit a pull request to fix this issue, as it looks like it's hard to a core dev to replicate without having a git server that acts in this way.

**Comment by intspt** [comment]
@orta 
sorry I can't write Ruby
And this bug has nothing to do with private repository
such as

Podfile
`install! 'cocoapods', :deterministic_uuids => false
platform :ios, '8.0'

target 'tmp' do
    pod 'AFNetworking', :git => 'https://github.com/AFNetworking/AFNetworking.git', :branch => '2974'
end`

Output
`[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.12_1/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
Update all pods
  Preparing
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-tmp`: (``)

Finding Podfile changes
  - AFNetworking

Fetching external sources
-> Pre-downloading: `AFNetworking` from `https://github.com/AFNetworking/AFNetworking.git`, branch `2974`
  $ /usr/local/bin/git ls-remote https://github.com/AFNetworking/AFNetworking.git 2974
  [proxychains] DLL init: proxychains-ng 4.12
  [proxychains] DLL init: proxychains-ng 4.12
  [proxychains] Strict chain  ...  127.0.0.1:1080  ...  github.com:443  ...  OK
  d284c551809ea911e90f30f872d1911b5a41cc04	refs/heads/2974
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/AFNetworking/AFNetworking.git /var/folders/0k/9w0xj_jx24nfd8sn0fjxlx8r0000gn/T/d20170612-8899-c64mth
     --template=
     [proxychains] DLL init: proxychains-ng 4.12
     Cloning into '/var/folders/0k/9w0xj_jx24nfd8sn0fjxlx8r0000gn/T/d20170612-8899-c64mth'...
     [proxychains] DLL init: proxychains-ng 4.12
     [proxychains] Strict chain  ...  127.0.0.1:1080  ...  github.com:443  ...  OK
     [proxychains] DLL init: proxychains-ng 4.12
     [proxychains] DLL init: proxychains-ng 4.12
     [proxychains] DLL init: proxychains-ng 4.12
   $ /usr/local/bin/git -C /var/folders/0k/9w0xj_jx24nfd8sn0fjxlx8r0000gn/T/d20170612-8899-c64mth checkout --quiet d284c551809ea911e90f30f872d1911b5a41cc04
   [proxychains] DLL init: proxychains-ng 4.12
  > Copying AFNetworking from `/Users/spt/Library/Caches/CocoaPods/Pods/External/AFNetworking/a89537f30f70e582e6915e54db66302b` to `Pods/AFNetworking`

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  M AFNetworking

Downloading dependencies

-> Installing AFNetworking 3.0.0-beta.1 (was 3.0.0-beta.1)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `AFNetworking` iOS 7.0
    - Installing target `Pods-tmp` iOS 8.0
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-tmp` (`tmp.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from `/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb`
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12
[proxychains] DLL init: proxychains-ng 4.12

Sending stats
      - AFNetworking, 3.0.0-beta.1

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.`

**Comment by zw1924** [comment]
what happend with v1.9.1。why dismiss depth=1

**Comment by Creolophus** [comment]
Any update for this issue?
