### ISSUE TITLE
Can't update repo for a month now. Nothing worked to solve this

### ISSUE THREAD

**Issue by zaxy78** [CocoaPods/CocoaPods#6425]
pod repo update --verbose
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: Not a git repository (or any of the parent directories): .git

Updating spec repo `master`
  $ /usr/bin/git -C /Users/asachs/.cocoapods/repos/master pull --ff-only
  From https://github.com/CocoaPods/Specs
     25d7716..ca54d0a  master     -> origin/master
  Updating 3d2f644..ca54d0a
  fatal: Unable to create '/Users/asachs/.cocoapods/repos/master/.git/index.lock': File exists.

  Another git process seems to be running in this repository, e.g.
  an editor opened by 'git commit'. Please make sure all processes
  are terminated then try again. If it still fails, a git process
  may have crashed in this repository earlier:
  remove the file manually to continue.
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:110:in `rescue in update_git_repo'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:106:in `update_git_repo'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:124:in `update_git_repo'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source.rb:334:in `update'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-core-1.1.1/lib/cocoapods-core/master_source.rb:15:in `update'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:88:in `block (2 levels) in update'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:87:in `block in update'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `each'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `update'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.1.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.1.1/libexec/bin/pod:23:in `<main>'
 ✘ ⚙ asachs@asachs-mac02  ~/Documents/Projects/ShlomosApp   master  pod repo update
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: Not a git repository (or any of the parent directories): .git
Updating spec repo `master`
  $ /usr/bin/git -C /Users/asachs/.cocoapods/repos/master pull --ff-only
  From https://github.com/CocoaPods/Specs
     ca54d0a..02cd8d2  master     -> origin/master
  Updating ca54d0a..02cd8d2
  Fast-forward
   .../0.0.1/XYVolumeHandler.podspec.json             | 22 ++++++++++++++++++++++
   1 file changed, 22 insertions(+)
   create mode 100644 Specs/2/1/b/XYVolumeHandler/0.0.1/XYVolumeHandler.podspec.json

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/Cellar/cocoapods/1.1.1/libexec/bin/pod repo update
```

### Report

* What did you do?
Trying to setup/install/update ANY pod file or project I have. 
* What did you expect to happen?
repo update success
* What happened instead?
repo update failed

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.3
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 02cd8d263abf1d4ec8b68352e83ddf9f536d3c22
               master-bak - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               master-bak2 -  @ fatal: Not a git repository (or any of the parent directories): .git
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShlomosApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShlomosApp

end
```

### Error

```
ArgumentError - comparison of Pod::Version with Gem::Version failed
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:132:in `>'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:132:in `verify_compatibility!'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:90:in `block (2 levels) in update'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:87:in `block in update'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `each'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/sources_manager.rb:86:in `update'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/Cellar/cocoapods/1.1.1/libexec/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.1.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.1.1/libexec/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment]
Hi @zaxy78! Thanks for the report! I'm not sure what state your specs repo is in. I'd recommend just running `rm -rf ~/.cocoapods/repos/master` and then `pod setup`. This removes the master specs repo from your machine, and then the 2nd command re-clones it. Mind giving that a try? Thanks!

**Comment by benasher44** [comment]
Just a heads up that the comment above has been updated. Please make sure to review it before verifying the fix/workaround. Thanks!

**Comment by benasher44** [comment]
I'm going to close this. It's been awhile since there has been any activity on this issue. If you're still experiencing this, please file a new issue, and we'd be happy to help. Thanks, and have a great day!

**Comment by gazedash** [comment]
@benasher44 it didn't help, same issue
