### ISSUE TITLE
File not found when running `pod lib lint`

### ISSUE THREAD

**Issue by dshahidehpour** [CocoaPods/CocoaPods#6431]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
`pod lib lint`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
For the lint to finish successfully.

## What happened instead?

ℹ Please replace this with of what happened instead.  
I was given the following error: 
```
 -> YogaKit (1.0.0)
    - ERROR | [YogaKit/Core] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [YogaKit/Core] xcodebuild:  /Users/dust/yoga/YogaKit/YGLayout.h:11:9: fatal error: 'yoga/YGEnums.h' file not found

[!] YogaKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
```

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.2.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.8.0-rc2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1a60cf51865351bce6d0d4fe8d4bce4982b60769
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

https://github.com/dshahidehpour/yoga/tree/cocoapods4

Here's the [podspec](https://github.com/dshahidehpour/yoga/blob/cocoapods4/YogaKit.podspec)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
