### ISSUE TITLE
aubio is licensed under the GNU/GPL

### ISSUE THREAD

**Issue by piem** [CocoaPods/CocoaPods#6439]
hi there,

aubio license is not "type: copyright". nor it is "all rights reserved".

aubio is licensed under the GNU/GPL. Please fix.

best, Paul

**Comment by orta** [comment]
Hey, I think you might need to take this up either with the owner of the library, or the podspec owner. We don't handle the semantics for individual libraries using CocoaPods.

**Comment by piem** [comment]
Great, could you tell me how I can do that? I'm the copyright owner. Thank you for your help.

**Comment by orta** [comment]
Looks like these are the people you want to speak to:

```sh
$  pod trunk info aubio-iOS

aubio-iOS
    - Versions:
      - 0.4.2 (2016-07-27 07:09:55 UTC)
    - Owners:
      - Vladimir Lyukov <v.lyukov@gmail.com>

$  pod trunk info aubio-iOS-SDK

aubio-iOS-SDK
    - Versions:
      - 0.4.1 (2014-07-27 02:38:13 UTC)
    - Owners:
      - Khoa Nguyen <khoa.nguyen@notabasement.com>
```

**Comment by piem** [comment]
ok, thanks @orta, bye

**Comment by piem** [comment]
hi @tkhoa87 and @glyuck, please check your mail. thanks, piem

**Comment by tkhoa87** [comment]
Corrected ;)

**Comment by piem** [comment]
awesome, thank you @tkhoa87 ! :)
