### ISSUE TITLE
Unable to install development ObjC-Only pod; getting Swift-related error

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/CocoaPods#6441]
I include a simple demo app along with my source, and include a step in my build that installs the pod from the parent directory and validates everything's working right. Since updating to Xcode 8, this isn't working. The demo app is Swift, but my pod is still 100% Objective-C. I'm puzzled as to why I'm getting a Swift-related error here. I've tried all of the suggestions in Issue #5864 to try to resolve it, and none worked. My `SWIFT_VERSION` in the Demo project is `Unspecified`, but even changing it to `NO` doesn't help.

# Report

## What did you do?

1. Change into the `UnzipKitDemo` directory
2. Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

I get this error:

```
[!] The `UnzipKit` pod failed to validate due to 1 error.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run: 
    `echo "2.3" > .swift-version`:
    - ERROR | version: A version is required.
```

### Stack

```
   CocoaPods : 1.2.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 102a29a180d22487130b9547ba96444b87e70669
```

### Installation Source

```
Executable Path: /Users/Dov/.gem/ruby/2.0.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

`master` branch of UnzipKit (tip revision at the moment, `ebba26732ef219d803b55092cbe3f6287feed48a`)

https://github.com/abbeycode/UnzipKit

**Comment by dnkoutso** [comment]
Thats not the problem. The first error says that your podspec version is missing, or at least it was for me.

Your podspec version is set to `s.version = ENV["TRAVIS_TAG"]`.

When I set that to `"1.0.0"` for example and ran `lib lint` it worked.

```
** BUILD SUCCEEDED **

 -> UnzipKit (1.0.0)

Pods workspace available at `/var/folders/40/mxlx0vqn29vcg5g3vl7n5w7000015m/T/CocoaPods/Lint/App.xcworkspace` for inspection.

UnzipKit passed validation.
```

**Comment by jugutier** [comment]
@dnkoutso he was mislead about the same thing I did (#6428). Would it make sense to reorder that warning message  below the breaking one? The one that actually prevents the spec lint? Just point me in the right direction and I'll do it.

**Comment by abbeycode** [comment]
@dnkoutso Thanks, I didn't realize that my podspec using an environment variable would cause a `pod install` to fail. I added a section of script that sets the environment variable if it isn't already.

@jugutier I agree that the error message had me barking up the entirely wrong tree.

I'm going to close this issue though, since I'm all set.

**Comment by HusamAamer** [comment]
**FIXED** : I've just added a summary which was blank string `s.summary = ''`.
