### ISSUE TITLE
Feature discussion: Easier to make your cocoa app more 12 factor

### ISSUE THREAD

**Issue by vongohren** [CocoaPods/CocoaPods#6448]
[ 🌟 ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What I want to do?

Im trying to create a nice build setup for my ios version of a react native cocoa pods project.
What i'm basically is trying to do is to abstract everything that has to do with Xcode and try to keep it as close to the terminal as possible. By this, i have created a Pod, that has its own run script, which is placed before compile time. This script picks up the envfile from env variables, reads the file, replaces a config.json file that has been attached as resources from the pod install moment. Then my swift code will read this file and make it available in native and in react native code.

I got pretty much every step to work, but there is one thing im not super happy with, and that is that I have to ask the users of my pod to add this to their podfile.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name.include? 'RNConfig'
      phase = target.new_shell_script_build_phase("Build env file")
      phase.shell_script = "cd .. && cd .. && ./node_modules/.bin/build-ios-env"
      target.build_phases.move_from(4,0)
    end
  end
end
```
This is not completly isolated, I wish the pod itself could have a way to add its own run scripts. If there is a plugin, or a reason for this feature to be turned down, let me know.

Two ways for me to be happy would be(preferable option 2):

1. A way to point to a ruby script in the post installer loop, passing in the installer object, so I atleast could hide some of this code.
2. A way for the pod itself, through the pod spec or something, could add a run script on its own build phase. Like now, it's adding resources and source files.

I would love some feedback on these ideas

## CocoaPods Environment

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b9c7fa87755836c1c752f9570ebda506684fca2c
```

**Comment by orta** [comment]
You could look into [CocoaPods-Keys](https://github.com/orta/cocoapods-keys) as a potential solution for this, it's what we use at Artsy for those kind of environment keys

**Comment by Snorlock** [comment]
Cool, il check it out tomorrow, I cant just let you know that my travel was through https://github.com/luggit/react-native-config which was the inspiration for a nice 12 factor way of handling our apps. Trying to avoid using schemas in iOS and flavors in android. But they didnt cope with cocoa setup of the app so we had to make something ourselves, which was inspired by that library.

**Comment by benasher44** [comment]
@Snorlock would the `prepare_command` attribute help here? 

https://guides.cocoapods.org/syntax/podspec.html#prepare_command

**Comment by Snorlock** [comment]
I use post_install now, but prepare_command is also in the podfile?

**Comment by benasher44** [comment]
That would go in your podspec.

**Comment by Snorlock** [comment]
I did take a look at this earlier and thought it didnt work for me, so I have these follow up questions.
Well, this only runs at pod install right? Or is it run at every build?
Because my script is needed to be run at every build to work. It prepares an env file to be picked up by the iOS project.

**Comment by benasher44** [comment]
My understanding is that it runs during `pod install`. In that case, you'd want some sort of plugin.

**Comment by orta** [comment]
Yeah, it's not for that scope of work - you would need to either use a custom xcconfig, xccscheme or create your own custom build phase that DIs your env vars.

**Comment by Snorlock** [comment]
Yeah we found a solution we can live with now, and that is that users which use our script have to add something into the podfile, post_install. Works for now but is not the perfect solution, because I want the pod to hold all its info
