### ISSUE TITLE
Build failing with 1.2.0 -Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Maxwell2022** [CocoaPods/CocoaPods#6450]
I just updated cocoapod from `1.2.0-rc1` to the latest `1.2.0` and my project is now failing to build. I'm not really an expert with pods & xCode so I'm not sure what is going on and why this is failing now.

I've downgraded to `1.2.0-rc1` and it's working again.

## What did you do?

- install cocoapod 1.2.0
- remove existing Pods and Podfile.lock
- run `pod install` (succeeded)
- build xcode project

## What did you expect to happen?
My project to build successfully as before

## What happened instead?

Project failed to build with the following error:

> Undefined symbols for architecture x86_64

![2017-01-30](https://cloud.githubusercontent.com/assets/670701/22454067/6e6e3b40-e7d7-11e6-87dc-19c0b0db8b7d.png)

## CocoaPods Environment

- cocoa pod 1.2.0
- xcode 8.2.1
- react native 0.40.0

## Project that demonstrates the issue

Private project

**Comment by dnkoutso** [comment]
Can you paste your podfile?

**Comment by dnkoutso** [comment]
There was a change in 1.2.0 that avoids double linking static frameworks when targets use `inherit! search_paths` but I'd like to see your Podfile first to see how its wired up.

**Comment by Maxwell2022** [comment]
Here is my Podfile:

```
# Uncomment the next line to define a global platform for your project
# NOTE: The underlying Twilio SDKs require a minimum deployment target of 8.1
platform :ios, '8.1'

install! 'cocoapods', :deterministic_uuids => false

# List repo sources required
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/twilio/cocoapod-specs'

target 'networkhub' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inherit! :search_paths

  # Pods for networkhub
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'React', :path => '../node_modules/react-native'
  pod 'RNBackgroundGeolocation', :path => '../node_modules/react-native-background-geolocation-android'
  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

  # Pods required for Twilio chat
  pod 'TwilioIPMessagingClient', '~> 0.14.2'
end

```

**Comment by dnkoutso** [comment]
@Maxwell2022 is there a reason you are using `inherit! search_paths`? Is `networkhub` an app target or a library?

You should probably remove this line and `pod install` again and try again.

**Comment by Maxwell2022** [comment]
It's an app. yes, removing this line fixed it! Thanks
