### ISSUE TITLE
dyld: Library not loaded:

### ISSUE THREAD

**Issue by useeless37** [CocoaPods/CocoaPods#6453]
# Report

## What did you do?
make my xcode schemes `RideAustin` shared
sudo gem install cocoapods (version 1.2)
Run `pod install`

## What did you expect to happen?
app should run smoothly

## What happened instead?
app crashes with error:

> dyld: Library not loaded: @rpath/libswiftCore.dylib
> Referenced from: /private/var/containers/Bundle/Application/....../Frameworks/MRCountryPicker.framework/MRCountryPicker
> Reason: image not found

## additional info
It works fine when my pod is 1.1.1
<img width="884" alt="screen shot 2017-01-31 at 8 43 56 pm" src="https://i.stack.imgur.com/rDz93.png">
#pod file
```
platform :ios, '10.0'
use_frameworks!

def ride_pods
pod 'MRCountryPicker', :git => 'https://github.com/useeless37/MRCountryPicker.git'
end

target 'RideAustin' do
    ride_pods
end
```

**Comment by benasher44** [comment]
Hi @useeless37! Thanks for the report! Can you please show the contents of your `Pods/Target Support Files/Pods-RideAustin/Pods-RideAustin.debug.xcconfig`? Thanks!

**Comment by useeless37** [comment]
Hi @benasher44 thanks for checking!

EMBEDDED_CONTENT_CONTAINS_SWIFT = YES
FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/AFNetworking" "$PODS_CONFIGURATION_BUILD_DIR/APAddressBook" "$PODS_CONFIGURATION_BUILD_DIR/Bolts" "$PODS_CONFIGURATION_BUILD_DIR/FBSDKCoreKit" "$PODS_CONFIGURATION_BUILD_DIR/FBSDKLoginKit" "$PODS_CONFIGURATION_BUILD_DIR/FBSDKShareKit" "$PODS_CONFIGURATION_BUILD_DIR/ISO8601DateFormatterValueTransformer" "$PODS_CONFIGURATION_BUILD_DIR/KVOController" "$PODS_CONFIGURATION_BUILD_DIR/MRCountryPicker" "$PODS_CONFIGURATION_BUILD_DIR/Mantle" "$PODS_CONFIGURATION_BUILD_DIR/Parse" "$PODS_CONFIGURATION_BUILD_DIR/ParseFacebookUtilsV4" "$PODS_CONFIGURATION_BUILD_DIR/RKValueTransformers" "$PODS_CONFIGURATION_BUILD_DIR/RestKit" "$PODS_CONFIGURATION_BUILD_DIR/SAMKeychain" "$PODS_CONFIGURATION_BUILD_DIR/SDWebImage" "$PODS_CONFIGURATION_BUILD_DIR/SOCKit" "$PODS_CONFIGURATION_BUILD_DIR/SVProgressHUD" "$PODS_CONFIGURATION_BUILD_DIR/Stripe" "$PODS_CONFIGURATION_BUILD_DIR/TTTAttributedLabel" "$PODS_CONFIGURATION_BUILD_DIR/TransitionKit" "$PODS_CONFIGURATION_BUILD_DIR/UIActivityIndicator-for-SDWebImage" "$PODS_CONFIGURATION_BUILD_DIR/ZLPeoplePickerViewController" "${PODS_ROOT}/Crashlytics/iOS" "${PODS_ROOT}/Fabric/iOS" "${PODS_ROOT}/GoogleMaps/Base/Frameworks" "${PODS_ROOT}/GoogleMaps/Maps/Frameworks" "${PODS_ROOT}/GooglePlaces/Frameworks" "${PODS_ROOT}/HockeySDK/HockeySDK-iOS/HockeySDK.embeddedframework"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Crashlytics" "${PODS_ROOT}/Headers/Public/Fabric" "${PODS_ROOT}/Headers/Public/GoogleMaps" "${PODS_ROOT}/Headers/Public/GooglePlaces" "${PODS_ROOT}/Headers/Public/HockeySDK"
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
OTHER_CFLAGS = $(inherited) -iquote "$PODS_CONFIGURATION_BUILD_DIR/AFNetworking/AFNetworking.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/APAddressBook/APAddressBook.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/Bolts/Bolts.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/FBSDKCoreKit/FBSDKCoreKit.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/FBSDKLoginKit/FBSDKLoginKit.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/FBSDKShareKit/FBSDKShareKit.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/ISO8601DateFormatterValueTransformer/ISO8601DateFormatterValueTransformer.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/KVOController/KVOController.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/MRCountryPicker/MRCountryPicker.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/Mantle/Mantle.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/Parse/Parse.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/ParseFacebookUtilsV4/ParseFacebookUtilsV4.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/RKValueTransformers/RKValueTransformers.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/RestKit/RestKit.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/SAMKeychain/SAMKeychain.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/SDWebImage/SDWebImage.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/SOCKit/SOCKit.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/SVProgressHUD/SVProgressHUD.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/Stripe/Stripe.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/TTTAttributedLabel/TTTAttributedLabel.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/TransitionKit/TransitionKit.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/UIActivityIndicator-for-SDWebImage/UIActivityIndicator_for_SDWebImage.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/ZLPeoplePickerViewController/ZLPeoplePickerViewController.framework/Headers" -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/Crashlytics" -isystem "${PODS_ROOT}/Headers/Public/Fabric" -isystem "${PODS_ROOT}/Headers/Public/GoogleMaps" -isystem "${PODS_ROOT}/Headers/Public/GooglePlaces" -isystem "${PODS_ROOT}/Headers/Public/HockeySDK"
OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"z" -framework "AFNetworking" -framework "APAddressBook" -framework "Accelerate" -framework "AssetsLibrary" -framework "Bolts" -framework "CoreData" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreTelephony" -framework "CoreText" -framework "Crashlytics" -framework "FBSDKCoreKit" -framework "FBSDKLoginKit" -framework "FBSDKShareKit" -framework "Fabric" -framework "Foundation" -framework "GLKit" -framework "GoogleMaps" -framework "GoogleMapsBase" -framework "GoogleMapsCore" -framework "GooglePlaces" -framework "HockeySDK" -framework "ISO8601DateFormatterValueTransformer" -framework "ImageIO" -framework "KVOController" -framework "MRCountryPicker" -framework "Mantle" -framework "MobileCoreServices" -framework "OpenGLES" -framework "Parse" -framework "ParseFacebookUtilsV4" -framework "QuartzCore" -framework "QuickLook" -framework "RKValueTransformers" -framework "RestKit" -framework "SAMKeychain" -framework "SDWebImage" -framework "SOCKit" -framework "SVProgressHUD" -framework "Security" -framework "Stripe" -framework "SystemConfiguration" -framework "TTTAttributedLabel" -framework "TransitionKit" -framework "UIActivityIndicator_for_SDWebImage" -framework "UIKit" -framework "ZLPeoplePickerViewController"
OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}/Pods

**Comment by benasher44** [comment]
Ah okay I think I see the issue here. Can you show me the Use Legacy Swift Language Version setting in your RideAustin target?

**Comment by useeless37** [comment]
where can i find that?

**Comment by benasher44** [comment]
It should be a build setting for your RideAustin target. Does your target have Swift files?

**Comment by useeless37** [comment]
no, its the 3rd party library that is using swift MRCountryPicker

**Comment by benasher44** [comment]
CocoaPods uses the Swift version to determine which flag to use. Since you don't have a Swift version set (because your target isn't a Swift target), it's falling back to the old `EMBEDDED_CONTENT_CONTAINS_SWIFT` flag. The easiest way to work around this in your situation is to just set `SWIFT_VERSION = 3.0` (or whichever version of Swift your dependency uses) as a setting in your own xcconfig file or as a user-defined setting in the build settings list for your target. I'll see if there's a reasonable fix here otherwise, but this setup seems to be less common (Obj-C only target with Swift pod dependency).

**Comment by benasher44** [comment]
After discussing this, the best solution for now is probably to bail out if we don't have a `SWIFT_VERSION` set for the given target. This is critical info to know anyway, since we don't otherwise know which version to use to build the Swift targets. I'm going to leave this here for someone who'd like to contribute to CP, since this is an easy starter ticket.

**Comment by useeless37** [comment]
How come it works as expected on cocoapods 1.1 ?

**Comment by benasher44** [comment]
Previously, we didn't choose the build setting key based on the Swift version. We set both the Xcode 7 (old) version and the Xcode 8 (new) version of this setting. Now (as of 1.2.0), we judge which one to set based on the Swift version you have set in your target. If you're using at least version 2.3, then you must be using Xcode 8, so we use the newer build setting key, otherwise, we use the older one, which is what you have set in the first line `EMBEDDED_CONTENT_CONTAINS_SWIFT = YES`.

**Comment by useeless37** [comment]
Hi, where should I set EMBEDDED_CONTENT_CONTAINS_SWIFT = YES ?

**Comment by benasher44** [comment]
@useeless37 on the targets that use Swift code in anyway: either explicitly or via 3rd party libraries. You should be able to find the right flag by searching for "embed" in your build settings.
