### ISSUE TITLE
Improving logic so incomplete downloads aren't cached

### ISSUE THREAD

**Issue by noisypigeon** [CocoaPods/CocoaPods#6454]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

A Realm user filed an issue on [Realm-Cocoa](https://github.com/realm/realm-cocoa) explaining that one of our files (`collection_notifications.hpp`) could not be found. The specific issue can be found here: https://github.com/realm/realm-cocoa/issues/4614.

To summarize it:

- The user has CocoaPods version `1.1.1` installed.
- `pod update` failed with this message:

```
Installing Realm (2.4.2)
[!] /bin/bash -c
set -e 
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 1.0.1
Downloading sync failed:
curl: (56) SSLRead() return error -36
```

- The user claims their internet connection was unstable at the time.
- The user tried again later when their connection was stable but the files weren't fixed.
- The user mentioned the following script fixed the issue for them:

```
#!/usr/bin/env bash

rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

I'm not experienced in this area but is it possible for CocoaPods to improve the logic where downloads occur so incomplete downloads aren't cached in a problematic way? 

Please let me know if there's anything else I can provide. ❤️

**Comment by benasher44** [comment]
@istx25 thanks for the report! This definitely sounds like a bad cache type of issue. I can't guarantee when someone will get to fixing this, but I'll make sure that this issue is labeled appropriately!

**Comment by wgraysen** [comment]
There's nothing more for me to add. All information should be there and it's just in backlog until someone in the CocoaPods team can get around to fix it.

**Comment by istx25** [comment]
There's nothing more for me to add. All information should be there and it's just in backlog until someone in the CocoaPods team can get around to fix it.

**Comment by dnkoutso** [comment]
@istx25 was that part of executing a prepare_command or downloading the actual source (zip perhaps) of the pod?

The reason I am asking is because this issue exists https://github.com/CocoaPods/CocoaPods/issues/4587 which might be similar and if solved will solved this issue here as well.

**Comment by istx25** [comment]
I'm not sure. I'd recommend looking at the original issue on the Realm organization that I linked above. I no longer work at Realm so if you need more information, I recommend reaching out on the original issue and trying to talk to others who work there. Cheers

**Comment by dnkoutso** [comment]
@istx25 thanks, from checking the podspec this seems the same issue where the `prepare_command` failed and possibly continued and so it never ran again.
