### ISSUE TITLE
Using specific git repository with Podspec that has syntax error will say no Podspec found

### ISSUE THREAD

**Issue by Legoless** [CocoaPods/CocoaPods#6457]
# Report

## What did you do?

Trying to install a pod from a specific git repository, that stores the Podspec file. This is the entry in Podfile:

```
pod 'Kvitto', :git => 'https://github.com/cocoanetics/kvitto.git'
```

After running `pod install`, this is the output:
```
Pre-downloading: `Kvitto` from `https://github.com/cocoanetics/kvitto.git`
[!] Unable to find a specification for 'Kvitto'.
```

## What did you expect to happen?

The specification is available on the URL, but the Podspec file has syntax error. The error output by Cocoapods, should clearly state that Podspec was found, but was unable to be parsed.

## What happened instead?
Cocoapods error was to unable to find specification. Since Podspec file is there, I was looking for error in wrong places for quite a while.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ a0eeb5b2f70ec81c193486cf869f6ca29ed38293
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

inhibit_all_warnings!
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'Application' do
    pod 'Kvitto', :git => 'https://github.com/legoless/Kvitto.git'

    target 'FirstBlubs'

end
```

**Comment by DanToml** [comment]
@Legoless There is a syntax error on line 4 of the podspec https://github.com/Cocoanetics/Kvitto/blob/develop/Kvitto.podspec#L4 (see double, double quotes for spec.summary =)

**Comment by DanToml** [comment]
That error should probably be better tho, I saw this elsewhere recently, and the SyntaxError message was below a bunch of stuff that was not particularly helpful for some people

**Comment by Legoless** [comment]
You are absolutely right, I noticed the SyntaxError as well, just needed a while to figure it out. This issue is meant to note that error messages need to be improved. :) It's a very low priority issue though.

**Comment by benasher44** [comment]
Improving the error message here would be a great starter task for someone who's new to contributing!

**Comment by dnkoutso** [comment]
@Legoless I opened up a PR and I tested it against your bad podspec. Looks much better now!
