### ISSUE TITLE
Improving CocoaPods while working in teams. Submodule the Pods directory?

### ISSUE THREAD

**Issue by nickdomenicali** [CocoaPods/CocoaPods#6458]
🌈

One of the questions I keep coming back to when using CocoaPods is whether or not to include the Pods directory in source control (https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control).

The 3rd benefit of ignoring pods is a pretty big deal when working in teams. If you've ever had to review a PR with a modified Pods directory it's very difficult. 

> 3. There won't be any conflicts to deal with when performing source control operations, such as merging branches with different Pod versions.

But ignoring Pods comes with a lot of negatives too. So what if there was a 3rd option? Source control pods but in a separate submodule repo?

It requires some extra coordination between pod update / install and the submodule commit/push. But are there any issues with this I'm not thinking of?

**Comment by orta** [comment]
We do this in [artsy/eigen](https://github.com/artsy/eigen) - I don't think there needs to be any CocoaPods work around automation because CP shouldn't be pushing/pulling from repos not owned by CP

**Comment by nickdomenicali** [comment]
Ok. Yeah you're right @orta , this probably isn't something CP needs to implement. But do you have anything helping keep the submodule up to date when the podfile.lock changes? Or would a prehook work to prevent a commit/push if there are changes in the submodule?

**Comment by orta** [comment]
Nope, we don't do anything, you could maybe do a post-pull hook if that exists to see if the submodule has changed? In our case it happens so rarely that if the build fails we know to either run `pod install` or update the submodule
