### ISSUE TITLE
Issue with if_ether.h header file

### ISSUE THREAD

**Issue by mavris** [CocoaPods/CocoaPods#6459]
* [* ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I created a spec using `pod lib create MF` and put some files in "classes" folder.

## What did you expect to happen?
When I run `pod spec lint MF.podspec` I expected to be successful.

## What happened instead?

I got this error:
```
-> MF (0.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  /var/folders/3t/vz245nxs76xd8z_65b9nwwmh0000gn/T/CocoaPods/Lint/Build/Products/Release-iphonesimulator/MF/MF.framework/Headers/if_ether.h:68:10: error: include of non-modular header inside framework module 'MF.if_ether' [-Werror,-Wnon-modular-include-in-framework-module]
    - ERROR | xcodebuild:  /var/folders/3t/vz245nxs76xd8z_65b9nwwmh0000gn/T/CocoaPods/Lint/Build/Products/Release-iphonesimulator/MF/MF.framework/Headers/MacFinder.h:17:10: error: include of non-modular header inside framework module 'MF.MacFinder' [-Werror,-Wnon-modular-include-in-framework-module]
    - NOTE  | [iOS] xcodebuild:  /var/folders/3t/vz245nxs76xd8z_65b9nwwmh0000gn/T/CocoaPods/Lint/App/main.m:3:9: fatal error: could not build module 'MF'

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 3 errors.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run: 
    `echo "2.3" > .swift-version`.
```
## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b5f214fe352f53be08e933b677d57e4a35682da5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,

The project that reproduce the error: https://github.com/mavris/MF

**Comment by benasher44** [comment]
Hi @mavris! Thanks for the report! I apologize for the delayed response. Are you still experiencing this issue, and if so would you mind re-posting your sample project? Thanks again!

**Comment by benasher44** [comment]
I'm going to close this issue, since there hasn't been any more detail provided that would allow us to help debug the issue. If you're still experiencing this, please feel free to reopen and provide more detail that could help us debug, and then we'd be happy to help. Have a great day!
