### ISSUE TITLE
Adding new pods not updating Pods project targets

### ISSUE THREAD

**Issue by dbarros** [CocoaPods/CocoaPods#6460]
# Report

## What did you do?

Add these two lines to my Podfile (for both app targets):

```
pod 'Fabric'
pod 'Crashlytics'
```

Then ran `pod install`

## What did you expect to happen?

When I open the workspace of the project which uses the Pods project, I expected to see two new targets, one for each pod added to the Podfile.

## What happened instead?

The Targets for the Pods project did not change.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.10.0
Ruby lib dir : /Users/diego/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 31e024c6ca3a1b53af0e79e7f15a74e18aca99c4
```

### Installation Source

```
Executable Path: /Users/diego/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'talkApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '3.4.1'
	pod 'AlamofireImage', '2.4.1'
	pod 'JGProgressHUD', '1.4'
	pod 'JKNotificationPanel', '0.2.0'
	
	pod 'Freddy', '2.1.0'

  pod 'Fabric'
  pod 'Crashlytics'
end

target 'talkClient' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '3.4.1'
  pod 'AlamofireImage', '2.4.1'
  pod 'JGProgressHUD', '1.4'
  pod 'JKNotificationPanel', '0.2.0'
  
  pod 'Freddy', '2.1.0'

  pod 'Fabric'
  pod 'Crashlytics'
end
```

**Comment by dnkoutso** [comment]
Are those pre-built pods? Pre-built (no sources) pods will not have any targets created for them.

**Comment by diegob** [comment]
Under the Pods project there are: 

```
Pods > Crashlytics > Frameworks > Crashlytics.framework
Pods > Fabric > Frameworks > Fabric.framework
```

Although, for both, at the level above the aforementioned `Frameworks` directories the source code is also there.

**Comment by dbarros** [comment]
Under the Pods project there are: 

```
Pods > Crashlytics > Frameworks > Crashlytics.framework
Pods > Fabric > Frameworks > Fabric.framework
```

Although, for both, at the level above the aforementioned `Frameworks` directories the source code is also there. 

So what I'm seeing is both? Pre-built pods, along with their source?

**Comment by dnkoutso** [comment]
<img width="400" alt="screen shot 2017-02-02 at 10 31 30 pm" src="https://cloud.githubusercontent.com/assets/310370/22581786/607d33bc-e997-11e6-8ce7-d0a7a8a69b5d.png">

You are seeing the headers and packaged framework.

I dont think there is an issue here?

**Comment by dnkoutso** [comment]
The generated xcconfig properly includes the `-framework` flags as well.

**Comment by dbarros** [comment]
@dnkoutso that is what you referred to as a pre-built pod?

**Comment by dnkoutso** [comment]
Yes.

**Comment by dbarros** [comment]
@dnkoutso First time I've run across one. Thank you for responding.

**Comment by dnkoutso** [comment]
np!
