### ISSUE TITLE
Custom Module Map And Cocoapods

### ISSUE THREAD

**Issue by rparvathaneni** [CocoaPods/CocoaPods#6461]
# Report
A Swift framework with explicit submodules defined in custom module map is not carrying over to the App.

## What did you do?
Created a framework with a custom module map with explicit submodules.
```
framework module MyFramework {
    explicit module Models {
        header "MyFrameworkModels.h"
        export *
    }
    explicit module API {
        header "MyFrameworkAPI.h"
        export *
    }
}
```
Within the framework when I try to import the classes defined under Models, compiler requires explicit import of Models (`import MyFramework.Models`). But, when we import the same framework via cocoapods into an App, by simply importing the framework(`import MyFrameworks`) we have access to the classes from both `Models` and `API` submodules. The restrictive nature of defining explicit submodules via custom module map file is lost.

## What did you expect to happen?
I expected the restrictive nature of defining explicit submodules is retained in MyApp as well.

## What happened instead?
 The restrictive nature of defining explicit submodules with custom module map file is lost.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4cb642d9944f733df63ef03ec79d2f804a089aa9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-art         : 0.9.5
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

inhibit_all_warnings!

project 'MyApp.xcodeproj'

target 'MyApp'
pod 'MyFramework', :path => '../MyFramework'
```

## Project that demonstrates the issue

https://www.dropbox.com/s/0nkz1p82glt369h/CustomModuleMapAndCocoapods.zip?dl=0

`MyApp` is the app that has `MyFramework` installed via local cocoapods. When you open the `MyApp.xcworkspace` you can see  that inside the `ViewController.swift` class we are just importing `import MyFramework` and I am able to initialize both `ModelA(a: "a")` and `APIA()` no problem. The compiler should have instead required us to import `MyFramework.Models` and `MyFramework.API` for the code to compile.

Any ideas on how to retain the restrictive nature of defining explicit submodules in custom module map?

**Comment by benasher44** [comment]
Hi @rparvathaneni! Thanks for the report! We really appreciate you posting a link to a sample project. Unfortunately, that link no longer works. In the meantime, have you made sure you're using the `module_map` setting in your podspec https://guides.cocoapods.org/syntax/podspec.html#module_map ?

**Comment by benasher44** [comment]
I'm going to close this issue, since there hasn't been any more detail provided that would allow us to help debug the issue. If you're still experiencing this, please feel free to reopen and provide more detail that could help us debug, and then we'd be happy to help. Have a great day!

**Comment by rparvathaneni** [comment]
@benasher44 - I did try using the `module_map` setting in the podspec file to begin with. Here is a link to the sample project: https://github.com/rparvathaneni/CustomModuleMapAndCocoapods

**Comment by rparvathaneni** [comment]
@benasher44 - can you please reopen this issue and take a look at the above sample project. Appreciate your help!

**Comment by benasher44** [comment]
@rparvathaneni thanks!

**Comment by benasher44** [comment]
Hi @rparvathaneni! I cloned your project and built, and it worked fine. I also was able to see that your module map was integrated properly:

![screen shot 2017-03-28 at 7 04 34 am](https://cloud.githubusercontent.com/assets/1120429/24409353/d1f377f6-1384-11e7-8597-b98da064109e.png)

There you can see the `MyFramework.modulemap` in the project files on the left, and you can see the build setting is properly set on the right. Is there something I'm missing here? Thanks!

**Comment by rparvathaneni** [comment]
Hi @benasher44, The problem here is that I defined explicit submodules below.

![screen shot 2017-03-28 at 6 52 21 pm](https://cloud.githubusercontent.com/assets/723860/24431105/114c24b2-13e8-11e7-9e56-7152b13a9182.png)

So, I would expect to import `MyFramework.Models` to have access to `ModelA` class and to import `MyFramework.API` to have access to `APIA` class. 

Instead, simply by importing `MyFramework` in `MyApp` I am getting access to both `ModelA` & `APIA`. The restrictive nature of defining explicit submodules with custom module map file seems to be lost. Isn't this incorrect behavior?

Please let me know if I am missing something here. Thanks!

![screen shot 2017-03-28 at 6 50 30 pm](https://cloud.githubusercontent.com/assets/723860/24430990/71cb651a-13e7-11e7-91e2-84fcc2f03006.png)
