### ISSUE TITLE
pod lib lint issue with yajl dependency

### ISSUE THREAD

**Issue by herau** [CocoaPods/CocoaPods#6468]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod lib lint XXX.spec` on a spec file which contains `yajl-obj` dependency.
The project has been created with the `pod lib create Test` command.
Then i put a `yajl-objc`dependency in my spec file

## What did you expect to happen?

**BUILD SUCCESS**
The build is successful if i use a `Podfile` with a `yajl-obj` pod dependency and using `pod install`. Cocoapods will fetch both `yajl` and `yajl-obj` and build the project correctly.

## What happened instead?

lib lint error : `yajl` module isn't built.

```
** BUILD FAILED **
The following build commands failed:
	CompileC /Volumes/diskE/Users/n27/Library/Developer/Xcode/DerivedData/App-bamojkvdfucwpygzokefophgrqrc/Build/Intermediates/Pods.build/Release-iphonesimulator/yajl-objc.build/Objects-normal/i386/YAJLDocument.o yajl-objc/Classes/YAJLDocument.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
 -> DSPassport (0.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  yajl/src/yajl_alloc.h:42:10: fatal error: 'api/yajl_common.h' file not found
    - NOTE  | [iOS] xcodebuild:  yajl-objc/Classes/YAJLParser.h:31:10: fatal error: could not build module 'yajl'
```

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.9.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 3dspods - ssh://git@gitlab.anakin.dsone.3ds.com:10022/mobile/cocoapods-specs.git @ d933852523c6541d292e5a39487eba3228ec00b0
               master - https://github.com/CocoaPods/Specs.git @ adea5e77cf0f03ceb7b0dbc458176f78125b4095
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```
## Project that demonstrates the issue

https://github.com/herau/Test

**Comment by orta** [comment]
This sounds like an issue with the yawl dependency rather than with CocoaPods the tool itself, I'd recommend moving this issue over to that library.
