### ISSUE TITLE
Can't change name of cocoapods account 

### ISSUE THREAD

**Issue by odedharth** [CocoaPods/CocoaPods#6469]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk register my@email.com 'My Name'

## What did you expect to happen?

My account name would update

## What happened instead?

Got a mail to validate the session. Clicked the mail. And then nothing happened. The name of my account stayed the same. 

## CocoaPods Environment

   CocoaPods : 1.2.0
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)

**Comment by orta** [comment]
`pod trunk register` will [create a new account](https://guides.cocoapods.org/terminal/commands.html#pod_trunk_register) with the new email,  not re-name it.

**Comment by benasher44** [comment]
Ah this was my bad. I was under the impression you could update your account name this way. I think I got that impression from another issue, but I can't seem to find it.

**Comment by orta** [comment]
I bet there's some confusion with all of this: https://github.com/CocoaPods/trunk.cocoapods.org/issues/155

**Comment by odedharth** [comment]
It indeed says it should change the name:

>     $ pod trunk register EMAIL [NAME]
> 
>       Register a new account, or create a new session.
> 
>       If this is your first registration, both an `EMAIL` address and your `NAME` are
>       required. If you’ve already registered with trunk, you may omit the `NAME`
>       (unless you would like to change it).

**Comment by orta** [comment]
Ah cool, then yeah, this is a dupe of the issue I've mentioned above
