### ISSUE TITLE
Why I use pod search command can't find out my spec?

### ISSUE THREAD

**Issue by dawnnnnn** [CocoaPods/CocoaPods#6470]
I' m using CocoaPods 1.2.0
When I run `pod trunk push DNTagView.podspec`, it tell me that `DNTagView(1.0.0) successfully published`. But I can't use pod search DNTagView command get a result of my spec. Can someone tell me what happend?

And I can search other specs like AFNetworking, and I have been updated my pod repo.. It still no result..

This is my spec 👉 [DNTagView](http://cocoapods.org/pods/dntagview)

**Comment by orta** [comment]
Can you try deleting your local cache? `rm -rf ~/Library/Caches/CocoaPods` and then see if that fixes it?

**Comment by dawnnnnn** [comment]
Thank you for helping.  The problem is resolved. 😊

**Comment by lilianmao** [comment]
I met the same problem, I remove the CocoaPods cache, but ```pod search LLModularization```doesn't find.

**Comment by lilianmao** [comment]
I run ```pod trunk ```again, it tell me ```Unable to accept duplicate entry for: LLModularization (1.0.0)```.
<img width="1273" alt="llmodularization" src="https://user-images.githubusercontent.com/9494430/35512548-10374c1a-053b-11e8-8c5b-b7f853c02d6a.png">
