### ISSUE TITLE
watchOS storyboards do not support target device type "mac"

### ISSUE THREAD

**Issue by songjianboy** [CocoaPods/CocoaPods#6472]
I would like to move watch target's resource and storyboard as a pod library, but when I 
compile error “error: watchOS storyboards do not support target device type "mac””。
I found Pods-JDWatch-resources.sh script TARGET_DEVICE_ARGS not include watch，Is cocoaPods not supported like this？please help me！

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
