### ISSUE TITLE
Can not update cocoapods from 0.35.0 to 1.1.0

### ISSUE THREAD

**Issue by matzino** [CocoaPods/CocoaPods#6475]
# Report

## What did you do?
sudo gem install cocoapods --verbose

ℹ Please replace this with what you did.  
sudo gem install cocoapods --verbose

## What did you expect to happen?
Update from cocoapods from version 0.35.0 to 1.1.0

ℹ Please replace this with what you expected to happen.  
Update from cocoapods from version 0.35.0 to 1.1.0

## What happened instead?
GET https://api.rubygems.org/api/v1/dependencies?gems=thread_safe
200 OK
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ETIMEDOUT: Operation timed out - connect(2) (https://your-dns-needs-immediate-attention.box/quick/Marshal.4.8/nap-1.1.0.gemspec.rz)

ℹ Please replace this with of what happened instead.  
GET https://api.rubygems.org/api/v1/dependencies?gems=thread_safe
200 OK
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ETIMEDOUT: Operation timed out - connect(2) (https://your-dns-needs-immediate-attention.box/quick/Marshal.4.8/nap-1.1.0.gemspec.rz)

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
[!] Unknown command: `env`
Did you mean: ipc

Usage:

    $ pod COMMAND

      CocoaPods, the Objective-C library package manager.

Commands:

    + init                Generate a Podfile for the current directory.
    + install             Install project dependencies to Podfile.lock versions
    + ipc                 Inter-process communication
    + lib                 Develop pods
    + list                List pods
    + outdated            Show outdated project dependencies
    + plugins             Show available CocoaPods plugins
    + repo                Manage spec-repositories
    + search              Searches for pods
    + setup               Setup the CocoaPods environment
    + spec                Manage pod specs
    + trunk               Interact with the CocoaPods API (e.g. publishing new specs)
    + try                 Try a Pod!
    + update              Update outdated project dependencies and create new
                          Podfile.lock

Options:

    --silent              Show nothing
    --completion-script   Print the auto-completion script
    --version             Show the version of the tool
    --verbose             Show more debugging information
    --no-ansi             Show output without ANSI codes
    --help                Show help banner of specified command
`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by Coeur** [comment]
probably unrelated but...
> `your-dns-needs-immediate-attention.box`

Maybe something to do with https://triple-networks.com/2015/03/26/your-dns-needs-immediate-attention/

**Comment by benasher44** [comment]
Hi there! Thanks for the report! This appears to be an issue with your connection, and hopefully some of the links that @Coeur graciously posted will help out. I also recommend trying `gem update` as opposed to `gem install` for updating an existing install of CocoaPods. Since this doesn't appear to be a CocoaPods issue, I'm going to close this. If you experience more issues running `gem install` or `gem update`, I recommend filing an issue on rubygems. Have a great day!

**Comment by matzino** [comment]
Thank you for your help. I could solve it :)
