### ISSUE TITLE
Allow different version of a pod per Target in same project

### ISSUE THREAD

**Issue by jadyzdd** [CocoaPods/CocoaPods#6478]
## What did you expect to happen?
i have a Podfile like this, 
Is it possible to Allow two different version of a pod per target in same project?

target 'XXXX' do
pod 'AFNetworking',  '2.0.0'
end

target 'XXXX1' do
pod 'AFNetworking',  '3.0.0'
end

**Comment by dnkoutso** [comment]
Not at this time. PRs welcome!

**Comment by jadyzdd** [comment]
@dnkoutso  Can you tell me when can you support？

**Comment by orta** [comment]
There is no timeframe for this @jadyzdd - it's not our our roadmap, but you or others are welcome to add it

**Comment by jadyzdd** [comment]
@dnkoutso  i see, thank you all the same!

**Comment by benasher44** [comment]
@jadyzdd can you provide some more background on the use case here? Thanks!

**Comment by benasher44** [comment]
There hasn't been discussion on this issue in some time. I'm going to close it for now. Please feel free to reopen if you'd like to provide more detail and continue the discussion. Have a great day!
