### ISSUE TITLE
Wrong FRAMEWORK_SEARCH_PATHS when inheriting search paths

### ISSUE THREAD

**Issue by YANOUSHek** [CocoaPods/CocoaPods#6479]
@dnkoutso I'm opening a new issue just like you asked.

The problem happens in my project that is written in Swift and uses Google's pods that are Obj-C only and delivered without source – just frameworks. The main target for the project works fine but the test targets that should inherit the search paths include only the ones that are really compiled and not the ones that are delivered as frameworks.

I've created a simple Podfile to showcase the issue:

```
target 'CocoaPodsStaticLinkingExample' do
  use_frameworks!

  pod 'FacebookLogin'
  pod 'FacebookCore'
  pod 'Google/SignIn'

  target 'CocoaPodsStaticLinkingExampleTests' do
    inherit! :search_paths
  end

  target 'CocoaPodsStaticLinkingExampleUITests' do
    inherit! :search_paths
  end
end
```

When doing `pod install` with this file the FRAMEWORK_SEARCH_PATHS for CocoaPodsStaticLinkingExampleTests and CocoaPodsStaticLinkingExampleUITests targets are wrong. They're missing references to Google/SignIn since those pods are delivered without a source – only frameworks.

To compare: this is the `FRAMEWORK_SEARCH_PATHS` for CocoaPodsStaticLinkingExample target (line breaks added for readability):
```
FRAMEWORK_SEARCH_PATHS = 
  $(inherited) 
  "$PODS_CONFIGURATION_BUILD_DIR/Bolts"
  "$PODS_CONFIGURATION_BUILD_DIR/FBSDKCoreKit" 
  "$PODS_CONFIGURATION_BUILD_DIR/FBSDKLoginKit" 
  "$PODS_CONFIGURATION_BUILD_DIR/FacebookCore"
  "$PODS_CONFIGURATION_BUILD_DIR/FacebookLogin" 
  "$PODS_CONFIGURATION_BUILD_DIR/GTMOAuth2" 
  "$PODS_CONFIGURATION_BUILD_DIR/GTMSessionFetcher" 
  "$PODS_CONFIGURATION_BUILD_DIR/GoogleToolboxForMac" 
  "${PODS_ROOT}/FirebaseAnalytics/Frameworks/frameworks" 
  "${PODS_ROOT}/FirebaseCore/Frameworks/frameworks" 
  "${PODS_ROOT}/FirebaseInstanceID/Frameworks/frameworks" 
  "${PODS_ROOT}/Google/Frameworks" "${PODS_ROOT}/GoogleAppUtilities/Frameworks/frameworks" 
  "${PODS_ROOT}/GoogleInterchangeUtilities/Frameworks/frameworks" 
  "${PODS_ROOT}/GoogleSignIn/Frameworks" 
  "${PODS_ROOT}/GoogleSymbolUtilities/Frameworks/frameworks"
```

this is `FRAMEWORK_SEARCH_PATHS` for CocoaPodsStaticLinkingExampleTests and CocoaPodsStaticLinkingExampleUITests:
```
FRAMEWORK_SEARCH_PATHS =
  $(inherited)
  "$PODS_CONFIGURATION_BUILD_DIR/Bolts"
  "$PODS_CONFIGURATION_BUILD_DIR/FBSDKCoreKit" 
  "$PODS_CONFIGURATION_BUILD_DIR/FBSDKLoginKit" 
  "$PODS_CONFIGURATION_BUILD_DIR/FacebookCore" 
  "$PODS_CONFIGURATION_BUILD_DIR/FacebookLogin" 
  "$PODS_CONFIGURATION_BUILD_DIR/GTMOAuth2" 
  "$PODS_CONFIGURATION_BUILD_DIR/GTMSessionFetcher" 
  "$PODS_CONFIGURATION_BUILD_DIR/GoogleToolboxForMac" 
```

My current work-around for this problem is to extract the test targets from inside the app target in the Podfile and just include all the pods in them individually.

I've created an example project that shows this problem. Just run `pod install` and if you try to build the app it works just fine but when running tests linker will complain about missing headers:
[CocoaPodsStaticLinkingExample.zip](https://github.com/CocoaPods/CocoaPods/files/764579/CocoaPodsStaticLinkingExample.zip)

Hope this is detailed enough.

**Comment by dnkoutso** [comment]
@YANOUSHek are you sure you tried the latest version from master?

My search paths for `Pods-CocoaPodsStaticLinkingExampleTests.debug` are:

```
FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/Bolts" "$PODS_CONFIGURATION_BUILD_DIR/FBSDKCoreKit" "$PODS_CONFIGURATION_BUILD_DIR/FBSDKLoginKit" "$PODS_CONFIGURATION_BUILD_DIR/FacebookCore" "$PODS_CONFIGURATION_BUILD_DIR/FacebookLogin" "$PODS_CONFIGURATION_BUILD_DIR/GTMOAuth2" "$PODS_CONFIGURATION_BUILD_DIR/GTMSessionFetcher" "$PODS_CONFIGURATION_BUILD_DIR/GoogleToolboxForMac" "${PODS_ROOT}/FirebaseAnalytics/Frameworks/frameworks" "${PODS_ROOT}/FirebaseCore/Frameworks" "${PODS_ROOT}/FirebaseInstanceID/Frameworks/frameworks" "${PODS_ROOT}/Google/Frameworks" "${PODS_ROOT}/GoogleAppUtilities/Frameworks/frameworks" "${PODS_ROOT}/GoogleInterchangeUtilities/Frameworks/frameworks" "${PODS_ROOT}/GoogleSignIn/Frameworks" "${PODS_ROOT}/GoogleSymbolUtilities/Frameworks/frameworks"
```

**Comment by YANOUSHek** [comment]
If that's the  case then the master version works fine and I just messed up when installing it. Thanks... can't wait for this to be release in 1.2.1 (hopefully).

**Comment by dnkoutso** [comment]
@YANOUSHek we might get a release next week. I am marking this as awaiting input for now, please close once you've verified it works (or not!)

**Comment by dnkoutso** [comment]
@YANOUSHek took a bit longer than a week but 1.2.1.beta.1 is out. Please test and ensure it works for you and close the issue.

**Comment by dnkoutso** [comment]
Going to close this one, @YANOUSHek please re-open if this is still an issue for 1.2.1.beta.1.

**Comment by YANOUSHek** [comment]
@dnkoutso I'll test it and let you know. But looks like it should work  ;)

**Comment by YANOUSHek** [comment]
Works like a charm. Thank you
