### ISSUE TITLE
Including pods requiring different deployment targets for app and extension

### ISSUE THREAD

**Issue by arifken** [CocoaPods/CocoaPods#6482]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Create an iOS application project with an iMessage extension. set the platform in the Podfile to :ios, 9.0, since we want the iOS application to run on 9.0 devices. The iMessage extension will only run on 10.0 devices.
2. Have both the app and the iMessage extension require some sort of common dependency, e.g. Alamofire.
3. Create a separate pod library that has classes that reference iOS 10-only frameworks (e.g. calling MSMessage, or message extension classes). Also, have this pod library depend on Alamofire. For this example. let's call it MyMessageExtensionUtils
4. Have the Podfile's Message extension target depend on MyMessageExtensionUtils created in step 3, so that the message extension can use reference classes in the pod library.

The requirements are to be able to run `pod install` on the iOS application, and to be able to publish MyMessageExtensionUtils to a private specs repo

## What did you expect to happen?

Two things: 
1) When I run `pod install` on the application, I expect it to install all my dependencies 
2) I expect to be able to run `pod lib lint` on MyMessageExtensionUtils and have that succeed

## What happened instead?

I noticed this issue because when I run `pod lib lint` on MyMessageExtensionUtils, I get the error 
`Specs satisfying the <any dependency in my podspec>  dependency were found, but they required a higher minimum deployment target.`

If i set `spec.ios.deployment_target = '10.0'` in MyMessageExtensionUtils's podspec, this lint error goes away, and linting completes successfully

However, by setting this deployment target in MyMessageExtensionUtils's podspec, i'm unable to `pod install` on my application. My main application has a deployment target of 9.0, but my Messages extension has a deployment target of 10.0. Since my Messages extension is the only target depending on MyMessageExtensionUtils, I would expect it to install successfully. Instead, it fails with the error:

`Specs satisfying the <my library project> dependency were found, but they required a higher minimum deployment target.`

I don't think it should fail here, because the deployment target of the Message Extension matches the deployment target of MyMessageExtensionUtils

## CocoaPods Environment

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
```

## Project that demonstrates the issue

I don't have a specific project, but I can create an example if needed

**Comment by benasher44** [comment]
Hi there! What pods are listed as dependencies in your podspec?

**Comment by arifken** [comment]
Hey @benasher44! I just listed Alamofire and AlamofireImage. I actually created a sample project that demonstrates this (created the project named DependencyDemo, and put the library project in the same directory as DependencyDemoLib, referencing with :path) https://github.com/arifken/cocoapods-issue-6482

In the current state I committed, `pod install` on the main project works. But if you try to cd to the DependencyDemoLib (the library project) and run `pod lib lint` it will fail. If you then uncomment the line in the podspec that sets the deployment target to 10.0 for iOS, the linting will succeed, but the `pod install` on the main app will then fail. Thanks for your help!

**Comment by benasher44** [comment]
@arifken I had some time to try this out. I apologize for the delay. I set the deployment target to 9.0 in DependencyDemoLib, and then the pod lints fine if you make your `ReplaceMe.swift` look like this:

```
import Messages

@available(iOS 10, *)
class ReplaceMe {
    var iosTenOnlyVar:MSMessage?
}
```


Typically what you do in these scenarios is use iOS 9 for your minimum deployment target anyway, and then you use availability macros/checks (like the one inserted above the `class` declaration above) to ensure that you don't call into iOS 10-only APIs on an iOS 9 device. Hope this helps! I'm going to close this out, since I believe CocoaPods already supports this scenario you're referring to. Feel free to continue to post here though, and I'd be happy to help you get your pod linting.
