### ISSUE TITLE
maintain a http download via podspec source and got fatal error: 'string' file not found

### ISSUE THREAD

**Issue by shenruisi** [CocoaPods/CocoaPods#6485]
this is my pod spec 

Pod::Spec.new do |s|
  s.name         = "prengine"
  s.version      = "0.1.0-beta.2"
  s.summary      = "A static library of prengine."
  s.description  = <<-DESC
                  一种用来帮助客户端实现更好的路由解决方案的rewrite引擎（mobile router）
                   DESC

  s.homepage     = "https://github.com/shenruisi/prengine"
 
  s.license      = "BSD"

  s.author             = { "shen yin" => "tigris.shin@gmail.com" }

  s.source       = { :http => "https://github.com/shenruisi/prengine/files/765799/prengine-0.1.0-beta.1.zip"}
  s.source_files  = '*.h'
  s.vendored_libraries = "libprengine-0.1.0-beta.1.a"

  s.library = 'stdc++'

  s.xcconfig = {
    'CLANG_CXX_LANGUAGE_STANDARD' => 'gnu++11',
    'CLANG_CXX_LIBRARY' => 'libstdc++'
  }

end

and in the zip there are files as below
/cond_ast.h
/prengine_val.h
/prengine.h
/libprengine-0.1.0-beta.1.a

my lib is written in c++, and i got follow error  when i run pod spec lint
- NOTE  | xcodebuild:  Headers/Public/prengine/prengine_val.h:13:10: fatal error: 'string' file not found

and this is what in the prengine_val.h
#ifndef prengine_val_hpp
#define prengine_val_hpp

#include <string>
using namespace std;
typedef enum {
    PR_ID_LONGLONG,
    PR_ID_DOUBLE,
    PR_ID_STRING
}PR_ID_TYPE;

class pr_id{
public:
    union{
        double d;
        long long ll;
    }number;
    bool undefined = false;

    string str;
    PR_ID_TYPE type;

    pr_id();
    pr_id(double);
    pr_id(long long);
    pr_id(string);

    double doubleValue();
    long long longLongValue();
    string stringValue();

    void print();

    pr_id operator+(const pr_id &);
    pr_id operator-(const pr_id &);
    pr_id operator*(const pr_id &);
    pr_id operator/(const pr_id &);
    pr_id operator%(const pr_id &);
    bool operator==(const pr_id &);
    bool operator>(const pr_id &);
    bool operator>=(const pr_id &);
    bool operator<(const pr_id &);
    bool operator<=(const pr_id &);
    bool operator!=(const pr_id &);
    bool operator&&(const pr_id &);
    bool operator||(const pr_id &);
};

pr_id pr_yes();
pr_id pr_no();
pr_id pr_undefined();
pr_id pr_getval(const char*);
void pr_valfree(pr_id*);

#endif /* prengine_val_hpp */

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
