### ISSUE TITLE
Add command line support for `deprecated_in_favor_of`

### ISSUE THREAD

**Issue by thomasvl** [CocoaPods/CocoaPods#6486]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

[`pod trunk deprecate [name]`](https://guides.cocoapods.org/terminal/commands.html#pod_trunk_deprecate) only seems to set [deprecated](https://guides.cocoapods.org/syntax/podspec.html#deprecated), it would be nice if it accepted an argument to also support setting [deprecated_in_favor_of](https://guides.cocoapods.org/syntax/podspec.html#deprecated_in_favor_of).

## What did you expect to happen?

N/A

## What happened instead?

N/A

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3a1df803ccc7cc6c14a834dc48b9717fc8dca1ee
```

### Installation Source

```
Executable Path: /Users/thomasvl/.gem/ruby/2.0.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

N/A

**Comment by dnkoutso** [comment]
Thanks @thomasvl this doesn't seem hard to add, I think. Will mark it as an easy improvement and maybe get to it for next release.

**Comment by dnkoutso** [comment]
/ @thomasvl is this not already supported? https://github.com/CocoaPods/cocoapods-trunk/blob/master/lib/pod/command/trunk/deprecate.rb#L14

**Comment by dnkoutso** [comment]
Opened up a PR to fix the help command to properly display the available options.

**Comment by thomasvl** [comment]
You might want to also update the guide page: https://guides.cocoapods.org/terminal/commands.html#pod_trunk_deprecate
