### ISSUE TITLE
Framework build fails with apostrophe

### ISSUE THREAD

**Issue by grosch** [CocoaPods/CocoaPods#6488]
> Before you start, are you using the latest CocoaPods release?

I'm using 1.2.0 which is what gem install just provided so I think yes.

# Report

## What did you do?

Building my older application with Xcode 8

## What did you expect to happen?

It to build :)

## What happened instead?

I'm getting an error on code signing:

Code Signing /Users/scott/Library/Developer/Xcode/DerivedData/Daytona's_Surf-agsuaanghqhucxafbevzpibqsuxy/Build/Products/Debug-iphonesimulator/Daytona's Surf.app/Frameworks/AFNetworking.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/scott/Library/Developer/Xcode/DerivedData/Daytona's_Surf-agsuaanghqhucxafbevzpibqsuxy/Build/Products/Debug-iphonesimulator/Daytona's Surf.app/Frameworks/AFNetworking.framework'
/Users/scott/Library/Developer/Xcode/DerivedData/Daytonas_Surf-agsuaanghqhucxafbevzpibqsuxy/Build/Products/Debug-iphonesimulator/Daytonas Surf.app/Frameworks/AFNetworking.framework: No such file or directory

Notice how my target has an apostrophe in it.  Bad, I know, but this is a published app and Apple accepted it this way so at this point I can't just undo it.  Notice how the codesign command it PRINTS shows the 's in the display, but when the actual eval happens that apostrophe disappears, resulting in a bad path name.

It's missing in two places there when the eval happens

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.11.1
Ruby lib dir : /usr/local/Cellar/ruby/2.4.0/lib
Repositories : ExpandableDatePicker - https://github.com/GargoyleSoft/ExpandableDatePicker.git @ ccd44244dc2321ad6f53ce91a5c9eb13de338037
               master - https://github.com/CocoaPods/Specs.git @ 16a5b72f3a182d403d27337f476bbec6fcfeb2a8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
use_frameworks!
platform :ios, '8.0'
target "Daytona's Surf" do
	pod 'AFNetworking'
	pod 'FreeStreamer'
	#pod 'Alamofire', '~> 3.0'
end
```

## Project that demonstrates the issue

Rename this from .png to .tgz and you'll have a bare-bones example of an empty Xcode project that has an 's in the name, and then a Podfile that asks for AFNetworking.  Just open the .xcworkspace and hit build and you'll see the issue.

![example](https://cloud.githubusercontent.com/assets/315966/22961633/820b25a2-f2fc-11e6-8af5-006ba1dfa631.png)

**Comment by dnkoutso** [comment]
There's been 3 commits around this: 08d756c2d89b8ac599877fea4cf7ab6696e92d9a, 991624d084191ee95a20f9d834089c5bf1df4256 and 787813313fa8628801387d32a426b80363e178b8 seems like a pretty delicate situation that can easily go wrong...

**Comment by benasher44** [comment]
The arguments to `codesign` should be quoted. The fix seems pretty straightforward. Thanks @grosch for the report!

**Comment by benasher44** [comment]
@grosch we'd really appreciate a PR if you have time to look at fixing this! I'd be happy to help in any way I can :).

**Comment by EliaCereda** [comment]
This doesn't seem exactly straightforward to me, seeing that the way that particular parameter is quoted has been changed two times in two weeks.

Can someone with shell script programming experience look into it? This is creating problems for me too.

**Comment by dnkoutso** [comment]
@EliaCereda feel free to take a shot at it. Adding tests for this will ensure all edge cases are handled.

**Comment by benasher44** [comment]
Erg actually, I'm looking at this again, and the argument in question is quoted. I'm not sure why this is failing :(
