### ISSUE TITLE
ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

### ISSUE THREAD

**Issue by surjeet-singh** [CocoaPods/CocoaPods#6489]
I am trying to create pod of my project, but when i run below command on terminal. 
`pod lib lint `
I received this error 
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.

When i hit this command `pod spec lint --verbose`
I received this log as error 

`
-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with xcodebuild. 
xcodebuild clean build -workspace /var/folders/x9/8nkwp5316d7fmkm3tphnxbgm00010n/T/CocoaPods/Lint/App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=0BAD1EBA-82C1-4418-BA98-C8B3338D94CB
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = iphonesimulator10.2

=== CLEAN TARGET SSPods OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
=== BUILD TARGET SSPods OF PROJECT Pods WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
 -> SSPods (1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/spec/lint.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
`
**XCode Version**
8.2.1

**CocoaPods Environment**
CocoaPods : 1.1.1

**Comment by dnkoutso** [comment]
Please upgrade to 1.2.0 and see if that fixes it. Also please paste podspec contents or a sample project.

**Comment by benasher44** [comment]
@surjeet-singh thanks again for the report! I'm going to close this one, since there hasn't been any activity on it for awhile. Please open a new issue if you're still experiencing this with the latest CocoaPods version. Have a great day!

**Comment by comcc** [comment]
i meet the same question on 1.2.0

**Comment by Insofan** [comment]
i meet the issue on 1.2.1
here is the podspec
```
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Insofan' => 'blabla@gmail.com' }
  s.source           = { :git => 'https://github.com/Insofan/HXPullRefresh.git', :tag => s.version.to_s }
  s.ios.deployment_target = '8.0'
  s.source_files = 'HXPullRefresh/Classes/**/*'
  s.resource_bundles = {
  'HXPullRefresh' => ['HXPullRefresh/**/*']
  }
   s.frameworks = 'UIKit'
   s.dependency 'SnapKit'
```
@comcc Have you fix it?
