### ISSUE TITLE
Question - How can I weakly link to dynamic framework and then manually load it in code using dlopen

### ISSUE THREAD

**Issue by avnerbarr** [CocoaPods/CocoaPods#6494]
I want to weakly link to a vendored framework (embedded library) in such a way where it doesn't "auto-load" with the app/

The framework should only be loaded at the point that I call something like:

```

- (void)doSomethingWithFramework
{
   // first we load the framework explicately
  loadFramework(@"myFramework");

  // now we can do something with it
MyFrameworkClass *c = ....;
}

void loadFrameworkDynamic(NSString * _Nonnull libName) {
  
    //WidgetSource is the name of framework
    
    NSString *libExtension = @"framework";
    NSString *path = [[NSBundle mainBundle] pathForResource:libName ofType:libExtension];
    NSLog(@"Loading dynamic library: %@", path);
    path=[path stringByAppendingString:[NSString stringWithFormat:@"/%@",libName]];
    
    void *revealLib = NULL;
    revealLib = dlopen([path cStringUsingEncoding:NSUTF8StringEncoding], RTLD_NOW);
    
    if (revealLib == NULL)
    {
      char *error = dlerror();
      NSLog(@"dlopen error: %s", error);
    }

}

```

Is it possible to configure the pod in such a way?

**Comment by dnkoutso** [comment]
Podspecs support weak_framework setting, however if this doesn't work for you, you cannot do it from the Podfile level. Somethin like, `pod 'SomePod', :link_style => 'weak'` is potentially what you are asking.

You can however do a `post_install` hook in your Podfile that replaces the `-framework` with `-weak_framework` for the one you want. its a bit hacky but it should work.

**Comment by avnerbarr** [comment]
how would I go about writing a post_install hook like that?

**Comment by benasher44** [comment]
@avnerbarr You'd have to write some code that manipulates the appropriate *.xcconfig files used for the targets that link the framework in question. I'm going to close this, since I don't think we'll be able to provide any support for this in terms of patching CocoaPods, and I think the `post_install` hook provides a pretty flexible workaround for cases like this. We'd certainly appreciate if you posted any progress you made here to help others as well! Have a great day!

**Comment by lordzsolt** [comment]
Sorry for reviving this thread, @dnkoutso could you elaborate on the `post_install` hook?

I tried `config.build_settings['OTHER_LDFLAGS'] << '-weak_framework FooFramework'`, but `-framework FooFramework` still gets generated in `Pods-MyTarget.debug.xcconfig`. I tried printing the contents of `config.build_settings['OTHER_LDFLAGS']` but it's empty.

Any tips on how I modify the `.xcconfig` file? Or I'm not supposed to do that?

**Comment by akhrameev-picsart** [comment]
@lordzsolt I've found [this solution](https://stackoverflow.com/a/65058023/1735276).

Hope it can help someone later ;-)

```
targets_to_weaklink=['Target1']
frameworks_to_weaklink=['Framework1']
post_install do |installer|
  targets_to_weaklink.map!{|t| t="Pods-#{t}"}
  installer.pods_project.targets.each do |target|
    next unless targets_to_weaklink.include?(target.name)

    target.build_configurations.each do |config|
      base_config_reference = config.base_configuration_reference
      unless base_config_reference.nil?
        xcconfig_path = base_config_reference.real_path
        xcconfig = File.read(xcconfig_path)
        frameworks_to_weaklink.each do |framework|
          xcconfig = xcconfig.gsub(/-framework "#{framework}"/, "-weak_framework \"#{framework}\"")
        end
        File.open(xcconfig_path, "w") { |file| file << xcconfig }
      end
    end
  end
end
```
