### ISSUE TITLE
1.2.1 

### ISSUE THREAD

**Issue by jklausa** [CocoaPods/CocoaPods#6498]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Hey,

we're impacted by the bug fixed in https://github.com/CocoaPods/CocoaPods/pull/6477, which seems to be targeted to be included in 1.2.1 release.

Is there any chance of this getting pushed out in a public release anytime soon? 

We can of course just tell `bundler` to use CP's `master`, but I'm reluctant to use that ~~ in production ~~.

Thanks for the awesome work on the project!

**Comment by DanToml** [comment]
@jklausa My current plan is to get a 1.2.1 release out late this week. You could also point bundler at the exact commit that #6477 was merged with as a stable point until then?

**Comment by jklausa** [comment]
Awesome, thanks for letting me know!

Late this week is perfect. 👌
