### ISSUE TITLE
Fail to generate the expected project url.

### ISSUE THREAD

**Issue by WenchaoD** [CocoaPods/CocoaPods#6499]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Try to enter the following url:
https://cocoapods.org/pods/FSPagerView

## What did you expect to happen?

Entering the expected website.

## What happened instead?

* Redirecting to the following url:
https://github.com/WenchaoD/FSPagerView

* After clicking the `Spec` button in the search result of `https://cocoapods.org/?q=FSPagerView`, a `404` showed with a strange url: https://github.com/CocoaPods/Specs/tree/master/Specs/FSPagerView/0.1.0/FSPagerView.podspec.json

| 
![image](https://cloud.githubusercontent.com/assets/5186464/23131814/6dbc670e-f7c6-11e6-8942-d617a7795568.png)
|
| --- |

| 
![image](https://cloud.githubusercontent.com/assets/5186464/23131841/8bc1f584-f7c6-11e6-90df-6bb3ce667311.png)
 |
| --- |

## CocoaPods Environment

> Notice that this issue has happened before I updated to the latest version of CocoaPods.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /usr/local/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1846a157ace2d10b73649b70c4cf2a0b2d70dc7a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/WenchaoD/FSPagerView

| ![image](https://cloud.githubusercontent.com/assets/5186464/23131964/01edde6c-f7c7-11e6-8e75-cdbd1cbd1efe.png) |
| --- |

**Comment by dnkoutso** [comment]
You probably want to file this in Cocoapods.org repo (https://github.com/CocoaPods/cocoapods.org)

**Comment by WenchaoD** [comment]
Looks like it could be (https://github.com/CocoaPods/cocoadocs.org). Thanks for your help @dnkoutso
