### ISSUE TITLE
Acknowledgments text format in pods-acknowledgments.plist not well formatted

### ISSUE THREAD

**Issue by tkallioras** [CocoaPods/CocoaPods#6501]
**Goals**

Produce an Acknowledgements section in Settings.bundle by use of cocoapods-acknowledgements plugin for Realm

**Expected Results**

Have the Realm Acknowledgements text shown in the Settings among all other framework acknowledgements

**Actual Results**

Realm Acknowledgements do not appear. There is a large gap where the text should appear. The other acknowledgement texts appear just fine.

**Steps to Reproduce**

Follow this [guide](https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements)

and then use in podfile:

plugin 'cocoapods-acknowledgements', :settings_bundle => true

I submitted this issue with the Realm team but after they looked into it, they said that it is a problem with the acknowledgments pod. I haven't seen it on other pods though.

This is the [initial issue](https://github.com/realm/realm-cocoa/issues/4636)

**Version of Realm and Tooling**

ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

Xcode 8.2.1
Build version 8C1002

Realm (2.4.2)
RealmSwift (2.4.2)

Cocoapods: 1.2.0

**Comment by benasher44** [comment]
@tkallioras thanks for the report! Would you mind posting a screenshot? Thanks!
