### ISSUE TITLE
The 'Pods-CommonPods-ProjectName' target has libraries with conflicting names:  libcrypto.a and libssl.a

### ISSUE THREAD

**Issue by hengyizhangcn** [CocoaPods/CocoaPods#6502]
two git repos are used in the podfile, like A and B, and they are all use libcrypto.a and libssl.a in their own repo. When I type the command "pod update --no-repo-update", in the last line of the outputs, it shows "The 'Pods-CommonPods-ProjectName' target has libraries with conflicting names:  libcrypto.a and libssl.a", how I can do to avoid or solve this problem?
(Tip: pod version is 1.2.0)

**Comment by dnkoutso** [comment]
@hengyizhangcn this is hard for us to debug/figure out without a sample project. Can you please provide one?

**Comment by hengyizhangcn** [comment]
@dnkoutso ,the sample project repo https://github.com/hengyizhangcn/PodConflictDemo.git.
Thanks!

**Comment by phanisai4u** [comment]
https://github.com/CocoaPods/CocoaPods/issues/5624

**Comment by shangqianForFun** [comment]
I just solve the problem by removing one of the conflict repo from the pod, instead, i manage the conflict repo manual...

**Comment by dnkoutso** [comment]
I might be able to take look soon enough (maybe this week)

**Comment by wmenge** [comment]
I've had a very similar issue with some private pods. This only happens since Cocoapods version 1.2.1. When I revert to 1.0.1, the issue dissappears

**Comment by NullWorld** [comment]
I also encountered this problem, use the pods tripartite library management, use of libcrypto. A. and libssl. A two times, has also had a conflict.Don't want to go to the version back to 1.0.1, because we have quite a few people...so we have better method to deal with the problem ...?

**Comment by hengyizhangcn** [comment]
@dnkoutso , this problem is always exist in the cocoapods leastest version 1.5.1

**Comment by haofanning** [comment]
Do anyone have any idea to solve this problem?
