### ISSUE TITLE
optional podspec variable breaking_change_version and breaking_change_warning

### ISSUE THREAD

**Issue by evermeer** [CocoaPods/CocoaPods#6505]
* [*] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

'pod update'

## What did you expect to happen?

I would like to see a warning if I can expect breaking changes (with pointer to changelog)

This could be solved by adding 1 or 2 variables to the podspec like this:

```ruby
Pod::Spec.new do |s|
  s.name         = "MyGreatLibrary"
  s.version      = "2.3.0"
  s.summary      = "This is my great library"
  s.breaking_change_version = "2.1.0"
  s.breaking_change_warning = "In version 2.1.0 the MyObj structure has change. See changelog for more info"
  ... rest of podspec
```

## What happened instead?

Just the update and then getting a compile error

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : angryduck2 - https://github.com/angryDuck2/CocoaSpecs @ d8ba9783b52fd970b8be590f0ce5de49a4c400e0
               master - https://github.com/CocoaPods/Specs.git @ 18e3aa6773d8b648bbbafa379d5de09188a5b50b
               popcorntimetv - https://github.com/PopcornTimeTV/Specs @ 7564b696351aafa600f85f404ddabb0ea7f0d7fc
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

-- removed, not applicable

## Project that demonstrates the issue

N/A

**Comment by benasher44** [comment]
@evermeer thanks for the suggestion! What advantage would this have over following semver versioning, wherein major version changes indicate a breaking change? Thanks!

**Comment by evermeer** [comment]
True, but with versioning it's not always a breaking change. It could mean new functionality. 
Besides that, when doing a pod update I would like to be able to inform users that they probably have to update their code and point them to the right instructions. 

Maybe an other option could be outputting the relative part of the changelog.md which could be triggered by a pod parameter? of course the .md then needs to be in a strict format. For instance the versions should be in there as `## 1.2.0 ....` or even within that a tag like `##### breaking changes`

**Comment by benasher44** [comment]
I think the latter idea (outputting relative part of the changelog) could be done as a CocoaPods plugin and would be a good place to start! This seems like a nice-to-have feature rather than something that belongs in the podspec, at least right now.
