### ISSUE TITLE
Specify platform version for individual pod

### ISSUE THREAD

**Issue by meismyles** [CocoaPods/CocoaPods#6506]
Removed the template text as it's more of a query that I can't find an answer to rather than an issue.

Is it possible to specify a platform version for an individual pod? I want to keep my overall platform version at iOS 8.3 - but I want to install a pod that requires iOS 9+.

What I would like to do, is keep an overall version at 8.3, but somehow specify for a single pod that the platform is iOS 9, so that `pod install` does not fail, and then do manual checks in my actual project code to see if the user is on iOS 9 or not, and then only use this functionality if they are. Is this possible?

**Comment by dnkoutso** [comment]
I do not believe this is supported today. It will be a bit complicated to add maybe.

**Comment by meismyles** [comment]
Ok, that's a shame 😢

Thanks for your help. I'll leave the issue open for now in case anyone else has any ideas - but feel free to close it whenever.

**Comment by benasher44** [comment]
I'm not sure if one already exists, but typically you'd write a plugin that subverts `pod install` checks in this case. That way, you can enable the plugin and enter into a sort of "i know what I'm doing" mode :)

**Comment by benasher44** [comment]
Thinking about this some more, in your case you technically support lower than iOS 9, so it makes sense that your pod would be marked as such.

**Comment by meismyles** [comment]
@benasher44 Yeah but I want the pod still. Just I want to decide in my code (by checking if iOS 9 is available) whether to use it or not.

I understand that this is probably not best as default behaviour as it allows users to install pods and then potentially try and use them when the device doesn't support it causing a crash. However, a setting that allows you to ignore this and perform the checks yourself would be nice.

I've just worked around it myself by forking the repo, modifying the podspec version to 8.3 and then performing the checks myself manually. If anyone else runs into this issue, this is one potential workaround. It will stop any updates of that repo though until you pull them into your personal repo.

**Comment by benasher44** [comment]
In your case, you can just set the supported iOS version to the lowest version you're willing to support, and then have your code do nothing unless the version in use is iOS 9. Or am I misunderstanding what you want?

**Comment by meismyles** [comment]
If I set the supported iOS version to 8.3 in **my Podfile** then I can't install the pod I want as it has a min iOS version of iOS 9.0 in **its Podspec**.

If I set the supported iOS version to 9.0 in **my Podfile**, the new pod I want will install fine, however, then all my other pods either update (or will in the future if a version is released) potentially to a version that no longer supports iOS 8.

**Comment by benasher44** [comment]
Ah I see. I misunderstood. Yes, in that case you'll need to use a custom plugin or some other means to subvert the CocoaPods check. Thanks again for bringing this up, but we're going to keep this check in CocoaPods because it's useful in the vast majority of cases. Have a great day!

**Comment by andrewtheis** [comment]
@benasher44 Was a workaround or feature added that allows this check to be skipped?
