### ISSUE TITLE
Downloading source via http ignores URL

### ISSUE THREAD

**Issue by Noobish1** [CocoaPods/CocoaPods#6507]
# Report

## What did you do?

Adding [SwiftLint](https://github.com/realm/SwiftLint) to my Podfile via:
```
pod 'SwiftLint', :git => 'https://github.com/realm/SwiftLint.git'
```

## What did you expect to happen?

Download the `portable_swiftlint.zip` file for the latest release (0.16.1).

## What happened instead?

it downloaded the repo as a zip file instead

### Stack

Cocoapods 1.2.0, Originally tried with Cocoapods 1.1.1 and upgraded to see if it was still broken on 1.2.0.

## Project that demonstrates the issue

Add Swiftlint to any project.

**Comment by Noobish1** [comment]
Their podspec is the following:
```

Pod::Spec.new do |s|
  s.name                = 'SwiftLintFramework'
  s.version             = `make get_version`
  s.summary             = 'A tool to enforce Swift style and conventions.'
  s.homepage            = 'https://github.com/realm/SwiftLint'
  s.source              = { :git => s.homepage + '.git', :tag => s.version }
  s.license             = { :type => 'MIT', :file => 'LICENSE' }
  s.author              = { 'JP Simard' => 'jp@jpsim.com' }
  s.platform            = :osx, '10.10'
  s.source_files        = 'Source/SwiftLintFramework/**/*.swift'
  s.pod_target_xcconfig = { 'APPLICATION_EXTENSION_API_ONLY' => 'YES' }
  s.dependency            'SourceKittenFramework', '= 0.17.0'
  s.dependency            'Yaml', '= 3.3.1'
  s.dependency            'Yams', '= 0.1.4'
end
```

**Comment by orta** [comment]
You're overriding the `source` attribute with ` :git => 'https://github.com/realm/SwiftLint.git'` and so it won't sue the one inside the podspec. This is a feature that lets people use their own forks etc. You would need to point to the actual zip file instead of the repo if you wanted to use a different URL.

**Comment by Noobish1** [comment]
Oh crap right, derp my bad sorry for the hassle, thanks Orta.

**Comment by orta** [comment]
No worries 👍
