### ISSUE TITLE
Cannot Resolve Pod B's dependency upon Pod A

### ISSUE THREAD

**Issue by verticon** [CocoaPods/CocoaPods#6508]
# Report

## What did you do?

pod spec lint MoBetterBluetooth.podspec 

## What did you expect to happen?

I expected the pod spec to be successfully validated

## What happened instead?

I had 12 unresolved identifier errors

### Stack

```
   CocoaPods : 1.2.0.beta.3
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.6.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c9cf31de3d5b41a83b5340b66f8321453379643e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/verticon/MoBetterBluetooth.git

This morning I created my first ever pod; VerticonsToolbox
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  VerticonsToolbox (0.0.2) successfully published
 📅  February 22nd, 11:22
 🌎  https://cocoapods.org/pods/VerticonsToolbox
 👍  Tell your friends!
--------------------------------------------------------------------------------

In the pod spec for MoBetterBluetooth I have :   s.dependency "VerticonsToolbox"
But when I lint MoBetterBluetooth I get unresolved identifier errors. All of the missing identifiers are in VerticonsToolbox.

Also, when I browse to cocoapods.org and search for VerticonsToolbox it is not found. Huh?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by verticon** [comment]
Okay, Orta, I'll take it to StackOverflow, Thx.
