### ISSUE TITLE
tvOS pod xcassets not compiling

### ISSUE THREAD

**Issue by AnthonyMDev** [CocoaPods/CocoaPods#6509]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I have a private pod with a subspec that includes a `resource_bundle`. I'm using this and it works properly in an `iOS` project.

I'm including this pod in a `tvOS` project and the `.xcassets` are not being included in my compiled application. The resources exist in the pod in my workspace. I can view the `.xcassets` in Xcode. However, when I run my application, the compiled bundle does not include the `.car` file for the assets. The resource bundle does exist in the location I expect it to be in, but there are no resources.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : bitbucket-ao-private-cocoapods - https://AnthonyMDev@bitbucket.org/app-order/ao-private-cocoapods.git @ c6ac8aaff905b29935fd59c32df406d7049ebe54
               bitbucket-app-order-ao-private-cocoapods - https://bitbucket.org/app-order/ao-private-cocoapods.git @ c6ac8aaff905b29935fd59c32df406d7049ebe54
               master - https://github.com/CocoaPods/Specs.git @ 478ce6985d4b3f57961a9d14043b8d7008322e67
               Zorts - https://bitbucket.org/app-order/zorts-private-spec-repo.git @ 042e59bc61f0675641ed04e5cf42ded327e84bb1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.1.2
cocoapods-try          : 1.1.0
```

**Comment by AnthonyMDev** [comment]
I solved this. My own mistake. Sorry.

**Comment by benasher44** [comment]
No problem! Glad you got it resolved!
