### ISSUE TITLE
loaded resources failure!!!

### ISSUE THREAD

**Issue by lzkkk** [CocoaPods/CocoaPods#6511]
i has a problem that when i us
“s.resource_bundles = {
    'PodTestLibrary' => ['Pod/Assets/*.png']
  }  ” in pod spec  , i can't loaded resources.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by lzkkk** [comment]
thx
