### ISSUE TITLE
Duplicate interface definition for class &  Property has a previous declaration error

### ISSUE THREAD

**Issue by RamdhaSOi** [CocoaPods/CocoaPods#6512]
Cocoapods version: 1.2.0
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

Recently i tried pod update, But after that facing lot of errors. 
1. Duplicate interface definition for class
2. Property has a previous declaration error
3. Redefinition of enumerator 

What reason behind this error? What the solution?

Thanks in advance.

**Comment by benasher44** [comment]
Hi @RamdhaSOi! Can you please post some information about your Podfile as well as the log output you're seeing? Thanks!

**Comment by RamdhaSOi** [comment]
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/tradingticket/SpecRepo'
platform :ios, '9.0'
inhibit_all_warnings!

# link_with 'appName', 'appName'

target 'appName' do
  use_frameworks!
  pod 'AFNetworking'
  pod 'AMPopTip'
  pod 'AppsFlyerFramework'
  pod 'Bolts'
  pod 'CHCSVParser'
  pod "CleverTap-iOS-SDK"
  pod 'DLImageLoader', '~> 2.1.0'
  pod 'DZNEmptyDataSet'
  pod 'EAIntroView', '~> 2.9.0'
  pod 'EventEmitter'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'Google/SignIn'
  pod 'GTMBase64'
  pod 'HWToast'
  pod 'iCarousel'
  pod 'JSBadgeView'
  pod 'KSToastView', '0.5.2'
  pod 'KVNProgress'
  pod 'LogEntries'
  pod 'Mantle'
  pod 'MGSwipeTableCell'
  pod 'Mixpanel'
  pod 'MSSimpleGauge'
  pod 'MBProgressHUD'
  pod "MTDates"
  pod "NIXTextEncoding"
  pod 'PNChart'
  pod 'PubNub'
  pod "RNCryptor", '~> 3.0.1'
  pod "SlackTextViewController"
  pod 'STHTTPRequest'
  pod "TCJSONKit"
  pod 'TradeItIosTicketSDK', '~> 0.1.15'
  pod 'TTTAttributedLabel'
  pod 'Underscore.m'
end


1.  **Duplicate interface definition for class 'PNConfiguration'.**
*In file included from /Volumes/D/appName/libs/vinepub/Vinepub.m:15:
16:12: Previous definition is here

**2. Property has a previous declaration:** /Volumes/D/appName/Pods/PubNub/PubNub/Data/Service Objects/PNResult.h:43:69: Property has a previous declaration

*In file included from /Volumes/D/appName/libs/vinepub/models/channels/ChannelMap.m:17:9: In file included from *In file included from /Volumes/D/appName//libs/vinepub/models/channels/ChannelMap.m:17:

**3. Redefinition of enumerator** /Volumes/D/appName/Pods/AFNetworking/AFNetworking/AFNetworkReachabilityManager.h:27:28: Redefinition of 'AFNetworkReachabilityStatus'

**Comment by benasher44** [comment]
Just looking at the output, this appears to be an issue with a pod you updated. Running `pod update` updates all of your pods. You'll likely need to go through and figure out which symbols are being duplicated, which pods those duplicated symbols appear in, and in which versions these started to happen so that you can report this issue to the appropriate pod authors.

Given that this doesn't appear to be an issue with CocoaPods, but rather an unfortunate mixture of updated pods, I'm going to close this one. Best of luck, and have a great day!

**Comment by Jasper2016** [comment]
I  have this issue, how to deal with it ?

**Comment by RamdhaSOi** [comment]
Under Target->Architecture-> Project Build Architecture Only
Debug =>Yes
Release => No


After setting like this. Its was working

**Comment by Alex-Daocaoren** [comment]
I always meet this issue when i  switch the same pods of remote to local。The previous pods of remote still in my project root Pod directory，then i build the build error occur！I always remove the preview pods which i want to switch local to avoid this problem。how to solve this problem more grace ？

**Comment by RameshSain** [comment]
Having same issue . did you find the reason for this issue? @ElizaSapir  @Alex-Daocaoren

**Comment by Alex-Daocaoren** [comment]
> @Alex-Daocaoren did you find the reason for this issue?

sorry, I'm not

**Comment by Alex-Daocaoren** [comment]
@RameshSain  @ElizaSapir I'm not

**Comment by peixuan197** [comment]
I also having same issue . did you find the reason for this issue? @ElizaSapir @Alex-Daocaoren

**Comment by JasonYaoSiXu** [comment]
I had same issue.And I resolved it . But I still not ideal why.
This is my podfile
```
target 'CallPods' do
  use_frameworks!
  
  pod 'xxx','1.5.2'
  pod 'logs','1.2.1'
end
```
And this is my xxx podspec
```
Pod::Spec.new do |s|
s.dependency 'logs','>= 1.2.1'

s.pod_target_xcconfig = {
    'FRAMEWORK_SEARCH_PATHS' => '$(inherited) $(PODS_ROOT)/**',
    'HEADER_SEARCH_PATHS' => '$(inherited) $(PODS_ROOT)/**'
}
end

```

pod install work well, but when I ran my project,  I met **Duplicate interface definition for class & Property has a previous declaration error**. My way is delete **'HEADER_SEARCH_PATHS' => '$(inherited) $(PODS_ROOT)/**'**.  pod install and ran project work well

**Comment by JasonYaoSiXu** [comment]
And this

`cocoapods (1.11.2)
cocoapods-core (1.11.2)
cocoapods-deintegrate (1.0.5)
cocoapods-downloader (1.5.1)
cocoapods-mPaaS (0.9.5)
cocoapods-plugins (1.0.0)
cocoapods-pod-linkage (0.0.1)
cocoapods-search (1.0.1)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.6.0)
cocoapods-try (1.2.0)
cocoapods-user-defined-build-types (0.0.7)`

**Comment by hgrigoryan-fy** [comment]
> I had same issue.And I resolved it . But I still not ideal why. This is my podfile
> 
> ```
> target 'CallPods' do
>   use_frameworks!
>   
>   pod 'xxx','1.5.2'
>   pod 'logs','1.2.1'
> end
> ```
> 
> And this is my xxx podspec
> 
> ```
> Pod::Spec.new do |s|
> s.dependency 'logs','>= 1.2.1'
> 
> s.pod_target_xcconfig = {
>     'FRAMEWORK_SEARCH_PATHS' => '$(inherited) $(PODS_ROOT)/**',
>     'HEADER_SEARCH_PATHS' => '$(inherited) $(PODS_ROOT)/**'
> }
> end
> ```
> 
> pod install work well, but when I ran my project, I met **Duplicate interface definition for class & Property has a previous declaration error**. My way is delete **'HEADER_SEARCH_PATHS' => '$(inherited) $(PODS_ROOT)/**'**. pod install and ran project work well

You saved me!! In my case I had $(PODS_ROOT) being added in the project settings (as opposed to from podspec).
