### ISSUE TITLE
storyboard of watchos lint failed with 'do not support target device type'

### ISSUE THREAD

**Issue by kjian** [CocoaPods/CocoaPods#6516]
# Report

## What did you do?

ℹ Run 'pod lib lint' against a podspec, which contains a storyboard targeted at 'watchos 3.0'.

## What did you expect to happen?

ℹ Lint passed successfully.

## What happened instead?

ℹ Failed with 'error: watchOS storyboards do not support target device type "mac".'.

## Possibly Reason

ℹ According to the code [here](https://github.com/CocoaPods/CocoaPods/blob/32e84e15cab49ead0c61ce85c2324acf9c4f72f9/lib/cocoapods/generator/copy_resources_script.rb#L117) and issue #[5282](https://github.com/CocoaPods/CocoaPods/issues/5282#issuecomment-218475519) , did the `TARGETED_DEVICE_FAMILY=4` option forgot to implement? 
Since the same storyboard can be compiled successfully with `--target-device watch`.

## CocoaPods Environment

ℹ 
### Stack

```
CocoaPods : 1.2.0
Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
RubyGems : 2.4.5.1
Host : Mac OS X 10.12 (16A323)
Xcode : 8.2.1 (8C1002)
Git : git version 2.2.1
Ruby lib dir : /Users/kjian/.rvm/rubies/ruby-2.2.4/lib
```

### Installation Source

```
Executable Path: /Users/kjian/.rvm/gems/ruby-2.2.4@test/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podspec

```ruby
Pod::Spec.new do |s|
  s.name             = 'watch'
  s.summary          = 'xxx'
  s.version          = '0.1.0'
  s.description      = <<-DESC
                       xxx xxx
                       DESC
  s.homepage         = 'xxx'
  s.license          = { :type => 'Copyright', :text => 'All rights reserved.' }
  s.author           = { 'xxx' }
  s.platform         = :watchos, '3.0'
  s.source           = { :git => 'xxx'}

  s.watchos.resources = ['Assets.xcassets', 'Interface.storyboard']
end

```

**Comment by benasher44** [comment]
Thanks for the report, pointing out where in code the issue is, and a potential solution! This seems like a great starter ticket for someone, so I'm going to tag is as such. Thanks again!
