### ISSUE TITLE
Error Installing Pod

### ISSUE THREAD

**Issue by yashvyas29** [CocoaPods/CocoaPods#6517]
# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Error installing pod.

### Error Detail:

"Http download
   $ /usr/bin/curl -f -L -o
   /var/folders/8n/vqz11bsn7_3cz_50ks86sx7s2qfzw4/T/d20170227-2837-nt6nnl/file.zip
   http://dev.umeng.com/files/download/Umeng_SDK_Social_iOS_ARM64_6.3.0.zip
   --create-dirs --netrc-optional
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--          0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--          0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--          0  101M    0  3960    0     0   1473      0 19:58:39  0:00:02 19:58:37  147     0  101M    0 30720    0     0   7803      0  3:46:16  0:00:03  3:46:13  780     0  101M    0 40960    0     0   8965      0  3:16:56  0:00:04  3:16:52  896     0  101M    0 55160    0     0   9417      0  3:07:29  0:00:05  3:07:24 1044     0  101M    0 60160    0     0   8753      0  3:21:42  0:00:06  3:21:36 1136     0  101M    0 60160    0     0   7636      0  3:51:13  0:00:07  3:51:06 1082     0  101M    0 60160    0     0   6776      0  4:20:34  0:00:08  4:20:26  595     0  101M    0 60160    0     0   6087      0  4:50:03  0:00:09  4:49:54  361     0  101M    0 85760    0     0   8096      0  3:38:05  0:00:10  3:37:55  646     0  101M    0 92160    0     0   7538      0  3:54:13  0:00:12  3:54:01  598     0  101M    0 92160    0     0   6967      0  4:13:25  0:00:13  4:13:12  598     0  101M    0 92160    0     0   6477      0  4:32:35  0:00:14  4:32:21  598     0  101M    0 92160    0     0   6050      0  4:51:50  0:00:15  4:51:35  598     0  101M    0 92160    0     0   5676      0  5:11:03  0:00:16  5:10:47  113     0  101M    0 93440    0     0   5416      0  5:25:59  0:00:17  5:25:42   25     0  101M    0 93440    0     0   5118      0  5:44:58  0:00:18  5:44:40   25     0  101M    0 93440    0     0   4852      0  6:03:53  0:00:19  6:03:34   25     0  101M    0 93440    0     0   4612      0  6:22:49  0:00:20  6:22:29   25     0  101M    0 93440    0     0   4394      0  6:41:49  0:00:21  6:41:28   25     0  101M    0 93440    0     0   4197      0  7:00:41  0:00:22  7:00:19          0  101M    0 93440    0     0   4016      0  7:19:38  0:00:23  7:19:15          0  101M    0 93440    0     0   3850      0  7:38:36  0:00:24  7:38:12          0  101M    0 93440    0     0   3697      0  7:57:34  0:00:25  7:57:09          0  101M    0 93440    0     0   3556      0  8:16:30  0:00:26  8:16:04          0  101M    0 93440    0     0   3425      0  8:35:30  0:00:27  8:35:03          0  101M    0 93440    0     0   3303      0  8:54:32  0:00:28  8:54:04          0  101M    0 93440    0     0   3190      0  9:13:29  0:00:29  9:13:00          0  101M    0 93440    0     0   3085      0  9:32:19  0:00:30  9:31:49          0  101M    0 93440    0     0   2986      0  9:51:17  0:00:31  9:50:46          0  101M    0 93440    0     0   2893      0 10:10:18  0:00:32 10:09:46          0  101M    0 93440    0     0   2806      0 10:29:13  0:00:33 10:28:40          0  101M    0 93440    0     0   2724      0 10:48:10  0:00:34 10:47:36          0  101M    0 93440    0     0   2646      0 11:07:16  0:00:35 11:06:41          0  101M    0 93440    0     0   2573      0 11:26:12  0:00:36 11:25:36          0  101M    0 93440    0     0   2504      0 11:45:06  0:00:37 11:44:29          0  101M    0 93440    0     0   2438      0 12:04:12  0:00:38 12:03:34          0  101M    0 93440    0     0   2376      0 12:23:06  0:00:39 12:22:27          0  101M    0 93440    0     0   2317      0 12:42:01  0:00:40 12:41:21          0  101M    0 93440    0     0   2261      0 13:00:53  0:00:41 13:00:12          0  101M    0 93440    0     0   2207      0 13:20:00  0:00:42 13:19:18          0  101M    0 93440    0     0   2156      0 13:38:55  0:00:43 13:38:12          0  101M    0 94720    0     0   2136      0 13:46:35  0:00:44 13:45:51   25     0  101M    0 96000    0     0   2153      0 13:40:04  0:00:44 13:39:20   59     0  101M    0 99840    0     0   2161      0 13:37:02  0:00:46 13:36:16  131     0  101M    0 99840    0     0   2115      0 13:54:48  0:00:47 13:54:01  131     0  101M    0 99840    0     0   2071      0 14:12:32  0:00:48 14:11:44  131     0  101M    0 99840    0     0   2028      0 14:30:37  0:00:49 14:29:48  105     0  101M    0 99840    0     0   1988      0 14:48:08  0:00:50 14:47:18   68     0  101M    0 99840    0     0   1949      0 15:05:54  0:00:51 15:05:03          0  101M    0 99840    0     0   1911      0 15:23:55  0:00:52 15:23:03          0  101M    0 99840    0     0   1875      0 15:41:39  0:00:53 15:40:46          0  101M    0 99840    0     0   1841      0 15:59:03  0:00:54 15:58:09          0  101M    0 99840    0     0   1807      0 16:17:05  0:00:55 16:16:10          0  101M    0 99840    0     0   1775      0 16:34:42  0:00:56 16:33:46          0  101M    0 99840    0     0   1744      0 16:52:23  0:00:57 16:51:26          0  101M    0 99840    0     0   1714      0 17:10:06  0:00:58 17:09:08          0  101M    0 99840    0     0   1685      0 17:27:50  0:00:59 17:26:51          0  101M    0 99840    0     0   1657      0 17:45:32  0:01:00 17:44:32          0  101M    0 99840    0     0   1630      0 18:03:11  0:01:01 18:02:10          0  101M    0 99840    0     0   1603      0 18:21:26  0:01:02 18:20:24          0  101M    0 99840    0     0   1578      0 18:38:53  0:01:03 18:37:50          0  101M    0 99840    0     0   1553      0 18:56:54  0:01:04 18:55:50          0  101M    0 99840    0     0   1529      0 19:14:44  0:01:05 19:13:39          0  101M    0 99840    0     0   1506      0 19:32:23  0:01:06 19:31:17          0  101M    0 99840    0     0   1484      0 19:49:45  0:01:07 19:48:38          0  101M    0 99840    0     0   1462      0 20:07:40  0:01:08 20:06:32          0  101M    0 99840    0     0   1441      0 20:25:16  0:01:09 20:24:07          0  101M    0 99840    0     0   1420      0 20:43:23  0:01:10 20:42:13          0  101M    0 99840    0     0   1400      0 21:01:09  0:01:11 20:59:58          0  101M    0 99840    0     0   1381      0 21:18:30  0:01:12 21:17:18          0  101M    0 99840    0     0   1362      0 21:36:20  0:01:13 21:35:07          0  101M    0 99840    0     0   1344      0 21:53:41  0:01:14 21:52:27          0  101M    0 99840    0     0   1326      0 22:11:31  0:01:15 22:10:16          0  101M    0 99840    0     0   1308      0 22:29:51  0:01:16 22:28:35          0  101M    0 99840    0     0   1291      0 22:47:37  0:01:17 22:46:20          0  101M    0 99840    0     0   1275      0 23:04:47  0:01:18 23:03:29          0  101M    0 99840    0     0   1259      0 23:22:23  0:01:19 23:21:04          0  101M    0 99840    0     0   1243      0 23:40:26  0:01:20 23:39:06          0  101M    0  100k    0     0   1266      0 23:14:38  0:01:21 23:13:17   58     0  101M    0  108k    0     0   1364      0 21:34:26  0:01:21 21:33:05  264     0  101M    0  113k    0     0   1397      0 21:03:51  0:01:23 21:02:28  330     0  101M    0  113k    0     0   1381      0 21:18:30  0:01:24 21:17:06  330     0  101M    0  115k    0     0   1385      0 21:14:48  0:01:24 21:13:24  382     0  101M    0  115k    0     0   1369      0 21:29:42  0:01:25 21:28:17  306     0  101M    0  115k    0     0   1353      0 21:44:57  0:01:26 21:43:31  118     0  101M    0  115k    0     0   1338      0 21:59:35  0:01:27 21:58:08   27     0  101M    0  115k    0     0   1323      0 22:14:33  0:01:28 22:13:05   27     0  101M    0  115k    0     0   1308      0 22:29:51  0:01:29 22:28:22          0  101M    0  116k    0     0   1303      0 22:35:02  0:01:31 22:33:31   23     0  101M    0  116k    0     0   1289      0 22:49:45  0:01:32 22:48:13   23     0  101M    0  116k    0     0   1275      0 23:04:47  0:01:33 23:03:14   23     0  101M    0  116k    0     0   1261      0 23:20:10  0:01:34 23:18:36   23     0  101M    0  116k    0     0   1248      0 23:34:45  0:01:35 23:33:10   23     0  101M    0  116k    0     0   1235      0 23:49:38  0:01:36 23:48:02          0  101M    0  116k    0     0   1222      0 24:04:51  0:01:37 24:03:14          0  101M    0  116k    0     0   1210      0 24:19:11  0:01:38 24:17:33          0  101M    0  118k    0     0   1229      0 23:56:37  0:01:39 23:54:58   59     0  101M    0  122k    0     0   1258      0 23:23:30  0:01:39 23:21:51  146     0  101M    0  128k    0     0   1305      0 22:32:57  0:01:40 22:31:17  276     0  101M    0  130k    0     0   1310      0 22:27:47  0:01:41 22:26:06  331     0  101M    0  130k    0     0   1297      0 22:41:18  0:01:42 22:39:36  331     0  101M    0  136k    0     0   1347      0 21:50:46  0:01:43 21:49:03  397     0  101M    0  141k    0     0   1380      0 21:19:25  0:01:44 21:17:41  378     0  101M    0  145k    0     0   1395      0 21:05:40  0:01:46 21:03:54  306     0  101M    0  147k    0     0   1418      0 20:45:08  0:01:46 20:43:22  358     0  101M    0  155k    0     0   1465      0 20:05:11  0:01:48 20:03:23  449     0  101M    0  155k    0     0   1452      0 20:15:59  0:01:49 20:14:10  331     0  101M    0  156k    0     0   1459      0 20:10:09  0:01:49 20:08:20  316     0  101M    0  156k    0     0   1446      0 20:21:01  0:01:50 20:19:11  272     0  101M    0  163k    0     0   1498      0 19:38:38  0:01:51 19:36:47  312     0  101M    0  163k    0     0   1484      0 19:49:45  0:01:52 19:47:53  193     0  101M    0  163k    0     0   1471      0 20:00:16  0:01:53 19:58:23  193     0  101M    0  163k    0     0   1458      0 20:10:58  0:01:54 20:09:04  144     0  101M    0  163k    0     0   1446      0 20:21:01  0:01:55 20:19:06  144     0  101M    0  163k    0     0   1433      0 20:32:06  0:01:56 20:30:10          0  101M    0  163k    0     0   1421      0 20:42:30  0:01:57 20:40:33          0  101M    0  163k    0     0   1409      0 20:53:05  0:01:58 20:51:07          0  101M    0  163k    0     0   1397      0 21:03:51  0:01:59 21:01:52          0  101M    0  163k    0     0   1386      0 21:13:53  0:02:00 21:11:53          0  101M    0  163k    0     0   1374      0 21:25:00  0:02:01 21:22:59          0  101M    0  167k    0     0   1399      0 21:02:03  0:02:02 21:00:01   85     0  101M    0  170k    0     0   1405      0 20:56:39  0:02:03 20:54:36  130     0  101M    0  171k    0     0   1406      0 20:55:46  0:02:04 20:53:42  163     0  101M    0  176k    0     0   1435      0 20:30:23  0:02:05 20:28:18  267     0  101M    0  176k    0     0   1423      0 20:40:46  0:02:06 20:38:40  267     0  101M    0  176k    0     0   1412      0 20:50:26  0:02:07 20:48:19  174     0  101M    0  176k    0     0   1401      0 21:00:15  0:02:08 20:58:07  130     0  101M    0  176k    0     0   1391      0 21:09:18  0:02:09 21:07:09   99     0  101M    0  176k    0     0   1380      0 21:19:25  0:02:10 21:17:15          0  101M    0  176k    0     0   1369      0 21:29:42  0:02:11 21:27:31          0  101M    0  176k    0     0   1359      0 21:39:11  0:02:12 21:36:59          0  101M    0  176k    0     0   1349      0 21:48:49  0:02:13 21:46:36          0  101M    0  176k    0     0   1339      0 21:58:36  0:02:14 21:56:22          0  101M    0  176k    0     0   1329      0 22:08:31  0:02:15 22:06:16          0  101M    0  176k    0     0   1319      0 22:18:35  0:02:16 22:16:19          0  101M    0  176k    0     0   1309      0 22:28:49  0:02:17 22:26:32          0  101M    0  177k    0     0   1310      0 22:27:47  0:02:18 22:25:29   25     0  101M    0  177k    0     0   1300      0 22:38:09  0:02:19 22:35:50   25     0  101M    0  185k    0     0   1347      0 21:50:46  0:02:20 21:48:26  184     0  101M    0  191k    0     0   1376      0 21:23:08  0:02:22 21:20:46  279     0  101M    0  191k    0     0   1366      0 21:32:32  0:02:23 21:30:09  279     0  101M    0  193k    0     0   1374      0 21:25:00  0:02:24 21:22:36  298     0  101M    0  193k    0     0   1365      0 21:33:29  0:02:25 21:31:04  298     0  101M    0  193k    0     0   1355      0 21:43:02  0:02:26 21:40:36  157     0  101M    0  195k    0     0   1360      0 21:38:14  0:02:26 21:35:48   85     0  101M    0  195k    0     0   1360      0 21:38:14  0:02:26 21:35:48  1102
   curl: (18) transfer closed with 105737036 bytes remaining to read

[!] Error installing UMengUShare
[!] /usr/bin/curl -f -L -o /var/folders/8n/vqz11bsn7_3cz_50ks86sx7s2qfzw4/T/d20170227-2837-nt6nnl/file.zip http://dev.umeng.com/files/download/Umeng_SDK_Social_iOS_ARM64_6.3.0.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  101M    0  195k    0     0   1360      0 21:38:14  0:02:26 21:35:48  1102
curl: (18) transfer closed with 105737036 bytes remaining to read

/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:142:in `rescue in execute_command'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:140:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/http.rb:93:in `download_file'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/http.rb:26:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:82:in `block in download'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:157:in `block in ui_action'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:156:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.1.3/lib/cocoapods-downloader/base.rb:80:in `download'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:108:in `download_source'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:75:in `download_request'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader/cache.rb:171:in `download'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader/cache.rb:154:in `block in uncached_pod'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader/cache.rb:181:in `call'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/downloader.rb:42:in `download'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:85:in `titled_section'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:313:in `each'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:157:in `download_dependencies'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:111:in `install!'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/command/update.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.2.0/libexec/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.2.0/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.2.0/libexec/bin/pod:23:in `<main>'"

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 81441bd457fc2f1d8dfadfdc86942e0a707be7df
               master copy - https://github.com/CocoaPods/Specs.git @ 36394abcea618693701d42bf541611ed23aaff4e
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.2.0/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
This looks like an issue with you trying to download the file http://dev.umeng.com/files/download/Umeng_SDK_Social_iOS_ARM64_6.3.0.zip

It's likely a networking issue on your side, this isn't a CocoaPods issue. Please contact Umeng if you're having issues.
