### ISSUE TITLE
Pod dependencies in App extension cause a "Target 'XXX' has frameworks with conflicting names" issue on 1.2.0

### ISSUE THREAD

**Issue by richardshi97** [CocoaPods/CocoaPods#6522]
[ 🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Added `use_frameworks!` to the top of my Podfile to start using swift frameworks in addition to the Objc pods that I have, then ran `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

I get a conflict error: 
[!] The 'Pods-Rave' target has frameworks with conflicting names: gtmsessionfetcher. 

After some digging it seems like 'Firebase/Auth' has a dependency with gtmsessionfetcher, which 'GoogleAPIClient/Drive' also has and is conflicting with. 

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e2d1f38aa812198a279572b1fa4f1ef9cf3ccb94
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.2.0/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

def sharedPods
        pod 'AFNetworking', '~> 2.6'
	pod 'Firebase/Core'
	pod 'Firebase/RemoteConfig'
        pod 'PureLayout'

        # I conflict with GoogleAPIClient/Drive!
	pod 'Firebase/Auth'
end

target "test_issue" do
	sharedPods

        # I conflict with Firebase/Auth!
	pod 'GoogleAPIClient/Drive'
end

target "AppExtension" do
	sharedPods
	pod 'libPusher', '1.6.1'
end

post_install do |installer_representation|
	installer_representation.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
			if target.name == "AFNetworking"
				config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'AF_APP_EXTENSIONS=1']
			end
			if target.name == "GTMSessionFetcher-Core"
				config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'GTM_BACKGROUND_TASK_FETCHING=0', 'GTM_BACKGROUND_UIAPPLICATION=0']
			end
			if target.name == "PureLayout"
				config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PURELAYOUT_APP_EXTENSIONS=1']
			end
		end
	end
	
end
```

**Comment by benasher44** [comment]
Hi @richardshi97! Thanks for the report! I believe Firebase is a binary, is that correct? If that's the case, and it includes gtmsessionfetcher in the binary, then there's nothing CocoaPods can do really. This is the downside to using binary SDKs: resolving clashing dependencies is very difficult.

**Comment by richardshi97** [comment]
Hi @benasher44, would you have any idea why the podfile was working without the 'use_framework!' declaration? Many thanks!

**Comment by benasher44** [comment]
Hm. That is odd. I'll have to dig more, but I'm not sure when I'll get to it. I have a lot on my list at the moment. It's possible there is more to consider around naming when dynamically linking frameworks at runtime, which is why we're throwing the error. But, I'm not so sure on that. When I can, I'll try to get back to you with a better answer.

**Comment by richardshi97** [comment]
Hello @benasher44, did you have time to look at this issue? Many thanks.

**Comment by benasher44** [comment]
I have not yet. It's still on my list though! Apologies!
