### ISSUE TITLE
Difficult to manage CONSISTENCY in terms of dependency versions

### ISSUE THREAD

**Issue by hoangcanhsek6** [CocoaPods/CocoaPods#6527]
For example, I have two private pods and it also have the same dependency 'RealmSwift' 
 **PKDeviceManager_Internal.podspec file**
```
...
spec.dependency 'RealmSwift', '2.4.9'
...
```
and 
**PKGoalTracking_Internal.podspec file**
```
...
spec.dependency 'RealmSwift', '2.4.3'
...
```

**And the Podfile.lock look like this:** 
```
-  PKDeviceManager (2.0.0):
    - RealmSwift (= 2.4.9)
- PKGoalTracking (1.0.0):
    - RealmSwift (= 2.4.3)
```

## The issue is:
If I have a lot of development pods and almost of them have the same dependency (RealmSwift, Alamofire etc.) 
# Expect: 
### When we update a pod to a higher version, I expect to update in in one place (not N podspecs that depend on it).

Could I have any solution to resolve this issue? 
Thanks,

**Comment by benasher44** [comment]
Hi @hoangcanhsek6! Thanks for bringing this up! Do I understand that you want some way to automatically upgrade the RealmSwift dependency set in the `s.dependency` line, which occurs in many of your podspecs, and therefore would need updating in many different repos (one for each podspec)?

**Comment by hoangcanhsek6** [comment]
Hi @benasher44,
Yes, that's my point. 
More clearly: 
Currently, When I need to upgrade the RealmSwift to higher version I have to update the _s.dependency_ line in two podspec files (PKGoalTracking_Internal.podspec, PKDeviceManager_Internal.podspec) 
I really want to update the new RealmSwift version in the Podfile without update the new version in two podspec files. ---> It's too complicate if I have many many repos using RealmSwift.
Is there any way declare the 's.deoendency' line to upgrade the RealmSwift dependency automatically? Or maybe some tricks to do that?

**Comment by benasher44** [comment]
The best way to do that is to have a looser constraint in your podspecs. For example, instead of putting `s.dependency 'RealmSwift', '2.4.3'` (which pins RealmSwift to that specific version), try `s.dependency 'RealmSwift', '~> 2.4'`, which would require at least 2.4 but would allow any version between 2.4 and 3.0 (not including 3.0). This way, you only have lots of friction when doing a major version upgrade, which might be expected anyway.

I hope this helps, and thanks again for bringing this up. Have a great day!

**Comment by hoangcanhsek6** [comment]
Thanks for your answer, but I still confusing that if I need to upgrade the new version of `RealmSwift` to `~> 2.5` (old version is `~>2.4`) , is there anything else that I can do that without update `s.dependency` on many files?

**Comment by orta** [comment]
`~> 2.5` means `2.5 -> 2.9.9999` - so you shouldn't need to do any updates, see this video: https://www.youtube.com/watch?v=x4ARXyovvPc

**Comment by benasher44** [comment]
You can stick with `~> 2.4` if you'd like for sure. The important thing is to have the `~>` operator there, which is what allows your pods to flexibly upgrade.
