### ISSUE TITLE
what for "inherit! :search_paths" ?

### ISSUE THREAD

**Issue by goodyboy6** [CocoaPods/CocoaPods#6537]
i don't understand when should i use inherit! :search_paths ?  or how can i check the difference between none / search_paths  / complete  ?

all i got is:
>inheritance Symbol  The inheritance mode to set.
Available Modes: + :complete The target inherits all behaviour from the parent. + :none The target inherits none of the behaviour from the parent. + :search_paths The target inherits the search paths of the parent only.

but when i test code:
````
target 'CocoaPodsTest' do
    pod 'Mantle', :configuration => 'Debug'
    target 'CocoaPodsTestTests' do
        inherit! :search_paths  #none  #search_paths  # complete
    end
end
````
when i use one of inherit! : #none  #search_paths  #complete , nothing different when i run unit test code:
````ObjC
#import <XCTest/XCTest.h>
#import <Mantle/Mantle.h> 
@interface CocoaPodsTestTests : XCTestCase
@end
````

CocoaPods veriosn 1.1.1

**Comment by dnkoutso** [comment]
Can you please provide a full sample project?

**Comment by dnkoutso** [comment]
Also what version of CocoaPods? Can you please try 1.2.1.beta.1?

**Comment by goodyboy6** [comment]
@dnkoutso  i use 1.1.1, but i think try 1.2.1.beta.1 is ok.

**Comment by dnkoutso** [comment]
can you close issue?

**Comment by goodyboy6** [comment]
@dnkoutso  my question is updated~

**Comment by dnkoutso** [comment]
@goodyboy6 I still don't understand if there is an actual problem or are you asking a question?

**Comment by dnkoutso** [comment]
@goodyboy6 you use `inherit! search_paths` for targets that you want to be able to use imports but not directly link dependencies. This is primarily used for test targets that use the app as the app host.

See this also http://stackoverflow.com/questions/37060065/what-does-inherit-search-paths-do

I am going to close this issue as its not a CocoaPods bug or enhancement.
