### ISSUE TITLE
Problem in pod installing !!!!

### ISSUE THREAD

**Issue by colarex** [CocoaPods/CocoaPods#6545]
I have this problem, Xcode 8 , 
![img_2018](https://cloud.githubusercontent.com/assets/23652412/23832211/7637d438-0741-11e7-97c0-2d5af37bbf63.JPG)
![img_2019](https://cloud.githubusercontent.com/assets/23652412/23832212/768c2e66-0741-11e7-9155-f79675782fba.JPG)

operating system is mac sierra 10.12

**Comment by benasher44** [comment]
Hi @colarex! Thanks for the report! That first screenshot appears to indicate issues with your local network. For the 2nd screenshot, there's not enough info here for us to help debug. I'm going to close this, but please feel free to file a new issue and fully fill out the issue template, if you're still experiencing this issue. When you can do that, we'd be happy to help out! Have a great day!
