### ISSUE TITLE
Import not found

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#6549]
# Report

## What did you do?

pod lib create ElevationAPISwift
Cloning `https://github.com/CocoaPods/pod-template.git` into `ElevationAPISwift`.
Configuring ElevationAPISwift template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and double click links to open in a browser. )

What language do you want to use?? [ Swift / ObjC ]
 > Swift

Would you like to include a demo application with your library? [ Yes / No ]
 > Yes

Which testing frameworks will you use? [ Quick / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > No

Running pod install on your new library.

Analyzing dependencies
Fetching podspec for `ElevationAPISwift` from `../`
Downloading dependencies
Installing ElevationAPISwift (0.1.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `ElevationAPISwift.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'ElevationAPISwift/Example/ElevationAPISwift.xcworkspace'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

## What did you expect to happen?

After replacing ReplaceMe.swift by my class Elevation.swift, and running pod install, import it in ViewController.swift

## What happened instead?

@Import Elevation -> not found

![2017-03-13_06-40-13](https://cloud.githubusercontent.com/assets/1782450/23842905/08ca728a-07b8-11e7-9388-f801cf5d6842.png)

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.4.5
Ruby lib dir : /Users/patrickbodet/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2cd1d7fed524ef57f313242c4a7e792d31458cf3
```

### Installation Source

```
Executable Path: /Users/patrickbodet/.rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'ElevationAPISwift_Example' do
  pod 'ElevationAPISwift', :path => '../'

  target 'ElevationAPISwift_Tests' do
    inherit! :search_paths

    
  end
end
```
## Project that demonstrates the issue

[ElevationAPISwift.zip](https://github.com/CocoaPods/CocoaPods/files/837366/ElevationAPISwift.zip)

**Comment by benasher44** [comment]
Hi there! Thanks for the report! You'll need to import "ElevationAPISwift" instead of "Elevation" because the former is the name of your library. Can you try replacing your import with `import ElevationAPISwift`? Thanks!

**Comment by iDevelopper** [comment]
Thanks for your response! I just got my mistake. I replaced Elevation.swift by ElevationAPISwift.swift (it is not the same in Objective-c) and imported (import ElevationAPISwift). It would be nice if the template could be configured with [the name of the library].swift rather than with a file called ReplaceMe.swift, no? Thanks a lot for all! There is always a response from CocoaPods!

**Comment by benasher44** [comment]
Glad you got it fixed! Interesting idea, but I'm not sure that conveys that "we put a placeholder here and you need to replace it" as well as a file called ReplaceMe.swift. Generally speaking, I'm not sure it's common to have a swift file with the same name as your library in the library itself, and the library in this example doesn't actually need to have a file called ElevationAPISwift.swift to work. So again not a bad suggestion, but I thing what we have now is more clear. Have a great day!
