### ISSUE TITLE
No Pods Founds

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#6551]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

On https://cocoapods.org/ search my pod, I taped ELE to find ElevationAPI

## What did you expect to happen?

See my pod and expand it.

## What happened instead?

SORRY. NO PODS FOUND.

## CocoaPods Environment

N/C

## Project that demonstrates the issue

N/C

![2017-03-13_17-07-23](https://cloud.githubusercontent.com/assets/1782450/23863759/da7a253e-0810-11e7-9a85-d8012096dc2f.png)

**Comment by dnkoutso** [comment]
https://cocoapods.org/pods/ElevationAPI It's there but searching might require time to index it properly? @orta might know about this.

**Comment by iDevelopper** [comment]
But there are a lot of other Pods with the keyword ELE and yesterday I could see it.

**Comment by dnkoutso** [comment]
Hm works for me...

<img width="1242" alt="screen shot 2017-03-13 at 9 22 50 am" src="https://cloud.githubusercontent.com/assets/310370/23865128/e0ee0f0a-07d1-11e7-9d1f-720ca4670356.png">

**Comment by iDevelopper** [comment]
Yes for me too now... Aleatory... Thanks!
