### ISSUE TITLE
CocoaPods swift librairies documentation

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#6552]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

N/C: Question:

In Xcode 8, Apple integrated a comment documentation generator plugin. Select your method or function (Swift) and Menu -> Editor -> Structure -> Add Documentation.

Is this recognized by CocoaPods for Swift librairies?

## What did you expect to happen?

N/C

## What happened instead?

N/C

## CocoaPods Environment

N/C

## Project that demonstrates the issue

Example:

![2017-03-13_18-24-33](https://cloud.githubusercontent.com/assets/1782450/23866850/6ab2e0ce-081a-11e7-87fc-0bbc944b08e9.png)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
