### ISSUE TITLE
Is it possible to update README without pushing new version?

### ISSUE THREAD

**Issue by kkontus** [CocoaPods/CocoaPods#6557]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I added some changes and pushed new version

## What did you expect to happen?

I expected that preview image will be shown

## What happened instead?

Image wasn't shown due to raw = true in github README.md, so I removed it from there.
This is another issue where this happened but I found that after I got that issue. 
https://github.com/CocoaPods/cocoadocs.org/issues/321

## Project that demonstrates the issue

https://cocoapods.org/pods/SwiftCheckboxDialog

So the question is, is it possible to run redeploy so new, updated README from Github is used instead of pushing completely new version just because of the image?

**Comment by orta** [comment]
Nope, it requires a new version to be pushed, otherwise your master README could be out of sync with your tagged version.
