### ISSUE TITLE
Have to set module when using view from cocoapod

### ISSUE THREAD

**Issue by MaikoHermans** [CocoaPods/CocoaPods#6561]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I'm currently trying to create a library by using cocoapods for the first time. It mainly exists out of custom views.

However in order for it to work I need to enter the module name after I set the custom class to the UIView.

for instance this doesn't work: 
![custom view](https://i.stack.imgur.com/BcTqR.png)

While this does work: 
![custom view](https://i.stack.imgur.com/Z2f7B.png)

I doubt that it is supposed to work like this. Shouldn't it set the module automatically?

If so how do you make sure this happens? What am I doing wrong exactly.

The code for it is available [here](https://github.com/MaikoHermans/MHWalkthrough)

 I created a test project in order to test it. I installed my pod by entering this into my `Podfile`

``` ruby
pod 'MHWalkthrough', :path => '~/Path/To/Folder/Containing/My/Pod'
```

**Comment by benasher44** [comment]
Hi @MaikoHermans! Thanks for the report! It makes sense to me that the 1st screenshot would not work, and the 2nd screenshot would work. Why do you think this should not be the case and something should happen automatically?

**Comment by MaikoHermans** [comment]
@benasher44 Thanks for your response.

When I take a look at other pods that mainly contain custom views they don't have to set the Module manually. It will work the moment they set the custom view class.

So I guess what I'm really wondering is why with mine the module needs to be set where other pods work without setting the module. I'm confused on what the reason is for this and I just can't seem to find anything on it really.

I hope that explains it better.

**Comment by benasher44** [comment]
It depends on the context. If you're using your pod view from within your pod, I don't think you need to set the module. Otherwise, you probably do. This also might be different if you don't have `use_frameworks!` enabled.

**Comment by benasher44** [comment]
I'm going to close this, since this doesn't appear to be a CocoaPods bug that we can fix, but it's rather an issue of how custom views work in IB in the context of shared libraries.
