### ISSUE TITLE
pod spec lint gives error of validation relates to AFNetworking

### ISSUE THREAD

**Issue by jagdish24** [CocoaPods/CocoaPods#6562]
Used in pod file.

`	pod 'AFNetworking', '~> 2.0'`

Created dependency in pod spec file.

`  s.dependency 'AFNetworking'`

Now i m going to lint code and push on source which is http
`pod spec lint`

    - ERROR | [iOS] xcodebuild:  XXXX/XXXX/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:51:1: error: illegal redeclaration of property in class extension 'AFNetworkActivityIndicatorManager' (attribute must be 'readwrite', while its primary must be 'readonly')

    - ERROR | [iOS] xcodebuild:  XXXX/XXXX/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:48:12: error: definition of 'AFNetworkActivityIndicatorManager' must be imported from module 'AFNetworking.AFNetworkActivityIndicatorManager' before it is required

**Comment by benasher44** [comment]
Hi @jagdish24! Thanks for the report! Unfortunately, there's not enough info here for us to help debug, so I'm going to close this. If you could please file a new issue and fully fill out the issue template, then we'd be happy to help out! Have a great day!
