### ISSUE TITLE
Missing libpods .a file and Mach-O Linker error

### ISSUE THREAD

**Issue by shanehartman** [CocoaPods/CocoaPods#6564]
After doing a Pod init and Pod install with the Venmo dependency specified within the Pod file, I attempted to build the project. I specified the platform at the top of my pod file as ios 10.2

I pre-cleaned and deleted derived data before each build / run.

I expect the podslib- .a file in my project folder to not be in red. I also expect the build settings architecture to not set to none for SDK and mac os default when I specify ios as the platform.

In order to try to fix these problems, particularly the libpods .a file being missing, I uninstalled cocoa pods and the xcodeproj gem, reinstalled them. also tried removing the master and doing set up again. this problem started on an older laptop. after realizing how many cocoapods and ruby configurations there were, I wiped the hard drive clean and ended up buying a brand new macbook. now on the new macbook I have the same exact issue with a fresh install of everything.

I've tested this with various dependencies. with cocoapod pop I'm finally able to get the app to run but the libpod . a always shows up red / missing. With venmo, I cannot ever get the project to build or run. Even after I change the base sdk to Latest iOS it still fails with a Apple Mach-O Linker error. It says there are missing directories (see attached screenshot).
![screen shot 2017-03-17 at 1 31 01 pm](https://cloud.githubusercontent.com/assets/6888127/24055471/8430a4c4-0b16-11e7-8beb-a30885e11565.png)
 I've spent days / hours trying to resolve this issue.
## What happened instead?
The project fails to build.

   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0221aecc0655403ebf10b1573db3f5616958f556
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, ’10.2’

target 'TestVenmo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestVenmo
  pod 'Venmo-iOS-SDK', '~>1.3'

end



[TestVenmo](https://github.com/shanehartman/TestVenmo)

**Comment by dnkoutso** [comment]
See this https://github.com/venmo/venmo-ios-sdk/issues/121

Not sure if this project is still active: https://github.com/venmo/venmo-ios-sdk/pulse/monthly

This is not a cocoapods issue so I am closing.
