### ISSUE TITLE
Ruby Gem method calls in CocoaPods post_install hook not called on a fresh install.

### ISSUE THREAD

**Issue by tirodkar** [CocoaPods/CocoaPods#6566]
* [X ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Freshly cloned the [EarlGrey project](https://github.com/google/EarlGrey) and ran `Pod Install` on the EarlGreyExample CocoaPods [project](https://github.com/google/EarlGrey/tree/master/Demo/EarlGreyExample). 

## What did you expect to happen?

All Pod libs / frameworks were added and the configuration changes in the EarlGrey gem such as a new `EarlGrey Copy Files` Build Phase was added.

## What happened instead?

All Pod libs / frameworks were added, but the configuration changes were not. After one more `pod install`, the configuration changes were added.

## CocoaPods Environment

No specific environment issue. Present on all projects doing this.

## Project that demonstrates the issue

https://github.com/google/EarlGrey/tree/master/Demo/EarlGreyExample

**Comment by benasher44** [comment]
Hi @tirodkar! Thanks for the report! I cloned the EarlGrey project, and I verified that the `post_install` hook ran on the first `pod install` using CocoaPods 1.2.0. This sounds like an issue that you should bring up in the EarlGrey repo, and I also encourage you to verify that you're using the latest CocoaPods. Best of luck, and have a great day!
