### ISSUE TITLE
CLI creating extra repositories in ~/.cocoapods/repos/ while ignoring existing

### ISSUE THREAD

**Issue by skimgosu** [CocoaPods/CocoaPods#6568]
# Report

## What did you do?

I have two private specs repositories setup with GitLab.
The two repos are named "../x/PodSpecs.git" and "../y/PodSpecs.git".
I have the private spec repos setup for pushing updates:
```
pod repo add customLocalName urlToGit
```
I have the podfile setup correctly with:
```
source "url to git 1"
source "url to git 2"
source 'https://github.com/CocoaPods/Specs.git'
```
I update one of the pods and run:
```
pod repo push customLocalName *.podspec
```
All good, no problems.
I run ```pod install``` on a project that had its dependency updated.
That didn't work so I had to use ```pod update``` to get it to update.. (while CLI tells me use pod repo update but I'm lazy and works anyways?)
This is great and all, until you see some of the lines in the CLI...

## What did you expect to happen?

Nothing special. Everything is functional, but..

## What happened instead?

There is a new repo in ```~/.cocoapods/repos/``` named ```gitlab-podspecs```. If I do more updates to pods, it's not unusual to see ```gitlab-podspecs1``` and ```gitlab-podspecs2```, etc.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : privateSpec1 - git@gitlab.com:xyz/PodSpecs.git @ 2ac21c57872e5cceb2eccb656bd1ea0b85d21890
               master - https://github.com/CocoaPods/Specs.git @ f8317d8cad3a6625d64ab05417b37e65a4060451
               privateSpec2 - git@gitlab.com:abc/PodSpecs.git @ 1d3ca04139a6b139b0c40901c95fa27db407a377
               (**duplicate**) privateSpec2-1 - /Users/me/.cocoapods/repos/abc @ 1d3ca04139a6b139b0c40901c95fa27db407a377
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

I googled a bit and [found this](https://github.com/CocoaPods/Core/issues/170) where you guys previously supported using the local spec name as the source. I think a syntax option like ``` source 'MyLocalSpec', 'url=git@gitlab.com:xyz/PodSpecs.git'``` might solve the issue. You can have it refer to local source for ```pod install``` or use the git URL for ```pod update```?

Also, I think source ```source 'https://github.com/CocoaPods/Specs.git'``` should be implicit in the podfile even if you use additional sources, and a command be offered to explicitly not use CocoaPods/Specs.git as a source. This is based on an assumption that most use cases include the Cocoapod's spec as a source.

**Comment by benasher44** [comment]
Hi @skimgosu! Thanks for the report! This sounds like a bug where CocoaPods has trouble identifying existing specs repos by URL and is creating new ones by mistake. That should definitely be fixed. I can't guarantee when it will be fixed, but I've tagged it appropriately.

As far as `source 'https://github.com/CocoaPods/Specs.git'` being implicit in Podfiles. I think this change seems like it would be innocuous at first, but I think this could get confusing down the line and would break existing Podfiles that don't include that source line. The current situation doesn't add much friction (have to ensure this line is in your Podfile once) and is explicit, so I think it'd be preferable to keep that how it is.

**Comment by skimgosu** [comment]
Hey @benasher44,

I just remembered that I include the username:password in the Git URL for ease of access to the private repos. For example:

```https://someUserName:somePlainTextPassword@gitlab.com/someUserWithPrivateSpecs/PodSpecs.git```

That may be the specific reason as to why it happens.

**Comment by benasher44** [comment]
Thanks for the update!
