### ISSUE TITLE
Please help me！ The privateRepo is error！

### ISSUE THREAD

**Issue by Bofearless** [CocoaPods/CocoaPods#6577]
why？
why？

![image](https://cloud.githubusercontent.com/assets/16445320/24185778/effb9c48-0f0f-11e7-8821-5b5b97ad151b.png)

**Comment by dnkoutso** [comment]
`repo push` will clone your git repo and then try to validate. `lib lint` will use whats on your local path.

Can you please paste the `podspec` and second ensure you have a git tag of `0.0.1` in the repo that provides the podspec.
