### ISSUE TITLE
Linker error: "ld: framework not found Pods_PodsTestApp" after pod install

### ISSUE THREAD

**Issue by lyricsboy** [CocoaPods/CocoaPods#6578]
# Report

## What did you do?

* create a new Workspace (empty, PodsTest.xcworkspace) in a new directory (PodsTest)
* create a new iOS application project in the workspace (PodsTestApp, in its own subdirectory)
* create the Podfile (included below) in the PodsTestApp directory
* run `pod install` in the PodsTestApp directory

## What did you expect to happen?

Project builds and runs correctly.

## What happened instead?

Linker error:
`ld: framework not found Pods_PodsTestApp`

Reference, but no backing file, for `Pods_PodsTestApp.framework` in the PodsTestApp target.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/me/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5c3ef327f56a7f599508de149518d98339663701
```

### Installation Source

```
Executable Path: /Users/me/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
slather               : 2.3.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

workspace '../PodsTest'

target 'PodsTestApp' do
  use_frameworks!
  
  pod 'Fabric'
  pod 'Crashlytics'
end
```

## Project that demonstrates the issue

https://github.com/lyricsboy/PodsTest/commits/master

Note the before and after commits; this could probably be made into an integration test if it's something y'all intend to support.

**Comment by lyricsboy** [comment]
Deleting the invalid reference to `Pods_PodsTestApp.framework` makes the project build and run successfully, but every time I `pod install` again, that reference will come back.

**Comment by benasher44** [comment]
Hi @lyricsboy! Thanks for the report! I've cloned your sample project to try to reproduce do the bug. Here are the steps I did:

```
git clone https://github.com/lyricsboy/PodsTest
cd PodsTest/PodsTestApp
pod install
```

I then opened the workspace in the root of the repo, built, and it built successfully. Maybe try removing your `Pods` directory and giving it another go?

**Comment by lyricsboy** [comment]
Thanks for the sanity check. I can confirm that it is working for me now as well.

The behavior I reported appears to be caused by me trying to build from the *project* instead of the *workspace*. Classic mistake :(

**Comment by benasher44** [comment]
No problem! Glad you got it worked out!

**Comment by fbartolom** [comment]
Could you someone explain what it means to build from the workspace instead of from the project?

**Comment by instafluff** [comment]
@fbartolom He means opening the .xcworkspace file into XCode instead of the .xcodeproj to build and run
