### ISSUE TITLE
iOS8 pod 'FMDB/standalone/FTS', '~> 2.6.2' DB Error: 1 "unknown tokenizer: unicode61

### ISSUE THREAD

**Issue by wusuowei** [CocoaPods/CocoaPods#6582]
I use pod to manage fmdb like this "pod 'FMDB/standalone/FTS', '~> 2.6.2'".
When i add "use_frameworks!" to my Podfile. My app use fmdb search in a FTS database table. It log this error "DB Error: 1 "unknown tokenizer: unicode61"".(The db file in my app used fts unicode61 tokenizer.)
This error only happened on ios8. I build the same code on ios9 and ios10 is work well.

PS：I add "use_frameworks!" to my Podfile is because I want to use some swift Pod lib to my project.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
