### ISSUE TITLE
 CocoaPods generates wrong frameworks search path when merging subspec dependencies from multiple podspec's

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#6584]
🌈
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm noticing that the frameworks search path is not generated correctly in an Xcode workspace is generated from two podspecs with separate subspec dependencies from the same external pod.

1. `git clone git@github.com:paulb777/CocoapodsSubspecBug.git`
1. `cd CocoapodsSubspecBug/Example/`
1. `pod update`
1. `open CocoapodsSubspecBug.xcworkspace/`
1. Command-B to run the CocoapodsSubspecBug-Example scheme. Note that it succeeds.
1. Change the scheme to Root-Example. Command-B and note success.
1. Change the scheme back to CocoapodsSubspecBug-Example
1. Shift-Command-K to clean
1. Command-B and note compiler failure:

`/Users/paulbeusterien/demo/CocoapodsSubspecBug/CocoapodsSubspecBug/Classes/ReplaceMe.m:2:9: fatal error: 'GoogleToolboxForMac/GTMNSDictionary+URLArguments.h' file not found
#import <GoogleToolboxForMac/GTMNSDictionary+URLArguments.h>
        ^
1 error generated.`

## What did you expect to happen?

I expected the framework search path to point to the corresponding version of GoogleToolboxForMac.framework to the scheme.

## What happened instead?

Two GoogleToolboxForMac.frameworks paths were passed to clang and clang used the first, which led to it not finding the right header file.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.11.0.390.gc69c2f50cf-goog
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories :  master - https://github.com/CocoaPods/Specs.git @ d8a949d345cc514c7625f70f9167f09585993511
               paul-specs - sso://user/paulbeusterien/Specs @ ce79542a7e712053dd8eff1cedc4428f72a26b3e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.1.2
cocoapods-try          : 1.1.0
```

## Project that demonstrates the issue

https://github.com/paulb777/CocoapodsSubspecBug

**Comment by dnkoutso** [comment]
@paulb777 I tried your steps using CocoaPods 1.2.1.beta.1 and I was unable to reproduce.

**Comment by dnkoutso** [comment]
This was on Xcode 8.0.0. I do not currently have Xcode 8.2.1.

**Comment by paulb777** [comment]
@dnkoutso Thanks for taking a look. I was able to reproduce on Xcode 8.2.1, 8.3, and 8.0 with 1.2.1.beta.1. 

Are you sure you followed the instructions in exactly the right order?  Steps 5-9 need to go exactly that way to produce the state that leads to the failure.
