### ISSUE TITLE
"Source code for your Pod was not accessible to CocoaPods Trunk"

### ISSUE THREAD

**Issue by pengbins** [CocoaPods/CocoaPods#6585]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
pod trunk push xxxxx.podspec  --allow-warnings --verbose

## What did you expect to happen?
new podspec update to trunk repo

## What happened instead?
```
-> "HTTP/1.1 403 Forbidden\r\n"
-> "Date: Mon, 27 Mar 2017 02:49:32 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 135\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 135 bytes...
-> "{\"error\":\"Source code for your Pod was not accessible to CocoaPods Trunk. Is it a private repo or behind a username/password on http?\"}"
read 135 bytes
Conn keep-alive
[!] Source code for your Pod was not accessible to CocoaPods Trunk. Is it a private repo or behind a username/password on http?
```

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.2 (16C68)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1970efbe132ca942fe28ae5a7e955aae2aa58e2c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
 It's only an issue with CocoaPods the tool while pushing to trunk
After try a few times to push to trunk, it would success  eventually. 
But how can I avoid keep get this error?

**Comment by pengbins** [comment]
The source of my podspec is 

```
s.source = { 
    :http => 'https://ks3-cn-beijing.ksyun.com/ksy.vcloud.sdk/Ios/ksylive_ios_v%s.zip' % s.version,
  }
```

I am trying to update this spec to version 2.0.3, so the url is 
https://ks3-cn-beijing.ksyun.com/ksy.vcloud.sdk/Ios/ksylive_ios_v2.0.3.zip

wget --spider  https://ks3-cn-beijing.ksyun.com/ksy.vcloud.sdk/Ios/ksylive_ios_v2.0.3.zip
Spider mode enabled. Check if remote file exists.
--2017-03-27 12:15:45--  https://ks3-cn-beijing.ksyun.com/ksy.vcloud.sdk/Ios/ksylive_ios_v2.0.3.zip
Resolving ks3-cn-beijing.ksyun.com... 111.206.217.37
Connecting to ks3-cn-beijing.ksyun.com|111.206.217.37|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 139441565 (133M) [application/zip]
Remote file exists.

**Comment by pengbins** [comment]
It is quite similar to this issue https://github.com/CocoaPods/CocoaPods/issues/5234

but this one is not ref to github's release

**Comment by JiaDingYi** [comment]
I met the same problem.My source preserved in oss.
Looking forward to answer.

**Comment by orta** [comment]
These commands work o the server too, so it must be something else

![screen shot 2017-03-29 at 11 40 18](https://cloud.githubusercontent.com/assets/49038/24450879/8038fd78-1474-11e7-9cb7-2337dd742822.png)

I don't have tie to dig in, but this [is the checking code](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/http.rb#L41-L78).

**Comment by pengbins** [comment]
tie --> time ?

**Comment by yeluolei** [comment]
same problem here
```
<- "CONNECT trunk.cocoapods.org:443 HTTP/1.1\r\nHost: trunk.cocoapods.org:443\r\n\r\n"
-> "HTTP/1.1 200 Connection established\r\n"
-> "\r\n"
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.2.0\r\nAuthorization: Token 7f6b8f8ae14c2de10c3ded9de0e28341\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 796\r\n\r\n"
<- "{\"name\":\"BaiduMobStat\",\"version\":\"4.5.0\",\"summary\":\"Baidu Mobile Analysis SDK for iOS.\",\"description\":\"Baidu Mobile Analysis SDK for iOS, Please get the APP Key From Our Site\",\"homepage\":\"https://mtj.baidu.com/\",\"license\":{\"type\":\"Copyright\",\"text\":\"Copyright 2017 Baidu. All rights reserved.\"},\"authors\":{\"apptongji\":\"apptongji@baidu.com\"},\"platforms\":{\"ios\":\"5.0\"},\"source\":{\"type\":\"zip\",\"http\":\"https://mtj.baidu.com/static/cocoapods/BaiduMobStat_V4.5.0.zip\"},\"source_files\":\"BaiduMobStat/BaiduMobStat.h\",\"public_header_files\":\"BaiduMobStat/BaiduMobStat.h\",\"vendored_libraries\":[\"BaiduMobStat/libBaiduMobStat.a\"],\"frameworks\":[\"JavaScriptCore\",\"Security\",\"CoreLocation\",\"SystemConfiguration\",\"CoreTelephony\",\"CoreGraphics\",\"UIKit\",\"Foundation\"],\"libraries\":[\"z\",\"stdc++\"],\"requires_arc\":true}\n"
-> "HTTP/1.1 403 Forbidden\r\n"
-> "Date: Thu, 06 Apr 2017 07:00:55 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 135\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
```

**Comment by yeluolei** [comment]
I resolve this issue by change my zip file url from https to http, this issue seams the validation environment doesn't support some https url.

for example:

doesn't support:
`https://mtj.baidu.com/static/cocoapods/BaiduMobStat_V4.5.0.zip`

support:
`http://mtj.baidu.com/static/cocoapods/BaiduMobStat_V4.5.0.zip`

**Comment by pengbins** [comment]
http works!

**Comment by JiaDingYi** [comment]
not work for me.
our url is always http .

**Comment by yishuiliunian** [comment]
i have the same problem use:
~~~
  s.source = { :http=>"http://iossdks-1253653367.costj.myqcloud.com/QCloudCore.zip" }
~~~

**Comment by feikang** [comment]
when i execute pod trunk me. it works.

**Comment by PoojaChirp** [comment]
I have the same problem. My GitHub repo is a private repo and I can't run the following command -
pod trunk push --allow-warnings --use-libraries --verbose

I get an error stating-
Source code for your Pod was not accessible to CocoaPods Trunk. Is it a private repo

How to fix it?

**Comment by 515783034** [comment]
pod trunk me. it works.
it's just amazing!!!!

**Comment by 0x5e** [comment]
sees to be the network issue on server side. I retried many times then succeed. not `pod trunk me` or http

**Comment by jbarros35** [comment]
does not work at all. same issue here.
private repo of course.
