### ISSUE TITLE
how to ignore warning & show error only when [pod update]

### ISSUE THREAD

**Issue by suihan** [CocoaPods/CocoaPods#6586]
when I use [pod update --silent],cocoapods show a lot of warning like that:
```
[!] Found multiple specifications for `UtilsPlugin4iOS (0.1.1.1)`:
- /Users/huineng/.cocoapods/repos/mogujie-ios-team-mgjpodspec-nodependence/Specs/UtilsPlugin4iOS/0.1.1.1/UtilsPlugin4iOS.podspec.json
- /Users/huineng/.cocoapods/repos/mogujie-ios-team-mgjpodspec-framework/Specs/UtilsPlugin4iOS/0.1.1.1/UtilsPlugin4iOS.podspec.json

```
so I try to use [pod update 1>/dev/null],it seems that cocoapods make waring to a stderr output?
We made multipule specifications in order to ignore dependences in podspec,because it is a waste of time,we declare all dependence in podfile to make [pod update] action faster.

**Comment by suihan** [comment]
when I use [pod update 1>/dev/null],if some error iccur,such as [Unable to satisfy the following requirements],cocoapods will not print the error info which [pod update] will print.

**Comment by dnkoutso** [comment]
An option was added in 1.2.1 (which will be released hopefully this coming week).

https://github.com/CocoaPods/CocoaPods/pull/6497

I am closing this for now since its probably as far we will go.

**Comment by StewartGillen** [comment]
Correction: (note the errant comma after `install!`)
`install! 'cocoapods', :warn_for_multiple_pod_sources => false`

**Comment by leeseawuyhs** [comment]
Fixed this issue:
