### ISSUE TITLE
Cloning into 'master'... Forever

### ISSUE THREAD

**Issue by GioAlba** [CocoaPods/CocoaPods#6589]
Hi,
when I try to run the command "pod setup"  receive:
Setting up CocoaPods master repo
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master
  --progress
  Cloning into 'master'...
  remote: Counting objects: 1157224, done.        
  remote: Compressing objects: 100% (638/638), done.        
  Receiving objects:   6% (69434/1157224), 13.01 MiB | 2.68 MiB/s  

the problem is that it never reaches 100%. He stops at a certain percentage and does not go forward.
How can I fix?

Thanks

**Comment by GioAlba** [comment]
Sorry. I tried many times. the last came to 100%
Fixed thanks

**Comment by benasher44** [comment]
Glad you got it worked out!
