### ISSUE TITLE
xcodebuild error 

### ISSUE THREAD

**Issue by harshkahlon** [CocoaPods/CocoaPods#6590]
Agent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/FBKeyboard.o
/usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentLib/Utilities/FBKeyboard.m:36:58: error: values of type 'NSUInteger' should not
      be used as format arguments; add an explicit cast to 'unsigned long' instead [-Werror,-Wformat]
  [FBLogger logFmt:@"Typing with maximum frequency %lu", freq];
                                                   ~~~   ^~~~
                                                         (unsigned long)
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC build/WebDriverAgent.build/Release-iphoneos/WebDriverAgentLib.build/Objects-normal/armv7/FBKeyboard.o WebDriverAgentLib/Utilities/FBKeyboard.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by dnkoutso** [comment]
@harshkahlon please fill in the proper template and provide a sample project as well as better repro steps.

It's impossible to work with this information. Closing until better instructions provided.
