### ISSUE TITLE
Pods-<Target>-resources.sh echo commands generate output too large for Xcode

### ISSUE THREAD

**Issue by postmechanical** [CocoaPods/CocoaPods#6595]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

While this really is a Xcode bug, it is unlikely to be fixed any time soon, if ever, and thus CocoaPods needs to work around it.

## What did you do?

Build workspace

## What did you expect to happen?

Build succeeds

## What happened instead?

Pods-Target-resources.sh script fails with error due to `echo` on line 48:
```
error: Resource temporarily unavailable
Command /bin/sh failed with exit code 1
```
### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.5.2
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : cocoapods - https://github.com/cocoapods/cocoapods.git @ 6a6df6f01d48b769bb89bc9f7d26bbc312624740
               LPM - git@github.com:lonelyplanet/lpm-specs-ios.git @ 2a89500ce94755688ab621a4dc9a8ce5081dd063
               master - https://github.com/CocoaPods/Specs.git @ 782b74bf2f9c3c131e41a105785e914d046dfdbd
```

### Installation Source

```
Executable Path: /Users/alondon/.gems/bin/pod
```

### Plugins

```
cocoapods-deintegrate   : 1.0.1
cocoapods-plugins       : 1.0.0
cocoapods-search        : 1.0.0
cocoapods-sorted-search : 0.2.4
cocoapods-stats         : 1.0.0
cocoapods-trunk         : 1.1.2
cocoapods-try           : 1.1.0
```

## Project that demonstrates the issue

In any project using CocoaPods replace all `echo` commands that go to stdout in `Pods/Target Support Files/Pods-Target/Pods-Target-resources.sh` with:

```
echo `printf '=%.0s' {1..600}` 
```

Appending `|| true` to those lines works around the issue.

**Comment by dnkoutso** [comment]
@postmechanical this should be fairly easy to make a PR for, want to give it a shot?

**Comment by DanToml** [comment]
This was resolved in https://github.com/CocoaPods/CocoaPods/pull/6635
