### ISSUE TITLE
dyld: Library not loaded: @rpath/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds

### ISSUE THREAD

**Issue by hborders** [CocoaPods/CocoaPods#6596]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I added [Google's IMA SDK Version 3](https://developers.google.com/interactive-media-ads/docs/sdks/ios/) to my project with CocoaPods, but my app crashes on launch in the simulator, and I see the following error:

```
dyld: Library not loaded: @rpath/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds
  Referenced from: /path/to/my/app/My_App.app/My_App
  Reason: image not found
```

[Other Google IMA SDK Version 3 users have the same problem.](https://groups.google.com/d/msg/ima-sdk/QrwiC1JWyD0/_f6K37JXBgAJ)

## What did you do?
I added Google's IMA SDK Version 3 to my projet the same way [Google's](https://github.com/googleads/googleads-ima-ios/blob/master/Objective-C/BasicExample/Podfile) [examples](https://github.com/googleads/googleads-ima-ios/blob/master/Objective-C/AdvancedExample/Podfile) do:

```
pod 'GoogleAds-IMA-iOS-SDK'       , '3.5.0'
```

Then, I deleted my `Podfile.lock` file and `Pods` directory and then ran `pod install`:

```
cd $PROJECT_ROOT
rm -rf Podfile.lock Pods
pod install
```

## What did you expect to happen?

My app launches normally.

## What happened instead?

My app crashes on launch with the following error in the console:

```
dyld: Library not loaded: @rpath/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds
  Referenced from: /path/to/my/app/My_App.app/My_App
  Reason: image not found
```

## Workaround

If I manually add `@executable_path/Frameworks` to my target's `LD_RUNPATH_SEARCH_PATHS`, as instructed by [this comment](http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta#comment67493855_24345546) on [this stackoverflow answer](http://stackoverflow.com/a/24345546/9636) the problem goes away. [Google's example code uses the same workaround.](https://github.com/googleads/googleads-ima-ios/blob/master/Objective-C/AdvancedExample/AdvancedExample.xcodeproj/project.pbxproj#L318)

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.11.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ea7502c16b473994653e3b341ed0221ab8d6c353
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.0
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.1.2
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

I can't include my Podfile at this time, but this is a 100% Objective-C project with static linking.

## Project that demonstrates the issue

I can't include my project at this time, but again, this is a 100% Objective-C project with static linking.

**Comment by hborders** [comment]
I include a bunch of other pods that also use frameworks: `ComScore`, `Crashlytics`, `Fabric`, and `google-cast-sdk`, and I never had this problem with any of them. Could this be an issue with how Google built the `GoogleAds-IMA-iOS-SDK` framework? Even if this is a `GoogleAds-IMA-iOS-SDK` bug, maybe CocoaPods could report during `pod install` that I'm using an incompatible pod.

**Comment by hborders** [comment]
I linked to this issue in a [Google IMA SDK forum reply](https://groups.google.com/d/msg/ima-sdk/QrwiC1JWyD0/y-NdmucnCwAJ).

**Comment by dnkoutso** [comment]
It shouldn't matter, I don't think. Its just a vendored framework that should get linked.

Look into your `xcconfig` files that get generated for your targets, see if you see `-framework "GoogleInteractiveMediaAds"` to ensure it gets linked properly.

Also look at the logs in terms of perhaps you get a warning that the framework is rejected due to inconsistency between the supported architectures.

I tried with CocoaPods 1.2.0 and CocoaPods 1.2.1.beta.1 to consume it with a sample app and it worked.

By default if you make a new app target Xcode adds `@executable_path/Frameworks` as the default runpath to use in your project settings. Ensure this is there in your app project settings too.

**Comment by dnkoutso** [comment]
@hborders:

Executing:

```
~/Development/ios/SampleApp/Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds/GoogleInteractiveMediaAds.framework $ file GoogleInteractiveMediaAds 
```

Gives:

```
GoogleInteractiveMediaAds: Mach-O universal binary with 5 architectures: [x86_64: Mach-O 64-bit dynamically linked shared library x86_64] [i386: Mach-O dynamically linked shared library i386] [arm_v7: Mach-O dynamically linked shared library arm_v7] [arm_v7s] [arm64]
GoogleInteractiveMediaAds (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
GoogleInteractiveMediaAds (for architecture i386):	Mach-O dynamically linked shared library i386
GoogleInteractiveMediaAds (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
GoogleInteractiveMediaAds (for architecture armv7s):	Mach-O dynamically linked shared library arm_v7s
GoogleInteractiveMediaAds (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

It's possible that ComScore, Crashlytics being vendored *static* frameworks versus *dynamic* require the `LD_RUNPATH_SEARCH_PATHS` to be set in your project. Xcode should have done this by default unless your app was created in a much older version of it?

I don't think there is a CocoaPods issue here.

**Comment by hborders** [comment]
Executing:

```
$ file Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework/GoogleCast
```

Gives:

```
Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework/GoogleCast: Mach-O universal binary with 4 architectures: [arm_v7: current ar archive] [i386] [x86_64] [arm64]
Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework/GoogleCast (for architecture armv7):	current ar archive
Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework/GoogleCast (for architecture i386):	current ar archive
Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework/GoogleCast (for architecture x86_64):	current ar archive
Pods/google-cast-sdk/GoogleCastSDK-2.10.4-Release/GoogleCast.framework/GoogleCast (for architecture arm64):	current ar archive
```

So it looks like `google-cast-sdk` does package static archives into its framework.

**Comment by hborders** [comment]
> Xcode should have done this by default unless your app was created in a much older version of it?

My app was created in 2011, so it wasn't set there. I didn't realize this was the default.

> I don't think there is a CocoaPods issue here.

I still think CocoaPods should check `LD_RUNPATH_SEARCH_PATHS` in all targets or at either update it if necessary or emit an error saying it needs to be updated.

**Comment by hborders** [comment]
> Look into your xcconfig files that get generated for your targets, see if you see -framework "GoogleInteractiveMediaAds" to ensure it gets linked properly.

`Pods-MY_APP.debug.xcconfig` has the following line:

```
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Crashlytics/iOS" "${PODS_ROOT}/Fabric/iOS" "${PODS_ROOT}/ComScore/ComScore/iOS" "${PODS_ROOT}/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds" "${PODS_ROOT}/google-cast-sdk/GoogleCastSDK-2.10.4-Release"
```

`GoogleAds-IMA-iOS-SDK` is also present in `HEADER_SEARCH_PATHS`: `"${PODS_ROOT}/Headers/Public/GoogleAds-IMA-iOS-SDK"` and `OTHER_CFLAGS`: `-isystem "${PODS_ROOT}/Headers/Public/GoogleAds-IMA-iOS-SDK"` so I think `GoogleAds-IMA-iOS-SDK` is linked properly

**Comment by dnkoutso** [comment]
> I still think CocoaPods should check LD_RUNPATH_SEARCH_PATHS in all targets or at either update it if necessary or emit an error saying it needs to be updated.

Upon further investigation I was a bit wrong. CocoaPods *does* generate them and *there is* a slight bug.

You don't use `use_frameworks!` in your Podfile do you?

The `LD_RUNPATH_SEARCH_PATHS` will only be generated if `use_frameworks!` is enabled. See https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb#L83

Which then invokes:
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb#L217-L236

Seems like those should be updated if `use_frameworks!` is ON or any consumer target includes any vendored dynamic framework.

**Comment by hborders** [comment]
> You don't use `use_frameworks!` in your Podfile do you?

I don't use `use_frameworks!`. As I mentioned in the original issue, this is a 100% Objective-C project with static linking.

**Comment by dnkoutso** [comment]
Yeap. So yes we can do better here. In the meantime manually adding it to your project is a good thing anyway and should unblock others. I'll see if I can quickly get a PR out to fix this for 1.2.1.

**Comment by hborders** [comment]
Thanks very much! CocoaPods is the best!

**Comment by dnkoutso** [comment]
@hborders PR open. Verified it works locally (I used my SampleApp without `use_frameworks!` and deleted my runtime search paths) but also added a test.
