### ISSUE TITLE
  i can't search 'SKTakaPhoto'

### ISSUE THREAD

**Issue by housenkui** [CocoaPods/CocoaPods#6612]
according to terminal i have successfully publish,but i can't search 'SKTakaPhoto'
![yyyy](https://cloud.githubusercontent.com/assets/5885635/24577245/c87ec84e-16fc-11e7-9668-0cc073ed9652.png)

**Comment by housenkui** [comment]
😂

**Comment by iDevelopper** [comment]
You have to wait for a delay! I can see it actually but your project is redirected to the Github page.

**Comment by housenkui** [comment]
rm ~/Library/Caches/CocoaPods/search_index.json    ，now  i can search  my pod. O(∩_∩)O谢谢。
