### ISSUE TITLE
My friend cannot pod search SKTakePhoto 

### ISSUE THREAD

**Issue by housenkui** [CocoaPods/CocoaPods#6613]
Hello:
pod search SKTakePhoto  do well in my computer.But my friend Cannot  pod search SKTakePhoto .

Another one,i search SKTakePhoto in https://cocoapods.org/   i can get it

  Thanks.

**Comment by adellibovi** [comment]
Probably he has an out-of-date specs locally. Use `pod repo update` to update the specs and then try again to install the pod.

**Comment by housenkui** [comment]
uncle， help me  to try   pod search SKTakePhoto ,then can you get my pod ? Thanks @adellibovi

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by housenkui** [comment]
OK，thanks for your tip.
