### ISSUE TITLE
pod lib lint error with both 'arc/non-arc' and 'prefix_header_contents' configured in .podspec

### ISSUE THREAD

**Issue by ccloong** [CocoaPods/CocoaPods#6616]
I think this is an issue of cocoapods.
It has been tested that if only one of 'arc/non-arc' and 'prefix_header_contents' is configured in .podspec, the 'pod lib lint' will not produce any error. But when both of them are defined in the .podspec, the 'pod lib lint' won't pass due to an error:
- ERROR | [iOS] [MaYuePodDemo/no-arc] xcodebuild: Returned an unsuccessful exit code.

The error really has kept me from going any further for days, I've attached a simple demo to reproduce it.

Please help me with how to make lint pass while both of the two fields mentioned above defined in the .podspec, as I really need both non-arc and prefix_header_contents are configured.

Thanks in advanced!
Ma Yue

# Report

## What did you do?

Run 'pod lib lint'

## What did you expect to happen?

pod validated pass with no error

## What happened instead?

The following build commands failed:
	CompileC /Users/mayue/Library/Developer/Xcode/DerivedData/App-bkctwdmgavbimvbmbwwiqgnewsvx/Build/Intermediates/Pods.build/Release-iphonesimulator/MaYuePodDemo.build/Objects-normal/i386/MaYuePodDemo-dummy.o /private/var/folders/qt/vsv4yzsd4lz1wlpsnb5hry8m0000gn/T/CocoaPods/Lint/Pods/Target\ Support\ Files/MaYuePodDemo/MaYuePodDemo-dummy.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
 -> MaYuePodDemo (0.1.0)
    - WARN  | summary: The summary is not meaningful.
    - ERROR | [iOS] [MaYuePodDemo/no-arc] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [MaYuePodDemo/no-arc] xcodebuild:  Target Support Files/MaYuePodDemo/MaYuePodDemo-prefix.pch:13:9: fatal error: 'MYPodDemo-Header.h' file not found

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 6-leapp-specs - git@10.19.6.155:ios/Leapp-Specs.git @ 637290f337ce4d8c3c7e5aecdec3c0096d47b209
               ccloong - https://github.com/ccloong/MayuePodSpecsRepo.git @ fd03215d76562ecce9535c1ebe73aac2b3e4970c
               LeappIMLib - https://github.com/ccloong/Leapp-IMLibSpecs.git @ b704217500dbd61d560598f0b4902e7b5f9d1cc9
               leappmusic-ios-leapp-specs - https://git.leappmusic.cc/ios/Leapp-Specs.git @ e0cf452e7f420b5d96db3f1f2a30c9e834cde516
               master - https://github.com/CocoaPods/Specs.git @ 186e13b94c5c9de943bd3ac65f617103028613f4
               MayuePodSpecs - https://github.com/ccloong/MayuePodSpecs.git @ fd03215d76562ecce9535c1ebe73aac2b3e4970c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/ccloong/MaYuePodDemo.git

**Comment by RetVal** [comment]
same issue in cocoapods v1.2.1

**Comment by RetVal** [comment]
same issue is happened with cocoapods v1.3.0.beta.2

**Comment by amorde** [comment]
Will re-open since this wasn't ever investigated

**Comment by jottenlips** [comment]
I found a workaround by making a new prefix header for the subspec that is empty.

```
  non_arc_files = "/your/non-arc/files"
  s.exclude_files = non_arc_files
  s.subspec 'no-arc' do |sna|
    sna.requires_arc = false
    sna.source_files = non_arc_files
    sna.prefix_header_file = 'no-arc-Prefix.pch'
  end
```

**Comment by xihuang31** [comment]
Having the same issue at version 1.6.1
