### ISSUE TITLE
Duplicate symbols when framework target and app target depend on the same pod

### ISSUE THREAD

**Issue by vminc** [CocoaPods/CocoaPods#6619]
# Report

## What did you do?

Run the app

## What did you expect to happen?

No duplicate symbol warning.

## What happened instead?
Many duplicate symbols warnings:
Class GADMobileAds is implemented in both .../Xcode/DerivedData/..../AdsKit.framework/AdsKit (0x1169a13e8) and ../MyApp.app/MyApp. One of the two will be used. Which one is undefined.

## CocoaPods Environment

```
use_frameworks!

def admob_pods
  pod 'Google-Mobile-Ads-SDK'
end

target 'AdsKit' do
  workspace 'MyWS'
  project 'AdsKit/AdsKit.xcodeproj'
  platform :ios, '8.0'
  admob_pods
end

abstract_target 'WithAds' do
  platform :ios, '8.0'
  admob_pods
  target 'MY_APP'
...
end
```

**Comment by dnkoutso** [comment]
do you use inherit search paths anywhere? Can you show more of the podfile or provide a sample project? Also can you try CocoaPods 1.2.1.beta.1?

**Comment by vminc** [comment]
I don't have inherit search paths options in the pod file. This occurs with 1.2.1.beta.1. I think the above is the essential part of the pod file that is relevant to this problem. The rest is just for other targets and other pods.

**Comment by blackm00n** [comment]
Have the same issue.

The example project: https://github.com/blackm00n/FabricBug

Run and in the logs see:

```
objc[26850]: Class CLSInternalReport is implemented in both /Users/alexey.kozhevnikov/Library/Developer/Xcode/DerivedData/FabricBug-egedofsvoztkfndoylpqhwzshsai/Build/Products/Debug-iphonesimulator/Foobar.framework/Foobar (0x10f84c908) and /Users/alexey.kozhevnikov/Library/Developer/CoreSimulator/Devices/6AFDC91A-D2A3-4165-9C5D-7747A7B9D898/data/Containers/Bundle/Application/44AB3192-0946-49FD-8BD8-C31C3A45E74C/FabricBug.app/FabricBug (0x10dc2e428). One of the two will be used. Which one is undefined.
```

**Comment by hannesoid** [comment]
I'm having a similar issue with GooglePlaces sdk.

#### Example
Here is a minimal example project: https://github.com/hannesoid/DuplicateSymbolsIssue 

#### Podfile
```ruby
platform :ios, '10.3'

target 'GP' do
  use_frameworks!
  pod 'GooglePlaces'
end

target 'GPF' do
  use_frameworks!
  pod 'GooglePlaces'
end
```
There's a branch where I tried same with `abstract_target`

#### Logs
Similar logs of the form  `Class GMSAutocompleteResultsViewController is implemented in both …/Library/Developer/Xcode/DerivedData/GP-bwyegobhixkihmeuknrdbpdrhkwc/Build/Products/Debug-iphonesimulator/GPF.framework/GPF (0x10e6ac360) and …/Library/Developer/CoreSimulator/Devices/294199C5-9818-4971-9E8F-A17ACBB74D75/data/Containers/Bundle/Application/D0AD7A15-BCF7-4566-A1BF-1BE7058529FF/GP.app/GP (0x10bbd8508). One of the two will be used. Which one is undefined.`

**Comment by nikolaypoq** [comment]
What is stale? Stop do it! I just don't have time!

**Comment by combinatorial** [comment]
This is still an issue in 1.3.1

**Comment by LiohAu** [comment]
I think I am also facing the same issue..

**Comment by paulb777** [comment]
With CocoaPods 1.4.0, use the `static_framework` podspec attribute introduced in #6811 to depend on static library frameworks.

**Comment by combinatorial** [comment]
That issue is for the podspec it does not seem to address creating static libraries via a Podfile attribute.

**Comment by paulb777** [comment]
Oh I see. Static framework merging needs to happen based on multiple Podfile target's being built into the same app.
