### ISSUE TITLE
fatal error: '*****-Swift.h' file not found

### ISSUE THREAD

**Issue by Lucashuang0802** [CocoaPods/CocoaPods#6620]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I am trying to add Swift files to an existing Objective-C pod, which is published for a while. However, I keep getting "fatal error: '***-Swift.h' file not found" by running `pod lib lint ***.podspec --allow-warnings --verbose` The project compiles fine in XCode as I think the `***-Swift.h` is generated prior the point where XCode gets to the actual compilation with ObjC and Swift codes.

## What did you do?

- Add Swift files to existing Objective-C pod
- run `pod lib lint ***.podspec --allow-warnings --verbose`

## What did you expect to happen?

Expect to pass the validation

## What happened instead?

It throws fatal error: '*****-Swift.h' file not found

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e1f5057d680f73612016074d96ffef96f164a81a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/opentok/accelerator-core-ios/tree/cocoapods
Due to the library we use is too large, you will need to download from here(https://tokbox.com/developer/sdks/ios/) and place it to the root directory. Then you are good to go. 😃

**Comment by kratijain-flipkart** [comment]
I am facing the exact same issue with my pod which has both Swift and objc source files. What can be done to fix this ?

**Comment by rahulOYO** [comment]
I am facing the same issue. Any workaround to fix this?
