### ISSUE TITLE
clang: error: no such file or directory: 'UIKit'

### ISSUE THREAD

**Issue by karthinalliyappan** [CocoaPods/CocoaPods#6622]
![screen shot 2017-04-05 at 4 14 07 pm](https://cloud.githubusercontent.com/assets/26541759/24702098/f06f98bc-1a1a-11e7-8c70-f64463712f74.png)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
