### ISSUE TITLE
App extension and the Container App share the code without double size the package

### ISSUE THREAD

**Issue by WalterCreazyBear** [CocoaPods/CocoaPods#6624]
# Report

## What did you do?
This is my demo PodFile. And the pod install just work fine. But this will double size my package. In our real project, the size is almost 100M. So double size is not allowed!
```
def common_pod
    pod 'MJExtension','3.0.10'
    pod 'YYModel','1.0.4'
    pod 'AFNetworking','3.0.4'
    pod 'YYText','1.0.7'
    pod 'SDWebImage'
    pod 'Objection', '1.6.1'
    pod 'lottie-ios'
    pod 'Protobuf'
    pod 'Toast', '~> 3.1.0'
    pod 'YapDatabase'
    pod 'SAMKeychain'
end

#main app
target 'BearDS' do
    # use_frameworks!
    common_pod()
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    pod 'PureLayout'
    pod 'MLeaksFinder'
    pod 'UIView+Positioning', '1.0'
end

#imessage extension
target 'BearDSiMessage' do
    common_pod()
end

```

## What did you expect to happen?
I expect App extension and the Container App share the code without double size the package!

## What happened instead?
It seem's like the app extension just copied the pod spect.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.9.2
Ruby lib dir : /Users/mac/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9b0404e49349a89788a947abc489b3ad449dd642

```

### Installation Source

```
Executable Path: /Users/mac/.rvm/rubies/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


def common_pod
    pod 'MJExtension','3.0.10'
    pod 'YYModel','1.0.4'
    pod 'AFNetworking','3.0.4'
    pod 'YYText','1.0.7'
    pod 'SDWebImage'
    pod 'Objection', '1.6.1'
    pod 'lottie-ios'
    pod 'Protobuf'
    pod 'Toast', '~> 3.1.0'
    pod 'YapDatabase'
    pod 'SAMKeychain'
end

#main app
target 'BearDS' do
    # use_frameworks!
    common_pod()
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    pod 'PureLayout'
    pod 'MLeaksFinder'
    pod 'UIView+Positioning', '1.0'
end

#imessage extension
target 'BearDSiMessage' do
    common_pod()
end
```

**Comment by benasher44** [comment]
Hi @WalterCreazyBear! Thanks for the report! Could you please share a sample project? Thanks!

**Comment by WalterCreazyBear** [comment]
hi, I had make a demo: [PodDemo](https://github.com/WalterCreazyBear/PodDemo.git)
In this demo, I have add a today extension and a iMessage extension. And if I add some spec in the extension, the size will change a lot. It seem's like the container app and the extension can't share code. They just copy from the same one.
The size of the product with container app + iMessage with spec + today with spec is 27.5
The size of the product with container app + iMessage with spec is 18.5
The size of the product with container app is 9.5
Thanks😄

**Comment by benasher44** [comment]
@WalterCreazyBear those numbers sound reasonable to me since each time you're subtracting an executable (first you subtract the today binary to get 18.5, then you subtract both iMessage binary and spec). You can see exactly what gets built if you have a look in your app's derived data folder. Use `find` on your derived data folder, and you should be able to see if there are any duplicate frameworks.

**Comment by benasher44** [comment]
@WalterCreazyBear hope you were able to understand what was going on here. Thanks for closing this out!
