### ISSUE TITLE
Use modulemaps for static libraries to use fewer frameworks

### ISSUE THREAD

**Issue by hborders** [CocoaPods/CocoaPods#6626]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Supposedly, we can import static libraries into Swift projects by using a modulemap. Maybe CocoaPods could build that map for us?

http://blog.bjhomer.com/2015/05/defining-modules-for-custom-libraries.html?m=1

**Comment by dnkoutso** [comment]
@segiddins ths is an old issue but is it covered by the Swift static libraries work in 1.5.0?

**Comment by segiddins** [comment]
Yup! Enabling modular headers for a static library will get you a module map
