### ISSUE TITLE
I can't receive the email of register

### ISSUE THREAD

**Issue by HJaycee** [CocoaPods/CocoaPods#6633]
I am the owner of pods  'JCAlertView'. I changed my macbook. So when I use 'pod trunk register hjaycee@163.com',  I can't receive the email. Is there any way to delete this pods and I add a new one use a new emall acount?

**Comment by dnkoutso** [comment]
Please open an issue at the https://github.com/CocoaPods/cocoapods-trunk repo.

**Comment by xclidongbo** [comment]
@dnkoutso  I cant receive the email of register,too.
