### ISSUE TITLE
Unable to install cocoa pods in Mac Mini Sierra.

### ISSUE THREAD

**Issue by VijayKZakkula** [CocoaPods/CocoaPods#6637]
Hi Guys,

I am unable to install the cocoapods on Mac mini which is showing an error message as showed in below. I got the same issue with http://rubygems.org. However, i am able to access the url "https://rubygems.org/latest_specs.4.8.gz" on browser explicitly.  Requesting to please help me out from this issue. 

sudo gem install -n /usr/local/bin cocoapods --source https://rubygems.org
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)

Kindly find the my current mac environment details below.
Mac Mini with sierra(10.12.1)
current gem version installed in mac: 2.0.14.1

Thanks in Advance

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
