### ISSUE TITLE
"pod spec lint" failed for compiler error  

### ISSUE THREAD

**Issue by jagdish24** [CocoaPods/CocoaPods#6638]
Command fired to validate pod spec file, 
`pod spec lint XXXX.podspec --verbose --no-clean --allow-warnings --use-libraries`

And i received below error 

```
The following build commands failed:
	CompileC /Users/ciright/Library/Developer/Xcode/DerivedData/App-ebjuwogmrpmvrhgqgyhwxxpntpsb/Build/Intermediates/Pods.build/Release-iphonesimulator/XXXX.build/Objects-normal/i386/FILENAME.o XXXX/XXXX/XXXXTests/FILENAMETest.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

[!] The spec did not pass validation, due to 1 error.
```
Here i have put my pod spec file. 
https://github.com/CocoaPods/CocoaPods/issues/6567

Please give me solution.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
