### ISSUE TITLE
email:xxx@163.com   can't receve verification email  from  pod trunk register xxx@163.com 'my'

### ISSUE THREAD

**Issue by fanxiangyang** [CocoaPods/CocoaPods#6640]
1.i have a pod  ,i want update version    pod trunk  push FanKit.podspec   
2.i session ,and i  
pod trunk register xxx@163.com 

3.than than  i  can't fond  verification email,my Dustbin email   and other ,all not fond Email

**Comment by orta** [comment]
I've cleaned up a bunch of blocks due to rejections - probably worth trying again.

**Comment by fanxiangyang** [comment]
i cleaned  some bunch,it ok ,thanks

**Comment by isaced** [comment]
I still can't.

**Comment by fanxiangyang** [comment]
1. `gem list --local` 
```
claide (1.0.1, 1.0.0)
cocoapods (1.2.1)
cocoapods-core (1.2.1)
cocoapods-deintegrate (1.0.1, 1.0.0)
cocoapods-downloader (1.1.3, 1.0.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.2.0)
cocoapods-try (1.1.0, 1.0.0)
colored (1.2)
colored2 (3.1.2)

```
2.delete old `cocoapods-*`   than  it work 
```
sudo gem uninstall cocoapods-core

sudo gem uninstall cocoapods-deintegrate
    ***************

```

3.or you can Uninstall All  cocoapods ，again install

**Comment by isaced** [comment]
It doesn't work. @fanxiangyang

**Comment by fanxiangyang** [comment]
so  i also don't known, @isaced

**Comment by isaced** [comment]
Today I can receive the mail again 🤤
