### ISSUE TITLE
CocoaPods install issues - Argument list too long - curl

### ISSUE THREAD

**Issue by davidgrigoryan92** [CocoaPods/CocoaPods#6641]
## I want to use the Pods on all targets - Please help

ℹ  I have almost 300 targets in my project. In Podfile, I create a `def`  for the pod dependencies and deliver this `def` in the targets. 
e.g. 
def pods_my_project
    pod 'AFNetworking', 
    pod 'SDWebImage', 
    pod 'UIViewController+Routing', 
    pod 'MagicalRecord'
    pod 'GoogleMaps'
    pod 'Parse'
    pod 'Vertigo'
    pod 'Fabric'
    pod 'Crashlytics'
    pod "VK-ios-sdk"
    pod 'EasyMapping'
    pod "XCDYouTubeKit", '~> 2.5'
    pod 'AKNumericFormatter'
    pod 'libextobjc'
    pod 'NSDate-Escort'
    pod 'Google/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end

target 'Абакан' do
  pods_my_project

end

target 'Азнакаево' do
  pods_my_project

end

target 'Азов' do
  pods_my_project

end
.........etc.

## I want to be successfully added all Pods in all targets.
And for this I do `pod install`

## When i use this on small amounts of targets(f.e.x. 20), working fine, but in 300 targets gives an error message

ℹ ### Error

```
Errno::E2BIG - Argument list too long - curl
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/sender.rb:26:in `spawn'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/sender.rb:26:in `curl'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/sender.rb:17:in `send'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb:48:in `block (2 levels) in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb:32:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/hooks_manager.rb:109:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/hooks_manager.rb:101:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/hooks_manager.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/installer.rb:495:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/installer.rb:474:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/installer.rb:121:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Argument+list+too+long+-+curl&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

## CocoaPods Version

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1.rc.1/lib/cocoapods.rb

## Xcode Version
Version 8.3.1 (8E1000a)

------------------------------------------------
[Podfile.zip](https://github.com/CocoaPods/CocoaPods/files/912899/Podfile.zip)

**Comment by dnkoutso** [comment]
Interesting, add this to your `Podfile`:

```ruby
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
```

**Comment by segiddins** [comment]
This belongs over on https://github.com/CocoaPods/cocoapods-stats

**Comment by davidgrigoryan92** [comment]
@dnkoutso  Thanks, it helped me, now pods works ! ! !
