### ISSUE TITLE
podfile.lock conflict with '

### ISSUE THREAD

**Issue by duan007a** [CocoaPods/CocoaPods#6644]
every time when I execute command "pod update",the podfile.lock file has a pair of strange " ' ' ",like this   LibraryName: '00486c646f8eaca9c6cd4f436772794dd6a95ac2',and conflict with other has no symbol of " ' "

**Comment by aksswami** [comment]
I am also facing the same issue with Cocoapod version `1.2.1`. Every time I execute `pod update` it removes quote for specific pod only.

```
-  ObjectMapper: '042708195cc46c20871cbcbec0453826398273fd'
+  ObjectMapper: 042708195cc46c20871cbcbec0453826398273fd
```

**Comment by aksswami** [comment]
Thanks @duan007a. I almost forgot this issue until I saw notification for your reply.
