### ISSUE TITLE
How to report error if CP version is lower than Podfile.lock

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#6646]
I had update my CP version to a lastest version before a few days, but I found many guys in my team do not update their CP. So the Podfile.lock always change the version.

I hope there is a way to lock the CP version, if somebody use the CP's version is lower than Podfile.lock, they should get a error to let they update their CP version.

**Comment by orta** [comment]
This sounds like a good idea for a plugin 👍
