### ISSUE TITLE
Couldn't load project after `pod install`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#6647]
I found I often get a error `Couldn't load project` after `pod install`, but it does not fail every time.

I can not found the reason and must be reopen the workspace.

How to solve it?

**Comment by benasher44** [comment]
Hi @Whirlwind. Thanks for the report! Hi there! Unfortunately, there's no info here we can use to help debug your issue, so I'm going to close this. If you could please file a new issue and fully fill out the issue template, we'd be happy to help you out. Have a great day!

**Comment by benasher44** [comment]
I have heard of people encountering this though, and they were able to fix it by clearing various caches. Unfortunately, I don't have the issue number handy.
