### ISSUE TITLE
Create xctest target using cocoapods

### ISSUE THREAD

**Issue by Usipov** [CocoaPods/CocoaPods#6649]
Hello! Thanx for the amazing tool you've created!

**Story**
I often use developement pods. Recently I confronted an issue of stroing tests next to protocols and implementations
```
-Service
--Service.swift
--ServiceImpl.swift
--ServiceSpy.swift
--ServiceTests.swift
```

**What I tried**
I did manage to sepate sources from test files via subscpecs in my podspec
```
  s.subspec 'Sources' do |sc|
    sc.source_files  = "sources/*/*.swift"
    sc.exclude_files = "sources/*/*{Tests,Spy,Stub}.swift"
  end

  s.subspec 'Tests' do |sc|
    sc.source_files = "sources/*/*{Tests,Spy,Stub}.swift"
    sc.frameworks = 'XCTest'
  end
```

I also did manage to link those subspecs against different targets in my workspace: sources to the main target, tests to the test target.
```
target 'MainTarget' do
  pod 'DevelopementPod/Sources', :path => '../DevelopementPod'
end

target 'MainTarget Tests' do
  pod 'DevelopementPod/Tests', :path => '../DevelopementPod'
end
```

**What happened**
However, cocoapods creates a framework target (not an xctest target) from sources specified in developement pod's podspec. That means I cannot run tests on `ServiceTests.swift`. If I could create and xctest target, I would add that test bundle to my main target's scheme. 

**Question**
Is there a way to create an xctest target using cocoapods?

**Comment by DanToml** [comment]
Currently, this is not really possible, however, @dnkoutso is currently working on this (https://github.com/CocoaPods/Core/pull/369). I don't see an existing umbrella issue so I'll leave this issue open for discussion.

**Comment by orta** [comment]
Support just hit master https://github.com/CocoaPods/CocoaPods/pull/6703
