### ISSUE TITLE
pod lib create error

### ISSUE THREAD

**Issue by tangzhentao** [CocoaPods/CocoaPods#6652]
## What did you do?

 Run `pod lib create Share`

## What did you expect to happen?

create a Share lib。

## What happened instead?

faild to creat pod lib Share and output:
Cloning `https://github.com/CocoaPods/pod-template.git` into `Share`.
Configuring Share template.
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- colored (LoadError)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tang/github/Share/setup/TemplateConfigurator.rb:2:in `<top (required)>'
	from ./configure:5:in `require_relative'
	from ./configure:5:in `block in <main>'
	from ./configure:4:in `each'
	from ./configure:4:in `<main>'

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3 (8E162)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

**Comment by annjose** [comment]
I got the same error when I didn't have the `colored` gem installed on my machine. Can you run the command `gem install colored` and try again?

**Comment by orta** [comment]
Oh interesting, we don't ship with coloured in CP anymore, uses `colored2` - can you make an issue or pr to cocoa pods/pod-template for this?

**Comment by annjose** [comment]
Thanks for the info @orta - I have submitted the PR https://github.com/CocoaPods/pod-template/pull/207.

**Comment by startupthekid** [comment]
I'm experiencing a similar crash on `pod lib create [name]`.

/myfolder/myproject/setup/MessageBank.rb:45:in `welcome_message': undefined method `underline' for #<String:0x007fe34b8675a0> (NoMethodError)
	from /myfolder/myproject/setup/TemplateConfigurator.rb:71:in `run'
	from ./configure:9:in `<main>'

**Comment by sush4** [comment]
Same crash on pod lib create [name].
/Users/Desktop/someting/setup/MessageBank.rb:45:in `welcome_message': undefined method `underline' for #<String:0x007f8029274290> (NoMethodError)
Did you mean?  underlined
               underlined!
from /Users/Desktop/someting/setup/TemplateConfigurator.rb:71:in `run'
	from ./configure:9:in `<main>'

**Comment by appbanana** [comment]
faild to creat pod lib Share and output:
To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
/Users/JQC/Desktop/业务组件/FMMine/setup/MessageBank.rb:45:in `welcome_message': undefined method `underline' for #<String:0x007fd0a10626f0> (NoMethodError)
Did you mean?  underlined
               underlined!
	from /Users/JQC/Desktop/业务组件/FMMine/setup/TemplateConfigurator.rb:71:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`

CocoaPods Environment 1.2.1
cocoapods (1.2.1)
cocoapods-core (1.2.1)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.3)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.2.0, 1.1.2)
cocoapods-try (1.1.0)

**Comment by Insofan** [comment]
@sush4 I have the same crash. Have you fixed it?

**Comment by MyroMac** [comment]
PR to fix this issue is up: https://github.com/CocoaPods/pod-template/pull/208

**Comment by tangzhentao** [comment]
@annjose Thank you. I fixed the "colored (LoadError)" .  But I encounted another problem, when I run "pod lib create Share". output:
------------------------------

To get you started we need to ask a few questions, this should only take a minute.

2017-04-16 12:00:23.595 defaults[885:16979] 
The domain/default pair of (org.cocoapods.pod-template, HasRunbefore) does not exist
If this is your first time we recommend running through with the guide: 
/Users/tang/github/Share/setup/MessageBank.rb:45:in `welcome_message': undefined method `underline' for #<String:0x007fa21685d788> (NoMethodError)
Did you mean?  underlined
               underlined!
	from /Users/tang/github/Share/setup/TemplateConfigurator.rb:71:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

**Comment by MyroMac** [comment]
@tangzhentao the problem has been identified and a fix has been produced. Just waiting for code review and the fix should be merged in the master branch soon.

**Comment by tangzhentao** [comment]
@MyroMac fixed! Thank you!

**Comment by appbanana** [comment]
I slove it.  I run the command ''sudo gem install fastlane''  to update my another plug-in fanstlane. I hope it can help you.

**Comment by tangzhentao** [comment]
@appbanana Thank you for telling me your solution. Now "pod lib create " works.

**Comment by avangel** [comment]
As of Cocoapods version 1.5.3, I got `SecKeychainSearchCopyNext` *error* failing the `pod lib create` command. I solved it by updating with `sudo gem update xcodeproj`. Then it works as expected.

**Comment by patniemeyer** [comment]
> `sudo gem update xcodeproj`

I'm getting the `SecKeychainSearchCopyNext` error with the latest Codoapods (1.6.1) and the latest xcodeproj.  I haven't seen any issues yet but it concerns me.
