### ISSUE TITLE
CocoaPods Website Search not working

### ISSUE THREAD

**Issue by michaelsilvers** [CocoaPods/CocoaPods#6654]
# Report

## What did you do?

Went to the website and searched various pod names (AlamoFire, XModeAPI) in the search bar at the top of the page.  No results were found.

## What did you expect to happen?

I expected Pods related to the search terms to be returned.

## What happened instead?

Nothing.  No results were returned.

## CocoaPods Environment

https://cocoapods.org

**Comment by dnkoutso** [comment]
Back online.

**Comment by pmiotto** [comment]
Not working for me. The search results were empty. Tried different browsers and computers.
![screen shot 2017-04-26 at 10 57 35 am](https://cloud.githubusercontent.com/assets/10111956/25413645/304f1746-2a6f-11e7-9e44-55b8d15c45a5.png)

**Comment by AmirDaliri** [comment]
me2

**Comment by dpalme3160** [comment]
broken again

**Comment by sivatamilmani** [comment]
Broken again

**Comment by maxim04** [comment]
+1

**Comment by niazoff** [comment]
Likewise

**Comment by yamiscott** [comment]
Hello, there's a JS error on the search:

> XMLHttpRequest cannot load https://search.cocoapods.org/api/v1/pods.picky.hash.json?query=flurry&ids=20&offset=0&sort=quality. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cocoapods.org' is therefore not allowed access. The response had HTTP status code 503.

**Comment by dpalme3160** [comment]
Still broke

**Comment by markfilter** [comment]
Glad it is not just me...Still not working.

**Comment by DanToml** [comment]
It was back up last night, I'll roll it again now. I've also been trying to get a more long term fix in place

**Comment by sabrefm1** [comment]
also not working for me

**Comment by yamiscott** [comment]
If you guys still want to search (granted it's not as helpful, but you can still look for pods and find the url of the pods for further details), you can use the "pod search" command. WARNING! It takes a while because it's searching everything from the master repo. Use --simple to only search on title.

eg:
pod search flurry --simple

you can even filter by platform using --ios --tvos --osx --watchos

**Comment by indrekru** [comment]
Still not working, what is going on here? 
Then there's this place:
http://cocoapods.wantedly.com/

**Comment by bermanapps** [comment]
This is still not working for me. Its crazy?!?

**Comment by alexwillingham** [comment]
down atm?

**Comment by bermanapps** [comment]
dunno. Its just not working.

**Comment by truebucha** [comment]
again not working

**Comment by truebucha** [comment]
http://cocoapods.wantedly.com/
Seems that it shows not all pods

**Comment by jonauz** [comment]
Not working now again.

**Comment by Abderezai** [comment]
not working again, tried Chrome and IE.

**Comment by annjawn** [comment]
Not working !! 😩 Chrome/Safari

**Comment by Abderezai** [comment]
I just google Cocopods + "name of pod or keyword" and it brings up the page I need.
Strange that it is down tho

**Comment by annjawn** [comment]
It's working now though (as of 6/13 4:30 PM PST)

**Comment by alaeddineG** [comment]
Is not working anymore now ( 6/15 2:48 PM UTC )

**Comment by RaphaelReiter** [comment]
not working :/

**Comment by scr0** [comment]
bump

**Comment by nsnick** [comment]
not working

**Comment by jchon258** [comment]
bump

**Comment by orta** [comment]
I'm locking this, we know that the search goes down pretty often - and are in the process of getting more resources for the search engine, but I'm afraid these things just take time.
