### ISSUE TITLE
Multiple includes with the same name creates insuppressible warning

### ISSUE THREAD

**Issue by kylefleming** [CocoaPods/CocoaPods#6657]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a pod library with multiple headers with the same name (in different folders). The podspec includes `header_mappings_dir` in order to preserve the folder structure.

This only happens when the library is installed without `use_frameworks!`.

## What did you expect to happen?

No warnings to arise.
All headers to be in the `project` category of Xcode's `Headers` section in `Build Phases`.

## What happened instead?

A warning is created for each duplicate file. However, since it's a Xcode Dependency Analysis Warning, there is no way to suppress it. It's user-facing since these insuppressible warnings pollute the user's project.

![screen shot 2017-04-16 at 11 17 06 am](https://cloud.githubusercontent.com/assets/192120/25073298/6c2c45ce-2298-11e7-8054-07eacdb16bd6.png)

Since CocoaPods is handling these headers anyways by copying them into the `Pods/Headers` folder, I would expect the headers to be in the `project` category in Xcode

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.5.2
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.1 (8E1000a)
         Git : git version 2.12.2
Ruby lib dir : /Users/kyle/.rvm/rubies/ruby-2.3.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 410ec41773d896aeafaa6a1827606841a06209ff
```

### Installation Source

```
Executable Path: /Users/kyle/.rvm/gems/ruby-2.3.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# use_frameworks!

target 'CocoaPodsDuplicateHeaderTest_Example' do
  pod 'CocoaPodsDuplicateHeaderTest', :path => '../'
end
```

## Project that demonstrates the issue

https://github.com/kylefleming/CocoaPodsDuplicateHeaderTest

**Comment by NinoScript** [comment]
🌈 **I have some new information about this issue**

This is also happening to me as a user when using PubNub's pod **with** `use_frameworks!` .
They also have multiple files with the same name in different folders.

Here's the Dependency Analysis Warning text:
```
Check dependencies

Warning: Multiple build commands for output file /Users/ninoscript/Library/Developer/Xcode/DerivedData/lets-talk-business-ios-bspamstmoefskmbhnccygfjtcrpd/Build/Products/Debug-iphonesimulator/PubNub/PubNub.framework/Headers/PubNub.h
```

These are the files:
https://github.com/pubnub/objective-c/blob/master/PubNub/PubNub.h
https://github.com/pubnub/objective-c/blob/master/Framework/PubNub/PubNub.h
https://github.com/pubnub/objective-c/blob/master/Support/Fabric/Headers/PubNub.h

I hope this is helpful to reproducing the issue.

**Comment by kylefleming** [comment]
This still exists on `1.3.0.beta.3`.
