### ISSUE TITLE
Simple pod with static library in not uploaded (Link fails)

### ISSUE THREAD

**Issue by Rostyk** [CocoaPods/CocoaPods#6660]
# Report

## What did you do?

pod trunk push

    Pod::Spec.new do |s|
      s.name     = 'Testlib'
      s.version  = '1.0.5'
      s.license  = 'BSD'
      s.summary  = 'Test statis lib'
      s.description  = 'Pod to test static library as dependency'
      s.homepage = 'https://maliwan.net'
      s.author       = 'Ross'
      s.source   = { :git => 'https://github.com/Rostyk/Testlib.git', :tag => s.version.to_s }
      s.preserve_paths = '*.a'
      s.libraries = 'testlibraryrelease'
      s.xcconfig     =  { 'LIBRARY_SEARCH_PATHS' => '"$(PODS_ROOT)/Testlib"' }
      s.platform = :ios
    end

## What did you expect to happen?

upload the pod to trunk 

## What happened instead?

The following build commands failed:
	Ld /Users/Rostyslav.Stepanyak/Library/Developer/Xcode/DerivedData/App-hhjmwqqmryghipdyvuqyiatmdkcg/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
	Ld /Users/Rostyslav.Stepanyak/Library/Developer/Xcode/DerivedData/App-hhjmwqqmryghipdyvuqyiatmdkcg/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386
(2 failures)
 -> Testlib (1.0.5)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)

[!] The spec did not pass validation, due to 1 error.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run: 
    `echo "2.3" > .swift-version`.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/Rostyslav.Stepanyak/.rvm/rubies/ruby-2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fdbed6ad3f406cc135f332ccd75a4b9466b70e71
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/Rostyk/Testlib

**Comment by Rostyk** [comment]
Also

    lipo -info testlibraryrelease.a
show armv7 armv7s i386 x86_64 arm64. I'm sure all the architectures inside the library are conrrect cause when I link it manually in xCode project its works.

**Comment by george-luofz** [comment]
hi! Have you solved the problem? i meet this too. please help!

**Comment by Rostyk** [comment]
Yes, I solved that. I'm away from desk, gonna share the solution.
Add me and name in skype: rostyslav.stepanyak
I'll be online in 6hours

пʼятниця, 2 червня 2017 р. користувач Luo fuzhong <notifications@github.com>
написав:

**Comment by Rostyk** [comment]
It had nothing to do with architectures of the lib.
The pod spec was wrong, in my case "s.libraries" should have contained "lib" prefix.

Take a look at the public repo: [protobuf](http://github.com/Rostyk/Protobuf)
It's a public repo with fixed podspec.
