### ISSUE TITLE
Pod trunk push issue

### ISSUE THREAD

**Issue by Insofan** [CocoaPods/CocoaPods#6661]
Report

 What did you do?
`pod trunk push --verbose`
Terminal log
```
The following build commands failed:
	Check dependencies
(1 failure)
 -> HXPullRefresh (0.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

[!] The spec did not pass validation, due to 1 error.
```

CocoaPods Environment
1.2.1

Podspec
 ```
s.ios.deployment_target = '8.0'

  s.source_files = 'HXPullRefresh/Classes/**/*'

s.resource_bundles = {
'HXPullRefresh' => ['HXPullRefresh/**/*']
}
  # s.public_header_files = 'Pod/Classes/**/*.h'
   s.frameworks = 'UIKit'
   s.dependency 'SnapKit'
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
