### ISSUE TITLE
How to change the e-mai address?

### ISSUE THREAD

**Issue by VisionBao** [CocoaPods/CocoaPods#6663]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Cocoapods 1.2.1

I used `pod trunk register XXXXX@mail.com` register an account, but I want to change the email, how should I do?

or

how to Logout? how to Login?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
