### ISSUE TITLE
target overrides the `ALWAYS_SEARCH_USER_PATHS` build setting warning

### ISSUE THREAD

**Issue by themlkang** [CocoaPods/CocoaPods#6664]
# Report

## What did you do?
* Upgraded to xcode 8.3.
* Fixed new compiler warnings `warning: using 'ALWAYS_SEARCH_USER_PATHS = YES' while building targets which define modules ('DEFINES_MODULE = YES') may fail. Please migrate to using 'ALWAYS_SEARCH_USER_PATHS = NO'.` by setting `ALWAYS_SEARCH_USER_PATHS` to `NO` in the Target's Build Settings.  (ALWAYS_SEARCH_USER_PATHS is deprecated in xcode 8.3 and should be set to NO according to this: https://developer.apple.com/library/content/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html)
* Ran `pod install`

## What did you expect to happen?
Command to run correctly without warnings.

## What happened instead?
`pod install` ran with a bunch of warnings like this:
```
[!] The `AppName` target overrides the `ALWAYS_SEARCH_USER_PATHS` build setting defined in `Pods/Target Support Files/AppName/AppName.release.xcconfig'. This can lead to problems with the CocoaPods installation
- Use the `$(inherited)` flag, or
- Remove the build settings from the target.
```

When I looked in `Pods/Target Support Files/AppName/AppName.release.xcconfig`, `ALWAYS_SEARCH_USER_PATHS = YES` is there and I'm not sure how it got there or where that file came from.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.10
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3 (8E162)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/lee/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fd41a33fbeae99727ab2af8c9392c2b176a7c966
```

### Installation Source

```
Executable Path: /Users/lee/.rvm/gems/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
workspace "Via"
project 'AppName.xcodeproj'
install! 'cocoapods', :deterministic_uuids => false

def shared_dependencies
  pod 'ADiOSUtilities', '= 1.0.0'
  pod 'Mixpanel', '= 3.0.7'
  pod 'CorePlot', :git => 'https://github.com/core-plot/core-plot.git', :branch => 'release-2.2'
  pod 'Stripe', '= 2.2.2'
  pod 'Stripe/ApplePay'
  pod 'Adjust', :git => 'git://github.com/adjust/ios_sdk.git', :tag => 'v3.4.0'
  pod 'SocketRocket', '= 0.3.1-beta2'
  pod 'Appirater', '= 2.0.4'
  pod 'Raven', '= 1.0.1'
  pod 'AppsFlyer-SDK', '= 3.3.0'
  pod 'SHEmailValidator', '= 1.0.2'
  pod 'Branch', '= 0.11.13'
  pod 'FXBlurView', '= 1.6'
  pod 'FXPageControl', '= 1.4'
  pod 'OpenTok', '= 2.9.1'
  pod 'Fabric', '=1.6.11'
  pod 'Crashlytics', '=3.8.3'
end

target 'AppName' do
  shared_dependencies
end

target 'AppNameTests' do
  shared_dependencies
  pod 'OCMock', '~> 3.1.2'
end

target 'EarlGreyAppNameTests' do
  project 'AppName'

  use_frameworks!
  inherit! :search_paths
  shared_dependencies
  pod 'EarlGrey', '~> 1.8.0'
end

inhibit_all_warnings!

post_install do |installer|
  require 'earlgrey'
  configure_for_earlgrey(installer, 'AppName', 'EarlGreyAppNameTests', 'EarlGreyAppNameTests.xcscheme', {swift: true})

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
```

**Comment by benasher44** [comment]
Hi @themlkang! Thanks for the report! Unfortunately, one of the pods you're using is likely setting that build setting. You'll have to try various combinations of removing and adding pods to your Podfile and `pod install`ing to see which makes that setting go away, or you'll have to examine the specs of the pods you've added to see which one is adding that setting. I'm going to close this out, since this is an issue you'll want to bring up with the pod author, once you've determined which is the offending pod. Best of luck, and have a great day!

**Comment by mbaltaks** [comment]
For a workaround while you wait (for those coming from a search engine about this issue):

```ruby
post_install do |installer|
    `sed -i '' 's,ALWAYS_SEARCH_USER_PATHS = YES,,g' "Pods/Target Support Files/CorePlot/CorePlot.xcconfig"`
end
```

Adjust for the xcconfig files that are causing the warnings for you.
