### ISSUE TITLE
Cocoapods cannot build module for pod with static lib and headers

### ISSUE THREAD

**Issue by TienVu-PW** [CocoaPods/CocoaPods#6667]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I created a pod with only headers and a static library `.a` file, successfully pod spec and I installed it on a swift project with default `pod init` and git URL

The pod spec only contains `source_files` for the headers and `vendored_libraries` for the static library

XCode is 8.3.1

Thanks for helping

## What did you expect to happen?

Can use it by `import POD_MODULE_NAME`

## What happened instead?

It show `No such module POD_MODULE_NAME`, when building there's no module building appear, still able to use bridging header to use, before it was able to create, on new project it wont make the scheme anymore for this kind of pod

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.3.1 (8E1000a)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b12800334bbf27f87620eaebf659b5b698a378e1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'PWLocalSDKDemoSwift' do
  use_frameworks!
  # Pods for PWLocalSDKDemoSwift
  pod 'PWLocalSDK', :git => 'https://github.com/paymentwall/paymentwall-pwlocal-ios'
end
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
