### ISSUE TITLE
Getting While executing gem ... (TypeError)     no implicit conversion of nil into String after Pod install

### ISSUE THREAD

**Issue by Anilkr91** [CocoaPods/CocoaPods#6668]
Cocoa version = 1.0.1
ruby version = ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
xcode 7 and 8 using  both version 
macOS Sierra version = 10.12.1

**Comment by dnkoutso** [comment]
There is not enough information to debug this issue. Closing and please re-open new issue and fill in the template.
