### ISSUE TITLE
invalid tag for SwiftyJson 3.1.1

### ISSUE THREAD

**Issue by gr-orc** [CocoaPods/CocoaPods#6671]
https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/b/e/4/SwiftyJSON/3.1.1/SwiftyJSON.podspec.json#L22

# Report

## What did you do?
Run `pod install`

## What did you expect to happen?
Install SwiftyJson 3.1.1 correctly.

## What happened instead?
```sh
[!] Error installing SwiftyJSON
[!] /usr/bin/git clone https://github.com/SwiftyJSON/SwiftyJSON.git /var/folders/lz/krk8j37d4fq4dbznskttfc4r0000gp/T/d20170421-9483-1dkvcle --template= --single-branch --depth 1 --branch v3.1.1
```

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.11.6 (15G1217)
       Xcode : 8.2 (8C38)
         Git : git version 2.9.0
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5f2dbbe99f7f7e10b23e3900ee3e78dbbe01390b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
swift_version = '3.0.1'
use_frameworks!

def shared_pods
    pod 'Alamofire', '~> 4.0.0'
    pod 'SwiftyJSON', '3.1.1'
    pod 'KeychainAccess'
    pod 'INTULocationManager', '~> 4.1.1'
    pod 'SDWebImage', '~>3.7'
    pod 'ReachabilitySwift'
    pod 'ECSlidingViewController', '~> 2.0.3'
    pod 'LineKit'
    pod 'DZNEmptyDataSet'
    pod 'ActionSheetPicker-3.0'
    pod 'SwiftHEXColors'

    pod 'FBSDKCoreKit', '~> 4.13.0'
    pod 'FBSDKLoginKit', '~> 4.13.0'

    #pod 'GoogleAnalytics'
    pod 'GoogleTagManager', '~> 3.15.0'
    pod 'GoogleMaps'
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'OneSignal'
    
    pod 'SloppySwiper'
end

target 'goodroom_ios' do
    shared_pods
end

target 'goodroom_ios_staging' do
    shared_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = "3.0.1"
        end
    end
end
```

**Comment by aaberga** [comment]
Even a far simpler podfile shows the same problem...

`
host:Test App user$ pod install
Analyzing dependencies
Downloading dependencies
Installing SwiftyJSON (3.1.1)

[!] Error installing SwiftyJSON
[!] /usr/bin/git clone https://github.com/SwiftyJSON/SwiftyJSON.git /var/folders/87/jx7c32wd3cl6sss25thb38080000gn/T/d20170427-2527-1a7k6oc --template= --single-branch --depth 1 --branch v3.1.1

Cloning into '/var/folders/87/jx7c32wd3cl6sss25thb38080000gn/T/d20170427-2527-1a7k6oc'...
warning: Could not find remote branch v3.1.1 to clone.
fatal: Remote branch v3.1.1 not found in upstream origin

host:Test App user$
`

The pod file is attached...
[Podfile.txt](https://github.com/CocoaPods/CocoaPods/files/960928/Podfile.txt)

**Comment by orta** [comment]
This sounds like an issue with SwiftJSON the library, not CocoaPods the tool. I'd recommend writing an issue on their repo.

**Comment by aaberga** [comment]
That is very likely: thanks for pointing this out!

Aldo

**Comment by gr-orc** [comment]
@orta thank you for your recommendation.  I worte a issue on their repo.
