### ISSUE TITLE
An unexpected version directory `Assets` was encountered for the Pod in the repository

### ISSUE THREAD

**Issue by Mohamed3amer** [CocoaPods/CocoaPods#6674]
# Report

## What did you do?

Am trying to create a private CocoaPod using `pod lib create MyLibrary` terminal command, after creating the sample CocoaPod workspace i pushed it on Gitlab repository.

I used this command `pod spec lint --verbose --allow-warnings` to lint my podspec file and i got below result:

> Bootstrap.podspec passed validation.

But when i try to use this pod in another project am getting this error from `pod install` command

> [!] An unexpected version directory Assets was encountered for the .cocoapods/repos/gitlab-bootstrap/Bootstrap Pod in the Bootstrap repository.

My podspec file is here:

```
Pod::Spec.new do |s|
s.name             = 'Bootstrap'
s.version          = '0.1.0'
s.summary          = 'Bootstrap is a library.'
s.description      = <<-DESC
Bootstrap is a library.
DESC

s.homepage         = 'https://gitlab.com/apptech/Bootstrap'
# s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
s.license          = { :type => 'MIT', :file => 'LICENSE' }
s.author           = { 'MIT' => 'm@m.com' }
s.source           = { :git => 'git@gitlab.com:apptech/Bootstrap.git', :tag => s.version.to_s }
# s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

s.ios.deployment_target = '9.0'

s.source_files = 'Bootstrap/Classes/**/*'

#s.resource_bundles = {
#  'Bootstrap' => ['Bootstrap/Assets/*.png']
#}

# s.public_header_files = 'Pod/Classes/**/*.h'
# s.frameworks = 'UIKit', 'MapKit'
# s.dependency 'AFNetworking', '~> 2.3'
end
```

And Pod file is here:

```
# Insert your own private specs repo source
source 'git@gitlab.com:apptech/Bootstrap.git'

# Standard cocoapods specs source
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'test' do

    pod 'Bootstrap', '0.1.0'

end
```

Notes:-
CocoaPods Version is 1.2.1
xCode Version 8.2.1
OS version macOS Sierra

## What did you expect to happen?

I be able to use the private CocoaPods created.

## What happened instead?

Getting an error while running `pod install` command as below

> [!] An unexpected version directory Assets was encountered for the .cocoapods/repos/gitlab-bootstrap/Bootstrap Pod in the Bootstrap repository.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

pod env

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : gitlab-bootstrap - git@gitlab.com:apptech/Bootstrap.git @ 89a2933375c0b9ff54d51f0012a2bef06c023832
               master - https://github.com/CocoaPods/Specs.git @ d41d4c1d733f740077474d6a62c5669e5c517bcb
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

It is a private project.

**Comment by eraducan** [comment]
Same error. 
In podspec file i also have:  
```
 ts.source_files   = "**"
```

**Comment by dnkoutso** [comment]
Can you limit your `s.source_files = '**'` to `s.source_files = '**/*.{h,m}`?

**Comment by enryold** [comment]
Same for for me, using s.source_files = '**/*.{h,m}'

**Comment by cameronehrlich** [comment]
Were you keeping `Podspec` file in the same repo as your pod code and versioning file tree?
