### ISSUE TITLE
I can`t receive the email.

### ISSUE THREAD

**Issue by xclidongbo** [CocoaPods/CocoaPods#6675]
version 1.2.0

lidongbo:XCkit lidongbo$ pod trunk me
[!] Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session.
lidongbo:XCkit lidongbo$ pod trunk register xclidongbo@gmail.com 'xclidongbo' --description='macboo
kpro'
[!] Please verify the session by clicking the link in the verification email that has been sent to xclidongbo@gmail.com

**Comment by benasher44** [comment]
Hi @xclidongbo! Thanks for the report! I've checked our email service, and it appears that the most recent attempt was successful (along with all the previous ones I can see) and was opened. I'm going to close this, since it appears to be resolved. Have a great day!

**Comment by healthathand** [comment]
Happening to me yet. 
pod version 1.6.1. I am receiving email, when click, it gives me message

ACE, YOU'RE SET UP.
You can go back to your terminal now.

But it gives same error on Terminal when I run trunk command.
