### ISSUE TITLE
Pod Lib Create Commond Error

### ISSUE THREAD

**Issue by josercc** [CocoaPods/CocoaPods#6677]
➜  GITHUB pod lib create SVNLogManager
Cloning `https://github.com/CocoaPods/pod-template.git` into `SVNLogManager`.
Configuring SVNLogManager template.
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- colored2 (LoadError)
	from /Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhangxing/Documents/GITHUB/SVNLogManager/setup/TemplateConfigurator.rb:2:in `<top (required)>'
	from ./configure:5:in `require_relative'
	from ./configure:5:in `block in <main>'
	from ./configure:4:in `each'
	from ./configure:4:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

Cocoapod Version 1.2.0

**Comment by alexfeng** [comment]
https://github.com/CocoaPods/CocoaPods/issues/6659

**Comment by benasher44** [comment]
Thanks for the report! This appears to be fixed in CocoaPods 1.2.1 as indicated in #6659, so I'm going to close this. Have a great day!
