### ISSUE TITLE
a problem about "https"

### ISSUE THREAD

**Issue by dengbin9009** [CocoaPods/CocoaPods#6678]
Hi，I met a problem when using cocoapod
![09b6ff17-701d-4137-ae75-7895901b0085](https://cloud.githubusercontent.com/assets/3061194/25320920/f61da90e-28dc-11e7-9bec-7b0aff988f41.png)
What should I do now?

**Comment by benasher44** [comment]
Hi there! Thanks for the report! There appears to be some sort of issue with your installation. In the output there, it's trying to run git, and it appears that your git doesn't know how to handle https. If you reinstall your upgrade your git, that should fix the issue. Checkout git-scm.com where there are binaries available for download, or you can use a tool like [homebrew](brew.sh) to install a new git. Best of luck!

**Comment by dengbin9009** [comment]
@benasher44  It doesn't work for me!
I has reinstall git any time, but the issue is appeared  again.
![2617b2de-8738-48e1-8cb3-00477bb4529d](https://cloud.githubusercontent.com/assets/3061194/25464243/e62c7856-2b2d-11e7-9e4d-fb5afd3e1099.png)

And I has tried install homebrew,but I failed too. The warning(fatal: Unable to find remote helper for 'https') is appear too. 
![12de43f8-30c9-4779-ade2-99ee3765a1ad](https://cloud.githubusercontent.com/assets/3061194/25464332/5b13ee1a-2b2e-11e7-80bd-785da0ce2e5a.png)

I'm looking forward to get your help!  thx...

**Comment by MadeInFck** [comment]
I have exactly the same issue. So far nothing that I read fixed it, even update or new install of git.
