### ISSUE TITLE
Difficulty controlling location of headers

### ISSUE THREAD

**Issue by rigdern** [CocoaPods/CocoaPods#6683]
I have a podspec file called [`Yoga.podspec`](https://github.com/facebook/react-native/blob/v0.42.0/ReactCommon/yoga/Yoga.podspec) and the `spec.name` is `Yoga`. The headers are placed in `Headers/Public/Yoga/`. Instead, I would like the headers placed in `Headers/Public/yoga` (notice the "y" is now lowercase).

I tried setting `module_name` to `yoga`, running `pod install`, but it didn't seem to have any impact on the header location.

I tried setting `header_dir` to `yoga` but then `pod install` placed the headers into `Headers/Public/Yoga/yoga`.

As a workaround, I ended up changing `spec.name` to `yoga`.

@alloy expected me to be able to get this to work without my workaround so he asked me to file this issue.

I'm consuming my CocoaPods as static libraries.

The reason I'm trying to do this is my project is generating a `-Wnonportable-include-path` warning (new in Xcode 8.3) when I consume React Native as a CocoaPod and try to import its headers from a non-CocoaPod (e.g. `#import <React/RCTConvert.h>`). `-Wnonportable-include-path` detects when the casing of a header import doesn't match the casing of the path on disk (e.g. `#import <yoga/Yoga.h>` doesn't match `$(BUILT_PRODUCTS_DIR)/Yoga/Yoga.h` due to the difference in capitalization of the directory name).

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.10
        Host : Mac OS X 10.11.6 (15G1212)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ 7a41f784f9d8e7a3d0b1a97eb8294df1c93231cf
```

### Installation Source

```
Executable Path: /Users/adcom/Kit/.gem/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

**Comment by benasher44** [comment]
Great! Would you mind also pasting the contents of `pod env` for reference. Thanks!

**Comment by rigdern** [comment]
@benasher44 Thanks for the quick response. I added the output of `pod env` to my issue description.

**Comment by alloy** [comment]
@benasher44 So even though iirc CP doesn’t use modules for static libraries, I think that intuitively the module name, when given, should be used for build time logic _over_ the pod’s name. Because the pod’s name could be used in a way that’s more geared towards marketing rather than build time logic.

**Comment by benasher44** [comment]
Makes sense to me! Seems like a nice improvement.

**Comment by amorde** [comment]
With #8706, setting `module_name` will now update the header directory to the module name. Does that resolve this issue?
