### ISSUE TITLE
undefined method `encode' for nil:NilClass

### ISSUE THREAD

**Issue by alanwangmodify** [CocoaPods/CocoaPods#6684]
when 
'pod lib lint'

error: 
- ERROR | [iOS] unknown: Encountered an unknown error (undefined method `encode' for nil:NilClass) during validation.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
