### ISSUE TITLE
How do I force using a subspec in a Podfile?

### ISSUE THREAD

**Issue by 0xced** [CocoaPods/CocoaPods#6689]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I’m trying to use a specific subspec for a dependent pod. The `XCDLumberjackNSLogger` pod depends on the `NSLogger` pod but I would like to force using the `NoSwift` subspec.

```ruby
platform :ios, '9.0'

target 'MyApp' do
  pod 'XCDLumberjackNSLogger', '1.1.1'
  pod 'NSLogger/NoSwift', '1.8.2'
end
```
 
```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing CocoaLumberjack (3.1.0)
Installing NSLogger 1.8.2 (was 1.8.2)
Installing XCDLumberjackNSLogger (1.1.1)
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: NSLogger
```

## What did you expect to happen?

I expect the `NoSwift` subspec is used instead of the default subspec. If I remove `pod 'XCDLumberjackNSLogger', '1.1.1'` and use only `pod 'NSLogger/NoSwift', '1.8.2'` then the error goes away, but of course I can't use the `XCDLumberjackNSLogger` pod anymore.

## What happened instead?

An error occurs because I don't want to use frameworks and the default subspec of the NSLogger pod includes swift code.

## Question

Is there a way to force using a specific subspec for a dependent pod, like using the :git/:branch or :git/:commit specifier?

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin15]
    RubyGems : 2.4.5.2
        Host : Mac OS X 10.11.6 (15G1421)
       Xcode : 8.2 (8C38)
         Git : git version 2.12.2
Ruby lib dir : ~/.rbenv/versions/2.2.6/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ acdeeff55df502a8b43c758ac25d798d92ba7a26
```

### Installation Source

```
Executable Path: ~/.rbenv/versions/2.2.6/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'MyApp' do
  pod 'XCDLumberjackNSLogger', '1.1.1'
  pod 'NSLogger/NoSwift', '1.8.2'
end
```

**Comment by orta** [comment]
I _think_ you can change [this line](https://github.com/CocoaPods/Specs/blob/master/Specs/d/d/4/XCDLumberjackNSLogger/1.1.1/XCDLumberjackNSLogger.podspec.json#L29) to be `NSLogger/NoSwift`.

**Comment by 0xced** [comment]
I was hoping for a solution at the Podfile level rather than at the podspec level, but thanks, I will try.

**Comment by orta** [comment]
Today the Podfile is only really additive WRT targets and subspecs
