### ISSUE TITLE
DJI-UILibrary-iOS CocoaPods page and podspec are missing!

### ISSUE THREAD

**Issue by oliverou** [CocoaPods/CocoaPods#6690]
# Report

## What did you do?

Run `pod trunk push DJI-UILibrary-iOS.podspec` to publish the DJI-UILibrary-iOS pod. Here is the successful log message:

![djiuilibrary_log_message](https://cloud.githubusercontent.com/assets/13310805/25603024/08d11e60-2f2b-11e7-9128-9901fadb5313.png)

## What did you expect to happen?

The DJI UILibrary iOS CocoaPods webpage should be shown when click this link: <https://cocoapods.org/pods/DJI-UILibrary-iOS>. And the podspec Github page show be shown too.

## What happened instead?

When you click the DJI UILibrary CocoaPods link: <https://cocoapods.org/pods/DJI-UILibrary-iOS>,  it jumps to the Github page instead. Also, if you search "DJI" on CocoaPods website, it shows three buttons on the right side for DJI-UILibrary-iOS, when you click the **Spec** button, it jumps to a 404 Github page:

![searchresult](https://cloud.githubusercontent.com/assets/13310805/25603106/b81f84d8-2f2b-11e7-842d-ee810d266935.png)

![404](https://cloud.githubusercontent.com/assets/13310805/25603216/5ca5f3a2-2f2c-11e7-971d-40d80feda6f6.png)

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /usr/local/Cellar/ruby/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d7ab5bdb0f50fd00043520984677c59d9e217f8d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# platform :ios, '9.0'

target 'UILibraryTest' do
  pod 'DJI-UILibrary-iOS', '~> 4.0'
end
```

## Project that demonstrates the issue

DJI UILibrary iOS: <https://cocoapods.org/pods/DJI-UILibrary-iOS>
Github Podspec: <https://github.com/CocoaPods/Specs/tree/master/Specs/DJI-UILibrary-iOS/4.0.1.1.0.0/DJI-UILibrary-iOS.podspec.json>

**Comment by orta** [comment]
Hi, thanks for the issue - as the issue template notes, please don't raise issues about search results on this repo, this is for CocoaPods the tool, not the website.  

The issue templates in CocoaPods.org/CocoaDocs.org repos provide instructions on how to debug this sort of thing yourself, I've ran through them while writing this up and everything is working now. 👍

**Comment by orta** [comment]
Also, I have a Mavic, this SDK looks cool 💯

**Comment by oliverou** [comment]
Hi @orta, thanks a lot for your help! Glad that you like the SDK and Mavic Pro!
