### ISSUE TITLE
use_frameworks and adding a swift framework results in file not found for depedency header files

### ISSUE THREAD

**Issue by jamehta** [CocoaPods/CocoaPods#6693]
> using cocoapods 1.2.1

> using Xcode 8.2.1

# Report

## What did you do?

I have a framework A which has dependency B.
When in a swift application, i use use_frameworks and use A as dependency and compile,
my swift application fails to compile. It complains that cannot find header file (these are header files
for B)

## What did you expect to happen?

Since in the Pods directory i have B and all its files, i expect my swift application to compile fine.

## What happened instead?

header file not found error for B.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
