### ISSUE TITLE
CircleCI builds all failing?

### ISSUE THREAD

**Issue by jgavris** [CocoaPods/CocoaPods#6695]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I created a pull request https://github.com/CocoaPods/CocoaPods/pull/6694, then inspected the build log for CircleCI https://circleci.com/gh/CocoaPods/CocoaPods.

## What did you expect to happen?

I expected a configured status check to be passing on `master` for this repository. 

## What happened instead?

All the builds are failing 😁

**Comment by orta** [comment]
I think this is fixed by https://github.com/CocoaPods/CocoaPods/pull/6282 :D
