### ISSUE TITLE
Pod install is adding settings = {COMPILER_FLAGS = "-fno-objc-arc"; }; to several files.

### ISSUE THREAD

**Issue by marcvanolmen** [CocoaPods/CocoaPods#6701]
Xcode 8.3.2, CocoaPods 1.2.1 (installed with Brew)

# Report

When I run "pod install" with our private project dependency, some files (some are .m and .swift) of the project get the custom compiler flag ```settings = {COMPILER_FLAGS = "-fno-objc-arc"; };```

remark: (we use our own specs) library but I also tried to do it by pointing to the project on our local disk, it doesn't make a difference. 

## What did you do?

pod install

## What did you expect to happen?

No ```settings = {COMPILER_FLAGS = "-fno-objc-arc"; };``` added to some files. 

## What happened instead?

some files had the flags ```settings = {COMPILER_FLAGS = "-fno-objc-arc"; };```
 
### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 36778816ef965125c1df8cefabc4109977b5f4e1
               <<our specs>> @ de8e558d124dbfb219ed1cf553b26a9d02189b72
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.2.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby

platform :ios, '10.0'


target '<<our app>>' do
  use_frameworks!

  # Pods for <<our app>>
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'GoogleTagManager', '~> 5.0'
  pod 'FBAudienceNetwork'
  pod 'HockeySDK', :subspecs => ['CrashOnlyExtensionsLib']
  pod 'ComScore'

  pod 'Chartbeat', '1.2.2'
  pod 'RTVCore', '~> 0.0.8'

end
```
## Project that demonstrates the issue

can't share private project. The project has several folders that go like 4 level deep and about 50 files.

 But here the spec file of the private project:

```
Pod::Spec.new do |s|
  s.name         = "RTVCore"
  s.version      = "0.0.8"
  s.summary      = "Private library for integrating with video API"
  s.description  = "Private library for integrating with video API."
  s.homepage     = "<<our url>>"
  s.license      = { :type => 'Commercial', :file => 'LICENSE.md' }
  s.source       = { :git => "<<our url>>", :tag => "#{s.version}" }
  s.platform     = :ios
  s.ios.deployment_target = "10.0"
  s.requires_arc  = true
  s.source_files  = "RTVCore/**/*.{h,m}", "RTVCore/**/*.{swift}"
  s.library = "xml2"
  s.xcconfig = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }
  s.dependency "ObjectMapper", "~> 2.2.5"
end

```

**Comment by marcvanolmen** [comment]
I found the reason why this issue is happening:

Objectmapper has a typo in the Cocoapod  Spec:

```
  s.requires_arc = 'true'
```

instead of 
```
  s.requires_arc = true
```

https://github.com/Hearst-DD/ObjectMapper/pull/804

I also had this error before, in my own repo, so this seems like a common mistake to make, maybe cocoa pods should check for this!!!

so I'm leaving this ticket open.

**Comment by orta** [comment]
Yeah, this sounds like a good feature for the linter 👍 

Kinda surprised that 'true' doesn't evaluate to true somewhere as it is a truth value.

**Comment by segiddins** [comment]
It's because strings are valid values for `requires_arc`, and it's interpreted as a path pattern of files that should compiled with ARC enabled

**Comment by RetVal** [comment]
How can we mark some files are not required arc? Because almost of files need arc, a few of them need not, if we use s.requires_arc = 'src/ARC/' can do this, but on the filesystem, this looks strange, module files are split by memory management?

**Comment by paulb777** [comment]
@RetVal You can do the opposite and put the files that require no arc in a special subdirectory like https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCommunity.podspec#L78
