### ISSUE TITLE
XMPPFramework install through cocoapods failing because of dependency

### ISSUE THREAD

**Issue by holykou** [CocoaPods/CocoaPods#6706]
I'm using cocopods version 0.39.0
When I try to install the pod for XMPPFramework (pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'), I get the following error:
[!] Unable to satisfy the following requirements:

- `libidn (~> 1.33.0)` required by `XMPPFramework (3.7.0)`

Will this affect anything, or can I just ignore this?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
