### ISSUE TITLE
Error with 'pod trunk register' 

### ISSUE THREAD

**Issue by itmarsung** [CocoaPods/CocoaPods#6709]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/XXX/.rvm/rubies/ruby-2.3.0/bin/pod trunk register [email_address] [name] --description=iMac
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.9.2
Ruby lib dir : /Users/XXX/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f7daa04eb6a188b9e6469334d74b279fc764ae19
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Error

```
Netrc::Error - Permission bits for '/Users/XXX/.netrc' should be 0600, but are 644
/Users/XXX/.rvm/gems/ruby-2.3.0@global/gems/netrc-0.7.8/lib/netrc.rb:33:in `check_permissions'
/Users/XXX/.rvm/gems/ruby-2.3.0@global/gems/netrc-0.7.8/lib/netrc.rb:40:in `read'
/Users/XXX/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-trunk-1.2.0/lib/pod/command/trunk.rb:106:in `netrc'
/Users/XXX/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-trunk-1.2.0/lib/pod/command/trunk/register.rb:72:in `save_token'
/Users/XXX/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-trunk-1.2.0/lib/pod/command/trunk/register.rb:62:in `run'
/Users/XXX/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/XXX/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Users/XXX/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/Users/XXX/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `load'
/Users/XXX/.rvm/rubies/ruby-2.3.0/bin/pod:22:in `<main>'
/Users/XXX/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/XXX/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+bits+for+%27%2FUsers%2Fmarsung%2F.netrc%27+should+be+0600%2C+but+are+644&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Getting error after editing a podspec
   https://github.com/CocoaPods/CocoaPods/issues/644 [closed] [4 comments]
   4 hours ago

**Comment by orta** [comment]
Did you look at changing your permissions for your `.netrc`?

> Netrc::Error - Permission bits for '/Users/XXX/.netrc' should be 0600, but are 644
