### ISSUE TITLE
Code sharing with extension using the subspec approach doesn't work

### ISSUE THREAD

**Issue by zierka** [CocoaPods/CocoaPods#6711]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

* Setup the project as described in [#5373](https://github.com/CocoaPods/CocoaPods/issues/5373) ([comment](https://github.com/CocoaPods/CocoaPods/issues/5373#issuecomment-220486539), sharing a subset of functionality with an extension). Initially reported this in that thread, but felt like it should have it's own issue.
* Run `pod install`

### Details:
A private framework with two subspecs:
- `App`: for the main app target
- `Extension`: for the extension target, uses some files "from" the `App` subspec

### `podspec`:

```ruby
Pod::Spec.new do |s|
  s.name        = 'MyFramework'
  s.version       = '0.1.0'
  s.summary       = 'Dummy Framework'
  s.homepage      = 'https://github.com/zierka'
  s.license       = 'MIT'
  s.author        = {'Zier Erik' => 'erik.interwebz@gmail.com'}

  s.source        = {:git => 'git@github.com:zierka/subspec-error-example.git', :tag => s.version.to_s}

  s.requires_arc  = true
  s.platform      = :ios
  s.ios.deployment_target = '10.0'

  s.default_subspecs = 'App'

  s.subspec 'App' do |app|
    app.source_files = [
      'App/**/*.{swift}'
    ]
  end

  s.subspec 'Extension' do |ext|
    ext.source_files = [
      'App/CoreClass.swift',
      'Extension/**/*.{swift}'
    ]

    ext.exclude_files = [
      'App/AppClass.swift'
    ]
  end

end
```

### A simple xcode project, with 2 targets:
- the main app target has the `MyFramework` as dependency in the Podfile
- the extension target has the `MyFramework/Extension` as dependency

### `Podfile`:

```ruby
platform :ios, '10.0'
use_frameworks!

target 'SubspecProblemExample' do
  pod 'MyFramework', :path => "../MyFramework" . # equal to MyFramework/App as that's declared for default_subspecs
end

target 'todayWidget' do
  pod 'MyFramework/Extension', :path => "../MyFramework"
end
```

## What did you expect to happen?

Successful integration, creating a workspace. 

## What happened instead?

`[!] The 'Pods-SubspecProblemExample' target has frameworks with conflicting names: myframework.`

I'm aware that this error is mentioned in a quite a few issues, I read through all of them, but it's still not clear to me what the real problem is. 

* Is the described subspec approach not supported anymore?
I never got a confirmation about this, and based on the replies in that thread, it's described as a working solution, hence my confusion.
* If it's not working anymore, is there any other way to share code like this? Note that one of the key reasons for sharing code this way is to exclude usage of unavailable code from the extension (e.g. `UIApplication`), but still able to use it in the main target.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
[REDACTED: removed some private spec repositories]
               master - https://github.com/CocoaPods/Specs.git @ 73b41a4e0658de58a2031c6e2da00f37ae5813f3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/zierka/subspec-error-example

**Comment by orta** [comment]
I think this is a bug, I'm pretty sure we've supported or aim to support this kind of setup.

**Comment by yarneo** [comment]
this has always been the case, and i think is related to: https://github.com/CocoaPods/CocoaPods/issues/5643

**Comment by yarneo** [comment]
As it is now, it seems like there is no way of having a subspec that supports app extensions when the main app uses the framework as well.

**Comment by kjacobs-aa** [comment]
I see this as a bug too. Could this be solved by a different naming for the framework products (e.g. podspec_name-subspec_name.framework?

**Comment by cerupcat** [comment]
I'm running into this too. It seams like, if you're using `use_frameworks!` (required for swift) you can only use frameworks that can work both in an extension and main app. Is that correct? With static libraries, we could set preprocessor definitions to create a different library for the extension and the main app. Without the ability to at least configure the extension framework and main app independently it's not possible to use frameworks that make API calls not allowed in extension (ie. UIApplication). Isn't this a common problem or am I misunderstanding?

**Comment by kjacobs-aa** [comment]
@cerupcat that is also my understanding of it. Frameworks built out of a subspec contain the same framework name and thus conflict.

**Comment by dnkoutso** [comment]
I might be planning for CocoaPods 1.4.0 to "promote" subspecs to separate libraries instead of using the same framework name. This will come in a while though probably Fall of 2017.

**Comment by cerupcat** [comment]
Thanks, this makes sense. The only issue I see for using different framework names for the same framework would then be that any reference using <FramworkName/Wahtever.h> could then be wrong since the `FrameworkName` would change based on subspec.

**Comment by dnkoutso** [comment]
> Thanks, this makes sense. The only issue I see for using different framework names for the same framework would then be that any reference using <FramworkName/Wahtever.h> could then be wrong since the FrameworkName would change based on subspec. I guess there's no way around it then.

Exactly!

**Comment by kjacobs-aa** [comment]
@cerupcat sounds to me like this has more to do with duplicate symbols from your both frameworks. I'd wonder what the indended solution direction would be here, @dnkoutso do you have any ideas how to approach this?

**Comment by cerupcat** [comment]
@kjacobs-aa The actual error was a `lexical or preprocessor error` `could not build module ----` on the framework extension (the other framework seemed to build fine). It may or may not related to them being the same framework/files, but it was hard to tell. I couldn't figure it out.

**Comment by paulb777** [comment]
@dnkoutso A downside of promoting "subspecs to separate libraries" would be losing the advantage of subspecs to consolidate dynamic libraries and minimize their performance impact.

**Comment by dnkoutso** [comment]
@paulb777 you mean that you will get many dynamic frameworks to link? I think this can be solved separately. 

Haven't had it fleshed out in my mind 100% yet but definitely worth a discussion.

**Comment by paulb777** [comment]
@dnkoutso Yes, I mean that subspecs are a mechanism so that fewer dynamic frameworks are linked so that the incremental dynamic library loader time is lower.

A discussion sounds good. :)
