### ISSUE TITLE
Cocoapods for os x 10.9.5

### ISSUE THREAD

**Issue by Crazyfirethe13** [CocoaPods/CocoaPods#6712]
Im on os x 10.9.5 because i cant upgrade and tried to download cocapods but i get the message "You have OS X 10.9.5. The application requires OS X 10.10 or later." i tried to download an early version but i get the same message so anyone help?

**Comment by orta** [comment]
The CocoaPods Mac app does not support that version of macOS I'm afraid, you'll need to use the ruby gem which supports most modern versions of macOS instead.
