### ISSUE TITLE
Readme and changelog not updated

### ISSUE THREAD

**Issue by n3trino** [CocoaPods/CocoaPods#6716]
* [✔] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk push WOVER.podspec

## What did you expect to happen?

1. Update README.md and CHANGELOG.md included inside zip file to latest version of pod.

## What happened instead?

Keeps README.md and CHANGELOG.md from previous version.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/stavrosschizas/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 01275f74bd2fed6db034f7a40d84635a0a960b7f
```

### Installation Source

```
Executable Path: /Users/stavrosschizas/.rvm/gems/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://cocoapods.org/pods/WOVER

**Comment by orta** [comment]
This repo is for CocoaPods the command line tool, not for the websites - please see the cocoapods.org  or cocoadocs.org repos for those.
