### ISSUE TITLE
target overrides the `LIBRARY_SEARCH_PATHS

### ISSUE THREAD

**Issue by SpaceStar2016** [CocoaPods/CocoaPods#6719]
ℹ I added $(inherited) to figure out the issue --"target overrides the `LIBRARY_SEARCH_PATHS"， but I still used FFMpeg in my project and FFMpeg need other header search path and lib search path. When I used $(inherited)  and added the FFMpeg search path in my project, it didn't work. It seems that $(inherited) covers the FFMpeg lib search path. So what should do? pod version 1.1.1

![Uploading issue.png…]()

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
