### ISSUE TITLE
Unexpected "Unable to find a specification" error

### ISSUE THREAD

**Issue by groue** [CocoaPods/CocoaPods#6720]
# Report

## What did you do?

```
$ pod install
...
[!] Unable to find a specification for `GRDBCipher`
$ pod try GRDBCipher
Updating spec repositories
[!] Unable to find a specification for `GRDBCipher`
$ pod list | grep GRDBCipher
(nothing)
```

## What did you expect to happen?

All commands above to succeed, since I did a successful `pod trunk push` for GRDBCipher, [GRDBCipher.podspec.json](https://github.com/CocoaPods/Specs/blob/master/Specs/8/4/b/GRDBCipher/0.108.0/GRDBCipher.podspec.json) exists, and https://cocoapods.org/?q=grdbcipher gives a result.

## What happened instead?

Error messages that say that CocoaPods is "unable to find a specification for `GRDBCipher`".

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.12.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : accengage - https://github.com/Accengage/CocoaPodsSpecs.git @ c51d74c11e3fc1ed018f6359bc444ca40da74c40
               master - https://github.com/CocoaPods/Specs.git @ ec8b63aa8788d3da9bf4136978051bc78ebfc882
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target "DemoApp" do
  use_frameworks!
  pod 'RxGRDB/GRDBCipher', :git => 'https://github.com/groue/RxGRDB.git', :branch => 'GRDBCipher'
end
```

## Project that demonstrates the issue

It's still a tiny project that I use to check that the `RxGRDB/GRDBCipher` can be used in a Podfile, before I can ship this library for good. See the Podfile above.

Thanks for your support!

**Comment by orta** [comment]
Have you tried `pod repo update`? By default `install` won't download new specs.

**Comment by groue** [comment]
@orta, you have some serious mojo. Thanks a *lot*, your advice solves all problems!
