### ISSUE TITLE
No email received for 'pod trunk register

### ISSUE THREAD

**Issue by prabhjotAppmobi** [CocoaPods/CocoaPods#6724]
Hi,

Recently we've been trying to register a machine with pod trunk register.

    pod trunk register cocoapod@appmobi.com 'Appmobi' --description='Appmobi 1.1.6'

But we did not received any email from cocoa pods for verification. Please check into the issue.

We did the same thing with a different email and it worked as expected.

Could you please check if there are any issues on your end with the registration of the cocoapod@appmobi.com.

**Comment by orta** [comment]
![screen shot 2017-05-18 at 10 00 51](https://cloud.githubusercontent.com/assets/49038/26194621/e4cc8f62-3bb0-11e7-897b-07afeeefb642.png)

Your mail server reported the email didn't exists - I've removed the block on the email from our side 👍  - should be fine now.

**Comment by prabhjotAppmobi** [comment]
Thanks for your prompt response.

We see that you unblocked the cocoapods@appmobi.com, but the email configured as a owner is cocoapod@appmobi.com , So we would Request you to please unblock 'cocoapod@appmobi.com' so that we can receive verification email and push our Pod updated.

Thanks Again @orta.

**Comment by orta** [comment]
Done 💯

**Comment by prabhjotAppmobi** [comment]
This has been completed. Thanks for your support @orta.

**Comment by akhilcb** [comment]
We are facing same issue. We tried multiple mail ids and none of them received any mails. Could you please check and unblock us too. This is the mail id used "cocoapods@bluejeans.com".
