### ISSUE TITLE
frameworks not linked

### ISSUE THREAD

**Issue by gumnym** [CocoaPods/CocoaPods#6728]
# Report

After pod installation I'm getting  "Undefined symbols for architecture" error. I have to manually copy frameworks from pods project to Build Phases -> Link Binary with Libraries on my target, only then I can compile project.

## What did you do?

Created Podfile

platform :ios, '9.0'
inhibit_all_warnings!

workspace 'OnTheRoad'

def shared_pods
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
end

target 'OnTheRoadDEV' do
	shared_pods
end

and installed pods

## What did you expect to happen?

I should be able to start using firebase 

## What happened instead?

I could not compile project due to Undefined symbols for architecture, also it's not only with Firebase but all other pods

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0b6fad22cf83e317578366798ec2441997663227
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
inhibit_all_warnings!

workspace 'OnTheRoad'

def shared_pods
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
end

target 'OnTheRoadDEV' do
	shared_pods
end

target 'OnTheRoadUAT' do
        shared_pods
end

target 'OnTheRoadSQA' do
        shared_pods
end

target 'OnTheRoad' do
        shared_pods
end
```

**Comment by DanToml** [comment]
Please could you share a project that reproduces this?

**Comment by jz709u** [comment]
I'm having the same issue...

**Comment by gumnym** [comment]
I can't share project but if you have some hints about what specific could be wrong I can check it
