### ISSUE TITLE
`pod update <Framework> --sources=<source>` updates all pods instead of the specified

### ISSUE THREAD

**Issue by allen-zeng** [CocoaPods/CocoaPods#6730]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod update <Internal Framework> --sources=<internal CocoaPods source>`

## What did you expect to happen?
The internal source specified is updated, and _only_ the internal framework specified in the command is updated.

## What happened instead?
All sources including the CocoaPods master specs repo are updated, then the command carried on to update all the pods, not just the specified.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/Allen/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a02aee00aac360b977257e29d730ce4f7a7388f6
               <internal CocoaPods source> - <SSH URL for internal CocoaPods source> @ <SHA for internal CocoaPods source>
```

### Installation Source

```
Executable Path: /Users/Allen/Documents/<redacted>/.bundle/ruby/2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile
Podfile contains the source commands:
```ruby
source '<SSH URL for Internal CocoaPods source>'
source 'https://github.com/Cocoapods/Specs.git'
```

**Comment by dnkoutso** [comment]
Would love a sample project for this. This does not happen to us at least internally in CP 1.2.1.

**Comment by allen-zeng** [comment]
I can't seem to replicated it any more myself either... I think it's probably some weird internal set up that was incorrect, will keep an eye out and report back if it's really a problem. Thanks!

Closing this for now.
