### ISSUE TITLE
is it `s.platform = :ios, :tvos` or `s.platforms = { :ios => nil, :tvos => nil }`?

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#6731]
Hello,

I got a pull request with the following suggestion: https://github.com/squarefrog/UIDeviceIdentifier/pull/26/files

But I'm wondering:
1) is that change correct?
2) is having `=> nil` for each platform mandatory?
3) could we trigger a lint warning if someone is writing `s.platform = :ios, :tvos` or similar?
4) can we query the cocoapods public database of podspecs to find similar issues to report/fix?

**Comment by orta** [comment]
This is documented in [the Podspec reference](https://guides.cocoapods.org/syntax/podspec.html#platform) it says:

> The platform on which this Pod is supported. Leaving this blank means the Pod is supported on all platforms. When supporting multiple platforms you should use deployment_target below instead.

So it should be something like:

```ruby
spec.ios.deployment_target = '6.0'
spec.osx.deployment_target = '10.8'
```

---

Adding a linter warning could make sense, yes

**Comment by DanToml** [comment]
It might be worth filing an issue on [CocoaPods/Core](https://github.com/CocoaPods/Core) to add better enforcement of this in the data model :+1:
