### ISSUE TITLE
Issues in jenkin integration

### ISSUE THREAD

**Issue by kiranvarma** [CocoaPods/CocoaPods#6735]
Team, 

We are having a continuous integration through jenkins, It is working well recently, suddenly getting below issue 

Library/Ruby/Site/2.0.0/rubygems/dependency.rb:318:in `to_specs': Could not find 'cocoapods-core' (= 1.2.1) among 13 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=file:/Users/administrator/.jenkins/plugins/ruby-runtime/WEB-INF/lib/stapler-jruby-1.209.jar!/gem:/Users/administrator/Software/ruby', execute `gem env` for more information
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1402:in `block in activate_dependencies'

Below are the steps did to resolve. 

- Uninstall the cocoapods
- Install again 

But still facing the issue, Why suddenly getting the issue. Please suggest

**Comment by dnkoutso** [comment]
Seems like an issue on your setup, not really cocoapods related?

**Comment by prabhjotAppmobi** [comment]
I am also facing the same issue. Is it resolved?
