### ISSUE TITLE
cocoapods project can use object-c and swift ?

### ISSUE THREAD

**Issue by WhatIsLionKing** [CocoaPods/CocoaPods#6737]
https://i.stack.imgur.com/1qvDt.png

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
