### ISSUE TITLE
pod search issue.

### ISSUE THREAD

**Issue by jacinzhang** [CocoaPods/CocoaPods#6741]
➜  ~ pod search AFNetwroking

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod search AFNetwroking
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.6.7
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.1 (8E1000a)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 30a645cd325f9e9072b8f936fd758736388d12d4
               me:arch-ios_specs - git@git.elenet.me:arch.mobile/iOS_specs.git @ 3ad99efb2ace039f33379fda48e01e90cfd964df
               mobile-ios-specs - git@git.elenet.me:eleme.mobile.ios/ios-specs.git @ 0e23683bf89523927dfc140d86a269da40b4063a
               mobile-specs - git@git.elenet.me:eleme.mobile.ios/Specs.git @ 2667f5f5011ca87a29d39e8db35bc1c9611f95e9
               moretv-specs - git@git.moretv.cn:mobile-ios/Specs.git @ eb142521fb992b63ee61300d8fdcdd64b6e6a851
               PPTVPodSpecs - git@gitlab:rockyzhang/pptvpodspecs.git @ 0fe55de2348f59e4b942694b3c64778cea6a17c2
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
JSON::ParserError - 784: unexpected token at '"],"PPTV_P2PSDK":["PPTV_P2PSDK"],"PPTV_StreamingSDK":["PPTV_StreamingSDK"],"Streaming":["PPTV_StreamingSDK"],"RockyFang":["PPTV_StreamingSDK"],"rockyfang@pptv.com":["PPTV_StreamingSDK"],"PulsingHalo":["PulsingHalo"],"Component":["PulsingHalo"],"For":["PulsingHalo"],"Creating":["PulsingHalo"],"Pulsing":["PulsingHalo"],"Animation":["PulsingHalo"],"Great":["PulsingHalo"],"Annotations":["PulsingHalo"],"And":["PulsingHalo"],"Beacons":["PulsingHalo"],"shu223":["PulsingHalo"],"shuichi0526@gmail.com":["PulsingHalo"],"TransitionKit":["TransitionKit"],"block-based":["TransitionKit"],"State":["TransitionKit"],"Machine":["TransitionKit"],"API":["TransitionKit"],"Objective-C.":["TransitionKit"],"Blake":["TransitionKit"],"Watters":["TransitionKit"],"blakewatters@gmail.com":["TransitionKit"],"boost":["boost"],"iOS-WebP":["iOS-WebP"],"WebP":["iOS-WebP"],"image":["iOS-WebP"],"decoder":["iOS-WebP"],"encoder":["iOS-WebP"],"Sean":["iOS-WebP"],"Ooi":["iOS-WebP"],"sean.ooi@me.com":["iOS-WebP"],"openssl":["openssl"]}}'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Cellar/ruby/2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=784%3A+unexpected+token+at+%27%22%5D%2C%22PPTV_P2PSDK%22%3A%5B%22PPTV_P2PSDK%22%5D%2C%22PPTV_StreamingSDK%22%3A%5B%22PPTV_StreamingSDK%22%5D%2C%22Streaming%22%3A%5B%22PPTV_StreamingSDK%22%5D%2C%22RockyFang%22%3A%5B%22PPTV_StreamingSDK%22%5D%2C%22rockyfang%40pptv.com%22%3A%5B%22PPTV_StreamingSDK%22%5D%2C%22PulsingHalo%22%3A%5B%22PulsingHalo%22%5D%2C%22Component%22%3A%5B%22PulsingHalo%22%5D%2C%22For%22%3A%5B%22PulsingHalo%22%5D%2C%22Creating%22%3A%5B%22PulsingHalo%22%5D%2C%22Pulsing%22%3A%5B%22PulsingHalo%22%5D%2C%22Animation%22%3A%5B%22PulsingHalo%22%5D%2C%22Great%22%3A%5B%22PulsingHalo%22%5D%2C%22Annotations%22%3A%5B%22PulsingHalo%22%5D%2C%22And%22%3A%5B%22PulsingHalo%22%5D%2C%22Beacons%22%3A%5B%22PulsingHalo%22%5D%2C%22shu223%22%3A%5B%22PulsingHalo%22%5D%2C%22shuichi0526%40gmail.com%22%3A%5B%22PulsingHalo%22%5D%2C%22TransitionKit%22%3A%5B%22TransitionKit%22%5D%2C%22block-based%22%3A%5B%22TransitionKit%22%5D%2C%22State%22%3A%5B%22TransitionKit%22%5D%2C%22Machine%22%3A%5B%22TransitionKit%22%5D%2C%22API%22%3A%5B%22TransitionKit%22%5D%2C%22Objective-C.%22%3A%5B%22TransitionKit%22%5D%2C%22Blake%22%3A%5B%22TransitionKit%22%5D%2C%22Watters%22%3A%5B%22TransitionKit%22%5D%2C%22blakewatters%40gmail.com%22%3A%5B%22TransitionKit%22%5D%2C%22boost%22%3A%5B%22boost%22%5D%2C%22iOS-WebP%22%3A%5B%22iOS-WebP%22%5D%2C%22WebP%22%3A%5B%22iOS-WebP%22%5D%2C%22image%22%3A%5B%22iOS-WebP%22%5D%2C%22decoder%22%3A%5B%22iOS-WebP%22%5D%2C%22encoder%22%3A%5B%22iOS-WebP%22%5D%2C%22Sean%22%3A%5B%22iOS-WebP%22%5D%2C%22Ooi%22%3A%5B%22iOS-WebP%22%5D%2C%22sean.ooi%40me.com%22%3A%5B%22iOS-WebP%22%5D%2C%22openssl%22%3A%5B%22openssl%22%5D%7D%7D%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
/usr/local/lib/ruby/gems/2.3.0/gems/gh_inspector-1.0.2/lib/gh_inspector/sidekick.rb:83:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
	from /usr/local/lib/ruby/gems/2.3.0/gems/gh_inspector-1.0.2/lib/gh_inspector/sidekick.rb:32:in `search'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gh_inspector-1.0.2/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /usr/local/lib/ruby/gems/2.3.0/gems/gh_inspector-1.0.2/lib/gh_inspector/inspector.rb:59:in `search_exception'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:65:in `report_error'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:396:in `handle_exception'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:337:in `rescue in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:325:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'
➜  ~

**Comment by DanToml** [comment]
This looks like you have an invalid specification in your PPTV Spec Repo. Run `pod repo lint` to identify and fix it.
