### ISSUE TITLE
Unnecessary `.swift-version` file for Objective-C only pods

### ISSUE THREAD

**Issue by atreat** [CocoaPods/CocoaPods#6742]
When trying to lint some private podspecs I've written get failure messages that my `.swift-version` file is not correct.
```
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run:
    `echo "2.3" > .swift-version`.
```

This is caused by the validator always adding this message if the `dot_swift_version` is nil ([source](https://github.com/CocoaPods/CocoaPods/blob/c310381f4a054b86971598160ccc37c3423629f5/lib/cocoapods/validator.rb#L149)).

If possible, can the validator check to see if any swift files are included in the project? Or could the podspec define the languages it uses such that if Swift is not included this validation won't occur? I find it odd that I need to include a `.swift-version` file even though my pod does not use Swift.

```
$ pod --version
1.2.1
```

**Comment by dnkoutso** [comment]
Yes! Good issue, want to try and make a PR for it? It is annoying that this shows up as an error message even though its irrelevant.

**Comment by atreat** [comment]
Sure I can try to open a PR.

I'll do some reading to see if I can look for Swift sources dynamically, but if you know off-hand if this is possible could you link to some code that may already be in place? If not I can add a spec configuration for this.

**Comment by dnkoutso** [comment]
In `validator.rb` it looks like there is a method:

```ruby
def used_swift_version
...
end
```

You should be able to use that. Also ensure to write a test (spec) in `validator_spec.rb`

**Comment by atreat** [comment]
Sweet! Thanks I'll check it out. Will also make sure its spec'd.

**Comment by atreat** [comment]
Is there a good way to run the specs? I've branched off of master and written a fix, but none of the unit tests pass when I run without my changes in place.

[CONTRIBUTING.md](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) doesn't seem to have any instructions.

**Comment by dnkoutso** [comment]
You can use for a specific spec:

```
bundle exec bacon ./spec/unit/generator/xcconfig/xcconfig_helper_spec.rb
```

for all tests I think:
```
bundle exec rake spec:all
```

**Comment by atreat** [comment]
I didn't have the submodules (do'h).

For posterity (and future newcomers):
```
$ git submodule init
$ git submodule update
```

**Comment by DanToml** [comment]
Fixed by https://github.com/CocoaPods/CocoaPods/pull/6750

**Comment by HusamAamer** [comment]
**FIXED** : I've just added a summary which was blank string `s.summary = ''`.
