### ISSUE TITLE
How to edit and save Podfile by the CocoaPods lib?

### ISSUE THREAD

**Issue by danfeng** [CocoaPods/CocoaPods#6746]
```
podfile = Pod::Podfile.from_file(@path);

pods.each { |name| podfile.pod name }

## podfile.save?
```

**Comment by danfeng** [comment]
and, `p podfile  ##input :{"target_definitions"=>[{"name"=>"Pods", "abstract"=>true, "platform"=>{"ios"=>"9.0"}, "uses_frameworks"=>true, "dependencies"=>["JSONKit", "AFNetworking", "BEKit"], "children"=>[{"name"=>"TestAutoConfig", "dependencies"=>["BEKit"], "children"=>[{"name"=>"TestAutoConfigTests", "abstract"=>false, "inheritance"=>"search_paths"}, {"name"=>"TestAutoConfigUITests", "abstract"=>false, "inheritance"=>"search_paths"}]}]}], "sources"=>["https://github.com/CocoaPods/Specs.git", "git@git.oschina.net:mvn/Specs.git"]}`,but,how to save the local Podfile?

Thanks！

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
