### ISSUE TITLE
remote: Repository not found.

### ISSUE THREAD

**Issue by kiranvarma** [CocoaPods/CocoaPods#6747]
Team, 

I am facing a issue in getting data from private repository, It is giving remote: repository not found. 
We are using the same repo in other machines and they are working fine. 

I have installed all cocoapods multiple times and installed again. 

Current Version : 1.2.1 (Latest)
Path **/Users/administrator/Software/ruby/gems/cocoapods-1.2.1/lib/cocoapods.rb** But in other machines i mentioned has a different path **/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods.rb**

Don't know the path is creating the issues, We are able to download the public pods but when getting private pod getting the issue. 

we are using below URLs in the podfile
source 'https://github.com/company/ios-specs.git'
source 'https://github.com/cocoaPods/Specs.git'

We are using that machine as jenkins server.

How can it be resolved

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
