### ISSUE TITLE
pod lib lint passes locally but not on travis (Dependency mismatch)

### ISSUE THREAD

**Issue by startupthekid** [CocoaPods/CocoaPods#6751]
I have a library, [FeathersRestSwift](https://github.com/startupthekid/feathers-swift-rest), that depends on another library, [FeathersSwift](https://github.com/startupthekid/feathers-swift). 

The podspec for FeathersRestSwift is fairly simple:

```
Pod::Spec.new do |s|
  s.name         = "FeathersSwiftRest"
  # Version goes here and will be used to access the git tag later on, once we have a first release.
  s.version      = "3.0.1"
  s.summary      = "REST transport provider for FeathersSwift"
  s.description  = <<-DESC
                   REST provider for FeathersSwift for making HTTP connections to a
                   FeathersJS backend.
                   DESC
  s.homepage     = "https://github.com/startupthekid/feathers-swift-rest"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author       = "startupthekid"

  s.ios.deployment_target = "8.0"
  s.osx.deployment_target = "10.10"
  s.tvos.deployment_target = "9.0"
  s.watchos.deployment_target = "2.0"
  s.source       = { :git => "https://github.com/startupthekid/feathers-swift-rest.git", :tag => "#{s.version}" }

  s.default_subspec = "Core"

  s.subspec "Core" do |ss|
    ss.source_files = "FeathersSwiftRest/Core/*.{swift}"
    ss.framework = "Foundation"
    ss.dependency 'Result'
    ss.dependency 'Feathers'
    ss.dependency 'Alamofire'
    ss.dependency 'ReactiveSwift'
  end

  s.pod_target_xcconfig = {"OTHER_SWIFT_FLAGS[config=Release]" => "-suppress-warnings" }
end
```

And when I run `pod lib lint FeathersSwiftRest.podspec` locally, it passes and all is good with the world.

However, on travis, `pod lib lint` fails saying:

`Specs satisfying the `Feathers` dependency were found, but they required a higher minimum deployment target.) during validation.`

I went through and checked and both podspecs for both libraries have the same deployment targets and all the targets in each of the frameworks has the same deployment target as well. And because this happens only on Travis, I can't reproduce the issue locally.

The failing build job is here: https://travis-ci.org/startupthekid/feathers-swift-rest/jobs/235693019.

Anyone have any idea why it'd pass locally but not on travis? Before each `pod lib lint`, I'm also doing a `pod repo update --silent`.

**Comment by startupthekid** [comment]
I'm going to close this, I managed to get builds to pass by removing `--silent` on `pod repo update`. No idea why that works but it does

**Comment by victorlaerte** [comment]
Removing `--silent` from `pod repo update` also worked for me. 
But this issue should not be reopened ? Seems to be a bug when using --silent on travis
