### ISSUE TITLE
Pod install, installing wrong version of the pods. Possibly using cached specs.

### ISSUE THREAD

**Issue by ugenlik** [CocoaPods/CocoaPods#6754]
I have two Macs, running the same version of cocoapods and exact same podfile

One of them can install the latest version of some pods but other one doesnt. 

Both machines:
 
```
pod --version
1.2.1
``` 
In both machines, Podfile.lock and Pods folder is removed from the repo (.gitignore ignores it anyways)

Both:
```
pod cache clean --all
```

Both:
```
Cleaned derived data folder
```

Machine A: 

```
Installing AMScrollingNavbar (3.3.1)
Installing Alamofire (4.4.0)
Installing DGElasticPullToRefresh (1.1)
Installing DeviceKit (1.0.1)
Installing Firebase (3.16.0)
Installing FirebaseAnalytics (3.8.0)
Installing FirebaseCore (3.6.0)
Installing FirebaseCrash (1.1.6)
Installing FirebaseInstanceID (1.0.10)
Installing FirebaseRemoteConfig (1.3.4)
Installing GoogleToolboxForMac (2.1.1)
```

MachineB:
```
Installing AMScrollingNavbar (3.3.3)
Installing Alamofire (4.4.0)
Installing DGElasticPullToRefresh (1.1)
Installing DeviceKit (1.0.1)
Installing Firebase (4.0.0)
Installing FirebaseAnalytics (4.0.0)
Installing FirebaseCore (4.0.0)
Installing FirebaseCrash (2.0.0)
Installing FirebaseInstanceID (2.0.0)
Installing FirebaseRemoteConfig (2.0.0)
Installing GoogleToolboxForMac (2.1.1)
```

Looks like Machine B is installing latest versions.
https://cocoapods.org/pods/Firebase

I have also tried to uninstall and reinstall the cocopods 

```
gem list --local | grep cocoapods
sudo gem uninstall cocoapods
sudo gem uninstall cocoapods-core
sudo gem uninstall cocoapods-deintegrate
sudo gem uninstall cocoapods-downloader 
sudo gem uninstall cocoapods-plugins
sudo gem uninstall cocoapods-search
sudo gem uninstall cocoapods-stats
sudo gem uninstall cocoapods-trunk
sudo gem uninstall cocoapods-try
```

Why are specs not updated? Where does cocopods caches this specs.... This is ridiculous...

**Comment by ugenlik** [comment]
uninstalling everything then removing the master repo worked

    gem list --local | grep cocoapods
    sudo gem uninstall cocoapods
    sudo gem uninstall cocoapods-core
    sudo gem uninstall cocoapods-deintegrate
    sudo gem uninstall cocoapods-downloader 
    sudo gem uninstall cocoapods-plugins
    sudo gem uninstall cocoapods-search
    sudo gem uninstall cocoapods-stats
    sudo gem uninstall cocoapods-trunk
    sudo gem uninstall cocoapods-try

then

    rm -rf ~/.cocoapods/repos/master
    sudo gem install cocoapods

then

    pod setup --verbose

**Comment by orta** [comment]
I think you probably needed to run `pod repo update` - when CocoaPods fails to find a pod, it should tell you this in the error message if you're using `pod install`. If you're doing `pod update` then it will assume you know that you want your dependency tree to update.

**Comment by matejukmar** [comment]
I had to delete Podfile.lock and then it installed correct version.

**Comment by DarkoDamjanovic** [comment]
In my experience this is a dependency problem. E.g. using pod 'Google/Analytics' instead of pod 'GoogleAnalytics' or pod 'Google/SignIn' instead of pod 'GoogleSignIn' caused also to load the wrong Firebase version.

**Comment by endogenesis** [comment]
Have same problem, two machines, exact same podfile.lock, but different sources.

**Comment by FrancoSabadini** [comment]
I'm having the same problem but none of the suggestions above fixed it. Is there an actual fix for this?
