### ISSUE TITLE
CocoaPods Website Search not working

### ISSUE THREAD

**Issue by sivatamilmani** [CocoaPods/CocoaPods#6757]
# Report

## What did you do?
Going to https://cocoapods.org and searched for pods doesn't work.

## What did you expect to happen?
List all available pods

## What happened instead?
API Call https://search.cocoapods.org/api/v1/pods.picky.hash.json?query=text&ids=20&offset=0&sort=quality from the webpage returns a 503

## CocoaPods Environment
https://cocoapods.org

**Comment by Noodlekim** [comment]
Yeah. This is emergency!

**Comment by segiddins** [comment]
See https://github.com/CocoaPods/cocoapods.org/issues/319 . The search server has been running out of memory lately

**Comment by Liandas** [comment]
still have same issue. #emergency!

**Comment by nourallahtq** [comment]
still not working until today

**Comment by Praveen-Balpande** [comment]
search not working its very inconvenience.
