### ISSUE TITLE
I can not find my pod on CocoaPods.org

### ISSUE THREAD

**Issue by hemangshah** [CocoaPods/CocoaPods#6760]
I can see this output in Terminal, however, the Pod doesn't exist.

<img width="597" alt="screen shot 2017-05-30 at 3 09 10 pm" src="https://cloud.githubusercontent.com/assets/3313412/26577464/178a9280-454a-11e7-87c3-cf5b9993f987.png">

What's the problem?

**Comment by dnkoutso** [comment]
Not sure what's wrong here...I cant find your pod either, maybe @orta has any guesses for this?

**Comment by hemangshah** [comment]
I have removed the Pods from CocoaPods. The reason, after adding my Pod with above name. I had to use the printer_logger everywhere, that's what I didn't want. I will come up with a good solution.

**Comment by orta** [comment]
@hemangshah you can use `module_name` in the pod spec to define what the import name would be in a user's project.

**Comment by hemangshah** [comment]
@orta, thank you. I will try this.

**Comment by hemangshah** [comment]
@orta , can you give me an example of specifying module_name with the spec? Right now, I am using it like this and couldn't build.

    s.module_name      = "Printer.swift"


    - ERROR | module_name: The module name of a spec should be a valid C99 identifier.

**Comment by chih98** [comment]
I believe a module name should be
```ruby
s.module_name = "Printer"
```

I believe the `.swift` is invalidating the name.

**Comment by pavanidivya48** [comment]
Hi I'm facing the same above issue. i created pod but when  i opened cocoapods.org, and search for my pod it's not showing. I do not know how to resolve this one. Can u please help me.

Thanks in Advance.

**Comment by hemangshah** [comment]
@pavanidivya48 - please share more details. What's your pod name etc. If you've taken the screenshot like me then post it as well.

**Comment by pavanidivya48** [comment]
@hemangshah Hi, Please check the below screenshot

![Screenshot 2019-08-08 at 3 52 21 PM](https://user-images.githubusercontent.com/53815631/62766434-17557e00-bab0-11e9-80b1-00c6d88e3376.png)

**Comment by hemangshah** [comment]
@pavanidivya48 are you able to install your sample cocoapods like you integrate any other pods?

**Comment by pavanidivya48** [comment]
Yes, i'm able to install the pod but pod directories are empty.. 
please check the below screenshot.

![Screenshot 2019-08-10 at 11 16 16 AM](https://user-images.githubusercontent.com/53815631/62818129-4b887780-bb60-11e9-94e0-1420ec268bde.png)
