### ISSUE TITLE
Test Specs' schemes should include the test scheme

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#6765]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod lib lint --no-clean`

## What did you expect to happen?

The scheme for my pod with a test specification should have included the test schemes under the list of tests in the scheme editor

## What happened instead?

It did not, that list of tests was empty.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3 (8W132p)
         Git : git version 2.13.0
Ruby lib dir : /Users/segiddins/.rubies/2.4.1/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 91c57cfdfaedfa39aacf7fae74ce5339baba0e7c
               buithuyen - https://github.com/buithuyen/Specs.git @ a6e6fe0cef7644fe55139842bf8529013f9821dc
               eyeem - https://github.com/eyeem/CocoaPods-Specs.git @ 1749fee08c2524d992af4bf368566449ae7668b1
               master - https://github.com/CocoaPods/Specs.git @ 2875e9fb983932700917632035be09f6200903ba
               unityappstudio - https://github.com/unityappstudio/Specs.git @ 4c5d9046d47906df7b3bafa6641cb4e752f057a7
```

### Installation Source

```
Executable Path: /Users/segiddins/Development/Rainforest/CocoaPods/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.0
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.2.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
install! 'cocoapods',
  integrate_targets: false,
  share_schemes_for_development_pods: true

target 'Test' do
  platform :osx, '10.10'
  use_frameworks!
  pod 'FooBar', path: '.'
end
```

## Project that demonstrates the issue

https://github.com/segiddins/CocoaPods-Test-Spec-Test

**Comment by dnkoutso** [comment]
I believe this is already done. The podfile is missing `pod 'FooBar/Tests'` and it would automatically share the xcscheme.

**Comment by segiddins** [comment]
Ideally, the test scheme would appear under the framework schemes testable list. But not a huge deal

**Comment by dnkoutso** [comment]
I think to achieve adding CMD+U support to the framework scheme itself we need to update https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/project.rb#L800-L820 to provide a block to edit xcschemes as they get recreated. 

Otherwise we would have to re-save (which might slow things down) after `recreate_user_schemes` returns.
