### ISSUE TITLE
Cannot include non-modular header inside framework module

### ISSUE THREAD

**Issue by wikwie** [CocoaPods/CocoaPods#6771]
# Report

## What did you do?

I made a Objective-C wrapper around C++ library and want to include this wrapper independently in projects as pod.

I configured podspec file: 

`Pod::Spec.new do |s|
  s.name             = 'NAME'
  s.version          = '0.3.0'
  s.summary          = 'Wrapper around C++ lib.'
  s.description      = 'Wrapper around C++  lib.'

  s.homepage         = 'HOMEPAGE LINK'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'author' => 'email' }
  s.source           = { :git => 'git source', :tag => s.version.to_s }

s.platform     = :ios, '9.0'

s.requires_arc = true

s.source_files = 'Source/**/*.{h,m,mm,cpp}', 'SDK/include/Vuforia/*'

s.header_dir = 'Vuforia'

s.vendored_libraries = 'SDK/lib/arm/libVuforia.a'

other_frameworks =  [
'AVFoundation',
'MediaPlayer',
'SpriteKit',
'AudioToolbox',
'CoreMotion',
'CoreMedia',
'SystemConfiguration',
'OpenGLES',
'SceneKit'
]

other_ldflags = '$(inherited) -framework ' + other_frameworks.join(' -framework ')

s.public_header_files = 'Source/**/*.{h}' <-- objective c header 
s.private_header_files = 'SDK/include/Vuforia/*.{h}' <-- c++ header 

s.library = 'c++'

s.xcconfig  =  {
'ENABLE_BITCODE[sdk=iphoneos*]' => 'NO',
'OTHER_LDFLAGS[sdk=iphoneos*]' => other_ldflags,
'CLANG_CXX_LANGUAGE_STANDARD' => 'c++11',
'CLANG_CXX_LIBRARY' => 'libc++',
'SWIFT_INCLUDE_PATHS' => '${PODS_ROOT}/../../SDK/include/Vuforia'
}

end`

I made own repo for library and second for podspec.

Pod lib lint and pod repo push passed successfully.

Than I created a test swift project to check if pod works correctly (I added Bridging-Header-File and included Objective-C header inside)

`#import <Vuforia/VuforiaManager.h>`

## What did you expect to happen?

Everything should works correctly. 

## What happened instead?

I've got errors : "Could not build module 'Vuforia'" and "Include of non-modular header inside framework module" 

## Project that demonstrates the issue

![2017-06-01 13 54 33](https://cloud.githubusercontent.com/assets/6360968/26678678/ed46c56e-46d1-11e7-8694-9f80f059e5cc.png)

**Comment by MadeByDouglas** [comment]
this seems to be similar to this issue here https://github.com/CocoaPods/CocoaPods/issues/4420 but i'm not sure what the fix would be now
