### ISSUE TITLE
Add source static library framework CocoaPods

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#6772]
🌈
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## Introduction

This is a proposal and specification to add support for static library framework CocoaPods. For a combination of performance and dependency constraints, the currently supported dynamic library frameworks do not support some use cases. 

## Background

Currently CocoaPods requires static library frameworks with module maps to be binary (via vendored_frameworks). This is an impediment to providing source CocoaPods, since dynamic frameworks are not always viable:
  * If a pod has dependencies that are static library frameworks, the pod itself must be static.
  * The slower cold start time of dynamic libraries is not acceptable for some apps. We've measured around a 600 millisecond impact of each dynamic library on an iPhone 6.

The specific issue is that we'd like to incrementally open source Firebase and enable the open source build process to be inter-operable with the closed source build process. Firebase has historically release as several inter-dependent closed-source static library pods.  CocoaPods does not currently support building open source library pods that depend on closed-source static library pods, without hacks like **def installer.verify_no_static_framework_transitive_dependencies;** Also CocoaPods does not support building static library frameworks from source which is necessary to meet our performance requirements if we want to provide source CocoaPod support to our Swift users.

Xcode has built in support for creating dynamic library frameworks, but leaves static library framework construction to external scripts. CocoaPods already generates constructs to manage static libraries. The following section describes how to extend and/or replace the static library management with static frameworks.

## Specification 

Currently the static library build for a library Foo consists of the following components that are referenced by the CocoaPods generated xcconfig files:
  * A static library in _"$PODS_CONFIGURATION_BUILD_DIR/MyFoo/libFoo.a"_ 
    * referenced it by adding _"$PODS_CONFIGURATION_BUILD_DIR/MyFoo"_ to **LIBRARY_SEARCH_PATHS** in the generated xcconfig files
    *  and _-l"Foo"_ to **OTHER_LDFLAGS** 
  * The header files are copied into _"${PODS_ROOT}/Headers/Public/MyLibrary"_
    * The header path is added to **HEADER_SEARCH_PATHS**

Instead, a static library framework should be constructed at _"$PODS_CONFIGURATION_BUILD_DIR/MyFoo/Foo.framework"_. 
  * The static library should be moved to _"$PODS_CONFIGURATION_BUILD_DIR/MyFoo/Foo.framework/Foo"_. 
  * The The headers should be moved to _"$PODS_CONFIGURATION_BUILD_DIR/MyFoo/Foo.framework/Headers"_. 
  * A modulemap should be constructed at _"$PODS_CONFIGURATION_BUILD_DIR/MyFoo/Foo.framework/Modules/module.modulemap"_

For reference, see Swift code for generating a static framework [here](https://github.com/firebase/firebase-ios-sdk/blob/master/BuildFrameworks/build.swift#L147).

The xcconfig file should be generated exactly the same as it is for dynamic frameworks:
  * _"$PODS_CONFIGURATION_BUILD_DIR/MyLibrary"_ should be added to **FRAMEWORK_SEARCH_PATHS**
  * -iquote _"$PODS_CONFIGURATION_BUILD_DIR/MyLibrary/MyLibrary.framework/Headers"_ should be added to **OTHER_CFLAGS**
  * _-framework "MyLibrary"_ should be added to **OTHER_LDFLAGS**

This works because Xcode's underlying build tools don't care about whether the library contained in a framework structure is static or dynamic. The link will be attempted either way.

## Phasing and Options
  1. If a pod depends on binary static pod and no binary dynamic pods, automatically build a static framework pod for itself and all of its dependencies.
  1. Add a mechanism to the podspec to specify a source pod should be built statically even when !use_frameworks is specified
  1. Future, consider podspec and podfile options to specify definitely dynamic or static or preferred dynamic or static.

## Related Issues
[Swift Cocoapod can't import Firebase pod dependencies](https://github.com/CocoaPods/CocoaPods/issues/6138)
[Development Pods - No Such Module Found while Example project is okay](https://github.com/CocoaPods/CocoaPods/issues/5368)
[Prevent Transitive Dependency Errors in Swift Project with Vendored Frameworks](https://github.com/CocoaPods/CocoaPods/issues/3289)
This issue replaces [Add support for source static library framework CocoaPods](https://github.com/CocoaPods/CocoaPods/issues/6651)

**Comment by dnkoutso** [comment]
Thanks for the report. This will be rather relatively hard to integrate but it is an enhancement that can be done.

**Comment by jlaws** [comment]
Carthage already added support for this. Here is a great analysis:

https://blog.automatic.com/how-we-cut-our-ios-apps-launch-time-in-half-with-this-one-cool-trick-7aca2011e2ea

**Comment by paulb777** [comment]
Fixed by #6811

**Comment by freak4pc** [comment]
Sorry for bumping this thread but it seems as states in [this comment](https://github.com/CocoaPods/CocoaPods/pull/6811#issuecomment-318503856) that this is only for frameworks that describe themselves as able to be built statically. 

Is there any ongoing effort regarding allowing (via a Podfile) to define any (or all) dependencies of an app to be built as static frameworks? to reduce launch time as described in @jlaws comment above?
