### ISSUE TITLE
how to deal with "ld: library not found for -lYXAdSDKRelease" error

### ISSUE THREAD

**Issue by george-luofz** [CocoaPods/CocoaPods#6776]
## What did you do?
Firstly,I create a private static library, the static library use another private framework and a bundle, i archive these files with zip command,then i upload the zip file into my own public github repository. (All of these are learning from [publish-a-universal-binary-ios-framework-in-swift-using-cocoapods](https://eladnava.com/publish-a-universal-binary-ios-framework-in-swift-using-cocoapods/),thanks)
secondly, i will use this private static libary from github repository with cocoapod.I create an podspec file.The content of my podspec is like below:
```
Pod::Spec.new do |s|
  s.name         = 'YXAdSDK'
  s.version      = '2.1.0'
  s.summary      = 'summary'
  s.homepage     = 'https://e.yixia.com'
  s.author             = { 'george_luofz' => 'luofuzhong@yixia.com' }
  s.ios.deployment_target = '8.0'
  s.source       = { :http => 'https://github.com/george-luofz/LibYXAdSDK/raw/master/LibYXAdSDK.zip' }
  s.frameworks = ['UIKit', 'Foundation','CoreFoundation','SystemConfiguration','AVKit','AdSupport','AVFoundation']
  s.vendored_libraries = 'libYXAdSDK2/YXAdSDKRelease.a'
  s.vendored_frameworks = 'libYXAdSDK2/YXSDKWebP.framework'
  s.library = 'sqlite3'
  s.public_header_files = 'libYXAdSDK2/include/*.h'
  s.resources = 'libYXAdSDK2/YXAdSDK.bundle'
  s.user_target_xcconfig =   {'OTHER_LDFLAGS' => ['-lObjC']}
end
```
Thirdly,i did the command 'pod init' and edit the podfile like below:
```source 'https://github.com/george-luofz/LibYXAdSDK.git'
target 'Test_MyselfPod' do
  pod 'YXAdSDK', :podspec => ‘.’
end
```
Finally,i did the 'pod install',and open the xcworkspace file.when i build it , it build failed.The error shows:
```
ld: library not found for -lYXAdSDKRelease.
Linker command failed with exit code 1 (use -v to see invocation)
```
i had try all of the answers in stackoverflow.but it did nothing.Maybe anywhere is error.how can i solve it? 

## What did you expect to happen?
build my test project sussessfully.
## What happened instead?
it build error.
### Stack
```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : george-luofz - https://github.com/george-luofz/LibYXAdSDK.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               master - https://github.com/CocoaPods/Specs.git @ 8b28a6b32d6b4445ea0eabc8038a1b94fe0387dd
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/george-luofz/LibYXAdSDK.git'

target 'Test_MyselfPod' do
  pod 'YXAdSDK', :podspec => ‘.’

end
```
`
## Project that demonstrates the issue
the static library github repository is [static library](https://github.com/george-luofz/LibYXAdSDK)
the test project github repository is [test project](https://github.com/george-luofz/Test_MyselfPod)

**Comment by george-luofz** [comment]
anybody help @kommen @ericallam @lukeredpath @farcaller @aanand

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by george-luofz** [comment]
ok！thanks a lot

**Comment by farcaller** [comment]
It's also a very bad idea to ping people at random, FWIW (I don't have any idea what are you discussing here).
