### ISSUE TITLE
umbrella header not found

### ISSUE THREAD

**Issue by iSwiftUser** [CocoaPods/CocoaPods#6777]
# Report

## What did you do?
I am using Telerik Framework in my Project and i created the Dev pod for my project.When i added this cocoa pod to my another project(pod install) and i can see the Cocoa pod project under Development pods.But  when i tried building the project,i am getting build error. Umbrella header not found.

As TelerikUI do not have any umbrella header ,so i created modulemap file for the same.If i use the Telerik Framework in my project(without creating it a pod) ,it works fine.

## CocoaPods Environment
I am using latest cocoa Pods environment with Xcode 8.3

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
