### ISSUE TITLE
Run examples on Circle against Xcode 9 as well

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/CocoaPods#6781]
Exactly as it says in the title, let's make sure  didn't break things.

**Comment by CodingMarkus** [comment]
Be sure to also test out the new build system (see release notes), as when taking an existing project with pods that builds fine with Xcode 8, it also builds fine in Xcode 9 but when I switch to the new build system, I get a lot of codesigning errors and sometimes umbrella headers are not found (all when building pods).

**Comment by aledalgrande** [comment]
Related to this, is there an issue like https://github.com/CocoaPods/CocoaPods/issues/6117 for Xcode 9? New default project settings create warnings for pods.

**Comment by segiddins** [comment]
@aledalgrande that's unrelated, but there's a PR to CocoaPods/Xcodeproj bumping the project defaults

**Comment by dnkoutso** [comment]
@segiddins @DanToml can this be closed with https://github.com/CocoaPods/CocoaPods/pull/7366?

**Comment by segiddins** [comment]
Yup!
