### ISSUE TITLE
The Pod' target has transitive dependencies that include static binaries:/Pods/Crashlytics/iOS/Crashlytics.framework and /Pods/Fabric/iOS/Fabric.framework)

### ISSUE THREAD

**Issue by timonchev** [CocoaPods/CocoaPods#6785]
after update 1.3.0 I see issues with installing this lib from podspec .

Podspec file:

```
#s.xcconfig = { 'LIBRARY_SEARCH_PATHS' => "$(SRCROOT)/Pods/**" }
s.ios.deployment_target = '8.0'
s.requires_arc = true

s.compiler_flags = '-ObjC', '$(inherited)',

s.pod_target_xcconfig = {'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}"/**',
'OTHER_LDFLAGS'          => '$(inherited) -ObjC -l"z" -framework "Crashlytics" -framework "Fabric" "-all_load" ',
'ENABLE_BITCODE'         => 'YES'
}

s.resource_bundles = {
'core_ios' => [ 'Assets.xcassets', 'Fonts/*.ttf']
}
s.dependency 'Fabric'
s.dependency 'Crashlytics'
end
```

Pod file:

```
use_frameworks!
platform :ios, '9.0'


target 'Project-name' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  

  # Pods for Project-name
  pod 'core_ios', :path => 'Project-name/core_ios'
  
  pod 'GoogleMaps'
  pod 'GoogleSignIn'
  pod 'GooglePlaces'
  
  target 'Project-nameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  targetProject-nameUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pre_install do |installer|
      def installer.verify_no_static_framework_transitive_dependencies; end
  end
end
```

What's the problem? I didn't saw same in 1.2.1 version.  -undefined dynamic_lookup flag also no helps

**Comment by orta** [comment]
Looks like the runtime hacking of CocoaPods is failing in your Podfile - there was probably work down around `installer.verify_no_static_framework_transitive_dependencies`

However, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
