### ISSUE TITLE
When pushing new version to CocoaPods, outdated files that no longer exist in my source are being used

### ISSUE THREAD

**Issue by Daltron** [CocoaPods/CocoaPods#6790]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ I tried uploading a new version of my repo [NotificationBanner](https://github.com/Daltron/NotificationBanner) to CocoaPods

## What did you expect to happen?

My new CocoaPod version to pass `spec lint` validation

## What happened instead?

ℹ Please replace this with of what happened instead.  

when I run `pod spec lint`, I get the following errors:

```ruby
 -> NotificationBannerSwift (1.3.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] xcodebuild:  NotificationBannerSwift/NotificationBanner/Classes/NotificationBanner.swift:73:29: error: type 'MarqueeLabel.MarqueeType' has no member 'left'
``` 

The reason I know its using an outdated file is because of that second error. That line 73 it is complaining about USED to be what it is reporting, but has since been updated and is no longer the same. 
I went to: `/Users/MyUsername/Library/Caches/CocoaPods/Pods/External/NotificationBannerSwift/{hash}`
and noticed that my most up to date files were not being used.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/Dalton/.rbenv/versions/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3756a835bdf3b499f0e2c52e325dc316423c9d90
```

### Installation Source

```
Executable Path: /Users/Dalton/.rbenv/versions/2.2.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

`pod install NotificationBannerSwift`

You will notice that line 73 inside `NotificationBanner.swift` is different in the version that CocoaPods provides from the version on the `master` branch  [NotificationBanner](https://github.com/Daltron/NotificationBanner)

**Comment by orta** [comment]
`pod spec lint` will use a tagged version of your library, so it's likely that you'd need to update the tag that the pod spec refers to, if you want to verify that it works locally you can use `pod lib lint`.

**Comment by Daltron** [comment]
@orta when I run `pod spec lint`, it passes validation with no problems but when I `pod trunk push`, I receive the same errors as mentioned above. Why is this the case?

**Comment by orta** [comment]
Ah, might be a caching issue then, try [using](https://guides.cocoapods.org/terminal/commands.html#group_cache) `pod cache clean` to wipe it

**Comment by Daltron** [comment]
@orta Thank you for your help. Even though I've done [this](https://guides.cocoapods.org/making/making-a-cocoapod.html) over a dozen times, I incremented the version number, and performed the steps again in that guide and everything worked. I believe it was something to do on my end but unsure what. Consider this issue closed for good. Thanks again! 😄
