### ISSUE TITLE
An unexpected version directory `Model.xcdatamodeld` was encountered

### ISSUE THREAD

**Issue by siempay** [CocoaPods/CocoaPods#6796]
# Report
` pod --version : 1.2.1`

## What did you do?
I've created a private pod I coded it in pure swift 
I followed these [tuto1](https://code.tutsplus.com/tutorials/creating-your-first-cocoapod--cms-24332), [tuto2](https://code.tutsplus.com/tutorials/managing-private-pods-with-cocoapods--cms-25137) 

and I then I went to a project, create a pod file `pod init` 
added this to it 
`source "ssh://192.168.1.16/home/brahim/TacosDeLyonPVModel.git"`
`target 'test7' do`
 ` use_frameworks!`
`pod 'TacosDeLyonPVModel' , '~> `0.0.2.1'
`end
`
and then in terminal `pod install`
in spec file of my pod i set `  s.source_files  = "TacosDeLyonPVModel/**/*.{h,m,swift,xcdatamodeld}", "TacosDeLyonPVModel/*.{h,swift,xcdatamodeld}"
` even if I dont have `*.m`, I have only one `*.h`, one `*.xcdatamodeld` and lot of `*.swift` 
## What did you expect to happen?
  Install pod dependencie correctly.

## What happened instead?
`[!] An unexpected version directory` `Model.xcdatamodeld` `was encountered for the ` `/Users/brahim/.cocoapods/repos/TacosDeLyonPVModel/TacosDeLyonPVModel` `Pod in the ``TacosDeLyonPVModel` `repository.
`

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 88e71eaf050dbbf784fa92ae1b77000ff26a6d4e
               TacosDeLyonPVModel - ssh://192.168.1.16/home/brahim/TacosDeLyonPVModel.git @ 9e5a103efc7e3b8d548c50ef2ee318677e5a68ee
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.2.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

source "ssh://192.168.1.16/home/brahim/TacosDeLyonPVModel.git"

source 'https://github.com/CocoaPods/Specs.git'

target 'test7' do

  use_frameworks!


 	pod 'Material', '~> 2.0'
   	pod 'Hue'
   	pod 'FontAwesome.swift' 
  	pod 'TacosDeLyonPVModel' , '~> 0.0.2.1'
  

end
```

the project is private

**Comment by SanyasiraoM** [comment]
@siempay Did you resolve it?

**Comment by siempay** [comment]
@SanyasiraoM  No man I didnt

**Comment by dnkoutso** [comment]
There is insufficient information here for us to debug this issue. The source you provide in your podfile is a local IP address in which we cannot access. Please provide a sample project for us to be able to successfully debug the issue.

Closing.

**Comment by siempay** [comment]
thats the point, I was having an issue with installing a pod that I have created in my local server
