### ISSUE TITLE
Define Build Script inputs and outputs to get fast incremental builds with Xcode 9

### ISSUE THREAD

**Issue by hartbit** [CocoaPods/CocoaPods#6797]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Xcode 9 comes with a new Build System (which is not yet enabled by default). One of the advantages of the new build system is incredibly fast incremental builds through very good task dependency management. Unfortunately, even when changing no files, the build system will still run the Cocoapods generated Build Scripts because they don't define inputs or outputs, and therefore the build system can't reason about them.

If we could define those inputs and outputs, we could get instant incremental builds!

@neonichu Think you might have some inputs to provide here :)

**Comment by dnkoutso** [comment]
Agreed. I believe support exists to edit the inputs/outputs from the Xcodeproj gem.

**Comment by neonichu** [comment]
I agree that this is the way to go with run script phases 👍

**Comment by dnkoutso** [comment]
What happens if you have different inputs for each configuration, debug vs release? Do we need to split those script phases into as many configuration phases instead?

**Comment by segiddins** [comment]
@dnkoutso my guess is that you'd specify all of the inputs for all configurations

**Comment by dnkoutso** [comment]
PR is up https://github.com/CocoaPods/CocoaPods/pull/6800
