### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _parse_numeric_port

### ISSUE THREAD

**Issue by lyuxxx** [CocoaPods/CocoaPods#6799]
## What did you do?  
 Run `gem install cocoapods`

## What did you expect to happen?  
Install cocoapods correctly.

## What happened instead?
dyld: lazy symbol binding failed: Symbol not found: _parse_numeric_port
  Referenced from: /Users/liuyuxuan/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/x86_64-darwin16/socket.bundle
  Expected in: flat namespace

dyld: Symbol not found: _parse_numeric_port
  Referenced from: /Users/liuyuxuan/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/x86_64-darwin16/socket.bundle
  Expected in: flat namespace

I got this error,I can't solve it after I googled.Anyone can help?

**Comment by CHPisces** [comment]
> ## What did you do?
> Run `gem install cocoapods`
> 
> ## What did you expect to happen?
> Install cocoapods correctly.
> 
> ## What happened instead?
> dyld: lazy symbol binding failed: Symbol not found: _parse_numeric_port
> Referenced from: /Users/liuyuxuan/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/x86_64-darwin16/socket.bundle
> Expected in: flat namespace
> 
> dyld: Symbol not found: _parse_numeric_port
> Referenced from: /Users/liuyuxuan/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/x86_64-darwin16/socket.bundle
> Expected in: flat namespace
> 
> I got this error,I can't solve it after I googled.Anyone can help?

I got this error too,I can't solve it after I googled.Anyone can help?
