### ISSUE TITLE
Objective-C project is forced to use 'echo "2.3" > .swift-version' command

### ISSUE THREAD

**Issue by archerLj** [CocoaPods/CocoaPods#6809]
# Report

## What did you do?
I new an Objective-C project `A` and then verify my podspec file use the command of
```
pod spec lint --sources='git@github.com:LFModulizationDemo/PrivateRepo.git,https://github.com/LFModulizationDemo/PrivateRepo.git'  A.podspec --verbose --allow-warnings
```
My project is Objective-C project, and it still let me use  `echo "2.3" > .swift-version`. and if i use this command, all my source in `A/A/*.{h,m}` can not be imported by `pod install` in `MainProject` project.

## What happened instead?
This is the error info:
```
[!] The spec did not pass validation, due to 1 error.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run: 
    `echo "2.3" > .swift-version`.
```

## CocoaPods Environment

1.2.1

## Project that demonstrates the issue
You can find all the source in here:
[https://github.com/LFModulizationDemo](https://github.com/LFModulizationDemo);

**Comment by dnkoutso** [comment]
This has been fixed on master. Can you use `--verbose`, the swift error message is irrelevant to linting. I do not have time to look atyour sample repo today but will do over the next week.

I am fairly certain there is another problem than the swift error message.

**Comment by paulb777** [comment]
Looks like an unsatisfied pod dependency on HandyFrame:

`    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `HandyFrame` depended upon by `A``

**Comment by archerLj** [comment]
Maybe The error of `- ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification forHandyFramedepended upon byA` is caused by  `--sources='git@github.com:LFModulizationDemo/PrivateRepo.git,https://github.com/LFModulizationDemo/PrivateRepo.git'`. This is the address of my private podspec. If i do not use this option, my private podspec `B_Category ` can not be found.

**Comment by dnkoutso** [comment]
@archerLj do `pod repo list` use the repo name not the repo url.

**Comment by archerLj** [comment]
@dnkoutso thx. it's worked.
