### ISSUE TITLE
CocoaPods with Dynamic Frameworks

### ISSUE THREAD

**Issue by jn-se** [CocoaPods/CocoaPods#6818]
Assume the following setup:

A Swift project with a main target that links two dynamic Cocoa Touch Framework targets.
* MainProject
  * MainTarget
  * FrameworkA
  * FrameworkB

1. Framework A links CocoaPodM.
2. Framework B links CocoaPodN.
3. The test target for the main target and FrameworkA require the Pod CocoaPodTestLoggingX.
4. The test target for the FrameworkB requires the Pod CocoaPodTestLoggingY.

Is the following Podfile correct?

```
platform :ios, '8.0'
use_frameworks!

target 'MainTarget' do
    
    pod 'CocoaPodM', '~> 1.0'
    pod 'CocoaPodN', '~> 1.0'
    
    target 'MainTarget Tests' do
        inherit! :search_paths
        pod 'CocoaPodTestLoggingX, '~> 1.0'
    end
    
end

target 'FrameworkA' do
    
    pod 'CocoaPodM', '~> 1.0'
    
    target 'FrameworkATests' do
        inherit! :search_paths
        pod 'CocoaPodTestLoggingX, '~> 1.0'
    end
end

target 'FrameworkB' do

    pod 'CocoaPodN', '~> 1.0'
    
    target 'FrameworkBTests' do
        inherit! :search_paths
        pod 'CocoaPodTestLoggingY, '~> 1.0'
    end
end
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by jn-se** [comment]
I created an issue at StackOverflow.
https://stackoverflow.com/questions/44670416/cocoapods-with-dynamic-frameworks

But in addition I would recommend to create a documentation in the project that shows different sample Podfiles for specific conditions.

**Comment by jn-se** [comment]
Until now there are no responses in Stackoverflow. Seems that the question is to specific.

I would suggest to reopen the issue because the documentation for that scenario is missing and I assume the use case is not very rare.
