### ISSUE TITLE
Incorrect "Smart quotes" Warning on `pod install`

### ISSUE THREAD

**Issue by johndanek** [CocoaPods/CocoaPods#6830]
> Before you start, are you using the latest CocoaPods release?
I am using 1.2.1

* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace this with what you did.  
Ran `pod install`

## What did you expect to happen?

ℹInstall all pods with no warnings

## What happened instead?

ℹGot the following warning:
`[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.`

There are no smart quotes in my file. I am not using TextEdit nor do I have smart quotes enabled in vim.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.8.1
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c20dba8c21d04b75eb81a4349015646ec8c926e6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, "10.0"
# Uncomment this line if you’re using Swift
use_frameworks!

#workspace "TeamCoco.xcodeproj/project.xcworkspace/"

target "TeamCoco" do
 pod "GVRSDK"
 pod "youtube-ios-player-helper", "~> 0.1.4"
end

**Comment by orta** [comment]
I'm pretty surprised by this, as the checker code is super simple - https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/podfile.rb#L278

Might be worth seeing what happens when you run this code in a REPL with the original Podfile.

**Comment by johndanek** [comment]
It's a pretty simple podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, "10.0"
# Uncomment this line if you’re using Swift
use_frameworks!

#workspace "TestProj.xcodeproj/project.xcworkspace/"

target "TestProj" do
 pod "GVRSDK"
 pod "youtube-ios-player-helper", "~> 0.1.4"
end
```

**Comment by dnkoutso** [comment]
@johndanek can you replace all `""` with single quotes and see if it works?

**Comment by johndanek** [comment]
@dnkoutso I replaced with all single quotes, and still get the warning. Here is my current Podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you’re using Swift
use_frameworks!

#workspace 'TestProj.xcodeproj/project.xcworkspace/'

target 'TestProj' do
 pod 'GVRSDK'
 pod 'youtube-ios-player-helper', '~> 0.1.4'
end

```

**Comment by johndanek** [comment]
Oh man, I found it. Sorry for wasting your time. It's the apostrophe in `you're` in that Swift comment. I think I copied and pasted that from the Google VR tutorial, or somewhere. Thanks!

**Comment by dnkoutso** [comment]
ha! nice.
