### ISSUE TITLE
fail to get plugin with specific tag name

### ISSUE THREAD

**Issue by arthur-tam** [CocoaPods/CocoaPods#6832]
# Report

## What did you do?

I use it with Cordova platform add ios

## What did you expect to happen?
success get the plugin: phonegap-plugin-push
p.s. in config.xml
&lt;plugin name="phonegap-plugin-push" spec="https://github.com/phonegap/phonegap-plugin-push#v2.0.0-rc5" /&gt;
and it can success get the plugin for cocopods 1.2.1

## What happened instead?
fail with this error:
Failed to install 'phonegap-plugin-push': undefined
Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: Version should contain only numbers and dots

### Stack

```
   CocoaPods : 1.3.0.beta.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3433d0889817aa8253d7d701fe4b38a993f894f1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
```
Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: Version should contain only numbers and dots
```

Looks like your error message, which doesn't seem related to CocoaPods. I'd recommend you go to the Cordova documentation and take a look around this.
