### ISSUE TITLE
Include .cc file as a header

### ISSUE THREAD

**Issue by sharkpc0813** [CocoaPods/CocoaPods#6833]
# Report

## What did you do?

ℹ Please replace this with what you did.  

 Run `pod lib lint`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

```
- ERROR | [iOS] private_header_files: The pattern matches non-header files ({MYPROJECT}/libs/spdlog/include/spdlog/details/format.cc).
```

## What happened instead?

ℹ Please replace this with of what happened instead.  

I'm a user using c++ logging library and I found some including usage like below.
https://github.com/gabime/spdlog/tree/master/include/spdlog/fmt/bundled/format.h
```
// format.h
# include "format.cc"
```

When I'm include this header within my pods, it couldn't reference format.cc because there is no idea to copy the file as a header while pod lint(or build).

I'm trying to include it like other header files but pod occur an error.
(Put this in `private_header_files`)

```
- ERROR | [iOS] private_header_files: The pattern matches non-header files (.../spdlog/include/spdlog/details/format.cc).
```

I think there is a various way to include header files,  .cc file too.

Any idea to include this?

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5dcfd43939e84e4b8b9d47c177c46332f839da29
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-art         : 1.0.0
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
I'm wary of including cc as a header file would break more things, as `*.cc` is commonly accepted as [a c++ source file](https://encrypted.google.com/search?hl=en&q=cc%20vs%20cpp).

**Comment by sharkpc0813** [comment]
I agree with you it is not used usually. 

I couldn't find exact convention for this but I found below.

`*.cc` file would be included exceptionally. (This is different with including `*.cpp` as you had searched.)

```
As an exception, a template that is explicitly instantiated for all relevant sets of 
template arguments, or that is a private implementation detail of a class, is allowed 
to be defined in the one and only .cc file that instantiates the template.
```
https://google.github.io/styleguide/cppguide.html#Self_contained_Headers

**Comment by orta** [comment]
👍 yeah this seems reasonable, wanna take a look about adding it in cocoapods/core?

**Comment by sharkpc0813** [comment]
The constants in cocoapods/core is seems to be referencing a constants in cocoapods/xcodeproj and put my commit there.
