### ISSUE TITLE
No email received for pod trunk register

### ISSUE THREAD

**Issue by tomaszmaciejko** [CocoaPods/CocoaPods#6836]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

Run the following `pod trunk register sdk@mobiledonky.com 'Tomasz Maciejko' --description='macbook pro'`

## What did you expect to happen?

Receive an email with a link to start a session

## What happened instead?

No email received

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 71aff9c91d3bf728472d02ae96aa3e2211cc1c3d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Additional information
This issue is related to https://github.com/CocoaPods/CocoaPods/issues/5630 but experienced on another machine. Please check if we have not being blacklisted again

**Comment by ben-moore** [comment]
Hi, is there anyone available who can investigate this for us please, it's a critical blocking issue for us at present.

**Comment by orta** [comment]
Looks like we got a rejection again from that email, I've removed the bounce again - I'm not really sure what that error message means though.

![screen shot 2017-07-03 at 14 34 22](https://user-images.githubusercontent.com/49038/27804415-c8417b12-5ffc-11e7-9ade-8b3ac4447121.png)

Anyway, I've removed the block from our side 👍
