### ISSUE TITLE
Cocoapods vs. Xcode9b2: [CP] Check Pods Manifest.lock phase fails

### ISSUE THREAD

**Issue by dhmspector** [CocoaPods/CocoaPods#6840]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Tried to use Cocoapods 1.2.1 with Xcode9beta2

ℹ Please replace this with what you did.  
 1. Start with Apple's ARKit example code
 2. type `pod init` in directory at same level as existing Xcode project file
 3. Edit resulting Podfile - add a pod (in this case `RealmSwift`)
 4. Run `pod install` to create/install workspace file and initial Pods
 5. Attempt to build and run project

## What did you expect to happen?

App should compile and run

## What happened instead?

App compiles but at end of build phase `[CP] Check Pods Manifest.lock` the following error occurred:

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 9.0 (9M137d)
         Git : git version 2.13.0 (Apple Git-88)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ded197537fab349d546221cd16496d50f36776c2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARKitExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARKitExample
  pod 'RealmSwift'
 

end
```

## Project that demonstrates the issue

N/A project builds - fails only at the `[CP] Check Pods Manifest.lock` build phase

**Comment by dhmspector** [comment]
_Update_:  After a few selective edits changing 
```bash
diff "${PODS_PODFILE_DIR_PATH}/Podfile.lock" "${PODS_ROOT}/Manifest.lock" > /dev/null
```
to 
```bash
diff "${SRCROOT}/Podfile.lock" "${SRCROOT}/Pods/Manifest.lock" > /dev/null
```
 
additional errors occur in the pods integration phase ... 

```
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/spector/Library/Developer/Xcode/DerivedData/ARKitExample-awcfttgvlzvokvggcyiuborrenrr/Build/Intermediates.noindex/ARKitExample.build/Debug-iphoneos/ARKitExample.build/Script-C39B9792AC7FE0D039BDD3CA.sh
    cd /Users/spector/Work/Realm/ARKitTest
    /bin/sh -c /Users/spector/Library/Developer/Xcode/DerivedData/ARKitExample-awcfttgvlzvokvggcyiuborrenrr/Build/Intermediates.noindex/ARKitExample.build/Debug-iphoneos/ARKitExample.build/Script-C39B9792AC7FE0D039BDD3CA.sh

/Users/spector/Work/Realm/ARKitTest/Pods/Target Support Files/Pods-ARKitExample/Pods-ARKitExample-resources.sh: line 7: /resources-to-copy-ARKitExample.txt: Permission denied
```

My best guess from trying to run the script in pieces is that It looks like the like the root cause is `PODS_ROOT` isn't  being globally defined...

**Comment by jshier** [comment]
There's this from the Xcode 9 release notes:
```
The new build system may not define all of the environment variables that the standard build system defines when launching shell scripts. If the new build system is not supplying an environment variable which your scripts use, please file a bug with the name of the environment variable, the expected value you saw under the old build system, and a brief explanation about your usage of the variable. (24541618)
```
That seems like it would only apply to system or Xcode provided environment variables in the new build system, but it could be related.

**Comment by dhmspector** [comment]
Yeah - this would appear to be the case - even if I define POD_ROOT to be SRCROOT at the lock check, the  copy resources phase as then, lastly inside the Pods-<TARGETNAME>-resources.sh file, I can eventually get the project to compile ... however once I try to use a module that would be part of the pod resources build -- in this case  RealmSwift -- Xcode cannot see the module.  So it looks like Xcode isn't seeing the resulting Cocoapods frameworks even after they get compiled.

**Comment by dnkoutso** [comment]
Updated labels. New build system not 100% supported or updated for CocoaPods. I believe this may have been fixed already since we have a large project that works with Xcode 9 and CocoaPods 1.3.1.

**Comment by yuri-swift** [comment]
It has not been fixed yet in Xcode 9.1.
The way to avoid it is  as follows.

・Open Xcode left side panel and select your app in PROJECT and select info tab.
・Find  **Configurations** from it.
・Configurations has two items Debug and Release and each of them have your app name file.
・If you click on that file, two more items will appear.
・From the item on the right, change each **Based on Configuration file** to None.
・Close Xcode.
・Open Xcode and set the item that was changed to None again.

I think that the image below will help you understand.

<img width="737" alt="2017-11-09 10 33 24" src="https://user-images.githubusercontent.com/18731884/32584037-ca0ee784-c539-11e7-90c8-d5c361de2e46.png">

Good hack everyone!(๑˃̵ᴗ˂̵)و

**Comment by sed76** [comment]
What about XCode 9.2?

**Comment by dnkoutso** [comment]
@dhmspector @sed76 is this still a problem with Xcode 9.4 or Xcode 10 beta?
