### ISSUE TITLE
Avoiding the transitive dependency error when linking to static libraries subspec

### ISSUE THREAD

**Issue by JosueB** [CocoaPods/CocoaPods#6841]
# Report

## What did you do?
I am creating a  pod to reuse some functionalities of my app that depends on GoogleMaps and google-maps-ios-utils. 

I created the pod and added the google-maps-ios-utils manually because of the use_frameworks issue, and installed GoogleMaps as a normal pod. 

MyFuel pod file contains 

```
target 'FuelMap' do
  use_frameworks!
  pod 'GoogleMaps'
end
```

and the FuelMap pod contains the google-maps-ios-utils library as explained here. 
https://github.com/googlemaps/google-maps-ios-utils/blob/master/Swift.md

pod spec: 
```
...
s.subspec 'Google-Maps-iOS-Utils' do |base|
    base.source_files = 'FuelMap/**/*.{h,m}'
    base.dependency 'GoogleMaps'
  end
```

## What did you expect to happen?

From my regular project I should be able to run pod install and by doing this the GoogleMaps  and google-maps-ios-utils should be added since I want to be able to call the classes in the framework that use both of these libraries. 

## What happened instead?
In the regular project I run pod install and I keep receiving the transitive error. 
The 'Pods-Mock' target has transitive dependencies that include static binaries: ...

**Comment by midea-sdk** [comment]
the same problem for me.

**Comment by paulb777** [comment]
With CocoaPods 1.4.0, use the `static_framework` option introduced in #6811 to depend on static library CocoaPods.
