### ISSUE TITLE
Link target with multiply targets

### ISSUE THREAD

**Issue by oleander** [CocoaPods/CocoaPods#6845]
I've this setup.

``` ruby
target "A" do
  pod "Pod1"
  target "ATests" do
    pod "Pod2"
  end
end

target "B" do
  pod "Pod3"
  target "BTests" do
    pod "Pod4"
  end
end

target "SharedTests" do
  pod "Pod5"
end  
```

How do I link targets `ATests` and `BTests` with `SharedTests`  but not `A` and `B`. Was hoping to use something like `link_with`, but that seems to be long gone.

My goal is to share code, not necessarily pods, between the test targets.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by oleander** [comment]
Aha, you're right. Thanks for the links!

**Comment by oleander** [comment]
Just posted a question here, in case someone else has the same one; https://stackoverflow.com/questions/44904591/link-one-target-with-multiply-other-targets
