### ISSUE TITLE
Add -fno-objc-arc to part of files in podspec

### ISSUE THREAD

**Issue by RingoD** [CocoaPods/CocoaPods#6849]
# Report

## What did you do?

Run `pod spec lint --verbose --skip-import-validation`

## What did you expect to happen?

Lint my own podspec with adding `-fno-objc-arc` for part of files 

## What happened instead?

The only way I find to do so is to define a subspec 'noarc'. But it fails while linking due to dependency. Some of the no-arc files depend on the other arc file. So I can't solve it through subspec.

So I wonder the right way to define no-arc, or it's just not supported?

### Stack

```
   CocoaPods : 1.3.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c551226530fbdb04ba66ebfcd92316d304a42b32
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by RingoD** [comment]
I didn't find out the right way to solve this on StackOverflow. So I ask you to make sure if it's really not supported.
If so, then it can be a feature we needed, which means "enhancement".

**Comment by hatjs880328s** [comment]
ss.requires_arc = false
