### ISSUE TITLE
Inheriting search paths for group of test targets

### ISSUE THREAD

**Issue by rafaelnobrepd** [CocoaPods/CocoaPods#6853]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

add `inherit! :search_paths` clause in an abstract target to share search paths in all test targets from the targets that contains them:
```
target 'MyApp' do
    use_frameworks!

    pod 'A'
    pod 'B'
    pod 'UITestHelper/App'

    abstract_target 'Tests' do
        use_frameworks!
        inherit! :search_paths
        
        target 'MyApp Tests'
        target 'MyApp UITests'
        target 'MyApp SnapshotTests'
        
        pod 'Nimble'
        pod 'UITestHelper'
    end
end
```

## What did you expect to happen?

This used to work fine in 1.1.1. Pod install was happy, and I could Build the App and run the Tests.

## What happened instead?

On 1.2.1, pod install fails i.e cannot inherit in abstract target. If I remove inherit, test targets won't build. I just want the app paths to be added to each unit test target. What is the supported way to share paths to multiple test targets in 1.2.1 and up ?

**Comment by dnkoutso** [comment]
1.2.1 intentionally added a check to prevent adding `inherit! :search_paths` on abstract targets. The PR that did it https://github.com/CocoaPods/CocoaPods/issues/5342

The recommended way is to explicitly define this on every test target that you want to inherit search paths.

Its inconvenient but it's correct now.
