### ISSUE TITLE
Prevent files deletions

### ISSUE THREAD

**Issue by rehannali** [CocoaPods/CocoaPods#6854]
Hey, I install pod and there are some missing functionality and i want to add files.
I asked from author and copy files direct to my project but whenever i install another project or run pod update it delete those file which i copied. 
How can i prevent those deletion from Pods? Please help me to fix this problem.

**Comment by dnkoutso** [comment]
Hey there, this looks like a great example of a question that you should ask on StackOverflow - there is an active tag CocoaPods where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
