### ISSUE TITLE
how to share the same target to other multiple targets

### ISSUE THREAD

**Issue by yuanjilee** [CocoaPods/CocoaPods#6857]
I use react-native only in target3 that as a framework belong to target1, there is a target2 copy by target1 . then, how to share target3 to both target1 & target2. the blew Podfile is error with `The target 'target3' is declared twice for the project 'Target3/Target3.xcodeproj'.`

    target 'target1' do
      use_frameworks!
  
      target 'target3' do
        use_frameworks!
    
        react_native_path = 'node_modules/react-native/'
        pod 'React', :path => react_native_path, :subspecs => [
        'Core',
        'BatchedBridge',
        ]
      end
    end

    target 'target2' do
      use_frameworks!
  
      target 'target3' do
        use_frameworks!
    
        react_native_path = 'node_modules/react-native/'
        pod 'React', :path => react_native_path, :subspecs => [
        'Core',
        'BatchedBridge',
        ]
      end
    end

**Comment by amorde** [comment]
You need to inverse the hierarchy so that the shared target is in the outer scope    
```ruby
target 'target3' do
    use_frameworks!

    react_native_path = 'node_modules/react-native/'
    pod 'React', :path => react_native_path, :subspecs => [
        'Core',
        'BatchedBridge',
    ]

    target 'target1' do
        # target1 stuff
    end

    target 'target2' do
        # target2 stuff
    end
end
````

Any further issues might be a better question for StackOverflow

**Comment by yuanjilee** [comment]
@amorde  very appreciate for your answer, but it not use for the issue. because `target3` as a framework is contained in `target1`, so if do as your suggestion, it throw a error: `Unable to find a target named target1`.

**Comment by orta** [comment]
Sounds like you want abstract_target instead

**Comment by yuanjilee** [comment]
I found the solution finally = =

if anyone has the equal question, see: https://stackoverflow.com/a/45729238/5557953
