### ISSUE TITLE
Stale bot not closing issues

### ISSUE THREAD

**Issue by SD10** [CocoaPods/CocoaPods#6862]
### Stale bot not closing issues
Currently, probot doesn't close stale issues for stale labels that contain spaces. [#44](https://github.com/probot/stale/pull/44)

Your stale label: `s1:awaiting input`

If you change this to `s1:awaiting_input` or another label without spaces then update your `stale.yml`, you can reap the full benefit of probot. 

Just thought I'd let you know as we had to deal with it in another repo 😅

**Comment by orta** [comment]
<3

**Comment by segiddins** [comment]
This seems like a bug that should be fixed in probot, rather than us having to change label names?

**Comment by orta** [comment]
I _think_ it's about label identifiers _not_ names, so the id for "This That" would be "this_that", not "this that".

**Comment by SD10** [comment]
@segiddins Couldn't agree more. This issue links to a PR solving the bug. I'm just notifying you all because I don't know if it will be merged in a timely manner.

Probot uses the search query `is:issue is:open label:label name` to find stale issues. It doesn't wrap labels with spaces in quotes, resulting in an invalid query.

**Comment by segiddins** [comment]
Sorry, I saw other PRs in response to this with us changing label names and figured this was the right place to leave my 2 :cents:

**Comment by bkeepers** [comment]
This has been fixed in probot. Thanks @SD10 for the pull request!

**Comment by orta** [comment]
Awesome, I'll revert our changes in another repo - thanks all
