### ISSUE TITLE
Use Xcode 9's recommended project settings

### ISSUE THREAD

**Issue by saagarjha** [CocoaPods/CocoaPods#6863]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

> Note: If this is a known issue and you're just waiting for Xcode 9 to be public before working on it, please close/ignore this.

## What did you do?

1. Run `pod install` on a project and then open it in Xcode 9.

## What did you expect to happen?

CocoaPods generates a project that doesn't have any warnings.

## What happened instead?

A project that was generated with a suggestion to "Update to recommended settings", with the following suggestions:

<img width="615" alt="screen shot 2017-07-11 at 23 46 39" src="https://user-images.githubusercontent.com/13786931/28105174-3a78f7ea-6693-11e7-880f-d23336fd0142.png">

### Stack

```
   CocoaPods : 1.3.0.beta.2
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.13 (17A306f)
       Xcode : 9.0 (9M174d)
         Git : git version 2.13.2
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cee025f7d7ddc49076c481ecd08d8bd382428294
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :osx, '10.11'

target 'iina' do
  
  use_frameworks!

  # Pods for iina
  pod 'MASPreferences', :git => 'https://github.com/saagarjha/MASPreferences.git'
  pod 'Just', :git => 'https://github.com/saagarjha/Just.git'
  pod 'AEXML'
  pod "PromiseKit", :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift4-beta1'
  pod 'GzipSwift', :git => 'https://github.com/1024jp/GzipSwift.git', :branch => 'swift4'
  pod 'GRMustache.swift', :git => 'https://github.com/saagarjha/GRMustache.swift.git'
  pod 'Sparkle'

#  target 'iinaTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end
```

## Project that demonstrates the issue

[Here's one.](https://github.com/lhc70000/iina/) You should probably try out the `swift-4` branch, since the other ones don't build in Xcode 9.

**Comment by dnkoutso** [comment]
I believe this has been merged but not released yet.

**Comment by saagarjha** [comment]
Great! Look forward to seeing this in a later version, then.

**Comment by dpfannenstiel** [comment]
Has this been release as of 1.3.1?  I'm seeing it as I attempt to migrate my project to Xcode 9.

**Comment by dpfannenstiel** [comment]
@saagarjha Hey, has this issue actually been resolved for you?  I'm on 1.3.1 and am still getting hit by it.

**Comment by saagarjha** [comment]
@dpfannenstiel No, it doesn't look like it. Maybe I'm missing a setting somewhere?

**Comment by dpfannenstiel** [comment]
@dnkoutso Can you confirm that this has been released.  I'm still seeing it with 1.3.1.

**Comment by ZevEisenberg** [comment]
+1 still seeing this with 1.3.1 and Xcode 9 beta 6.
<img width="422" alt="screen shot 2017-09-02 at 11 57 25 am" src="https://user-images.githubusercontent.com/464574/29996955-0cffe4a6-8fd6-11e7-889b-62368102d208.png">

**Comment by kreeger** [comment]
And I'm still seeing this on the GM of Xcode 9 (not a surprise there!).

**Comment by adamstener** [comment]
Also seeing this with Xcode 9 GM on 1.3.1 but there are a few more warnings on mine.
<img width="578" alt="screen shot 2017-09-14 at 8 49 32 am" src="https://user-images.githubusercontent.com/680770/30433335-d24dcb36-9929-11e7-9fcf-4dbf84f91920.png">

**Comment by kylemay-gridstone** [comment]
Any plans to rectify this?

**Comment by dnkoutso** [comment]
This has not shipped yet and it will ship with CocoaPods 1.4.0 (including betas)

**Comment by Codeido** [comment]
@dnkoutso when do you think that this version comes out?

**Comment by damacster** [comment]
@dnkoutso do we have an estimated timeframe when we can expect an updated version of CocoaPods with support for Xcode 9?

**Comment by dnkoutso** [comment]
@damacster the best i can give is hopefully next week. We do not have any set dates for releases. Keep in mind most people who contribute to this project do this in their free time.

I cant promise a specific date.

**Comment by dpfannenstiel** [comment]
@damacster thanks for responding. I understand it’s an open source project and greatly appreciate all the hard work the community does continuing to grow the project. An early misunderstanding about the state of this issue may have contributed to concern about the release. Especially since 1.3.1 was released so recently.

Again, thanks for all the hard work. It’s a wonderful project.

**Comment by damacster** [comment]
@dpfannenstiel Thanks Dustin, i totally understand. Your work and the work of others on this project is greatly appreciated.

**Comment by chrismanderson** [comment]
Should this issue be resolved in `1.4.0.beta.1`? I upgraded, ran a `pod install`, but still see the "Upgrade to recommended settings" prompt.

**Comment by dnkoutso** [comment]
Hm I ran the update with Xcode 9 and it did not produce any diff. Might need to inspect further.

**Comment by dnkoutso** [comment]
@chrismanderson what is the diff you see when you do select to update the settings?

**Comment by abagmut** [comment]
for me it adds lots of "lastKnownFileType = sourcecode.cpp.cpp;"
like http://take.ms/nl9Zb

**Comment by dpfannenstiel** [comment]
I installed the beta and it's building without the projects settings warning now.  Thanks.
(Note to self: Learn ruby.  Contribute.)

**Comment by dnkoutso** [comment]
The last known filetype I don't think that's part of the project settings and it's part of your configuration.

**Comment by abagmut** [comment]
installed last beta build
run Editor->Validate Settings... on Pods project file and still see this message http://take.ms/urkfv

**Comment by Blackjacx** [comment]
I also see the `Update to recommended settings` warning which includes e.g. the whole moduel optimization setting....

**Comment by dpfannenstiel** [comment]
Have you tried deleting your "Pods" folder and then running `pod install`? That's what worked for me.

**Comment by Blackjacx** [comment]
Jupp tried that at first 💃

**Comment by arn8tas** [comment]
Release please!

**Comment by dnkoutso** [comment]
This should be fixed by https://github.com/CocoaPods/Xcodeproj/pull/496.

We will very soon release 1.4.0.beta.2 so if this is still a problem please file a new issue.

**Comment by piotr-tobolski** [comment]
it still happens for me when using cocoapods 1.4.0.beta.2

**Comment by chrisvanbuskirk** [comment]
Concur.  Still a problem.  Why close this?

**Comment by orta** [comment]
Hi there both of you, it'd be nice if you followed the request from @dnkoutso just above - e.g. create a new issue showing what's changed. It's hard to keep track of issues on previously resolved issues at our scale. I'm going to lock this thread to keep more +1s.
