### ISSUE TITLE
Pod for Obj-c and Swift

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#6864]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I would like to know how to create a pod with an Obj-C target and another Swift? Using "pod lib create", it is asked "Objective-C or Swift".

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by iDevelopper** [comment]
Ok, thanks but pod lib create ask for Obj-c or Swift:

![2017-07-12_12-15-19](https://user-images.githubusercontent.com/1782450/28118812-e6082e3a-6712-11e7-9d87-2f0540f85e0b.png)

**Comment by iDevelopper** [comment]
It will be nice to propose a third option: Twice, no?

**Comment by iDevelopper** [comment]
* both

**Comment by orta** [comment]
It'd be nice, and you can make that improvement to [the pod-template](https://github.com/cocoapods/pod-template/) if you're interested in building and maintaining it 👍 .

**Comment by iDevelopper** [comment]
I am interested but I do not know enough about this project. I'm involved in other projects. I am really sorry. Never mind. It was just a suggestion for improvement.
