### ISSUE TITLE
Unable to find a specification for `OpenSSL (= 1.0.210)` depended upon by `XYZ`

### ISSUE THREAD

**Issue by ankit-thanekar007** [CocoaPods/CocoaPods#6865]
Hi , I'm trying to make a pod using OpenSSL , But I'm getting the attached error. I'm using the latest beta version -> **1.3.0.beta.2** . When I was on  1.2.1 I was getting the duplicate file name error, which was resolved after updating to latest version. I've tried using --sources but its giving me the same error . I'm using this terminal command for pod creation -> **pod lib lint ColorsG.podspec --sources='https://github.com/FredericJacobs/OpenSSL-Pod' --verbose** , If the sources has wrong link can anybody point me to the right one because this is the one I found. 

![screen shot 2017-07-12 at 4 06 36 pm](https://user-images.githubusercontent.com/26094255/28114074-e3cd5744-671c-11e7-82a5-3c6ad398e495.png)

**This is my subspec in podspec file**
s.subspec 'InAppPurchase' do |inApp|
inApp.source_files = 'ColorsG/InApp/*.{h,m}'
inApp.dependency 'OpenSSL', '1.0.210'
inApp.ios.vendored_library = 'Pods/OpenSSL-Classic/lib-ios/*.a'
inApp.vendored_libraries = 'libssl.a', 'libcrypto.a'

end

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by ankit-thanekar007** [comment]
@orta  Fair Enough thanks for quick reply!
