### ISSUE TITLE
pod spec lint succeeds but pod lib lint fails

### ISSUE THREAD

**Issue by davidair** [CocoaPods/CocoaPods#6868]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report 🌈

## What did you do?

`pod lib lint ~/.cocoapods/repos/master/Specs/6/1/e/nanopb/0.3.8/nanopb.podspec.json`

## What did you expect to happen?

Lint to pass successfully.

## What happened instead?

 -> nanopb (0.3.8)
    - ERROR | [nanopb/encode,nanopb/decode] file patterns: The `source_files` pattern did not match any file.
    - ERROR | [nanopb/encode,nanopb/decode] file patterns: The `public_header_files` pattern did not match any file.

Note: The pod spec lint command passes successfully:

`pod spec lint ~/.cocoapods/repos/master/Specs/6/1/e/nanopb/0.3.8/nanopb.podspec.json`

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin16.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.13.2.932.g7449e964c-goog
Ruby lib dir : /Users/davidair/.rbenv/versions/2.1.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7300d28e59787ac9d2a28b0cfcd3397ea306fece
```

### Installation Source

```
Executable Path: /Users/davidair/.rbenv/versions/2.1.3/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.2.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

**Comment by dnkoutso** [comment]
`pod spec lint` will clone the repo at the tag you specified, perhaps it clones a different tag compared to `lib lint` which uses your local sources present. You are linting a pod inside the repo which has no sources available.

This is not a bug in CocoaPods.
