### ISSUE TITLE
Adding source_files to podspec hides vendored_frameworks interface

### ISSUE THREAD

**Issue by rajohns08** [CocoaPods/CocoaPods#6872]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run `pod install` with the following Podfile:
```
platform :ios, '9.0'

target '{YOUR_TARGET}' do
  use_frameworks!
  pod 'AdamPodTest', '0.1.6'
end
```

## What did you expect to happen?

The host app that runs the `pod install` command should have the `AdamPodTest` framework added (which has a public class called `MyButton`). The host app should be able to `import AdamPodTest` in a View Controller and initialize a variable with `let button = MyButton()`.

## What happened instead?

When initializing the button variable with `let button = MyButton()`, Xcode has a compiler error `Use of unresolved identifier 'MyButton'`.

The issue must be with adding `source_files` to the [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/7/6/7/AdamPodTest/0.1.6/AdamPodTest.podspec.json) in `0.1.6`, because this issue doesn't occur if using version `0.1.5`. Also I noticed there was an automatically added `pushed_with_swift_version` key to my `.podspec.json` file when adding `source_files` which could have something to do with the issue.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : AdamPodTest - https://github.com/rajohns08/AdamPodTest.git @ 698b12f846d6e8cb25adf3cb7b714f7181696999
               master - https://github.com/CocoaPods/Specs.git @ 4e918cd0b84f1865270b90744a0d1f8d58033ce4
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'AdamPodTestApp' do
  use_frameworks!
  pod 'AdamPodTest', '0.1.6'
end
```

## Project that demonstrates the issue

https://github.com/rajohns08/AdamPodTestApp

**Comment by rajohns08** [comment]
Further proof that the `source_files` line is causing the problem can be seen by comparing versions [0.1.8](https://github.com/CocoaPods/Specs/blob/master/Specs/7/6/7/AdamPodTest/0.1.8/AdamPodTest.podspec.json) and [0.1.6](https://github.com/CocoaPods/Specs/blob/master/Specs/7/6/7/AdamPodTest/0.1.6/AdamPodTest.podspec.json) in which the only difference is the addition of the `source_files` line to the podspec. The 2 podspecs files literally point to the exact same zip source file.

**Comment by PhilippOtto89** [comment]
I´m facing the same issue with my podspec using vendored_framework. If the source_files point to any files my application is not able to access the attributes and methods inside of my binary framework.

**Comment by dnkoutso** [comment]
The problem probably lies because the vendored framework or library does not get linked to the target when you use source files.

Yes this must be fixed in CocoaPods but in the meantime you can split your podspec into two. One that *only* brings the vendored framework/library without any source files and the other that includes the source files.

**Comment by thatjuan** [comment]
Related to https://github.com/CocoaPods/CocoaPods/issues/6409
