### ISSUE TITLE
CocoaPods copy resources to multiple targets instead to copy to one target

### ISSUE THREAD

**Issue by oxview** [CocoaPods/CocoaPods#6874]
# Report
###
I'm created the XCode project with two targets:

1. **RootApp** - is single view application
2. **FrameworkWithXibs** - is framework with some ui resources

**RootApp** have embedded binaries:**FrameworkWithXibs**.

**FrameworkWithXibs** depend for CocoaPod (**DemoPod**).

**DemoPod** have a ViewController class with xib resource.

**DemoPod podspec** : 

```ruby
Pod::Spec.new do |s|
	s.name                  = 'DemoPod'
	s.version               = '0.0.1'
	s.summary               = 'DemoPod'
	s.homepage              = 'https://github.com/oxview/DemoPod'
	s.authors               = {'oxview' => 'oxview@gmail.com'}
	s.source                = {:git => 'https://github.com/oxview/DemoPod.git'}
	
	s.platform              = :ios, '8.0'
	s.requires_arc          = true 
	s.source_files 	        = 'Classes/*.{h,m}'
	s.resources             = 'Resources/*.{xib}'
end
```

Run command **pod install**. 

Build the **RootApp** target.

## After building I expect to have **RootApp.app** build like this : 

![screen shot 2017-07-14 at 5 35 36 pm](https://user-images.githubusercontent.com/28188080/28219664-0bb11da8-68bd-11e7-8dc6-bd877276e85d.png)

## What happened instead?

![screen shot 2017-07-14 at 5 35 09 pm](https://user-images.githubusercontent.com/28188080/28219220-7d337f54-68bb-11e7-9410-5fc6d7bd0033.png)

**DemoViewController.nib** is dublicated in **RootApp.app** bundle and in **FrameworkWithXibs.framework** but they need to be only in **FrameworkWithXibs.framework**

### Stack

```
   CocoaPods : 1.3.0.beta.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/oxview/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5dd3d65b019e5f289121baeabf35c1cbc6d7ff3f
```

### Installation Source

```
Executable Path: /Users/oxview/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'

target 'FrameworkWithXibs' do
    pod 'DemoPod', :git => 'https://github.com/oxview/DemoPod.git'
end

target 'RootApp' do

end
```

## Project that demonstrates the issue

- **Demo App** - https://github.com/oxview/DemoPodApp

- **DemoPod** - https://github.com/oxview/DemoPod

**Comment by umbri** [comment]
same

**Comment by umbri** [comment]
### Podfile

```
platform :ios, '8.0'

target 'FrameworkWithXibs' do
    pod 'DemoPod', :git => 'https://github.com/oxview/DemoPod.git'
end

target 'RootApp' do

end
```

I find that in ```RootApp``` CocoaPods will link ```DemoPod``` too, but from Podfile I expect that it will NOT link them.

**Comment by dnkoutso** [comment]
@umbri how do you know its linked? Does the Pods-RootApp.xcconfig include `-framework DemoPod` or `-l DemoPod`?

**Comment by umbri** [comment]
@dnkoutso Yes I copy it from there

**Comment by umbri** [comment]
@dnkoutso The most strange is that, I encounter this problem only when building framework that has a ```HostApp```

**Comment by dnkoutso** [comment]
ah yes this happens because the first target of yours in the Podfile is a framework. CocoaPods will automatically copy those pods/resources to the host app.

Probably in version 2.0.0 (no promises) this will be re-worked.

**Comment by umbri** [comment]
@dnkoutso changed to this:
```
platform :ios, '8.0'

target 'RootApp' do
    
end

target 'FrameworkWithXibs' do
    pod 'DemoPod', :git => 'https://github.com/oxview/DemoPod.git'
end
```

and I get same:
```
OTHER_LDFLAGS = $(inherited) -ObjC -l"DemoPod"
```

**Comment by dnkoutso** [comment]
The best bet right now is to use a `post_install` hook to manage this manually.

**Comment by umbri** [comment]
any examples ?

**Comment by umbri** [comment]
But with ```OTHER_LDFLAGS``` is not so big problem, but when I get like @oxview a framework with Resources, all this Resources are copied in RootApp and in Framework (as expected) as well, and all that garbage (resources) are useless in RootApp
