### ISSUE TITLE
Overview is empty on CocoaPods web site

### ISSUE THREAD

**Issue by evgenyneu** [CocoaPods/CocoaPods#6878]
Hi, the overview page is completely empty for the Cosmos library version 11.0.3 in all browsers I tried (Chrome, Safari, Firefox). I did `pod trunk push` about 12 hours ago with CocoaPods 1.2.0.beta.1. The Cosmos library version 11.0.3 is available for installation through cocoapods.

[https://cocoapods.org/pods/Cosmos](https://cocoapods.org/pods/Cosmos)

Thanks

**Comment by orta** [comment]
Please use the repos for CocoaPods.org / CocoaDocs for instructions on how to debug this kind of issue, this repo is only for CocoaPods the CLI tool.
