### ISSUE TITLE
Unknown class in Interface Builder file

### ISSUE THREAD

**Issue by rajohns08** [CocoaPods/CocoaPods#6885]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` and set custom class in Storyboard to public class from pod framework:

![screen shot 2017-07-18 at 11 50 40 am](https://user-images.githubusercontent.com/2711642/28329429-6ab6b692-6baf-11e7-9aa6-ea78fb1b0186.png)

I've also tried setting the `Module` to `VisaCheckoutSDK`, `Pods`, `Pods_AppName`, `CheckoutButton`, etc.

## What did you expect to happen?

I expected the ability to use the public class `CheckoutButton` from the `VisaCheckoutSDK` programmatically and in Storyboard.

## What happened instead?

The public class was accessible programmatically (e.g. `let button = CheckoutButton()` in a ViewController after `import VisaCheckoutSDK` declared), but not recognized in Storyboard.

![screen shot 2017-07-18 at 11 51 37 am](https://user-images.githubusercontent.com/2711642/28329449-7d4adf22-6baf-11e7-8351-1283fbc1e385.png)

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : AdamPodTest - https://github.com/rajohns08/AdamPodTest.git @ 698b12f846d6e8cb25adf3cb7b714f7181696999
               master - https://github.com/CocoaPods/Specs.git @ dd6422a36f7b38e72012ddfeb08e21f647e67420
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'MComm' do
  use_frameworks!
  pod 'VisaCheckoutSDK', '5.2.0-8.3.3'
end
```

## Project that demonstrates the issue

https://github.com/rajohns08/MComm

**Comment by dnkoutso** [comment]
I am not certain this is a cocoapods library issue. I think you need to use `VisaCheckoutButton` instead. Perhaps the framework is not exposing `CheckoutButton` for ID.

Does it actually work if you do not use cocoapods and manually link the framework?

**Comment by dnkoutso** [comment]
@rajohns08 even with linking manually the VisaCheckoutSDK.framework to another app I was still seeing "2017-10-12 16:54:01.671062-0700 SingleView[78881:2143979] Unknown class CheckoutButton in Interface Builder file.".

Going to close this as I do not believe its a CocoaPods issue.

**Comment by dnkoutso** [comment]
@rajohns08 during testing of your pod and project i noticed the project was yielding a lot of duplicate symbols and they seem to be related to the `TrusDefender.framework`.

For example:

```
objc[80501]: Class VisaURLConnection is implemented in both /Users/dimitris/Library/Developer/CoreSimulator/Devices/C4DB71F7-A850-4839-9BAD-ED8ED178B41A/data/Containers/Bundle/Application/07197E5F-E89E-4EEC-9126-BD79D19F7937/MComm.app/Frameworks/VisaCheckoutSDK.framework/VisaCheckoutSDK (0x10862fed0) and /Users/dimitris/Library/Developer/CoreSimulator/Devices/C4DB71F7-A850-4839-9BAD-ED8ED178B41A/data/Containers/Bundle/Application/07197E5F-E89E-4EEC-9126-BD79D19F7937/MComm.app/MComm (0x107ee2dd0). One of the two will be used. Which one is undefined.
```

It appears that `TrustDefender` executable inside `TrustDefender.framework` is not a dynamic shared library but a normal archive. This includes the same symbols as the one in `VisaCheckoutFramework` binary and hence the warnings.

Recommend fixing this in your pod for consumers.

**Comment by dnkoutso** [comment]
File:
```
file TrustDefender 
TrustDefender: Mach-O universal binary with 5 architectures: [arm_v7: current ar archive random library] [arm_v7s] [i386] [x86_64] [arm64]
TrustDefender (for architecture armv7):	current ar archive random library
TrustDefender (for architecture armv7s):	current ar archive random library
TrustDefender (for architecture i386):	current ar archive random library
TrustDefender (for architecture x86_64):	current ar archive random library
TrustDefender (for architecture arm64):	current ar archive random library
```
And
```
file VisaCheckoutFramework
VisaCheckoutSDK: Mach-O universal binary with 4 architectures: [i386: Mach-O dynamically linked shared library i386] [x86_64] [arm_v7] [arm64]
VisaCheckoutSDK (for architecture i386):	Mach-O dynamically linked shared library i386
VisaCheckoutSDK (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
VisaCheckoutSDK (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
VisaCheckoutSDK (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by rajohns08** [comment]
@dnkoutso how can I fix the duplicate symbol issues since the TrustDefender library is a static framework and provided to me by a 3rd party vendor? I opened up a separate issue about there here: https://github.com/CocoaPods/CocoaPods/issues/6895
