### ISSUE TITLE
Transitive dependencies problem

### ISSUE THREAD

**Issue by dgaedcke** [CocoaPods/CocoaPods#6889]
# Report

## What did you do?

I ran:
 pod lib lint  PMKFirebaseAuth.podspec --verbose

## What did you expect to happen?

I expected it to:
pull in deps for my project
build them
allow me to import them in my pod code

## What happened instead?
I got this:
```-> Installing nanopb (0.3.8)
  > Copying nanopb from `/Users/dgaedcke/Library/Caches/CocoaPods/Pods/Release/nanopb/0.3.8-22bc0` to
  `../../../../private/var/folders/__/fkx2m9h55n3135677_zflp3c0000gn/T/CocoaPods/Lint/Pods/nanopb`
  - Running pre install hooks
 -> PMKFirebaseAuth (0.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/__/fkx2m9h55n3135677_zflp3c0000gn/T/CocoaPods/Lint/Pods/FirebaseAuth/Frameworks/FirebaseAuth.framework)
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:434:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:426:in `each'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:426:in `block in verify_no_static_framework_transitive_dependencies'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:423:in `each'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:423:in `verify_no_static_framework_transitive_dependencies'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:486:in `block in install_pod'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:486:in `each'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:486:in `install_pod'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:306:in `block in perform_extensive_analysis'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:298:in `each'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:298:in `perform_extensive_analysis'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/validator.rb:79:in `validate'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/command/lib/lint.rb:65:in `block in run'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/command/lib/lint.rb:52:in `each'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/command/lib/lint.rb:52:in `run'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/bin/pod:23:in `load'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/bin/pod:23:in `<main>'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/dgaedcke/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
) during validation.```

## CocoaPods Environment

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.4.3
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/dgaedcke/.rvm/rubies/ruby-2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7d8664766f78891fe748c5b9f7a443565c7bf4c5
               twilio - https://github.com/twilio/cocoapod-specs @ cfa92127047dca210fc40619e50a5920b1ba4af9
```

## Project that demonstrates the issue

https://github.com/dgaedcke/PMKFirebaseAuth

although what's up there is an old version that I will replace in the next 10 mins

**Comment by dgaedcke** [comment]
I'm a beginner with CocoaPods and I don't know ObjC or all these compiler/framework settings either so if I'm doing something wrong, please be very specific with me....

**Comment by amorde** [comment]
This is a known limitation, you cannot have a pod which depends on another pod that is a statically compiled framework. I believe this is still an issue, although its possible its been fixed and not yet released

See #3267 , #2926

**Comment by dgaedcke** [comment]
thanks for the info.....those issues you linked have been rambling on for almost 3 years.   I'm not experienced enough to understand or implement the many approaches they propose.  (or to know which ones would still apply with todays version of things).   Are there any other sources where I can search for workarounds?

**Comment by paulb777** [comment]
PR #6811 is targeted for the CocoaPods 1.4.0 and will enable Objective C CocoaPods to depend upon transitive binary static library dependencies.  In the meantime, one possible workaround is to use the FirebaseUI approach of wrapping the static libraries. See https://github.com/firebase/FirebaseUI-iOS/blob/master/build.swift

**Comment by dgaedcke** [comment]
Thanks for that link.
I get the general idea that they wrap their dependencies as part of their build script.
But I can't get close to building because I'm failing at the "lib lint" stage....

Perhaps you are suggesting I just manually add the FirebaseAuth code to my project and circumvent CP altogether??
Thanks again for the pointers...
I see that 1.3 was just released to beta.....does that mean that 1.4 will follow reasonably soon?

**Comment by dnkoutso** [comment]
@paulb777 should we close this that now 1.4.0 static frameworks are in?

**Comment by paulb777** [comment]
After #6811, it's now possible for source CocoaPods to depend on statically compiled frameworks.
