### ISSUE TITLE
The 'Pods-App' target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by hamilyjing** [CocoaPods/CocoaPods#6892]
hi,

i will do a framework as private pod spec. the spec file blow:

Pod::Spec.new do |s|

  s.name         = "YZT_iOS_Common_Tool"
  s.version      = "0.0.18"
  s.summary      = "iOS common tool"
  s.license      = "COMMERCIAL"
  s.homepage     = "http://git-ma.paic.com.cn/ToaApp/YZT_iOS_Common_Tool"
  s.author       = { "JJ" => "gongjian_001@126.com" }
  s.platform     = :ios, "8.0"
  s.source       = { :git => "http://git-ma.paic.com.cn/ToaApp/YZT_iOS_Common_Tool.git", :tag => s.version }
  s.source_files = "YZT_iOS_Common_Tool", "YZT_iOS_Common_Tool/**/*.{h,m,c}"

  s.libraries = 'z'

  s.framework = "Foundation"
  s.framework = "UIKit"
  s.framework = "Security"
  s.framework = "CoreTelephony"
  s.framework = "QuartzCore"
  s.framework = "CoreSpotlight"

  s.dependency 'SDWebImage', '3.7.1'
  s.dependency 'OpenSSL', '1.0.210'

end

when execute ‘pod spec lint --verbose --allow-warnings’
encounter blow error:

-> YZT_iOS_Common_Tool (0.0.18)
    - ERROR | [iOS] unknown: Encountered an unknown error (The 'Pods-App' target has transitive dependencies that include static binaries: (/private/var/folders/rw/n6cb8dxx5cnck3lbt_j0bpkc0000gn/T/CocoaPods/Lint/Pods/OpenSSL/lib/libcrypto.a and /private/var/folders/rw/n6cb8dxx5cnck3lbt_j0bpkc0000gn/T/CocoaPods/Lint/Pods/OpenSSL/lib/libssl.a)

how can i solve it？

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
