### ISSUE TITLE
Automatic Manage Signing of Pods.xcodeproj is getting set as OFF when using Pod version ≥ 1.1.0

### ISSUE THREAD

**Issue by rishijoshi-ibm** [CocoaPods/CocoaPods#6906]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` using 2 different cocoapod versions 1.0.0 and 1.2.1 using .
`pod _1.0.0_ install` and `pod _1.2.1_ install`

## What did you expect to happen?

Install all pod dependencies correctly, generate pods project successfully.

## What happened instead?

When I install pods using cocoapod version 1.0.0, _Automatic Manage Signing_ property in _General_ Tab of _Pods.xcodeproj_ is ticked (*ON*).
But when I use 1.2.1 pod version to install cocoapods, _Automatic Manage Signing_ property in _General_ Tab of _Pods.xcodeproj_ is un-ticked (*OFF*).

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.12
        Host : Mac OS X 10.11.6 (15G1510)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e1cb183dee20adde2a6dfe17084b1dae27031c91
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'IceCreamShop' do
  use_frameworks!
  pod 'Alamofire', '4.4.0'
  pod 'MBProgressHUD', '~> 1.0'
end
```

## Project that demonstrates the issue

I have shared a direct download link of a sample Project from Ray Wenderlich's Website where this issue I was able to replicate.
https://koenig-media.raywenderlich.com/uploads/2017/04/IceCreamShop_Final-1.zip

## Requirement

I have a Continuous Integration environment setup which installs pod and archives the project. Archiving an Xcode Project via command line by passing Provisioning Profile Specifier requires _Automatic Manage Signing_ property in _General_ Tab of _Pods.xcodeproj_ to be *OFF* for main target and *ON* for other Pod related targets.
But for Pod Versions ≥ 1.1.0, I am unable to archive the project because the aforesaid property doesn't get set as it used to happen for pod version ≤ 1.0.1.
Podfile post-install hook allows me to make changes only to the _Build Settings_ Tab like the following method that changes _Use Swift Legacy Version_ settings of each pod to 'No'.
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```
The property _Automatic Manage Signing_ which is not referenced in Xcode Build Settings. So if there can be any way to enable that from Podfile by adding something like above, that would be quite helpful.

Following is the Screenshot when `pod _1.0.0_ install` is performed.
<img width="1017" alt="solution" src="https://user-images.githubusercontent.com/27675385/28668757-0a987bfa-72ef-11e7-856e-b697b5c48927.png">

Following is Screenshot when `pod _1.2.1_ install` is performed.
<img width="1014" alt="issue" src="https://user-images.githubusercontent.com/27675385/28668672-9881948e-72ee-11e7-8331-29d6fc834cf9.png">

Has anyone seen such issue? or Can anyone help me out here?

**Comment by anback** [comment]
+ mother f**** 1, i am trying to fix this now with a hacky script

**Comment by DanToml** [comment]
Automatically manage signing is deliberately disabled as we handle code signing in the copy phase. https://github.com/CocoaPods/CocoaPods/pull/5528

You could unset those build settings in a post install hook, but that's not super supported.

**Comment by rishijoshi-ibm** [comment]
@DanToml But how can I unset them? I have tried the following in post_install hook with no success:
```
config.build_settings['CODE_SIGNING_REQUIRED'] = 'YES'
config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'NO_SIGNING/'
config.build_settings['ProvisioningStyle'] = 'Automatic'
```
Could you be more specific as to which property I should edit to as to get `ProvisioningStyle` as Automatic for Pods? This issue is breaking my CI setup, due to which we aren't able to support pods above `1.0.1` for installing cocoapods.

**Comment by dnkoutso** [comment]
@rishijoshi-ibm remember to call `config.save_as(path)` when you are done editing the config.

**Comment by dnkoutso** [comment]
A sample:

```ruby
  installer.aggregate_targets.each do |t|
    t.xcconfigs.each do |name,config|
      path = t.xcconfig_path(name)
      # config.build_settings['ProvisioningStyle'] = 'Automatic' # Change whatever you want here.
      config.save_as(path)
    end
  end
```

**Comment by rishijoshi-ibm** [comment]
I'm using the following in post_install hook:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['ProvisioningStyle'] = 'Automatic'
        end
    end
end
```
Can you tell me how to use what you mentioned, in this version?
I'm getting error while installing Pods when using `config.build_settings['ProvisioningStyle'] = 'Automatic'` and config.build_settings['SWIFT_VERSION'] = '3.0' in your sample:
`undefined method 'build_settings' for #<Xcodeproj::Config`

**Comment by dnkoutso** [comment]
If you are changing the project you must call `project.save` on it. If you are changing the xcconfig then you must call `config.save_as(path)` where you pass the path.

Tinker with it I am sure you can get it to work.

**Comment by rishijoshi-ibm** [comment]
@dnkoutso I'm getting you are telling, but I wasn't calling `config.save_as(path)` earlier and whatever I was setting, viz. `config.build_settings['SWIFT_VERSION'] = '3.0'` it was reflecting in Pods.xcodeproj without calling . So, why do I need to do it this time? I don't get it.
I mean, I don't see it solving my problem. I played with it and got it to work somehow, but still it doesn't do what I need it to.

I just need the property with which I can fiddle with so that it changes the `ProvisioningStyle`, but that field doesn't even appear in `pbxproj` of Pods.xcodeproj unless I manually place a tick on **Automatic Manage Signing** after opening it in Xcode, so I'm not able affect `ProvisioningStyle` property via post_install hook because it isn't there!
<img width="770" alt="pods after pod install" src="https://user-images.githubusercontent.com/27675385/30899094-1fd29b50-a37c-11e7-8dad-b39d63b01f79.png">

And as @DanToml mentioned that **Automatic Manage Signing** was _deliberately disabled_, then there should be a toggle option for people who want it _enabled_. Isn't it?

**Comment by dkk** [comment]
I'm gessing it doesn't work with the hook because the Pods project gets generated after the post install hook is executed:

From `pod install --verbose`:

```
 - Running post install hooks
    - Podfile
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`
```

**Comment by findyam** [comment]
try  config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ''
        config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'

**Comment by rishijoshi-ibm** [comment]
Hi All,

Sorry for a bit late reply, _CODE_SIGN_STYLE_ was the key.
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_STYLE'] = "Automatic"
        end
    end
end
```
