### ISSUE TITLE
-no--repo--update not working

### ISSUE THREAD

**Issue by ledikari** [CocoaPods/CocoaPods#6907]
Cocoapods: Latest Release
using Xcode 8.3.3

After Mac restarted, tried 'pod install -no--repo-update --verbose' command
I was expecting that pod will install all pod dependencies correctly
unfortunatley it cloned master again ignoring the --no-reporo-update option

after the clone succeeds, tried pod install again and it works, after I restart the Mac the issue will happen again.

**Comment by dnkoutso** [comment]
Thats not what the flag does. The master repo will be cloned if its not cloned. I do not think this is an issue.
