### ISSUE TITLE
Tests not detected in Sparkle's pod

### ISSUE THREAD

**Issue by pornel** [CocoaPods/CocoaPods#6911]
According to CocoaPods Sparkle doesn't [get any "Has tests" points](https://cocoapods.org/pods/Sparkle/quality). However, [Sparkle does have tests](https://github.com/sparkle-project/Sparkle/tree/master/Tests).

I've found that the score is based on 'total_test_expectations' count, but I could not find where that stat comes from. I could not find information what counts as tests and how to specify that ("test" is not present in https://guides.cocoapods.org/syntax/podspec.html).

**Comment by orta** [comment]
The detection code is inside CocoaDocs, you're welcome to take a look inside the 'testing_estimator' I think. In the mean time, I'm closing this as it's not a CocoaPods the CLI tool issues, happy to have it re-opened on cocoadocs.org.
