### ISSUE TITLE
pod install @repo_update   no env sources  Analyzing dependencies

### ISSUE THREAD

**Issue by YanweiLi** [CocoaPods/CocoaPods#6916]
I get this issue：

$pod install
@repo_update  
no env sources 
Analyzing dependencies
[!] Unable to find a specification for `AFNetworking (~> 3.1)`

------------------------------------------------
podfile :
platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target "FlyImage" do
  pod 'AFNetworking', '~> 3.1'
	pod 'libwebp', '0.6'
end

------------------------------------------------

I  had update my spec repo useing: pod repo update ,  and never work.

I want to know:
@repo_update  
no env sources 

what's happened to cocoapods by this string '@repo_update  no env sources '?

**Comment by gurisxie** [comment]
I meet this q ,too

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
