### ISSUE TITLE
Lint spec && build fails

### ISSUE THREAD

**Issue by guilllaumeCritizr** [CocoaPods/CocoaPods#6919]
## Framework

- Swift 3

## What did you do?

pod spec lint Critizr-iOS-Swift.podspec --verbose

## What did you expect to happen?

Pass succesful spec lint

## What happened instead?

The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/guillaumeboufflers/Library/Developer/Xcode/DerivedData/App-bgejgdepwleolufqdyvrxszwcuri/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Script-979372651046B59A4D8BD3AE.sh
[!] The spec did not pass validation, due to 1 error.

### Stack

```
   CocoaPods : 1.3.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b771e46954aca1bf2a746712759e2f2098602a76
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Logs

The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/guillaumeboufflers/Library/Developer/Xcode/DerivedData/App-ehjnbhaacaowhjatdeeteqwyycmh/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Script-D69E15C36464F7CE166F7C0C.sh
(1 failure)
   Testing with xcodebuild.
 -> Critizr-iOS-Swift (2.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  ld: warning: ignoring file Critizr-iOS-Swift/critizr_sdk_swift.framework/critizr_sdk_swift, missing required architecture i386 in file Critizr-iOS-Swift/critizr_sdk_swift.framework/critizr_sdk_swift (2 slices)
    - NOTE  | [iOS] xcodebuild:  ld: warning: ignoring file Critizr-iOS-Swift/critizr_sdk_swift.framework/critizr_sdk_swift, missing required architecture x86_64 in file Critizr-iOS-Swift/critizr_sdk_swift.framework/critizr_sdk_swift (2 slices)
    - NOTE  | [iOS] xcodebuild:  fatal error: lipo: -remove's specified would result in an empty fat file

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.rc.1/lib/cocoapods/command/spec/lint.rb:87:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.rc.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.0.rc.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
@guilllaumeCritizr please provide a podspec to work with. It's very hard to dissect the issue as such.

To me this seems like an `xcodebuild` error and most likely not a cocoapods issue.

Seems like:

```
- NOTE | [iOS] xcodebuild: ld: warning: ignoring file Critizr-iOS-Swift/critizr_sdk_swift.framework/critizr_sdk_swift, missing required architecture i386 in file Critizr-iOS-Swift/critizr_sdk_swift.framework/critizr_sdk_swift (2 slices)
```

Basically tells you that that the `.framework` produced is not a fat framework.

**Comment by guilllaumeCritizr** [comment]
Hey dnkoutso, Thanks for taking the time.

I have tried to build it for both simulator and device thank to a Run script

## Podspec

Pod::Spec.new do |s|

s.name         = "Critizr-iOS-Swift"
s.version      = "2.0.0"
s.summary      = "Donne accès à l'ensemble des fonctionnalités Critizr pour vos applications iOS."
s.description  = "Le SDK iOS vous permet :
D’ouvrir une interface d’envoi de feedbacks pour un point de vente donné
D’ouvrir une interface Store Locator
D’obtenir la note de relation client d’un point de vente"

s.license      = { :type => 'BSD', :text => "LICENSE.txt" }
s.homepage     = "http://developers.critizr.com/docs/ios_sdk.html"
s.screenshots  = "http://developers.critizr.com/images/illustrations/sdk_ios.svg"
s.author             = { "Guillaume Boufflers" => "guillaume.boufflers@critizr.com" }

s.platform     = :ios
s.source       = { :git => "https://github.com/critizr/critizr-ios-swift-pod.git", :tag => "2.0.0" }

s.ios.deployment_target = '8.0'

s.vendored_frameworks = "critizr_sdk_swift.framework"

end

##Runscript

#!/bin/sh
UNIVERSAL_OUTPUTFOLDER=${BUILD_DIR}/${CONFIGURATION}-universal
# make sure the output directory exists
mkdir -p "${UNIVERSAL_OUTPUTFOLDER}"
# Step 1. Build Device and Simulator versions
xcodebuild -target "critizr-sdk-swift" ONLY_ACTIVE_ARCH=NO -configuration ${CONFIGURATION} -sdk iphoneos  BUILD_DIR="${BUILD_DIR}" BUILD_ROOT="${BUILD_ROOT}" clean build
xcodebuild -target "critizr-sdk-swift" -configuration ${CONFIGURATION} -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO BUILD_DIR="${BUILD_DIR}" BUILD_ROOT="${BUILD_ROOT}" clean build
# Step 2. Copy the framework structure (from iphoneos build) to the universal folder
cp -R "${BUILD_DIR}/${CONFIGURATION}-iphoneos/critizr_sdk_swift.framework" "${UNIVERSAL_OUTPUTFOLDER}/"
# Step 3. Copy Swift modules from iphonesimulator build (if it exists) to the copied framework directory
SIMULATOR_SWIFT_MODULES_DIR="${BUILD_DIR}/${CONFIGURATION}-iphonesimulator/critizr_sdk_swift.framework/Modules/critizr_sdk_swift.swiftmodule/."
if [ -d "${SIMULATOR_SWIFT_MODULES_DIR}" ]; then
cp -R "${SIMULATOR_SWIFT_MODULES_DIR}" "${UNIVERSAL_OUTPUTFOLDER}/critizr_sdk_swift.framework/Modules/critizr_sdk_swift.swiftmodule"
fi
# Step 4. Create universal binary file using lipo and place the combined executable in the copied framework directory
lipo -create -output "${UNIVERSAL_OUTPUTFOLDER}/critizr_sdk_swift.framework/critizr_sdk_swift" "${BUILD_DIR}/${CONFIGURATION}-iphonesimulator/critizr_sdk_swift.framework/critizr_sdk_swift" "${BUILD_DIR}/${CONFIGURATION}-iphoneos/critizr_sdk_swift.framework/critizr_sdk_swift"
# Step 5. Convenience step to copy the framework to the project's directory
cp -R "${UNIVERSAL_OUTPUTFOLDER}/critizr_sdk_swift.framework" "${PROJECT_DIR}"
# Step 6. Convenience step to open the project's directory in Finder
open "${UNIVERSAL_OUTPUTFOLDER}"

I found that one on the internet looking for an answer on building for multiple architectures but i'm still facing the same issue..

**Comment by guilllaumeCritizr** [comment]
I also made a very simple test:
 - Created a new project
 - pod init
 
## Podfile

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'critizt-ios-sdk-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod ‘Critizr-iOS-Swift’, :path => '/Users/guillaumeboufflers/Project/Mobile/critizr-ios-pod-swift'

end

And it actually runs smoothly on both device and emulator..

Any hint would be very much appreciated :)

**Comment by haemi** [comment]
did you find a solution to this?

**Comment by dnkoutso** [comment]
@guilllaumeCritizr can you please provide a sample repo that demonstrates the issue with a few easy commands/

**Comment by guilllaumeCritizr** [comment]
Hey guys !

Yes i did find a solution to this and it was pretty stupid ..
I updated my version of cocoapods
