### ISSUE TITLE
Unable to push a binary pod to Spec Repo

### ISSUE THREAD

**Issue by heleny** [CocoaPods/CocoaPods#6920]
Hello, 

I created a static lib MyProjectStaticLib.a, which has all architectures in the fat file
```
>>> lipo -info MyProjectStaticLib.a
>>> Architectures in the fat file: MyProjectStaticLib.a are: armv7 armv7s i386 x86_64 arm64
```
However, when i pushed it to the Spec Repo by running the following command
```
pod repo push REPO_NAME MyProjectStaticLib.podspec --verbose --allow-warnings --use-libraries
```
it complained that symbol(s) is not found for architecture x86_64.
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/xxxxx/Library/Developer/Xcode/DerivedData/App-eqvcifulvvizoravpibiwvnxqdeu/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
(1 failure)
```

Does anyone know why?  Any hint is appreciated.  
If i removed the x86_64 from the fat file, i.e. MyProjectStaticLib.a, it will get pushed to the Spec Repo.  But i need it though.  

Here is my script for generating the static lib:
```
# define output folder environment variable
UNIVERSAL_OUTPUTFOLDER=${BUILD_DIR}/${CONFIGURATION}-universal

# Step 1. Build Device and Simulator versions
xcodebuild -target ImageFilters ONLY_ACTIVE_ARCH=NO -configuration ${CONFIGURATION} -sdk iphoneos  BUILD_DIR="${BUILD_DIR}" BUILD_ROOT="${BUILD_ROOT}"
xcodebuild -target ImageFilters -configuration ${CONFIGURATION} -sdk iphonesimulator -arch i386 BUILD_DIR="${BUILD_DIR}" BUILD_ROOT="${BUILD_ROOT}"

# make sure the output directory exists
mkdir -p "${UNIVERSAL_OUTPUTFOLDER}"

# Step 2. Create universal binary file using lipo
lipo -create -output "${UNIVERSAL_OUTPUTFOLDER}/lib${PROJECT_NAME}.a" "${BUILD_DIR}/${CONFIGURATION}-iphoneos/lib${PROJECT_NAME}.a" "${BUILD_DIR}/${CONFIGURATION}-iphonesimulator/lib${PROJECT_NAME}.a"

# Last touch. copy the header files. Just for convenience
cp -R "${BUILD_DIR}/${CONFIGURATION}-iphoneos/include" "${UNIVERSAL_OUTPUTFOLDER}/"
```

**Comment by dnkoutso** [comment]
It's hard to debug without a podspec. Can you provide it? Or a sample repo/project?

Try using `pod spec lint --use-libraries --no-clean` and open the generated workspace and try to dissect the error from within Xcode.

**Comment by heleny** [comment]
I just ran ```pod spec lint --use-libraries --no-clean --verbose ``` and it resulted in the same error.

**Comment by heleny** [comment]
@dnkoutso  Here is my podspec:
```
Pod::Spec.new do |s|
  s.name         = 'MyProjectStaticLib'
  s.version      = '0.1.0'
  s.summary      = 'Static Lib for iOS'
  s.homepage     = 'https://www.example.com'
  s.license      = { :type => 'MIT', :file => 'LICENSE' }
  s.author       = { 'Helen Yang' => 'heleny@example.com' }
  s.platform     = :ios
  s.source       = { :http => 'https://www.example.com/framework/release/0.1.0/MyProjectStaticLib.zip' }
  s.source_files = 'include/MyProjectStaticLib/*.h'
  s.ios.deployment_target = '8.0'
  s.vendored_libraries = 'libMyProjectStaticLib.a'
  s.public_header_files = 'include/MyProjectStaticLib/*.h'
end
```

**Comment by dnkoutso** [comment]
This podspec does not help. The `http` link is not pointing to a url I can download the file to lint it.

When I said to use the `lint` command I meant to use it to open the `xcworkspace` generated and inspect it there. It wasn't going to solve the problem.

**Comment by heleny** [comment]
My question is my *.a has support for x86_64, but when I pushed it to cocoapods, it complained the symbols for x86_64 cannot be found.  Are they referring to the same thing?  I did set my build setting "Build Active Architecture Only" to NO.  That's what puzzled me...  The link works.. sorry, i munged it to be invalid.

**Comment by dnkoutso** [comment]
I am sorry its hard to debug without the `.a` or sources. My gut tells me that there is a missing symbol in your `.a`.

You can try ` pod spec lint --use-libraries --verbose --skip-import-validation` although this is generally not recommended.

**Comment by heleny** [comment]
@dnkoutso I have put up a new pod on the public CocoaPods spec repo: https://cocoapods.org/pods/MiaImageFilter

Here is my podspec:
```
Pod::Spec.new do |s| 
  s.name         = "MiaImageFilter"
  s.version      = "0.3"
  s.summary      = "Mia's Image Filter"
  s.homepage     = "https://cocoapods.org"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author       = { "Helen Yang" => "git.heleny@gmail.com" }
  s.platform     = :ios
  s.ios.deployment_target = "8.0"
  s.source       = { :http => "https://www.dropbox.com/s/u1m4rbdpe0g9lpk/MiaImageFilter.zip?dl=1" }
  s.vendored_libraries = "libMiaImageFilter.a"
  s.source_files  = "include/MiaImageFilter/*.h"
  s.public_header_files = "include/MiaImageFilter/*.h"
end
```

I can push it to cocoapods, but when I tried to use the pod, it complained
```
>>> pod install
Analyzing dependencies
[!] Unable to find a specification for `MiaImageFilter (~> 0.3)`
```

Any ideas? 

Thanks!

**Comment by heleny** [comment]
@dnkoutso the test app's Podfile is the following: 
```
#source "https://github.com/CocoaPods/Specs.git"
platform :ios

target 'MyAppTarget' do
  use_frameworks!
  pod 'MiaImageFilter', '~> 0.3'
end
```

Same error with or without ``` use_frameworks! ```.

**Comment by dnkoutso** [comment]
`pod install --repo-update` perhaps?

I am going to close this issue as I don't think there is a problem with the cocoapods library itself.

Those questions are also best asked in StackOverflow under the 'cocoapods' tag.

**Comment by heleny** [comment]
I did ``` pod install --repo-update```, but getting 
```
[!] Unable to satisfy the following requirements:

- `MiaImageFilter (~> 0.3)` required by `Podfile`

Specs satisfying the `MiaImageFilter (~> 0.3)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by dnkoutso** [comment]
@heleny the message clear says `dependency were found, but they required a higher minimum deployment target.`

You must bump your deployment target in your app.

**Comment by heleny** [comment]
I bump it up to 9.0, still complained...

**Comment by dnkoutso** [comment]
Look at the `MiaImageFilter` and see what it requires.

**Comment by heleny** [comment]
@dnkoutso thanks.  It works.
