### ISSUE TITLE
windows compatibility error 

### ISSUE THREAD

**Issue by MaskedHawk** [CocoaPods/CocoaPods#6923]
Hello,
When i tried to execute : `pod setup` on windows command failed with error
"[!] Unable to locate the executable `git`"
it's due to this file executable.rb
:97
`bin = File.expand_path(program, path)`
:100
`if File.file?(bin) && File.executable?(bin)`
because on windows you search for .exe
so you just have to add this : 
:97
`bin = File.expand_path(program, path)`  
`exe = bin + ".exe"`
:100 
`if (File.file?(bin) && File.executable?(bin)) || (File.file?(exe) && File.executable?(exe))`
bye ....

**Comment by dnkoutso** [comment]
@MaskedHawk seems like you got most of the issue investigated, care to open a PR with a test?
