### ISSUE TITLE
'pod install' force update version of dependency, described in .podspec file ignoring .lock file

### ISSUE THREAD

**Issue by rostislawko** [CocoaPods/CocoaPods#6931]
In app's Podfile I have dependency on lib (let's call it 'A'), which .podspec file is placed in local directory. In that .podspec file there is dependency on another lib (let's call it 'B') from 1.8.0 till 2.0.0 version:
A.podspec
```
s.subspec 'Static' do |static|
    static.platform = :ios, '7.0'
    static.preserve_paths       = ***
    static.source_files         = ***
    static.public_header_files  = ***
    static.vendored_frameworks  = ***
    static.dependency 'B', '>= 1.8.0', '< 2.0.0'
  end
```
In app's Podfile.lock version of lib 'B' is pinned to 1.8.3. In repository the latest version of lib is 1.9.0. 

And when I run 'pod install' (for example on teamcity server), version in .lock file is ignored, and version of lib 'B' is forced to latest (1.9.0).

It looks like a bug. 

Version of cocoa pods is 1.2.1

**Comment by orta** [comment]
I agree, this doesn't sound right, can you make a re-production repo that someone can take a look at?

**Comment by icecrystal23** [comment]
I'm also seeing `pod install` ignore the lock file and update dependencies... I'll see if I can reproduce in a shareable sample project.

**Comment by NZhlebinkov** [comment]
`pod install` still ignores the .lock file for my Flutter project. @orta Have you received a reproducible repo?
