### ISSUE TITLE
Cocoapods down now 6:15 pm - GMT 0

### ISSUE THREAD

**Issue by KatkayApps** [CocoaPods/CocoaPods#6932]
Cocoapods website is down, it shows no results for any search.

`pod install` is not working too for any package.

**Comment by DanToml** [comment]
`pod install` is not dependent on the search service being available.

Please could you fill in the regular CocoaPods issue template with steps to reproduce your `pod install` issue.

**Comment by KatkayApps** [comment]
ok but the website shows no result.

**Comment by DanToml** [comment]
@KatkayApps The search issue is unrelated to installing pods and is best tracked on the search repository.

**Comment by KatkayApps** [comment]
I am closing the issue now, the system is working now for `pod install` but the search on the site is still not returning any package. Thanks for the help.
