### ISSUE TITLE
Undefined symbols for architecture i386, x86_64

### ISSUE THREAD

**Issue by heleny** [CocoaPods/CocoaPods#6933]
# Report

## What did you do?
I tried to push a static lib podspec to cocoapods
e.g. Run ```pod repo push SPEC_REPO MyProjectStaticLib.podspec --verbose --allow-warnings --use-librarie```

## What did you expect to happen?
MyStaticLib.podspec is successfully pushed to the cocoapods' spec repo

## What happened instead?
It complained an error on 'undefined symbols for architecture i386, x86_64' for sqlite3: 

```
Undefined symbols for architecture i386:
  "_sqlite3_column_bytes", referenced from:
      ...
  "_sqlite3_exec", referenced from:
      ...
  "_sqlite3_free", referenced from:
      ...
  "_sqlite3_close_v2", referenced from:
      ...
  "_sqlite3_finalize", referenced from:
      ...
  "_sqlite3_column_int64", referenced from:
      ...
  "_sqlite3_bind_int64", referenced from:
      ...
  "_sqlite3_db_readonly", referenced from:
      ...

Undefined symbols for architecture x86_64:
       "_sqlite3_column_bytes", referenced from:
      ...
       "_sqlite3_exec", referenced from:
      ...
      "_sqlite3_free", referenced from:
      ...
      "_sqlite3_close_v2", referenced from:
      ...
      "_sqlite3_finalize", referenced from:
      ...
      "_sqlite3_column_int64", referenced from:
      ...
      "_sqlite3_bind_int64", referenced from:
      ...
      "_sqlite3_db_readonly", referenced from:

** BUILD FAILED **


The following build commands failed:
	Ld /Users/xxxx/Library/Developer/Xcode/DerivedData/App-fcybnxyykthoxqeawvstzspoinmj/Build/Intermediates/App.build/Release-iphonesimulator/App.build/Objects-normal/x86_64/App normal x86_64
(1 failure)
```

I have added libsqlite3.dylib to ```Linked Binary with Libraries``` and added ```-lsqlite3``` to ```Other Linker Flags```, it still outputs the same error.  I have also tried it on Xcode 7.3, same output.  My static lib uses sqlite3.  I can build/run it without any error.  I got this error when I tried to push it to cocoapods.  

## CocoaPods Environment
```
pod -version: 1.3.0.rc.1
Xcode: 8.3.3
```

**Comment by heleny** [comment]
I added libsqlite3.dylib and libz.dylib to ``` Link binary With Libraries``` from this [stackoverflow page](https://stackoverflow.com/questions/27878860/apple-mach-o-linker-error-sqlite3).  It doesn't seem to work though.

**Comment by dnkoutso** [comment]
Try adding:

```ruby
s.library = 'sqlite3'
```
in your podspec.

I am closing this as this is not a cocoapods issue. Please use StackOverflow to ask these types of questions.

**Comment by heleny** [comment]
@dnkoutso  do i still need libsqlite3.dylib and libz.dylib build settings?

**Comment by dnkoutso** [comment]
sounds like you need `sqlite3` I am not sure for `z`.

Either way add:

```ruby
s.library = 'sqlite3', 'z'
```

Should fix it.

**Comment by heleny** [comment]
@dnkoutso 👍
