### ISSUE TITLE
Configuring Pods-App-frameworks.sh installation

### ISSUE THREAD

**Issue by Unihilator** [CocoaPods/CocoaPods#6934]
For some reason I don't want to add pod to Pods-App-frameworks.sh script. Is there a way do to that without changing Pods-App-frameworks.sh manually?

Example: 

Want not to include SnapKit
``` Ruby
install_framework "$BUILT_PRODUCTS_DIR/SnapKit/SnapKit.framework"
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

You should also look into a `post_install` script.
