### ISSUE TITLE
Can't upgrade cocoapods to 1.3

### ISSUE THREAD

**Issue by gyzerocc** [CocoaPods/CocoaPods#6935]
# Report

## What did you do?

run "gem install cocoapods"

## What did you expect to happen?

cocoapods's version update to 1.3.1, now it's 1.3.0.rc.1

## What happened instead?

result:
```
$ gem install cocoapods
Successfully installed cocoapods-1.2.1
Parsing documentation for cocoapods-1.2.1
Done installing documentation for cocoapods after 2 seconds
1 gem installed
```

and I use "gem install cocoapods --pre" before this command.
so the version is:
```
$ pod --version
1.3.0.rc.1
```

## CocoaPods Environment

$ pod env

### Stack

```
   CocoaPods : 1.3.0.rc.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.10
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/gongyang/.rvm/rubies/ruby-2.3.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 38578b424baf50fd1787d33bd43c0440d81dae03
```

### Installation Source

```
Executable Path: /Users/gongyang/.rvm/gems/ruby-2.3.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
CLosing as i dont think this is an issue with the cocoapods library itself.

Try
```
gem install cocoapods -v 1.3.0
```

**Comment by gyzerocc** [comment]
```
$ sudo gem install cocoapods -v 1.3.0
ERROR:  Could not find a valid gem 'cocoapods' (= 1.3.0) in any repository
ERROR:  Possible alternatives: cocoapods
```

**Comment by dnkoutso** [comment]
@gyzerocc the release is available and I can use. https://rubygems.org/gems/cocoapods

I think something is wrong on your local machine.

**Comment by gyzerocc** [comment]
I think so..

thank you
