### ISSUE TITLE
Xcode 9 new build system + CP 1.3.x - issue with vendored framework resource bundle

### ISSUE THREAD

**Issue by igor-makarov** [CocoaPods/CocoaPods#6936]
* [✓] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I began using CP 1.3.0 with new Xcode 9 build system. It didn't copy `TwitterKitResources.bundle` to the app bundle.

## What did you expect to happen?

`TwitterKitResources.bundle` to be copied to the app bundle as expected.

## What happened instead?

`TwitterKitResources.bundle` was not copied to the app bundle.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.5.2
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9M189t)
         Git : git version 2.13.2 (Apple Git-90)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 673308018a262e5ddc2bd3ce24cc34938fb3a551
               twilio - https://github.com/twilio/cocoapod-specs @ 3861dbb30e05c7b721702df717616e79f01de495
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-amimono     : 0.0.9
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
slather               : 2.4.1
```

### Podfile

```ruby
target 'DemoVendoredBundleCopying' do
  use_frameworks!
  pod 'TwitterKit'
end
```

## Project that demonstrates the issue

https://github.com/igor-makarov/DemoVendoredBundleCopying

**Comment by igor-makarov** [comment]
I noticed that it also happens every once in a while on the old build system - still under Xcode 9, though.

**Comment by Dimillian** [comment]
I have the same issue, 100% of the time. With TwitterKit and other frameworks providing resources. Any workaround for now?

**Comment by MatejBalantic** [comment]
Seeing the same issue, every time I build.

**Comment by dnkoutso** [comment]
I'll speak for me, but I haven't done any work on new build system still it's still in beta.

I do not expect a ton of progress on this, but always feel free to try and contribute back. I'll keep this issue open.

**Comment by igor-makarov** [comment]
I'd like to point out that it sometimes happens in old build system as well. 

I believe this is a side effect of using the script file paths optimization introduced in 1.3.0.

**Comment by dnkoutso** [comment]
> I believe this is a side effect of using the script file paths optimization introduced in 1.3.0.

@igor-makarov how do you come to this conclusion? Does the first build work but then a subsequent build fail?

**Comment by dnkoutso** [comment]
Also you can try CP 1.2.x with Xcode 9 maybe and see if it exhibits the same behavior?

**Comment by igor-makarov** [comment]
I know this because it started doing this after I upgraded to 1.3.0. It didn't happen in 1.2.x with new build system.

Also, as I said, under old build system and 1.3.0, it still happens occasionally. Very infrequently.

I can also say that I've had done some experiments with script file paths myself and I noticed that Xcode doesn't behave well when the paths specified aren't a single file each - frameworks are directories.

**Comment by dnkoutso** [comment]
Thanks, will have to take a look here but priority is to ship 1.4.0.beta.1

For the paths.........these are vendored frameworks so nothing about them should change.

**Comment by bjhomer** [comment]
I've done some investigation; it appears that the problem here is related to the "output files" setting on the "Copy Pod Resources" build script phase. 

When building, we see the following warning in the Xcode build log:

> warning: unexpected duplicate creator 'PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/[username]/Library/Developer/Xcode/DerivedData/MyApp-agpxwtxsbxtyowaakpssvpppoqfy/Build/Intermediates.noindex/MyApp.build/Debug-iphoneos/MyApp.build/Script-C10301E611CE467A6B3D5D66.sh' for node '${BUILT_PRODUCTS_DIR}/MyApp.app' with prior creator 'MkDir ${BUILT_PRODUCTS_DIR}/MyApp.app' (in target 'MyApp')

So, Xcode seems to believe that the "Copy Pod Resources" script is creating "MyApp.app". Why does it think that? Because the run script phase has one output file listed: `${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}`. For iOS targets, that resolves to `${BUILT_PRODUCTS_DIR}/MyApp.app`.

This apparently confuses the new build system, and it elects to skip the run script phase altogether.

I see two possible ways to address this:

1. List all the output resources individually in the phase's output files, just like we list all the input files in the phase's input files.
2. Produce a dummy output file inside `${DERIVED_FILE_DIR}` that indicates that the phase has run, as show [here](http://indiestack.com/2014/12/speeding-up-custom-script-phases/).

Of these two options, I think the first is the better option.

**Comment by danilobuerger** [comment]
Still happening with CP 1.4.0 beta 2.

**Comment by danilobuerger** [comment]
Listing all output resources individually as explained by @bjhomer works for me. In my case, I need to copy the hockey sdk resource bundle. Instead of `${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}` I now have `${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/HockeySDKResources.bundle`.

**Comment by igor-makarov** [comment]
@bjhomer did you test option 1? It seems like a good solution.

**Comment by bjhomer** [comment]
I did not; I believe it should work; it was just inconvenient to manually do so with my particular project.

**Comment by igor-makarov** [comment]
W00t!

**Comment by kyleturner** [comment]
We're still seeing this issue against latest CP master branch with Xcode 9+, specifically running our test target from the primary target through the Xcode Test action.

We're using the new `test_spec` configuration in our `.podspec`, but now no longer are seeing our `TestTarget.bundle` being generated. This includes test `.json`, and `.PDF` files we run unit tests against.

I'm able to run `pod install` with no issues, the targets are compiling, but tests fail because it cannot find the `TestTarget.bundle` (nor included resources within).

Our `.podspec` for test_spec looks something like:

```ruby
s.test_spec 'Tests' do |test_spec|
  test_spec.resource_bundles = {
    'TestTarget' => ['Tests/Resource/*.{pdf,png,jpeg,json}']
  }
  test_spec.ios.frameworks = 'XCTest'
  test_spec.dependency 'ObjectMapper', '~> 2.2'
  test_spec.source_files = 'Tests/*.swift'
end
```

And our local Podfile uses the podspec directly via:

```ruby
target 'Main' do
  podspec
  target 'TestTarget' do
    inherit! :search_paths
    pod 'ObjectMapper', '~> 2.2'
end
```

Could someone please explain how to continue creating the resource bundle for nested Test targets?

**Comment by dnkoutso** [comment]
@kyleturner can you provide a sample?

**Comment by kyleturner** [comment]
Hey @dnkoutso thank you so much for the quick response! Trying to update our team from Cocoapods 0.38.2 -> 1.4 beta so definitely appreciate the help.

Here's the real source:

## Podspec

```ruby
Pod::Spec.new do |s|
  s.name                      = "Core"
  s.version                   = "1.0.1"
  s.summary                   = "The Core Framework for TrackVia Swift applications."
  s.homepage                  = "https://trackvia.com"
  s.license                   = { :type => "MIT", :file => "LICENSE.md" }
  s.author                    = { "TrackVia, Inc." => "ios@trackvia.com" }
  s.source                    = { :git => "https://github.com/XVia/Core.git", :tag => s.version }
  s.social_media_url          = 'https://twitter.com/trackvia'
  s.ios.frameworks            = 'UIKit'
  s.ios.deployment_target     = '9.0'
  s.watchos.deployment_target = '2.0'
  s.requires_arc              = true
  s.default_subspec           = 'Request'

  #########################
  # Subspecs
  #########################
  s.subspec 'Common' do |cs|
    cs.ios.source_files = 'Core/Core/Common/*.swift'
    cs.dependency 'CryptoSwift', '~> 0.7.0'
    cs.dependency 'KeychainSwift', '~> 9.0'
    cs.dependency 'ObjectMapper', '~> 2.2'
    cs.dependency 'SwiftyJSON', '~> 3.0'
  end

  s.subspec 'Model' do |ms|
    ms.ios.source_files = 'Core/Core/Model/*.swift'
    ms.dependency 'Core/Common'
  end

  s.subspec 'Request' do |rs|
    rs.ios.source_files = 'Core/Core/Request/*.swift'
    rs.dependency 'Core/Model'
  end

  s.subspec 'Test' do |ts|
    ts.ios.source_files = 'Core/Core/Test/*.swift'
    ts.dependency 'Core/Request'
  end

  #########################
  # Test Spec
  #########################
  s.test_spec 'Tests' do |test_spec|
    test_spec.resource_bundles = {
      'CoreTest' => ['Core/CoreTests/Resource/*.{pdf,png,jpeg,jpg,json}']
    }
    test_spec.ios.frameworks = 'XCTest'
    test_spec.dependency 'CryptoSwift', '~> 0.7.0'
    test_spec.dependency 'KeychainSwift', '~> 9.0'
    test_spec.dependency 'ObjectMapper', '~> 2.2'
    test_spec.dependency 'SwiftyJSON', '~> 3.0'
    test_spec.source_files = 'Core/CoreTests/Common/*.swift', 'Core/CoreTests/Test/*.swift'
  end
end
```

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/XVia/TrackVia-iOS-Pods.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

workspace 'Core.xcworkspace'
project 'Core/Core.xcodeproj'

target 'Core' do
  podspec
  target 'CoreTests' do
    inherit! :search_paths
    pod 'CryptoSwift', '~> 0.7.0'
    pod 'KeychainSwift', '~> 9.0'
    pod 'ObjectMapper', '~> 2.2'
    pod 'SwiftyJSON', '~> 3.0'
  end
end
```

## Derived Data from Main Compiled

![deriveddata - main](https://user-images.githubusercontent.com/283362/33340806-5a83785c-d43a-11e7-98c9-6db584b9dd42.png)

## Test.xctest contents

![test xctest contents](https://user-images.githubusercontent.com/283362/33340805-5a7219cc-d43a-11e7-96b1-a73ecc1fc951.png)

Previously, with some slightly different podspec and Podfile config, I was able to see `CoreTest.bundle` and within it, the resource files I am specifying in the spec.

Anything else I can provide please let me know!

**Comment by dnkoutso** [comment]
@kyleturner a couple of things, can you file a new issue and upload the sample project in a zip?

**Comment by kyleturner** [comment]
@dnkoutso Sure thing, give me about an hour and I'll file a new issue and link to it here for others experiencing similar. Happy to cleanup my examples above too.

**Comment by nianran** [comment]
Hello, I have a problem with the [pr](https://github.com/CocoaPods/CocoaPods/commit/9046e78eec9c61c17da75c4473b32433cd823276) which u fix the issue.

ENV:
cocoapods: 1.4.0(release)
xcode version 9.2 (9C40b)
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin17]

pod install -> everythings is fine
when I build the project, build failed 
the problem says:
"Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below."

OK, I compare pod 1.3.1 to 1.4.0.
when I reset xxx.xcodeproj/project.pbxproj to the 1.3.1 version, build success.

OK, show the diff.
1.3.1:
outputPaths = (
    "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}",
);

1.4.0
outputPaths = (
    "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.xib",
    "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.js",
    "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.xcassert",
    "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.mob",
    "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.bundle",
    ........(more and more)
);

I can't reproduce the phenomenon in demo. sorry.
