### ISSUE TITLE
Xcode 9 biuld with local pod with vendored framework - framwork not found when linking *app*

### ISSUE THREAD

**Issue by aufflick** [CocoaPods/CocoaPods#6937]
# Report

## What did you do?

I have a podspec with a `vendored_framework`. I'm using the pod via `:path`.

Attempted to build the app.

## What did you expect to happen?

Expect app to build and link.

## What happened instead?

"Framework not found" error when linking the *app*.

Note that the framework of the pod that contains the `vendored_framework` links fine (I can see it's linking in the framework, and the `FRAMEWORK_SEARCH_PATHS` in the pod's `xcconfig` file correctly has the path to the folder containing the vendored framework (which since it's currently included via `:path` is `"${PODS_ROOT}/../../../Foo/Frameworks"`).

The *app's* xcconfig file makes no attempt to locate the vendored framework. It doesn't really *need* to in theory, since all the symbols are in the cocoapods generated framework.

There's no `-framework` directive in the xcconfig or elsewhere in the xcodeproj directing it to re-link the framework (doing so would cause duplicate symbol errors anyway I imagine since this particular framework is static).

I'm guessing perhaps new behaviour that the linker in Xcode 9 want's to inspect the framework at the point of final linking for optimisation etc.

## Solution

I can solve the linking problem by adding:

```    spec.user_target_xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/../../../Foo/Frameworks"' }```

Where that path matches what's in the pod's `xcconfig` file. I suspect that whatever logic is used to set `FRAMEWORK_SEARCH_PATHS` in that file needs to be also used to insert additional `FRAMEWORK_SEARCH_PATHS` into the main user target `xcconfig` file. I don't see that this would cause any issues for Xcode 8.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9M202q)
         Git : git version 2.8.3
Ruby lib dir : /Users/aufflick/.rubies/ruby-2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c1f068517975d0c873edee459c87a051f360839b
```

### Installation Source

```
Executable Path: /Users/aufflick/.gem/ruby/2.1.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

target 'FooTestApp' do
  use_frameworks!

  pod 'Foo', :path => '../..'

end
```

## Project that demonstrates the issue

I'll work on reducing this into a sample project I can post tomorrow - wanted to get the report up asap.

**Comment by thatjuan** [comment]
This may not necessarily be xcode 9 specific... I ran into the exact same thing on xcode 8.2.1 and 8.3.3. I arrived at the same solution that you proposed; add `FRAMEWORK_SEARCH_PATHS`. 

It seems to be a problem with the way vendored_frameworks are set up in cocoapods.

**Comment by thatjuan** [comment]
p.s. https://github.com/CocoaPods/CocoaPods/issues/6409
