### ISSUE TITLE
Deleted a version of my pods from CocoaPods, but still can find debris of it on the web

### ISSUE THREAD

**Issue by accuware** [CocoaPods/CocoaPods#6938]
CLI reports: 

[!] The version is already deleted.

Whom to contact on this?

**Comment by orta** [comment]
Can you provide some links?

**Comment by accuware** [comment]
@orta Sorry for the late reply. Well, yes there are links, but I deleted it because I didn't want to publish. Is there a more private way to let you know about?

**Comment by orta** [comment]
This was handled via email

**Comment by accuware** [comment]
@orta What has changed? Parts are still there...
