### ISSUE TITLE
passing --swift-version still throws error message as though it wasn't passed

### ISSUE THREAD

**Issue by ZevEisenberg** [CocoaPods/CocoaPods#6941]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint --swift-version=4.0` with no `.swift-version` file.

## What did you expect to happen?

Library lints with Swift 4.0 and doesn't complain about it, or if it does, gives a more useful error message.

## What happened instead?

``` -> BonMot (4.3.1)
    - WARN  | [iOS] swift_version: The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run: 
    `echo "2.3" > .swift-version`

```

### Stack

```
   CocoaPods : 1.3.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9M202q)
         Git : git version 2.14.0
Ruby lib dir : /Users/igeek/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8ee4d9d7c2a9e2b74a8a7856ca40ddc78f279672
```

### Installation Source

```
Executable Path: /Users/igeek/.rvm/gems/ruby-2.2.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Check out this branch and delete the `.swift-version` file: https://github.com/Raizlabs/BonMot/tree/feature/xcode-9

**Comment by ZevEisenberg** [comment]
cc @DanToml re: https://iosdevelopers.slack.com/archives/C04B6UKL5/p1502320704428006

**Comment by SpacyRicochet** [comment]
I had the same thing, while both trying to validate a pod with Swift 3.2 and Swift 4.0. 

I'm suspecting this line here doesn't work as expected. If I'm reading this correctly, it also warns you when you _are_ using `--swift-version=1.2.3` and you have no `.swift-version` file, which should be expected behaviour.

https://github.com/CocoaPods/CocoaPods/blob/c6eee2ed3f229c5fb7ec078c1c22b7330466a740/lib/cocoapods/validator.rb#L389

**Comment by DanToml** [comment]
Ah yeah - This happens because there's no good way to tell if you used the default value here right now. An ~ok fix might be to not assign the default value to the ivar, and check to see if the ivar is nil.

**Comment by SpacyRicochet** [comment]
As per Twitter, here's the verbose outputs for the combinations. So far, the following doesn't go right;

* When using the explicit `--swift-version=3.2`, without the dot-file, it still warns you. 

The rest seems to go okay (tested with Xcode 8.3.3's build tools).

[with_swift-version.txt](https://github.com/CocoaPods/CocoaPods/files/1242332/with_swift-version.txt)
[without_swift-version.txt](https://github.com/CocoaPods/CocoaPods/files/1242333/without_swift-version.txt)
[with_dot-swift-version.txt](https://github.com/CocoaPods/CocoaPods/files/1242331/with_dot-swift-version.txt)
[with_both.txt](https://github.com/CocoaPods/CocoaPods/files/1242330/with_both.txt)
