### ISSUE TITLE
Missing podspec

### ISSUE THREAD

**Issue by arrrnas** [CocoaPods/CocoaPods#6945]
The GoogleMobileAdsMediationInMobi pod [found here](https://cocoapods.org/?q=GoogleMobileAdsMediationInMobi) seems to be broken, its spec link leads to [404](https://github.com/CocoaPods/Specs/tree/master/Specs/GoogleMobileAdsMediationInMobi/6.2.1.0/GoogleMobileAdsMediationInMobi.podspec.json), the correct page is [here](https://github.com/CocoaPods/Specs/blob/master/Specs/7/8/1/GoogleMobileAdsMediationInMobi/6.2.1.0/GoogleMobileAdsMediationInMobi.podspec.json). 
Trying to install the pod predictably fails.

**Comment by orta** [comment]
The pod shows up for me in `pod search GoogleMobileAds --simple` so it does exist in the repo, so you should be able to use it.

I thought I removed the podspec link on the site, but I hadn't - it was broken as we'd have to re-implement that sharing algorithm in JS and no-one has the time for that. It was a broken link, not a broken spec. Can you please double check that you can't install it?

**Comment by arrrnas** [comment]
A bunch of different ones show up but the one I'm looking for doesn't @orta 
```
⇒  pod search GoogleMobileAdsMediationInMobi --simple
[!] Unable to find a pod with name matching `GoogleMobileAdsMediationInMobi'
```

**Comment by orta** [comment]
Is your specs repo up to date? `pod repo update`?

**Comment by arrrnas** [comment]
whoops :)
works as expected now, sorry for bothering.

**Comment by orta** [comment]
No problem 👍
