### ISSUE TITLE
Connect to github.com failed on a network proxy

### ISSUE THREAD

**Issue by dadameng** [CocoaPods/CocoaPods#6949]
## What did you do?

ℹ Please replace this with what you did.  
 Run `pod install`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace this with of what happened instead.  
 when I am on a network proxy ,It always cann't download the correct repo.or everything is ok.
So i want to  know that how to download the repo with Cocoapods. is it just that Cocoapods executes git clone http://github.com/xxx/xxx.git?

**Comment by orta** [comment]
This is an issue with your network, CocoaPods does nothing other than a normal `git clone` - you can see the commands if you run with `--verbose`
