### ISSUE TITLE
Pod install failed with !ProtoCompiler

### ISSUE THREAD

**Issue by sibinlutoken** [CocoaPods/CocoaPods#6955]
# Report

pod install fail due to parsing error in Podfile.lock (with pod !ProtoCompiler)

the exclamation mark '!' should be the problem in parsing

## What did you do?

ℹ Please replace this with what you did.  

Run `pod install`

## What did you expect to happen?

I expect pod install successfully

## What happened instead?

[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at /Users/sibinlu/token-ios/sdk-objc/Podfile.lock
PODS:
  - !ProtoCompiler (3.2.0):
    - Protobuf (~> 3.0)
  - OrderedDictionary (1.4)
  - Protobuf (3.3.0)
  - Unirest (1.1.4)

DEPENDENCIES:
  - !ProtoCompiler
  - OrderedDictionary
  - Unirest (~> 1.1.4)

SPEC CHECKSUMS:
  !ProtoCompiler: b66c7c0c1d911ad1490dcbfce30e1508739d8309
  OrderedDictionary: 138c8d2e358d3a0c9adda15c6c7db24e8e3b09e6
  Protobuf: d582fecf68201eac3d79ed61369ef45734394b9c
  Unirest: 5e4d93eaf32463bf619a4ecd3bbc8c32acf21eac

PODFILE CHECKSUM: 785ce8f1bef7995d4072e104a87b1ff588d167c1

COCOAPODS: 1.3.0

After I add !ProtoCompiler. 

Works correctly in 1.2.1. Wrong in 1.3.1 and 1.3.0

### Stack

```
   CocoaPods : 1.3.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bitbucket-tokenio-token-cocoa-pods - https://bitbucket.org/tokenio/token-cocoa-pods.git @ 255ace37e83fe94352b290cda8b37193ad8df0be
               master - https://github.com/CocoaPods/Specs.git @ d90ae805424b7033f69ee7d18ebaffe6e2284062
               token-cocoa-pods - git@github.com:tokenio/token-cocoa-pods.git @ 9decc2ebf86adcdb060f9762b49967725b468118
               tokenio - https://github.com/tokenio/token-cocoa-pods.git @ 9decc2ebf86adcdb060f9762b49967725b468118
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'


target 'TokenSdk' do
  pod "!ProtoCompiler"
  #pod '!ProtoCompiler-gRPCPlugin'
  pod "OrderedDictionary"
  pod 'Unirest', '~>1.1.4'


  target 'TokenSdkTests' do
    inherit! :search_paths
  end
end
```

You can reproduce the problem by linking !ProtoCompiler as a pod in Podfile. The first install might generate the lock file, then the second install will fail due to the Podfile.lock

**Comment by dnkoutso** [comment]
Dup of https://github.com/CocoaPods/CocoaPods/issues/6925 and fixed by https://github.com/CocoaPods/Core/issues/395.

Hasn't shipped yet but you are welcome to point your cocoapods-core gem to the SHA. You will need to maybe remove your existing podfile lock and regenerate it via `pod install`.

**Comment by sibinlutoken** [comment]
How to point the cocoapods-core to SHA? Thanks a lot if you can give me some example

**Comment by dnkoutso** [comment]
@sibinlutoken I recommend using Bundler http://bundler.io/v1.14/git.html 

Create a `Gemfile` and specify the dependencies and then run `bundle install`.

```ruby
gem 'cocoapods-core', :github => 'cocoapods-core', :ref => 'SHAHERE'
```

**Comment by sibinlutoken** [comment]
Thank a lot!

**Comment by phlippieb** [comment]
More on using a gemfile: http://guides.cocoapods.org/using/a-gemfile.html

**Comment by phlippieb** [comment]
@dnkoutso Please take note that, as @combanatorial mentioned in #7268, this is NOT fixed in 1.4.0.rc.1. 

If anyone else just needs a working solution, the latest stable release without this issue is 1.2.1. Uninstall your current version(s) with `sudo gem uninstall cocoapods`, then install with `sudo gem install cocoapods -v 1.2.1`. Confirm your version with `pod --version`.

**Comment by Jason-Chan** [comment]
In my case, `pod install` works after removing the "Podfile.lock" and the "Pods/Manifest.lock"😀

**Comment by vlad2010** [comment]
I still have exactly the issue with pod 1.9.3 on  OSX 10.15.6   
Is there way to fix it? 

zsh can't find protoc compiler (file exists) becuase special symbol is not screenedin prepare_command Local Podspecs/Name.podspec.json 

/bin/bash: line 3: ./Pods/!ProtoCompiler/protoc: No such file or director

% ls -l ./Pods/\!ProtoCompiler/protoc
-rwxr-x---  1 user  staff   ./Pods/!ProtoCompiler/protoc
% ls -l ./Pods/!ProtoCompiler/protoc
zsh: event not found: ProtoCompiler/protoc

Not sure that using special symbols in file names was good idea.
