### ISSUE TITLE
Linker Error Architecture Not Found When Including Framework in Pod

### ISSUE THREAD

**Issue by ivsall2012** [CocoaPods/CocoaPods#6956]
*  [ ✔] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Hi everybody,  I'm developing a project in pieces of private pods.
I got a problem with including Realm frameworks into my private pod:

> ld: framework not found Realm for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

I know this seems to relate to Realm, but please bear with me for a minute:)
I did filed an [issue](https://github.com/realm/realm-cocoa/issues/5230) in [realm-cocoa](https://github.com/realm/realm-cocoa) along with a [sample project(32.96 MB)](https://firebasestorage.googleapis.com/v0/b/savori-6387d.appspot.com/o/Realm_Test_ProjectBB.zip?alt=media&token=24db5807-23e8-482c-bc14-39581d9b7658).
Yet, the problem remained unsolved.
So I want to ask you guys and see if there's any clue to solve this problem.

# Report
## What did you do?
Let's assume the sample project's name is `RealmTest`.
I created it by using `pod lib create RealmTest`
And I added the two necessary frameworks, for Realm to run in Swift, into the directory `RealmTest` within the root project directory.
I added the line `s.vendored_frameworks = 'RealmTest/Realm.framework', 'RealmTest/RealmSwift.framework'` to the podspec file.
And then I did a `pod install` for the Example project.

## What did you expect to happen?
The build did succeed and I expect by doing all those to speed up the build time of the project, instead of compiling Realm from source code.

## What happened instead?
Until I `import RealmSwift` and started to use it, the following happened:
![](https://camo.githubusercontent.com/7ac37076026550e823e45e40ce1f3e362154cc17/68747470733a2f2f666972656261736573746f726167652e676f6f676c65617069732e636f6d2f76302f622f7361766f72692d36333837642e61707073706f742e636f6d2f6f2f53637265656e25323053686f74253230323031372d30382d31322532306174253230342e30362e3439253230504d2e706e673f616c743d6d6564696126746f6b656e3d34386430643464622d333438642d343536392d616137352d306536663134336537303138)
The build report says as mentioned earlier:
```
ld: framework not found Realm for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Notes
1. I specifically use `lipo -info` to check both of the Realm's frameworks, downloaded from their official site. Both of them support all of the four architectures.
2. Both of the frameworks are already included into the `Pods`:
![](https://camo.githubusercontent.com/0a25de64a8978db2e45bce7df82c55e91ee4c615/68747470733a2f2f666972656261736573746f726167652e676f6f676c65617069732e636f6d2f76302f622f7361766f72692d36333837642e61707073706f742e636f6d2f6f2f53637265656e25323053686f74253230323031372d30382d31322532306174253230342e30362e3535253230504d2e706e673f616c743d6d6564696126746f6b656e3d39663163663765352d383235302d343461392d626132352d616130376431323064653561)
3. And in the project's product directory(the compile technically succeeded, but the link failed at the end), both frameworks are indeed included in the app bundle's framework directory:
![](https://user-images.githubusercontent.com/5942142/29306641-6c74706e-8153-11e7-97b0-c5818d546bf1.png)

## Experiment 
I created a dummy framework which supports all of the architectures and added it to the project.
With Realm import commented out, the project gets built successfully. 
Once I import Realm module, the error resurfaces!
Here's the link to the sample project: [zip(32.96 MB)](https://firebasestorage.googleapis.com/v0/b/savori-6387d.appspot.com/o/Realm_Test_ProjectBB.zip?alt=media&token=24db5807-23e8-482c-bc14-39581d9b7658)
It is already included both Realm frameworks and the dummy framework.
To see the error, just simply uncomment `import RealmSwift` at the top of the class file `TestClass.swift` which is under group path `Development Pods/RealmTest/RealmTest/Classes` within the `Pods` project in `RealmTest.xcworkspace`

But one of the team member took a look at the sample project and couldn't find anything wrong on the Realm side so far, that's why I came to you guys for help! 

You can read the discussion from the [issue](https://github.com/realm/realm-cocoa/issues/5230) and download the [sample project](https://firebasestorage.googleapis.com/v0/b/savori-6387d.appspot.com/o/Realm_Test_ProjectBB.zip?alt=media&token=24db5807-23e8-482c-bc14-39581d9b7658).

Thank you for your time!!

## CocoaPods Environment
When I did `pod env | pbcopy`, I didn't get anything back.
So here's the `pod env` from my console:

AHFMSpecs is my private spec repository at Github.
### Stack

```
   CocoaPods : 1.3.0.beta.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : PrivateRepo - git@github.com:ivsall2012/PrivateRepo.git @ 53ada5ac79af3c65aa19cab1ce97fa616e864729
               master - https://github.com/CocoaPods/Specs.git @ 59263f3b1a444fbbffab03634b4e328da3c0d5fc
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```
### Podspec
```
Pod::Spec.new do |s|
  s.name             = 'RealmTest'
  s.version          = '0.1.0'
  s.summary          = 'A short description of RealmTest.'
  s.description      = <<-DESC
TODO: Add long description of the pod here.
                       DESC

  s.homepage         = 'https://github.com/ivsall2012/RealmTest'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'ivsall2012' => 'ivsall2012@gmail.com' }
  s.source           = { :git => 'https://github.com/ivsall2012/RealmTest.git', :tag => s.version.to_s }

  s.ios.deployment_target = '8.0'

  s.source_files = 'RealmTest/Classes/**/*'
s.vendored_frameworks = 'RealmTest/DummyFramework.framework','RealmTest/Realm.framework', 'RealmTest/RealmSwift.framework'

end
```

### Podfile

```ruby
use_frameworks!

target 'RealmTest_Example' do
  pod 'RealmTest', :path => '../'

  target 'RealmTest_Tests' do
    inherit! :search_paths

    
  end
end
```

## Project that demonstrates the issue
[The sample project(32.96 MB)](https://firebasestorage.googleapis.com/v0/b/savori-6387d.appspot.com/o/Realm_Test_ProjectBB.zip?alt=media&token=24db5807-23e8-482c-bc14-39581d9b7658)

**Comment by ivsall2012** [comment]
Any idea guys?
I have been stuck with this problem over a week now...
I'd be really appreciate it if you can just give me a clue or something.
Thanks!

**Comment by LLLhao** [comment]
I have the same problem,do you solve it finally?

**Comment by zhuozhuo** [comment]
Hi ivsall2012
   Have you solved the problem?
