### ISSUE TITLE
[iOS] file patterns: The `source_files` pattern did not match any file.

### ISSUE THREAD

**Issue by mlfarrell** [CocoaPods/CocoaPods#6957]
> Before you start, are you using the latest CocoaPods release?
yes

# Report

## What did you do?

Pod::Spec.new do |s|

  s.name         = "Something-Debug"
  s.version      = "0.9.0"
  s.summary      = "Something Utilities"
  
  s.author             = { "Michael L Farrell" => "fuck@off.com" }
  
  s.license = ""
  s.homepage = "http://removedforclientprivacy.com"
  s.source = { :git => 'git@bitbucket.org:private/rnd.git', :branch => "master" }

#^^^^ this doesn't freaking work.  I've tried 1000 variations.  Tag doesn't work, commit doesn't work, #branch doesn't work, nothing does. HTTPS is not an option because I use two-step auth and this is a #private repo
 
  s.platform     = :ios, '9.0'
  s.ios.deployment_target = '9.0'
  s.module_name = 'Something'
  
  s.vendored_frameworks = 'Something.framework'
end
  

ℹ Please replace this with what you did.  
 pod lib lint

## What did you expect to happen?
It to freaking work

ℹ Please replace this with what you expected to happen.  
e.g. Install all pod dependencies correctly.

Not print     - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.

## What happened instead?

ℹ Please replace this with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
               master - https://github.com/CocoaPods/Specs.git @ 951b3f1949474a2dda9083538b388ccd18ceead9
               twilio - https://github.com/twilio/cocoapod-specs @ cd8b6ee42161bf643b6006534ea5ab6c9ca15265
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

Addendum:
For the LOVE OF GOD, print out exactly why this is happening when using the --verbose switch.  This is like working in the dark.

**Comment by mlfarrell** [comment]
Oh and before someone tells me to put ssh:// in front of the URL,

this is what happens

URI::InvalidURIError - the scheme ssh does not accept registry part: git@bitbucket.org:private (or bad hostname?)

**Comment by amorde** [comment]
> s.author = { "Michael L Farrell" => "fuck@off.com" }

> ^^^^ this doesn't freaking work. I've tried 1000 variations. Tag doesn't work, commit doesn't work, branch doesn't work, nothing does. HTTPS is not an option because I use two-step auth and this is a private repo

> What did you expect to happen?
> It to freaking work

> Addendum:
For the LOVE OF GOD, print out exactly why this is happening when using the --verbose switch. This is like working in the dark. I'm going to recommend my client get off of cocoapods forever. THIS this is why I never used this damn thing because it never works right. You've had 5 years to get your act together and cocoapods are still a giant mess and waste of time. Dropping in a framework manually is still 1000x easier than using this project and thats just ridiculous.

> Oh and before someone tells me to put ssh:// in front of the URL ...

This isn't exactly the best way to encourage the CocoaPods developers to assist you. Most of the contributors do it on their free time, and also spend a significant amount of time going through issues that are not related to CocoaPods directly. Please be respectful.



With that said, the error is saying that `source_files` from your podspec isn't matching any of the files in your repo. Can you provide your .podspec file and a rough description of the directory structure of your pod?

**Comment by mlfarrell** [comment]
Yeah, I realized shortly after posting. Sorry about that.  

 The pertinent part of the podspec is given above,

**Comment by mlfarrell** [comment]
Aaaand I accidentally hit close. I'll just leave it closed at this point.

**Comment by orta** [comment]
@mlfarrell consider this your first warning, I don't want to see more issues with a tone like this from you in the future - it's definitely not conforming to our Codes of Conduct.

**Comment by mlfarrell** [comment]
@orta you won't see me back on here.  I'm off of cocoapods for all projects :)

**Comment by mlfarrell** [comment]
@orta @amorde and others:

I'd like to come in here and just apologize in general for this stupid bug report and talking smack in general to the cocoapods contributors.  I think its important to go back and recognize your own mistakes especially in public forums and in the tech space.  This project truly is amazing and you guys have taken it very far over the past years.
