### ISSUE TITLE
No email received for pod trunk register

### ISSUE THREAD

**Issue by novomind-faleaf** [CocoaPods/CocoaPods#6960]
Hi guys,

I don't receive any mail using

pod trunk register apps@novomind.com 'novomind AG' --description='fahims macbook'

Can you check that? Thanks!

* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk register apps@novomind.com 'novomind AG' --description='fahims macbook'

## What did you expect to happen?

Incoming mail with verification link.

## What happened instead?

No mail

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 360dialog - https://github.com/360dialog/d360-cocoapods-specs.git @ a2783a714142d03656cd1661b708acd43171b07d
               360dialog-1 - ssh://git@github.com/360dialog/d360-cocoapods-specs.git @ a2783a714142d03656cd1661b708acd43171b07d
               indooratlas - https://github.com/IndoorAtlas/CocoaPods-Specs @ 88d8d1ea917153b01223edf9feddf71b517fa782
               master - https://github.com/CocoaPods/Specs.git @ 91bd5f559cfdf64cf3be666b6a804f06b119cf2f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

n/a

**Comment by orta** [comment]
This is likely the same as #6474

**Comment by novomind-faleaf** [comment]
No, I don't think so. If I use my personal email address I do get the verification email. I guess that the email address apps@novomind.com might be blacklisted somewhere... can you check that?

**Comment by orta** [comment]
Yeah, looks like the first send in November last year was before the account existed - I've removed the blacklist
