### ISSUE TITLE
Specify Alternative Dependencies

### ISSUE THREAD

**Issue by herzi** [CocoaPods/CocoaPods#6962]
* [x] I've read and understood the [CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

We develop an advertising solution that can use e.g. Google Mobile Ads. However, there are two pods providing that API: [Google-Mobile-Ads-SDK](https://cocoapods.org/pods/Google-Mobile-Ads-SDK) and [Firebase/Admob](https://cocoapods.org/pods/Firebase).

We'd like to specify for out project that it depends on either of them (and we don't care which one).

## What did you expect to happen?

There should be a way to specify alternative dependencies: Install exactly one of these pods (maybe default to the first one unless the second one will be chosen by a different project dependency).

## What happened instead?

I haven't found any in the documentation on the CocoaPods website.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/herzi/.brew/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b4fb06013276b90461928152b06bba1e1afe97b7
```

### Installation Source

```
Executable Path: /Users/herzi/.brew/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

(I skipped the Podfile as I don't think that it matters in this case.)

## Project that demonstrates the issue

None.

**Comment by orta** [comment]
You can do this with subspecs `pod "MyPod/GA"` or `pod "MyPod/Abmod"`. See [how Moya does it](https://github.com/moya/moya/) for a reference.

**Comment by paulb777** [comment]
Firebase/AdMob is a subspec that depends on Google-Mobile-Ads-SDK. See https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/4.1.0/Firebase.podspec.json#L57
