### ISSUE TITLE
Source files not found for subspecs

### ISSUE THREAD

**Issue by rzolin** [CocoaPods/CocoaPods#6973]
* [√] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

It could be simple misunderstanding on my side. But searching for the answer didn't get good results in the CocoaPods Guides or on StackOverflow. So, some help would be really appreciated.

I am trying to setup a framework with a couple of subspecs: `DataManagement` and `Networking`, which are grouped into the `Core` subspec (copied from `RestKit`). As I understood the `Core` subspec could be replaced with `default_subspecs = 'DataManagement', 'Networking'` to the same effect (probably).

Need to mention that at some point I used general `source_files` pattern to include all files for the entire framework and it work. So there is something wrong with subspec config I assume.

# Report

## What did you do?

I created a framework (`pod spec create`) and was trying to `lint` it with `pod lib lint`. 

The directory structure is as following:
```
MessengerFramework
   > Assets (not used)
   > Code
       > ReplaceMe.swift
       > DataManagement
           > ReplaceMe.swift
           > Model
               > Model.xcdatamodeld
       > Networking
           > ReplaceMe.swift
       > DataManagement.h
       > Networking.h
```

## What did you expect to happen?

I was expecting to pass all the checks.

## What happened instead?

Getting the error:
```
-> MessengerFramework (0.1.0)
    - ERROR | [MessengerFramework/DataManagement,MessengerFramework/Networking] file patterns: The `source_files` pattern did not match any file.
```
Also if uncomment the `resources` and `preserve_paths` they also give the error about not found files. 

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.14.1
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9e769bf7f0a353b76666db836be764b168ec905b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Pod Spec in question

```
Pod::Spec.new do |s|
  s.name             = 'MessengerFramework'
  s.version          = '0.1.0'
  s.summary          = 'some desc'

  s.description      = <<-DESC
 some desc
                      DESC

  s.homepage         = 'http://www.example.com'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'rzolin' => 'rzolin@gmail.com' }
  s.source           = { :git => '<git-repo>', :tag => s.version.to_s }

  # Platform setup
  s.requires_arc = true
  s.ios.deployment_target = '8.0'

  s.default_subspec = 'Core'

  ### Subspecs
  s.subspec 'Core' do |cs|
    cs.dependency 'MessengerFramework/DataManagement'
    cs.dependency 'MessengerFramework/Networking'
  end

  s.subspec 'DataManagement' do |ds|
    ds.source_files = 'MessengerFramework/Code/DataManagement.h', 'MessengerFramework/Code/DataManagement/**/*'
    ds.resources = [ 'MessengerFramework/Code/DataManagement/Model/Model.xcdatamodeld', 'MessengerFramework/Code/DataManagement/Model/Model.xcdatamodeld/*.xcdatamodel' ]
    ds.preserve_paths = 'MessengerFramework/Code/DataManagement/Model/Model.xcdatamodeld'
  end

  s.subspec 'Networking' do |ns|
    ns.source_files = 'Code/Networking.h', 'Code/Networking/**/*.{h,m,swift}'
  end

  # s.resource_bundles = {
  #   'MessengerFramework' => ['MessengerFramework/Assets/*.png']
  # }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  # s.dependency 'AFNetworking', '~> 2.3'
end

```

## Project that demonstrates the issue

Sample Project is [here](https://github.com/rzolin/SampleMessengerCocoapodFramework)

**Comment by rzolin** [comment]
Sorry, but I obfuscated some of the data here to preserver privacy/sensitivity of the project. The source (git repo), the website and some other refs are there, but names are changed. And the s.source is accessible and doesn't give an error in the `lint`.

**Comment by dnkoutso** [comment]
@rzolin its hard to debug these without a sample project...can you provide one?

**Comment by rzolin** [comment]
Let me try to cook one up.

**Comment by rzolin** [comment]
I think I replicated it: `pod spec lint SampleMessengerCocoapodFramework.podspec`. I've updated the report above and included the link to the github project

**Comment by rzolin** [comment]
It gives the error:
```
-> SampleMessengerCocoapodFramework (0.1.0)
    - WARN  | description: The description is equal to the summary.
    - ERROR | [SampleMessengerCocoapodFramework/DataManagement,SampleMessengerCocoapodFramework/Networking] file patterns: The `source_files` pattern did not match any file.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error and 1 warning.
```

**Comment by orta** [comment]
As it's `pod spec` are you sure the tag it is referring to is up to date?

**Comment by rzolin** [comment]
Yeah, I noticed the discrepancy. In the git repo the tag is right (on the latest commit), but I cannot update it in GitHub repo. Any points to update it?

**Comment by orta** [comment]
Just downloaded it, your subspecs look like this:

```ruby
s.subspec 'Networking' do |ns|
        ns.source_files = 'Code/Networking.h', 'Code/Networking/**/*.{h,m,swift}'
end
```

but when I run `ls` for these I get nothing:

```sh
$ ls Code
ls: Code: No such file or directory
```

It's likely that you're not referring to files based on the root of the podspec.

**Comment by rzolin** [comment]
Good call! Thanks. I pretty much copied from RestKit, but probably the directory structure is different. 

But now there is another error:
```
-> SampleMessengerCocoapodFramework (0.1.0)
    - WARN  | description: The description is equal to the summary.
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find other source ref for /Users/rzolin/Projects/ArmorText/iOS-Pod-Test/SampleMessengerCocoapodFramework/SampleMessengerCocoapodFramework/Code/DataManagement/Model/Model.xcdatamodeld/Model.xcdatamodel/contents for target SampleMessengerCocoapodFramework.) during validation.

[!] SampleMessengerCocoapodFramework did not pass validation, due to 1 error and 1 warning.
You can use the `--no-clean` option to inspect any issue.
```

I've added the `resources` and `preserve_path` from some solutions to CoreData model. But it doesn't help. And again, I cannot get more help on the Internet. Even the error description itself is not clear to me. Reference to file? In the Project or in Pod/Framework? 
So, any help is appreciated.

**Comment by orta** [comment]
@rzolin I'd recommend consulting [the guides](https://guides.cocoapods.org/) or asking on asking on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this isn't.
