### ISSUE TITLE
how to clean repo ,when i use 'pod repo push [Spec] [My].podspec' ，It happened error

### ISSUE THREAD

**Issue by chunxigege** [CocoaPods/CocoaPods#6975]
<img width="597" alt="2017-08-23 1 23 34" src="https://user-images.githubusercontent.com/8032681/29600118-a001ac94-8806-11e7-96d5-372ab3f43d79.png">

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
