### ISSUE TITLE
The `pod update` command doesn't respect `--sources` option

### ISSUE THREAD

**Issue by nivanchikov** [CocoaPods/CocoaPods#6976]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

The `pod update` command doesn't seem to respect `--sources` option and updates all repos including master.

## What did you do?

run `bundle exec pod update LNNotificationsUI --sources=https://github.com/nivanchikov/public_specs.git`

## What did you expect to happen?
The internal pods source is updated, and only the framework specified in the command is updated.

## What happened instead?
All sources including the CocoaPods master specs repo are updated, then the command carried on to update all the pods, not just the specified.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.14.1
Ruby lib dir : /Users/<redacted>/.rvm/rubies/ruby-2.3.3/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 96f0b3857c391f01ded97d61249868d9e9a43962
               nivanchikov - https://github.com/nivanchikov/public_specs.git @ 9b79468432686f3655c67e3cc0d8a89235860b3a
```

### Installation Source

```
Executable Path: /Users/<redacted>/.rvm/gems/ruby-2.3.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/nivanchikov/public_specs.git'

target 'CocoaPodsTest' do
	pod 'LNNotificationsUI', '~> 1.0'
end
```

## Project that demonstrates the issue

https://drive.google.com/open?id=0B1sAPboxsrjFVEI2T2gwSGVHRzA

**Comment by orta** [comment]
A PR is welcome to add the feature where it only updates the source repos you specify, but I don't think this is going to be on our roadmap anytime soon - given that the current behaviour is fine.

**Comment by nivanchikov** [comment]
thanks @orta, I thought the `--sources` option was already there in https://github.com/CocoaPods/CocoaPods/issues/5807? Please correct me if I'm mistaken

**Comment by orta** [comment]
Ah, sounds like a regression then, yeah 👍
