### ISSUE TITLE
Development Pods not Testable with Quick Nimble 

### ISSUE THREAD

**Issue by neeraj-goyal-wibmo** [CocoaPods/CocoaPods#6977]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Followed all the instructions in this tutorial link to create a cocoa pod named **NgFramework**.
1. [Create your first pod](https://code.tutsplus.com/tutorials/creating-your-first-cocoapod--cms-24332)
2. Add a NgConfigSpec : QuickSpec class and write a test that an NgConfig object is initialised.
3. Add a NgConfig swift class in classes folder of pod spec dir structure. Set target as NgFramework.framework
4. If you call default initialiser `NgConfig()` in spec file it says unresolved identifier. Compiler Error.
5. if you add `@testable` annotation before `import NgFramework` the symbol is found. but build fails saying 

> The bundle “NgFramework_Tests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.

6. Make your `NgConfig` class as public. Symbol is found but initialiser is not accessible. So build fails. 
7. Define an `public init(){}` in `NgConfig` class. Build fails with 

> The bundle “NgFramework_Tests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.

## What did you expect to happen?
1. `@testable` should not be mandatory. As demonstrated in `Test.swift` file created by demo `pod lib create <Project>` 
2. Should recognise symbols and access to its functions in the test spec class. 

## What happened instead?
The framework pod does not behave as required for TDD development. Some extra settings or changes are required in the project, which is not know. 

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 27a02f66a5c800d11ace2d9bfae397efd46ec66c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'NgFramework_Example' do
  pod 'NgFramework', :path => '../'

  target 'NgFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
```

## Project that demonstrates the issue
[Example Project](https://github.com/neerajgoyal12/NgFramework)

**Comment by neerajgoyal12** [comment]
**Found a solution for this**

> 1. `Runpath Search Path` in build settings for both project and test target should add `$(FRAMEWORK_SEARCH_PATHS)`
> 2. `@testable` should be used for importing your framework target in spec or test classes. 

> Questions: 
> 1. Should this be done by pod install by default ?
> 2. Is this the correct solution ?
