### ISSUE TITLE
libtool: can't locate file for: -lPods-...

### ISSUE THREAD

**Issue by idokleinman** [CocoaPods/CocoaPods#6985]
I have a workspace/project that is a static lib pod `ParticleSetup` that relies on some other pods as dependencies.
I recently did a rename and changed all the class names prefix from "Spark" to "Particle", and also one of the dependency pods from "Spark-SDK" to "Particle-SDK" - same procedure worked well for that other SDK pod but not for this pod for some reason. 

Full project source can be found here: (it's under `use_renamed_lib` branch):
https://github.com/spark/spark-setup-ios/tree/use_renamed_lib
said target is called `ParticleSetup` and is buildable under the `ParticleDeviceSetup static library` scheme name. Worth mentioning is that pod also has a resource bundle which builds just fine and separately there's an independant framework target which also builds just fine.

I am getting a linker errors when I try to build: `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-ParticleSetup`
and
`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-ParticleSetup is not an object file (not allowed in a library)`

Unsure why, tried many things - as well as uninstalling/reinstalling pods in project.
Any help / directions why this is happening would be greatly appreciated !!

Thank you.

my pod environment is:

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/ido/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ce75a0e48ee23f2f10ffdc3dca43e851353013ac
```

### Installation Source

```
Executable Path: /Users/ido/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 1.6.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

project 'ParticleSetup'
    target 'ParticleSetup' do
        pod 'AFNetworking'
        pod 'Particle-SDK'
        pod '1PasswordExtension'
end
```

Thanks!

**Comment by dnkoutso** [comment]
Try `pod deintegrate` first. It is possible the last integration before the rename is still present in your project.
