### ISSUE TITLE
Ability to add tools from mypod to /Pods/mypod folder, but not in Pods.xcodeproj

### ISSUE THREAD

**Issue by e5faf2** [CocoaPods/CocoaPods#6987]
Hey CocoaPods community.

I'm developing pod which include some python script for class generation. I would like to have this script added to /Pods/mypod physical folder after pod install. 
But at the same time, I would not like to have it being added to Pods.xcodeproj, because it is should not be a part of my Xcode project.

I tried combination of setting on podspec and cant get the result:
- s.source_files add my tool to Pods.xcodeproj - its not good for me
- s.exclude_files do not add my tool - not solving my case
- s.resources - add my tool to Resources of my pod in Pods.xcodeproj and in result copy to bundle, its not good for me.

Is there any way to get the required result by podspec file setup?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by dnkoutso** [comment]
@e5faf2 probably want to use `s.preserve_paths`
