### ISSUE TITLE
-bash: pod: command not found

### ISSUE THREAD

**Issue by rob-nash** [CocoaPods/CocoaPods#6996]
# Report

## What did you do?
Attempt to install cocoapods (first attempt).

ℹ Please replace this with what you did.  
touch ~/.profile

added the following.
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

gem install cocoapods --user-install

## What happened
Installation completed but...
-bash: pod: command not found

## CocoaPods Environment
-bash: pod: command not found

**Comment by paulb777** [comment]
Perhaps /usr/local/bin/pod

**Comment by rob-nash** [comment]
no @paulb777 there is no 'pod' at that location. the path, as stated in the documentation is 

export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

the location is here

$ gem which cocoapods
~/.gem/ruby/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods.rb

**Comment by rob-nash** [comment]
so I did this and it worked

export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/ruby/2.0.0/bin:$PATH
