### ISSUE TITLE
Integrating Pods into Network Extensions (NEXT, .appex) for macOS doesn't work

### ISSUE THREAD

**Issue by CodingMarkus** [CocoaPods/CocoaPods#6998]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Please bear with me that I cannot be totally open about all details here and also share Xcode projects or a full Podfiles, I am simply not allowed to do so.

## What did you do?

I have two targets (actually more than two but only two are relevant). One is an normal  UI application for macOS (mixed Obj-C and Swift code), the other one is a Network Extension (NEXT, .appex) that is embedded within the UI app. The UI is using a couple of pods unrelated to the network extension, the network extension requires only one pod which the UI doesn't.

The Podfile is rather simple, just think of 
```
target 'App' do
# ...
end

target 'Extension' do
  pod 'SomePod'
end
```
and whatever else is essential (like `project` defining project name and how build settings map to debug/release as well as `use_frameworks!` for Swift)

Then I do `pod install` and build the `App` target. Everything builds well and the app itself also runs well, but then I try to start the network extension embedded in the app.

## What did you expect to happen?

As the network extension built correctly I expected it to run correctly.

## What happened instead?

The network extension crashes directly on start with a `dyld` error. `dyld` complains that it cannot load the `SomePod` framework. Turns out that it would try to locate it under

```@rpath/SomePod.framework/Versions/A/SomePod```

Well, the framework is not in the network extension as CP didn't add a copy framework build phase to the 'Extension' target, only a copy resources phase. Instead it copies the framework into the app bundle from the `App` target. Copying the framework manually into the extension bundle where `dyld` expects it fixes the issue.

I somewhere read that extensions must not contain frameworks but that seems to contradict to what Apple writes in their own documentation, so this is either incorrect or outdated:

> Using an Embedded Framework to Share Code
>
> You can create an embedded framework to share code between your app extension and its containing app. For example, if you develop an image filter for use in your Photo Editing extension as well as in its containing app, put the filter’s code in a framework and embed the framework in both targets. 
--> [Source](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html)

Note: A network extension is not loaded by the binary that provides it. It runs in its own dedicated address space, it's an own process. So neither `@executable_path` nor `@load_path` will point to the application binary, in case that was the intention.

Another possible fix was to add the following path to the `LD_RUNPATH_SEARCH_PATHS` setting:
```@executable_path/../../../../Frameworks```

I don't what is better, but whatever the "correct" solution is here, I had expected CP to do just that for me, as apparently it is smart enough to recognize app extensions and treats them special (why else would `SomePod.framework` end up in the app bundle when the app doesn't even reference that pod?)

**Comment by wongzigii** [comment]
@CodingMarkus How do you finally solve this?

**Comment by CodingMarkus** [comment]
@wongzigii 
As mentioned in my report, I manually set the search path (`LD_RUNPATH_SEARCH_PATHS`) for the APPEX target to  `@executable_path/../../../../Frameworks` and this works. Of course, every time you call update or re-install the pod, this change is overridden again but that is less an issue as I rarely ever have to do that and when I have to, I fix it by hand again. If you need to update your pods more often, you may want to add a post-install hook to your podfile to have this automatically fixed for you. [Here's an example](https://stackoverflow.com/a/31804504/15809) how to do it for `OTHER_LDFLAGS`, should work similar for other Xcode settings, too.

I don't know why this issue has been tagged as "d3:hard", considering that the fix is really dead simple: copy the framework to the right folder or set the search path as shown above. But that's not the first time a dead simple problem is not getting fixed, despite the solution being presented on a silver plate. E.g. [that problem](https://github.com/CocoaPods/CocoaPods/issues/7587) is also dead simple to fix, I even presented the full fix with the report, all they needed to do was copy&paste but apparently they are not even able to build a simple test case without external help. As a developer I need reliable tools and nobody is paying me to first code these tools or fix existing ones and why would I spend my free time for fixing tools that I exclusively need on the job? CocoaPods was chosen to save us work but more and more issues force us to make ugly hacks with post-install hooks and at some point that will be more work than this tool can even save us and then we will just abandon it and find something better or return to manage decencies by hand.

**Comment by dnkoutso** [comment]
If the issues are so easy why don't you make the PRs and help everyone? You continue to discard and bash everyone's free time and work here while simultaneously declare that you shouldn't spend your own free time because somehow it is more precious than of others and more entitled.

This is not how open source contributions work. Show the way and please stop complaining and nearly insulting everyone else's time spend here.

**Comment by CodingMarkus** [comment]
You have tagged this bug hard for no particular reason as there is absolutely nothing hard about solving this bug. I presented you with two easy solutions, that is a luxury most developers in this world never have. Do you think my customers come to me and present me with ready-to-use solutions? Still just have closed this bug (or allowed it to be closed) with no attempt to even consider fixing it. So apparently you have no interest in solving this bug, this is the message you send out to the world. We have a saying where I live: The way you shout into the woods is the way the woods shout back at you.

I would not have said anything but then I ran into that other issue and as you can see, this time I wasn't even taking myself the time to write a lengthy, full detailed bug report as I did that last time and what was it worth in the end? Right, nothing. Okay, lesson learned. And this time I even gave you ready to use code, copy & paste it and it would have solved the issue for everyone. No, that's not enough, you require me to first make a whole new sample project for you.

Seriously, if I shall fix all the bugs myself, why do I even waste my time reporting them here? Writing a full featured bug report as I did above was more work than it would have been to fix that bug for myself. Other developers are thankful for people writing reports and presenting them with the solution but all you do is complaining and asking for more and more and more. A detailed bug report? Is not enough. Working code that fixes the problem? Is not enough. Apparently a sample project would not have been enough either, as basically you just said "Go and fix that bug yourself".

Fine, that's what I will do in the future but then I don't have to waste my time to come here and let myself being talked down as the way you treat your bug reporters that really spend their precious time to present you with reports and even fixes is simple disrespectful. This bug is closed and I will not bother you again with another  bug report in the future that apparently heads nowhere anywhere when I report them here. Again, lesson learned.

**Comment by paulb777** [comment]
@CodingMarkus Sorry that the process is not going as you would like. CocoaPods gets more bug reports than there is volunteer bandwidth to address.  You might want to examine how your bug reports compare with the [many CocoaPods bugs that do get fixed](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md).

**Comment by dnkoutso** [comment]
The bug was not closed by me. We have a process that auto-closes issues that people open and do not follow up.

It was also open for 9 months before you posted the "silver-platter" solution. **Way** after this bug was opened.

I won't continue arguing with you as we have reached an impasse here. 

If issues are not handled or closed please at least stop being toxic and bash others with direct or indirect comments against the maintainers.
