### ISSUE TITLE
Pods configs not linked when using different path for Podfile

### ISSUE THREAD

**Issue by tackgyulee** [CocoaPods/CocoaPods#6999]
# Report

## What did you do?

What I was trying to do is to separate the Podfile path and Xcode project path.

So I set up Podfile and Xcode project path differently, i.e:
```
- {{ROOT}}/Podfile
- {{ROOT}}/{{PROJECT_NAME}}/{{PROJECT_NAME}}.xcodeproj
```

Add code to Podfile as:
```ruby
workspace '{{PROJECT_ROOT}}/{{PROJECT_NAME}}'
project '{{PROJECT_ROOT}}/{{PROJECT_NAME}}'
```

Then run `pod install`

## What did you expect to happen?

Pods dependency set up successfully as it were when Podfile path and Xcode project path are same

## What happened instead?

Instead I get the following error, one for each configurations:
```
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `{{PROJECT_NAME}}` to `../Pods/Target Support Files/Pods-{{PROJECT_NAME}}/Pods-{{PROJECT_NAME}}.debug.xcconfig` or include the `../Pods/Target Support Files/Pods-{{PROJECT_NAME}}/Pods-{{PROJECT_NAME}}.debug.xcconfig` in your build configuration (`{{PROJECT_ROOT}}/Pods/Target Support Files/Pods-{{PROJECT_NAME}}/Pods-{{PROJECT_NAME}}.debug.xcconfig`).
```

It seems that Pods config files are not appropriately linked to auto-generated workspace. I looked up `https://guides.cocoapods.org/syntax/podfile.html#group_hooks` but there seems to be no configurations to deal with this issue.

### Stack

```
   CocoaPods : 1.3.0
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/tackgyulee/.rbenv/versions/2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c309da88eedfe998865758936e83213ca12a50d4
```

### Installation Source

```
Executable Path: /Users/tackgyulee/.rbenv/versions/2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

It's a private project, but I'm sure it can be regenerated by using different paths for Podfile and Xcode project file.

**Comment by dnkoutso** [comment]
I think the error message tells you that the project already has a few config files set and you must unset them before cocoapods attempts to set them itself.

I am going to close this one but if you feel strongly this is an issue and I did not understand it correctly please feel free to comment here and also include a sample project to demonstrate the issue.

Sample projects help us reproduce and fix issues many times faster than trying to recreate the environment manually.
