### ISSUE TITLE
10.13 beta (dyld: Library not loaded)

### ISSUE THREAD

**Issue by jamesdaniels** [CocoaPods/CocoaPods#7001]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Linker errors in macOS 10.13 Beta

## What did you do?

Ran `pod install`, cleaned the xcode project, built, ran. 

## What did you expect to happen?

`pod install` would work on macOS 10.13 beta without fuss

## What happened instead?

App crashes on startup with "dyld: Library not loaded" errors.

After some debugging I checked the two cocoapods acting up were, in the form of:

* Diff-macOS.framework
* Diff-OSX.framework
* Diff.framework
* ReactiveKit-macOS.framework
* ReactiveKit-OSX.framework
* ReactiveKit.framework

In my build folder. 

Had nothing other than `Version/A/Resources/Info.plist` in their Frameworks in the compiled .app, copy/pasting the contents that were in the relevant xxx-platform.framework allowed the application to run.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.13 (17A360a)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/james/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d1a48d073fa5aa365bec5e44b432e3fd2997c8bd
```

### Installation Source

```
Executable Path: /Users/james/.rvm/gems/ruby-2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

would rather not paste the rest

## Project that demonstrates the issue

rather not

**Comment by dnkoutso** [comment]
@jamesdaniels sorry without a project to demonstrate the issue makes it ten times harder to debug these.

Please try to get a sample project to demonstrate this.
