### ISSUE TITLE
Miss the path while get specs name form ssh url

### ISSUE THREAD

**Issue by yanzhiwei147** [CocoaPods/CocoaPods#7008]
# Report

## What did you do?

Run `pod install`.

The Podfile content digest:

```ruby
source 'ssh://git@cocoapods.xx.my:/cocoapods/specs.git'
source 'ssh://git@cocoapods.xx.my:/CompiledMirrors/specs.git'

platform :ios, '8.0'

project 'testforsign'

target 'testforsign' do
  pod 'YYYY'
end
```

## What did you expect to happen?

Auto create pod specs repo:

```ruby
xx-cocoapods-specs
- Type: git (master)
- URL:  ssh://git@cocoapods.xx.my:/cocoapods/specs.git
- Path: /Users/arida/.cocoapods/repos/xx-cocoapods-specs

xx-compiledmirrors-specs
- Type: git (master)
- URL:  ssh://git@cocoapods.xx.my:/CompiledMirrors/specs.git
- Path: /Users/arida/.cocoapods/repos/xx-compiledmirrors-specs
```

## What happened instead?

Miss the path `cocoapods` and `CompiledMirrors`
Auto create pod specs repo:

```ruby
xx-specs
- Type: git (master)
- URL:  ssh://git@cocoapods.xx.my:/cocoapods/specs.git
- Path: /Users/arida/.cocoapods/repos/xx-cocoapods-specs

xx-specs-1
- Type: git (master)
- URL:  ssh://git@cocoapods.xx.my:/CompiledMirrors/specs.git
- Path: /Users/arida/.cocoapods/repos/xx-compiledmirrors-specs
```

## CocoaPods Environment

cocoapods 1.2.0
cocoapods-core 1.2.0

**Comment by yanzhiwei147** [comment]
It has not been solved yet.

**Comment by segiddins** [comment]
Can you please share the full error message CocoaPods prints when you try to install? Thanks!

**Comment by yanzhiwei147** [comment]
@segiddins No error message, It is  not a crash bug. I resolve issue in [that PR](https://github.com/CocoaPods/Core/pull/405), but it can't merged now.

**Comment by yanzhiwei147** [comment]
This issue exist in latest version.

**Comment by yanzhiwei147** [comment]
I resolve issue in [that PR](https://github.com/CocoaPods/Core/pull/405), it can merge now?

**Comment by segiddins** [comment]
That PR seems to contain 2 different sets of changes in it...

**Comment by yanzhiwei147** [comment]
oh my god. this issue can literal replication still now.

**Comment by dnkoutso** [comment]
@segiddins we should try to merge this.

**Comment by yanzhiwei147** [comment]
I expect get the result for this issue resolution can be merged, have any one can provide a right resonse?
