### ISSUE TITLE
Option to set HEADER_SEARCH_PATHS to just "${PODS_ROOT}/Headers/Public"?

### ISSUE THREAD

**Issue by fabb** [CocoaPods/CocoaPods#7011]
This is more a question than a bug report.

Currently, CocoaPods generates a `HEADER_SEARCH_PATHS` that looks like this:
```
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Pod1" "${PODS_ROOT}/Headers/Public/Pod2"
```

This allows to write imports in mixed style:
```
#import "Pod2.h"
#import "Pod2/Pod2.h"
#import <Pod2/Pod2.h>
```

The Swift compiler actually has a problem with that, as there currently is a bug when mixing imports of the same file:
https://miqu.me/blog/2017/06/16/fixing-autocompletion-on-mixed-objective-c-and-swift-projects/
TL;DR of that blog post: the Swift compiler does not notice that the same header was imported twice when importing it using mixed styles in the bridging header (or recursively in its imported headers), the result is that it sees duplicate symbols which breaks autocomplete.

I guess if CocoaPods would set `HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public"`, the client project would be forced to use the folder name in the import, and the Swift bug could be avoided.

**So finally to the question: Is there an easy way to configure CocoPods via the Podfile to just set `HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public"`?**

**Comment by fabb** [comment]
https://bugs.swift.org/browse/SR-5842

**Comment by dnkoutso** [comment]
See this PR https://github.com/CocoaPods/CocoaPods/pull/6743

Potentially planning to update the header search paths for 1.5.x maybe 1.4.x but its a big change that could break a lot of integrations today so it needs to be phased out.

**Comment by dnkoutso** [comment]
Stay.

**Comment by dnkoutso** [comment]
Fixed by https://github.com/CocoaPods/CocoaPods/pull/7412
