### ISSUE TITLE
Resources are not installed for all test target's configurations except Debug

### ISSUE THREAD

**Issue by tarbayev** [CocoaPods/CocoaPods#7012]
# Report

## What did you do?

Create a test specification in pod's podspec file containing `resource_bundles`.
Specify test spec with `:testspecs => ['test_spec_name']` for the corresponding pod in Podfile.
Run `pod install`
Edit test target's scheme to run tests for any configuration other than **Debug** (e.g. **Release**).
Run tests for test target.

## What did you expect to happen?

Resources from test specification are installed (copied into test bundle). Tests relying on the resources pass.

## What happened instead?

Resources are not installed (no resource bundle in test bundle). Tests relying on the resources fail.

## CocoaPods Environment

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0
Ruby lib dir : /Users/nick/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d5a73389c142c2ba70e7d659e1cfce54fa9701d1
```

### Installation Source

```
Executable Path: /Users/nick/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
slather               : 2.4.1
```

### Other notes 

The problem seems to be coming from here
https://github.com/CocoaPods/CocoaPods/blob/19203fc02cc0ce57ef221a87aa958ea0a04d7770/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L342

Resource paths map is hardcoded with 'Debug' configuration only ignoring target's configurations completely.

**Comment by dnkoutso** [comment]
@tarbayev yes this was slightly intentional. Lint will actually run it against debug, not release too. Feel free to open a PR that updates this should be easy.
