### ISSUE TITLE
Cannot push to trunk due to "Unrecognized `testspecs` key." 

### ISSUE THREAD

**Issue by macteo** [CocoaPods/CocoaPods#7016]
# Report

## What did you do?

I'm trying to push a new spec containing a `test_spec` to trunk with the command

`pod trunk push`

## What did you expect to happen?

The new spec to be published on trunk.

## What happened instead?

I've got an error:

```
-> "{\"error\":\"The Pod Specification did not pass validation.\",\"data\":{\"warnings\":[\"Unrecognized `testspecs` key.\"]}}"
read 112 bytes
Conn keep-alive
[!] The Pod Specification did not pass validation.
The following validation failed:
- Warnings: Unrecognized `testspecs` key.
```

I've linted and installed the pod locally with success using the  `pod lib lint` and `pod install` commands.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/matteo/.rbenv/versions/2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8eeb0f0a335a584818f7bc00dc93e09fe53b88fb
```

### Installation Source

```
Executable Path: /Users/matteo/.rbenv/versions/2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

This is the offending spec
https://github.com/DimensionSrl/FilterKit/blob/master/FilterKit.podspec

**Comment by orta** [comment]
Looks like trunk may need it's cocoapods-core dependency updating. 

@dnkoutso I thought you pushed podspecs using testspecs?

**Comment by dnkoutso** [comment]
Uh. Yes using `testspecs` is in cocoapods-core and published with 1.3.1.

There are also a few other public pods with testspecs available

**Comment by dnkoutso** [comment]
Sample pod live: ster/Specs/2/0/9/B

Updating of cocoapods-trunk cocoapods and cocoapods-core dependencies PR https://github.com/CocoaPods/cocoapods-trunk/pull/97

**Comment by dnkoutso** [comment]
https://github.com/CocoaPods/trunk.cocoapods.org/pull/231

**Comment by dnkoutso** [comment]
@macteo can you please try again?

**Comment by macteo** [comment]
It worked! Thanks
