### ISSUE TITLE
pod install not honoring cocoapods version in pod.lock file

### ISSUE THREAD

**Issue by btelintelo** [CocoaPods/CocoaPods#7017]
## What did you do?

project A has pod.lock file with cocoapods 1.3.1
project B has pod.lock file with cocoapods 1.2.1

when I run pod install on project B, cocoapods is updated to 1.3.1

## What did you expect to happen?

project B would use cocoapods version 1.2.1 as this is the version specified in the lock file.  I have version 1.2.1 installed.  

I know I can use 1.2.1 with a command line argument, but that is a pain.  Sometimes I don't want to update cocoapods to latest version, just run pod install and run project.

**Comment by DanToml** [comment]
CocoaPods doesn't offer any mechanism to automatically switch versions, we do however recommend [usage a Gemfile](http://guides.cocoapods.org/using/a-gemfile) to ensure that everybody on your team is using the same version consistently.
