### ISSUE TITLE
false pod version!

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#7022]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expect to happen?

Install the current version (i.e 1.2.4) for PBRevealViewController/Swift

## What happened instead?

Installed 1.2.3

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin16]
    RubyGems : 2.4.5
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.4.5
Ruby lib dir : /Users/patrickbodet/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0edcfbdbed7a6308b9992d2d729299ee494b5b64
```

### Installation Source

```
Executable Path: /Users/patrickbodet/.rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'globalview' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for globalview

    pod 'PBRevealViewController/Swift'
    pod 'SVProgressHUD'
    pod 'Firebase/Core'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/AdMob’
    pod 'ESOpenSourceLicensesKit'
  
    post_install do |installer_representation|
        system("ruby Pods/ESOpenSourceLicensesKit/ESOpenSourceLicensesKit/Scripts/generate_licenses.rb --post_install")
    end
  

  target 'globalviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'globalviewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Which pod are you referring about being downloaded as 1.2.3 versus 1.2.4?

**Comment by iDevelopper** [comment]
I have updated the issue description, thanks

**Comment by dnkoutso** [comment]
Try to force `PBRevealViewController/Swift, '1.2.4` in your podspec.

**Comment by dnkoutso** [comment]
Also check your `Podfile.lock` there is possibility one dependency to force version `1.2.3`.

Either way I do not think this is a CocoaPods library issue. Going to close and double check with you when you report back.

**Comment by iDevelopper** [comment]
Not working!

![2017-09-11_17-09-49](https://user-images.githubusercontent.com/1782450/30281989-39734d76-9714-11e7-8100-ab42c6e920a3.png)

**Comment by dnkoutso** [comment]
Use `pod install --repo-update`?

**Comment by iDevelopper** [comment]
Thanks a lot, it works but why?

**Comment by dnkoutso** [comment]
Your internal repo was outdated, it only knew about version 1.2.3. Repo update will update your repos with the latest published pods including 1.2.4 which was released 3 days ago.

**Comment by iDevelopper** [comment]
This is my own repo. All the users have to do this?

**Comment by dnkoutso** [comment]
generally users know they have to update their repos and no this pod is not hosted on your own repo its hosted on the master repo [here](https://github.com/CocoaPods/Specs/tree/master/Specs/4/6/3/PBRevealViewController/1.2.4).

**Comment by dnkoutso** [comment]
Let's stop using this thread for tutorial purposes. Please read https://guides.cocoapods.org/making/specs-and-specs-repo.html and general guides here https://guides.cocoapods.org/

**Comment by iDevelopper** [comment]
Ok thanks, then always use pod install --repo-update? And not pod install?

**Comment by iDevelopper** [comment]
Thanks!
