### ISSUE TITLE
Not getting session email. 

### ISSUE THREAD

**Issue by danieldahan** [CocoaPods/CocoaPods#7024]
Hey! I cannot receive a session with the email daniel@graphkit.io. Thank you!

**Comment by dnkoutso** [comment]
Please file an issue with cocoapods-trunk

https://github.com/CocoaPods/cocoapods-trunk

/cc @orta on this.

**Comment by danieldahan** [comment]
Cool, thanks!

**Comment by danieldahan** [comment]
Can someone help with this issue (https://github.com/CocoaPods/cocoapods-trunk/issues/98) please ?
