### ISSUE TITLE
  error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

### ISSUE THREAD

**Issue by roohi66** [CocoaPods/CocoaPods#7025]
I got this error after `pod install`

> Setting up CocoaPods master repo
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
  Cloning into 'master'...
  remote: Counting objects: 1520989, done.
  remote: Compressing objects: 100% (4367/4367), done.
  error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed

also I have tried `pod setup` and `git clone http://github.com/CocoaPods/Specs.git master ` in repo directory but failed

I dont know maybe should I reinstall OS ?
Do you have any idea ?

**Comment by dnkoutso** [comment]
This seems like an issue with cloning the master repo.

I dont think this is a cocoapods library issue.

Try to clone repo manually https://github.com/CocoaPods/Specs and then place it in `~/.cocoapods/repos/master`

**Comment by BunnyImran** [comment]
@dnkoutso , you mean to just simply place(copy & paste) those spec master files in repos?

**Comment by BunnyImran** [comment]
@dnkoutso actually i did this but i am still getting stuck at cloning part, and then i got this error:

error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by roohi66** [comment]
maybe you put the files in wrong folder 
after copy the files in correct folder go to your project folder and user "pod install" not "pod setup"

**Comment by BunnyImran** [comment]
@roohi66 which files? can you please elaborate.  
There are no files except "pod".

**Comment by sudoFerraz** [comment]
I am also experiencing the same error but with other GitHub repo

**Comment by thumb0422** [comment]
Cloning into 'master'...
remote: Counting objects: 1976654, done.        
remote: Compressing objects: 100% (581/581), done.        
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by i-Roma** [comment]
Have the same issue. Just try adding this line at the top of your Podfile:

> source 'https://github.com/CocoaPods/Specs.git'

Then do `pod install` again. The issue must go

**Comment by Favouroked** [comment]
Does anyone know the solution?

**Comment by Favouroked** [comment]
Does anyone know the solution?

**Comment by roohi66** [comment]
just Try to clone repo manually https://github.com/CocoaPods/Specs and then place it in ~/.cocoapods/repos/master

I did this but got error after multiple try I find out the folder was wrong
just try to copy in diffrent folder .../repo or .../master
it will be ok

**Comment by pelmegov** [comment]
I am also experiencing the same error but with other GitHub repo - `git clone https://github.com/elastic/elasticsearch.git`.
Does anyone know the solution?

**Comment by WANGNEWMAN** [comment]
I Try pod install,But one of dependencies fail, I got this error

**Comment by OrangePJ** [comment]
I also meet the error when clone other repo, but I tried three or four times and it succeeded

**Comment by udarasasanka** [comment]
Just disable to Firewall and start again. It worked for me

**Comment by rogerluan** [comment]
I'm also getting this constantly, but after trying a second time, it works... Fails when installing any pod, really random.

**Comment by mariustop** [comment]
same for me, worked when I tried to clone second time

**Comment by katona85** [comment]
[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress

Cloning into 'master'...
fatal: unable to access 'https://github.com/CocoaPods/Specs.git/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54


thats my full error, if anyone can help.. barney terms, i'm new at this

**Comment by ygg29** [comment]
@roohi66  right ! This is useful to me! but why can't i use  "pod setup"?

**Comment by roohi66** [comment]
@ygg29  'pod install' is like initializing the data that you got,  but 'pod setup' will download all package again from coccapods server.

**Comment by CatzillaOrz** [comment]
I tried 13 times , finally got
```bash 
make install
🍺 
```

**Comment by CatzillaOrz** [comment]
I tried 13 times , finally succeed

**Comment by TimurNurlygayanov** [comment]
please try this solution, worked for me:
https://stackoverflow.com/a/36843260

**Comment by mesqueeb** [comment]
I have the same problem.

### Steps to reproduce:
1. `brew install cocoapods`
2. `pod setup`

Tried this as well:
```bash
git config --global http.postBuffer 524288000
```
But every time somewhere between 5~50% it stops. It first downloads at 3MB / sec but then drops to 4kB / sec and then errors out.

**Comment by dnkoutso** [comment]
CocoaPods 1.8.x will ship with CDN source by default therefore avoiding cloning the git repo.

Note this does not mean that network issues will magically disappear but at least you won't have to clone the repo to begin using CocoaPods

**Comment by nomi9995** [comment]
git config --global http.postBuffer 1048576000

**Comment by dimlark** [comment]
Hello
Similar issue.  I am using MacOS Mojave 10.14.6.
When I run either "pod setup" or "pod setup --verbose", there is no output and it immediately returns to the prompt.  No ".cocoapods" folder is created.  I have disabled the Firewall, and increased the git buffer as indicated earlier.  I have checked the Activity Monitor Network tab, but I do not see any type of "git" connection.  I have run the command, then let everything sit for an hour, but again no folders or files are ever created.
Per a speedtest, I am running at 76.9Mbps.

$ pod setup --verbose
$ 

Thank you in advance

**Comment by lchenfox** [comment]
After trying two days, I still got the same error. Restarting computer, terminal, network settings, nothing does work.

**Comment by LigH-de** [comment]
The reason may be a [Microsoft issue under Windows 7 / Server 2008 R2](https://support.microsoft.com/en-us/help/981344/an-application-may-receive-the-10054-error-when-the-application-receiv); a hotfix was discontinued, you have to use Windows 10 now.

**Comment by tomfriwel** [comment]
> After trying two days, I still got the same error. Restarting computer, terminal, network settings, nothing does work.

Same issue. Various approaches have been tried.

**Comment by vijaysaiM** [comment]
> > After trying two days, I still got the same error. Restarting computer, terminal, network settings, nothing does work.
> 
> Same issue. Various approaches have been tried.

try to connect another network, it works fine.
