### ISSUE TITLE
Dummy provisioning profile "NO_SIGNING/" causing build issues for us

### ISSUE THREAD

**Issue by icecrystal23** [CocoaPods/CocoaPods#7038]
Our command line builds in Xcode 9 have started to fail due to CocoaPods inserting a dummy value of "NO_SIGNING/" into the Provisioning Profile build settings of the Pods project.

Is there some reason the dummy value is required? Our builds work if we delete this dummy value.

**Comment by dnkoutso** [comment]
Related https://github.com/CocoaPods/CocoaPods/pull/6964/files

**Comment by meiravf** [comment]
Any updates on this issue? will it be solved?

**Comment by igoMobile** [comment]
we are experiencing same issue
