### ISSUE TITLE
Apple Mach-O Linker Error - "ld: warning: directory not found" when attempting to build

### ISSUE THREAD

**Issue by kennydust** [CocoaPods/CocoaPods#7039]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I started a new xcode project and initiated a `'pod init'` in the root. This was followed by adding an existing pod, 'Charts' in the `'Pod'` file and then executed a`'pod install'`. So far so good. However, attempting to build failed.

## What did you expect to happen?
I expected the XCode project to successfully build.

## What happened instead?
XCode build failed. With the following error:

![image](https://user-images.githubusercontent.com/4044513/30458269-c8c47804-9978-11e7-922c-cede46f1caca.png)
![image](https://user-images.githubusercontent.com/4044513/30458273-cdc3e2ae-9978-11e7-84eb-11bc3adcc463.png)

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b705cbf94fed30fa51c955ee34640d0b315ff581
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Podtesting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Charts'

  target 'PodtestingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

https://github.com/kennydust/podtesting

**Comment by dnkoutso** [comment]
Thanks for the report and sample project, will take a look.

**Comment by dnkoutso** [comment]
@kennydust I cloned your project and tried it out of the box with CocoaPods 1.3.1 and the build was successful.

Are you sure you are opening `Podtesting.xcworkspace` instead of `Podtesting.xcodeproj`?

**Comment by dnkoutso** [comment]
I am also on Xcode 8.3.3.

**Comment by kennydust** [comment]
@dnkoutso I was loading .xcodeproj. Are we supposed to use .xcworkspace going forward? I had previous used cocoapods version < 1 and recently upgraded.

**Comment by kennydust** [comment]
@dnkoutso from a curiosity point of view; if the .xcodeproj file and cocoapods aren't going to be supported today, are there future plans to support it in newer versions?

**Comment by dnkoutso** [comment]
@kennydust CocoaPods has switched to generate a workspace long time ago, probably ~2 years.

This is the way the library works and it wont change. The workspace is not a big deal in terms of using CocoaPods, it basically brings your `.xcodeproj` and the `Pods.xcodeproj` together.
