### ISSUE TITLE
Test spec stalling with no output for a while (consider xcodebuild verbose flag)

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/CocoaPods#7040]
> Before you start,  are you using the latest CocoaPods release?

Yes, 1.3.1

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

From the [issue59 branch of UnzipKit](https://github.com/abbeycode/UnzipKit/tree/issue59), run `./Scripts/cocoapod-validate.sh`, which basically calls `pod lib lint --verbose`, but sets up some environment variables first.

## What did you expect to happen?

Expected output to be written throughout the unit tests' run.

## What happened instead?

After the unit tests are started, there is no output for a long time. On Travis-CI ((example build)[https://travis-ci.org/abbeycode/UnzipKit/jobs/274427308])), it's going longer than 30 minutes without any output, causing the build to fail. When I run locally, it's going 6 minutes, which is still noticeable. This is the last line before output stalls:

> xcodebuild clean test -workspace /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/CocoaPods-Lint-20170915-1321-1bl59r0-UnzipKit/App.xcworkspace -scheme UnzipKit-Unit-Tests -configuration Debug CODE_SIGN_IDENTITY=

### Stack
```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.12.5 (16F73)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.13.1
Ruby lib dir : /Users/travis/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2fe61865cbe4e17db78b41a0141558755e5d6de1
```
### Installation Source
```
Executable Path: /Users/travis/.rvm/gems/ruby-2.4.1/bin/pod
```
### Plugins
```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

UnzipKit's `issue59` branch (dedicated to implementing the Test Spec) is demonstrating this: https://github.com/abbeycode/UnzipKit/tree/issue59

You can see a sample build that's stalling out here: https://travis-ci.org/abbeycode/UnzipKit/jobs/274427308

**Comment by dnkoutso** [comment]
I am not sure if there is a lot to do here, this is an invocation to `xcodebuild`. It should stall when you copy paste this command directly to your command line.

**Comment by abbeycode** [comment]
I updated with the `pod env` output. Doesn't `xcodebuild` print unit test information as tests run usually? The problem isn't how long it takes, but that there's no output in that time. When you pass the `--verbose` flag to `pod lib lint`, can that get passed to `xcodebuild`? Would that make a difference?

**Comment by dnkoutso** [comment]
@abbeycode should be fairly easy to do this but i think the output will become too verbose. Perhaps that was the intention of the developers?

Either way I am marking this as an easy task. Feel free to edit `validator.rb` and make a PR. If nothing gets done for this then the stalebot will close it eventually :)

**Comment by abbeycode** [comment]
To recap the discussion that's happened on the PR, it actually looks like a lack of verbosity on the part of `xcodebuild` is not to blame. Rather, it's that when the validator calls `xcodebuild`, it's capturing the output instead of sending it to `stdout`. Can we modify it to call `Executable.execute_command` instead of `Executable.capture_command`? I could update my PR to reflect that (or open a new one).

**Comment by abbeycode** [comment]
It looks like the reason `xcodebuild()` uses `capture_command` instead of `execute_command` because it makes use of the command line output regardless of failure, and still uses the status without parsing the output. From what I can tell, `execute_command` doesn't return `output` on failure if you pass `raise_on_failure: true`, but if you don't then you'd need to parse the output just to detect failure at all. Does that sound right?

If all that is correct, then there would be a couple possible approaches I can see: modify `capture_command` to somehow also stream the output when `--verbose` is passed, or create an `execute_command` overload that returns a success variable in addition to its output. Which of those makes sense to you (or an option I hadn't considered)?

**Comment by abbeycode** [comment]
@dnkoutso @orta Any thoughts? I'm ready to submit a new PR, but I need some input/guidance from the CocoaPods team.

**Comment by orta** [comment]
I don't really have any thoughts, I don't have the time to go read all the source code and try provide any directly useful advice (as I haven't touched any of this part of the codebase) - you have the freshest eyes, go with what you think is best

**Comment by DanToml** [comment]
@abbeycode I would be a plus one on making us also print the Xcodebuild output for --verbose.

**Comment by abbeycode** [comment]
I'd appreciate any help you guys can offer on the PR (#7064)

**Comment by abbeycode** [comment]
(Bump)

**Comment by abbeycode** [comment]
PR #7064 is finally passing all validation checks! 🎊

**Comment by dnkoutso** [comment]
Nice! Apologies for the delay to review this, give me next week to review and potentially merge.

**Comment by abbeycode** [comment]
@dnkoutso Just wanted to check in if there are any review issues I need to address yet.
