### ISSUE TITLE
CP 1.3.1 add many resources to input files in `[CP] Copy Pods Resources`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7042]
I found the `[CP] Copy Pods Resources` add many resource files in `input files`, it cause the project file became very large.

<img width="871" alt="qq20170915-211630 2x" src="https://user-images.githubusercontent.com/1251192/30483947-5a374a04-9a5b-11e7-8bc9-62545bd330d2.png">

I check the `copy-resources.sh`, and the files also in the script. So I don't know why to add the files.

**Comment by dnkoutso** [comment]
This works as expected. CocoaPods does this to speed up your re-builds.

Read this http://blog.cocoapods.org/CocoaPods-1.3.0/

**Comment by minwoolee** [comment]
If there are too many input files (especially, when the project paths is too long), Xcode can run into this issue: http://www.openradar.me/15781129  Only workaround was either 1) shorten project path (not always possible), or 2) remove input files in Xcode project manually after `pod install`

Is there any way to disable this optimization?

**Comment by dnkoutso** [comment]
@minwoolee interesting. The only workaround right now is potentially a `post_install` hook that edits the targets, finds the script phases and deletes the input/output files.

This definitely feels like a hack though. I am hoping Apple fixes the real problem.

**Comment by summertian4** [comment]
I have same question.
The project path on our CI machine is very deep, this caused us build failed.
I`m thinking about how to write post_install hook.
What should I do

**Comment by amorde** [comment]
@summertian4 if you'd like to remove input/output paths, you can include this in your `Podfile`

```ruby
install! 'cocoapods', :disable_input_output_paths => true
```
