### ISSUE TITLE
podspec test_spec dependency interfering with application's test target dependencies

### ISSUE THREAD

**Issue by molescat** [CocoaPods/CocoaPods#7043]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
🌈

# Report

## What did you do?
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
App's Test target is missing the pods Quick and Nimble.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /Users/myles_abbott/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 08a1fb0c86484134247d91b13426fa5dd4f3aa3a
```

### Installation Source

```
Executable Path: /Users/myles_abbott/.rbenv/versions/2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

target 'MyApp' do
  use_frameworks!

  # By adding testspecs here, this will mess things up,
  # such that MyApp's Unit Tests can no longer find Quick/Nimble
  pod 'SomeCoolStuff', :path => './modules/SomeCoolStuff', :testspecs => ['Tests']

  # Change it to this and it will work
  # pod 'SomeCoolStuff', :path => './modules/SomeCoolStuff'


  target 'MyAppTests' do
    inherit! :search_paths
    pod 'Quick', '1.1.0'
    pod 'Nimble', '7.0.1'
  end

end
```

### Framework Podspec

```
Pod::Spec.new do |s|
  s.name             = 'SomeCoolStuff'
  s.version          = '0.1.0'
  s.summary          = 'CocoaPods testspecs issue - test rig SomeCoolStuff.'
  s.description      = 'Test rig to examine the test_spec dependency issue for users of a framework that specifies dependencies, when the pod is used locally.'

  s.homepage         = 'https://github.com/molescat'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Myles Abbott' => 'myles.abbott@rea-group.com' }
  s.source           = { :path => '.'}
  s.source_files = 'SomeCoolStuff/Classes/**/*'

  s.ios.deployment_target = '8.0'

  s.test_spec 'Tests' do |t|
    t.source_files = 'Example/Tests/*.swift'
    # I think there is a bug in cocoapods
    # These subspec dependencies will impact the user of this test_spec
    # and literally remove them from your parent project for all targets.
    t.dependency 'Nimble', '7.0.1'
    t.dependency 'Quick', '1.1.0'
  end

end
```

## Project that demonstrates the issue

See example
https://github.com/molescat/cocoapods-testspecs-issue

MyApp has unit tests that are dependant on Quick and Nimble.
MyApp is also dependant on a framework SomeCoolStuff.
SomeCoolStuff itself has unit tests that are also dependant on Quick and Nimble.
The SomeCoolStuff framework is locally pathed, in a modules folder (as seen in the Podfile).
This simple example replicates the issue we are experiencing in a much larger application.

**Comment by dnkoutso** [comment]
@molescat thanks for the report, I believe this is fixed in 1.4.0.beta.1 which we hope to ship very soon.

Is it possible for you to try latest master of CocoaPods and report back if that fixes the issue?

**Comment by dnkoutso** [comment]
@molescat I followed your example with latest master and I think I did it all right. The installation worked and build was successful.

**Comment by dnkoutso** [comment]
I also tested this with Xcode 9 to be specific although I dont think it should be a problem with Xcode 8.

**Comment by dnkoutso** [comment]
@molescat hmm I also tried 1.3.1 itself and it seems to have worked too. Followed your example step by step.

**Comment by molescat** [comment]
@dnkoutso that is awesome news.
I've tested this with master - and it does indeed work.
