### ISSUE TITLE
Size of ~/.cocoapods/repos exceeds 1gb

### ISSUE THREAD

**Issue by chrismanderson** [CocoaPods/CocoaPods#7046]
The size of my `~/.cocoapods/repos` folder is over 1gb (1.3gb to be specific). This seems much too large. Can I remove this folder? Or how can I shrink it down? Trying to maximize every iota of space on a MacBook with minimal storage.

**Comment by dnkoutso** [comment]
@chrismanderson it's because of the specs master repo most likely (https://github.com/CocoaPods/Specs). I do not think anything can be done at this moment to reduce its size but I do understand it is becoming a problem.

**Comment by chrismanderson** [comment]
Yeah, I know folder came about from http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/, but still, I hope there is something that can be done about it in the future. Just too big a folder to require people to keep.

**Comment by orta** [comment]
We've taken a [few attacks](https://github.com/orta/repo_commit_squasher) that this, but realistically it's a hard problem that no-one has volunteered time to fix and maintain. If this is something you're interested at fixing, there's a few ideas:

* Create a smaller binary version of the specs repo that stays local
* Move trunk specs resolving to a server, similar to how bunder works
* Regularly squash the specs repo

**Comment by amorde** [comment]
What if two separate repositories existed, one which `pod trunk` etc. interacted with and retained the full history, and one that is kept in sync but routinely squashed? 

It seems like the main issue is that the history of who/when adds specs is useful and worth keeping, but every user of CocoaPods does not need to be downloading the entire history and keeping a copy on their machine.

**Comment by orta** [comment]
That's what my repo tried to do, but it turns out you don't really gain much from the process alas

**Comment by amorde** [comment]
Just tried checking out the Specs repo and removing the `.git` folder, and it while there is a significant reduction it's most likely not worth the effort.

`192,884,971 bytes (773.4 MB on disk) for 404,973 items`

Attempting to even create a fresh repo takes quite a long time and increases the size dramatically.

**Comment by davidair** [comment]
What if (and I know this is probably a crazy idea) the CocoaPods repo was split into multiple repositories based on some spec partition that would optimize for most common cases? Then the pod installation/update could conceivably function like that:

- Sync the smaller "current" repo first, attempt to resolve all dependencies. If it worked, done.
- Keep syncing additional "archival" repos until the dependencies are fully resolved.

Of course, these would have to be all brand-new repositories and pod trunk push would probably have to publish to both the monolithic repo and the new partitioned ones. Managing the relative sizes of the partitioned repos would also become a continuous maintenance task.

**Comment by chrismanderson** [comment]
What’s the biggest obstacle in implementing a Bundler-type system? The dev work involved, or finding a host/sponsor/etc for server costs?

**Comment by orta** [comment]
I guess dev work to integrate and having admins around to maintain the server infra long term. Server costs are _probably_ fine with our existing relationships - but that service would be mission critical. 

The worrying part for me is that every service we've made so far does not affect someone using CocoaPods, you could always `pod install` if trunk was down for example, an online resolver requires a different level of commitment.

**Comment by dnkoutso** [comment]
Stay.

**Comment by shawnce** [comment]
Yeah the size of this is getting kinda a problem especially in CI setups, etc. Does anyway exist to have pod evaluate the Podfile and generate local spec repo of just the things you currently need? We could then cache that for CI, etc. and only modify it when the Podfile changes?

```
[0:524] (master)> du -hd 1
889M    ./Specs
584M    ./.git
1.4G    .
```

**Comment by orta** [comment]
Wit that you're back to building a web service for resolving which brings it back to https://github.com/CocoaPods/CocoaPods/issues/7046#issuecomment-333401676

Which someone can definitely do, but it's a serious commitment

**Comment by CrazyPython** [comment]
[Homebrew](https://github.com/Homebrew/homebrew-core) doesn't use a centralized server and it doesn't use a lot of space for its build details- perhaps cocoapods could do what homebrew does?

**Comment by amorde** [comment]
@CrazyPython actually Homebrew basically does the same exact thing that CocoaPods does. The reason it doesn't require as much space is that the number of specs is significantly fewer than the number of Podspecs.

**Comment by gautamkrishnar** [comment]
@orta perhaps you guys can apply for openshift open source sponsorship: https://blog.openshift.com/openshift-for-non-profits-open-source-and-educational-institutions/ if you are planning to maintain a server for cocoapods specs.

**Comment by rob-nash** [comment]
It's interesting that @orta considers [this](https://github.com/CocoaPods/CocoaPods/issues/7046#issuecomment-330284751) as an attack and not constructive critisism. 

He [shut me down here](https://github.com/CocoaPods/CocoaPods/issues/8001) and suggested I was too mean. Maybe I could have re-phrased it slightly but still man...get a thicker skin and man up.

**Comment by orta** [comment]
@rob-nash please be more considerate of others feelings on our issues. Constructive criticism is awesome and useful when focused. You definitely have the right provide feedback, that's why we're not deleting or editing your posts - but please stay on topic.

**Comment by rob-nash** [comment]
@orta I understand. I can’t open a thread here to discuss the issue and I suspect it has a lot to do with the fact that this is the public domain. Is there a way I can raise this issue internally, so that only those in control of the fate of cocoapods can see and comment on this issue? The issue being quite simply that cocoapods, in my opinion, is getting in the way of creative iOS development. I just want to smash some UI together man. I have spent hundreds of hours repairing podfiles.

**Comment by amorde** [comment]
> The issue being quite simply that cocoapods, in my opinion, is getting in the way of creative iOS development. I just want to smash some UI together man. I have spent hundreds of hours repairing podfiles.

@rob-nash if you have specific examples of things that CocoaPods could improve on, please do submit an issue with a suggestion for an improvement. But saying that CocoaPods is getting in your way doesn't really help us make it better unless you give some specifics :)

**Comment by amorde** [comment]
Re: 1GB spec repo, the CocoaPods devs also want to fix this. Some possible solutions have been noted [here](https://github.com/CocoaPods/CocoaPods/issues/7046#issuecomment-330284751), including possibly making a service similar to RubyGems. Some others suggested by users in this tread:

* Try squashing commits (this appears to not make enough of a difference, unfortunately)
* Shard the spec repo into multiple repos

A web service similar to RubyGems is likely the best option, but it brings with it some concerns:

* Our ability to maintain another web server over time
* If the service goes down, this may break many teams' workflows
* Potential costs of hosting. This may or may not be a concern for CocoaPods with the resources available at this time

**Comment by amorde** [comment]
Other ways you can mitigate the impact of this to your project right now:

* Create a [custom spec repo](https://guides.cocoapods.org/making/private-cocoapods.html) with just the specs you need, and use that repo in your Podfile
* Commit the `Pods/` directory to source control so that `pod install` isn't required at all when building on CI environments
* Use the `:git` or `:podspec` options when declaring pod dependencies in the Podfile to manually load Pods

None of these options are ideal but they can help alleviate some of the problems that the big specs repo causes until we have a solution in place.

**Comment by rob-nash** [comment]
Regarding your comment [here](https://github.com/CocoaPods/CocoaPods/issues/8001#issuecomment-412300943) @amorde i have done. but the issue [was closed](https://github.com/CocoaPods/CocoaPods/issues/7046#issuecomment-412303742).

**Comment by ashanbrown** [comment]
I've been attempting to accelerate the cocoapods download on circleci by caching a shallow copy of the master spec repo.  However, when I run `pod install --no-repo-update` it tries to updates the repo anyway.   Here's my log:

```
> pod install --no-repo-update
....
Updating spec repo `master`
  Performing a deep fetch of the `master` specs repo to improve future performance
    $ /usr/local/bin/git -C /Users/distiller/.cocoapods/repos/master fetch --unshallow
  $ /usr/local/bin/git -C /Users/distiller/.cocoapods/repos/master fetch origin --progress
  $ /usr/local/bin/git -C /Users/distiller/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/distiller/.cocoapods/repos/master reset --hard origin/master
  fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master-1`.
(CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`)
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sources_manager.rb:35:in `rescue in find_or_create_source_with_url'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sources_manager.rb:38:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:873:in `block in sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:872:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:872:in `sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:780:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
Exited with code 1
```

I see there has been a lot of discussion about shallow repos, but my goal is not to pull a shallow repo directly from github.  I download the repo from s3 (about 45 seconds in circleci) and then shallow clone it to create the copy I will cache.   Is not trying to update the master spec repo something you'd be willing to support?  Thanks.

**Comment by CrazyPython** [comment]
What if JFrog Bintray was used? They have an open-source plan with 1TB/month, which might not be enough, but JFrog might be willing to negotiate due to the prominence CocoaPods holds.

Although BinTray is for application binaries, it could just as easily be for specs. 

Their [API](https://bintray.com/docs/api/#_create_package) has package creation, search, and update. I'm imagining the bot that commits to the specs repo could also create or update bintray at the same time.

**Comment by reitzig** [comment]
This continues to be a serious issue. Usability aside, always retrieving the entire history of all pods that ever were seems ridiculous. So far, I have not read a single argument for the current approach being necessary.

> A web service similar to RubyGems is likely the best option, but it brings with it some concerns:
> 
>     * Our ability to maintain another web server over time
> 
>     * If the service goes down, this may break many teams' workflows
> 
>     * Potential costs of hosting. This may or may not be a concern for CocoaPods with the resources available at this time

You could have a post-receive hook on the spec repo create some form of static website and/or API and host that on Github pages. That way, you don't have to maintain separate infrastructure and the specs can be served efficiently, e.g. via CDNs or caches or whatever Github does to deliver those pages.

**Comment by dnkoutso** [comment]
We did something very similar. We have a mirror of the open source dependencies that we use instead and never declare the `source` directive to the `Podfile` for the open source repo.

Faster repo update update times and installation, more secure since depending on open source dependencies they can change under you.

We have an internal tool that take any podspec zips it up and uploads its sources internally to be hosted and published the podspec to our mirror repo.

**Comment by at-daonguyen** [comment]
Can we move `inactive` pods out of `master` repo?
`inactive` means number of downloads per year is equal to zero.

**Comment by ccorcos** [comment]
Just curious, can someone explain why the Spec repo is necessary to have locally?

**Comment by segiddins** [comment]
It isn’t necessary, you do not need to use the public specs repo to use CocoaPods.

**Comment by ccorcos** [comment]
Hmm. Then why don't we just not clone it?

**Comment by amorde** [comment]
You need it if you want to access the public spec repo (the repository of all public pods) - you don't need it if you use private spec repos, or if you manually specify pods with directives like `:git` or `:path`

There's work being done to improve this - see #8268 and its accompanying PRs for details

**Comment by ccorcos** [comment]
I see. Well there's a good idea!

**Comment by ffffwh** [comment]
An idea for a quick fix
- make a git branch, e.g. `empty`
  - in the branch, `rm -r Specs/`
- `checkout master` before `pod <operation>`, and `checkout empty` after.
- make it an option to satisfy both who often `pod` and who seldom do it or want to save space.

Since git will pack & compress things not in the working tree, it saves space.

**Comment by igor-makarov** [comment]
PRs #8280 & [Core#469](https://github.com/CocoaPods/Core/pull/469) were merged into master on both repos.  
To take advantage of CDN-based spec repo do the following:
* Use a Gemfile and get the latest `cocoapods` and `cocoapods-core` gems from master.
* On command line: `bundle exec pod repo add-cdn jsDelivr-Specs "https://cdn.jsdelivr.net/cocoa/" `
* In your Podfile: `source "https://cdn.jsdelivr.net/cocoa/" `
* If you already have a Podfile.lock replace the `SPEC REPOS` key there as well - there's a bug that prevents it from auto-updating.

**Comment by igor-makarov** [comment]
CDN-based spec retrieval is in 1.7.0 beta.

Perhaps this issue can be closed?

**Comment by strobox** [comment]
> Use a Gemfile and get the latest cocoapods and cocoapods-core gems from master.
On command line: bundle exec pod repo add-cdn jsDelivr-Specs "https://cdn.jsdelivr.net/cocoa/"
In your Podfile: source "https://cdn.jsdelivr.net/cocoa/"`

@igor-makarov  will it be possible to use that with react-native project, how do you think?

Also confused how to change this in Podfile.lock: 
```
SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - boost-for-react-native
```

**Comment by igor-makarov** [comment]
The info in this thread is outdated, go here for official final info:

https://blog.cocoapods.org/CocoaPods-1.7.2/

**Comment by braysonjohn148** [comment]
[cocoapods] anybody with this ziped folder https://github.com/CocoaPods/Specs to provide us the link, taking long to clone from git. Please help, trying to download for month now.

**Comment by jgreen210** [comment]
http://blog.cocoapods.org/CocoaPods-1.8.0-beta/

**Comment by braysonjohn148** [comment]
Please some explanations. I installed pods, after that i run pod setup it started cloning the file which never ended. So how do i do this

**Comment by FranklinYu** [comment]
@braysonjohn148 CocoaPods version? In addition, what’s your `Podfile`?

**Comment by rene-dohan** [comment]
If number of podspecs is the issue what if cocoapods start to do some cleanup of them ? There for sure is a lot of absolete ones, not useful, duplicate and so on... Do you believe you can grow library indefinitely ? I would suggest some radical rules for keeping podspecs in repo and removing all rest to keep size in check.

**Comment by bysiber** [comment]
For anyone landing here looking to reclaim space, the CDN approach (default since CocoaPods 1.8) helps prevent this going forward, but if you still have the old `~/.cocoapods/repos` folder, you can safely remove it (it gets re-fetched as needed).

If you're generally tight on MacBook disk space from dev caches, [ClearDisk](https://github.com/bysiber/cleardisk) can help identify and clean up CocoaPods cache, Xcode DerivedData, Homebrew downloads, node_modules, Docker cache, and other typical space hogs in one pass. It's free and open source, lives in your menu bar and shows sizes for each cache type.
