### ISSUE TITLE
Changing Build Products Path

### ISSUE THREAD

**Issue by willywos** [CocoaPods/CocoaPods#7047]
# Report

Hi, I'm working on a project and I have 3 schemes. Debug, Staging and Release. When I build for Debug and Release it works fine. I found that when I set the Build Products Path in Xcode to ```${SRCROOT}/../build``` I can build my project fine. If not it throws a linker exception that it wasn't able to find the pod. I wasn't sure if I could run a post install hook to set an environment variable or if cocoa pods has a way to set this path some other way? I kind of inherited this project from another dev so I don't know very much about using Cocoapods. 

Thanks all. The project has been really helpful for us.

Here is a screenshot in Xcode to see that the property is inside XCode.

This is what it looks like after I do a ```pod install```
![screen shot 2017-09-18 at 10 59 34 am](https://user-images.githubusercontent.com/101503/30561423-9e8cf7e0-9c80-11e7-8040-e944585e64f2.png)

Then I change this in Xcode to ```${SRCROOT}/../build```
 
![screen shot 2017-09-18 at 10 54 33 am](https://user-images.githubusercontent.com/101503/30561453-b6ac2602-9c80-11e7-9b71-4c55ab71d04c.png)

## What did you do?

```
$ pod install
```
Ran pod install

## What did you expect to happen?

The build products path would be set to ```${SRCROOT}/../build``` instead of ```build```? I'm not sure really.

## What happened instead?

When I run the pod install command, it create a new Pods/Pods.xcodeproj but the setting isn't being saved.

## CocoaPods Environment

$ pod env

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.7.0
Ruby lib dir : /Users/willwilimek/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7e33ed3232ec44c236861f4d2de8de433a4a0682
```

### Installation Source

```
Executable Path: /Users/willwilimek/.rvm/gems/ruby-2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dashtrain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  project 'Dashtrain.xcworkspace'

  # Pods for Dashtrains
  pod 'Fabric'
  pod 'Crashlytics'

  target 'DashtrainTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Comment by dnkoutso** [comment]
Might be a real bug. A post install hook can also change it for you but someone would need to investigate.

A sample project with a similar setup would also be very helpful and speeds up a lot the time needed to fix these issues.

**Comment by dnkoutso** [comment]
@willywos fixed by https://github.com/CocoaPods/CocoaPods/pull/7083

**Comment by willywos** [comment]
@dnkoutso thanks! Can't wait to test it out.

**Comment by dnkoutso** [comment]
Merged. Not shipped yet but you can still use it if you use Bundler and point to master or the SHA.

**Comment by willywos** [comment]
Verified it worked by having bundler update to master. Thanks @dnkoutso so much!

**Comment by dnkoutso** [comment]
Perfect!
