### ISSUE TITLE
Module-name swift file not found on Unit Tests scheme

### ISSUE THREAD

**Issue by benjdum59** [CocoaPods/CocoaPods#7050]
I decided recently to migrate my iOS application to the newest stable version of CocoaPods (was 0.39 now is 1.3.1). Since I did the migration. I have lot of problems with compilation (for all my schemes/targets). I succeed to make all "normal" schemes compile again but I still have an issue with my unit test target with a File not found on MyApp-Swift.h. My project is on originally Obj-C project created with some new classes written in Swift. Everything worked on CocoaPods version 0.39. 

This is my environment:

- cocoapods : 1.3.1
- XCode : 8.3.3
- Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

abstract_target 'defaults' do
  pod 'AFNetworking', '~> 2.4'
  pod 'SVProgressHUD', '2.0.3'
  target 'MyApp PRD'
  target 'MyApp-dev'
  target 'MyApp-tests'
  target 'MyApp-devTests' do
    inherit! :search_paths
    pod 'AFNetworking', '~> 2.4'
  end
end
```

Note : My PodFile is an example (not all the pods are written).

**Comment by dnkoutso** [comment]
Please provide a sample project. Its very hard to reproduce problems like these without a sample project demonstrating the issue.
