### ISSUE TITLE
"Expand" button on Cocoapods website 

### ISSUE THREAD

**Issue by idokleinman** [CocoaPods/CocoaPods#7053]
I had a pod called [Spark-SDK](https://cocoapods.org/?q=spark-sdk) which has been deprecated in favor of a new pod called [Particle-SDK](https://cocoapods.org/?q=particle-sdk).
The old one has the "Expand" button and a page with download stats while the new one, which is identical in form and function only shows "Docs" and "Site" buttons and does not lead to the page with the download stats.

What is the reason for that and how can it be solved?

**Comment by orta** [comment]
Please don't use this repo for issues about the website, as the issue template says this repo is for the CLI tool. The [CocoaDocs repo](https://github.com/CocoaPods/cocoadocs.org) has a lot of information about how to debug these kind of issues yourself.

**Comment by idokleinman** [comment]
OK my apologies, readme does not show any leads on that issue, is there any troubleshooting guide? Shall I post the issue there?
