### ISSUE TITLE
Pod dependency in podspec support specifying branch

### ISSUE THREAD

**Issue by zhuhuihuihui** [CocoaPods/CocoaPods#7055]
Hey, currently we can't specify branch for pod dependencies in podspec. It would be great to have that feature.

**Comment by dnkoutso** [comment]
I don't think the DSL will ever allow this for podspecs. In the meantime you can "override" the dependency in your `Podfile`.

Like so:

```ruby
pod 'MyPod', git: 'https://github.com/MyPod/MyPod.git', branch: 'somebranch'
```

Going to close this.

**Comment by zhuhuihuihui** [comment]
Hi @dnkoutso, thank you for your response. Will the "override" affect my pod as well? For my case, I have  a `pod` that has some dependencies and an app that use this pod.  I  can "override" the dependency in my Podfile of my app which will affect my app, but will my pod be able to take that benefit as well? Cause there's code in my pod that use those dependencies.  

Thanks,
Scott

**Comment by dnkoutso** [comment]
Unfortunately not. Your podspec at this time does not support the ability to point to a specific branch. Pods are meant to be "final" when they are public and if developers want to work on a branch of your pod then they can use the method above.

I am sorry but I do not think it will be built into the podspec in the near future.

**Comment by zhuhuihuihui** [comment]
Make sense, thanks for your clarification.
