### ISSUE TITLE
Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`

### ISSUE THREAD

**Issue by SrikarMudapally** [CocoaPods/CocoaPods#7062]
![screen shot 2017-09-25 at 2 23 28 pm](https://user-images.githubusercontent.com/32189093/30800472-b73afd00-a1fd-11e7-8753-dc42eddfb568.png)

Help me out with this issue

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
