### ISSUE TITLE
pod lib lint Error: Bundle identifier is missing. App doesn't have a bundle identifier for the Release build configuration. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor.

### ISSUE THREAD

**Issue by Namunaka** [CocoaPods/CocoaPods#7063]
## What did you do?

Need to use real machine compiler So update validator.rb 

before
      when :ios
        command += %w(CODE_SIGN_IDENTITY=- -sdk iphonesimulator)
        command += Fourflusher::SimControl.new.destination(:oldest, 'iOS', deployment_target)

after 
      when :ios
        command += %w(-sdk iphoneos11.0 -destination=generic/iOS ONLY_ACTIVE_ARCH=NO ARCHS=armv7)

but will return error when pod lib lint 

How do I need to configure the certificate for the compilation environment?

## What did you expect to happen?

pass verification

## What happened instead?

Error: Bundle identifier is missing. App doesn't have a bundle identifier for the Release build configuration. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor.

## CocoaPods Environment

xcode9
cocoapods 1.3.1

**Comment by orta** [comment]
Can you provide an example?

**Comment by Namunaka** [comment]
anyone cocoapods project ，Just modify the file validator.rb to armv7 will show this error

**Comment by dnkoutso** [comment]
Cannot resolve issues without a sample project.

**Comment by Namunaka** [comment]
sorry this is project git.  https://github.com/Namunaka/NMTools   Need to be modified validator.rb and this file I have uploaded to git

**Comment by dnkoutso** [comment]
I cannot attempt to repro this because `XXTools` cannot be found, is it on a private repo?
