### ISSUE TITLE
"'metal_stdlib' file not found" when i try to validate and build my podspec

### ISSUE THREAD

**Issue by LSJFR** [CocoaPods/CocoaPods#7073]
# Report

## What did you do?

pod lib lint MyPod.podspec

## What did you expect to happen?

Validate my pod to push it to my private repo

## What happened instead?

error: 'metal_stdlib' file not found

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bitbucket-degrader-degradr-core-3 - https://bitbucket.org/degrader/degradr-core-3.git @ 0d4a0842f0da5c059359bd330d59cb6bc77a60b4
               bitbucket-degrader-degradr-math - https://bitbucket.org/degrader/degradr-math.git @ e186d202de6c1904449bd5c370738b95f40f8a79
               Lumiscaphe - git@argon:com.lumiscaphe.pods @ 8106669f01f77e56c879bd95d23696e97aa0e8ae
               master - https://github.com/CocoaPods/Specs.git @ fed865feba65cb17eefaec20720aa8ff57246a93
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
``

## Project that demonstrates the issue

I can't upload this projet for now

The project compile when i build it alone (From the .xcodeproj)

But when i try to validate it with "pod spec lint" this message is showed : 
"error: 'metal_stdlib' file not found"

When i launch the generated project ("App.xcworkspace") by the pod command, the error is the same.

Thanks in advance !

**Comment by dnkoutso** [comment]
Are you linking the library in your podspec? See https://guides.cocoapods.org/syntax/podspec.html#libraries

Unfortunately the information given is too vague without a podspec or a sample project to reproduce.

It's hard to spend time to guess so I will close this issue, please re-open if you can provide a reproducible sample of this issue.

**Comment by LSJFR** [comment]
Hello,

I added spec.libraries directive but it won't work.

You will find here an example : 
[https://github.com/LSJFR/sample_metalstdlib](https://github.com/LSJFR/sample_metalstdlib)

Thanks for your help.

**Comment by dnkoutso** [comment]
@LSJFR I dont think this is a cocoapods issue. Your `.h` file has `#include <metal_stdlib>` which doesnt seem to work but it does work for `.metal` file.

I am not very familiar with Metal but I am very confident this is not an issue with CocoaPods.

**Comment by woaiios** [comment]
@LSJFR did you solve it?

**Comment by LSJFR** [comment]
Hi,

I embeded my project instead of use cocoapods...

**Comment by XieLinhua** [comment]
@LSJFR I also encountered this problem. I found a solution to resolve this issue.  In your `HRMaterialSeamUniform.h` and `HRMetalHelper.h`, add below code:

```
#if __METAL_MACOS__ || __METAL_IOS__

#include <metal_stdlib>

using namespace metal;

#endif /* __METAL_MACOS__ || __METAL_IOS__ */
```

Any thing related to `Metal` in your shader .h files, you should use this macos.

**Comment by Insofan** [comment]
> @LSJFR I also encountered this problem. I found a solution to resolve this issue. In your `HRMaterialSeamUniform.h` and `HRMetalHelper.h`, add below code:
> 
> ```
> #if __METAL_MACOS__ || __METAL_IOS__
> 
> #include <metal_stdlib>
> 
> using namespace metal;
> 
> #endif /* __METAL_MACOS__ || __METAL_IOS__ */
> ```
> 
> Any thing related to `Metal` in your shader .h files, you should use this macos.

But xx.m use this `HRMetalHelper.h`file can't find the code in side

**Comment by tbfungeek** [comment]
i  have the same error any solution
