### ISSUE TITLE
vendored_library where library is distant

### ISSUE THREAD

**Issue by Larmichou** [CocoaPods/CocoaPods#7074]
FYI my current version:
>$ pod --version
>1.1.1

I'm between asking if it's possible, and in the other case, if other can be interested in it, and if doable to be available in a next release of CocoaPods.

### Why?
Static libraries (.a) may be quite heavy.
To manage them on Git, it's recommended to use Git LFS (Large File Storage). Git repositories have a limit on size.
Unfortunately, this can be quite expensive ($), and in a team usage, we may use a private/local server.
We receive quite regularly a debug static library and a release static library from partners, and it's exceeding the size repository limit.

### Suggestion:
Is it possible to use *:http =>* (and others distant access) on  *vendored_library*?

Possible use: 

    s.ios.vendored_library = {:http => "http://www.myPrivateServercom/VersionNumberOrTaG/libMyStaticLibrary.a"}

Currently, on running a `>$ pod spec lint`

     -> MyPodSpec (0.0.1)
        - ERROR | [iOS] unknown: Encountered an unknown error (undefined method `gsub' for ["http", "http://www.myPrivateServercom/VersionNumberOrTaG/libMyStaticLibrary.a"]:Array) during validation.

Or is there already a better way to do it and already a working one, and I'm missing something.

**Comment by dnkoutso** [comment]
You can pack your library in a zip file and change the source to be a zip then point to the vendored library from within the zip file. We do plenty of this internally.

Here's a sample:

```json
{
  "name": "CannonPodder",
  "version": "1.0.5",
  "summary": "Small library that can be used for some stuff",
  "license": {
    "type": "Proprietary",
    "text": "© 2017 Something, Inc."
  },
  "authors": {
    "Something": "someone@someinc.com"
  },
  "homepage": "http://www.something.com",
  "source": {
    "http": "https://somelink.to/download/cocoapods/CannonPodder-1.0.5.zip",
    "sha256": "dadb7892455944930ee3dfeb397e579f3aaa76f3e8bc76b94290535efe718238"
  },
  "resource_bundles": {
    "CannonPodderResources": [
      "Resources/**/*"
    ]
  },
  "platforms": {
    "ios": "9.0",
    "osx": "10.10"
  },
  "ios": {
    "source_files": "ios/CannonPodder.framework/**/*.{h,hh}",
    "vendored_frameworks": "ios/CannonPodder.framework"
  },
  "osx": {
    "source_files": "osx/CannonPodder.framework/**/*.{h,hh}",
    "vendored_frameworks": "osx/CannonPodder.framework"
  }
}

**Comment by dnkoutso** [comment]
Closing as I don't think this is an issue with a library or there is any plan to support something like this in the future.
