### ISSUE TITLE
Deployment Target not set via Cocoapods 

### ISSUE THREAD

**Issue by RabbitMC** [CocoaPods/CocoaPods#7076]
# Report

## What did you do?
Deployment Target not set via CocoaPods 

Create a iOS Xcode 9 project, with Swift 4 usage.
Create a Podfile a simple as possible
Add `platform :ios, '10.0'` for iOS 10.0 as minimum deployment target
Run `pod install`
Check deployment target in Xcode 9, it will be 11.0

## What did you expect to happen?

Configure iOS 10.0 as minimum deployment target

## What happened instead?

Configured iOS 11.0 as minimum deployment target

## CocoaPods Environment
Version is 1.3.1
Xcode 9
macOS 10.13
Swift 4

**Comment by staminajim** [comment]
This just happened to me too.

Downgrading xcodeproj from 1.5.2 to 1.5.1 seems to make it work again.

**Comment by RabbitMC** [comment]
Where do you downgrade `xcodeproj`? 
Can you give me a detailed instruction?

**Comment by dnkoutso** [comment]
Can you provide a quick sample project demonstrating the issue?

**Comment by RabbitMC** [comment]
Sure:
[FooBar.zip](https://github.com/CocoaPods/CocoaPods/files/1337588/FooBar.zip)

**Comment by dnkoutso** [comment]
Thanks!

**Comment by dnkoutso** [comment]
Hm I can see the issue but I couldn't get it fixed by downgrading to xcodeproj 1.5.1.

**Comment by dnkoutso** [comment]
@RabbitMC are you referring to the deployment target in `Pods.xcodeproj` or `FooBar-iOS.xcodeproj` project in the sample you gave me? 

Looking from the code I don't think cocoapods ever sets the deployment target to the users project. From looking into `Pods.xcodeproj` all deployment target values are set correctly.

**Comment by dnkoutso** [comment]
<img width="1151" alt="screen_shot_2017-09-27_at_7_54_41_am" src="https://user-images.githubusercontent.com/310370/30920623-4ead760c-a359-11e7-9f1e-4bb65199100e.png">

**Comment by RabbitMC** [comment]
@dnkoutso You are totally right. Sorry for that opening that issue.

**Comment by dnkoutso** [comment]
No problemo my friend! Enjoy.
