### ISSUE TITLE
Custom build configuration doesn't define correct build directory variable.

### ISSUE THREAD

**Issue by lolgear** [CocoaPods/CocoaPods#7081]
I have one custom build configuration PublicBeta.
It is duplicate of Release configuration.
After all I have three build configurations.

Debug, Release and PublicBeta.

I have a complex workspace structure.
Several frameworks and main app.

After installing pods I noticed that $BUILD_DIR variable has default 'build' value.

For example:
In app:
```
//:configuration = Debug
// has build/Debug-iphoneos
CONFIGURATION_BUILD_DIR = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)

//:configuration = PublicBeta
// has build/PublicBeta-iphoneos
CONFIGURATION_BUILD_DIR = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)

//:configuration = Release
// has build/Release-iphoneos
CONFIGURATION_BUILD_DIR = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
```

In Pods project:
In Pods-App.framework target:
```
//:configuration = Debug
SYMROOT = ${SRCROOT}/../build

//:configuration = PublicBeta
SYMROOT = build

//:configuration = Release
SYMROOT = ${SRCROOT}/../build
```

**Comment by dnkoutso** [comment]
@lolgear thanks, probably this is a bug can you get a small example project to demonstrate it? Doesn't have to be the actual project you are using.

**Comment by lolgear** [comment]
[CustomBuildConfigurationDemo.zip](https://github.com/CocoaPods/CocoaPods/files/1339001/CustomBuildConfigurationDemo.zip)

**Comment by dnkoutso** [comment]
👍

**Comment by dnkoutso** [comment]
@lolgear fixed with https://github.com/CocoaPods/CocoaPods/pull/7083

**Comment by lolgear** [comment]
@dnkoutso any workarounds before prerelease?

**Comment by lolgear** [comment]
@dnkoutso 

Not sure if this snippet could help. I still have build errors.

```
		post_install do |installer_representation|
	    	release = installer_representation.pods_project.build_configurations.select {|c| c.name == 'Release'}.first
			installer_representation.pods_project.build_configurations.select {|c| c.name != 'Release' }.each do |config|	config.build_settings['SYMROOT'] = release.build_settings['SYMROOT']
			end
		end
```

**Comment by dnkoutso** [comment]
check out if the project has the correct SYMROOT set after you run pod install.

You should be able to make it work with a post install hook.

**Comment by lolgear** [comment]
@dnkoutso yes, it is solve demo project dependencies.

However, I have more complex project structure.

Please, have a look at updated project.

( Only app target has custom configuration, framework target doesn't have custom configuration ).
[CustomBuildConfigurationDemo.zip](https://github.com/CocoaPods/CocoaPods/files/1351574/CustomBuildConfigurationDemo.zip)

As expected framework was build in Release build configuration and can not be found in PublicBeta-iphoneos build configuration.

I have updated main app target build setting framework search paths by adding 
```
"$PODS_BUILD_DIR/Release$(EFFECTIVE_PLATFORM_NAME)"
```
to search inside Release builds.

However, copy phase broken.
