### ISSUE TITLE
Product with single quotes in name fails to build

### ISSUE THREAD

**Issue by jordanperry** [CocoaPods/CocoaPods#7090]
# Report

## What did you do?
Run `pod install` using version 1.2 or later (currently using 1.3.1)
Attempt to build, observe failure

## What did you expect to happen?
Build success

## What happened instead?
Build fails with > Pods-OBF/Pods-OBF-frameworks.sh: eval: line 81: unexpected EOF while looking for matching `''

## Workarounds
Go to line 81, replace `'$1'` with `\"$1\"`

Appears to be introduced here: https://github.com/CocoaPods/CocoaPods/commit/787813313fa8628801387d32a426b80363e178b8

**Comment by dnkoutso** [comment]
@jordanperry want to provide a PR that fixes this including tests? Careful though because this change happened on purpose to fix another issue which I do not recall and I need to dig up for you.

**Comment by jordanperry** [comment]
@Rajveer86 I've updated the Podfile for the project that experiences this issue to contain the following, so that I don't have to manually update my file after running `pod install`:

```
post_install do |installer|
    text = File.read("Pods/Target Support Files/Pods-Project/Pods-Project-frameworks.sh")
    new_contents = text.gsub(/'\$1'/, "\\\"$1\\\"")

    File.open("Pods/Target Support Files/Pods-Project/Pods-Project-frameworks.sh", "w") {|file| file.puts new_contents}
end
```

@dnkoutso I haven't had the time to look into providing a fix inside CocoaPods. We are satisfied with the workaround here.

**Comment by Rajveer86** [comment]
@jordanperry Thank you for posting your post_install script, that works perfectly for me!
