### ISSUE TITLE
Resources of static_framework are not copied to the link target

### ISSUE THREAD

**Issue by anton-matosov** [CocoaPods/CocoaPods#7094]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I am trying out the static_framework in 1.4 beta 1 and found an issue with resources.
If resources are included directly into the pod that declares static_framework=true, then these resources are ignored and not copied to the target

## What did you do?
Created a pod that has static_framework=true and added resources to it

## What did you expect to happen?
Resources and resource bundles of the pod that is static framework should be copied to the target the same way as it happens with static libraries.

## What happened instead?
Resources and/or resource bundles have been ignored and not copied to the target

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-darwin16]
    RubyGems : 2.4.5.2
        Host : Mac OS X 10.13 (17A365)
       Xcode : 9.0 (9A235)
         Git : git version 2.12.0
Ruby lib dir : /Users/antonmatosov/.rbenv/versions/2.2.6/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e779e58b99234b7d52bc0a9b29203dc970eadba6
```

### Installation Source

```
Executable Path: /Users/antonmatosov/.rbenv/versions/2.2.6/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.2.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
use_frameworks!

target 'StaticFrameworkResources_Example' do
  platform :ios, '11'
  pod 'StaticFrameworkResources', :path => '../'

  target 'StaticFrameworkResources_Tests' do
    inherit! :search_paths

    
  end
end
```

## Project that demonstrates the issue
https://github.com/anton-matosov/StaticFrameworkResources

**Comment by paulb777** [comment]
@anton-matosov Thanks for the report. I'll take a look within the next week.

**Comment by anton-matosov** [comment]
You are welcome @paulb777 
Thank you for implementing static_framework support!

**Comment by dnkoutso** [comment]
@anton-matosov the fix was merged, want to try using master SHA to verify it works also?

**Comment by anton-matosov** [comment]
Nice! I will give it a shot tomorrow.

**Comment by anton-matosov** [comment]
Couldn't stand it. Checked right away and it works as expected!
Thanks @dnkoutso and @paulb777 for fixing this issue!

**Comment by paulb777** [comment]
@anton-matosov Glad it worked! 👍  Thanks again for trying out the beta and the report.
