### ISSUE TITLE
inhibit_all_warnings! doesn't work for Share extention if use_frameworks! is specified

### ISSUE THREAD

**Issue by ws233** [CocoaPods/CocoaPods#7095]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

In our workspace we have 2 targets: the main project and a share extention.
Also in the Podfile we have the following:
```
inhibit_all_warnings!
use_frameworks!
```
This causes all warnings to be hidden in the main target, but still they appear in the share target.
If I remove the `use_frameworks!` from the Podfile the warnings in the Share extention target disappear as well.

## What did you expect to happen?

All warnings should be hidden in the share extention even if `use_frameworks!` is used.

## What happened instead?

The subprojects warnings are visible while building share extention.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.8.4
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : alekoleg - https://github.com/alekoleg/AOSpec @ f48f17fc17fed912d62cf47725029bc5c1e3c70b
               master - https://github.com/CocoaPods/Specs.git @ 9e86bcefca64b4caf560f92a4cdb1e402e139c96
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false
workspace 'Workspace'

def commonTargets
    pod 'RMPhoneFormat', :git => 'https://github.com/bomjkolyadun/RMPhoneFormat.git'
    pod 'CocoaLumberjack', '3.2.1'
    pod 'AFNetworking', '3.0'
    pod 'MBProgressHUD'
    pod 'UIViewController+KeyboardAnimation', '1.3'
    pod 'Fabric', '1.6.13'
    pod 'Crashlytics', '3.8.6'
    pod 'ZendeskSDK', '1.11.0.1'
    pod 'SSZipArchive', '1.6.2'
    pod 'TrustKit', '1.5.1'
    pod 'Typhoon', '4.0.2'
end

def mainTargets
    commonTargets
    pod 'CrutchKit', :git => 'https://github.com/CognitiveDisson/CrutchKit.git', :tag => '0.0.11'
    pod 'SocketRocket', :git => 'https://github.com/facebook/SocketRocket.git', :commit => '877ac7438be3ad0b45ef5ca3969574e4b97112bf'
    pod 'THContactPicker', '2.0'
    pod 'Masonry', '1.0.2'
    pod 'MRProgress', '0.8.3'
    pod 'MTMigration', '0.0.5'
end

#main targets
target :"Target" do
    mainTargets
end

target :TargetUnitTests do 
    pod 'OCMock', '3.3'
    pod 'OHHTTPStubs', '5.2.1'
    pod 'AFNetworking', '3.0'
    pod 'CocoaLumberjack', '3.2.1'
end

#extentions
target :"Share" do
    commonTargets
end

target :"Common" do
    project 'Common/Common'
    pod 'CocoaLumberjack', '3.2.1'
end

target :"CommonTests" do
    project 'Common/Common'
    pod 'CocoaLumberjack', '3.2.1'
end

target :"Storage" do
    project 'Storage/Storage'
    pod 'CocoaLumberjack', '3.2.1'
end

target :"StorageTests" do
    project 'Storage/Storage'
    pod 'OCMock', '3.3'
    pod 'CocoaLumberjack', '3.2.1'
end
```

**Comment by dnkoutso** [comment]
Can you please upload a tiny sample project that demonstrates the issue? It makes it 1000x easier for us to debug and fix these issues.

**Comment by suihan** [comment]
the same,my warning like after using inhibit_all_warnings!:
[!] Found multiple specifications for `Fabric (1.6.11.1)`:
- /Users/lesetong/.cocoapods/repos/xxx-ios-team-3rdpartyframeworkspec/Fabric/1.6.11.1/Fabric.podspec.json
- /Users/lesetong/.cocoapods/repos/xxx-ios-team-mgjpodspec-framework/Specs/Fabric/1.6.11.1/Fabric.podspec.json

[!] Unable to read the license file `/Users/lesetong/temp/xxx/Pods/Aspects/LICENSE` for the spec `Aspects (1.4.1.1)`

**Comment by ws233** [comment]
Any thoughts about this?
