### ISSUE TITLE
Feature: Version Available Notifier in Pod output

### ISSUE THREAD

**Issue by mohpor** [CocoaPods/CocoaPods#7096]
🌈 Since Swift has been introduced, a lot of us have chilling nightmares as we close to September when we have to manage a lot of dependencies which will (undoubtedly) break due to Swift version and/or iOS  incompatibilities. For this reason or for a variety of reasons, some may choose to stick to an specified version or git or whatever means to be able to work on their project. But, they have to check on the projects to see if there is a new version for that Pod that might solve their problem.

I suggest we have an Update Indicator in the Pod update output log to indicate there is an update available for the Pod.
Something like this:

> Installing IGListKit 3.1.1 (was 3.1.1) ** 3.1.2 is availabe

**Comment by dnkoutso** [comment]
@mohpor there is a command already `pod outdated` that will do this.

I don't think it will be built into the `pod install` command. Going to close this but if you feel strongly or don't believe `pod outdated` does the trick please respond here and I can re-open.

**Comment by mohpor** [comment]
Wow, How did I miss that!
Thanks
