### ISSUE TITLE
PodOne and PodOne/Extension can't be installed alongside when pulled from git repository

### ISSUE THREAD

**Issue by besi** [CocoaPods/CocoaPods#7097]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod install` with a "double-dependency" (What would be the correct name for that anyway?)

```ruby

  # ...
platform :ios, '9.0'
use_frameworks!

target 'MyApp' do
  swift_version = '4.0'
  # ...
  pod 'PromiseKit', git: 'https://github.com/mxcl/PromiseKit', branch: 'master' #, '~> 4.3.2'
  pod 'PromiseKit/UIKit', '~> 4.0'
end
```

## What did you expect to happen?

The sources of both pods should be installed, just like when using the pods without `git`-reference.
```ruby
pod 'PromiseKit'
pod 'PromiseKit/UIKit'
```
## What happened instead?

I get the following error messsage:
> [!] There are multiple dependencies with different sources for `PromiseKit` in `Podfile`:
> 
> - PromiseKit (from `https://github.com/mxcl/PromiseKit`, branch `master`)
> - PromiseKit/UIKit (~> 4.0)

In some cases (new swift-version) etc. I do need pods with the `git:` option. So I need to be able to install these along side other.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin15]
    RubyGems : 2.4.5
        Host : Mac OS X 10.13 (17A365)
       Xcode : 9.0 (9A235)
         Git : git version 2.11.0
Ruby lib dir : /usr/local/var/rbenv/versions/2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1bea355a550e09c597b039dfca571e5cfac92225
```

### Installation Source

```
Executable Path: /usr/local/var/rbenv/versions/2.2.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'


use_frameworks!

target 'ShopInventory' do
    
  swift_version = '4.0'
    
  pod 'Eureka', '~> 4.0.0'
  pod 'LLSimpleCamera', '~> 5.0'
  pod 'EZSwiftExtensions', git: 'https://github.com/goktugyil/EZSwiftExtensions', branch: 'swift4'
  pod 'BSImagePicker', git: 'https://github.com/mikaoj/BSImagePicker', branch: 'master'
  pod 'PKHUD', git: 'https://github.com/pkluz/PKHUD.git', branch: 'release/swift4'
  pod '1PasswordExtension', '~> 1.8.4'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.0.1'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'ObjectMapper', '~> 2.0'
  pod 'MagicalRecord', '~> 2.3.2'
  pod 'Locksmith', '~> 4.0.0'
  pod 'ImageRow', git: 'https://github.com/EurekaCommunity/ImageRow', branch: 'master'
  pod 'PromiseKit'
  pod 'PromiseKit/UIKit'

  # pod 'XCGLogger', '~> 4.0'  
end
```

**Comment by dnkoutso** [comment]
Right now subspecs always fall into the same "parent" target and are not separate targets. The way this is structured what you are asking cannot be done without significant changes under the hood to support splitting of subspecs into different targets.

@besi I apologize in advance but I do not foresee this being supported anytime soon so I am going to close this.

**Comment by besi** [comment]
According to https://github.com/PromiseKit/UIKit/issues/7#issuecomment-333874558 I should be able to do this:

You can do:

```ruby
pod 'PromiseKit',
    git: 'https://github.com/mxcl/PromiseKit', branch: 'master',
    subspecs: ['Foundation', 'UIKit']
As a workaround.
```
