### ISSUE TITLE
pod CLI not working anymore after HighSierra upgrade and cocoapods reinstall

### ISSUE THREAD

**Issue by vitobellini** [CocoaPods/CocoaPods#7102]
# Report

## What did you do?

ℹ pod <any command>

## What did you expect to happen?

ℹ pod should works   

## What happened instead?

ℹ Throws exception, gem not found
`/Library/Ruby/Site/2.3.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.3.0/rubygems.rb:299:in `activate_bin_path'
	from /usr/local/bin/pod:23:in `<main>'`
## CocoaPods Environment

ℹ Unable to run pod env, same error of above

I'm using HighSierra, I have updated cocoa pods after OS upgrade by the following way:
`sudo gem update --system
sudo gem install -n /usr/local/bin cocoapods`

I also have updated gems:
`gem update --system`

**Comment by consbulaquena** [comment]
In Terminal:
1: `sudo gem uninstall cocoapods `

2: `sudo gem install -n /usr/local/bin cocoapods`
