### ISSUE TITLE
Presentr error at "let font = CGFont(provide"

### ISSUE THREAD

**Issue by pprevalon** [CocoaPods/CocoaPods#7105]
error message "Initializer for conditional binding must have Optional type, not 'CGFont'"
how can i fix this error. thank you.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by pprevalon** [comment]
This error is coming straight from the pod. This is not my code.
