### ISSUE TITLE
No email received for pod trunk register

### ISSUE THREAD

**Issue by batkov** [CocoaPods/CocoaPods#7107]
Hi, 
haven't received any mail after 

```
pod trunk register batkov@i.ua 'some' --description='macmini'
```

Looks same as:
https://github.com/CocoaPods/CocoaPods/issues/6960

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
pod trunk register batkov@i.ua 'some' --description='macmini'

## What did you expect to happen?
Get registration email

## What happened instead?
no mail

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.9.2
Ruby lib dir : /Users/haryton/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d6d4d93ca0894574c169d16654cd58483ddb08f1
```

### Installation Source

```
Executable Path: /Users/haryton/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
Just pod Trunk, not related to some project

**Comment by orta** [comment]
Your mail host's IP is on a blacklist. I've triedto unblock it from our side, so it might work on the next try

![screen shot 2017-10-06 at 10 20 49 am](https://user-images.githubusercontent.com/49038/31282276-15febaa4-aa80-11e7-88d5-39c83c366f77.png)

**Comment by batkov** [comment]
Tried on two different devices. Still no email.
Will wait for a while, but not sure they will arrive.

**Comment by dnkoutso** [comment]
This should also be filed under https://github.com/CocoaPods/cocoapods-trunk repo.

Closing it may have already been fixed here.

**Comment by batkov** [comment]
No fixed, but added issue there
https://github.com/CocoaPods/cocoapods-trunk/issues/100
