### ISSUE TITLE
pod lib lint fails with module in Swift 4 and dependencies in Swift 3

### ISSUE THREAD

**Issue by adamszeremeta** [CocoaPods/CocoaPods#7115]
# Report

## What did you do?

pod lib lint --verbose

## What did you expect to happen?

validation should pass

## What happened instead?

ModuleName did not pass validation, due to n errors.

## CocoaPods Environment

Tested on 1.3.1 and 1.4 beta1

I have private pod library with dependencies to private and public libraries. All dependencies are in Swift 3 and all of them have .swift-version file with content 3.0. My module is written in Swift 4 and have .swift-version file with 4.0 inside.

I would expect that xcodebuild run when lint is done should have dependencies compiled with Swift 3 (not 4 like my module)

**Comment by dnkoutso** [comment]
Closing as part of https://github.com/CocoaPods/CocoaPods/issues/6791

**Comment by ShaneQi** [comment]
@dnkoutso 
I don't think this issue has been solved by 1.4.0.

When it comes to `pod lib lint`, only one swift version can be used for both my lib and dependencies. Didn't find a way to make `pod lib lint` use 4.1 for my lib and 3.3 for dependencies.

**Comment by dnkoutso** [comment]
@ShaneQi you cannot set the Swift version for dependencies. That is intentional. The pod author must set this up.

If the author has not set a `s.swift_version` then the one from your podspec is being used as there is no way for CocoaPods to guess which Swift version to use for your dependencies.

**Comment by ShaneQi** [comment]
I agreed that CocoaPods shouldn't guess which Swift version to user for dependencies, but there isn't a way to explicitly tell it.

I understand that authors of dependencies can use `s.swift_version`, but most libraries haven't adopted it. And old versions that are already pushed to trunk are probably won't ever be updated to adopt it.

This leads to a awkward situation that: my lib will need to use a Swift version that all my dependencies can be compiled with.

I'm DOWNGRADING my lib from 4.1 to 3.3, because of this awkward situation, and I hated it.

**Comment by dnkoutso** [comment]
@ShaneQi understood. I think this will become very complicated to set it up on the Validator (the thing that drives the `lint` command). It will require to make the command line invocation very complex.

More importantly, if we did offer a way for you to customize this and you manage to publish your pod by overriding the Swift version of your dependencies, it will also mean that the *consumer* of your pod apply the same change in their `Podfile`. This can go quickly get out of hand if let's say another pod is using the same dependency as you but expects it to be in Swift 3.1 in order for it to work. There will be no way for the consumer to reconcile this.

I am sorry, but I cannot see any easy way for us to do this, it's best to contact the authors to update their podspecs and explicitly set version of they support.

**Comment by dnkoutso** [comment]
@ShaneQi my pleasure! I love discussing this stuff and explaining certain decisions made in the library. Please keep bringing that stuff up!

**Comment by talezion** [comment]
@dnkoutso  I am facing the same issue and unfortunately downgrading is not an option. 

- My pod is now Swift 4.2
- A dependency is still in Swift 4.0 with no forecast when they will add support for Swift 4.2

If the swift_version must be set by the user, can we bypass that error for lint to pass validation? There is no way to publish dependencies with different Swift versions, which seems obsolete, now that Apple supports more than one versions. Would be great to have some kind of parameter we can pass to override such cases. 

`--ignore-dependencies-validation`

**Comment by ShaneQi** [comment]
@talezion  I don't think such parameter would help. Because the problem during publishing isn't a validation error, it's a compiling error.
