### ISSUE TITLE
Using static framework gives error

### ISSUE THREAD

**Issue by mukeshthawani** [CocoaPods/CocoaPods#7117]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Created a pod that has static_framework=true and added dependencies

## What did you expect to happen?

To build successfully

## What happened instead?

Getting error
![screen shot 2017-10-10 at 9 41 11 am](https://user-images.githubusercontent.com/5956714/31369373-9af0880e-ada1-11e7-8b6c-241de79ebe44.png)

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c9ae2b83739d682b3957c23f56e683d3f19a0053
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-playgrounds  : 1.2.2
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.3.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

## Project that demonstrates the issue

https://github.com/mukeshthawani/TestStaticFramework

**Comment by mukeshthawani** [comment]
@paulb777 Please check this issue

**Comment by paulb777** [comment]
Looks like fix is to 

- Make sure `Kingfisher` in the Target Dependency Build Phase for `TestStaticFramework`
- Add TestStaticFramework/Example/Pods/GoogleMaps/Maps/Frameworks  to the Framework Search Paths
- Add TestStaticFramework/Example/Pods/GoogleMaps/Base/Frameworks to the Framework Search Paths

**Comment by vauxhall** [comment]
I think I found a solution, at least it works for me.
Add the bridging header for your pod, you can do it manually on the Pod Target generated on your project, or you can add it on the podspec.

Something like this:

```
.
.
.
  s.static_framework = true
  s.dependency 'Firebase'
  s.pod_target_xcconfig = {

"ENABLE_BITCODE" => 'NO',
"OTHER_LDFLAGS" => '$(inherited) -framework "KudanAR"',
"SWIFT_OBJC_BRIDGING_HEADER" => '${PODS_ROOT}/SuggesticGo/suggesticgo/Sources/BridgingHeader.h'
}
```

Hope this helps someone else.
