### ISSUE TITLE
Pod Spec Lint not finishing Xcode 9

### ISSUE THREAD

**Issue by AfrozZaheer** [CocoaPods/CocoaPods#7119]
# Report

## What did you do?

pod spec lint

## What did you expect to happen?

What I expect is to complete and give me some errors of success 

## What happened instead?

Pod spec lint is running from almost 24 hours and not finishing 

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : JetsRewards - https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git @ 0ec0d34e8ba7a7d69885c2b8e7a4f0cafc722be5
               jetsrewardspod - https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git @ 0ec0d34e8ba7a7d69885c2b8e7a4f0cafc722be5
               lightningkite - https://github.com/Lightningkite/LKPodspec.git @ ee2fee0fdf27732bfa2d4b105c449dfc3698d124
               master - https://github.com/CocoaPods/Specs.git @ 7dd014f4a3f385c9ecb351fb580b8f134dfb94bb
               PrivatePod - https://AfrozNXB@bitbucket.org/AfrozNXB/privatepodtest.git @ 74c9285203952bba4b9cf8304a5cc1f6012919aa
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Pod Spec on which runing 
```

Pod::Spec.new do |s|

s.name = "JetsRewards"
s.version = "0.1.0"
s.summary = "JetsRewards POD to integrate in jets app"

s.description = <<-DESC
POD to integrate jet reward to integrate to any jets app blah blah blah blah
DESC

s.homepage = "https://bitbucket.org/AfrozMuhammad/jetsrewardspod/overview?init=true"

s.license = { :type => 'MIT', :file => 'LICENSE' }

s.author = { "AfrozZ" => "afrozezaheer@gmail.com" }

s.source = { :git => "https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git" }

s.platform = :ios, "9.0"

s.source_files = 'Pod//*.{swift,xcassets,h,m}'
s.resource_bundles = {
'JetsRewardsElements' => ['Pod//*.{storyboard,xib,xcassets,otf}']
}

s.dependency "Alamofire"
s.dependency "FAParser"
s.dependency "Shimmer"
s.dependency "JTProgressHUD"
s.dependency "PagingView"
s.dependency "Hero"
s.dependency "SDWebImage"
s.dependency "IQKeyboardManagerSwift"
s.dependency "FormTextField"
s.dependency "CryptoSwift"

end
```
After running pod spec lint --verbose I found out that it stuck at 

xcodebuild clean build -workspace /var/folders/gy/cbwttyb17f1gsbvkgl623k5m0000gp/T/CocoaPods-Lint-20171010-1614-x2n1xd-JetsRewards/App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=B3531727-9C0B-40D3-87A1-1EA68962F99E

**Comment by dnkoutso** [comment]
I cant reproduce 

```
[!] Error installing JetsRewards
 -> JetsRewards (0.1.0)
    - WARN  | source: Git sources should specify a tag.
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/local/bin/git clone https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git /var/folders/40/mxlx0vqn29vcg5g3vl7n5w7000015m/T/d20171009-13861-1pva0ec --template= --single-branch --depth 1

Cloning into '/var/folders/40/mxlx0vqn29vcg5g3vl7n5w7000015m/T/d20171009-13861-1pva0ec'...
remote: Empty password
fatal: Authentication failed for 'https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git/'
```

@AfrozZaheer please do not open a new issue for each iteration of your problem.

It remains that this is not a cocoapods library issue.

**Comment by AfrozZaheer** [comment]
Hi dnkoutso 

It's an private pod thats why you are unable to install.. I'm having issue regarding pod spec lint. and it stuck at xcode build can you help me there... 
it seems cocoa pod is not working correctly with xocde 9 and swift 3.2... can you please give me some direction to solve my problem. it will be great.

**Comment by dnkoutso** [comment]
@AfrozZaheer as I said in the other issue, `pod spec lint --verbose --no-clean` and open the generated `.xcodeproj` to inspect and build the project manually.

**Comment by AfrozZaheer** [comment]
Sorry to bother you but I can't find .xcodeproj after pod spec lint --verbose --no-clean.
P.S. it stuck at pod spec lint --verbose --no-cleanat same psition xcode build.

**Comment by justinseanmartin** [comment]
The path to the xcworkspace is outputted on the command line from pod spec lint. It'll be a different tmp folder for each `pod spec lint` invocation. From the command line output above, that instance would have been placed at:

/var/folders/gy/cbwttyb17f1gsbvkgl623k5m0000gp/T/CocoaPods-Lint-20171010-1614-x2n1xd-JetsRewards/App.xcworkspace

The `--no-clean` option instructs CocoaPods to not delete the tmp folder after the operation completes.

You could try directly rerunning the xcodebuild command (instead of it being invoked via cocoapods) and see where/how it is getting stuck. You may want to look at `htop` or `pstree` to find out what the xcodebuild process and its children are doing. You could also run `sample` to figure out what the stack traces within the xcodebuild process itself look like if it is really wedged.

The xcodebuild output is being captured by CocoaPods, which is why you aren't seeing any output via the `pod spec lint` command (see #7064 for more info).
