### ISSUE TITLE
linker errors from using -ObjC

### ISSUE THREAD

**Issue by deanmao** [CocoaPods/CocoaPods#712]
I noticed that CocoaPods will auto inject `-ObjC` into the linker flags for your project.  This flag causes all symbols to be loaded and may cause errors with other existing frameworks that may not like this flag.  The fix would simply be to use a more "targeted" flag as described in Apple's QA 1490: http://developer.apple.com/library/mac/#qa/qa1490/_index.html

Basically, the fix would be to use something like this as the linker flag instead:  `-force_load $(TARGET_BUILD_DIR)/libPods.a`

This would have the same desired effect as `-ObjC` without any of the undesirable side effects.

**Comment by MattHillebrandHTC** [comment]
I'm sorry, but why was this issue closed? It's affecting me severely, even with the latest CocoaPods v0.37.1.

I've got some C++ libraries that simply don't jive with the -ObjC linker flag.

**Comment by segiddins** [comment]
@MattHillebrandHTC please open up a new issue that includes a sample project?

**Comment by MattHillebrandHTC** [comment]
It's the same issue... I also don't think my company would like me posting their C++ libraries publicly :)

**Comment by segiddins** [comment]
well without a sample project, we're not going to be able to track this down. Doesn't have to be your company's lib, but we need something we can run to see the problem in order to fix it,

**Comment by MattHillebrandHTC** [comment]
With or without CocoaPods, I can't use the linker flag "-ObjC" in my project. If I use "-force_load <lib>" for each static library individually (like everyone else has been saying in this thread), I can link...but that's only if I don't use CocoaPods. Is there a way for me opt-out of CocoaPods applying "-ObjC"?

**Comment by neonichu** [comment]
I would have recommended using frameworks to integrate, but apparently we are still supplying `-ObjC` there, I think that is definitely superfluous. I have created #3537 to change that.

**Comment by MattHillebrandHTC** [comment]
Thank you!

**Comment by aanchalkalani** [comment]
Hi,

We are getting errors even after adding libPods.a in other linker flag,

Targets in Build Settings :-  Other Linker Flags :- Remove -ObjC and add  -force_load $(TARGET_BUILD_DIR)/libPods.a but after adding the above line we are getting below errors :- 

```
ld: file not found: /Users/abc/Library/Developer/Xcode/DerivedData/MyApp-cti.........yl.........ifas/Build/Products/Debug-iphonesimulator/libPods.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

And our `Pods.xcconfig` file is lock we can't able to edit `-ObjC by -force_load $(TARGET_BUILD_DIR)/libPods.a in Pods.xcconfig`

Any help appreciated
