### ISSUE TITLE
Document/Improve Swift language version support

### ISSUE THREAD

**Issue by thomasvl** [CocoaPods/CocoaPods#7121]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

The docs for publishing a pod don't really talk at all about `.swift-version`, but trying to run `lint` or `push` the pod can kick out warnings about it.  But if one trying to find out more about the file, there is no clear info in the official docs.  Even if you use the `--swift-version` command line arg, you still get warnings telling you to create the file, and the warning goes no indication that the command line arg was honored.

If the pod is really for a Swift project, odds are they are going support multiple versions of Swift (since the language is stabilizing and there are `#swift()` conditionals, it is very doable), having the file can make some developers think that version is required.

So better docs about what this file is would help for people who thing this implies something about the pod; likewise, docs in generally acknowledging how Swift versions come into play with pods would be welcomed.

## Project that demonstrates the issue

On https://github.com/apple/swift-protobuf we're support back "one full major version" (so Swift 3.0.1 thru 4 currently).

**Comment by orta** [comment]
We're definitely happy to accept PRs improving the documentation 👍

**Comment by thomasvl** [comment]
> We're definitely happy to accept PRs improving the documentation 👍

I have to admit at the moment, I'm not even clear when the file should/shouldn't be used.  So I'm not sure what to suggest for improvements.  😦

**Comment by dnkoutso** [comment]
@thomasvl at least for starters we can suppress the warning message if `--swift-vesion` was supplied.

**Comment by dnkoutso** [comment]
@thomasvl FWIW we are planning on introducing DSL inside the podspec in which specifies the versions of Swift a pod supports.

I think in the meantime I will probably make a small improvement to close this issue around the redundant warning outputted even if Swift version was set.

**Comment by thomasvl** [comment]
Thanks!
