### ISSUE TITLE
pod push too silent, --verbose too verbose for Travis

### ISSUE THREAD

**Issue by jgongo** [CocoaPods/CocoaPods#7123]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

A `pod push` task in Travis deployment phase gets canceled due to the command not outputting anything for more than ten minutes. Could some output be added to inform of the progress while the tool is working?

## What did you do?

I tried to run `pod push` using `fastlane` in Travis. I include the relevant code snippets:

`.travis.yml`
```
deploy:
  skip_cleanup: true
  provider: script
  script: rvm $TRAVIS_RUBY_VERSION do bundle exec fastlane publish
  on:
    branch: master
```

`fastlane/Fastfile`
```
  lane :publish do
    pod_push(path: 'MyPod.podspec', repo: 'my-repo', allow_warnings: true)
  end
```

## What did you expect to happen?

I expected the job to finish correctly and publish the podscpec to my private specs repository.

## What happened instead?

- If I run the command as shown above, the Travis job gets canceled due to the command not outputting anything for 10 minutes (I guess due to a long `pod lib lint`)
- If I add the `--verbose` flag the job gets canceled due to too much output
- If I try to add `travis_wait` the job errors due to travis-ci/travis-ci#7961

## CocoaPods Environment

Output of `bundle exec pod env | pbcopy` in my local machine, but should be very similar, as I use `rvm` and `bundle`to provide replicability of the toolchain.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /Users/jose.gonzalez/.rbenv/versions/2.4.2/lib
Repositories : marketing-suite - https://github.com/Marketing-Suite/podSpec.git @ 2d77bd9975a85b82e177cebdbce835faa54e674a
               master - https://github.com/CocoaPods/Specs.git @ a3c4eeaf937c027d62b7917f8bc8c6ff8ef2ac30
               rakuten-it-scm-eco-core-ios-specs - https://gitpub.rakuten-it.com/scm/eco/core-ios-specs.git @ f08f8dbfacd867f27b21642b28fe08e390d92451
               wuakitv - git@github.com:wuakitv/ios-specs.git @ f1934885f374966004984a39236729a06dd6b54a
               wuakitv-1 - https://github.com/wuakitv/ios-specs.git @ 41fa8235344cf09fd24cdadf32c604d1386b05f1
```

### Installation Source

```
Executable Path: /Users/jose.gonzalez/Documents/projects/rakuten/ios/ios-commons/vendor/bundle/ruby/2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.3
```

**Comment by amorde** [comment]
This seems related to #7040, there's an open PR for streaming the output of xcodebuild which may fix this

**Comment by mxcl** [comment]
Here was my solution:

```ruby
pod lib lint --fail-fast --verbose | ruby -e 'ARGF.each{ print "." }';
```
