### ISSUE TITLE
Pod trunk remove from private pod repo

### ISSUE THREAD

**Issue by fredybp** [CocoaPods/CocoaPods#7128]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run "pod trunk remove"

## What did you expect to happen?

Be able to point the repo to remove a pod from. 

## What happened instead?

Because the pod I have in my private repo has the same name as a pod in the Master CocoaPods repo it saying I don't have permission to remove it, there is no way I can remove the pod from my private repo.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13 (17A405)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : bitbucket-mosyleios-mosyle-cocoa-pods-specs - https://bitbucket.org/mosyleios/mosyle-cocoa-pods-specs @ dee6fca9a73074db57633ef10de70edd9280a02a
               bitbucket-mosyleios-simplepingpod - https://bitbucket.org/mosyleios/simplepingpod @ e5be5ebe245f6a0f05b8e7af37ad56685010b7fd
               master - https://github.com/CocoaPods/Specs.git @ e8d0c2acdb67babbfb1f273f10526866efae4b7f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Do not use `trunk` for private repo commands.

Your private repo is located in `~/.cocoapods/repos/<your_private_repo>`. This is a normal git repo in which you have control of (hopefully). Make a pull request to your private repo to remove the podspec from it.

**Comment by fredybp** [comment]
Ok, thank you very much!
