### ISSUE TITLE
pod lib lint validation error with swift 4 dependency 

### ISSUE THREAD

**Issue by talezion** [CocoaPods/CocoaPods#7144]
# Report

## What did you do?

Run `pod lib lint STWSocialKit.podspec --private --allow-warnings` 

## What did you expect to happen?

Pass validation

## What happened instead?

Error:

```
- ERROR | [iOS] xcodebuild:  OAuthSwift/Sources/OAuthSwiftHTTPRequest.swift:239:42: error: 'filter' is unavailable 
- NOTE  | [iOS] xcodebuild:  Swift.Dictionary:390:17: note: 'filter' was introduced in Swift 4.0
```

>Note: OAuthSwift is added as a dependency `s.dependency 'OAuthSwift', '~> 1.2.0'` Swift 4.0 version. 

Xcode build is successful, OAuthSwift .swift-version is 4.0 

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : Cocoa_Pods_Specs - https://github.com/stanwood/Cocoa_Pods_Specs.git @ c62d71c578f7e1c246b22d3f6cc4fe56d9116195
               master - https://github.com/CocoaPods/Specs.git @ 30d4da841237802f6ef30ee2037e1e0fe78080ae
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

The pod is under a private repository

**Comment by dnkoutso** [comment]
This should be fixed by https://github.com/CocoaPods/CocoaPods/issues/7134 once its completed.

In the meantime, it would be hard for us to debug this without a sample project.
