### ISSUE TITLE
Check Pods Manifest takes long time

### ISSUE THREAD

**Issue by dorsegal** [CocoaPods/CocoaPods#7145]
Hi,
Can someone please help me figure out why 'Check Pods Manifest' its taking 3 minutes?
This happens during archive process
[11:36:46]: ▸ Running script '[CP] Check Pods Manifest.lock'
[11:39:02]: ▸ ⚠️  /Users/jenkins/Library/Developer/Xcode/DerivedData/testapp-anojkfdvwfclipastszqzvcrmwet/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/DevRelease-

Im using Xcode 9 with CocoaPods 1.3.1

**Comment by dnkoutso** [comment]
@dorsegal strange. This script is meant to perform a `diff` only.

However, please provide a sample project that demonstrates the issue. It is downright impossible for us to debug your issue with the given report.

Going to close this and please comment here with a sample project so I can re-open it.

**Comment by dorsegal** [comment]
I cannot post our code here. any logs I can get you?

**Comment by DanToml** [comment]
@dorsegal It looks like you're using xcpretty, can you check your raw xcodebuild log? Usually this is `codesign` doing something but not being printed by xcpretty
