### ISSUE TITLE
32 bit Pod symbols included in iOS 11 archive

### ISSUE THREAD

**Issue by robmaceachern** [CocoaPods/CocoaPods#7148]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Create a new Swift iOS Xcode 9 project (defaults to iOS 11 deployment target) and close it.
2. Run `pod init` in new project directory (using CocoaPods 1.3.1)
3. Open Podfile and add `platform :ios, '11.0'` and add Alamofire pod
4. Run `pod install`
5. Open the .xcworkspace with Xcode and archived my application.
6. Inspect the symbols for each architecture in the archive's dSYMs directory. Result of dwarfdump:
```
Roberts-MacBook-Pro:TooManySymbols rob$ cd /Users/rob/Library/Developer/Xcode/Archives/2017-10-17/TooManySymbols\ 2017-10-17\,\ 11.29\ AM.xcarchive 
Roberts-MacBook-Pro:TooManySymbols 2017-10-17, 11.29 AM.xcarchive rob$ cd dSYMs/
Roberts-MacBook-Pro:dSYMs rob$ dwarfdump --uuid *
UUID: D76374BF-C5DE-3DFB-9DB7-2D9D2FECA971 (armv7) Alamofire.framework.dSYM/Contents/Resources/DWARF/Alamofire
UUID: 0FDB1FC0-50E2-3F98-8616-E36F7103AC79 (arm64) Alamofire.framework.dSYM/Contents/Resources/DWARF/Alamofire
UUID: EC68C4DA-879E-3DB9-8F72-BC97106D1CB8 (arm64) TooManySymbols.app.dSYM/Contents/Resources/DWARF/TooManySymbols
```

## What did you expect to happen?

I expect only arm64 symbols to be included in the archive since 32-bit apps are not available on iOS 11 and Xcode does not build any corresponding 32-bit slice. Submitting this build to iTunes Connect would trigger a warning: `Too many symbol files - These symbols have no corresponding slice in any binary [D76374BF-C5DE-3DFB-9DB7-2D9D2FECA971.symbols]`.

## What happened instead?

armv7 (32-bit) symbols are included for Alamofire

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.12.6 (16G1031)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /Users/rob/.rubies/ruby-2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ dde90d7326c4d83053a8f70a4af16379679ef9de
```

### Installation Source

```
Executable Path: /Users/rob/.gem/ruby/2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/robmaceachern/TooManySymbols

## Workarounds

It's possible to set a post-install hook in the Podfile that sets the `ARCHS` build setting to use only 64 bit architectures.

```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        # Ensure 32 bit symbols aren't included when building
        config.build_settings['ARCHS'] = '$(ARCHS_STANDARD_64_BIT)'
    end
end
```

## Notes

I also tried using CocoaPods master (ba32500) and had the same problem.

Similar to issue #7111

**Comment by dnkoutso** [comment]
@robmaceachern thanks for the report but its already fixed with https://github.com/CocoaPods/CocoaPods/pull/7112.

It has not been released yet with 1.4.0.beta.2 but we are aiming for a release this week.

In the meantime use Bundler http://bundler.io/v1.12/git.html to specify a specific SHA on master to get the latest version without a release.

**Comment by dnkoutso** [comment]
@robmaceachern hm you mentioned you already tried master. I will see what i can repro.

**Comment by dnkoutso** [comment]
Seems like a separate issue from pre-compiled dSYMs that #7112 fixed. This is an issue that generally the architectures chosen for iOS 11 and Xcode 9 should only be set to 64 bit for all pods being built.

**Comment by litchie** [comment]
Still seeing this warning for pod 1.4.0.

**Comment by ZevEisenberg** [comment]
+1 me too. I tried this in my Podfile, but it did not help:

```ruby
installer.project.targets.each do |target|
  target.build_configurations.each do |configuration|
    target.build_settings(configuration.name)['ARCHS'] = 'arm64'
  end
end
```

**Comment by ZevEisenberg** [comment]
Oh, and I'm using the new Xcode 9 build system.

**Comment by ZevEisenberg** [comment]
Updated update: I had bitcode disabled, and re-enabling it fixed it! @litchie you might want to check for that.
