### ISSUE TITLE
`pod trunk push` errors remain after they were fixed and retagged

### ISSUE THREAD

**Issue by jhurray** [CocoaPods/CocoaPods#7150]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I am attempting to push a new major version of a Pod. I ran 

`pod trunk push SelectableTextView.podspec`

 and got some errors. Output:

`[!] The spec did not pass validation, due to 21 errors and 2 warnings.`

I fixed the errors and ran `pod lib lint` which succeeds.

I pushed the changes and updated the tag. After running `pod trunk push` again I still see all the same errors even though I fixed them.

## What did you expect to happen?

I expected the errors to go away once I fixed them.

## What happened instead?

The errors are still there

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1c373ace4a4a553f7ea36b7a0208b37b5a0691e5
               yahoo-iris-pod-specs - git@git.corp.yahoo.com:iris/iris-pod-specs.git @ b3051b46cff1be5cc95dd2ea280d794494411bc7
               yahoo-pod-specs - git@git.corp.yahoo.com:ymobilelibs/pod-specs.git @ 1e905c974cd39e06459fde622de451fb84dab8e3
               yahoo-spbracket - git@git.corp.yahoo.com:sportacular-ios/SPBracket.git @ 8c5acd41f03e8919f987d12b01b00bb5d1ec2c88
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/jhurray/SelectableTextView/tree/1.0.0

**Comment by orta** [comment]
You probably didn't update the external tag, so you're getting the same results when it clones your repo.

**Comment by jhurray** [comment]
Thanks for the quick response @orta. What do you mean by the `external tag`? I updated the local and remote tags after making/pushing the necessary changes and before running `pod trunk push`

**Comment by dnkoutso** [comment]
@jhurray maybe `pod cache clean SelectableTextView`?

**Comment by jhurray** [comment]
I'll try that out, thanks @dnkoutso. FWIW I deleted the derived data referenced in the `xcodebuild` errors and that didnt help
