### ISSUE TITLE
1.4.0.beta.1 is failing to validate with lint.rb:85:in `block in run'

### ISSUE THREAD

**Issue by nmdias** [CocoaPods/CocoaPods#7156]
# Report

## What did you do?
I merged a [PR](https://github.com/nmdias/FeedKit/commit/870b6ecb8088d2c498270fa2fab420b686ac760c) that triggered travis to run: 

```sh
gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
```
Then, perform a bunch of builds and tests, and finally call:

```sh
pod lib lint
```

## What did you expect to happen?
The Pod successfully pass validation by outputting:

```sh
FeedKit passed validation.
```

## What happened instead?

Initially, this:

```sh
 -> FeedKit (7.0.0)
 - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
[!] FeedKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
The command "if [ $POD_LINT == "YES" ]; then pod lib lint; fi" exited with 1.
Done. Your build exited with 1.
```

Afterwards, I updated [travis.yml](https://github.com/nmdias/FeedKit/commit/69f71c5fc654203b09ac0aede1677d17f28523ee#diff-354f30a63fb0907d4ad57269548329e3) to call `pod lib lint` in verbose mode:

```sh
 pod lib lint --verbose
```

The output then changed to:

```swift
 Testing with xcodebuild.
 -> FeedKit (7.0.0)
 - ERROR | xcodebuild: Returned an unsuccessful exit code.
[!] FeedKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command/lib/lint.rb:85:in `block in run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command/lib/lint.rb:54:in `each'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command/lib/lint.rb:54:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/travis/.rvm/gems/ruby-2.4.2/gems/cocoapods-1.4.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/pod:23:in `load'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/pod:23:in `<main>'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
/Users/travis/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

### Travis output

The complete failing `--verbose` output can be seen in the travis [job](https://travis-ci.org/nmdias/FeedKit/jobs/290894040) (at the very end of the logs)

### Resolving the Issue by falling back to a stable version

I was able to fix the issue, by removing the `--pre` parameter from the CocoaPods installation, like this:

```sh
gem install cocoapods --no-rdoc --no-ri --no-document --quiet
```
Then it successfully passes validation:

```sh
 Testing with xcodebuild.
 -> FeedKit (7.0.0)
FeedKit passed validation.
```

This is happening, from my understanding, in the [1.4.0.beta.1](https://github.com/CocoaPods/CocoaPods/releases/tag/1.4.0.beta.1) pre-release, but not in the stable [1.3.1](https://github.com/CocoaPods/CocoaPods/releases/tag/1.3.1) release.

Thank you

### edit

Trying to dig further I noticed that another framework [Alamofire](https://github.com/Alamofire/Alamofire), with an identical travis [yml](https://github.com/Alamofire/Alamofire/blob/master/.travis.yml) file is **successfully** llinting with the same ruby version `2.4.2` as me and using the [1.4.0.beta.1](https://github.com/CocoaPods/CocoaPods/releases/tag/1.4.0.beta.1) pre-release.

**Comment by dnkoutso** [comment]
I think the issue from the log is:
```
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
```

Which has been fixed by https://github.com/CocoaPods/CocoaPods/pull/7131 and has not been released yet.

Can you please try using latest master to confirm this is the case? You can use Bundler to achieve this and find more info here. http://bundler.io/v1.12/git.html

**Comment by dnkoutso** [comment]
I am going to close this, please re-open if you can provide more info.
