### ISSUE TITLE
Can't archive with static_framework

### ISSUE THREAD

**Issue by yimingtang** [CocoaPods/CocoaPods#7158]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I installed the master branch of CocoaPods (revision: 6efbda55fcd72cd2e7da9463527cc1593e00c5e3) and https://github.com/CocoaPods/Core/commit/3efa5e2f0dec56af6fdcfd98822156b65c888ef5 with [bundler](http://bundler.io).

I tweaked the following pod to support `static_framework`.

* [iException/BXSocialAuth](https://github.com/iException/BXSocialAuth/tree/static-framework)

Then I turned on the `use_frameworks!` option in my app's Podfile.

1. `pod install`
2. Product -> Archive with Xcode 9

## What did you expect to happen?

Xcode should archive the app without any error.

## What happened instead?

It failed while archiving. Xcode showed error messages:

![screen shot 2017-10-23 at 2 19 44 pm](https://user-images.githubusercontent.com/529212/31874714-4780729a-b7fd-11e7-864b-6d743e9adfad.png)

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.10
        Host : Mac OS X 10.13 (17A405)
       Xcode : 9.0.1 (9A1004)
         Git : git version 2.14.0
Ruby lib dir : /Users/yiming/.rvm/rubies/ruby-2.3.3/lib
Repositories : 
               cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ 770f7975a69eaf70a8f1009166fdb54231592dd4
```

### Installation Source

```
Executable Path: /Users/yiming/.rvm/gems/ruby-2.3.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'BXSocialAuth_Example' do
  pod 'BXSocialAuth', :path => '../'
end

target 'BXSocialAuth_Tests' do
  # pod 'BXSocialAuth', :path => '../'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
```

## Project that demonstrates the issue

https://github.com/iException/BXSocialAuth/tree/static-framework

**Comment by yimingtang** [comment]
@paulb777 I'm sorry for disturbing you, Paul. You're an expert on `static_framework`, so if you have time, please take a look at this issue. Thank you in advance.

**Comment by paulb777** [comment]
@yimingtang Thanks for raising the issue and providing the example. I've reproduced it and will work on a fix this week.
