### ISSUE TITLE
curl(28) timed out 

### ISSUE THREAD

**Issue by sz-ashik440** [CocoaPods/CocoaPods#7160]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I am trying to add GoogleMaps pod into my project.

## What did you expect to happen?
Pod should be downloaded.

## What happened instead?
When I try to `pod install` it throws curl(28) operation timed out error.
![image](https://user-images.githubusercontent.com/9111027/31890967-c5820662-b826-11e7-9ed8-38cfebaa925c.png)

## CocoaPods Environment
```
CocoaPods : 1.3.1
Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
RubyGems : 2.0.14.1
Host : Mac OS X 10.12.6 (16G29)
Xcode :  8.3.3
Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git@312b3b75eb4832220c35e166722bd150f3dff9a4
```
Podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'

target 'Boatlah' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Boatlah
  pod 'EZSwiftExtensions'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'Kingfisher', '~> 3.13.1'
  pod 'GoogleMaps', '~> 2.3.1'
  pod 'XLPagerTabStrip', '~> 8.0'
  pod "TSMessages"

  target 'BoatlahTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoatlahUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

**Comment by dnkoutso** [comment]
This seems more of an issue with your network configuration. It works for me here.

Going to close as a non-library issue. Try to`curl` manually on your command line and see if that works.
