### ISSUE TITLE
iTunes connect invalid bundle: Ensure that app executables and bundled frameworks use consistent architectures

### ISSUE THREAD

**Issue by sumeshd** [CocoaPods/CocoaPods#7161]
# Report

## What did you do?

Run `pod install` after mentioning several frameworks to install Podfile. All dependencies run great on debug mode. 
Then before release, we changed the pod architecture to iOS 11, arm64, signing to automatic and selected our team (similar to our core project file).
Archived the project and then submitted it to iTunes connect. 

## What did you expect to happen?

The submission to be accepted after processing on iTunes connect

## What happened instead?
I received this message in my email:
Invalid bundle: Ensure that app executables and bundled frameworks use consistent architectures.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13 (17A405)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!
target 'te' do

  	pod 'RecordButton'
  	pod 'FSPagerView'
 
end

target 'te MessagesExtension' do

  	pod 'RecordButton'
  	pod 'FSPagerView'
 

end
```
## Project that demonstrates the issue

Sample project: https://we.tl/A9ja03mDur

**Comment by dnkoutso** [comment]
Please provide a sample project that makes it easy to demonstrate the issue.

**Comment by sumeshd** [comment]
I have an iMessage app that includes a few Pods Framework. I have already ensured all the frameworks while uploading through the Application loader has consistent architecture: ie arm64 and tried resubmitting again. All process' get executed but after submission to the iTunes connect and a few minutes of processing, I get the above error in my email.
We have also additionally tried these:

1. One build: running sh script in build phases to make sure architecture is consistent.
2. Another build: with even the app executable in arm64 (though this is not needed, empty iMessage template test builds with app executable in arm7, arm7s, arm64 has been submitted and accepted). So I can safely assume that it is the addition of Pods that is causing the trouble. 
3. Making sure that all targets have arm64 in their info, including pods targets.
4. I have also tried combinations removing and keeping framework, to check if it is a particular framework that is causing the issue, turns out that is not the case.
5. Making sure all frameworks are in arm64, through the summary presented in application loader
6. Unchecking from archive submission of Bitcode and 'upload your apps symbols to receive Sybolicated reports from Apple'

None of the above solutions work, no matter what I do.

Please help.

Sample project: https://we.tl/A9ja03mDur

**Comment by sumeshd** [comment]
I am hard pressed on release, please help by today.

**Comment by sumeshd** [comment]
@dnkoutso @benasher44  Please help

**Comment by cyu** [comment]
I too was getting this error and tried many things.  The last thing I tried was to go through every target in the pods project and make sure the deployment target is set to 11.0 as well.  And for good measure, make sure it's set to 11.0 in the Pods project as well.

**Comment by sumeshd** [comment]
@cyu I did try that too but there is a dynamic library that in is the project. I am able to get it passed the processing stage without the dynamic library but the moment I include the dylib, this error reoccurs on submission.

**Comment by kyleweiner** [comment]
I have this issue with my iMessage app. However, uploading the same code with an iOS 10 deployment target is successful. Simply using an iOS 11 deployment target is where the problem starts. As far as I can tell, the pods used are not the issue—I tried a few different pods in separate builds as a sanity check. Uploading a build with the generated workspace and no pods was also not an issue.

The sample project above appears to have been removed, but this issue is very easy to reproduce. Just use the template iMessage App project in Xcode 9+, add a pod and upload a build. After the build is done processing, you’ll receive an email from iTunes Connect that states: 

> Invalid Bundle - Ensure that app executables and bundled frameworks use consistent architectures.

I’m using CocoaPods 1.3.1 and Xcode 9.1. I’ve tried CocoaPods 1.4.0.beta.2 too.

**Comment by ardalahmet** [comment]
@cyu's suggestion worked for me.
I wrote a `post_install` script to automate the process.
Since it only affects iTunes builds, I only set the deployment target for non-Debug schemes' build settings.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name != 'Debug'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
```

**Comment by kyleweiner** [comment]
Seems I was a bit hasty in my testing. @cyu's solution is working for me. Thanks for the `post_install` hook, @ardalahmet.
