### ISSUE TITLE
incorrect path for a framework in a multi-platform project

### ISSUE THREAD

**Issue by mackuba** [CocoaPods/CocoaPods#7162]
Reopening #6817 - reproduced on Xcode 9.1 beta 2 and CocoaPods 1.3.1.

---

# Report

## What did you do?

I have a multi-platform project: it was first created as an iOS app, but then a Mac app target was added too. The Podfile specifies some pods to be included on both platforms.

When I run `pod install`, CocoaPods sets up the Pods project and integrates it with the main one, adding a bunch of `.framework` entries. However, after I build both versions of the app, I can see that one of the `.framework` entries is still shown in red. After examining its path, I can see that it's referencing a pods framework for the Mac app in the iOS build folder.

In the `Pods` project under `Products` I can see two `.framework` entries:

- `Pods_FooApp.framework` -> `Build/Products/Debug-iphoneos/Pods_FooApp.framework` (iOS build folder)
- `Pods_FooAppMac.framework` -> `Build/Products/Debug/Pods_FooAppMac.framework` (Mac build folder)

However, in the `FooApp` project under `Frameworks` I can see the same two entries repeated again, but one of them seems to have an incorrect path:

- `Pods_FooApp.framework` -> `Build/Products/Debug-iphoneos/Pods_FooApp.framework` (iOS build folder)
- `Pods_FooAppMac.framework` -> `Build/Products/Debug-iphoneos/Pods_FooAppMac.framework` (iOS build folder again!)

And the last one is shown in red, since the Mac framework obviously doesn't exist in the iOS build folder even after I build both apps.

Am I doing something wrong with the Podfile, or am I setting up the Xcode project incorrectly, or is this some kind of bug?

## What did you expect to happen?

After I build both the iOS and the Mac app, I would expect all product and intermediate files to exist and be shown in black in the file inspector.

## What happened instead?

One of the files is shown in red in the file inspector, since it doesn't exist at the path the entry is linking to.

<img width="260" alt="screen shot 2017-06-19 at 01 39 58" src="https://user-images.githubusercontent.com/28465/27265132-449e9f0a-5490-11e7-9570-2252837f75b3.png">

Note: the project can use the pod just fine despite this - it's just about this Xcode file entry that obviously points to a wrong path and is always shown in red (I'm not sure what it's for if everything works fine without it...).

## How to reproduce

1. Create an iOS app.
2. Run `pod init`. Add the first part of the Podfile (the iOS target). Run `pod install`.
3. Close the project and open the xcworkspace.
4. Add a Mac app target.
5. Add the second part of the Podfile (the Mac target). Run `pod install` again.
6. Build both targets (iOS for generic device and the Mac app).

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.7.3
Ruby lib dir : /Users/psionides/.rvm/rubies/ruby-2.3.0/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ b17a5505814a13b1bb8d4d1b6fae56acfe6318f6
               master - https://github.com/CocoaPods/Specs.git @ 6e15bfd46cad79c435e402fc5a49c76e84cb6126
```

### Installation Source

```
Executable Path: /Users/psionides/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-check       : 1.0.0
cocoapods-deintegrate : 1.0.1
cocoapods-keys        : 1.6.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'Foofoo' do
  platform :ios, '10.0'
  use_frameworks!

  pod 'CocoaLumberjack'
end

target 'FoofooMac' do
  platform :osx, '10.12'
  use_frameworks!

  pod 'CocoaLumberjack'
end
```

## Project that demonstrates the issue

https://www.dropbox.com/s/ia3nkwlfruz78fj/FooApp.zip?dl=0

**Comment by paulb777** [comment]
`pod deintegrate` before the second `pod install` may be a workaround
