### ISSUE TITLE
[iOS] xcodebuild:  xcodebuild: error: Unable to find a destination matching the provided destination specifier:

### ISSUE THREAD

**Issue by truebucha** [CocoaPods/CocoaPods#7167]
# Report

I try to lint this pod
https://github.com/truebucha/CDBKit

## What did you do?

pod lib lint --no-clean

## What did you expect to happen?

succeed lint

## What happened instead?

-> CDBKit (1.2.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: Unable to find a destination matching the provided destination specifier:

Pods workspace available at `/var/folders/jn/hg95mfns0nj41y2mchn7fpnc0000gn/T/CocoaPods-Lint-20171026-909-cmb7gk-CDBKit/App.xcworkspace` for inspection.

[!] CDBKit did not pass validation, due to 1 error.

verbose option shows that build is OK but test on simulator failed.

this is all what log gives 
  - NOTE  | [iOS] xcodebuild:  xcodebuild: error: Unable to find a destination matching the provided destination specifier:

## CocoaPods Environment

I tried xCode 9.0 and xCode 9.1 beta (9B46) 

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13 (17A405)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3dd7c904bf75005d6dbe0047028799cb1f2a4a13
```

### Installation Source

```
Executable Path: ~/Software/ruby/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Please provide a sample project demonstrating the issue. From your log it appears to be a valid `xcodebuild` (compilation) issue and not a cocoapods library issue.

I will re-open this once a sample project clearly demonstrating the problem is attached.

**Comment by truebucha** [comment]
https://github.com/truebucha/CDBKit
Example

**Comment by dnkoutso** [comment]
I spoke a bit soon and apologies. I saw the last entry of the issue as empty. However, the issue still remains that this might be an xcodebuild issue and not a cocoapods library issue.

CocoaPods does not perform compilation of your sources, `xcodebuild` does.

**Comment by truebucha** [comment]
This is not a build issue
this is test phase issue

**Comment by dnkoutso** [comment]
Did you try with `--verbose`? It passed for me. Destination issue seems like a problem with your iOS simulator setup.

**Comment by truebucha** [comment]
`ouch /Users/bucha/Library/Developer/Xcode/DerivedData/App-ftgridlesbqrntegkbjadowkqqkm/Build/Products/Release/App.app
    cd /var/folders/jn/hg95mfns0nj41y2mchn7fpnc0000gn/T/CocoaPods-Lint-20171026-1150-1piq92s-CDBKit
    /usr/bin/touch -c /Users/bucha/Library/Developer/Xcode/DerivedData/App-ftgridlesbqrntegkbjadowkqqkm/Build/Products/Release/App.app

RegisterWithLaunchServices /Users/bucha/Library/Developer/Xcode/DerivedData/App-ftgridlesbqrntegkbjadowkqqkm/Build/Products/Release/App.app
    cd /var/folders/jn/hg95mfns0nj41y2mchn7fpnc0000gn/T/CocoaPods-Lint-20171026-1150-1piq92s-CDBKit
    builtin-lsRegisterURL /Users/bucha/Library/Developer/Xcode/DerivedData/App-ftgridlesbqrntegkbjadowkqqkm/Build/Products/Release/App.app

** BUILD SUCCEEDED **

   Testing with xcodebuild.
 -> CDBKit (1.2.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: Unable to find a destination matching the provided destination specifier:

[!] CDBKit did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

/Users/bucha/Software/ruby/gems/cocoapods-1.3.1/lib/cocoapods/command/lib/lint.rb:85:in `block in run'
/Users/bucha/Software/ruby/gems/cocoapods-1.3.1/lib/cocoapods/command/lib/lint.rb:54:in `each'
/Users/bucha/Software/ruby/gems/cocoapods-1.3.1/lib/cocoapods/command/lib/lint.rb:54:in `run'
/Users/bucha/Software/ruby/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/bucha/Software/ruby/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Users/bucha/Software/ruby/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/Users/bucha/Software/ruby/bin/pod:22:in `load'
/Users/bucha/Software/ruby/bin/pod:22:in `<main>'`

**Comment by dnkoutso** [comment]
`pod lib lint CDBKit.podspec --verbose --allow-warnings`

```
** BUILD SUCCEEDED **

   Testing with xcodebuild. 
 -> CDBKit (1.2.0)
    - WARN  | [OSX] xcodebuild:  /Users/dimitris/Development/ios/CDBKit/Pod/Classes/CDBKit.m:12:33: warning: 'colorWithRed:green:blue:alpha:' is only available on macOS 10.9 or newer [-Wunguarded-availability]
    - NOTE  | [OSX] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:88:1: note: 'colorWithRed:green:blue:alpha:' has been explicitly marked partial here
    - NOTE  | [OSX] xcodebuild:  /Users/dimitris/Development/ios/CDBKit/Pod/Classes/CDBKit.m:12:33: note: enclose 'colorWithRed:green:blue:alpha:' in an @available check to silence this warning

CDBKit passed validation.
```

**Comment by dnkoutso** [comment]
Something is wrong with your local setup, most likely around iOS sim.

**Comment by truebucha** [comment]
So you are right, the issue in Simulators configuration. Where I could find necessary  devices list?

**Comment by dnkoutso** [comment]
Start with `xcrun simctl list`

The rest you can google around :)

**Comment by truebucha** [comment]
Please point me to the right direction.

Do you have iOS 9 simulators on your system?
Do you have xCode beta installed?

**Comment by dnkoutso** [comment]
Xcode 9.0 I do have iOS 8, 9, 10 and 11 sims

**Comment by truebucha** [comment]
Thanks
