### ISSUE TITLE
pod repo update --silent fails to update repos

### ISSUE THREAD

**Issue by jonsorrells** [CocoaPods/CocoaPods#7176]
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

`pod repo update --silent` seems to not correctly fetch from origin.  `pod repo update --verbose` however works fine.
The issue is caused by this commit: https://github.com/CocoaPods/CocoaPods/commit/bf5ae18c1cf18b65e690c7543f1f9604c7e7b9e1 specifically this line `git!(%W(-C #{repo} fetch origin #{show_output ? '--progress' : ''}))`
`git fetch` is getting confused by the empty string passed to it.

## What did you do?

run `bundle exec pod repo update --silent`

## What did you expect to happen?

Update all repos in ~/.cocoapods/repos to the latest master.

## What happened instead?

Repos were not updated.  I'm using a private spec repo, which I had pushed a commit to earlier.  The copy of the repo in ~/.cocoapods/repos was not updated with the latest commit.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13 (17A405)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.9.3
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_2/lib
Repositories : cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ 1a1289d47cc377b5f334741d631eb2451dde1352
               [redacted] - git@github.com:[redacted]/Specs.git @ 66196b0c3eb68cda780c9a133ec6313cb2e6113b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Care to make a PR for this? Seems fairly easy and you've done most of the work!
