### ISSUE TITLE
Copy resources phase doesn't copy resources

### ISSUE THREAD

**Issue by steven-at-truemotion** [CocoaPods/CocoaPods#7184]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

(Detailed description follows the Report section.)

# Report

## What did you do?

Run `pod install`, then build my app.

## What did you expect to happen?

The resources from pods to be included in the app bundle.

## What happened instead?

None of the resources from pods were included in the app bundle.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.9.2
Ruby lib dir : /Users/sclark/.rvm/rubies/ruby-2.4.0/lib
Repositories : censio - git@github.com:Censio/pod-specs.git @ ab25d8f6637d641de3b58d982b6db90916e749d0
               master - https://github.com/CocoaPods/Specs.git @ 9f109f7bca694b552e76acbb429393e34e18dd8e
```

### Installation Source

```
Executable Path: /Users/sclark/.rvm/gems/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```
Also cocoapods-downloader 1.1.3, although I doubt that's relevant.

### Podfile

```ruby
source 'git@github.com:Censio/pod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "9.0"

project 'Sensors.xcodeproj'

pre_install do |installer|
    # The prepare_command is not executed for podspecs
    # using :path. As a workaround we invoke the scripts
    # here.
    system('sh ./CensioKit/scripts/format_revision_string.sh')
end

# These apply to all targets.
pod 'NSDate-Extensions-iOS7', '~> 1.0'
# temp. fix for MP Podspec issue
pod 'MPMessagePack', '1.3.5'
pod 'CensioKit', :path => 'CensioKit/'
pod 'Crashlytics'
project 'Sensors.xcodeproj'

target "PabloApp" do
    # For development you can do something like this:
    #pod 'TMO_Pablo', :path => '../pablo/projects/ios/pods'
    pod 'TMO_Crash', '1.5.1-dev'
    pod 'TMO_PhoneUsage', '1.5.1-dev'
    pod 'TMO_Brake', '1.5.1-dev'
end

target "DistractionApp" do
    # For development you can do something like this:
    #pod 'TMO_Pablo', :path => '../pablo/projects/ios/pods'
    pod 'TMO_Crash', '1.5.1-dev'
    pod 'TMO_PhoneUsage', '1.5.1-dev'
    pod 'TMO_Brake', '1.5.1-dev'
end
```

## Project that demonstrates the issue

Sorry, I do not have anything I can make public at this time.

# Details

This problem does not manifest with CocoaPods 1.2.1.  I am filing the bug right away, as soon as I think I might have enough information for you to go on.  I have a potential solution approach below.  I understand that I might be mistaken.  This issue might be related to #7012.

## Observations

In my app Xcode places unlocalized resources directly in the top level .app directory.  I have no idea why, if this is normal or not.  I expected them to be in xxx.app/Resources, but that's not really the point.

With the addition in CP 1.3 of input and output files associated with the [CP] Copy Pods Resources build phase, Xcode never executes that build phase script.  I believe the PR is #6806.

If, after pod install, I manually remove the input and output files from [CP] Copy Pods Resources, it works perfectly.

The input files list appears to be correctly generated.  There is one output file generated, and it's "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" - which ends up being the xxx.app folder itself.

## Theory

I believe what happens is that before running the phase script, Xcode checks timestamps on the input and output files.  If it finds that the output files exist and are newer than the inputs, it skips the step.  In this case the xxx.app folder always exists and is newer than the pod resource files so the resources are never copied.  This is supported by the test I mentioned in which I removed all the generated input and output files from the build phase.

## Candidate Solution

If my theory is correct, a more robust approach would be to generate one output file for each input file rather than listing only the directory that contains the output files.  All the necessary information must be present in order for CocoaPods to do what it already does:  to generate the input file list and the output directory.  If there are cases in which resources are copied to subdirectories of the UNLOCALIZED_FOLDER_PATH, those cases are known when generating the script that does the copying.

# Closing

Thank you very much.

**Comment by dnkoutso** [comment]
A sample project is the best and fastest way for us to debug this. I think you are correct that the blanket folder for resources may not be enough. Either way, it seems like a clean build is a easy workaround here correct?

**Comment by steven-at-truemotion** [comment]
No, a clean build doesn't work.  I've never under any circumstances seen a build succeed with the generated input and output file lists.

**Comment by steven-at-truemotion** [comment]
The easy workaround is to peg CocoaPods at 1.2.1 in the Gemfile.  I just tried that and it works like a charm.  (Manually removing the added input and output file lists doesn't work very well on a continuous integration server.)  I'll try to throw together a sample project later.

**Comment by justinseanmartin** [comment]
We have resources that get copied without issue despite the same `${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}` output path (runinng 1.4.0.beta.2), so I think it is a more specific issue than just copying resources being generally.

What is your pre_install script attempting to do? I'm just wondering if that is causing some weird interaction with CocoaPods and Xcode and the resources that should be getting copied.

If you only remove only one of either the input or output file lists (rather than both) is that sufficient to get it working? Just trying to narrow down which one is causing the issue.

Can you give an example of what your input file paths looks like? If you add a script phase to `ls -la <path>` on one of the input file paths that isn't being copied, does it exist at the time it is being used as an input path?

As a short term local fix, you could add a post_install step that removes the output paths from the targets, but that'd just be a stopgap solution.

**Comment by dnkoutso** [comment]
> I'm going to put my effort into creating a small example that exhibits the problem, if you think that's reasonable.

this is by far the best way to demonstrate the issue and also help us debug it faster

**Comment by steven-at-truemotion** [comment]
My first attempt to reproduce the problem in a simple example fails to reproduce the problem.  Just FYI.

**Comment by igor-makarov** [comment]
[#7209](https://github.com/CocoaPods/CocoaPods/pull/7209) addresses this 😎

**Comment by dnkoutso** [comment]
@steven-at-truemotion @igor-makarov I am going to close this issue then. Will ship with next 1.4.0 release (beta or RC)
