### ISSUE TITLE
Spaces in a vendored framework path breaks OTHER_LDFLAGS

### ISSUE THREAD

**Issue by lagnat** [CocoaPods/CocoaPods#7185]
# Report
I'm creating and testing a private pod on my local machine.  I've got a vendored framework and a vendored static lib.  The framework has a space in the name and the generated xcconfig OTHER_LDFLAGS gets mangled.  `pod lib lint` also fails.

## What did you do?

In the podspec:
`s.vendored_libraries  = 'build/libcef_dll_wrapper/Debug/libcef_dll_wrapper.a'`
`s.vendored_frameworks = 'Debug/Chromium Embedded Framework.framework'`

NOTE that I tested escaping those spaces with backslashes and that did not help.

In the Podfile:
`pod 'CEF', :path => ".. path to where it is .."`

`$ pod install`

## What did you expect to happen?

`OTHER_LDFLAGS = $(inherited) -ObjC -l"cef_dll_wrapper" -framework "Chromium Embedded Framework"`

## What happened instead?

`OTHER_LDFLAGS = $(inherited) -ObjC Embedded Framework -l"cef_dll_wrapper" -framework "Chromium"`

## CocoaPods Environment

`Tested with 1.4.0 Beta 2, and 1.3.1
High Sierra beta 17B46a`

**Comment by sunuslee** [comment]
@lagnat hello, right now, in Pod 1.2.0
how do u write that podspec?

**Comment by sunuslee** [comment]
this one:
s.vendored_frameworks = 'Debug/Chromium Embedded Framework.framework'
