### ISSUE TITLE
Build configuration(s) in Podfile aren't taking effect

### ISSUE THREAD

**Issue by jaclync** [CocoaPods/CocoaPods#7186]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` where `Podfile` specifies certain a build configuration for a pod (example `Podfile` [here](https://github.com/jaclync/MultipleConfigurationsApp/blob/master/Podfile)) following "Build configurations" section in https://guides.cocoapods.org/syntax/podfile.html#pod

## What did you expect to happen?

Pod is built only for configurations specified in `Podfile`

## What happened instead?

Pod is built for all configurations, including ones not specified in `Podfile`

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.6.10
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.10.0
Ruby lib dir : /opt/rubies/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 04ecea26a6313b060b066ee6a665a2b430584833
               Quizlet - https://github.com/quizlet/CocoaPodsSpecs.git @ 854a57642a36972620394b85314fbffa4d8a0081
               quizlet-1 - https://github.com/quizlet/Specs.git @ ff038ca0bccb0b34b29df0b79dcb0da23713ccdf
               quizlet-2 - https://github.com/quizlet/QuizletNetworkTestHelpers @ 2cac98a3f320d2bfc6ca97954d11b3990476c5cb
               QuizletNetworkTestHelpers - git@github.com:quizlet/QuizletNetworkTestHelpers.git @ 2cac98a3f320d2bfc6ca97954d11b3990476c5cb
```

### Installation Source

```
Executable Path: /opt/boxen/rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MultipleConfigurationsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MultipleConfigurationsApp
  pod 'SimulatorStatusMagic', '2.0', :configuration => 'Test'

  target 'MultipleConfigurationsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

https://github.com/jaclync/MultipleConfigurationsApp

**Comment by dnkoutso** [comment]
@jaclync what you do you mean it's not being built for this configuration? 
![screen shot 2017-10-31 at 11 01 27 am](https://user-images.githubusercontent.com/310370/32240575-e966eb6a-be2a-11e7-9236-9354d0dff1be.png)

**Comment by jaclync** [comment]
@dnkoutso sorry it's probably showing "Test" since I didn't mark the scheme as "shared" (just pushed that change). If you manually change the configuration right there to `Release` or `Debug`, do you see the pod `SimulatorStatusMagic` in your build logs?

**Comment by dnkoutso** [comment]
![screen shot 2017-10-31 at 11 07 55 am](https://user-images.githubusercontent.com/310370/32240879-c810d182-be2b-11e7-9628-9e4588bc2319.png)

Yes

**Comment by dnkoutso** [comment]
Thats with setting the app into `Debug` configuration.

**Comment by dnkoutso** [comment]
@jaclync I am inclined to close. I cannot repro or 100% understand your issue.

**Comment by jaclync** [comment]
the issue is that the `Podfile` specifies the pod (`SimulatorStatusMagic` in this example) should only be built for certain build configurations (`Test` configuration in this example). However as your screenshot showed, the pod is still built for non-`Test` configurations (`Debug`, `Release`). Does this clarify the issue a bit more?

**Comment by dnkoutso** [comment]
@jaclync I see now, hm I do not know why xcode invokes the build or if it can be avoided but I do know that CocoaPods does the right thing and only adds `-framework` into your `Pods-MultipleConfigurationsApp.test.xcconfig` and NOT into `Pods-MultipleConfigurationsApp.debug.xcconfig` or `Pods-MultipleConfigurationsApp.release.xcconfig`.

**Comment by dnkoutso** [comment]
This would be a much larger change to basically create different pod targets per configuration which I do not think it will happen anytime soon. The important bit here is that the pod does not get linked which works as expected.

**Comment by dnkoutso** [comment]
@jaclync I do not think there is even an easy way to accomplish this with Xcode itself anyway unless you create two identical dependency trees for each configuration.

Given that CocoaPods generates the correct xcconfig and the fact that I do not think this will be modelled anytime soon I am going to close.
