### ISSUE TITLE
Whole project recompilation with static frameworks.

### ISSUE THREAD

**Issue by volodg** [CocoaPods/CocoaPods#7187]
I am using ```cocoapods``` gem from ```master``` branch with ```XCode 9``` (last commit: https://github.com/CocoaPods/CocoaPods/commit/4ea4f5aed7fd6f3fbc120e23fc302d16c89f8e2c)

My project contains static swift framework dependence and I think this integrated into target "Setup Static Framework" script:
```
mkdir -p "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.framework/Modules"
cp "${BUILT_PRODUCTS_DIR}/lib${PRODUCT_NAME}.a" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.framework/${PRODUCT_NAME}"
cp "${MODULEMAP_FILE}" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.framework/Modules/module.modulemap"
# If there's a .swiftmodule, copy it into the framework's Modules folder
cp -r "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}".swiftmodule "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.framework/Modules/" 2>/dev/null || :
# If archiving, Headers copy is needed
cp -r "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.framework/Headers" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.framework/" 2>/dev/null || :
cp -r "${TARGET_BUILD_DIR}/${PRODUCT_NAME}.framework/PrivateHeaders" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.framework/" 2>/dev/null || :
```

cause rebuild of the whole project each build time without any source code changes

**Comment by dnkoutso** [comment]
Are you consuming a pod with `s.static_framework = true`? This script only runs for static frameworks

**Comment by volodg** [comment]
Yes, of cause, I am using ```s.static_framework = true```

**Comment by dnkoutso** [comment]
@volodg 👍 the initial issue was referring to static *libraries* thats why I asked.
