### ISSUE TITLE
Podspec - add No_Common_Blocks flag to target

### ISSUE THREAD

**Issue by ItayAmzaleg** [CocoaPods/CocoaPods#7198]
I need to add no common blocks flag to a specific target.
The pod workspace structure contains the App project and the Pods project. inside the Pods project I have 'MyCode' target, Pods-App target, and other dependency targets (AFNetwork etc...).
I need to flag `'GCC_NO_COMMON_BLOCKS' => 'NO'` on 'MyCode' target.
On my pod spec file I tried to use `s.pod_target_xcconfig = { 'GCC_NO_COMMON_BLOCKS' => 'NO' }`, but it add the flag to the App project. When I use `s.user_target_xcconfig = { 'GCC_NO_COMMON_BLOCKS' => 'NO'}` It adds the flag to the App project and the Pods project, But not to any of it's targets.
Do I need to use subspec? when I do I get an error 'undefined method subspec for Pod:Module.'
My subspec definition is:
```
subspec 'MyCode' do |sp|
  sp.pod_target_xcconfig = {
    'GCC_NO_COMMON_BLOCKS' => 'NO'
  }
end
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by ItayAmzaleg** [comment]
will do, tnx.
