### ISSUE TITLE
pod_target_xcconfig GCC_NO_COMMON_BLOCKS ignored

### ISSUE THREAD

**Issue by ItayAmzaleg** [CocoaPods/CocoaPods#7201]
I need to flag 'GCC_NO_COMMON_BLOCKS' => 'NO' on my target.
On my pod spec file I use:

```
s.pod_target_xcconfig = {
        'GCC_PREPROCESSOR_DEFINITIONS' => 'PROJECT_DIR=@\""$PROJECT_DIR"\"',
        'GCC_NO_COMMON_BLOCKS' => 'NO',
        'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES'
    }
```
But only the GCC_PREPROCESSOR_DEFINITIONS and CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES is edited correctly. the GCC_NO_COMMON_BLOCKS flag value remains with the same value.
Is that an issue, or am I doing something wrong?

**Comment by dnkoutso** [comment]
Its because Xcode is setting this automatically for all dynamic framework targets. I do not think there is a lot we can do in this case within CocoaPods.

**Comment by dnkoutso** [comment]
If you create a new dynamic framework target in Xcode without CocoaPods you will see it it sets it to 'YES'

<img width="828" alt="screen_shot_2017-11-06_at_7_18_02_pm" src="https://user-images.githubusercontent.com/310370/32475563-477cd10a-c327-11e7-899a-bd6f27de137b.png">

**Comment by dnkoutso** [comment]
This could potentially be ever solved by new DSL in which we set flags directly to the target instead. I do not think this will happen in the near future though.

**Comment by ItayAmzaleg** [comment]
So nothing I can do when trying convert existing project to pod, but change the project?

**Comment by dnkoutso** [comment]
Unfortunately, no I do not think so. You have to change the project via a `post_install` hook perhaps.

**Comment by dnkoutso** [comment]
@ItayAmzaleg sorry but I do not think there will be support soon for this so I am going to close.
