### ISSUE TITLE
When I use static_framework,Archive project can't find header file

### ISSUE THREAD

**Issue by heroims** [CocoaPods/CocoaPods#7202]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I use `s.static_framework= true` in my project.

## What did you expect to happen?

It archiving failed in Xcode9.but it build success.It can't find header file in project.

## What happened instead?

archiving success

### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.6 (16G1036)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /Users/admin/.rvm/rubies/ruby-2.3.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bab2af7be7383fd6f0cdcbfc1157d94a9ff05329
               YYModel - https://github.com/ibireme/YYModel.git @ 699cc26252f476ed3c7438d47a23b983e7299f2b
```

### Installation Source

```
Executable Path: /Users/admin/.rvm/gems/ruby-2.3.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DEF' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for DEF
  pod 'ABC' ,:path => '../ABC/ABC.podspec'
  target 'DEFUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue
Demo `DEF` 

[PodsTest.zip](https://github.com/CocoaPods/CocoaPods/files/1446017/PodsTest.zip)

**Comment by heroims** [comment]
@paulb777

**Comment by heroims** [comment]
If add Header Search Paths it can Archiving success.It means this repo is static framework but it forgot add Header Search Paths.

**Comment by noppefoxwolf** [comment]
I have same issue. +1

**Comment by noppefoxwolf** [comment]
@heroims What did you added search paths? 
And Which did you added paths to target.

**Comment by dnkoutso** [comment]
Closing as dup of https://github.com/CocoaPods/CocoaPods/issues/7203
