### ISSUE TITLE
Xcode Archive failure.

### ISSUE THREAD

**Issue by noppefoxwolf** [CocoaPods/CocoaPods#7207]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Archive example project of pod with Xcode.

## What did you expect to happen?

Successfully archive.

## What happened instead?

An error occurred on Xcode.

`ld: framework not found BXSocialAuth
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

*But work fine CocoaPods on 6ef370a. *
I happen this issue when cocoapods of 5c0bd2c.

### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /Users/tomoya.hirano/.rbenv/versions/2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b901b19cc1f4a4f428236fdd6cfa290faa03926a
```

### Installation Source

```
Executable Path: /Users/tomoya.hirano/Documents/workspace/lab/BXSocialAuth/Example/vendor/bundle/ruby/2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'BXSocialAuth_Example' do
  pod 'BXSocialAuth', :path => '../'
end

target 'BXSocialAuth_Tests' do
  # pod 'BXSocialAuth', :path => '../'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
```

## Project that demonstrates the issue

It is a demo repository described on #7158.

**Comment by dnkoutso** [comment]
This issue has been fixed in 6ef370ac4c5a19d873fd88375826ac28b0071c72 as you pointed out. There is no need to re-open a new issue. 

It will be released with the next 1.4.0 beta or use bundler (http://bundler.io/v1.12/git.html) to point ot the SHA instead.

**Comment by noppefoxwolf** [comment]
5c0bd2c is newer than 6ef370a.
Is there not a problem?

**Comment by dnkoutso** [comment]
@roxiemobile please open a new issue, fill in the template and *include* a sample project clearly demonstrating the issue.

**Comment by paulb777** [comment]
@roxiemobile @dnkoutso I'm wrapping up for today, but will take a look tomorrow to see if I can reproduce with the original example and a post 4150bb7 CocoaPods.

Thanks for narrowing it down!

**Comment by paulb777** [comment]
Opened #7225.
