### ISSUE TITLE
Vendored frameworks are not included when source is http

### ISSUE THREAD

**Issue by tamastimar** [CocoaPods/CocoaPods#7212]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I'm trying to add a dependency via local podspec: `pod 'SomePod', :podspec => './SomePod.podspec'`

It contains a framework, specified by `vendored_frameworks`, **`source` is `http`**.

## What did you expect to happen?
Add specified framework to the generated Pods project.

## What happened instead?
Specified framework is not added to the generated Pods project.

**However it works well if the `source` is `git`.**

You can reproduce it by changing the source to GitHub artifact url in a local podspec of a pod already available on GitHub.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G1036)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 14cc729f98b8e50b93470306b264ebbbacb66790
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'localspec' do
  pod 'SomePod', :podspec => './SomePod.podspec'
end
```

**Comment by dnkoutso** [comment]
Need a sample project for this

**Comment by tamastimar** [comment]
@dnkoutso here is a sample project: https://github.com/tamastimar/CocoaPods--7212-Sample.

You can see the different behaviour on `git-install` and `http-install` branches.

**Comment by ghugues** [comment]
@tamastimar The path to the framework is different when using `http`. Try adding `ObjectivePGP-0.9.4` to the root of your path in the podspec (e.g. `'ObjectivePGP-0.9.4/Frameworks/ios/ObjectivePGP.framework'`)

**Comment by mattrobmattrob** [comment]
I am having similar issues with a local/development CocoaPod referencing dependencies that use `vendored_frameworks`. I'm having linker errors on some dependencies (that are vendored frameworks) that are remote and local/development.

|Pod|Working|Podspec|Source|
|---|---|---|---|
|Reveal|Yes|https://github.com/CocoaPods/Specs/blob/master/Specs/c/8/7/Reveal-SDK/14/Reveal-SDK.podspec.json|https://download.revealapp.com/RevealServer-14.zip|
|Apptimize|Yes|https://github.com/CocoaPods/Specs/blob/d6ecaef7994afdb033bf93ae2b08f0b7ae3d4c88/Specs/e/1/6/Apptimize/2.18.1/Apptimize.podspec.json|https://sdk.apptimize.com/ios/apptimize-ios-2.18.1.zip
|ZendeskSDK|No|https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/6/5/9/ZendeskSDK/1.7.6.1/ZendeskSDK.podspec.json|https://github.com/zendesk/zendesk_sdk_ios.git|
|FirebasePerformance|No|https://github.com/CocoaPods/Specs/blob/2d2778fb24db7c07bcb9e99796138e8ece784217/Specs/e/5/6/FirebasePerformance/1.0.0/FirebasePerformance.podspec.json|https://dl.google.com/dl/cpdc/1c447a14228a6a29/FirebasePerformance-1.0.0.tar.gz|
|HockeySDK|No|https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/7/4/6/HockeySDK/4.1.2/HockeySDK.podspec.json|https://github.com/bitstadium/HockeySDK-iOS/releases/download/4.1.2/HockeySDK-iOS-4.1.2.zip
|GoogleSignIn|No|https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/d/4/0/GoogleSignIn/4.0.1/GoogleSignIn.podspec.json|https://dl.google.com/dl/cpdc/1e9a99db415f062f/GoogleSignIn-4.0.1.tar.gz|

Initially, I thought it was an issue cause by the source being `git:` vs. `http:` but that doesn't seem to be the case for me given the above table.

```
Target
-- TargetCore
---- Reveal
---- Apptimize
---- ZendeskSDK
---- FirebasePerformance
---- HockeySDK
---- GoogleSignIn
```

Any suggestions or pointing me to what to fix inside CocoaPods would be appreciated.

**Comment by dnkoutso** [comment]
@mattrobmattrob do you have a quick Sample App for this ?
