### ISSUE TITLE
Mixed Swift and Objective C static libraries require bridging header

### ISSUE THREAD

**Issue by piercifani** [CocoaPods/CocoaPods#7213]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
The new Swift static libraries feature available with Xcode 9 and CocoaPods 1.4.0 can be used for targets that mix Objective C and Swift. 

However, for these to be built correctly (Swift must be able to 'see' ObjC code), a Bridging Header must be provided and I can't find any documented feature that enables this.

A workaround can be achieved by using: `s.xcconfig = { 'SWIFT_OBJC_BRIDGING_HEADER' => 'RxCocoa/RxCocoa.h' }` or setting it manually, but it is less than ideal and IMHO it should be promoted to a full podspec specification so the integration is easier.

## What did you do?
Try to use CocoaPods 1.4.0 beta 2 to build a mixed library

## What did you expect to happen?
For the library to compile correctly

## What happened instead?
The compilation failed because the ObjC code wasn't available for the Swift code.

### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.1 (17B48)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories :  master - https://github.com/CocoaPods/Specs.git @ 484789662cfb979e75360a0803919f9939b2912b          
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'RxSample' do
  pod 'RxCocoa', :path => '../RxCocoa.podspec'
  pod 'RxSwift', :path => '../RxSwift.podspec'

  target "RxSampleTests" do
    inherit! :search_paths
      pod 'RxBlocking', :path => '../RxBlocking.podspec'
      pod 'RxTest', :path => '../RxTest.podspec'
  end
end
```

## Project that demonstrates the issue

Please go [here](https://github.com/BlurredSoftware/RxSwift/tree/static-lib) at the `static-lib` branch, `cd` into RxCocoapodsExample and do a pod init

**Comment by piercifani** [comment]
After applying the workaround, the library compiles just fine, but importing it from the app causes another [issue](https://i.imgur.com/naIXOEq.png)

**Comment by paulb777** [comment]
@piercifani Thanks for trying the new feature and the report.  

I don't see enough here to reproduce the issue. Ideally, would you make a minimal project that demonstrates the issue, or at least exact instructions for seeing the problem in the referenced large repo.

#7140 is an example of a minimal fixed issue about access to Swift static frameworks. Perhaps you could extend that example to demonstrate your issue?

**Comment by piercifani** [comment]
Hey @paulb777,  

[here](https://github.com/BlurredSoftware/RxSwift/tree/static-lib) you'll find a RxSwift fork where I've added the `static_framework` attribute. 

Please clone the `static-lib` branch, `cd` into the "RxCocoapodsExample" directory and from there you can do a Pod init. When you try to build the project

This should be enough to reproduce the issue. However, I can try to build a smaller project that exposes this issues without relying on a big project like RxSwift if it's necessary.

Thanks!

**Comment by paulb777** [comment]
@piercifani I might be missing something, but I've never used CocoaPods without a `pod update` or `pod install` to create an .xcworkspace. What is the project you're opening and Xcode scheme that you're building?

**Comment by piercifani** [comment]
Oh yeah... pod install... sorry!

**Comment by paulb777** [comment]
```
pod install
Analyzing dependencies
[!] Unable to find a target named `RxSample`, did find `RxExample-iOS`, `RxExample-OSX`, `RxExample-iOSTests`, `RxExample-iOSUITests`, and `RxExample-macOSUITests`.
```

**Comment by piercifani** [comment]
I believe you're not navigating into the right folder, you're doing `pod install` on the root of that directory and that's why it's finding the `RxExample` from RxSwift instead of the ones I created for this example.

Just copy paste this into the terminal and it should work: 
`git clone git@github.com:BlurredSoftware/RxSwift.git -b static-lib; cd RxSwift/RxCocoapodsExample; pod install; open .`

[This](https://i.imgur.com/8DuWQH6.png) is what you should see.

**Comment by paulb777** [comment]
OK, I may have it now. I was in the RxExample directory instead of RxCocoapodsExample.

I believe I'm reproducing your experience, except I need 

`  s.pod_target_xcconfig = { 'SWIFT_OBJC_BRIDGING_HEADER' => '$(PODS_ROOT)/../../RxCocoa/RxCocoa.h' }`

added to RxCocoa.podspec to do the workaround and build successfully

**Comment by dnkoutso** [comment]
As a sidenote, for podspecs within the `pod_target_xcconfig` DSL its best to use `PODS_TARGET_SRCROOT` which is always relative and works for local and remote linting :)

**Comment by piercifani** [comment]
@paulb777 glad that you could reproduce the issue. 

But keep in mind that even if it compiles after the workaround, if you import that library from the app, you'll see another compile issue like [this one](https://i.imgur.com/naIXOEq.png)

**Comment by piercifani** [comment]
Any news on this?

**Comment by paulb777** [comment]
I'm not likely to get to this in the 1.4 timeframe, but happy to help if anyone else wants to work on a PR.

**Comment by piercifani** [comment]
That's a bummer... Swift static libraries was one of the key features of 1.4 that I was really looking forward. 

I can't help with PRs because I don't know any Ruby, but I can happily provide test scenarios.

**Comment by paulb777** [comment]
Before this summer, I didn't know Ruby, but really wanted some CocoaPods features and fixes :) - but understood - it's a non-trivial learning curve.

My understanding is that this is only an issue for libraries that mix Objective C and Swift. Is a reorganization possible that makes each library mono-language?

While I saw the first issue with the xcconfig workaround, I didn't see the 2nd issue. Is there potentially a workaround for that compile issue?

Test scenarios and feature specifications will definitely help to get the implementation moving.

**Comment by kustra** [comment]
I prepared a small test project to reproduce this issue: https://github.com/kustra/NVMDummyTestPod
`pod lib lint` gives the following error:
```
 -> NVMDummy (2.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] xcodebuild:  /Users/kustra/Development/.../NVMDummyTestPod/NVMDummy/MySWClass.swift:14:14: error: use of unresolved identifier 'NVMMyOCClass'

[!] NVMDummy did not pass validation, due to 2 errors.
You can use the `--no-clean` option to inspect any issue.
```

If I remove [s.static_framework = true](https://github.com/kustra/NVMDummyTestPod/blob/9844e1d5d76c4ae8b1729f670801dd48665a3e52/NVMDummy.podspec#L15) from the podspec, it passes validation.

pod version 1.4.0.rc.1
Xcode version 9.2 (9C40b)

**Comment by dnkoutso** [comment]
Thanks that would help a lot for anyone who wants to fix this issue.

**Comment by paulb777** [comment]
If it's not clear from the discussion, this issue is about managing the bridging header for static framework pods that are a mix of Swift and Objective C.

Any suggestions about how the implementation should work? How should the bridging header be generated/specified?

**Comment by kustra** [comment]
I've only just skimmed the discussion, so I may be off here.
Also, I've never looked at the generated Pods project in detail, but I'm going to assume that it contains framework targets for each dependency.

Isn't a bridging header only applicable for app targets? I thought [you needed to use the umbrella header for framework targets](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html). (Check out the _"To import Objective-C code into Swift from the same framework"_ part.) According to the docs, including a public ObjectiveC header in the umbrella header would make it available to the Swift code in the same framework target.
And this is how it works, even with the default Cocoapods-generated umbrella header, if `s.static_framework` is **not** `true`. See the test project I posted earlier. It passes `pod lib lint` in this case. (Please note that it's using the Cocoapods-generated umbrella header, not the [NVMDummy.h included in the project](https://github.com/kustra/NVMDummyTestPod/blob/master/NVMDummy/NVMDummy.h).)

However, if I set `s.static_framework` to `true` and change nothing else, it produces the error noted above, as the Swift code in the pod doesn't see the ObjectiveC code.
If I do what I assume is the equivalent in the Xcode project, and set `Mach-O Type` to `Static Library` in the build settings, it compiles without errors and produces a static framework from Xcode. (I just pushed a change for the example project that does this.)
Clearly, this works in Xcode regardless of the static/dynamic framework setting. Yet it doesn't work in Cocoapods, which I guess is a bug somewhere in Cocoapods. :smile:

**Comment by paulb777** [comment]
Thanks @kustra!  I understand the issue better now. You're right that it is an umbrella header issue even though a bridging header is a workaround.

At the beginning of a framework build, Xcode creates an intermediate module map that points at the umbrella header in the "Write auxiliary files" phase. That intermediate module map is used in building the Swift files of the framework. CocoaPods doesn't generate the module map until after the framework build.

**Comment by dnkoutso** [comment]
Should we aim for this in 1.5.0?

**Comment by paulb777** [comment]
@dnkoutso Yes - it's at the top of my list.
