### ISSUE TITLE
CLANG_WARN_UNGUARDED_AVAILABILITY warnings

### ISSUE THREAD

**Issue by judos** [CocoaPods/CocoaPods#7223]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Using cocoapods 1.3.1 with XCode9.

## What did you do?
added AFNetworking as a pod to cocoapods
Deployment target for our project is set to iOS 9.0

## What did you expect to happen?
No warnings about availability of methods >=iOS 9.0

## What happened instead?

We get a lot of warnings e.g.: "AFNetworking/AFURLSessionManager.m:163:30: 'setResumingHandler:' is only available on iOS 9.0 or newer" even so our deployment target is set to 9.0 and not lower.

This seems to be due to CocoaPods setting the CLANG_WARN_UNGUARDED_AVAILABILITY to YES_AGGRESSIVE.

The only other alternative for us seems to be disabling warnings entirely for pods which is probably worse than configuring this warning specifically.

Is there a way to make it go away? AFNetworking is of course not something which we can change code ourselves...

## CocoaPods Environment

```
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def x_pods

  pod 'ZXingObjC', '3.2.1', :inhibit_warnings => true
  pod 'OpenSSL', '1.0.210'
  pod 'libPhoneNumber-iOS', '0.9.6'
  pod 'youtube-ios-player-helper', '0.1.6', :inhibit_warnings => true
  pod 'CocoaLumberjack', '3.2.1', :inhibit_warnings => true
  pod 'MTMigration', '0.0.5', :inhibit_warnings => true
  pod 'HockeySDK', '4.1.3', :subspecs => ['CrashOnlyLib']
  pod 'GoogleAnalytics', '3.14.0'
  pod 'GoogleTagManager', '3.15.0'
  pod 'MBProgressHUD', '0.9.2', :inhibit_warnings => true
  pod 'SAMKeychain', '1.5.2', :inhibit_warnings => true
  pod 'TPKeyboardAvoiding', '1.3.1', :inhibit_warnings => true
  pod 'Toast', '~> 3.1.0', :inhibit_warnings => true
  pod 'YLGIFImage', '0.11'
  pod 'lottie-ios', '2.1.3', :inhibit_warnings => true

  # further private pods...
end


target 'x' do
  # Pods for x
  project 'x'
  x_pods
  target 'x_UnitTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OCMock', '3.4', :inhibit_warnings => true
  end
end
```

## Project that demonstrates the issue

The project is for a customer so I'm not able to share this.

**Comment by dnkoutso** [comment]
> This seems to be due to CocoaPods setting the CLANG_WARN_UNGUARDED_AVAILABILITY to YES_AGGRESSIVE.

CocoaPods does not set the value of this flag. It is the default value set by Xcode (in my case I use Xcode 9.1).

The best path forward is to contact the author and ask them to update `s.pod_target_xcconfig` value to change this flag.

Another option is to fork the podspec and do it yourself and then publish it in an internal repo of yours with the updated config.

This is not a CocoaPods library issue so I am going to close this.

**Comment by dnkoutso** [comment]
Try creating a new dynamic framework target on a normal `.xcodeproj` you will see Xcode sets the default value to `YES_AGGRESSIVE` for `CLANG_WARN_UNGUARDED_AVAILABILITY`.

**Comment by judos** [comment]
Thanks for the response.
I don't understand this "pod_target_xcconfig". What should I ask them to add there? Directly the flag to not have aggressive availability checks? Isn't this kind of in the wrong spot then? Usually the ones caring about warnings are those who get them. In this case I think it's only on the side of users who add the AFNetworkng/CocoaLumberjack pod...

The way I see it is that XCode generates these useless warnings, therefore I would think it makes sense that cocoapods does override this config and sets only `YES` for the `CLANG_WARN_UNGUARDED_AVAILABILITY `. Or otherwise that we can configure this option in the podfile somehow.
