### ISSUE TITLE
Install dependencies OneSignal

### ISSUE THREAD

**Issue by dogcity** [CocoaPods/CocoaPods#7224]
➜  ios git:(feature/push) ✗ pod install
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
        install onesignal dependencies
* What did you expect to happen?
       the dependencies were installed correctly
* What happened instead?
       error: Nanaimo::Reader::ParseError - [!] Unexpected end of string while parsing

### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G1036)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c14eae6956fecaf2a37c69f3a63bf72587fb3a3d
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
workspace 'yutrack.xcworkspace'
project 'yutrack.xcodeproj'
platform :ios, '9.0'

target 'yutrack' do
  pod 'OneSignal', '~> 1.13.3'

end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Unexpected end of string while parsing
 #  -------------------------------------------
1>
    ^
 #  -------------------------------------------

/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:129:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.3/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.3/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.3/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/analyzer.rb:907:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/analyzer.rb:906:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/analyzer.rb:906:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/analyzer.rb:901:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer/analyzer.rb:75:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer.rb:243:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/installer.rb:116:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Unexpected+end+of+string+while+parsing%0A+%23++-------------------------------------------%0A1%3E++%0A++++%5E%0A+%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Usage of pods static library in user's project.
   https://github.com/CocoaPods/CocoaPods/issues/1 [closed] [10 comments]
   30 Sep 2014

 - Unexpected end of string while parsing (with no file)
   https://github.com/CocoaPods/CocoaPods/issues/6670 [closed] [2 comments]
   29 May 2017

 - Nanaimo::Reader::ParseError - [!] Unexpected end of string while parsing
   https://github.com/CocoaPods/CocoaPods/issues/6528 [closed] [0 comments]
   02 Mar 2017

and 2 more at:
https://github.com/cocoapods/cocoapods/search?q=[!]%20Unexpected%20end%20of%20string%20while%20parsing%0A%20%23%20%20-------------------------------------------%0A1%3E%20%20%0A%20%20%20%20%5E%0A%20%23%20%20-------------------------------------------%0A&type=Issues&utf8=✓

**Comment by dnkoutso** [comment]
Seems like an issue within your xcodeproj, perhaps an invalid value. Please inspect `yutrack.xcodeproj/project.pbxproj` for the invalid value.

I believe you will get the same error with whatever pod you install, not just `OneSignal`.

I was able to install `OneSignal` pod successfully in a sample project of mine.

This is is not a cocoapods library issue

**Comment by dogcity** [comment]
when I run "pod install" it generates the error above, and I can not open the .xcodeproj file
![captura de pantalla 2017-11-16 a la s 13 38 30](https://user-images.githubusercontent.com/12253764/32903399-aa3d2714-cad3-11e7-930a-278863168aa9.png)

when opening the .xcworkspace file throws an error
![captura de pantalla 2017-11-16 a la s 13 39 03](https://user-images.githubusercontent.com/12253764/32903438-c3a5bec8-cad3-11e7-8c16-33ad1e9e7ee8.png)

Everything works well before installing Cocoapod ...

**Comment by dnkoutso** [comment]
Please attach a sample app if I can reproduce I will re-open.
