### ISSUE TITLE
pod spec lint NameSpec.podsepc ERROR  did not match any file

### ISSUE THREAD

**Issue by wjszf** [CocoaPods/CocoaPods#7227]
Macos:10.12.6
Xcode:9.0
Cocopods:1.4.0 beta 2
Project:https://github.com/wjszf/CPrivateImage.git
  
ERROR:
'public_header_files' pattern did not match any file.

I find pod spec lint not check  the working dir  of current NameSpec.podsepc.
this will check  /Library/Caches/CocoaPods/Pods/External/ 。but this dir  not copy
 my project inside。

**Comment by dnkoutso** [comment]
```
** BUILD SUCCEEDED **

   Testing with xcodebuild. 
 -> CImageViewDefault (0.1.2)

Analyzed 1 podspec.

CImageViewDefault.podspec passed validation.
```

Works for me.

Please ask a question to StackOverflow with CocoaPods tag. This is not a CocoaPods library issue.
