### ISSUE TITLE
unable to add “GooglePlacePicker” as dependency on swift framework of cocoapod

### ISSUE THREAD

**Issue by rakeshtatekonda** [CocoaPods/CocoaPods#7233]
I have written custom framework in swift and I want to use "GooglePlacePicker" as an dependency on cocoapods spec of that framework.Below is the error of the development pod.

"The 'Pods-NFClient' target has transitive dependencies that include static binaries: (*Pods/GooglePlacePicker/Frameworks/GooglePlacePicker.framework)".

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
