### ISSUE TITLE
Need help for podspecs

### ISSUE THREAD

**Issue by lazarte** [CocoaPods/CocoaPods#7235]
Can someone lightened me on how I can successfully build the pod specs

Below is the hierarchy for my Framework. LoginController used some of the string extension on the ExtClass like validateEmail(). So basically LoginController is dependent on the ExClass and later on I can add some subspecs that also dependent on the extension. How can create a podspec on this?

* Project
  * Extension
      * ExtClass.swift
  * Login
      * LoginController.swift
      * LoginController.xib
   * Project.h
   * Info.plist

PodSpecs - This will error
```
  s.public_header_files = 'Project/Project.h'

  s.subspec 'Login' do |login|
    login.source_files = 'Project/Login/*.{swift}'
    login.resources = 'Project/Login/*.{xib}'
    login.dependency 'Project/Extension'
  end

  s.subspec 'Extension' do |extension|
    extension.source_files = 'Project/Extension/*.{swift}'
  end
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
