### ISSUE TITLE
pod install stuck on pre-downloading from GitHub

### ISSUE THREAD

**Issue by RedPlumber** [CocoaPods/CocoaPods#7236]
I am using CocoaPods 1.3.1
I deleted the cache, pods folder and workspace.

I added 

pod 'Calabash', :git => 'https://github.com/calabash/calabash-ios.git', :tag => 'v0.21.2'

to my podfile since only version 0.21.1 is available using pod 'Calabash'

I run 'pod install --verbose'

and the script gets stuck on pre-downloading, to be specific in cloning.

I looked at the folder where the repo should be cloned and it is empty.

**Comment by orta** [comment]
I'd try re-running with `--verbose` but if it's just a cloning issue there's not really much we can do about it as CocoaPods just runs a normal `git clone` command for git repos.
