### ISSUE TITLE
Development Pods does not import custom module

### ISSUE THREAD

**Issue by baltameme** [CocoaPods/CocoaPods#7237]
Hi;

I am using CocoaPods 1.3.1 on Xcode 9.1

I was trying to make my custom modulemap to import some 'C' libraries on my Swift Framework for bridging purpose. On the swift framework level the xcode build successfully, but if i try to add the pod as a local development pod to an actual project i recieve build error saying 'No Such Module' found.

I reproduced the same case by downloading the following repos and importing them on a test project as a development pods and still receive the same error. please, not that those libraries are 
are also using modulemap to make a swift wrapper for 'C' libraries.

https://github.com/marmelroy/Zip

https://github.com/onmyway133/arcane

**Comment by amorde** [comment]
The author of the `Zip` library has written a blog post with steps on how to do what they did to get this to work:

https://medium.com/swift-and-ios-writing/using-a-c-library-inside-a-swift-framework-d041d7b701d9

This limitations here aren't necessarily related to CocoaPods, although one could argue that CocoaPods should support this natively. In the meantime the steps in that article should work
