### ISSUE TITLE
Pod install or update fails after installing Google Speech To Text framework for iOS

### ISSUE THREAD

**Issue by adarshroy** [CocoaPods/CocoaPods#7239]
I have a demo project, did Pod-init -> success.

1. added  pod 'Alamofire' -> pod install -> success
2. added  pod 'googleapis', :path => '.' -> pod install -> success
3. added any other framework, -> pod install -> fails OR did simple pod install/update -> fails

Here is the error :

------------------------------------------------------------------------------------------
`[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at /Users/ios/Documents/Projects/DemoProj4/Podfile.lock
PODS:
  - !ProtoCompiler (3.0.2):
    - Protobuf (~> 3.0)
  - !ProtoCompiler-gRPCPlugin (1.0.2):
    - !ProtoCompiler (= 3.0.2)
    - gRPC-ProtoRPC (= 1.0.2)
  - Alamofire (4.5.1)
  - BoringSSL (7.0):
    - BoringSSL/Implementation (= 7.0)
    - BoringSSL/Interface (= 7.0)
  - BoringSSL/Implementation (7.0):
    - BoringSSL/Interface (= 7.0)
  - BoringSSL/Interface (7.0)
  - googleapis (0.0.1):
    - !ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)
    - googleapis/Messages (= 0.0.1)
    - googleapis/Services (= 0.0.1)
  - googleapis/Messages (0.0.1):
    - !ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)
    - Protobuf
  - googleapis/Services (0.0.1):
    - !ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)
    - googleapis/Messages
    - gRPC-ProtoRPC
  - gRPC (1.0.2):
    - gRPC-Core (= 1.0.2)
    - gRPC-RxLibrary (= 1.0.2)
  - gRPC-Core (1.0.2):
    - gRPC-Core/Implementation (= 1.0.2)
    - gRPC-Core/Interface (= 1.0.2)
  - gRPC-Core/Implementation (1.0.2):
    - BoringSSL (~> 7.0)
    - gRPC-Core/Interface (= 1.0.2)
  - gRPC-Core/Interface (1.0.2)
  - gRPC-ProtoRPC (1.0.2):
    - gRPC (= 1.0.2)
    - gRPC-RxLibrary (= 1.0.2)
    - Protobuf (~> 3.0)
  - gRPC-RxLibrary (1.0.2)
  - Protobuf (3.4.0)

DEPENDENCIES:
  - Alamofire
  - googleapis (from `.`)

EXTERNAL SOURCES:
  googleapis:
    :path: .

SPEC CHECKSUMS:
  !ProtoCompiler: cfad9cbe5299a4923b1c3c8f150818c91efd0b6d
  !ProtoCompiler-gRPCPlugin: ee00d28bb35b26e2657f239833b8f2aa66724f96
  Alamofire: 2d95912bf4c34f164fdfc335872e8c312acaea4a
  BoringSSL: 50035b9d9eeff5529587311782fc57c00ebf13ae
  googleapis: daa20dca7a0097c6c3316fdfd888e0ba1b7c8921
  gRPC: dd3a91e0fb770b9fc4f43d1292fb19f2a2e04158
  gRPC-Core: cc4a7613190ff0bc60a0c1e702ef07cd3f868ae6
  gRPC-ProtoRPC: 11533510522a5e9627883a597a796cfe6bef05f3
  gRPC-RxLibrary: 02cc70b76bc0c5bc622ba27595cca2598d9fe528
  Protobuf: 03eef2ee0b674770735cf79d9c4d3659cf6908e8

PODFILE CHECKSUM: 18b058a3c41c21290645f923f90bea7209df1f49

COCOAPODS: 1.4.0.beta.2`

------------------------------------------------------------------------------------------

Then in terminal, I did this: "pod spec lint", and it is showing this:

--------------------------------------------------------------------------------------------

` -> googleapis (0.0.1)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/local/bin/git clone https://github.com/GoogleCloudPlatform/ios-docs-samples.git /var/folders/ww/6vrzrmr5719673rcd2dl2h0w0000gn/T/d20171128-3497-1wew1rs --template= --single-branch --depth 1 --branch 0.0.1

Cloning into '/var/folders/ww/6vrzrmr5719673rcd2dl2h0w0000gn/T/d20171128-3497-1wew1rs'...
warning: Could not find remote branch 0.0.1 to clone.
fatal: Remote branch 0.0.1 not found in upstream origin
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.`

--------------------------------------------------------------------------------------------

This is not happening for any other project, but when only this demo project is pod-installed/updated, the issue comes.
Tried all re-installing pods, psych, etc.
Please help

[https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/speech/Objective-C/Speech-gRPC-Streaming](url)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by adarshroy** [comment]
Installing googleapis as done in the sample, in my app. After that not able
to install any other pods. This is happening only for this googleapis pod.
Therefore mentioned in the issues of the Sample.

**Comment by paulb777** [comment]
It looks like an old sample since it is using gRPC 1.0.2. gRPC is now at [1.7.1](https://github.com/CocoaPods/Specs/blob/master/Specs/1/2/a/gRPC/1.7.1/gRPC.podspec.json)

**Comment by adarshroy** [comment]
But this is the only sample provided for speech-to-text Client from google. It was working perfectly fine, until I found it prevents to install other pods. 
Removing this googleapis pod from podfile and then doing pod-install, is also not working. Throwing the same error.

Have to solve this pod issue, as pod-install is not seeming possible for future pods.
What needs to be done in terminal, or my Xcode project, to remove this error and pod-install command run?

**Comment by adarshroy** [comment]
Any method to remove this pod, is also welcome

**Comment by paulb777** [comment]
You can remove the Podfile.lock before each `pod update` or `pod install`
