### ISSUE TITLE
Please support subspec can has its own product_name instead of root_spec.name

### ISSUE THREAD

**Issue by meritozh** [CocoaPods/CocoaPods#7244]
CocoaPods does not support subspec change its product name, it just use name of root spec. Now, I have a pod named `A`, which has a subspec named `z`, another pod named `B` need depend on `A/z`. But pod `A` also must depend on `B`. End, the workspace looks like this (Demo project just use A):

```
- A.xcworkspace
 - Demo.xcodeproj
 - A.xcodeproj (whole project)
  - target
   - A
  - product
   - A.framework
 - Pods.xcodeproject
  - target
   - A-a
  - product
   - A.framework
```

This will cause two problems when build demo project:

1. run `Embed Frameworks` phase first, it will copy A.framework (whole one), then run `[CP] Embed Pods Frameworks`, copy A.framework (subspec one). Subspec one will cover whole one.
2. we need build A.xcodeproj first. This condition is calculated by Xcode `implicit dependencies` feature because demo link with A.framework which is same as name of one target's product. But for now, there are two product named `A.framework`. Different target name produce same product, it will break Xcode implicit dependencies feature. 

I have tried many ways to fix the two problem. And yes, I did it. but it's too hack, is not a general solution.

I have two idea to fix problems above:

1. CocoaPods support subspec can have its own `product_name`, not just `root_spec.name`.
2. A depend on B, B depend on A/z (subspec), in this scene, change B depend on A instead of one subspec of A. Because A exist in the whole dependencies tree.

**Comment by meritozh** [comment]
Can CcocoaPods support it offically? Or we must change our project's architecture : (

**Comment by orta** [comment]
Subspecs are meant to be about breaking up an existing library, I think introducing the ability for them to start changing their product names is going to introduce a lot of build-time complexity for an edge case. I'd recommend re-architecting how you expect your Podspec to be used.

**Comment by meritozh** [comment]
How about the idea 2?
