### ISSUE TITLE
Linker error showing on installing MobileVLCKit via pods in my project

### ISSUE THREAD

**Issue by adarshroy** [CocoaPods/CocoaPods#7245]
# Report

## What did you do?

- Added in podfile: pod 'MobileVLCKit'
- Run pod-install, and pod installed successfully
- 'MobileVLCKit' folder is visible inside 'Pods' folder

## What did you expect to happen?

-In Project ->buildSettings-> OtherLinkerFlags, the pod name 'MobileVLCKit' should show
-The Project should build successfully.

## What happened instead?

-In Project ->buildSettings-> OtherLinkerFlags, the pod name 'MobileVLCKit' is not showing
-The Project build failed with linker error:

```
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_VLCTime", referenced from:
          objc-class-ref in OpusPlayViewController.o
      "_OBJC_CLASS_$_VLCMedia", referenced from:
          objc-class-ref in OpusPlayViewController.o
      "_OBJC_CLASS_$_VLCMediaPlayer", referenced from:
          objc-class-ref in OpusPlayViewController.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## CocoaPods Environment

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0.beta.2/lib/coc‌​oapods.rb

**Comment by meritozh** [comment]
If you transitive depend on one static library, you will find your project won't link with that static library, then raise a linking error.

**Comment by dnkoutso** [comment]
Please provide a sample app.
