### ISSUE TITLE
 lipo: -remove's specified would result in an empty fat file after updating  CocoaPods to pre-beta

### ISSUE THREAD

**Issue by lbagga2x** [CocoaPods/CocoaPods#7246]
# Report

## What did you do?

ℹ sudo gem install cocoapods --pre

## What did you expect to happen?

ℹ Project should build successfully

## What happened instead?

ℹ lipo: -remove's specified would result in an empty fat file

## CocoaPods Environment

ℹ 1.4.0.beta.2

**Comment by dnkoutso** [comment]
Fixed on latest master. Will ship with 1.4.0.rc1.
