### ISSUE TITLE
unable to update cocoapods 

### ISSUE THREAD

**Issue by Madhu02** [CocoaPods/CocoaPods#7255]
I'm trying to update one of the library in my pod file by changing the version no. But i'm getting 
**Analyzing dependencies [!] Unable to satisfy the following requirements:**

**ArcGIS-Runtime-SDK-iOS (~> 100.1.1) required by Podfile**
 
$pod update
Update all pods
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.3.0/gems/cocoapods-deintegrate-1.0.1`
Updating local specs repositories

CocoaPods 1.2.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.3.0/gems/cocoapods-deintegrate-1.0.1`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.13.1 (17B1003)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2d939ca0abb4172b9ef087d784b43e0696109e7c
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '7.1'

target 'Altus Blue Force' do
    pod 'ArcGIS-Runtime-SDK-iOS', '~> 10.2.5'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SSKeychain', '1.2.2'
    pod 'MBProgressHUD', '~> 0.8'
    pod 'Mantle', '~> 1.4.1'
    pod 'BlocksKit', '2.2.5'
    pod 'kingpin', '0.3.2'
    pod 'CocoaLumberjack', '~> 1.9'
    pod 'ReactiveCocoa', '~> 2.3.0'
    pod 'ActionSheetPicker-3.0', '~> 2.0.1'
    pod 'SDCAlertView', '~> 2.2'
    pod 'JSQMessagesViewController', '~> 7.0.0'
    pod 'MMDrawerController', '~> 0.5.7'
    pod 'Reachability'
end

target 'Altus Blue ForceTests', :exclusive => true do
    # this pod is not used by MyAppName Tests, but we need something here to ensure we properly link cocoapods to the MyAppName Tests target
    # this dummy pod is not part of kylef's solution, but since we don't have anything unique to our test target, I added it here to ensure something unique was present
    pod 'OCMock', '3.1.2'
    pod 'ArcGIS-Runtime-SDK-iOS', '~> 10.2.5'
end

target 'Altus Mobile' do
    pod 'ArcGIS-Runtime-SDK-iOS', '~> 10.2.5'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SSKeychain', '1.2.2'
    pod 'MBProgressHUD', '~> 0.8'
    pod 'Mantle', '~> 1.4.1'
    pod 'BlocksKit', '2.2.5'
    pod 'kingpin', '0.3.2'
    pod 'CocoaLumberjack', '~> 1.9'
    pod 'ReactiveCocoa', '~> 2.3.0'
    pod 'ActionSheetPicker-3.0', '~> 2.0.1'
    pod 'SDCAlertView', '~> 2.2'
    pod 'JSQMessagesViewController', '~> 7.0.0'
    pod 'MMDrawerController', '~> 0.5.7'
    pod 'Reachability'
end

target 'Altus Mobile Tests', :exclusive => true do
    # this pod is not used by MyAppName Tests, but we need something here to ensure we properly link cocoapods to the MyAppName Tests target
    # this dummy pod is not part of kylef's solution, but since we don't have anything unique to our test target, I added it here to ensure something unique was present
    pod 'OCMock', '3.1.2'
    pod 'ArcGIS-Runtime-SDK-iOS', '~> 10.2.5'
end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworking">
Did you mean?  to_query
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
You are using a very old version of cocoapods. Recommend you upgrade to 1.4.0.beta.2.

**Comment by Madhu02** [comment]
I have upgraded my pods to version 1.3.1 , and this is the issue i'm facing when i run pod install

$pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
[!] Unable to find a specification for `ArcGIS-Runtime-SDK-iOS (~> 100.1.1)`
$ pod outdated
Updating spec repo `master`
  $ /usr/bin/git -C /Users/PW/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 9, done.        
  remote: Compressing objects: 100% (8/8), done.        
  remote: Total 9 (delta 5), reused 0 (delta 0), pack-reused 0        
  From https://github.com/CocoaPods/Specs
     35d104c5b58..075f335e119  master     -> origin/master
  $ /usr/bin/git -C /Users/PW/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/PW/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 075f335e119 [Add] ZPageControl 0.0.1
No pod updates are available.
$ pod update ArcGIS-Runtime-SDK-iOS
Re-creating CocoaPods due to major version update.
Updating local specs repositories
  $ /usr/bin/git -C /Users/PW/.cocoapods/repos/master fetch origin --progress
  $ /usr/bin/git -C /Users/PW/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/PW/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 075f335e119 [Add] ZPageControl 0.0.1
Analyzing dependencies
[!] Unable to find a specification for `ArcGIS-Runtime-SDK-iOS (~> 100.1.1)`

What might be the issue? Please help me

**Comment by dnkoutso** [comment]
Your master repo may not be updated? Check `~/.cocoapods/repos/master`

Either way I do not think this is a cocoapods issue, please ask StackOverflow with the tag `cocoapods`.

**Comment by vaisakhcherrylabs** [comment]
i tried reinstalling the cocoapod in system. Even other libraries that i uploaded in swift 4.2, now not able to pass the validation.
