### ISSUE TITLE
Pod test_spec shouldn't attempt to test against watch simulator

### ISSUE THREAD

**Issue by SuperBarracuda** [CocoaPods/CocoaPods#7256]
## What did you do?

Created a pod spec compatible with iOS , watchOS, macOS and tvOS with test_spec.

```
Pod::Spec.new do |s|

 s.name         = 'WN'
 s.version      = '1.0.2'
 s.summary      = 'WN'
 s.homepage     = ''
 s.author = {
 }
 s.license = {
   :type => 'Private',
   :text => <<-LICENSE
             © 2017 All rights reserved.
   LICENSE
 }
 s.source = { :git => "project_url", :tag => "#{s.version}" }
 s.source_files = 'src/**/*.{h,m}'
 s.resources = 'resources/*'

 s.ios.deployment_target = '9.0'
 s.watchos.deployment_target = '2.0'
 s.tvos.deployment_target = '9.0'
 s.osx.deployment_target = '10.10'
 s.dependency 'MKDKit/MKDNetwork'
 
 s.test_spec 'Tests' do |test_spec|
	test_spec.source_files = 'tests/*.{h,m,swift}'
	test_spec.resources = 'tests/resources/*'
 end  

end
```

**Ran** 

> pod repo push podspecs WN.podspec --allow-warnings --verbose --sources='git@URL/cocoapodspecs,https://github.com/CocoaPods/Specs' 

## What did you expect to happen?

Version the pod.

## What happened instead?

XCTest couldn't be found. Im guessing this is because watchOS targets don't support unit tests. Perhaps a fix would be to prevent the pod versioning from running tests against watch targets.

```/var/folders/c2/fbtgd5b1091ffwbkfkpn85hm0000gn/T/CocoaPods-Lint-20171204-13071-1w02wok-WN/Pods/WN/tests/DrawnGame_Tests.swift:1:8: error: no such module 'XCTest'
import XCTest
       ^

2017-12-04 15:15:23.867 xcodebuild[14309:1124030] Error Domain=IDETestOperationsObserverErrorDomain Code=14 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/c2/fbtgd5b1091ffwbkfkpn85hm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-8E98EAAA-3CA8-4821-8D67-DB0E0E4B7F44/WN-Unit-Tests-7DB8D5DF-8F74-4E43-8C25-F5A7A54F7F91/Session-WN-Unit-Tests-2017-12-04_151448-TVzhyL.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/c2/fbtgd5b1091ffwbkfkpn85hm0000gn/T/com.apple.dt.XCTest/IDETestRunSession-8E98EAAA-3CA8-4821-8D67-DB0E0E4B7F44/WN-Unit-Tests-7DB8D5DF-8F74-4E43-8C25-F5A7A54F7F91/Session-WN-Unit-Tests-2017-12-04_151448-TVzhyL.log}

Testing failed:
	No such module 'XCTest'
** TEST FAILED **


The following build commands failed:
	CompileSwift normal i386 /var/folders/c2/fbtgd5b1091ffwbkfkpn85hm0000gn/T/CocoaPods-Lint-20171204-13071-1w02wok-WN/Pods/WN/tests/DrawnGame_Tests.swift
	CompileSwift normal i386 /var/folders/c2/fbtgd5b1091ffwbkfkpn85hm0000gn/T/CocoaPods-Lint-20171204-13071-1w02wok-WN/Pods/WN/tests/ALCPrizePayoutTests.swift
	CompileSwift normal i386 /var/folders/c2/fbtgd5b1091ffwbkfkpn85hm0000gn/T/CocoaPods-Lint-20171204-13071-1w02wok-WN/Pods/WN/tests/ALCRequestDrawGames_Tests.swift
	CompileSwift normal i386 /var/folders/c2/fbtgd5b1091ffwbkfkpn85hm0000gn/T/CocoaPods-Lint-20171204-13071-1w02wok-WN/Pods/WN/tests/TestDataBuilder.swift
	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(5 failures)```

## CocoaPods Environment

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.1 (17B1003)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f3c1ddf5594be4458771a92ba3f2a9e36937441d
               COMPANY-cocoapodspecs - ssh://COMPANY/cocoapodspecs.git @ 2d088b0af978a3c3634236f05aab89c0cf28b755
               COMPANY-mkodo-cocoapodspecs - https://COMPANY/cocoapodspecs.git @ 2d088b0af978a3c3634236f05aab89c0cf28b755
               podspecs - git@ COMPANY/cocoapodspecs.git @ a966de1ce29c068a0cb9297b367d4e88aa04acbb
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Dup of https://github.com/CocoaPods/CocoaPods/issues/7174
