### ISSUE TITLE
Unable to add a private pod as a dependency in another podspec.

### ISSUE THREAD

**Issue by siddharthsuneel** [CocoaPods/CocoaPods#7258]
> Before you start, are you using the latest CocoaPods release?
> A lot changes with Xcode releases that are not backwards compatible.
>Yes, I am using latest CocoaPods 1.3.1
 
Using Xcode 9 beta version
> Using Xcode 8: Requires CocoaPods 1.1.0 or above.

# Report

## What did you do?

I am running the below command: 
`pod lib lint Dependency2.podspec --no-clean`

Expected: successful validation of podspec

## What happened instead?

validation fails with an error: 
` - ERROR | [iOS] unknown: Encountered an unknown error (Unable to find a specification for `Dependency1` depended upon by `Dependency2`) during validation.`

## CocoaPods Environment

I am creating a private pod where I have two different pods where one is getting used as a dependency in the other one.

pod lib lint Dependency1.podspec --no-clean get validated successfully & I have also executed the next command to push i.e. 
`pod repo push .....`
this also get success.

The problem arises when I run `pod lib lint Dependency2.podspec --no-clean`

**Comment by dnkoutso** [comment]
Use `--sources` to specify the sources you want included during lint.

**Comment by dnkoutso** [comment]
e.g. `pod lib lint Dependency2.podspec --no-clean --sources=master,someprivaterepo

**Comment by siddharthsuneel** [comment]
@dnkoutso  this is not helping out.
Now it is giving a new error:

`- ERROR | [iOS] unknown: Encountered an unknown error (An unexpected version directory `Assets.xcassets` was encountered for the `/Users/dmi/.cocoapods/repos/Dependency2` Pod in the `Dependency1` repository.) during validation.`

**Comment by dnkoutso** [comment]
it seems that it did help out. Unfortunately, with the information you provide we are unable to guess what the problem might be.

It also does not appear to be a cocoapods library issue. Please ask in StackOverflow using the `cocoapods` tag instead.

**Comment by siddharthsuneel** [comment]
After executing the above command  `pod lib lint Dependency2.podspec --no-clean --sources=master,someprivaterepo`
I am having the following error: refer to the screenshot attached.

![screen shot 2017-12-06 at 3 50 11 pm](https://user-images.githubusercontent.com/15324076/33656895-993a749c-da9d-11e7-98fc-3cfa3270f87b.png)

**Comment by dnkoutso** [comment]
this is a build error. Open the generated workspace and inspect the issue. I cant guide any further.

Still not a CocoaPods library issue.
