### ISSUE TITLE
Pods for debug configuration are included in release (:configuration => 'Debug' does not work)

### ISSUE THREAD

**Issue by jessesquires** [CocoaPods/CocoaPods#7270]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

🌈 

# Report

## What did you do?

- Run `pod install`
- Archive app (release config) in Xcode

We've tried `:configurations => ['Debug']` and `:configuration => 'Debug'`. Neither seem to work when archiving a release build in Xcode (that is, these debug pods are included in release).

## What did you expect to happen?

Pods for `debug` configuration are not built and not included in `release`

## What happened instead?

Debug pods are included in release

### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.12.6 (16G1114)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.1
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f8b5cc31c3ddc5c38089ab7dad76d144a16065f8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

(shortened)

```ruby
source 'https://github.com/CocoaPods/Specs.git'

workspace 'PlanGrid.xcworkspace'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

pod 'ReactiveCocoa', '6.0.2'
pod 'ReactiveObjC', '1.0.1'

pod 'FLEX', '~> 2.0', :configuration => 'Debug'
```

**Comment by dnkoutso** [comment]
Can you please provide a sample project? How do you determine that its not? Have you opened Pods-PlanGrid-Release.xcconfig and see the `-framework FLEX` missing?

**Comment by dnkoutso** [comment]
How do you verify that the pod in included with your binary?

**Comment by jessesquires** [comment]
Thanks @dnkoutso !

We noticed the framework getting built in the archive logs. However, it looks`Pods-PlanGrid/Pods-PlanGrid.release.xcconfig` **does not** include `FLEX` so I think we're ok.

Sorry for the false alarm! 😄

**Comment by dnkoutso** [comment]
superb.
