### ISSUE TITLE
Plenty of Warnings for NSYearCalendarUnit

### ISSUE THREAD

**Issue by zdavatz** [CocoaPods/CocoaPods#7272]
Hi

I am using Xcode 9.2 and I get plenty of warnings regarding:

NSYearCalendarUnit should be NSCalendarUnitYear
NSMonthCalendarUnit should be NSCalendarUnitMonth

in the NTMonthYearPicker.

Thank you for your Feeback.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by zdavatz** [comment]
Well Cocoapods is not uptodate with Xcode 9.2.
