### ISSUE TITLE
Pod Repo Update HEAD is now at d1b078dfe31 [Add] CPYDownloader 0.1.2

### ISSUE THREAD

**Issue by kwstasna** [CocoaPods/CocoaPods#7274]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod repo update

## What did you expect to happen?
update the pods spec

Install latest specs

## What happened instead?
 HEAD is now at d1b078dfe31 [Add] CPYDownloader 0.1.2

Updating spec repo `master`
  $ /usr/bin/git -C /Users/kwstasna/.cocoapods/repos/master fetch origin
  --progress
  From https://github.com/CocoaPods/Specs
     7788c30b232..d1b078dfe31  master     -> origin/master
  $ /usr/bin/git -C /Users/kwstasna/.cocoapods/repos/master rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/kwstasna/.cocoapods/repos/master reset --hard
  origin/master
  HEAD is now at d1b078dfe31 [Add] CPYDownloader 0.1.2

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.6
        Host : Mac OS X 10.12.1 (16B2327e)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d1b078dfe312060bea4e8e2851137082bb95f135
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
slather               : 2.3.0
```

Any help?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by kwstasna** [comment]
Its my bad. false alarm. everything works 100% good.
