### ISSUE TITLE
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`. 

### ISSUE THREAD

**Issue by imatchegy** [CocoaPods/CocoaPods#7275]
I tried a lot :(
when it comes to ....(receiving objects:  12% (216120/1784609), 43.13 MiB | 328.00 KiB/s ) in the terminal pod install
..... it's stopped

then this note shows :
[!] unable to add a source with url `https://github.com/cocoapods/specs.git` named `master`. you can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
as bellow
pleaaase help
![screen shot 2017-12-10 at 7 46 45 am](https://user-images.githubusercontent.com/34419154/33806528-5ce2d578-dd7e-11e7-8546-97d3d6e59e83.png)
:(((

**Comment by dnkoutso** [comment]
Seems like an internet connection issue. Not a cocoapods library issue. I understand the pain point though. We might be planning some updates with CocoaPods 1.5.0 and the master repo.

Try to manually clone the repo and place it into ~/.cocoapods/repos/master` or download it as a zip and extract it.

Going to close this as a non-cocoapods library issue.
