### ISSUE TITLE
Add support for *.inl header files (C++) or manually specifying which files should be considered as headers

### ISSUE THREAD

**Issue by bes** [CocoaPods/CocoaPods#7283]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I am creating a PodSpec with a C++ library (wrapped as Obj-C++) and need to distribute it with `.inl` headers.

However, CocoaPods does not recognize `.inl` as headers, and instead adds the files as source files and XCode warns:

```
Warning: no rule to process file '/A/link/to/header.inl' of type text for architecture arm64
```

It would be nice if either CocoaPods was able to recognize `.inl` files or if it was possible to tell CocoaPods which file endings are headers and which are compiled sources.

Here is an example of an old fix that adds support for `.hh` header files.
https://github.com/CocoaPods/CocoaPods/pull/576/files

## What did you do?

Trying to create a PodSpec which includes C++ `.inl` headers

## What did you expect to happen?

The `.inl` headers to end up in `Pods > My Target > Build Phases > Headers` instead of `Compile Sources`

## What happened instead?

The files ended up in `Compile Sources`

## CocoaPods Environment

`bundle exec pod env`

### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.1
Ruby lib dir : /Users/bes/.rvm/rubies/ruby-2.3.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5b356983679436766cbfe250c273bc81129734a2
```

### Installation Source

```
Executable Path: /Users/bes/.rvm/gems/ruby-2.3.4@myapp_ios/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'MyApp' do
    pod 'lib-my-local-lib', :path => '../lib-my-local-lib'

   [... more undisclosed pods]
end
```

## Project that demonstrates the issue

N/A

**Comment by bes** [comment]
Here is the PodSpec I am using if anyone needs it

```ruby
Pod::Spec.new do |s|
  s.name             = 'lib-my-local-lib'
  s.version          = '0.1.0'
  s.summary          = 'Library'
  s.description      = <<-DESC
Description
                       DESC

  s.homepage         = 'https://github.com/...
  s.license          = { :type => 'X', :file => 'Y' }
  s.author           = { 'NN' => 'nn@nn.com' }
  s.source           = { :git => 'https://github.com/..., :tag => s.version.to_s }
  s.ios.deployment_target = '9.0'
  s.source_files = 'src/**/*.{mm,cpp,h,hpp,inl}'
  s.header_mappings_dir = 'src'
  s.xcconfig = { 'HEADER_SEARCH_PATHS' => '"${PODS_ROOT}/lib-my-local-lib/src" "${PODS_ROOT}/../../lib-my-local-lib/src"' }
end
```

**Comment by orta** [comment]
Makes sense, send in a pr to adding them [to xcodeproj](https://github.com/CocoaPods/Xcodeproj) - you'll want to edit [constants.rb](https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb))

**Comment by dnkoutso** [comment]
@bes yes as @orta said we can update the xcodeproj project to include those as headers. See this PR for reference https://github.com/CocoaPods/Xcodeproj/pull/338

**Comment by bes** [comment]
I'll give it a try

**Comment by bes** [comment]
I have made a tiny pull regarding the `.inl` header but if you guys (or anyone) has the time the time to implement a way to select header endings from the Podfile/Podspec that would probably be a lot more versatile.

But this solves my current issue. Thanks.

**Comment by dnkoutso** [comment]
@bes, merged. Going to close this issue. This will ship with 1.4.0.rc.1 when it comes out. We do not provide specific dates.

In the meantime, use http://bundler.io/ to configure and point to the SHA you want for `xcodeproj`.
