### ISSUE TITLE
CocoaPods should not pre-download entire repo if only small part of is actually needed

### ISSUE THREAD

**Issue by akshay23** [CocoaPods/CocoaPods#7285]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
`pod install`

## What did you expect to happen?
Install all pod dependencies correctly in a quick and efficient manner.

## What happened instead?
CocoaPods keeps pre-downloading my entire private repo even though I only need a small portion of it as specified by the repo's podspec file.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.1 (17B1003)
       Xcode : 9.2 (9C40b)
         Git : git version 2.13.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f2a6d1a77587ee7df9ca851f2b2d7a8fcb5144de
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

abstract_target 'RxAnimotoAbstract' do
    pod 'FSPagerView'
    pod 'Gallery'
    pod 'JWPlayer-SDK', '~> 2.7.9'
    pod 'Kingfisher'
    pod 'MBProgressHUD'
    pod 'RxGesture'
    pod 'RxRealmDataSources'

    ## NOTE: To pull from the Engine git repo uncomment below line and comment out the above line.
    ## NOTE: Since CocoaPods pre-downloads private repos, it can take several minutes to download the Engine repo!!!
    pod 'Engine', :git => 'https://github.com/animoto/engine.git', :branch => 'master'

    target 'RxAnimoto' do
        platform :ios, '10.0'
    end

    target 'RxAnimotoTests' do
    	platform :ios, '10.0'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
```

## Project that demonstrates the issue
Cannot link to private repo

**Comment by dnkoutso** [comment]
This is a one time operation though, it shouldn't need to re-download it over and over again. I do not see us changing this behavior in the future, how big is the private repo of yours? I can't imagine its bigger than the master repo which can be a problem and we are having some thoughts in 1.5.0.

I am going to close this, but feel free to push back especially if you have proposals that could improve this process.

**Comment by amorde** [comment]
@dnkoutso Note I believe they are referring to downloading the source of a pod, not a private spec repo

```ruby
## NOTE: To pull from the Engine git repo uncomment below line and comment out the above line.
## NOTE: Since CocoaPods pre-downloads private repos, it can take several minutes to download the Engine repo!!!
pod 'Engine', :git => 'https://github.com/animoto/engine.git', :branch => 'master'
```

**Comment by dnkoutso** [comment]
For this case, I believe the clone strategy just uses depth and doesn't clone the whole thing.

Here's sample verbose output:

```
-> Installing PrivatePod (1.1.0)
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://privaterepo.git /var/folders/0x/798grj997td8xhm6_jr85l680000gn/T/d20171213-16738-1nqmv9v --template= --single-branch --depth 1 --branch release/1.1.0
     Cloning into '/var/folders/0x/798grj997td8xhm6_jr85l680000gn/T/d20171213-16738-1nqmv9v'...
     Note: checking out 'b1ff89ecb10d30b982d8c8b4eb9c6f6cb033f609'.
```

Am I still understanding this correctly?

**Comment by amorde** [comment]
I think we're on the same page - there isn't much else CocoaPods could do here IMO
