### ISSUE TITLE
Unable to activate cocoapods-static-frameworks-0.0.1, because cocoapods-1.4.0.beta.2 conflicts with cocoapods (= 1.3.1)

### ISSUE THREAD

**Issue by luoqisheng** [CocoaPods/CocoaPods#7287]
### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ db5ee8b42e85183d97eb6b4be7ff479230a444b1
               ruguoapp - https://github.com/ruguoapp/ruoyou-specs.git @ 9fcaaef9764b99ba887dc4bf144ff4b747f248fe
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate       : 1.0.1
cocoapods-plugins           : 1.0.0
cocoapods-search            : 1.0.0
cocoapods-static-frameworks : 0.0.1
cocoapods-stats             : 1.0.0
cocoapods-trunk             : 1.3.0
cocoapods-try               : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/ruguoapp/ruoyou-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

workspace 'StaticLibsAppDemo.xcworkspace'
target 'StaticLibsAppDemo' do
    pod 'AsyncSwift', :podspec => './podspecs/AsyncSwift.podspec'
end
```

---------------------------------------------
Error loading the plugin `cocoapods-static-frameworks-0.0.1`.

Gem::LoadError - Unable to activate cocoapods-static-frameworks-0.0.1, because cocoapods-1.4.0.beta.2 conflicts with cocoapods (= 1.3.1)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:93:in `safe_activate_and_require'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:31:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:30:in `map'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command/plugin_manager.rb:30:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:326:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `run'
/Users/luoqisheng/.podenv/versions/1.4.0.beta.2/gems/cocoapods-1.4.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Users/luoqisheng/.podenv/versions/1.4.0.beta.2/gems/cocoapods-1.4.0.beta.2/bin/pod:55:in `<top (required)>'
/Users/luoqisheng/.podenv/versions/1.4.0.beta.2/bin/pod:23:in `load'
/Users/luoqisheng/.podenv/versions/1.4.0.beta.2/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
this does not appear to be a cocoapods issue. It seems you are using cocoapods 1.4.0.beta.2 and the gemspec of cocoapods-static-frameworks requires version 1.3.1.

My recommendation is to ask the cocoapods-static-framework author to update the gemspec to use >= 1.3.0 or something that allows you to use it with 1.4.0.

In the meantime you have to use 1.3.1 if you want to use cocoapods-static-frameworks plugin.

https://github.com/b-ray/cocoapods-static-frameworks/blob/master/cocoapods-static-frameworks.gemspec#L21

Closing as a non cocoapods library issue
