### ISSUE TITLE
pod install still fails in the second run when a dependency has "!" symbol in its name

### ISSUE THREAD

**Issue by phlippieb** [CocoaPods/CocoaPods#7302]
* [:+1:] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Upgrade CocoaPods to 1.4.0.rc.1
2. Include a pod with an `!` (exclamation mark) in its name, such as `!ProtoCompiler-gRPCPlugin`
3. Run `pod install` **twice**

## What did you expect to happen?

The parsing issues that were encountered in 1.3.0 and 1.3.1 to be fixed, and all pods to install without errors.

## What happened instead?

On the second `pod install`, the following parsing error still occurs:
```
[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at /path/to/Podfile.lock
```

**Comment by phlippieb** [comment]
Note: This issue has already been noted since 1.3.0 and is detailed by #6925, #6955,#6980, #7239, #7241, and #7268 (that I could find). These issues have all been closed as duplicates (strangely, #6925 and #6955 are marked as dupes of *each other*) and as fixed by CocoaPods/Core#395. 

However, to my understanding, version 1.4.0.rc.1 has the fix merged; yet the issue persists. Thus this issue should be closed as fixed yet; or at least, some of the existing issues should be reopened.

There is an open PR at CocoaPods/Core/pull/419 to fix the issue, which is still awaiting feedback on a comment.

The latest version before this issue was introduced is 1.2.1, which was released back in April, and has problems of its own. Considering the relatively long waits between stable releases, it would be greatly appreciated if 1.4.0 could fix this issue once and for all.

**Comment by phlippieb** [comment]
gRPC has an example project that can be used to demonstrate the issue. Instructions to set up (found [here](https://github.com/grpc/grpc/tree/master/examples/objective-c/helloworld)):

```
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
cd examples/objective-c/helloworld
pod install
```
The first `pod install` should work, but running `pod install` again will fail with 1.4.0.rc.1.

**Comment by dnkoutso** [comment]
Will move this to 1.5.0.

**Comment by dnkoutso** [comment]
Confirmed.

**Comment by phlippieb** [comment]
@dnkoutso Ok rad. Any chance we could aim to get this in 1.4.0? From the number of issued opened for this in the past, seems like this fix is highly sought after. I for one would love to be able to use an up-to-date version of CocoaPods again :) As I mentioned above, there is an open PR for this already at CocoaPods/Core/pull/419

**Comment by dnkoutso** [comment]
@phlippieb I am sorry but 1.4.0 is about to ship (most likely today) this will have to be for 1.5.0 or 1.4.1 quick update.

In the meantime once we fix it there will be easy ways using bundler for you to consume the fix.

**Comment by njovy** [comment]
I'm also facing this issue after upgrade to 1.4.0.
Do we have any workaround for this issue?

**Comment by segiddins** [comment]
https://github.com/CocoaPods/Core/pull/381/files is what broke things
