### ISSUE TITLE
Please specify "higher minimum deployment target" dependency

### ISSUE THREAD

**Issue by AaronBratcher** [CocoaPods/CocoaPods#7304]
* [ X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

While installing a pod to a local podspec, I get the Specs satisfying the `xxx` dependency were found, but they required a higher minimum deployment target. It would be good if it could tell me WHAT dependency had a higher minimum deployment target.

## What did you do?

 Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Got an error about minimum deployment target.

### Stack

```
   CocoaPods : 1.4.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G1114)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : livepersoninc - https://github.com/LivePersonInc/iOSPodSpecs.git @ fab2df00efa71fb4996a44a7f39c98354c821643
               lprnd-lp-coapp-pods - git@lpgithub.dev.lprnd.net:RnD-Mannheim/lp-coapp-pods.git @ 20f665d3a1039f5218d6aeec789f6439cda94cd3
               lprnd-lpmessagingsdk-pod - git@lpgithub.dev.lprnd.net:lp-mobile/LPMessagingSDK-Pod.git @ 30965a6f6d59e8685c828fad54592b760425df28
               master - https://github.com/CocoaPods/Specs.git @ 8ccb84beba24a27269a61dfcb32c566927085370
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Reference App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ContactAtOnceMessaging', :path => 'ContactAtOnceMessaging/'

end
```

**Comment by ahmetabdi** [comment]
@AaronBratcher Why close?

**Comment by AaronBratcher** [comment]
That was so long ago, I don't remember. I must have found the solution.

**Comment by fssrepository** [comment]
I have browsed everywhere, but i have found the solution. Very likely the Firebase related pods are not in sync, so you need to let the cocoapod to resolve the required dependencies again.
It is related to a dead Podfile.lock, which you should remove, and pod install, and it will be fine.

**Comment by GreenRidingHood** [comment]
@ghost 

i deleted pods folder and Podfile.lock from platform/ios (Cordova)
i still see that error when i try to run 'pod install'

<img width="654" alt="Screen Shot 2019-05-08 at 11 30 21 AM" src="https://user-images.githubusercontent.com/17296724/57391718-b18de900-7184-11e9-96a9-0578bdaa84c2.png">

**Comment by GreenRidingHood** [comment]
Solved the issue with changing 
platform :ios, '8.0' to platform :ios, '9.0' 
form platform/ios/Podfile  file

thx

**Comment by nihp** [comment]
Above @GreenRidingHood  answer works for me. 

What is the maximum number  platform :ios, '9.0' we can add. 

I have a clarification here. Can anyone brief what is the use of ios here with 8, 9 and soon

**Comment by Manikandan707** [comment]
> Solved the issue with changing
> platform :ios, '8.0' to platform :ios, '9.0'
> from platform/ios/Podfile file
> 
> thx

This one is working for me. I have changed iOS '9.0' to '10.0'.

**Comment by orsospatrick** [comment]
> > Solved the issue with changing
> > platform :ios, '8.0' to platform :ios, '9.0'
> > from platform/ios/Podfile file
> > thx
> 
> This one is working for me. I have changed iOS '9.0' to '10.0'.

Thank you a lot ! WORK FOR ME!

**Comment by akjesto** [comment]
I have got the issue like the following

![Screen Shot 2020-05-08 at 8 49 36 AM](https://user-images.githubusercontent.com/8862491/81366341-018cec00-9108-11ea-8670-670b399ef555.png)


In my pod file like the following
 ```
 platform :ios, '10.0'
pod 'AFNetworking','~> 4.0.1'
 pod 'AFOAuth2Manager','~> 3.0'
```

**Comment by frankarinze** [comment]
> > Solved the issue with changing
> > platform :ios, '8.0' to platform :ios, '9.0'
> > from platform/ios/Podfile file
> > thx
> 
> This one is working for me. I have changed iOS '9.0' to '10.0'.

This too worked for me thanks!

**Comment by haewhybabs** [comment]
changing it from iOS '9.0' to '11.0' works for me

**Comment by diegslva** [comment]
> > > Solved the issue with changing
> > > platform :ios, '8.0' to platform :ios, '9.0'
> > > from platform/ios/Podfile file
> > > thx
> > 
> > 
> > This one is working for me. I have changed iOS '9.0' to '10.0'.
> 
> This too worked for me thanks!

Work's for me! '9.0' bump it to '11.0' in my case!

**Comment by real1900** [comment]
Put this in your pod file

platform :ios, '10.1'

**Comment by kevin1jamal** [comment]
change platform:ios, : 9.0 to 11.0

it work for me

**Comment by Shashank123sprive** [comment]
Check in your Podfile, and if it is still 9.0 then make it 10.0 or higher
**platform :ios, '10.0'**

**Comment by frankmaayn** [comment]
> > Solved the issue with changing
> > platform :ios, '8.0' to platform :ios, '9.0'
> > from platform/ios/Podfile file
> > thx
> 
> This one is working for me. I have changed iOS '9.0' to '10.0'.

Changed my platform: ios 9.0 to platform: ios 10.0
Thank you so much!

**Comment by Antonz0** [comment]
Guys, just simply bumping target iOS version and being happy IS NOT a solution for an outlined problem. 
For me I need to stay with iOS 9, and I need to know which dependency causes violation of installation. Is it so hard to implement?

**Comment by p4rse** [comment]
> Guys, just simply bumping target iOS version and being happy IS NOT a solution for an outlined problem.
> For me I need to stay with iOS 9, and I need to know which dependency causes violation of installation. Is it so hard to implement?

You will need to install an older version of that dependency which causes the issue, otherwise you have no other choices.

**Comment by Antonz0** [comment]
> > Guys, just simply bumping target iOS version and being happy IS NOT a solution for an outlined problem.
> > For me I need to stay with iOS 9, and I need to know which dependency causes violation of installation. Is it so hard to implement?
> 
> You will need to install an older version of that dependency which causes the issue, otherwise you have no other choices.

I know that I can install an older version. The original question and bug report were not about it. 
It was about improving error reporting - if CocoaPods knows that some dependency prevents installation, then display which! It should not be too hard. 
This information is not reported even in verbose mode.

A good example: Firebase Crashlytics claims that it's compatible with iOS 9. And iOS 9 can be important because Apple dropped some devices on this version - users with such devices cannot upgrade to iOS 10 even if they want. But, the latest version doesn't want to install when you request iOS 9 - only very old and outdated version gets installed. And if you force to install '~ 7.7' version it fails with such a non-informative message. And I've checked - it's not a Firebase Crashlytics, who's to blame - it's one of their huge dependency tree (other Firebase & Google modules) which cause this issue. If CocoaPods has clearly shown which dependency breaks installation I may go to the vendor and ask questions to them. Or try patching.

**Comment by paulb777** [comment]
@Antonz0 You may be running into a bug being addressed by https://github.com/firebase/firebase-ios-sdk/pull/7681. If so a workaround is `pod 'FirebaseCrashlytics'` instead of `pod 'Firebase/Crashlytics'`

**Comment by Antonz0** [comment]
> @Antonz0 You may be running into a bug being addressed by [firebase/firebase-ios-sdk#7681](https://github.com/firebase/firebase-ios-sdk/pull/7681). If so a workaround is `pod 'FirebaseCrashlytics'` instead of `pod 'Firebase/Crashlytics'`

Much thanks for it! Looks like it works. I've also used "Firebase/Analytics" and switched it to "FirebaseAnalytics".
So, looks that there's a two version of frameworks - monolithic without additional dependencies (no slash) and ones that have a lot of dependencies on other Google/Firebase components, right?

**Comment by paulb777** [comment]
@Antonz0 It was just a bug only with the Firebase/Crashlytics specification. Otherwise the only difference of using the subspecs from the Firebase pod, is installing the one extra Firebase pod itself which gives access to the Firebase module, so that code can import the single Firebase module instead of each Firebase library separately.

**Comment by MarioRover** [comment]
Change platform iOS to higher version that exist.
platform :ios, '9.0' -> platform :ios, '14.0'...

**Comment by Antonz0** [comment]
> 
> 
> Change platform iOS to higher version that exist.
> platform :ios, '9.0' -> platform :ios, '14.0'...

Please, do not give "simple" but destructive solutions. You can easily rise the target platform to whatever version is available. This is not solving the issue, it produces another - your build will not be compatible with older versions, and probably in a subtle, hard to test way. And many products need to support older versions of iOS.

**Comment by raqib850** [comment]
> Solved the issue with changing
> platform :ios, '8.0' to platform :ios, '9.0'
> from platform/ios/Podfile file
> 
> thx

I changed my already existing 9.0 to 11.0 and it is working , thanks for the hint

**Comment by non4mee** [comment]
try change platform :ios, "your num" for '11.0' its work for me

**Comment by Antonz0** [comment]
> try change platform :ios, "your num" for '11.0' its work for me. 17.05.2022

Please, this is not a fix but just an "easy tweak to make myself happy". See the [comment above](https://github.com/CocoaPods/CocoaPods/issues/7304#issuecomment-870398617) on why this can be not what you want:

**Comment by phillipjfry93** [comment]
Go into the file its indicating. For me it was 
"EXDevice (from `../node_modules/expo-device/iOS`)"

I looked in "EXDevice.podspec" and found that it asked for a minimum platform. Looked like this: 


Pod::Spec.new do |s|
  s.name           = 'EXDevice'
  s.version        = package['version']
  s.summary        = package['description']
  s.description    = package['description']
  s.license        = package['license']
  s.author         = package['author']
  s.homepage       = package['homepage']
//This one right here 
  s.platform       = :ios, '12.0'
  s.source         = { git: 'https://github.com/expo/expo.git' }
  s.static_framework = true

  s.dependency 'ExpoModulesCore'

My version in my core pod file was set to '11.0' for some reason. Like @GreenRidingHood originally said, change it and it should work. Just wanted to elaborate in case you have a different version where to find solution. Hope this helps!

**Comment by domestia** [comment]
I used "pod update" after removing pubspec.lock and it works (don't know if it's necessary to remove it though)
`
Update all pods
Updating local specs repositories
Analyzing dependencies
firebase_core: Using Firebase SDK version '9.2.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '9.2.0' defined in 'firebase_core'
Downloading dependencies
...
`
It give me that now: 
`Running pod install...
Running Xcode build...
Xcode build done.`

**Comment by mmmoussa** [comment]
Had the same issue, running `pod update` was the solution.

**Comment by Manu343726** [comment]
> > Solved the issue with changing
> > platform :ios, '8.0' to platform :ios, '9.0'
> > from platform/ios/Podfile file
> > thx
> 
> This one is working for me. I have changed iOS '9.0' to '10.0'.

I have changed iOS '13.0' to '14.0' and it didn't work for me :(
