### ISSUE TITLE
Private framework not linked to project

### ISSUE THREAD

**Issue by AaronBratcher** [CocoaPods/CocoaPods#7305]
* [ X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Created a private framework called ContactAtOnceMessaging and associated .podspec then created a project to use it and a podfile. Ran pod install

## What did you expect to happen?

Expected the newly created .xcworkspace to include the private framework so I could include it in my project classes and use it.

## What happened instead?

All dependencies were downloaded and included properly, however my private framework was not.
`import ContactAtOnceMessaging` in the app results in a `No such module 'ContactAtOnceMessaging'` error

### Stack

```
   CocoaPods : 1.4.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G1114)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : livepersoninc - https://github.com/LivePersonInc/iOSPodSpecs.git @ fab2df00efa71fb4996a44a7f39c98354c821643
               lprnd-lp-coapp-pods - git@lpgithub.dev.lprnd.net:RnD-Mannheim/lp-coapp-pods.git @ 20f665d3a1039f5218d6aeec789f6439cda94cd3
               lprnd-lpmessagingsdk-pod - git@lpgithub.dev.lprnd.net:lp-mobile/LPMessagingSDK-Pod.git @ 30965a6f6d59e8685c828fad54592b760425df28
               master - https://github.com/CocoaPods/Specs.git @ 4c5e45958aa1e6e0fb2d0b2be702efda050b7d5a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Reference App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ContactAtOnceMessaging', :path => 'ContactAtOnceMessaging/'

end
```

### Framework Podspec

``` ruby
Pod::Spec.new do |s|
  s.name         = "ContactAtOnceMessaging"
  s.version      = "1.0.0"
  s.summary      = "In-App Messaging framework for Contact At Once customers"
  s.authors      = "Contact At Once"
  s.license      = "Private"
  s.homepage     = "http://www.contactatonce.com/live-chat-support/"

  s.platform     = :ios, '10.0'
  
  s.source                  = { :http => 'AaronLBratcher.com/ContactAtOnceMessaging.zip' }
  s.vendored_frameworks     = 'ContactAtOnceMessaging.framework'
  s.frameworks              = 'UIKit'
  
  s.ios.dependency 'TTTAttributedLabel', '~> 2.0'
  s.ios.dependency 'SLXMPPFramework', '~> 4.0'
  s.ios.dependency 'Promises', '~> 2.0'
  s.ios.dependency 'RNCryptor', '~> 5.0'
  s.ios.dependency 'ReachabilitySwift', '~> 4.1'
end

```

## Project that demonstrates the issue

[iOS-Messaging-SDK.zip](https://github.com/CocoaPods/CocoaPods/files/1598325/iOS-Messaging-SDK.zip)

## PS
I see that someone else has the same issue on StackOverflow and there is no answer provided. https://stackoverflow.com/questions/47704497/ios-publish-private-code-framework-on-cocoapods

**Comment by dnkoutso** [comment]
@AaronBratcher there is no such `ContactAtOnceMessaging.framework` file present in the sample you provided me. If this is the case with your project then this is the problem.

**Comment by dnkoutso** [comment]
You are also using the `:path` directive in your Podfile this means that the `ContactAtOnceMessaging.podspec` is being used locally. Download the `.framework` from `AaronLBratcher.com/ContactAtOnceMessaging.zip` and place it into the same folder as the podspec and try again.

Generally, this does not appear a CocoaPods library issue so far, so I am going to close.

**Comment by AaronBratcher** [comment]
The local podspec specifies the HTML location of the zipped framework.

**Comment by dnkoutso** [comment]
Yes but when you use `:path` in the `Podfile` its being treated as a local pod and no sources are downloaded, instead everything is used locally and relative to the podspec path.

**Comment by AaronBratcher** [comment]
Okay. Thanks

**Comment by dnkoutso** [comment]
Can try using `:podspec => ...` instead I think that will do it properly.

**Comment by Jignesh1805** [comment]
how to private .framework use in my own cocoapod lib ? please help me
