### ISSUE TITLE
No profile created for my Pod on CocoaPods.org

### ISSUE THREAD

**Issue by hemangshah** [CocoaPods/CocoaPods#7306]
This is my project: https://cocoapods.org/?q=zingle

This is project's Github URL: https://github.com/hemangshah/Zingle

But I can't see a profile on CocoaPods.org. 

There's no expand button for it.

What am I missing?

<img width="1398" alt="screen shot 2018-01-03 at 10 09 10 am" src="https://user-images.githubusercontent.com/3313412/34509289-45ffa9fa-f06e-11e7-8da2-00f821475228.png">

**Comment by dnkoutso** [comment]
Please file issue on https://github.com/CocoaPods/cocoapods-docs project.

**Comment by hemangshah** [comment]
@dnkoutso, Done! https://github.com/CocoaPods/cocoapods-docs/issues/10
