### ISSUE TITLE
Problems in a Swift-Objective-C-mixed static_framework pod, with vendor frameworks and libraries. I'm using v1.4.0.rc.1.

### ISSUE THREAD

**Issue by jaybowong** [CocoaPods/CocoaPods#7307]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ I just can't wait for v1.4.0 any longer. I believe a lot of developers feel the same. So I gave v1.4.0.rc.1 a try.
I created a pod that has both Swift and Objective-C code. It also has some vendor frameworks and libraries. `s.static_framework` is `true` in my podspec file. I found some bad use cases. 

Below are all possible use cases. Those without check marks are not working.

In `AwesomePodObjectiveCObject.m` file
- [x] `@import VendorFramework;`
- [x] `#import "VendorLibrary.h";`
- [x] `#import "AwesomePod-Swift.h";`, use `AwesomePodSwiftObject.swift`

In `AwesomePodSwiftObject.swift` file
- [x] `import VendorFramework`
- [ ] Use VendorLibrary
- [ ] Use `AwesomePodObjectiveCObject` class

In `MyAppObjectiveCObject.m` file
- [x] `@import VendorFramework;`
- [x] `#import "VendorLibrary.h";`
- [x] `@import AwesomePod;`, use `AwesomePodObjectiveCObject.h`
- [ ] `@import AwesomePod;`, use `AwesomePodSwiftObject.swift`

In `MyAppSwiftObject.swift` file
- [x] `import VendorFramework`
- [x] `#import VendorLibrary.h;` in `MyApp-Bridging-Header.h`
- [ ] `import AwesomePod`, use `AwesomePodObjectiveCObject.h`
- [x] `import AwesomePod`, use `AwesomePodSwiftObject.swift`

## What did you expect to happen?

ℹ I expected all these use cases work.

## What happened instead?

ℹ As listed above.

## CocoaPods Environment

ℹ 
### Stack

```
   CocoaPods : 1.4.0.rc.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : aliyun - https://github.com/aliyun/aliyun-specs.git @ 4a3f51d9c5c522281907b72b4f9e67d633b34982
               cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ cd48c04d0d05dedff4edf2bcfa4a02819d387234
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-amimono     : 0.0.10
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'SwiftOCMixedPodWithLibAndFrameworkDependencies_Example' do
  pod 'SwiftOCMixedPodWithLibAndFrameworkDependencies', :path => '../'

  target 'SwiftOCMixedPodWithLibAndFrameworkDependencies_Tests' do
    inherit! :search_paths

    
  end
end
```

## Project that demonstrates the issue

ℹ https://github.com/jaybowong/SwiftOCMixedPodWithLibAndFrameworkDependencies.git

**Comment by paulb777** [comment]
@jaybowong Thanks for the feedback and detailed test case. This is a dup of #7213. See the discussion there for a bridging header workaround and more details about the problem.

So far, we have not come up with a solution that would be low risk enough to fit into 1.4.0.

**Comment by rezakhmf** [comment]
any update for this:(? really stop us to go ahead...thanks

**Comment by paulb777** [comment]
@rezakhmf We're unlikely to have automatic support for mixed Swift/Objective C static framework pods in 1.4.0. I plan to work on it for 1.5.0. In the meantime there is the bridging header workaround described in #7213.

**Comment by paulb777** [comment]
Reopening since the last two app test failures are beyond the scope of mixed Swift/ObjC pod build issue covered by #7213.

**Comment by bryanboyko** [comment]
@paulb777 Is there a fix for the last two app test failures in PR #6966?

**Comment by paulb777** [comment]
I'm making progress on this and now have all the tests working except for the vendor library in the pod swift file which I believe is failing for the unrelated reason of no module map for the vendor library. The changes I've made to the tests are at https://gist.github.com/paulb777/ed910f1500ca15bde6f1150c47b8905a.  A PR should be out in the next week.
