### ISSUE TITLE
Is there a way to checkout code/binary framework or static library and do NOT integration with workspace and even specify the download path?

### ISSUE THREAD

**Issue by jacobjiangwei** [CocoaPods/CocoaPods#7308]
Is there a way to checkout code/binary framework or static library and do NOT integration with workspace and even specify the download path?

**Comment by dnkoutso** [comment]
Please ask in StackOverflow, however I think you are after a `--do-not-integrate` flag during `pod install`? 

Either way this is not an issue with the CocoaPods library so I am going to close.
