### ISSUE TITLE
Not able to import CardIO (static framework) into my Swift framework

### ISSUE THREAD

**Issue by jamehta** [CocoaPods/CocoaPods#7311]
# Report

## What did you do?

I have a new swift framework in which i want to use CardIO which is static framework. Since my framework cannot have bridging header, i am finding a way to include CardIO/CardIO.h in my framework. But #import <CardIO/CardIO.h> OR import CardIO fails.

CardIO does not have umbrella header. can somebody help with what are the steps to include this file. i also tried modulemap file but giving path in that file is hard coz we cannot give path as Pods/CardIO/CardIO.h

**Comment by jamehta** [comment]
@neonichu

**Comment by dnkoutso** [comment]
Please provide a sample app demonstrating the issue. Additionally this looks like a great question to ask in StackOverflow under the tag 'cocoapods'.

This does not appear to be an issue with the library itself.
