### ISSUE TITLE
difference between `:git => '...'` and `git: '...'`?

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#7312]
Is there any difference between syntaxes:

    pod 'example', :git => 'https://example.com/examplegit', :branch => 'master', :commit => 'HEAD'

    pod 'example', git: 'https://example.com/example.git', branch: 'master', commit: 'HEAD'

Is one syntax recommended over the other?

**Comment by Coeur** [comment]
Oh, actually it's something related to Ruby 1.9+, not CocoaPods specifically: https://stackoverflow.com/questions/8675206/is-there-any-difference-between-the-key-value-and-key-value-hash-no

**Comment by dnkoutso** [comment]
I believe its 2.0.0

**Comment by Coeur** [comment]
@dnkoutso, should I make pull requests to change it on https://github.com/CocoaPods/pod-template and on documentations or you prefer we don't change the examples?
