### ISSUE TITLE
Installing a pod from `:git` fails in certain circumstances

### ISSUE THREAD

**Issue by RishabhTayal** [CocoaPods/CocoaPods#7315]
## What did you do?
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
Failed to install pods if the `:git` url is specified.
E.g.
```
Pre-downloading: `CryptoSwift` from `https://github.com/krzyzanowskim/CryptoSwift`, branch `swift32`
[!] Failed to download 'CryptoSwift'.
```

**Comment by amorde** [comment]
Could you provide an example project that demonstrates the issue?

**Comment by RishabhTayal** [comment]
@amorde Here is a example project: https://www.dropbox.com/s/yjtls9y63mf7nfy/ExampleProject.zip?dl=0

There is nothing out of ordinary setup.

**Comment by amorde** [comment]
@RishabhTayal 

I get the following:

```
$ pod install                                                                                                                                                             ‹system›
Analyzing dependencies
Pre-downloading: `Spring` from `https://github.com/MengTo/Spring.git`, branch `swift3`
Downloading dependencies
Installing Spring (1.0.3)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `ExampleProject.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

Please check your internet connection, or try asking a question on [StackOverflow](https://stackoverflow.com/questions/tagged/cocoapods). This does not appear to be an issue with CocoaPods

**Comment by dnkoutso** [comment]
What @amorde said. Seems like a network user configuration issue.
