### ISSUE TITLE
Multiple "pod repo update" commands fail because of git.

### ISSUE THREAD

**Issue by daniel-beard** [CocoaPods/CocoaPods#7317]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Multiple jenkins jobs on the same machine ran `pod repo update`, this obviously fails because git holds locks: 

```bash
Exit status of command 'pod repo update ios-my-cocoapods' was 1 instead of 0.
Updating spec repo `ios-my-cocoapods`
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods fetch origin --progress
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods reset --hard origin/master
  fatal: Unable to create '/Users/builduser/.cocoapods/repos/ios-my-cocoapods/.git/index.lock': File exists.
  
  Another git process seems to be running in this repository, e.g.
  an editor opened by 'git commit'. Please make sure all processes
  are terminated then try again. If it still fails, a git process
  may have crashed in this repository earlier:
  remove the file manually to continue.
[!] CocoaPods was not able to update the `ios-my-cocoapods` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
```

## What did you expect to happen?

Given that cocoapods is often used in CI jobs, I'd expect cocoapods to be able to handle this case. 

## What happened instead?

See error message above.

## CocoaPods Environment

```
$ pod env

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.0
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2_1/lib
Repositories : ios-my-cocoapods - git@github.privatecompanyurl.com:ios/ios-my-cocoapods.git @ 03be05fe4339a34927f41c5e6e6c592436d276ca
               master - https://github.com/CocoaPods/Specs.git @ 77a078acf65b13224ab92950ae06191e0a73ffb6
```

### Installation Source

```
Executable Path: /Users/dbeard/.podenv/versions/1.4.0.beta.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
This seems like a private repo and that cannot be updated.

Please go into `~/.cocoapods/repos/ios-my-cocoapods` and do `git pull` and see why the private repo cannot be updated.

Also the error message shows:
```
Updating spec repo `ios-my-cocoapods`
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods fetch origin --progress
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/builduser/.cocoapods/repos/ios-my-cocoapods reset --hard origin/master
  fatal: Unable to create '/Users/builduser/.cocoapods/repos/ios-my-cocoapods/.git/index.lock': File exists.
```
Try:
```
rm /Users/builduser/.cocoapods/repos/ios-my-cocoapods/.git/index.lock
```

And see if that works.

This is not a CocoaPods library issue so I am going to close.

**Comment by daniel-beard** [comment]
@dnkoutso this is not a permissions issue, and it's trivially reproducible with the master spec repo as well. Please reopen.

**Comment by dnkoutso** [comment]
@daniel-beard I do not get this issue with the master repo, what particularly do you see as specific to the master repo? The error message clearly shows its failing to update your own private repo.

**Comment by dnkoutso** [comment]
```
[!] CocoaPods was not able to update the `**ios-my-cocoapods**` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`
```

**Comment by daniel-beard** [comment]
Running `git pull` from that repository on disk shows no issues. 
This is able to recreate the issues I'm talking about:

```ruby
thread_1 = Thread.new do
    puts `pod repo update`
end

thread_2 = Thread.new do
   puts `pod repo update`
end

thread_1.join
thread_2.join
```

**Comment by orta** [comment]
Makes sense, you could make the `pod repo update` command look for a git lock and skip updating if it's there

**Comment by dnkoutso** [comment]
Hm, so currently nothing handles this and it seems like you are calling `pod repo update` across multiple threads on the same machine.

What are you trying to accomplish? You might be able to handle this yourself via a locking mechanism rather than handle this inside CocoaPods?

**Comment by dnkoutso** [comment]
I re-opened the issue but I still do not think we will be building this inside CocoaPods to begin with.

Apologies for the quick close.

**Comment by daniel-beard** [comment]
@dnkoutso this is because of multiple simultaneous (independent) iOS build jobs running on a single machine through jenkins. 

@orta guess I'll try this route or implement a timeout like "if pod repo has been updated in the last hour, don't update again"

**Comment by dnkoutso** [comment]
I will mark this as a medium enhancement to make `pod repo update` command thread safe.

**Comment by serges147** [comment]
We have exactly the same issue as @daniel-beard described - periodically one or another job fails on `pod repo update` step. And it's all depends on whether there are several concurrent jobs in their beginning phase (where we do the pod call) or not.

**Comment by serges147** [comment]
BTW, wrapping pod call into small ruby code solves the problem.
```ruby
#!/usr/bin/env ruby

printf("Waiting for POD lock...")
File.open("/tmp/#{File.basename $0}.lock", File::RDWR|File::CREAT, 0644).flock(File::LOCK_EX)
printf(" got it.\n")

system("bundle exec pod install --repo-update")
```

**Comment by rpecka** [comment]
May I pick up this issue?

**Comment by kristerkarto** [comment]
Same problem on Azure Devops with private agents. I have multiple agents on same machine.

**Comment by amorde** [comment]
@rpecka yes, if you'd like to work on this PRs would be welcome!

**Comment by fandor92** [comment]
It's still happening with the same error on our CI system using GitLab and CocoaPods 1.7.5 :(

**Comment by SunnySunning** [comment]
> It's still happening with the same error on our CI system using GitLab and CocoaPods 1.7.5 :(

you can try 1.8.0-beta1。

**Comment by yashwanth-l** [comment]
I still this issue occurring with GitLab CI and static nodes. @serges147
