### ISSUE TITLE
How do I make use of aggregate target? Xcode build passes but podspec lint fails. 

### ISSUE THREAD

**Issue by kandelvijaya** [CocoaPods/CocoaPods#7319]
# Report

I wanted to use CCommonCrypto in the library that I'm working on. I had 2 options; a) use modulemap b) use aggregate target and create module-map in the run phase. 

I favored the second approach. The build is Okay `xcodebuild -workspace OAuth2.xcworkspace -scheme OAuth2`, tests target runs fine and everything is good locally until `pod spec lint OAuth2.podspec --verbose`.

I expected the lint to build the project successfully. 

Instead, build failed. Note the build passes with both Xcode build and CLI build using `xcodebuild -workspace OAuth2.xcworkspace -scheme OAuth2`.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.1 (9B55)
         Git : git version 2.15.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : accengage - https://github.com/Accengage/CocoaPodsSpecs.git @ 66e9de64664678ebeb70d8f67db79bc130c6f019
               master - https://github.com/CocoaPods/Specs.git @ aaf8d351ff67e06043c2923bd87e80e35d04cb78
               zalando - https://stash.zalando.net/scm/shop-mobile/specs.git @ 7944fca15a750e02bc6ed61d467525fb88a5ac33
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.3.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'OAuth2' do
  use_frameworks!

  # Pods for OAuth2
  pod 'Kekka'

  target 'OAuth2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

https://github.com/kandelvijaya/OAuth2

## Screens 
<img width="588" alt="screen shot 2018-01-09 at 21 34 30" src="https://user-images.githubusercontent.com/4518004/34742213-af7042fc-f585-11e7-859d-b3ec1dab511f.png">

<img width="880" alt="screen shot 2018-01-09 at 21 34 17" src="https://user-images.githubusercontent.com/4518004/34742227-b72eec3c-f585-11e7-8801-333fefaf9525.png">

  
<img width="1283" alt="screen shot 2018-01-09 at 21 41 39" src="https://user-images.githubusercontent.com/4518004/34742307-faa19c12-f585-11e7-90ca-34452840f667.png">

**Comment by dnkoutso** [comment]
I don't think you can do this. `lint` will create its own project and does not support adding aggregate targets.

But with 1.4.0 you may be able to use a `script_phase` DSL, see this https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L1300-L1337

**Comment by kandelvijaya** [comment]
@dnkoutso Thanks for the pointer. Will try out soon and update.

**Comment by tahourj** [comment]
Hi all in case I have used script_phase to generate common_cryto module for a swift project and worked successfully
here is my podspec DSL
`s.script_phases = [ { :name => 'CommonCryptoModule', :script => 'if [ -d "${BUILT_PRODUCTS_DIR}/CommonCryptoModuleMap" ]; then
echo "${BUILT_PRODUCTS_DIR}/CommonCryptoModuleMap directory already exists, so skipping the rest of the script."
exit 0
fi

mkdir -p "${BUILT_PRODUCTS_DIR}/CommonCryptoModuleMap";
touch "${BUILT_PRODUCTS_DIR}/CommonCryptoModuleMap/module.modulemap";
echo "module CommonCrypto [system] {" >> $BUILT_PRODUCTS_DIR/CommonCryptoModuleMap/module.modulemap;
echo "header \"${SDKROOT}/usr/include/CommonCrypto/CommonCrypto.h\"" >> $BUILT_PRODUCTS_DIR/CommonCryptoModuleMap/module.modulemap;
echo "export *" >> $BUILT_PRODUCTS_DIR/CommonCryptoModuleMap/module.modulemap;
echo "}" >> $BUILT_PRODUCTS_DIR/CommonCryptoModuleMap/module.modulemap;', :execution_position => :before_compile , :shell_path => '/bin/sh' }]`
