### ISSUE TITLE
CocoaPods documentation is not updating with README.md

### ISSUE THREAD

**Issue by Monntay** [CocoaPods/CocoaPods#7322]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Update and push the README.md

nano LocalizableUI.podspec
// update version code
pod lib lint    
// LocalizableUI passed validation.
git add -A && git commit -m "Release 0.3.5."
git tag '0.3.5'  
git push --tags 
pod trunk push LocalizableUI.podspec 
// ... 🎉  Congrats...

## What did you expect to happen?

The documentation at https://cocoapods.org/pods/LocalizableUI should be the same as visible in GitHub https://github.com/weiss19ja/LocalizableUI

## What happened instead?

The documentation athttps://cocoapods.org/pods/LocalizableUI is not updated

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.2 (17C205)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2_1/lib
Repositories : adesso-mobile-podspecs - ssh://git@scm.adesso-mobile.de:7999/pods/podspecs.git @ 5c033f7eb3df84545751635db2313110281bc16f
               master - https://github.com/CocoaPods/Specs.git @ b75ffb1a6ee1d1467471cef415e306dd9705a0b1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.4
```

## Project that demonstrates the issue

https://cocoapods.org/pods/LocalizableUI

**Comment by Monntay** [comment]
curl http://207.254.41.223:4567/redeploy/LocalizableUI/latest fixed the issue

**Comment by sisoje** [comment]
what id the new ip for redeploy?

**Comment by sisoje** [comment]
anyone?
