### ISSUE TITLE
Pod won't update on cocoapods.org

### ISSUE THREAD

**Issue by xmari0** [CocoaPods/CocoaPods#7324]
# Report

## What did you do?

I recently turned my library from being an alpha version to an actual release by changing the tag from "1.0.7.alpha" to "1.0.0"

## What did you expect to happen?

I expected it would change the version on cocoapods.org aswell. It still shows that it's on version 1.0.7.alpha. The readme.md is far far behind aswell. Updated it few times but it doesn't update.

## What happened instead?

It still shows that it's on version 1.0.7.alpha. The readme.md is far far behind aswell. Updated it few times but it doesn't update.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f14ac3f44f6c1032c7d912d9c4947e9c188cbfe1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
`1.0.7.alpha` is greater than `1.0.0` in semantic versioning - so it is being used instead. At this point you'd need to ship `1.0.8` to update the README.

**Comment by dnkoutso** [comment]
what @orta said
