### ISSUE TITLE
Cocoapods.org do not update github stats

### ISSUE THREAD

**Issue by amichnia** [CocoaPods/CocoaPods#7325]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Submitted new version of library via `pod trunk push`.

## What did you expect to happen?

Readme, changelog, version, github stats updated.

## What happened instead?

Version is partially updated (not in search results), readme not, changelog not, github stats as well.  I know this is not happening immediately, but it seems that at least github stats did not changed for last 2-3 releases.

## Project that demonstrates the issue

[https://cocoapods.org/pods/SwiftyMocky](https://cocoapods.org/pods/SwiftyMocky)

**Comment by orta** [comment]
Hi there, this is an issue that should be on another repo, this repo is only for CocoaPods the command line tool - and it only is for bug reports and feature requests. Please re-create your issue on the right repo so that the correct people will be highlighted to it 👍
