### ISSUE TITLE
How to ignore single pod when use pod update?

### ISSUE THREAD

**Issue by allen8300** [CocoaPods/CocoaPods#7329]
When we use pod update, cocospod will update all pod of podfile.
Also we can use pod update frameworkname1 to update only frameworkname1.

However, if i want to also dont update framework1，I have to use pod update framework2,framework3,framework4,...... 

Any way can do like pod update -ignore framework1 this?

**Comment by dnkoutso** [comment]
Use 'pod update <pod_name>'

**Comment by dnkoutso** [comment]
Comma separated too can help you update mutlitple pods at once

**Comment by dnkoutso** [comment]
Sorry space separated

**Comment by allen8300** [comment]
@dnkoutso 
Dear man, seems you didn't get my point, please don't hurry closing the question before it's really solved. ☺

Can you re-read my title?
