### ISSUE TITLE
Is there any way to specify “latest” version for a pod library?

### ISSUE THREAD

**Issue by adriano-di-giovanni** [CocoaPods/CocoaPods#7332]
According to the [docs](http://guides.cocoapods.org/using/the-podfile.html) you can use the latest version of a pod library by simply omitting its version in the podfile.

Is there any way to use the latest version by specifying something like `+` or `*` or `latest`?

**Comment by dnkoutso** [comment]
Not currently but what is the reason you want this?

**Comment by adriano-di-giovanni** [comment]
It is one of the two possible solutions to an issue I'm facing with cordova.

**Comment by dnkoutso** [comment]
So can you use no version way?

**Comment by adriano-di-giovanni** [comment]
I have to set version using a preference. Preferences are mandatory and they can't have blank defaults otherwise they are considered missing.

**Comment by dnkoutso** [comment]
I think you can use '> 0'?

**Comment by adriano-di-giovanni** [comment]
Thanks for the hint. I'm going to try.

**Comment by dnkoutso** [comment]
I think we can close this. Please respond again if you have additional thoughts and i can re-open
