### ISSUE TITLE
How to ignore a single pod when using 'pod update' ?

### ISSUE THREAD

**Issue by allen8300** [CocoaPods/CocoaPods#7334]
When we use pod update, cocospod will update all pod of podfile.
Also we can use 'pod update < framework1 >' to update only framework1.

However, if I don't want to update framework1，then I have to do it like this:
'pod update framework2, framework3, framework4,......'
But it's really fool, isn't it?

So, any other smart way that I can ignore a single pod when using 'pod update' ?
Brainstorming, like 'pod update -ignore framework1' ?

I've asked [here](https://github.com/CocoaPods/CocoaPods/issues/7329),  but it's closed without solving my problem.

**Comment by dnkoutso** [comment]
@allen8300 thanks for re-filing this again, I was going to-reopen your other issue. Anyway we keep this one now. 

This might be a good enhancement. Feel free to make a PR if you'd like to add it. I will mark it as easy.

**Comment by allen8300** [comment]
@dnkoutso  Thanks so much man；
So for now, any idea or work around about this case?

**Comment by dnkoutso** [comment]
it shouldnt be hard to write a ruby script around this by re-using existing model classes, see this http://www.rubydoc.info/github/CocoaPods/Core/master/Pod/Podfile

**Comment by dnkoutso** [comment]
Sorry I mean https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/lockfile.rb

**Comment by allen8300** [comment]
@dnkoutso 
Yes, thanks, will check your reference;
How about modifying Podfile by script? (adding or removing a line of code)
Do you have any suggestion or guidance about how to do this?

**Comment by dnkoutso** [comment]
there are many ways to edit a file. @allen8300 I positive StackOverflow is a much better forum for you to get help on how to do this. In the meantime I keep this open as it could be a good enhancement on the `pod update` command.

**Comment by amorde** [comment]
@allen8300 This has been implemented on master and will be released with CocoaPods version `1.5.0` - please see https://github.com/CocoaPods/CocoaPods/pull/7524 for details on the new feature
