### ISSUE TITLE
Pod lib lint: xcodebuild: error: The workspace named "App" does not contain a scheme named "MyProject".

### ISSUE THREAD

**Issue by scottire** [CocoaPods/CocoaPods#7336]
* [✅] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run  `pod lib lint --skip-import-validation --verbose --no-clean`

## What did you expect to happen?
Lint the project successfully

## What happened instead?
There is an error at the  `Building with xcodebuild` step.

```Building with xcodebuild. 
xcodebuild clean build -workspace /var/folders/7t/pzxxc43531z94d11xvjhjw7c0000gn/T/CocoaPods-Lint-20180116-3230-hvhdp6-MyProject/App.xcworkspace -scheme MyProject -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=E466A27A-2F6B-4DB2-A1C3-645CD3E52826
Build settings from command line:
    CODE_SIGN_IDENTITY = -
    SDKROOT = iphonesimulator11.2

xcodebuild: error: The workspace named "App" does not contain a scheme named "MyProject". The "-list" option can be used to find the names of the schemes in the workspace.
   Testing with xcodebuild. 
 -> MyProject (2.3.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: The workspace named "App" does not contain a scheme named "MyProject". The "-list" option can be used to find the names of the schemes in the workspace.
```

```xcodebuild clean build -workspace /var/folders/7t/pzxxc43531z94d11xvjhjw7c0000gn/T/CocoaPods-Lint-20180116-3230-hvhdp6-MyProject/App.xcworkspace -scheme MyProject -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=E466A27A-2F6B-4DB2-A1C3-645CD3E52826```

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.4
        Host : Mac OS X 10.13.1 (17B1003)
       Xcode : 9.2 (9C40b)
         Git : git version 2.6.2
Ruby lib dir : /Users/scottire/.rvm/rubies/ruby-2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 54b623b82dcffd3d00e699c2c856d5e447f53b98
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[Project](https://github.com/flomio/flomio_mw_releases/blob/master/FlomioSDK.podspec)

**Comment by dnkoutso** [comment]
Thanks for the report will investigate.

**Comment by dnkoutso** [comment]
@scottire confirmed. The issue arises due to the combination of `--skip-import-validation` and lack of any sources in your pod.

As a workaround you can add a `Dummy.m` file inside the `FlomioSDK/Classes` folder to bypass the issue.

```
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --timestamp=none /Users/dimitris/Library/Developer/Xcode/DerivedData/App-eordolmcxgazmkeyizlfkaumrihn/Build/Products/Release-iphonesimulator/FlomioSDK/FlomioSDK.framework

** BUILD SUCCEEDED **

   Testing with xcodebuild. 
 -> FlomioSDK (2.3.0)
```
