### ISSUE TITLE
podspec: `header_mappings_dir` does not preserve path prefixes.

### ISSUE THREAD

**Issue by dcow** [CocoaPods/CocoaPods#7338]
Despite specifying `header_mappings_dir = subspec_src_dir`, the header paths are not preserved when the headers are added to the framework nor do the imports in the umbrella header reflect the paths. 

For example:

```
:= Example.podspec
s.subspec {
    ss.header_mappings_dir = 'src'
    ...
}

:= src
+-- a/foo.{m,h}
+-- b/bar.{m,h}

:= b.h
#import <a/foo.h>

:= Main podfile
pod 'Example', :path => 'Example'

:= Main app
@import Framework
+-- umbrella header imports b.h which imports a/foo.h
```

This will fail because `foo` ends up in `Framework/Headers` directly. Shouldn't the paths be preserved, or am I misunderstanding something here?

**Comment by dnkoutso** [comment]
can you please provide a sample project here?

**Comment by dcow** [comment]
I will do that when I get a chance.

**Comment by dnkoutso** [comment]
@dcow once you provide a sample I will re-open.

**Comment by dcow** [comment]
Okay. Perhaps stale bot should be a little more flexible... it's only been 8 days.

**Comment by mrousavy** [comment]
@dcow did you find a solution for this?

I currently have two headers with the same name:

```
ABC.h
lib/Core/Some.h
lib/iOS/Core/Some.h
```

And the one in the `iOS` folder tries to import the one in the other folder, but it doesn't work since the `Core/Some.h` import does not work 🤨
