### ISSUE TITLE
how to solve follow problem Mac 10.13.2 

### ISSUE THREAD

**Issue by Runtomorrow** [CocoaPods/CocoaPods#7339]
GemWrappers: Can not wrap missing file: pod
GemWrappers: Can not wrap missing file: sandbox-pod
Successfully installed cocoapods-1.3.1
Parsing documentation for cocoapods-1.3.1
Done installing documentation for cocoapods after 2 seconds
1 gem installed

**Comment by dnkoutso** [comment]
Please use the template and file an issue with proper instructions and a sample project for us to reproduce.

We cannot work with this information. Additionally consider asking Stackoverflow first with the cocoapods tag.
