### ISSUE TITLE
Contents of README.md not updated on CocoaPods Website

### ISSUE THREAD

**Issue by herzi** [CocoaPods/CocoaPods#7341]
* [x] I've read and understood the *[CONTRIBUTING guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md)* and have done my best effort to follow.

# Report

## What did you do?

We published a cocoa pod several months ago and have regularly released new versions. In the mean time the content of the file `README.md` contained in out zip archive changed.

## What did you expect to happen?

I would expect https://cocoapods.org/pods/AATKit to reflect the contents of the latest `README.md`. There may be multiple definitions of “latest”, however I don't mind if it's the latest beta's content or the latest stable's. All I expect for the content is to be updated given a certain set of preconditions (like a new release to trunk).

## What happened instead?

The content of the updated `README.md` will not be reflected on the cocoa pods website.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.6 (16G1114)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/herzi/.brew/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0e3e0f9c16a604fc943449cd3a7dfe0b1cb1b768
```

### Installation Source

```
Executable Path: /Users/herzi/.brew/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project

target 'AATKitResources' do
  platform :ios, '7.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AATKitResources

end

target 'IntentInspector' do
  platform :ios, '9.3'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntentInspector
  pod 'FBAudienceNetwork', '< 4.22'
end

target 'IntentKit' do
  platform :ios, '7.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IntentKit
  pod 'ANPreBidMobileForDFP', '2.4.7'   # TODO: Update version number in driver class manually.
  pod 'FBAudienceNetwork', '< 4.22'
  pod 'Google-Mobile-Ads-SDK', '7.26.0'
  #pod 'ANPreBidMobileForMoPub', '2.4.7' # TODO: Update version number in driver class manually.

  target 'IntentKit Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by orta** [comment]
Hi there, this is an issue that should be on another repo, this repo is only for CocoaPods the command line tool - and it only is for bug reports and feature requests. Please re-create your issue on the right repo so that the correct people will be highlighted to it 👍

**Comment by herzi** [comment]
I was really thinking about where to file this bug. I haven't found a list or something like that. Could you please tell me which component is the right one? „CocoaPods the Website“ doesn't feel right, neither does „CocoaPods Trunk Authentication Server“.

**Comment by orta** [comment]
No worries, in theory it's about https://github.com/CocoaPods/cocoapods.org but making an issue will re-direct you to https://github.com/CocoaPods/cocoadocs.org
