### ISSUE TITLE
CocoaPods removes SWIFT_VERSION from config file

### ISSUE THREAD

**Issue by revolter** [CocoaPods/CocoaPods#7344]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I tried updating `CocoaLumberjack` to version `3.4.0` from `3.0.0`.

## What did you expect to happen?

Successfully build the project.

## What happened instead?

Project build fails with error:

> The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

### Stack

```
   CocoaPods : 1.4.0.rc.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 04144d8b6067aa7200c00668ea290e70961b89fc
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

target 'AppName' do
	use_frameworks!

	pod 'Fabric'
	pod 'Crashlytics'

	pod 'FirebaseUI/Auth'
	pod 'FirebaseUI/Facebook'

	pod 'FLEX', '~> 2.0', :configurations => ['Debug']
	pod 'CocoaLumberjack/Swift'

	pod 'AlamofireImage'

	pod 'Result'

	target 'AppNameTests' do
		inherit! :search_paths
	end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |configuration|
			configuration.build_settings['SWIFT_VERSION'] = '3.2'
		end
	end
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

This happens because the `SWIFT_VERSION = 3.0` gets removed by CocoaPods when running `pod install` from `Pods-AppName.debug.xcconfig`.

**Comment by dnkoutso** [comment]
![screen shot 2018-01-17 at 11 23 02 am](https://user-images.githubusercontent.com/310370/35062399-0d295d9a-fb79-11e7-90d8-2e4195f5939f.png)

This seems to be working fine for me and I can successfully build a project that consumes `CocoaLumberjack/Swift` can you please upload a sample app?

**Comment by revolter** [comment]
It looks the same for me too, but in my app's project settings, it's missing:

![screen shot 2018-01-17 at 21 26 31](https://user-images.githubusercontent.com/5748627/35062571-60d7efb6-fbcd-11e7-86c4-d44bc0f033ad.jpg)

**Comment by dnkoutso** [comment]
@revolter in my sample app I have set Swift Version to 4.0 and I do not see it being overridden or removed.

**Comment by dnkoutso** [comment]
@revolter I do not think CocoaPods sets your apps `SWIFT_VERSION` ever in the generated `Pods-AppName.debug.xcconfig`

**Comment by revolter** [comment]
I think that an older version (~1 year ago) of CocoaPods was adding `SWIFT_VERSION` to that config file, but now it removes it, so I just had to set it from `Xcode` on the target instead of expecting it to come from the config file.

**Comment by dnkoutso** [comment]
hm maybe! I do not recall :)

Either way it is correct to set it for yourself in your own project, cocoapods avoids editing this for you.
