### ISSUE TITLE
[Question] My pod redirect to github page, and docs are not available

### ISSUE THREAD

**Issue by Berk-Kaya** [CocoaPods/CocoaPods#7347]
Hello, I have published <a href="https://cocoapods.org/pods/C2Alert" target="_blank">C2Alert</a> but CocoaPods redirect me to its github page, and when I click docs it gives me 404 error. Any ideas?

**Comment by dnkoutso** [comment]
File an issue with https://github.com/CocoaPods/cocoadocs.org
