### ISSUE TITLE
Cannot import pod in classes of development pod

### ISSUE THREAD

**Issue by ulayuno** [CocoaPods/CocoaPods#7350]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I added the " s.dependency 'Alamofire' " to the podspec file.

## What did you expect to happen?

When importing Alamofire into a class of the development pod, it would find it.

## What happened instead?

Error appears: "No such module".

Sorry for opening an issue here, I have just tried everything I know and it is still not working.

**Comment by segiddins** [comment]
Please share a sample project that reproduces the issue, thanks!

**Comment by dnkoutso** [comment]
+1 or the issue will eventually be auto closed.

**Comment by ulayuno** [comment]
I already fixed it.

Thanks for answering.
