### ISSUE TITLE
subspec with static_framework

### ISSUE THREAD

**Issue by west0r** [CocoaPods/CocoaPods#7355]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

How can i make podspec with both of static and dynamic version of my library? When i describe static subscpec and run `pod lib lint`, cocoapods gives an error message

# Report

## What did you do?
pod lib lint
## What did you expect to happen?
no errors
## What happened instead?
```
ERROR | attributes: Can't set `static_framework` attribute for subspecs (in `Library/Static`).
```
### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.2
Ruby lib dir : /Users/west0r/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fcdd2a4ccf6191bdada028572f1076241d0bb7d7
```

### Installation Source

```
Executable Path: /Users/west0r/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-keys        : 2.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

```
Pod::Spec.new do |s|
  # Some dynamic library spec 
  s.subspec 'Static' do |ss|
      # Some static library podspec
      ss.static_framework = true
  end
end
```

**Comment by dnkoutso** [comment]
I don't think you can. Subspecs are only subparts of a single library target, they are not separate targets.

This is a root only DSL.

@paulb777 please confirm and close issue if the above is true.

**Comment by paulb777** [comment]
Confirmed. subspecs only determine what pieces go into a library.  A dynamic or static specification only makes sense for the entire library.

**Comment by erkanyildiz** [comment]
What if there are `Core` and `Optional` subspecs, and only `Optional` subspec has a static dependency. 

If I only want `Core` it can be dynamic, but if I want `Optional` too, then it has to be static.

Something like this:

```
Pod::Spec.new do |s|

  s.name = 'AnExample'
  s.version = '1.0'
  s.default_subspecs = 'Core'

  s.subspec 'Core' do |core|
    core.source_files = '*.{h,m}'
  end

  s.subspec 'AdditionalFeatures' do |af|
    af.dependency 'AnExample/Core'
    af.dependency 'HereIsAStaticDependency'
    af.static_framework = true # this could be useful here
  end
  
end
```

**Comment by iHTCboy** [comment]
@erkanyildiz Finally, is there any good way?

> What if there are `Core` and `Optional` subspecs, and only `Optional` subspec has a static dependency.如果有 和 subspecs，并且只有 subspec 具有静态依赖关系怎么办。
> 
> If I only want `Core` it can be dynamic, but if I want `Optional` too, then it has to be static.如果我只想，它可以是动态的，但如果我也想要，那么它必须是静态的。
> 
> Something like this: 像这样：
> 
> ```
> Pod::Spec.new do |s|
> 
>   s.name = 'AnExample'
>   s.version = '1.0'
>   s.default_subspecs = 'Core'
> 
>   s.subspec 'Core' do |core|
>     core.source_files = '*.{h,m}'
>   end
> 
>   s.subspec 'AdditionalFeatures' do |af|
>     af.dependency 'AnExample/Core'
>     af.dependency 'HereIsAStaticDependency'
>     af.static_framework = true # this could be useful here
>   end
>   
> end
> ```
