### ISSUE TITLE
Discovered undocumented feature of Podfile DSL

### ISSUE THREAD

**Issue by mwoollard** [CocoaPods/CocoaPods#7359]
* [✅] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Discovered that you can use `:source` with `pod` statement but this is not documented in the Podfile Reference Guide (as discussed in #7354)

## What did you expect to happen?

Documentation to reflect the Podfile DSL accurately.

Creating this issue to track PR for documentation fix I'll submit to keep it separate from #7354.

**Comment by dnkoutso** [comment]
👍
