### ISSUE TITLE
How to include files into main class?

### ISSUE THREAD

**Issue by Karmadon** [CocoaPods/CocoaPods#7364]
# Report

In example all builds and working

## What did you do?

 `pod spec lint`

## What did you expect to happen?

pass validation

## What happened instead?

    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | [iOS] xcodebuild:  SwiftyNominatim/SwiftyNominatim/Classes/Nominatim.swift:21:57: error: use of undeclared type 'ReversePayload'
    - ERROR | [iOS] xcodebuild:  SwiftyNominatim/SwiftyNominatim/Classes/Nominatim.swift:26:46: error: use of unresolved identifier 'ReversePayload'

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 76aede2178684c353af16385e257b442de72d01b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/Karmadon/SwiftyNominatim

**Comment by dnkoutso** [comment]
This seems like a user error with the build, not a CocoaPods issue with the library. The error message shows this. Are you missing an `s.dependency` in your podspec?

Sorry going to close this as it does not appear a CocoaPods library issue.

**Comment by Karmadon** [comment]
I know that is not a CocoaPods issue
it would be better to help ((
I have only two files in Classes folder, in single file all works

**Comment by dnkoutso** [comment]
@Karmadon recommend posting to StackOverflow for advise
