### ISSUE TITLE
Xcode 9.3 beta 1 new recommended settings

### ISSUE THREAD

**Issue by kdawgwilk** [CocoaPods/CocoaPods#7365]
Xcode 9.3 beta 1 was just released with some new recommended settings that CocoaPods will need to add for the Pods generated project
![screen shot 2018-01-24 at 12 56 57 pm](https://user-images.githubusercontent.com/7799267/35355552-dfebb50c-010a-11e8-9475-d387b468dabe.png)
![screen shot 2018-01-24 at 12 56 51 pm](https://user-images.githubusercontent.com/7799267/35355553-e00fc3fc-010a-11e8-8105-c2e6c889d10d.png)

**Comment by dnkoutso** [comment]
Thank you for the report, we will fold your issue into this existing issue https://github.com/CocoaPods/CocoaPods/issues/7206 for Xcode 9.x.

Closing as "dup".
