### ISSUE TITLE
Mixpanel SDK no longer compiles with 1.4

### ISSUE THREAD

**Issue by kdawgwilk** [CocoaPods/CocoaPods#7367]
As you can see in this issue mixpanel/mixpanel-iphone#764 Mixpanel no longer compiles with CocoaPods 1.4.  I verified that dropping the version back to 1.3 did in fact fix the issue and it does.  This seems like a breaking change or bug not sure which the right answer.

**Comment by dnkoutso** [comment]
![screen shot 2018-01-25 at 10 14 53 am](https://user-images.githubusercontent.com/310370/35404659-9a9c7262-01b8-11e8-8be4-8d0ae8412e2a.png)

I successfully compiled it with 1.4.0

**Comment by dnkoutso** [comment]
@kdawgwilk please use the template to file issues and providing a sample app can help immensely with the debug process

**Comment by dnkoutso** [comment]
Can also compile it as a static library.
