### ISSUE TITLE
Errno::ENOENT - No such file or directory @ realpath_rec - /Users/zhaotianwei/Documents/iOS Src/5miles-ios-client/Vendor/ForestDB/FILE_LICENSE

### ISSUE THREAD

**Issue by orghostcoder** [CocoaPods/CocoaPods#7370]
Errno::ENOENT - No such file or directory @ realpath_rec - /Users/zhaotianwei/Documents/iOS Src/5miles-ios-client/Vendor/ForestDB/FILE_LICENSE
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/project.rb:190:in `realpath'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/project.rb:190:in `realpath'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/project.rb:190:in `add_file_reference'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:122:in `block (3 levels) in add_developer_files'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:120:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:120:in `block (2 levels) in add_developer_files'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:115:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:115:in `block in add_developer_files'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:142:in `message'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:114:in `add_developer_files'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb:43:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:163:in `install_file_references'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
Seems like an issue not finding the license file. Either way I am sorry but I am going to close this one as we cannot work with such a report.

Please use the template and re-open a new issue providing a sample app.
