### ISSUE TITLE
Pod update color indications not colorblind friendly

### ISSUE THREAD

**Issue by sendoa** [CocoaPods/CocoaPods#7372]
# Report

## What did you do?

Run `pod outdated`

## What did you expect to happen?

I'd expect the color representing the different update consequences would be more colorblind friendly.

## What happened instead?

I can't tell aparte between green and yellow. Perhaps substitute green or yellow with blue?

Thank you!

**Comment by iv-mexx** [comment]
I think it would make as much sense to use blue instead of yellow, I can provide a PR

**Comment by dnkoutso** [comment]
👍 go for it!

**Comment by dnkoutso** [comment]
Makes me wonder if we should a more comprehensive solution across the board for being colorblind friendly.....

**Comment by segiddins** [comment]
> Makes me wonder if we should a more comprehensive solution across the board for being colorblind friendly.....

Exact colors are set by the terminal application -- I'm not sure there's much that we can do on our end, since the ANSI escape sequences just specify "blue", "red", etc, rather than specific RGB values.

**Comment by iv-mexx** [comment]
Maybe like color profiles where all "yellow" is replaced by "blue"... (and other replacements for other types of color blindness)?

**Comment by orta** [comment]
Yeah, the mapping of the name `"red"` to `RBG(255,0,0)` that's a per-terminal option (e.g. https://github.com/mbadolato/iTerm2-Color-Schemes#batman which makes it a yellow)

I think this is a good example of something we should fix, as the majority of the time we're only really using white/green/red

**Comment by dnkoutso** [comment]
The change was merged.
