### ISSUE TITLE
binary code was lost when  using static framework!

### ISSUE THREAD

**Issue by Goosoul** [CocoaPods/CocoaPods#7374]
* [] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I tried to make a libxxx.a to be static framework  on my project, so I modifed the podspec of lib using 's.static_framework = true' and enabled 'use_framework' in Podfile.
Also I clean Xcode Cache, pod install ... anyhow I compiled success and run the app. 
Unexpectedlly: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[XXXX YYYY]: unrecognized selector sent to class 
I use Hopper to check execute file and find almost code or symbols lost, however the static framework is normal. I guess something wrong when link the framework.

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.13 (17A360a)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : gxpods - https://git.coding.net/Gxthird/gxpods.git @ 5a63274f1f3f8671d7d53a6566aa39b1a2bd3937
               master - https://github.com/CocoaPods/Specs.git @ 0b352fb68dc36bb16a90fdd774a29ce867761087
               pinpods - https://git.assembla.com/pinpods.git @ b57e98c5ece0eb62c4ec76b7067cdddbe1c60e4c
               uaexpods - https://git.coding.net/uaex/Specs.git @ 1af1e9c50d212937c32cefca9f4e919aefc7ee2b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

O__O "…

**Comment by dnkoutso** [comment]
Please provide a sample app to debug this. It is very difficult for us to figure out what's wrong without one

**Comment by paulb777** [comment]
The use case of using a `static_framework` to wrap a binary static library is not one I intended to support with the 1.4.0 implementation. 

It's something that could be considered, but I would have thought the `vendored_frameworks` podspec attribute to be sufficient.

**Comment by Goosoul** [comment]
I add other linker flags -ObjC to fixed the crash (prevent striping code...🙃), BUT
ld: warning: Auto-Linking supplied '.../ABC.framework/ABC', framework linker option at '.../ABC.framework/ABC' is not a dylib, a pile of undefined symbols 😂😂😂

**Comment by dnkoutso** [comment]
@paulb777 anything from our side to do here?

**Comment by Goosoul** [comment]
Finally, I found my workmate given me a custom template project but not set $(inherited) in Other Linker Flags at main project.(I add flags in static framework before but not notice it 😂😂😂).Thank your help~ @paulb777  @dnkoutso 👍👍👍
