### ISSUE TITLE
Pod install mess with : one workspace with multiple projects with different relative paths.

### ISSUE THREAD

**Issue by dperetti** [CocoaPods/CocoaPods#738]
Consider this layout :
    platform :ios, '5.1'

```
xcodeproj 'Core/App1' do
    target App1
end

xcodeproj 'Core/PlugIns/MyPlugIn' do
    target MyPlugIn
end
```

Apparently, there is a unique PODS_ROOT used, and the last defined target wins. The other one gets a wrong path.

**Comment by vijaytholpadi** [comment]
@foobar8675 That helped me get started on something I was trying out. Thanks!

**Comment by ignaciov** [comment]
In case that someone happens the same that happened to me :)

I was working in a project with other developer and I had this issue.

What happened in my case was that the other developer had renamed the project and when I did a pull I ended with two .xcodeproj:

nameBeforeRename.xcodeproj
nameAfterRename.xcodeproj

Then when I was running pod install or pod update I get the message "Could not automatically select an Xcode project."

The solution was to just delete the old .xcodeproj and then run pod install.

**Comment by arindamIos** [comment]
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
    project 'TestProject.xcodeproj'   <- *******(Need to mention protect name)**********

target 'BaalDahab' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestProject
  

pod 'Test_POd'
end
