### ISSUE TITLE
How to create a pod lib which dependency libraries is shipped by npm

### ISSUE THREAD

**Issue by SuperMarioBean** [CocoaPods/CocoaPods#7386]
I wonder how to create a pod lib which its dependency libraries is shipped by npm, just like React Native and Code Push.

In my pod lib .podspec file I can not use the `path` and also I can not control the npm to update or install package.json.

Any ideas?

**Comment by dnkoutso** [comment]
you cannot use `:path` within podspecs. The only way around it is having a `Podfile` that specifies where each dependency comes from. But even if you do that this still means you cannot publish your podspec for remote consumption by others.

Please use Stackoverflow under `cocoapods` tag for these kind of questions and how to work around them.

As this is not a cocoapods library issue in terms of how the library functionally works. I am going to 
close.

If you feel there could be an enhancement here (although I do not think we will support `:path` dependencies in podspecs) please do make a case and I can re-open.
