### ISSUE TITLE
resource_bundles: append resources to the same bundle in subspec

### ISSUE THREAD

**Issue by Goosoul** [CocoaPods/CocoaPods#7387]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

In my podspec:

....
```
s.resource_bundles = {
    'node_modules' => ['node.bundle/{node_modules}/{core}']
  }

  s.subspec 'Express' do |ss|
    ss.resource_bundles = {
      'node_modules' => ['node.bundle/{node_modules}/{express}']
    }
  end
```
....

## What did you expect to happen?

I want to combine these resources in one bundle node_modules.bundle just like (node install)

## What happened instead?

node_modules.bundle just contains the last resource with replacement. 

## CocoaPods Environment

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.13.4 (17E139j)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Use the root level declaration of the resource bundle. Subspecs do not generate a separate target, instead they are just are being added to the single target generated.

Something like:

```
s.resource_bundles = { 'node_modules' => ['node.bundle/{node_modules}/{core,express}'] }
```

Please use StackOverflow for these kind of questions, if there is an actual bug in cocoapods library I will re-open this issue.

**Comment by dnkoutso** [comment]
If you do find a bug please also include a sampleapp demonstrating the issue.

**Comment by Jon889** [comment]
@dnkoutso That doesn't work because the express resources will be included even if the Express subspecies is not included.
