### ISSUE TITLE
GCC_PREPROCESSOR_DEFINITIONS[config=Release]

### ISSUE THREAD

**Issue by kingslay** [CocoaPods/CocoaPods#7388]
in podspec 
```
	s.xcconfig = {
		"GCC_PREPROCESSOR_DEFINITIONS[config=Release]" => "$(inherited) NDEBUG=1"
		} 
``` 
have not   effect

**Comment by dnkoutso** [comment]
Use `s_pod_target_xcconfig` the one you are using is for the user target.

Also please use StackOverflow for these kind of questions.

**Comment by kingslay** [comment]
in podspec
`	s.pod_target_xcconfig = {
		"GCC_PREPROCESSOR_DEFINITIONS[config=Release]" => "NS_BLOCK_ASSERTIONS NDEBUG=1",
		"GCC_PREPROCESSOR_DEFINITIONS[config=Release][sdk=iphonesimulator*]" => "NS_BLOCK_ASSERTIONS NDEBUG=1",
		"GCC_PREPROCESSOR_DEFINITIONS[config=Release][sdk=iphoneos*]" => "NS_BLOCK_ASSERTIONS NDEBUG=1"
	  }`
but the result is 
![image](https://user-images.githubusercontent.com/3964055/38910666-0da0aba4-42fd-11e8-9d56-618a031edf89.png)
