### ISSUE TITLE
 ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

### ISSUE THREAD

**Issue by hownaskie** [CocoaPods/CocoaPods#7390]
![screen shot 2018-02-02 at 11 59 53 am](https://user-images.githubusercontent.com/6029968/35716026-1647e2c6-0811-11e8-912f-04978911a527.png)
Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
   Testing with xcodebuild. 
 -> CSChatLibrary (0.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

Pods workspace available at `/var/folders/6w/f9v9fkl56tg6xvxf8gypblbr0000gp/T/CocoaPods-Lint-20180202-3228-13phea-CSChatLibrary/App.xcworkspace` for inspection.

[!] CSChatLibrary did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0/lib/cocoapods/command/lib/lint.rb:85:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0/lib/cocoapods/command/lib/lint.rb:54:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0/lib/cocoapods/command/lib/lint.rb:54:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
![screen shot 2018-02-02 at 12 00 15 pm](https://user-images.githubusercontent.com/6029968/35715966-b016f730-0810-11e8-8aaa-7b30ec4a1f29.png)

How to fix this error? I tried to set SWIFT_VERSION but i cant find that on the build so i just added a user-defined setting, but unfortunately the error still exist

**Comment by dnkoutso** [comment]
please use the template of the issue and provide a sample app demonstrating the issue.

Use CocoaPods 1.4.0 and set `s.swift_version` to your podspec in order to set `SWIFT_VERSION` attribute.

At this time this issue does not appear a CocoaPods library issue, StackOverflow under the `cocoapods` tag is a better forum to ask these questions.

Going to close and will re-open if this proves to be a CocoaPods issue.
