### ISSUE TITLE
Can't build pod with deployment target of iOS 4.x when using Xcodeproj 1.5.5

### ISSUE THREAD

**Issue by vincentisambart** [CocoaPods/CocoaPods#7391]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I'm not sure if that should be considered a bug of CocoaPods, Xcodeproj, or even a podspec problem.

Starting from Xcodeproj 1.5.5 (PR: CocoaPods/Xcodeproj#541), the project generated by Xcodeproj (so also CocoaPods) has `CLANG_ENABLE_OBJC_WEAK` set to `YES`.

Unfortunately, when using a pod that has a deployment target version of iOS 4.x (for example [UICKeyChainStore](https://github.com/kishikawakatsumi/UICKeyChainStore) – [podspec](https://github.com/kishikawakatsumi/UICKeyChainStore/blob/master/UICKeyChainStore.podspec)), building the pod fails with the following error:
```
clang: error: -fobjc-weak is not supported on the current deployment target
```

If you change manually the deployment target in Pods.xcodeproj to 5.0 everything builds properly.

I could probably just ask the developer of `UICKeyChainStore` to update the podspec file, but there might be other podspecs with this deployment target. So it might be better to fix that on the CocoaPods side. CocoaPods could either set `CLANG_ENABLE_OBJC_WEAK` to false if the deployment target is too old, or change the deployment target to iOS 5.0 if it's less than that (or even set it to the deployment target of the project it's linked to). What do you think?

## What did you do?

- Create a new "Single View App" iOS project in Xcode (I'm using Xcode 9.2).
- Create the following `Podfile`:

```ruby
platform :ios, '9.0'
target 'MyProject' do
  pod 'UICKeyChainStore'
end
```

- Make sure you have Xcodeproj 1.5.5 installed (`gem update xcodeproj` or using a `Gemfile`).
- Run `pod install`.
- Open and build the project in Xcode.

## What did you expect to happen?

- The project should build successfully.

## What happened instead?

- Xcode failed with the following error:
```
clang: error: -fobjc-weak is not supported on the current deployment target
```

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.16.1
Ruby lib dir : /Users/vincent-isambart/.rbenv/versions/2.4.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c0f1c78a9902ae8e4a6dc43d99854f6c71a28d5b
```

### Installation Source

```
Executable Path: /Users/vincent-isambart/.rbenv/versions/2.4/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.4
```

**Comment by dnkoutso** [comment]
Honestly I think asking the developer is best here. iOS 4 was released 8 years ago. Understood your point though some devs haven't updated their podspecs and we could possibly do something from the cocoapods side but I think it will be a "losing" battle for us to litter the codebase with conditionals to handle such old versions.

Will keep this issue open for a few days if someone wants to weigh in, if you think talking to the developer will speed things up feel free to close!

**Comment by dnkoutso** [comment]
also thank you for the great report.

**Comment by dnkoutso** [comment]
Also CocoaPods does not exactly touch the value `CLANG_ENABLE_OBJC_WEAK` its only get set as the default from the Xcodeproj gem since it was updated to work with Xcode 9.x

**Comment by vincentisambart** [comment]
@kishikawakatsumi Would it be possible to increase the deployment target specified in UICKeyChainStore's podspec to at least iOS 5.0?

**Comment by dnkoutso** [comment]
@vincentisambart one more thing, you can also "fork" the podspec and republish it internally in your own git repo by changing the deployment target if the library has been abandoned.

**Comment by dnkoutso** [comment]
*or* a `post_install` hook can edit this target to change its deployment target.

**Comment by vincentisambart** [comment]
@dnkoutso I'll do one of those if the author doesn't reply, thanks.

**Comment by dnkoutso** [comment]
If you do not mind I will close this since we do not plan to make any changes on our side. If we do or something else changes I will re-open;.

**Comment by segiddins** [comment]
This should be fixed now with Xcodeproj master, which I'd like to release as 1.5.6 tonight

**Comment by dnkoutso** [comment]
Back reference to https://github.com/CocoaPods/Xcodeproj/pull/546

**Comment by vincentisambart** [comment]
Worked fine, thank you @segiddins!
