### ISSUE TITLE
Incorrect Frameworks paths

### ISSUE THREAD

**Issue by nawar** [CocoaPods/CocoaPods#7392]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Wrong framework paths with a fresh project and pod installation. Unknown error is encountered upon building for the device

## What did you do?

- Created a new project
- Initiated a PodFile
- Run "Pod install"

## What did you expect to happen?
 Install all pod dependencies correctly.

## What happened instead?

Incorrect paths for frameworks are included in the project navigator instead. The build fail for unknown error 
`/Users/nawar/Library/Developer/Xcode/DerivedData/Poder-csqhkuqrhojwmxghnxsazqqcdqkj/Build/Products/Debug-iphoneos/Poder.app/Frameworks/CocoaAsyncSocket.framework: unknown error -1=ffffffffffffffff`

which I suspect because it is looking for the *.framework in the wrong directory of the derivedData

![screen shot 2018-02-02 at 8 42 03 am](https://user-images.githubusercontent.com/928095/35734720-779fd006-07f8-11e8-92cf-38fbc5cfff14.png)

When clicking on any of those it shows the wrong path

![screen shot 2018-02-02 at 8 42 13 am](https://user-images.githubusercontent.com/928095/35734740-8ad7307e-07f8-11e8-94d4-c9cf1371a5af.png)

It should be under `.../Debug-iphoneos/{frameworkname}/{frameworkname}.framework`

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b44c615e8043534fb23293f513d8f1d446b18028
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Poder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Poder
  pod 'Fabric'
  pod 'Crashlytics'
  # XMPP
  pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'
  # Google
  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/Calendar'
  # Microsoft
  pod 'MSGraphSDK'
  pod 'MSGraphSDK-NXOAuth2Adapter'

  # Tooltip
  # pod 'EasyTipView', '~> 1.0.2' # this is the original
  pod 'EasyTipView', :git => "https://github.com/igorkislyuk/EasyTipView", :branch => 'master' # swift-4 support
  # KeyChain
  # pod 'SwiftKeychainWrapper'

  # Snackbar from Android for connectivity
  pod 'MaterialComponents/Snackbar'

  # Checkbox
  pod 'UICheckbox.Swift'

end
```

## Project that demonstrates the issue

https://file.io/IeGwbO

**Comment by dnkoutso** [comment]
![screen shot 2018-02-02 at 10 39 27 am](https://user-images.githubusercontent.com/310370/35749127-5cfb6c1c-0805-11e8-8044-5386a5a04d12.png)

Works for me right out of the box, have you done a clean build? I am also on Xcode 9.2

**Comment by nawar** [comment]
No worries Dimitris, for some reason, a clean machine restart solved it as it was only building for the simulator but not for the device. After narrowing the problem down, I found out that it has nothing to do with CocoaPods.
