### ISSUE TITLE
Setting up a Swift podspec that depends on an Objective-C pod

### ISSUE THREAD

**Issue by shoumikhin** [CocoaPods/CocoaPods#7396]
# Report

## What did you do?

See [below](#project-that-demonstrates-the-issue)

## What did you expect to happen?

See [below](#project-that-demonstrates-the-issue)

## What happened instead?

See [below](#project-that-demonstrates-the-issue)

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.7.4
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.16.0.rc1.238.g530d649a79-goog
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4702daf0beb8370381efec67ecd825c456111b0c
```

### Installation Source

```
Executable Path: $HOME/.ruby/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

We have a [Promises](https://github.com/google/promises) library that provides both an [Objective-C](https://github.com/google/promises/tree/master/Sources/FBLPromises) framework and a [Swift](https://github.com/google/promises/tree/master/Sources/Promises) module. We currently have a [Podspec](https://github.com/google/promises/blob/master/PromisesObjC.podspec) set up for our ObjC library, but would also like to set up a [Podspec](https://gist.github.com/temrich/438e97a674557f48e252f13d24186f2d) for our Swift module (which would have a dependency on the ObjC pod).  Unfortunately, we run into the following errors:

-  "Could not build Objective-C module `FBLPromises`" --> when trying to test the `PromisesSwift` pod in a Swift project locally
- "Target Support Files/PromisesObjC/PromisesObjC-umbrella.h:13:9: error: include of non-modular header inside framework module 'FBLPromises'". --> when running `pod lib lint PromisesSwift.podspec`

We suspect that part of the issue is a result our [custom module map](https://github.com/google/promises/blob/master/Sources/FBLPromises/include/module.modulemap#L1) not specifying "framework module" in the module declaration. However, adding "framework" to our module map breaks the builds for both [Bazel](https://github.com/google/promises/blob/master/BUILD) and [Swift PM](https://github.com/google/promises/blob/master/Package.swift). We would really like to support CocoaPods for our Swift module, but haven't been able to come up with a solution to resolve the errors mentioned above. Any help that the CocoaPods team can provide would greatly be appreciated!

Thank you!

**Comment by dnkoutso** [comment]
thank you for the nice writeup and detailed explanation. I haven't verified myself so I am keeping this open and will add labels as I dig further.

**Comment by paulb777** [comment]
This may be a factor:  A supplied umbrella header doesn't get copied into the `pod lib lint`s `Target Support Files` directory and the search paths don't seem to be used to search for the umbrella header from the module map - which is copied there.  It seems that module maps expect umbrella header's to be in the same directory and that doesn't happen with the PromisesObjC.modulemap. It's not able to find the umbrella FBLPromises.h. 

 I do get the `pod lib lint` environment to build if I manually add the absolute path to the `User Header Search Paths` of the App's settings.  I wasn't able to find an environment variable that could find it's way back to the original pod's sources though.

**Comment by shoumikhin** [comment]
Thank you for taking a look, Paul!
Is that something we could fix on our end? Also, note that the [umbrella header](https://github.com/google/promises/blob/master/Sources/FBLPromises/include/FBLPromises.h) itself seems to be located at the correct place along with all other headers, and we also provide a [symlink](https://github.com/google/promises/blob/master/FBLPromises.h) to it at the repo root to facilitate `#import` statement.

**Comment by paulb777** [comment]
I dug a bit deeper today. In CocoaPods, the `module` and `framework` concepts are intertwined.  And until the future 1.5.0, both are always needed for Swift.  The module_map option overrides the module map that gets built into the FBLPromises.framework with a module map without the "framework" string and that leads to the lint validation issues.

We actually successfully include a non-framework module map in the [Firebase pod](https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/4.8.2/Firebase.podspec.json#L35). However, that is a wrapper pod that does not include any sources.  When I try to do something similar for FBLPromises, I run into build conflicts between the source and build artifacts.

Here are some possible next step directions:

1. Consider eliminating the custom module map. Is there any reason CocoaPods can't generate the correct module map with the right public and private header specifications?
2. Restructure pod structure with a wrapper pod like the Firebase pod with a subspec to the pod containing the sources.
3. Add a pre-build phase to add the "framework" prefix to the module map.
4. Learn more about CocoaPods and contribute to making module map handling more complete.

**Comment by shoumikhin** [comment]
Many thanks for the details, Paul!
I guess we don't currently specify any custom module map in PromisesObjC.podspec. But we need that module map for Bazel and SwiftPM without "framework" prefix, though. Do you get those issues when set `module_map` in ObjC spec and then try to lint it? What do you see when try to use the existing ObjC podspec and the [Swift podspec](https://gist.github.com/temrich/438e97a674557f48e252f13d24186f2d) that depends on it?

**Comment by paulb777** [comment]
Yep - I was working with the previous version of the ObjC podspec that you had previously asked me about. It looks like there was a subsequent commit that removed the `module_map` from the podspec.  I suspect the Swift podspec is a similar issue, but it may be a few days before I have time for more investigation.

**Comment by dnkoutso** [comment]
Again without having taking a deeper look you can always use [script_phases](https://guides.cocoapods.org/syntax/podspec.html#script_phases) to perform any custom operation during build.

**Comment by shoumikhin** [comment]
Seems like we managed to resolve the issue by flattening include/ directory. We used to have subdirs in it, so that some import statements looked like #import "Subdir/Header.h". But when a .framework created, the headers are copied to Headers/ and never preserve the directory structure. Curious if there're any workarounds, though.
Many thanks for taking a look, guys!

**Comment by shoumikhin** [comment]
I believe that's exactly what happens, unfortunately.

**Comment by daisyramos317** [comment]
I recently came across the same ordeal, has anyone else found other workarounds?

**Comment by shoumikhin** [comment]
Check out https://github.com/google/promises project structure and podspecs.

**Comment by daisyramos317** [comment]
Awesome! thanks for the quick response
