### ISSUE TITLE
Adding the CoreLocation framework to my Podfile

### ISSUE THREAD

**Issue by Joseph310** [CocoaPods/CocoaPods#7401]
Hi, 

I added the `GoogleMobileAdsMediationMoPub` pod to my Podfile. Apparently this pod requires `CoreLocation`, which for some reason does not get added to my target's `Other Linker Flags`.

If I just compile the project, I get an error mentioning 
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CLLocation", referenced from:
     objc-class-ref in MoPubAdapter(GADMAdapterMoPub.o)
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
If I manually add `-framework` and `"CoreLocation"` to the `Other Linker Flags` Xcode can compile the project without a problem.

My Podfile also has `use_frameworks!`, but is there a way for me to manually add `CoreLocation` to the Podfile so that it will be added? I'd prefer not to edit the Other Linker Flags manually, so that they can be used by CocoaPods as is. 

Thanks for any tips. 
-Joseph

**Comment by dnkoutso** [comment]
Either add `s.frameworks = 'CoreLocation'` in the podspec if you control it or manually add it to your app target in your .xcodeproj.

CocoaPods does not provide means to manipulate the linker or framework paths within the `Podfile`.
