### ISSUE TITLE
--- pod lib lint ----I have a third party Frameworks, but this Frameworks doesn't support simulator. 

### ISSUE THREAD

**Issue by sdzwb89** [CocoaPods/CocoaPods#7403]
I have a third party Frameworks, but this Frameworks doesn't support simulator. What do I need to do to put the Frameworks in my private cocoapods library?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by sdzwb89** [comment]
ok,thanks
