### ISSUE TITLE
Custom framework with multiple target | pod integration issue

### ISSUE THREAD

**Issue by amitvolansystech** [CocoaPods/CocoaPods#7405]
We have developed a Custom framework in iOS which has multiple targets. Each target gives a different (Example SDK1,SDK2,SDK3) SDK. We have also uploaded the same on Github with below podspec.

    Pod::Spec.new do |s|
          #1.
          s.name               = "CustomFramework"
          #2.
          s.version            = "1.0.1"
          #3.  
          s.summary         = "Sort description of 'CustomFramework' framework"
          #4.
          s.homepage        = "http://www.customframework.com"
          #5.
          s.license              = "MIT"
          #6.
          s.author               = "Test Author"
          #7.
          s.platform            = :ios, "10.0"
          #8.
          s.source              = { :git => "https://abc.com/xxxx/CustomFramework.git", :tag => "1.0.1" }
          #9.
          s.source_files     = "CustomFramework", "CustomFramework/**/*.{h,m,swift}"
     end

To add this sdk in project, we have written below code in pod file.

   ` pod 'CustomFramework',:git=>'https://abc.com/xxxx/CustomFramework.git'
`
But it always fetch the SDK which are belongs to first target (SDK1).

**Comment by dnkoutso** [comment]
This seems like a question to ask in Stackoverflow under the `cocoapods` tag. 

IIRC `pod 'CustomFramework',:git=>'https://abc.com/xxxx/CustomFramework.git'` will checkout the master branch of your git repo instead.

Use maybe pod 'CustomFramework',:git=>'https://abc.com/xxxx/CustomFramework.git', :tag => '1.0.1'` 

etc.

I do not believe this is a cocoapods library issue or have not understood if an enhancement is required here so I am going to close it.

**Comment by gorbat-o** [comment]
Hello guys,

I am encountering the same issue,
I am using libraries which have multiple target for different settings (and different file used),

And I didn't find a way in Cocoapods to specify a particular target of my library.
Maybe I didn't read right the Cocoapods documentations, 

Thanks,
