### ISSUE TITLE
'ModuleName-Swift.h' file not found when Swift and OC mixed

### ISSUE THREAD

**Issue by wangjindong** [CocoaPods/CocoaPods#7413]
My English is poor!But I have an unsolvable problem。

cocoapods:1.4.0

I add spec.static_framework = true to the spec。

OC can not import 'ModuleName-Swift.h'  when the static framework contains swift.

demo is [here](https://github.com/wangjindong/SwiftAndOc/tree/master)

**Comment by paulb777** [comment]
Thanks for the report and test case.

Looks like a duplicate of #7213. See that issue for a workaround.

I'll take a look at this test case when a fix is ready to try as well.

**Comment by dnkoutso** [comment]
Dup of #7213

**Comment by wangjindong** [comment]
@dnkoutso @paulb777  oh，thanks！
