### ISSUE TITLE
Swift pod dependent static_library error

### ISSUE THREAD

**Issue by tanhuiya** [CocoaPods/CocoaPods#7415]
I use `pod lib create` a Swift project. 
It contains `.a` static libraries
When I run `pod lib lint --allow-warnings --use-libraries`
It fails with following:

```
- ERROR | [iOS] unknown: Encountered an unknown error (Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pods being used are: Alamofire, Differentiator, Kingfisher, Moya, PictureBook, Result, RxBlocking, RxCocoa, RxDataSources, RxOptional, RxSwift, SnapKit, SwiftyJSON, and Then
```

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.6.2
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/tanhui/.rvm/rubies/ruby-2.2.3/lib
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
The pods are you are depending on include swift which as of right now require to be built in a dynamic framework. Remove the ‘use libraries’ flag.

This will be possible with 1.5.0.

**Comment by tanhuiya** [comment]
The .a file is build in an OC_Pod from third part 
the problem is I can't pakage it to a framework , because I need the OC_Pod in another module via cocoapods.

**Comment by dnkoutso** [comment]
I am sorry I cannot understand what you are trying to do. Please upload a sample app and if its a CocoaPods bug I will re-open, but this doesn't sound like a CocoaPods library issue, maybe a limitation...

Either way it is best to ask these questions to StackOverflow under `cocoapods` tag.
