### ISSUE TITLE
Build operation failed without specifying any errors

### ISSUE THREAD

**Issue by karosLi** [CocoaPods/CocoaPods#7416]
# Report
When I archive with cocoapods 1.4.1, I met following error.
Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below.
## What did you expect to happen?
should archive successfully

## What happened instead?
Build operation failed without specifying any errors.

## CocoaPods Environment
using 1.4.1

## Workaround
if I using 1.3.1, I can archive successfully. 

So what 1.4.1 did do? it make the archive fail. Could you pls check this issue?

**Comment by dnkoutso** [comment]
This might be this https://github.com/CocoaPods/CocoaPods/pull/7384

Also the information you've provided is very little for us to debug. Please include a sample app demonstrating the issue. My gut tells me you have too many input/output paths and #7384 fixes the issue.

**Comment by nliz77** [comment]
Th

**Comment by dnkoutso** [comment]
@nliz77 
please provide correct information and a sample app demonstrating the issue also try #7384.

Going to close for now.
