### ISSUE TITLE
Acknowledgements generation: generate also a HTML file. No HTML file.

### ISSUE THREAD

**Issue by lolgear** [CocoaPods/CocoaPods#7420]
CocoaPods 1.4.0

https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements
https://github.com/CocoaPods/CocoaPods/issues/1817

No HTML file.
No RTF file.

**UPD:**
**CocoaPods 1.4.0**

**Comment by orta** [comment]
Hi, this is a too little information for us to understand what you're trying to do, can you create an exam[le repo that exhibits the problem you're seeing?

**Comment by lolgear** [comment]
@orta 

After pod installation:

```
ls Pods/Target\ Support\ Files/Pods-Mytarget/ | grep acknow

Pods-Mytarget-acknowledgements.markdown
Pods-Mytarget-acknowledgements.plist
```

No occurrences of .html or .rtf files ( which could be presented in native webview )

**Comment by dnkoutso** [comment]
There is no such version of CocoaPods 1.16.1? Please upload an example app clearly showing what is not working as expected.

**Comment by lolgear** [comment]
@dnkoutso my fault, I look at bundler version.

CocoaPods 1.4.0

**Comment by dnkoutso** [comment]
Still this is not helping. I am inclined to close this issue unless you provide more information and detailed explanation of what you expect to happen. Sounds like an enhancement or some sort.

**Comment by lolgear** [comment]
@dnkoutso 

well, I would like to have html version of markdown document "acknowledgements", which is autogenerated by CocoaPods.

However, related issues are closed due to upcoming releases.

**Comment by dnkoutso** [comment]
Sounds like an enhancement to be made. I will mark it as such. Feel free to contribute!

**Comment by orta** [comment]
Might be worth extending https://github.com/CocoaPods/cocoapods-acknowledgements

**Comment by dnkoutso** [comment]
Agreed!

**Comment by dnkoutso** [comment]
I'd argue this issue can move there...but meh its all about how the CocoaPods library works.

**Comment by orta** [comment]
Yeah, me too. Going to close this.

@lolgear I'm happy to re-open this if you're interesting in sending a PR?

**Comment by lolgear** [comment]
@orta I would like to know preferable solutions for it.

1. markdown to html converter?
2. html templates?
3. etc

Am I right that CocoaPods could generate acknowledgements locally without any remote server?

**Comment by orta** [comment]
cocoapods-acknowledgements already passes you the rendered [html of a library's description](https://github.com/CocoaPods/cocoapods-acknowledgements/blob/master/lib/cocoapods_acknowledgements/plist_generator.rb#L23-L33), so you may not need to do any work, just handle the plist it provides

**Comment by lolgear** [comment]
@orta, I think about nokogiri html builder. Is there any native/cocoapods html builders?
Xcodeproj has plist writing implementation which is reasonable for Xcode necessary files.

**Comment by orta** [comment]
You're welcome to improve the library 👍

**Comment by lolgear** [comment]
@orta how could this plugin be installed for development? (local path or custom GitHub url)
It has only mocks for tests, oh.

**Comment by lolgear** [comment]
@orta please, have a look at

https://github.com/CocoaPods/cocoapods-acknowledgements/pull/47
