### ISSUE TITLE
inhibit_all_warnings! doesn't cover // TODO: & // FIXME:

### ISSUE THREAD

**Issue by zachwhelchel** [CocoaPods/CocoaPods#7425]
inhibit_all_warnings! doesn't seem to cover // TODO: & // FIXME: warnings in my pods. Trying to get my warnings count down to my project only. Is there a fix for this?

**Comment by dnkoutso** [comment]
No, is there a build setting to handle this? Going to close preemptively and will re-open if there is a setting and CocoaPods can actually alter it.
