### ISSUE TITLE
[Suggestion] Treat private_header_files that matches nothing as Warning instead of Error

### ISSUE THREAD

**Issue by ZSaberLv0** [CocoaPods/CocoaPods#7427]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

when running `pod lib lint` with `private_header_files` that use wildcard but matches nothing,
a `pattern did not match any file` error would occur

Suggest to treat this as Warning instead of Error, because:

* missing private header files has no side effect for Pod users,
    for Pod developers, if really missed something important,
    surely would result compile error
* for Pod developers, since the podspec is Ruby files in fact,
    we may use Ruby functions to generate bunch of similar `subspec` declarations,
    when we want to ignore something by path componments (e.g. `**/private/*`),
    and if some of the `subspec`s does not have anything match,
    the `pattern did not match any file` error would occur,
    that's not convenient

the same thing also happens on `public_header_files`

**Comment by amorde** [comment]
@ZSaberLv0 Thanks for the suggestion! This will be released with CocoaPods 1.6.0
