### ISSUE TITLE
 - ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.     - NOTE  | xcodebuild:  lhFMDB/lhfmdb/lhfmdb/LHManage.h:9:9: fatal error: 'FMDB.h' file not found

### ISSUE THREAD

**Issue by saberLiuhui** [CocoaPods/CocoaPods#7429]
# ――― Source Code ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  CocoaPods is smart about how it includes source code. For source files
  #  giving a folder will include any swift, h, m, mm, c & cpp files.
  #  For header files it will include any header in the folder.
  #  Not including the public_header_files will make all headers public.
  #

  s.source_files  = "lhfmdb/lhfmdb/LHManage.h","lhfmdb/lhfmdb/LHManage.m"
  s.exclude_files = "Classes/Exclude"

  #s.public_header_files = "FMDB/**/*.h"

  # ――― Resources ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  A list of resources included with the Pod. These are copied into the
  #  target bundle with a build phase script. Anything else will be cleaned.
  #  You can preserve files from being cleaned, please don't preserve
  #  non-essential files like tests, examples and documentation.
  #

  # s.resource  = "icon.png"
  # s.resources = "Resources/*.png"

  # s.preserve_paths = "FilesToSave", "MoreFilesToSave"

  # ――― Project Linking ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  Link your library with frameworks, or libraries. Libraries do not include
  #  the lib prefix of their name.
  #

  # s.framework  = "SomeFramework"
  # s.frameworks = "SomeFramework", "AnotherFramework"

  # s.library   = "iconv"
  # s.libraries = "iconv", "xml2"

  # ――― Project Settings ――――――――――――――――――――――――――――――――――――――――――――――――――――――――― #
  #
  #  If your library depends on compiler flags you can set them in the xcconfig hash
  #  where they will only apply to your library. If you depend on other Podspecs
  #  you can include multiple dependencies to ensure it works.

  # s.requires_arc = true

  # s.xcconfig = { "HEADER_SEARCH_PATHS" => "$(SDKROOT)/usr/include/libxml2" }
   # s.dependency 'FMDB'

pod file :
platform :ios, '8.0'
target 'lhfmdb' do

#pod "FMDB"
pod 'FMDB'
pod 'lhFMDB', :path => '../../../lhFMDB'

end

**Comment by dnkoutso** [comment]
I am sorry but with this bug report we are unable to diagnose the issue. Please provide a sample app and use the issue template.
