### ISSUE TITLE
"pod install" not working 

### ISSUE THREAD

**Issue by BunnyImran** [CocoaPods/CocoaPods#7430]
i am facing issue with repo, i have tried everything from GitHub and stack-overflow and still nothing happens. Actually the master file is not being installed/created. No matter whatever I do, Please kindly guide or help me.
Thank You!

**Comment by BunnyImran** [comment]
![04k8d](https://user-images.githubusercontent.com/32432931/36094297-729a7fb0-100f-11e8-923a-059bcbd2c686.jpg)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by BunnyImran** [comment]
alright
