### ISSUE TITLE
[Meta] Addressing abandoned community projects

### ISSUE THREAD

**Issue by freak4pc** [CocoaPods/CocoaPods#7431]
This isn't a technical issue but more of a discussion. 

I'm one of the many people involved in the RxSwiftCommunity orgazniation (http://github.com/RxSwiftCommunity) where the community manages an assortment of RxSwift related OS projects. 

The problem is, the owners of some of the original repositories have entirely vanished and are not pushing new versions as they are built by the community. Since they have sole ownership over the Podspec, this leaves us - as a community - at a bit of a hostage situation. 

Usually I would resolve this by pinging the author, or even going as far as e-mailing them directly and asking them to add a secondary owner. We're also trying to establish better rules to resolve this kind of scenario (See https://github.com/RxSwiftCommunity/contributors/issues/44), cc @ashfurrow @orta 

The issue is, that even after all that, there are scenarios (not only in our repos) that the repo owner is not responsive via any means of communications after several attempt via all platforms (GitHub, Email, Twitter, etc), leaving us in a sticky position.

One of the repos suffering from this is RxGoogleMaps, where a new Podspec hasn't been released in about a year now. (A majority percentage of our issues are related to that: https://github.com/RxSwiftCommunity/RxGoogleMaps/issues?q=is%3Aissue+pod+is%3Aclosed) 

The only solution we can offer these users now, [is to directly link their Podfile to the repo and master branch](https://github.com/RxSwiftCommunity/RxGoogleMaps/issues/11#issuecomment-353971821), but that is not a good long-term solution. 

I wanted to open a discussion here regarding - how do we, as the CocoaPods community, think about solving this sort of scenario of project abandonment, in a community scenario.

Perhaps file for some "Abandonment" claim if the project is owned by an organization and the CocoaPod itself isn't, to transfer ownership if the original author is not responsive to CocoaPods itself? 

Would appreciate any and all of your thoughts!

Thanks
Shai

**Comment by orta** [comment]
Use the dispute system: https://trunk.cocoapods.org/claims/new

If you have write access to the repo, you would get access to the Podspec.

**Comment by freak4pc** [comment]
Wow I didn't even know that one exists :) Thanks Orta!
