### ISSUE TITLE
Transitive dependencies output their warnings during `pod trunk push`

### ISSUE THREAD

**Issue by mxcl** [CocoaPods/CocoaPods#7434]
🌈

* [ x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

    pod trunk push PromiseKit.podspec

## Description of Issue

The linting step output warnings for the transitive dependencies Bolts and OMGHTTPURLRQ. These are not warnings I can control, however any warnings cause the push to fail without specifying `--allow-warnings` and I don't want to get into the habit of always specifying this flag.
 
### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.16.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 728af8ad320b2b9e5c6fd50a685f492bd49b648c
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.4.0/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/mxcl/PromiseKit

**Comment by mxcl** [comment]
[pmk.log](https://github.com/CocoaPods/CocoaPods/files/1721519/pmk.log)

Attached the log.

**Comment by segiddins** [comment]
We could probably specify `inhibit_all_warnings!` to inhibit warnings for other pods, and disable it for the specific pod being linted?

**Comment by dnkoutso** [comment]
PR https://github.com/CocoaPods/CocoaPods/pull/7544
