### ISSUE TITLE
existing `.swift-version` shouldn't be an error

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/CocoaPods#7436]
# Report

## What did you do?

`pod trunk push`

## What did you expect to happen?

ignore the `.swift-version` instead. It's used not only by the CocoaPods. In my case it's used by the CI for Linux builds and it's not a most fortunate to remove it. 

## What happened instead?

ERROR | swift: Specification `CryptoSwift` specifies an inconsistent `swift_version` (`4.0`) compared to the one present in your `.swift-version` file (`4.0.3`). Please remove the `.swift-version` file which is now deprecated and only use the `swift_version` attribute within your podspec.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/marcinkrzyzanowski/.rvm/rubies/ruby-2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a05c3f0394cef32fffe9b88a87bd24ae2255085a
```

### Installation Source

```
Executable Path: /Users/marcinkrzyzanowski/.rvm/gems/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://travis-ci.org/krzyzanowskim/CryptoSwift/builds/341809786

**Comment by dnkoutso** [comment]
This file is more or less an "internal" API of CocoaPods. I think the fact you are relying on it in another process does not come with guarantee that it will always be there just as the warning suggests.

Another workaround is to parse the spec using CocoaPods, it is very easy.
```ruby
require 'cocoapods'
spec = Pod::Specification.from_file('CryptoSwift.podspec')
swift_version = spec.swift_version.to_s
```

I am going to close this one as I do not anticipate changing this, in fact the `.swift-version` file is going away in the future as the warning suggests and has been replaced with the `swift_version` DSL.

**Comment by krzyzanowskim** [comment]
But the `.swift-version` is for `swiftenv` tool, NOT for the CocoaPods.

**Comment by krzyzanowskim** [comment]
see https://github.com/kylef/swiftenv/issues/110

**Comment by dnkoutso** [comment]
ugh. didn't see anything in this report on `swiftenv`... might have to switch this from `error` to `warning`

**Comment by dnkoutso** [comment]
This will be "fixed" at a much later version (1.6.0+) when CocoaPods drops `.swift-version` file support entirely and there will be no need to warn or error out.

**Comment by krzyzanowskim** [comment]
@dnkoutso I see. Until then... can't release to the CocoaPods apparently

**Comment by orta** [comment]
In this case, you could disable the check by editing your cocoapods' source code. I do this for our React Native podspec.

Or by shipping a PR and using that fork

**Comment by dnkoutso** [comment]
Gonna move this to 2.0.0. Removing support for `.swift-version` will actually be a breaking change.
