### ISSUE TITLE
Issue with finding source files for private pod

### ISSUE THREAD

**Issue by trusk89** [CocoaPods/CocoaPods#7439]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
 
Tried to create a private pod

## What did you expect to happen?

Have the pod validated with ```pod spec lint mySDK.podspec```

## What happened instead?

```- ERROR | file patterns: The `source_files` pattern did not match any file.```

## CocoaPods Environment

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.2 (17C205)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9d0803da1c1d801c43f39065e26eeccda5d1872c
               mySDKPodspec - https://private/mysdk-podspec.git @ e323e8a0f5c813087191064006ac02e9a5f44623
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.4
```

## Project that demonstrates the issue

I don't have a project as it's an internal private company pod, but I have detailed the issue and what I've done [here](https://stackoverflow.com/questions/48809031/cocoapods-podspec-error-source-files-pattern-did-not-match-any-file?noredirect=1#comment84637852_48809031)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
