### ISSUE TITLE
A compiled ipa

### ISSUE THREAD

**Issue by Dershowitz011** [CocoaPods/CocoaPods#7444]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I opened xcodeworkspace, created an archive by building and renamed the .xcodearchive to .app. Put it in Payload folder and zipped the file using `zip -qr`. Signed and tried to install it . Please put up a compiled ipa so that we can download and sign and install. I'm on ios 11.2.5 iPhone 6s plus. DO oblige. Thanks.

## What did you expect to happen?

Install fine without any errors using `ios-deploy`.

## What happened instead?
 
`invalid signing identity.`

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1f17f05783731c9c6781ddeaeb90ddefdc6fcf4f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
I do not understand what you are trying to do and what does not work.

**Comment by Dershowitz011** [comment]
I opened pulse.xcodeworkspace and built it. It was fine. Then I archived it and changed .xcodearchive to .app. Next I covered it to an ipa by sipping if. I have a udid registered certificate. So I thought I’ll sign with that. But when I signed and tried to deploy the ipa to my idevice, it says invalid signing identity. My certificate works fine. Confirmed with other ipas. Please help. Thx.

**Comment by dnkoutso** [comment]
I am having a hard time understanding what you are trying to do, even so this does not seem a CocoaPods issue.

**Comment by Dershowitz011** [comment]
I am just trying to convert the Pulse.xcodeworkspace to pulse.ipa so that I can sign with my UDID registered certificate and install on my iPhone 6s Plus running iOS 11.2.5. When I sign and try to deploy using `iOS-deploy`, I get the error saying invalid signing identity.
