### ISSUE TITLE
Sub-targets missing install_framework, install_resource calls with Development Pods

### ISSUE THREAD

**Issue by knightcode** [CocoaPods/CocoaPods#7446]
* [ 🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Created a Podfile referencing Development Pods:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/Foo/FooPods.git'

platform :ios, '11.2'
use_frameworks!

workspace "Foo"

target 'App' do
    project 'App'
    pod 'PromiseKit/CorePromise', :inhibit_warnings => true
    pod 'FooKit', :path => '../FooKit'
    pod 'FooUI', :path => '../FooUI'
    target 'AppBeta' do
        inherit! :search_paths
    end
end
```

Ran `pod install`

## What did you expect to happen?

These two files should be identical:
```
./Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh
./Pods/Target Support Files/Pods-AppBeta/Pods-AppBeta-frameworks.sh
```

## What happened instead?

The Beta version of the script is missing the lines where all the magic happens:
```bash
if [[ "$CONFIGURATION" == "Debug" ]]; then
    install_framework "${BUILT_PRODUCTS_DIR}/PromiseKit/PromiseKit.framework"
    install_framework "${BUILT_PRODUCTS_DIR}/FooKit/FooKit.framework"
    install_framework "${BUILT_PRODUCTS_DIR}/FooUI/FooUI.framework"
fi
if [[ "$CONFIGURATION" == "Release" ]]; then
    install_framework "${BUILT_PRODUCTS_DIR}/PromiseKit/PromiseKit.framework"
    install_framework "${BUILT_PRODUCTS_DIR}/FooKit/SavoryKit.framework"
    install_framework "${BUILT_PRODUCTS_DIR}/FooUI/FooUI.framework"
fi
```

A similar problem occurs with the `install_resource` lines in the `-resources.sh` scripts, too... omitted here for brevity.

Switching from the Dev Pods to their versioned brethren from a spec repo seems to fix the problem. 

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 989552eeebf483cd81f9fd15d573d77552a5519d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Can you please provide a sample app demonstrating this? I believe you it happens but sample app speeds up velocity to resolve these tremendously.

**Comment by knightcode** [comment]
Yeah, it's a lot to set up, so I was hoping it'd be an obvious fix. I'll throw something together.

**Comment by knightcode** [comment]
https://github.com/knightcode/PodFail

**Comment by dnkoutso** [comment]
Will debug and figure this out for 1.6.0.

**Comment by segiddins** [comment]
I think this is intentional, since you have `inherit! :search_paths` set for the nested target. if you want the frameworks/resources to be linked against that target directly, you'll need to remove that line

**Comment by knightcode** [comment]
Thanks... that worked for the frameworks! 

But `install_resource` is still missing for FooUI's resource bundle

**Comment by dnkoutso** [comment]
@knightcode I do not think bundles support embedding frameworks. At least not in cocoapods perspective

**Comment by knightcode** [comment]
@dnkoutso  I updated the repo at https://github.com/knightcode/PodFail to remove `inherit! :search_paths` and both `Pods-App-resources.sh` and `Pods-AppBeta-resources.sh` have the lines for `install_resource "${PODS_CONFIGURATION_BUILD_DIR}/FooUI/FooAsset.bundle"` (in addition to the frameworks)

However, for my actual project, neither `pod install` nor `pod update` generates those lines in either resource script, i.e. those lines are missing from both targets' scripts. From what I can tell, after adding dependencies and frameworks to the podspecs, the only significant difference in either `podspec` or the `Podfile` is the inclusion of another private specs repos, e.g. `source 'https://github.com/Foo/FooPods.git'` in the Podfile of my actual project, which houses older versions of the two development pods included in my project. But commenting that line out of my Podfile had no effect.

So I don't know that I can recreate my problem for you now. Maybe, when you get a chance to look at it, you'll see something, but I get it if you want to close this one. I can add the lines manually every time I update.

**Comment by amorde** [comment]
@knightcode Can you try running `pod deintegrate` followed by `pod install` and see if that fixes the issue?

**Comment by knightcode** [comment]
@amorde no change.

**Comment by segiddins** [comment]
I think this is intentional -- because you're saying `inherit! :search_paths`, cocoapods is _not_ linking the frameworks into the beta target. I think you might want `inherit! :complete`

**Comment by gobetti** [comment]
I had this problem after updating from CocoaPods 1.5.3 to 1.6.1 - unsure if caused by the updated version or because someone manually edited something before and it ended up being replaced after the update. Replacing `inherit! :search_paths` by `inherit! :complete` as suggested by @segiddins did the trick. Thank you very much!

I'd be OK closing this issue :+1:

**Comment by knightcode** [comment]
I thought I replied to this, but I guess not. I'm pretty sure removing `inherit! :search_paths` worked for me as well, so I'm good with this getting closed as well.
