### ISSUE TITLE
Extract Swift Framework from Cocoapods Project ?!

### ISSUE THREAD

**Issue by Vinz1911** [CocoaPods/CocoaPods#7457]
Hello,

I try to extract my Swift Framework from a Cocoapods Project. I've started writing a Swift Framework and I needed to add some dependencies, so I created a Pods Project and continued working with the .xcworkspace file. Now I want to extract the framework to use it in other projects. How can I archive that ? Most tutorials I tried haven't worked for me :(

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
