### ISSUE TITLE
RuntimeError - [Xcodeproj] Unknown object version.

### ISSUE THREAD

**Issue by iwheelbuy** [CocoaPods/CocoaPods#7458]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod init` for a new project.

## What did you expect to happen?

`Podfile` should be created successfully.

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.4/lib/xcodeproj/project.rb:102:in `open'
/Users/admin/.gem/ruby/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:333:in `run'
/Users/admin/.gem/ruby/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Users/admin/.gem/ruby/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.3 (9Q107o)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 633f63ec268d45fa8c3f5771b961fadf98633e51
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[Tracker.zip](https://github.com/CocoaPods/CocoaPods/files/1755706/Tracker.zip)

## Reason to post an issue

I've read [this issue](https://github.com/CocoaPods/CocoaPods/issues/6991) and [this issue](https://github.com/CocoaPods/CocoaPods/issues/6992). They don't provide any working solution and they are closed. I tried doing all the steps [infinZero](https://github.com/infinZero) describes in his [solution](https://github.com/CocoaPods/CocoaPods/issues/6992#issuecomment-345656686) without any success. Also, I've read that the [owner](https://github.com/segiddins) of the repository [asks to share a sample project](https://github.com/CocoaPods/CocoaPods/issues/6991#issuecomment-361336918) so that the team will be able to investigate. Since I've just created an empty project which demonstrates the issue - I decided to share it.

**Comment by iwheelbuy** [comment]
I have found a temporary solution (inspired by this [pull request](https://github.com/CocoaPods/Xcodeproj/pull/253)). I made the project's format **Xcode 8.0-compatible** and **CocoaPods** started to work as expected. Turning it back to **Xcode 9.3-compatible** breaks `pod init` again.

**Comment by dnkoutso** [comment]
@iwheelbuy can you upgrade your xcodeproj gem to 1.5.6 and try again? I think this issue is already fixed.

**Comment by iwheelbuy** [comment]
@dnkoutso it helped!

**Comment by dnkoutso** [comment]
I take it as it was fixed? :)

Going to close this one as it has already been fixed with xcodeproj 1.5.6.

**Comment by Litlmoz** [comment]
Running `bundle update` will install the correct version of the xcodeproj gem dependency.

**Comment by veerChauhan** [comment]
get gem install cocoapods -pre

**Comment by twof** [comment]
@veerChauhan should be `gem install cocoapods --pre`

**Comment by hyperionstudios** [comment]
`gem update` fixed it for me after updaing xcode to the 9.3 (9E145)

**Comment by sauchye** [comment]
@twof thanks ,  it helped!

**Comment by lixiaodongdg** [comment]
@veerChauhan   According to you this solves my problem, thank you. command is  
Sudo gem install cocoapods --pre(mac OS 10.13.4  Xcode3)

**Comment by veerChauhan** [comment]
@twof Thanks, Fixed  that mistake
@lixiaodongdg  the more you get into a problem the more you become able to get rid of.

**Comment by caixindong** [comment]
Because `Rootless`, use `sudo gem install -n /usr/local/bin cocoapods --pre` better

**Comment by burla69** [comment]
You can use:  gem install cocoapods --pre --user
If you have "While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory" error

**Comment by Mattia541993** [comment]
@hyperionstudios it works also for Xcode beta 10 beta 4

**Comment by marlosirapuan** [comment]
> Because `Rootless`, use `sudo gem install -n /usr/local/bin cocoapods --pre` better

works here. Thank you.

**Comment by nunogoncalves** [comment]
This might help someone as well, 

I use RVM. 
Had to change the ruby version from which RVM is pointing to the system one. 
`rvm use system`
then I made `gem list xcodeproj` and I had two versions, (1.7.0 and 1.5.7). Removed the 1.5.7 and it started working.

**Comment by zhaiduo** [comment]
OMG, I encounter this in 2021... with cocoapods 1.9.1.

**Comment by nmtitov** [comment]
Same here, Xcode 13 beta

**Comment by Apanlin** [comment]
My project was created by Xcode13 ，My xcodeproj‘s version is 1.14.0
When I  use `pod update` ，show the same error
But I use `gem install xcodeproj` update xcodeproj to 1.21.0，then it is fixed！
Yeah~

**Comment by kongtianxintang** [comment]
Same Error
Update Pod To 1.11.2, fix this error

**Comment by CHENG-LIANG1** [comment]
Non of the above works, if you encounter this issue on 2021, with xcode version 13, you need to change the 'Project Format' to xcode-12 compatible

**Comment by mattstyles64** [comment]
> Non of the above works, if you encounter this issue on 2021, with xcode version 13, you need to change the 'Project Format' to xcode-12 compatible

This is the only thing that worked for me. You can change Project Format by going to the top-level App document which will be yourProjectName.xcodeproject

**Comment by AndyMomot** [comment]
I recommend update pod. It's worked for me.

sudo gem install -n /usr/local/bin cocoapods -v 1.8.4
