### ISSUE TITLE
vendored_frameworks don't include in all dependencies chain, only included in main project

### ISSUE THREAD

**Issue by akeTML** [CocoaPods/CocoaPods#7459]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Create pod library by adding a pod with `vendored_frameworks`

## What did you expect to happen?

Framework in `vendored_frameworks` should be included in pod library and pod example project

## What happened instead?

Framework in `vendored_frameworks` is included only in main project (example project), but not include in my pod library.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : Bethard_Specs - git@git.themobilelife.com:Bethard/iOS/Specs/Specs.git @ 8f91bbf831315e435fc7e0f3287a4e4f183637c3
               bitbucket-widespacegit-widespacepublicpodrepo - https://bitbucket.org/WidespaceGIT/widespacepublicpodrepo.git @ 808003fd9d5a4f9e3b3f11e6cbb4be15c9dc4c63
               master - https://github.com/CocoaPods/Specs.git @ 38923946284a81f5d06e11caf7aa11690d4a8003
               themobilelife-bthomeui - git@git.themobilelife.com:Bethard/iOS/BTHomeUI.git @ e5fccf85e02a24cd1ff5bac7cd23c7568469eef0
               themobilelife-specs - git@git.themobilelife.com:tma/ios/specs.git @ bb2453dbf1091e4e72f7bcb85a5f3fc01c2865b5
               themobilelife-specs-1 - git@git.themobilelife.com:tml/ios/specs.git @ ecd7b91030a02fa80f625b53bf5106712ac59e30
               themobilelife-specs-2 - git@git.themobilelife.com:tma/ios/clients/volaris/specs.git @ 99f9060db587d3ac8c6b3c7c687ab4bba69cc857
               themobilelife-tmldatabase - git@git.themobilelife.com:Administrator/tmldatabase.git @ 2ddfb852062284e5ccbc4fe42c524a19983fa4e9
               themobilelife-tmlioslibrary - git@git.themobilelife.com:Administrator/tmlioslibrary.git @ d8416280f3b11caa909787a675382dfb45f16219
               TML_BT - git@git.themobilelife.com:Bethard/iOS/Specs/Specs.git @ adb02c00f8c4e0576035a243e0433cffd3f1a49a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'TestVendoredFramework_Example' do
  pod 'TestVendoredFramework', :path => '../'

  target 'TestVendoredFramework_Tests' do
    inherit! :search_paths

    
  end
end
```

## Project that demonstrates the issue

This is the project that I can't compile because Firebase frameworks are not included in `TestVendoredFramework` pod, but I can use `Firebase` in `TestVendoredFramework_Example`. 
FirebaseCore use this
`"vendored_frameworks": [
    "Frameworks/FirebaseCore.framework"
  ],`
 https://www.dropbox.com/s/by4iohe2aoc5pqh/TestVendoredFramework.zip?dl=0

**Comment by paulb777** [comment]
It's not possible to link a static library from a vendored_framework into a dynamic library framework.

An alternative approach would be to use the CocoaPods 1.4.0 feature `static_framework` and make the `FirebaseCore` CocoaPod a dependency of your CocoaPod.  Examples in the podspecs at https://github.com/firebase/firebase-ios-sdk.

**Comment by akeTML** [comment]
Works thanks
