### ISSUE TITLE
Issue with external libraries (release, debug) without podspec linking to workspace (qa)

### ISSUE THREAD

**Issue by mabounassif** [CocoaPods/CocoaPods#7461]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expect to happen?

Expect external libraries without podspec but with only `realease` and `debug` configurations to properly bundle on a `qa` configuration.

## What happened instead?

The bundling happens properly for `release` and `debug` but when building for `qa` the external libraries are not linked.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.2 (17C205)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.1
Ruby lib dir : /Users/mahmoud/.rbenv/versions/2.4.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 83ae6b313b385aa06e824f87678c2c971c2adda3
```

### Installation Source

```
Executable Path: /Users/mahmoud/.rbenv/versions/2.4.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/mabounassif/CocoaPods-Issue7461

Stackoverflow question:
https://stackoverflow.com/questions/48349352/projects-dependencies-for-custom-configuration

**Comment by dnkoutso** [comment]
Please upload a sample app to demonstrate the issue. It makes it immensely easier to debug these issues.

**Comment by mabounassif** [comment]
@dnkoutso here's a sample project: https://github.com/mabounassif/CocoaPods-Issue7461

**Comment by dnkoutso** [comment]
perfect thanks, will try to debug.

**Comment by mabounassif** [comment]
@dnkoutso gentle reminder... I tried searching for clues in the documentation without any luck

**Comment by dnkoutso** [comment]
@mabounassif confirmed. This is a bug. The `qa` configuration is not propagated through the other `.xcodeproj` you have.

**Comment by dnkoutso** [comment]
@mabounassif this is actually not a CocoaPods bug. you need to go clone and add `Qa` configuration into your other `.xcodeproj` and then run `pod install` again.

Worked for me.

going to close this one.

**Comment by dnkoutso** [comment]
Add `Qa` into the `Info` tab of `RNRandomBytes.xcodeproj` etc.
