### ISSUE TITLE
Headers of development pod included via symlink get acl 'Project' instead of 'Public'

### ISSUE THREAD

**Issue by rmtmckenzie** [CocoaPods/CocoaPods#7463]
See #5790.

I'm not going to describe this too much more since it has been described already, but it is still definitely a bug. And since the Flutter framework has started using symlinks within their projects I would imagine this will become more relevant fairly quickly.

**Comment by dnkoutso** [comment]
Is this when you use frameworks or use static libraries?

**Comment by rmtmckenzie** [comment]
I'm seeing it with a static library.

**Comment by rmtmckenzie** [comment]
Well, to be precise - I have a pod that uses google's Mobile Vision pod which includes a static library as a framework, and because all sorts of things go wrong if I don't I'm using static_framework=true within my podspec.

**Comment by rmtmckenzie** [comment]
As noted in #5790, it is quite likely to be to do with https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L673.

**Comment by paulb777** [comment]
Seems the fix in #7165 might have been too narrow.
