### ISSUE TITLE
Our Cocoapods library page is redirected to github page

### ISSUE THREAD

**Issue by leo1980** [CocoaPods/CocoaPods#7465]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Then release our library by issuing command below,
$> git add -A && git commit -m "Release 0.9.4"
$> git tag '0.9.4'
$> git push --tags
$> pod lib lint AIQKit.podspec
$> pod trunk push AIQKit.podspec

then I got output,

:tada:  Congrats

:rocket:  AIQKit (0.9.4) successfully published
:date:  February 5th, 09:48
:earth_americas:  https://cocoapods.org/pods/AIQKit
:+1:  Tell your friends!

## What did you expect to happen?
When I access AIQKit page,
https://cocoapods.org/pods/AIQKit

I should see page for it.

## What happened instead?

But reality is that I was redirected to github page 
https://github.com/iqnect-org/aiqkit-ios

I can found the AIQKit from cocoapods page search, and I can use AIQKit by adding AIQKit into Podfile

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 713cb9c62547df8651141d41b306b6c42c182fdd
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/iqnect-org/aiqkit-ios

**Comment by orta** [comment]
Hi there, this is an issue that should be on another repo, this repo is only for CocoaPods the command line tool - and it only is for bug reports and feature requests. Please re-create your issue on the right repo so that the correct people will be highlighted to it 👍

**Comment by leo1980** [comment]
could you tell which is right repo?

**Comment by orta** [comment]
CocoaPods.org

**Comment by leo1980** [comment]
thanks. I posted it to stackoverflow. Can I invite you to give some hint overthere
https://stackoverflow.com/questions/49102306/our-cocoapods-library-page-is-redirected-to-github-page
