### ISSUE TITLE
72 duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by quietautumn** [CocoaPods/CocoaPods#7466]
I ran into a problem when I was using CocoaPods，When I use Product=>Archive pack IPA，failed,
like this.

(https://user-images.githubusercontent.com/16301518/36717230-404cad92-1bd8-11e8-9106-e6be0d2d6cb0.png)
,But everything else is normal and will not make a mistake.
Xcode version：9.3
CocoaPods is latest version.

**Comment by amorde** [comment]
Can you upload an example project that demonstrates the issue?

**Comment by quietautumn** [comment]
@amorde @dnkoutso thanks ,The problem has been solved, and it is a lack of a dependency in other demo instances.
