### ISSUE TITLE
avoiding xcodebuild "clean build"

### ISSUE THREAD

**Issue by igordeoliveirasa** [CocoaPods/CocoaPods#7469]
Is there any way to remove clean build parameter from xcodebuild?

**Comment by dnkoutso** [comment]
why? when you lint we should always ensure the environment is clean to ensure the library builds from scratch.

Needless to say each lint invocation now uses a different temp folder so you wouldn't gain any speed from this.

My recommendation is to use `--no-clean` and then open the generated workspace and work from there if you want to ensure the job works without constantly invoking `lint`.

Additionally you can temporarily change the source of `validator.rb` in your setup to remove the clean command.

I do not see what we can do here in the library itself so I am going to close the issue. Feel free to comment further and if something comes up I can re-open.

**Comment by igordeoliveirasa** [comment]
@dnkoutso alright. Since my podspec only copies project files, ignoring tdd files, how could I test the project before pushing process?

**Comment by dnkoutso** [comment]
At the moment this is not as easy...you can create a simple empty app and include a `Podfile` that points to your podspec using `:path` directive, if I understand 100% what you are tryin to do.

**Comment by igordeoliveirasa** [comment]
I'm just running "xcodebuild test" before calling pod push... However, since I've already built the project because of the tests, I thought I could take part in of that build process, however, I noticed that pod push uses another directory and it's impossible to take part in, right?
