### ISSUE TITLE
Is this a beautiful thing to do?

### ISSUE THREAD

**Issue by igordeoliveirasa** [CocoaPods/CocoaPods#7471]
I don't know if I am using correctly but I guess it's a bit weird to create a tag and push it and only after this to publish a package. Let's suppose the publishing step does not work? A tag was created erroneously. I tried to lint before creating tag but, it also needs to point to a remote repo, which is the tag previously created..

I need some tips.

Thanks.

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
