### ISSUE TITLE
how to fix "undefined method `pod' for #......" when call pod command in a custom ruby class inside a ruby file instead of podfile

### ISSUE THREAD

**Issue by crespoxiao** [CocoaPods/CocoaPods#7476]
## What did you do?

I create a file named XXXModule.rb., Add a class and some functions for the class, then called pod command  in the function, check the code below.

`
#!/usr/bin/ruby

class XXXModulePods
    
    def loadPods_PhoneOnly()
        pod 'FLEX', '~> 2.0', :configurations => ['Debug']
        puts "load commonPods phoneOnly pods"
    end

    def loadPods_HDOnly()
        puts "load commonPods HDOnly pods"
    end
    
end
`

In podfile , load this ruby file and create an Object to call these functions.

`
load "../RetailModules/RetailCommon/XXXModule.rb"
xxxModule=XXXModulePods.new()

workspace "RetailHD"
target "RetailCommon" do
    project '../RetailModules/RetailCommon/RetailCommon.xcodeproj'

    target "RetailHD" do
        project 'RetailHD.xcodeproj'
        xxxModule.loadPods_HDOnly()
    end
    
    target "Retail" do
        project '../Retail/Retail.xcodeproj'
        xxxModule.loadPods_PhoneOnly()
    end

end
`
 

## What did you expect to happen?

My workspace contains many module , each  developer in charge different module.
So I decide  to create a ruby file for each module, the developer add pods inside it to avoid modify the podfile regularly.

## What happened instead?

when run 'pod update', theres an error "[!] Invalid `Podfile` file: undefined method `pod' for #<XXXModule:0x00007f81a90bd330>."

What should I do ? Add require or include inside the ruby files would  make it works ? 
Please help me to fix it, thank you !

**Comment by segiddins** [comment]
That's a method on the `Podfile` class, not a global method

**Comment by crespoxiao** [comment]
@segiddins  I tried and failed. Finally  i quit and use an easy way ,this solution is too complex and hard to maintain. thank you anyway.
