### ISSUE TITLE
POD install oh! no issue occured

### ISSUE THREAD

**Issue by RameshSain** [CocoaPods/CocoaPods#7477]
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
/Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/gh_inspector-1.1.2/lib/gh_inspector/sidekick.rb:67:in `url_for_request': uninitialized constant GhInspector::Sidekick::ERB (NameError)
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/gh_inspector-1.1.2/lib/gh_inspector/sidekick.rb:24:in `search'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/gh_inspector-1.1.2/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/gh_inspector-1.1.2/lib/gh_inspector/inspector.rb:59:in `search_exception'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:67:in `report_error'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `run'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:23:in `load'
	from /usr/local/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
Sorry please use the template for issues.
