### ISSUE TITLE
url_for_request': uninitialized constant GhInspector::Sidekick::ERB (NameError)

### ISSUE THREAD

**Issue by RameshSain** [CocoaPods/CocoaPods#7478]
I am getting this issue while installing pods .

	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/gh_inspector-1.1.2/lib/gh_inspector/sidekick.rb:24:in `search'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/gh_inspector-1.1.2/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/gh_inspector-1.1.2/lib/gh_inspector/inspector.rb:59:in `search_exception'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:67:in `report_error'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `run'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
	from /Users/macmini/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
	from /Users/macmini/.rbenv/versions/2.1.0/bin/pod:23:in `load'
	from /Users/macmini/.rbenv/versions/2.1.0/bin/pod:23:in `<main>'
Macs-Mac-mini:ios macmini$ `url_for_request': uninitialized constant GhInspector::Sidekick::ERB (NameError)

its after update the pod .

My pod file is look like this :-
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ESNext' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'NewRelicAgent'
   pod 'Firebase', '~> 4.0.0'
#   pod 'Firebase/Crash'
#   pod 'Firebase/Performance'
pod 'Fabric', '~> 1.7.5'
pod 'Crashlytics', '~> 3.10.1'
#   pod 'React', path: '../node_modules/react-native', :subspecs => [
#   'Core',
#   'RCTActionSheet',
#   'RCTGeolocation',
#   'RCTImage',
#   'RCTLinkingIOS',
#   'RCTNetwork',
#   'RCTSettings',
#   'RCTText',
#   'RCTVibration',
#   'RCTWebSocket'
#   ]
#   
#   
#    pod 'GoogleMaps'
#    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
#    pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'

#  pod 'RSKImageCropper'
#  pod 'QBImagePickerController'
#pod 'react-native-fetch-blob',
#:path => '../node_modules/react-native-fetch-blob'
  # Pods for ESNext

end
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == "react-native-google-maps"
#            target.build_configurations.each do |config|
#                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#            end
#        end
#    end
#end

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by umwelt** [comment]
On Xcode, I had changed Project Document -> Project Format to Xcode 10. Rolled back to 9.3 and then I'm able to install again
