### ISSUE TITLE
user .composer does not exist error found during Pod Setup --verbose

### ISSUE THREAD

**Issue by ndoctor13** [CocoaPods/CocoaPods#7484]
I am running the most latest version (1.4.0) of cocoapods but I can't seem to set it up correctly. Whenever I run "Pod setup --verbose", I am getting the below error. No other command seems to work. They all give the same error message. I am not sure what is going on. 

````
ArgumentError - user .composer doesn't exist
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/executable.rb:93:in `expand_path'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/executable.rb:93:in `block in which'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/executable.rb:92:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/executable.rb:92:in `which'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/executable.rb:110:in `which!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/executable.rb:49:in `execute_command'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/executable.rb:27:in `block in executable'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command/repo/add.rb:71:in `block in clone_repo'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command/repo/add.rb:69:in `chdir'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command/repo/add.rb:69:in `clone_repo'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command/repo/add.rb:41:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command/repo/add.rb:39:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command/setup.rb:54:in `add_master_repo'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command/setup.rb:27:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command/setup.rb:21:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.1.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment]
From the log it does not seem you run 1.4.0. It says 1.1.0.

**Comment by ndoctor13** [comment]
Sorry I downgraded it to see if older version would work. Here is the error log from 1.4.0

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:93:in `expand_path': user .composer doesn't exist (ArgumentError)
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:93:in `block in which'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:92:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:92:in `which'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:110:in `which!'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/executable.rb:133:in `capture_command'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:116:in `git_version'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:128:in `verify_minimum_git_version!'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:49:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'

**Comment by dnkoutso** [comment]
Have no idea sorry.

**Comment by segiddins** [comment]
what happens when you run `ruby -e 'p [Dir.home, File.expand_path("~"), Dir.pwd, ENV["USER"]]' ?

**Comment by ndoctor13** [comment]
Did you mean to run it in the Ruby/Gems directory? Below is what I get when I run it in the actual directory. I don't think this is what you were looking for.

Nishants-MacBook-Pro:cocoapods nishantdoctor$ ruby -e 'p [Dir.home, File.expand_path("~"), Dir.pwd, ENV["USER"]]'
["/Users/nishantdoctor", "/Users/nishantdoctor", "/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods", "nishantdoctor"]

**Comment by ndoctor13** [comment]
``

**Comment by dnkoutso** [comment]
@ndoctor13 something seems messed up with your PATH. Is it possible to print it out?
