### ISSUE TITLE
pod lib lint sometimes file not found sometimes success

### ISSUE THREAD

**Issue by songjianboy** [CocoaPods/CocoaPods#7485]
when i run command  pod lib lint in terminal,sometimes get results fatal error:  file not found and sometimes success. 

When I bulid with /var/folders/w6/rfc115f94691psp4vvtqkqyw0000gn/T/CocoaPods/Lint/App.xcworkspace  it was successful.

Please help me.

**Comment by dnkoutso** [comment]
Sorry we cant work with this bug report. Please use the template and provide a sample app with clear instructions as to why things did not work.
