### ISSUE TITLE
How can I improve app launch time(Pre main) time when I am using both objective-c as well as swift framework.

### ISSUE THREAD

**Issue by rohitntsnewscorp** [CocoaPods/CocoaPods#7491]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹI am trying to use Multiple pod file in single Xcode project because I need to improve the `pre-main` time of app. As, I am using third party library some of them are in Objective C and some are in swift hence I am unable to convert them to the static framework because swift doesn't allow me to convert dynamic framework to static framework.

## What did you expect to happen?
I want that I can segregate all third party library written in objective c and convert those in to static framework that will boost my `App launch time`.

## What happened instead?
I am not able to improve app launch time (Pre main time) if I am having the mixing of framework (some of them are in Objective C and some are in swift).

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
