### ISSUE TITLE
Cannot install a private pod from specific branch

### ISSUE THREAD

**Issue by nick3389** [CocoaPods/CocoaPods#7492]
# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Error: Unable to find a specification for 'private_pod'

Hi,

I have a problem with a private pod when I try to install it from a specific branch. When i include in the podfile:

`pod 'private_pod'`

everything works ok.

But when I change it to:

`pod 'private_pod', :git => 'git_repo', :branch => 'develop'`

I get all the times this error:
**Unable to find a specification for 'private_pod'**

Is there anything I can do?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by nick3389** [comment]
@orta I noticed similar issues here, so that's why I posted it here. Also, I did not see any solution in these posts and also this post: https://github.com/CocoaPods/CocoaPods/issues/3877 is closed despite the fact that it is not solved.

**Comment by segiddins** [comment]
You can either use `:podspec` to point to a specific podspec with a custom `source` property, or you can add the specification for `private_pod` to its git repo
