### ISSUE TITLE
Redefinition of module Error

### ISSUE THREAD

**Issue by saravanankk** [CocoaPods/CocoaPods#7493]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I am trying to create a Library that uses IOS-Pods-DFU-Library as one of the dependency. I am using COACOAPODS for my Library dependency management. I am releasing my library as a binary framework to the end Customers. Then the customers will integrate it with their app using COACOAPODS from localhost server with our custom podspec file that will download our binary framework(alreday shared to them) from localhost servers and resolve other dependencies we used in our library.

## What did you expect to happen?

In the client applications, it should able to compile, build and run properly

## What happened instead?
Client application produces the following error.

```
/Users/Softwaredevelopement2/Saravanan/workspace/consumer app test/CustomerTest/Pods/Zip/Zip/minizip/module.modulemap:1:8: error: redefinition of module 'minizip'
module minizip [system][extern_c] {
       ^
/Users/Softwaredevelopement2/Saravanan/workspace/Test/TestSDK/Example/Pods/Zip/Zip/minizip/module.modulemap:1:8: note: previously defined here
module minizip [system][extern_c] {
       ^
<unknown>:0: error: could not build Objective-C module 'Zip'
```
It used to work fine without iOSDFULibrary[They internally used Zip as their dependency]. 

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.16.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5889f07c0147d5c3cfe6f98e238aaa470d6dd69f
               Test -  @ fatal: Not a git repository (or any of the parent directories): .git
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.1
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Below are our sample podspec file and example how user includes our library.

```ruby
Pod::Spec.new do |s|
s.name = "xxxxxx"
s.version = "1.0.0"
s.summary = "xxxxxx description ."
s.author = { "" => "" }
s.license = { :type => 'Apache-2.0', :file => 'LICENSE' }

s.ios.preserve_paths = 'xxxxxx.framework/*.bundle'

s.ios.deployment_target = "9.0"

s.source = { 
  :http => 'http://localhost:8000/xxxxxx.zip'
}  
s.ios.vendored_frameworks = 'xxxxxx.framework'
s.dependency 'SSZipArchive', ' 2.1'
s.dependency 'XCGLogger', ' 6.0'
s.dependency "iOSDFULibrary", '4.1.1'

end
```

Customers will include our library by specifying above podsepec file path as below in their pod file
pod 'xxxxxx', :podspec => './xxxxxx.podspec'

**Comment by dnkoutso** [comment]
Please provide a sample app demonstrating the issue.

**Comment by saravanankk** [comment]
Attached sample project CustomerApp is the final project to reproduce the issue. 
CustomerApp already contains MyLibrary binary frameworks attached. 
Currently, CustomerApp should only run on real devices it won't support simulators, please check with the real device also change bundle identifier.

MyLibrary folder is the source for Library Project. I build the MyLibrary project and taken generated 
MyLibrary.framework and attached Licence file and then created a final zip file for support custome Customer.podspec.

[workspace.zip](https://github.com/CocoaPods/CocoaPods/files/1798923/workspace.zip)

**Comment by dnkoutso** [comment]
@saravanankk I am unable to reproduce given your sample app and using CocoaPods 1.5.0.beta.1

Tried a test target as well and it successfully built.

**Comment by dnkoutso** [comment]
Please update here if you are still experiencing this issue and see if we can re-open it.
