### ISSUE TITLE
SWIFT_VERSION not being propagated down to test specs in pod spec

### ISSUE THREAD

**Issue by paxswill** [CocoaPods/CocoaPods#7498]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Write a Podspec with a test spec that uses additional Swift dependencies (example below).
2. `pod lib lint --verbose`

## What did you expect to happen?

The Podspec is tested, and the test dependencies are built as part of that.

## What happened instead?

The test dependencies are *not* built, with the following error being reported:

Testing failed:
	The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

If I copy the dependencies form the test spec into the root spec, they are built appropriately (probably as part of the normal build process) and tests run as expected.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.3 (9Q127n)
         Git : git version 2.16.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 140836b675a0d67b9273dce685eb15f735b7b02d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
I'm still getting the hang of CocoaPods, but I think I set this up right. The [spec in this repo](https://github.com/paxswill/SubSpecSwift) fails to build Quick and Nimble as part of `pod lib lint`. Unfortunately, the generated workspace doesn't seem to include an actual test target, but the verbose output includes the error. I also have another project (not currently uploaded anywhere) that exposes the error in the generated workspace, but I can upload it if you like.

**Comment by paulz** [comment]
Same here:

`pod lib lint` fails to build `test_spec`:

```shell
Testing failed:
	The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
** TEST FAILED **
```
See this in the build failure example:
https://travis-ci.org/paulz/ImageCoordinateSpace/builds/352681029#L1406 

Here is Podspec: https://github.com/paulz/ImageCoordinateSpace/compare/test-spec#diff-bb95b557484327c4af49a0c6c41f3b39R22

```ruby
    s.test_spec do |ts|
        ts.frameworks = 'XCTest'
        ts.source_files = 'Unit Tests/**/*.{h,swift}'
        ts.dependencies = {'Quick':'1.2.0', 'Nimble':'7.0.3'}
    end
```

**Comment by dnkoutso** [comment]
Thanks for the reports I should be able to take a look and take care of this, there is a chance its fixed in 1.5.0 already but I do not recall immediately.

**Comment by paulz** [comment]
How can I install 1.5.0 to try it out?

Tried with latest cocoapods in `Gemfile`:
https://github.com/paulz/ImageCoordinateSpace/blob/test-spec/Gemfile
```ruby
source 'https://rubygems.org'

gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git'
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git'
gem 'xcodeproj', :git => 'https://github.com/CocoaPods/Xcodeproj.git'
```
Same result:
```
Testing failed:
	The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
	No such module 'Nimble'
** TEST FAILED **
```

Here is the branch to try: https://github.com/paulz/ImageCoordinateSpace/tree/test-spec

**Comment by dnkoutso** [comment]
Will give it a shot and get back to you I do not think its fixed in 1.5.0.

**Comment by dnkoutso** [comment]
Confirmed. I know what is wrong. Unfortunately I do not think there is a workaround available at this time.

**Comment by dnkoutso** [comment]
Fixed here https://github.com/CocoaPods/CocoaPods/pull/7501

**Comment by dnkoutso** [comment]
Podspecs should be updated to include `swift_version` DSL. If they do not then the one specified by the pod being tested (in this example `ImageCoordinateSpace`) version will be used or the one specified by the `.swift-version` file if the pod being tested does not provide one.
