### ISSUE TITLE
Search on cocoapods.org doesn't work anymore

### ISSUE THREAD

**Issue by xlbs-rm** [CocoaPods/CocoaPods#7499]
Cannot search for Pods? Are there alternatives? 
Google search with site:cocoapods.org is not really a alternative.

Tested on 2 different Devices, Browsers: Chrome, FF

Expected: List of Results e.g. for: Realm (automatic written in Uppercase REALM)
Given: Result shows no result, URL has right search Param, pods are available example: https://cocoapods.org/pods/Realm

**Comment by dnkoutso** [comment]
Please file a bug on https://github.com/CocoaPods/cocoapods.org

**Comment by trevor-sonic** [comment]
still the same! I search a pod, no any result returns :-/
