### ISSUE TITLE
crash on startup with enterprise build

### ISSUE THREAD

**Issue by jamehta** [CocoaPods/CocoaPods#7502]
Using cocoapods 1.0.1

we are using cardio as dependency.

when we build thru xcode on device, everything is fine.

when we build enterprise build, on app startup there is below crash:
==

Termination Description: DYLD, Symbol not found: _OBJC_CLASS_$_CardIOCreditCardInfo | Referenced from: /private/var/containers/Bundle/Application/3B983FDE-83CA-4C33-ABF8-503421128C7E/PayPal.app/Frameworks/Wallet.framework/PayPalWallet | Expected in: flat namespace | in /private/var/containers/Bundle/Application/3B983FDE-83CA-4C33-ABF8-503421128C7E/Wallet.app/Frameworks/Wallet.framework/Wallet
Triggered by Thread:  0

There is no difference between debug and enterprise build except for signing.

**Comment by dnkoutso** [comment]
This does not seem a cocoapods issue. Also please fill in the template and provide a sample app demonstrating the issue.

I will re-open if this appears a cocoapods issue.
