### ISSUE TITLE
pod lib lint generates target for test_spec without Info.plist

### ISSUE THREAD

**Issue by paulz** [CocoaPods/CocoaPods#7506]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

While in a directory with a Pod spec containing `test_spec`
Run `pod lib lint --no-clean`

## What did you expect to happen?

Generated xcode workspace test target to have `Info.plist` set

## What happened instead?

Test target info.plist is not set

as a workaround I am setting path to plist in the pod spec: (note the content of plist is incorrect, it should be a standard Xcode generated test target info plist file)

```
    s.test_spec 'UnitSpecs' do |ts|
        ts.pod_target_xcconfig = {
            'INFOPLIST_FILE'=>'Target Support Files/ImageCoordinateSpace/Info.plist' }
        ts.resource       = 'Example/Assets.xcassets'
        ts.source_files   = 'Unit Tests/**/*.{h,swift}', 'ImageCoordinateSpace/**/*.{h,swift}'
        ts.dependencies   = {'Quick':'1.2.0', 'Nimble':'7.0.3'}
    end

```

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.2
Ruby lib dir : ~/.rvm/rubies/ruby-2.3.3/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 1e45ae05aed0a9df955b24847b84aaa2d7a88021
               cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ 49219096a3324f39bfb82dbeb5fc160adce2182f
```

### Installation Source

```
Executable Path: ~/.rvm/gems/ruby-2.3.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Podspec:
https://github.com/paulz/ImageCoordinateSpace/blob/61ce72d7d5d9711982d4520c9d8ca54bc81dba5c/ImageCoordinateSpace.podspec#L24

Gemfile.lock:
https://github.com/paulz/ImageCoordinateSpace/blob/61ce72d7d5d9711982d4520c9d8ca54bc81dba5c/Gemfile.lock

**Comment by dnkoutso** [comment]
What should a default Info.plist be? I'll need to investigate.

**Comment by dnkoutso** [comment]
Thanks! Will mark it as an easy enhancement

**Comment by paulz** [comment]
Thank you for looking into it! Excited to pilot test_spec for my pod.

Xcode generates this `Info.plist` when you add new test target:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>BNDL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
</dict>
</plist>
```

The content of the file is not so important as long as it's valid bundle Info.plist

Without bundle plist the unit tests fails to load resources from bundle

**Comment by dnkoutso** [comment]
@paulz you should still be ok with the workaround for now to include your own plist for your test target.

**Comment by paulz** [comment]
Yes, forgot about it! Will do

**Comment by dnkoutso** [comment]
@paulb777 

> Without bundle plist the unit tests fails to load resources from bundle

Which bundle are you referring to, the actual test bundle or a separate resource bundle?

Are you using `test_spec.resource` or `test_spec.resource_bundle`?

**Comment by paulz** [comment]
Thank you, @dnkoutso, works for me now on master (0778a2aa8056f23f9bfc45a03f24b7031d5016e8) after the merge

Now Xcode correctly shows Info plist build setting set:
<img width="1462" alt="Screenshot showing Info Plist property is set in xcode" src="https://user-images.githubusercontent.com/59230/37695201-c5ff3668-2c8a-11e8-8164-8b19b56ca5b9.png">
and Info tab on test target shows content of the Info.plist file:
<img width="1080" alt="screen shot showing Info tab on test target shows content of Info.plist" src="https://user-images.githubusercontent.com/59230/37695202-c6153fa8-2c8a-11e8-891c-2093b40f789e.png">

and here is my travis build successfully passing `pod lib lint` on the pod spec with`test_spec`:
https://travis-ci.org/paulz/ImageCoordinateSpace/builds/356194782

Here is the pod spec:
https://github.com/paulz/ImageCoordinateSpace/blob/aae66d65c57a4264646ed2c364886371a50e8c5d/ImageCoordinateSpace.podspec

**Comment by dnkoutso** [comment]
flawless!
