### ISSUE TITLE
test_spec module_name equals to parent

### ISSUE THREAD

**Issue by paulz** [CocoaPods/CocoaPods#7507]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint` for a pod spec with `test_spec`

## What did you expect to happen?

Generated test target to have Xcode build setting
`PRODUCT_NAME` to be different from the main pod `PRODUCT_NAME`

## What happened instead?

`PRODUCT_NAME` for test target is the same as framework target. This cause
 1. incorrect warning about import MyFramework
 2. @testable import MyFramework fails to make classes accessible
 3. Tests can not access the Framework classes, because they are part of the module but in the different bundle. 

As a workaround I copy Framework sources into Test bundle as part of the pod spec:

See https://github.com/paulz/ImageCoordinateSpace/blob/61ce72d7d5d9711982d4520c9d8ca54bc81dba5c/ImageCoordinateSpace.podspec#L26
```
    s.test_spec 'UnitSpecs' do |ts|
        ts.pod_target_xcconfig = {
            'INFOPLIST_FILE'=>'Target Support Files/ImageCoordinateSpace/Info.plist' }
        ts.resource       = 'Example/Assets.xcassets'
        ts.source_files   = 'Unit Tests/**/*.{h,swift}', 'ImageCoordinateSpace/**/*.{h,swift}'
        ts.dependencies   = {'Quick':'1.2.0', 'Nimble':'7.0.3'}
    end
```

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.2
Ruby lib dir : ~/.rvm/rubies/ruby-2.3.3/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 1e45ae05aed0a9df955b24847b84aaa2d7a88021
               cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ 49219096a3324f39bfb82dbeb5fc160adce2182f
```

### Installation Source

```
Executable Path: ~/.rvm/gems/ruby-2.3.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/paulz/ImageCoordinateSpace/tree/test-spec

https://github.com/paulz/ImageCoordinateSpace/blob/test-spec/ImageCoordinateSpace.podspec

**Comment by paulz** [comment]
My wish for test spec module name to be either set to `<PodName>Test` or allow `module_name` to be set in the `test_spec`.

When I tried to set `module_name` I am getting an error:
```
ERROR | [iOS] attributes: Can't set `module_name` attribute for subspecs (in `ImageCoordinateSpace/UnitSpecs`).
```

**Comment by segiddins** [comment]
I believe on `master` they have different `PRODUCT_NAME` but the same `PRODUCT_MODULE_NAME`

**Comment by dnkoutso** [comment]
No I think they are still the same on master

**Comment by dnkoutso** [comment]
@paulz I tried master and I see this:

![screen_shot_2018-03-14_at_9_55_54_am](https://user-images.githubusercontent.com/310370/37417612-f785d51a-276d-11e8-9faf-5f14f8fdc420.png)
![screen_shot_2018-03-14_at_9_55_51_am](https://user-images.githubusercontent.com/310370/37417613-f7a11eb0-276d-11e8-94ce-bc6495fbc98e.png)

**Comment by dnkoutso** [comment]
@paulz did you mean `PRODUCT_MODULE_NAME` instead? because those *are* the same.

**Comment by dnkoutso** [comment]
@paulz confirmed a regression on master which I assume you are using, PR coming up.

**Comment by dnkoutso** [comment]
@paulz thanks for surfacing these issues, glad to fix them for you :)

**Comment by paulz** [comment]
Thank you for looking into this, @dnkoutso 

Yes, you right we do care about `PRODUCT_MODULE_NAME`, however Xcode default value for `PRODUCT_MODULE_NAME` is `$(PRODUCT_NAME)`, so if we can get product name fixed we should get module name automatically.

The fix https://github.com/CocoaPods/CocoaPods/pull/7510 should fix this too!

**Comment by dnkoutso** [comment]
👍
