### ISSUE TITLE
[1.4.0] pod update PODNAME updates ALL pods

### ISSUE THREAD

**Issue by ivan-r** [CocoaPods/CocoaPods#7509]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod update Alamofire`

## What did you expect to happen?

`Alamofire` gets updated to the version specified in `Podfile`

## What happened instead?

pod tries to update all pods and exits with error:
`[!] Unable to find a specification for 'PRIVATE-POD (= 2.5.1)'`

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/********/.rvm/rubies/ruby-2.4.2/lib
Repositories : cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ dd31daf9044a292fe817b6b76e8507e9dba9b10b
```

### Installation Source

```
Executable Path: /Users/********/.rvm/gems/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs'
#source 'http://private/pod/repo’

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'Target' do
    pod 'Alamofire', '~> 4.6.0'
    pod 'SwiftyJSON', '3.1.1'
    pod 'NSAttributedString-DDHTML', '1.2.0'
    pod 'CocoaLumberjack/Swift', '3.2.0'
    pod 'HockeySDK'
    pod 'SnapKit', '3.2.0'
    pod 'GoogleMaps'
    # Private pod
    pod ‘PRIVATE-POD’, '2.5.1'
end

target 'Target-Tests' do
    pod 'SwiftyJSON', '3.1.1'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = ‘3.0’
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

## Additional Information

All pods in the `Podfile` are already installed and on the `Podfile.lock`.
Since I don't have credentials for the private pod repo, I need to update all other pods without changing `PRIVATE-POD`.

If I comment  
```
# pod ‘PRIVATE-POD’, '2.5.1'
```
and run 
```
pod update Alamofire
```

`PRIVATE-POD` gets deleted, and all the pods in `Podfile` are updated

**Comment by segiddins** [comment]
CocoaPods still needs to be able to access your specification to be able to run the resolver

**Comment by dnkoutso** [comment]
Is this an issue then? Should we close?

**Comment by orta** [comment]
Yeah, IMO it's not an issue, if CP can't do a full resolve it can't figure out what the current dep tree is, and can't realistically update anything
