### ISSUE TITLE
AppIcon cannot show in the Simulator Client

### ISSUE THREAD

**Issue by wangjindong** [CocoaPods/CocoaPods#7511]
![20180315093552040](https://user-images.githubusercontent.com/4929805/37439717-56d3feea-2834-11e8-90e0-e8e9317f6db4.png)

![20180315093616548](https://user-images.githubusercontent.com/4929805/37439724-60aa252a-2834-11e8-9172-12419692b331.png)

xcode：9.2
cocoapods：1.4.0

I have a resource project，it has only Images.xcassets。
But it causes appicon not to be displayed。
It's no problem in other images.

How to solve this problem

[demo](https://github.com/wangjindong/ResourcesDemo.git)

**Comment by dnkoutso** [comment]
I do not think this is a cocoapods library issue. you should be setting the app icon to your project settings in Demo.xcodeproj.

CocoaPods does not mess with app icon integration.

**Comment by wangjindong** [comment]
Please run the demo，app icon  really in Demo.xcodeproj。
delete #pod 'Resources', :path => '../'。App icon can be displayed normally!

**Comment by dnkoutso** [comment]
ok I can investigate.

**Comment by dnkoutso** [comment]
@wangjindong first of all confirmed. Second of all your project actually exposed a caching issue which I have fixed for faster re-builds!

Third, I apologize for closing quickly, let me see what I can do for your issue, I think one of your resources basically is stomping some files on your project.

**Comment by dnkoutso** [comment]
@wangjindong quick work around is to use `s.resource_bundle` instead of `s.resources` in your podspec.

**Comment by wangjindong** [comment]
Sorry,It need some time to be replaced for s.resource_bundle.

Is there no better solution?

**Comment by dnkoutso** [comment]
This appears to be this issue https://github.com/CocoaPods/CocoaPods/pull/7020 I think

**Comment by dnkoutso** [comment]
@wangjindong will close this one as dup of #7003

**Comment by wangjindong** [comment]
ok,tks！
