### ISSUE TITLE
BUG: private zip having proper podspec file, getting downloaded when doing pod install, but complaint that Unable to find a specification for 'DigitalSDKClient'

### ISSUE THREAD

**Issue by gkmrakesh** [CocoaPods/CocoaPods#7514]
## What did you do?
Installing private pod where the source is 

```ruby
s.source = { :http => 'https://dl.dropboxusercontent.com/s/zktmooi8vjb1aoo/DigitalSDKClient.zip' }
```

## What did you expect to happen?

as Zip file, i am referring, having proper podspec,  pod should get installed properly

## What happened instead?

[!] Unable to find a specification for 'DigitalSDKClient'.

## Pod File

```ruby
Pod::Spec.new do |s|
  s.name = 'DigitalSDKClient'
  s.ios.deployment_target = '9.0'
  s.osx.deployment_target = '10.11'
  s.tvos.deployment_target = '9.0'
  s.version = '1.0.0'
  s.source = { :http => 'https://dl.dropboxusercontent.com/s/zktmooi8vjb1aoo/DigitalSDKClient.zip' }
  s.authors = 'Amadeus'
  s.homepage = 'http://www.xyz.com'
  s.license = 'MIT'
  s.summary = 'iOS SDK for Amadeus Digital API'
  s.description = 'iOS SDK for Amadeus Digital API iOS SDK for Amadeus Digital API iOS SDK for Amadeus Digital API'
  s.dependency 'Alamofire', '~> 4.5.0'
  s.preserve_path = '*'
  s.source_files = '*'
  s.pod_target_xcconfig = { "SWIFT_VERSION" => "3.2" }
end
```

## Finding 
When running with "pod install --verbose" i can find some interesting things
1. zip file from the specified location in podspec  getting downloaded into file.zip
2. when file.zip getting extracted by cocoapod, it is missing DigitalSDKClient.podspec though it is there in file.zip
3. [!] Unable to find a specification for 'DigitalSDKClient'. issue is being thrown

Requesting urgent help as it is a critical issue.

**Comment by segiddins** [comment]
Can you please share the output of `pod env`, as requested in the issue template? Thanks!

**Comment by gkmrakesh** [comment]
### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.7.5
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /Users/rmembaram/.rvm/rubies/ruby-2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 239843d73c04148af4dbe55a9aa919bb5a83a57b
               SpecRepo - https://github.com/gkmrakesh/SpecRepo.git @ 1ab53c923460e5891e9f0477f1b2eceeac60dc55
```

### Installation Source

```
Executable Path: /Users/rmembaram/.rvm/gems/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

def server
    pod 'DigitalSDKClient', :http => 'https://dl.dropboxusercontent.com/s/zktmooi8vjb1aoo/DigitalSDKClient.zip'
end

target 'MeRCIapp' do
    server
end
```

**Comment by gkmrakesh** [comment]
@segiddins 

Sorry, it took little time as I was away from my MAC for some time.

**Comment by segiddins** [comment]
Since it's in a `.zip`, you need to prefix all paths with the name of the zip (in this case,  `DigitalSDKClient`). Alternatively, you could use `flatten: true` to flatten the zip, but I think that's broken at the moment
