### ISSUE TITLE
use script_phase but $EXPANDED_CODE_SIGN_IDENTITY is empty

### ISSUE THREAD

**Issue by Goosoul** [CocoaPods/CocoaPods#7516]
I use s.script_phase = { :name => 'XXX', :script => '${PODS_TARGET_SRCROOT}/yyy.sh', :execution_position => :after_compile} in my podspec and it works! However I can't get $EXPANDED_CODE_SIGN_IDENTITY like adding 'Run Script' in xcproj. so I use `set` to print all varibles and found "EXPANDED_CODE_SIGN_IDENTITY="

**Comment by dnkoutso** [comment]
A couple of things:

1) This question seems better asked on StackOverflow under `cocoapods` tag instead
2) You should be able to set `EXPANDED_CODE_SIGN_IDENTITY` yourself via `pod_target_xcconfig` for your pod. 
3) CocoaPodes not set `EXPANDED_CODE_SIGN_IDENTITY` anywhere in the codebase it only reads it for some of its internal scripts.
