### ISSUE TITLE
Build failure triggered by reordered umbrella header file

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#7518]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

` git clone git@github.com:paulb777/NVMDummyTestPod.git`
`~/Cocoapods/CocoaPods/bin/pod update --no-repo-update`
`open NVMDummy.xcworkspace/`
Build and notice build failure

## What did you expect to happen?

I expected the build to succeed like it does if I run `pod update` with the 1.4.0 version.  Running with [latest master](https://github.com/CocoaPods/CocoaPods/commit/606b943343b525418d4e24564a141973fe6cc263) fails.

The difference is the file `./Pods/Target Support Files/Protobuf/Protobuf-umbrella.h` which has the imports specified by a wildcard listed ahead of the explicitly named headers, despite the wildcard listed first in the podspec file.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin17]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.0.403.gc27cc4dac6-goog
Ruby lib dir : /Users/paulbeusterien/.rbenv/versions/2.4.0/lib
Repositories : cpdc-eap-spec - sso://cpdc-eap/spec @ c8892452be7c52ff70c238c111369b92ab97e90c
               cpdc-internal-spec - sso://cpdc-internal/spec @ bba62265f71bd5cbed7df4a35a1c9abf8064f139
               master - https://github.com/CocoaPods/Specs.git @ afe932100bfb533402402b5f0d3fa9032bdca57b
               paul-specs - sso://user/paulbeusterien/Specs @ 0b01f6ce5731056ef13971c3c2e339fb1c789cff
```

### Installation Source

```
Executable Path: /Users/paulbeusterien/Cocoapods/CocoaPods/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.2
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.3.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'


target 'NVMDummy' do
  platform :ios, '8.0'

  pod 'NVMDummy', :path => './'

end
```

## Project that demonstrates the issue

`git@github.com:paulb777/NVMDummyTestPod.git`

**Comment by segiddins** [comment]
Fairly certain this was caused by https://github.com/CocoaPods/CocoaPods/pull/7473, but I'm not sure why it would break a build -- headers should always be importing the headers they themselves need, so the ordering in the umbrella header shouldn't be consequential

**Comment by segiddins** [comment]
cc @manuyavuz

**Comment by dnkoutso** [comment]
@paulb777 can you please try without #7473 to verify this is the root cause?

**Comment by paulb777** [comment]
Confirmed that reverting the three code commits of #7473 fixes the build regression. 

I tend to agree that umbrella headers should not depend upon order - but this change could break others that are either knowingly or unknowingly depending on the order of headers to match the podspec order.

**Comment by manuyavuz** [comment]
This is definitely a problem, it's hard for everyone to prepare an order independent code. I'll look into this.
