### ISSUE TITLE
I can't install because of an 443 error.

### ISSUE THREAD

**Issue by forthenature** [CocoaPods/CocoaPods#752]
Resolving dependencies of `./Podfile'
Updating spec repositories
[!] git pull

error: Unknown SSL protocol error in connection to github.com:443  while accessing https://github.com/CocoaPods/Specs.git/info/refs

fatal: HTTP request failed

PS:I'm in China, so I suspect it is because of the GFW. Anyone who is not in China has the same problem?

**Comment by gaoguanghui** [comment]
I  met the problem, what should I do?
![2018-08-22 1 41 11](https://user-images.githubusercontent.com/12198974/44445542-e87e9780-a613-11e8-8b09-d5788bcbd748.png)
@forthenature
