### ISSUE TITLE
Getting issue to pod install command

### ISSUE THREAD

**Issue by hadwanihardik** [CocoaPods/CocoaPods#7520]
Each time I call `pod install ` command it start downloading all details like below.

>  Analyzing dependencies
> Setting up CocoaPods master repo
>   $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
>   Cloning into 'master'...
>   remote: Counting objects: 1998407, done.        
>   remote: Compressing objects: 100% (442/442), done.        
>   Receiving objects:   0% (19754/1998407), 3.93 MiB | 14.00 KiB/s     

Every time it download all 1.9GB data.

<img width="562" alt="screen shot 2018-03-16 at 9 50 44 pm" src="https://user-images.githubusercontent.com/5634693/37532364-d93bfc62-2964-11e8-839a-a8e6262d7893.png">

**Comment by dnkoutso** [comment]
Until we remove the dependency to master repo you can either manually set it up and add it to `~/.cocoapods/repos/master` .

We will be re-working this after 1.6.0.

Please also use existing questions in StackOverflow for this or prior issues filed here.

**Comment by hadwanihardik** [comment]
How to set it up and add it?
