### ISSUE TITLE
Xcode Version 9.3 beta 4: The sandbox is not in sync with the Podfile.lock

### ISSUE THREAD

**Issue by alex-trandafir** [CocoaPods/CocoaPods#7523]
# Report

## What did you do?

Download the [ARKit](https://developer.apple.com/documentation/arkit/recognizing_images_in_an_ar_experience) example from Apple website 

Run `pod init` 
Run `pod install`
Open `ARKitImageRecognition.xcworkspace` in Xcode Version 9.3 beta 4 (9Q127n)

## What did you expect to happen?
The code should compile

## What happened instead?

Received the following errors: 
> diff: /Podfile.lock: No such file or directory
> diff: /Manifest.lock: No such file or directory
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.3 (9Q127n)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3575c40cd37f250d5e9022670be62f37a274ec20
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARKitImageRecognition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARKitImageRecognition

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

## Workaround

Applying the fix "diff "${SRCROOT}/Podfile.lock" "${SRCROOT}/Pods/Manifest.lock" > /dev/null" from over [here](https://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res)  works but then, after adding a pod, it cannot be used as the compiler says "library_name not found" (after running the appropriate steps: pod install, opening the .xcworkspace)

**Comment by dnkoutso** [comment]
Please provide a sample app. I am not sure this seems a CocoaPods library issue.

**Comment by dnkoutso** [comment]
Oh nevermind, heh just woke up there is instructions to use a sample app :)

**Comment by dnkoutso** [comment]
@alex-trandafir can you please attach a sample app showing the issue?
