### ISSUE TITLE
podspec spec.libraries not work

### ISSUE THREAD

**Issue by wsh4089** [CocoaPods/CocoaPods#7529]
In my podspec, I use ` spec.libraries = 'sqlite3', 'z'`, and then `pod install`. 
Then in my xcode target , `Other Linker Flags` don't contains `-l "sqlite3" -l "z"`.

If I add text to `spec.ios.library = 'sqlite3' , 'z'` below ` spec.libraries = 'sqlite3', then it's ok.

So I don't confirm that if it is a problem and the [doc](https://guides.cocoapods.org/syntax/podspec.html#libraries) also don't specify.

`pod --version`
`1.4.0`

**Comment by dnkoutso** [comment]
please upload a sample app demonstrating the issue.

**Comment by wsh4089** [comment]
I'm sorry that I can't show a sample app demonstrating the issue , because it did work .

I don't confirm that if the problem is cache files.

Thank you for your patience.
