### ISSUE TITLE
Question: How to set CFBundleVersion in Pod Framework?

### ISSUE THREAD

**Issue by knightcode** [CocoaPods/CocoaPods#7530]
I apologize for the clutter, but I've googled around for an answer to this and haven't found an answer. I'm developing an SDK in a Pod as a framework that wraps a REST api. I don't care what the users of this pod set their `CFBundleVersion` value to. That number has no meaning to our system. Instead, I need to declare the `CFBundleVersion` for each release of the pod so that we can know what versions are out in the wild. And it seems like bad form to require each user of the framework to put the correct `post_install` script in their Podfile.

I'm sure there must be a way to do this and that I just haven't found the right documentation. Can someone enlighten me.

🌈

**Comment by dnkoutso** [comment]
What is the value to be set? Can `pod_target_xcconfig` set it in your podspec?

**Comment by knightcode** [comment]
I think that's what I'm looking for... but what's the right key?  Using 'CFBundleVersion' did set the property in xcconfig, but the Info.plist is unchanged.

**Comment by dnkoutso** [comment]
it seems this is inside the `Info.plist`. You can always provide your own in `INFOPLIST_FILE` setting within the `pod_targert_xcconfig` and just set the`CFBundleVersion`

CocoaPods will generate a default one otherwise.

**Comment by dnkoutso** [comment]
Remember to use `${PODS_TARGET_SRCROOT}/some/path/to/your/Info.plist` to ensure the path is always relative and correct.

**Comment by knightcode** [comment]
That didn't seem to have any effect.

I put the Info.plist in the top-level directory, outside of anything that would match `source_files` with just this content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleVersion</key>
  <string>133</string>
</dict>
</plist>
```

podspec:
```ruby
 s.pod_target_xcconfig = { "INFOPLIST_FILE" => "${PODS_TARGET_SRCROOT}/Info.plist" }
```

**Comment by dnkoutso** [comment]
@knightcode please upload a sample app so I can reproduce and see.

**Comment by knightcode** [comment]
updated: https://github.com/knightcode/PodFail

**Comment by dnkoutso** [comment]
thanks

**Comment by dnkoutso** [comment]
@knightcode this is a bug indeed. The info plist file is being overridden the generation of the default one after.

**Comment by knightcode** [comment]
ok. Thanks!

Any chance you could shortcut the process with another (maybe optional) podspec property similar to `s.version` and however that gets into the generated Info.plist?

**Comment by dnkoutso** [comment]
Nope, the fix is how the integration works. Will have to be CocoaPods 1.5.0.

**Comment by dnkoutso** [comment]
@knightcode aiming for 1.5.0.beta.2 to fix this.

**Comment by knightcode** [comment]
cool. ...Will I need to have a fully specified Info.plist or is one containing the single property enough? (fingers crossed for the latter)

**Comment by dnkoutso** [comment]
depends if Xcode accepts it. You might be OK but I cannot guarantee that as I do not know.

**Comment by dnkoutso** [comment]
@amorde I believe this still is an error for test specs.

```test_spec.pod_target_xcconfig = { 'INFOPLIST_FILE' => '"$(PODS_TARGET_SRCROOT)/UnitTests/Info.plist"' }```
```

Will not be applied to the test native target and will be overridden by the default one.

**Comment by amorde** [comment]
interesting - got a sample project I can test on?

**Comment by knightcode** [comment]
Briefly reading through the changes, it looks like there's no merging of plists. Is that correct? I need to fully specify the Info.plist of my Pod? I'm okay-ish with that, just asking for clarification.
