### ISSUE TITLE
Swift Library - Unresolved Identifiers even though item is public

### ISSUE THREAD

**Issue by mlb5000** [CocoaPods/CocoaPods#7534]
CocoaPods 1.4.0
XCode 9.2
Swift 4

I'm having the same problem as #4657, except my class **is** public. 

1. `pod lib create MyLibrary` (accept all defaults)
2. Put my files in `MyLibrary/Classes`, in podspec `s.sources = "MyLibrary/Classes/**/*`
3. `pod install` in `Example`
4. Open `xcworkspace`
5. Build everything
6. `import MyLibrary` in the example `ViewController.swift` and create an instance of `MyClass` from `MyLibrary` which is marked as public
7. Attempt to build - `Use of unresolved identifier 'MyClass'`

**Comment by dnkoutso** [comment]
Are you using 1.4.0 or master?

Please upload the sample app.

**Comment by mlb5000** [comment]
@dnkoutso it's actually 1.4.0 (I upgraded today in an attempt to fix this). New data:

* Add empty class to library `public class MyOtherClass { public init() { } }`
* Remove `MyClass` Reference, add `MyOtherClass` in example and compile. It compiles.
* Add `MyClass` reference in example. It also compiles.

I seriously hate XCode

**Comment by dnkoutso** [comment]
lol. So is this still an issue with CocoaPods I havent quite understood.

**Comment by mlb5000** [comment]
* Perform clean.
* Build - Fails with `Use of undeclared type 'MyClass'`

There appears to be an issue with properly discovering `public` symbols to export from the generated `.framework`. Can someone follow the above steps and tell me if they run into the same problems?

**Comment by mlb5000** [comment]
OK. The issue was caused by a Core ML model that was added to the pod as a resource. For "CoreML Model" file types there is a "convenience" step in XCode where your `mlmodel` will be compiled into an `mlmodelc` during the build process. In the build log this step shows up as "Compile Swift source files", which I _think_ tricks XCode into thinking that the only class that should be packaged into the framework is the model interface file it generates (which is internal by default). I'm not 100% sure, but this would explain why "Jump to definition" on my framework import would show an empty list of exports (except for the version number).

What I am sure about is the solution. In the Build Phases of the Pod target containing the `mlmodel` file you need to move the `Copy Bundle Resources` build phase to before `Compile Sources`. That way everything we need gets included in the linked framework.

Is there a way to change the order of these build phases in the podspec, or is this a manual step we're going to have to take every time we integrate that library into an application (it's a private pod)?

**Comment by mlb5000** [comment]
@dnkoutso ^

**Comment by dnkoutso** [comment]
While Xcode allows you to re-organize them I do not think CocoaPods does it.

For most of target generation CocoaPods tends to just create the target and let Xcode use defaults for the most part including the order of the build phases.

Care to show the podspec? Are `mlmodel` files expected to be in resources or compile sources, sorry I haven't worked with `Core ML` at all.

**Comment by mlb5000** [comment]
@dnkoutso I added it as a resource because that made the most sense at the time. However, I just tested moving it to the `Classes` folder instead and that appears to have worked. So that's likely the better solution.

**Comment by dnkoutso** [comment]
@mlb5000 does it work in normal Xcode if you place it in resources? Do you think this issue should remain open?

**Comment by wenquanlebao** [comment]
> @dnkoutso I added it as a resource because that made the most sense at the time. However, I just tested moving it to the `Classes` folder instead and that appears to have worked. So that's likely the better solution.

That's what I do.But I found it impossible to initialize with mlmodelc files.
