### ISSUE TITLE
ArgumentError - Illformed requirement `"~>"`

### ISSUE THREAD

**Issue by Ianchan7** [CocoaPods/CocoaPods#7535]
Command

    /usr/local/bin/pod update --no-repo-update

Report

- What did you do?
update cocoapods to 1.4.0 and execute 'pod update' commands

- What did you expect to happen?
update success

- What happened instead?
ArgumentError - Illformed requirement `"~>"`

Stack

       CocoaPods : 1.4.0
            Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
        RubyGems : 2.7.6
            Host : Mac OS X 10.13.3 (17D102)
           Xcode : 9.2 (9C40b)
             Git : git version 2.14.3 (Apple Git-98)
    Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
    Repositories : artsy - https://github.com/artsy/Specs.git @ f16ce0e4d635a3219b4e52d79b1e0d257b43b8fe
                   BJZF-IOS-Specs - https://git.zhubajie.la/BJZF-IOS/BJZF-IOS-Specs @ 78144be95a124d22af0b596dfdd830d7585d7a71
                   master - https://github.com/CocoaPods/Specs.git @ babce131b9aacbae7fc6205d77f235dbc569caf5
                   ZBJMobileSpecs - https://git.zhubajie.la/ZBJMobileCocoapodsSpecs-iOS/ZBJMobileSpecs.git @ 12ddb6a61459831ea654472afe8b365286a7587e
                   ZBJWitKeyBusinessModuleSpecs - https://git.zhubajie.la/ZBJWitKey-iOS/ZBJWitkeyBussinessModuleSpecs.git @ 8519054824e76f3dad3163cecf56559ead8dbc42
                   zhubajie-zbjmobilecocoapodsspecs-ios-zbjbuyermodulespec - https://git.zhubajie.la/ZBJMobileCocoapodsSpecs-iOS/ZBJBuyerModuleSpec.git @ 829aa45bbb448ee4b843300b58d0405a9b1c1e49
                   zhubajie-zbjmobilecocoapodsspecs-ios-zbjmobilecommoncomponentspecs - https://git.zhubajie.la/ZBJMobileCocoapodsSpecs-iOS/ZBJMobileCommonComponentSpecs.git @ 2aef8078ebe262e6ad7fa8439e11c1b470c59ebb

Plugins

    cocoapods-deintegrate : 1.0.2
    cocoapods-plugins     : 1.0.0
    cocoapods-search      : 1.0.0
    cocoapods-stats       : 1.0.0
    cocoapods-trunk       : 1.3.0
    cocoapods-try         : 1.1.0

Podfile

    source 'https://github.com/artsy/Specs.git'
    source 'https://github.com/CocoaPods/Specs.git'
    source 'https://git.zhubajie.la/ZBJMobileCocoapodsSpecs-iOS/ZBJMobileSpecs.git'
    source 'https://git.zhubajie.la/ZBJWitKey-iOS/ZBJWitkeyBussinessModuleSpecs.git'
    source 'https://git.zhubajie.la/BJZF-IOS/BJZF-IOS-Specs.git'
    
    platform :ios, '9.0'
    
    # ignore all warnings from all pods
    inhibit_all_warnings!
    
    target 'WitKey' do
        pod 'JSONModel'
        pod 'MJRefresh'
        pod 'FMDB'
        pod 'SVProgressHUD'
        pod 'IQKeyboardManager'
        pod 'ReactiveObjC'
        pod 'Masonry'
        pod 'Qiniu', '~>7.1'
        pod 'SDWebImage'
        pod 'PNChart'
        pod 'EBForeNotification', '~> 1.0.7'
    
        #private specs
        pod 'ZBJWitKeyNetworkModule'
        pod 'BJZFMobileCashier_Vendor'
        pod 'ZBJClickStatistic'
        pod 'ZBJAppDevelopKit/Categories'
        pod 'ZBJFaceRecognition'
        pod 'ZBJNetwork-X'
        pod 'ZBJNetwork-XLoggger', :configurations => ['Debug','InHouse']
        pod 'ZBJClickStatisticLogger', :configurations => ['Debug','InHouse']
        pod 'ZBJWitKeyBaseDevKitLib'
        pod 'ZBJWitKeyCommonUIKit'
        pod 'BSFingerSDK_Vendor'
    
        #super witkey
        pod 'ZBJWitKeyModuleMediator'
        pod 'ZBJWitKeyActivityModule'
        pod 'ZBJWitKeyLoginModule'
        pod 'ZBJWitKeyQrModule'
        pod 'ZBJWitKeyUserPermissionModule'
        pod 'ZBJWitKeyTransactionManagementModule'
        pod 'ZBJWitKeyCommunicationManagement'
        pod 'ZBJWitKeyAssociationModule'  #社群模块
        pod 'ZBJWitKeyCommunityModule'  #社区模块
        pod 'ZBJWitKeySquareModule' #广场模块
        pod 'ZBJWitKeyPersonalCenterModule' #我的模块
        pod 'ZBJWitKeyFeedBackModule' #意见反馈模块
    
        #shareSDK
    #    pod 'ShareSDK3'
    #    pod 'MOBFoundation'
    #    pod 'ShareSDK3/ShareSDKPlatforms/QQ'
    #    pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
        #八戒支付里依赖了微信sdk，此处会产生冲突
    #    pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
    #    pod 'ShareSDK3/ShareSDKPlatforms/Copy'
    
        #TalkingData
        pod 'TalkingData_Vendor'
    
        #GeTui
        pod 'GTSDK'
    
        #Fabric
        pod 'Fabric'
        pod 'Crashlytics'
    end

Error

    ArgumentError - Illformed requirement `"~>"`
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:63:in `parse'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `map!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:88:in `initialize'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:34:in `new'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/requirement.rb:34:in `create'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/dependency.rb:116:in `initialize'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification/consumer.rb:210:in `new'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification/consumer.rb:210:in `block in dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification/consumer.rb:209:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification/consumer.rb:209:in `map'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification/consumer.rb:209:in `dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification.rb:326:in `block in dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification.rb:325:in `map'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification.rb:325:in `dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/specification.rb:334:in `all_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:169:in `dependencies_for'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:807:in `block in group_possibilities'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:806:in `reverse_each'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:806:in `group_possibilities'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:778:in `possibilities_for_requirement'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.4/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/resolver.rb:110:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:770:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:767:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:243:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/installer.rb:116:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/update.rb:81:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

I spent a very long time to find where should I put this `"~>"` and finaly I found it was about one of my private pods `'ZBJWitKeyCommunicationManagement'`

here is `ZBJWitKeyCommunicationManagement`'s podSpec
```
Pod::Spec.new do |s|
  s.name             = 'ZBJWitKeyCommunicationManagement'
  s.version          = '0.1.22'
  s.summary          = 'communication management module'

  s.homepage         = 'https://git.zhubajie.la/ZBJWitKey-iOS/ZBJWitKeyCommunicationManagement'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'dengsha' => 'dengsha@zbj.com' }
  s.source           = { :git => 'https://git.zhubajie.la/ZBJWitKey-iOS/ZBJWitKeyCommunicationManagement.git', :tag => s.version.to_s }

  s.ios.deployment_target = '9.0'
  s.source_files = 'ZBJWitKeyCommunicationManagement/Classes/**/*.{h,m}'
  s.resource_bundles = {
    'ZBJWitKeyCommunicationManagement' =>['ZBJWitKeyCommunicationManagement/Classes/**/*.xcassets']
  }

  s.dependency 'Masonry'
  s.dependency 'JSONModel'
  s.dependency 'DZNEmptyDataSet'
  s.dependency 'ZBJWitKeyBaseDevKitLib'
  s.dependency 'ZBJWitKeyCommonUIKit'
  s.dependency 'ZBJClickStatistic'
  s.dependency 'ZBJNetwork-X'
  s.dependency 'ZBJWitKeyModuleMediator/ZBJWKIMModule'
  s.dependency 'ZBJWitKeyModuleMediator/ZBJWKLoginModule'
  s.dependency 'ZBJWitKeyModuleMediator/ZBJWKTaskDetailModule'
end
```

so, I changed my podfile like
```
pod 'ZBJWitKeyCommunicationManagement', '~> 0.1.22'
```
then it was working.....

what makes me confuse is that why I have to add this `~>` to this pods ?
And why this podfile  worked perfect before I update cocoapods to 1.4.0 ?

**Comment by dnkoutso** [comment]
What versions have you published for the `ZBJWitKeyCommunicationManagement` pod? 

Have you also tried the `master` version of CocoaPods (soon to be 1.5.0)?

**Comment by acalism** [comment]
`pod 'XXX', ''`
I did not specify the version and left the version a zero-length string, which caused the error.
