### ISSUE TITLE
Swift dependency in Obj-C project fails linking with the AVFoundation framework

### ISSUE THREAD

**Issue by tralves** [CocoaPods/CocoaPods#7538]
🌈
# Report

## What did you do?

I am creating a pod for an Obj-C project that has a Swift pod dependency (`PlayKit`). The relevant part of the `.podspec` is: 
```ruby
  s.platform     = :ios
  s.ios.deployment_target = "9.0"
  s.frameworks  = 'Foundation', 'AVFoundation'
  s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4' }

  s.source = { :git => "https://github.com/eyzhub/weex-kdp.git", :tag => s.version }
  s.source_files  = "ios/Sources/*.{h,m,mm}"

  s.static_framework = true
  s.dependency "WeexPluginLoader"
  s.dependency "WeexSDK", "0.16.0"
  s.dependency "PlayKit"  #!!!!!!!!! <- swift dependency
```

I am running `pod spec lint --allow-warnings`.

## What did you expect to happen?

It should validate my pod.

## What happened instead?

I get the errors:
```
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Player/Media/AssetLoaderDelegate.swift:283:140: error: missing argument for parameter 'error' in call
    - NOTE  | [iOS] xcodebuild:  , error: <#NSErrorPointer#>
    - NOTE  | [iOS] xcodebuild:  AVFoundation.AVAssetResourceLoadingRequest:44:15: note: 'persistentContentKey(fromKeyVendorResponse:options:error:)' declared here
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Managers/TimeObserver.swift:261:29: error: 'schedule(deadline:repeating:leeway:)' is unavailable
    - NOTE  | [iOS] xcodebuild:  Dispatch.DispatchSourceTimer:210:17: note: 'schedule(deadline:repeating:leeway:)' was introduced in Swift 4
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Player/Tracks/TracksManager.swift:62:79: error: type 'AVMediaCharacteristic' (aka 'NSString') has no member 'audible'
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Player/Tracks/TracksManager.swift:69:79: error: type 'AVMediaCharacteristic' (aka 'NSString') has no member 'legible'
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Player/Tracks/TracksManager.swift:84:64: error: type 'AVMediaCharacteristic' (aka 'NSString') has no member 'audible'
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Player/Tracks/TracksManager.swift:106:90: error: type 'AVMediaCharacteristic' (aka 'NSString') has no member 'audible'
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Player/Tracks/TracksManager.swift:123:64: error: type 'AVMediaCharacteristic' (aka 'NSString') has no member 'legible'
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Player/Tracks/TracksManager.swift:149:89: error: type 'AVMediaCharacteristic' (aka 'NSString') has no member 'legible'
    - ERROR | [iOS] xcodebuild:  PlayKit/Classes/Player/Media/PKMediaSource.swift:108:10: error: method 'setContentUrl' with Objective-C selector 'setContentUrl:' conflicts with setter for 'contentUrl' with the same Objective-C selector
```

It seems to me that the error is caused because `PlayKit` is trying to use the Swift `AVFoundation` framework but it is linking with the Obj-C `AVFoundation` framework.
For instance, the first error is about a missing parameter `error` that exists in the [Obj-C `AVFoundation` function](https://developer.apple.com/documentation/avfoundation/avassetresourceloadingrequest/1623676-persistentcontentkeyfromkeyvendo?language=objc), but not in the corresponding [Swift `AVFoundation` function](https://developer.apple.com/documentation/avfoundation/avassetresourceloadingrequest/1623676-persistentcontentkey).

Thus, `PlayKit` fails to build.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 442116227a31718cf36e7d3957c8ea473573fca2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

The project is in a private repo, but I may get permission to publish it if it helps.

Thanks! I tried to explain the best I can, though I am not a CocoaPods/iOS expert...

**Comment by dnkoutso** [comment]
@tralves have you tried cocoapods master (which would be 1.5.0 soon)?

**Comment by tralves** [comment]
Just tried that (`sudo gem install cocoapods --pre`, right?). 

Same output.

**Comment by dnkoutso** [comment]
No, beta is not out yet. Use bundler (http://bundler.io/) to set it up quickly

**Comment by dnkoutso** [comment]
see this also http://bundler.io/v1.12/git.html

**Comment by tralves** [comment]
@dnkoutso Sorry, I don't think I understand.

I added a `Gemfile` to my project with:
```
source 'https://rubygems.org'

gem 'CocoaPods', :github => 'CocoaPods/CocoaPods',  :branch => 'master' 
```
And ran `bundle install`.

The result:
```
The git source `git://github.com/CocoaPods/CocoaPods.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/CocoaPods/CocoaPods.git
Fetching gem metadata from https://rubygems.org/..........
Could not find gem 'CocoaPods' in git://github.com/CocoaPods/CocoaPods.git (at master@0778a2a).
The source does not contain any versions of 'CocoaPods'
```

**Comment by dnkoutso** [comment]
`cocoapods` not `CocoaPods`

**Comment by dnkoutso** [comment]
Try also `gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git'`

**Comment by tralves** [comment]
Grrr. I was wrestling `bundler` but it was so simple. Anyway, not I have this error:

```
 -> WeexKdp (0.0.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (wrong number of arguments (given 4, expected 3)) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

`--verbose` didn't help either...

**Comment by dnkoutso** [comment]
@tralves also add `gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git'`

**Comment by tralves** [comment]
`bundle install` only worked with 
```gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git', :branch => '1a92ff1'```

and then the original error stays the same...

**Comment by dnkoutso** [comment]
someone will have to investigate then sorry I cant tell from here what could be wrong.

**Comment by dnkoutso** [comment]
@tralves one thing that would help a lot is if you can get a sample app demonstrating the issue.

**Comment by tralves** [comment]
Ok. I can do that.

**Comment by tralves** [comment]
I here goes my project:

How to reproduce:
``` bash
git clone https://github.com/tralves/weex-kdp
cd weex-kdp

# using the release version
pod spec lint --allow-warnings

# using master
bundle install
bundle exec pod spec lint --allow-warnings
```

**Comment by dnkoutso** [comment]
@tralves I figured it out. You have a `.swift-version` file that is set to `3.0` which `PlayKit` most likely does not work with anymore.

Furthermore your `WeexKdp.podspec` has:
```ruby
s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4' }
```

Which is *not* the way to set `SWIFT_VERSION`, change it to `s.swift_version = '4.0'`

Also remove your `.swift-version` file entirely since it has been deprecated in 1.4.0.

**Comment by dnkoutso** [comment]
I was able to successfully compile. Also `spec lint` will do remote clone so make sure you update the tag of your version first and also use `lib lint` for local linting

**Comment by dnkoutso** [comment]
Basically I think the version of `PlayKit` was published with Swift 3.0 but with older Xcode version and it does not seem to work with Xcode 9 or so.

Setting the `SWIFT_VERSION` to `4.0` does the trick but the maintainer should update their library.

**Comment by tralves** [comment]
@dnkoutso Oh wow, thanks! I didn't test it yet, but you certainly went further that what I'd expect as a maintainer. Do you have a patreon or paypal? I'd like to buy you a beer or something!

**Comment by dnkoutso** [comment]
ha, np my friend, my pleasure
