### ISSUE TITLE
Swift static library support + FireBase/Core + beta 1.5.0.beta.1 =>  error 'Include of non-modular header inside framework module'

### ISSUE THREAD

**Issue by jogu** [CocoaPods/CocoaPods#7542]
🌈
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Tried to use the FireBase/Core pod with CocoaPods new to 1.5.0 beta 1 swift static library support.

## What did you expect to happen?

The build would work. (Or at least I /hoped/ the build would work!)

## What happened instead?

The build failed with:

/Users/joseph/Documents/podtest/fbpodtest/Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.framework/Headers/FIRAnalyticsConfiguration.h:1:9: Include of non-modular header inside framework module 'FirebaseAnalytics.FIRAnalyticsConfiguration': '/Users/joseph/Documents/podtest/fbpodtest/Pods/Headers/Public/FirebaseCore/FirebaseCore/FIRAnalyticsConfiguration.h'

If I remove put back 'use_frameworks!' everything works fine, but I am hoping to switch my project over to static libraries.

I tried setting 'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' everywhere I could and was surprised to find it didn't help.

I'm struggling to figure out if this is an Xcode problem, a firebase problem or a cocoapods problem. I've done a reasonable search but I couldn't find any evidence anyone else had ever run into this problem. I've tried with Firebase/Core 4.10.1 and 4.11 (latest) and it happens with both.

### Stack

```
   CocoaPods : 1.5.0.beta.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : local - /Users/joseph/Documents/cocoa-private/Specs.git/ @ 4ecf5cc02bd9b5d2ae860056d47ef12baf16843c
               local-1 - /Users/joseph/.cocoapods/repos/local @ 4ecf5cc02bd9b5d2ae860056d47ef12baf16843c
               localhost-users-joseph-documents-cocoa-private-specs - file://localhost/Users/joseph/Documents/cocoa-private/Specs.git @ 4ecf5cc02bd9b5d2ae860056d47ef12baf16843c
               master - https://github.com/CocoaPods/Specs.git @ 28311463bf45b46e18b1ee403606f9d56b81825a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fbpodtest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for fbpodtest
  pod 'Firebase/Core', '4.10.1'

end
```

## Project that demonstrates the issue

https://github.com/jogu/fbposttest

**Comment by dnkoutso** [comment]
Thanks for detailed report, this might be a Firebase pod specific issue but we should ensure that is the case first.

**Comment by jogu** [comment]
Thanks @dnkoutso.  Yes, it could well be pod specific. TBH what Google are doing here does look at bit dodgy to me, but equally it seems it worked okay before.

I've run into several issues trying to rid my project of use_frameworks!. At least one is definitely a pod specific error (XLPagerTabStrip, including a .xib file in source_files), but some have been harder to figure out.

**Comment by paulb777** [comment]
This is a known issue with FirebaseAnalytics that is planned to be fixed in the next Firebase major release.

To workaround, you can do a post_install step similar to https://github.com/firebase/firebase-ios-sdk/blob/master/Example/Podfile#L217.

Your test repo builds if ./Pods/FirebaseAnalytics/Frameworks/FirebaseAnalytics.framework/Headers/FirebaseAnalytics.h is updated similarly.

There is also potentially a CocoaPods issue since CocoaPods 1.4.0 didn't expose this problem.

**Comment by paulb777** [comment]
OK, not a CocoaPods 1.4.0 issue, because CocoaPods 1.4.0 did not support Swift modules without use_frameworks!

**Comment by jogu** [comment]
Thank you @paulb777 ! It seems that patch solves the issue in my 'real' app too (though I can't be absolutely 100% sure until I solve all the other issues...).

I agree it's not a regression. I presume it makes sense to close this issue then, given Paul has opened a new issue to track it in the firebase repo. (If there's a reason to keep it open, please feel free to reopen!)
