### ISSUE TITLE
Swift static library support + FBSDKLoginKit + beta 1.5.0.beta.1 => error: no such module 'FBSDKLoginKit'

### ISSUE THREAD

**Issue by jogu** [CocoaPods/CocoaPods#7543]
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Tried to use the FBSDKLoginKit pod with CocoaPods new to 1.5.0 beta 1 swift static library support.

## What did you expect to happen?

The build would work. (Or at least I /hoped/ the build would work!)

## What happened instead?

The build failed with:

/Users/joseph/Documents/podtest/fbpodtest/fbpodtest/ViewController.swift:10:8: error: no such module 'FBSDKLoginKit'

### Stack

```
   CocoaPods : 1.5.0.beta.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.2 (9C40b)
         Git : git version 2.10.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : local - /Users/joseph/Documents/cocoa-private/Specs.git/ @ 4ecf5cc02bd9b5d2ae860056d47ef12baf16843c
               local-1 - /Users/joseph/.cocoapods/repos/local @ 4ecf5cc02bd9b5d2ae860056d47ef12baf16843c
               localhost-users-joseph-documents-cocoa-private-specs - file://localhost/Users/joseph/Documents/cocoa-private/Specs.git @ 4ecf5cc02bd9b5d2ae860056d47ef12baf16843c
               master - https://github.com/CocoaPods/Specs.git @ 172f11bafe17c797972f7bbfc94f81a51e0d770d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fbpodtest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for fbpodtest
  pod "FBSDKLoginKit"

end
```

## Project that demonstrates the issue

https://github.com/jogu/facebookpodtest

**Comment by paulb777** [comment]
There is also potentially a CocoaPods issue since CocoaPods 1.4.0 didn't expose this problem.

**Comment by jogu** [comment]
@paulb777 Thanks! I suspect at least your first comment is meant for #7542 ?

**Comment by paulb777** [comment]
Yes - fixing now ...

**Comment by jogu** [comment]
The "youtube-ios-player-helper" pod seems to fail in the same way.

**Comment by dnkoutso** [comment]
@jogu I think you are hitting errors from pods who need to be updated correctly.

Will be trying out FBSDKLoginKit myself though first to confirm the above statement.

**Comment by rafaelsfarias** [comment]
@jogu Did you manage to get this working?

**Comment by jogu** [comment]
@rafaelsfarias  I've not had a chance to go back and try it again, so no idea if it works now or not.
