### ISSUE TITLE
Cocoapods.org site searches not working

### ISSUE THREAD

**Issue by pmiotto** [CocoaPods/CocoaPods#7545]
# Report

## What did you do?
Go to cocoapods.org and search for a package

## What did you expect to happen?
A search result to appear

## What happened instead?
Nothing

## CocoaPods Environment
Website

## Project that demonstrates the issue
Console shows that the request to https://aws-search.cocoapods.org/api/v1/pods.picky.hash.json?query=a&ids=20&offset=0&sort=quality does not finish

**Comment by MartinSchultz** [comment]
Same here, doesn't work since a couple of days.

**Comment by segiddins** [comment]
It looks like we're getting 504s. @DanToml do we need to restart aws-search ?

**Comment by DanToml** [comment]
@segiddins Judging by the memory graphs in EC2 things look weird, I'll ssh into a box and take a look at logs tonight.

I think I remember seeing a db maintenance email from heroku recently, so maybe some creds got rolled.

**Comment by alexanderathan** [comment]
Bump. Same for me.

**Comment by antonioreyna** [comment]
search not working today either :(

**Comment by vagautham** [comment]
Tried it today. Not working yet

**Comment by orta** [comment]
I'm gonna lock this for +1s until @DanToml can get some time to look at it

**Comment by DanToml** [comment]
Taking a look into this now, I didn't have the ssh key for those hosts on my laptop.

**Comment by DanToml** [comment]
I just tried rebooting the containers - They'll probably take a little while to reindex, so I'll check in on them in the morning. Heading to 💤 now.

**Comment by DanToml** [comment]
I just deployed another patch which _should_ work. Just waiting for it to index.

**Comment by dnkoutso** [comment]
Its back online. Closing.
