### ISSUE TITLE
the copy resources shell script copied all Asset.xcassets, including these in PODS_ROOT path

### ISSUE THREAD

**Issue by hanshuaiLoopeer** [CocoaPods/CocoaPods#7550]
in copy_resources_script.rb

```
# Find all other xcassets (this unfortunately includes those of path pods and other targets).
  OTHER_XCASSETS=$(find "$PWD" -iname "*.xcassets" -type d)
  while read line; do
    if [[ $line != "${PODS_ROOT}*" ]]; then
      XCASSET_FILES+=("$line")
    fi
  done <<<"$OTHER_XCASSETS"
```
`if [[ $line != "${PODS_ROOT}*" ]]; then` maybe wrong. It always fail.
Maybe it should be `if [[ $line != ${PODS_ROOT}* ]]; then` 

`$line != "${PODS_ROOT}*"` and `$line != ${PODS_ROOT}*` is different in shell script

**Comment by dnkoutso** [comment]
Dup of https://github.com/CocoaPods/CocoaPods/issues/6159

**Comment by dnkoutso** [comment]
Please respond there with ideas and comments

**Comment by hanshuaiLoopeer** [comment]
I mean，is there any spell error in `if [[ $line != "${PODS_ROOT}*" ]]; then`?
It seems this line does not make sense, it always fail.

**Comment by dnkoutso** [comment]
@hanshuaiLoopeer not sure i understand, is this an issue you have that xcassets are *not* copied or that *all* of them are copied (in this case the same as #6159)

Can you please upload a sample app demonstrating the issue? Then I can re-open this.

**Comment by hanshuaiLoopeer** [comment]
This case is similar but not the same as #6159 

My pod file like this
```
target 'Target1' do
    platform :watchos,'2.0'
    pod 'Target1Module'
end

target 'Target2' do
    platform :ios, '10.0'
    pod  'Target2Module'
end

```
as #6159, members in target should like this

Target | Members
----|------
Target1 | Target1.xcassets, Target2.xcassets, Target1Module.xcassets  
Target2 | Target1.xcassets, Target2.xcassets, Target2Module.xcassets  

but, in fact, we get this

Target | Members
----|------
Target1 | Target1.xcassets, Target2.xcassets, Target1Module.xcassets, Target2Module.xcassets
Target2 | Target1.xcassets, Target2.xcassets, Target1Module.xcassets, Target2Module.xcassets

in https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/copy_resources_script.rb#L210

`if [[ $line != "${PODS_ROOT}*" ]]; then` maybe wrong. It always fail.
It means to search for all .xcasset bundles outside of the Pods folder and bundles them in.
but in fact, It search for all .xcasset bundles, including Pods folder. 
Maybe it should be `if [[ $line != ${PODS_ROOT}* ]]; then`

**Comment by rock88** [comment]
Hi, any news or workaround? Tips from #6159 didn't work.
