### ISSUE TITLE
https://cocoapods.org/ Anything Search text not working. Its 504 error

### ISSUE THREAD

**Issue by khetaram** [CocoaPods/CocoaPods#7552]

**Comment by ejosephwilson** [comment]
Getting same error. Screenshot attached
![image](https://user-images.githubusercontent.com/18560418/38037264-17a1dd52-326e-11e8-8a94-ef31664997d2.png)

**Comment by dnkoutso** [comment]
Dup https://github.com/CocoaPods/CocoaPods/issues/7545
