### ISSUE TITLE
 You are not allowed to push new versions for this pod.

### ISSUE THREAD

**Issue by Arc-lin** [CocoaPods/CocoaPods#7553]
Hello~
I have create a lib last year, but I use my company's email `arclin@dankal.cn` by mistake,  now I am leaving the company, so my email could not be used, how could I change the pod's owner to 'm13643046965@163.com' my new email

pod's github address is https://github.com/Arc-lin/ALCalendarPicker

**Comment by dnkoutso** [comment]
Please use the dispute system to re-claim the pod https://trunk.cocoapods.org/claims/new
