### ISSUE TITLE
spec.vendored_frameworks = '../Foo.framework' does not work

### ISSUE THREAD

**Issue by torarnv** [CocoaPods/CocoaPods#7554]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

`spec.vendored_frameworks = '../Foo.framework'` fails, as the final `xcconfig` is missing the right `FRAMEWORK_SEARCH_PATHS` to look up the framework. 

It should be possible to reference a relative framework paths, so that you can have your specs in `$PROJECT/lib/specs` and framework/libs in `$PROJECT/lib`

Thanks!

**Comment by segiddins** [comment]
Please upload a sample project that demonstrates the issue, as requested in the issue template.

**Comment by torarnv** [comment]
[cocoapods-reproducer.zip](https://github.com/CocoaPods/CocoaPods/files/1855676/cocoapods-reproducer.zip)

**Comment by torarnv** [comment]
An alternative here would be to allow `:file` in `spec.source`, so that `pod 'Foo', :path => '/tmp/myspecs'` would allow `/tmp/myspecs/Foo.podspec` to point to `/tmp/myframeworks`

**Comment by torarnv** [comment]
Allowing `:file` in `spec.source` would also fit nicely with allowing `source '/tmp/myspecs`. The latter works today somewhat, using `source 'file:///tmp/myspecs'`, but that path needs to be a git repository, which makes it awkward to work with for a local spec repository during development, and also tricky to provide something like https://bugreports.qt.io/browse/QTBUG-42933

**Comment by torarnv** [comment]
Are there existing issues for allowing `:file` in `spec.source`, and allowing local non-git paths in `source`?

**Comment by segiddins** [comment]
> Are there existing issues for allowing :file in spec.source

No, that is not something that CocoaPods will support

**Comment by segiddins** [comment]
You can't specify any file patterns that live above the podspec, directory-wise. 

Running `pod lib lint` gives the following error:

```
 -> Foo (1.0)
    - WARN  | source: Git sources should specify a tag.
    - ERROR | file patterns: The `vendored_frameworks` pattern did not match any file.
    - WARN  | license: Unable to find a license file
```

**Comment by dnkoutso** [comment]
The podspec must be at the root of the repo, AFAIK the only way `../Foo.framework` would work is when consumers of your pod use it using `:path` directive (i.e for local development)

**Comment by dnkoutso** [comment]
@torarnv I am going to close this issue, please feel free to comment further here and see if there is anything we can add to the library I can re-open.

**Comment by torarnv** [comment]
> You can't specify any file patterns that live above the podspec, directory-wise.

I know, that's what I'm reporting as the issue :)

**Comment by torarnv** [comment]
@dnkoutso See https://bugreports.qt.io/browse/QTBUG-42933 for reference.

The use-case is that I'd like to add CocoaPods support to Qt, so that you can depend on Qt using CocoaPods. But most developers get their Qt libraries from:

1.  Building Qt locally, e.g. during development of Qt
2. Installing from the Qt binary installer
3. Via Homebrew

In all of these you end up with a local installation of Qt somewhere on the filesystem. I'd like to bundle `.podspec` files with this install, that users of CocoaPods can point their Podfiles to, to depend on Qt.

We do the same for e.g. CMake and pkg-config.

**Comment by dnkoutso** [comment]
You can place the podspec in the root of your folder as per requirement by CocoaPods (predates me).

The only two ways supported in which the podspec does not live in the root of the repo is by using  `:path` or `:podspec` directory in your `Podfile`.

I haven't tried `:podspec` but I know for a fact `:path` works.

Like so:
```ruby
pod 'SomePod', :path => './some/path/to/my.podspec'
```

Does this work for you?

**Comment by shamilovtim** [comment]
Please reopen this. Having this ability is valuable especially now that monorepos are popular and repositories are organized in various ways. The following is a perfectly valid setup:

```
./
./my-wrapper/mywrapper.podspec
./my-sdk/MySdk.framework
```
There's no great reason that you shouldn't be able to pull a framework locally one folder up. It's valid for local development.
