### ISSUE TITLE
Subspec module_name support

### ISSUE THREAD

**Issue by avi-kik** [CocoaPods/CocoaPods#7556]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint --allow-warnings`

## What did you expect to happen?

Successfully lint podspec.

## What happened instead?

Received an error:
```
 -> StellarKit (0.2.7)
    - ERROR | [iOS] attributes: Can't set `module_name` attribute for subspecs (in `StellarKit/StellarErrors`).
    - ERROR | [iOS] unknown: Encountered an unknown error (The `StellarKit` pod failed to validate due to 1 error:
    - ERROR | [iOS] attributes: Can't set `module_name` attribute for subspecs (in `StellarKit/StellarErrors`).
```

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/avi/.rbenv/versions/2.3.1/lib
Repositories : kik - git@github.com:kikinteractive/cocoapods.specs @ bfe749946da6db5e93e7e1d5eb057f2c78634776
               master - https://github.com/CocoaPods/Specs.git @ e5aae1392e9b008b48bc01be71c834273ed49231
```

### Installation Source

```
Executable Path: /Users/avi/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.3
```

**Comment by paulb777** [comment]
I believe this is correct functionality. Subspecs choose what gets built into a particular pod/library/module.  If multiple subspecs are chosen, they're consolidated into one pod/library/module, so it does not make sense to be able to set a module_name on an individual subspec.

**Comment by dnkoutso** [comment]
That is correct. The way things are modeled currently subspecs all merge into a top level target named after the root one and do not create a separate target.

There are no plans to change this at the moment, sorry.
