### ISSUE TITLE
You are not allowed to push new versions for this pod.

### ISSUE THREAD

**Issue by simformsolutions** [CocoaPods/CocoaPods#7557]
We have created one social login pod which is dependent on FacebookLoginKit, So we have mention dependency like 
`  s.dependency 'FBSDKLoginKit'`

but while publishing we got error like

**You (reg@simform.in) are not allowed to push new versions for this pod. The owners of this pod are nlutsenko@me.com and cocoapods@fb.com.**

Please help.

**Comment by orta** [comment]
Please use the trunk dispute system for this - https://trunk.cocoapods.org/claims/new
