### ISSUE TITLE
NoMethodError - undefined method `version' for nil:NilClass

### ISSUE THREAD

**Issue by awanglilong** [CocoaPods/CocoaPods#7560]
### Command

```
/Users/wanglilong/.rvm/rubies/ruby-2.4.1/bin/pod list
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.5.0.beta.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.12.6 (16G1212)
       Xcode : 9.1 (9B55)
         Git : git version 2.13.6 (Apple Git-96)
Ruby lib dir : /Users/wanglilong/.rvm/rubies/ruby-2.4.1/lib
Repositories : .git - https://github.com/CocoaPods/Specs.git @ e8783d55ad2eb614677f08ee2c258df0fbbf5fbf
               master - https://github.com/CocoaPods/Specs.git @ c099e26a559c249a8302fc5bb25df99a92cbde90
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'new' do
pod 'AFNetworking', '~> 3.2.0'

end
```

### Error

```
NoMethodError - undefined method `version' for nil:NilClass
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/user_interface.rb:209:in `pod'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/command/list.rb:24:in `block in run'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/command/list.rb:24:in `each'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/command/list.rb:24:in `run'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/wanglilong/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `load'
/Users/wanglilong/.rvm/rubies/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `eval'
/Users/wanglilong/.rvm/gems/ruby-2.4.1@global/bin/ruby_executable_hooks:15:in `<main>'

**Comment by awanglilong** [comment]
when I run pod install,  show  [!] Unable to find a specification for `AFNetworking (~> 3.2.0)`.This problem is still in，after  I have unloaded installed several times.

**Comment by dnkoutso** [comment]
seems like a problem with your master specs repo.

What is `ls -l ~/.cocoapods/repos/master/Specs` print?

Going to close to start with as the same example works for me.

**Comment by dnkoutso** [comment]
Will re-open if this appears to be an issue with the library itself.

**Comment by dnkoutso** [comment]
Also please fill in further the template with exactly what command you are executing.

**Comment by awanglilong** [comment]
ls -l ~/.cocoapods/repos/master/Specs.  print
total 0
drwxr-xr-x  19 wanglilong  staff  646  3 30 09:12 0
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:37 1
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:37 2
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:37 3
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:37 4
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:37 5
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:37 6
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 7
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 8
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 9
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 a
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 b
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 c
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 d
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 e
drwxr-xr-x  18 wanglilong  staff  612  3 30 07:38 f
