### ISSUE TITLE
pod update with private spec

### ISSUE THREAD

**Issue by wangjindong** [CocoaPods/CocoaPods#7562]
I don't want to update master,but can update my private spec.
Any idea for me？
tks!!!

for example：pod update --no-repo-update master 
Can it be supported！！！

**Comment by dnkoutso** [comment]
There is no way to do this right now unfortunately.

The best (which is pretty bad) way to do it is mirror your public master repo dependencies in your private repo and remove the master specs repo from your `Podfile`.

Truly hope that this year we will get rid of the master specs repo entirely for CocoaPods.
