### ISSUE TITLE
Can't search libraries on CocoaPods web application

### ISSUE THREAD

**Issue by Tzoani** [CocoaPods/CocoaPods#7563]
Search on "https://cocoapods.org"

<img src="https://dl.dropboxusercontent.com/s/zjyd81mvstvm61q/Screen%20Shot%202561-03-30%20at%2010.09.27.png" style="width: auto; height: auto;"/>

**Comment by dnkoutso** [comment]
Dup https://github.com/CocoaPods/CocoaPods/issues/7545
