### ISSUE TITLE
Site search still not working

### ISSUE THREAD

**Issue by Jules2010** [CocoaPods/CocoaPods#7564]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Try the cocoapods site search 

## What did you expect to happen?

Return some results

## What happened instead?

A 504 timeout error could be seen in dev tools.

## CocoaPods Environment

N/A

## Project that demonstrates the issue
N/A

**Comment by dnkoutso** [comment]
Dup https://github.com/CocoaPods/CocoaPods/issues/7545
