### ISSUE TITLE
Is there anyway to make cocoapods use cache first when I want to use the bleeding edge version of a Pod? 

### ISSUE THREAD

**Issue by intspt** [CocoaPods/CocoaPods#7565]
Podfile
    `pod 'QQSDKStatic', :git => 'http://xxx.com/xxx/qqsdkstatic.git'`

local pod cache
> QQSDKStatic:
>   - Version: 1.0.0
>     Type:    External
>     Spec:    /Users/spt/Library/Caches/CocoaPods/Pods/Specs/External/QQSDKStatic/92bec12f8440cd451c4fd0582aa43a76.podspec.json
>     Pod:     /Users/spt/Library/Caches/CocoaPods/Pods/External/QQSDKStatic/0c2c223d2e0d598522ccd35fb4cb7567-3bf00

pod update --no-repo-update --verbose
> -> Pre-downloading: `QQSDKStatic` from `http://code.corp.elong.com/iosstaticframework/qqsdkstatic.git`
>  > Git download
>  > Git download
>      $ /usr/bin/git clone http://code.corp.elong.com/iosstaticframework/qqsdkstatic.git
>      /var/folders/0k/9w0xj_jx24nfd8sn0fjxlx8r0000gn/T/d20180330-14502-1xvirp7 --template= --single-branch --depth 1
>      Cloning into '/var/folders/0k/9w0xj_jx24nfd8sn0fjxlx8r0000gn/T/d20180330-14502-1xvirp7'...
>   $ /usr/bin/git -C /var/folders/0k/9w0xj_jx24nfd8sn0fjxlx8r0000gn/T/d20180330-14502-1xvirp7 rev-parse HEAD
>   5523b485b06819059dce74f9b05b4c0664c5664a
>   > Copying QQSDKStatic from `/Users/spt/Library/Caches/CocoaPods/Pods/External/QQSDKStatic/92bec12f8440cd451c4fd0582aa43a76` to `Pods/QQSDKStatic`

local pod cache after pod update
> QQSDKStatic:
>   - Version: 1.0.0
>     Type:    External
>     Spec:    /Users/spt/Library/Caches/CocoaPods/Pods/Specs/External/QQSDKStatic/92bec12f8440cd451c4fd0582aa43a76.podspec.json
>     Pod:     /Users/spt/Library/Caches/CocoaPods/Pods/External/QQSDKStatic/0c2c223d2e0d598522ccd35fb4cb7567-3bf00

same as before
but git clone again

**Comment by segiddins** [comment]
No, because CocoaPods has no way of knowing what the `HEAD` of `master` of the git repo will be

**Comment by dnkoutso** [comment]
close?
