### ISSUE TITLE
LoadError - cannot load such file -- nanaimo

### ISSUE THREAD

**Issue by erinson** [CocoaPods/CocoaPods#7566]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Try `gem install nanaimo` first.

Please fill in the template and additionally use StackOverflow using `cocoapods` tag for these questions.

**Comment by erinson** [comment]
all time error

**Comment by meAbhishekTripathi** [comment]
Hello Erison,

 Did you find any solution for the problem? As I have same set of errors on installation of pod for a Xcode project. 

Let me know if you find any solution.

Thanks

**Comment by meAbhishekTripathi** [comment]
Hey Erison,

Seems there is problem with the version of cocoa pod for as we were using version 1.4.0 but after using command
$ [sudo] gem install cocoapods --pre

from link:
https://guides.cocoapods.org/using/getting-started.html#getting-started

worked out and it is currently working fine. 

Thanks

**Comment by erinson** [comment]
Hi 

Thank you can solve the problem using  using this command sudo gem install cocoapods —pre

**Comment by cotrim149** [comment]
Hello,

The same thing happens to me. 

I solved that uninstalling all versions of cocapods and nanaimo. Every gem uninstall command I set to remove all versions.
In order of commands:

gem uninstall cocoapods 
gem uninstall -i /Users/cotrim/.rvm/gems/ruby-2.2.1@global cocoapods -> Removing from global gems

than:
gem uninstall nanaimo
gem uninstall -i /Users/cotrim/.rvm/gems/ruby-2.2.1@global nanaimo -> Again, removing from global.

and last step:
gem install cocoapods -> This last step install nanaimo and cocoapods.

now, pod install works. 😄 

I Hope  have helped you.

**Comment by G1King** [comment]
@cotrim149  thank you very much! Success solved my problem.

**Comment by yanctrindade** [comment]
Ty @cotrim149 , legendary.

**Comment by zanyfly** [comment]
Thanks @cotrim149， it works for me

**Comment by ccChucker** [comment]
I followed the steps listed above but am still having the same issue.  To clarify, I'm running fastlane to install pods in a project.

**Comment by cotrim149** [comment]
@ccChucker 
try put the commands in a .sh script and make fastlane call it.

And you are using the rubi version from mac, re-installed ruby version (removed the pre-installed ruby and installed using brew) or rbenv ?

**Comment by ccChucker** [comment]
My problem was fixed by uninstalling and re-installing npm.  I'm now using bundler and this seems to be much better now.
