### ISSUE TITLE
Project interdependencies for real

### ISSUE THREAD

**Issue by ianbytchek** [CocoaPods/CocoaPods#7568]
I have a relatively large project with 30 targets equally split into apps, libs and tests. The hierarchy isn't overly crazy, but some libs have interdependencies between each other and final targets might include one, but not others. That's where problems begin. Imagine a [simple project](https://github.com/ianbytchek/InterPod) with targets:

```ruby
# Lib Foo              # depends on ReactiveSwift
# Framework Bar        # depends on Foo
# Tests Bar            # depends on Bar

project 'InterPod.xcodeproj'
platform :osx, '10.12'

target 'Foo' do
  use_frameworks!
  pod 'ReactiveSwift'
end

target 'Bar' do
  use_frameworks!
  target 'BarTests' do
    use_frameworks!
  end
end

```

Build throws `ld: framework not found ReactiveSwift` error. Adding ReactiveCocoa into Bar makes this go away. Turning Bar into a lib works good (if not mistaken), turning Foo into a framework compiles, but fails with `image not found` runtime error. Removing BarTests from Bar leads to a bunch of other issues, not so much on this example, but with the real project.

From looking at [other](https://github.com/CocoaPods/CocoaPods/search?utf8=%E2%9C%93&q=%22framework+not+found%22&type=Issues) [issues](#7558) this seems like a common issue or issue category. I've looked under the hood and understand how huge of a project CocoaPods is and that current approach wasn't chosen for no reason. But I really want to understand a few things and hopefully contribute a fix.

Does CocoaPods look into actual target interdependency graph and create final target frameworks search paths and embed pods frameworks lists out of that or purely based on dependencies defined Podfile? Unless there's a bug, the latter seems to be the case. Don't you think this would be the right approach that would solve many headaches?

In other words, wouldn't it be best to have the following Podfile and allow CocoaPods to find that BarTests depends on Bar, which depends on Foo and therefore BarTests must link against Foo pods and include them into frameworks search path?

```ruby
target 'Foo' do
  use_frameworks!
  pod 'ReactiveSwift'
end

target 'Bar' do
  use_frameworks!
end

target 'BarTests' do
  use_frameworks!
end
```

I'm coming from Carthage background where this kind of linking would be done manually and it's a nightmare. CocoaPods solves many issues, but without automating this the only option is to manually find all internal framework dependencies and `pod` them into final app and test targets. Or create Podspecs for internal frameworks and include them in Podfile, which would overkill the workflow.

Am I talking sense or have a completely wrong perspective on the subject?

**Comment by dnkoutso** [comment]
AFAIK there are two paths which CocoaPods tries to perform some analysis between targets.

1) Extensions and copying targets of extensions into the app host. I do not have a lot of experience with extensions but I am fairly certain there might be a few issues there.

2) When a `target` is nested within a target in your `Podfile` this means that all dependencies of the parent should be available to the child target. If `inherit! :search_paths` is specified on the child target then this means "do not actually LINK my parent targets dependencies" but instead just provide the search paths only. This is useful for test targets which frequently use the parent as the app host. Things can get complicated there because CocoaPods must ensure the test target does not link the same dependencies as the parent which causes warnings of duplicate classes.

In your first example above CocoaPods did the right thing. There is no nesting between the targets therefore `ReactiveSwift` is not linked into `Bar`. You either have to move the `pod` declaration outside to the root (in which case it applies to ALL targets) or nest `Bar` within `Foo`.

There are *many* combinations where things can go wrong. CocoaPods is fairly opinionated and works on most cases but its not surprising when you try to deviate from the norm to find edge cases for us to fix.

@ianbytchek I do not see an action item for the library itself here so I am going to close and continue this discussion unless we converge on an actual issue here that is reproducible and then I can re-open.

**Comment by dnkoutso** [comment]
The most common case is:
```ruby

pod 'CommonPod'

target 'App1' do
  use_frameworks!
  pod 'App1Pod'

  target 'App1Tests' do
    inherit! :search_paths # Use all pods from `App1` into `App1Tests` target but don't link them.
  end

  target 'App3' # `App3` is nested within `App1` so `App1Pod` will be part of it and also linked.
end

target 'App2' do
  pod 'App2OnlyPod'
end

```

**Comment by dnkoutso** [comment]
One last thing to note, CocoaPods *does not* at the moment try to be smart around figuring out which pods should actually be linked into a dynamic framework and instead will *always* link all pods to the top level target instead.

For CocoaPods 2.0 we might want to re-think this but no active plans right now.

**Comment by ianbytchek** [comment]
Thanks for a detailed and enlightening response. That all does make sense.

My argument (more of a curiosity really) is coming from the fact that semantically parent-child approach doesn't always make sense. It assumes clear one-to-one relations between targets, like framework, framework tests, and app that uses that framework. In a simple case, like above, it works perfectly. But with 10 *project-internal* framework targets, where some depend on others it simply not possible to define that linear dependency:

```
libA: pod …
libB: pod … + (depends on libA)
libC: (depends on libA)
libX: (depends on libB, libC)
App: pod … + (depends on libC, libX)
```

👆 libB perhaps could be inherited from libA, but libX cannot be inherited from from both libB and libC (if not semantically, then because `target 'libX'` cannot be used twice a Podfile), neither should App be a child of any lib. There used to be `link_with` command, which probably would work in this case, but it's gone and probably for a good reason. 

I also saw [artsy/eigen Podfile](https://github.com/artsy/eigen/blob/master/Podfile) and guessing that they have fully separated those internal targets into independent projects, which can be included straight with CocoaPods. This makes sense for bigger projects, but not for self-contained ones that simply want a modest separation of concern.

On another hand, what I'm really interested in figuring out: we already have Xcode project that fully defines target dependencies, so instead of replicating (to a limited degree) these relations in Podfile, CocoaPods could just take them as a fact. This at once would eliminate the need for `target('Foo') { target 'FooTests' }` and leave the power of proper abstract configurations so much missing in Xcode.

Perhaps I'm missing a point (?), but wouldn't this be the most straight forward thing to do opposite to being smart? 🙂 Podfile would get way simpler, where we'd just say which targets need which pods and the rest would come from existing project. Again, maybe I'm missing something obvious, but chances of this going wrong are zero to none, aren't they?

**Comment by dnkoutso** [comment]
>10 project-internal framework targets,

@ianbytchek do you mean those are "dynamic framework" targets or static library targets? I believe you can specify `target 'MyFramework'` and add pods to it. As I said in my comment above I think all of those will eventually be linked into the app that `MyFramework` depends upon.

**Comment by ianbytchek** [comment]
Some are dynamic frameworks, some are static libraries. I've figured out several ways to make everything work as required. Besides it looking monstrous I don't have any serious problems. 

With this issue I want to figure out if the described approach for automatic dependency assessment is a valid idea. I'd dig into the code, but CocoaPods is huge and first I want an opinion from who's familiar with the matter. If in theory it makes things simpler and DRYer, I'd experiment with this idea further.
