### ISSUE TITLE
header_dir adds an extra folder in the Headers folder

### ISSUE THREAD

**Issue by fandyfyf** [CocoaPods/CocoaPods#7569]
# Report

## What did you do?

I am trying to compile a pod with `use_modular_headers!` on 1.5.0.beta.1

The Pod has the following structure.
`Pod_A/PublicHeaders/*.h`
`Pod_A/*.{m,h}`

## What did you expect to happen?

After ran `pod _1.5.0.beta.1_ install`, I expect to see all the public headers under
`Pods/Public/Pod_A/*.h`

## What happened instead?

Instead I got an extra folder
`Pods/Public/Pod_A/Pod_A/*.h`

I wonder if there is something messed up in the PodSpec of the pod I was trying to use.
Please see following,

```
  s.default_subspecs = 'Default'

  s.header_dir       = 'Pod_A'
  s.module_name      = 'Pod_A'

  s.subspec 'Default' do |default|
    default.source_files = ['Pod_A/*.{h,m}' , 'Pod_A/PublicHeaders/*.h']
    default.public_header_files = ['Pod_A/PublicHeaders/*.h']
  end

```

After I removing  `s.header_dir = 'Pod_A' ` it seems all working fine.

**Comment by dnkoutso** [comment]
The nesting is intentional for 1.5.0.beta.1 since it provides the stage for us to do modular headers correctly.

I think the right approach here is for you to remove that from your podspec.

**Comment by fandyfyf** [comment]
Hi there, do you mean removing `s.header_dir = 'Pod_A'` ?

**Comment by dnkoutso** [comment]
What is the name of the podspec? Is it `Pod_A`?

**Comment by fandyfyf** [comment]
Yes. `Pod_A` is the name

**Comment by dnkoutso** [comment]
I think you can delete it then.

**Comment by fandyfyf** [comment]
Thank you!
