### ISSUE TITLE
How to uninstill please

### ISSUE THREAD

**Issue by hcri50** [CocoaPods/CocoaPods#7572]
I am unable to install no cocoapods no more. I can not even use terminal no more. For it gives me an error. How can I unstall CocoaPods App.
So that I can use my terminal again 
How will I be alerted with instructions? please. Right now I am DEAD IN THE WATER. 
Unable to install Alamofire and SwiftyJSON. My two very important cocoapods.

desaeger@hcri.com

Last login: Sun Apr  1 19:00:36 on ttys000
Roberts-MacBook-Pro:CustomAlamofireAndSwiftyJSON hcri50$ pod init
[in /Users/hcri50/Desktop/Nervino]

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.2 (17C88)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : abtsoftware - https://github.com/ABTSoftware/PodSpecs.git @ 6a04a24a25c3a25ef4bfa2f4b818a25c0171b0c7
               master - https://github.com/CocoaPods/Specs.git @ 372840c2a03e683496f3fd317ad1a28814b048b5
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nervino' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nervino
  pod 'Charts'
  pod 'Highcharts'
  pod 'SVProgressHUD'
  pod 'SwiftyJSON'
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage', '~> 3.3'
    pod 'SVProgressHUD'
  
end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.3/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.3/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Unknown+object+version.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - RuntimeError - [Xcodeproj] Unknown object version.
   https://github.com/CocoaPods/CocoaPods/issues/7458 [closed] [7 comments]
   14 hours ago

 - RuntimeError - [Xcodeproj] Unknown object version.
   https://github.com/CocoaPods/CocoaPods/issues/6992 [closed] [10 comments]
   2 days ago

 - RuntimeError - [Xcodeproj] Unknown object version.
   https://github.com/CocoaPods/CocoaPods/issues/6991 [closed] [11 comments]
   03 Feb 2018

and 30 more at:
https://github.com/cocoapods/cocoapods/search?q=[Xcodeproj]%20Unknown%20object%20version.&type=Issues&utf8=✓
Roberts-MacBook-Pro:CustomAlamofireAndSwiftyJSON hcri50$

**Comment by dnkoutso** [comment]
Update the xcodeproj gem `gem update xcodeproj`.

Please also use StackOverflow under `cocoapods` tag for these questions.

**Comment by dnkoutso** [comment]
Then maybe update to cocoapods 1.5.0.beta.1? It seems your `xcodeproj` gem is out of date. You are on 1.5.3 but should go to 1.5.7.

**Comment by hcri50** [comment]
Thank you, I will try.

**Comment by Nirajpaul2** [comment]
I have solved the issues. because of the issues happened in xcode 9.3, so i have create the project in xcode 9.2 , install the pod. and than after open the project in xcode 9.3 and start work on it.Its work for me.
