### ISSUE TITLE
Cocoapods not creating Xcode 9.3 workspace correctly

### ISSUE THREAD

**Issue by jamiedaniel** [CocoaPods/CocoaPods#7574]
Using CocoaPods 1.5

Using Xcode 9.3

# Report

## What did you do?

Pod init and pod install does not create the appropriate entries for the New Xcode 9.3 Workspace

## What did you expect to happen?

The correct Xcode 9.3 workspace to be created

## What happened instead?

The workspace doesn't include pods targets from he project dropdown.

### Stack

```
   CocoaPods : 1.5.0.beta.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ eaf022d75825d891551c2da1e28f48112d16691b
```

## Project that demonstrates the issue

All projects have the same behavior when created with cocoapods 1.5 and Xcode 9.3 / Swift 4.1

**Comment by dnkoutso** [comment]
Please provide a sample app? I have a few local projects here that work OK with the 9.3 Beta, haven't tried with the final version;.

**Comment by jamiedaniel** [comment]
Downgraded to Cocopods 1.4

**Comment by segiddins** [comment]
We need a sample project to reproduce, thank you!

**Comment by jamiedaniel** [comment]
Any project created with Xcode 9.3 / swift 4.1 and then executing a 'pod init' with Cocoapopds 1.5-pre will produce this error.
I have removed cocoapods and reinstalled 1.4, rebooted and can now build the project. But the PODS are not listed as build targets in the targets dropdown.
<img width="380" alt="screen shot 2018-04-03 at 11 22 32 am" src="https://user-images.githubusercontent.com/2378140/38258775-5729c2c4-3731-11e8-97f3-8862e85d7474.png">

**Comment by dnkoutso** [comment]
@jamiedaniel is there a case where these schemes are always available? I am starting to think this is not a bug?

I tried brand new project with 1.4.0 and Xcode 9.3 beta but the schemes still dont show up.

**Comment by dnkoutso** [comment]
I do not think schemes are shared by default is what I am saying.

**Comment by yichengchen** [comment]
in my case.when i use cocopods 1.5. the project doesn't complier the pod project and directly compiler the main project. cause 3d-partly library "no found" error. after I run 'pod install' in version 1.4. all the error when away.

my project write in swift4. pods contain objective-c and swift library.

**Comment by Asinox** [comment]
Any fix about this?

**Comment by segiddins** [comment]
No, we still haven't received a sample project that reproduces the issue

**Comment by sultan-arshi** [comment]
I have the same project but can not share the sample code here
but can not share the sample code here because of copy right issues, but I can provide you some more information about it 

- the code is working fine in other machines 
- I have tried to clone it again, by taking a copy from other machine but whenever I move this code or unzip the code .xcworkspace gone
- I also tried to get the code in the original formate (not in zip) but same thing happened it automatically hide or deleted 
-I also tried to show and hide the hidden files and folder but only .git directory shows
-I have updated POD but not gain

**Comment by sultan-arshi** [comment]
I solve it by this
I used all of the given solution but did not get success.   

First got to **Product->Scheme->ManageSchem** and then check the shared box(Selected Form)     
Try this     

    pod setup
    pod install
if still have problem.   

    rm -rf ~/.cocoapods 
    pod setup
    pod install
if problem still there then last but not least    

    rm -rf ~/.cocoapods 
    git clone https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master
    pod install
