### ISSUE TITLE
strip_invalid_archs() breaks vendored frameworks

### ISSUE THREAD

**Issue by CodingMarkus** [CocoaPods/CocoaPods#7587]
A framework looks like that:
```
FW.framework
FW.framework/FW -> Versions/Current/FW
FW.framework/Headers -> Versions/Current/Headers
FW.framework/Resources -> Versions/Current/Resources
FW.framework/Versions
FW.framework/Versions/A
FW.framework/Versions/Current -> A
FW.framework/Versions/A/FW
FW.framework/Versions/A/Headers
FW.framework/Versions/A/Resources
```
Note that the 2nd line above is a **symlink** to the real binary which resists in the `A` folder. However, if that binary is a fat binary and you call `strip_invalid_archs()` to thin it, the resulting framework looks like that:
```
FW.framework
FW.framework/FW
FW.framework/Headers -> Versions/Current/Headers
FW.framework/Resources -> Versions/Current/Resources
FW.framework/Versions
FW.framework/Versions/A
FW.framework/Versions/Current -> A
FW.framework/Versions/A/FW
FW.framework/Versions/A/Headers
FW.framework/Versions/A/Resources
```
Note that the 2nd line is **no symlink** anymore. Now the framework contains two binaries. A thin one ```FW.framework/FW``` and the original, unmodified fat one ```FW.framework/Versions/A/FW```.

This results in `codesign` to fail with the following error:

```bundle format is ambiguous (could be app or framework)```

**Comment by dnkoutso** [comment]
I assume this happens pre-1.5.0 too correct?

**Comment by dnkoutso** [comment]
@CodingMarkus can you also upload a quick sample app?

**Comment by CodingMarkus** [comment]
It happens because of this code line
```
lipo -remove "$arch" -output "$binary" "$binary" || exit 1
```
If you need a test universal binary, just download a freeware, like Bonjour Browser:
http://www.tildesoft.com/#RendezvousBrowser

And here is the problem:
```
# lipo -info "Bonjour Browser.app/Contents/MacOS/Bonjour Browser" 
Architectures in the fat file: Bonjour Browser.app/Contents/MacOS/Bonjour Browser are: ppc i386

# ln -s "Bonjour Browser.app/Contents/MacOS/Bonjour Browser" test

# ls -l test
...  test -> Bonjour Browser.app/Contents/MacOS/Bonjour Browser

# lipo -info test
Architectures in the fat file: test are: ppc i386 

# arch=ppc binary=test ; ( lipo -remove "$arch" -output "$binary" "$binary" )

# lipo -info test
Architectures in the fat file: test are: i386

# ls -l test
... test

# lipo -info "Bonjour Browser.app/Contents/MacOS/Bonjour Browser"
Architectures in the fat file: Bonjour Browser.app/Contents/MacOS/Bonjour Browser are: ppc i386 
```
`lipo` does not follow symlinks when writing output files, it's that easy, so the symlink is replaced by an actual file. If you want to preserve existing symlinks, you have to do a `readlink` first and then operate on the real binary, just as `install_framework()` is doing it.

**Comment by dnkoutso** [comment]
@CodingMarkus I've already reprod and have a fix. Just testing it out a bit, sorry should have updated the issue.

**Comment by dnkoutso** [comment]
@CodingMarkus what does `file <path/to/your/.framework/executable` output for you?

**Comment by dnkoutso** [comment]
@CodingMarkus this is not about `lipo` but `codesign` itself, I have a feeling it has to do with the binary type instead of the symlinks.

**Comment by CodingMarkus** [comment]
This is all about `lipo` and the way you are calling it. A framework containing a binary at top level is not allowed on macOS, it must be a symlink and it was a symlink prior to `lipo` destroying it. `file` says exactly what it supposed to say after the lipo-strip.

I lust replaced
```
lipo -remove "$arch" -output "$binary" "$binary" || exit 1
```
with
```
realBinary="${binary}"
if [ -L "${realBinary}" ]; then
	echo "Symlinked..."
	dirname="$(dirname "${realBinary}")"
	realBinary="${dirname}/$(readlink "${realBinary}")"
fi
lipo -remove "${arch}" -output "${realBinary}" "${realBinary}" || exit 1
```
and everything works perfectly.

**Comment by dnkoutso** [comment]
Cool thanks again will try it out and make a PR.

**Comment by dnkoutso** [comment]
@CodingMarkus I really need you to share a project. I just tried again locally with a macOS framework and the process works and yes it has symlinks and the structure you mention.

I am sorry this has been annoying but something else is off here. Please do share one so I can reproduce.

**Comment by CodingMarkus** [comment]
I cannot share anything with you. The project in question is commercial, it's huge, has tons of dependencies which I must not share either and the vendored framework is commercially licensed and thus also not shareable. If you need to reproduce it, just use any project and add any pod with vendored universal framework. But now that I have a fix that works for me, I don't care for this issue to fixed any longer as for me it's fixed. I shared the code that fixes it, so take it or keep shipping a broken Cocoapods, I gave you all the help I could.

**Comment by dnkoutso** [comment]
Cool then it will be fixed when somebody gets on it

**Comment by dnkoutso** [comment]
Best and fastest way is to open a new issue and provide the framework as an example with reproducible steps.

**Comment by rogerluan** [comment]
@Nightsd01 Did you resolve this issue? I'm facing the exact same issue as you, on OneSignal as well 😄 Running cocoapods 1.7.0. Any help?
