### ISSUE TITLE
When using use_modular_headers!, NSUInteger is cast in Swift as Int instead of UInt

### ISSUE THREAD

**Issue by MaximeLM** [CocoaPods/CocoaPods#7589]
🌈
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 

# Report

## What did you do?

In the Podfile of a Swift project, replace `use_frameworks!` with:
```
use_frameworks!(false)
use_modular_headers!
```
The project uses an Objective-C pod. The Objective-C pod use `NSUInteger` in its public interface.

## What did you expect to happen?

NSUInteger should be cast in Swift as `UInt`. This is the previous behavior.

## What happened instead?

NSUInteger is cast is Swift as `Int`. The swift project fails to compile.

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /Users/maximelemoine/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4ddb0bcf3b52ed9ff3e40a475fb06d9dc264bcfe
```

### Installation Source

```
Executable Path: /Users/maximelemoine/.rvm/gems/ruby-2.2.1/bin/pod
```

### Plugins

```
cocoapods-amimono     : 0.0.10
cocoapods-deintegrate : 1.0.2
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :osx, '10.10'

# The project will compile with these settings
#use_frameworks!

# The project will fail to compile with these settings
use_frameworks!(false)
use_modular_headers!

target 'TestNSUInteger' do
  
  pod 'TestLib', :path => '.'

end
```

## Project that demonstrates the issue

https://github.com/MaximeLM/TestNSUInteger.git

This is a simple project that demonstrates the issue. Reverting to `use_frameworks!`in the Podfile makes the project build again.

This issue is preventing apps that use RealmSwift to build with the new setting: https://github.com/realm/realm-cocoa/issues/5663

**Comment by MaximeLM** [comment]
This seems to be caused by https://github.com/CocoaPods/CocoaPods/commit/cd554f433a4d731e65d0d502ef726f23ef694e73

In the test project, the content of `Pods/Headers/Public/TestLib/TestLib.modulemap` is:
```
module TestLib [system] {
  umbrella header "TestLib-umbrella.h"

  export *
  module * { export * }
}
```

If I remove the `[system]` tag, the error is gone.

This thread indicates that NSUInteger is bridged as Int for system frameworks like Foundation/AppKit/UIKit, and as UInt for user frameworks.
https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20160111/000848.html

**Comment by segiddins** [comment]
Well that’s unfortunate, and undocumented in the clang modules page :(. All it says the system modifier does is suppress warnings from headers

**Comment by dnkoutso** [comment]
We might have to remove this.

**Comment by gereons** [comment]
This issue also prevents apps using [SwiftyDropbox](https://github.com/dropbox/SwiftyDropbox) from switching to `use_frameworks!(false)`.

**Comment by dnkoutso** [comment]
PR https://github.com/CocoaPods/CocoaPods/pull/7638

**Comment by MaximeLM** [comment]
I still can't build RealmSwift with CocoaPods on the master branch. The Realm subpod defines a module map with `framework module Realm`, which is replaced by `module Realm [system]` by CocoaPods.
https://github.com/realm/realm-cocoa/blob/master/Realm/Realm.modulemap
https://github.com/CocoaPods/CocoaPods/blob/0a93634a872c5c14592f764384694023f69381b7/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L628

**Comment by dnkoutso** [comment]
1.5.1 hasn't shipped yet. did you try with latest master branch?

**Comment by dnkoutso** [comment]
Oops @MaximeLM you are right this should also be removed.

**Comment by dnkoutso** [comment]
Let me open a PR

**Comment by MaximeLM** [comment]
@dnkoutso yes I used the latest master

**Comment by dnkoutso** [comment]
@MaximeLM PR up

**Comment by MaximeLM** [comment]
@dnkoutso the app compiles with your fix, thank you!

Two warnings have appeared in our app:
```
Umbrella header for module 'Realm' does not include header 'RLMMigration_Private.h'
Umbrella header for module 'Realm' does not include header 'RLMSyncManager_Private.h'
```

I guess that is an issue with Realm?

**Comment by segiddins** [comment]
No, it’s a CocoaPods issue that we don’t know how to fix for static libraries
