### ISSUE TITLE
Xcode 9.3 - cocoapods Target Pods - cannot link framework

### ISSUE THREAD

**Issue by AdamMak** [CocoaPods/CocoaPods#7593]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Update Xcode to latest version - 9.3 and updated cocoapods to 1.5

## What did you expect to happen?

Project should run normally

## What happened instead?

I am getting warning saying Target Pods-App product Pods_App cannot link framework Foundation.framework. I can run the app and it seems to work. When I look in my pods project, all the frameworks are faded red.  [
![screen shot 2018-04-06 at 13 40 11](https://user-images.githubusercontent.com/17201601/38421739-12e01ca0-39a0-11e8-9d55-b78ee65611aa.png)
](url)

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 079aadeadef0629bd01dadcfa2f984a7661af9ae
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'App' do
	pod 'Google/Analytics'
	pod 'SwiftyJSON'
	pod 'Alamofire'
	pod 'lottie-ios'
	pod 'ZDCChat'
	pod 'AFNetworking'
	pod 'Starscream'
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'Branch'
	pod 'RxSwift'
        pod 'RxCocoa'
	pod 'KeychainSwift'
	pod 'Charts'
   	use_frameworks!
	pod 'HockeySDK', '~> 5.1.2'
	inhibit_all_warnings!


	target ‘AppTests’ do
	inherit! :search_paths
	pod 'Alamofire'
	pod 'Nimble'
	pod 'Quick'
	pod 'Firebase'

	end
 end

## Project that demonstrates the issue

**Comment by dnkoutso** [comment]
Please upload a sample app, furthermore those questions are best asked in StackOverflow under `cocoapods` tag until it has been verified this is an actual CocoaPods library issue.

Closing for now.

**Comment by adamkmccarthy** [comment]
This issue is being worked on here: https://github.com/CocoaPods/CocoaPods/issues/7251

**Comment by tzars21** [comment]
I am getting error when I am using swiftJSON on Xcode 9.3 for iOS 11
when I solve this problem by using swiftyJSON then it produces running
time error like Swift version problem
