### ISSUE TITLE
Access private headers with use_modular_headers

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#7596]
Private headers are importable from frameworks by explicitly naming them in imports and they're available in plain static libraries via ${PODS_ROOT}/Headers/Private. There should be a way to access them if modular_headers is on without making a custom module map.

For code that accesses private headers to work both as a static library and with modular headers, I need either a comparable path or an ifdef to flip between the explicit module import and the path in ${PODS_ROOT}/Headers/Private.

**Comment by dnkoutso** [comment]
@paulb777 do you want this for 1.5.1?

**Comment by segiddins** [comment]
We _could_ just add `${PODS_ROOT}/Headers/Private` back to the header search paths ?

**Comment by paulb777** [comment]
@dnkoutso Yes. This along with #7591, #7592, and #7597 is needed for Swift static libraries and Firebase.
