### ISSUE TITLE
[1.5.0, static libs] Pods using modular_headers with custom modulemap and private headers not configured correctly in Pods project

### ISSUE THREAD

**Issue by p4checo** [CocoaPods/CocoaPods#7598]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Removed `use_frameworks!`
- Added `:modular_headers => true` to Pod with Obj-C dependency, custom `.modulemap` and private header ([(ReactiveCocoa)](https://github.com/ReactiveCocoa/ReactiveCocoa))
- Ran `pod install`
- Built project

## What did you expect to happen?

- Project set up correctly (main + Pods)
- Project built successfully 

## What happened instead?

- Project failed when building because ReactiveCocoa target wasn't configured correctly in Pods.xcodeproj
- I managed to get it building successfully, after tracking down the issues:

### Issue 1:  Pod's custom script "Copy generated compatibility header" is not respecting custom `modulemap`'s umbrella header name

When building ReactiveCocoa, the following message was printed:
```
ditto: can't get real path for source '/path/to/project/Pods/Headers/Private/ReactiveCocoa/ReactiveCocoa-umbrella.h'
```
This is incorrect, since the ReactiveCocoa [modulemap](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/30ee38bcc0ddf6a9d3e63d86af0529be0809b391/ReactiveCocoa/module.modulemap#L2) specifies that the umbrella header is `ReactiveCocoa.h`

### Issue 2: Pod's private headers (podspec and/or modulemap) are not marked as Private on the Header's build phase:

When building the main target, the following message was printed: 
```
error: header 'ObjCRuntimeAliases.h' not found
        private header "ObjCRuntimeAliases.h"
                       ^
<unknown>:0: error: could not build Objective-C module 'ReactiveCocoa'
```

This header is specified on both ReactiveCocoa's [podspec](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/30ee38bcc0ddf6a9d3e63d86af0529be0809b391/ReactiveCocoa.podspec#L19) and [modulemap](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/30ee38bcc0ddf6a9d3e63d86af0529be0809b391/ReactiveCocoa/module.modulemap#L3), but it's configured as `Project` in the Pod's Headers build phase.

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /Users/user/.rbenv/versions/2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f2029de3594ebdfa50afdd5ea5552dfe95c6a751
```

### Installation Source

```
Executable Path: /Users/user/.rbenv/versions/2.2.4/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.4
```

### Podfile

```ruby
platform :ios, '9.0'
inhibit_all_warnings!

target 'App' do

  pod 'ReactiveCocoa', '~> 7.0', :modular_headers => true

end
```

## Project that demonstrates the issue

https://github.com/p4checo/CPTestCustomModuleMapAndPrivateHeader

`master` branch  shows the issues
`manual-fix` branch contains the fixes described above

**Comment by dnkoutso** [comment]
Thanks for filing this, would love a PR.

**Comment by p4checo** [comment]
Unfortunately, my Ruby skills are quite limited, and I'm not familiar with the CocoaPods codebase at all 😅
Any tips on where to start looking?

**Comment by segiddins** [comment]
This won’t be simple to fix, I probably wouldn’t recommend it as your first foray into ruby

**Comment by dnkoutso** [comment]
Is this a dup of https://github.com/CocoaPods/CocoaPods/issues/7585?

**Comment by segiddins** [comment]
Looks like it

**Comment by p4checo** [comment]
Damn, missed that one 😞
Sorry guys. Should I close this one?

**Comment by dnkoutso** [comment]
@p4checo no problem! I will close this one but it will be referred on the other. Thank you again for the detailed report!

**Comment by dreampiggy** [comment]
@dnkoutso What's going on for this issue ? I'm stilling face this issue. Using CocoaPods 1.7.0 official release.

SDWebImage have a custom modulemap, and we have private headers (in `private_header_files`).

When using `use_frameworks!`, the Private header are configurated correctly as Private in Xcode.

However, chaning to `use_modular_headers!`, the Private headers are configurated as Project in Xcode. No anything other changes between these two tests.

See the screenshot:

+ `Podfile`
![image](https://user-images.githubusercontent.com/6919743/58543811-bf3e0800-8232-11e9-8d8d-dd2ef3160356.png)

+ `use_frameworks!`
![image](https://user-images.githubusercontent.com/6919743/58543825-c36a2580-8232-11e9-87aa-4a46152d7c00.png)

+ `use_modular_headers!`
![image](https://user-images.githubusercontent.com/6919743/58543872-d846b900-8232-11e9-9ad6-bcf723155b77.png)
