### ISSUE TITLE
Add `pod update [podname]` command

### ISSUE THREAD

**Issue by nickynick** [CocoaPods/CocoaPods#760]
Existing `pod update` only allows you to update all pods at once. But sometimes you don't need that, you just want to get the latest version of the specific pod. Right now this involves nuking its directory in Pods, stripping it from Podfile.lock and running `pod install`. Quite annoying :)

Thus, it would be nice to be able to supply a pod name (or, possibly, a list of names) to `pod update` to limit its updating scope.

**Comment by johnrogers** [comment]
This is an old thread, however still seems to be visited frequently as a means to find an answer to this. 

We ran into an issue where our CI running `pod install` via Fastlane would not update to the latest version of the pod (under development, pointing to the `develop` branch of the pod).

We found that this issue began to arise when we removed `Podfile.lock` from source control. Upon re-adding it, `pod install` recognises that the hashes have changed and always correctly updates the pod. If you're having issues with the Fastlane `cocoapods` step, make sure `Podfile.lock` is checked in and up-to-date in the commit you're building from to point to the commit of the Pod you'd like to use.

Hope this is helpful to someone! :)

**Comment by getaaron** [comment]
@johnrogers I found it helpful to add a `Podfile.lock` check in my Fastfile:

```ruby
  private_lane :check_for_podfile_lock_changes do
    next unless Actions.sh("git status --porcelain").include? "Podfile.lock"
    UI.error "Looks like `pod install` modified Podfile.lock."
    UI.error "This can happen if you committed a change to Podfile but didn't also commit all of the changes to Podfile.lock."
    UI.error "Try running:"
    UI.command "pod install --repo-update"
    UI.error "Then commit the Podfile.lock changes locally, and retry."
    UI.user_error! "Aborting since the Podfile.lock change is unexpected."
  end
```
