### ISSUE TITLE
[1.5, static libs] Importing ObjC pods into Swift Notification Service Extension fails

### ISSUE THREAD

**Issue by robinkunde** [CocoaPods/CocoaPods#7609]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I tried to add an ObjC pod to an app's Swift Notification Service Extension.

## What did you expect to happen?

The project builds and the pod is available for import in the extension.

## What happened instead?

The project fails to build with a "No such module" error for the pod.

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.17.0
Ruby lib dir : /Users/rkunde/.rbenv/versions/2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6f804f87d630f929fc3b28f88b021632db5fd952
```

### Installation Source

```
Executable Path: /Users/rkunde/.rbenv/versions/2.5.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!
  pod 'UrbanAirship-iOS-SDK'

  # Pods for example

end

target 'NotificationServiceExtension' do
  # platform :ios, '10.0'
  pod 'UrbanAirship-iOS-AppExtensions'
end
```

## Project that demonstrates the issue

https://github.com/robinkunde/cocoapodsStaticLibraryIssue

**Comment by segiddins** [comment]
I can't get the example project to build because it requires code signing:

```
Check dependencies
Code Signing Error: No profiles for 'com.recoursive.example.NotificationServiceExtension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.recoursive.example.NotificationServiceExtension'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild.
Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 11.3'
```

**Comment by robinkunde** [comment]
Sorry, I'm not sure what the code signing settings in Xcode need to be to be completely portable. Can you try changing team and bundle ids for both the app target and extension target?
Are you building in Xcode or command line?

**Comment by robinkunde** [comment]
Depending on how you build, just turning off automatic code signing might also do the trick.

**Comment by robinkunde** [comment]
@segiddins Is there anything else I can do to help debug this?

**Comment by segiddins** [comment]
Not sure, last time I looked I ran into code signing issues and that was all the time I was able to spend on it
