### ISSUE TITLE
Modulemap path works for local pod development but not when the pod is installed from remote

### ISSUE THREAD

**Issue by bryanboyko** [CocoaPods/CocoaPods#7619]
# Report

## What did you do?

Create my_framework with a VungleSDK dependency as a pod (VungleSDK is included by Cocoapods as a .framework as opposed to being a collection of source files which Cocoapods then packaged as a framework). 

Expose Objective-C VungleSDK module to my_framework Swift files with the following code from module.modulemap 

```
module VungleSDK [system] {
    header "../../../../Pods/VungleSDK-iOS/VungleSDK.framework/Headers/VungleSDK.h"
    export *
}
```

The potentially relevant portion of my podspec:

```
  s.xcconfig         = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }
  s.libraries        = 'xml2'
  s.swift_version    = "4.0"

  s.requires_arc     = true
  s.platform         = :ios, '8.0'
  s.static_framework = true

 s.subspec 'Vungle' do |d|
    d.dependency 'VungleSDK-iOS', '5.4.0'
    d.source_files = ['MYSDK/ThirdParty/*.swift', 'MYSDK/ThirdParty/Vungle/**/*']
    d.xcconfig = { 'SWIFT_INCLUDE_PATHS' => '$(PODS_TARGET_SRCROOT)/MYSDK/ThirdParty/Vungle/ModuleMap' }
    d.preserve_paths = 'MYSDK/ThirdParty/Vungle/ModuleMap/module.modulemap'
  end
```

The above setup works for local development, but not when my_framework is installed by Cocoapods from a remote source. 

I used the answers from the below Cocoapods issue to get local development working https://github.com/CocoaPods/CocoaPods/issues/5271

My header path in the module map looks gross. I'm guessing it's causing this issue. I couldn't find how to make the path work after digging around the web. 

Likely there is an answer in the clang docs? I'm finding them difficult to decipher.. http://clang.llvm.org/docs/Modules.html#module-declaration

## What did you expect to happen?

The module map path that works for local pod development of my_framework should also work when my_framework is installed from a remote source

## What happened instead?

XCode build error
```
Could not build Objective-C module 'VungleSDK'
```

### Stack

```
   CocoaPods : 1.5.0.beta.1
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 01a6310775e35c4d06ede009c44635600971f4ed
               MYSDK-Specs - git@github.com:MYSDK/Specs.git @ fc84b2d94a911a9b9484114c9add939ca6694e76
               mysdk - https://github.com/MYSDK/Specs.git @ 58c1c0279879e0375c07ab825bf014b27d1e5f58
               Specs - git@github.com:MYSDK/Specs.git @ 58c1c0279879e0375c07ab825bf014b27d1e5f58
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/MYSDK/Specs.git'

def common_deps

  use_frameworks!

  pod 'SwiftLint'
  pod "VungleSDK-iOS", "5.4.0"
 
end

target 'MYSDK' do

  common_deps

  target 'MYSDKTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end


end
```

## Project that demonstrates the issue

Let me know if a sample project will be helpful and I will make one.

**Comment by dnkoutso** [comment]
Not sure for the core problem but one thing to note:
```
    d.xcconfig = { 'SWIFT_INCLUDE_PATHS' => '$(PODS_TARGET_SRCROOT)/MYSDK/ThirdParty/Vungle/ModuleMap' }
```

Are you intentionally changing this? `xcconfig` actually changes the user xcconfig and not the pod one. Generally not advised as it changes the users project. Unless you really intended to do this.

**Comment by bryanboyko** [comment]
I added that line based on the solution suggested in #5271

I just tried removing it from the podspec. When I re-pod installed, I got the error `No such module 'VungleSDK'`

I'm not very familiar with module maps, but it seems like this is an issue with the header path in my module map, which works to incorporate my_framework is a development pod, but not when it's installed as a pod from a remote source.

**Comment by dnkoutso** [comment]
@bryanboyko I think it would be best to provide a sample app for us to repro and diagnose.

**Comment by bryanboyko** [comment]
@dnkoutso ok coming up

**Comment by dnkoutso** [comment]
@bryanboyko thanks! *miiight* be related to https://github.com/CocoaPods/CocoaPods/pull/7616? You can apply the fix manually or use `bundler` and try it out?

**Comment by bryanboyko** [comment]
@dnkoutso thanks will take a look

**Comment by bryanboyko** [comment]
@dnkoutso I'm having a bit of trouble figuring out how to apply the fix manually. 

I followed the PR code to the `xcconfig_helper.rb` class. Since I've got `static_framework = true` in my podspec, im assuming `self.add_static_dependency_build_settings` function will be hit and then `add_framework_build_settings` will be hit. 

`add_framework_build_settings` makes the following calls

```
build_settings = {
            'FRAMEWORK_SEARCH_PATHS' => quote([dirname]),
          }
build_settings['OTHER_LDFLAGS'] = "-framework \"#{name}\"" if include_ld_flags
```

That means I just need to add VungleSDK to the FRAMEWORK_SEARCH_PATHS and OTHER_LDFLAGS in the sample app's build settings?

**Comment by dnkoutso** [comment]
@bryanboyko for 1.6.0 all of the build settings are being re-written. Sorry haven't had time to look over this issue.

**Comment by dnkoutso** [comment]
@bryanboyko from a very quick look this might be fixed by the build settings revamp https://github.com/CocoaPods/CocoaPods/pull/7631

**Comment by bryanboyko** [comment]
@dnkoutso no worries. 

Looking forward to the next Cocoapods release.

**Comment by klein-thibault** [comment]
@bryanboyko I'm experiencing the same issue that you mentioned here, did you end up solving your issue?

**Comment by mitchross** [comment]
@bryanboyko I would like to know also!

**Comment by amadeu01** [comment]
@bryanboyko Im facing the same issue, how did you fix ?

**Comment by Jageen** [comment]
@brentnycum I am having same issue, did you solved it?

**Comment by Jageen** [comment]
Hello @dnkoutso It issue is closed and it seems that @brentnycum did found solution but can you put some more light over solution ?
Can you let me know what might @brentnycum did to solve his problem ?

**Comment by SeanTrinhHai** [comment]
Incase anyone is still looking the answer just like me before, modulemap file directory is different when we using remote pod instead of local pod. Therefore, you might have to modify header path in modulemap file a bit to math with new directory in remote version, in my case:
`module InsiderMobile [system] {
	// Framework complier
//	header "../../../../Pods/InsiderMobile/InsiderMobile.framework/Headers/Insider.h"
	
	//App complier
	header "../../../../../../Pods/InsiderMobile/InsiderMobile.framework/Headers/Insider.h"

    export *
}
`
I change the header directory before deploy pod and it work fine for my application
