### ISSUE TITLE
Warning| Unable to read the license file

### ISSUE THREAD

**Issue by PoojaChirp** [CocoaPods/CocoaPods#7620]
Hi All,

I've followed the rules suggested in the article-https://guides.cocoapods.org/syntax/podspec.html#license, but I've no luck. A warning is seen when I pod lint the spec -

Unable to read the license file /<path>/LICENSE.md for the spec spec name(11.12.0.0)

Installed software versions on my device:
.gem/ruby/2.5.0/
gems/cocoapods-1.4.0/
Xcode-9.2

Thanks,
Pooja

**Comment by amorde** [comment]
Most likely you have specified a license file but the path does not exist.

Can you provide the contents of the podspec?

**Comment by dnkoutso** [comment]
This is also a warning and most likely what @amorde said.

Please use StackOverflow under `cocoapods` tag to ask these questions. There is little information fro us to debug this or even come to a conclusion that this is a bug in the library itself.

Please provide sample app and use the template when filing an issue clearly showing the problem.
