### ISSUE TITLE
Issues with Podfile Syntax Reference

### ISSUE THREAD

**Issue by PoojaChirp** [CocoaPods/CocoaPods#7621]
Hi All,

I have a created the podspec with an SDK dependency. My SDK dependency is specified as given below-

s.dependency  '[SDK NAME]', '~> [VERSION]'

When these pods are published and when I do a pod init of the newly created pod, the dependency SDK version fetched isn't consistent. At times I fetch the latest SDK while the rest of the times I fetch the version as specified in the dependency attribute of the code, though there is an incremental version of the SDK available. Hence can you please recommend an approach that lets me download only the specified version of the SDK instead of latest. 

Thanks!

**Comment by amorde** [comment]
Removing the `~>` operator will limit the version to an exact match

**Comment by dnkoutso** [comment]
Please use StackOverflow under the `cocoapods` tag to ask these questions. There is not a lot for us to diagnose or even consider this is an issue with the library itself.
