### ISSUE TITLE
xcpretty make pob lib lint too slow

### ISSUE THREAD

**Issue by meritozh** [CocoaPods/CocoaPods#7626]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint --verbose --allow-warnings --fail-fast | xcpretty`

## What did you expect to happen?

fast, maybe 6 min for my spec.

## What happened instead?

too slow, take more than 30 min!

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.3 (9E145)
         Git : git version 2.17.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : elenet-ping-im-pingopenspecs - https://git.elenet.me/ping-im/PingOpenSpecs.git @ d3a0a731ae30b4c6e186246ca0dc8954fbbe9748
               master - https://github.com/CocoaPods/Specs.git @ 28c5bd8f279ca3c954829b4e860cbc59a8550177
               me:arch-ios_specs - git@git.elenet.me:arch.mobile/iOS_specs.git @ f2af63114ed169e727ad4a7e5a909e4c465f8061
               mobile-ios-specs - git@git.elenet.me:eleme.mobile.ios/ios-specs.git @ 075a2f97a972007118b2b8d0478aa21c662e5180
               mobile-specs - git@git.elenet.me:eleme.mobile.ios/Specs.git @ c1f6cce459eff586fc0682a1eff85f9d80ad47b7
               msec_Specs - git@git.elenet.me:risk.msec/msec_Specs.git @ 40cd9af6f26150ed6515c94cebbdf4591c58e794
               pingSpec - git@git.elenet.me:ping-im/PingOpenSpecs.git @ d3a0a731ae30b4c6e186246ca0dc8954fbbe9748
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.2
cocoapods-dependencies : 1.1.0
cocoapods-packager     : 1.5.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.3.0
cocoapods-try          : 1.1.0
```

## Addition

I have test,

Run `pod lib lint --verbose --allow-warnings --fail-fast | xcpretty`, it will clone all dependencies first, which is too slow. Run `pod lib lint --verbose --allow-warnings --fail-fast | cat` or `pod lib lint --verbose --allow-warnings --fail-fast` will fast, it will fetch source from cache, no git clone phase. So the problem must caused by xcpretty.

The behavior is strange, why xcpretty which only eat stdout will affect cocoapods's behavior?

**Comment by segiddins** [comment]
Piping to xcpretty won’t effect CocoaPods behavior

**Comment by meritozh** [comment]
Can you reproduce this issue?

**Comment by segiddins** [comment]
```
pod lib lint --verbose --allow-warnings --fail-fast  6.02s user 3.19s system 128% cpu 7.185 total
```

```
pod lib lint --verbose --allow-warnings --fail-fast  5.78s user 2.95s system 129% cpu 6.767 total
xcpretty  0.40s user 0.08s system 7% cpu 6.771 total
```

No difference between the two on a random pod I had lying around
