### ISSUE TITLE
How to modify local podspec in pre_install hook?

### ISSUE THREAD

**Issue by Langxxx** [CocoaPods/CocoaPods#7627]
# Report

## What did you do?
I want to modify some local podspec in `pre_install`  hook.And now, i had been found a way to modify some third-party pods.Like below:
```
//in podfile
pod 'Tactile', :git => 'https://github.com/delba/Tactile', :branch => 'master'
//in pre_install hook
installer.sandbox.specifications_root.children.each do |podspec|
        if podspec.extname() == '.json'
            code = File.read(podspec)
            json = JSON.parse(code)
            if json['name'] == 'Tactile'
                json['source_files'] = ['Source/**/*.swift']
            end
            File.write(podspec, JSON.generate(json))
        end
end
```
In this way, everything is ok,the cocoapods can use the new json file to config my project.But it do not work when i do the same way to the local pod.

```
pod 'MessagePack', :path => '../../../MessagePack'
```
the json file(`**/Pods/Local Podspecs/MessagePack.podspec.json`) had been changed ,but cocoapods did not use  this.

## What did you expect to happen?
Could you please help me to figure it out

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
