### ISSUE TITLE
Can't open project from workspace

### ISSUE THREAD

**Issue by OgreSwamp** [CocoaPods/CocoaPods#763]
Hi,

I installed pods for my fresh XCode project (with some cocos2D). Actually I've installed only 1 Pod - TestFlightSDK at the moment.
Pod was downloaded, workspace created etc. 
When I open workspace it opens Pods project but cannot open original one. It shows error:

> Workspace Integrity
> Couldn't load CocosAlpha.xcodeproj because it is already opened from another project or workspace

Project isn't opened.
I already tried to restart XCode, restart my Mac, delete Pods, workspace and install them again. But nothing helps.
Any ideas why it can happens?

**Comment by qwang216** [comment]
The solution works for me. 1) close project/workspace 2) `pod install` Thanks!

**Comment by manishios** [comment]
This works only when you are installing the pod for the first time. 
I am facing an issue where in I am trying to rebase feature branch (FB) on to develop. I am in the workspace. Rebase is done and after this I am unable to open the workspace. The file "pods.xcodeproj is unable to open". Any help is appreciated.

**Comment by cenkay123** [comment]
> I had the same issue, when I made sure xcode was closed before running 'pod install', that fixed my problem. Then again that could just be coincidence:)

it's really amazing that this is the solution 😬
