### ISSUE TITLE
[1.5] Dependency analysis for Pod that contains .xib files fails

### ISSUE THREAD

**Issue by gereons** [CocoaPods/CocoaPods#7633]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).  🌈

# Report

## What did you do?

ran `pod install` on the linked sample project, tried to compile with Xcode 9.3

## What did you expect to happen?

successful compilation

## What happened instead?

Compilation fails with `Dependency Analysis Error`, listing 9 issues relating to .xib files included in the `SDCAlertView` pod:

`Unable to run command 'StripNIB $nibname' - this target might include its own product.`

This pod works as intended when using `use_frameworks!`
Pod source is at https://github.com/sberrevoets/SDCAlertView
 
### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 685f50e0a7f0ea95847ab8632f1f28acfc7d3b3b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!
platform :ios, '11.0'

target 'AlertExample' do
    pod 'SDCAlertView'
end
```

## Project that demonstrates the issue

https://github.com/gereons/AlertExample

**Comment by dnkoutso** [comment]
Your title says static libs but your description uses static frameworks, which one is it? I haven't looked at the sample yet.

**Comment by gereons** [comment]
Sorry for the confusion. I don't really care about libaries vs frameworks, this issue is about what looks to me as a regression - compilation works when using `use_frameworks!` and fails without it.

**Comment by dnkoutso** [comment]
@gereons I know its been eons this this issue was updated but I tried 1.8.4 and this successfully compiles with static libraries. Not sure if the pod 'SDCAlertView' has changed until then or Xcode has fixed the issue.

**Comment by dnkoutso** [comment]
![Screen_Shot_2019-12-04_at_12_19_15_PM](https://user-images.githubusercontent.com/310370/70165111-57102900-1690-11ea-8b29-701eb7163984.png)

**Comment by gereons** [comment]
Indeed, this works now. Thanks for the follow-up!
