### ISSUE TITLE
error: RPC failed; curl 56 LibreSSL SSL_read: error:140943FC:SSL routines:SSL3_READ_BYTES:sslv3 alert bad record mac, errno 0

### ISSUE THREAD

**Issue by cyaris** [CocoaPods/CocoaPods#7635]
Made updates to a github local repository with large files. Tried to push to the remote repository but it exceeded the limit so I installed Git Large File Storage. Since then, I've encountered this error message when trying to push to the remote repository:

error: RPC failed; curl 56 LibreSSL SSL_read: error:140943FC:SSL routines:SSL3_READ_BYTES:sslv3 alert bad record mac, errno 0

Things I've tried:
git config http.sslVersion tlsv1.2
git config http.postBuffer 524288000
git config --global http.postBuffer 2M

Just trying to push the most current version of my local repository to GitHub. Any help would be appreciated. Thanks so much.

**Comment by dnkoutso** [comment]
This does not seem a CocoaPods library issue, please ask this question in StackOverflow using `cocoapods` tag.
