### ISSUE TITLE
1.5.0 ipa EXPORT FAILED

### ISSUE THREAD

**Issue by wangjindong** [CocoaPods/CocoaPods#7641]
The same project can correct export for cocoapods 1.4.0, but not for cocoapods 1.5.0。

erro info : 

```
xcodebuild[3545:4698010] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/zg/ymr0ctxx0bj146t1hs04zrbc0000gn/T/Integration_2018-04-16_18-11-57.935.xcdistributionlogs'.
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found enterprise

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found enterprise" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found enterprise}

** EXPORT FAILED **
```

I need help !!!

**Comment by wangjindong** [comment]
command line
`
xcodebuild -exportArchive -archivePath ${archivePath} -exportPath ${exportPath} -exportOptionsPlist ${exportOptionsPlist}`

**Comment by dnkoutso** [comment]
Please fill in the template and provide a sample app. We cannot possibly diagnose this like this and might be a user error.

It is also better to ask these questions in StackOverflow under `cocoapods` tag. This may be a dup of https://github.com/CocoaPods/CocoaPods/issues/7590

Will re-open if you fill in the template and provide a sample app.

**Comment by wangjindong** [comment]
I found it.

The following script has a problem。

`  printf "%s\0" "${XCASSET_FILES[@]}" | xargs -0 xcrun actool --output-format human-readable-text --notices --warnings --platform "${PLATFORM_NAME}" --minimum-deployment-target "${!DEPLOYMENT_TARGET_SETTING_NAME}" ${TARGET_DEVICE_ARGS} --compress-pngs --compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${TARGET_BUILD_DIR}/assetcatalog_generated_info.plist"
`

${TARGET_BUILD_DIR} to ${BUILD_DIR} will be correct。

Why?

**Comment by dnkoutso** [comment]
This is most likely fixed with https://github.com/CocoaPods/CocoaPods/pull/7637 which has been merged.

**Comment by wangjindong** [comment]
oh，tks。
