### ISSUE TITLE
use_framework! and submit for review failed in itunesconnect!

### ISSUE THREAD

**Issue by mdsb100** [CocoaPods/CocoaPods#7645]
* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

use_framwork!

Upload testflight well and download it to test well.

## What did you expect to happen?

submit for review well in itunesconnect

## What happened instead?
If the frameworks are more than 75, it got
![wechatimg155](https://user-images.githubusercontent.com/2350193/38822370-d2ce1124-41d5-11e8-8327-a11c6c6aff9f.jpeg)
![wechatimg156](https://user-images.githubusercontent.com/2350193/38822374-d66a6832-41d5-11e8-9a2d-b71886b7e810.jpeg)

The response of  `https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/1128660260/versions/826445971/submit/summary` will get code -1 when browser force close request because it has no response for a long time.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : aliyun - https://github.com/aliyun/aliyun-specs.git @ 0e6724ac88fc797d1c6f7d1283ef7d60552e233c
               baidao-ios-ytx-pod-specs - http://gitlab.yintech.net/ytx-ios/ytx-pod-specs.git @ d06b451bcb16f3b9261c474b4ad82cbf291391b9
               master - https://github.com/CocoaPods/Specs.git @ 602f9b42a99d7d3f7704900b55fbe7d2e2edbc60
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.2
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.3.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

We are looking for feedback on Apple's customer service. However, no useful reply has been received so far.
Anyone have any idea， please tell me.

**Comment by mdsb100** [comment]
I can use cocoapods@1.5 to avoid use `use_framework!` by using swift. But I really want to what happen in apple! why is 75 frameworks!

**Comment by dnkoutso** [comment]
@mdsb100 please do not use this issue list for support. Please ask this question on stackoverflow under 'cocoapods' tag.

From the report this does not appear to be a cocoapods library issue. I might be wrong though so if you can reproduce and include a sample app then i will re open.
