### ISSUE TITLE
Website search is broken, again.

### ISSUE THREAD

**Issue by pmiotto** [CocoaPods/CocoaPods#7647]
## What did you do?
Go to cocoapods.org and search for something

## What did you expect to happen?

Search results to appear

## What happened instead?

Nothing

**Comment by segiddins** [comment]
looks like aws-search.cocoapods.org just isn't responding

**Comment by Leon16** [comment]
have to use another one <http://cocoapods.wantedly.com>

**Comment by sushant40** [comment]
@segiddins - happy to help out to make search more robust. Though I don't know where to start... can you point me in the right direction please?

**Comment by sushant40** [comment]
Has anyone looked at moving the search and index out into something like https://www.algolia.com/

Its free to use for open source so licensing shouldn't be a problem for CocoaPods. Very fast and very reliable.

**Comment by askari01** [comment]
it is still down

**Comment by mkubista** [comment]
Is here anybody, who knows, how to fix this? I would be very happy to help solve this, but as mobile developer  have no clue right now what is happening. As somebody mentioned the search engine is down. Am I right that it is hosted on https://www.cloudflare.com/? Does somebody know if the search engine is overloaded, turned off or there is some bug?

**Comment by orta** [comment]
I've left notes about porting it to algolia, https://github.com/CocoaPods/cocoapods.org/issues/356 - which is open for someone to pick up

**Comment by misteu** [comment]
In the meantime, I found this terminal command quite helpful:

> pod search alamofire --simple --ios

make sure to use --simple, otherwise it is very slow because of it indexing the master repo.

**Comment by ygornascimento** [comment]
Same problem here in Brazil.  I'm not an expert but, I'd like to help you guys to solve the problem.

**Comment by c3stream** [comment]
https://github.com/CocoaPods/cocoapods.org/issues/356

When do you expect the problem to be resolved?

**Comment by ppamorim** [comment]
Still broken, trying to access it on Ireland.

**Comment by av089** [comment]
@ppamorim I think it will never come again!
please move to Carthage, which is far best than this...

**Comment by StanDimitroff** [comment]
Not working from Bulgaria too :(

**Comment by gaus55** [comment]
Hi Guys i tried this and worked. https://stackoverflow.com/questions/38993527/cocoapods-failed-to-connect-to-github-to-update-the-cocoapods-specs-specs-repo

**Comment by segiddins** [comment]
It’s known to be down. Please follow status.cocoapods.org for updates.
The search repo is at https://github.com/CocoaPods/search.cocoapods.org for those interested in contributing.

I’m locking this issue for now, since we know it’s down and further comments won’t give us more actionable information

**Comment by dnkoutso** [comment]
Search is back online.
