### ISSUE TITLE
Module not found in test target

### ISSUE THREAD

**Issue by zishanj** [CocoaPods/CocoaPods#7649]
I am receiving `No such module xxx` when I try to import `RxTest` or `RxBlocking` module in my Test target. Here is my podfile:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My-Sample Live' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My-Sample Live
  pod 'MaterialControls', :git => 'https://github.com/fpt-software/Material-Controls-For-iOS.git'
  pod 'HexColors'  
  pod 'Siren'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SwiftyJSON'
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxAlamofire'
  
  target 'My-Sample LiveTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

end
```

All other modules from non-test targets are available in test targets. Whats the issue?

**Comment by dnkoutso** [comment]
We do not know. Need a sample.

**Comment by zishanj** [comment]
@dnkoutso what type of sample?

**Comment by dnkoutso** [comment]
A sample xcodeproj showing the issue.

**Comment by zishanj** [comment]
I am using latest XCode Version 9.3 (9E145). You can put above Podfile in your project dir and run `pod install`.

**Comment by rawlinxx** [comment]
same problem. 
removing test target make example project run success, but pod lint will error again, i can't push lib to specs repo.
