### ISSUE TITLE
cocoapods website search not working

### ISSUE THREAD

**Issue by dficken** [CocoaPods/CocoaPods#7650]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

opened browser (safari and chrome)
went to http:\\cocoapods.org
entered known pod name in search field (e.g., charts)

## What did you expect to happen?

search results to be returned

## What happened instead?

nothing

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /Users/dficken/.rbenv/versions/2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f8039eef6ff32aa9a253d845247c3e4eed6f7969
```

### Installation Source

```
Executable Path: /Users/dficken/.rbenv/versions/2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
  platform :ios, '11.0'

target 'CellarView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CellarView
	pod 'SwiftyUserDefaults', '~> 3.0.1'
	pod 'Charts', '~> 3.1.0'
	pod 'FBSDKCoreKit', '~>  4.32.0'
	pod 'ReachabilitySwift', '~> 4.1.0'
	pod 'PMAlertController', '~> 3.3.0'
	pod 'SJStringScore', '~> 1.0.1'

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
dup of https://github.com/CocoaPods/CocoaPods/issues/7647
