### ISSUE TITLE
pod spec lint fails to parse source url

### ISSUE THREAD

**Issue by dylanshine** [CocoaPods/CocoaPods#7652]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
pod trunk push OKTableViewLiaison.podspec

## What did you expect to happen?
Cocoapod would be successfully deployed.

## What happened instead?
pod spec lint failed to parse git source url for Podspec

```
 -> OKTableViewLiaison (1.0.0)
    - WARN  | url: There was a problem validating the URL https://github.com/kcupid/OKTableViewLiaison.
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/kcupid/OKTableViewLiaison.git /var/folders/j6/pdkws_z15sx4yryrmsyv5f7c0000gn/T/d20180417-82456-131p15i --template= --single-branch --depth 1 --branch 1.0.0

Cloning into '/var/folders/j6/pdkws_z15sx4yryrmsyv5f7c0000gn/T/d20180417-82456-131p15i'...
fatal: unable to access 'https://github.com/?okcupid/OKTableViewLiaison.git/': The requested URL returned error: 400
) during validation.
```

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 601c5684c6c706ea651d176d00cf8d2e99b0a148
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/OkCupid/OKTableViewLiaison

**Comment by dnkoutso** [comment]
The tag `1.0.0` points to `0c567c314fe738bc0aa3383aed2608ce5010b76d` which is used for cloning. In this SHA your `podspec` has `s.source https://github.com/kCupid/OKTableViewLiaison.git` 

Notice the extra `k` and missing `o` from there.

Please update your tag to point to the latest one and try again.

Also please use StackOverflow under `cocoapods` tag for these types of questions.

**Comment by dylanshine** [comment]
@dnkoutso I don't believe that is correct. The URL in the podspec for that SHA is 

```  s.source           = { :git => 'https://github.com/OkCupid/OKTableViewLiaison.git', :tag => s.version.to_s }
```

**Comment by dylanshine** [comment]
OkCupid
