### ISSUE TITLE
Cocoapods1.5.0 ${TARGET_TEMP_DIR} will caused LaunchImage invalid

### ISSUE THREAD

**Issue by wangjindong** [CocoaPods/CocoaPods#7654]
${TARGET_TEMP_DIR} will caused app be black at top and bottom.

It be similar without LaunchImage。

But ${BUILD_DIR} have no problem。

I upload a sample app for this.

[Demo](https://github.com/wangjindong/CocoaPodsDemo1.5.0)

#7641 
#7590

**Comment by dnkoutso** [comment]
@MaximeLM any thoughts?

**Comment by freezy7** [comment]
I run  the demo on the iPhone X simulator, sometimes like what you say that, I think you can put the pictures of launchImage completion at Assets and then try again, my project on the 1.5.0 change ${TARGET_TEMP_DIR} did not find the problem

**Comment by dnkoutso** [comment]
@freezy7 are you saying this is not an issue with CocoaPods and its just a configuration issue with the launch images? I havent tried the sample myself yet.

**Comment by freezy7** [comment]
@dnkoutso  I'm not sure, but when LaunchImage invalid, the debug print
` CocoaPodsDemo1.5.0[61529:20102670] +[CATransaction synchronize] called within transaction`

then I remove some empty file in LaunchImage File, it will be valid.Maybe is the LaunchImage configure Problem. My project not use the `LaunchImage` and `LaunchScreen.storyBoard`, I use `LaunchScreen.xib`, hope this can help you. @wangjindong 

And when the pod version is 1.5.0, I think this script is not need in podfile

```ruby
post_install do |installer_representation|
    #解决多个Images.xcassets导致appicon显示不出来的bug
    installer_representation.aggregate_targets.each do |target|
        copy_pods_resources_path = "Pods/Target Support Files/#{target.name}/#{target.name}-resources.sh"
        string_to_replace = '${TARGET_BUILD_DIR}/assetcatalog_generated_info.plist'
        assets_compile_with_app_icon_arguments = '${TARGET_TEMP_DIR}/assetcatalog_generated_info.plist'
        text = File.read(copy_pods_resources_path)
        new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
        File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
    end
end
```

**Comment by wangjindong** [comment]
@freezy7  

It sometimes appear for me too.

My appstore project also have the same problem，and sometimes other images load failed when use [UIImage imageNamed:@""].

If you delete `pod 'Resources', :path => 'Resources/Resources.podspec'` or  change to ${BUILD_DIR} ，will find it to be correct.

So ,I don't think it happened because LaunchImage.

It's not just me, but my colleagues.

**Comment by wangjindong** [comment]
I understand what you mean and I will do it。

But now my` [UIImage imageNamed:@""] `and resources  are in two pod，It may be  incorrect，but I can't immediately change it .

**Comment by wangjindong** [comment]
So， why II can use ${BUILD_DIR}.

**Comment by freezy7** [comment]
I have the same problem,  I fix it by replace `--output-partial-info-plist "${TARGET_BUILD_DIR}/assetcatalog_generated_info.plist"` with `--output-partial-info-plist "${TARGET_TEMP_DIR}/assetcatalog_generated_info.plist"` yesterday.  Not produces other problem. And now waiting for 1.5.1 release to help me.

**Comment by wangjindong** [comment]
I guess it have  images.xcassets in my pod project.

**Comment by MaximeLM** [comment]
@dnkoutso I can reproduce the problem with the Demo App, here's what I think happens:
* Xcode compiles the assets with the --launch-image param, adds `UILaunchImages` in ${TARGET_TEMP_DIR}/assetcatalog_generated_info.plist
* CocoaPods compiles the assets without --launch-image, overwrite ${TARGET_TEMP_DIR}/assetcatalog_generated_info.plist without `UILaunchImages`
* Xcode adds the keys in ${TARGET_TEMP_DIR}/assetcatalog_generated_info.plist to the final Info.plist, does not include launch images

If I revert to using ${TARGET_BUILD_DIR} or an other path, CocoaPods does not mess with ${TARGET_TEMP_DIR}/assetcatalog_generated_info.plist so the final Info.plist still includes launch images.

The fix would be to add `--launch-image "${ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME}"` in the CocoaPods build phase, if the variable is set.

**Comment by MaximeLM** [comment]
@wangjindong could you replace `${TARGET_TEMP_DIR}/assetcatalog_generated_info.plist` with `${TARGET_TEMP_DIR}/assetcatalog_generated_info_cocoapods.plist` in your Podfile, make a clean build and see if it fixes the problem?

**Comment by wangjindong** [comment]
oh,very nice. It work for me. 
Tks and I will test again.

**Comment by dnkoutso** [comment]
@MaximeLM great, so we think we should just use a different output name?

**Comment by dnkoutso** [comment]
@MaximeLM does using a different filename still work for all other cases? or should we use the same filename and use pass `--launch-image`?

**Comment by MaximeLM** [comment]
@dnkoutso yes, since the file generated by CocoaPods can mess the Xcode build phase if think it's better to use a different output name. According to the docs http://www.manpagez.com/man/1/actool/ it is only used for app icons and launch images, CocoaPods does not need it.
```
--output-partial-info-plist path
              Emit a plist to path that contains keys and values to include in
              an  application's  info plist. path is the full path to the info
              plist, and should have the path extension .plist specified.  The
              plist is populated with information gathered while compiling the
              CAR file, and currently contains information about the app  icon
              and launch images used by the project. During builds, the infor-
              mation produced here will be merged  into  the  target  bundle's
              Info.plist.
```
But maybe we should also use `--launch-image` in the CocoaPods script. There may be an issue with tvOS:
```
--launch-image name
              Can be combined with --compile to select a launch image to  com-
              pile  to  the output directory, for most platforms. On tvOS, the
              launch image is compiled into the resulting CAR file. This  flag
              also  causes  actool  to declare the launch image in the patrial
              info plist component specified by --output-partial-info-plist.
```

**Comment by dnkoutso** [comment]
@MaximeLM care to make a PR that changes the output file and ensuring that it works on the other cases?

Additionally, really thank you for digging this stuff and helping, please feel free to take your time and if you can't I will make the PR eventually. Just doing too much stuff at the moment...

**Comment by dnkoutso** [comment]
I also think we should skip the `--launch-image` option

**Comment by MaximeLM** [comment]
@dnkoutso I'll do the PR, no problem :)

**Comment by dnkoutso** [comment]
@MaximeLM thanks you!
