### ISSUE TITLE
Could not find compatible versions for pod from several frameworks

### ISSUE THREAD

**Issue by byoth** [CocoaPods/CocoaPods#7656]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I'm sorry about my poor english and basic knowledge...

# Report

## What did you do?

Run `pod install` after added various pod frameworks to Podfile.

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

I received this error log.

```
[!] CocoaPods could not find compatible versions for pod "TheLibrary":
  In snapshot (Podfile.lock):
    TheLibrary (= 4.1.2, ~> 4.0)

  In Podfile:
    FrameworkA (~> 4.0) was resolved to 4.0.4, which depends on
      TheLibrary (~> 4.0)

    FrameworkB (~> 1.0) was resolved to 1.0.4, which depends on
      TheLibrary (~> 3.0)
```

===

I understand what is problem. because of two frameworks are needed same library but different versions. (... right?)

But I must use that versions that FrameworkA is `~> 4.0` and FrameworkB is `~> 1.0`.

What are the solutions in my case?

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
    RubyGems : 2.7.3
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/prnd/.rbenv/versions/2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 778cf97ca1feca1da20f0f9f130432ea010c9b08
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

**Comment by dnkoutso** [comment]
I think from the message the pod is not found in any of the sources. I do not remember from the top of my head if different pod versions are supported across different targets. I do not think they do.

Please also use StackOverflow under `cocoapods` tag for these kind of questions.
