### ISSUE TITLE
 [1.5, static libs] Tests not compiling with static libraries

### ISSUE THREAD

**Issue by piercifani** [CocoaPods/CocoaPods#7664]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Execute unit tests for a library 
## What did you expect to happen?

Unit tests are linked and executed correctly
## What happened instead?

The tests fail to link because it can't find the pod's symbols when linking. This is due to the  fact that `OTHER_LDFLAGS` aren't set correctly for tests for static libraries, since they don't link the pods.
### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b0c181973eabe699ca7b3a7ece6efd742697d442
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Accengage/ios-pod-specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

#pods for the app
def rx_pods
    pod 'RxSwift', '4.0.0'
    pod 'RxCocoa', '4.0.0'
    pod 'RxSwiftExt', '3.1.0'
    pod 'Moya/RxSwift', '10.0.1'
end


#publish to appstore target
target 'HelloWorld' do
    rx_pods

    #test target
    target 'HelloWorldTests' do
        inherit! :search_paths
    end
end

target 'HelloWorldKit' do
    rx_pods
    target 'HelloWorldKitTests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1.0'
        end
    end
end
```
`

## Project that demonstrates the issue

Just clone [this](https://github.com/piercifani/CocoapodsStaticLibTestsBug) project, do a pod install and command U

**Comment by dnkoutso** [comment]
@piercifani definitely can reproduce but trying to figure this out. From a linking perspective CocoaPods will *not* link static libraries to your test bundle *and* your app host otherwise you would get a bunch of warnings of having duplicate symbols.

This is why you do not see the `OTHER_LDFLAGS` in the test xcconfig.

**Comment by dnkoutso** [comment]
@piercifani as suspected if I manually add the linker flags:
```
objc[88525]: Class _TtC7RxCocoa35_RxTableViewReactiveArrayDataSource is implemented in both /Users/dimitris/Library/Developer/CoreSimulator/Devices/B319291C-741D-48D5-BB3B-DB665EEC3378/data/Containers/Bundle/Application/0F5ADC59-EE80-4F5C-BA1E-32C9B4A088D1/HelloWorld.app/HelloWorld (0x10cbfc448) and /Users/dimitris/Library/Developer/Xcode/DerivedData/HelloWorld-bccfcavwdgpjofbffseydknojjjg/Build/Products/Debug-iphonesimulator/HelloWorld.app/PlugIns/HelloWorldKitTests.xctest/HelloWorldKitTests (0x1284ee1e0). One of the two will be used. Which one is undefined.
```

**Comment by piercifani** [comment]
Definitely there's not an easy way out here. 

How did Cocoapods do this pre-Swift and `use-frameworks!`?

**Comment by dnkoutso** [comment]
@piercifani if you `use_frameworks!` we still include `-framework` for test bundles and the compilation works and without warnings. The reason for this is because dynamic frameworks are loaded once at runtime and therefore it works.

I am just puzzled here on which way to go...

**Comment by piercifani** [comment]
Exactly.

Maybe create a dummy test target app and link required frameworks there?

**Comment by dnkoutso** [comment]
well this is your own test bundle in your own project so you get to choose the app host. I do not think CocoaPods should make that decision for you.

I am guessing here...but wonder if this is an Xcode issue with Swift Static libs and modules? This is the easiest case, it should just work.

Your workaround for now is to use dynamic frameworks unfortunately.

**Comment by dnkoutso** [comment]
@piercifani another thing is...can this be reproduced without CocoaPods? Using a normal Xcode app target that links a Swift Static lib and then a test bundle that imports it but does not link it.

**Comment by paulb777** [comment]
I'd recommend that any acceptable solution only link the libraries once.  People quickly ignore the double link warning and it leads to subtle test failures. 

In testing 1.5.0 with Firebase, we discovered that CocoaPods was double linking our static library build test build and it led to subtle test failures primarily from `isKindOfClass` behaving randomly.  That issue was fixed in #7601.

**Comment by dnkoutso** [comment]
I am actually referring to reproduce it *without* double linking. 

@piercifani a workaround also is to remove `inherit! :search_paths` from your test targets in your `Podfile`. This will cause it to add the linker flags but you will get the warnings.

**Comment by dnkoutso** [comment]
And I agree, we should not double link.

**Comment by piercifani** [comment]
I did not know that removing the `inherit! :search_paths` to the Test Target would add the right flags to `OTHER_LDFLAGS`. 

Doing this and setting the host app for tests to None (which is a good idea for isolated code as libraries anyway) makes the tests run correctly and no warnings for double linking. I'll be doing this until 1.5.1 is shipped with https://github.com/CocoaPods/CocoaPods/pull/7601

Thanks a lot for your time @dnkoutso @paulb777 🎈
