### ISSUE TITLE
Cocoapods search isn't working

### ISSUE THREAD

**Issue by drpjcohen** [CocoaPods/CocoaPods#7670]
* [ X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Typed in various words and hit Enter

## What did you expect to happen?
Thought it would show a list of pods matching the search term

## What happened instead?
nothing

## CocoaPods Environment
cocoapods.org

## Project that demonstrates the issue
cocoapods.org

**Comment by dnkoutso** [comment]
Dup https://github.com/CocoaPods/CocoaPods/issues/7647
