### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by SunnyMxj** [CocoaPods/CocoaPods#7674]
# Report

## What did you do?

ℹ Run `pod install` to update framework

## What did you expect to happen?

ℹ project build success

## What happened instead?

ℹ project build error in pch file with message "xxx.h file not found"
but if commit&push code to git, other mac may build success
and after several times delete pod and "pod install" may fix this 

## CocoaPods Environment

ℹ    CocoaPods : 1.5.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.8.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git

**Comment by dnkoutso** [comment]
Please fill in the full template including a sample app. We are unable to diagnose issues with the given information.

Also better to ask StackOverflow under `cocoapods` tag.
