### ISSUE TITLE
The operation couldn’t be completed. (CocoaPods.CPPodfileInitErrors error 0.)

### ISSUE THREAD

**Issue by dmalone08** [CocoaPods/CocoaPods#7675]
* [ x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ I tried to create a New Podfile From Xcode Project

## What did you expect to happen?

ℹ I expected to open a install screen.

## What happened instead?

ℹ I got this error "The operation couldn’t be completed. (CocoaPods.CPPodfileInitErrors error 0.)"

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Fill in the template please.
