### ISSUE TITLE
`pod install` deletes references to framework listen in Podfile; workspace fails to find it

### ISSUE THREAD

**Issue by H2CO3** [CocoaPods/CocoaPods#7679]
* [√] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

I had a working CocoaPods project in Swift, with several pods installed. A colleague and I've been building it successfully since forever. Yesterday, another coworker of mine freshly cloned our repo, ran `pod install`, opened the workspace then tried to build it.

## What did you expect to happen?

I expected `pod install` to pull in all frameworks listed in the Podfile, so that Xcode can build the workspace.

## What happened instead?

My coworker signalled that after cloning the repository, he was having trouble building the project. After `pod install`, CocoaPods **deleted** references to a certain framework (`IKEventSource`) from the `project.pbxproj` file. Then swiftc complained during the build that the `IKEventSource` framework was not found (`no such module: IKEventSource` on the `import` line in the relevant source file).

Undoing the removal of these references using `git checkout -- .` doesn't seem to have helped, so I suspect there's more going on in the background than just these erroneously-removed references. Both my coworker and I have been using CocoaPods 1.4. I have upgraded to latest CocoaPods 1.5 since, which didn't make a difference.

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.12.6 (16G1314)
       Xcode : 9.1 (9B55)
         Git : git version 2.12.2
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7fdee73d264709be9888c809b5ebe5fe484d7276
```
(my coworker uses latest Xcode, `9.3 build 9E145`, but it doesn't seem to make a difference either. I managed to reproduce the issue myself by freshly re-cloning the repository into a new folder on my own computer.)

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
use_frameworks!

pod 'CryptoSwift', '0.7.2'
pod 'AWSKMS', '2.6.2'
pod 'Gloss', '2.0.0-beta.1'
pod 'Result', '3.2.4'
pod 'ReSwift', '4.0.0'
pod 'Stripe', '10.2.0'
pod 'SwiftyJSON', '3.1.4'
pod 'SwiftDate', '4.4.1'
pod 'Valet', '2.4.2'
pod 'PromiseKit', '4.4.0'
pod 'ReachabilitySwift', '~> 4.1.0'

target '<REDACTED>' do

  pod 'IKEventSource', '2.0.0'
  pod 'BEMCheckBox', '1.4.1'
  pod 'CardIO', '5.4.1'
  pod 'HockeySDK/CrashOnlyLib', '5.0.0'
  pod 'MMMaterialDesignSpinner', '0.2.5'
  pod 'PINCache', '2.3'
  pod 'SetNeedsReadable', '2.3'
  pod 'GoogleAnalytics', '3.17.0'
  pod 'DGElasticPullToRefresh', '1.1'
  pod 'Cloudinary', '2.0.2'
  pod 'MBProgressHUD', '1.0.0'
  pod 'GoogleMaps'
  pod 'Intercom', '4.1.9'

end

target '<REDACTED>-tests' do
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['Gloss',
            'SwiftDate',
            'CryptoSwift',
            'Result',
            'ReSwift',
            'SwiftyJSON',
            'PromiseKit',
            'SetNeedsReadable',
        ].include? target.name

            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

## Project that demonstrates the issue

Unfortunately, I am not allowed to post our actual project. <strike>I will try to reproduce it in an empty project, but maybe you have an idea / suggestions in the meantime…</strike> I was unable to reproduce the error in an empty project only containing `IKEventSource`.

**Comment by dnkoutso** [comment]
@H2CO3 these issues are often hard to debug and diagnose without a sample demonstrating the issue.

If possible try to reduce your problem into a smaller sample you can provide us.

Going to keep it open until a sample is provided.

**Comment by H2CO3** [comment]
Thanks for getting back to us so quickly! In the meantime, we found that the issue was with the given pod's specification. We fixed it by adding an explicit git repository URL and tag to the entry in the Podfile.

**Comment by dnkoutso** [comment]
excellent!
