### ISSUE TITLE
`pod lib lint` fails because it doesn't download source

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#7686]
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint`

## What happened instead?

>ERROR | ...
> ... No such file or directory

The `source` of the podspec were not downloaded at all, so linting cannot be accomplished properly.

## CocoaPods Environment

CocoaPods 1.5.0

### Podspec

```ruby
Pod::Spec.new do |s|
  s.name     = 'Discount'
  s.version  = '2.1.5a'
  s.license  = 'BSD-style'
  s.summary  = 'C implementation of John Gruber\'s Markdown markup language'
  s.homepage = 'http://www.pell.portland.or.us/~orc/Code/discount'
  s.author   = { 'David Parsons' => 'orc@pell.portland.or.us' }
  s.source   = { :git => 'https://github.com/Orc/discount.git', :tag => 'v'+s.version.to_s }

  s.prepare_command = './configure.sh && make blocktags && rm *.in'
  s.source_files = 'amalloc.{h,c}', 'blocktags', 'config.h', 'Csio.c', 'cstring.h', 'emmatch.c', 'generate.c', 'markdown.{h,c}', 'mkdio.{h,c}', 'resource.c', 'setup.c', 'tags.{h,c}', 'xml.c'
  s.public_header_files = 'mkdio.h'
end
```

## Project that demonstrates the issue

Example of affected podspecs that can't be lint because they need to download a `source` beforehand:
* https://github.com/tomaz/appledoc/blob/master/Specs/discount.podspec
* https://github.com/Coeur/jpush-extension-ios/blob/master/JPush-extension-iOS.podspec

**Comment by orta** [comment]
I'd love a PR to `pod lib lint` that does some detection before running the linter to see if someone really should be using `pod spec lint` ( e.g. verify the tag exists, or the files exist locally )

**Comment by Coeur** [comment]
OK
