### ISSUE TITLE
Can't search anything

### ISSUE THREAD

**Issue by tonifirnandes** [CocoaPods/CocoaPods#7690]
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

We are trying to search some pods on web with basic key "ex: image" (https://cocoapods.org/?q=IMAGE)

## What did you expect to happen?

Result of the pods

## What happened instead?

Nothing shown, after long time using this web search function, looks problem just happened now.

## CocoaPods Environment

-
## Project that demonstrates the issue
![cocoapods error](https://user-images.githubusercontent.com/3122029/39294279-83f42e98-4965-11e8-8708-78683b707284.png)

Thank you very much.

**Comment by dnkoutso** [comment]
Dup https://github.com/CocoaPods/CocoaPods/issues/7647
