### ISSUE TITLE
please use `--depth 1` when cloning with git 

### ISSUE THREAD

**Issue by ohadcn** [CocoaPods/CocoaPods#7691]
`pod install` or `pod setup` can install directly from a git repo, which is great.
But why does it needs to download the whole git repo? all commits history? Cloning the last revision (shallow clone) is enough, much faster and take much less network bandwidth / disk space.
Use `--depth 1` when cloning with git.

**Comment by dnkoutso** [comment]
Please see this issue. This is intentional but `--depth 1` *is* being used during installation, not repo installation.

https://github.com/CocoaPods/CocoaPods/issues/7280
