### ISSUE TITLE
latest version 1.5.0 bug on Jenkins with error message "You have to provide a value for either the marketing or technical version. Found neither."

### ISSUE THREAD

**Issue by crespoxiao** [CocoaPods/CocoaPods#7693]
hi , Jenkins build error, cocoapods version was 1.5.0.
when I switch to the version 1.2.1, pod install && pod update, Jenkins build succeed. 

check the discussion: https://issues.jenkins-ci.org/browse/JENKINS-26368 
please let me know when you guys fix this problem. thank you.

**Comment by segiddins** [comment]
What does this have to do with CocoaPods the tool?

**Comment by dnkoutso** [comment]
The discussion linked is from 2015. I am sorry we cannot do anything with this information. Please file a new issue with the template, explaining the problem and provide a sample app.
