### ISSUE TITLE
RuntimeError - [Xcodeproj] Unknown object version.

### ISSUE THREAD

**Issue by YouZoudeFish** [CocoaPods/CocoaPods#7697]
### Command

```
/Users/zhangmin/.rvm/gems/ruby-2.2.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.4.0.beta.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.3 (9E145)
         Git : git version 2.14.1
Ruby lib dir : /Users/zhangmin/.rvm/rubies/ruby-2.2.4/lib
Repositories : 6-mobile-ios-sdk-specs - git://198.218.6.243/mobile/ios/sdk/Specs.git @ 863e58c5e2a1251becbff1981db2a1a3bcee97e8
               master - https://github.com/CocoaPods/Specs.git @ 7e956a240d4d10cfd5e007231f6d33760e09f41a
               PrivatePods - https://github.com/ModulizationDemo/PrivatePods.git @ 15670ad09d48a8659723fee7ab238cd965416326
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform:ios,'8.0'

target 'xmpptest' do
pod 'RealReachability', '~> 1.1.8'
pod 'AFNetworking', '~> 3.1.0'
   pod 'PureLayout', '~> 3.0.2'

pod 'SDWebImage', '~> 4.0.0'
end
```

### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/xcodeproj-1.5.2/lib/xcodeproj/project.rb:217:in `initialize_from_file'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/xcodeproj-1.5.2/lib/xcodeproj/project.rb:102:in `open'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:907:in `block (2 levels) in inspect_targets_to_integrate'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:906:in `each'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:906:in `block in inspect_targets_to_integrate'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:901:in `inspect_targets_to_integrate'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer/analyzer.rb:75:in `analyze'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer.rb:243:in `analyze'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/installer.rb:116:in `install!'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command/install.rb:41:in `run'
/Users/zhangmin/.rvm/gems/ruby-2.2.4@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/lib/cocoapods/command.rb:52:in `run'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/gems/cocoapods-1.4.0.beta.1/bin/pod:55:in `<top (required)>'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/bin/pod:23:in `load'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/bin/pod:23:in `<main>'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/zhangmin/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by YouZoudeFish** [comment]
HELP!!! just build a new project-vim Podfile-pod install , then the error.....

**Comment by YouZoudeFish** [comment]
I have tried:gem install cocoapods --pre,but did not resovle the problem.

**Comment by dnkoutso** [comment]
`gem update xcodeproj`, must use version 1.5.7.

**Comment by dnkoutso** [comment]
Also update to use cocoapods 1.5.0.

**Comment by YouZoudeFish** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/13774334/39391078-b7562aae-4ad0-11e8-99d4-73566316ee4f.png">
cocoapods only can update to 1.4.0 beta.1....

**Comment by YouZoudeFish** [comment]
OMG.....I just fixed the problem.Too many posting on the internet suggest the operation：gem install cocoapods --pre
But it doesn't work for me!
If you encounter the same probem likes me,try this
<img width="432" alt="image" src="https://user-images.githubusercontent.com/13774334/39391206-884bd9be-4ad2-11e8-971c-e87ee4f9f1b4.png">

My xcode version is 9.3,so the project format settint would be :Xcode 9.3 - compatible
just select one under 9.3.
then  pod install
fixed.....it works for me(confused 2 days),hope helps you guys!!!!!

**Comment by YouZoudeFish** [comment]
@dnkoutso thanks for your help!!!

**Comment by dnkoutso** [comment]
<3 <3

**Comment by oneGain** [comment]
OMG,Amazing! But,I want know why

**Comment by YouZoudeFish** [comment]
@oneGain don't understand clearly,supposed to be the Compatibility

**Comment by mrjlovetian** [comment]
gem install cocoapods --pre

**Comment by soober** [comment]
Thanks, it works! ~By the way, Are you Chinese?游走的Fish? HaHa

**Comment by hamartia0** [comment]
Thanks, it works for me!

**Comment by hamartia0** [comment]
There is another way, update to use pod 1.5.2
`sudo gem install cocoapods`

**Comment by YouZoudeFish** [comment]
@soober Yeah,I'm a Chinese！！！

**Comment by YouZoudeFish** [comment]
@hamartia0 take it easy

**Comment by chaogeup** [comment]
@YouZoudeFish thanks. laotie

**Comment by cclbj** [comment]
@YouZoudeFish OMG! It works for me. Bro,Old iron,liuliuliu.

**Comment by iOS-Kel** [comment]
@YouZoudeFish omg! guys, thank you very much, you are very six six six!

**Comment by TyroneZhang** [comment]
"sudo gem install cocoapods " works for me.

**Comment by dushansapu** [comment]
Hit this on Terminal

sudo gem install cocoapods -n /usr/local/bin

**Comment by luckycherry** [comment]
Amazing~ thank you so much. i am chongqing man

**Comment by YouZoudeFish** [comment]
@luckycherry Beijing coder says HELLO~

**Comment by samzhiwei** [comment]
I find that if gem sources use [http://rubygems-china.oss.aliyuncs.com](url) in cocoa pods only can update to v1.3.0.
If you gem sources use this, it must change to [https://gems.ruby-china.org](url) for latest version.
Then, just hit this on Terminal
sudu gem install -n /usr/local/bin cocoa pods --pre

Finally, It works!

Thx!

**Comment by jcxc** [comment]
@YouZoudeFish  thanks bro ,  it works for me .   Six Six Six ~~~

**Comment by YouZoudeFish** [comment]
@jcxc ........

**Comment by GordonHuangYong** [comment]
brew upgrade cocoapods
work for me!

**Comment by LDKFighter** [comment]
@YouZoudeFish  How to push this changes to remote?

**Comment by YASH12366** [comment]
> OMG.....I just fixed the problem.Too many posting on the internet suggest the operation：gem install cocoapods --pre
> But it doesn't work for me!
> If you encounter the same probem likes me,try this
> <img alt="image" width="432" src="https://user-images.githubusercontent.com/13774334/39391206-884bd9be-4ad2-11e8-971c-e87ee4f9f1b4.png">
> 
> My xcode version is 9.3,so the project format settint would be :Xcode 9.3 - compatible
> just select one under 9.3.
> then pod install
> fixed.....it works for me(confused 2 days),hope helps you guys!!!!!



> OMG.....I just fixed the problem.Too many posting on the internet suggest the operation：gem install cocoapods --pre
> But it doesn't work for me!
> If you encounter the same probem likes me,try this
> <img alt="image" width="432" src="https://user-images.githubusercontent.com/13774334/39391206-884bd9be-4ad2-11e8-971c-e87ee4f9f1b4.png">
> 
> My xcode version is 9.3,so the project format settint would be :Xcode 9.3 - compatible
> just select one under 9.3.
> then pod install
> fixed.....it works for me(confused 2 days),hope helps you guys!!!!!

You save my day.... Thanks

**Comment by Shadow-NewBee** [comment]
> There is another way, update to use pod 1.5.2
> `sudo gem install cocoapods`

Thanks, it works...

**Comment by MinskLeo** [comment]
> OMG.....I just fixed the problem.Too many posting on the internet suggest the operation：gem install cocoapods --pre
> But it doesn't work for me!
> If you encounter the same probem likes me,try this
> <img alt="image" width="432" src="https://user-images.githubusercontent.com/13774334/39391206-884bd9be-4ad2-11e8-971c-e87ee4f9f1b4.png">
> 
> My xcode version is 9.3,so the project format settint would be :Xcode 9.3 - compatible
> just select one under 9.3.
> then pod install
> fixed.....it works for me(confused 2 days),hope helps you guys!!!!!

Thanks a lot. It helps even today, at 2 of January, 2021.
(Such issue reproduced after installing pods for react-native v0.64.0-rc.2)

**Comment by nmtitov** [comment]
> OMG.....I just fixed the problem.Too many posting on the internet suggest the operation：gem install cocoapods --pre
> But it doesn't work for me!
> If you encounter the same probem likes me,try this
> <img alt="image" width="432" src="https://user-images.githubusercontent.com/13774334/39391206-884bd9be-4ad2-11e8-971c-e87ee4f9f1b4.png">
> 
> My xcode version is 9.3,so the project format settint would be :Xcode 9.3 - compatible
> just select one under 9.3.
> then pod install
> fixed.....it works for me(confused 2 days),hope helps you guys!!!!!

Changing back to `Xcode 12` from `Xcode 13` helped, thanks!
