### ISSUE TITLE
Can't update pod file

### ISSUE THREAD

**Issue by Neha1211** [CocoaPods/CocoaPods#7700]
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Illformed+requirement+%60%22%3D+3.1.%2FUsers%2Fusername%2FDesktop%2FFolder%2FProjectName%2FPodfile0%22%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

/Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:91:in `block in validate_delegate': #<Pod::UserInterface::InspectorReporter:0x007f83ed7175c8> does not handle inspector_successfully_recieved_report (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:90:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:90:in `validate_delegate'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:20:in `search'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:65:in `search_query'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:59:in `search_exception'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:325:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'

**Comment by dnkoutso** [comment]
please fill in the template properly
