### ISSUE TITLE
When building pods as static libraries, a dynamic vendored_framework cannot link to its dependencies, which are also static

### ISSUE THREAD

**Issue by sirghi** [CocoaPods/CocoaPods#7701]
* [✓] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

I've removed use_frameworks! with the adoption of 1.5.0 in order to build the pods as static libraries. But I have a 3rd party pod that's delivered in binary form as a dynamic framework (using the _vendored_frameworks_ option). Now that pod itself depends on Alamofire in its podspec.

## What did you expect to happen?

Build and run the project successfully

## What happened instead?

What happens is, Alamofire gets built as a static library. And at runtime, since Dynamic Frameworks cannot link to Static Libraries, the app crashes at launch with the error:
`dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/mobile/Containers/Bundle/Application/.../.../3rdParty.framework/3rdParty
  Reason: image not found`

Is there a way I can force Alamofire be built as a static library? Or maybe there's another solution I'm not aware of. 

Cheers

Here's an excerpt from the 3rd party's podspec:
```
  s.source            = { :http => 'https:/abcd.com/lib.zip'}
    
  s.ios.deployment_target = '9.0'
  s.ios.vendored_frameworks = '3rdParty.framework'

  s.dependency 'Alamofire', '~> 4.5'
  s.dependency 'AlamofireImage', '~> 3.3'
  s.dependency 'Mixpanel-swift'
```
### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/xxxx/.rbenv/versions/2.2.3/lib
Repositories : bitbucket-cocoapod-specs - git@bitbucket.org:company/cocoapod-specs.git @ 37adc081601af8ba42c4efa3f4e4c53a83259d87
               jumio-distribution - http://mobile-sdk.jumio.com/distribution.git @ 8c5314f38df4dc73bf03398b6cf20449a1824ef9
               master - https://github.com/CocoaPods/Specs.git @ 88197b71facfd5ed4cc2e14591840f5d1371ef71
```

### Installation Source

```
Executable Path: /Users/xxxx/.rvm/gems/ruby-2.2.3/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'http://mobile-sdk.jumio.com/distribution.git'

target :myApp do

  pod 'CMPopTipView', '2.3.0'
  pod 'HCSStarRatingView', '1.4.5'
  pod 'RateView', '1.2'
  pod 'FXBlurView', '1.6.4'
  pod 'GoogleTagManager', '~> 3'
  pod 'INTULocationManager', '4.2.0'
  pod 'JumioMobileSDK'
  pod 'MBProgressHUD', '1.0.0'
  pod 'Masonry', '1.0.2'
  pod 'OAStackView', '1.0.1'
  pod 'ObjectiveSugar', '1.1.0'
  pod 'PMNibLinkableView', '0.2.0'
  pod 'PMSqueezableView', '0.3.0'
  pod 'PureLayout'
  pod 'Reachability', '3.2'
  pod 'SDWebImage', '3.8.2'
  pod 'TPKeyboardAvoiding', '1.3.2'
  pod 'TrustKit', '~> 1.4.2'
  pod 'Typhoon'
  pod 'iRate', '1.11.7'
  pod 'libextobjc', '0.4.1'
  pod 'FBSDKCoreKit', '4.18.0'

  pod '3rdParty', :podspec => '3rdParty/Active-podspec'
  
end

pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

system 'xcproj touch'
```

**Comment by dnkoutso** [comment]
@sirghi thanks for the report, I believe this has been fixed already on master, can you try it?

**Comment by segiddins** [comment]
This cannot work. Either the vendored framework needs to be built to be static, or you need to build its dependencies as frameworks

**Comment by sirghi** [comment]
@dnkoutso Tried with master, sadly the same issue.
@segiddins Exactly, is there a way to tell CocoaPods to build only those dependencies as dynamic and leave all the other pods as static?

**Comment by sirghi** [comment]
I'm no ruby or CocoaPods expert in general, but maybe there's a way for CocoaPods to detect whether a vendored framework is dynamic and in that case build its dependencies as dynamic too.

**Comment by segiddins** [comment]
> is there a way to tell CocoaPods to build only those dependencies as dynamic and leave all the other pods as static?

no

> but maybe there's a way for CocoaPods to detect whether a vendored framework is dynamic and in that case build its dependencies as dynamic too

this would be predicated on (1) being possible

**Comment by sirghi** [comment]
Too bad

**Comment by prOlya** [comment]
I know it's not what you asked about, but it could be a workaround: 
Use **use_frameworks!** and set which frameworks you want to use as dynamic
https://github.com/CocoaPods/CocoaPods/issues/7428#issuecomment-377864948

**Comment by sirghi** [comment]
Thanks @unknown-account ! Seems like an appreciated answer. Will give it a try.

**Comment by chuva-io** [comment]
Thanks @unknown-account! Your suggestion worked for me! I've spent hours on this!
