### ISSUE TITLE
ld: warning: directory not found for option '-F'

### ISSUE THREAD

**Issue by jlubeck** [CocoaPods/CocoaPods#7703]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I created a new empty project and installed a bunch of libraries with a Podfile

## What did you expect to happen?

Install everything correctly (which it did) and not have any warnings on build. 

## What happened instead?

I have a lot of `ld: warning: directory not found for option '-F' ` warnings

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.6.7
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /Users/jan/.rbenv/versions/2.3.1/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 516190102f14f23a6bfd49380518fe6af1734196
               FSPodSpecs - https://github.com/fyrastudio/FSPodSpecs.git @ 4d32b6004e070b9f626e65326ac36fa65271430f
               master - https://github.com/CocoaPods/Specs.git @ 7cd678d3ebd43f2b1c439cf8b4e29998bdebcdad
```

### Installation Source

```
Executable Path: /Users/jan/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-check       : 1.0.0
cocoapods-deintegrate : 1.0.2
cocoapods-keys        : 1.6.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
inhibit_all_warnings!

def shared_pods
    pod 'SwiftLint'
    pod 'MagicalRecord'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'RSKImageCropper'
    pod 'MaterialComponents/Tabs'
    pod 'DLRadioButton', '~> 1.4'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SwiftyBeaver'
    pod 'SnapKit', '~> 4.0.0'
    pod 'UITextView+Placeholder', '~> 1.2'
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
    pod 'OpenTok'
    pod 'FSUtils'
    pod 'LUExpandableTableView'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'lottie-ios'
    pod 'Cosmos', '~> 15.0'
    pod 'IQKeyboardManager', :inhibit_warnings => true
    pod 'SwiftyJSON'
    pod 'Stripe'
    pod 'AFNetworking', '~> 3.0.0'
    pod 'SwiftValidators'
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'SACodedTextField'
end

target 'Test' do
    use_frameworks!
    shared_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
```

## Project that demonstrates the issue

I don't think a project is needed since creating a new one with that Podfile creates this issue 100% of the times. Might be related to #4651

**Comment by jlubeck** [comment]
Interestingly, there are SOME pods that are not throwing the warning:

    pod 'SwiftLint'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
    pod 'OpenTok'

all the others are throwing it... Not sure if that helps in finding the issue...

**Comment by segiddins** [comment]
Can you try with CocoaPods master? https://guides.cocoapods.org/using/unreleased-features.html

**Comment by jlubeck** [comment]
I created a Gemfile and put this in it 
`gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git'`

Ran `bundle install`

And then `bundle exec pod install`

Same issue with the warnings

**Comment by jlubeck** [comment]
Well, like I mentioned, creating a new Xcode project from scratch with that Podfile has the issue. 
But since you are asking so nicely, here you go!

https://github.com/jlubeck/cocoapods-issue-7703

Thanks!!

**Comment by paulb777** [comment]
FRAMEWORK_SEARCH_PATHS are being added for pods that are built as static libraries.

**Comment by paulb777** [comment]
@jlubeck Is the failure and post_install workaround documented in another issue?

**Comment by jlubeck** [comment]
It probably is, but not by me... I remember finding it through a google search... I'll see if I can find it again... Just thought I'd ask you first in case you spotted the problem right away. I'll be back with what I find. Thanks!

**Comment by cyupa** [comment]
I experience something similar:
https://github.com/CocoaPods/CocoaPods/issues/7220#issuecomment-387212235

**Comment by cyupa** [comment]
Actually I managed to fix my own mistake. At one point, I think, CocoaPods warned me that there is no base config set for the Project so I set it to the one used by iOS target - that's why I was getting all that weird import issues. Changing it to none did the job.

**Comment by jlubeck** [comment]
Don't ask me why or how. But I'm not getting any more warnings even with that post install script... The  initial problem was fixed either way by removing that script from the pod file. So I'll go ahead and close this. If I run into it again, I'll open a new one. Thanks to everyone that helped me!
