### ISSUE TITLE
git:// sources are not encrypted

### ISSUE THREAD

**Issue by KrauseFx** [CocoaPods/CocoaPods#7705]
After working on https://github.com/CocoaPods/CocoaPods/pull/7250 and https://github.com/CocoaPods/CocoaPods/pull/7293 to add better protection for the user against human-in-the-middle attacks for un-encrypted network traffic, I just learned that `git://` seems to also be unencrypted by default.

Thanks to @larsxschneider for bringing this up with https://github.com/KrauseFx/krausefx.com/commit/0628e01f84ff993c578c127a350a37c8e97d8fe8#r28804197

I didn't verify that this is actually the case, but according to the docs, this is accurate.

Maybe someone here knows more about this, but if it's true, we should update CocoaPods to also warn when specifying a `git://` URL instead of `ssh://` 👍

**Comment by larsxschneider** [comment]
That sounds great! However, I would recommend to use `https://` instead of `git://`. The reason: `ssh://` requires configured SSH credentials even for public repos. `https://` should work on almost any platform for public repos with less trouble.

**Comment by larsxschneider** [comment]
Plus, at the last Git contributor summit @peff asked if it would make sense to deprecate the anonymous Git protocol (search "git anonymous protocol" in the [notes](https://public-inbox.org/git/alpine.DEB.2.20.1803091557510.23109@alexmv-linux/)). AFAIK there is no specifc plan to do this any time soon but the topic seems to be on some peoples radar.

**Comment by KrauseFx** [comment]
Agreed, I personally always use `https://`, however I do know of developers who don't have `https` auth set up

**Comment by larsxschneider** [comment]
@KrauseFx AFAIK you don't need `https` auth setup for publicly accessible repos.
