### ISSUE TITLE
When using resource_bundle, my cocoapods spec can not pass the lint validation

### ISSUE THREAD

**Issue by guoyingtao** [CocoaPods/CocoaPods#7713]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

use resource_bundle like  s.resource_bundle = {'MyFramework' => 'MyFramework/*.xcdatamodeld'}

## What did you expect to happen?

It can pass lint validation when I run "pod spec --verbose lint"

## What happened instead?

Build failed. 

```
The following build commands failed:
    	Check dependencies
    (1 failure)
    === BUILD TARGET MyFramework-MyFramework OF PROJECT Pods WITH CONFIGURATION Release ===
```

My build target is MyFramework, but it was looking for a MyFramework-MyFramework build target.
I changed the key of resource_bundle say s.resource_bundle = {'AnyKey' => 'MyFramework/*.xcdatamodeld'}, then it always tried to build the target named MyFramework-AnyKey.
I don't know why it added the extra part "-AnyKey" to my target.

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : boxfish-project - https://github.com/boxfish-project/Specs.git @ 6e3e277009be29c777c44d578641e6ec7998c1d0
               master - https://github.com/CocoaPods/Specs.git @ cb2ed4376e882be326c10b7b458618a348c1b80b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by guoyingtao** [comment]
@dnkoutso Thanks for your reply.

The following one is my project
https://github.com/guoyingtao/Trigger
Currently, it works well.

But if I change s.resources to s.resource_bundle = {'SwiftTrigger' => 'SwiftTrigger/*.xcdatamodeld'}
in SwiftTrigger.podspec, it will fail when executing "pod spec --verbose lint"

**Comment by guoyingtao** [comment]
@dnkoutso I have added the GitHub link of my project.
the pod spec file is 
https://github.com/guoyingtao/Trigger/blob/master/SwiftTrigger.podspec

Do you need more examples?

**Comment by dnkoutso** [comment]
Nope thats good enough most likely.

**Comment by amorde** [comment]
I think this has to do with .xcdatamodeld needing to be in the build phase under certain conditions.

There's a comment about this in the codebase regarding this

https://github.com/CocoaPods/CocoaPods/blob/43d1fa7cf1c8a5ede2acb2797476e6e08d09003c/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L191-L199

**Comment by guoyingtao** [comment]
Thanks for your answer! Do you know if there is any way to fix it currently?
