### ISSUE TITLE
pod lib lint success but pod spec lint faild

### ISSUE THREAD

**Issue by leoxpx** [CocoaPods/CocoaPods#7714]
My project relies on a Shared library and relies on a private library. pod lib lint is success but pod spec lint faild .
private library:
![image](https://user-images.githubusercontent.com/16935402/39704153-0d020522-523d-11e8-83bf-204c0aeb3ede.png)
pch:
![image](https://user-images.githubusercontent.com/16935402/39704168-1c03f7ce-523d-11e8-99ba-5c0725b32d84.png)
pod lib lint success
![image](https://user-images.githubusercontent.com/16935402/39704198-30a5ca68-523d-11e8-8f3a-9d241a83f659.png)
pod spec lint faild
![image](https://user-images.githubusercontent.com/16935402/39704236-459cf554-523d-11e8-93a8-8787aae6649d.png)

XWPublicBaseTools.podspec:
spec.authors      = { 'xinwang' => '123@51geshui.com' }
spec.summary      = 'first test'
spec.source       = { :git => 'http://gitlab.51geshui.com:10080/ios/XWPublicBaseTools.git', :tag =>'0.0.2'  }
spec.platform     = :ios, '9.0'
spec.source_files = 'XWPublicBaseTools/XWPublicBaseTools/**/*.{h,m}'
spec.requires_arc = true
spec.prefix_header_file = 'XWPublicBaseTools/XWPublicBaseToolsPrefixHeader.pch'

spec.dependency 'XWFoundation'
spec.dependency 'XWUIKit'
spec.dependency 'XWNetworking'

spec.dependency 'RTRootNavigationController'
spec.dependency 'MBProgressHUD'
spec.dependency 'MJRefresh'
spec.dependency 'MJExtension'
spec.dependency 'IQKeyboardManager'
spec.dependency 'Masonry'
spec.dependency 'FMDB'
spec.dependency 'ReactiveObjC'
spec.dependency 'YJBannerView'
spec.dependency 'dsBridge'
spec.dependency 'DGActivityIndicatorView'

`why?

**Comment by dnkoutso** [comment]
Where does the the tag 0.0.2 point to? Please also use StackOverlow with `cocoapods` tag to ask these questions.

There is also no sample app for us to reproduce.

I am going to close this but we can perhaps continue the discussion here. If we find out its a CocoaPods library issue I will re-open.
