### ISSUE TITLE
Suppressing a warning in an imported header

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/CocoaPods#7717]
My library (in Objective-C) includes the source for a C++ library it wraps in its repo. I never make any changes to those files, making it easier to drop in upgrades as necessary. In later versions of Xcode, some warnings have sprung up in a _header_ from this library. I'm suppressing those warnings in my library by wrapping the import with warning suppression pragmas:

``` Objective-C
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wstrict-prototypes"
#import "dll.hpp"
#pragma clang diagnostic pop
```

This is working great, and is the only way I've found to suppress imported headers' warnings, since there are no compiler flags for them. But when I run `pod lib lint`, I'm still seeing those warnings, coming from the import of that library from the generated umbrella header (MyLibrary-umbrella.h). I see the lines below in my logs higher up:

```
    While building module 'UnrarKit' imported from /var/folders/rq/5_xw4bcd7n5fbxhv_4pffj4h0000gp/T/CocoaPods-Lint-20180508-33623-1b7acvi-UnrarKit/App/main.m:3:
    In file included from <module-includes>:1:
    In file included from /Users/dfrankel/Library/Developer/Xcode/DerivedData/App-efniuyxfdheafqgmuszhqkaivyuo/Build/Products/Release-iphonesimulator/UnrarKit/UnrarKit.framework/Headers/UnrarKit-umbrella.h:14:
    /Users/dfrankel/Library/Developer/Xcode/DerivedData/App-efniuyxfdheafqgmuszhqkaivyuo/Build/Products/Release-iphonesimulator/UnrarKit/UnrarKit.framework/Headers/dll.hpp:177:31: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    int    PASCAL RARGetDllVersion();
                                  ^
                                   void
    1 warning generated.
    1 warning generated.
```

And then in the summary, I see this:

        - WARN  | [UnrarKit/unrar-lib] xcodebuild:  /Users/dfrankel/Library/Developer/Xcode/DerivedData/App-efniuyxfdheafqgmuszhqkaivyuo/Build/Products/Release-iphonesimulator/UnrarKit/UnrarKit.framework/Headers/dll.hpp:177:31: warning: this function declaration is not a prototype [-Wstrict-prototypes]

What can I do to suppress this without the sledgehammer of passing `--allow-warnings` to `pod lib lint`?

**Comment by dnkoutso** [comment]
@abbeycode another way to ask, is what would you expect cocoapods to do in this case?

**Comment by abbeycode** [comment]
@dnkoutso I'm not sure - is there a way for me to insert arbitrary code into the generated umbrella header? I could suppress the warnings with a pragma at the beginning and end of the umbrella header.

**Comment by dnkoutso** [comment]
ah I do not think there is a current way to edit this through "normal" means. Only through a post install hook perhaps.
