### ISSUE TITLE
pod lib lint failed: xxx/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386

### ISSUE THREAD

**Issue by fanxiaocong** [CocoaPods/CocoaPods#7718]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I want to make a private pod and depend on another framework(JPush)，Because the framework(JPush) does not support the i386 architecture，I added this line code in the podspec file.

```objc
  s.static_framework = true
  s.subspec 'JPushNotification' do |jpush|
      jpush.source_files = 'XCPushNotification/Classes/JPushNotification/*.{h,m}'
      jpush.dependency 'XCPushNotification/XCPushNotification'
      jpush.dependency 'XCMacros'
      jpush.dependency 'JPush', '~> 3.0.6'
      jpush.xcconfig = {
          'VALID_ARCHS' => 'armv7 armv7s arm64 x86_64'
      }
  end
```

When I submit the validation，it failed.  When I modify `VALID_ARCHS`， it can be verified through. But it doesn't support `armv7 armv7s`，What should I do？

- Modified code

```objc
      jpush.xcconfig = {
          'VALID_ARCHS' => 'arm64 x86_64'
      }
```

## CocoaPods Environment

1.5.0

## Project that demonstrates the issue

    Undefined symbols for architecture i386:
      "_OBJC_CLASS_$_JPUSHService", referenced from:
          objc-class-ref in XCPushNotification(JPushNotification.o)
    ld: symbol(s) not found for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    ** BUILD FAILED **

    The following build commands failed:
    	Ld /Users/fanxiaocong/Library/Developer/Xcode/DerivedData/App-beiqxmlfkwrnvzccxgcdrxnzorca/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/i386/App normal i386
    (1 failure)

**Comment by dnkoutso** [comment]
Can you use `pod_target_xcconfig` instead?

Also I am uncertain this is a cocoapods library issue and its best to be asked in StackOverflow under `cocoapods` tag. 

I'd be glad to re-open this issue for you once we have determined there is a defect or enhancement for the library.

**Comment by fanxiaocong** [comment]
I changed xcconfig to pod_target_xcconfig in podspec file, but it still made the same mistake. I did not find the answer to this question on StackOverflow.
Below is the code in my modified podspec file:

```ruby
  s.static_framework = true
  s.subspec 'JPushNotification' do |jpush|
      jpush.source_files = 'XCPushNotification/Classes/JPushNotification/*.{h,m}'
      jpush.dependency 'XCPushNotification/XCPushNotification'
      jpush.dependency 'XCMacros'
      jpush.dependency 'JPush', '~> 3.0.6'
#      jpush.xcconfig = {
#          # 'VALID_ARCHS' => 'armv7 armv7s arm64 x86_64',
#          'VALID_ARCHS' => 'arm64 x86_64',
#
#      }
      jpush.pod_target_xcconfig = {
          'VALID_ARCHS' => 'armv7 armv7s arm64 x86_64'
      }
  end
```
