### ISSUE TITLE
Spec repo URL becoming lower case

### ISSUE THREAD

**Issue by vincentisambart** [CocoaPods/CocoaPods#7722]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

The spec repo URL in `Podfile.lock` to not change.

## What happened instead?

The spec repo URL in `Podfile.lock` changed from `https://github.com/CocoaPods/Specs.git` to `https://github.com/cocoapods/specs.git` (lower case).

```console
$ git diff
diff --git a/Podfile.lock b/Podfile.lock
index c12081a..0e82a92 100644
--- a/Podfile.lock
+++ b/Podfile.lock
@@ -21,7 +21,7 @@ DEPENDENCIES:
   - Result

 SPEC REPOS:
-  https://github.com/CocoaPods/Specs.git:
+  https://github.com/cocoapods/specs.git:
     - KeychainAccess
     - OHHTTPStubs
     - Result
@@ -33,4 +33,4 @@ SPEC CHECKSUMS:

 PODFILE CHECKSUM: 04f0696303a5bb13bc9e3b40c61919303b45a04d

-COCOAPODS: 1.5.0
+COCOAPODS: 1.5.2
```

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
    RubyGems : 2.6.14.1
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.3 (9E145)
         Git : git version 2.17.0
```

**Comment by dnkoutso** [comment]
This is an intentional change in 1.5.2 to fix https://github.com/CocoaPods/CocoaPods/issues/7586 which broke CircleCI jobs.

Sorry going to close this one as it has already been discussed for 1.5.2.

**Comment by vincentisambart** [comment]
That seems pretty hacky :(
@dnkoutso Please make sure it's at least written in the release notes (at https://github.com/CocoaPods/CocoaPods/releases/1.5.2), I'm pretty sure I won't be the only one to be surprised by this.

**Comment by dnkoutso** [comment]
@vincentisambart agreed, sorry for the confusion. It is in the release note of cocoapods-core which is here https://github.com/CocoaPods/Core/blob/master/CHANGELOG.md where the fix happened.
