### ISSUE TITLE
SEARCH NOT WORKING ON THE WEBSITE WHY

### ISSUE THREAD

**Issue by verebes1** [CocoaPods/CocoaPods#7730]
# Report

## What did you do?

ℹWent onto cocoapods.org via safari or firefox on various devices including mobile phone tried different networks including 4G.
Searched for a known term like Chameleon

## What did you expect to happen?

ℹ Nothing happened

## What happened instead?

ℹ Simply nothing

**Comment by segiddins** [comment]
follow status.cocoapods.org for updates, and please be respectful of the fact that this infrastructure is maintained in people’s spare time
