### ISSUE TITLE
SWIFT_VERSION not being set in pods when its value is set in the project by xcconfig files

### ISSUE THREAD

**Issue by acecilia** [CocoaPods/CocoaPods#7731]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I migrated my project from Xcode build settings to xcconfig files.

After moving to xcconfig files:
Run `pod install`

## What did you expect to happen?
Build successfully.

## What happened instead?
Xcode rises an error saying: `The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.`
This error appears once per pod.

## Explanation: 
Using an xcconfig file, I am setting the swift version at target level:

`SWIFT_VERSION = 4.1`

In the project, I can see that Xcode properly set the swift version:

![screen shot 2018-05-11 at 14 38 11](https://user-images.githubusercontent.com/7938671/39924654-f6e68562-5528-11e8-9dda-b90ce13a65c5.png)

But after `pod install` the pods do not have the `SWIFT_VERSION` build setting set.

After testing a bit, I realised that setting the `SWIFT_VERSION` build setting from xcode and running `pod install` afterwards fixed the issue:

![screen shot 2018-05-11 at 14 39 41](https://user-images.githubusercontent.com/7938671/39924710-2f32773c-5529-11e8-93ed-7dea5180f127.png)

Observe the subtle difference between the two images: in the second the swift version is manually set (is bold).

## CocoaPods Environment
Cocoapods version: 1.5.2

**Comment by dnkoutso** [comment]
Yeap, looks like an API *is available* to do this as shown here https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/project/object/configuration_list.rb#L75 but https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer/target_inspector.rb#L221 is not invoking it and it defaults to `false`.

**Comment by armcknight** [comment]
I just hit this issue when assigning an xcconfig to the project level, instead of target level, so that all targets inherit the `SWIFT_VERSION` build setting. I did confirm that it worked if I instead assigned it directly to the target.

Here are screenshots of the settings and the example project I built to verify.

<img width="1179" alt="Screenshot 2019-04-10 11 59 33" src="https://user-images.githubusercontent.com/3241469/55909441-8665a900-5b88-11e9-9cf2-b38d3e6857ce.png">
<img width="1482" alt="Screenshot 2019-04-10 11 59 54" src="https://user-images.githubusercontent.com/3241469/55909442-8665a900-5b88-11e9-9afe-3f9051c3cebc.png">
[cp-swift-5-xcconfig.zip](https://github.com/CocoaPods/CocoaPods/files/3065618/cp-swift-5-xcconfig.zip)


Here's some console output. Let me know what else I can provide to help!

```
> rbenv exec bundle exec pod --version
1.6.1
> rbenv exec bundle exec pod install
Analyzing dependencies
Downloading dependencies
Installing Alamofire (4.8.2)
[!] Unable to determine Swift version for the following pods:

- `Alamofire` does not specify a Swift version and none of the targets (`cp-swift-5-xcconfig`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by armcknight** [comment]
I just hit this issue again because I forgot about the nuances mentioned in my previous comment :D 

Should I open a separate issue for it or is this a better place to continue the conversation?

**Comment by dnkoutso** [comment]
Upload a sample here. we will re-open if confirmed its an issue.

**Comment by armcknight** [comment]
Thanks for replying @dnkoutso, the sample project linked from my last comment is still available for download. Please let me know if it's not acceptable, or if the instructions aren't clear or reproducible.

**Comment by ExtremeMan** [comment]
Looks like this issue still exists. Any suggested workaround besides of hardcoding in the project file?
