### ISSUE TITLE
Unable to include subspec framework in app extension target

### ISSUE THREAD

**Issue by atreat** [CocoaPods/CocoaPods#7733]
This issue is more a discussion of what I needed to do to get this working and asking the core team if this is expected/desired.

# Report

## What did you do?

I have a private pod that I is distributed as a framework. I recently was tasked to add a feature that on iOS requires the App target to have an embedded NotificationService extension.

In order to implement this, I figured I would have most of the Notification handling implemented as a subspec. This would allow consumers that would like to take advantage of the improved notification UX could pull in the subspec framework only inside the app extension target.

Here's a snippet from the podspec
```ruby
  spec.default_subspec = 'Core'
  spec.subspec 'Core' do |core|
    core.source_files        = "Classes", "Classes/**/*.{h,m,swift}"
    core.public_header_files = "Classes/**/*.h"
    core.prefix_header_file  = "Supporting\ Files/Prefix.pch"
  end

  spec.subspec 'NotificationService' do |ns|
    ns.source_files = "NotificationService"
  end
```

## What did you expect to happen?

I expected the consuming Apps to pull in two frameworks from 'MyCustomPod'. One named 'MyCustomPod' for the 'Core' spec linked to the consuming App target. Another named 'MyCustomPod_NotificationService' for the Notifications subspec linked to the consuming App Extension target.

Here is the consuming Podfile:

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App
  pod 'MyCustomPod', path: '../MyCustomPod'

end

target 'Notification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Notification
   pod 'MyCustomPod/NotificationService', path: '../MyCustomPod'

end

```

## What happened instead?

Cocoapods generates the project successfully, but at runtime when my Core framework is called I receive a dyld error.

```
dyld: Symbol not found: _OBJC_CLASS_$__TtC10MyCustomPod14MyCustomClass
  Referenced from: /Users/me/Library/Developer/CoreSimulator/Devices/54B7F5DA-BC0A-448B-8E74-4DB6734DF03E/data/Containers/Bundle/Application/3CAEB964-3D5C-4EE3-A7A6-50B46AA56601/App.app/App
  Expected in: /Users/me/Library/Developer/CoreSimulator/Devices/54B7F5DA-BC0A-448B-8E74-4DB6734DF03E/data/Containers/Bundle/Application/3CAEB964-3D5C-4EE3-A7A6-50B46AA56601/App.app/Frameworks/MyCustomPod.framework/MyCustomPod
 in /Users/me/Library/Developer/CoreSimulator/Devices/54B7F5DA-BC0A-448B-8E74-4DB6734DF03E/data/Containers/Bundle/Application/3CAEB964-3D5C-4EE3-A7A6-50B46AA56601/App.app/App

```

## Initial investigation

This means the `MyCustomClass` symbol isn't found inside the framework binary. If i use the `nm` tool I can confirm that that symbol does not exist in the 'Expected' binary path. If I use `nm` on each of the frameworks using the path linked from the Pods/Products groups I do see that the Notification binary does not contain this symbol (which makes sense) and the Core binary does (which also makes sense). I also notice the 'Expected' binary path from the error output above contains all of my Notification framework's symbols.

It seems that the Notification binary is overwriting the Core binary when it is copied into the App Target's framework path. I notice that the 'Embed Pods Frameworks' script in the App target is acting on the NotificationService framework, I didn't expect it to be embed the notification framework directly into the App target.

<img width="754" alt="embed_pods_frameworks" src="https://user-images.githubusercontent.com/1031555/39931671-15cab0c4-550c-11e8-9830-80c2abd5aafc.png">

## Thoughts

- It seems that this issue may be related to #3979, as I'm unable to set the product name for the subspec, which means when these frameworks are embedded into the app in the 'Embed Pods Frameworks' build phase they overwrite eachother. But I don't think allowing the subspec to set a different PRODUCT_NAME would necessarily be the correct fix, as I don't think my NotificationService framework should be embedded directly into the App target anyway.

- I was able to fix my issue by breaking out my subspec into a standalone podspec. I got this idea after the discussion in #3979 so it seems like that is the best way to go. I was wondering if the core team still thinks this is the preferred distribution method for handling app extension targets?

- Should the App Extension target have an 'Embed Pods Frameworks' Build Phase step? Currently there is not a `Pods-Notification-frameworks.sh` script in the 'Targets Support Files' group. I'd expect the frameworks used by this target to be embedded into the target, not into the app target.

**Comment by segiddins** [comment]
You’re going to run into trouble by using different sets of subspecs across different targets that get bundled into the same product

**Comment by evanxie-cn** [comment]
@segiddins excuse me, how could I use private pod and public pod in the same project?

**Comment by segiddins** [comment]
@atreat CocoaPods can only embed a single framework with a given name, so you're _not_ able to expose different functionality to the extension and the main app by using subsepcs

**Comment by pigmasha** [comment]
Is there any workaround? I have the same situation - the notification extension target only needs a subspec of some pod, while app target requires a whole pod. This is necessary because extensions are limited in memory

**Comment by Fab1n** [comment]
please I need help there, too

**Comment by pigmasha** [comment]
I solve by creating a separate project that builds subspec as a static library. Here is a Podfile
```
use_frameworks!
workspace 'TestApp.xcworkspace'

target :TestApp do
  pod 'TestPod'
end

# Use separate project for extension pods
target :ExtensionPods do
  use_frameworks! false
  project 'TestAppExt/ExtensionPods.xcodeproj'
  pod 'TestPod/Engine'
end
```

In main project I link with the library manually
```
OTHER_LDFLAGS = -ObjC "-l"TestPod-Engine"
HEADER_SEARCH_PATHS = Pods/Headers/Public/
LIBRARY_SEARCH_PATHS = "$(BUILT_PRODUCTS_DIR)/TestPod-Engine"
```

**Comment by Fab1n** [comment]
Thank you @pigmasha, that is an approach that is worth to be explored.
