### ISSUE TITLE
Test target with inherit! :search_paths tries to link against inherited static library pods

### ISSUE THREAD

**Issue by kballard** [CocoaPods/CocoaPods#7735]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

When pulling in a prebuilt static library pod, `inherit! :search_paths` doesn't work and the target tries to link against the library anyway (which fails).

## What did you do?

`pod install` followed by trying to build the unit tests.

## What did you expect to happen?

The unit tests should build.

## What happened instead?

I get a linker error saying the static library can't be found (in the case of the attached project it's the `Smartling` library).

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G1314)
       Xcode : 9.2 (9C40b)
         Git : git version 2.16.3
Ruby lib dir : /opt/local/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a807fa1178202d4ee9a4d38cbcd1bfc69e8ff7d9
```

### Installation Source

```
Executable Path: /opt/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.2'

target 'InheritTest' do
  pod 'Smartling'
  
  target 'InheritTestTests' do
    inherit! :search_paths
  end
end
```

## Project that demonstrates the issue

[InheritTest.zip](https://github.com/CocoaPods/CocoaPods/files/1996358/InheritTest.zip)

**Comment by kballard** [comment]
In a quick test it appears using a prebuilt dynamic framework pod works, it's just the static library case that's broken.

In the dynamic framework case, the nested target still ends up with `OTHER_LDFLAGS` trying to link against the inherited frameworks, but the linker is ok with this. For example, with the attached project, if I switch to `pod 'Smartling-framework'` then the test target ends up with

```
OTHER_LDFLAGS = $(inherited) -framework "Smartling" -framework "UIKit"
```

**Comment by dnkoutso** [comment]
@kballard I believe this is intentional, the static library should not link to the test target because it will already be linked to the app target causing warnings of duplicate symbols.

**Comment by dnkoutso** [comment]
I might be wrong though let me check your sample.

**Comment by kballard** [comment]
@dnkoutso Well yes, the bug is CocoaPods has configured the test target to try and link to the static library anyway, when it shouldn't.

**Comment by dnkoutso** [comment]
@kballard definitely a bug.

**Comment by dnkoutso** [comment]
Works with non vendored static library pods.

**Comment by dnkoutso** [comment]
wait a minute, @kballard this is not a cocoapods issue. The podspec for Smartling is wrong.

https://github.com/CocoaPods/Specs/blob/master/Specs/6/a/2/Smartling/1.4.6/Smartling.podspec.json

It seems whoever published it is treating the library as a *system* library but it should be `s.vendored_libraries` and not needing to set the search paths manually via the `xcconfig` tag.

**Comment by kballard** [comment]
Ah hah. I'll file a bug on them. Thanks.

**Comment by kballard** [comment]
Filed as https://github.com/Smartling/ios-lqa-sdk/issues/8.
