### ISSUE TITLE
 [pod lib lint  ERROR] None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon"

### ISSUE THREAD

**Issue by zyw113** [CocoaPods/CocoaPods#7741]
/* com.apple.actool.errors */
    : error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".
    /* com.apple.actool.compilation-results */
    /Users/zyw113/Library/Developer/Xcode/DerivedData/App-gtvmgbszbrzyxjfczydyqmvxdylg/Build/Products/Release-iphonesimulator/App.app/Assets.car
    /Users/zyw113/Library/Developer/Xcode/DerivedData/App-gtvmgbszbrzyxjfczydyqmvxdylg/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/assetcatalog_generated_info_cocoapods.plist

    Command /bin/sh failed with exit code 1

    ** BUILD FAILED **

    The following build commands failed:
    	PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/zyw113/Library/Developer/Xcode/DerivedData/App-gtvmgbszbrzyxjfczydyqmvxdylg/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Script-347E47FF259797CA6DFBEC6D.sh
    (1 failure)
   Testing with `xcodebuild`.
 -> GurnShareService (1.0.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  warning: no rule to process file 'BaseExtensions/BaseExtensions/Classes/Core/Foundation/CommonCrypto/module.modulemap' of type sourcecode.module-map for architecture i386
    - NOTE  | xcodebuild:  warning: no rule to process file 'BaseExtensions/BaseExtensions/Classes/Core/Foundation/CommonCrypto/module.modulemap' of type sourcecode.module-map for architecture x86_64
    - NOTE  | [iOS] xcodebuild:  : error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".

/Users/zyw113/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.5.2/lib/cocoapods/command/lib/lint.rb:85:in `block in run'
/Users/zyw113/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.5.2/lib/cocoapods/command/lib/lint.rb:54:in `each'
/Users/zyw113/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.5.2/lib/cocoapods/command/lib/lint.rb:54:in `run'
/Users/zyw113/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/zyw113/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.5.2/lib/cocoapods/command.rb:52:in `run'
/Users/zyw113/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.5.2/bin/pod:55:in `<top (required)>'
/Users/zyw113/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/zyw113/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/zyw113/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/zyw113/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dnkoutso** [comment]
Can you please upload a sample app for us to use?

**Comment by zyw113** [comment]
Thank you! I have already solved it, Resources can be put into the Bundle file。

**Comment by zengzhihui** [comment]
@zyw113 I have the same problem. How do you resolved?
