### ISSUE TITLE
所有使用cocoapods库管理的项目，xcodeproj都不见了~  是所有的

### ISSUE THREAD

**Issue by hahazheng** [CocoaPods/CocoaPods#7742]
![wechatimg1](https://user-images.githubusercontent.com/14149301/40031218-3a2bcb84-5821-11e8-8c47-9820f641963d.jpeg)
<img width="427" alt="qq20180515-092055 2x" src="https://user-images.githubusercontent.com/14149301/40031230-48e6d970-5821-11e8-8439-b96447ab435c.png">
本地大致有这样的项目10多个，神奇的是，工程文件都不见了，导致无法用Xocde打开，这是什么原因呢  ？

**Comment by orta** [comment]
Sorry, I'm afraid CocoaPods' maintainers can only help with questions in English, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
