### ISSUE TITLE
Adding script_phase to vendored_frameworks in Podspec causes `dyld: Symbol not found:`

### ISSUE THREAD

**Issue by vkedwardli** [CocoaPods/CocoaPods#7746]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Adding a `script_phase` to a `vendored_frameworks` podspec

## What did you expect to happen?

Only the `script_phase` should be added.

## What happened instead?

1. There is a new target inside the Pods.xcodproj, with the `script_phase` added to `Build Phases` (Not harmful to me actually, just stating the difference, without `script_phase` I can't see the target for vendored framework)

2. What actual breaks:
A redundant `install_framework` function is added to `Pods-$(Target)-frameworks.sh`
```diff
   install_framework "${PODS_ROOT}/../Foo/Foo.framework"
   install_dsym "${PODS_ROOT}/../Foo/Foo.framework.dSYM"
+  install_framework "${BUILT_PRODUCTS_DIR}/Foo/Foo.framework"
```
(First 2 line is the original lines with only `vendored_frameworks` in podspec, the newline appears right after adding a `script_phase`)

Causing the contents of the vendored framework is stripped like other compiled frameworks, resulting `dyld: Symbol not found:`

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3.1 (9E501)
         Git : git version 2.13.0
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a6d38046fc6442739144e0ff2c0d0ab434a4ee57
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Yeap most likely an issue, do you have a sample app to reproduce ?

**Comment by vkedwardli** [comment]
@dnkoutso thanks for verifying

You may refer to:
https://github.com/vkedwardli/Cocoapods-issue-7746

You should be able to build and run the project with this commit
https://github.com/vkedwardli/Cocoapods-issue-7746/commit/07fcff071501f4b6a97b5314f9dbaf43597feddb

and right after adding the `script_phase` and do a `pod install` (https://github.com/vkedwardli/Cocoapods-issue-7746/commit/7accc10f57f9416a98c0aa55135a4b826c362531), it can't even run

(a bit different from my original issue, in my environment the project still can build? Anyways this projects still can reflect the additional line being injected into the `Pods-$(Target)-frameworks.sh`, see:https://github.com/vkedwardli/Cocoapods-issue-7746/commit/7accc10f57f9416a98c0aa55135a4b826c362531#diff-a49c46049bf2e1702953653ee842c9db)

Hope this could help spotting the bug, please notify me if the demo project requires the exact replication) :D

**Comment by vkedwardli** [comment]
May not be related, while using a really really really old cocoapods xcode project (since Swift 1 or 2 era, now Swift 4.1), adding `script_phase` to the vendored framework and `pod install` again, it only adds the `install_framework "${BUILT_PRODUCTS_DIR}/Foo/Foo.framework"` line without changing the project structure a lot, and the project still can build without errors

But on a completely brand new project, it won't build at all after adding the `script_phase` like the above example
