### ISSUE TITLE
Only happen in Archive - Can't find libPods.a

### ISSUE THREAD

**Issue by mickeyckm** [CocoaPods/CocoaPods#775]
Hi, 

I search and try all sort of methods, but not working. 

ld: file not found: /Users/xxxxx/Work/xxxxx/codes/xxxxx/DerivedData/xxxxx/Build/Intermediates/ArchiveIntermediates/xxxxx/InstallationBuildProductsLocation/Applications/libPods.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm using XCode 4.6 and iOS 5.0.

I'm not sure what else to do. It works fine when I run it. Only a problem when I try to archive it. 

Cheers,
Mickey

**Comment by otto1020** [comment]
@johnnyclem

Thanks a lot

**Comment by aibeke** [comment]
Hi,
I have same problem, but my attempt to rectify fails.

Podfile:
`platform :ios, '7.0'

target 'KGD' do

  # Pods for KGD
  pod 'SDWebImage', '~>3.6'
  pod 'MVYSideMenu', '~> 1.0.0'
  pod 'SpinKit', '~> 1.1'
  pod 'TGLStackedViewController', '~> 1.0'
  pod 'XBPageCurl', '~> 1.0.1'
  pod 'Reachability', '~> 3.2'
  pod 'ZXingObjC', '~> 3.1.0'

  target 'KGDTests' do
    inherit! :search_paths
    # Pods for testing
  end

end`

Screen of project structure and error:
![2016-09-21_1601](https://cloud.githubusercontent.com/assets/5820013/18708568/fcd7f5ae-8014-11e6-8c96-774e5d668c7e.png)

Error message:
**ld: library not found for -lPods
linker command failed with exit code 1 (use -v to see invocation)**

Help please.
