### ISSUE TITLE
Cocoapods does not properly generate HEADER_SEARCH_PATHS for vendored_library & private_header_paths

### ISSUE THREAD

**Issue by ronak2121** [CocoaPods/CocoaPods#7758]
Hi,

I'm using Cocoapods 1.5.2 on High Sierra/Xcode 9.2. I have a project that depends on ffmpeg that I'm trying to write a pod spec for.

I'm pulling in ffmpeg into my project by setting HEADER_SEARCH_PATHS and LIBRARY_SEARCH_PATHS to refer to it when I'm not using Cocoapods. 

In the podspec, I'm trying to set the vendored_library and private_header_paths so Cocoapods does the same. I see the LIBRARY_SEARCH_PATHS set, but not the HEADER_SEARCH_PATHS.

* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I'm running `pod lib lint --verbose` on my project to validate my podspec. I've tried using source_files, public_header_files, private_header_files, header_dir, and header_search_mappings. None of them work in this circumstance. As you can see, the project builds just fine once you set the header_search_path manually like I've done in my project.

## What did you expect to happen?
The HEADER_SEARCH_PATHS & LIBRARY_SEARCH_PATHS are correctly set.

## What happened instead?
The HEADER_SEARCH_PATHS is not set, so the internal imports to ffmpeg are not able to be found.

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.2 (9C40b)
         Git : git version 2.6.3
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories
master - https://github.com/CocoaPods/Specs.git @ 70ffae19e308df729df3a605e5a5ea2a54c804a3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0

```
# Project that demonstrates the issue
[TestApp.zip](https://github.com/CocoaPods/CocoaPods/files/2019661/TestApp.zip)

**Comment by dnkoutso** [comment]
@ronak2121 I haven't taken a more in-depth look but can you try master (upcoming 1.6.0)? I believe thi might be fixed with the revamped build settings

**Comment by dnkoutso** [comment]
@ronak2121 not sure if master will do the trick, quickly tried it seems like a configuration issue here

**Comment by dnkoutso** [comment]
With master commit I managed to compile it successfully by fixing the import `#import <libavfilter/avfilter.h>`

You will probably need a subspec for this to change the `header_dir` property.

**Comment by ronak2121** [comment]
Hey thanks for the help, so are you saying:

1. I should make a subspec for avutil and another for avfilter?
2. Which import did you have to change?
3. Will this work in version 1.5.2?

**Comment by ronak2121** [comment]
I switched to using 3 subspecs, and I see the headers properly being segmented. However, Cocoapods 1.5.2 still doesn't set the HEADER_SEARCH_PATHS, even with the dependencies set.

**Comment by ronak2121** [comment]
gem update cocoapods --pre doesn't show any available versions of Cocoapods...how do I uninstall 1.6.0?

**Comment by dnkoutso** [comment]
@ronak2121 there is no 1.6.0 released yet and we do not have ETAs for releases. You will have to use something like https://bundler.io/ to setup easier and point to a specific SHA.

**Comment by dnkoutso** [comment]
Most likely yes

**Comment by ronak2121** [comment]
Why is this closed? I can’t even verify this on 1.6.0 not update to it en masse for my team.

**Comment by dnkoutso** [comment]
@ronak2121 you can still verify this even without 1.6.0.beta.1 being released.

Use https://bundler.io/

```ruby
source 'https://rubygems.org' do
  gem 'cocoapods', git: 'https://github.com/CocoaPods/CocoaPods'
end
```

Then `bundle install` and then `bundle exec pod install`.

**Comment by segiddins** [comment]
See https://guides.cocoapods.org/using/unreleased-features.html for a guide on using unreleased features

**Comment by dnkoutso** [comment]
1.6.0.beta.1. shipped
