### ISSUE TITLE
project symlink not work

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7761]
CocoaPods v1.5.0 and v1.5.2:

I have a project, a development pods and other development pods in the project directory, but all projects are under the symlink directory. eg:
```
- MyApp -> .mbox/repos/MyApp
                      |---MySDK2
                             |---MySDK2.podspec
- MySDK -> .mbox/repos/MySDK
                      |---MySDK.podspec
- Podfile
```

In the `Podfile`:
```
project 'MyApp/MyApp.xcodeproj'

target 'MyApp' do
    pod 'MySDK', :path=>"MySDK"
    pod 'MySDK2', :path=>"MyApp/MySDK2"
end
```

I found the `Development Pods` in `Pods` project group will not work:

![image](https://user-images.githubusercontent.com/1251192/40305325-9d5a7600-5d2c-11e8-821c-a95b6d714888.png)

Demo here: https://github.com/Whirlwind/CocoaPodsTestSymlink

**Comment by dnkoutso** [comment]
Yes. I believe this is the a bug. An attempt was made here https://github.com/CocoaPods/CocoaPods/pull/7051 but was not finished to land because it had various drawbacks.

**Comment by dnkoutso** [comment]
which was this issue https://github.com/CocoaPods/CocoaPods/issues/6603
