### ISSUE TITLE
Obj-C project with Swift pod fails with error about missing SWIFT_VERSION

### ISSUE THREAD

**Issue by kballard** [CocoaPods/CocoaPods#7770]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

If I have a pure-Obj-C project and I try to add a Pod dependency that uses Swift, I get an error during dependency analysis that looks like

> Check dependencies
> 
> The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

I trivially reproduced this by creating a brand new iOS app project with Objective-C set as the language, adding Podfile with a single pod that uses Swift (I picked [PMJSON](https://github.com/postmates/PMJSON)), running `pod install`, and hitting Build.

### Stack

```
   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.3.1 (9E501)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b7a6aff002b37ae77f2f9c034a9e2c600d583e6c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
project 'Bar.xcodeproj/'

platform :ios, '11.3'

target 'Bar' do
  use_frameworks!

  pod 'PMJSON'
end
```

## Project that demonstrates the issue

[Bar.zip](https://github.com/CocoaPods/CocoaPods/files/2029491/Bar.zip)

**Comment by kballard** [comment]
It looks like the `SWIFT_VERSION` build setting must be defined in the app target prior to invoking `pod install`.

**Comment by dnkoutso** [comment]
@kballard correct. It must be.  Should be fairly easy to make an enhancement PR to catch that a bit earlier.

**Comment by kballard** [comment]
Why does Cocoapods even care about the `SWIFT_VERSION` in the main app, though? Why does that affect building my pods?

**Comment by dnkoutso** [comment]
@kballard I might not have the full historical context but earlier versions of CocoaPods did not support a `swift_version` DSL to be set at the podspec level. Furthermore, Xcode only supported a single version of Swift but as of Xcode 9 you can have multiple versions per-target (e.g. 3.2 and 4.0).

I guess earlier when only a _single_ version was supported CocoaPods reads that from the users target and then applies it to all the pods automatically.

Since 1.4.0 there is a `swift_version` DSL but we cannot remove all the prior functionality to preserve compatibility and until pod authors update their podspecs.

**Comment by dnkoutso** [comment]
> I should be able to use a Pod that requires Swift 4.0 while my app is still using Swift 3.2.

This is now possible in >= 1.4.0.

> In the case of a Swift pod that does not set s.swift_version AND does not have a .swift-version file then using SWIFT_VERSION of the app is an acceptable fallback

This is _almost_ what happens today (>= 1.4.0) with the exception of the `.swift-version` which is not usually a file included in podspecs. It actually is exactly what happens during validation (`lint`).

Will keep the issue open to at least add a warning for:

a) When the users app `SWIFT_VERSION` is not set but there are pods that use Swift (and have no `s.swift_version` present)
b) Potentially add a warning for the case above but probably with an option to be silenced as it will be rather noisy.

Another longer term view in a CocoaPods 2.0.0 we force an error if `s.swift_version` isn't set for a pod that uses Swift.

**Comment by dnkoutso** [comment]
Actually I think a) in my comment above should be an error during `pod install`.

**Comment by kballard** [comment]
Why is the `.swift-version` file not actually being used? I thought the whole point of it was to set the `SWIFT_VERSION` for the Pod. I never bothered to update my pods to use the new `swift_version` DSL because I didn't think it mattered (and because the last time I thought about this, 1.4.0 had literally just been released that day and I didn't want to break compatibility with older versions).

**Comment by dnkoutso** [comment]
@kballard its been used during linting (`lint` or `push`) command but the file is not present during installation for a consumer.

Again, most of this predates me but we can expand the scope here to include the `.swift-version` file or we can migrate to the DSL.

**Comment by dnkoutso** [comment]
@kballard opened a PR just now that covers the a) case. It will now be an error for the original issue you discovered.

If its sufficient we can close this here and generally push others to move to use the `swift_version` DSL.

**Comment by kballard** [comment]
We should probably emit a warning during `pod lib lint` if it includes swift files but doesn't use the `swift_version` DSL. That would be the most effective way to push people towards using it.

I'll go ahead and close this issue in response to your PR, and I'll file an issue about the `pod lib lint` warning specifically.
