### ISSUE TITLE
Conflicts around in Pods/Manifest.lock checksum prevent pod install

### ISSUE THREAD

**Issue by iwllyu** [CocoaPods/CocoaPods#7775]
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

tl;dr: I don't understand why I can't do a `pod install` when there are conflicts in `Pods/Manifest.lock`. or around Podfile.lock or Manifest.lock file checksums

Would/Could a plugin enable the behavior I'm desiring?

## What did you do?

After merging branches in git, and resolving conflicts in the Podfile and Podfile.lock, I should be able to `pod install` to "fix" any conflicts in my Pods/ folder, but I have to resolve conflcits in the Pods/Manifest.lock file too. 

Usually the conflicts are for the checksum. It doesn't matter if I choose to resolve with mine or theirs, `pod install` creates a new checksum. So why does it matter if there are merge conflicts in the Manifest.lock file? Or conflicts around the checksum in `Podfile.lock` ?

## What did you expect to happen?

`pod install` succeeds even if there are conflicts in the `Pods/` folder.
Or if the conflicts are only around the checksum in Podfile.lock

## What happened instead?

[!] ERROR: Parsing unable to continue due to merge conflicts present in:
the file located at ~/proj/Pods/Manifest.lock

## CocoaPods Environment

CocoaPods : 1.4.0

**Comment by amorde** [comment]
The merge conflicts prevent CocoaPods from parsing the file correctly. This is a known issue, see https://github.com/CocoaPods/CocoaPods/issues/7517

This is definitely something we want to fix. PRs are welcome :)

**Comment by dnkoutso** [comment]
Closing this as "dup" of #7517 

There is also a workaround available via a plugin https://github.com/segiddins/cocoapods-amicable which removes this from the `Podfile.lock`
