### ISSUE TITLE
`pod lib lint` should have --platform flag

### ISSUE THREAD

**Issue by kballard** [CocoaPods/CocoaPods#7783]
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

The `pod lib lint` command should have a `--platform` flag to allow me to request that only specific platforms are linted. The idea here is when I'm testing podfile changes that are platform-agnostic, I don't want to wait for it to build 4 different times when building for a single platform is sufficient. It already has the `--fail-fast` flag but that only makes failure faster, it doesn't make success faster.

**Comment by dnkoutso** [comment]
This could be a good starter ticket for anyone. 

Start here https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/lib/lint.rb and then here https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/validator.rb

**Comment by amorde** [comment]
@kballard Implemented as `--platforms`, allows you to specify a list of platforms like `--platforms=ios,watchos`. This will be released with CocoaPods 1.6.0

Thanks for the suggestion!
