### ISSUE TITLE
[Master] OTHER_LDFLAGS should not be present for static library integrated targets

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7793]
I use master branch of Cocoapods, but always get very many fails. I compare the xcconfigs between generated by Master and by v1.5.3, I found many differences:

1. master add `USE_HEADERMAP = NO`, it cause all import failed.
I found that when I import other files in my project, I always get the error which can not found the header files. But all files are in same project. I think the import behavior should could import all header files in same project without any changes.

2. When my target is a static library, The xcconfig which generated by v1.5.3 has not `OTHER_LDFLAGS`. But the master will link all dependencies. I think it should not link the dependency if target is library/framework.

Is it right?

**Comment by Whirlwind** [comment]
The `USE_HEADEMAP` maybe is #1216 , the master branch lost this fix.

**Comment by Whirlwind** [comment]
Hello, somebody could help me?

**Comment by Whirlwind** [comment]
I know that.
But I must make a sure that it is a bug, then I could make the MR.

**Comment by Whirlwind** [comment]
There are many `OTHER_LDFLAGS ` in the xcconfig when user target is a static library. And if the user target is static framework, the `OTHER_LDFLAGS` is empty.

**Comment by dnkoutso** [comment]
re-opened, @Whirlwind care to make a PR? You did it already for one fo the two issues here. Try to compare 1.5.3 code and 1.6.0 (master). It changed rather significantly for performance reasons but there are obviously a few regressions.

**Comment by Whirlwind** [comment]
Sorry, I try to do it, but I still can not find the reason.... :(

**Comment by dnkoutso** [comment]
@Whirlwind I will check it out.

**Comment by dnkoutso** [comment]
@Whirlwind This is what I see for 1.5.3 vs 1.6.0 (master)

1.5.3 Pods-LibraryDemo.debug
```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/AFNetworking" "${PODS_ROOT}/Headers/Public/SDWebImage"
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/AFNetworking"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/AFNetworking" -isystem "${PODS_ROOT}/Headers/Public/SDWebImage"
OTHER_LDFLAGS = $(inherited) -ObjC -l"AFNetworking" -framework "CoreGraphics" -framework "MobileCoreServices" -framework "Security" -framework "SystemConfiguration"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
```

1.6.0 Pods-LibraryDemo.debug
```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/AFNetworking" "${PODS_ROOT}/Headers/Public/SDWebImage"
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/SDWebImage"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/AFNetworking" -isystem "${PODS_ROOT}/Headers/Public/SDWebImage"
OTHER_LDFLAGS = $(inherited) -ObjC -l"SDWebImage" -framework "ImageIO"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
```

I do not see a diff here, what is the problem?

**Comment by dnkoutso** [comment]
All of the targets in your sample app work in 1.6.0.

**Comment by Whirlwind** [comment]
First, your `1.6.0 Pods-LibraryDemo.debug` should be `1.6.0 Pods-FrameworkDemo.debug`. It seem that you print another xcconfig file..... 

The correct `1.6.0 Pods-LibraryDemo.debug`
```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/AFNetworking" "${PODS_ROOT}/Headers/Public/SDWebImage"
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/SDWebImage"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/AFNetworking" -isystem "${PODS_ROOT}/Headers/Public/SDWebImage"
OTHER_LDFLAGS = $(inherited) -ObjC -l"SDWebImage" -framework "ImageIO"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
```
I think the `-l"SDWebImage" -framework "ImageIO"` should be removed, and the `OTHER_LDFLAGS` should be `$(inherited) -ObjC` or it should be removed from xcconfig file.

**Comment by dnkoutso** [comment]
@Whirlwind let me check it out again.
