### ISSUE TITLE
There are multiple dependencies with different sources

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7796]
I have a test podfile:
```
target 'AssetsDemo' do
    pod 'SDWebImage'
    pod 'AFNetworking', path: './AFNetworkingFramework'
end

target 'FrameworkDemo' do
    pod 'SDWebImage'
end

target 'LibraryDemo' do
    pod 'AFNetworking'
end
```
First, I think the `AFNetworking` will use the `./AFNetworkingFramework` instead of from github, because I use the `path` and other use default.
But I got a error:
```
[!] There are multiple dependencies with different sources for `AFNetworking` in `Podfile`:

- AFNetworking (from `./AFNetworkingFramework`)
- AFNetworking
```

So I must use the `path` in the `LibraryDemo`:
```
target 'AssetsDemo' do
    pod 'SDWebImage'
    pod 'AFNetworking', path: './AFNetworkingFramework'
end
target 'LibraryDemo' do
    pod 'AFNetworking', path: './AFNetworkingFramework'
end
```

I think it is unnecessary, and we could use the `path` if there is not any source.

**Comment by dnkoutso** [comment]
This is not currently supported. You can also work around by this using a simple method:
```ruby
def afnetworking
  pod 'AFNetworking, path: './AFNetworkingFramework'
end

target 'AssetsDemo' do
    pod 'SDWebImage'
    afnetworking
end
target 'LibraryDemo' do
    afnetworking
end

```

**Comment by dnkoutso** [comment]
@Whirlwind going to close this one. i think its' actually harder to implement and might be a tiny confusing if it automatically changes the source.

**Comment by Whirlwind** [comment]
I think the way is not friendly. Sometime, I just change to local path for debug, and I must modify many lines.
