### ISSUE TITLE
`pod_target_xcconfig` not work in master branch

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7798]
The new `build_settings.rb` have many bugs to me....
I found that I have a pod and its podspec: 
```
  "subspecs": [
    {
      "pod_target_xcconfig": {
        "GCC_PREPROCESSOR_DEFINITIONS": "EffectFilterMode=1"
      },
    },
    {
      "pod_target_xcconfig": {
        "GCC_PREPROCESSOR_DEFINITIONS": "InvisibleWatermarkEnable=1"
      },
      "resources": "IESVideoEditor/Core/Resources/IESVideoEditorWatermark.bundle"
    },
```
After `pod install`, only a `pod_target_xcconfig` work:
```
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1 InvisibleWatermarkEnable=1
```

I check the source code, and maybe it is a bug:
```
@@ -489,7 +490,7 @@ module Pod
        # @return [Xcodeproj::Xconfig]
        define_build_settings_method :xcconfig, :memoized => true do
          xcconfig = super()
-          xcconfig.merge(pod_target_xcconfig)
+          xcconfig.merge(merged_pod_target_xcconfigs)
        end

@@ -804,7 +805,7 @@ module Pod
        #
        def pod_target_xcconfig_values_by_consumer_by_key
          spec_consumers.each_with_object({}) do |spec_consumer, hash|
-            spec_consumer.user_target_xcconfig.each do |k, v|
+            spec_consumer.pod_target_xcconfig.each do |k, v|
              (hash[k] ||= {})[spec_consumer] = v
            end
          end
```

After change the source code, `pod_target_xcconfig` will work.

**Comment by dnkoutso** [comment]
Might be a bug yes. As I said you are trying the master branch (unreleased). Thank you for doing so because you are testing it out.

**Comment by Whirlwind** [comment]
There is not  enough unit tests in the `build_settings.rb`

**Comment by dnkoutso** [comment]
There is also `pod_target_settings_spec.rb` and `aggregate_target_settings_spec`

**Comment by dnkoutso** [comment]
@Whirlwind keep in mind you are always testing an unreleased (not even beta) version.

**Comment by Whirlwind** [comment]
I known. I meant that CP pass all tests, but it seem not to find this bug. We can add more tests for new `build_settings.rb`

**Comment by dnkoutso** [comment]
yes! want to try make a PR for this?

**Comment by Whirlwind** [comment]
:( I am not good at the ruby.

**Comment by Whirlwind** [comment]
I only report the bug for you. :)
