### ISSUE TITLE
Complex version requirement in podspec

### ISSUE THREAD

**Issue by akashivskyy** [CocoaPods/CocoaPods#7800]
I'd like to specify a custom version requirement in one of my podspecs:

```none
>= 3.9.1 && < 4.0.0
```

I can't use `~> 3.9.1` because it is a completely different requirement:

```
>= 3.9.1 && < 3.10.0
```

Is there way to specify the one I want?

---

* [x] I've read and understood the [CONTRIBUTING guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) and have done my best effort to follow.

**Comment by dnkoutso** [comment]
'>= 3.9.1, < 4.0.0` works?

**Comment by dnkoutso** [comment]
Also these questions are best asked in StackOverflow under `cocoapods` tag.

@akashivskyy I am going to preemptively  close this and re-open if we find out its an actual bug in cocoapods library.
