### ISSUE TITLE
Stop linking libPods.a to framework

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7803]
The CocoaPods will not add `OTHER_LDFLAGS` into the xcconfig which used by user target if the user target is a library/framework.

I think the `libPods.a` should not be added to the `Linked Frameworks and Libraries`, too. Is it right?

**Comment by dnkoutso** [comment]
In some cases. If the user target is a framework then yes it will/should link all of these dependencies.

It probably shouldn't for user static libraries because there is no linking phase. If it does it doesn't matter because Xcode just ignores it.

What issue does this cause to you?

**Comment by Whirlwind** [comment]
In  my case, my framework is a static framework, and the framework link all dependencies will cause the symbols duplicate if the static framework link the `libPods.a` and use the `OTHER_LDFLAGS`.

As you said, the framework will keep the `OTHER_LDFLAGS` link dependencies?

**Comment by dnkoutso** [comment]
for static libraries it only links them to the target app. I dont think if you build just the static library target you will see any link phase executing.

**Comment by dnkoutso** [comment]
@Whirlwind I dont think there is anything wrong here. You are integrating a few pods to your static framework and linking occurs there.

You should move these pods to the target you expect them to be linked or use `inherit! :search_paths` under your static framework target.

**Comment by Whirlwind** [comment]
Maybe the `inherit! :search_paths` work for me, but I found that the static framework still link the `libPods.a` when I use `inherit! :search_paths`. Is it right?

**Comment by dnkoutso** [comment]
uh probably not try deleting it and then `pod install` again it shouldnt add it. I think its a small de-integration issue.

**Comment by Whirlwind** [comment]
I try again. I delete the `libPods.a`, and then `pod install` again, the `libPods.a` be added again.

**Comment by Whirlwind** [comment]
My Podfile:
```
    project "AWEIM.xcodeproj"
    target :AWEIM do
        inherit! :search_paths
        podspec
    end
```
![image](https://user-images.githubusercontent.com/1251192/40762196-558657f6-64d2-11e8-836a-a9f3f74ca74d.png)

**Comment by dnkoutso** [comment]
hm it might be because its a root target. Unsure.

**Comment by Whirlwind** [comment]
I think it is a small issue, but I still hope fix it.

**Comment by Whirlwind** [comment]
I think the `Pods-AWEIM` target in `Pods` project should not be generated.

**Comment by Whirlwind** [comment]
@dnkoutso I use `abstract_target` and `inherit!`, the `libPods.a` still be linked.

**Comment by Whirlwind** [comment]
Maybe, we can remove the `libPods.a` when the dependency is empty. Like the `copy resources` build phase, it is removed if there is not any resource files.
