### ISSUE TITLE
Could we remove `Target Dependencies` in `PodTarget`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7804]
First, when user build their target, if the target is a app or test target, xcode must build the `libPods.a` before the user target. Then the `Target Dependencies` in the `Build Phases` of `libPods.a` will build by xcode.

Now, I found that all dependencies are added into the `Target Dependencies` of the `libPods.a`( `AggregateTarget` ). So the `Target Dependencies` in another dependencies (`PodTarget`) will be unnecessary. 

If user direct build the `PodTarget`, xcode should not build the dependencies in `Target Dependencies` in the `PodTarget`, and If user build their target, xcode will build the all `PodTarget` in the `AggregateTarget`. Everything is OK.

And I found that CP creates many `Placeholder Target` for the PodTarget which `should_build?` is False. As the comment:
```
                # For targets that should not be built (e.g. pre-built vendored frameworks etc), we add a placeholder
                # PBXAggregateTarget that will be used to wire up dependencies later.
                native_target = add_placeholder_target
```
If clear the `Target Dependencies` in the `PodTarget`, the placeholder is not unnecessary, too.

Is it right?

**Comment by dnkoutso** [comment]
I do not understand what the ask is here. This is increasingly becoming a pattern with multiple design questions for an unreleased version. I *really* appreciate that you are doing that and you have already caught two bugs because of this but these issues are becoming more and more questions.

What is the ask here? We now always add a placeholder target since it helps Xcode better.

**Comment by segiddins** [comment]
The target dependencies **are** necessary, since the specific order in which targets are built matters, not just that they come before the user target

**Comment by dnkoutso** [comment]
For now going to close this. @Whirlwind will re-open if the discussion leads into a bug or enhancement here.

**Comment by Whirlwind** [comment]
@dnkoutso I want to remove all placeholder target and target dependencies to increase the speed when xcode build user target. So I ask why we need the specific order.

@segiddins Thanks to answer me. But I test my project and remove all placeholder and target dependencies, everything works fine. Why do the targets in `Pods` need the specific order?

I think that targets in `Pods` are framework/library type, they will not link other library and just search header files. So they will not build in specific order.
