### ISSUE TITLE
Local pod with vendor_frameworks doesn't get added in the project at all

### ISSUE THREAD

**Issue by revolter** [CocoaPods/CocoaPods#7811]
🌈

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Vendored frameworks are not copied to the project.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.17.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 074b284209b72236f6c3bb960b64deb208dff7dc
```

### Installation Source

```
Executable Path: /Users/iulian/.gems/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'

target 'MyProject' do
    pod 'MyKitDebug', path: '../MyKit', configurations: %w[Debug]
    pod 'MyKit', path: '../MyKit', configurations: %w[Release]
end
```

## Project that demonstrates the issue

[CocoaPodsIssueSample.zip](https://github.com/CocoaPods/CocoaPods/files/2071608/CocoaPodsIssueSample.zip)

Running `pod install` in the `MyProject` directory doesn't add the `MyKit` nor the `MyKitDebug` directories in the `Pods` directory.

`pod install --verbose`:

```
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-MyProject`: (``)

Finding Podfile changes
  - MyKit
  - MyKitDebug

Fetching external sources
-> Fetching podspec for `MyKit` from `../MyKit`
-> Fetching podspec for `MyKitDebug` from `../MyKit`

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  - MyKit
  - MyKitDebug

Downloading dependencies

-> Using MyKit (0.6.0)

-> Using MyKitDebug (0.6.0)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Adding development pod helper files to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Pods-MyProject` iOS 10.0
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
    - Generating deterministic UUIDs
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-MyProject` (`MyProject.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from `/Users/iulian/.gems/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb`

Sending stats

-> Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```

I also tried `s.source = { :git => '.' }` to no avail.

**Comment by revolter** [comment]
Let me know if you need more information 😃

**Comment by dnkoutso** [comment]
@revolter I didnt try it yet but when you use `:path` directive CocoaPods just picks up everything from the local path and relative to that path. I do not believe Pods using `:path` are copied over and inside the `Pods/` folder, only the ones that are installed remotely.

What issue is this causing to you?

**Comment by revolter** [comment]
I can't reproduce it anymore :( The problem was happening when trying to compile the main project, because it didn't find a class declared in a public header in the vendored framework. The thing is that I didn't push the new podspec and framework to the Pod's repo, nor to the private specs repo.

**Comment by dnkoutso** [comment]
@revolter I am inclined to close this. So far it worked for me to compile and use the framework.

FWIW I tried this with master cocoapods (soon to be 1.6.0.beta.1)

**Comment by dnkoutso** [comment]
@revolter please follow through here and I can re-open.
