### ISSUE TITLE
error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".

### ISSUE THREAD

**Issue by zColdWater** [CocoaPods/CocoaPods#7816]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod lib lint --verbose --allow-warnings --sources='git@git.nevint.com:ios/nio-lib-repo.git,https://github.com/CocoaPods/Specs.git'

## What did you expect to happen?

Pods lint success

## Podspec file

Pod::Spec.new do |s|
  s.name             = 'FDBusinessUIControl'
  s.version          = '0.1.68'
  s.summary          = '----'
  s.homepage         = 'https://git.nevint.com/DOMOBILE-FeiDian/DOMOBILE-FeiDian-FDBusinessUIControl'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'yongpeng.zhu' => 'yongpeng.zhu@nio.com' }
  s.source           = { :git => 'git@git.nevint.com:DOMOBILE-FeiDian/DOMOBILE-FeiDian-FDBusinessUIControl.git', :tag => s.version.to_s }

  s.ios.deployment_target = '9.0'
  s.swift_version = '4.1'
  s.static_framework = true
  s.pod_target_xcconfig = { 'ENABLE_BITCODE' => 'NO' }

  s.subspec 'Hud' do |h|
    h.source_files = 'FDBusinessUIControl/Hud/**/*.{h,m,swift,xcdatamodeld}'
  end

  s.subspec 'Toast' do |t|
    t.source_files = 'FDBusinessUIControl/Toast/**/*.{h,m,swift,xcdatamodeld}'
    t.dependency 'FDFoundation'
  end
  
  s.subspec 'FDWebView' do |web|
      web.public_header_files = 'FDBusinessUIControl/FDWebView/**/*.h'
      web.source_files = 'FDBusinessUIControl/FDWebView/**/*.{h,m,swift,xcdatamodeld}'
      web.ios.resource = 'FDBusinessUIControl/FDWebView/**/*.{js}'
  end
      
  s.subspec 'PopupControl' do |pc|
    pc.source_files = 'FDBusinessUIControl/PopupControl/**/*.{h,m,swift,xcdatamodeld}'
    pc.ios.resource = 'FDBusinessUIControl/PopupControl/**/*.{xib,storyboard,xcassets}'
    pc.dependency 'FDFoundation'
    pc.dependency 'FDBusinessService'
  end
  
  s.subspec 'Form' do |f|
      f.source_files = 'FDBusinessUIControl/Form/**/*.{h,m,swift,xcdatamodeld}'
      f.ios.resource = 'FDBusinessUIControl/Form/**/*.{xib,storyboard,xcassets}'
      f.dependency 'FDBusinessUIControl/Toast'
      f.dependency 'FDFoundation'
      f.dependency 'Eureka'
  end
  
  s.subspec 'BaseController' do |bc|
      bc.source_files = 'FDBusinessUIControl/BaseController/**/*.{h,m,swift,xcdatamodeld}'
  end
  
  s.subspec 'WebView' do |wb|
      wb.source_files = 'FDBusinessUIControl/WebView/**/*.{h,m,swift,xcdatamodeld}'
      wb.dependency 'FDBusinessUIControl/BaseController'
      wb.dependency 'NIOAppKit'
  end
  
  s.subspec 'Evaluation' do |e|
      e.source_files = 'FDBusinessUIControl/Evaluation/**/*.{h,m,swift,xcdatamodeld}'
      e.ios.resource = 'FDBusinessUIControl/Evaluation/**/*.{xib,storyboard,xcassets}'
      e.dependency 'FDBusinessUIControl/Toast'
      e.dependency 'FDBusinessUIControl/Hud'
  end
  
  s.subspec 'VerifyCode' do |verify|
      verify.source_files = 'FDBusinessUIControl/VerifyCode/**/*.swift'
      verify.dependency 'FDFoundation'
  end

end

## CocoaPods Environment

   CocoaPods : 1.5.2
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
       Git : git version 2.16.3

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```
## Analysis

When I lint my Pods, I get the following error.
Why do my xcassets add "AppIcon"  icon set?

error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".

How to solve it?

**Comment by GoCac** [comment]
I also encountered the same problem. 
In my case, the pod is a kind of framework, which doesnt need AppIcon, however, the console told me the same error - "error: None of the input catalogs contained a matching stickers icon set or app icon set named "AppIcon"."

**Comment by dnkoutso** [comment]
@zColdWater @GoCac thanks for the report. This is a known issue with the `xcassets` used in your podspec and has been tracked here. https://github.com/CocoaPods/CocoaPods/issues/7617.

Going to close this one as a dup.

**Comment by zColdWater** [comment]
@dnkoutso 
OK, I want to know when this issue will be fixed.
We have to skip the lint step and then forcibly update the spec repo,  which means we cannot update pod automatically by jenkins.

**Comment by deanguo11** [comment]
I also encountered the same problem. i hope we can be settled as soon as possible. thanks~

**Comment by TalentLifeFeng** [comment]
I added a empty appIcon image set and passed the validation

**Comment by ayushgoel** [comment]
@TalentLifeFeng Where did you add the icon? In the folder pointed to by your `spec.resources` value in podspec?

**Comment by jj89757hhb** [comment]
怎么解决这个问题呢

**Comment by GoCac** [comment]
> 怎么解决这个问题呢

We using `bundle` instead of `xcassets`.
我们在 pod 里面创建一个专门的 bundle 来存放图片。

**Comment by jj89757hhb** [comment]
> > @jj89757hhb
> > 怎么解决这个问题呢
> 
> We using `bundle` instead of `xcassets`.
> 我们在 pod 里面创建一个专门的 bundle 来存放图片。

为什么会突然出现这种情况呢？
