### ISSUE TITLE
Build input file cannot be found: .xctest file

### ISSUE THREAD

**Issue by YMonnier** [CocoaPods/CocoaPods#7824]
* [ X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I updated macOS to Version 10.14 Beta (18A293u) (Mojave).
I updated my iPhone to iOS 12 beta to test ARKit 2.
Then I try to compile my private  pod library with iOS 12.  (Deployment Target 12.0)

## What did you expect to happen?
Compile my project.

## What happened instead?
I got an error with my `Products/[filename].xctest`

![screenshot 2018-06-12 at 10 21 46](https://user-images.githubusercontent.com/9322425/41278643-995c4f38-6e2a-11e8-877e-f886a02271b2.png)

![screenshot 2018-06-12 at 10 23 31](https://user-images.githubusercontent.com/9322425/41278742-df9bd9e6-6e2a-11e8-95f3-abd5e1ab331f.png)

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.6p384 (2017-12-14 revision 61254) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.2
        Host : Mac OS X 10.14 (18A293u)
       Xcode : 10.0 (10L176w)
         Git : git version 2.17.0 (Apple Git-106)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : gitlab-kzslab-specs - https://gitlab.com/KZSLAB/Specs.git @ 6eb7e4eac7ba1d93cf7d7e2d0adee749e6725cd6
               master - https://github.com/CocoaPods/Specs.git @ afba47e62e50f52d414e722590e387ca670248d7
               Specs - git@gitlab.com:KZSLAB/Specs.git @ 6eb7e4eac7ba1d93cf7d7e2d0adee749e6725cd6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.com:Private/Specs.git'

use_frameworks!

def dev
    pod 'KZSLAB-AR-Indicator', :path => '../../KZSLAB-AR-Indicator/'
end

target 'KZSLAB-AR-View_Example' do
  pod 'KZSLAB-AR-View', :path => '../'
  
  #dev

  target 'KZSLAB-AR-View_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 1.2.0'
    #pod 'Nimble', '~> 7.0.2'
    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
```

**Comment by dnkoutso** [comment]
@YMonnier thanks for the sample app! Do you happen to have a small sample app that demonstrates the issue?

**Comment by YMonnier** [comment]
unfortunately no, it's a private project and I can't reproduce the problem

**Comment by dnkoutso** [comment]
@YMonnier I am uncertain yet if its a CocoaPods issue, it might be but I cant easily tell. If you delete the red reference of `.xctest` does the issue go away? and does cocoapods add it again after `pod install`?

**Comment by YMonnier** [comment]
@dnkoutso I cannot delete de red reference...

![screenshot 2018-06-12 at 16 26 07](https://user-images.githubusercontent.com/9322425/41296547-76500b14-6e5d-11e8-83d2-798f5f37cb92.png)

Moreover, the `.xctest` file does not exist on the file system.

**Comment by dnkoutso** [comment]
Yeah that makes sense because Xcode probably adds this an expects it to be a there as a result of building the test bundle.

**Comment by dnkoutso** [comment]
I think I am looking at the wrong place...unfortunately it's very hard to guess this without a sample.

**Comment by YMonnier** [comment]
Ok, I will make an investigation...

**Comment by dnkoutso** [comment]
thank you!

**Comment by asharanasjumppace** [comment]
Is there any solutions for this issue, Im getting same issue while running Unit tests.
