### ISSUE TITLE
Can't use Swift dependency as static lib in ObjC project.

### ISSUE THREAD

**Issue by tralves** [CocoaPods/CocoaPods#7830]
🌈

* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I want to import an Swift library (PlayKit) to an ObjC project. I removed `user_frameworks!` from the Podfile. I also added a .swift file in my ObjC project to make it compile.

I tried adding a Swift bridging header in the Swift lib, but it throws the error `<unknown>:0: error: using bridging headers with framework targets is unsupported`

## What did you expect to happen?

I expected to be able to use the Swift code on my ObjC project with `#import <PlayKit/PlayKit-Swift.h>`.

## What happened instead?

`PlayKit/PlayKit-Swift.h` doesn't exist and thus my ObjC code to "see" the Swift classes from the static lib.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.4 (17E202)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ dd4290e1841b2a901112b78d37fde41f414d8c59
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

pod 'PlayKit'

target 'StaticSwiftToObjCTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for StaticSwiftToObjCTest

  target 'StaticSwiftToObjCTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StaticSwiftToObjCTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pre_install do |installer|
  def installer.verify_no_static_framework_transitive_dependencies; end
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          #config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
          if (target.name == 'PlayKit' ||
              target.name == 'PlayKitUtils' ||
              target.name == 'Log' ||
              target.name == 'PlayKitUtils' ||
              target.name == 'KalturaNetKit' ||
              target.name == 'SwiftyXMLParser')
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end
end
```

## Project that demonstrates the issue

I created this project https://github.com/tralves/StaticSwiftToObjCTest to demo the issue. In `AppDelegate.m` I am trying to import the bridge header file and it can't find it.

I may be missing some obvious step here, but I read all related issues and nothing seemed to work in my case.

Thanks!

**Comment by segiddins** [comment]
Try using `@import Playkit;` or `#import “PlayKit-Swift.h”`

**Comment by tralves** [comment]
@segiddins I didn't work... can't find the module nor “PlayKit-Swift.h”...

**Comment by segiddins** [comment]
```diff
diff --git a/StaticSwiftToObjCTest/AppDelegate.m b/StaticSwiftToObjCTest/AppDelegate.m
index bd753ca..b62b86c 100644
--- a/StaticSwiftToObjCTest/AppDelegate.m
+++ b/StaticSwiftToObjCTest/AppDelegate.m
@@ -7,7 +7,7 @@
 //
 
 #import "AppDelegate.h"
-#import <PlayKit/PlayKit-Swift.h>
+@import PlayKit;
 
 @interface AppDelegate ()
 
```

fixes it for me

**Comment by tralves** [comment]
I tried that. It says "Module 'Playkit' not found". :(

I searched about this error or modules not being imported but nothing helped me so far.

Thanks!

**Comment by segiddins** [comment]
can you update your sample project then? Since I was able to get it to compile just fine with that diff

**Comment by tralves** [comment]
Oh! It did work! I was probably trying other things with the podfile.

Thanks a million! I was dealing with this problem for such a long time! Do you have a paypal or something? I want to buy you a beer. 🍺

**Comment by segiddins** [comment]
Don't worry about it 🍻 

Glad you got things working!
