### ISSUE TITLE
[Discussion]About develop static library

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7832]
I have developed many static libraries/frameworks for a few years, but It seems that I have some different idea and develop ways with others. I want to make a discussion if somebody have free time.

I known that CocoaPods have a [pod-template](https://github.com/CocoaPods/pod-template) plugin to create a SDK with some template files. But I don't like it. I'd like my SDK target in my project rather than in Pods project. Because, when I new a file or delete a file, I must run `pod install` again. So I will install many times a day. On the other hand, I want to control more things which in the `Build Phases`. Use the `development pods` way, it could be done, but it is not friendly. So I use the Apple way to make a SDK development.

I create a static library target `MySDK` and a demo app target `MyApp`, the `MySDK` will be linked into the `MySDK`.
I have a `MySDK.podspec` and a `Podfile` in the root directory. 
`MySDK.podspec`:
```
s.dependency 'AFNetworking`
s.dependency 'SDWebImage`
```
`Podfile`:
```
target 'MySDK' do
    podspec

    target 'MyApp' do
        pod 'MyFoundationKit' # from my private spec repo and it dependencies `YYCache`
    end
end
```

After `pod install`, I get a workspace:
```
MySDK.xcodeproject
    |--MyApp.app
            |-- link Pods-MySDK-MyApp.a
            |-- link MySDK.a
    |-- MySDK.a
            |-- link Pods-MySDK.a
Pods.xcodeproject
    |-- Pods-MySDK-MyApp.a
            |-- dependency AFNetworking.a
            |-- dependency SDWebImage.a
            |-- dependency MyFoundationKit.a
            |-- dependency YYCache.a (copy from `MyFoundationKit`)
    |-- Pods-MySDK.a
            |-- dependency AFNetworking.a
            |-- dependency SDWebImage.a
    |-- MyFoundationKit.a
            |-- dependency YYCache.a
    |-- SDWebImage.a
    |-- AFNetworking.a
    |-- YYCache.a
```
The order which build `MySDK` will be:

1. Build `AFNetworking` and `SDWebImage` ( `Pods-MySDK.a` required)
2. Build `Pods-MySDK` ( `MySDK.a` required)
3. Build `MySDK`
4. Link `Pods-MySDK.a` into `MySDK.a`

The step 4 will be run by the `Link Libraries and Frameworks`, the xcode will force to link the `Pods-MySDK.a`. But xcode will not link `AFNetworking.a` and `SDWebImage.a`, because they are in `OTHER_LDFLAGS` and xcode ignore it.
Sometimes, the build will fail, xcode disallow to link a library into other library. but sometimes it works.
I don't know why it is.

The order which build `MyApp` will be:

1. Build `AFNetworking` and `SDWebImage` ( `Pods-MySDK.a` required)
2. Build `Pods-MySDK` ( `MySDK.a` required)
3. Build `MySDK`  ( `MyApp.app` required)
4. Build `YYCache.a` ( `MyFoundationKit` required)
5. Build `MyFoundationKit` ( `Pods-MySDK-MyApp.a` required)
6. Build `Pods-MySDK-MyApp` ( `MyApp.app` required)
7. Build `MyApp.app` and link all static libraries.

I think that a static library just get the header files by the `HEADER_SEARCH_PATHS` and `FRAMEWORK_SEARCH_PATHS`, and build the dependencies is Unnecessary. So I remove the `Pods-MySDK.a` from `MySDK` target. Everything works. It saves much time when I just build a static library.

The issue [Stop linking libPods.a to framework](https://github.com/CocoaPods/CocoaPods/issues/7803) will hope to remove the dependency.

The issue [[Master] `abstract_target` and `inherit` lost framework search path](https://github.com/CocoaPods/CocoaPods/issues/7828) hope fix import framework header fail.

The issue [[Master] OTHER_LDFLAGS should not be present for static library integrated targets](https://github.com/CocoaPods/CocoaPods/issues/7793) hope clear the `OTHER_LDFLAGS`, because it is unnecessary.

On the other hand, I found that there are many  `Target Dependency` in pod targets ( not AggregateTarget), and there are all dependencies in `Target Dependency` of AggregateTarget. In the example, the `MyFoundationKit` have a `YYCache` in the `Target Dependency`, and the `YYCache` also in the `Pods-MySDK-MyApp` target. Xcode will spend much time to analyze the dependency whether should build.

I have a plugin to make a pre-build for all pod targets. So my plugin will build `YYCache` target when I just build the `MyFoundationKit`. I think we just keep the `Target Dependency` of AggregateTarget and clear the `Target Dependency`  list of PodTarget. 

I hope the workspace like it:

```
MySDK.xcodeproject
    |--MyApp.app
            |-- link Pods-MySDK-MyApp.a
            |-- link MySDK.a
    |-- MySDK.a ( NO link Pods-MySDK.a)
Pods.xcodeproject
    |-- Pods-MySDK-MyApp.a
            |-- dependency AFNetworking.a
            |-- dependency SDWebImage.a
            |-- dependency MyFoundationKit.a
            |-- dependency YYCache.a
    |-- Pods-MySDK.a ( Not be linked, just keep search path, and will not dependency targets)
    |-- MyFoundationKit.a ( Not dependency YYCache.a)
    |-- SDWebImage.a
    |-- AFNetworking.a
    |-- YYCache.a
```
So the order will be changed:

1. Build `AFNetworking`, `SDWebImage`, `YYCache`, `MyFoundationKit` ( `Pods-MySDK-MyApp.a` required)
2. Build `MySDK`  ( `MyApp.app` required)
3. Build `MyApp.app` and link all static libraries.

Xcode will concurrent build all PodTargets better than the way which have many `Dependency Target` in PodTarget.

The issue [Could we remove `Target Dependencies` in `PodTarget`](https://github.com/CocoaPods/CocoaPods/issues/7804) hope clear `Dependency Target` of PodTarget.

Maybe, I have some incorrect ways or have a better way to develop a SDK, please tell me.

**Comment by Whirlwind** [comment]
My English is not good. But I've done my best to explain my ideas. If there is any misunderstanding or impoliteness, please let me know.

Thanks

**Comment by Whirlwind** [comment]
By the way, I ofter develop a static framework instead of a static library. And they should be same way. But the CocoaPods seem that have some different logic for a framework. CP maybe think the framework is a dynamic framework, I guest.

I found that CP will copy resource into the static library, too. Is it a bug?

**Comment by lolgear** [comment]
@Whirlwind You should not use SDWebImage never. Never. N-ever. It is a piece of code that smells.

You can build everything on top of URLSession ( even downloading/uploading images, yes ).

**Comment by orta** [comment]
@lolgear comments like yours are not welcome in our issues. Please keep those kind of opinions to yourself or other communities with different standards.

**Comment by Whirlwind** [comment]
Do anyone want to talk to me about it?

**Comment by Whirlwind** [comment]
How to make a pod with script phases in a podspec?

**Comment by segiddins** [comment]
https://guides.cocoapods.org/syntax/podspec.html#script_phases

**Comment by Whirlwind** [comment]
Is it the script phase in Pod Target? Not user target in user project?

**Comment by dnkoutso** [comment]
Yes pod target, its a new feature in 1.4.0.
