### ISSUE TITLE
Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa

### ISSUE THREAD

**Issue by SAVeselovskiy** [CocoaPods/CocoaPods#7835]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Got error: "Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa"

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.6p384 (2017-12-14 revision 61254) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.2
        Host : Mac OS X 10.14 (18A293u)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : GSPods - ssh://git@git.geo4.pro:49384/ios/GSPods.git @ b6f6bbe0011db70e436918e8c3b6bc889150a0c7
               master - https://github.com/CocoaPods/Specs.git @ 66d002cdf4467b318684487888e984abe72e45d1
```
Also using Xcode 10 beta
### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'GSMapCamera_Example' do
  pod 'GSMapCamera', :path => '../'
  pod 'SwiftLint'

  target 'GSMapCamera_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
```

**Comment by segiddins** [comment]
Are you using a project generated by Xcode 10?

**Comment by dnkoutso** [comment]
This is probably about https://medium.com/xcblog/wwdc18-modern-tips-for-optimising-swift-build-time-in-xcode-10-a81de3a9be6d which talks about `xcfilelist`?

**Comment by segiddins** [comment]
Please share the project that caused this?

**Comment by dnkoutso** [comment]
@segiddins its simple, any Xcode 10 project that has a new script phase that has input file list or output file list shows this warning.

<img width="952" alt="screen_shot_2018-06-14_at_11_11_22_pm" src="https://user-images.githubusercontent.com/310370/41452821-4d4faffe-7028-11e8-845d-7277cb91c8f5.png">

If a user actually adds an entry to these then `pod install` crashes with "Xcodeproj Unknown Object version"

**Comment by segiddins** [comment]
Ah, so they did bump the object version! I'd made a new project with Xcode 10, but it was still on object version 50.

**Comment by zkf85** [comment]
I met the same problem, but i'm using XCode 9.4. so what should i do then?

**Comment by MikeFighting** [comment]
I have the same problem and i'm using Xcode9.3. And I cannot find the input file list

**Comment by AncAinu** [comment]
@dnkoutso that issue can happen even when the lists are empty in Xcode 10 UI.
I had to manually edit the project.pbxproj file and delete the concerned lines to be free of that issue.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1257961/43145191-b9276cd8-8f56-11e8-826b-c4b0af66d330.png">

**Comment by anhtuank7c** [comment]
@AncAinu Delete all of them will fix the issue. Thank you ^^!

**Comment by peruginni** [comment]
Or try `gem update xcodeproj`.

**Comment by Krusheuski** [comment]
Nice! @peruginni

**Comment by dsringari** [comment]
Thanks!!!! @peruginni

**Comment by divethru** [comment]
Thanks @peruginni

**Comment by cielojrdev** [comment]
Thanks! @peruginni

**Comment by tranhieubframgia** [comment]
Thanks !!!@peruginni 
It's correct answer

**Comment by luismgb** [comment]
> Or try `gem update xcodeproj`.

Thank you @peruginni !!! This solved the issue.

**Comment by YK-Unit** [comment]
I got the same issue when my CocoaPods Environment  is: 
```
- CocoaPods : 1.5.3
- Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
- Host : Mac OS X 10.14 
- Xcode : 10.0 (10A255)
``` 
---

**But now I find a solution, and it is working for me:**
1.  upgrade ruby: `brew install ruby `
2. uninstall cocoapods:  `sudo gem uninstall cocoapods`
3. reinstall  cocoapods: `sudo gem install -n /usr/local/bin cocoapods`
4. done

**now My CocoaPods Environment  is:**
```
- CocoaPods : 1.5.3
- Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
- Host : Mac OS X 10.14 
- Xcode : 10.0 (10A255)
```

**Comment by chetandobariya** [comment]
> gem update xcodeproj

this solve the issue :)

**Comment by drewpitchford** [comment]
@peruginni Thanks so much! I wasted an entire morning trying to figure why cocoa pods broke after altering a build phase

**Comment by olizh** [comment]
I followed the instruction in two lines from the threads: 
1. YK-Unit: 
Updated to the latest gem and pod version
2. peruginni: 
gem update xcodeproj: 

And problem solved! Thanks a lot!

**Comment by Ogiwara-CostlierRain464** [comment]
Thanks! @peruginni

**Comment by nmvictor** [comment]
Thanks @peruginni

**Comment by YK-Unit** [comment]
> I got the same issue when my CocoaPods Environment is:
> 
> ```
> - CocoaPods : 1.5.3
> - Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
> - Host : Mac OS X 10.14 
> - Xcode : 10.0 (10A255)
> ```
> **But now I find a solution, and it is working for me:**
> 
> 1. upgrade ruby: `brew install ruby `
> 2. uninstall cocoapods:  `sudo gem uninstall cocoapods`
> 3. reinstall  cocoapods: `sudo gem install -n /usr/local/bin cocoapods`
> 4. done
> 
> **now My CocoaPods Environment is:**
> 
> ```
> - CocoaPods : 1.5.3
> - Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
> - Host : Mac OS X 10.14 
> - Xcode : 10.0 (10A255)
> ```

@peruginni is right, `gem update xcodeproj` is the optimal solution.

**Comment by rdas-deloitte** [comment]
@peruginni thank you!

**Comment by yurovmd** [comment]
> @dnkoutso that issue can happen even when the lists are empty in Xcode 10 UI.
> I had to manually edit the project.pbxproj file and delete the concerned lines to be free of that issue.
> 
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/1257961/43145191-b9276cd8-8f56-11e8-826b-c4b0af66d330.png">

For me, it helped. Instead of @peruginni answer :)

**Comment by sustinel** [comment]
Thanks!!!! @peruginni

**Comment by nthrussell** [comment]
@peruginni you are a legend

**Comment by apchawan** [comment]
@peruginni thanks for `gem update xcodeproj`

**Comment by ZvOlCuOk2009** [comment]
I was helped by the decision @AncAinu

**Comment by EnderRule** [comment]
Thanks @peruginni

**Comment by mohanvydehi** [comment]
Thanks @peruginni

**Comment by jdleo** [comment]
thanks @peruginni

**Comment by ptejas26** [comment]
Thanks @peruginni you saved my hours

**Comment by nicolas-miari** [comment]
`gem update xcodeproj` Did nothing for me:

> Nothing to update

I have non-empty "Input Files" / "Output files" attributes because I'm also using **Carthage**, which requires a RunScript phase to copy the framework binaries.

**Comment by Coeur** [comment]
Note that the issue is fixed by a72f9de23c498097b80a5dfc0fdc1b709f4118c7, which means it's fixed in CocoaPods 1.6.0 beta 1 and newer.

**Comment by lawreyios** [comment]
> Or try `gem update xcodeproj`.

Top Solution!!!

**Comment by nicolas-miari** [comment]
@Coeur 
Thank you; it turns out the Gemfile in my project directory was locking me to xcodeproj version 1.5.6. Once I changed it and was able to update to 1.7.0, the issue was resolved. I didn't update Cocoapods though.

**Comment by usman1372** [comment]
Thanks @peruginni

**Comment by marouanelkhebir** [comment]
Thanks @peruginni

**Comment by Leonif** [comment]
> > I got the same issue when my CocoaPods Environment is:
> > ```
> > - CocoaPods : 1.5.3
> > - Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
> > - Host : Mac OS X 10.14 
> > - Xcode : 10.0 (10A255)
> > ```
> > **But now I find a solution, and it is working for me:**
> > 
> > 1. upgrade ruby: `brew install ruby `
> > 2. uninstall cocoapods:  `sudo gem uninstall cocoapods`
> > 3. reinstall  cocoapods: `sudo gem install -n /usr/local/bin cocoapods`
> > 4. done
> > 
> > **now My CocoaPods Environment is:**
> > ```
> > - CocoaPods : 1.5.3
> > - Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
> > - Host : Mac OS X 10.14 
> > - Xcode : 10.0 (10A255)
> > ```
> 
> @peruginni is right, `gem update xcodeproj` is the optimal solution.

How to know CocoaPods Environment?

**Comment by Coeur** [comment]
@Leonif : `pod --version` or `gem which cocoapods`
As written above, it's fixed since version 1.6.0+. So just do `gem update cocoapods` to get the latest stable version of cocoapods.

**Comment by Leonif** [comment]
> * [x]  I've read and understood the [_CONTRIBUTING_ guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
> 
> # Report
> ## What did you do?
> Run `pod install`
> 
> ## What did you expect to happen?
> Install all pod dependencies correctly.
> 
> ## What happened instead?
> Got error: "Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa"
> 
> ## CocoaPods Environment
> ### Stack
> ```
>    CocoaPods : 1.5.3
>         Ruby : ruby 2.3.6p384 (2017-12-14 revision 61254) [universal.x86_64-darwin18]
>     RubyGems : 2.5.2.2
>         Host : Mac OS X 10.14 (18A293u)
>        Xcode : 9.4 (9F1027a)
>          Git : git version 2.15.1 (Apple Git-101)
> Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
> Repositories : GSPods - ssh://git@git.geo4.pro:49384/ios/GSPods.git @ b6f6bbe0011db70e436918e8c3b6bc889150a0c7
>                master - https://github.com/CocoaPods/Specs.git @ 66d002cdf4467b318684487888e984abe72e45d1
> ```
> Also using Xcode 10 beta
> 
> ### Installation Source
> ```
> Executable Path: /usr/local/bin/pod
> ```
> ### Plugins
> ```
> cocoapods-deintegrate : 1.0.2
> cocoapods-plugins     : 1.0.0
> cocoapods-search      : 1.0.0
> cocoapods-stats       : 1.0.0
> cocoapods-trunk       : 1.3.0
> cocoapods-try         : 1.1.0
> ```
> ### Podfile
> ```ruby
> use_frameworks!
> 
> target 'GSMapCamera_Example' do
>   pod 'GSMapCamera', :path => '../'
>   pod 'SwiftLint'
> 
>   target 'GSMapCamera_Tests' do
>     inherit! :search_paths
> 
>     pod 'Quick', '~> 1.2.0'
>     pod 'Nimble', '~> 7.0.2'
>   end
> end
> ```

open project file, find **inputFileListPaths** and **outputFileListPaths** and remove them

**Comment by MataHu** [comment]
> Environment



> > I got the same issue when my CocoaPods Environment is:
> > ```
> > - CocoaPods : 1.5.3
> > - Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
> > - Host : Mac OS X 10.14 
> > - Xcode : 10.0 (10A255)
> > ```
> > **But now I find a solution, and it is working for me:**
> > 
> > 1. upgrade ruby: `brew install ruby `
> > 2. uninstall cocoapods:  `sudo gem uninstall cocoapods`
> > 3. reinstall  cocoapods: `sudo gem install -n /usr/local/bin cocoapods`
> > 4. done
> > 
> > **now My CocoaPods Environment is:**
> > ```
> > - CocoaPods : 1.5.3
> > - Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
> > - Host : Mac OS X 10.14 
> > - Xcode : 10.0 (10A255)
> > ```
> 
> @peruginni is right, `gem update xcodeproj` is the optimal solution.

**Comment by superkam** [comment]
@peruginni Thank you so much! You are my HERO~

**Comment by samma89** [comment]
> @dnkoutso that issue can happen even when the lists are empty in Xcode 10 UI.
> I had to manually edit the project.pbxproj file and delete the concerned lines to be free of that issue.
> 
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/1257961/43145191-b9276cd8-8f56-11e8-826b-c4b0af66d330.png">

Thank you! A life savior. I was going to do a fresh installation of CocoaPods. Thanks

**Comment by falipate** [comment]
I've tried all the suggested solutions and my issue is still present does anyone know what I'm missing?

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f7712ba0f57898b72eb19c7bfaebda092e89ca03
               sentia - git@github.com:Sentia/Sentia-Repository.git @ 4e74ad3dd0c3e1075dcd3dad5780963c87e25ba7
               sentia-1 - git@github.com:Sentia/iOS-Cocoapods-Repository.git @ 7d505112f28acd8bc64ddae285a9fca125f06d53
               twilio - https://github.com/twilio/cocoapod-specs @ 9bf659ed7246ba34625b81754031fbd5ac20fe68
```

**Comment by Coeur** [comment]
@falipate the issue described in this thread was for Xcode 10 beta and was resolved a year ago.
Please open a new issue and share a project that caused this issue, as advised by segiddins above.
And specify in your new issue if you have installed Xcode 11 beta and if the Pull Request https://github.com/CocoaPods/Xcodeproj/pull/687 is able to solve your issue or not.

**Comment by darhonbek** [comment]
Oka thank you @AncAinu 🙌

**Comment by kazamihayato** [comment]
Thanks @peruginni

**Comment by IbraD00** [comment]
> Or try `gem update xcodeproj`.

Thanks @peruginni

**Comment by bmvdeveloper** [comment]
Updating cocoapods fixed this issue for our team:

`sudo gem install cocoapods`

Cheers!

**Comment by mtaimoor123** [comment]
The think worked for me is `sudo xcode-select --reset`
Then `brew install cocoapods`
Thanks all
