### ISSUE TITLE
The 'Pods-CommonPods-ProjectName' target has libraries with conflicting names: libcrypto.a and libssl.a 

### ISSUE THREAD

**Issue by hengyizhangcn** [CocoaPods/CocoaPods#7838]
Two git repos are used in the podfile, like A and B, and they are all use libcrypto.a and libssl.a in their own repo. When I type the command "pod update --no-repo-update", in the last line of the outputs, it shows "The 'Pods-CommonPods-ProjectName' target has libraries with conflicting names: libcrypto.a and libssl.a", how I can do to avoid or solve this problem?
(Tip: pod version is 1.5.3)

The sample project repo https://github.com/hengyizhangcn/PodConflictDemo.git.
Thanks!

@dnkoutso , it's an old issue #6502 , but the problem is aways exists in the newest CocoaPods! So I open a new one to track!

**Comment by dnkoutso** [comment]
@hengyizhangcn AlipayCopy and EZOpenSDKCopy both use `libcrypto.ssl` and `libssl.a`.

https://github.com/WildDylanOpenCourse/EZOpenSDKCopy/blob/master/EZOpenSDKCopy.podspec#L34

It seems you own this podspec? so maybe remove those as they conflict.

**Comment by dnkoutso** [comment]
The message could be enhanced though.

**Comment by hengyizhangcn** [comment]
@dnkoutso , this is just the demo! In the real project, the pods like the issue described are belong to different podspecs! Ah ha, I don't own the podspec, so they can't imported by Cocoapods together!

**Comment by hengyizhangcn** [comment]
Even though A can dragged into the main project and B imported by Cocoapods, the management of A is inconvenient!

**Comment by dnkoutso** [comment]
@hengyizhangcn I am sorry I dont think much can be done here.

**Comment by dnkoutso** [comment]
@hengyizhangcn going to mark this as a small enhancement to enhance the error message to explicitly show the pods that link the same dependency.

**Comment by hengyizhangcn** [comment]
then, this issue can be closed?
