### ISSUE TITLE
Can't install SnapKit pod

### ISSUE THREAD

**Issue by bhartsb** [CocoaPods/CocoaPods#7839]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Installed cocoapods and updated pod file to include SnapKit
ℹ ran pod install
 

ℹ I expected SnapKit to be installed.

## What happened instead?

ℹ [![!] The `DoorDashLiteMVC_PTests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-DoorDashLiteMVC_PTests/Pods-DoorDashLiteMVC_PTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

ℹ I went in and set $(inherited)  as instructed ....doesn't make any difference.

## CocoaPods Environment

ℹ ### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ be30f7196adfa0aefe1e28bcc098ec82f7e463de
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoorDashLiteMVC_P' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoorDashLiteMVC_P

  target 'DoorDashLiteMVC_PTests' do
    inherit! :search_paths
    
    pod 'SnapKit', '~> 4.0.0'
    
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Works for me.

![screen shot 2018-06-15 at 6 08 54 pm](https://user-images.githubusercontent.com/310370/41494379-2fce9766-70c7-11e8-9046-75b2be31967d.png)

It seems you are receiving a warning not an error.

@bhartsb sorry I am going to preemptively close this and re-open if we figure this is an actual issue.

**Comment by bhartsb** [comment]
I made the $(inherited) setting that the warning recommends and still get
the warning.

When I try to build my project and import SnapKit it can't find the
module.  The SnapKit frameworks shows up as dimmed in Xcode.

Any ideas?  At the very least the warning should have gone away.

**Comment by bhartsb** [comment]
I created a new project and things seemed to work in so far as SnapKit.
Not sure why it failed on the other project as it was a new project also.
Only difference is that the first was a programmatic iOS program versus
using storyboard.

**Comment by dnkoutso** [comment]
Shouldn't matter seems like you might be changing the wrong target.

**Comment by bhartsb** [comment]
It is finicky.  The only thing I noticed was that when I put import SnapKit
before adding any code that used SnapKit it complained, but adding code
that used SnapKit and then adding the import SnapKit seemed to work.  It
might be that or some strangeness with Xcode.  I haven't gone back to
double verify what I noticed.
