### ISSUE TITLE
Why the folder in the library are missing ! what happened ？ 

### ISSUE THREAD

**Issue by chenliangloveyou** [CocoaPods/CocoaPods#7840]
Why the folder in the library are missing !
i have try many times , and have two computer .

 # My project local : 
<img width="292" alt="2018-06-17 12 22 58" src="https://user-images.githubusercontent.com/10606555/41500575-eb94bdfe-71c6-11e8-9ef6-a08250015dee.png">

 # cocoapods file:
<img width="468" alt="2018-06-17 12 38 34" src="https://user-images.githubusercontent.com/10606555/41500578-f98a4a14-71c6-11e8-9599-0aaa837a9203.png">

**Comment by dnkoutso** [comment]
Have no idea. Please upload a sample app and its best to ask these questions in StackOverflow under `cocoapods` tag.

We get too many issues open and its get harder and harder to manage.

I am going to preemptively close this issue and re-open once a sample app is uploaded and it can clearly show an issue with CocoaPods integration.

**Comment by amorde** [comment]
@chenliangloveyou The folder structure is only preserved for development pods - this is on purpose, as there is a performance hit for recreating the structure every time `pod install` is run. The current behavior is faster and also makes the Pods project simpler

**Comment by chenliangloveyou** [comment]
@amorde No folder, I feel very pain.I think it's a very bad change.
