### ISSUE TITLE
No email received for 'pod trunk register'

### ISSUE THREAD

**Issue by hsoehalim** [CocoaPods/CocoaPods#7852]
Hi There,

I've ran this several times: pod trunk register harry@answerdash.com 'Harry Soehalim'
and I haven't received any emails so far. Can you help?

Thanks,
Harry

**Comment by dnkoutso** [comment]
@hsoehalim thanks for the inquiry can I please ask you to file this into https://github.com/CocoaPods/cocoapods-trunk repo instead?

In the meantime we will also check it out.

**Comment by hsoehalim** [comment]
sure, it's done: https://github.com/CocoaPods/cocoapods-trunk/issues/110

Thanks,
Harry

**Comment by dnkoutso** [comment]
thank you!
