### ISSUE TITLE
Alphabetic version will get a error version

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7859]
The Podfile:
```
    pod 'ASDK', '0.8.4-abc'
```
One day, there a new version be added into same spec repo: `0.8.4.abc`. They're crazy.
Now, there are two versions:
```
/Users/whirlwind/.cocoapods/repos/private-specs/ASDK/0.8.4.abc/ASDK.podspec
/Users/whirlwind/.cocoapods/repos/private-specs/ASDK/0.8.4-abc/ASDK.podspec
```
run `pod install`, the Podfile.lock will be changed:
```
PODS:
  - ASDK (0.8.4.abc)

DEPENDENCIES:
  - ASDK (= 0.8.4-abc)
```
I don't know why it is. and I test it in CocoaPods 1.3.1 and master branch, I get same result.

**Comment by Whirlwind** [comment]
The Podfile require `pod 'ASDK', '0.8.4-abc'`. But we get the `0.8.4.abc`. They are not different versions.

**Comment by dnkoutso** [comment]
One has a `-` the other `.` I believe this is how sem ver is preferred?

**Comment by Whirlwind** [comment]
I write the version in the podfile and the podfile.lock have a different version.

**Comment by amorde** [comment]
@Whirlwind did you happen to also update the podspec to include `s.version = '0.8.4-abc'`?

**Comment by Whirlwind** [comment]
The podspec (0.8.4.abc): 
```
Pod::Spec.new do |s|
    s.name    = 'ASDK'
    s.version = "0.8.4.abc"
```

The podspec (0.8.4-abc):
```
Pod::Spec.new do |s|
    s.name    = 'ASDK'
    s.version = "0.8.4-abc"
```

The specs should be right.
