### ISSUE TITLE
Cocoapods without editing main project or creating workspace

### ISSUE THREAD

**Issue by pablonosh** [CocoaPods/CocoaPods#7860]
I'd like to use cocoapods as a package manager, but not have it edit my project or workspace. 

Similar to carthage, but keeping the cocoapods plugins and build process.

**Comment by dnkoutso** [comment]
@pablonosh I am not sure I understand 100% but CocoaPods supports two ways:

a) Full integration upon which your project must be edited to some extend in order for CocoaPods to work
b) Skip integration (just dependency resolution and downloading of dependencies). This can be done via:
```ruby
install! 'cocoapods', :integrate_targets => false
```
If you choose b) I am uncertain if plugins will run and you will have to link the dependencies yourself manually.

Going to close this for now. Will re-open if we can figure out an enhancement of bug.

**Comment by pablonosh** [comment]
cool I didn't know about skip integration, thanks will check it out.

**Comment by dnkoutso** [comment]
excellent! let me know if something is off we can re-open this and fix it.

**Comment by pablonosh** [comment]
So I've done a skipped integration build, and I have some subfolders with my dependencies in it.

It'd be cool the pods command, generated a big .a static library with all the dependencies setup in it. So then you just have to link one library and it all just works.

Any hints?

**Comment by dnkoutso** [comment]
This should be fairly easy to write it yourself. There are no plans to offer it now from within the library.

**Comment by pablonosh** [comment]
I was hoping it'd be relatively easy, but I'm a bit nervous of missing some of the required config - if any docs come to mind I'd appreciate any pointers. Thanks all you've been really helpful
