### ISSUE TITLE
I have pushed a new version and it's not showing up

### ISSUE THREAD

**Issue by hsoehalim** [CocoaPods/CocoaPods#7861]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
pod trunk push AnswerDashSDK.podspec

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
the `pod trunk push` was successful, but i didn't the see the latest version on:
http://cocoadocs.org/docsets/AnswerDashSDK/0.4.0

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
I'm getting 404 not found

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ eafdb826bba2cd980a3064d54801f535c6929989
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.
I'm afraid this is not quite possible. Our company repo is private at the moment.

**Comment by orta** [comment]
[CocoaDocs was deprecated over a year ago](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/) and no new docs are generated.

**Comment by dnkoutso** [comment]
https://cocoapods.org/pods/AnswerDashSDK

**Comment by hsoehalim** [comment]
Ah ok, thanks for the info. Btw, how do i update the `CHANGELOG`? It still doesn't have the latest update.
