### ISSUE TITLE
Unable to add cocoapod dependancy in Custom framework - Swift

### ISSUE THREAD

**Issue by priyankamistry09** [CocoaPods/CocoaPods#7869]
# Report

## What did you do?

ℹ  I have created podspec file for my custom Framework as:
```
Pod::Spec.new do |s|
  s.platform = :ios
  s.ios.deployment_target = '10.0'
  s.name = "CustomFramework"
  s.summary = "CustomFramework have all the wrapper API."
  s.requires_arc = true
  s.version = "1.0.0"
  s.license = { :type => "MIT", :file => "LICENSE" }
  s.author = { "My Name" => "my.name@xyz.com" }
  s.homepage = "URL_LINK"
  s.source = { :git => "github_url_link", :tag => "#{s.version}"}

      s.dependency 'RealmSwift', '3.5.0'
      s.dependency 'Firebase/Core', '5.1.0'
      s.dependency 'Firebase/Firestore', '5.1.0'
      s.dependency 'PubNub','4.7.5'

  s.source_files = "CustomFramework/**/*.{swift}"
end
```

I am adding this Custom framework pod in the sample project as:
```
target 'customFrameworkSample' do
  use_frameworks!
  pod 'customFramework' , :path => 'Local_Path_for_customFramework.podspec'
  
  target 'customFrameworkSampleTests' do
    use_frameworks!
      pod 'customFramework' , :path => 'Local_Path_for_customFramework.podspec'
  end
end
```

## What did you expect to happen?

ℹ Pod should install properly and When sample project is Build, it should Run and not throw any error. 

## What happened instead?

ℹ In the Sample project, error is thrown while importing firbase, RealmSwift files, etc.. in CustomFramework files.
![screen shot 2018-06-22 at 3 24 02 pm](https://user-images.githubusercontent.com/13692458/41770696-8d22abb4-7630-11e8-967b-f08c80455f0f.png)

## CocoaPods Environment

ℹ cocoapod : 1.5.3

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
