### ISSUE TITLE
[v1.5.3] Podspec compiler_flags doesn't apply during pod spec lint

### ISSUE THREAD

**Issue by GeekTree0101** [CocoaPods/CocoaPods#7873]
```ruby
Pod::Spec.new do |s|
  
  ....  blah blah ......

  s.compiler_flags = ['ONLY_ACTIVE_ARCH=YES']
end
```
I setup compiler flags but  compiler_flags doesn't apply during `pod spec lint`

```
-> Pod installation complete! There is 1 dependency from the Podfile and 7 total pods installed.
   Building with `xcodebuild`. 
    $ /usr/bin/xcodebuild clean build -workspace /var/folders/gd/~~dir`~~/App.xcworkspace -scheme
    App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=IDXXXXX-XXX-XXXXXXXX
    Build settings from command line:
        CODE_SIGN_IDENTITY = -
        SDKROOT = iphonesimulator11.4
    
    === CLEAN TARGET PINOperation OF PROJECT Pods WITH CONFIGURATION Release ===

```

**Comment by dnkoutso** [comment]
A few things.

On a test library I have it seems this setting correctly is added to compiler flags. See screenshot below:
<img width="858" alt="screen_shot_2018-06-24_at_9_40_12_pm" src="https://user-images.githubusercontent.com/310370/41830681-471fabd0-77f7-11e8-9790-32ab608ff8a9.png">

Having said that:

a) `pod spec lint` clones the tag you have in your podspec so it's possible the SHA you are pointing to is not the latest one. You can try `pod lib lint` for quick check.
b) Compilation fails with your setting like this you probably want:
```ruby
  s.pod_target_xcconfig = {
    'ONLY_ACTIVE_ARCH' => 'YES'
```

@GeekTree0101 I am going to preemptively close issue. I *will* re-open it if your issue persists and it is an actual issue with CocoaPods. A sample project always helps. 

It is also best to ask these questions in StackOverflow under `cocoapods` tag.

**Comment by GeekTree0101** [comment]
Thank you!
