### ISSUE TITLE
dyld: Library not loaded: @rpath/CocoaLumberjack.framework/CocoaLumberjack

### ISSUE THREAD

**Issue by jimUpdate** [CocoaPods/CocoaPods#7880]
===========my podfile===========

`# Uncomment the next line to define a global platform for your project

platform:ios, '10.0'
use_frameworks!
inhibit_all_warnings!#忽略警告
workspace 'ipms.xcworkspace'

def common_pods
    pod 'Moya/RxSwift','8.0.5'
    pod 'RxSwift', '3.6.1'
    pod 'RxCocoa', '3.6.1'
    pod 'SwiftyJSON', '3.1.4'
    pod 'Toaster', '2.0.4'#吐司
    pod 'SnapKit', '3.2.0'#代码添加约束
    pod 'MJRefresh', '3.1.15'
    pod 'HGPlaceholders', '0.2.3'
    pod 'Kingfisher', '4.3.0'#加载图片
    pod 'HTMLString', '3.0.0'#富文本处理工具
    
    pod 'JRDB', '2.1.1'#数据库
    pod 'SwipeMenuViewController', '2.0.2'#tab切换
    pod 'FSCalendar', '2.7.9'#值班日历
    pod 'SwiftEventBus', '2.1.2'
    pod 'SVProgressHUD', '2.2.5'#弹窗
    pod 'NextGrowingTextView', '1.1.0'#多文本输入
    pod 'SLExpandableTableView', '1.3.1'#可折叠的UItableView
    pod 'TZImagePickerController', '1.9.6'#图片选择框架
    pod 'SearchEmojiOnString', '~> 1.0'#表情校验[不固定版本,因为需要包含尽可能多的表情]
    pod 'IQKeyboardManagerSwift', '5.0.8'
    
    pod 'Bugly'#bugly异常上报
    
    pod 'MGJRouter', '~>0.9.0'
end

common_pods

target 'ipms_xinxike' do
    project "Xinxike"
end

target 'Router' do
    project "Modules/Router/Router"
end

target 'Meeting' do
    project "Modules/Meeting/Meeting"
end

target 'ReqForm' do
    project "Modules/ReqForm/ReqForm"
end

target 'JobForm' do
    project "Modules/JobForm/JobForm"
end

target 'SignIn' do
    project "Modules/SignIn/SignIn"
end

target 'Datum' do
    project "Modules/Datum/Datum"
end

target 'Duty' do
    project "Modules/Duty/Duty"
end

target 'Base' do
    project "Modules/Base/Base"
    pod 'CocoaLumberjack/Swift'#Log收集器用于平时debug
    
end

target 'WordPress' do
    project "Modules/WordPress/WordPress"
    pod 'CocoaLumberjack'#WordPress
    pod 'NSObject-SafeExpectations','0.0.2'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['ARCHS'] = 'i386 x86_64 arm7s arm7 arm64'
        end
    end
end
`

===========rely relationship========

xinxike
Duty Datum ReqForm JobForm Meeting SignIn
Base
Router WordPress

===========base info===========

zhouzhoujiedeMacBook-Pro:2.2.0 jimy$ pod --version
1.4.0.beta.1

===========error===========

dyld: Library not loaded: @rpath/CocoaLumberjack.framework/CocoaLumberjack
  Referenced from: /Users/zhouzhoujie/Library/Developer/Xcode/DerivedData/ipms-cyjqymqhtdkktxdhqymzzfgwowbp/Build/Products/Debug-iphonesimulator/Base.framework/Base
  Reason: image not found

===========question===========
how to fix my problem

**Comment by dnkoutso** [comment]
Hey there, this looks like a great example of a question that you should ask on StackOverflow - there is an active tag `cocoapods` where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

Please also upload a sample app demonstrating the issue. If we derive this is actually a CocoaPods library issue problem I *will* re-open this.

**Comment by dnkoutso** [comment]
You should also upgrade to 1.5.3 version and check the runtime paths in your app project.

**Comment by jimUpdate** [comment]
Thanks a lot, I will update my Demo Later, then copy the problem to StackOverflow with the TAG `cocoapods`

**Comment by CoderWeiLee** [comment]
> Thanks a lot, I will update my Demo Later, then copy the problem to StackOverflow with the TAG `cocoapods`

Hey, man, can you tell me how to solve it finally, because I'm in the same trouble
