### ISSUE TITLE
Is it necessary to dependency  activesupport <5 

### ISSUE THREAD

**Issue by zhiguangqiao** [CocoaPods/CocoaPods#7885]
Is it necessary to dependency  activesupport <5 
I use cocoapods in rails 5.1 project , bundle install error

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    cocoapods (~> 1.3.1) was resolved to 1.3.1, which depends on
      activesupport (< 5, >= 4.0.2)

    rails (~> 5.1.0) was resolved to 5.1.0, which depends on
      activesupport (= 5.1.0)

**Comment by orta** [comment]
CocoaPods supports Ruby 2.0, which activesupport > 5 does not I'm afraid.

**Comment by feelepxyz** [comment]
@orta any thoughts on dropping support for Ruby 2.0 now that Mojave is out and we have a full cycle of Mac OS releases with Ruby 2.3+ support? 🤠

We're keen to add support to automatically update Podfiles in [Dependabot](https://dependabot.com/) which uses Rails 5.
Original comment raising this: https://github.com/CocoaPods/CocoaPods/pull/5602#issuecomment-303251393

**Comment by amorde** [comment]
@feelepxyz do you have a link or other info which specifies which version of Ruby is included with each version of macOS?

**Comment by feelepxyz** [comment]
@amorde I can't seem to find any official info but found the following reports:

10.12 Sierra ships with Ruby 2.0
- Released September 20, 2016
- https://futureshare.lip6.fr/macOS_Sierra.html

10.13 High Sierra ships with Ruby 2.3.3
- Released September 25, 2017
- https://futureshare.lip6.fr/macOS_High_Sierra.html
- https://apple.stackexchange.com/a/257629

10.14 Mojave ships with Ruby 2.3.7
- Released September 24, 2018
- https://applech2.com/archives/macos-mojave-new-features-ruby-php-python.html

**Comment by franklinyu** [comment]
I don't think Apple officially announce this anywhere; another citation for Ruby version (that agree with what @feelepxyz said) is https://apple.stackexchange.com/questions/257627/ruby-version-on-macos-sierra

**Comment by segiddins** [comment]
That sounds right? Also cc @DanToml

**Comment by orta** [comment]
I feel like it was both Xcode and macOS

**Comment by amorde** [comment]
I don't think this is documented anywhere, and so I wouldn't be opposed to re-evaluating it. But would need to investigate the impact of dropping support for 2.0.0 - my guess is that a significant amount of users are still using 2.0.0 but I could be wrong

**Comment by franklinyu** [comment]
How about rolling this out? Show warning to user if `pod` is called with Ruby 2.0?

**Comment by segiddins** [comment]
We can still support 2.0.0 (and we must until CocoaPods 2.0), but we can probably stop bending over backwards to make its experience as good as possible. So I’m fine just making the activesupport dependency >4,<6 personally.

**Comment by FranklinYu** [comment]
@segiddins Any progress? If I understand correctly, the current plan is to write code compatible with both ActiveSupport 4.x and 5.x?

And shall we re-open this issue if this is the plan?

**Comment by FranklinYu** [comment]
macOS High Sierra (10.13) comes with Ruby 2.3. Now that Catalina is released, Apple isn’t expected to support Sierra (10.12) any more. Is there any plan to upgrade ActiveSupport? Or at least, any plan to deprecate Ruby 2.1 or below?

**Comment by gsbernstein** [comment]
Is this still an issue? I'd love to be able to use Dependabot with CocoaPods!

**Comment by amorde** [comment]
Yes, we are currently in a beta period for 1.9 so this likely won't change until after 1.9 is released

**Comment by rogerluan** [comment]
Just to officialize the conclusion of this issue, cocoapods dependency activesupport is `> 5.0 && < 6.0` https://github.com/CocoaPods/CocoaPods/blob/master/Gemfile#L41 already (since mid feb or so).

This unblocks Dependabot from moving forward 👍
