### ISSUE TITLE
clean project needed everytime when make changes in development pods

### ISSUE THREAD

**Issue by Minghao2017** [CocoaPods/CocoaPods#7887]
I generate my pod using '''pod lib create'''. When I make some changes of my code in the development pods I have to clean my project otherwise It can't take effect in the generated example target. I seems to be a problem. Could some one give a hand?

**Comment by ataranlen** [comment]
Have you tried reverting to the legacy build system?

File > Workspace Settings > Build System: change it to 'Legacy build system'
<img width="535" alt="screen shot 2018-06-27 at 9 28 47 am" src="https://user-images.githubusercontent.com/1933566/41980617-877ef6d0-79ec-11e8-9743-81d91b6b50bc.png">

**Comment by dnkoutso** [comment]
Would prefer to see a sample app here. Also these kind of questions are best asked in StackOverflow under `cocoapods` tag.

We cannot easily diagnose the problem here with the information given.

**Comment by Minghao2017** [comment]
@ataranlen You saved my life, thank you so much. Yes, I was using XCode 10 beta too.

**Comment by dnkoutso** [comment]
Going to close this. At least as it looks like right now might be an Xcode 10 thing.
