### ISSUE TITLE
Avoid compiling pods project

### ISSUE THREAD

**Issue by felixsolorzano** [CocoaPods/CocoaPods#7889]
Every time I run the app or build the app project the pods project compile its targets, is it possible to avoid that? Compile time takes so much time because of it

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by dnkoutso** [comment]
What @orta said ^ but a quick note:

Those are your pod dependencies (libraries) that you have to build because you requested them in your podfile. You can pre-compile them yourself but if you want to be able to use them you have to compile them.

**Comment by felixsolorzano** [comment]
Yeah, but is really necessary to compile them every time?, They won't be modified.

**Comment by dnkoutso** [comment]
Try https://bundler.io/v1.12/git.html and pin to the latest master version.
