### ISSUE TITLE
Can not use local sources as pod

### ISSUE THREAD

**Issue by alexlee002** [CocoaPods/CocoaPods#7890]
# Report

## What did you do?
I want to create a private pod in my project, the source files are located in  a local subdirectory.
I add this pod in my Podfile:
```
pod 'myPodName', :path => 'path/to/mypod'
```
And, in directory `path/to/mypod` there are my source files and `myPodName.podspec`.
In `myPodName.podspec` I specify my sources locate:
```
alloy.source        = { :path => "." }
```
Then, I run `pod install` and I seems work.
In the Pods project there is a new folder: `Development Pods` with my pod in it.  But no source file is included!!!

## What did you expect to happen?
How can I create a pod with source files in local directory?  If I add a pod in Podfile like this: `pod 'mypod', :path => 'local_path'`,  what' s the correct value of the `source` key in `local_path/mypod.podspec`?

## CocoaPods Environment
pod version: 1.5.3

**Comment by dnkoutso** [comment]
path is not supported in a podspec. second when using `:path` in the podfile then the `s.source` is not being downloaded or cloned so instead all of the `s.source_files` are picked up relative to where the podspec is placed.

Please also use StackOverflow under `cocoapods` tag to ask these questions. Currently as it seems this does not appear a CocoaPods library issue.

@alexlee002 I am going to preemptively close and I *will* re-open if you can show this is a bug in the library or make a good case for an enhancement.

**Comment by segiddins** [comment]
Have you specified source_files in the podspec?

**Comment by alexlee002** [comment]
@dnkoutso  this could work in Cocoapods v1.0 and earlier。But failed after I upgrade my cocoapods.
I don't need to download any code,  the code is in my local disk.  I just want to make it as a private pod.

@segiddins YES,  I did!

**Comment by alexlee002** [comment]
@dnkoutso and @segiddins ：

Sorry, it's work, it's not cocoapods' bug.  It's Xcode's bug! (Xcode v9.4.1 Can not automatically refresh the workspace when project.pbxproj was changed by pod install)
