### ISSUE TITLE
[!] Unable to add a source with url....

### ISSUE THREAD

**Issue by DreamScy** [CocoaPods/CocoaPods#7892]
localhost:CloudLearning_Main scy$ pod update
Update all pods
Updating local specs repositories
Cloning spec repo `speiyou-xes_cloudlearning_online-xes_cloudlearning_online_ios_privatepods` from `https://git.speiyou.cn/xes_cloudlearning_online/xes_cloudlearning_online_ios_privatepods.git`
[!] Unable to add a source with url `https://git.speiyou.cn/xes_cloudlearning_online/xes_cloudlearning_online_ios_privatepods.git` named `speiyou-xes_cloudlearning_online-xes_cloudlearning_online_ios_privatepods`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

please help

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
