### ISSUE TITLE
podspec dependency is not available from framework

### ISSUE THREAD

**Issue by maniacs-engineerica** [CocoaPods/CocoaPods#7893]
Hi, sorry if this is not the place where I should have asked this question.

I created a local framework which depends on AFNetworking, so I added to the podspec this line:

s.dependency 	'AFNetworking'

Then I link the framework from my project using pod install and it was built perfect. The problem is that AFNetworking as available from the project, but not from the framework.

Thanks!

**Comment by maniacs-engineerica** [comment]
Sorry, based on other answers I shouldn't have asked here.

**Comment by maniacs-engineerica** [comment]
Hi, I am opening this issue because I can't find enough documentation to answer my question. I only read 'dependency' is using for adding..."Any dependency on other Pods or to a ‘sub-specification’.". I am not sure if the dependency must be available from the framework or only from the project. Thanks.

**Comment by dnkoutso** [comment]
If you need your pod to be able to import heads from another dependency then you add it to your podspec. Otherwise you an add it to the Podfile.

This is best asked in StackOverflow under `cocoapods` tag. Given its current state this does not seem an issue with the CocoaPods library.
