### ISSUE TITLE
Internal Error when submitting podspec

### ISSUE THREAD

**Issue by shawnkc** [CocoaPods/CocoaPods#7899]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod trunk push --verbose AdColony.podspec`

## What did you expect to happen?

Update the master podspec repo.

## What happened instead?

Internal error occurred:

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.5.3\r\nAuthorization: Token 29b3beb5fa91e4c4d26f538ac7b71202\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 1497\r\n\r\n"
<- "{\"name\":\"AdColony\",\"version\":\"3.3.5\",\"summary\":\"AdColony delivers high-definition Instant-Play video ads that can be displayed anywhere within your application.\",\"description\":\"AdColony delivers high-definition Instant-Play video ads that can be displayed anywhere within your application. AdColony also contains V4VC, a secure system for rewarding users of your app with virtual currency upon the completion of video plays.\",\"homepage\":\"http://adcolony.com\",\"license\":{\"type\":\"Commercial\",\"text\":\"You must accept the terms and conditions on the AdColony website by registering in order to legally use the AdColony SDK. U.S. based companies will need to complete the W-9 form and send it to us, as well as complete the section on payment information on clients.adcolony.com, before publisher payments can be issued.\"},\"authors\":{\"AdColony Support\":\"support@adcolony.com\"},\"source\":{\"git\":\"https://github.com/AdColony/AdColony-iOS-SDK-3.git\",\"tag\":\"v3.3.5\"},\"platforms\":{\"ios\":\"6.0\"},\"requires_arc\":true,\"public_header_files\":\"AdColony.framework/**/*.h\",\"source_files\":\"AdColony.framework/**/*.h\",\"vendored_frameworks\":\"AdColony.framework\",\"preserve_paths\":\"AdColony.framework\",\"libraries\":\"z\",\"frameworks\":[\"AdColony\",\"AdSupport\",\"AudioToolbox\",\"AVFoundation\",\"CoreMedia\",\"CoreTelephony\",\"JavaScriptCore\",\"MessageUI\",\"MobileCoreServices\",\"SystemConfiguration\"],\"weak_frameworks\":[\"Social\",\"StoreKit\",\"WatchConnectivity\",\"WebKit\"],\"xcconfig\":{\"FRAMEWORK_SEARCH_PATHS\":\"\\\"$(PODS_ROOT)/AdColony\\\"\"}}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Fri, 29 Jun 2018 19:27:33 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /Users/shawn/.rbenv/versions/2.3.0/lib
Repositories : deltadna - https://github.com/deltaDNA/CocoaPods @ 15774cbadf54cbf2522d9f6a18a7ad1efd85a698
               master - https://github.com/CocoaPods/Specs.git @ 4d7192eb301979a4bba5e85a943376eabae10ce4
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
hello @shawnkc thanks for the report, can I please ask you to file it instead on https://github.com/CocoaPods/trunk.cocoapods.org?

**Comment by shawnkc** [comment]
Done, thanks.
