### ISSUE TITLE
Multiple projects in a Workspace?

### ISSUE THREAD

**Issue by bonkowski** [CocoaPods/CocoaPods#79]
Hi.

I want to use CocoaPods on our new project, but I think I'm missing something. I want to have one Workspace containing a couple of projects, but it seems that CocoaPods does not support this. 

Whenever I run pod install AppName.xcodeproj it generates a new workspace called AppName.xcworkspace and tells  me to use this from now on. But what about the existing workspace? And how can I add additional CocoaPods based project to the same workspace?

Thanks

**Comment by andrew8712** [comment]
Can anyone provide a valid working podfile for two-project workspace? All of the above are not working.

**Comment by andrew8712** [comment]
Okay, got this working with the following pod file:

    workspace 'Projects.xcworkspace'
    platform :ios, '8.0'
    
    use_frameworks!
    
    # ignore all warnings from all pods
    inhibit_all_warnings!
    
    def shared_pods
        # all the pods go here
        # pod 'Parse' etc.
    end
    
    xcodeproj 'Project1.xcodeproj'
    xcodeproj 'Project2/Project2.xcodeproj'
    
    target :Project1 do
      xcodeproj 'Project1'
      shared_pods
    end
    
    target :Project2 do
      xcodeproj 'Project2/Project2.xcodeproj'
      shared_pods
    end

**Comment by fatuhoku** [comment]
@andrew8712 I've also managed to make a minimal demo project for this.

**Comment by segiddins** [comment]
Please don't comment on three year old closed issues.

**Comment by andrew8712** [comment]
@segiddins why not? I googled about this issue and came here. I believe this is how many of us looking for a solution.

**Comment by segiddins** [comment]
If you're having an issue, please open one with all of the information requested in the contributing guidelines.

**Comment by fatuhoku** [comment]
... @segiddins I posted a link because I originally got my demo setup working using @andrew8712's code snippet. I was not raising a new issue. I cannot imagine why starting another issue would help anybody.
