### ISSUE TITLE
"A signed resource has been added, modified, or deleted" error for CocoaPods with .xib files

### ISSUE THREAD

**Issue by gillygize** [CocoaPods/CocoaPods#790]
![Screen Shot 2013-02-10 at 10 15 35 AM](https://f.cloud.github.com/assets/496130/142801/b7d9ebb6-731f-11e2-964d-45103e765870.png)

I have seen the above error message a number of times while using CocoaPods on two different projects.

If I run

```
 codesign --verify --verbose /path/to/MyApp.app
```

on my app, it can tell me why the verification failed.  The response that I receive is:

```
 resource modified: /path/to/MyApp.app/GTMOAuth2ViewTouch.nib
```

which, in this case, is a nib file from the gtm-oauth2 CocoaPods package.  I had a similar problem with another CocoaPods project, which also included a nib file.

It also does not occur the first time I compile a project, or if I clean the project and then build, which makes it seem as if the problem is something like: during the "Copy Pods Resource" phase, ibtool will touch the nib file _after_ the codesign process or perhaps that codesign is, for some reason, signing the app with the _old_ .nib rather than the new one.

Anyway, as a fix, I have added the script "rm -rf ${BUILT_PRODUCTS_DIR}" to the Pre-actions of the Build stage of my Scheme, which seems to fix the problem, but perhaps there is a way of handling the copy script which can make this unnecessary.

**Comment by dwery** [comment]
It actually happened to me while developing an app with a today extension, signing failed on a nib. What about having cocoapods detect nibs outside a bundle so that the podspec author could easily be notified?

**Comment by ronak2121** [comment]
We've also seen this even without any nib in our app extensions. All we did was turn on "link_with" to point to the today extension and this started happening: here's the relevant portion of the pod file:

xcodeproj 'TestApp', 'App Store Distribution' => :release, 'Debug' => :debug
link_with 'AppTarget', 'TodayExtension'

**Comment by angelolloqui** [comment]
Same thing here. App Extension with Pods is producing this error unless I do the `rm -rf ${BUILT_PRODUCTS_DIR}`, which causes lot longer build times. Very annoying!

**Comment by ronbarr** [comment]
I get this too.

**Comment by Hazneliel** [comment]
+1
This thing is slowing me badly

**Comment by rookdev** [comment]
This has been an issue for me as well.

**Comment by romoore** [comment]
+1

**Comment by segiddins** [comment]
Instead of all of these +1s, it would be really helpful if someone stepped up with a pull request that fixes the problem.

**Comment by mAu888** [comment]
A workaround for this issue for now is to move the *Copy Bundle Resources* after the *Copy Pods Resources* phase. Then add a new *Run script phase* before the *Copy Bundle Resources* with the following script:
```bash
find YourFolder -name "*.xcassets" -exec touch {} \+;
```

To determine which files actually have to be touched, build the project twice until you receive the signing error. Then run the following command in your build directory:
```bash
codesign --verify --verbose yourAppBundle.app/
```

It should give you something like:
```bash
file modified: /Users/anonymous/Library/Developer/Xcode/DerivedData/yourApp-eaqqekgihswhiueralkepqlxsjwk/Build/Products/Debug-iphoneos/yourAppBundle.app/Assets.car
```

Note: also run this command for any Today Extensions or other separate signed stuff (i.e. `codesign --verify --verbose yourAppBundle.app/PlugIns/yourTodayExtension.appex/`).

Kudos to @T-Pham who explained this [here](https://github.com/CocoaPods/CocoaPods/issues/1546#issuecomment-75701520).

**Comment by jvanderwee** [comment]
Should this be reopened then?

**Comment by kimar** [comment]
+1 I'm also seeing this in a Swift project with App Extension and Cocoapods.

**Comment by thyselius** [comment]
+1
I've tried every solution on this page with no luck, the strangest thing is that mAu888's 
codesign --verify --verbose MyApp.app/ 
Tells me:
MyApp.app/: valid on disk
MyApp.app/: satisfies its Designated Requirement
It seems like it should work, but I'm still getting the error message. Any ideas?

**Comment by kimar** [comment]
Me neither, I'd really like to contribute on this but I'd first need to figure out where and how Cocoapods does it's core work.

My actual problems seems to originate in my `WatchKit Extension` target using Cocoapods, I didn't manage to get this extension use Cocoapods, using them for my `App`-target works as expected.

**Comment by mAu888** [comment]
@thyselius Do you have any extension included in your app? Then you also have to check within the `PlugIns` folder inside your app bundle (see last part of [my previous post](https://github.com/CocoaPods/CocoaPods/issues/790#issuecomment-82861315)).

**Comment by chrisfsampaio** [comment]
@mAu888 I've ran the command and it gave the following output:
```
$codesign --verify --verbose MyApp.app/PlugIns/MyAppTodayExtension.appex

MyApp.app/PlugIns/MyAppTodayExtension.appex: a sealed resource is missing or invalid
file missing: /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyApp.app/PlugIns/MyAppTodayExtension.appex/Frameworks/CocoaLumberjack.framework/Modules/module.modulemap
file missing: /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyApp.app/PlugIns/MyAppTodayExtension.appex/Frameworks/YapDatabase.framework/Modules/module.modulemap
file missing: /Users/christian/Library/Developer/Xcode/DerivedData/MyApp-grrgmdoviysaemfceiqmuuiywqof/Build/Products/Debug-iphoneos/MyApp.app/PlugIns/MyAppTodayExtension.appex/Frameworks/UIImage_BlurredFrame.framework/Modules/module.modulemap
```

I didn't quite understand what you did to get the code signing process to work properly, any thoughs?

**Comment by chrisfsampaio** [comment]
I've managed to get this working by modifying the "Pods-frameworks.sh" script and adding the "Modules" folder to the excluded list. Also I've made a pull request that fixes the script generator. 🌈

**Comment by Jeswang** [comment]
@thyselius Did you solve the problem?

**Comment by thyselius** [comment]
No... Gave up after a few hours and did a swift only solution for the
keyboard extension. :(

**Comment by Jeswang** [comment]
@thyselius It seems a different problem here. Updating Xcode from 6.3 to 6.3.1 solves my problem.(Weird Xcode)

**Comment by whiskey** [comment]
I'm having the issues with Xcode 6.4, pods v. 0.38 – and previous versions of both. This happened after I added a today extension to my Obj-c/Swift app.

**Comment by iMinder** [comment]
We have the same problem after we add a today extension to our app.My solution is delete Today.appex created and let it create a new one.

**Comment by Koshub** [comment]
Have the same issue with XCode 6.4 , pods v 0.38.2 . After linking some pods with today extension target XCode starts to show this error. Need always clean build folder.

**Comment by neonichu** [comment]
Has anyone of you got a sample project which reproduces this?

**Comment by bnickel** [comment]
@neonichu I just got this on a relatively large project in Xcode 7.  I will try to distill it down but I assume it's a problem with my Podfile now that I've switched to using frameworks.

My Podfile looks like this (but longer):

```ruby
use_frameworks!
pod 'Bite'

target 'SEHotQuestionWidget', :exclusive => true do
    pod 'Bite'
end
```

During build, Xcode:

1. Builds and signs the Bite target.
2. Builds the SEHotQuestionWidget target and signs SEHotQuestionWidget.appex/Frameworks/Bite.framework.  **outputs about replacing signature**
3. Builds the app target and signs Stack\ Exchange.app/Frameworks/Bite.framework  **outputs about replacing signature**

Running `codesign --verify --verbose Stack\ Exchange.app` checks out.

Running `codesign --verify --verbose Stack\ Exchange.app/PlugIns/SEHotQuestionWidget.appex` gives me the following:

```text
Stack Exchange.app/PlugIns/SEHotQuestionWidget.appex: a sealed resource is missing or invalid
file modified: .../Stack Exchange.app/PlugIns/SEHotQuestionWidget.appex/Frameworks/Bite.framework/Bite
```

I am guessing I am doing something wrong because Bite.framework shouldn't exist in two places (is this because of exclusive?), but it looks like Cocoapods is touching all the extension frameworks, probably when it signs for the app target.

**Comment by bnickel** [comment]
The solution to my problem was actually just to remove the Embed Pods Frameworks step from app extension.  This only works because the frameworks used by my extension are a subset of the frameworks used by the app.  A full solution would probably be to have a `parent_target` function for extensions so frameworks provided by the parent are excluded from that step.

**Comment by bnickel** [comment]
Not able to create a sample project in 0.38.2.  In 0.36.4, converting to `use_frameworks!` added the script to my build phases. This is no longer the case with new installs.
