### ISSUE TITLE
Is local source location supported

### ISSUE THREAD

**Issue by Minghao2017** [CocoaPods/CocoaPods#7903]
Hey guys ,I just want to know if I can specify a local location for the `s.source` param in my pod spec file so that I don't have to have a remote git repository?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
