### ISSUE TITLE
Alternative to PODS_ROOT for 'pod lib lint' header search paths

### ISSUE THREAD

**Issue by wjmelements** [CocoaPods/CocoaPods#7905]
I am having trouble building the pod for `pod lib lint` because the pod lives in `Development Pods` instead of `Pods`, which breaks using `PODS_ROOT` for the header path, though only for linting. This would not be problematic, except that the pod is a transitive dependency, so I need to push a trunk podspec.

Pod paths:
```
openssl/
  - include/
  -   - openssl/
  -   -   - *.h
  -   - internal/
  -   -   - *.h
  - src/**/
  -   - *.h
  -   - *.c
```

The source files include `"internal/ctype.h"`, which I support with xcconfig:

```
  s.xcconfig = { 
    'HEADER_SEARCH_PATHS' => '${PODS_ROOT}/CoreEthereum/openssl/include',
    'USER_HEADER_SEARCH_PATHS' => '${PODS_ROOT}/CoreEthereum/openssl/src/**'
  }
  s.public_header_files = 'openssl/include/openssl/*.h'
  s.private_header_files = 'openssl/include/internal/*.h'
  s.source_files = 'openssl/**/*.c', 'openssl/include/**/*.h'
```

The prescribed solution is to specify the source files; however this is not sufficient to locate the `"internal/*.h"` files, and furthermore causes issues because other files that include `<ctype.h>`, like:
```
#include <ctype.h>
```
use the `internal/cytpe.h` instead of `/usr/include/ctype.h`, because Xcode does not distinguish `<>` and `""` includes. But still, even if I rename the file to avoid a conflict, the `internal/*.h` headers can not be found.

**Comment by dnkoutso** [comment]
Does using `PODS_TARGET_SRCROOT` work in your case?

**Comment by wjmelements** [comment]
That works (!) for the pod but not for its consumer; the consumer's header search path is now set as if `PODS_TARGET_SRCROOT` were undefined. I think I can work around that though. Where can I find documentation for the PODS_* variables?

**Comment by wjmelements** [comment]
The lint still fails because of the consumer issue; the consumer's header search path prevents the building of the module in the `App` lint project.

<img width="711" alt="screen shot 2018-07-02 at 6 22 31 pm" src="https://user-images.githubusercontent.com/799573/42193718-04547838-7e25-11e8-8c68-d8bae2ac11ef.png">

**Comment by wjmelements** [comment]
While I can use PODS_ROOT for my consumer, I believe I require an environment variable that the lint App can use to locate the development pod.

**Comment by wjmelements** [comment]
It looks like `pod lib lint` is not required for trunk push, and I can use `pod spec lint` (which works), so this is less-urgent for me now.

**Comment by dnkoutso** [comment]
Yes `pod spec lint` clones the actual library and consumes it as if it was remote. `pod lib lint` is for local.

Going to close this issue and we can re-open if we deem its necessary to improve something in the library.
