### ISSUE TITLE
Use "bundle install" then I got error "error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54"

### ISSUE THREAD

**Issue by chenzhengxu** [CocoaPods/CocoaPods#7906]
# Report

## What did you do?

1. Use `git clone git@github.com:CocoaPods/CocoaPods.git` to clone Cocoapods to my mac.
1. Then I switch to the branch `origin/1-5-stable`.
1. Enter the `CocoaPods` catalog,run `bundle instal`.

## What did you expect to happen?

Install all gem dependencies correctly.

## What happened instead?

I got a error

```
Fetching https://github.com/CocoaPods/Core.git
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

## CocoaPods Environment

```
gem -v
2.5.2
```

**Comment by dnkoutso** [comment]
Works for me:
```
Bundle complete! 32 Gemfile dependencies, 87 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

@chenzhengxu seems like maybe related to https://github.com/CocoaPods/CocoaPods/issues/7447

Goin to close preemptively but I *will* re-open if we confirm this is not an issue with your network configuration.
