### ISSUE TITLE
Could not generate swift representation

### ISSUE THREAD

**Issue by mefilt** [CocoaPods/CocoaPods#7913]
Hi, I'm using static libraries for swift
And when I want to go to the module (Jump to definition), I get this error.
If I use "use_frameworks", then everything works for me.
How do you think the problem is?

```
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!(false)
use_modular_headers!

target 'Kiss' do
    pod 'RxAlamofire'
    pod 'Moya/RxSwift'
end

```
<img width="884" alt="2018-07-07 16 54 41" src="https://user-images.githubusercontent.com/1247906/42411662-4842c0cc-8208-11e8-8903-a85015b4ce90.png">

**Comment by segiddins** [comment]
That looks like an error in SourceKit to me
