### ISSUE TITLE
Could not remove the Cache when pod upgrade/downgrade?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7915]
I have multi version cocoapods in my projects. The CP is controlled by the Gemfile.
The CP will clear all cache in `~/Library/Caches/CocoaPods/Pods` when the cocoapods version is different with `~/Library/Caches/CocoaPods/Pods/VERSION`.
For example, there is a project which use the CocoaPods v1.3.1, the `VERSION` in cache directory will be set to `1.3.1`. Then when I use the project which use the v1.5.3 CocoaPods, CP will clear the all cache:
```
      def ensure_matching_version
        version_file = root + 'VERSION'
        version = version_file.read.strip if version_file.file?

        root.rmtree if version != Pod::VERSION && root.exist?
        root.mkpath

        version_file.open('w') { |f| f << Pod::VERSION }
      end
```

On the other hand, In my CI server, a project with v1.5.3 create the cache and other with v1.3.1 will remove the cache at same time. There are 3 tasks be builded at same time. It will cause a error:
```
Errno::ENOTEMPTY - Directory not empty @ dir_s_rmdir - /Users/xx/Library/Caches/CocoaPods/Pods
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1337:in `rmdir'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1337:in `block in remove_dir1'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1348:in `platform_support'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1336:in `remove_dir1'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1329:in `remove'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:691:in `block in remove_entry'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1386:in `ensure in postorder_traverse'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:1386:in `postorder_traverse'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:689:in `remove_entry'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:557:in `block in rm_r'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:553:in `each'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:553:in `rm_r'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/pathname.rb:589:in `rmtree'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:83:in `ensure_matching_version'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader/cache.rb:22:in `initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:41:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/downloader.rb:41:in `download'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.3.1/lib/cocoapods/installer.rb:364:in `install_source_of_pod'
```

**Comment by segiddins** [comment]
We could try FLOCKing the cache directory, but CocoaPods generally has not supported running multiple installs simultaneously, though we certainly could.

As a short term workaround for you, you might want to use the skip cache option

**Comment by Whirlwind** [comment]
I think that running multiple installs simultaneously should be supported, because the CI always run many tasks. I think that we could check the cache version is allowed in current version, instead of match the version. eg: update the cache directory only when `VERSION < Pod::Version`

**Comment by amorde** [comment]
If we namespace the cache directory by version then it will stick around after upgrades. That might be a reasonable trade off, just something to keep in mind.

**Comment by Whirlwind** [comment]
Maybe, we could create a new `Cache::Version` instead of `Pod::Version`, so if we just upgrade the CocoaPods without change the Cache logic, the `Cache::Version` will not changed and the cache still works.

We could create a new namespace as the Cache Directory `Cache/v1`, then CocoaPods will clean the old cache directory by default. The CI will use a environment value to skip clean cache.

**Comment by amorde** [comment]
>> If we namespace the cache directory by version then it will stick around after upgrades. That might be a reasonable trade off, just something to keep in mind.
>
> yeah, thats an option, but it would lead to unbounded cache growth, which is really not optimal

Yep that's my concern as well

**Comment by dreampiggy** [comment]
I face the exact same issue.

I'm a Pod author, and I'm using a computer for Work and OpenSource Life.

Since CocoaPods is ruby gem, I use bundle to manage the multiple CocoaPods version.

For each Open Source Project, it contains its own `Gemfile`, like [FirebaseUI-iOS](https://github.com/firebase/FirebaseUI-iOS). When I start to build, I'll run `bundle update && bundle exec pod install`

However, because of CocoaPods this `automatically removing Cache` thing, each time I switch to different project (This become really frequently in my daily life). The `~/Library/Caches/CocoaPods` is been purged. Which means, I can not get all things ready and all Pods need to re-download.

Any good idea to solve this ? Currently I have to do this hack to avoid this behavior, really annoying:

```ruby
# ensure_matching_version #comment this line !
```

**Comment by Serena1993** [comment]
I have met a problem with the CI machine.
When the different source control in Podfile.lock.
One is 1.9.1 and another is 1.9.3.
When two CI jobs run concurrently.
The pod cache has version control, too. 
The two jobs will affect each other. 
I found clean cache will cause the job to fail.
Is there any method that can resolve this problem? 
Thanks

**Comment by KM8Oz** [comment]
- pod deintegrate && rm -rf ~/Library/Caches/CocoaPods/* 
 - pod install
