### ISSUE TITLE
I want change my CocoaPods account name

### ISSUE THREAD

**Issue by Mark-Ma-1988** [CocoaPods/CocoaPods#7918]
# Report

## What did you do?
I want to change my account (not pod name) by creating a new account: 
pod trunk register my_email ‘my_name’ --verbose`

## What did you expect to happen?

It can change my account name.

## What happened instead?

It didn't work.

## CocoaPods Environment

CocoaPods : 1.5.3
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.6.4
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ af1e88e8145be5259df1404b27320e1fc500ef2b

## Project that demonstrates the issue

Just want to change my account name

**Comment by DanToml** [comment]
@Mark-Ma-1988 If you use cocoapods-trunk from this branch (https://github.com/CocoaPods/cocoapods-trunk/pull/92) you should be able to use `pod trunk me rename`

**Comment by Mark-Ma-1988** [comment]
@DanToml I typed it in terminal, but got this return: Unknown command: `rename`

**Comment by Mark-Ma-1988** [comment]
@DanToml could you help me to change it in your backend database?

**Comment by DanToml** [comment]
@Mark-Ma-1988 Are you using cocoapods-trunk from the correct branch?

You may need to use a gemfile: http://guides.cocoapods.org/using/a-gemfile

**Comment by Mark-Ma-1988** [comment]
@DanToml the problem is, I can use this branch since there is already a high version of cocoapods-trunk in my laptop which is binded with cocoapods, could you merge this rename branch into your master branch, or is there other way for me fix it?

**Comment by dnkoutso** [comment]
Should the issue be closed then?

**Comment by Mark-Ma-1988** [comment]
@dnkoutso Yep, close it, thank you
