### ISSUE TITLE
Impossible to register two emails

### ISSUE THREAD

**Issue by wjmelements** [CocoaPods/CocoaPods#7922]
I have multiple email addresses because of work and I do not want to `pod trunk register` when I change my working email address. Once I've authorized a device for an email, I don't want to re-authorize again. I should be able to maintain pods assigned to different emails.

**Comment by DanToml** [comment]
@wjmelements If an account is your own, I would recommend using your personal email address, and adding an organisation specific user as an owner for pods owned by a corporate entity.

I'm not against adding support for multiple emails, but this would require changes to https://github.com/CocoaPods/trunk.cocoapods.org to support it in the domain model and api, alongside changes in https://github.com/CocoaPods/cocoapods-trunk for managing them. RFCs and PRs are welcome on the respective repositories.
