### ISSUE TITLE
pod repo push ignore "--no-overwrite" when specify "--commit-message"

### ISSUE THREAD

**Issue by HuangShaoyan** [CocoaPods/CocoaPods#7926]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Spec of foo (0.0.1) already exists in my private repo and a duplicate push is invoked. 
```pod repo push foo foo.spec --commit-message="my foo" --no-overwrite```

## What did you expect to happen?
CocoaPods should reject the duplicate push and outputs: 
```
Adding the spec to the `foo' repo

[!] foo (0.0.1) already exists and overwriting has been disabled.
```

## What happened instead?
CocoaPods ignores "--no-overwrite" and allows the push.
```
Adding the spec to the `foo' repo

 - [No change] foo (0.0.1)

Pushing the `foo' repo
```

## CocoaPods Environment
```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.17.0
```

## Bug 
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/command/repo/push.rb#L180:
```
def add_specs_to_repo
    ...
    if @message && !@message.empty?
        message = @message
    elsif output_path.exist?
        unless @allow_overwrite
        raise Informative, "#{spec} already exists and overwriting has been disabled."
        end
        message = "[Fix] #{spec}"
    ...
```
check of "@allow_overwrite" will be ignored if "@message" is not empty.

**Comment by segiddins** [comment]
A PR with a fix would be greatly appreciated!
