### ISSUE TITLE
The same issue

### ISSUE THREAD

**Issue by iamwlb** [CocoaPods/CocoaPods#7929]
Password:On branch master
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
Counting objects: 32, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (32/32), done.
Writing objects: 100% (32/32), 125.19 MiB | 0 bytes/s, done.
Total 32 (delta 16), reused 0 (delta 0)
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

**Comment by dnkoutso** [comment]
This looks like a connection issue. Sorry also this does not include enough information.
