### ISSUE TITLE
Swift Static Libraries + Unit Tests: Build errors

### ISSUE THREAD

**Issue by xaverlohmueller** [CocoaPods/CocoaPods#7935]
🌈
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I'm having an issue with CocoaPods Swift static library mode and Unit Tests. I've tried this with other pods (such as Alamofire) with identical results.

As described in the [1.5.0 release notes][1.5-release-notes], I tried just leaving out the `use_frameworks!` from the Podfile, but this breaks the unit test suite.

It might be related to [this issue][related-issue], but the steps there can't solve my issue.

## What did you do?

1. Run `pod install`
2. Add `import Kingfisher` (or whatever pod it is) to a file
3. Run cmd+U (Unit Tests)

## What did you expect to happen?

The Unit Tests should execute as expected

## What happened instead?

An error is generated: `Cannot load underlying module for 'Kingfisher'`

<img width="271" alt="screen shot 2018-07-16 at 20 51 26" src="https://user-images.githubusercontent.com/16212751/42777413-4a975750-893a-11e8-9003-6215bcbf7212.png">

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.18.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1c3d4235b58162d8979e143110dd0d1a320539b9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile
```
platform :ios, '10.0'

target 'CocoaPodsStatic'

pod 'Kingfisher', '~> 4.0'

target 'CocoaPodsStaticTests' do
  inherit! :search_paths
end
```

## Project that demonstrates the issue

[CocoaPodsStatic.zip](https://github.com/CocoaPods/CocoaPods/files/2198966/CocoaPodsStatic.zip)

[related-issue]: https://github.com/CocoaPods/CocoaPods/issues/7664
[1.5-release-notes]: http://blog.cocoapods.org/CocoaPods-1.5.0/

**Comment by paulb777** [comment]
This looks like a static library issue, not a static framework issue.  Kingfisher is not a static framework.

**Comment by xaverlohmueller** [comment]
Thanks for clarifying the terminology. I updated the title and the description.

**Comment by dnkoutso** [comment]
@xaverlohmueller this works:
```ruby
platform :ios, '10.0'

target 'CocoaPodsStatic' do
  pod 'Kingfisher', '~> 4.0'	
  target 'CocoaPodsStaticTests' do
    inherit! :search_paths
   end
end
```

I believe when you do not nest this certain settings are not added to the generated xcconfig. It might be a bug most likely with the way you have your Podfile but I am not sure.

**Comment by xaverlohmueller** [comment]
@dnkoutso Awesome, yes, this fixes the issue with the demo project!

I chose this Podfile as a minimal working example to reproduce the build failure.

Our real [Podfile][cineaste-podfile], however, has an `abstract_target`, so I can't perform this workaround.

Do you have any pointers how to perform a similar workaround with an `abstract_target`?

[cineaste-podfile]: https://github.com/spacepandas/cineaste-ios/blob/master/Podfile

**Comment by dnkoutso** [comment]
Neither abstract targets or targets with `inherit! :search_paths` will actually link the pod. You can remove `inherit! :search_paths` I believe and it should work.

**Comment by xaverlohmueller** [comment]
I see! Doing this, I get other errors related to Google Nearby, so I'll be investigating there.

Thanks for your help!
