### ISSUE TITLE
version 1.5.3 has some build problem on mac by use Xcode9.4

### ISSUE THREAD

**Issue by kobe1941** [CocoaPods/CocoaPods#7937]
we user one pod library called openssl-ios-bitcode， when pod version is 1.3.1，it work well , then I update cocoapods version to 1.5.3，Xcode can not build， always show the error:

`openssl/opensslconf.h' file not found `

**Comment by dnkoutso** [comment]
Sorry please ask StackOverflow under `cocoapods` tag.

There is not enough information here for us to diagnose this. Need a sample app and please fill in the issue template.
