### ISSUE TITLE
Anyway can put all the test targets into main target's scheme's buildable reference?

### ISSUE THREAD

**Issue by findyam** [CocoaPods/CocoaPods#7941]
We want run all the test case at once，but pods test targets need manually add into buildable reference，is there a way to modify the scheme with cocoapods or other script?
![image](https://user-images.githubusercontent.com/5172226/42940581-9ffa0c84-8b8c-11e8-8950-93f4785133c8.png)

**Comment by dnkoutso** [comment]
do you mean generated targets from test specs? Yes you can reference them manually or write a script that does it.

Start with something like:
```ruby
scheme = Xcodeproj::XCScheme.new(File.join(project.path, 'xcshareddata', 'xcschemes', 'My.xcscheme'))
# ... edit scheme here to add stuff
scheme.save!
```

This is currently not an issue so I am going to close. It is best to ask these questions on StackOverflow under `cocoapods` tag.

I will re-open if we figure out this is a good enhancement or a bug in the cocoapods library.
