### ISSUE TITLE
Xcode says: Project 'Pods' Turn on whole module optimization

### ISSUE THREAD

**Issue by phoney** [CocoaPods/CocoaPods#7944]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod update or pod install

## What did you expect to happen?

Pods project has no warnings from Xcode.

## What happened instead?

There are Xcode warnings that say: Update to recommended settings Pods.xcodeproj. I understand cocoapods isn't responsible for the warnings from individual pods but there is a new warning for the Pods project.

I believe this started with a recent update to cocoapods 1.5.3 and wasn't present in the previous version.
I'm using Xcode 9.4.1

<img width="585" alt="screen shot 2018-07-20 at 1 13 43 pm" src="https://user-images.githubusercontent.com/3106038/43016087-b1860c30-8c1f-11e8-8bbc-c9dac9f6a6f6.png">

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6fc2c0384a758081a1ed2411349c3be4bf0f92f1
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.4
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios,           '9.0'

def pods
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'Charts', '~> 3.1.0'
  pod 'Device'
  pod 'Down', '~> 0.4'
  pod 'DZNEmptyDataSet'
  pod 'FontAwesome.swift'
  pod 'HockeySDK', '~> 5.1'
  pod 'IQKeyboardManagerSwift', '~> 6.0'
  pod 'MGSwipeTableCell'
  pod 'Mixpanel-swift', '~> 2.3'
  pod 'PDFExporter'
  pod 'PhoneNumberKit'
  pod 'Realm', '~> 3.0'
  pod 'RealmSwift', '~> 3.0'
  pod 'SDWebImage', '~> 4.2'
  pod 'SVProgressHUD', '~> 2.0'
  pod 'SwiftDate', '~> 5.0'
  pod 'SWRevealViewController', :git => 'https://github.com/John-Lluch/SWRevealViewController.git', tag: 'v2.4.0'
  pod 'TPKeyboardAvoiding'
end

target 'MyApp' do
  pods
end
```

**Comment by dnkoutso** [comment]
Please upload sample app. Also could try `rm -rf Pods/Pods.xcodeproj` and try regenerating?

**Comment by phoney** [comment]
Sample project is here https://github.com/phoney/TestCocoaPods
"rm -rf Pods" had no effect.

**Comment by amorde** [comment]
I'm able to repro on master (including latest SHA of Xcodeproj) and on 1.5.3

Running `pod install` and then letting Xcode update the project results in a few of these:

```diff
-				SWIFT_COMPILATION_MODE = wholemodule;
-				SWIFT_OPTIMIZATION_LEVEL = "-O";
+				SWIFT_OPTIMIZATION_LEVEL = "-Owholemodule";
```

as well as a few of these:

```diff
				MTL_FAST_MATH = YES;
				PRODUCT_NAME = "$(TARGET_NAME)";
				STRIP_INSTALLED_PRODUCT = NO;
+				SWIFT_COMPILATION_MODE = wholemodule;
				SYMROOT = "${SRCROOT}/../build";
			};
```

that's as much info I have for now. I think Swift's optimization settings were updated for Swift 4.2

**Comment by segiddins** [comment]
@amorde doesnt https://github.com/CocoaPods/Xcodeproj/pull/578 contain those changes?

**Comment by amorde** [comment]
hmmm yeah @segiddins you're right - maybe there was something off about my particular set up?

**Comment by getaaron** [comment]
@segiddins the latest version of CocoaPods uses Xcodeproj 1.5.9 which doesn't contain the changes from your PR

I think we need a new Xcodeproj release to resolve this issue

**Comment by amorde** [comment]
When I tried this I was using the master branch of Xcodeproj.

Will check again now

**Comment by amorde** [comment]
Tested with a fresh project, I don't see these warnings on master. Will be fixed with the next release of Xcodeproj

**Comment by getaaron** [comment]
Should we keep the issue open until the xcodeproj release is available?
