### ISSUE TITLE
`pod repo push` command doesn't respect `--sources` order

### ISSUE THREAD

**Issue by a-voronov** [CocoaPods/CocoaPods#7947]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

`pod repo push` seems to not respect order of repos enumerated in `--sources` option, thus fetches repo with matching name from `master` instead of specified private specs-repo.

## What did you do?

Run `pod repo push --sources=privaterepo,master` (or full URL to privaterepo, doesn't matter)

## What did you expect to happen?

Use pod with matching name from `privaterepo` first.

## What happened instead?

Pod with matching name is used from `master` repo.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.0dev (2017-10-02 trunk 60101) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.14.2
Ruby lib dir : ~/.rvm/rubies/ruby-head/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8886978c993c6bc00a7293ce905bec1f6d48930c
               privaterepo - ssh://git@xxxx/xxxx.git @ xxxx
```

### Installation Source

```
Executable Path: ~/.rvm/gems/ruby-head/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
You are probably experiencing this issue which has a PR https://github.com/CocoaPods/Molinillo/pull/98.

**Comment by dnkoutso** [comment]
Can you use `pod 'A', :source => 'url/to/git/repo.git'`?

**Comment by a-voronov** [comment]
I’m actually solving it this way in Podfile, but you can’t specify source in podspec, since it doesn’t resolve anything. Thus when doing `pod repo push`, it can use pod from different source.

From what I see, you can name your pod with some preffix, leaving module name as it was. Or you might be able to use unique version preffix, that is only available in your pod. But not sure about latter.

**Comment by SebastianBoldt** [comment]
@dnkoutso I totally forgot about this option and yes it solved my issue. Thx.
