### ISSUE TITLE
Linting pod bundle fails with `The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift.`

### ISSUE THREAD

**Issue by gearnshaw** [CocoaPods/CocoaPods#7950]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod lib lint --verbose` on a pod library with a .xcdatamodeld file attached as a resource bundle

## What did you expect to happen?

Linting to complete successfully

## What happened instead?
Linting fails with the following error. I've checked that all targets in the pod workspace have the swift language version set, and it isn't clear to me where else I need to set this flag in order for the project to work with my bundle
```
     === CLEAN TARGET CoreDataBundleExample-CoreDataBundleExample OF PROJECT Pods WITH CONFIGURATION Release ===
    
    Check dependencies
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
    
    ** CLEAN FAILED **
    
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
    === BUILD TARGET CoreDataBundleExample-CoreDataBundleExample OF PROJECT Pods WITH CONFIGURATION Release ===
    
    Check dependencies
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

...
   ** BUILD FAILED **
    
    
    The following build commands failed:
    	Check dependencies
    (1 failure)
   Testing with `xcodebuild`. 
 -> CoreDataBundleExample (0.1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.

[!] CoreDataBundleExample did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

```
### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.17.1
Ruby lib dir : /Users/gabriellelittler/.rvm/rubies/ruby-2.4.2/lib
Repositories : bitbucket-controlf1-cf1-specs - https://bitbucket.org/controlf1/cf1-specs @ 54057a89684479c6556333adef172df146ba92ba
               cf1-specs - https://gllittler_cf1@bitbucket.org/controlf1/cf1-specs @ d697e6c7dc6d13d2316d66e8f7de7b1a2117cc32
               master - https://github.com/CocoaPods/Specs.git @ fd26e5d57586dbcb0d7bbf86b210afcef7bbbd94
```

### Installation Source

```
Executable Path: /Users/gabriellelittler/.rvm/rubies/ruby-2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/gearnshaw/CoreDataBundleExample

**Comment by dnkoutso** [comment]
Hm definitely can reproduce. I did not know `SWIFT_VERSION` should be set on resource bundles as well. I tried adding manually a new bundle in Xcode (without CocoaPods) and the `xcdatamodeld` and I received the same error.  

Not entirely sure what the right fix is here...we could have CocoaPods set that value.

**Comment by dnkoutso** [comment]
I guess it happens because the code generation for the `xcdatamodeld` is set to `Swift`.

**Comment by dnkoutso** [comment]
@gearnshaw fixed it.

**Comment by plflanagan** [comment]
I did not run into this error while linting, but I did run into this issue when trying to use the pod. I also had to change the `xcdatamodel code-generation` to `objective-c` before the project using the pod would clean successfully.
