### ISSUE TITLE
Pre-downloading is so slow!!!

### ISSUE THREAD

**Issue by AJXiao** [CocoaPods/CocoaPods#7951]
-> Pre-downloading: `iflyMSC` from `https://gitlab.com/PEP_Public/iflyMSC.git`, commit `1523d44eaef932b42e48b10a9485d792eb963717`
 > Git download
 > Git download
     $ /usr/bin/git clone https://gitlab.com/PEP_Public/iflyMSC.git
     /var/folders/jc/r25pjv252bbc5gmvn3wymhmm0000gn/T/d20180725-11230-1pjot67 --template=
     Cloning into '/var/folders/jc/r25pjv252bbc5gmvn3wymhmm0000gn/T/d20180725-11230-1pjot67'...

    i don't know what happened.
    /var/folders....?cocoapd need to change 'Var'???
   Pre-downloading is so slow!

**Comment by dnkoutso** [comment]
Sorry this is not a valid issue report and it does not appear to be an issue. Could be your internet connection or the repo you are trying to clone is big.

Going to close as this is not actionable.
