### ISSUE TITLE
`pod repo update` should unset GIT_DIR before running git operations

### ISSUE THREAD

**Issue by lilyball** [CocoaPods/CocoaPods#7958]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I updated my Podfile and ran `pod update someDep` from within a `git rebase` operation, which triggered a `pod repo update`.

## What did you expect to happen?

This should have updated the cocoapods repo.

## What happened instead?

Because I was in the middle of a `git rebase`, the `GIT_DIR` environment variable was set. This made CocoaPods's `git fetch` operation actually apply the operation to my local repo instead of the cocoapods spec repo.

## Notes

The `GIT_DIR` environment variable should be unset, but there's probably others that need to be unset too.

**Comment by segiddins** [comment]
Should be fairly easy to do, just by wrapping the git operations done in the source manager in a block that saves the `ENV`, unsets the git stuff, runs the fetch, and then restores
