### ISSUE TITLE
Why Metal can't work in pod ？

### ISSUE THREAD

**Issue by qianlishun** [CocoaPods/CocoaPods#7967]
I'm  build a pod thats uses the iOS Metal framework, it's succeed.

Then I pod this in a project, build succeed.

But it was wrong when it was running：

**[MTLComputePipelineDescriptorInternal setComputeFunction:], line 363: error 'computeFunction must not be nil.'**

This indicates that the metal file is not compiled, can't use the following method to get metal Function

> [m_Library  newFunctionWithName:@"metalMethodName"];

If I import the metal file in my project, it's work ok.

**How should I use the metal file in cocoapods?**

Look forward to your reply, thanks.

**Comment by dnkoutso** [comment]
Need a sample app. Unable to diagnose this without it.

**Comment by qianlishun** [comment]
I found out pod did not compile the ***.metal** into **metallib**, 
so Metal Function could not be used.

Although I now use resource to import *.metallib to pods, this can solve my problem for the time being.  but, the way does not solve the source control of metal files.

So, question:
**How do I set up Pods so that it can compile Metal files?**


> I try use Staic Library build *.a,  Staic Library did compile *.metal files into a default.metallib.

**Comment by qianlishun** [comment]
[PodsMetalTest.zip](https://github.com/CocoaPods/CocoaPods/files/2252855/PodsMetalTest.zip)

Sry, this is a test project ...   
I think it may not help.

**Comment by dnkoutso** [comment]
No you can only specify `use_frameworks` per target, not per pod.

**Comment by yangKJ** [comment]
Set the podspec file to `s.static_framework = false`.

In this way, the framework package can be loaded.

You can refer to my Metal open source library [Harbeth](https://github.com/yangKJ/Harbeth/blob/master/Harbeth.podspec) here.
