### ISSUE TITLE
Could I add the `pod_target_xcconfig` into user target if use `podspec` in the Podfile?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7968]
I have a idea. I often develop a SDK (static library), and sometimes I want to set the `pod_target_xcconfig` for my SDK pod. It is nothing wrong. 

But I found that I must set the `Build Settings` for my target to same settings with the podspec.
My Podfile:
```
target :mySDK do
   podspec
end
```
The `podspec` will pick the dependencies from the podspec, but it will not pick the `pod_target_xcconfig`. So I must set the build settings by myself. They are same settings. And my SDK  should be a pod and the `pod_target_xcconfig` should works. right?

**Comment by dnkoutso** [comment]
Isnt there a `user_target_xcconfig` you can set?

**Comment by Whirlwind** [comment]
If I set the `user_target_xcconfig`, The User project will be apply my config , when use `pod 'mySdk', :git=> ''`.

**Comment by Whirlwind** [comment]
The `user_target_xcconfig` will apply user target which use my SDK, it is dangerous and incorrect. I just want to set the config to my SDK target, so the `pod_target_xcconfig` should be used.

The mySDK is a normal target when I develop it, and use `podspec` to pick the dependencies. So the mySDK is a `user target`, the `pod_target_xcconfig` will not works. But the mySDK is a `pod target`, too. I hope the `pod_target_xcconfig` work.

**Comment by dnkoutso** [comment]
you can only achieve that using a post install hook in this case to set the same config to your mySDK target.

**Comment by Whirlwind** [comment]
It is a bad idea. I think that the `podspec` should set my current target to pod target.

**Comment by dnkoutso** [comment]
I cannot understand 100% what you are trying to say I am sorry.

**Comment by Whirlwind** [comment]
I sorry that my English is bad....

I think that the `podspec` will take my user target as a pod target, but the target is create by myself, not by cocoapods. So the every settings which to pod target will apply to my user target, too. There are some configs should set to my user target, like `pod_target_xcconfig`, `dependencies`, `subspec`, `requires_arc`, `compiler_flags` and so on.

By the way. the `podspec` lose some feature, eg: I hope pick some dependencies from a subspec to a target and pick another dependencies from other subspec to other user target, but the `podspec` is not support it.
```
target :mySDK1 do
     podspec :subspec=>'mySDK1'
end

target :mySDK2 do
    podspec :subspec => 'mySDK2'
end
```

The `mySDK1` and `mySDK2` is two different platforms, and they have different dependencies.

I think that we could add more feature into the `podspec` .
