### ISSUE TITLE
use_modular_headers w/ MaterialComponents pod

### ISSUE THREAD

**Issue by mwoollard** [CocoaPods/CocoaPods#7974]
* [* ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Having an issue with use_modular_headers with the MaterialComponents pod. We have a complex setup with internal repo and to date with 1.5.3 we've had no issues integrating 3rd party and our own pods with use_modular_headers.

MaterialComponents will build fine if integrated with use_frameworks but this is not a solution for us. I note that it appears to find the headers but for some reason isn't seeing the symbols from the pod dependencies MaterialComponents has on other pods such as MDFInternationalization.

Some experimenting suggested changing source includes to these from:

#import <MDFInternationalization/MDFInternationalization.h>

to

@import MDCInternationalization;

Fixed the compile issues, it allowed the build to progress a lot further but still had a couple of issues not resolved.

One thought is to post install hook to move the source from dependent pod targets into the main MaterialComponents pod target so the code isn't being treated as a separate module? Thoughts on that?

Any other fixes / suggestions ?

## What did you do?

ℹ Please replace these two lines with what you did.  
Create a shell single screen app project in Xcode

$ pod init

Edited pod file as needed

$ pod install

Then opened workspace and build

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Project to build

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  

Got compile time error:

/Users/markw/UrbanThings/mdbug/Pods/MaterialComponents/components/ButtonBar/src/private/MDCAppBarButtonBarBuilder.m:159:41: error: no visible @interface for 'MDCButtonBar' declares the selector 'mdf_effectiveUserInterfaceLayoutDirection'
             layoutDirection:[buttonBar mdf_effectiveUserInterfaceLayoutDirection]

## CocoaPods Environment

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : issue-7354 - https://github.com/mwoollard/issue-7354.git @ a5f04b96a60055d7f318043e7956c5879358a5af
               master - https://github.com/CocoaPods/Specs.git @ 52f343421ebc8e90a97b487740a075fc0b0b9b20
               mwoollard - https://github.com/mwoollard/specs.git @ b7b69c024fa9237d1058e034a64dcaeda26edd4d
               mwoollard-1 - https://github.com/mwoollard/erg_core.git @ b0deb7bd17563b8ffbeb246f985ee27aae50cf87
               urbanthings - git@bitbucket.org:urbanthings/podspecs.git @ 95d584b8a19493d7eee3a5ec128ad5113cb28378
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mdbug' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for mdbug
  pod 'MaterialComponents'

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,

Any Xcode template project with Podfile integrating 'MaterialComponents' with use_modular_headers will cause the issue.

**Comment by mwoollard** [comment]
After a few hours experimentation I can get our app to build with the following post install hook, hopefully this will give someone with deeper knowledge of the module import process than me some clues as how it might possibly be fixed in CocoaPods :-)

Found I needed to patch imports in MaterialComponents source .m files from `#import <Module/Module.h>` to `#import "Module.h"` and in header files (only one reference) from #import <Module/Module.h>` to `@import Module;`. Finally had to patch a module import header from `#import "Module.h"` to `#import <Module/Module.h>` (*Module* is placeholder for actual modules this needed doing for).

So I am unblocked but would be great to have this addressed in CocoaPods if it can be - thanks all !

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'MaterialComponents'
            root = File.join(File.dirname(installer.pods_project.path), 'MaterialComponents')
            `chflags -R nouchg #{root}`
            puts "Patching #import <MDFInternationalization/MDFInternationalization.h> -> @import MDFInternationalization;"
            `grep --include=\*.m -rl '#{root}' -e "#import\s*<MDFInternationalization/MDFInternationalization.h>" | xargs sed -i '' 's:<MDFInternationalization/MDFInternationalization.h>:"MDFInternationalization.h":'`
            puts "Patching #import <MotionAnimator/MotionAnimator.h> -> @import MotionAnimator;"
            `grep --include=\*.m -rl '#{root}' -e "#import\s*<MotionAnimator/MotionAnimator.h>" | xargs sed -i '' 's:<MotionAnimator/MotionAnimator.h>:"MotionAnimator.h":'`
            puts "Patching #import <MDFTextAccessibility/MDFTextAccessibility.h> -> @import MDFTextAccessibility;"
            `grep --include=\*.m -rl '#{root}' -e "#import\s*<MDFTextAccessibility/MDFTextAccessibility.h>" | xargs sed -i '' 's:<MDFTextAccessibility/MDFTextAccessibility.h>:"MDFTextAccessibility.h":'`
            `grep --include=\*.h -rl '#{root}' -e "#import\s*<MDFTextAccessibility/MDFTextAccessibility.h>" | xargs sed -i '' 's:#import <MDFTextAccessibility/MDFTextAccessibility.h>:\@import MDFTextAccessibility;:'`
        end
        if target.name == 'MDFTextAccessibility'
            puts "Patching MDFTextAccessibility-umbrella.h"
            root = File.join(File.dirname(installer.pods_project.path), 'Headers')
            `chflags -R nouchg #{root}`
            grep = "grep --include=MDFTextAccessibility-umbrella.h -rl \"#{root}\" -e \"#import \\\"MDFTextAccessibility.h\\\"\""
            `#{grep} | xargs sed -i '' 's:#import "MDFTextAccessibility.h":#import <MDFTextAccessibility/MDFTextAccessibility.h>:'`
        end
    end
end
```

**Comment by dnkoutso** [comment]
You would have to contact the pod author to have support for this and fix their header imports. I do not think anything can be done in CocoaPods here to fix this.

**Comment by mwoollard** [comment]
OK thanks for feedback - thought that might be the case !

**Comment by dnkoutso** [comment]
@mwoollard thank you, I will close this for now, we can re-open if we can figure out anything else around this.
