### ISSUE TITLE
Fail to add objc category file into swift pod

### ISSUE THREAD

**Issue by miku1958** [CocoaPods/CocoaPods#7987]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Create a swift project
2. Make a pod base the project and success
3. Compatible to objc ,try to add a category to a swift class and built success
4. Try to add objc file to pod ,then fail,It cant find swift class
5. Add @import myModule; in objc file,bulit success but still can't add to pod
6. Make swift class to subspec,then make objc file to another subspec ,but there is anthor error: import of module '' appears within same top-level module ''
7. Try diffent way to @import myModule; in objc file , like @import myModule.subModule; ,but fail
8. Try to make it possible,but fail, can't find any solution to add submodule of frame in pod

## What did you expect to happen?

can @import myModule.subModule;  
or add objc category file into swift pod

## What happened instead?

can't add objc category file into swift pod
can't make submodule

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c4cfcc961331e6c424405065486412107e513daf
               PrivatePods - https://github.com/ModulizationDemo/PrivatePods.git @ 15670ad09d48a8659723fee7ab238cd965416326
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'MDKImageCollection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MDKImageCollection
  pod 'MDKTools/swift'

end
```

## Project that demonstrates the issue

this my podspec
https://github.com/miku1958/MDKImageCollection/blob/master/MDKImageCollection.podspec

**Comment by amorde** [comment]
@miku1958 apologies this hasn't been looked into yet - have you gotten the chance to try this on the latest beta (`1.6.0.beta.2`)?
