### ISSUE TITLE
Trying to configure a MAS, and non-MAS version of mac app with different pods

### ISSUE THREAD

**Issue by rudedogg** [CocoaPods/CocoaPods#7990]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Duplicated build schemes for a Mac App Store version, and non-App Store version:
![screen shot 2018-08-08 at 12 17 56 pm](https://user-images.githubusercontent.com/2127629/43856301-5c89961c-9b05-11e8-870e-75b8e78bf28c.png)

- Added `Active Compilation Condition` variables for MAS/NOMAS to make `#if MAS` work
![screen shot 2018-08-08 at 12 18 30 pm](https://user-images.githubusercontent.com/2127629/43856312-636aa732-9b05-11e8-8357-428bc7649035.png)

- Added configuration entries to a Podfile, ie:
```ruby
  pod 'DevMateKit_MAS', :configuration => ['Debug MAS', 'Release MAS']
  pod 'DevMateKit', :configuration => ['Debug NOMAS', 'Release NOMAS']
```
- Ran `pod install`

- Opened .xcworkspace

- Attempt to use those pods.

- Use `NOMAS` build scheme and build the app

## What did you expect to happen?

Expected to be able to import and use those pods based on the build scheme being used.

## What happened instead?

Get "No such module `DevMateKit`, etc. Same issue with `canImport()`; it never succeeds.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.18.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 318dd6d72ddffb6bbd3ea063b887684d9d65bdb6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :osx, '10.11'

target 'ColorProducer' do
  pod 'SnapKit'
  pod 'Realm', :modular_headers => true
  pod 'RealmSwift'
  pod 'Highlightr'
  pod 'VersionTrackerSwift'
  pod 'AsyncSwift'
  pod 'SwiftyAttributes'
  pod 'MulticastDelegateSwift'
  pod 'Differ'
  pod 'SipHash'
  pod 'DOMKit', :git => 'http://git.local:3000/rudedogg/DOMKit.git', :branch => 'master'
  pod 'ColorKit', :git => 'http://git.local:3000/rudedogg/ColorKit.git', :branch => 'master'
 # pod 'Try' # For catching obj-c errors webkit throws
  pod 'SwifterSwift/SwiftStdlib' # Used only for Double.random in AddColorsFromImageViewController
  # Format/Linting
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
  pod 'IBAnalyzer'

  pod 'DevMateKit_MAS', :configuration => ['Debug MAS', 'Release MAS']
  pod 'DevMateKit', :configuration => ['Debug NOMAS', 'Release NOMAS']
end

target 'ColorProducerTests' do

end
```

**Comment by dnkoutso** [comment]
Is it possible to package up a sample app?

**Comment by rudedogg** [comment]
@dnkoutso Sure, I've uploaded a minimal example of the issue at https://github.com/rudedogg/cocoapods-build-config-issue

I committed after every single step, so hopefully looking at the commits will be helpful.

**Comment by dnkoutso** [comment]
thank you so much. This helps a lot. Will need to find time to investigate. Appreciate the time.

**Comment by dnkoutso** [comment]
@rudedogg I do not think this is a CocoaPods issue...There are multiple issues here.

First the podspec is wrong (https://github.com/CocoaPods/Specs/blob/master/Specs/6/7/e/DevMateKit/1.3/DevMateKit.podspec.json#L25-L28)
```
  "xcconfig": {
    "LD_RUNPATH_SEARCH_PATHS": "@executable_path/../Frameworks",
    "FRAMEWORK_SEARCH_PATHS": "$(PODS_ROOT)/DevMateKit/DevMateKit.framework/Frameworks"
  }
```

This should be removed. CocoaPods does the right thing and its also missing `$(inherited)`.

Second, the vendored framework itself does not include a module map.

<img width="882" alt="screen_shot_2018-08-16_at_8_23_40_pm" src="https://user-images.githubusercontent.com/310370/44246308-61a06980-a192-11e8-8b54-5826e5f81102.png">

Add a `module.modulemap` file into that folder:

```
framework module DevMateKit {
    umbrella header "DevMateKit.h"
    module * { export * }
```

Finally this line is wrong https://github.com/CocoaPods/Specs/blob/master/Specs/6/7/e/DevMateKit/1.3/DevMateKit.podspec.json#L24 and must be removed.

Got it to work.

<img width="971" alt="screen shot 2018-08-16 at 8 28 15 pm" src="https://user-images.githubusercontent.com/310370/44246418-ed19fa80-a192-11e8-8d24-c15c070a846e.png">

Going to close this issue as its a problem with the vendored framework instead.
