### ISSUE TITLE
Getting error when installing pod 'Firebase'

### ISSUE THREAD

**Issue by ashokquad** [CocoaPods/CocoaPods#7993]
target 'NJHINTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NJHINUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
Errno::EACCES - Permission denied @ dir_s_mkdir - /Users/admin/Library/Caches/CocoaPods
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:229:in `mkdir'
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:229:in `fu_mkdir'
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:207:in `block (2 levels) in mkdir_p'
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:205:in `reverse_each'
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:205:in `block in mkdir_p'
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:191:in `each'
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
/Users/admin/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/pathname.rb:576:in `mkpath'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/config.rb:90:in `cache_root'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:33:in `download'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/pod_source_installer.rb:121:in `download_source'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:374:in `install_source_of_pod'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:339:in `block (2 levels) in install_pod_sources'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:338:in `block in install_pod_sources'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:321:in `each'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:321:in `install_pod_sources'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:164:in `block in download_dependencies'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:162:in `download_dependencies'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:117:in `install!'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Users/admin/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/admin/.rvm/gems/ruby-2.4.1@global/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/Users/admin/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
/Users/admin/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/admin/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `eval'
/Users/admin/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Fadmin%2FLibrary%2FCaches%2FCocoaPods&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by paulb777** [comment]
See the first line of the Error message. CocoaPods expects to have permission to write to `$HOME/Library/Caches/CocoaPods`

**Comment by ashokquad** [comment]
how to I enable the permission. please give me terminal command

**Comment by amorde** [comment]
@ashfurrow that folder should already be writable by default, if not you can look into the unix `chmod` command.

I'd recommend posting on [StackOverflow](https://stackoverflow.com/questions/tagged/cocoapods) for help with troubleshooting these kind of issues
