### ISSUE TITLE
Pod Repo Name when putting the source in Podfile is unexpected.

### ISSUE THREAD

**Issue by eugenebiryukov** [CocoaPods/CocoaPods#7997]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I want to use private repo kept on GitHub under organization account. The account name consists of three letter-numbers (for the case if it could cause the issue), so it looks in Podfile like: 
```
source https://github.com/us1/my-pod-lib.git
```

Then I'm running 'pod install' command.

## What did you expect to happen?

I expect Cocoapod to generate a name specific for the project like it is supposed to be: 'us1-my-pod-lib', so different libraries in organization will be gotten managed separately.

## What happened instead?

Cocoapod log shown this:
```
Cloning spec repo `us1` from `https://github.com/us1/my-pod-lib.git`.
```

So, the Cocoapod gave the repo's name using the Organization name only: 'us1'. And because of it all the Pods of the Organization get managed all together that is not acceptable, so I need to ask Integrators to run additional command 'pod repo add MyPodLib https://github.com/us1/my-pod-lib.git' to work it around.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-art         : 1.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
I think you're confusing the pod spec repo, (what `source` is) and a custom podspec url which uses [`pod`](https://guides.cocoapods.org/syntax/podfile.html#pod).

**Comment by eugenebiryukov** [comment]
Alright, but why when I used bitbucket on the Organization's server (as subtool: `source 'http://team.organization.com/bitbucket/path/my-pod-lib.git'`) exactly by the described way in the case, it created for me a podspec repo as designed: "organization-my-pod-lib"?

**Comment by orta** [comment]
We have to generate some sort of name to use locally for the local podspec source repos. When using GitHub the org makes a lot of sense because you'd usually only have one per org. 

For non-github URLs we use something else I guess - I'd consider that an implementation detail.

**Comment by eugenebiryukov** [comment]
Ok, thanks.
