### ISSUE TITLE
EXPANDED_CODE_SIGN_IDENTITY: unbound variable

### ISSUE THREAD

**Issue by ZevEisenberg** [CocoaPods/CocoaPods#8000]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`bundle exec pod lib lint --no-clean --verbose`

## What did you expect to happen?

The pod lints cleanly.

## What happened instead?

Linting fails with:

>/var/folders/j_/86_9xkgj0pqc0q2h5xx_9lt40000gn/T/CocoaPods-Lint-20180810-16542-1ru5jza-BonMot/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code

This seems to be some kind of weird regression of #7708, which appears to have been fixed prior to the release of CocoaPods 1.5.3, but when I look at the contents of the Pods-App-frameworks.sh script mentioned in the error message, it contains `if [ -n "${EXPANDED_CODE_SIGN_IDENTITY}"` instead of the version from that issue/PR, which should look like `if [ -n "${EXPANDED_CODE_SIGN_IDENTITY:-}"`.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10L221o)
         Git : git version 2.18.0
Ruby lib dir : /Users/zev/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 00eaf927d5829980d5afde43770d32c23086099a
```

### Installation Source

```
Executable Path: /Users/zev/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.6
```

## Project that demonstrates the issue

https://github.com/Raizlabs/BonMot/pull/344 as of commit https://github.com/Raizlabs/BonMot/pull/344/commits/8300727aa1b0bda7d1f5fab5ca5826abe3e50409

**Comment by ZevEisenberg** [comment]
Oh, and you can see the error log from a build _in situ_ at https://circleci.com/gh/Raizlabs/BonMot/612?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by dnkoutso** [comment]
Can you try master?

**Comment by dnkoutso** [comment]
Seems like that fix is in 1.6.0 not 1.5.3. So I believe `master` should work for you.

**Comment by ZevEisenberg** [comment]
Oops, totally missed the milestone flag. Checking.

**Comment by ZevEisenberg** [comment]
That worked. Is there a timeline for 1.6? Specifically, do you think it will be before/around the time of Xcode 10 going GM? The work I'm doing on this branch is for Xcode 10 compatibility.

**Comment by dnkoutso** [comment]
Actually we are probably days away from shipping 1.6.0.beta.1. A blog post is ready https://github.com/CocoaPods/blog.cocoapods.org/pull/154

Thank you for confirming though!

**Comment by Jon889** [comment]
From the 7708 issue:  the workaround is to do:

export EXPANDED_CODE_SIGN_IDENTITY=""
export EXPANDED_CODE_SIGN_IDENTITY_NAME=""
export EXPANDED_PROVISIONING_PROFILE=""

before the command to build is run.
