### ISSUE TITLE
Pod Update: RuntimeError - [Xcodeproj] Unknown object version. Xcode Beta 5

### ISSUE THREAD

**Issue by TheApApp** [CocoaPods/CocoaPods#8003]
* [X ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod update

## What did you expect to happen?

Trying to add RxSwift to a iOS 12 project I am working on with Beta 5 of Xcode 10.  

## What happened instead?

received the error RuntimeError - [Xcodeproj] Unknown object version.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A353d)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e434706ac19542c15f62606df118dc800193f13d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'


target 'WastedTime' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'TwitterKit' 
    pod 'TwitterCore'
    pod "RxSwift"
    pod "RxCocoa"
    
  # 'JTSImageViewController'

end
```
### Error

```
RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:218:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.9/lib/xcodeproj/project.rb:103:in `open'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:918:in `block (2 levels) in inspect_targets_to_integrate'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `each'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:917:in `block in inspect_targets_to_integrate'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:912:in `inspect_targets_to_integrate'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:78:in `analyze'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/update.rb:97:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Users/michaelrowe/.gem/ruby/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

**Comment by dnkoutso** [comment]
Hello there, can you please upload a sample app? There is a chance this is already fixed on Xcodeproj master. Use Bundler (https://bundler.io/v1.12/git.html) to install and use it.

**Comment by TheApApp** [comment]
Not sure what details you need in the sample project.. I tried to do the same update on another computer that is not using Mojave or the xCode 10 beta...   do you just need the xCodeproj file?

**Comment by TheApApp** [comment]
OK, here's the Xcode Workspace and two project files as well as the podfile.  I am trusting that they don't contain anything like developer keys, etc.  (if so let me know and I will delete) 
[WastedTime.xcworkspace.zip](https://github.com/CocoaPods/CocoaPods/files/2284017/WastedTime.xcworkspace.zip)
[WastedTime.xcodeproj.zip](https://github.com/CocoaPods/CocoaPods/files/2284018/WastedTime.xcodeproj.zip)
[Pods.xcodeproj.zip](https://github.com/CocoaPods/CocoaPods/files/2284019/Pods.xcodeproj.zip)

**Comment by dnkoutso** [comment]
thank you very much will take a look.

**Comment by TheApApp** [comment]
Do you have all you need?

**Comment by dnkoutso** [comment]
This worked for me on latest master
```
The Gemfile's dependencies are satisfied
Analyzing dependencies
Downloading dependencies
Installing TwitterCore (3.2.0)
Installing TwitterKit (3.4.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```

**Comment by TheApApp** [comment]
Hmmm.. it should also be pulling in RxSwift

**Comment by dnkoutso** [comment]
I had those removed on purpose but will try again with them

**Comment by dnkoutso** [comment]
@TheApApp can you please try 1.6.0.beta.1?

**Comment by dnkoutso** [comment]
I am on Xcode 10 Beta 5 with your project and all the dependencies and it all works.

**Comment by dnkoutso** [comment]
```
Using RxCocoa (4.2.0)
Using RxSwift (4.2.0)
Using TwitterCore (3.2.0)
Using TwitterKit (3.4.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 4 dependencies from the Podfile and 4 total pods installed.
```

**Comment by TheApApp** [comment]
Ok.. then I am confused... but I guess it is not recreatable on your side.. go ahead and close

**Comment by dnkoutso** [comment]
@TheApApp OK, can you also try 1.6.0.beta.1 it was just released!

Also ensure that your compatibility version of Xcode is something like 3.2:

![screen_shot_2018-08-17_at_12_50_46_pm](https://user-images.githubusercontent.com/310370/44285984-3e220100-a21c-11e8-8670-a32ccfde6bf7.png)

**Comment by TheApApp** [comment]
I uninstalled cocoapods and reinstalled and still same issue

**Comment by TheApApp** [comment]
New update .. the 1.6.0 version of Cocoapods seems to have fixed all my issues. And I have successfully run the pod update!!

**Comment by dnkoutso** [comment]
yay!

**Comment by knightcode** [comment]
downgrading my project file from Xcode 10-compatible to Xcode 8.0-compatible worked for me on this one
