### ISSUE TITLE
ruby-2.4.2 clean and reinstalled, Pod Init fails with _rb_isspace error

### ISSUE THREAD

**Issue by sonnytron** [CocoaPods/CocoaPods#8006]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?  

brew install cocoapods
cd Developer/ProjectDir  
pod init

## What did you expect to happen?

PodFile to be created in project directory

## What happened instead?

```
dyld: lazy symbol binding failed: Symbol not found: _rb_isspace
  Referenced from: /Users/UserName/.rvm/gems/ruby-2.4.2/gems/bigdecimal-1.3.4/lib/bigdecimal.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_isspace
  Referenced from: /Users/UserName/.rvm/gems/ruby-2.4.2/gems/bigdecimal-1.3.4/lib/bigdecimal.bundle
  Expected in: flat namespace
```
## CocoaPods Environment

```
dyld: lazy symbol binding failed: Symbol not found: _rb_isspace
  Referenced from: /Users/UserName/.rvm/gems/ruby-2.4.2/gems/bigdecimal-1.3.4/lib/bigdecimal.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_isspace
  Referenced from: /Users/UserName/.rvm/gems/ruby-2.4.2/gems/bigdecimal-1.3.4/lib/bigdecimal.bundle
  Expected in: flat namespace

[1]    34004 abort      pod env
```
## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
Not related to project

**Comment by dnkoutso** [comment]
Have no idea. Seems like somethings wrong with the Ruby setup and specifically the `bigdecimal` gem...not really CocoaPods.

Does everything else work in Rubygems?

**Comment by Nakilon** [comment]
Did anyone investigate this?
I have a gem that compiles well on macOS but on Alpine I get these "symbol not found" in runtime starting from Ruby 2.4
