### ISSUE TITLE
resource_bundles have wrong BuildableName before opening Xcode

### ISSUE THREAD

**Issue by DickSmith** [CocoaPods/CocoaPods#8007]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I have a development pod that includes a resource_bundle with same name as the Cocoapod (or even a different name):
`Candy.podspec`:
``` ruby
s.name = 'Candy'
...
s.resource_bundle = {
  'Candy' => [
    'Assets/**/*.*'
  ]
}
```

`pod install`
Build using command line tools without opening the project in Xcode.

## What did you expect to happen?
The resource bundle `BuildableName` is as expected (e.g. `Candy.bundle`).
`demo.xcworkspace/xcuserdata/dick.xcuserdatad/UserInterfaceState.xcuserstate`:
``` xml
<BuildableReference
    BuildableIdentifier = "primary"
    BlueprintIdentifier = "B97EC5452B757418871ECAD2EE9818B8"
    BuildableName = "Candy.bundle"
    BlueprintName = "Candy-Candy"
    ReferencedContainer = "container:Pods.xcodeproj">
</BuildableReference>
```

## What happened instead?
The resource bundle `buildableName` is not as expected (e.g. `Candy-Candy.bundle`)
`demo.xcworkspace/xcuserdata/dick.xcuserdatad/UserInterfaceState.xcuserstate`:
``` xml
<BuildableReference
   BuildableIdentifier = "primary"
   BlueprintIdentifier = "B97EC5452B757418871ECAD2EE9818B8"
   BlueprintName = "Candy-Candy"
   ReferencedContainer = "container:Pods.xcodeproj"
   BuildableName = "Candy-Candy.bundle">
</BuildableReference>
```
When I then open the workspace in Xcode, this then auto-corrects to the expected `BuildableName` of `Candy.bundle`.
However, when building using TravisCI, the Xcode.app is not used to open the project, so the `BuildableName` is not corrected when building from the command line.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.12
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /Users/dick/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ af1c40cc1f1d4a977c53a7b7436f76f4c5358eec
```

### Installation Source

```
Executable Path: /Users/dick/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Definitely a thing we can improve on. Thanks for the great report. I think resource bundles are intentionally namespaced with the name of the pod so they do not collide between other pods so it will always prefix your pods name to the bundle name.

**Comment by DickSmith** [comment]
After trying a few different things in the `post_install`, I found that this results in a consistent `.xcscheme` both before and after launching the project in Xcode:
```
post_install do |installer|
  installer.target_installation_results.pod_target_installation_results.each do |t, v|
    if v.resource_bundle_targets.length != 0
      v.resource_bundle_targets.each do |rbt|
        rbt.build_configuration_list.build_configurations.each do |bc|
          bc.build_settings['PRODUCT_NAME'] = rbt.product_name
        end
      end
    end
  end
end
```
It seems that the `PBXNativeTarget.product_name` and the `XCBuildConfiguration.build_settings['PRODUCT_NAME']` have different values before opening Xcode. The `PBXNativeTarget` will have `PodName-BundleName` and the `XCBuildConfiguration` will have `BundleName`. When launching Xcode, Xcode then resolves this by prioritizing the value in `XCBuildConfiguration`.

The inverse works does not seem to work, however:
```
...
      v.resource_bundle_targets.each do |rbt|
        rbt.build_configuration_list.build_configurations.each do |bc|
          rbt.product_name = bc.build_settings['PRODUCT_NAME']
        end
...
```
It appears that `PBXNativeTarget.name` is used for both the *BuildableName* (Porduct Name) and *BlueprintName* (Target Name) instead of `PBXNativeTarget.product_name` for the `BuildableName` when generating the `.xcscheme`.

From what I can tell, the namespaced version of the bundle is always being discarded for the non-namespaced once Xcode is opened.

**Comment by dnkoutso** [comment]
Could review it in a PR along with a test!

**Comment by DickSmith** [comment]
@dnkoutso 
For sure, my Ruby skills are pretty weak, so it may be a bit before I can dig into the actual code to figure out the fix. For now I'm just updating this issue with my findings in case anyone else encounters a similar issue and needs to solve it. Too often GitHub tickets have misleading workarounds, since once the poster finds the good one they stop updating the ticket. :D

My current work around:
```
post_install do |installer|
  installer.pods_project.targets.each do |nt|
    if nt.isa != 'PBXAggregateTarget'
      # PBXNativeTarget.name is BlueprintName
      # PBXNativeTarget.product_reference.path is BuildableName
      # But opening Xcode auto-corrects product_reference.path -> product_reference.name
      ref_name = nt.product_reference.name
      if nt.product_reference.path != ref_name
        puts "Renaming #{nt.product_reference.path} -> #{ref_name}"
        nt.product_reference.path = ref_name
      end
    end
  end
end
```

I found that it subtly affects all targets, potentially, even the top level AbtractTargets (which usually isn't an issue, but does mean the schemes are subtly different before opening Xcode):
<img width="894" alt="screen shot 2018-09-03 at 11 20 04 pm" src="https://user-images.githubusercontent.com/6675511/45187049-6f7b6480-b1fd-11e8-99ec-08321c5fa678.png">
<img width="904" alt="screen shot 2018-09-03 at 11 20 22 pm" src="https://user-images.githubusercontent.com/6675511/45187068-730eeb80-b1fd-11e8-9710-cb8e4a018abc.png">
(BuildableNames have the `-` are converted to `_`, once Xcode being opened, but by setting `product_reference.path -> product_reference.name` the schemes are 100% the same, and Xcode doesn't even reorder the other lines as shown in my diffs.)
