### ISSUE TITLE
Embedded frameworks dependencies are copied as part of Embed Pods Frameworks regardless of their whitelists

### ISSUE THREAD

**Issue by thibaudrobelain** [CocoaPods/CocoaPods#8011]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I used a Podfile similar to https://github.com/thibaudrobelain/EmbeddedFrameworksReproApp/blob/master/Podfile

The app I work on embeds a framework created in a subproject. As suggested in https://github.com/CocoaPods/CocoaPods/issues/6123, I did:

> In the meantime, you can work around this by making your core project a sub-project in your app project and then adding your core.framework as a dependency in your target dependency build phase

It's working fine, except in our project, there's a specific requirement of the Embedded Framework to only link against a specific pod for the "Debug" configuration as it's not needed in release builds.

## What did you expect to happen?

The embedded framework's dependency to only be copied to the Frameworks directory when building for Debug

## What happened instead?

The embedded framework's dependency was copied over in all builds.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

https://github.com/thibaudrobelain/EmbeddedFrameworksReproApp
Readme should give you more info about what I did!

The current workaround is commented in that sample repo / podfile above, and it's to explicitly add the same dependency to the app target, with the same whitelist. That way, it's correctly excluded.

I see some newer commits in the files we took a look at when investigating (like https://github.com/CocoaPods/CocoaPods/blob/412c5109f37a9783870caf0f8113d2b3240ebeef/lib/cocoapods/installer/analyzer.rb#L269) so I'm not exactly sure what the new behavior is going to be but I couldn't get the project to compile when trying bin/pod in the master branch of CocoaPods at this time. (didn't spend much time trying, though.)

**Comment by dnkoutso** [comment]
Is this with CocoaPods 1.5.3 or master?

**Comment by thibaudrobelain** [comment]
Yes, that's the behavior we're seeing. Actually I'll try master on the example project and not on our repo too.

**Comment by dnkoutso** [comment]
@thibaudrobelain my output above was from master, I think I repro'd and can understand the issue. We can potentially get a fix. But please do some more inspection if you'd like as it will help me further.

**Comment by thibaudrobelain** [comment]
Yeah I just confirmed the same thing as you with master on the repro app. However, in our actual repo the dependency is just gone from all the configurations when I `pod install` from the master branch...

**Comment by dnkoutso** [comment]
The dependency might be by some other optimizations done to reduce the generated `.xcodeproj` size. I think the bug is that the script includes this framework in the `.sh` file

**Comment by dnkoutso** [comment]
@thibaudrobelain I am sorry I just want to clarify as you saying the bug exists or does not exist on master?

**Comment by thibaudrobelain** [comment]
@dnkoutso On master, the bug definitely exists for the repro app (as you pointed out with the parts you copied from the Embed frameworks script)
For our repo, it seems like a different bug is introduced in master, in the sense that the pod dependency disappears from ALL configurations, even the ones where it should have been whitelisted.

Like this would be our project's look with current master
```
if [[ "$CONFIGURATION" == "Debug" ]]; then
 # expected to see Pod dependency but did not
fi
if [[ "$CONFIGURATION" == "Release" ]]; then

fi
```

Does that clarify it?

**Comment by dnkoutso** [comment]
I am not seeing the "other" bug you are saying...Here's a screenshot of what i see from master

<img width="1148" alt="screen shot 2018-08-14 at 2 51 06 pm" src="https://user-images.githubusercontent.com/310370/44120545-89c4fa10-9fd1-11e8-9239-dda4d3b6a380.png">

**Comment by thibaudrobelain** [comment]
oh yeah @dnkoutso, I meant that the other bug I see in our own project (that I can't share)

**Comment by dnkoutso** [comment]
I see well lets fix this one here first...

**Comment by dnkoutso** [comment]
@thibaudrobelain I think I have a fix.

**Comment by dnkoutso** [comment]
@thibaudrobelain fixed.
![screen shot 2018-08-14 at 3 18 55 pm](https://user-images.githubusercontent.com/310370/44121580-653ac180-9fd5-11e8-9261-f8ade598d24b.png)

keep in mind this will break release builds for your app but that is what you've asked in the Podfile so in my opinion it is correct.

**Comment by thibaudrobelain** [comment]
@dnkoutso Cool, I'll give this a try shortly on our own project too!

**Comment by thibaudrobelain** [comment]
@dnkoutso yeah so FYI with master after your PR merge, our project has no mention of the pod dependency at all in that shell script, even in configurations where it should be embedded. Anything I could do to help see if this is an actual issue?

**Comment by dnkoutso** [comment]
@thibaudrobelain np. 

I think you might be experiencing a different issue, perhaps its a configuration issue on your side. I know that the original issue you filed here was a definitely a bug and it was fixed.

The most helpful and best thing to do here is upload a sample project again in which you expect a frameworks pods to be embedded to a host but they are not.

My gut feeling is that 1.6.0 (master) does something better now and 1.5.3 was accidentally including targets that were not supposed to be there.

**Comment by thibaudrobelain** [comment]
@dnkoutso, so just to close the loop, I've tried with 1.6.0.beta.1 and couldn't repro the case where the framework disappeared from that shell script... all clear for now!
