### ISSUE TITLE
Libraries with conflicting names with vendored_libraries from two different dependencies

### ISSUE THREAD

**Issue by marcelomp** [CocoaPods/CocoaPods#8012]
Using CocoaPods <= 1.5.3
Using Xcode 9.2: Requires CocoaPods 1.5.3.

# Report

## What did you do?

    'pod install'

## What did you expect to happen?

    Install all pod dependencies correctly.

## What happened instead?

[!] The 'Pods-MyApp' target has libraries with conflicting names: libCommonDependency.a and libCommonDependency-simulator.a.

### Stack

```
CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.5 (17F77)
    Xcode : 9.2 (9C40b)
        Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4ebd1a592e014393618ef654e557862d2653d3d9
            produbanbr-br-arch-mobile-stspec - https://gitlab.produbanbr.corp/BR-ARCH-MOBILE/STSpec.git @ 51e7a9516319b6e9c4dbb695fd7c31c27c015f24
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

source 'https://github.com/CocoaPods/Specs.git'

target 'MyApp' do
    
  use_frameworks!

  pod 'Dependency1'
  pod 'Dependency2'

end

# Detailed Description

I have one common dependency that defines a pod that only exports a common .a library, 
a second and a third dependency that both depend on that common dependency and an App that depend on these two dependencies
below are the sample .podspec files to each dependency and the Podfile for the App,

// Common Dependency .podspec
```
    Pod::Spec.new do |s|
        s.name = "CommonDependency"
        ....
        s.vendored_libraries = 'libs/libCommonDependency.a', 'libs/libCommonDependency.a'
        ....
    end
````

// Dependency 1 .podspec
```
    Pod::Spec.new do |s|
        s.name = "Dependency1"
        ....
        s.dependency 'CommonDependency'
        ...
    end
````

// Dependency 2 .podspec
```
    Pod::Spec.new do |s|
        s.name = "Dependency2"
        ....
        s.dependency 'CommonDependency'
        ....
    end
````

// App Podfile
```
source 'https://github.com/CocoaPods/Specs.git'

target 'MyApp' do
    
  use_frameworks!

  pod 'Dependency1'
  pod 'Dependency2'

end
```

After I run a pod install I get the following error,

[!] The 'Pods-MyApp' target has libraries with conflicting names: libCommonDependency.a and libCommonDependency-simulator.a.

That happen because the method verify_no_duplicate_names in file target_validator.rb contains duplicated instances from those libs,
that where added from two diferent dependencies, 

```
def verify_no_duplicate_names(names, label, type)
    duplicates = names.map { |n| n.to_s.downcase }.group_by { |f| f }.select { |_, v| v.size > 1 }.keys
    unless duplicates.empty?
    raise Informative, "The '#{label}' target has " \
        "#{type} with conflicting names: #{duplicates.to_sentence}."
    end
end
````

If i ignore the error (comment that method out) the project compiles fine, I suspect that method should consider duplicated libs from the 
same dependency but not from diferent dependencies, as the project file was created fine and there are no linking errors.

**Comment by dnkoutso** [comment]
Want to attempt to fix this with a PR and a test?

**Comment by marcelomp** [comment]
Sure, I am just not sure if my analysis of the problem is correct, on an initial testing only skipping the verification of duplicate names on my case did work. But I am afraid that I could be missing something.

**Comment by dnkoutso** [comment]
I need to look thoroughly on your issue to make sure its actually doing the right thing or not. The best way to also figure this out is writing a test :) I know it's hard but doing so would help everyone.

Thanks for the report!

**Comment by marcelomp** [comment]
After further investigation, I found out that the problem was with the .podspec of one of the dependencies, the cocoapods behavior was the expected one. So I will close the issue.
