### ISSUE TITLE
 [!] Dictionary missing ';' after key-value pair for "ORGANIZATIONNAME", found "@" (Nanaimo::Reader::ParseError)

### ISSUE THREAD

**Issue by wenhaoliu** [CocoaPods/CocoaPods#8017]
```
[!] Dictionary missing ';' after key-value pair for "ORGANIZATIONNAME", found "@" (Nanaimo::Reader::ParseError)
   #  -------------------------------------------
   #  				CLASSPREFIX = ZbCCPaperSearchModuleDemo;
   #  				LastUpgradeCheck = 0830;
146>  				ORGANIZATIONNAME = xxxxxxxxxxx@189.cn;
      				                              ^
   #  				TargetAttributes = {
   #  					6003F589195388D20070C39A = {
   #  -------------------------------------------
```
I have this problem  when I used cocoapods to create the custom template. How can I change the 'ORGANIZATIONNAME'，Hope to answer！

My cocoapods version is  1.5.3 , nanaimo is 0.2.6.

**Comment by ToLengSon** [comment]
Sky King cover ground tiger，Price tower shock river monster.

**Comment by wenhaoliu** [comment]
@ToLengSon Are you the fucking funny guy who invited by monkey?

**Comment by dnkoutso** [comment]
<img width="325" alt="screen_shot_2018-08-16_at_8_06_36_am" src="https://user-images.githubusercontent.com/310370/44217038-5534f600-a12b-11e8-9d5b-2061dbe78841.png">

Wrap the value in quotes inside your `proect.pbxproj`

```
ORGANIZATIONNAME = "@something";
```

**Comment by wenhaoliu** [comment]
@dnkoutso Hi, I tried to modify 'proect. Pbxproj', but 'ORGANIZATIONNAME' did not change when I used cocoapods to create the custom template.
