### ISSUE TITLE
pod try doesn't work for SwiftNIO

### ISSUE THREAD

**Issue by weissi** [CocoaPods/CocoaPods#8019]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
pod try SwiftNIO
```

## What did you expect to happen?

Xcode opening up with a project where I can try SwiftNIO

## What happened instead?

```
$ pod try SwiftNIO
Updating spec repositories

Trying SwiftNIO
[!] Unable to find any project in the source files of the Pod: `/private/var/folders/k8/7d0p_dxx2ll8vnw5mt5__ddc0000gn/T/CocoaPods/Try/SwiftNIO`
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
       Xcode : 10.0 (10A243)
         Git : git version 2.17.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d5477981560bd851f8aa66dd2db6a2bfd4251e1b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

n/a

**Comment by dnkoutso** [comment]
For version 1.9.1 of SwiftNIO there is no `.xcodeproj` at that tag as `pod try` expects. https://github.com/CocoaPods/cocoapods-try/blob/master/lib/pod/command/try.rb#L250-L262

It seems you need to provide one so it knows which project to open. 

Others like `pod try Alamofire` work.

We _could_ actually hook up `cocoapods-try` to the other plugin `cocoapods-generate` (https://github.com/square/cocoapods-generate) and generate the workspace if one cannot be found.

**Comment by dnkoutso** [comment]
@weissi I'd actually file this issue to https://github.com/CocoaPods/cocoapods-try repo and we can mark it as an enhancement.

**Comment by weissi** [comment]
@dnkoutso thanks, will migrate!
