### ISSUE TITLE
Are the Metrics/Quality Indexes working?

### ISSUE THREAD

**Issue by pcsaito** [CocoaPods/CocoaPods#8020]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Submitted a new Pod version.

## What did you expect to happen?

The metrics get updated to the new version sent.

## What happened instead?

All the metrics used for the quality index are frozen on the first version of the pod. This is misleading and turns all the quality index not trustful and favourable to old Pods with the metrics.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A365a)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 35342599c4c53b5fa1930f5bee1ee810e4dcf4ac
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
use_frameworks!

target 'FlowterTests' do
  pod 'KIF'
end
```

## Project that demonstrates the issue
https://cocoapods.org/pods/Flowter

**Comment by dnkoutso** [comment]
Hey there, thanks for your report. Can you please file with https://github.com/CocoaPods/metrics.cocoapods.org instead?

**Comment by dnkoutso** [comment]
Re-tracked https://github.com/CocoaPods/metrics.cocoapods.org/issues/46
