### ISSUE TITLE
[1.6.0.beta.1] pod outdated fails with 

### ISSUE THREAD

**Issue by marcelofabri** [CocoaPods/CocoaPods#8025]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod outdated` with CP 1.6.0.beta1.

## What did you expect to happen?

It would show outdated Pods.

## What happened instead?

```
[!] Cannot analyze without fetching dependencies since the sandbox is not up-to-date. Run `pod install` to ensure all dependencies have been fetched.
```

This was working on CP 1.5.3.

PS: I've run `pod install` after that and tried again, just in case.

## CocoaPods Environment

I couldn't reproduce it in another project. I can send privately the environment information to a maintainer, just not comfortable posting it here since it's happening on a real™ project.

**Comment by dnkoutso** [comment]
Yeap most likely a regression thanks

**Comment by dnkoutso** [comment]
Would love a sample here to be honest...maybe the command is actually working better now?

**Comment by marcelofabri** [comment]
@dnkoutso I've just sent you an email with the output from `pod env`. Hope that helps!

**Comment by dnkoutso** [comment]
thanks, I can reproduce on an internal project of mine.
