### ISSUE TITLE
Error running unit tests for a static framework

### ISSUE THREAD

**Issue by felipe-valio-movile** [CocoaPods/CocoaPods#8031]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Create a pod with `pod lib create TestExample`
2. Turn the pod in a static framework by adding `s.static_framework = true`
3. Create a unit test class in `TestExample/Tests/FrameworkTests.swift`
4. Create a test spec in `TestExample.podspec` like this:

```
s.test_spec 'Tests' do |test_spec|
  test_spec.source_files = 'TestExample/Tests/**/*'
end
```

5. Add `TestExample-Unit-Tests` to tests action of the project scheme
6. Run the tests

## What did you expect to happen?

The pod tests should run correctly.

## What happened instead?

The app tests runs fine, but the pod tests fails with this console message:

```
2018-08-21 13:59:45.787495-0300 xctest[40101:8820276] The bundle “TestExample-Unit-Tests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-08-21 13:59:45.788556-0300 xctest[40101:8820276] (dlopen_preflight(/Users/felipe.valio/Library/Developer/Xcode/DerivedData/TestExample-gyfgqphahycqtigtvqsrufgjzjlq/Build/Products/Debug-iphonesimulator/TestExample-Unit-Tests.xctest/TestExample-Unit-Tests): Library not loaded: @rpath/TestExample.framework/TestExample
  Referenced from: /Users/felipe.valio/Library/Developer/Xcode/DerivedData/TestExample-gyfgqphahycqtigtvqsrufgjzjlq/Build/Products/Debug-iphonesimulator/TestExample-Unit-Tests.xctest/TestExample-Unit-Tests
  Reason: image not found)
Program ended with exit code: 82
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.8.1
Ruby lib dir : /Users/felipe.valio/.rvm/rubies/ruby-2.4.1/lib
Repositories : brion - https://github.com/brion/OGVKit-Specs.git @ 112e5ba727405f227246bbf6fbc7ef519ac823a7
               master - https://github.com/CocoaPods/Specs.git @ 329ece4460f5123db814792f678b52a742034e54
```

### Installation Source

```
Executable Path: /Users/felipe.valio/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 0.8.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

platform :ios, '10.0'

target 'TestExample_Example' do
  pod 'TestExample', :path => '../', :testspecs => ['Tests']

  target 'TestExample_Tests' do
    inherit! :search_paths
  end
end
```

## Project that demonstrates the issue

https://github.com/felipe-valio-movile/TestExample

**Comment by dnkoutso** [comment]
Great report, thanks, have you tried 1.6.0.beta.1?

**Comment by felipe-valio-movile** [comment]
Yes, I tried it just now, the problem still occurs.

**Comment by dnkoutso** [comment]
@felipe-valio-movile does your `TestExample-Unit-Tests` have any files?

**Comment by dnkoutso** [comment]
Yes you do...investigating.

**Comment by dnkoutso** [comment]
@felipe-valio-movile confirmed this is an issue due to `s.static_framework = true` being set in your `podspec`.

Will mark it for 1.6.0 (and 1.6.0.beta.2)

**Comment by dnkoutso** [comment]
Found it! It is semi-related to static frameworks. Got a fix !

**Comment by felipe-valio-movile** [comment]
Yes, there is a test file:

https://github.com/felipe-valio-movile/TestExample/blob/master/TestExample/Tests/FrameworkTests.swift

**Comment by dnkoutso** [comment]
@felipe-valio-movile fixed.
