### ISSUE TITLE
Apple Mach-O Linker Error on test target when accessing some types from specific pods

### ISSUE THREAD

**Issue by devxoul** [CocoaPods/CocoaPods#8036]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Created a new project named 'MyApp' with Xcode 9.4.1.

```console
$ cd MyApp
$ pod init
$ vim Podfile
$ pod install
Analyzing dependencies
Downloading dependencies
Installing Quick (1.3.1)
Installing lottie-ios (2.5.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```

**ViewController.swift**

```swift
import UIKit
import Lottie

class ViewController: UIViewController {
  let animationView = LOTAnimationView()
}
```

**MyAppTests.swift**

```swift
import XCTest
@testable import MyApp

class MyAppTests: XCTestCase {
  func testExample() {
    print(ViewController().animationView) // this line causes the problem
  }
}
```

And I didn't modify any other build settings.

## What did you expect to happen?

<kbd>Command</kbd> + <kbd>U</kbd> runs the test correctly.

## What happened instead?

<img width="321" alt="screen shot 2018-08-22 at 4 23 56 pm" src="https://user-images.githubusercontent.com/931655/44448973-c98a0080-a627-11e8-8720-f484b12d198d.png">

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LOTAnimationView", referenced from:
      objc-class-ref in MyAppTests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The interesting this is that the test build works when I delete the `inherit! :search_paths` line from the Podfile.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.14 (18A365a)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.12.0
Ruby lib dir : /Users/xoul/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 546f07e1da2488b16a5b7ae9941efad810de93a6
```

### Installation Source

```
Executable Path: /Users/xoul/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 0.8.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
inhibit_all_warnings!
platform :ios, '9.0'

target 'MyApp' do
  use_frameworks!
  pod 'lottie-ios'

  target 'MyAppTests' do
    inherit! :search_paths
    pod 'Quick'
  end
end
```

## Project that demonstrates the issue

You can just create a new Xcode project and install `lottie-ios`. There are some other pods that cause the problem (from my existing project):

<img width="324" alt="screen shot 2018-08-22 at 4 34 15 pm" src="https://user-images.githubusercontent.com/931655/44449481-3b167e80-a629-11e8-9c97-c68585f3773e.png">

**Comment by devxoul** [comment]
Another workaround I found is to import all the pods at least once in the test target.

**Comment by dnkoutso** [comment]
Can you please provide a sample app?

**Comment by devxoul** [comment]
@dnkoutso, actually I didn't create a sample project because I could reproduce the bug in other machine. I just created one and you can find it [here](https://github.com/devxoul/CocoaPods-issue-8036).

**Comment by dnkoutso** [comment]
Thank you!

**Comment by dnkoutso** [comment]
@devxoul works for me on CocoaPods 1.6.0.beta.1 and Xcode 10 (10A254a).

Was able to launch app and run tests.

**Comment by devxoul** [comment]
Yeah, I tried again with the new Xcode and it works on Xcode 10 and CocoaPods 1.5.3 as well :)
