### ISSUE TITLE
[New Feature] Generate xcfilelist for Script Build Phases

### ISSUE THREAD

**Issue by dacaiguoguogmail** [CocoaPods/CocoaPods#8037]
Xcode 10 has a new xcfilelist file type that can be used to specify the input and output files for Run Script build phases. We should generate these files so that no one needs to manually specify all those files for "[CP] Embed Pods Frameworks"

**Comment by dnkoutso** [comment]
Yes but only when Xcode 10 is released and Xcode 9 is no longer supported. It will be a while.

> so that no one needs to manually specify all those files for "[CP] Embed Pods Frameworks"

Noone needs to maintain this manually today, CocoaPods takes care of these.

**Comment by segiddins** [comment]
We could do it conditionally based upon the object version in the project file

**Comment by dnkoutso** [comment]
Marking for 1.7.0.
