### ISSUE TITLE
[Question] failed to push a Swift pod which depends on an Objective-C pod

### ISSUE THREAD

**Issue by casatwy** [CocoaPods/CocoaPods#8038]
I have a question about push a swift pod that depends on a Objective-C pod, and I googled a lot but find nothing helpful, can you guys help me? or tell me some keywords that I can google?

```
The Swift pod `Extension_MandarinUploadViewController` depends upon `CTMediator`, which do not define modules. 

To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

The `Extension_MandarinUploadViewController` is a Swift pod, and `CTMediator` is a Objective-C pod.
I want to push `Extension_MandarinUploadViewController` as a private pod.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 7846d407822407c6a93526cbf81d5b53058e08bb
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Extension_MandarinUploadViewController' do

use_frameworks!
pod "CTMediator"
 
end
```

If you want any other information, just tell me, and I will put it here.

**Comment by dnkoutso** [comment]
Hey there, this looks like a great example of a question that you should ask on StackOverflow - there is an active tag CocoaPods where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests.

There is also `--use-modular-headers` in 1.6.0.beta.1

**Comment by casatwy** [comment]
Thank you! Your answer solved my problem!

and next time I will send my question to stackoverflow.

Thank you again!
