### ISSUE TITLE
pod lib lint fails during compilation although generated project compiles correctly

### ISSUE THREAD

**Issue by jgongo** [CocoaPods/CocoaPods#8040]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I tried to publish a private pod to a private spec repository. The publication failed due to compilation errors. In order to diagnose the issue I manually run `pod lib lint`, and I got some unexpected compilation problems. Further diagnosing took me to run `pod lib lint` with the `--no-clean` option to inspect the generated project:

```
$ bin/pod lib lint --private --allow-warnings --sources=git@github.com:wuakitv/ios-specs.git,https://github.com/CocoaPods/Specs --no-clean
```

## What did you expect to happen?

Both `pod lib lint` and the generated project should either succeed or fail while compiling the sources.

## What happened instead?

`pod lib lint` failed during compilation with the following error:

```
 -> Tifmetok (1.0.0)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - WARN  | url: The URL (https://github.com/wuakitv/tifmetok) is not reachable.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - WARN  | xcodebuild:  SwinjectPropertyLoader/Sources/JsonPropertyLoader.swift:46:104: warning: 'characters' is deprecated: Please use String or Substring directly
    - WARN  | xcodebuild:  SwinjectPropertyLoader/Sources/JsonPropertyLoader.swift:50:44: warning: 'characters' is deprecated: Please use String or Substring directly
    - ERROR | [iOS] xcodebuild:  /Users/jose.gonzalez/Documents/projects/rakuten/ios/tifmetok/Tifmetok/classes/configuration/PropertyDescriptorBuilder.swift:21:16: error: cannot convert return expression of type 'PropertyDescriptorBuilder<T>' to return type 'PropertyDescriptorBuilder<PropertyDescriptor<T>>'
    - ERROR | [iOS] xcodebuild:  /Users/jose.gonzalez/Documents/projects/rakuten/ios/tifmetok/Tifmetok/classes/configuration/PropertyDescriptorBuilder.swift:26:16: error: cannot convert return expression of type 'PropertyDescriptorBuilder<T>' to return type 'PropertyDescriptorBuilder<PropertyDescriptor<T>>'
    - ERROR | [iOS] xcodebuild:  /Users/jose.gonzalez/Documents/projects/rakuten/ios/tifmetok/Tifmetok/classes/configuration/PropertyDescriptorBuilder.swift:31:16: error: cannot convert return expression of type 'PropertyDescriptorBuilder<T>' to return type 'PropertyDescriptorBuilder<PropertyDescriptor<T>>'
    - ERROR | [iOS] xcodebuild:  /Users/jose.gonzalez/Documents/projects/rakuten/ios/tifmetok/Tifmetok/classes/configuration/PropertyDescriptorBuilder.swift:35:84: error: cannot convert return expression of type 'PropertyDescriptor<PropertyDescriptor<T>>' to return type 'PropertyDescriptor<T>'
    - ERROR | [iOS] xcodebuild:  /Users/jose.gonzalez/Documents/projects/rakuten/ios/tifmetok/Tifmetok/classes/configuration/PropertyDescriptorBuilder.swift:41:98: error: cannot convert value of type 'URL' to expected dictionary value type 'PropertyDescriptor<URL>'

Pods workspace available at `/var/folders/d2/wk2qp1qj65s4nj_s7kn2kw3nmbk8_y/T/CocoaPods-Lint-20180822-17958-c4a8d6-Tifmetok/App.xcworkspace` for inspection.

[!] Tifmetok did not pass validation, due to 6 errors.
```

Meanwhile, opening the generated project with the following command:

```
open /var/folders/d2/wk2qp1qj65s4nj_s7kn2kw3nmbk8_y/T/CocoaPods-Lint-20180822-17958-c4a8d6-Tifmetok/App.xcworkspace
```

and building it for testing (shift + command + u) succeeded. The build log is included as an attachment: [successful-compilation.rtf.zip](https://github.com/CocoaPods/CocoaPods/files/2310749/successful-compilation.rtf.zip)

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.16.2
Ruby lib dir : /Users/jose.gonzalez/.rbenv/versions/2.5.0/lib
Repositories : marketing-suite - https://github.com/Marketing-Suite/podSpec.git @ d1efbaa085e0273f1472b9053cf69b5bedb52289
               master - https://github.com/CocoaPods/Specs.git @ e5cb9a11a1f75be6ab8b341e4ce6d9f3a2159bba
               rakuten-it-scm-eco-core-ios-specs - https://gitpub.rakuten-it.com/scm/eco/core-ios-specs.git @ 223ff65437a41ab23251109c448ce63ef59fcbf6
               wuakitv - git@github.com:wuakitv/ios-specs.git @ d06e98f7d24a8b6a4f7523c816466eb5febb8feb
```

### Installation Source

```
Executable Path: bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
slather               : 2.4.6
```

## Project that demonstrates the issue

I'm not able to publicly upload the project as this is internal code, but I would be willing to share it privately with whoever wants to take a look at it (from the CocoaPods team).

Anyway it seems I've managed to reduce the sources involved in the bug to the two pods included in the following zip: [lint-bug.zip](https://github.com/CocoaPods/CocoaPods/files/2311078/lint-bug.zip)

**Comment by dnkoutso** [comment]
Thanks for report but we are unable to diagnose without a sample, please attach one.

**Comment by jgongo** [comment]
Can I send it privately to the person reviewing the bug?

**Comment by dnkoutso** [comment]
preferably the original pod with sources so I can also try it out.

**Comment by jgongo** [comment]
@dnkoutso This pod is an internal pod that uses several other internal pods coming from a private spec repository. I don't think I can share this publicly. Is there any other way to do this?

**Comment by dnkoutso** [comment]
I understand completely...you have a good report but I can't figure out if somethings wrong...

Do you use same Xcode in command line and when you open the workspace?

**Comment by jgongo** [comment]
I have managed to reduce the sources involved in the bug, I think you can reproduce it with the two pods included in the following zip: [lint-bug.zip](https://github.com/CocoaPods/CocoaPods/files/2311078/lint-bug.zip)

Regarding Xcode, I'm using Xcode 9.4.1 to open the workspace, the same version reported by `pod env`

**Comment by dnkoutso** [comment]
great

**Comment by jgongo** [comment]
Let me know if you need anything else. Thanks!

**Comment by jgongo** [comment]
I'm reviewing the code and I'm starting to think this is a weird Swift compilation bug...

**Comment by dnkoutso** [comment]
Still doesn't explain why the two are different :| they shouldn't be.

**Comment by jgongo** [comment]
You were right... if I change the build configuration from Debug to Release it also fails in Xcode. What I don't understand is how the code is correctly compiling in the Debug configuration, if it's supposed to fail due to the type system being unable to properly match types due to the generic parameter and associated type being named the same. Any idea??

**Comment by dnkoutso** [comment]
¯\\\_(ツ)_/¯

**Comment by dnkoutso** [comment]
@jgongo sounds like not a CocoaPods issue, if you are OK with this I am going to close we can re-open if we figure out a problem in the CocoaPods library but this seems like a Swift Compiler issue. Also recommend following up on StackOverflow.
