### ISSUE TITLE
Transitive Dependencies Error.....with a Dynamic Framework?

### ISSUE THREAD

**Issue by Nightsd01** [CocoaPods/CocoaPods#8050]
* [y] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Ran `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
I receive the following error. The strange thing is, the framework it mentions **DOES NOT** depend on static binaries, so I am at a loss as to why this is happening...?

```
The 'Pods-Runner' target has transitive dependencies that include static binaries: (/Users/bradhesse/onesignal/OneSignal-Flutter-SDK/example/ios/Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework)
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d626ba255046031293304fbf1f67b1bdb7f5fcf9
               OneSignalPro - https://github.com/Hiptic/OneSignal-iOS-SDK-PRO.git @ b92175abb35ffd4c88f52349b2cd4168cb5b2141
               twilio - https://github.com/twilio/cocoapod-specs @ 87ef83a8a28f39d04729f08f0cbcddd95276a2f6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

***NOTE***: This is a complicated podfile because it's a Flutter project, but you can ignore almost all of it. The problem is if I use `OneSignal` as a _dependency_ of another podspec. Attempting to run `pod install` with that other podspec that depends on OneSignal causes the problem.

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
   use_frameworks!
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

# target 'OneSignalNotificationServiceExtension' do
#    use_frameworks!
#    pod 'OneSignal', '>= 2.8.7', '< 3.0'
# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

## Project that demonstrates the issue
I can post an example project if needed, but I think an even better link would be to just link to the framework that is causing the issue. It's our OneSignal-iOS-SDK here:
https://github.com/OneSignal/OneSignal-iOS-SDK/issues

Using this framework _directly_ in a Swift project (with `use_frameworks!`) works fine. The only problem is if I use OneSignal as a *dependency* of another project. The bizarre thing is that the OneSignal iOS SDK does _not_ depend on any static libraries, so I am not sure why this is happening or how I can fix it?

**Comment by paulb777** [comment]
The framework in OneSignal is a static framework:

```
$ file Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal
Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal: Mach-O universal binary with 4 architectures: [i386:current ar archive] [arm64]
Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal (for architecture i386):	current ar archive
Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal (for architecture armv7):	current ar archive
Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal (for architecture x86_64):	current ar archive
Pods/OneSignal/iOS_SDK/OneSignalSDK/Framework/OneSignal.framework/OneSignal (for architecture arm64):	current ar archive
```

**Comment by Nightsd01** [comment]
@paulb777 I'm a bit confused - isn't any framework ending in `.framework' always a dynamic (not static) framework?

**Comment by Nightsd01** [comment]
@paulb777 Also, in the build settings for the SDK, the target that produces `OneSignal.framework` has `Mach-O type` = `Dynamic Library`?

**Comment by paulb777** [comment]
Frameworks can include static or dynamic libraries. This one, as is the case in most CocoaPods' vendored_frameworks, is static.

Are you sure that the target you're looking at is the one that built the fat library framework that's in the CocoaPod?

**Comment by dnkoutso** [comment]
It seems this is working as expected? Should we close and re-open if we do realize this is actually a CP issue?

**Comment by Nightsd01** [comment]
It appears that whenever we build our dynamic framework, it builds as a static framework. We need to export it from an archive in order to produce the dynamic framework.

This actually fixes multiple issues we've been facing, thanks for bringing this up! I was under the impression _all_ `.framework`'s were dynamic frameworks, thank you for clearing that up for me.
