### ISSUE TITLE
How to use static framework with dynamic framework at the same time?

### ISSUE THREAD

**Issue by yupengyang** [CocoaPods/CocoaPods#8051]
I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

cocoapods version : 1.5.0

In my podfile, I use `use_frameworks!`. I need to keep it on for my unit test (Quick need to be dynamic framework to run)

But in my project, I need to use [AMapLocation](https://cocoapods.org/pods/AMapLocation) for location service which is static framework.

 when i run `pod install`, there is an error: `target has transitive dependencies that include static binaries: ({project path}/Pods/AMapLocation/AMapLocationKit.framework)`

I got a solution from Google, add these code in `Podfile`

```
pre_install do |installer|
    Pod::PodTarget.send(:define_method, :static_framework?) {
        return true
    }
end
```

It actually fix `pod install` error. But it change all my framework into static library which makes UnitTest cannot get the code coverage. 

I don't want to change all my pods into static library, so

**is there a way to use static and dynamic library in Podfile at the same time?**

**Comment by dnkoutso** [comment]
You can use different `use_frameworks!` entries per target.

I think this question is best to be asked in StackOverflow under `cocoapods` tag.

**Comment by Copypeng** [comment]
so，what about the static framework and dynamic framework in the same target ?

**Comment by eggswift** [comment]
> so，what about the static framework and dynamic framework in the same target ?

same issue
