### ISSUE TITLE
CocoaPods 1.6.0.beta.1 no longer supports weak_frameworks

### ISSUE THREAD

**Issue by bstpierr** [CocoaPods/CocoaPods#8052]
* [ x ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lint Google-Mobile-Ads-SDK.podspec.json`

## What did you expect to happen?

The linting to succeed

## What happened instead?

Linting failed due to missing symbols from an Apple framework that should be weak-linked.

## CocoaPods Environment

I was using `pod --version` 1.6.0.beta.1 at the time. I've since gone back to 1.5.3.

## Project that demonstrates the issue

Download the current version of [Google Mobile Ads SDK](https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/5/9/a/Google-Mobile-Ads-SDK/7.32.0/Google-Mobile-Ads-SDK.podspec.json) and attempt to lint the file locally. It fails with 1.6.0.beta.1, but succeeds with 1.5.3.

**Comment by dnkoutso** [comment]
Fixed already https://github.com/CocoaPods/CocoaPods/pull/8026 and dup of https://github.com/CocoaPods/CocoaPods/issues/7872

You may use Bundler to point to a SHA to use this until beta 2 ships

**Comment by dnkoutso** [comment]
If it does not work for you with this fix I can re-open.

**Comment by jlew-nevo** [comment]
I don't know if this is a manifestation of the same thing or not, but using `pod 'Appboy-iOS-SDK','3.12.0'` fails to link the Pods project, complaining about CoreTelephony.framework which is mentioned in the `weak_framework` section of the podspec.  I added a `post_install` script to add this back in `OTHER_LDFLAGS`, which seems to clear it up.

**Comment by Pitsko** [comment]
I have the same issue with pod 'Appboy-iOS-SDK','3.12.0'

**Comment by wellbranding** [comment]
@jlew-nevo  can you provide more details about post_install script? We have found a problem that if our framework uses other vendored frameweroks as weak_frameworks and does not specify them in cocoapods then the pod, which gets integrated is missing dependencies and does not build... This is really strange... I can't provide weak_frameworks in Podspec because I get an error that framework is missing.
@Pitsko have you solved it?

**Comment by jlew-nevo** [comment]
@wellbranding sure, looks like this:
```
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "Appboy-iOS-SDK"
                # Appboy-iOS-SDK fails to link without the -framework CoreTelephony addition.
                # It specifies CoreTelephony as a "weak_framework" in its podspec, which may not exist in 1.6?
                config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC" -framework CoreTelephony'
            end
        end
    end
end
```

**Comment by wellbranding** [comment]
@jlew-nevo  I thought that I somehow could configure it in podspec without forcing client to use the script.. If you have a moment can you look at our issue and our problem, then building a framework and adding optional frameworks to that framework..
https://github.com/CocoaPods/CocoaPods/issues/8594#issuecomment-472118886
