### ISSUE TITLE
Add prepare_command in Podfile

### ISSUE THREAD

**Issue by Freeway1979** [CocoaPods/CocoaPods#8053]
# Report

## What did you do?

ℹ  I want to add some prepared commands in Podfile before all pods executed.

## What did you expect to happen?

ℹ I want to copy some files in Podfile when `pod install`

## What happened instead?

  I only found `pre_install` to do something before pod project generated.

 My prepared commands are executed after Pods downloaded.It's not what I want.

## CocoaPods Environment

```
### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /Users/andyliu/.rvm/rubies/ruby-2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6bccc3c5f3392e2f5b41d11e0ea7e68479993e61
```

### Installation Source

```
Executable Path: /Users/andyliu/.rvm/rubies/ruby-2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'myapp' do
    pre_install do |installer|
        system('echo "hello,world"')
        system("/bin/sh ../ios/build_proto.sh")
    end
    pod 'grpclib',  :path => "."
    post_install do |installer|
        system('echo "well done"')
      end
end
```

**Comment by dnkoutso** [comment]
The `Podfile` is a ruby file you can execute any code you want directly there. A `pre_install` hook should also do what you want and I do not think `pre_install` can exist inside of a `target` definition.

I am sorry with the given information I cannot seem a path towards an enhancement here and I am pretty sure you can accomplish what you want already.

I will preemptively close this issue and re-open it if we can find a path towards an enhancement here. It is also best to ask this in StackOverflow under `cocoapods` tag.

**Comment by Freeway1979** [comment]
@dnkoutso Thanks for you comments. Yes,I moved `system('echo "hello,world"')` out of target, it works.
  Great.
