### ISSUE TITLE
The fetch-cocoapods-repo-from-s3.sh script delivers the wrong repo.

### ISSUE THREAD

**Issue by wilimitis** [CocoaPods/CocoaPods#8054]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run
```
curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
```

## What did you expect to happen?

After running the script, `MASTER_REPO_LOCATION` (a variable defined within the script) seems like it should contain a repo clone of https://github.com/CocoaPods/Specs/tree/master, so that subsequent calls to `pod install` may be able to locate dependencies as required.

(Maybe this is why dependencies cannot be found, but they _can_ be found when running `pod setup && pod install`)

## What happened instead?

After running the script, `MASTER_REPO_LOCATION` seems to contain a repo from https://github.com/CocoaPods/Specs.

When I run `pod setup` and then inspect `MASTER_REPO_LOCATION` the expected behavior occurs.

**Comment by dnkoutso** [comment]
@DanToml any ideas here?

**Comment by DanToml** [comment]
@wilimitis The S3 tarball cache is typically up to about 30 minutes stale (depending on current clone rate limiting). Are you seeing any issues outside of being a little bit behind `HEAD`?

**Comment by opfeffer** [comment]
It looks like the tarball is actually referencing the `backz` branch (https://github.com/CocoaPods/Specs/commit/c16d9f421ecb9a597d8a7a604e1d40622fac0eea) which appears to be the new base branch for Cocoapods/Specs?

`backz` doesn't appear to contain any specs

**Comment by DanToml** [comment]
I've fixed the CocoaPods/Specs repo configuration to correctly point to the `master` branch again, so the tarball should be correct as of the last update ~20 mins ago.

**Comment by wilimitis** [comment]
Thank you both for responding so quickly! 😄 AFAICT, the script is WAE again.
