### ISSUE TITLE
Can't run Pod Install on windows

### ISSUE THREAD

**Issue by NicWickman** [CocoaPods/CocoaPods#8055]
I am trying to use CocoaPods on Windows to develop a React Native app. At first I was unable to run any commands at all, so I disabled the "cannot run cocoapods as root" function. 

Trying to run any Pod commands now returns the following error:

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/executable.rb:111:in `block in which!': [!] Unable to locate the executable `git` (Pod::Informative)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/executable.rb:110:in `tap'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/executable.rb:110:in `which!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/executable.rb:133:in `capture_command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:116:in `git_version'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:49:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
        from C:/Ruby24-x64/bin/pod:23:in `load'
        from C:/Ruby24-x64/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
you need to install `git` as the error message clearly says.

**Comment by NicWickman** [comment]
Thank you for your help. Git is installed. 

$ git --version
git version 2.8.1.windows.1

**Comment by ilikesomething** [comment]
exactly the same issue here, and git is working in CLI, and i use it since years...

**Comment by rfitz123** [comment]
I am still having the issue: 

![cantfindbash](https://user-images.githubusercontent.com/54483846/72673122-f4060600-3a33-11ea-84dd-675f150c4a11.PNG)

Git and curl are both on the PATH.
Any ideas?

**Comment by ennahid** [comment]
the problem is in the PATH of the machine

[command]"C:\Program Files\Git\bin" - is missing

**Comment by daniele777** [comment]
C:\Users\Dani>pod - version
Traceback (most recent call last):
        31: from C:/Ruby26-x64/bin/pod:23:in `<main>'
        30: from C:/Ruby26-x64/bin/pod:23:in `load'
        29: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.0/bin/pod:36:in `<top (required)>'
        28: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        27: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods.rb:17:in `<top (required)>'
        25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods.rb:75:in `<module:Pod>'
        24: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        23: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
        21: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        20: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/sources_manager.rb:5:in `<top (required)>'
        18: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
        15: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:15:in `<top (required)>'
        12: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:8:in `<top (required)>'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `<module:Curl>'
         7: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:99:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not op (LoadError)libcurl': Impossibile trovare il modulo specificato.
.
Could not open library 'libcurl.dll': Impossibile trovare il modulo specificato.
.
Could not open library 'libcurl.so.4': Impossibile trovare il modulo specificato.
.
Could not open library 'libcurl.so.4.dll': Impossibile trovare il modulo specificato.
i have this problem ..path it's ok

**Comment by daniele777** [comment]
same problem path is ok !!! help

**Comment by susan007** [comment]
PS C:\myapp\ios> pod install
Traceback (most recent call last):
        31: from C:/Ruby27-x64/bin/pod:23:in `<main>'
        30: from C:/Ruby27-x64/bin/pod:23:in `load'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/bin/pod:36:in `<top (required)>'
        28: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        27: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        26: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods.rb:17:in `<top (required)>'
        25: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods.rb:75:in `<module:Pod>'
        24: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        23: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        22: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/core_overrides.rb:1:in `<top (required)>'
        21: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        20: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.1/lib/cocoapods/sources_manager.rb:5:in `<top (required)>'
        18: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        17: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
        15: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        14: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon.rb:15:in `<top (required)>'
        12: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        11: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon/curl.rb:8:in `<top (required)>'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `<module:Curl>'
         6: from C:/Ruby27-x64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:99:in `map'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/ffi-1.12.2-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'libcurl': �Ҳ���ָ����ģ�顣\r (LoadError)

.
Could not open library 'libcurl.dll': �Ҳ���ָ����ģ�顣\r
.
Could not open library 'libcurl.so.4': �Ҳ���ָ����ģ�顣\r
.
Could not open library 'libcurl.so.4.dll': �Ҳ���ָ����ģ�顣\r

**Comment by MatthieuFereyre** [comment]
See : https://stackoverflow.com/a/54520887

**Comment by Kevinscki** [comment]
> rfitz123
`C:\git\ollamaGUI>pod install
Analyzing dependencies
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/CocoaPods-version.yml Response: SSL peer certificate or SSH remote key was not OK`
How did you even reach the download stage, im stuck on an SSL error
