### ISSUE TITLE
pod not generating page on CocoaPods.org (GDTMobSDK)

### ISSUE THREAD

**Issue by nimomeng** [CocoaPods/CocoaPods#8056]
[GDTMobSDK](https://cocoapods.org/pods/GDTMobSDK) don't generate CocoaPods.org page. 😞
And each time I click search result(GDTMobSDK) on Cocoapods.org, it will redirect to website.

Please have a look: https://cocoapods.org/pods/GDTMobSDK
Many thanks! 😃

**Comment by dnkoutso** [comment]
Hello there, thanks for the issue.

We are trying to keep things as organized as possible, can you please file the issue here instead https://github.com/CocoaPods/blog.cocoapods.org?

I am going to preemptively close this for now.

**Comment by nimomeng** [comment]
@dnkoutso Got it, moved.
Thx.
