### ISSUE TITLE
pod install make some pods disappear in FRAMEWORK_SEARCH_PATHS inside the xcconfig file

### ISSUE THREAD

**Issue by fans3210** [CocoaPods/CocoaPods#8057]
# Report

## What did you do?
Run 'pod install'

## What did you expect to happen?
project should compile successfully

## What happened instead?
Error: ld: symbol(s) not found for architecture arm64
Attached screenshot:
<img width="969" alt="screenshot 2018-08-29 17 13 54" src="https://user-images.githubusercontent.com/6023208/44778369-5a745500-abaf-11e8-9da7-a493eae033bb.png">
 
From the screenshot you can see that there are totally 11 pods that have problem: cryptoswift, awss3...etc

I started to debug and found that after pod install, those pods disappeared in the framework search paths inside the xcconfig file as shown below: 
<img width="968" alt="screenshot 2018-08-29 17 12 21" src="https://user-images.githubusercontent.com/6023208/44778513-bf2faf80-abaf-11e8-9492-3c1011df6c2a.png">

The issue was resolved after I revert the changes of the lines shown in the above screenshot

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10L232m)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 83a523af04677d539f200326e4d8e4f788f2cd61
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
use_frameworks!

def app_ui_pods
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'MBProgressHUD'
    pod 'SVProgressHUD'
    pod 'IQKeyboardManagerSwift'
    pod 'Texture'
    pod 'M13ProgressSuite'
    pod 'JVFloatLabeledTextField'
    pod 'SlackTextViewController', :git => 'https://github.com/fans3210/SlackTextViewController.git', :branch => 'develop'
    pod 'SKPhotoBrowser', :git => 'https://github.com/fans3210/SKPhotoBrowser.git', :branch => 'develop'
    pod 'BadgeSwift'
#    pod 'DLRadioButton'

end

def app_util_pods
    pod 'Swinject'
    pod 'PromiseKit'
    pod 'RxSwift'
    pod 'ReSwift'
#    pod 'Fabric'
#    pod 'Crashlytics'
    pod 'IGListKit'
end

def ext_pods
    pod 'PromiseKit'
    pod 'RxSwift'
    pod 'ReSwift'
    pod 'SnapKit'
    pod 'Swinject'
    pod 'MBProgressHUD'
    pod 'FileKit'
    pod 'Locksmith'
end

target 'OnePipMSO' do
    
    app_ui_pods
    app_util_pods
    
end

target 'OnePipMSOStaging' do
    
    app_ui_pods
    app_util_pods
    
end


target 'OnePipMSOTesting' do
    app_ui_pods
    app_util_pods
end

target 'OnePipCore' do
    pod 'Swinject'
    pod 'SwiftyBeaver'
    pod 'PromiseKit'
    pod 'RxSwift'
    pod 'ReSwift'
    pod 'Locksmith'
    pod 'Alamofire-SwiftyJSON'
    pod 'Kingfisher'
    pod 'AWSS3'
    pod 'AWSAppSync', :git => 'https://github.com/fans3210/aws-mobile-appsync-sdk-ios.git', :branch => 'develop'
    pod 'FileKit'
    pod 'CryptoSwift'
    pod 'Repeat'
end

target 'OnePipMsoShare' do
    ext_pods
end

target 'OnePipMsoShareStaging' do
    ext_pods
end


target 'OnePipCoreTests' do
    
    # Pods for testing
end


target 'OnePipMSOTests' do

# Pods for testing
    
end




swift_4_1_pod_targets = ['SnapKit', 'FileKit', 'SKPhotoBrowser', 'BadgeSwift']

post_install do | installer |
    installer.pods_project.targets.each do |target|
        if swift_4_1_pod_targets.include?(target.name)
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end
```

**Comment by dnkoutso** [comment]
This might be intentional because of they are static libs? do you have a sample you can upload please?

**Comment by fans3210** [comment]
@dnkoutso I don't think they are static libraries. They are in my framework target.  I'm trying to reproduce it in a new project.

**Comment by fans3210** [comment]
Hi @dnkoutso , I cannot reproduce it every time. But below is the project that I reproduced the issue: clang: error: linker command failed with exit code 1 (use -v to see invocation). Although it's not exactly the same issue in my app. 
using cocoapod 1.6.0 beta
1. create a new swift project using xcode10 beta 6
2. pod init and pod install
3. in podfile add Alamofire, Alamofire-SwiftyJSON and SwifyJSON
4. create a new framework target and create a class 
5. import the framework target in app's vc
6, run podinstall again

Below is the project I faced such error. I cannot reproduce it every time. The 'Order' of the steps of creating the project is important).
Another thing about warning message, after fixed the warnings make the project able to compile again even though I revert back my changes in project settings and run pod install again.

<img width="1658" alt="screenshot 2018-08-31 09 32 31" src="https://user-images.githubusercontent.com/6023208/44887858-d500ba00-ad00-11e8-8a04-666ee50be453.png">


Below is the link of a simple sample project:
https://www.dropbox.com/s/dur3vdn88w7oyp0/TestPodIssue2.zip?dl=0

Please let me know if the sample project doesn't provide sufficient information. Thanks!

**Comment by fans3210** [comment]
@dnkoutso I kind of find the cause of the issue. I imported a framework pod which is used by my own framework target. As you can see, I use pod 'FileKit' in my framework target, but in my main app, I still can use 'import Filekit' without error. It only happens when I compile the app. 
The solution is to add pod 'FileKit' in my app target too. I think Xcode 9 doesn't complain about this issue before. But Xcode 10 will.

**Comment by fans3210** [comment]
But although can complile right now. When running the app, still facing image not found:

dyld: Library not loaded: @rpath/AWSAppSync.framework/AWSAppSync
  Referenced from: /private/var/containers/Bundle/Application/50422660-D7A5-4639-B78D-BA6A6322D14C/OPX.app/Frameworks/OnePipCore.framework/OnePipCore
  Reason: image not found

**Comment by fans3210** [comment]
basic solution for image not found are the same, add the pod which gives me issue to the main app target in podfile. The strange thing is: I never import or use those frameworks in app target directly. What I would do is just to import my framework which contains those pods.

**Comment by kristofferarl** [comment]
We have the same issue with "image not found" on Xcode 10
Any updates on this?

**Comment by fans3210** [comment]
@kristofferarl . My issue happens on special frameworks. If I see image not found. The err also give us about which framework reports me such issue for image not found.

For my case, I face this issue in 'Alamofire'. I have a framework target for my frameworks which is the only target that used 'Alamofire' as dependency. Eg: I have a class LoginApi.swift in my framework target which handles network request logics. In my main app target I have a UserLoginManager.swift class which wraps the loginapi.swift and coredatastack.swift and other decencies.
I Xcode 9 and before, in my UserLoginManager.swift, I don't need to import Alamofire directly, I just need to import my framework and let the framework's LoginApi to handle the network logics. But now I find in Xcode10, I have to add "pod 'Alamofire'" in both my framework target and app target, otherwise I will face this image not found error. I don't know whether is the correct solution but this fixed my problem
