### ISSUE TITLE
ENOTEMPTY - Directory not empty

### ISSUE THREAD

**Issue by itumeleng-mabote** [CocoaPods/CocoaPods#8060]
Hi

This is just me trying to help out anyone that encounters this problem 

This all started out with what seemed like a corrupted library. After clearing all caches for xcode and cocoapods, I was left with this error

Errno::ENOTEMPTY - Directory not empty @ dir_s_rmdir - /Users/itumelengmabote/Library/Caches/CocoaPods/Pods
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:1337:in `rmdir'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:1337:in `block in remove_dir1'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:1348:in `platform_support'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:1336:in `remove_dir1'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:1329:in `remove'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:691:in `block in remove_entry'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:1386:in `ensure in postorder_traverse'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:1386:in `postorder_traverse'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:689:in `remove_entry'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:557:in `block in rm_r'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:553:in `each'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/fileutils.rb:553:in `rm_r'
/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/pathname.rb:589:in `rmtree'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader/cache.rb:83:in `ensure_matching_version'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader/cache.rb:22:in `initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:41:in `new'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/downloader.rb:41:in `download'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/pod_source_installer.rb:121:in `download_source'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:374:in `install_source_of_pod'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:339:in `block (2 levels) in install_pod_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in `titled_section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:338:in `block in install_pod_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:321:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:321:in `install_pod_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:164:in `block in download_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:162:in `download_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:117:in `install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

I finally solved this issue by manually deleting Library/Caches/CocoaPods/

**Comment by dnkoutso** [comment]
The issue appears resolved. I dont see an action item here?
