### ISSUE TITLE
Cannot install Pods.

### ISSUE THREAD

**Issue by atlbananas** [CocoaPods/CocoaPods#8062]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Pod Install.

## What did you expect to happen?

ℹInstall Pod depedencies.  I've tried two different CocoaPods.

## What happened instead?

ℹ I get the error "Unable to add a source with url 'https://github.com/CocoaPods/Specs.git' named 'master-1'  You can try adding it manually in ~/.cocoapods/repos' or via 'pod repo add'."

I have deleted cocoapods and reinstall several times.  I've navigated to ~.cocoapods/repos and run git clone https://github.com/CocoaPods/Specs.git master.  After doing that, I get the message that the master repo is not a git repo.  I've deleted the cache.  I tried adding a source and calling it master-1, but it then gives me the error stating master-2.  It's like an endless cycle of fail.  Seems that this just does not work.

## CocoaPods Environment

ℹ ### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin14]
    RubyGems : 2.7.7
        Host : Mac OS X 10.10.5 (14F2511)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e580bdaef6756ff4ff408c4c81b904d6f736a807
```

### Installation Source

```
Executable Path: /Users/nsarpong/.rvm/rubies/ruby-2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'pod-test' do
    use_frameworks!

pod 'SVProgressHUD'

  target 'pod-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pod-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


## Project that demonstrates the issue

ℹJust an issue trying to install Pods.

**Comment by dnkoutso** [comment]
Please use `--verbose` also maybe it will provide more context.

If you do `git clone https://github.com/CocoaPods/Specs.git master` and then `pod repo add be pod repo add master ttps://github.com/CocoaPods/Specs.git`

**Comment by dnkoutso** [comment]
I am saying use `--verbose` for `pod setup`.

**Comment by atlbananas** [comment]
Nanas-MacBook-Pro:repos nsarpong$ pod setup --verbose


Setting up CocoaPods master repo

  $ /usr/bin/git remote set-url origin
https://github.com/CocoaPods/Specs.git

  $ /usr/bin/git checkout master

  Already on 'master'

  Your branch is up-to-date with 'origin/master'.

env: illegal option -- u

usage: env [-i] [name=value ...] [utility [argument ...]]

[!] The `master` repo is not a git repo.


/Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-core-1.5.3/lib/cocoapods-core/source/manager.rb:318:in
`git_source_named'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/sources_manager.rb:80:in
`update'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/setup.rb:63:in
`update_master_repo'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/setup.rb:25:in
`block in run'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in
`section'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/setup.rb:21:in
`run'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in
`run'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in
`run'

/Users/nsarpong/.rvm/gems/ruby-2.5.1@global/gems/cocoapods-1.5.3/bin/pod:55:in
`<top (required)>'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/bin/pod:23:in `load'

/Users/nsarpong/.rvm/rubies/ruby-2.5.1/bin/pod:23:in `<main>'

/Users/nsarpong/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'

/Users/nsarpong/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in
`<main>'

**Comment by dnkoutso** [comment]
```
env: illegal option -- u

usage: env [-i] [name=value ...] [utility [argument ...]]
```

can you please update your `git` version via `brew upgrade git`.

that is your issue.

**Comment by dnkoutso** [comment]
And then `rm -rf ~/.cocoapods/repos/master` just in case and re-run `pod setup`

**Comment by atlbananas** [comment]
Still getting the same error.  When I orginally tried upgrading, I got
the following error "Git not installed".  I installed git. Tried upgrading
and got the message, "git 2.18.0 already installed."  Tried installing Pod
and got the same error:

[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git`
named `master-1`.

You can try adding it manually in `~/.cocoapods/repos` or via `pod repo
add`.

Is this the current/correct version of git?

**Comment by dnkoutso** [comment]
Oh sorry I think it might be an old version of macOS instead. You are on 10.10 I recommend upgrading this.

**Comment by atlbananas** [comment]
Is there another way to add Pods manually?  I cannot upgrade macOS due to
audio hardware requirements.

**Comment by dnkoutso** [comment]
Nope the master repo unfortunately is required (it's something tracked here to remove).

Best bet is to fork CocoaPods and remove the code that deals with master repo but you won't be able to consumer open source libraries.
