### ISSUE TITLE
Cannot find Microblink.bundle in your main bundle

### ISSUE THREAD

**Issue by Jovial-Ionnex** [CocoaPods/CocoaPods#8065]
Dear MicroBlink,

I have get this error when Integration without CocoaPods in my framework.
`Cannot find Microblink.bundle in your main bundle, reason: Please make sure you have Microblink.bundle in the copy resources build phase of your app.`

The reason no MicroBlink.bundle found as i have put the bundle in my framework project instead in my app project.
Below is my code in framework to look for MicroBlink.bundle:
`      let path = Bundle(for: type(of: self)).bundlePath + "/MicroBlink.bundle"
        MBMicroblinkApp.instance().resourcesBundle = Bundle(path: path)!
        MBMicroblinkSDK.sharedInstance().setLicenseKey()
`
ℹ Error hit when MBMicroblinkSDK.sharedInstance().setLicenseKey() want to set the licenseKey as  MicroBlink.framework in app try to look for the MicroBlink.bundle in app.

ℹ May I know how to set the MicroBlink.framework in app to look for the MicroBlink.bundle in framework?

Thanks,
Jovial

**Comment by amorde** [comment]
Hello,

This looks like an issue with a specific third party library, and not something related to CocoaPods itself. I'd recommend submitting an issue to the Pod author, possibly here? https://github.com/BlinkID/blinkid-ios
