### ISSUE TITLE
CocoaPods mistakenly removed 32 bit support on my framework

### ISSUE THREAD

**Issue by nsquangexception** [CocoaPods/CocoaPods#8072]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ I created a Swift framework that support i386, x86_64, armv7, arm64. 
I can use it normally by dragging it to "embedded binaries" and enable "always embed Swift standard library".
I zipped the framework, created `podspec` file for it and integrate with CocoaPods to other project.

## What did you expect to happen?

ℹ The project should be able to run on all architectures like manual integration.

## What happened instead?

ℹ I can run integrated project normally on 64-bit iPhones (physical & simulator) but not 32-bit. Xcode project cannot find Swift declaration for any classes or functions from my framework.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d1445d64d70673c0aa8b45eb4526a03e10ed35a6
               MY_COMPANY_REPO - https://git.my-company-domain.com/scm/~my.username/host-podspec.git @ fbc0908fff56ebb7a9a6821f075fa64e41ded53b
               mycompanydomain-scm-eco-core-ios-specs - https://gitpub.my-company-domain.com/scm/eco/core-ios-specs.git @ 44a77411180f467ae7977084d1a992193f87aaed
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://git.my-company-domain.com/scm/~my.username/host-podspec.git'

target 'MyAppTarget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'MyCompanySDK'

end
```

**Comment by dnkoutso** [comment]
Need a sample app please to debug this.
