### ISSUE TITLE
After Mac OS update , CocoaPod cannot working

### ISSUE THREAD

**Issue by JimChi** [CocoaPods/CocoaPods#8074]
hey there ,

I have some problem , After Mac OS update 10.13.6 version , i use pods  build library it working , but i cannot import something inside , before update it working . 

Thx

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
