### ISSUE TITLE
Pod install installs pod from wrong spec repository

### ISSUE THREAD

**Issue by SebastianBoldt** [CocoaPods/CocoaPods#8079]
We created a private pod called **ListKit** und put it into our private cocoapods repository.

The Cocoapod Documentation says:
"The order of the sources is relevant. CocoaPods will use the highest version of a Pod of the first source which includes the Pod (regardless whether other sources have a higher version)."

We included both spec sources on top of the Podfile like so: (our own repo is the first on the list)

```
source 'ssh://git@stash.mycompany:7999/customspec.git'
source 'https://github.com/CocoaPods/Specs.git'
```

For some reason **ListKit** of the Cocoapods Master Spec Repository will be used if i run 
```pod install```
instead of the **ListKit** from our private spec repository.

Is this intentional or a bug?

It would be great if someone could help me out. 

I use Cocoapods Version: 1.5.3
on Mac OS 10.13.2

**Comment by paulb777** [comment]
Is there an existing `Podfile.lock`? You might need `pod update` instead of `pod install`.

**Comment by SebastianBoldt** [comment]
Yes, i tried that out. I also removed the whole pods folder + Podfile.lock but it also did not work.

**Comment by dnkoutso** [comment]
I believe this is a dup of https://github.com/CocoaPods/CocoaPods/issues/7947. PR was made here https://github.com/CocoaPods/Molinillo/pull/98 but it was believed better fixed in CocoaPods not Molinillo.

Closing as dup @SebastianBoldt let me know if this is different and I can re-open.
