### ISSUE TITLE
Pod still shows in search after deleting it from trunk

### ISSUE THREAD

**Issue by hassanvfx** [CocoaPods/CocoaPods#8080]
# Report

## What did you do?

I accidentally created a Podspec using a lowercase character 'kron' instead of 'Kron' (First pod mistake!)

I tried to delete the Pod but it still shows in the search

```
[~] ->  pod trunk delete kron 1.2.3
WARNING: It is generally considered bad behavior to remove versions of a Pod that others are depending on!
Please consider using the `deprecate` command instead.
Are you sure you want to delete this Pod version?
> yes

[!] The version is already deleted.
[~] ->
```

```
[~] ->  pod trunk me
  - Name:     Eonfluxor
  - Email:    eonfluxor@gmail.com
  - Since:    September 9th, 13:39
  - Pods:
    - kron
    - Delayed
  - Sessions:
    - September 9th, 13:39 - January 16th, 2019 13:40. IP: 47.33.86.138
    Description: Macbook SGI
[~] ->  pod trunk info kron

kron
    - Versions:
      - 1.2.2 (2018-09-09 20:41:20 UTC)
    - Owners:
      - Eonfluxor <eonfluxor@gmail.com>
```

## What did you expect to happen?

ℹ I originally expected to be able to resubmit the Pod after deleting it, but further research shows that this is not possible?

## What happened instead?

The pod is still showing in the search

<img width="801" alt="screen shot 2018-09-10 at 1 40 04 pm" src="https://user-images.githubusercontent.com/425926/45323110-12cec100-b4ff-11e8-9f47-304f9d4f7fa1.png">

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /Users/hassanvfx/.rvm/rubies/ruby-2.4.0/lib
Repositories : Delayed - git@github.com:eonfluxor/delayed.git @ ea0f32dcbb6e6ee059f993be76985d0328864e9f
               eonfluxor - https://github.com/eonfluxor/kron @ b51097ed861b0914e797aa28597aaf6ae9c8da04
               eonfluxor-1 - https://github.com/eonfluxor/delayed @ ea0f32dcbb6e6ee059f993be76985d0328864e9f
               HourGlass - git@github.com:hassanvfx/hourglass.git @ 2e50d10fa9f364737146c45ed312c79b475d894f
               master - https://github.com/CocoaPods/Specs.git @ a5fb8f68f082f1e5e15ad95c3c70e4f9d9e220ba
```

### Installation Source

```
Executable Path: /Users/hassanvfx/.rvm/rubies/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

This is the repo

https://cocoapods.org/pods/kron

* I tried deleting it from trunk, and the command did succed but the pod is still available. 
* After researching on similar issues I learned that there is no way to "free" the name even after deleting the pod from trunk.
*  It's still a problem because I created another Pod with a different name (Delayed) but potential users will be confused using the deleted pod that still shows in the search

**Comment by hassanvfx** [comment]
Thanks guys  this is my first time writing here and I want to say THANKS and praise your great work with cocoapods!

It would be great if you can help me removing "kron" from the search.

**Comment by dnkoutso** [comment]
@hassanvfx thanks for the report! Can I ask you to close this and file it under https://github.com/CocoaPods/cocoapods-search repo instead?

**Comment by hassanvfx** [comment]
yes of course @dnkoutso

**Comment by hassanvfx** [comment]
Reposted here:  https://github.com/CocoaPods/cocoapods-search/issues/27
