### ISSUE TITLE
how to use pods to install the same library with different version

### ISSUE THREAD

**Issue by chalkrender** [CocoaPods/CocoaPods#8085]
i want to pod same Library with different version
just like this example, but it does not work
target 'TagDemo' do
       pod 'RxSwift', '~> 4.2.0'
end

target 'TagTest' do
        pod 'RxSwift', '~> 4.1.2'
end

**Comment by dnkoutso** [comment]
This is currently not possible and there are no plans to support it at this time.

**Comment by chalkrender** [comment]
thans to answer 
I have a problem that there is a library with  different version and different functions 
i need to embed this library 
Could you offer me some advice？

**Comment by dnkoutso** [comment]
Update your targets to support the same version?

I apologize but in terms of keeping issues open I am going to close this. I recommend asking StackOverflow under `cocoapods` tag.

Since we have no plans on supporting this currently going to close.
