### ISSUE TITLE
Build errors when using C++ in headers

### ISSUE THREAD

**Issue by trungvinh1991** [CocoaPods/CocoaPods#8088]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod lib lint MyLibrary.podspec`

I have an issue when linting headers file include C++. 

> #include memory
> #include string
> #include vector
> #include stdexcept

I get the following error
`PathToMyHeader:31:10: fatal error: 'memory' file not found`
I think 'string', 'vector', 'stdexpept' will be the same errors
## What did you expect to happen?

I expected it to lint successfully.

## What happened instead?

I think C++ compiles errors

## CocoaPods Environment
<img width="1204" alt="screen shot 2018-09-12 at 5 50 50 pm" src="https://user-images.githubusercontent.com/8643020/45420477-70583e80-b6b4-11e8-88de-f9be2018cbad.png">
s.source_files = 'Pod/Classes/Include/*'
=> Here is path of header files

After linted podspec
<img width="1838" alt="screen shot 2018-09-12 at 5 41 39 pm" src="https://user-images.githubusercontent.com/8643020/45420155-9df0b800-b6b3-11e8-9640-71fb26216778.png">

**Comment by dnkoutso** [comment]
Hey there, thanks for the report. It is best to ask these questions in StackOverflow under `cocoapods` tag.

Currently this does not appear to be an issue with the library nor is there a sample app attached demonstrating the issue.

Please use `--no-clean` option in `lint` and inspect the generated project manually.

**Comment by paulb777** [comment]
https://stackoverflow.com/questions/52293771/cocoapod-podspec-linting-errors-when-using-c-in-header-files
