### ISSUE TITLE
:local pod development on a project that includes libraries

### ISSUE THREAD

**Issue by mattyohe** [CocoaPods/CocoaPods#809]
When writing a Podspec for a library, it has been the case that I would write something like:

```
Pod::Spec.new do |s|
⋮
s.xcconfig  =  { 'LIBRARY_SEARCH_PATHS' => '"$(PODS_ROOT)/MySDK/"' }
⋮
end
```

However, if I want to develop this as a :local pod, PODS_ROOT is not going to point to the correct library path.

Is there a solution to deal with this?

If not, would it be possible to have a PODS_ROOT-like variable that has knowledge of the pod being local, and thus pointing to the correct local pod location?

**Comment by malhal** [comment]
A side effect of vendored_frameworks is now the framework is also embedded in the app bundle. What if you don't want that? e.g. if you just want to link because the framework will already installed in the users Frameworks folder on the mac or device.

**Comment by keeshux** [comment]
@malhal `frameworks` should suit your use-case.
