### ISSUE TITLE
Error 500 installing new pod

### ISSUE THREAD

**Issue by Vortec4800** [CocoaPods/CocoaPods#8093]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Added the FBAudienceNetwork:

`pod 'FBAudienceNetwork'`

then run 'pod install'

## What did you expect to happen?

Install new FBAudienceNetwork pod

## What happened instead?

An error occurs:

```$ pod install
Analyzing dependencies
Downloading dependencies
Using AFNetworking (3.2.0)
Using Appirater (2.3.1)
Using Bolts (1.9.0)
Using ChimpKit (3.1.1)
Using CocoaSoundCloudAPI (1.0.2)
Using CocoaSoundCloudUI (1.0.9)
Installing FBAudienceNetwork (5.0.0)

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/tz/7_rrgmx110z_3m1vdm79_7sh0000gn/T/d20180913-1514-10oz5o7/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.0.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 500 
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G2307)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3457f42f40427ede8e185780a162420a0c5319c9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Platform', :git => "git@bitbucket.org:Vortec4800/Platform.git", :commit => 'e086953'
  pod 'AFNetworking', '~> 3.1'
  pod 'SVProgressHUD', '~> 1.1'
  pod 'CocoaSoundCloudAPI', '~> 1.0.2'
  pod 'CocoaSoundCloudUI', '~> 1.0.9'
  pod 'NSData+Base64', '~> 1.0.0'
  pod 'RevMob-Goonbee', '~> 8.1'
  pod 'Google-Mobile-Ads-SDK', '~> 7.0'
  pod 'Flurry-iOS-SDK', '~> 8.3'
  pod 'Appirater', '~> 2.3'
  pod 'TwitterKit', '~> 3.2'
  pod 'FBSDKShareKit', '~> 4.28'
  pod 'ChimpKit', '~> 3.1'
  pod 'IQKeyboardManager'
  pod 'FBAudienceNetwork'

end
```

## Project that demonstrates the issue

Will provide if necessary.

## Other info

I first thought this was a problem with the Facebook server returning an error 500, so I opened a support ticket with them. They said they were unable to reproduce this error, and had me run this command:

`curl -vvv -o a.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.0.0.zip`

Which did run successfully. I've tried this on multiple computers from multiple locations (different networks, etc) over the course of several days and the error always occurs.

**Comment by dnkoutso** [comment]
```
The Gemfile's dependencies are satisfied
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork (4.99.3)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

Worked for me.

Sorry I do not believe this is a CocoaPods issue. This appears to be an internal server error on the source that hosts the zip file.

**Comment by Vortec4800** [comment]
Well the weird part is if you run the curl command on the machine that this doesn't work on, it succeeds, but when Cocoapods runs the curl command it fails as error 500. What could cause that? How can I debug that more?

**Comment by Vortec4800** [comment]
I'll add to this. I changed my Podfile to specify the version 4.99.3 and that did succeed, all is good. However when trying to install the latest version, 5.0.0, it fails. Can you try installing the latest version on your end and see if that makes a difference?

**Comment by dnkoutso** [comment]
Let me see

**Comment by dnkoutso** [comment]
@Vortec4800 worked for me with 5.0.0 as well. Here's the command CocoaPods uses:
https://github.com/CocoaPods/cocoapods-downloader/blob/master/lib/cocoapods-downloader/http.rb#L11
You can toy around with your configuration and change the flags in `curl` to maybe narrow down the issue? If so we can potentially make a PR to fix this in CocoaPods if its an edge case.

```
Analyzing dependencies
Downloading dependencies
Installing FBAudienceNetwork 5.0.0 (was 4.99.3)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

**Comment by Vortec4800** [comment]
Okay. I ran this command, and it shows the error 500. Let me look into the flags and see if I can figure out which one is causing the problem.

`curl -f -L -o file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.0.0.zip --create-dirs --netrc-optional --retry 2`

**Comment by Vortec4800** [comment]
Thanks for your help, I've been able to narrow down the command and see that it is failing for the 5.0.0 zip and not the 4.99.3 zip and it does indeed appear to be a problem on their server. I've sent this info to them to take a look at. If I find anything that needs to be modified in Cocoapods I'll post back, but for now I'll leave it in the hands of Facebook.

**Comment by dnkoutso** [comment]
Thank you @Vortec4800 !
