### ISSUE TITLE
Question: what exactly does `pod lib lint` do?

### ISSUE THREAD

**Issue by noamtamim** [CocoaPods/CocoaPods#8098]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Please explain what it does -- I haven't found any explanation. Among other things, it seems to call xcodebuild a few times (my pod has subspecs) -- but what is the algorithm?

**Comment by dnkoutso** [comment]
Linting is the process of which you pod is validated to ensure it can be consumed by others before it gets published. This includes running tests and build for `RELEASE` configuration. 

There is no algorithm, all subspecs will be built with `xcodebuild` separately to ensure they can be consumed separately and for all platforms your pod supports.

Going to close as there is no action here, can follow up more on this thread even if its closed.

**Comment by dnkoutso** [comment]
Tiny bit here https://guides.cocoapods.org/making/specs-and-specs-repo.html

**Comment by noamtamim** [comment]
Thanks.
I saw this page, it didn't have all the information. However, it does tell me to run `spec lint` before `trunk push`, even though it seems that `trunk push` also does the linting.

**Comment by noamtamim** [comment]
@dnkoutso that makes total sense. However, if it performs a `spec lint` internally, why do you instruct developers to perform `spec lint` beforehand? Isn't that a waste of time?

> How do I update an existing Pod?
> 
>     1. Create your Podspec as described above.
>     2. Run pod spec lint to check for errors.
>     3. Submit your Podspec to Trunk with pod trunk push NAME.podspec

As an aside, `spec lint` could save a hash of all the files that it built, allowing `trunk push` to just scan the files and make sure nothing has changed.

But that's an optimization. My real concern is, why should I lint before pushing, if push will lint again anyway?

**Comment by orta** [comment]
Happy to take a PR adding that @noamtamim 👍
