### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by yuzhidu** [CocoaPods/CocoaPods#8101]
I don't known who you are! I hope you can help me.
According to company regulations, i must delete my repository！(It's PXNetwork)
Due to it use cocopods, and I don't know how to delete Spec file in https://github.com/CocoaPods/Specs/tree/e122b8b9b53322d60da4d55fd4e10c477ae4fcb7/Specs/c/4/b/PXNetwork
Please Delete it!! I'm a chinese, my english is poor, i hope you can understand!

my email:luyiyun798@gmail.com

**Comment by dnkoutso** [comment]
Please use https://guides.cocoapods.org/terminal/commands.html#pod_trunk_delete to delete a pod.

Ask StackOverflow under `cocoapods` tag for further questions about this command.
