### ISSUE TITLE
Xcode 10 doesn't apply development pod changes while building

### ISSUE THREAD

**Issue by kdurant35** [CocoaPods/CocoaPods#8102]
When i change my development pod and run Example project, it doesn't apply last changes inside dev pods while closing and opening Xcode or cleaning project.

Before you start, are you using the latest CocoaPods release?
YES

Not an issue about the CocoaPods command line app? NO

Using CocoaPods 1.5.3 and Xcode 10 10A255

**Comment by piotrczurak** [comment]
I'm experiencing the same issue. To add to confusion, new methods added pods are visible and can be called in main project, but they never execute.
Only thing that seems to help is running `pod deintegrate && pod install` after each change in development pods.

**Comment by kdurant35** [comment]
@piotrczurak try clean project before running with shift + command + k or from product menu. it works for me but annoying, so i downloaded Xcode 9.4.1.

**Comment by dnkoutso** [comment]
You are correct this is an issue. But it is a dup here https://github.com/CocoaPods/CocoaPods/issues/8073 and its an Xcode problem so far.

I am going to close this as a dup. 

Workaround is to either remove the input/output paths or use old build system.

**Comment by peterng014** [comment]
Change System Build to Legacy in workspace setting works for me

**Comment by mohshbool** [comment]
> Change System Build to Legacy in workspace setting works for me

that causes a compilation error for swift files

**Comment by acecilia** [comment]
workaround: https://github.com/CocoaPods/CocoaPods/issues/8073#issuecomment-628092129
