### ISSUE TITLE
Error Using FileManager/FileHandle from own CocoaPod library with Photo Gallery images

### ISSUE THREAD

**Issue by ballard** [CocoaPods/CocoaPods#8103]
Using CocoaPods 1.5.3

Using Xcode 9

I have a class function in my own cocoapod framework:

    public class FilesTools {
        class func getSizeOfFile(_ path: String) -> UInt64? {
            do {
                let fileAttributes = try FileManager.default.attributesOfItem(atPath: path)
                let fileSize = fileAttributes[.size]
                guard let size = fileSize as? NSNumber else { return nil }
                let int64Size = size.uint64Value
                return int64Size
            } catch {
                print("error: \(error.localizedDescription)")
                return nil
            }
        }
    }

Then I use it on simulator it's OK, but I have an error on the real device. I get error of kind:

*"error: Error Domain=NSCocoaErrorDomain Code=257 "The file “IMG_0001.JPG” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/var/mobile/Media/DCIM/100APPLE/IMG_0001.JPG, NSUnderlyingError=0x1c0842d00 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}"*

**If I call this method from the application code, not from framework code it works fine.**

Of course I asking for permission by NSPhotoLibraryUsageDescription in my plist file.

I'm getting file URL via such function using PHAsset:

    asset.requestContentEditingInput(with: nil) { (input, info) in
            guard let url = input?.fullSizeImageURL else {
                return
            }
         ...
         FilesTools.getSizeOfFile(url.path)
         ...
    }

So I have access problem only using my own cocoapod framework...

Is this CocoaPod's or Apple problem?

**Comment by dnkoutso** [comment]
Thanks for the report but It's hard to tell nor is this report following our issue template. 

This does not appear to be a CocoaPods problem and its best to ask StackOverflow under `cocoapods` tag.

If you are certain this is a CocoaPods issue please upload a sample app and I will re-open this issue.
