### ISSUE TITLE
No way to install beta versions of cocoapods through Homebrew

### ISSUE THREAD

**Issue by davecom** [CocoaPods/CocoaPods#8107]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
brew install --devel cocoapods
```

## What did you expect to happen?

Get CocoaPods 1.6.0 beta 1 through homebrew.

## What happened instead?

```
Error: No devel block is defined for cocoapods
```

## CocoaPods Environment

```
### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9a688d408a931212ae72f0a9150b0a1b0a793467
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

N/A

**Comment by segiddins** [comment]
I guess you can add that block to the home brew definition?

**Comment by lixiaodongdg** [comment]
[sudo] gem install cocoapods --pre

**Comment by lixiaodongdg** [comment]
Yes, I also found this problem, but I can pass  $ [sudo] gem install cocoapods --pre

**Comment by mxcl** [comment]
Why did you open this? Do it yourself! Homebrew is designed so anyone can edit the formula. Burdening CocoaPods developers with this is just selfish.

**Comment by davecom** [comment]
> Burdening CocoaPods developers with this is just selfish.

Hi @mxcl,
Your language is very strong. Calling someone "selfish" for opening an issue when they are just trying to point out something to be helpful is not a way to encourage them to contribute. I don't really know how cocoapods works and I don't really know how homebrew works. As an outsider, I simply figured that the same people who maintain cocoapods are probably the people who maintain cocoapods in homebrew. I'm probably wrong. You may be a great developer, but your tone here sucks.
Best,
Dave

**Comment by mxcl** [comment]
Fair point, I apologize. I just have sympathy for the maintainers here who already have plenty to do.

**Comment by amorde** [comment]
Here's the current formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cocoapods.rb

Here's a guide to creating Homebrew formulae: https://docs.brew.sh/Formula-Cookbook

I _believe_ this is maintained by the community but I'm honestly not sure. I use Homebrew myself but am not familiar with how the formula are updated. It looks like there's [a command you can run](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) to create a PR automagically.

If someone who is already familiar with this stuff would be willing to contribute it would be very much appreciated :) Ideally there would be some sort of option to install the beta, but by default the production version would be installed.

**Comment by mxcl** [comment]
K, well, because I feel like a douche, I'm adding this, one moment.

**Comment by mxcl** [comment]
https://github.com/Homebrew/homebrew-core/pull/32829

**Comment by mxcl** [comment]
This is now merged. Ticket can be closed?

I'll check the docs for this repo to see if it makes sense to add this anywhere.

**Comment by amorde** [comment]
Added in https://github.com/Homebrew/homebrew-core/pull/32829 - thanks again @mxcl!

You can install the beta version with `brew install cocoapods --devel`

**Comment by mxcl** [comment]
> I'll check the docs for this repo to see if it makes sense to add this anywhere

brew doesn’t seem to be mentioned anywhere, so not changing any CocoaPods docs.

**Comment by amorde** [comment]
Thanks for checking, I think you are right that it isn't mentioned

**Comment by anohren** [comment]
I don't know anything about Homebrew so I don't know if this is supposed to still work, but I thought I'd add that I got the same error as OP just in case it is. Had to use `gem install cocoapods –pre` instead.

**Comment by amorde** [comment]
@anohren this was added by @mxcl, so you should be able to `brew install cocoapods --devel`

**Comment by mxcl** [comment]
The brew core team removed all `--devel` specs from the main tap a few days ago, so my work was for nothing. Your only option is CocoaPods.

**Comment by anohren** [comment]
That explains why it was so hard to find a brew equivalent. Thanks for the update 👍

**Comment by amorde** [comment]
Ah, bummer. Thank you @mxcl for the info on that
