### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by yuzhidu** [CocoaPods/CocoaPods#8108]
Reference https://github.com/CocoaPods/CocoaPods/issues/8101
I use **pod trunk delete NAME VERSION** , and success delete master branch spec files, but it have a branch **Tree** still exist.
![snip20180919_1](https://user-images.githubusercontent.com/8081777/45734680-f6760700-bc17-11e8-8556-431f8b0beae7.png)
![snip20180919_2](https://user-images.githubusercontent.com/8081777/45734681-f70e9d80-bc17-11e8-86c9-ff53a23af3ca.png)

**Comment by dnkoutso** [comment]
The commit clearly shows you deleted version 1.1.0. You need to do this for every version.

https://github.com/CocoaPods/Specs/commit/b793d19fae6b44b00491a6851aa70fc08d0c78b1

Please only use this issue even if its closed to ask for updates instead of re-opening new issues over and over.

**Comment by yuzhidu** [comment]
I apologize for create a new issues! I thought it would be useless if it closed.

I delete every version,the difference between the two is that
**tree/e122b8b9b53322d60da4d55fd4e10c477ae4fcb7/Specs/c/4/b/PXNetwork**,
another is master **tree/master/Specs/c/4/b**, I think **e122b8b9b53322d60da4d55fd4e10c477ae4fcb7** is a tag,but **pod trunk delete NAME VERSION** do not work.
