### ISSUE TITLE
xcodebuild:  error: unexpected duplicate task: CopyStringsFile

### ISSUE THREAD

**Issue by osdudutz** [CocoaPods/CocoaPods#8112]
I am using Xcode 10 the latest full version, CocoaPods 1.5.3 and using Legacy Build System

I run pod install and it's working fine after building and running the app.
But I have this error message after 'pod spec lint'
**xcodebuild:  error: unexpected duplicate task: CopyStringsFile**
regarding localization.

I already tried CocoaPods beta 1.6.0 it's not working too.

What should I do?

**Comment by dnkoutso** [comment]
Its very hard to tell with your given information. It is downright impossible to debug this.

Please use StackOverflow under `cocoapods` tag to for these questions or include a sample app clearly demonstrating the issue.
