### ISSUE TITLE
Private pod put into .zip misses .framework itself on pod install

### ISSUE THREAD

**Issue by vyacheslavvorona** [CocoaPods/CocoaPods#8113]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

- I have a framework archived into .zip along with the LICENSE file. It is uploaded as a release attachment on GitHub.
- I have a private Spec repo with a structure duplicating the one from [this example](https://guides.cocoapods.org/making/private-cocoapods)

Here are my .podspec contents:
```
Pod::Spec.new do |s|
  s.name             = 'FrameworkName'
  s.version          = '1.0.1'
  s.summary          = 'Some framework summary'
  s.description      = 'Framework description'
  s.homepage         = 'homepage url'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'vyacheslavvorona' => 'my@mail.here' }
  s.source           = { :http => 'https://github.com/frameworkname/Specs/releases/download/v1.0.1/FrameworkName.zip' }

  s.ios.deployment_target = '8.0'
  s.swift_version = '3.3'
  s.source_files = 'FrameworkName/Classes/**/*'
  s.dependency 'Alamofire', '~> 4.7.3'
  s.dependency 'AlamofireImage', '~> 3.3'
end
```

My podfile:
```
source 'https://github.com/frameworkname/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'testingPodInstall' do
  use_frameworks!

 pod 'FrameworkName', '~> 1.0.1'

end
```

## What did you do?

```
pod install
```

## What did you expect to happen?

I expected to find `FrameworkName.framework` in `/Pods/FrameworkName`

## What happened instead?

`/Pods/FrameworkName` contains only LICENSE file

`pod install` shows no issues though:

```
skolvan:testingPodInstall voronavyacheslav$ pod install
Analyzing dependencies
Downloading dependencies
Using FrameworkName (1.0.1)
Using Alamofire (4.7.3)
Using AlamofireImage (3.4.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.3 (17D47)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2_1/lib
Repositories : FrameworkName - https://github.com/frameworkname/Specs.git @ 2597b70fd8b925223734b0cdb8ef52ddeab866ec
               frameworkname-1 - https://github.com/frameworkname/Specs.git @ 2597b70fd8b925223734b0cdb8ef52ddeab866ec
               master - https://github.com/CocoaPods/Specs.git @ c674f8b4d22d3253ed48e62173e7073a14b78ce9
```
^^^ this causes some concerns: there are 2 repos related to my framework

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
We cannot debug with the given information. It seems your `.zip` file does not include your framework or the paths in your podspec are not properly pointing to the relative paths from the extract zip file.

Please use StackOverflow under `cocoapods` tag for these problems.

I _will_ re-open this if it ends up being a cocoapods library bug but please upload a sample app demonstrating the issue.
