### ISSUE TITLE
`pod trunk push --quick`? 

### ISSUE THREAD

**Issue by olejnjak** [CocoaPods/CocoaPods#8114]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Hi,

I got a library whose `pod lib lint` runs for a long time due to dependencies which have a long compile time. So on Travis CI it always times out. For that purpose I use there `pod lib lint --quick`.

Now I'd love to run `pod trunk push` when new tag is pushed. But here I don't have an option to run "quick lint". 

Is there a way how to do "quick lint" when running `pod trunk push`?

Thanks

**Comment by orta** [comment]
We want to be certain that the pod will work for clients - allowing people to skip the user-protecting parts of the push feels worrying to me.

**Comment by olejnjak** [comment]
Well then.
