### ISSUE TITLE
`prefPane` wrapper extension target doesn't have copying frameworks build phase

### ISSUE THREAD

**Issue by youknowone** [CocoaPods/CocoaPods#8115]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Create an xcodeproj with prefPane target. (for System Preference)
2. Write a Podfile with framework. (MASShortcut for me)
3. pod install  (`[CP] Copy Pods Resources */` step is expected to be added but it doesn't)
4. Build the prefPane target (MASShortcut.framework is expected to be placed in Frameworks directory of the target but it doesn't)

## What did you expect to happen?

It should work as normal app target.

## What happened instead?

Missing build steps in 3

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G2307)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.18.0
Ruby lib dir : /Users/user/.rbenv/versions/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 643723cb9231f9c3aa6bc5371bafbd9b1d0fc138
```

### Installation Source

```
Executable Path: /Users/user/.rbenv/versions/2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
workspace 'Gureum'

target 'OSX' do
    platform :osx, "10.10"
    project 'Gureum.xcodeproj'
    pod 'cdebug'
    pod 'FoundationExtension', '>= 1.3.1'
    pod 'Fabric'
    pod 'Crashlytics'
end
target 'Preferences' do
    use_frameworks!
    platform :osx, "10.10"
    project 'Gureum.xcodeproj'
    pod 'MASShortcut'
end
target 'PreferencesApp' do
    use_frameworks!
    platform :osx, "10.10"
    project 'Gureum.xcodeproj'
    pod 'MASShortcut'
end
target 'OSXTests' do
    platform :osx, "10.10"
    project 'Gureum.xcodeproj'
    pod 'cdebug'
    pod 'FoundationExtension', '>= 1.3.1'
end

target :'App' do
    platform :ios, "9.0"
    project 'iOS.xcodeproj'
    pod 'FoundationExtension', '>= 1.3.1'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'GoogleMobileAds'
    pod 'GlobalActivityIndicatorView', '>= 0.1.1'
end
target :'iOS' do
    platform :ios, "9.0"
    project 'iOS.xcodeproj'
    pod 'FoundationExtension', '>= 1.3.1'
    pod 'Fabric'
    pod 'Crashlytics'
end
target :'iOSTests' do
    platform :ios, "9.0"
    project 'iOS.xcodeproj'
    pod 'FoundationExtension', '>= 1.3.1'
end
```

## Project that demonstrates the issue

https://github.com/gureum/gureum/commit/2cb4ba00504a5f1201a3f5f2b2786e38a654eb32

**Comment by Crazor** [comment]
@youknowone Did you figure this out? I'm running into the same issue here, prefpane does not get the Framework copied in.

**Comment by youknowone** [comment]
I don't remember the details, but I created an app target and manually copied the result to .perfPane one. I still think this is a bug.

**Comment by Crazor** [comment]
Agreed. That's the solution I came up with yesterday, too. Since my prefpane shares it's dependencies with the embedded app, I manually added the "[CP] Embed Pods Frameworks" phase from the app target to the prefpane target. This works, but only when both targets need the same frameworks.
