### ISSUE TITLE
Consider adding descriptions to GitHub issue labels

### ISSUE THREAD

**Issue by jverkoey** [CocoaPods/CocoaPods#8123]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

 🌈

GitHub [launched support this year for setting descriptions on issue labels](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/). They're an easy way to give additional context to the meaning of a label, and their descriptions are shown when you hover over the labels (helpful for newbies and core team members alike).

Example:

<img width="501" alt="screen shot 2018-09-22 at 10 03 59 pm" src="https://user-images.githubusercontent.com/45670/45920895-b7fc7880-beb3-11e8-9a05-fbd47445495b.png">

**Comment by dnkoutso** [comment]
We already have plenty of labels, not all issues are categorized as it takes time for folks to read and assess which labels to add.

@jverkoey am I missing something? I am going to maybe prematurely close this but I can re-open if you mean something else or I did not understand something correctly.

**Comment by dnkoutso** [comment]
Here's example filters https://github.com/CocoaPods/CocoaPods/issues?q=is%3Aopen+is%3Aissue+label%3Ad1%3Aeasy

**Comment by jverkoey** [comment]
Ah I think you may have thought I was referring to GitHub labels themselves (which I agree there are plenty already!). My original description is referring to the ability to add a description to an individual label. For example: “discussion” might say “The core team needs to discuss this topic further” or “This issue is a discussion”, depending on what the intended meaning is.

**Comment by dnkoutso** [comment]
ah! ok reopening

**Comment by segiddins** [comment]
Can probably take some of the description we have in the guides: https://guides.cocoapods.org/contributing/tickets-handling.html && https://guides.cocoapods.org/contributing/contribute-to-cocoapods.html

**Comment by amorde** [comment]
I did a quick pass over the labels and added some descriptions. Will close this for now but let us know if you have suggestions for improvements 👍
