### ISSUE TITLE
test_spec cannot find parent pod's resource_bundle when using static linking

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#8127]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Add a test_spec for a podspec that contains a resource bundle, then try to run the tests that expect the presence of `ExampleFramework.bundle`. This is project is _not_ using `use_frameworks!`.

```ruby
Pod::Spec.new do |s|
  s.name             = 'ExampleFramework'
  s.resource_bundles = {
    'ExampleFramework' => ['ExampleFramework/**/*.xib',
                        'ExampleFramework/**/*.xcassets']
  }
  s.test_spec 'CedarTests' do |test_spec|
    test_spec.source_files = 'Tests/Cedar/ExampleFrameworkCedarTests/**/*.{h,m,mm}'
    test_spec.dependency 'Cedar'
  end  
end
```

```ruby
pod 'ExampleFramework', :path => './Externals/ExampleFramework', :inhibit_warnings => false, :testspecs => ['CedarTests']
```

```objc
@implementation NSBundle (ExampleFramework)

+ (nullable NSBundle*) exampleFrameworkBundle {
    NSBundle *frameworkBundle = [NSBundle bundleForClass:ExampleFrameworkClass.class];
    NSString *path = [frameworkBundle pathForResource:@"ExampleFramework" ofType:@"bundle"];
    NSAssert(path != nil, @"ExampleFramework.bundle not found!");
    if (!path) {
        return nil;
    }
    NSBundle *bundle = [[NSBundle alloc] initWithPath:path];
    NSAssert(bundle != nil, @"ExampleFramework.bundle not found!");
    return bundle;
}

@end
```
## What did you expect to happen?

Tests that expect the presence of `ExampleFramework.bundle` should be able to load resources from that bundle.

## What happened instead?

The resource bundle is not found. Additionally, when using Xcode 10's build system you cannot recreate the bundle like `test_spec.resource_bundles = ...` because it causes duplicate output errors.

## CocoaPods Environment

Tried both CocoaPods 1.5.3 and CocoaPods 1.6.0-beta1.

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
    RubyGems : 2.6.14.1
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A254a)
         Git : git version 2.19.0
Ruby lib dir : /Users/chrisbal/.rbenv/versions/2.4.4/lib
               master - https://github.com/CocoaPods/Specs.git @ 3d708d2b2eddd63a20d83cb9a8c28f2fbd01926c
```

### Installation Source

```
Executable Path: /Users/chrisbal/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
inhibit_all_warnings!
pod 'ExampleFramework', :path => './Externals/ExampleFramework', :inhibit_warnings => false, :testspecs => ['CedarTests']
```

## Project that demonstrates the issue

I can make a test spec / project if needed.

**Comment by dnkoutso** [comment]
Your report is great, a sample app would help but I think I can try to repro myself in the meantime. If you can get the sample it will speed up the process of debugging this.

**Comment by dnkoutso** [comment]
@chrisballinger isn't that expected though? Static linking means you produce `.a` files and resource bundles are actually copied into the app bundle instead of the `.framework`.

**Comment by dnkoutso** [comment]
The bundle will be copied in the test bundle though and if that does not work then thats a bug.

**Comment by chrisballinger** [comment]
@dnkoutso Thanks for the reply! 

Ya, the `ExampleFramework.bundle` is not copied into the xctest bundle. When using CocoaPods 1.6.0-beta1's unit tests (without app host) its still not copied.

**Comment by dnkoutso** [comment]
Weird it copies the resource bundle for me to the `xctest` bundle.

Can you please upload a sample?

**Comment by dnkoutso** [comment]
@chrisballinger give me until the weekend.

**Comment by chrisballinger** [comment]
@dnkoutso No rush, thanks for looking into it!

**Comment by chrisballinger** [comment]
@dnkoutso It would be great if you could find it because I no longer have access to the original project :(
