### ISSUE TITLE
Embed pod frameworks leads to "multiple commands produce ... " error in Xcode 10 

### ISSUE THREAD

**Issue by LiohAu** [CocoaPods/CocoaPods#8132]
Since I updated Xcode I encounter the following error when using the new build system : 

```
:-1: Multiple commands produce '/.../MyApp.app/Frameworks/SwiftFrameworkPod.framework':
1) Target 'App' has copy command from '/.../Build/Products/Debug-iphoneos/SwiftFrameworkPod.framework' to '/.../Build/Products/Debug-iphoneos/MyApp.app/Frameworks/SwiftFrameworkPod.framework'
2) That command depends on command in Target 'App': script phase “[CP] Embed Pods Frameworks”
```
If I remove the framework from the "Embed frameworks" build phase, the compilation works but I get an undefined symbol error when running the app.
But if I remove the framework from the "input files" / "output files" of the "[CP] Embed pods frameworks" build phase, it works appropriatelly.

So 2 questions : 
1. Is there something that I can set in my podfile to prevent this framework to be added to the "[CP] Embed pods frameworks" build phase
2. Shouldn't the "Embed frameworks" Xcode build phase have the same behavior as the "[CP] Embed pods frameworks" build phase ?

PS : Running on cocoapod 1.6.0.beta.1

**Comment by dnkoutso** [comment]
Embed Frameworks is not a CocoaPods phase. The ones prefixed with `[CP]` are.

This seems so far an improper configuration of your project. 

Please upload a sample app demonstrating the issue its downright impossible to debug this. 

This PR (https://github.com/CocoaPods/CocoaPods/pull/8105) also landed on master and you can use it to disable input/output paths. You shouldn't though because that would slow down incremental builds and my gut feeling is that your project is misconfigured here.

**Comment by LiohAu** [comment]
Ok maybe I have an invalid configuration because even before Xcode 10 I had "random" build errors sometimes that were fixed once I cleaned derived data/build folder.

So could you help me to build a proper podfile for my situation ? Maybe i misunderstood something related to the dependencies management.

Basically here is my configuration : 

My application project includes 2 target for the same .app. 
The 1st one uses Fabric and Crashlytics pods, 2nd one has Calabash as additional pod (an UI automation framework).
In addition to these pods, in this project I have 2 dynamic frameworks (mixing swift and objective-C). The app target needs the 1st one and the latter depends on the 2nd one. And I also have another dynamic framework in another xcode project (but in the same workspace) which is used by the 1st dynamic framework.
Since they are not pods
In these 2 frameworks, I need code that is in another pure Objective-C dynamic framework exposed as a private pod. And in the 2nd framework only, I need 2 other private pods.

And here is the Podfile I currently have : 

`
source 'https://github.com/CocoaPods/Specs.git'
source 'http://...private_pods.../_git/Specs'

workspace 'MyApp'
use_frameworks!

platform :ios, '10.0'

target 'CommonFramework' do
  project 'MyApp/CommonFramework.xcodeproj'
  pod 'MyDatabaseObjCPod'
end

abstract_target "CommonPods" do
  pod 'Fabric'
  pod 'Crashlytics'

  target 'MyApp'
  target 'MyApp-Calabash' do
    pod 'Calabash'
  end
end

target 'SubFrameworkOne' do
  pod 'MyDatabaseObjCPod'
  pod 'MyBLESwiftPod'
  pod 'AnotherObjCAndCppPod', '>= 0.0.0.97'

  target 'SubFrameworkOneTests' do
    inherit! :search_paths
  end

  target 'SubFrameworkTwo' do
    pod 'MyDatabaseObjCPod'
    pod 'MyBLESwiftPod'
    pod 'AnotherObjCAndCppPod'
    inherit! :search_paths
    target 'SubFrameworkTwoTests' do
      inherit! :search_paths
    end

  end

end`

**Comment by dnkoutso** [comment]
Can you please upload it in a sample zip?
