### ISSUE TITLE
Feature Request: Let Private Pods depend on other Private Pods

### ISSUE THREAD

**Issue by knightcode** [CocoaPods/CocoaPods#8133]
* [🌈] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Would it be possible to allow a private dependency in a private pod?

For example if I had a private podspec that I wanted to depend on a private pod called `FooKit`, it'd be nice to do something like:

```
source 'https://github.com/knightcode/FooPods.git'

Pod::Spec.new do |s|
  ...  
  s.dependency 'FooKit'
end
```
where FooKit is defined in the sourced specs repo.

**Comment by amorde** [comment]
Private pods can already depend on other private pods as long as the source is included in the Podfile. Podspecs cannot provide their own sources - this has been discussed before, but it is not currently something that is planned to be implemented.

See previous discussions here:

* #3276
* #4921

**Comment by dnkoutso** [comment]
Correct. Providing sources in podspecs can yield to even more difficult problems if for example the podspec is published in the open source repo but points to private repos.

At this time I am going to close this one as it has already been covered.

**Comment by knightcode** [comment]
I'm able to build the final app with all the pods included, yes. But there's no way you can fix `pod spec lint --private`  and `pod repo push FooPods FooUI.podspec` so that I can at least publish the private pod to my private specs repo?

**Comment by amorde** [comment]
does the `--sources` argument for `lint` and `push` not do what you're trying to do? you can specify private sources to use during lint

**Comment by Amzd** [comment]
I have a test project with a few private pods (all in different sources) and to write the --sources every time I want to do `lint` seems too much work so to do this now I created a .command file for each pod and added the sources in there so I can run lint without worrying about sources. 

![image](https://user-images.githubusercontent.com/17001151/46349226-c84de980-c651-11e8-8571-20766edf7ff9.png)

The script:

```
# The sources from which to pull dependent pods (defaults to https://github.com/CocoaPods/Specs.git).
# Multiple sources must be comma-delimited.
SOURCES=<Set sources here>
ROOT=<Path to folder where podspecs are>
NAME=$(basename -- "$0" .command)
SPECPATH=$ROOT/$NAME.podspec

cd "$(dirname "$0")"
/usr/local/bin/pod lib lint $SPECPATH --sources=$SOURCES
```

This is not as elegant as adding the sources in the podspec like you proposed but it works better than typing them each time.
