### ISSUE TITLE
Generate acknowledgements artifacts per each configuration

### ISSUE THREAD

**Issue by OdNairy** [CocoaPods/CocoaPods#8137]
Since it's possible to separate pods by configuration I would expect CocoaPods to provide acknowledgements files depend on configuration. Currently, my acknowledgements includes debug-only dependencies.
I would expect generation `Pods-Reader-acknowledgements-debug.markdown` and `Pods-Reader-acknowledgements-release.markdown` instead of single `Pods-Reader-acknowledgements.markdown` file.

cocoapods 1.5.3
Xcode 10

**Comment by orta** [comment]
If you'd like something more complex than the default setup, I'd recommend using [cocoapods-acknowledgements](https://github.com/CocoaPods/cocoapods-acknowledgements) instead

**Comment by OdNairy** [comment]
> If you'd like something more complex than the default setup, I'd recommend using [cocoapods-acknowledgements](https://github.com/CocoaPods/cocoapods-acknowledgements) instead

So you don't see room in CocoaPods core for this feature? Or PR with such changes has a chance to be merged in upstream?

**Comment by orta** [comment]
No, personally, we'd always planned to have more nuanced acknowledgements work using the plugin system

**Comment by OdNairy** [comment]
Ok, thanks for fast responses.
