### ISSUE TITLE
error: Multiple commands produce

### ISSUE THREAD

**Issue by hengyizhangcn** [CocoaPods/CocoaPods#8140]
error: Multiple commands produce '/Users/zhy/Library/Developer/Xcode/DerivedData/MerchantAide-byeocklaxwfswwgwftkafwgzlecm/Build/Products/Debug-iphonesimulator/MyFuture.app/Info.plist':
1) Target 'MyFuture' (project 'MerchantAide') has copy command from '/Users/zhy/Documents/github/MyFutureNew/MerchantAideTests/Info.plist' to '/Users/zhy/Library/Developer/Xcode/DerivedData/MerchantAide-byeocklaxwfswwgwftkafwgzlecm/Build/Products/Debug-iphonesimulator/MyFuture.app/Info.plist'
2) Target 'MyFuture' (project 'MerchantAide') has process command with output '/Users/zhy/Library/Developer/Xcode/DerivedData/MerchantAide-byeocklaxwfswwgwftkafwgzlecm/Build/Products/Debug-iphonesimulator/MyFuture.app/Info.plist'

**Comment by dnkoutso** [comment]
Dup of https://github.com/CocoaPods/CocoaPods/issues/8125

Please search for issues prior to filing new ones. Remove `Info.plist` from `s.source_files` your glob is probably matching it.

**Comment by hengyizhangcn** [comment]
NO, NO
The problem isn't exist due to the podspec

**Comment by dnkoutso** [comment]
But it is the same problem in terms of configuring your target. You are shipping an Info.plist as part of your source build phase.

**Comment by hengyizhangcn** [comment]
It's the main project.

**Comment by hengyizhangcn** [comment]
Follow steps just solved my problem:
1.Remove .xcworkspace file
2.Remove Podfile.lock
3.Remove Pods
4.Remove Derive Data
rm -rf ~/Library/Developer/Xcode/DerivedData
5.pod install again
6.Remove info.plist in Targets->Build Phases->Copy Bundle Resources
I don't sure which step can be removed

**Comment by dnkoutso** [comment]
sure that would do :D

**Comment by GurjinderSinghJW** [comment]
After using 
pod spec lint --verbose

I noticed following errors. Please anyone can help here.

 error: Multiple commands produce '/var/folders/m_/6h1x546s4n1c_98qv9z_q71h0000gn/T/CocoaPods-Lint-20200505-39793-xvrtvc-TrackingSdk/Build/Products/Release-iphonesimulator/TrackingSdk/TrackingSdk.framework/Headers/GCDAsyncUdpSocket.h':

    2) Target 'TrackingSdk' (project 'Pods') has copy command from '/var/folders/m_/6h1x546s4n1c_98qv9z_q71h0000gn/T/CocoaPods-Lint-20200505-39793-xvrtvc-TrackingSdk/Pods/TrackingSdk/TookanTracker/TookanTracker/SDK/CocoaAsyncSocket.framework/Headers/GCDAsyncSocket.h' to '/var/folders/m_/6h1x546s4n1c_98qv9z_q71h0000gn/T/CocoaPods-Lint-20200505-39793-xvrtvc-TrackingSdk/Build/Products/Release-iphonesimulator/TrackingSdk/TrackingSdk.framework/Headers/GCDAsyncSocket.h'

    error: Multiple commands produce '/var/folders/m_/6h1x546s4n1c_98qv9z_q71h0000gn/T/CocoaPods-Lint-20200505-39793-xvrtvc-TrackingSdk/Build/Products/Release-iphonesimulator/TrackingSdk/TrackingSdk.framework/traffic_startcap.png':

and more..

Thanks!
