### ISSUE TITLE
pod trunk delete podName podVersion not work

### ISSUE THREAD

**Issue by SunnySunning** [CocoaPods/CocoaPods#8142]
I use the '`pod trunk delete WebViewPool 0.1.0`',its work fine,show me its excute success! but after a while, the WebViewPool 0.1.0 **reappear** in the cocoapods index repo,its very distress! whats wrong with the cocoapods index repo,help me!

**Comment by dnkoutso** [comment]
Can you please file this in https://github.com/CocoaPods/cocoapods-trunk instead?

**Comment by SunnySunning** [comment]
> Can you please file this in https://github.com/CocoaPods/cocoapods-trunk instead?

ok，I close this one！
