### ISSUE TITLE
Cleaning of a pod very slow and pointless, and using :clean => false makes it worse

### ISSUE THREAD

**Issue by djrtl** [CocoaPods/CocoaPods#8143]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈 

# Report

## What did you do?

`pod install` with a Podfile that contains a dependency to a "big" pod (with a lot of files), such as Boost.

## What did you expect to happen?

Well, to take the appropriate amount of time for each step.

## What happened instead?

Everything seems to take more or less the time it should take, except that the call to `clean_pod_sources` (installer.rb) gets stuck for longer than anything else while cleaning that big pod mentioned above.

It's quite annoying because not only does it take long, in most cases it does nothing, because all the contents of the pod are actually used, so nothing gets deleted in the end.

Checking the CocoaPods code I can see that I can disable cleaning with option `:clean => false` when calling `install!`. However this for some reason also disables completely the cache while fetching pods, so in the end -- while indeed the cleaning stage doesn't happen -- the whole process of installing takes way longer.

### Stack                                    
                                                    
```                                                
   CocoaPods : 1.5.3                            
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.6                          
        Host : Mac OS X 10.13.5 (17F77)
       Xcode : 9.3 (9E145)             
         Git : git version 2.15.1 (Apple Git-101)                                
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_2/lib
Repositories : ...
```                               
                                      
### Installation Source
                                                                                                                                                    
```
Executable Path: /Users/atme/.gem/ruby/2.5.0/bin/pod                
```
                                        
### Plugins                
                                                 
```
cocoapods-art         : 0.9.5              
cocoapods-deintegrate : 1.0.2                           
cocoapods-plugins     : 1.0.0                                   
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0                           
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

install! 'cocoapods', :deterministic_uuids => false

target 'testpod' do
  pod 'boost'
end
```

## Project that demonstrates the issue

Any project, even a completely empty one, as soon as you put something like `pod 'boost'` in it.

**Comment by amorde** [comment]
> Checking the CocoaPods code I can see that I can disable cleaning with option :clean => false when calling install!. However this for some reason also disables completely the cache while fetching pods, so in the end -- while indeed the cleaning stage doesn't happen -- the whole process of installing takes way longer.

It looks like this would be relatively easy to change, but I am not familiar with the reasoning behind disabling the download cache when `:clean` is `false`. Here's where that is set:

https://github.com/CocoaPods/CocoaPods/blob/1fe4659a9201572df3587899941812756f2e0050/lib/cocoapods/installer.rb#L398

@segiddins I believe you implemented the installation options, any insights on what the impact would be of allowing the cache when `:clean => false`?

**Comment by segiddins** [comment]
> However this for some reason also disables completely the cache while fetching pods

That's because we only cache the cleaned version of a pod, so that we're not storing unnecessary files (like a `.git` directory)

**Comment by amorde** [comment]
Ah, that makes sense. At the very least this could be documented better.

I do wish there was a way for `:clean` to not disable caching but I'm not sure it's worth the added complexity of having to re-clean when pulling from the cache.
