### ISSUE TITLE
Access to 1.6.0-beta via ruby?

### ISSUE THREAD

**Issue by bpollock-vida** [CocoaPods/CocoaPods#8144]
Can we get access to 1.6.0-beta version via ruby gem? 

I would like to get the fixes for the RxCocoa dependency cycles without having to custom install. Seems relevant now that Xcode 10 is GM and 1.6.0 has been in beta for over 30 days.

**Comment by amorde** [comment]
Hi @bpollock-vida 

You can install the 1.6.0.beta.1 with: `[sudo] gem install cocoapods --pre`, which I believe is what you're asking. If you are requesting that we release 1.6.0, we don't have any timelines on releases.

Going to go ahead and close this but can continue to discuss here if desire

**Comment by bpollock-vida** [comment]
@amorde Thanks! I didn't see it in the gem list and didn't know about --pre.
