### ISSUE TITLE
No email received for pod trunk register

### ISSUE THREAD

**Issue by Tulleb** [CocoaPods/CocoaPods#8145]
Hey team, thanks for your work.

I don't receive any email from `pod trunk register guillaume@bellut.com 'Guillaume Bellut'`. Am I in a blacklist or anything?

**Comment by Tulleb** [comment]
I already checked my junks. I am waiting for like 30mns now. Maybe I have to wait a bit longer...

**Comment by Tulleb** [comment]
Still no mail 😔
I did the command twice yesterday.

**Comment by Tulleb** [comment]
Also posted here: https://github.com/CocoaPods/cocoapods-trunk/issues/114

**Comment by dnkoutso** [comment]
Fixed in CocoaPods/cocoapods-trunk#114
