### ISSUE TITLE
Pod linter does not take into account pod versions

### ISSUE THREAD

**Issue by MartinMoizard** [CocoaPods/CocoaPods#8147]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod lint

## What did you expect to happen?

I expect the linter to use the dependencies (and the good versions) I specified in my Podfile

## What happened instead?

Instead, the linter installed the latest version on my dependencies, without caring of the specified version in the Podfile.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : blbl-pod-specs - ssh://git@git.blbl.cr/iphone/pod-specs.git @ fd265792f7563042f83d315b2971e52d536bb8cb
               master - https://github.com/CocoaPods/Specs.git @ 34ec60e491bb6b8ee6b780927aa2fcfe6741bcf7
```

### Installation Source

```
Executable Path: /Users/m.moizard/.rvm/gems/ruby-2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Public repo specs
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'Pixar' do
  use_frameworks!

  pod 'JTAppleCalendar', :path => '../JTAppleCalendar'

end
```

## More details

In my Podfile, 'JTAppleCalendar' points to a local folder. When linting in verbose mode, I see the following:
```
-> Installing JTAppleCalendar (7.1.6)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/patchthecode/JTAppleCalendar.git
```

I would expect the linter to use the local folder '../JTAppleCalendar'.

**Comment by dnkoutso** [comment]
`pod lint` does not take into consideration your `Podfile.` Lint is used to ensure that your `podspec` can be compiled with everything it defines (source files, dependencies, resources, etc.).

If `lint` passes it means that it can be consumed by others successfully and therefore it means you can publish your podspec to the master repo or your private repo.

You should specify the version of dependencies you want exactly in your podspec.

Closing as this is not a CocoaPods issue as it stands. I will re-open if we do identify this is a CocoaPods library issue.

**Comment by dnkoutso** [comment]
Also, pointing to a local path inside a `podspec` is not supported since podspecs can be published and therefore local paths would not match a consumers directory structure.
