### ISSUE TITLE
Don't show a warning about using HTTP sources from localhost

### ISSUE THREAD

**Issue by Corrob** [CocoaPods/CocoaPods#8156]
My team does some testing with pods that are hosted locally. However, we see the warning:

The URL (`<localhost_url>`) doesn't use the encrypted HTTPs protocol. It is crucial for Pods to be transferred over a secure protocol to protect your users from man-in-the-middle attacks. This will be an error in future releases. Please update the URL to use https.

Can update this check to be alright with HTTP when the host is localhost. I don't think we have to worry about man-in-the-middle attacks in this case, and needing to use HTTPS adds complications for testing.

Thanks!

**Comment by Corrob** [comment]
Thanks for the fast response! Yes, this is only for local testing purposes.

If it was as easy as adding https to the URL, that would be great. Unfortunately, getting a local server to support HTTPS requires jumping through some hoops: https://stackoverflow.com/questions/43677457/how-to-create-a-https-server-on-localhost.

**Comment by dnkoutso** [comment]
@Corrob for pods consumed locally the source is not cloned or accessed therefore you should be OK to change this.

You will only be able to consume the pod with `pod 'MyPod', :path => '/path/to/file.podspec'` which as I understand you do.

**Comment by Corrob** [comment]
This is probably a weird setup, but we have some general infrastructure for testing binary pods that are served through a local server.

We test it with a Podfile like:
```
source 'http://localhost:<port>/<path>/.git'
pod '<pod_under_test>'
```

**Comment by segiddins** [comment]
That sounds reasonable to me

**Comment by dnkoutso** [comment]
@Corrob should be fairly easy to make a PR to add this. I've marked it as such.

**Comment by dnkoutso** [comment]
Accidental close.
