### ISSUE TITLE
Image not found when running after pod install

### ISSUE THREAD

**Issue by AaronBratcher** [CocoaPods/CocoaPods#8164]
I downloaded a project at `https://github.com/ContactAtOnce/iOS-Messaging-SDK` Followed the instructions in the Sample Apps/Swift folder to install the dependencies.

Ran the project and got an Image not found error. Checking the destination reveals the framework in question does exist.

I contacted Apple and they said it's an issue with CocoaPods.

**Comment by dnkoutso** [comment]
Sorry this report is insufficient to understand the problem and issue. Please use the issue template to file the issue and provide a sample app demonstrating the problem.

Alternatively, from the description you gave I recommend using StackOverflow under `cocoapods` tag instead.

Going to preemptively close, until more information is provided.
