### ISSUE TITLE
"Image not found" error when running .xcworkspace after pod install

### ISSUE THREAD

**Issue by AaronLBratcher** [CocoaPods/CocoaPods#8166]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I downloaded a project from `https://github.com/ContactAtOnce/iOS-Messaging-SDK` and ran pod install in the Sample Apps/Swift directory.

## What did you expect to happen?

For .xcworkspace to be created that would allow me to run the sample app in simulator.

## What happened instead?

Running the resulting .xcworkspace in the simulator causes an 'image not found' error. The source fat binary framework has multiple architectures.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0d67e6d87b60c683f10f584bf82327508c6214d4
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Reference App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ContactAtOnceMessaging', :podspec => '../../ContactAtOnceMessaging/'

end
```

## Project that demonstrates the issue

https://github.com/ContactAtOnce/iOS-Messaging-SDK
Sample Apps/Swift folder

**Comment by dnkoutso** [comment]
I tried and got a different error.
```
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/dnkoutso/Development/ios/iOS-Messaging-SDK/Sample Apps/Swift/Pods/ContactAtOnceMessaging/ContactAtOnceMessaging.framework/Modules/ContactAtOnceMessaging.swiftmodule/x86_64.swiftmodule
```

**Comment by AaronLBratcher** [comment]
Sorry, I was doing this with Xcode 9.3.1 when I got the error. Didn't notice it said Xcode 10.

**Comment by dnkoutso** [comment]
@AaronLBratcher do you mean there is no issue here?

**Comment by dnkoutso** [comment]
Or I should try with Xcode 9.x instead?

**Comment by AaronLBratcher** [comment]
Try Xcode 9.3 instead. Thanks

**Comment by AaronLBratcher** [comment]
Have you been able to replicate the issue?

**Comment by AaronLBratcher** [comment]
Just installed 1.6.0.beta.1 and this is still an issue.

**Comment by AaronLBratcher** [comment]
@dnkoutso I just installed 1.6.0.beta.1 and this is still an issue.
