### ISSUE TITLE
The spec did not pass validation but ** BUILD SUCCEEDED **

### ISSUE THREAD

**Issue by dulacp** [CocoaPods/CocoaPods#817]
When I first wanted to check my `.podspec` file with ran `$ pod spec lint --local` and it failed with this error

``` sh
- ERROR | [OS X] XCODEBUILD >  ../path/to/header.h:9:9: fatal error: 'UIKit/UIKit.h' file not found
- ERROR | [OS X] XCODEBUILD >  ../path/to/another/header.h:9:9: fatal error: 'UIKit/UIKit.h' file not found
```

Which was perfectly normal because I had left `s.osx.deployment_target = '10.7'` in the podspec, so I removed it.

But now, everytime I run `$ pod spec lint --local --verbose` it keeps failing with this ambigious 

``` sh
** BUILD SUCCEEDED **

 -> DPMeterView (0.0.1)
    - ERROR | [OS X] XCODEBUILD >  ../path/to/header.h:9:9: fatal error: 'UIKit/UIKit.h' file not found
    - ERROR | [OS X] XCODEBUILD >  ../path/to/another/header.h:9:9: fatal error: 'UIKit/UIKit.h' file not found

Analyzed 1 podspec.

[!] The spec did not pass validation.
```

How can it both "succeed" and "fail"... is it due to some caching issue ?

**Comment by onmyway133** [comment]
@keith clearing the cache fixes the issue for me. Thanks :+1:
