### ISSUE TITLE
/Headers/XXX/XXXX.modulemap Files in 1.6.0 change to reference, 1.5.0 was the file copy from target support files path

### ISSUE THREAD

**Issue by looseyi** [CocoaPods/CocoaPods#8170]
fatal error: module map file '/Users/Shared/Jenkins/Home/jenkins/workspace/fund-ios-dev/Pods/Headers/Public/JRSwizzle/JRSwizzle.modulemap' not found

**Comment by dnkoutso** [comment]
Sorry we are unable to work with this report. Please fill in the template and provide sample app demonstrating the issue.

It's just not enough information with this. Please re-file it.
