### ISSUE TITLE
Podfile and Podfile.lock should have a path extension rb

### ISSUE THREAD

**Issue by acalism** [CocoaPods/CocoaPods#8171]
ℹ Podfile and Podfile.lock may need a path extension, such as Podfile.rb and Podfile.lock.rb, to make it more suitable for Finder QuickLook and other text editors to color the codes.  

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

**Comment by amorde** [comment]
I like the idea, but this would be a breaking change and we'd need to maintain support for the previous files. It also might mess with developer's SCM history of the file.

For what its worth, other tools such as Fastlane do the same as CocoaPods (ex. `Fastfile`)

**Comment by acalism** [comment]
> I like the idea, but this would be a breaking change and we'd need to maintain support for the previous files. It also might mess with developer's SCM history of the file.
> 
> For what its worth, other tools such as Fastlane do the same as CocoaPods (ex. `Fastfile`)

Podfile.rb first, then Podfile if Podfile.rb does not exist. Maybe fastlane's author dislikes path extension, too; however, path extension is really useful.

**Comment by amorde** [comment]
Ahh I see, so the default could still be `Podfile` but you're suggesting we also search for `Podfile.rb` in case it exists.

That sounds reasonable to me

**Comment by dnkoutso** [comment]
For `Podfile` start here https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/config.rb#L289

`Podfile.lock` would be a bit tougher.

**Comment by amorde** [comment]
`Podfile.lock` is a YAML file, not ruby, so it shouldn't ever have an `.rb` extension

**Comment by orta** [comment]
Yeah, I think **optionally** supporting `Podfile.rb` and `Podfile.lock.yml` is a reasonable idea - the prefix-less-ness convention is a Unix one that CP and all those other tools mentioned continues.

**Comment by dnkoutso** [comment]
The problem is that `Podfile.lock` would need an option to override so it becomes `Podfile.lock.yaml` instead.

Like `install! 'cocoapods', :lockfile_extension => :yaml`

**Comment by orta** [comment]
Argh, yeah, then no, that's not important enough to warrant a config option IMO

**Comment by amorde** [comment]
I agree on the lock file - its not something that should be edited so it doesn't have _as much_ of a need for syntax formatting

**Comment by amorde** [comment]
PRs up for adding the optional `.rb` extension for Podfiles.

For now I think we'll keep this to just the `Podfile` - the lockfile is a bit more complicated

**Comment by amorde** [comment]
`Podfile.rb` is now supported - if you feel the `Podfile.lock.yml` change is worth while, PRs are welcome 👍
