### ISSUE TITLE
Resource file is added to bundle and copied in build phase causing duplicates

### ISSUE THREAD

**Issue by mozeryansky** [CocoaPods/CocoaPods#8173]
In my podspec I have:
```
...
s.test_spec 'Tests' do |test_spec|
    test_spec.source_files = 'Tests/Sources/**/*'
    test_spec.resources = 'Tests/Resources/**/*'
end
... 
```

This causes the image I have in the Resources folder to be added to the 'Copy Bundle Resources' build phase, and CocoaPods adds it to the '[CP] Copy Pods Resources' phase. When building this duplicates the file.

Xcode produces this warning:
`
Showing All Messages
:-1: ignoring duplicated output file: '/Users/michael/Library/Developer/Xcode/DerivedData/MyWorkspace-aeopwxywrxoflbeustfgkzsnmojk/Build/Products/Debug-iphonesimulator/MyTarget.xctest/background.jpg' (in target 'MyTarget')`

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : calthings - git@github.com:Calthings/CTPodSpecs.git @ e0244915947e6543c1de4116c6ad4fb72538fd3b
               master - https://github.com/CocoaPods/Specs.git @ 7ea1295dbee73cd26cc6f685fa0d4d3a78384a7a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Can you please upload a sample app?

**Comment by mozeryansky** [comment]
From building the sample project I've narrowed down the issue. It only happens when I have a custom scheme which builds the test target and the app in the same build. In the attached project there is a scheme called "All" which generates the issue.

[Issue8173.zip](https://github.com/CocoaPods/CocoaPods/files/2466312/Issue8173.zip)

**Comment by SlaunchaMan** [comment]
I’m getting this too, but when I run `pod lib lint` for a library that has a test spec—I’m assuming the created project has the same problem as @mozeryansky’s sample app.

**Comment by mozeryansky** [comment]
@dnkoutso I attached a sample a while back, should that tag be removed?

**Comment by tinder-hemanthprasad** [comment]
@dnkoutso Do you happen to know a workaround for the warnings?

**Comment by mozeryansky** [comment]
@tinder-hemanthprasad I don't remember exactly, but I attempted to remove the warning by using a resource bundle instead and getting that specific bundle. Or you can just rename one of the assets.

In your podspec, something like:
-    test_spec.resources = 'Tests/Resources/**/*'
+    test_spec.resource_bundles = { 'Tests' => 'Tests/Resources/**/*' }

In code:
-        let bundle = Bundle(for: type(of: self))
+        let testsBundleURL = Bundle(for: type(of: self)).url(forResource: "Tests", withExtension: "bundle")!
+        let bundle = Bundle(url: testsBundleURL)!

**Comment by tinder-hemanthprasad** [comment]
@mozeryansky Moving Resources to a bundle caused the following warning. 

Podspec,
`
 test_spec.resource_bundles = { 'Fixtures' => 'Tests/Resources/*' }
`

Warning: 

`
ignoring duplicated output file: '/Users/<******>/Fixtures.bundle' (in target 'Development-Pod-Unit-Tests')
`

**Comment by tinder-hemanthprasad** [comment]
I did this as workaround, 

`
development_pod_unit_test_targets = installer.pods_project.targets.select {|t| t.name.include? "Unit-Tests"  }

def remove_copy_pod_resources_phase(targets)
    targets.each { |t| t.resources_build_phase.files.clear }
end
`

**Comment by paulb777** [comment]
Resources are being copied in both the `Copy Bundle Resources` and `Copy Pods Resources` Phases.

**Comment by nhnam** [comment]
I checked all the answers and I couldn't find the proper way. 
If you don't want the resources to be copied twice ( duplicated), just need to specify the platform

From
`spec.resource_bundles = { ... } `

To
`spec.ios.resource_bundles = { ... }`
