### ISSUE TITLE
How to delete a version of a private repository?

### ISSUE THREAD

**Issue by rakuyoMo** [CocoaPods/CocoaPods#8176]
* [ Y ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk delete MBCStableThirdLib 1.0.1

## What did you expect to happen?

delete 1.0.1 version of MBCStableThirdLib.

## What happened instead?

Have a error : No pod found with the specified name.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin18]
    RubyGems : 2.6.14
        Host : Mac OS X 10.14.1 (18B45d)
       Xcode : 10.0 (10L232m)
         Git : git version 2.18.0
Ruby lib dir : /Users/mbcore/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 981b8faf79164e6eb34f22d7e4e4f8eeef783b2f
               mbcore-iosmodule-mbcspecs - https://git.mbcore.com/iOSModule/MBCSpecs.git @ 03b01d18b2a44deff70ee2101e909da1ac8dec39
               MBCSpecs - git@git.mbcore.com:iOSModule/MBCSpecs.git @ 03b01d18b2a44deff70ee2101e909da1ac8dec39
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

This is a private library of our company, and I submitted it using the 'pod repo push' command when I submitted it.

So what command should I use to remove the version? Does CocoaPods provide this feature?

**Comment by dnkoutso** [comment]
`trunk` is used for the open source repo.

If you manage the git repo yourself you can just open a normal PR on your repo that deletes the podspec.

**Comment by amorde** [comment]
If you have a private spec repo, you can use `pod repo remove [SPEC_NAME]` to remove it from the private repo.

**Comment by rakuyoMo** [comment]
@dnkoutso @amorde But I only want to delete a version, not the entire repository.

pod repo remove [SPEC_NAME] will make me delete the entire repository, which is not what I want

**Comment by amorde** [comment]
ah, apologies, you're right. I guess you have to delete it manually

**Comment by amorde** [comment]
You can delete the folder the file is in (find it with `pod spec which`) and then commit the changes to your spec repo

**Comment by rakuyoMo** [comment]
@amorde 

I am really sorry, I didn't understand what you mean.

I am now trying to delete a version, such as version 1.0.1, version 1.0.2.

What do you mean by a file or folder? Is the .podspec file? Why am I going to delete it?

**Comment by rakuyoMo** [comment]
@amorde 

Do you mean that I want to delete the entire repository and then resubmit it using the latest version?

**Comment by amorde** [comment]
if this is a private repo, the repo should be in `~/.cocoapods/repos/[REPO_NAME]` - you can go there and delete the podspec you are trying to remove

**Comment by rakuyoMo** [comment]
@amorde  Thank you very much for your patience, I successfully deleted the version I want to delete.
