### ISSUE TITLE
Is there a way to install pods for a specific swift version?

### ISSUE THREAD

**Issue by felixsolorzano** [CocoaPods/CocoaPods#8182]
I know that there are many others who have asked similar questions but I can't figure out how to specify that I want to download the lates pod's version that supports a given swift version for example.

Is that possible?

**Comment by dnkoutso** [comment]
I believe you are asking a way to override SWIFT_VERSION even if the author has specified one? 

Here's a quick `post_install` hook that would do it:

```ruby
post_install do |installer|
  target = installer.pods_project.targets.find do |target|
    target.name == 'PODNAME'
  end
  target.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '3.0'
  end    
end
```

In 1.7.0 we are planning on revamping a bit the Swift version management so I am going to close this for now.

It is best to ask this in StackOverflow under `cocoapods` tag. I will preemptively close and re-open this if we can figure out a thing to build here or improve on.

**Comment by felixsolorzano** [comment]
No, I don't want to override the swift version.

I'll explain my problem: I have a project, that project depends on some pods, some of these pods are supporting `swift 4.2`, my project is under `swift 4`, when I run `pod update` all the pods update to their latest version, the pods with support for swift 4.2 don't allow my project to compile after the update.

I would like to know if there's a way to specify what swift version is using my project so that when running `pod update` the pods will update up to the latest version compatible with my project's swift version.

@dnkoutso
