### ISSUE TITLE
New Pod Publish URL is getting redirected to Home page URL.

### ISSUE THREAD

**Issue by pruthvin17** [CocoaPods/CocoaPods#8184]
# Report

## What did you do?
   pod trunk push

## What did you expect to happen?

IBMMobileFirstPlatformFoundationAnalytics should be displayed in cocoapods.
The https://cocoapods.org/pods/IBMMobileFirstPlatformFoundationAnalytics should redirect to cocoapods and the artifact displayed.

 What happened instead?

Pod published Successfully, but URL is getting redirected to Home page URL.
Further the artifact IBMMobileFirstPlatformFoundationAnalytics is not displayed in cocoapods.

(i.e) https://cocoapods.org/pods/IBMMobileFirstPlatformFoundationAnalytics is redirected to the home page url

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 8.1 (8B62)
         Git : git version 2.12.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8b8a264b4f040b9452db0dded01cd4c778af014e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by rob-keepsafe** [comment]
Hi @pruthvin17 👋 Please file that issue here: https://github.com/CocoaPods/trunk.cocoapods.org

This GitHub repo is not for `trunk`

**Comment by amorde** [comment]
Covered by 
https://github.com/CocoaPods/trunk.cocoapods.org/issues/243
