### ISSUE TITLE
mac 10.14 pod install error  Why? !!!!!!! 

### ISSUE THREAD

**Issue by dylwwj123** [CocoaPods/CocoaPods#8185]
![Uploading 2505B7DF-91BD-45B2-8937-65970809AB6E.png…]()

**Comment by dylwwj123** [comment]
pod install

/Library/Ruby/Site/2.3.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'xcodeproj' (< 2.0, >= 1.6.0) among 48 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/wangwenshuai/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /Library/Ruby/Site/2.3.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
	from /Library/Ruby/Site/2.3.0/rubygems/specification.rb:1461:in `each'
	from /Library/Ruby/Site/2.3.0/rubygems/specification.rb:1461:in `activate_dependencies'
	from /Library/Ruby/Site/2.3.0/rubygems/specification.rb:1443:in `activate'
	from /Library/Ruby/Site/2.3.0/rubygems.rb:310:in `block in activate_bin_path'
	from /Library/Ruby/Site/2.3.0/rubygems.rb:309:in `synchronize'
	from /Library/Ruby/Site/2.3.0/rubygems.rb:309:in `activate_bin_path'
	from /usr/local/bin/pod:23:in `<main>'

**Comment by dylwwj123** [comment]
What a mistake it is!! Did anyone meet to solve it? Thank you!!!

**Comment by dnkoutso** [comment]
Missibg xcodeproj ruby gem.
