### ISSUE TITLE
Duplicate Pods targets for dependencies with subspecs

### ISSUE THREAD

**Issue by alex-kovalenko** [CocoaPods/CocoaPods#8190]
* [x ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

We're running into issue when duplicate POD target is being generated when we believe it shouldn't be. We found a workaround (see [Workaround Example)](#workaround-example) in one of the `.podspec` files to avoid the duplicate framework. It seems like there is an issue with internal dependency resolver for default subspecs. Ideally both solutions would produce the same results (single framework) since they appear to be the same.

## What did you do?

I created an iOS project with 2 targets (PODSample and PODNotification) and 3 dependencies (FoundationFramework, FeatureA, FeatureB). 

**Podfile**
```Ruby
use_frameworks!

def foundation
  pod 'FoundationFramework', :path => 'FoundationFramework', :subspecs => [
    'SubA', 'SubB', 'SubC', 'SubD'
  ]
end

target 'PODSample' do
  foundation
  pod 'FeatureA', :path => 'FeatureA'
  pod 'FeatureB', :path => 'FeatureB'
end

target 'PODNotification' do
  foundation
end
```

**FoundationFramework**
```Ruby
Pod::Spec.new do |s|
  s.name = 'FoundationFramework'
  s.version = '1.0.0'
  s.license = ...
  s.homepage = ...
  s.summary = 'Sample framework to demonstrate issues with subspecs.'
  s.authors = ...

  s.source = { :git => 'git://some', :tag => s.version }

  s.ios.deployment_target = '12.0'
  s.default_subspec = ['SubA', 'SubB', 'SubC']

  ############## Subspecs #############

  s.subspec 'SubA' do |ss|
    ss.source_files = 'Source/SubA/**/*.swift'
  end

  s.subspec 'SubB' do |ss|
    ss.source_files = 'Source/SubB/**/*.swift'
  end

  s.subspec 'SubC' do |ss|
    ss.source_files = 'Source/SubC/**/*.swift'
  end

  s.subspec 'SubD' do |ss|
    ss.source_files = 'Source/SubD/**/*.swift'
  end  
end
```

**FeatureA**
```Ruby
Pod::Spec.new do |s|
  s.name = 'FeatureA'
  s.version = '1.0.0'
  s.license = ...
  s.homepage = ...
  s.summary = 'Sample framework to demonstrate issues with subspecs.'
  s.authors = ...

  s.source = { :git => 'git://some', :tag => s.version }

  s.ios.deployment_target = '12.0'

  s.dependency 'FoundationFramework'

  s.source_files = 'Source/**/*.swift'
end
```

**FeatureB**
```Ruby
Pod::Spec.new do |s|
  s.name = 'FeatureB'
  s.version = '1.0.0'
  s.license = ...
  s.homepage = ...
  s.summary = 'Sample framework to demonstrate issues with subspecs.'
  s.authors = ...

  s.source = { :git => 'git://some', :tag => s.version }

  s.ios.deployment_target = '12.0'

  s.source_files = 'Source/**/*.swift'
  s.dependency 'FoundationFramework/SubD'
end
```
## What did you expect to happen?

I expect Pods project to have 5 targets:

- FeatureA
- FeatureB
- FoundationFramework
- Pods-PODNotification
- Pods-PODSample

<img width="575" alt="screen shot 2018-10-15 at 11 32 59 am" src="https://user-images.githubusercontent.com/1427527/46970502-21644700-d06e-11e8-9c44-5207f3fd46df.png">

## What happened instead?

I have Pods project with 6 targets instead:

- FeatureA
- FeatureB
- FoundationFramework-SubA-SubB-SubC-SubD
- FoundationFramework.default-SubD
- Pods-PODNotification
- Pods-PODSample

<img width="576" alt="screen shot 2018-10-15 at 11 27 58 am" src="https://user-images.githubusercontent.com/1427527/46970531-393bcb00-d06e-11e8-8398-c628803cc19c.png">

## Workaround Example

If I change `FeatureA.podspec` to explicitly callout all default_subspec of `FoundationFramework`, then I get expected result in the `Pods` project.

**FrameworkA**
```Ruby
Pod::Spec.new do |s|
  s.name = 'FeatureA'
  s.version = '1.0.0'
  s.license = ...
  s.homepage = ...
  s.summary = 'Sample framework to demonstrate issues with subspecs.'
  s.authors = ...

  s.source = { :git => 'git://some', :tag => s.version }

  s.ios.deployment_target = '12.0'

  # This produces duplicate targets, even though default_subspecs are SubA, SubB, and SubC
  # s.dependency 'FoundationFramework'

  # This works as expected
  s.dependency 'FoundationFramework/SubA'
  s.dependency 'FoundationFramework/SubB'
  s.dependency 'FoundationFramework/SubC'

  s.source_files = 'Source/**/*.swift'
end
```

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.0 (10A254a)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /Users/akova2/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a5cad5fd45db1774d6a6dbbc5eb3f0777c0ee7e1
               nikedev-nike-private-spec - ssh://git@stash.nikedev.com/ncps/nike-private-spec.git @ 9a64bc1214c39eeb87004ee3f69d5d40ee142efd
```

### Installation Source

```
Executable Path: /Users/akova2/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

def foundation
  pod 'FoundationFramework', :path => 'FoundationFramework', :subspecs => [
    'SubA', 'SubB', 'SubC', 'SubD'
  ]
end

target 'PODSample' do
  foundation
  pod 'FeatureA', :path => 'FeatureA'
  pod 'FeatureB', :path => 'FeatureB'
end

target 'PODNotification' do
  foundation
end
```

## Project that demonstrates the issue

https://github.com/alex-kovalenko/duplicate-pod-targets

**Comment by dnkoutso** [comment]
I believe `s.dependency 'FoundationFramework'` also includes the root and therefore CocoaPods will split them into two distinct targets.

Your work around to be the actual correct answer *I think*.

**Comment by alex-kovalenko** [comment]
`FoundationFramework` defines `s.default_subspec = ['SubA', 'SubB', 'SubC']` and I'd expect both 
```Ruby
s.dependency `FoundationFramework/SubA`
s.dependency `FoundationFramework/SubB`
s.dependency `FoundationFramework/SubC`
```
and
```Ruby
s.dependency `FoundationFramework`
```
to be resolved in the same set of subspecs. Isn't it the case?

**Comment by dnkoutso** [comment]
I dont think it is because the second one also brings the root podspec. I will need to double check to be 100% certain.

**Comment by dnkoutso** [comment]
I asked another contributor and said the root is also included as I suspected.

I am starting to think this works as intended actually and your workaround is the correct way to go.

**Comment by alex-kovalenko** [comment]
The workaround is not always applicable since I don't have control over some dependencies and how they define their subspecs.

Is there a way to call out `root` podspec at the app level to avoid duplicate targets? 
```Ruby
def foundation
  pod 'FoundationFramework', :path => 'FoundationFramework', :subspecs => [
    'root', # ???
    'SubA',
    'SubB', 
    'SubC',
    'SubD'
  ]
end
```

Updating `Podfile` to 
```Ruby
def foundation
  pod 'FoundationFramework', :path => 'FoundationFramework'
end
```
results into 2 versions of identical `FoundationFramework` targets as well.

**Comment by dnkoutso** [comment]
I dont think there is a way to specify the root if `:subspecs` is specified.

At its best if this case needs to be supported it would be an enhancement

**Comment by alex-kovalenko** [comment]
Could you explain what "root" podspec means? I've tried adding `Root.swift` file to the `Source` folder of `FoundationFramework`, and I still get 2 identical frameworks. And `FoundationFramework.default-sub4` does not include the `Root.swift` file. 

There is also a bit more to this problem. 
1. It is really hard to track this problem on a big project with lots of dependencies and multiple targets.
2. Both of these targets have the same target location at the 'Archive' stage. It means that if they were different, then one of them could override another and cause serious issues in the app. (Xcode 10 with new build system treats this as an error)

**Comment by dnkoutso** [comment]
For example:
```ruby
Pod::Spec.new do |s|
  s.name = 'FoundationFramework'
  # ... etc
```
There is FoundationFramework which is a spec and its the root. All subspecs are part of the root and they are named `FoundationFramework/SubA` etc. Root spec includes sources, resources which is also everything a subspec does.

CocoaPods will detect what Xcode targets to generate based on what specs each of your app or other pods request.

Most of the times its the same set so its all combined into a single target. For your case two different targets ask for the same pod but different _parts_ ("subspecs") of it therefore they get split so you don't end up with more sources and symbols on a target that did not ask for these parts.

**Comment by alex-kovalenko** [comment]
I was able to specify `Root` dependency at the Podfile level and this helped to fix framework duplication. 

```ruby
def foundation
  pod 'FoundationFramework', :path => 'FoundationFramework'
  pod 'FoundationFramework', :path => 'FoundationFramework', :subspecs => [
    'root', # ???
    'SubA',
    'SubB', 
    'SubC',
    'SubD'
  ]
end
```

Adding `FoundationFramework` without subspecs adds `Root` to the project.
