### ISSUE TITLE
Xcode 10 cannot run unit tests on mixed objc - swift framework project

### ISSUE THREAD

**Issue by MarcoBrescianini** [CocoaPods/CocoaPods#8193]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm developing an iOS framework written in Objc that links against an open source Swift project and an open source Objective-c project. After updating to Xcode 10, unit tests cannot be performed anymore, because of a runtime error. Dynamic Libraries cannot be found and test bundle crashes immediately.

## What did you expect to happen?

Run my unit tests, without any problems. 

## What happened instead?

Test bundle cannot be loaded. Dynamic libraries cannot be found and an exception is thrown right away.
Following an example of what Xcode prints in the console:

```
2018-10-16 14:25:19.708594+0200 xctest[57583:16465752] The bundle “FooBar” couldn’t be loaded. Try reinstalling the bundle.
2018-10-16 14:25:19.709041+0200 xctest[57583:16465752] (dlopen(/Users/marco/Library/Developer/Xcode/DerivedData/FooBar-fhpmnawxvgbjevforarylnxivude/Build/Products/Debug-iphonesimulator/FooBar.xctest/FooBar, 265): Symbol not found: _$SBOWV
  Referenced from: /Users/marco/Library/Developer/Xcode/DerivedData/FooBar-fhpmnawxvgbjevforarylnxivude/Build/Products/Debug-iphonesimulator/FooBar.xctest/Frameworks/Starscream.framework/Starscream
  Expected in: /Users/marco/Library/Developer/Xcode/DerivedData/FooBar-fhpmnawxvgbjevforarylnxivude/Build/Products/Debug-iphonesimulator/FooBar.xctest/Frameworks/libswiftCore.dylib
 in /Users/marco/Library/Developer/Xcode/DerivedData/FooBar-fhpmnawxvgbjevforarylnxivude/Build/Products/Debug-iphonesimulator/FooBar.xctest/Frameworks/Starscream.framework/Starscream)
Program ended with exit code: 83
```

Using Xcode 9.4.1 this error doesn't occur. 
I also noticed that, if swift projects are removed as dependencies from the podfile, unit tests can be run without any problems on Xcode 10.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /Users/marco/.rbenv/versions/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cedd3b8f7d0214e2b6cc7ed1373ece9bf639df86
```

### Installation Source

```
Executable Path: /Users/marco/.rbenv/versions/2.4.2/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'UnitTestIssue' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking'
  pod "PromiseKit", "~> 6.0"

  target 'UnitTestIssueTests' do
    inherit! :search_paths

    pod 'OCHamcrest', '~> 7.1'
    pod 'OCMockito', '~> 5.0'

  end

end
```

## Project that demonstrates the issue

https://github.com/MarcoBrescianini/CocoaPods-UnitTest-Issue.git

**Comment by nhgrif** [comment]
I'm not sure that this problem is caused by Objective-C necessarily.  I've been running into basically an identical error message recently when trying to add a new test target to a project.  The test target is Swift.  The main target is also Swift.  For legacy (and potential future-proofing), the project _does_ have a bridging header in the main target, but it only has a comment at the top, as we've removed any Objective-C imports from this header.

I was browsing through the CocoaPods issues to see if I could find anyone running into identical issues as me.  I've put together my own sample project, in an effort to try recreating my error in a simplified example... but I started running into other errors (from CocoaPods).

Suffice to say, either me or CocoaPods is completely failing when it comes to adding UI test targets to projects.  Because I'm now running into a new set of errors in trying to reproduce my issue, I'm going to open a new issue, but will link it to this one.  My problem is strictly to do with trying to add a new test target to an existing project (which maybe that's how you actually came across this problem).

**Comment by nhgrif** [comment]
https://github.com/CocoaPods/CocoaPods/issues/8269 describes the issues I ran into when trying to reproduce this error in a standalone project.

**Comment by DevWithLove** [comment]
Hey Nick, have you solved this issue? I am having the same problem.

**Comment by DevWithLove** [comment]
This fixed my issue.  In XCode go to File-> Workspace Settings 
Change Build System to "Legacy Build System" in both shared workspace settings and Per-User workspace Settings. 

Refer to :
https://stackoverflow.com/questions/52405272/xcode-10-fails-my-tests-in-simulator-without-any-information-as-to-the-failure

**Comment by MarcoBrescianini** [comment]
@nhgrif I came across this issue as soon as i updated to Xcode 10. I'm working on very large SDK written in Obj-c, that depends on a third party framework written in Swift. Before Xcode 10, everything worked fine.
I didn't investigate too much on the problem, but i found this issue #8139 that describes something that looks like the problem i ran into. I haven't try the proposed solutions, yet. You should take a look there, maybe it'll help you fixing your problem.

@DevWithLove thanks for your suggestion 👍

**Comment by MarcoBrescianini** [comment]
I fixed the problem following [this suggested solution](https://github.com/CocoaPods/CocoaPods/issues/8139#issuecomment-425351960). To me it is also clear that the issue i ran into is not related to CocoaPods.

**Comment by leogiertz** [comment]
An alternate solution that worked for our project was the one found here: https://stackoverflow.com/questions/52566702/xcode-10-uitests-reason-image-not-found/52623506#52623506
