### ISSUE TITLE
Project build fails when there are two pods with same header files names

### ISSUE THREAD

**Issue by anivaros** [CocoaPods/CocoaPods#8194]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Add two pods that have same header files names
2. Run `pod install`
3. Run build

## What did you expect to happen?

Project builds correctly

## What happened instead?

Build fails with error 

## CocoaPods Environment

In CocoaPods 1.4.0 all works fine.
Issue appeared in CocoaPods 1.5.0 - 1.6.0.beta.1

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A391)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : drsk_lib_cocoapods - git@git.digdes.com:DRSK_LIB_Cocoapods.git @ 93ccb4ccf1c0997ac9ba6a70e393115a28133524
               master - https://github.com/CocoaPods/Specs.git @ a74524f3052ffd540f6957fe0aaef079678cd871
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'Cocoapods Bug Test' do
  use_frameworks!
  
  pod 'SSZipArchive', '~> 1.8.1'
  pod 'OpenSSL', :git => 'https://github.com/wzbozon/OpenSSL-Pod'
end
```

## Project that demonstrates the issue

[Cocoapods Bug Test.zip](https://github.com/CocoaPods/CocoaPods/files/2569749/Cocoapods.Bug.Test.zip)

When compiling starts, Xcode compiles SSZipArchive first, but takes file aes.h from second lib (openssl).

**Comment by anivaros** [comment]
Any workaround maybe?

**Comment by anivaros** [comment]
Please, try to reproduce in attached project. 
All imports are inside libs. And it’s not about wrong imports, but about compiling state. Before versions 1.4.0+ all was fine, but since 1.5.0 something went wrong.

**Comment by anivaros** [comment]
In attached test project pod version is 1.5.3 and it's don't builds. If you run pod _1.4.0_ install, it will fix all errors.

**Comment by anivaros** [comment]
That what changed after upgrading form 1.4.0 to 1.5.3:
<img width="905" alt="screenshot 2018-11-11 at 22 54 29" src="https://user-images.githubusercontent.com/873387/48317529-c7bb5200-e604-11e8-952e-40efad8bc108.png">

**Comment by dnkoutso** [comment]
That's not related since its about resources and 1.5.3 optimizes from not including this if its not needed.

**Comment by amorde** [comment]
I would guess the relevant changes would be in the generated `.xcconfig` files for the pod targets

**Comment by anivaros** [comment]
No ideas? :(

**Comment by segiddins** [comment]
Sorry, haven’t yet had a chance to look

**Comment by anivaros** [comment]
Problem fixed by updating to latest version of SSZipArchive. 
In new version files structure changed and `SSZipArchive/aes/` folder were moved to `SSZipArchive/minizip/aes/`. And now all fine 🤷‍♂️
