### ISSUE TITLE
Pod Setup Repo Clone Issue - Mac OS Mojave

### ISSUE THREAD

**Issue by baltameme** [CocoaPods/CocoaPods#8207]
# Report

## What did you do?

I was trying to setup CocoaPods on my Mac machine that runs Mojave OS.

I run pod setup command to download and setup the master repo of cocoapods 

## What happened instead?
I kept receiving the same error down below:

[!] /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress

Cloning into 'master'...
remote: Enumerating objects: 429, done.        
remote: Counting objects: 100% (429/429), done.        
remote: Compressing objects: 100% (381/381), done.        
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A391)
       Xcode :  ()
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
This seems like a network issue so far. I have run it on Mojave and it worked correctly.

Will preemptively close this one and re-open if we can show its an actual CocoaPods issue.
