### ISSUE TITLE
Error `require': cannot load such file -- ruby-prof` when `$PROFILE` is set

### ISSUE THREAD

**Issue by colus001** [CocoaPods/CocoaPods#8209]
* [v] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I newly installed cocoa pod in Mac OSX Mojave 

```
$ sudo gem install cocoapods
```

```
$ pod setup
```

## What did you expect to happen?

Pod setup done properly.

## What happened instead?

```
Traceback (most recent call last):
	4: from /usr/local/bin/pod:23:in `<main>'
	3: from /usr/local/bin/pod:23:in `load'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:39:in `<top (required)>'
	1: from /usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ruby-prof (LoadError)
```

If I install ruby-prof by `$ sudo gem install ruby-prof`, shows following error

```
Traceback (most recent call last):
	2: from /usr/local/bin/pod:23:in `<main>'
	1: from /usr/local/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:49:in `<top (required)>': Unknown profiler format indicated by extension:  (RuntimeError)
```

## CocoaPods Environment

Even pod env shows same error. I'm using Mac OSX Mojave by the way.

**Comment by segiddins** [comment]
What environment variables do you have set?

**Comment by colus001** [comment]
> What environment variables do you have set?

Nothing? You mean gem ? or ruby ?
`$ pod` just shows the error. `$ pod env` also.

**Comment by colus001** [comment]
I tried pod with sudo

```
$ sudo pod
```

Traceback (most recent call last):
	4: from /usr/local/bin/pod:23:in `<main>'
	3: from /usr/local/bin/pod:23:in `load'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/bin/pod:55:in `<top (required)>'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.6.0.beta.2/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
```

It's kind of working but showing permission error (of course).
seems like `ruby-prof` having problem with some sort of sudo and non-sudo permission.

**Comment by colus001** [comment]
I found out that one of my env `$PROFILE` has set to `default`, which makes runtime error in `/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:38`

```
if profile_filename = ENV['PROFILE']
```

**Comment by ThonyFD** [comment]
Ok i going post this, I think it could help someone...

For some reason cocoa pods need our profile file with specific extensions(txt, html or callgrind) I don't know why, my profile file didn't have extension and I was couple hours running in circles trying to solve the error **"Unknown profiler format indicated by extension:"**

Finally I changed my profile file from **"export PROFILE=$HOME/.bash_profile"** to **export PROFILE=$HOME/.bash_profile.txt** and then cocoa pods run ok

Someone konws why it need these especifics extensions?

**Comment by amorde** [comment]
CocoaPods uses that for development purposes - if you have `$PROFILE` set to `profile.html` it will try to make an html profile report of the execution.

We could fix this by renaming the environment variable to something like `COCOAPODS_PROFILE`

**Comment by amorde** [comment]
Going to re-open as I think this can be improved

**Comment by tutipeti** [comment]
Any chance you guys could bump the priority here? It took me quite some time to figure out why our builds were failing and `PROFILE` is a word that can very easily appear in a CI environment.
