### ISSUE TITLE
CoreData build errors with included pod

### ISSUE THREAD

**Issue by AaronLBratcher** [CocoaPods/CocoaPods#8214]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run pod install
Open workspace in Xcode 10 and build for simulator or device

## What did you expect to happen?
Product to build without error

## What happened instead?
Using legacy or new build system, it throws multiple errors for the included pod file:
`Could not determine generated file paths for Core Data code generation`

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7e882bab6d61272d9ade5aeb312d0db096944ffb
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Reference App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ContactAtOnceMessaging', :podspec => '../../ContactAtOnceMessaging/'

end
```

## Project that demonstrates the issue
[Swift.zip](https://github.com/CocoaPods/CocoaPods/files/2503602/Swift.zip)

**Comment by dnkoutso** [comment]
From a quick first look, how is this a CocoaPods issue? It could be a new build system issue or a podspec issue.

**Comment by AaronLBratcher** [comment]
It did work with Xcode 9.3 and version 1.4.0. I think I need to include the parent folder that includes the ConetactAtOnceMessaging.podspec.  This is a link to the entire folder structure: https://www.dropbox.com/s/g7ugmktk0rkm5tf/iOS-Messaging-SDK-master.zip?dl=0

**Comment by dnkoutso** [comment]
@AaronLBratcher I am sorry but this so far does not appear to be a CocoaPods library issue. The xcdatamodeld files are directly added to your project and not coming through CocoaPods. The podspec does not specify anything else besides a vendored framework.

I think it is best to ask StackOverflow for this.

Going to preemptively close but I will re-open if you can show this is indeed a CocoaPods library bug.
