### ISSUE TITLE
No such file or directory @ rb_sysopen - again

### ISSUE THREAD

**Issue by pdarcos** [CocoaPods/CocoaPods#8217]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Mac HighSierra 10.13.6
Node 10.12.0 and npm 6.4.1

## What did you do?

ℹ Please replace these two lines with what you did.  
Ran `pod install`

## What did you expect to happen?
Pod should install

## What happened instead?
 
Following error message: 

pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  pod 'RNGoogleSignin',
    :path => '../node_modules/react-native-google-signin'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-calendar-events',
    :path => '../node_modules/react-native-calendar-events'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen -
/Users/chewie/Documents/Dev/jitsi-meet/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec
/usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/open-uri.rb:37:in `initialize'
/usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/open-uri.rb:37:in `open'
/usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/open-uri.rb:37:in `open'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/podspec_source.rb:19:in
`block in fetch'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in
`titled_section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/podspec_source.rb:11:in
`fetch'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:697:in
`fetch_external_source'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:673:in
`block (2 levels) in fetch_external_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in
`each'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in
`block in fetch_external_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in
`section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:671:in
`fetch_external_sources'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:85:in
`analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in
`analyze'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in
`block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in
`section'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in
`resolve_dependencies'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in
`install!'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in
`run'
/usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in
`run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in
`run'
/usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top
(required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+%2FUsers%2Fchewie%2FDocuments%2FDev%2Fjitsi-meet%2Fnode_modules%2Freact-native%2Fthird-party-podspecs%2FDoubleConversion.podspec&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to
properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new
If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to
properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.3/lib
Repositories :
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```



## Project that demonstrates the issue

https://github.com/jitsi/jitsi-meet/blob/master/doc/mobile.md
jitsi-meet iOS app

**Comment by dnkoutso** [comment]
```/Users/chewie/Documents/Dev/jitsi-meet/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec```

Is this file in the correct place?

**Comment by pdarcos** [comment]
Thanks @dnkoutso 
It is there but it seems to be corrupted.
I'm going to clean out and do an npm install again. Hopefully that fixes it.
I'll keep the thread posted.

**Comment by dnkoutso** [comment]
@pdarcos I am going to preemptively close. I will re-open if we figure out its an actual CocoaPods issue.
