### ISSUE TITLE
pod lib lint - error: "Bundle identifier is missing"

### ISSUE THREAD

**Issue by skytodmoon** [CocoaPods/CocoaPods#8223]
# Report

## What did you do?

I want to create a private pod. I use the "lib lint"

## What did you expect to happen?

pass the validation

## What happened instead?

 -> ONTOCSDK (0.0.1)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  error: Bundle identifier is missing. App doesn't have a bundle identifier for the Release build configuration. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor. (in target 'App')

I tried add "spec.xcconfig = {"PRODUCT_BUNDLE_IDENTIFIER" => "com.medishares.ONTWallet" ,"DEVELOPMENT_TEAM" => "Qi Sun"}" in podspec.
It print:
    - NOTE  | [iOS] xcodebuild:  error: No profiles for 'com.medishares.ONTWallet' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.medishares.ONTWallet'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'App')

I suppose some file is missing, I do not know how to add this in the podspec, and i do not want to add the apple profile in this private pod, any solutions?

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A255)
         Git : git version 2.15.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2d05faa439affa52693799375bdf099e57332ace
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/skytodmoon/ONTOCSDK.git

**Comment by dnkoutso** [comment]
Your podspec is changing the xcconfig of the app:

```ruby
spec.xcconfig = {"PRODUCT_BUNDLE_IDENTIFIER" => "com.medishares.ONTWallet" ,"DEVELOPMENT_TEAM" => "Qi Sun"}
```
Should be
```ruby
spec.pod_target_xcconfig = {"PRODUCT_BUNDLE_IDENTIFIER" => "com.medishares.ONTWallet" ,"DEVELOPMENT_TEAM" => "Qi Sun"}
```

**Comment by dnkoutso** [comment]
It is best to also ask these questions in StackOverflow under `cocoapods` tag
