### ISSUE TITLE
Default `pod lib create` constructs project that doesn't build. "Overlapping accesses ..."

### ISSUE THREAD

**Issue by brianLeeson** [CocoaPods/CocoaPods#8225]
🌈
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. `pod lib create NAME`
2. Hit "enter" to accept all default values
3. In xcode, built newly made project

## What did you expect to happen?

Project would build successfully.

## What happened instead?

Project did not build successfully.
Specifically two swift compile "Overlapping access" errors with Nimble in Nimble/Carthage/..../CwlCatchBadInstruction.swift

Line 100: "Overlapping accesses to 'request', but modification requires exclusive access; consider copying to a local variable"
Line 124: "Overlapping accesses to 'reply', but modification requires exclusive access; consider copying to a local variable"

I need to admit my ignorance with iOS dev. To me this looks like a Nimble problem, not a CocoaPods problem. Maybe the most recent version of Nimble is borked? I couldn't say what this problem is for certain. 

I googled and searched through the Issues and couldn't find a problem with a default `pod lib create` out of the box.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 72da9cab256900072b62d99fe3247a0b518be9c5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/brianLeeson/dummy.git

**Comment by dnkoutso** [comment]
Yes this is a Nimble issue but you are also pointing to a very old version. 

```ruby
pod 'Nimble', '7.3.1'
```

In your `Podfile` and worked for me.

**Comment by brianLeeson** [comment]
Thanks dnkoutso. I'll update to the newest version. Why does `create lib` create a podfile that points to such an old version?

**Comment by dnkoutso** [comment]
@brianLeeson good question. It reads it from this repo https://github.com/CocoaPods/pod-template/blob/master/setup/ConfigureSwift.rb#L21.

You can open a PR there to update it!

**Comment by brianLeeson** [comment]
@dnkoutso, I'll likely give it a shot!
