### ISSUE TITLE
Do not copy resource if user target is a static framework

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8228]
In CocoaPods, it will skip copy the resource if the user target is a static library. But if the target is a static framework, I think it should be same with the static library, right?
```
          native_targets.each do |native_target|
            # Static library targets cannot include resources. Skip this phase from being added instead.
            next if native_target.symbol_type == :static_library
            TargetIntegrator.create_or_update_copy_resources_script_phase_to_target(native_target, script_path, input_paths, output_paths)
          end
```

**Comment by dnkoutso** [comment]
no you can copy the resources to static frameworks. Why wouldn't we?

**Comment by Whirlwind** [comment]
If CP copy the resources into Static framework, when other project import it, The resources will be duplicate.

**Comment by dnkoutso** [comment]
@Whirlwind is this not happening on dynamic frameworks too then?

**Comment by Whirlwind** [comment]
emm.... Maybe, if the user target is not a app ( include library and framework), we should not copy the resources.

**Comment by dnkoutso** [comment]
If a user target is a framework we should copy them as we are integrating that target. Care to provide a sample or example here?

**Comment by dnkoutso** [comment]
Hm yes it certainly is an issue we can potentially avoid running the script phase if we know the framework is being integrated by an app target (i.e is not an SDK). See `analyze_host_targets_in_podfile` method in `analyzer.rb` and also `generate_targets#415` in `analyzer.rb`

**Comment by dnkoutso** [comment]
Actually it makes me wonder if we should ever do it...

**Comment by Whirlwind** [comment]
I think that if the code from dependencies are linked into the user target, so the resources should be copyied. When the user target is library/framework/object, the xcode will not link the dependencies, so the resources shoud be not copied. When the user target is a app, the code and resources from depedencies should be linked/copied.

**Comment by Whirlwind** [comment]
The code and resources should have same logic.

**Comment by paulb777** [comment]
This static framework podspec with resources seems to be working fine - https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInAppMessagingDisplay.podspec

**Comment by Whirlwind** [comment]
@paulb777 I means that the user target is static framework, not the pod target.

**Comment by chinnisasi** [comment]
@paulb777  @Whirlwind  is there any way to achieve this.. like post install script .. pls help
