### ISSUE TITLE
Push when logged out experience is confusing

### ISSUE THREAD

**Issue by kornelski** [CocoaPods/CocoaPods#8236]
I've installed cocoapods on a new machine, and I'm trying to publish a pod:

    pod trunk push

This command prints 35 lines of text, of which only 1 is relevant:

> You need to register a session first.

However, when I run `pod --help`, there is no command to "register a session". 

It would be more helpful if:

* it did not print all of the generic `pod trunk push` usage information which makes harder to spot the actual error which has nothing to do with syntax and conditions described in the usage

* the error message mentioned the exact subcommand that should be used for "registering a session"

**Comment by segiddins** [comment]
A PR to `cocoapods-trunk` with those improvements would be great!

**Comment by cltnschlosser** [comment]
Looks like this can be closed.

**Comment by orta** [comment]
Agree, thanks
