### ISSUE TITLE
Xcode 10.1 warnings after install

### ISSUE THREAD

**Issue by chrisvanbuskirk** [CocoaPods/CocoaPods#8242]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Warnings - Target XXXX overrides the Architecture setting

<img width="708" alt="screen shot 2018-11-01 at 1 24 01 pm" src="https://user-images.githubusercontent.com/3638007/47874564-c9517280-ddd9-11e8-85aa-61d48993809f.png">

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : bitbucket-xxx-pods - https://bitbucket.org/xxx/pods.git @ f1590365fdcef1c933712de42509adb7cc81c695
               master - https://github.com/CocoaPods/Specs.git @ 2169acc71e90de4dbd70cb1121f2321b231910b5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://bitbucket.org/XXXXXX/pods.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'


def available_pods
    pod 'ALForm'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'extensions'
    pod 'Toast-Swift'
    pod 'SwiftValidators'
end

target 'LabelCheck' do
    use_frameworks!
    available_pods
    
    target 'LabelCheckTests' do
    	inherit! :complete
	end
end
```

## Project that demonstrates the issue

N/A

**Comment by amorde** [comment]
This was done as part of https://github.com/CocoaPods/CocoaPods/pull/7932 - its possible Xcode 10 is smarter about this, so maybe we need to revert that change.

Could you post the diff in your project from before and after having Xcode "Perform Changes"?

**Comment by chrisvanbuskirk** [comment]
Sure.

[diff.txt](https://github.com/CocoaPods/CocoaPods/files/2539894/diff.txt)

**Comment by dnkoutso** [comment]
```diff
6c6
< 	objectVersion = 50;
---
> 	objectVersion = 46;
17a18
> 			productName = Fabric;
27a29
> 			productName = Crashlytics;
327c329
< 		48577275660F68B9DEF89A9CCDA88DBB /* MBProgressHUD.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; name = MBProgressHUD.framework; path = MBProgressHUD.framework; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		48577275660F68B9DEF89A9CCDA88DBB /* MBProgressHUD.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = MBProgressHUD.framework; sourceTree = BUILT_PRODUCTS_DIR; };
340c342
< 		5568ED09B1562409C8FF030D7BAB89F7 /* Pods_LabelCheck.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; name = Pods_LabelCheck.framework; path = "Pods-LabelCheck.framework"; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		5568ED09B1562409C8FF030D7BAB89F7 /* Pods_LabelCheck.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = Pods_LabelCheck.framework; sourceTree = BUILT_PRODUCTS_DIR; };
376c378
< 		8F75DA9C7FF8A7CBD28FCEBE35724C2A /* Pods_LabelCheck_LabelCheckTests.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; name = Pods_LabelCheck_LabelCheckTests.framework; path = "Pods-LabelCheck-LabelCheckTests.framework"; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		8F75DA9C7FF8A7CBD28FCEBE35724C2A /* Pods_LabelCheck_LabelCheckTests.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = Pods_LabelCheck_LabelCheckTests.framework; sourceTree = BUILT_PRODUCTS_DIR; };
381c383
< 		94D143739BAB9142B43512D7F20CD7E6 /* Toast_Swift.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; name = Toast_Swift.framework; path = "Toast-Swift.framework"; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		94D143739BAB9142B43512D7F20CD7E6 /* Toast_Swift.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = Toast_Swift.framework; sourceTree = BUILT_PRODUCTS_DIR; };
393c395
< 		AAD3D441DFF998F445B07C463607DF9B /* extensions.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; name = extensions.framework; path = extensions.framework; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		AAD3D441DFF998F445B07C463607DF9B /* extensions.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = extensions.framework; sourceTree = BUILT_PRODUCTS_DIR; };
398c400
< 		B36AB396275697EEE1A5B13BA8A38FE3 /* Podfile */ = {isa = PBXFileReference; explicitFileType = text.script.ruby; includeInIndex = 1; indentWidth = 2; lastKnownFileType = text; name = Podfile; path = ../Podfile; sourceTree = SOURCE_ROOT; tabWidth = 2; xcLanguageSpecificationIdentifier = xcode.lang.ruby; };
---
> 		B36AB396275697EEE1A5B13BA8A38FE3 /* Podfile */ = {isa = PBXFileReference; explicitFileType = text.script.ruby; includeInIndex = 1; indentWidth = 2; name = Podfile; path = ../Podfile; sourceTree = SOURCE_ROOT; tabWidth = 2; xcLanguageSpecificationIdentifier = xcode.lang.ruby; };
408c410
< 		BEEEAEC49ECEFE91F07485FD09298FE4 /* ALForm.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; name = ALForm.framework; path = ALForm.framework; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		BEEEAEC49ECEFE91F07485FD09298FE4 /* ALForm.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = ALForm.framework; sourceTree = BUILT_PRODUCTS_DIR; };
429c431
< 		DEAA7430E3CF7406305D0CB0DABF17B5 /* SwiftValidators.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; name = SwiftValidators.framework; path = SwiftValidators.framework; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		DEAA7430E3CF7406305D0CB0DABF17B5 /* SwiftValidators.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = SwiftValidators.framework; sourceTree = BUILT_PRODUCTS_DIR; };
441c443
< 		EEDD6E298BB39FA9579E743BF79F2A3C /* Reusable.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; name = Reusable.framework; path = Reusable.framework; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		EEDD6E298BB39FA9579E743BF79F2A3C /* Reusable.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; includeInIndex = 0; path = Reusable.framework; sourceTree = BUILT_PRODUCTS_DIR; };
446c448
< 		F92841CCA653B51527EFC1B60E97703F /* ALForm.bundle */ = {isa = PBXFileReference; explicitFileType = wrapper.cfbundle; includeInIndex = 0; name = ALForm.bundle; path = "ALForm-ALForm.bundle"; sourceTree = BUILT_PRODUCTS_DIR; };
---
> 		F92841CCA653B51527EFC1B60E97703F /* ALForm.bundle */ = {isa = PBXFileReference; explicitFileType = wrapper.cfbundle; includeInIndex = 0; path = ALForm.bundle; sourceTree = BUILT_PRODUCTS_DIR; };
603d604
< 			name = "Toast-Swift";
627d627
< 			name = SwiftValidators;
676d675
< 			name = ALForm;
752d750
< 			name = MBProgressHUD;
795d792
< 			name = Fabric;
821d817
< 			name = Crashlytics;
888d883
< 			name = Reusable;
920d914
< 			name = extensions;
1204c1198
< 				LastUpgradeCheck = 0930;
---
> 				LastUpgradeCheck = 1010;
1579d1572
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1593,1597c1586
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
1616d1604
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1630,1634c1618
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
1655d1638
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1659,1662c1642
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
1673d1652
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1687,1691c1666
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
1773d1747
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1787,1791c1761
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
1809d1778
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1823,1827c1792
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
1846d1810
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1850,1853c1814
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
1864d1824
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1878,1882c1838
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
1903d1858
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
1917,1921c1872
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
1990,1991c1941
< 				SWIFT_COMPILATION_MODE = wholemodule;
< 				SWIFT_OPTIMIZATION_LEVEL = "-O";
---
> 				SWIFT_OPTIMIZATION_LEVEL = "-Owholemodule";
2001d1950
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2015,2019c1964
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
2053d1997
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2067,2071c2011
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
2090d2029
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2105,2109c2044
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
2127d2061
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2142,2146c2076
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
2165d2094
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2179,2183c2108
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
2204d2128
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2219,2223c2143
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
2242d2161
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2246,2249c2165
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
2260d2175
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2264,2267c2179
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
2277d2188
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2291,2295c2202
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
2330d2236
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2344,2348c2250
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
2367d2268
< 				ARCHS = "$(ARCHS_STANDARD_64_BIT)";
2382,2386c2283
< 				LD_RUNPATH_SEARCH_PATHS = (
< 					"$(inherited)",
< 					"@executable_path/Frameworks",
< 					"@loader_path/Frameworks",
< 				);
---
> 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";```

**Comment by amorde** [comment]
Great, thanks for the diff. It does look like Xcode 10 wants us to not specify this setting in this scenario.

@robmaceachern have you experienced this issue as well?

**Comment by adarhef** [comment]
I've experienced this as well on Xcode 10.1. I think it reproduces on a new project too.

**Comment by robmaceachern** [comment]
Yeah I see the same warnings in Xcode 10.1 too.

**Comment by amorde** [comment]
Thanks everyone, I'll get a fix out as soon as I can 👍

**Comment by dnkoutso** [comment]
@amorde would you like this for 1.6.0? I think it would be best to do so.

**Comment by amorde** [comment]
yes, agreed

**Comment by chrisvanbuskirk** [comment]
@amorde I'm not see a change in this warning in RC 1.

**Comment by amorde** [comment]
@chrisvanbuskirk do you have a sample project I can test?

**Comment by amorde** [comment]
Note that the way we determine which Xcode version you are using is through the project version on your project - you may have to bump your `Project Format` setting to `Xcode 10-Compatible`

**Comment by chrisvanbuskirk** [comment]
@amorde Thanks for clarifying that.  It’s working properly.  Thanks for your hard work.

**Comment by philfi** [comment]
I've recently updated to XCode 10.2.1 running Cocoapods 1.6.2 and am experiencing this issue even after I set the `Project Format` for my two main projects (one iOS, one macOS) in my workspace to `Xcode 10.0-compatible` as suggested. When I look at the `Project Format` setting for the `Pods project` I see that it is now also getting set to `Xcode 10.0-compatible`.

The warning seems to only apply to the macOS versions, perhaps this was solved for iOS but not macOS?

I've attached a diff showing before/after selecting `Update to recommended settings`.
[diff.txt](https://github.com/CocoaPods/CocoaPods/files/3204139/diff.txt)

**Comment by amorde** [comment]
@philfi based on the diff I think what you're describing is different than this issue - could you open a new issue?

Also I know some changes when into Xcodeproj to support the latest versions of Xcode - it's worth trying `[sudo] gem update xcodeproj` to see if it has already been fixed.

**Comment by philfi** [comment]
I am experiencing the `Target X overrides the architecture setting...` so I assumed it was related. I did try updating `xcodeproj` and am still experiencing but I can open a new issue if that makes the most sense.
![image](https://user-images.githubusercontent.com/39564615/58127084-896da380-7be2-11e9-9c5d-dd6bb396fb93.png)

**Comment by philfi** [comment]
ah actually may be user error here, I forgot I am running cocoapods through bundler so it was still using old version of `xcodeproj`. I don't get these warnings after running it with the latest version of `xcodeproj` (1.9.0). Thanks!

**Comment by amorde** [comment]
no problem 👍 sorry I missed that part of the diff since there was a lot of other stuff in the beginning

**Comment by liamnichols** [comment]
I stumbled across this issue because I am also finding the warning about `ARCHS` being set to `$(ARCHS_STANDARD_64_BIT)` and I couldn't for the life of me work out why...

After digging through the code in the repo, I discovered this code:

https://github.com/CocoaPods/CocoaPods/blob/59f16420e5bd638a54aa5318df7b806d8470118e/lib/cocoapods/installer/analyzer.rb#L1061-L1086

Older Xcode Project versions cause Cocoapods to behave in different ways and it turns out that by updating the project version to Xcode 11 compatible, I was able to get Cocoapods to generate a more modern project file that fixes this issue

<img width="271" alt="Screenshot 2019-10-08 at 18 53 01" src="https://user-images.githubusercontent.com/482871/66419940-df5daf00-e9fc-11e9-869f-cd3d9ac17935.png">

It turns out our project was set down to Xcode 3.2 so I guess it was due a bump 😅

**Comment by nex-derek** [comment]
> I stumbled across this issue because I am also finding the warning about `ARCHS` being set to `$(ARCHS_STANDARD_64_BIT)` and I couldn't for the life of me work out why...
> 
> After digging through the code in the repo, I discovered this code:
> 
> https://github.com/CocoaPods/CocoaPods/blob/59f16420e5bd638a54aa5318df7b806d8470118e/lib/cocoapods/installer/analyzer.rb#L1061-L1086
> 
> Older Xcode Project versions cause Cocoapods to behave in different ways and it turns out that by updating the project version to Xcode 11 compatible, I was able to get Cocoapods to generate a more modern project file that fixes this issue
> 
> <img alt="Screenshot 2019-10-08 at 18 53 01" width="271" src="https://user-images.githubusercontent.com/482871/66419940-df5daf00-e9fc-11e9-869f-cd3d9ac17935.png">
> 
> It turns out our project was set down to Xcode 3.2 so I guess it was due a bump 😅

Xcode 11.1 seems bring back the warnings. Anyone getting the same thing?

**Comment by liamnichols** [comment]
> Xcode 11.1 seems bring back the warnings. Anyone getting the same thing?

I am using Xcode 11.1 and don't see the issue anymore... Could be that you're project has a slightly different setup that is triggering CocoaPods to generate its project differently though.

**Comment by alexgolikov** [comment]
> > I stumbled across this issue because I am also finding the warning about `ARCHS` being set to `$(ARCHS_STANDARD_64_BIT)` and I couldn't for the life of me work out why...
> > After digging through the code in the repo, I discovered this code:
> > https://github.com/CocoaPods/CocoaPods/blob/59f16420e5bd638a54aa5318df7b806d8470118e/lib/cocoapods/installer/analyzer.rb#L1061-L1086
> > 
> > Older Xcode Project versions cause Cocoapods to behave in different ways and it turns out that by updating the project version to Xcode 11 compatible, I was able to get Cocoapods to generate a more modern project file that fixes this issue
> > <img alt="Screenshot 2019-10-08 at 18 53 01" width="271" src="https://user-images.githubusercontent.com/482871/66419940-df5daf00-e9fc-11e9-869f-cd3d9ac17935.png">
> > It turns out our project was set down to Xcode 3.2 so I guess it was due a bump 😅
> 
> Xcode 11.1 seems bring back the warnings. Anyone getting the same thing?

I'm experiencing the same problem on Xcode 11.2.1: Warnings - Target XXXX overrides the Architecture setting. Could anybody help?

**Comment by JustinGanzer** [comment]
@alexgolikov Did you run `pod install` after your change? Make sure to keep cocoapods updated as well.

**Comment by FelixII** [comment]
I also receive this warning for my **macOS** dependencies with Xcode 11.3.

It looks like the `ARCHS` Xcode setting is always generated for macOS targets, regardless of the project version.

https://github.com/CocoaPods/CocoaPods/blob/42741d897eb8ab34f9a1524988f59ff3f7760cc4/lib/cocoapods/installer/analyzer.rb#L1124-L1128

Is this behavior intended?

I've written a `post_install` hook to remove the Xcode setting for all targets:

    post_install do |installer|
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings.delete('ARCHS')
        end
      end
    end

**Comment by Theome** [comment]
> I also receive this warning for my **macOS** dependencies with Xcode 11.3.
> 
> It looks like the `ARCHS` Xcode setting is always generated for macOS targets, regardless of the project version.
> 
> https://github.com/CocoaPods/CocoaPods/blob/42741d897eb8ab34f9a1524988f59ff3f7760cc4/lib/cocoapods/installer/analyzer.rb#L1124-L1128
> 
> Is this behavior intended?
> 

I have the same problem with Xcode 12. The warnings appear only for my macOS targets. I have updated the Xcode Project format to *Xcode 12.0-compatible* and use Cocoapods 1.10.0 with xcodeproj 1.19.0.

@FelixII Are you still using your `post_install` hook or have you found another solution?

**Comment by FelixII** [comment]
@Theome CocoaPods 1.10.0 still overrides the `ARCHS` setting for macOS targets. I keep using the workaround.

**Comment by steffidg** [comment]
FTR, on Xcode 13 I'm also still using `post_install` `ARCHS` delete step.
