### ISSUE TITLE
Missing libs when installing from local location using :path

### ISSUE THREAD

**Issue by gammelby** [CocoaPods/CocoaPods#8245]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I installed a pod using a local path:

```
project 'PodDebug/PodDebug.xcodeproj/'
platform :ios, '11.0'

target 'PodDebug' do
  pod 'kxmovie', :path => '~/git/kxmovie'
end
```

The local path was an unmodified clone of the github repo referenced below.

## What did you expect to happen?

I expected the same files to be installed as when installing from the CocoaPods registry or directly from github:

```
target 'PodDebug' do
  pod 'kxmovie', :git => 'https://github.com/Guoxweii/kxmovie'
end
```

This installs a number of .a files:

```
ug@mclappe2:~/git/pod-debug $ pod install --verbose
  Preparing

Analyzing dependencies
...

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
ug@mclappe2:~/git/pod-debug $ find ./ -name "*.a"
.//Pods/kxmovie/output/libavutil.a
.//Pods/kxmovie/output/libavcodec.a
.//Pods/kxmovie/output/libavformat.a
.//Pods/kxmovie/output/libswresample.a
.//Pods/kxmovie/output/libswscale.a
.//Pods/kxmovie/output/libkxmovie.a
ug@mclappe2:~/git/pod-debug $ 
```

Maybe I misinterpret the documentation? https://guides.cocoapods.org/syntax/podfile.html#pod says the `:path` construct is useful for developing a pod - I read this as `:path` could be used also when constructing a binary-only pod, but perhaps this is wrong and it only works for source-based pods? If so, the documentation should probably be updated to reflect this.

## What happened instead?

Installation succeeded according to the console output but nothing is installed.

```
ug@mclappe2:~/git/pod-debug $ pod install --verbose
  Preparing

Analyzing dependencies
...
-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
ug@mclappe2:~/git/pod-debug $ find ./ -name "*.a"
ug@mclappe2:~/git/pod-debug $ 
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 75a0c42dab2c63cce068796186a06eb94bfefd7c
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
project 'PodDebug/PodDebug.xcodeproj/'
platform :ios, '11.0'

target 'PodDebug' do
#  pod 'kxmovie', :path => '~/git/kxmovie'
  pod 'kxmovie', :git => 'https://github.com/Guoxweii/kxmovie'
end
```

## Project that demonstrates the issue

https://github.com/nabto/pod-debug 🌈 😇

**Comment by amorde** [comment]
Hello @gammelby!

The `:path` option installs the pod as a "development" pod, and uses the files at the location specified instead of copying them into the `Pods/` directory. This allows you to edit those files and have it be reflected in the original location.

I tried your sample (checking out the source of the dependency and then using `:path` to point to it) and it behaves as expected.

<img width="260" alt="screen shot 2018-11-02 at 3 30 39 pm" src="https://user-images.githubusercontent.com/2281949/47943648-45b88400-deb4-11e8-8272-c5d537c6aceb.png">

the `.a` libraries are included via symlink to their original location on disk. Are you expecting different behavior here?

**Comment by gammelby** [comment]
Thanks for your reply! I did not realize files are installed differently with the `:path` option, perhaps a little note in the docs would be good about this? I will check tomorrow when xcode is done installing an update if it works (I am sure it does - I ended up looking on the filesystem for missing files on a long debugging trail (of another pod) where I obviously have to backtrack a bit now).

**Comment by gammelby** [comment]
Hello again! You are completely right and the documentation even says this (https://guides.cocoapods.org/syntax/podfile.html#pod):

> will **link** the files directly from there in the Pods project

I obviously missed that crucial detail about linking instead of copying. Sorry about the noise - and thanks for your assistance!
