### ISSUE TITLE
How to provide a README.md with the 'http' defined download method in the `source`?

### ISSUE THREAD

**Issue by 2energycell** [CocoaPods/CocoaPods#8250]
Since there is not git source provided, hence it will not look for README.md in the git. So it is not clear how to provide a README.md file in order to improve the quality of a pod. Thanks.

**Comment by dnkoutso** [comment]
Ship it inside the ZIP? I believe it would work. All paths are relative to the extract zip.

I am going to close this preemptively and *I will* re-open if we find it's CocoaPods enhancement we could make.

Also consider asking on StackOverflow under `cocoapods` tag.
