### ISSUE TITLE
Give access to cocoapods in order to clone from private repository

### ISSUE THREAD

**Issue by hadiidbouk** [CocoaPods/CocoaPods#8252]
Hello,  

I am trying to make a simple pod using `VSTS` as git repository.
This git repository Isn’t public for sure, so when someone from our team needs to clone he should add his username and password.

Now after I created the pod library, I am receiving this error :

```
Cloning into '/var/folders/98/4q0y6scd6px7x0stc6pc79q00000gq/T/d20181106-27470-pis6gw'...
fatal: could not read Username for 'https://XXX.visualstudio.com': Device not configured
```

How can I configure a device for a specific pod? like adding the email and password before calling
 `pod install`.

**Comment by mpp-mariusc** [comment]
I think you will have to get anyone who is going use this pod to set up [SSH keys in VSTS](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=vsts) and give them access that way to the pod repo. If you are running `pod spec lint` or `pod lib lint` in an Azure DevOps Pipeline you'll have to make sure you import a SSH key for it to be able to access the pod repo.

**Comment by MariusCiocanel** [comment]
I think you will have to get anyone who is going use this pod to set up [SSH keys in VSTS](https://docs.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=vsts) and give them access that way to the pod repo. If you are running `pod spec lint` or `pod lib lint` in an Azure DevOps Pipeline you'll have to make sure you import a SSH key for it to be able to access the pod repo.

**Comment by hadiidbouk** [comment]
What if we are using the cocoapods app?

**Comment by MariusCiocanel** [comment]
> What if we are using the cocoapods app?

I don't use the CocoaPods.app so I can't comment. Maybe someone else knows...

**Comment by hadiidbouk** [comment]
The fact that you cannot force a developer to use terminal in order to download and use your app,
Thank you anyway
