### ISSUE TITLE
Contents of Podfile: swift_version is not reflected

### ISSUE THREAD

**Issue by mofneko** [CocoaPods/CocoaPods#8254]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

My project is currently using Swift 4.2.
And similarly for libraries to be used internally, the following is listed at the top level of Podfile to specify Swift 4.2.
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
swift_version = '4.2'
```
It should be noted that swift_version specifies 4.2 here.
However, after executing in both pod install / pod update, the library project specifies 4.0 for SwiftLanguage.

This phenomenon can be handled manually by manually specifying 4.2 from Xcode for a project under Pod management, but these settings are reset by executing the pod install / pod update command again.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/yusuke_arakawa/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 36c8f6a42c8c04d1b8ebffa2b77d5066395e1e5c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
You need to specify the swift version with each `target` declaration.

Probably a bug allowing this to be set at the root. 

Also keep in mind that the pod author may have specified the `swift_version` in their podspec which will always be honored first.

**Comment by dnkoutso** [comment]
Can you please move the declaration on each `target` and report back if it works?

**Comment by mofneko** [comment]
I list several library projects that confirmed the symptoms below.

pod 'RealmSwift'
pod 'SwiftIconFont'
pod 'Eureka'

**Comment by dnkoutso** [comment]
@mofneko I would love a sample app. if I recall correctly this DSL is actually unused within `target` you should set those into the user (not Pods) `.xcodeproj` instead.

**Comment by mofneko** [comment]
https://github.com/mofneko/CocoaPodsErrorSample

**Comment by mofneko** [comment]
https://github.com/mofneko/CocoaPodsErrorSample

I made a sample.
The first commit works normally (SwiftVersion is set as 4.2 for PodProject).
The second commit is a configuration imitating our project, and a title error occurs.
Strictly speaking, our project is making the SwiftVersion setting indefinite and always using the latest Swift.

**Comment by dnkoutso** [comment]
This is superseded by the newly added API for `supports_swift_versions` in the `Podfile`.

There is no officially exposed DSL of `swift_version` for `Podfile` and target definitions.

Closing for now.
