### ISSUE TITLE
Update a pod will cause update all dependency by the pod

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8255]
I have a demo app with the Podfile:
```
target 'TestMolinillo' do
  pod 'CalendarKit'
end
```
And I have the Podfile.lock:
```
PODS:
  - CalendarKit (0.5.0):
    - DateToolsSwift
    - Neon
  - DateToolsSwift (4.0.0)
  - Neon (0.3.4.3)

DEPENDENCIES:
  - CalendarKit

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - CalendarKit
    - DateToolsSwift
    - Neon

SPEC CHECKSUMS:
  CalendarKit: 6dbbb067737f4f0338aadbcbe9ec5e2e87aa3691
  DateToolsSwift: 875d97ff9e3a5d54abdd67a269b3f51c757b71ab
  Neon: 5862929ff079a3c371637b01aba136df37e4988c

PODFILE CHECKSUM: 5ea5a52802a2003831742a3c4b8b2df7b99774c5

COCOAPODS: 1.5.3
```

I need update the `CalendarKit` to the `0.5.1` from `0.5.0`, but I want to keep the version `0.3.4.3` of `Neon` which dependency by the `CalendarKit`.

After run `pod update CalendarKit`, I got:
```
pod update CalendarKit --no-repo-update
Analyzing dependencies
Downloading dependencies
Installing CalendarKit 0.5.1 (was 0.5.0 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Using DateToolsSwift (4.0.0)
Installing Neon 0.4.0 (was 0.3.4.3 and source changed to `https://github.com/CocoaPods/Specs.git` from `https://github.com/cocoapods/specs.git`)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

The CocoaPods update `CalendarKit` and `Neon`. I check the code from Molinillo, it seams that Molinillo will remove the `Neon` from the `DependencyGraph` when its parent is updated and there is not any `incoming_edges`:
```
      @vertex.outgoing_edges.each do |e|
          v = e.destination
          v.incoming_edges.delete(e)
          if !v.root? && v.incoming_edges.empty?
            removed_vertices.concat graph.detach_vertex_named(v.name)
          end
        end
```

I think the `Neon` should keep old version when I only update the `CalendarKit`. Right? Is it a bug?

**Comment by segiddins** [comment]
It’s intentional, since Neon isn’t in your Podfile (or required by any pod you’re not updating)

**Comment by Desgard** [comment]
I think the **upgrade operation** should be **a developer's active behavior**. 
It's like the `git submodule --recursive`, `--recursive` can control submodules version change of the submodule for repo. 
From this, `pod update CalendarKit --recursive` looks more reasonable?

**Comment by Whirlwind** [comment]
Case A:

Podfile:
```
  pod 'CalendarKit'
  pod 'Neon '
```
Podfile.lock:
```
PODS:
  - CalendarKit (0.5.0):
    - DateToolsSwift
    - Neon
  - DateToolsSwift (4.0.0)
  - Neon (0.3.4.3)
```
Now, I remove `Neon` from `Podfile`, it will casue `Neon` update to 0.4.0.

Case B:

Podfile:
```
  pod 'CalendarKit'
```

Podfile.lock:
```
PODS:
  - CalendarKit (0.5.0):
    - DateToolsSwift
    - Neon
  - DateToolsSwift (4.0.0)
  - Neon (0.3.4.3)
```
Now, I update `CalendarKit`, it will casue `Neon` update to 0.4.0. Now, the Neon `0.4.0` may be not supported by `CalendarKit`'s `0.5.1` version.  (If the `Neon` `0.4.0` is release after `CalendarKit` `0.5.1`)

Case C:

Podfile:
```
  pod 'CalendarKit'
  pod 'OtherKit'
```

Podfile.lock:
```
PODS:
  - CalendarKit (0.5.0):
    - DateToolsSwift
    - Neon
  - DateToolsSwift (4.0.0)
  - Neon (0.3.4.3)
  - OtherKit (0.1):
    - Neon
```

If I update `CalendarKit` to `0.5.1`, the `Neon` will not be updated.  If the Case B is `intentional`, so this case will also update `Neon`, right?

**Comment by Whirlwind** [comment]
I did a simple hook:
```
module Pod
  class Config
    attr_accessor :update_mode
  end

  class Command
    class Update < Command
      alias_method :mbox_run_1108, :run
      def run
        if @pods
          config.update_mode = @pods
        else
          config.update_mode = :all
        end
        mbox_run_1108
      end
    end
  end

  class Resolver
    include Config::Mixin

    alias_method :mbox_specifications_for_dependency_1108, :specifications_for_dependency
    def specifications_for_dependency(dependency, additional_requirements = [])
      r = mbox_specifications_for_dependency_1108(dependency, additional_requirements)
      unless config.update_mode.nil?
        if config.update_mode != :all && !config.update_mode.include?(Specification.root_name(dependency.name))
          locked = config.lockfile.version(dependency.name)
          if locked
            prefect = r.find { |s| locked == s.version }
            if prefect
              r.delete(prefect)
              r.append(prefect)
            end
          end
        end
      end
      r
    end
  end
end
```

This hook file is very simple: Just bring the version which locked by `Podfile.lock` to the top of the specs. So the CocoaPods will use the locked version first, if the version is conflict with others, CocoaPods will use the latest version instead of the locked version.

Of cause, user could update the dependency with `pod update xxx`, the locked version of  `xxx` will not be bring to the top.

It is simply, but works.
