### ISSUE TITLE
unable to spawn process (Argument list too long)

### ISSUE THREAD

**Issue by 12721576** [CocoaPods/CocoaPods#8257]
## What did you do?

 I had update Xcode 10.1, and use the New Build System， that build the project and get error for it. The error from:

- Check Pods Manifest.lock 

- Copy Pods Resources

- Embed Pods Frameworks

  That i select each other "run script only" when installing, it build success.
  Please check this issue.
   Thank you very much.

## What happened instead?

Error is as follows ：
     **PhaseScriptExecution [CP]\ Copy\ Pods\ Resources  Resources** /Users/xxx/Library/Developer/Xcode/DerivedData/aaa-aguqvqbnkdcbjzeboblivwxpuzqq/Build/Intermediates.noindex/aaa.build/Debug-iphoneos/aaa.build/Script-78B6DC2EB701A4579063C47D.sh (in target: aaa)
    cd /Users/xxx/Desktop/kai/code/iphone-aaa/aaa
    /bin/sh -c /Users/xxx/Library/Developer/Xcode/DerivedData/aaa-aguqvqbnkdcbjzeboblivwxpuzqq/Build/Intermediates.noindex/aaa.build/Debug-iphoneos/aaa.build/Script-78B6DC2EB701A4579063C47D.sh
     **error: unable to spawn process (Argument list too long)**

**PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock** /Users/xxx/Library/Developer/Xcode/DerivedData/aaa-aguqvqbnkdcbjzeboblivwxpuzqq/Build/Intermediates.noindex/aaa.build/Debug-iphonesimulator/aaa.build/Script-9A3E319640EA6CB57426CAF3.sh (in target: aaa)
    cd /Users/xxx/Desktop/kai/code/iphone-aaa/aaa
    /bin/sh -c /Users/xxx/Library/Developer/Xcode/DerivedData/aaa-aguqvqbnkdcbjzeboblivwxpuzqq/Build/Intermediates.noindex/aaa.build/Debug-iphonesimulator/aaa.build/Script-9A3E319640EA6CB57426CAF3.sh
      **error: unable to spawn process (Argument list too long)**

**PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks** /Users/xxx/Library/Developer/Xcode/DerivedData/aaa-aguqvqbnkdcbjzeboblivwxpuzqq/Build/Intermediates.noindex/aaa.build/Debug-iphonesimulator/aaa.build/Script-9363232669D278A0B07C1BAE.sh (in target: aaa)
    cd /Users/xxx/Desktop/kai/code/iphone-aaa/aaa
    /bin/sh -c /Users/xxx/Library/Developer/Xcode/DerivedData/aaa-aguqvqbnkdcbjzeboblivwxpuzqq/Build/Intermediates.noindex/aaa.build/Debug-iphonesimulator/aaa.build/Script-9363232669D278A0B07C1BAE.sh
      **error: unable to spawn process (Argument list too long)**

     Why cause the "Argument list too long"? And how to sovle it?

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.6 (17G3025)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/.rvm/rubies/ruby-2.4.0/lib

### Installation Source

```
Executable Path: /Users/.rvm/gems/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0

**Comment by YYYYCY** [comment]
I had the same problem, can u tell my how to fix it? :)

**Comment by pateljay43** [comment]
@12721576 can you help us by posting you solution here? I am facing the same issue right now out of no where.

**Comment by pateljay43** [comment]
cc @YYYYCY

**Comment by pateljay43** [comment]
I ended up using Legacy Build System and it worked for now. I don't want to keep using Legacy system hence still looking for a proper fix for this issue

**Comment by CrazyFanFan** [comment]
We met the same issue in our project, and it will be raised when assigning long argument to the environment variable. We found that the script will automatically generate the command like "`export HEADER_SEARCH_PATHS="${ALL_PTAHS}`". Here attached the demo that will generate the same issue. 

[ArgumentListTooLongDemo.zip](https://github.com/CocoaPods/CocoaPods/files/3339231/ArgumentListTooLongDemo.zip)

XCode Device Target： Generic iOS Device
XCode: Product  -> Archive

**Comment by CrazyFanFan** [comment]
@dnkoutso

**Comment by dnkoutso** [comment]
There isn't much you can do this is reaching ARG_MAX limit. You have to reduce the number of characters for each path.

**Comment by pateljay43** [comment]
Reducing number of character is like a temporary patch. And, does not guarantee to work.

After researching a while, bug from Swift JIRA: https://bugs.swift.org/browse/SR-280
Note: the threshold number is way less than 1500 swift files in your project. So Project Modularization is the best way to handle this issue according to my knowledge.

**Comment by xanderbuck** [comment]
> I ended up using Legacy Build System and it worked for now. I don't want to keep using Legacy system hence still looking for a proper fix for this issue

@pateljay43 Did you ever find a solution for this?

**Comment by pateljay43** [comment]
> Reducing number of character is like a temporary patch. And, does not guarantee to work.
> 
> After researching a while, bug from Swift JIRA: https://bugs.swift.org/browse/SR-280
> Note: the threshold number is way less than 1500 swift files in your project. So Project Modularization is the best way to handle this issue according to my knowledge.

@xanderbuck yes

**Comment by rfitz123** [comment]
> @xanderbuck yes. modularize your project into frameworks
@pateljay43  Could you explain a bit more what you mean?

**Comment by pateljay43** [comment]
@rfitz123 Search for "modularization in ios" and you will find a lot of articles in detail which will show you not only what that means, but also how to do it.

**Comment by BorisNikolic** [comment]
> HEADER_SEARCH_PATHS

Can you elaborate with little more details on this, please? What is the 'environment variable' in your answer? Which script will generate the command?

Thanks!

**Comment by picciano** [comment]
Still seeing this is current version, 1.9.3.

No fix? "modularize your project" is not really a workable solution.

**Comment by devSC** [comment]
me too in flutter project

**Comment by LYMelody** [comment]
> Still seeing this is current version, 1.9.3.
> 
> No fix? "modularize your project" is not really a workable solution.

mee too.

**Comment by Binlogo** [comment]
> There isn't much you can do this is reaching ARG_MAX limit. You have to reduce the number of characters for each path.

Absolutely, reduce the each path is almost the only way. If meet this issue, just do it.  😭

**Comment by msbouchedid** [comment]
Anyone ever find a solution to this? Unfortunately using legacy build system is no longer an option a of Xcode 12.3+

**Comment by pateljay43** [comment]
https://github.com/CocoaPods/CocoaPods/issues/8257#issuecomment-506734912

> Reducing number of character is like a temporary patch. And, does not guarantee to work.
> 
> After researching a while, bug from Swift JIRA: https://bugs.swift.org/browse/SR-280
> Note: the threshold number is way less than 1500 swift files in your project. So Project Modularization is the best way to handle this issue according to my knowledge.

**Comment by HsS-2019** [comment]
meet the same question. it seem as if reduce the path is the only way :)

**Comment by TyrantDante** [comment]
try remove phase

`post_integrate do |installer|
  # 删除 Check Pods Manifest.lock 因为会有 argument too long的问题，先用这种方式吧
  projects = Pathname.glob(installer.config.installation_root + '*.xcodeproj').map { |path| Xcodeproj::Project.open(path) }
  projects.each do |project|
    project.native_targets.each do |native_target| 
      build_phase = native_target.shell_script_build_phases.find { |bp| bp.name && bp.name.end_with?("Check Pods Manifest.lock") }
      return unless build_phase.present?
      native_target.build_phases.delete(build_phase)
    end
    project.save
  end
end
`
