### ISSUE TITLE
Need Official extension to Pre-Build pod to framework

### ISSUE THREAD

**Issue by wudijimao** [CocoaPods/CocoaPods#8258]
Hello~
      I found a useful unofficial CocoaPods extension here: https://github.com/leavez/cocoapods-binary
Witch can pre build framework to avoid rebuild pods after clean.
Whether there is an existing solution to avoid rebuild?
Or Do we have a plan to make an official extension to do this?
Thank you very much!

**Comment by paulb777** [comment]
https://github.com/CocoaPods/Rome does a prebuild of the Pods and then never needs another rebuild. The cost is a bit more configuration work.
