### ISSUE TITLE
Issues with validating podspc

### ISSUE THREAD

**Issue by Smiller193** [CocoaPods/CocoaPods#8262]
So I am trying to create a podspec for this github repo

https://github.com/EurekaCommunity/VideoRow

I followed this tutorial here however when I run 
https://www.youtube.com/watch?v=oZSZ8mievUU

> pod spec lint

I get these errors

> -> VideoRow (1.0.0) - ERROR | [iOS] file patterns: The source_files pattern did not match any file. - NOTE | xcodebuild: note: Using new build system - NOTE | [iOS] xcodebuild: note: Planning build - NOTE | [iOS] xcodebuild: note: Constructing build description - NOTE | [iOS] xcodebuild: warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

I am using the most up to date version of cocoapods and my podspec looks like this 

    Pod::Spec.new do |spec|
      spec.name         = "VideoRow"
      spec.version      = "1.0.0"
      spec.summary      = "Eureka row that allows users to select videos"
      spec.description  = "This framework is an add on to the many rows that encompass the Eureka Community. This row will allow users to select videos from there media library to potentially export to some backend service."
      spec.homepage     = "https://github.com/EurekaCommunity/VideoRow"
      spec.license      = { :type => "MIT", :file => "LICENSE" }
      spec.author       = { "Smiller193" => "shawn.miller@temple.edu" }
      spec.social_media_url = 'https://twitter.com/EurekaCommunity'
      spec.platform    = :ios, "9.1"
      spec.source       = { :git => "https://github.com/EurekaCommunity/VideoRow.git", :tag => "1.0.0" }
      spec.source_files  = 'VideoRow'
      spec.requires_arc = true
      spec.dependency "Eureka"
      spec.dependency "TLPhotoPicker"
      spec.swift_version = '4.2'
    end

**Comment by dnkoutso** [comment]
Your `s.source_files` does not match any files.

Use something like `s.source_files = 'VideoRow/*.{h,m}'` etc...

```
 -> VideoRow (1.0.0)
    - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  note: Using build description 'db911fd60d0446a0badba73732cf2dc3'
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - NOTE  | [iOS] xcodebuild:  note: Using eager compilation
    - NOTE  | [iOS] xcodebuild:  note: build debugging is enabled, trace file: '/Users/dimitris/Library/Developer/Xcode/DerivedData/App-frjvprwgyifcrdfsrocfrcowsteh/Build/Intermediates.noindex/XCBuildData/buildDebugging-563420036.202337/build.trace'
    - NOTE  | [iOS] xcodebuild:  note: build debugging is enabled, current manifest: '/Users/dimitris/Library/Developer/Xcode/DerivedData/App-frjvprwgyifcrdfsrocfrcowsteh/Build/Intermediates.noindex/XCBuildData/buildDebugging-563420036.202337/current-manifest.xcbuild'
    - NOTE  | [iOS] xcodebuild:  note: build debugging is enabled, current serialized description: '/Users/dimitris/Library/Developer/Xcode/DerivedData/App-frjvprwgyifcrdfsrocfrcowsteh/Build/Intermediates.noindex/XCBuildData/buildDebugging-563420036.202337/current-desc.xcbuild'

Analyzed 1 podspec.
```

This is not a CocoaPods library issue. Please ask StackOverflow under `cocoapods` tag.
