### ISSUE TITLE
Invalid `VideoRow.podspec` file: undefined method `join' for “TLPhotoPicker”:String

### ISSUE THREAD

**Issue by Smiller193** [CocoaPods/CocoaPods#8263]
Im confused as to why this error is occuring when I try to create my own podfile 

I am following this tutorial here 

https://ronakshah.org/How-To-Make-A-Cocoapod-With-Dependencies/

However, when I try to run pod install for the last step it gives me this error

>  Invalid `VideoRow.podspec` file: undefined method `join' for "TLPhotoPicker":String

        Pod::Spec.new do |s|
      s.name             = 'VideoRow'
      s.version          = '0.1.0'
      s.summary          = 'Eureka row that allows us to take or select a video.'
      s.description      = <<-DESC
    This is an add-on to the many rows that are in the Eureka Community. This row will allow users to select a video from there library to export to a backend service of there choosing.
                           DESC
      s.homepage         = 'https://github.com/EurekaCommunity/VideoRow'
      s.license          = { :type => 'MIT', :file => 'LICENSE' }
      s.author           = { 'Smiller193' => 'shawn.miller@temple.edu' }
      s.source           = { :git => 'https://github.com/EurekaCommunity/VideoRow.git', :tag => s.version.to_s }
       s.social_media_url = 'https://twitter.com/EurekaCommunity'
    
      s.ios.deployment_target = '9.1'
    
      s.source_files = 'VideoRow/Classes/**/*'
      s.platform = :ios, "10.0"
      s.dependency = 'TLPhotoPicker'
      s.dependency = 'Eureka'
      s.swift_version = '4.2'
    end

This is my podspec

        use_frameworks!
    
    target 'VideoRow_Example' do
      pod 'VideoRow', :path => '../'
      pod 'Eureka'
      pod 'TLPhotoPicker'
      target 'VideoRow_Tests' do
        inherit! :search_paths
    
        
      end
    end

Both of these seem right but I get an error every time I try to run pod install.

**Comment by c-goettert** [comment]
I had the same error, maybe it will help someone:

Try adjusting the lines
```
  s.dependency = 'TLPhotoPicker
  s.dependency = 'Eureka'
```
to follows:
```
  s.dependency 'TLPhotoPicker
  s.dependency 'Eureka'
```
