### ISSUE TITLE
 - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/

### ISSUE THREAD

**Issue by ssowri1** [CocoaPods/CocoaPods#8267]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by orta** [comment]
This issue is just the template.

**Comment by ssowri1** [comment]
> This issue is just the template.

I have edited my quest. Please check this.

**Comment by orta** [comment]
It looks like an issue with cloning your repo, maybe you have the wrong url or don't have a tag set up

**Comment by ssowri1** [comment]
> It looks like an issue with cloning your repo, maybe you have the wrong url or don't have a tag set up

Thanks for your kind response. I am new one to here. Can you help me to rid of this issue. I have edited my question again. please check it.

**Comment by ssowri1** [comment]
Hi @orta ,

Thank you for spent a time with my concern. As you said this is tag set up issue only. Well! I used the below link to get rid of that issue,

https://help.github.com/articles/creating-releases/
