### ISSUE TITLE
No email received for 'pod trunk register'

### ISSUE THREAD

**Issue by ktaiq** [CocoaPods/CocoaPods#8276]
Hi,

Recently we've been trying to register a machine with pod trunk register.

$ pod trunk register liyi@aiq.tech 'AIQKit' --description='build machine'
$ [!] Please verify the session by clicking the link in the verification email that has been sent to liyi@aiq.tech

But no verification email was received.
Doing the same thing with a different email from the same domain, worked as expected.

@orta Could you please check if there are any issues on your end with the registration of the liyi@aiq.tech email.

**Comment by orta** [comment]
We got a bounce today that the email address didn't exist, so I've removed it from our blacklist 👍

**Comment by ktaiq** [comment]
thanks! got the verify email !

**Comment by iOSPrincekin** [comment]
> We got a bounce today that the email address didn't exist, so I've removed it from our blocklist 👍

I have the same problem. could you help me remove the email address trustdevice@trustdecision.com ,thanks!
