### ISSUE TITLE
No way to just update only the development pod?

### ISSUE THREAD

**Issue by pepasflo** [CocoaPods/CocoaPods#8277]
We have some of our in-house "library" code split off as a separate framework project, which is used by our main project.  This is accomplished by having `pod` manage the framework as a "development pod".

If you add a new file to the framework, that file doesn't become visible in the main project until you run `pod update`, which causes the project files to be regenerated.

Unfortunately, this also pulls in a bunch of updates to the 3rd-party pods we use, which isn't what I want (we typically update our dependencies in a dedicated PR).  This is true even if we specify the development pod (`pod update Foo`)

* [✅] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod update Foo`

## What did you expect to happen?

Foo is a "development pod".  I added a file to Foo.xcworkspace, and I need it to be visible to the project which has Foo pulled in as a development pod.  So I just need pod to regenerate the Xcode project files.

## What happened instead?

`pod` updates a few other unrelated pods anyway.

![screen shot 2018-11-14 at 5 34 26 pm](https://user-images.githubusercontent.com/25310741/48519902-40542580-e834-11e8-9633-994fc5d079df.jpg)

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/jpepas/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ce03e56a743764c5b7c9d1cd3e15fe72b7acc8a9
```

### Installation Source

```
Executable Path: /Users/jpepas/.rvm/gems/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# If you don't start the first line with a comment, you don't get Vim syntax highlighting.
platform :ios, '10.0'
use_frameworks!

target 'FloSports' do  

  # Pods for FloSports
  pod 'FloSportsCore', :path => '../FloSportsCore'
  pod 'Kingfisher', '4.8.0'
  pod 'Cartography', '2.1.0'
  pod 'google-cast-sdk', '3.3.0'
  pod 'SkyFloatingLabelTextField', '3.4.1'
  pod 'SwiftMessages'
  pod 'Youbora-AVPlayer'
  pod 'Bugsnag'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Branch'
  pod 'RxAVFoundation'
  pod 'RxAppState', '1.1.2'
  pod 'RxGesture'
  pod 'IterableSDK', '4.4.7'
  pod 'NSLogger/Swift'

  # Pinned dependencies needed for FloSportsCore
  # Ugh, it appears some of these have to be pinned in both FloSports and FloSportsCore
  pod 'Firebase', '4.10.1'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'FirebaseInstanceID'
  pod 'Alamofire', '4.7.2'
  pod 'RxSwiftExt', '3.2.0'
  pod 'RxAppState', '1.1.2'
  
  target 'FloSportsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase', '4.10.1'
  end

  # thanks to http://marginalfutility.net/2015/10/11/swift-compiler-flags/
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'FloSportsCore'
        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '-D DEBUG -D NSLOGGER_ENABLED'
          else
            config.build_settings['OTHER_SWIFT_FLAGS'] = '-D NSLOGGER_ENABLED'
          end
        end
      end
    end
  end

end
```

## Project that demonstrates the issue

(I can create a demo project if needed)

**Comment by dnkoutso** [comment]
`pod update` will update all dependencies. Use `pod install` to refresh the workspace that will refresh the development pod files if any have changed.

Additionally, in your development pod `.podspec` _lock_ the dependencies to a specific version if you do not expect them to be updated even with a `pod update`.

Going to preemptively close this issue but I _will_ re-open if we identify missing functionality or bug in CocoaPods library here.

**Comment by pepasflo** [comment]
Ok, it looks like the specific dependencies which are getting updated are actually dependencies of the development pod:

```
$ cat FloSportsCore.podspec | grep ReachabilitySwift
  spec.dependency "ReachabilitySwift"
```

**Comment by pepasflo** [comment]
@dnkoutso are you saying `pod update foo` will update all dependencies, or that `pod update` will update all dependencies?

**Comment by dnkoutso** [comment]
@pepasflo `pod update foo` will update foo and its dependencies which from your last comment seems to specify no requirements (`spec.dependency "Pod"`) will _always_ accept the latest version.

`pod update` will update all dependencies for all pods.

**Comment by dnkoutso** [comment]
Again use `pod install` that will refresh the development pod and not perform any updates.

**Comment by dnkoutso** [comment]
And in your podspec use `spec.dependency "Pod", '1.0.0'` to lock it so even `pod update` won't update anything

**Comment by pepasflo** [comment]
thanks @dnkoutso !
