### ISSUE TITLE
PLCrashReporter-DynamicFramework can't build with Xcode 10

### ISSUE THREAD

**Issue by allen8300** [CocoaPods/CocoaPods#8279]
Hi man,
I'm using your PLCrashReporter-DynamicFramework '~> 1.3.0.1' in my iOS app;
But it cannot build with Xcode10, the segment registers are 16 bit, Zeroing out the other 48 bits in
case client code depends on it.
So can you update code from [here](https://github.com/AbletonAppDev/plcrashreporter) and supply a new version asap?

**Comment by dnkoutso** [comment]
Please file an issue with the corresponding repo. This is about the CocoaPods library. 

https://github.com/plausiblelabs/plcrashreporter
