### ISSUE TITLE
Oh no, an error occurred.

### ISSUE THREAD

**Issue by WandyLau** [CocoaPods/CocoaPods#8282]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.   Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Dictionary+missing+%27%3B%27+after+key-value+pair+for+%22USER_HEADER_SEARCH_PATHS%22%2C+found+%22%2C%22%0A+++%23++-------------------------------------------%0A+++%23++%09%09%09%09%22SYSTEM_FRAMEWORK_SEARCH_PATHS%5Bsdk%3Diphonesimulator12.1%5D%22+%3D+%22%24%28inherited%29%22%3B%0A+++%23++%09%09%09%09TARGETED_DEVICE_FAMILY+%3D+1%3B%0A569%3E++%09%09%09%09USER_HEADER_SEARCH_PATHS+%3D+%09%22%24%28BUILT_PRODUCTS_DIR%29%2F%24%28PRODUCT_NAME%29.framework%2FHeaders+%24%28CONTENTS_FOLDER_PATH%29%2FHeaders%22%2C%0A++++++%09%09%09%09+++++++++++++++++++++++++++%09+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++%5E%0A+++%23++%09%09%09%09%29%3B%0A+++%23++%09%09%09%7D%3B%0A+++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
/Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:95:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:34:in `search'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`
### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : hyperledger - https://github.com/hyperledger/indy-sdk.git @ c428b79e31016662809e03ce457402a9c98988e9
               master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hyperledger/indy-sdk.git'
platform :ios, '10.2'

workspace 'Indy.xcworkspace'

def appPods
    pod 'libsodium', '1.0.12'
    pod 'libzmq', '4.2.3'
    pod 'OpenSSL-lib-iOS'
    #pod 'libindy', "1.6.7"
end

target 'Indy-demo' do
    project 'Indy-demo'
    pod 'CoreBitcoin', :podspec => 'https://raw.github.com/oleganza/CoreBitcoin/master/CoreBitcoin.podspec'

    target 'Indy-demoTests' do
	inherit! :search_paths
    end
end


target 'Indy' do
    project 'Indy'
    appPods
end

# ignore all warnings from all pods
#inhibit_all_warnings!

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'libzmq'
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'ZMQ_BUILD_DRAFT_API=1']
        end
      end
      if target.name == 'libsodium'
        target.build_configurations.each do |config|
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'NATIVE_LITTLE_ENDIAN=1 PACKAGE_NAME=\"libsodium\" PACKAGE_TARNAME=\"libsodium\" PACKAGE_VERSION=\"1.0.12\" PACKAGE_STRING=\"libsodium\ 1.0.12\" PACKAGE_BUGREPORT=\"https://github.com/jedisct1/libsodium/issues\" PACKAGE_URL=\"https://github.com/jedisct1/libsodium\" PACKAGE=\"libsodium\" VERSION=\"1.0.12\" HAVE_PTHREAD_PRIO_INHERIT=1 HAVE_PTHREAD=1 STDC_HEADERS=1 HAVE_SYS_TYPES_H=1 HAVE_SYS_STAT_H=1 HAVE_STDLIB_H=1 HAVE_STRING_H=1 HAVE_MEMORY_H=1 HAVE_STRINGS_H=1 HAVE_INTTYPES_H=1 HAVE_STDINT_H=1 HAVE_UNISTD_H=1 _POSIX_PTHREAD_SEMANTICS=1 NATIVE_LITTLE_ENDIAN=1 HAVE_WEAK_SYMBOLS=1 CPU_UNALIGNED_ACCESS=1 CONFIGURED=1']
        end
      end
    end
end
```
## Project that demonstrates the issue

I got this repeatedly. I think this may be a really bug. Each time I have to reinstall it.
Please help.

**Comment by dnkoutso** [comment]
Please upload sample app.

**Comment by WandyLau** [comment]
I think this should be some issue in project config file. I tried another one it is good. But the error msg is not helpful for debug.

**Comment by WandyLau** [comment]
Sorry, I missed some error msg. I think this results from misconfiguration.

**Comment by ChineseCoder** [comment]
Has the problem been solved? I don't see it

**Comment by listenzz** [comment]
Same problem
