### ISSUE TITLE
error while  "pod install" google maps ionic 1

### ISSUE THREAD

**Issue by khaled-elrifaay** [CocoaPods/CocoaPods#8294]
i used version 1.5.3 cocoapods 
my xcode 9.4.1
i'm in project ionic 1
when i try pod install i have that error 
### Error
```
Errno::EACCES - Permission denied @ dir_s_mkdir - /Users/briskdigi/Desktop/patientApp/platforms/ios/Pods
[!] Oh no, an error occurred.
i want to install google maps why those conflicts ?

**Comment by dnkoutso** [comment]
Seems a permission issue with `/Users/briskdigi/Desktop/patientApp/platforms/ios` folder`.

Right now with the given information it does not appear to be a CocoaPods issue and also please use the issue template and provide a sample app.

This appears to be a machine configuration issue as `pod install` with google maps works for me.
