### ISSUE TITLE
licucore is not an object file (not allowed in a library)

### ISSUE THREAD

**Issue by JanC** [CocoaPods/CocoaPods#830]
Hi,
I have a static library project where I want to use CocoaPods. I've just added one dependency to my Podfile:

```
platform :ios, '6.0'
pod 'RegexKitLite', '~> 4.0'
```

When I build the project, I get the following error:

```
file: -licucore is not an object file (not allowed in a library)
```

If I remove manually the `-licucore` linker flag from the Pods.xcconfig it compiles fine but I'd have to do this everytime I run the `pod install` command

Is this a bug in Cocoapods?

cheers

**Comment by robertcrabtree** [comment]
It may be true that you don't link a static library with another static library (a CocoaPod lib), but what if the static library includes headers from the CocoaPod library? How do you structure the Podfile?

**Comment by chappejw** [comment]
One of my projects already includes Minzip in a static library which now interferes with the renamed LK_* Minzip included in LaunchKit. Any way around this? Another developer has suggested to create a framework from LaunchKit. Is this the right way to do this?
