### ISSUE TITLE
iOS Message Extension with CocoaPods: Invalid Bundle

### ISSUE THREAD

**Issue by phr85** [CocoaPods/CocoaPods#8300]
I have a standalone iMessage Extension with Cocoapods.

Xcode: 10.1 Min SDK Target: 11.0 CocoaPod Version: 1.5.3

My CocoaPods File: 
`platform :ios, '11.0'

 target 'App' do
   use_frameworks!
 end

 target 'App MessagesExtension' do
   use_frameworks!
   pod 'Alamofire'
   pod 'Firebase/Core'
 end`

I can run my Extension in Simulator. After uploading App (App Extension) I get:

 Invalid Bundle - Ensure that app executables and bundled frameworks use consistent architectures
What I figure out is that "Container" App contains "Architectures: armv7, armv7s, and arm64" but my Extension and all Frameworks only "arm64".

 "Build Active Architecture Only" is set to "NO"
Someone use CocoaPods in successfully in their App Extension App?

I appreciate any kind of hints or links!

**Comment by segiddins** [comment]
Please add a sample project that reproduces the issue
