### ISSUE TITLE
Pod install adds a libPods to the framworks group

### ISSUE THREAD

**Issue by shaharmor** [CocoaPods/CocoaPods#8301]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
- Built an obj-c cocoa touch framework, with the following podspec:
```
Pod::Spec.new do |s|  
    s.name              = 'MyPodKit'
    s.version           = '1.3.0'
    s.summary           = 'MyPod'
    s.homepage          = 'https://www.MyPod.com/'

    s.author            = { 'Name' => 'dev@MyPod.com' }
    s.license           = { :type => 'Proprietary', :file => 'LICENSE' }
    s.source            = { :http => "https://www.MyPod.com/MyPod.zip" } 

    s.ios.deployment_target = '8.0'
    s.ios.vendored_frameworks = 'iOS/MyPod.framework'

    s.tvos.deployment_target = '11.0'
    s.tvos.vendored_frameworks = 'tvOS/MyPod.framework'
end
```

- Created a new project (Either iOS single-view-app or tvOS single-view-app).
- Run `pod init`
- Update the Podfile to this:
```
platform :ios, '8.0'

target 'test-cocoapods-ios' do
  # use_frameworks!

  pod 'MyPod', :path => '/path/to/MyPod'

end
```
- Run `pod install`
- Close the project, open the workspace

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Not to have a `liPods-[appName].a` file in the `Framworks` group, as its both not needed, and doesn't exist, which causes an error when building unless I manually remove it

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
A static library `liPods-[appName].a` is referenced in the `Frameworks` group, even though it doesn't exist and doesn't do anything

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G3025)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 48f4c1d7b7b18d6981039f9c2ba8720c60ab4c96
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

Note: I tested it also with latest stable, same issue

**Comment by segiddins** [comment]
> Not to have a liPods-[appName].a file in the Framworks group, as its both not needed, and doesn't exist, which causes an error when building unless I manually remove it

What error does it cause? Can you please share a project that reproduces the error?

**Comment by shaharmor** [comment]
Hey @segiddins 
I managed to identify the problem and have a project that reproduces it.

The problem only occurs if you first create an empty **workspace**, than add a new project to it and work on that project.

If you only have a project when you run the `pod install` phase, it works.

But if you already have a workspace in your parent folder that contains the project, it fails with this error:
```
ld: library not found for -lPods-cocoa-app
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Example framework project: https://github.com/shaharmor/cocoa-framework
Example app workspace + project: https://github.com/shaharmor/cocoa-workspace

What happens is that `pod install` create a new workspace in the same folder of the project, but we already have an existing workspace in the parent folder that we use (We do it to consolidate multiple projects together).

I guess that cocoapods doesn't modify the parent workspace accordingly, which is what causes the error.

If I open the workspace the cocoapods created, it does work.

But I don't work with separate projects, but with 1 workspace that contains multiple ones.

**Comment by segiddins** [comment]
You can tell cocoa pods what workspace to use: https://guides.cocoapods.org/syntax/podfile.html#workspace

**Comment by shaharmor** [comment]
Shame on me :(

I would have thought that CocoaPods would traverse up the tree and check if any xcworkspace file exists that references this project
