### ISSUE TITLE
Install some dependencies with swift static library cause build fail 

### ISSUE THREAD

**Issue by marcuswu0814** [CocoaPods/CocoaPods#8303]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Using [static libraries](http://blog.cocoapods.org/CocoaPods-1.5.0/).
Run `pod install` and build project

## What did you expect to happen?

Running success.

## What happened instead?

But compiler can't found some header files.

## CocoaPods Environment

1.5.3

## Project that demonstrates the issue

[reproduces project](https://github.com/marcuswu0814/CocoapodsTest)

If using a workaround that adding a `"${PODS_ROOT}/Headers"` and set to recursive, it can build success but is there had any good solution to fix this out?

**Comment by marcuswu0814** [comment]
Hi @segiddins, it seems work, but why? what's the different?

**Comment by segiddins** [comment]
Not sure, but a lot of work went into refactoring build settings generation in 1.6

**Comment by dnkoutso** [comment]
@marcuswu0814 should we close?

**Comment by marcuswu0814** [comment]
Sure, thanks. 😃
