### ISSUE TITLE
create swift child cocoapods used OC third library

### ISSUE THREAD

**Issue by snailjj** [CocoaPods/CocoaPods#8306]
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `JJSocketManager` depends upon `CocoaAsyncSocket`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

':modular_headers => true'. where I can write

**Comment by snailjj** [comment]
s.subspec 'Socket' do |st|
      st.source_files = 'JJSocketManager/Socket/*.swift'
      st.dependency 'CocoaAsyncSocket'
  end

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
