### ISSUE TITLE
Exclude local spec-repos directory from backups

### ISSUE THREAD

**Issue by sonicdoe** [CocoaPods/CocoaPods#8308]
The size of the [CocoaPods master repo](https://github.com/CocoaPods/Specs) on disk is well over 1 GB right now (see also #7046). Not only that, the repo is also included in Time Machine backups as can be verified by `tmutil isexcluded ~/.cocoapods/repos/master`.

Since CocoaPods repos are merely caches, I’d suggest excluding the local spec-repos directory from backups. This can be achieved using `tmutil addexclusion ~/.cocoapods/repos` which adds the extended attribute `com.apple.metadata:com_apple_backup_excludeItem`. This attribute not only helps Time Machine but can also be picked up by other backup applications.

If there’s any interest in this feature, I’d be happy to give the implementation a try myself.

---

✓ I’ve read and understood the [contributing guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) and have done my best effort to follow 🌈

**Comment by orta** [comment]
This is a great idea IMO 👍

**Comment by segiddins** [comment]
Sounds like a good idea, but we need to make sure things work on machines that

- don't have time machine set up
- don't use hfs+/apfs
- aren't macOS

**Comment by dnkoutso** [comment]
Yes!

**Comment by sonicdoe** [comment]
> don't have time machine set up

I haven’t tested this yet but I don’t think `tmutil addexclusion` cares about whether Time Machine is actually enabled. It simply writes an extended attribute.

> don't use hfs+/apfs

This should be seamlessly handled by macOS. When trying to use extended attributes on a file system which does not support them, macOS creates a “dot-underscore” file to simulate them.

> aren't macOS

Does CocoaPods support non-macOS operating systems? I was under the impression that it’s strictly limited to macOS.

**Comment by segiddins** [comment]
CocoaPods should run fine on any posix system

**Comment by amorde** [comment]
The Travis tests are run on Ubuntu, for example

**Comment by sonicdoe** [comment]
I’d still like to work on this but haven’t found any time recently. If someone else wants to grab it, feel free!
