### ISSUE TITLE
Pod installable but not visible on cocoapods.org 

### ISSUE THREAD

**Issue by gammelby** [CocoaPods/CocoaPods#8309]
<!--

* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Successfully deployed to cocoapods.org and pod is installable from projects. The pod shows up in search result.

## What did you expect to happen?

When searching for pod (NabtoAPI) and clicking the search result, the pod page should be shown. 

## What happened instead?

The pod's associated www page is shown.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8a7c90c565d3268846fc4bcd11b79a9b75283508
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/nabto/nabto-api-pod

**Comment by dnkoutso** [comment]
Please provide more information. What pod? Also the changes propagate through slowly.

If possible please also file a much more detailed issue under this repo https://github.com/CocoaPods/cocoapods.org instead.

**Comment by gammelby** [comment]
The name was specified in the ticket. The problem has been going on for about a month.

**Comment by dnkoutso** [comment]
Which ticket? I do not see it can you specify?

**Comment by gammelby** [comment]
Uh, I thought you removed the body somehow? I submitted a full ticket following the template (... but clicked some github issue beta preview thing that may have screwed up something). Anyways, I will re-submit under cocoapods.org as it sounds more appropriate.

**Comment by gammelby** [comment]
https://github.com/CocoaPods/cocoapods.org/issues/390 ... sorry about the confusion
