### ISSUE TITLE
Autocomplete with test specs doesn't work in Xcode 9 or 10

### ISSUE THREAD

**Issue by jverkoey** [CocoaPods/CocoaPods#8312]
### Repro steps:

```
git clone https://github.com/material-components/material-components-ios.git
cd material-components-ios/catalog
pod install
open MDCCatalog.xcworkspace
```

Expand Pods -> Development Pods -> MaterialComponents -> ButtonBar -> tests -> unit

Open `ButtonBarButtonTitleCasingTests.swift`

Add a new line after line 24.

Start typing `buttonBar`.

Expected behavior: auto-complete kicks in and buttonBar has a valid and known type.

Actual behavior:

<img width="737" alt="screen shot 2018-11-27 at 4 34 33 pm" src="https://user-images.githubusercontent.com/45670/49113040-721cb180-f262-11e8-9860-c8fb5d2ec4dd.png">

dot auto-completion also does not suggest any APIs.

### Things I've tried

- Clean build.
- Closing and reopening Xcode.
- Blowing away derived data.
- Doing all of the above in different orders.
- Waiting for indexing to finish.
- Hitting Cmd+S while the file is open.
- Going for a walk.

### What does work

Objective-C autocompletion in test files does work.

**Comment by dnkoutso** [comment]
Do you have suggestions on how CocoaPods can fix this? CocoaPods creates the project. Can you create an Xcode project and show that it works without CocoaPods?

All I am asking is why this wouldn't be a radar filed to Apple?

**Comment by dnkoutso** [comment]
And make sure the Xcode project without CocoaPods has the same structure, i.e 2 xcodeprojs and dependencies between them etc.
