### ISSUE TITLE
Sending stats should be asynchronous

### ISSUE THREAD

**Issue by ZevEisenberg** [CocoaPods/CocoaPods#8316]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`.

## What did you expect to happen?

Pods install, and I don't have to wait any longer than is absolutely necessary.

## What happened instead?

Pods install like normal, but then I have to wait an extra few seconds at the end of the invocation for the "sending stats" step to complete. When I'm on a slow connection (I often work over a tethered connection on my commute), this can take a fair few seconds, and on a project that doesn't check in pods, jumping between a couple branches, this can quickly add up. It would be great if the "Sending stats" message appeared in the log, as it does now, but then immediately returned, and any network activity that needs to happen can happen in the background. I don't think most users care if sending stats succeeds or not, so it's annoying to have to wait for it every time.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.0 (10A255)
         Git : git version 2.19.2
Ruby lib dir : /Users/zeisenberg/.rvm/rubies/ruby-2.4.4/lib
Repositories : REDACTED - git@github.com:REDACTED/REDACTED.git @ redacted
               master - https://github.com/CocoaPods/Specs.git @ 6b7e6102cf91d09eca9cd0ddeaa0513e6e5d876c
```

### Installation Source

```
Executable Path: /Users/zeisenberg/.rvm/gems/ruby-2.4.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
project 'REDACTED.xcodeproj'

platform :ios, '10.0'

pre_install do |installer|
    REDACTED IRRELEVANT THINGS
end

abstract_target 'defaults' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'SwiftLint'
  pod 'REDACTED PRIVATE POD', :path => 'WOULDN’T YOU LIKE TO KNOW'
  pod 'REDACTED PRIVATE POD', :path => 'WOULDN’T YOU LIKE TO KNOW'
  pod 'REDACTED PRIVATE POD', :path => 'WOULDN’T YOU LIKE TO KNOW'
  pod 'REDACTED PRIVATE POD', :path => 'WOULDN’T YOU LIKE TO KNOW'

  pod 'REDACTED PUBLIC POD'
  pod 'REDACTED PUBLIC POD'

  target 'REDACTED'
end
```

**Comment by amorde** [comment]
I actually just had this thought the other day, definitely agree (though it should still print a message "Sending stats")

👍 for me

**Comment by amorde** [comment]
Taking a look at this, it appears that a large portion of the time is actually spent computing the stats to send - the sending part is very quick. Nonetheless the work to compute the stats could be done in a fork
