### ISSUE TITLE
Local Pod and .framework

### ISSUE THREAD

**Issue by onato** [CocoaPods/CocoaPods#832]
I am trying to get my local pod to add a third party framework (WFConnector.framework).

I am getting the following compile error...

```
#import <WFConnector/WFConnector.h>  // file not found
```

I have managed to get the .framework into the Pods-resources.sh and the framework is being copied correctly into the build folder. 

I have the following in my .podspec...

```
  s.resources = ["Resources/**/*.*", "Frameworks/WFConnector.framework"]
  s.preserve_paths =  'Frameworks/WFConnector.framework'
  s.framework  = 'WFConnector', 'ExternalAccessory', 'CoreBluetooth'
  s.ios.xcconfig       =  { 'FRAMEWORK_SEARCH_PATHS' => '"$(inherited)" "$(PODS_ROOT)/../../../Modules/MYPOD/Frameworks/"'}
```

At the moment the only way I can get it to compile is by dragging the WFConnector.framework into the frameworks folder of the Pods project.

Can someone tell me what I am missing?

**Comment by sauravambastha** [comment]
Hi,
Ian trying to make a simple app with the integration of ANT MACOSX library. I want to control the ANT Library output through my designed screen objects. I have referred wahoo KICKRDemo OS X sample for the same. But when i am trying to compile it showing the error WFConnector.h File not found. Can you help to to get rid over this ?
Here the code of .h file 


![screen shot 2015-11-25 at 6 18 02 pm](https://cloud.githubusercontent.com/assets/13886407/11397647/02b8b33e-93a1-11e5-8245-43157141b5d9.png)

#import <Cocoa/Cocoa.h>
#import <WFConnector/WFConnector.h>


@interface AppDelegate : NSObject <NSApplicationDelegate , WFHardwareConnectorDelegate >

{
    NSWindow *window ;
    NSArray *deviceParams;
    BOOL deviceInfoUpdated;
    BOOL isSearching;
    NSString *statusString;
    NSButton *connectButton;
    NSTextField *deviceIdLabel;
    NSButton *enableANTButton;
    NSTextField *antAvailableLabel;
    NSButton *searchButton;
    NSButton *connectSCButton;
    
}
@property (assign) IBOutlet NSWindow *window;
@property (retain) NSArray *deviceParams;
@property (retain) NSMutableArray *discoveredSensors;
@property (retain) NSString *statusString;
@property (assign) IBOutlet NSButton *connectButton;
@property (assign) IBOutlet NSTextField *antAvailableLabel;
@property (assign) IBOutlet NSButton *enableANTButton;
@property (assign) IBOutlet NSTextField *deviceIdLabel;
@property (assign) IBOutlet NSTextField *signalLabel;
@property (assign) IBOutlet NSTextField *connectionStatusLabel;

// Connection
- (IBAction)enableBTLEClicked:(id)sender;
- (IBAction)enableANTClicked:(id)sender;
- (IBAction)connectButtonClicked:(id)sender;
- (IBAction)proximityCheckBoxClicked:(id)sender;
- (IBAction)wildcardCheckBoxClicked:(id)sender;


@end

**Comment by malhal** [comment]
Any more hints on this? I'm also getting my framework header not found in my example app. I'm using pod lib create so my paths are different from all of those SDK podspecs above.
