### ISSUE TITLE
in spec file, specify dependency a git url

### ISSUE THREAD

**Issue by HJaycee** [CocoaPods/CocoaPods#8322]
For example:

I have a lib. It's name is  as same as AFNetworking in `https://github.com/AFNetworking/AFNetworking.git`. 

But I want use my own AFNetworking in `https://www.abc.com/AFNetworking.git`
```
Pod::Spec.new do |s|
  s.dependency 'AFNetworking', :git => 'https://www.abc.com/AFNetworking.git'
end
```
How can I do ?

**Comment by dnkoutso** [comment]
This is not supported nor are any plans to support it. You can override this in the `Podfile` only.

Published specs are meant to use semver to locate dependencies. Consuming your podspec with such declaration would make it successful for one SHA but the git repo might change causing breakages and unexpected results and also make builds non-hermetic.

**Comment by HJaycee** [comment]
Thanks for your reply. But when I use `pod repo push xxx`, it always failed.

Because `xcodebuild` can not find some methods or properties in `https://github.com/AFNetworking/AFNetworking.git` which are defined in `https://www.abc.com/AFNetworking.git`.

How can I make `pod repo push xxx` success.

```
 - ERROR | [iOS] xcodebuild:  xxx.m:26:71: error: property 'xxx' not found on object of type 'xxx *'
[!] The `KSWeexKit.podspec` specification does not validate.
```
