### ISSUE TITLE
cocoapods adds suffix to framework name, results in compilation errors

### ISSUE THREAD

**Issue by arielelkin** [CocoaPods/CocoaPods#8323]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

My Podfile is referring a local podspec:

```ruby
 target "MyTarget" do
        pod 'MySDK', :path => '../path/to/mysdk'
```

when I run `pod install`, among the targets in the generated Pods.xcodeproj is a corresponding framework with a mysterious suffix: `MySDK-39199c20`.  There is also a `MySDK-39199c20-umbrella.h`, a `MySDK-39199c20-dummy.m`, etc. 

I'm now getting `No such module 'MySDK'` compilation errors. I tried `pod deintegrate` and deleting `DerivedData` a couple of times already. Any thoughts? 

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.18.0

cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Are you using subspecs? The framework name should not matter. need a sample app here and its best to ask these questions in StackOverflow under cocoapods tag

**Comment by arielelkin** [comment]
Yes, i'm using subspecs and private pods. Unfortunately I'm unable to reproduce the issue in a sample app. 

Let me know if you want me to close this and move it over to SO.

**Comment by dnkoutso** [comment]
Subspecs would add the suffix but it shouldnt affect the framework module and name created.

**Comment by dnkoutso** [comment]
Going to preemptively close and I _will_ re-open if you can get a sample for us so we can debug!
