### ISSUE TITLE
Swift Test Spec Headers Unavailable in Objective-C Tests

### ISSUE THREAD

**Issue by SlaunchaMan** [CocoaPods/CocoaPods#8327]
🌈

* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Created a library that’s mostly Swift, but that I want to work from Objective-C, too. To that end, I created some test files in Objective-C to ensure that the library works from the language. Then, I added some helper functions to a Swift test file and wanted to use them in my Objective-C tests. This all works great from Xcode. I also have a test spec defined in my podspec so that tests run when I lint the library. The problems start when I run `pod lib lint`.

## What did you expect to happen?
The Swift header import looks like this (for a project named MyProject):
```Objective-C
#import "MyProjectTests-Swift.h"
```

I expect this to work when I run `pod lib lint`.

## What happened instead?
When I run `pod lib lint`, I get this output:
```
    - NOTE  | [iOS] xcodebuild:  :9: fatal error: 'MyProjectTests-Swift.h' file not found
```

## CocoaPods Environment
<details>
<summary>Redacted environment</summary>

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.2
Ruby lib dir : /Users/jeff/.rbenv/versions/2.5.3/lib
Repositories : detroit-labs - git@github.com:detroit-labs/detroit-labs-specs.git @ 90fd1ac1e0b30403afd5ea66b6353d058267efdd
               detroit-labs-1 - https://github.com/detroit-labs/REDACTED-specs.git @ 1cd9412413fcab4c51237a705fb6ee26ed26c003
               REDACTEDSpecs - git@github.com:detroit-labs/REDACTED-specs.git @ 1cd9412413fcab4c51237a705fb6ee26ed26c003
               master - https://github.com/CocoaPods/Specs.git @ 091ea50e8a3c1bbd33c6b72d6e63ddf886b4a649
```

### Installation Source

```
Executable Path: /Users/jeff/.rbenv/versions/2.5.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-keys        : 2.0.6
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
slather               : 2.4.6
```

### Podfile

```ruby
workspace 'REDACTED'

plugin 'cocoapods-keys', {
  :project => "REDACTEDExample/REDACTEDExample",
  :target => 'REDACTEDExample',
  :keys => [
    "TeamID",
    "REDACTEDClientID",
    "REDACTEDClientSecret"
  ]
}

target 'REDACTEDExample' do
  platform :ios, '9.0'
  project 'REDACTEDExample/REDACTEDExample.xcodeproj'
  use_frameworks!

  pod "REDACTED/Valet", :path => "."

  pod "Crashlytics"
  pod "Fabric"
  pod "UILabel+Copyable"
end

target 'REDACTEDTests' do
  platform :ios, '8.0'
  project 'REDACTED.xcodeproj'
  use_frameworks!

  pod "OHHTTPStubs/HTTPMessage"
  pod "OHHTTPStubs/Swift"
end
```
</details>

## Project that demonstrates the issue
[MixedTestSpecExample.zip](https://github.com/CocoaPods/CocoaPods/files/2644752/MixedTestSpecExample.zip)

**Comment by SlaunchaMan** [comment]
Note: This could be fixed by adding setting the `SWIFT_OBJC_INTERFACE_HEADER_NAME` build setting in the generated test project to "`TEST SPEC NAME`-Swift.h".

**Comment by SlaunchaMan** [comment]
In the meantime, I’ve developed a two-step workaround. We can reveal the header name as a custom preprocessor macro. First, define a new build setting in your test spec definition in your Podspec:
```Ruby
ts.pod_target_xcconfig = { 'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) SWIFT_HEADER_PATH=$(SWIFT_OBJC_INTERFACE_HEADER_NAME)' }
```

Then, in your Objective-C file, import the macro as a header:
```Objective-C
#define QUOTE(name) #name
#define STR(macro) QUOTE(macro)

#import STR(SWIFT_HEADER_PATH)
```

Of course, you’ll have to add that same setting to your local Xcode project for testing during development.

**Comment by dnkoutso** [comment]
This could be added fairly easy in `pod_target_installer.rb` where all target installation is setup.

**Comment by dnkoutso** [comment]
Would also love a test for this.
