### ISSUE TITLE
succes in 1.2.1 but fail in 1.6.0.beta.2

### ISSUE THREAD

**Issue by suihan** [CocoaPods/CocoaPods#8329]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod update`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
 Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
fail in analyzing dependence，info：
 CocoaPods could not find compatible versions for pod "MCECore"
In Podfile:
    MCECore (= 0.1.15)

    MGJMeProfile (= 0.0.16) was resolved to 0.0.16, which depends on
      MGJSearch was resolved to 0.3.133, which depends on
        MGJiPhoneSDK (~> 0.7.414) was resolved to 0.7.471, which depends on
          MCECore

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.7.8
        Host : Mac OS X 10.13.6 (17G3025)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/lesetong/.rvm/rubies/ruby-2.2.4/lib
Repositories : mogujie-cocoapodsrepos-cocoapodsrepospecs - http://gitlab.mogujie.org/CocoapodsRepos/CocoapodsRepoSpecs.git @ 344c09115bfc1a5d60fbc54bb55839f3106f34bd
               mogujie-huineng-mgjpodspec-framework - http://gitlab.mogujie.org/huineng/mgjpodspec-framework.git @ 1e52065ddd05e3c760065360ad8d82c607549b2d
               mogujie-im-impodspecs - http://gitlab.mogujie.org/im/IMPodSpecs.git @ f5b2398b07b9c3c787c3ce0f7992ba8195561f5e
               mogujie-ios-team-3rdpartyframeworkspec - http://gitlab.mogujie.org/ios-team/3rdpartyframeworkspec.git @ f4251fde17ffca5c76effe9c1be2b16e4a0915cc
               mogujie-ios-team-cocoapods-official-specs-mirror - http://gitlab.mogujie.org/ios-team/cocoapods-official-specs-mirror.git @ 130c0f1ef0918bc566aaffeb556a31f4ca7b897d
               mogujie-ios-team-mgjpodspec-framework - http://gitlab.mogujie.org/ios-team/mgjpodspec-framework.git @ 6cf1faa5bb0ebd27d5e9a9f2d196c3635afe719d
               mogujie-ios-team-mgjpodspec-nodependence - http://gitlab.mogujie.org/ios-team/mgjpodspec-nodependence.git @ e1086a08544dbecb5e495af6bbdabf882a84ebee
               mogujie-ios-team-mgjpodspecs - http://gitlab.mogujie.org/ios-team/mgjpodspecs.git @ 25217108d21edb2be5202f4c896486606057e809
               mogujie-ios-team-xdpodspecs - http://gitlab.mogujie.org/ios-team/xdpodspecs.git @ 6258cf5ae8f1dcc756c8a6dca536ee489ce82165
               mogujie-macos-macosbasepodspec - http://gitlab.mogujie.org/macOS/MacOSBasePodSpec.git @ fcd53f7e2db61309f7199b16e373eec29115fb9d
               mogujie-weshop-ios-weshoppodspecs - http://wxgitlab.mogujie.org/weshop-iOS/weshopPodSpecs.git @ 9c03db3c23d33e7e2e0115e5d00eb23f98922683
```

### Installation Source

```
Executable Path: /Users/lesetong/.rvm/gems/ruby-2.2.4/bin/pod
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Please provide sample app
