### ISSUE TITLE
Allow the user to customize the prefix headers and the xcconfigs

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#833]
See this thread for some context: http://stackoverflow.com/questions/12967220/i-want-to-allow-invalid-ssl-certificates-with-afnetworking

Essentially we should be able to declare in the podfile that I want pods to run with some other c flags that can manipulate the pod libraries themselves.

---

Renamed from:Add an ability to apply #defines to pods target from podfile

**Comment by segiddins** [comment]
With the advent of frameworks, I'm really not sure we need to implement this beyond the already-supported post-install hooks.

**Comment by neonichu** [comment]
Also does anything keep people from setting their own XCConfig in the project and including the one created by CP? They'd get a warning when doing a `pod install`, but that's about it or am I missing something?

**Comment by segiddins** [comment]
They won't even get the warning any more, if they actually include the CocoaPods one.

**Comment by neonichu** [comment]
And prefix headers should :fire: anyways - I'd also say this is not relevant anymore.

**Comment by batrinuvlad** [comment]
What's the solution to this after all?
I mean I've been trying to inject some code in all .pch files using the post_install hook, but no success https://stackoverflow.com/questions/58522119/inject-code-in-pch-files-from-pods-in-post-install
