### ISSUE TITLE
Podspec with Swift Static Library error on installation

### ISSUE THREAD

**Issue by sachinmobstac** [CocoaPods/CocoaPods#8332]
# Report
NearBee Swift Static Library

## What did you do?
I created a Sample App using the NearBee version 0.0.3, I was unable to use it in my Pod.

## What did you expect to happen?
The pod project should contain the NearBee target and should work normally.

## What happened instead?
No error was generated by the CocaoPods at the same time the NearBee target was not added to the pod project.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1b81d168d9d10cd43646fcf6ceb279af1cdf0c51
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate      : 1.0.2
cocoapods-fix-react-native : 2018.10.31.23
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-trunk            : 1.3.1
cocoapods-try              : 1.1.0
```

## Project that demonstrates the issue

https://drive.google.com/open?id=1s9P6RsUpa8Tb7JNlWUMUjnaIG1_SCx5W

**Comment by dnkoutso** [comment]
The target is a pre-built library. It is installed and available in the project.

In 1.6.0.x these targets will show as PBXAggregateTargets but 1.5.3 does the correct thing.

![screen_shot_2018-12-05_at_10_42_27_am](https://user-images.githubusercontent.com/310370/49536059-7d7f6680-f87a-11e8-8ffa-c233d6413bb3.png)

**Comment by sachinmobstac** [comment]
@dnkoutso It's not what I asked, the issue is that it is not showing this target in the Pods Project, which restricts the usage of the Pod. Attaching an image for reference.

<img width="1440" alt="screenshot 2018-12-06 at 7 57 55 am" src="https://user-images.githubusercontent.com/34122260/49557259-14a4f680-f92d-11e8-993b-06ba9b165072.png">

**Comment by dnkoutso** [comment]
Please try 1.6.0.beta.2 where the target now shows up in Pods.xcodeproj.

**Comment by sachinmobstac** [comment]
It works thanks.
