### ISSUE TITLE
UI Tests no longer run after Firebase/Core pod install

### ISSUE THREAD

**Issue by MrAPolk** [CocoaPods/CocoaPods#8337]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

When I installed the Firebase Core pod and tried running my test target it runs my unit tests correctly but fails to launch my UI tests.

I raised this issue with the Firebase team [here](https://github.com/firebase/firebase-ios-sdk/issues/2147) and they recommended its a CocoaPods issue.

I found one workaround solutions which is to add `$(FRAMEWORK_SEARCH_PATHS)` to the UI Test target's Runpath search paths. Which is also suggested [here](https://stackoverflow.com/questions/34990175/test-target-x-encountered-an-error-early-unexpected-exit-operation-never-finis).

## What did you do?

Try run my test target after a I installed Firebase/Core pod.

## What did you expect to happen?

My Unit and UI tests to run.

## What happened instead?

It failed to launch my UI tests giving the following error:

BrokenFirebaseCoreUITests-Runner.app (80714) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: The test runner failed to load the test bundle. Executable cannot be loaded for some other reason, such as a problem with a library it depends on or a code signature/entitlements mismatch.))

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.1
Ruby lib dir : /Users/apolk/.rbenv/versions/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 67b896ef7d187eccb6f5088812330091490ad3d4
```

### Installation Source

```
Executable Path: /Users/apolk/.rbenv/versions/2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrokenFirebaseCore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrokenFirebaseCore
  pod 'Firebase/Core', '5.13.0'

  target 'BrokenFirebaseCoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BrokenFirebaseCoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

A test project that replicates the issue can be found [here](https://github.com/firebase/firebase-ios-sdk/files/2648116/BrokenFirebaseCore.zip). Simply run the test target (CMD+U) to see the error.

**Comment by jjochen** [comment]
Same issue here.

It works fine without `use_framework!` btw.

**Comment by paulb777** [comment]
@amorde I've reproduced and verified the workaround.  It seems to be a long-time CocoaPods bug based upon https://stackoverflow.com/questions/34990175/test-target-x-encountered-an-error-early-unexpected-exit-operation-never-finis.  However, I haven't tried to investigate on the CocoaPods internal side yet.  I will do so in the next few weeks if no one else gets to it.

**Comment by jjochen** [comment]
The workaround doesn't seem to work for iOS 11 though.

**Comment by dnkoutso** [comment]
@MrAPolk The real fix here is to remove `inherit! :search_paths` from your UI test bundle. See more here https://github.com/CocoaPods/CocoaPods/pull/8423
