### ISSUE TITLE
Weird! I've created two pods with the same files, but one of them builds failed in my iOS project.

### ISSUE THREAD

**Issue by liaohuanyu** [CocoaPods/CocoaPods#8340]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I've created a public pod named 'xxxxx', when it's been integerated, my iOS project builds failed. So I create another one named 'KSDK1' which builds fine with the same files. I really don't know why this happens. Some suggestions would be greatfully appreciated.

## What did you expect to happen?

The pod named 'xxxxx' should buid fine in project just like 'KSDK1'.

## What happened instead?

The pod named 'xxxxx' builds failed.

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.8
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.1 (10B61)
         Git : git version 2.18.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : KSORepos - http://ksogit.kingsoft.net/kso_explore/KSORepos @ fc28aafbdea718c9a5c22025ff27239aebd202e3
               master - https://github.com/CocoaPods/Specs.git @ f07282c10ea4b8ec8141c155eae2b43c998bd0d3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Link of [the project](https://github.com/liaohuanyu/test20181207.git)

**Comment by amorde** [comment]
The link is inaccessible (maybe its private?) so we can't try it to attempt to reproduce.

Can you post the error you are getting or update the link to the sample project?

**Comment by liaohuanyu** [comment]
Fixed! It seems like that the content of my podspec file is not correct. File with suffix of ".a" should not been included in "s.source_files", but in "s.vendored_libraries".
The wrong one:
```
Pod::Spec.new do |s|
  s.name         = "KingsoftOfficeSDK"
  s.version      = "1.9.8"
  s.summary      = "A short summary of KingsoftOfficeSDK."
  s.description  = "A short description of KingsoftOfficeSDK."
  s.homepage     = "https://github.com/WPSOffice-Dev/KingsoftOfficeSDK"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author       = { "wps_ios" => "wps_ios@wps.cn" }
  s.source       = { :git => "https://github.com/WPSOffice-Dev/KingsoftOfficeSDK.git", :tag => s.version }
  s.source_files = 'KingsoftOfficeSDK/*.{h,a}'
end
```

The correct one:
```
Pod::Spec.new do |s|
  s.name         = "KingsoftOfficeSDK"
  s.version      = "1.9.8"
  s.summary      = "A short summary of KingsoftOfficeSDK."
  s.description  = "A short description of KingsoftOfficeSDK."
  s.homepage     = "https://github.com/WPSOffice-Dev/KingsoftOfficeSDK"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author       = { "wps_ios" => "wps_ios@wps.cn" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "https://github.com/WPSOffice-Dev/KingsoftOfficeSDK.git", :tag => s.version }
  s.source_files = 'KingsoftOfficeSDK/*.{h}'
  s.vendored_libraries = "KingsoftOfficeSDK/*.{a}"
end
```

Anyway, thanks a lot!
