### ISSUE TITLE
Use 'podspec :path =>'  in Podfile, the pod install , can't find my lib

### ISSUE THREAD

**Issue by lantony001** [CocoaPods/CocoaPods#8344]
# Report

## What did you do?

ℹ i use podspec in podfile, it seems don't work
i write like this:
podspec :path => '/Users/myName/Desktop/ios_common_library/CommonLib.podspec'
then run 'pod install'

## What did you expect to happen?

ℹ i want to load my privite repo in local path, but not in Development Pods mode
i know that use 
 pod 'CommonLib',  :path => '../ios_common_library/' will load my local codes

after pod install, it found other dependencies, but did't find mine like:(CommonLib.podspec), and i'm sure the path is correct.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.13.6 (17G2208)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'


target 'mytarget' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'AFNetworking', '<=3.1.0'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  ...

podspec :path => '/Users/myName/Desktop/ios_common_library/CommonLib.podspec'
end

**podspec :path => '/Users/myName/Desktop/ios_common_library/CommonLib.podspec'**  this line is my question

**Comment by dnkoutso** [comment]
Sorry this does not appear to be an issue with the library. Please post on stackoverflow under cocoapods tag.
