### ISSUE TITLE
pod lib lint failed with dependencies in Swift 3.2 on macOS Mojave

### ISSUE THREAD

**Issue by ldp940622** [CocoaPods/CocoaPods#8349]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have created a private lib on Swift 3.2, and dependent on a pod on Swift 3.2 too. After upgrading the macOS to Mojave,  I want to run `pod lib lint` to lint it.

## What did you expect to happen?

pod lib lint successfully.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  

`pod lib lint` failed. And I found that the reason is `xcodebuild` compile then dependency on **Swift 4.2**.

When I check the `App.workspace` by lint, the `Pods-App` just compile with Swift 4.2 not Swift 3.2.

I think this problem only show on macOS Mojave, and I never met it on macOS High Sierra. 

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7b77f848be0151cadf8c16208776e9af9218f75c
               saybot-repospec - git@git.saybot.net:ios/repospec.git @ 6267a8e98803c27fa5eab85af332954be004fa39
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Mojave and the generated App has nothing to do with this. Please paste the xcodebuild error msg and upload a sample app.

**Comment by ldp940622** [comment]
@dnkoutso I have create the test pod [here](https://github.com/ldp940622/TestPod).

You can find out that the travis-ci is successful on `osx_image: xcode9.4`, but failed on `osx_image: xcode10.1`.

Of course, I am not sure if it is the bug on SnapKit. 🤣

**Comment by dnkoutso** [comment]
Works with 10.1 for me.

```
    Touch /Users/dimitris/Library/Developer/Xcode/DerivedData/App-bhyrixjnymrzpeeoxwppqrnzrdis/Build/Products/Release-iphonesimulator/App.app (in target: App)
        cd /var/folders/0x/798grj997td8xhm6_jr85l680000gn/T/CocoaPods-Lint-20181212-2462-aifuo2-TestPod
        /usr/bin/touch -c /Users/dimitris/Library/Developer/Xcode/DerivedData/App-bhyrixjnymrzpeeoxwppqrnzrdis/Build/Products/Release-iphonesimulator/App.app
    
    ** BUILD SUCCEEDED **
```

**Comment by dnkoutso** [comment]
Please also specify `s.swift_version = '4.2'` in your podspec.

**Comment by dnkoutso** [comment]
You should request the author of SnapKit to upgrade and support this. In 1.7.0 there are ways to specify multiple swift versions.

**Comment by ldp940622** [comment]
@dnkoutso @amorde 
Alright, I think it is the bug of `SnapKit`, so I'll close this issue. Many thanks for the support.
