### ISSUE TITLE
Add pods to both main project and its subproject (library) and link them together

### ISSUE THREAD

**Issue by sryze** [CocoaPods/CocoaPods#8358]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a project that contains a subproject (a third-party SDK xcodeproj), which is a static library. This library requires the Facebook SDK, and my main project also uses the Facebook SDK.

I was trying to figure out how to integrate it into both targets and make include and linker paths work, but I don't see a clear solution after reading the docs and examples. I would like to know what is the suggested way to achieve this setup.

Here is what I've tried:

1. Leave the subproject included, add a target to the Podfile corresponding to this project, link both projects with FacebookSDK:

```
def facebook_sdk_pods
    pod 'Bolts'
    pod 'FBSDKCoreKit', '= 4.38.1'
    pod 'FBSDKLoginKit', '= 4.38.1'
end

target 'MyApp' do
    project 'MyApp.xcodeproj'
    facebook_sdk_pods
end

target 'OneAll' do
    project 'MyApp/Libraries/OneAll/OneAll.xcodeproj'
    facebook_sdk_pods
end
```

This sort of works but CocoaPods creates another project with the same name at the top level, so my project tree becomes:

```
- MyApp
--- Libraries/OneAll
- Pods
- OneAll
```

2. Remove the subproject, use a nested (?) target:

```
target 'MyApp' do
    project 'MyApp.xcodeproj'
    pod 'Bolts'
    pod 'FBSDKCoreKit', '= 4.38.1'
    pod 'FBSDKLoginKit', '= 4.38.1'

    target 'OneAll' do
        project 'MyApp/Libraries/OneAll/OneAll.xcodeproj'
        inherit! :search_paths
    end
end
```

Unfortunately this doesn't work - I receive a linker error because one of the symbols from the library can't be found by the main project (MyApp).

3. Use Podfile from [1], remove the subproject

Same result as [2].

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G3025)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bfe9b367e83998ecb0c37c297465f18ded926ec1
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```
```

**Comment by dnkoutso** [comment]
@sryze can you please upload a sample app demonstrating the issue? It makes it easier to diagnose these issues.

**Comment by mstaicu** [comment]
I struggle with this as well, and I fail to understand on why is it so hard from core maintainers to come up with a proper example for this use case
