### ISSUE TITLE
Credits not right for my repo

### ISSUE THREAD

**Issue by lingol** [CocoaPods/CocoaPods#8361]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a [repo](https://cocoapods.org/pods/MMKV) published for over 3 months. With a full readme, license, wiki and stuff. And get over [5.7k stars](https://github.com/Tencent/mmkv) on GitHub.

## What did you expect to happen?

The credits of my repo should be over 50.

## What happened instead?

Yet it's not. Specifically, CocoaPods shows that my repo has [**an empty readme**](https://cocoapods.org/pods/MMKV/quality), which is not right at all.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 747d63e2cc2b578ac6e6a499071f6c02f69473da
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
The quality indexes were shut down with CocoaDocs [last year](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/), I've gone and removed links to the indexes from the front-end https://github.com/CocoaPods/cocoapods.org/pull/393 which means people won't get confused about them anymore.
