### ISSUE TITLE
pod install --project-directory=project-dir will produce many symbolic links

### ISSUE THREAD

**Issue by edison0951** [CocoaPods/CocoaPods#8364]
# Report

## What did you do?
Run `pod install --project-directory=project-dir --verbose`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?
Errno::ELOOP - Too many levels of symbolic links @ realpath_rec - my-file-path

### Stack
```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 56qq-hcbspecs - git@git.56qq.com:iOS-Team/HCBSpecs.git @ a0cd408802960bbcc35f8d4b5286874108d78b2d
               coding-leqi-specs - https://git.coding.net/leqi/Specs.git @ 39a62257b2f7953ea79baa1781aa52d0e9ee540f
               edu-git-cocoapods-specs - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git @ 0c1a60cd1158727a8d902f7f10ac035712f0ab13
               master - https://github.com/CocoaPods/Specs.git @ cf44b5a82b7ead5bb47decd72ab748680ac5e336
               ymmoa-iosymm-mbspecrepo - git@code.ymmoa.com:iOSYmm/MBSpecRepo.git @ 0261ea0f33ecc2d5ce9cf47abbf9dd8a5b02d200
               ymmoa-iosymm-ymmspecrepo - git@code.ymmoa.com:iOSYmm/YMMSpecRepo.git @ 718fb16ceee2f26d133ba33e7c61224d21668a70
```

### Installation Source

```
Executable Path: /usr/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```
I found in my project's parent dir that produce many symbolic links. And I want to know what to do will produce symbolic links in podspec file.

**Comment by dnkoutso** [comment]
Can you please provide a sample app? This is most likely a bug.

**Comment by edison0951** [comment]
I use my private cocoapod repo. So I can't provide the sample app. Can you tell me what's the code in podspec can product symbolic links. And the situation is only arise  when I use  the --project-directory parameter.

**Comment by dnkoutso** [comment]
@edison0951 I dont understand your question. Can you please provide a sample even with the master (non-private) cocoapods repo?

**Comment by edison0951** [comment]
how can I provide a sample even with the master?

**Comment by dnkoutso** [comment]
I need clear step-by-step instructions on how to reproduce this.

**Comment by paulb777** [comment]
@edison0951 Please share an example with exact instructions including which directory to go to and what the problematic symbolic links are.  Instructions for creating a CocoaPod are at https://guides.cocoapods.org/making/using-pod-lib-create.html.
