### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by phamotcreations** [CocoaPods/CocoaPods#8366]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expect to happen?

install pods successfully

## What happened instead?

Analyzing dependencies
Setting up CocoaPods master repo
  $ /usr/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
  Cloning into 'master'...
  fatal: unable to access 'https://github.com/CocoaPods/Specs.git/': error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

## CocoaPods Environment
v1.5.3, MacOS v10.14.2 Mojave. Xcode 10.1

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

**Comment by dnkoutso** [comment]
Please ask StackOverflow under `cocoapods` tag for this issue. Seems like a network issue with respect to SSL and not a cocoapods issue specifically.

**Comment by phamotcreations** [comment]
Thanks @dnkoutso
