### ISSUE TITLE
How can I source the develop repo?

### ISSUE THREAD

**Issue by Lidalu** [CocoaPods/CocoaPods#8371]
I push the  repo  a develop branch, not master branch, then how to source the develop branch.
source 
like source 'git@github.com:CocoaPods/Specs.git', branch 'develop'

But not like pod 'AFNetworking', branch: 'develop'

**Comment by dnkoutso** [comment]
This is not officially supported. You can maybe switch the repo to the branch for your local machine but no support from Podfile.

**Comment by Lidalu** [comment]
Looking forward to official support.
