### ISSUE TITLE
Unable to use resource bundle from podspec 

### ISSUE THREAD

**Issue by tinder-hemanthprasad** [CocoaPods/CocoaPods#8372]
* I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Unable to access resources from `resource_bundles` in the podspec.

## What did you expect to happen?

I should be able to access resource bundle from the main app.

Podspec file:

```
  Pod::Spec.new do |s|
  s.name                         = "ResourcesBundleExample"
  s.version                      = "0.0.1"
  s.summary                      = "Resources in a spec test pod."
  s.description                  = "This spec specifies images as resources."

  s.ios.deployment_target        = '8.0'
  s.osx.deployment_target        = '10.9'
  s.homepage                     = "https://cocoapods.org"
  s.license                      = { :type => "MIT", :file => "../../../LICENSE" }
  s.author                       = { "Ben Asher" => "benasher44@gmail.com" }
  s.source                       = { :path => "." }
  s.source_files                 = "Example.swift"
  s.resource_bundles             = {"ResourcesBundleExample" => ["Resources/*.jpg"] }
end
```
Access code:

    NSBundle *b = [NSBundle bundleForClass:Empty.class];
    NSBundle *rb=[NSBundle bundleWithURL:[b URLForResource:@"Resources" withExtension:@"bundle"]];
    self.imageView.image = [UIImage imageNamed:@"cat1" inBundle:rb compatibleWithTraitCollection:nil];

## What happened instead?

 I'm experiencing the following error.
```
Error Domain=NSCocoaErrorDomain Code=4 "The bundle “Resources.bundle” couldn’t be loaded because its executable couldn’t be located." UserInfo={NSLocalizedFailureReason=The bundle’s executable couldn’t be located., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSBundlePath=/Users/hemanthprasad/Library/Developer/CoreSimulator/Devices/DFC6A7FD-A2DA-4D54-82B6-D683A533419A/data/Containers/Bundle/Application/F17FB023-CD31-4695-8C5D-434AC212F337/Resource Bundle Example.app/Frameworks/ResourceExample.framework/Resources.bundle, NSLocalizedDescription=The bundle “Resources.bundle” couldn’t be loaded because its executable couldn’t be located.}
```

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/hemanthprasad/.rvm/rubies/ruby-2.5.1/lib
Repositories : facebook - https://github.com/facebook/Sonar.git @ f5e5c33c68db42e775585f006857ca722550265b
               master - https://github.com/CocoaPods/Specs.git @ 77d252b869df155f3895d669c842e29c916942d5
               tinderapp - https://github.com/TinderApp/proto.git @ 789366819647293964c2b1edfaf1bcc1381158ee
```

### Installation Source

```
Executable Path: /Users/hemanthprasad/.rvm/gems/ruby-2.5.1/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.2
cocoapods-dependencies : 1.3.0
cocoapods-generate     : 1.1.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.3.1
cocoapods-try          : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
use_frameworks!

workspace 'Examples.xcworkspace'
project 'Resource Bundle Example.xcodeproj'

target 'Resource Bundle Example' do
  pod 'ResourceExample', :path =>  'Example Pods'
  pod 'ResourcesExample', :path =>  'Example Pods'
  pod 'ResourceAssetsExample', :path =>  'Example Pods'
  pod 'ResourcesBundleExample', :path =>  'Example Pods'
end
```

## Project that demonstrates the issue

[Resource Bundle Example.zip](https://github.com/CocoaPods/CocoaPods/files/2704257/Resource.Bundle.Example.zip)

**Comment by amorde** [comment]
Hello @tinder-hemanthprasad!

I noticed there was a couple things strange about the example - the resource bundle is set as `"ResourcesBundleExample"` in the Podspec but the code attempts to load `"Resources.bundle"`. Also, the method `loadAndReturnError:` on `NSBundle` is meant to load _executable_ bundles - you do not need to manually load resource bundles using this method.

Then when loading the image using `[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]` function, per the docs you must specify the file extension if you are not loading either a PNG or an image from an asset catalog

Docs for the `imageNamed:` argument:

> The name of the image. For images in asset catalogs, specify the name of the image asset. For PNG image files, specify the filename without the filename extension. For all other image file formats, include the filename extension in the name.

Updating the code in the `ViewController.m` to the following works correctly for me:

```objc
- (void)viewDidLoad {
    [super viewDidLoad];
    NSBundle *b = [NSBundle bundleForClass:Empty.class];
    NSBundle *resourceBundle = [NSBundle bundleWithURL:[b URLForResource:@"ResourcesBundleExample" withExtension:@"bundle"]];
    
    self.imageView.image = [UIImage imageNamed:@"cat1.jpg"
                                      inBundle:resourceBundle
                 compatibleWithTraitCollection:nil];
    // loads successfully
}
```

I'm going to go ahead and close this but please let me know if there is something else going on here that I missed. Thanks!
