### ISSUE TITLE
The Method named 'push_repo' was hard coded by 'master'

### ISSUE THREAD

**Issue by Lidalu** [CocoaPods/CocoaPods#8374]
### I found I can add the develop branch repo.

pod repo add --help
Usage:

    $ pod repo add NAME URL [BRANCH]

      Clones `URL` in the local spec-repos directory at
      `/Users/lilu/.cocoapods/repos`. The remote can later be referred to by `NAME`.

Options:

    --progress   Show the progress of cloning the spec repository
    --silent     Show nothing
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command` 

But I can't pod repo push the repo to remote develop branch. Because in /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/repo/push.rb file, the method named 'push_repo' has been hardcode by 'master',  you should receive push_branch from the command line like --sources=https://github.com/artsy/Specs,master.

`pod repo push libQIMKit-iOS-Cook-Develop QIMDataBase.podspec --allow-warnings --push-branch=develop
`
![image](https://user-images.githubusercontent.com/16262826/50399467-a1b7ce80-07ba-11e9-9d55-ad102242d89a.png)

**Comment by amorde** [comment]
Yeah, I don't think it's worth the extra complexity. What's the use case for having multiple branches on a single spec repo?
