### ISSUE TITLE
Cocoapods frameworks does not support provisioning profiles

### ISSUE THREAD

**Issue by jsaha2007** [CocoaPods/CocoaPods#8375]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ xcodebuild -exportArchive -exportOptionsPlist exportPlists/qa.plist -archivePath Artifacts/TPS/XXXXX.xcarchive -exportPath Artifacts/TPS

## What did you expect to happen?

ℹ Generate the .IPA in the "Artifacts" folder.

## What happened instead?

ℹ Throwing error with the pods I have used in application from CI(Jenkins) tool. 
**exportArchive: KeychainSwift.framework does not support provisioning profiles. **
**error: exportArchive: Alamofire.framework does not support provisioning profiles.**

## CocoaPods Environment

ℹ ### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a0ea3e04e60e09cba711eb22783643ea2a6b4f9f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

workspace 'XXXXXX'
target 'XXXXX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '4.7'
  pod 'KeychainSwift', '~> 13.0'

  # Pods for XXXX

  target 'XXXXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XXXXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    configuration.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    configuration.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
    configuration.build_settings['CODE_SIGN_STYLE'] = ""
  end
end
```

**Comment by dnkoutso** [comment]
Can you please include a sample app?

**Comment by jsaha2007** [comment]
Thanks @dnkoutso for replying, but unfortunately, this is the project from my employer which I am working on, and I will not be able to upload anything from that app. and I don't have any personal subscription for appstore that I can create my own sample app to show. 

You can ask anything that you want, I can answer.

Sorry for this again. Please help me.

**Comment by amorde** [comment]
Could you try removing this section from your post_install hook?

```ruby
configuration.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
configuration.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
configuration.build_settings['CODE_SIGN_STYLE'] = ""
```
