### ISSUE TITLE
NoMethodError - undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by ucarbehlul** [CocoaPods/CocoaPods#8377]
### Command

```
/opt/local/bin/pod install --verbose
```

### Report

* What did you do?
I was running pod install to install dependencies.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-darwin18]
    RubyGems : 2.6.6
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.0 (10A255)
         Git : git version 2.19.1
Ruby lib dir : /opt/local/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6adefc22e9c2797b2d91b4c65d22db90acaac49b
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

def base_pods
  # Pods for xReactNative
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'TwitterKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKMessengerShareKit'
  pod 'AppsFlyerFramework'
  pod 'Kahuna'
  pod 'Google/SignIn'
end

target 'xProduction' do
    base_pods
end

target 'xStaging' do
    base_pods
end

target 'xDevelopment' do
    base_pods
end


target 'xReactNativeTests' do
    base_pods
end
```

### Error

```
NoMethodError - undefined method `size' for nil:NilClass
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/macho_file.rb:420:in `populate_mach_header'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/macho_file.rb:234:in `populate_fields'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/macho_file.rb:55:in `initialize_from_bin'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/macho_file.rb:33:in `new_from_bin'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/fat_file.rb:321:in `block in populate_machos'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/fat_file.rb:320:in `each'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/fat_file.rb:320:in `populate_machos'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/fat_file.rb:124:in `populate_fields'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho/fat_file.rb:63:in `initialize'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho.rb:31:in `new'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/ruby-macho-1.2.0/lib/macho.rb:31:in `open'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:431:in `dynamic_binary?'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:164:in `block in vendored_dynamic_frameworks'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:163:in `select'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:163:in `vendored_dynamic_frameworks'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:172:in `vendored_static_frameworks'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:122:in `add_static_dependency_build_settings'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:89:in `block in add_settings_for_file_accessors_of_target'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:86:in `each'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:86:in `add_settings_for_file_accessors_of_target'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:424:in `block in generate_vendored_build_settings'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:422:in `each'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:422:in `generate_vendored_build_settings'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:79:in `generate'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:107:in `update_changed_file'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:96:in `block in create_xcconfig_file'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `each'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `create_xcconfig_file'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:181:in `block (2 levels) in install_libraries'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `each'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `block in install_libraries'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:167:in `install_libraries'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:119:in `install!'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/opt/local/lib/ruby2.2/gems/2.2.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/opt/local/bin/pod:22:in `load'
/opt/local/bin/pod:22:in `<main>'
```

**Comment by ucarbehlul** [comment]
Removing contents of `Pods` folder solved the issue.

**Comment by dnkoutso** [comment]
Something was installed in your `Pods` folder that was failing. If you can reproduce it can you please upload sample

**Comment by ZhuHui19921129** [comment]
It happens pod install for Flutter,Flutter needs to upgrade, then flutter clean.  then flutter build iOS

**Comment by TheWalkingDead1024** [comment]
> It happens pod install for Flutter,Flutter needs to upgrade, then flutter clean. then flutter build iOS

It does not work for me. Could anybody help me with this issue?

**Comment by czqasngit** [comment]
> It happens pod install for Flutter,Flutter needs to upgrade, then flutter clean. then flutter build iOS

It works for me, thanks you!!!~

**Comment by victorkifer** [comment]
Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then

`
flutter clean
rm -Rf ios/Pods
rm -Rf ios/.symlinks
rm -Rf ios/Flutter/Flutter.framework
rm -Rf ios/Flutter/Flutter.podspec
`

**Comment by zhouyangyng** [comment]
> It happens pod install for Flutter,Flutter needs to upgrade, then flutter clean. then flutter build iOS

It works for me. Thanks~

**Comment by rufw91** [comment]
> Removing contents of `Pods` folder solved the issue.

Solved for me too

**Comment by kashbase** [comment]
works Thanks

**Comment by jiyeyuran** [comment]
It does not work for me. I am working on a react native project. I've tried `rm -rf Pods`, `pod install` and `pod update`.

**Comment by JigneshPatel23** [comment]
Thanks @victorkifer worked for me. (y)

**Comment by karan-rawal** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```

You just saved me. :)

**Comment by JoakimLiu** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```

Thank you

**Comment by DanielCardona** [comment]
`flutter clean
rm -Rf ios/Pods
rm -Rf ios/.symlinks
rm -Rf ios/Flutter/Flutter.framework
rm -Rf ios/Flutter/Flutter.podspec`

@victorkifer, you are my new hero! ;-)

**Comment by jurgenizer** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```
Thank you very very much @victorkifer - it worked!

**Comment by hasherhari** [comment]
> > Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> > ```
> > flutter clean
> > rm -Rf ios/Pods
> > rm -Rf ios/.symlinks
> > rm -Rf ios/Flutter/Flutter.framework
> > rm -Rf ios/Flutter/Flutter.podspec
> > ```
> 
> Thank you

**Comment by w819314930** [comment]
flutter clean
flutter pub get
pod install
problem solving

**Comment by a8thunder** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```

thanks you

**Comment by mreram** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```

Nice, solved!

**Comment by JasonXZJ** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```

It works for me. Thanks~

**Comment by MASKADEV** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```

thanks

**Comment by KohlsAdrian** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```

If it was on StackOverflow, this should be the accepted answer

**Comment by thenixoncompany** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```

save my day, thanku!

**Comment by padishahG** [comment]
> Also faced with this issue. Fixed by updating flutter and cocoa pods to the latest version and then
> 
> ```
> flutter clean
> rm -Rf ios/Pods
> rm -Rf ios/.symlinks
> rm -Rf ios/Flutter/Flutter.framework
> rm -Rf ios/Flutter/Flutter.podspec
> ```
thanks

**Comment by carusd** [comment]
no solution above works for me, have to remove all files from git

**Comment by azarAngga** [comment]
> 

thanks bro u make my day :)
