### ISSUE TITLE
No solution was found [!] Oh no, an error occurred.

### ISSUE THREAD

**Issue by SpikeLeeHom** [CocoaPods/CocoaPods#8379]
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Operation+not+permitted+%40+apply2files+-+%2FUsers%2Fjavis%2FDocuments%2FAME%2FPods%2FAMap2DMap-NO-IDFA%2FMAMapKit.framework%2FHeaders%2FMAAnnotation.h&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

[!] The `xxx[Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-AME_IM/Pods-AME_IM.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `xxx [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-AME_IM/Pods-AME_IM.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

**Comment by dnkoutso** [comment]
Sorry this report does not help us diagnose it. Please fill in template and provide a sample app if possible.
