### ISSUE TITLE
Is it possible to specify pod for all build configurations except certain one?

### ISSUE THREAD

**Issue by specialfor** [CocoaPods/CocoaPods#8386]
For instance, I have a few build configuration: Develop, **Prerelease**, PrereleaseDebug, Release, etc.
I want to install specific pod for all configurations except **Prerelease** one.
Is it possible to do?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
