### ISSUE TITLE
Troubles copying Info.plist with custom key/value pairs and Xcode10

### ISSUE THREAD

**Issue by ztepsa** [CocoaPods/CocoaPods#8396]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Updated Xcode from 9 to 10 and tried to build the framework as described in the old issue https://github.com/CocoaPods/CocoaPods/issues/7891 using CocoaPods (`1.6.0.beta.2`).

## What did you expect to happen?

The framework builds correctly using Xcode 10 and solution found in the old issue https://github.com/CocoaPods/CocoaPods/issues/7891

## What happened instead?

Framework does not work due to error:
```
Multiple commands produce '/Users/ztepsa/Library/Developer/Xcode/DerivedData/Project/Build/Products/Debug-iphonesimulator/Project/Project.framework/Info.plist':
1) Target 'Project' (project 'Pods') has copy command from '/Users/ztepsa/Projects/Project/Pods/Project/Sources/Info.plist' to '/Users/ztepsa/Library/Developer/Xcode/DerivedData/Project-cdsgitmylgzujsckqzdbflsfvapc/Build/Products/Debug-iphonesimulator/Project/Project.framework/Info.plist'
2) Target 'Project' (project 'Pods') has process command with output '/Users/ztepsa/Library/Developer/Xcode/DerivedData/Project-cdsgitmylgzujsckqzdbflsfvapc/Build/Products/Debug-iphonesimulator/Project/Project.framework/Info.plist'
```
as seen in the https://github.com/CocoaPods/CocoaPods/issues/7891 issue podspec setup is as following:
```
s.pod_target_xcconfig = { 'INFOPLIST_FILE' => '${PODS_TARGET_SRCROOT}/Sources/Info.plist' }
s.source_files = 'Sources/*.{swift,h,m,plist}'
```
this worked with Xcode 9, but after upgrading to Xcode10 it's broken and if I remove copying plist files to sources, there is no longer single copy of the file in the project (hence it does not work).

After searching online for this issue there are two solutions but none is CocoaPods related, first is to remove `Info.plist` manually from the `Build Phases` section after running `pod install` ([link](https://stackoverflow.com/a/50719379)), or to switch to legacy build system ([link](https://stackoverflow.com/a/51089264)), both of these solutions are not an option and would require end user to perform changes to their project if they wanna integrate framework using CocoaPods.

Is there a different way to achieve this, so it works with Xcode10?

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a210d6827e01d41134fb4741f4b46df87adadd01
               worldline-spain - https://github.com/worldline-spain/t21_pods-specs_ios.git @ 5f4b1b32764181aa1455982aeec0d95074d8b9f2
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
Check out the old issue -> https://github.com/CocoaPods/CocoaPods/issues/7891

**Comment by ztepsa** [comment]
Yeah I thought that would be the case, but wanted to check anyway 👍 I'll change up how we handle data in the `Info.plist` so we don't have these issues, both with Xcode10 or having requirement to use beta CocoaPods (until new version is out). 

This might be a bug in Xcode and they change it later on, otherwise CocoaPods would need to provide a different way of copying custom `Info.plist` file to a project so it does not break new build system.

Thanks for the fast response! I would close the issue if you don't need it open?

**Comment by davidgish760** [comment]
@ztepsa You said "I'll change up how we handle data in the Info.plist so we don't have these issues..." How did you do that, exactly?

**Comment by ztepsa** [comment]
@davidgish760 I ended up removing all of the custom data from `Info.plist` and migrating them to another `.plist` file which is copied over (so in the end I'm not using `Info.plist` for anything as it's currently not possible with CocoaPods and new build system, sorry that the response sounded like issue was solved in some way 😁)

**Comment by ignatovv** [comment]
I Have the same issue. I want to provide custom info plist for my test target, but 
`s.pod_target_xcconfig = { 'INFOPLIST_FILE' => '${PODS_TARGET_SRCROOT}/Sources/Info.plist' }`
only works for main spec, not for test one. Cocoapods modify `INFOPLIST_FILE` value of buildSettings inside Pods.xcodeproj and override value from xcconfig.
May be there is a way to turn off this modification if `INFOPLIST_FILE` flag is specified in podspec?

**Comment by linkoubian** [comment]
@ztepsa I create a test example with pod lib command, and then specify pod_target_xcconfig as you did. Customized value in info plist can be retrieved with NSBundle.

[BLFoundation.zip](https://github.com/CocoaPods/CocoaPods/files/3403010/BLFoundation.zip)
