### ISSUE TITLE
Vendored_Framework with external dependencies

### ISSUE THREAD

**Issue by sathishvgs** [CocoaPods/CocoaPods#8397]
### What did you expect to happen

I like to create and publish the framework through **Cocoapod** which should hide all my implementation files. 

### My Question

 Is it possible to add the external dependencies [eg: Alamofire] in the *Vendored_Framework* ?

### What happen instead

It hided all implementation files but its crashing with `Reason: image not found`.

### Thing which I tried
I have zipped the .framework file and hosted in server and also linked the file url in `podspec`. 

### Stack

```
CocoaPods : 1.6.0.beta.2
Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
RubyGems : 2.5.2.3
Host : Mac OS X 10.14.2 (18C54)
Xcode : 10.1 (10B61)
Git : git version 2.20.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 
         a210d6827e01d41134fb4741f4b46df87adadd01
         worldline-spain - https://github.com/worldline-spain/t21_pods-specs_ios.git @ 
         5f4b1b32764181aa1455982aeec0d95074d8b9f2
```

### Installation Source

`Executable Path: /usr/local/bin/pod                                                                                                                  
` 

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Hey there, this looks like a good example question to ask in StackOverflow under `cocoapods` tag.

**Comment by sathishvgs** [comment]
@dnkoutso , I have already asked in StackOverflow but didn't get a valid answer.
StackOverflow -> [click here](https://stackoverflow.com/questions/54050022/how-to-use-the-framework-with-external-dependency)
