### ISSUE TITLE
pod install with RainForest in XCode10 failed

### ISSUE THREAD

**Issue by BartonQiu** [CocoaPods/CocoaPods#8398]
Dear segiddins,

As there are many frameworks in our Project, we finally find your pod. It really works for three times, but now it doesn't. The message says,
'
...
RuntimeError - [!] Xcodeproj doesn't know about the following attributes {"inputFileListPaths"=>[], "outputFileListPaths"=>[]} for the 'PBXShellScriptBuildPhase' isa.
If this attribute was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
/Users/ytx/.rvm/gems/ruby-2.3.4/bundler/gems/Xcodeproj-bd3dc02dc868/lib/xcodeproj/project/object.rb:321:in `configure_with_plist'
...'

Please give me sone advice.

Best regards.

**Comment by BartonQiu** [comment]
Did CocoaPod in RainForest locked to 1.5.0 while some friends suggest to update CocoaPod in XCode 10?

**Comment by dnkoutso** [comment]
Please `gem update xcodeproj` which fixes the issue around new file list paths.

Going to close this for now as this is not actionable here so far.
