### ISSUE TITLE
Provide more information about use_frameworks! in the auto-generated Podfile

### ISSUE THREAD

**Issue by michaeleisel** [CocoaPods/CocoaPods#8399]
Currently, the Podfile generated (see `lib/cocoapods/command/init.rb` in this repo) has something along the lines of:
```
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
```

However, it is now possible to use static libraries containing Swift code. The comment should be updated accordingly. Also, a lot of developers are unfamiliar with the tradeoffs of static vs. dynamic libraries. In particular, the startup time can be increased by hundreds of milliseconds from using dynamic libraries (and in a way that is difficult to measure). On the other hand, dynamic libraries are better for incremental build time. So perhaps the comment should link to an article about the tradeoffs, or at least mention that you are either sacrificing startup time or incremental build performance (the two biggest tradeoffs that I can think of) when you choose whether or not to include `use_frameworks!`.

**Comment by dnkoutso** [comment]
Sounds like a good PR to come and fairly easy to do so. Want to make one?

**Comment by michaeleisel** [comment]
Done, see https://github.com/CocoaPods/CocoaPods/pull/8401
