### ISSUE TITLE
Clean up Podfile syntax

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#840]
#### Background

_Note: This text will be updated to reflect the most recent proposal_

Currently CocoaPods:

- Skips target definitions without dependencies as the user might not want the implicit root target definition (which automatically links with the first target) and there is no other way to prevent its integration.
- Marks a target as exclusive if it has a different platform from the parent not inheriting any dependency.
- Doesn't have a way to specify what should be inherited from the parent target definition (nothing, only the headers, the dependencies). This is evident in the tests target which currently need to be marked as exclusive, however this set up only works because CocoaPods makes the headers of all targets visible (exactly for this reason).
- Doesn't allow to specify that a target should not be integrated in the Podfile. It is only possible to specify that whole Podfile should not be integrated (i.e. no workspace) with a command line option.

#### Proposal

- [ ] Add a new `abstract_target!` attribute to the target definition.
  - Skip the installation of the implicit root target definition if it doesn't have any dependency (temporary see below).
  - Otherwise never skip the installation of a target unless marked abstract.
- [ ] Add a new `do_not_integrate!` root attribute which would replace the command line option (`--no-integrate` of pod install and pod update).
- [ ] Inherit the compatible dependencies from the parent target definition if the platforms do not match.
- [ ] Add a new `inherit` attribute to the target definition which would support 3 values (true, false, :headers).
  - Phase out the `exclusive` option of the target definition.
- [ ] Drop any form of integration of the implicit target definition by CP 1.0. Adding a warning immediately.
- [ ] Drop the options parameter used for new target definitions (the has used after the name and before the block) in favor of statements inside the block.
  - This would accelerate the phasing out of the [exclusive](http://docs.cocoapods.org/podfile.html#target) option.
- [ ] Deprecate the `link_with` attribute. Every integrated target should be identified by the name of the target definition common dependencies can be declared in dedicated targets. This would not only simplify the DSL but also the implementation of the CP analyzer and user project integrator.

#### Points which require Feedback

- The name of the `abstract_target!` and of the `do_not_integrate!`
- Wether inheritance by nesting targets definitions should be dropped for an attribute (`inherits_from`, se example below).

###### Headers only inheritance

Note that By CocoaPods 1.0 the `abstract_target!` call can be dropped from the root as it will become the default behaviour.

```ruby
abstract_target!
pod 'CocoaAsyncSocket', '0.0.1'
pod 'CocoaLumberjack', '>=1.6'

target 'App_1'
  # deps
end

target 'App_2'
  # deps
end
```

---

###### Abstract targets

```ruby
target 'MacApp'
  pod 'AFNetworking'
 
  target 'MacAppTests' do
     use_headers_of_parent
     # dependencies
  end
end
```

--

###### Alternative headers only inheritance

In this scenario nesting would be disabled.

```ruby
target 'MacApp'
  pod 'AFNetworking'
end

target 'MacAppTests' do
  use_headers_of 'MacApp' 
  # use_headers_of 'MacApp_1', 'MacApp_2'
  # dependencies
end
```

---

###### Multi platform inheritance

```ruby
abstract_target!
pod 'CocoaAsyncSocket', '0.0.1'
pod 'CocoaLumberjack', '>=1.6'

target 'iOSApp'
  platform :ios
  # deps
end

target 'MacApp'
  platform :osx 
  # deps
end
```

**Comment by orta** [comment]
bwahah, you can't escape.

**Comment by jcampbell05** [comment]
Hoe much of this is achieved ?

**Comment by kylef** [comment]
@jcampbell05 There is a WIP pull request at https://github.com/CocoaPods/CocoaPods/pull/4644
