### ISSUE TITLE
pod search is ok but pod install failed  Unable to find a specification

### ISSUE THREAD

**Issue by gcgxfqw** [CocoaPods/CocoaPods#8402]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I want to dependence a lib in my private repo 

## What happened instead?

pod search XYAgoraSdk

-> XYAgoraSdk (0.1.1)
   A short description of XYAgoraSDK.
   pod 'XYAgoraSdk', '~> 0.1.1'
   - Homepage: https://github.com/gc/XYAgoraSDK
   - Source:   git@code.aliyun.com:jyxb/XYAgoraSDK.git
   - Versions: 0.1.1, 0.1.0 [jyxbrepo repo]

but pod install 

Analyzing dependencies
Fetching podspec for `XYRealTimeSession-swift` from `../`
[!] Unable to find a specification for `XYAgoraSDK (~> 0.1.1)` depended upon by `XYRealTimeSession-swift`

this is podspec file
  s.dependency 'XYNIMSDK'
  s.dependency 'RxSwift'
  s.dependency 'ObjectMapper'
  s.dependency 'XYAgoraSDK', '~> 0.1.1'

when i remove "s.dependency 'XYAgoraSDK', '~> 0.1.1'" it's ok, and XYNIMSDK is also a private lib in my repo

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.15.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : jyxbrepo - git@code.aliyun.com:xyjy-ios/XYSpecs.git @ ae3bbea3ad60f8232a8352ec4314e71f5978d0bb
               master - https://github.com/CocoaPods/Specs.git @ 567ab2c8162bab07290193bcdf9a389c2e7624d9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'git@code.aliyun.com:xyjy-ios/XYSpecs.git'

platform :ios, '8.0'

target 'XYRealTimeSession-swift_Example' do
  pod 'XYRealTimeSession-swift', :path => '../'

  target 'XYRealTimeSession-swift_Tests' do
    inherit! :search_paths

    
  end
end
```
## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Did you try `--repo-update`?
