### ISSUE TITLE
Is there a way to handle built resources in Swift Static Libraries mode?

### ISSUE THREAD

**Issue by s1ddok** [CocoaPods/CocoaPods#8403]
I'm trying to migrate from dynamic frameworks to swift static libraries. I have a whole ecosystem of private pods and some of them contain coreml models/metal files inside them, which are compiled to `.mlmodelc` and `.metallib` and get copied to a framework's bundle, so later I can access them via `Bundle(for:<AnyClass>)`

Is there anything similar with Swift Static lib? Do they even support resources in any way? Maybe it is possible to point resources in build folder?

**Comment by dnkoutso** [comment]
it will have to be a separate resource bundle that will get copied to the app instead.

This does not appear to be a CocoaPods issue with the library itself and I think it is currently supported. I am going to preemptively close and re-open if we find a feature enhancement we can build.

Also recommend asking the same on StackOverflow under `cocoapods` tag.

Thank you!

**Comment by s1ddok** [comment]
@dnkoutso yup, but the problem is that they are not regular resources, they need to be compiled first and then copied. Like `.metal` files are compiled into `.metallib` and `.mlmodel` files are compiled into `.mlmodelc`. I see those files in Products dir next to lib<Name>.a, but they are not copied into app's bundle. 

Is there a way to tell CocoaPods to grab resources from build directory? 

Btw, thanks for quick response and sorry if GitHub issues is the wrong place.

**Comment by s1ddok** [comment]
Okay, so I compose the project. You can see they way we use it with frameworks, but once you switch to libs everything breaks up.

If you jump to built products dir you will see that metal files are actually compiled to `.metallib`, but it never gets copied. 

![](https://i.ibb.co/smJGvkC/image.png)

Another question: how to detect that the pod is being built as library or as framework? 

Because we will also have to replace Bundle(for:) somehow like that:

```swift
#if POD_IS_FRAMEWORK:

// load resources from Bundle(for: Foo.self)

#else

// load resouces from something like Bundle.main/"Foo"
#endif
```

This is the link to the project: https://drive.google.com/file/d/1DJWIf2nSNbXjQKoBwE_05CAMO5IweYWT/view?usp=sharing

**Comment by dnkoutso** [comment]
Thanks for the project. I will have to take a look once I find time

**Comment by dnkoutso** [comment]
@s1ddok is this happening only with metal sources or other ones as well?

**Comment by s1ddok** [comment]
Basically all resources that have to compiled, e.g. CoreML model

**Comment by dnkoutso** [comment]
@s1ddok hm I will double check with CoreData too
