### ISSUE TITLE
Pod-Frameworks are missing in Xcode

### ISSUE THREAD

**Issue by regetskcob** [CocoaPods/CocoaPods#8408]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

 Run `pod install`

## What did you expect to happen?

Download/create the frameworks of the related pods.

## What happened instead?

The sources are there, but Xcode is missing the frameworks. 

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 826cc2fcfbfc5511f8c06714474d6ec88102a88b
               master - https://github.com/CocoaPods/Specs.git @ d182af3aa22eab5b13e263dbd20525c54201925e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Sources
source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'T1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for T1

  # public open source pod
  pod 'AFNetworking', '~> 3.0'
  pod 'Alamofire'
  pod 'AWSS3'
  
  # artsy pod
  pod 'Artsy-UIButtons'
  pod 'Aerodramus'

  # Download pod
  pod 'GoogleAds-IMA-iOS-SDK-For-AdMob'

end
```

## Screenshot that illustrates the issue

<img width="2560" alt="bildschirmfoto 2019-01-10 um 17 13 07" src="https://user-images.githubusercontent.com/1019812/50982158-d20ea500-14fc-11e9-9796-a69691467c5c.png">

**Comment by dnkoutso** [comment]
1.5.3 does not create a target for pre-built vendored pods. 

Does compilation fail for you? Whats the actual issue here? Also try 1.6.0.beta.2 which would create an aggregate placeholder target for each of those.

**Comment by dnkoutso** [comment]
Can you please upload a sample? It helps a lot to diagnose these.
