### ISSUE TITLE
`pod spec lint` incorrectly tries to resolve dependency for wrong platforms

### ISSUE THREAD

**Issue by armcknight** [CocoaPods/CocoaPods#8409]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. add an ios-specific dependency to a subspec (`subspec.ios.dependency = 'SomePod'`)
1. pod spec lint --allow-warnings

## What did you expect to happen?

expected no errors for any platforms

## What happened instead?

Fails validating for macOS, due to trying to resolve a dependency on another podspec that is only available for iOS ("SomePod"). 

```
    - ERROR | [OSX] unknown: Encountered an unknown error (CocoaPods could not find compatible versions for pod "SomePod":
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.18.0
Ruby lib dir : /Users/andrew/.rbenv/versions/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 49abc736016a6791609da4df67370bfb20542c58
```

### Installation Source

```
Executable Path: /Users/andrew/.rbenv/versions/2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!
install! 'cocoapods', :share_schemes_for_development_pods => true
project 'Pippin.xcodeproj'
workspace 'Pippin.xcworkspace'
platform :ios, '11.0'

abstract_target 'PippinPods' do
  pod 'Pippin', path: '.', :testspecs => ['Tests']
  pod 'PippinAdapters', path: '.'

  target 'PippinTestHarness' do
    pod 'Crashlytics', '~> 3'
  end
end

abstract_target 'PippinTestPods' do
  platform :ios, '11.0'
  pod 'PippinTesting', path: '.', :testspecs => ['Tests']
  pod 'Pippin/Extensions', path: '.'

  target 'PippinUITests'
  target 'PippinUnitTests'
end

post_install do |installer|
   # set SWIFT_VERSION for pods that don't declare it in their podspec
   installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         if target.name == 'PinpointKit' or target.name == 'Anchorage' then
            config.build_settings['SWIFT_VERSION'] = '4.2'
         end
      end
   end
end
```

**Comment by dnkoutso** [comment]
Can you please upload a sample repo? It's difficult to debug these with the given information.

**Comment by armcknight** [comment]
Sure thing @dnkoutso, here's what I have so far: https://github.com/armcknight/cocoapods-platform-dependency-test. 

`pod install` works but I get the OSX error when linting. I use --allow-warnings while linting as my target project does too. Although now it's a different failure mode: fixing the dependency_target for osx solved the dependency resolution issue, but now there's a build error for the macOS test app the linter sets up. (Happy to update this issue's title/description, or to create a new one if you want.)

So far I'm zeroing in on the xcodebuild invocation used to build the macOS test App while linting. Here's what cocoapods is calling:

```
/usr/bin/xcodebuild clean build -workspace /path/to/.../App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY=
```

which causes this error:
```
/var/folders/t5/t07f7xt10x1g9p8c85ln84pm0000gn/T/CocoaPods-Lint-20190110-91239-17p7spt-mainPod/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable
```

It's able to build successfully if the trailing `CODE_SIGN_IDENTITY=` is removed:
```
/usr/bin/xcodebuild clean build -workspace /path/to/.../App.xcworkspace -scheme App -configuration Release
```

Is it required for some reason to be there?

**Comment by armcknight** [comment]
Haha I found https://github.com/CocoaPods/CocoaPods/issues/7708 as you sent that reply. Updating to 1.6.0.beta.2 fixed it. Thanks! 👍
