### ISSUE TITLE
CocoaPods fetches nonexistent version of pod

### ISSUE THREAD

**Issue by chauduyphanvu1** [CocoaPods/CocoaPods#8411]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Create a podfile to contain `pod 'MoPub-Chartboost-Adapters'`
2. Run `pod update`

## What did you expect to happen?
The version fetched for that pod should contain 4 digits at max (e.g. 1.2.3.4). At this time, the correct version should be `7.3.0.0`.

## What happened instead?
The version fetched for that pod is currently `7.3.0.0.1.1.1`, which is not an expected versioning scheme our team uses. Our podspec has never historically contained that version string: https://github.com/mopub/mopub-ios-mediation/commits/master/Chartboost/MoPub-Chartboost-PodSpecs/MoPub-Chartboost-Adapters.podspec. It's unclear how `7.3.0.0.1.1.1` made its way to CocoaPods.

I found the `7.3.0.0.1.1.1` string mentioned on this unaffiliated page: https://tryexcept.com/articles/cocoapod/mopub-chartboost-adapters. It's unclear if that has any connection to this issue.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin16.7.0]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.6 (17G4015)
       Xcode : 10.1 (10B61)
         Git : git version 2.12.0
Ruby lib dir : /Users/vchau/.rvm/rubies/ruby-2.0.0-p247/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b7654a1fe76cd9a01f0397771a7f0e2df0ef0f1f
```

### Installation Source

```
Executable Path: /Users/vchau/.rvm/rubies/ruby-2.0.0-p247/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://s3.us-east-2.amazonaws.com/chauduyphanvu/sample_apps/cocoapods-test-project.zip

**Comment by orta** [comment]
Hi, that is correctly the latest version (and highest by semantic release) so I don't think this would be considered a bug on our end. Someone must have deployed that version. Here's everyone with access:

```
~/d/p/o/j/r/website  $ pod trunk info MoPub-Chartboost-Adapters

MoPub-Chartboost-Adapters
    - Versions:
      - 7.0.4.0 (2018-02-05 21:43:17 UTC)
      - 7.0.4.1 (2018-02-16 16:14:47 UTC)
      - 7.0.4.2 (2018-03-09 23:16:29 UTC)
      - 7.0.4.3 (2018-03-22 16:55:07 UTC)
      - 7.1.2.0 (2018-03-29 21:41:08 UTC)
      - 7.1.2.1 (2018-04-18 20:29:45 UTC)
      - 7.2.0.0 (2018-05-15 23:27:45 UTC)
      - 7.2.0.2 (2018-06-08 06:14:30 UTC)
      - 7.2.0.3 (2018-06-11 23:43:23 UTC)
      - 7.3.0.0 (2018-12-03 16:43:23 UTC)
      - 7.3.0.0.1.1.1 (2018-12-21 19:53:40 UTC)
    - Owners:
      - ‘AdColonyAdapters --description=‘AdColony adapters for MoPub mediation <pshashidhar@twit...>
      - Rupa Twitter Cocoapods <rsatrasala@twit...>
      - MoPub Mediation Cocoapods <vchau@twit...>
      - MoPub Mediation Cocoapods <dnataraj@twit...>
```

**Comment by chauduyphanvu1** [comment]
Ok, thank you! We'll check internally on this then.
