### ISSUE TITLE
IBDesignable rpath error

### ISSUE THREAD

**Issue by drmarkpowell** [CocoaPods/CocoaPods#8412]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I made a resuable UIView pod project with tests and IBDesignable.

git clone https://github.com/drmarkpowell/ReachabilityView
pod install

## What did you expect to happen?

Install the pod into the example project and tests targets and be able to render the IBDesignable on the storyboard

## What happened instead?

The pod was installed fine in the example project and test targets (app runs, tests execute), but the IBDesignable does not render on the storyboard.

Instead of rendering the IBDesignable on the storyboard, I got a runtime error from IB:

```
/Users/mpowell/Workspaces/ReachabilityView/Example/ReachabilityView/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ViewController (vXZ-lx-hvc): dlopen(ReachabilityView.framework, 1): Library not loaded: @rpath/Reachability.framework/Reachability
  Referenced from: ReachabilityView.framework
  Reason: image not found
```

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode :  ()
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 91e9aed7a5238063dd7c737ff2b6b94e9a06f49a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0

## Project that demonstrates the issue

https://github.com/drmarkpowell/ReachabilityView

**Comment by drmarkpowell** [comment]
WORKAROUND:
I have found a workaround that I applied and checked into a branch named 'runpath_search_fix' where I applied two changes:
1) Selecting the ReachabilityView target in the Pods project, in Build Settings->Runpath Search Paths, I added in $(FRAMEWORK_SEARCH_PATHS) as the last path.
2) Selecting the ReachabilityView_Example target in the ReachabilityView project, in Build Settings->Runpath Search Paths, I added in $(FRAMEWORK_SEARCH_PATHS) as the last path.

After this, the IBDesignable will render on the storyboard instead of giving an error.

**Comment by dnkoutso** [comment]
I dont get it. Everything renders properly for me on `Main.storyboard` or any other `.xib`.

Can you please provide more clear steps on how to get the issue?

**Comment by drmarkpowell** [comment]
I'm sorry, but I don't know how to make it any more clear? I executed the same steps on a different Mac just to verify and it does the same thing:
1) git clone
2) pod install
3) open the example xcworkspace in XCode 
4) select the Main.storyboard in the example project
after the build, the IB renderer fails with an error, the Reachability View is just white.

I'm using XCode 10.1 10B61 and Cocoapods 1.6.0.beta.2

I'm happy to provide *any* more information. Can you think of anything that might help?

**Comment by jshier** [comment]
I'm seeing this same issue with 1.6.0. I have my designable views in their own framework and the single CP dependency that target uses breaks all of the designables with the same error originally reported. @drmarkpowell's workaround works as described: designables started rendering again when I added the setting he mentioned to both my designable framework and the CP dependency it uses.
