### ISSUE TITLE
Pod spec lint fail while finding `-Swift.h` with Swift 4 and XCode 10

### ISSUE THREAD

**Issue by ankitthakur** [CocoaPods/CocoaPods#8417]
# Report
Created Swift based `Cocoa Touch Framework` and added dependency pods. Then created PodSpec file, created git tag, and run `pod spec lint` and it fails, saying `Framework-swift.h` file not found.

Pod version 1.5.3

## What did you do?
Here is open source code:
https://github.com/ankitthakur/CoreDataPreference

1. Created `CoreDataDefaults` framework in xcode.
2. Install dependent pods using `pod init` && `pod install`
3. Write XCTest cases for the same.
4. Build and Test project in IDE and got success.
5. Integrated Travis-CI to confirm build process and got success.
6. Created podspec file of the project.
7. Created tag 0.0.3 version in github.
8. run `pod spec lint`

## What did you expect to happen?
`pod lib lint` should be successful.

## What happened instead?

It is presuming Swift module as Objective-C module
```
    - ERROR | xcodebuild:  /Users/ankitthakur/Library/Developer/Xcode/DerivedData/App-ashbqphybkdwclgbgwtgzyapoqwx/Build/Products/Release-iphonesimulator/CoreDataDefaults/CoreDataDefaults.framework/Modules/module.modulemap:9:12: error: header 'CoreDataDefaults-Swift.h' not found
    - ERROR | xcodebuild:  /var/folders/k0/dd091g8x0yv330vn1bhlzfch0000gn/T/CocoaPods-Lint-20190113-21769-vs66ru-CoreDataDefaults/App/main.swift:1:8: error: could not build Objective-C module 'CoreDataDefaults'
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 63d377a2221b893df6c57bceda3549e01d299111
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
 platform :ios, '8.4'

target 'CoreDataDefaults' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreDataDefaults
  pod 'EncryptedCoreData', :git => 'https://github.com/project-imas/encrypted-core-data', :commit => 'b97ffaf2f19dad4d1558bc9b0668cc2e09d17347'
  pod 'SwiftyBeaver'

  target 'CoreDataDefaultsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue
https://github.com/ankitthakur/CoreDataPreference

**Comment by dnkoutso** [comment]
Out of curiosity have you tried 1.6.0.beta.2?

**Comment by ankitthakur** [comment]
Sorry, not the beta versions. One thing I would like to clarify I did not created pod with `pod create -type lib' because, I had to install few more dependencies for my pod. An hour back, I had made 1.0 version release. https://github.com/ankitthakur/CoreDataPreference
