### ISSUE TITLE
Header search path gets hijacked by test specs' dependencies

### ISSUE THREAD

**Issue by theodelrieu** [CocoaPods/CocoaPods#8420]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm trying to create a test spec for a subspec in my project, the latter uses `PromiseKit/Promise` legacy version (~> 1.0) and the test spec uses `PromiseKit/Hang` and `PromiseKit/When`.

In my `Project/Example/Podfile`, I tried to use the testpec in the `Project_Tests` target.

I ran `pod install`

I tried to build the main target (not the test one)

## What did you expect to happen?

I expected the main target to build without an issue.

## What happened instead?

The compiler says that there is a non-modular header include in `PromiseKit.h`. On the following lines:

```objective-c
#if __has_include(<PromiseKit/Promise+When.h>)
#import <PromiseKit/Promise+When.h>
#endif

/* several lines later */

#if __has_include(<PromiseKit/Promise+Hang.h>)
#import <PromiseKit/Promise+Hang.h>
#endif
```

Removing by hand `Pods/PromiseKit/Sources/PromiseKit/Promise+When.h` and `Promise+Hang.h` solves the issue (for the main target).

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.16.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ f70fb4fd11ae3f0348ba76709e86c5b28716a441

```

### Installation Source

```
Executable Path: /Users/theo/.gem/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

platform :ios, '8.0'

target 'bug_Example' do
  pod 'bug', :path => '../'

  target 'bug_Tests' do
    inherit! :search_paths

    pod 'bug', :path => '../', :testspecs => ['PromiseKitLegacy_Tests']
  end
end
```

## Project that demonstrates the issue

[bug.zip](https://github.com/CocoaPods/CocoaPods/files/2755603/bug.zip)

**Comment by theodelrieu** [comment]
Hi, I've completely forgotten about this issue, and don't remember anything about it. If the example code passes, then I guess it got fixed.

I've had several include-related issues in different Xcode versions. So that might not be a Cocoapods issue in the first place.

**Comment by dnkoutso** [comment]
Thank you!
