### ISSUE TITLE
undefined method `map' for nil:NilClass (NoMethodError) Did you mean?  tap

### ISSUE THREAD

**Issue by chshapiro** [CocoaPods/CocoaPods#8425]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` or `pod update`

## What did you expect to happen?

pod dependencies get uploaded

## What happened instead?

got following error message:
```
/Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:95:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
Did you mean?  tap
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:34:in `search'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:67:in `report_error'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
	from /Users/xxx/.gem/ruby/2.3.0/bin/pod:22:in `load'
	from /Users/xxx/.gem/ruby/2.3.0/bin/pod:22:in `<main>'
```

## CocoaPods Environment

```
### Stack

   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 03d0a95c316ba6036f120f66c12a1eed23786dd6

### Installation Source

Executable Path: /usr/local/bin/pod

### Plugins

cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
This is an issue within an issue. The tool is trying to find similar issue and it fails.

I am moving this to the corresponding GH repo.

**Comment by dnkoutso** [comment]
Actually I can't can you please file the issue here https://github.com/orta/gh_inspector/issues

**Comment by amorde** [comment]
Actually this looks just like https://github.com/orta/gh_inspector/issues/12

**Comment by dnkoutso** [comment]
Yes!

**Comment by chshapiro** [comment]
@dnkoutso it looks like Cocoapods is passing in a string that's too long which is making it fail. 
1. Is there anything that can be done to prevent that?
2. Why is this causing `pod install` and `pod update` to fail?

**Comment by dnkoutso** [comment]
@chshapiro My gut feeling is that you are getting a different crash and while `gh_inspector` tries to find similar errors for you it fails and crashes _again_.

Can you modify your own `gh_inspector` gem to skip this check and then post here to see what the real underlying crash is?

**Comment by dnkoutso** [comment]
@chshapiro I will re-open this issue once this is done!

**Comment by amorde** [comment]
@chshapiro for context, what you are seeing is a crash on the code that _handles crashes_ - when CocoaPods crashes, the exception is caught and gh_inspector searches for issues on Github that look similar to the error, in order to help the user find other issues that may be relevant. 

This doesn't mean that it's causing `pod install` or `pod update` to fail, because by that point it had already failed.

**Comment by zkrige** [comment]
is there no resolution here? I'm having same issue

**Comment by zkrige** [comment]
ah `gem update xcodeproj` fixes the problem for me

**Comment by amorde** [comment]
If updating Xcodeproj fixed the issue, it was most likely this https://github.com/CocoaPods/CocoaPods/issues/7835

**Comment by zkrige** [comment]
Yes most likely. I had a different pods installation where i had to manually edit the xcodeproj to remove the sections causing the problem.

**Comment by jakubziembinski** [comment]
The same issue occurred to me when `};` was missing in `.xcodeproj` file. After fixing this the Cocopoads started working again.

**Comment by maheshkumar2150** [comment]
> ah `gem update xcodeproj` fixes the problem for me

Not for me. Any other solution

**Comment by maheshkumar2150** [comment]
> The same issue occurred to me when `};` was missing in `.xcodeproj` file. After fixing this the Cocopoads started working again.

Can you tell me exactly which file please??

**Comment by TeamRainless** [comment]
> > ah `gem update xcodeproj` fixes the problem for me
> 
> Not for me. Any other solution

I think there's a simple solution:

For me the problem was that I hadn't defined two important files: .ruby-gemset and .ruby-version.

You can find your ruby version just by typing "ruby --version" So... for example... mine is 2.6.2. So you just make a file called .ruby-version and put that in there. Similarly it's easy to find out which gemset you should be using. Just go into your home directory... find out where your gems are stored... and locate the one for "homebrew".  Then type that into .ruby-gemset.

DONE!

**Comment by codeclinic** [comment]
> So you just make a file called .ruby-version and put that in there.
Where does this file go?

**Comment by TeamRainless** [comment]
In the same directory as your Podfile.
