### ISSUE TITLE
Error when depending on header only pod. 

### ISSUE THREAD

**Issue by dave234** [CocoaPods/CocoaPods#8426]
* 🌈 I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Created a header only library called [Cwift](https://github.com/dave234/Cwift) (current version has empty file workaround). Then, created another library [LibDependsOnCwift](https://github.com/dave234/LibDependsOnCwift) that depends on [Cwift v0.4](https://github.com/dave234/Cwift/releases/tag/0.4) (this version doesn't include empty file workaround) along with an example project. Within LibDependsOnCwift, in [MyClass.h](https://github.com/dave234/LibDependsOnCwift/blob/master/LibDependsOnCwift/Classes/MyClass.h), imported Cwift. 

Called `pod install` from within LibDependsOnCwift/Example and built project.

## What did you expect to happen?

Expected Cwift to be successfully imported Into my public class header that will be defining types that depend on Cwift.

## What happened instead?

Instead, got the error `Include of non-modular header inside framework module 'LibDependsOnCwift.MyClass': '/Users/dave/projects/LibDependsOnCwift/Example/Pods/Headers/Public/Cwift/Cwift.h'`

![untitled](https://user-images.githubusercontent.com/4334667/51366987-706ead80-1a9d-11e9-8399-266d908cb543.jpeg)

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.13.6 (17G4015)
       Xcode : 10.1 (10B61)
         Git : git version 2.14.2
Ruby lib dir : /usr/local/Cellar/ruby/2.5.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e99fc18e8c6702eb27db37824f7986cffbd12cc5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

platform :ios, '8.0'

target 'LibDependsOnCwift_Example' do
  pod 'LibDependsOnCwift', :path => '../'

  target 'LibDependsOnCwift_Tests' do
    inherit! :search_paths

    
  end
end
````

## Project that demonstrates the issue

https://github.com/dave234/LibDependsOnCwift
Open LibDependsOnCwift/Example/LibDependsOnCwift.xcworkspace

## Details

Here is the [podspec](https://github.com/dave234/Cwift/blob/master/Cwift.podspec) for [Cwift](https://cocoapods.org/pods/Cwift), it only includes a single header in the root directory.
``` ruby
Pod::Spec.new do |s|
  s.name               = "Cwift"
  s.version            = '0.4'
  s.summary            = 'Conditional clang attributes used for C-Swift interoperability.'
  s.homepage           = 'https://github.com/dave234/Cwift'
  s.authors            = { "Dave O'Neill" => 'daveoneill234@gmail.com' }
  s.license            = { :type => 'MIT', :text => license }
  s.source             = { :git => 'https://github.com/dave234/Cwift.git', :tag => '0.4' }
  s.source_files       = 'Cwift.h'
  s.public_header_files = 'Cwift.h'
  s.requires_arc       = false
  s.ios.deployment_target = '7.0'
  s.osx.deployment_target = '10.8'
  s.tvos.deployment_target = '9.0'
end
```  

Here is the podspec for LibDependsOnSwift
``` ruby
Pod::Spec.new do |s|
  s.name             = 'LibDependsOnCwift'
  s.version          = '0.1.0'
  s.summary          = 'A short description of LibDependsOnCwift.'
  s.description      = 'hodor'
  s.homepage         = 'https://github.com/dave234/LibDependsOnCwift'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'Dave O\'Neill' => 'daveoneill234@gmail.com' }
  s.source           = { :git => 'https://github.com/dave234/LibDependsOnCwift.git', :tag => s.version.to_s }
  s.ios.deployment_target = '8.0'
  s.source_files = 'LibDependsOnCwift/Classes/**/*'
  s.dependency 'Cwift' ', '= 0.4'
end
```

**Comment by dnkoutso** [comment]
Most likely an issue that the pod has no sources yes. This might be more complicated @dave234 but wouldn't mind if you dig in. Start in `pod_target_installer.rb`.
