### ISSUE TITLE
[Flutter] use_frameworks! Cannot Find Header

### ISSUE THREAD

**Issue by Nightsd01** [CocoaPods/CocoaPods#8427]
* [ Y ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I am building a Flutter SDK that uses Cocoapods. This flutter framework depends on our native iOS pod as a Cocoapod dependency.

In essence, adding `use_frameworks!` to the Podfile for a given target breaks the ability of our SDK to find the header file for our framework.

## What did you expect to happen?
I expected that after running `pod install` that CocoaPods would correctly link our local pod with our framework from CocoaPods that it depends on.

## What happened instead?
The generated Xcode project is unable to find the header files for our Cocoapod, OneSignal. I have spent _months_ trying different Framework/Header search paths and so on, but I've never found any solutions and I am completely out of ideas.

## CocoaPods Environment
***PLEASE NOTE***: I currently have the cocoapods beta, but I have tried _every_ recent release of CocoaPods and this issue occurs on _all_ of them, exactly the same.

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d69ddac8cd95d279304181cabb1e359ed2e7eea7
               OneSignalPro - https://github.com/Hiptic/OneSignal-iOS-SDK-PRO.git @ 289b89f65a28e633f142eae229dd13593708deba
               twilio - https://github.com/twilio/cocoapod-specs @ 15612163b2cae5be50339701ce3702af12a090f8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

## Project that demonstrates the issue
Here is a link that demonstrates the issue. Please run the `Runner` target and you will see that it cannot find the header file for `OneSignal.h` when the pod is installed in a target with `use_frameworks!`.

Please note that our normal pod, installed by itself, works just fine. The problem occurs when our `OneSignal` pod is used as a _dependency_ of another pod.

https://www.dropbox.com/s/okln8wn9lyoo8ri/testflutter.zip?dl=0

**Comment by Nightsd01** [comment]
Users of our Flutter SDK have been facing issues with this for several months, so up to this point we've been advising them not to use `use_frameworks!` with our SDK. We would really like to figure out what's going on here, I suspect there's something we can change in our podspec to allow the linker to find the header file but I've not been able to figure this out.

**Comment by dnkoutso** [comment]
The sample app uploaded is fully configured to use your own paths. I am unable to test anything.

Please fix the sample to work properly for consumption or reduce it into a simple case.

**Comment by Nightsd01** [comment]
@dnkoutso Is this something that `pod install` would fix? If so, that would be fine, the issue isn't dependent on this particular install

**Comment by Nightsd01** [comment]
@dnkoutso sorry to be a bother, but would a simple ‘pod install‘ fix the path issue? When I look into the project all I’m seeing are relative paths that should work on any machine, I’m not sure where you are seeing non-relative paths

**Comment by amorde** [comment]
@Nightsd01 here's what I get if I run `pod install` on the project while inside the `ios` directory:

```
$ pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
[!] No podspec found for `Flutter` in `.symlinks/flutter/ios`
```

haven't dug into it at all but I'm guessing this is what @dnkoutso was experiencing.

**Comment by dnkoutso** [comment]
@Nightsd01 
```xml
// This is a generated file; do not edit or check into version control.
FLUTTER_ROOT=/Users/bradhesse/flutter
FLUTTER_APPLICATION_PATH=/Users/bradhesse/onesignal/testflutter
FLUTTER_TARGET=lib/main.dart
FLUTTER_BUILD_DIR=build
SYMROOT=${SOURCE_ROOT}/../build/ios
FLUTTER_FRAMEWORK_DIR=/Users/bradhesse/flutter/bin/cache/artifacts/engine/ios
FLUTTER_BUILD_NAME=1.0.0
FLUTTER_BUILD_NUMBER=1
```

`Generated.xcconfig` file has absolute paths.

**Comment by rgomezp** [comment]
@Nightsd01 Hey Brad any input you can add here?

**Comment by rgomezp** [comment]
@Nightsd01 any recent insights here?

**Comment by dnkoutso** [comment]
This appears to be an issue with Flutter+CocoaPods integration. Anyone who can assist feel free to do so.

If this lingers longer it will be closed.
