### ISSUE TITLE
Cannot add new pods to project : Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by alexiscreuzot** [CocoaPods/CocoaPods#844]
Hey everyone, I've been pulling my hair for more than a week on this issue now and I can't seem to find anything at all.
I don"t know why or how, but at one point my project stopped accepting more Pods, let me explain. Here is my Podfile : 

`platform :ios, '4.3'
pod 'SVGeocoder', :git => 'https://github.com/kirualex/SVGeocoder.git'
pod 'KALayoutHelper', :git => 'https://github.com/kirualex/KALayoutHelper.git'
pod 'SBJson', '3.1.1'
pod 'AFNetworking', '0.10.1'
pod 'SDWebImage', '2.4'
pod 'SVProgressHUD'
pod 'iActiveRecord'``

Everything is working great with it, but here's the trick, as soon as I want to add a new pod (such as Flurry or Crittercism), I get the same kind of error :

`Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Crittercism", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)``

I'm getting very frustrated with this as I'm near the end of this project and I am currently forced to import these libraries by the "dirty old way" ! Any help would be very very much appreciated !

Thanks guys !

**Comment by trisb** [comment]
Removing -objc fixed it for me.

**Comment by andrewreeman** [comment]
Deleting the DerivedData folder worked for me. I didn't initially know where this was so for future reference it is in:
~/Library/Developer/Xcode

**Comment by skv-headless** [comment]
I think I tried everything from this thread but I still have this issue.

#### podspec

https://github.com/bugsnag/bugsnag-react-native/blob/master/BugsnagReactNative.podspec 

#### example project
https://github.com/skv-headless/AwesomeProject/tree/bugsnag

I appreciate if someone can take a look
