### ISSUE TITLE
Search for existing GitHub issues similar to yours: https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+%2FUsers%2Fyaowenjing%2FDocuments%2Fmac%E6%96%87%E7%A8%BF%E9%87%8C%E7%9A%84%2Fios%E5%8E%9F%E7%94%9F%E4%B8%8Ern%E7%9A%84%E9%9B%86%E6%88%90%2Fnode_modules%2Freact-native%2Fthird-party-podspecs%2FDoubleConversion.podspec&type=Issues

### ISSUE THREAD

**Issue by 15210873185** [CocoaPods/CocoaPods#8443]
[

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Sorry this is not a valid issue template.

**Comment by iranaahsanali** [comment]
I am facing same issue.
