### ISSUE TITLE
add `USER_HEADER_SEARCH_PATHS` into `PLURAL_SETTINGS` in `build_setting.rb`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8451]
I have some pods which with `USER_HEADER_SEARCH_PATHS` in the podspec. Use CocoaPods v1.5.3, I get any warning. 
But in the v1.6.0.beta, I get some warnings:
```
[!] Can't merge pod_target_xcconfig for pod targets: ["GIF", "WebP"]. Singular build setting USER_HEADER_SEARCH_PATHS has different values.
```
I check the source code of CocoaPods, I found the `USER_HEADER_SEARCH_PATHS` is missing for the `PLURAL_SETTINGS`. I think we should add it, right?

**Comment by dnkoutso** [comment]
probably but it would have to be for 1.7.0.

**Comment by dnkoutso** [comment]
I just think it is a minor regression in 1.6.0 new build settings. Let's fix for 1.7.0 by adding it to PLURAL settings.

**Comment by Whirlwind** [comment]
I don't check the branch 1.5.3, but I am sure that there is not any warning.

**Comment by dnkoutso** [comment]
Yes that is because the implementation changed. The warning you see now is a side-effect from the re-write of build settings.

**Comment by segiddins** [comment]
https://github.com/CocoaPods/CocoaPods/pull/8452 should fix
