### ISSUE TITLE
Pods are linked (i.e. `-l`) to vendored frameworks instead of vendored libraries

### ISSUE THREAD

**Issue by Westacular** [CocoaPods/CocoaPods#8453]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run "pod install" with 1.6.0.rc.1, on an app that incorporates a private Pod that contains both vendored static libraries and vendored static frameworks.

For the purposes of this report, let's say the pod is named `MyPod` and contains `libLibraryFoo.a` as a vendored library and `FrameworkBar.framework` as a vendored framework.

## What did you expect to happen?

I expected the `MyPod.xcconfig` that was generated to contain
```
OTHER_LDFLAGS = $(inherited) -l"LibraryFoo" -framework "FrameworkBar"
```

## What happened instead?

The MyPod.xcconfig that was generated contains
```
OTHER_LDFLAGS = $(inherited) -l"FrameworkBar" -framework "FrameworkBar"
```

i.e., it's erroneously linking `FrameworkBar` both as a library and a framework, _and_ there's no mention of `LibraryFoo` in any of the `LDFLAGS` for `MyPod` _or_ the application.

The culprit appears to be [build_settings.rb:610](https://github.com/CocoaPods/CocoaPods/blob/1.6.0.rc.1/lib/cocoapods/target/build_settings.rb#L610), inside `define_build_settings_method :libraries`, it's doing
```ruby
libraries.concat vendored_static_frameworks.map { |l| File.basename(l, '.framework') }
```
where I believe the intended code is
```ruby
libraries.concat vendored_static_libraries.map { |l| File.basename(l, l.extname).sub(/\Alib/, '') }
```
and the error is a result of some copy and pasting from the frameworks code that never got cleaned up.

Making that change locally appears to result in the correct behaviour. I'll make a PR on the assumption that this is the correct fix.

### Stack

```
   CocoaPods : 1.6.0.rc.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.1
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9a4e48f9d57ad45499110a3aeb0a350fb9544685
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.2
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-packager     : 1.5.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.3.1
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
use_frameworks!

workspace 'Example'
project 'Example'

target 'Example' do
    pod 'MyPod', :path => '..'
end
```

**Comment by dnkoutso** [comment]
Yeap definitely an issue and most likely lost in merge hell we went through, can you make a PR?

**Comment by dnkoutso** [comment]
Thank you a test would be great too so this doesnt happen again!

**Comment by dnkoutso** [comment]
@Westacular please point to `1-6-stable` branch instead of master.

**Comment by Westacular** [comment]
Looks like the BananaLib tests would have caught this, except that the stripped names of both the vendored library and framework in that test are both "Bananalib", creating an ambiguity. I'll include a name change for those in my PR.

**Comment by dnkoutso** [comment]
awesome thanks! I will be here to review. I can make a 1.6.0.rc.2 next week.
