### ISSUE TITLE
Pod not linking to its vendored library

### ISSUE THREAD

**Issue by zwaldowski** [CocoaPods/CocoaPods#8454]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod update` after installing 1.6.0.rc.1 on a project using a pod `Foo` that a) has a `vendored_libraries` of `libbar.a` and b) has `source_files` that import and use symbols from that vendored library.

Seems related to #8453 but not quite the same.

## What did you expect to happen?

I am able to build the project, with `Foo` linking `-lbar`.

## What happened instead?

During the `pod update`, `Pods/Target Support Files/Foo/Foo.xconfig` loses its `-l"bar"` linker flag.

## CocoaPods Environment

<details>

### Stack

```
   CocoaPods : 1.6.0.rc.1
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 3.0.2
        Host : Mac OS X 10.14.4 (18E174f)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.1
Ruby lib dir : /usr/local/var/rbenv/versions/2.5.3/lib
Repositories : apple-istpods - git@github.pie.apple.com:PartnerMobile/ISTPods.git @ 82c3a8c96d44e816c593c14e0cf36acee8d4ece2
               master - https://github.com/CocoaPods/Specs.git @ b190fea926b7f8d4ec3005884e63ee32e1f6444b
```

### Installation Source

```
Executable Path: /usr/local/var/rbenv/versions/2.5.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'git@github.pie.apple.com:PartnerMobile/ISTPods.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

def common_frameworks
    pod 'monkey', :path => './monkey'
end

target 'SimpleApp' do
  common_frameworks
end

target 'SimpleFramework' do
  common_frameworks
end
```
</details>

## Project that demonstrates the issue

[SimpleApp.zip](https://github.com/CocoaPods/CocoaPods/files/2798260/SimpleApp.zip)

**Comment by dnkoutso** [comment]
This is the same issue, why is not quite the same?

**Comment by dnkoutso** [comment]
You are correct it is different. Will look further.

**Comment by dnkoutso** [comment]
@zwaldowski 

It does not appear that 1.6.0.rc1 has changed the build settings:

1.5.3 for `monkey.xcconfig`
```
CONFIGURATION_BUILD_DIR = ${PODS_CONFIGURATION_BUILD_DIR}/monkey
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/../monkey"
OTHER_LDFLAGS = -l"monkey" -l"z"
OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/../monkey
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
```

1.6.0.rc.1 for `monkey.xcconfig`
CONFIGURATION_BUILD_DIR = ${PODS_CONFIGURATION_BUILD_DIR}/monkey
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/../monkey"
OTHER_LDFLAGS = $(inherited) -l"monkey" -l"z"
OTHER_SWIFT_FLAGS = $(inherited) -D COCOAPODS
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/../monkey
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
```

The `-l` is only added to the `monkey.framework` target because it is a framework.

**Comment by dnkoutso** [comment]
@zwaldowski was this working on a prior version for you?

**Comment by arielpollack** [comment]
Same here. 
Happens also for the React framework, I think it's a critical issue as I only found about it because my CI (BuddyBuild) apparently updated their CocoaPods version so my builds started to fail because it missed `DoubleConversion` and `glog` frameworks.

Testing it locally, installing pods under 1.6.0.beta.2, 1.5.* works, but 1.6.0 doesn't.

![image](https://user-images.githubusercontent.com/1862153/52470459-dcbd6800-2b96-11e9-8a52-53570980ae40.png)

**Comment by gregcotten** [comment]
Hi this is happening for me also. 1.6 onward fails to work for me.

**Comment by 666tos** [comment]
Same issue with 1.6.1

**Comment by 666tos** [comment]
Let's say we have pods `A` and `B`
Pod `B` contains static libraries. 
Pod `A` has B as dependency.
`1.7.1` does not generate `LIBRARY_SEARCH_PATHS`, comparing to `1.5.3`, which is causing `ld: library not found` linker error

**Comment by codecaffeine** [comment]
Yes, I’m running into the same issue as @666tos

**Comment by 666tos** [comment]
Created followup bug https://github.com/CocoaPods/CocoaPods/issues/9548
