### ISSUE TITLE
Vendored frameworks might have  bcsymbolmap files next to them so should copy them

### ISSUE THREAD

**Issue by dacaiguoguogmail** [CocoaPods/CocoaPods#8461]
Vendored frameworks might have  bcsymbolmap files next to them so should copy them.

**Comment by dnkoutso** [comment]
Are these files next to `.framework` like `dSYM` or _within_ the `.framework`?

**Comment by dacaiguoguogmail** [comment]
In the same folder. Like this
```
65872824-5735-3872-B3A8-40216155B829.bcsymbolmap 

A26156AF-A856-3ED6-AD10-9C837D306A08.bcsymbolmap
Vendors.framework.dSYM
Vendors.framework
```

**Comment by dacaiguoguogmail** [comment]
bcsymbolmap files next to .framework like dSYM

**Comment by endresjd** [comment]
So in 1.7.4 I don't see it handling the bcsymbolmap files for vendored frameworks.  I have

1204127A-202B-3D1A-9AF0-C7D15706E9B8.bcsymbolmap
MyFramework.framework
MyFramework.framework.dSYM

But the bcsymbolmap never shows up.  Is there an extra step I need to do?

**Comment by dnkoutso** [comment]
Upload a sample app demonstrating the issue.

**Comment by endresjd** [comment]
I'm this [article](https://medium.com/onfido-tech/distributing-compiled-swift-frameworks-via-cocoapods-8cb67a584d57) as a template, and the zip file contains the projects and repositories.

Project: [binarytest.zip](https://github.com/CocoaPods/CocoaPods/files/3451771/binarytest.zip)

Just note that this is Xcode 11, fwiw.

Thanks!
