### ISSUE TITLE
can not read cocoapods version

### ISSUE THREAD

**Issue by Danie1s** [CocoaPods/CocoaPods#8462]
I want to use shields，but it can not read cocoapods version

https://github.com/badges/shields/issues/2875

**Comment by paulmelnikow** [comment]
Hello from Shields!

These URLs are both returning Forbidden:

- https://trunk.cocoapods.org/api/v1/pods/AFNetworking/specs/latest
- https://trunk.cocoapods.org/api/v1/pods/Tiercel/specs/latest

Has anything changed on your end?

Thanks!

**Comment by dnkoutso** [comment]
I am unaware of trunk status personally. Maybe @orta will know?

**Comment by Danie1s** [comment]
I have updated the version

**Comment by paulmelnikow** [comment]
Could this be reopened? These endpoint links are not working.

**Comment by paulmelnikow** [comment]
Ah, nevermind, they are working with `curl -L`. Not sure why they are not in the browser.

**Comment by paulmelnikow** [comment]
Why doesn’t the browser follow them?

**Comment by amorde** [comment]
Not sure honestly, it must be something else
