### ISSUE TITLE
dSYMs for unused architectures left in archive

### ISSUE THREAD

**Issue by fgulan** [CocoaPods/CocoaPods#8469]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Archived provided example project (https://github.com/fgulan/cocoapods-dsyms-issue).

## What did you expect to happen?

Opening `CocoapodIssue.xcarchive/dSYMs` folder and running `dwarfdump -u *` should contain dSYMs only for arm64 architecture since deployment target is set to iOS 11.0.

## What happened instead?

Mentioned archive contains Alamofire dSYMs for both arm64 and arm7 architecture - which cause App Store connect to warn us about too many symbol files.

I suspect the reason for this to happen is that Alamofire has deployment target set to iOS 8.0 and Xcode generates dSYMs for arm7 as well.

### Stack

```
   CocoaPods : 1.6.0.rc.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.3 (18D42)
       Xcode : 10.1 (10B61)
         Git : git version 2.18.0
Ruby lib dir : /Users/fgulan/.rbenv/versions/2.5.1/lib
Repositories : goinstant - https://github.com/goinstant/pods-specs-public @ 5ed86c53058e4d115764a57be7b7059238d6a10e
               master - https://github.com/CocoaPods/Specs.git @ 5cb923e97cef2b3326d4b510ef53abc1117b9c2a
```

### Installation Source

```
Executable Path: /Users/fgulan/.rbenv/versions/2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CocoapodsIssue' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoapodsIssue
  pod 'Alamofire'

end
```

## Project that demonstrates the issue

You can reproduce the issue using example project: https://github.com/fgulan/cocoapods-dsyms-issue which uses Alamofire pod targeting to iOS 8.0, while project targets to iOS 11.0

I'm not sure about correct behaviour for this issue since pods can define their custom deployment targets but as a workaround I've deleted deployment target for each pod framework - that way leaving it to automatically fallback to project deployment target.

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

**Comment by fgulan** [comment]
Not sure for 1.5.3, but on 1.6.0.beta.2 it was behaving differently.

Only difference I can see between rc1 and beta2 is that Xcode with rc1 doesn't produce update project settings warning anymore - automatically select architectures mentioned in issue https://github.com/CocoaPods/CocoaPods/issues/8242 

So, as far as I understand there are two possible workarounds:

1. Manually set `ARCHS` for each target to `ARCHS_STANDARD_64_BIT` if master project is targeting iOS 11 - but that will cause mentioned warning in Xcode 10.1
2. Delete IPHONEOS_DEPLOYMENT_TARGET for each pod target, thus letting it fallback to Pods project target which for some bundles (SwiftMessages - TabView.xib) causes warning: `This file is set to build for a version older than the deployment target. Functionality may be limited`

**Comment by amorde** [comment]
Ok wanted to make sure, I think it is the same.

There was some discussion on #7314 but I think the iOS 11 architecture issue is enough of a reason to change the behavior.

Another option is to use the same `post_install` hook to set the deployment target to whatever value you want, such as `'11.0'`

**Comment by polmum** [comment]
I'm having the same issue as described here. Is there no other solution besides the workarounds mentioned in this thread?

**Comment by amorde** [comment]
There isn't any other solution at this time
