### ISSUE TITLE
Wiki/Acknowledgements typo

### ISSUE THREAD

**Issue by pauluhn** [CocoaPods/CocoaPods#8478]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Tap `Acknowledgements` on Wiki home and
2. Tap `Acknowledgements` on Wiki side panel

## What did you expect to happen?

Accurate instructions on copying generated `plist` to project.

## What happened instead?

Couldn't find file because folder structure has changed since last update.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9f968209b0e3b337be42f557ead852677ccb5fa3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
slather               : 2.4.6
```

### Podfile

```ruby
platform :ios, '12.1'

target 'AcknowledgementSample' do
  use_frameworks!

  # Pods for AcknowledgementSample
  pod 'Swiftilities/Acknowledgements'

end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-AcknowledgementSample/Pods-AcknowledgementSample-acknowledgements.plist', 'AcknowledgementSample/Acknowledgements.plist', :remove_destination => true)
end
```

**Comment by dnkoutso** [comment]
I am sorry I do not quite understand the issue.

```
Tap Acknowledgements on Wiki home and
Tap Acknowledgements on Wiki side panel
```

Which Wiki Home and which Wiki side panel?

**Comment by pauluhn** [comment]
On the [Wiki](https://github.com/CocoaPods/CocoaPods/wiki), there is an `Acknowledgements` link under [Ancillary Features](https://github.com/CocoaPods/CocoaPods/wiki#ancillary-features) that goes to `http://blog.cocoapods.org/Acknowledgements`

Side panel is the alphabetical list of pages on the side of the Wiki. You'll find an `Acknowledgements` link that goes to `https://github.com/CocoaPods/CocoaPods/wiki/Acknowledgements`

**Comment by dnkoutso** [comment]
fixed.
