### ISSUE TITLE
Support external vendored libraries

### ISSUE THREAD

**Issue by alejandro-isaza** [CocoaPods/CocoaPods#8479]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I want to distribute a pod with a vendored library. My understanding is that the compiled library has to be checked in to the git repository. I would like to have the library be downloaded from the GitHub releases instead of having to check in a large binary file to my codebase. I would like something like

`spec.vendored_libraries = 'https://github.com/Project/myproject/releases/download/0.2.0/mylib.a'`

Bonus points for supporting zipped version. Is there a way of achieving this? If not I what would be the best approach to implement? Happy to contribute where I can.

**Comment by dnkoutso** [comment]
This can be accomplished by:
```ruby
spec.prepare_command = <<-CMD
                        # download zip here use `curl` maybe
                   CMD

spec.vendored_libraries = "path/to/downloaded/mylib.a"
```

**Comment by paulb777** [comment]
Or use the source attribute - like https://github.com/CocoaPods/Specs/blob/master/Specs/e/5/6/FirebasePerformance/2.2.2/FirebasePerformance.podspec.json#L35

**Comment by alejandro-isaza** [comment]
Great suggestions, thanks!
