### ISSUE TITLE
Parent directory chunks in host workspace's project paths result in project duplicates after pod install

### ISSUE THREAD

**Issue by anToha** [CocoaPods/CocoaPods#8481]
TL&DR: If the predefined workspace contains relative Projects' paths with parent directory chunks (i.e. `/..`) then `pod install` may reassemble the workspace with duplicated projects.

See also: https://github.com/CocoaPods/CocoaPods/issues/2413

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

All dependencies installed. The old workspace structure preserved.

### Before `pod install`
Workspace contains subprojects: App, FirstLibrary, SecondLibrary, ThirdLibrary.

### After `pod install`
Workspace contains subprojects: App, FirstLibrary, SecondLibrary, ThirdLibrary, Pods, **FirstLibrary** (duplicate).

## CocoaPods Environment

(For example project)

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.14.3 (18D42)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.17.1
Ruby lib dir : /Users/antonogarkov/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7cc24887f2051cbc6e30b7a0bd6bd94cbc923b3e
**other private repositories were removed for the output**
```

### Installation Source

```
Executable Path: /Users/antonogarkov/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.6
```

### Podfile

```ruby
platform :ios, '12.0'
use_frameworks!
workspace 'CocoapodsDuplicatedProjectDemo.xcworkspace'
project 'FirstLibrary/FirstLibrary.xcodeproj'

abstract_target 'FirstDependencies' do
  pod 'OAuthSwift', '1.2.2'
  pod 'SwiftReorder', '6.0.1'

  target 'FirstLibrary' do
    project 'FirstLibrary/FirstLibrary.xcodeproj'
  end

  target 'App' do
    project 'App/App.xcodeproj'
  end

end
```

## Project that demonstrates the issue

[CocoapodsDuplicatedProjectDemo.zip](https://github.com/CocoaPods/CocoaPods/files/2824129/CocoapodsDuplicatedProjectDemo.zip)

Please see the structure of `contents.xcworkspacedata` in the project - FirstLibrary project reference is the following:
`"group:OMGNotExistingDirectory/../FirstLibrary/FirstLibrary.xcodeproj"`

**Comment by anToha** [comment]
Workaround is described here: https://github.com/CocoaPods/CocoaPods/issues/2413#issuecomment-459267252

**Comment by dnkoutso** [comment]
Thanks @anToha !

**Comment by dnkoutso** [comment]
Fixed by https://github.com/CocoaPods/Xcodeproj/pull/760 will ship in next version of Xcodeproj gem.
