### ISSUE TITLE
Xcode 10.2 beta 2 warning: Enable Base Internationalization

### ISSUE THREAD

**Issue by alex-vasenin** [CocoaPods/CocoaPods#8494]
# Report

## What did you do?

Run `pod install`.

## What did you expect to happen?

Xcode shows no warnings.

## What happened instead?

Xcode 10.2 beta 2 shows **Enable Base Internationalization** warning on Pods project. Xcode release notes [states](https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_beta_2_release_notes)
> Enabling Base Internationalization is recommended for all projects, and any projects that don’t currently use Base Internationalization are offered an upgrade even if they only have a single localization. The upgraded projects are backward-compatible with previous releases of Xcode. (15160454)

### Stack

```
   CocoaPods : 1.6.0.rc.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.2 (10P91b)
         Git : git version 2.20.1 (Apple Git-116)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ca3a92816774e978c816594083d67f2f17ee43a6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.0'
inhibit_all_warnings!
use_frameworks!

workspace 'XyzExample.xcworkspace'

def xyz_pods
  pod 'TwilioChatClient'
  pod 'JWTDecode'
  pod 'PromiseKit/CorePromise'
  pod 'MBProgressHUD'
  pod 'Chatto'
  pod 'ChattoAdditions'
  pod 'PINCache'
end

target 'XyzExample' do
  project 'XyzExample.xcodeproj'
  pod 'Fabric'
  pod 'Crashlytics'
  xyz_pods
end

target 'Xyz' do
  project '../Xyz.SDK/Xyz.xcodeproj'
  xyz_pods
end

target 'XyzTests' do
  project '../Xyz.SDK/Xyz.xcodeproj'
  xyz_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['Chatto', 'ChattoAdditions'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
```

**Comment by dnkoutso** [comment]
Yes they probably need to be updated.

**Comment by xmollv** [comment]
Just as a confirmation, on the final version of Xcode 10.2 (10E125) the warning appears as described above.

**Comment by DenTelezhkin** [comment]
I would also add that apart from Pods project mentioned in this issue, if you use new experimental flag `generate_multiple_pod_projects` set to true, those warnings also appear in **each** CocoaPod dependency, which makes warning levels go to extreme. 

@dnkoutso Maybe you can point out how Xcode project for CocoaPods generation can be updated, so I could help with PR to solve this issue as soon as possible?

**Comment by benguild** [comment]
Also seeing this on the 10.2 release build.

**Comment by kubatruhlar** [comment]
You could set the `Missing localizability` key in the Build Settings to `false` and restart Xcode.

**Comment by fsuc** [comment]
Thanks, @kubatruhlar. The following code seems to remove the warning.

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end
end

**Comment by kreeger** [comment]
@fsuc That doesn't seem to fix our issue; if I blow away `Pods/` and run `pod install` after placing that code at the bottom of my `Podfile`, the localization warnings for the `Pods` project reappear.

**Comment by fsuc** [comment]
@kreeger You're right, 2 new localization warnings appear when you relaunch Xcode (there's no issue after closing and reopening the project ...). Xcode wants to remove the deprecated English development region and enable base internationalization.

**Comment by kmuralidharan91** [comment]
any help/suggestion for the warning?

**Comment by owenzhao** [comment]
> Migrate “English.lproj” (Deprecated)
> Migrating the English, deprecated localization to English is recommended for all projects. This will ensure localized resources are placed in “en.lproj” directories instead of deprecated “English.lproj” directories.

So it is just a directory name issue. Maybe this should be done by the creator of the specific pod other than CocoaPods, or a warning should also be made when creating a pod?

**Comment by MaximeLM** [comment]
The workaround by @fsuc can be updated to fix the two additional warnings:

``` ruby
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end
  installer.pods_project.root_object.known_regions.insert(0, "Base")
  installer.pods_project.root_object.development_region = "en"
end
```

**Comment by stanmots** [comment]
Xcode Version 10.2.1 (10E1001) still shows these warnings:
 ![Image of Xcode Warnings](https://i.imgur.com/ufvq8ll.png)

**Comment by dnkoutso** [comment]
I believe this is fixed by https://github.com/CocoaPods/Xcodeproj/pull/669. We released xcodeproj 1.9.0 can someone verify?

**Comment by stanmots** [comment]
@dnkoutso Tried CocoaPods 1.7.0.rc.1 - same issues. Also tried the new `generate_multiple_pod_projects` and this is what I got:
 ![Image of Xcode Warnings](https://i.imgur.com/lrEphO6.png)

**Comment by dnkoutso** [comment]
But did you ensure xcodeproj gem is on version 1.9.0?

**Comment by stanmots** [comment]
I installed CocoaPods using this command: `sudo gem install cocoapods --pre`. Is there something else I need to do to ensure xcodeproj is 1.9.0?

**Comment by dnkoutso** [comment]
Yes its a different gem. 'gem update xcodeproj'.

**Comment by stanmots** [comment]
Okay, I've just rebuilt the project and everything works fine. Thanks.

**Comment by chrisvanbuskirk** [comment]
<img width="261" alt="Screen Shot 2019-05-05 at 12 05 48 PM" src="https://user-images.githubusercontent.com/3638007/57198279-27e4de00-6f2e-11e9-9e44-578a0ff07500.png">

I'm still affected.  Updated to rc1 and the latest version of xcodeproj.

**Comment by stanmots** [comment]
@chrisvanbuskirk Ensure that you have xcodeproj-1.9.0 properly installed. If you used sudo then check out the following path: `Library/Ruby/Gems/<RubyVersion>/gems/`. When I removed older versions of xcodeproj from this folder the warnings disappeared.

**Comment by chrisvanbuskirk** [comment]
@stanmots Thanks...it works now.

**Comment by dnkoutso** [comment]
It seems this is good to close then?

**Comment by DenTelezhkin** [comment]
Resolved in both 1.7.0 and 1.6.x 👍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dnkoutso** [comment]
For anyone following `gem update xcodeproj` to version 1.9.0 to fix this. Closing.

**Comment by ferrerod** [comment]
I don't think this is yet resolved. I have verified I have gem xcodeproj 1.9.0 and removed all older xcodeproj gems. I'm using cocoapods 1.7.1, bundler 1.17.1
I have tried deleting derived Xcode's derived data, I've tried bundle exec pod deintegrate then deleting Pods and workspace and recreating with install. No matter what I do the Base International warning reappears. It appears the Pods project is not keeping the flag set to Base. Thoughts?

When I run bundle exec pod install, the Pods/Pods.xcodeproj/project.pbxproj knows:
```
knownRegions = (
                                en,
                        );
```

instead of:
```
knownRegions = (
                                en,
                                Base,
                        );
```

**Comment by tache** [comment]
> @chrisvanbuskirk Ensure that you have xcodeproj-1.9.0 properly installed. If you used sudo then check out the following path: `Library/Ruby/Gems/<RubyVersion>/gems/`. When I removed older versions of xcodeproj from this folder the warnings disappeared.

to remove older version of xcodeproj 

`gem uninstall xcodeproj`

**Comment by chrisballinger** [comment]
This is issue has resurfaced with Xcode 11.1 and xcodeproj (1.12.0)

**Comment by richellis** [comment]
This warning is happening again with Xcode 11.6, CocoaPods 1.9.3, xcodeproj 1.17.0. If I accept the changes Xcode makes I see this in the diff:
```
--- a/Pods/Pods.xcodeproj/project.pbxproj
+++ b/Pods/Pods.xcodeproj/project.pbxproj
@@ -8864,7 +8864,7 @@
                        isa = PBXProject;
                        attributes = {
                                LastSwiftUpdateCheck = 1100;
-                               LastUpgradeCheck = 1100;
+                               LastUpgradeCheck = 1160;
                        };
                        buildConfigurationList = 4821239608C13582E20E6DA73FD5F1F9 /* Build configuration list for PBXProject "Pods" */;
                        compatibilityVersion = "Xcode 9.3";
@@ -12137,6 +12137,7 @@
                        isa = XCBuildConfiguration;
                        buildSettings = {
                                ALWAYS_SEARCH_USER_PATHS = NO;
+                               CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
                                CLANG_ANALYZER_NONNULL = YES;
                                CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
                                CLANG_CXX_LANGUAGE_STANDARD = "gnu++14";
@@ -14046,6 +14047,7 @@
                        isa = XCBuildConfiguration;
                        buildSettings = {
                                ALWAYS_SEARCH_USER_PATHS = NO;
+                               CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED = YES;
                                CLANG_ANALYZER_NONNULL = YES;
                                CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
                                CLANG_CXX_LANGUAGE_STANDARD = "gnu++14";
```
