### ISSUE TITLE
Sources under a "Resources" directory missing with a Resource Bundle

### ISSUE THREAD

**Issue by sebastianv1** [CocoaPods/CocoaPods#8496]
# Report
**Note**: This is based off the tip of CocoaPods master.

Xcode does not have the correct path to source files under a directory named `Resources` when its resource bundle also points to a directory named `Resources`. These are not the same directories, as the project structure looks like:
```
MyProject
-->Sources
---->Resources
------>1.h & 1.m
-->Resources
---->Images.xcassets
```
This causes the build to fail as `1.h` and `1.m` are missing.

## CocoaPods Environment
branch:`master`

## Project that demonstrates the issue
[ResourcesErrorSample.zip](https://github.com/CocoaPods/CocoaPods/files/2842173/ResourcesErrorSample.zip)

**Comment by segiddins** [comment]
Any chance this is related to https://github.com/CocoaPods/CocoaPods/pull/8445/files ?

**Comment by segiddins** [comment]
cc @amorde

**Comment by amorde** [comment]
Ah yep, it is

**Comment by amorde** [comment]
I'm thinking we shouldn't be using `reflect_file_system_structure` for resources here

https://github.com/CocoaPods/CocoaPods/blob/984af0b1c31000b30455b276bcac21d424003f40/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb#L110-L115

**Comment by amorde** [comment]
Have a fix for this, PR will be up soon
