### ISSUE TITLE
inherit! :search_paths not inheriting user_target_xcconfig settings in CocoaPods 1.6.0

### ISSUE THREAD

**Issue by vincentisambart** [CocoaPods/CocoaPods#8497]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Create a new "Single View App" project with Unit Tests in Xcode 10.1.
- `bundle init`
- Add `gem "cocoapods"` to the Gemfile
- `bundle exec pod init`
- In the generated Podfile, add `pod "Firebase"` to the main target.
- `bundle exec pod install`
- Open the xcworkspace in Xcode
- Add `import Firebase` to AppDelegate.swift
- Run the tests (Cmd+U)

## What did you expect to happen?

I expected the tests to build (and run) without any problem, as it does with CocoaPods 1.5.3.

## What happened instead?

`Missing required module 'Firebase'` error on the `@testable import` of the unit test file.

If seems that when using CocoaPods 1.5.2, the `Header Search Path` of the Tests target contains the `HEADER_SEARCH_PATHS` setting added by the podspec's `user_target_xcconfig` (https://github.com/CocoaPods/Specs/blob/master/Specs/0/3/5/Firebase/5.16.0/Firebase.podspec.json#L48-L50), but when using CocoaPods 1.6.0 it's not included.

**Comment by segiddins** [comment]
Huh, I had no idea that `inherit! :search_paths` included `user_target_xcconfig` of the inherited pods... This should be relatively easy to fix, by changing https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/target/build_settings.rb#L1135 to include inherited pod targets as well

**Comment by mrgrauel** [comment]
@segiddins do you plan a bug fix release for this one? We have to stay on 1.5.3 cause of this issue.

**Comment by dnkoutso** [comment]
The fix is here https://github.com/CocoaPods/CocoaPods/pull/8500

**Comment by vincentisambart** [comment]
@dnkoutso Thanks for the fix!
