### ISSUE TITLE
Unable to use dynamic framework inside my cocoapod

### ISSUE THREAD

**Issue by dsrijan** [CocoaPods/CocoaPods#8504]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod lib lint`
  s.vendored_frameworks = 'Dynamic.framework'
  s.ios.vendored_frameworks = 'Framework/Dynamic.framework'

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin17]
    RubyGems : 2.7.8
        Host : Mac OS X 10.13.6 (17G2208)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/srijankumar/.rvm/rubies/ruby-2.2.4/lib
Repositories : // Private repo

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```


## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dsrijan** [comment]
Why this closed without any comment?

**Comment by amorde** [comment]
@dsrijan It looks like the template wasn't properly filled out - notice the sections that say "Please replace these two lines with..."

Apologies for the quick close, we get a lot of issue submissions that are just the empty template

**Comment by amorde** [comment]
As it stands we can't provide any assistance as the only context you've given are these two lines:

```ruby
s.vendored_frameworks = 'Dynamic.framework'
s.ios.vendored_frameworks = 'Framework/Dynamic.framework'
```
