### ISSUE TITLE
Using weak_framework on a Podfile with use_frameworks! broken on 1.6.0

### ISSUE THREAD

**Issue by leolobato** [CocoaPods/CocoaPods#8505]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` using CocoaPods 1.6.0 on a project that worked fine with CocoaPods 1.5.3.

Pods project won't build now, complaining about missing symbols for a weakly linked framework required by a Pod.

## What did you expect to happen?

Pods to be reinstalled and project to build, just like it did on 1.5.3.

## What happened instead?

Pods project was updated but workspace won't build anymore.

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.15.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1e819df018715de5b4616c7b6d724193756e681f
               mediabrix - https://github.com/mediabrix/mediabrix-cocoapods-spec.git @ ba8de3e81619fe553260f1775bf50243508caecc
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'WeakTest' do
    platform :ios, '9.0'
    use_frameworks!
    
    pod 'Flurry-iOS-SDK/FlurrySDK'
    pod 'Flurry-iOS-SDK/FlurryMessaging'
    pod 'Flurry-iOS-SDK/FlurryAds'
end
```

## Project that demonstrates the issue

It's attached here.

It seems the issue is on `OTHER_LDFLAGS` on the generated `Flurry-iOS-SDK.xcconfig` file:

On 1.5.3 it looks like:

    OTHER_LDFLAGS = -l"FlurryAds_1.1.0" -l"FlurryMessaging_9.3.0" -l"Flurry_9.3.0" -l"z" -framework "AVFoundation" -framework "CoreGraphics" -framework "CoreMedia" -framework "CoreTelephony" -framework "Foundation" -framework "MediaPlayer" -framework "Security" -framework "SystemConfiguration" -framework "UIKit" -framework "WebKit" -weak_framework "AdSupport" -weak_framework "SafariServices" -weak_framework "StoreKit"

and on 1.6.0 it's missing all `-weak_framework`:

    OTHER_LDFLAGS = $(inherited) -l"FlurryAds_1.1.0" -l"FlurryMessaging_9.3.0" -l"Flurry_9.3.0" -l"z"

[WeakTest-sample-project.zip](https://github.com/CocoaPods/CocoaPods/files/2851597/WeakTest-sample-project.zip)

**Comment by dnkoutso** [comment]
Fixed already here https://github.com/CocoaPods/CocoaPods/issues/8493
