### ISSUE TITLE
Support test_spec configurable test_types

### ISSUE THREAD

**Issue by mikehaney24** [CocoaPods/CocoaPods#8507]
When using cocoapods-generate, a new test target is created for each test target. This is awesome!

One thing to make it even more awesome would be to allow developers to specify the `test_type` in the `test_spec` so that our generated test targets have configurable names.

For example, these two test specs from [GoogleDataTransport](https://github.com/firebase/firebase-ios-sdk/blob/googledatatransport/GoogleDataTransport.podspec)

```
  # Unit test specs
  s.test_spec 'Unit' do |test_spec|
    test_spec.requires_app_host = false
    test_spec.source_files = ['GoogleDataTransport/Tests/Unit/**/*.{h,m}'] + common_test_sources
  end

  # Integration test specs
  s.test_spec 'Integration' do |test_spec|
    test_spec.requires_app_host = false
    test_spec.source_files = ['GoogleDataTransport/Tests/Integration/**/*.{h,m}'] + common_test_sources
    test_spec.compiler_flags = '-DGDT_LOG_TRACE_ENABLED=1'
    test_spec.dependency 'GCDWebServer'
  end
```
 
produce test targets of the names `GoogleDataTransport-Unit-Unit` and `GoogleDataTransport-Unit-Integration`

If one could specify the test_type in `pod_target_installer.rb` and `pod_target.rb` via the `test_spec`, we could configure the test target names to be something other than `Unit`

**Comment by dnkoutso** [comment]
The DSL is there and by default only supports `:unit`. This was meant to match Apples unit test bundle vs UI test bundle which runs different and produces a different product I believe.

https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L1460

There is no support yet or UI test but the DSL was built in a way that it can be expanded. Am I understanding that you are asking for this improvement?

**Comment by mikehaney24** [comment]
I think you mostly got it. Said another way, while Apple only inherently supports 'Unit' and 'UI', instead of generating a scheme with those words, I'd like to be able to configure the word that's generated via a param in the test_spec.

**Comment by dnkoutso** [comment]
Ok so it is more about the generated name of the target rather than supporting a new test type (UI in this case).

This can range from "easy" to "medium" enhancement but I am curious on the underlying reason to give such an option. Is it more cosmetic?

**Comment by mikehaney24** [comment]
Yes, it's cosmetic. Having the word 'Unit' in a test that isn't quite a
unit test (even if it uses Apple's unit test infrastructure) can be
difficult to understand.

**Comment by dnkoutso** [comment]
Understood. I am marking this as a medium/enhancement because believe it or not it might need a DSL change to be able to customize this, which would require a review and approval to extend.

The alternative path is a `post_install` hook that updates the targets names. Note this won't update the internal files that CocoaPods generates (such as the .xcconfig and info.plist for the target) but that might be OK.

**Comment by dnkoutso** [comment]
Maybe a `plugin` also?

**Comment by mikehaney24** [comment]
Now, my need has slightly evolved, and I definitely need XCUITest support (in addition to the desire to have customizable target names). Should I create a new issue for that?

**Comment by dnkoutso** [comment]
@mikehaney24 that is a bigger task we can perhaps repurpose this issue to be the one that adds support for XCUITest bundles into cocoapods.

**Comment by mikehaney24** [comment]
SGTM, thanks for your attention!

**Comment by dnkoutso** [comment]
Kind of being eyeing to add support for this 1.9.0.

**Comment by dnkoutso** [comment]
@mikehaney24 1.8.0.beta.1 added support for UI test bundles. Should we close this?

**Comment by mikehaney24** [comment]
SGTM!
