### ISSUE TITLE
Pods using `:podspec` aren't updated when their podspecs are changed

### ISSUE THREAD

**Issue by noahsark769** [CocoaPods/CocoaPods#8509]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I've been having an issue with external pods (using internal podspecs with `:podspec`) not updating when their version is changed. When you change an internal podspec for an external library, the new version of the library is not fetched on the next `pod install`.

## What did you do?

Made the following sample projects to demonstrate the issue:

1. Created [NGResourcePodExample](https://github.com/noahsark769/NGResourcePodExample) as a library which distributes an asset (txt file). There are two "releases" of this example library available as tars on github (1.0.0 and 1.1.0): [https://github.com/noahsark769/NGResourcePodExample/releases](https://github.com/noahsark769/NGResourcePodExample/releases).
2. Created [NGProjectThatRequestsNGResourcePodExample](https://github.com/noahsark769/NGProjectThatRequestsNGResourcePodExample), which is an example iOS app which consumes the resource pod. The Podfile looks like:
    ```
    pod 'NGResourcePodExample', :podspec => 'InternalPodspecs/NGResourcePodExample.podspec'
    ```

    And the relevant portion of the podspec is:
    ```
    url = "https://github.com/noahsark769/NGResourcePodExample/releases/download/v#{s.version}/v#{s.version}.tar"
    s.source = {
        :http => url,
        :flatten => false
    }
    ```
    Ran the following to set it up:

    ```
    bundle install
    bundle exec pod install
    ```

This succeeded. Then, changed the `InternalPodspecs/NGResourcePodExample.podspec`'s version from 1.0.0 to 1.1.0 and ran `bundle exec pod install`.

## What did you expect to happen?

I expected the pod to get updated with the new resources from 1.1.0 of [NGResourcePodExample](https://github.com/noahsark769/NGResourcePodExample)

## What happened instead?

The library is not updated and continues to use 1.0.0. On `pod install`, it says `Using NGResourcePodExample (1.0.0)`.

I tried to `rm -rf Pods/NGResourcePodExample/`, but that makes CocoaPods error on subsequent pod installs:

```
[!] CocoaPods could not find compatible versions for pod "NGResourcePodExample":
  In snapshot (Podfile.lock):
    NGResourcePodExample (from `InternalPodspecs/NGResourcePodExample.podspec`)

  In Podfile:
    NGResourcePodExample (from `InternalPodspecs/NGResourcePodExample.podspec`)

None of your spec sources contain a spec satisfying the dependencies: `NGResourcePodExample (from `InternalPodspecs/NGResourcePodExample.podspec`), NGResourcePodExample (from `InternalPodspecs/NGResourcePodExample.podspec`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

I'm not sure if this is the expected behavior, and I think that I might need to use a differently named podspec file for the 1.1.0 version? If this is the case, I think we should document that this is necessary (i.e. that just updating the content of an internal podspec is not sufficient to make CocoaPods install a new version). It would also be great to confirm that this is the expected behavior.

It looks like this has been discussed before in #1623 and #2278:

> I'd expect that if I did a `pod install` with a local pod it would do the equivalent to `pod update XX` and update to be whatever version the Podspec is. My main argument here is that the files will always be up to date because they're sym-linked but ignoring changes to the Podspec doesn't make sense.

I'm not sure if those changes ever made it in, or if there's a better way to handle this case now.

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.8
        Host : Mac OS X 10.14.1 (18B75)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 521d35ff6d9529ca5f254b64c8217753bf0377c2
```

### Installation Source

```
Executable Path: /Users/ngilmore/NGProjectThatRequestsNGResourcePodExample/vendor/bundle/ruby/2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NGProjectThatRequestsNGResourcePodExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'NGResourcePodExample', :podspec => 'InternalPodspecs/NGResourcePodExample.podspec'

end
```

## Project that demonstrates the issue

[NGProjectThatRequestsNGResourcePodExample](https://github.com/noahsark769/NGProjectThatRequestsNGResourcePodExample) (which consumes [NGResourcePodExample](https://github.com/noahsark769/NGResourcePodExample)). More detailed info available in the project's README and here in the "What did you do?" section.

**Comment by dnkoutso** [comment]
Why not run `bundle exec pod update <podname>`? The file that it was locked in `Podfile.lock` will be used by `pod install`.

**Comment by noahsark769** [comment]
@dnkoutso great question! I should have included this in the original report - we tried using `bundle exec pod update NGResourcePodExample` initially, but committing those changes (as well as the changes to `Podfile.lock`) breaks `pod install` for other developers that have already installed pods in the same repo.

To demonstrate this, I ran `bundle exec pod update NGResourcePodExample`, committed the result, and pushed [`a52a5d8691e2cff0a4d34dcf341d9879df499318`](https://github.com/noahsark769/NGProjectThatRequestsNGResourcePodExample/commit/a52a5d8691e2cff0a4d34dcf341d9879df499318) in the example project repo. Other developers pulling the new commit and running `bundle exec pod install` get the same error:

```
  In snapshot (Podfile.lock):
    NGResourcePodExample (from `InternalPodspecs/NGResourcePodExample.podspec`)

  In Podfile:
    NGResourcePodExample (from `InternalPodspecs/NGResourcePodExample.podspec`)

None of your spec sources contain a spec satisfying the dependencies: `NGResourcePodExample (from `InternalPodspecs/NGResourcePodExample.podspec`), NGResourcePodExample (from `InternalPodspecs/NGResourcePodExample.podspec`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

The following commands should hopefully reproduce this error if you're interested:
```
git clone git@github.com:noahsark769/NGProjectThatRequestsNGResourcePodExample.git NGProjectThatRequestsNGResourcePodExample-2
cd NGProjectThatRequestsNGResourcePodExample-2
bundle install
bundle exec pod install # succeeds, using 1.0.0 library version
git fetch origin
git checkout a52a5d8691e2cff0a4d34dcf341d9879df499318
bundle exec pod install # expect to succeed with the new library version, errors instead
```

Perhaps the fact that installing with the new `Podfile.lock` makes this error is a bug in itself - happy to report a different issue if needed.

The other developers could run `bundle exec pod update NGResourcePodExample` to fix this, but I'd argue that we shouldn't be imposing this workflow every time `NGResourcePodExample` is updated. Instead, I would expect something like the discussion in #1623, where updating a local filesystem podspec would be equivalent to running `pod update <podname>`.

**Comment by segiddins** [comment]
> Perhaps the fact that installing with the new `Podfile.lock` makes this error is a bug in itself - happy to report a different issue if needed.

I think it is, but that ought to have been fixed by https://github.com/CocoaPods/CocoaPods/pull/8178 ?

**Comment by noahsark769** [comment]
> I think it is, but that ought to have been fixed by #8178 ?

@segiddins That seems like a similar issue, although I think the JSON podspec and its checksum are now being correctly set on first install (I can see it in `Pods/Local\ Podspecs/NGResourcePodExample.podspec.json`):

```
$ git clone git@github.com:noahsark769/NGProjectThatRequestsNGResourcePodExample.git NGProjectThatRequestsNGResourcePodExample-3
$ cd NGProjectThatRequestsNGResourcePodExample-3
$ bundle install
$ bundle exec pod install
$ shasum -a 1 Pods/Local\ Podspecs/NGResourcePodExample.podspec.json
08b4adf73a95e5720518cbcf08ef54acaa142082  Pods/Local Podspecs/NGResourcePodExample.podspec.json
$ cat Podfile.lock | grep 08b4
  NGResourcePodExample: 08b4adf73a95e5720518cbcf08ef54acaa142082
```

Just for reference, everything here was repro'd on 1.6.0

**Comment by noahsark769** [comment]
@segiddins @dnkoutso should I open a separate github issue for Cocoapods failing to install with the new Podfile.lock that I mentioned in https://github.com/CocoaPods/CocoaPods/issues/8509#issuecomment-463031569 ?

**Comment by dnkoutso** [comment]
No I think this issue is sufficient?

**Comment by noahsark769** [comment]
Got it! I think I'll probably have some time today to look into it - I'm guessing the issue is probably somewhere in molonillo. Will keep this thread updated if I figure anything out 👍

**Comment by noahsark769** [comment]
Thanks for the bump, stalebot. Unfortunately I haven’t had time to look at this, will update here if I do
