### ISSUE TITLE
Localize test's AppHost to test specific localizations

### ISSUE THREAD

**Issue by likhogrud** [CocoaPods/CocoaPods#8522]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

My application contains several localization. I use cocoapods `tests_spec`s to keep tests close to pods. According to [apple's documentation](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html), to run tests for russian localization I set ApplicationLanguage and ApplicationRegion to Russian in scheme options. I found out that it works only for tests bundles that have host app. Okay, set `requires_app_host` to `true` for `test_spec` in podspec. 

## What did you expect to happen?

`Locale.current.identifier` in tests generated from `test_spec`s is `ru_RU`

## What happened instead?

`Locale.current.identifier` in tests is `en_RU`.

It happens because run settings from scheme applied to `TEST_HOST` and then inherited by tests. If `TEST_HOST` does not support locale, then default `localization native development region` is used. In my case, localization native development region is 'en' and `Locale.current.identifier` in tests is `en_RU`.

If at least one file in `TEST_HOST` is localized, then all works fine. I demonstrate it in [example](https://github.com/likhogrud/cocoapods-locale-dependent-tests) by creating exact the same tests target whose  `TEST_HOST` is main app, which is localized. 

`Pods.xcodeproj` knows about localizations of pods - it retrieves them from pod's  resources. I suppose that cocoapods can localize generated TEST_HOSTs on all localizations from pod. It's enougth to localize `LaunchScreen.storyboard` - copy it to `<lang>.lproj` subdirectories. 

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.16.3
Ruby lib dir : /Users/likhogrud/.rvm/rubies/ruby-2.1.1/lib
Repositories :
               master - https://github.com/CocoaPods/Specs.git @ c34741476c90f4b423f332d9fdebe0df706df31e
            
```

### Installation Source

```
Executable Path: /Users/likhogrud/.rvm/gems/ruby-2.1.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
inhibit_all_warnings!

target 'CocoapodsLocaleDependentTests' do
    project 'CocoapodsLocaleDependentTests'
end

target 'TestsBundle' do
    project 'CocoapodsLocaleDependentTests'
    pod 'LocaleDependentLib', :path => "./LocaleDependentLib", :testspecs => ['Tests']
end
```
## Project that demonstrates the issue

https://github.com/likhogrud/cocoapods-locale-dependent-tests

**Comment by dnkoutso** [comment]
Should we set this value for generated bundles to `$(DEVELOPMENT_LANGUAGE)` instead?

**Comment by likhogrud** [comment]
$(DEVELOPMENT_LANGUAGE) is fixed in project settings. ApplicationLanguage and AppleLocale are  launch arguments, and are fixed in scheme settings. [Documentation](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html).

**Comment by dnkoutso** [comment]
@amorde is this fixed by Info plist DSL in 1.8?

**Comment by amorde** [comment]
Yes I think so, but there is a setting `developmentRegion` within the project itself which might mess with this.

@likhogrud here's an example of how this would work:
```ruby

s.test_spec 'Tests' do |spec|
  spec.source_files = 'Tests/**/*.swift'
  spec.dependency 'FBSnapshotTestCase'
  spec.requires_app_host = true
  spec.app_host_name = 'LocaleDependentLib/TestHost'
  spec.dependency 'LocaleDependentLib/TestHost'
end

  s.app_spec 'TestHost' do |spec|
    # This will be the host target for the `Tests` subspec
    spec.info_plist = {
      'CFBundleDevelopmentRegion' => 'ru_RU'
    }
    spec.source_files = 'AppDelegate.swift'
  end
```

I'll send a PR to your example repo with these changes so you can try it

**Comment by amorde** [comment]
https://github.com/likhogrud/cocoapods-locale-dependent-tests/pull/1

**Comment by likhogrud** [comment]
Hi. Thanks for the help. I apologize for the long answer, there was no time to figure it out well.

The proposed solution works, but only on cocoapods 1.7.4 from master @ 51d84f5. On 1.8.0.beta.1 - unfortunately not, for some reason resource bundles are not copied to the test bundle, although tests are linked to the library by `OTHER_LDFLAGS = $ (inherited) -ObjC -l "LocaleDependentLib"` in .xcconfig. Therefore, `Bundle (for: LocaleDependentLib.Resources.self)` returns a test bundle, but there is no bundle with resources in it. At the same time, resources are copied to app_host. Possibly, it is expected that tests should take symbols from app_host through **Allow testing Host Application APIs.** But then link tests with the library - an error, because we get duplication of symbols. Loader writes to console: 

> Class PodsDummy_LocaleDependentLib is implemented in both .... / LocaleDependentLib-TestHost.app/LocaleDependentLib-TestHost (0x109efb208) and .... ) One of the two will be used. Which one is undefined.

In 1.7.4 from master @ 51d84f5 tests pass successfully, because resources are copied, but there is warnings about duplicated symbols too.

The proposed solution is correct only when `use_frameworks!` is specified in the Podfile and pods are built to dynamic libraries, which are then packed together with resources into frameworks. With static libraries, the default non-disable dependency of both test_specs and app_specs on the parent pod together with using of app_specs as hosts for test_specs always leads to duplication of symbols.

I modified the solution a bit by extracting fake app_host into a separate pod. This was prompted by the example `test_spec.app_host_name = 'CannonPodder / DemoApp'` - that you need to specify the parent pod of app_host. I ended up making two specs

```
Pod :: Spec.new do | s |
  ...
  s.source_files = 'Sources / ** / *'

  s.app_spec 'App' do | spec |
    spec.info_plist = {
      'CFBundleDevelopmentRegion' => 'ru_RU'
    }
    spec.source_files = 'AppDelegate.swift'
  end
end 
```

and  

```
Pod :: Spec.new do | s |
  ...

  s.source_files = 'Sources / ** / *'
  s.resource_bundles = {'LocaleDependentLib' => 'Resources / *. lproj / *'}

  s.test_spec 'Tests' do | spec |
    spec.source_files = 'Tests / ** / *. swift'
    spec.dependency 'FBSnapshotTestCase'
    spec.requires_app_host = true
    spec.app_host_name = 'TestHost / App'
    spec.dependency 'TestHost / App'
  end
end
```

And surprisingly, it works! And now there is no duplication of symbols and pod resources are copied to the test bundle. In addition, we have many pods with tests, and they now have one common app_host. 

Can be viewed at https://github.com/likhogrud/cocoapods-locale-dependent-tests

PS:

Of course, there is a solution through post_install - override `Native Development Region` in info_plist of generated test hosts or make a fake application yourself and put it to test bundles like 

```
if target.name.include?("Unit-Tests") 
   config.build_settings['TEST_HOST'] = '$(BUILT_PRODUCTS_DIR)/TestHost.app/TestHost'
end
```
