### ISSUE TITLE
 Not working with Safari extension when using cocoaPods.

### ISSUE THREAD

**Issue by MrChens** [CocoaPods/CocoaPods#8523]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
## What did you do?
1. `pod init`
2. `pod install`
3. open test.xcworkspace
4. command + R

## What did you expect to happen?
`test Extension` show in Safari->Preferences->Extensions

## What happened instead?
`test Extension` not show in Safari->Preferences->Extensions

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.3_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 091e14ce340a3319ea4d52f550f2fd151c353360
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test

  target 'testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'test Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test Extension

end
```

## Project that demonstrates the issue
1. Xcode->File->New->Project...->macOS->Safari Extension App(test.xcodeproj)
2. command + R 
3. that work fine, `test Extension` show in Safari->Preferences->Extensions
4. `pod init`
5. `pod install`
6. open test.xcworkspace
7. command + R
8. that is bad, `test Extension` not show in Safari->Preferences->Extensions

**Comment by dnkoutso** [comment]
Safari extensions are not supported.
