### ISSUE TITLE
Can't search

### ISSUE THREAD

**Issue by yuyedaidao** [CocoaPods/CocoaPods#8530]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.### Command

```
/usr/local/lib/ruby/gems/2.6.0/bin/pod search XTCkey
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.2
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /usr/local/Cellar/ruby/2.6.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fc85c41eedb8336cac82b9de5f2c2f26e53997aa
               oschina-padding-yqpods - https://git.oschina.net/padding/YQPods.git @ dfe944cc5ffb29cf7552f6ccd3c034194cf67621
               YQPods - https://gitee.com/padding/YQPods.git @ dfe944cc5ffb29cf7552f6ccd3c034194cf67621
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Error

```
JSON::ParserError - 767: unexpected token at 'torShared"],"components.":["iOSEditorShared"],"This":["iOSEditorShared"],"first":["iOSEditorShared"],"step":["iOSEditorShared"],"required":["iOSEditorShared"],"build":["iOSEditorShared"],"WordPress-iOS":["iOSEditorShared"],"with":["iOSEditorShared"],"UI":["iOSEditorShared"],"Aaron":["iOSEditorShared"],"Douglas":["iOSEditorShared"],"astralbodies@gmail.com":["iOSEditorShared"],"diegoreymendez@gmail.com":["iOSEditorShared"],"sergioestevao@gmail.com":["iOSEditorShared"]}}'
/usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.0/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.0/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.0/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
/usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `load'
/usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=767%3A+unexpected+token+at+%27torShared%22%5D%2C%22components.%22%3A%5B%22iOSEditorShared%22%5D%2C%22This%22%3A%5B%22iOSEditorShared%22%5D%2C%22first%22%3A%5B%22iOSEditorShared%22%5D%2C%22step%22%3A%5B%22iOSEditorShared%22%5D%2C%22required%22%3A%5B%22iOSEditorShared%22%5D%2C%22build%22%3A%5B%22iOSEditorShared%22%5D%2C%22WordPress-iOS%22%3A%5B%22iOSEditorShared%22%5D%2C%22with%22%3A%5B%22iOSEditorShared%22%5D%2C%22UI%22%3A%5B%22iOSEditorShared%22%5D%2C%22Aaron%22%3A%5B%22iOSEditorShared%22%5D%2C%22Douglas%22%3A%5B%22iOSEditorShared%22%5D%2C%22astralbodies%40gmail.com%22%3A%5B%22iOSEditorShared%22%5D%2C%22diegoreymendez%40gmail.com%22%3A%5B%22iOSEditorShared%22%5D%2C%22sergioestevao%40gmail.com%22%3A%5B%22iOSEditorShared%22%5D%7D%7D%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Traceback (most recent call last):
	11: from /usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `<main>'
	10: from /usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `load'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.0/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.0/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.6.0/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
	 1: from /usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Cellar/ruby/2.6.0/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at 'torShared"],"components.":["iOSEditorShared"],"This":["iOSEditorShared"],"first":["iOSEditorShared"],"step":["iOSEditorShared"],"required":["iOSEditorShared"],"build":["iOSEditorShared"],"WordPress-iOS":["iOSEditorShared"],"with":["iOSEditorShared"],"UI":["iOSEditorShared"],"Aaron":["iOSEditorShared"],"Douglas":["iOSEditorShared"],"astralbodies@gmail.com":["iOSEditorShared"],"diegoreymendez@gmail.com":["iOSEditorShared"],"sergioestevao@gmail.com":["iOSEditorShared"]}}' (JSON::ParserError)
	12: from /usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `<main>'
	11: from /usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `load'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:67:in `report_error'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.6.0/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:34:in `search'
/usr/local/lib/ruby/gems/2.6.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:95:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)

**Comment by dnkoutso** [comment]
Sorry this report is not complete. Please fill in the template and provide steps or a sample to reproduce the issue.
