### ISSUE TITLE
Sources vendored by plugins not working 

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/CocoaPods#8540]
👋 Aloha!

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  

Upgraded CocoaPods to `1.6.0` from `1.5.3` and run `pod install` on a project using a source vendored by a plug-in (via the [`:source_provider`](https://github.com/CocoaPods/CocoaPods/blob/b918bc0fbcc622401a4c5c8fe298cfd95df1fb7a/lib/cocoapods/installer.rb#L638)).

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen. 

The installation to succeed.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
 
`pod install` fails because CocoaPods is unable to find the source vendored by the plugin.

```
Pod::StandardError - [Bug] Failed to find known source with the URL "protocol://my-source"
/ruby/gems/2.3.0/gems/cocoapods-core-1.6.0/lib/cocoapods-core/source/manager.rb:38:in `aggregate_for_dependency'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:406:in `aggregate_for_dependency'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:392:in `create_set_from_sources'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:361:in `find_cached_set'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:335:in `specifications_for_dependency'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:142:in `search_for'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:251:in `block in sort_dependencies'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:244:in `each'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:244:in `sort_by'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:244:in `sort_dependencies'
/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/resolver.rb:91:in `resolve'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:913:in `block in resolve_dependencies'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/user_interface.rb:64:in `section'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:908:in `resolve_dependencies'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer/analyzer.rb:114:in `analyze'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:266:in `analyze'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/user_interface.rb:64:in `section'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:136:in `install!'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
/ruby/gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
/ruby/gems/2.3.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
project/runtime/ruby2.3.x/gem_bin/pod:22:in `load'
project/runtime/ruby2.3.x/gem_bin/pod:22:in `<main>'
```

After a cursory look it looks like the `plugin_sources` [are not being added to the Configs pluging manager](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer.rb#L176).

**Comment by amorde** [comment]
Hmm, it looks like the analyzer passes the sources to the resolver [here](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer.rb#L937) - that should include the plugin sources theoretically. Will dig into this more when I get the chance 👍

**Comment by fabiopelosin** [comment]
The resolver calls the `aggregate_for_dependency` form the config sources manager which doesn't include the plugin sources:

https://github.com/CocoaPods/CocoaPods/blob/037563cd0818ce6f31f51663dec25ed3201e2cd5/lib/cocoapods/resolver.rb#L394-L397

This in turn [raises](https://github.com/CocoaPods/Core/blob/1.6.0/lib/cocoapods-core/source/manager.rb#L35-L40) because the source_manager doesn't include those sources.

It is unclear to me what is the reason for not adding the `plugin_sources` to the `source_manager`.

**Comment by dnkoutso** [comment]
most likely a regression, would love a fix and a test for it!

**Comment by dnkoutso** [comment]
Is there a quick sample to try this out?

**Comment by antigp** [comment]
cocoapods-art not working with 1.6.0 due to this error

**Comment by dnkoutso** [comment]
Will have to investigate still.

**Comment by dnkoutso** [comment]
What is an easy plugin we can use to repro this? I tried to dig this through and I couldn't immediately find the issue.

@antigp how can I setup cocoapods-art with a public artifactory repo so I can try this out? Do you have a sample app/repo I could use?

**Comment by dnkoutso** [comment]
ping anyone again here perhaps @fabiopelosin @amorde. I will try to take a look again manually and trying to setup my own plugin that adds a source to reproduce.

**Comment by NirPernexus** [comment]
Any progress on this?

**Comment by dnkoutso** [comment]
Nope. I have requested for additional info.

**Comment by dnkoutso** [comment]
Noone has provided a concrete example here for us to reproduce. We wanted to include this in a 1.6.2 release but it is now being pushed to 1.7 and it might not make it there either.
