### ISSUE TITLE
Docs: list all of the platforms

### ISSUE THREAD

**Issue by pepasflo** [CocoaPods/CocoaPods#8541]
On the docs page about platforms: https://guides.cocoapods.org/syntax/podspec.html#platform

It doesn't list what all of the possible platforms are.  For example, what is the keyword for the Apple TV platform?  `:appletv`?  `:tvOS`?  `:tvos`?  You have to dig through podspecs until you find an example.

**Comment by orta** [comment]
Nice idea 👍 

Happy to accept PRs on it

**Comment by dnkoutso** [comment]
Its driven from here https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L566-L586

**Comment by pepasflo** [comment]
thanks @dnkoutso I'll take a look

**Comment by pepasflo** [comment]
PR! https://github.com/CocoaPods/Core/pull/516

**Comment by pepasflo** [comment]
@orta thanks for the poke :)
