### ISSUE TITLE
[STUCK] Can't create a pod shipping MyFramework.framework which has a dependency PodDep

### ISSUE THREAD

**Issue by Daavidaviid** [CocoaPods/CocoaPods#8547]
# Report

## What did you do?

I'm creating a bridge for react-native for an existing framework. On iOS, I'd like to embed this framework, let's call it `MyFramework.framework`, into a pod, let's call it `MyPod`, but this framework has a dependency on another pod let's call it `PodDep`. So I created a pod with the following podspec : 

```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name		= 'MyPod'
  s.summary		= 'React Native Component for bla bla'
  s.version		= '0.0.1'
  s.authors		= { 'XX' => 'xxx@yyy.zz' }
  s.homepage    	= 'https://LINKTOGITHUBPAGE'
  s.license     	= 'MIT'
  s.platform    	= :ios, '8.0'
  s.source      	= { :git => 'https://LINKTOGIT' }
  s.source_files	= 'ios/RCTF/**/*.{h,m}' // <-- I put my sources files in a folder called RCTF

  s.pod_target_xcconfig = {
    'FRAMEWORK_SEARCH_PATHS' => '$(inherited) $(PROJECT_DIR) "$(PODS_ROOT)"/PodDep/**',
    'LIBRARY_SEARCH_PATHS' => '$(inherited) $(PROJECT_DIR) "$(PODS_ROOT)"/PodDep/**',
    'HEADER_SEARCH_PATHS' => '$(inherited) "$(PODS_ROOT)/Headers/Public" "$(PODS_ROOT)"/PodDep/**',
  }

  s.vendored_frameworks = 'ios/MyFramework.framework'
  s.dependency 'React'
  s.dependency 'GoogleSignIn', '~> 4.3.0'
  s.dependency 'PodDep'

end
```

Also I added the PodDep in the Podfile of my app project because PodDep is not registred on CocoaPod register. 

## What did you expect to happen?

I was expecting that everything would work just fine, as the MyFramework.framework is recognized during the building of the app.

## What happened instead?

I get an error all the time during the building. And `Build failed`...
Well in MyFramework.framework there is this file which is `MyFramework-Swift.h` and in there, there is this import : 

```
@import poddep; // <-- Module 'poddep' not found
```

And I've been trying hard to find a solution for that this past week but couldn't find one..
I gotta admit I'm not an expert with cocoapod and xcode, but still...

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4dae83ce0622fddaf42fa253e6d85332ad5cd8d5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Not public yet, unfortunately.

**Comment by dnkoutso** [comment]
Please upload a sample app. I am personally unable to see an issue with the given information.

**Comment by Daavidaviid** [comment]
Ok in the next hour I will link it to a GitHub.
Thanks for your answer.

**Comment by Daavidaviid** [comment]
So here we go :
https://github.com/Daavidaviid/react-native-firekast

The iOS sample app is located in `react-native-firekast/example/`

You'll find a Podfile : `react-native-firekast/example/Podfile`
And a podspec : `react-native-firekast/RNFirekast.podspec`

And currently the app is crashing when we launch it with the following error : 
<img width="375" alt="capture d ecran 2019-02-24 a 19 15 41" src="https://user-images.githubusercontent.com/32457364/53303358-bc193180-3869-11e9-8840-c1f23dd427a4.png">

**Comment by dnkoutso** [comment]
@Daavidaviid 
```npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t https://bitbucket.org/daavidaviid/react-native-firekast-v2.git
npm ERR! 
npm ERR! remote: Invalid username or password
npm ERR! fatal: Authentication failed for 'https://bitbucket.org/daavidaviid/react-native-firekast-v2.git/'
npm ERR! 
npm ERR! exited with error code: 128
```

Trying to work around it.

**Comment by Daavidaviid** [comment]
My bad, that’s my private repo.

**Comment by Daavidaviid** [comment]
It’s should be okay now.
Thanks for the help

**Comment by dnkoutso** [comment]
@Daavidaviid trying again but got same error.

**Comment by Daavidaviid** [comment]
Oh I know, once you pull the latest version with updated podspec, you need
to remove the node_modules folder and the yarn.lock or package-json.lock
and launch the package.json installation once again.


Or more rapidly just copy the content of RNFirekast.podspec from root
folder and put it in the podspec file located in
example/node_modules/react-native-firekast/

**Comment by Daavidaviid** [comment]
Pod is still using the podspec file located in node_modules

**Comment by dnkoutso** [comment]
getting more issues with 
```
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
```
File not found...sorry this is a bit difficult to setup.

**Comment by dnkoutso** [comment]
Still getting
```
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "Refusing to download the git repo {\"hostname\":\"bitbucket.org\",\"protocol\":\"https:\",\"repository\":\"https://bitbucket.org/daavidaviid/react-native-firekast-v2\"} over HTTPS without a commit hash - possible certificate error?".
info If you think this is a bug, please open a bug report with the information provided in "/Users/dimitris/Development/ios/react-native-firekast/example/yarn-error.log".

```

**Comment by Daavidaviid** [comment]
It's okay, react-native is kind of weird when you're not used to.
So basically, what you need to do after a git pull from the repo : https://github.com/Daavidaviid/react-native-firekast

```
cd react-native-firekast/example
```
Install node dependencies : 
```
yarn
OR
npm install
```
Then
```
cd ios
pod install
open Example.xcworkspace
```

And `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec` should be found after as it will be installed as all the dependencies from `example/package.json`

**Comment by dnkoutso** [comment]
@Daavidaviid one more thing your RNFirekast podspec points to ios/Firekast.farmework but https://github.com/Daavidaviid/react-native-firekast/tree/master/ios there is none.

**Comment by dnkoutso** [comment]
@Daavidaviid I am running those command exactly as you say and get:
```
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "Refusing to download the git repo {\"hostname\":\"bitbucket.org\",\"protocol\":\"https:\",\"repository\":\"https://bitbucket.org/daavidaviid/react-native-firekast-v2\"} over HTTPS without a commit hash - possible certificate error?".
info If you think this is a bug, please open a bug report with the information provided in "/Users/dimitris/Development/ios/react-native-firekast/example/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Daavidaviid** [comment]
Oops I precipited myself to make public repo, I should have been more careful.
I updated the `example/package.json` accordingly. 
Now it should be okay.

**Comment by Daavidaviid** [comment]
And also with react-native, you're not supposed to use : 
`use_frameworks!`in the podfile because it's not supported by most of the other pods.

**Comment by dnkoutso** [comment]
@Daavidaviid from the error message where does UriParser.framework come from? It seems whoever built `Firekast.framework` has a reference to it.

**Comment by Daavidaviid** [comment]
I don't know actually

**Comment by dnkoutso** [comment]
That is the issue.

```
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @rpath/UriParser.framework/UriParser (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 1.0.0
compatibility version 1.0.0
```

Your framework is pointing to this but its no where defined in the project for CocoaPods to copy it over.

**Comment by dnkoutso** [comment]
@Daavidaviid I am going to close as I dont think rigth now its a cocoapods issue but I *will* re-open if we continue here and find out its a bug.

**Comment by dnkoutso** [comment]
You might need a podspec that wraps UriParser.framework vendored framework or update the `RNFirekast.podspec` to add the `UriParser.framework` vendored framework.

Use `otool -l Firekast` to analyze the binary of a framework.

**Comment by Daavidaviid** [comment]
Ok I'll dig into this. And I'll keep you updated.
Thanks for the help !

**Comment by Daavidaviid** [comment]
But now that I think about it. I don’t have any issue when I’m directly using that Firekast.framework in an iOS app. How can that be possible ?

**Comment by dnkoutso** [comment]
@Daavidaviid 

Got a pure non-CocoaPods app and linked the binary same error:
```
dyld: Library not loaded: @rpath/UriParser.framework/UriParser
  Referenced from: /Users/dimitris/Library/Developer/CoreSimulator/Devices/DC760E48-0D90-4E6B-ADE1-294D89CE2008/data/Containers/Bundle/Application/DF8B7591-D06D-48F0-BF56-8497E1A71737/testapp.app/Frameworks/Firekast.framework/Firekast
  Reason: image not found
(lldb) 
```

**Comment by Daavidaviid** [comment]
Oh I see, it works but only with use_frameworks! I think
