### ISSUE TITLE
About `s.dependency` Depends on the modified third-party library URL address.

### ISSUE THREAD

**Issue by Jinxiansen** [CocoaPods/CocoaPods#8550]
I used a repository `QBImagePickerController` , but it hasn't been maintained for 3 years. I forked a source and modified it, but it is a dependency of my other third-party repository.

When I write like this:

` s.dependency 'QBImagePickerController', :git => 'https://github.com/laoyuegou/QBImagePicker.git'
`
![111](https://user-images.githubusercontent.com/16829428/53296888-d2b28f00-384f-11e9-9130-f976b1a6e909.png)

The execution failed, prompting:

`[!] Failed to load 'RNImageCropPicker' podspec:
[!] Invalid `RNImageCropPicker.podspec` file: [!] Unsupported version requirements.`

<img width="694" alt="222" src="https://user-images.githubusercontent.com/16829428/53296891-d80fd980-384f-11e9-95f2-0ab015704742.png">

So, how can I configure it? 🤔

Thank you very much! ☕️

> English is not my native language; please excuse typing errors.

**Comment by tripleCC** [comment]
dependency's requirements can't be a git

```ruby
unless version_requirements.all? { |req| req.is_a?(String) }
  version_requirements.each do |requirement|
    if requirement.is_a?(Hash)
      if !requirement[:path].nil?
        raise Informative, 'Podspecs cannot specify the source of dependencies. The `:path` option is not supported.'\
                           ' `:path` can be used in the Podfile instead to override global dependencies.'
      elsif !requirement[:git].nil?
        raise Informative, 'Podspecs cannot specify the source of dependencies. The `:git` option is not supported.'\
                           ' `:git` can be used in the Podfile instead to override global dependencies.'
      end
    end
  end

  raise Informative, "Unsupported version requirements. #{version_requirements.inspect} is not valid."
end
```
you may publish a pre-release version if QBImagePickerController is in development

**Comment by dnkoutso** [comment]
Correct. this is not supported currently and there are no plans to do so. Sorry I am going to close this one.

**Comment by Jinxiansen** [comment]
Ok, I forked the source code of this repository and regenerated a new pod name via `pod trunk push` and other commands: `s.dependency 'QBImagePickerControllerNew'`, this problem is solved.  😬

< English is not my native language; please excuse typing errors.

**Comment by az-oolloow** [comment]
Seems to be a popular problem @dnkoutso , e.g. for this particular pod that @Jinxiansen mentions (QBIMAGEPICKERCONTROLLER) there are 6 different versions of it on cocoapods.org, suggesting this is more frequent than not...

**Comment by muhammadsaddamnur** [comment]
Hi @Jinxiansen,
How to do it? I'm also having the same problem

**Comment by pckz** [comment]
+1
