### ISSUE TITLE
[1.7.0.beta1] bcsymbolmap files get copied into product dir which leads to an invalid archive

### ISSUE THREAD

**Issue by florianbuerger** [CocoaPods/CocoaPods#8552]
When archiving an app that has a framework that included `.bcsymbolmap` files the resulting archive is invalid. It will be shown as a “Generic archive” in Xcode's organizer. 

Seems the issues is caused by https://github.com/CocoaPods/CocoaPods/pull/8470#issuecomment-464347047. I tested it using Xcode 10.1 & the Mapbox SDK but the files ended up the `${TARGET_BUILD_DIR}` and Xcode **did not** copy them to the right destination. This resulted in a “Generic Archive” instead of an app archive because there are files next to the app bundle which isn't allowed. This then fails during export because it doesn't understand the usual export options, for example `-exportMethod: app-store`.

Changing the `embed_frameworks_script.rb` from using 

```shell
local destination="${TARGET_BUILD_DIR}"
``` 

to 

```shell
local destination="${CONFIGURATION_BUILD_DIR}"
``` 

fixes the issue. I am not 100% sure if that issue is only related to Mapbox because have special handling for this https://github.com/mapbox/mapbox-gl-native/pull/12257/.

I am happy to change the embed script and the intergration spec if that is the way to go but I wanted to confirm beforehand.

---

Cocoapods version `1.7.0.beta1`
Xcode `10.1`

**Comment by florianbuerger** [comment]
Okay, this is weird. It works as intended if I change it to `${CONFIGURATION_BUILD_DIR}`. 

Looking at 

```
xcodebuild -workspace Flighty.xcworkspace -scheme 'Flighty Production' -showBuildSettings
```

both variables have the same value.

```
TARGET_BUILD_DIR = /Users/florian/Library/Developer/Xcode/DerivedData/Flighty-dgugoswnzugoyzhkinzovapfmjio/Build/Products/Release-iphoneos
```

```
CONFIGURATION_BUILD_DIR = /Users/florian/Library/Developer/Xcode/DerivedData/Flighty-dgugoswnzugoyzhkinzovapfmjio/Build/Products/Release-iphoneos
```

But running archive with `$TARGET_BUILD_DIR` results in the invalid archive I described earlier, `$CONFIGURATION_BUILD_DIR` works and produces a correct archive which distributed via TestFlight correctly.

**Comment by dnkoutso** [comment]
weird indeed. I am sorry I do not know 100% where those files should end up...:|

**Comment by dnkoutso** [comment]
@florianbuerger if you do it manually without CocoaPods where does Xcode place these files for a pre-built vendored framework?

**Comment by florianbuerger** [comment]
@dnkoutso They aren't handled at all. You have to include them manually. Also, Xcode only generates them when you archive a framework.

I think @dacaiguoguogmail was right in https://github.com/CocoaPods/CocoaPods/pull/8470#issuecomment-464347047 that Xcode handles them automatically when placed in the right place. In the archive, they have to end up in the `BCSymbolMaps` folder.

---

I looked at the values again in Xcode's build log and there they show different values. 

`TARGET_BUILD_DIR`

```
:-1: rsync --delete -av --filter P .*.?????? --filter - CVS/ --filter - .svn/ --filter - .git/ --filter - .hg/ --filter - Headers --filter - PrivateHeaders --filter - Modules /Users/florian/Projects/TestIntegration/Pods/Mapbox-iOS-SDK/dynamic/A6621399-62A0-3DC3-A6E3-B6B51BD287AD.bcsymbolmap /Users/florian/Library/Developer/Xcode/DerivedData/TestIntegration-bcbbgadyfaabukczgxpmxmkjugwe/Build/Intermediates.noindex/ArchiveIntermediates/TestIntegration/InstallationBuildProductsLocation/Applications
```

vs. `CONFIGURATION_BUILD_DIR`

```
:-1: rsync --delete -av --filter P .*.?????? --filter - CVS/ --filter - .svn/ --filter - .git/ --filter - .hg/ --filter - Headers --filter - PrivateHeaders --filter - Modules /Users/florian/Projects/TestIntegration/Pods/Mapbox-iOS-SDK/dynamic/F8207D73-7248-3A6B-8A81-8EE831BAC4E6.bcsymbolmap /Users/florian/Library/Developer/Xcode/DerivedData/TestIntegration-bcbbgadyfaabukczgxpmxmkjugwe/Build/Intermediates.noindex/ArchiveIntermediates/TestIntegration/BuildProductsPath/Release-iphoneos
```

Here the `TARGET_BUILD_DIR` is clearly wrong. I have no idea why the variable is different when printing it using `xcodebuild -showBuildSettings`.

Looking at the build setting reference:

> TARGET_BUILD_DIR
> Identifies the root of the directory hierarchy that contains the product’s files (no intermediate build files). Run Script build phases that operate on product files of the target that defines them should use the value of this build setting, but Run Script build phases that operate on product files of other targets should use BUILT_PRODUCTS_DIR instead.

so it seems the correct variable to use should be `BUILT_PRODUCTS_DIR` which also produces the correct path and therefore a valid archive 🎉 

```
:-1: rsync --delete -av --filter P .*.?????? --filter - CVS/ --filter - .svn/ --filter - .git/ --filter - .hg/ --filter - Headers --filter - PrivateHeaders --filter - Modules /Users/florian/Projects/TestIntegration/Pods/Mapbox-iOS-SDK/dynamic/A6621399-62A0-3DC3-A6E3-B6B51BD287AD.bcsymbolmap /Users/florian/Library/Developer/Xcode/DerivedData/TestIntegration-bcbbgadyfaabukczgxpmxmkjugwe/Build/Intermediates.noindex/ArchiveIntermediates/TestIntegration/BuildProductsPath/Release-iphoneos
```

**Comment by dnkoutso** [comment]
@florianbuerger excellent! Want to make a PR for it?

**Comment by dacaiguoguogmail** [comment]
This is my careless mistake.
`${TARGET_BUILD_DIR}` was wrong.  
In the archive
`${CONFIGURATION_BUILD_DIR}` is equal `${BUILT_PRODUCTS_DIR}`.
The correct variable to use should be `BUILT_PRODUCTS_DIR`.

**Comment by florianbuerger** [comment]
Yes, I am happy to do it later.
