### ISSUE TITLE
"No such module" found from Swift files within sub-groups

### ISSUE THREAD

**Issue by thatjuan** [CocoaPods/CocoaPods#8553]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Podfile includes `pod 'SnapKit'`

1. `rm -rf Pods Podfile.lock`
2. `Deleted DerivedData`
3. `pod install`

From Xcode 10.1, I added 2 groups to the project files. Inside of the inner-most group I added a swift file that defines a ViewController. It imports a framework called SnapKit.

## What did you expect to happen?

I expect the ViewController to be able to import SnapKit and Xcode to autocomplete stuff provided by SnapKit.

## What happened instead?

- Xcode complais about `No such module SnapKit` within the ViewController
- Xcode doesn't autocomplete SnapKit calls
- Project builds and runs on simulator and device normally, and the SnapKit calls work
- *Important detail* if I move the ViewController.swift file to be a sibling of AppDelegate.swift, then Xcode autocompletes SnapKit calls and stops complaining about missing modules.

Xcode is mirroring groups to the filesystem, so the ViewController file is placed inside of the folders. When it's in the folders, it doesn't work.

## CocoaPods Environment

*Please note that I also tried this with 1.6.0 and had exactly the same results*

### Stack

```
   CocoaPods : 1.7.0.beta.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 4thdown-cocoapods-spec - git@code.4thdown.co:clients-mobile/cocoapods-spec.git @ 3593241a90ba5e461837794ec5997c43b36ecab0
               master - https://github.com/CocoaPods/Specs.git @ cdaaee36a6bdea2eafb5e0fb8e2ffdc94225a967
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-bugsnag     : 2.0.1
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

def common_pods
  pod 'SnapKit', '~> 4.2.0'
  pod 'MyToolKit', :path => '../framework/MyToolKit'
end


target 'MyToolIOS' do
  use_frameworks!
  platform :ios, '11.0'

  common_pods

   target 'MyToolTests' do
     inherit! :search_paths
     pod 'MyToolKit', :path => '../framework/MyToolKit'
   end

end

 target 'MyToolMacOS' do
   platform :osx, '10.13'

   common_pods

   target 'MyToolMacOSTests' do
     inherit! :search_paths
     pod 'MyToolKit', :path => '../framework/MyToolKit'
   end

end
```

## Project that demonstrates the issue

I tried reproducing this in a fresh Xcode project, and although initially it would behave the same way with subdirectories, after a few seconds it'll start autocompleting properly.

Is there anything I'm missing that's causing frameworks to not be seen by Xcode while developing?

**Comment by dnkoutso** [comment]
I do not have a good idea on why this would happen, perhaps due to implicit linking? I am keeping this open for anyone who can help diagnose it.

**Comment by thatjuan** [comment]
The only solution was to create a new project and just keep iOS and MacOS in separate targets. Not sure if this is or isn't cocoapods-specific.

**Comment by thatjuan** [comment]
In case someone ends up landing here looking for solutions, I ended up finding that autocomplete only stops working on sources that have a *UITest in its target memberships.

If I just leave the main project in the memberships, everything works well.

I am not sure whether this is cocoapods-specific, or an Xcode bug.
