### ISSUE TITLE
Create device-only pod for Metal.framework used.

### ISSUE THREAD

**Issue by evanxlh** [CocoaPods/CocoaPods#8560]
Dear CococPods, I'm sorry to open an issue here. 

**My Problems**

- Using pod lib lint, it reports error because Metal.framework can not compile on simulator, so I have to use below macro to check:

`#if (arch(arm) || arch(arm64)) && os(iOS)`

- metal_stdlib not found.

- no rule to process file '.metal' of type 'sourcecode.metal' for architecture 'x86_64' (in target 'DeviceOnlyMetalPod')

**My Purpose**

- Let my pod lib runs only on the device, how to ignore compile on the simulator when runing pod lib lint

- Push the podspec to private repository.

Any solutions, hopely someone can help me, if you also encountered this issue.

Example code repo: https://github.com/MrEndlesswhy/DeviceOnlyMetalPod

**Comment by dnkoutso** [comment]
I dont think lint supports for device only frameworks now, perhaps you can ship a stub framework?

**Comment by MrEndlesswhy** [comment]
@dnkoutso Thanks for your reply, I'm sorry I don't know what's a stub framework, can you show me some guides?

**Comment by dnkoutso** [comment]
Just include a framework that acts as a stub that is not for devices. At this current time this is not supported I don't think.
