### ISSUE TITLE
Build failed "directory not found for option"

### ISSUE THREAD

**Issue by Cypaubr** [CocoaPods/CocoaPods#8562]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`
In XCode, Build

## What did you expect to happen?

Build successfully with the pods.

## What happened instead?

Build failed with an error:
```
ld: warning: directory not found for option '-F/Users/cyprien/Library/Developer/Xcode/DerivedData/Cityfid-hhdmvkqkrceixqdstpuwufyndpxb/Build/Products/Debug-iphonesimulator/Realm'
ld: warning: directory not found for option '-F/Users/cyprien/Library/Developer/Xcode/DerivedData/Cityfid-hhdmvkqkrceixqdstpuwufyndpxb/Build/Products/Debug-iphonesimulator/RealmSwift'
ld: warning: directory not found for option '-F/Users/cyprien/Library/Developer/Xcode/DerivedData/Cityfid-hhdmvkqkrceixqdstpuwufyndpxb/Build/Products/Debug-iphonesimulator/Realm'
ld: warning: directory not found for option '-F/Users/cyprien/Library/Developer/Xcode/DerivedData/Cityfid-hhdmvkqkrceixqdstpuwufyndpxb/Build/Products/Debug-iphonesimulator/RealmSwift'
ld: framework not found Realm
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Stack

```
   CocoaPods : 1.7.0.beta.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f8a8d67b192abc66512aae2ed18ea610590a8d2a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cityfid' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cityfid
  pod 'RealmSwift'
end
```

**Comment by dnkoutso** [comment]
Please upload sample app.

**Comment by Cypaubr** [comment]
Here is the project: [https://github.com/Cypaubr/CityfidiOS](https://github.com/Cypaubr/CityfidiOS)

**Comment by dnkoutso** [comment]
![screen shot 2019-02-26 at 11 08 26 am](https://user-images.githubusercontent.com/310370/53439449-e593a380-39b6-11e9-88eb-95992154ec3e.png)


Build works for me for your project.

Currently this does not appear a CocoaPods library issue bug. It is best to ask StackOverflow under `cocoapods` tag for support on build errors or project configuration.

Closing for now but *I will* re-open if we can show this is a CocoaPods integration issue which so far does not appear to be.

**Comment by rjriel** [comment]
Commenting on this because I had the same issue and solved my problem. No need to re-open, this is just informational.

The issue I had is that I was opening the xcodeproj file in xcode instead of the xcworkspace file. Opening the xcworkspace file with XCode solved my problem.
