### ISSUE TITLE
Ho can I include another framework as dependency?

### ISSUE THREAD

**Issue by wellbranding** [CocoaPods/CocoaPods#8564]
Hello, when will cocoa pods enable to add additional frameworks( dynamic frameworks) inside of new framework which will be distributed as Pod? Right now I have not found any way of building a framework which would include additional dynamic frameworks ( not from cocoa pods, but local dynamic frameworks which are private)

. It would really improve our framework quality and will help to ship our framework as a standalone project without building an Umbrella framework.

It would benefit other developers. Please provide concrete estimations if it even is possible or should we switch to Carthage?

**Comment by dnkoutso** [comment]
You can easily zip those frameworks and manually include `s.pod_target_xcconfig` with `-framework` flags for "private" frameworks.

I believe it can be done using current DSL...not super pretty but there are no plans to support something like this now as it requires more proper design process.

**Comment by wellbranding** [comment]
Wow really thanks for quick support! You mean I should create a folder and add our framework and also third party framework in the same folder. Zip all that put it in S3( as I have did it with my other projects) and then you could refer : s.vendored_framework "folder/third-party.framework". Am I correct? Also about s.pod_target_xconfig . I might actually don't need it , that third party framework could be visible by our clients..I was not very clear.

**Comment by dnkoutso** [comment]
sure that would work I think and if I understand 100% what are you trying to do.

**Comment by wellbranding** [comment]
Ok, just to be clear I will explain myself. Basically I have framework which imports other dynamic frameworks, which are local files. I add import third-party inside of my project classes and also specify in particular Framework to **Link Binary with Libraries** with third -party frameworks. 

Then I generate fat frameworks for each third party framework and also for our framework, put everything in the S3 and  in Podspec and publish our Pod? I will commit following days to verifying if it is working, just wanted to ask, before wasting days for our team and maybe found some possible bugs down the road.
