### ISSUE TITLE
Copy Pods Resource Error，Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by yongboQu** [CocoaPods/CocoaPods#8567]
cocoapods (1.5.3)
ruby 2.3.7

flutter_assets/packages/xxx/images/multi_like_2.png
flutter_assets/packages/xxx/images/multi_like_3.png
flutter_assets/packages/xxx/images/multi_like_4.png
flutter_assets/packages/xxx/images/multi_like_5.png
flutter_assets/packages/xxx/images/multi_like_6.png
flutter_assets/packages/xxx/images/multi_like_7.png
flutter_assets/packages/xxx/images/multi_like_8.png

sent 42086565 bytes  received 14872 bytes  28067624.67 bytes/sec
total size is 42033538  speedup is 1.00
Command /bin/sh failed with exit code 1

**Comment by dnkoutso** [comment]
Sorry this is not a sufficient report.

**Comment by yongboQu** [comment]
I am wondering why error shows less useful message
