### ISSUE TITLE
Is there any way to delete a public podspec?

### ISSUE THREAD

**Issue by MrEndlesswhy** [CocoaPods/CocoaPods#8568]
I deleted the git repository of a public podspec, is there any way to delete this public podspec from CocoaPods repository?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

That said, check out https://guides.cocoapods.org/terminal/commands.html#pod_trunk_delete

**Comment by MrEndlesswhy** [comment]
@orta Thank you very much. I'm sorry to ask question here.
