### ISSUE TITLE
Unexpected warning with `pod lib lint`

### ISSUE THREAD

**Issue by funitron** [CocoaPods/CocoaPods#8570]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Create a simple pod library
2. run `pod lib lint`

## What did you expect to happen?

Expectation is that no warnings are created for the `App` project generated by pods since this is outside of the user's control.

## What happened instead?

Received the following warning using both stable (`cocoapods-1.6.1`) and pre-release (`cocoapods-1.7.0.beta.1`):

```
NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
```

Examining the app generated by pods for linting (using the `--no-clean` option) there is no `Info.plist` specified under the `App` target, and none to be found on the filesystem.

![screen shot 2019-02-28 at 3 18 06 pm](https://user-images.githubusercontent.com/18307574/53595816-3dbfd680-3b6c-11e9-8703-6a0eddc7c8b4.png)

Manually adding an `Info.plist` and then re-running the `xcodebuild` command used by `pod` results in no warning. The command used by pods is:

```
/usr/bin/xcodebuild clean build -workspace /var/folders/lz/prdncsvd1hn9g0lfc_r936lhgyv1pn/T/CocoaPods-Lint-20190228-65191-a9ba57-<project name>/App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=76CC9A77-B08E-4B22-8B99-AC49C0EAE4EA
```

### Stack

```
   CocoaPods : 1.7.0.beta.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.21.0
Ruby lib dir : /Users/<userid>/.rvm/rubies/ruby-2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 00183fc508a5752a273f525539da577320d4a308
```

### Installation Source

```
Executable Path: /Users/<userid>/.rvm/gems/ruby-2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Is this blocking a release or anything for you? I see its being treated as a `NOTE`

What exactly is the issue?

**Comment by funitron** [comment]
Not a blocking issue, just not expecting any warnings to be generated by the tool itself.

**Comment by dnkoutso** [comment]
👍 will mark it as an easy task to fix.

**Comment by funitron** [comment]
cool, and thanks 👍

**Comment by Misantrofia** [comment]
Are there any plans to fix this ? My use case it to setup a Jenkins job for a library with pod lib lint without setting the flag "allow_warnings" to fail the build for any contributor that is introducing warning in the code. I inspected the the generated files after running pod lib lint --no_clean and if I add a plist file to that project the warning goes away.
I can do a Pull Request with a fix if I get some guidance on how to fix this issue.
