### ISSUE TITLE
Should copy pod resources into the static framework?

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8573]
I have a static framework target in my project, and the CocoaPods will copy the all resources from the Pods. Is it right?

After build the static framework, the static framework will contains all resources, and others use my framework by the CocoaPods, they will copy the all resources from my framework and other pods.

By the way, if my framework is a dynamic framework, it still need  copy the resources from pods, is it right?

**Comment by Whirlwind** [comment]
I check the code in `target_intergrator.rb`:

```
          native_targets.each do |native_target|
            # Static library targets cannot include resources. Skip this phase from being added instead.
            next if native_target.symbol_type == :static_library
            TargetIntegrator.create_or_update_copy_resources_script_phase_to_target(native_target, script_path, input_paths, output_paths)
          end
```

if the user target is a static library, CP will not copy pod resources. But if the user target is a framework ( include static and dynamic), CP will copy all resources.

**Comment by dnkoutso** [comment]
yes it should afaik. Its a framework which can contain resources.

**Comment by Whirlwind** [comment]
I think the dynamic framework should contain resources, and the static framework should not contain resources. Because the resources in the static framework should be copied into the main bundle, and the dynamic framework will keep the resources in the framework/Resources. They are different.

**Comment by dnkoutso** [comment]
There is no current plan to change this now.

> Because the resources in the static framework should be copied into the main bundle

Why would this need to happen? Care to elaborate more?

**Comment by leavez** [comment]
Hi @dnkoutso , is there some related changes in cocoapods 1.7? 

I found that, when building a pod with 'static_framework = true' and with cocoapods 1.6, it will generate a framework containing the resource files in framework bundle. But when use cocoapods 1.7, no resources will copied to the framework bundle. Is this an intentional change or bug?
