### ISSUE TITLE
`sudo gem install cocoapods` error with `write permission`? Should update guide? 

### ISSUE THREAD

**Issue by shengyang998** [CocoaPods/CocoaPods#8574]
[ * ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `sudo gem install cocoapods`

## What did you expect to happen?

install cocoapods on my systems (macOS Mojave)

## What happened instead?

failed with error: 
```shell
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.
```

## How to resolve

Just use command `sudo gem install cocoapods -n /usr/local/bin` instead.
The reason is Apple protect `/usr/bin` from others - even from root users - editing. 
The doc is somehow misleading since the apple changed its privacy policy.

**Comment by dnkoutso** [comment]
Works for me on Mojave I just tried it.

**Comment by shengyang998** [comment]
That's is strange, I must add -n /usr/local/bin so that it will work on `macOS Mojave 10.14.3 (18D109) `

**Comment by dnkoutso** [comment]
Same version here as well.

**Comment by shengyang998** [comment]
Is the SIP enable on your system? 
Just run `csrutil status`. 
I've got it enable. Maybe that is the reason.

**Comment by shengyang998** [comment]
I tested a brand new installing of CocoaPods on another MacBook (with SIP enable). 
It does install successfully without `-n /usr/local/bin`. 
Maybe I messed up with the permission of some folder. 
Since it seems not a common problem, I'm closing this issue.

**Comment by yossi102** [comment]
thanks
working with Catlina too

**Comment by gbhaumikkumar14** [comment]
Not working on BigSur and Monterey

**Comment by TheBuzzer67** [comment]
Doesn't work on Monterey 12.6!

I've tried all suggestions here!?
