### ISSUE TITLE
When using incremental installs, not all targets get generated

### ISSUE THREAD

**Issue by igor-makarov** [CocoaPods/CocoaPods#8577]
I've encountered an issue while using the experimental Incremental Install feature in CP 1.7.0.
The issue occurs when using a pod that results in more target.  
When one of the targets needs generation, and incremental install is enabled, only the modified target gets generated.

I've made a demo project that reproduces the issue: [link](https://github.com/igor-makarov/DemoCPIncrementalBug)

I'm attaching the excerpt from the Podfile from the project here:
```ruby
abstract_target 'All' do
  pod 'BlocksKit/Core'
  target 'App' do
    pod 'BlocksKit'
    pod 'DevPod/App', path: './DevPod/'
  end
  target 'Widget' do
    pod 'DevPod/Widget', path: './DevPod/'
  end
end
```

Adding a file to the subspec `DevPod/Widget` causes a regeneration of the relevant target. However, the sibling target `DevPod/App` gets missed.

I've already got PR #8572 that fixes the problem, however I don't have an idea of how to write the tests for it. @sebastianv1 thanks for volunteering to help!

**Comment by dnkoutso** [comment]
And https://github.com/CocoaPods/CocoaPods/pull/8582
