### ISSUE TITLE
[Feature] Opt-out of linting for private specs

### ISSUE THREAD

**Issue by richardtop** [CocoaPods/CocoaPods#8580]
I'd like to have an option to disable linting and validation when pushing to private Specs.
Numerous issues had been already created, showing demand for this feature.

Linting should have an option of opting out since the person issuing the command knows why he/she is doing it and the result doesn't affect the CocoaPods master repo in any way.

**Comment by dnkoutso** [comment]
You already have that option. You can just commit the podspec directly to your private repo. Its just a git repo.

@richardtop going to close this preemptively but we can keep talking about it maybe we can make it enhancement.

**Comment by richardtop** [comment]
It’s just much easier to use command line tool, especially if it has to be included as a part of a CI workflow.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dnkoutso** [comment]
We cannot offer this option as the moment we do those commands are used for publishing to a master repo. It would be rather unnecessary to add a flag and filter it based on the repo you are publishing.

**Comment by paulb777** [comment]
The git command line tools can do everything needed.

**Comment by richardtop** [comment]
@paulb777 sure I could do it even with a hammer, but what about convenience?
