### ISSUE TITLE
How to build facebook/flipper on 1.6.0+?

### ISSUE THREAD

**Issue by DDDrop** [CocoaPods/CocoaPods#8587]
In `1.6.0+` `host_requires_frameworks` was changed to be *readonly*.

Is there any way to make the code below work?
> facebook/flipper
```
  # If you use `use_frameworks!` in your Podfile, 
  # uncomment the below $static_framework array and also 
  # the pre_install section.  This will cause Flipper and 
  # it's dependencies to be static and all other pods to 
  # be dynamic.

  # $static_framework = ['FlipperKit', 'Flipper', 'Folly',
  #   'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion', 
  #   'glog', 'PeerTalk', 'RSocket', 'Yoga', 'YogaKit', 
  #   'CocoaLibEvent', 'OpenSSL-Static', 'boost-for-react-native']
  
  # pre_install do |installer|
  #     installer.pod_targets.each do |pod|
  #       if $static_framework.include?(pod.name)  
  #         pod.host_requires_frameworks = false
  #       end
  #   end
  # end
```

There is a discuss about this > [LINK](https://github.com/facebook/flipper/issues/254)

**Comment by dnkoutso** [comment]
This was never public API. The fact that it was working before is not something we can guarantee.

You can still perform the hack by calling `send`.

See something like https://stackoverflow.com/questions/7849521/set-attribute-dynamically-of-ruby-object

Sorry going to close as we _want_ things to become more and more immutable in the codebase.
