### ISSUE TITLE
#if canImport() not working with Subspec

### ISSUE THREAD

**Issue by wellbranding** [CocoaPods/CocoaPods#8594]
Hello, we have created a framework which has several extensions( subspecs). We are distributing our framework as a lite Pod without additional subspecs..

&#x200B;
However even though our subspecs have been configured correctly and client integrates them separately, but our framework **crashes if client integrates a lite version without any additional modules.**.. Error says that our framework cannot reference another framework from  subspecs in code...

I do reference code from subspecs, but only between **#if canImport(optional framework)**. Why then our framework crashes ?

**Reason: image not found**

&#x200B;

**Our subspec:**

    s.default_subspec = 'defaultSDK'
    
    s.subspec 'defaultSDK' do |default|
    default.vendored_frameworks = 'Default.framework'
    end
    
    s.subspec 'firstSubspec' do |first|
    //accesses separate framework 
    first.dependency   = 'First'
    end

then in our default framework, we call:

    #if canImport(First)
    import First
    #endif

**In our defaultSDK Podfile we include firstSubspec framework, because it is also is accessible as separate framework**

    pod 'First'

And use same logic to call any methods from First.framework.

What is wrong with our structure?

**Comment by segiddins** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by wellbranding** [comment]
I have asked, no help. Actually I see that community is not that great as it was. Difficult problems are not getting answered. This is why I need support from actual maintainers.

**Comment by dnkoutso** [comment]
@wellbranding would love a sample app here demonstrating the issue. It makes debugging much easier and faster.

**Comment by wellbranding** [comment]
Ok, I could create it. Should I create a repository and provide link ? :) It is indeed interesting problem to work with and really useful.

**Comment by dnkoutso** [comment]
A repository should be fine yes instead of a one-off zip file.

**Comment by dnkoutso** [comment]
To be precise this might not be a bug or might end up being an improvement thats not worth supporting.

**Comment by wellbranding** [comment]
@dnkoutso I am sorry it won't go smoothly with repository.. Basically, you still need a token to access our framework(it is verification framework). We will however, share our podspec and it should be clear:

    `s.default_subspec = 'mainSDK'
    
    s.subspec 'mainSDK' do |mainSDK|
    mainSDK.vendored_frameworks = 'mainSDK.framework''
    mainSDK.source_files = "mainSDK.framework/Headers/*.h"
    end
    
    s.subspec 'additionalSDK' do |additionalSDK|
    additionalSDK.source_files = "additionalSDK.framework/Headers/*.h"
    additionalSDK.vendored_frameworks =['additionalSDK.framework', 'mainSDK.framework'
    end

Now, in our mainSDK we include additionalSDK with **#if canImport(additionalSDK)**

&#x200B;

However, after including additionalSDK, our  **#if canImport(additionalSDK)** always returns **false...** 

&#x200B;

**Comment by wellbranding** [comment]
@dnkoutso Hello, after lots of hard work we have changed our setup. Right now our main framework has added two optional dependencies and we **mark them as optional, instead of required**. 
Also we add -weak_framework 'otherSDK' in **other linker flags.** 
Right now our subspec which includes all frameworks works well! However, our light version which does not include 2 optional dependencies in podspec, provides Xcode error: "**Missing required modules:**

Why it says that it is **missing required modules**, if they are marked as optional and have weak_framework tag?

 I think that including our SDK by yourself would be **easier for you.**

 Here: add pod 'iDenfySDK' and it will include our SDK and will create an error 
Our pod:

**Comment by wellbranding** [comment]
@dnkoutso this issue still continues in production.. What can we do about this?
