### ISSUE TITLE
Questions about the roadmap for acknowledgements generation

### ISSUE THREAD

**Issue by winkelsdorf** [CocoaPods/CocoaPods#8596]
Referencing #6056 and https://github.com/CocoaPods/cocoapods-acknowledgements/issues/37.

Years later still a valid point. There is different functionality in cocoapods` core acknowledgement generation compared to the plugin. Each has functionality the other is missing. 

Each time I stumble upon this I'm wondering where to create PRs. **So, what's the plan with this for the future?**

If I may suggest, either
1) get all related functionality out of cocoapods itself, probably make cocoapods-acknowledgments a required dependency later or 
2) merge the small plugin back in..

### Examples of current differences in **acknowledgements generation**:

- cocoapods integrates better into settings.bundle out of the box (speaking of the filenames)
- cocoapods creates markdown files
- cocoapods-acknowledgement creates a custom plist with more details (`specs`) on license, homepage etc. which is parseable 
- cocoapods-acknowledgement allows excluding custom pods

Instead of creating a PR for the plugin which duplicates current cocoapods markdown _generation_ functionality 1:1, probably easier to merge it's functionality back in and extend cocoapods native generation with:

- parsable plist generation a.k.a. `Full Podspec metadata plist` (this should be fairly easy)
- allow excluding pods from acknowledgement in `Podfile` with an option like
`pod 'myPod', :exclude_acknowledgements => true`

Opinions?

**Comment by orta** [comment]
I don't really have a strong opinion on the matter. I'd lightly prefer that it lives in the plugin so that CocoaPods itself can stay focused on dependency management etc, and can live outside of the release cycle.

**Comment by winkelsdorf** [comment]
Yea, I like the idea of modularized functionality, too. But speaking of the other repos activity looks like it's not worth all the efforts over there.

For me making two adjustments to CocoaPods itself looks easier.

I would propose:

- adding Full Podspec as generator, comparable to existing  https://github.com/CocoaPods/CocoaPods/blob/1-7-stable/spec/unit/generator/acknowledgements/plist_spec.rb.

- introduce option like `:exclude_acknowledgements => true` to exclude pods from acknowledgements (though it needs smaller changes in the current generator logic).

So speaking of about ~ 100-150 LoC being added here.

The convenience copying to `settings.bundle` the plugin does can be omitted. It's easily doable using the `post_install` hook (or with a build phase in Xcode).
