### ISSUE TITLE
Sharing CocoaPod using UIApplication.shared between iOS Extension and app

### ISSUE THREAD

**Issue by fishcharlie** [CocoaPods/CocoaPods#8597]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# General

_I'm including this general section to give more context to the issue. You can find the rest of the issue template below that I have attempted to fill out to the best of my ability._

I have a custom built private CocoaPod that I wrote. I'm trying to use it in my iOS application, which is working fine. But when I add it to my iMessage App or Share Extension it fails and gives me an error `'shared' is unavailable: Use view controller based solutions where appropriate instead.` when trying to use `UIApplication.shared`.

My first thought of how to fix this was to add a Swift Flag `IN_EXTENSION` or something like that. Then wrap the code in an `#if` block.

Problem is the target for the CocoaPod source is in some type of framework. The source is not part of the app or extensions directly. So adding that flag doesn't really help.

Below is an example of my Podfile.

```
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:CUSTOMORG/Private-CocoaPods-Spec.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
 
target 'MyApp' do
  pod 'MyCustomSwiftPackage', '1.0.0'
end

target 'MyApp Share Extension' do
  pod 'MyCustomSwiftPackage', '1.0.0'
end
```

If I comment out the line `pod 'MyCustomSwiftPackage', '1.0.0'` under `MyApp Share Extension` it works fine. But if I leave it uncommented it fails.

I do need this package in my share extension tho.

I've thought about writing a separate pod that just handles the `UIApplication.shared` logic and adding that pod to the `MyApp`. But that seems like a real pain. Especially since I'm not aware of a way to deploy 2 CocoaPods in 1 project that rely on the same source files.

If that is the only solution it almost seems better to use Git Submodules and have the source directly in the app, so I can have it part of those targets directly and the `#if` SHOULD work then. Problem with that is the dependancies of the CocoaPod wouldn't be handled if I use Git Submodules. So I really have to use CocoaPods somehow.

I'd prefer a simple solution that doesn't feel as hacky as those ones. So is there a better way to handle this and fix that error without resorting to rewriting a TON of code, and that isn't a super hacky solution? 

I have seen mentions to use `NSSelectorFromString` with `UIApplication.responds` and `UIApplication.perform`. Problem with that is if Apple ever changes the API, the code will break, even for previous versions of the application since it is being called dynamically with no API future proofing. Although that solution sounds easy, it seems like a really bad decision. I have also seen solutions to set `Require Only App-Extension-Safe API` to true. But I've heard that doesn't make it through App Review.

I've also tried to add the following to my PodSpec:

```
  s.default_subspec = 'Core'
  s.subspec 'Core' do |core|
    core.source_files = 'MyPackage/Classes/**/*'
    core.resources = 'MyPackage/Assets/**/*.{ttf,xcassets}'
  end
  s.subspec 'AppExtension' do |ext|
    ext.source_files = 'MyPackage/Classes/**/*'
    ext.resources = 'MyPackage/Assets/**/*.{ttf,xcassets}'
    # For app extensions, disabling code paths using unavailable API
    ext.pod_target_xcconfig = { 'OTHER_SWIFT_FLAGS' => '-DIN_EXTENSION' }
  end
```

And the Podfile:

```
target 'MyApp' do
  pod 'MyPackage/Core', '1.0.0'
end

target 'MyApp Share Extension' do
  pod 'MyPackage/AppExtension', '1.0.0'
end
```

Problem with that is that is that when running the app it looks like `MyApp` is using the code for `IN_EXTENSION`. When I look in the Pods project, it looks like `MyApp` has both `MyPackage/Core` and `MyPackage/AppExtension` and so it seems like `MyPackage/AppExtension` and therefor `IN_EXTENSION` is taking priority.

I feel like I'm close with that solution, but I'm unsure how to get it to work the way I want.

https://stackoverflow.com/q/54773509/894067

---
# Report

## What did you do?

Built a private CocoaPod, installed it into an iOS application and iOS app extension.

## What did you expect to happen?

No compile errors, and the code to execute as expected.

## What happened instead?

Either I get compile errors, or the code doesn't execute as expected. It uses the `IN_EXTENSION` in the main application.

### Stack

```
   CocoaPods : 1.6.0.rc.2
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin16]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/charliefish/.rbenv/versions/2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 190a2b4aa4514624d33046ea166b5042246d69e6
               rrainnCocoaPodsSpec - git@github.com:rrainn/CocoaPods-Spec.git @ e26eab8bd9c2438ab4bf4c8b623a657639111a7b
```

### Installation Source

```
Executable Path: /Users/charliefish/.rbenv/versions/2.2.5/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by 0xpulsar** [comment]
Even I have this issue

**Comment by ssnvgirish** [comment]
def resusedPOD
    pod 'pod1Sample'
end

target 'Framework' do
    resusedPOD
end

target 'myProject' do
    resusedPOD
    // Some other pods
end

target 'ExtensionProject' do
    resusedPOD
end
