### ISSUE TITLE
Customizing name of installed pod

### ISSUE THREAD

**Issue by LinusU** [CocoaPods/CocoaPods#8600]
🌈

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have an existing project, [`JSBridge`](https://github.com/LinusU/JSBridge), which was consumed thru Carthage or SwiftPM. Today I added support for CocoaPods as well since to make it easier for users using CocoaPods.

Since the name `JSBridge` was already taken on CocoaPods, I simply published it as `LinusU_JSBridge`.

The problem now is that I have another project, [`Marionette`](https://github.com/LinusU/Marionette), which depends on `JSBridge`. This is the library that I actually wanted to consume from CocoaPods right now. When adding a pod-spec to this repo I'm running into an issue though.

Since I had named the first pod `LinusU_JSBridge`, I have to import it in the Swift code as `LinusU_JSBridge` instead of just `JSBridge`.

**Is there any way that I can customize the name of the installed library, so that I can import it as `JSBridge`?**

The problem with just changing the code is that then it's not compatible with Carthage or SwiftPM anymore, and making it work with both would be quite ugly. It would also be a better user experience if the library is always imported as `JSBridge` regarding of how it was installed.

## What did you expect to happen?

I actually expected `import JSBridge` to work, but that might have been naive 😄.

## What happened instead?

```
- ERROR | [iOS] xcodebuild:  Sources/Marionette.swift:2:8: error: no such module 'JSBridge'
```

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a3331796863b7c7e96eea4b3a0729fdcd42ba33a
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[`JSBridge`](https://github.com/LinusU/JSBridge) together with [`Marionette`](https://github.com/LinusU/Marionette)

*(@ArthurChi I see that you currently have the `JSBridge` name, but haven't updated it since 2016. If you are no longer using the name, would you consider giving it to my project? I would really much appreciate it ❤️)*

**Comment by dnkoutso** [comment]
I dont think this is possible as a "first" class API or so. You can maybe try `s.pod_target_xcconfig` and change the `MODULE_NAME` build setting?

**Comment by dnkoutso** [comment]
but you would still run at a risk that you will clash with the other pod published.

**Comment by LinusU** [comment]
> change the MODULE_NAME build setting?

Thanks! I'll try this out right away

> but you would still run at a risk that you will clash with the other pod published.

It doesn't seem that widely used, so I don't think anyone is going to use both ☺️

**Comment by LinusU** [comment]
🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 

This is actually supported through an official API, and documented:

> ### `module_name`
> 
> The name to use for the framework / clang module which will be generated for this specification instead of the default (header_dir if set, otherwise the specification name).

https://guides.cocoapods.org/syntax/podspec.html#module_name 

I can also confirm that it does indeed work, sorry for the false report!

**Comment by dnkoutso** [comment]
ha lol and I forgot about it as well.
