### ISSUE TITLE
File patterns did not match any file when spec lint

### ISSUE THREAD

**Issue by GTMYang** [CocoaPods/CocoaPods#8606]
We tried "pod spec lint" for a .podspec from "https://github.com/GTMYang/GTMBarcodeScanner.git"

**Comment by GTMYang** [comment]
[!] The spec did not pass validation
- ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `resources` pattern did not match any file.

**Comment by dnkoutso** [comment]
Hey this is a great example of a question to ask in StackOverflow under `cocoapods` tag. 

Remember `pod spec lint` will clone the repo at the version/tag you specify so maybe you need to update your git tag pointer.
