### ISSUE TITLE
Build fails if resource folder contains the word "resources"

### ISSUE THREAD

**Issue by richardtop** [CocoaPods/CocoaPods#8611]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Created `.podspec` with assets. One of the folders is named `resources`.

## What did you expect to happen?
When I press "Run" in Xcode, I expect project to compile.

## What happened instead?
Build fails

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : gitlab-ios_protobuf_runtime - git@gitlab.local:software/ios_protobuf_runtime.git @ 9d4bcb70122e1c14dbc66a060dc7f6a284c6d22e
               master - https://github.com/CocoaPods/Specs.git @ 033fcf45fc7b4489ccf7f95ce24d35b0fc4826bb
               PrivateSpecs - XXXXXXXXXXXXXXXXXX
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## "Solution"

Renaming the `resources` folder solves the issue, e.g.:
`"resources" -> "teamcookresources"`

**Comment by dnkoutso** [comment]
Probably a legitimate bug.

**Comment by segiddins** [comment]
Can you try with the latest beta release? I seem to recall us fixing something similar.
