### ISSUE TITLE
Can I grouped my pods projects?

### ISSUE THREAD

**Issue by alexlee002** [CocoaPods/CocoaPods#8613]
* [√ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
1. CocoaPods 1.7.0.beta.2 installed. 
1. There are so many pods in my APP. some are the 3rd frameworks, some are the submodules of my app.

## What did you expect to happen?

I hope cocoapods can support a feature to group my pods, to make it more clear to organize the pods.

## What happened instead?

The pods projects are not in order or can be grouped.

**Comment by dnkoutso** [comment]
Not currently and there is no option to support this.
