### ISSUE TITLE
Pod install failed when changed(deleted) one subspec of pod lib in podfile.

### ISSUE THREAD

**Issue by Crazzzzyy** [CocoaPods/CocoaPods#8615]
* [√] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. delete one spec of pod lib, like this:
  Before: pod 'libA', :subspecs => ['subspec1', 'subspec2']
  After: pod 'libA', :subspecs => ['subspec1']
2. Run 'pod install'

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

[!] Error installing libA
[!] /usr/bin/git clone xx.git /var/folders/m0/z18l023d0pv0hp8pwx6bhl_m0000gn/T/d20190317-56206-pn9pwx --template= --single-branch --depth 1 --branch 4.0.6

Cloning into '/var/folders/m0/z18l023d0pv0hp8pwx6bhl_m0000gn/T/d20190317-56206-pn9pwx'...
warning: Could not find remote branch 4.0.6 to clone.
fatal: Remote branch 4.0.6 not found in upstream origin
fatal: The remote end hung up unexpectedly
![pod](https://user-images.githubusercontent.com/17905223/54490383-6546cb00-48f0-11e9-9a6b-84729eb994eb.png)

## CocoaPods Environment

   CocoaPods : 1.5.2
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.8
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

That said, you want to look at this:

> warning: Could not find remote branch 4.0.6 to clone.

Your repo doesn't have the 4.0.6 tag.

**Comment by Crazzzzyy** [comment]
thanks for reply, but my pod is installed by commit like this:
![image](https://user-images.githubusercontent.com/17905223/54490802-1307a900-48f4-11e9-97a0-dc6cf445e38d.png)

and it's ok for pod install, when i delete 'sub1' in subspecs,  pod install will faild

**Comment by Crazzzzyy** [comment]
> Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
> 
> That said, you want to look at this:
> 
> > warning: Could not find remote branch 4.0.6 to clone.
> 
> Your repo doesn't have the 4.0.6 tag.
thanks for reply, but my pod is installed by commit like this:
![image](https://user-images.githubusercontent.com/17905223/54490802-1307a900-48f4-11e9-97a0-dc6cf445e38d.png)

and it's ok for pod install, when i delete 'sub1' in subspecs,  pod install will faild
