### ISSUE TITLE
CocoaPod dependencies are not embedded to the framework binary created by Xcode

### ISSUE THREAD

**Issue by axnmax** [CocoaPods/CocoaPods#8616]
While building a cocoa touch framework that includes some Cocoapod dependencies. The CocoaPod dependencies are not embedded to the framework binary created by Xcode. Although this works if I make a iOS application all the Cocoapod dependencies are embedded in the .app file as separate .frameworks.

Is there any issue with using CocoaPods and CocoaTouch frameworks together? Is there any workaround for this issue ?

**Comment by dnkoutso** [comment]
All pod dependencies are currently linked to the top level app. Will close issue and re-open if we identify a bug.

**Comment by axnmax** [comment]
In this project the top level target is the framework only. Otherwise how to share this framework to third party apps if it will not embed the dependent pods.
