### ISSUE TITLE
XCode Server / Bot / Integration Error - Unable to open file (in target...

### ISSUE THREAD

**Issue by TekHero** [CocoaPods/CocoaPods#8619]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a project set up with an Xcode Server and a bot for pulling the latest changes from a Git repo and running test cases for the newest changes automatically

## What did you expect to happen?
I expected the integration to begin testing the newest version of the app on actual devices right away

## What happened instead?
Instead, the integration failed and prevented further testing from happening because of an error that says "error: /Users/my_user/Library/Caches/XCSBuilder/Bots/e28b0d4a3f0e9452c24f6ca389060753/Source/my_project/Pods/Target Support Files/Pods-my_project/Pods-my_project.debug pro.xcconfig: unable to open file (in target “my_project” in project “my_project”) (in target ‘my_project’)"

### Stack

```
   CocoaPods : 1.7.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
This does not seem a CocoaPods library issue as it stands. Please also upload a sample app or repository that demonstrate the issue.

**Comment by TekHero** [comment]
Yes you were correct, it was not a CocoaPods library issue. It has been resolved. Thanks!

**Comment by vineetj** [comment]
@TekHero : Please share how did you resolved it as i am also facing the same.

**Comment by DavidCelentano** [comment]
@TekHero @vineetj Also having this issue, what was the resolution?

**Comment by uddinr** [comment]
having this same issue how did you resolve this?

**Comment by fishercraigj** [comment]
ditto today.  same issue.

**Comment by gulabry** [comment]
same

**Comment by s-efanov** [comment]
It helps for me
https://medium.com/@romainbrunie/how-to-plug-in-cocoapods-with-xcode-server-e2cc9006e16c

**Comment by lizhaohong** [comment]
having this same issue how did you resolve this?
