### ISSUE TITLE
[1.7.0] The changes of local pods not work.

### ISSUE THREAD

**Issue by alexlee002** [CocoaPods/CocoaPods#8622]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
*  cocoapods version: 1.7.0
*  enable multi-project: `install! 'cocoapods', :generate_multiple_pod_projects => true`
*  Add local pod: `pod 'HomeModule', :path => 'Modules/HomeModule'`
*  run the app, and then modify the source code of `HomeModule`,  run the app again.

## What did you expect to happen?

I hope the change would work while I run the app again.

## What happened instead?

The new changes not work, and still shows the result of the old version. Even if I run `pod install`.
It only work if I clean and rebuild the app.

**Comment by segiddins** [comment]
Are you using dynamic frameworks, by any chance?

**Comment by alexlee002** [comment]
@segiddins 
YES， I enable `use_frameworks!` in my pod file. so the pods are build as dynamic frameworks.

**Comment by dnkoutso** [comment]
You're probably running into https://github.com/CocoaPods/CocoaPods/issues/8073 disable input/output paths and try again?

**Comment by alexlee002** [comment]
@dnkoutso 
Hi, I see the issue #8073 ,  And I will try it later.
Another solution: Add all the pods as sub-projects of the app,  and added to the app target's dependencies.

**Comment by alexlee002** [comment]
That's OK if I use static frameworks not dynamic frameworks.

**Comment by dnkoutso** [comment]
Yes it is OK to use static frameworks. This seems like #8073 going to close this as dup.
