### ISSUE TITLE
BITCODE_GENERATION_MODE not added to framework target in Pods project

### ISSUE THREAD

**Issue by uerceg** [CocoaPods/CocoaPods#8625]
# Report

## What did you do?
Run `pod install`

## What did you expect to happen?
I expected `Adjust` framework target inside of `Pods` project to have `User-Defined` setting `BITCODE_GENERATION_MODE` which is set on `Adjust` project level.

## What happened instead?
`Adjust` target inside of `Pods` project is missing `BITCODE_GENERATION_MODE` `User-Defined` setting.

### Stack
```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8daf51047f4804cd4938f375622d573c59832abc
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.0'
use_frameworks!

target 'test' do
    pod 'Leanplum-iOS-SDK'
    pod 'Adjust'
end
```
## Project that demonstrates the issue
[test.zip](https://github.com/CocoaPods/CocoaPods/files/2985875/test.zip)

---

If one tries to build this app with having device selected (not simulator, with it it works well), error will be reported that `Adjust.framework/Adjust` isn't built with full bitcode support. This can be fixed if one goes to `Adjust` target inside of `Pods` project and adds `User-Defined` setting `BITCODE_GENERATION_MODE=bitcode`.

In [here](https://github.com/adjust/ios_sdk/blob/master/Adjust.xcodeproj/project.pbxproj#L2845) you can see that this setting is enabled on project level (`9679922F18BBAE2800394606` is Release build of `PBXProject "Adjust"` as you can see in [here](https://github.com/adjust/ios_sdk/blob/master/Adjust.xcodeproj/project.pbxproj#L3314)).

So I am wondering why is this `User-Defined` setting not being translated to `Adjust` target inside of `Pods` project in app which uses it. Do you have any idea what might be causing this?

Looking forward to hear from you.

Cheers
Ugi

**Comment by dnkoutso** [comment]
The pods project is always re-generated. You should add it to `s.pod_target_xcconfig` of the `Adjust` pod.

**Comment by dnkoutso** [comment]
Is `Adjust` maintained by you? nothing in its podspec specifies this.

You can accomplish what you want with `post_install` hook.

Sorry going to close this does not appear to be a CocoaPods bug currently.

**Comment by uerceg** [comment]
Hi @dnkoutso

And thank you for your reply. No problem at all for closing the issue and yes, I am one of the maintainers. 

What you suggested seems like what I managed to find as only solution when testing locally before making new release (you can check my findings in here: https://github.com/adjust/ios_sdk/issues/368#issuecomment-474439095).

The only thing which remained mystery to me is that this other Pod I am adding to my test app seems to have this option automatically in its target in Pods project upon `pod install` and if you check their podspec file, they also don't have this mentioned option added to it. Do you maybe have any idea how is that possible?
