### ISSUE TITLE
cocoapod make private library error!!!!

### ISSUE THREAD

**Issue by xavierXing** [CocoaPods/CocoaPods#8626]
hi ：

When I used cocoapod to make the private library, I relied on other frameworks, but I didn't rely on cocoapod, but directly integrated it into the internal. Now there are many mistakes in the figure below, how can I solve this problem?

![WeChat8145cd0bc830c5760674292197268888](https://user-images.githubusercontent.com/13817436/54662025-6ad22a00-4b17-11e9-8ffb-9f31f772c9b9.png)

![企业微信截图_60fa363d-0b45-40cb-acb3-d3ffa7325bc0](https://user-images.githubusercontent.com/13817436/54662172-19766a80-4b18-11e9-8fc3-2af7b849c3a7.png)
<img width="2402" alt="WeChat597eb1a33dab9a61ecda5215befbbd5d" src="https://user-images.githubusercontent.com/13817436/54662174-1aa79780-4b18-11e9-9913-e4dac1e99c48.png">

![WechatIMG17](https://user-images.githubusercontent.com/13817436/54662047-8b9a7f80-4b17-11e9-994b-26276cad260a.jpeg)

**Comment by dnkoutso** [comment]
Please use StackOverflow under `cocoapods` tag for these questions.

This does not appear a CocoaPods library issue.
