### ISSUE TITLE
OTHER_LDFLAGS of pods are inherited by app target

### ISSUE THREAD

**Issue by tamastimar** [CocoaPods/CocoaPods#8629]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

`OTHER_LDFLAGS` of app target are not filled with values coming from pods.

## What happened instead?

`OTHER_LDFLAGS` of pod appear in app target.

```OTHER_LDFLAGS = $(inherited) -l"sqlite3" -l"sqlite3" -framework "UIKit"```
(sqlite, sqlite3, UIKit are coming from the dependency.)

In my private project there is a custom library linked to the dependency pod from a custom path. So the app target can't be linked since it can't find the library.

It worked as expected in CP 1.5.3.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3aff96531d015fefa5df4448a12f161b8ded89e5
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-art         : 1.0.2
cocoapods-deintegrate : 1.0.3
cocoapods-links       : 0.3.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

def shared_pods
  pod 'dep', :path => '.'
end

target 'ldflags-test' do
  shared_pods 
end
```

## Project that demonstrates the issue

https://github.com/tamastimar/CocoaPods--8629-Sample

**Comment by tamastimar** [comment]
Possibly releated to #8608.

**Comment by dnkoutso** [comment]
This works for me on 1.6.1.
![Screen Shot 2019-05-03 at 11 31 42 AM](https://user-images.githubusercontent.com/310370/57148167-0b626d80-6d97-11e9-9d07-ed9c563e7024.png)
