### ISSUE TITLE
Build Error For Subspec: Cycle in dependencies between targets

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8634]
I have two pods `A` and `B`:
```
{
  "name": "A",
  "subspec": [
    {
      "name": "Interface"
    },
    {
      "name": "Core",
      "dependencies": [
        "B/Interface"
      ]
    }
  ]
}
```
```
{
  "name": "B",
  "subspec": [
    {
      "name": "Interface"
    },
    {
      "name": "Core",
      "dependencies": [
        "A/Interface"
      ]
    }
  ]
}
```
As the podspec said, the `A` dependency `B/Interface` and `B` dependency `A/Interface`. There is not cycle dependency for CocoaPods.

Now, I have a user app target `AppTarget`, and it have the pod `A` and `B`:
```
pod 'A'
pod 'B'
```

When I build the app, I get a error:
```
error: Cycle in dependencies between targets 'B-1234567' and 'A-1234567'; building could produce unreliable results.
```
CP will create a Pod Target `A-1234567` contains `A/Interface` and `A/Core`. So the target `A-1234567` and `B-1234567` are not allowed by Xcode 10.

Could we split the `A-1234567` into two targets which `A-Interface` and `A-Core`? if that, it will build success.

**Comment by dnkoutso** [comment]
This is not currently supported. Subspecs always get enabled or disabled but added as the "root" pod name.

There is no splitting of subspecs yet and maybe there never will be.

**Comment by dnkoutso** [comment]
The "best" idea is to split the two into separate podspecs

**Comment by Whirlwind** [comment]
If the A.podspec is below:
```
{
  "name": "A",
  "subspec": [
    {
      "name": "Interface",
      "pod_target_xcconfig": {
         "OHTER_LDFLAG": "-DEBUG"
       }
    },
    {
      "name": "Core",,
      "pod_target_xcconfig": {
         "OHTER_LDFLAG": "-NDEBUG"
       }
      "dependencies": [
        "B/Interface"
      ]
    }
  ]
}
```
Now, the xcconfig of pod target `A-1234567` will have the `OTHER_LDFLAG = -DEBUG -NDEBUG`, it seems wrong.

**Comment by dnkoutso** [comment]
As I said subspecs are part of a single target and not their own so if they are activated (used) then the `pod_target_xcconfig` is merged.

**Comment by dnkoutso** [comment]
Unless you mean that `A/Core` is not activated and therefore should not be merged at all which might be a bug if it happens.

**Comment by Whirlwind** [comment]
The `A/Interface` and `A/Core` should be activated, but they have conflict config! CP use a single target will merge the `pod_target_xcconfig`, it will cause build failed.
