### ISSUE TITLE
CocoaPods 1.6.1 ignores Swift version in pods pushed by CocoaPods 1.7.0-beta.1

### ISSUE THREAD

**Issue by 1ec5** [CocoaPods/CocoaPods#8637]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

A Swift pod pushed to CocoaPods trunk using CocoaPods v1.7.0-beta.1 or above is incompatible with projects that integrate the pod using CocoaPods v1.6.1.

I’m breaking the rules and eschewing the issue template, because I think it’s clearer to explain it this way, but a filled-out template follows down below.

## Steps to reproduce

This past Friday, a Ruby podspec specifying `swift_version` (singular) of 4.0:

https://github.com/mapbox/mapbox-navigation-ios/blob/58a1a43efd9498604b483bf93e145b3aa2aa6a10/MapboxCoreNavigation.podspec#L51

was pushed to CocoaPods trunk using CocoaPods v1.7.0-beta.2. Due to #8192, the resulting JSON podspec specified `swift_versions` (plural):

https://github.com/CocoaPods/Specs/blob/9296973de80172a1ecb2389d5f02f742934ca46b/Specs/a/7/3/MapboxCoreNavigation/0.30.0/MapboxCoreNavigation.podspec.json#L40

CocoaPods v1.6.1 doesn’t recognize `swift_versions` (plural), so the pod’s target ends up inheriting the `SWIFT_VERSION` of the application target, which may be 4.2 rather than 4.0.

## Workaround

I worked around the issue by deleting the pod version and pushing the same Ruby podspec using CocoaPods v1.6.1. (I had to apply the workaround in #8635 because of CocoaPods/trunk.cocoapods.org#256.) That resulted in a JSON podspec specifying `swift_version` (singular), as expected:

https://github.com/CocoaPods/Specs/blob/64276e07a7eeef4f3e0164c496a37218387fa920/Specs/a/7/3/MapboxCoreNavigation/0.30.0/MapboxCoreNavigation.podspec.json#L40

Now applications written in Swift 4.2 can safely integrate the pod.

Another, less satisfying workaround would’ve been to set `cocoapods_version` to require v1.7.0-beta.1 or higher.

## Suggested fix

A fix would either entail releasing a CocoaPods v.1.6._x_ update that recognizes `swift_versions` (plural) or releasing a new beta of CocoaPods v1.7.0 that reverts to `swift_version` (singular) when there’s only one version.

----

The usual issue form follows…

# Report

## What did you do?

1. Author a podspec that sets `swift_version` (singular) to 4.0.
1. `pod trunk push` using CocoaPods 1.7.0-beta.1 or above, which includes CocoaPods/CocoaPods#8192.
1. Create an Xcode application target written in Swift 4.2.
1. Author a Podfile for this Xcode project that requires the pod from CocoaPods trunk.
1. `pod update` using CocoaPods 1.6.1.

## What did you expect to happen?

CocoaPods 1.6.1 generates an Xcode target that has `SWIFT_VERSION` set to `4.0` in build settings.

## What happened instead?

CocoaPods 1.6.1 generates an Xcode target that has `SWIFT_VERSION` set to `4.2` in build settings.

## CocoaPods Environment

Here’s the environment in step 5. The environment in step 2 has CocoaPods 1.7.0-beta.1 or above installed instead.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.3_1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 079d9aa6c155a393f43c2d495e122b49e5a6b866
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.3
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.3.1
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'Navigation-Examples' do
    pod 'MapboxNavigation', '~> 0.30.0'
end
```

/ref mapbox/mapbox-navigation-ios#2060

**Comment by dnkoutso** [comment]
The author can specify `cocoapods_version` DSL to limit consumers for using the new DSL.

**Comment by dnkoutso** [comment]
There is currently no plan to make 1.6.x support the new plural DSL.

**Comment by 1ec5** [comment]
It would be rather aggressive to require everyone to adopt v1.7.0 before it comes out of beta, wouldn’t it? This affects every pod written in Swift.

**Comment by dnkoutso** [comment]
Why is the pod published with the beta? It seems if the producer of the pod wants to use this new feature but does not expect consumers to do so?

**Comment by 1ec5** [comment]
The podspec didn’t make use of the new feature, only the same `swift_version` (singular) as before. The only mistake was upgrading to the beta before pushing the pod.

**Comment by paulb777** [comment]
One option is to use the `cocoapods_version` attribute in the podspec like [this](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseAuth.podspec#L24).  Then consumers would be forced to upgrade before using it.

**Comment by 1ec5** [comment]
Unfortunately, it isn’t feasible to set `cocoapods_version` to 1.7.0-beta.1, because not everyone is willing to run a prerelease CocoaPods. Depending on how long it takes before 1.7.0 comes out of beta, setting it to 1.7.0 then might still be an aggressive upgrade schedule to force upon the pod’s consumers.

**Comment by dnkoutso** [comment]
@1ec5 if you do not mind I am closing this is as dup of #8635. Let's move conversation there.
