### ISSUE TITLE
The pod version is not match with `Manifest.lock`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8647]
The CocoaPods use `Pods/Manifest.lock` ( copy from `Podfile.lock`) to get the pod version in the sandbox. But I found that we often get a build error, the CP use a wrong version but the version in the `Manifest.lock` is right.

The version in the sandbox is different with the Manifest.lock!!

I think the reason is that the pod in the sanbox was installed by last `pod install`, but the install  failed. The `Manifest.lock` not be updated and the pod in the sandbox is updated. On the other hand, I try to use the old `Podfile.lock` and CP think the `Podfile.lock` is same with `Manifest.lock`, so CP will use the pod in the sandbox. But the pod's version is updated.

I think we could add a version file in the pod directory, and check the version whether is equal to the version in the `Manifest.lock`.

**Comment by dnkoutso** [comment]
Need sample please

**Comment by Whirlwind** [comment]
I could not do a sample, it is accidental.

You can try do these steps:

1. run `pod install`, and it works.
2. change a pod version in the `Podfile` (eg: Pod `A` changed to `2.0` from `1.0`)
3. run `pod install`, wait the download finished, the kill the `pod install` before CP write the lockfile.
4. revert the `Podfile` ( change `A` to `1.0` from `2.0`)
5. run `pod install` and run the project in the xcode.

Now, the `A` is `1.0` in the `Manifest.lock` and it is `2.0` in the Sandbox.
