### ISSUE TITLE
Is the order of the sources relevant?

### ISSUE THREAD

**Issue by ripperhe** [CocoaPods/CocoaPods#8650]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Use the Pod of the first source.

## What happened instead?

Actually use the pod of  the official CocoaPods source.

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.8.1
Ruby lib dir : /Users/ripper/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e0b8b3b1e7b84d667194fa8476396961ba04ce0d
               PicoocSpecs - https://git.picooc.com/iOS/Specs.git @ ebcde5094bca220b9ac674a221c39665612db9a2
               taobao-baichuansdk-alibcspecs - http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git @ fba92a5a2ad724fef413ceed649b73de78433e25
               ZYSpec - https://git.coding.net/ripper/ZYSpec.git @ 9dd366df171589c2f811cf619c9119b92df40071
```

### Installation Source

```
Executable Path: /Users/ripper/.rvm/gems/ruby-2.3.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://git.picooc.com/iOS/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


# platform :ios, '9.0'

target 'PodTest' do
  pod 'MJRefresh'
end
```
## Project that demonstrates the issue

![Jietu20190329-105052](https://user-images.githubusercontent.com/13943595/55206440-642b6d00-5211-11e9-90aa-9bdb90d5f445.png)
![Jietu20190329-105115](https://user-images.githubusercontent.com/13943595/55206443-67265d80-5211-11e9-8d3e-4894dc7ca6d1.png)

**Comment by dnkoutso** [comment]
It is and you can use `pod 'MyPod', :source => 'source'` to override it.
