### ISSUE TITLE
Podfile with `integrate_targets: false` set fails on lack of SWIFT_VERSION

### ISSUE THREAD

**Issue by dfed** [CocoaPods/CocoaPods#8653]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Ran `pod install`

## What did you expect to happen?

Download our dependencies distributed via CocoaPods

## What happened instead?
```
Analyzing dependencies
Downloading dependencies
Using CocoaLumberjack (3.4.2)
[!] Unable to determine Swift version for the following pods:

- `CocoaLumberjack` does not specify a Swift version and none of the targets (`Random-Inc`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
    RubyGems : 3.0.2
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.21.0
Ruby lib dir : /Users/dan_federman/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d1274e7ae102fca8339dae1ec8fa9a6b1331e149
```

### Installation Source

```
Executable Path: /Users/dan_federman/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 1.0.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

# Only download the files, don't create Xcode projects
install! 'cocoapods', integrate_targets: false

use_frameworks!

target 'Random-Inc' do
  pod "CocoaLumberjack/Swift", '~> 3.0'
end
```

## Project that demonstrates the issue

See Podfile above

**Comment by dnkoutso** [comment]
confirmed both issues. Will fix for 1.7.0.

**Comment by segiddins** [comment]
> Adding a bit of color to this issue: it looks like the Pods.xcodeproj is generated even though we have integrate_targets: false set

The Pods project is still supposed to be generated, it just doesn't get _integrated_ into your own Xcode project

**Comment by dfed** [comment]
Got it @segiddins. I'd love the ability to turn the `xcodeproj` generation off, since I'm using another tool to define my library sources & do project generation. Should I file a separate feature-request issue?

**Comment by segiddins** [comment]
Sure, though we're not likely to work on that feature in the near-term

**Comment by dfed** [comment]
Makes sense @segiddins. I've filed https://github.com/CocoaPods/CocoaPods/issues/8683.

**Comment by dnkoutso** [comment]
This bug can be circumvented. When integration is off, cocoapods does not compute the swift version for the target definition therefore treating them all as blank.

Doing:
```ruby
target 'Random-Inc' do
  pod "CocoaLumberjack/Swift", '~> 3.0'
  current_target_definition.swift_version = '4.0'
end
```

Should work but people who fall into this bug should be aware that this API might change. We need to see if we want to expose `swift_version` as a DSL under target definition and also update cocoapods not to compute and set it directly on the target definition.

Discussed with original issue author and workaround is sufficient to close for now.
