### ISSUE TITLE
[Feature] Use `Development Pods` group for `generate_multiple_pod_projects` mode

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8659]
When `:generate_multiple_pod_projects=>true`, all pod will use a single project in `Dependencies` group, include the development pods. It is hard to find the development pod in 150+ pods!! On the other hand, it is hard to check whether is a local pod for a pod ( I must check the path of a source file).

Have CP a plan that move back the local pod to `Development Pods` group? Of cause, I still hope keep the single pod project for per-pod in the `Development Pods`.

**Comment by sebastianv1** [comment]
I think it makes sense for subprojects to just holds a `Dependencies` group, but for `Pods.xcodeproj` we could produce a similar structure as before since it holds every pod in the workspace. Thoughts @segiddins @dnkoutso ?

**Comment by amorde** [comment]
I'd be in favor of something like the `Development Pods` group that exists now, I use it in my projects

**Comment by sebastianv1** [comment]
Cool, so I'm thinking the structure would look something like:
```
├── Pods.xcodeproj
│   ├── Development Pods (if they exist)
│   │   ├── Local Pod A
│   │   │   └── Dependencies
│   ├── Pods
│   │   ├── Remote Pod A
│   │   │   └── Dependencies
...
```
The `Dependencies` group still gets generated, but only for each individual subproject and *not* for `Pods.xcodeproj`.

**Comment by Whirlwind** [comment]
Why do we need the `Dependencies` group? I think the old structure is fine:
```
├── Pods.xcodeproj
│   ├── Development Pods (if they exist)
│   │   ├── Local Pod A.xcodeproj
│   ├── Pods
│   │   ├── Remote Pod A.xcodeproj
```

Or, move the development pod into workspace:
```
├── Pods.xcodeproj
│   ├── Pods
│   │   ├── Remote Pod A.xcodeproj
│── Local Pod A.xcodeproj
```

**Comment by sebastianv1** [comment]
`Dependencies` group is required for target dependencies to be set up correctly. A target dependency can only be added to a target if it exists in the same project or is nested as a subproject, hence the `Dependencies` group.

**Comment by sebastianv1** [comment]
PR: #8731

**Comment by wulongwang** [comment]
cocoapods can do that below?
> ```
> ├── Pods.xcodeproj
> │   ├── Remote Pod A.xcodeproj
> │   ├── Framework
> │── Local Pod A.xcodeproj
> ```
