### ISSUE TITLE
Pod install with legacy build system does not remove the xcfilelist files

### ISSUE THREAD

**Issue by csknns** [CocoaPods/CocoaPods#8662]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
The pod install when the legacy build system is enabled does not produce xcfilelist files files but does not remove them from the Copy Pods Resources build phase if a previous pod install had the the new build system in the workspace.

## What did you do?

pod install
changed the build system of workspace to legacy
pod install
build

## What did you expect to happen?
The build should succeed.
The pod install when the legacy build system should remove them from the Copy Pods Resources build phase.

## What happened instead?
the build failed with error:
Dependency error can not find file
				```"${PODS_ROOT}/Target Support Files/X-Optio/Pods-X-resources-${CONFIGURATION}-input-files.xcfilelist",```

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.13
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/christoskoninis/.rbenv/versions/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e32cfb2068c5fc464211639e053a0c8968da0a37
```

**Comment by dnkoutso** [comment]
xcfilelists are not tied to new or old buidl system afaik. Its mostly the version of Xcode you are using and what version your `.xcodeproj` is compatible with.

**Comment by dnkoutso** [comment]
That said it is probably a bug yes.

**Comment by jrickett** [comment]
Looks like 1.7.0 fixes this
