### ISSUE TITLE
podfile in unix executable

### ISSUE THREAD

**Issue by rich202** [CocoaPods/CocoaPods#8665]
Hi, i cannot edit podfile because it is in unix executable format. i double click but it said line 12 target: command not found and line 13 end: command not found. 

The podfile comes along with https://github.com/udacity/ios-nd-firebase

i use the pod version is 1.6.0

i did pod init again, but it said podfile already exist.

Thank you

**Comment by dnkoutso** [comment]
Hi there sorry this isnt an actionable bug report for us. Please use StackOverFlow under cocoapods tag to ask these questions or fill in issue template with a reproducible sample app.
