### ISSUE TITLE
How to remove "${PODS_ROOT}/Headers/Private" from Pod.xcconfig when pod install/update

### ISSUE THREAD

**Issue by lusnaow** [CocoaPods/CocoaPods#8666]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
pod install/update

## What did you expect to happen?
HEADER_SEARCH_PATHS of Pod.xcconfig should not have "${PODS_ROOT}/Headers/Private".  
I know this line is added to HEADER_SEARCH_PATHS by default, can I customize it? I can't find any help on https://guides.cocoapods.org/syntax/podspec.html#pod_target_xcconfig.

## What happened instead?
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Private" "..." "..."

### Stack

```
   CocoaPods : 1.7.0.beta.3
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14.5 (18F96h)
       Xcode : 10.2 (10P99q)
         Git : git version 2.20.1 (Apple Git-116)
Ruby lib dir : /usr/local/Cellar/ruby/2.6.0/lib
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true
target 'Sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sample

pod 'PodB', :git => 'git@github.com:lusnaow/PodB.git'
pod 'PodA', :path => '../PodA'

end
```

**Comment by dnkoutso** [comment]
This is how it has been since CocoaPods 0.3.x and 1.x.

You are right it shouldnt be there but that is a huge change to make and can only be made for 2.x version as it will be a breaking change for folks.

Going to close for now.
