### ISSUE TITLE
podspec validation: target has no source files

### ISSUE THREAD

**Issue by theodelrieu** [CocoaPods/CocoaPods#8667]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

>pod spec lint MyPod.podspec --skip-tests

## What did you expect to happen?

Lint validation.

## What happened instead?

- ERROR | [iOS] unknown: Encountered an unknown error (Unable to install the `MyPod` pod, because the `MyPod-Unit-Tests` target in Xcode would have no sources to compile.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.16.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : repo - git@10.100.0.1:MyProject/PodSpecs.git @ 727d7bd3b3472cefe78234a27e975be317d149bf
               master - https://github.com/CocoaPods/Specs.git @ cf09b5ae71fbc2bf1f961bdb2c9a87fa8de644cd

```

### Installation Source

```
Executable Path: /Users/theo/.gem/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

My main issue seems to be about `test_spec`. Long story short I do not provide test files in the final Pod, and I'd like to remove the `test_spec` from the `MyPod.podspec`.

Even passing `--skip-tests` does not help... Is there any other way than providing test files?

**Comment by dnkoutso** [comment]
Remove the `s.test_spec` declaration then.

**Comment by theodelrieu** [comment]
I need the `test_spec` locally for CI integration, and I'd like to avoid having two separate podspecs.

**Comment by dnkoutso** [comment]
Hm...can you please a temporary file ? This is a check in the linter that I dont think we want to remove.

**Comment by theodelrieu** [comment]
Here is the [podspec](https://github.com/TankerHQ/sdk-ios/blob/master/Tanker/Tanker.podspec) I have.

**Comment by theodelrieu** [comment]
The workaround is to add a `Dummy.m` file for the test_spec target. Actually it was `pod repo push` that was unhappy, passing `--skip-import-validation` had no effect.
