### ISSUE TITLE
Include pod with a deployment target different from the app

### ISSUE THREAD

**Issue by amaurydavid** [CocoaPods/CocoaPods#8669]
Hello :)
I have an app that has its deployment target set to iOS 9 and I would like to use a pod which target's is iOS 10. Users using iOS 10+ will then be able to use the feature while users on iOS 9 will be handled differently.
Is there a way to do this with cocoapods? I've seen some old issues here about this kind of behavior but they are few years old and I guess things have moved since.

The reason why the pod is only compatible iOS 10+ is because it itself uses a library that is incompatible with iOS 9. Is it possible in a pod to use optional libraries ?

Thanks!

**Comment by dnkoutso** [comment]
To my knowledge nothing has changed here. Sorry this is not currently supported.
