### ISSUE TITLE
Accessing PODS_TARGET_SRCROOT in podspec

### ISSUE THREAD

**Issue by theodelrieu** [CocoaPods/CocoaPods#8673]
This is more a question than a bug.

Using cocoapods v1.6.1
I'm vendoring some static libs in a podspec of mine, the code looks like that:

```ruby
s.subspec "sub" do |ss|
    libs = Dir['Libraries/*.a']
    ss.vendored_libraries = libs
    ss.libraries = ['c++', 'c++abi'] + libs.collect{|l| l[/lib(.*).a/, 1]}
end
```

The first line works great during local dev, but after a release when users run `pod install`, `libs` is empty, thus the link fails.
It seems the podspec is separated from everything it contains. The former is in `~/.cocoapods/...`, while the latter is in `PODS_TARGET_SRCROOT`, i.e. `Pods/Local Podspecs`.

Is there a way to access `PODS_TARGET_SRCROOT` in a `subspec` definition?

Or must I enumerate all static libs by hand which is quite cumbersome, especially when adding new libs.

Thanks!

**Comment by dnkoutso** [comment]
Not currently. The `PODS_TARGET_SRCROOT` is set a variable and is part of `xcodebuild`.

**Comment by dnkoutso** [comment]
Going to close and we can continue this discussion here. I will re-open if we can find out an enhancement or bug fix.

**Comment by theodelrieu** [comment]
Agreed. I think one way to fix this would be to change the current directory to where the pod has been extracted, when a pod is consumed.

**Comment by theodelrieu** [comment]
The rationale for this suggestion is that the Podspec file is the **only** file in its folder. Therefore there is nothing interesting that can be done with the current working dir.

**Comment by segiddins** [comment]
You can use globs natively in podspecs, ```
s.vendored_libraries = “*.a”
```

**Comment by theodelrieu** [comment]
I remember I had to specify `s.libraries` as well, because the linker would not get the `-lstuff.a` flags.
Or is it done automatically by setting `s.vendored_libraries`?

**Comment by dnkoutso** [comment]
`s.libraries` is for system libraries use `s.vendored_libraries` which will add the `-lstuff.a` for you.

**Comment by theodelrieu** [comment]
Thanks, I'll try that!

**Comment by theodelrieu** [comment]
I tried your solution, with no success:

```ruby
# Below lines all fail
s.vendored_libraries = '*.a'
s.vendored_libraries = 'Libraries/*.a'
s.vendored_libraries = ['Libraries/*.a']
s.vendored_libraries = '**/Libraries/*.a'

# This works, the -lboost_atomic appears in the linker invocation
s.vendored_libraries = ['Libraries/libboost_atomic.a'] 
```

It seems there is an issue with patterns. Do you want me to open a new issue?

**Comment by theodelrieu** [comment]
In fact, the latter does not work all the time. Sometimes it is present in the linker invocation, sometimes it is not. Reverting changes to the podspec and running `pod install` does not yield the same output

**Comment by theodelrieu** [comment]
Hmm, building `MyLib` target instead of `MyLib-Unit-Tests` correctly links the vendored libs. However, building `MyLib-Unit-Tests` afterwards still fails to link, even though the `-framework MyLib` is provided.

**Comment by theodelrieu** [comment]
Ok, my bad, I forgot to add a `vendored_libraries` attribute in my test spec... Thanks for your help!
