### ISSUE TITLE
How to have resources copied into main bundle and not a framework?

### ISSUE THREAD

**Issue by gabimo** [CocoaPods/CocoaPods#8678]
I want my pod assets copied into the main bundle. I see cocoapods creates a framework and I can access the images from code but unless theyre in the main bundle theyre not accessible to the Xcode interface builder. They appear in the XC Interface builder but they don't load when compiled because theyre not in the main bundle. Is it no longer possible to have resources copied over to the main bundle? 

https://github.com/CocoaPods/CocoaPods/issues/3643 

This might be old and it doesn't seem to be accurate: https://github.com/CocoaPods/CocoaPods/issues/5105#issuecomment-204243998 

> Without Sources (.m's)
> There's nothing to compile, so there's nothing to turn into the executable part of a .framework, so there's no way to create a valid framework bundle. Since there's no bundle, the resources get copied into the main app bundle.

**Comment by cltnschlosser** [comment]
You can use this https://guides.cocoapods.org/syntax/podspec.html#resources but notice there are downsides.
