### ISSUE TITLE
An unexpected version directory `General` was encountered

### ISSUE THREAD

**Issue by nikunjazilen** [CocoaPods/CocoaPods#8680]
@amorde  Can you please help me out the resolve issue?

 I m following same structure for pod specification as per [https://guides.cocoapods.org/making/private-cocoapods.html](https://guides.cocoapods.org/making/private-cocoapods.html) but facing issue like "An unexpected version directory `General` was encountered for the `/Users/nikunjjadav/.cocoapods/repos/AppKit/AppKit` Pod in the `AppKit` repository."

Also, General folder is available and inside this folder classes is there.

**AppKit.podspec**
spec.source       = { :git => "https://test.adv.com/_git/iOS_App", :tag => "#{spec.version}" }
spec.source_files  = "Classes", "AppKit/**/*.{h,m,swift}"
spec.exclude_files = "Classes/Exclude"

Folder Structure: Spec -> AppKit -> 2.0.5 -> AppKit.podspec

Thanks in advance.

**Comment by dnkoutso** [comment]
Please ask StackOverflow under `cocoapods` tag for these kind of problems.
