### ISSUE TITLE
$ pod spec lint causes  errors with private repo

### ISSUE THREAD

**Issue by sumansun** [CocoaPods/CocoaPods#8681]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I have created a private spec repo in a private organization. The podspec points to a source in a private repo as below 
  `s.source                    = { :http => 'https://PrivateRepo/Framework.zip' }`

The pod lint fails when i run `pod spec lint Framework.podspec`

## What did you expect to happen?

Pod validation succeeds

## What happened instead?

This fails podspec with error as 
`End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.`

However, when i replace the s.source with the S3 URL it works fine. I am accessing the url from within private network which has access to the zip and downloads when i click on it. However, podspec throws an error. 
### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G6030)
       Xcode : 10.1 (10B61)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2cb234a339f52cbf32fdb10ef1c9b20f175d4e3c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
We are unable to diagnose this with the given information. Please ask StackOverflow under `cocoapods` tag for assistance.

`pod spec lint` will download the source you have so maybe the `zip` file you are downloading is corrupt.

I will re-open this issue if we can show its a cocoapods bug (perhaps in the cocoapods-downloader) project.

**Comment by harishgupta01** [comment]
@sumansun Hi, Did you find any solution for this issue ?
