### ISSUE TITLE
How to set -force_load config in  .podspec file

### ISSUE THREAD

**Issue by ToBeDefined** [CocoaPods/CocoaPods#8682]
i'm writing an podspec file , and set `s.static_framework = true` want this pod always use static libary.

then i want set `-force_load` config, what should I do?

Suppose my pod is named `ABC`, I've tried set this (i'm using v1.6.1 now):
	`s.user_target_xcconfig = {'OTHER_LDFLAGS' => '-force_load $(PODS_CONFIGURATION_BUILD_DIR)/ABC/libABC.a'}`

but when user set `use_frameworks!` in there `Podfile`, is obviously will fail when they run `pod install`.

because the lib is `ABC.framework`, and 
`s.user_target_xcconfig` should be `{'OTHER_LDFLAGS' => '-force_load $(PODS_CONFIGURATION_BUILD_DIR)/ABC/ABC.framework/ABC'}`.

But here's the problem, when i set the latter config, when user use static lib(not set `use_frameworks!` in there `Podfile`), its still have error.

I want know how to set `-force_load` config, or have other way?

can i check user's `Podfile` and then set relevant config in `.podspec` file, or have some config variable can do this?

**Comment by paulb777** [comment]
There's not enough information here for me to be sure that this is your issue, but the `static_framework` attribute is only for source CocoaPods. Binary `vendored_frameworks` are already typically built with static libraries without the attribute.

**Comment by dnkoutso** [comment]
You also cannot check the settings of the `Podfile` those are controlled by the consumer of your pod.

**Comment by dnkoutso** [comment]
Going to preemptively close and I will re-open if we can find an enhancement or bug in cocoapods.
