### ISSUE TITLE
Closed source library missing when using specific branch

### ISSUE THREAD

**Issue by jakunico** [CocoaPods/CocoaPods#8687]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

A little bit of info:

We have a closed source library that we distribute through Cocoapods. You can check our podspec [here](https://github.com/mozioinc/mobile-sdk-ios).

We are having trouble installing our SDK in a project created with Xcode 10.2 so we created a new branch `xcode-10.2` that we would use to play around and try to get the root of the problem.

## What did you do?

Created a new branch in the repo that holds our `.podpsec` and tried to install our library from that specific branch.

## What did you expect to happen?

The contents of the `.zip` file (our `.framework`) is found at `/Pods/Mozio/Mozio.framework` folder.

## What happened instead?

The contents of the `.zip` file (our `.framework`) is missing from the `/Pods/Mozio` folder.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.2 (10E125)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/nicolas/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0eed24425822af1dfeda0bf609d55ec8f4b543ae
```

### Installation Source

```
Executable Path: /Users/nicolasjakubowski/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnotherTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "Mozio", :git => "https://github.com/mozioinc/mobile-sdk-ios.git", :branch => "xcode-10.2"

end
```

## Project that demonstrates the issue

Download from [here](https://drive.google.com/open?id=1BKoieOBv9MfqI4gIc0h18MMpl0sOBVCA).

This is what I did:

1. Create a new project with Xcode 10.2
2. Add `pod "Mozio", :git => "https://github.com/mozioinc/mobile-sdk-ios.git", :branch => "xcode-10.2"` to the `Podfile`
3. Check the `Pods/Mozio/` directory where you will see that the `.zip` contents are not there.

If you then go and change the line added in `2.` for just `pod "Mozio"` you will get the framework correctly downloaded. Notice that project will still not compile (this is the problem we're trying to solve) but that is not related to this issue.

**Comment by segiddins** [comment]
Pointing to a git repo will always assume the contents of the repo can _replace_ what's in the source, and therefore no other archive will be expanded. You can either use `podspec` to point to a spec with the amended source, or expand the zip file in your git repo

**Comment by jakunico** [comment]
Fantastico @segiddins! That worked like charm.

For anyone encountering this, here's what solved the problem:

```
pod "Mozio", :podspec => "https://raw.githubusercontent.com/mozioinc/mobile-sdk-ios/xcode-10.2/Mozio.podspec"
```
