### ISSUE TITLE
Failing adding pod to multiple targets

### ISSUE THREAD

**Issue by impul** [CocoaPods/CocoaPods#8707]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
 Added `AvatarHashView` to my Podfile
 Run `pod install`
 Open 'Essentia.xcworkspace'
 Get warnings about that `Realm` (not related to `AvatarHashView`) can not be auto-linked
## What did you expect to happen?
 Pod installed normally
## What happened instead?
`EssUI` Targert get a warning
Project do not build anymore
### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ d285c517e258effbe6933bf44e2a5ddf4f0cfedb
               essentia - https://github.com/essentiaone/ess-cocoapodspec @ 193e66d7c91debf31768620259835619526caa4a
               master - https://github.com/CocoaPods/Specs.git @ caa65c12b20773827754af88708404345e1ef76f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-check       : 1.0.2
cocoapods-deintegrate : 1.0.2
cocoapods-keys        : 2.0.6
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.0'
inhibit_all_warnings!
ENV['COCOAPODS_DISABLE_STATS'] = "true"

workspace 'Essentia.xcworkspace'

source 'https://github.com/CocoaPods/Specs.git'

# Pods def

def pod_analytics
    pod 'Fabric'
    pod 'Crashlytics'
end

def pod_core
   pod 'HDWalletKit'
   pod 'essentia-bridges-api-ios'
   pod 'essentia-network-core-ios'
end

def pod_notification
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end


def pod_functional 
    #pod 'PromiseKit', '~> 6.0'
end

def pod_ui
    pod 'SVProgressHUD' # Can remove later
    pod 'Kingfisher', '5.1.1' # Can remove later
    pod 'QRCodeReader.swift' # Can remove later
    pod 'AvatarHashView'
end

def pod_debug
    pod 'CocoaLumberjack/Swift'
end

def pod_database
    pod 'RealmSwift'
end

# Core functionality

target 'EssModel' do
    project 'Modules/EssModel/EssModel.xcodeproj'
    use_frameworks!
    pod_database
end

target 'EssUI' do
    project 'Modules/EssUI/EssUI.xcodeproj'
    use_frameworks!
    pod_ui
end

target 'EssResources' do
    project 'Modules/EssResources/EssResources.xcodeproj'
    use_frameworks!
    pod_debug
    pod_database
end

target 'EssDI' do
    project 'Modules/EssDI/EssDI.xcodeproj'
    use_frameworks!
    
end

target 'EssCore' do 
    project 'Modules/EssCore/EssCore.xcodeproj'
    use_frameworks!
    pod_debug
    pod_ui
    pod_core
end

# dApps

target 'EssWallet' do 
    project 'Modules/dApps/EssWallet/EssWallet.xcodeproj'
    use_frameworks!
    pod_core
    pod_debug
    pod_ui
    pod_database
end

# =====

target 'Essentia' do
    use_frameworks!
    pod_core
    pod_ui
    pod_debug
    pod_analytics
    pod_functional
    pod_database
    pod_notification
end

target 'EssUIGallery' do 
    project 'Modules/EssUIGallery/EssUIGallery.xcodeproj'
    use_frameworks!
    pod_core
    pod_ui
    pod_database
    pod_debug
end
```

## Project that demonstrates the issue
https://github.com/essentiaone/Essentia-iOS/tree/feature/avatar-hash-view

**Comment by impul** [comment]
Any suggestions? Also interesting is that I got waring in `EssUI` target. There only imported `pod_ui`.

**Comment by amorde** [comment]
I can't get this project to build with a fresh checkout in Xcode 10.2 - it has a build error in one of the dependencies

<img width="1342" alt="Screen Shot 2019-04-17 at 3 20 24 PM" src="https://user-images.githubusercontent.com/2281949/56324668-58eaa380-6124-11e9-99bb-307058e67166.png">

Could you upload a .zip of a project that reproduces the issue?

**Comment by impul** [comment]
@amorde , I build project in Xcode 10.1

**Comment by dnkoutso** [comment]
I get no warning when building `EssUI` target. I cant build Essentia due to Swift compilation issues on Xcode 10.1

**Comment by impul** [comment]
@dnkoutso, 
![Screenshot 2019-04-22 at 3 39 26 AM](https://user-images.githubusercontent.com/15803807/56477617-626f6500-64b0-11e9-81a0-5a4a3c344f35.png)
![Screenshot 2019-04-22 at 3 39 55 AM](https://user-images.githubusercontent.com/15803807/56477623-6b603680-64b0-11e9-9127-496e30861bff.png)
Do you think, that update to Swift 5 will fix it?

**Comment by impul** [comment]
@dnkoutso , I updated project for Xcode 10.2, and CocoaPods to Beta version . 
`https://github.com/essentiaone/Essentia-iOS/tree/feature/avatar-hash-view`

**Comment by amorde** [comment]
Thanks for updating for Xcode 10.2, I'm now able to reproduce what you are seeing.

The reason this is happening is that the target producing the errors (EssModel) is a static library, which is linked to (EssCore), which is linked to the app. But Realm & RealmSwift do not support integration as static libraries, and require dynamic linking. 

I don't think the current configuration of your project will work with Realm - static and dynamic libraries only work together if they do not depend on each other

**Comment by impul** [comment]
@aanand, interesting. But now it works. Develop branch works correctly. 
Do you have any suggestions what I should do now?
