### ISSUE TITLE
The name of a spec should not contain a slash.

### ISSUE THREAD

**Issue by byk04712** [CocoaPods/CocoaPods#8713]
Podfile
```
// ...
    pod 'react-native-pdf', :path => '../node_modules/@polysoft/react-native-pdf'
// ...
```

when i run `pod install`, the error below
```
[!] The `react-native-pdf` pod failed to validate due to 1 error:
    - ERROR | [iOS] name: The name of a spec should not contain a slash.
```

The `react-native-pdf`  name in `package.json` is `@polysoft/react-native-pdf` 

package.json
```
{
    "name": "@polysoft/react-native-pdf",
    "version": "5.0.12",
    "summary": "A react native PDF view component",
    "description": "A react native PDF view component, support ios and android platform",
    "main": "index.js",
    "typings": "./index.d.ts",
    "repository": {
        "type": "git",
        "url": "git+https://github.com/wonday/react-native-pdf.git"
    },
    // ...
}
```

project directory

<img width="247" alt="a" src="https://user-images.githubusercontent.com/6211302/56201562-b83cab00-6073-11e9-94fe-46bb6ac6c89e.png">

How can i resolve this problem and pod install success?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
