### ISSUE TITLE
Version 1.6.1 `public_header_files` file pattern ignored for framework

### ISSUE THREAD

**Issue by yanzhiwei147** [CocoaPods/CocoaPods#8714]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

- Install success.
- In `Pods/Headers/Public/${pod}` directory not empty.

## What happened instead?

In `Pods/Headers/Public/${pod}` directory miss special pod public headers.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.14.3 (18D42)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /Users/arida/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5426b66cd00433d3e8220cbf0397f3e4ab100e3c
```

### Installation Source

```
Executable Path: /Users/arida/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
claide-plugins               : 0.9.2
cocoapods-deintegrate        : 1.0.2
cocoapods-dependencies       : 1.1.0
cocoapods-foundation-headers : 1.0.1
cocoapods-packager           : 1.5.0
cocoapods-plugins            : 1.0.0
cocoapods-podfile_info       : 1.0.0
cocoapods-repo-shard         : 1.0.0
cocoapods-search             : 1.0.0
cocoapods-stats              : 1.0.0
cocoapods-trunk              : 1.3.1
cocoapods-try                : 1.1.0
cocoapods-uploader           : 0.0.2
cocoapods_debug              : 0.1.0
slather                      : 2.4.6
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

project 'DemoProject'
platform :ios, '8.0'

def dependency
    pod 'FrameworkDemo4Arida'
end

def develop_dependency
    # pod 'OCMock', '~> 3.3'
    # pod 'OHHTTPStubs'
end

target 'DemoProjectTests' do
    dependency
    develop_dependency
end
```

## Project that demonstrates the issue

We can put `pod 'FrameworkDemo4Arida'` in Podfile and run `pod install`.

## diff

Now provide the Pods directory diff of 1.5.3 and 1.6.1:

![image](https://user-images.githubusercontent.com/5554220/56206123-343bf080-607e-11e9-9958-dd8cce189298.png)

The right panel directory tree was wrong.

**Comment by amorde** [comment]
Could you post the Podspec that has this issue?

**Comment by yanzhiwei147** [comment]
@amorde Yes, you can get the Podspec file from [here](https://github.com/CocoaPods/Specs/blob/master/Specs/3/a/9/FrameworkDemo4Arida/2.0.0/FrameworkDemo4Arida.podspec.json).

**Comment by paulb777** [comment]
Typically, `public_header_files` is not used in the same podspec with a `vendored_framework`. CocoaPods will generate references to the public headers in the specified framework.

**Comment by dnkoutso** [comment]
That is correct @paulb777.

**Comment by yanzhiwei147** [comment]
@dnkoutso @paulb777 So i can't import public headers when use the `pod 'FrameworkDemo4Arida'`, have some suggest for my public header import correct?

**Comment by yanzhiwei147** [comment]
@dnkoutso Have some suggest to use `FrameworkDemo4Arida`?

**Comment by paulb777** [comment]
Investigate how it's different from podspec's that successfully expose public headers from vendored_frameworks like https://github.com/CocoaPods/Specs/blob/master/Specs/e/2/1/FirebaseAnalytics/5.8.0/FirebaseAnalytics.podspec.json

**Comment by yanzhiwei147** [comment]
Thanks.

**Comment by yanzhiwei147** [comment]
@paulb777 Sorry, this solution not working for me. Now i present our usage(use `FirebaseAnalytics `):

- I have multi development pods(pure framework pod, eg: `Cococapods161library`)
- Integration to unit test target, and framework target ininherit search_paths only(not contain dependency symbols into development pod)
- In `Cococapods161library` development stage, should import `FirebaseAnalytics` pod header.
- I can use `#import <FirebaseAnalytics/FirebaseAnalytics.h>` at target `Cococapods161libraryTests`
- I can't use `#import <FirebaseAnalytics/FirebaseAnalytics.h>` at target `Cococapods161library`, it will report header not found

If you can't understand above steps, you should download attachment and install dependency via cocoapods 1.6.1, after build target `Cococapods161library` you will got the compile error.

[Cococapods161library.zip](https://github.com/CocoaPods/CocoaPods/files/3110849/Cococapods161library.zip)

**Comment by paulb777** [comment]
This looks more like an issue related to `inherit! :search_paths`.  If I move `pod 'FirebaseAnalytics', '5.8.0'` into the `Cococapods161library` target, it builds fine.

**Comment by yanzhiwei147** [comment]
I should not put `pod 'FirebaseAnalytics'` into the `Cococapods161library` target. Here`s why:

- I develop the `Cococapods161library` pod and provide it for other developer.
- While development stage, i use the dependency public headers only, so build the `Cococapods161library` static library will not contain `FirebaseAnalytics` symbols.
- Of course, i Integration the `FirebaseAnalytics` into `Cococapods161libraryTests` target, it will support our unit test work fine.

In any case, i only use the dependency public headers, for this reason i append `Pods/Headers/Public/**` to `Header Search Paths` in `Build Settings`, but this way was broken when upgrade to version 1.6.1.

**Comment by yanzhiwei147** [comment]
@paulb777 Have some milestone discussion result?

**Comment by paulb777** [comment]
@yanzhiwei147 I'm still not understanding the use case.  A statically linked library does not pull in its external library dependencies.

**Comment by yanzhiwei147** [comment]
@paulb777 I upload my demo project tomorrow, please waiting.

**Comment by yanzhiwei147** [comment]
Below is my workflow:

Step 1(for development & test):

- Create a static library call `Cococapods161library `
- Wirte `Podfile` :
```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'Cococapods161libraryTests' do
  pod 'FirebaseAnalytics', '5.8.0'
end
```
- Navigation to `Cococapods161library` target's `Build Settings`,  Append `Pods/Headers/public` to `HEADER_SEARCH_PATHS`
- While development stage, we write code in `Cococapods161library` target, eg:

```objc
// Cococapods161library.h
@interface Cococapods161library : NSObject
+ (void)sayHello;
@end

//Cococapods161library.m
#import <FirebaseAnalytics/FirebaseAnalytics.h>

@implementation Cococapods161library
+ (void)sayHello {
    [FIRAnalytics setUserID:@"my_uid"];
    NSLog(@"Hello My Library!");
}
@end
```

- Write unit test in `Cococapods161libraryTests` target, eg:

```objc
```

Step 2(generate & publish):

- Write `build.sh` to generate fake framework directory struct.
- Navigation to project root path, run `sh build.sh` and generate framework on `output` directory.
- Write `Cococapods161library.podspec` file.
- Put the `Cococapods161library.podspec` and `Cococapods161library.framework` to git repo, and push to remote.
- Publish the `Cococapods161library.podspec` to `Specs` remote.

By this way, i can quick provide many library

**Comment by yanzhiwei147** [comment]
@paulb777 Overall, my workflow designed for pure library development, and publish library via framework rather than source code.

**Comment by yanzhiwei147** [comment]
Should i provide more information?

**Comment by wanhmr** [comment]
Any update?

**Comment by wanhmr** [comment]
![屏幕快照 2019-08-20 下午6 04 44](https://user-images.githubusercontent.com/14258488/63338307-22908f80-c375-11e9-8f44-70b6e0e9ae46.png)
![屏幕快照 2019-08-20 下午6 05 03](https://user-images.githubusercontent.com/14258488/63338308-23292600-c375-11e9-9176-38e4d8137397.png)
![屏幕快照 2019-08-20 下午6 05 32](https://user-images.githubusercontent.com/14258488/63338310-23292600-c375-11e9-98e1-08407e340e5e.png)
version 1.7.5 `public_header_files` file pattern ignored for framework.

**Comment by wanhmr** [comment]
@yanzhiwei147 @paulb777

**Comment by madaoCN** [comment]
include_frameworks default set to false
```
      # @param [Boolean] include_frameworks
      #        Whether or not to include the headers of the vendored frameworks.
      #        Defaults to not include them.
      #
      # @return [Array<Pathname>] the public headers of the specification.
      #
      def public_headers(include_frameworks = false)
        public_headers = public_header_files
        project_headers = project_header_files
        private_headers = private_header_files
        if public_headers.nil? || public_headers.empty?
          header_files = headers
        else
          header_files = public_headers
        end
        header_files += vendored_frameworks_headers if include_frameworks
        header_files - project_headers - private_headers
      end
```

**Comment by madaoCN** [comment]
`next if header.to_s.include?('.framework/') ` will ignore framework headers.

```ruby
# source file : CocoaPods/lib/cocoapods/installer/xcode/pods_project_generator/file_references_installer.rb /Users/liangxiansong/git4Madao/CocoaPods/lib/cocoapods/target/pod_target.rb
# Computes the destination sub-directory in the sandbox
#
# @param  [Sandbox::FileAccessor] file_accessor
#         The consumer file accessor for which the headers need to be
#         linked.
#
# @param  [Array<Pathname>] headers
#         The absolute paths of the headers which need to be mapped.
#
# @return [Hash{Pathname => Array<Pathname>}] A hash containing the
#         headers folders as the keys and the absolute paths of the
#         header files as the values.
#
def header_mappings(file_accessor, headers)
  consumer = file_accessor.spec_consumer
  header_mappings_dir = consumer.header_mappings_dir
  dir = headers_sandbox
  dir += consumer.header_dir if consumer.header_dir

  mappings = {}
  headers.each do |header|
    next if header.to_s.include?('.framework/') # !!!!!!! ignore framework

    sub_dir = dir
    if header_mappings_dir
      relative_path = header.relative_path_from(file_accessor.path_list.root + header_mappings_dir)
      sub_dir += relative_path.dirname
    end
    mappings[sub_dir] ||= []
    mappings[sub_dir] << header
  end
  mappings
end
```
