### ISSUE TITLE
 Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/specs.4.8.gz)

### ISSUE THREAD

**Issue by ricardolousada** [CocoaPods/CocoaPods#8723]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
gem install cocoapods

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
cocoapods to be installed

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
got this error:
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/specs.4.8.gz)

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
Pod is not working i was trying to solve it by running gem install cocoapods (this was recommended regarding this issue
/usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

**Comment by dnkoutso** [comment]
This looks like an issue with Ruby configuration and not CocoaPods. Please ask StackOverflow under `cocoapods` tag.
