### ISSUE TITLE
CocoaPods 1.6.1 not honoring semantic versioning for the first number.

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#8728]
* [x] I've read and understood the [🌈*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Podfile with `pod 'AMPopTip', '~> 0'`.
Run `pod install`.

## What did you expect to happen?
I expected CocoaPods to install version 4.x.x of AMPopTip, following [Semantic Versioning 2.0.0](https://semver.org/).

## What happened instead?
CocoaPods installed version 0.10.2 of AMPopTip, which isn't the latest x.x.x stable release.
This issue only happens with the first number of the version. For instance, if we do `pod 'AMPopTip', '~> 3.0'`, then CocoaPods will correctly install the latest 3.6.0 and not some 3.0.x version.

### Stack
```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 326de7bcd70cc2291fa9fc0d223b24e867335df9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.3.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.3.1
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!

abstract_target 'default_pods' do
    pod 'AMPopTip', '~> 0'
    
    target 'MyApp'
end
```

ps: same issue with CocoaPods 1.7.0 beta 3.

**Comment by segiddins** [comment]
This is the same behavior as rubygems / bundler `~> x` == `>= x` where `x` is a single number

**Comment by Coeur** [comment]
@segiddins OK, you're right on one point, after verification, it's the same behavior as writing `gem 'cocoapods', '~> 0'` (it will install version 0.39 instead of 1.y). But you're incorrect on thinking that `~> x` is the same as `>= x`, because currently `gem 'cocoapods', '~> 0'` will install version 1.6.1.

It's disconcerting, as it means that currently `'~> x'` is the behaving the exact same as `'~> x.0'` but differently from `'~> x.0.0'`. I.e. the rule behind `~>` is different depending on the number of fields.

As it's affecting bundler and doesn't seem like an issue specific to CocoaPods, I'll close that GitHub issue here.
