### ISSUE TITLE
public spec and private spec Same name

### ISSUE THREAD

**Issue by zhuamaodeyu** [CocoaPods/CocoaPods#8735]
hello:  
 i am has a private framework and public framework , public framework spec file exists cocopods public Specs.git , private framewrok spec file exists private Specs.git , 
so i want use private framework , what shoud i do ?  

thanks!  

```
source 'https://github.com/CocoaPods/Specs'
source 'git@github.com:keji/Spec.git' 
target 'TKFrameworkTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TKFrameworkTest
  # 
  pod 'SwiftyJSON'
end

```

 but, this can use public framework. 

 

>

**Comment by dnkoutso** [comment]
Use `pod 'Name', :source => 'git@github.com:keji/Spec.git'` or flip the order at the top.

**Comment by zhuamaodeyu** [comment]
I know you say first  way.  But second way is not work.pod is use cache
