### ISSUE TITLE
Pod repo push podspec to Private git - Error: Git access over HTTP is not allowed

### ISSUE THREAD

**Issue by ankitthakur** [CocoaPods/CocoaPods#8737]
I am succefully able to create pod and run 
`pod lib lint`.
Then I have created local tags and push tag to private git repo.
After that, when we are pushing Repo to private git, it is givine error

`pod repo push git@git.url.com:ankit.thakur/llocalpod.git localpod.podspec`

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777

Validating spec
Username for 'https://git.url.com': ankit.thakur@url.com
Password for 'https://ankit.thakur@url.com@git.url.com':
 -> localpod (0.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://git.url.com/ankit.thakur/localpod.git /var/folders/__/03k8ghwd21z5y_qktvldd2cr0000gp/T/d20190425-1693-1pap2fg --template= --single-branch --depth 1 --branch 0.1.0

Cloning into '/var/folders/__/03k8ghwd21z5y_qktvldd2cr0000gp/T/d20190425-1693-1pap2fg'...
remote: Git access over HTTP is not allowed
fatal: unable to access 'https://git.url.com/ankit.thakur/localpod.git/': The requested URL returned error: 403
) during validation.

[!] The `localpod.podspec` specification does not validate.
```

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

**Comment by ankitthakur** [comment]
No proper response I am receiving from Stackflow.  I have also set my own query. But did not recieved proper solution till now.

https://stackoverflow.com/questions/55862794/cocoapods-pod-repo-push-git

**Comment by ankitthakur** [comment]
Please dont close query without relevant solution shared.

**Comment by amorde** [comment]
Could you provide the output of running `pod repo list`?

Given the error in your output, is looks like an issue with your Git setup

```
Cloning into '/var/folders/__/03k8ghwd21z5y_qktvldd2cr0000gp/T/d20190425-1693-1pap2fg'...
remote: Git access over HTTP is not allowed
fatal: unable to access 'https://git.url.com/ankit.thakur/localpod.git/': The requested URL returned error: 403
) during validation.
```
