### ISSUE TITLE
Cocoapods in iOS Framework

### ISSUE THREAD

**Issue by rivsat** [CocoaPods/CocoaPods#8738]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
I have a MyApp.xcodeworkspace that uses a homegrown MyAppKit iOS framework. MyAppKit is included as xcodeproject inside the parent MyApp project.

I've done the required pod init, pod install in MyAppKit without any errors.

MyAppKit.xcworkspace on its own builds and compiles successfully.

The Podfile in MyAppKit looks like this:
```ruby
platform :ios, '11.0'

target 'MyAppKit' do
  use_frameworks!

  # Pods for MyAppKit
  pod 'Firebase/Core', '~> 5.19'
  pod 'Firebase/ABTesting'
  pod 'Firebase/Performance'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Analytics'
  pod 'GoogleTagManager', '~> 7.1'
  pod 'Google-Mobile-Ads-SDK'
end
```

## What did you expect to happen?

After installing the pods in MyAppKit project and then opening up the parent MyApp.xcworkspace, I expect the project to compile and run.

## What happened instead?

When I include Firebases and Google Tag Manager via CocoaPods in MyAppKit framework and compile the parent project, I get this error.

ld: framework not found Pods_MyAppKit

and a bunch of warnings:-
```
ld: warning: directory not found for option '-F/Users/this.user/Library/Developer/Xcode/DerivedData/MyApp-enzvpdzsyhjszqbnwiclnpszlyri/Build/Products/Debug-iphonesimulator/FirebaseCore'
ld: warning: directory not found for option '-F/Users/this.user/Library/Developer/Xcode/DerivedData/MyApp-enzvpdzsyhjszqbnwiclnpszlyri/Build/Products/Debug-iphonesimulator/FirebaseInstanceID'
ld: warning: directory not found for option '-F/Users/this.user/Library/Developer/Xcode/DerivedData/MyApp-enzvpdzsyhjszqbnwiclnpszlyri/Build/Products/Debug-iphonesimulator/GTMSessionFetcher'
ld: warning: directory not found for option '-F/Users/this.user/Library/Developer/Xcode/DerivedData/MyApp-enzvpdzsyhjszqbnwiclnpszlyri/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac'
ld: warning: directory not found for option '-F/Users/this.user/Library/Developer/Xcode/DerivedData/MyApp-enzvpdzsyhjszqbnwiclnpszlyri/Build/Products/Debug-iphonesimulator/GoogleUtilities'
ld: warning: directory not found for option '-F/Users/this.user/Library/Developer/Xcode/DerivedData/MyApp-enzvpdzsyhjszqbnwiclnpszlyri/Build/Products/Debug-iphonesimulator/Protobuf'
ld: warning: directory not found for option '-F/Users/this.user/Library/Developer/Xcode/DerivedData/MyApp-enzvpdzsyhjszqbnwiclnpszlyri/Build/Products/Debug-iphonesimulator/nanopb'
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/tasvir.rohila/.rbenv/versions/2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7c9a708dce25221eabc35ed39a92524c61ac9ac2
```

### Installation Source

```
Executable Path: /Users/tasvir.rohila/.gem/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by paulb777** [comment]
There's not enough detail to fully assess what is happening here, but one issue is that all of the CocoaPods you are adding are static framework CocoaPods and will not work as dependencies of a dynamic framework target. They can only be dependencies of other static frameworks or an app target.

**Comment by rivsat** [comment]
@paulb777 Thanks for your reply. 
Well, basically we have an app target (MyApp) that uses dynamic framework (MyAppKit). 
MyAppKit has several reusable components used by the app. Until now we were using `Firebase` as a Carthage dependency and `GoogleTagManager` as static library in MyAppKit, which worked well.

Next came the need to upgrade to `GoogleTagManager version 5` which required compatible version of `Firebase`. To better manage these dependencies we want to move to Cocoapods.

Our logic behind adding the Cocoapods in the dynamic framework is that the parent project calls methods on interfaces / classes defined in dynamic framework (MyAppKit). The underlying implementation of calling Firebase, Google Analytics, etc. is encapsulated from the main app target (MyApp).
Whats more this dynamic framework is used in several other app targets and hence has no knowledge of which app targets would use it.

- With this information, do you reckon its possible to achieve what we are trying using Cocoapods
- What, according to you, are possible workarounds so that we are able to use Cocoapods for Firebase and GoogleTagManager.

Thanks,
Tas

**Comment by paulb777** [comment]
Although linking static libraries to dynamic libraries doesn't work in the general case, it might work in some cases where the static libs only get linked into one dynamic library. Potentially there is a change to CocoaPods that would fix that case.

An approach that could work without changing CocoaPods would be to define MyAppKit as a CocoaPods static framework.

**Comment by rivsat** [comment]
In our case we are trying to link the Firebase and GoogleTagManager frameworks into one dynamic framework (MyAppKit). 
>Potentially there is a change to CocoaPods that would fix that case.

**Comment by rivsat** [comment]
@paulb777 
I have integrated Firebase and GoogleTagManager into my iOS app target using Cocoapods. When I build my target, Xcode constantly gives me error:


Showing Recent Messages
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks 

mkdir -p /Users/xxx.xxx/Library/Developer/Xcode/DerivedData/MyApp-enzvpdzsyhjszqbnwiclnpszlyri/Build/Products/Debug-iphonesimulator/MyApp.app/Frameworks


/Users/xxx.xxx/Projects/MyApp/Applications/MyApp/Pods/Target Support Files/Pods-MyApp/Pods-MyApp-frameworks.sh: line 43: source: unbound variable


Command /bin/sh failed with exit code 1
I've cleaned my project multiple times, deleted the derived data folder but none of these seem to work.

My Podfile looks like this:

platform :ios, '11.0'

target 'MyApp' do

  use_frameworks!

  # Pods for MyApp
    pod 'Firebase/Core', '~> 5.19'
    pod 'Firebase/ABTesting'
    pod 'Firebase/Performance'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Analytics'
    pod 'GoogleTagManager', '~> 7.1'
 end
Cocoapods Environment

CocoaPods : 1.5.3
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/xxx.xxx/.rbenv/versions/2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7c9a708dce25221eabc35ed39
What is it that I am missing in my project settings that is causing this error ?

I have spent several days looking for a solution on SO / Cocoapods but in vain.

Any help in this regards would be really appreciated.

**Comment by paulb777** [comment]
@rivsat There were some similar issues in CocoaPods 1.5.x. See https://github.com/CocoaPods/CocoaPods/issues?utf8=%E2%9C%93&q=is%3Aissue+unbound+variable.

If you're still stuck after that, we'll likely need a reproducible sample.
