### ISSUE TITLE
Converting post_install hooks once generate_multiple_pod_projects is set to true

### ISSUE THREAD

**Issue by Panajev** [CocoaPods/CocoaPods#8739]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Request for Help
@sebastianv1   hello :), I have been trying to take advantage of the **generate_multiple_pod_projects** feature and although I have read the original pitch [thread](https://github.com/CocoaPods/CocoaPods/issues/8253) (hopefully well :)) and seen the hints in how to migrate current post install hooks, I am unable to put them in practice successfully:

This is the kind of hooks I am trying to run and convert to CocoaPods post the multiple pod projects flag:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['VALID_ARCHS'] = 'arm64'
      config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      if "#{target.name}" == "XMPPFramework" || "#{target.name}" == "FBSDKCoreKit" || "#{target.name}" == "Bolts" || "#{target.name}" == "Mantle" || "#{target.name}" == "Tune"
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end
    end
  end
end
```
In some cases, I have had to override the deployment target or the Swift version, but it is a variation of the changes above.

It would be really appreciated some help in converting that and maybe adding instructions to the README for 1.7.0. Thank you in advance!

**Comment by sebastianv1** [comment]
@Panajev For `incremental_installation`, we added some new properties to `Pod#Installer` that I would recommend using regardless of whether or not your project actually uses the incremental option.

```ruby
    # @return [Array<Project>] The list of projects generated from the installation.
    #
    attr_reader :generated_projects

    # @return [Array<PodTarget>] The list of pod targets that were generated from the installation.
    #
    attr_reader :generated_pod_targets

    # @return [Array<AggregateTarget>] The list of aggregate targets that were generated from the installation.
    #
    attr_reader :generated_aggregate_targets
```

So for your post-install hook example, replacing `installer.pods_project` with `installer.generated_projects` should prevent any exceptions. It's also worth noting that due to the nature of incremental installation, the post install hook may not get applied to all of your targets as we only install the set of targets that have changed since the last installation. So when adding a new post install hook that you'd like to be applied to all targets in your project right away, you should pass the `--clean-install` flag to `pod install` or `pod update`.

**Comment by Panajev** [comment]
Thank you @sebastianv1 , for completeness (still testing the results), this seems to be what I was looking for (no errors) based on your response:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['VALID_ARCHS'] = 'arm64'
      config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
      if "#{target.name}" == "XMPPFramework" || "#{target.name}" == "FBSDKCoreKit" || "#{target.name}" == "Bolts" || "#{target.name}" == "Mantle" || "#{target.name}" == "Tune"
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end
    end
  end
end
```

**Comment by Panajev** [comment]
> Thank you @sebastianv1 , for completeness (still testing the results), this seems to be what I was looking for (no errors) based on your response:
> 
> ```ruby
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['VALID_ARCHS'] = 'arm64'
>       config.build_settings['VALID_ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
>       if "#{target.name}" == "XMPPFramework" || "#{target.name}" == "FBSDKCoreKit" || "#{target.name}" == "Bolts" || "#{target.name}" == "Mantle" || "#{target.name}" == "Tune"
>         config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
>       end
>     end
>   end
> end
> ```

Mmmhh... it does not throw exceptions but it also does not seem to apply any of those build settings...  I suspect one of those arrays is empty / null and thus skipped... @sebastianv1 , sorry to ask again, but do you have any advice here?

**Comment by RbBtSn0w** [comment]
> --clean-install

Could you expand this detail, event was using this code at the same time.

`
install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

`

How to use --clean-install ?
