### ISSUE TITLE
Bundle Not Found Run 'pod install' to update the copy resources script

### ISSUE THREAD

**Issue by fishcharlie** [CocoaPods/CocoaPods#8744]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Run `pod install`
2. Clean project
3. Build and run

## What did you expect to happen?

1. Build to succeed and application to launch

## What happened instead?

1. Received the following error:

```
error: Resource "/Users/charliefish/Library/Developer/Xcode/DerivedData/MyApp-avelzyufzyaplqamqnsmsosmypsr/Build/Products/Debug-iphonesimulator/MyPrivateCocoaPod/MyPrivateCocoaPodBundle.bundle" not found. Run 'pod install' to update the copy resources script.
```

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin16]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/charliefish/.rbenv/versions/2.2.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3746234fdf8264696245f42f264a400f15404d92
               rrainnCocoaPodsSpec - git@github.com:rrainn/CocoaPods-Spec.git @ b6628d0f9b9888be7b4bd751b06fa8aed086440b
```

### Installation Source

```
Executable Path: /Users/charliefish/.rbenv/versions/2.2.5/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
This isn't quite enough for us to answer your question, I'm afraid you'll need to submit a sample project which reproduces the problem.

**Comment by fishcharlie** [comment]
@orta What do you think would be best way to do that? Is there a private way I can share this project with you, or should I attempt to recreate a sample project? If I attempt to recreate it, I'm not sure if I'll be able to and I'm not sure if it's just something specific to this project.

Also forgot to attach my Podfile, doing that below.

```
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:rrainn/CocoaPods-Spec.git'
platform :ios, '9.0'
#use_frameworks!
use_modular_headers!
inhibit_all_warnings!
 
target 'MyApp' do
  pod 'SwiftyJSON', '4.3.0'
  pod 'IQKeyboardManagerSwift', '6.2.1'
  pod 'Alamofire', '4.8.2'
  pod 'AlamofireImage', '3.5.2'
  pod 'ActionSheetPicker-3.0', '2.3.0'
  pod 'BEMCheckBox', '1.4.1'
  pod 'Siren', '5.0.0'
  pod 'SwipeCellKit', '2.5.4'
  pod 'MyPrivateCocoaPodBundle/Core', '0.7.6'
  pod 'UIGradient', '1.3.1'
end

target 'MyApp Share Extension' do
  pod 'Alamofire', '4.8.2'
  pod 'AlamofireImage', '3.5.2'
  pod 'SwiftyJSON', '4.3.0'
  pod 'MyPrivateCocoaPodBundle/AppExtension', '0.7.6'
end

target 'MyApp iMessage' do
  pod 'SwiftyJSON', '4.3.0'
  pod 'Alamofire', '4.8.2'
  pod 'AlamofireImage', '3.5.2'
  pod 'MyPrivateCocoaPodBundle/AppExtension', '0.7.6'
end

target 'MyAppScreenshots' do
  pod 'SimulatorStatusMagic', '2.4.1'
end
```

**Comment by dnkoutso** [comment]
Just zip up the folder with the .xcodeproj and pods installed.

**Comment by fishcharlie** [comment]
I'm trying to build a project that reproduces the issue. I'm not sure if I'm going to be successful at that. I can't really share the project that has this issue publicly. So trying to reproduce it in a separate project.

While doing that I'm running into a different error:

```
: error: There are multiple stickers icon set or app icon set instances named "AppIcon".
/* com.apple.actool.compilation-results */
/Users/charliefish/Library/Developer/Xcode/DerivedData/TestClientApp-bymamsyojpcmsfaswdojplslazhr/Build/Products/Debug-iphonesimulator/TestClientApp.app/Assets.car
/Users/charliefish/Library/Developer/Xcode/DerivedData/TestClientApp-bymamsyojpcmsfaswdojplslazhr/Build/Intermediates.noindex/TestClientApp.build/Debug-iphonesimulator/TestClientApp.build/assetcatalog_generated_info_cocoapods.plist

/Users/charliefish/Desktop/TestClientApp/Pods/Target Support Files/Pods-TestClientApp/Pods-TestClientApp-resources.sh: line 7: realpath: command not found
:133: error: Unexpected failure
```

Attached below is the ZIP file for that error.

[Archive.zip](https://github.com/CocoaPods/CocoaPods/files/3135235/Archive.zip)

**Comment by MarcSteven** [comment]
@orta  Yeah I also meet this issue ,I did nothing ...

**Comment by Hext123** [comment]
I also encountered this mistake

/Users/hext/Desktop/SaicPushKit/Pods/Target Support Files/Pods-SaicPushKitDemo/Pods-SaicPushKitDemo-resources.sh: line 7: realpath: command not found
:315: error: Unexpected failure

**Comment by pionl** [comment]
After upgrading to Catalina same issue -- `realpath` is not available. `brew install coreutils` fixed the issue.
