### ISSUE TITLE
use_frameworks Code Signing Error: package_info does not support provisioning profiles

### ISSUE THREAD

**Issue by DavidYang1121** [CocoaPods/CocoaPods#8750]
When i use xcodebuild, podfile set use_frameworks!，archive log is "Code Signing Error: package_info does not support provisioning profiles. package_info does not support provisioning profiles", after i set config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'， but 
the log show "error: exportArchive: device_info.framework does not support provisioning profiles", please help, thank you!

**Comment by DavidYang1121** [comment]
@kommen @lukeredpath @farcaller @aanand

**Comment by farcaller** [comment]
fyi: it's generally not useful to cc random people to the tickets.

**Comment by orta** [comment]
That said, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
