### ISSUE TITLE
Is it possible to check if my project pods are available in a swift version all at once?

### ISSUE THREAD

**Issue by fenixsolorzano** [CocoaPods/CocoaPods#8751]
My project has many dependencies (~10), I would like to check if the pods installed in are available in swift 5 by running a command, is there any command available? If not a command is there any other way?

**Comment by dnkoutso** [comment]
There is none at the moment. It can probably be done in a pre or post install hook as a check.

I am going to close this issue and we can continue a discussion here. I will re-open if we identify a bug or enhancement we want to do here.

**Comment by fenixsolorzano** [comment]
As swift evolves some pods evolve too, some apis change with break changes, it would be nice to have a way to check if the pods in the current project are available for a specific swift version.
