### ISSUE TITLE
Cannot build watchOS library in watchOS library

### ISSUE THREAD

**Issue by worldofnick** [CocoaPods/CocoaPods#8760]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I am the developer of a iOS/watchOS library and I have published this library and can use it without any problems inside of a iOS and watchOS app. However, when I create a new watchOS static library and attempt to `pod install` my library I get a warning message:

`[!] The Podfile contains framework or static library targets (MyLib), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).`

I ignored it at first and I am able to open Xcode and use the library inside of my new watchOS static lib, everything builds fine. 

However, when I try to build my library from the command line I get an error:

```
[x] error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-MyLib_watchOS



[x] error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-MyLib_watchOS is not an object file (not allowed in a library)


** BUILD FAILED **
```

My Xcode build command looks like:
```
set -o pipefail && \
	xcodebuild -configuration Release \
		-workspace MyWorkspace.xcworkspace \
		-scheme MyLib_watchOS \
		-sdk watchsimulator \
		-arch x86_64 \
		-derivedDataPath /Users/nporter/Developer/iOS/iOS-Platform/MyLib/bin/watchOS/build_temp/ \
		WATCHOS_DEPLOYMENT_TARGET=3.0 GCC_TREAT_WARNINGS_AS_ERRORS=YES GCC_GENERATE_DEBUGGING_SYMBOLS=NO STRIP_INSTALLED_PRODUCT=YES STRIP_STYLE=ALL GCC_PREPROCESSOR_DEFINITIONS='CC_PREPROCESSOR_DEFINITIONS NDEBUG=1 NS_BLOCK_ASSERTIONS=1 COMPILEFORAPP' \
		| /Users/nporter/Developer/iOS/iOS-Platform/MyLib/tools/xcpretty/bin/xcpretty --no-color --no-utf
```

For reference the podspec of my library looks similar to:
```
Pod::Spec.new do |s|
  s.name         = "MyLib"
  s.version      = "0.0.0.34"
  # ...
  s.ios.deployment_target = '10.0'
  s.watchos.deployment_target = '3.0'

  s.ios.vendored_libraries = "iOS/libMyLib_iOS.a"
  s.ios.frameworks = "UIKit", "SystemConfiguration", "WebKit", "UserNotifications"
  s.ios.libraries = "sqlite3.0", "z", "c++"
  s.ios.source_files = "iOS/include/*.h"

  s.watchos.vendored_libraries = "watchOS/libMyLib_watchOS.a"
  s.watchos.frameworks = "UIKit", "UserNotifications", "WatchKit"
  s.watchos.libraries = "sqlite3.0", "z", "c++"
  s.watchos.source_files = "watchOS/include/*.h"

end
```

And the Podfile for my other static watchOS lib looks like:
```
platform :ios, '10.0'

workspace 'MySecondLib'
project 'MySecondLib.xcodeproj'

target 'MySecondLib_iOS' do
    pod 'MyLib'
end

target 'MySecondLib_watchOS' do
  platform :watchos, '3.0'
  pod 'MyLib'
end

end
```

## What did you expect to happen?

I expected no warning to appear when installing my pods, and I expected my build command to work the same it does for iOS. I noticed one of the first lines of output after running my build command for iOS is `> Aggregate Pods/ACPCoreWatch_Staging-iOS [Release]` however, I see no such aggregate command running when I try to build my watchOS lib.

## What happened instead?

Instead, I can build inside of Xcode, but cannot build via my Xcode build command.

### Stack

```
   CocoaPods : 1.6.0.beta.2
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5e8a21b86c882987c2a994ea085ea1cabd3e0357
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/worldofnick/WatchLibTest

**Comment by aleksandergrzyb** [comment]
How did you solve this issue? 🙂
