### ISSUE TITLE
what's wrong with it

### ISSUE THREAD

**Issue by tangjinzhao** [CocoaPods/CocoaPods#8769]
pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `audioplayers` from `.symlinks/plugins/audioplayers/ios`
Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
Fetching podspec for `contact_picker` from `.symlinks/plugins/contact_picker/ios`
Fetching podspec for `flutter_alipay` from `.symlinks/plugins/flutter_alipay/ios`
Fetching podspec for `flutter_baidu_map` from `.symlinks/plugins/flutter_baidu_map/ios`
Fetching podspec for `flutter_sound` from `.symlinks/plugins/flutter_sound/ios`
Fetching podspec for `fluwx` from `.symlinks/plugins/fluwx/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `imsdk` from `.symlinks/plugins/imsdk/ios`
Fetching podspec for `medias_picker` from `.symlinks/plugins/medias_picker/ios`
Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
Fetching podspec for `webview_flutter` from `.symlinks/plugins/webview_flutter/ios`
Downloading dependencies
Installing AliPay (2.1.2)
Installing BMKLocationKit (1.0.1)
Installing Flutter (1.0.0)
Installing Gallery (2.0.5)
Installing SVProgressHUD (2.2.2)
Installing audioplayers (0.0.1)
Installing camera (0.0.1)
Installing contact_picker (0.0.1)
Installing flutter_alipay (0.0.1)
Installing flutter_baidu_map (0.0.1)
Installing flutter_sound (0.0.1)
Installing fluwx (0.0.1)
Installing image_picker (0.0.1)
Installing imsdk (0.0.1)
Installing medias_picker (0.0.1)
Installing package_info (0.0.1)
Installing path_provider (0.0.1)
Installing permission_handler (2.1.0)
Installing shared_preferences (0.0.1)
Installing url_launcher (0.0.1)
Installing video_player (0.0.1)
Installing webview_flutter (0.0.1)
Generating Pods project
Integrating client project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G6030)
       Xcode : 10.1 (10B61)
         Git : git version 2.6.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ bb16ff168c626b30ffb941e8eb124bb29aa82d05
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '10.0'

#use_modular_headers!

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  use_frameworks!  

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

### Error

```
RuntimeError - Unsupported workspace file reference type `build`
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace/file_reference.rb:74:in `absolute_path'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:201:in `block in load_schemes'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:200:in `each'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:200:in `load_schemes'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:85:in `from_s'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/xcodeproj-1.8.1/lib/xcodeproj/workspace.rb:66:in `new_from_xcworkspace'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:93:in `create_workspace'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/user_project_integrator.rb:64:in `integrate!'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:645:in `block in integrate_user_project'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:642:in `integrate_user_project'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:141:in `install!'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
/usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Unsupported+workspace+file+reference+type+%60build%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Resources installed using cocoapods not loaded for xctest bundle
   https://github.com/CocoaPods/CocoaPods/issues/4752 [closed] [47 comments]
   31 Jul 2018

 - Allow :local in podfile
   https://github.com/CocoaPods/CocoaPods/issues/178 [closed] [38 comments]
   22 Nov 2015

**Comment by dnkoutso** [comment]
Please upload sample app.

**Comment by tangjinzhao** [comment]
> Please upload sample app.

ok

**Comment by elliott-io** [comment]
Having the same problem.
