### ISSUE TITLE
Claim Pod (Tesseract)

### ISSUE THREAD

**Issue by ypopovych** [CocoaPods/CocoaPods#8771]
Hello,

My name is Yehor. I’m CTO of Tesseract dApps Platform.

We are working on the set of libraries for different platforms, iOS and OS X are part of them.
I found out, that “Tesseract” name is taken on CocoaPods.

It’s taken by an outdated library, released in 2012.

I contacted the library owner (@ldiqual), he doesn’t want to support it, and even forgot about this Pod at all.

Can we somehow get this name?

Right now the library doesn’t have maintainer at all (Unclaimed).

**Comment by dnkoutso** [comment]
Please use https://trunk.cocoapods.org/claims/new
