### ISSUE TITLE
Can I copy Development Pods to Pods directory?

### ISSUE THREAD

**Issue by chaoskyme** [CocoaPods/CocoaPods#8775]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`
pod 'Sample', :path => '../xxx'

## What did you expect to happen?

I hope pod install local Development Pods as other normal pods, Development Pods  can move to Pods directory and not in local directory.

**Comment by amorde** [comment]
The idea with the local pods feature is that they are pods that are in active development in parallel with the app they are installed in. This means the source code may be in a totally different SCM repository, or maybe in the same folder as the app code.

While this option _could_ be added I don't see it happening personally. Could you explain why you want development pods in the `Pods` directory rather than using a spec repo?

**Comment by chaoskyme** [comment]
Hi, thanks for replay. Because I develop app with flutter, flutter's pods are located in my machine directory and pods' reference is absolute path, if other persons aren't install flutter environment, they will not compile pass. And then if development pods in the Pods directory, I can commit pods code to SCM and they don't need install flutter environment.

**Comment by amorde** [comment]
There shouldn’t be any absolute paths when using local pods - is it possible there’s something about Flutter or your Podfile that is putting absolute paths? Could you share an example?

**Comment by chaoskyme** [comment]
In the Flutter `podhelper.rb` file have under code, it's  absolute paths.
![WX20190508-103328](https://user-images.githubusercontent.com/1863204/57345273-cf575000-717c-11e9-884d-b6bff51c5373.png)

**Comment by amorde** [comment]
`:path` accepts relative paths - I recommend modifying your Podfile to use relative paths which should resolve the issue you are experiencing.

Based on this, I'm going to go ahead and close this as this doesn't seem like an issue with CocoaPods, nor does it seem like something we plan to change. Thanks!

**Comment by chaoskyme** [comment]
@amorde  Hi, the key problem isn't relative path, I want move Development Pods to `Pods` directory, can I modify CocoaPods to change? Thanks!

**Comment by amorde** [comment]
Sorry, I don't imagine that is something we would want to support. I don't understand the use case.

If you are trying to keep all the source code in one repo, that is possible using `:path` - it doesn't need to be in the `Pods` folder
