### ISSUE TITLE
Ten minutes resolving dependencies

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#8777]
cd ~/.cocoapods/repos/master
git checkout 64ced5b17d6f030d6a5a50099e0e238edc2d591f

Add the following to a Podfile:

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Firestore'
  pod 'SDWebImage'

 /usr/bin/time pod update --no-repo-update  --verbose
Update all pods
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-AnalyticsExample`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-AnalyticsExampleTests`: (``)

Resolving dependencies of `Podfile`

**Wait 10 minutes**

< More logs deleted>

      603.58 real       595.56 user         4.87 sys

**Comment by paulb777** [comment]
This isn't the highest priority since we triggered this by pushing a Firebase without an accompanying FirebaseUI and it took a lot of searching in Molinillo to determine that the latest Firebase could be used with an ancient FirebaseUI.  We're going to solve this in the practical case by pushing an updated FirebaseUI.

Still it would be nice for CocoaPods to give some feedback that the recent podspec combinations aren't working and its going into deep search mode long before 10 minutes pass.

**Comment by segiddins** [comment]
Would be nice, but honestly we should just profile and figure out a way to optimize this case IMO

**Comment by paulb777** [comment]
Closing because of low priority.
