### ISSUE TITLE
Allowing summary or description for a subspec?

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#8778]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I want to have a description for my subspec. So I wrote:
```
sp.summary  = 'A cool subspec to do foo bar'
sp.description  = 'This is a cool subspec, made with love, to do foo bar'
```

Then I did:
`pod lib lint`

## What happened?

- ERROR | attributes: Can't set `summary` attribute for subspecs (in `Example/SubExample`).
- ERROR | attributes: Can't set `description` attribute for subspecs (in `Example/SubExample`).

Are there alternatives to describe a subspec?

## CocoaPods Environment

CocoaPods 1.6.1.

**Comment by dnkoutso** [comment]
I can see that maybe as an enhancement

**Comment by orta** [comment]
I’m interested in where we’d show this if it was supported?

**Comment by Coeur** [comment]
@orta Could be seen:
- on the website https://cocoapods.org/pods/SwiftImageEffects
- on the JSON version of the podspec
- on some command outputs like a `pod doc SwiftImageEffects`

**Comment by Coeur** [comment]
@stale: this feature request hasn't been implemented yet.

**Comment by Coeur** [comment]
@Stale: this feature request hasn't been implemented yet.

**Comment by Coeur** [comment]
@Stale: this feature request hasn't been implemented yet.
