### ISSUE TITLE
Unexpected folder reference of `Pods` group in `.xcodeproj` does not give a warning or other notice in `pod deintegrate` or `pod install`

### ISSUE THREAD

**Issue by SpacyRicochet** [CocoaPods/CocoaPods#8779]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## TLDR

If for any reason, the `Pods` group in an Xcode project is referencing an unexpected file (for example, because you moved the Podfile and generate the Pods from another directory), `pod deintegrate` and `pod install` will not touch the group, except to add configuration file references, as if everything is okay.

However, Xcode may throw warnings, because the configuration file's paths are incorrect.

## What did you do?

1. Open sample project.
  * `InternalFramework.xcproj` has a `Pods` group that points to `Pods (relative to group)` as opposed to `../Pods (relative to group)`.
2. Do a `pod install` in the sample project's root folder.
3. Do a `pod deintegrate frameworks/InternalFramework.xcodeproj`

## What did you expect to happen?

Every trace to Pods being removed from `InternalFramework.xcodeproj` – **including the `Pods` group** – with the following console output;

```
> pod deintegrate frameworks/InternalFramework.xcodeproj

Deintegrating `frameworks/InternalFramework.xcodeproj`
Deleted 1 'Check Pods Manifest.lock' build phases.
- Pods_InternalFramework.framework
- Pods-InternalFramework.debug.xcconfig
- Pods-InternalFramework.release.xcconfig
- Pods-InternalFramework.anotherrelease.xcconfig
Deleted 1 empty `Pods` groups from project.
Deleted 1 empty `Frameworks` groups from project.
Removing `Pods` directory.

Project has been deintegrated. No traces of CocoaPods left in project.
Note: The workspace referencing the Pods project still remains.
```

**Or alternatively** a warning in the console output that states the 'Pods' group has been left alone.

## What happened instead?

The Pods group was not removed. This is not mentioned specifically in the console output, though the usual line is omitted (so it could've been inferred.)

```
> pod deintegrate frameworks/InternalFramework.xcodeproj

Deintegrating `frameworks/InternalFramework.xcodeproj`
Deleted 1 'Check Pods Manifest.lock' build phases.
- Pods_InternalFramework.framework
- Pods-InternalFramework.debug.xcconfig
- Pods-InternalFramework.release.xcconfig
- Pods-InternalFramework.anotherrelease.xcconfig
Deleted 1 empty `Frameworks` groups from project.
Removing `Pods` directory.
```

## Project setup

**Folder structure**

```
- Project
  - apps
    - AppA
      - AppB.xcproj
    - AppB
      - AppB.xcproj
  - frameworks
    - Frameworks.xcproj
  - podstest.xcworkspace
  - Podfile
```

**Podfile**

```
workspace 'podstest'
platform :ios, '10.3'
inhibit_all_warnings!
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'AppA' do
    project 'apps/AppA/AppA'

    pod 'Braintree'
    # more pods
end

target 'AppB' do
    project 'apps/AppB/AppB'

    pod 'Braintree'
    # more pods
end

target 'InternalFramework' do
    project 'frameworks/InternalFramework'

    pod 'Braintree'
    # more pods
end
```

## Workarounds

* Remove `Pods` group manually and do a `pod install`, or…
* Change the folder reference of the `Pods` group to the correct folder.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.21.0
Ruby lib dir : /Users/brunoscheele/.rbenv/versions/2.6.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9b3ad06162c31785b203a27de94144b0c936c184
               parkmobile - ssh://git@stash-ssh.parkmobile.com:7999/globiosf/podspecrepo.git @ 6d2c2b63004775b1988fa8e0c8b4509e6f3ab8a1
               parkmobile-podspecrepo - ssh://git@stash-ssh.parkmobile.com:7999/globiosf/podspecrepo.git @ 6d2c2b63004775b1988fa8e0c8b4509e6f3ab8a1
```

### Installation Source

```
Executable Path: /Users/brunoscheele/.rbenv/versions/2.6.0/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
workspace 'podstest'
platform :ios, '10.3'
inhibit_all_warnings!
use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'PodsConfigurationTest' do
    project 'apps/podconfigurationtest/PodsConfigurationTest'

    pod 'Braintree'
end

target 'InternalFramework' do
    project 'frameworks/InternalFramework'

    pod 'Braintree'
end
```

## Project that demonstrates the issue

[PodsConfigurationTest.zip](https://github.com/CocoaPods/CocoaPods/files/3157558/PodsConfigurationTest.zip)

Note that when opening `podstest.xcworkspace`, the InternalFramework already has a Pods group, pointing to a different place than CocoaPods will place the configuration files.

## Suggested fixes

* Add warning console output that indicates the 'Pods' group was not touched by `pod deintegrate`.
* Update `pod install` to add a warning console output that the 'Pods' group is unexpected.

**Comment by dnkoutso** [comment]
Thanks! Hoping someone (or me) can find time to dig through this.

**Comment by dnkoutso** [comment]
Repo where cocoapods-deintegrate resides https://github.com/CocoaPods/cocoapods-deintegrate and probably where the fix needs to happen.
