### ISSUE TITLE
podspec won't validate due to forward class declaration

### ISSUE THREAD

**Issue by testower** [CocoaPods/CocoaPods#878]
I am trying to create a pod from a static library I am working on. The library itself has a pod dependency to AFNetworking. What is the proper way to do this? I suspect I have done something wrong with respect to this because I am getting the following message from pod spec lint:

 -> WPJsonApiHandler (0.0.1)
    - ERROR | XCODEBUILD >  WPJsonApiHandler/WPJsonApiHandler/WPJsonApiHandler.m:54:42: error: receiver 'AFJSONRequestOperation' for class message is a forward declaration
    - ERROR | XCODEBUILD >  WPJsonApiHandler/WPJsonApiHandler/WPJsonApiHandler.m:54:41: error: no known class method for selector 'JSONRequestOperationWithRequest:success:failure:'
    - ERROR | XCODEBUILD >  WPJsonApiHandler/WPJsonApiHandler/WPJsonApiHandler.m:64:6: error: receiver type 'AFJSONRequestOperation' for instance message is a forward declaration
    - NOTE  | XCODEBUILD >  WPJsonApiHandler/WPJsonApiHandler/WPJsonApiHandler.h:27:8: note: forward declaration of class here
    - NOTE  | XCODEBUILD >  WPJsonApiHandler/WPJsonApiHandler/WPJsonApiHandler.h:27:8: note: forward declaration of class here

Analyzed 1 podspec.

[!] The spec did not pass validation.

Also it seems to comment on my forward class declaration in front of my protocol declaration in the header file (not related to AFNetworking).

**Comment by jvelascovanadis** [comment]
Hi, Im'm facing the same issue so I can't validate my podspec due to a UIActivityIndicatorView+AFNetworking.h' file not found message. So, testowe can you explain how could you finally fix this?
