### ISSUE TITLE
Data missing closing  when pod install

### ISSUE THREAD

**Issue by MarcSteven** [CocoaPods/CocoaPods#8784]
―― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.6.4
Ruby lib dir : /Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib
Repositories : artsy - https://github.com/Artsy/Specs.git @ 9cb037d588b443729d0b35d2bea523183a084753
               master - https://github.com/CocoaPods/Specs.git @ ea9da031d401dcbc8300b048be6af41c5ffa21fb
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform:ios , "11.0"
use_frameworks!
target "MemoryChain" do
    pod 'RxSwift','~> 5'
    pod 'RxCocoa','~> 5'

    pod 'Crashlytics'
    pod 'Fabric'

    pod 'Kingfisher', '~> 5.4.0'



    pod 'SnapKit','~> 5'


    pod 'SnapKit'

    #cloud service to collect mobile application log
    pod 'Reveal-iOS-SDK'
    pod 'IQKeyboardManagerSwift'
	end
    target "MemoryChainTests" do

        pod 'RxBlocking', '~> 5'
        pod 'RxTest', '~> 5'




end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Data missing closing '>'
    #  -------------------------------------------
    #  				CLANG_ENABLE_MODULES = YES;
    #  				CODE_SIGN_STYLE = Automatic;
2107>  <<<<<<< HEAD
        ^
    #  				DEVELOPMENT_TEAM = NGJVXQWTLX;
    #  				FRAMEWORK_SEARCH_PATHS = (
    #  -------------------------------------------

/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:208:in `parse_data'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:136:in `parse_object'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:187:in `parse_dictionary'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:193:in `parse_dictionary'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/xcodeproj-1.9.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/xcodeproj-1.9.0/lib/xcodeproj/project.rb:112:in `open'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1025:in `block (2 levels) in inspect_targets_to_integrate'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1024:in `each'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1024:in `block in inspect_targets_to_integrate'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:1019:in `inspect_targets_to_integrate'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:96:in `analyze'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
/Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/pod:23:in `load'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/pod:23:in `<main>'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Data+missing+closing+%27%3E%27%0A++++%23++-------------------------------------------%0A++++%23++%09%09%09%09CLANG_ENABLE_MODULES+%3D+YES%3B%0A++++%23++%09%09%09%09CODE_SIGN_STYLE+%3D+Automatic%3B%0A2107%3E++%3C%3C%3C%3C%3C%3C%3C+HEAD%0A++++++++%5E%0A++++%23++%09%09%09%09DEVELOPMENT_TEAM+%3D+NGJVXQWTLX%3B%0A++++%23++%09%09%09%09FRAMEWORK_SEARCH_PATHS+%3D+%28%0A++++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Traceback (most recent call last):
	14: from /Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
	13: from /Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	12: from /Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/pod:23:in `<main>'
	11: from /Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/bin/pod:23:in `load'
	10: from /Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
	 9: from /Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
	 8: from /Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
	 7: from /Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	 6: from /Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	 5: from /Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:67:in `report_error'
	 4: from /Users/zhaoxinqiang/.rvm/gems/ruby-2.5.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	 3: from /Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	 2: from /Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	 1: from /Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:34:in `search'
/Users/zhaoxinqiang/.rvm/rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:95:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError

**Comment by dnkoutso** [comment]
You have an unresolved conflict inside your pbxproj.

Please use StackOverflow under `cocoapods` tag.

**Comment by MarcSteven** [comment]
@dnkoutso Thank for your feedback ,I think I find the issue.sorry to disturb your time...
