### ISSUE TITLE
installed cocoapods -v 1.5.3, however, I'm still getting these errors. What should I do?

### ISSUE THREAD

**Issue by divinzer** [CocoaPods/CocoaPods#8795]
installed cocoapods -v 1.5.3, however, I'm still getting these errors. What should I do?

[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `native_target' for <Pod::PodTarget name=Amplitude-iOS >:Pod::PodTarget

/Users/iryna/Documents/Projects/civic-champs-client/ios/Podfile:137:in `block (4 levels) in from_ruby'
/Users/iryna/Documents/Projects/civic-champs-client/ios/Podfile:121:in `each'
/Users/iryna/Documents/Projects/civic-champs-client/ios/Podfile:121:in `block (3 levels) in from_ruby'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-core-1.7.0.beta.3/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:836:in `run_podfile_post_install_hook'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:824:in `block in run_podfile_post_install_hooks'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/user_interface.rb:145:in `message'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:823:in `run_podfile_post_install_hooks'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:309:in `block in create_and_save_projects'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:290:in `create_and_save_projects'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:281:in `generate_pods_project'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/installer.rb:159:in `install!'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/command/install.rb:51:in `run'
/Users/iryna/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/lib/cocoapods/command.rb:52:in `run'
/Users/iryna/.rvm/gems/ruby-2.6.0/gems/cocoapods-1.7.0.beta.3/bin/pod:55:in `<top (required)>'
/Users/iryna/.rvm/gems/ruby-2.6.0/bin/pod:23:in `load'
/Users/iryna/.rvm/gems/ruby-2.6.0/bin/pod:23:in `<main>'

**Comment by dnkoutso** [comment]
You have a `post_install` hook in your `Podfile`. Please update it as the non-public API has changed.
