### ISSUE TITLE
"Command PhaseScriptExecution failed with a nonzero exit code" - Doesn't respect single quote at target's name

### ISSUE THREAD

**Issue by ericleiyang** [CocoaPods/CocoaPods#8796]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Create a project named: Testers' app
- run "Pod install" to install all libs
- Build and run the app

## What did you expect to happen?

Build and run the app correctly

## What happened instead?

Got error: Command PhaseScriptExecution failed with a nonzero exit code.

## CocoaPods Environment

Pod 1.6.1

Proposed solution:

line 117 at Testers' app-frameworks.sh
`local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements '$1'"`

should be changed to 
`local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements \"$1\""`

to respect the single quote at the target name.

**Comment by dnkoutso** [comment]
Known issue see https://github.com/CocoaPods/CocoaPods/pull/8709.

Dup of https://github.com/CocoaPods/CocoaPods/issues/8703
