### ISSUE TITLE
Sandbox::PodDirCleaner::clean_paths is too slow then pod contains large amount of files

### ISSUE THREAD

**Issue by hovox** [CocoaPods/CocoaPods#8797]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Calling `bundle exec pod install` takes too much time to complete. Most of the time it hangs out on this nested loop in `clean_paths` method:

```
files.reject do |candidate|
          candidate = candidate.downcase
          candidate.end_with?('.', '..') || cached_used.any? do |path|
            path = path.downcase
            path.include?(candidate) || candidate.include?(path)
          end
        end
```

Digging deeper I have found that I can disable cleaning by specifying :
```
install! "cocoapods",
          :clean => false
```
`:clean => false` in my `Podfile`, but doing that will disable CocoaPods caches and `pod install` will take longer when I remove `Pods` folder.
Can't we use `Set` data structure or optimize this nested loop ? Can you help me understand why we need to check both `path.include?(candidate) || candidate.include?(path)` ?

## What did you do?

`bundle exec pod install`

## What did you expect to happen?

I expect install finish within 30 seconds or a minute max.

## What happened instead?

Install hangs out more then 2 minutes

## CocoaPods Environment

I have tried with cocoapods 1.5.2,1.7.0.rc1 versions

**Comment by hovox** [comment]
changing code to this improved performance by a margin, is it okey solution ? I can open a pull request:

```
def clean_paths
        cached_used = used_files.map do |path|
          path.downcase
        end
        glob_options = File::FNM_DOTMATCH | File::FNM_CASEFOLD
        files = Pathname.glob(root + "**/*", glob_options).map(&:to_s)

        cached_used_set = cached_used.to_set
        result = files.reject do |candidate|
          candidate = candidate.downcase
          candidate.end_with?(".", "..") || cached_used_set.include?(candidate) || cached_used.any? do |path|
            path.include?(candidate) || candidate.include?(path)
          end
        end
        return result
      end
```

I have added `cached_used_set` and befoer checking by `any?` I'm checking if `candidate` includes in `cached_used_set`.

**Comment by dnkoutso** [comment]
How much does it improve it by?

If there is sufficient test coverage open up a PR.

**Comment by hovox** [comment]
Time get down from 47 seconds to 7 seconds by this optimization on my 2017 MacBook pro. We have 15.000 files in that pod. I do not know how to create a test case. Should I check that everything work as before or should I test for performance or both ?

**Comment by dnkoutso** [comment]
Open up the PR and I will also test it on our project!

**Comment by hovox** [comment]
Hey @dnkoutso , here is a pull request, please let me know in case I need to change anything, thanks.

https://github.com/CocoaPods/CocoaPods/pull/8799
