### ISSUE TITLE
Unknown installation options: generate_multiple_pod_projects and incremental_installation

### ISSUE THREAD

**Issue by chaoskyme** [CocoaPods/CocoaPods#8801]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

When I run `pod install` in the `examples/MultiXcodeProject Example` directory, there is an error `Unknown installation options: generate_multiple_pod_projects and incremental_installation.`

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.21.0
Ruby lib dir : /Users/qinming/.rvm/rubies/ruby-2.6.2/lib
Repositories : facebook - https://github.com/facebook/Sonar.git @ d044ae991faf6814235b4b149c5a7068c9f61ee3
               gxm - https://git.guoxiaomei.cn/ios/Specs.git @ 0cf073a0948787b4a72d62d751f95508e3be0d5a
               master - https://github.com/CocoaPods/Specs.git @ b0d9ddda54667bea515c0007936b08059bfa9f6b
```

### Installation Source

```
Executable Path: /Users/qinming/.rvm/gems/ruby-2.6.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
workspace 'Examples.xcworkspace'
platform :ios, '9.0'

install! 'cocoapods',
	 generate_multiple_pod_projects: true,
	 incremental_installation: true

target 'MultiXcodeProject' do
  pod 'Coffee', path: 'Coffee/Coffee.podspec'
  pod 'CoffeeMachine', path: 'CoffeeMachine/CoffeeMachine.podspec'

  target 'MultiXcodeProjectTests' do
    inherit! :search_paths
  end

  target 'MultiXcodeProjectUITests' do
    inherit! :search_paths
  end
end

target 'MultiXcodeProjFrameworks' do
  use_frameworks!
  pod 'Coffee', path: 'Coffee/Coffee.podspec'
  pod 'CoffeeMachine', path: 'CoffeeMachine/CoffeeMachine.podspec'
end

ENV['COCOAPODS_DISABLE_STATS'] = 'true'
```

## Project that demonstrates the issue

<https://github.com/CocoaPods/CocoaPods/tree/master/examples/MultiXcodeProject%20Example>

**Comment by dnkoutso** [comment]
Please use CocoaPods 1.7.0 as those options only exist in that version.

**Comment by chaoskyme** [comment]
@dnkoutso Thank you very much.

**Comment by Usipov** [comment]
I have the same issue with cocoapods 1.8.4
```
$ pod _1.8.4_ install
[!] Unknown installation options: generate_multiple_pod_projects and incremental_installation.
```
any ideas?

**Comment by paulb777** [comment]
@Usipov Check ` pod _1.8.4_  --version` to make sure that your Ruby configuration is really getting the 1.8.4 version.

**Comment by Usipov** [comment]
hm...

```
$  pod _1.8.4_ --version
1.5.3
```

Can you please say ho to set the correct version?

**Comment by paulb777** [comment]
Depends upon your setup - but perhaps `gem install cocoapods -v 1.8.4 --user-install`
