### ISSUE TITLE
Incompatible version, due to minimum_deployment_target, of transient dependency pulled in

### ISSUE THREAD

**Issue by icecrystal23** [CocoaPods/CocoaPods#8808]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Pod A has min target of iOS 9.0
Pod B at v3 has min target of iOS 9.0, at v4 has min target of iOS 10.0
Pod A depends on Pod B.
Podfile depends on Pod A
Podfile with deployment target 9.0 pulls in compatible v3 of Pod B
Podfile with deployment target 10.0 pulls in v4 of Pod B
- This fails to compile because Pod A can't import v4 of Pod B

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Podfile with deployment target 9.0 pulls in compatible v3 of Pod B
Podfile with deployment target 10.0 pulls in v4 of Pod B
- This fails to compile because Pod A can't import v4 of Pod B

## CocoaPods Environment

pod env output anonymized

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1
Ruby lib dir : /Users/me/.rbenv/versions/2.5.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3b67e8d7e7155126856cdb53ce133bd8f1a11431
               internal_repo - url to internal repo
```

### Installation Source

```
Executable Path: /Users/me/.rbenv/versions/2.5.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate       : 1.0.4
cocoapods-framework_builder : 0.0.1
cocoapods-plugins           : 1.0.0
cocoapods-search            : 1.0.0
cocoapods-stats             : 1.1.0
cocoapods-trunk             : 1.3.1
cocoapods-try               : 1.1.0
```

## Project that demonstrates the issue

Currently I can only reproduce the issue with proprietary projects.  I am having trouble finding public Pods with the right conditions to reproduce the issue.

**Comment by amorde** [comment]
@icecrystal23 is it the case that PodA has a deployment target of iOS 9.0, but would theoretically work if compiled for iOS 10.0?

If so, then yes this would be resolved by https://github.com/CocoaPods/CocoaPods/pull/8743

**Comment by icecrystal23** [comment]
Possibly, but that doesn’t seem like a good solution since not all libraries will compile for a higher minimum deployment version. 

The version resolver should realize that it needs v3 of Pod B to meet the requirements of all project dependencies.
