### ISSUE TITLE
Regression resources of test targets missing

### ISSUE THREAD

**Issue by mfiebig** [CocoaPods/CocoaPods#8813]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod install` with one of the pods containing a test target, that relies on resources bundled with the test target.

## What did you expect to happen?

The resources should be available within the test bundle.

## What happened instead?

Target is missing the test resources. `-resources.sh` is also missing the files.

### Stack

```
   CocoaPods : 1.7.0.rc.2
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.2
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.1
Ruby lib dir : /Users/mfi/.rvm/rubies/ruby-2.6.0/lib
Repositories : cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               db-dbn-ios-cocoapods - https://dbnlab.app.db.de/dbn-ios/cocoapods.git @ c80d4edc2642eb222738d824f42b935bd1952b6a
               futureworkshops - https://github.com/FutureWorkshops/FWTPodspecs.git @ a9ea4571b55c2cc15837282c242d2a09220fd451
               hacon - https://gitlab.local.hacon.de/iphone-dev/cocoapodsrepo.git @ 8f9c63b118b63949c5497451ca5b0c569d1ec45a
               hacon-cocoapodsrepo - git@gitlab.local.hacon.de:iphone-dev/cocoapodsrepo.git @ 425a5c53b516018e5faa639761dd554ce8cf9295
               hacon-iphone-dev-cocoapodsrepo - https://gitlab.local.hacon.de/iphone-dev/cocoapodsrepo.git @ e419e2a9fcf8a317a74be8c3c7f8604a81882218
               master - https://github.com/CocoaPods/Specs.git @ 13ed505b5318acc51153c501af9ee73e4a40015c
```

### Installation Source

```
Executable Path: /Users/mfi/.rvm/gems/ruby-2.6.0/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://gitlab.local.hacon.de/iphone-dev/cocoapodsrepo.git'
source 'https://github.com/CocoaPods/Specs.git'

install! 'cocoapods',
  :share_schemes_for_development_pods => true 

platform :ios, '10.0'
workspace 'HAFAS'
use_modular_headers!

pod 'SwiftLint', '0.27.0'

target 'Sample' do

...
    pod 'HAFASServices', :testspecs => ['HCI-1.24/Tests'], :subspecs => ['Protocols',
...
    'TripSearchUserOptionsProfilesCloud'], :path => './', :inhibit_warnings => true

    target 'SampleUITests' do
        pod 'NSLoggerClient', '~> 0.1'
        pod 'NSLogger/ObjC', '~> 1.9', :inhibit_warnings => true
    end
end
```

## Project that demonstrates the issue

I can't provide that yet.

I'll try to look into that later today or tomorrow and will provide an example or a PR if I can.

**Comment by dnkoutso** [comment]
Fixed by https://github.com/CocoaPods/CocoaPods/pull/8812

**Comment by dnkoutso** [comment]
Will re-open if its not the same issue.

**Comment by dnkoutso** [comment]
Well maybe not but care to verify #8812?

**Comment by paulb777** [comment]
Hm, my tests with `use_modular_headers!` worked both before and after #8812. Only `--use-libraries` was broken and fixed.

@mfiebig Was the issue introduced in 1.7.0.rc.2? Did the example work in 1.7.0.rc.1?

**Comment by mfiebig** [comment]
Yes, I forgot to mention, I checked with 1.6.x, 1.7.0.rc.1, 1.7.0.rc.2. Only 1.7.0.rc.2 failed.

**Comment by dnkoutso** [comment]
Besides #8812 no other change has been made.

**Comment by mfiebig** [comment]
I'll check with `1-7-stable`

**Comment by mfiebig** [comment]
Works with `1-7-stable` (https://github.com/CocoaPods/CocoaPods/commit/c8bcf3c9ed4a13e20267da2ebc8789507e42ad5f)

Next time I'll check with HEAD :) Didn't expect changes that fast :) Sorry for the hassle, thanks for the support!

**Comment by dnkoutso** [comment]
You should be able to but I did for you
