### ISSUE TITLE
Pod lib lint past but pod spec lint failed

### ISSUE THREAD

**Issue by stonezhl** [CocoaPods/CocoaPods#8820]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Run `pod spec lint`

## What did you expect to happen?

ℹ spec lint past

## What happened instead?

ℹ get error 
```
- NOTE  | [iOS] xcodebuild:  warning: duplicate output file '/Users/stonezhl/Library/Developer/Xcode/DerivedData/App-fuhvfxstnghxjddoehimojfbhmkk/Build/Products/Release-iphonesimulator/Bookbinder/Bookbinder.framework/Headers/NimbleSpecHelper.h' on task: CpHeader Bookbinder/Bookbinder/Carthage/Checkouts/Quick/Externals/Nimble/Tests/NimbleTests/objc/NimbleSpecHelper.h /Users/stonezhl/Library/Developer/Xcode/DerivedData/App-fuhvfxstnghxjddoehimojfbhmkk/Build/Products/Release-iphonesimulator/Bookbinder/Bookbinder.framework/Headers/NimbleSpecHelper.h (in target 'Bookbinder')
    - NOTE  | [iOS] xcodebuild:  error: Multiple commands produce '/Users/stonezhl/Library/Developer/Xcode/DerivedData/App-fuhvfxstnghxjddoehimojfbhmkk/Build/Products/Release-iphonesimulator/Bookbinder/Bookbinder.framework/Headers/NimbleSpecHelper.h':
```

## CocoaPods Environment

ℹ
 ```
   CocoaPods : 1.6.1
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f55f638f36e2df303db4f2a58ac229dbf41984b3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

ℹ https://github.com/stonezhl/Bookbinder/tree/1.0.0

## More details
I have a framework `bookbinder` which using `Kanna` & `ZIPFoundation` as dependencies via Carthage.
When I run `pod spec lint`, got the error above.
But when I run `pod lib lint`, it works well.
I also tried making a demo project to install the pod locally, and it works very well.

Thanks in advance.

**Comment by paulb777** [comment]
`pod spec lint` grabs sources from the root of the repo, not the location of the podspec, so all of the test source is being built into the library.

It's typical practice to put .podspec's at the root of the repo so that `pod spec lint` and `pod lib lint` are more consistent.

**Comment by dnkoutso** [comment]
yes please update the git tag and try again. So far this does not appear to be a library issue so I am going to close. I will re-open it if we can show a cocoapods bug.
