### ISSUE TITLE
Cocoapods 1.6.0+ breaks the pre_compile hooks used by plugins.

### ISSUE THREAD

**Issue by Unknoob** [CocoaPods/CocoaPods#8828]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Tried using the `cocoapods-rome` plugin with a `pre_compile` hook.
Some of the dependencies we use do not have a `SWIFT_VERSION` parameter set in the Podspec, so we must execute a pre_compile hook setting this value.

## What did you expect to happen?

The pre_compile hook being executed before Rome tried to compile the dependency and fixing the missing `SWIFT_VERSION` parameter missing

## What happened instead?

The pre-compile hook is not executed and we get an error complaining about the missing `SWIFT_VERSION`

### Stack

```
   CocoaPods : 1.7.0.rc.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.1 (10B61)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 2ae5b65abddcb8aa6aacce9a5d75d218a6b14745
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 1.0.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
install! 'cocoapods', integrate_targets: false 

use_frameworks!
inhibit_all_warnings!

def common_pods
    pod 'Apptimize', '3.1.6'
    pod 'FBSDKCoreKit', '~> 4.44'
    pod 'FBSDKLoginKit', '~> 4.44'
    pod 'Firebase', '~> 5.20'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Performance'
    pod 'Firebase/RemoteConfig'
    pod 'JTAppleCalendar', '~> 7.1'
    pod 'SKPhotoBrowser', '6.0.0'
    pod 'UrbanAirship-iOS-SDK', '~> 10.0'
end

def testing_pods
    pod 'Nimble', '~> 8.0'
end

target 'App' do
    common_pods
end

target 'AppTests' do
    common_pods
    testing_pods
end

plugin 'cocoapods-rome', { :pre_compile => Proc.new { |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = 'arm64'
            config.build_settings['SWIFT_VERSION'] = '4.2'
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end

    installer.pods_project.save
}, 
    dsym: false,
    configuration: 'Release'
}
```

**Comment by dnkoutso** [comment]
>The pre-compile hook is not executed and we get an error complaining about the missing SWIFT_VERSION

How do you know this is not being executed?

**Comment by Unknoob** [comment]
> How do you know this is not being executed?

Because I'm using the pre_compile hook to set the `SWIFT_VERSION` before Rome compiles the frameworks.

If I use Cocoapods 1.5.3 it works as expected, but after I update to cocoapods 1.6.0 or 1.7.0.rc.2 I get an error telling me the attribute is not set.

```
- `SKPhotoBrowser` does not specify a Swift version and none of the targets (`App` and `AppTests`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by dnkoutso** [comment]
I think the hook is being executed but the `SWIFT_VERSION` is checked earlier in 1.6.x and 1.7.x.

You also specify `pre_compile` but CocoaPods only has `pre_install` hooks.

**Comment by Unknoob** [comment]
Rome documentation tells me to use the `pre_compile` hook instead. I was under the impression that it was a Rome specific hook that got broken in the new Cocoapods version.

```
plugin 'cocoapods-rome', { :pre_compile => Proc.new { |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ARCHS'] = 'arm64'
            config.build_settings['SWIFT_VERSION'] = '4.2'
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end

    installer.pods_project.save
}, 
    dsym: false,
    configuration: 'Release'
}
```

**Comment by dnkoutso** [comment]
I think `cocoapods-rome` plugin needs an update to work with 1.6.x and 1.7.x. Both of these versions are performing earlier checks for `SWIFT_VERSION` availability.

**Comment by Unknoob** [comment]
We've been struggling with this [issue](https://github.com/CocoaPods/Rome/issues/75) since November 2018 and your answer helped me find a workaround.

I'm now using a `pre_install` hook to modify the `SWIFT_VERSION` before Rome gets executed.

```
pre_install do |installer|
    installer.analysis_result.specifications.each do |s|
      s.swift_version = '4.2' 
    end
end
```
I think we can update the Rome docs to provide this workaround since more people are having this issue, but not sure if an update to the plugin is really needed.

Thank you for the help!

**Comment by dnkoutso** [comment]
excellent! Going to close this and sorry for the inconvenience but this check must run earlier for now.
