### ISSUE TITLE
How to declare Cocoapods-art dependency in podspec

### ISSUE THREAD

**Issue by Tripwire999** [CocoaPods/CocoaPods#8830]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I tried to setup a private Cocoapod which contains a wrapper for a Cocoapod installed via Cocoapods-art. So I need to add the Cocoapods-art as a dependency in my podspec file

## What did you expect to happen?
That I could add the Cocoapods-art plugin + source to the podspec.

## What happened instead?
Linter threw an error that there is no plugin method in podspec.

## CocoaPods Environment
/Users/user/.cocoapods/repos-art/ios-keycore/.artpodrc

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/user/.rbenv/versions/2.6.0/lib
Repositories : ios-keycore -  @ 3c5f7c9fb7b1175e2d6b6c135a110a61ae4fdf19
               master - https://github.com/CocoaPods/Specs.git @ f1c46b35acb522e33cb32883c99bb33c23230d88
```

### Installation Source

```
Executable Path: /Users/user/.rbenv/versions/2.6.0/bin/pod
```

### Plugins

```
cocoapods-art         : 1.0.3
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
You cannot. It will have to be on installation instructions for your pod.

I _could_ see a DSL to support some "required_plugins" but I dont think it will be implemented anytime soon.

**Comment by dnkoutso** [comment]
Feel free to provide a proposal and attempt to implement this! See other RFCs like this one https://github.com/CocoaPods/CocoaPods/issues/8191

**Comment by Tripwire999** [comment]
@dnkoutso Thanks, if I have time i'll look into it. Question though, without this private repo my pod doesn't compile when doing pod lib lint. Can I still create a Cocoapod for my wrapper or is it impossible?

**Comment by dnkoutso** [comment]
I think your pod must have instructions to include this repo via the plugin in order for it to function.

**Comment by dnkoutso** [comment]
This issue will remain open but will close in a few days if there is no progress.

**Comment by Tripwire999** [comment]
> I think your pod must have instructions to include this repo via the plugin in order for it to function.

I know I've added it to the instructions but how do I distribute this pod when I can't get through the pod lib lint since it doesn't compile without that dependency... Or might I be doing something wrong?

**Comment by dnkoutso** [comment]
hm true you cannot do that there is no plugins support for `pod lib lint` and I dont think we want to add this because there is no way to enforce consumers to use the plugin....the only way to do so is via instructions in a README or something...

**Comment by segiddins** [comment]
`plugin ‘cocoapods-art’` in your Podfile should do the trick

**Comment by Tripwire999** [comment]
@segiddins  I know for the Podfile this works :) but this still doesn't solve the issue regarding pod lib lint which fails because the dependency on my private cocoapod-art plugin isn't there. Might need to rethink if a pod is the best solution for this.

**Comment by orta** [comment]
If the Podspec is released as ruby, you could use code to determine if the plugin is set up in the current podfile and fail elegantly with a message. This wouldn't work if you publish it via trunk though, as it only uses JSON Podspecs.

**Comment by dnkoutso** [comment]
I do not think we will be doing any changes here. You can write Ruby for a private repo as @orta said but you cannot use it for trunk since its JSON.

Closing for now as I do not suspect we will do anything here.

**Comment by neetin** [comment]
> > I think your pod must have instructions to include this repo via the plugin in order for it to function.
> 
> I know I've added it to the instructions but how do I distribute this pod when I can't get through the pod lib lint since it doesn't compile without that dependency... Or might I be doing something wrong?
@Tripwire999 
Did you find any workaround for this?
