### ISSUE TITLE
Header path changed in 1.7.0

### ISSUE THREAD

**Issue by vincentisambart** [CocoaPods/CocoaPods#8836]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` and built my project with Xcode. That project does work properly when using CocoaPods 1.6.1.

## What did you expect to happen?

My project to build properly when using CocoaPods 1.7.0.

## What happened instead?

Xcode complained it could not find headers with a hyphen `-` in the pod name.

Looking at files in the `Pods/` directory, it seems pod names in `Pods/Headers/Public/` and `Pods/Headers/Private/` now have hyphens `-` replaced by underscores `_` (though they still use hyphens in `Pods/`).

I had to change for example:
```objc
#import <pantryman-ios/pantryman-ios.h>
```
to: (changing the hyphen in the directory name to an underscore, but keeping the hyphen in the file name)
```objc
#import <pantryman_ios/pantryman-ios.h>
```
for my project to continue building.

That is a breaking change that doesn't seem to be mentioned in the change log. Was that intended?

### Stack

```
   CocoaPods : 1.7.0
        Ruby : ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.21.0
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

The project's Podfile doesn't `use_frameworks!`.

**Comment by dnkoutso** [comment]
Do you have a sample repo?

**Comment by vincentisambart** [comment]
Sample: https://github.com/vincentisambart/cocoapods-header-path-bug-sample
To build, just run `bundle exec pod install` in the `project/` directory and build the workspace with Xcode. You should get the following error:
```
.../project/CocoaPodsTest/AppDelegate.m:2:9: fatal error: 'my-pod/my-pod.h' file not found
#import <my-pod/my-pod.h>
        ^~~~~~~~~~~~~~~~~
1 error generated.
```

If you modify the Gemfile to use CocoaPods 1.6.1 and run `bundle exec pod install`, the project builds successfully.

**Comment by dnkoutso** [comment]
Nice thanks!

**Comment by dnkoutso** [comment]
Absolutely a regression. Investigating further...

**Comment by dnkoutso** [comment]
regressed here https://github.com/CocoaPods/CocoaPods/pull/8706/files#diff-3dcc246453139b4a892d9e3625c9c2eeR153
