### ISSUE TITLE
CocoaPods linker errors when using the c++ 11 standard library

### ISSUE THREAD

**Issue by mhaylock** [CocoaPods/CocoaPods#884]
If I try to compile a project that has "C++ Standard Library" (`CLANG_CXX_LIBRARY`) set to `libc++` and the Podfile contains a project using c++ then I get linker errors because `libc++` and `libstdc++` intentionally generate incompatible symbols. Pods.xcodeproj ends up using `libstdc++` as "C++ Standard Library" is not set, i.e. the value in Xcode shows as "Compiler Default".

My fix for this is to add the following to the Podfile for the project:

``` ruby
post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
    end
  end
end
```

However this seems like a kludge, is there some way that CocoaPods can handle this gracefully?

**Comment by jaredmg75** [comment]
I was able to address the problem by updating my library (MobileVLCKit) to the latest version which uses the libc++ library.  Once I updated by project and my libraries were built using the same c++ library and everything was good.
