### ISSUE TITLE
header search path not set if a static framework pod depends a static library pod.

### ISSUE THREAD

**Issue by alexlee002** [CocoaPods/CocoaPods#8840]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I have a compiled pod:
```ruby
#...
s.name = "PodA"
#...
s.source = {:http => 'https://xxx/pod.zip'}
s.source_files = 'include/*.h'
s.vendored_library = 'libPodA.a'
```
and PodB is a development pod:

```ruby
# ...
s.name = 'PodB'
s.source_files = "classes/*.{h,m}"
s.dependency 'PodA'
s.static_framework = true
```

and my Podfile is:

```ruby
# ...
use_frameworks!
# ...
pod 'PodB', :path => 'path/to/PodB'
pod 'PodA'
# ...
```

After `pod install`,  the PodB's header search path does NOT contain the header path of PodA.
And, If I import the PodA's header in PodB, and "header file not found" error is occured.

## What did you expect to happen?

PodB's header search path should include the PodA's header.

## CocoaPods Environment
Cocpapods v1.7.0-rc2

**Comment by dnkoutso** [comment]
Can you please upload a sample repo? This is difficult to re-setup a test environment and time consuming.

**Comment by alexlee002** [comment]
[PodTest2.zip](https://github.com/CocoaPods/CocoaPods/files/3215022/PodTest2.zip)
Here is my demo.
I need to build my local pod (`MyShare`) as static framework， but it need a static library (`WeChatSD`)

**Comment by samchang8826** [comment]
same issue

**Comment by dnkoutso** [comment]
Thanks. Does it work with prior versions of CocoaPods like 1.6.x or 1.5.x?

**Comment by alexlee002** [comment]
@dnkoutso :

> Does it work with prior versions of CocoaPods like 1.6.x or 1.5.x?

I didn't try,  I use this case after I upgrade to 1.7.0.rc

**Comment by samchang8826** [comment]
after i downgrade to 1.6.1, everything
 works fine

**Comment by paulb777** [comment]
@alexlee002 Change the import to `#import <WeChatSDK/WXApi.h>`.  Module style imports are required with the generate_multiple_pod_projects and incremental_installation options.
