### ISSUE TITLE
header search path not set in multiple pod projects

### ISSUE THREAD

**Issue by lusnaow** [CocoaPods/CocoaPods#8842]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
import header file of a dependency pod 

#import "UIViewController+KeyboardAnimation.h"

https://github.com/Just-/UIViewController-KeyboardAnimation

## What did you expect to happen?

compile successfully

## What happened instead?

"${PODS_ROOT}/Headers/Public/UIViewController_KeyboardAnimation" not set in header search path.  File not found error.

### Stack

```
   CocoaPods : 1.7.0
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14.5 (18F96h)
       Xcode : 10.2 (10P99q)
         Git : git version 2.20.1 (Apple Git-116)
Ruby lib dir : /usr/local/Cellar/ruby/2.6.0/lib
               master - https://github.com/CocoaPods/Specs.git @ 9e6579b054a5cb46a00998fefa4770bad462a860
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

install! 'cocoapods',
:warn_for_multiple_pod_sources => false,
:generate_multiple_pod_projects => true

target 'Sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sample
pod 'PodA', :path => '../PodA'

end
```

## Project that demonstrates the issue

[TestPod.zip](https://github.com/CocoaPods/CocoaPods/files/3216086/TestPod.zip)

**Comment by dnkoutso** [comment]
Fixed already. Will ship with 1.7.1
