### ISSUE TITLE
Published pod not installable or searchable

### ISSUE THREAD

**Issue by dmillerconsulting** [CocoaPods/CocoaPods#8843]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Created a new pod, pushed podspec to CocoaPods using `pod trunk push MozendaSwift.podspec --allow-warnings`. I got a success response with the URL for my pod on Cocoapods.org.

## What did you expect to happen?

I expected my pod to be installable on searchable. 

## What happened instead?

It doesn't install in other projects and is not showing up on the Cocoapods.org search.

## CocoaPods Environment

```### Stack


   CocoaPods : 1.7.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f433f2f1e5c73b4459c77d755170821d162078c3


### Installation Source


Executable Path: /usr/local/bin/pod


### Plugins


cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Just search for MozendaSwift on cocopods.org or try to install the pod MozendaSwift. The URL to that particular pod project is https://github.com/dmillerconsulting/MozendaSwift

**Comment by dnkoutso** [comment]
Pod is installable
```
The Gemfile's dependencies are satisfied
Analyzing dependencies
Downloading dependencies
Installing Alamofire (4.8.2)
Installing MozendaSwift (0.0.7)
Installing SwiftyJSON (5.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

Make sure you do `--repo-update` for your local repo to be updated.

As for searching...its a bug and was filed here for another pod https://github.com/CocoaPods/CocoaPods/issues/8843.

I am going to close as the pod is installable and searching is tracked as dup.
