### ISSUE TITLE
Global platform prevents abstract targets with platforms from working properly

### ISSUE THREAD

**Issue by stevenp** [CocoaPods/CocoaPods#8846]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
  
I was attempting to create a new `abstract_target` for a cross-platform framework in a Podfile for a project that already had a global `platform` specified.

## What did you expect to happen?

After running `pod install`, the Pods project should contain 6 targets: `Pods-AbstractTargetGeneration-Framework-iOS` and `Pods-AbstractTargetGeneration-Framework-macOS`, along with targets for the installed pods: `PromisesObjC-iOS`,  `PromisesObjC-macOS`, `PromisesSwift-iOS`, and `PromisesSwift-macOS`.

## What happened instead?

The `Pods-AbstractTargetGeneration-Framework-iOS` target is correctly generated, but the macOS target is called `Pods-Framework-macOS` and is empty (it has no target dependencies). The only targets for the pods themselves that are generated are `PromisesObjC` and `PromisesSwift`.

As a result, only the `Framework-iOS` target builds successfully.

Removing the global `platform` line is a workaround for the issue.

### Stack

```
   CocoaPods : 1.7.0
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.6 (18G29g)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/steven/.rvm/rubies/ruby-2.6.0/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 627d6ce9caaec1ccf0d9fa5b011fd6ef45442504
```

### Installation Source

```
Executable Path: /Users/steven/.rvm/gems/ruby-2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!
platform :ios, '11.0'

abstract_target 'AbstractTargetGeneration' do

    pod 'PromisesSwift'

    target 'Framework-iOS' do
        platform :ios, '11.0'
    end

    target 'Framework-macOS' do
        platform :osx, '10.13'
    end
end
```

## Project that demonstrates the issue

[AbstractTargetGeneration.zip](https://github.com/CocoaPods/CocoaPods/files/3218617/AbstractTargetGeneration.zip)

**Comment by stevenp** [comment]
Updated because the example I submitted with the issue was using 1.6.1. This occurs in 1.7.0 as well.

**Comment by dnkoutso** [comment]
stay

**Comment by dnkoutso** [comment]
@stevenp the setup you have is no longer possible in 1.8.x.

It will yield the following warning:
```
[!] The abstract target `Pods` is not inherited by a concrete target, so the following dependencies won't make it into any targets in your project:
    - PromisesSwift
```
There is no concrete target that uses `PromisesSwift` as a parent.

It seems that this issue is now side-stepped by this functionality.

**Comment by paulb777** [comment]
Even after fixing this, multi-platform Podfile's still may run into #8729 on Xcode 10.2 and newer.
