### ISSUE TITLE
[suggestion] add feature: completely non-project-file?

### ISSUE THREAD

**Issue by alexlee002** [CocoaPods/CocoaPods#8854]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you expect to happen?
Now cocoapods is used in many big projects, in most cases，the big project is usually split into many sub-modules, each sub-module can be described via` podspec`， and use the `Podfile` to organize the whole project.  But, the Xcode's `project.pbxproject` is so easy to be conflicted and we need to cost so much time to resolve it.

Can we support a feature that there is a way to describe the 'main project'（and the extensions app, etc）via the `podspec`, eg:

```ruby
Pod::Spec.new do |spec|
  spec.name  = "MyApp"
  spec.type    = :app # the app type
  # spec.type = :appex # the extensions type
  # spec.type = :lib  # the normal pods
```
and the `Podfile` is like this:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
workspace 'MyApp'

# the use projects
pod 'MyApp', :path => "path/to/app.podspec" # the main app project
pod 'My-ShareExt', :path => "path/to/shareext" # the extensions project
# ...

# the pods defines
pod 'MyModule1', :path => 'path/to/module1'
pod 'MyModule2', :git => 'the module2's git url'
# ...
```
so, all the Xcode projects are created by cocoapods and there won't be conflicted anymore.

**Comment by segiddins** [comment]
You can already do most of this using app specs and test specs!

**Comment by paulb777** [comment]
See http://blog.cocoapods.org/CocoaPods-1.7.0-beta/

**Comment by alexlee002** [comment]
@segiddins segiddins

Thanks! I'll learn more about app specs and check if it is the way.

I want to use cocoapods to assemble all of my project,  including my "Main App" and "App extensions", not only the "3rd frameworks"。 What I wanna to do is that ".xcodeproj-less"。

**Comment by alexlee002** [comment]
@paulb777 
thanks, I have read this document, and I wrote my cocoapods-plugin base on 1.7.0-rc.2, and I didn't find a way to auto-create the `.xcodeproj` for the "Main app".

I'll read the document again carefully.

**Comment by alexlee002** [comment]
If someone can read Chinese, here is a post:
https://mp.weixin.qq.com/s/Oa52PvsHw8wS-OvYb3ArZg

The Baidu App Team has implemented a tool like cocoapods called 'easybox'.

**Comment by alexlee002** [comment]
@dnkoutso Can we make a document about appspec and appexspec? or the dev-plan?

**Comment by dnkoutso** [comment]
@alexlee002 yes we can make a guide for cocoapods.org to discuss about app specs.
