### ISSUE TITLE
Install target specific podspec dependencies

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#8855]
🌈
* [ X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

git clone git@github.com:paulb777/target-specific-dep-bug.git
cd target-specific-dep-bug/Foo/
pod install

## What did you expect to happen?

Successful Install

## What happened instead?

[!] The platform of the target `App-macOS` (macOS 10.10) is not compatible with `Bar (1.0.0)`, which does not support `osx`.

Note that Foo's dependency on Bar is iOS specific.

### Stack

```
   CocoaPods : 1.7.0
        Ruby : ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
    RubyGems : 2.7.8
        Host : Mac OS X 10.14.3 (18D109)
       Xcode : 10.1 (10B61)
         Git : git version 2.19.0.605.g01d371f741-goog
Ruby lib dir : /Users/paulbeusterien/.rvm/rubies/ruby-2.4.4/lib
Repositories :  master - https://github.com/CocoaPods/Specs.git @ b150ef793dcf415a49f1475688df16a8e6359b52

```

### Installation Source

```
Executable Path: /Users/paulbeusterien/.rvm/gems/ruby-2.4.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 1.5.0
cocoapods-plugins                     : 1.0.0
cocoapods-rome                        : 1.0.1
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.3.1
cocoapods-try                         : 1.1.0
```

### Podfile

```ruby
---
installation_method:
  name: cocoapods
workspace: Foo.xcworkspace
target_definitions:
  - abstract: true
    children:
      - abstract: true
        name: Transitive Dependencies
      - name: App-iOS
      - name: App-macOS
      - name: App-tvOS
      - name: App-watchOS
    dependencies:
      - Bar:
        - :path: "Bar.podspec"
      - Foo:
        - :path: "Foo.podspec"
      - Foo/Tests:
        - :path: "Foo.podspec"
    name: Pods
    user_project_path: Foo.xcodeproj
    uses_frameworks: true
```

## Project that demonstrates the issue

https://github.com/paulb777/target-specific-dep-bug

**Comment by segiddins** [comment]
Nothing in that Podfile actually seems to be specifying the platforms for the different target definitions?

**Comment by paulb777** [comment]
When I was debugging it looked like the target_definition section [here](https://github.com/paulb777/target-specific-dep-bug/blob/master/Foo/CocoaPods.podfile.yaml#L11) specified the four platforms.

**Comment by segiddins** [comment]
There's nothing in there that actually specifies the platform, unless that's being inferred from the user project?

**Comment by paulb777** [comment]
The dependency from Foo to Bar is specified to be iOS only [here](https://github.com/paulb777/target-specific-dep-bug/blob/master/Foo/Foo.podspec.json#L19).

**Comment by amorde** [comment]
The target definitions in the YAML don't seem to specify platforms though, right?
