### ISSUE TITLE
how to skip download zip file in the internet with local zip file

### ISSUE THREAD

**Issue by rickrickrickyyy** [CocoaPods/CocoaPods#8861]
```
Http download
   $ /usr/bin/curl -f -L -o /var/folders/yd/7wwfhscd7fs4gj7q25kr_4gr0000gn/T/d20190529-9547-aoy6jz/file.zip
   https://github.com/opencv/opencv/releases/download/3.4.6/opencv-3.4.6-ios-framework.zip --create-dirs --netrc-optional --retry 2
   
```

because the zip file is big and my internet is slow , pod install failed here every time. Can i download the zip file manually and tell CocoaPods to find the zip file in local directory.

**Comment by dnkoutso** [comment]
I am not sure. But either way this is not a feature or bug request so I am going to close.

Look into `pod cache` command.
