### ISSUE TITLE
[CP] Copy Pods Resources not generated anymore after updating to 1.7.0

### ISSUE THREAD

**Issue by simonangerbauer** [CocoaPods/CocoaPods#8862]
Just wanted to know if I'm doing something wrong, the following behaviour is actually expected or if there really could be an issue, because it seems definitely weird to me. 🌈

# Report
## What did you do?

* Updated CocoaPods from `1.6.1` to `1.7.0`
* Run `pod update`

## What did you expect to happen?

Workspace is generated and `[CP] Copy Pods Resources` and `[CP] Embed Pods Frameworks` are generated just like with the previously used CocoaPods version (With a lot of resources and a few frameworks in this target)

## What happened instead?

`[CP] Copy Pods Resources` is not generated anymore and `[CP] Embed Pods Frameworks` is generated with a lot of frameworks compared to the few that were before.

_Note: Seems to be independent of the Usage of `xcfilelist`, because it also happens, if project object version is still < 50 just with all of the input/output files instead of the lists_

### Stack

```
   CocoaPods : 1.7.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.21.0
Ruby lib dir : /Users/sia/.rvm/rubies/ruby-2.6.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7580adf4066309965d634b7d0f7357505a4e70b6
```

### Installation Source

```
Executable Path: /Users/sia/.rvm/gems/ruby-2.6.3@pods-1.7.0/bin/pod
```

### Plugins

```
claide-plugins                   : 0.9.2
cocoapods-ack_filter             : 0.3.0
cocoapods-deintegrate            : 1.0.4
cocoapods-plugins                : 1.0.0
cocoapods-run-scripts            : 1.0.1
cocoapods-search                 : 1.0.0
cocoapods-simplifier             : 1.0.3
cocoapods-static-swift-framework : 0.4
cocoapods-stats                  : 1.1.0
cocoapods-trunk                  : 1.3.1
cocoapods-try                    : 1.1.0
slather                          : 2.4.7
```

### Podfile
Can't share the full Podfile of this project, unfortunately.

## Project that demonstrates the issue

Can't share the project, where this issue occurs either..

**Comment by dnkoutso** [comment]
Still need a sample app as I cant reproduce. The script phase won't be added if its not needed.

**Comment by armandzwan** [comment]
Same here. I'll try if I can create a sample project.

**Comment by armandzwan** [comment]
When I remove the Pods_<appname>.framework from the target at the "Linked Frameworks and Libraries" section (in general tab), the error is gone and the App builds.

**Comment by dnkoutso** [comment]
Still need a reproducible project here.

**Comment by Buju77** [comment]
> The script phase won't be added if its not needed.

what are the deciding factors for not adding the script phase?

**Comment by dnkoutso** [comment]
if there are no frameworks to copy into the host target then the script phase is not added.

**Comment by simonangerbauer** [comment]
Can't reproduce this issue in a sample project unfortunately.
