### ISSUE TITLE
Do not check newer podspec when using an older version

### ISSUE THREAD

**Issue by fangmobile** [CocoaPods/CocoaPods#8867]
# Report

## What did you do?
Used new `swift_versions=` in my latest pod spec.
e.g. in mySdk version 2.0.0 podspec, I have `s.swift_versions  = ['4.2', '5.0']`

## What did you expect to happen?
User who is NOT using mySdk 2.0.0 should not need to check 2.0.0 pod spec when they run `pod install`

## What happened instead?
User who is using mySdk 1.0.0 also have an older version of cocopods, so `pod install` failed because his older cocoapods does not understand ``s.swift_versions`

## CocoaPods Environment
< 1.7.0

## Project that demonstrates the issue
N/A

**Comment by dnkoutso** [comment]
Is this podspec published json or Ruby? Internal repo?

**Comment by dnkoutso** [comment]
Your user can also apply a constraint to the version so get something `pod 'myPod', '< 2.0'`

**Comment by fangmobile** [comment]
> Is this podspec published json or Ruby? Internal repo?

Internal repo. Ruby.

**Comment by dnkoutso** [comment]
You can publish with `--use-json` (or `--json` IIRC) to avoid this limitation like the master specs repo does.

Additionally as I said the user can apply constraints to the version to consume. I do no think there is something to improve here given that there are options to circumvent this.

Going to close preemptively and I will re-open if we can figure out maybe an enhancement.

**Comment by fangmobile** [comment]
> Your user can also apply a constraint to the version so get something `pod 'myPod', '< 2.0'`

We are using fixed version number in the podfile
```pod 'myPod', '1.0.0'```
but it is still checkiing 2.0.0 podspec and failed the command because it found it can not under stand `s.swift_versions`

```[!] Invalid `myPod.podspec` file: undefined method `swift_versions=' for #<Pod::Specification name="myPod">
Did you mean?  swift_version=
               swift_version.

 #  from /Users/user/.cocoapods/repos/internal-cocoapods/myPod/2.0.0/myPod.podspec:6
 #  -------------------------------------------
 #    s.summary         = 'Intuit Authorization iOS Library'
 >    s.swift_versions  = ['4.2', '5.0']
 #  
 #  -------------------------------------------
```

**Comment by dnkoutso** [comment]
You are correct it will do that. Publish your podspec as JSON to avoid this. < 1.7.0 versions will not become forward compatible.

**Comment by fangmobile** [comment]
> You are correct it will do that. Publish your podspec as JSON to avoid this. < 1.7.0 versions will not become forward compatible.

I am saying we are already putting constrains like `pod 'myPod', '1.0.0'` but it is still checking 2.0.0 pod spec and fails the command. Anywyas ...

**Comment by dmcgloin** [comment]
It would be good for the parser to look first for `s.cocoapods_version = '>= 1.7.0'` before failing when trying to parse out stuff it can potentially never understand.
