### ISSUE TITLE
[iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: )

### ISSUE THREAD

**Issue by Adrift001** [CocoaPods/CocoaPods#8875]
# Report

## What did you do?

pod lib lint --sources=http://git.ycteam.work/YCSpecs.git,https://github.com/CocoaPods/Specs.git --allow-warnings  (git.ycteam.work is local server)

## What did you expect to happen?

Verify that the library has errors

## What happened instead?

- ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/swifter/.rvm/rubies/ruby-2.6.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 27ed88ffc11275f6e0fb814a3d36e3c00358418d
               ycteam-ycspecs - http://git.ycteam.work/YCSpecs.git @ 888db81fd7c799ccf389a9c2d9ea6ba849dc8e3f
```

### Installation Source

```
Executable Path: /Users/swifter/.rvm/rubies/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**I installed Xcode 11.0, but let me delete it. It doesn't work at all.**

**Comment by Adrift001** [comment]
@Coeur @MaximBazarov

**Comment by tepmnthar** [comment]
Same here.

**Comment by Coeur** [comment]
Untested, but according to @dimsky on [this comment](https://github.com/CocoaPods/CocoaPods/issues/8163#issuecomment-498997173), we could change fourflusher find.rb to be:
```ruby
if device['availability'] == '(available)' || device['isAvailable'] == true || device['isAvailable'] == 'YES' || device['isAvailable'] == 'true'
        Simulator.new(device, os_name, os_version)
end
```

**Comment by Adrift001** [comment]
got it!

**Comment by kurabi** [comment]
Pull request does not seem to fix the issue.

**Comment by kurabi** [comment]
I tried the PR again, and I can confirm it fixes this issue (unlike my previous claim).

**Comment by reececomo** [comment]
Yep this worked for me 👍. Was able to push a new Swift 5.1/iOS 13.0+ pod just now for those sweet sweet SF Symbols:

https://github.com/hubrioAU/SFSymbols

**Comment by dnkoutso** [comment]
Released 2.3.0 of fourflusher should be able to do `gem update fourflusher` to fix this issue.

Please note rubygems.org might take a bit of time to catch up with the release.

**Comment by alfwatt** [comment]
If you have `pod` installed via `homebrew` the quickest update process (adding brew-gem to manage the packages) is: ```brew remove cocoapods
brew install brew-gem
brew gem install cocoapods
brew gem upgrade fourflusher 2.3.0```

**Comment by Adrift001** [comment]
```
gem uninstall fourflusher
gem install fourflusher
```
