### ISSUE TITLE
[1.7.1] Pod using custom modulemap and integrate with `modular_headers` will cause the `export *` export all Public and Private headers, where `use_frameworks!` does not

### ISSUE THREAD

**Issue by dreampiggy** [CocoaPods/CocoaPods#8879]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Write a CoocaPods's Pod, which have a `modulemap`, and have some `private_header_files`. Both of them as valid Podspec syntax.
2. Integrate the Pod, using `modular_headers`, it can be done using `use_modular_headers!` or specify only for this Pod
3. Run `pod install`
4. Check the generate Xcode project. The modulemap file is placed under `Pods/Headers/Private`
5. This cause the warning for clang. Because the modulemap use `export *` syntax, which will mark all `Pods/Headers/Private/*.h` as public headers.

Note: This issue does not appear, when don't use `modular_headers`, or `use_frameworks!`.

## What did you expect to happen?

When using custom modulemap, the modulemap file should be placed into `Pods/Headers/Public`, just as the default CocoaPods generated one, but not the `Pods/Headers/Private`.

## What happened instead?

When using custom modulemap, the modulemap file should be placed into `Pods/Headers/Private`, cause the `export *` syntax mismatch all the headers as public.

User who have private header files, should manualy strip the private headers, even they already declare them in `Podspec.private_header_files` syntax.

```
// Lib.modulemap

exclude header "Private1.h"
exclude header "Private2.h"

export *
module * { export * }
```

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
    RubyGems : 2.7.9
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/lizhuoli/.rvm/rubies/ruby-2.5.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b287af13e912623835bbfdf04ce18b0892a058b0
```

### Installation Source

```
Executable Path: /Users/lizhuoli/.rvm/gems/ruby-2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_modular_headers!

target 'SDWebImageWebPCoderTest' do
    pod 'SDWebImage'
    pod 'SDWebImageWebPCoder'
end
```

## Project that demonstrates the issue

You can use this Demo project: https://github.com/ledyba/SDWebImageWebPCoderTest

1. Run `pod update` after clone.
2. Build the Application target
3. See the clang warning
4. Change to use `use_frameworks!` and retry the same steps

+ `use_frameworks!`
![image](https://user-images.githubusercontent.com/6919743/58543825-c36a2580-8232-11e9-87aa-4a46152d7c00.png)

+ `use_modular_headers!`
![image](https://user-images.githubusercontent.com/6919743/58543872-d846b900-8232-11e9-9ad6-bcf723155b77.png)

![image](https://user-images.githubusercontent.com/6919743/58544165-55722e00-8233-11e9-828c-4a9c7501c6b0.png)

**Comment by dreampiggy** [comment]
This similar issue appear in the issue list, but it's still not been fixed and been closed. See #7598

**Comment by dnkoutso** [comment]
Maybe an issue but currently I do not have time to investigate

**Comment by dreampiggy** [comment]
Sorry. I found the the reason for that warning. It's not because of the. It's because of the modulemap file. This modulemap file, should not be marked as `Private` when using `use_modular_headers` and have custom modulemap.

```
umbrella header for module 'SDWebImage' does not include header 'SDWeakProxy.h'
```

When removing the `s.modulemap = 'WebImage/SDWebImage.modulemap'` in Podspec, I compare the result of two generate project. Here is the changes:

![image](https://user-images.githubusercontent.com/6919743/59009362-dd71bc80-885f-11e9-8468-c6b2a459a422.png)

**Comment by dreampiggy** [comment]
After I comment this line of CocoaPods code, to use the same directory as CocoaPods auto-generated modulemap, this warning disappear. Anyone know what this logic used for ?

https://github.com/CocoaPods/CocoaPods/blob/1.7.1/lib/cocoapods/target/pod_target.rb#L418-L427

into:

```ruby
      basename = "#{label}.modulemap"
      if build_as_framework?
        super
      else
        sandbox.public_headers.root + product_module_name + basename
      end
```


The build result now without this warning (keeping `s.modulemap`, actually, no any change to demo project or Podspec):

![image](https://user-images.githubusercontent.com/6919743/59010510-20359380-8864-11e9-930c-a46c8326e861.png)

**Comment by dreampiggy** [comment]
Seems related to https://github.com/CocoaPods/CocoaPods/commit/4acf59d4be90b00782e92c172954b5e2fa48ae5c

**Comment by dreampiggy** [comment]
I update the Issue title to describe the syntax more clearly.

Maybe I can now understand the issue's reason. But I want to know whether, this is a designed behavior, or just bug ?

> Why this behaivor is different from `use_frameworks!` and `use_modular_headers!` ?
They all using modulemap, but why `use_frameworks!` put the modulemap into `Pods/Headers/Public`, the `use_modular_headers` puts the modulemap into `Pods/Headers/Private`. Can they have the same behavior ?
