### ISSUE TITLE
Pod trunk push Github timed out

### ISSUE THREAD

**Issue by meteora8888** [CocoaPods/CocoaPods#8889]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I ran pod trunk push AdoKod.podspec

## What did you expect to happen?

The pod to upload to cocoa pods 

## What happened instead?

I received an error after quite a long wait.
[!] Calling the GitHub commit API timed out. Please check GitHub’s status at https://status.github.com and try again later.

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : AdoPushDemoSpec - https://github.com/meteora8888/AdoPushDemoSpec.git @ a8a379185d76436767786023c15edf1839c92af0
               master - https://github.com/CocoaPods/Specs.git @ c215bc2ac86aa3d69de1af0a370a45aaa46428bc
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/meteora8888/AdoKod

## What I've tried

I tried to debug it by using the verbose 

Updating spec repo `master`
Validating podspec
    AdoKod (0.1.3) - Analyzing on iOS 10.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `AdoKod` from `/Users/andrejjasso/github/AdoKod/AdoKod.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A AdoKod

Downloading dependencies

-> Installing AdoKod (0.1.3)
  > Copying AdoKod from
  `/Users/andrejjasso/Library/Caches/CocoaPods/Pods/External/AdoKod/d8a423dea57f67f135d1bc493a67a559-89287`
  to
  `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/AdoKod`
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Installing files into Pods project
    - Adding source files
    - Adding frameworks
    - Adding libraries
    - Adding resources
    - Linking headers
  - Installing Pod Targets
    - Installing target `AdoKod` iOS 10.0
      - Generating module map file at
      `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Target
      Support Files/AdoKod/AdoKod.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Target
      Support Files/AdoKod/AdoKod-umbrella.h`
      - Generating Info.plist file at
      `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Target
      Support Files/AdoKod/AdoKod-Info.plist`
      - Generating dummy source at
      `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Target
      Support Files/AdoKod/AdoKod-dummy.m`
  - Installing Aggregate Targets
    - Installing target `Pods-App` iOS 10.0
      - Generating Info.plist file at
      `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Target
      Support Files/Pods-App/Pods-App-Info.plist`
      - Generating module map file at
      `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Target
      Support Files/Pods-App/Pods-App.modulemap`
      - Generating umbrella header at
      `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Target
      Support Files/Pods-App/Pods-App-umbrella.h`
      - Generating dummy source at
      `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Target
      Support Files/Pods-App/Pods-App-dummy.m`
  - Stabilizing target UUIDs
  - Running post install hooks
  - Writing Xcode project file to
  `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Pods.xcodeproj`
  Cleaning up sandbox directory
  - Writing Lockfile in
  `../../../../var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Podfile.lock`
  - Writing Manifest in
  `../../../../private/var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/Pods/Manifest.lock`

Integrating client project

[!] Please close any current Xcode sessions and use `App.xcworkspace` for this project from now on.

Integrating target `Pods-App` (`../../../../var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/App.xcodeproj` project)
  Adding Build Phase '[CP] Embed Pods Frameworks' to project.
  Adding Build Phase '[CP] Check Pods Manifest.lock' to project.

-> Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
   Building with `xcodebuild`. 
    $ /usr/bin/xcodebuild clean build -workspace
    /var/folders/5f/l_171f252xq69s5vkgv44tw80000gn/T/CocoaPods-Lint-20190607-51654-9phxc4-AdoKod/App.xcworkspace
    -scheme App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator
    -destination id=1EC2C673-F427-476B-A3D4-23F84DDC8D1A
    Build settings from command line:
        CODE_SIGN_IDENTITY = -
        SDKROOT = iphonesimulator12.2
    
    note: Using new build system
    
    ** CLEAN SUCCEEDED **
    
    note: Using new build system
    note: Planning build
    note: Constructing build description

FOLLOWED by a lot of mkdik etc.. 

  Testing with `xcodebuild`. 
 -> AdoKod (0.1.3)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.7.1\r\nAuthorization: Token 1e88cd7b860ac30766234510e0241e4d\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 1094\r\n\r\n"
<- "{\"name\":\"AdoKod\",\"version\":\"0.1.3\",\"summary\":\"By far the most fantastic view I have seen in my entire life. No joke.\",\"description\":\"This fantastic view changes its color gradually makes your app look fantastic!\",\"swift_versions\":\"4.2\",\"homepage\":\"https://github.com/meteora8888/AdoKod.git\",\"license\":{\"type\":\"Apache License, Version 2.0\",\"text\":\"Licensed under the Apache License, Version 2.0 (the \\\"License\\\");\\nyou may not use this file except in compliance with the License.\\nYou may obtain a copy of the License at\\n\\nhttp://www.apache.org/licenses/LICENSE-2.0\\n\\nUnless required by applicable law or agreed to in writing, software\\ndistributed under the License is distributed on an \\\"AS IS\\\" BASIS,\\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\\nSee the License for the specific language governing permissions and\\nlimitations under the License.\\n\"},\"authors\":{\"Andrej Jasso\":\"andrej.jasso@gmail.com\"},\"source\":{\"git\":\"https://github.com/meteora8888/AdoKod.git\",\"tag\":\"0.1.3\"},\"platforms\":{\"ios\":\"10.0\"},\"source_files\":\"AdoKod/*.swift\",\"swift_version\":\"4.2\"}\n"
-> "HTTP/1.1 504 Gateway Time-out\r\n"
-> "Date: Fri, 07 Jun 2019 08:30:09 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 133\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 133 bytes...
-> "{\"error\":\"Calling the GitHub commit API timed out. Please check GitHub\xE2\x80\x99s status at https://status.github.com and try again later.\"}"
read 133 bytes
Conn keep-alive
[!] Calling the GitHub commit API timed out. Please check GitHub’s status at https://status.github.com and try again later.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:70:in `print_error'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:30:in `request_url'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:36:in `request_path'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/push.rb:85:in `push_to_trunk'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/push.rb:71:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

Also when I redo the request It writes that I cannot push a duplicate but the pod is not downloadable or visible anyways. 

Gitsttatus says its up and running

**Comment by hatjs880328s** [comment]
This problem has often occurred in the last two days.

wait.........

**Comment by Daltron** [comment]
Experiencing the exact same issues.

**Comment by ranabirm** [comment]
Same error occurring on my system. Logs given below ->

`opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.7.1\r\nAuthorization: Token 6951b5e8ca233ccbc3d382be7371d62d\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 1432\r\n\r\n"
<- "{\"name\":\"DTBiOSSDK\",\"version\":\"2.1.2\",\"summary\":\"Amazon Mobile Ads SDK for iOS\",\"description\":\"The APS mobile monetization program is designed to integrate Amazon\u{2019}s demand into your ad server and ad optimization stack. It works through two main components, an Amazon-provided SDK and the Key-Value targeting or Custom Targeting feature in your ad server.\\nGeneral Process - \\n1. The SDK needs to be included in your App. \\n2. It calls Amazon to see if we have ads available to show on the page and sets a flag or a key for each ad that Amazon has available.  \\n3. You also need to set up ad tags provided by Amazon in your ad server. \\n4. When serving an ad, your ad server includes the Amazon tag ad as a candidate in its consideration set if the key value pair is set. \\n5. It only serves the Amazon ad tag if it meets all of its own optimization criteria and if the key value pair is set.\",\"homepage\":\"https://aps.amazon.com/aps/solutions-for-mobile-app-developers/\",\"license\":{\"type\":\"Custom\",\"file\":\"MMB_IOS_2.1.2/LICENSE.txt\"},\"authors\":{\"Amazon Publisher Services\":\"aps-mobile-support@amazon.com\"},\"source\":{\"http\":\"https://d21wcxpfwrhwzb.cloudfront.net/MMB_IOS.zip\"},\"platforms\":{\"ios\":\"9.0\"},\"requires_arc\":true,\"ios\":{\"vendored_frameworks\":\"MMB_IOS_2.1.2/DTBiOSSDK.framework\"},\"frameworks\":[\"AdSupport\",\"CoreLocation\",\"SystemConfiguration\",\"CoreTelephony\",\"MediaPlayer\",\"EventKit\",\"EventKitUI\",\"StoreKit\",\"QuartzCore\"]}\n"
-> "HTTP/1.1 504 Gateway Time-out\r\n"
-> "Date: Fri, 07 Jun 2019 17:46:10 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 133\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 133 bytes...
-> "{\"error\":\"Calling the GitHub commit API timed out. Please check GitHub\xE2\x80\x99s status at https://status.github.com and try again later.\"}"
read 133 bytes
Conn keep-alive
[!] Calling the GitHub commit API timed out. Please check GitHub’s status at https://status.github.com and try again later.
`

**Comment by ranabirm** [comment]
same issue here as well - .podspec lints correctly, xcode build passes, final POST to git via trunk.cocoapods.org:443 -> fails consistently from my system

**Comment by aiwo** [comment]
Have the same issue

**Comment by dnkoutso** [comment]
This may be a Github issue as the initial error suggests:

```
"{"error":"Calling the GitHub commit API timed out. Please check GitHub\xE2\x80\x99s status at https://status.github.com and try again later."}"
```

Keep retrying. Although all status on GH looks normal.

**Comment by ranabirm** [comment]
Can confirm that repeated pushing from my local doesn't work - will wait for others to provide feedback

**Comment by aiwo** [comment]
Works fine at the moment

**Comment by dnkoutso** [comment]
Will close this and re-open if more reports come through. Nothing has changed with respect to trunk lately.

**Comment by meteora8888** [comment]
I agree to the closing, since it works to me too now. Must have been an issue with GitHub like the error. The link they provided in the error wasn't helpful but now it works so happy me :) Thanks for sharing your problems here. Its better to know I am not alone in it!

**Comment by DanielCech** [comment]
I noticed the same problem and I also found a solution (at least for me). I started `pod trunk push ...` from fish shell. From bash shell it worked fine.

**Comment by justSmK** [comment]
Still happening

[GitHub Action](https://github.com/mindbox-cloud/ios-sdk/actions/runs/15158705581/job/42620006501)

```
opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established, protocol: TLSv1.3, cipher: TLS_AES_128_GCM_SHA256
<- "POST /api/v1/pods?allow_warnings=true HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.16.2\r\nAuthorization: Token ***\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 632\r\n\r\n"
<- "{\"name\":\"MindboxLogger\",\"version\":\"2.13.3\",\"summary\":\"SDK for utilities to work with Mindbox\",\"description\":\"-\",\"homepage\":\"[https://github.com/mindbox-cloud/ios-sdk\](https://github.com/mindbox-cloud/ios-sdk/)",\"license\":{\"type\":\"CC BY-NC-ND 4.0\",\"file\":\"LICENSE.md\"},\"authors\":{\"Mindbox\":\"ios-sdk@mindbox.ru\"},\"platforms\":{\"ios\":\"12.0\"},\"source\":{\"git\":\"[https://github.com/mindbox-cloud/ios-sdk.git\](https://github.com/mindbox-cloud/ios-sdk.git/)",\"tag\":\"2.13.3\"},\"source_files\":[\"MindboxLogger/**/*.{swift}\",\"SDKVersionProvider/**/*.{swift}\"],\"exclude_files\":\"Classes/Exclude\",\"resource_bundles\":{\"MindboxLogger\":[\"MindboxLogger/**/*.xcdatamodeld\",\"MindboxLogger/**/*.xcprivacy\"]},\"swift_versions\":\"5\",\"swift_version\":\"5\"}\n"
-> "HTTP/1.1 504 Gateway Timeout\r\n"
-> "Server: Cowboy\r\n"
-> "Date: Wed, 21 May 2025 09:41:44 GMT\r\n"
-> "Report-To: {\"group\":\"heroku-nel\",\"max_age\":3600,\"endpoints\":[{\"url\":\"https://nel.heroku.com/reports?ts=1747820490&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=EJhUpkxsek57L7ebMK42UClGhonjLf703k4qMVTUTNg%3D\"}]}\r\n"
-> "Reporting-Endpoints: heroku-nel=https://nel.heroku.com/reports?ts=1747820490&sid=929419e7-33ea-4e2f-85f0-7d8b7cd5cbd6&s=EJhUpkxsek57L7ebMK42UClGhonjLf703k4qMVTUTNg%3D\r\n"
-> "Nel: {\"report_to\":\"heroku-nel\",\"max_age\":3600,\"success_fraction\":0.005,\"failure_fraction\":0.05,\"response_headers\":[\"Via\"]}\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Content-Length: 133\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 133 bytes...
-> "{\"error\":\"Calling the GitHub commit API timed out. Please check GitHub\xE2\x80\x99s status at https://status.github.com/ and try again later.\"}"
read 133 bytes
Conn keep-alive
[!] Calling the GitHub commit API timed out. Please check GitHub’s status at https://status.github.com/ and try again later.

/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk.rb:70:in `print_error'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk.rb:30:in `request_url'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk.rb:36:in `request_path'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/push.rb:89:in `push_to_trunk'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/push.rb:73:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/lib/ruby/gems/3.3.0/gems/cocoapods-1.16.2/bin/pod:55:in `<top (required)>'
/opt/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `load'
/opt/homebrew/lib/ruby/gems/3.3.0/bin/pod:25:in `<main>'
Error: Process completed with exit code 1.
```
