### ISSUE TITLE
[Catalyst] Add new "iosmac" platform

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#8892]
I am not sure if this is necessarily the correct approach, because I'm not sure if we can still use a single app target for "ios" and "iosmac".

We need to ship 3 `.a` files now instead of 2 because of the conflict for the x86_64 slice being used by both the iOS simulator and "UIKit for macOS". 

```ruby
# built for macOS (x86_64, i386)
s.macos.vendored_libraries = 'libs/mac/*.a'
# built for iOS and iOS simulator (armv7, arm64, x86_64, i386)
s.ios.vendored_libraries = 'libs/ios/*.a'
# built for "UIKit for macOS" (x86_64)
s.iosmac.vendored_libraries = 'libs/iosmac/*.a'
```

_Originally posted by @chrisballinger in https://github.com/CocoaPods/CocoaPods/issues/8877#issuecomment-499206609_

**Comment by dnkoutso** [comment]
This will probably need a CocoaPods/Core DSL improvement to add the new platform. Could transfer issue there.

**Comment by chrisballinger** [comment]
I'm wondering if it would be better served as an override for `ios` specs, because "source only" specs should be mostly okay as-is, and it would require less updates from podspec authors.

```ruby
s.ios.source_files = 'Source/*.swift'
s.ios.vendored_libraries = 'libs/ios/*.a'
s.ios.vendored_libraries.iosmac = 'libs/iosmac/*.a'
```
vs
```ruby
s.ios.source_files = 'Source/*.swift'
s.ios.vendored_libraries = 'libs/ios/*.a'
s.iosmac.source_files = 'Source/*.swift'
s.iosmac.vendored_libraries= 'libs/iosmac/*.a'
```

I'm not familiar with the CocoaPods internals enough to guess which would be easier to implement in practice.

**Comment by igor-makarov** [comment]
As far as I'm seeing from my initial work, `iosmac` isn't a separate platform. As far as Xcode is concerned, it's just a deployment target for iOS apps. Imagine it to be kinda like a new 'architecture' only it can't be, since i386 is already an existing arch for the simulator. 🤦🏻‍♂️

For vendored frameworks, Apple invented this new 'extra fat' XCFramework format that can contain frameworks for simulator along with frameworks for Catalyst.

**Comment by chrisballinger** [comment]
Perhaps the correct way forward is generating XCFrameworks. Do you know if it's possible to vendor a static library inside an xcframework bundle?

**Comment by igor-makarov** [comment]
Haven't had the chance to figure out what an XCFramework actually is inside yet. 
You can always vend a static framework instead of a library.

**Comment by igor-makarov** [comment]
BTW, this is the relevant talk, which I haven't watched yet: https://developer.apple.com/videos/play/wwdc2019/416/

**Comment by igor-makarov** [comment]
So I watched the video and according to it, it's possible to bundle an `.a` library into a XCFramework. They didn't specify how, however in the `xcodebuild` man page there is a clue:
```
xcodebuild -create-xcframework [-help] [-framework <path>] [-library <path> [-headers <path>]] -output <path>
```
In any case, adding a XCFramework seemingly creates the same project nodes as a `.framework`. I couldn't get it to work with `vendored_frameworks` because CP is very particular about what goes where.

**Comment by jonas-sleepcycle** [comment]
Could this be relevant? An answer from Apple but also a comment about getting one framework working with UIKit-for-mac:

https://forums.developer.apple.com/message/362577

**Comment by appfrilans** [comment]
Could this be relevant? An answer from Apple but also a comment about getting one framework working with UIKit-for-mac:

https://forums.developer.apple.com/message/362577

**Comment by amorde** [comment]
Very interesting, key point from the linked post:

> Libraries coming into the UIKit for Mac environment need to be compiled for the iOS platform, not the macOS platform. 

Seems like we might be able to get away with using the iOS platform - CocoaPods would need to add support for including iOS pods into macOS targets which might get tricky

**Comment by igor-makarov** [comment]
These aren't macOS targets, these are iOS targets. I've managed to compile out app with lots of pods for UIKitForMac and the only things I had to rip out were vendored frameworks, because they weren't compatible.

CocoaPods needs to be modified to recognize the new `.xcframework` extension but that's it I think.

**Comment by amorde** [comment]
Right but couldn't we support integrating iOS pods into macOS targets when the deployment target of the user target is Catalina or higher? Even if a Podspec doesn't claim to support macOS, if it supports iOS 13 then it (theoretically) implicitly supports Catalyst apps on macOS. I'm not saying we _should_ do it that way but it sounds possible

**Comment by igor-makarov** [comment]
I haven't figured out yet how this is supported by Xcode. Ultimately if it builds, that's good. 

But the biggest use case is porting iOS targets.

**Comment by chrisballinger** [comment]
I think I should close this issue and open a new one. UIKitForMac uses the iOS platform, and you can't mix a UIKitForMac target with a native AppKit target. 

The issue comes from vendored libraries and frameworks needing two x86_64 slices compiled for different targets (iOS simulator and UIKitForMac). The status quo is to include a fat binary with all your slices for example libFoo.a with armv7, arm64 and x86_64 (simulator) slices. Since we can't add an additional x86_64 UIKitForMac slice to the fat static lib, we'll probably need to create an `xcframework`.

**Comment by BalkiX** [comment]
Few findings when distributing xcframework through pods.
First I've tried using podpec like this:

```
Pod::Spec.new do |s|
s.name             = "FRAMEWORK_NAME"
s.version          = "x.y.z"
s.platform         = :ios
s.source           = { :http => 'http://distribution_server.com:8081/repository/xi-pods/FRAMEWORK_NAME-x.y.z.zip'}
s.ios.deployment_target = '11.0'
s.ios.vendored_frameworks = ['FRAMEWORK_NAME.xcframework']
end
```

but I've run into multiple issues:

1. In generated Pods.xcconfig file, the framework was referenced in **_OTHER_LDFLAGS_** in format **_-framework "FRAMEWORK_NAME.xcframework"_** the extension .xcframeworks is unnecessary at this place and it needs to be referenced in format **_-framework "FRAMEWORK_NAME"'_** 

2.  In generated Pods.xcconfig file, the _**FRAMEWORK_SEARCH_PATHS**_ was set same way as for classic framework in format:  _**"${PODS_ROOT}/FRAMEWORK_NAME"**_. But as now xcframework contains new folder structure for multiple architectures it has to explicitly reference all subfolders or needs to use recursive search like this: _**"${PODS_ROOT}/FRAMEWORK_NAME/\*\*"**_

To workaround those issues I've temporarily updated podspec the way that the xcframework is refereced as a resource and I'm setting FRAMEWORK_SEARCH_PATHS and OTHER_LDFLAGS manually. See example below: 
```
Pod::Spec.new do |s|
s.name             = "FRAMEWORK_NAME"
s.version          = "x.y.z"
s.platform         = :ios
s.source           = { :http => 'http://distribution_server.com:8081/repository/xi-pods/FRAMEWORK_NAME-x.y.z.zip'}
s.ios.deployment_target = '11.0'
s.resources = ['FRAMEWORK_NAME.xcframework']
s.xcconfig = { 
'FRAMEWORK_SEARCH_PATHS' => '"${PODS_ROOT}/FRAMEWORK_NAME/FRAMEWORK_NAME.xcframework/ios-arm64" "${PODS_ROOT}/FRAMEWORK_NAME/FRAMEWORK_NAME.xcframework/ios-x86_64-simulator" "${PODS_ROOT}/FRAMEWORK_NAME/FRAMEWORK_NAME.xcframework/ios-x86_64-uikitformac"', 
'OTHER_LDFLAGS' => '-framework "FRAMEWORK_NAME"' 
}
end
```

**Comment by bielikb** [comment]
Is there any plan on supporting the `xcframeworks` ? Should there be another issue opened in these regards?

**Comment by paulb777** [comment]
My understanding is that `xcframework` support is the main work required for this issue so that binary pods can be supported. Source pods already are enabled if the app selects the `Mac` box on the iOS target.

**Comment by igor-makarov** [comment]
I can confirm what @paulb777  is saying. I've been successful in building and running a large application (Moovit) for Mac Catalyst. The only things I had to comment out were the binary frameworks.

**Comment by paulb777** [comment]
Close in favor of #9148
