### ISSUE TITLE
Xcode 11: "The spec did not pass validation, due to 1 error"

### ISSUE THREAD

**Issue by richardtop** [CocoaPods/CocoaPods#8893]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
While **Xcode 11** is installed, Xcode 10.3.1 Command Line Tools selected.

```
pod trunk push --allow-warnings
```

## What did you expect to happen?

CocoaPod released to the Trunk repository correctly.

## What happened instead?

CocoaPod didn't pass validation and failed with an error:
```
[!] Found podspec `CalendarKit.podspec`
Updating spec repo `master`
Validating podspec
 -> CalendarKit (0.7.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

[!] The spec did not pass validation, due to 1 error.
```

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/richard/.rvm/rubies/ruby-2.6.0/lib
Repositories : gitlab-privatespecs - git@gitlab.local:mobile/privatespecs.git @ cd59b2559bd958318a40f04229d5018b2d78fa97
               master - https://github.com/CocoaPods/Specs.git @ 05b50da9920b95055a3ca96f5fc365b58bd1ed02
```

### Installation Source

```
Executable Path: /Users/richard/.rvm/gems/ruby-2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by richardtop** [comment]
StackOverflow issue:
https://stackoverflow.com/questions/52742003/cocoapods-cant-find-simulators-pod-repo-push-fails

**Comment by dnkoutso** [comment]
Did you `gem update fourflusher`?

**Comment by dnkoutso** [comment]
Will close and re-open as I believe this has been fixed. If its not I will re-open.

**Comment by richardtop** [comment]
Thanks for pinpointing the issue, now the validator works fine:

```
dsl-hkibng11-50dccf-231:CalendarKit richard$ pod lib lint --allow-warnings

 -> CalendarKit (0.7.1)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description

CalendarKit passed validation.
dsl-hkibng11-50dccf-231:CalendarKit richard$ 
```

**Comment by izooto-mobile-sdk** [comment]
Please help
Resolve my issue or guide me
    - NOTE  | [iOS] xcodebuild:  error: Multiple commands produce '/Users/amit/Library/Developer/Xcode/DerivedData/App-bsplkyxyaklywecmhsadfqgusrow/Build/Products/Release-iphonesimulator/iZootoFramework/iZootoFramework.framework/Info.plist':
