### ISSUE TITLE
order of sources with private pods not working anymore

### ISSUE THREAD

**Issue by dfrobese** [CocoaPods/CocoaPods#8895]
<!--
We are using cocapods in combination of building frameworks in with combination with
github and private pods.

After updating cocoapod from 1.6 to 1.7.1 it looks like, that the order of the pod namespaces has been changed. Before 1.7.1 cocoapod resolves the pod dependecies in the order of the given --sources command parameter.

In the actual release of cocoapods the mater repo is always first. This leads into an error, when a pod with the same name is in a private and the master pod. Trying to reference the private pod fails, because the pod of the master is taken first.

# Report

## What did you do?

e.g. Run `pod spec lint sources=https://git.PRIVATEPOD.de/cocoapodspecs.git,https://github.com/CocoaPods/Specs.git`

## What did you expect to happen?

Checking the podspec, with referencing the dependencies first to the private pod, if not successful, the master pod.

## What happened instead?

Dependencies are always resolved from the master pod first

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : CocoaPodSpecs - https://git.frobese.de/mobile/cocoapodspecs.git @ abd44caff3d14d05ff4db5cccfbf1ab44917e7be
               
               master - https://github.com/CocoaPods/Specs.git @ f220051f86ce7a46c4c4223fef5e75d64ea0a610
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
source 'https://git.frobese.de/mobile/cocoapodspecs.git'   <---- Private POD first in the order
# source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.jsdelivr.net/cocoa/'

target 'ClassExtensionPack macOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for ClasExtensionPack macOS
    pod 'Logging', :git => 'https://git.frobese.de/mobile/Logging.git'  <--- Private Logging pod

    target 'ClassExtensionPackTests' do
        inherit! :search_paths
        # Pods for testing
    end
end

target 'ClassExtensionPack iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for ClassExtensionPack iOS
    pod 'Logging', :git => 'https://git.frobese.de/mobile/Logging.git'

end

target 'ClassExtensionPack tvOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for ClassExtensionPack tvOS
    pod 'Logging', :git => 'https://git.frobese.de/mobile/Logging.git'

end

target 'ClassExtensionPack watchOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for ClassExtensionPack watchOS
    pod 'Logging', :git => 'https://git.frobese.de/mobile/Logging.git'

end
```

#

**Comment by dnkoutso** [comment]
Not enough information to diagnose. Please file issue template and include a sample app.

Use `pod 'MyPod', :source => 'mysourc'` to override.

**Comment by dfrobese** [comment]
I try to explain a bit deeper in detail

This is the log from the pod spec lint command:

`MonteCapanne:classextensionpack dfrobese$ rm -rf /Users/dfrobese/Library/Caches/CocoaPods/Pods/Release/
MonteCapanne:classextensionpack dfrobese$ pod spec lint --verbose

  CDN: jsdelivr-cocoa Relative path: **CocoaPods-version.yml** exists! Returning local because checking is only perfomed in repo update
    ClassExtensionPack (1.0.10) - Analyzing on tvOS 11.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `ClassExtensionPack` from `/Users/dfrobese/Xcode/classextensionpack/ClassExtensionPack.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A ClassExtensionPack
  A Logging

Downloading dependencies

-> Installing ClassExtensionPack (1.0.10)
 > Git download
 > Git download
     $ /usr/bin/git clone https://git.frobese.de/mobile/ClassExtensionPack.git
     /var/folders/xz/0hnwmnt92b70426zyxdhh9nh0000gn/T/d20190611-6851-mppyh2 --template= --single-branch --depth 1
     Cloning into '/var/folders/xz/0hnwmnt92b70426zyxdhh9nh0000gn/T/d20190611-6851-mppyh2'...
  $ /usr/bin/git -C /var/folders/xz/0hnwmnt92b70426zyxdhh9nh0000gn/T/d20190611-6851-mppyh2 rev-parse HEAD
  3264484d17cfb61f7b84c2f01a6ee79f4838e5a7
  > Copying ClassExtensionPack from
  `/Users/dfrobese/Library/Caches/CocoaPods/Pods/External/ClassExtensionPack/0b15704899f1c106992c0fa57a356c71-e13ec` to
  `../../../../private/var/folders/xz/0hnwmnt92b70426zyxdhh9nh0000gn/T/CocoaPods-Lint-20190611-6851-srmvdi-ClassExtensionPack/Pods/ClassExtensionPack`

**-> Installing Logging (1.1.0)**
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/apple/swift-log.git 
`

As you can see, it takes the Logging pod from the master not from the private pod.
In the pod file I use the reference to the provate pod:

  pod 'Logging', :git => 'https://git.frobese.de/mobile/Logging.git'


Related Podfiles are appended.


[Archiv.zip](https://github.com/CocoaPods/CocoaPods/files/3277649/Archiv.zip)

**Comment by dfrobese** [comment]
NICE BUT NOT WORKING

Am 11.06.2019 um 18:05 schrieb D. Koutsogiorgas <notifications@github.com<mailto:notifications@github.com>>:


Not enough information to diagnose. Please file issue template and include a sample app.

Use pod 'MyPod', :source => 'mysourc' to override.
