### ISSUE TITLE
Update Pods.xcproject rather than targets in post_install

### ISSUE THREAD

**Issue by aelam** [CocoaPods/CocoaPods#8900]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort  to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I wanna a way to update Pods.project rather than each target.  that would be easier and enough in most cases. But I didn't find the docs at all.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts target.name
  end
end
```

**Comment by dnkoutso** [comment]
```ruby
installer.pods_project
```
_is_ the `Pods.xcodeproj`...update it and call `installer.pods_project.save` in the end.
