### ISSUE TITLE
Do not clone/use master specs repo, switch default to CDN

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#8905]
CocoaPods should no longer clone the master specs repo unless explicitly specified by the user in the `Podfile`.

Consider making the CDN source the default?

/cc @igor-makarov for 1.8.0.

**Comment by dnkoutso** [comment]
PR https://github.com/CocoaPods/CocoaPods/pull/8923

**Comment by nothingismagick** [comment]
Yeah, when using this with capacitor there is no feedback that a very, very, very large git repository is being cloned... I actually didn't know what was going on until I manually ran `$ pod install`. 

And maybe https://github.com/CocoaPods/CocoaPods/issues/8931 is related to the very high velocity of merges to the git repo. (Just a hunch)

**Comment by nothingismagick** [comment]
FYI - the master clone weighs in at 661.04  MiB.

**Comment by igor-makarov** [comment]
@nothingismagick Check out this blog post: http://blog.cocoapods.org/CocoaPods-1.7.2/
