### ISSUE TITLE
pod command not found

### ISSUE THREAD

**Issue by ArunIOS-ab** [CocoaPods/CocoaPods#8908]
In Mac OS Mojave
![Screenshot 2019-06-16 at 7 30 24 AM](https://user-images.githubusercontent.com/51868900/59558132-be65ee00-9008-11e9-8ddc-ef60cb87b234.png)

**Comment by dnkoutso** [comment]
Did you install cocoapods? This does not appear to be an issue with cocoapods library. Closing.

**Comment by ArunIOS-ab** [comment]
> Did you install cocoapods? This does not appear to be an issue with cocoapods library. Closing.

yes, but it showing pod not found while using "pod init" command too.

**Comment by ArunIOS-ab** [comment]
yes, but it showing pod not found while using "pod init" command too.

**Comment by ankitgauravapporio** [comment]
-bash: pod: command not found
yes i have installed cocoapods , even some of my old project is using the cocoapods , but when i am going for pod init for a new project its showing me this.

**Comment by jessegavin** [comment]
I am also experiencing this problem. I ran the following commands

```sudo gem install cocoapods```

Then I tried

```pod try FeedKit```

and got the following error

```zsh: command not found: pod```
