### ISSUE TITLE
Did you install cocoapods? This does not appear to be an issue with cocoapods library. Closing.

### ISSUE THREAD

**Issue by ArunIOS-ab** [CocoaPods/CocoaPods#8910]
Did you install cocoapods? This does not appear to be an issue with cocoapods library. Closing.

_Originally posted by @dnkoutso in https://github.com/CocoaPods/CocoaPods/issues/8908#issuecomment-502414697_

**Comment by ArunIOS-ab** [comment]
yes i installed cocoapods, but it shows -bash: pod: command not found

**Comment by dnkoutso** [comment]
Can you please comment on the original issue instead of opening a new one?
