### ISSUE TITLE
Build problems: '[!] CocoaPods could not find compatible versions for pod "DoubleConversion"'

### ISSUE THREAD

**Issue by davidlebor** [CocoaPods/CocoaPods#8913]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` through bitrise to build a project.

## What did you expect to happen?

Install pod dependencies, build project.

## What happened instead?

I received the following error:

Resolving dependencies of `Podfile`
[!] CocoaPods could not find compatible versions for pod "DoubleConversion":
  In snapshot (Podfile.lock):
    DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  In Podfile:
    DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)

To give a bit more background: the project previously built without incident. It still builds but cannot deploy to testflight because the xcode sdk version is too old. So I open it up and xcode, commit, try to rebuild, which is when this error appears. 

If I try to run 'pod install' locally, it produces the same error. I can solve this by running 'npm install' beforehand. At this point cocoapods installs (with some warnings, but nothing that seems related). 

So, I don't understand what seems to be going wrong -- the path to the podsec seems right...

Sorry if this isn't as detailed as is usually desired. I'm a real novice at all of this, and your patience and help would be enormously appreciated.

**Comment by dnkoutso** [comment]
Seems like something outside related to CocoaPods...something must setup those dependencies so CocoaPods can install which is probably your `npm install` command.

I am sorry but this does not appear to be a CocoaPods library functionality issue so I am going to close. We can keep discussing here if we find a bug or I recommend asking StackOverflow instead.

**Comment by davidlebor** [comment]
Can you explain what you mean by 'setup those dependencies' in this context? How would it make sense that the other pods listed in the podfile can be located, while 'DoubleConversion' cannot -- especially given that the location in the file appears to be correct (when checked)? 

And if it's 'something outside related to CocoaPods' -- how would that make sense? I'm explicitly trying to install CocoaPods, and it's not working. What 'something outside' might it be? 

Thanks in advance.

**Comment by dnkoutso** [comment]
It seems that your repo expects a configuration step to setup additional modules before CocoaPods can find them via `pod install`.

**Comment by davidlebor** [comment]
OK (I think), but why would this have randomly broken, given that the build process just fine on the same set of files just a few months ago?
