### ISSUE TITLE
Subspecs that compile ARC and non-ARC code do not have the correct compiler flags set

### ISSUE THREAD

**Issue by simonmaddox** [CocoaPods/CocoaPods#892]
Tested on 0.16.4

Given the following podspec:

``` ruby
Pod::Spec.new do |s|
  s.name         = 'Test Project'
  s.version      = '1.0'
  s.license      = 'License'
  s.summary      = 'Test Project.'
  s.homepage     = 'https://github.com/something/something'
  s.author       = { 'Some Author' => 'something@example.com' }
  s.platform     = :ios, '5.0'

  s.subspec 'arc' do |sp|
    sp.source_files = FileList['file*.*}'].exclude('file3.*')
    sp.requires_arc = true
  end

  s.subspec 'no-arc' do |sp|
    sp.source_files = 'file3.{h,m}'
    sp.requires_arc = false
  end
end
```

I'd expect that `file1` and `file2` are compiled with `-fobjc-arc` while `file3` is compiled with `-fno-obj-arc`. However, `file3` is compiled with `-fobjc-arc` instead.

So let's try something else. Change the `no-arc` subspec to:

``` ruby
s.subspec 'no-arc' do |sp|
  sp.source_files = 'file3.{h,m}'
  sp.requires_arc  = false
  sp.compiler_flags = '-fno-objc-arc'
end
```

Now `file3` is compiled with `-fobjc-arc` again.

One more try - add `s.requires_arc = false` to the main spec. `file3` is compiled with `-fobjc-arc` once more.

So how do I create a Podspec that _needs_ to have certain files compiled without ARC?

To be more specific, I'm trying to create a privately-hosted spec for @steipete's PSPDFKit (so we can do something like `pod 'PSPDFKit', :git => 'url.to.private.git.repo'` in our Podfile

**Comment by benvium** [comment]
FileList has been deprecated, and you should use `exclude_files = '/PSPDFPatches/` instead

```
Pod::Spec.new do |s|
  s.name         = 'PSPDFKit'
  s.version      = '0.0.1'
  s.license      = 'Commercial'
  s.summary      = 'PS PDF Kit.'
  s.source       = { :git => "https://github.com/example/PSPDFKit", :commit => 'sha1' }
  s.homepage     = 'https://github.com/example/PSPDFKit'
  s.author       = { 'Peter Steinberger' => 'pspdfkit@gmail.com' }
  s.platform     = :ios, '5.0'
  s.source_files = 'PSPDFKit/**/*.{h,m}'
  s.exclude_files = '/PSPDFPatches/'
  s.requires_arc = true

  s.subspec 'no-arc' do |sp|
    sp.source_files = 'PSPDFKit/PSPDFPatches.{h,m}'
    sp.requires_arc = false
  end
end
```

**Comment by steipete** [comment]
@simonmaddox we have a podspec for PSPDFKit - is there anything wrong with the official one?

**Comment by simonmaddox** [comment]
@steipete thanks. This was posted over 2 years ago, so I assume it's been resurrected for future-searchers. If I recall, there was no Podspec at the time. No longer working with this client though :)

**Comment by steipete** [comment]
Ahhh, didn't see the timestamp. Thanks :)

**Comment by benvium** [comment]
@simonmaddox Yes, I needed to have a single file in my podspec use -fno-obj-arc, and my googling led me here.

**Comment by klusinyan** [comment]
Hi all, I have one question about arc/no-arc podspec definitions. Currently I am trying to push MyLib to private git repository. The problem is similar defined above with a difference that my whole project is written in NON ARC. So together with non-arc files I have a few files written in ARC. 
There is no way to pass "pod lib lint" command. It gives me an error saying that the header declared in NON ARC are not visibile inside of ARC files. This is an example of my podspec which I am trying to push:

Pod::Spec.new do |s|
    s.name         = 'MyLib'
    s.version      = '1.0.0'
    s.summary      = 'MyLib Example.'
    s.homepage     = 'https://git.karen.it/ios/MyLib'
    s.license      = { :type => 'MIT', :file => 'LICENSE' }
    s.author       = { 'Karen Lusinyan' => 'karen.lusinyan.developerios@gamil.com' }
    s.platform     = :ios, '7.0'
    s.source       = { :git => 'https://git.karen.it/ios/MyLib.git', :tag => s.version.to_s }

    s.prefix_header_file = 'MyLib/Classes/Lib_Prefix.pch'

    arc_files = 'MyLib/Classes/Slider/**/*.{h,m}'

    s.requires_arc = false
    s.source_files = 'MyLib/Classes/**/*.{h,m}'
    s.exclude_files = arc_files

    s.subspec 'arc' do |ss|
        ss.requires_arc = true
        ss.source_files = arc_files
    end

   end

Thanks in advance.
