### ISSUE TITLE
when ${SRCROOT} is NOT the path where *. xcodeproj at make error

### ISSUE THREAD

**Issue by hkajcy** [CocoaPods/CocoaPods#8922]
# Report

## What did you do?

My project is generated by cmake. 
I have a CMakeLists.txt at some where I cd to.
I just run cmd.

mkdir -p build/ios
cd build/ios
cmake ../..
cmake -DCMAKE_TOOLCHAIN_FILE=./ios.cmake -DIOS_PLATFORM=OS -H. -Bbuild/ios -GXcode

So there is a *.xcodeproj at build/ios/*.xcodeproj.

then 

pod init
pod install

pods file installed at build/ios
## What did you expect to happen?

everything is OK.

## What happened instead?

but pod file is related to ${SRCROOT}
but in my project ${SRCROOT} is the path where cmake at
NOT the path where *.xcodeproj at

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2 (10E125)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9dfb6392311400a18520ca5447508a204de237e6
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

nothing

**Comment by dnkoutso** [comment]
You have to define it from your generated project. I am sorry this is not enough to diagnose or debug nor does it appear to be a CocoaPods library issue.
