### ISSUE TITLE
SQLite.swift pod returns error 500 on "cocoapods.org"

### ISSUE THREAD

**Issue by ypopovych** [CocoaPods/CocoaPods#8924]
Hi.
We have a problem with CocoaPods trunk.

I'm a collaborator in SQLite.swift library and I want to publish a new version. But seems as something happened on CocoaPods trunk with this library.

When I'm opening https://cocoapods.org/pods/SQLite.swift it returns error 500.

It returns the same error for `pod trunk push` command.

How can we fix it?

**Comment by dnkoutso** [comment]
Marking as dup of https://github.com/CocoaPods/CocoaPods/issues/8925.

The best I can advise is to keep trying. Nothing has changed on the backend recently.
