### ISSUE TITLE
`pod trunk push` stuck on "Internal server error" after initial failure due to Github timeout

### ISSUE THREAD

**Issue by groue** [CocoaPods/CocoaPods#8925]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod trunk push --allow-warnings GRDB.swift.podspec --verbose`

## What did you expect to happen?

[GRDB v4.1.0](https://github.com/groue/GRDB.swift/blob/v4.1.0/GRDB.swift.podspec) to be published.

## What happened instead?

After a few initial failures about timeouts reaching Github, the `pod trunk push` would never stop ending with an internal server error, as below:

```

Updating spec repo `master`
Validating podspec
    GRDB.swift (4.1.0) - Analyzing on iOS 9.0 platform.

...

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=true HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.7.2\r\nAuthorization: Token redacted\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 1084\r\n\r\n"
<- "{\"name\":\"GRDB.swift\",\"version\":\"4.1.0\",\"license\":{\"type\":\"MIT\",\"file\":\"LICENSE\"},\"summary\":\"A toolkit for SQLite databases, with a focus on application development.\",\"homepage\":\"https://github.com/groue/GRDB.swift\",\"authors\":{\"Gwendal Rou\u{e9}\":\"gr@pierlis.com\"},\"source\":{\"git\":\"https://github.com/groue/GRDB.swift.git\",\"tag\":\"v4.1.0\"},\"module_name\":\"GRDB\",\"swift_versions\":[\"4.2\",\"5\"],\"platforms\":{\"ios\":\"9.0\",\"osx\":\"10.9\",\"watchos\":\"2.0\"},\"module_map\":\"Support/module.modulemap\",\"default_subspecs\":\"standard\",\"subspecs\":[{\"name\":\"standard\",\"source_files\":[\"GRDB/**/*.swift\",\"Support/*.h\"],\"frameworks\":\"Foundation\",\"libraries\":\"sqlite3\"},{\"name\":\"SQLCipher\",\"source_files\":[\"GRDB/**/*.swift\",\"Support/*.h\"],\"frameworks\":\"Foundation\",\"dependencies\":{\"SQLCipher\":[\">= 3.4.0\"]},\"xcconfig\":{\"OTHER_SWIFT_FLAGS\":\"$(inherited) -D SQLITE_HAS_CODEC -D GRDBCIPHER -D SQLITE_ENABLE_FTS5\",\"OTHER_CFLAGS\":\"$(inherited) -DSQLITE_HAS_CODEC -DGRDBCIPHER -DSQLITE_ENABLE_FTS5\",\"GCC_PREPROCESSOR_DEFINITIONS\":\"$(inherited) SQLITE_HAS_CODEC=1 GRDBCIPHER=1 SQLITE_ENABLE_FTS5=1\"}}],\"swift_version\":\"5\"}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Thu, 20 Jun 2019 18:39:45 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:70:in `print_error'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:30:in `request_url'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk.rb:36:in `request_path'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/push.rb:85:in `push_to_trunk'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-trunk-1.3.1/lib/pod/command/trunk/push.rb:71:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

### Stack

```
   CocoaPods : 1.7.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.0 (11M337n)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : accengage - https://github.com/Accengage/CocoaPodsSpecs.git @ 1c13e11d306b4bcb515bc4df21c5d9214efbf13b
               master - https://github.com/CocoaPods/Specs.git @ aefc507c17674e982ab7f7475cfc65f7df2fbabe
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

http://github.com/groue/GRDB.swift

**Comment by dnkoutso** [comment]
@groue is it still failing for you?

**Comment by groue** [comment]
Hello @dnkoutso,

Yes, it is still failing. It's been one day now, and I've been trying multiple (!) times.

Looking at the commits to CocoaPods/Spec, it looks like  other pods are published successfully : https://github.com/CocoaPods/Specs/commits/master

Is there an alternative to `pod trunk push` I should be aware of?

**Comment by groue** [comment]
> CocoaPods Environment
> `Xcode : 11.0 (11M337n`

Oops, I was still running with `Xcode-beta.app`. Could it be the cause of the issue?

Let's reset to Xcode 10.2.1... No, same error 😢

**Comment by ypopovych** [comment]
In my case fixed by bumping version one more time (seems as something happened on first upload, and it "half-uploaded" version)

**Comment by groue** [comment]
Thanks for the tip, @ypopovych, I'll try it 👍

**Comment by dnkoutso** [comment]
I do not think Xcode version matters here but I might be wrong though.

**Comment by groue** [comment]
Thank you @ypopovych: pushing a new version 4.1.1 has fixed the problem.

@dnkoutso: it was never possible to publish 4.1.0 despite my multiple attempts, so I guess *something* remains somewhere on the server and prevents the process to successfully complete. I now recall than before those internal errors, the first `pod trunk push` failures were about timeouts reaching Github. After them, the situation settled for good on the internal server error dead-end.

So I don't close this issue, and rename it.

**Comment by groue** [comment]
I also slightly rewritten the "What happened instead?" section in the OP

**Comment by ypopovych** [comment]
In my case, I got a GitHub error too. Seems as something was broken on the server, and it "half-published" our pods.

**Comment by dnkoutso** [comment]
@groue I'd love to debug your problem with 4.1.0... not sure how to do that...are you on Slack?

**Comment by groue** [comment]
Hi @dnkoutso, Would you like me to perform a pod trunk push while you're watching? I'm OK, if it can help. I'm in Paris, France. Just paste the Slack URL here, I'll go there.

**Comment by dnkoutso** [comment]
@groue can you join https://cocoapods.slack.com? If not then DM me on Twitter (https://twitter.com/dnkoutso) and we can figure it out there!

Thanks!
