### ISSUE TITLE
Missing Landing Page on Cocoapods.org

### ISSUE THREAD

**Issue by mmujic** [CocoaPods/CocoaPods#8927]
Hello,

we recently published our pod _InfobipRTC_ to CocoaPods but it is not visible via search on Cocoapods.org homepage, and access via direct link https://cocoapods.org/pods/InfobipRTC redirects to Homepage declared in podspec file.

**Comment by dnkoutso** [comment]
Hi there same issue as https://github.com/CocoaPods/cocoapods.org/issues/417. Something is wrong with indexing or searching. Sorry for the inconvenience. Will close this and follow through in the other issue.
