### ISSUE TITLE
Static library - libtool: can't locate file for, "-" instead of "_" in the name of library

### ISSUE THREAD

**Issue by aleksandergrzyb** [CocoaPods/CocoaPods#8934]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

We are trying to switch into static frameworks in our project. We deleted `use_frameworks!` entry from `Podfile` and then CocoaPods automatically added `libPods-Target.a` into "Link Binary With Libraries" build phase of Target.

## What did you expect to happen?

I expected Target to build successfully.

## What happened instead?

Xcode gives an error when building Target:

```
error: /Applications/Xcode-10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-Target
error: /Applications/Xcode-10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-Target is not an object file (not allowed in a library)
```

## CocoaPods Environment

We are using CocoaPods `1.7.2` and Xcode `10.2.1`. Unfortunately I can't provide `Podfile`.

## How I solved the issue

The error pointed that `libPods-Target.a` library is missing. When I tapped on "+" button in "Link Binary With Libraries" build phase of Target I saw that `libPods-Target.a` library is available. I selected this library (just to be sure) and Xcode automatically changed the name of the library from `libPods-Target.a` to `libPods_Target.a` ("-" changed to "_"). After this change Target seems to be building just fine.

Hard to tell if it's an Xcode issue or CocoaPods one.

**Comment by dnkoutso** [comment]
Removing `use_frameworks!` doesnt switch to static frameworks. This is planned probably for 1.8.0.

Will need a sample app if possible to reproduce this, can you upload one?

**Comment by aleksandergrzyb** [comment]
I investigated the issue further and we had an error in our configurations. In `Pods-Target.debug.xcconfig` we are including another `.xcconfig` which was overwriting `PRODUCT_NAME` to `$(TARGET_NAME:c99extidentifier)`. That's why "-" was changed "_". Thank you and sorry for the noise.
