### ISSUE TITLE
`pod lib create testpod` produces ld warning "directory not found for option -F"

### ISSUE THREAD

**Issue by alex-vasenin** [CocoaPods/CocoaPods#8938]
* [+] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod lib create testpod`. Opened `testpod.xcworkspace` in Xcode 10.2. Build the project.

## What did you expect to happen?

The project builds without warnings.

## What happened instead?

The following warning appears (along with several others):
> ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/Developer/Library/Frameworks'

### Stack

```
   CocoaPods : 1.7.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 053ec4d59c56d16f52c6f9f9547ca5fd130195f3
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.7.2/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Just run `pod lib create anypod` and open the project.

Related issues: #4651, #5759, #7703, #7894

**Comment by dnkoutso** [comment]
Can you please provide specific steps on the `pod lib create` command? I just tried it and it worked.

**Comment by dnkoutso** [comment]
Oh sorry I read again about the warning. Yes you are right this is confirmed on my side as well.

**Comment by dnkoutso** [comment]
This can be fixed in https://github.com/CocoaPods/pod-template and does not require a cocoapods release.
