### ISSUE TITLE
Unexpected failure in build

### ISSUE THREAD

**Issue by SureshBalusu** [CocoaPods/CocoaPods#8944]
I am unable to build with latest Xcode 10.2.1. I am using 1.7.2 pods version. 
Attached error message below. Getting as unexpected failure
<img width="806" alt="Screenshot 2019-06-28 at 2 50 25 PM" src="https://user-images.githubusercontent.com/14269689/60332424-6938bd80-99b4-11e9-91ea-27f56678c057.png">

**Comment by dnkoutso** [comment]
There is no sufficient information for us to debug/diagnose. Please fill in the issue template and provide an example to reproduce it.

**Comment by GJBlog** [comment]
I has the same problem.Who help me?
