### ISSUE TITLE
use source is http and zip `Unable to read the license file`

### ISSUE THREAD

**Issue by zhuamaodeyu** [CocoaPods/CocoaPods#8945]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do? 

1. edit Profile add two source  
```
source 'https://gitee.com/wenliaokeji/Spec.git'
source 'https://github.com/CocoaPods/Specs.git'
```
2. run pod install or pod update 
```
pod install  or pod update 
```

## What did you expect to happen?

Do not display the following warning  

## What happened instead?
* The same library in multiple repos
```
[!] Found multiple specifications for `Moya (13.0.1)`:
- /Users/sss/.cocoapods/repos/silvrr-specs/Moya/13.0.1/Moya.podspec.json
- /Users/sss/.cocoapods/repos/master/Specs/8/a/7/Moya/13.0.1/Moya.podspec.json
```
*  use framework license file not found
```
[!] Unable to read the license file `FILE_LICENSE` for the spec `Coupon (0.1.9)`

```

### Stack

```
   CocoaPods : 1.7.2
        Ruby : ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.19.1
Ruby lib dir : /usr/local/Cellar/ruby/2.6.2/lib
Repositories : BinSpec - https://git.silvrr.com/TKTestGroup/TKBinSpec.git @ 0ca3fbe335404e302f45c90d52e89078d5d5d8c9
               gitee-wenliaokeji-spec - https://gitee.com/wenliaokeji/Spec.git @ dc5f5ebd36ea4bccc6af815d26180cdf39dddce6
               LibSpec - https://github.com/zhuamaodeyu/LibSpec.git @ 79dd778912ed87df83036087e4be030406ae606d
               master - https://github.com/CocoaPods/Specs.git @ 20b358756409addfc4b3ad50fb059db29dd9d836
               silvrr-specs - git@git.silvrr.com:iOS/Specs.git @ f8a3a1d3ae59ee7ee2a501ca839c9eb6c0612e46
               Specs - https://git.silvrr.com/iOS/Specs.git @ f8a3a1d3ae59ee7ee2a501ca839c9eb6c0612e46
               TKSpec - https://git.silvrr.com/TKTestGroup/TKSpec.git @ 8e23fea2b9c3d4b89d87a26554b527f56e12d83d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-packager     : 1.5.0
cocoapods-packager-pro : 1.5.4
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.3.1
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
slather                : 2.4.7
```

**Comment by dnkoutso** [comment]
Whats Coupon pod? is it public?

**Comment by dnkoutso** [comment]
Can you also upload a sample app?

**Comment by zhuamaodeyu** [comment]
Coupon is private pod,   
[Test project](https://github.com/zhuamaodeyu/PodTest.git)  
this is about first question

**Comment by dnkoutso** [comment]
Use `pod 'Moya', :source => 'https://gitee.com/wenliaokeji/Spec.git'` will remove the warning.

**Comment by zhuamaodeyu** [comment]
> 使用`pod 'Moya', :source => 'https://gitee.com/wenliaokeji/Spec.git'`将删除警告。

Hey, is there only one way? Whether warnings can be filtered by adding special attributes to the Podfile file. You think this is a good way

**Comment by dnkoutso** [comment]
Apologies yes this is the only way currently.

**Comment by zhuamaodeyu** [comment]
Can this feature be included in future plans?

**Comment by dnkoutso** [comment]
No plans to support this now. Best way to do it is by opening up a PR!

**Comment by zhuamaodeyu** [comment]
OK, thank you very much

**Comment by zhuamaodeyu** [comment]
sorry, given the example for so long. i added an example for question 2,(Unable to read the license file), you can run `pod install ` or `pod update` show this question . This problem occurs with binary type libraries  

[Test Project](https://github.com/zhuamaodeyu/PodTest.git)
