### ISSUE TITLE
cocoapods 1.7.2 not work with static_framework as 1.6.1

### ISSUE THREAD

**Issue by CodeEagle** [CocoaPods/CocoaPods#8946]
As the script below, It works in version 1.6.1, but fail at 1.7.2

```
pre_install do |installer|
  Pod::PodTarget.send(:define_method, :static_framework?) { true }
end
```
Not generating static_framework for target

**Comment by dnkoutso** [comment]
You are accessing and sending a method to a private method. There is never guarantee those will be stable.

This has now moved into https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/target/build_type.rb class.

See https://github.com/segiddins/cocoapods-packing-cubes plugin also that helps you do what you want.
