### ISSUE TITLE
Concurrent::Promises is not found in 1.7.3

### ISSUE THREAD

**Issue by hhfa008** [CocoaPods/CocoaPods#8948]
# Report
Issue with concurrent-ruby

## Env
Using Xcode 10.2: Requires CocoaPods 1.7.3 or above.

## What did you do?
 
Run `pod install`

## What did you expect to happen?

pod install normally

## What happened instead?
Concurrent::Promises is not found 

## Solution

update concurrent-ruby first!

**Comment by dnkoutso** [comment]
`gem install concurrent-ruby` or `gem update concurrent-ruby`.

Closing! thanks people can seek this issue for solution.
