### ISSUE TITLE
CDN 502 Error on CI

### ISSUE THREAD

**Issue by cltnschlosser** [CocoaPods/CocoaPods#8954]
Getting the following error on our CI machines when running `bundle exec pod repo update`. It doesn't happen every time, but we switched to using CDN today and it's already happened multiple times.
`CDN: cocoapods- Relative path couldn't be downloaded: Specs/7/1/d/lottie-ios/3.0.3/lottie-ios.podspec.json Response: 502`
🌈 
* [x ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod repo update`

## What did you expect to happen?

Work correctly, with no errors.

## What happened instead?

502 error from cdn.cocoapods.org

## CocoaPods Environment

version 1.7.3

**Comment by dnkoutso** [comment]
Yes this seems to happen infrequently. I do not think much can be done from our side, perhaps we can add retries for 5xx errors @igor-makarov?

**Comment by dnkoutso** [comment]
Who can help us diagnose and debug those issues?

**Comment by cltnschlosser** [comment]
Does `pod repo update` need to update the CDN source. Seems like if you asked for an unknown version that it could check for updates on demand.

**Comment by cltnschlosser** [comment]
If you could get it to throw 503's you would get retries from the rest gem: https://github.com/iron-io/rest/blob/master/lib/rest/client.rb#L173 😂

**Comment by dnkoutso** [comment]
lol

**Comment by igor-makarov** [comment]
That's not the gem that CP uses...

I actually can't tell by the current logging whether it's Netlify or GitHub that's giving this response.

That would be step one.

Step two would be trying to get in touch with the CDN that's erroring. I think that retrying should only be considered last resort.

**Comment by cltnschlosser** [comment]
@igor-makarov Let me know if I can help. I've been able to reproduce this consistently within ~10 minutes by doing `while bundle exec pod repo update --verbose; do; done`. If you have a branch with better logging I can reproduce the error.

I would agree that the following is the wrong approach, but I think it is working pretty well so far. Still testing.
https://github.com/cltnschlosser/Core/commit/c35c393061a214400bc6ee5459cabe839cf0fddf
I'm doing a 5 second sleep and retry.

**Comment by dnkoutso** [comment]
What about setting the number of threads to lower via `MAX_CDN_NETWORK_THREADS` env variable?

**Comment by cltnschlosser** [comment]
Running `export MAX_CDN_NETWORK_THREADS=10; while bundle exec pod repo update --verbose; do; done` with cocoapods-core 1.7.3 now. I'll let you know how long until I get an error.

Well it errored before I finished this message. Failed on the second go.

**Comment by dnkoutso** [comment]
Not sure how to debug this further. Hoping you can derive with some more logging which request actually fails, i.e is it Github or Netlify and then we can go from there.

**Comment by cltnschlosser** [comment]
Doesn't look like it's github, so I assume Netlify, not very familiar with the whole CDN process.
I changed the logging from the partial url to the full url.
```
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_8_d_d.txt Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_3_c_1.txt Response: 502
```
```
[!] CDN: cocoapods- Repo update failed - 10 error(s):
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/4.11.0/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/2.1.0/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/3.7.2/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/3.1.0/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/3.9.3/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/4.6.0/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/4.0.2/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/4.8.1/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/4.23.1/Braintree.podspec.json Response: 502
CDN: cocoapods- Relative path couldn't be downloaded: https://cdn.cocoapods.org/Specs/d/a/5/Braintree/4.8.6/Braintree.podspec.json Response: 502
```

**Comment by dnkoutso** [comment]
Thanks this is good logging a bit. 

The link directly works for me in the browser, does it work for you?

https://cdn.cocoapods.org/Specs/d/a/5/Braintree/4.8.6/Braintree.podspec.json

**Comment by cltnschlosser** [comment]
Yep, and running pod repo update works. In my earlier testing 8/270 worked after retries(would have failed with released 1.7.3). Although I think it's more common than that if you aren't just constantly running `pod repo update`.

**Comment by dnkoutso** [comment]
Its not good and I think we need to figure this out and fix it before we launch this.

**Comment by igor-makarov** [comment]
These are errors on Netlify. 

Does this happen when calling cURL repeatedly?

**Comment by igor-makarov** [comment]
I just tried it myself and it looks like a Netlify server error as reported by [Cloudflare](https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors#502504error).  

I've sent them a support request, in addition let's page @orta as he mentioned having friends who work there.

**Comment by dnkoutso** [comment]
This may be related https://news.ycombinator.com/item?id=20334924

**Comment by dnkoutso** [comment]
@cltnschlosser how are things looking now, it seems this may have been an intermittent issue that may have been fixed.

**Comment by cltnschlosser** [comment]
Looping `pod repo update` and going to lunch. I'll let you know how it goes.

**Comment by cltnschlosser** [comment]
Just canceled it now, roughly 90 minutes later. Seems like this is fixed, must of been the cloudflare issue.
