### ISSUE TITLE
Cannot remove multiple targets with post_install hook

### ISSUE THREAD

**Issue by AndyShi12** [CocoaPods/CocoaPods#8956]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report
Post install script is not adhering to multiple `remove_from_project` commands, breaking CI tools

## What did you do?

`pod install` with the following `post_install` script

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'React'
      target.remove_from_project
    end
    if target.name == 'yoga'
      target.remove_from_project
    end
  end
end
```

## What did you expect to happen?
For `React` and `yoga` to be both removed from Xcode `Pods/Targets`

## What happened instead?
- Removing a single target is fine, i.e. `React` but not `yoga`, `yoga` but not `React`
- When trying to remove **both** targets, `React` is removed, however `yoga` still exists under Target. This in turn causes a `Multiple commands produce ... libyoga.a` when building for archive.

### Stack

```
   CocoaPods : 1.7.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e96842b1bea8eff7e355aec65b5b18fcf76cd96d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
project 'ios/Test.xcodeproj'
platform :ios, '9.0'

target 'Test' do
  rn_path = 'node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # External libaries
  pod 'RNImageCropPicker', :path =>  'node_modules/react-native-image-crop-picker'
end

# Open PRs: libreact.a + libyoga.a bug
# https://github.com/facebook/react-native/issues/19573
# https://github.com/facebook/react-native/issues/12814
# https://github.com/facebook/react-native/issues/20492
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'React'
      target.remove_from_project
    end
    if target.name == 'yoga'
      target.remove_from_project
    end
  end
end

install! 'cocoapods',
  :deterministic_uuids => false
```

## Project that demonstrates the issue
https://github.com/facebook/react-native/issues/12814
https://github.com/facebook/react-native/issues/20492

**Comment by dnkoutso** [comment]
Does the target `yoga` even exist?

Sorry can you distill that down in a much smaller reproducible case? This could be anything with the RN integration.

**Comment by AndyShi12** [comment]
Yes, under Xocde/Pods. 

This is reproducible on a fresh `react-native` project
> react-native init TestProject
> pod init
> pod install

Copy/paste the Podfile above, then attempt to archive, it will throw a `Multiple commands produce ... libyoga.a` 

For the time being, I removed React/yoga and installed `react-native-image-crop-picker` manually.
