### ISSUE TITLE
Swift static vendor framework not working via cocoapods

### ISSUE THREAD

**Issue by kealdishx** [CocoaPods/CocoaPods#8957]
# Report

## What did you do?

I compiled static framework of SwiftyJSON and made it as the vendor framework of another pod named Apod. When I used Apod in my project via cocoapods, I cannot find any public class or struct of SwiftyJSON framework. For example, SwiftyJSON has the public strcut named JSON, but Xcode cannot find it after I importing it. On the other hand, Xcode can find the struct JSON when I dragged the SwiftyJSON.framework into my project directly.

## What did you expect to happen?

Compiler can find all classes、structs and other things that exposed in pure static swift frameworks.

## What happened instead?

Compiler cannot find symbols exposed of SwiftyJSON.framework.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.8
        Host : Mac OS X 10.14.5 (18F203)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.22.0
Ruby lib dir : /Users/keal/.rvm/rubies/ruby-2.5.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cf286ee2b52571d86d5cd9b33128954dd925ab7b
```

### Installation Source

```
Executable Path: /Users/keal/.rvm/gems/ruby-2.5.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[https://github.com/kealdishx/SwiftPodProj](https://github.com/kealdishx/SwiftPodProj)

**Comment by dnkoutso** [comment]
I am unable to setup your SampleApp due to https://gitlab.yc345.tv/teacher/iOS/otspecs.git repo being locked.

At a first glance your podfile is not pointing to the local pod you mentioned so nothing will integrated in CocoaPods.

If there is no response this issue will be auto-closed in a week.

**Comment by kealdishx** [comment]
You do not need access to the repo because I have executed `pod install` and you can see OTSwiftyJSON.framework at `Pods/OTSwiftyJSON/SwiftyJSON.framework`. You just need open `SwiftJSONPod.xcworkspace` and run, then you'll get `Use of undeclared type 'JSON'` error in `Mappable.swift`.

Next, you can drag `Pods/OTSwiftyJSON/SwiftyJSON.framework` and `Mappable.swift` directly to another empty project and then run.It'll be successful.

**Comment by dnkoutso** [comment]
![Screen Shot 2019-07-02 at 10 39 30 AM](https://user-images.githubusercontent.com/310370/60521693-b28b5480-9cb5-11e9-9170-ba099d22a8e8.png)

There is no reference to `SwiftyJSON.framework` in the project. I'd love to see the `OTSwiftyJSON` podspec if possible.

**Comment by kealdishx** [comment]
Here is the podspec file below

```
Pod::Spec.new do |s|
  s.name        = "OTSwiftyJSON"
  s.version     = "1.0.2"
  s.summary     = "SwiftyJSON makes it easy to deal with JSON data in Swift"
  s.homepage    = "https://github.com/SwiftyJSON/SwiftyJSON"
  s.license     = { :type => "MIT" }
  s.authors     = { "lingoer" => "lingoerer@gmail.com", "tangplin" => "tangplin@gmail.com" }

  s.platform = :ios
  s.requires_arc = true
  s.swift_version = "5.0"
  s.module_name = 'SwiftyJSON'
  s.ios.deployment_target = "8.0"
  s.source   = { :git => "https://gitlab.yc345.tv/ios/otswiftyjson.git", :tag => s.version }
  s.default_subspec = 'Framework'

  s.subspec 'Framework' do |ss|
    ss.source_files = 'fake.swift'
    ss.ios.vendored_frameworks = 'SwiftyJSON.framework'
  end

  s.subspec 'Source' do |ss|
    ss.source_files = "Source/SwiftyJSON/*.swift"
  end

end
```

**Comment by dnkoutso** [comment]
Yes looks right it should work. Sorry though I cant debug this without being able to `pod install`.

**Comment by kealdishx** [comment]
Well, I'll make another pod which you can be access tomorrow and update the example project. Once finished, I'll notify you.

**Comment by dnkoutso** [comment]
Thanks, sorry for making it difficult its just hard to diagnose/debug and iterate with the debugger if `pod install` cannot happen.

**Comment by kealdishx** [comment]
@dnkoutso I've update the sample project, and you can use `pod install` now.

[https://github.com/kealdishx/SwiftPodProj][https://github.com/kealdishx/SwiftPodProj]

**Comment by dnkoutso** [comment]
@kealdishx thanks, I tried it quickly and got:
```
[!] Unable to find a specification for `ICSwiftyJSON (= 1.0.0)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

Is ICSwiftyJSON published?

**Comment by kealdishx** [comment]
yes, you need try `pod install --repo-update`

**Comment by kealdishx** [comment]
@dnkoutso Hi, is there anything updated about this issue?

**Comment by kealdishx** [comment]
I've solved the problem and this issue can be closed.
