### ISSUE TITLE
How to use OC framework in private pod

### ISSUE THREAD

**Issue by iOSCoderJane** [CocoaPods/CocoaPods#8964]
I am using a oc framework in swift private pods.
in podspec I write that:
s.static_framework = true
s.dependency 'AlipaySDK-iOS'

then cd /Example, and pod install.
but I don't know how to use that's framework's header 'AlipaySDK.h' in Development Pods file in swift.

here is my demo, you can download that's file and cd /Example make pod install.

Looking forward to your reply！ thank you！

**Comment by dnkoutso** [comment]
This isnt enough for us to diagnose/debug. This is used for cocoapods library issues. Please ask in StackOverflow under `cocoapods` tag.

If its a bug, file a new issue with the template and sample app.
