### ISSUE TITLE
Use 'generate_multiple_pod_projects' project error

### ISSUE THREAD

**Issue by LisonFan** [CocoaPods/CocoaPods#8967]
Version
Cocoapods 1.7.3
Ruby 2.6.2

Error Info
![image](https://user-images.githubusercontent.com/9424775/60636608-cff12780-9e49-11e9-930c-d3fe71b5207b.png)

I am using a search engine to find a solution to this problem
Add configuration in podfile `config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'`, but did not solve the problem

Podfile
```
source 'https://github.com/CocoaPods/Specs.git'

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

platform :ios, '9.0'

target 'Action Extension' do
  pod 'SVProgressHUD'
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
end

```

It seems that this configuration does not take effect in the third-party library.
```
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
    end
```
![image](https://user-images.githubusercontent.com/9424775/60637538-70951680-9e4d-11e9-9a90-a4d0d51ddd87.png)

![image](https://user-images.githubusercontent.com/9424775/60638765-42660580-9e52-11e9-9d55-a35b638b97d8.png)
![image](https://user-images.githubusercontent.com/9424775/60638809-6f1a1d00-9e52-11e9-9550-742c841c5958.png)

**Comment by dnkoutso** [comment]
We cannot debug/diagnose this without a sample app.

**Comment by LisonFan** [comment]
> We cannot debug/diagnose this without a sample app.

[generate_multiple_pod_projects_demo.zip](https://github.com/CocoaPods/CocoaPods/files/3364340/generate_multiple_pod_projects_demo.zip)

**Comment by sebastianv1** [comment]
@LisonFan You are using `installer.pods_project` which only references `Pods.xcodeproj`. With multi xcode proj there is a separate project per third party pod so you need to apply your hook over that particular project. You're probably looking for `installer.generated_projects`

```ruby
...
# @return [Array<Project>] The list of projects generated from the installation.
#
attr_reader :generated_projects
...
```

You should also run `pod install --clean-install` whenever you change your post install hook with incremental installation enabled since it's not guaranteed that all projects will be generated.

**Comment by LisonFan** [comment]
> @LisonFan You are using `installer.pods_project` which only references `Pods.xcodeproj`. With multi xcode proj there is a separate project per third party pod so you need to apply your hook over that particular project. You're probably looking for `installer.generated_projects`
> 
> ```ruby
> ...
> # @return [Array<Project>] The list of projects generated from the installation.
> #
> attr_reader :generated_projects
> ...
> ```
> 
> You should also run `pod install --clean-install` whenever you change your post install hook with incremental installation enabled since it's not guaranteed that all projects will be generated.

thank you very much! Your answer helped me solve the problem

**Comment by Q14** [comment]
installer.generated_projects = [] how to reslove it

**Comment by izooto-mobile-sdk** [comment]
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

**Comment by RandallWang** [comment]
> installer.generated_projects = [] how to reslove it
If you already generate multiple pod projects, generated_projects will return []
You can try to deintegrate pods and pod install
