### ISSUE TITLE
Correct wrong cdn source in Podfile do not work

### ISSUE THREAD

**Issue by ZhangTonghai** [CocoaPods/CocoaPods#8969]
I run `pod update` with an wrong source in my Podfile, then I correct it and run `pod update` again, but is still not working.

* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
1、Change source in Podfile from `https://cdn.jsdelivr.net/cocoa/` to `https://cdn.cocoapods.org`
2、`pod update` and failed
3、correct source to `https://cdn.cocoapods.org/` and `pod update`
4、failed and get message below

`[!] CDN: cocoapods--1 Relative path couldn't be downloaded: CocoaPods-version.yml, error: Failed to open TCP connection to cdn.cocoapods.orgCocoaPods-version.yml:443 (getaddrinfo: nodename nor servname provided, or not known)`

What should I do to make the correct source make work?

## What did you expect to happen?
update all pods

## What happened instead?
pod update fail

## CocoaPods Environment

pod version 1.7.3

**Comment by dnkoutso** [comment]
Fixed here https://github.com/CocoaPods/Core/pull/552
