### ISSUE TITLE
TagManagerResources.bundle not found

### ISSUE THREAD

**Issue by VaniaTHAI** [CocoaPods/CocoaPods#8971]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
TagManagerResources.bundle not found from Android Studio 
![Error_01](https://user-images.githubusercontent.com/41766886/60711018-1e7fee00-9f3e-11e9-9951-0a86cf8f92a5.png)
![Finder](https://user-images.githubusercontent.com/41766886/60711019-1e7fee00-9f3e-11e9-838d-583caffb890a.png)

## What did you do?

I'm developing an iOS project using MOE (Multi-OS Engine).
I'm adding Google Tag Manager container from Xcode and Pods "pod 'GoogleTagManager'"
Then run "pod install"
We can build the project from XCode.
But it's fail from Android Studio with error.

## What did you expect to happen?

Project should build OK from Android Studio

## What happened instead?

I'm trying build the project from Android Studio. There is an error occurred:
"error: Resource "/Volumes/DATA/VANIA/ECO ATM/ecoATM_Mobile/ecomobile/ios/build/moe/xcodebuild/sym/Debug-iphonesimulator/GoogleTagManager/TagManagerResources.bundle" not found. Run 'pod install' to update the copy resources script."

I've tried to check the path: "/Volumes/DATA/VANIA/ECO ATM/ecoATM_Mobile/ecomobile/ios/build/moe/xcodebuild/sym/Debug-iphonesimulator/". That path doesn't existed. But "TagManagerResources.bundle" is located at: "/Volumes/DATA/VANIA/ECO ATM/ecoATM_Mobile/ecomobile/ios/build/moe/xcodebuild/Debug-iphonesimulator/".

## CocoaPods Environment

I'm using the CocoaPods 1.7.3 and have tried with v 1.5.3 also

## Podfile
platform :ios, '11.0'

target 'projectName' do
  use_frameworks!

  # Pods for Firebase and Crashlytics
  pod 'Firebase/Core', '5.11.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'
  pod 'GoogleAppMeasurement', '~> 5.3.0'
  pod 'GoogleTagManager'
  
  # Pods for Find A Kiosk Maps
  pod 'GoogleMaps'

end

target 'projectName-Test' do
  use_frameworks!

  # Pods for projectName-Test

end

**Comment by dnkoutso** [comment]
We cannot debug/diagnose this without a sample app. Please upload one and I can take a look and re-open this issue if there is an actual issue.

Please also ask StackOverflow under `cocoapods` tag.

**Comment by VaniaTHAI** [comment]
Hi @dnkoutso ,
I've uploaded an sample from here: https://drive.google.com/open?id=1prGqboKvjd4BNACSrzHLl9-bdzS7xRiN
Could you please take a look?
You can take a glance at README file before opening that sample.

Thanks,

**Comment by VaniaTHAI** [comment]
Hi @dnkoutso ,

I've uploaded a sample project here: https://drive.google.com/open?id=1XHFFdzAlyXiT0E_B0pldsr3q0BpvSwoU
Please help to take a look.
You can take a look at README file before open this sample.

Thank you so much!
