### ISSUE TITLE
Setting configuration build setting in post_install hook doesn't work

### ISSUE THREAD

**Issue by samyachour** [CocoaPods/CocoaPods#8972]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

(Reproduced on CocoaPods 1.7.3)

# Report

## What did you do?

In the `post_install` hook in my Podfile I manually set a configuration settings using `config.build_settings['ENABLE_BITCODE'] = 'NO'`

## What did you expect to happen?

I expected to run pod install and see the generated `.xcconfig` files reflect that setting value

## What happened instead?

The generated `.xcconfig` files used the platform default values ('YES' for enabling bitcode in this example)

## CocoaPods Environment

- This is from a private closed source repository so I cannot post the full Podfile, but here is the code of my `post_install` hook:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Debug'
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
            if config.name == 'Test'
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
end
```

## Project that demonstrates the issue

- This is a private closed source repository

**Comment by dnkoutso** [comment]
> I expected to run pod install and see the generated .xcconfig files reflect that setting value

You are changing it at the project / target level not the `.xcconfig` level.

Use:
```ruby
xccconfig = Xcodeproj::Config.new(path)
# edit the file here
xcconfig.save_as(path) # make sure to call that to reflect changes.
```

**Comment by dnkoutso** [comment]
I will re-open this if we find a bug but I attempted it and I correctly saw changing the project/target level instead of the `xcconfig`.

**Comment by samyachour** [comment]
@dnkoutso I was not seeing it change at the project/target level either, so you're saying it must be a quirk of my project vs one in CocoaPods?

**Comment by dnkoutso** [comment]
Dont worry I will re-open this if we get closer to a bug. Would love a sample here to repro as I can't.

**Comment by samyachour** [comment]
Understood. It's a company repository so I can't share but I will try to provide more information if I find any!

**Comment by dnkoutso** [comment]
Thank you!

**Comment by samyachour** [comment]
@dnkoutso is it normal for our `pod install` to generate `.xcconfig` files for our targets (not just for dependencies) that seem to override project settings? For example:

![image](https://user-images.githubusercontent.com/8519850/60746069-dbb81900-9f31-11e9-9353-f3a1c3c8d34b.png)
