### ISSUE TITLE
Exclude cocoapod dependency iOS 10 and below but include from the rest. 

### ISSUE THREAD

**Issue by jefhai** [CocoaPods/CocoaPods#8977]
I have an app that I want to use a cocoapod when users are on iOS 11 and above, but not on iOS 10 and 9. I know it's possible to test iOS at runtime and with macros.. But I get errors when archiving because my target still has armv7 in its supported devices, but the cocoapod only supports iOS 11 and above... Is it possible to handle this?

https://stackoverflow.com/questions/56938743/bundle-cocoapod-dependency-depending-on-ios-version

**Comment by dnkoutso** [comment]
I do not think this is supported but probably can be handled via other means.

**Comment by jefhai** [comment]
@dnkoutso any thought as to what "other means" means?
