### ISSUE TITLE
Error: Pod lib lint looks for Device

### ISSUE THREAD

**Issue by Evilsmaher** [CocoaPods/CocoaPods#8978]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Using `pod lib lint` I am having a compile error. While developing code using XCode, you can specify the device, i.e. a simulator or your actual device plugged into the computer. However, when using certain code, you have to use your device and only your device or you will run into errors. In this case, I am utilizing Metal and Swift. You can see the error [here](https://stackoverflow.com/questions/41916306/metal-texture-not-found) and I am not the only one with this issue. While developing code, easily enough, I can change the simulator to my plugged-in device and continue developing. However, while running the command `pod lib lint`, it attempts to create a xcworkspace but is unable to do so since the simulator is the default device. Thus, it is not able to compile. I have also asked this on SO: https://stackoverflow.com/questions/56911727/podspec-target-device-required. Thanks for the help in advance.

## What did you do?

Run `pod lib lint`

## What did you expect to happen?

Pod Successful

## What happened instead?

```
DepthCamera (0.1.0)
    - WARN  | [iOS] license: Unable to find a license file
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - ERROR | [iOS] xcodebuild:  DepthCamera/Camera/Renderer/MetalRenderer.swift:71:39: error: value of type 'MTLDrawable' has no member 'texture'
```

## CocoaPods Environment

```
CocoaPods : 1.7.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 92fb563a932a0e22a16cbb1cf381c4697fd9f442
```

## Project that demonstrates the issue

Link to Project: https://github.com/Evilsmaher/DepthCamera

**Comment by dnkoutso** [comment]
I do not understand the question or issue here. It seems you are having a compile error during `lint`.

Please explain further and I will re-open this issue or better yet ask StackOverflow under `cocoapods` tag.

**Comment by Evilsmaher** [comment]
I have added a report to detail my current problem as well as reference my SO post.

**Comment by dnkoutso** [comment]
Thanks, `pod lib lint` will always use the oldest simulator for the deployment target you are using is selected.

https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/validator.rb#L1033

What simulator and build target do you want to choose?

**Comment by Evilsmaher** [comment]
I need the device to target an actual device or it won't compile. Like no simulator at all. If I use simulator, then the xcworkspace gets the compile error of 'no variable found'.

**Comment by Evilsmaher** [comment]
This can be seen inside of another SO post: https://stackoverflow.com/questions/41916306/metal-texture-not-found

**Comment by dnkoutso** [comment]
Right now there is no support to target a device in order to lint. We can fold this issue under `Metal` issue support here https://github.com/CocoaPods/CocoaPods/issues/8403.

**Comment by Evilsmaher** [comment]
Okay, is there a workaround solution to post a pod similar to this issue?

**Comment by dnkoutso** [comment]
Not currently. Perhaps a runtime check whether you are running on a sim vs device. https://swiftunboxed.com/internals/targetenvironment-platform-condition/

This will make `lint` pass and you will be able to publish your pod as well as consumers can compile against your pod on a simulator.

@Evilsmaher thanks for this, there is already the issue being tracked for better Metal support so I am going to close this if its OK with you.

**Comment by Evilsmaher** [comment]
That’s fine! Thanks for the advice. As long as I can get it to compile, it should be good to go!

**Comment by dnkoutso** [comment]
yes!
