### ISSUE TITLE
Can't find variable name inside my Cocoapod

### ISSUE THREAD

**Issue by Evilsmaher** [CocoaPods/CocoaPods#8985]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I have a cocoapod, https://github.com/Evilsmaher/DepthCamera, but am unable to reference the code inside. If you notice inside my main file, https://github.com/Evilsmaher/DepthCamera/blob/master/Camera/RealTimeDepthViewController.swift, that I have a public init method. I'd like to reference this method. So, I download my pod (not the first one in my project) and call "import DepthCamera" but I cannot call this initializer.

## What did you do?
ran `pod update` after installing `pod DepthCamera`. I `import DepthCamera` in my code and it compiled. I referenced code from the pod.

## What did you expect to happen?
Install pod correctly. Be able to reference the code and successfully compile. 

## What happened instead?

I obtained a 'Use of unresolved identifier 'RealTimeDepthViewController' error. This class is from the pod and has a `public init` method I should be able to reference

## CocoaPods Environment

```
CocoaPods : 1.7.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f73bc7d7a60fd070e08932ad63d7f3663575d925
```

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARMail' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # There are other pods in here that I removed since it doesn't relate to this error.
  pod 'DepthCamera'

  target 'ARMailTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARMailUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

https://github.com/Evilsmaher/DepthCamera

**Comment by amorde** [comment]
Hello!

You need to make the class itself public

https://github.com/Evilsmaher/DepthCamera/blob/a2504cc7a74c24797b707202af65bc0d47d3eb39/Camera/RealTimeDepthViewController.swift#L11-L13

In the future, this would be a better question for [StackOverflow](http://stackoverflow.com/tags/cocoapods). We try to keep issues related to bugs within the library itself.

If you run into further issues, please do follow up here and I can re-open this issue 👍

**Comment by Evilsmaher** [comment]
LOL 😂😂😂 durr. I was overthinking and thought it was maybe a pod issue lol. Thanks for helping this rookie.

**Comment by amorde** [comment]
No problem!
