### ISSUE TITLE
Pulling in lots of extra assets

### ISSUE THREAD

**Issue by cltnschlosser** [CocoaPods/CocoaPods#8988]
🌈
* [x ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## Problem

The resources script is pulling in lots of extra assets into our app.

I've tracked it down to this commit. This is really old and was suppose to fix issues with assets in development pods, unfortunately this is causing problems specific to development pods for me. https://github.com/CocoaPods/CocoaPods/commit/e06296847aa99d0e31cee1451dab9995200ec4b5

Our project is setup like:
```
git root
  Main app code
  lib
    examplePod1
      examplePod1.podspec
      Sources
      ExampleHostApp - used for testing and faster edit test debug cycle
```

So the problem is `OTHER_XCASSETS` is pulling in test assets and example assets that are used in these smaller example apps. We have lots of example apps, so this is potentially a big issue with final app size (Haven't ran any app size metrics to see what would happen without theses pulled in).

All of our development pods use `resource_bundles`, so theoretically we only need to pull in assets from `Pods/` and `/Resources/Images.xcassets` (our main app asset catalog).

Still digging into the history of the script and testing what happens without the OTHER_XCASSETS portion of the script. I'll update this issue as I have more useful information, but it would be really nice to get a proper fix for this.
My initial thoughts are that we should only pull in assets that are included in the xcodeproj and explicitly mentioned by `resources` sections in podspecs.

## CocoaPods Environment

1.7.3

**Comment by cltnschlosser** [comment]
```
  OTHER_XCASSETS=$(find "$PWD" -iname "*.xcassets" -type d)
  while read line; do
    if [[ $line != "${PODS_ROOT}*" ]]; then
      XCASSET_FILES+=("$line")
    fi
  done <<<"$OTHER_XCASSETS"
```
For reference this is the original script.

In our project, changing the if line to this fixes the problem, but obviously this isn't a scalable solution:
```
    if [[ $line != *${PODS_ROOT}* ]] && [[ $line != *lib* ]] && [[ $line != *DevelopmentPods* ]]; then
```
`[[ $line != "${PODS_ROOT}*" ]]` < Also pretty sure this doesn't work: https://stackoverflow.com/a/2172367

**Comment by dnkoutso** [comment]
Yes this is a very well known issue. https://github.com/CocoaPods/CocoaPods/issues/8431 and my comment with more issues here https://github.com/CocoaPods/CocoaPods/issues/8431#issuecomment-460886031.

The whole xcassets mechanism is currently very broken with input and output paths and the one you posted.

We've discussed ways to re-do it from scratch but it might end up being a breaking change.

Going to close as dup please read the rest of the issues for more info.
