### ISSUE TITLE
pod spec lint failed

### ISSUE THREAD

**Issue by shahbazsaleem01** [CocoaPods/CocoaPods#8989]
## What did you do?

ℹ Trying to lint my project

## What did you expect to happen?

ℹ It should lint successfully as its running okay on xCode 10.2 without any errors or warnings

## What happened instead?

ℹ CustomAlertController/Source/BeAlertController.swift:51:14: error: 'required' initializer must be accessible wherever class 'BeAlertController' can be subclassed

ℹCustomAlertController/Source/BeAlertController.swift:55:26: error: overriding instance method must be as accessible as the declaration it overrides

## CocoaPods Environment

CocoaPods : 1.7.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2 (10E125)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6899a48be40054011dd89a436c53446c9f7f1229

## Project that demonstrates the issue

https://github.com/shahbazsaleem01/CustomAlertController

**Comment by dnkoutso** [comment]
This does not seem a CocoaPods library issue. Please use StackOverflow under `cocoapods` tag.

I might take a look but I am closing this preempitvely. If you believe its an issue with the library itself I can re-open.

**Comment by shahbazsaleem01** [comment]
I used StackOverflow at first place, but i think the issue is with lint as in code everything is perfect i believe. Please reopen

**Comment by paulb777** [comment]
@shahbazsaleem01 Use the `--no-clean` option to debug the issue in an Xcode workspace

**Comment by shahbazsaleem01** [comment]
using --no-clean i got this, can someone tell me that why this is happening

/var/folders/m9/n45grwdn7rl2p2tbydzr07tc0000gn/T/CocoaPods-Lint-20190711-95326-djscmb-CustomAlertController/Pods/CustomAlertController/Source/BeAlertController.swift:51:14: error: 'required' initializer must be accessible wherever class 'BeAlertController' can be subclassed
        required init?(coder aDecoder: NSCoder) {
                 ^
                 public 
    /var/folders/m9/n45grwdn7rl2p2tbydzr07tc0000gn/T/CocoaPods-Lint-20190711-95326-djscmb-CustomAlertController/Pods/CustomAlertController/Source/BeAlertController.swift:55:26: error: overriding instance method must be as accessible as the declaration it overrides
        override public func viewDidLoad() {
                 ~~~~~~      ^
                 open
    UIKit.UIViewController:16:15: note: overridden declaration is here
        open func viewDidLoad()
