### ISSUE TITLE
[CDN] Which CDN source should use?

### ISSUE THREAD

**Issue by rakuyoMo** [CocoaPods/CocoaPods#8992]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

When source is 'https://cdn.jsdelivr.net/cocoa/', the 'pod update' command is executed much faster than 'https://cdn.cocoapods.org/'. 

Should I use the first source?

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.

That said I'd check out the announcements blog for Qs about the CDN: http://blog.cocoapods.org/CocoaPods-1.7.2/

**Comment by rakuyoMo** [comment]
So `https://cdn.cocoapods.org/` is the official source, right? The official recommendation to use this source

**Comment by dnkoutso** [comment]
Yes.
