### ISSUE TITLE
pod install I get this error from .gitconfig    fatal: bad config line 69 in file /Users/userA/.gitconfig

### ISSUE THREAD

**Issue by a-elnajjar** [CocoaPods/CocoaPods#8994]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod install`

## What did you expect to happen?
install all pod dependencies correctly.

## What happened instead?
$ pod install
Analyzing dependencies
Setting up CocoaPods master repo
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git --progress -- master
  Cloning into 'master'...
  fatal: bad config line 69 in file /Users/userA/.gitconfig
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
You can try adding it manually in `/Users/userA/.cocoapods/repos` or via `pod repo add`.

also, I try this this fix 
Go to ~/.cocoapods/repos and run git clone https://github.com/CocoaPods/Specs.git master

I get the following error 

$ git clone https://github.com/CocoaPods/Specs.git master
Cloning into 'master'...
fatal: bad config line 69 in file /Users/userA/.gitconfig

**Comment by dnkoutso** [comment]
Seems like a bad config on your machine that prevents `git` from running.

This is not a CocoaPods library issue especially since you tried `git clone https://github.com/CocoaPods/Specs.git master` manually without using CocoaPods to do.

Open the file and check what is on line 69 and fix it or remove it.

**Comment by a-elnajjar** [comment]
I fixed the issue. it is .gitconfig
