### ISSUE TITLE
cocoapod framework static dynamic partly

### ISSUE THREAD

**Issue by kingnight** [CocoaPods/CocoaPods#8995]
this is  a  feature request or maybe I don‘t know how to do it 

```
plugin 'cocoapods-binary'
all_binary!
platform :ios, '10.0'
use_frameworks!
#enable_bitcode_for_prebuilt_frameworks!
install! 'cocoapods', 
         :generate_multiple_pod_projects => true,         
         :incremental_installation => true

abstract_target 'App' do
    pod 'SDWebImage', '~> 4.0'
    pod 'SDWebImage/WebP'
    pod 'SDWebImage/GIF'
    pod 'SnapKit'
    pod 'lottie-ios','2.5.3'
    
  target 'mainTarget' do
      inherit! :complete
      pod 'AFNetworking','~> 2.5.4'
      pod 'YYText'
  end

  target 'extension' do
      inherit! :complete
  end
  
  target 'otherTarget' do
      inherit! :search_paths
      pod 'Alamofire', '~> 4.8.2'
  end
end

pre_install do |installer|
  installer.pod_targets.each do |target|
    puts target.name
    if target.name == "SDWebImage" || target.name == "lottie-ios" || target.name == "SnapKit" 
      puts "dynamic_framework"
    else
      class BuildType
          def linkage
               :static
           end
      end 
      puts "static_framework"
    end
  end
end
```

I want to make all pod build as framework ,but some build as dynamic framework , other build as static framework  ,  for example SDWebImage  build as dynamic framework ,because main target and extension both need use this , but  AFNetworking  build as static framework, only use in main target , and speed up App launch time .

I am trying to  use pre_install  to do this , but fail ,  please how to do this ?  or this feature will be possible by use some key words in future ?

**Comment by dnkoutso** [comment]
Not currently supported but can be done via https://github.com/segiddins/cocoapods-packing-cubes plugin for now.

This is semi-tracked here https://github.com/CocoaPods/CocoaPods/issues/7579 with a public design doc https://docs.google.com/document/d/1lr2mHkwhNha5_0Wfa_pYL51MAxoro0LBxx_DUzuSu0Y/edit which will be added to GH later and hopefully for 1.8.x release.

In the mean time I will close this as we already have an issue that kind of tracks it and now they are both linked.
