### ISSUE TITLE
Strip contents of framework after install_framework

### ISSUE THREAD

**Issue by vitor-gyant** [CocoaPods/CocoaPods#8996]
So, I've a framework which requires some additional files only for x86_64 arch. Since this is a closed source vendor framework I've created a fat binary with everything which works just fine with Cocoapods.

However, I want to make sure that these additional files are not included in the device compilation / App Store submission.

Ideally, I will want to execute a script after the Embed Frameworks phase in the main target. If possible, without requiring developer to change their Podfile.

I tried the new script_phase feature on the podspec but it seems that it will always run before the Embed Frameworks since it belongs to a specific pod target.

I'd appreciate any suggestion, Thanks!

**Comment by dnkoutso** [comment]
> Ideally, I will want to execute a script after the Embed Frameworks phase in the main target. If possible, without requiring developer to change their Podfile.

Just add a script phase in Xcode or in `Podfile` for the target to perform this operation. You cannot do the script phase on the podspec if you expect to do this after the main target embed framework script phase has been executed.

Going to close as I do not see any enhancement or bug here currently. I will re-open this if we do so and we can continue discussion here.

**Comment by vitor-gyant** [comment]
@dnkoutso Sorry for your reply but I don't want to change the client Podfile. Is there another way to change which framework files are embedded into the app target ? My files are not code.

**Comment by dnkoutso** [comment]
You cannot do that without asking the client since the project belongs to them. Unless again you find a way to do it from the podspec via a `script_phase` but I cant think of quickly a way to do it.

It seems you want to "wait for the main target embed frameworks phase" to run and then do something and I cant think of a way of doing this without asking the client to do it.

**Comment by vitor-gyant** [comment]
@dnkoutso Yeah your right. Maybe you could help me with a workaround I was trying. So, what I've done was created a debug and release version of my framework. The only difference between both Podspecs is the name 'MySDK' / 'MySDK-dev' and the assets added to it. Then on the Podfile I was doing the following:

pod 'MySDK-dev', :configuration => 'Debug'
pod 'MySDK', :configuration => 'Release'

However, the pod install command says it has conflicting names on MySDK dependencies. I should say that I've also created custom Podspecs for the dependencies like 'Dep1-dev' and 'Dep2-dev'. The MySDK-dev.podspec specifies 'Dep1-dev' and 'Dep2-dev' has dependencies. 

I don't want to actually rename the frameworks to avoid having different imports on the client side.

Does this make sense ? Basically, I'm trying to ship the same framework compiled a bit different for debug vs release which solves the need to remove some assets that I have now.

Thanks again,
