### ISSUE TITLE
Catch xcrun issues around git and offer advice to install Xcode cli dev tools?

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#8997]
This comes from this issue: https://github.com/react-native-community/cli/issues/528

Looks like upgrading your OS can break the local `git`, it would be nice if CocoaPods could catch this error and present a `"you need to re-install the Xcode CLI or install git"` style message.

**Comment by sw-yx** [comment]
in my case i just needed to run some xcode devtools cli i got from stackoverflow, i would be somewhat alarmed if i got told i needed to reinstall git (even if in fact thats what xcode devtools did for me under the hood?)
