### ISSUE TITLE
Supporting UITest bundles for test specifications

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/CocoaPods#9001]
I tried to add UI test support by adding a `test_spec` which uses an `app_spec` as host app in the following configuration:

```
    s.app_spec "MyApp" do |app|
    end
    
    s.test_spec 'UITests' do |ui_tests|
      ui_tests.requires_app_host = true
      ui_tests.app_host_name = "MyPod/MyApp"
      ui_tests.dependency "MyPod/MyApp"
    end
```

There are two limitations with current integration:
1- CocoaPods generates a test bundle having product type `com.apple.product-type.bundle.unit-test`. For UITest bundles, this should be `com.apple.product-type.bundle.ui-testing`.

2- CocoaPods adds the following build settings to generated test target:
https://github.com/CocoaPods/CocoaPods/blob/714b103d2c68d80b3fa5730995d00cd16f9c1053/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_dependency_installer.rb#L143-L144

However, for a UITest bundle, these build settings should be empty. Rather, Xcode adds the following when you create a UITest bundle and select a particular host app:

```
'TEST_TARGET_NAME'=$APP_NAME   # $APP_NAME is literal name of the host app
```

---

To tweak these limitations, I provided 'TEST_TARGET_NAME' manually as part of `pod_target_xcconfig` for `test_spec` definition. And added the following `post_install` hook to `Podfile`:

```ruby
post_install do |installer|
    installer.generated_projects.each do |project|
            pbxproj = project.root_object
            pbxproj.targets.each do |target|
                if target.symbol_type == :unit_test_bundle
                    if target.name.include?('UITests')
                        target.product_type = 'com.apple.product-type.bundle.ui-testing'
                        target.build_configurations.each do |config|
                            config.build_settings.delete('TEST_HOST')
                        end
                    end
                end
            end
    end
end
```

Then I could run UI tests included in `test_spec` successfully.

To add a proper support, the following should be done:

1- Ability to set up test type for a `test_spec`. This should be easy, we can make `test_type` writer public.
2- Set proper build settings according to test type.
3- Set proper product type when creating corresponding xcodeproj.

Am I missing anything else which might be problematic?

**Comment by dnkoutso** [comment]
Awesome yes! This was built with mind that can be expanded! https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L1506

@manuyavuz either close this issue or this one https://github.com/CocoaPods/CocoaPods/issues/8507 since they are dups.

**Comment by dnkoutso** [comment]
`test_type` is already public https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/dsl.rb#L1523-L1526

**Comment by manuyavuz** [comment]
#8507 also mentions about providing a way to name generated targets. I would like to have that too, but it's better if we keep this isolated.

@mikehaney24, would you like to modify your original issue as request for custom target names for test specs?

**Comment by dnkoutso** [comment]
@mikehaney24 btw I think after this lands you can potentially monkey-patch https://github.com/CocoaPods/CocoaPods/pull/9002/files#diff-3dcc246453139b4a892d9e3625c9c2eeL491 as a workaround to your issue. Its a big ugly but will work
