### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Alamofire":

### ISSUE THREAD

**Issue by Jiboxiake** [CocoaPods/CocoaPods#9003]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I was using pod Alamofire (~> 5.0.0-beta.5)  in my pod file  

## What did you expect to happen?
Pod should generating a pod file for me and install all dependencies

## What happened instead?
I got [!] CocoaPods could not find compatible versions for pod "Alamofire":
  In Podfile:
    Alamofire (~> 5.0.0-beta.5)

Specs satisfying the `Alamofire (~> 5.0.0-beta.5)` dependency were found, but they required a higher minimum deployment target.

## CocoaPods Environment

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

### Stack

```
   CocoaPods : 1.7.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F203)
       Xcode :  ()
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ abd9f3a3500a375c4e5e712aeb028542c4ddcb3b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'

target 'real time chart' do
  use_frameworks!
  pod 'Charts', '~> 3.3.0'
  pod 'PusherSwift', '~> 7.0.0'
  pod 'Alamofire', '~> 5.0.0-beta.5'
end

## Project that demonstrates the issue
I got nothing yet

**Comment by Jiboxiake** [comment]
FYI, I do have Xcode-beta installed. But it's not through App Store. I don't know why it doesn't show the version

**Comment by dnkoutso** [comment]
Your deployment target is set to 9.0 but Alamofire is on https://github.com/Alamofire/Alamofire/blob/master/Alamofire.podspec#L12 `10.0`.

Please use StackOverflow under `cocoapods` tag for these questions.
