### ISSUE TITLE
Use of undeclared type...

### ISSUE THREAD

**Issue by jeromeDefReputation** [CocoaPods/CocoaPods#9005]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Attempted to create a private pod for an internal framework
Ran command: `pod repo push RPLoginFW ~/Desktop/RPLoginFW.podspec --verbose`

## What did you expect to happen?
Expected all `lint`checks to pass and no warnings, errors

## What happened instead?

The specification does not validate

### Stack

```
   CocoaPods : 1.7.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a1420cb17d98c9f1d2ab329ef6eca15b322fc125
```

## Project that demonstrates the issue
![CocoaPods pod repo push step](https://user-images.githubusercontent.com/45769254/61251552-9fde3a00-a70f-11e9-8175-193bbd9da556.png)
![Cocoapods podspec](https://user-images.githubusercontent.com/45769254/61251319-f0a16300-a70e-11e9-9411-89104352ad69.png)

)
Unable to share at this time because it's a private repository.  Are only 'open' or 'public' keywords supported in CocoaPods for creating the pod?  This is meant to be an internal/private framework within our organization that we want to track with dependency management but it doesn't make sense for some of these classes to be `public` or `open`.

**Comment by paulb777** [comment]
Those look like build errors in your code. Use the `--no-clean` option to `pod spec lint` to get an Xcode workspace to debug.

**Comment by jeromeDefReputation** [comment]
Hi @paulb777 , thanks for the quick response.  Here's the `pod spec lint --no-clean` result.
![pod lint](https://user-images.githubusercontent.com/45769254/61252207-a40b5700-a711-11e9-93a3-9159f1e8c9fc.png)

**Comment by paulb777** [comment]
@jeromeDefReputation Open the workspace printed out at the bottom and you should be able to reproduce and debug the build errors.

**Comment by jeromeDefReputation** [comment]
Hi @paulb777 the issue was due to to a duplicate `Model` definition in our master remote version of the code vs. the local and we solved that, I ran into another issue with pod installation that I can post on a different issue.

**Comment by dnkoutso** [comment]
Just use this issue and post an update on what the other issue is.

**Comment by jeromeDefReputation** [comment]
I was able to `pod repo push` successfully.  Attempted to do a `pod install` into a separate project, however, I got the error: `Unable to find a specification for RPLoginFW`.  After some research, I did a `pod setup && rm -rf ~/Library/Caches/Cocoapods` which completes successfully but the result of a `pod search RPLoginFW` is below...


<img width="1069" alt="pod search RPLoginFW" src="https://user-images.githubusercontent.com/45769254/61328915-ee9fd880-a7d0-11e9-876c-c3e8f77c104a.png">

**Comment by dnkoutso** [comment]
Once you publish you need to do `pod install --repo-update` so the repo is updated and can see the new version.

Search is a bug here https://github.com/CocoaPods/cocoapods.org/issues/416

Closing for now.

**Comment by jeromeDefReputation** [comment]
@dnkoutso yes, I did that.  Same result.

**Comment by dnkoutso** [comment]
I do not understand the issue further. Please provide concise and precise steps of the issue and I can re-open it maybe.

**Comment by jeromeDefReputation** [comment]
Steps:
1) `pod repo push RPLoginFW RPLoginFW.podspec --allow-warnings` from the framework path to push the repo up to CocoaPods.
2) Change directory to project which I want to include the desired pod
3) Include `pod RPLoginFW` into project's podfile
3) `pod install --repo-update` as instructed
4) Receive errors that CocoaPods was `unable to find a specification for RPLoginFW`

<img width="1665" alt="Screen Shot 2019-07-16 at 2 39 08 PM" src="https://user-images.githubusercontent.com/45769254/61331908-c23b8a80-a7d7-11e9-8a37-7116198860dd.png">

**Comment by dnkoutso** [comment]
It seems you pushed to a private repo, you need to add that in your `Podfile` as a `source` declaration for CocoaPods to find specs from. It seems you only have the master specs repo which is only for public pods.

Sorry please continue with Stackoverflow under `cocoapods` tag. This does not appear to be an issue with the CocoaPods library.
