### ISSUE TITLE
podspec for static frameworks and swift files

### ISSUE THREAD

**Issue by arielelkin** [CocoaPods/CocoaPods#9007]
* [ x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Tried to `pod spec lint` https://github.com/arielelkin/ios-streaming-sdk

## What did you expect to happen?

Success.

## What happened instead?

Series of errors such as: 
` error: use of undeclared type 'SPTSession'`

## CocoaPods Environment

CocoaPods : 1.7.2

## Project that demonstrates the issue

https://github.com/arielelkin/ios-streaming-sdk

Also see `SpotifyWrapper/SpotifyWrapper.xcodeproj`.

**Comment by dnkoutso** [comment]
There is no modulemap file inside the vendored `.framework`. You cannot import anything from Swift without one.

Please ask the vendor to add them so it can properly be imported.

Sample `module.modulemap`

```
framework module SpotifyAuthentication {
   umbrella header "SpotifyAuthentication.h"

   export *
   module * { export *}
}
```

Place it inside `SpotifyAuthentication.framework/Modules` folder.

Closing as its a non-cocoapods library issue.

**Comment by dnkoutso** [comment]
You also have a typo in your podspec:
```ruby
s.swift_versions = '5.0'
```

**Comment by arielelkin** [comment]
Thanks much, @dnkoutso, adding the modulemap files in my fork did the trick. 

Thanks also for flagging the typo in my podspec. Note that I got it from the sample in https://guides.cocoapods.org/syntax/podspec.html, so you may want to update that too.

**Comment by dnkoutso** [comment]
I do not see the typo.

**Comment by arielelkin** [comment]
ah, no you're right. Both `swift_version` and `swift_versions` are valid keys, but they expect different things.. Got confused with  https://guides.cocoapods.org/syntax/podspec.html#swift_versions

**Comment by dnkoutso** [comment]
To be clear they do not expect different things. You can use the same values for either. The singular version is just a convenience.
