### ISSUE TITLE
pod search error

### ISSUE THREAD

**Issue by yinjining** [CocoaPods/CocoaPods#9012]
pod trunk push  xxx ,  successful,the path is“Specs/d/6/f/JNAppDelegateManager/0.3.0/JNAppDelegateManager.podspec.json”，But I can't pod search it，I tried the official website (https://cocoapods.org) and didn't find JNAppDelegateManager. What should I do?

**Comment by dnkoutso** [comment]
Dup of https://github.com/CocoaPods/cocoapods.org/issues/416

**Comment by yinjining** [comment]
@dnkoutso Is there no solution to this problem yet?

**Comment by dnkoutso** [comment]
No not currently.
