### ISSUE TITLE
inhibit_all_warnings! breaks with Swift files in Xcode11 beta 4

### ISSUE THREAD

**Issue by icecrystal23** [CocoaPods/CocoaPods#9013]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`, tried to compile my project with Xcode 11 beta 4

## What did you expect to happen?

The project compiles successfully

## What happened instead?

I got a swift compilation error

    <unknown>:0: error: unknown argument: '-w'
    <unknown>:0: error: unknown argument: '-Xanalyzer'
    <unknown>:0: error: unknown argument: '-analyzer-disable-all-checks'
    Command CompileSwiftSources failed with a nonzero exit code

## CocoaPods Environment

Podfile option `inhibit_all_warnings!` seems to be causing this, when applied to Swift files.

## Project that demonstrates the issue

TODO: Create sample project.  Should be easy: include pod Pulley with inhibit_all_warnings!
and try to build.

## Note about a potential fix

Search for "-w -Xanalyzer -analyzer-disable-all-checks" (currently showing up in `pod_target_installer.rb` in my code base, but it could be outdated) for a clue as to where a fix needs to be worked in.  These need to be skipped for Swift files.  Potentially another solution for ignoring warnings in Swift code will need to be applied.

**Comment by dnkoutso** [comment]
Whats the way to inhibit warnings for Swift files? Definitely something we can fix.

**Comment by icecrystal23** [comment]
Set this on the target:

    SWIFT_SUPPRESS_WARNINGS = YES;

**Comment by dnkoutso** [comment]
Has this been the case for Xcode 10? Sorry I do not know from the top of my head.

**Comment by dnkoutso** [comment]
Looks like Xcode 8 https://miqu.me/blog/2016/07/31/xcode-8-new-build-settings-and-analyzer-improvements/

**Comment by dnkoutso** [comment]
Hmmm we are already removing `.swift` files here https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L282-L296

**Comment by dnkoutso** [comment]
Was reading it wrong. We do not remove `.swift` files there.

**Comment by dnkoutso** [comment]
PR is out.

**Comment by icecrystal23** [comment]
Cool, thanks for the quick turnaround!

**Comment by dnkoutso** [comment]
Shipped with 1.7.5.

**Comment by ilosqut** [comment]
<unknown>:0: error: unknown argument: '-w' still exist

**Comment by dnkoutso** [comment]
Please upload sample app that demonstrates the issue.

**Comment by ZhangJialinZack** [comment]
> Shipped with 1.7.5.

Thank u. It works! Just use Cocoapods 1.7.5, then  run `pod install`.

**Comment by jacobokoenig** [comment]
Same thing here with XCode11 beta 4. I'm sure is fairly replicable. Offending pods in my case are alamofire, kingfisher and hero.

**Comment by africanSuperStar** [comment]
I'm having the same issue on XCode11 beta 4. In my case p2.oAuth2-iOS
