### ISSUE TITLE
Separating downloading form integrating

### ISSUE THREAD

**Issue by grav** [CocoaPods/CocoaPods#9020]
We're evaluating using [XcodeGen](https://github.com/yonaskolb/XcodeGen) for generating our project file. 

For CocoaPods support, the XcodeGen docs [suggest](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/FAQ.md#can-i-use-cocoapods) running `pod install` after generating the project file. 

But we're checking in our `Pods` directory in order to have fewer integration points (the CocoaPods repo) and speed up our build process, so going back to `pod install` is not ideal

Would it be possible to separate the download step from the integration step, so that we could for instance run something like `pod integrate` to just use existing pods for creating and updating workspace/project files?

**Comment by orta** [comment]
There's an option for having CocoaPods just download [in a Podfile](https://guides.cocoapods.org/syntax/podfile.html#install_bang) - `integrate_targets` which might be what you want.

**Comment by dnkoutso** [comment]
Going to close preemptively.
