### ISSUE TITLE
SteviaLayout git url error

### ISSUE THREAD

**Issue by vtesoho** [CocoaPods/CocoaPods#9021]
/User/****/.cocoapods/repos/master/Specs/a/3/3/SteviaLayout/****

git address replace
https://github.com/freshOS/Stevia.git

**Comment by orta** [comment]
Hey there, this looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this doesn't look like.
