### ISSUE TITLE
@testable import <module_name> gives compile error Failed to load module <module_name>

### ISSUE THREAD

**Issue by artemisia-absynthium** [CocoaPods/CocoaPods#9022]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

* Create a brand new iOS Single View App project with Unit Tests checked
* Run `pod init`
* Add any pod
* Run `pod install`
* Open workspace in Xcode

## What did you expect to happen?

The project should compile as before adding Cocoapods.

## What happened instead?

In the test target, the `@testable import <module_name>` row, has a compile error saying `Failed to load module <module_name>`.

### Stack

```
   CocoaPods : 1.7.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1cbf89150451465b25cace1c344432b9b81ab0d6
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '12.0'

target '<module name>' do
  use_frameworks!

  pod 'Moya', '~> 13.0'
  pod 'UICKeyChainStore'
  pod 'MaterialComponents/Snackbar'

  target '<module name>Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '<module name>UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue

Any brand new project with that Podfile can reproduce the issue, I'm experiencing the same issue in every project I'm working on, so I suspect it could also be a Podfile error on my side but I absolutely have no clue and cannot find any specific info on the web.

**Comment by dnkoutso** [comment]
is `<module name>` an app or a framework?

**Comment by dnkoutso** [comment]
@artemisia-absynthium this works for me.

<img width="1512" alt="Screen_Shot_2019-07-19_at_4_55_50_PM" src="https://user-images.githubusercontent.com/310370/61571129-2ebbc100-aa46-11e9-96aa-1e7f039e0266.png">

I am going to close preemptively and I will re-open if we find a bug. Please also upload a sample app that reproduces the issue as I cannot reproduce here.

**Comment by artemisia-absynthium** [comment]
@dnkoutso it was an app. Eventually I was able to solve the issue by delving deeper in the build settings, maybe something got corrupted while building the workspace, it's really hard to know the exact reason behind it, I'll update here if I find any clue. Thanks a lot!
