### ISSUE TITLE
No such module 'Framework'

### ISSUE THREAD

**Issue by tanyaberezovsky** [CocoaPods/CocoaPods#9025]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Added SwiftSocket to an existing project. The build process return No such module 'SwiftSocet'.

## What did you do?
added pod 'SwiftSocket' to Podfile
and run: pod update
## What did you expect to happen?

To be able to import SwiftSocket in my project and start using it
## What happened instead?
Can't use it. Receiving an error No such module 'SwiftSocket'.
In Pods project, SwiftSocket added as yellow folder instead a red target image. 
Look like it mistakenly added as different type of target. 
![Screen Shot 2019-07-21 at 19 58 08](https://user-images.githubusercontent.com/4649101/61594234-1dafb300-abf2-11e9-9140-47b25074f225.png)

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4b6826d3ae2b7f4155d0794b8196ea30908f657f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

def import_pods
    pod 'Fabric'
    pod 'Crashlytics', '~> 3.13'
    pod 'GoogleMaps', '~> 3.1'
    pod 'GooglePlaces', '~> 3.1'
    pod 'MobileVLCKit', '~> 3.3'
pod 'SwiftSocket'
   # pod 'CocoaAsyncSocket'
#, '~> 7.6'
    #pod 'Mixpanel'
end

target 'Crow' do
    import_pods
end

target 'Telesikring' do
    import_pods
end

target 'Mondial' do
    import_pods
end

target 'SIM' do
    import_pods
end

target 'Smartsikring' do
  import_pods
end
```

**Comment by dnkoutso** [comment]
Need a sample app. Please upload one as I was able to successfully compile a project with SwiftSocket locally.

**Comment by tanyaberezovsky** [comment]
Thanks for quick answer. I couldn't send you a source project so I created a test one and in test project I received another error 'unsupported swift version' in SwiftSocket itself, the swift version definition was missing and some how I wasn't receive this in source project. After I fixed 'unsupported swift version' project compiles successfully and I'm able to use SwiftSocket.
