### ISSUE TITLE
Build setting values use wrong capitalization of user home dir

### ISSUE THREAD

**Issue by Thomvis** [CocoaPods/CocoaPods#9027]
🌈

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
- Run `pod install`
- Look inside a pod's .xcconfig

## What did you expect to happen?
- See that values for keys such as `PODS_TARGET_SRCROOT` have the correct capitalization of the home dir (i.e. `thomas` not `Thomas`)

## What happened instead?
- The home dir is written with a capital "T"

Example: `PODS_TARGET_SRCROOT = ${PODS_ROOT}/../../../../../../Thomas/Highstreet/Core/iOS`

### Stack

```
   CocoaPods : 1.7.2
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/thomas/.rubies/ruby-2.4.1/lib
Repositories : highstreetapp-services-components-cocoapods - https://gitlab.highstreetapp-services.com/components/cocoapods.git @ 43d05ff57b12f45e82ed45dcffdcc4faeab35a70
               master - https://github.com/CocoaPods/Specs.git @ 9407c5f116ed97e7c9e4f2d0c3d3c2bf76a6ab21
```

### Installation Source

```
Executable Path: /Users/thomas/.gem/ruby/2.4.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-binary      : 0.4.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-rome        : 1.0.1
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
earlgrey              : 1.14.0
slather               : 2.4.5
```

### Podfile
Not included. Don't think it's relevant, but I can provide a cleaned up version if needed.

---

## Notes
- Case doesn't matter on macOS, but I pass the value of `PODS_TARGET_SRCROOT` as an environment variable to my iOS tests running in the simulator which is case sensitive.
- Executing `Pathname.new("/Users/thomas/Highstreet/Core").relative_path_from(Pathname.new("/Users"))` in irb does show the correct capitalization of the home dir.

**Comment by dnkoutso** [comment]
probably an issue yes. Not sure how or why this is capitalized. Could use some help. Start here https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/target/pod_target.rb#L771-L773

**Comment by Thomvis** [comment]
Found the issue, I think it was my own mistake. Sorry.

I was using the wrong capitalization in the `file` option of a development pod, so I guess CocoaPods is behaving correctly.
