### ISSUE TITLE
Intercom Error on pod -v 1.7.5 not happening on 1.7.4

### ISSUE THREAD

**Issue by Sethmr** [CocoaPods/CocoaPods#9028]
While trying to install Intercom on any version I receive this error since v1.7.5
```

[!] Error installing Intercom
[!] /usr/bin/curl -f -L -o /var/folders/6q/f10gzsnn5ml6vq5yq1chbfxr0000gn/T/d20190722-22895-i2gb93/file.tgz https://github.com/intercom/intercom-ios/releases/download/5.4.0/CocoaPods.tar.gz --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 1 seconds. 2 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 1 retries 
Warning: left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 500 Internal Server Error
```

**Comment by Sethmr** [comment]
Error was resolved by running `sudo gem uninstall cocoapods` and then `sudo gem install cocoapods`

**Comment by dnkoutso** [comment]
Github is having issues today. This is a network error 500 issue.

**Comment by Sethmr** [comment]
Uninstalling and reinstalling worked.... I was testing across multiple computers..... this was not a GitHub issue in the sense that it was correlating with the Cocoapods version.

**Comment by dnkoutso** [comment]
Nothing has changed between the two versions regarding this code. You were just getting lucky between the versions.

https://www.githubstatus.com/

The error message clearly says 500.

**Comment by Sethmr** [comment]
Wow... that is crazy.

I guess I'll blame GitHub since... 
I just refreshed this page and got a version where the issue didn't exist 
...into a version where it existed prior to any comments 
...into a version that is how it is now.

**Comment by Sethmr** [comment]
It must have been correlating with the different networks the computers are connected through then. That is still quite strange.
