### ISSUE TITLE
Pod Target Management

### ISSUE THREAD

**Issue by CrystalBlack** [CocoaPods/CocoaPods#9031]
# Report
I have a sub target named Ku and parent target named LibDemo. 
Below is my Podgfile:
```
platform :ios, '9.0'

workspace 'LibDemo.xcworkspace'

target 'LibDemo' do
  target :Ku do
    project 'Ku/Ku'
    pod 'Masonry'
  end
end
```

## What did you do?

pod install

## What did you expect to happen?

I wish Ku Target can use Masonry pod, LibDemo Target cant use.

## What happened instead?

Both subTarget and parentTarget can use Masonry pod.

## CocoaPods Environment
```
CocoaPods : 1.7.5
Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
RubyGems : 2.5.2.3
Host : Mac OS X 10.14.4 (18E226)
Xcode : 10.2.1 (10E1001)

cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Can you upload a sample I think this is due to legacy header search paths which we cant do something about.

The best bet to avoid this is to split the two targets into two top level targets.

**Comment by CrystalBlack** [comment]
Thank you for your reply！！

This my sample.
https://github.com/CrystalBlack/QuestionDemo

I tried again. 
If `QuestionDemo Target` use pod (eg. Masonry in my sample) belong to `ModuleA` subTarget.
I can only compiled it. But run failed.

But , if i use `Masonry` in my `ModuleA` subTarget. I cant run success.
So, How do I configure my Podfile.

I wish :
use `Masonry` and `MBProgressHUD` in ModuleA Target.
use `SDWebImage` and `MBProgressHUD` in ModuleB Target.
use `MBProgressHUD` in QuestionDemo Target.

**Comment by dnkoutso** [comment]
You shouldn't link `MBProgressHUD` at the app target if you are using static libraries since it will get linked to both ModuleA and ModuleB since they inherit from QuestionDemo app.

You will get
```
objc[71920]: Class MBProgressHUDRoundedButton is implemented in both /Users/dimitris/Library/Developer/Xcode/DerivedData/QuestionDemo-bvuhzfcziqgwfnexdiyiazyvdzrg/Build/Products/Debug-iphonesimulator/ModuleB.framework/ModuleB (0x10fe5f1e8) and /Users/dimitris/Library/Developer/CoreSimulator/Devices/FE47DE0C-2439-4FB2-9B0E-45409E10955C/data/Containers/Bundle/Application/858951F1-14AC-42EC-B01D-4871051E99FF/QuestionDemo.app/QuestionDemo (0x10f038c40). One of the two will be used. Which one is undefined.
```

Warnings like I did.

**Comment by CrystalBlack** [comment]
1. `ModuleA ` and `ModuleB ` used `static  framework`. In my sample, i can't run it successfully. It will be crashed. In subTarget, i get `-[UIImageView sd_setImageWithURL:]: unrecognized selector`error. But, if i move dependent libraries to `QuestionDemo` Target, it's ok.

2.If i used `dynamic  framework` in  `ModuleA ` and `ModuleB `.  All dependent libraries could be called in any file. 

3.I don't know what changes you made. But, I don't get the warnings like you said.

4.Could you please revise my Responsitory with merge request? if you can solve my problem whether by `dynamic  framework` or `static  framework`.

Finally, thank you for taking the time to answer my question.

**Comment by CrystalBlack** [comment]
I expect the result:
`Main Target` dependent on `podA`.
`Main Target` link a `subTargetA`. `subTargetA` dependent on `podB`, and inherit `Main Target`.

`Main Target` can use `podA` but not `podB`.
`subTargetA` can use `podA` and `podB`.

**Comment by CrystalBlack** [comment]
> You shouldn't link `MBProgressHUD` at the app target if you are using static libraries since it will get linked to both ModuleA and ModuleB since they inherit from QuestionDemo app.
> 
> You will get
> 
> ```
> objc[71920]: Class MBProgressHUDRoundedButton is implemented in both /Users/dimitris/Library/Developer/Xcode/DerivedData/QuestionDemo-bvuhzfcziqgwfnexdiyiazyvdzrg/Build/Products/Debug-iphonesimulator/ModuleB.framework/ModuleB (0x10fe5f1e8) and /Users/dimitris/Library/Developer/CoreSimulator/Devices/FE47DE0C-2439-4FB2-9B0E-45409E10955C/data/Containers/Bundle/Application/858951F1-14AC-42EC-B01D-4871051E99FF/QuestionDemo.app/QuestionDemo (0x10f038c40). One of the two will be used. Which one is undefined.
> ```
> 
> Warnings like I did.
