### ISSUE TITLE
No such module 'Framework' 

### ISSUE THREAD

**Issue by tanyaberezovsky** [CocoaPods/CocoaPods#9033]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Added CryptoSwift pod to an existing project. Originally this project was an Obj-C but now it's mix Obj-C and Swift. The build process return No such module 'CryptoSwift'.

## What did you do?
added pod 'CryptoSwift' to Podfile
and run: pod update
## What did you expect to happen?

To be able to import CryptoSwift in my project and start using it
## What happened instead?
Can't use it. Receiving an error No such module 'CryptoSwift'.

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4b6826d3ae2b7f4155d0794b8196ea30908f657f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

def import_pods
    pod 'Fabric'
    pod 'Crashlytics', '~> 3.13'
    pod 'GoogleMaps', '~> 3.1'
    pod 'GooglePlaces', '~> 3.1'
    pod 'CryptoSwift'
end

target 'Crow' do
    import_pods
end

target 'Telesikring' do
    import_pods
end

target 'Mondial' do
    import_pods
end

target 'SIM' do
    import_pods
end

target 'Smartsikring' do
  import_pods
end
```

**Comment by dnkoutso** [comment]
Wasnt this the same as https://github.com/CocoaPods/CocoaPods/issues/9025?

**Comment by dnkoutso** [comment]
Its because of this:
```
Showing Recent Messages
Target 'Pods-Telesikring' of project 'Pods' was rejected as an implicit dependency for 'Pods_Telesikring.framework' because its architectures 'x86_64' didn't contain all required architectures 'i386 x86_64'
```

**Comment by dnkoutso** [comment]
Its definitely due to this the dependencies are not being built. I am uncertain if the issue is in your project or in CocoaPods integration.

@amorde any ideas?

**Comment by dnkoutso** [comment]
@amorde for some reason `target_inspector` returns `[]` array when inspecting the project. Not sure why. Perhaps because project is Xcode 6.3 compatible? Still could use some help figuring this out.

**Comment by amorde** [comment]
Will try to look into this today but yes we do change architecture settings based on iOS & Project versions, except I don’t think that happens in the inspector I think it’s in the analyzer

**Comment by dnkoutso** [comment]
```ruby
          archs = target_requires_64_bit ? ['$(ARCHS_STANDARD_64_BIT)'] : target_inspection.archs
```
but I think `target_inspection.archs` are `[]`

**Comment by tanyaberezovsky** [comment]
I reinstalled CryptoSwift three times each time I changed Project Format to Xcode 8/9.3/10 compatible but still can't recognise this framework in my project.

**Comment by amorde** [comment]
Sorry for the delay - @tanyaberezovsky do you have an example project I could look at?

As far as the `ARCHS` setting, CocoaPods will enforce `ARCHS_STANDARD_64_BIT` if either:
* The platform is `macOS`
* The platform is iOS, and:
  * The deployment target is iOS 11.0 or higher
  * The .xcodeproj object version is less than 50, or missing. Xcode 10 will emit a warning if we specify this value because Xcode wants to automatically determine this setting based on the platform and deployment target

**Comment by Sega-Zero** [comment]
Facing the same issue when generating a new project with pods and adding pod 'HWPanModal' + not specifying `use_frameworks!`. Static config doesn't work, frameworks config - does work.
