### ISSUE TITLE
Embed Pods Frameworks incorrectly removed

### ISSUE THREAD

**Issue by revolter** [CocoaPods/CocoaPods#9043]
* [x] 🌈 I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Removed the `TwitterKit` pod from the `Podfile`;
- Ran `pod install`.

## What did you expect to happen?

The `[CP] Embed Pods Frameworks` build phases should not be removed.

## What happened instead?

They were completely removed, even if the `*-input-files.xcfilelist` file was not empty after `pod install`.

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A512f)
       Xcode : 11.0 (11M374r)
         Git : git version 2.21.0 (Apple Git-120)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 39fd35e1393010fcdce3e5c74ee947b9be01ffb9
```

### Installation Source

```
Executable Path: /Users/revolt/.gems/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# frozen_string_literal: true

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!

install!('cocoapods')

def defaults
    pod 'FLEX', git: 'https://github.com/Flipboard/FLEX', commit: 'ab9515c', configurations: %w[Debug Staging]
    pod 'Fingertips', configurations: %w[Debug Staging]

    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'GoogleSignIn'
    # pod 'TwitterKit'

    pod 'Crashlytics'
    pod 'Flurry-iOS-SDK/FlurrySDK'

    pod 'SQLCipher'

    pod 'PureLayout'
    pod 'SDVersion', git: 'https://github.com/revolter/SDVersion.git', branch: 'fork'
    pod 'Typeset', git: 'https://github.com/revolter/Typeset.git', branch: 'fork'

    pod 'AFNetworking'

    pod 'JazzHands', git: 'https://github.com/revolter/JazzHands.git', branch: 'fork'
    pod 'LUNSegmentedControl', git: 'https://github.com/revolter/LUNSegmentedControl.git', branch: 'fork'
end

target '<TargetName>' do
    defaults
end

post_install do |installer|
    puts("\nUpdating Pods project's targets")

    pod_build_settings_names = %w[HEADER_SEARCH_PATHS LIBRARY_SEARCH_PATHS OTHER_CFLAGS OTHER_LDFLAGS]

    installer.pods_project.targets.each do |pod_target|
        puts("\tUpdating \"#{pod_target.name}\" target")

        pod_target.build_configurations.each do |build_configuration|
            if pod_target.name == 'FLEX'
                build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'SQLITE_HAS_CODEC=1']
                build_configuration.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)', '${PODS_ROOT}/Headers/Public/SQLCipher']
            end

            build_configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'

            xcconfig_path = build_configuration.base_configuration_reference.real_path

            xcconfig = File.read(xcconfig_path)

            xcconfig.slice!(' -l"sqlite3"')

            # Only run this for macOS
            xcconfig.slice!(' -weak_framework "ARKit"')
            xcconfig.slice!(' -framework "OpenGLES"')

            unless (pod_target.name =~ /^Pods-/).nil?
                pod_build_settings_names.each do |build_setting_name|
                    xcconfig.sub!(/^(#{build_setting_name})/, 'PODS_\1')
                end
            end

            File.open(xcconfig_path, 'w') { |file| file << xcconfig }
        end
    end

    puts()
end
```

_(I removed some parts of the `Podfile` for privacy reasons)_

## Project that demonstrates the issue

I don't currently have time to try to reproduce it 😞

**Comment by dnkoutso** [comment]
Unfortunately without a sample app we cannot debug/diagnose easily. Please provide one.

**Comment by revolter** [comment]
I tried but it doesn't reproduce.

1. I found another issue. I have multiple, different iOS apps as multiple project targets, and after removing the `TwitterKit` pod, it was removed only from one `Pods-<TargetName>-frameworks-Debug-input-files.xcfilelist` file. Does this info help?
2. Is there any way I can debug it myself using my actual project that I can't share?

**Comment by revolter** [comment]
I think it's related to the fact that I enabled macOS support (UIKit for Mac / Project Catalyst) for the target that was the only one that had its `*-frameworks-*.xcfilelist` file modified.

**Comment by revolter** [comment]
There is another issue with the `libPods-<TargetName>.a` file references (there are 3 of them) that for some reason get completely removed from the `<ProjectName>.xcodeproj/project.pbxproj` file, and if I run `pod install` again, 2 of them get added back, but in different places in the file than before, and this gets added too:

```js
D141079CFF42B9D596DD50C0 /* BuildFile in Frameworks */ = {isa = PBXBuildFile; };
```

And if I change something in Xcode so it forces an update of the file, that line gets replaced with

```js
D141079CFF42B9D596DD50C0 /* (null) in Frameworks */ = {isa = PBXBuildFile; };
```

**Comment by revolter** [comment]
I also receive this warning:

> [!] `<PBXBuildFile UUID=`D141079CFF42B9D596DD50C0`>` attempted to initialize an object with an unknown UUID. `68ADE4FEEF2C7D20216638BA` for attribute: `file_ref`. This can be the result of a merge and  the unknown UUID is being discarded.

but before running `pod install` twice as in my last comment, I have:

```js
D141079CFF42B9D596DD50C0 /* libPods-<TargetName>.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 68ADE4FEEF2C7D20216638BA /* libPods-<TargetName>.a */; };

...

68ADE4FEEF2C7D20216638BA /* libPods-<TargetName>.a */ = {isa = PBXFileReference; explicitFileType = archive.ar; includeInIndex = 0; path = "libPods-<TargetName>.a"; sourceTree = BUILT_PRODUCTS_DIR; };
```

Though I also found

```js
B858C17E1E2CE8BA000D2911 /* libPods-<TargetName>.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 68ADE4FEEF2C7D20216638BA /* libPods-<TargetName>.a */; };
D141079CFF42B9D596DD50C0 /* libPods-<TargetName>.a in Frameworks */ = {isa = PBXBuildFile; fileRef = 68ADE4FEEF2C7D20216638BA /* libPods-<TargetName>.a */; };
```

in the `PBXBuildFile` section, and I think that there should be only one.

**Comment by revolter** [comment]
I found out when the duplicate entry was added (maybe it was another CocoaPods bug back in 2017, or probably was caused by duplicating an existing project target instead of creating it from scratch), I removed it, and it fixed the `(null) in Frameworks` and the warning. But the initial issue and the one with the `*.xcfilelist` one still remain.

**Comment by dnkoutso** [comment]
I continue to be unable to diagnose. CocoaPods does not add the input/output paths if the target has no frameworks/resources to embed or it does not require embedding because its host target will do the embedding.

Without a sample app this is like finding a needle in a haystack I am sorry.

**Comment by lufinkey** [comment]
Just experienced this too. Not sure what causes it, but throwing this out there that it's a real bug

**Comment by source-creator** [comment]
Ran into this issue  myself, leaving this for reference:

If you are using Flutter, then the Build Phase `[CP] Embed Pods Frameworks` would be removed if your plugin `pubspec.yaml` doesn't contain the iOS plugin settings:

```yaml
# Plugin pubspec.yaml
flutter:
  plugin:
    platforms:
      android:
        package: com.example
        pluginClass: ExamplePlugin
      ios:
        pluginClass: ExamplePlugin
      linux:
        pluginClass: ExamplePlugin
      macos:
        pluginClass: ExamplePlugin
```

Solution is to add it back.
Might need to run all the usual clean commands.
