### ISSUE TITLE
pod install,but the project does not refresh

### ISSUE THREAD

**Issue by LazyJiu** [CocoaPods/CocoaPods#9051]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Sometimes I add a dependency ,then pod install, but the project does not refresh,I can not see the pod, I need to re-open this project, to see the pod

## What did you expect to happen?
pod install  and refresh this project, to see the pod
![image](https://user-images.githubusercontent.com/18650229/62003753-3ec25780-b14e-11e9-80d5-51e13cb8d594.png)

## What happened instead?
pod install and this project does not refresh, I need to re-open,to see the pod
![image](https://user-images.githubusercontent.com/18650229/62003714-ccea0e00-b14d-11e9-8d7a-01bbdfe0671e.png)

## CocoaPods Environment
1.7.5

**Comment by dnkoutso** [comment]
We cannot diagnose this issue with the given information. please upload a sample.

**Comment by LazyJiu** [comment]
> We cannot diagnose this issue with the given information. please upload a sample.

After restarting the computer, all right.
