### ISSUE TITLE
Unknown file type under __MACOSX

### ISSUE THREAD

**Issue by Luten** [CocoaPods/CocoaPods#9054]
### What did you do?

Trying to validate podspec with:
`pod spec lint Threads.podspec --verbose`

### What happened?

Validation failed with error:
```
[!] Error installing Threads
 -> Threads (2.48.8)
    - ERROR | [iOS] unknown: Encountered an unknown error (unknown file type: /var/folders/b5/bd619y795g51wghl0xw01y480000gn/T/d20190730-3848-1uvx3tq/__MACOSX/Threads.framework
```

### What did you expect to happen?

Validation passed successfully

#### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.4
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.13.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ df8ab5ecacbb0da7aed06e6f483fc44b5fdb3000
```

#### Installation Source

```
Executable Path: /usr/local/bin/pod
```

#### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Project that demonstrates the issue
Podspec: [Threads.podspec.txt](https://github.com/CocoaPods/CocoaPods/files/3445352/Threads.podspec.txt)

### Related info
Might be related to #7282

**Comment by dnkoutso** [comment]
I cannot extract the .zip to reproduce.

<img width="490" alt="Screen Shot 2019-07-30 at 2 13 17 AM" src="https://user-images.githubusercontent.com/310370/62105189-a02e1780-b26f-11e9-8346-d1c694c1eccc.png">

Yes possibly related to #7282.

**Comment by Luten** [comment]
@dnkoutso 
I can extract it without issue, could you please redownload, or try to unzip it in terminal, or another tool.

Also, as I understand, you don't need to extract to reproduce, you need to run `pod spec lint` on podspec I've povided

**Comment by Luten** [comment]
@dnkoutso 
I've fixed the issue:
Replaced zip with one without `__MACOSX` folder in it - created in terminal by `zip` -r <archive_name> .`
Now Threads.podspec passes validation.

For debug purposes here is the old zip: [Threads.framework.zip](https://github.com/CocoaPods/CocoaPods/files/3445975/Threads.framework.zip)

**Comment by dnkoutso** [comment]
Thanks! I dont think there is currently much to do here.

**Comment by Luten** [comment]
I don't think the issue should be closed because workaround has been found.
Issue\bug is still there

**Comment by dnkoutso** [comment]
How can we detect and fix this up if its the zip that has a problem? We could skip the this directory but yes this doesnt happen very often and the workaround is fairly easy.

I can re-open but I think the issue will eventually be closed for inactivity. Want to try a PR?
