### ISSUE TITLE
Unable to import subspec module into swift project

### ISSUE THREAD

**Issue by VasilijSviridov** [CocoaPods/CocoaPods#9055]
My subspec look like this:  
s.name         = "Module"
s.subspec 'Base' do |sp|
    sp.dependency   "Core"
    sp.source_files = "Folder/*.swift"
  end

My podfile looks like this:
target 'NewTarget' do
  use_frameworks!
  pod 'Module/Base', :path=>'../SubSpecFolder'
 
All is good when I am using just Module, works fine and all is good but,
Now in swift when I try to import created module for subspec which looks like this : Module-Base , I am unable to do this, as I get "No such module" 
Any help on this ?

**Comment by dnkoutso** [comment]
Please ask StackOverflow under `cocoapods` tag. 

This report does not provide enough information or a sample app for us to diagnose.

I am going to preemptively close.

**Comment by VasilijSviridov** [comment]
well, thank you for nothing 
Cheers

**Comment by dnkoutso** [comment]
Sorry, but we simply cannot help with the report here. If you can upload a sample app and provide clear steps of the issue maybe someone can take a look. There is an issue template to use and we get too many issues filed that are tough to debug with the given info.
