### ISSUE TITLE
error: Value for SWIFT_VERSION cannot be empty - Regression from 1.7.5 to master

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#9060]
To reproduce:

```
git clone https://github.com/firebase/firebase-ios-sdk.git
cd firebase-ios-sdk/
git checkout pb-test-cp-180
cd Firestore/Example/
bundle exec pod install
xcodebuild -workspace Firestore.xcworkspace -scheme Firestore_IntegrationTests_iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7" ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=YES
```

Output of last command:
```
Build settings from command line:
    CODE_SIGNING_ALLOWED = YES
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = YES
    SDKROOT = iphonesimulator12.4

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Value for SWIFT_VERSION cannot be empty. (in target 'Firestore_IntegrationTests_iOS')

** BUILD FAILED **
```

The build starts successfully on the firebase-ios-sdk master branch that specifies the 1.7.5 bundles.

**Comment by dnkoutso** [comment]
Uncertain what the root cause is yet. I suspected (and still do) that this https://github.com/CocoaPods/CocoaPods/pull/9010 causes it but I can't prove it yet and I am uncertain if the PR actually fixed a real underlying issue and you need to specify the `SWIFT_VERSION` in your targets.

Will keep looking.

**Comment by dnkoutso** [comment]
I am completely stumped here. I could use some help to diagnose this. We still need to confirm if 1.8.x does something _right_ and the fact that the user target does not specify `SWIFT_VERSION` is a problem.

Somehow, something sets the `SWIFT_VERSION = '4.0'` in the xcconfig of these inherited targets but I cant trace it.

**Comment by segiddins** [comment]
Different Xcodeproj versions, maybe?

**Comment by paulb777** [comment]
Fixed by https://github.com/firebase/firebase-ios-sdk/pull/3481.
Verified in https://travis-ci.org/firebase/firebase-ios-sdk/builds/566245788

This was an issue with a Firebase post_install script running in some ruby environments.

**Comment by dnkoutso** [comment]
Excellent!
