### ISSUE TITLE
private pods lib, when install,clong whole project

### ISSUE THREAD

**Issue by GuangPengLiu** [CocoaPods/CocoaPods#9063]
## What did you do?

I builded a private pods lib,and add it to my private Spec Repo,i can run 'pod search mypodlib' successfully.But,when i use it in my own project, using 'pod install,it always do 'Cloning spec repo `guangpengliu` from `https://github.com/GuangPengLiu/TempLib.git`'
and add the 'guangpengliu' file in my ~/.cocoapods/repos/. 
## What did you expect to happen?

i want 'pod install' correct

## What happened instead?

using 'pod install,it always do 'Cloning spec repo `guangpengliu` from `https://github.com/GuangPengLiu/TempLib.git`'
and add the 'guangpengliu' file in my ~/.cocoapods/repos/.

## Project that demonstrates the issue
https://github.com/GuangPengLiu/TempStecs.git 
https://github.com/GuangPengLiu/TempLib.git

**Comment by dnkoutso** [comment]
I am unable to reproduce, can you try `pod repo remove guangpengliu` and try again?

**Comment by GuangPengLiu** [comment]
> I am unable to reproduce, can you try `pod repo remove guangpengliu` and try again?

when i remove the 'guangpengliu' and do 'pod install',it will clone guangpengliu again

**Comment by dnkoutso** [comment]
Something is wrong in your `Podfile` or setup that I can't tell from the sample app. It did not install this repo for me when I tried your project.
