### ISSUE TITLE
Multiple Target use cocoapods manage dependent lib.

### ISSUE THREAD

**Issue by CrystalBlack** [CocoaPods/CocoaPods#9064]
I expect the result:
`Main Target` dependent on `podA`.
`Main Target` link `subTargetA`. 
`subTargetA` dependent on `podB`, and inherit `Main Target`.

`Main Target` can use `podA` but not `podB`.
`subTargetA` can use `podA` and `podB`.

_Originally posted by @CrystalBlack in https://github.com/CocoaPods/CocoaPods/issues/9031#issuecomment-515454579_

**Comment by dnkoutso** [comment]
Kept https://github.com/CocoaPods/CocoaPods/issues/9031 open.
