### ISSUE TITLE
Resource bundles not adding targeted device family when included in an Apple Watch target

### ISSUE THREAD

**Issue by Spilly** [CocoaPods/CocoaPods#9075]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Added a pod containing a framework and resource bundle target for the Watch OS platform.

## What did you expect to happen?

I expected it to be added to my project without any errors or warnings

## What happened instead?

Xcode is displaying a warning that the Info.plist generated for the resource bundle by CocoaPods does not contain any device family values compatible with the watchOS platform. CocoaPods does properly generate the Info.plist file for the framework specified for this pod, but not the resource bundle plist. This is currently happening the DeviceGuru pod. 

ProcessInfoPlistFile /Users/xxx-watchos/DeviceGuru/DeviceGuru.bundle/Info.plist xxx/Pods/Target\ Support\ Files/DeviceGuru/ResourceBundle-DeviceGuru-DeviceGuru-Info.plist (in target: DeviceGuru-DeviceGuru)
    cd /xxx/Pods
    builtin-infoPlistUtility /xxx/Pods/Target\ Support\ Files/DeviceGuru/ResourceBundle-DeviceGuru-DeviceGuru-Info.plist -producttype com.apple.product-type.bundle -expandbuildsettings -format binary -platform watchos -o /xxx/Library/Developer/Xcode/DerivedData/esfpxpymkdrnvncrhykmgjnlqtan/Build/Products/Debug\ xxx-watchos/DeviceGuru/DeviceGuru.bundle/Info.plist

warning: TARGETED_DEVICE_FAMILY value (1,2) does not contain any device family values compatible with the watchOS platform. Please add the value '4' to the TARGETED_DEVICE_FAMILY build setting to indicate that this target supports the 'watch' device family.

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : xxx - git@xxx:xxx/Specs.git @ ca23ccbb4a0948c0765af441509efa16f8b1bc87
               xxx-specs - git@xxx:xxx/Specs.git @ ca23ccbb4a0948c0765af441509efa16f8b1bc87
               master - https://github.com/CocoaPods/Specs.git @ d6854346a369cf80a4556cd9208e43d985d14a6e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
slather               : 2.4.7
```

### Podfile

```ruby
source 'git@dexgithub01.xxx:xxx/Specs.git'

workspace 'XXX'
project 'Projects/XXX.xcodeproj', 'Debug OUS' => :debug, 'Release OUS' => :release, 'Debug OUS MMOL' => :debug, 'Release OUS MMOL' => :release
use_frameworks!

def test_pods
  pod 'OCMock', '3.4.2', :inhibit_warnings => true
  pod 'SimulatorStatusMagic', '2.2', :inhibit_warnings => true
end



abstract_target :app do
  platform :ios, '11.0'

...
  
  abstract_target :main_app do
...
    pod 'DeviceGuru', '5.1.4', :inhibit_warnings => true

    target 'XXX-Enterprise' do
      inherit! :complete

      # Enterprise-only pods
      pod 'SwiftLint', '0.33.0', :inhibit_warnings => true

      target 'ScreenCrawler' do
        inherit! :complete

        test_pods
      end

      target 'MarketingUITests' do
          inherit! :search_paths

          test_pods
      end

      target 'XXX-Server-Tests' do
          inherit! :search_paths

          test_pods
      end
    end

    target 'XXX-Store' do
      inherit! :complete
    end
  end


end

abstract_target :watch_app do
  platform :watchos, '4.3'
  
  abstract_target :watch_extension do
    pod 'DeviceGuru', '5.1.4', :inhibit_warnings => true
    
    target 'Watch Extension - Enterprise' do
      inherit! :complete
    end

    target 'Watch Extension - Store' do
      inherit! :complete
    end 
  end

  target 'Watch - Enterprise' do
    inherit! :complete
  end

  target 'Watch - Store' do
    inherit! :complete
  end
end

post_install do |installer|  
  installer.pods_project.targets.each do |target|  
    target.build_configurations.each do |config|  
      if config.build_settings['SDKROOT'] == 'watchos'  
        config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '4.3'
      end  
    end  
  end
end
```

**Comment by dnkoutso** [comment]
Probably something we can fix yes.

Start here: https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L533-L537

Code already had a comment for it but things may have changed here. Is it a watchOS extension or app?

**Comment by Spilly** [comment]
We are including this pod in the extension target.

**Comment by Spilly** [comment]
I could create a PR but I'm not sure if we should append the device family to support watch or replace with simply the watch device family. The 'right' solution to me would be to only have the watch device family, but maybe these resource bundles get copied from the phone to the watch and need to support all three?

**Comment by dnkoutso** [comment]
Havent investigated much myself but best rubrik is to immitate what Xcode 10.2 does. I.e do the same without CocoaPods in Xcode and see what it sets it to. Then we can change it here.

**Comment by Spilly** [comment]
I assume you mean 10.3 now? I'll try to take a look today or early next week.

**Comment by dnkoutso** [comment]
Yea thats fine 10.3, latest stable release, not Xcode 11 beta.

**Comment by Spilly** [comment]
This is what I see when I create a resource bundle, change the base sdk to watch os and compile with Xcode 10.3. It sets the UIDeviceFamily to 4, but if you look at the targeted device family in Xcode it does not automatically set that at all. For the framework that contains the device bundle, it's targeted device family is also only set to 4. So I believe that is the correct value for the resource bundle as well.  

<img width="912" alt="Screen Shot 2019-08-05 at 2 26 09 PM" src="https://user-images.githubusercontent.com/864813/62496182-009be800-b78d-11e9-9151-43f83c6ba2ca.png">

<img width="1512" alt="Screen Shot 2019-08-05 at 2 29 14 PM" src="https://user-images.githubusercontent.com/864813/62496319-71db9b00-b78d-11e9-9ccf-0effcb5dae44.png">

<img width="1512" alt="Screen Shot 2019-08-05 at 2 29 21 PM" src="https://user-images.githubusercontent.com/864813/62496328-7738e580-b78d-11e9-9b25-af05e77fb3dc.png">

**Comment by Spilly** [comment]
Ok, I've create a branch with the fix, but don't have push permissions. How do I submit a PR?

**Comment by dnkoutso** [comment]
Fork the repo and make a PR between the two repos
