### ISSUE TITLE
Broken Cocapods Specs Repository after trying to install pod library in remote server using SSH.

### ISSUE THREAD

**Issue by Layer3LLC** [CocoaPods/CocoaPods#9078]
I'm trying to install a pod library located in azure dev server using SSH.

I'm excepting to download the pod library, but the library couldn't be download, nevermind for auth issue or other reasons. after that it seems the master cocapods specs is broken, such that I couldn't download any pod library: such as "pod 'Alamofire'" even for other projects.
Please any help.

**Comment by dnkoutso** [comment]
Duplicate
