### ISSUE TITLE
Add support for Xcode 11 script build phase dependency files to podspec script_phases

### ISSUE THREAD

**Issue by jmagman** [CocoaPods/CocoaPods#9082]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Xcode 11 added support for dependency files as input to script build phases.
> Run script phases and custom build rules may declare and emit a dependencies file, in the Makefile-style .d format output used by some compilers and build tools. The build system checks the files listed for changes during subsequent builds when determining if the rule or phase should be executed. (49226986)

https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_5_release_notes?language=objc#3318304

See the new "Use discovered dependency file" field:
![dep_file](https://user-images.githubusercontent.com/682784/62490143-77c98000-b77d-11e9-8c29-dae69e70725f.png)

# Feature Request

It would be great if this could be added to a spec `script_phases`, similar to `:input_files`,  `:input_file_lists`, etc.
```
spec.script_phase = { :name => 'Hello World', :script => 'echo "Hello World"',
  :dependency_file => '/path/to/depfile.d'
}
```

**Comment by dnkoutso** [comment]
Yes! Should be fairly easy to add but adding as "Moderate" for folks who are new.

This needs https://github.com/CocoaPods/Xcodeproj change to read the new value for Xcode 11 and then a Core and CocoaPods gems change to parse and set the value.

**Comment by dnkoutso** [comment]
Here I did the Xcodeproj PR https://github.com/CocoaPods/Xcodeproj/pull/705 and was merged.

**Comment by dnkoutso** [comment]
Marking for 1.9 as 1.8.0.beta.1 has shipped and we do not do new enhancements.

**Comment by dnkoutso** [comment]
Will ship with 1.9 which will probably ship after Xcode 11 final ships in a month or two I would say.

**Comment by dreampiggy** [comment]
Can this dependency of `input_file` be used within Podfile DSL's `script_phase` ?

https://guides.cocoapods.org/syntax/podfile.html

Seems this PR only added the support in Podspec.

**Comment by iaaqibhussain** [comment]
Hi @dnkoutso ,
I am not sure if its the right place to ask you this but.
Can you tell me if I enable "For install builds only" from the script_phase? I tried googling a lot but couldn't really find any thing.
<img width="416" alt="Screenshot 2021-06-16 at 12 55 44" src="https://user-images.githubusercontent.com/9073795/122207458-73566e00-cea2-11eb-96ac-e85e67881237.png">
