### ISSUE TITLE
CDN is just not working

### ISSUE THREAD

**Issue by jeroenleenarts** [CocoaPods/CocoaPods#9085]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`bundle update`
`bundle exec pod outdated`

## What did you expect to happen?

A listing of outdated pods.

## What happened instead?

I can update my Gems no problem. But CocoaPods times out all over the place.

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.6 (18G87)
       Xcode : 10.3 (10G8)
         Git : git version 2.21.0
Ruby lib dir : /Users/jeroenleenarts/.rbenv/versions/2.5.1/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 86b39b12a2e1d3b278654b4d4b2dbea89d0861e0
```

### Installation Source

```
Executable Path: /Users/jeroenleenarts/.rbenv/versions/2.5.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '10.0'
workspace 'EvenAppen'
use_frameworks!
inhibit_all_warnings!
install! 'cocoapods', :generate_multiple_pod_projects => true

source 'https://cdn.cocoapods.org/'

def networking_pods
    pod 'AFNetworking'
end

def app_pods
    pod 'SwiftLint'
    pod 'Reachability'
    pod 'libPusher'
    pod 'XMLReader-Arc'
    pod 'UICKeyChainStore'

    pod 'SQLCipher'

    pod 'Firebase'
    pod 'FirebaseCore'
    pod 'FirebasePerformance'
    pod 'FirebaseDynamicLinks'
    pod 'FirebaseInstanceID'
    pod 'FirebaseAnalytics'
    pod 'Crashlytics'

    pod 'GoogleTagManager'

    pod 'Usabilla'

    pod 'ASN1Decoder', :git => 'https://github.com/filom/ASN1Decoder.git'

    pod 'PromiseKit'
    pod 'HPGrowingTextView'

    pod 'lottie-ios'
    pod 'Charts'
end

target 'EvenAppen' do
    project 'EvenAppen'
    use_frameworks!

    networking_pods
    app_pods

    target 'EvenAppenLogicTests' do
        inherit! :complete
    end

    post_install do | installer |
        require 'fileutils'
        FileUtils.cp_r('Pods/Target Support Files/Pods-EvenAppen/Pods-EvenAppen-Acknowledgements.plist', 'Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)

        installer.pods_project.targets.each do |target|
            if target.name != 'GoogleTagManager-TagManagerResources'
                target.build_configurations.each do |config|
                  config.build_settings['LD_NO_PIE'] = 'NO'

                    if config.base_configuration_reference != nil
                        xcconfig_path = config.base_configuration_reference.real_path

                        build_settings = Hash[*File.read(xcconfig_path).lines.map{|x| x.split(/\s*=\s*/, 2)}.flatten]
                        if build_settings['OTHER_LDFLAGS']
                            other_ldflags = build_settings['OTHER_LDFLAGS']

                            if other_ldflags.include? '-l"sqlite3"'
                                index = other_ldflags.index('-l"sqlite3"')
                                length = '-l"sqlite3"'.length
                                first_path = other_ldflags[0,index]
                                last_path = other_ldflags[index+length..-1]
                                exclude_ldflags = first_path + last_path

                                build_settings['OTHER_LDFLAGS'] = exclude_ldflags
                            end

                            # write build_settings dictionary to xcconfig
                            File.open(xcconfig_path, "w")
                            build_settings.each do |key,value|
                                File.open(xcconfig_path, "a") {|file| file.puts "#{key} = #{value}"}
                            end
                        end
                    end
                end
            end
        end
    end
end

target 'EvenAppenUITests' do
    project 'EvenAppen'
    use_frameworks!

    networking_pods
    
    pod 'Embassy', :git => 'https://github.com/envoy/Embassy.git'
end

target 'EvenAppenDomain' do
  project '../EvenAppenDomain/EvenAppenDomain'
  use_frameworks!
  
  pod 'Reachability'
end

target 'EvenAppenData' do
  project '../EvenAppenData/EvenAppenData'
  use_frameworks!

  pod 'libPusher'
end
```

**Comment by jeroenleenarts** [comment]
```Updating spec repo `cocoapods-`
[!] CDN: cocoapods- Repo update failed - 50 error(s):
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/3.0.1/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.2.3/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.2.4/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.0.0/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.6.2/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/3.0.0/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.0.0-RC3/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.4.1/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/1.0RC1/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/1.1.0/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/1.3.4/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/0.5.1/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/1.3.3/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.5.0/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/1.3.2/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.1.0/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.5.1/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/0.9.2/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/3.1.0/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/3.0.0-beta.1/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.0.0-RC1/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/3.2.1/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/3.0.2/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.6.0/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/2.0.2/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/7/5/AFNetworking/1.2.0/AFNetworking.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/a/f/1/PromiseKit/3.5.2/PromiseKit.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/d/c/1/FirebaseABTesting/3.0.0/FirebaseABTesting.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.20.1/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.34.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.30.1/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.15.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.30.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.23.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.29.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.29.1/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.23.1/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.27.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.18.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.33.1/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.16.1/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.33.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.18.1/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.16.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.22.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.28.1/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.26.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.19.0/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/0.29.3/SwiftLint.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)
CDN: cocoapods- Relative path couldn't be downloaded: Specs/3/6/0/Crashlytics/3.7.0/Crashlytics.podspec.json, error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443)```

**Comment by jeroenleenarts** [comment]
To me this looks like Github is throttling due to the crazy amount of network calls the new CDN approach is causing. Especially in corporate environments where multiple users share a single public IP...

**Comment by jeroenleenarts** [comment]
Any way to attach a user specific acces token might help.

**Comment by igor-makarov** [comment]
GitHub CDN isn't limited like their API access is. These aren't accepting API key.

**Comment by jeroenleenarts** [comment]
Then why would I be getting timeouts. I've tried on multiple networks... 🤔 😢

**Comment by dnkoutso** [comment]
It seems suspicious that you get 50 errors, one for each thread used for
CDN.

You can also use the ENV variable `MAX_CDN_NETWORK_THREADS` to adjust the
number of threads, even to 1.

I will be trying your Podfile later today and see how it works.

I am ultimately afraid there is not too much we can do here, the "fallback"
to use the `git` based source will always be available at least for 1.x
releases.

**Comment by dnkoutso** [comment]
Sorry it seems you cannot do 1 but you can do 5 which is the minimum number
of threads.

**Comment by jeroenleenarts** [comment]
I am running ZSH and not bash. But that shouldn't matter right? Trying with `export MAX_CDN_NETWORK_THREADS=5` seems to show I am running with 5 threads when I run with `--verbose`.

It's just taking a long while.

**Comment by jeroenleenarts** [comment]
```➜  EvenAppen git:(develop) bundle exec pod update --verbose
Update all pods
  Preparing

Updating local specs repositories
  CDN: cocoapods- Relative path: CocoaPods-version.yml exists! Returning local
  because checking is only perfomed in repo update

Updating spec repo `cocoapods-`
  CDN: cocoapods- Relative path: all_pods_versions_9_5_6.txt, has ETag?
  "a12eca4c46838740547ad7932acb81f7-ssl"
  CDN: cocoapods- Relative path: all_pods_versions_8_7_0.txt, has ETag?
  "4658e89ba500a1b6638988a6d404f9ca-ssl"
  CDN: cocoapods- Relative path: CocoaPods-version.yml, has ETag?
  "4afbc63d706a0681583f8aea5064086b-ssl"
  CDN: cocoapods- Relative path: all_pods_versions_a_7_5.txt, has ETag?
  "a06697d9751dc13d8efc63ddcc57684c-ssl"
  CDN: cocoapods- Relative path: all_pods_versions_6_e_5.txt, has ETag?
  "d3622ec73f0dc36476ca7d451b42fa04-ssl"
  CDN: cocoapods- Relative path: all_pods_versions_8_7_0.txt error: execution
  expired - retrying
  CDN: cocoapods- Relative path: all_pods_versions_6_e_5.txt error: execution
  expired - retrying
  CDN: cocoapods- Relative path: all_pods_versions_9_5_6.txt error: execution
  expired - retrying
  CDN: cocoapods- Relative path: CocoaPods-version.yml error: execution expired
  - retrying
  CDN: cocoapods- Relative path: all_pods_versions_a_7_5.txt error: execution
  expired - retrying```

**Comment by jeroenleenarts** [comment]
The above run is still running and it keeps on retrying. At least I now know it is trying something.

**Comment by dnkoutso** [comment]
I was able to fully install all the pods in your podfile with CDN. No retries, no network issues.

I am afraid the best advise i can give is to either diagnose the network issue or use the `git` repo.

**Comment by jeroenleenarts** [comment]
Alright. Closing this then. If I find any causes due to something cocoapods I'll re-open. 👍

**Comment by jerryzhoujw** [comment]
When I run:
> pod repo update --verbose

Got message
>  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update

and seems just stop there.

**Comment by jerryzhoujw** [comment]
The solution of above is [pod repo remove trunk and pod install.](https://github.com/CocoaPods/CocoaPods/issues/9343#issuecomment-553820956)

**Comment by Voldemarus** [comment]
It doesn't help...

```
Colombina:turi-annotate-od 1$ pod install
Analyzing dependencies
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_2_1_2.txt, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
Colombina:turi-annotate-od 1$ pod repo remove trunk
Removing spec repo `trunk`
Colombina:turi-annotate-od 1$ pod install
Analyzing dependencies
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
Colombina:turi-annotate-od 1$ pod update
Update all pods
Updating local specs repositories
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
Colombina:turi-annotate-od 1$ 
````
`

**Comment by igor-makarov** [comment]
@Voldemarus that's definitely a DNS or network error.

**Comment by Ontegor** [comment]
This cdn was blocked in my country. Using VPN helped me (VPN country - United States)

**Comment by isabsent** [comment]
> This cdn was blocked in my country. Using VPN helped me (VPN country - United States)

Seems I know this country because I am sitting in the same ass with the same error... Мрази путинские...

**Comment by mayconmesquita** [comment]
You can always fallback to the previous git based implementation by adding to your **Podfile**

source 'https://github.com/CocoaPods/Specs.git'

**Comment by iballan** [comment]
What finally solved it for me is those:
```
pod repo remove trunk 
pod update
```

**Comment by sera4am** [comment]
@iballan work for me.

**Comment by DeltaTough** [comment]
Hi everyone. Does anyone have an idea of why I get this error on pod update:

CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.9.0/Firebase.podspec.json Response: 302 <html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Moved Temporarily</h1></center>
<hr><center>Umbrella Cloud Security Gateway</center>
</body>
</html>

Thanks

**Comment by igor-makarov** [comment]
@DeltaTough according to the log, it looks like there's some sort of cloud security software running on your end or in your network that is redirecting your request.

**Comment by DeltaTough** [comment]
@igor-makarov Thank you for coming back to me. Will investigate any network blockers. First time to see that.

**Comment by kunjalsoni-simformsolutions** [comment]
> What finally solved it for me is those:
> 
> ```
> pod repo remove trunk 
> pod update
> ```

This worked for me. Thank you!

**Comment by mendaparadarshit** [comment]
> What finally solved it for me is those:
> 
> ```
> pod repo remove trunk 
> pod update
> ```

Works for me. Thanks!

**Comment by matijamatija** [comment]
> > This cdn was blocked in my country. Using VPN helped me (VPN country - United States)
> 
> Seems I know this country because I am sitting in the same ass with the same error... Мрази путинские...

Experienced the same in Croatia. When I switched to US VPN it worked.
(September 2020)

**Comment by comvenger-brandon** [comment]
Same issue in Germany.

**Comment by igor-makarov** [comment]
@comvenger-brandon could you run your command with the flag `--verbose` and post it here? It's been a while and I wanna make sure it's not a different root cause.

**Comment by comvenger-brandon** [comment]
@igor-makarov 

`Resolving dependencies of `Podfile`
  CDN: trunk Relative path: all_pods_versions_0_3_5.txt modified during this
  run! Returning local
  CDN: trunk Redirecting from
  https://cdn.cocoapods.org/Specs/0/3/5/Firebase/6.34.0/Firebase.podspec.json to
  https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.34.0/Firebase.podspec.json
  CDN: trunk URL couldn't be downloaded:
  https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.34.0/Firebase.podspec.json
  Response: Timeout was reached, retries: 4
  CDN: trunk URL couldn't be downloaded:
  https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.34.0/Firebase.podspec.json
  Response: Timeout was reached, retries: 3
  CDN: trunk URL couldn't be downloaded:
  https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.34.0/Firebase.podspec.json
  Response: Timeout was reached, retries: 2
  CDN: trunk URL couldn't be downloaded:
  https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.34.0/Firebase.podspec.json
  Response: Timeout was reached, retries: 1
[!] CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/3/5/Firebase/6.34.0/Firebase.podspec.json Response: Timeout was reached

/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.3/lib/cocoapods-core/cdn_source.rb:407:in `block in download_and_save_with_retries_async'
`

**Comment by igor-makarov** [comment]
@comvenger-brandon Looks like you're having network timeouts. I've checked with our uptime monitor and CDN provider, and there doesn't seem to be any outage. 

My best guess would be some local network connectivity problems.

**Comment by comvenger-brandon** [comment]
Opening the url in any browser works fine, but "pod install" keeps throwing these errors. 

pod repo remove trunk 
pod update

fixes it.

**Comment by catach** [comment]
so what's the status update on that issue? It's a pain to remove the trunk ALL THE TIME to make a simple update.

**Comment by NguyenPhatBG** [comment]
> > What finally solved it for me is those:
> > ```
> > pod repo remove trunk 
> > pod update
> > ```
> 
> This worked for me. Thank you!

It's also work for me 👯

**Comment by fabyeah** [comment]
> I am running ZSH and not bash. But that shouldn't matter right?

I've been stuck on this timeout problem for hours. I'm also using zsh. Finally tried `pod update` in bash instead (`exec bash`) and it worked. 🙏

**Comment by HindrikStegenga** [comment]
I just get 302 Found and then redirects. Nothing seems to help. :(

**Comment by TranLuongTuanAnh** [comment]
@HindrikStegenga Me too :(

**Comment by zaeem-khatib** [comment]
Stuck at this error:

  CDN: trunk Relative path:
  Specs/8/b/d/FirebaseCore/4.0.18/FirebaseCore.podspec.json exists! Returning
  local because checking is only perfomed in repo update


Tried everything mentioned above.

**Comment by StratRob** [comment]
Got the error 3 times in a row, simply disabling and re-enabling wi-fi worked for me 🤷‍♂️

**Comment by Medef** [comment]
I just switched from wifi to my iphone's hotspot. After that, `pod update` started as if nothing had happened

**Comment by viettrung030699** [comment]
> I just switched from wifi to my iphone's hotspot. After that, `pod update` started as if nothing had happened

thanks @medef00, it worked for me.
