### ISSUE TITLE
Can import a package of swiftpackage By using cocopods? 

### ISSUE THREAD

**Issue by zhouJinYing** [CocoaPods/CocoaPods#9089]
Can import a package of swiftpackage By using cocopods? If can, How to import it ?

**Comment by dnkoutso** [comment]
Sorry I cannot fully understand the question.

**Comment by zhouJinYing** [comment]
In this issues, Allow Podspec dependency on a SPM package， I want to confirm this function can be supported Now [？](https://github.com/CocoaPods/CocoaPods/issues/5903 )
https://github.com/CocoaPods/CocoaPods/issues/5903

**Comment by dnkoutso** [comment]
Ah its for SPM support. This is not supported currently and there are no plans to do so as far as I know.

**Comment by dnkoutso** [comment]
Sorry going to close for now!

**Comment by paulb777** [comment]
Given the more typical expected migration paths, adding podspec support to SPM would be more useful.
