### ISSUE TITLE
framework

### ISSUE THREAD

**Issue by sqmer** [CocoaPods/CocoaPods#9094]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
- I have a framework (.framework) "A" that depends on a pod "B"
- I want to put framework "A" in a project that also depends on pod "B"
- I end up with duplicate pod "B" (one as a pod and the other embedded in framework "A")

## What did you expect to happen?
I need to know if there is a way to create a framework (.framework) pod dependent without embedding the pod in it.

**Comment by dnkoutso** [comment]
Is `PodA` a prebuilt vendored framework? If it is then `PodB` is already linked to it then as you said linking `PodB` to the app will yield duplicate symbols.

**Comment by sqmer** [comment]
Hello @dnkoutso  `PodA` is a prebuilt vendored framework.
How can I solve the duplicate symbols?
i.e.: What if i linked the framework to `PodB` version 1.0 but the app to `PodB` version 2.0?

**Comment by dnkoutso** [comment]
That might work but if `PodA` is a prebuilt vendored framework then it has already linked the `PodB` so what you are trying to do is not going to work.

I suggest you read about exporting symbols from frameworks, start here maybe https://developer.apple.com/library/archive/documentation/Performance/Conceptual/CodeFootprint/Articles/ReducingExports.html

I do not think this is a CocoaPods library issue so far so I am going to close. I will re-open it if we find a bug or enhancement.

We can also continue discussion here.
