### ISSUE TITLE
How to conditionally define a Podspec property depending on static or dynamic usage

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/CocoaPods#9101]
I'm including a Swift source in my CocoaPods library for the first time. For me to get the project to compile, I need to import the generated Swift header into my Objective-C source. This takes two different forms, depending on whether the project is being built as a static library or a dynamic framework:

``` objc
#ifdef BUILT_AS_FRAMEWORK
    #import <UnzipKit/UnzipKit-Swift.h>
#else
    // Used when built as a static library
    #import "UnzipKit-Swift.h"
#endif
```

I'm defining `BUILT_AS_FRAMEWORK` in my Xcode project for development time, but when I lint the library as a dynamic framework, and because I haven't defined that flag in the Podspec, it attempts to resolve the second import, and can't find it.

Is there a way I can define the `BUILT_AS_FRAMEWORK` preprocessor macro, but only if the consuming Podfile specifies `use_frameworks`?

**Comment by abbeycode** [comment]
This would be especially pertinent if #9099 gets implemented. Is there currently a recommended solution for this, in libraries that mix Objective-C and Swift?

**Comment by dnkoutso** [comment]
I do not think there is a way to do this currently. How is that handled lets say from Xcode without CocoaPods?

**Comment by abbeycode** [comment]
In Xcode your target is only either a static library or a dynamic framework. Until I added Swift to my library, CocoaPods allowed it to be configured as either by a consumer, but now it looks like I'll need to pick one or the other and document it in the readme (or forego Swift).

**Comment by dnkoutso** [comment]
Yeah I know Xcode will be either or and CocoaPods allows consumers to choose how to package something (and soon with #9099 link something) but is there any other way to detect that? I guess thats what you are asking ;)

**Comment by dnkoutso** [comment]
I searched a bit and I do not think there is a way to do this, not easily at least.

**Comment by dnkoutso** [comment]
Can potentially make CocoaPods generate a user-defined build setting like `PODS_USE_FRAMEWORKS` that can be queried at runtime.

**Comment by dnkoutso** [comment]
I am a bit uncertain if I want to add this though as folks might start leaning on it and might end up being a bad idea for library developers to depend on this?

**Comment by dnkoutso** [comment]
I am curious also why would you need the conditional in the first place?

**Comment by abbeycode** [comment]
A some thoughts, responses, and questions:

1. I was looking at the Xcode build settings, and found that there's a `PACKAGE_TYPE` setting with either `com.apple.package-type.wrapper.framework` or `com.apple.package-type.static-library` values depending on whether the target is a framework or a static library. I don't think there's any way to use that in conditional compilation, since it's just an environment variable
1. Can Podspec-defined script phases run before the Compile Sources build phase? If so, I could use the variable above to conditionally generate a header file to define the `BUILT_AS_FRAMEWORK` flag mentioned in my code sample
1. I think as a fallback, I could pick a preferred method (either framework or static library) and then require a consumer who want to use it the other way to add a post-install hook in his Podfile to define a flag
1. Is it desirable for pods to support being used as frameworks or libraries interchangeably depending on the needs of the consumer? If not, we can probably forget any further discussion of addressing this case more formally in CocoaPods
1. If we did want to formally address in CocoaPods, it would need to expose a compile-time flag, not a runtime setting

**Comment by dnkoutso** [comment]
For 2. the answer is yes!

https://guides.cocoapods.org/syntax/podspec.html#script_phases

When I first wrote it I added support for :execution_position which you can set the script phase to run _before_ compilation.

**Comment by dnkoutso** [comment]
For 5. this is what I meant kind of. If CocoaPods exposed a `PODS_USE_FRAMEWORKS` then you could lean on that.
```objc
#ifdef PODS_USE_FRAMEWORKS
    #import <UnzipKit/UnzipKit-Swift.h>
#else
    // Used when built as a static library
    #import "UnzipKit-Swift.h"
#endif
```

etc.

**Comment by abbeycode** [comment]
Success!!!

## generate-swift-import-header.sh

This should be mostly reusable by other projects, adjusting the paths relative to the repo root.

```bash
#!/bin/sh

[[ "${PACKAGE_TYPE}" = "com.apple.package-type.wrapper.framework" ]] \
    && SWIFTIMPORT="<${PRODUCT_MODULE_NAME}/${PRODUCT_MODULE_NAME}-Swift.h>" \
    || SWIFTIMPORT="\"${PRODUCT_MODULE_NAME}-Swift.h\""

if [ -z "$PODS_TARGET_SRCROOT" ]; then
    PODS_TARGET_SRCROOT=${SOURCE_ROOT}
    echo "Building in Xcode instead of CocoaPods. Overriding PODS_TARGET_SRCROOT with SOURCE_ROOT"
fi

_Import_text="
#ifndef GeneratedSwiftImport_h
#define GeneratedSwiftImport_h

#import ${SWIFTIMPORT}

#endif /* GeneratedSwiftImport_h */
"
echo "$_Import_text" > ${PODS_TARGET_SRCROOT}/Source/GeneratedSwiftImport.h
```

## Podspec update

```ruby
s.script_phases = { :name => "Generate UnzipKit Swift Header",
                    :script => "\"${PODS_TARGET_SRCROOT}\"/Scripts/generate-swift-import-header.sh",
                    :execution_position => :before_compile }
```

## Library source
I replaced my conditional import with this:

```objc
#import "GeneratedSwiftImport.h"
```

I also ignored the `GeneratedSwiftImport.h ` file in Git, and it's all good. @dnkoutso thanks as always for the help!
