### ISSUE TITLE
PATH in xcode build scripts

### ISSUE THREAD

**Issue by dbquarrel** [CocoaPods/CocoaPods#9107]
## What did you do?

Tried do build with xcodebuild:

    xcodebuild -destination generic/platform=iOS -scheme 'Release Builder' -sdk iphoneos

## What did you expect to happen?

A build.

## What happened instead?

Silent failure with non-zero error code.

## CocoaPods Environment

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
workspace 'Oshi'
project 'Oshi/Oshi.xcodeproject'

use_frameworks!
platform :ios, '12.0'
target 'Oshi' do
  pod 'Charts', "3.3.0"
  pod 'AppCenter'
  pod 'AppCenter/Distribute'
  pod 'AppCenter/Crashes'
end
```

## Project that demonstrates the issue

I've already figured out the problem and in my case was local to the system. However it points out a larger problem. The install script is using various commands and it has the user's path set by default. In my case this causes the scripts to pick up all of my various personal scripts and project scripts which have been written over 20 years.

    binary_archs="$(lipo -info "$binary" | rev | cut -d ':' -f1 | awk '{$1=$1;print}' | rev)"

Is to begin with poorly written. There is no need to reverse the string, cut it, then AWK it then reverse it again. If you want just the last field of a line with colons in it like this you can do that in AWK very easily without calling out to multiple commands.

I think the line can be replaced with:

    binary_archs="$(lipo -info "$binary" | awk -F: ' { print $NF } ')"

However this is not the key issue. I had a script in my user paths called "rev" and since the use of "rev" in this line is taking the user's path, it's not calling the correct "rev". Since you cannot ever depend on the user's path, the first step in any of these shell scripts should be to reset the PATH environment variable to a clean state so you know exactly what programs you will be calling within the script.

Script in question is Pods-${APPNAME}-frameworks.sh

XCode by default does this so the build scripts work fine within the Xcode context but at the commandline will have various problems which will be difficult to diagnose as they depend on the variety of user path environment variables in the world (i.e. you won't be able to replicate them). 

So the solution is to explicitly set the path as mentioned.

Secondary suggestion is to not use long complex pipelines of commands whenever possible. If you're calling AWK and AWK can already do what you need there is no need to pipe a few other commands in there, it just slows down processing and introduces more potential issues as you have more dependencies. 

One more note about this script, it contains this line:

     for arch in "${binary_archs}"; do

And I am not a bourne shell pro but I am pretty sure that is wrong syntax for iterating an array correctly. It is going to take that variable and break it down into words. So it is working correctly but via side effect because the architectures are assumed to be individual words. The correct syntax I think is:

      for arch in "${binary_archs[@]}"; do

Probably a good idea to change it because the more your programming depends on side effects the less robust the overall project is. So it is a principle thing. Iterate all arrays using array syntax and you will not get into weird problems. Equivalent in C would be trying to iterate over a string "fast" by treating it like a series of integers. It "works" if strings are aligned on integer boundaries but it is neither correct nor something you should do. 

Again I'm no bourne shell pro or anything so I could be wrong.

The path thing though is a major issue because you will never know what is in the user's path.

    export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"

At the top of your scripts.

Now, my system is not supposed to have user scripts coming ahead of system scripts so that is my issue with how I configured my path and reasons for that go back 20 years. But the point is that one line of code means that you don't have to make assumptions about what the user has done and makes your scripts bulletproof. Which is the end goal of all programming.

**Comment by amorde** [comment]
Is the issue there that Xcode already resets `PATH` when building within the Xcode UI, but when running `xcodebuild` it does not do this?

One issue I see with the proposed solution is that Xcode prepends several toolchain paths to `PATH` when building inside Xcode

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/usr/local/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/local/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/local/bin
```

though I guess if this were an issue then command line builds would already be having problems
