### ISSUE TITLE
Google Utilities multiple files not found error during build Xcode

### ISSUE THREAD

**Issue by TomaszWozniakMosina** [CocoaPods/CocoaPods#9113]
* [*] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run build in Xcode 10.2 and Xcode 10.3 for mobile game (Android and iOS) made in Unity 5.4, but currently build under Unity 2019.

## What did you expect to happen?

Succesful build

## What happened instead?

Errors occurred during build:
'GoogleUtilities/*.h' file not found (where * = different files i.e: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3241aa150bf61fb48ddeb21e1941000277e43160
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Project unavailable online. It's application made in Unity 5.4, needed to build under 2019.

**Comment by dnkoutso** [comment]
Without a sample app this is not easy to diagnose. Sorry there isn't too much information here.

The only thing I'd suggest is update CocoaPods as it seems you are using CocoaPods 1.5.0.

**Comment by TomaszWozniakMosina** [comment]
Sorry, cannot show sample app.
Error occurs in the connection to lines in files in GoogleUtilities that looks like:
#import <GoogleUtilities/GULReachabilityChecker.h>

After updating Cocoapods error still occurs.

**Comment by dnkoutso** [comment]
As I mentioned, we cannot debug this without one.

I recommend asking on StackOverflow or the google utilities repo

**Comment by paulb777** [comment]
The `Podfile.lock` file might provide some clues about what is going on. One possibility is a combination of `Podfile` specifications forcing an ancient version to be installed.
