### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults"

### ISSUE THREAD

**Issue by rzy77** [CocoaPods/CocoaPods#9114]
# Report

## What did you do?
MacBook-Pro$ ionic cordova platform add ios
....
Installing "cordova-plugin-googleplus" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-googleplus': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/razvan/RZY/zapps/fotbalist/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
pod: Command failed with exit code 1

MacBook-Pro$ cd platforms/ios/

MacBook-Pro$ pod setup
Setting up CocoaPods master repo
...
Setup completed
MacBook-Pro$ pod install
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
  In snapshot (Podfile.lock):
    GoogleUtilities/UserDefaults (= 6.2.5, ~> 6.0, ~> 6.2)

  In Podfile:
    GoogleUtilities (= 6.2.3) was resolved to 6.2.3, which depends on
      GoogleUtilities/UserDefaults (= 6.2.3)

Specs satisfying the `GoogleUtilities/UserDefaults (= 6.2.5, ~> 6.0, ~> 6.2), GoogleUtilities/UserDefaults (= 6.2.3)` dependency were found, but they required a higher minimum deployment target.

## What did you expect to happen?

- install the ios platform correctly
- install all pod dependencies correctly

## What happened instead?

- ios platform does not install correctly
- CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults"

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G87)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 83e6e394e9128aa33cdb7ed1910a10032ddff32a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
The error message clearly states:
```
Specs satisfying the GoogleUtilities/UserDefaults (= 6.2.5, ~> 6.0, ~> 6.2), GoogleUtilities/UserDefaults (= 6.2.3) dependency were found, but they required a higher minimum deployment target.
```

Please update your deployment target.

I do not see a CocoaPods issue here so I am going to preemptively close. Please also ask StackOverflow under `cocoapods` tag.

I will re-open this if we find an actual bug and please upload a sample app with it.

**Comment by mmdock** [comment]
@dnkoutso i have a similar issue:

Specs satisfying the `SnapKit (~> 5.0.1)` dependency were found, but they required a higher minimum deployment target.

Their deployment target is iOS 10: https://github.com/SnapKit/SnapKit/blob/develop/SnapKit.podspec#L11

My deployment target is iOS 10.0:
<img width="329" alt="Screen Shot 2019-08-22 at 12 02 23 PM" src="https://user-images.githubusercontent.com/2423465/63542211-bc228300-c4d4-11e9-85a2-4b8e7e9116a7.png">

Could you explain what I am doing wrong or where else I need to change this?

**Comment by dnkoutso** [comment]
I'll need a sample app here to be able to diagnose. Check the DEPLOYMENT_TARGET build setting in the your target that integrates the SnapKit pod.

**Comment by mmdock** [comment]
@dnkoutso 

This what you need? 

<img width="980" alt="Screen Shot 2019-08-22 at 12 27 02 PM" src="https://user-images.githubusercontent.com/2423465/63543699-3f91a380-c4d8-11e9-9f60-9e984fbe8eba.png">

**Comment by dnkoutso** [comment]
maybe, I do not know all targets that your pod is integrated to, do you have mac or watchos targets? I could potentially improve the error message to include that information.

I need a demo project that clearly reproduces the issue.

**Comment by paulb777** [comment]
Or maybe the Podfile specifies a version less than 10?

**Comment by dnkoutso** [comment]
oh thats also a good point

**Comment by mmdock** [comment]
@dnkoutso @paulb777 🤦‍♂ I forgot a long while back I added a specific version into the Podfile.  Surprised I didn't encounter this sooner.  

Works fine now 👍
