### ISSUE TITLE
Pure objc project use swift pod without add swift file?

### ISSUE THREAD

**Issue by helele90** [CocoaPods/CocoaPods#9115]
My pod has some swift files.
My Objc main project uses pod to not import files directly, using the url router method.

If the main project does not add a swift file, it will prompt an error.

ld: warning: Could not find auto-linked library 'swiftObjectiveC'
ld: warning: Could not find auto-linked library 'swiftUIKit'
ld: warning: Could not find auto-linked library 'swiftDarwin'
ld: warning: Could not find auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find auto-linked library 'swiftCore'
ld: warning: Could not find auto-linked library 'swiftQuartzCore'
ld: warning: Could not find auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find auto-linked library 'swiftsimd'
ld: warning: Could not find auto-linked library 'swiftFoundation'
ld: warning: Could not find auto-linked library 'swiftMetal'
ld: warning: Could not find auto-linked library 'swiftDispatch'
ld: warning: Could not find auto-linked library 'swiftAVFoundation'
ld: warning: Could not find auto-linked library 'swiftCoreMedia'
ld: warning: Could not find auto-linked library 'swiftSwiftOnoneSupport'
ld: warning: Could not find auto-linked library 'swiftCoreImage'
ld: warning: Could not find auto-linked library 'swiftCoreAudio'

Is there any way to not add a swift file? such as pod_target_xcconfig?
because every other pure objc project use this pod must add a empty swift file.

**Comment by dnkoutso** [comment]
You need to link Swift since your pod has swift filea. Maybe set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES in pod target xcconfig.

Closing as it does not appear to be an ussue with CocoaPods library.
