### ISSUE TITLE
pod repo push ignores SSH url provided in sources flag

### ISSUE THREAD

**Issue by arielelkin** [CocoaPods/CocoaPods#9123]
Cocoapods v1.7.2

I am developing a private pod hosted in a private repo, here's the relevant part of its podspec:

```
  s.source           = {
    :git => 'https://domain.com/my-framework.git',
    :tag => s.version
  }
```

(The git url is HTTP instead of SSH in order to avoid lint warning "Git SSH URLs will NOT work for ..." but the pod's SSH url is specified in the Podfile)

Now if I call `pod repo push` the validation is carried out by cloning using the HTTP URL , _even if_ I specify an SSH url in `--sources` : 

```
$ pod repo push my-specs my-framework.podspec --verbose --sources='git@domain.com:me/my-framework.git'

Validating spec
    My_Framework (0.1.0) - Analyzing on iOS 10.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `My_Framework` from `/Users/me/My_Framework/My_Framework.podspec`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A My_Framework

Downloading dependencies

-> Installing My_Framework (0.1.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://domain.com/my-framework.git /var/folders/13/jh62fb214m394xbztdjkl2vm0000gn/T/d20190822-11218-13xkcme --template=
     --single-branch --depth 1 --branch 0.1.0
     Cloning into '/var/folders/13/jh62fb214m394xbztdjkl2vm0000gn/T/d20190822-11218-13xkcme'...
Username for 'https://github.com': 
```

**Comment by dnkoutso** [comment]
> Now if I call pod repo push the validation is carried out by cloning using the HTTP URL , even if I specify an SSH url in --sources :

The `--sources` you specify is not the source of where the pod will be downloaded from. Its additional sources for finding dependencies of your pod.

When you `pod repo push` CocoaPods will have to clone your pod from the `s.source` you specified to ensure it can be cloned and can be compiled.

I do not see immediately a bug into the CocoaPods library issue here so I am going to close this but I *will* re-open if we find a bug (with clear steps on how to repro) or enhancement to do.

We can also continue the discussion here.

**Comment by arielelkin** [comment]
ah, I understand. I thought it was a bug. 

For anyone landing on this in the future, if you specify an SSH url in your private podspec _and_ then lint it using `pod lib lint --private`, there won't be a "Git SSH URLs will NOT work for ..." warning. 

Thanks @dnkoutso
