### ISSUE TITLE
Installation error POD

### ISSUE THREAD

**Issue by dvorCE** [CocoaPods/CocoaPods#9124]
![Captura de pantalla 2019-08-22 a la(s) 03 00 09](https://user-images.githubusercontent.com/54412263/63534997-cc435e00-c4e6-11e9-8d01-e87d5033c433.png)

Hi, I tried to solve this error 5 days ago and I can't fix it. Try many ways and methods and I still can't solve it. I would like to know if there is any alternative way to install. Thank you.

**Comment by dnkoutso** [comment]
This seems like a network error issue trying to clone the git repo. 

An alternative is to use 1.8.0.beta.1 and CDN, read here http://blog.cocoapods.org/CocoaPods-1.8.0-beta/

Sorry I am going to close as there is not much we can do here.
