### ISSUE TITLE
Wrong sources when cancel pod install

### ISSUE THREAD

**Issue by SolaWing** [CocoaPods/CocoaPods#9128]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
checkout a old commit, and run `pod install`, then interrupt after download some source, then checkout back and run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

previous download source overwrite Pods Content, and the last pod install not restore it. cause the wrong dependencies sources. 

## CocoaPods Environment
cocoapod 1.7.5

**Comment by dnkoutso** [comment]
Yes I think I've seen a report previously about this. Does the pod you install come from `git` or `http` based source?

**Comment by dnkoutso** [comment]
a sample app would also be helpful here, are you saying that between the two commits the version of the pod has changed in the `Podfile.lock` or is it the same and installed sources are corrupted? If its the former then this seems a resolver issue although I ultimately believe the issue is in `pod cache` itself.

**Comment by SolaWing** [comment]
here I create a demo:
[Podbug.zip](https://github.com/CocoaPods/CocoaPods/files/3541388/Podbug.zip)


first, in master branch and run `pod install`
```
0:Podbug $ pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (3.2.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```
the file of 3.2.1 is exist:
```
0:Podbug $ file Pods/AFNetworking/AFNetworking/AFCompatibilityMacros.h
Pods/AFNetworking/AFNetworking/AFCompatibilityMacros.h: UTF-8 Unicode text
```
then checkout other branch, run pod install to install other version, but interrupt before finish.
```
0:Podbug $ git checkout other
Switched to branch 'other'
0:Podbug $ pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking 3.0.4 (was 3.2.1)
[!] An error occurred while processing the pre-install hook of the Podfile.

simulate cancel

/private/tmp/Podbug/Podfile:13:in `block (2 levels) in from_ruby'
```
this version not have the file:
```
0:Podbug $ file Pods/AFNetworking/AFNetworking/AFCompatibilityMacros.h
Pods/AFNetworking/AFNetworking/AFCompatibilityMacros.h: cannot open `Pods/AFNetworking/AFNetworking/AFCompatibilityMacros.h' (No such file or directory)
```
checkout back to master, and run install
```
0:Podbug $ git checkout master
Switched to branch 'master'
0:Podbug $ pod install
Analyzing dependencies
Downloading dependencies
Using AFNetworking (3.2.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```
the file still not exist and Pods/AFNetwork is not change. (expect the contents is 3.2.1's contents)
```
0:Podbug $ file Pods/AFNetworking/AFNetworking/AFCompatibilityMacros.h
Pods/AFNetworking/AFNetworking/AFCompatibilityMacros.h: cannot open `Pods/AFNetworking/AFNetworking/AFCompatibilityMacros.h' (No such file or directory)
```

**Comment by dnkoutso** [comment]
Thanks! Most likely a bug yes. Probably due to the fact `pre_install` fails and the cache is warmed up but the actual files do not get copied to `Pods/` until after. Could use some help here anyway. Start with installer.rb.
