### ISSUE TITLE
CFBundleIdentifier collision (watchOS)

### ISSUE THREAD

**Issue by andreyoshev** [CocoaPods/CocoaPods#9135]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install, pod update

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

ITMS-90806: CFBundleIdentifier collision - Each bundle must have a unique bundle identifier. The bundle identifier 'org.cocoapods.UICKeyChainStore' is used in the bundles '[UICKeyChainStore.framework, UICKeyChainStore.framework]'

ITMS-90806: CFBundleIdentifier collision - Each bundle must have a unique bundle identifier. The bundle identifier 'org.cocoapods.FastEasyMapping' is used in the bundles '[FastEasyMapping.framework, FastEasyMapping.framework]'

ITMS-90806: CFBundleIdentifier collision - Each bundle must have a unique bundle identifier. The bundle identifier 'org.cocoapods.Realm' is used in the bundles '[Realm.framework, Realm.framework]'

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G87)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : audiokit - https://github.com/AudioKit/Specs.git @ 5550f600a0d8e30661995178d28a0b37ad0624bd
               master - https://github.com/CocoaPods/Specs.git @ fdbb8984b65ae76b17760d5b2d6134ed013490e3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
inhibit_all_warnings!
use_frameworks!

def di
    pod 'Typhoon'
end

def data
    pod 'UICKeyChainStore', '~> 2.1'
    pod 'FastEasyMapping', '~> 1.2'
    pod 'Realm'
end

def network
    pod 'AFNetworking', '~> 3.1'
    pod 'SDWebImage', '~> 4.0'
end

def other
    pod 'Fabric'
    pod 'Crashlytics', '~>  3.9'
    pod 'Amplitude-iOS', '~> 4.0.1'
    pod 'YandexMobileMetrica/Dynamic'
    pod 'IAPHelper'
    pod 'APLViperStack', '~> 0.1.2'
    pod 'OneSignal', '>= 2.5.2', '< 3.0'
end

def ui
    pod 'Masonry'
    pod 'lottie-ios', '~> 2.5'
    pod 'Bluuur'
    pod 'JVFloatLabeledTextField'
    pod 'Shimmer'
    pod 'SVProgressHUD'
end

def social
    pod 'VK-ios-sdk'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'Branch'
end

target 'Watch Extension' do
    platform :watchos, '2.0'
    data
end

target 'OneSignalNotificationServiceExtension' do
    platform :ios, '10.0'
    pod 'OneSignal', '>= 2.5.2', '< 3.0'
end

target 'Learnwords' do
    platform :ios, '10.0'
    di
    network
    data
    ui
    other
    social
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '4.0'
        end
    end
end
```

**Comment by wilmarvh** [comment]
I've been getting these all day. It's definitely related to changes in App Store Connect in the last 24 hours. I resubmitted a previous build which processed successfully and it's now failing to process, and gets flagged as "invalid binary".

**Comment by andreyoshev** [comment]
> I've been getting these all day. It's definitely related to changes in App Store Connect in the last 24 hours. I resubmitted a previous build which processed successfully and it's now failing to process, and gets flagged as "invalid binary".

Same. Previous build was processed successfully :)

**Comment by Landsi** [comment]
We are experiencing the same issue. As far as I can tell, Apple has updated their validation of framework bundle identifiers, so not frameworks linked with multiple platforms (iOS, watchOS, tvOS ... ) need a unique identifier.

we're currently testing that theory with our app. what we did was change one line in all our  `.xcconfig` files of all pods from
`PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}`
to
`PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}.${PLATFORM_NAME}`

**Comment by dnkoutso** [comment]
So this is only for watchOS apps that share the same dynamic frameworks as the main app?

**Comment by andreyoshev** [comment]
> So this is only for watchOS apps that share the same dynamic frameworks as the main app?

Yes

**Comment by dnkoutso** [comment]
How does Xcode handle the bundle identifier for a framework shared between watchOS and an app without CocoaPods?

**Comment by andreyoshev** [comment]
> How does Xcode 10.3 handle the bundle identifier for a framework shared between watchOS and an app without CocoaPods?
> 
> Does it use a unique bundle identifier name and "it happens" to work? If so we can make this change to CocoaPods as well.

Don't know :) 
But this worked: 
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}.${PLATFORM_NAME}.

<img width="398" alt="Screenshot 2019-08-29 at 21 10 13" src="https://user-images.githubusercontent.com/17673010/63957219-6be18d00-caa1-11e9-9e0c-1d2780e053e3.png">
<img width="396" alt="Screenshot 2019-08-29 at 21 10 17" src="https://user-images.githubusercontent.com/17673010/63957220-6c7a2380-caa1-11e9-83de-21f4fccc1b96.png">

**Comment by dnkoutso** [comment]
I'd love for someone to confirm what happens in Xcode 10.3 without CocoaPods in terms of having a shared dynamic framework. We try to imitate as close to possible what Xcode would do.

Seems like there is a plausible workaround here present for folks until we get a real fix.

**Comment by Landsi** [comment]
sorry, @dnkoutso - we have a cocoapods setup in all our apps and i needed to make a hotfix version for us.

maybe i'll find the time to try it out tomorrow.
the workaround works for us, though:
https://github.com/Landsi/CocoaPods/tree/1-6-runtastic

**Comment by adellibovi** [comment]
Hi,
Since more people may probably reach this issue while a solution (and its release) is on progress.
I wanted to share the small snippet that does the workaround based on what has been previously mentioned here :)
Ideally it may be easier for other people to apply the fix just by temporary changing the podfile (hopefully more then changing Cocoapods source or pointing to a temporary fork).

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}.${PLATFORM_NAME}"
        end
    end
end
```

**Comment by wilmarvh** [comment]
> Hi,
> Since more people may probably reach this issue while a solution (and its release) is on progress.
> I wanted to share the small snippet that does the workaround based on what has been previously mentioned here :)
> Ideally it may be easier for other people to apply the fix just by temporary changing the podfile (hopefully more then changing Cocoapods source or pointing to a temporary fork).
> 
> ```ruby
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>             config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "org.cocoapods.${PRODUCT_NAME:rfc1034identifier}.${PLATFORM_NAME}"
>         end
>     end
> end
> ```

Not having success with this @adellibovi, even when all the bundle identifiers are updated in the ipa.

**Comment by mattreesEE** [comment]
Feeling the same pain.

Quick dirty fix is to go back to static libraries removing use_frameworks!

**Comment by dnkoutso** [comment]
The Apple forums issue https://forums.developer.apple.com/thread/122048.

**Comment by MrJre** [comment]
Is there any documentation on these AppStoreConnect related changes?

**Comment by parrots** [comment]
A version of the script for those of us using `generate_multiple_pod_projects` :

```
post_install do |installer|
    installer.pod_target_subprojects.each do |subproject|
        subproject.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "org.cocoapods.${PRODUCT_NAME:rfc1034identifier}.${PLATFORM_NAME}"
            end
        end
    end
end
```

**Comment by ijaureguialzo** [comment]
@parrots, you should filter the pods to only include those who are duplicated/shared with the watch (I included just the ones apple rejected) as some pods don't behave correctly otherwise. 

I've been experiencing issues with Firebase on this (it compiled but crashed on start) and the problem was that the script had renamed its bundle.

Hope it helps.

**Comment by parrots** [comment]
@ijaureguialzo Interesting, I have Firebase (Crashlytics, remote config and a few more) installed with this script and submitted to iTC and installed, and I haven't ran into any issues. Wonder if there was something else going on?

**Comment by ijaureguialzo** [comment]
My problem was with Firestore, it gave an SSL error and won't start.

**Comment by danielleahyinsight** [comment]
I am having the same problem, using SwiftyBeaver pod in ios and watchos, changed 
xcconfig in the pod to

PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}.${PLATFORM_NAME}

Getting error
Invalid Code signature identifier. The identifier "org.cocoapods.SwiftyBeaver.iphoneos" in your code signature for "SwiftyBeaver" must match its bundle identifier "org.cocoapods.SwiftyBeaver"

What is the workaround, apart from removing SwiftyBeaver from one of the targets?

**Comment by nerocristallo** [comment]
try something like

```
post_install do |installer|
 installer.pods_project.targets.each do |target|
  if target.name == 'SwiftyBeaver-watchOS'
   target.build_configurations.each do |config|       
    config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'org.cocoapods.${PRODUCT_NAME:rfc1034identifier}-$(PLATFORM_NAME)'
   end
  end
 end
end
```

see discussion on stackoverflow
[https://stackoverflow.com/questions/57723390/ios-watchos-app-publishing-issue-cfbundleidentifier-collision](stackoverflow)

**Comment by ijaureguialzo** [comment]
I have solved this way, just add the conflicting pods to the list:

```ruby
post_install do |installer|
    watchosPods = ['Localize-Swift-watchOS', 'XCGLogger-watchOS', 'ObjcExceptionBridging-watchOS']

    installer.pods_project.targets.each do |target|
      if watchosPods.include? target.name
        target.build_configurations.each do |config|
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "org.cocoapods.${PRODUCT_NAME:rfc1034identifier}.${PLATFORM_NAME}"
        end
      end
    end
end
```

**Comment by danielleahyinsight** [comment]
I have tried variations of what you suggested in the post install script, you get the same invalid code signature error with SwiftBeaver. I will try again but i can predict with near certainty that you get the same error,  do you anything special in your workflow after you change the podfile post_install script

like 
clean build
pod deintegrate
pod install
rebuild
create archive
validate archive
??

**Comment by ijaureguialzo** [comment]
You should do a `pod install` to update project configuration.

**Comment by nerocristallo** [comment]
Can you confirm that now your error is related to org.cocoapods.SwiftyBeaver.**whatchos** but no more to org.cocoapods.SwiftyBeaver.**iphoneos**?

**Comment by danielleahyinsight** [comment]
I just tried the post_install script change method (just for the SwiftyBeaver-watchOS target) and it successfully validated, trying to upload to app store now?

**Comment by dnkoutso** [comment]
We can change CocoaPods here for sure, but again I'd love for someone to confirm that the same happens in normal Xcode. I'd assume it would but I am curious if you use the same framework target across an app and a watch extension does somehow Xcode change the bundle identifier?

**Comment by danielleahyinsight** [comment]
Thank you @ijaureguialzo , your solution worked for my problem, my app uploaded successfully to the app store.
If you use the same pods across multiple targets, SwiftyBeaver in my case in ios app and watchos you will get the same bundle identifier in your compiled targets, app will run in development mode, validate locally but will then not upload to the app store due to the duplicate identifier in the 2 pods, you willl get `ITMS-90806: CFBundleIdentifier collision - Each bundle must have a unique bundle identifier. The bundle identifier 'org.cocoapods.SwiftyBeaver' is used in the bundles '[SwiftyBeaver.framework, SwiftyBeaver.framework]'`
Changing the bundleidentifier manually didn't work for me, i tried variations of changing the post_install script and that didn't work. Finally i tried @ijaureguialzo solution which did.

I do think Cocoapods should be able to resolve this issue by default.

Say by appending the platform name into the product bundle identifier for each pod that is used across multiple platforms.

Thank you again for your help in resolving this issue.

**Comment by dnkoutso** [comment]
Still need someone to confirm this for non-cocoapods perspective.

**Comment by dnkoutso** [comment]
Any updates from anyone here? It seems people requests or +1s have dropped here significantly did Apple fix the issue?
