### ISSUE TITLE
How do I build the library generated by pod lib create? 

### ISSUE THREAD

**Issue by AdamCrabtreeMSFT** [CocoaPods/CocoaPods#9136]
I am using the latest cocoapod release. 

I'm not sure what to expect however when I create a pod library using the command:

pod lib create MyLibrary

this should create a library that I can compile correct? But it's not. It has no schemes. I'm not sure how to give it schemes. This is the tutorial I followed.

https://guides.cocoapods.org/making/using-pod-lib-create.html

There is no example application and no testing framework. All I want to do is compile the library into a pod that can be distributed.

**Comment by dnkoutso** [comment]
You need to have a project to integrate the podspec that was generated by it. 

There _is_ a quick way with cocoapods-generate plugin https://github.com/square/cocoapods-generate that takes any podspec and creates a project around it for you to develop on it.

For now I am going to close this as it does not appear to be an issue in the library or an enhancement. We can continue the discussion here and I will re-open if we need to.

**Comment by dnkoutso** [comment]
also a project is created for you so run `pod install` as the guide says and open the `.xcworkspace.`

**Comment by AdamCrabtreeMSFT** [comment]
I'm very confused...So I opened the .xcworkspace and I created a scheme for my library. However I'm not sure how to actually build it. It says my scheme has no build configuration.

**Comment by AdamCrabtreeMSFT** [comment]
Okay wait I read your first comment like 20 more times until I understood.


So in Android I can create a library and just...build that library. I do not need to include it inside of another project in order to build.

Are we saying this is not the case for xCode and that I need to include this library in another project?

**Comment by dnkoutso** [comment]
You need an `.xcodeproj` to build it or you can build it via the command line and using `xcodebuild`.

You probably need to read some tutorials on Xcode and how to build your own library like [this](https://www.raywenderlich.com/2658-creating-a-static-library-in-ios-tutorial) one.

**Comment by AdamCrabtreeMSFT** [comment]
But I have an xcodeproject? That's what pod lib create did?

**Comment by dnkoutso** [comment]
Yes. Open it and build the library there. Please read tutorials on Xcode development.
