### ISSUE TITLE
error: Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by Denmal1982** [CocoaPods/CocoaPods#9139]
I get an error after running the command
`pod install --repo-update`

`[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/deprecated_podspecs.txt, error: Connection reset by peer - SSL_connect`

Xcode 10.3 
version 1.8.0.beta.2

**Comment by dnkoutso** [comment]
Looks like a network issue on your part. I am sorry but this does not appear to be an issue with CocoaPods. You can also fallback to use `git`.

**Comment by moskvin-apiqa** [comment]
I have the same trouble after updating to 1.8

**Comment by Kamikozz** [comment]
Got the same trouble:
![image](https://user-images.githubusercontent.com/33129671/68004469-b38fbb00-fc82-11e9-8a74-5d3a30b8fe31.png)

Did the same as mentioned [here](https://facebook.github.io/react-native/docs/getting-started) for iOS & macOS

**Comment by moskvin-apiqa** [comment]
I found the reason of the problem for developers from Russia — it seems that something used in CocoaPods is blocked now by Roskomnadzor. I add to the ”/private/etc/hosts“ the line “142.93.108.123 cdn.cocoapods.org“, and it resolves the problem.
