### ISSUE TITLE
pod install does not respect decreasing Xcode compatibility version

### ISSUE THREAD

**Issue by Speakus** [CocoaPods/CocoaPods#9140]
## What did you do?

1. open project: https://github.com/Speakus/CocoapodIssueChangeCompatibilityVersion
2. bundle install
3. bundle exec pod install
I already changed compatibility version to 8.0 but cocoapod system ignore this change.
the commit since changing compatibility version here:
https://github.com/Speakus/CocoapodIssueChangeCompatibilityVersion/commit/bd645ac777d9f620fad9854c606b81f48d8e6a07

## What did you expect to happen?

cocoapod will respect compatibility version

## What happened instead?

Pods project still use compatibility version 10.0 and use `.xcfilelist` inside build phase:
https://github.com/Speakus/CocoapodIssueChangeCompatibilityVersion/blob/master/CocoapodIssueChangeCompatibilityVersion.xcodeproj/project.pbxproj#L166

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G3020)
       Xcode : 11.3 (11C29)
         Git : git version 2.26.0
Ruby lib dir : /Users/speakus/.rbenv/versions/2.3.7/lib
Repositories : artsy - git - https://github.com/artsy/Specs.git @ 285dab6864a02da926cb0786f58ee3d800ffe372

               AtlasCocoapods - git - https://bitbucket.org/firstatlas/AtlasCocoapods.git @ 7dcbeaefdc11b7a1f120b8a1a20d274d9d57d975

               bitbucket-simpletechs-avoplayer-cocoapods - git - https://bitbucket.org/simpletechs/avoplayer-cocoapods.git @ 1786e8d99ad65259519565988d6f402e8b8fe4de

               cocoapods - git - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875

               goinstant - git - https://github.com/goinstant/pods-specs-public @ 03600012d72355c5ac7f5f1060c023c18c2035ae

               master - git - https://github.com/CocoaPods/Specs.git @ b3447f0ca8350c384edef56d6bfb8f227f4bf19c

               trunk - CDN - https://cdn.cocoapods.org/
               twilio - git - https://github.com/twilio/cocoapod-specs @ 9bf659ed7246ba34625b81754031fbd5ac20fe68

```

### Installation Source

```
Executable Path: /Users/speakus/.rbenv/versions/2.3.7/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Podfile syntax here: https://guides.cocoapods.org/syntax/podfile.html
minTarget = '10.0'

def crashPods()
    # for getting useful info about crashes
    pod 'Crashlytics' # Commercial
    pod 'Fabric' # Commercial
end

platform :ios, minTarget
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'CocoapodIssueChangeCompatibilityVersion' do
  crashPods
  pod 'PKHUD'
end
```

## Project that demonstrates the issue

https://github.com/Speakus/CocoapodIssueChangeCompatibilityVersion

**Comment by amorde** [comment]
CocoaPods uses `objectVersion` when gating project features that require certain Xcode features. Looks like the example project is using an `objectVersion` [that indicates Xcode 10.x](https://github.com/Speakus/CocoapodIssueChangeCompatibilityVersion/blob/bd645ac777d9f620fad9854c606b81f48d8e6a07/CocoapodIssueChangeCompatibilityVersion.xcodeproj/project.pbxproj#L6), don't remember the specific version that introduced object version 51 but I know its at least Xcode 10.

Are you using a newer version of Xcode but needing to maintain compatibility with older Xcode versions?

**Comment by Speakus** [comment]
> Are you using a newer version of Xcode but needing to maintain compatibility with older Xcode versions?

Previously I definitely uses Xcode 9 and Xcode 10. In near future I will use Xcode 10.3 and Xcode 11 simultaneously.
Anyway the context of this issue is here: https://github.com/CocoaPods/CocoaPods/issues/9056#issuecomment-525409978

**Comment by amorde** [comment]
I think we should update our logic here to use the compatibility version instead of the object version

**Comment by Speakus** [comment]
the issue is still on 1.9.1 version of cocoapod
