### ISSUE TITLE
iOS [error] file patterns: The `source_files` pattern did not match any file

### ISSUE THREAD

**Issue by keithtso** [CocoaPods/CocoaPods#9143]
Recently I've created a podspec and successfully push to cocoapods. The fisrt version is like below:
Pod::Spec.new do |spec|

  spec.name         = "sample-SDK"
  spec.version      = "4.2.6.2"
  spec.summary      = "My iOS sample SDK."
......
......

  spec.source       = { "http" => "https://XXXXX_v4.2.6.2.zip" }

  spec.public_header_files = "XXXX_v4.2.6.2/sdk/bbb.framework/Headers/*.h"

  spec.source_files  = "XXXX_v4.2.6.2/sdk/bbb.framework/Headers/*.h"

  spec.resources = "XXXX_v4.2.6.2/sdk/bbb.framework/bbb.bundle"

  spec.ios.vendored_frameworks = "XXXX_v4.2.6.2/sdk/bbb.framework"

  .....
end

And then the framework has a new version updated to v4.2.7, I update the podspec file to :
Pod::Spec.new do |spec|

  spec.name         = "sample-SDK"
  spec.version      = "4.2.7"
  spec.summary      = "My iOS sample SDK."
......
......

  spec.source       = { "http" => "https://XXXXX_v4.2.7.zip" }

  spec.public_header_files = "XXXX_v4.2.7/sdk/bbb.framework/Headers/*.h"

  spec.source_files  = "XXXX_v4.2.7/sdk/bbb.framework/Headers/*.h"

  spec.resources = "XXXX_v4.2.7/sdk/bbb.framework/bbb.bundle"

  spec.ios.vendored_frameworks = "XXXX_v4.2.7/sdk/bbb.framework"

  .....
end

when I do pod spec lint sample-SDK.podspec --verbose, 3 errors come out: 
ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `resources` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `vendored_frameworks` pattern did not match any file.

The source download link is correct and the file structure is the same as the previous one except v4.2.6.2 changed to v4.2.7. 
Did I write the correct path for source_files, resources and vendored_frameworks?

====================================
An update: 
spec.public_header_files = "**sdk/bbb.framework/Headers/*.h**"

  spec.source_files  = "**sdk/bbb.framework/Headers/*.h**"

  spec.resources = "**sdk/bbb.framework/bbb.bundle**"

  spec.ios.vendored_frameworks = "**sdk/bbb.framework**"

when I change the path to **sdk/bbb.framework/**, it passes validation?

Why the path changed to start with sdk instead of XXXX_v4.2.7?

**Comment by dnkoutso** [comment]
We cannot diagnose this without a podspec. The error message clearly says that the zip file you include maybe does not match the glob you are using in your podspec.

It is best to ask StackOverflow under `cocoapods` tag for this as this does not appear an issue with the CocoaPods library.
