### ISSUE TITLE
CocoaPoads client does not support any authentication, even simple one by login/password during fetching Spec files and metadata files(like all_pods.txt) from CDN source(s).

### ISSUE THREAD

**Issue by igorudovika** [CocoaPods/CocoaPods#9151]
I am trying new CDN approach in restricted zones. To work with custom created CDN source or to work with public https://cdn.cocoapods.org one via proxy server. I had a look in source code https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/cdn_source.rb and found that during get request CocoaPods client does not  try to set login/password and always works with anonymous user. I can see rest client Fingertips/nap in source code and it can use login/password. In same time seems it is possible to use authentication for fetching pod libraries sources.

**Comment by dnkoutso** [comment]
cc @igor-makarov

**Comment by igor-makarov** [comment]
The server does not require authentication. It's public. 

Using a proxy is done by setting the `http_proxy` environment variable, as is customary in Ruby.

**Comment by igorudovika** [comment]
> The server does not require authentication. It's public.
> 
> Using a proxy is done by setting the `http_proxy` environment variable, as is customary in Ruby.

@igor-makarov thanks for answer, yep, I am familiar `http_proxy` environment variable. I talked more about different kinds of proxying repository managers.  In same time as far CDN approach is becoming main and default one I am thinking how to work with private Specs repositories.

**Comment by igor-makarov** [comment]
Private spec repos can use the original git method, it wasn't deprecated and is still fully supported. We decided they tend to be much smaller and therefore not in need of CDN. 

What size are your private spec repos? Care to elaborate on your use cases?

**Comment by igorudovika** [comment]
Yep, I am understanding that main target of CDN approach is resolving problem with huge size of master Spec repo and that for now it is still possible to use git approach. I just would like to see CDN approach more flexible and seems now(on stage of first implementations) is good time to do it. So in future for different use cases we all will not need to choose different approaches because each of them have limitations that was skipped initially.

**Comment by igor-makarov** [comment]
I think using the CDN is an optimization based on the main registry's size. 

git is much more suited for everything else, precisely because it's a well-tested and flexible tool that can give users all the authentication and proxying options they need.

**Comment by jlstephens89** [comment]
Hi @igor-makarov. Repository Managers (such as the open source tool Nexus Repository Manager) are designed to work via HTTP so the "CDN mode" is a great fit. NXRM can be used for private specs repositories but also for proxying any publicly available specs repositories. Enabling organizations to use a repository manager will reduce how much they hit the CDN because the specs files will be cached locally. 

We are hearing from lots of organizations that they want to be able to use their repository managers with CocoaPods but also expect to be able to authenticate from the Cocoapods Client to control access. Adding the option for authentication here would make for a great user experience with a repository manager and would further help with the adoption of Cocoapods within some larger orgs.

**Comment by igorudovika** [comment]
Seems Core functionality is going to be moved here. I can see PR 8980. But for now it is different repo. So I am providing two PRs that should resolve issue. If these two repos will be merged then I will work to prepare new one

**Comment by dnkoutso** [comment]
PR 8980 might not land in a long while as we consider it a breaking change. The PRs you have in the two repos should be good.

**Comment by igorudovika** [comment]
> #8980 might not land in a long while as we consider it a breaking change. The PRs you have in the two repos should be good.

got it, thanks
