### ISSUE TITLE
how does podspec add a local denpendency

### ISSUE THREAD

**Issue by mrkizy** [CocoaPods/CocoaPods#9155]
I have a program, we call it A program, and it depends on other sdk called B, B sdk is a local program that depends on other local sdk called C, so an issues happends:
beacuese B and C sdk are local dependencies, when A program  depens on B sdk, run "pod install", errors happends. below is the podfile of A program:
pod 'B_sdk', :path=> '../b_sdk folder'
and below is the podspec of B sdk:
s.dependency '../C_sdk'(beacuse B depends on C sdk which is a local dependency ),
I know that ths podspec is incorrect, but I have no idea that how does podspec add a local denpendency,beacuse A->B(local)->C(local).

**Comment by dnkoutso** [comment]
you cannot set a dependency in a podspec as local because podspecs are meant to be published.

If you want that to work you need to setup the dependency in the `Podfile` via `:path` directive.

Closing as it appears a question and not an issue or enhancement.
