### ISSUE TITLE
How to modify `'Pods.xcodeproj'` project name ?

### ISSUE THREAD

**Issue by dacaiguoguogmail** [CocoaPods/CocoaPods#9159]
`CocoaPods/lib/cocoapods/sandbox.rb` line 132
```
    def project_path
      root + 'Pods.xcodeproj'
    end
```

Is there a way or parameter to modify the project name?

**Comment by dacaiguoguo** [comment]
https://guides.cocoapods.org/syntax/podfile.html#plugin

Can it be implemented by means of plugins?

**Comment by dacaiguoguo** [comment]
```
pre_install do |installer|
    original_sand = installer.sandbox
    def original_sand.project_path
        return @root + 'BarPods.xcodeproj'
    end
    puts installer.sandbox.project_path
end
```

`pre_install` is good way.

**Comment by dnkoutso** [comment]
No current way to modify it. What you did should be OK.
