### ISSUE TITLE
RuntimeError - [Xcodeproj] Consistency issue: no parent for object `RNPlaceholder.swift`: `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`

### ISSUE THREAD

**Issue by newah** [CocoaPods/CocoaPods#9166]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Working on new react-native version, creating a module that requires swift.
To test it:
1) generated a sample project, i.e.  react-native init tester --version 0.60.5
2) yarn add react-native-swift (to be able to use swift)
3) react-native link react-native-swift
4) yarn add react-native-argyle-sdk (custom module that uses swift code)
5) cd ios && pod install

## What did you do?
pod install

## What did you expect to happen?
install pods successfully

## What happened instead?
got an error (for some reason it started working on 1 project, but keeps failing on newly generated)

RuntimeError - [Xcodeproj] Consistency issue: no parent for object `RNPlaceholder.swift`: `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`, `SourcesBuildPhase`
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb:18:in `parent'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project/object/build_file.rb:71:in `ascii_plist_annotation'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project.rb:296:in `block in to_ascii_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project.rb:295:in `each'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project.rb:295:in `to_ascii_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project.rb:364:in `block in save'
/Library/Ruby/Gems/2.3.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
/Library/Ruby/Gems/2.3.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.10.0/lib/xcodeproj/project.rb:363:in `save'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/user_project_integrator.rb:158:in `block in save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/user_project_integrator.rb:156:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/user_project_integrator.rb:156:in `save_projects'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/user_project_integrator.rb:76:in `integrate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:780:in `block in integrate_user_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:776:in `integrate_user_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0b313154daa72f313bfa37d78b7a3062ad6811a7
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
After adding Signing team, the error disappears.

would be able to provide a project with this error within couple of days if needed.

**Comment by dnkoutso** [comment]
Looks like a bad user project. Please attach reproducible sample for us to diagnose.

**Comment by roduyemi** [comment]
It case it helps anyone, I managed to install Pods by removing `RNPlaceholder.swift` from the project.

**Comment by soulloop-dev** [comment]
> It case it helps anyone, I managed to install Pods by removing `RNPlaceholder.swift` from the project.

Make sure you have a File.swift file in your root project.
