### ISSUE TITLE
git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by dathu7728** [CocoaPods/CocoaPods#9171]
![Screenshot 2019-09-20 at 5 31 38 PM](https://user-images.githubusercontent.com/15993908/65325720-3e35c280-dbcd-11e9-82c4-1a0a8caaf174.png)

Setting up CocoaPods master repo
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git --progress
  -- master
  Cloning into 'master'...
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
[!] /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git --progress -- master

Cloning into 'master'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by dathu7728** [comment]
while install pods

pod install
Analyzing dependencies
Setting up CocoaPods master repo
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git --progress
  -- master
  Cloning into 'master'...
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.

**Comment by dnkoutso** [comment]
This looks like a network issue on your side. Closing but I will reopen if we see a bug in cocoapods with a sample.

**Comment by DhanyarajPaytm** [comment]
@dnkoutso , Even i am facing same problem. Issue is not due to network here. It says public key is missing and we tried all the ways possible to add new SSH keys etc. Still no luck.

**Comment by hemendraggohel** [comment]
Hello,

I am facing the same issue. Tried all luck by setting up ssh. 
![Screenshot 2021-08-31 at 5 55 28 PM](https://user-images.githubusercontent.com/59216569/131506520-bf38a63d-0628-43b6-a00c-9a2acea1b602.png)


Kindly suggest?
