### ISSUE TITLE
Claiming hidapi ownership (claim form doesn't work for us)

### ISSUE THREAD

**Issue by vitalys** [CocoaPods/CocoaPods#9173]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

We're trying to claim hidapi pod ownership using https://trunk.cocoapods.org/claims/new

## What did you expect to happen?

Transfer ownership to libusb/hidapi team

## What happened instead?

No answer received.

**Comment by dnkoutso** [comment]
I believe this was taken care of. Apologies for delay on looking at disputes.

**Comment by dnkoutso** [comment]
Let me know if it didn't and I will re-open.

**Comment by Youw** [comment]
Me, and @vitalys both got access, thanks!
