### ISSUE TITLE
Unable to access content of Assets.car file

### ISSUE THREAD

**Issue by Yqnn** [CocoaPods/CocoaPods#9180]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I created a basic Swift framework pod containing:
- Some Swift classes
- An asset catalog containing PNG images

The pod spec contains the following line:
`spec.resource_bundle = { "MyFramework" => "MyFramework/**/*.xcassets"}`

Then I created an application that uses this pod.

## What did you expect to happen?

I expect the xcassets file to be compiled into a `Assets.car`, and the content of this `Assets.car` to be accessible from the application.

## What happened instead?

The generated application contains a `Framework` folder that looks like this:
```
Frameworks
└── MyFramework.framework
    ├── Info.plist
    └── MyFramework.bundle
        ├── Info.plist
        └── Assets.car
```

I tried two approaches to read the content of `Assets.car` :
```swift
// This bundle points to the MyFramework.framework folder:
let frameworkBundle = Bundle(identifier: "org.cocoapods.MyFramework")!

// This bundle points to the MyFramework.bundle folder:
let nestedBundle = Bundle(path:"\(frameworkBundle.resourcePath!)/MyFramework.bundle")!

// These 2 lines always returns nil, I would have expected at least the second line to return a UIImage
UIImage(named: "myimage", in: frameworkBundle, compatibleWith: nil) 
UIImage(named: "myimage", in: nestedBundle, compatibleWith: nil) 
```

Actually, it doesn't work because the `Info.plist` files both use the same Bundle identifier. So the 2 Bundle instances expects the `Assets.car`file to be in `MyFramework.framework` and not in `MyFramework.bundle`.

By playing with the generated configuration I found 2 possible solutions that seem to work:
- Do not create `MyFramework.bundle`, and copy all its content directly inside `MyFramework.framework`
- Use a different Bundle Identifier for `MyFramework.bundle`

### Stack

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  pod 'MyFramework', :git => '../MyFramework', :tag => '1.0.0'

end
```

## Project that demonstrates the issue

[Archive.zip](https://github.com/CocoaPods/CocoaPods/files/3649299/Archive.zip)

**Comment by dnkoutso** [comment]
I do not think we support directly copying resources into the `.framework` itself of your pod. If you use `s.resources` those will be copied to the target that integrates your pod.

**Comment by Yqnn** [comment]
Indeed, seems it works much better with `s.resources`.
Thanks @dnkoutso !
