### ISSUE TITLE
"Multiple commands produce" error when building unit test target without a host

### ISSUE THREAD

**Issue by akashivskyy** [CocoaPods/CocoaPods#9185]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

### What did you do?

1. Set up a pod that vendors a binary framework (e.g. `Library.framework`) **and a dSYM artifact** (e.g. `Library.framework.dSYM`).

2. Set up a project that has a unit test target **without a host application**.

3. Run `pod install`.

4. Built the unit test target **for testing**.

### What did you expect to happen?

Compiling succeeds and dependency is available in both main target and unit test target.

### What happened instead?

Compiling fails because:

```
Multiple commands produce '/Users/Adrian/Library/Developer/Xcode/DerivedData/Demo/Build/Products/Debug-iphonesimulator/Library.framework.dSYM':
1) That command depends on command in Target 'Demo' (project 'Demo'): script phase “[CP] Embed Pods Frameworks”
2) That command depends on command in Target 'DemoTests' (project 'Demo'): script phase “[CP] Embed Pods Frameworks”
```

### Workarounds

1. Setting a test host for the unit test target makes it work.

2. Switching to the legacy build system makes it work.

3. Adding `disable_input_output_paths: true` option makes it work.

### Stack

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.0 (11M392r)
         Git : git version 2.23.0
Ruby lib dir : /Users/Adrian/.rbenv/versions/2.6.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ aff37984f83a304d8f1f3c5bd909f8f377617acc
```

### Installation Source

```
Executable Path: /Users/Adrian/.rbenv/versions/2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-keys        : 2.1.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
   pod "Kingfisher", podspec: "./Kingfisher/Kingfisher.podspec"
end

target 'Demo' do
    shared_pods
end

target 'DemoTests' do
    shared_pods
end
```

## Project that demonstrates the issue

Attached: [15589-9.0.0-ios.zip](https://github.com/CocoaPods/CocoaPods/files/3651971/15589-9.0.0-ios.zip). The archive consists of:

- `Demo.xcodeproj` that has the set up described above.
- `Kingfisher.framework` and `.dSYM` used by `Podfile`.

**Comment by dnkoutso** [comment]
Hm maybe a bug but thanks for the report and sample app! If its identified to be an issue we can fix it for 1.8.1 release.

**Comment by dnkoutso** [comment]
It's because your `DemoTests` depends on `DemoApp` but it does not use it as its app host as you said initially. 

You can also remove the `DemoApp` dependency from the 'Dependencies' phase in your `DemoTests` target.

**Comment by akashivskyy** [comment]
I understand that the workarounds... work.

But target dependency only describes which targets are built _before_ the current one. Having a unit test target without a test host is a **valid setup** that should be supported while using xcfilelists.

This setup _is_ supported for open source pods that don't have the need to define dSYMs in `preserve_paths`. It only breaks if there's a dSYM. That's why I believe it's an issue in file lists generated by CocoaPods.

**Comment by dnkoutso** [comment]
Its probably a bug yes in CocoaPods. we need to detect if the dependency is set but _not_ the app host.

It seems Xcode does not complain in the case in which the app host is set...this will require a change in CocoaPods to detect that case.

**Comment by ricardolx** [comment]
This started happening for me on the xcode 11. 

In build phases, we have custom fonts included in Copy Bundle Resources and we also had them as input and output files in Copy Pods Resources. In order for the build to work, we have to remove them from Copy Pods Resources, but Pod install/update re-adds them here.

**Comment by wangyutao0424** [comment]
> This started happening for me on the xcode 11.
> 
> In build phases, we have custom fonts included in Copy Bundle Resources and we also had them as input and output files in Copy Pods Resources. In order for the build to work, we have to remove them from Copy Pods Resources, but Pod install/update re-adds them here.

We have same problem.

**Comment by dnkoutso** [comment]
I do not think the last two comments are the same issue. Rather a different one and possibly a misconfiguration of the project.

For the original issue this is definitely confirmed. We use `${DWARF_DSYM_FOLDER_PATH}/Kingfisher.framework.dSYM` for the output path of each dSYM because that is where Xcode copies `dSYMs` too. It seems that this is triggered as long as the test target does not use the target app as its app host.

**Comment by nikolaykasyanov** [comment]
I've hit a similar issue with in a different setup. So I have an app target (`App`) that has the following dependencies:

* `B`, a developmeent pod with a vendored framework and dSYM.
* `A`, a development pod that also depends on `B` and has a hostless test spec.

Here's the error message:
```
Multiple commands produce '/path/to/Build/Products/Debug-iphonesimulator/B.framework.dSYM':
1) That command depends on command in Target 'A-Unit-Tests' (project 'Pods'): script phase “[CP] Embed Pods Frameworks”
2) That command depends on command in Target 'App' (project 'App'): script phase “[CP] Embed Pods Frameworks”
```

**Comment by navartis** [comment]
We have a very difficult non trivial project structure and use [cocoapods-binary](https://github.com/leavez/cocoapods-binary) plugin.

In case of deactivation cocoapods-binary this issue are not reproduced for our project.

But cocoapods-binary are very useful for us and I solve issue by running script right after pod install

```
#!/bin/bash -l
set -e
set -o pipefail

full_local_path=$(dirname "$0")

for pfx in "Pods-UIKitDemo" "Pods-Settings" "*TestApp" "*Tests"; do
	find $full_local_path/../Pods -type f -name "$pfx-frameworks-Debug-output-files.xcfilelist" -exec sed -E -i '' '/.*framework\.dSYM$/d' {} \;
done
```

This script are not universal.
If you want to use it you should change string "for pfx in "Pods-UIKitDemo" "Pods-Settings" "*TestApp" "*Tests"; do"

**Comment by kacper1703** [comment]
For me (Xcode 11, CP 1.8.4) switching to "Legacy Build System" in fixes the build issue but requires me to switch to the system each time I want to run tests. This is really troublesome.

**Comment by dnkoutso** [comment]
We investigated the issue further, this is actually a much more complex change so it will have to be in 1.10.0 release.

The issue here is that CocoaPods treats dSYMs as if they were frameworks during the embedding stage versus all that is needed is to just copy the vendored dSYM into the Products dir.

I am re-implemeting this from scratch and will have a PR soon.

**Comment by dnkoutso** [comment]
Work in progress here https://github.com/CocoaPods/CocoaPods/issues/9185

**Comment by dnkoutso** [comment]
@akashivskyy can you try #9547 ?

**Comment by akashivskyy** [comment]
@dnkoutso I confirm that the sample project I attached now builds with #9547. Thank you! ❤️

**Comment by dnkoutso** [comment]
awesome! @akashivskyy I pushed another update. This should land today (PST timezone)

**Comment by dnkoutso** [comment]
One more follow up to use `DWARF_DSYM_FOLDER_PATH` instead https://github.com/CocoaPods/CocoaPods/pull/9552. This ensures again dSYMs are copied correctly for archiving.

**Comment by nabillanurj** [comment]
> @akashivskyy can you try #9547 ?

sorry just want to asking, how i implement this one?

**Comment by Jon889** [comment]
@dnkoutso Now that 1.10 is released has this been fixed?

**Comment by dnkoutso** [comment]
Looks like closed and marked for this release so it should be yes.

**Comment by FaultyJuggler** [comment]
Seeing this issue with similar setup to @navartis, using binary in prebuild because Firebase and other google pods are massive (15-20 min) compile times
With cocoapods-binary I get

**Comment by seanmalone-redibs** [comment]
@FaultyJuggler Did you figure this out? I'm seeing the same.

**Comment by StefaniOSApps** [comment]
same with binary ..

**Comment by acecilia** [comment]
Yes, I am seeing the same as @FaultyJuggler in the latest version of cocoapods `1.10.0`

**Comment by carlosmellado** [comment]
Same happening with :binary => true
Tried workaround #10373 with no luck.

**Comment by carlosmellado** [comment]
Found this post integrate script that did the trick, if someone is looking for:

```
post_integrate do |installer|
  installer.pods_project.targets.each do |target|
    target.shell_script_build_phases.each do |phase|
      script = phase.shell_script
      if script.include? "-copy-dsyms.sh\""
        script = script.delete_prefix "\"${PODS_ROOT}/"
        script = script.delete_suffix "\"\n"
        script = "Pods/" + script

        contents = File.read(script)
        contents = contents.gsub(/-av/, "-r -L -p -t -g -o -D -v")
        File.open(script, "w") do |file|
          file.puts contents
        end
      end
    end
  end
end
```

**Comment by RajvinderPayU** [comment]
> Found this post integrate script that did the trick, if someone is looking for:
> 
> ```
> post_integrate do |installer|
>   installer.pods_project.targets.each do |target|
>     target.shell_script_build_phases.each do |phase|
>       script = phase.shell_script
>       if script.include? "-copy-dsyms.sh\""
>         script = script.delete_prefix "\"${PODS_ROOT}/"
>         script = script.delete_suffix "\"\n"
>         script = "Pods/" + script
> 
>         contents = File.read(script)
>         contents = contents.gsub(/-av/, "-r -L -p -t -g -o -D -v")
>         File.open(script, "w") do |file|
>           file.puts contents
>         end
>       end
>     end
>   end
> end
> ```

Still facing this issue, even after trying your solution. @dnkoutso what could be the possible reason. Thanks in advance.
