### ISSUE TITLE
CocoaPods 1.8.0 added 'trunk' to my repo though I don't use 'trunk'

### ISSUE THREAD

**Issue by owenzhao** [CocoaPods/CocoaPods#9190]
* [*] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I updated to CocoaPods 1.8.0 and I run `pod install`.

## What did you expect to happen?
 
CocoaPods works like previous version.

## What happened instead?

CocoaPods added a trunk repo to me.

```
$ pod install
Analyzing dependencies
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

Since then, whenever I run `pod repo update`, there is a ``Updating spec repo `trunk` `` that takes long time. 

I don't need `trunk`, how to removing it?

### Stack

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
    RubyGems : 3.0.4
        Host : Mac OS X 10.15 (19A573a)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /usr/local/Cellar/ruby/2.6.4_2/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 09b4075bdb5ce5c5e3aad5beb808ee78a1a0016d
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stand Minus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '13.1'
  use_frameworks!

  # Pods for Stand Minus
  pod 'OneSignal', '>= 2.6.2', '< 3.0'

end

# target 'Stand Minus WatchKit App' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for Stand Minus WatchKit App
#
# end

# target 'Stand Minus WatchKit Extension' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for Stand Minus WatchKit Extension
#
# end
```

**Comment by amorde** [comment]
Hello 👋 

`trunk` is the new name for the main specs repo which is backed by a CDN. This repo is included by default, and since your Podfile does not have any custom spec repos specified, it is being included in this case.

`trunk` replaces `master` in 1.8.0. You can continue you use `master` by manually specifying it in your Podfile, or you can continue with `trunk` and run `pod repo remove master`  to remove the previous git-based repo.

For more details on the CDN repo, check out [this blog post](http://blog.cocoapods.org/CocoaPods-1.8.0-beta/) detailing the changes in 1.8.0

I'm going to close this as it doesn't seem to be an issue in CocoaPods, but will re-open if we determine there's a bug here.

**Comment by IDFC-DEV** [comment]
Hello @amorde ,
I am facing the issue, in my podfile.lock i relpaced trunk with master url but when i do pod install it again adds the trunk spec also tried by adding source as master url in podfile but still trunk is used.

Can you please help?

**Comment by owenzhao** [comment]
> Hello @amorde ,
> I am facing the issue, in my podfile.lock i relpaced trunk with master url but when i do pod install it again adds the trunk spec also tried by adding source as master url in podfile but still trunk is used.
> 
> Can you please help?

You should does nothing with `podfile.lock` file. I wrote a blog on how to changing back from trunk to main https://zhaoxin.pro/15695124897584.html. If you know Chinese, you can read the previous blog. 

Here is what you should do.

1. If you already have trunk. In terninal, run 
```pod repo remove trunk```
2. If you mater was removed. run below code to recover
```git clone https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master```
3. last, but not the least, in each `Podfile` of your projects, on the very beginning, insert a line with 
```source 'https://github.com/CocoaPods/Specs.git'```

Then you can use cocoapods in the legacy way.

**Comment by vlaksi** [comment]
> > Hello @amorde ,
> > I am facing the issue, in my podfile.lock i relpaced trunk with master url but when i do pod install it again adds the trunk spec also tried by adding source as master url in podfile but still trunk is used.
> > Can you please help?
> 
> You should do nothing with `podfile.lock` file. I wrote a blog on how to changing back from trunk to main https://zhaoxin.pro/15695124897584.html. If you know Chinese, you can read the previous blog.
> 
> Here is what you should do.
> 
> 1. If you already have trunk. In terninal, run
>    `pod repo remove trunk`
> 2. If you mater was removed. run below code to recover
>    `git clone https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master`
> 3. last, but not the least, in each `Podfile` of your projects, on the very beginning, insert a line with
>    `source 'https://github.com/CocoaPods/Specs.git'`
> 
> Then you can use cocoapods in the legacy way.

You saved my day !! <3
