### ISSUE TITLE
Framework targets broken on 1.6.0+

### ISSUE THREAD

**Issue by rwbutler** [CocoaPods/CocoaPods#9197]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run pod install on a fresh project that contains an app and a framework target.

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Project will compile successfully but at runtime fail with the following error:

```
dyld: Library not loaded: /System/Library/Frameworks/Network.framework/Network
  Referenced from: /Users/butlerrr/Library/Developer/CoreSimulator/Devices/D80B56A3-0D79-474E-BF2B-4DDE362ED1CC/data/Containers/Bundle/Application/9930F558-E3E7-4D24-B9B3-4324975A461C/ConnectivityTest.app/Frameworks/Connectivity.framework/Connectivity
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/Network.framework/Network: mach-o, but not built for iOS simulator
```

I noticed that this became an issue after introducing the following line into the podspec:

```
s.frameworks      = 'Network', 'SystemConfiguration'
```

It only appears to be an issue where using `use_frameworks!`. When built as a static library the issue does not arise.

I have also noticed that this issue appears to have been reported previously but the issue was closed without being fixed:

[https://github.com/CocoaPods/CocoaPods/issues/8664](https://github.com/CocoaPods/CocoaPods/issues/8664)

### Stack

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.6.13
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ d6d9199b6a25239bf886c56b13868b91eb0e1586
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!
target 'ConnectivityTest'
  platform :ios, '12.0'
  pod 'Connectivity'
```

## Project that demonstrates the issue

[https://github.com/rwbutler/connectivitytest](https://github.com/rwbutler/connectivitytest)

**Comment by dnkoutso** [comment]
This worked just fine for me on Xcode 11 (11A419c) on iPhone 11 Pro Max sim.

I used CocoaPods 1.8.1 (which shouldnt have big changes from 1.8.0 which you have in your sample project.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-27 at 14 20 38](https://user-images.githubusercontent.com/310370/65792565-0af5b500-e132-11e9-9ea6-90ead668604e.png)

Unable to reproduce so far.

**Comment by dnkoutso** [comment]
Can repro on iOS 11.

**Comment by dnkoutso** [comment]
This appears to be an Apple issue not so much of a CocoaPods issue:
```
dyld: Library not loaded: /System/Library/Frameworks/Network.framework/Network
  Referenced from: /Users/dimitris/Library/Developer/CoreSimulator/Devices/EC935B0F-3901-4CE8-88BE-8938AD79C6DE/data/Containers/Bundle/Application/35967D2D-DC7A-407C-BD62-65FD16DAAB70/ConnectivityTest.app/Frameworks/Connectivity.framework/Connectivity
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/Network.framework/Network: mach-o, but not built for iOS simulator
```

**Comment by dnkoutso** [comment]
These frameworks appear to be system frameworks so CocoaPods besides adding them to be linked doesnt do anything special.

It also works on iOS 13 so I am inclined to say its an Apple/Xcode issue.

**Comment by rwbutler** [comment]
Solved this issue - all that was required was to make the dependency on `Network.framework` part of the `weak_frameworks` (I was previously unaware that this existed) rather than `frameworks` in the podspec so that it was linked correctly on iOS 11 and below (`Network.framework` is available from iOS 12 only).
