### ISSUE TITLE
Xcode 11 - pod install - [!] Error installing - dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by DK-Web** [CocoaPods/CocoaPods#9202]
# Report

## What did you do?

pod install

## What did you expect to happen?

Install all pod dependencies correctly. But I get the same error in any attempt to install any pod.

## What happened instead?

[!] Error installing HelloWorld_testingPod
[!] /usr/bin/git clone https://github.com/SunnySs/HelloWorld_testingPod.git /var/folders/49/k2kb5k6s3kj0qtxrg5tb_c880000gn/T/d20190928-5910-1btcljg --template= --single-branch --depth 1 --branch 0.2.0

Cloning into '/var/folders/49/k2kb5k6s3kj0qtxrg5tb_c880000gn/T/d20190928-5910-1btcljg'...
dyld: lazy symbol binding failed: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib

dyld: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib

## CocoaPods Environment

   CocoaPods : 1.8.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - file system
               trunk - CDN - https://cdn.cocoapods.org/

**Comment by dnkoutso** [comment]
This seems like a user configuration issue, have you upgraded to latest macOS? If you run:
```git clone https://github.com/SunnySs/HelloWorld_testingPod.git /var/folders/49/k2kb5k6s3kj0qtxrg5tb_c880000gn/T/d20190928-5910-1btcljg --template= --single-branch --depth 1 --branch 0.2.0```
from your console does it still fail?

**Comment by DK-Web** [comment]
hi, thank you for your quick support. I'm really desperate. When I call this command the same error occurs:

`git clone https://github.com/SunnySs/HelloWorld_testingPod.git /var/folders/49/k2kb5k6s3kj0qtxrg5tb_c880000gn/T/d20190928-5910-1btcljg --template= --single-branch --depth 1 --branch 0.2.0
Cloning into '/var/folders/49/k2kb5k6s3kj0qtxrg5tb_c880000gn/T/d20190928-5910-1btcljg'...
dyld: lazy symbol binding failed: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib

dyld: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib`

I just updated the Mac, but the bug is still there.

System: MacOS Mojave Version: 10.14.6 (18G103)

Thank you for helping me!

**Comment by DK-Web** [comment]
Ok, I have partially corrected the error. I had to enter these commands in the console:

`export PATH="/usr/local/bin:${PATH}"
source ~/.bash_profile`

Afterwards I can do it as long as I do not close the terminal. But how can I set it up permanently?

**Comment by DK-Web** [comment]
I could fix the problem. The PATH was changed in the .bash_profile file for whatever reason.

Add in .bash_profile: 

`export PATH="/usr/local/bin:${PATH}“`

and it works again.

Thanks again for the support!

**Comment by dnkoutso** [comment]
yeap!

**Comment by demiculus** [comment]
This worked for me: https://stackoverflow.com/a/31780545/4204919
