### ISSUE TITLE
Errno::ENOENT - No such file or directory @ rb_sysopen 

### ISSUE THREAD

**Issue by nlanatta** [CocoaPods/CocoaPods#9209]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod repo update`

## What did you expect to happen?

Update all pod dependencies correctly.

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/ionic/.cocoapods/repos/Spec_Lock
/Users/ionic/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:118:in `initialize'
/Users/ionic/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:118:in `open'
/Users/ionic/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:118:in `update'
/Users/ionic/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.8.0/lib/cocoapods/command/repo/update.rb:23:in `run'
/Users/ionic/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/ionic/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:52:in `run'
/Users/ionic/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.8.0/bin/pod:55:in `'
/Users/ionic/.fastlane/bin/bundle/bin/pod:22:in `load'
/Users/ionic/.fastlane/bin/bundle/bin/pod:22:in `

## CocoaPods Environment

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.5.2
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/ionic/.fastlane/bin/bundle/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Ionic AppFlow process

**Comment by dnkoutso** [comment]
Something is wrong with your spec repos. `pod repo list` and remove the bad repo maybe called `Spec_Lock` or something.

**Comment by eteeselink** [comment]
FWIW, I have the same issue, on a brand new clean mac:

```sh
> sudo gem install cocoapods
> pod repo update # (or `pod try somethingsomething`)
```

and I get the exact same error as @nlanatta . I have absolutely no idea what to do :)

**Comment by felix-zg** [comment]
Same here :(

**Comment by stefanmdt** [comment]
I had the same problem on a clean mac, too. Found this related issue: https://github.com/flutter/flutter/issues/41253. 

I switched back to an older version and now pod setup is downloading the repos ...

**Comment by distinctdan** [comment]
Following, have exact same issue on a clean install.

**Comment by dnkoutso** [comment]
Please see https://github.com/CocoaPods/CocoaPods/issues/9216

Run at least once `pod install` to fix the issue.

**Comment by distinctdan** [comment]
Running `pod install` did nothing for me. Here's my issue with more details: https://github.com/CocoaPods/CocoaPods/issues/9228

**Comment by hannatagen** [comment]
running `pod repo update` and then `pod install` did the job for me

**Comment by VincentSit** [comment]
I encountered this problem after I upgraded to macOS Catalina, the answers above did not work for me. I removed the CDN repo and it worked.

My CocoaPods version is `1.8.4`.

```
$ bundle exec pod repo

jsdelivr-cocoa
- Type: CDN
- URL:  https://cdn.jsdelivr.net/cocoa/
- Path: /Users/myuser/.cocoapods/repos/jsdelivr-cocoa

master
- Type: git (master)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/myuser/.cocoapods/repos/master

trunk
- Type: CDN
- URL:  https://cdn.cocoapods.org/
- Path: /Users/myuser/.cocoapods/repos/trunk

3 repos
```

```
$ bundle exec pod repo remove jsdelivr-cocoa
Removing spec repo `jsdelivr-cocoa`
```

```
$ bundle exec pod repo remove trunk
Removing spec repo `trunk`
```

```
$ bundle exec pod repo update
Updating spec repo `master`
  $ /usr/bin/git -C /Users/myuser/.cocoapods/repos/master fetch origin --progress
  remote: Enumerating objects: 27019, done.
  remote: Counting objects: 100% (27019/27019), done.
  remote: Compressing objects: 100% (283/283), done.
  remote: Total 82801 (delta 26846), reused 26724 (delta 26724), pack-reused 55782
  Receiving objects: 100% (82801/82801), 9.31 MiB | 227.00 KiB/s, done.
  Resolving deltas: 100% (57582/57582), completed with 5739 local objects.
  From https://github.com/CocoaPods/Specs
     201c4698747..1127a7a2796  master     -> origin/master
  $ /usr/bin/git -C /Users/myuser/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/myuser/.cocoapods/repos/master reset --hard origin/master
  Updating files: 100% (8665/8665), done.
  HEAD is now at 1127a7a2796 [Add] CTool 1.2.2
```
