### ISSUE TITLE
No way to add passing test_spec that doesn't cause build warning "Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform"

### ISSUE THREAD

**Issue by jmagman** [CocoaPods/CocoaPods#9210]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Add test_spec to podspec.
```ruby
s.test_spec 'Tests' do |test_spec|
  test_spec.source_files = 'Tests/**/*'
end
```

```shell
pod lib lint image_picker.podspec --no-clean --verbose
```

i386 linker errors 
```
    Undefined symbols for architecture i386:
      "_FlutterMethodNotImplemented", referenced from:
          -[FLTImagePickerPlugin handleMethodCall:result:] in ImagePickerPlugin.o
      "_OBJC_CLASS_$_FlutterError", referenced from:
          objc-class-ref in ImagePickerPlugin.o
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in ImagePickerPlugin.o
    ld: symbol(s) not found for architecture i386
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

From [the validator code](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/validator.rb#L1040) it looks like the i386 simulator can be excluded by setting a VALID_ARCHS that includes armv7 and x86_64.  See https://github.com/CocoaPods/CocoaPods/issues/8129.  

Add `s.pod_target_xcconfig = { 'VALID_ARCHS' => 'armv7 arm64 x86_64' }` to [podspec](https://github.com/flutter/plugins/blob/master/packages/image_picker/ios/image_picker.podspec).

## What did you expect to happen?

No build warnings or errors.

## What happened instead?

Now there's a new warning, though no errors and tests pass:
```
warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
```
![Screen Shot 2019-10-01 at 11 20 04 AM](https://user-images.githubusercontent.com/682784/65988842-72b34500-e43d-11e9-89ea-470461a55b6a.png)

**What's the suggested value of `VALID_ARCHS` that will prevent the i386 simulator from running but also not cause a build warning?**

## CocoaPods Environment

```shell
$ pod --version                                                               
1.8.1
```

## Project that demonstrates the issue

https://github.com/flutter/plugins/tree/master/packages/image_picker/ios

**Comment by jmagman** [comment]
This seems to have made the warning go away in the actual Xcode project with any simulator/device selected:
```ruby
s.pod_target_xcconfig = { 'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64' }
```

But obviously that isn't the [key the validator is checking](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/validator.rb#L1040), so in the lint I still get this note because the i386 simulator is still building: 
```shell
- NOTE  | [iOS] xcodebuild:  ld: warning: ignoring file /Users/m/Library/Developer/Xcode/DerivedData/App-delzxvvvbagvqiamowplxdvtihdi/Build/Products/Release-iphonesimulator/image_picker/image_picker.framework/image_picker, building for iOS Simulator-i386 but attempting to link with file built for iOS Simulator-x86_64
- NOTE  | [iOS] xcodebuild:  ld: warning: ignoring file Flutter/Flutter.framework/Flutter, missing required architecture i386 in file Flutter/Flutter.framework/Flutter (3 slices)
```

**Comment by jmagman** [comment]
> This seems to have made the warning go away in the actual Xcode project 

Interestingly this was only true for an Objective-C plugin.  With a Swift plugin it fails to compile even though both apps have ONLY_ACTIVE_ARCH=NO for Release:

```
CompileSwift normal i386 (in target 'App' from project 'App')
    cd /var/folders/mv/qlhc4vsj6tqct166rw3zwmth00mfq2/T/CocoaPods-Lint-20191001-97932-c24o1c-test_swift_plugin
...
/var/folders/mv/qlhc4vsj6tqct166rw3zwmth00mfq2/T/CocoaPods-Lint-20191001-97932-c24o1c-test_swift_plugin/App/main.swift:1:8: error: could not find module 'test_swift_plugin' for target 'i386-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64
import test_swift_plugin
```

**Comment by amreniouinnovent** [comment]
Same issue

**Comment by deremakif** [comment]
same issue
