### ISSUE TITLE
https://cdn.cocoapods.org/`: 503 "Forwarding failure"

### ISSUE THREAD

**Issue by Lius1104** [CocoaPods/CocoaPods#9213]
# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: 503 "Forwarding failure"

### Stack

```
   CocoaPods : 1.8.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/lius/.rvm/rubies/ruby-2.6.0/lib
Repositories : 
```

### Installation Source

```
Executable Path: /Users/lius/.rvm/rubies/ruby-2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  pod 'AFNetworking'

  target 'TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestUITests' do
    # Pods for testing
  end

end
```

**Comment by dnkoutso** [comment]
Can you run `pod repo list`? Seems like the master specs repo is added as a CDN repo.

**Comment by Lius1104** [comment]
@dnkoutso 
when I run 'pod repo list' , I get the ‘0 repos’

**Comment by dnkoutso** [comment]
@Lius1104 I will need a sample app here or clear steps to reproduce. It is very weird why `https://github.com/CocoaPods/Specs.git` is being attempted to added as a CDN repo.

**Comment by Lius1104** [comment]
@dnkoutso I'm so sorry, I gave you the wrong result. In fact, the result is [!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: 503 "Forwarding failure".
But, today I try `pod install` again, I get the result is :
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
As for sample app，I just create a sample test demo, use `pod init` to create podfile, and run `pod install`

**Comment by dnkoutso** [comment]
Looks like this invocation is failing:
```ruby
     def cdn_url?(url)
        url =~ %r{^https:\/\/} &&
          REST.head(url + '/all_pods.txt').ok?
      rescue => e
        raise Informative, "Couldn't determine repo type for URL: `#{url}`: #{e}"
      end
```

Seems like a server side issue...you can workaround it by using the `git` repository of CocoaPods.

**Comment by H-Ghadirian** [comment]
I have the same issue
