### ISSUE TITLE
Getting dyld: Library not loaded when running for Catalyst with Xcode 11 on Catalina

### ISSUE THREAD

**Issue by ahmedk92** [CocoaPods/CocoaPods#9227]
# Report

## What did you do?

Run the project on Mac (Catalyst).

## What did you expect to happen?

Run. 

## What happened instead?

Crashes.

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.15 (19A583)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0
Ruby lib dir : /usr/local/Cellar/ruby/2.5.1/lib
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
This is insufficient information for us to diagnose this issue. Please upload a sample app and the exact steps to reproduce.

We are getting plenty of issues that remain open without any follow ups so I am going to preemptively close this one until a sample app and steps to reproduce are uploaded, then I _will_ re-open it.

**Comment by ahmedk92** [comment]
I added `$(inherited)` to Runpath search paths in the main target and it worked!
