### ISSUE TITLE
Repo error with cordova: "The CocoaPods repo has not been synced yet"

### ISSUE THREAD

**Issue by distinctdan** [CocoaPods/CocoaPods#9228]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Ran `cordova plugin add cordova-plugin-firebasex`

## What happened instead?
The install failed with the error: 

`Failed to install 'cordova-plugin-firebasex': undefined`
`CordovaError: Promise rejected with non-error: 'The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.'
`

I then tried running `pod setup`, which did nothing, then `pod install` in my ios project directory, which installed 0 dependencies.

Running `pod repo update` errors also: `Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/MyUsername/.cocoapods/repos/Spec_Lock`

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.1 (11A1027)
         Git : git version 2.9.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '9.0'

target 'Orbus' do
	project 'Orbus.xcodeproj'

end
```

**Comment by dnkoutso** [comment]
You are hitting multiple issues. The first is a bug in Cordova and assumes CocoaPods works with the master specs repo. Since 1.8.x the master specs repo is not required.

The second issue is https://github.com/CocoaPods/CocoaPods/issues/9216.

**Comment by dnkoutso** [comment]
You are better off filing this issue with Cordova cocoapods plugin.

**Comment by dnkoutso** [comment]
Closing as the `Spec_Lock` issue is already filed and known issue. The other issue as I said it is better to file to them.

**Comment by dnkoutso** [comment]
It seems their plugin assumes the master specs repo is there but as I said CocoaPods no longer clones the master specs repo by default.

**Comment by distinctdan** [comment]
Ok, thanks for the info. I was able to work around the issues by downgrading to 1.7.5, syncing the repo, then upgrading to 1.8.3.

**Comment by dnkoutso** [comment]
thank you!
