### ISSUE TITLE
Set APPLICATION_EXTENSION_API_ONLY to Pods when set in the project's .xcconfig

### ISSUE THREAD

**Issue by juanjonol** [CocoaPods/CocoaPods#9233]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

Since pull request #4321, the `APPLICATION_EXTENSION_API_ONLY` build setting is automatically applied to Pods if it's set in the user target. But this doesn't work if `APPLICATION_EXTENSION_API_ONLY` is set in an Config file (.xcconfig).

This also applies to the `BUILD_LIBRARY_FOR_DISTRIBUTION` Build Setting if #9232 is fixed.

## What did you do?

1. Create a new project.
2. Create an .xcconfig file and make the project use it.
3. Add `APPLICATION_EXTENSION_API_ONLY = YES` to the .xcconfig.
4. Use `pod install` to install any pod.

## What did you expect to happen?

CocoaPods should set `APPLICATION_EXTENSION_API_ONLY` to `YES` in all Pods, like it does if the setting is applied directly to the project.

## What happened instead?

Pods don't have the `APPLICATION_EXTENSION_API_ONLY` set to `YES`, so there's a `Linking against a dylib which is not safe for use in application extensions` warning for each Pod.

## Workaround

Use a `post_install` hook to set `APPLICATION_EXTENSION_API_ONLY ` to `YES` in all pods.

**Comment by dnkoutso** [comment]
This PR will allow for this to be fixed https://github.com/CocoaPods/Xcodeproj/pull/722
