### ISSUE TITLE
Installation configuration error.

### ISSUE THREAD

**Issue by MichaelTiernan** [CocoaPods/CocoaPods#9236]
# Report
I tried to see if this was a new issue but couldn't find any other reports.

I have to ask for forgiveness, I'd like to have gone through the process of created a perfect bug report but CocoaPods isn't a project I spend a lot of time in and so I've tried to provide proper feedback without wasting everyone's time.

Good luck and thank you to everyone for your hard work.

## What did you do?
Executed the command `sudo gem install cocoapods`

## What did you expect to happen?
Install "product" properly.<br>("Properly" is the appropriate word but it sounds more harsh than I intend. Sorry about that.)

## What happened instead?
The product files located in `/Library/Ruby/` are installed using the ***user's umask*** and not reset (as they should be) for use by non-root users. In this instance, my umask is 0077 and the files were all installed owned by `root` with permissions locking out all other users as the mode flags were xx00 across the board. (No, this is *NOT* for me to fix, this is the responsibility of the software installation process and should be done independent of the user's specific settings.)

The executables in `/usr/local/bin` were also installed as 700 instead of 755.
~~~sh
-rwx------  1 root  admin  538 Oct  9 12:24 /usr/local/bin/fuzzy_match
-rwx------  1 root  admin  535 Oct  9 12:24 /usr/local/bin/httpclient
-rwx------  1 root  admin  526 Oct  9 12:24 /usr/local/bin/pod
-rwx------  1 root  admin  534 Oct  9 12:24 /usr/local/bin/sandbox-pod
-rwx------  1 root  admin  532 Oct  9 12:24 /usr/local/bin/xcodeproj
~~~

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G8037)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :osx, '10.8'
inhibit_all_warnings!

target 'cocoadialog' do
  pod 'GRMustache', '~> 7.3.2'
  pod 'Masonry', '~> 1.1.0'
  pod 'TSMarkdownParser', '~> 2.1.3'
end

class ::Pod::Generator::Acknowledgements
  def header_text
    "\nThe following third party libraries are so awesome, you'll just have to check them out to see how badass they are! Thank you for coding amazing tools and letting this project use them!\n\n\n" +
    "## CocoaPods\n\n[CocoaPods](https://cocoapods.org) is a dependency manager for Swift and Objective-C Cocoa projects.\n\nThe MIT License (MIT): \n\nhttps://github.com/CocoaPods/CocoaPods/blob/master/LICENSE\n\n"
  end
  def footnote_text
    ""
  end
end

post_install do | installer |
  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['GCC_PREFIX_HEADER'] = "$(SDKROOT)/System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h"
#    end

    # Only match Pod targets, not Pods used inside the targets.
    next if !target.name.match(/^Pods-/)

    root = Pathname.new(File.dirname(__FILE__))

    # Generated file.
    dir = installer.sandbox.target_support_files_root.relative_path_from(root).to_s + "/" + target.name
    filename = target.name + "-acknowledgements.markdown"
    file = dir + "/" + filename

    # New file.
    newDir = "Resources"
    newFilename = "Acknowledgements.md"
    newFile = newDir + "/" + newFilename

    # Check if generated file exists and then copy it.
    puts "    - Checking if \"" + target.name + "\" has \"" + file + "\"..."
    if (File.file?(file))
        puts "      - Copying \"" + filename + "\" -> \"" + newFile + "\"..."
        FileUtils.cp_r(file, newFile, :remove_destination => true)
    end
  end
end
```

## Project that demonstrates the issue
N/A

**Comment by dnkoutso** [comment]
Thanks for the report, however I fail to see how this is related to CocoaPods itself and rather a RubyGems configuration issue and perhaps a specific configuration issue with your machine.

**Comment by dnkoutso** [comment]
I recommend filing an issue here instead https://github.com/rubygems/rubygems

**Comment by MichaelTiernan** [comment]
Good point.
Damn. Shows you what happens when you try to do too many things at once. :(
Thanks.
