### ISSUE TITLE
generate_multiple_pod_projects post_install error

### ISSUE THREAD

**Issue by Q14** [CocoaPods/CocoaPods#9245]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Run `pod install`

## What did you expect to happen?

ℹpod install success 

## What happened instead?

ℹ 
```
install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|

             #只需要主项目里的该设置为YES就可以了，POD不需要，以防多次拷贝Swift standard libraries，见https://developer.apple.com/library/content/qa/qa1881/_index.html
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
            config.build_settings['SWIFT_SWIFT3_OBJC_INFERENCE'] = 'Default'

             #给POD的Target增加一个宏IS_USER，表示当前APP是用户版(针对的是OC代码)
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','IS_USER=1']
             #pod install之后需要指定Swift Other Flag中的变量，用于#if判断
            if config.name == 'Debug'
                config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D DEBUG -D IS_USER'
                elsif config.name == 'AppStore'
                config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D APPSTORE -D IS_USER'
                elsif config.name == 'Release'
                config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D RELEASE -D IS_USER'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
                elsif config.name == 'UnitTest'
                # 额外的，针对UnitTest，通过使用NS_BLOCK_ASSERTIONS禁用OC的NSAssert()，通过使用与-assert-config Release禁用Swift的assert()
                config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D UnitTest -D IS_USER -assert-config Release'
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NS_BLOCK_ASSERTIONS'
            end
        end
    end
end
```
## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`
``
   CocoaPods : 1.7.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c5b20063d656f3430a7bcb653a49dddace030d84
               wanmeizhensuo-gmspecs - git@git.wanmeizhensuo.com:gengmeiios/GMSpecs.git @ b4d2ba41a484f27416cb33b648223d1d4cdf866a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```
## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by Q14** [comment]
how to modify   post_install

**Comment by dnkoutso** [comment]
Sorry this is currently an insufficient report. Please fill in all steps and provide a sample app with steps to reproduce.

Going to preemptively close and I will re-open if a sample app or a full clear report is filed.
