### ISSUE TITLE
homepage is required, but must be public

### ISSUE THREAD

**Issue by typeoneerror** [CocoaPods/CocoaPods#9247]
* [x] 🌈 I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod spec lint

## What did you expect to happen?

I expect to be able to supply a homepage that is private because this is a private podspec.

## What happened instead?

```
- WARN  | url: The URL (https://github.com/PrecisionNutrition/capacitor-device-model) is not reachable.
```

**Comment by dnkoutso** [comment]
Hmmm not sure what to make of that as that decision was made a long time ago. We could limit that warning only if you try to publish to the master specs repo.

**Comment by dnkoutso** [comment]
Workaround is to use `--allow-warnings`
