### ISSUE TITLE
[!] Cannot perform full-text search in repo cocoapods

### ISSUE THREAD

**Issue by HSFAqi** [CocoaPods/CocoaPods#9253]
when I "pod search xxx"
error:
[!] Cannot perform full-text search in repo cocoapods because it's missing Algolia config

I donot konw how to do
help me!

**Comment by dnkoutso** [comment]
Can you paste `pod repo list` please?

**Comment by HSFAqi** [comment]
$ pod repo list

cocoapods
- Type: CDN
- URL:  https://github.com/CocoaPods/Old-Specs/
- Path: /Users/hsf/.cocoapods/repos/cocoapods

master
- Type: git (master)
- URL:  https://git.coding.net/CocoaPods/Specs.git
- Path: /Users/hsf/.cocoapods/repos/master

trunk
- Type: CDN
- URL:  https://cdn.cocoapods.org/
- Path: /Users/hsf/.cocoapods/repos/trunk

3 repos

**Comment by HSFAqi** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    When I “pod repo list “cocoapods- Type: CDN- URL:  https://github.com/CocoaPods/Old-Specs/- Path: /Users/hsf/.cocoapods/repos/cocoapodsmaster- Type: git (master)- URL:  https://git.coding.net/CocoaPods/Specs.git- Path: /Users/hsf/.cocoapods/repos/mastertrunk- Type: CDN- URL:  https://cdn.cocoapods.org/- Path: /Users/hsf/.cocoapods/repos/trunk3 repos
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                huangsf_ios
                            
                    
                        
                            
                                    huangsf_ios@sina.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 10/14/2019 21:24，D. Koutsogiorgas<notifications@github.com> wrote： 


Can you paste pod repo list please?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by baiwulong** [comment]
`pod repo remove cocoapods` . and try again.
it works for me,thanks @dnkoutso
