### ISSUE TITLE
Pod update failed. Execution expired.

### ISSUE THREAD

**Issue by andreyoshev** [CocoaPods/CocoaPods#9254]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod update`

## What did you expect to happen?

Updated pods.

## What happened instead?

pod update
Update all pods
Updating local specs repositories
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: execution expired

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15 (19A583)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/andreyoshev/.rvm/rubies/ruby-2.6.5/lib
Repositories : audiokit - git - https://github.com/AudioKit/Specs.git @ 5550f600a0d8e30661995178d28a0b37ad0624bd
               master - git - https://github.com/CocoaPods/Specs.git @ 2ecdc6e245a349601581408bc53418d4bbc7bf87
```

### Installation Source

```
Executable Path: /Users/andreyoshev/.rvm/gems/ruby-2.6.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
inhibit_all_warnings!
use_frameworks!

def di
    pod 'Typhoon'
end

def data
    pod 'UICKeyChainStore', '~> 2.1'
    pod 'FastEasyMapping', '~> 1.2'
    pod 'Realm'
end

def network
    pod 'AFNetworking', '~> 3.1'
    pod 'SDWebImage', '~> 4.0'
end

def other
    pod 'Fabric'
    pod 'Crashlytics', '~>  3.9'
    pod 'Amplitude-iOS', '~> 4.0.1'
    pod 'YandexMobileMetrica/Dynamic'
    pod 'AppsFlyerFramework'
    pod 'IAPHelper'
    pod 'APLViperStack', '~> 0.1.2'
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
end

def ui
    pod 'Masonry'
    pod 'lottie-ios', '~> 2.5'
    pod 'Bluuur'
    pod 'JVFloatLabeledTextField'
    pod 'Shimmer'
    pod 'SVProgressHUD'
end

def social
    pod 'VK-ios-sdk'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
end

target 'Watch Extension' do
    platform :watchos, '2.0'
    data
end

target 'OneSignalNotificationServiceExtension' do
    platform :ios, '11.0'
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
end

target 'Learnwords' do
    platform :ios, '11.0'
    di
    network
    data
    ui
    other
    social
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '4.0'
            config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "org.cocoapods.${PRODUCT_NAME:rfc1034identifier}.${PLATFORM_NAME}"
        end
    end
end
```

**Comment by dnkoutso** [comment]
Seems like your CDN repo cannot be updated can you run with `--verbose` and paste the output here?

**Comment by andreyoshev** [comment]
@dnkoutso 

[!] CDN: trunk Repo update failed - 36 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.1.7/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.1.8/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.1.9/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.0/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.1/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.2/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.3/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.4/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.5/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.6/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.7/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.2.8/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.3.0/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.3.1/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.3.2/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.3.3/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.3.4/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.4.1/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.4.2/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.4.3/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.4.4/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.4.5/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.4.7/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.4.8/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.4.9/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.5.0/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.5.1/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/3.6.0/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/4.0.0/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/4.0.1/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/4.0.2/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/4.0.3/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/4.0.4/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/4.0.5/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/4.0.7/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/1/3/a/Typhoon/4.0.8/Typhoon.podspec.json, error: Failed to open TCP connection to cdn.cocoapods.org:443 (No route to host - connect(2) for "cdn.cocoapods.org" port 443)

**Comment by dnkoutso** [comment]
Seems like a network issue with your configuration that is preventing you from communicating to `cdn.cocoapods.org`. Recommend falling back to master git repo by adding:
```ruby
source 'https://github.com/CocoaPods/Specs.git'
```

Going to close for now as there is a workaround and that does not seem something CocoaPods can fix currently.

**Comment by H-Ghadirian** [comment]
Adding `source ` not helped me.
I still have the same issue.

**Comment by mahesh-dhapa** [comment]
> Adding `source ` not helped me.
> I still have the same issue.

@H-Ghadirian i had same issue. I was using version 1.8.4 cocoapods.
Updating version 1.9.1 solved my provlem.
