### ISSUE TITLE
Failure to install cocoapods on MacOS 10.15 Catalina

### ISSUE THREAD

**Issue by benlue1992** [CocoaPods/CocoaPods#9255]
MacOS version 10.15

$ sudo gem update --system

$ sudo gem install -n /usr/local/bin cocoapods

$ pod setup

But executing `pod setup'did not require any response, nor did it prompt any errors.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
pod --version    
1.8.3

gem -v
3.0.6

I don't know what the problem is.

**Comment by dnkoutso** [comment]
Pod setup no longer performs anything in 1.8.x. we kept it because we didnt want to break existing setups.

We added a message for 1.9.x.

Closing as behaves correctly.

**Comment by benlue1992** [comment]
oh thinks
