### ISSUE TITLE
pod install command throw error

### ISSUE THREAD

**Issue by perceptionfoundry** [CocoaPods/CocoaPods#9262]
Cocoapods Version 1.8.3
Xcode 11.1
MacOS 10.15

I created a new Xcode project using storyboard, open terminal, pod init, open pod file (screenshot attached below) and add one dependency, save and run command "pod install".

Terminal is showing trackback error
" /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for #<String:0x00007fabaebb72c0> (NoMethodError)"

<img width="1552" alt="Screenshot 2019-10-16 at 6 26 23 PM" src="https://user-images.githubusercontent.com/31928839/66931410-78b94080-f04f-11e9-877f-793649e830bc.png">

**Comment by dnkoutso** [comment]
try `gem install activesupport`.

Either way I cannot reproduce this locally and we will need a sample app if possible that shows the error.

**Comment by dnkoutso** [comment]
Also can you paste `pod repo list`?

**Comment by perceptionfoundry** [comment]
tried both commands, issue still there
<img width="1680" alt="Screenshot 2019-10-16 at 8 31 48 PM" src="https://user-images.githubusercontent.com/31928839/66934530-0eef6580-f054-11e9-967b-bdd13ad983aa.png">

**Comment by perceptionfoundry** [comment]
Traceback (most recent call last):
	34: from /usr/local/bin/pod:23:in `<main>'
	33: from /usr/local/bin/pod:23:in `load'
	32: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
	31: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
	30: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	29: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command/install.rb:52:in `run'
	28: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:156:in `install!'
	27: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
	26: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface.rb:64:in `section'
	25: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
	24: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer.rb:410:in `analyze'
	23: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
	22: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
	21: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface.rb:64:in `section'
	20: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:985:in `block in resolve_dependencies'
	19: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:177:in `sources'
	18: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:177:in `map'
	17: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
	16: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:19:in `find_or_create_source_with_url'
	15: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:386:in `source_with_url'
	14: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:58:in `all'
	13: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:24:in `aggregate'
	12: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `aggregate_with_repos'
	11: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `map'
	10: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `block in aggregate_with_repos'
	 9: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:315:in `source_from_path'
	 8: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:308:in `block in source_from_path'
	 7: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:308:in `new'
	 6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:29:in `initialize'
	 5: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source.rb:31:in `initialize'
	 4: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:55:in `refresh_metadata'
	 3: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source.rb:434:in `refresh_metadata'
	 2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:28:in `from_file'
	 1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:28:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for #<String:0x00007fdc58fb58d8> (NoMethodError)
	25: from /usr/local/bin/pod:23:in `<main>'
	24: from /usr/local/bin/pod:23:in `load'
	23: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
	22: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
	21: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	19: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	18: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:66:in `report_error'
	17: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface/error_report.rb:24:in `report'
	16: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface/error_report.rb:77:in `stack'
	15: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface/error_report.rb:173:in `repo_information'
	14: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:58:in `all'
	13: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:24:in `aggregate'
	12: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `aggregate_with_repos'
	11: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `map'
	10: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `block in aggregate_with_repos'
	 9: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:315:in `source_from_path'
	 8: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:308:in `block in source_from_path'
	 7: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:308:in `new'
	 6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:29:in `initialize'
	 5: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source.rb:31:in `initialize'
	 4: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:55:in `refresh_metadata'
	 3: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source.rb:434:in `refresh_metadata'
	 2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:28:in `from_file'
	 1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:28:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for #<String:0x00007fdc58fc7290> (NoMethodError)
shahrukh@Perception-Foundry-MacBook-Pro testAPP % od repo list
od: repo: No such file or directory
od: list: No such file or directory
od: list: Bad file descriptor
shahrukh@Perception-Foundry-MacBook-Pro testAPP % pod repo list
Traceback (most recent call last):
	20: from /usr/local/bin/pod:23:in `<main>'
	19: from /usr/local/bin/pod:23:in `load'
	18: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
	17: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
	16: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	15: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command/repo/list.rb:33:in `run'
	14: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:58:in `all'
	13: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:24:in `aggregate'
	12: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `aggregate_with_repos'
	11: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `map'
	10: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `block in aggregate_with_repos'
	 9: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:315:in `source_from_path'
	 8: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:308:in `block in source_from_path'
	 7: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:308:in `new'
	 6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:29:in `initialize'
	 5: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source.rb:31:in `initialize'
	 4: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:55:in `refresh_metadata'
	 3: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source.rb:434:in `refresh_metadata'
	 2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:28:in `from_file'
	 1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:28:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for #<String:0x00007fe45316abe0> (NoMethodError)
	25: from /usr/local/bin/pod:23:in `<main>'
	24: from /usr/local/bin/pod:23:in `load'
	23: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
	22: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
	21: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run'
	19: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception'
	18: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:66:in `report_error'
	17: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface/error_report.rb:24:in `report'
	16: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface/error_report.rb:77:in `stack'
	15: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.3/lib/cocoapods/user_interface/error_report.rb:173:in `repo_information'
	14: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:58:in `all'
	13: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:24:in `aggregate'
	12: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `aggregate_with_repos'
	11: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `map'
	10: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:324:in `block in aggregate_with_repos'
	 9: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:315:in `source_from_path'
	 8: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:308:in `block in source_from_path'
	 7: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/manager.rb:308:in `new'
	 6: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:29:in `initialize'
	 5: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source.rb:31:in `initialize'
	 4: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/cdn_source.rb:55:in `refresh_metadata'
	 3: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source.rb:434:in `refresh_metadata'
	 2: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:28:in `from_file'
	 1: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:28:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.3/lib/cocoapods-core/source/metadata.rb:15:in `initialize': undefined method `with_indifferent_access' for #<String:0x00007fe453173628> (NoMethodError)

**Comment by dnkoutso** [comment]
Can you paste the output of `ls ~/.cocoapods/repos`?

**Comment by perceptionfoundry** [comment]
output :
<img width="1680" alt="Screenshot 2019-10-16 at 8 44 21 PM" src="https://user-images.githubusercontent.com/31928839/66935627-c042cb00-f055-11e9-9e7b-d3f81e7be891.png">

**Comment by dnkoutso** [comment]
can you `rm -rf ~/.cocoapods/repos` and try the command again?

**Comment by perceptionfoundry** [comment]
thanks issue resolve :-)

**Comment by dnkoutso** [comment]
Wish I could find out what was truly wrong here....
