### ISSUE TITLE
`use_modular_headers!` can cause "modulemap not found" compilation error

### ISSUE THREAD

**Issue by jmagman** [CocoaPods/CocoaPods#9266]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Add `use_modular_headers!` in conjunction with pod BoringSSL-GRPC (I noticed this working with Firebase).
```ruby
target 'UseModularHeadersTest' do
  use_modular_headers!
  pod 'BoringSSL-GRPC'
end
```

## What did you expect to happen?

No compilation errors.

## What happened instead?

Error:
'/<>/Pods/Headers/Private/openssl_grpc/BoringSSL-GRPC.modulemap' not found

That file does not exist.

Everything works if `use_frameworks!` is used.

The real modulemap is here:
Pods/Target Support Files/BoringSSL-GRPC/BoringSSL-GRPC.modulemap
```
  module openssl {
    umbrella header "umbrella.h"
    textual header "arm_arch.h"
    export *
    module * { export * }
  }
```

BoringSSL-GRPC is specifying the modulemap explicitly:
https://github.com/grpc/grpc/blob/ead48a64a6df7c6bb3821af81692a4bf9470de5c/templates/src/objective-c/BoringSSL-GRPC.podspec.template#L114

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G87)
       Xcode : 11.2 (11B41)
         Git : git version 2.20.1.415.g653613c723-goog
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.4.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

## Project that demonstrates the issue

Create new Xcode project (Obj-C or Swift reproduce)
`pod init`
Remove `use_frameworks!` and add this to the target:
```
use_modular_headers!
pod 'BoringSSL-GRPC'
```
Build workspace in Xcode.

**Comment by dnkoutso** [comment]
custom module map files for static libraries is not supported see this https://github.com/CocoaPods/CocoaPods/issues/9023

**Comment by dnkoutso** [comment]
@jmagman if you feel #9023 is what you want (which it started with a slightly different request) then we can close this as a dup.

**Comment by jmagman** [comment]
Sounds good, thanks!

**Comment by eusouoviana** [comment]
This is still happening
