### ISSUE TITLE
pod lib lint does not support multiple version of Swift in dependencies

### ISSUE THREAD

**Issue by facundor** [CocoaPods/CocoaPods#9267]
# Report

Linting / release a library pod ExampleA in Swift 5 and having dependencies with Swift 4.2 is working properly. When I use a Pod ExampleB with dependecies to ExampleA (Swift 5) and his dependencies in 4.2 (Alamofire,etc), I have an error in the linting process. This not work in the release of pod B also. There is a way to set linting with Swift 5.0 some dependencies and with 4.2 others, in the same linting process? The same with release process (pod repo push)? There is a way to avoid lint dependencies in the linting and release process? 

```
 
ExampleB (Swift 5) -> ExampleA (Swift 5) -> Alamofire (Swift 4.2)
				        -> Split.io (Swift 4.2)
				        -> mores dependencies with Swift 4.2

```
 
## What did you do?

Run `pod lib lint --sources=https://myrepo.git,https://github.com/CocoaPods/Specs.git --verbose --allow-warnings --swift-version=4.2`

Crash when linting dependency ExampleA (because need Swift 5)

Run `pod lib lint --sources=https://myrepo.git,https://github.com/CocoaPods/Specs.git --verbose --allow-warnings --swift-version=5.0`

Crash when linting dependency Alamofire and others (because need Swift 4.2)

## What did you expect to happen?

I need linting and release my modules in Swift 5 (my code), and with Swift 4.2 some libraries like Alamofire and others external libs.

## What happened instead?

When I have a relationship in my pods, i need lint this dependencies in Swift 5 and the rest in Swift 4.2

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A536g)
       Xcode : 10.3 (10G8)
         Git : git version 2.19.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : amplitude - https://github.com/amplitude/Amplitude-iOS.git @ 972583722ce4c471ecd534974d0d7872ae6bd40c
               master - https://github.com/CocoaPods/Specs.git @ 1a3a4bcf589c957c92b291c384731e059123c3e3
               naranja-specs - git@gitlab.naranja.dev:core-mobile/ios/specs.git @ e65a6811fc7b850d47b1f6c59186524c2e4d8009
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
We intentionally do not allow this to happen unless the dependencies themselves also declare their `swift_versions` DSL.

Setting the Swift version on a dependency is not something we want because there is no guarantee when someone consumes your pod that they will use the same version of Swift for the dependency as you decided when you ran `lint`.

The best thing to do is here reach out to the pod authors and ask them to specify `swift_versions` DSL and explicitly define the versions of Swift they support.

**Comment by dnkoutso** [comment]
The `--swift-version` param is only meant to affect your pod and _only_ has an effect on dependencies if they specify a list of supported Swift versions and they include the version you specified.

**Comment by facundor** [comment]
Hi @dnkoutso 
Thanks for reply so quickly man 👍 

In resume, i can't use in a pod with Swift 5 code, mixed dependencies of pods that:

* only support Swift 5 
* others depedencies that only support Swift 4.2 at maximun. 

There is no way to mix dependecies with diferente Swift version, in a pod with Swif 5 code. That is righit?

I supose we will have to wait until all the third parties dependencies finish migration to Swift 5. Then we will use Swift 5 as a common base in our modules and third parties. And linter/release will run in Swift 5 and all be alright

Alamofire do not have a final release in Swift 5 today.

Thanks again,

Cheers

**Comment by facundor** [comment]
@dnkoutso i resolved my problem.

We use in our pods podspec
```
s.swift_versions = ['5.0'] 
```

And we have only one problem dependency to URITemplate without swift_version or swift_versions specified in podspec. I release one internal version of URITemplate based on 2.0.3 version, it contains swift_version = "4.0" in podspec file.

I deleted the --swift-version parameter from linting and release process.

Our  app and all modules lint and compile without errors. Thanks a lot

Cheers

**Comment by dnkoutso** [comment]
Btw, that pod _does_ specify `swift_versions` in its 3.x version, see https://github.com/kylef/URITemplate.swift/blob/master/URITemplate.podspec#L16
