### ISSUE TITLE
xcrun: error: unable to find utility "pngcrush", not a developer tool or in PATH

### ISSUE THREAD

**Issue by boriskushnir1** [CocoaPods/CocoaPods#9268]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I use CocoaPods 1.8.3 and Xcode 11.1.
I distributed my compiled library (file: myFramework.a) to Cocodapods. The library should be used and, of course, tested with one 3rd party framework. Also there's a [CP] Copy Pod Resources build phase inside that copies .png files .
JFYI, the local build was successful and I succeed to use the library inside my test project. 

 Podspec file:

    Pod::Spec.new do |s|

	    s.name         = "MyLibrary"
	    s.version      = "5"
	    s.summary      = "My Library"

	    s.homepage     = "http://mywebsite.com"
            s.license      = { :type => 'LGPLv3', :file => 'LICENSE' }

	    s.author       = { "MyLibrary" => "myemail@myemail.com"}

	    s.platform     = :ios
	    s.ios.deployment_target = '10.0'

	     s.source       = { :http => "https://mywebsite.com/libraries/MyLibrary_5.zip"}

	     s.dependency 'mopub-ios-sdk'
	     s.source_files   = "include/MyLibrary/*.{h}"
	     s.vendored_libraries = "libMyLibrary.a"
     end

## What did you expect to happen?

Successful pod verification and pod distribution.

## What happened instead?

Pod verification fails. 
When I ran 'pod lint --verbose' I saw several same errors that are relevant to .png files:

    CopyPNGFile /Users/home/Library/Developer/Xcode/DerivedData/App-hkwptbwonkymrgbqemlqdrmaijfq/Build/Products/Release-iphonesimulator/mopub-ios-sdk/MoPub.framework/MPMutedBtn@2x.png /var/folders/cq/p7hnpp8j5l161n8876f384p00000gn/T/CocoaPods-Lint-20191017-70959-xil1bj-MyLibrary/Pods/mopub-ios-sdk/MoPubSDK/Resources/MPMutedBtn@2x.png (in target 'mopub-ios-sdk' from project 'Pods')
            cd /var/folders/cq/p7hnpp8j5l161n8876f384p00000gn/T/CocoaPods-Lint-20191017-70959-xil1bj-MyLibrary/Pods
            export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
            export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk
            export TOOLCHAINS=""" "
        /Applications/Xcode.app/Contents/Developer/usr/bin/copypng -compress -strip-PNG-text /var/folders/cq/p7hnpp8j5l161n8876f384p00000gn/T/CocoaPods-Lint-20191017-70959-xil1bj-MyLibrary/Pods/mopub-ios-sdk/MoPubSDK/Resources/MPMutedBtn@2x.png /Users/home/Library/Developer/Xcode/DerivedData/App-hkwptbwonkymrgbqemlqdrmaijfq/Build/Products/Release-iphonesimulator/mopub-ios-sdk/MoPub.framework/MPMutedBtn@2x.png
    sh: line 1: 71391 Abort trap: 6           /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk -find pngcrush 2> /dev/null
        xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk -find pngcrush 2> /dev/null' failed with exit code 34304: (null) (errno=No such file or directory)
        xcrun: error: unable to find utility "pngcrush", not a developer tool or in PATH

      Testing with `xcodebuild`.
     -> YouAppiMoPubAdapter (4.4.5)
         - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
         - NOTE  | xcodebuild:  note: Using new build system
         - NOTE  | [iOS] xcodebuild:  note: Planning build
         - NOTE  | [iOS] xcodebuild:  note: Constructing build description
         - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'mopub-ios-sdk' from project 'Pods')
         - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
         - NOTE  | xcodebuild:  xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk -find pngcrush 2> /dev/null' failed with exit code 34304: (null) (errno=No such file or directory)
         - NOTE  | xcodebuild:  xcrun: error: unable to find utility "pngcrush", not a developer tool or in PATH

     Analyzed 1 podspec.

     [!] The spec did not pass validation, due to 1 error.

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A583)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 54d52283fd2fc9ab25faa3e2366940165a8e1ae0
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Some investigation notes

It looks like 'pngcrush' shouldn't be in this path at all: 
        
    Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk

I see it here:

    Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush

Is there any idea why CocoaPods is trying to find it in another destination that is different from default for Xcode 11?

**Comment by boriskushnir1** [comment]
> CocoaPods does not run `pngcrush` manually if I remember correctly. This seems to be a misconfigured setup on your system perhaps?

Sorry for stupid question maybe... But how that could be relevant to my system setup? 
As long as I understand, when I call 'pod lint', the new empty Xcode workspace is created on some remote machine, then all the frameworks/libraries (including mine) that I mentioned in podspec are integrated and the workspace is built. 
Or do you mean that everything is built on my machine locally?

**Comment by dnkoutso** [comment]
CocoaPods does not directly execute `pngcrush`. The error is this:
```
    xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk -find pngcrush 2> /dev/null' failed with exit code 34304: (null) (errno=No such file or directory)
    xcrun: error: unable to find utility "pngcrush", not a developer tool or i
```

Something is off in the setup that Xcode is unable to find this utility. Try invoking it manually from the command line does it work?

**Comment by boriskushnir1** [comment]
> CocoaPods does not directly execute `pngcrush`. The error is this:
> 
> ```
>     xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk -find pngcrush 2> /dev/null' failed with exit code 34304: (null) (errno=No such file or directory)
>     xcrun: error: unable to find utility "pngcrush", not a developer tool or i
> ```
> 
> Something is off in the setup that Xcode is unable to find this utility. Try invoking it manually from the command line does it work?

No, it doesn't.
Because actually pngcrush is located by default in 


        Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/pngcrush

I've never had this problem before Xcode 11. And, as I have mentioned before, it's strange that if I create empty project, put my frameworks inside and build the project from Xcode, not from command line, it works fine. It fails only when I run 'pod lint'.

**Comment by boriskushnir1** [comment]
> CocoaPods does not directly execute `pngcrush`. The error is this:
> 
> ```
>     xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.1.sdk -find pngcrush 2> /dev/null' failed with exit code 34304: (null) (errno=No such file or directory)
>     xcrun: error: unable to find utility "pngcrush", not a developer tool or i
> ```
> 
> Something is off in the setup that Xcode is unable to find this utility. Try invoking it manually from the command line does it work?

Btw, I don't think that this is relevant to Xcode setup, because I tried to build it on Bitrise and got the same error.

**Comment by boriskushnir1** [comment]
@dnkoutso , thank you!
As long as I'm coming to the deadline, I used --skip-import-validation as a workaround for this at the moment. But I'll try to provide you some demo in the nearest time, because it's really interesting for me to understand what the issue is.
