### ISSUE TITLE
Update CocoaPods version 1.3.1 to 1.8.4,can not build static framework,

### ISSUE THREAD

**Issue by cjlcooper** [CocoaPods/CocoaPods#9272]
# Report

## What did you do?

We update CocoaPods version 1.3.1 to 1.8.3,after update successfully,we can not build a normal static framework in our project,but it is ok in version 1.3.1 or 1.5.3.

## What did you expect to happen?

Create a normal static framework,same in version 1.3.1 or 1.5.3.

## What happened instead?

When we use CocoaPods (Version 1.8.4),build the framework with command line(xcodebuild --workspace xxx -scheme xxx ....),it is show "build success",but not any file output.
By the way,in version 1.3.1 or 1.5.3,this operation is ok.

## CocoaPods Environment

CocoaPods Version: 1.8.3
Xcode Version: 11.0
Mac OSX Version: 10.14.6

## Project that demonstrates the issue

This is private project,but we believe any simple project could reproduce this problem.

**Comment by Dandre126** [comment]
remove i386

**Comment by dnkoutso** [comment]
There is insufficient information to diagnose/debug the issue. Please upload a sample app.
