### ISSUE TITLE
Running *-resources.sh in parallel

### ISSUE THREAD

**Issue by hhfa008** [CocoaPods/CocoaPods#9276]
# Report

## What did you do?

There are hundred of resources to copy by  *-resources.sh When I run my app with Xcode.
It takes a long time to copy files because this job is doing in serial.

## What did you expect to happen?

change install_resource function into parallel,  such as

file:lib/cocoapods/generator/copy_resources_script.rb

```
install_resource() 
```
to

```
install_resource() {
_install_resource $1 &
}
_install_resource()
```

It will be save a lot of time.

Thanks

**Comment by dnkoutso** [comment]
This could be a good enhancement, we already have this for embed frameworks script doing it with `COCOAPODS_PARALLEL_CODE_SIGN`.

Happy to review PRs!
