### ISSUE TITLE
Not reading .netrc file when declaring podspec source

### ISSUE THREAD

**Issue by kmfreas** [CocoaPods/CocoaPods#9283]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
`pod install`

## What did you expect to happen?
Cocoapods to read my `~/.netrc` file in my home directory and supply basic authentication credentials to requests for the podspec and the source files.

## What happened instead?
Not receiving an `Authorization` header on my backend.
I've read in multiple places this is possible by putting credentials in `~/.netrc`, for example:
https://github.com/CocoaPods/CocoaPods/issues/876
https://github.com/CocoaPods/CocoaPods/issues/5055

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15 (19A603)
       Xcode : 11.1 (11A1027)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 8c7257f6fbe7300b07deab1836a3f1f4e9bffc82
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'ExampleProject PodExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleProject PodExample
  pod 'ExampleProject', podspec: 'http://localhost:3000/files/3.0.0/ExampleProject.podspec'


end
```

## Project that demonstrates the issue
Unfortunately I don't have an example to share. But essentially I'm writing a lambda function that authenticates via basic auth and then returns files from the podspec and source .zip files from s3.

If I run `curl --netrc-optional http://localhost:3000/files/3.0.0/ExampleProject.podspec` it works just fine. However, running `pod install` (with a clean cache) it fails with the below errors:
```
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/podspec_source.rb:22:in `rescue in block in fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/podspec_source.rb:18:in `block in fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/external_sources/podspec_source.rb:11:in `fetch'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:901:in `fetch_external_source'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:880:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:879:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:878:in `fetch_external_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

One thing I've noticed is if I set the pod definition back to `git:` or `source:` I get two requests, one without the authorization header, but the _next_ one will have it after my endpoint responds with the header `'WWW-Authenticate: Basic realm="insert realm"'`. So the issue must be in using the `podspec:` definition. If I replace `podspec:` with `git:` like the below, it works but only for authentication. I'm not storing this as a git repo, so git itself fails after authentication.

`pod 'ExampleProject', git: 'http://localhost:3000/files/3.0.0/ExampleProject.podspec'`

### Conclusion

Is there any way I can supply basic authentication headers while requesting solely a .podspec file? Either through `.netrc` or some other cocoapods configuration I'm completely missing? Thanks for looking at this!

**Comment by dnkoutso** [comment]
Hm uncertain if this is supported currently. Would love someone to dig in and try to help.
