### ISSUE TITLE
Xcode 11 crashes when dependencies change

### ISSUE THREAD

**Issue by joona0825** [CocoaPods/CocoaPods#9289]
* [V] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Modify `Podfile` and run `pod install`
Or run `pod repo update` and if new version of dependency exists, run `pod update`

## What did you expect to happen?

ℹ .xcworkspace file updates and indexing starts without Xcode crashes

## What happened instead?

ℹ Xcode crashed and force closed

## CocoaPods Environment

ℹ 
### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A602)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /usr/local/Cellar/ruby/2.6.4_2/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 515b6617dd5292fb4bb12831916582e2a002a6f5
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mindpro_new' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mindpro_new

  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'RealmSwift'
  pod 'CryptoSwift', '~> 0.15.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Kingfisher'
  pod 'Alamofire', '~> 4.7.3'
  pod 'TwilioVoice', '~> 2.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Cosmos', '~> 16.0'
  pod 'RemoteMonster'
  pod 'MessageInputBar'
  pod 'MessageKit', :path=>'./mindpro_new/MessageKit'
  pod 'SpreadsheetView'
  pod 'Logging', '~> 1.1.1'
  pod 'ObjectMapper', '~> 3.4'

end
```

## Project that demonstrates the issue

ℹ  Every time I modify Podfile and run `pod install`, Xcode crashes. It seems Xcode crashes when CocoaPods is touching .xcworkspace or Pods.xcodeproj file while Xcode is running. Even updating dependencies causes crash of Xcode.

**Comment by dnkoutso** [comment]
There isn't enough information for us to diagnose this issue. No stacktrace or a reproducible project.

Please attach logs, a sample app and other information that shows CocoaPods problem and not an Xcode problem.

Due to many issues being filed I am going to close and I will re-open once you attach information here.

**Comment by marlti7** [comment]
same problem @joona0825  do you fix it?

**Comment by jienice** [comment]
i have the same issue but i don't know whether the problem is Xcode or CocoaPods
