### ISSUE TITLE
Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: 407 "authenticationrequired"

### ISSUE THREAD

**Issue by MGABSI** [CocoaPods/CocoaPods#9291]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?

Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: 407 "authenticationrequired"

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A602)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories :
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project

platform :ios, '12.0'


target 'DynamicSwiftUITableView' do

pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Analytics'
pod 'Firebase/Database'

end

## Project that demonstrates the issue

an Empty project with this podfile

**Comment by dnkoutso** [comment]
Seems like your ISP or your network configuration is preventing you from reaching out `https://cdn.cocoapods.org`.

There isn't much we can do about this so I recommend you switch back to use the `git` based repo by adding it with `source 'https://github.com/CocoaPods/Specs.git'` into your `Podfile`.

**Comment by MGABSI** [comment]
I have tried this solution but it does not work
all my proxy credentials are setted correctly in the terminal and the url is available using web browser.
You can't close the issues without asking for further details

**Comment by dnkoutso** [comment]
> I have tried this solution but it does not work

What solution did you try?

We can still keep talking about this issue even if it's closed. 

The code that errors out is:
```ruby
      def cdn_url?(url)
        url =~ %r{^https?:\/\/} &&
          REST.head(url + '/all_pods.txt').ok?
      rescue => e
        raise Informative, "Couldn't determine repo type for URL: `#{url}`: #{e}"
      end
``` 

CocoaPods is making a request that receives a 407 for providing credentials to your proxy server.

> The HTTP 407 Proxy Authentication Required client error status response code indicates that the request has not been applied because it lacks valid authentication credentials for a proxy server that is between the browser and the server that can access the requested resource.

I will re-open but I will await for your input on showing what we can do to fix this in CocoaPods as I personally do not know.

**Comment by MGABSI** [comment]
Even if i add source 'https://github.com/CocoaPods/Specs.git' in my pod file i have the same problem.
my proxy credentials are exported correctly using this command:
export http_proxy=http://username:pws@proxyhost:port/
export https_proxy=http://username:pws@proxyhost:port/
It was perfectly working with OSX Mojave but the problem occur with Catalina.

**Comment by dnkoutso** [comment]
Would love someone to assist here on figuring out although again this issue appears to be related to Catalina as you say and something with the network configuration to be able to use these credentials for the proxy.

**Comment by e911miri** [comment]
I have been experiencing the same issue since Dec 2, 
Started on Catalina. Is this issue closed?

**Comment by WeZZard** [comment]
Nope. I also have encountered this issue.

**Comment by H-Ghadirian** [comment]
I have this issue!

**Comment by amorde** [comment]
Are you running a proxy server? Did you see [this comment](https://github.com/CocoaPods/CocoaPods/issues/9291#issuecomment-546384958)?

**Comment by Edorin9** [comment]
### **UPDATE COCOAPODS**

sudo gem install cocoapods

**Comment by e911miri** [comment]
> I have been experiencing the same issue since Dec 2,
> Started on Catalina. Is this issue closed?

Found a workaround for this.
Turns out the proxy was not being picked up. Running this just before the command fixed it export `http_proxy=http://username:pws@proxyhost:port/`
