### ISSUE TITLE
Issue with testspecs depending on subspecs within the same podspec

### ISSUE THREAD

**Issue by kylefleming** [CocoaPods/CocoaPods#9294]
🌈
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## Description

I'm using testspecs in a pod that has multiple subspecs. In order to test these subspecs in isolation, I've created a dedicated testspec for each subspec. Additionally, because CocoaPods unions subspecs within a target, I'm using a dedicated `abstract_target` per `test_spec`.

Does CocoaPods treat subspecs as implicitly depending on their parent? Furthermore, are testspecs treated as implicitly depending on the subspec that holds the testspec?

CocoaPods currently raises an error if you try to explicitly declare a dependency on a parent subspec, so if CocoaPods doesn't create an implicit dependency on the parent, then a testspec could not be nested reliably within the subspec it is intending to test (I say reliably because it could work if all the dependencies happen to be satisfied regardless).

The second part of this is that I'm running into a bug where CocoaPods is choosing the wrong target as a dependency for the `Test/Rx/Tests` testspec. I believe this is caused by the `Pod::Installer::Analyzer` not taking into account the parent subspec as a direct dependency of the child testspec when calculating dependencies for that testspec.

I believe this bug is causing a second bug where the testspec ends up depending on 2 different versions of the pod target, each with different subspec configurations. This is evidenced in the example project (see [Test-Core-Rx.unit-rx-tests.xcconfig](https://github.com/kylefleming/CocoaPodsTestSpecParentDepBug/blob/feff524afc08fea2570b575d715c40d729468bfb/Pods/Target%20Support%20Files/Test-Core-Rx/Test-Core-Rx.unit-rx-tests.xcconfig#L1)) where you will actually see that the `Test` pod is being referenced twice in the `FRAMEWORK_SEARCH_PATHS` variable.

Considering that the `Podfile` in the example project is declaring the pod with the testspec's parent subspec as the base (`pod 'Test/Rx', testspecs: ['Tests']`), I would expect the `Test/Rx/Tests` target to have a dependency on the `Test/Rx` subspec, regardless of whether or not CocoaPods creates an implicit dependency from a subspec/testspec to its parent subspec.

Essentially I've outlined 2 issues:
1) Because a testspec are meant to test a piece of code, it seems like it would be best if it was nested within the spec/subspec it's testing. This implies the need for the testspec to declare a dependency on its parent subspec, whether implicitly or explicitly.
2) There appears to be a bug where CocoaPods is selecting 2 versions of a pod for a testspec to depend on, creating a conflict about which one should be imported (the example app demonstrates this)

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.15 (19A583)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/kyle/.rbenv/versions/2.5.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 8d08cb56c3c211bfb8e15bc0a86359545d843dd1
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/kyle/.rbenv/versions/2.5.3/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://cdn.cocoapods.org/'
platform :ios, '10.0'

use_frameworks!

workspace 'Test'

abstract_target 'DummyTarget1' do
  pod 'Test/Core', path: '.', testspecs: ['Tests']
end

abstract_target 'DummyTarget2' do
  pod 'Test/Rx', path: '.', testspecs: ['Tests']
end
```

## Project that demonstrates the issue

https://github.com/kylefleming/CocoaPodsTestSpecParentDepBug

**Comment by dnkoutso** [comment]
@kylefleming thanks for the issue. I will need sometime to carefully read and diagnose this.
