### ISSUE TITLE
cocoapod The Podfile contains framework or static library targets (CameraSDK, HomeGuardSDK), for which the Podfile does not contain host targets (targets which embed the framework).

### ISSUE THREAD

**Issue by wanglongxiang360** [CocoaPods/CocoaPods#9296]
podfile

platform :ios, '9.0'

# pod update --verbose --no-repo-update
use_frameworks!

pod 'SDWebImage', '~> 5.0.4'   # 最近版本 5.x
pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh', '~> 3.2.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'AFNetworking', '~> 3.2.1'
pod 'MJExtension', '~> 3.2.1'
pod 'CocoaAsyncSocket', '~> 7.6.3'
pod 'YYModel', '~> 1.0.4'

target 'CameraES' do
project 'CameraES.xcodeproj'
workspace 'CameraES.xcworkspace'

end

target 'QGCameraSDK' do
project 'CameraES.xcodeproj'
workspace 'CameraES.xcworkspace'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # Pods for QGCameraSDK

    pod 'SHPluginSDK', :git => "https://xx.git" ,:branch=>"tag26"

end

target 'HomeGuardSDK' do
  project 'HomeGuardSDK/HomeGuardSDK.xcodeproj'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # Pods for HomeGuardSDK
  

end

**Comment by wanglongxiang360** [comment]
help！help！help！

**Comment by dnkoutso** [comment]
This is just a warning and currently the message explains why it shows up. Furthermore, this is insufficient information for us to diagnose the issue but from what it looks like there is no issue here.

Please fill in the issue template fully, upload a sample app and include step-by-step instructions for us to diagnose the issue.
