### ISSUE TITLE
A Crazy Problem！！！

### ISSUE THREAD

**Issue by HuangYanQi** [CocoaPods/CocoaPods#9297]
When I performan 'pod init',it works! And generate Podfile。But!!!! In the next step，I perform 'pod install',it tell me "[!] No `Podfile' found in the project directory." What's the problem with you! It's so crazy!!!!!!!!!

**Comment by dnkoutso** [comment]
This is insufficient information for us to diagnose. Please fill in issue template and provide step-by-step instructions for us to diagnose.

**Comment by HuangYanQi** [comment]
Hello！I'm glad to tell you the problem have been resolved by myself.The reason is that I use the command 'git init' and 'git install' under the directory who‘s name contains Chinese Character '（）',such as "Project（WorkSpace）" &nbsp;and so on.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D. Koutsogiorgas"<notifications@github.com&gt;; 
发送时间: 2019年10月28日(星期一) 晚上10:43
收件人: "CocoaPods/CocoaPods"<CocoaPods@noreply.github.com&gt;; 
抄送: "huangyanqi"<247069512@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CocoaPods/CocoaPods] A Crazy Problem！！！ (#9297)




This is insufficient information for us to diagnose. Please fill in issue template and provide step-by-step instructions for us to diagnose.
