### ISSUE TITLE
USER_HEADER_SEARCH_PATHS with relative path not working

### ISSUE THREAD

**Issue by johanlantz** [CocoaPods/CocoaPods#9299]
So, this is most likely me using things wrong so see it is a noob question and apologize if I am missing something obvious.

I have a .podspec file that is depending on a precompiled library so I use:
```s.ios.vendored_library = "lib/ios/essentia/lib/libessentia.a"```

for the library and then I added:
``` s.pod_target_xcconfig = { 'USER_HEADER_SEARCH_PATHS' => '"/Users/xxx/projects/my_project/lib/ios/essentia/include/**"' }```

for the header file. This works fine

However I do not want to use the absolute path above but nothing I try with a relative path works.

Assuming that we start from the root folder like for the .a file does not work, neither does anything else I have tried:
``` s.pod_target_xcconfig = { 'USER_HEADER_SEARCH_PATHS' => '"lib/ios/essentia/include/**"' }```

I also tried something like this with preserver_paths but no luck so far:
``` 
s.preserve_paths = "lib/ios/essentia/include/**/*"
  s.pod_target_xcconfig = {
    "HEADER_SEARCH_PATHS" => '"$(PODS_ROOT)/lib/ios/essentia/include/**/*"'
  }
```
What is the correct way to point to the header files for a precompiled library from the .podspec file?

**Comment by dnkoutso** [comment]
Use `$PODS_TARGET_SRCROOT` should do it. I am going to preemptively close and we can re-open if we find a bug!
