### ISSUE TITLE
 CDN: trunk Repo update failed - 2 error(s):

### ISSUE THREAD

**Issue by SnailLoveSmile** [CocoaPods/CocoaPods#9303]
[!] CDN: trunk Repo update failed - 2 error(s):
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/8/a/0/IQKeyboardManager/6.5.2/IQKeyboardManager.podspec.json, error: execution expired
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/8/a/0/IQKeyboardManager/6.5.3/IQKeyboardManager.podspec.json, error: execution expired

how can i fix it? help me please

**Comment by SnailLoveSmile** [comment]
cocopods -- version 1.8.4

**Comment by llt3677** [comment]
[!] CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/2/e/c/RxSwift/5.0.1/RxSwift.podspec.json, error: execution expired
llt@lilutaode

**Comment by yangdongming** [comment]
Me too

**Comment by RiberWang** [comment]
I try to adding it with source 'https://github.com/CocoaPods/Specs.git' into my Podfile, but it's don't worked.

**Comment by RiberWang** [comment]
`pod repo list` 查看源列表
`pod repo remove trunk` 移除trunk源

问题才解决！！！

**Comment by sea7reen** [comment]
移除了以后，pod install 会自动Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
这个怎么处理，感觉死循环了。

**Comment by RiberWang** [comment]
看下这篇文章
https://www.jianshu.com/p/bf1cbe49cb5d

**Comment by RiberWang** [comment]
大家看下这篇文章 里面说的很详细了
https://www.jianshu.com/p/bf1cbe49cb5d

**Comment by Songkunda** [comment]
1. Podfile add
`source 'https://github.com/CocoaPods/Specs.git'`
2.  remove  trunk
`pod repo remove trunk`

**Comment by yang0123shu** [comment]
如果系统是10.15.1, pod 1.8.4版本，建议卸载重装旧版本pod。个人亲测，1.6.1正常使用。

**Comment by ripperhe** [comment]
发布pod不还是要用trunk吗？

**Comment by Lex-Nart** [comment]
没用，说的很不现实，掩耳盗铃

**Comment by yang0123shu** [comment]
> 没用，说的很不现实，掩耳盗铃

是的，trunk又报错了。

**Comment by FreezzzFrank** [comment]
> 1. Podfile add
>    `source 'https://github.com/CocoaPods/Specs.git'`
> 2. remove  trunk
>    `pod repo remove trunk`

ths,this save my life

**Comment by luoshiyutim** [comment]
I encountered your problem in cocoapods 1.8.4. Trying various methods still can't solve the problem.

Finally

`$ sudo gem install cocoapods --pre`

solved !!!

**Comment by FireG** [comment]
> [!] CDN: trunk Repo update failed - 2 error(s):
> CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/8/a/0/IQKeyboardManager/6.5.2/IQKeyboardManager.podspec.json, error: execution expired
> CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/8/a/0/IQKeyboardManager/6.5.3/IQKeyboardManager.podspec.json, error: execution expired
> 
> how can i fix it? help me please

解决了吗？

**Comment by feixue299** [comment]
I tried the proxy a few more times and it worked

**Comment by luoshiyutim** [comment]
> I encountered your problem in cocoapods 1.8.4. Trying various methods still can't solve the problem.
> 
> Finally
> 
> `$ sudo gem install cocoapods --pre`
> 
> solved !!!

This solution is not working now.

Finally, I found that this is a proxy issue for me. 

solution:
`$ export https_proxy=my proxy;`
`$ git config --global https.proxy $HTTPS_PROXY`
`$ git config --global --get https.proxy`

ps:
When you open a new terminal, you must execute these command line again.

**Comment by RITL** [comment]
> 发布pod不还是要用trunk吗？

您好，我这边也在发布pod，由于依赖了Masonry，验证总是出错:  是需要我这边怎么配置吗，不知道您知不知道 😀
```
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired
```

**Comment by ripperhe** [comment]
@RITL 我记得当时我用 `1.8.4` 也遇到这个问题，没解决掉，最后降级到 `1.7.0` 了

```sh
sudo gem uninstall cocoapods
gem install cocoapods -v 1.7.0
```

**Comment by RITL** [comment]
好的，十分感谢 @ripperhe  0.0

**Comment by RITL** [comment]
@ripperhe  我现在的解决方式是在 `host` 文件里面 加了
 `199.232.4.133 raw.githubusercontent.com`
就不会出现`CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired`这个了，不知道能不能解决你的问题 😀 共勉一下

**Comment by juncen** [comment]
> @ripperhe 我现在的解决方式是在 `host` 文件里面 加了
> `199.232.4.133 raw.githubusercontent.com`
> 就不会出现`CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired`这个了，不知道能不能解决你的问题 😀 共勉一下

it works for me！thank you so much！

**Comment by samniu** [comment]
> > @ripperhe 我现在的解决方式是在 `host` 文件里面 加了
> > `199.232.4.133 raw.githubusercontent.com`
> > 就不会出现`CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired`这个了，不知道能不能解决你的问题 😀 共勉一下
> 
> it works for me！thank you so much！

199.232.4.133 is ok!  but the ping result not works.

**Comment by Saron977** [comment]
> @ripperhe 我现在的解决方式是在 `host` 文件里面 加了
> `199.232.4.133 raw.githubusercontent.com`
> 就不会出现`CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired`这个了，不知道能不能解决你的问题 😀 共勉一下

牛皮，可以的

**Comment by ripperhe** [comment]
> @ripperhe 我现在的解决方式是在 `host` 文件里面 加了
> `199.232.4.133 raw.githubusercontent.com`
> 就不会出现`CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired`这个了，不知道能不能解决你的问题 😀 共勉一下

兄弟，谢谢了，好用

**Comment by jayasme** [comment]
Most of reasons address to GFW, using a VPN or proxy could solve the problem...sometimes....

**Comment by hanniuqueen** [comment]
> @ripperhe 我现在的解决方式是在 `host` 文件里面 加了
> `199.232.4.133 raw.githubusercontent.com`
> 就不会出现`CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired`这个了，不知道能不能解决你的问题 😀 共勉一下

牛皮，感恩～～～

**Comment by cybaba7660** [comment]
> /

host 文件在哪啊大佬

**Comment by KevinCool01** [comment]
> > /
> 
> host 文件在哪啊大佬

cd /etc/hosts

**Comment by zmXie** [comment]
> @ripperhe 我现在的解决方式是在 `host` 文件里面 加了
> `199.232.4.133 raw.githubusercontent.com`
> 就不会出现`CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired`这个了，不知道能不能解决你的问题 😀 共勉一下

牛批

**Comment by zxwcool** [comment]
> @ripperhe 我现在的解决方式是在 `host` 文件里面 加了
> `199.232.4.133 raw.githubusercontent.com`
> 就不会出现`CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/a/4/Masonry/0.0.2/Masonry.podspec.json, error: execution expired`这个了，不知道能不能解决你的问题 😀 共勉一下

U saved my life! it works for me, thanks!

**Comment by Songkunda** [comment]
> raw.githubusercontent.com

我用的这个:
199.232.68.133 raw.githubusercontent.com

比你那个快一些

**Comment by rocky-co** [comment]
>@Songkunda 我用的这个:
> 199.232.68.133 raw.githubusercontent.com
> 比你那个快一些 
我也是
