### ISSUE TITLE
[!] CDN: trunk Repo update failed - 2 error(s):

### ISSUE THREAD

**Issue by HSFAqi** [CocoaPods/CocoaPods#9306]
when i code : pod search xxx

[!] CDN: trunk Repo update failed - 2 error(s):
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/7/5/AFNetworking/1.0.1/AFNetworking.podspec.json, error: Net::OpenTimeout
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/a/7/5/AFNetworking/2.0.0-RC2/AFNetworking.podspec.json, error: execution expired

**Comment by dnkoutso** [comment]
This report is insufficient for us to diagnose the issue. It seems like you are retrieving a network issue hitting our CDN server. Please use add the `git` based source in your `Podfile` as a workaround and use `git` instead of the `trunk` repo. You can also do `pod repo remove trunk` after.
