### ISSUE TITLE
No longer able to build sample app with Cocoapods 1.8.x

### ISSUE THREAD

**Issue by chrismrideos** [CocoaPods/CocoaPods#9308]
* [Y] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Steps:
1) Upgraded from CocoaPods `1.7.5` to `1.8.4`
2) Ran `pod install` on [this sample project](https://github.com/rideOS/RideOsApiTestApp)
3) Opened the generated `RideOsApiTestApp.xcworkspace` and attempted to build the app

## What did you expect to happen?

The app to build and run correctly, as it did when running `pod install` using CocoaPods `1.7.5`

## What happened instead?

Got a lot of build errors in `RideOsApi-umbrella.h`

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A603)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 935d7ef0d772a97b5d0b82232c76fedfdc712366
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '13.0'
use_frameworks!

target 'RideOsApiTestApp' do
  pod 'RideOsApi'
end
```

## Project that demonstrates the issue

https://github.com/rideOS/RideOsApiTestApp

The [latest commit](https://github.com/rideOS/RideOsApiTestApp/commit/be8302e399dca6bebab3253a64d9b544e8756541) contains the state of the workspace after upgrading to `1.8.4`. The [2nd-to-latest commit ](https://github.com/rideOS/RideOsApiTestApp/commit/1f9aa8e354dc07a28df922b446c9336a8646d757) contains the state of the workspace with `1.7.5`

**Comment by chrismrideos** [comment]
Is there anyone who might be able to help with this?

**Comment by irons163** [comment]
I think it probably because 1.8.0 change the `header_mappings_dir` behavior.
The fail message said "Include of non-modular header inside framework module".
The solutions are two:
1. Add 
post_install do |installer|
  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end
end
in your Podfile and reinstall.

2. Write your custom umbrella header.

I'll show you how to do the method 2.

**Comment by chrismrideos** [comment]
Thanks @irons163. Upon further investigation, it appears the main issue is that the headers are marked as `Project`, not `Public` in the `Headers` build phase. If I manually mark them as `Public` in the GUI, and then remove all relative paths in the generated umbrella header, everything builds.

It appears that Cocoapods now generates its own Copy Headers phases for each set of headers (ex: I see a `Copy RideOsApi/core Public Headers` phase). These happen *after* the main `Headers` phase, though, which seems to be causing issues. Is there a way to get Cocoapods to use the main `Headers` build phase instead of generating its own?

**Comment by dnkoutso** [comment]
> These happen after the main Headers phase, though, which seems to be causing issues. Is there a way to get Cocoapods to use the main Headers build phase instead of generating its own?

I believe this is fixed for 1.9.x can you try master?

**Comment by chrismrideos** [comment]
> I believe this is fixed for 1.9.x can you try master?

Thanks for the suggestion, @dnkoutso. Unfortunately I see the same behavior with master

**Comment by dnkoutso** [comment]
@chrismrideos the reason these generated header phases appear is because the podspec uses `header_mappings_dir` so CocoaPods preserves the folders inside the `.framework` that will be generated for the `RideOsApi` target.

I believe this is a bug with subspecs of course so I am still investigating.

**Comment by dnkoutso** [comment]
It's clearly an issue with combining subspecs with header mappings dir and a root spec without. I am marking it as such.

**Comment by dnkoutso** [comment]
@chrismrideos are you the owner of the pod? if so how was it published does it lint successfully?

**Comment by dnkoutso** [comment]
@chrismrideos [this](https://github.com/CocoaPods/CocoaPods/pull/9383) would fix your initial bug with `SDKLoad.h` which belongs in the root spec and does not specify the header mappings dir. You would need to fix the RPC generated code to import the correct framework paths since you are using custom header mappings dir for that code.
