### ISSUE TITLE
Outdated resources bundle installed with framework

### ISSUE THREAD

**Issue by hassaanelgarem** [CocoaPods/CocoaPods#9318]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod install` with the following pod in the podfile `pod 'Instabug', '~> 8.7.2'`

## What did you expect to happen?

I expected that the Instabug pod be installed correctly

## What happened instead?

The framework was installed but the resources bundle included in the framework was outdated. The framework installed was of version 8.7.2 but the resources bundle installed with it wasn't matching, it was of a previous version.

This caused the apps of our users using Instabug to crash because the NIB files didn't match the code.

This issue happened with a couple of our users that uses Instabug. One of the users tried a couple of approaches to fix this including deleting the cache and clearing the derived data and running pod update multiple times. One of these steps fixed it for them, but they're not sure which one. 

Linked is the [issue](https://github.com/Instabug/Instabug-iOS/issues/339) opened in Instabug's repo.

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 9a7f370f0c3cb8442655c3b27658a436faee7206
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.3'

inhibit_all_warnings!

target 'MyApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WawiboxScan
  pod 'Alamofire', '~> 4.7.3'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.3.0'
  pod 'ObjectMapper', '~> 3.3.0'
  pod 'NibDesignable', :git => 'https://github.com/Pro2005/NibDesignable.git'
  pod 'KeychainAccess', '~> 3.1.2'
  pod 'PromiseKit/CorePromise', '~> 6.5.2'
  pod 'Mockingjay/Core', '~> 2.0.1'
  pod 'ACAlertController', :git => 'https://github.com/Pro2005/ACAlertController.git'
  pod 'ACNotifications', :git => 'https://github.com/Pro2005/ACNotifications.git'
  pod 'SwiftyBeaver', '~> 1.6.1'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  pod 'Instabug', '~> 8.7.2'
  pod 'SnapKit', '~> 4.2.0'
  pod 'NVActivityIndicatorView', '~> 4.7.0'
  pod 'Validator', '~> 3.2.1'
  
end
```

**Comment by dnkoutso** [comment]
What does "outdated" mean? Need a sample app as this currently appears a `Instabug` pod issue probably.

> The framework was installed but the resources bundle included in the framework was outdated. The framework installed was of version 8.7.2 but the resources bundle installed with it wasn't matching, it was of a previous version.

This sounds like the pod author did not update the resource bundle on this release.

Need a sample app with clear steps to reproduce.

**Comment by Kmohamed** [comment]
@dnkoutso I do not think this was the case could you please check the issue [here](https://github.com/Instabug/Instabug-iOS/issues/339).
After `pod deintegrate` and `pod update` the crash disappeared on the same version.

**Comment by Kmohamed** [comment]
An issue like this is hard to be reproduced using a sample app 😬
