### ISSUE TITLE
Prepend PCH option for OpenCV dependency

### ISSUE THREAD

**Issue by BryanVision** [CocoaPods/CocoaPods#9320]
I am attempting to move our SDK over to cocoapods.   
It has OpenCV as a dependency. 
OpenCV requires the following code at the TOP of the pch file.
```
#ifdef __cplusplus
#include <opencv2/opencv.hpp>
#endif
```

In the podspec, prefix_header_file and prefix_header_contents appear to only append the autogenerated pch file but the #ifdef code will not work unless it is first, above the other code it generated.  If I attempt to move all of that code out to my own pch, pod install duplicates the code.

<img width="477" alt="Screen Shot 2019-11-04 at 2 23 01 PM" src="https://user-images.githubusercontent.com/53382005/68163120-a38c0b80-ff0e-11e9-8967-2375d83969cf.png">

Is there a workaround here, such that use of our pod doesn't require that the user manually take steps to fix the opencv build error every time they do a pod install?

<img width="271" alt="Screen Shot 2019-11-04 at 2 27 53 PM" src="https://user-images.githubusercontent.com/53382005/68163425-56f50000-ff0f-11e9-8c43-c1df823f8d8e.png">

<img width="408" alt="Screen Shot 2019-11-04 at 2 24 52 PM" src="https://user-images.githubusercontent.com/53382005/68163211-e817a700-ff0e-11e9-9774-e4a10f2988ef.png">

I've tried setting prefix_header_file to false and adding my own pch file, but pod-install overwrites the build setting reference path to my pch even when the option is set to false.

**Comment by dnkoutso** [comment]
> I've tried setting prefix_header_file to false and adding my own pch file, but pod-install overwrites the build setting reference path to my pch even when the option is set to false.

How did you try that? `prefix_header_file = false` will skip the PCH file generation by CocoaPods.

**Comment by drriguz** [comment]
Hi，I got the same issue, have you solved this?
