### ISSUE TITLE
Unable to update podspec

### ISSUE THREAD

**Issue by vaisakhcherrylabs** [CocoaPods/CocoaPods#9322]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod spec lint AsistaCore.podspec --verbose

## What did you expect to happen?

Expecting the updation of current cocoapod version to v1.0.0

## What happened instead?

 -> AsistaCore (1.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Pod::DSLError) during validation.

Analyzed 1 podspec.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 3cce38582d61a339bc415016b0e37b363dc62601
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
This is the public repo for AsistaCore SDK. Current production version of library is 0.3.1. 
https://github.com/cherrylabstech/asista-sdk-ios

**Comment by dnkoutso** [comment]
Is this issue still relevant?

I tried your instructions and I got:
```
Analyzed 1 podspec.

AsistaCore.podspec passed validation.
```
