### ISSUE TITLE
How can I modify the contents of the Info.plist?

### ISSUE THREAD

**Issue by rakuyoMo** [CocoaPods/CocoaPods#9323]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Requirement
My requirement is to modify some of the values in the Info.plist file in the main project, for example:

```
'CFBundleShortVersionString' => '1.0.0'
```

> ps:
> Someone may question my needs, so I want to explain
> 
> When doing componentization, we will have some Config components. I want to put a lot of configuration in this component, as long as the main project integrates this component, it will have these configurations.
> 
> At the same time, for some reason, these configurations, such as some strings, already exist in the Config component, I don't want to take them out separately and write them again in the main project - in this case, when I need to modify these configurations, I Need to be modified twice in different places - it is better to modify twice in the same place than to modify it twice in different places.

# Problem

I know both `info_plist` and `INFOPLIST_FILE`, but they don't seem to satisfy my needs.

I want to modify the contents of the main application, `info_plist` can only modify the pod, and `INFOPLIST_FILE` is just the path to the info.plist file, I don't want to specify a new info.plist file.

Is there similar to `pod_target_xcconfig` and `user_target_xcconfig`? I think I need a `user_ info_plist`

**Comment by dnkoutso** [comment]
You can easily load your applications info plist in a post install hook. Load it, modify it and then save it.

I do not think we will be adding first class DSL for this now.

**Comment by rakuyoMo** [comment]
I don't want to write any configuration in the main project's podfile. I want to write the content in the component's podspec. What commands can I do? `script_phases` or `prepare_command` ?

**Comment by dnkoutso** [comment]
You can probably do it with script phases. A podspec shouldnt need to know the users target to edit it as it is meant to be used by any user target.

If its internal usage only then yes script phase or prepare command would suffice.

I am going to close this as I do not see any action that we can do further here with the CocoaPods library.

**Comment by rakuyoMo** [comment]
I know what to do, thank you very much for your patience.

**Comment by Aaronwk** [comment]
> 我知道该怎么办，非常感谢您的耐心配合。

您好，我正好有这方面的需求。请问一下，您是怎么解决的？方便说一下吗

**Comment by rakuyoMo** [comment]
@Aaronwk You can try this way

```Ruby
s.user_target_xcconfig = {
          'PRODUCT_BUNDLE_IDENTIFIER[config=MBDev_Debug]' => 'com.your.bundle',
}
```

**Comment by Aaronwk** [comment]
> @Aaronwk您可以尝试这种方式
> 
> ```ruby
> s.user_target_xcconfig = {
>      ' PRODUCT_BUNDLE_IDENTIFIER [config = YOUR_SCHEME] ' => ' com.your.bundle '，
> }
> ```
你好，感谢您的回复。可是我使用这个 然后 执行 pod install 我的 PRODUCT_BUNDLE_IDENTIFIER 没有发生任何改变。是哪里操作有问题吗 我的目的是 想在info.plist 里面添加一项。比如 key:TestName  value: name   感谢
