### ISSUE TITLE
Swift compiler version changes on pod install [Bug]

### ISSUE THREAD

**Issue by Albinzr** [CocoaPods/CocoaPods#9324]
I'm facing an issue with the universal framework in iOS (closed source).

When creating the universal framework it shows * Generated by Apple Swift version 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9) * and it works fine if add the framework to project

But after uploading it to git and using pod to install I'm getting an error Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.2 compiler

When I checked the header file I saw // Generated by Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)

The issue I understood is while uploading my compiler is Swift version 5.1.2, which is correct but after pod install somehow it's getting changed to Swift version 5.0.1

Why is this getting changed? and how can I make sure that it won't change?

**Podspec**
`
Pod::Spec.new do |s|
 s.platform = :ios, '11.0'
 s.name = "IntellicarBle"
 s.version = '1.0.5'
 s.summary = 'IntellicarBle - Binaries'
 s.description = 'Framework for IntelliBlu'
 s.homepage = 'https://github.com/intellicar/IntelliBlu_iOS_SDK'
 s.license = { :type => 'MIT' }
 s.author = 'https://github.com/Albinzr'
 s.requires_arc = true
 s.swift_version = '5.1'
 s.source = { :http => 'https://github.com/intellicar/IntelliBlu_iOS_SDK/blob/master/IntellicarBle.framework.zip?raw=true' }
 s.ios.deployment_target = '11.0'
 s.ios.vendored_frameworks = 'IntellicarBle.framework'
end

`
**Podfile details**
`
target 'IntellicarBleDemo' do
  use_frameworks!
  pod 'IntellicarBle', :git => 'https://github.com/intellicar/IntelliBlu_iOS_SDK.git', :branch => '1.0.5'
end
`

**Comment by Albinzr** [comment]
you can check this repo for sample 
[Repo](https://github.com/intellicar/IntelliBlu_iOS_SDK/)

**Comment by Albinzr** [comment]
@dnkoutso Any idea why this is happening?

**Comment by Albinzr** [comment]
Any updates??

**Comment by Albinzr** [comment]
@dnkoutso any fixes?

**Comment by Albinzr** [comment]
Couldn't get any response from cocoapods team, Moved the SDK to swift packages and Carthage

**Comment by Albinzr** [comment]
Couldn't get any response from cocoapods team, Moved the SDK to swift packages and Carthage

**Comment by dnkoutso** [comment]
We do this work in our freetime, apologies for the delay.

**Comment by dnkoutso** [comment]
From a quick overview this is a known issue that binary pods (pods that have no source files) do not obey the Swift version parameter used.

You can work around this by adding a single source file and I believe that would force the correct Swift version attribute to be set but I haven't tested it myself.

**Comment by Albinzr** [comment]
@dnkoutso Can you explain how to do it in detail? Thanks

**Comment by Albinzr** [comment]
Still not fixed ....
