### ISSUE TITLE
Prevent using global gem

### ISSUE THREAD

**Issue by revolter** [CocoaPods/CocoaPods#9325]
🌈

What do you think about adding some mechanism to CocoaPods to prevent users from using the global gem instead of the local one?

It could be a waning similar to how _fastlane_'s:

<img width="856" alt="image" src="https://user-images.githubusercontent.com/5748627/68211729-cab30d80-ffe0-11e9-95ac-2b815c9d2e5c.png">

Related issue: https://github.com/fastlane/fastlane/issues/9435.

Or it could be an error, when it detects some flag. Examples:
- If the `Podfile` contains some flag or calls some method
- If an `.env` file from the current directory contains some flag
- If the `.stop_global_pod` file exists in the current directory

If we do find a solution that is acceptable by you, I would be up to implement it.

**Comment by orta** [comment]
Yeah, at [Artsy we used this code](https://github.com/artsy/eigen/blob/master/Podfile#L1-L6) to validate folks were only using bundler:

```ruby
using_bundler = defined? Bundler
unless using_bundler
  puts "\nPlease re-run using:".red
  puts "  bundle exec pod install\n\n"
  exit(1)
end
```

I think it makes sense if you have a Gemfile in the CWD and no `defined? Bundler` that it should probably warn like Fastlane does

**Comment by revolter** [comment]
But maybe we'd want to make this opt-in, at least in the beginning? Maybe there are people or CI configurations that (albeit incorrectly) are using them without `bundle exec`, even if they have a `Gemfile` in the project.

Also, you could have a `Gemfile` that doesn't contain the `cocoapods` gem, so in that case, you **can't** use `bundle exec`. Which means you either show a warning instead of exiting, either allow users to opt-in into exiting.

**Comment by revolter** [comment]
Oh, I didn't read your message properly, I now see that that code is in the project's `Podfile`. How could I not have thought of that? 😆

So that code could be moved into a function like `ensure_bundler!` in CocoaPods, similar to `inhibit_all_warnings!`, right?

**Comment by dnkoutso** [comment]
It could move yes but I think the workaround of adding to the `Podfile` is sufficient. We do the same internally.

**Comment by revolter** [comment]
But that means that everyone who wants this, needs to copy+paste it, and that a lot of people don't even know about this possibility and the issues it could avoid. But having it in CocoaPods means having it documented, maybe even in a getting started doc.

But, it's your call, if you decide otherwise, let me know and I'll work on a PR adding it.

**Comment by amorde** [comment]
I personally don't think we should prevent this, or even warn, as most individuals likely prefer using it globally and teams of iOS developers likely have this setup in their project anyway. We can update the docs to make this more visible though.

If you are an individual working on your own iOS project, there isn't a huge need to use bundler unless you also use other Ruby tools, are using custom branchs of CocoaPods, or have multiple projects

**Comment by revolter** [comment]
I think that using bundler is ok even if you don't use other Ruby tools or using custom branches. Because a developer might use a version of the tool that modifies the project file in some way, and another developer might be in the opposite case, so there will be a lot of commits changing the project file back and forth.

But I have no problem with this proposal being denied.

**Comment by amorde** [comment]
Oh I definitely think bundler should be _preferred_, but don't think it should be enforced with an error or something similar. I agree there are plenty of benefits that come with using bundler which is why I always use it on my projects :)

**Comment by revolter** [comment]
It would be enforced only if you add `ensure_bundler!` in your project's `Podfile`. In no way it should do this by default.

**Comment by amorde** [comment]
Ah, yes I think that'd be a nice addition 👍
