### ISSUE TITLE
pod install 后，三方库的后面没有了版本号

### ISSUE THREAD

**Issue by linger997** [CocoaPods/CocoaPods#9326]
--------
lingerdeMacBook-Pro:WaspTC linger$ pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 25 dependencies from the Podfile and 27 total pods installed.
lingerdeMacBook-Pro:WaspTC linger$ 
-------
之前是应该显示版本号的
AMapFoundation 1.5.9 (was 1.5.8)
AMapSearch 7.1.0 (was 6.9.0)
YBImageBrowser (3.0.6)
YYImage (1.0.4)

**Comment by dnkoutso** [comment]
Please fill in the issue template.
