### ISSUE TITLE
CoreML .mlmodel file is not compiled when added through podspec

### ISSUE THREAD

**Issue by johanlantz** [CocoaPods/CocoaPods#9328]
Using CocoaPods <= 1.8.4

Using Xcode 11.2:
# Report
My cocoapod needs to provide a CoreML file (.mlmodel) to the app.

## What did you do?
I added the .mlmodel as a source like this:
```
s.source_files  = "src/ios/**/*.swift", "src/ios/**/*.h", "src/ios/**/*.cpp", "src/ios/Model/iemocap.mlmodel"
```

## What did you expect to happen?
I see that the .mlmodel file is available under my development pod
![Screenshot 2019-11-07 at 14 57 29](https://user-images.githubusercontent.com/7461655/68394894-f237e080-016e-11ea-9ed2-67d87fc75bea.png)

but unlike when I drag the model into the Xcode project manually, the model does not seem to be compiled by Xcode into the mlmodelc format. In the project using the cocoapod the build phases looks like this:
![Screenshot 2019-11-07 at 14 58 18](https://user-images.githubusercontent.com/7461655/68394978-1e536180-016f-11ea-8a20-248d66e0be63.png)

while in a project where I dragged the model into the app it is present under Comoile Sources in Build Phases:
![Screenshot 2019-11-07 at 14 59 26](https://user-images.githubusercontent.com/7461655/68395030-3f1bb700-016f-11ea-9f67-dca2fbece6b2.png)

One interesting thing is that the class that is autogenerated for the model is indeed working so this code compiles:
```
let model: iemocap = iemocap()
```

However the compiled files (that Xcode must auotcompile during build is not found, so when trying to load the model file in a project using a .podspec this fails:
```
let updatableModelURL = Bundle.main.url(forResource: "iemocap",
                                                withExtension: "mlmodelc")!
```

Saying that the file is not found which should prove that the compilation was not done during the build.

I have also tried to add the .mlmodel as a resource:
```
s.resources = ["src/ios/Model/iemocap.mlmodel"]
```

and used preserve_paths:
```
s.preserve_paths = "src/ios/Model/iemocap.mlmodel"
```

but it did not change anything.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A603)
       Xcode : 11.2 (11B52)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 0bd090e8274cc459a0d0b52c569f07cf088fbdf9
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
I am probably just doing this the wrong way and maybe I just have to add something simple in my podpec to make the .mlmode file compile
If this is not the case, I will try to provide a sample project. The problem is that this happens when using the cocoapod as a Flutter plugin so you would need to install Flutter to reproduce it.

**Comment by dnkoutso** [comment]
Metal files are not supported I believe as its also mentioned here https://github.com/CocoaPods/CocoaPods/issues/8403

**Comment by MatheusDomingos** [comment]
Hello, I had the same problem and it took me a long time to find a solution. The big secret is to "compile" at run time with the method: compileModelAtURL. I will show below how I did it:

`NSBundle *bundle = [NSBundle mainBundle];
        NSURL *centerModelURL = [bundle URLForResource: @"CenterModelCrop" withExtension: @"mlmodel"];`

`NSError *err;
        if ([centerModelURL checkResourceIsReachableAndReturnError:&err] == NO)
            NSLog(@"%@", err);`
        
  **Compile is Magic. This is trick to library.**

 `NSURL *urlCenterModel = [MLModel compileModelAtURL:centerModelURL error:&err];`

**Comment by gungorbasa** [comment]
Non of the solutions worked for me on my test target. I solved the issue by renaming the file. I renamed my `mlmodel` file with a different extension like `ml` then I could compile my model perfectly.

**Comment by BrentMifsud** [comment]
I have this issue as well. It seems the only solution is to copy the model from the pod into your apps bundle manually...
