### ISSUE TITLE
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

### ISSUE THREAD

**Issue by dreleanor** [CocoaPods/CocoaPods#9330]
<!--
ℹ Previously working app on iOS, however when trying to re-build error message as per above. 

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods.rb

# Report

## What did you do?

Ran pod update due to build error in Xcode with following message: PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/eleanorcartwright/Library/Developer/Xcode/DerivedData/Runner-exayyxyxqpckasajdnsnhbaxugne/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-A1D4B1618D684855FBCFA77C.sh (in target 'Runner' from project 'Runner')
    cd /Users/eleanorcartwright/Desktop/Developer/the_blue_book/ios
    /bin/sh -c /Users/xxxxxxxxxx/xxxxxx/xxxxx/Xcode/DerivedData/Runner-exayyxyxqpckasajdnsnhbaxugne/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Script-A1D4B1618D684855FBCFA77C.sh

diff: /Users/xxxxxxxxxxxxx/xxxxxxx/xxxxxxx/xxxxxxx/ios/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

## What did you expect to happen?

Install all pod dependencies and get rid of error message as per previous GitHub guides

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A603)
       Xcode : 11.2 (11B52)
         Git : git version 2.23.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
require 'cocoapods-core/podfile'

module Pod
  class Podfile
    autoload :InstallationOptions, 'cocoapods/installer/installation_options'

    # @return [Pod::Installer::InstallationOptions] the installation options specified in the Podfile
    #
    def installation_options
      @installation_options ||= Pod::Installer::InstallationOptions.from_podfile(self)
    end
  end
end
```

### Error

```
Errno::EACCES - Permission denied @ dir_s_mkdir - /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/Pods
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sandbox.rb:66:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:193:in `new'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:193:in `sandbox'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:140:in `installer_for_config'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/update.rb:46:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by dnkoutso** [comment]
There is insufficient information for us to diagnose this issue.
