### ISSUE TITLE
pod trunk push error

### ISSUE THREAD

**Issue by zanjs** [CocoaPods/CocoaPods#9335]
`
[!] Couldn't determine repo type for URL: `https://cdn.cocoapods.org/`: execution expired`

```
pod --version
1.8.4
```

**Comment by dnkoutso** [comment]
If you cannot use the CDN repo then switch to use the `git` based repo. Closing as currently this appears to be a network issue.

**Comment by girish54321** [comment]
after adding source 'https://github.com/CocoaPods/Specs.git' 
my other pod package stated showing error !!
