### ISSUE TITLE
Including a directory as a search path during compilation with CocoaPods

### ISSUE THREAD

**Issue by kentcb** [CocoaPods/CocoaPods#9337]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

The full details of my issue (including a repro) are provided in [this Stackoverflow question](https://stackoverflow.com/questions/58690010/including-a-directory-as-a-search-path-during-compilation-with-cocoapods). I hope it's acceptable to link to that rather than duplicating information here. If not, I will be happy to delete this issue and re-open another one.

**Comment by dnkoutso** [comment]
@kentcb isnt this answered in StackOverflow now?
