### ISSUE TITLE
pod trunk push failed on CI

### ISSUE THREAD

**Issue by Kmohamed** [CocoaPods/CocoaPods#9338]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command
pod trunk push Instabug.podspec
```
/Users/distiller/.gem/ruby/2.6.4/bin/pod trunk push Instabug.podspec
```

### Report

* What did you do?
Release a new version

* What did you expect to happen?
to be released

* What happened instead?
Failed
  CDN: Repo trunk does not exist!

### Stack

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 11.1 (11A1027)
         Git : git version 2.23.0
Ruby lib dir : /Users/distiller/.rubies/ruby-2.6.4/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `url' for nil:NilClass
/Users/distiller/.gem/ruby/2.6.4/gems/cocoapods-trunk-1.4.0/lib/pod/command/trunk/push.rb:155:in `master_repo_url'
/Users/distiller/.gem/ruby/2.6.4/gems/cocoapods-trunk-1.4.0/lib/pod/command/trunk/push.rb:121:in `validate_podspec'
/Users/distiller/.gem/ruby/2.6.4/gems/cocoapods-trunk-1.4.0/lib/pod/command/trunk/push.rb:70:in `run'
/Users/distiller/.gem/ruby/2.6.4/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/distiller/.gem/ruby/2.6.4/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:52:in `run'
/Users/distiller/.gem/ruby/2.6.4/gems/cocoapods-1.8.0/bin/pod:55:in `<top (required)>'
/Users/distiller/.gem/ruby/2.6.4/bin/pod:23:in `load'
/Users/distiller/.gem/ruby/2.6.4/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by dnkoutso** [comment]
Use version CocoaPods 1.8.4 and also add the `trunk` repo by adding at least once `pod install`.

**Comment by Kmohamed** [comment]
@dnkoutso same
### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin18]
    RubyGems : 2.6.11
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /Users/khaledElMorabea/.rbenv/versions/2.4.1/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ dc4c97af544797233ecf7492616fe484bc2bc316
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `url' for nil:NilClass
/Users/khaledElMorabea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.4.0/lib/pod/command/trunk/push.rb:155:in `master_repo_url'
/Users/khaledElMorabea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.4.0/lib/pod/command/trunk/push.rb:121:in `validate_podspec'
/Users/khaledElMorabea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.4.0/lib/pod/command/trunk/push.rb:70:in `run'
/Users/khaledElMorabea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/khaledElMorabea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/khaledElMorabea/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/khaledElMorabea/.rbenv/versions/2.4.1/bin/pod:22:in `load'
/Users/khaledElMorabea/.rbenv/versions/2.4.1/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by nkshah2** [comment]
Hi, I realise this issue is closed but I am facing the same error. After running ```pod trunk push --verbose``` the error I get is 

```
CDN: Repo trunk does not exist!
```

Now I know this means that ```trunk``` has not been added and I need to run pod install. The problem is that the library I am working on has no dependencies and thus does not have a podfile. I was wondering if there was a way to install the ```trunk``` repo without needing a podfile in the project.

**Comment by a1049145827** [comment]
> Hi, I realise this issue is closed but I am facing the same error. After running `pod trunk push --verbose` the error I get is
> 
> ```
> CDN: Repo trunk does not exist!
> ```
> 
> Now I know this means that `trunk` has not been added and I need to run pod install. The problem is that the library I am working on has no dependencies and thus does not have a podfile. I was wondering if there was a way to install the `trunk` repo without needing a podfile in the project.

I run this command
```
rm -rf ~/.cocoapods/repos
```

and then, run `pod trunk push xxx`, it works!

**Comment by iPermanent** [comment]
> > Hi, I realise this issue is closed but I am facing the same error. After running `pod trunk push --verbose` the error I get is
> > ```
> > CDN: Repo trunk does not exist!
> > ```
> > 
> > 
> > Now I know this means that `trunk` has not been added and I need to run pod install. The problem is that the library I am working on has no dependencies and thus does not have a podfile. I was wondering if there was a way to install the `trunk` repo without needing a podfile in the project.
> 
> I run this command
> 
> ```
> rm -rf ~/.cocoapods/repos
> ```
> 
> and then, run `pod trunk push xxx`, it works!

worked for me, thanks
