### ISSUE TITLE
pod update Issues

### ISSUE THREAD

**Issue by nizenyang** [CocoaPods/CocoaPods#9340]
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Malformed+version+number+string+%5B%225.0%22%2C+%225.1%22%5D&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - pod repo lint : ArgumentError - Malformed version number string xcuserdata
   https://github.com/CocoaPods/CocoaPods/issues/1911 [closed] [9 comments]
   30 Mar 2014

**Comment by dnkoutso** [comment]
There is insufficient information for us to diagnose the issue.
