### ISSUE TITLE
ERROR when  pod install

### ISSUE THREAD

**Issue by bhandaribhumin** [CocoaPods/CocoaPods#9342]
Hey team I'm ionic developer, when I was use firebase dependancy I got some weird error. 

> project-103524:ios bhumin3imac$ pod install

Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/bhumin3imac/.gem/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G1012)
       Xcode : 11.2 (11B52)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '11.0'

target '@project' do
	project '@project.xcodeproj'
	pod 'FirebaseMessaging', '~> 2.0.0'
end
```

### Error

```
NoMethodError - undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.13.0/lib/xcodeproj/project.rb:265:in `new_from_plist'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.13.0/lib/xcodeproj/project.rb:212:in `initialize_from_file'
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.13.0/lib/xcodeproj/project.rb:112:in `open'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1098:in `block (2 levels) in inspect_targets_to_integrate'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1097:in `each'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1097:in `block in inspect_targets_to_integrate'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:1092:in `inspect_targets_to_integrate'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Users/bhumin3imac/.gem/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/Users/bhumin3imac/.gem/bin/pod:22:in `load'
/Users/bhumin3imac/.gem/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%5B%5D%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - NoMethodError - undefined method `size' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9295 [closed] [2 comments]
   a week ago

 - NoMethodError - undefined method `real_path`
   https://github.com/CocoaPods/CocoaPods/issues/8082 [open] [13 comments]
   25 Feb 2019

 - NoMethodError - undefined method `each' for nil:NilClass
   https://github.com/CocoaPods/CocoaPods/issues/9239 [closed] [1 comment]
   5 weeks ago

and 206 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60%5B%5D%27%20for%20nil&type=Issues&utf8=✓

**Comment by dnkoutso** [comment]
This is insufficient information for us to diagnose this. Please upload a sample app and fill in the issue template.

**Comment by sumitrvi** [comment]
Any one got solution of this issue

**Comment by mitchiemt11** [comment]
I might be late but in my case, I'm using React Native and I just removed the Podfile.lock and ran `pod install`.
