### ISSUE TITLE
Vendored Dynamic frameworks can't link to project

### ISSUE THREAD

**Issue by QFangM** [CocoaPods/CocoaPods#9344]
## What did you do?

- Create a new pod lib with default demo template.
- Add a dynamic frameworks dependency in demo pod lib's podspec using vendored_frameworks
- Podfile using use_frameworks!.
- Exec Pod install 
- Build or archive the project.

## What did you expect to happen?

The new pod lib can use the vendored framework and the project can be build success.

## What happened instead?

when i use cocoapods > 1.5.3 while have the follow error as follow. but when i use cocoapods 1.5.3 all are correct. But i create a demo dynamic framework(TestFramework.framework) it is right in all version. The vendor framework QiotsSDK.framework will have this error.

> Undefined symbols for architecture arm64:
>  "_OBJC_CLASS_$_QHCamLivePlayer", referenced from:
>      objc-class-ref in BHTools.o
> ld: symbol(s) not found for architecture arm64

found the cocoapods > 1.5.3 OTHER_LDFLAGS are create in a wrong place, it create in poddemo_example OTHER_LDFLAGS = $(inherited) -framework "QiotsSDK" -framework "TestFramework" -framework "poddemo", This link macro should create in poddemo.xcconfig

## CocoaPods Environment

CocoaPods : 1.8.4
Mac os： 10.2
ruby : 2.3.7p456

## Project that demonstrates the issue
demo project
[https://github.com/QFangM/poddemo.git](https://github.com/QFangM/poddemo.git)

**Comment by lifely** [comment]
What your podspec is defining is a realm `cocoapods`, including two `vendored` framework.
However you're not telling anyone to link w/ theses frameworks

you need to add the following line to your `poddemo.podspec`:
> `s.frameworks = 'QiotsSDK', 'TestFramework'`

this will require cocoapods to link `Poddemo` w/ both `QiotsSDK` and `TestFramework`

**Comment by dnkoutso** [comment]
Thats not correct. You want `s.vendored_frameworks` as the `s.frameworks` is used for _system_ frameworks and not vendored ones.
