### ISSUE TITLE
Openssl_Grpc.framework not signed with error: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by repollo** [CocoaPods/CocoaPods#9345]
../Library/Developer/Xcode/DerivedData/Runner-egeqnflybdvurjdboxfmmcwdwkhy/Build/Products/Debug-iphonesimulator/Runner.app/Frameworks/openssl_grpc.framework: code object is not signed at all

In architecture: x86_64
**Command PhaseScriptExecution failed with a nonzero exit code**

What should I be looking for? I don't understand cocoas-pods so I'm really lost. Im trying to build a flutter app with Cloud Firestore integration, here are the versions and flutter doctor:

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/reymarrero/Developer/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/reymarrero/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

Can anyone point in the right direction?

**Comment by dnkoutso** [comment]
Seems like an issue with Flutter, please file an issue with them first. Going to preemptively close as we get a ton of issues lately.

**Comment by repollo** [comment]
Thanks for the quick response. Probably you guys are getting a ton of attention because of the flutter project? Maybe there's a market around there, hehe. Anyways thanks, I'll be doing a post in the flutter project.

**Comment by dnkoutso** [comment]
thats true! @repollo if we do identify an issue with CocoaPods library itself I _will_ re-open this!
