### ISSUE TITLE
Pod Update is removing “Target Support Files”

### ISSUE THREAD

**Issue by usama-shafiq** [CocoaPods/CocoaPods#9349]
After running a 'pod update', the project will not compile. Here is what I've noticed. The update itself appears to run fine, just like normal. I did notice that some of the files in 'Pods/Target Support Files' have been removed.

When I attempt to run, I get an error :
**dyld: Library not loaded: @rpath/RevealServer.framework/RevealServer
  Referenced from:**

**Comment by dnkoutso** [comment]
Please fill in the issue template and upload a sample app. I will re-open this issue once this is done as we get a lot of issues currently.
