### ISSUE TITLE
Update #4989 to indicate that issue with specs repo download speed can possibly be resolved by changing CDN

### ISSUE THREAD

**Issue by IanKemp** [CocoaPods/CocoaPods#9350]
The second result for Googling "cocoapods slow download" is #4989, which has a comment at the top of the issue suggesting that affected users run some git commands to work around the issue. However, in CocoaPods 1.7.2 [the issue was fixed for good with the introduction of a CDN](https://blog.cocoapods.org/CocoaPods-1.7.2/) which makes those git commands unnecessary for users on that or a later version.

Given the popularity of #4989 I suggest you edit it to include something along these lines at the top of the issue:

"If you're experiencing this issue with CocoaPods >= 1.7.2, please read the announcement and follow the instructions at https://blog.cocoapods.org/CocoaPods-1.7.2/#usage to resolve it. If after doing so you still encounter slow speeds, please create a new issue in this repository."

(I'm aware that the 1.7.2 announcement including CDN is 5th in the Google results list, but many people either won't read that far, or will skip over it as it does not at face value appear to offer a solution to the problem.)

**Comment by dnkoutso** [comment]
Good point! Done.
