### ISSUE TITLE
How to delete a remote private pod spec version which had already been `pod repo push`?

### ISSUE THREAD

**Issue by MrBoog** [CocoaPods/CocoaPods#9351]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod repo remove `spec_name`

## What did you expect to happen?

remove a specific remote private pod version

## What happened instead?

cannot remove remote pod version

## CocoaPods Environment

 CocoaPods : 1.8.0

## Project that demonstrates the issue

is it possible or acceptable that allows developers to delete a private repo pod version which has already been published?

**Comment by paulb777** [comment]
Use git commands. See https://stackoverflow.com/a/58187254/556617
