### ISSUE TITLE
how can I make Xcode Group looks like normal

### ISSUE THREAD

**Issue by xyqjay** [CocoaPods/CocoaPods#9356]
there a lot of " .. " " .. " " .. " 
how can I remove those " .. " 
![image](https://user-images.githubusercontent.com/6870026/69128035-6ca91e80-0ae6-11ea-97c4-cf2d90e53a6a.png)

my podfile:
`pod 'SFFundation', :path => '~/GitHome1/SFFundation'`
my podspec:
```
  s.subspec 'Core' do |core|
    core.source_files = 'SFFundation/Classes/**/*.{swift,h,m,c}'
 end
```

my SFFundation folder tree:
```
.
├── SFFundation
│   ├── Classes
│   │   ├── AD
│   │   │   ├── ADManager.swift
│   │   │   ├── ADRequestModel.swift
│   │   │   └── ADResponseModel.swift
│   │   ├── BaseClass
│   │   │   ├── BaseCell.swift
│   │   │   ├── BaseRouterUrlProtocol.swift
```

**Comment by dnkoutso** [comment]
You cannot. This is where the local pod is relative to your folder which is using $HOME_DIR or `~`.
