### ISSUE TITLE
How to delete open source library

### ISSUE THREAD

**Issue by yunjinghui123** [CocoaPods/CocoaPods#9360]
## What did you do?

ℹ Please replace these two lines with what you did.  
 Run `pod trunk me`
- Name:     xxx
  - Email:    xxx@xx.com
  - Since:    November 23rd, 2017 20:39
  - Pods:
    - PH
    - xx
    - xx
## What did you expect to happen?
- Pods:
 -PH is no longer used, I hope that when I run `pod trunk me` :
- Name:     xxx
  - Email:    xxx@xx.com
  - Since:    November 23rd, 2017 20:39
  - Pods:
    - xx(no PH，delete PH)
    - xx
    - xx

This is a library I submitted, but I don't want to use it, what should I do?

**Comment by dnkoutso** [comment]
I do not think deletions are possible to prevent clients of pods from breaking.

**Comment by dnkoutso** [comment]
Going to close as there is no action currently for us to take.

**Comment by yunjinghui123** [comment]
This means that there is no way to delete it?

**Comment by dnkoutso** [comment]
Nope.

**Comment by yunjinghui123** [comment]
So what should I do to delete it
