### ISSUE TITLE
Aggregate Target will not regenerate when increment pod install for resources changes

### ISSUE THREAD

**Issue by SolaWing** [CocoaPods/CocoaPods#9361]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

with 
```
install! 'cocoapods',
    :incremental_installation => true,
    :generate_multiple_pod_projects => true,
```
upgrade a pod, which change resources path

## What did you expect to happen?

aggregate target got regenerate, and the Pods-XXX-resources.sh script copy the correct resource.

## What happened instead?

Pods-XXX-resources.sh did not change, and still copy the non-exist old path.

I have seen in target_cache_key.rb, aggregate target regenerate only when BUILD_SETTINGS_CHECKSUM changes. but resources change will not cause it change.

## CocoaPods Environment

cocoapod 1.7.5

**Comment by dnkoutso** [comment]
Did you try 1.8.4? I believe it was fixed there.

**Comment by dnkoutso** [comment]
Also please attach a sample app if possible for us to reproduce. cc @sebastianv1
