### ISSUE TITLE
How to specify directory for pod stuff when running “pod install” command

### ISSUE THREAD

**Issue by igorek9191** [CocoaPods/CocoaPods#9362]
I'm installing pods in Jenkins pipeline, here the peace of pipeline code

```
npm install -g yarn
npm install -g pod
yarn cache clean
yarn install --network-concurrency 1
cd ios
pod install
```
After pod install command in the output I see such warning:

> Hello! It seems it's your first time running pod on this machine. Please specify a directory for pod to put stuff in. - Make sure your account has full access to that directory. - You can use relative paths (resolved against your cwd).

So, how to specify the directory for pod stuff ?

**Comment by dnkoutso** [comment]
That is a different package and not cocoapods.

Use `npm install cocoapods` maybe?

There is no such message in our codebase.
