### ISSUE TITLE
pod search can't find the library

### ISSUE THREAD

**Issue by yunjinghui123** [CocoaPods/CocoaPods#9366]
## What did you do?
Run `pod search AFNetworking`
[!] Unable to find a pod with name, author, summary, or description matching `AFNetworking`

Run 'pod repo list'
0 repos

## What did you expect to happen?
Find the version of AFNetworking

## What happened instead?
I can't find it when I search in the terminal.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /Users/yunjinghui/.rvm/rubies/ruby-2.6.3/lib
Repositories : 
```

### Installation Source

```
Executable Path: /Users/yunjinghui/.rvm/rubies/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by igor-makarov** [comment]
@dnkoutso I think we need to bring setup back, what do you think?

**Comment by dnkoutso** [comment]
I think we had fixed this? We can of course bring it back to just add `trunk`.

**Comment by yunjinghui123** [comment]
Do I need to wait for the next version update to use

**Comment by yunjinghui123** [comment]
Actually, I just want to know how to solve this problem and what should I do

**Comment by igor-makarov** [comment]
If you `pod install`, it will cause the `trunk` repo to get added. Then you can search without problem.

**Comment by yunjinghui123** [comment]
I created a new project and 'pod install'
Analyzing dependencies
Adding spec repo `trunk` with CDN` https: // cdn.cocoapods.org / `
Downloading dependencies
Installing AFNetworking (3.2.1)

It can also be found, but the speed is very slow, and the previous version is not updated as fast as possible. Maybe it is the reason of the Chinese network?
Obviously, this version is not as exciting as expected.

**Comment by yunjinghui123** [comment]
I found something very unfortunate.
’pod search xx‘ I can find other people's libs, but I can't find my own. I submitted a git version and it worked, but I just couldn't find my own，like this:
Updating spec repo `trunk`

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  YJHKeyboardAnimation (0.0.6) successfully published
 📅  November 26th, 01:23
 🌎  https://cocoapods.org/pods/YJHKeyboardAnimation
 👍  Tell your friends!
--------------------------------------------------------------------------------
yunjinghui@bogon % pod search YJHKeyboardAnimation
[!] Unable to find a pod with name, author, summary, or description matching `YJHKeyboardAnimation`

**Comment by igor-makarov** [comment]
That might be the search indexer not being updated due to a bug @dnkoutso @Haroenv.

**Comment by yunjinghui123** [comment]
May be a bug, but i can update it in my project.

pod update YJHKeyboardAnimation
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing YJHKeyboardAnimation 0.0.6 (was 0.0.5 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Generating Pods project
Integrating client project
Pod installation complete! There are 46 dependencies from the Podfile and 50 total pods installed.

**Comment by igor-makarov** [comment]
Yes, just the web search is having an indexing issue.

**Comment by yunjinghui123** [comment]
Waiting for repair.

**Comment by Haroenv** [comment]
Sorry, there's indeed a bug in the indexer, it seems that the runner isn't actually running, although it's successfully finding what the new packages should be.

**Comment by yunjinghui123** [comment]
I suspect there are some issues with pod update too.
I submitted an update version is 0.0.8，then in my project:
pod update YJHKeyboardAnimation
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "YJHKeyboardAnimation":
  In Podfile:
    YJHKeyboardAnimation (~> 0.0.8)
None of your spec sources contain a spec satisfying the dependency: `YJHKeyboardAnimation (~> 0.0.8)`.
You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
It is not update.

Then I submitted another update version 0.0.9, 'pod update', and I found that it was OK again. em m..., strange!
pod update YJHKeyboardAnimation
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing YJHKeyboardAnimation 0.0.9 (was 0.0.7 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Generating Pods project
Integrating client project

**Comment by igor-makarov** [comment]
I'm thinking that's just a CDN build delay. The published pod doesn't appear on the CDN source the same instance it's published, if there are several pods published at the same time, it can take a while for the CDN build to finish.

**Comment by yunjinghui123** [comment]
Maybe I should wait for a while before updating.

**Comment by gcox** [comment]
Issue for the indexer problem: https://github.com/CocoaPods/indexer.cocoapods.org/issues/11

**Comment by Haroenv** [comment]
Sorry for being slow on fixing this, but I have finally found the root cause. This issue can be closed
