### ISSUE TITLE
Pods Template end - oh no, an error occurred

### ISSUE THREAD

**Issue by goldengel** [CocoaPods/CocoaPods#9367]
Error message on Mac

Ionic cordova

> Installing "cordova-plugin-androidx-adapter" for ios
> Failed to install 'cordova-plugin-firebasex': undefined
> Failed to restore plugin "cordova-plugin-firebasex" from config.xml. You might need to try adding it again. Error: /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

> 
> Use Swift language version 5
> [ERROR] An error occurred while running subprocess cordova.
>         
>         cordova prepare exited with exit code 1.
>         
>         Re-running this command with the --verbose flag may provide more information.
> Gunthers-Air:sonnenbraeu foxdev$ cd platforms/ios
> Gunthers-Air:ios foxdev$ pod install
> 
> ――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> ### Command
> 
> ```
> /usr/local/bin/pod install
> ```
> 
> ### Report
> 
> * What did you do?
> 
> * What did you expect to happen?
> 
> * What happened instead?
> 
> 
> ### Stack
> 
> ```
>    CocoaPods : 1.8.4
>         Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
>     RubyGems : 3.0.3
>         Host : Mac OS X 10.15.1 (19B88)
>        Xcode : 11.2.1 (11B500)
>          Git : git version 2.21.0 (Apple Git-122.2)
> Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
> Repositories : trunk - CDN - https://cdn.cocoapods.org/
> ```
> 
> ### Plugins
> 
> ```
> cocoapods-deintegrate  : 1.0.4
> cocoapods-dependencies : 1.3.0
> cocoapods-plugins      : 1.0.0
> cocoapods-search       : 1.0.0
> cocoapods-stats        : 1.1.0
> cocoapods-trunk        : 1.4.1
> cocoapods-try          : 1.1.0
> ```
> 
> ### Podfile
> 
> ```ruby
> # DO NOT MODIFY -- auto-generated by Apache Cordova
> source 'https://cdn.cocoapods.org/'
> platform :ios, '11.0'
> use_frameworks!
> target 'Sonnenbraeu' do
>         project 'Sonnenbraeu.xcodeproj'
>         pod 'Firebase/Core', '6.11.0'
>         pod 'Firebase/Auth', '6.11.0'
>         pod 'Firebase/Messaging', '6.11.0'
>         pod 'Firebase/Performance', '6.11.0'
>         pod 'Firebase/RemoteConfig', '6.11.0'
>         pod 'Fabric', '1.10.2'
>         pod 'Crashlytics', '3.14.0'
> end
> ```
> 
> ### Error
> 
> ```
> Errno::EACCES - Permission denied @ dir_s_mkdir - /Users/foxdev/iCloud Drive (Archiv)/Documents/development/sonnenbraeu/platforms/ios/Pods
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir'
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `each'
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sandbox.rb:66:in `initialize'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:193:in `new'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:193:in `sandbox'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:140:in `installer_for_config'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:47:in `run'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'
> ```
> 
> ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> [!] Oh no, an error occurred.
> 
> Search for existing GitHub issues similar to yours:
> https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Ffoxdev%2FiCloud+Drive+%28Archiv%29%2FDocuments%2Fdevelopment%2Fsonnenbraeu%2Fplatforms%2Fios%2FPods&type=Issues
>

**Comment by dnkoutso** [comment]
This looks like a local system permission issue and not a bug in CocoaPods. I recommend fixing user permissions before invoking CocoaPods.

**Comment by goldengel** [comment]
Its no permission issue. Permission is give.

**Comment by deepakiosdev** [comment]
I am also facing same issue. Getting this issue only one repo others are fine.
