### ISSUE TITLE
pod install is taking over 10 minutes for the clone step

### ISSUE THREAD

**Issue by owattenmaker** [CocoaPods/CocoaPods#9368]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run `pod install` on a brand new environment

## What did you expect to happen?

install all pod dependencies correctly within a reasonable time frame

## What happened instead?

takes over 11 minutes for the 
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`
step to complete. this is because of the massive version history inside of the Spec folder. what i'd like the option to do is pass an (optional) flag to pod install to ensure that it clones with depth of 1, which dramatically reduces the time taken for the repo download, as you can see here:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/10779381/69672717-89e16e00-104d-11ea-96df-cfd95c34ac5d.png">

I am running this inside of a CI environment where it has to rebuild the world every time it runs. The increased time for this cloning step has recently passed 10 minutes, which causes the build to time out since it thinks that it stalled. I could tell our CI to wait for additional time as a quick workaround, but if the entire git tree isn't needed for the repo-update step, there should really be an option since I don't think waiting an extra 10 minutes just for fun is a good use of anyones time.

If the entire git tree is needed, then please tell me and I can look like a fool for creating this request :)

**Comment by dnkoutso** [comment]
Yes the repo is huge and it is intentionally needing all of the repo (eep clone compared to shallow).

Please use CocoaPods 1.8.4 which uses CDN as the default repo and remove the master specs repo from your `Podfile`.

**Comment by dnkoutso** [comment]
Read more here http://blog.cocoapods.org/CocoaPods-1.8.0-beta/

**Comment by owattenmaker** [comment]
ah, thank you. i'm using 1.7 so that would indeed explain it
