### ISSUE TITLE
pod update duplicate file

### ISSUE THREAD

**Issue by Blankz** [CocoaPods/CocoaPods#9369]
Using CocoaPods <= 1.8.4 with home-brew

Using Xcode 11.2.1: 

when I use pod update 

pod file will duplicate file  like awss3 2.h

**Comment by dnkoutso** [comment]
This is insufficient information for us to diagnose the issue. Please fill in the template and also provide a sample app.

**Comment by Blankz** [comment]
when I used pod update 

![Screen Shot 2562-11-27 at 11 16 04](https://user-images.githubusercontent.com/10516174/69693337-99bd8880-1107-11ea-9134-5eff23d03a61.png)
![Screen Shot 2562-11-27 at 11 17 35](https://user-images.githubusercontent.com/10516174/69693342-9f1ad300-1107-11ea-8d00-f4cf9e252235.png)

**Comment by eschos24** [comment]
I am having the exact same issue. This seems to happen randomly; I can't figure out what causes it or what exactly the correlation is/how to reproduce it, but it happens frequently and the best fix I have found so far is to run `pod deintegrate` and then run `pod install` right after.

**Comment by Adrimi** [comment]
What can i tell this issue can happen randomly if you perform `pod isntall` or `pod update` without closing XCode. Just remember to close xcode before using cocoapods
