### ISSUE TITLE
I have an error when I compile my app in another iOS.

### ISSUE THREAD

**Issue by crianpiro** [CocoaPods/CocoaPods#9375]
This is the error I have:

/Users/tecun/development/flutter_Soft_1/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh: line 43: source: unbound variable.

And this is the code the error refers to:

if [ -L "${source}" ]; then
    echo "Symlinked..."
    source="$(readlink "${source}")"
  fi

I've tried to run "pod install" to fix it but I got this:

[!] No podspec found for `Flutter` in `.symlinks/flutter/ios`

**Comment by dnkoutso** [comment]
This appears to be a flutter setup issue  and not cocoapods issue.
