### ISSUE TITLE
Can't run unit tests with auto-generated app host

### ISSUE THREAD

**Issue by michaeleisel** [CocoaPods/CocoaPods#9377]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I installed a Cocoapod, ZippyJSON, and tried to run unit tests on my iPhone with an app host. However, it didn't work. I got the following error:
```
Unable to install "AppHost-ZippyJSON-Unit-Tests"

The certificate used to sign "AppHost-ZippyJSON-Unit-Tests" has either expired or has been revoked. An updated certificate is required to sign and install the application.
```

### Stack

```
   CocoaPods : 1.8.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E2034)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Podfile for the consumer of ZippyJSON:
```
target 'ZipPod' do
  use_frameworks!
  pod 'ZippyJSON', :path => '../ZippyJSON', :testspecs => ['Tests'] 
  pod 'ZippyJSONCFamily', :path => '../ZippyJSONCFamily'
end
```

with ZippyJSON at 49386ccc53c19e59ea0c907ce1eca4ef8edba55e on branch me-v1-1, and ZippyJSONCFamily at d0ab43122addca0d16c1a2ecb420f1671b9708af on its own branch me-v1-1

**Comment by dnkoutso** [comment]
I cant clone on `49386ccc53c19e59ea0c907ce1eca4ef8edba55e`

```
[!] Error installing ZippyJSON
[!] Failed to download 'ZippyJSON': [!] /usr/local/bin/git -C /var/folders/g7/83vp4gbx2q58k1wd02f17b4r0000gn/T/d20191203-69433-1t5uoc7 checkout --quiet 49386ccc53c19e59ea0c907ce1eca4ef8edba55e

fatal: reference is not a tree: 49386ccc53c19e59ea0c907ce1eca4ef8edba55e
```

I did try latest version though with a test spec and I was able to run the tests successfully. Can you please upload a sample app with the `pod install` completed and the `Pods/` folder?

**Comment by ahmedAlmasri** [comment]
I have a same issue when try to run the unit test on real device

**Comment by michaeleisel** [comment]
@dnkoutso did you run the tests on a real device?
