### ISSUE TITLE
Unable to customize schemes before projects are written.

### ISSUE THREAD

**Issue by yusufoos** [CocoaPods/CocoaPods#9379]
🌈 We would like to modify the visibility of specific schemes before our projects are written/saved to disk.

Unfortunately, this is not supported by podfile post install hooks because `projects_writer.write!` overwrites the visibility of all the schemes.

https://github.com/CocoaPods/CocoaPods/blob/c1292cca13a8afa067e5157856b73cb0a65d6da4/lib/cocoapods/installer.rb#L322-L326

https://github.com/CocoaPods/CocoaPods/blob/c1292cca13a8afa067e5157856b73cb0a65d6da4/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb#L38-L59

Ideally we would `run_podfile_post_install_hooks` after the PodsProjectWriter calls `recreate_user_schemes` on all the projects but before it calls save on all the projects.

I'd be willing to make a PR if this approach is acceptable.

Thanks!

**Comment by dnkoutso** [comment]
We do not want to move that currently as it will break a ton of projects which they will need to add `project.save` to their hooks. 

Additionally we actually prefer the user to be able to modify the project _before_ `project.save` from CocoaPods is called because that would only write the project once which can be a slow operation and also cause various Xcode issues while its open.

**Comment by yusufoos** [comment]
I think you misunderstood, I'm proposing moving the hook to _before_ project.save is called but _after_ `recreate_user_schemes` is called. It would looks something like this:

```
def write! 
   cleanup_projects(projects) 
  
   projects.each do |project| 
     UI.message "- Writing Xcode project file to #{UI.path project.path}" do 
       library_product_types = [:framework, :dynamic_library, :static_library] 
       results_by_native_target = Hash[pod_target_installation_results.map do |_, result| 
         [result.native_target, result] 
       end] 
       project.recreate_user_schemes(false) do |scheme, target| 
         next unless target.respond_to?(:symbol_type) 
         next unless library_product_types.include? target.symbol_type 
         installation_result = results_by_native_target[target] 
         next unless installation_result 
         installation_result.test_native_targets.each do |test_native_target| 
           scheme.add_test_target(test_native_target) 
         end 
       end 
     end 
   end

   run_podfile_post_install_hooks

   projects.each do |project| 
     project.save
   end

end 
```

**Comment by dnkoutso** [comment]
ah...hmmm I think that would work we can try opening up a PR and see if tests fail for starters.
