### ISSUE TITLE
Conflict between header files with same names in different pods

### ISSUE THREAD

**Issue by jbelkins** [CocoaPods/CocoaPods#9387]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Imported a Cocoapod with a public header file (`chord.h`) that matches the name of a public header file in another installed pod.

## What did you expect to happen?

I expected the project to build and run successfully.

## What happened instead?

The project fails with `chord.h` not found:
```
/Users/josh/Code/WTFVerovio/Pods/Verovio/src/view_element.cpp:23:10: fatal error: 'chord.h' file not found
#include "chord.h"
         ^~~~~~~~~
```

(If I rename the `chord.h` header file in one of the projects or remove either pod from the Podfile, it builds successfully.)

Not sure if this is due to configuration of either my project or my pods' podspecs, or an issue with CocoaPods itself.  I know something weird is going on with header search paths, but I can't put my finger on where I'm going wrong.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /Users/josh/.rvm/rubies/ruby-2.6.5/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 6f1f8ebf1d57b3d23f25897f8a1ba7c7bd89c2ee
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/josh/.rvm/gems/ruby-2.6.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '13.0'

use_frameworks!

target 'WTFVerovio' do
  pod 'Verovio'
  pod 'HeaderDups', git: "https://github.com/jbelkins/HeaderDups.git", tag: '0.0.4'
end
```

## Project that demonstrates the issue

https://github.com/jbelkins/WTFVerovio.git (master branch)

**Comment by lpugin** [comment]
It is quite weird but when I build your example with Verovio pull from a local copy it works:

```
platform :ios, '13.0'

use_frameworks!

target 'WTFVerovio' do
  pod 'Verovio', :path => '/Users/laurent/projects/verovio_develop'
  pod 'HeaderDups', git: "https://github.com/jbelkins/HeaderDups.git", tag: '0.0.4'
end
```

(The local copy is the current develop branch)

**Comment by irons163** [comment]
I meet the same issue, any update?

Just guess, the xxx-umbrella.h import all of the headers even the headers you set as private, so of course the duplicate name issue in different pods would happened.

CocoaPods : 1.8.4

**Comment by jbelkins** [comment]
With the latest Verovio podspec, I can no longer reproduce this.  Closing.
