### ISSUE TITLE
Add option to select test specs for `pod lib lint`

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#9392]
Currently, it is only possible to test all of the test_specs or none with `--skip-tests`.  It would be nice to be able to choose which test specs to run.

For example, for a pod that has both Swift and Objective C tests, it would be useful to be able to only run the Objective C tests when `--use-libraries` is also set.

**Comment by dnkoutso** [comment]
Yeap, should be easy to add!
