### ISSUE TITLE
Do not link AppKit/Cocoa for macOS Command Line

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#9394]
I have a macOS command line project, and it will not link the `AppKit.framework`. But the CocoaPods will always link the `AppKit.framework` in the `Frameworks and Libraries` for every pod target, and write `#import <Cocoa/Cocoa.h>` into the pch file for every pod target.

I want to only link the `Foundation.framework` and write the `#import <Foundation/Foundation.h>` to pch file. How to do?

**Comment by Whirlwind** [comment]
I found the `CocoaLumjack` project, there is a `DD_CLI` to disable `Cocoa` framework:
```
#ifndef DD_CLI
#import <Cocoa/Cocoa.h>
#end
```
But the CocoaPods add the Cocoa.framework in the Pod Target, it will make the CocoaLumjack always link the Cocoa.framewk. It is too bad.

**Comment by paulb777** [comment]
A workaround would be to add `s.prefix_header_file = false` to the podspec to completely disable the pch generation. You would then need to add the Foundation manually where needed.

**Comment by Whirlwind** [comment]
No, it is not a good workaround.

First,  I could not modified the podspec! I could only modify the Podfile, right?
Then, the `prefix_header_file` will be used by some pods.
Third, the `Cocoa.framework` still be added in the `Frameworks and Libraries` of every pod target.
