### ISSUE TITLE
in development pods, i can't auto complete the full header file name when i type import, can i solve this?

### ISSUE THREAD

**Issue by QDFish** [CocoaPods/CocoaPods#9398]
<!--
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
when i need import a header file that not in the same file
## What did you expect to happen?
the xcode can help me to complete the the full header file, e.g. i type import <xx>, xcode can auto show the <xx/xx.h>
## What happened instead?
it doesn't work

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
^CTraceback (most recent call last):
	20: from /usr/local/bin/pod:23:in `<main>'
	19: from /usr/local/bin/pod:23:in `load'
	18: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:36:in `<top (required)>'
	17: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods.rb:17:in `<top (required)>'
	14: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods.rb:30:in `<module:Pod>'
	13: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:1:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface/error_report.rb:5:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 5: from /Library/Ruby/Gems/2.6.0/gems/gh_inspector-1.1.3/lib/gh_inspector.rb:3:in `<top (required)>'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /Library/Ruby/Gems/2.6.0/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:1:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': Interrupt

➜  Example git:(feature/forum/2019_50_51week) ✗ pod env | pbcopy
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
➜  Example git:(feature/forum/2019_50_51week) ✗ pod env
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.1 (19B2106)
       Xcode :  ()
         Git : git version 2.23.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ 811053bcd0a5811f30ed7605063bae35d4770521
               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 97c83d8c0cdbad29c54383b9718260a57b40ad63
               taqu-ios-hbspecs - git - http://git.internal.taqu.cn/ios/HBSpecs.git @ a4d562177f5c966e75d9e0e9a1e8b8feeb2e875f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-binary      : 0.4.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.internal.taqu.cn/ios/HBSpecs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

#plugin 'cocoapods-binary'

use_frameworks!

#all_binary!

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '9.0'

target 'ForumModule_Example' do

  pod 'ForumModule', :path => '../../ForumModule'
  pod 'TouchCommon', :path => '../../TouchCommon'
  pod 'HBPublic', :git => 'http://git.internal.taqu.cn/ios/HBPublic.git' , :branch => 'develop'
  pod 'XHBUIKit', :git => 'http://git.internal.taqu.cn/ios/XHBUIKit.git' , :branch => 'develop'
  pod 'XHBFrame', :git => 'http://git.internal.taqu.cn/ios/XHBFrame.git', :branch => 'develop'
  pod 'XHBTool' , :git => 'http://git.internal.taqu.cn/ios/XHBTool.git'  , :branch => 'develop'
  pod 'XHBVideoBeauty', :git => 'http://git.internal.taqu.cn/ios/XHBVideoBeauty.git', :branch => 'master'
  pod 'XHBBusiness/XHBLaunchAD', :git => 'http://git.internal.taqu.cn/ios/XHBBusiness.git', :branch => 'master'
  pod 'YYModel' , :git => 'https://github.com/zxwo0o/YYModel.git'
  pod 'FLEX'

end

**Comment by dnkoutso** [comment]
This is insufficient template. Please provide a sample app and something that we can reproduce this problem with.

I will re-open this issue once a project the issue template are filled.

**Comment by QDFish** [comment]
if the framework can't help it ? how can i let module, such as ForumModule as library form so i can auto complete the #import

**Comment by QDFish** [comment]
> if the framework can't help it ? how can i let module, such as ForumModule as library form so i can auto complete the #import

other basic pod use framework,

**Comment by QDFish** [comment]
> This is insufficient template. Please provide a sample app and something that we can reproduce this problem with.
> 
> I will re-open this issue once a project the issue template are filled.

the issue template is filled, can you re-open it?
