### ISSUE TITLE
Update activesupport dependency

### ISSUE THREAD

**Issue by waiting-for-dev** [CocoaPods/CocoaPods#9404]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

Currently `CocoaPods` is the bottleneck to update `rails` gem to version 6 in NixOS operating system. In NixOS, all packaged gems need to be compatible with one each other. `CocoaPods` depends on `active_support` less than 5, which forces rails to be still in version 4. See this link for further reference:

https://github.com/NixOS/nixpkgs/pull/74925#issuecomment-564142662

Thanks!

**Comment by dnkoutso** [comment]
Not sure why its not allowing 5.x and the only comment i found is:
```
gem 'activesupport', '>= 4.0.2', '!= 4.2.11.12', '< 5' # Pinned < 5 to ensure we're speccing 4.x.x
```

In CocoaPods/Core.

**Comment by waiting-for-dev** [comment]
That's it, `> 5` doesn't allow version 5 or higher. Ideally, we need last version so that NixOs has no problems.

**Comment by amorde** [comment]
Meant to comment here a while ago, but this is because we still support Ruby 2.0. Once we drop support for 2.0 we can bump the dependency.

**Comment by waiting-for-dev** [comment]
Any roadmap? Ruby itself ended support for 2.0 in 2016.

**Comment by amorde** [comment]
We are still in a beta period for 1.9

**Comment by shepting** [comment]
We would love for this to be bumped as well. The `activesupport` deprecation logs make our users worried.

**Comment by dnkoutso** [comment]
I dont think the 1.10 release drops Ruby 2.0 so far but I think the next one will.

**Comment by rajivshah3** [comment]
A vulnerability in `activesupport` was disclosed last week: https://app.snyk.io/vuln/SNYK-RUBY-ACTIVESUPPORT-569598

**Comment by dnkoutso** [comment]
Once #9821 lands this should be closed.
