### ISSUE TITLE
pod search error

### ISSUE THREAD

**Issue by WeiCY** [CocoaPods/CocoaPods#9409]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod search afnet

## What did you expect to happen?

I hope it can correctly search out the corresponding library

## What happened instead?

<img width="621" alt="image" src="https://user-images.githubusercontent.com/17762251/70860573-50ba6080-1f5e-11ea-870e-207a34f58a9b.png">

## CocoaPods Environment

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test

pod 'SDWebImage'


  target 'testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testUITests' do
    # Pods for testing
  end

end
```

**Comment by dnkoutso** [comment]
This seems a problem with you reaching our CDN. Please switch up to use the old `git` based solution.

**Comment by WeiCY** [comment]
I used cocoapods a few days ago is normal, but I can’t use it since I updated the latest system 10.15.2 (19C57). What other solutions can I use besides switching back to the old version?

**Comment by dnkoutso** [comment]
This seems like a network issue though so I dont think there is much we can do here.
