### ISSUE TITLE
Issue with vendored ".framework.dSYM" files

### ISSUE THREAD

**Issue by kylefleming** [CocoaPods/CocoaPods#9419]
🌈

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## Description

This bug report is related to vendored `.framework.dSYM` files. The issue only occurs when using the new build system, and only when the scheme being run contains more than 1 target with the `[CP] Embed Pods Frameworks` script phase (e.g. you have a separate UI Test Host and your scheme is building both the main app and the UI Test Host).

## Error

This is an example of the error. This was produced by the sample app linked at the bottom of this ticket.
```
error: Multiple commands produce '/Users/kyle/Library/Developer/Xcode/DerivedData/ClientApp-hcaxpttrbfuuzofmmcsdxpvgmvqh/Build/Products/Debug-iphonesimulator/VendoredFramework.framework.dSYM':
1) That command depends on command in Target 'ClientApp' (project 'ClientApp'): script phase “[CP] Embed Pods Frameworks”
2) That command depends on command in Target 'ClientAppUITestHost' (project 'ClientApp'): script phase “[CP] Embed Pods Frameworks”


warning: duplicate output file '/Users/kyle/Library/Developer/Xcode/DerivedData/ClientApp-hcaxpttrbfuuzofmmcsdxpvgmvqh/Build/Products/Debug-iphonesimulator/VendoredFramework.framework.dSYM' on task: PhaseScriptExecution [CP] Embed Pods Frameworks /Users/kyle/Library/Developer/Xcode/DerivedData/ClientApp-hcaxpttrbfuuzofmmcsdxpvgmvqh/Build/Intermediates.noindex/ClientApp.build/Debug-iphonesimulator/ClientAppUITestHost.build/Script-0B91F756715E69CE2E47BA72.sh (in target 'ClientAppUITestHost' from project 'ClientApp')
```

## Discussion

The issue at hand can be summarized as follows:
* Under Xcode's "Modern Build System", each output file in the build directory must have one and only 1 target that produces it (in the context of the scheme that's being run).
* CocoaPods adds a `[CP] Embed Pods Frameworks` script phase that copies the vendored `.framework.dSYM` files to the `Build/Products` directory.
* Xcode treats these output product as being created by the target that the script phase belongs to. Often this target is the final app (rather than Xcode treating the output product as being created by the appropriate pod target within the `Pods` project).
* When you invoke a scheme that has more than 1 target with this script phase, Xcode doesn't know if it should invoke target A or target B in order to produce that `.framework.dSYM` file.

Notes:
* This doesn't affect `.framework` files because those are copied into the `.app` bundle and there are distinct `.app` bundles for each target. Since the `.framework.dSYM` exists side-by-side to the `.app` bundles, this causes a clash.

## Possible Solutions

* Rather than having the `[CP] Embed Pods Frameworks` script phase copy the vendored `.framework.dSYM` files to the `Products` directory, instead have the corresponding pod target within the `Pods` project move them. This would solve the issue because then both targets would depend on the same pod target and Xcode would know to only run the pod target once.
* Change the output location of the `.framework.dSYM` files within the `Products` directory to be distinct per target containing the `[CP] Embed Pods Frameworks` script phase. This would solve the issue by having separate `.framework.dSYM` locations per target, allowing Xcode to know exactly which target is responsible for producing each `.framework.dSYM` file within the `Products` directory.

### For end-users:
* Adjust schemes so that none of them are trying to build more than 1 target containing a `[CP] Embed Pods Frameworks` script phase at a time.
* Use Xcode's "Legacy Build System"
* Modify the `Pods/Target Support Files/Pods-<TargetName>/Pods-<TargetName>-frameworks.sh` script in some way after each run of `pod install`.
* Add `install! 'cocoapods', :disable_input_output_paths => true` to the `Podfile`.

### For pod authors:
* Change the pod vendoring the framework to not include `.framework.dSYM` files.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /Users/kyle/.rbenv/versions/2.6.5/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 8d08cb56c3c211bfb8e15bc0a86359545d843dd1
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/kyle/.rbenv/versions/2.6.5/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-repo-update : 0.0.4
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/kylefleming/CocoaPodsVendoredDSYMIssue

## Related Tickets

* https://github.com/CocoaPods/CocoaPods/issues/9185
* https://github.com/CocoaPods/CocoaPods/pull/7166
* https://github.com/CocoaPods/CocoaPods/pull/6536

**Comment by dnkoutso** [comment]
Excellent issue report. Thanks! Curious how is it different from #9185?

**Comment by kylefleming** [comment]
> Curious how is it different from #9185?

They are very possibly caused by the same underlying issue. 

However, #9185 seemed to be describing a more specific use-case (not setting the app host for a unit test). Additionally, there were other reports within that ticket describing similar symptoms, but it seemed there was some uncertainty about whether the reports were related or not.

Ultimately, I created a new ticket because I don't believe the solution presented in the other ticket (https://github.com/CocoaPods/CocoaPods/issues/9185#issuecomment-535571742) would have solved it for the use-cases where I was encountering the issue (which is anytime there is more than 1 target with the `[CP] Embed Pods Frameworks` script phase being built as part of a single scheme, coupled with a vendored `.framework.dSYM` file and using Xcode's "Modern Build System").

**Comment by Leenahp** [comment]
Thank

**Comment by dnkoutso** [comment]
@kylefleming I think https://github.com/CocoaPods/CocoaPods/pull/9547 resolves this. Can you verify?

**Comment by mplorentz** [comment]
This issue is still present for me on CocoaPods version 1.9.1, which includes #9547. @dnkoutso could you reopen this issue?

I tried: 
1. Upgrading to cocoapods 1.9.1
2. `pod deintegrate`
3. `pod install`
4. Delete Derived Data
5. Clean
6. Build & Test

I still get the "Multiple commands produce ....*.dSYM" errors.

**Comment by dnkoutso** [comment]
The issue was auto closed due to inactivity. We did merge a dSYM fix on `master` which would be 1.10.0 but has not been released yet.

Please try https://github.com/CocoaPods/CocoaPods/pull/9547. You can do so using bundler and point to `master` branch.

**Comment by dnkoutso** [comment]
I updated the milestone though

**Comment by mplorentz** [comment]
@dnkoutso thanks! Running through the same steps I listed above with the `master` branch of cocoapods does fix the error for me.

**Comment by mplorentz** [comment]
I installed cocoapods from `master` and ran through the steps to test again. It looks like the `Multiple commands produce *.dSYM` errors are gone, but I still have `Multiple commands produce *.bcsymbolmap`.

@dnkoutso Would it be reasonable for [this function](https://github.com/CocoaPods/CocoaPods/pull/9547/files#diff-38f6da95e04f241c354bdac3cee39386R788) to copy bcsymbolmaps along with the dSYMs?

**Comment by dnkoutso** [comment]
oh interesting @mplorentz maybe `master` did not fix the issue with `bcsymbolmaps`.

Care to make a PR to improve/fix this?

**Comment by mplorentz** [comment]
Sure, I'll take a crack at it.

For anyone else following this: we were using the `:disable_input_output_paths` mitigation for this issue, but found out it causes the `Embed Pods Frameworks` build script to execute on every build, which added about 13 seconds to our compile time. We switched to a bash script that is manually run after `pod install` and removes the dSYMs and bcsymbolmaps from the test target. It looks something like this:

```
sed -i '' '/\.bcsymbolmap$/d' Pods/Target\ Support\ Files/Pods-YourTarget\ Tests/Pods-YourTarget\ Tests-frameworks-Debug-output-files.xcfilelist
sed -i '' '/\.dSYM$/d' Pods/Target\ Support\ Files/Pods-YourTarget\ Tests/Pods-YourTarget\ Tests-frameworks-Debug-output-files.xcfilelist
```
Replace YourTarget with one of the targets listed in the `Multiple commands produce:` error output. It requires that CocoaPods is using .xcfilelists which requires your .xcproject object version to be >50.

**Comment by kylefleming** [comment]
> @kylefleming I think #9547 resolves this. Can you verify?

Looks like it fixes it. Thank you @dnkoutso!
