### ISSUE TITLE
Generated Pods-PROJECTNAME-resources.sh fails when project is loaded from symbolic link directory

### ISSUE THREAD

**Issue by dwsjoquist** [CocoaPods/CocoaPods#9423]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Built project that was loaded from a symbolic link on mac os.

## What did you expect to happen?

Project should build successfully.

## What happened instead?

It fails on these lines:
``` 
# Find all other xcassets (this unfortunately includes those of path pods and other targets).
  OTHER_XCASSETS=$(find "$PWD" -iname "*.xcassets" -type d)
```

The problem as I understand it is that the `find` behaves differently with symbolic links. If I load the project from the full, normal path, it builds fine.

The $PWD value is something like this: `/d/mydir` and if I temporarily change the script to this, it works fine:

```
OTHER_XCASSETS=$(find -L "$PWD" -iname "*.xcassets" -type d)
```

**Comment by dnkoutso** [comment]
yes that could be an improvement by passing `-L`.

**Comment by dwsjoquist** [comment]
Thank you :)

**Comment by dnkoutso** [comment]
Will ship with 1.9.0.beta.3
