### ISSUE TITLE
share_schemes_for_development_pods not worked for xcode 11.2.1

### ISSUE THREAD

**Issue by sunnyweekday** [CocoaPods/CocoaPods#9426]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
pod install

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
When installed finished.
Open the Pods project generated by cocoapods.
There are three schemes in the xcode left corner.(IGListKit,IGListDiffKit,Pods-Onlysource)

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  

There is no scheme in the xcode left corner.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!
platform :ios, "11.0"

project "./OnlySource/OnlySource.xcodeproj"

install! 'cocoapods', :share_schemes_for_development_pods => true

target 'OnlySource' do
    pod 'IGListKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.
[PodsDemo.zip](https://github.com/CocoaPods/CocoaPods/files/3994525/PodsDemo.zip)

**Comment by heliangzhang** [comment]
I have read the 
configure_schemes function of pods_project_generator.rb
the sandbox.local?(pod_target.pod_name) is false

**Comment by dnkoutso** [comment]
You have to use `:path` for a pod to be a development pod. This is working as expected.

**Comment by dnkoutso** [comment]
Your pod is treated as non development pod.

Do:
```ruby
pod 'IGListKit', :path => '/somewhere/where/you/cloned/that/repo.git'
```
