### ISSUE TITLE
Do we need to refresh file installers for local pods?

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/CocoaPods#9427]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

`read_file_system` to be called only once for each `PathList` object corresponding to local pods.

## What happened instead?

It's called twice because `refresh_file_accessors` is called by `FileReferencesInstaller.install!`.

## CocoaPods Environment

Cocoapods v1.8.4

## Reason for this expectation

For local pods with a root folder that has a huge recursive content, `read_file_system` takes multiple seconds depending on the content size of the folder. This operation is done twice during clean install, which seems unnecessary for local pods as we don't expect file system content to be changed for local pods during `pod install` process.

## Details

refresh_file_accessors has the following note:
```ruby
# @!group Installation Steps

# Reads the file accessors contents from the file system.
#
# @note   The contents of the file accessors are modified by the clean
#         step of the #{PodSourceInstaller} and by the pre install hooks.
#
# @return [void]
#
def refresh_file_accessors
  file_accessors.map(&:path_list).uniq.each(&:read_file_system)
end
```

And I see that `PodSourceInstaller.clean!` only does cleaning for non local pods:

```ruby
# Cleans the installations if appropriate.
#
# Cleaning the installation will remove any files that are not used during the build process, based on
# the podspec and platforms of the target that the pod is integrated into.
#
# @see {#clean_installation}
#
# @return [void]
#
def clean!
  clean_installation unless local?
end
```

I don't know how `pre_install` hooks might affect the file accessors, but regarding `PodSourceInstaller.clean!` is only called for non local pods, I believe we might do the same for `refresh_file_accessors` too. What do you think?

@dnkoutso did you evaluate this during your immutability refactor? Currently PathList objects are mutable because of this `read_file_system` trigger.

**Comment by dnkoutso** [comment]
The immutability refactor was mostly an effort. It has succeeded in many cases but not in all. Definitely not for `installer.rb` which is public API.

I agree we should avoid calling this twice it will speed up things for us as well! Want to try making a PR for it?

**Comment by manuyavuz** [comment]
Ideally, I would look into a complete refactoring for `PathList` class as I think it works suboptimal compared to an actual dir globbing. I have some profiling results which clearly shows the case.

The original idea of `PathList` class was to read the file system content once, then running matching against that content list which is held in memory. But I think it loses it's advantages when file system content is huge and you do relatively smaller glob operations.

I will send a PR with some quick wins in a bit.

**Comment by dnkoutso** [comment]
@manuyavuz should I close this since #9428 landed?

**Comment by manuyavuz-pointr** [comment]
Yes I’ll close it.
