### ISSUE TITLE
hope a new project DSL to wrap pods together

### ISSUE THREAD

**Issue by guzhenhuaGitHub** [CocoaPods/CocoaPods#9429]
Now:

```ruby
target 'Target' do
  pod 'PodA', project_name: 'UI'
  pod 'PodB', project_name: 'UI'
  pod 'PodC', project_name: 'UI'
  pod 'PodD', project_name: 'UI'
  pod 'PodE', project_name: 'Network'
  pod 'PodF', project_name: 'Network'
  pod 'PodG', project_name: 'Network'
end
```

it's not clear when there is a lot pod and project

Prefer:
```Ruby
target 'Target' do
  project: 'UI' do
    pod 'PodA'
    pod 'PodB'
    pod 'PodC'
    pod 'PodD'
  end
  project: 'Network' do
    pod 'PodE'
    pod 'PodF'
    pod 'PodG'
  end
end
```

**Comment by orta** [comment]
Have you looked at [`abstract_target`](https://guides.cocoapods.org/syntax/podfile.html#abstract_target) as a way to handle this?

**Comment by guzhenhuaGitHub** [comment]
> Have you looked at [`abstract_target`](https://guides.cocoapods.org/syntax/podfile.html#abstract_target) as a way to handle this?

I'm not talking about target.
I'm talking about the new dsl :project_name, the new feature in Cocoapods 1.8

**Comment by dnkoutso** [comment]
Can you also just use:
```ruby
def ui_pod(name)
  pod name, :project_name => 'UI'
end

def network_pod(name)
  pod name, :project_name => 'Network'
end
```
The example you provide is not bad but I am not sure yet of implementing it.
