### ISSUE TITLE
CP auto umbrella header generation and Xcode `-Swift.h` header generation seem to conflict

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/CocoaPods#9432]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Have a pod named `Foo` that includes both ObjectiveC and Swift source files. 
- Do not provide a module map so that CP generates an umbrella header.
- Do not have a `Foo.h` header as it's not needed.
- Have Swift files use ObjC API, and ObjC files use Swift API.
- Use that pod as development pod.

## What did you expect to happen?

- All files to see each other as expected.

## What happened instead?

- When Xcode automatically generates `Foo-Swift.h` file, it puts `#import <Foo/Foo.h>` into generated header if needed (it happens if Swift API has a dependency to an ObjC API).
- Because `Foo` pod does not have a `Foo.h` header, build fails with `Foo.h` not found error.

## CocoaPods Environment

CP 1.8.4

## Discussion

CP generates umbrella header as `Foo-umbrella.h`, but Xcode seems to expect a `Foo.h` for some reason I'm not aware of.

What I would expect here is for Xcode to add `#import <Foo/Foo-umbrella.h>` into `Foo-Swift.h` file. When ObjC and Swift files reside together in a framework target, Swift files can see all API included in public umbrella header, without doing any `import Blah` calls.  ObjC files can see all Swift API too, if they include `#import <Foo/Foo-Swift.h>`. But if I try to do that without having a `Foo.h` header, build fails due to `not found` error.

Is this the expected behavior?

PS: I will try to create a demo project demonstrating the problem.

Best

**Comment by manuyavuz** [comment]
Ok this is a duplicate of #3767. But I don't see a clear solution here.

I also thought about adding `Foo.h` with following content:

```objc
#import <Foo/Foo-umbrella.h>
```

But the problem is, name of the umbrella header might change if target are duplicated, so different subspecs of the same pod might have different naming for umbrella header. Currently for example I have following umbrella files:

```
Foo-core-umbrella.h
Foo-core-ui-umbrella.h
```

And because I don't have to actual control over this naming, any content I put into `Foo.h` will be fragile.

**Comment by amorde** [comment]
Yes I've run into this issue as well, CocoaPods is in a tough spot because we cannot control what Xcode `#import`s in the `-Swift.h` header, but we don't want to generate `Module.h` since by convention that is usually something library authors control.

The workaround is to manually create your own `Foo.h` and import the headers you need. While you lose the automatic generation that CocoaPods, this is what you'd normally have to do without CocoaPods.

**Comment by amorde** [comment]
It was suggested [here](https://github.com/CocoaPods/CocoaPods/issues/3767#issuecomment-143254444) that CocoaPods could check if `Module.h` exists, and if not use that as the umbrella header name instead of `Module-Umbrella.h`, but it was never implemented.

**Comment by manuyavuz-pointr** [comment]
@amorde problem with providing a manual module is that CP does not currently support static frameworks or libraries for them. And I don’t want to lose that option.

**Comment by amorde** [comment]
Hmm I'm not familiar with this limitation, why is that the case? If you create that header manually and add it to the public header files, what happens?

**Comment by manuyavuz-pointr** [comment]
#7585 #7598 #9023 are related. Basically, you can’t integrate podfile with static libraries if you use custom module map in one of the pods. And if you dont provide a module map, umbrella header will always be generated even though you would have a Foo/Foo.h file that includes all headers for example.

**Comment by amorde** [comment]
Oh yes, familiar with those issues but wasn't tying the dots together.

I think revisiting the logic of "use Foo.h if it doesn't already exist" may still be valid, though would be a breaking change if anyone was depending on the existence of `Foo-umbrella.h`
