### ISSUE TITLE
CocoaPods as a local dependency in the React-Native project

### ISSUE THREAD

**Issue by Greg-Bush** [CocoaPods/CocoaPods#9434]
Hello! I am Front-end & React Native developer. And I would like to designate CocoaPods as a local dependency on our project. Because there are might be some problems when everybody in the team have different versions on their local machines. Is it possible to implement it for example as "npm" dependency? Thanks.

**Comment by dnkoutso** [comment]
Use https://bundler.io/ to accomplish this with a `Gemfile` or `:path`.
