### ISSUE TITLE
Not ideal behavior during deduplication suffix generation

### ISSUE THREAD

**Issue by manuyavuz** [CocoaPods/CocoaPods#9436]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- Have a podspec with `cpp`, `core`, `ui` as subspecs.
- Have following Podfile:
```ruby
abstract_target 'Core' do
  pod 'Foo/core', path: '..'
end

abstract_target 'UI' do
  pod 'Foo/ui', path: '..'
end
```
- Run `pod install`

## What did you expect to happen?

- Expect two pod targets to have names `Foo` and `Foo-ui`.

## What happened instead?

- Got two pod targets with names `Foo-cpp-core` and `Foo-cpp-core-ui`.

## CocoaPods Environment

CP 1.9.0.beta.2

## Details

Current suffix generation steps seem too complicated, and not intuitive. The method is the following:

https://github.com/CocoaPods/CocoaPods/blob/80c3bc3acd769d864d39b006b0bdda82a2ff3c9c/lib/cocoapods/installer/analyzer/pod_variant_set.rb#L116-L161

Logic seems like the following:

```
- Take default subspecs + root spec as `default_specs` (rather than directly using default subspecs)
- For each variant:
  - Omit `default_specs` if it's a subset of variant specs
  - Omit `common_specs` if it's a proper superset of `default_specs`
  - If there is no specs left:
    - Add `.common` if commons were omitted
    - Keep empty if defaults were omitted
  - Else:
    - Add `.common` if commons were omitted
    - Add `.default` if defaults were omitted
```

A few problems I see:
- Why we always add root spec into `default_specs`? If we do that, a variant including only subspecs won't be omitted even if subspecs is superset of default subspecs. To workaround that, I have to do sth like this:

```ruby
abstract_target 'Core' do
  pod 'Foo', path: '..'
  pod 'Foo/core', path: '..'
end

abstract_target 'UI' do
  pod 'Foo', path: '..'
  pod 'Foo/ui', path: '..'
end
```

- Why add `.default` if there are some specs remaining to add, and do not add anything if there is no spec remaining? I don't see any useful use case to do that. This makes my case to have `Foo` and `Foo.default-ui` as names even with above workaround. I would only expect `Foo` and `Foo-ui`.
- I think we could even ignore adding `.common` always. If `Foo`'s default subspec is `cpp`, and I add `Foo/core` and `Foo/ui`, I would still expect `Foo` and `Foo-ui` to be visible.
- I understand that being explicit might sound wise, but our default behavior is not that. For example, if someone only uses `Bar/core` where `Bar` default subspecs is not set, we still label it as `Bar`, not `Bar-core`.

@mrackwitz what are your thoughts on this as the main author of the feature? I'm pretty sure there are some things I'm missing, but this seems the intuitive way as an outsider.

**Comment by dnkoutso** [comment]
I am not seeing a huge issue besides aesthetics?

**Comment by manuyavuz** [comment]
There is one problem, the handling of the issue #9432 

We are currently using this suffixed names as the prefix to generated `-umbrella.h` umbrella headers. So for `Foo`, I get `Foo-umbrella.h`, for `Foo.default-ui` I get `Foo.default-ui-umbrella.h`.

This makes writing a workaround for #9432 too dirty.

Maybe we should always generate `$PRODUCT_MODULE_NAME-umbrella.h` as the file name? If we do that regardless of deduplication scoping, it would make it possible for someone to refer to `#import<Foo/Foo-umbrella.h>` without fear.

And for naming, I feel we are trying to be too clever and handle all naming issues ourselves. Maybe we can just require user input with a Podfile dsl when deduplication requires some scoping?


Currently, with a little different configuration change, I can get completely different pod target names, which makes CI tooling fragile as scheme names change for build and test targets for instance.

Therefore, I don't think it's just an aesthetics issue.

**Comment by manuyavuz** [comment]
I think having a `:target_name` dsl in podfile and/or podspec will be beneficial for people running into problems regarding CP chosen names.

**Comment by manuyavuz** [comment]
I ended up with a little bit of hacking to make pod target labels and umbrella header names as I wish:
```ruby
installer.pod_targets.select { |t| t.name =~ /Foo/ }.each do |t|
  t.define_singleton_method(:umbrella_header_path) do
    module_map_path.parent + "#{product_module_name}-umbrella.h"
  end
  t.define_singleton_method(:umbrella_header_path_to_write) do
    module_map_path_to_write.parent + "#{product_module_name}-umbrella.h"
  end
  t.define_singleton_method(:test_target_label) do |test_spec|
    "#{label}-#{subspec_label(test_spec)}"
  end
  t.define_singleton_method(:label_for_test_type) do |_test_type|
    ''
  end
  if t.name =~ /UI/
    t.define_singleton_method(:label) do
      'FooUI'
    end
  else
    t.define_singleton_method(:label) do
      'FooCore'
    end
  end
end
```

I can live by this, but I can put some more effort to integrate a better solution into CocoaPods. Opinions?

**Comment by fangmobile** [comment]
I see value in this. I recently changed my pod spec to have more sub specs, and saw a .common target show up and did not know why. Build broke. Then google took me here.
