### ISSUE TITLE
Include scripts and other files to call from script_phase

### ISSUE THREAD

**Issue by pacu** [CocoaPods/CocoaPods#9446]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm trying to replicate the Podspec that is discussed on the 1.4.0 release notes. 
```` ruby
s.script_phases = [
  { :name => 'Precompile',
    :script => '${PODS_TARGET_SRCROOT}/setup.sh',
    :execution_position => :before_compile
  },
  { :name => 'Postcompile',
    :script => 'echo "yay!"',
    :execution_position => :after_compile
  }
]
````

Thing is that when I run `pod install` the build phases would be added, but they won't work when a build is triggered because the 'setup.sh' script would not be present in the Pods/MY_POD/ folder.

## What did you expect to happen?

I would expect that the script files are copied over to the Pods/ 

## What happened instead?

scripts referenced by script_phase are nowhere to be found by the client app and build fails

## CocoaPods Environment
CocoaPods 1.8.4

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.2.1 (11B53)
         Git : git version 2.23.0
Ruby lib dir : /usr/local/Cellar/ruby/2.6.5/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by pacu** [comment]
Solution: preserve the paths where your script_phases resources live 
```
s.preserve_paths = ['Scripts', ...]
```

**Comment by dnkoutso** [comment]
Yeap thats it.
