### ISSUE TITLE
Xcframework Source file path error 

### ISSUE THREAD

**Issue by NishantTiwarins** [CocoaPods/CocoaPods#9449]
Hi

I am using the cocoapods version 1.9.0.beta.2

I am trying to distribute my xcframework through the podspec file 

My podspec file contains this 

spec.name             = 'SDKNAME'
  spec.version          = 'VERSION NUMBER'
  spec.license          =  {:type => 'MIT', :file => 'License.md'}
  spec.homepage         = 'URL OF THE PRODUCT'
  spec.authors          = {  'AUTHOR NAME' => 'AUTHOR EMAIL'}
  spec.summary          = 'SUMMARY OF THE SDK'
  spec.source          = { :git => "GIT URL OF THE SDK", :tag => 'VERSION OF THE SDK'}
  spec.source_files     = 'SDK.xcframework/Headers/*.{h,m,swift}'
  spec.library          = 'z', 'sqlite3', 'xml2.2'
  spec.xcconfig         = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }
  spec.vendored_frameworks = 'SDK.xcframework','Vendors/VENDORSDK1.xcframework','Vendors/VENDORSDK2.framework'
  spec.documentation_url = 'Documetation URL'
  spec.framework        = 'FRAMEWORK NAME'
  spec.exclude_files    = "Classes/Exclude"
  spec.platform         = :ios, "10.0"
end

Here vendor1 and vendor 2 is my dependencies framework. Out of which i have vendor1 as a XCframework. I get the following error - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.

What i am doing wrong? can you please help me with that .

**Comment by NishantTiwarins** [comment]
Hi 

Can any one please help me with this. As i have been waiting long for this feature

**Comment by dnkoutso** [comment]
cc @amorde ?

**Comment by amorde** [comment]
You should not be using `source_files` for the contents of a compiled XCFramework - can you explain a bit more what you're trying to do?

The headers of the framework specified in `vendored_frameworks` should automatically be exposed by CocoaPods

**Comment by NishantTiwarins** [comment]
Hi 

Actually i am trying to distribute my SDK which is an Xcframework through cocoapods and while passing the Xcframework path in my podspec file in spec.source_files and after validating the podspec i get the following eror. can you please let me know how can i pass the xcframework path in source_files.

**Comment by dnkoutso** [comment]
You should `s.vendored_frameworks` for pre-built xcframeworks in 1.9.0+. Do not use `source_files` for that it is used for different set of files.
