### ISSUE TITLE
unable to spawn process (Argument list too long) error

### ISSUE THREAD

**Issue by xanderbuck** [CocoaPods/CocoaPods#9450]
# Report

## What did you do?

I tried installing the Firebase Analytics pod in my project. I ran pod install and it successfully completed.

## What did you expect to happen?

I expected after a successful pod install I would be able to build the Xcode project.

## What happened instead?

When trying to build the Xcode project I got the build error **unable to spawn process (Argument list too long)**.

It seems to fail when running the shell script "Check Pods Manifest.lock" step of the build process.

```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/xxx/Library/Developer/Xcode/DerivedData/xxx/Build/Intermediates.noindex/xxx.build/Debug\ (Staging)-iphonesimulator/OV.build/Script-05BB3CCD2FBD4842F78B0F4F.sh (in target 'xxx' from project 'xxx')
    cd /Users/xxx/Documents/Projects/ov-ios
    /bin/sh -c /Users/xxx/Library/Developer/Xcode/DerivedData/xxx/Build/Intermediates.noindex/xxx.build/Debug\\\ \\\(Staging\\\)-iphonesimulator/xxx.build/Script-05BB3CCD2FBD4842F78B0F4F.sh

error: unable to spawn process (Argument list too long) (in target 'xxx' from project 'xxx')
```

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-check       : 1.1.0
cocoapods-deintegrate : 1.0.4
cocoapods-keys        : 2.1.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '13.0'
use_frameworks!

def example_pods
    pod "Apollo", '0.16.0'
    pod 'AlamofireImage', '3.5.2'
    pod 'KeychainAccess', '4.1.0'
    pod 'SwiftUIRefresh', '0.0.1'
    pod 'Firebase/Analytics', '6.14.0'
end

target 'Example' do
  example_pods
end

target 'ExampleTests' do
  example_pods
end

target 'ExampleUITests' do
  example_pods
end

plugin 'cocoapods-keys', {
  :project => "Example",
  :keys => [
   
  ]}
```

**Comment by dnkoutso** [comment]
Hmmm not sure what your `ARG_MAX` is set to. Either way this is an issue because the command being executed is too long as the error message says. 

I do not see immediately a change we can do here...

**Comment by xanderbuck** [comment]
@dnkoutso Where would I set my ARG_MAX? I'm not familiar with that. Is this on the Cocoapods side or Xcode side?

**Comment by dnkoutso** [comment]
Its on UNIX level http://porkmail.org/era/unix/arg-max.html

**Comment by iferrera** [comment]
@xanderbuck @dnkoutso did you get any solution to this? Getting the same error in our project when doing an Archive.
BTW, Build or Run is successful.

We've tried the following with no luck:

- Try with disable_input_output_paths install option.
- Both legacy or new build system.
- Changing derived data path to a shorter one
- Adding the User Defined Build Setting USE_SWIFT_RESPONSE_FILE to YES/NO

At the moment, we have 201 dependencies when running a pod install, so I've no clue if that could be a unexpected amount of pods to handle.

We are using Xcode11.1 and Cocoapods 1.8.4.

Thanks in advance.

**Comment by gonghonglou** [comment]
We get the same error. We've changed the Derived Data path in Xcode, made it shorter, and it works. But is there a better solution?

<img width="798" alt="截屏2020-11-04 下午5 29 14" src="https://user-images.githubusercontent.com/14970112/98093921-885a3000-1ec3-11eb-9dca-11bdac79e410.png">

**Comment by gonghonglou** [comment]
> We get the same error. We've changed the Derived Data path in Xcode, made it shorter, and it works. But is there a better solution?
> 
> <img alt="截屏2020-11-04 下午5 29 14" width="798" src="https://user-images.githubusercontent.com/14970112/98093921-885a3000-1ec3-11eb-9dca-11bdac79e410.png">

Sometimes it works and sometimes it doesn't......🤷‍♂️

**Comment by gonghonglou** [comment]
Getting the same error. Changing the Derived Data path in Xcode sometimes works and sometimes it doesn't......🤷‍♂️

Xcode11.7 and Cocoapods 1.9.3

**Comment by gonghonglou** [comment]
We solved this problem by modifying podspec: changing `s.resources = 'Pod/Assets/**/*'` to `s.resources = 'Pod/Assets/*.xcassets'`, or using `resource_bundles`.

`**/*` will execute many useless copy commands to copy the image file to main bundle path.


ps: you will find the `/Script-05BB3CCD2FBD4842F78B0F4F.sh` only has

```
#!/bin/sh
"${PODS_ROOT}/Target Support Files/Pods-App/Pods-App-resources.sh"
```

**Comment by gonghonglou** [comment]
We solved this problem by modifying podspec:
```
# s.resources = 'Pod/Assets/**/*'❌
s.resources = 'Pod/Assets/*.xcassets' ✅
```
or using `resource_bundles`

`**/*` will execute many useless copy commands to copy the image file to main bundle path.

ps: you will find the `/Script-05BB3CCD2FBD4842F78B0F4F.sh` only has
```
#!/bin/sh
"${PODS_ROOT}/Target Support Files/Pods-App/Pods-App-resources.sh"
```
