### ISSUE TITLE
While using XCFramework as a vendored_framework, Instead of IOS Archive, It is generating the Generic Xcode Archive.

### ISSUE THREAD

**Issue by sasikumar-mobiotics** [CocoaPods/CocoaPods#9458]
Hi, 

# Report

## What did you do?

ℹ I have created XCFramework, that one I added as `vendored_frameworks` and distributed in cocoapods.

## What did you expect to happen?

ℹ Once we install that pod into the client's IOS projects, It is working fine when running into a simulator or real device. But when we create the archive it is expected to create` IOS Archive`.

## What happened instead?

ℹ Instead of `IOS Archive`, It is generating the `Generic Xcode Archive`. When we use .framework file, it is working fine. Problem with XCFramework only. 

## CocoaPods Environment

ℹ CocoaPods version **1.9.0.beta.2**
ℹ  Xcode Version - 11.2.1

## Project that demonstrates the issue

ℹ I have verified this repo also [cocoapods integration repo](https://github.com/CocoaPods/cocoapods-integration-specs/tree/master/install_vendored_xcframework). The Same problem.

ℹ Try with this also `pod 'CoconutLib'`

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

@amorde Please help me to resolve this issue. I looking forward to hearing from you. If you need more information let me know.

**Comment by amorde** [comment]
Confirmed, thank you for submitting this! Looks like the xcframework slice is put in the wrong place when archiving. Still looking into why but can reproduce it.

**Comment by amorde** [comment]
The framework slice is being put into the correct place, but the copy from the `Prepare Artifacts` script is left in `${TARGET_BUILD_DIR}` which is a different location when archiving. We need to store it somewhere else or delete that copy when archiving.

**Comment by dnkoutso** [comment]
Fixed. Will ship in 1.9.0.beta.3

**Comment by sasikumar-mobiotics** [comment]
> Fixed. Will ship in 1.9.0.beta.3

Thanks @amorde and @dnkoutso

**Comment by NishantTiwarins** [comment]
Hi @amorde  and @dnkoutso  Is the 1.9.0.beta.3 released?

**Comment by dnkoutso** [comment]
Not yet but you can use https://bundler.io/ to point to the `1-9-stable` branch if you want the latest commits from now.

**Comment by NishantTiwarins** [comment]
@dnkoutso  Thanks for the quick reply. Will do that, also is it possible to know by when you will be releasing ? Any ETA would be nice.

**Comment by dnkoutso** [comment]
@NishantTiwarins we do not do any fixed releases, my best guess is this week but no promises.

**Comment by NishantTiwarins** [comment]
@dnkoutso  Okay no problem. Anyway thanks for the update and a quick reply.

**Comment by Evomo** [comment]
I have the same issue. Thanks for your quick fix. Great work. Looking forward to test ist.
