### ISSUE TITLE
Missing [CP] Embed Pods Frameworks

### ISSUE THREAD

**Issue by Jon889** [CocoaPods/CocoaPods#9459]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I created a new framework Project in Xcode. Then used this Podfile 
```
# sources
source 'https://github.com/CocoaPods/Specs.git'

# global config
platform :ios, '10.0'
use_frameworks!
workspace 'Galaxy'

pod 'TrustKit', '1.5.3'
# targets

target 'Galaxy' do
  project 'Galaxy/Galaxy'
  
  target 'GalaxyTests' do
  end
end
```

Then ran `pod install`.

After opening the workspace there is no `[CP] Embed Pods Frameworks` Run Script Phase installed. This means the when running the app that uses the framework, it crashes on launch with this error:  `dyld: Library not loaded: @rpath/TrustKit.framework/TrustKit . `

I've looked in the `Target Support Files` directory and there isn't the `Pods-Galaxy/Pods-Galaxy-frameworks.sh` for me to manually add the Run Script Phase. The .sh file for the Unit tests however does exist (`Pods-Galaxy-GalaxyTests/Pods-Galaxy-GalaxyTests-frameworks.sh`).

I've read a lot of Stackoverflow posts and issues here, which suggest things like making the frameworks optional (which I can't find in Xcode 11). But none of them seem to deal with the missing script file. eg https://github.com/CocoaPods/CocoaPods/issues/5250#issuecomment-220061976 doesn't help because .sh file is missing.

I already have a project (that was setup about a year ago) that uses TrustKit (version 1.5.3) and that is setup correctly. I've also tried downgrading to CocoaPods 1.6.0 and that hasn't worked.

## What did you expect to happen?

 Install all pod dependencies correctly. And the shell script exists as expected.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G2022)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 81e8d9b1ec1c5cade2f2e0d36d7c26793b447c53
               tesco-ios-pods - git - git@github.dev.global.tesco.org:MobileApps/ios-pods.git @ c70535a88bb6c67f7064f05e2c6b2f9a2a772918
               tesco-mobileapps-ios-pods - git - git@github.dev.global.tesco.org:MobileApps/ios-pods.git @ 7171569686b851152d72d905088005aba74f7d22
               tesco-mobileapps-ios-pods-1 - git - https://github.dev.global.tesco.org/MobileApps/ios-pods.git @ 684c7c1a58820489605c1f13a94148f5f9df36d6
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.3.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.4.1
cocoapods-try          : 1.1.0
slather                : 2.4.6
```

### Podfile

```ruby
# sources
source 'https://github.com/CocoaPods/Specs.git'

# global config
platform :ios, '10.0'
use_frameworks!
workspace 'Galaxy'

pod 'TrustKit', '1.5.3'
# targets

target 'Galaxy' do
  project 'Galaxy/Galaxy'
  
  target 'GalaxyTests' do
  end
end
```

## Project that demonstrates the issue

[Galaxy.zip](https://github.com/CocoaPods/CocoaPods/files/4026627/Galaxy.zip)

**Comment by dnkoutso** [comment]
I believe frameworks are only embedded into app targets which you do not specify in your `Podfile`.

**Comment by Jon889** [comment]
I'm not sure I understand we definitely have other private pod frameworks that have other frameworks as cocoapod dependencies. It seems like it would be weird to have to include all of Galaxy's dependencies an app's target, shouldn't that be done automatically?

**Comment by dnkoutso** [comment]
I think its because frameworks cannot include other frameworks. Although umbrella frameworks are a thing I am not sure if its used outside of Apples' core frameworks.

Going to close as it seems it behaves correctly.
