### ISSUE TITLE
    - ERROR | [iOS] unknown: Encountered an unknown error (no block given) during validation.

### ISSUE THREAD

**Issue by Godxiao6** [CocoaPods/CocoaPods#9460]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run `pod lib lint`

## What did you expect to happen?
passed validation

ℹ Please replace these two lines with what you expected to happen.  

## What happened instead?
 - ERROR | [iOS] unknown: Encountered an unknown error (no block given) during validation.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `tal_ios_speech_recogn` from `/Users/lihaoliang/work/project/upload_speech_reg_sdk/tal_ios_speech_recogn/tal_ios_speech_recogn.podspec`

Resolving dependencies of 
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local
  because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_a_7_5.txt exists! Returning local
  because checking is only perfomed in repo update
  CDN: trunk Relative path:
  Specs/a/7/5/AFNetworking/3.2.1/AFNetworking.podspec.json exists! Returning
  local because checking is only perfomed in repo update
  CDN: trunk Relative path: all_pods_versions_d_e_9.txt exists! Returning local
  because checking is only perfomed in repo update
  CDN: trunk Redirecting from
  https://cdn.cocoapods.org/Specs/d/e/9/CocoaSecurity/1.2.2/CocoaSecurity.podspec.json
  to
  https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/e/9/CocoaSecurity/1.2.2/CocoaSecurity.podspec.json
  CDN: trunk URL couldn't be downloaded:
  https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/d/e/9/CocoaSecurity/1.2.2/CocoaSecurity.podspec.json
  Response: Couldn't connect to server, retries: 4
 -> tal_ios_speech_recogn (1.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (no block given
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1476:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/object.rb:57:in `new'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/synchronization/object.rb:57:in `new'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1383:in `new_blocked_by1'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:595:in `chain_on'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:577:in `chain'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:210:in `schedule_on'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/cdn_source.rb:430:in `sleep_async'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/cdn_source.rb:420:in `exponential_backoff_async'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/cdn_source.rb:404:in `block in download_and_save_with_retries_async'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:385:in `apply'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1148:in `apply'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1498:in `block (2 levels) in on_resolvable'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1343:in `evaluate_to'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1498:in `block in on_resolvable'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1179:in `raise'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:1179:in `wait_until_resolved!'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.4/lib/concurrent/promises.rb:940:in `wait!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/cdn_source.rb:144:in `block in versions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/cdn_source.rb:471:in `concurrent_requests_catching_errors'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/cdn_source.rb:121:in `versions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/specification/set.rb:98:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0.beta.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:1064:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:1062:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/validator.rb:565:in `block in download_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/validator.rb:565:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/validator.rb:565:in `download_pod'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/validator.rb:389:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/validator.rb:383:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/validator.rb:383:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/validator.rb:130:in `validate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/spec/lint.rb:78:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/spec/lint.rb:63:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/spec/lint.rb:63:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/spec/lint.rb:95:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

### Stack

```
   CocoaPods : 1.9.0.beta.2
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.2
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : billyhq - git - https://github.com/Billyhq/TALVoiceEvalSDKCocoaPodRepo.git @ b47bcda9392c3a691054bc49728feadceb53c400

               master - git - https://github.com/CocoaPods/Specs.git @ 3f8238ac9fb0dd211bc4a1794869710334a03b98

               trunk - CDN - https://cdn.cocoapods.org/
               victorzhang2014 - git - https://github.com/VictorZhang2014/ZRKeyChain @ 3a48669fdc5ed0533d08e5ab90b532893f7c0cba

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Seems like an issue with reaching CDN. Can you try using the `git` based source?

**Comment by Godxiao6** [comment]
> Seems like an issue with reaching CDN. Can you try using the `git` based source?

Thank you for your reply. I'm new to ios, I found these libraries on git and use pod to import them into my project,I don't know how to using git base source, should I add something in the podspce file?

**Comment by dnkoutso** [comment]
Use `pod repo add` command see http://blog.cocoapods.org/CocoaPods-1.7.2/

**Comment by dnkoutso** [comment]
I am going to close preemptively and recommend you file this on StackOverflow instead.
