### ISSUE TITLE
xcode build the xcode project  below 10.0 version with option  -UseModernBuildSystem=YES  test faild

### ISSUE THREAD

**Issue by willson-chen** [CocoaPods/CocoaPods#9463]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
```
xcodebuild `` -workspace Example/ZipArchiveExample.xcworkspace `` -scheme ObjectiveCExample_macOS `` -sdk macosx `` -destination "platform=macosx" `` -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES `` -UseModernBuildSystem=YES `` test
```
## What did you expect to happen?

test pass

## What happened instead?

test fail:
```
In file included from <built-in>:1:
/Users/wilson/workspace/ZipArchive/Example/Pods/Target Support Files/SSZipArchive-iOS/SSZipArchive-iOS-prefix.pch:3:9: fatal error: 'UIKit/UIKit.h' file not found
#import <UIKit/UIKit.h>
```
## CocoaPods Environment

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3 (11C29)
```
## Project that demonstrates the issue
https://github.com/ZipArchive/ZipArchive/tree/master/Example

**Comment by dnkoutso** [comment]
You are passing `-sdk macosx` and UIKit is only part of iOS? Furthermore this does not seem a CocoaPods issue as you are invoking `xcodebuild` directly.

Will re-open as we go through this but for now I will close.
