### ISSUE TITLE
When building a static library, I can't generate public header files

### ISSUE THREAD

**Issue by freshman007** [CocoaPods/CocoaPods#9467]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
 Run `pod install`, and the host target definition doesn't specify `use_frameworks!`

## What did you expect to happen?
To generate a private static library which has public header files by using the cocoapods, we create the .podSpec file in which we also have specify properties of source_files and public_header_files;
![image](https://user-images.githubusercontent.com/7614682/71969536-d077da00-3241-11ea-87a0-d1e2abfa1d5e.png)

## What happened instead?

After I runned the 'pod install', these header files in the target are added in the "Build Phase->Header->Project", not in the "Build Phase->Header->Public". And the product of this target has no public header files.
![image](https://user-images.githubusercontent.com/7614682/71969410-91498900-3241-11ea-8e9b-cd4c642c6a9c.png)
![image](https://user-images.githubusercontent.com/7614682/71970110-fc478f80-3242-11ea-9e86-9782376ed39f.png)

 I have analyzed the code in "https://github.com/CocoaPods/CocoaPods/blob/1-9-stable/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb" and find out that when we build a static library, the environment var, 'acl', always set as "Project", just like the picture below:
![image](https://user-images.githubusercontent.com/7614682/71968521-0fa52b80-3240-11ea-80fb-e617bb2838f5.png) 
I'm confused with this code and hope you can help me.

## CocoaPods Environment

###Programming Language:
```
swift + Objective-C，xcode 11.3
```

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G84)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.3.0
cocoapods-packager     : 1.5.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.4.1
cocoapods-try          : 1.1.0
```

**Comment by paulb777** [comment]
Static library headers are typically installed into Pods/Headers/Public/{Podname} and static library client workspaces are updated to find them there.

**Comment by freshman007** [comment]
> Static library headers are typically installed into Pods/Headers/Public/{Podname} and static library client workspaces are updated to find them there.

Is there a way to get  static library and header files in the product file? In Cocoapod 1.2.0, when we specify properties of source_files and public_header_files in .podspec file and run `pod install`, the headers indicated in the property of public_header_files will be added in the "Build Phase->Header->Public" of the target. After build this target,  we can totally get the product which contains static library and header files in one product folder. But in Cocoapod 1.8.5, the header files will not be added in the  "Build Phase->Header->Public", and the product folder doesn't contains these files.

**Comment by dnkoutso** [comment]
Why do you need them to be present there? What are you trying to accomplish specifically?

A post install hook might allow you to do what you want but in order for us to figure out if CocoaPods can change we could use some more info.

**Comment by freshman007** [comment]
> Why do you need them to be present there? What are you trying to accomplish specifically?
> 
> A post install hook might allow you to do what you want but in order for us to figure out if CocoaPods can change we could use some more info.

The change of Cocoapods should be rigorous. In my opinion, properties of source_files and public_header_files allow us to specify public header files and we can easily get the product contains header files in the release folder when we release the target. Then it's convenient for us to share the static library by copying the product in one folder rather than piece up the product. Maybe my question is inconsequential,  you show me the ability to set public headers by using properties of source_files and public_header_files but it's actually not work.  That's confused me.

**Comment by CNKCQ** [comment]
https://guides.cocoapods.org/syntax/podspec.html#public_header_files say: When the library is built, these headers will appear in the build directory. That's confused me too.

**Comment by TaronSahakyan92** [comment]
@freshman007 did you find a solution ?
