### ISSUE TITLE
Unable to find a specification for [framework_name]

### ISSUE THREAD

**Issue by elsh** [CocoaPods/CocoaPods#9471]
I have a podspec that looks like this: 

MockoloFramework.podspec (see https://github.com/uber/mockolo/blob/master/MockoloFramework.podspec). Note that the source is a link to .zip. 

```
Pod::Spec.new do |s|
  s.name             = 'MockoloFramework'
  s.version          = '1.1.2'
  s.summary          = 'Efficient Mock Generator for Swift'
  s.description      = 'MockoloFramework provides a fast and easy way to autogenerate mock objects that can be tested in your code....'

  s.homepage         = 'https://github.com/uber/mockolo'
  s.license          = { :type => 'Apache 2.0', :file => 'LICENSE.txt' }
  s.author           = { 'name' => 'name@co.com' }
  s.source           = { :git => 'https://github.com/uber/mockolo.git', :tag => s.version.to_s }
  s.osx.deployment_target = '10.14'
  s.swift_version    = '5.1'
  s.dependency 'SourceKittenFramework', '~>0.26.0'
  s.source         = { :http => "#{s.homepage}/archive/#{s.version}.zip" }
end
```

There are 2 issues: 
1. I have run pod setup, pod repo update, and pod trunk push --skip-tests --allow-warnings, and it says 'MockoloFramework (1.1.2) successfully published' (https://cocoapods.org/pods/MockoloFramework), but searching for the framework at http://cocoapods.org/pods/ doesn't show it in the results. 

2. I'm also trying to create a sample project using the above framework as a pod, but 'pod install' shows 'Unable to find a specification' error. 

➜  SomeTest git:(master) pod install
Analyzing dependencies
Pre-downloading: `MockoloFramework` from `https://github.com/uber/mockolo/archive/1.1.2.zip`
[!] Unable to find a specification for 'MockoloFramework'.

➜  SomeTest git:(master) pod env 
### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G1012)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.19.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ c0413b4e2c44dd26b1b037f69fdeaf1820af5770
               MockoloFramework - git - https://github.com/uber/mockolo.git @ e50986520ba25aa082d06b87c1246ad87c8c30f3
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'source 'https://github.com/uber/mockolo'
source 'https://github.com/CocoaPods/Specs.git'

workspace 'SomeTest.xcworkspace'
use_frameworks!

target 'SomeTest' do
  platform :osx, '10.14'

  pod 'MockoloFramework', :http => 'https://github.com/uber/mockolo/archive/1.1.2.zip'

end
```

**Comment by elsh** [comment]
@segiddins Any idea why i'm getting the above error?

**Comment by dnkoutso** [comment]
```ruby
Analyzing dependencies
Downloading dependencies
Installing MockoloFramework (1.1.2)
Installing SWXMLHash (5.0.1)
Installing SourceKittenFramework (0.26.0)
Installing Yams (2.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
```

I am able to install it. You must probably run `pod repo update` to update your repos to find out about the new pod.

The search functionality for new pods is broken for a while and many issues have been filed and closed.

I am not seeing an error here with CocoaPods, you should provide `s.source_files` in your podspec as it currently has no sources?

**Comment by dnkoutso** [comment]
Going to close this ticket as I do not see an issue. The license warning is tracked in a separate ticket.

**Comment by dnkoutso** [comment]
Use `pod repo list` to find out your repos and their types and make sure you update them.

**Comment by dnkoutso** [comment]
It's possible the license issue is triggered because you have no `source_files` set in your podspec.

**Comment by elsh** [comment]
@dnkoutso Thanks for answers. I tried source_files but now it throws another error. See https://github.com/CocoaPods/CocoaPods/issues/9479.
