### ISSUE TITLE
Unable to build unit test target when including static library pod

### ISSUE THREAD

**Issue by mjjimenez** [CocoaPods/CocoaPods#9473]
🌈
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  

Added a unit test target in the project. Then I updated the `Podfile` to included a static library I'm using in the app (`LibTorch`) to the test target.

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  

Unit test target will build and run correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  

Build failed

error logs showed

```
Undefined symbols for architecture x86_64:
  "c10::Error::Error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*)", referenced from:
      torch::jit::(anonymous namespace)::ConstantPropagator::ConstantPropagation(torch::jit::Block*) in libtorch.a(constant_propagation.cpp.o)
      torch::jit::(anonymous namespace)::checkDoubleInRange(double) in libtorch.a(register_prim_ops.cpp.o)
  "c10::detail::StripBasename(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      torch::jit::is_enabled(char const*, torch::jit::JitLoggingLevels) in libtorch.a(jit_log.cpp.o)
      torch::jit::jit_log_prefix(torch::jit::JitLoggingLevels, char const*, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libtorch.a(jit_log.cpp.o)

....


ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

The app target builds and runs normally (simulator or device) with the static library included. Only the unit test target build fails.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.3 (11C29)
         Git : git version 2.8.1
Ruby lib dir : /Users/mjjim2003/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 7bb44aaa4557b457f1c13cb1a7e403248a0ef594
               rnapier - git - https://github.com/rnapier/RNCryptor.git @ 5e3bbf44f08bf90049537cb8902d8f4fa911a79a
               trunk - CDN - https://cdn.cocoapods.org/
               twilio - git - https://github.com/twilio/cocoapod-specs @ 9bf659ed7246ba34625b81754031fbd5ac20fe68
```

### Installation Source

```
Executable Path: /Users/mjjim2003/.rvm/gems/ruby-2.2.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '12.0'
target 'HelloWorld' do
    pod 'LibTorch', '~> 1.3.0'

    target 'HelloWorldTests' do
      inherit! :search_paths

    end

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

https://github.com/mjjimenez/ios-demo-app

specifically the `HelloWorld` project

https://github.com/mjjimenez/ios-demo-app/tree/master/HelloWorld/HelloWorld

**Comment by dnkoutso** [comment]
https://github.com/mjjimenez/ios-demo-app/tree/master/HelloWorld/HelloWorld is not allowed to be cloned.

This seems a library issue at first glance and not a cocoapods issue but please provide a sample app for us to diagnose or fix the permissions on the one you linked.

**Comment by mjjimenez** [comment]
Hey @dnkoutso , you can clone it here: https://github.com/mjjimenez/ios-demo-app
I just forked the example app provided by the `LibTorch` maintainer and added a unit test target in their hello-world project.

After cloning, the project reproducing the issue is specifically in `ios-demo-app/HelloWorld/HelloWorld/` directory. They didn't include the `Pods` directory so you have to `pod install`.

Yes I agree, it does seem like a library issue but I'm not really sure so I would appreciate any help.

**Comment by dnkoutso** [comment]
Does your unit test target use the app as the app host or no app host?

**Comment by mjjimenez** [comment]
The test target uses the app as a host application.

**Comment by dnkoutso** [comment]
```
Showing All Issues
Ignoring file /Users/dimitris/Development/ios/ios-demo-app/HelloWorld/HelloWorld/Pods/LibTorch/install/lib/libnnpack.a, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
```

The issue is that the pr-built static library `.a` files from the `LibTorch` pod are not universal libs and only include arm-64 architecture for device.

Run `lipo -info Pods/LibTorch/install/lib/libnnpack.a` to see.
```
Non-fat file: libnnpack.a is architecture: arm64
```

This currently does not appear to be a CocoaPods issue so I am going to close for now. We can re-open if we find an issue/bug.
