### ISSUE TITLE
sepc.pod.target_xcconfig bug

### ISSUE THREAD

**Issue by wanglelewang** [CocoaPods/CocoaPods#9474]
cocoapods 版本号1.8.4  OC Xcode 11.2.1

第一种写法：   
  spec.pod_target_xcconfig = {
    'OTHER_LDFLAGS' => '-lObjC',  
    'VALID_ARCHS' => ['arm64']
  }

第二种写法：
  spec.pod_target_xcconfig = {
    'OTHER_LDFLAGS' => '-lObjC',  
    'VALID_ARCHS' => 'arm64',
  }

pod lib lint  第一种可以通过 第二种不可以 
但是 第一种在项目里 pod 'xxx'这个库之后 会报错 找不到这个库 需要把build setting中的 archs 从 [arm64]  的[] 去掉才可以

我认为第二种写法应该可以lint 才是正确的

**Comment by dnkoutso** [comment]
Please file issue in template in english. We are unable to diagnose this issue.

**Comment by wanglelewang** [comment]
cocoapods verison1.8.4 OC Xcode 11.2.1

first：
spec.pod_target_xcconfig = {
'OTHER_LDFLAGS' => '-lObjC',
'VALID_ARCHS' => ['arm64']
}

second：
spec.pod_target_xcconfig = {
'OTHER_LDFLAGS' => '-lObjC',
'VALID_ARCHS' => 'arm64',
}

pod lib lint  first: passed validation.   second: did not pass validation
but first in project pod 'xxx'this  error: "not found lib xxx" need go to the Project's Xcode build setting's  Valid Architectures  [arm64] delete the []   , after run success

so I think second should right

**Comment by amorde** [comment]
@wanglelewang I just tested this and it worked fine for me:

```ruby
spec.pod_target_xcconfig = {
  'VALID_ARCHS' => 'arm64'
}
```

<img width="610" alt="Screen Shot 2020-01-09 at 4 05 36 PM" src="https://user-images.githubusercontent.com/2281949/72114890-e5b03f80-32f9-11ea-8a4d-b72be81aad85.png">

Do you have a sample we can use to reproduce the issue?

**Comment by wanglelewang** [comment]
ok
 I am write a demo  but  this is right  , so this may be others bug  ,   thanks
