### ISSUE TITLE
[Enhancement] Run pod install if Manifest.lock and Podfile.lock mismatch

### ISSUE THREAD

**Issue by arbitur** [CocoaPods/CocoaPods#9475]
I suggest to implement a flag or another way to customize the "[CP] Check Pods Manifest.lock" script so that if the lock files are mismatched then run `pod install` so the user doesnt have to open terminal cd into the project directory and install manually.

**Comment by dnkoutso** [comment]
Doesn't it already do that?

**Comment by dnkoutso** [comment]
oh sorry you mean run `pod install`, I misunderstood. I dont think this is something we want to support. CocoaPods is also meant to work by sharing the project with someone who doesnt have CocoaPods installed.
