### ISSUE TITLE
[Feature Request] Allow Cross-Platform App Specs

### ISSUE THREAD

**Issue by SlaunchaMan** [CocoaPods/CocoaPods#9481]
🌈

* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I created an app spec in a library that also vends a macOS app. The app spec specifies its platform as macOS. It’s [SBTUITestTunnelHost](https://github.com/Subito-it/SBTUITestTunnelHost), a tool to communicate between iOS UI tests and macOS. Here’s what I added to their Podspec to create an app spec:

<details>
<summary>SBTUITestTunnelHost.podspec</summary>

```ruby
Pod::Spec.new do |s|
  s.name             = 'SBTUITestTunnelHost'
  s.version          = '0.2.7'
  s.summary          = 'Execute commands on your testing mac host while using SBTUITestTunnel'
  
  s.description      = <<-DESC
Extend SBTUITestTunnel adding a tunnel between your test target and host mac running tests. This allows to launch terminal commands on your testing mac during test execution
  DESC
  
  s.homepage         = 'https://github.com/Subito-it/SBTUITestTunnelHost'
  s.license          = 'Apache License, Version 2.0'
  s.author           = { "Tomas Camin" => "tomas.camin@scmitaly.it" }
  s.source           = { :git => "https://github.com/Subito-it/SBTUITestTunnelHost.git", :tag => s.version.to_s }
  
  s.platform     = :ios, '9.0'
  s.requires_arc = true
  
  s.frameworks = 'XCTest'
  s.source_files = 'SBTUITestTunnelHost/*.{h,m}'
  s.pod_target_xcconfig = { :prebuild_configuration => 'debug' }
  
  s.app_spec 'MacHost' do |mac_host|
    mac_host.platform  = :osx, "10.13"
    mac_host.source_files = "Mac Host/SBTUITunnelHostServer/**/*.swift"

    mac_host.info_plist = {
      'LSApplicationCategoryType' => 'public.app-category.developer-tools',
      'LSUIElement' => true,
      'NSAppTransportSecurity' => {
        'NSAllowsArbitraryLoads' => true
      },
      'NSAppleEventsUsageDescription' => 'Grant permission to allow host to drag mouse around',
      'NSHumanReadableCopyright' => 'Copyright © 2016 Subito.it. All rights reserved.',
      'NSMainNibFile' => 'MainMenu',
      'NSPrincipalClass' => 'NSApplication'
    }
  end
end
```

</details>

On an iOS project, I pointed my Podfile to the local version of this and attempted to add it as an app spec for my UI tests:

```ruby
target 'InstantReplay-iOS' do
  platform :ios, "10.0"
  use_frameworks!

  target 'InstantReplay-iOSUITests' do
    pod 'SBTUITestTunnelHost', :path => '/Users/jeff/Projects/Open-Source/SBTUITestTunnelHost', :appspecs => ['MacHost']
  end

end
```

## What did you expect to happen?

My goal here is to create a target in my iOS application workspace for the Mac app that SBTUITestTunnelHost provides, so that I can run it before running my UI tests without leaving Xcode.

## What happened instead?

Here is the output of `pod install`:

```shell
InstantReplay jeff$ bundle exec pod install
Analyzing dependencies
/Users/jeff/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:326: warning: URI.escape is obsolete
[!] The platform of the target `InstantReplay-iOSUITests` (iOS 10.0) is not compatible with `SBTUITestTunnelHost/MacHost (0.2.7)`, which does not support `iOS`.
```

## CocoaPods Environment

<details>
<summary>Output of `bundle exec pod env`</summary>

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3 (11C29)
         Git : git version 2.24.1
Ruby lib dir : /Users/jeff/.rbenv/versions/2.7.0/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ c22d20ab3843e3a3ee298a06e953fe9327e6c976
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/jeff/.rbenv/versions/2.7.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'InstantReplay-iOS' do
  platform :ios, "10.0"
  use_frameworks!

  target 'InstantReplay-iOSUITests' do
    pod 'SBTUITestTunnelHost', :path => '/Users/jeff/Projects/Open-Source/SBTUITestTunnelHost', :appspecs => ['MacHost']
  end

end
```

</summary>

**Comment by dnkoutso** [comment]
```ruby
    pod 'SBTUITestTunnelHost', :path => '/Users/jeff/Projects/Open-Source/SBTUITestTunnelHost', :appspecs => ['MacHost']
```

I dont think this does what you think it does. It does not use `MacHost` as the app host of `SBTUITestTunnelHost`. It only tells CocoaPods to install the app host in the `Pods.xcodeproj` so it can be built.

You'd have to mak `SBTUITestTunnelHost` manually depend on the app as its app host in which the reference will be "red" unless `pod install` is executed and the workspace is open.

**Comment by dnkoutso** [comment]
@SlaunchaMan any comments to the above?

**Comment by SlaunchaMan** [comment]
Let me try to rephrase.

SBTUITestTunnelHost has two components: a Mac app and extensions for XCTest. In order to use the latter, the Mac app has to be running on your local system. What I want is to add the Mac app as a scheme in Xcode when you use the library in your UI tests. This way it could be triggered by a pre-run script to automatically launch with your UI tests.

**Comment by samdmarshall** [comment]
@SlaunchaMan i'm not sure i am fully following what you are asking here as some of the terminology you used in your last comment doesn't make sense to me; but what i'm gathering is that for these non-mac platform tests to be run, there is a pre-requisite of needing this host app to be running. This host app is something that Xcode has absolutely no knowledge about, nor is there a way to conveniently express this to Xcode. Additionally if i'm following you correctly, this is complicated by the fact that it requires two different schemes to be run (not targets, but schemes; so the equivalent of two separate and specific actions/invocations).

If that is the case, then you are out of luck. Short of writing a wrapper script for performing two separate `xcodebuild` invocations of the related schemes, you won't find a way to do this with Xcode at all. This is because it is a fundamental limitation of how Schemes are designed to work, and how Xcode can only act on a single scheme at a time. I ran into this problem myself before when implementing a similar test-case setup to what you have described, and wrote a tool that wraps the commands to handle ordering of building+running schemes. I think this falls outside of the realm of dependency management and is more of a build system management problem, which isn't something that cocoapods is suited for handling.
