### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found:

### ISSUE THREAD

**Issue by necatievrenyasar** [CocoaPods/CocoaPods#9489]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have developed framework which is private. It has some dependency other framework such as Kingfisher, Parchment etc. When I try to use my framework, I get some error.

PodSpec of my framework;

[TRPCoreKit pod specs](https://github.com/Tripian-inc/iOS-podspecs/blob/master/TRPCoreKit/1.5.0/TRPCoreKit.podspec 
)

## What happened instead?

When I used my framework with Cocoapods, I took some error about Depencendy.
My framework couldn't access Kingfisher.

`dyld: lazy symbol binding failed: Symbol not found: _$s10Kingfisher0A7WrapperVAASo11UIImageViewCRbzlE8setImage4with11placeholder7options13progressBlock17completionHandlerAA12DownloadTaskVSgAA8Resource_pSg_AA11Placeholder_pSgSayAA0A15OptionsInfoItemOGSgys5Int64V_AXtcSgyAA6ResultOyAA08RetrievefV0VAA0A5ErrorOGcSgtF
  Referenced from: /Users/evrenyasar/Library/Developer/CoreSimulator/Devices/515F2386-1B0F-4100-ACE9-4E38DBD515C8/data/Containers/Bundle/Application/E8919AE7-563A-4201-B962-9F03EEF95CB3/CocoaPodTestCoreKit.app/Frameworks/TRPCoreKit.framework/TRPCoreKit
  Expected in: /Users/evrenyasar/Library/Developer/CoreSimulator/Devices/515F2386-1B0F-4100-ACE9-4E38DBD515C8/data/Containers/Bundle/Application/E8919AE7-563A-4201-B962-9F03EEF95CB3/CocoaPodTestCoreKit.app/Frameworks/Kingfisher.framework/Kingfisher`

## CocoaPods Environment
 ```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodTestCoreKit' do
  use_frameworks!
  pod 'TRPCoreKit', '1.5.0'

end

**Comment by nikitaame** [comment]
@necatievrenyasar did you find a solution to this?
