### ISSUE TITLE
dyld: Library not loaded: @rpath/MJRefresh.framework/MJRefresh   Referenced from:

### ISSUE THREAD

**Issue by CanYouHelpMe** [CocoaPods/CocoaPods#9492]
my podfile
# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MJRefresh'
  # Pods for Test

end

**Comment by dnkoutso** [comment]
Please file the issue properly with a sample app.
