### ISSUE TITLE
I have a question for private pod

### ISSUE THREAD

**Issue by J0HDev** [CocoaPods/CocoaPods#9494]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have created two private pod, written in Swift and another one written in Objective-C

## What did you expect to happen?

I don't want using `@import` to import Swift Class in Objective-c file

## What happened instead?

I want to import Swift class in Objective-C file, I know that I can use `@import xxx` and  I don't wanna use `@import`, in my Objective-C pod I don't have `xx-Swift.h`, what should I do?

I have bad English to express my question..

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : hupu-iosclient-hpspecs - git - http://gitlab.hupu.com/iOSClient/HPSpecs.git @ cc17a4ebc0361a66d661508e52658c92d861993e
               master - git - https://github.com/CocoaPods/Specs.git @ 59127d30fdfb168c47e7914d5134ad7b90a09aea
               summertian4 - git - https://github.com/summertian4/ZLYSpec.git @ 11ccf9788b81b9325019b8712f1cb3e23e122c47
               taobao-baichuansdk-alibcspecs - git - http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git @ 382daa10bf61ef3f66b387eb64fc088ce44ee314
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

It's a company project, I can't share a link so..

**Comment by dnkoutso** [comment]
This question is best asked in StackOverflow under `cocoapods` tag.
