### ISSUE TITLE
Contains framework or static library

### ISSUE THREAD

**Issue by Umity** [CocoaPods/CocoaPods#9495]
Hey guys, i have a framewok already and whatever i did, i could not install a cocoapod into my project which has already a framework.

[!] The Podfile contains framework or static library targets (DeluxeFX iOS), for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).

where am i doing a mistake? this is my podfile:

```
workspace 'Examples/Sense.xcworkspace'
platform :ios, '9.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
    # all the pods go here
    # pod 'Parse' etc.
end

project 'Examples/Sense.xcodeproj'
project '/Users/umit/Documents/APPS/v5/Terra/Terra.xcodeproj'

target :Sense do
  project 'Sense'
pod 'MetalPetal'

# Swift extensions (optional).
pod 'MetalPetal/Swift'

end

target :'Terra iOS' do
  project '/Users/umit/Documents/APPS/v5/Terra/Terra.xcodeproj'
pod 'MetalPetal'
# Swift extensions (optional).
pod 'MetalPetal/Swift'

end
```

**Comment by dnkoutso** [comment]
This is not a mistake, this is a warning. Other `Sense` or `Terra iOS` is a framework or a library that it is not embedded in any app.

You can safely ignore the warning as it says.

So far this does not look like an issue with CocoaPods so I am going to close. I will re-open if we find a bug or enhancement!
