### ISSUE TITLE
Include of non-modular header inside framework module

### ISSUE THREAD

**Issue by Ybrin** [CocoaPods/CocoaPods#9496]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I am trying to push a working cocoapod (a C++ library wrapper), which is building successfully if I use the pod locally, with the command `pod trunk push`.

## What did you expect to happen?

The pod should be pushed.

## What happened instead?

I get the error `Include of non-modular header inside framework module`. I have read a lot about this error but nobody has this issue when pushing a pod, only when installing pods. The weird thing is that `pod spec lint` succeeds.    
Also, using the pod (installed locally) by an app also works and the project builds fine.

The following is the repository I am trying to push.

https://github.com/Ybrin/rocksdb.swift

The repository consists of two podspecs. One (librocksdb.podspec) are the C++ bindings only building the original C++ library. The other one (rocksdb.swift.podspec) is the problematic one. It is a Swift library which has librocksdb (which can be pushed successfully) as the only dependency.    
The weird thing is that the C++ library can be built but a library depending on it can't be pushed. Also using the library in Xcode doesn't generate any errors.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.19.0
Ruby lib dir : /Users/koray/.rbenv/versions/2.4.0/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ be9a23cbaa1c36ca69617c68ed24c96e66d772a6
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/koray/.rbenv/versions/2.4.0/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.4.1
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
slather                : 2.4.5
```

## Project that demonstrates the issue

Already discussed above how to reproduce. Link: https://github.com/Ybrin/rocksdb.swift

**Comment by amadeu01** [comment]
@Ybrin have you managed to get it working ?
I’m having similar issues. How did you fix that ?

**Comment by Ybrin** [comment]
@amadeu01 I did not. It's a cocoapods release issue. They see it as a problem although it builds just fine. I just skipped the checks before publishing the pod by changing the release gem and using my version...it's a hack but the only possible way to do this right now.

**Comment by amadeu01** [comment]
thanks!
