### ISSUE TITLE
Incorrect Warning about CLI tools trying to integrate dynamic frameworks

### ISSUE THREAD

**Issue by CodingMarkus** [CocoaPods/CocoaPods#9498]
# Report

## What did you do?

`pod install`

## What did you expect to happen?

Pods being installed without a warning.

## What happened instead?

I received a warning:

> [!] The Podfile contains command line tool target(s) (<names of CLI tools>) which are attempting to integrate dynamic frameworks.
> This may not behave as expected, because command line tools are usually distributed as a single binary and cannot contain their own dynamic frameworks.

## CocoaPods Environment

Cannot post the pod file content here in public, my employer gives no permission for that.

The thing is: There is no `use_frameworks!` anywhere in Podfile. All pods are statically build and thus statically linked, which is also possible for CLI targets. Despite that, the pods integrated into the CLI targets are binary pods that ship as static library (there are only header and one `.a` file for these pods), so even if we were using frameworks for source pods, the warning would still be wrong.

I looked at the code and the code doesn't seem to check if the pods integrated are static or not or whether frameworks are build at all, the code only looks if there are CLI targets that aren't marked as sub-targets to an app or framework and if there are, it issues that warning.

**Comment by dnkoutso** [comment]
cc @amorde ?

**Comment by amorde** [comment]
Most likely a bug, might be able to take a look this weekend

**Comment by dnkoutso** [comment]
fixed for 1.9.0 next beta.
