### ISSUE TITLE
Module 'SomePod' not found issue

### ISSUE THREAD

**Issue by ShakeebM** [CocoaPods/CocoaPods#9512]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Installed some pod libraries via Podfile and `pod install`

## What did you expect to happen?

it needs to work fine

## What happened instead?

Getting Error like Module is not found. even I installed it via cocoapod

### Stack

```
   CocoaPods : 1.9.0.beta.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 430316ed474d70c4117c4a6bd272828cc108887c

               trunk - CDN - https://cdn.cocoapods.org/
               twilio - git - https://github.com/twilio/cocoapod-specs @ 9bf659ed7246ba34625b81754031fbd5ac20fe68

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BuyMeACoffeeSupportes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BuyMeACoffeeSupportes
  pod 'ObjectMapper'
  pod 'ReachabilitySwift'
  pod 'R.swift'
  pod 'Kingfisher'
  pod 'PKHUD'
  pod 'Giphy'
  pod 'ISEmojiView'

  # Facebook
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  # Google
  pod 'GoogleSignIn'

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  pod 'Fabric'
  pod 'Crashlytics'
  
  # Chat
  pod 'TwilioChatClient'

end
```

**Comment by dnkoutso** [comment]
Without a sample app this is not possible for us to diagnose. I recommend uploading one but even better ask StackOverflow under `cocoapods` tag instead.

Going to preempitvely close but I will re-open once a sample is uploaded and a case is made that this is a cocoapods bug.

**Comment by ShakeebM** [comment]
@dnkoutso Uploading Source code to public platform is not permissible from office. that is the issue. 
what is happening is I installed some pods via cocoapod, it work fine for sometime. but after that i am getting error like any of the module is not found. after i do `pod deintegrate` and `pod install` again, the error will disappear. but it repeats after a while. can i share any specific file like xcode workspace or something like that to identify bug? or let me try to upload a sample of code to reproduce the issue.
