### ISSUE TITLE
info_plist DSL & NSPrincipalClass

### ISSUE THREAD

**Issue by beefon** [CocoaPods/CocoaPods#9514]
In my dev pod podspec I specify the following info.plist contents using DSL:

```ruby
    ss.test_spec 'UnitTests' do |test_spec|
        test_spec.source_files = 'UnitTests/Sources/**/*.{h,m,swift}'
        test_spec.resources = 'UnitTests/Resources/**/*.{json}'
        test_spec.info_plist = {
            'NSPrincipalClass' => 'MyPrincipalClass',
        }
    end  
```

However, after running `pod deintegrate & pod install` `Info.plist` file of unit tests has empty value for `NSPrincipalClass` key. How do I force it to work properly?

CocoaPods 1.9.0b2

**Comment by dnkoutso** [comment]
cc @amorde 

Can you please upload a sample app?

**Comment by amorde** [comment]
I tried with a fresh project and it seems to be working for me

<img width="760" alt="Screen Shot 2020-02-06 at 1 07 46 PM" src="https://user-images.githubusercontent.com/2281949/73978791-e54b9a00-48e1-11ea-960f-4d8ea632d6fe.png">

As mentioned a sample would be helpful here

**Comment by beefon** [comment]
I'm sorry, after trying it one more time I was able to see my class in plist. My fault. 
All the best!

**Comment by amorde** [comment]
No problem, glad it worked out 👍
