### ISSUE TITLE
关于pod update问题需要帮助

### ISSUE THREAD

**Issue by xuanInitial** [CocoaPods/CocoaPods#9515]
使用 source 'https://cdn.cocoapods.org/'
报错
![Uploading 16731580732453_.pic_hd.jpg…]()
![16261580731583_ pic_hd](https://user-images.githubusercontent.com/20314658/73654244-27988f80-46c6-11ea-98fe-cd3357ca63c5.jpg)
![16231580731572_ pic_hd](https://user-images.githubusercontent.com/20314658/73654250-2bc4ad00-46c6-11ea-92a3-7b1b5b922138.jpg)

使用  source 'https://github.com/CocoaPods/Specs.git'
报错
![16841580733656_ pic_hd](https://user-images.githubusercontent.com/20314658/73654280-3f701380-46c6-11ea-835f-b5d97a59b2ee.jpg)

请求帮助 应该如何做

pod是最新版本
![16981580734065_ pic_hd](https://user-images.githubusercontent.com/20314658/73654370-79411a00-46c6-11ea-8fdb-51c94c5171a3.jpg)

**Comment by dnkoutso** [comment]
We cannot understand this issue. Please ask in StackOverflow under `cocoapods` tag. From screenshots please use the `git` based master specs repo as it seems you can't reach the CDN one due to network issues.
