### ISSUE TITLE
I got this error and i dont know how to slove him 

### ISSUE THREAD

**Issue by Fightfx1** [CocoaPods/CocoaPods#9519]
the error that i got
from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:47:in `run'	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
from /usr/local/bin/pod:22:in `load'
from /usr/local/bin/pod:22:in `<main>'

i did use pod install on react native expo app

**Comment by dnkoutso** [comment]
Please ask in StackOverflow under `cocoapods` tag.

This issue does not meet our guidelines by not filling in the issue template and does not provide a sample app.

Closing pre-empitvely.
