### ISSUE TITLE
About multiple pod modules in one repository

### ISSUE THREAD

**Issue by robotan0921** [CocoaPods/CocoaPods#9526]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

I want to manage multiple pod modules in ONE repository (which is github private repo).
My ideal folder structure is below;
```
MyRepo/ (repo root)
|-- MyModuleA/
|          |----Sources/
|          |----MyModuleA.podspec
|
|-- MyModuleB/
|          |----Sources/
|          |----MyModuleB.podspec
|
....
```
And I want to write like this in Podfile;
```
pod 'MyModuleA', :git => 'https://github.com/myuser/MyRepo.git' (i know this is invalid)
pod 'MyModuleB', :git => 'https://github.com/myuser/MyRepo.git'
```

Do you know best practices in that case?

Or I am ok with another case that i can import a `MyModuleAB` which includes MyModuleA and MyModuleB.

Thank you for any help you can provide:)

**Comment by dnkoutso** [comment]
You can use `:path` there instead?

**Comment by robotan0921** [comment]
@dnkoutso thank you.
In case of using `:path`, MyRepo should be cloned at local before `pod install`?
Or `:path` can recognize URLs such as "https://github.com/myuser/MyRepo/ModuleA"?

Btw, I can install `MyModuleAB` including `MyModuleA` and `MyModuleB` using `subspec` in my podfile.

**Comment by paulb777** [comment]
The podspecs at https://github.com/firebase/firebase-ios-sdk are an example of multiple pods from a single repo.

**Comment by robotan0921** [comment]
@paulb777 thank you so much for your advise! 
It is a great repository I want to refer. I try it.
