### ISSUE TITLE
Add support for dSYMs when using XCFrameworks in CocoaPods 1.9.0.beta.x

### ISSUE THREAD

**Issue by radazzouz** [CocoaPods/CocoaPods#9530]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

---

- [x] I've searched the opened (and closed) issues and I found https://github.com/CocoaPods/CocoaPods/issues/1698, which is a different issue.

---

CocoaPods 1.9.3.beta.x added support for XCFrameworks (see https://github.com/CocoaPods/CocoaPods/issues/9148 and https://github.com/CocoaPods/CocoaPods/pull/9334). However, dSYMs are not currently supported.

At PSPDFKit, we currently bundle the CocoaPods artifact as the old fat `.frameworks`, and we plan on distributing XCFrameworks as soon as CocoaPods supports dSYMs in its latest stable version, as `dSYM` support is crucial for our customers.

## How the Manual Integration with dSYM supports works:

You can manually integrate XCFrameworks into your project and add the dSYMs using an `.xcfilelist`, as described in the second step of this guide here: https://pspdfkit.com/guides/ios/current/getting-started/integrating-pspdfkit/#integrating-the-xcframework

### Create the Local PSPDFKit CocoaPods Artifacts:

1. If you’re an existing customer, download PSPDFKit for iOS from the [customer portal](https://customers.pspdfkit.com/). Otherwise, if you don’t already have PSPDFKit, [sign up for our 60-day trial](https://pspdfkit.com/try/) and you will receive an email with the download instructions.
2. Copy `PSPDFKit.xcframework`, `PSPDFKitUI.xcframework`, `PSPDFKit-dSYMs`, and `PSPDFKitUI-dSYMs` in a writable location.
3. Remove `strip-bitcode.sh` and `strip-framework.sh` from `PSPDFKit.xcframework/*/PSPDFKit.framework`:

```sh
rm PSPDFKit.xcframework/*/PSPDFKit.framework/strip-*.sh
```
4.  Rename the `PSPDFKit-dSYMs` and `PSPDFKitUI-dSYMs` foldersto `PSPDFKit.dSYMs`, and `PSPDFKitUI.dSYMs` respectively.
5. Create an archive (`.zip` file) by compressing `PSPDFKit.xcframework`, `PSPDFKitUI.xcframework`, `PSPDFKit.dSYMs`, and `PSPDFKitUI.dSYMs` into `PSPDFKit.zip`.
6. Rename the resulting `Archive.zip` to `PSPDFKit.zip`.

### Integrate PSPDFKit using CocoaPods Beta in a Sample Project:

- Install CocoaPods beta on your Mac: `sudo gem install cocoapods --pre`. In my tests, I used 1.9.3.beta.3 in my tests
- Download the attached sample project ([CocoaPods-dSYM-Support.zip](https://github.com/CocoaPods/CocoaPods/files/4187431/CocoaPods-dSYM-Support.zip)) and unzip it.
- `cd` into the project directory: `cd CocoaPods-dSYM-Support/SwiftExample`
- Copy the CocoaPods artifacts (`PSPDFKit.zip`) in the root folder (`CocoaPods-dSYM-Support`).
- run `pod install`.
- Open the sample project in Xcode 11.3.1: `open SwiftExample/SwiftExample.xcworkspace`.
- Create an archive: In Xcode UI go to Product > Archive.
- Inspect the dSYMs in the archive an notice that the PSPDFKit dSYMs are not present.

<img width="405" alt="Screen Shot 2020-02-11 at 9 29 35 AM" src="https://user-images.githubusercontent.com/7443038/74246207-282aba80-4cb2-11ea-9444-67a746b9d739.png">

## Proposed Outcome:

- dSYMs should be automatically added when using XCFrameworks, just like when using fat `.frameworks`.

**Comment by dnkoutso** [comment]
@amorde didnt we add dSYM support in 1.9.x?

**Comment by amorde** [comment]
Hi @radazzouz 👋 

dSYM support was added by including a folder in the format `FrameworkName.dSYMs`, so in this case if the folders `PSPDFKit.dSYMs` and `PSPDFKitUI.dSYMS` exist, CocoaPods should pick those up and include it during the build. Did you try that and, if so, did it not work correctly?

**Comment by radazzouz** [comment]
Thanks for the prompt response, @amorde! 👍 

I just tested with the dSYM folders named `PSPDFKit.dSYMs`, and `PSPDFKitUI.dSYMs` instead of `PSPDFKit-dSYMs` and `PSPDFKitUI-dSYMs` and they dSYMS are still not present in the archive.

I also updated the instructions and the sample project's Podspec from the main comment so you can conveniently test it on your side.

**Comment by radazzouz** [comment]
BTW, when using the manual integration (see the [Manual-Integration-dSYM-Support.zip](https://github.com/CocoaPods/CocoaPods/files/4187519/Manual-Integration-dSYM-Support.zip) sample project), the dSYMs can be found in the archive on both iOS and Mac Catalyst:

| **iOS** | **Mac Catalyst** |
| --- | --- |
| <img width="405" alt="Screen Shot 2020-02-11 at 1 35 20 PM" src="https://user-images.githubusercontent.com/7443038/74267311-d1ce7380-4cd3-11ea-9836-0e1eecca07a2.png"> | <img width="405" alt="Screen Shot 2020-02-11 at 1 39 24 PM" src="https://user-images.githubusercontent.com/7443038/74267382-f296c900-4cd3-11ea-991d-f4eadfb0e9f3.png"> |

**Comment by amorde** [comment]
Hmm ok will need some time to look into this, thanks for the detailed report!

**Comment by amorde** [comment]
The names of the dSYMs are messing with the logic of finding the binary inside the `dSYM` bundle.

This is something we can fix, hopefully I'll have a PR up soon in time for 1.9. Thanks for the report!

**Comment by amorde** [comment]
@radazzouz I've pushed up a WIP fix for this on the `amorde/xcframework-dsyms` branch - if you get the chance, check it out and let me know if it works for you. I tested it against PSPDFKit and it worked for me.

**Comment by radazzouz** [comment]
Thanks @amorde! 👍 

I just pulled your branch and it did not work for me. Did you use the same sample project and the updated integration steps from the main comment?

**Comment by amorde** [comment]
Yes I did, thank so much for the sample + details instructions!

**Comment by radazzouz** [comment]
> What happened when you tried my branch?

Everything worked except for the dSYMs.Just like on 1.9.0.beta.3.

BTW, I used [these instructions](https://guides.cocoapods.org/using/unreleased-features#real-world-walk-through) to build locally.

> did it you see "Selected dsym [path]" in the build output?

No. Unfortunately, I did not.

**Comment by amorde** [comment]
Looks like I had some local changes that didn't get included in that commit - I pushed again, please give it another try when you can

**Comment by radazzouz** [comment]
Thank you so much, @amorde!

I confirm that it now works on both iOS and Mac Catalyst! 🎉 

| **iOS** | **Mac Catalyst** |
| --- | --- |
| <img width="462" alt="Screen Shot 2020-02-13 at 7 44 56 AM" src="https://user-images.githubusercontent.com/7443038/74436759-f68e2c80-4e34-11ea-91f1-f0600f7ac519.png"> | <img width="499" alt="Screen Shot 2020-02-13 at 7 45 19 AM" src="https://user-images.githubusercontent.com/7443038/74436767-fd1ca400-4e34-11ea-88eb-4fa358745edf.png"> |

**Comment by dnkoutso** [comment]
Will ship with final 1.9.0 release.
