### ISSUE TITLE
"Authentication token is invalid" could be more helpful

### ISSUE THREAD

**Issue by kornelski** [CocoaPods/CocoaPods#9531]
> [!] Authentication token is invalid or unverified. Either verify it with the email that was sent or register a new session.

This message doesn't tell me what command to use. I'd expect something:

> [!] Login expired. Run `pod <that command which I need>` to continue.

The actual command to log in is something unintuitive that I can't remember. I publish pods rarely enough that every time I do it my session expires, and every time I struggle to find the solution. It's frustrating.

`pod --help` doesn't contain words "register" or "session".

**Comment by dnkoutso** [comment]
PRs welcome!
