### ISSUE TITLE
Is the "Claim Cocoapod" form still valid?

### ISSUE THREAD

**Issue by john-mejia** [CocoaPods/CocoaPods#9532]
I've used the claim cocoapod form to claim a couple of cocoapods owned by my company who's owners are no longer employed here.

I have not gotten any response (or confirmation) so I'm curious if this form is still the proper way to do this, google-ing has not led me to a better answer. 

I'm happy to wait if it's just me being impatient, but want to make sure I started the process.

**Comment by amorde** [comment]
It is, apologies for the slow responses, the amount of time & number of people available to respond has lessened over time. But we do see it and will get to it. Thanks for your patience! :)

**Comment by john-mejia** [comment]
Thanks @amorde - In that case I will close this issue.
