### ISSUE TITLE
Problem in the 'Copy Pods Resources' phase when using static linking and the project name contains a "+".

### ISSUE THREAD

**Issue by Curtis-Halbrook** [CocoaPods/CocoaPods#9533]
🌈

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm experimenting with using `use_frameworks! :linkage => :static` in CocoaPods 1.9.0.beta.3.  What I am seeing is during building there is an error in running the shell script '[CP] Copy Pods Resources'. 

 Note that this **ONLY** happens when trying to build using static libraries; using the default linkage does not show this issue.

The problem I'm seeing is this message:

```
Resource "/[mypath]/DerivedData/iPhone/Build/Products/Debug-iphoneos/PrivacyKit+UI/PrivacyKit\+UI.bundle" not found. Run 'pod install' to update the copy resources script.
```
In this particular case, we have two private 'pods that we distribute to our apps, one with the core behavior and one with an optional user interface.  As you can see, we added "+UI" to the project name.  

Apparently, however, during the construction of the script '/[myproj]/Pods/Target Support Files/Pods-iPhone-resources.sh' that does the actual copy of the resources, an escape was added to the file name, making it 'PrivacyKit\\+UI.bundle'.

```
install_resource "${PODS_CONFIGURATION_BUILD_DIR}/PrivacyKit+UI/PrivacyKit\+UI.bundle"
```

When I manually change the above script to remove the backslash, the build completes and the app runs as expected.  (*And shaves over a second off of our startup time, thank you very much!*)

So, it's obviously something in the generator for the Pods-iPhone-Resources.sh file.  

### Stack

```
   CocoaPods : 1.9.0.beta.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ a96e84cf1a9795ccf2d672e30f98b6a1210e7cd2

               [redacted]

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-binary      : 0.4.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
nice probably a bug! Try PR?
