### ISSUE TITLE
Help :((

### ISSUE THREAD

**Issue by ThangTruong921** [CocoaPods/CocoaPods#9535]
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Dictionary+missing+%27%3B%27+after+key-value+pair+for+%22objects%22%2C+found+%22%22%0A++++%23++-------------------------------------------%0A++++%23++%09rootObject+%3D+4A1A7AFE23EC1FC3006B4257+%2F%2A+Project+object+%2A%2F%3B%0A++++%23++%7D%0A1143%3E++%0A+++++++%5E%0A++++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
Did you mean?  tap

**Comment by dnkoutso** [comment]
Sorry this is not an error report we can make sense of. Please re-open with the issue template filled in correctly.
