### ISSUE TITLE
[Podspec] Explicit setting of 'CFBundleIdentifier' in s.info_plist causes a warning

### ISSUE THREAD

**Issue by giofid** [CocoaPods/CocoaPods#9536]
As discussed [here]( #3032), when in the .podspec file we explicitly set the bundle identifier in this way

```
# in .podspec
s.info_plist = {
  'CFBundleIdentifier' => 'com.myorg.mylib'
}
```

XCode 11 gives a warning 

`warning: User-supplied CFBundleIdentifier value 'com.myorg.mylib' in the Info.plist must be the same as the PRODUCT_BUNDLE_IDENTIFIER build setting value 'org.cocoapods.mylib'`

**Comment by dnkoutso** [comment]
Probably a minor bug yes, care to make a PR?

**Comment by amorde** [comment]
For anyone interested in contributing, this is currently set here:

https://github.com/CocoaPods/CocoaPods/blob/a1c94aaaa21b3da318208c7426433753c0332716/lib/cocoapods/target/build_settings.rb#L901

This could potential be moved to somewhere a bit higher level such as here: 

https://github.com/CocoaPods/CocoaPods/blob/a1c94aaaa21b3da318208c7426433753c0332716/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L199-L220
