### ISSUE TITLE
Mojave (Mac OS 10.14.6): Failed to build gem native extension

### ISSUE THREAD

**Issue by MahmoudKhaled** [CocoaPods/CocoaPods#9538]
I have an error with install cocoapods by comand sudo gem install cocoapods

OSX 10.14.6
Xcode 11.3.1

ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/json-2.1.0/ext/json/ext/generator
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I /Library/Ruby/Site/2.3.0 -r ./siteconf20200214-2603-1amgo5q.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/json-2.1.0 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.1.0/gem_make.out

**Comment by dnkoutso** [comment]
This does not appear to be a cocoapods issue directly but rather maybe something related to your environment.

Try upgrading Ruby to 2.6.x

**Comment by MahmoudKhaled** [comment]
@dnkoutso 
Yes thats right i have updated Ruby to 2.6.3 and install command line tools for Xcode 11.3.1
i used theses command in terminal

curl -L https://get.rvm.io | bash -s stable
then 

rvm install ruby-2.6
then 
rvm use ruby-2.6.3

then 
rvm --default use 2.6.3

from this link 
https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/

**Comment by daseed** [comment]
Many thanks for your solution, same problem here, solved with your help !

**Comment by programmarchy** [comment]
May want to update the [Getting Started docs](https://guides.cocoapods.org/using/getting-started.html):

> You can use a Ruby Version manager, however we recommend that you use the standard Ruby available on macOS unless you know what you're doing.

Not sure which Ruby version is present on Catalina or Big Sur, but Mojave comes with Ruby 2.3.0 which can no longer build the cocoapods gem, so the "blessed" way of installing Cocoapods with the standard Ruby won't work for Mojave users.

**Comment by codybreene** [comment]
Thanks so much, this helped enormously, specifically with serving a Jekyll theme on localhost.

**Comment by zzafergok** [comment]
> @dnkoutso
> Yes thats right i have updated Ruby to 2.6.3 and install command line tools for Xcode 11.3.1
> i used theses command in terminal
> 
> curl -L https://get.rvm.io | bash -s stable
> then
> 
> rvm install ruby-2.6
> then
> rvm use ruby-2.6.3
> 
> then
> rvm --default use 2.6.3
> 
> from this link
> https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/

Thanks so much. You saved my day.

**Comment by IvanNextToJunior** [comment]
And mine too

**Comment by IvanNextToJunior** [comment]
> > @dnkoutso
> > Yes thats right i have updated Ruby to 2.6.3 and install command line tools for Xcode 11.3.1
> > i used theses command in terminal
> > curl -L https://get.rvm.io | bash -s stable
> > then
> > rvm install ruby-2.6
> > then
> > rvm use ruby-2.6.3
> > then
> > rvm --default use 2.6.3
> > from this link
> > https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/
> 
> Thanks so much. You saved my day.

And mine too

**Comment by phostann** [comment]
> @dnkoutso
> Yes thats right i have updated Ruby to 2.6.3 and install command line tools for Xcode 11.3.1
> i used theses command in terminal
> 
> curl -L https://get.rvm.io | bash -s stable
> then
> 
> rvm install ruby-2.6
> then
> rvm use ruby-2.6.3
> 
> then
> rvm --default use 2.6.3
> 
> from this link
> https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/

Thank you so much, it's useful for me.

**Comment by CesarRN** [comment]
Requirements installation failed with status: 1.

**Comment by Berlin-Koeln** [comment]
> @dnkoutso
> Yes thats right i have updated Ruby to 2.6.3 and install command line tools for Xcode 11.3.1
> i used theses command in terminal
> 
> curl -L https://get.rvm.io | bash -s stable
> then
> 
> rvm install ruby-2.6
> then
> rvm use ruby-2.6.3
> 
> then
> rvm --default use 2.6.3
> 
> from this link
> https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/

when i type "rvm install ruby-2.6" i get error:
command not found: rvm

**Comment by alextapia007** [comment]
after curl -L https://get.rvm.io | bash -s stable
show you a message * To start using RVM you need to run...
try copy and return 
then
rvm install ruby-2.6

then
rvm use ruby-2.6.*

then
rvm --default use 2.6.*

for me 2.6.6

**Comment by alextapia007** [comment]
> > @dnkoutso
> > Yes thats right i have updated Ruby to 2.6.3 and install command line tools for Xcode 11.3.1
> > i used theses command in terminal
> > curl -L https://get.rvm.io | bash -s stable
> > then
> > rvm install ruby-2.6
> > then
> > rvm use ruby-2.6.3
> > then
> > rvm --default use 2.6.3
> > from this link
> > https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/
> 
> when i type "rvm install ruby-2.6" i get error:
> command not found: rvm

after curl -L https://get.rvm.io | bash -s stable
show you a message * To start using RVM you need to run...
try copy and return
then
rvm install ruby-2.6

then
rvm use ruby-2.6.*

then
rvm --default use 2.6.*

for me 2.6.6

**Comment by Maham-At-Sys** [comment]
> @dnkoutso Yes thats right i have updated Ruby to 2.6.3 and install command line tools for Xcode 11.3.1 i used theses command in terminal
> 
> curl -L https://get.rvm.io | bash -s stable then
> 
> rvm install ruby-2.6 then rvm use ruby-2.6.3
> 
> then rvm --default use 2.6.3
> 
> from this link https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/

Thanks for the great suggestion

**Comment by DavidHuang12345678** [comment]
> @dnkoutso Yes thats right i have updated Ruby to 2.6.3 and install command line tools for Xcode 11.3.1 i used theses command in terminal
> 
> curl -L https://get.rvm.io | bash -s stable then
> 
> rvm install ruby-2.6 then rvm use ruby-2.6.3
> 
> then rvm --default use 2.6.3
> 
> from this link https://codingpad.maryspad.com/2017/04/29/update-mac-os-x-to-the-current-version-of-ruby/

Thanks a lot, it's useful
