### ISSUE TITLE
Error while installing SDWebImage  on my mac. 

### ISSUE THREAD

**Issue by droriikar** [CocoaPods/CocoaPods#9544]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run  pod try SDWebImage

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Install DWebImage correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
I received an error 

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
Setup completed
Updating spec repositories

Trying SDWebImage

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod try SDWebImage
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.0.beta.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ c3cf10d1420809c8ae15c799b2154e82db59c2ef

```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target ’Spottr’ do
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'Alamofire', '~> 3.0'
pod 'KeychainSwift', '~> 3.0'
pod 'ONOSideMenuViewController',  :podspec => 'ONOSideMenuViewController.podspec'
pod 'CryptoSwift'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
platform :ios, '8.0'
pod 'SDWebImage', '~>3.7'
use_frameworks!
#pod 'Fabric'
#pod 'Crashlytics'

end

target 'ReshefTests' do
    pod 'Alamofire', '~> 3.0'
    pod 'KeychainSwift', '~> 3.0'
    pod 'ONOSideMenuViewController',  :podspec => 'ONOSideMenuViewController.podspec'
    pod 'CryptoSwift'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'


end

target 'ReshefUITests' do
    pod 'Alamofire', '~> 3.0'
    pod 'KeychainSwift', '~> 3.0'
    pod 'ONOSideMenuViewController',  :podspec => 'ONOSideMenuViewController.podspec'
    pod 'CryptoSwift'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'


end
```

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.3/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.3/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.3/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.3/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60root%27+for+false%3AFalseClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - error pod try MaterialComponents
   https://github.com/CocoaPods/CocoaPods/issues/9452 [closed] [1 comment]
   6 weeks ago

 - pod try BEMCheckBox stacktrace
   https://github.com/CocoaPods/CocoaPods/issues/9415 [closed] [1 comment]
   17 Dec 2019

 - pod install UrbanAirship-iOS-SDK failed
   https://github.com/CocoaPods/CocoaPods/issues/9403 [closed] [5 comments]
   13 Dec 2019

and 2 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60root%27%20for%20false%3AFalseClass&type=Issues&utf8=✓

**Comment by droriikar** [comment]
Any ideas what I need to do to fix this issue?

**Comment by amorde** [comment]
Looks like this is the same as https://github.com/CocoaPods/cocoapods-try/issues/63 - that issue is still open. I don't believe there is any workaround currently. Contributions are welcome!
