### ISSUE TITLE
FIRAuth, has been renamed to Auth Error.

### ISSUE THREAD

**Issue by hoseikijima** [CocoaPods/CocoaPods#9545]
Im trying to create a social media application on Xcode which needs Firebase and Cocoapods. I inputted the Firebase Elements such as Firebase/Auth, Firebase/Storage, and Firebase/Database. But for some reason, I try to run my build but it fails saying that "FIRAuth, had been renamed to Auth. Please correct me if I'm wrong but I think there is an issue with Cocoapods. Could you guys help me please. Thank you!

**Comment by dnkoutso** [comment]
This seems like an issue to file with Firebase repo. This so far does not appear to be an issue with CocoaPods and also this issue does not conform to the issue template.

Please ask on the Firebase repo instead.

**Comment by paulb777** [comment]
See https://stackoverflow.com/a/44559163/556617
