### ISSUE TITLE
Pod not linking to its vendored library

### ISSUE THREAD

**Issue by 666tos** [CocoaPods/CocoaPods#9548]
This is follow-up bug of https://github.com/CocoaPods/CocoaPods/issues/8454

@codecaffeine, @gregcotten, @arielpollack, @zwaldowski are you still interested in solution?

Bug is still present in CocoaPods 1.8.4

Let's say we have project `X`, which depends on pod `A`.
Pod `A` has `B` as dependency.
Pod `B` contains static libraries.
1.8.4 does not generate LIBRARY_SEARCH_PATHS, comparing to 1.5.3, which is causing ld: library not found linker error

Temporary solution is to add 
`LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/PodB/MY_LIBS_FOLDER"`
manually. That can be achieved in multiple ways:

1. For project `X`, track `/Pods/Target Support Files/PodA/PodA.xcconfig` by source control and manually add `LIBRARY_SEARCH_PATHS`. Each time `pod install/update` is performed, config must be reverted.
2. Edit `post_install` hook in `Podfile` of project `X`
3. Edit `podspec` of Pod `A` to include extra `LIBRARY_SEARCH_PATHS` as

**Comment by dnkoutso** [comment]
This is intentional fix otherwise Pod B would be linked in both Pod A and the user target.

**Comment by 666tos** [comment]
But currently it's not linked anywhere
