### ISSUE TITLE
subspec defined in podspec should have dependency requirement equal to the parent podspec

### ISSUE THREAD

**Issue by mobileben** [CocoaPods/CocoaPods#9550]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I'm working on a tool to extract some information from the podspec. In my code to go through the subspec dependencies, I was finding the wrong version of the subspec was being used. This is because the `Dependency` from `Pod::Specification::dependencies` has `requirement` set to `default` (>=0).

It seems to me this should really be set to what the parent is. 
An example of this is I was using AFNetworking 2.6.3. When going through the subspec dependencies, the `Dependency.requirement` is >=0. It would more ideally be 2.6.3.

As a slight addition, it would be helpful to have comparison operators for requirements. Although it wouldn't matter so much if dependency requirement had the same value as it's parent.

**Comment by dnkoutso** [comment]
I do not understand what the issue, improvement or expectation is here. It seems you are invoking some of these methods from a tool which is fine, what is missing?

**Comment by paulb777** [comment]
Right, a subspec only specifies a subset of a selected pods from the parent. They cannot be versioned differently.

**Comment by mobileben** [comment]
Correct. The problem is the dependency requirement for the subspec is reported as >= 0. Not the version of the parent. I was just saying it ideally helps if it is set to the parents version. 

I had a method which finds the spec based on name and requirement. 

I did work around it, but effectively it was done by comparing with `default` and setting to the parent value. Just seems like a hack. 

Technically, they are "versioned differently". If I am using the Podspecs for AFNetworking version 2.6.3, the dependencies list the requirement as >= 0. So when looking up the spec, it returns the most recent version.
