### ISSUE TITLE
How to import project's module in development pods?

### ISSUE THREAD

**Issue by magic3584** [CocoaPods/CocoaPods#9563]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

## First, it is not an issue, but I haven't get any answer in [stackoverflow](https://stackoverflow.com/questions/60317009/how-to-import-pods-in-development-pods-written-in-swift-with-pods-written-in-oc), so I come here to seek for help, sorry about this.

# Report

## What did you do?

My project is Demo which has two pods: A is development pods written in swift, B is project's pods and written in OC.

The pod file of project is like this:

```` ruby
s.subspec "A" do |ss|
    ss.dependency 'B'
end
````
## What did you expect to happen?

import successfully

## What happened instead?

I wanna import B in file in A but it shows the error: No such module 'B'.

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
What is the module map that is generated when you integrate your project? Can you please attach a sample?

**Comment by magic3584** [comment]
@dnkoutso Hi, I have made a demo [github](https://github.com/magic3584/PodsDemo).

Let me specify the project:

**A** and **B** are both pods, and subspec of **A** is written in Objective-C. Although they are all subspec of demo, sometimes I need use functions of **A** in **B**.
Now because I add `#import <AFNetworking/AFNetworking.h>`  in **PodsDemo-Bridging-Header**, so I can use **A** in demo project  like line 19 in **AppDelegate.swift** . But I cannot use **AFNetworking** in  **B.swift** in **B**.

Could u please tell me how can I make it? Is that possible?

Thanks

**Comment by magic3584** [comment]
Hello？
