### ISSUE TITLE
[Enhancement] Specify path to podspec in repo

### ISSUE THREAD

**Issue by patrickbdev** [CocoaPods/CocoaPods#9573]
This repo for example contains the podspec one folder down in "Superpowered"
https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform

It would be great if when we're specifying a ":site", we can specify the path as well.

**Comment by dnkoutso** [comment]
If you mean specifying `:path` in a podspec `dependency` then this is intentionally not allowed.
