### ISSUE TITLE
Is it possible to use cocoapods to embed dependences in a framework?

### ISSUE THREAD

**Issue by johntmcintosh** [CocoaPods/CocoaPods#9581]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Use cocoapods to include dependencies as static libraries inside of a dynamic framework, without exposing the dependencies to the parent app the will be consuming the dynamic framework.

I am developing a closed source framework. We would like to be able to use cocoapods to manage dependencies of the framework without forcing someone integrating the framework to need to care which dependencies we are using. My impression had been that we could do this by linking the dependencies as static libraries into the parent dynamic framework. 

## What did you expect to happen?

Be able to compile the parent app that is embedding my dynamic framework.

## What happened instead?

When using this setup, the framework itself compiles, but after embedding the framework in the parent app, the parent app compilation fails with:

> Cannot load underlying module for '_dependency name_'

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C505)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /Users/jtm/.rubies/ruby-2.6.5/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ ed08eebab42ae8458ab7004ce8751529f7cbddfc
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/jtm/.gem/ruby/2.6.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-mangle      : 1.0.1
cocoapods-packager    : 1.5.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '13.0'

target 'MyFramework' do
  inhibit_all_warnings!
  
  pod 'Kingfisher', '5.13.0'
end
```

## Project that demonstrates the issue

I've created a sample project demonstrating this here. You should be able to download, launch the workspace, and compile the `DemoApp` to see the compilation error in question. There are only three commits in the repo history, which clearly document the steps taken to get the project to this state: https://github.com/johntmcintosh/library-with-embedded-pods/tree/master

Thanks!

**Comment by dnkoutso** [comment]
The setup you have is supported in the `Podfile` but i think for not exposing those dependencies you would have to configure your "MyFramework" target not to export them something that CocoaPods won't do currently.

**Comment by johntmcintosh** [comment]
Thanks @dnkoutso . I guess there are a couple of levels of "not exposing" that could apply, so I'll clarify a little to be sure we're on the same page.

My understanding from https://forums.swift.org/t/update-on-implementation-only-imports/26996 is that any Swift dependency that's statically linked to a framework will be "exposed" to the parent app in the sense that the parent can import the framework and then be able to make calls against the public API of the child dependency. I've been able to verify this without cocoapods with a different sample project and manual integration of the libraries. I understand and am Ok with this limitation.

By "not exposing" I primarily mean that I don't want the developer of the parent app to need to manually link (or use cocoapods to link) my dependencies into their app. I'd like them to be embedded in my framework to simplify the integration process.

I created a separate test project (https://github.com/johntmcintosh/static-libaries-in-dynamic-framework) that has the following structure:

- Parent app
  - Dynamic framework linked in to parent
    - Static libraries embedded in dynamic framework

And in this project was able to validate that manually created static libraries can be manually embedded in the dynamic framework, and then I was able to build with the parent app only needing to know about and embed the dynamic framework.

In that case, what is different about the way cocoapods would be treating the static libraries it's managing such that they aren't embedded, while the manually linked ones are?

**Comment by amorde** [comment]
The problem with this approach is that if the user's app or any of its dependencies _also_ depends on the thing your framework depends on, it will end up being linked twice and lead to duplicate symbols.

Usually the "standard" approach is to link it manually to your framework and hide it from the user, _or_ declare the pod as a dependency in your podspec. The podspec route won't be the exact same as your Podfile setup though.

Here's a similar issue with more details: https://github.com/CocoaPods/CocoaPods/issues/9559#issuecomment-595382323

**Comment by johntmcintosh** [comment]
Thanks @amorde. I'm aware of the risks when doing this, but mostly wanted to understand why it didn't seem feasible. Since the standard approach of linking manually does work without the integrating app needing any extra steps, I was surprised that I wasn't able to link the dependencies with cocopods and get the same result.

**Comment by amorde** [comment]
It should work - will take a look at the example project when I get the chance
