### ISSUE TITLE
Using podspec option for podfile in subfolder in private repo

### ISSUE THREAD

**Issue by johanlantz** [CocoaPods/CocoaPods#9584]
We are using a private repo that has two different podspec files, both located in subfolders.

From the last option here:
https://guides.cocoapods.org/syntax/podfile.html#pod

I understand I can use something like:
pod "liquiddsp", :podspec => 'https://github.com/mycompany/myproject/tree/master/external/liquiddsp/liquiddsp.podspec'

The path I provide is correct since if I paste it into Chrome, the correct file opens.

However when doing pod install, I get a 404 and I assume this is because its a private repo.

The comment to the solution here:
https://stackoverflow.com/questions/35488215/when-pointing-to-a-github-repo-with-cocoapods-is-there-a-way-to-specify-a-subfo/35509484

indicates the same problem and it is unanswered.

So, if I have this legacy project with podspec files in subfolders inside a private repo, is there a way to point to the .podspec from the Podfile that I am missing?

**Comment by dnkoutso** [comment]
Can you not use `:path`? `pod 'MyPod', :path => '/path/to/mypod.podspec'`?
