### ISSUE TITLE
Duplicate frameworks linking on modular architecture

### ISSUE THREAD

**Issue by rickrvo** [CocoaPods/CocoaPods#9586]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have the same problem as #5768 , when I did a modularization of the app on the latest 1.8.4 cocoapods version... I really want to use dynamic framework instead of a static one... 
this is my podfile:
https://guides.github.com/features/mastering-markdown/
```
platform :ios, '10.0'

workspace 'MyAppName'
#use_modular_headers!
use_frameworks!

def shared_pods
...
pod 'Firebase', :modular_headers => true
pod 'FirebaseRemoteConfig', :modular_headers => true
pod 'FirebaseAnalytics', :modular_headers => true
pod 'FirebaseDynamicLinks', :modular_headers => true
pod 'FirebaseMessaging', :modular_headers => true
pod 'FacebookCore', :modular_headers => true
pod 'FacebookLogin', :modular_headers => true
pod 'FacebookShare', :modular_headers => true
pod 'GoogleSignIn', :modular_headers => true
pod 'GoogleAnalytics', :modular_headers => true
pod 'GoogleIDFASupport', :modular_headers => true
...
pod 'GoogleMaps', :modular_headers => true
pod 'GooglePlaces', :modular_headers => true

end

def application_pods

pod 'SideMenu', :modular_headers => true
...
end

def core_application_pods

pod 'Alamofire', :modular_headers => true
...
end

target 'Application' do

project 'Application/Application.xcodeproj'

# Pods for Application
shared_pods
application_pods

target 'ApplicationTests' do
inherit! :search_paths
# Pods for testing
end

target 'ApplicationUITests' do
# Pods for testing
end
end  

target 'Core' do

project 'Core/Core.xcodeproj'

# Pods for Core

shared_pods
core_application_pods

target 'CoreTests' do
  inherit! :search_paths
  # Pods for testing
end
end

 # Static libraries
static_libraries = ['GoogleMaps', 'GoogleMapsBase', 'GoogleMapsCore']#, 'GooglePlaces']

post_install do |installer|
puts "Running post_install script"

puts "Fix static_libraries"
installer.aggregate_targets.each do |aggregate_target|
    #unless ['Pods-Application'].include? aggregate_target.name ## I tried with and without this 
        aggregate_target.xcconfigs.each do |config_name, config_file|
            config_file.frameworks.subtract(static_libraries)
            xcconfig_path = aggregate_target.xcconfig_path(config_name)
            config_file.save_as(xcconfig_path)
        end
    #end
end

puts "Retarget Swift build version to 4.2 in Pods"
installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
    end
end
end
```

## What did you expect to happen?

I expected the pods to work as they where working before the modularization. I had everything on 1 project and I changed it to Application and a dynamic framework called Core

## What happened instead?

I got a BAD_ACCESS crash with no debug information...

The crash is happening with GoogleMaps pod. It happens when I open the View Controller which contains the map.

When I turn on Zombie debug I get:

> objc[4150]: Class _NSZombie_GMSSTSDataRequest is implemented in both ?? (0x29bb5ec90) and ?? (0x29321ad50). One of the two will be used. Which one is undefined.
> objc[4150]: Class _NSZombie_GMSTileRequest is implemented in both ?? (0x29bb4fa50) and ?? (0x29a936650). One of the two will be used. Which one is undefined.
> objc[4150]: Class _NSZombie_GMSx_GMPCLabelGroup is implemented in both ?? (0x29bbab650) and ?? (0x29bbabd50). One of the two will be used. Which one is undefined.
> objc[4150]: Class _NSZombie_GMSx_GMPCLabelRenderOp is implemented in both ?? (0x29bbab590) and ?? (0x29bbabd10). One of the two will be used. Which one is undefined.
> objc[4150]: Class _NSZombie_GMSFeatureStyle is implemented in both ?? (0x29bbaf3d0) and ?? (0x29bbaca10). One of the two will be used. Which one is undefined.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 0c93f56ebb7e5c13c35536e8f951e2a8a305f0bc
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by rickrvo** [comment]
I found a workaround.. if anyone is facing this problem and needs a quick fix check [here](https://stackoverflow.com/questions/60343664/googlemaps-sdk-crashing-app-after-modularization-of-project/60546190#60546190)

**Comment by amorde** [comment]
If you statically link a dependency into a dynamic framework _and_ an app, and then link that framework into the app, you will end up with duplicate symbols. Is that what's happening here?

**Comment by rickrvo** [comment]
Not sure.. but I don't think thats the case. GoogleMaps and GooglePlaces are dynamic frameworks right? they generate a ".framework" file not a ".a" file. If I have GoogleMaps as a shared pod on both Application and Core projects it ends up duplicated

**Comment by paulb777** [comment]
Looks like a static framework:

```
$ file Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps
Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps: Mach-O universal binary with 4 architectures: [i386:Mach-O object i386] [x86_64] [arm_v7] [arm64]
Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps (for architecture i386):	Mach-O object i386
Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps (for architecture x86_64):	Mach-O 64-bit object x86_64
Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps (for architecture armv7):	Mach-O object arm_v7
Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps (for architecture arm64):	Mach-O 64-bit object arm64
```

**Comment by amorde** [comment]
Yep figured - `.framework` bundles can contain either statically linked or dynamically linked binaries.

@paulb777 is there any way to get a dynamically linked version of the `GoogleMaps` SDK?

**Comment by paulb777** [comment]
Not that I know of. Probably best to reorganize app to link it once or follow up on `GoogleMaps` support channels

**Comment by rickrvo** [comment]
So the only option for a modular workspace project to use dynamic frameworks is to create a custom framework that imports all static frameworks and use that as a shell interface for the static ones?

**Comment by paulb777** [comment]
Or use all static frameworks for modularization.

**Comment by amorde** [comment]
Going to close this as there doesn't seem to be anything CocoaPods can do here - this is an inherent limitation imposed by the linker.

**Comment by haofanning** [comment]
Any solutions ? I'm facing the same problem

**Comment by trimech-hsan** [comment]
Any solutions ? I'm facing the same problem
I have the same issue with my custom xcframework
