### ISSUE TITLE
installed , but some error

### ISSUE THREAD

**Issue by xclidongbo** [CocoaPods/CocoaPods#9589]
$ sudo gem install cocoapods
Password:
Fetching ffi-1.12.2.gem
Fetching ethon-0.12.0.gem
Fetching cocoapods-core-1.9.0.gem
Fetching typhoeus-1.3.1.gem
Fetching cocoapods-1.9.0.gem
Building native extensions. This could take a while...
Successfully installed ffi-1.12.2
Successfully installed ethon-0.12.0
Successfully installed typhoeus-1.3.1
Successfully installed cocoapods-core-1.9.0
Successfully installed cocoapods-1.9.0
Parsing documentation for ffi-1.12.2
Installing ri documentation for ffi-1.12.2
Parsing documentation for ethon-0.12.0
Installing ri documentation for ethon-0.12.0
Parsing documentation for typhoeus-1.3.1
Installing ri documentation for typhoeus-1.3.1
Parsing documentation for cocoapods-core-1.9.0
Installing ri documentation for cocoapods-core-1.9.0
Parsing documentation for cocoapods-1.9.0
Installing ri documentation for cocoapods-1.9.0
Done installing documentation for ffi, ethon, typhoeus, cocoapods-core, cocoapods after 34 seconds
5 gems installed

$ pod --version
zsh: command not found: pod

**Comment by dnkoutso** [comment]
Please ask in StackOverflow under `cocoapods` or tooling issues. This appears to be a system specific issue.
