### ISSUE TITLE
iOS13.3.1 swift project can't run in real device, but the simulator is ok

### ISSUE THREAD

**Issue by FishWithoutWings** [CocoaPods/CocoaPods#9591]
<img width="1150" alt="截屏2020-03-05上午11 40 00" src="https://user-images.githubusercontent.com/46670185/75945752-1665bd00-5ed6-11ea-8c48-253188099f07.png">

pod --version 1.4.0

Podfile
platform :ios, '10.0'

target 'YYCode' do
  use_frameworks!

    pod 'Alamofire'
    pod 'SnapKit'
    pod 'RealmSwift'
    pod 'Kingfisher'

end

<img width="630" alt="截屏2020-03-05上午11 39 05" src="https://user-images.githubusercontent.com/46670185/75945761-1cf43480-5ed6-11ea-8f90-4f0fe5e0b209.png">

crash error:
dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/YYCode
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/Frameworks/Alamofire.framework/Alamofire'

	/private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/Frameworks/Alamofire.framework/Alamofire'

	/private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/Frameworks/Alamofire.framework/Alamofire: stat() failed with errno=1
	/private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/Frameworks/Alamofire.framework/Alamofire'

	/private/var/containers/Bundle/Application/EC1DDD60-6E1C-4BC4-AEA9-EDA95016B7F9/YYCode.app/Frameworks/Alamofire.framework/Alamofire: stat() failed with errno=1

**Comment by dnkoutso** [comment]
Seems like a signing issue and not related to CocoaPods. I have built a sample app for device with Alamofire and it worked. Please ask in StackOverflow instead.

**Comment by paulb777** [comment]
Probably https://stackoverflow.com/questions/60096258/library-not-loaded-rpath-fblpromises-framework-fblpromises-ios-13-3-1
