### ISSUE TITLE
Static C++ library as a part of private/local pod

### ISSUE THREAD

**Issue by KrillioSokolov** [CocoaPods/CocoaPods#9596]
First of all, thank you very much for contributing best dependency system for iOS. 

I have a swift project which will be used as a private pod. This project has C++ static library 'euscp.a', with Objc-c wrapper. This is how my podspec looks like: 

Pod::Spec.new do |s|

  s.name         = "ElectronicDigitalSignature"
  s.version      = "0.1.0"
  s.summary      = "SDK for electronic signing documents"
  s.description  = "SDK for electronic signing documents. Developed by iOS dream team."
  s.homepage   = "https://git.microaws.com/p24-ios/electronic_digital_signature-ios"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author    = "PrivatBank"
  
  s.platform     = :ios, "9.0"
  s.swift_version = "5.0"
  s.source    = { :git => "https://git.microaws.com/p24-ios/electronic_digital_signature-ios", :tag => '0.1.0' }
  s.pod_target_xcconfig = {'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) PC_STATIC_LIBS OS_IOS',
		'USER_HEADER_SEARCH_PATHS' => '"${PROJECT_DIR}/ElectronicDigitalSignature/.."/**' }
  ###s.libraries = 'euscp', 'xml2', 'c++' 
  s.resources = "ElectronicDigitalSignature/**/*.{png,jpeg,jpg,storyboard,xib,xcassets,xcdatamodeld,strings}"

  s.source_files  = "ElectronicDigitalSignature/SDK/**/*.{h,m,mm,cpp,c,a,swift}"
  s.vendored_libraries = 'ElectronicDigitalSignature/**/euscp.a'

  s.frameworks = "Foundation", "UIKit"
	
  s.dependency "SnapKit"
  s.dependency "Alamofire"
  s.dependency "ios-sdk-extensions"
  s.dependency "shared-ios"
  
end

When I connect in my main project this Pod (as a local developer pod or from branch), I got an error: ld: library not found for -leuscp
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I make research an issue with the same problem, but without a result. I also try to link it manually, but is still error.  Can anybody help me with this problem, please? 

<img width="1208" alt="Screen Shot 2020-03-06 at 13 24 00" src="https://user-images.githubusercontent.com/23337273/76079758-0caf8880-5fae-11ea-8404-4c2ac224aa45.png">
<img width="507" alt="Screen Shot 2020-03-06 at 13 23 32" src="https://user-images.githubusercontent.com/23337273/76079765-0f11e280-5fae-11ea-8d9e-99505d1110ac.png">

<img width="441" alt="Screen Shot 2020-03-06 at 13 45 48" src="https://user-images.githubusercontent.com/23337273/76080998-d45d7980-5fb0-11ea-8229-fe399820a98a.png">

**Comment by amorde** [comment]
Can you try renaming your binary to `libeuscp.a`? Also, looks like there's an extra `/` character in the `vendored_libraries` value.

**Comment by KrillioSokolov** [comment]
@amorde, it is a brilliant answer with adding "lib" in the file name.   Can you explain how it works, please?

**Comment by amorde** [comment]
This is the behavior of gcc and clang's linker flags - from [gcc's docs](https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/Link-Options.html#Link-Options):

> -l library
> ...
> The linker searches a standard list of directories for the library, which is actually a file named liblibrary.a. The linker then uses this file as if it had been specified precisely by name.

So using `-lmylib` expects a file named `libmylib.a`
