### ISSUE TITLE
Building as Static Library using a property like :modular_headers

### ISSUE THREAD

**Issue by celtaheaven** [CocoaPods/CocoaPods#9600]
I wanted to know if there is any property that I can force to build as static library. Tried to use as modular_headers but it doesn't work when I check through `pod.build_as_static_library?`.

As for now I'm using this (CocoaPods 1.9.0): 

> $static_frameworks = ['RNPermissions', 'Permission-Camera', 'Permission-PhotoLibrary', 'Permission-Microphone']

>pre_install do |installer|
> installer.pod_targets.each do |pod|
>    if $static_frameworks.include?(pod.name)
>      puts "Overriding as static framework:#{pod.name}"
>      def pod.build_type;
>        Pod::BuildType.static_library
>      end
>    end
>  end
>end

**Comment by dnkoutso** [comment]
I am not sure i understand the question properly. It is best to ask StackOverflow under `cocoapods` tag for this.
