### ISSUE TITLE
Failed to build gem native extension. Header file missing,

### ISSUE THREAD

**Issue by mscherer82** [CocoaPods/CocoaPods#9602]
`sudo gem install cocoapods`

I've installed ruby 2.3.0 but I got the following error:

```
ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I /Library/Ruby/Site/2.3.0 -r ./siteconf20200309-67350-e0q2jt.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/ffi-1.12.2/gem_make.out
```

**Comment by dnkoutso** [comment]
Seems like a ruby issue on your system. Please ask in StackOverflow instead.

**Comment by mscherer82** [comment]
But wouldn't it be helpful to at least mention the prerequisites in the docs?

**Comment by nhnicwaller** [comment]
This question has been asked on StackOverflow:

- [gem native extension error while installing cocoapods](https://stackoverflow.com/q/60585707/190298)

And on AskDifferent, the Apple-specific site on Stack Exchange:

- [Installing cocoapods on macOS Mojave](https://apple.stackexchange.com/q/384382/18101)

**Comment by riodw** [comment]
I had the same problem on macOS Mojave 10.14.16

A few threads eventually lead me [here](https://apple.stackexchange.com/questions/384382/installing-cocoapods-on-macos-mojave) which solved it for me:
> It looks like CocoaPods 1.9.0, the latest version as of this writing, depends on a newer version of Ruby than 2.3.7. But macOS Mojave only includes Ruby 2.3.7, so you have a few different options.
> 
> 1. Upgrade to macOS Catalina and get Ruby 2.6.3
> 2. Use Ruby Version Manager to install a newer version of Ruby
> 3. Install an older version of CocoaPods
> `sudo gem install cocoapods -v 1.8.4`


I did 3
`sudo gem install cocoapods -v 1.8.4`

I was installing Flutter, now `flutter doctor` says "Xcode - develop for iOS and macOS" is OK.

**Comment by roshit-omanakuttan** [comment]
I had a similar problem for macOS Catalina.
Here is what worked for me:

```
# brew cleanup -d -v    
# brew install cocoapods

```

**Comment by AyushKovind** [comment]
Hey, so I also had the same problem. This is probably happening because your computer has older version of ruby. So you need to first update your ruby. Mine worked for ruby 2.6.3 version.I got this solution from stackoverflow, 

You need to first open terminal  and put this code 
`curl -L https://get.rvm.io | bash -s stable`

Then put this command
`rvm install ruby-2.6`

This would install the ruby for you if it hasn' t been installed.After this just update the ruby to the new version 
`rvm use ruby-2.6.3`

After this just make ruby 2.6.3 your default 
`rvm --default use 2.6.3`

This would possibly fix your issue. You can now put the command 
`sudo gem install cocoapods`
And the command 
`pod setup`

I hope this was useful

**Comment by rohan20** [comment]
This occurs due to an issue with how xcode 11 is shipped on different MacOS versions. Read more here: https://stackoverflow.com/a/58226876/5066615

Worked for me.

**Comment by sabina-r** [comment]
@riodw You saved my life!!! another hour with that problem, and mac would have fallen out of my window. Thank you so much!!

**Comment by gaurav8809** [comment]
> I had a similar problem for macOS Catalina.
> Here is what worked for me:
> 
> ```
> # brew cleanup -d -v    
> # brew install cocoapods
> ```

It work for me
Thanks

**Comment by vimalswaroopj** [comment]
check this link I had same issue I solved using this https://stackoverflow.com/a/69158556/13503880

**Comment by BasemSaabneh** [comment]
# brew cleanup -d -v 
# brew install  /usr/local/bin cocoapods

**Comment by mann2108** [comment]
![image](https://user-images.githubusercontent.com/44433995/140190323-3ec1abf1-accb-4452-ab2e-54f046222907.png)

Getting this error on firing ridk install command, can anyone help me out?

**Comment by budostylz** [comment]
Get a Mac
