### ISSUE TITLE
[Feature Request] On-Demand Resource Support

### ISSUE THREAD

**Issue by Damonvvong** [CocoaPods/CocoaPods#9606]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# On-Demand Resource

On-demand resources are app contents that are hosted on the App Store and are separate from the related app bundle that you download. They enable smaller app bundles, faster downloads, and richer app content. The app requests sets of on-demand resources, and the operating system manages downloading and storage. The app uses the resources and then releases the request. After downloading, the resources may stay on the device through multiple launch cycles, making access even faster.

More infomation: https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/On_Demand_Resources_Guide/index.html

**But It is not support by Cocoapods.** 

Here are same problem at stackoverflow: https://stackoverflow.com/questions/51901563/ios-on-demand-resources-from-a-framework-or-cocoapod

# *.xcodeproj File Diff

if we want use **ODR**, `*.xcodeproj ` file must set options like this: 

## FileRef

```diff

-   25C339XXXXXXXXXXXXXXX2FD9 /* Test_ODR.bundle in Resources */ = {isa = PBXBuildFile; fileRef = 25C339XXXXXXXXXXXXXXX2FD9 /* Test_ODR.bundle */; };
+   25C339XXXXXXXXXXXXXXX2FD9 /* Test_ODR.bundle in Resources */ = {isa = PBXBuildFile; fileRef = 25C339XXXXXXXXXXXXXXX2FD9 /* Test_ODR.bundle */; settings = {ASSET_TAGS = (Tag, ); }; };

```

## Section

```diff
/* Begin PBXProject section */
    25C339XXXXXXXXXXXXXXX2FD9 /* Project object */ = {
      isa = PBXProject;
      attributes = {
+       KnownAssetTags = (
+         Tag,
+         Tag1,
+         Tag2,
+       );
```

# Question

no matter 

```ruby

s.resources    = 'ODRPodDemo/Assets/**/*.bundle'

```
and

```ruby

s.resource_bundles = {
    'ODRPodDemo' => ['ODRPodDemo/Assets/*.png']
}

```

did not support

# Request

whether there are some possible support `Pods`'s resource can use On-Demand Resource when `pod install` or `pod update` or not? Like this:

```ruby

s.on_demand_resources  = {
    'Tag1' => ['ODRPodDemo/Assets/*.png'],
    'Tag2' => ['ODRPodDemo/Assets/*.png']
}

```

**Comment by dnkoutso** [comment]
Yep could use some help on this but a good enhancement!

**Comment by Damonvvong** [comment]
@dnkoutso  So what can I help you ?

**Comment by dnkoutso** [comment]
of course! I would start with a proposal so other contributors can weigh in with feedback. See examples https://github.com/CocoaPods/CocoaPods/issues/8753 and https://github.com/CocoaPods/CocoaPods/issues/9099

**Comment by Damonvvong** [comment]
@dnkoutso  Do you have any good suggestions for this enhancement Or if you deal it, how would you solve this problem ?

**Comment by dnkoutso** [comment]
PR here https://github.com/CocoaPods/CocoaPods/pull/10812
