### ISSUE TITLE
Failed to import objective C header from Pod into Swift file.

### ISSUE THREAD

**Issue by Tejas7194** [CocoaPods/CocoaPods#9607]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Trying to add pod quantumgraph to 'xyz' plugin in my Xcode project.

## What did you expect to happen?

ℹ pod quantumgraph should be added successfully and its headers should be accessible into my plugin.

## What happened instead?

ℹ pod quantumgraph getting added successfully. but its QGSdk.h header is not accessible to my plugin classes. So what exactly Im doing wrong in podspec of my plugin.

## CocoaPods Environment

ℹ This is my Podspec:

Pod::Spec.new do |s|

    s.name             = "MyMediaQGraphPlugin"
    s.version          = '0.1.1'
    s.summary          = "MyMediaQGraphPlugin iOS."
    s.description      = <<-DESC
                          MyMediaQGraphPlugin analytics plugin for iOS.
                         DESC
    s.homepage         = "https://xyz:8fqTzT2v7UXAwu6RE6CV@bitbucket.org/media/MyMediaQGraphPlugin-ios.git"
    s.license          = 'MIT'
    s.author           = { "abc" => "abc@gmail.com" }
    s.source           = { :git => "https://abc:8fqTzT2v7UXAwu6RE6CV@bitbucket.org/media/MyMediaQGraphPlugin-ios.git", :tag => s.version.to_s }

    s.ios.deployment_target  = "10.0"
    s.platform     = :ios, '10.0'
    s.requires_arc = true
    s.swift_version = '5.1'
    s.frameworks = 'UserNotifications', 'UIKit', 'Foundation', 'UserNotificationsUI'
    s.source_files = 'PluginClasses/**/*.{swift,h,m}'
    s.resources = 'Resources/**/*.{storyboard,xib,xcassets,png,plist}'
    s.static_framework = true
    s.dependency 'quantumgraph'

    s.xcconfig =  { 'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
                'ENABLE_BITCODE' => 'YES',
                'SWIFT_VERSION' => '5.1',
    }
  end

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by amorde** [comment]
Looks like this wasn't investigated at all - based on the issue description I'm not sure what the issue is, but if you have an example project that reproduces this issue then I'd be happy to re-open
