### ISSUE TITLE
spec.compiler_flags ignored in local pod

### ISSUE THREAD

**Issue by NSExceptional** [CocoaPods/CocoaPods#9608]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Using [this podspec file](https://github.com/Flipboard/FLEX/blob/4.0/FLEX.podspec#L38) I installed `pod 'FLEX'` as a pod from my local machine (`:path => ...`).

## What did you expect to happen?

Cocoapods should respect the `spec.compiler_flags` line in the file above.

## What happened instead?

It did not; none of the custom compiler flags can be found anywhere in the project. I looked:
- In the Pods project under the FLEX target
- In the `Pods-FLEXample.*.xcconfig` files
- In the workspace by searching for either of the flags

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C505)
         Git : git version 2.16.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '13.0'

target 'FLEXample' do
  pod 'FLEX', :path => '~/Repos/FLEX'
end
```

## Project that demonstrates the issue

https://github.com/Flipboard/FLEX/tree/4.0

**Comment by dnkoutso** [comment]
The sample app link is broken with 404 can you upload or point to the right one?

**Comment by NSExceptional** [comment]
Weird, somehow I copied a branch URL with `/blob/<branch>` instead of `/tree/<branch`. Fixed!

**Comment by dnkoutso** [comment]
<img width="1792" alt="Screen_Shot_2020-03-12_at_3_29_25_PM" src="https://user-images.githubusercontent.com/310370/76572076-497bf380-6476-11ea-8a52-e5d680340744.png">

works for me with 1.9.0.

**Comment by NSExceptional** [comment]
Oh, I was looking in the wrong place. I wonder why Xcode doesn't bring the contents of that screen up in search results.

Thank you! Sorry for my confusion 🙃
