### ISSUE TITLE
Development Pod in Git Submodule 

### ISSUE THREAD

**Issue by ibrahimdevs** [CocoaPods/CocoaPods#9610]
Hello,

I read all related docs and comment, but can't find a real answer.

Here is my setup;
- Create "A Pod" and push to git.
- In my "B Project", add A Pod as git submodule in same level of Podfile.
- And add Podfile "A Pod" like this: pod 'APod', :path => 'submodule/APod/'

I can use this "A Pod" in my project, if I need, can update directly on A Pod in "development-pods" folder and because of it is submodule I can directly push changes. So, my team can pull this submodule and they have the latest version.

All wonderful but here is my question: Is this setup production ready? I mean can i directly archive and publish my "B Project"? All examples are using this setup for development, when finish development, they change this setup to remote private pod. 

I feel that i can use this submodule local pod system for production, but it's name is development, and all example opposite to me.

In documentation, I can't find my answer, can you help me? 

Thanks,

**Comment by dnkoutso** [comment]
If your question is whether development pods can be shipped then yes. We are using them extensively in our own project with hundreds of local pods and we ship our app every 2 weeks.

**Comment by dnkoutso** [comment]
I am not seeing an actual action item here such as an enhancement or bug so I am going to close and we can continue the discussion here. I will re-open if we find an area of improvement.
