### ISSUE TITLE
Trying to install cocoapod 'MaterialComponents/Dialogs', Error 416

### ISSUE THREAD

**Issue by gmhcode** [CocoaPods/CocoaPods#9611]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ This is what my Podfile looks like
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Delivery TipR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Delivery TipR
	pod 'MaterialComponents/Dialogs'

  target 'Delivery TipRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
Then I ran ``` pod install```

## What did you expect to happen?

ℹ  Install all pod dependencies correctly.

## What happened instead?

ℹ I got this error

### Error

```
JSON::ParserError - 416: unexpected token at '{
          "name": "UnitTests",
          "test_type": "unit",
          "source_files": [
            "components/Chips/tests/unit/*.{h,m,swift}",
            "components/Chips/tests/unit/supplemental/*.{h,m,swift}"
          ],
          "resources": "components/Chips/tests/unit/'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

## CocoaPods Environment

ℹ ### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ edc32cc393818cd581a1d4d24b163222c4e8d0e0

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Delivery TipR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Delivery TipR
	pod 'MaterialComponents/Dialogs'

  target 'Delivery TipRTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by dnkoutso** [comment]
Can you please run `pod cache clean --all` and try again?

**Comment by gmhcode** [comment]
> Can you please run `pod cache clean --all` and try again?

The same error occurs

**Comment by dnkoutso** [comment]
I was able to integrate successfully on a sample app:
```
The Gemfile's dependencies are satisfied
Analyzing dependencies
Downloading dependencies
Installing MDFInternationalization (2.0.0)
Installing MDFTextAccessibility (2.0.0)
Installing MaterialComponents (107.2.0)
\Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.
```

**Comment by gmhcode** [comment]
can you show me your podfile? I tried on a sample app and was able to install alamofire. But MaterialComponents still gave me the error

**Comment by dnkoutso** [comment]
```ruby
use_frameworks!
platform :ios, '12.0'

install! 'cocoapods'

target 'SampleApp' do
  use_frameworks!
  pod 'MaterialComponents/Dialogs'
end```

**Comment by gmhcode** [comment]
yea, still getting the same error

**Comment by dnkoutso** [comment]
sorry I am unsure what the issue will. We will need a sample app or clear reproducible steps for us ti diagnose given that it works here for me locally. I tried '9.0' platform also and it still worked and wiped out cache.

**Comment by shunnokw** [comment]
I have the same issue and I solved it by fully uninstall cocoapods (please also delete /.cocoapods)

**Comment by gmhcode** [comment]
well deleting /.cocoapods and re-installing then trying to add the cocoapod to my project got me a different error.

`SON::ParserError - 767: unexpected token at ''
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `map'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/greghughes/.rvm/rubies/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'`

**Comment by gmhcode** [comment]
fixed it, here's my command list after I got that last error
rm -rf ~/.cocoapods/repos/trunk/
pod install
(got another error)
pod cache clean --all   
pod install 
(got another error)
rm -rf ~/.cocoapods/repos/trunk/
pod install

then it worked

**Comment by rushabhshah065** [comment]
> fixed it, here's my command list after I got that last error
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> (got another error)
> 
> pod cache clean --all
> pod install
> (got another error)
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> 
> then it worked
> 
> So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> 
> gem list --local | grep cocoapods
> sudo gem uninstall (all the items in the list)
> sudo rm -rf ~/.cocoapods
> sudo gem install cocoapods
> cd (PROJECT DIRECTORY)
> pod init
> (put cocoapod in podfile)
> pod install
> rm -rf ~/.cocoapods/repos/trunk/
> pod cache clean --all
> pod install
> 
> Then it worked

**I have followed all steps but after that it gives Mudule 'firebase_core' not found. Error while building.**

**Comment by ladeng** [comment]
rm -rf ~/.cocoapods/repos/trunk/
pod install
pod update xxx
worked for me!

**Comment by ehsanbigzad** [comment]
> fixed it, here's my command list after I got that last error
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> (got another error)
> 
> pod cache clean --all
> pod install
> (got another error)
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> 
> then it worked
> 
> So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> 
> gem list --local | grep cocoapods
> sudo gem uninstall (all the items in the list)
> sudo rm -rf ~/.cocoapods
> sudo gem install cocoapods
> cd (PROJECT DIRECTORY)
> pod init
> (put cocoapod in podfile)
> pod install
> rm -rf ~/.cocoapods/repos/trunk/
> pod cache clean --all
> pod install
> 
> Then it worked

It helped my with flutter firestore package

**Comment by PolyKuzin** [comment]
> > fixed it, here's my command list after I got that last error
> > rm -rf ~/.cocoapods/repos/trunk/
> > pod install
> > (got another error)
> > pod cache clean --all
> > pod install
> > (got another error)
> > rm -rf ~/.cocoapods/repos/trunk/
> > pod install
> > then it worked
> > So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> > gem list --local | grep cocoapods
> > sudo gem uninstall (all the items in the list)
> > sudo rm -rf ~/.cocoapods
> > sudo gem install cocoapods
> > cd (PROJECT DIRECTORY)
> > pod init
> > (put cocoapod in podfile)
> > pod install
> > rm -rf ~/.cocoapods/repos/trunk/
> > pod cache clean --all
> > pod install
> > Then it worked
> 
> It helped me with flutter firestore package

YOU'VE SAVED ME A DAY OF LIFE!))))

**Comment by DevarajNiOS** [comment]
> fixed it, here's my command list after I got that last error
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> (got another error)
> 
> pod cache clean --all
> pod install
> (got another error)
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> 
> then it worked
> 
> So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> 
> gem list --local | grep cocoapods
> sudo gem uninstall (all the items in the list)
> sudo rm -rf ~/.cocoapods
> sudo gem install cocoapods
> cd (PROJECT DIRECTORY)
> pod init
> (put cocoapod in podfile)
> pod install
> rm -rf ~/.cocoapods/repos/trunk/
> pod cache clean --all
> pod install
> 
> Then it worked

For those who is encountering integration with Google "materialComponents/*" this might help you, i had issue with "pod 'MaterialComponents/TextControls+OutlinedTextFields'" and this helped.

**Comment by SunshineTraveller** [comment]
> fixed it, here's my command list after I got that last error
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> (got another error)
> 
> pod cache clean --all
> pod install
> (got another error)
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> 
> then it worked
> 
> So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> 
> gem list --local | grep cocoapods
> sudo gem uninstall (all the items in the list)
> sudo rm -rf ~/.cocoapods
> sudo gem install cocoapods
> cd (PROJECT DIRECTORY)
> pod init
> (put cocoapod in podfile)
> pod install
> rm -rf ~/.cocoapods/repos/trunk/
> pod cache clean --all
> pod install
> 
> Then it worked

God Bless You!  YOU'VE SAVED ME A DAY OF LIFE!

**Comment by JavaBlackBelt** [comment]
> fixed it, here's my command list after I got that last error
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> (got another error)
> 
> pod cache clean --all
> pod install
> (got another error)
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> 
> then it worked
> 
> So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> 
> gem list --local | grep cocoapods
> sudo gem uninstall (all the items in the list)
> sudo rm -rf ~/.cocoapods
> sudo gem install cocoapods
> cd (PROJECT DIRECTORY)
> pod init
> (put cocoapod in podfile)
> pod install
> rm -rf ~/.cocoapods/repos/trunk/
> pod cache clean --all
> pod install
> 
> Then it worked
-----
Was facing same issue for Firebase dependencies, this above solution helps me .thanks A lot
**i used 
rm -rf ~/.cocoapods/repos/trunk/
pod install**

**Comment by nivas37** [comment]
> fixed it, here's my command list after I got that last error
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> (got another error)
> 
> pod cache clean --all
> pod install
> (got another error)
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> 
> then it worked
> 
> So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> 
> gem list --local | grep cocoapods
> sudo gem uninstall (all the items in the list)
> sudo rm -rf ~/.cocoapods
> sudo gem install cocoapods
> cd (PROJECT DIRECTORY)
> pod init
> (put cocoapod in podfile)
> pod install
> rm -rf ~/.cocoapods/repos/trunk/
> pod cache clean --all
> pod install
> 
> Then it worked

After struggling for a day, your solution helped me! Thank you so so so much!

**Comment by TyagiShishira** [comment]
> fixed it, here's my command list after I got that last error
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> (got another error)
> 
> pod cache clean --all
> pod install
> (got another error)
> 
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> 
> then it worked
> 
> So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> 
> gem list --local | grep cocoapods
> sudo gem uninstall (all the items in the list)
> sudo rm -rf ~/.cocoapods
> sudo gem install cocoapods
> cd (PROJECT DIRECTORY)
> pod init
> (put cocoapod in podfile)
> pod install
> rm -rf ~/.cocoapods/repos/trunk/
> pod cache clean --all
> pod install
> 
> Then it worked

yes it worked thanks

**Comment by krAnkkit** [comment]
I was trying to add 'MaterialComponents/Ripple' and was running into similar issues. I switched to adding 'MaterialComponents' and that worked for me.
Sequence of cmds :
pod repo remove trunk
pod setup
<change 'MaterialComponents/Ripple' to 'MaterialComponents' in Podfile>
pod install

**Comment by boshang** [comment]
> fixed it, here's my command list after I got that last error
> 
> rm -rf ~/.cocoapods/repos/trunk/ pod install (got another error)
> 
> pod cache clean --all pod install (got another error)
> 
> rm -rf ~/.cocoapods/repos/trunk/ pod install
> 
> then it worked
> 
> So from my beginning problem till now, here all the commands in order that seemed to have made it work.
> 
> gem list --local | grep cocoapods sudo gem uninstall (all the items in the list) sudo rm -rf ~/.cocoapods sudo gem install cocoapods cd (PROJECT DIRECTORY) pod init (put cocoapod in podfile) pod install rm -rf ~/.cocoapods/repos/trunk/ pod cache clean --all pod install
> 
> Then it worked

not work for me , Is there any other way? Thank you very much

**Comment by ganeelz** [comment]
> rm -rf ~/.cocoapods/repos/trunk/
> pod install
> pod update xxx
> worked for me!

Thanku!! I was stuck for 2 days with PromiseKit similar error.

**Comment by SunshineTraveller** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到您的邮件...
