### ISSUE TITLE
CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_f_2_0.txt Response: Timeout was reached

### ISSUE THREAD

**Issue by wuzeqin** [CocoaPods/CocoaPods#9618]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

 Run `pod install`  ,  the below error occured to me

[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_f_2_0.txt Response: Timeout was reached

then i try add source 'https://cdn.cocoapods.org/' to my podfile then other error haapened instead 

## What did you expect to happen?

 Install all pod dependencies correctly.

## What happened instead?

Resolving dependencies of `Podfile`
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in
  repo update
  CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_f_2_0.txt Response:
  Timeout was reached, retries: 4
  CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_f_2_0.txt Response:
  Timeout was reached, retries: 3
  CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_f_2_0.txt Response:
  Timeout was reached, retries: 2
  CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_f_2_0.txt Response:
  Timeout was reached, retries: 1
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/all_pods_versions_f_2_0.txt Response: Timeout was reached

/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:401:in `block in download_and_save_with_retries_async'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:406:in `apply'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1205:in `apply'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1729:in `block (2 levels) in on_resolvable'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1582:in `evaluate_to'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1729:in `block in on_resolvable'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:353:in `run_task'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:342:in `block (3 levels) in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `loop'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:325:in `block (2 levels) in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `catch'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:324:in `block in create_worker'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1257:in `raise'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:1257:in `wait_until_resolved!'
/Library/Ruby/Gems/2.3.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/promises.rb:977:in `wait!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:333:in `download_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

### Stack

```
   CocoaPods : 1.9.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.6 (18G2022)
       Xcode :  ()
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Seems like a network issue reaching our CDN server. Please switch back to `git` based solution instead. There are other issues here on GH similar and on StackOverflow.

Closing pre-emptively.

**Comment by wuzeqin** [comment]
> Seems like a network issue reaching our CDN server. Please switch back to `git` based solution instead. There are other issues here on GH similar and on StackOverflow.
> 
> Closing pre-emptively.

i try again , it work!  i found all_pods_versions_*_*_*.txt and .etag  in trunk.  it's net work issue.

**Comment by Daricxu** [comment]
I got the same problem, can you elaborate a little bit about what you have done to solve this? like how did you '.etag in trunk' ?
thanks
