### ISSUE TITLE
[Feature Support]On-Demand Resource

### ISSUE THREAD

**Issue by JunyiXie** [CocoaPods/CocoaPods#9621]
[Feature Request] On-Demand Resource Support  https://github.com/CocoaPods/CocoaPods/issues/9606

PR:
https://github.com/CocoaPods/CocoaPods/pull/9620

depand on 
Core: https://github.com/CocoaPods/Core/pull/622
Xcodeproj: https://github.com/CocoaPods/Xcodeproj/pull/742

**Comment by dnkoutso** [comment]
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9606 No need for separate issue.
