### ISSUE TITLE
Failed to link to XCFramework

### ISSUE THREAD

**Issue by 666tos** [CocoaPods/CocoaPods#9623]
# Report

## What did you do?

I have project structure like following
Project `P` has `A` as dependency.
`A` has `B` as dependency.

`B` provides `xcframework` as `vendored_frameworks`

I have to use `Modern build system` (in order to build `Mac Catalyst` app)

## What did you expect to happen?

I expect whole project to be built correctly.

### Issue 1
`Pods-P-iOS-artifacts.sh` in my case performs something like this

> rsync --delete -av "/[DerivedData]/[Project]-[UUID]/Build/Products/[Config]-maccatalyst/B.framework" "/[DerivedData]/[Project]-[UUID]/Build/Products/[Config]-maccatalyst"

Which totally makes no sense

### Issue 2
Becase of parallel build process, `Pods-P-iOS-artifacts.sh` is executed after `A` was build, which causes `A` failing on linking, being unable to find `B`'s frameworks.

### Issue 3 
It also turns out that `FRAMEWORK_SEARCH_PATHS` are set incorrectly:
`"${PODS_ROOT}/B" "${PODS_ROOT}/B/B.xcframework/ios-arm64" "${PODS_ROOT}/B/B/ios-x86_64-maccatalyst" "${PODS_ROOT}/B/B.xcframework/ios-x86_64-simulator"` instead of simple `"${PODS_CONFIGURATION_BUILD_DIR}"`

Also OTHER_CGFLAGS:
`-iframework "${PODS_ROOT}/B" -iframework "${PODS_ROOT}/B/B.xcframework/ios-arm64" -iframework "${PODS_ROOT}/B/B.xcframework/ios-x86_64-simulator" -iframework "${PODS_ROOT}/B/B.xcframework/ios-x86_64-maccatalyst"`

## CocoaPods Environment

Cocoapods 1.9.1

**Comment by dnkoutso** [comment]
Not sure here, maybe @amorde has some knowledge

**Comment by csutanyu** [comment]
@666tos Did you solve this link issue ?

**Comment by 666tos** [comment]
@csutanyu nope, but I did following:

for project `A` i edited `xcconfig` as following:

>   s.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '"${PODS_CONFIGURATION_BUILD_DIR}"' }

And then i manually copied proper parts of `xccframework` to `PODS_CONFIGURATION_BUILD_DIR`, which is something like this 

> /<DERIVED DATA>/<PROJECT_NAME>-<UUID>/Build/Products/<CONFIG>-maccatalyst/

Unfortunately, it's only possible to do during development, but product can't be deployed to and `CI`

**Comment by amorde** [comment]
>> rsync --delete -av "/[DerivedData]/[Project]-[UUID]/Build/Products/[Config]-maccatalyst/B.framework" "/[DerivedData]/[Project]-[UUID]/Build/Products/[Config]-maccatalyst"
> 
> Which totally makes no sense

Why does it make no sense?

> It also turns out that FRAMEWORK_SEARCH_PATHS are set incorrectly

I considered using something such as `${PODS_CONFIGURATION_BUILD_DIR}` but then Xcode won't be able to find the headers at all without building. But that might be a trade off we have to make, unfortunately Xcode won't search inside an .xcframework which would be ideal.

> Also OTHER_CGFLAGS:
-iframework "${PODS_ROOT}/B" -iframework "${PODS_ROOT}/B/B.xcframework/ios-arm64" -iframework "${PODS_ROOT}/B/B.xcframework/ios-x86_64-simulator" -iframework "${PODS_ROOT}/B/B.xcframework/ios-x86_64-maccatalyst"

This looks incorrect to me, will look into this when I can

**Comment by 666tos** [comment]
> Why does it make no sense?

It makes no sense because it copies framework slice from `Build/Products/[Config]-maccatalyst/B.framework`, which was never created, because `xcframework` was vendored.

**Comment by amorde** [comment]
Circling back to this, #9720 was merged recently which reworked xcframework support including changing the way the search paths are setup. I believe this issue should be fixed with that, but can't confirm without a sample project.

@666tos can you try using the latest master branch of CocoaPods? You can use https://bundler.io/ to try specific branches of CocoaPods
