### ISSUE TITLE
Issue while trying to install Swift Lint 

### ISSUE THREAD

**Issue by swasalunke** [CocoaPods/CocoaPods#9633]
* [✔️] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`
Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.
Install pod dependencies correctly

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.
Got an error `[!] CDN: cocoapods- Relative path couldn't be downloaded: Specs/4/0/1/SwiftLint/index.txt Response: 301`

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

### Stack

```
   CocoaPods : 1.7.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G3020)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
               forcedotcom - https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git @ e93f9c95d981d3c3f71064b870ab7bdf86015603
               master - https://github.com/CocoaPods/Specs.git @ 955b84fed44e8064abef57979de8b2257b3f9b30
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CollectionView' do
  # Comment the next line if you don't want to use dynamic frameworks
  source 'https://cdn.cocoapods.org/'
  use_frameworks!
  pod 'SwiftLint'
  # Pods for CollectionView

end
```

**Comment by dnkoutso** [comment]
Please upgrade to 1.9.1 also if this is a network issue with CDN please fallback to the `git` based source.
