### ISSUE TITLE
 library not found for class Digest::MD5 -- digest/md5

### ISSUE THREAD

**Issue by wenweijia** [CocoaPods/CocoaPods#9645]
### Command

```
/Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.7.2
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.15 (19A583)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b8acadcf635bedad78ba94bcee2b30ce9d98e424
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios,  '8.0'
use_frameworks!
# pod update --verbose --no-repo-update
target 'YunShiSwift' do
    
    pod 'SnapKit'
    pod 'Moya'
    pod 'SwiftyJSON'
    pod 'MJRefresh'
    pod 'LTScrollView'
    pod 'ESTabBarController-swift'
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'DNSPageView'
    pod 'IQKeyboardManagerSwift'
    pod 'Kingfisher'
    pod 'EmptyDataSet-Swift', '~> 4.2.0'
    pod 'HandyJSON', '~> 5.0.0'
    pod 'SwifterSwift'
    pod 'CryptoSwift'
    pod 'SVProgressHUD'
#    pod 'NVActivityIndicatorView'
#    pod 'SwiftDate', '~> 5.0'
    pod 'SwiftyAttributes'
    pod 'SCLAlertView'
#    pod 'JXPhotoBrowser', '~> 3.0'
end
```

### Error

```
LoadError - library not found for class Digest::MD5 -- digest/md5
/Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/digest.rb:15:in `const_missing'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source/metadata.rb:45:in `path_fragment'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source.rb:111:in `pod_path'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source.rb:267:in `search'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.7.2/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:389:in `create_set_from_sources'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:358:in `find_cached_set'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:332:in `specifications_for_dependency'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:139:in `search_for'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:248:in `block in sort_dependencies'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:241:in `each'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:241:in `sort_by'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:241:in `sort_dependencies'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/resolver.rb:88:in `resolve'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:398:in `analyze'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/installer.rb:156:in `install!'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/command/install.rb:51:in `run'
/Users/wenweijia/.rvm/gems/ruby-2.2.4/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
/Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
/Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/pod:23:in `load'
/Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/pod:23:in `<main>'
/Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:24:in `eval'
/Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=library+not+found+for+class+Digest%3A%3AMD5+--+digest%2Fmd5&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
/Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:120:in `require': dlopen(/Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin17/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (LoadError)
  Referenced from: /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin17/openssl.bundle
  Reason: image not found - /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/x86_64-darwin17/openssl.bundle
	from /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/openssl.rb:17:in `<top (required)>'
	from /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:892:in `connect'
	from /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/wenweijia/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:84:in `get_api_results'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/gems/gh_inspector-1.1.3/lib/gh_inspector/sidekick.rb:28:in `search'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:68:in `search_query'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/gems/gh_inspector-1.1.3/lib/gh_inspector/inspector.rb:62:in `search_exception'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:67:in `report_error'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/gems/claide-1.0.2/lib/claide/command.rb:325:in `run'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/lib/cocoapods/command.rb:52:in `run'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.7.2/bin/pod:55:in `<top (required)>'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/pod:23:in `load'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/pod:23:in `<main>'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:24:in `eval'
	from /Users/wenweijia/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:24:in `<main>'

**Comment by dnkoutso** [comment]
Please upgrade to latest CocoaPods 1.9.1 as I believe this is fixed already.
