### ISSUE TITLE
Compilation error "... is not available when building for iOS Simulator"

### ISSUE THREAD

**Issue by nonameplum** [CocoaPods/CocoaPods#9650]
# Report

## What did you do?

I made a framework that has a dependency to Carbon framework https://github.com/ra1028/Carbon

## What did you expect to happen?

Application compiles without the error message

## What happened instead?

Project with Application that uses my framework that depends on Carbon cannot be compiled because of the compilation error message:
`~/Test/MyLibraryTestApp/Pods/Pods.xcodeproj Carbon is not available when building for iOS Simulator.`

The same thing happens when I switch compilation from the simulator to device only the error message is slightly different:
`~/Test/MyLibraryTestApp/Pods/Pods.xcodeproj Carbon is not available when building for iOS.`

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MyLibraryTestApp' do
  use_frameworks!

  pod 'MyLibrary', :path => '../MyLibrary'

end
```

## Project that demonstrates the issue

Minium example that reproduces the issue:
[Test.zip](https://github.com/CocoaPods/CocoaPods/files/4389642/Test.zip)

**Comment by nonameplum** [comment]
It seems like this is Xcode 11.4 related.

**Comment by dnkoutso** [comment]
Thanks! Havent installed it yet to know...would appreciate any follow ups here for others. Might or might not be a CocoaPods issue but for now I will leave it open.

**Comment by nonameplum** [comment]
The same issue (https://github.com/ra1028/Carbon/issues/73) was on the example app of the Carbon framework that doesn't use cocoapods to resolve dependencies and it was fixed by this changes: https://github.com/ra1028/Carbon/pull/74/files

**Comment by nonameplum** [comment]
The problem is the framework name. Since Xcode 11.4 the are more restrictive rules agains linking as far as I can tell and `Carbon` collides with Apple’s framework.

**Comment by paulb777** [comment]
Closing since this seems to be an Xcode 11.4 and framework name issue - unrelated to CocoaPods.
