### ISSUE TITLE
[!] The Podfile does not contain any dependencies.

### ISSUE THREAD

**Issue by jjung98** [CocoaPods/CocoaPods#9651]
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+space+left+on+device+%40+fptr_finalize_flush+-+%2FUsers%2Fzzang%2Fjoin-tech-app%2Fplatforms%2Fios%2FPods%2FTarget+Support+Files%2FPods-dmdxpzm%2FPods-dmdxpzm.debug.xcconfig&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

[!] The Podfile does not contain any dependencies.

**Comment by dnkoutso** [comment]
This is not a valid issue template. Please fill it in properly.
