### ISSUE TITLE
PODSpec is not valid sucessfully, erorr while push - ios swift 5

### ISSUE THREAD

**Issue by pradipwalghude** [CocoaPods/CocoaPods#9655]
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - ERROR | [iOS] xcodebuild:  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/lib/swift/XCTest.swiftmodule/x86_64.swiftinterface:6:19: error: no such module 'XCTest'
    - ERROR | [iOS] xcodebuild:  fieldinsight/verso-fi-pod/verso-fi-podTests/verso_fi_podTests.swift:9:8: error: failed to load module 'XCTest'
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

[!] The `fieldinsight.podspec` specification does not validate.

 Please help me asap.

**Comment by dnkoutso** [comment]
Hey there, thanks for the issue. There isn't sufficient information for us here to diagnose plus this issue looks like a podspec configuration issue. Please ask in StackOverflow under `cocoapods` tag instead.

This is mostly reserved for actual bugs in the CocoaPods library. If you believe this is one then please upload a sample app and podspec that clearly demonstrates the issue and I will re-open this.

**Comment by pradipwalghude** [comment]
If you don't no the solution then why you close this issue

**Comment by dnkoutso** [comment]
Because we have an issue template to file and the issue you filed gives little to no information. We get a lot of issues here that maintaining them open can be very difficult.
