### ISSUE TITLE
Firebase SetUp Issue: 'FirebaseCoreDiagnosticsInterop/FIRCoreDiagnosticsData.h' file not found

### ISSUE THREAD

**Issue by tiaralogan** [CocoaPods/CocoaPods#9659]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod init

## What did you expect to happen?
To add pod 'Firebase/Database' and pod 'Firebase/Storage' and not get an error

## What happened instead?

I got an error and in my code I got this error also: 'FirebaseCoreDiagnosticsInterop/FIRCoreDiagnosticsData.h' file not found

## CocoaPods Environment

error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool. 

[Pods.xcodeproj.zip](https://github.com/CocoaPods/CocoaPods/files/4398009/Pods.xcodeproj.zip)

**Comment by dnkoutso** [comment]
Please file an issue with Firebase github. The attached project is insufficient for us to diagnose. We are getting many issues and cannot keep them all open.

The report here is incomplete.

**Comment by dnkoutso** [comment]
Also debug:

> error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
