### ISSUE TITLE
How to Remove Absolute Paths to Publisher's Machine

### ISSUE THREAD

**Issue by joesus** [CocoaPods/CocoaPods#9665]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

When the CocoaPod is published via Travis CI there are no references to the publishing developer's machine but there are when using the local machine to push to trunk. 
The actual command I'm using is the same for each component of Facebook's iOS SDK. Example for `FBSDKCoreKit.podspec` I run:

`pod trunk push FBSDKCoreKit.podspec --allow-warnings`

More details on the undesired side effect of pushing locally here:
https://github.com/facebook/facebook-ios-sdk/issues/1203

## What did you do?

`pod trunk push FBSDKCoreKit.podspec --allow-warnings`

## What did you expect to happen?

Expected to push `FBSDKCoreKit` pod without including paths to the device I pushed from.

## What happened instead?

https://github.com/facebook/facebook-ios-sdk/issues/1203

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C505)
         Git : git version 2.13.5
Ruby lib dir : /Users/joesusnick/.rbenv/versions/2.5.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 4b58d70d6c0a9c5b8f09453e06d5525eba7c8500
               privatePodSpecs - git - https://github.com/joesus/privatePodSpecs.git @ c1d8f8604e7f72556eb5b6d73c26dbf1fb3a2209
               privatepodspecs-1 - git - /Users/joesusnick/.cocoapods/repos/privatePodSpecs @ c1d8f8604e7f72556eb5b6d73c26dbf1fb3a2209
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/joesusnick/.rbenv/versions/2.5.3/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

N/A Included link to Github issue.

**Comment by dnkoutso** [comment]
Hmmm I am not quite sure how those are generated and why the absolute path is used there.

Is your pod shipping pre-compiled libs? From the issue report it seems those are generated by Xcode derived data in the `.pcm` so I am not sure where it picks up that path.

**Comment by dnkoutso** [comment]
Nothing in your podspec looks out of the ordinary here. I am quite unsure where those paths are maintained.

**Comment by orta** [comment]
Looking in the FBSDK repo, there's only really one reference to the path too, it comes inside an xcodeproj which shouldn't affect this (I think): https://github.com/facebook/facebook-ios-sdk/search?q=joesusnick&unscoped_q=joesusnick
