### ISSUE TITLE
xargs: insufficient space for argument while run custom shell script '[CP] Copy Pods Resources'

### ISSUE THREAD

**Issue by magic3584** [CocoaPods/CocoaPods#9669]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Product -> Archive

## What did you expect to happen?

Archive successfully
## What happened instead?

It shows error: `xargs: insufficient space for argument` while run custom shell script '[CP] Copy Pods Resources'
### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f8532e243c06ad8011dd4348cd7a520191033bc0
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
How big is your project? Do you have a sample app that reproduces and shows the issue?

**Comment by magic3584** [comment]
@dnkoutso 
Sorry I don't have a sample app. 
I cut some images in pods to the main project, it worked.
The project folder is less than 2 GB and the cut images is just 600KB.

**Comment by dnkoutso** [comment]
What does "I cut some images" mean?

**Comment by magic3584** [comment]
@dnkoutso I copy images to main project, and then delete the images in pod.

**Comment by magic3584** [comment]
Please see the pic:
The **images folder** was in **place 1** where the error showed, but after I moved them to **place 2**, product can archived successfully. 
There are 146 pngs in **images folder** and the folder size is 600KB

![WX20200402-212108@2x.png](https://i.loli.net/2020/04/02/r7J4ABidQ1hqSK9.png)

**Comment by dnkoutso** [comment]
Should this issue be closed?

**Comment by magic3584** [comment]
@dnkoutso Is this a bug? Could it be solved?

**Comment by dnkoutso** [comment]
We need a sample app here to be able to assess if its a bug or not.

Large projects can hit ARG_MAX limit that could cause this to happen.

**Comment by magic3584** [comment]
The **images** contains hundreds of pics. The error happens when they are imported directly in CocoaPods just at the place **1** on top screenshot. 
But after I put them in an images.assets and then imported again, the error disappears .
Is this the reason you said `Large projects can hit ARG_MAX limit` ?

**Comment by songqingcool** [comment]
you can try change【Pods-resources.sh】script file like this ：【 | xargs -0 xcrun actool --output-format human-readable-text --notices --warnings --platform "${PLATFORM_NAME}" --minimum-deployment-target "${!DEPLOYMENT_TARGET_SETTING_NAME} 】change to 【 | xargs -0 -n 20480 -s 4096 xcrun actool --output-format human-readable-text --notices --warnings --platform "${PLATFORM_NAME}" --minimum-deployment-target "${!DEPLOYMENT_TARGET_SETTING_NAME} 】。 it works to me

**Comment by magic3584** [comment]
@songqingcool Why ` | xargs -0 -n 20480 -s 4096 `? What it exactly do?
