### ISSUE TITLE
Unsupported download strategy `{:local=>"MyLocalPodCode"}

### ISSUE THREAD

**Issue by azeitler** [CocoaPods/CocoaPods#967]
Pod::Downloader::DownloaderError - Unsupported download strategy `{:local=>"MyLocalPodCode"}

Seems the ":local" key was removed from cocoapods-downloader?
Any way to get back support for local pods in 0.18.x?

**Comment by jagdish24** [comment]
@colasbd Is this  "s.source  = { :path =>" worked for you ?

**Comment by jbarros35** [comment]
No, its not working anymore.
