### ISSUE TITLE
Can't import C++ Pod dependency header in development Pod

### ISSUE THREAD

**Issue by mjjimenez** [CocoaPods/CocoaPods#9678]
🌈

* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I'm developing a Cocoapod library with a C++ dependency (`libtorch`) that is also distributed using Cocoapods. When I import `libtorch`'s header in an Objective-C or Objective-C++ file, the project fails to build due to not being able to find one of `libtorch`'s header files.
Specific Steps:
1. `pod lib create <pod>`
2.  Add the C++ library as a dependency `s.dependency 'LibTorch', '~> 1.3.0'`
3.  Add Objective-C files `TestClass.h` and `TestClass.m`
4. `pod install`
5. Build the project, then it fails to build.
 

## What did you expect to happen?

The project builds successfully.

## What happened instead?

Error when buidling: `'torch/script.h' not found`
In `Pods/LibTorch/Core/Libtorch.h`
```
#ifndef LibTorch_h
#define LibTorch_h

#include <torch/script.h>

#endif
```
I've already checked and script.h already exists after I did `pod install` at  `SamplePod-Swift/Example/Pods/LibTorch/install/include/torch/script.h`

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 11.3 (11C29)
         Git : git version 2.8.1
Ruby lib dir : /Users/mjjim2003/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ f3f9d841c25a98394169080fddbe337daa2f365c
               personal - git - https://github.com/mjjimenez/SamplePodspecRepo @ 4ccb780ab8d7ba61663ad7755c44266108787547
               rnapier - git - https://github.com/rnapier/RNCryptor.git @ 5e3bbf44f08bf90049537cb8902d8f4fa911a79a
               trunk - CDN - https://cdn.cocoapods.org/
               twilio - git - https://github.com/twilio/cocoapod-specs @ 9bf659ed7246ba34625b81754031fbd5ac20fe68
```

### Installation Source

```
Executable Path: /Users/mjjim2003/.rvm/gems/ruby-2.2.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/mjjimenez/SamplePod

**Comment by mjjimenez** [comment]
Sorry, the sample project was actually missing some files to reproduce the issue. It should be OK now and the error should occur.

**Comment by paulb777** [comment]
Might be related to #5152

**Comment by mjjimenez** [comment]
The developer replied here: https://discuss.pytorch.org/t/cant-use-ios-libtorch-as-a-dependency-for-a-library-using-cocoapods/75544/3 

To summarize for anyone else browsing this issue, I had to add the header search paths on my own library's podspec again.

```
    s.pod_target_xcconfig = { 
      'HEADER_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}/LibTorch/install/include"',
    }
```

I'm not sure why though, since it's already defined in the other library's podspec (Libtorch). But this solved the problem.
