### ISSUE TITLE
Building project with RestKit 0.10.3 fails with "'RKConfigurationDelegate.h' file not found" after upgrading to 0.17+

### ISSUE THREAD

**Issue by sharplet** [CocoaPods/CocoaPods#968]
To reproduce:
1. Create a new iOS project
2. Add the Podfile
   
   ```
   platform :ios
   pod 'RestKit', '0.10.3'
   ```
3. `pod install`
4. Open the workspace and try build the project

While building, I get an error in RKClient.h, "'RKConfigurationDelegate.h' file not found".

I'm not expert in CocoaPods, but I did notice this diff in Podfile.lock for an established project that updated to 0.18:

``` diff
   RestKit: 1fb57eb941d7d2587648491507a0bcaeb70b67f2
-  RestKit/JSON: 1fb57eb941d7d2587648491507a0bcaeb70b67f2
-  RestKit/Network: 1fb57eb941d7d2587648491507a0bcaeb70b67f2
-  RestKit/ObjectMapping/CoreData: 1fb57eb941d7d2587648491507a0bcaeb70b67f2
-  RestKit/ObjectMapping/JSON: 1fb57eb941d7d2587648491507a0bcaeb70b67f2
-  RestKit/UI: 1fb57eb941d7d2587648491507a0bcaeb70b67f2
```

which made me wonder if perhaps the subspecs are no longer being installed for some reason.

**Comment by balram1990** [comment]
Hi fabiopelosin,

I got an old project to work on and I am facing same problem as mentioned above. The link you have mentioned does't work so I can please let me know the steps to solve the problem, it would be great. Consider me as a newbie in cocoa pods.

Thanks-
Balram
