### ISSUE TITLE
ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES Swift 5 runtime

### ISSUE THREAD

**Issue by Ryuuke** [CocoaPods/CocoaPods#9680]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Updated project to support iOS 12.2 and above
Updated all pods and project to use Swift 5
Run `pod install`

## What did you expect to happen?
I excpected to have the option `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` set to `false` for my project, it is the case for every pod's xcconfig

## What happened instead?
`ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is set to `true` when I import a swift pod. I believe there is a condition that sets this value to true for projects that have swift version >= 2.4 but doesn't take into consideration the fact that it is no more necessary to set this value to true in this particular case since the libraries are already embedded into iOS

## CocoaPods Environment
```
source 'https://github.com/CocoaPods/Specs.git'

target 'Test_project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '12.3'
  pod 'Alamofire', '~> 5.0', :inhibit_warnings => true
  # Pods for Test_runtime
end
```

[Sample project](https://github.com/CocoaPods/CocoaPods/files/4423000/Test_runtime.zip)

**Comment by dnkoutso** [comment]
Seems like an improvement we can make yes. Is it always guaranteed that if Swift 5.0 is used then the Swift binaries are embedded?

What does `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` being true have an effect on when using Swift 5.0 which is provided by the system? Does Xcode still copy the Swift standard libs and bloats the binary?

**Comment by Ryuuke** [comment]
After further testing, I noticed that the library is not included in the app's binary even when ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES is set to YES when iOS 12.2+ & Swift 5+
My problem came from elsewhere, this can be closed. Thanks for the fast reply :)

**Comment by cornZhou** [comment]
I'm doing app slimming recently. I set support system 12.2+, then the ipa not include SwiftSupport, ipa packets are getting smaller. but when I send the ipa to iTunes connect，notice “Invalid Swift Support - The SwiftSupport
 folder is empty. Rebuild your app using the current public (GM) version of Xcode and resubmit it.Best regards”. 
then I set ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES NO,  package and upload to iTunes connect, notice "Binary file failure". Do you know how to fix the question?
