### ISSUE TITLE
Feature request: add an option to "pod lib lint" so that it compiles in Debug mode

### ISSUE THREAD

**Issue by gereons** [CocoaPods/CocoaPods#9686]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).  🌈

I would like to propose that `pod lib lint` gets an option to specify which configuration to build. Right now, building `Release` is hardcoded in [validator.rb](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/validator.rb#L717), and that should remain the default. Allowing for a command line option like `pod lib lint --configuration=Debug` or maybe simply `pod lib lint --debug` would allow users to specify compiling in Debug mode.

The reason for this request is that I'm running my CI builds on a system that is metered by CPU minutes, and where Mac CPU minutes are worth 10 times as much as a "regular" minute. Thus, optionally speeding up linting not only provides for faster feedback, it is also significantly cheaper.

Initial tests show that linting times would improve significantly: one of the pods I'm maintaining takes ~5 minutes to lint using Release, and only ~1min 20s using Debug.

If this proposal is accepted, I can provide a PR on short notice.

**Comment by dnkoutso** [comment]
It may have been discussed in the past..I think the reason for that is that pods are meant to be published and ensure that they can be released for Release configuration.

Why not use other means to test that like https://github.com/square/cocoapods-generate to produce a workspace and invoke `xcodebuild` on it?

**Comment by paulb777** [comment]
I could support such a feature.

While the Release config is important for the final app, the developer clients of source pods typically use them in both Debug and Release configurations.

While `pod generate` is great for pod development, a one line `pod lib lint` invocation is nicer for CI use cases.

**Comment by gereons** [comment]
Admittedly, I did not know about `pod gen`. I tried it, but unfortunately it does not work with my pod because it somehow insists on building for Catalyst instead of iOS - I'll investigate further and will probably file an issue in its repo.

Anyway, the point of my suggestion was to have a way to get all the validations that `pod lib lint`does, just faster and without installing extra modules. My plan would be to run the fast/debug version for branch commits, and use the release/expensive checks for when a pod's release is published.

**Comment by gereons** [comment]
Can I ask for some guidance on how to continue? With what looks to me like a "dunno" and a +1, should I provide the PR? If so, what should the option be called?

**Comment by paulb777** [comment]
For the option name, how about the specific `--configuration-debug` or the more flexible `--configuration={config}`?

@dnkoutso Would such a PR get merged?

**Comment by amorde** [comment]
Closing as #9760 was merged - this will be released in 1.10 👍
