### ISSUE TITLE
Feature request - Support for CocoaPods registries

### ISSUE THREAD

**Issue by eyalbe4** [CocoaPods/CocoaPods#9690]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).🌈 

JFrog Artifactory supports managing CocoaPods packages, through its [CocoaPods Repositories](https://www.jfrog.com/confluence/display/JFROG/CocoaPods+Repositories). Since CocoaPods does not support Artifactory natively, the [cocoapods-art](https://github.com/jfrog/cocoapods-art) gem is currently used for this integration. Since this is an external plugin, it can break, following changes implemented in Cocoapods.

We suggest adding native Artifactory support to CocoaPods, so that it can seamlessly work with Artifactory [CocoaPods Repositories](https://www.jfrog.com/confluence/display/JFROG/CocoaPods+Repositories), like any other repository. 

We are willing to contribute this functionality through a pull request.

**Comment by dnkoutso** [comment]
what is an example of "breakage" we tend to ensure we follow semver guidelines and not ship breaking changes.

**Comment by eyalbe4** [comment]
@dnkoutso,
The plugin does not use CocoaPods public APIs, but instead overrides some of the code, so that the authenticated REST APIs of Artifactory are invoked by CocoaPods. This is why this solution is occasionally breaking. 
We would like to try creating a simple and easy to maintain solution.

**Comment by eyalbe4** [comment]
@dnkoutso,
Actually, the functionality we are proposing should allow CocoaPods to work with any CocoaPods registry, not just Artifactory, for the benefit of the CocoaPods community.
Once we have a working solution, we would like to share it with you and get your feedback for it.

**Comment by eyalbe4** [comment]
@dnkoutso,

The current title of this issue is a bit misleading, because we're actually not proposing to support Artifactory specifically. We think it makes more sense for CocoaPods to support any CocoaPods registry vendor. This would allow others to build their own CocoaPods proxies, and would greatly benefit the CocoaPods community. I'm therefore changing the title of this issue to "Feature request - Support for CocoaPods registries".

We've started looking into implementing this and hope we can get your feedback for a pull request we'll submit. We'd really appreciate any feedback, questions or requests you may already have for this initiative,  
Please let us know what you think.

**Comment by pschneider** [comment]
While in general this is definitely a good Idea to better support tools like Artifactory for proxying available libraries and making local builds faster and also reliable (in case of unavailable master repo, unpublished libraries) I think it doesn't really make sense to do that for the old style repository anymore. This is slow, takes a lot of space locally and in the end the CDN is/will be the preferred way (as far as I understood).

Therefor it should rather be possible to enable this for CocoaPods CDN which is as well not supported by Artifactory as of now: https://www.jfrog.com/jira/browse/RTFACT-20455

**Comment by eyalbe4** [comment]
Thanks for you comment and suggestion @pschneider!
We're currently looking into this option.

**Comment by dnkoutso** [comment]
hey @eyalbe4 and others! Apologies for the long delay here. Past month I wasnt able to spend time on CocoaPods...

I think a proposal would make sense here in either direction and I would be glad to review PRs and the proposal itself to support it first-class within CocoaPods.

**Comment by eyalbe4** [comment]
Hi @dnkoutso - thanks for your feedback!
I suggest we start with the old style solution, and put in a place a good working solution. Once done, we can look into the CDN option. Let us reallocate some time for this and start working on a PR.

**Comment by dnkoutso** [comment]
sounds good!

**Comment by eyalbe4** [comment]
@dnkoutso,
@yahavi created the above two PRs, which add support for CocoaPods registries.
Thanks!

**Comment by endocrimes** [comment]
@eyalbe4 Is there a specification of the expected behavior for these registries? - I'd be a bit worried about merging in support for this without the expectations being documented

**Comment by eyalbe4** [comment]
@endocrimes,

Sure, I completely agree.

@yahavi added the usage details for the new functionality in the description of https://github.com/CocoaPods/CocoaPods/pull/9959 but please let us know where you would like us to document the specification. Also, if there's a preferred format or convention for the documenting the specification, please let us know and we'll make sure to follow it.

Thanks

**Comment by dnkoutso** [comment]
@eyalbe4 an RFC write up can be very helpful. Some examples:

https://github.com/CocoaPods/CocoaPods/issues/8191
https://github.com/CocoaPods/CocoaPods/issues/8253 and
https://github.com/CocoaPods/CocoaPods/issues/8753

**Comment by dnkoutso** [comment]
Any updates here? Would love this for 1.11.0 release.

**Comment by eyalbe4** [comment]
@dnkoutso,
Thanks for following up on this! We're also looking forward to making this happen. 
Give us just a few more days to create the RFC.

**Comment by yahavi** [comment]
@endocrimes @dnkoutso 
We created a RFC for this feature: https://github.com/CocoaPods/CocoaPods/issues/9994
Thanks.

**Comment by dnkoutso** [comment]
Going to close this in favor of https://github.com/CocoaPods/CocoaPods/issues/9994! I do not think a separate issue adds anything more than the RFC.
