### ISSUE TITLE
Issue when pod validate 

### ISSUE THREAD

**Issue by NishantTiwarins** [CocoaPods/CocoaPods#9701]
Hi

I am using latest version of cocoapods i.e 1.9.1

I am having an issue when I am validating my podspec file. My podspec file contains xcframework and framework. All my xcframework are the dependencies framework. below is how my Podspec file looks like.

Pod::Spec.new do |spec|
  spec.name             = 'XXXXX'
  spec.version          = '0.0.4.beta'
  spec.license          =  {:type => 'MIT', :file => 'License.md'}
  spec.homepage         = 'https://www.wwwww.com/wee'
User' => 'useremail'}
  spec.summary          = 'XXXXX used for customised calling screen'
  spec.source          = { :http => 'source path url'}
  spec.source_files     = 'XXXXX.framework/Headers/*.{h,m,swift}'
  spec.vendored_frameworks =  "XXXXX.framework","Vendor/XXXXX1.xcframework","Vendor/XXXXX2.xcframework","Vendor/XXXXX3.xcframework","Vendor/XXXXX4.xcframework","Vendor/XXXXX5.xcframework","Vendor/XXXXX6.xcframework","Vendor/XXXXX7.xcframework","Vendor/XXXXX8.xcframework","Vendor/XXXXX9.xcframework","Vendor/XXXXX10.xcframework","Vendor/XXXXX11.xcframework","Vendor/XXXXX12.xcframework","Vendor/XXXXX13.xcframework","Vendor/XXXXX14.xcframework","Vendor/XXXXX15.xcframework","Vendor/XXXXX16.xcframework","Vendor/XXXXX17.xcframework","Vendor/XXXXX18.xcframework","Vendor/XXXXX19.xcframework","Vendor/XXXXX20.xcframework","Vendor/XXXXX21.xcframework","Vendor/XXXXX22.xcframework","Vendor/XXXXX23.xcframework","Vendor/XXXXX24.xcframework","Vendor/XXXXX25.xcframework","Vendor/XXXXX26.xcframework","Vendor/XXXXX27.xcframework","Vendor/XXXXX28.xcframework","Vendor/XXXXX29.xcframework","Vendor/XXXXX30.xcframework","Vendor/XXXXX31.xcframework","Vendor/XXXXX32.xcframework","Vendor/XXXXX33.xcframework","Vendor/XXXXX34.xcframework","Vendor/XXXXX35.xcframework","Vendor/XXXXX36.xcframework","Vendor/XXXXX37.xcframework"
  spec.documentation_url = 'doc url'
  spec.framework        = 'XXXXX'
  spec.exclude_files    = "Classes/Exclude"
  spec.platform         = :ios, "11.0"
  
  
end

Can you please help me out as I am running out of deadlines. Any assistance or help will be really appreciated. Thanks in advance

**Comment by dnkoutso** [comment]
It is impossible for us to assist you with the given bug report as it is unsufficient. Please ask into StackOverflow under `cocoapods` tag. We reserve this space for actual cocoapods library issues.
