### ISSUE TITLE
CompileSwift normal x86_64     	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler     (2 failures)

### ISSUE THREAD

**Issue by memoriesus** [CocoaPods/CocoaPods#9703]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod spec lint example.podspec (Xcode builds successfully )

## What did you expect to happen?
should be successful
## What happened instead?
Failed -CompileSwift normal x86_64
    	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    (2 failures)
## CocoaPods Environment

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
    RubyGems : 3.1.2
        Host : Mac OS X 10.15.4 (19E266)
       Xcode : 11.4 (11E146)
         Git : git version 2.6.4
Ruby lib dir : /Users/MarcZhao/.rvm/rubies/ruby-2.7.0/lib
Repositories : artsy - git - https://github.com/Artsy/Specs.git @ d70f6d5de16e32f4d001a6b9753ba65d250aa866

               master - git - https://github.com/CocoaPods/Specs.git @ 340490d8289d7d51192c73d7d9885afffe85ddad

               trunk - CDN - https://cdn.cocoapods.org/
```

**Comment by dnkoutso** [comment]
This isn't a sufficient issue report. Need a sample app and clear steps to reproduce.

Please upload a sample app and I can re-open if we confirm a bug in CocoaPods.

**Comment by memoriesus** [comment]
Because it's my static libraries

**Comment by francodoshii** [comment]
> Because it's my static libraries

@memoriesus may i know how did you solved this?

**Comment by benleah** [comment]
I get this with a clean react native install. 
`npx react-native init MyApp`
`cd MyApp`
`npx react-native run-ios`

**Comment by benleah** [comment]
I encountered the same error. To solve I updated cocoapods (to version 1.9.3) `sudo gem install cocoapods` and re-ran `pod install` ... after that the build succeed

**Comment by amerllica** [comment]
@benleah, I'm using the version 1.9.3 but still have this error.
