### ISSUE TITLE
Problem in releasing and trunk pushing  cocoapods

### ISSUE THREAD

**Issue by eevaah** [CocoaPods/CocoaPods#9704]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ tried running pod trunk push FantasticView27.podspec  

## What did you expect to happen?

ℹ pushing of the pods to GitHub

## What happened instead?

ℹgave the error :-
### Error

```
Netrc::Error - Permission bits for '/Users/sidaksinghaulakh/.netrc' should be 0600, but are 644
/Library/Ruby/Gems/2.6.0/gems/netrc-0.11.0/lib/netrc.rb:45:in `check_permissions'
/Library/Ruby/Gems/2.6.0/gems/netrc-0.11.0/lib/netrc.rb:52:in `read'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:106:in `netrc'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk.rb:111:in `token'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:56:in `validate!'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

## CocoaPods Environment

ℹ ### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.22.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : FantasticView27PodSpecs - git - https://github.com/eevaah/FantasticView.git @ fb168913fe2c3a9d61f3722250bde529df38eb4f

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
`Netrc::Error - Permission bits for '/Users/sidaksinghaulakh/.netrc' should be 0600, but are 644`

Use `chmod` on that file. The error message describes the issue.

Going to close as I do not see a change for CocoaPods here.
