### ISSUE TITLE
Problem with pod install

### ISSUE THREAD

**Issue by rafsouzap** [CocoaPods/CocoaPods#9705]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install` via fastlane

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Returns the error message: `no such module 'KeychainAccess'`

I identified that previously the build log looked like this:
`=== BUILD TARGET KeychainAccess OF PROJECT Pods WITH CONFIGURATION Debug ===`

And since it started to give an error, the build log started to look like this:
`=== BUILD AGGREGATE TARGET KeychainAccess OF PROJECT Pods WITH CONFIGURATION Debug ===`

This error happened without any change in the project.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /Users/vendasci/.rvm/rubies/ruby-2.5.0/lib
Repositories : globoi - git - git@github.com:globoi/pods-repository.git @ 9a0951e0fb83e8b8348dda96cd0d85a7374362ca
               globoi-1 - git - https://github.com/globoi/pods-repository.git @ b412160c47eff7452577650d340eb6ac8e8f9f5e
               master - git - https://github.com/CocoaPods/Specs.git @ 9d00d30bed63bcd6d35f897f05da0154f4f94dd4
```

### Installation Source

```
Executable Path: /Users/vendasci/.rvm/rubies/ruby-2.5.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
slather               : 2.4.7
```

### Podfile

```ruby
source 'https://github.com/cocoapods/specs.git'

inhibit_all_warnings!

def test_pods
  pod 'Quick', '~> 2.1.0'
  pod 'Nimble', '~> 8.0.1'
end

target 'iOS' do
  platform :ios, '10.0'
  use_frameworks!
  pod 'AppAuth'
  pod 'KeychainAccess', '~> 3.2'
end

target 'UnitTests-iOS' do
  platform :ios, '10.0'
  use_frameworks!
  test_pods
  pod 'OHHTTPStubs/Swift', '~> 8.0.0'
end

target 'UnitTests-tvOS' do
  platform :tvos, '11.0'
  use_frameworks!
  test_pods
end

target 'IntegrationTests-iOS' do
  platform :ios, '10.0'
  use_frameworks!
  test_pods
end
```

**Comment by dnkoutso** [comment]
Please upload a sample app for this. This isn't sufficient information to diagnose/debug from the issue.

**Comment by rafsouzap** [comment]
I could even share an example project, but what catches my attention is that the project works normally on my local machine, but when this same project is submitted to the CI it does not compile the pod, and days ago it did not have this problem , started without any interaction from anyone on the project.
