### ISSUE TITLE
linting fails because of build error even though project builds successfully ('string' file not found)

### ISSUE THREAD

**Issue by arielelkin** [CocoaPods/CocoaPods#9715]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
pod spec lint
```
## What did you expect to happen?

Linting to succeed, given that the pod builds successfully when integrated as a development pod. 
 
## What happened instead?

Linting failed as the the module could not be built.

```
/Build/Products/Release-iphonesimulator/STK/STK.framework/Headers/Stk.h:4:10: fatal error: 'string' file not found
    #include <string>
             ^~~~~~~~
```

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : iris-specs - git - git@github.com:shapedbyiris/Specs.git @ cc6a6173044744aef168c420b8571cc7a8c10b95

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/thestk/stk/tree/cocoapods-update

If you create a blank host iOS project and integrate the pod locally (i.e. via `  pod 'STK', :path => '~/path/to/STK'`), you will see that the Pod builds successfully. To my knowledge, this pod cannot imported into Swift, so you must import its .h files only in an Objective-C++ file (i.e. an ObjC file with its extension renamed from `.m` to `.mm`)

But `pod spec lint` fails because of a build error.

**Comment by paulb777** [comment]
This looks like a duplicate of #5152. CocoaPods 1.x linting does not support libraries with C++ headers.  The workaround is to use the option `--skip-import-validation`.

**Comment by arielelkin** [comment]
Thanks @paulb777 , that fixed it!
