### ISSUE TITLE
Cannot install CocoaPods

### ISSUE THREAD

**Issue by RoadToDream** [CocoaPods/CocoaPods#9724]
* [☑️] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Try to install cocoapods
sudo gem install cocoapods

## What did you expect to happen?
cocoapods successfully installed

## What happened instead?
execution terminated with errors. Errors shows that make failed, because " /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/.libs/libffi_convenience.a(/) is not an object file "
> 
> Building native extensions. This could take a while...
> ERROR:  Error installing cocoapods:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /Library/Ruby/Site/2.6.0 -r ./siteconf20200417-32017-1200vne.rb extconf.rb
> checking for ffi.h... no
> checking for ffi.h in /usr/local/include,/usr/include/ffi... no
> checking for shlwapi.h... no
> checking for rb_thread_call_without_gvl()... yes
> checking for ruby_native_thread_p()... yes
> checking for ruby_thread_has_gvl_p()... yes
> creating extconf.h
> creating Makefile
> 
> current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c
> make "DESTDIR=" clean
> 
> current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c
> make "DESTDIR="
> mkdir -p "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c"/libffi-x86_64; (if [ ! -f "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi"/configure ]; then echo "Running autoreconf for libffi"; cd "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi" && /bin/sh /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/autogen.sh > /dev/null; fi); (if [ ! -f "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c"/libffi-x86_64/Makefile ]; then echo "Configuring libffi for x86_64"; cd "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c"/libffi-x86_64 && env CC=" xcrun clang" CFLAGS="-arch x86_64 " LDFLAGS="-arch x86_64" "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi"/configure --disable-static --with-pic=yes --disable-dependency-tracking --disable-docs --host=x86_64-apple-darwin > /dev/null; fi); /Applications/Xcode.app/Contents/Developer/usr/bin/make -C "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c"/libffi-x86_64
> Configuring libffi for x86_64
> clang: error: unsupported option '-print-multi-os-directory'
> clang: error: no input files
> /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
> Making all in include
> make[3]: Nothing to be done for `all'.
> Making all in testsuite
> make[3]: Nothing to be done for `all'.
> Making all in man
> make[3]: Nothing to be done for `all'.
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/prep_cif.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/prep_cif.c
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/prep_cif.c  -fno-common -DPIC -o src/.libs/prep_cif.o
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/types.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/types.c
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/types.c  -fno-common -DPIC -o src/.libs/types.o
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/raw_api.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/raw_api.c
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/raw_api.c  -fno-common -DPIC -o src/.libs/raw_api.o
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/java_raw_api.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/java_raw_api.c
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/java_raw_api.c  -fno-common -DPIC -o src/.libs/java_raw_api.o
> /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/java_raw_api.c:328:46: warning: 'ffi_java_raw_size' is deprecated [-Wdeprecated-declarations]
>   ffi_java_raw *raw = (ffi_java_raw*)alloca (ffi_java_raw_size (cif));
>                                              ^
> include/ffi.h:299:56: note: 'ffi_java_raw_size' has been explicitly marked deprecated here
> size_t ffi_java_raw_size (ffi_cif *cif) __attribute__((deprecated));
>                                                        ^
> /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/java_raw_api.c:331:3: warning: 'ffi_java_ptrarray_to_raw' is deprecated [-Wdeprecated-declarations]
>   ffi_java_ptrarray_to_raw (cif, avalue, raw);
>   ^
> include/ffi.h:295:93: note: 'ffi_java_ptrarray_to_raw' has been explicitly marked deprecated here
> void ffi_java_ptrarray_to_raw (ffi_cif *cif, void **args, ffi_java_raw *raw) __attribute__((deprecated));
>                                                                                             ^
> 2 warnings generated.
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/closures.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/closures.c
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/closures.c  -fno-common -DPIC -o src/.libs/closures.o
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/x86/ffi64.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/x86/ffi64.c
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/x86/ffi64.c  -fno-common -DPIC -o src/x86/.libs/ffi64.o
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64  -c -o src/x86/unix64.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/x86/unix64.S
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/x86/unix64.S  -fno-common -DPIC -o src/x86/.libs/unix64.o
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src   -arch x86_64  -Wall -fexceptions -c -o src/x86/ffiw64.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/x86/ffiw64.c
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -Wall -fexceptions -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/x86/ffiw64.c  -fno-common -DPIC -o src/x86/.libs/ffiw64.o
> /bin/sh ./libtool  --tag=CC   --mode=compile xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src  -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64  -c -o src/x86/win64.lo /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/x86/win64.S
> libtool: compile:  xcrun clang -DHAVE_CONFIG_H -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -I. -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/include -Iinclude -I/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src -arch x86_64 -c /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/src/x86/win64.S  -fno-common -DPIC -o src/x86/.libs/win64.o
> /bin/sh ./libtool  --tag=CC   --mode=link xcrun clang  -arch x86_64  -Wall -fexceptions  -arch x86_64 -o libffi_convenience.la  src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo   src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffiw64.lo src/x86/win64.lo 
> libtool: link: ar cru .libs/libffi_convenience.a src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffiw64.o src/x86/.libs/win64.o 
> ar: `u' modifier ignored since `D' is the default (see `U')
> libtool: link: ranlib .libs/libffi_convenience.a
> libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s "../libffi_convenience.la" "libffi_convenience.la" )
> /bin/sh ./libtool  --tag=CC   --mode=link xcrun clang  -arch x86_64  -Wall -fexceptions -no-undefined -version-info `grep -v '^#' /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi/libtool-version`   '-arch' 'x86_64'  -arch x86_64 -o libffi.la -rpath /usr/local/lib src/prep_cif.lo src/types.lo src/raw_api.lo src/java_raw_api.lo src/closures.lo  src/x86/ffi64.lo src/x86/unix64.lo src/x86/ffiw64.lo src/x86/win64.lo 
> libtool: link:  xcrun clang -dynamiclib  -o .libs/libffi.7.dylib  src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffiw64.o src/x86/.libs/win64.o    -arch x86_64 -arch x86_64 -arch x86_64   -install_name  /usr/local/lib/libffi.7.dylib -compatibility_version 9 -current_version 9.0 -Wl,-single_module
> libtool: link: dsymutil .libs/libffi.7.dylib || :
> warning: no debug symbols in executable (-arch x86_64)
> libtool: link: (cd ".libs" && rm -f "libffi.dylib" && ln -s "libffi.7.dylib" "libffi.dylib")
> libtool: link: ( cd ".libs" && rm -f "libffi.la" && ln -s "../libffi.la" "libffi.la" )
> # Assemble into a FAT (x86_64, i386, ppc) library
> /usr/bin/libtool -static -o "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi-universal-darwin19"/.libs/libffi_convenience.a \
> 	    "/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c"/libffi-x86_64/.libs/libffi_convenience.a
> error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi-x86_64/.libs/libffi_convenience.a(/) is not an object file (not allowed in a library)
> make: *** ["/Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2/ext/ffi_c/libffi-universal-darwin19"/.libs/libffi_convenience.a] Error 1
> 
> make failed, exit code 2
> 
> Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/ffi-1.12.2 for inspection.
> Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/ffi-1.12.2/gem_make.out

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Please see https://github.com/CocoaPods/CocoaPods/issues/9641

**Comment by RoadToDream** [comment]
Seems that post doesn't solve the issue, still cannot install cocoapods using system system ruby even the version is 2.6.3.

**Comment by ananay** [comment]
@RoadToDream I got the same error; installing ffi worked for me, here's the command I used:

`sudo LDFLAGS="-L/usr/local/opt/libffi/lib" PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig" gem install ffi -v '1.9.25'`

then do `sudo gem install cocoapods`
