### ISSUE TITLE
pod list - NoMethodError - undefined method `version' for nil:NilClass

### ISSUE THREAD

**Issue by maciejtrybilo** [CocoaPods/CocoaPods#9728]
### Command

```
/usr/local/bin/pod list
```

### Report

* What did you do?
Run `pod list`

* What did you expect to happen?
The list of pods. I'm not interested in the list of pods as such, but it's part of what Microsoft's Objective Sharpie utility does, so I'm trying to figure out why `pod list` is failing.

* What happened instead?

I see lots of pods printed out all the way to `PNImagePicker 1.2.5`. Then the error below.
### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.26.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ dd74c000d2e79a7328ec852948a5e16ccd239f33

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `version' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:214:in `pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/list.rb:24:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/list.rb:24:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/list.rb:24:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment]
Need a sample app.

**Comment by dnkoutso** [comment]
Sorry wrong issue!

**Comment by dnkoutso** [comment]
Just tried it for me and it worked.
```
...
  CatalogShared 1.20200504.221803
  I18nShared 1.20200504.221803
  IcalShared 1.20200504.221803
  InventoryShared 1.20200504.221803
  J2ObjC-square 2.0.5-sq2
  J2objcRuntime 2.0.5-sq30
  JavaObjCConversionUtils 1.20200504.221803
  PLCrashReporter 1.5.1 <---------------
  PricingEngineBridge 1.20200504.221803
  PricingEnginePrimitives 1.20200504.221803
  PricingShared 1.20200504.221803
  ProtobufRuntime 1.20200504.221803
```

Would love some help here to diagnose and debug otherwise this issue will be auto-closed eventually.

**Comment by dnkoutso** [comment]
I continue to read things wrong in this thread. It was a different pod you saw this.

**Comment by maciejtrybilo** [comment]
It did start working at some point again. I reckon it might be configuration of a certain pod that tripped it. I hoped that the stack trace would give enough info to prevent `pod` from crashing in such case.

**Comment by dnkoutso** [comment]
@maciejtrybilo doyou think you can repro? If not I am afraid we have to close.

**Comment by maciejtrybilo** [comment]
I presume you'd have to run `pod list` against a trunk commit from 18th of April and see what was up with the repo that comes after `PNImagePicker` to see what triggered the issue. I'm probably not the best guy to try doing it.

**Comment by dnkoutso** [comment]
I will close this for now and we can re-open if we see it.
