### ISSUE TITLE
Input file list `xcfilelist` not found

### ISSUE THREAD

**Issue by jayz5** [CocoaPods/CocoaPods#9729]
Xcode version 11.4, project compatibility Xcode 3.2.

Tried different packages, like Tesseract and Firebase Analytics, but `pod install` always generate in Build Phase "[CP] Embed Pods Frameworks" some input file list 

"${PODS_ROOT}/Target Support Files/Pods-XXX/Pods-WordsLens-frameworks-${CONFIGURATION}-input-files.xcfilelist"

which Xcode complains not able to find.

Tried every solution in https://stackoverflow.com/q/55505991/1724059, but none works. Particularly if I try removing the files from input/output file list Pods complain that it's incompabile with Podfile.lock and must run `pod install` , which puts the input/output file lists back.

**Comment by dnkoutso** [comment]
Need a sample app with clear reproducible steps for us to diagnose/debug. Please upload one.

**Comment by jayz5** [comment]
I just created an empty project and added 'Firebase' as the pod content, and it also populated the intputfilelist and outputfilelist with some .xcfilelist. However this project does compile and can run, so I don't know why in my real project it complains about why it can't find .xcfilelist. I suspected it was because I also has a Swift Package Dependency (introduced in Xcode 11), but removing that didn't help.

**Comment by jayz5** [comment]
The problem is with my project for some reason the Pods script cannot access /dev/null, and the PODS_ROOT dir is not defined, even after I deintegrate pods and re-install multiple times. My other projects are all fine. Not sure why, but at least now I can work around it by some manual processes.

**Comment by dnkoutso** [comment]
OK. going to close preemptively. I will re-open this once and if you find out a sample you can upload here for us to diagnose and debug.
