### ISSUE TITLE
rsync: failed to open files-from file Repo/Pods/resources-to-copy-Project.txt

### ISSUE THREAD

**Issue by hissain** [CocoaPods/CocoaPods#9735]
Cocoapod version 1.6.2

I am getting below build error for an iOS project which was buildable previously without any source code modification.

```
rsync: failed to open files-from file Repo/Pods/resources-to-copy-Project.txt: Permission denied
Unexpected Failure
```

In my project I found no script like ${SRCROOT}/Pods/Pods-resources.sh

How to resolve it? My Mac is offline and I cannot run pod install anymore. Just need to build previously buildable project.

**Comment by dnkoutso** [comment]
Please update the version of CocoaPods to 1.9.1 as it might have fixed the issue. Also this issue does not conform to our issue template and there isn't much info for us to debug or diagnose.

Please ask on StackOverflow under `cocoapods` tag or upload a sample app here showing the issue.

Closing preemptively
