### ISSUE TITLE
I have no access to my older email due to company changing email addresses

### ISSUE THREAD

**Issue by ohernandezIBM** [CocoaPods/CocoaPods#9743]
I noticed that I could not see new pod I deployed. I then used:

ohernandezltkmacs-MacBook-Pro:1.0.0 ohernandez@us.ibm.com$ pod trunk me
  - Name:     Omar Hernandez
  - Email:    ohernandez@us.ibm.com
  - Since:    March 30th, 2018 14:30
  - Pods:
    - EOCore
    - EOCoreDebug
    - IBMTealeaf
    - IBMTealeafDebug
    - DigitalAnalytics
    - DigitalAnalyticsDebug
    - IBMTealeafReactNativeDebug
    - IBMTealeafReactNative
    - TealeafMD5
    - TealeafSHA2
  - Sessions:
    - March 30th, 2018 14:30 - August 5th, 2018 14:30. IP: 98.248.18.4   Description: IBM Customer Analytics Core Library
    - June 1st, 2018 16:17   -     August 28th, 18:55. IP: 67.180.26.237

I forgot to update my email, I tried https://github.com/CocoaPods/CocoaPods/issues/5109. I registered a new email:

ohernandezltkmacs-MacBook-Pro:1.0.0 ohernandez@us.ibm.com$ pod trunk me
  - Name:     Omar Hernandez
  - Email:    omar.hernandez@acoustic.co
  - Since:    April 22nd, 19:10
  - Pods:     None
  - Sessions:
    - April 22nd, 19:10 - August 28th, 19:20. IP: 67.164.73.137

But now I can not add new owners on my old repos. How can I fix this?

**Comment by amorde** [comment]
Hi Omar,

We got all of the dispute requests you submitted, and we'll get to them. Sorry the response isn't super quick, but we do see them 👍

**Comment by ohernandezIBM** [comment]
ok thank you

**Comment by ohernandezIBM** [comment]
any update?

**Comment by amorde** [comment]
@orta Sorry to ping you directly - can you take a look at the disputes submitted by Omar?

**Comment by ohernandezIBM** [comment]
I need to do some releases, thank you

**Comment by sdamale** [comment]
Hi @amorde , @orta Can you please update Omar's email id ? Appreciate your support in this matter.

**Comment by ohernandezIBM** [comment]
Any update? @amorde or @orta

**Comment by amorde** [comment]
Got these handled, thanks for your patience 🙏 

It looks like some had already been resolved (maybe @sdamale added you), but if any were missed submit another dispute and we'll get to it.

**Comment by sdamale** [comment]
Thank you @amorde @orta !
