### ISSUE TITLE
Private pod, s.dependency 'xxx', :configurations => ['Debug'], but it does not work

### ISSUE THREAD

**Issue by lxz555** [CocoaPods/CocoaPods#9744]
```ruby
  s.ios.deployment_target = '8.0'
  s.source_files = 'gscomponentdebugkit/Classes/**/*'

  s.dependency 'xxx', :configurations => ['Debug']
```
It is a private pod, it dependency some other pod 'xxx' which wish only debug , but I counld see 'xxx' in xcode-build settings-other linker flags-Release.  What should I do?

**Comment by dnkoutso** [comment]
This is not sufficient information. Please upload a sample app and use our issue template with step-by-step instructions.

Going to close as incomplete issue template here.

**Comment by XHL-Mao** [comment]
> This is not sufficient information. Please upload a sample app and use our issue template with step-by-step instructions.
> 
> Going to close as incomplete issue template here.

[TestSpecDebug.zip](https://github.com/CocoaPods/CocoaPods/files/5127190/TestSpecDebug.zip)

Hello  @dnkoutso , same question  

TestSpecDebug.zip is a sample project

**Comment by summerHearts** [comment]
@XHL-Mao  你解决了嘛

**Comment by xujiebing** [comment]
楼主解决了吗
