### ISSUE TITLE
Framework built in swift evolution mode can't load static dependencies

### ISSUE THREAD

**Issue by sirghi** [CocoaPods/CocoaPods#9751]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

This is a bit tricky and I don't know whether the problem lies within Cocoapods/Xcode/Swift, so please bear with me.

We're building a static vendored framework (`FrameworkA`), that has a dependency. We want to build it with BUILD_LIBRARY_FOR_DISTRIBUTION, so that integrators can use newer Xcode versions without waiting for us to rebuild the framework for the new Swift version.

The framework is built statically, and the integrators ought to also setup the other dependencies statically, so as not to have too many dynamic frameworks in the app.

Now, if you look in the attached repo, you'll find the following products along with dependencies:

1. The FrameworkA project (BUILD_LIBRARY_FOR_DISTRIBUTION is set) <- Apollo (via submodules)
2. The App <- FrameworkA (Cocoapods) <- Apollo (Cocoapods)

The second setup is of interest. There are 3 commits in the repo. If you checkout the first commit, the framework is built with the current (5.2) swift version, CocoaPods integrated statically. It builds fine.

If you checkout the second commit, I swapped in a framework that's built with the 5.1.2 swift toolchain. It fails to build with an `Cannot load underlying module for 'Apollo'` error in the .swiftinterface file (_Note_, I provided only the Simulator slice for simplicity).

If you checkout the third commit, I moved the pods to _use_frameworks!_, and it builds fine again.

Any ideas about what's going on would be highly appreciated. Namely, when linking dependencies statically, why can't it find the underlying module?

Thanks

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /Users/xxxx/.rbenv/versions/2.6.5/lib
Repositories : 
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/xxxx/.rbenv/versions/2.6.5/bin/pod
```

### Plugins

```
claide-plugins             : 0.9.2
cocoapods-acknowledgements : 1.2.0
cocoapods-deintegrate      : 1.0.4
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.1.0
cocoapods-trunk            : 1.4.1
cocoapods-try              : 1.1.0
slather                    : 2.4.7
```

### Podfile

```ruby
platform :ios, '9.0'

use_frameworks!

target 'Opa' do
	pod'FrameworkA', :path => '.'
end


# post_install do |installer|
#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
#           config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#       end
#     end
# end
```
## Project that demonstrates the issue

https://github.com/sirghi/library-built-for-distribution

**Comment by paulb777** [comment]
Modules aren't created unless the Podfile specifies `use_frameworks!`. Likely you want `use_frameworks! :linkage => :static`

**Comment by sirghi** [comment]
Confirmed that adding the `:linkage => :static` directive solved the issue.

**Comment by bentonquest** [comment]
Hi! Any ideas on how to solve this without requiring `use_frameworks!` flag?
