### ISSUE TITLE
App spec: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon"

### ISSUE THREAD

**Issue by acecilia** [CocoaPods/CocoaPods#9755]
When using an app spec inside a podspec I get the following error despite my app spec has a `.xcassets` with an `AppIcon` image set on it:

```
/* com.apple.actool.errors */

...../Media.xcassets:1:1: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".

/* com.apple.actool.compilation-results */
```

I troubleshooted that this happens when the main spec has also a `.xcassets` resource.

My podspec:

```
Pod::Spec.new do |s|
  s.name                  = 'Sample'
  s.version               = '0.0.1'
  s.swift_version         = '5.0'
  s.ios.deployment_target = '11.0'
  s.ios.source_files      = 'main/**/*.swift'
  s.ios.resources         = 'main/Media.xcassets'

  s.test_spec 'test' do |test_spec|
    test_spec.ios.source_files = 'test/**/*.swift'
  end

  s.app_spec 'sample' do |app_spec|
    app_spec.ios.source_files = 'sample/**/*.swift'
    app_spec.ios.resources    = 'sample/Media.xcassets'
  end

  # Dummy data required by cocoapods
  s.authors                = 'dummy'
  s.summary                = 'dummy'
  s.homepage               = 'dummy'
  s.license                = { :type => 'MIT' }
  s.source                 = { :git => '' }
end
```

Find an example project here: https://github.com/acecilia/SampleCocoapodsProject

How to reproduce:
```
git clone https://github.com/acecilia/SampleCocoapodsProject
cd SampleCocoapodsProject
bundle install
bundle exec pod install
open Pods/Sample.xcodeproj
# And now run the app scheme: Sample-sample
```

Cocoapods 1.9.1, Catalina, Xcode 11.3.1

I believe that the root problem is the issue described in https://github.com/CocoaPods/CocoaPods/issues/1546 (which I do not think is solved despite it being closed), which I have also experienced: if I have a podspec with assets and test subspec with assets, the test assets never get embed into the test bundle because they are overwritten by the assets from the main spec.

Some people suggest that the workaround is to add an empty `AppIcon` image set in the assets of the main spec. This does in fact get rid of the cocoapods error and the app builds, but then the app will crash at runtime when trying to access an asset, I believe due to the reason explained above (the app subspec assets are not in the sample app bundle because they are overwritten with the assets from the main spec, and the app crashes when accessing them).

Moving the `Copy Bundle Resources` build phase to the last step fixes the problem of the assets not being embed into the bundle (you still need a dummy `AppIcon` in the assets of the main spec though), but since this is something I can NOT express in code, I do not think there is an existing workaround for any of this issues.

**Comment by acecilia** [comment]
I can confirm that if you use `resource_bundles` in all your frameworks, you can use `resources` in the app spec and it works

**Comment by acecilia** [comment]
Another problem: it is not possible to use `xcassets` that are located in resource bundles: https://stackoverflow.com/a/23903860

**Comment by acecilia** [comment]
@dnkoutso I would very much appreciate your feedback here :)

**Comment by amorde** [comment]
I think this is currently tracked in https://github.com/CocoaPods/CocoaPods/issues/7745, we haven't been able to get this to work yet unfortunately. The use of a resource_bundle is the currently recommended workaround
