### ISSUE TITLE
Cocoapods website not working - Internal Server Error

### ISSUE THREAD

**Issue by marcodd23** [CocoaPods/CocoaPods#9763]
# Report

## What did you do?

ℹ I browsed to cocoapods.org

## What did you expect to happen?

ℹ Expected to see the homepage

## What happened instead?

ℹ  Internal Server Error

**Comment by dnkoutso** [comment]
Not sure what the root cause has been but its back online now.

**Comment by JimmyRare** [comment]
Internal Server Error again

**Comment by harrybui2804** [comment]
.

**Comment by krzykol123** [comment]
and again. Internal Server Error

**Comment by marcinbogiel** [comment]
Internal Server Error again

**Comment by chuannm** [comment]
One more time ==> Internal Server Error

**Comment by GuitarKitty** [comment]
Internal Server Error again

**Comment by sbqsbqsbq** [comment]
Internal server error again.

**Comment by jevonmao** [comment]
Internal server error again

**Comment by jeffala** [comment]
Having this issue now.

**Comment by jason-hwang** [comment]
Anybody website is working now?

**Comment by SungKihun** [comment]
Internal server error again

**Comment by maonz** [comment]
Internal server error

**Comment by MichaelSebsbe** [comment]
Internal server error: it's been like 2hrs

**Comment by maonz** [comment]
> Internal server error: it's been like 2hrs

more than

**Comment by Junker** [comment]
again...

**Comment by prateekshac1** [comment]
Happening now again

**Comment by Invader1999** [comment]
Happening now again
