### ISSUE TITLE
Does cocoapods  support dynamic framework take option about Embedded & sign?

### ISSUE THREAD

**Issue by LionNeo** [CocoaPods/CocoaPods#9764]
I have a question about bring the ohter dynamic framework into my project by pod.but this framework must require Embedded & sign . I try to writte my podspec :

s.ios.vendored_frameworks = 'demo.framework'

Although  project  can install framework by pod , it does not work.
 so  i wonder if there is a way to make the dynamic framework  Embedded & sign introduced ?

**Comment by dnkoutso** [comment]
I dont think this is supported today and I dont quite understand what you are asking for here.
