### ISSUE TITLE
pod lib lint cause `incompatible encoding regexp match` for non-ascii pod name

### ISSUE THREAD

**Issue by banjun** [CocoaPods/CocoaPods#9765]
* [x] 🌈 I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `git clone https://github.com/banjun/ikemen` and `cd ikemen`
Run `pod lib lint`

## What did you expect to happen?

The lint pass without errors.

## What happened instead?

```
 -> ※ikemen (0.6.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)) during validation.
```

Note that `※ikemen` has a non-ascii character `※` in its pod name.

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.25.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 0a4408de50e224aa6f8f5897d77a2a794afae854

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-app_group   : 0.4.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

https://github.com/banjun/ikemen

The pod has been validated for years (2015-).

# Possible Fix

This change fixes the problem

https://github.com/banjun/CocoaPods/commit/def8d761479e58c9ca2641447b0b0736f2c2b26d

# Other Configurations

I have tried to reproduce in other environments. It might be caused by Catalina or Catalina system ruby...? 🤔

| Configuration | Result | Screenshot |
|--------------|------|-----------|
| [Github Actions on macOS-latest (log)](https://github.com/banjun/ikemen/runs/646945044?check_suite_focus=true) | ❌ NG | <img width="589" alt="image-2" src="https://user-images.githubusercontent.com/11156/81102767-0d7f7f00-8f4b-11ea-8d05-f1a3033ca5ac.png"> |
| [bitrise on Catalina stack (log)](https://app.bitrise.io/build/294c86c6bbdc3b79#?tab=log) | ❌ NG | ![image-4](https://user-images.githubusercontent.com/11156/81102802-1cfec800-8f4b-11ea-84ad-3238014411c5.png) |
| [bitrise on Mojave stack (log)](https://app.bitrise.io/build/7908c3f6b04b3fef#?tab=log) | ✅ OK |![image-3](https://user-images.githubusercontent.com/11156/81102832-29832080-8f4b-11ea-96b9-3c7098a362c6.png) |

**Comment by dnkoutso** [comment]
Its probably because of the `※` character.

**Comment by banjun** [comment]
@dnkoutso yes it makes sense but non-ascii names including the character have been valid and cocoapods/specs already have such names.

**Comment by dnkoutso** [comment]
Can you please make a PR and add a test to fix this?

**Comment by banjun** [comment]
@dnkoutso Yes, I will do that 👍
