### ISSUE TITLE
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. Build system information     error: Multiple commands produce.

### ISSUE THREAD

**Issue by gurjindersinghkhalsa** [CocoaPods/CocoaPods#9766]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod spec lint --verbose`

## What did you expect to happen?

It should validate podspec file

## What happened instead?

 Build system information
    error: Multiple commands produce '/var/folders/m_/6h1x546s4n1c_98qv9z_q71h0000gn/T/CocoaPods-Lint-20200506-54931-14tx6je-TrackingSdk/Build/Products/Release-iphonesimulator/TrackingSdk/TrackingSdk.framework/Headers/GCDAsyncUdpSocket.h':

 Build system information
    error: Multiple commands produce '/var/folders/m_/6h1x546s4n1c_98qv9z_q71h0000gn/T/CocoaPods-Lint-20200506-54931-14tx6je-TrackingSdk/Build/Products/Release-iphonesimulator/TrackingSdk/TrackingSdk.framework/Headers/GCDAsyncSocket.h':

  Build system information
    error: Multiple commands produce '/var/folders/m_/6h1x546s4n1c_98qv9z_q71h0000gn/T/CocoaPods-Lint-20200506-54931-14tx6je-TrackingSdk/Build/Products/Release-iphonesimulator/TrackingSdk/TrackingSdk.framework/traffic_startcap.png':

    Build system information
    error: Multiple commands produce '/var/folders/m_/6h1x546s4n1c_98qv9z_q71h0000gn/T/CocoaPods-Lint-20200506-54931-14tx6je-TrackingSdk/Build/Products/Release-iphonesimulator/TrackingSdk/TrackingSdk.framework/bubble_right@3x.png':

..and more like this.
### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.25.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

My SDK has Static framework 
- CocoaAsyncSocket.framework
- GoogleMaps.bundle
- GooglePlaces.bundle
- GoogleMaps.framework
- GoogleMapsBase.framework
- GoogleMapsCore.framework
- GooglePlaces.framework

This is my podspec file

Pod::Spec.new do |s|

s.name         = 'TrackingSdk'
s.version      = '0.0.3'
s.summary      = 'Now add Tookan Tracker in app for quick tracking.'
s.homepage     = 'https://github.com/tookanapp/tookan-tracker-ios'
s.license      = 'MIT'
s.author             = { 'Dev' => 'test' }
s.source       = { :git => 'https://github.com/tookanapp/tookan-tracker-ios.git', :tag => s.version }
s.ios.deployment_target = '9.0'

s.source_files = 'TookanTracker/TookanTracker/**/*.{h,m,swift}'
s.resources = 'TookanTracker/**/*.{png,jpeg,jpg,storyboard,xib,xcassets}'

#s.exclude_files = 'TookanTracker/TookanTracker/DemoApp'
#s.static_framework = false

s.swift_version = '5.0'

end

**Comment by dnkoutso** [comment]
Build works for me but validation fails for a different (valid) reason.
```
    ** BUILD SUCCEEDED ** [0.531 sec]
    
   Testing with `xcodebuild`. 
 -> TrackingSdk (0.0.3)
    - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - ERROR | [iOS] file patterns: The `resources` pattern did not match any file.
    - WARN  | [iOS] license: Unable to find a license file
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')

Pods workspace available at `/var/folders/g7/83vp4gbx2q58k1wd02f17b4r0000gn/T/CocoaPods-Lint-20200506-66422-g0vgo3-TrackingSdk/App.xcworkspace` for inspection.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 2 errors and 1 warning.
```

Please provide clear reproducible steps and a sample app.

**Comment by gurjindersinghkhalsa** [comment]
All the duplicate files are eitherinside static frameworks(GoogleMaps or GooglePlaces) and Objective C classes.

**Comment by gurjindersinghkhalsa** [comment]
All the duplicate files are either inside static frameworks(GoogleMaps or GooglePlaces) and Objective C classes.

**Comment by gurjindersinghkhalsa** [comment]
Please Help!

**Comment by paulb777** [comment]
@gurjindersinghkhalsa It would help to provide step-by-step reproduction instructions.

**Comment by gurjindersinghkhalsa** [comment]
@paulb777 
Please find the sample on below link
https://github.com/mukul-kansal/test

**Comment by gurjindersinghkhalsa** [comment]
@paulb777 
Sample can be found at https://github.com/mukul-kansal/tookan-tracker-ios

**Comment by gurjindersinghkhalsa** [comment]
@paulb777  and @dnkoutso Please update on this?

**Comment by paulb777** [comment]
The source and resource patterns pick up every file in the repo.

```
s.source_files = 'TookanTracker/**/*.{h,m,swift}'
s.resources = 'TookanTracker/**/*.{png,jpeg,jpg,storyboard,xib,xcassets}'
```

and there are duplicates like 

```
$ find . | grep GCDAsyncSocket.h
./TookanTracker/GCD/GCDAsyncSocket.h
./TookanTracker/SDK/CocoaAsyncSocket.framework/Headers/GCDAsyncSocket.h
```
It can also be seen directly in Xcode by running `pod lib lint TookanTracker.podspec --no-clean`:

![Screen Shot 2020-05-16 at 7 21 13 AM](https://user-images.githubusercontent.com/73870/82122024-daf13580-9745-11ea-8130-c0435ff76976.png)

**Comment by gurjindersinghkhalsa** [comment]
@paulb777 
Can you help me to set the correct path? As I am unable to do it.

**Comment by paulb777** [comment]
@gurjindersinghkhalsa Make sure that the file patterns in the podspec don't include duplicates. stackoverflow.com is probably a better forum for usage help where you can show what you've tried.

**Comment by Tareshjain16** [comment]
@gurjindersinghkhalsa I am facing same issue, have you got any solution?

**Comment by gurjindersinghkhalsa** [comment]
@Tareshjain16 I removed the .xcodeproj file from a folder that I was using for Pod
