### ISSUE TITLE
GoogleWebRTC spec has incorrect minimum iOS versions

### ISSUE THREAD

**Issue by ctsimmonds** [CocoaPods/CocoaPods#9768]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

My Podfile contains:
```platform :ios, '9.0'```
and
```  pod 'GoogleWebRTC', '1.1.26989'```

It successfully builds for the iOS 9.0 target. But when run on an actual iOS 9.0 device, it crashes because the binary framework actually has the minimum OS level of 10.0:

```
$ otool -l GoogleWebRTC-1.1.27828/Frameworks/frameworks/WebRTC.framework/WebRTC | grep -A3 VERSION_MIN
      cmd LC_VERSION_MIN_IPHONEOS
  cmdsize 16
  version 10.0
      sdk 12.0
```

## What did you expect to happen?

CocoaPods should have flagged that this version was not compatible with iOS 9.0 and provided an error at build time.

The problem appears to be the the spec file for the pod incorrectly lists the minimum OS version as 9.0 <https://github.com/CocoaPods/Specs/blob/master/Specs/2/c/6/GoogleWebRTC/1.1.27828/GoogleWebRTC.podspec.json>:
```
 "platforms": {
    "ios": "9.0"
  },
```

Looking through the older versions, 1.1.26989 was the last version for which the binary actually supported iOS 9. All of the newer versions have a real minimum level of iOS 10.0 and the pod spec files should be updated to reflect that.

**Comment by ctsimmonds** [comment]
Typo in the description: the version in my podfile was 1.1.27828, not 1.1.26989.

**Comment by amorde** [comment]
Thanks, but this doesn't appear to be an issue with CocoaPods itself. I'd recommend contacting the Pod authors instead of posting an issue here. Looks like they have a [mailing list](https://groups.google.com/forum/#!forum/discuss-webrtc), and the source is hosted [here](https://webrtc.googlesource.com/src)
