### ISSUE TITLE
pod install library(remote:Repository not found)

### ISSUE THREAD

**Issue by ZainLiOK** [CocoaPods/CocoaPods#9770]
pod install error:

[!] Error installing FMDBMigrationManager
[!] /usr/bin/git clone https://github.com/layerhq/FMDBMigrationManager.git /var/folders/jm/7jj4q8xs20j45srst4tyrkvc0000gn/T/d20200507-41753-1vcyf3s --template= --single-branch --depth 1 --branch v1.4.1

Cloning into '/var/folders/jm/7jj4q8xs20j45srst4tyrkvc0000gn/T/d20200507-41753-1vcyf3s'...
remote: Repository not found.
fatal: repository 'https://github.com/layerhq/FMDBMigrationManager.git/' not found

**Comment by dnkoutso** [comment]
This is an insufficient error report. seems like https://github.com/layerhq/FMDBMigrationManager/ is not working after I tried it.

**Comment by ZainLiOK** [comment]
Pod search FMDBMigrationManager is exists
ssh -T git@github.com is success
Why this error？

**Comment by jonnehomie** [comment]
I get the same error with both 'pod update' and 'pod install'. Below output running pod update:

```
> pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing FMDBMigrationManager (1.4.1)
Username for 'https://github.com': myuser
Password for 'https://myuser@github.com': 

[!] Error installing FMDBMigrationManager
[!] /usr/bin/git clone https://github.com/layerhq/FMDBMigrationManager.git /var/folders/0y/dpg5lf9j4n191rys3w3v6gfc0000gn/T/d20200525-10753-ys4oaq --template= --single-branch --depth 1 --branch v1.4.1

Cloning into '/var/folders/0y/dpg5lf9j4n191rys3w3v6gfc0000gn/T/d20200525-10753-ys4oaq'...
remote: Repository not found.
fatal: repository 'https://github.com/layerhq/FMDBMigrationManager.git/' not found
```
The same commands used to worked before. Has the original project been removed since you get 404 Not Found when browsing this url: https://github.com/layerhq/FMDBMigrationManager/

**Comment by paulb777** [comment]
According to https://github.com/layerhq/, that organization has no public repositories.
