### ISSUE TITLE
[!] Error installing GoogleMaps [!] /usr/bin/curl -f -L -o /var/folders/xd/jmncvtdj289bbmjrn_05gzkc0000gn/T/d20200507-32106-fkal70/file.tgz https://dl.google.com/dl/cpdc/6102410a0f276cba/GoogleMaps-3.8.0.tar.gz --create-dirs --netrc-optional --retry 2    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                  Dload  Upload   Total   Spent    Left  Speed   7 56.1M    7 4095k    0     0  13319      0  1:13:40  0:05:14  1:08:26 17346 curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

### ISSUE THREAD

**Issue by oluwatobiHammed** [CocoaPods/CocoaPods#9773]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
e.g. Install all pod dependencies correctly.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by oluwatobiHammed** [comment]
[!] Error installing GoogleMaps
[!] /usr/bin/curl -f -L -o /var/folders/xd/jmncvtdj289bbmjrn_05gzkc0000gn/T/d20200507-32106-fkal70/file.tgz https://dl.google.com/dl/cpdc/6102410a0f276cba/GoogleMaps-3.8.0.tar.gz --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  7 56.1M    7 4095k    0     0  13319      0  1:13:40  0:05:14  1:08:26 17346
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

**Comment by oluwatobiHammed** [comment]
[!] Error installing FirebaseInstanceID
[!] /usr/local/bin/git clone https://github.com/firebase/firebase-ios-sdk.git /var/folders/xd/jmncvtdj289bbmjrn_05gzkc0000gn/T/d20200507-29429-1f4essp --template= --single-branch --depth 1 --branch InstanceID-4.3.0

Cloning into '/var/folders/xd/jmncvtdj289bbmjrn_05gzkc0000gn/T/d20200507-29429-1f4essp'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by dominic-mynt** [comment]
Hello @oluwatobiHammed, did you find a fix for this issue? I'm also experiencing this.

**Comment by 15krati** [comment]
Installing IDnowSDK (4.5.299)

[!] Error installing IDnowSDK
[!] /usr/bin/curl -f -L -o /var/folders/z0/8bj3tq9561xblflnhrrynwt80000gn/T/d20210524-50568-zpj2cf/file.tgz https://downloads.idnow.de/ios/idnow-ios-4.5.2.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 25  281M   25 70.7M    0     0   190k      0  0:25:09  0:06:19  0:18:50  285k
curl: (18) transfer closed with 220567643 bytes remaining to read

I'm getting the same issue while installing "IDnowSDK" pod.
Anyone have idea regarding this error?
