### ISSUE TITLE
 Couldn't connect to server

### ISSUE THREAD

**Issue by HeMa321** [CocoaPods/CocoaPods#9780]
[!] CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/6/7/d/boost-for-react-native/1.63.0/boost-for-react-native.podspec.json Response: Couldn't connect to server

**Comment by paulb777** [comment]
Transient networking failure?

**Comment by dnkoutso** [comment]
Seems so and a workaround is available to used the `git` based repo. Closing for now as the issue report does not appear sufficient for something for us to work with.
