### ISSUE TITLE
Ability to add custom parameters when running cocoapods cli

### ISSUE THREAD

**Issue by rpassis** [CocoaPods/CocoaPods#9783]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

As our `Podfile` gets more complex, we conditionally run various commands depending on the environment in which we are building for.

Up until now we've been relying mostly on environment variables to do this. So for example to determine the `platform` value in the `Podfile` we use:

```ruby
target_platform = (ENV["PODS_TARGET_PLATFORM"] || "ios").to_sym
```

Artsy uses a similar approach with both environment variables and also ARGV - see the [Podfile](https://github.com/artsy/eigen/blob/master/Podfile#L21) example here.

This works well but it requires a reasonable amount of implicit knowledge of how things work.

In an effort to be more explicit it would be great if we could, for example, include some of these flags as part of the command line:

```ruby
bundle exec pod install --custom-parameters --platform tvos
```

Is this something that has ever been considered/discussed with the Cocoapods team? If the team would consider this a worthwhile feature I'd be happy to work on the implementation. 

The changes are additive so there is very little risk involved, and I imagine the surface area that needs changing would be relatively small.

Let me know what you all think.
Rog

**Comment by dnkoutso** [comment]
Yes! Seems like a good improvement to add in my opinion as well.

**Comment by rpassis** [comment]
After some consideration I ended up creating a plugin for this instead. 

My reasoning is that this is unlikely to be needed by the majority of Cocoapods users so it is better suited as an opt-in feature.

You can find it [here](https://github.com/rpassis/cocoapods-env)
