### ISSUE TITLE
Linking error when xcframework is linked to framework distributed through CocoaPods

### ISSUE THREAD

**Issue by Hsilgos** [CocoaPods/CocoaPods#9784]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

Actually this issue was already mentioned [there](https://github.com/CocoaPods/CocoaPods/issues/9148#issuecomment-566573968) and [there](https://github.com/CocoaPods/CocoaPods/issues/9148#issuecomment-584442688), but no examples were provided.

# Report

## What did you do?

1. I built simple. xcframework: `test_xcframework.xcframework` which contains one file `foo.swift`:
```
import Foundation

public func foo() {
    print("test")
}
```
2. I creates simple project with framework:
```
pod lib create cocoa_framework
```
3. I copied `test_xcframework.xcframework` from step 1 to `cocoa_framework/Frameworks` and added it to `cocoa_framework.podspec` as vendored framework:
```
s.vendored_frameworks='cocoa_framework/Frameworks/test_xcframework.xcframework'
```
4. I ran `pod install`, opened `Example/cocoa_framework.xcodeproj` and tried to build.

## What did you expect to happen?

Compilation succeed.

## What happened instead?

I see linking error
```
ld: warning: ignoring file /Applications/here_av_excluded/temp/cocoa_issue/cocoa_framework/cocoa_framework/Frameworks/test_xcframework.xcframework/ios-arm64/test_xcframework.framework/test_xcframework, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture x86_64:
  "test_xcframework.foo() -> ()", referenced from:
      cocoa_framework.Bar() -> () in Bar.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.24.2 (Apple Git-127)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : here-cocoapods - git - ssh://khnykin@gerrit.it.here.com:29418/iot-sdk/cocoapods @ 3da1984d8e79d0f021d2aa03fd71cd3db0be167a

               master - git - https://github.com/CocoaPods/Specs.git @ b8bdf8e3686fe0b22fe458a75f1cede39badfa94

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '13.0'

use_frameworks!
target 'cocoa_framework_Tests' do
  pod 'cocoa_framework', :path => '../'
  
  
end
```

## Project that demonstrates the issue

There are two archive attached.:

[test_xcframework.zip](https://github.com/CocoaPods/CocoaPods/files/4617175/test_xcframework.zip)
is simple xcframework. Unzip it and build with script `build_xcframework.sh` inside. It should create xcframework by path `build/test_xcframework.xcframework`.

[cocoa_framework.zip](https://github.com/CocoaPods/CocoaPods/files/4617174/cocoa_framework.zip) is framework created with pods. Unzip it, copy `test_xcframework.xcframework` to `cocoa_framework/Frameworks` and run `pods install`

**Comment by dnkoutso** [comment]
Did you try latest master? I do not know from the issue report if its fixed or not but there were some updates on latest master of CocoaPods regarding XCFramework support.

**Comment by Hsilgos** [comment]
@dnkoutso 
When I added
```
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git' 
```
to `Example/Podfile`, run `pod install` and try to build project I see the same error.
I'm not very familiar with Cocoa though, so I'm not sure that I do it correctly.

**Comment by dnkoutso** [comment]
I mean latest master of CocoaPods not latest master of Alamofire

**Comment by Hsilgos** [comment]
@dnkoutso , It was challenging to run master :)
I don't see the error with master and build log looks much better.
Hopefully nothing else is broken. Do you know which version will include it?

**Comment by dnkoutso** [comment]
Will ship with 1.10!
