### ISSUE TITLE
Pod with XCFrameworks embedded libraries not compiling on simulator

### ISSUE THREAD

**Issue by remizorrr** [CocoaPods/CocoaPods#9785]
Setup is: 
Xcode 11.4.1,
Cocapods latest beta.

Local pod, with embedded (vendored_frameworks) xcframeworks.
project, referencing local pod.

compiling and running on the iPhone - everything works.
Compiling for simulator - getting following error.

```
ld: warning: ignoring file /Users/antonremizov/Documents/Work-Projects/CocoapodsExample/Library/Frameworks/CTFoundation.xcframework/ios-arm64/CTFoundation.framework/CTFoundation, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture x86_64:
  "(extension in CTFoundation):Swift.Array<A where A == Swift.UInt8>.hexString.getter : Swift.String", referenced from:
      Library.testPrint() -> () in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

attaching a sample project.

[CocoapodsExample.zip](https://github.com/CocoaPods/CocoaPods/files/4618905/CocoapodsExample.zip)

**Comment by dnkoutso** [comment]
Can you please try cocoapods latest master?

**Comment by remizorrr** [comment]
@dnkoutso Thank you. Top of tree master worked.

**Comment by dnkoutso** [comment]
Alright it will ship with 1.10 hopefully soon! Closing this for now and others can still find this issue.

**Comment by jaroslavas** [comment]
Any plans on when that soon may be expected?
And is there a document explaining how to install cocoapods from master?

**Comment by dnkoutso** [comment]
Use bundler https://bundler.io/v1.5/git.html

**Comment by dnkoutso** [comment]
As for the release there is no ETA on releases. Most of the work is done ad-hoc in the free time of folks.

**Comment by jaroslavas** [comment]
I've installed cocoapods from master branch (`0a46d4948ae6a3fd9fee8c022741e2c36baca86d`), `pod install` runs fine, but then while building the app I get `code object is not signed at all` error in `PhaseScriptExecution [CP] Embed Pods Frameworks` step:
```
Code Signing /Users/user/Library/Developer/Xcode/DerivedData/ProtonVPN-gbslyxolvvcktdcdnryucgxjnmgo/Build/Products/Debug-iphonesimulator/ProtonVPN.app/Frameworks/MyFramework.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/user/Library/Developer/Xcode/DerivedData/ProtonVPN-gbslyxolvvcktdcdnryucgxjnmgo/Build/Products/Debug-iphonesimulator/ProtonVPN.app/Frameworks/MyFramework.framework'
/Users/user/Library/Developer/Xcode/DerivedData/ProtonVPN-gbslyxolvvcktdcdnryucgxjnmgo/Build/Products/Debug-iphonesimulator/ProtonVPN.app/Frameworks/MyFramework.framework: code object is not signed at all
```

Any suggestions?

**Comment by amorde** [comment]
@jaroslavas could you open a separate issue with a sample project that reproduces the bug? that sounds different than what this issue was describing.

Looking at the error I don't have any suggestions ATM, haven't seen that particular error. Does look like you have a code signing identity set to `-` (maybe for Catalyst support?)
