### ISSUE TITLE
Nanaimo::Reader::ParseError - [!] Found additional characters after parsing the root plist object

### ISSUE THREAD

**Issue by kapilgoyal6** [CocoaPods/CocoaPods#9786]
While we run pod install, we are getting the error 

Nanaimo::Reader::ParseError - [!] Found additional characters after parsing the root plist object

#  -------------------------------------------
  #  			name = Libraries;
  #  			sourceTree = "<group>";
85>  		};
     		 ^
  #  		83CBB9F61A601CBA00E9B192 = {
  #  			isa = PBXGroup;
  #  -------------------------------------------

We are using nanaimo-0.2.6
xcodeproj-1.16.0
cocoapods-1.8.4

**Comment by amorde** [comment]
This is often due to a bad rebase or merge conflict. Will need a sample to confirm if thats not the case

**Comment by ZainabShakeel** [comment]
still facing error , has any solution

**Comment by qxh5696** [comment]
Hello, I'm running into this same issue with `nanaimo-0.3.0`, was there a fix to this issue?
