### ISSUE TITLE
Validation issue with pod deintegrate

### ISSUE THREAD

**Issue by chrismash2** [CocoaPods/CocoaPods#9787]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

Run `pod deintegrate`

## What did you expect to happen?

Deintegrate the pods from the projects

## What happened instead?

Hit a validation error:
[!] A valid Xcode project file is required.
([cocoapods-deintegrate-1.0.4/lib/cocoapods/command/deintegrate.rb:34](https://github.com/CocoaPods/cocoapods-deintegrate/blob/master/lib/cocoapods/command/deintegrate.rb))

No issues with `pod install`, just `pod deintegrate`, maybe the validations aren't aligned? I tried adding `project 'xxx'` all over the place but it didn't help.

## CocoaPods Environment

/Users/christopherma/.cocoapods/repos-art/xx-pods-retail/.artpodrc
/Users/christopherma/.cocoapods/repos-art/bba/.artpodrc
/Users/christopherma/.cocoapods/repos-art/bbi/.artpodrc

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : xx-pods-retail - file system
               bba - file system
               bbi - file system
               cocoapods - git - https://github.com/CocoaPods/Specs.git @ b5c60bc4fbaedb3445f8d66ac435b8c62689912b

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-art         : 1.0.4
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
workspace 'Workspace'

platform :ios, '11.0'

use_frameworks!
install! 'cocoapods', :deterministic_uuids => false
source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'abstract-target' do
  # Shared dependency between Framework and App
  pod 'SwiftyBeaver'

  target 'Framework' do
    project 'Framework/Framework.xcodeproj'
    use_frameworks!
  end

  target 'App' do
    project 'App/App.xcodeproj'
    platform :ios, '11.0'
    use_frameworks!
  end
end
```

**Comment by dnkoutso** [comment]
Please upload a sample app demonstrating the issue.

**Comment by chrismash2** [comment]
[pod deintegrate issue.zip](https://github.com/CocoaPods/CocoaPods/files/4633052/pod.deintegrate.issue.zip)

Just try and run `pod deintegrate` and it fails with the error. `pod install` was fine the first time and any time after.

**Comment by dnkoutso** [comment]
```ruby
        unless @project_path
          xcodeprojs = Pathname.glob('*.xcodeproj')
          @project_path = xcodeprojs.first if xcodeprojs.size == 1
        end

        help! 'A valid Xcode project file is required.' unless @project_path
```

The code looks to find `.xcodeproj` in the current working directory which you have none. You either have to pass the parameter or you have to run the command where an `.xcodeproj` is present.

`pod deintegrate App/App.xcodeproj`

worked for me.

Closing as working as expected.

**Comment by chrismash2** [comment]
Thanks for explaining, I assumed it would work in the same way `pod install` works from the root, which could be an improvement to make, but perhaps it's not intended to work in the same way, either way, problem solved for me!

**Comment by Zhamshid** [comment]
Make sure that you under **_/ios_** file
