### ISSUE TITLE
IBDesignable not works in custom framework

### ISSUE THREAD

**Issue by lioz12131415** [CocoaPods/CocoaPods#9789]
**Report**

## What did you do?
Use my custom framework which linked with CocoaPods' Frameworks

## What did you expect to happen?
Just works.

## What happened instead?
//file:///Users/******/********/*******/*******/*******/*******/*******/*******.storyboard: error: IB Designables: Failed to render and update auto layout status for ******* (N*Z-*n-**o): dlopen(*.framework, 1): no suitable image found.  Did find:
//*.framework: unknown file type, first eight bytes: 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A

//file:///Users/******/********/*******/*******/*******/*******/*******/*******/*******/*******.storyboard: error: IB Designables: Failed to render and update auto layout status for ******* (N*1-*1-**S): dlopen(*.framework, 1): Library not loaded: @rpath/AWSCore.framework/AWSCore
//Referenced from: *.framework
//Reason: image not found

## CocoaPods Environment

       CocoaPods : 1.9.1
       Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
       RubyGems : 2.5.2.3
       Host : Mac OS X 10.14.6 (18G95‏)
       Xcode : 11.3 (11C29)

## Project that demonstrates the issue
# platform :ios, '11.0'
inhibit_all_warnings!

target '*****' do
  
#use_frameworks!
use_modular_headers!

pod ‘AWSS3’
pod ‘SwiftyJSON’
pod 'SDWebImage'

end

**Comment by dnkoutso** [comment]
This seems like a corrupt `.framework` binary or something close to that. I dont think its a CocoaPods issue. Try integrating the framework manually without CocoaPods and see if it works.
