### ISSUE TITLE
Unable to push static framework

### ISSUE THREAD

**Issue by Srinija** [CocoaPods/CocoaPods#9791]
# Report

## What did you do?
I have a dynamic framework on Cocoapods. I want to change it to a static framework. 

Steps I followed:
- Changed the 'Mach-O Type' from 'Dynamic Library' to 'Static Library'. 
- Generated the '.framework' file.
- Replaced the dynamic framework in my repo with this. 
- Ran `pod lib lint --allow-warnings --no-clean`

## What did you expect to happen?

Validation to be successful

## What happened instead?
Got the following error:
`[iOS] xcodebuild:  clang: error: linker command failed with exit code 1`

<img width="1440" alt="cocoapod_error" src="https://user-images.githubusercontent.com/8607690/82134983-faf92580-9827-11ea-92b7-d1178fdf325e.png">

I opened the 'App.xcworkspace'(from the last line) and tried to build it using Xcode. The same build errors came up. 

When I added a 'BridgindHeader.h' to the project, all the errors disappeared and I was able to build the project. Not sure how to make the linter do this.

This was never necessary when the framework was dynamic. This issue is only after I converted it to a static framework.

Also, the framework will be used only in Swift projects. And it works just fine with Swift projects. Unfortunately, the linter seems to test with Objective C project.

I have been stuck with this for almost two days now. Any help would be appreciated!

## CocoaPods Environment

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.3.1 (11C505)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /usr/local/Cellar/ruby/2.5.0_2/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ c919cb908f0b2bb86220c3f4794a16f7d3b14086

               trunk - CDN - https://cdn.cocoapods.org/
```

## More details:
The codebase is entirely in swift and will be used in swift projects only.
Xcode version - 11.3.1
Build System - New build system

**Comment by paulb777** [comment]
Does it make a difference to add the option `--use-modular-headers`?
