### ISSUE TITLE
An internal server error occurred during trunk register

### ISSUE THREAD

**Issue by AnanthaKrish** [CocoaPods/CocoaPods#9796]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod trunk register <email> <username>`

## What did you expect to happen?

trunk register mail.

## What happened instead?
An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

**Comment by eladnava** [comment]
Reproducing as well.

Related: 
* https://stackoverflow.com/questions/61861711/begin-session-pod-trunk-register-shows-internal-server-error
* https://twitter.com/MainasuK/status/1262291504506089474
* https://twitter.com/divinedube/status/1262147498673569794

**Comment by dnkoutso** [comment]
Yeap someone is looking into it. In the meantime follow this issue instead https://github.com/CocoaPods/trunk.cocoapods.org/issues/284

**Comment by AnanthaKrish** [comment]
@dnkoutso Sure, thank you!
