### ISSUE TITLE
Error in pod referencing C + + framework and files

### ISSUE THREAD

**Issue by zdw19840929** [CocoaPods/CocoaPods#9797]
When I refer to the C + + files and framework and report the following errors, please help me to see what is the problem, thank you very much

**- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.**
    - NOTE  | [EChatIMLib/ProtobufEC] xcodebuild:  note: Using new build system
    - NOTE  | [EChatIMLib/ProtobufEC] xcodebuild:  note: Building targets in parallel
    - NOTE  | [EChatIMLib/ProtobufEC] xcodebuild:  note: Planning build
    - NOTE  | [EChatIMLib/ProtobufEC] xcodebuild:  note: Constructing build description
    - NOTE  | [EChatIMLib/ProtobufEC] xcodebuild:  warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.4.99. (in target 'Protobuf' from project 'Pods')
    - NOTE  | [EChatIMLib/ProtobufEC] xcodebuild:  warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'App' from project 'App')
    - NOTE  | [EChatIMLib/ProtobufEC] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    **- ERROR | [iOS] xcodebuild:  /Users/daweimac/Desktop/Git/EChatIMLib/EChatIMLib/Classes/Mars/PublicComponentV2/stn_callback.mm:24:25: error: allocating an object of abstract class type 'mars::stn::StnCallBack'**

## This is my podspec file compilation option

s.source_files = 'EChatIMLib/Classes/*.h', 'EChatIMLib/Classes/**/*.{h,m,cc,mm}'
  s.public_header_files = 'EChatIMLib/Classes/*.h', 'EChatIMLib/Classes/**/*.h'
  s.requires_arc = true
  s.subspec 'ProtobufEC' do |protobuf| 
    protobuf.source_files = 'EChatIMLib/Classes/ProtobufEC/*'
    protobuf.public_header_files = 'EChatIMLib/Classes/ProtobufEC/*.h'
    protobuf.requires_arc = false
  end
  s.frameworks = 'UIKit', 'Foundation', 'CoreTelephony', 'SystemConfiguration', 'CFNetwork'
  s.libraries = "resolv.9", "z"
  s.vendored_frameworks = 'Frameworks/mars.framework', 'Frameworks/Realm.framework'
  s.xcconfig = {'OTHER_LDFLAGS' => '-ObjC -lc++'
          'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
          'FRAMEWORK_SEARCH_PATHS' => '$(inherited) $(SRCROOT)',
          'HEADER_SEARCH_PATHS' =>'$(inherited) $(SRCROOT)',
          'ARCHS' => '$(inherited)',
          'VALID_ARCHS' =>valid_archs.join(' ')}
  s.pod_target_xcconfig = {
    "CLANG_ENABLE_OBJC_ARC" => true, 
    "CLANG_CXX_LANGUAGE_STANDARD" => "gnu++14",
    "GCC_C_LANGUAGE_STANDARD" => "gnu11",
    "CLANG_CXX_LIBRARY" => "libc++",
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
    'ENABLE_BITCODE' => false
  }
  s.dependency 'Protobuf', '~> 3.10.0'

## Files in error
stn_callback.h

#ifndef STNCALLBACK_h
#define STNCALLBACK_h
#import <mars/stn/stn_logic.h>
#import "NetworkService.h"
namespace mars {
    namespace stn {
class StnCallBack : public Callback {
private:
    StnCallBack() {}
    ~StnCallBack() {}
    StnCallBack(StnCallBack&);
    StnCallBack& operator = (StnCallBack&);
public:
    static StnCallBack* Instance();
    static void Release();
private:
    static StnCallBack* instance_;
};
    }
}
#endif /* STNCALLBACK_h */

stn_callback.mm
#include "stn_callback.h"
namespace mars {
    namespace stn {
StnCallBack* StnCallBack::instance_ = NULL;
StnCallBack* StnCallBack::Instance() {
    if(instance_ == NULL) {
        instance_ = new StnCallBack();
    }
    return instance_;
}  
void StnCallBack::Release() {
    delete instance_;
    instance_ = NULL;
}
    }
}

**Comment by dnkoutso** [comment]
This seems like a project setup error, not sure if its a CocoaPods one. Please update sample app.

**Comment by zdw19840929** [comment]
@dnkoutso Thank you very much. It's really the problem of the project. I have solved it.
