### ISSUE TITLE
CP 1.9 Can't install Swift pods with missing swift_version

### ISSUE THREAD

**Issue by bpoplauschi** [CocoaPods/CocoaPods#9799]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## CocoaPods Environment

- Our project uses Xcode 11.3.1, CocoaPods 1.7.2 and the [CocoaPods Rome plugin](https://github.com/CocoaPods/Rome)
- We have a few Swift pods that never had a `swift_version` set via their `podspec`. 
- Examples: [Locksmith version 4.0 - the last available version](https://github.com/matthewpalmer/Locksmith) or [AlamofireNetworkActivityIndicator v 2.4.0](https://github.com/Alamofire/AlamofireNetworkActivityIndicator)
- to avoid the Swift version missing error (`PODNAME does not specify a Swift version and none of the targets (MYTARGET) integrating it have the SWIFT_VERSION attribute set.`), we always (back to earlier versions) used the `pre_install` hook to set that `swift_version` for those pods
```
pre_install do |installer|
    installer.analysis_result.specifications.each do |s|
        if ['AlamofireNetworkActivityIndicator', 'Locksmith', ...].include?(s.name)
            s.swift_version = '5.0'
        end
    end
end
```

## What did you do?

- We tried upgrading CocoaPods to the latest version (`1.9.0` or `1.9.1`), but apparently the way `swift_version` setter works has changed (probably in version `8.0` where you added support for multiple swift versions), so we still get the error
`PODNAME does not specify a Swift version and none of the targets (MYTARGET) integrating it have the SWIFT_VERSION attribute set.`
- Because we use the Rome plugin, there is no Target to get the `SWIFT_VERSION` from and since the podspec is missing it, ... the error is justified
- Tried different things, but apparently setting `s.swift_version` or `s.swift_versions` has the same effect: the **`swift_versions`** property is populated
- At this point, I just wanted to ask you if there is any way we can use those pods in the environment I descried, like some way to set the `SWIFT_VERSION`

## What did you expect to happen?

Have a way to use Swift pods that don't have `swift_version` set in their `podspec` and without picking up `SWIFT_VERSION` from any target.

## What happened instead?

The error above...

## Project that demonstrates the issue

N/A

## Thank you CocoaPods team

I enjoy CocoaPods for so many years now, wanted to say thanks for building and maintaining it. Keep up the very nice work.

**Comment by dnkoutso** [comment]
Thanks for report! Yes probably that API changed I believe we had an issue around here that shows how to set the Swift version in 1.9.x....

In the meantime I need to re-dig and figure out how you can do this in 1.9.x.

**Comment by bpoplauschi** [comment]
@dnkoutso your response got me to search and find this issue #8653. Per your comment there
```
target 'XXX' do
  current_target_definition.swift_version = '5.0'
end
```
worked fine for me, setting `current_target_definition.swift_version` is sufficient for those pods missing their Swift version. Thanks for pointing me in the right direction.

**Comment by dnkoutso** [comment]
nice! thanks that was it
