### ISSUE TITLE
[1.9.2] Builds stuck at Running script '[CP] Prepare Artifacts'

### ISSUE THREAD

**Issue by rist** [CocoaPods/CocoaPods#9817]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm depending on a pod which uses xcframeworks but am still forced to use the legacy build systems for various reasons. Thankfully there have been some changes in cocoapods which allowed me to get that working.

I used some prerelease version and everything worked fine.

```
gem 'cocoapods', :git => 'https://github.com/CocoaPods/CocoaPods.git', :ref => '2b774aa58f1edc2c3b90b4f854577daf8a989ea0' 
gem 'cocoapods-core', :git => 'https://github.com/CocoaPods/Core.git', :ref => '8923c0cdca68d4bc7126cd64106a5fc1e9217ced'
gem 'xcodeproj', :git => 'https://github.com/CocoaPods/Xcodeproj.git', :ref => 'ed0558ecf5ae28464407269225565050a4d6e6f8'
gem 'cocoapods-keys', :git => 'https://github.com/orta/cocoapods-keys.git', :ref => '4ed63506b986960be1d1eea00e06420f67f940e4'

```

Now I tried to switch to Cocoapods 1.9.2 as I assume it would continue working but now my builds are again stuck at `Running script '[CP] Prepare Artifacts'`

One obvious issue is that with that prerelase I had this line in the xcconfig files `PODS_XCFRAMEWORKS_BUILD_DIR = $(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates` which disappeared

## What did you expect to happen?

To be able to build as I was able with that prelrease.

## What happened instead?

Builds stuck

### Stack

```
   CocoaPods : 1.9.2
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : beeone-cocoa-pods-specs - git - git@github.beeone.at:kyc/cocoa-pods-specs.git @ e1d31c0edde28dd80878f3172f64da14ba0891a8

               innovatrics - git - https://github.com/innovatrics/innovatrics-podspecs.git @ 7460030207ea55ce811b75448f12441a05d3eb47

               threatmark - git - https://jkaplicky:P%24r9fmK4Ux%23QFV@git.threatmark.com/dist/threatmark-podspecs.git @ ad11b2c48ae69c4723fe4e6cb01c61d8e9afebce

               threatmark-dist-threatmark-podspecs - git - https://git.threatmark.com/dist/threatmark-podspecs.git @ ad11b2c48ae69c4723fe4e6cb01c61d8e9afebce

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/rist/.gem/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.2
cocoapods-deintegrate  : 1.0.4
cocoapods-dependencies : 1.3.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.1.0
cocoapods-trunk        : 1.5.0
cocoapods-try          : 1.2.0
slather                : 2.4.8
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Can you try master branch?

**Comment by rist** [comment]
Hi, just tried on master and it works - so does 1.9.2 not include all xcframework related improvements?

**Comment by dnkoutso** [comment]
Nope 1.9.2 was a bug fix release. 1.10 will include it.

**Comment by rist** [comment]
ok, thanks, looking forward to 1.10

**Comment by ahmedAlmasri** [comment]
@dnkoutso 1.10 not released?

**Comment by luutruong** [comment]
Updated to 1.10 still have issues when running prepare artifacts. it's seem take forever to complete.

**Comment by kushalpal17** [comment]
I am also facing same issue. My Xcode version is 12.0.1, Cocoapods version is 1.9.3 and Mac OS version is 10.15.7

**Comment by raphaels17** [comment]
Same  My Xcode version is 12.2, Cocoapods version  1.10.0 and  macOS 11.0.1
