### ISSUE TITLE
Cannot specify some files private. `project_header_files` DSL support.

### ISSUE THREAD

**Issue by CrystalBlack** [CocoaPods/CocoaPods#9820]
# Report

I've already set `private_header_files` option, but i can still use these private files in my main project. 

## What did you do?

In `Podfile`, i set `use_frameworks! :linkage => :static` 
In `xx.podspec`, i set  `s.private_header_files = 'Pod/Classes/Public/*.h'`

## What did you expect to happen?

I wish I could specify some files which is public and others which is private. 

## What happened instead?

Whether I set `private_header_files` or `public_header_files`, i could use all of the files in the pod project.

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.3 (19D76)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.24.2 (Apple Git-127)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : aliyun - git - https://github.com/aliyun/aliyun-specs.git @ 4155941aefe348addab970471acaf038f7e65191

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 4fe665ac9b85ebae0aa08ab51590bd5c57e00209

               edu-git-cocoapods-specs - git - https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git @ c12bcbd77a15034b975ae0f48892cb18acf74345

               trunk - CDN - https://cdn.cocoapods.org/
               yintech-ytx-ios-ytx-pod-specs - git - http://gitlab.yintech.net/ytx-ios/ytx-pod-specs.git @ 991e99f8f3575e57197da192ca2d8763e36a7660

```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
install! 'cocoapods', :generate_multiple_pod_projects => true
use_frameworks! :linkage => :static

target 'FrameworkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for FrameworkDemo
  pod 'Q',:path => '/Users/yqp/Desktop/FrameworkDemo/Q'
end
```

**Comment by amorde** [comment]
> Whether I set private_header_files or public_header_files, i could use all of the files in the pod project.

Could you expand on this a bit? `private_header_files` will mark the headers as private in Xcode within the target membership. Is that not happening?

**Comment by dnkoutso** [comment]
I think what they mean is that they can still access private headers even though they have been marked as private.

**Comment by paulb777** [comment]
In Xcode and CocoaPods, "private" headers are still accessible by name to clients. Unlike "public" headers they are not available via the module import. Use "internal" to restrict header access to the enclosing library.

**Comment by amorde** [comment]
Yeah sounds like maybe you’re looking to use Project headers

**Comment by dnkoutso** [comment]
do we have support for Project headers?

**Comment by CrystalBlack** [comment]
> > Whether I set private_header_files or public_header_files, i could use all of the files in the pod project.
> 
> Could you expand on this a bit? `private_header_files` will mark the headers as private in Xcode within the target membership. Is that not happening?

**Comment by CrystalBlack** [comment]
> I think what they mean is that they can still access private headers even though they have been marked as private.

Yes. 
If i marked some files as `public_header_files `,  other files could be accessed in project. 
If i marked some files as `private_header_files `,  these files still could be accessed in project.
Seemingly, I couldn't  control the header file.
In Xcode, i could set `Build Phases` -> `Header` and config default file (Xcode create framework auto generate an xx.h header file) with `#import <frameworkName/target header.h>`. Use this way, i could control headers.

so, how should i do to control pod public headers?

**Comment by CrystalBlack** [comment]
I found that `module.modulemap` will declare `umbrella header "xxxx-umbrella.h"`, and "xxxx-umbrella.h" will import all of the header file.

**Comment by dnkoutso** [comment]
You can supply your own modulemap file `s.module_map`.

**Comment by CrystalBlack** [comment]
I have tried it.
I used own `xxx.modulemap` file and own `xxx-umbrella.h`. If i used `@import xxx`, it worked.

But if i used `@import <xxx/xxx.h>`, i still access private headers. 

Because in the framework, `Headers` folder include `xxx-umbrella.h` and all header files.

**Comment by CrystalBlack** [comment]
> Yeah sounds like maybe you’re looking to use Project headers

Yes. 

I want to control the use of header file.

Do you consider support this feature?

**Comment by CrystalBlack** [comment]
> In Xcode and CocoaPods, "private" headers are still accessible by name to clients. Unlike "public" headers they are not available via the module import. Use "internal" to restrict header access to the enclosing library.

How to use  "internal"?

**Comment by paulb777** [comment]
Headers that are only specified in the `source_files` attribute are not accessible to pod clients.

Here's an example of all three: https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCore.podspec#L28

**Comment by amorde** [comment]
Unfortunately that's only true if you also specify `public_header_files` - by default if only `source_files` is specified they are all public.

We should probably have a `project_header_files` DSL as this has come up before

**Comment by CrystalBlack** [comment]
> Unfortunately that's only true if you also specify `public_header_files` - by default if only `source_files` is specified they are all public.
> 
> We should probably have a `project_header_files` DSL as this has come up before

Yes, i think so.
I think `project_header_files` DSL  is necessary. We should manage the permissions of the source files.
In the future, could you consider supporting this feature?

**Comment by CrystalBlack** [comment]
> Headers that are only specified in the `source_files` attribute are not accessible to pod clients.
> 
> Here's an example of all three: https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseCore.podspec#L28

It could work.Thank you~

**Comment by dnkoutso** [comment]
actually re-opening this for `project_header_files` support DSL.
