### ISSUE TITLE
Drop support for Ruby 2.0 

### ISSUE THREAD

**Issue by amorde** [CocoaPods/CocoaPods#9821]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

macOS 10.13.3 (High Sierra) ships Ruby 2.3.3, and this is the required OS version for Xcode 10. Since we typically support [current Xcode] and [previous Xcode], this is safe to drop.

This is a prerequisite for https://github.com/CocoaPods/CocoaPods/issues/9404, which also unblocks dependabot support https://github.com/dependabot/dependabot-core/pull/731

**Comment by igor-makarov** [comment]
I agree. I just had the same thing in https://github.com/igor-makarov/xcake/pull/211 and the reason I had to give it up is because it caused a dependency conflict wit CP.
