### ISSUE TITLE
pod trunk push validation always unsuccessfully

### ISSUE THREAD

**Issue by yoklmnprst** [CocoaPods/CocoaPods#9823]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# It is impossible to do `pod trunk push` for project with updated dependency.

## What did you do?

ℹ `pod trunk push VoxImplant.podspec`

## What did you expect to happen?

ℹ pod trunk pushed successfully. 

## What happened instead?

ℹ VoxImplant.podspec contains dependency to subspec VoximplantWebRTC. VoxImplantWebRTC has successfully trunk pushed (https://github.com/CocoaPods/Specs/blob/master/Specs/d/c/f/VoxImplantWebRTC/78.3.0/VoxImplantWebRTC.podspec.json). But VoxImplant.podspec validation failed with error. 
```
Validating podspec
 -> VoxImplantSDK (2.32.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (CocoaPods could not find compatible versions for pod "VoxImplantWebRTC":
  In Podfile:
    VoxImplantSDK (from `/Users/jobs/Downloads/artifacts/VoxImplantSDK.podspec`) was resolved to 2.32.0, which depends on
      VoxImplantSDK/Core (= 2.32.0) was resolved to 2.32.0, which depends on
        VoxImplantWebRTC (= 78.3.0)
```
`pod repo update` doesn't help.

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.21.1 (Apple Git-122.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ de8e1c4559e53fd3611e06efe2e4612347e2d1a2

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment]
Did you run `--repo-update` or use `--synchronous` flag?

**Comment by paulb777** [comment]
Update to cocoapods-trunk 1.5.0 and use `--synchronous`

**Comment by dnkoutso** [comment]
Closing pre-emptively but I will re-open if we find a bug.

**Comment by dnkoutso** [comment]
https://github.com/CocoaPods/cocoapods-trunk/pull/147

**Comment by yoklmnprst** [comment]
Thank you, `--synchronous` option really helps.
