### ISSUE TITLE
Need help when build to IOS. Pod install "UnityFramework"

### ISSUE THREAD

**Issue by QuanHuynhM** [CocoaPods/CocoaPods#9825]
When I build IOS with Unity 2019.3, I look at the pod file, I see the difference is: target 'UnityFramework' instead of 'Unity-Iphone'.
I still try to build it but when I use 'pod install' I get the following message:

[!] The Podfile contains framework or static library targets (UnityFramework), for which the Podfile does not contain host targets (targets which embed the framework). If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).

Will it affect my project? What can I do to not display this message?

target 'UnityFramework' do
pod 'Crashlytics'
pod 'Fabric'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/RemoteConfig'
end

**Comment by dnkoutso** [comment]
You cannot disable this message right now.

The message basically tells you that your project only has a library target `UnityFramework` which is not embedded in any bundle (app or test etc).

**Comment by dnkoutso** [comment]
Going to close for now we can re-open if we can see an enhancement or bug.

**Comment by seanreinhardtapps** [comment]
This looks like a podfile generated by the External Dependency Manager for Unity (https://github.com/googlesamples/unity-jar-resolver).  They have released a lot of patches recently in support of Unity 2019.3, you could check if there's an update available, and possibly leave an issue there if the project doesn't build correctly.
