### ISSUE TITLE
[Trunk specs repo] all_pods_versions_4_e_0.txt is not updated

### ISSUE THREAD

**Issue by ElfSundae** [CocoaPods/CocoaPods#9826]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
```
pod 'NIMSDK_LITE'
```

`pod update`

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  

`NIMSDK_LITE` 7.7.0 should be installed.

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  

The Trunk specs repo's index file `all_pods_versions_4_e_0.txt` did not update.

There is a `7.7.0` version of NIMSDK_LITE: https://github.com/CocoaPods/Specs/tree/master/Specs/4/e/0/NIMSDK_LITE/7.7.0 but the index file https://cdn.cocoapods.org/all_pods_versions_4_e_0.txt does not contain this version.

Same issue with `NIMSDK` https://github.com/CocoaPods/Specs/tree/master/Specs/4/c/9/NIMSDK/7.7.0
https://cdn.cocoapods.org/all_pods_versions_4_c_9.txt

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.

1.9.2

**Comment by Varnius** [comment]
Having same issue with https://cdn.cocoapods.org/all_pods_versions_9_2_5.txt

**Comment by eddyfrank** [comment]
Confirm. We have similar issue getting the latest version of our pod published on 2020-05-28.
Latest version is listed via `pod trunk info ...`, but is not available for installation via `pod install --repo-update`. Also reproducible with your pod `NIMSDK_LITE` v7.7.0, @ElfSundae .

Seems like an issue with the CDN trunk repo (https://cdn.cocoapods.org/)??

**Comment by ElfSundae** [comment]
@eddyfrank Yes it is a CDN trunk related issue, `all_pods_versions_x_x_x.txt` files are index files.

A temporal workaround: edit the local `all_pods_versions_x_x_x.txt` and append the new versions, for example:
```console
$ md5 -s NIMSDK_LITE                               
MD5 ("NIMSDK_LITE") = 4e048e67573453a1bd6f8eaf8f3b02e6
$ vim ~/.cocoapods/repos/trunk/all_pods_versions_4_e_0.txt
```
append `/7.7.0` at the end of `NIMSDK_LITE/2.7.0/2.7.1/...` line, then run `pod update` on your project directory.

**Comment by eddyfrank** [comment]
Thanks for the workaround, @ElfSundae .
I just used your pod to test and confirm that there is a **general issue on cdn.cocoapods.org with indexing latest pods** :-( . Same for our pod `ScanbotBarcodeScannerSDK` - version 1.5.0 is missing in https://cdn.cocoapods.org/all_pods_versions_3_4_f.txt .

**Comment by canberksinangil** [comment]
https://github.com/CocoaPods/CocoaPods/issues/9827

**Comment by mitchross** [comment]
https://cdn.cocoapods.org/all_pods_versions_b_f_7.txt same issue

**Comment by amorde** [comment]
I believe this is fixed now - our last successful deploy was 14 minutes ago which includes everything that was missing during this time. Will leave open for now in case there are more issues but would appreciate a few folks trying again now to see if it's working for them

**Comment by amorde** [comment]
Another deploy just went through from a pod getting pushed 🎉

**Comment by mitchross** [comment]
Confirming fixed for me also

**Comment by dnkoutso** [comment]
Closing for now. We will keep monitoring the situation.

**Comment by LorDisturbia** [comment]
This issue is still ongoing for me. I just pushed [Tempura](https://cocoapods.org/pods/Tempura) version 6.0.0. 

If I run `pod trunk info Tempura` I get

```
Tempura
    - Versions:
      - 1.10.0 (2018-06-13 12:46:11 UTC)
      - 1.11.0 (2018-06-28 10:30:23 UTC)
      - 1.12.0 (2018-07-02 11:03:37 UTC)
      - 1.4.0 (2018-02-28 16:01:52 UTC)
      - 1.5.0 (2018-04-17 11:28:51 UTC)
      - 1.6.0 (2018-05-03 08:04:36 UTC)
      - 1.6.1 (2018-05-03 14:11:33 UTC)
      - 1.6.2 (2018-05-03 14:57:20 UTC)
      - 1.7.0 (2018-05-08 08:10:26 UTC)
      - 1.7.1 (2018-05-10 12:38:33 UTC)
      - 1.7.2 (2018-05-25 13:42:55 UTC)
      - 1.8.0 (2018-05-30 09:22:57 UTC)
      - 1.8.1 (2018-06-01 09:24:50 UTC)
      - 1.8.2 (2018-06-05 12:12:33 UTC)
      - 1.9.0 (2018-06-12 08:19:28 UTC)
      - 2.0.0 (2018-09-19 13:42:23 UTC)
      - 2.1.0 (2018-10-26 09:58:53 UTC)
      - 3.0.0 (2019-01-04 10:10:57 UTC)
      - 3.0.1 (2019-01-08 10:33:07 UTC)
      - 4.0.0 (2019-03-27 15:24:59 UTC)
      - 4.0.1 (2019-04-01 16:01:08 UTC)
      - 4.1.1 (2019-07-17 07:58:13 UTC)
      - 4.1.2 (2019-09-25 14:15:26 UTC)
      - 4.1.3 (2019-11-21 07:46:13 UTC)
      - 4.2.0 (2019-11-25 10:39:25 UTC)
      - 4.3.0 (2019-12-06 13:48:37 UTC)
      - 4.3.1 (2020-03-23 16:59:57 UTC)
      - 4.4.0 (2020-05-06 12:27:11 UTC)
      - 5.0.0 (2020-07-31 10:27:12 UTC)
      - 5.1.0 (2020-09-10 09:21:31 UTC)
      - 6.0.0 (2020-10-28 09:12:45 UTC)
    - Owners:
      - Bending Spoons <opensource@bendingspoons.com>
```

But I can't find it in pod install, regardless of how many times I run `pod repo update`

**Comment by igor-makarov** [comment]
@LorDisturbia I'm seeing Tempura in the index - https://cdn.cocoapods.org/all_pods_versions_3_5_b.txt 

```
Appcues/0.10.0/0.11.0/0.11.1/0.11.3/0.12.0/0.12.1/0.13.0/0.13.1/0.13.2/0.13.3/0.13.4/0.13.5/0.13.6/0.14.0/0.14.1/0.14.2/0.15.0/0.16.0/0.16.1/0.16.2/0.17.0/0.17.1/0.17.2/0.17.3/0.17.4/0.18.0/0.18.1/0.18.2/0.18.3/0.18.4/0.18.5/0.18.6/0.19.0/0.19.1/0.19.2/0.20.0/0.21.0/0.22.0/0.23.0/0.23.1/0.23.2/0.6.0/0.6.1/0.6.2/0.6.3/0.6.4/0.7.0/0.7.1/0.8.0/0.9.0/1.0.0
CircuitBreaker/0.1.0
GPXParser/1.0
ISO8601/0.0.1/0.1.0/0.1.1/0.1.2/0.1.3/0.2.0/0.3.0/0.5.0/0.5.1/0.5.2/0.6.0
KHSegmented/0.1.1/0.1.2
Navajo-Swift/0.0.2/0.0.3/0.0.4/0.0.5/0.0.6/0.1.0/0.2.0/1.0.0/2.0.0/2.1.0
SeanTrySynchronousPosterGetter/0.1.0/0.2.0/0.3.0
SundeedQLite/1.0.0/1.0.1/1.0.2/1.0.3/1.0.4/1.0.5/1.0.6/1.0.7/1.0.8/1.0.9/1.1.1/1.1.2/1.1.4/1.1.5
Tempura/1.10.0/1.11.0/1.12.0/1.4.0/1.5.0/1.6.0/1.6.1/1.6.2/1.7.0/1.7.1/1.7.2/1.8.0/1.8.1/1.8.2/1.9.0/2.0.0/2.1.0/3.0.0/3.0.1/4.0.0/4.0.1/4.1.1/4.1.2/4.1.3/4.2.0/4.3.0/4.3.1/4.4.0/5.0.0/5.1.0/6.0.0
UIColor+InputMethods/1.0.3/1.0.4/1.0.5/1.0.6
UPMenu/0.1.0/0.2.0
WKSimpleBridge/0.0.1/0.0.2/0.0.3
YCAlert/1.0.0/1.1.0/1.2.0
YLShare/1.1/1.2
YYControl/1.0.0/1.0.1/1.0.2/1.0.3/1.0.4/2.0
```
