### ISSUE TITLE
Recent Pods are not indexed. We cannot update / download latest pods.

### ISSUE THREAD

**Issue by canberksinangil** [CocoaPods/CocoaPods#9827]
**Recent pods are not indexed. Because of that we cannot update the pods. I have tried many libraries with different computers. Results are the same.**

https://github.com/CocoaPods/Specs/commits/master

* [YES] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod repo update`
```
Updating spec repo cocoapods
Updating spec repo trunk
```
Run `pod update`

## What did you expect to happen?

Install the pod dependency correctly with the latest version or specified version. 

## What happened instead?
 
Latest version or specified latest version didn't install even after 16 hours.
https://github.com/CocoaPods/Specs/commit/cacd82baaa2d758d607262a24d15ae57843ce523

```
[!] CocoaPods could not find compatible versions for pod "InsiderMobile":
  In Podfile:
    InsiderMobile (= 10.3.0)

None of your spec sources contain a spec satisfying the dependency: `InsiderMobile (= 10.3.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.`
```
### Stack

```
   CocoaPods : 1.9.2
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.3 (11C29)
         Git : git version 2.26.0
Ruby lib dir : /Users/canberk/.rvm/rubies/ruby-2.6.5/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 526150c47b473a21e793570af7557303f5f3ff7d

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/canberk/.rvm/rubies/ruby-2.6.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by mitchross** [comment]
Same issue here

**Comment by paulb777** [comment]
Workaround is adding `source 'https://github.com/CocoaPods/Specs.git'` to the Podfile. See also https://stackoverflow.com/questions/62071323/pod-update-will-not-update-to-latest-version-of-pod-no-matter-what-i-do/62072745#62072745

**Comment by dnkoutso** [comment]
Yes we are receiving such reports. An issue was filed here so I am grouping them #9826
