### ISSUE TITLE
My pods are uploaded but users are unable to update them

### ISSUE THREAD

**Issue by Arohi-Magotra** [CocoaPods/CocoaPods#9828]
I ran command 'pod repo update' followed by 'pod update', but i m unable to update the pods.
Please help

**Comment by mitchross** [comment]
I have this same issue

**Comment by lingol** [comment]
Same here. I have pushed my lib MMKVCore with new version v1.1.2. Yet the CDN digest not updated. https://cdn.cocoapods.org/all_pods_versions_b_d_5.txt
>BetterBaseControllers/1.0.0/1.0.1/1.0.2
>CAFVuMeter/0.1.0
>KMOnlineWeb/0.1.0/0.1.1/0.1.2/0.1.3/0.1.4/0.1.5
>LightDependency/1.0.0/1.0.1/2.0-beta1
>MMKVCore/1.1.0/1.1.1
>NetworkMediator/0.1.1/0.1.2/0.1.3
>ObjectEncoder/0.2.0
>PPVideoImage/0.1.0/0.1.1
>PZNetworkLayer/0.0.1/0.0.2/0.0.3/0.0.4/0.0.5/0.0.6/0.0.7/0.0.8/0.0.9
>ResourceManager-smorel/1.2.0
>RobFantasticView/0.6.0/0.7.0/0.8.0
>SwiftCheckboxDialog/0.1.0/0.1.1/1.0.0/1.0.1
>XMExpandableTableView/0.1.0
>ZhiziyunMobileAds/1.0.0/1.0.1/1.0.2/1.0.3
>IBarChart/0.1/0.2
>iosvoronoi/0.1.0/0.1.3
>keylime/0.0.1
>sureBellFramework-iOS/0.1.0

**Comment by canberksinangil** [comment]
https://github.com/CocoaPods/CocoaPods/issues/9827

**Comment by dnkoutso** [comment]
Yes we are receiving such reports. An issue was filed here so I am grouping them https://github.com/CocoaPods/CocoaPods/issues/9826
