### ISSUE TITLE
pod install not working after updating macOS to Catalina & Xcode 11.5

### ISSUE THREAD

**Issue by AndrewFakher** [CocoaPods/CocoaPods#9830]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

upgrading to the latest ruby gems and tried some stackoverflow solutions but still have the same error

# Report

## What did you do?

ℹ Run `pod install`

## What did you expect to happen?

ℹ Install all pod dependencies correctly

## What happened instead?

ℹ   I got this error

### Error
`-bash: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby: bad interpreter: No such file or directory`

**Comment by dnkoutso** [comment]
This does not seem a CocoaPods related issue rather than something with your environment.

I recommend asking on StackOverflow instead. Sorry but as it is this does not appear a CocoaPods library issue.

**Comment by AndrewFakher** [comment]
Solved using homebrew:
- brew install cocoapods --build-from-source
- then: brew link --overwrite cocoapods

**Comment by Liqiankun** [comment]
@AndrewFakher I got same, I gonna give this a shot.
