### ISSUE TITLE
Unable to upgrade past version 1.9.1 in macOS Catalina

### ISSUE THREAD

**Issue by nimeshneema** [CocoaPods/CocoaPods#9831]
[cocoapods.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cocoapods.rb) in Homebrew Core still points to version 1.9.1 while two more [public releases](https://github.com/CocoaPods/CocoaPods/releases) have been made.

Please update the spec in Homebrew to enable the installation of the newer versions of CocoaPods.

**Comment by dnkoutso** [comment]
CocoaPods maintainers/contributors do not maintain or update that. In the past it has happened by others outside of CocoaPods.

**Comment by Vanson** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew

**Comment by dnkoutso** [comment]
Here's 1.9.2 PR https://github.com/Homebrew/homebrew-core/pull/55148 been worked on.

**Comment by nimeshneema** [comment]
@dnkoutso Thanks for the update.
