### ISSUE TITLE
pod lib lint not working as excepted

### ISSUE THREAD

**Issue by ivemmy** [CocoaPods/CocoaPods#9832]
# Report

## What did you do?

Run 'pod lib lint'

## What did you expect to happen?

Pass verification when .podspec is written correctly

## What happened instead?

In our project, there are several subspecs and there are dependencies between them. And the lint fails because it can find the dependency subspec. And I run again with the `--no-clean` option and find the pod of test project only contains a subspec

In order to verify whether it is a problem of our project, I wrote a demo, which .podspec is shown below, the same as the [official website](https://guides.cocoapods.org/syntax/podspec.html#subspec)

```
  spec.subspec 'Twitter' do |sp|
    sp.source_files = 'Classes/Twitter'
  end

  spec.subspec 'Pinboard' do |sp|
    sp.source_files = 'Classes/Pinboard'
  end
```

and run the command 

```
pod lib lint --no-clean
```

it passes because there are no dependencies between them, however, the workspace for inspection only contains the Pinboard subspec

![image](https://user-images.githubusercontent.com/32251035/83370038-c2914400-a3f0-11ea-9b88-bac43b80c3a8.png)

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/zhouxuan/.rvm/rubies/ruby-2.6.3/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ cff98795159ab3be75cf398329172c3226fe77f0

               FlamingoUI - git - http://git.code.oa.com/FlamingoUI/FlamingoUI.git @ 449cd1593b274db53f5a15ff625b43524b2aeacb

               oa-emmyzhou-flamingoui - git - http://git.code.oa.com/emmyzhou/FlamingoUI.git @ 449cd1593b274db53f5a15ff625b43524b2aeacb

               oa-falco-ios-specs - git - http://git.code.oa.com/falco-iOS/Specs.git @ b9259d2222ebd61dc0af3b5c6ce0736f8cfe1b7d

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/zhouxuan/.rvm/gems/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.2.0
```

## Project that demonstrates the issue

https://github.com/ivemmy/TestLint

**Comment by dnkoutso** [comment]
Did you use `--subspecs` during the `lint` invocation?

**Comment by ivemmy** [comment]
No, I just run `pod lib lint --no-clean` without any other options

**Comment by dnkoutso** [comment]
Can you try?

**Comment by ivemmy** [comment]
I have tried and it still only contains the Pinboard subspec

**Comment by dnkoutso** [comment]
I do not understand the issue here. I ran `pod lib lint` and it worked.

```
TestLint passed validation.
```

Need more complete instructions on the issue you are seeing here.
