### ISSUE TITLE
Trunk repo should be added before pushing private podspec repo

### ISSUE THREAD

**Issue by ElfSundae** [CocoaPods/CocoaPods#9833]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a private podspec that depends on some third libraries published in the Trunk spec repo. When running `pod repo push private-repo`, it shows error `Unable to find a specification`.

## What did you expect to happen?

The Trunk repo should be automatically added if it does not exist before validating spec file, like `pod lib lint` does.

Additionally, I tried to add the Trunk repo manually:

```console
$ pod repo add trunk https://cdn.cocoapods.org/
[!] Repo name `trunk` is reserved for CocoaPods' main spec repo accessed via CDN.
```

## CocoaPods Environment

1.9.3

## Project that demonstrates the issue

Demo project: https://github.com/ElfSundae/PushPrivatePodSpecsRepoTest

Error log: https://github.com/ElfSundae/PushPrivatePodSpecsRepoTest/runs/726134793?check_suite_focus=true

**Comment by dnkoutso** [comment]
I think we can add this to `pod setup`.

**Comment by ElfSundae** [comment]
Currently `pod setup` does not add the trunk repo: https://github.com/ElfSundae/PushPrivatePodSpecsRepoTest/runs/726398314?check_suite_focus=true

Maybe `pod setup` should add, in my opinion `pod repo push` also should add the trunk repo.

**Comment by dnkoutso** [comment]
PRs welcome for `pod setup` to do it! When we did CDN `pod setup` became noop.

**Comment by ElfSundae** [comment]
I can not write Ruby code 😭  I will try later.

**Comment by ElfSundae** [comment]
PR created #9840
