### ISSUE TITLE
I encountered the CDN problem in the process of using "pod trunk push -- skip import validation -- allow warnings".

### ISSUE THREAD

**Issue by kinsunlu** [CocoaPods/CocoaPods#9836]
I encountered the CDN problem in the process of using "pod trunk push -- skip import validation -- allow warnings". All the solutions I found were to replace the source, but I couldn't replace the CDN source with "pod trunk push". I hope to solve my problem

""
kinsun@KinsundeMacBook-Pro DNAdSDK % pod trunk push --skip-import-validation --allow-warnings

[!] Found podspec `DNAdSDK.podspec`
Updating spec repo `trunk`
Validating podspec
 -> DNAdSDK (5.1)
    - WARN  | attributes: Missing required attribute `license`.
    - WARN  | license: Missing license type.
    - WARN  | description: The description is equal to the summary.
    - ERROR | [iOS] unknown: Encountered an unknown error (CDN: trunk Repo update failed - 22 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/1.9.8.2/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/1.9.8.5/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/1.9.9.2/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/1.9.9.3/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/1.9.9.5/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.0.1.1/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.0.1.2/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.1.0.1/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.1.0.2/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.2.0.2/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.3.0.3/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.3.1.0/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.4.6.3/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.4.6.7/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.5.1.2/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.5.1.5/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.7.5.2/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.8.0.1/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.9.0.1/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.9.0.7/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.9.5.6/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/9/2/6/Bytedance-UnionAD/2.9.5.8/Bytedance-UnionAD.podspec.json Response: SSL peer certificate or SSH remote key was not OK) during validation.

[!] The spec did not pass validation, due to 1 error.

""

**Comment by TsnumiDC** [comment]
I have the same problem, today

**Comment by cubegao** [comment]
I have the same problem

**Comment by dnkoutso** [comment]
We are investigating a bit.In the meantime I am consolidating reports here https://github.com/CocoaPods/CocoaPods/issues/9834.

You can also use `git` based repo instead by adding it to your `Podfile`.

**Comment by kinsunlu** [comment]
> We are investigating a bit.In the meantime I am consolidating reports here #9834.
> 
> You can also use `git` based repo instead by adding it to your `Podfile`.

But my problem can't be fixed by modifying "podfile", because I want to push my project to cocoapods. It can't be modified to git source, but I only use the trunk of CDN. I don't have any way now, nor can I solve it by using 《United States VPN》 .

**Comment by dnkoutso** [comment]
You can still add the git repo `pod repo add` and then during `trunk` or `pod repo push` pass `--sources`.
