### ISSUE TITLE
Whither release notes?

### ISSUE THREAD

**Issue by skydivedan** [CocoaPods/CocoaPods#9838]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Noticed that there was a new release of Cocoapods, and checked the release notes.

## What did you expect to happen?

I expected to see changes to cocoapods in the release. 

## What happened instead?

I saw "None" for both "Bug Fixes" and "Enhancements". Also, so this in the prior release for 1.9.2 of Cocoapods.

**Comment by dnkoutso** [comment]
The fixes and changelog are in CocoaPods/Core gem. https://github.com/CocoaPods/Core/releases
