### ISSUE TITLE
Swift Compiler Error Cannot load underlying module for... 

### ISSUE THREAD

**Issue by echyone** [CocoaPods/CocoaPods#9839]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expect to happen?

Install pods and configure project correctly

## What happened instead?

Pods were installed but app using framework target will not compile.

We have a Swift/Objective C project to generate a framework fro public distribution. The project imports several Swift only internally produced libraries using Cocoapods. Our framework project compiles and works in Objective C files in an app. However, importing the framework into a Swift file results in a compile error that a library cannot be loaded.

This sample demonstrates the problem. We must use use_modular_headers! so that we dont't have to distriibute and expose API's for the private libraries we use in the framework. In Test.swift commenting out import sample will allow the app to compile and run. ViewController is able to import and use both the Swift and Objective C classes and methods in the framework.

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E266)
       Xcode : 11.3.1 (11C504)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : garmin-mobile-ios-cocoapods-private-specs - git - ssh://gerrit.consumer.garmin.com:29418/mobile/ios/cocoapods-private-specs @ f9aabdf4b072bfcfa39137738422dd7c91cf88b7

               master - git - https://github.com/CocoaPods/Specs.git @ 78e5ee4a289197638ad054b116d5a9112b3fcc1a

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.9.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source "https://github.com/CocoaPods/Specs.git"


platform :ios, "11.0"
use_modular_headers!
#use_frameworks!


target "sample" do
    pod 'SwiftyJSON', '~> 4.0'
end
```

## Project that demonstrates the issue

https://github.com/echyone/sample

**Comment by echyone** [comment]
Has anyone looked at this? Are you saying it isn't a CocoaPods bug? Any feedback would be great.

**Comment by dnkoutso** [comment]
We havent had time to look at this. Any help appreciated from others or from you if you can dig in.

**Comment by dnkoutso** [comment]
This seems to be working for me on Xcode 12.1 and cocoapods 1.10.1.

**Comment by xn1924** [comment]
I met the same issue,could you show me how to figure it out ?@echyone
