### ISSUE TITLE
Unit test in a dynamic framework fails to run because could not find the pods referenced by another library

### ISSUE THREAD

**Issue by CaioSanchez** [CocoaPods/CocoaPods#9841]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
 Run dynamic framework (ModuleA) unit test bundle that depends on other dynamic framework (ModuleB) that references pods.

## What did you expect to happen?
Runs tests

## What happened instead?

- The bundle “ModuleATests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.

-(dlopen_preflight(/Users/caio/Library/Developer/Xcode/DerivedData/BugDemo-bufyebcspignpjddejxjmtjeuuvt/Build/Products/Debug-iphonesimulator/ModuleATests.xctest/ModuleATests): Library not loaded: @rpath/RxSwift.framework/RxSwift
  Referenced from: /Users/caio/Library/Developer/Xcode/DerivedData/BugDemo-bufyebcspignpjddejxjmtjeuuvt/Build/Products/Debug-iphonesimulator/ModuleB.framework/ModuleB
  Reason: image not found)

Program ended with exit code: 9
### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 48fc43349f0f54af6cfb06486ccce7c46206b6aa

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.0'
use_frameworks!

workspace 'BugDemo'

def module_B_pods
  pod 'RxSwift'
end

target 'ModuleA' do
  project 'ModuleA/ModuleA'
  
  target 'ModuleATests' do
  end
end

target 'ModuleB' do
  project 'ModuleB/ModuleB'
  module_B_pods
  
  target 'ModuleBTests' do
  end
end

target 'BugDemo' do
  # Pods for BugDemo
  module_B_pods

  target 'BugDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

## Project that demonstrates the issue
[BugDemo.zip](https://github.com/CocoaPods/CocoaPods/files/4717256/BugDemo.zip)

**Comment by dnkoutso** [comment]
You are using dynamic frameworks across the project. This means RxSwift wont be actually linked into ModuleB.framework and once you link ModuleB.framework into ModuleA.framework it will only keep track of the usage of RxSwift.

Something must copy RxSwift.framework into the unit test bundle so it can be dynamically loaded.

This worked for me:
```ruby
platform :ios, '11.0'
use_frameworks!

workspace 'BugDemo'

def module_B_pods
  pod 'RxSwift'
end

target 'ModuleB' do
  project 'ModuleB/ModuleB'
  module_B_pods
  
  target 'ModuleBTests' do
  end

  target 'ModuleA' do
    project 'ModuleA/ModuleA'
  
    target 'ModuleATests' do
    end
  end  
end

target 'BugDemo' do
  # Pods for BugDemo
  module_B_pods

  target 'BugDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

The alternative workaround is to enable static linking, which. also worked for me:

```
platform :ios, '11.0'
use_frameworks!(:linkage => :static)

workspace 'BugDemo'

def module_B_pods
  pod 'RxSwift'
end

target 'ModuleA' do
  project 'ModuleA/ModuleA'
  
  target 'ModuleATests' do
  end
end

target 'ModuleB' do
  project 'ModuleB/ModuleB'
  module_B_pods
  
  target 'ModuleBTests' do
  end
end

target 'BugDemo' do
  # Pods for BugDemo
  module_B_pods

  target 'BugDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

And add an empty `.swift` file into ModuleB since now RxSwift will be linked into it.

ModuleA/Tests successfully ran for me with either of the two options above.

Going to preemptively close and re-open as we discuss further
