### ISSUE TITLE
How to declare .swiftmodule and .swiftinterface when using Swift Static Library ? 

### ISSUE THREAD

**Issue by SketchK** [CocoaPods/CocoaPods#9845]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I want to use the binary static library(like .a not .framework) for my app. when I finish the job, I find that I can't get the interface of my pod, I think I should tell the podspec where is the file like .swiftmodule or .swiftinterface

## What did you expect to happen?

Let me introduce my pipeline

SoucrcePod -> StaticLibary -> BinaryLibraryPod -> AnotherHostApp

Step 1:  Source Pod is the source file of my code
Step 2: StaticLibrary is a demo project to produce source pod’s binary
Step 3: Binary LibraryPod is a filegroup to store my Step 2's result, like libSourcePod.a, SourcePod.modulemap, xxx.h and .swiftmodule, etc
Step 4: AnotherHostApp consume Binary LibraryPod like a pod

Now, I can use some API  in my objc file through the SourcePod-Swift.h 
I also hope that I can use these API in my swift file

## What happened instead?

when I import SourcePod Module, Nothing happened, 
and Xcode gives the feedback  "Module 'SourcePod' not found"

I think I should write something in my podspec, but I don't find any place to declare .swiftmodule or .swiftinterface, and modulemap also do not work 

### Stack

```
   CocoaPods : 1.9.2
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.5 (19F96)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/sketchk/.rvm/rubies/ruby-2.6.5/lib
Repositories : my-specs - git - /Users/sketchk/MySpecs.git @ 5ff09fbb580798de9243d48258eaf58512f519f2

               sankuai-binaryspecs - git - ssh://git@git.sankuai.com/ios/binaryspecs.git @ 8fa0fcb15e04bcc9bade95e3ce9af071a40e6392

               sankuai-specs - git - ssh://git@git.sankuai.com/ios/specs.git @ 7cc5662d50a3ada0213cdd7762da3817085dc428

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/sketchk/.rvm/gems/ruby-2.6.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AnotherHostApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SourcePod', :path => '~/Desktop/BinaryLibraryPod'
end
```

## Project that demonstrates the issue

Here is the demo: [https://github.com/SketchK/SwiftBinaryLibraryDemo](https://github.com/SketchK/SwiftBinaryLibraryDemo)

**Comment by dnkoutso** [comment]
I dont think you set `.swiftmodule` or `.swiftinterface` manually. At least for `.swiftmodule` those are  in binary format.

Have you tried `use_modular_headers!` in your Podfile?

**Comment by jsxyjGithub** [comment]
use swift include path for .swiftmodule
