### ISSUE TITLE
Custom pod's configuration for using token from target project to feed it into sub dependency

### ISSUE THREAD

**Issue by GUIEEN** [CocoaPods/CocoaPods#9848]
-   [x] I've read and understood the [_CONTRIBUTING_ guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Question

I'm making a custom pod to use it on my project and this custom pod requires sub dependency library, let's call it **Pod_A**.

Problem is that this **Pod_A** requires `access_token` that should be listed on info.plist file of xcode project.

What I want to achieve is that,
1. ~~Get access_token value listed at info.plist from xcode project that using custom pod~~
2. Then internally custom pod use that access_token value as a **Pod_A**'s requirement

I know how to get the access_token value from xcode project that using custom pod, 
but not sure how to feed this value to **Pod_A**
> **Pod_A** requires `access_token` that should be listed on info.plist file of xcode project.

maybe this question could be changed like 
How to add info.plist having `access_token` on custom pod and use `access_token` for its sub dependency pod ?
and what is the right way for doing this ?

Is there any suggestions to make this work ?
Any help would be appreciated.

## CocoaPods Environment

CocoaPods : 1.9.1

**Comment by dnkoutso** [comment]
You can most likely accomplish this via `post_install` hook and access the pods you want to edit including the plist files. Open `pod_target.rb` instance to find out the methods you want to edit.

I dont see an enhancement or bug in CocoaPods library here so I am going to close. This seems a very user-specific problem that can be solved via the CocoaPods hook points.

It is best to ask in StackOverflow under `cocoapods` tag for additional support.
