### ISSUE TITLE
Approaches to modularizing a Podfile

### ISSUE THREAD

**Issue by rpassis** [CocoaPods/CocoaPods#9854]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Our current repository contains various targets across multiple platforms so managing dependencies with a single `Podfile` was becoming unwieldy.

So the solution we found was to modularize our large Podfile into smaller chunks.

For example we have a `Podfile` at the root of our project that among other things, defines:

```ruby
# Evaluates the contents of the file passed in,
# effectively injecting ruby code in this file
def eval_podfile(filename)
    contents = Bundler.read_file(filename)
    instance_eval(contents)
end
```

So we can then call 

```ruby
eval_podfile("Podfiles/Podfile.base")
eval_podfile("Podfiles/Podfile.#{target_platform}")
```

Where target platform may be `ios`, `tvos`, `macos`, etc

This works great and has greatly reduced the complexity of this setup however one downside is that because the actual `Podfile` rarely changes since most dependencies are declared in their platform specific file, the `Podfile` checksum almost always remains the same.

This is because the checksum is defined by reading the `Podfile` file, but without actually evaluating it.

```ruby
checksum = Digest::SHA1.hexdigest(File.read(defined_in_file))
```

Ideally the behavior above would somehow evaluate all the included "modules" before creating the checksum but I understand this would be pretty difficult to accomplish in a generic way.

So my questions are:

1) Should I care that the `Podfile` checksum doesn't change? Does it serve any purpose other than ensuring that the sandboxes are in sync?

2) Is the approach I described above reasonable, or is there a supported / better way of achieving the same thing?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.5 (19F96)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/my-username/.rbenv/versions/2.6.5/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ c425c2da051040b640c1857ed365a098324d351d

               trunk - CDN - https://cdn.cocoapods.org/

```

### Installation Source

```
Executable Path: /Users/my-username/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-env         : 0.1.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
using_bundler = defined? Bundler
unless using_bundler
  puts "\nPlease re-run using:".red
  puts "  bundle exec pod install\n\n"
  exit(1)
end

source 'https://cdn.cocoapods.org/'

MINIMUM_DEPLOYMENT_TARGET = '12.4'

use_frameworks!
inhibit_all_warnings!
plugin 'cocoapods-env'

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

workspace '...'

# User defined options are set by passing `--user-defined-${key}=${value}` options
# when running pod install i.e. `bundle exec pod install --user-defined-platform=tvos`
target_platform = user_defined_options[:platform] || "ios"

puts "------------------------------------".yellow
if user_defined_options[:platform] != nil
puts "User defined platform environment set".yellow
end
puts "Building pods for #{target_platform}".yellow
puts "------------------------------------".yellow

# Evaluates the contents of the file passed in,
# effectively injecting ruby code in this file
def eval_podfile(filename)
    contents = Bundler.read_file(filename)
    instance_eval(contents)
end

eval_podfile("Podfiles/Podfile.base")
eval_podfile("Podfiles/Podfile.modules")
eval_podfile("Podfiles/Podfile.#{target_platform}")
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
hmmm I see the issue. Wouldn't it be possible to just actually embed the contents of the sub-Podfiles into your root Podfile instead of `eval`?

This way the checksum would change. 

Your statement around `Check Pods Manifest` giving your a false positive is correct since your root `Podfile` contents did not change.
