### ISSUE TITLE
Environment variables affect TEST_HOST of test_specs

### ISSUE THREAD

**Issue by chenxiao0228** [CocoaPods/CocoaPods#9856]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
PRODUCT_NAME=FOO pod install

## What did you expect to happen?
TEST_HOST be correct

## What happened instead?
TEST_HOST of the test_spec is set to $(BUILD_PRODUCTS)/FOO.app/FOO

## CocoaPods Environment
Cocoapods 1.8.4

## Project that demonstrates the issue
Any project with test_spec that needs test_host.

**Comment by dnkoutso** [comment]
CocoaPods will not read `PRODUCT_NAME` as the environment variable as far as I know.

The `PRODUCT_NAME` is set on the app target that is meant to be the test host or within an xcconfig.

Please provide more details on what you are trying to accomplish.

**Comment by chenxiao0228** [comment]
A little more background.
We have a *test_spec* with *requires_app_host=true*

When we run *pod install*, the auto-generated app-host target name would be something like *foo-test-host*. But, if there is *PRODUCT_NAME* in environment variables, as what we have in our CI pipeline, the test_host will be *$PRODUCT_NAME*. It can be easily reproduced by running *PRODUCT_NAME=Bar pod install*.

I dug a little deeper and found it comes from `resolved_build_setting`. I also talked to Sam a little bit, it makes sense to consider ENV when evaluating build settings, but I am not sure whether we should make a special case for this scenario.
