### ISSUE TITLE
Unhelpful warning when platform not specified

### ISSUE THREAD

**Issue by ConfusedVorlon** [CocoaPods/CocoaPods#9859]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Don't specify platform in podfile
Run `pod install`

## What did you expect to happen?

easily useable warning about platform

## What happened instead?

slightly unhelpful warning

> [!] Automatically assigning platform `macOS` with version `10.15` on target `Recorder` because no platform was specified. Please specify a platform for this target in your Podfile.

if you then take this warning to heart, open up the podfile, uncomment the platform section and enter

platform :macOS, '10.15'

you get an error that macOS is not recognised.

it would be slightly more helpful if the warning message listed the platform in the same format that you have to enter it in the podfile

e.g.
```
Automatically assigning `platform :macos, '10.15'` on target `Recorder` because no platform was specified. Please specify a platform for this target in your Podfile.
```
(or something like that)

and yes - I know this is a pretty trivial issue!

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
    RubyGems : 3.0.8
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/rob/.rvm/rubies/ruby-2.6.6/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 78d03f328ba483c56e5bbd56e4ce4730eb3626e0

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/rob/.rvm/gems/ruby-2.6.6/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :macos, '10.15'

target 'Recorder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recorder
  pod 'SwiftyUserDefaults', '~> 5.0'

end
```

## Project that demonstrates the issue

ℹ Please link to a project we can download that reproduces the issue.
You can delete this section if your issue is unrelated to build problems,
i.e. it's only an issue with CocoaPods the tool.

**Comment by dnkoutso** [comment]
Heh, this was even intentionally changed to be more "user-friendly" https://github.com/CocoaPods/CocoaPods/commit/8760be3940b6e516caf4616d6b54f79de20068dc

I can see your point....we can always revert that change.
