### ISSUE TITLE
Cocoapods doesn't have the updated library for "SwiftChart"

### ISSUE THREAD

**Issue by vivek5605** [CocoaPods/CocoaPods#9869]
Cocoapods doesn't have the updated library for "SwiftChart". The version for this SwiftChart you got is 1.0.1 and it doesn't have the changes since two years. There is an error in this pod which they fixed it but it doesn't get reflected in the version that you have. The fix for the issue was addressed in repo #105 in their github. https://github.com/gpbl/SwiftChart/issues/112

**Comment by paulb777** [comment]
Library owners are responsible for publishing their libraries to CocoaPods. Please make the request to the providers of SwiftChart.
