### ISSUE TITLE
bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#9872]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
 pod spec lint PBPopupController.podspec

## What did you expect to happen?
PBPopupController.podspec passed validation.

## What happened instead?
Pod is trying to find Ruby in 2.2.2 folder instead of 2.3.1 folder.

-bash: /Users/patrickbodet/.rvm/gems/ruby-2.3.1/bin/pod: /Users/patrickbodet/.rbenv/versions/2.2.2/bin/ruby: bad interpreter: No such file or directory

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`
-bash: /Users/patrickbodet/.rvm/gems/ruby-2.3.1/bin/pod: /Users/patrickbodet/.rbenv/versions/2.2.2/bin/ruby: bad interpreter: No such file or directory

but: macOS Catalina 10.15.4

## Project that demonstrates the issue
https://github.com/iDevelopper/PBPopupController

**Comment by dnkoutso** [comment]
Looks like a bad Ruby installation or some environment setup.Worked for me:
```
   Testing with `xcodebuild`. 
 -> PBPopupController (3.0.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'PBPopupController' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Pods-App' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'App' from project 'App')

Analyzed 1 podspec.

PBPopupController.podspec passed validation.
```

I recommend asking stackoverflow instead. Closing as does not appear to be a CocoaPods library issue.
