### ISSUE TITLE
Error: Could not find a `ios` simulator

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/CocoaPods#9874]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
pod spec lint PBPopupController.podspec

## What did you expect to happen?
PBPopupController.podspec passed validation.

## What happened instead?
 -> PBPopupController (3.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

### Stack

```
   CocoaPods : 1.7.0.beta.3
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.4 (19E266)
       Xcode : 11.5 (11E608c)
         Git : git version 2.27.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.1_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5e77c27bd62dfd5d5ff392b12f825305ef421e88
               RWPodSpecs - https://github.com/iDevelopper/RWPodSpecs.git @ f504174c594fef57e23e66346c00574f4f3fa7e9
               thecodedself - https://github.com/TheCodedSelf/RWPodSpecs @ 5f08646fe7241516dd126bb5fb4669c20188828b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
https://github.com/iDevelopper/PBPopupController

**Comment by dnkoutso** [comment]
The error is clear on the issue. You need to install an iOS sim. There isnt much CocoaPods can do here.

**Comment by iDevelopper** [comment]
I have multiple iOS sim installed!

**Comment by dnkoutso** [comment]
You are also on an old version of cocoapods 1.7.0.beta.3. Please use 1.9.3 and also update `gem update fourflusher`

**Comment by iDevelopper** [comment]
I just installed cocoapods, like this:

gem install cocoapods --user-install

Successfully installed httpclient-2.8.3
Successfully installed algoliasearch-1.27.3
Successfully installed concurrent-ruby-1.1.6
Successfully installed ethon-0.12.0
Successfully installed typhoeus-1.4.0
Successfully installed cocoapods-core-1.9.3
Successfully installed cocoapods-trunk-1.5.0
Successfully installed xcodeproj-1.16.0
Successfully installed fourflusher-2.3.1
Successfully installed cocoapods-1.9.3
...

And pod env give me:

### Stack

```
   CocoaPods : 1.7.0.beta.3
        Ruby : ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
    RubyGems : 3.1.4
        Host : Mac OS X 10.15.4 (19E266)
       Xcode : 11.5 (11E608c)
         Git : git version 2.27.0
Ruby lib dir : /usr/local/Cellar/ruby/2.7.1_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5e77c27bd62dfd5d5ff392b12f825305ef421e88
               RWPodSpecs - https://github.com/iDevelopper/RWPodSpecs.git @ f504174c594fef57e23e66346c00574f4f3fa7e9
               thecodedself - https://github.com/TheCodedSelf/RWPodSpecs @ 5f08646fe7241516dd126bb5fb4669c20188828b
```


What am I missing, please?

**Comment by dnkoutso** [comment]
something is using an old version of cocoapods ...not sure. It should use 1.9.3

**Comment by iDevelopper** [comment]
Thanks, I had to install like this:
 gem install cocoapods
instead of:
gem install cocoapods --user-install
Don't know why?
