### ISSUE TITLE
How is ObjectVersion for the Pods.xcodeproj selected?

### ISSUE THREAD

**Issue by acecilia** [CocoaPods/CocoaPods#9885]
I was trying yo find information online, but could not find much. I am trying to understand how the `ObjectVersion` of the generated xcode projects is calculated (for example `Pods.xcodeproj`).

I observed that:
* Having a normal `Podfile` with a target, the generated `Pods.xcodeproj` has `ObjectVersion = 51`.
* Having a normal `Podfile` with a target and `install! 'cocoapods', integrate_targets: false`, the generated `Pods.xcodeproj` has `ObjectVersion = 46`.
* Having a normal Podfile without any target, the generated `Pods.xcodeproj` has `ObjectVersion = 46`.

Is there any way to use `install! 'cocoapods', integrate_targets: false` and at the same time generate a more updated xcode project, lets say `ObjectVersion = 51`?
Is there any way to customize it from the `Podfile`?

Thanks :)

**Comment by dnkoutso** [comment]
It uses the one from the user project. When you do `integrate_targets: false` it just creates `Pods.xcodeproj` so it chooses the default https://github.com/CocoaPods/Xcodeproj/blob/dac33d249ede1af24c8391e9a2c8b803cb316c4b/lib/xcodeproj/constants.rb#L31 (which is 46).

You can customize it in a `post_install` hook or update your user project that you are integrating with to specify the version you want.

**Comment by dnkoutso** [comment]
@acecilia going to preemptively close the issue. We can continue discussion of course and re-open if we can find an improvement or bug!
