### ISSUE TITLE
PodName-Swift.h File Generated but Unreachable

### ISSUE THREAD

**Issue by victorstewart** [CocoaPods/CocoaPods#9887]
I'm running the latest cocoapods (1.9.3 I think) and XCode 11.5 with an Objective C project, and just added my first Swift pod, and building all pods as static libraries.

I've tried every permutation of import I could think to import the Swift pod into some Objective C code but none of them worked.

```
#import "FlagPhoneNumber-Swift.h"
#import <FlagPhoneNumber/FlagPhoneNumber-Swift.h>
#import <Pods/FlagPhoneNumber/FlagPhoneNumber-Swift.h>
```

So I went digging in the derived data folder and found the file correctly generated, and just copied it into my Objective C folder (lol).

Obviously it's a search path problem but I don't understand since all my imports for all my other Objective C pods work as they always have.

Thoughts?

**Comment by dnkoutso** [comment]
Not quite sure what the issue described here is. It sounds like you expect a search path to be set but it is not.

Can you provide a sample app that demonstrates the issue?
