### ISSUE TITLE
Xcode 12 and development pods: navigation to pod code only shows the generated interface

### ISSUE THREAD

**Issue by gereons** [CocoaPods/CocoaPods#9893]
* 🌈 I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Opened a workspace containing a development pod in Xcode 12

## What did you expect to happen?

Being able to navigate from the app's code to the development pod's code via ctrl-cmd-clicks as in Xcode 11

## What happened instead?

Only the generated interface for the development pod is shown.

## Project that demonstrates the issue

https://github.com/gereons/DevPodTest

PS: this may very well be a bug or even intentional change in Xcode 12. I'm reporting this here because it may be something that cocoapods can influence, but I'm filing a Radar/Feedback with Apple as well. I think ease of developing a pod and an app that uses the pod in tandem is an extremely important feature and should be possible in the future...

**Comment by dnkoutso** [comment]
agreed overall, just not quite sure what we can do from our part here but maybe there is something...keeping it open for now.

**Comment by gereons** [comment]
FB7830055 in case anyone would like to dupe it.

**Comment by gereons** [comment]
This appears to be fixed in Xcode 12 beta 3 (12A8169g)
