### ISSUE TITLE
Pod Pushing spec fails 

### ISSUE THREAD

**Issue by salmanafzal25** [CocoaPods/CocoaPods#9897]
-> salmanFW (0.1.0)
    - ERROR | [iOS] file patterns: The `source_files` pattern did not match any file.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'Pods-App' from project 'Pods')
    - NOTE  | [iOS] xcodebuild:  note: Execution policy exception registration failed and was skipped: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" (in target 'App' from project 'App')

Pods workspace available at `/var/folders/rt/cdphq6m50xv46fxhr4hvfkj80000gp/T/CocoaPods-Lint-20200703-55670-1y7gucl-salmanFW/App.xcworkspace` for inspection.

[!] salmanFW did not pass validation, due to 1 error.

**Comment by dnkoutso** [comment]
The error message clearly says what is the issue:
```
- ERROR | [iOS] file patterns: The source_files pattern did not match any file.
```

Please ask in StackOverflow for help.

**Comment by salmanafzal25** [comment]
Thanks
