### ISSUE TITLE
No way to check if pod is published

### ISSUE THREAD

**Issue by nrbrook** [CocoaPods/CocoaPods#9901]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

We have a cocoapod that depends on another pod we maintain (part of the same project). We want to publish one pod, then publish the pod that depends on it immediately after. However, this will always fail, with:

```
None of your spec sources contain a spec satisfying the dependency: `AirTurnInterface-old-fw/Dynamic (= 4.1.0-b.3)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.) during validation.

[!] The spec did not pass validation, due to 1 error.
```

I've attempted to check if the pod is published with both
```
pod repo update
pod trunk info AirTurnInterface-old-fw
```
and 
```
pod search AirTurnInterface-old-fw
```
However, even though both of these show the pod has been published, attempting to publish the pod that depends on it fails until some time later (couple of minutes?)

I'm not sure if that is a bug in these commands, or if it is just a feature that doesn't exist. So I'm not sure if this is a bug report or a feature request.

**Comment by dnkoutso** [comment]
Please see https://github.com/CocoaPods/cocoapods-trunk/pull/147.

CDN does not always immediately update. Using `git` based master specs repo you can guarantee that.

Closing as I do not see an action for us to take currently and https://github.com/CocoaPods/cocoapods-trunk/pull/147 is already released.

**Comment by lucatorella** [comment]
`pod trunk push` does not have a `--sources option`. Is there another way to specify it?

**Comment by paulb777** [comment]
Use the `--synchronous` option

**Comment by lucatorella** [comment]
I did it. Before `--synchronous` was introduced, I had to wait 10 min and then it was still failing sometimes. When `--synchronous` was added, I migrated our script. Initially, it was great since there was no sleep between the first framework and the second one. But lately, it's failing 50% of the times so I'm adding a delay again.
