### ISSUE TITLE
the name of subspec starts with the pod name

### ISSUE THREAD

**Issue by XianpuMeng** [CocoaPods/CocoaPods#9906]
https://github.com/CocoaPods/CocoaPods/blob/760828a07f8fcfbff03bce13f56a1789b6f5a95d/lib/cocoapods/validator.rb#L121

I ran into a problem. `Pod lib lint` stop for error when the name of subspec starts with the pod name.

### eg

s.name = "MyPod"

s.subspec 'MyPodSub' do |ss|
end

like this, pod lib lint would be error.

### error

Unable to find a specification named `MyPodSub` in `MyPod`

**Comment by dnkoutso** [comment]
heh might be a bug, want to take a stab to fix it?

**Comment by XianpuMeng** [comment]
pr: https://github.com/CocoaPods/CocoaPods/pull/9914
review please! thx!

**Comment by XianpuMeng** [comment]
> heh might be a bug, want to take a stab to fix it?

pr: #9914
review please! thx!
