### ISSUE TITLE
Not installing XCFramework correctly for App Extension target

### ISSUE THREAD

**Issue by emawby** [CocoaPods/CocoaPods#9908]
* [* ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I am testing distributing an XCFramework that will be used in both an App and its embedded Notification Service Extension. When installing the XCFramework using cocoapods it correctly works for the App target, but it does not work for the NSE.

Notably the Build Phases of the NSE does not include [CP] Prepare Artifacts or [CP] Embed Pods Frameworks. This causes the XCFramework to fail building for all targets except the first one built in the XCFramework. 

Again this only affects the NSE. Using the same pod install but not embedding the NSE in the App works correctly for all architectures.

## What did you do?
Run `pod install` to install the XCFramework in both the App target and the NSE target
Build App containing a Notification Service Extension for x86_64 architectures (catalyst and simulator)

## What did you expect to happen?
App to build successfully

## What happened instead?
The build failed for Mac catalyst and iPhone simulators. It succeeds for physical devices.

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'TestApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'TestXCFramework', :path => '~/Documents/PathToFramework/'

end

 target 'TestNotificationServiceExtension' do
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    pod 'TestXCFramework', :path => '~/Documents/PathToFramework/'

end
```

### XCFramework podspec
```ruby
Pod::Spec.new do |s|
    s.name             = "TestXCFramework"
    s.version          = "2.13.1"
    s.summary          = "test library for mobile apps."
    s.homepage         = "https://test.com"
    s.license          = { :type => 'MIT', :file => 'LICENSE' }
    s.author           = { "Elliot Mawby" => "test@test.com" }
    
    s.source           = { :git => "~/Documents/PathToFramework" }
    
    s.platform     = :ios
    s.requires_arc = true
    
    s.ios.vendored_frameworks = 'PathToFramework/test.xcframework'
    s.preserve_paths = 'PathToFramework/test.xcframework'
    
  end
```

**Comment by dnkoutso** [comment]
Did you try master version of CocoaPods? There is plenty of revamped support for XCFrameworks.

Note I did not spend time reproducing your issue and this is just a quick attempt to see if its resolved already.

**Comment by emawby** [comment]
> Did you try master version of CocoaPods? There is plenty of revamped support for XCFrameworks.
> 
> Note I did not spend time reproducing your issue and this is just a quick attempt to see if its resolved already.

This is fixed in master! Thank you for the quick response!

**Comment by dnkoutso** [comment]
cool!
