### ISSUE TITLE
(cocoapods 1.9.3) still has a problem with pod install on a project generated by cmake results in broken xcconfig file references

### ISSUE THREAD

**Issue by Mee-gu** [CocoaPods/CocoaPods#9909]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I upgrade cocospods to 1.9.3 since this PR [#9551](https://github.com/CocoaPods/CocoaPods/pull/9551) fix project path handling issue causing bad cmake generated projects. However the problem remains.
## What did you do?

Run the following commands on the attached project: [HelloCocoaPods.zip](https://github.com/CocoaPods/CocoaPods/files/4894779/HelloCocoaPods.zip)
```
cd HelloCocoaPods
mkdir build && cd build
cmake .. -GXcode
pod install
open HelloCocoaPods.xcworkspace/
```

## What did you expect to happen?

xcconfig references are valid and project compiles successfully.

## What happened instead?
Compilation error:
xcconfig references are incorrect

![image](https://user-images.githubusercontent.com/29719737/87002329-efa0f580-c1eb-11ea-9bff-c15d234d625a.png)

After manually fix the xcconfig references, recompile and report bellow errors:
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

![image](https://user-images.githubusercontent.com/29719737/87002683-b1f09c80-c1ec-11ea-8c60-28fba3dedeac.png)

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ e9140d11dc0b6b616cad3433452666ddcb3bed3c

               Specs - git - git@github.com:CocoaPods/Specs.git @ ed7915533ac3c0cf3093eb6295b98faa4aaeaf97

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

[HelloCocoaPods.zip](https://github.com/CocoaPods/CocoaPods/files/4894779/HelloCocoaPods.zip)

**Comment by dnkoutso** [comment]
> I upgrade cocospods to 1.9.3

The fix landed for 1.10 which has not been released yet.

**Comment by minggo** [comment]
@dnkoutso can i know when 1.10 is released?

**Comment by dnkoutso** [comment]
We do not plan releases, but if i had to guess this week or next.

**Comment by minggo** [comment]
Our game engine [Creator](https://github.com/cocos-creator/engine) will release a version that uses CMake at the end of July. So i want to know if 1.10 will be released then. Thanks.

**Comment by cbedoy** [comment]
I faced same issue, I downgraded to 1.9.0

**Comment by dnkoutso** [comment]
1.10.0.beta.1 is out btw with new Xcodeproj gem. Can someone try it and confirm if this is fixed or not?

**Comment by ItaloYeltsin** [comment]
@dnkoutso tried yesterday and it's working fine!

**Comment by dnkoutso** [comment]
Closing for now!
