### ISSUE TITLE
XCFramework is not embedded on Cocoa framework

### ISSUE THREAD

**Issue by edias** [CocoaPods/CocoaPods#9910]
I'm using Cococapods 1.9.3 and I'm trying to import an XCFramework as one of my dependencies on my Cocoa Framework(Objective-C).

I'm adding this to my podspec:

`
s.vendored_frameworks = '${PODS_ROOT}/MyXCFramework/MyXCFramework.xcframework'
s.xcconfig = { 'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/MyXCFramework/**"' }
`

The Cocoa Framework is importing the library like this.
@import MyXCFramework;

Now the Objective-C class(Cocoa Framework) is saying -> "Receiver type 'Method' for instance message is a forward declaration" in many parts of the code.

Any help will be welcome

**Comment by dnkoutso** [comment]
You can try master branch of CocoaPods or wait for 1.10 to be released just to verify the issue is fixed there.

In the meantime we need a sample app here for us to diagnose further.
