### ISSUE TITLE
HELP - Failed to install 'phonegap-plugin-push': undefined - cocoapods -macOs Catalina

### ISSUE THREAD

**Issue by teuassuri2** [CocoaPods/CocoaPods#9913]
sudo ionic cordova platform add ios
Password:
> cordova platform add ios

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Using cordova-fetch for cordova-ios@^4.5.5
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.ionic.starter
	Name: MyApp
iOS project created with cordova-ios@4.5.5
Installing "cordova-plugin-compat" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-file" for ios
Plugin dependency "cordova-plugin-compat@1.2.0" already fetched, using that version.
Dependent plugin "cordova-plugin-compat" already installed on ios.
Installing "cordova-plugin-file-transfer" for ios
Plugin dependency "cordova-plugin-file@4.3.3" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on ios.
Installing "cordova-plugin-fullscreen" for ios
Installing "cordova-plugin-geolocation" for ios
Installing "cordova-plugin-inappbrowser" for ios
Installing "cordova-plugin-ionic-keyboard" for ios
Installing "cordova-plugin-ionic-webview" for ios
apple-ios version check failed ("/Users/teuassuricardoso/Desktop/iOS Paz/platforms/ios/cordova/apple_ios_version"), continuing anyways.
Installing "cordova-plugin-splashscreen" for ios
Installing "cordova-plugin-statusbar" for ios
Installing "cordova-plugin-whitelist" for ios
Installing "cordova-plugin-x-socialsharing" for ios
Plugin dependency "es6-promise-plugin@4.1.0" already fetched, using that version.
Installing "es6-promise-plugin" for ios
Installing "cordova-plugin-youtube-video-player" for ios
Plugin "es6-promise-plugin" already installed on ios. Making it top-level.
Installing "mx.ferreyra.callnumber" for ios
Installing "phonegap-plugin-push" for ios
Failed to install 'phonegap-plugin-push': undefined
CordovaError: Promise rejected with non-error: '/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/teuassuricardoso/Desktop/iOS Paz/node_modules/.bin in PATH, mode 040777\n/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:439:in `help!\': \u001b[31m[!] You cannot run CocoaPods as root.\u001b[39m (CLAide::Help)\n\n\u001b[4mUsage:\u001b[24m\n\n    $ \u001b[32mpod\u001b[39m \u001b[32mCOMMAND\u001b[39m\n\n      CocoaPods, the Cocoa library package manager.\n\n\u001b[4mCommands:\u001b[24m\n\n    \u001b[32m+ cache\u001b[39m      Manipulate the CocoaPods cache\n    \u001b[32m+ env\u001b[39m        Display pod environment\n    \u001b[32m+ init\u001b[39m       Generate a Podfile for the current directory\n    \u001b[32m+ install\u001b[39m    Install project dependencies according to versions from a\n                 Podfile.lock\n    \u001b[32m+ ipc\u001b[39m        Inter-process communication\n    \u001b[32m+ lib\u001b[39m        Develop pods\n    \u001b[32m+ list\u001b[39m       List pods\n    \u001b[32m+ outdated\u001b[39m   Show outdated project dependencies\n    \u001b[32m+ repo\u001b[39m       Manage spec-repositories\n    \u001b[32m+ setup\u001b[39m      Setup the CocoaPods environment\n    \u001b[32m+ spec\u001b[39m       Manage pod specs\n    \u001b[32m+ update\u001b[39m     Update outdated project dependencies and create new Podfile.lock\n\n\u001b[4mOptions:\u001b[24m\n\n    \u001b[34m--silent\u001b[39m     Show nothing\n    \u001b[34m--version\u001b[39m    Show the version of the tool\n    \u001b[34m--verbose\u001b[39m    Show more debugging information\n    \u001b[34m--no-ansi\u001b[39m    Show output without ANSI codes\n    \u001b[34m--help\u001b[39m       Show help banner of specified command\n\tfrom /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:47:in `run\'\n\tfrom /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>\'\n\tfrom /usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `load\'\n\tfrom /usr/local/Cellar/cocoapods/1.9.3/libexec/bin/pod:23:in `<main>\'\n'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more
        information.

ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

macOS Catalina10.15.5 (19F101)

PushPlugin 2.3.0
Thanks for opting into telemetry to help us improve cordova.
8.1.2 (cordova-lib@8.1.1)

   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 8.1.2 → 9.0.0    │
   │     Run npm i cordova to update     │
   │                                     │
   ╰─────────────────────────────────────╯

**Comment by teuassuri2** [comment]
**I ran the command and got this new error**

**_Mac-mini-de-Teuassuri:iOS Paz teuassuricardoso$ sudo chown -R teuassuricardoso /Users/teuassuricardoso/Desktop/iOS\ Paz_**

CordovaError: Promise rejected with non-error: 'The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add ios exited with exit code 1.

**Comment by dnkoutso** [comment]
This isn't a sufficient bug report for us to diagnose. Furthermore it appears an issue with Cordova setup so please file an issue there.

If you believe its a CocoaPods issue please upload sample app and clear steps to reproduce.

**Comment by dnkoutso** [comment]
It also tells you to do the following:
```
'The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run pod setup first to sync the repo.'
```

Run `pod setup` or setup the master specs repo manually.
