### ISSUE TITLE
Dependencies of configuration-specific pods should inherit that configuration

### ISSUE THREAD

**Issue by gereons** [CocoaPods/CocoaPods#9915]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

I'm trying to exclude a certain pod from my debug builds. This works great, but the pods that the excluded pod depends on are still present in the debug version, and in this specific case, even run code on app startup (via ObjC `+[load]` most likely).

I would rather not see any of these dependencies in my debug builds.

Here's an example podfile:

```
use_frameworks!
platform :ios, '13.0'
inhibit_all_warnings!

project 'myApp', 'Release' => :release, 'Debug' => :debug

target 'myApp' do
  pod 'SwiftLint'
  pod 'Firebase/Analytics', :configurations => ['Release']
end
```

results in Pods-myApp.debug.xcconfig listing all the dependencies that 'Firebase/Analytics' brings with it. Only 'Firebase/Analytics'  itself is not present.

Figuring out and listing all 13 dependencies explictly is tedious and error-prone. I think it would be much better if the dependencies automatically inherited the `:configurations` option from the top-level pod.

**Comment by dnkoutso** [comment]
i believe this issue has been brought up before. I do not recall what was/is the difficulty to achieve that.

**Comment by rlasante** [comment]
I'm also running into this issue too and would prefer to not have to manually update to remove the dependencies every single time I have to update

**Comment by dnkoutso** [comment]
The workaround here is to explicitly specify downstream dependencies configuration as well.

**Comment by dnkoutso** [comment]
Going to actually close this as a dup of https://github.com/CocoaPods/CocoaPods/issues/10474
