### ISSUE TITLE
1.10.beta.1: Test spec resources are missing

### ISSUE THREAD

**Issue by paulb777** [CocoaPods/CocoaPods#9920]
From https://github.com/firebase/firebase-ios-sdk:

`pod lib lint FirebaseCore.podspec --platforms=ios --no-clean`

The 1.10.beta.1 project is missing the resources in the build phase:

1.9.3

![Screen Shot 2020-07-18 at 8 57 23 AM](https://user-images.githubusercontent.com/73870/87856541-bd228700-c8d4-11ea-97e8-b39be63bf788.png)

1.10.beta.1

![Screen Shot 2020-07-18 at 8 57 55 AM](https://user-images.githubusercontent.com/73870/87856556-ce6b9380-c8d4-11ea-8789-4d562b5b7ccf.png)

Failure log in GitHub Actions at https://github.com/firebase/firebase-ios-sdk/runs/885053262?check_suite_focus=true

**Comment by dnkoutso** [comment]
I have not confirmed it but I suspect https://github.com/CocoaPods/CocoaPods/pull/9441 causing this

**Comment by paulb777** [comment]
Confirmed that reverting #9441 fixes the regression.
