### ISSUE TITLE
[Question] URL to download pods?

### ISSUE THREAD

**Issue by rpotter12** [CocoaPods/CocoaPods#9923]
Hi,
We can download gem package by https://rubygems.org/downloads/{name}-{version}.gem, cargo creates by https://crates.io/api/v1/crates/{name}/{version}/download. We can download download package directly by this url.

Is there any URL to download pods directly or we have to download any pod is downloaded by github only?

**Comment by dnkoutso** [comment]
Do you mean downloading the source of a pod or to download the cocoapods gem?

If its the former then each podspec defines where its source is by the pod author via the `s.source` DSL. You can always take a public podspec and republish it internally if you want to change its source to something else internal to you.

I do not see an action to be taken here either for a feature or bug fix so going to close. We can continue discussion as needed.
