### ISSUE TITLE
Cocoapods not installed or not in valid state

### ISSUE THREAD

**Issue by przbadu** [CocoaPods/CocoaPods#9924]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

```sh
- upgraded to latest Mac osx release
- updated xcode to latest version

 $ pod --version
1.9.3

$ which pod
/Users/przbadu/.rbenv/shims/pod

$  which gem
/Users/przbadu/.rbenv/shims/gem

$  which ruby
/Users/przbadu/.rbenv/shims/ruby
```

## What did you do?

```
flutter run
```

## What did you expect to happen?

- I want to run flutter app with basic configuration with location aware app. for that I have default flutter app setup with https://pub.dev/packages/geolocator. when I run flutter app, it should ask for permission, and if user allow permission, then it should give me permission.

## What happened instead?

```
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install:
  sudo gem install cocoapods

CocoaPods not installed or not in valid state.
Error launching application on iPhone 11 Pro.
```

## CocoaPods Environment

```

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G73)
       Xcode : 11.6 (11E708)
         Git : git version 2.27.0
Ruby lib dir : /Users/przbadu/.rbenv/versions/2.6.3/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 8e31472facf1d5d6e461046c94d23108658411dc

```

### Installation Source

```
Executable Path: /Users/przbadu/.rbenv/versions/2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

**Comment by przbadu** [comment]
seems like issue with AndroidStudio, building ios from CLI working:

Working command.

```sh
flutter build ios --simulator
flutter run
```

**Comment by netgfx** [comment]
Its the same thing for VSCode as well but the error is not giving more information, what is missing? where is it trying to pull cocoapods from?
Running directly for XCode works, running flutter run works. But the debug session is broken and throwing this error.
