### ISSUE TITLE
macOS 11.0 new installation on homebrew

### ISSUE THREAD

**Issue by brennobemoura** [CocoaPods/CocoaPods#9939]
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I installed a clean version of macOS 11.0 in Intel based mac.
After, I downloaded and install homebrew with Xcode 12.
Then, executed `brew install cocoapods`

## What did you expect to happen?

Install cocoapods 1.9.3 correctly

## What happened instead?

Homebrew threw this error
`Errno::ENOENT: No such file or directory - /usr/local/Cellar/cocoapods/1.9.3/libexec/bin/xcodeproj`

## CocoaPods Environment

None.

## Project that demonstrates the issue

None.

**Comment by dnkoutso** [comment]
I do not think this is an issue with CocoaPods itself?

**Comment by brennobemoura** [comment]
Yeah, I'm still investigating but it seems to be an error on ruby or homebrew. When I install using `gem install cocoapods` command, it works fine.
