### ISSUE TITLE
Mac OS X install error

### ISSUE THREAD

**Issue by nagy1991** [CocoaPods/CocoaPods#9940]
Hello, Support ! 

My Problem is sudo gem install cocoapods. NOT install error

admin:rubygems-3.1.4 user$ sudo gem install cocoapods
Building native extensions. This could take a while...
ERROR:  Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.13.1/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I /Library/Ruby/Site/2.3.0 -r ./siteconf20200724-19381-1vxn3yv.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/ffi-1.13.1 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/ffi-1.13.1/gem_make.out

**Comment by dnkoutso** [comment]
This seems an issue with installing. the ffi gem that CocoaPods depends upon. I would file an issue with them instead.

This report is not sufficient for us to diagnose here and does not look like related to CocoaPods directly.
