### ISSUE TITLE
Latest XCFramework rework on Cocoapods 1.10 is embedding static frameworks

### ISSUE THREAD

**Issue by BernardGatt** [CocoaPods/CocoaPods#9943]
# Report

## What did you do?

The [latest rework](https://github.com/CocoaPods/CocoaPods/pull/9720) fixes the issue where X86_64 were not being picked up from XCFrameworks.

But when archiving for release, static frameworks are being embedded with the IPA which causes a Mach-O error.

Looking at the `Pods-Target-frameworks.sh` in the `Debug` and `Release` section the static framework is being included for bundling.

```sh
install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/StaticFramework/StaticFramework.framework"
```

### Note
In 1.09 there was an embed flag which is now removed.

## What did you expect to happen?

Continue with signing and publishing of IPA.

## What happened instead?

![image](https://user-images.githubusercontent.com/346012/88482597-9e6e6100-cf62-11ea-9004-6ca26fc80252.png)

## CocoaPods Environment

1.10.0.beta.1

**Comment by dnkoutso** [comment]
cc @amorde
