### ISSUE TITLE
pod install no working

### ISSUE THREAD

**Issue by chellongCoder** [CocoaPods/CocoaPods#9946]
![image](https://user-images.githubusercontent.com/30166352/88633683-896b0c80-d0df-11ea-8a4d-c724c55c3576.png)

**Comment by bobgodwinx** [comment]
Is happening on `xcode 12 beta 3` ?

**Comment by dnkoutso** [comment]
This looks like its slow cloning the specs repo. Newer version of cocoapods uses CDN by default to avoid this.

The issue filed here does not show a bug or enhancement so I am going to close.
