### ISSUE TITLE
Validate `pod` directive options and print meaningful error.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#995]
See #994 for an example (combined use of `:podspec` and `:git`).

**Comment by k0nserv** [comment]
I can't reproduce the original issue. The podfile I am using 


```ruby
platform :ios, '8.0'

pod 'AFNetworking' 

target :Test do
    pod 'SDWebImage'
    pod 'Facebook-iOS-SDK', :podspec => "https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/Facebook-iOS-SDK/4.1.0/Facebook-iOS-SDK.podspec.json", 
                            :git => "https://github.com/facebook/facebook-ios-sdk.git", :commit => "fc1cde21ae7359255b59a24e4845a7da97ee3ec8"
end
```

installs without issue. I have a basic `PodfileValidator` implemented that could catch this issue, but I am not sure if it still is an issue

**Comment by segiddins** [comment]
@k0nserv that's a bug if that works...

**Comment by k0nserv** [comment]
Okay then I guess I'll continue. So both `podspec` and `path` are illegal in combination with any of the supported downloaders?

**Comment by segiddins** [comment]
yup!

**Comment by k0nserv** [comment]
Closing with the merge of #3676
