### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by jackiehu** [CocoaPods/CocoaPods#9952]
[!] CDN: trunk Repo update failed - 47 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/b/c/d/SwiftBrick/0.0.1/SwiftBrick.podspec.json Response: 403 <!DOCTYPE html><html><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title>403 Forbidden</title><style type="text/css">body{margin:5% auto 0 auto;padding:0 18px}.P{margin:0 22%}.O{margin-top:20px}.N{margin-top:10px}.M{margin:10px 0 30px 0}.L{margin-bottom:60px}.K{font-size:25px;color:#F90}.J{font-size:14px}.I{font-size:20px}.H{font-size:18px}.G{font-size:16px}.F{width:230px;float:left}.E{margin-top:5px}.D{margin:8px 0 0 -20px}.C{color:#3CF;cursor:pointer}.B{color:#909090;margin-top:15px}.A{line-height:30px}.hide_me{display:none}</style></head><body><div id="p" class="P"><div class="K">403</div><div class="O I">Forbidden</div><p class="J A L">Error Times: Thu, 30 Jul 2020 03:55:37 GMT<br><span class="F">IP: 106.8.149.8</span>Node information: wtong92:18<br>URL: https://cdn.jsdelivr.net/cocoa/Specs/b/c/d/SwiftBrick/0.0.1/SwiftBrick.podspec.json<br><span class="hide_me">Please contact our support: <A HREF="mailto:"></A><br></span>Check: <span class="C G" onclick="s(0)">Details</span></p></div><div id="d" class="hide_me P H"><div class="K">ERROR</div><p class="O I">The Requested URL could not be retrieved</p><div class="O"><div>While trying to retrieve the URL:</div><pre class="B G">https://cdn.jsdelivr.net/cocoa/Specs/b/c/d/SwiftBrick/0.0.1/SwiftBrick.podspec.json</pre></div><div class="M"><span>The following error was encountered:</span><ul class="E"><li class="D G">Invalid Request</li></ul></div><p class="M">The access control configuration prevents your request at this time.<p></p>Please contact your service provider if you feel this is incorrect.</p><a class="N C" href="#" onclick="s(1)">return</a></div><script type="text/javascript">function e(i){return document.getElementById(i);}function d(i,t){e(i).style.display=(t?'block':'none');}function s(e){d('p',e);d('d',!e);}</script></body></html>

**Comment by dnkoutso** [comment]
This isnt a valid issue report.

**Comment by dnkoutso** [comment]
Seems like a network firewall that prevents you from hitting our CDN. Use `git` based repo instead.

**Comment by marcuswu0814** [comment]
Hi @dnkoutso, same issue here, the `CDN` repo work perfect before today morning.

Since [1.7.2](https://blog.cocoapods.org/CocoaPods-1.7.2/) support `CDN` based repo to avoid super slow repo update issue. I don't think the best solution is rolling back to use `git` based repo. I want to check It's my environment issue or CDN issue?

**Comment by dnkoutso** [comment]
@marcuswu0814 I just removed my trunk repo locally and did `pod install` again and it worked through CDN.

Part of the logs:
```
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
  CDN: trunk Relative path downloaded: CocoaPods-version.yml, save ETag: "871dbc3ac66ab065476ee696d0c77eeb-ssl"
  CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
  CDN: trunk Relative path downloaded: all_pods_versions_a_7_5.txt, save ETag: "8a0eb0065a34ead56252d6dfa408a3d3-ssl-df"
  CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/a/7/5/AFNetworking/0.10.0/AFNetworking.podspec.json to
  https://cdn.jsdelivr.net/cocoa/Specs/a/7/5/AFNetworking/0.10.0/AFNetworking.podspec.json
  CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/a/7/5/AFNetworking/0.7.0/AFNetworking.podspec.json to
  https://cdn.jsdelivr.net/cocoa/Specs/a/7/5/AFNetworking/0.7.0/AFNetworking.podspec.json
  CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/a/7/5/AFNetworking/0.9.0/AFNetworking.podspec.json to
  https://cdn.jsdelivr.net/cocoa/Specs/a/7/5/AFNetworking/0.9.0/AFNetworking.podspec.json
```

So CDN is working.

**Comment by marcuswu0814** [comment]
Thanks @dnkoutso , I tried to use VPN to US ip and it work, so it's my ISP issue? 🤦‍♂️

**Comment by marcuswu0814** [comment]
In my case, some spec url can access with correct content:

https://cdn.jsdelivr.net/cocoa/Specs/b/c/d/SwiftBrick/0.0.1/SwiftBrick.podspec.json

some can't:

https://cdn.jsdelivr.net/cocoa/Specs/a/7/5/AFNetworking/0.9.0/AFNetworking.podspec.json
https://cdn.jsdelivr.net/cocoa/Specs/9/4/5/RealmSwift/5.0.0-beta.1/RealmSwift.podspec.json
