### ISSUE TITLE
undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by BaeksunYou** [CocoaPods/CocoaPods#9953]
Git iOS swift project
branch-1 > branch-2 > branch-3

1. merge 
git checkout branch-2
git merge branch-1

2. Xcode project open. not target open.

Error show!!!!!!!

$$$$$$$$$$$$$ xcodeproj target-diff
Traceback (most recent call last):
	13: from /usr/local/bin/xcodeproj:23:in `<main>'
	12: from /usr/local/bin/xcodeproj:23:in `load'
	11: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/bin/xcodeproj:10:in `<top (required)>'
	10: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/command/target_diff.rb:26:in `validate!'
	 8: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/command.rb:49:in `open_project!'
	 7: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/command.rb:60:in `xcodeproj'
	 6: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/project.rb:112:in `open'
	 5: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
	 4: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/plist.rb:27:in `read_from_path'
	 3: from /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:107:in `parse!'
	 2: from /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:132:in `parse_object'
	 1: from /Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:199:in `parse_dictionary'
/Library/Ruby/Gems/2.6.0/gems/nanaimo-0.2.6/lib/nanaimo/reader.rb:284:in `raise_parser_error': [!] Dictionary missing ';' after key-value pair for "objects", found "" (Nanaimo::Reader::ParseError)
    #  -------------------------------------------
    #  	rootObject = A560CE1520E2322E002D9C31 /* Project object */;
    #  }
6345>  
       ^
    #  -------------------------------------------
$$$$$$$$$$$$$ xcodeproj project-diff
Traceback (most recent call last):
	11: from /usr/local/bin/xcodeproj:23:in `<main>'
	10: from /usr/local/bin/xcodeproj:23:in `load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/bin/xcodeproj:10:in `<top (required)>'
	 8: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:333:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/command/project_diff.rb:34:in `validate!'
	 6: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/command.rb:51:in `open_project!'
	 5: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/command.rb:51:in `map'
	 4: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/command.rb:51:in `block in open_project!'
	 3: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.0/lib/xcodeproj/project.rb:107:in `open'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `+'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:350:in `initialize': no implicit conversion of nil into String (TypeError)

**Comment by dnkoutso** [comment]
This is not a valid issue report. Please file one using the issue template, provide a sample app and clear steps to reproduce the issue.
