### ISSUE TITLE
error installing cocoapods

### ISSUE THREAD

**Issue by kusofte-chap** [CocoaPods/CocoaPods#9965]
ERROR:  Error installing cocoapods:
        invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Library/Ruby/Gems/2.6.0/cache/concurrent-ruby-1.1.6.gem

**Comment by dnkoutso** [comment]
Try `gem uninstall concurrent-ruby` and re-install the gem? The issue report is insufficient for us to diagnose. I recommend asking in StackOverflow.

**Comment by dnkoutso** [comment]
we can continue the discussion here but I do not see a cocoapods library issue or enhancement.

**Comment by kusofte-chap** [comment]
> Try `gem uninstall concurrent-ruby` and re-install the gem? The issue report is insufficient for us to diagnose. I recommend asking in StackOverflow.

Thank you. The problem has been solved. I deleted 'concurrent-ruby-1.1.6.gem', and then reinstalled cocoapods, successfully.
