### ISSUE TITLE
Linting fails for pod framework that does not currently support arm64 simulator

### ISSUE THREAD

**Issue by paynerc** [CocoaPods/CocoaPods#9967]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I am currently working through updating the frameworks that we distribute to use XCFrameworks instead of the dynamic frameworks we have previously been shipping. Due to "reasons" our framework is not yet able to support the arm64 simulator as we have a number of internal static library dependencies that are part of our frameworks that need to be reworked to build for the arm64 simulator.

Starting with the release of Xcode 12 Beta 3 (and onward), Xcode attempts to build both simulator slices, x86_64 and arm64. In our internal build process for our frameworks we have disabled the building of the arm64 slices until we are able to complete the work mentioned above.

During our CI build process, we publish the artifacts to our internal Podspec repo to assist our QA team and other stakeholders to be able to use the internal variants during development. 

What I am finding is that `pod lint` and `pod repo push` are failing because the linting validation cannot link to the arm64 simulator slice.

I have been looking through the Cocoapods source to see if there is a way we can specify that linting should ignore the arm64 simulator architecture, but have not found a way.

## What did you expect to happen?

I would like for the ability to exclude the arm64 simulator architecture during linting and internal pod publishing.

## What happened instead?

```
    The following build commands failed:
    	Ld /Users/distiller/Library/Developer/Xcode/DerivedData/App-akgkjxxbwilmbdbiwbdaapxfpold/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Objects-normal/arm64/Binary/App normal arm64
    (1 failure)
```

## CocoaPods Environment

 pod env

### Stack

```
   CocoaPods : 1.10.0.beta.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.5 (19F101)
       Xcode : 12.0 (12A8179i)
         Git : git version 2.28.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapod-specs-internal - git - git@github.com:<redacted>/cocoapod-specs-internal.git @ 574684488984d7a31f213084464ad4d7de398098

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

**Comment by seanreinhardtapps** [comment]
I haven't tried it yet, but I think there could be a workaround in the form of adding `s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }` to your podspec.

**Comment by paynerc** [comment]
@seanreinhardtapps,

Thank you so much for that work around. That does get me past my current issue.

Ryan

**Comment by dnkoutso** [comment]
@seanreinhardtapps is this something we can tackle "first-class" in CocoaPods or shall I close with the above workaround?

**Comment by seanreinhardtapps** [comment]
I think we can close this.  This is the appropriate way for a podspec to exclude the ARM64 Simulator architecture.

**Comment by dnkoutso** [comment]
Sounds good.

**Comment by abiligiri** [comment]
Would this also apply to the App scheme while listing ? @seanreinhardtapps

**Comment by abiligiri** [comment]
Is this workaround effective if pod being listed has direct and/or transitive dependencies?

**Comment by valeriomazzeo** [comment]
> I haven't tried it yet, but I think there could be a workaround in the form of adding s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' } to your podspec.

@seanreinhardtapps - using your suggestion causes `pod lib lint` to fail with this error instead.
```
error: could not find module 'MyLibrary' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64
```

Any suggestion?

Xcode 12
Cocoapods v1.10.rc.1
