### ISSUE TITLE
Automate Binaries Generation on CI

### ISSUE THREAD

**Issue by edias** [CocoaPods/CocoaPods#9970]
Hello Everyone,

I'm working in a project that has a large amount of 3rd-party libraries using Cocapods.

We would like to generate universal binaries or XCFrameworks on our CI so we can reuse them across multiple PRs instead of rebuilding them all the time.

We can easily run xcbuild on these pods, generate a XCFramework from each of them and cache it. The challenge is to change cocoapods setup(podfile and podspecs) on CI for consecutive builds to link these binaries instead of building them over and over again later.

Any help will be very appreciated!

**Comment by dnkoutso** [comment]
Best thing to do is build them once and re-publish the pre-built xcframework with a podspec in your internal repo.

Then use `pod 'MyPod', :source => 'your/internal/repo'` to pickup the pre-built binary dependency.

**Comment by edias** [comment]
Thank you very much @dnkoutso
