### ISSUE TITLE
Video freeze when calling video at ipad 10.2 using googleWebRTC

### ISSUE THREAD

**Issue by nguyencongthienvu** [CocoaPods/CocoaPods#9971]
# Report

## What did you do?

Calling 2 ipad 1 ipad 6th 1 vs ipad 10.2, ipad Air vs ipad 10.2, ipad Pro vs ipad 10.2 

## What did you expect to happen?

Calling no freeze at ipad 10.2

## What happened instead?

Example I have ipad A (ipad 6th, pro, air ...) and ipad B (ipad 10.2), when calling ipad A to ipad B or ipad B to ipad, video screen will appear with screen A (Receiver), screen B(Caller). After 5 second or sometime 1 minute ipad B screen A (receiver) of ipad 10.2 freeze, screen B sill normal, and Ipad A screen A and screen B normal only ipad 10.2 freeze, do you know why ?

## CocoaPods Environment

 platform :ios, '12.4'

target 'tabiq' do
  use_frameworks!

  pod 'Localize-Swift', '~> 2.0'
  pod 'Alamofire'
  pod 'ActionSheetPicker-3.0'
  pod 'SwiftyDropbox'
  pod 'JGProgressHUD'
  pod 'GoogleWebRTC'
  pod 'Starscream', '~> 3.0'
  pod 'Socket.IO-Client-Swift', '~> 15.1.0'
  pod 'DLRadioButton', '~> 1.4'
  pod 'DropDown'
  pod 'KBNumberPad', '~> 1.0.1'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Crashlytics'
end

**Comment by dnkoutso** [comment]
This does not to seem to be an issue with CocoaPods package manager itself. Please file a bug in googleWebRTC repo.
