### ISSUE TITLE
CocoaPods 1.10.0 Beta 2

### ISSUE THREAD

**Issue by BernardGatt** [CocoaPods/CocoaPods#9972]
When are you planning to release Beta 2 as a public pre-release version?

Thank you!

**Comment by dnkoutso** [comment]
There has never been a schedule for releases so its always hard to commit on a specific date.

However, I am aiming to make a releases this week. In the meantime, if its urgent to use the latest 1-10-stable branch you can use Bundler and point to that branch.

Closing for now we can continue discussion.

**Comment by BernardGatt** [comment]
Thanks @dnkoutso. Needed to check because I have a pending release which switches the dependencies to xcframework.
