### ISSUE TITLE
Unable to recognize headers in Xcode 12 beta 4 

### ISSUE THREAD

**Issue by perlasivakrishna** [CocoaPods/CocoaPods#9975]
![error](https://user-images.githubusercontent.com/6779941/89997798-45186880-dcaa-11ea-9996-d3648d958300.png)

I'm able to build my project in Xcode 11.5 in device and simulators, but not able to build in Xcode12 simulators(works in device).

But when I create a new project, and copy this pod to new project and do pod install, every thing works in new project. 

Any suggestions what could be wrong ?

**Comment by dnkoutso** [comment]
Please ask this question in stackoverflow. Given the current issue this is hard to determine if its a cocoapods library bug itself and not a problem with your project setup or pod you are consuming.

I will close preemptively but i can re-open if you provide clear instructions and a sample app that shows a bug or missing functionality in cocoapods.
