### ISSUE TITLE
pod install issue

### ISSUE THREAD

**Issue by sorinszucsik** [CocoaPods/CocoaPods#9985]
can you please help me with this, I'm trying to compile a project for xcode but when I do the pod install command I end up with this:

https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Dictionary+missing+%27%3B%27+after+key-value+pair+for+%22ORGANIZATIONNAME%22%2C+found+%22T%22%0A++%23++-------------------------------------------%0A++%23++%09%09%09%09LastSwiftUpdateCheck+%3D+1020%3B%0A++%23++%09%09%09%09LastUpgradeCheck+%3D+1020%3B%0A95%3E++%09%09%09%09ORGANIZATIONNAME+%3D+Sfera+Timisoarei%3B%0A+++++%09%09%09%09+++++++++++++++++++++++++%5E%0A++%23++%09%09%09%09TargetAttributes+%3D+%7B%0A++%23++%09%09%09%09%098BEA476922B72C4C0034118D+%3D+%7B%0A++%23++-------------------------------------------%0A&type=Issues

**Comment by dnkoutso** [comment]
This isnt a valid issue report. Please fill in issue template properly and include a reproducible project.
