### ISSUE TITLE
TestInclusions example - duplicated linking

### ISSUE THREAD

**Issue by szotp** [CocoaPods/CocoaPods#9987]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Download CocoaPods repo
2. Launch TestInclusions example after installing pods.
3. Run test and observe console output.

## What did you expect to happen?

Tests completes without any warnings.

## What happened instead?

Tests completed, but I got a litany of "Class X is implemented in both..."
```
objc[28443]: Class SwrveBaseConversation is implemented in both /Users/work/Library/Developer/CoreSimulator/Devices/42A64C99-589F-4E64-9F3B-259114A31397/data/Containers/Bundle/Application/734CF9C7-374E-4371-B5A3-81A6A5F61198/TestInclusions.app/TestInclusions (0x100f84728) and /Users/work/Library/Developer/Xcode/DerivedData/Examples-gqbmxdedpvxeklgiqxapzmaxsbyf/Build/Products/Debug-iphonesimulator/TestInclusions.app/PlugIns/TestInclusionsTests.xctest/TestInclusionsTests (0x1014d6bb0). One of the two will be used. Which one is undefined.
```

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.5 (11E608c)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```
Xcode 11.5

## Project that demonstrates the issue

https://github.com/CocoaPods/CocoaPods/tree/master/examples/TestInclusions

## Workarounds
1. Use dynamic frameworks - but I would like to keep using static frameworks.
2. Set "Other linker flags" of TestInclusionsTests to empty - works, but if I had pods only for TestInclusionsTests target, I would need to edit it and keep synced.

**Comment by dnkoutso** [comment]
Yes this issue is accurate. We can just remove the app host from the test target and it seems to fix that. However, how is the current issue affecting any of your projects?

**Comment by szotp** [comment]
> Yes this issue is accurate. We can just remove the app host from the test target and it seems to fix that. 

Only because example app does not use any classes from main project. If you add this test:
```
- (void)testAppDelegate {
    NSLog(@"%@", [AppDelegate class]);
}
```

You will get:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AppDelegate", referenced from:
      objc-class-ref in TestInclusionsTests.o
ld: symbol(s) not found for architecture x86_64
```

Currently all tests pass, so the only problem is console spam. But I'm sure there are cases where it matters. Maybe if I used `isKindOfClass`.

**Comment by dnkoutso** [comment]
Sure but if we want to use sources from the app host then we will change the `Podfile`.

I continue to wonder how this issue manifests in one of your projects?

**Comment by szotp** [comment]
My app has the same setup: an app with static pods linked in + test target. I was getting these "implemented in both" errors, so I was wondering if CocoaPods even supports this use case. I searched a bit and found this TestInclusions example, hoping it would show me the correct approach - but it was broken the same way.

It seems like CocoaPods does not really support this, correct? And I should convert to dynamic frameworks, or keep using that workaround with linker flags.

**Comment by dnkoutso** [comment]
```ruby
abstract_target 'TestInclusionsPods' do
    pod 'SwrveConversationSDK', '~> 4.3.0'

    target 'TestInclusions' do
    	target 'TestInclusionsTests' do
    		inherit! :search_paths
    	end
    end    
end
```

This setup works and CocoaPods supports this case. The test will fail because it needs updating as the bundle referenced is no longer copied into the test bundle but rather exists in the app bundle.

But yes the above setup should work for handling statically linked libs shared between an app and a test bundle.

**Comment by szotp** [comment]
Sorry I forgot to reply. inherit! :search_paths fixes this, but sadly, only for ObjC modules.
