### ISSUE TITLE
pod outdated shows wrong latest version

### ISSUE THREAD

**Issue by phoney** [CocoaPods/CocoaPods#9988]
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod outdated

## What did you expect to happen?

list correct latest versions for pods that have new versions

## What happened instead?

The latest version for fontawesome_swift shows 5.14.0 when the correct latest version is 1.9.0

### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G73)
       Xcode : 11.6 (11E708)
         Git : git version 2.28.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://cdn.cocoapods.org/'
platform :ios,           '11.0'
use_frameworks!

def pods
  pod 'Alamofire', '~> 5.2.0'
  pod 'AppCenter'
  pod 'BadgeSwift', '~> 8.0'
  pod 'BonMot', '~> 5.0'
  pod 'ContextMenu', :git => 'https://github.com/GitHawkApp/ContextMenu.git', branch: 'master'
  pod 'Device'
  pod 'Down', '~> 0.9'
  pod 'DZNEmptyDataSet'
  pod 'FontAwesome.swift', '~> 1.7'
  pod 'IQKeyboardManagerSwift', '~> 6.0'
  pod 'MGSwipeTableCell'
  pod 'Mixpanel-swift', '~> 2.6'
  pod 'PDFExporter'
  pod 'PhoneNumberKit'
  pod 'RealmSwift', '5.3.2'
  pod 'SDWebImage', '~> 5.1'
  pod 'SVProgressHUD', '~> 2.0'
  pod 'SwiftDate', '~> 6.0'
  pod 'TPKeyboardAvoiding'
  pod 'UIScreenExtension', :git => 'https://github.com/marchv/UIScreenExtension'
end

target 'MyApp' do
  pods
end
```

I filed an issue with the fontawesome project that explains the cause of this in part.

https://github.com/thii/FontAwesome.swift/issues/263

There was a tag "5.14.0" in a branch that had been deleted. However, deleting the tag hasn't fixed the problem.

There's no reason I can see that having a tag that conflicts with the info in the podspec file for the latest version should cause pod outdated to mention that tag as the latest version. I guess you're reading the tags in order to display a newest version. I guess that makes sense for beta versions but not for any random tag. 

I see the same issue with RealmSwift.

Anyway, how can fontawesome_swift fix this issue now that the rogue tag is deleted?

**Comment by dnkoutso** [comment]
Its probably due to a cached value? Perhaps `pod cache clean --all` and try again?

**Comment by phoney** [comment]
I manually deleted the fontawesome files from the cache then did ```pod update``` and ```pod outdated``` and I still see that 5.14.0 latest version. It takes a while to download my pods but I'll try to clean all tonight.

**Comment by phoney** [comment]
I cleaned the cache and deleted the Pods folder in my project and the problem remains. I started to build a project that demonstrates this. The Podfile simply has    ``` pod 'FontAwesome.swift'``` and ```pod update``` throws an error about not being able to find a branch named "5.14.0" I don't think the problem is on my computer.

**Comment by dnkoutso** [comment]
its not about a branch its about a released version. The last release shown here is 5.14.0 https://cocoapods.org/pods/FontAwesome.swift so not sure what is going on here.

**Comment by paulb777** [comment]
Isn't that the problem? The podspec for version 5.14.0 is [published](https://github.com/CocoaPods/Specs/blob/master/Specs/d/e/b/FontAwesome.swift/5.14.0/FontAwesome.swift.podspec.json) and the tag no longer exists so it will fail.

**Comment by sunilmaurya04** [comment]
Also, I'm facing the same issue.

<img width="924" alt="Screenshot 2020-08-20 at 12 48 37 PM" src="https://user-images.githubusercontent.com/61402643/90729038-8da3d780-e2e3-11ea-8f03-af57b057ed28.png">

Please help me on the same.

**Comment by phoney** [comment]
To fix that you can put ```pod 'FontAwesome.swift', '~> 1.9```` in your Podfile. That will only match the 1.9.0 version.

**Comment by dnkoutso** [comment]
It looks like the author has deleted this tag but the version is still published. Not sure what the issue is here. I recommend reaching out to the author?

**Comment by keeshux** [comment]
> It looks like the author has deleted this tag but the version is still published. Not sure what the issue is here. I recommend reaching out to the author?

Indeed, the issue was on author's end. This one should be closed.

**Comment by phoney** [comment]
It's working correctly for me now. I'll close this. Thanks for the help.
