### ISSUE TITLE
Is there any possibility of installing pod based on configuration

### ISSUE THREAD

**Issue by Mridul56** [CocoaPods/CocoaPods#9989]
I want to install a pod for only debug or dev configuration not for release.
I've tried using `:configuration` tag but doing that its installing for all the configuration but adding header search path only for the given configuration.

I've tried this so far
`pod 'X', :configurations => ['debug']`

is there any way of doing that?

**Comment by dnkoutso** [comment]
That is the way. Pod will not be linked.

Closing as behaves correctly. Feel free to continue discussion here.

**Comment by Mridul56** [comment]
Hey @dnkoutso you are right linking is not happening for other configuration.
I think I have mentioned the wrong point.

I meant, is there a way to avoid downloading of pod itself based on configuration?

**Comment by dnkoutso** [comment]
not built in. CocoaPods integrates all configurations. There is no way to integrate only a single config.
