### ISSUE TITLE
Cocoapods 集成问题

### ISSUE THREAD

**Issue by miqilinsanxingchushi** [CocoaPods/CocoaPods#9993]
ArgumentError - Illformed requirement `"~> (0.3.0)"`
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:63:in `parse'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:88:in `block in initialize'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:88:in `map!'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:88:in `initialize'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:34:in `new'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/requirement.rb:34:in `create'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/dependency.rb:101:in `initialize'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/podfile/target_definition.rb:979:in `new'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/podfile/target_definition.rb:979:in `block in pod_dependencies'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/podfile/target_definition.rb:975:in `map'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/podfile/target_definition.rb:975:in `pod_dependencies'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/podfile/target_definition.rb:96:in `non_inherited_dependencies'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.0.beta.2/lib/cocoapods-core/podfile/target_definition.rb:74:in `dependencies'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:44:in `block in from_podfile'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `each'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer/podfile_dependency_cache.rb:43:in `from_podfile'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:85:in `initialize'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:420:in `new'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:420:in `create_analyzer'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:232:in `resolve_dependencies'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:160:in `install!'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/command.rb:52:in `run'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
/Users/adminxd/.rvm/rubies/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'

**Comment by paulb777** [comment]
Likely a typo in the Podfile like https://github.com/CocoaPods/CocoaPods/issues/9881. Please review the syntax and post the Podfile here if you're still stuck.

**Comment by dnkoutso** [comment]
This is an invalid issue report.
