### ISSUE TITLE
"The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

### ISSUE THREAD

**Issue by nabeelkhalid1** [CocoaPods/CocoaPods#9997]
[ x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
1."Pod deintegrate"
2. "sudo gem install cocoapods-clean"
3. "pod clean"
4. "pod setup"
5. "pod install" 

## What did you expect to happen?
I expected pods to install properly so that I could test my app via xcode

## What happened instead?
These two errors arose:
https://files.slack.com/files-pri/TPAJ1SWEM-F019DBMGJAG/screen_shot_2020-08-20_at_11.59.13_am.png
and when I ran my project the output from xcode was "The sandbox is not in sync etc"

## CocoaPods Environment

ℹ Please replace these two lines with the output of `pod env`.
e.g. via `pod env | pbcopy`

No output

edit: fixed picture
![Screen Shot 2020-08-20 at 11 59 13 AM](https://user-images.githubusercontent.com/68078085/90796954-fdaf5f00-e2dd-11ea-92db-756e5c51e835.png)

**Comment by dnkoutso** [comment]
Can you please upload a sample app demonstrating the issue?

**Comment by nabeelkhalid1** [comment]
I was told I cannot upload a sample app due to issues with HIPPA as it is an application being used in the medical field. Is there any way I can supply you with more information without uploading the app?

**Comment by dnkoutso** [comment]
Unfortunately with the given information its hard for us to diagnose.

**Comment by nabeelkhalid1** [comment]
yep I see why, my apologies!
