### ISSUE TITLE
Could not archive a build from Xcode until I deleted the [CP] Prepare Artifacts script

### ISSUE THREAD

**Issue by alex-x-x-x-x** [CocoaPods/CocoaPods#9998]
# Report
I've had an issue for a while where I couldn't archive a build from Xcode until I explicitly removed the **[CP] Prepare Artifacts** script from the **Build Phases** section of my project and was able to successfully archive a build after doing so. 

My question is, is it _absolutely necessary_ to have the **[CP] Prepare Artifacts** script in my project? 

## What did you do?
Removed the **[CP] Prepare Artifacts** script from the project. 

## What did you expect to happen?
I wasn't sure what would happen but thankfully, I was able to archive a build. 

## What happened instead?
I successfully archived a build from Xcode version 11.6

## CocoaPods Environment
Currently running Cocoapods version 1.9.3 on my machine.

**Comment by dnkoutso** [comment]
@amorde didnt this script go away? Is it an artifact of the prior release that we can force 1.10 to always remove?

**Comment by amorde** [comment]
Yes but this report is based on 1.9.3

**Comment by alex-x-x-x-x** [comment]
@dnkoutso @amorde I'd also like to add that my colleague has been able to archive a build from Xcode with the script in the project this entire time. There's 0 to no difference between our Xcode configurations but I wonder if he probably hasn't ran `pod repo update` in quite some time (if ever) so that may be why he hasn't experienced any archiving issues. 

I'm obviously just speculating but would be curious to know what the clear distinction would be between his ability to successfully archive with the script and my inability to archive with the script in the project until I remove it..

**Comment by alex-x-x-x-x** [comment]
> I am not sure what the issue is then. @alex-x-x-x-x can you upload a sample app demonstrating the issue?

Yeah, sorry I can't do that. Perhaps I can provide some screenshots with redacted proprietary information?

**Comment by dnkoutso** [comment]
Maybe those will help but its hard to guess what is going on here with the current information. Help is needed from you to diagnose why.

Also try 1.10.0.beta which doesnt have this script phase and maybe this issue is no longer an issue.

**Comment by amorde** [comment]
There are some known issues with the prepare artifacts script that were fixed in the 1.10 beta. I'd highly recommend trying the beta.

**Comment by alex-x-x-x-x** [comment]
@dnkoutso @amorde  Fair, I'll try it out in a few hours with and without the build script and report back here.
If using 1.10.0 beta allows me to archive a build with the [CP] Prepare Artifacts script in the project, I'll comment and close the issue. Sound good?

However, it seems that the prepare artifacts script is of no issue for my colleague so I wonder how the bug skipped him considering he's running cocoapods 1.9.3..

**Comment by dnkoutso** [comment]
not sure either. Yes it should be OK to close if its fixed in 1.10.0.beta.

Betas in CocoaPods should be fine to archive. Its not like in Xcode where you cannot submit an archive from an Xcode beta.

**Comment by amorde** [comment]
Starting in 1.10 the `Prepare Artifacts` script no longer exists

**Comment by dnkoutso** [comment]
@alex-x-x-x-x thanks for the investigation here. I think we will close this for now given that 1.10 stable is about to ship. 

Please re-open this issue or a new one if 1.10 ships and you see problems.
